### PR TITLE
adds a new genetic power (Toxin Lover)

### PR DESCRIPTION
**Pull request by boodaliboo**
this adds a trait that gives the ability slime people have to heal from toxic chemicals and take damage from toxin healing chems to genetics
it currently has a instability of 35 and is decently rare
#### Changelog

:cl:  
rscadd: Added a new genetics power
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
Can this be added to the trait system too?

**Comment by boodaliboo** [comment]
> Can this be added to the trait system too?

quirk system?

**Comment by MegaEmpirical** [comment]
Isn't this already in virology?

**Comment by boodaliboo** [comment]
> Isn't this already in virology?

no

**Comment by boodaliboo** [comment]
> Isn't this already in virology?

the viro one just makes it so you heal from any chem in your system what so ever if you reach a threshold this makes it so you heal from toxic chems and take damage from toxin healing chems like charcoal

**Comment by CMOisLing** [comment]
There isn’t a virus symptom that heals you from any chem in your system

**Review by alexkar598 — APPROVED** [review]

**Comment by ShadowDeath6** [comment]
virology has symptoms that heal based on certain things, like starlight condensation

make sure this is human / lizard only so slimepeople and plasmamen can't get this

**Comment by boodaliboo** [comment]
this isnt a problem if either of them get it as when i asked earlier it did nothing if someone got a trait twoce

**Comment by boodaliboo** [comment]
> There isn’t a virus symptom that heals you from any chem in your system

toxin filter does

**Pull request merged**
