### PR TITLE
Fix disposals in several maps

### PR DESCRIPTION
**Pull request by monster860**
### Intent of your Pull Request

I did a review of the disposals

Box:
- Fixes Genetics-tagged packages getting stuck in the junction before the chapel office
- Fixes Chapel-tagged packages not going to the chapel
- Fixes anything with a HoP tag getting put in downstream of the HoP junction getting stuck in an infinite loop
- Fixes Chemistry-tagged packages ending up in the south area of medbay instead
- Fixes stuff being thrown in the Chem trash can ending up in the Captain's office
- Removes redundant sort junction for Atmos office

Delta:
- Removes several useless disposal pipes that are probably the artifact of bad copy-pasting in Disposals Maint
- Makes it so that stuff going into the Xeno and Viro trash cans *always* gets spaced instead of being a 50/50
- Fixes the Testing Range-tagged packages having a 50% chance of ending up in the Nanite lab instead 

Meta:
- Makes it so that stuff going into the Xeno and Viro trash cans *always* gets spaced instead of being a 50/50

Eclipse:
- Fixes the trash ending up in Primary Tool Storage 50% of the time
- Fixes Security and HoS office disposals not ending up in their proper place
- Fixes Tech Storage disposals not being hooked up
- Fixes Atmos disposals being tagged as RD office
- Fixes CE office disposals being tagged as RD office
- Fixes Engineering junction not being tagged
- Fixes Genetics being tagged as Library
- Fixes CMO office being tagged as Genetics
- Fixes Toxins being mislabeled as RD office, as well as misaligned pipe

OmegaStation:
- Nothing here, because Omega uses virgin tree-disposals instead of chad loop-disposals, which is much more difficult to make mistakes, but doesn't support mailing at all :(

This isn't bloody rocket science

#### Changelog

:cl: monster860 
fix: Fixes several disposals issues
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
muh trash pipes finally gettin some love 10/10

**Comment by JamieD1** [comment]
@wejengin2

**Comment by patpol4** [comment]
Pretty cool, will look through this once random maint is merged

**Comment by patpol4** [comment]
This is going to be super difficult trying to fix the conflicts on this one with the way mapdiff bot generates previews but I'll try not to miss anything

**Review by patpol4 — APPROVED** [review]
This also introduces https://github.com/yogstation13/Yogstation/pull/9884 due to a bug, should be good to merge now.

**Pull request merged**
