### PR TITLE
Removes shitcode operator

### PR DESCRIPTION
**Pull request by Hopekz**
This has no reason to exist.

### CODE REVIEW

**Review by JamieD1 — APPROVED** [review]

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Fix the operator instead of removing it, its there to ensure you can cancel out of a mass modify

Also your change would break mass modify

**Comment by Hopekz** [comment]
> Also your change would break mass modify

!new_value == null can never be true.
The fix is to remove it.

Because of !new_value == null you can never satisfy condition nr. 2 in the argument (circled)
image

This whole if statement can be simplified down to !class if you want because the second portion literally cannot happen at the moment before this removal.

**Comment by Hopekz** [comment]
> > Also your change would break mass modify
> 
> !new_value == null can never be true.
> The fix is to remove it.
> 
> Because of !new_value == null you can never satisfy condition nr. 2 in the argument (circled)
> image

This whole if statement can be simplified down to !class if you want because the second portion literally cannot happen.

**Comment by alexkar598** [comment]
Your PR makes it so that any mass modify that tries to set it to something thats is not VV_NULL will fail

**Pull request closed without merging**
