### PR TITLE
Maxcap fireball bus

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

adds a unobtainable fireball spell which shoots a fireball that maxcaps

### CODE REVIEW

**Comment by Marmio64** [comment]
fireball bus? Bus as in adminbussing?

**Review by Hopekz — CHANGES_REQUESTED** [review]
A better description for everyone else, please.

**Comment by ynot01** [comment]
> A better description for everyone else, please.

Maxcap fireball bus

**Comment by boodaliboo** [comment]
add a descrption

**Comment by athena413** [comment]
description

**Comment by ynot01** [comment]
description added

**Comment by boodaliboo** [comment]
iits unobtaINABLE WHY NOT

**Comment by gar4** [comment]
It's a bad idea because half of the staff is incapable of keeping themselves from pressing buttons. One of them is going to go "hurr event time" then give themselves godmode and run around shooting people with this.

**Comment by ynot01** [comment]
apparently turdis doesnt like my branch and i dont care enough to fix it

**Pull request closed without merging**
