### PR TITLE
adds oxygen to tower caps and allows the chemical godsblood to be created

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
if you combine omnizine and earthsblood you make godblood which is omnizine with a much higher overdose rate.

also adds oxygen reagant to tower caps

this is a webedit
#### Changelog

:cl:  
rscadd: new chemistry recipe and adds oxygen reagant to tower caps
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
This man is drunk

**Comment by boodaliboo** [comment]
> This man is drunk

you are drunk

**Comment by boodaliboo** [comment]
> > This man is drunk
> 
> you are drunk
i need to add more botany thing

**Comment by Rayisken** [comment]
Why do we need a 3rd Omnizine like? Earthsblood is already supposed to be the upgraded omnizine

**Comment by boodaliboo** [comment]
Godsblood already existed and this is to prevent super healing plants but not by removing omnizine or earthsblood

**Comment by Rayisken** [comment]
goddammit TG

**Comment by boodaliboo** [comment]
merge when

**Pull request closed without merging**
