### PR TITLE
Psychotic brawling now worth being in the uplink as intended

### PR DESCRIPTION
**Pull request by milk-is-cool**
Psychotic Brawling:
Reverted to what it was pre-nerf. This was the version of psychotic brawling that was approved by the balance council to be added via the granter. It is already one of the weaker martial art as it is not a guaranteed win in a 1v1 situation unlike the other martial arts with combos. The issue is that it should ignore armor because it is **not** a guaranteed 1v1 win. If anything it needs to be buffed in order to align more with the other martial arts in that aspect, but getting it back to baseline is a good starting point.

Uplink Items:
The path names for the rapid syringe gun and the psychotic brawling notes were the exact same (unintentionally) which caused the psychotic brawling notes to be the only thing that appears in the role-specific uplink items for the respective roles. This just gives the psychotic brawling notes the correct unique path name so it does not do any overwriting.

:cl:  
bugfix: Rapid syringe gun now exists in the uplink like it was supposed to
tweak: Psychotic brawling reverted to what it was pre-nerf so it is uplink worthy
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
tweak: psychotic brawling now has 100 AP on all attacks

**Comment by Moltijoe** [comment]
buffing psychotic brawling a different way rather than reverting a nerf is probably better

**Comment by milk-is-cool** [comment]
> tweak: psychotic brawling now has 100 AP on all attacks

this is not out of the ordinary for a martial art i dont understand why this is even an issue. Almost every other martial art has 100AP on all attacks and the attacks that dont have 100AP dont need it anyway. Please tell me why you think it needs to not be 100AP so i can at least try to see where you are coming from.

**Comment by milk-is-cool** [comment]
> buffing psychotic brawling a different way rather than reverting a nerf is probably better

i agree but thats beyond my coding ability and im not going to wait for someone else to never do it

**Comment by Moltijoe** [comment]
> i agree but thats beyond my coding ability and im not going to wait for someone else to never do it

give me some ideas and i'll code it for you

**Comment by milk-is-cool** [comment]
> > i agree but thats beyond my coding ability and im not going to wait for someone else to never do it
> 
> 
> 
> give me some ideas and i'll code it for you

I'll think about it today and get back to you with any ideas I come up with when I get home from work

**Comment by Mqiib** [comment]
Not all martial arts have 100 AP on all attacks. I know specifically the ones I designed respect armor, and any others that don't are entirely because whoever coded them didn't bother to consider armor. That doesn't mean they SHOULD have 100 AP, it just means they happen to have 100 AP. Psychotic brawling is no exception, plus I GAVE it 20 AP anyways.

**Comment by milk-is-cool** [comment]
this is so scuffed, no clue how i even managed to do this just now

**Comment by Bibby0110** [comment]
Redo your PR, don’t do it on the master branch of your fork

**Pull request closed without merging**
