### PR TITLE
Changes Utatul's donor item to be more unique.

### PR DESCRIPTION
**Pull request by ghost**
# Github documenting your Pull Request
 **Untested, webedited..**

@Anvilman6 requested I snowflakeify their donor plush, so I'll do it. Why not give the best person in the server a slightly more unique plushie?

# Wiki Documentation
Nothing needed to document, this only adds a snowflake Azeel plushie that has a slightly extended description.

# Changelog

:cl:  
rscadd: makes utatuls donor item more unique by giving a slightly different description
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
LINTER WHAT THE FUCK WENT WRONG

**Comment by Mqiib** [comment]
Missing a " at the end of the description, and you might need to do \\" to make it not mess up the U.A. part

**Comment by ghost** [comment]
I'll fix it, give me a minute.

**Comment by ghost** [comment]
Fuck you too, linter.

**Comment by ghost** [comment]
Love you, linter.

**Comment by Cartlord** [comment]
will it have Authentic Azeel Noises(TM) when used inhand?

**Comment by ghost** [comment]
> will it have Authentic Azeel Noises(TM) when used inhand?

When I get Anvilman to make lizard noises to a microphone.

**Pull request merged**
