### PR TITLE
Readds Sec Budget Card in Armory

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request

To be used for emergencies.

The only budget card that actually makes sense, both for fines & buying weapons/mindshields

#### Changelog

:cl:  
rscadd: Budget cards have been added to all NT Armories
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Good PR, speedmerge

**Comment by MegaEmpirical** [comment]
Add service budget card too you savage.

**Comment by Hopekz** [comment]
If we're slowly going to revert this change 1 feature at a time we can just go ahead and revert the whole thing to get everything back to normal.

**Comment by Bibby0110** [comment]
> Add service budget card too you savage.

No? This budget card is being added so sec has a bit of an easier time during nukeops/conversion antags



> If we're slowly going to revert this change 1 feature at a time we can just go ahead and revert the whole thing to get everything back to normal.

See above, basically a bandaid fix until me and Jamie finish our rework :)

**Comment by Hopekz** [comment]
> :)

(:

**Review by patpol4 — APPROVED** [review]
Map fine

**Pull request merged**
