### PR TITLE
Crystal Foam Icon Fix

### PR DESCRIPTION
**Pull request by airlines7**
## The gist
issue #19193 said there was no icon at all for the crystal, all I've done is copy and paste the n2o crystal sprites in place of the missing sprites. Thought I'd give it a try to fix something.

# Spriting
Felinid for scale
image

# Changelog

:cl:  
bugfix: Crystal foam is no longer invisible
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Is it possible theres already a sprite somewhere, its just not being pointed to correctly?

**Comment by airlines7** [comment]
> Is it possible theres already a sprite somewhere, its just not being pointed to correctly?

I checked atmos.dmi and did a quick skim of the obj folder and found nothing.

**Comment by tattax** [comment]
it was ported directly from tg where an icon does exist

**Comment by tattax** [comment]
image

**Comment by airlines7** [comment]
> image

lemmie steal that real fast then...

**Comment by airlines7** [comment]
New sprite, felinid for scale.
image

**Review by cuackles — APPROVED** [review]

**Pull request merged**
