### PR TITLE
Adds a mutation that gives radiation immunity

### PR DESCRIPTION
**Pull request by Moltijoe**
35 instability to get radiation immunity, comparable to the adaptations when you factor in their downside

makes you take more damage from toxin to counteract it removing one of the most annoying sources of toxin damage

:cl:  
rscadd: Radproof mutation
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Should be incompatible with bone marrow and thick skin.

**Comment by Moltijoe** [comment]
> Should be incompatible with bone marrow and thick skin.

huh? why? those are directly combat related, this isn't

**Comment by wonderinghost** [comment]
I mean kinda. The rad bolts on the syndicate hard light bow

**Comment by Moltijoe** [comment]
> I mean kinda. The rad bolts on the syndicate hard light bow

Thats niche enough that its not comparable to thick skin or bone marrow

**Comment by LassiH** [comment]
jellypeople be smiling at this

**Review by ToasterBiome — APPROVED** [review]
Can you make it give like 95% resistance instead? Sounds like a really easy way to kill a bunch of people by getting 999999 rads.

**Comment by Moltijoe** [comment]
> Can you make it give like 95% resistance instead? Sounds like a really easy way to kill a bunch of people by getting 999999 rads.

Rad resistance might as well be binary, either its 100% and youre fine, or its not 100% and youre dying to radiation.
Also, if that was a problem, other species would do that without needing a genetic mutation

**Pull request merged**
