### PR TITLE
[s] Adds portal gun

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

not a rick and morty reference

### CODE REVIEW

**Comment by Runian** [comment]
can you shoot the gun?

**Comment by AMyriad** [comment]
HD does as HD wants but imma be real I'm not a fan of how ye got it looking
image

<details><summary>Critique if ye care:</summary>
<p>
- No animation; this is a downgrade
</p>
<p>
- Bad/2D perspective
</p>
<p>
- Bad shading, very simplistic blocky sprite
</p>
<p>
- Colors are very stark white even for what you're trying to go for, not good for the eyes
</p>
</details>

**Comment by JamieD1** [comment]
This TM only or is it for the memes or is it serious

**Review by cuackles — APPROVED** [review]

**Comment by JamieD1** [comment]
Waiting for @ToasterBiome to make it a small chance to replace

**Comment by JohnFulpWillard** [comment]
Wait do we not have the actual portal gun

**Comment by ToasterBiome** [comment]
ill wrap back around to this later

**Pull request closed without merging**
