### PR TITLE
Adds a new variation to Fore Maint: The Drone Hole

### PR DESCRIPTION
**Pull request by maxion12345**
basically I wanted drones to be more prevalent. they are pretty underused as it is and are a fun ghost role if someone bothers to make them. Now there is a chance for 2 drone shells to spawn, and of course, the drones can make more drones. 

:cl:  
rscadd: Adds new fore maint variation: The Drone Hole, with two drone shells
/:cl:

### CODE REVIEW

**Review by alexkar598 — APPROVED** [review]

**Comment by alexkar598** [comment]
Im a bit concerned about having roundstart drones on the station

**Comment by Partheo** [comment]
pics reeee

**Comment by Moggram** [comment]
get me them pics man

**Comment by maxion12345** [comment]
ah fuck i did forget pics one sec yall

**Comment by maxion12345** [comment]
> Im a bit concerned about having roundstart drones on the station

I find drones are underused in their current form, with little people probably even knowing how to make them. I'd love to figure out a way to give drones a makeover to fix some bugs such as them missing their first law, and all quality of life changes like the revive doing a pop-up similiar to defibbing.

**Comment by Marmio64** [comment]
i like drones but they're super annoying. I'm biased but they tend to steal my shit, ive seen them replace lights during sling rounds, helping fuck them over, and having a mini machine capable of fixing any breaches you cause as a traitor in seconds is really infuriating especially considering its so hard to kill them when they can run under doors. This will only be worse since they'll roundstart and you cant really do anything to stop them unless you want to toss them in space.

**Review by patpol4 — APPROVED** [review]
Reduced the amount of drones to 1 and renamed the bed. Map is fine, let's give this a try.

**Pull request merged**
