### PR TITLE
Removes Lag

### PR DESCRIPTION
**Pull request by JamieD1**
Removes Lag

#### Changelog

:cl:   
rscdel: Removes Laggy 4 way pipes
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Im not sure that the *4 way* heat exchange pipe is causing the lag, if heat exchange pipes are causing lags, its probably the heat exchange part of it, not the 4 way

**Comment by JamieD1** [comment]
> Im not sure that the _4 way_ heat exchange pipe is causing the lag, if heat exchange pipes are causing lags, its probably the heat exchange part of it, not the 4 way

Nope its shitty engineers being lazy doing this every round:

image

**Comment by patpol4** [comment]
Doing it this way halves the amount of time it takes to make a cooling loop and it works

**Comment by CMOisLing** [comment]
Honestly make heat pipe more effective so we dont need to spam so many of them

**Comment by MegaEmpirical** [comment]
Those lazy fucks, I know what I must do: burn them. If they're all banned, I can keep my pipes.

**Comment by jcatjmeow** [comment]
Redstone pipes when?

**Review by Hopekz — CHANGES_REQUESTED** [review]
Better title

**Comment by JamieD1** [comment]
I will be back

**Pull request closed without merging**
