### PR TITLE
New donator item for Cark

### PR DESCRIPTION
**Pull request by Moltijoe**
New cark donator item
it's a toggleable "hoodie"

item, sleeves down, sleeves up
image

:cl:  @cuackles @Moltijoe 
rscadd: Adds new donator item for Cark
imageadd: adds sprites for Cark's donator item
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
what country is this

**Comment by CrazyDrakkon** [comment]
> 

noone tell them

**Comment by Moltijoe** [comment]
> what country is this

no clue, very patriotic though

**Review by ToasterBiome — APPROVED** [review]
still don't know what flag this is

**Comment by adamsong** [comment]
So this is making cark's existing item (the bedsheet) no longer obtainable, and adding a new item locked to cark, in its place?

Is the intent for someone in future to be able to use this for other purposes, or if someone opens a pr that uses it, will it get shot down because "that used to be cark's item" because if the latter is the case, I would prefer the item removed entirely.

**Comment by Moltijoe** [comment]
> So this is making cark's existing item (the bedsheet) no longer obtainable, and adding a new item locked to cark, in its place?
> 
> Is the intent for someone in future to be able to use this for other purposes, or if someone opens a pr that uses it, will it get shot down because "that used to be cark's item" because if the latter is the case, I would prefer the item removed entirely.

Nah, this is a 2nd donator item, it gives them a box
Were the bedsheet to be removed as a donator item id just incorporate it into the game

**Comment by adamsong** [comment]
Under the new policy, each person is only allowed one donator item

**Pull request closed without merging**
