### PR TITLE
Adds more, useful crocs, as well as fixes the improper wear sprite of fire crocs.

### PR DESCRIPTION
**Pull request by Leatherturtle**
Magcrocs, and jackcrocs for sec and engineering.

#### Changelog
:cl:
rscadd: Added new crocs 
wip: I barely know what I am doing, so this is definitely work in progress.
tweak: tweaked fire crocs wear sprite
imageadd: added some icons and images  

/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
sure

**Review by nesisknesis — CHANGES_REQUESTED** [review]
Denying this PR for the absurdity of it.

Magcrocs and Jackcrocs seem like a meme that will dry out very quick. The sprites also low quality. In future, if you run by them in #spriting in the discord we can give feedback. 

You also appear to have changed multiple other sprites without documenting it.

As for clown crocs, this can be considered but because they're in this PR, cannot be merged.

For this PR to be merged, the above denied features need to be removed, as do the undocumented changes. Then, the fix involved with this PR can be merged without needing to make another one.

**Comment by Hopekz** [comment]
I think Idinuum meant to close this PR but didn't. 

IMO open up the clown crocs under a different PR like ident said and if you have any additional changes make sure to document them.

So sad the ridiculous crocs don't "fit" ):

**Comment by Hopekz** [comment]
Miscommunication. Thought Ident meant for this PR to be closed

**Pull request closed without merging**
