### PR TITLE
Adds the Nanotrasen Mental Health Room

### PR DESCRIPTION
**Pull request by maxion12345**
# Github documenting your Pull Request

Adds a small box in the corner of the station dedicated to employee mental health. This takes the place of the rows of air pumps and scrubbers that nobody ever uses ever.

# Wiki Documentation

update locker room image

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added a mental health box in the locker room for employees to practice mental health
rscdel: no more spare air pumps and scrubbers in the locker room. wasn't like you guys used them anyways.
/:cl:

### CODE REVIEW

**Comment by Anvilman6** [comment]
Shouldn't the Psych office already be the Amazon Death Box room on the station?

**Comment by maxion12345** [comment]
> Shouldn't the Psych office already be the Amazon Death Box room on the station?

no, it's far too big for an amazon death box and has windows
its also used by an actual mental health professional, assistants won't get those. assistants get the mental help box with a bible and a plant.

**Review by patpol4 — COMMENTED** [review]
Feels like pointlessly taking up way too much space for a meme

**Comment by Moggram** [comment]
Its true that the air pumps are almost useless, but the scrubbers are useful. If anything the air pumps should be changed out for AC units.

**Comment by UselessTheremin** [comment]
dont remove the damn scrubbers

**Comment by patpol4** [comment]
we lose more than we gain from this

**Pull request closed without merging**
