### PR TITLE
Footwraps are now craftable.

### PR DESCRIPTION
**Pull request by ghost**
# Github documenting your Pull Request
**Untested, webedited.**

@Anvilman6 wanted craftable footwraps. This would be good for ashwalkers so they won't get fucked over by a shard of glass or a cactus. More ways to obtain clothing items is nice.

# Wiki Documentation

**Three leather to craft.** Clothing category.

# Changelog

:cl:  
rscadd: footwraps are now craftable with 3 leather
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
Today I will apply Wirecutters to a bedsheet and completely nullify a racial nerf

**Comment by Marmio64** [comment]
your description says 3 leather to craft but the code says 3 cloth, maybe you'd like to fix that?
edit: also, chitin and bone armor protects the feet from sharp objects so ashwalkers already have the ability to be immune to glass, this is unneeded

**Comment by maxion12345** [comment]
Even if it was leather, you can rush the garden plants and shit out three leather roundstart iirc

**Comment by ghost** [comment]
> your description says 3 leather to craft but the code says 3 cloth, maybe you'd like to fix that?
> edit: also, chitin and bone armor protects the feet from sharp objects so ashwalkers already have the ability to be immune to glass, this is unneeded

How did I overlook this? I'm a massive dumbass so that might be why. Thank you.

> Even if it was leather, you can rush the garden plants and shit out three leather roundstart iirc

They're in vending machines, don't see much of a problem.

**Comment by ghost** [comment]
> your description says 3 leather to craft but the code says 3 cloth, maybe you'd like to fix that?
> edit: also, chitin and bone armor protects the feet from sharp objects so ashwalkers already have the ability to be immune to glass, this is unneeded

Good point.

**Pull request closed without merging**
