### PR TITLE
removes sandbox gamemode

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

I haven't gone and checked, but I am honestly willing to bet that this gamemode hasn't been run more than 10 times in the last 3 years.

#### Changelog

:cl:  
rscdel: sandbox is gone
/:cl:

(I bet most of you didn't even know this gamemode existed)

### CODE REVIEW

**Comment by boodaliboo** [comment]
I’m fine with this as most admins if they run events will just use extended

**Comment by Nickvr628** [comment]
Does extended trigger all the station goals like sandbox does?

**Comment by Amelia0010** [comment]
Sandbox does not trigger all 3 station goals, extended does. Sandbox gives everyone what is essentially creative mode.

**Comment by Hopekz** [comment]
I use this gamemode when I perform tests for my PR.
More of a "Dev mode" you're removing here since we don't actually use this in-server.

**Comment by Amelia0010** [comment]
why on god's green earth do you use sandbox for testing your PRs and not extended?

**Comment by ThatLing** [comment]
i knew sandbox existed!

**Comment by Hopekz** [comment]
> why on god's green earth do you use sandbox for testing your PRs and not extended?

Because I don't know any better and I get convenient building tools built-in. I'm not against removing this mode just telling you that some people might use this outside of the use that you see.

I went ahead and copied over the sandbox code to a separate sandbox branch that I will now use for testing so whatever happens to this feature is irrelevant for my use-case.

If you don't want any future people using sandbox instead of extended like myself just remove it so that everyone conforms to the way you like to play the game.

**Comment by Amelia0010** [comment]
Mane, it's not about making everyone conform to the way I like to play the game, it's about sandbox being made for a purpose which it doesn't serve here. 

We don't run creative "everyone gets to spawn whatever they want" gamemodes, which require you to have an integrated part of a gamemode just for letting people spawn things in, without giving people admin perms. 

I also had never even thought of it as being remotely useful for testing, since you're the first person I've ever heard of using this instead of extended + game panel. I recommend that you use the latter since game panel actually allows you to search rather than type in full typepaths, allows you to choose how many of each to spawn, and doesn't have a blacklist of things you're *not* allowed to spawn. 

Either way, it's not about forcing others to conform, it's about not having unused gamemodes lying around that are never run, and which serve no practical purpose

**Pull request merged**
