### PR TITLE
Updates Decals and signs to all match the correct yellowness that should be provided under law #103 RGB Yellow RGB code = 255*65536+255*256+0 

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
strips and signs have been updated to accommodate the new state law of yellow that is being introduced to help liberate the eyeballs of crew and scum alike.

If you are colorblind then nothing has changed for you.

If you are not then get ready to start licking the floor.

I'm dead ass, get on the fucking ground and stick your tongue out I am not playing games...

# Spriting
197683278-f5acd3fa-af1f-465c-9c3c-5c09c7849f15
yellow2

# Wiki Documentation
Color-wheel 

# Changelog

:cl:  

imagedel: Black and yellow black and yellow black and yellow black and yellow!

/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
whats different

EDIT: signs look significantly worse

**Comment by KillerOrcaCora** [comment]
> whats different
> 
> EDIT: signs look significantly worse

Matched caution strips with the same yellow disposals was using, slapped it on signs for fun

**Comment by cuackles** [comment]
> > whats different
> > EDIT: signs look significantly worse
> 
> Matched caution strips with the same yellow disposals was using, slapped it on signs for fun

i gotta go with biome here the sings looked better with the original color as they seem more clear and vibrant and have more added shading
diff
going from what the iconbot said the upper one are the older ones, tho i have to say that the one with the dude does look better with the more vibrant yellow

**Review by cuackles — CHANGES_REQUESTED** [review]
so like revert the sings version to the older versions except the one with the dude pretty please

**Comment by KillerOrcaCora** [comment]
Sure thing

**Review by cuackles — APPROVED** [review]

**Comment by ToasterBiome** [comment]
i approve

**Comment by Cartlord** [comment]
Cora, please take your meds.

**Comment by KillerOrcaCora** [comment]
Meds? the party is just getting started...

**Pull request merged**
