### PR TITLE
sterilizer spray no longer causes toxin damage

### PR DESCRIPTION
**Pull request by SomeguyManperson**
dumb as hell

### What general grouping does this PR fall under? 
med

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 
probably not documented anywhere but space cleaner deals like 1 toxin damage and sterilizer used to but now does not do that

# Changelog

:cl:  
tweak: sterilizer spray will no longer cause toxin damage
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Task linked: [CU-jf20ee Sterilizer increases success chance, not really useful, deals toxin damage https://github.com/yogstation13/Yogstation/pull/10846](https://app.clickup.com/t/jf20ee)

**Review by redmoogle — APPROVED** [review]
if this somehow bugs out I'd be impressed, but this is byond

**Comment by alexkar598** [comment]
image

**Comment by alexkar598** [comment]
Task linked: [CU-jf21vn Sterilizer deals toxin damage, making it kinda useless](https://app.clickup.com/t/jf21vn)

**Comment by alexkar598** [comment]
I swear to god, how do i disable these alerts

**Comment by redmoogle** [comment]
@alexkar598 
image

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
