### PR TITLE
Revert "Ate without table"

### PR DESCRIPTION
**Pull request by Mqiib**
Reverts yogstation13/Yogstation#19357

Doesn't work properly, just makes you sad whenever you eat food regardless of table location.

### CODE REVIEW

**Comment by ynot01** [comment]
Sounds like someone ate without table

**Comment by neeshacark** [comment]
functions just like rimworld, bless

**Comment by adamsong** [comment]
Fix it then?

**Comment by Mqiib** [comment]
> Fix it then?

Maybe make sure new features actually work?

**Comment by adamsong** [comment]
Should be a bugfix, not a full revert

**Pull request closed without merging**
