### PR TITLE
replaces all hermit seeds with plants native to lavaland except towercap

### PR DESCRIPTION
**Pull request by boodaliboo**
makes more sense as the hermit made the shelter already on lavaland
tower cap is kept so you can make mortar and pestle to make medicine
#### Changelog

:cl:  
tweak: changed seeds
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
But reishi, Plump-helmets and Liberty-cap are all mushrooms. They can be found on lavaland if you make alot of dirt piles and this is just a time delay.

**Comment by boodaliboo** [comment]
> But reishi, Plump-helmets and Liberty-cap are all mushrooms. They can be found on lavaland if you make alot of dirt piles and this is just a time delay.

what would you be doing with any of these, i dont really care if they get them but this makes more sense and a majority are edible

**Comment by Moggram** [comment]
>
> what would you be doing with any of these, i dont really care if they get them but this makes more sense and a majority are edible

Plump-helmets is used for food or be distilled into The Manly Dorf.
Glowshroom is for light.
Reishi is a God-tier plant on lavaland if you are a ashwalker or hermit. It has both charcoal and morphine in it. This is the only way to get something that heals toxin damage whit out killing/help from the miners. Also the morphine in it will let you run at full speed if you are hurt.

**Comment by Marmio64** [comment]
> > what would you be doing with any of these, i dont really care if they get them but this makes more sense and a majority are edible
> 
> Plump-helmets is used for food or be distilled into The Manly Dorf.
> Glowshroom is for light.
> Reishi is a God-tier plant on lavaland if you are a ashwalker or hermit. It has both charcoal and morphine in it. This is the only way to get something that heals toxin damage whit out killing/help from the miners. Also the morphine in it will let you run at full speed if you are hurt.

i added a reagent a while ago that you can make called 'capmix' that can be made with lavaland ingredients and will fix toxins.

**Comment by Moggram** [comment]
> i added a reagent a while ago that you can make called 'capmix' that can be made with lavaland ingredients and will fix toxins.

Did not know that.

**Review by patpol4 — APPROVED** [review]
ho boy we're going tribal

**Pull request merged**
