### PR TITLE
Ruin asteroid medbay even more

### PR DESCRIPTION
**Pull request by airlines7**
# Description
## Main change

- Removed the 2 tile hallways splitting the surgical bay and treatment room and flipped it to the surgical bay is now on the right and not the left. This makes the main med hall much more open as well as the treatment room. Added an entrance and exit doors for the treatment center as well.

image
## Significant Changes

- Medical Storage is now right under the treatment room with easy access to all medical supplies, the airlocks are timed to 3 seconds instead of 15.

image

- Medical Breakroom is now called Medical backroom (only just to utilize the medical backroom turf) because its no longer attached to the Medical storage and instead connected to surgery and paramed office. Cryo cell oxygen is also setup there now.

image

## Minor Changes
In no particular order
- Drink, coffee, and snack vending machines are added to the breakroom.
- There is a "Surgical Handwashing Station" in surgery now to appease the germaphobes.
- Medical maintenance entrances are now in surgery and the breakroom.
- There are "Triage Shutters" to block off the primary hallway from the treatment center that might cause a doctor to lose focus.
- Shower is in a little hole in the wall in the treatment center.
- There is now a disposals chute in the treatment center.
- Medical storage does not have windoors for holding the medkits, they are just in the open.
- slight style change with the decals and floor using the slimmer line decals for the paramed room, breakroom, surgical room, treatment room, and medical storage.
- There are now fire alarms in every medical room changed.
- Treatment room and breakroom both have a centralized fire extinguisher.
- Treatment center has a public surgery bay, now with privacy curtains!
- Blood crate is no longer in the open and now in med storage.
- Flipped the position of med hallway fire/emergency lockers and chairs to align with surgery.
- There is now a stack of 3 roller beds in the breakroom.
- There is one less medicine locker in the medbay, there is now one.

### Full picture of the new layout
image

### Picture of Turf layout
image

# Why did I make this?
Currently asteroid medbay has a serious case of high traffic areas being jammed with people, specifically that two tile hallway leading to surgery and treatment. The surgery bay from my observation is rarely used for any surgeries. My solution was to get rid of that gap and place the treatment center closer to the front entrance. This removes that jammed high traffic place, as well as have surgery next to medical once more.
Med storage was moved next to the treatment center instead of through the break room to help have faster access to medical supplies.
TL;DR this layout just streamlines getting into the treatment center.
 
# Changelog

:cl:  Airlines7
mapping: Ruined Asteroid Medbay
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image

It should not have this many changes oml

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
1. Make the trim size match, we'll shorten all the trims in one go.
2. all the maint doors can just have a trim stripe across the door, no need to have them in the corner. 
image
3. blinds not needed
image 

4. very far away 
image 
5. no maint access directly to the med area
6. this door is directly in front of some maint firelocks
image
7. cryo stuff is really far away
image

Overall I like the design layout of it where each room is, maybe not the surgery room in the middle, but there's a lot of problems in each individual room.

**Comment by airlines7** [comment]
> Make the trim size match, we'll shorten all the trims in one go.

Do you want me to do all of asteroid?
If so I'll open a new PR for that, its gonna take a hot minute.

also how is this, flipped and flopped the stuff around and made surgery 6 tiles smaller.
image

**Comment by ToasterBiome** [comment]
> Do you want me to do all of asteroid? If so I'll open a new PR for that, its gonna take a hot minute.

Nah

> also how is this, flipped and flopped the stuff around and made surgery 6 tiles smaller. image

seem fine

**Comment by airlines7** [comment]
oops

**Comment by airlines7** [comment]
don't merge yet something is sussy with the coding. I blame github.

**Comment by airlines7** [comment]
I'm gonna close and reopen as a new pull seeing as map diff icon is having a stroke and I can't find an issue

**Pull request closed without merging**
