### PR TITLE
Reinforced cap's shitter

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request
Makes the cap's shitter have rwalls and require cap access

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
tweak: Reinforced cap's shitter
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
Rwalls are cool. But door is dumb. Caps gonna lock himself in the toilet when he goes to take a shower

**Comment by Hopekz** [comment]
#11966 does this too.

**Comment by adamsong** [comment]
This atomizes that change

**Comment by Hopekz** [comment]
> This atomizes that change

Okay. 

Just remember that by choosing to touch the same file and area at the same time for some reason you're guaranteeing that either you or he have a map merge conflict. 
If you plan to merge your PR first because you believe it is a smaller change then it is going to be nasty for him since his has lots of changes all around the yogstation map.

**Review by patpol4 — COMMENTED** [review]
I really dont think the door access is a good idea, you usually take your pants off when you go to the toilet.

**Comment by Anvilman6** [comment]
If you'd atomize the wall reinforcements and door access, it would probably garner more individual support

**Comment by adamsong** [comment]
> you usually take your pants off when you go to the toilet.

This is true, but I usually remove them after entering the toilet

**Comment by JamieD1** [comment]
> I really dont think the door access is a good idea, you usually take your pants off when you go to the toilet.

Do you take your pants off before you walk into the bathroom? 

That feels a bit awkward if you had other people round. What if there are people waiting outside? 🤔

**Comment by patpol4** [comment]
Yes but it goes into his bedroom, that should be secure on its own. You already reinforced this a lot, i just think door access is overkill

**Review by patpol4 — COMMENTED** [review]
The airlock access is power creep imo. 
Hell, all of this is power creep, there are supposed to be weak spots, I don't even know what the intent behind this is

**Comment by Hopekz** [comment]
> The airlock access is power creep imo.
> Hell, all of this is power creep, there are supposed to be weak spots, I don't even know what the intent behind this is

A better PR died for this
image

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
