### PR TITLE
Makes most cardboard special containers fold-able

### PR DESCRIPTION
**Pull request by Hopekz**
image
image
image

This makes 7 more box types foldable when empty just like regular cardboard boxes.
**This includes all cigarette packs as well.**

This also effects not so common boxes such as the heart-shaped box

Also closes:
https://forums.yogstation.net/index.php?threads/pre-rebase-feature-folding-donut-boxes-into-cardboard.20336/ (thanks Lyis for the updated link)

TODO:
- [x] resolve the omega station merge conflict

#### Changelog

:cl:  Hopek
rscadd: Makes 7 types of different special cardboard containers foldable such as Donut boxes, Cigarette boxes, egg boxes etc.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Tested. Runs fine.
Needs to resolve this merge conflict because Omega station is being dumb

**Comment by overlord12345** [comment]
But can you craft it back into the special containers

**Comment by Jarod1200** [comment]
What is the control to fold it?

**Comment by MegaEmpirical** [comment]
And this: https://forums.yogstation.net/index.php?threads/pre-rebase-feature-folding-donut-boxes-into-cardboard.20336/

**Comment by boodaliboo** [comment]
unbalana ced op removes

**Comment by Hopekz** [comment]
> And this: https://forums.yogstation.net/index.php?threads/pre-rebase-feature-folding-donut-boxes-into-cardboard.20336/

Nice catch. 
Sorry late-night light night



> But can you craft it back into the special containers

No. 
Crafting them back into special containers is outside the scope of this PR IMO.
I did not touch any of the crafting code besides to make special boxes a child of box.

**Comment by MegaEmpirical** [comment]
We could pre-rebase, maybe look at that code?

**Comment by Hopekz** [comment]
> We could pre-rebase, maybe look at that code?

Not sure as I didn't look at pre base for this PR this is my own solution.
I accomplish what I set out to do if someone wants to make them craft-able that would have to be a separate PR as it is outside the scope of this PR at the moment.

This PR adds the folding function to these boxes.

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Candleboxes still cant be folded with this change as they return on attack_self

**Pull request merged**
