### PR TITLE
Fuck fucking slips mk2. git collectors edition

### PR DESCRIPTION
**Pull request by Jc1469**
Git was being a real bitch, guess thats what happens when your git is years old on a formatted partitioned HDD.

untested with the yogstation crap but hey, it should work right

#### Changelog

:cl:  
bugfix: You now might actually probably perhaps slip and bang your head on the floor and get stunned when you slip, as intended.
/:cl:

### CODE REVIEW

**Comment by Oakboscage** [comment]
Fucking neat

**Comment by Jc1469** [comment]
wheres the fun tag.  maintainer is biased

**Comment by Jc1469** [comment]
Also controversial if this was TG maybe. fuck tg though.

**Comment by Altoids1** [comment]
"Controversial" also means "No HC or maintainer wants to merge this"

**Comment by Jc1469** [comment]
Well. The only flaw I see with this is that the floor cluwne becomes more deadly. But considering the new players and the fact that already nobody ever kills the floor cluwne, I don't think anything has actually changed in regards to that.

**Comment by oklews** [comment]
Please merge this, I NEED IT, run a community vote or something!

**Comment by Ratvar** [comment]
Community votes are bad because they do not reflect what's good for the game, just what people want
That you need a community vote at all to justify something means there's no reason to add it

**Comment by HomocidlePancakes** [comment]
https://www.youtube.com/watch?v=C5I6YoSy4j0

**Comment by Jc1469** [comment]
You say that, but this not being merged because the headcoders don't want to. Not because there needs to be a vote.

**Comment by HomocidlePancakes** [comment]
>Community votes are bad because they do not reflect what's good for the game

Sorry. But not all decisions are black and white, so your argument that "cumunity vot ALWAYS bad" is invalid.

**Comment by Ratvar** [comment]
Headcoders don't want to merge this because they have no reason to merge it, yes.
Good thing I didn't say community votes are ALWAYS bad, and very good you didn't provide a reason to readd slips while you are at it

**Comment by HomocidlePancakes** [comment]
Oh shit I completely forgot this was a thing

1)Is this PR still alive?

2)personal preference or the same reason slips were replaced

3)

>Good thing I didn't say community votes are ALWAYS bad
>>That you need a community vote at all to justify something means there's no reason to add it

Translation: “Community votes literally mean nothing” or "cumunity vot ALWAYS bad"
Take that liberal

**Comment by ThatLing** [comment]
@yogstation13/maintainers Hello?

**Comment by Amelia0010** [comment]
lol

**Comment by Lynameep** [comment]
Don't think slips being strong again fits where the game is currently at/headed.

**Comment by HomocidlePancakes** [comment]
Where is it currently at/headed?

**Comment by Jc1469** [comment]
in a world of pushing someone into a wall and then having to push twice more for a very small stun and disguising it as skill when it's just bad

**Comment by SomeguyManperson** [comment]
We've already had a council vote that decided against TG's slip buff AKA disarm rework being merged, and the only way slips are getting reverted to their old state is if security also gets tasers back, since otherwise a bar of soap would be stronger than basically everything in the armory

**Comment by DiamondSentinel** [comment]
Stuns make for bad gameplay. In virtually every capacity. Because a stun turns into a cuff or a chain stun which makes combat rocket tag.

**Pull request closed without merging**
