### PR TITLE
adds silicon to nettles

### PR DESCRIPTION
**Pull request by boodaliboo**
stinging nettles use fibreglass tubes irl which are made of silicon 
#### Changelog

:cl:  
rscadd: Added silicon to nettles  
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
When botany mains make PRs like this, the first thing that should be done is looking up every chem that uses silicon as part of a recipe and see what chems can now be made when combined with already existing chem from other plants. Then you will know their true intentions.

**Comment by boodaliboo** [comment]
> When botany mains make PRs like this, the first thing that should be done is looking up every chem that uses silicon as part of a recipe and see what chems can now be made when combined with already existing chem from other plants. Then you will know their true intentions.

i havent played botany in a year but your not wrong

**Comment by SomeguyManperson** [comment]
Silicon is used to mix
Kelotane (already available in some quantities, requires carbon to be synthesized in botany with this pr)
Anti-toxin (partially synthesizable from botany with this pr, still requires nitrogen)
Leporazine (requires copper and plasma)
Space lube (already available in some quantities, requires oxygen)
Mindbreaker toxin (will become synthesizable fully from botany with this pr)

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
Id rather not powercreepe botany any further.

**Pull request closed without merging**
