### PR TITLE
Adds synth blood as preternis blood

### PR DESCRIPTION
**Pull request by Moltijoe**
Basically universal donor blood (that also includes exotic bloodtypes)

image

Made via a reaction of 
1 unstable mutagen (since i can't use blood because of synthmeat recipe)
1 cryoxadone
1 water (can be swapped for something else to balance)(probably should, to prevent saline invalidation)

also removes the safety check that vampires have for blood sucking exotic blood since bloodsuckers didn't have one
this will let them succ preterni again, but they need to actually think for even a moment before trying to suck an ethereal or poly
also, it's funny watching them suck bad blood

:cl:  
rscadd: Adds new reagent Synthblood that acts like all blood types (exotic too)
tweak: Changes preternis exotic blood from stable plasma to synthblood
tweak: Removes safety check for vampires trying to drink exotic blood (bloodsuckers didn't have one)
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
might be wise to remove the virology cheese to make blood duplicate if you do this, not sure how you'd work that out without fucking up viro though.

**Comment by 00ze-cyclone** [comment]
Maybe make it able to carry viruses and when the virology machine make culture bottles it’s of that synthblood, because the culture bottles already say that the content is synthetic blood.

**Comment by Moltijoe** [comment]
> might be wise to remove the virology cheese to make blood duplicate if you do this, not sure how you'd work that out without fucking up viro though.

i'm sorry, what?
oh, you mean unstable mutagen + blood to make more blood?
i don't think that's a problem, since that just creates more of the same blood type
this is more of a replacement/upgrade to saline than anything

**Comment by Moltijoe** [comment]
> Maybe make it able to carry viruses and when the virology machine make culture bottles it’s of that synthblood, because the culture bottles already say that the content is synthetic blood.

i'd rather just change the description instead of letting virologists print blood

**Comment by 00ze-cyclone** [comment]
> > Maybe make it able to carry viruses and when the virology machine make culture bottles it’s of that synthblood, because the culture bottles already say that the content is synthetic blood.
> 
> i'd rather just change the description instead of letting virologists print blood

They already print blood and there's more effective ways that are right in medbay to print blood anyway.

**Comment by Moltijoe** [comment]
> They already print blood and there's more effective ways that are right in medbay to print blood anyway.

i'll see what i can do for virus transfer

**Comment by Moltijoe** [comment]
blood code is too intertwined with everything, i'm just going to give them a universal bloodtype rather than whatever this jank is

**Pull request closed without merging**
