### PR TITLE
Fixes empowered burger sprite again (This time the right way)

### PR DESCRIPTION
**Pull request by ynot01**

### CODE REVIEW

**Comment by ynot01** [comment]
do not merge - i can't find the wip button

**Review by alexkar598 — CHANGES_REQUESTED** [review]
You will need to override the burger's icon var to point to the yogstation icon file instead.

**Comment by Readystorm546** [comment]
So much stuff for a burger dear god.

**Comment by ynot01** [comment]
its not even broken anymore tf

**Pull request closed without merging**
