### PR TITLE
Wampa Cave Ice Moon Ruin

### PR DESCRIPTION
**Pull request by UselessTheremin**
### Intent of your Pull Request

helping out in ways i can by adding new fun ice ruins to discover!

### Why is this good for the game?

wej wanted more ice ruins, and i do to, as there are barely any currently. I am helping out by improving the pool of ruins.

#### Changelog

:cl:  
rscadd: added the wampa cave, a hoth themed ruin for the ice moon.
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
no fake lightsaber or anything?

**Comment by patpol4** [comment]
Not bad actually

**Review by patpol4 — CHANGES_REQUESTED** [review]
1. Your map file doesn't follow the naming scheme used in config files
2. The map is wayy to big for what's actually inside it, trim the outer edges please so it doesnt take up that much space with template turfs when it spawns
chrome_mLgq0UQiHm
3. Capitalize the wampa name properly
4. Don't see why you would just put the armor inside a 1x1 room randomly, maybe place it scattered outside near the gibs?

**Comment by UselessTheremin** [comment]
did the thingies btw :heart:

**Review by patpol4 — APPROVED** [review]
The thingies have been done

**Comment by patpol4** [comment]
This is ready to merge, I just need the HC to click a button because our settings for config flags are bad. Don't want to bother him but feel free to ping if you really need this merged

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
