### PR TITLE
Reverts an undocumented change that nerfed lizards

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Author of #18097 removed this from the changelog and title of their PR but forgor to actually remove it from the code when asked to by balance council.

# Why is this good for the game?
Lizard

# Changelog

:cl:  
bugfix: fixed undocumented change that nerfed lizards, they no longer have slower tool speed
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
oh lol

**Comment by Moltijoe** [comment]
guess i forgot to push the commit

**Comment by neeshacark** [comment]
THE LIZARDS... THEY'RE EVOLVING!!!!!!!!!

**Comment by iloveloopers** [comment]
biased PR!!!!

**Comment by Chubbygummibear** [comment]
lizard buff let's fucking goooo

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
