### PR TITLE
Revert "You can no longer use camera consoles with the Bluespace Rapid Part Exchange Device"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#13877

This has NINE downvotes and no up votes???

### CODE REVIEW

**Comment by Sniblet** [comment]
Le selfmerge

**Comment by ghost** [comment]
While selfmerging is really a very bad thing, how the fuck should you exchange parts for machines by just looking on them through the camera, wtf

**Comment by maxion12345** [comment]
> While selfmerging is really a very bad thing, how the fuck should you exchange parts for machines by just looking on them through the camera, wtf

bluespace fuckery we don have to explain shit

**Comment by ghost** [comment]
Rip bozo

**Comment by Cartlord** [comment]
What the fuck is Jamie's deal?

**Comment by Spacemanspark** [comment]
Hmmm

**Pull request closed without merging**
