### PR TITLE
Tweaks medbay on box to encourage cooperation with medical

### PR DESCRIPTION
**Pull request by nmajask**
# Github documenting your Pull Request

In short, this removes the medical vendor in the medbay hallway with a shelf that contains a health analyzer, two crew pinpointers and two crew monitors. Also adds a crew monitor to the box CMO's locker and a medical vendor refill in the medbay break room. May need to tweak this a bit to make it look better and this has not been tested.

## Why?

I thought of this and decided to quickly make it to mess around with [FastDMM2](https://fastdmm2.ss13.io) (thanks monster) and also wanted to see how people would react to this.

As for why its good for the game, this discourages breaking into medical to simply treat yourself, and therefore encourages working with medical to heal wounds. The reason for the shelf with medical devices is to still allow antags to have access to crew monitors without having to break into medbay storage, and the reason for the crew monitor is because I said so and I'm tired of having to go get one from a vendor (and also because they start with the crew pinpointed, so they should also start with the second half of the crew monitoring package).

## Are there any pictures?

Yes

medbay1

medbay2

## I think this is a horrible change

Then dislike it

# Wiki Documentation

If this gets merged, the box medbay images will need to be updated and if the removed medical vendor is mentioned anywhere it will need to be changed. 

# Changelog

:cl:  
tweak: replaced the medical vendor in the box medbay hallway with a shelf with medical devices to encourage cooperation with medical
/:cl:

### CODE REVIEW

**Comment by nmajask** [comment]
Why did fast dmm remove random stuff from the map?

**Comment by nmajask** [comment]
oh, did I base it of my head branch?

**Comment by nmajask** [comment]
Oh, I opened fastdmm2 on my head branch, which is very out of date

**Comment by nmajask** [comment]
There, now its fixed I think

**Review by patpol4 — APPROVED** [review]
Interesting idea, although this might cause md's to instantly go for the monitors that just lie there and don't require more clicking, thus making pinpointers a lot less accessible to antags.

**Pull request merged**
