### PR TITLE
Tweaks the Syndicate Lavaland Base

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Tweaks a bunch of stuff in the Syndicate Lavaland Base, giving them more to do, more of a reason to attack it, and giving them better protection from miners. Untested, but it was done in Fast DMM so it should be fine. One thing that may need to be discussed by staff is what can syndicate scientists brainwash miners into doing (for example, can they brainwash a miner with the goal to release a singularity).
## Changes

- Added an operating computer, brainwashing disk, morphine bottle, and a syringe to the medical room
- Replaced the stray tools with a syndicate surgery duffle bag
- Replaced the empty defib with a combat one and a health analyzer
- Added a stasis bed circuit board to the storage room crates
- Added a viro vial box to the viro room
- Rearranged and added some turrets to better cover some of the egregious blind spots
- Added docking ports to the airlocks, currently only for admin bussing but I plan to do something with them in a later PR

### New Medical Room
image
### New Turret Placement
image
image
image
### New Docking Ports
image
image

# Wiki Documentation

The image for the Syndicate Lavaland Base will need to be updated if it is on the wiki. 

# Changelog

:cl:  
tweak: added many things to the Syndicate Lavaland Base
tweak: rearranged the turrets in the Syndicate Lavaland Base to remove some blind spots
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
sounds nice

**Review by patpol4 — APPROVED** [review]
Looks good to me

**Comment by warface1234455** [comment]
Xenobio when

**Comment by patpol4** [comment]
when you map it

**Pull request merged**
