### PR TITLE
Makes preternis lungs and eyes actually robotic as intended

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Whoever made these forgot to do this

# Changelog

:cl:  
bugfix: fixed preternis lungs and eyes not having the correct flags (they are actually robotic as intended now)
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
wouldn't this make a single emp a death sentence?

**Comment by Moltijoe** [comment]
> wouldn't this make a single emp a death sentence?

Preterni are emp immune, so not really
This will make even moderately cold air hurt all the more since your lungs wont slowly heal

**Comment by Moltijoe** [comment]
How is changing the eyes into robotic going to affect the night vision ability?

**Comment by iamthesilly** [comment]
> How is changing the eyes into robotic going to affect the night vision ability?

It doesn't

**Review by ToasterBiome — APPROVED** [review]

**Comment by KingSuperBOB** [comment]
Arent preterni lungs organic in lore with only a filter on them

**Pull request merged**
