### PR TITLE
Ports stray cargo pod event

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Original PR:https://github.com/tgstation/tgstation/pull/49707
Original author: XDTM

> Adds an event where a cargo pod containing a random cargo supply pack crash-lands on a random spot on the station.
> Added a rare variant (post 30 minutes) that spawns a null crate with 30 TCs of gear.
> 
> Crates which would be locked when ordered from cargo will start unlocked when falling with a stray cargo pod.

Should be good

#### Changelog

:cl:  
rscadd: Adds stray cargo event
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
Just make it so they spawn as broken Locks lmao

**Comment by Darkstick** [comment]
There better be a tell to where the shuttle is crashing, I don't want to be drinking at the bar until I get suddenly smushed by a bunch of lootboxes.

**Comment by swissloaf** [comment]
> There better be a tell to where the shuttle is crashing, I don't want to be drinking at the bar until I get suddenly smushed by a bunch of lootboxes.

priority_announce("Stray cargo pod detected on long-range scanners. Expected location of impact: [impact_area.name].", "Collision Alert")

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Yeet the syndi one. Its only to cause issues as syndicate items cannot be used by the station due to the rules.

We aint tg

**Comment by swissloaf** [comment]
> Yeet the syndi one. Its only to cause issues as syndicate items cannot be used by the station due to the rules.
> 
> We aint tg

done

**Review by JamieD1 — APPROVED** [review]

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
