### PR TITLE
Lizard-Tail Exclusive Emote: Thump

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Lizards can thump their tail.

Sourced from https://freesound.org/people/TylerAM/sounds/389665/
Ported from Shiptest.

https://github.com/yogstation13/Yogstation/assets/30399783/9b9cc5c1-a891-449b-b85e-b90953357581

# Why is this good for the game?
Improves the quality of role play that occurs on this fine server by expanding the catalog of emotes available to the player base for the purposes of socializing, role playing, and immersion as a lizard. (Again. 💯)

# Testing
I *thump as a lizard with my tail. Felinid Moja cannot *thump with cat tail.

# Changelog
:cl:  
rscadd: Lizard tail users can *thump their tail.
soundadd: Tail thump.
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Much better

**Comment by Scrambledeggs00** [comment]
Stanky leg died for this ;[

**Comment by ShoziOffical** [comment]
WEH

**Review by Majkl-J — APPROVED** [review]
Yespls

**Comment by MajManatee** [comment]
Not a fan of it.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
