### PR TITLE
Revert "Bluespace locker no longer has infinite power"

### PR DESCRIPTION
**Pull request by Cartlord**
Reverts yogstation13/Yogstation#17517 because, once again, Jamie merged a P.R. with massively negative reception and very little rationale - I'm frankly willing to bet that he only merged it because he's salty about his other locker nerf being refused.
also he was both the person who approved the code (wej only approved the map) and the one who merged it and that seems dumb

### CODE REVIEW

**Comment by MajManatee** [comment]
epic

**Review by patpol4 — APPROVED** [review]
map fine

**Review by MajManatee — APPROVED** [review]
code fine

**Comment by BurgerLUA** [comment]
Personally I think the other PR is fine. Just get a generator and put it in.

**Comment by Moltijoe** [comment]
> Personally I think the other PR is fine. Just get a generator and put it in.

cringe.
Honestly though, with bluespace lockers sometimes being crates now, it should be a large enough "nerf" to it's consistency that there's no need for this restriction. Also, with it being a crate, certain things can't be brought inside.

**Comment by Hopekz** [comment]
> Personally I think the other PR is fine. Just get a generator and put it in.

Where were you during the first PR?

**Comment by ThatLing** [comment]
Did you even try the new changes, or are you just salty because "muh bad"? Everyone in the original PR was crying about how this would completely ruin the BS locker, even though it only requires minimal effort to maintain power. I literally saw an assistant use the locker and build several machines with no issue, he simply replaced the power cell once in a while.

> massively negative reception

Of course, everyone always starts crying when stupid stuff inevitably gets nerfed. I bet the same will happen when the emag gets nerfed again in the future.

> also he was both the person who approved the code (wej only approved the map) and the one who merged it and that seems dumb

This happens literally all the time

**Comment by Moltijoe** [comment]
> Did you even try the new changes, or are you just salty because "muh bad"? Everyone in the original PR was crying about how this would completely ruin the BS locker, even though it only requires minimal effort to maintain power. I literally saw an assistant use the locker and build several machines with no issue, he simply replaced the power cell once in a while.

honestly, the change to locker spawning was a bigger nerf to bluespace lockers than the power things.

**Comment by Hopekz** [comment]
@ThatLing , @Moltijoe you aren't focusing on the point of this PR.
I think the main thing that the PR author is fighting is that the proper process potentially wasn't followed for the PR being reverted.

In the past if we've encountered something like this someone like bibby would revert it to allow it to go through the proper process to not go the whole "not reviewed and self merged" way.

The change itself doesn't matter it was the process in which this change was merged.

**Comment by Cartlord** [comment]
I'm not AS mad about that as I was with the other revert I made, because the person who made the P.R. I'm reverting and the person who merged are different this time - I see the "Jamie approved AND merged it" thing as more like the icing on this lame cake.

**Comment by Bibby0110** [comment]
We've had an internal discussion, where a broad consensus was agreed upon that we don't desire the bluespace locker to go in this direction, gameplay wise.
Thank you for making this PR which resulted in a productive discussion amongst the development team. Please feel free to do so in the future.

**Pull request closed without merging**
