### PR TITLE
Makes CQC Counter more consistent

### PR DESCRIPTION
**Pull request by Mqiib**
# Document the changes in your pull request

Right so 75% block chance is really good and all but cqc has stun baton hands so 99% of the time you're better off just not using it at all and just grabbing them because inevitably if you rely on the block you get dunked. Now you'll only get dunked anyways like 1% of the time instead of way more often than is fun. This doesn't necessarily make the offensive power of cqc better, but makes its defensive power more consistent (see sleeping carp having 100% chance to deflect projectiles, and lizard martial art always giving you the defensive bonuses). As of 3/19 it now also costs 10 stamina to block/counter an attack.

My reasoning: CQC is literally THE "kick your ass in melee but useless otherwise" martial art. It's a modern, well-designed martial art created by an advanced space-faring society. It stands to reason that someone with CQC would be very well trained in dealing with and neutralizing melee threats, especially (moderately-trained) people with stun batons or swords. Someone who is PREPARED for your attacks and ready to counter with training should easily stop you. It also will make CQC users feel WAY more badass when in melee.

Anyways I might later specifically add block piercing for other martial arts, dependent on the martial art or something, with actual proper block cooldowns also dependent on the martial art, assuming we get new martial arts with block chance other than cqc. Right now the only one that has something like this is the lizard martial art which has unblockable disarms.

# Wiki Documentation

Adjust block chance to 90% on wiki, maybe mention how the counter is a very strong defensive option mid-combat.

# Changelog

:cl:  
tweak: CQC active block increased up to 90% (from 75%)
tweak: CQC active block costs 10 stamina each time it is successful
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
At that point, why not just make blocking guaranteed?

**Comment by KillerOrcaCora** [comment]
I agree with cartlord, If it's not gonna have guaranteed aggressive grabs would make it better and more defining if it had 100% blocks, which would make it a lot more satisfying to use and be the other side of the grand sector shoot this guy and baton this guy.

**Comment by LazennG** [comment]
>Right now the only one that has something like this is the lizard martial art which has unblockable disarms.

cqc counters go through blocking things like shields

**Comment by Mqiib** [comment]
> I agree with cartlord, If it's not gonna have guaranteed aggressive grabs would make it better and more defining if it had 100% blocks, which would make it a lot more satisfying to use and be the other side of the grand sector shoot this guy and baton this guy.

Problem with this is if you have 100% block chance you can have a swarm of people beating on you and as long as you have throw mode on, NONE of them can hit you. Straight 100% block chance is really really powerful, but with 90% you can still be feasibly taken down by a large group of people with weapons. In 1-on-1 confrontations it is more or less guaranteed though.





> > Right now the only one that has something like this is the lizard martial art which has unblockable disarms.
> > cqc counters go through blocking things like shields

The counter requires that they swing at you, I would hardly consider it an attack that ignores shields since you're not the one attacking initially.

**Review by adamsong — APPROVED** [review]
Code looks fine, HD will need to review for balance

**Comment by Marmio64** [comment]
> > I agree with cartlord, If it's not gonna have guaranteed aggressive grabs would make it better and more defining if it had 100% blocks, which would make it a lot more satisfying to use and be the other side of the grand sector shoot this guy and baton this guy.
> 
> Problem with this is if you have 100% block chance you can have a swarm of people beating on you and as long as you have throw mode on, NONE of them can hit you. Straight 100% block chance is really really powerful, but with 90% you can still be feasibly taken down by a large group of people with weapons. In 1-on-1 confrontations it is more or less guaranteed though.
> 
> > > Right now the only one that has something like this is the lizard martial art which has unblockable disarms.
> > > cqc counters go through blocking things like shields
> 
> The counter requires that they swing at you, I would hardly consider it an attack that ignores shields since you're not the one attacking initially.

could make it deal stamina damage to you when you block a hit since it tires you out or something, so that you have no RNG, guaranteed blocks, that will eventually run out when used too much in a short period.

**Comment by Cartlord** [comment]
Is it possible to add a cooldown to blocks so that it's not feasible to block attacks from multiple at a time?

**Comment by KillerOrcaCora** [comment]
2 good suggestions for 100% blocks not exactly sure how they lay off the coding difficulty scale though.

**Comment by Mqiib** [comment]
> 2 good suggestions for 100% blocks not exactly sure how they lay off the coding difficulty scale though.

The way it handles blocking is fucky as hell, I wasn't able to quite suss out how it worked but I was able to get a functioning cooldown on the counter itself working. Issue was, attacks were still blocked while it was on cooldown and, as I said, I couldn't figure out where exactly to change stuff to fix that.

I do like the idea of stamina costs for blocking, might try that.

**Comment by JamieD1** [comment]
> > I agree with cartlord, If it's not gonna have guaranteed aggressive grabs would make it better and more defining if it had 100% blocks, which would make it a lot more satisfying to use and be the other side of the grand sector shoot this guy and baton this guy.
> 
> Problem with this is if you have 100% block chance you can have a swarm of people beating on you and as long as you have throw mode on, NONE of them can hit you. Straight 100% block chance is really really powerful, but with 90% you can still be feasibly taken down by a large group of people with weapons. In 1-on-1 confrontations it is more or less guaranteed though.
> 
> > > Right now the only one that has something like this is the lizard martial art which has unblockable disarms.
> > > cqc counters go through blocking things like shields
> 
> The counter requires that they swing at you, I would hardly consider it an attack that ignores shields since you're not the one attacking initially.

I disagree, you are changing a 1 in 4 chance to a 1 in 10. Thats a huge difference.

**Comment by adamsong** [comment]
I like the stamina damage idea, or, would it be possible to disable throw mode when an attack is blocked?

**Comment by Mqiib** [comment]
@JamieD1 it now costs stamina to do a block attack, effectively meaning that it'll pause your stamina regen for another 10 seconds in the middle of a fight and if you continue to you'll hit slowdown after a few hits. Really only will apply in 1 v X situations. Does this appease you, O' coder lord?

**Comment by JamieD1** [comment]
> @JamieD1 it now costs stamina to do a block attack, effectively meaning that it'll pause your stamina regen for another 10 seconds in the middle of a fight and if you continue to you'll hit slowdown after a few hits. Really only will apply in 1 v X situations. Does this appease you, O' coder lord?

Enough for a testmerge :)

**Comment by JamieD1** [comment]
Can you update your changelog

**Comment by Mqiib** [comment]
> Can you update your changelog

Changelog is currently accurate

**Pull request merged**
