### PR TITLE
Fixes psych office APC controlling vault power

### PR DESCRIPTION
**Pull request by alexkar598**
:cl:  
mapping: Fixes psych office APC controlling vault power on box
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
incorrect changelog

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Pretty sure you need the areastring changed instead of just removed

**Comment by alexkar598** [comment]
No, the APC lives in the area its meant to live in, it does not need the area string

**Review by ToasterBiome — APPROVED** [review]

**Comment by alexkar598** [comment]
https://github.com/yogstation13/Yogstation/blob/2e5668d609e7018000c824f8470ab6f50c5107ca/code/modules/power/apc.dm#L258-L259

**Pull request merged**
