### PR TITLE
Adds a config option to disallow AI from being traitor

### PR DESCRIPTION
**Pull request by Mr-Space**
### Intent of your Pull Request

I fucking updated my repo to satisfy the travis god. Basicly last PR but it's fixed because headcoders are lazy.

#### Changelog

:cl: MrSpace&AsV9
rscdel: Fuck AI tator tbh.  
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
im not sucking dick over here but its not headcoders fault that you had an outdated repo

**Comment by Mr-Space** [comment]
> 
> 
> im not sucking dick over here but its not headcoders fault that you had an outdated repo

truly it was the headcoders fault that they didn't update my repo :)))

**Comment by MegaEmpirical** [comment]
I don't have an issue being traitor AI with no borgs and you can still kill without murderboning just fine.

**Comment by Altoids1** [comment]
Again, this does exactly what #6472 did, a PR voted down by Council near-unanimously, but also affects just all gamemodes that inherit directly from the traitor gamemode.

**Comment by alexkar598** [comment]
Council can request the PR to be reverted if a need is there so this PR is essentially pointless.

**Comment by Mr-Space** [comment]
resim
> >council can request the PR to be reverted

**Review by alexkar598 — APPROVED** [review]
Welp who am I to argue

**Comment by MegaEmpirical** [comment]
You're all monsters and I'll see you in hell.

**Pull request merged**
