### PR TITLE
New AI Project: Language Processing

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Wow a new AI upgrade

# Changelog

:cl:  
rscadd: Added Language Processing Upgrade to the AI projects to be researched by the AI to learn more languages
/:cl:

### CODE REVIEW

**Review by MajManatee — APPROVED** [review]
borgs can do this, weird the AI cant

**Comment by ynot01** [comment]
Bibby claims he's doing this in https://github.com/yogstation13/Yogstation/pull/17756

**Comment by Bibby0110** [comment]
> Bibby claims he's doing this in #17756

i already did it read the pr

**Comment by ynot01** [comment]
> > Bibby claims he's doing this in #17756
> 
> i already did it read the pr

not merged

**Comment by Bibby0110** [comment]
closed in favor of my own shitcode

**Pull request closed without merging**
