### PR TITLE
Limits Abductors to 25 Pop

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

mmm I love the antag that can cause absolute nightmare chaos on *60 pop* doing it at 15 pop, where there's noone to stop or fix it :)

# Changelog

:cl:  
tweak: Midround Abductors are now pop limited
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
here before the ided


wait

**Comment by ToasterBiome** [comment]
this is only for dynamic doe

**Comment by VaelophisNyx** [comment]
not anymore ;P

**Comment by GraveHat** [comment]
You weren't kidding with that I ded tag

**Comment by ghost** [comment]
Abductors don't kill people and their organ effects can even be positive so there is no reason to do like this

**Comment by VaelophisNyx** [comment]
> Abductors don't kill people and their organ effects can even be positive so there is no reason to do like this

plasma organ
spider organ
all access organ

abductors also tend to be shitters and have gotten their own rules revised like 6 times now for it

**Comment by GraveHat** [comment]
> > Abductors don't kill people and their organ effects can even be positive so there is no reason to do like this
> 
> plasma organ spider organ all access organ
> 
> abductors also tend to be shitters and have gotten their own rules revised like 6 times now for it

that and the brainwashing of the entirety of lowpop crew is not as appealing as it sounds.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
