### PR TITLE
Makes Halloween last most of October

### PR DESCRIPTION
**Pull request by fluffe9911**
Lets be honest by the 10th most people are already in full spooky Halloween swing and buying candy and all that so lets change the date to start earlier for the spooks!

### CODE REVIEW

**Comment by Amelia0010** [comment]
no.

**Comment by fluffe9911** [comment]
yes.

**Comment by Amelia0010** [comment]
image
🤔

**Comment by fluffe9911** [comment]
Yes I like meh pr lol

**Comment by Amelia0010** [comment]
how about we merge this on the 28th, as a compromise. you get it merged, I get to not have halloween through more than half of october like some retard without a calendar who can't tell when halloween is and decides to celebrate it for 2/3rds of a month because I just want to be sure.

**Comment by Ratvar** [comment]
nich dumb

**Comment by ThatLing** [comment]
wtf nich its called spooktober for a reason

**Comment by Amelia0010** [comment]
yes, because it begins with oktober, and ends with spooks

**Comment by ThatLing** [comment]
I bet you don't even play anymore Nich, why do you care?

**Comment by Amelia0010** [comment]
I don't

**Pull request merged**
