### PR TITLE
Adds gangs to dynamic

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Adds gangs as a roundstart dynamic ruleset.

If this pull request and https://github.com/yogstation13/Yogstation/pull/15058 would get merged, I could PR a very funny thing.

# Changelog

:cl: SuperSlayer
rscadd: Added gangs to dynamic
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
hmm this will surely go well

**Comment by N3D6** [comment]
Please no, gangs as a mode is fucking horrendous

**Comment by ghost** [comment]
Gangs are cool

**Comment by Hopekz** [comment]
> Gangs are cool

Gangs is a "cool" game mode. Just not actually fun to play in practice.

We're the only codebase that has this unchanged game mode because every other codebase replaced it with something different.

Gangs would probably be both cool AND fun if someone cared enough to rework it

**Comment by Xoxeyos** [comment]
I purposely left gangs and revolutionaries out of dynamic for a reason, it will be on you to fix any sort of bugs, or balancing issues that comes from merging this.

**Comment by JamieD1** [comment]
Fuck Gangs

**Pull request closed without merging**
