### PR TITLE
Makes the Russian Bunker Harder. A lot Harder.

### PR DESCRIPTION
**Pull request by Lynameep**
### Intent of your Pull Request

Adjusts the difficulty of the ruin to border on the level of unfair.

- Russians no longer drop shotguns, act smarter, and don't die to fire(or even lava).
- Vodka Infused Hell Bears.
- Unbreakable walls and Tougher Turrets/Airlocks
- You now also get the katana for your troubles

#### Changelog

:cl:   
tweak: Russian Bunker is now Harder. Much Harder.
tweak: Increases the reward to include the Energy Katana.
/:cl:

### CODE REVIEW

**Comment by Ktlwjec** [comment]
Free emag+teleporter+weapon for completing the ruin? I know it's harder but no thank you

**Comment by HomocidlePancakes** [comment]
You can get mobs stuck on that heater in the lobby, forcing them to melee. Minor cheese but still cheese

**Comment by HomocidlePancakes** [comment]
Also you should just put a regular katana

**Comment by boodaliboo** [comment]
the fuck humans wearing bear fur are lava proof why just keep it how it is and remove the katana and the nagant loot and the hell bears are cool but this ruin isnt suppossed to be a death trap for a new miner who wanders into it

**Comment by HomocidlePancakes** [comment]
New miners exist only so that goliaths can reenact their favorite hentai with them

**Pull request closed without merging**
