### PR TITLE
Clown Wizard Den

### PR DESCRIPTION
**Pull request by Marmio64**
Adds a new ruin, the clown wizard den. It is just the wizard den, but modified to be worthy of a clown, and worthy of a space ruin. Notable loot is the cosmohonk spacesuit (a spacesuit that only clowns can wear, and looks funny), a bananium e-sword, and a shit ton of bananium if you deconstruct the walls and stuff. Nothing is really guarding the ruin, but if you piss off the destroyer inside you might have a bad time.

Also, if this gets merged, do I get my discord dev-team role back? Please?

edit: also, just to make this clear, it is not the wizard den, it is a space ruin, and everything is breakable. 

clownwizardship

#### Changelog

:cl:  
rscadd: Adds a new space ruin: The clown wizard den.
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
if the enemy is hostile by default and not neutral as is implied and if the besword is removed this would probably be fine.

**Comment by Marmio64** [comment]
just going to close this
it isn't very good of a idea tbh, and uh, i'd rather move on to a better space ruin im planning on doing
maybe i'll make it better later

**Comment by Marmio64** [comment]
hopek wants it open again

**Comment by Marmio64** [comment]
working on adding things, so make sure you don't merge this yet for whatever reason. Not closing it since i don't want to spam discord with open and close messages.

**Comment by ghost** [comment]
>bananium esword

Remove this or i'll do it for you later.

**Comment by UselessTheremin** [comment]
> > bananium esword
> 
> Remove this or i'll do it for you later.

breh the haunted toy shop has a bananium esword kek

**Comment by patpol4** [comment]
Not gonna lie this looks really bad

**Comment by Marmio64** [comment]
im going to make a separate clown themed space ruin perhaps instead of this one, because i can't think of good ways to make it look better and be better

**Pull request closed without merging**
