### PR TITLE
Ports eris slimes sprites mostly

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
Changes the current slime sprites and (most) of the slime crossbreed cores, slimes are ported from Eris (https://github.com/discordia-space/CEV-Eris/pull/6205), metalic slimes are edited versions of eris slimes to look more like liquid metal, crossbreed cores and edited to use the new sprite for the slime cores ( mostly )

# Spriting
2022-12-04 16_04_03-Window
slimes
2022-12-04 16_08_30-Window
edited crossbreeds
pngpngpng
old/new slime comparasion
# Wiki Documentation

Yogstation Wiki. 
edit the slime icons on the wiki, will put images of them in the comments to not bloat the PR
# Changelog

:cl:   WalterJe for original sprites, cuackles for the rest, isotope for paying
imageadd: added new slimes
imagedel: deleted old slimes
/:cl:

### CODE REVIEW

**Comment by ChuChu42** [comment]
gold slime looks more brownish than pure gold, it seems like you targeted the color of real gold but it whould have been better to be more yellow

**Comment by MajManatee** [comment]
slimin'

**Comment by isotope436** [comment]
the slooms are upon you **you cannot escape and they will not waver**

succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms, succumb to the slooms,

**Comment by isotope436** [comment]
image0

**Comment by cuackles** [comment]
> slimin'

image
do you bealive this is a better fit ?
or this
image

original
image

**Comment by cuackles** [comment]
image
could also be this

**Comment by cuackles** [comment]
i replied to the wrong comment im smart

**Comment by cuackles** [comment]
> gold slime looks more brownish than pure gold, it seems like you targeted the color of real gold but it whould have been better to be more yellow

u, see above

**Comment by isotope436** [comment]
The last one looks the best

**Comment by isotope436** [comment]
> image could also be this

Do this one :)

**Review by MajManatee — APPROVED** [review]
code checks out

**Comment by cuackles** [comment]
Dblue blue
gold gold
green green
grey grey
Lpink light pink
metal metal
oil oil
orange orange
pink pink
purple purple
pyrite pyrite
rainbow rainbow
red red
sepia sepia
silver silver
yellow yellow
adamantite adamantite
black black
blue blue
bs bluespace
cerulean cerulean
dark purple dark purple
images for the wiki

**Review by Ebin-Halcyon — APPROVED** [review]
Radical jump in sprites, but they're good none the less. Only hiccup I saw was IDB fucking up the renders.

**Comment by CMOisLing** [comment]
> > image could also be this

Cheese Burger

**Comment by isotope436** [comment]
> Radical jump in sprites, but they're good none the less. Only hiccup I saw was IDB fucking up the renders.

soon™

**Comment by ShoziOffical** [comment]
like pancake

**Comment by Simplehorror** [comment]
they look like crap wtf

**Comment by Simplehorror** [comment]
are they even transparent anymore

**Comment by cuackles** [comment]
The metalics aren't, the standard ones should have kept a degree of transparency, can you be more specific on why do they look like crap ?, An specific aspect ? The desing in general ? Is it only the metalics one that looks bad or is it everyone ?

**Comment by Simplehorror** [comment]
they feel more of a clusterfuck with a ton of clashing colours than the simple old slimes

**Comment by isotope436** [comment]
> they feel more of a clusterfuck with a ton of clashing colours than the simple old slimes

this pr has been up for almost 4 days and you waited till literally an hour after its merged to say anything :|

also the server style is getting redone soon anyways and your one of two people to have any issue with it as i made sure to bring it up to pretty much all of the active mentor or dev team members (at least the ones in the discord) before i asked cauckles to do it.

so either way the old sprites are getting removed i just put a rush on the slimes because im a biased xenobio main and they honestly have a smol chance of getting redone in the mass resprite coming up

**Comment by Simplehorror** [comment]
i didnt see it

and the server style is being redone? I hope not to something like this, because it looks fucking horrible, no offense to the spriter

**Pull request merged**
