### PR TITLE
Changes mous description

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your PR

E

# Wiki Documentation

Honk

# Changelog

:cl:  
tweak: changes mouse description
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
hmm

**Comment by ghost** [comment]
> hmm

Now it is better!

**Comment by tattax** [comment]
the joke is that the sprite is cute but the desc says otherwise

**Comment by ghost** [comment]
Е

**Comment by AshCorr** [comment]
I love it! this positive description is so much cuter!

**Review by adamsong — APPROVED** [review]

**Comment by ghost** [comment]
E

**Pull request merged**
