### PR TITLE
laugh cooldown

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

anti audio spam

# Changelog

:cl:  
tweak: laughing now has a 3 second cooldown
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
ided tier pr ~~lmao~~ bbecause im fairly certain last round caused this

**Comment by Hopekz** [comment]
> ided 

He died laughing?

**Comment by ynot01** [comment]
died of laughter

**Comment by RG4ORDR** [comment]
Absolutely not.
Add in oxyloss, so you can laugh yourself to death.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
