### PR TITLE
Removes the ability for slimepeople to swap bodies AFTER death

### PR DESCRIPTION
**Pull request by Mqiib**
I was under the assumption that the slimepeople I killed were just able to quickly swap bodies before they are critted but apparently IT DOES THAT FOR THEM! This removes the ability for them to be effectively unlimited revives for the low low price of breaking into science once.

# Wiki Documentation

Slime people no longer swap bodies on death.

# Changelog

:cl:  

rscdel: Removes slime person auto-body-swap on death

/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
i ded

**Comment by Mqiib** [comment]
> i ded

Just because it's an ided doesn't mean it's a bad change sunglasses emoji

**Comment by Maia-J** [comment]
> This removes the ability for them to be effectively unlimited revives for the low low price of breaking into science once.

Did you ever try to setup more than like 3 **equipped** bodies at once? It's not exactly easy to equip the clones to be useful when you inevitably die.

**Comment by CMOisLing** [comment]
> > This removes the ability for them to be effectively unlimited revives for the low low price of breaking into science once.
> 
> Did you ever try to setup more than like 3 **equipped** bodies at once? It's not exactly easy to equip the clones to be useful when you inevitably die.

You get to come back from death without any external intervention. Im pretty sure this even works with gibs and ceremation. Who cares if the other bodies arent kit'ed up? That seems like a very reasonable downside for getting a 1up that effectively removes you from any danger.

**Comment by ToasterBiome** [comment]
> > This removes the ability for them to be effectively unlimited revives for the low low price of breaking into science once.
> 
> Did you ever try to setup more than like 3 **equipped** bodies at once? It's not exactly easy to equip the clones to be useful when you inevitably die.

A radio headset is all you need if you're a non-antag

**Comment by boodaliboo** [comment]
maybe keep it as a traitor thingy

**Comment by boodaliboo** [comment]
> maybe keep it as a traitor thingy

like a item

**Comment by CMOisLing** [comment]
Can someone who downvotes please give a reason why this isnt a good nerf?

**Comment by CMOisLing** [comment]
> maybe keep it as a traitor thingy

I dont think we should be adding traitor items that do minor adjustments to already niche mechanics. Its just confusing, underwelming, and adds bloat.

**Comment by VaelophisNyx** [comment]
> Can someone who downvotes please give a reason why this isnt a good nerf?

my brother in christ it is the entire race's gimmick

**Comment by Mqiib** [comment]
> > Can someone who downvotes please give a reason why this isnt a good nerf?
> 
> my brother in christ it is the entire race's gimmick

No, their gimmick is having body clones you can swap to. Them also happening to have free revives so long as they have clones alive is only part of that and it is totally reasonable to remove this free revive thing for the low low price of being a slime person (who have a weakness to cold damage which is very uncommon but take HALF burn damage from all sources like lasers and heat and fire)

**Comment by VaelophisNyx** [comment]
and die if you charcoal syringe them...
idk this feels very Ided

**Comment by CMOisLing** [comment]
> and die if you charcoal syringe them... idk this feels very Ided

People also die if you syringe them with things that are toxic to them. The only difference is they cant just body swap before they die.

Slime people negatives are almost completely negated by the positives, and then completely negated again by the fact that death means nothing to them because they can just swap out of it. All this change means is they can no longer mindlessly suicide bomb, and now have to fear things like insta gibs. You have to worry about less things than a ling since you can effectively teleport out of your body if it looks like they are gonna gib or cremate you.

**Review by JamieD1 — APPROVED** [review]

**Comment by MegaEmpirical** [comment]
Good balance change.

**Comment by enkidienne** [comment]
just gotta put this here, but this is currently handled very weirdly, creamtor will permadeath you no matter what, you cannot body swap when restrained, stunned, in crit, or anything in that sense. I must say that this kinda kills the viability of slimepeoples.

**Comment by CMOisLing** [comment]
> just gotta put this here, but this is currently handled very weirdly, creamtor will permadeath you no matter what, you cannot body swap when restrained, stunned, in crit, or anything in that sense. I must say that this kinda kills the viability of slimepeoples.

I would make a bug report about not swapping when restrained or in crit. Slime people are still totally viable, if you miss the 1up part that much just carry around stabilized cerulean.

**Pull request merged**
