### PR TITLE
Adds colocups

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Adds colocups. And sprites for them.

# Changelog

:cl:  
rscadd: Adds colocups
imageadd: Adds images for colocups
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
image
Based

**Comment by ghost** [comment]
Actually i can remove the lean part of this PR if everyone doesn't want that

**Comment by Hopekz** [comment]
> Actually i can remove the lean part of this PR if everyone doesn't want that

Who knows.
I don't think their dislikes matter if they don't provide feedback.

The only time no feedback dislikes "matter" is when a HC or maintainer wants to close a PR anyway, so they use them as an excuse to do so.

**Comment by ghost** [comment]
> The only time no feedback dislikes "matter" is when a HC or maintainer wants to close a PR anyway, so they use them as an excuse to do so.

Okay, but maybe i will add lean as a separate PR

**Review by nesisknesis — APPROVED** [review]

**Comment by bruhlookatthisdood** [comment]
orange doesent like lean
):

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
