### PR TITLE
Makes sus hud a bit more sussy

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Replaces shitty ! hud icon with something a bit more suspicious

(Actually just makes sus hud have an amogus icon during aprill fools(Yeah, aprill fools aren't soon but I suddenly realised that this will be really funny, so I decided to PR it now))

# Spriting
image

# Changelog

:cl:  
tweak: During aprill fools suspicious hud will have a special icon
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
No

**Comment by ghost** [comment]
Ok

**Comment by nafo0** [comment]
ebic

**Comment by KillerOrcaCora** [comment]
Capture

**Pull request closed without merging**
