### PR TITLE
Megafaune buff: all megafauna drop their health in cash * 5 directly into the cargo budget when killed

### PR DESCRIPTION
**Pull request by SomeguyManperson**
FOR REFERENCE
Swarmer  beacon: 3750 credits (5 shrubbery crates)
Drake: 12500 credits (17 shrubbery crates)
Bubblegum: 12500 credits (17 shrubbery crates)
Colossus: 12500 credits (17 shrubbery crates)
Blood-Drunk Miner: 4750 credits (6 shrubbery crates)
Hierophant: 12500 credits (17 shrubbery crates)
Legion: total of just under 30000 credits (~42 shrubbery crates)

:cl:  
rscadd: Megafauna now supply cargo with money when killed
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
Before anyone objects to this being "overpowered", keep in mind that, as in `code/modules/cargo/exports/lavaland.dm`, each piece of megafauna loot (save for the ash drake and Legion's) can be exported for 40,000 credits. But miners aren't going to be likely to part with these, so there should be some other IC motivation to kill megafauna as well.

**Comment by Readystorm546** [comment]
I like this alot but only 2500 credits for bubblegum is like so fucked.

**Comment by Nickvr628** [comment]
Yeah 2500 credits seems low, that is a few sheets of minable materials. It should be a higher payout for big game hunting on lavaland.

**Comment by boodaliboo** [comment]
buff the stronger ones money output keep easy ones like hierophant the same

**Comment by SomeguyManperson** [comment]
scaling is now 5* health

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
