### PR TITLE
Add Catslug

### PR DESCRIPTION
**Pull request by Takahiru**
Adds the catslug (not the slugcat thats different) to Yogstation, it is present within the friendly gold core spawning pool. 

Sprites are from VoreStation btw

catslug

Catslug is now a critter in the gold slime pool wiki people

:cl:  
rscadd: Adds catslug
/:cl

### CODE REVIEW

**Comment by cuackles** [comment]
Add the sprites in the PR please

**Comment by Takahiru** [comment]
> Add the sprites in the PR please

I figured you could just use icon diff bot, but gimme a sec

**Comment by cuackles** [comment]
I mean yeah we can, but it's easier to see if they are directly in the pr

**Comment by redmoogle** [comment]
> Sprites are from VoreStation btw

**Comment by tattax** [comment]
why were you on vorestation

**Comment by Takahiru** [comment]
> why were you on vorestation

The TG PR credits vorestation, so I do the same here

**Comment by neeshacark** [comment]
i thought this was a cat-based shotgun slug. i am disappointed to see it is not.

**Review by KillerOrcaCora — APPROVED** [review]
sure why not

**Comment by JamieD1** [comment]
what the fuck

**Pull request merged**
