### PR TITLE
Removes all ambiguity around metashields by giving everyone an antag HUD

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

Finally we don't have to do complicated rules discussions

# Wiki Documentation

# Changelog

:cl:  
rscadd: Metashields are no more! Hooray!
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Close PR if you like kissing dudes

**Comment by Tipy1802** [comment]
image

**Comment by Bibby0110** [comment]
> image

Not a meme PR?

**Comment by adamsong** [comment]
> Close PR if you like kissing dudes

Ok

**Pull request closed without merging**
