### PR TITLE
Scientific toe stubbing

### PR DESCRIPTION
**Pull request by ghost**
5% chance to stub your toes while walking is retard levels of locomotory intelligence. This nerfs the chance to 0.1%, but makes it significantly more painful.

I want to remove this because it was a meme PR to begin with, but since I'll be met with "REMOVE DONT IMPROVE" if I did, I have improved toe stubbing by adding multiple checks based on speed and blindness to scale the stamina and brute damage. Going faster now makes you more likely to stub a toe and increases damage. Being blind makes you more likely, but people with congenital blindness (the roundstart quirk) are presumably used to being blind and therefore are less likely than newly blind people, but still more likely than regular people. Having blurry eyes also makes you more likely to stub your toe. Species without pain-sensitive toes do not have to deal with this shit.

Yes, that use of prob(80) is valid. That's the joke.

Blame swissloaf.

:cl:  
tweak: toe stubbing is now rarer but more severe, just like in real life.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
fucking git at it again

**Comment by Mqiib** [comment]
I don't know how to feel about this.

**Comment by MegaEmpirical** [comment]
so that's why I stubbed my fucking toe, I was wondering what the fuck happened

**Comment by ynot01** [comment]
wear shoes retard

**Comment by Takahiru** [comment]
stubbing your toe on every 1/20 tables is pretty wacky, just because you arent wearing shoes

**Comment by Mqiib** [comment]
> stubbing your toe on every 1/20 tables is pretty wacky, just because you arent wearing shoes

Especially when you consider how often the bump gets set off on a table when you don't even directly run into it, such as going over a corner sometimes setting it off.

**Comment by Featherfield** [comment]
Is this a ided

**Comment by jcatjmeow** [comment]
Changing from 👎 to 👍 given the more recent commits

**Comment by SomeguyManperson** [comment]
adjuststaminaloss deals distributed stamina damage so it actually needs 120 damage to stun
so either do that or  have it deal 50 stamina damage straight to the effected leg to disable it, which won't stun but will make you significantly slower

**Comment by Marmio64** [comment]
can we make golems not have to deal with toe stubs, they are literally always wearing shoes of metal and shit. Besides cloth golems and the other ""soft"" materials.

**Comment by ghost** [comment]
Massive megabrain autism moment of inspiration hit me, changing PR to reflect cosmicbrain ideas....

**Review by fluffe9911 — APPROVED** [review]
Alot of effort just for stubbing toes

**Pull request merged**
