### PR TITLE
Regal Rats now get an ability that gives them a tommy gun for 8 seconds

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

TIME TO GO

Also regal rat sucks and needs a buff in order to become a round altering antag, they get murdered by anyone in maints with a blunt object. should help them defend themselves
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Regal Rats now get an ability that gives them a tommy gun for 8 seconds
/:cl:

### CODE REVIEW

**Comment by UltraBigRat** [comment]
the pr we needed but dont deserve

**Comment by Simplehorror** [comment]
next pr is giving them an ability that makes them invisible

**Comment by Sniblet** [comment]
Also changes the flavor text for rat spit without telling anyone

I like the idea of this low-stakes midround joke "antag" being able to kill anyone without heavy ballistic armor in about 3 seconds without warning

**Comment by Simplehorror** [comment]
> Also changes the flavor text for rat spit without telling anyone
> 
> I like the idea of this low-stakes midround joke "antag" being able to kill anyone without heavy ballistic armor in about 3 seconds without warning

glad you like it my friend

**Comment by Rdrazga** [comment]
I thought these were supposed to be rat royalty not rat gangsters?

**Comment by Bibby0110** [comment]
no

**Comment by ToasterBiome** [comment]
Required to wait 24 hours before closing

**Comment by Simplehorror** [comment]
i'll give them invisibility instead

**Pull request closed without merging**
