### PR TITLE
Revert "Revert "heads can't roll shadowling""

### PR DESCRIPTION
**Pull request by jcatjmeow**
Reverts yogstation13/Yogstation#10046

### CODE REVIEW

**Comment by Reed0506** [comment]
heads shouldnt be able to roll antag at all as far as im concerned. its just a free win and makes life suck ass for anyone on the receiving end.

**Comment by jcatjmeow** [comment]
Agree with reed.

**Comment by JamieD1** [comment]
Literally RD and CMO only.

**Comment by Ratvar** [comment]
What a great argument, jamie. So what?

**Comment by JamieD1** [comment]
Fine might as well.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
