### PR TITLE
mesalikepie came crying to me about ez clean grenades and it turns out i forgot to consider you can use an oddyseus to synthesize infinite amounts of the chemical leading to it being used to instant kill people but fortunately i am incredibly handsome and intelligent and immediately had a fix on hand for that

### PR DESCRIPTION
**Pull request by ghost**
also i may have been hoping that this would happen because it would be really funny but that would be a lie because i genuinely didn't think this would happen

also it's down to 1 on reac volume instead of 1.5 so it shouldn't quite oneshot even in normal beaker form but now that you can't produce infinity of it you can't use it to wipe out the entire station

if it keeps being a problem i can just remove the reac volume effect entirely but this is fine otherwise

(this doesn't really change that being splashed with a beaker of this will still fucking kill you)
#### Changelog

:cl:  
tweak: fixes theos abusing waffle co chems
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
I'm not wrong

**Comment by ghost** [comment]
yeah hes not wrong ngl

theos wtf

**Comment by Mqiib** [comment]
Ok but it was hilarious the first time it was used and dude just dies instantly. Really warranted the nerf lmao.

**Review by SomeguyManperson — APPROVED** [review]
when are we banning this theos guy

**Pull request merged**
