### PR TITLE
Traitor crafting recipes (uplink item)

### PR DESCRIPTION
**Pull request by Ktlwjec1**
Open to ideas - I do want feedback on the TC price, recipes themselves, any recipes that you want added. ~~If this gets positive feedback I'll work on a better book sprite for it if it's needed.~~ Can't be fucked to make a new one honestly, it's not a terrible sprite but feel free to message me a better one/put it on here.

Adds an uplink item for 4TC. It is a one-use book that, once read, grants you access to the following in the crafting menu:
- Baseball Bat
- Explosive Lance

I don't want to lower the TC price anymore than that due to the weapons it provides, but I'm fine with upping the price as much as is wanted. Learnt recipes always show at the beginning of the crafting menu lists so they can be found easily.

:cl:  Ktlwjec
rscadd: New traitor item, the makeshift weapons book! Grants the reader access to new crafting recipes. 
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Explosive lance, haha no. We dont need traitors carrying an instakill

**Comment by ynot01** [comment]
> We dont need traitors carrying an instakill

yea we do

**Comment by fluffe9911** [comment]
yea we do x2

**Comment by Readystorm546** [comment]
I love democracy

**Comment by drderp3635** [comment]
Make it a multiuse book like codespeak manual so traitors can start a baseball bat revolution

**Comment by Ktlwjec1** [comment]
That is exactly why it's not multiuse, they can buy multiple if they wish to do it though.

**Comment by MegaEmpirical** [comment]
Paper shurikens that are kind of shit

**Comment by ghost** [comment]
frankly explosive lances aren't OP for traitors, the issue was that everyone and their mum could make one

**Comment by oklews** [comment]
It would be nice if it was greyshit/engineer/CE only

**Comment by Ktlwjec1** [comment]
I'll see how often this is used once/if merged, if too often I'll role restrict.

**Comment by CMOisLing** [comment]
Flashlight + Diamond = Esword
If Frank West can do it a traitor can too

**Comment by boodaliboo** [comment]
cant remeber if we got stun gloves but add this to it and maybe a crafting recipe for some tools that you can like make in perma

**Comment by alexkar598** [comment]
time to abuse and make a revert after abusing it

**Pull request merged**
