### PR TITLE
Ports tgui filing cabinets

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Ports tgui filling cabinets from tgstation

https://github.com/tgstation/tgstation/pull/64065

# Changelog

:cl: mozi-h, ported by SuperSlayer
tweak: filing cabinets now use tgui
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
WHAT

**Comment by ghost** [comment]
NO

**Comment by ghost** [comment]
ARE YOU KIDDING ME, I REVERTED THAT SHIT

**Comment by ghost** [comment]
I hate github I hate github I hate github I hate github I hate github I hate github I hate github

**Comment by ghost** [comment]
Why did lints fail but everything had compiled wtf

**Comment by Bibby0110** [comment]
Reopen when it compiles

**Pull request closed without merging**
