### PR TITLE
Revert "ye (#17881)" - Readding Yogsdelta

### PR DESCRIPTION
**Pull request by RG4ORDR**
This reverts commit e2ce0336ff02b002152da23db8e809376cda24a9.
Very simple, this PR is meant to fix Yogsdelta so it can be brought back to the "map rotation". I've asked several times in discord and never been given a clear picture about Delta, offering several times to solve issues that were spoken about but never shown before the map was removed. 

Any and every issue with the map I want posted in this PR so it can be solved and we can readd a great SS13 map.
There's a few I know about such as:
Gamer loot in maints
Too many static maints
Atmospherics and the Engine( the map features TWO engine rooms with a SM AND Tesla/Sing).

# Changelog

:cl:  
rscadd: Readds Delta
wip: This is work in progress  
mapping: Readds and fixes Delta map bugs,issues, so forth.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Is delta even still up to date?

**Comment by wonderinghost** [comment]
No.

**Comment by RG4ORDR** [comment]
> Is delta even still up to date?

No but I intend on getting it up to date.

**Comment by neeshacark** [comment]
you should probably bring it up to date before readding it, its not as extremely out of date as the map im bringing back (donut) but it really does need to be fixed up a bit first

**Comment by iamthesilly** [comment]
I think it's cool that it has two engines, and makes sense the atmos-based one is in atmos

**Comment by MajManatee** [comment]
too bad delta sucks. Definitely modernize the map before re-adding it.

**Comment by azzzertyy** [comment]
> too bad delta sucks. Definitely modernize the map before re-adding it.

no, stfu, delta is a good map, its just out of date.
delta is absolutely the best map out of all the highpop maps we have had, I cant name a single real major issue with its design other than its out of date and badly maintained

**Comment by Aquizit** [comment]
Simply adding the HD thing since it's technically a revert which is HD only.

**Comment by Bibby0110** [comment]
This is stale.

**Pull request closed without merging**
