### PR TITLE
Increases the size of the syndicate listening outpost

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Increases the size of the output was a little too cramped imo(and wonky shaped)

New:
image

Old:
image

#### Changelog

:cl:  
tweak: Syndicate listening outpost is bigger
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
syndi outpost is super cozy and doesn't waste space though, unlike this new one

**Comment by Hopekz** [comment]
2 doors looks weird here in my opinion. No further feedback maybe try to see if the double gas station door looks better here if you're insistent on it 2 tiles of doors.
2 doors and double doors are usually meant for high traffic areas

**Comment by redmoogle** [comment]
> 
> 
> 2 doors looks weird here in my opinion. No further feedback maybe try to see if the double gas station door looks better here if you're insistent on it 2 tiles of doors.
> 2 doors and double doors are usually meant for high traffic areas

It was meant to stay consistent with the halls, will experiment with it. I do agree it looks weird

**Comment by patpol4** [comment]
Does it really need the extra space though? And the double doors are super weird.

**Comment by redmoogle** [comment]
> 
> 
> Does it really need the extra space though? And the double doors are super weird.

eh we got a huge ass asteroid. was tempted to make a space variant of lavaland syndies

also double doors removed

**Comment by redmoogle** [comment]
> 
> 
> syndi outpost is super cozy and doesn't waste space though, unlike this new one

Missed that. mainly just the main hall/hub area was awkward I can get why you'd like it smaller though. however _sadly_ 3 tile wide is the only decent hallway size that isnt even numbered

**Review by patpol4 — APPROVED** [review]
Added monstermos firelocks, added decals, fixed some problems, moved a sink
vivaldi_9rfgeogku1
vivaldi_eipJb0TkmW

**Comment by redmoogle** [comment]
How was there a hole under the bookcase, wtf I had removed it and checked already

but thx

**Pull request merged**
