### PR TITLE
Reduces slowdown of worn duffel bag, galoshes, and clown shoes

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

Reduces the movement slowdown coefficient of a worn pair of galoshes from 1 to 0.75

Reduces the movement slowdown coefficient of a worn duffel bag and pair of clown shoes from 1 to 0.5

Apparently the basic hardsuit slowdown coefficient is also 1? I don't feel like it's appropriate to put these 3 things on the same level as an entire hardsuit.

TESTING:
I walked from the doors in engineering hallway to the southern wall. 

slowdown = 1 -- 7.42s
slowdown = 0.75 -- 6.95s
slowdown = 0.5 -- 6.18s
showdown = 0 -- 5.09s

(no this is not exact this is me just trying to push my stopwatch thing on my phone while moving)

I think that half-second feels a whole lot better.

# Changelog

:cl:  
tweak: Reduces slowdown coefficient of galoshes from 1 to 0.75
tweak: Reduces slowdown coefficient of duffel bag and clown shoes from 1 to 0.5
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
I'm still making fun of dufflers you can't stop me

**Comment by MajManatee** [comment]
Duffle bags are noob bait

**Comment by Aquizit** [comment]
My whole reasoning here is simply that these 3 things should not be as cumbersome as a full hardsuit, but still not be efficient or ideal.

**Comment by Moja10** [comment]
Genius change. I've always felt like clown shoes shouldn't be one of the strongest slowdown burdens in the game, makes things so unbelievably difficult, especially with Yogs already slower movement speed than default /tg/ speed. Duffles are entirely gimped by their slowdown, it feels nearly as bad as being half health. All these slowdowns just stacked on top of things like being half health, bolas, disablers, first baton hits, it made it so these were non options unless you are basically forced to, like with the clown.

**Comment by Moltijoe** [comment]
I could see clown shoes and duffel bag being reduced to even 0.5 and being fine. Galoshes i'm hesitant to reduce beyond 0.75 because of how powerful the effect CAN be.

**Comment by Aquizit** [comment]
I can adjust them down to 0.5 sure. Couldn't hurt anything and we can always adjust it later if it's too much. I agree with the galoshes, though, with the no-slip effect and all.

**Review by MajManatee — APPROVED** [review]
yeah sure i guess

**Comment by Aquizit** [comment]
slowdown = 0.5 -- 6.18s

updated main comment with this info

**Comment by ThatLing** [comment]
@Aquizit Can you add slowdown = 0 (so normal backpack) as a comparison

**Comment by Aquizit** [comment]
Yeah I did this yesterday too, I think it was something like 5.09s I'll add it to the main comment

**Review by Moltijoe — APPROVED** [review]
looks good, if for whatever reason it's a problem, it's easy to revert

**Pull request merged**
