### PR TITLE
Adds Redesign your logo by Lemon Demon to the lobby music

### PR DESCRIPTION
**Pull request by fluffe9911**
:cl:
rscadd: Redesign your logo my dudes
/:cl:

### CODE REVIEW

**Comment by Fillywonk** [comment]
I like this song and have listened to it casually for the past 4 years. But I don't like pop songs, and expecially songs with lyrics on the main title as a personal preference.

**Comment by Partheo** [comment]
Still not a fan

**Comment by Xoxeyos** [comment]
Not fit for the server I believe.

**Comment by jcatjmeow** [comment]
I like it personally but maybe an instrumental version could be better

**Pull request closed without merging**
