### PR TITLE
Increases amount of roundstart gang spawns from 2 to 4

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request
Will probably make things more chaotic but will hopefully decrease the amount of gang 1 snowballs threw the station while gang 2 dies incidents 
#### Changelog

:cl:  
tweak: Roundstart gangs upped to 4
tweak: Upped player req from 24 to 40
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
Doesn't it already go up to 4 on highpop? Does this mean there are always 4 gangs now?

**Comment by alexkar598** [comment]
I mean, gang balance is wayy broken anyways, maybe this MIGHT fix it

**Comment by ynot01** [comment]
40 is a little high, isnt nukies like 30?

**Comment by Marmio64** [comment]
40 isnt too high since its 4 entire conversion antags. Nukies doesn't need as many people since they can do with only 3 people against the station.

**Comment by MegaEmpirical** [comment]
Fuck I hate gangs so much.

Though would be nice if there was less snowballing.

**Review by alexkar598 — APPROVED** [review]
I honestly dont know what kind of impact this will do

**Pull request merged**
