### PR TITLE
un-nerf + buff the security cyborg

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
# Document the changes in your pull request

Security cyborgs are awful in most combat situations. Over the years, they've been endlessly nerfed, resulting in the current situation where they're both shitty as a module for combat reasons, and unpickable without an upgrade. This pull request un-nerfs them, as well as adding a new upgrade to them, allowing the printing of a baton upgrade module, which functions the same as the actual security baton's upgrade module, and allows one-hit stuns. Jamie suggested un-nerfing the security cyborgs on the basis that they're locked behind an upgrade now, so here it is.

# Spriting

Nope

# Wiki Documentation

guide to robotics, tech webs page

# Changelog

:cl:  
rscadd: cyborg baton upgrade, makes the security cyborg's stun baton instantly stun, functions the same as the normal baton upgrade
tweak: the security cyborg's disabler/laser will now draw from its internal battery
 /:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Bad

**Comment by ynot01** [comment]
Bad (i nerfed the disabler)

**Comment by Mqiib** [comment]
mmm yes lets give the absolutely stupid weapon to borgs that totally wont be annoying or awful to deal with ever at all no this is fine

**Comment by Marmio64** [comment]
they're not that strong but still really spammable in spite of everything so additional buffs seem unnecessary

**Comment by Runian** [comment]
If security can have an instant stun, then security borgs should have it too. Spammable disabler/laser gun isn't good though.

**Comment by Mqiib** [comment]
> If security can have an instant stun, then security borgs should have it too. Spammable disabler/laser gun isn't good though.

Security shouldn't have an instant stun either.

**Comment by ghost** [comment]
One hit stun sucks, I suggest giving them something like an upgrade that shortens the stuns from gettimg flashed/flashbanged.

**Comment by Smudged** [comment]
The game needs to stopped being balanced around rocket tag. 
Please stop giving things One-shot batons.

**Comment by KillerOrcaCora** [comment]
Absolutely not

**Pull request closed without merging**
