### PR TITLE
Rewrites the Corporate Lawset

### PR DESCRIPTION
**Pull request by jcatjmeow**
The new laws are:
1) The crew help generate profits if they are alive and able to work.
2) The station and its equipment help generate profits if they are maintained and functioning correctly.
3) You help generate profits if you are able to function.
4) Maximize profits.

I'm open to suggestions. I want to keep the spirit and intent behind the lawset but without the shitty wording.

### Intent of your Pull Request

The corporate lawset as it is sucks. I don't know if this is better, but it's different at least. Ideally this puts the ai more on the crew's side as they work together to make profits, vs putting the ai against the crew as the ai tries to minimize expenses from the crew. 

If you don't like this new law change, no hard feelings! Tell me so and lets try to find a corporate lawset that fits the spirit of corporate but isn't dogshit! :D

_Clarification: The point of this PR is to **replace** the old corporate. I think the old corporate is unfun to play and to play against. It encourages adversarial play and stuff like stopping people from being cloned cause "they are expensive to replace" and turning off lights cause "haha xD lights cost money". **I will not add this as an additional lawset alongside the old corporate**, this is a replacement/improvement/re-imagining._ 

Thank you! :3 😃 🎊 🎉 And if you think the name should be changed as to not cause confusion with people familiar with old corporate, let me know that too!
#### Changelog
:cl:  
tweak: changed the corporate lawset
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
This would still enable validhunting. Traitors wouldn't be doing work, and thus the AI could go grab them under law 4. They'd have to do it nonlethally but if the AI knows your a traitor it'd just send a Borg to stun you the moment you leave your department for not working

**Comment by yacabo** [comment]
Old corp allowed for valid hunting, this lawset prevents the AI from being obligated to slaughter the crew unlike old corp

**Comment by jcatjmeow** [comment]
> This would still enable validhunting. Traitors wouldn't be doing work, and thus the AI could go grab them under law 4. They'd have to do it nonlethally but if the AI knows your a traitor it'd just send a Borg to stun you the moment you leave your department for not working

Note that it says the crew generates profits if 
1) they are alive
2) they are ABLE to work

If the traitor is stunned or jailed, they are unable to work. This is something the ai should avoid unless keeping the perp unstunned is worse (for example if they are trying to murder a bunch of people or prevent them from doing their jobs in some way). 

Also note that the lawset doesn't actually care about the work the traitor is or isn't doing. As long as they are alive and able to work, they "generate profit", no matter what they are actually doing. So if you know someone is a traitor but they have only stolen something like the magboots or whatever, tough shit, you can't actually interfere because that would be rendering someone who is able to work unable to do so and thus lower profits. So ideally, only people who maim or kill, or those who destroy parts of the station can be validhunted.

If you have any suggestions on how to make the lawset more clear, please let me know!

**Comment by Hopekz** [comment]
Same shit; different wording.
I like the previous lawset more tbh so I'd be fine with adding your lawset while leaving corporate as one of the default ones.
Not sure why this is "replacing" corporate instead of just being in addition.

This isn't corporate anymore this is a capitalistic lawset

**Comment by jcatjmeow** [comment]
> Same shit; different words.

Yes that is the point I am keeping the spirit of the old lawset, while making it less antagonistic.

> I like the previous lawset more tbh so I'd be fine with adding your lawset while leaving corporate as one of the default ones.

Ok but I _don't_ like the previous lawset so I'd be fine with this replacing it! 

> Not sure why this is "replacing" corporate instead of just being in addition.

See above!

> This isn't corporate anymore this is a capitalistic lawset

No its corporate. See? It says so right there, in the title!
Also, how is it "same shit but different words" and also "isn't corporate anymore" at the same time? You seem confused, would you like me to clarify anything about the lawset?

**Comment by MenacingManatee** [comment]
I like the lawset, but I don't know about replacing corporate. I'd 100% be on board with adding it as "capitalist lawset" or something to that effect though

**Comment by ReddicusDragon** [comment]
hmm yes

**Comment by Hopekz** [comment]
> Yes that is the point I am keeping the spirit of the old lawset, while making it less antagonistic.

I don't think you are changing anything meaningful.
The words you are replacing old lawset with have the same meaning except now the fluff title isn't correct because it isn't corporate anymore.
 
> Ok but I _don't_ like the previous lawset so I'd be fine with this replacing it!

Okay then just remove corporate.
Stop trying to replace corporate with capitalism+ while still calling it corporate.

> See above!

I did see above. 
Did you read my argument? 
See above! (also re-read previous post if you're having trouble following)

> No its corporate. See? It says so right there, in the title!

Okay. Fair. 
So why not just replace the title with capitalist lawset? 
Why even settle on the same name call it peepoo lawset if the title is literally just a placeholder for you.

> Also, how is it "same shit but different words" and also "isn't corporate anymore" at the same time? You seem confused, would you like me to clarify anything about the lawset?

Because Capitalism and Corporate are similar lawsets in their interpretation except with different flavortext. They are following the exact same law interpretation with different flavortext except you're mislabeling the flavortext as corporate instead of capitalism.

**Comment by yacabo** [comment]
>I don't think you are changing anything meaningful.

>this lawset prevents the AI from being obligated to slaughter the crew unlike old corp

**Comment by jcatjmeow** [comment]
> > Yes that is the point I am keeping the spirit of the old lawset, while making it less antagonistic.
> 
> I don't think you are changing anything meaningful.

:(
> The words you are replacing old lawset with have the same meaning 

This is the general intention. I want the lawset to play differently but not so differently as to be unrecognizable and I want the 'spirit' of corporate to remain intact.
>except now the fluff title isn't correct because it isn't corporate anymore.

...but corporations exist to make money. Not to minimize expenses, to make money. I think its more accurate now!
> > Ok but I _don't_ like the previous lawset so I'd be fine with this replacing it!
> 
> Okay then just remove corporate.
> Stop trying to replace corporate with capitalism+ while still calling it corporate.

Are you familiar with the saying "remove don't improve"? While not applicable everywhere, I feel like rather than removing the lawset I could improve it by reworking it, which is what I did!
> > See above!
> 
> I did see above.

Well you could've fooled me! 
> Did you read my argument?
> See above! (also re-read previous post if you're having trouble following)

I did! That's why I quoted the entire thing bit by bit and responded to all of it. Glad you noticed! 😄 
> > No its corporate. See? It says so right there, in the title!
> 
> Okay. Fair.
> So why not just replace the title with capitalist lawset?
> Why even settle on the same name call it peepoo lawset if the title is literally just a placeholder for you.

I feel like you misunderstand. This is a replacement corporate. This is **not a new lawset** it is a **re-tooling of corporate**. The title is not a placeholder, the title is corporate. Please read the pr description before commenting! That way our discussions can be as productive as possible! 
If you would prefer to call it peepoo lawset, I will have to respectfully disagree with you on that one, as it would not foster the mrp experience we are going for, plus that title is rather nonsensical.

> > Also, how is it "same shit but different words" and also "isn't corporate anymore" at the same time? You seem confused, would you like me to clarify anything about the lawset?
> 
> Because Capitalism and Corporate are similar lawsets in their interpretation except with different flavortext. 

They are similar! But they differ in a few key ways, namely this lawset is much more on the crew's side, less antagonistic, and more forgiving vs antags who haven't murdered or destroyed anything. Plus it just makes more sense, in my opinion. So I have to respectfully disagree with you on this point. 
>They are following the exact same law interpretation with different flavortext except you're mislabeling the flavortext as corporate instead of capitalism.

Once again you seem to be confused. No lawset named "capitalism" exists. Corporations exist to make money, so this is perfectly thematic. No mislabeling is going on! 😄 

If you are still confused, please let me know specific questions you have so I can answer them! ❤️ And thank you for your interest in my pr! Negative feedback is very useful in refining ideas!

**Comment by Hopekz** [comment]
> > Because Capitalism and Corporate are similar lawsets in their interpretation except with different flavortext.
> 
> They are similar! But they differ in a few key ways, namely ....

Okay well the main disconnect we are having is you calling it corporate while acknowledging that they "differ in a few key ways" .

You turned a pinecone in to a kiwi without calling the end result a kiwi.

In that case the proper change would be:
- Removed pinecone
- added kiki

what you did:
- modified the pinecone to be a kiwi while still calling it a pinecone

**Comment by Lynameep** [comment]
I'm all for this as it sucks in a fun way; not a boring way.

**Comment by jcatjmeow** [comment]
> Okay well the main disconnect we are having is you calling it corporate while acknowledging that they "differ in a few key ways" .
> 
> You turned a pinecone in to a kiwi without calling the end result a kiwi.
> 
> In that case the proper change would be:
> 
> * Removed pinecone
> * added kiki
> 
> what you did:
> 
> * modified the pinecone to be a kiwi while still calling it a pinecone

how I see it is I changed the pinecone from a shortleaf pinecone to a lollylob one. Yes, they are different, but they are still both pinecones. They have the same general structure and function! If you would like, I can call this new one "corporate 2" or something? But either way I'm tossing corporate 1 so I don't see the point

**Comment by Hopekz** [comment]
> If you would like, I can call this new one "corporate 2" or something? 

This isn't "corporate 2" in the same way it isn't "corporate"

> But either way I'm tossing corporate 1 so I don't see the point

Not sure where the disconnect is.
I used a fruit explanation for your fruit logic because you are literally coming back to my point a second time while completely missing it.

You keep saying this change makes it different with "key differences" but won't rename it from corporate. 
You are literally admitting "corporate 1" is being removed so now rename it to something more fitting like "capitalist"

There is a reason the crew version of Asimov is not called Asimov anymore. This isn't Corporate anymore so just remove corporate and rename this as the replacement.

Why is this so hard to understand especially since you've supposedly agreed to my reasoning twice now.

**Comment by jcatjmeow** [comment]
> This isn't "corporate 2" in the same way it isn't "corporate"

But it literally is corporate! It says so right there! That's what the lawset is, and it's the best way to describe it. When someone says corporate what do you think of? For me, I think of a board of directors trying to squeeze as much profit and efficiency out of their company as they possibly can. While "capitalist" can also describe this, its a much more nonspecific term than corporate. Someone can be a capitalist and be dirt poor, or a small business owner, or an app developer, or an activist etc etc. Meanwhile, corporate means one specific thing, so I like it a lot more! 😄 

> Not sure where the disconnect is.
> I used a fruit explanation for your fruit logic because you are literally coming back to my point a second time while completely missing it.

Fruit logic? Woah there buddy! I have been nothing but civil. No need for petty insults! 
I didn't miss your point, I disagreed with it. 
> You keep saying this change makes it different with "key differences" but won't rename it from corporate.

Yes. It has key differences. That's the entire point of the pr. But it is not different enough, in my opinion, to deserve another name. As you yourself said several times, it's still very similar. 😄 
> You are literally admitting "corporate 1" is being removed so now rename it to something more fitting like "capitalist"

But corporate is more fitting than capitalist. A corporation is an organization that tries to make money. I think that fits this role I have put on the ai very much.

I considered the names "executive" or "ceo" before deciding that this keeps the spirit of corporate just fine, and no name change is needed. If lots of people get very confused I'll change it but I really don't think anyone else will. Pretty much everyone else who I have talked to has understood what I'm doing here, even people who disagree with the pr. 
> There is a reason the crew version of Asimov is not called Asimov anymore. 

The reasons is because both exist at the same time. It would be confusing to have two Asimovs that are different from each other. Wouldn't that be wacky! 🤣 If someone changed Crewsimov around a little bit, but the core of the lawset was still the same, I think we both would be still calling it crewsimov!
>This isn't Corporate anymore so just remove corporate and rename this as the replacement.

It is corporate still. The idea behind the lawset is the same. The spirit is the same. And, if all goes to plan, the lawset encourages you to play an amoral, money/productivity obsessed robot in a managerial role. Is that not the most corporate thing you have ever heard? I don't think the terms capitalist does it justice. "CEO" is a better alternative, but I don't think an alternative is necessary when corporate works just fine!
> Why is this so hard to understand especially since you've supposedly agreed to my reasoning twice now.

I'm not missing your point and agreeing. I read your point loud and clear, and decided it wasn't very good and that I disagreed. That's allowed, right? 😅 I'm sorry it wasn't clear that I disagreed with calling it capitalist, so I hope that's more clear now! 🙏 :D

Please be more civil! I think the exchange of ideas is important and it doesn't need to be bogged down by insults! 🕺

**Comment by Lynameep** [comment]
Watching HopeK lose an argument to jcat is probably the funniest fucking thing I've seen all day.

**Review by Hopekz — CHANGES_REQUESTED** [review]
Give the lawset a more appropriate name.

**Comment by jcatjmeow** [comment]
> Give the lawset a more appropriate name.

Nope!

Please actually read my response. You posted this 3 minutes after I posted it, and you clearly haven't read it, because I clearly articulated my reasons why the name is why it is. Thank you! If you try to use your git powers to bully me into making a change you personally want I will have to make an admin complaint or a ticket, and I'd rather just agree to disagree on this one! Thanks!

**Comment by Hopekz** [comment]
> > Give the lawset a more appropriate name.
> 
> Nope!

It is now a requirement for merge unless you go "around" me.

**Comment by Xantam-13** [comment]
@Hopekz to clarify, this won't be closed because he refuses to change the name of it, right? He can seek someone else to review right?

**Comment by Hopekz** [comment]
> @Hopekz to clarify, this won't be closed because he refuses to change the name of it, right? He can seek someone else to review right?

Me closing this PR because of that would be a little ridiculous.
Our usual process still applies I am just the only maintainer at the moment to have left my review.

Also, Monster speed merged this round start law change so it is irrelevant now.

**Comment by jcatjmeow** [comment]
@Hopekz I want to thank you for your input! It was very useful and helpful and productive! I only wish you are more considerate of alternative viewpoints to your own the next time you review a pr. Best of luck! 😄

**Comment by Moja10** [comment]
This is absolutely not the PR to be merged in 4 hours after creation.

**Pull request merged**
