### PR TITLE
I removed circuits from yogbox because I don't like them [NOT CLICKBAIT]

### PR DESCRIPTION
**Pull request by Ktlwjec**
In case #3316 gets merged.

image

:cl:  
rscdel: Circuits have been removed from the Yogbox Science department.
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
no fun allowed

**Comment by CMOisLing** [comment]
Rip, also if your going to add two nanite stations and cloud servers at least add another programmer or whatever the one that sets the program settings is called

**Comment by Ktlwjec** [comment]
Not needed but I need to remove the thingies from the left-side table anyway so I'll see how it looks with another one in.

**Comment by Amelia0010** [comment]
ok nevermind I guess

**Pull request closed without merging**
