### PR TITLE
You can now send PDA messages with the enter key

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request
Fixes a broken import
also fixes an issue with inferno

Fixes all <Button.Inputs>
# Changelog

:cl:  
bugfix: you can now send pda messages with the enter key
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Now make them not send out unless you intend for a message to be sent out so it doesn't auto send when you click off it

**Comment by redmoogle** [comment]
> Now make them not send out unless you intend for a message to be sent out so it doesn't auto send when you click off it

#15761

**Comment by Hopekz** [comment]
> > Now make them not send out unless you intend for a message to be sent out so it doesn't auto send when you click off it
> 
> #15761

Excellent

**Comment by Cartlord** [comment]
who do i bribe for a speedmerge

**Comment by Hopekz** [comment]
> who do i bribe for a speedmerge

Jamie accepts Paypal

**Comment by ShoziOffical** [comment]
now make it has job titles behind the names

**Comment by redmoogle** [comment]
> now make it has job titles behind the names

Its already az sorted or is about to be

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
