### PR TITLE
Revert "Adds radio SFX"

### PR DESCRIPTION
**Pull request by boodaliboo**
Reverts yogstation13/Yogstation#9404
i truthfully find it incredibley annoying

### CODE REVIEW

**Comment by Mesalikepie** [comment]
Maybe make it a preference? I love the sound effect personally

**Comment by maxion12345** [comment]
it'd be better if it was one sound instead of two, with a preference option

**Comment by ynot01** [comment]
i reallyyy like it

**Comment by boodaliboo** [comment]
it just is incredibly distracting for me i would much rather like it being a preference but i cant code that

**Comment by Firewolf34** [comment]
Do not just remove this. Add an option to disable it, if you don't like it.

Considering nobody pays any attention to the damn chat these days, because of the runetext, we need some way to stop people from walking around with radio mics on.

**Comment by boodaliboo** [comment]
> Do not just remove this. Add an option to disable it, if you don't like it.
> 
> Considering nobody pays any attention to the damn chat these days, because of the runetext, we need some way to stop people from walking around with radio mics on.

i have no clue how to add one so im doing the next best thing

**Comment by alexkar598** [comment]
Most people seem to like it to shrug

**Pull request closed without merging**
