### PR TITLE
Adds special The Wizard

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Adds Chris Remo - The Wizard to lobby music
req. by art director

#### Changelog

:cl:  
rscadd: Adds Chris Remo's The Wizard to lobby music
/:cl:

### CODE REVIEW

**Comment by overlord12345** [comment]
can you post a link to the song atleast

**Comment by swissloaf** [comment]
> can you post a link to the song atleast

literally if you check commits you can find the song

**Comment by athena413** [comment]
yes

**Comment by boodaliboo** [comment]
add a link to the song

**Pull request merged**
