### PR TITLE
Fixes Janitor's oxygen supply on Metastation

### PR DESCRIPTION
**Pull request by Xoxeyos**
# Document the changes in your pull request

Fixes the Janitorial supply closet's ventilation system, no longer will they be free of plasma-free air.

# Changelog

Janitorial supply closet on Metastation has had it's atmospherics fixed.

:cl: Xoxeyos
bugfix: The janitorial supply closet on Metastation has had it's atmospherics fixed.
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
who could have done this

**Comment by Xoxeyos** [comment]
https://github.com/yogstation13/Yogstation/issues/13128

**Comment by Xoxeyos** [comment]
> who could have done this

I wonder too.

**Review by patpol4 — APPROVED** [review]
Oops

**Pull request merged**
