### PR TITLE
General Gax Departmental + Maintenance Improvements

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Janitor closet shuffled around to not make awkward lockers:
image

Kitchen maint door moved:
image

Bartender gets window:
image

1x1 doors in Bar:
image

AI core + Toxins launch got moved down one tile to fit more things in maint + ATMOSPHERIC STORYTELLING:
image

Xenobio moved down + more maint + BZ can + stuff in the holding pen + egg:
image

Theatre backroom has stuff on table + mirror:
image

EVA is redone along with some extra maint areas + escape being moved up for shuttles to not clip maint:
chrome_pEiGsN1CcK

Confession booth for Chaplain:
image

# Changelog

:cl:  
mapping: Moves GaxStation Xenobiology + Secondary AI Core + Toxins Launch down to give more maintenance room
mapping: Tweaks various GaxStation Service rooms to have more things + better layout
mapping: More Water tanks + helpful lockers around GaxStation
mapping: Moves escape more north to give more maint room + redoes EVA
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Why can i only access the morgue from outside of medbay as a paramedic?

Or i suppose, why is the surgery room a pathway in or out of medbay

**Comment by ToasterBiome** [comment]
> Why can i only access the morgue from outside of medbay as a paramedic?
> 
> Or i suppose, why is the surgery room a pathway in or out of medbay

Because it opens into surgery.

**Comment by Moltijoe** [comment]
> Because it opens into surgery.

guh, if i knew how to map i'd redo gax medbay myself

**Comment by ToasterBiome** [comment]
> > Because it opens into surgery.
> 
> guh, if i knew how to map i'd redo gax medbay myself

What would you like changed about it? I'm happy to take a crack at a redesign.

**Comment by Moltijoe** [comment]
> What would you like changed about it? I'm happy to take a crack at a redesign.

spent some time looking at it and put together a list

### Things i don't like
Treatment shouldn't be directly in the middle of the path
Stasis bed and sleeper should probably be against a side wall rather than around a central pillar
Surgery should probably be a dead-end
Surgery observation should be on the inside of medbay
Morgue should be accessible from both inside and outside of the medbay without needing to go through other rooms
Maints should be accessible to everyone inside regardless of medbay access (probably connected to the main hallway somehow, or at least treatment, rather than being limited to either storage or chem access)
Virology engineering room being connected to the airlock rather than virology itself is weird
Medkits should probably be in storage rather than treatment but i suppose it doesn't matter that much, just helps with theft


### Things that i like
Combining the break room and storage is pretty nice since no one ever uses the break room
chemistry being so close to treatment
Paramedic room is pretty much perfect, at most it could be shrunk by a couple tiles


### Things that i'm indifferent to (change or not, i don't care)
CMO room
Security room
Genetics and cloning

**Comment by MajManatee** [comment]
wow he really went hard on the list of "things i dont like"

**Comment by Moltijoe** [comment]
> wow he really went hard on the list of "things i dont like"

doesn't help to "pull punches" since medbay is probably the department that good layout matters most

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
