### PR TITLE
Latex and Nitrile gloves make surgery faster

### PR DESCRIPTION
**Pull request by Moltijoe**
Weird that the medical gloves don't do anything for medical aside from faster picking up bodies
conditionally speeding up surgery should make cloning less enticing

:cl:  
rscadd: Latex and Nitrile gloves make surgery faster
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
could you give brig physician nitrile gloves as well? if they don't already, last i played they don't

**Comment by Moltijoe** [comment]
> could you give brig physician nitrile gloves as well? if they don't already, last i played they don't

sure, already did for mining medic

**Comment by ChuChu42** [comment]
JESUS CHRIST FINALLY!!!

**Comment by ReddicusDragon** [comment]
bad pr, lizbay needs nerfed not buffed

**Comment by Moltijoe** [comment]
> bad pr, lizbay needs nerfed not buffed

then nerf lizards

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
