### PR TITLE
MAKES FLY PEOPLE ROUNDSTART

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
fly people don't have anything inherently good and it would be fun to have them roundstart
#### Changelog

:cl:  
rscadd: Added fly roundstart
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
ty theos

**Comment by overlord12345** [comment]
Oh god there's gonna be so much vomit

**Comment by drderp3635** [comment]
Snail people when

**Comment by MegaEmpirical** [comment]
They eat the vomit so it goes away.


Also: yesssssss

**Comment by Lynameep** [comment]
Good meme-pr.

**Comment by DerelictDrone** [comment]
If this happens we need a vomit bar to go with it.

**Comment by ynot01** [comment]
isnt config serverside

**Comment by AsV9** [comment]
It is @ynot01

**Comment by Szyszkrzyneczka** [comment]
Good pr merg ples

**Comment by boodaliboo** [comment]
mrgf ;p,sae i want merg it god pr please add brszil number one

**Comment by MegaEmpirical** [comment]
Whyyyyyy

**Pull request closed without merging**
