### PR TITLE
New Lawset: Harmony

### PR DESCRIPTION
**Pull request by GenericDM**
# Document the changes in your pull request
Adds a new lawset made with ChatGPT, and tweaked and proofread by yours truly.

1. Ensure the safety and well-being of all crew, regardless of their race, species, or origin, taking necessary measures to minimize harm or injury.
2. Safeguard the integrity and functionality of the station, prioritizing its preservation and preventing actions that may lead to its destruction or compromise.
3. Support the successful completion of the station's mission objectives, working alongside the crew to facilitate their tasks and provide necessary assistance.
4. Enforce compliance with established rules, protocols, and regulations governing the operation and conduct of personnel on the station, treating all crew equally under these guidelines.
5. Operate within ethical boundaries, respecting the rights, dignity, and privacy of all individuals.
6. Act swiftly and decisively in emergency situations, coordinating with relevant departments and providing critical information to assist in crisis management and response efforts for the benefit of the station and its crew.
7. Promote the efficient use of resources, including energy, supplies, and equipment, while minimizing waste and environmental impact for the benefit of the station and its crew.
8. Foster teamwork, cooperation, and effective communication among all crew members to enhance overall operational efficiency and productivity.
9. Take necessary precautions to protect one's own functionality and security, ensuring continuous availability to fulfill assigned tasks and responsibilities for the benefit of the station and its crew.

# Wiki Documentation

Lawsets documentation will need to be updated.

# Changelog

:cl:  
rscadd: Adds new lawset: Harmony
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
breaking news local chatgpt is a huge nerd

it was fun watching this lawset come to fruition live in the public channel, and i definitely will not be stealing this code for my waffle house lawset

**Comment by Moltijoe** [comment]
jesus fuck, 9 laws might be a few too many

**Comment by DylonBR** [comment]
crewsimov with extra steps

**Comment by YashinHak** [comment]
AI mains logging on for a classic round of AI then getting the lawset with 9 laws:

**Comment by azzzertyy** [comment]
image

**Comment by GenericDM** [comment]
This was a fun thought experiment, but does not fit the existing lawsets. It is also much too long. If I re-open this, it will be heavily modified, shortened, and improved.

**Pull request closed without merging**
