### PR TITLE
Revert "Cycling Airlocks"

### PR DESCRIPTION
**Pull request by boodaliboo**
Reverts yogstation13/Yogstation#7874
these are fucking awful they take way to long

### CODE REVIEW

**Comment by Marmio64** [comment]
thank you, you are doing gods work

**Comment by boodaliboo** [comment]
fuck you map files

**Comment by Bibby0110** [comment]
Only remove them from the map.
Don't remove the actual object

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
If the problem is that they take too long, speed them up.

**Comment by boodaliboo** [comment]
fine

**Comment by alexkar598** [comment]
The reason for them taking too long is that atmos and machine can't tick fast enough

**Pull request closed without merging**
