### PR TITLE
instant unwrench when total mole below 0.01

### PR DESCRIPTION
**Pull request by warface1234455**
for some reason when you attempt to remove pipe when total mole is at 0 it wont do the instant-unwrench because it still detect some trace 0.00000000000001 mole left so yeah

# Document the changes in your pull request

instant unwrench when total mole below 0.01

# Wiki Documentation
in document of change

# Changelog

:cl:  

tweak: instant unwrench when total mole below 1
/:cl:

### CODE REVIEW

**Review by MajManatee — APPROVED** [review]
Idk if its a good idea, but it looks fine

**Comment by ShoziOffical** [comment]
> Idk if its a good idea, but it looks fine

unwrench gas pipe when mole is below 1 barely release any gas so i think its fine

**Comment by iamthesilly** [comment]
> unwrench gas pipe when mole is below 1 barely release any gas so i think its fine

Me when I unwrench a pipe with 0.5 moles of plasma at 1 million kelvin and die instantly

**Review by SapphicOverload — CHANGES_REQUESTED** [review]
You should use MINIMUM_MOLE_COUNT instead of 1, also check for unsafe_wrenching too so you don't instantly unwrench an unsafe pipe.

**Comment by ShoziOffical** [comment]
> > unwrench gas pipe when mole is below 1 barely release any gas so i think its fine
> 
> Me when I unwrench a pipe with 0.5 moles of plasma at 1 million kelvin and die instantly

no you dont the heat will spread out and decrease

**Review by SapphicOverload — APPROVED** [review]
Yeah looks good

**Pull request merged**
