### PR TITLE
regenerative cores now no longer fully heal the user because i'm not going to fucking let up

### PR DESCRIPTION
**Pull request by ghost**
instant application full adminheals are stupid and you guys know it

instead they heal -25 of all damage, except for clone, which they heal -50 of

they can still be applied instantly so you can still heal in combat with them, they're just now less effective than retreating to use a patch instead of MORE effective

xenobio shouldn't be better at being medbay than medbay

i'd give them a delay on self application too, but that's up for debate and i'd have to raise their numbers a little

#### Changelog

:cl:  
tweak: xenobiology regen cores now heal -25 of all damage types, except for clone, which they heal -50 of. all other effects remain the same.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
They already don't fully heal retard

**Comment by ghost** [comment]
yeah they do

**Comment by HomocidlePancakes** [comment]
Just played a miner shift. No, they don't. We had it merged from TG for god knows how long

**Comment by ghost** [comment]
also damn son that took 23 seconds to respond

**Comment by ghost** [comment]
dude i'm talking about XENOBIO regen cores not hivelord cores

**Comment by ghost** [comment]
read the  fucking PR next time

**Comment by ThatLing** [comment]
this is a very fast thread

**Comment by HomocidlePancakes** [comment]
Yes it is

**Comment by HomocidlePancakes** [comment]
Fuck xeno

**Comment by ThatLing** [comment]
also if you'd look at the code you would see they fully heal

**Comment by ghost** [comment]
it's my friend homocidal

he's very fast in all aspects of his life

i'm talking about sex. i'm saying he has premature ejaculation problems

**Comment by ThatLing** [comment]
you would also see that mr community banned is talking about xeno cores

**Comment by ghost** [comment]
i am NOT community banned i am REGULAR banned but forever

**Comment by HomocidlePancakes** [comment]
This thread is so fast, noone will see me sasying the nword

**Comment by AdamElTablawy** [comment]
ni

**Comment by ThatLing** [comment]
alexkar is gonna have a field day with this pr

**Comment by ghost** [comment]
alex is going to make 99 irrelevant reviews the fucking BurnMix PR still gives me nightmares

**Comment by MonsWTF** [comment]
This technically fixes a lot more than is immediately apparent in the PR, but I'll withhold that for now, what matters is it's a nerf and a fix.

Also one less thing for me to balance in the coming days.

I would suggest also taking from [tgstation/tgstation#47178](https://github.com/tgstation/tgstation/pull/47178) to have Regenerative extracts also dye the target's hair Purple, because why not?

**Comment by AnonymousNow** [comment]
This is veering into saltcode territory.

**Comment by drderp3635** [comment]
It isnt veering into salt code, it is salt code, everything adam makes is 

Also purple hair change is bad because it only discourages xeno helping with the crew

**Comment by MonsWTF** [comment]
In defense, most of the 'salt code' comes off as meme-y to me, with there being actual change substance behind the circlejerk title. 

I think it's fair to say that 100% full-heal is quite useful and potentially overpowered. Is 25% heal the right amount? Maybe, maybe not. I am personally inclined to say 'not enough' but I 1) like Xenobio, and 2) haven't encountered enough situations where it would have a significant impact. However, Xenobio barely has interactions for the time being outside of its office and Science. Seeing the nerf should help to measure its efficacy moving forward and as more changes to Xeno roll in.

**Comment by MonsWTF** [comment]
@AdamElTablawy I think one thing that needs to get addressed in addition to the changes made so far (and what I suggested above) is the Stabilized Rainbow interaction. Post-merge, the Stabilized Rainbow will simply bring the person back out of crit and in a weakened state, and likely to go right back into crit again. Should Regen's applied via Stabilized Rainbow follow a different set of rules?

**Comment by alexkar598** [comment]
@Thatling @adamtyenerd

Ive stopped moderating big PRs because oak gets sad and cries 

Those marked as off topics weren't me btw

**Review by alexkar598 — APPROVED** [review]

**Comment by ghost** [comment]
@MonsWTF 

post merge rainbow stabilized will simply put them at 25 health, which is fair, for instant application.

i don't see any reason to have anything else given the different traits of regenerative cores means that the person attackin you will likely end up fucked

**Pull request merged**
