### PR TITLE
Revert "Resprites pressure tanks"

### PR DESCRIPTION
**Pull request by Cartlord**
Reverts yogstation13/Yogstation#22334
I think they look terribly ugly, and don't fit with the tiles around them - the shading at the edges, in particular, just looks bad to me.

# Changelog

:cl:   
rscdel: Removed the new pressure tank sprite
rscadd: Brought back the old pressure tank sprite
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
The old version looks significantly worse, it was just a blank cube

**Comment by Cartlord** [comment]
@Moltijoe  you're thinking of the wrong sprites, those were removed by https://github.com/yogstation13/Yogstation/pull/21715 - and then the sprite got changed AGAIN by the P.R. I'm reverting

**Comment by Cartlord** [comment]
I don't know if the @Moltijoe ping worked since I edited it into the message after posting, so I'm doing it again - I do apologize if this results in a double ping.

**Comment by Scrambledeggs00** [comment]
It would help if you posted pictures of the sprites you're reverting back to.

**Comment by Cartlord** [comment]
PressureTankBlank
it didn't work before but it does now
i want these back and this brings them back

**Comment by Moltijoe** [comment]
> @Moltijoe you're thinking of the wrong sprites, those were removed by #21715 - and then the sprite got changed AGAIN by the P.R. I'm reverting

ah, i wasn't aware

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
can you make the old sprites use GAGS

**Comment by Cartlord** [comment]
> can you make the old sprites use GAGS

-why? pressure tanks are weird & situational enough, mapping-wise, that i don't see any circumstance where someone actually needs to add another for a different gas - meaning the increased ease of making new sprites for them would be irrelevant.
-i don't have that knowledge, but i can probably learn it
-i assumed they already used it, given that https://github.com/yogstation13/Yogstation/pull/21715 got merged by you after you made that request

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
can u test this and make sure it actually works

**Comment by Cartlord** [comment]
I don't understand why I'd need to test a revert, but fine.
I will get back to this.

**Pull request closed without merging**
