### PR TITLE
Syndicate Icemoon Revision 2.1: You Fuck Around and Find Out

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Gives Syndicate Icemoon the following:

Turns relay room in engi into EVA storage, moves engi suits there, moves relay to vault and disables heat gen

Fixes piping and atmos issues (cryo and vault respectively)

Gives the agents codespeak

One single box of donkpockets

Moves the NT corpse outside (keeps the morgue)

# Why is this good for the game?

Fixes bugs, provides more QoL, codespeak

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Syndicate Icemoon has fucked around and found out once again! On a related note, we got the budget to teach them codespeak.
/:cl:

also im apparently supposed to test shit???
https://drive.google.com/file/d/1cruqP7oMWAzo043WGjeartql8qbMdsXb/view?usp=drive_link

### CODE REVIEW

**Comment by KonKonBreezeFox** [comment]
can we have the turrets shoot mechs too?

**Comment by Addust** [comment]
next best thing, ions

**Comment by Addust** [comment]
recall implants added, cant griff if you cant even climb the ladder!

**Comment by neeshacark** [comment]
given some things working the way they do, i don't think the recall implant will even work

**Comment by Addust** [comment]
> given some things working the way they do, i don't think the recall implant will even work

i tested it (video attached)

**Comment by SomeguyManperson** [comment]
Quite interesting watching someone map in countermeasures to any possible way for their favorite ghostrole to be attacked. I wonder how long it will be until the turrets are replaced with the ones on the nukeop ship?

**Comment by Addust** [comment]
> Quite interesting watching someone map in countermeasures to any possible way for their favorite ghostrole to be attacked. I wonder how long it will be until the turrets are replaced with the ones on the nukeop ship?

i may be focusing on ensuring they can fight back but penetrator turrets are overkill

**Comment by Addust** [comment]
draft until i figure out how to remove anything that can aid escape from the imprinter

**Comment by Addust** [comment]
fuck this ill figure out a seperate solution

**Pull request closed without merging**
