### PR TITLE
Extools Patch for 515, Should be backwards compatible

### PR DESCRIPTION
**Pull request by JamieD1**
:cl:  
rscadd: backwards compat for extools 515/514
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Extools pr: yogstation13/extools#19

**Review by adamsong — CHANGES_REQUESTED** [review]
Do not merge until extools works

**Comment by adamsong** [comment]
Need a linux binary to get tests to pass, or roll back test version

**Comment by Bibby0110** [comment]
did not work

**Pull request closed without merging**
