### PR TITLE
Five Layer Burrito

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Adds the 5 layer burrito

image

Tested
image

Def didnt come up because ToG was describing a layer manifold as a "5 Layer Burrito"

### Why is this good for the game?

More food is always good right?

#### Changelog

:cl:  
rscadd: Adds Five Layer Burrito
/:cl:

### CODE REVIEW

**Comment by TheReddDragon** [comment]
-1 changelog poorly formatted

**Comment by TheReddDragon** [comment]
I change that to a +1 since the changelog is fixed

**Comment by Jarod1200** [comment]
Hell yes

**Review by fluffe9911 — APPROVED** [review]
funny joke code looks fine

**Pull request merged**
