### PR TITLE
Removes blood brother bundles

### PR DESCRIPTION
**Pull request by AsV9**
### Intent of your Pull Request

This PR reverts #5310 and #5399
The traitor bundles have a value of over 20 TC, and giving a team of traitors >40 TC kinda defeats the point of the entire gamemode and having to cooperate and all that shit.

:cl:  
rscdel: Blood brothers no longer spawn with traitor bundles.
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
but they are gimmick bundles that no one ever buys

**Comment by Altoids1** [comment]
Since https://github.com/yogstation13/Yogstation-TG/pull/5310 was a council vote, I'd recommend clearing this with council before merging.

**Comment by nesisknesis** [comment]
people should just git gud smh

**Comment by Ratvar** [comment]
Having to cooperate is a weakness because RNG of rolling a competent teammate is abysmal. Bloodcult and infinite buffs of stunarms, mirrorshields, stunspears and such, with 9 looses 1 win in a month show that team based antags gain almost nothing from cooperation, and that gimmick doesn't work at all as intended, instead just becoming a hard objective to keep an idiot alive. 
Saying that 2 bundles are worth 40 tc, while true, does not show how those bundles do not integrate well with each other, leaving bloodbrothers with much less actual power then 20 normal traitor tc's emag revolver/esword emp mix.
Why "the way gamemode was intended to be" is a priority over player's fun, and why "tc numbers" are used as a balancing factor at all?

**Comment by Alek2ander** [comment]
Brothers as intended (without gear) are far more healthy in an environment with tg's murderbone rules.

**Comment by HomocidlePancakes** [comment]
Give them fucking telepathy already jesus christ.

**Comment by HomocidlePancakes** [comment]
Just gonna recite what I said when this was implemented

77CF82B4-777A-45CD-B2B1-8FA66720F0ED

**Review by alexkar598 — APPROVED** [review]

**Comment by ynot01** [comment]
ill try my hand at making a functional uplink if this merges, hopefully ive learned a little more about dreammaker by now

**Comment by HomocidlePancakes** [comment]
Blood brothers. Do not. Need. An uplink.

**Comment by MacHac** [comment]
Blood brothers are consistently one of the least-liked modes for a good reason, and if they're too strong with actual gear then we should look at removal or a major rework. ([TG poll](https://tgstation13.org/tgdb/irvpolltally.php?id=203) eliminates it third, note that pure Traitor comes out on top.)

I turned it off in disgust after the umpteenth brother in a row that either contributed nothing or got scooped by security and disappeared, but it generally struck me as boring and often frustrating.  Traitors using codewords are a better blood brothers experience than blood brothers, since if the other guy beats a security officer over the head with a liquor bottle and gets executed you don't automatically redtext.  Plus, the traitor gear offers a variety of diverse approaches, rather than hoping to god that your partner has enough sense to start beating the guy when you do.

Giving syndicate gimmick packs at least adds diversity and a little much-needed survivability to the mode, and it gives relatively useless brothers (clerk with a CE brother) an opportunity to contribute beyond going AFK in dorms.  Plus, the greentext rate is still abysmal, so brothers probably need the help.

**Comment by ThatLing** [comment]
@MacHac This is a shitty solution to that problem though

**Comment by MacHac** [comment]
However bad this is, it's better than the brothers having nothing.  I worry that removal instead of replacement is a win for team 'brothers don't need a buff' instead of team 'brothers need a more thought out, fitting buff'.

Trying to buff these modes in the first place tends to cause massive backlash, wailing and gnashing of teeth, the council getting involved, etc.  If we want blood brothers to keep any sort of buff, we should put it in as a replacement now instead of trying to get it merged later.

**Comment by AsV9** [comment]
[https://forums.yogstation.net/index.php?threads/vote-merge-6348.19434/](https://forums.yogstation.net/index.php?threads/vote-merge-6348.19434/)

**Pull request merged**
