### PR TITLE
[Space Bar] More kitchen room and an oven

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

Adds some more room in the kitchen for the bartender to work if they're making lots of food. Couple more tables to work on. Moved the fridges to be more out of the way at the rear of the kitchen.
Added an oven so bartender can make bread, buns, pizza, and other bar food staples.

image

# Changelog

:cl:  
mapping: Expanded Space Bar kitchen
mapping: Gives space bar kitchen an oven
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Picture?

**Comment by Aquizit** [comment]
Oh my god I'm such an idiot. I'll get the picture in the morning my bad.

**Review by patpol4 — APPROVED** [review]
No worries, i can visualise dmm files from text in my head and its fine

**Comment by Aquizit** [comment]
I updated the initial post anyway with an image for those who can't. :^)

**Pull request merged**
