### PR TITLE
[TESTMERGE ONLY] F#!& your infinite research points

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

Removes centcomm miasma canisters.

# Why is this good for the game?

Baio told me to.

# Testing

I didn't it's just deleting 2 map things.

# Changelog

:cl:  
mapping: Miasma cans on centcomm gone
/:cl:

### CODE REVIEW

**Comment by milk-is-cool** [comment]
coder moment

**Comment by Aquizit** [comment]
> coder moment

just doing what my boss told me to

**Comment by Beeper-Skeeper** [comment]
you think cowbot is gonna say something about this

**Comment by Yarinoi** [comment]
so thats what kept making sci get a shitton of points roundstart?
hilarious

**Comment by MommaDragon** [comment]
Okay, how did they abuse this?

**Comment by Yarinoi** [comment]
> Okay, how did they abuse this?

miasma when heated up to some amount converts into oxygen and generates research points
a canister of miasma started at centcom (presumably) heated up and became oxygen on roundstart
and since its centcom there was probably an ungodly amount, ergo ungodly research points

**Pull request closed without merging**
