### PR TITLE
Revert Xeno chestbursting gibs brain

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

No, a simple chestbursting doesn't have the larva eat the brain.

#### Changelog

:cl:  

rscdel: xenos chestbursting now causes crippling brain damage instead of destroying the brain outright

/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
“We purposefully make things dangerous and then someone else trivilizes the consequnces” Hugbox GTFO

**Comment by ghost** [comment]
Imagine a team antag that's not deconvertable, is wildly OP, has access to THREE different kinds of stuns, and a 'conversion method' that deletes the one thing that makes the person clonable. Also making a come back against this kind of antag wipes out 50-90% of the crew, making them either unclonable due to a brain removing gib or one of the antags destroying the cloner APC.

I'm only removing ONE of the many issues with xenomorph.

**Comment by HomocidlePancakes** [comment]
Hm, you screech about “issues” that are alot more serious then this one and yet for some reason you tackle only this. Mind explaining why?

**Comment by ghost** [comment]
I'm doing this one at a time so the headcoders can pick and choose.

**Comment by HomocidlePancakes** [comment]
Oh, so you surely have a plan then, right? If you intend on making more changes related to this one, then it’s impossible to properly evaluate this PR without the full picture.

**Comment by HomocidlePancakes** [comment]
I am still waiting on thouse other changes you mentioned before (implying you even thought up any lol)

**Comment by HomocidlePancakes** [comment]
Trying to just sit this out silently won’t do ya any good laddie.

**Comment by deadmomo69** [comment]
I personally disagree with this, although lore accurate the aliens franchise, this stops a miner from getting infected by a face hugger and being cloned, and being like 'hey everythings hunky dorey now!!! and I caused an alien outbreak so all good', or some stupid thing like that.

**Comment by alexkar598** [comment]
I don't like this change and it seems noone is willing to merge this so imma close it,if another maint wants this then they can reopen the PR or some shit.

**Comment by SomeguyManperson** [comment]
Miners can't even get xenos any more so I'll make this cause the brain damage thing and it should be good. Any xenos are caused either by adminbus or by the random event.

**Pull request merged**
