### PR TITLE
Heads of Staff can no longer roll traitor or changeling

### PR DESCRIPTION
**Pull request by Takahiru**
Being able to get funny roundstart all access and a free not suspicious pass because there was no captain is pretty darn powerful, it can pretty much guarantee a greentext may someone roll a head of staff as antag, and there's no captain present.

Controversial!

### CODE REVIEW

**Comment by Jarod1200** [comment]
i think you should make this true on lowpop when there is less likely for there to be security or a real captain and then make it false on highpop

**Comment by ynot01** [comment]
total coincidence that this just happened 10 minutes ago right

**Comment by Takahiru** [comment]
coincidence i swear sure i can do that jarod

**Comment by ynot01** [comment]
traitor & ling should be enabled for sec tbh

**Pull request closed without merging**
