### PR TITLE
[BALANCE] Ability to build PDA and Phone just like tablet and laptop, whitelist more programs for PDA just like phone

### PR DESCRIPTION
**Pull request by warface1234455**
# About PR
Be able to build pda and phone via autolathe
Give PDA more programs to access just like phone
*note: This is NTOS Tablet PDA not normal PDA

# Wiki Documentation
You can build PDA and Phone now

# Changelog

:cl:  
rscadd: Ability to build PDA and Phone
tweak: PDA can access to more programs like phone
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
you might want to hold off on this one, a bigger rework to this stuff is in the works

**Comment by warface1234455** [comment]
> you might want to hold off on this one, a bigger rework to this stuff is in the works

You mean converting the normal PDA into NTOS? I'm just making the **Tablet** PDA one and Phone buildable

**Comment by VaelophisNyx** [comment]
> You mean converting the normal PDA into NTOS? I'm just making the **Tablet** PDA one and Phone buildable

no no it's a lot broader sweeping than that, including this function iirc

**Comment by warface1234455** [comment]
yike ok

**Review by ToasterBiome — DISMISSED** [review]
change title at least to say you're whitelisting all these programs

also balance

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
