### PR TITLE
New supermatter delaminate + small code cleanup

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Adds a new blob delamination caused by having a >=50% miasma mole ratio in the SM.
# Wiki Documentation
SM can delaminate into a superpowered blob if there is a >=50% miasma mole ratio.
# Changelog
:cl:  
rscadd: Adds a new blob delamination caused by having a >=50% miasma mole ratio in the SM.
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
cool idea, cant wait to self antag with this

**Comment by Simplehorror** [comment]
> cool idea, cant wait to self antag with this

that is against the rules

**Comment by KillerOrcaCora** [comment]
Your Cocain was folded more times then a Japanese Katana because this is some next level shit right here

**Comment by CMOisLing** [comment]
Stealth Nerfing Fart SM smh

**Comment by ShoziOffical** [comment]
What's the point of this

**Comment by ReddicusDragon** [comment]
why

**Comment by ShoziOffical** [comment]
Also This is too easy for blob delam, literally just delam sm to 1% then quickly replace the gas with miasma

**Comment by Simplehorror** [comment]
> Also This is too easy for blob delam, literally just delam sm to 1% then quickly replace the gas with miasma

Also This is too easy for tesla delam, literally just delam sm to 1% then quickly replace the gas with CO2

**Comment by ShoziOffical** [comment]
> > Also This is too easy for blob delam, literally just delam sm to 1% then quickly replace the gas with miasma
> 
> Also This is too easy for tesla delam, literally just delam sm to 1% then quickly replace the gas with CO2

That doesn't work like that lmao

**Comment by ShoziOffical** [comment]
To achieve tesla you need to fill in co2 constantly and make sure energy cap above 5000

**Comment by ShoziOffical** [comment]
This is blob delam literally requires no effort and u got a fucking blob

**Comment by ShoziOffical** [comment]
Just 1 mole of miasma

**Comment by ShoziOffical** [comment]
Tesla is not as destructive as blob so this pr is hugbox for tator

**Comment by Simplehorror** [comment]
ok, congratulations to anyone who manages to play this timing minigame and also has hijack.

**Comment by ShoziOffical** [comment]
> ok, congratulations to anyone who manages to play this timing minigame and also has hijack.

Well if u going this path maybe at least make blob sm delam requires extra steps like antinob crystal. The item only available for hijack tot

**Comment by Simplehorror** [comment]
> > ok, congratulations to anyone who manages to play this timing minigame and also has hijack.
> 
> Well if u going this path maybe at least make blob sm delam requires extra steps like antinob crystal. The item only available for hijack tot

no that thing fucking sucks

**Comment by Simplehorror** [comment]
i'll remove the antinob shard actually since nobody fucking uses it and it is the worst item in the game

**Comment by ShoziOffical** [comment]
> no that thing fucking sucks

Figure it out to make blob delam harder then

**Comment by ShoziOffical** [comment]
> i'll remove the antinob shard actually since nobody fucking uses it and it is the worst item in the game

Some people still use it

**Comment by Simplehorror** [comment]
seriously who is going to pay 10 TC for something i can accomplish by shooting it with a 357 or removing a heat exchanger and it doesnt even do tesla or singulo so it fucking SUCKS for hijack

**Comment by Simplehorror** [comment]
> > i'll remove the antinob shard actually since nobody fucking uses it and it is the worst item in the game
> 
> Some people still does

never seen it once

**Comment by ShoziOffical** [comment]
Well, this is the use of it, blob delam :)

**Comment by ShoziOffical** [comment]
well either this or something else that makes it harder for blob delam

**Comment by Simplehorror** [comment]
#16420

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Make it harder

**Comment by Simplehorror** [comment]
5000 total moles needed now. idfk where you're gonna get that

**Comment by ShoziOffical** [comment]
> 5000 total moles needed now. idfk where you're gonna get that

Well edit ur pr then

**Comment by CMOisLing** [comment]
Does 2000 moles sounds fair, you also need to make sure you dont cleanse the miasma with heat

**Comment by kooarbiter** [comment]
SM blobs will probably stop shuttle from leaving like regular blob, making it kind of a foot shooter if you have hijack, but i digress

**Comment by ShoziOffical** [comment]
image

didntt work and has runtime, after few moments it became singulo, no blobby, there were 6000 moles of miasma in it

**Review by warface1234455 — CHANGES_REQUESTED** [review]
fix

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Good idea, but make it not shit and work

**Comment by Simplehorror** [comment]
wtf worked before i made the mole shit changes

**Comment by Simplehorror** [comment]
there's no way that runtime is related to anything i have to do

**Comment by ShoziOffical** [comment]
> wtf worked before i made the mole shit changes

wanna join my private server and test it out :)(, i literally checkout your whole pr and attemped it

**Comment by ShoziOffical** [comment]
> wtf worked before i made the mole shit changes

i think that, the moles is the problem because it passed the singulo requirement so it resulted in a singulo instead of blobby

**Comment by Simplehorror** [comment]
i forgot to return so it just eats the blob lol

**Comment by JamieD1** [comment]
Is it working now?

**Comment by JamieD1** [comment]
Check 2

**Comment by Simplehorror** [comment]
works

**Comment by Bibby0110** [comment]
> works

It doesn’t compile..

**Comment by Simplehorror** [comment]
fuck this not fixing that fucked up conflict

**Pull request closed without merging**
