### PR TITLE
makes space bats holdable

### PR DESCRIPTION
**Pull request by tattax**
# Document the changes in your pull request

ljrhaNPZMJ

:cl:  
rscadd: you can now hold space bats
bugfix: bats can now actually see in the dark  
spellcheck: uncapitalized simplemob names
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
precious bat child

**Comment by MusselMain** [comment]
This makes me wanna feed the bat a celery

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Why isnt the HoS's Spider holdable?

**Review by cuackles — APPROVED** [review]
sprites aproved by both me and orca

**Pull request merged**
