### PR TITLE
Revert "Revert "NASA Space suit flash protection removal""

### PR DESCRIPTION
**Pull request by ThatLing**
Reverts yogstation13/Yogstation#17967

I forgot only Jamie can revert things, I am now being striked

### CODE REVIEW

**Comment by JamieD1** [comment]
God sake

**Comment by Maia-J** [comment]
Close this before someone takes this seriously

**Comment by MegaEmpirical** [comment]
Fix plasmamen too!

**Comment by Snellie12** [comment]
I can't tell if y'all waited to get the Curators happy that a personal grudge PR got reverted to do this; or this is a genuine clown thing ...

But not cool, y'all.

**Comment by Bibby0110** [comment]
48 hour rule

**Comment by JamieD1** [comment]
> 48 hour rule

Yes but he shouldnt of merged the revert 4head

**Pull request closed without merging**
