### PR TITLE
Removes objective lock from Neural Overclocker implant and makes it cost 14TC

### PR DESCRIPTION
**Pull request by Moltijoe**
Wasn't as strong as expected
Gibs you if you get emped enough times with it active
Only time people were using it was in conjunction with the emp immunity implant
This makes it more accessible

:cl:  
tweak: Neural Overclocker implant can be purchased by anyone with an uplink now
tweak: Neural Overclocker implant now only costs 14TC
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
this thing sucks for 20tc

**Comment by Moltijoe** [comment]
> this thing sucks for 20tc

#16966

**Comment by Simplehorror** [comment]
still

**Comment by Moltijoe** [comment]
> still

this entire game is an endless work in progress, if it's not good enough, it can be changed

**Review by MajManatee — APPROVED** [review]
oh no moving faster
idk why it was restricted originally

**Comment by Moltijoe** [comment]
> oh no moving faster idk why it was restricted originally

it was restricted because i wanted it to be nukies only at first, but then thought it fit martyr traitor well thematically

**Comment by UltraBigRat** [comment]
Honestly could make it like 12 tc to be on par with holoparas, but yeah this might make it a little bit more used.

**Comment by Moltijoe** [comment]
> Honestly could make it like 12 tc to be on par with holoparas, but yeah this might make it a little bit more used.

if it was 12tc that would make frenzy holopara literally useless, this was intended to be an upgrade from specifically frenzy holopara if you're willing to invest a bit more

**Comment by UltraBigRat** [comment]
> > Honestly could make it like 12 tc to be on par with holoparas, but yeah this might make it a little bit more used.
> 
> if it was 12tc that would make frenzy holopara literally useless, this was intended to be an upgrade from specifically frenzy holopara if you're willing to invest a bit more

Would it? frenzy holopara is both superspeed for you, a stun immune super fast sentient fireaxe  that can break walls, and a no cooldown ranged mini stun, that when not in use can simply buckle to you   and keep passive up to 2x speed. At the cost of being unable to be revived, though maybe im wrong cause to be fair i only used this once as a nukie (it somehow got slowed down to a crawl by an ebola despite me stacking 4x speed with maxed frenzy and this combined) and an admin event.

**Comment by Moltijoe** [comment]
> Would it? frenzy holopara is both superspeed for you, a stun immune super fast sentient fireaxe that can break walls, and a no cooldown ranged mini stun, that when not in use can simply buckle to you and keep passive up to 2x speed. At the cost of being unable to be revived, though maybe im wrong cause to be fair i only used this once as a nukie (it somehow got slowed down to a crawl by an ebola despite me stacking 4x speed with maxed frenzy and this combined) and an admin event.

Holoparas are more of a liability, main reason most don't get given range and are forced to just be a back turret
Neural overclocker goes as fast as a maxed potential frenzy holopara with additional effects added
Neural overclocker is also a toggle, allowing for more fine control of when the speedboost is given
Holopara is the one in control of the frenzy ability, this requires collaboration that often just isn't there
Frenzy is also just a temporary buff with a cooldown, meaning it sometimes isn't up when it's needed

**Pull request merged**
