### PR TITLE
Resprites the experimental tools from caravan ambush

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Make the experimental tools from the caravan ambush look super generic/hueshifted

image

#### Changelog

:cl:  
tweak: Resprited Caravan tools
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
~~oops didnt realize the title was fucked~~

**Comment by Mesalikepie** [comment]
Love it

**Review by Partheo — CHANGES_REQUESTED** [review]
expscrewdriver in tools_righthand.dmi has an extra animation frame.

**Comment by ToGWtF** [comment]
I see Redmoogle is a DeWALT man

**Review by Partheo — APPROVED** [review]

**Review by alexkar598 — DISMISSED** [review]
Fix your line endings

**Comment by redmoogle** [comment]
> 
> 
> Fix your line endings

oh heres a fun fact: The line endings should be CRLF like all other dm files but this one has LF for some reason

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
