### PR TITLE
Makes the pathfinder kasa side sprite less lizardy

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
because lizards are stinky

before
image

after
side

:cl:  
tweak: Makes the pathfinder kasa side sprite less lizardy
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
ided

**Comment by Moltijoe** [comment]
> ided

yes, inside

**Comment by iamthesilly** [comment]
It's supposed to be that way so that it doesn't look weird on ashwalkers

**Comment by Marmio64** [comment]
I thought the point of pathfinder was to let miners get ashstorm immunity not for ashwalkers to wear

**Pull request closed without merging**
