### PR TITLE
If you know you know. (Ai Face)

### PR DESCRIPTION
**Pull request by Readystorm546**
Adds new AI face to the game. Code Name Plain

BjMwffxLDB

// FACE WAS UPDATED

:cl:  
rscadd: Added new Ai Face 
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
nice

**Comment by Hopekz** [comment]
I think it is a little weird that it moves side by side. 
Ruins the illusion of this being a "face" for an AI in my opinion.

**Comment by Readystorm546** [comment]
> I think it is a little weird that it moves side by side.
> Ruins the illusion of this being a "face" for an AI in my opinion.

Best i could come up with.. YOu have any other ideas?

**Comment by monster860** [comment]
You can do the tried and true method of having it occasionaly distort for a second, and maybe slap some scanline effects on it

**Comment by Hopekz** [comment]
I like this one better than the first one.

**Review by Hopekz — APPROVED** [review]
I like this one better than the first one.
Now, this just needs to go through our almighty creative lead.

**Comment by athena413** [comment]
cool

**Comment by Xoxeyos** [comment]
Looks good as it is.

**Comment by alexkar598** [comment]
I dunno how I feel about adding a direct reference to a player like that

**Comment by Readystorm546** [comment]
> I dunno how I feel about adding a direct reference to a player like that

Theres a few direct references to players. However i can rename it to something besides Adrian.

**Comment by boodaliboo** [comment]
we have plenty of direct refereces to player

**Comment by alexkar598** [comment]
Eh, fine.

**Comment by Marmio64** [comment]
> I dunno how I feel about adding a direct reference to a player like that

cough cough wizard academy wizard names cough cough

**Pull request merged**
