### PR TITLE
Regen Coma heals for more and triggers closer to death

### PR DESCRIPTION
**Pull request by Moltijoe**
image

regen coma is terrible currently, it's a negative more than a positive
let's make it a bit stronger

:cl:  
tweak: Regen Coma heals for more and triggers closer to death
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
i'd make it so you come out of sleeping earlier after healing out of crit or whatever

**Comment by CMOisLing** [comment]
Make it work with necrotic metabolism and I will kiss you on the lips in dorms

**Comment by Moltijoe** [comment]
> Make it work with necrotic metabolism and I will kiss you on the lips in dorms

ah, you plan to join orca i see

**Comment by CMOisLing** [comment]
> ah, you plan to join orca i see

If I said I was gonna do it IRL would that still be breaking the rules?

**Comment by Simplehorror** [comment]
actually a better idea would to make it so it activates when you die and revives you on occasion

**Comment by MajManatee** [comment]
Make it not activate so early. I hate falling sleep because i got a paper cut

**Comment by Moltijoe** [comment]
> Make it not activate so early. I hate falling sleep because i got a paper cut

i already made that change
i updated the changelog, but forgot to rename the PR

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
