### PR TITLE
New medkit + briefcase sprites

### PR DESCRIPTION
**Pull request by Necrosium**
# Document the changes in your pull request
Resprites medkits and briefcases to have a more frontal vision. 

I will be making some changes on color/lighting/whatever cuackles and biome force me to change from time to time. I kinda made 'em in a rush as well

Heavily inspired by Bee's boxkits! (except the suitcases, those are yogriginal™)

# Why is this good for the game?
45 degree sprites are ancient, those sprites are smoother and look like futuristic medkits I believe. And why not!

# Spriting
image

The ones marked aren't in-game AFAIK

# Changelog

:cl: Time_URSS
imageadd: New medkit + briefcase sprites
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
weird question marks? if they aren't in game then why were they sprited?

**Comment by Necrosium** [comment]
Those will be added in the future, they dont spawn in game + if they are already in the dmi file, less trouble

**Comment by RG4ORDR** [comment]
Over-designed does not mean better.
The current medkit sprites are sufficient enough

**Comment by Necrosium** [comment]
> Over-designed does not mean better. The current medkit sprites are sufficient enough

I'd not say they are 'overdesigned', it's just a medkit that looks forward and not to the horizon. 

I do need to change the colouring though which I'm on it

**Comment by Moltijoe** [comment]
My issue is more so colour, why is brute sorta pinkish and burn yellow?

**Comment by ToasterBiome** [comment]
> My issue is more so colour, why is brute sorta pinkish and burn yellow?

brute kits are pink and burn kits are yellow in game currently.

**Comment by neeshacark** [comment]
not a big fan of the color or the shape to be honest

briefcase sprites are good though

**Comment by Moltijoe** [comment]
> brute kits are pink and burn kits are yellow in game currently.

But they arent that shade of pink or yellow

**Comment by Necrosium** [comment]
>  
> > brute kits are pink and burn kits are yellow in game currently.
> 
> But they arent that shade of pink or yellow

> I will be making some changes on color/lighting/whatever cuackles and biome force me to change from time to time. I kinda made 'em in a rush as well

**Comment by Necrosium** [comment]
> not a big fan of the color or the shape to be honest
> 
> briefcase sprites are good though

Colors will be changed, the shape though is that of a medkit, not sure whats the issue with it

**Review by cuackles — CHANGES_REQUESTED** [review]
image
could you clean up the black line on the bottom so it doesnt look out of place

**Comment by Necrosium** [comment]
Updated image: 
image

**Comment by Moltijoe** [comment]
> Updated image: image

i definitely prefer the colours they sorta pop more, similar to how they used to be

**Comment by AMyriad** [comment]
Not sure how much say I have here, but these sprites feel very out of place compared to the rest of the yogs artstyle. They aren't bad, but I very much prefer the ones we have right now over these ones. If you want to replace the medkits cause they're old, a more fitting design would be better.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
- I like the direction of the burn color, but I think it needs to be more gold, similar to how the originals looked.
- I like the updated oxygen colors, but again I think they need to be closer to the original color (as in the shitty sprites). I think you can make a nicer palette while starting with those two base colors.

**Review by cuackles — APPROVED** [review]
changes :)

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
the medbriefcase and normal briefcase look not very good, for at least the normal briefcase can you make it look more like the original one in design?

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
