### PR TITLE
reenables traitorvamp

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
i dont think it's too controversial to say that bloodsucker is fucking awful, it's even more of a snoozefest than vampires because they all get caught in the first 10 minutes or so by the funny maint dweller security officers and then round removed, whereas the vampires at least have a little mobility to escape, and i personally have seen the game just fucking end a good number of times because all the bloodsuckers died (hint: not supposed to happen) and traitorvamps are good variety to break up traitorling and traitorbb, and with bibby removing malf we're ending up with even less gamemodes which means even less variety

note: does not reenable just vampires because that gamemode is actually boring

# Changelog

:cl:  
tweak: traitorvamps has been re-enabled
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Just take them both out, they’re both dogshit

**Comment by Simplehorror** [comment]
"remove traitors" - N3D6

**Comment by N3D6** [comment]
> "remove traitors" - N3D6

You wanna remove just about everything else so we should just do this while we’re at it
And no, cunt, I didn’t say remove traitors, I meant remove vamps and bloodsuckers because both of those are terrible

**Comment by bruhlookatthisdood** [comment]
> > "remove traitors" - N3D6
> 
> You wanna remove just about everything else so we should just do this while we’re at it And no, cunt, I didn’t say remove traitors, I meant remove vamps and bloodsuckers because both of those are terrible

"improv don remov" - mr clean

**Comment by Simplehorror** [comment]
> > "remove traitors" - N3D6
> 
> You wanna remove just about everything else so we should just do this while we’re at it And no, cunt, I didn’t say remove traitors, I meant remove vamps and bloodsuckers because both of those are terrible

yeah they suck agreed

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
