### PR TITLE
Revert "Reduces Cargo Technician max job slots from 3 to 2 and roundstart from 2 to 1"

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
bad change

# Changelog
:cl:  
tweak: cargo tech gets 3 jobs again
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
There has been no recent development in cargo to justify another slot being open. Closing in 24h

**Comment by Moltijoe** [comment]
head dev has dictated it be closed after 24h

**Comment by azzzertyy** [comment]
more likes than dislikes open again :)

**Comment by Bibby0110** [comment]
Due to the conflict of interest Jamie will be deciding on this PR

**Comment by JamieD1** [comment]
State why the extra slot will be beneficial for the game @azzzertyy

**Comment by azzzertyy** [comment]
> State why the extra slot will be beneficial for the game @azzzertyy

i just don't think it should've been removed in the first place, its a newbie role for newbs and having a slot reduction in it doesnt make much sense, plus it means that roundstart its super easy for 50% of the cargo bay to be traitors and this just is Bad News alongside the syndicate bounty pr and the fact cargo can buy weapons, having 50% of the cargo bay being traitors just makes it instantly overtaken.

**Comment by ToasterBiome** [comment]
image

**Pull request closed without merging**
