### PR TITLE
fixes swarmers spacing areas

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

checks every adjacent turf to see if its spaced and refuses if so

# Changelog

:cl:  
bugfix: fixed swarmers spacing areas
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
Swarmers Moment

**Comment by TheRyeGuyWhoWillNowDie** [comment]
ided

**Comment by warface1234455** [comment]
Would this fix swarmers breaching burn room or fusion chamber

**Comment by ynot01** [comment]
> Would this fix swarmers breaching burn room or fusion chamber

not unless its spaced

**Comment by VaelophisNyx** [comment]
could add a check for if pressure is above livable limits

**Comment by warface1234455** [comment]
> could add a check for if pressure is above livable limits

yeah thats a good idea

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
