### PR TITLE
Port lavaland elites from TG

### PR DESCRIPTION
**Pull request by SomeguyManperson**
original PR: tgstation/tgstation#46566
A secondary type of tendril that spawns a miniboss on being interacted with, which can be made sentient by adding a stable legion core beforehand for special loot on winning. Loot is either an item specific to the miniboss or a special item that can be used to revive it to assist the activator.

🆑 Indie-ana Jones & Meyhazah
add: New lavaland ruin: Pulsating Tumor
add: New lavaland enemies: Lavaland Elites
add: New Lavaland Elite: Goliath Broodmother
add: New Lavaland Elite: Pandora
add: New Lavaland Elite: Legionnaire
add: New Lavaland Elite: Herald
imageadd: Added lavaland elite sprites and pulsating tumor sprites
imageadd: New lavaland loot sprites
imageadd: Elite ability sprites
/🆑

### CODE REVIEW

**Comment by Hopekz** [comment]
I followed this PR while it was being made in TG.
Good PR port +1

**Comment by SomeguyManperson** [comment]
stupid herald cloak doesn't work yet

**Comment by Laus4Deus** [comment]
Sounds amazing!
But what will you do abote hope medal?

**Comment by SomeguyManperson** [comment]
Probably going to be able to store 1 or 2 small/normal items

**Comment by HomocidlePancakes** [comment]
>Probably going to be able to store 1 or 2 small/normal items

Pen holder proved that it’s bad, unless you can make it work w/o detaching it from the suit

**Comment by SomeguyManperson** [comment]
I think the pocket protector is supposed to act like that but doesnt because its broke to the point of nonfunctionality

**Comment by HomocidlePancakes** [comment]
Port one-handing the crusher when?

**Pull request merged**
