### PR TITLE
Ports new decal painter uis from tg

### PR DESCRIPTION
**Pull request by warface1234455**
- ports decal painter uis from https://github.com/tgstation/tgstation/pull/66248 and some codes from https://github.com/BeeStation/BeeStation-Hornet/pull/7319

# Document the changes in your pull request

new ui for decal painter

Images: image

# Changelog

:cl:  Tastyfish, itsmeow ported by warface1234455
rscadd: new uis for decal painter

/:cl:

### CODE REVIEW

**Comment by warface1234455** [comment]
why runtime why

**Comment by ShoziOffical** [comment]
~~still dont know why the tgui keeps causing framedrops~~ seems like its a tgui moment, gotta wait untill tgui components are updated

**Comment by MajManatee** [comment]
@warface1234455 mighta made some merge conflicts, not an emergency though.

**Comment by ShoziOffical** [comment]
> @warface1234455 mighta made some merge conflicts, not an emergency though.

Yeah i knew this would happen

**Comment by ShoziOffical** [comment]
also i think i should close this until someone update the tgui components that when i can reopen this

**Pull request closed without merging**
