### PR TITLE
adds pocket cat costume to autodrobe

### PR DESCRIPTION
**Pull request by thegoldencat413**
# Document the changes in your pull request

adds costume of pocket cat from fear and hunger

# Why is this good for the game?
more costumes are cool, also we dont have any fear and hunger references, also its spooky month
# Testing
everything looks right I think

# Spriting
image
image
image
image

# Wiki Documentation
uhh i dont actually know what to put here exactly, but if this section means what I think it does I will add the clothes and their icons to the vending machines page under the autodrobe table

# Changelog

:cl:  
rscadd: Added pocket cat mask and suit

imageadd:  sprites for pocket cat mask and suit

/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
good

**Comment by Yarinoi** [comment]
90% of heads pickers quit right before they win big

**Comment by thegoldencat413** [comment]
tails never fails

**Comment by Yarinoi** [comment]
can we also add rusty nails to maintenance that you can step on if you're barefoot

**Comment by MajManatee** [comment]
im traumatized

**Review by cuackles — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
