### PR TITLE
[MDB IGNORE] NAUTILUS Station 13

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request

Introducing Nautilus Station 13
image
brought to you by Shambler's Juice

image

The only station with a space elevator, and half of the station is off the station!
This is currently an early version of the station, the plan is as follows:

Stationside: Atmospherics, Service, Command, Security, Medbay
Planetside: Supply, Engineering, Science, Smaller Medbay

The space elevator is currently done, it just needs a sprite of a planet approaching.

Its intended to be for Jungleland, when it releases that is.

# Changelog
:cl:  
mapping: Nautilus Station
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
0/10 doesnt have yogs in the name

**Comment by Hislyna** [comment]
Looks really cool, looking forward to how it comes along

**Comment by iloveloopers** [comment]
will we be able to crush people under the elevator?

**Comment by azzzertyy** [comment]
> will we be able to crush people under the elevator?

probably

**Comment by ShoziOffical** [comment]
Gotta love the 3x3 long hallway

**Comment by GDRdev** [comment]
where the fuck is everything

**Comment by ShoziOffical** [comment]
> where the fuck is everything

Wip

**Comment by neeshacark** [comment]
needs more trams

**Comment by ToasterBiome** [comment]
these trims r nasty

**Comment by patpol4** [comment]
cute trims

**Comment by Addust** [comment]
there should be an indestructible turf to represent the cable thingy of the space elevator

**Comment by azzzertyy** [comment]
> there should be an indestructible turf to represent the cable thingy of the space elevator

actually already done, its not in the image because i was testing but its just an indestructable plastitanium wall

**Comment by ToasterBiome** [comment]
reopen when worked on

**Pull request closed without merging**
