### PR TITLE
Nanotrasen Inspector booth

### PR DESCRIPTION
**Pull request by Kaithyl**
https://user-images.githubusercontent.com/90080475/233808252-74f48795-5c4b-4026-82ae-9ebdf28c8cfb.mp4

*Special thanks to Lucas Pope for creating Papers, Please and for the audio*

Tested in singleplayer but not completely in multiplayer.
There are also several unused assets but I needed to take a break from this project for my own sanity.

# Spriting
window
button_prototype
desk_bg
desk_bottom
desk_bottom_sepia
desk_top
desk_top_sepia
idcard
idcard_gold
idcard_silver
paper
speaker
stamp_approve
stamp_cap
stamp_ce
stamp_clown
stamp_cmo
stamp_deny
stamp_hop
stamp_hos
stamp_law
stamp_qm
stamp_rd
stamp_unknown
tray_cover
tray_end
tray_segment
inspector_booth
booth_maint
booth_off

*All designs were pre-approved by the lore director*

# Wiki Documentation

This should be added to the list of machines here: https://wiki.yogstation.net/wiki/Machines
The player can insert paperwork into the booth from any direction but the UI and maintenance hatch can only be accessed from the back of the machine. (Or if you're standing on the same tile somehow)
Part upgrades: 
stamp tray capacity is determined by 2 + micro manipulator tier (3 when first constructed)
booth item capacity is determined by 3 + 2 * matter bin tier (5 when first constructed)

# Changelog

:cl:  
rscadd: Added Inspector Booth machine
tweak: Added Inspector Booth to list of circuit boards and corresponding research (Basic Research Technology)
soundadd: Added several sfx for UI interaction (sound\machines\inspector_booth)
imageadd: Added several UI icons and sprites (icons\UI_Icons\tgui\inspector_booth and icons\obj\machines\inspector_booth.dmi)
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
absolutly love it but are we in the legal clear to use those sprites ?

**Comment by Kaithyl** [comment]
> absolutly love it but are we in the legal clear to use those sprites ?

Well I hand-drew all of the sprites so I guess I give myself permission to use them.

**Comment by ToasterBiome** [comment]
is the audio yours?

**Comment by cuackles** [comment]
> > absolutly love it but are we in the legal clear to use those sprites ?
> 
> Well I hand-drew all of the sprites so I guess I give myself permission to use them.

oh i tougth it was taken from the game, bet then i dont think it should be an issue

**Comment by Kaithyl** [comment]
> is the audio yours?

Audio was credited to Lucas Pope in both the PR and in attributions.txt

**Comment by ReddicusDragon** [comment]
This is already amazing, but if you REALLY want to go all out you should add paperwork printing abilities to the booth directly

**Review by ReddicusDragon — APPROVED** [review]

**Comment by wonderinghost** [comment]
_Drops a pizza in the slot_

**Comment by wonderinghost** [comment]
Now is it only papers or can you insert fairly small items in there. Like a live hand grenade

**Comment by wonderinghost** [comment]
Now I wonder if you can pair it for packaging

**Review by cuackles — APPROVED** [review]

**Comment by MajManatee** [comment]
Id like to see somthing like this replace the HOP office thing.

**Comment by Kaithyl** [comment]
Merge conflict was fixed. It was due to the fact that new techs were added to the tech web since this PR was first made.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
