### PR TITLE
Ghosts can now teleport to ruins of any kind

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Changes one variable that hopefully lets ghosts teleport to ruins, as I believe there is no reason for ghosts to NOT be able to teleport to ruins. Of course, this will require that ruin areas are named _clearly._

This PR also renames the ruin areas in Onehalf to avoid confusion.

if there are any unexpected consequences _**please scream at me over discord**_

# Changelog

:cl:   
tweak: ghosts can now teleport to ruin areas!
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Cool concept, only issue I can see is that similar to lava land, where a certain someone (curator) dies "accidentally" really early on and uses that time to ghost around and look for all the loot, but C'est la ve.

**Comment by Addust** [comment]
that's an admin issue and Not My Problem

**Comment by JohnFulpWillard** [comment]
This will fill up the list of station areas (the actual important places) with a massive list of every ruin currently in-game.
Why should ghosts care about these locations and why is it good for the game that this is accessible here?

**Comment by Addust** [comment]
i'd have given them the Jump to Ruin verb but i can't be bothered

/tg/station hasn't got ruin areas set to hidden and i don't see any negative consequences, so long as ruin areas are properly named

if you name your ruin's bridge area 'Bridge' then that is when a problem arises

**Comment by JohnFulpWillard** [comment]
> if you name your ruin's bridge area 'Bridge' then that is when a problem arises

You should add a unit test that prevents 2 areas from having the same name then, to pre-emptively prevent this from becoming a problem.

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
