### PR TITLE
ports shank from hippiestation with some modifications (working edition)

### PR DESCRIPTION
**Pull request by boodaliboo**
Intent of your Pull Request
this allows you to make a shank (originally created by steamp0rt)  a glass shard and a torn cloth in the crafting menu 
original pr:https://github.com/HippieStation/HippieStation/pull/3475
Changelog
🆑
rscadd: Adds a shank as a new craftable item
/🆑

### CODE REVIEW

**Comment by Quartich** [comment]
Metal rod? Why not just make a spear at this point? Maybe make it just use a metal sheet

**Comment by MegaEmpirical** [comment]
I was just thinking about looking into this, I thought we had this pre-rebase.

**Comment by HomocidlePancakes** [comment]
The sprite clearly has a piece of cloth as a makeshift handle and no sign of wires. Shard + cloth/damp rag?

**Comment by boodaliboo** [comment]
Yeah I can change the recipe I just didn’t want to port duct tape aswell and thrown mess with loot piles actually better yet torn cloth

**Comment by alexkar598** [comment]
Yet another stupid greytider buff

**Comment by boodaliboo** [comment]
This is more meant  as  a prisoner buff for permabrigged people once I change the recipe

**Comment by alexkar598** [comment]
The last thing prisonniers need is a buff

**Pull request closed without merging**
