### PR TITLE
doomsday device now resets timer if a core is destroyed

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

so you can't stack 10 cores and be invincible for 5 minutes
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: doomsday device now resets timer if a core is destroyed
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
> ided

check facebook dms

**Comment by Simplehorror** [comment]
simon please

**Comment by ReddicusDragon** [comment]
can't say I ever had my comment deleted by "yogstation13"

**Comment by bruhlookatthisdood** [comment]
lets see an ai 2 core get one core destroyed at 5 seconds

**Comment by neeshacark** [comment]
new meta: make an ai core and destroy it to stop the doomsday

**Comment by Bibby0110** [comment]
only works if the core the AI is in is destroyed

**Comment by Simplehorror** [comment]
yea, that the point

**Comment by Bibby0110** [comment]
> yea, that the point

kinda seems useless then

**Comment by Bibby0110** [comment]
dont believe this is necessary. Up the core count modifier if you feel it is too short

**Comment by BobTheButton** [comment]
I dont think it should just fully reset the timer, just readd like 3 minutes instead

**Pull request closed without merging**
