### PR TITLE
Remove the king of mining cheesing, vortex talisman

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Way too easy to kill EVERY megafauna with this trophy, it isn't even a challenge
# Spriting

# Wiki Documentation

NO MORE VORTEX TALISMAN
# Changelog

:cl:  
rscdel: Remove the king of mining cheesing, vortex talisman
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
There was literally another pr that replaces it with a homing projectile, why not just port that

**Comment by Simplehorror** [comment]
> There was literally another pr that replaces it with a homing projectile, why not just port that

nobody's going to use it if even if i replace it anyways

**Comment by Simplehorror** [comment]
all downvoters are miner mains who used this to cheese bubblegum and colossus and start validhunting

**Comment by MajManatee** [comment]
improve dont remove :)

**Comment by Simplehorror** [comment]
> improve dont remove :)

i'll remove your testicles

**Comment by Mantlecrawler** [comment]
Add some other trophy in its place, then. This really doesnt allow you to cheese megafauna asides from collosus

**Comment by Simplehorror** [comment]
> Add some other trophy in its place, then. This really doesnt allow you to cheese megafauna asides from collosus

it literally simplifies every megafauna to a point where i could teach a chimp to do it

**Comment by Mantlecrawler** [comment]
Alright i want a video of you clearing every megafauna easily with the tailsman

**Comment by LazennG** [comment]
> all downvoters are miner mains who used this to cheese bubblegum and colossus and start validhunting

-one of the people downvoting is someone you've explicitly said doesn't play mining when they disagree with your prs
-vortex talisman to cheese bubblegum
lol

**Comment by Simplehorror** [comment]
> > all downvoters are miner mains who used this to cheese bubblegum and colossus and start validhunting
> 
> -one of the people downvoting is someone you've explicitly said doesn't play mining when they disagree with your prs -vortex talisman to cheese bubblegum lol

yah

**Comment by Simplehorror** [comment]
i'm having too much fun abusing this

**Pull request closed without merging**
