### PR TITLE
Adds Personnel HUD Type, gives HoP and Cap a pair of sunglasses with it

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

Adds the Personnel HUD type, which just shows job ID icons. It already exists in datums as DATA_HUD_SECURITY_BASIC and the "basic" HUD sec gets is DATA_HUD_SECURITY_ADVANCED, who knew?

So this adds that and gives a pair of flash-proof sunglasses with the HUD on it to HoP and Captain.

HoP and Cap are stealing the CMO's shades, and CMO is getting a new, lighter version (I tried to make them kinda teal like their cloak, but it just did not work).

image

image

image

image

# Changelog

:cl:  
rscadd: Adds new Personnel HUD type
rscadd: Gives a pair of new personnel HUD sunglasses to the HoP and Cap worn at round start.
imageadd: Lightens up the CMO shades to make them a more lighter/brighter blue.
imageadd: Renames current CMO shades for personnel.
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
now this is epic.

**Comment by Moltijoe** [comment]
they should probably get their own sprite so they aren't confused for regular sunglasses

**Comment by Aquizit** [comment]
converting to draft for sprite work that won't be done tonight

**Comment by MajManatee** [comment]
recolour lenses to be uh... brown maybe?

**Comment by Aquizit** [comment]
A lot of colors would look weird with both of their uniforms being solid blue with some gold trim on the cap.

Working with cuackles on it but it just won't be done tonight

**Comment by milk-is-cool** [comment]
They should look like aviators, feels like it would fit.

**Review by cuackles — APPROVED** [review]
the edits are good, maybe a diferent glassess desing would make more sense but even that can be changed later if nesesary

**Review by MajManatee — APPROVED** [review]
finally

**Pull request merged**
