### PR TITLE
[AI] Upgrade Expansion | Now featuring induction!

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request
Main PR: https://github.com/yogstation13/Yogstation/pull/12815

Implements the first research "chain", induction, it allows you to charge APCs and borgs remotely. They're pricey upgrades and only have 1 charge. You recharge them by spending CPU 
Adds a new upgrade that allows the AI to tag 1 person (by shift-clicking them) and they will then be notified next time they're in view again

Backend:
Introduces passive upgrades and upgrades that unlock active abilities.

TODO:
- [x] Projects can unlock abilities
- [x] Projects can be "dummy" projects that only unlock other programs
- [x] Passive upgrades
- [x] Abilities can be recharged by spending CPU power
- [x] Add the actual induction abilities

# Changelog

:cl:  
rscadd: AI Projects have the ability to give active abilities
rscadd: New project allows AI to charge a borg remotely
rscadd: New project allows AI to keep APC operational even without power for a short duration
rscadd: New project that notifies the AI when a tagged individual re-enters camera view.
rscadd: Adds AI abilities that can be recharged by using CPU power
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Very cool kanye

**Comment by Sniblet** [comment]
Tried charging a borg on Lavaland, having researched APC then cyborg induction, returned _You can only charge APCs!_
Round 38907, a little while before shuttle arrival
Tried it on a borg on station, same error
Tried it on an APC, no problem

**Comment by Bibby0110** [comment]
> 

Bug that got fixed, but testmerge wasn't updated. Should be solved now

**Comment by adamsong** [comment]
Merge conflict

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Art review not required as its sprite already in game.

**Pull request merged**
