### PR TITLE
[BOX] Fixes railings in bar

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

fixes some railings in bar

# Changelog

:cl:  cark
mapping: fixes some railings in bar
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
not sure how this is a fix? it looks worse and makes less sense, you put the railings on this position if this is the position that is raised, but it is not, the other side is raised.

**Comment by Aquizit** [comment]
You know what the entire problem with this shit is?

image

These border tiles. Change them to the wood type and look how much better this will be.

image

I mucked up replacing the shadows but y'all know what I mean here.

image

And here's the thicker version of the trim to decide which looks best but seriously: make it wood

**Review by Aquizit — CHANGES_REQUESTED** [review]
I forgot I can actually just say do it and not just suggest it. :)

**Comment by azzzertyy** [comment]
> You know what the entire problem with this shit is?
> 
> image
> 
> These border tiles. Change them to the wood type and look how much better this will be.
> 
> image
> 
> I mucked up replacing the shadows but y'all know what I mean here.
> 
> image
> 
> And here's the thicker version of the trim to decide which looks best but seriously: make it wood

gross ew less constrast looks way worse, also, its not a "border" its to signify the depth, look at chapel2, it does the same thing.

**Comment by Aquizit** [comment]
It might actually be because I think the shadow decal is UNDERNEATH the gray trim in the first image. Which is making it basically not fucking exist.

**Comment by azzzertyy** [comment]
> It might actually be because I think the shadow decal is UNDERNEATH the gray trim in the first image. Which is making it basically not fucking exist.

its like that on chapel2 as well, its to add the shadow onto the floor and not the trim.

**Comment by neeshacark** [comment]
> not sure how this is a fix? it looks worse and makes less sense, you put the railings on this position if this is the position that is raised, but it is not, the other side is raised.

because the way they are people render over them, they are facing the wrong way.

**Comment by Aquizit** [comment]
> > It might actually be because I think the shadow decal is UNDERNEATH the gray trim in the first image. Which is making it basically not fucking exist.
> 
> its like that on chapel2 as well, its to add the shadow onto the floor and not the trim.

Ok, but on chapel2 it's going from tile-type trim to tile flooring. So it's less jarring. Plus the color is also less jarring. I'm understanding what it's supposed to look like: the wall there because it's lifted up.

The issue is we don't do that kind of perspective ANYWHERE ELSE -- like prime example is I think we're one of the few codebases left that do wall tiles that don't present a sort of visual verticality to them, like trying to portray a side of the wall so it makes more sense to see machinery on it. So doing that for raised areas just throws that off to my eye.

**Review by Aquizit — APPROVED** [review]

**Pull request merged**
