### PR TITLE
Adds Plushie accent

### PR DESCRIPTION
**Pull request by Hopekz**
Adds a new "Plushie" accent.

Basically inspired on how I'd imagine a plushie or a toy teddy bear would sound like if they were to talk for whatever reason.

#### Changelog

:cl:  Hopek
rscadd: Plushie accent has been added
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
@JamieD1 , @Ktlwjec , @Idinuum , @alexkar598 ;
So what do you guys not like about this?

The name? 
Some translations?
The idea behind it?
Are you just protesting accents in general?

What can I do to this PR to make you happy?

**Comment by swissloaf** [comment]
uwu i speak like a plushie i am very quirky

**Comment by alexkar598** [comment]
what swiss said

**Comment by Hopekz** [comment]
> uwu i speak like a plushie i am very quirky

That's literally just a name I came up with but alright thanks for your input.

**Comment by JamieD1** [comment]
> > uwu i speak like a plushie i am very quirky
> 
> That's literally just a name I came up with but alright thanks for your input.

I stated my reasoning in public, I dont like encouraging players to be degenerates with accents.

Pretty sure this is why we removed uwu

**Comment by SomeguyManperson** [comment]
rebranded uwu accent

**Comment by Colburn3000** [comment]
uwu me using a code endowsed woophowe to bweak da net speak wule

**Comment by Hopekz** [comment]
> uwu me using a code endowsed woophowe to bweak da net speak wule

The literal ironic example you provided isn't even netspeak.

**Comment by Colburn3000** [comment]
If anyone was using “teh” or “ur” regularly IC they would be bwoinked for netspeak. Not to mention the reasons others have stated.

**Comment by Hopekz** [comment]
> If anyone was using “teh” or “ur” regularly IC they would be bwoinked for netspeak. Not to mention the reasons others have stated.

Thank you.
You are the first person to actually give me real feedback of removing those translations from the accent besides just being on the bandwagon.

I'll remove those translations when I re-open this PR (since it will remove about 80% of the translations and be very different)

**Comment by Hopekz** [comment]
Closing this PR per the only real feedback I have received from Colburn.
Need to remove those translations before re-making this PR.

Not sure why Colburn was the only individual to leave useful feedback vs all our HC's and maintainers who tried to leave feedback but shitposted instead.

**Pull request closed without merging**
