### PR TITLE
Map Cleanup

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Clean maps up

### Why is this good for the game?

Cleans up default variables. _Shouldn't_ break anything.
Makes the codebase slightly smaller

### CODE REVIEW

**Review by patpol4 — APPROVED** [review]
Very nice, on hold for now due to https://github.com/yogstation13/Yogstation/pull/10447

**Comment by patpol4** [comment]
How did you do this anyway, just recheck everything with strongdmm?

**Comment by redmoogle** [comment]
> 
> 
> How did you do this anyway, just recheck everything with strongdmm?

Yeah, it has an option to remove default vars

**Comment by patpol4** [comment]
Might just want to remake this after the conflicts pass at this point

**Comment by redmoogle** [comment]
Will pr this slightly later when map changes go away

**Pull request closed without merging**
