### PR TITLE
updates Ptech vending machine to new pdas

### PR DESCRIPTION
**Pull request by Moltijoe**
wouldn't you know it, old pdas were removed a while ago

:cl:  
tweak: updates Ptech vending machine to new pdas
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
There's already the modular computer vendor to dispense the new PDA, a vendor with only one item also feel a little useless. If we can't find anything to put in it maybe it should just be removed.

**Comment by Moltijoe** [comment]
> There's already the modular computer vendor to dispense the new PDA, a vendor with only one item also feel a little useless. If we can't find anything to put in it maybe it should just be removed.

Its for the HoP to give out new pdas to those that lost them

**Comment by 00ze-cyclone** [comment]
In that case maybe a box of PDAs in their locker would be better

**Comment by MajManatee** [comment]
the old PDAs have the bluespace paper printer
no other PDA's have a printer installed by default, making it really annoying to dispense paperwork.

**Comment by ReddicusDragon** [comment]
> the old PDAs have the bluespace paper printer
> 
> no other PDA's have a printer installed by default, making it really annoying to dispense paperwork.
> 
> 

Actually, there's a paperwork program for new pdas and head PDAs come with a printer installed. I made this PR a bit ago, I think you just need to add paper.

**Review by ToasterBiome — APPROVED** [review]
goodbye, might be useful for more stuff to be added to this but, such is life

**Pull request merged**
