### PR TITLE
Syndicate Balloon Sprite Update!

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
This PR will change the old syndicate balloon to better fit the new Nukie hud Icon. Has been tested.

Wiki might have to change a PNG.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

/:cl:  
imageadd: [Resprite syndicate balloon]

/:cl:
https://streamable.com/2yqnwe

https://streamable.com/x1ftm1

### CODE REVIEW

**Comment by JamieD1** [comment]
Changelog is wrong

**Review by nesisknesis — COMMENTED** [review]
I'll take this opportunity to also review the other PR since I didn't get to. 

The new HUD looks like a floating head, which as a HUD I don't think looks great. My thinking is that there should be a distinct separation. 
I made some drafts on what my take would be
image
Basically a more detailed S with details to make it look like a snake.

However, since itd be awkward to backtrack on a merged PR, you don't have to change it if you don't want to.

As for this PR, there's a random DMI called "Onehandballoon" thats been added and it only contains the old balloon.

You also need to put imageadd: [changes here] in your changelog so that it works.

**Comment by KillerOrcaCora** [comment]
Oops ok it should be fixed now.

**Review by nesisknesis — APPROVED** [review]

**Comment by nesisknesis** [comment]
may get conflicts from #11946

**Comment by nesisknesis** [comment]
dwagadsb

**Review by nesisknesis — CHANGES_REQUESTED** [review]
Okay now that mantis blades are merged, this can also be merged. However, it also created a merge conflict so gods bless your soul and good luck. You'll most likely need to update the items_and_weapons DMI file and reapply your changes, though if that doesn't work tell me.

**Comment by JamieD1** [comment]
Hurry up @KillerOrcaCora

**Comment by JamieD1** [comment]
Reopen when you want to proceed

**Pull request closed without merging**
