### PR TITLE
Revert "makes valentines 2 days longer as a joke"

### PR DESCRIPTION
**Pull request by JamieD1**
Reverts yogstation13/Yogstation#7830

### CODE REVIEW

**Comment by Hopekz** [comment]
RP events are good

**Comment by LazennG** [comment]
the headcoder who stole valentines

**Comment by JamieD1** [comment]
Literally.. "As a joke"

**Comment by Hopekz** [comment]
> Literally.. "As a joke"

That's just meme words that he put on the PR.
The actual reasoning provided when people asked him about it was sound. 
He enjoyed the RP event a lot so he wanted to extend it and people at the time agreed.


If you care so much about PR wording why did you just merge a PR that had the reasoning of:
"atheists after saying "lol god isn't real" when someone say wizard is on station" in #13264

**Comment by JamieD1** [comment]
Either opt out and 5 days or this. Your choice.

**Pull request merged**
