### PR TITLE
Supermatter shard engine is now buildable + new cargo bounty

### PR DESCRIPTION
**Pull request by warface1234455**
more stuffs to do other than grabbing an axe and break sec locker, be less rely on cargo, 

# Document the changes in your pull request
New crystallizer recipe for supermatter silvers: 100 bz, 125 hypernob, 250 tritium, 750 plasma (Temp range: 100000K - 200000K)
New crystallizer recipe for supermatter hemostat: 5 bz, 100 hydrogen, 5 hypernob (Temp range: 50000K - 150000K)
New crystallizer recipe for supermatter base structure: 100 bz, 1000 hydrogen, 10 hypernob (Temp range: 50000K - 150000K)
New bounty for cargo: 20000 credits reward for 2 supermatter silvers

Also fix admin and log not reporting properly

Supermatter shard engine assembly steps:

1. Make supermatter hemostat, supermatter base structure, and 2 supermatter silvers
2. Use hemostat to carry supermatter silvers(Be fucking careful here not to mess up or you will dust yourself with it)
3. Use the sm hemostat on the sm base (The SM base requires 2 supermatter silvers to charge up and become an actual engine) also be careful, when it is finished charging up it will emit a bolt, remember to wear insul!
4. If you do everything correctly you will get a working supermatter shard engine

# Spriting

Left side is first stage, right one is second stage, third stage is just normal sm shard
image

# Wiki Documentation
Everything in document of changes

# Changelog

:cl:  
rscadd: New crystallizer recipe for supermatter silver: 100 bz, 125 hypernob, 250 tritium, 750 plasma (Temp range: 100000K - 200000K)
rscadd: New crystallizer recipe for supermatter hemostat: 5 bz, 100 hydrogen, 5 hypernob (Temp range: 50000K - 150000K)
rscadd: New crystallizer recipe for supermatter base structure: 100 bz, 1000 hydrogen, 10 hypernob (Temp range: 50000K - 150000K)
rscadd: New bounty for cargo: 20000 credits reward for 2 supermatter silvers
tweak: Supermatter shard engine is now buidable
bugfix: fix admin and log not reporting properly
/:cl:

### CODE REVIEW

**Comment by Rdrazga** [comment]
Im sorry but wut?

**Comment by Simplehorror** [comment]
i could get these requirements in my sleep

**Comment by Rdrazga** [comment]
You know the tesla generator being in there is memes, but I don't think we should be putting SM shards (which are still orderable from cargo) as a recipe personally

**Comment by ShoziOffical** [comment]
> You know the tesla generator being in there is memes, but I don't think we should be putting SM shards (which are still orderable from cargo) as a recipe personally

it takes time to make, but yeah you can order one from cargo which will be way more if you are lazy to make one by yourself

**Comment by ShoziOffical** [comment]
> i could get these requirements in my sleep

yeah right

**Comment by Simplehorror** [comment]
> > i could get these requirements in my sleep
> 
> yeah right

please do not act as though atmospherics is difficult or some arcane task that can't be done by normal humans

**Comment by ShoziOffical** [comment]
its a decent recipe, anyway can do it but it will take time

**Comment by Simplehorror** [comment]
yeah anyone can do it

**Comment by ShoziOffical** [comment]
> yeah anyone can do it

Yeah if they learn atmos

**Comment by UltraBigRat** [comment]
> i could get these requirements in my sleep

I will eat my jorts if you post a video of yourself making hyper noblium

**Comment by ShoziOffical** [comment]
This recipe is not too easy and not too hard to do

**Review by ReddicusDragon — COMMENTED** [review]
this is incredibly stupid and potentially griefy

**Comment by ShoziOffical** [comment]
> this is incredibly stupid and potentially griefy

Nah, the stupid one is it can be ordered from cargo, should be made here instead, grief? Nah, it logs everything so admin will noted if someone will try to grief
Cargo can just order one from cargo which is way more simple

**Comment by ShoziOffical** [comment]
I will change this to require more extra steps

**Comment by Annoying-plant** [comment]
Thats alot of Hypernobillium it needs and if hyper nob production gets capped at what was suggested in Simplehorors PR this  will take a long time to make

**Comment by ShoziOffical** [comment]
> Thats alot of Hypernobillium it needs and if hyper nob production gets capped at what was suggested in Simplehorors PR this will take a long time to make

wait what

**Comment by warface1234455** [comment]
265 moles of hypernob total for 1 sm shard engine

**Comment by Annoying-plant** [comment]
> 265 moles of hypernob total for 1 sm shard engine

nevermind i was being dumb i mixed up hydrogen and hyper nob though it was 1200 Hyper nob

**Comment by ShoziOffical** [comment]
> > 265 moles of hypernob total for 1 sm shard engine
> 
> nevermind i was being dumb i mixed up hydrogen and hyper nob though it was 1200 Hyper nob

imma change the desc so its more clear

**Comment by Annoying-plant** [comment]
> i could get these requirements in my sleep

if you actually learn atmos instead of using admin commands to edit gas mixtures you will find out it takes time and setup to get gasses (YES EVERY GAS IS EASY TO MAKE AND GET REQUIRMENTS FOR) the hard part is the time sink required setting up space loops mixing chambers pumping, heating and cooling gasses

**Comment by Annoying-plant** [comment]
overall i really like this PR though its cool

**Comment by knightshade0** [comment]
> please do not act as though atmospherics is difficult or some arcane task that can't be done by normal humans

This from the guy who didn't know how heat exchangers worked.

**Comment by Simplehorror** [comment]
> > please do not act as though atmospherics is difficult or some arcane task that can't be done by normal humans
> 
> This from the guy who didn't know how heat exchangers worked.

says who? lol?

**Comment by Simplehorror** [comment]
> > i could get these requirements in my sleep
> 
> if you actually learn atmos instead of using admin commands to edit gas mixtures you will find out it takes time and setup to get gasses (YES EVERY GAS IS EASY TO MAKE AND GET REQUIRMENTS FOR) the hard part is the time sink required setting up space loops mixing chambers pumping, heating and cooling gasses

again, please don't act like every department isn't trivial after so many hours

**Review by cuackles — APPROVED** [review]

**Review by MajManatee — APPROVED** [review]
While i dont like the idea of making cargo less relevant, i never see crystallizers used, so that's cool

**Comment by JamieD1** [comment]
Eh fuck it lets try it.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
