### PR TITLE
You cannot make cult golems unless you are cult

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

_Only one with forbidden knowledge could hope to work this metal..._

tested and working

#### Changelog

:cl:  
tweak: You can no longer make cult golems unless you are cult
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
why

**Comment by ynot01** [comment]
> why

non-cultists should not have access to overpowered cult material, the same reason noncultists cannot use cult metal or other cult gear

**Comment by boodaliboo** [comment]
why? i understand cult golem but not clock golem

**Comment by Tipy1802** [comment]
Does this include golems like the xenobio ones?

**Comment by Tipy1802** [comment]
Never mind it’s just the cult ones, I guess it’s fine then

**Comment by Marmio64** [comment]
i wouldn't say either of these are OP. Sure they are powerful, but do they need to be removed from random players? However, if this is added i'll probably add a way to sell cult metal in cargo (if you can't already, i dont know) so that it isn't totally useless.

**Review by jcatjmeow — APPROVED** [review]
Code looks fine to me

**Comment by Hopekz** [comment]
While not "OP" it seems like an oversight.
I don't think people can use cult metals normally to make things so it seems like inconsistent behavior to keep this in.

**Comment by UselessTheremin** [comment]
Sad cogger noises

**Comment by ghost** [comment]
@ynot01 @Hopekz it is neither OP nor an oversight

it was very much intended behavior

much like the chaplain can create crew-sided constructs (which is intended) if they get their hands on a construct shell and a purified soulstone xenobiology can create runic golems if the crew recovers runed metal

**Comment by ghost** [comment]
also the PR that added runic golems intentionally specified they were meant to look culty but not be necessarily cult sided

**Comment by Hopekz** [comment]
> also the PR that added runic golems intentionally specified they were meant to look culty but not be necessarily cult sided

Are you referring to this PR?
https://github.com/tgstation/tgstation/pull/25028


That PR is on TG.
We have not had this discussion yet on yogs. The PR that added the runic golems to yogs also didn't mention anything like that.

Remember; we are not TG so what might be intentional there might not be intentional here as it was added here in the form of a lazy port without any real discussion, making it a potential oversight.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
