### PR TITLE
ALL LOWPOP ACCESS SHOULD HAVE MAINT ACCESS, ALL CARGO SHUTTLES AND AIRLOCKS ARE PUBLIC

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request

updates access to all jobs (that dont got maint access) have maint access during low pop
access to airlocks in cargo (to shuttle) and on the shuttle are now public airlocks

# Why is this good for the game?
i think we are pretty sick and tired of kudzu everywhere during lowpop when you dont got access, getting them the ability to reach these hard to reach spots can really help during low pop. as a part of this cargo airlocks and shuttle will have public access to get to materials needed to deal with these situations, also helps spice up the round when there isnt a cargo tech or miner.

# Testing
checked once to see that access applies to jobs

# Changelog

:cl:  

tweak: all station jobs have maintenance access during lowpop
mapping: all cargo shuttles and the airlock connecting it are public access

/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
kudzu being a nightmare isn't a reason to give every job maint access
people should learn to hack if it matters that much
or maybe do something about kudzu

**Comment by wonderinghost** [comment]
> kudzu being a nightmare isn't a reason to give every job maint access people should learn to hack if it matters that much or maybe do something about kudzu

yeah however the problem with kudzu is that when it happens it spreads everywhere, and during these low pops when no one is in every part of the station to report on said vines. by the time people notice it be too late to effectively do anything about it except call the shuttle

**Comment by wonderinghost** [comment]
it adds more tedium to rounds when having to manually hack open every door to deal with vines

**Comment by Mqiib** [comment]
This is what emergency maint access is for. Don't give everyone maint.

**Comment by cowbot92** [comment]
there's so much random stuff changed in this PR, did you take a sledgehammer to it??

**Comment by wonderinghost** [comment]
> there's so much random stuff changed in this PR, did you take a sledgehammer to it??

if its random its becuase of my mapmerge tools, i dont know whats causing it but i cant build it normally without modifying the mapmerge tool. which i got from biome back when i was porting disposals.

**Comment by wonderinghost** [comment]
> This is what emergency maint access is for. Don't give everyone maint.

and players dictate otherwise. how often do you pop on and look at what jobs are taken up. if you dont see head or security then there is a 70 percent chance no one is asked to fill that position to give up a focus on their goal.

**Comment by wonderinghost** [comment]
@cowbot92 if this is such a problem than look at my recent mapping prs. because those have also been plagued by the issue where i cant build with the mapmerge tool

**Comment by cowbot92** [comment]
> @cowbot92 if this is such a problem than look at my recent mapping prs. because those have also been plagued by the issue where i cant build with the mapmerge tool

you should probably ask biome for help

**Comment by wonderinghost** [comment]
> > @cowbot92 if this is such a problem than look at my recent mapping prs. because those have also been plagued by the issue where i cant build with the mapmerge tool
> 
> you should probably ask biome for help

I did. All the way back in my disposal port pr

**Comment by Therandomhoboo** [comment]
Against this for several reasons:
The big one is, you can literally hack doors. This is good for teaching people how to hack doors cause beforehand I had no idea, after having literal 0 access everywhere it actually helped me learn how to hack doors which is very simple.

There is no actual reason for low-pop to gain maint-access especially if this is just literally made for space vines. All this does is make it easier to antags to get around and lure people into maints since free access will goat idiots into them.

As for the cargo shuttle and its subsequent airlock access change, this is bad, because quite literately you just opened a free-entrance to cargo without having to have access..... which is going via the airlocks which means Cargo is easy pickings to break into any point now. As well, if im reading it right, this isn't just for low-pop this is general access for the cargo area part.

Hell, it make stealth stronger. Go to the supply shuttle airlocks, walk in. Now you're at the console with minimal effort.

So yeah, pr don't seem like it was well thought out and more Gus-reactive type of PR.

**Comment by Therandomhoboo** [comment]
Also, if I hear one more cry about space vines I think I'm going to actual flid my lid:
Space vines have been soft cucked (apart from ice-meta bug) and its venus counterpart by the following:
They take 2x more damage from goats, fire & weedkiller
Venus can't drag anymore
Venus can't reproduce to make more if the area is depressurised
They are slow

Like, what are you guys doing to struggle with space vine? Sleeping in cryo pods? You guys have so many handouts to deal with space vines and its still a problem? Literally grab an rcd, find where the space vine is, decon the wall/floor and then deal with it. 
Or better yet, grab the round start scythe & grenades from the botany lockers whilst someone orders more?

The biggest problem by far I've seen is icemeta space vines growing through multi-levels. Other then that, you guys are just fumbling it hard by not working together. Just like with Xenos, just like with Blob. Just like with any fuckkken antag that has potential to over-run the station. It isn't an game issue, its a player issue,

**Comment by AMyriad** [comment]
All this just for kudzu? This'll affect a lot more than the crew vs. evil plant matchup. If the plant is the problem I'd rather see something done about it than widescale access changes.

**Comment by wonderinghost** [comment]
> Against this for several reasons:
> The big one is, you can literally hack doors. This is good for teaching people how to hack doors cause beforehand I had no idea, after having literal 0 access everywhere it actually helped me learn how to hack doors which is very simple.
> 
Fair. But you still have to hack open and bolt multiple doors with different wire access to deal with vines.

> There is no actual reason for low-pop to gain maint-access especially if this is just literally made for space vines. All this does is make it easier to antags to get around and lure people into maints since free access will goat idiots into them.
> 
And can you name more reasons why it shouldn't? And if this is a high pop issue or a generalized problem. 

We can be here until the end of this pr to the closing of this server which will never be remembered because it was in discord public.

I can name more reasons why its good.
Like how it can be a good escape for crew when a antag pops in. 

Medical doctors and chemists when there isn't para meds or doctors to go into maint to pull out dead bodies of victims

Crew can finally get to safety during radstorms when there isn't a ai or a head of staff active 

And so on. And don't forget this is for lowpop of 30 below 

> As for the cargo shuttle and its subsequent airlock access change, this is bad, because quite literately you just opened a free-entrance to cargo without having to have access..... which is going via the airlocks which means Cargo is easy pickings to break into any point now. As well, if im reading it right, this isn't just for low-pop this is general access for the cargo area part.
> 
Fair on this part. However a access lock on the shuttle is still kind of wonky

However you also don't play. Probably the most precedent is no one plays cargotech or qm anymore outside of the mains. 

And for who? Nukies for the few times they don't go nuclear because spoiler, it's still really easy to break in and get to the captain. Pirates can also do this very easily but that's dependant on pop and who is playing 
> Hell, it make stealth stronger. Go to the supply shuttle airlocks, walk in. Now you're at the console with minimal effort.
>
It's only at the airlocks connecting the shuttle
> So yeah, pr don't seem like it was well thought out and more Gus-reactive type of PR.
> 
> 

Its a lot more thought out when it's on my playtime. Every subsequent round vines always happen and they already spreaded to a 6th of the station and in separate parts.

I have been here in both active hours and off hours of this server for 2-3 years now. This is a culmination of bad decisions and practices to thoughts in the making before this pr was made 

If general low pop and high pop exceed the current bar this summer than this is more likely going to be a seasonal change that has to happen

**Comment by Therandomhoboo** [comment]
> Fair. But you still have to hack open and bolt multiple doors with different wire access to deal with vines.

What? Most wires maint are the same, and the ones that connect to the department are the same two. At best you need to figure out two wires, unless you're hacking the airlocks which can be different when the cargo shuttle lands or miner shuttle

> And can you name more reasons why it shouldn't? And if this is a high pop issue or a generalized problem.
> We can be here until the end of this pr to the closing of this server which will never be remembered because it was in discord public.
> I can name more reasons why its good. Like how it can be a good escape for crew when a antag pops in.
> 
> Medical doctors and chemists when there isn't para meds or doctors to go into maint to pull out dead bodies of victims
> 
> Crew can finally get to safety during radstorms when there isn't a ai or a head of staff active
> 
> And so on. And don't forget this is for lowpop of 30 below

Right, crew don't need that "extra" step up. It's been proven crew will validhunt over anything else if push comes to shove. Making it now that crew can freely go in and out of maints just makes maints even harder for antags to do anything in (cause you're going to have people searching for maint loot) and annoying for sec to deal with (having to see random strangers going through constantly)
Medical and chemists can just learn hacking yet again, its simple and it isn't their priority job to collect bodies regardless of paramedics or not. There are other crew members on there that im sure have maint access that can exist, if it is just two job roles on it then sure thats a problem but we're not making prs for literally 3 pop.

I could be wrong, but if there are no AI the maint doors automatically unlock for everyone to stop that issue. If not, then we can just make it do that. Problem solved.

During what I said, I think i added more reasons why it shouldn't be added tbf.

> And for who? Nukies for the few times they don't go nuclear because spoiler, it's still really easy to break in and get to the captain. Pirates can also do this very easily but that's dependant on pop and who is playing
> 
> > Hell, it make stealth stronger. Go to the supply shuttle airlocks, walk in. Now you're at the console with minimal effort.
> 
> It's only at the airlocks connecting the shuttle

Right im confused a little on this, because do you mean the shuttle airlock doors or the cargobay airlock doors? Cause you would need access to both to get into the cargo shuttle in the first place, unless you have cargo access that lets you. So which is it? If it does let you have access to the shuttle (which  then would be cargo airlock doors too) then yeah. My point again, and if this pr goes in then every traitor would. Because its easy to get into and now you have access to ordering stuff.


> > So yeah, pr don't seem like it was well thought out and more Gus-reactive type of PR.
>
> Its a lot more thought out when it's on my playtime. Every subsequent round vines always happen and they already spreaded to a 6th of the station and in separate parts.
> 
> I have been here in both active hours and off hours of this server for 2-3 years now. This is a culmination of bad decisions and practices to thoughts in the making before this pr was made
> 
> If general low pop and high pop exceed the current bar this summer than this is more likely going to be a seasonal change that has to happen

It isn't a major issue, I'm sorry but I've not seen anyone else gripe about not having access. And you yourself saying about vines and what not, I can 1000% promise its an IC issue and not a gameplay issue. 
A lot of players are fucking scared of teaming up or don't want to help cause they can't be arsed. Space vines has several counters to it.
Use them then come back.

**Comment by wonderinghost** [comment]
> What? Most wires maint are the same, and the ones that connect to the department are the same two. At best you need to figure out two wires, unless you're hacking the airlocks which can be different when the cargo shuttle lands or miner shuttle
> 
Most are the same but you have to deal with it spreading into departments that have different wires

> 
> Right, crew don't need that "extra" step up. It's been proven crew will validhunt over anything else if push comes to shove. Making it now that crew can freely go in and out of maints just makes maints even harder for antags to do anything in (cause you're going to have people searching for maint loot) and annoying for sec to deal with (having to see random strangers going through constantly)
> Medical and chemists can just learn hacking yet again, its simple and it isn't their priority job to collect bodies regardless of paramedics or not. There are other crew members on there that im sure have maint access that can exist, if it is just two job roles on it then sure thats a problem but we're not making prs for literally 3 pop.
> 
In a perfect world yes it wouldn't be a top priority. However this isn't a perfect world. More often than not you end up with ssd and catatonic people for a round. Most people would end up doing that person's job because they want the round to continue or accomplish something. I am a medical main and know for a fact on 80 percent of cases if no one knows you exist they are fine breaking in and reviving people. Or have the island nation that is security walk past 2 engineers to fix the engine because they didn't notice the jumpsuit 

> Right im confused a little on this, because do you mean the shuttle airlock doors or the cargobay airlock doors? Cause you would need access to both to get into the cargo shuttle in the first place, unless you have cargo access that lets you. So which is it? If it does let you have access to the shuttle (which  then would be cargo airlock doors too) then yeah. My point again, and if this pr goes in then every traitor would. Because its easy to get into and now you have access to ordering stuff.
> 
The shuttle airlock and the airlocks that dock it

> It isn't a major issue, I'm sorry but I've not seen anyone else gripe about not having access. And you yourself saying about vines and what not, I can 1000% promise its an IC issue and not a gameplay issue. 
> A lot of players are fucking scared of teaming up or don't want to help cause they can't be arsed. Spa

A lot can be left unspoken. There is a aspect here that sits in the back of your mind. I'm the aspect that surfaces

**Comment by Therandomhoboo** [comment]
> Most are the same but you have to deal with it spreading into departments that have different wires

It is quite literally flicking through a couple more wires, skill issue sadly.

> In a perfect world yes it wouldn't be a top priority. However this isn't a perfect world. More often than not you end up with ssd and catatonic people for a round. Most people would end up doing that person's job because they want the round to continue or accomplish something. I am a medical main and know for a fact on 80 percent of cases if no one knows you exist they are fine breaking in and reviving people. Or have the island nation that is security walk past 2 engineers to fix the engine because they didn't notice the jumpsuit

Report the SSD & catatonic people so the bad faith players get removed so slots get freed up, yes on low-pop other people do other jobs, but you medbay players will literally communicate with 0 other people so na, its an IC issue not a gameplay issue. It is just hugboxxing

> The shuttle airlock and the airlocks that dock it

So... Instead of having to through cargo main entrance which is two doors. I can go into space and go through the cargo shuttle airlock and be in there (if not I think its just one door hack so i unno but im sure the two airlocks are the same access)? what? na dude.

>A lot can be left unspoken. There is a aspect here that sits in the back of your mind. I'm the aspect that surfaces

What? What aspect? That you can't fight vines?

**Pull request closed without merging**
