### PR TITLE
Ports gangs from Hippie

### PR DESCRIPTION
**Pull request by daklj**
Good old gangs, the only new thing i've found is the lack of that thompson machine gun. Most of this is a blatant copypaste, seems to work. Will test it thoroughly later.

:cl:  
rscadd: Added gangs
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
once you've done basic testing like making sure the dominators work properly, it's probably easier to just testmerge it than it is to test it locally

**Comment by ThatLing** [comment]
@daklaj ping me on discord when you are up for a testmerge.

**Comment by daklj** [comment]
Local tests done, everything seems to work fine.

The gamemode id for `config/game_options.txt` is `GANG`

**Comment by ThatLing** [comment]
Admin HUD icons are a bit wonky and sometimes shows the same icon for different gangs.

**Comment by ghost** [comment]
remember that gangs was complete shit and universally hated on yogs and we didn't even have /tg/'s mulitations to the gamemode that made it even worse?

yeah

why are we adding it back

**Comment by Amelia0010** [comment]
This PR doesn't enable gangs, it just adds them. So for it to ever be played, we'd need admin intervention or the council to turn it on via config

**Comment by Nirnael** [comment]
Seriously though, this needs a change. Right now with the implant breakers, this is an absolute cesspool of a round. Implant breakers are cheap for gangs, but not for sec. It takes one dipshit to camp sec and tase all the implanted then break the implants.

**Comment by fluffe9911** [comment]
it seems the fake tags are invisible

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
there's still broken stuff from over two weeks ago, once you fix it it's good to go

**Comment by Amelia0010** [comment]
rup

**Pull request closed without merging**
