### PR TITLE
Mutation toxin no longer works on IPCs

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Title

# Changelog

:cl:  
tweak: mutation toxin no longer works on IPCs
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
I think people should be able to mutate IPCs.

**Comment by ThatLing** [comment]
lol https://github.com/yogstation13/Yogstation/pull/18452

**Comment by RG4ORDR** [comment]
No.
You must take your catgirl toxin.

**Comment by Moltijoe** [comment]
> lol #18452

What? Thats vaccines, not mutation toxin

**Comment by iamthesilly** [comment]
Can someone explain to me why a robot should be able to mutate into an organic being

**Comment by 00ze-cyclone** [comment]
> Can someone explain to me why a robot should be able to mutate into an organic being

Because mutation toxins (like the rest of xenobio) are slime magic and I mean that literally, it's magic, that's why slimes stop time, create monsters out of thin air, craft golems or make crystals doing random bullshit.

**Comment by Moltijoe** [comment]
> Because mutation toxins (like the rest of xenobio) are slime magic and I mean that literally, it's magic, that's why slimes stop time, create monsters out of thin air, craft golems or make crystals doing random bullshit.

they're literally called toxins my dude, that literally implies some form of chemical that acts upon organic material

**Comment by 00ze-cyclone** [comment]
Toxin just mean a poison created by an organism, nothing say it cannot affect robots.
Beside even your definition doesn’t prevent it affecting robots, just because it affect organics doesn’t mean it can’t do the same for inorganics.

**Comment by Moltijoe** [comment]
> Toxin just mean a poison created by an organism, nothing say it cannot affect robots. Beside even your definition doesn’t prevent it affecting robots, just because it affect organics doesn’t mean it can’t do the same for inorganics.

robots aren't organic material, toxins affect organic material

**Comment by Moltijoe** [comment]
balance council prefers IPC be immune, rather than adding a toxin to transform into them

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
