### PR TITLE
Prematurely cancelling desynchronizer now has serious downsides and nerfed max time

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

50 clone damage + vomit

Also capped to 60 seconds instead of 5 minutes

# Changelog

:cl:  
tweak: Desynchronizer is now capped to 60 seconds instead of 5 minutes
rscadd: Added downsides to prematurely cancelling desynchronizer
/:cl:

### CODE REVIEW

**Comment by UltraBigRat** [comment]
50 clone is alot for something so small. And why would you have it deal the hardest to cure damage type?

**Comment by ynot01** [comment]
> 50 clone is alot for something so small. And why would you have it deal the hardest to cure damage type?

invincibility comes at a cost, or wait out the duration you set

**Comment by UltraBigRat** [comment]
> > 50 clone is alot for something so small. And why would you have it deal the hardest to cure damage type?
> 
> invincibility comes at a cost, or wait out the duration you set

Yes but the thing is, this doesnt really fix any issues with it?  you can still safely chain desynchronizers and gain effective infinite invincibility at the cost of not being able to do anything all this does is severely punish anyone using it for anything actually practical or fun, i feel the real issue is them being chainable? could just not add any downsides and prevent chaining them? otherwise this just feels like an unnesecarry nerf that doesnt actually fix any core issues and punishes people with extreme severity for doing anything BUT chaining them and doing nothing other then being invincible.

**Comment by ynot01** [comment]
> i feel the real issue is them being chainable? could just not add any downsides and prevent chaining them? otherwise this just feels like an unnesecarry nerf that doesnt actually fix any core issues and punishes people with extreme severity for doing anything BUT chaining them and doing nothing other then being invincible.

chaining them is _one_ issue, not _the_ issue. that issue is not being addressed in this PR, this is a general nerf to the item which is very powerful on its own even without chaining being in scope. if you deny that this on-demand invincibility item is strong then you simply disagree with me and you're free to do so.

**Comment by MajManatee** [comment]
Pretty weird change, not really a fan of cloning dmg. Seems like a really easy way for someone to me fucking around with it trying to learn and killing themself

**Comment by Notamaniac** [comment]
>  if you deny that this on-demand invincibility item is strong then you simply disagree with me and you're free to do so.

psssst did you hear anyone say that the immortality talisman was op
also psssst on demand invincibility is pretty useless when you can do absolutely nothing while invincible
also also pssst pssst this is locked behind illegal tech and unregulated bluespace research, which are late game nodes and therefore not very easily printed or abusable

**Comment by MajManatee** [comment]
plus you pop out in the same place. Its already a VERY niche tool, this just makes it even less usable

**Comment by ynot01** [comment]
> psssst did you hear anyone say that the immortality talisman was op

Immortality talisman lasts like 5 seconds and can't be cancelled pre-maturely, not that you'd want to because it lasts 5 seconds, is incredibly obvious, and has a long cooldown

**Comment by Notamaniac** [comment]
> Immortality talisman lasts like 5 seconds and can't be cancelled pre-maturely, not that you'd want to because it lasts 5 seconds, is incredibly obvious, and has a long cooldown

Okay let's try flip this around- what are the use cases for this? In what situations do you see this item being used?

**Comment by ynot01** [comment]
> Okay let's try flip this around- what are the use cases for this? In what situations do you see this item being used?

Someone trying to kill you

You use the item

For the next 5 minutes they are completely unable to touch you

If at any point they get bored and leave you can just exit the pocket for free

This is assuming you didn't first call out your location and security are not coming

**Comment by Notamaniac** [comment]
> Someone trying to kill you
> You use the item
> For the next 5 minutes they are completely unable to touch you
> If at any point they get bored and leave you can just exit the pocket for free
> This is assuming you didn't first call out your location and security are not coming

Okay, let's completely and utterly ignore the fact that chaining desynchronisers is a thing- what does this nerf do to stop that?

Sure you wait out the entirety of the desynch length. But the attacker doesn't know what length you've set it to. They're still forced to sit there for up to five minutes. If they leave, you can still just eat the clone damage (assuming you're at full health) and yell over radio that so and so attacked you at x - if you're impatient enough. 

You still haven't adressed the core issue here. Sure if they abort early they'll be stunned and vulnerable- but if they're relying on the desynchroniser, chances are they didn't have any real method to fight back to begin with and are using it as a desperado move to delay the inevitable.

All you're doing by using it is just wasting time. You aren't killing the attacker, you aren't calling sec, you aren't actively healing, you aren't running away, you're doing precisely one thing - sitting in one spot doing nothing.

**Comment by ynot01** [comment]
> what does this nerf do to stop that?

Caps it to one minute and punishes you for using it without considering the length you had set it to

> Sure you wait out the entirety of the desynch length. But the attacker doesn't know what length you've set it to. They're still forced to sit there for up to five minutes. If they leave, you can still just eat the clone damage (assuming you're at full health) and yell over radio that so and so attacked you at x - if you're impatient enough. 

The clone damage is difficult to remove and will be an annoyance as punishment until you can get to medical and sit in cryo and if the attacker is waiting nearby they can use this incredibly vulnerable state to capitalize

> You still haven't adressed the core issue here. Sure if they abort early they'll be stunned and vulnerable- but if they're relying on the desynchroniser, chances are they didn't have any real method to fight back to begin with and are using it as a desperado move to delay the inevitable.
> 
> All you're doing by using it is just wasting time. You aren't killing the attacker, you aren't calling sec, you aren't actively healing, you aren't running away, you're doing precisely one thing - sitting in one spot doing nothing.

I'm not sure what you think the "core issue" is. The design of the item itself? Are you implying we should buff it in some way? I believe you are overthinking what is a simple nerf to a rather strong item.

**Comment by Notamaniac** [comment]
I don't think I'm going to convince you here so I'll just leave it.

All I'll say is that if it WAS a strong item, everyone would be using it. Except they aren't. You merge this, you'll make it a slightly better version of the immortality talisman. If you believe that the immortality talisman was useless just because it had a tell and a high cooldown, then you won't believe this nerf will make the desynchroniser just as useless as the immortality talisman.

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
