### PR TITLE
Introducing the TagMaster 3.0! Converts the TagMaster 2.2 to use TGUI

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

# Wiki Documentation

Less shiddy tagmaster

# Changelog

:cl:  
tweak: makes destination tagger use nice tgui instead of shitty Topic() that had no formatting
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
I wonder if it would be possible to automatically assign tags to mail based on the job of the mail receiver. Atmos techs get tagged with atmospherics, clown gets theatre. Etc etc

**Comment by ToasterBiome** [comment]
> I wonder if it would be possible to automatically assign tags to mail based on the job of the mail receiver. Atmos techs get tagged with atmospherics, clown gets theatre. Etc etc

Yes this is possible BUT it takes away from gameplay™️

**Comment by adamsong** [comment]
Can you select multiple tags at once?

**Comment by ToasterBiome** [comment]
> Can you select multiple tags at once?

no

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
