### PR TITLE
Should fix station goals never triggering

### PR DESCRIPTION
**Pull request by Moltijoe**
It never called the station goal report so it never enabled the purchase at cargo

# Testing
none

:cl:
bugfix: Should fix station goals never triggering
/:cl:

### CODE REVIEW

**Review by ToasterBiome — APPROVED** [review]

**Comment by Oblisk234** [comment]
Could you add "Fixes #22807" to your PR description?

**Comment by ShoziOffical** [comment]
> Could you add "Fixes #22807" to your PR description?

can't you link it?

**Comment by Oblisk234** [comment]
> > Could you add "Fixes #22807" to your PR description?
> 
> can't you link it?

This is not my PR, I cannot edit other people's PR descriptions. That and PRs autoclosing issues makes handling issues easier.

**Comment by ShoziOffical** [comment]
> > > Could you add "Fixes #22807" to your PR description?
> > 
> > 
> > can't you link it?
> 
> This is not my PR, I cannot edit other people's PR descriptions. That and PRs autoclosing issues makes handling issues easier.

i meant maintainer can link it, why cant you right, i remember maintainer can link pr to an issue

**Comment by Oblisk234** [comment]
> > > > Could you add "Fixes #22807" to your PR description?
> > > 
> > > 
> > > can't you link it?
> > 
> > 
> > This is not my PR, I cannot edit other people's PR descriptions. That and PRs autoclosing issues makes handling issues easier.
> 
> i meant maintainer can link it, why cant you right, i remember maintainer can link pr to an issue

Not sure what you mean?

**Comment by ShoziOffical** [comment]
> Not sure what you mean?

image

this was someone else pr

**Comment by Oblisk234** [comment]
> > Not sure what you mean?
> 
> image
> 
> this was someone else pr

That's very odd? Pretty sure it usually doesn't do that, for example how this issue is at present:
image

**Pull request merged**
