### PR TITLE
no more announcement console bigotry

### PR DESCRIPTION
**Pull request by Amelia0010**
see: https://discordapp.com/channels/134720091576205312/186490543398715392/750724537481429082

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Make it alert the mins too so they get annoyed

**Review by jcatjmeow — APPROVED** [review]

**Comment by Amelia0010** [comment]
nah

**Comment by TrojanWhite** [comment]
LOOOOOOOOOOOOOOL

**Comment by d3athrow** [comment]
lol

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
