### PR TITLE
Vampires can now go loud and unlock all abilities

### PR DESCRIPTION
**Pull request by ToGWtF**
### Intent of your Pull Request
Vampires can now go loud and unlock all abilities instantly. Also gives them a pool of 450 useable blood to actually use their abilities

Forces them to have a blood objective that's equal to multiple kill objectives

Forces them to wear a dracula cape. No more hiding in plain sight.

They lose the ability to transform if they drink enough blood to unlock even one new power.

#### Changelog

:cl:  
rscadd: Gives vampires new transformation. Unlocking their true powers
/:cl:

### CODE REVIEW

**Comment by Takahiru** [comment]
this is actually shit

**Comment by ynot01** [comment]
literally anything is better than what we have now lol

**Comment by patpol4** [comment]
i wanted to say no but i read the description and i'm going to say yes

**Comment by yacabo** [comment]
War vamps

**Comment by overlord12345** [comment]
its bad but its better then what we have so meh

**Comment by Hopekz** [comment]
I think this PR is worth a try.

**Comment by Takahiru** [comment]
This completely removes the point of having any early game vampire whatsoever, every time when there is a vampire as soon as they get enough to have all powers theres literally no point in hiding it so they just wear the cloak walk around and if they meet any trouble they use one of their many many escape tools to get away, this will just make vampire fake wizards is all.

**Comment by Jarod1200** [comment]
I feel like this should only be an option on high pop because pressing a gamer button to become an anemic bootleg wizard kinda takes the "be stealthy and snowball your power out of it." 
Vamps that make it to full potential anyway usially have no problem sucking a ton of blood and making a ton of new bloods.

**Comment by Marmio64** [comment]
i mean.... okay... but i'd rather have some changes to the abilities then just something like this.

I'd rather have it if vampires lost their jaunt and the screech only heavily disoriented people with ear protection instead of stunning them. To buff vampires then since they'd lose their most powerful ability and have another one nerfed, hypnotize should be a instant cast and stun for 5 seconds while muting for 10, however the stun is delayed by two seconds and gives a big warning to the person being hypnotized. Hypnotize also shouldn't work on mindshielded people though because the implant would protect them. 

 Along with this vampires should be able to transform into a Nosferatu and back with a 30 second toggle cooldown. While Nosferatu they are obviously a vampire , lose human status (if they had it), and no longer have any benefits or drawbacks of their previous species,  however they move 15% faster than humans, get 50% stun resistance, get a slow passive healing, and drink blood at twice the rate.

**Comment by Takahiru** [comment]
I believe having marmio's Nosferatu idea is much much better than this, this literally lets multiple antags get wizard powers roundstart. This just removes the entire point of vampire being getting powers over time and just makes it a worse wizard. This will make vampire even worse

**Comment by Alexandria404** [comment]
seems like a murderbone increase

**Comment by alexkar598** [comment]
Yeah how about no. This fits hippie or tg but not the slower experience yogs is *trying* to be

**Pull request closed without merging**
