### PR TITLE
The great I ded blood cult rune nerf pr

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:    
tweak: Barrier rune now lasts 30 seconds and has a cooldown of 10 seconds, no more instant-win-unless-surprise-nullrod
tweak: Blood boil rune now deals half damage  
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Well shit. Guess I will no longer convert critted people

**Comment by Ratvar** [comment]
You can, just 

- use literal blood magic healing spell
- stack pylons
- feed them unholy water
- use normal medication
- kill them and make constructs 

Like, you would only even care to heal powergamers that actually can function as human cultists. Otherwise it's better to construct them anyway.
Are you sure *it's not a buff*?

**Comment by SomeguyManperson** [comment]
Clock cultists don't get heal on convert but you don't see them complaining when they have to cast sentinels compromise, meanwhile bloodcult gets passive healing structures and a spell that can heal people and is recharged by.........clicking blood on the floor.

**Comment by HomocidlePancakes** [comment]
1) >Clock cultists don't get heal on convert but you don't see them complaining when they have to cast sentinels compromise

Thats because it barely costs anything

2) > meanwhile bloodcult gets passive healing structures

Only in base unlike the sentinels that can be used anywhere

3) >spell that can heal people and is recharged by.........clicking blood on the floor.

Not worth investing in to it after TG gimped the amount of blood you can get to use it. Also, unlike sentinels, it costs you an extra stun/escape and requires farming to be useful.

**Comment by HomocidlePancakes** [comment]
1) > use literal blood magic healing spell

See post above

2) > stack pylons

Won't have that in the field

3) > feed them unholy water

Why not just kill and leave them? Also not everyone will have it on them.

4) > use normal medication 

Why not just kill them leave them? Also not every player is a portable medbay.

5) > kill them and make constructs

Why not ju...(I think you get the point)
People would prefer to be actual cultists instead of handicaped constructs. Plus you will need to make a shell for them and there isn't enough for everyone.

**Comment by SomeguyManperson** [comment]
>won't have that in the field

You always have a base in the field; it's called "shitting out a telerune for 0.5% of your max health" which you will be doing anyways to convert someone since it's faster than finding someone outside the base to convert with you
>sentinel's compromise is cheap

You forgot the part where the person is going to be hobbling around at half speed unless they finish healing from (who would have guessed) going to a base.
>why not just kill them and leave them

Why not just turn everyone into vitality on a clock cult round? Regardless of the fact you can both get vitality and convert easily/blood rites someone then convert them, or that it's actually less risky to blood rites someone before converting since it *won't work if their blood is below safe levels*. If you use the charges of blood rites to heal the person they get 50 health which is more than enough to stand back up if you're stabbing people until they fall over.

**Comment by Lynameep** [comment]
Rat'var Approves.

**Comment by HomocidlePancakes** [comment]
1) > "shitting out a telerune for 0.5% of your max health"

Shit boyo. Noone ever bothers dragging crited people to base. Thats why the heal was added in the first place

2) > You forgot the part where the person is going to be hobbling around at half speed

Thats irrelevant. I healed them out crit.

3) > Why not just turn everyone into vitality on a clock cult round?

Thats liturally what everyone does lategame or, ya know, the point where both cults crit alot of people?

4) >  or that it's actually less risky to blood rites someone before converting since it won't work if their blood is below safe levels.

You can't drain blood out of someone you recently stunned with your meme red hand.

5) >  If you use the charges of blood rites to heal the person they get 50 health which is more than enough to stand back up if you're stabbing people until they fall over.

"heal the person they get 50 health". This implies I made blood rites to specifecly heal this one guy after critting him. So I have 4 spells. One of them has to be stun. I decide to stab a guy to crit instead of stunning. Then I decide to convert him for some reason, remove one of my spells for rites, drain him, convert and heal. Excuse me what the fuck?

**Comment by SomeguyManperson** [comment]
>stab a guy to crit instead of stunning
decide to convert for some reason

So we can agree that if you put someone into crit they won't be getting converted in the first place, which makes the heal on convert completely superfluous as you either
>stun the person and convert them

Or
>crit and sac the person

Already

>remove a spell for blood rites

Implies you don't already have charges for blood rites, the skill that already has far too much utility in that it can create a buffed clock spear, wizard barrage spell, or converty beams to break into sec/AI core

>drain the guy, convert, then heal

So basically the current thing you'd be doing in that scenario except the person doesn't get back 75% of their health for free

The conversion would go from

>crit man because it's faster than stun hand
Shit out conversion rune on the spot
Blood rites, convert, then forget since the guy is now back above the damage slowdown threshold

To

>crit man
Shit out conversion rune on the spot
Blood rites, convert, and spend blood rites charges or any of the other fifty ways you can heal people to get them out of crit

>blood rites/teleporting to a base with a pylon takes a miniscule amount of extra work to convert someone who's in crit
That's irrelevant, they are being healed out of crit.

**Comment by HomocidlePancakes** [comment]
I really liked how you described the whole conversion process time but at the same time completely ignored this

>Shit boyo. Noone ever bothers dragging crited people to base. Thats why the heal was added in the first place

Same applies to sacrificing. Or getting shells for shades. People are lazy and the heal was added to atleast somehow fix that. But since it’s gone... Yeah.

**Comment by SomeguyManperson** [comment]
How does having a heal change the fact people won't convert/sac in the first place? If someone wants to convert someone after critting them in either case they'll be placing a singular rune and using it a grand total of one or maybe two times. The difference is with the heal it's much faster to crit someone than it is to use the dedicated stun and spell for it, qnd the downside to critting the person is completely removed if they just get healed for free. You don't need to drag someone back to the base ever to convert them, just place a teleport rune on the spot and use that to get them to the base,  which has a conversion rune and likely multiple pylons in it to heal them afterwards.

**Comment by ghost** [comment]
> How does having a heal change the fact people won't convert/sac in the first place? If someone wants to convert someone after critting them in either case they'll be placing a singular rune and using it a grand total of one or maybe two times. The difference is with the heal it's much faster to crit someone than it is to use the dedicated stun and spell for it, qnd the downside to critting the person is completely removed if they just get healed for free.

objectively wrong statement, stunning is faster than critting, just not always viable since you have limited stuns and repeatedly using the magic stun on the person can quickly debilitate you. the main reason this crops up at all is because people stun someone and bludgeon them with a cult sword as they drag them to a rune, which usually kills the person before they end up on the rune

it's also there to allow cultists to convert people who attack them and have at least one person at full health after an attack if there are any survivors, as opposed to having a bunch of useless soulstones without a shell because cultists are always too stupid to plan ahead and have a shell surplus

the main reason this shows up at all is because people drop conversion runes in the middle of the hallway late game and fight people, then toss them on the rune, and that's risky since it can blow off limbs which are not restored when the damage is fixed, or cut out organs. 

enough to knock the person out of critical but keep them at a maximum of 10 health would be preferable, since the individual still needs to heal and is still likely bleeding, but it does make it possible for new converts to continue to exist when the cult is retarded and a jugg punches your convert 3 times.

the REAL issue, however, is what you're doing to blood boil, which is incredibly stupid.

**Comment by SomeguyManperson** [comment]
Heal on convert is back, but it should leave the convertee just barely out of crit/in extremely light crit at high damage, rather than safe from the damage slowdown threshold

**Comment by Altoids1** [comment]
https://forums.yogstation.net/index.php?threads/vote-merge-https-github-com-yogstation13-yogstation-tg-pull-5301.18996/

Council says no.

**Comment by Marmio64** [comment]
this is good PR though

**Pull request closed without merging**
