### PR TITLE
Reduce cooldown of creating culture bottles in virology

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

The method that most virologists use to create viruses has a very tedious bottleneck centered around the generation of creating culture bottles in the PANDEMIC. To make virology slightly less tedious than the mess of the system that it already is, I have lowered this cooldown since it doesn't really change anything aside making life harder for viros for no reason.

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Reduce cooldown of creating culture bottles in virology
/:cl:

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
50 to 5 is a very vast change. This upsets balance of the game too because then we have people like Mewsy who'll speedrun self-heal virus as viro antag

**Comment by Rdrazga** [comment]
I am not going to lie back in my time maining viro I was able to get a self resp+regen coma fully maxed virus done by the station timer hitting the 12 minute mark (Only took this long due to miners). There is 0 reason to make this any faster.

**Comment by Sniblet** [comment]
I'm not even sure how the viro strat where you make 40 culture bottles works, the cooldown has never been an issue for me and I get my viruses out in 10 minutes if RNG is nice (30 if it isn't)

**Comment by Rdrazga** [comment]
The multiple culture bottle strat was a LOT more useful when there was a decreasing chance of each trait going in above 4 traits. This no longer exists so the usefulness of spamming out culture bottles is limited.

**Pull request closed without merging**
