### PR TITLE
Even Further Heretic Adjustments: New minor things, Bug fixes, Heretic path adjustments and movement adjustments!

### PR DESCRIPTION
**Pull request by cowbot92**
Full credit for the code and sprite for the lionhunter, fire shark, rune knife and rust construction goes to these PRs
https://github.com/tgstation/tgstation/pull/65718
https://github.com/tgstation/tgstation/pull/64658
https://github.com/tgstation/tgstation/pull/73915
https://github.com/tgstation/tgstation/pull/71044

# Document the changes in your pull request

Adds new T3 heretic transmutation: Lionhunter rifle, a bolt-action rifle which carries 3 shots, which can either be shot at close range for small amount of damage, or from a longer range with a charged shot for massive amounts of damage.

Adds new T1 heretic transmutation: Carving Knife, a very sharp knife which allows you to set 3 types of traps- at a maximum of 3 per knife. The types of runes are thus: Alerting - tells you when someone steps over it, Grasping - will deal heavy damage to the legs of those who step over it, and knock them down, and Madness - will deal several debilitating status effects to those who step on it, be aware that you can also step on these runes! - This will replace the T1 ability "Void Phase"

Adds new T1 heretic transmutation: Fire shark, this summon can be controlled by ghosts, and will inject phlog into people who it bites, and upon being killed explode into a gas of plasma, leaking out into the area around it.

Adds new T1 heretic spell: Rust construction: A short cooldown spell which will allow it's user to create rust walls from rusted tiles, knocking anyone caught in the wall aside. 

Adjusts Eldritch Bolt to a T1 mind ability to replace the loss of "Mental Obfuscation"

-Rework of heretic movement abilities-

All heretic paths have been given their own jaunt, and passives to boost the class and the loss of additional movement abilities. These jaunts are slightly longer than the current ash jaunt, and heretics are given their upgraded version upon picking their path. All jaunts will be listed below

Ash - "Ashen Passage" - Grants the user 60% heat reduction and 20% burn damage reduction
Blade - "Shadow Passage" - The Heretic no longer makes sounds when walking
Cosmic - "Cosmic Passage" - Grants the user immunity to space
Flesh - "Blood Passage" - Grants the user the ability to reattach lost limbs, limbs cannot be disabled
Knock - "Expedited Passage" - Grants the user the ability to pickup bodies faster
Mind - "Mental Obfuscation" - No passive bonuses, however this jaunt will allow the user to travel slightly further.
Rust - "Decaying Phase" - Grants the user immunity to being pushed
Void - "Void Shift" - Grants resistance to cold, immunity to slipping on ice

Additional fixes: 

Makes it so you cannot purchase Void & Knock heretic basepaths at the same time. Oops.

# Why is this good for the game?

All of the new items and spells are good for variety, the Lionhunter and Rune Carver specifically will allow players who are both early game and late game to further themselves in different ways.

The Jaunts will hopefully even the playing field for every single path, firstly by making it so that heretics are not 'impossible' to catch, while giving early game heretics ways to ensure they're not dogged down instantly. 

# Testing

https://github.com/yogstation13/Yogstation/assets/75333826/ea8e0093-a38c-49b1-9518-e3f76a773228

# Spriting

mindbreak
leghurt
alert
runebreak
runecarver
image
image
image
image
image
image

# Wiki Documentation

I will update the wiki

# Changelog

:cl:  
rscadd: Adds new heretic stuff
rscdel: Removes some heretic stuff  
bugfix: fixes some heretic stuff
tweak: tweaks some heretic stuff
imageadd: adds new heretic icons

/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
god the fucking sharks

**Comment by cowbot92** [comment]
> god the fucking sharks

feesh

**Comment by ofscarletdreams** [comment]
i dont believe it the lovecraftian worshippers have sniper rifles

**Comment by maxion12345** [comment]
Adding more jaunts will make the heretic even less fun to play against. As it stands, heretics get enough "get out of jail free" cards without these additions. Most security players would agree that heretics are not fun to play against as security precisely because the jaunt is the meta pick (especially since the new meta is to combine it with that speed ability), so heretics are simply impossible to catch, or stop. It's a greentext printer with current jaunt, so giving heretics all jaunts is a bad idea.

Also, a sniper rifle? On the heretic thats based around knives? How does that fit in at all? 

Anyways, this feedback will be ignored and this merged anyways, calling it now

**Comment by cowbot92** [comment]
> Adding more jaunts will make the heretic even less fun to play against. As it stands, heretics get enough "get out of jail free" cards without these additions. Most security players would agree that heretics are not fun to play against as security precisely because the jaunt is the meta pick (especially since the new meta is to combine it with that speed ability), so heretics are simply impossible to catch, or stop. It's a greentext printer with current jaunt, so giving heretics all jaunts is a bad idea.
> 
> Also, a sniper rifle? On the heretic thats based around knives? How does that fit in at all?
> 
> Anyways, this feedback will be ignored and this merged anyways, calling it now

Hey! Sorry if it was a bit unclear but the 8 jaunts are per path, and I'm removing the other teleport options in favor of them, so heretics will go back to having one mobility option. I know you didn't really bother to read the PR so hopefully you take a second chance to look over it! I also know you don't really play the server or pay attention too-too much but all heretics already have baseline ash-jaunt as per https://github.com/yogstation13/Yogstation/pull/20610 This was just to give them a bit more 'path flavor'

Also maybe you're thinking of another server, but heretics don't have a speed up ability! Also the sniper is a port from TG, where it's a cross path (they do things a bit different) between void and blade, and all heretics can purchase it (since you probably didn't know that either) as with most things. Your feedback is absolutely appreciated when it's useful, or when it's constructive but quite honestly it's not, and you're kinda annoying! Sorry!

**Comment by MajManatee** [comment]
> Adding more jaunts will make the heretic even less fun to play against. As it stands, heretics get enough "get out of jail free" cards without these additions. Most security players would agree that heretics are not fun to play against as security precisely because the jaunt is the meta pick (especially since the new meta is to combine it with that speed ability), so heretics are simply impossible to catch, or stop. It's a greentext printer with current jaunt, so giving heretics all jaunts is a bad idea.
> 
> Also, a sniper rifle? On the heretic thats based around knives? How does that fit in at all?
> 
> Anyways, this feedback will be ignored and this merged anyways, calling it now

its bc your "feedback" is just complaining, not really constructive.

**Comment by ManofSan** [comment]
doesnt void shift basically just give aristocrat's way with the exception of still needing to breathe?

**Comment by cowbot92** [comment]
> doesnt void shift basically just give aristocrat's way with the exception of still needing to breathe?

Yes currently, this is semi-intentional as it gives void heretics technically a point to spend somewhere else, as they are the most likely to want to spec into ice spells, but may still purchase the ability if they want no breath

**Review by cuackles — APPROVED** [review]

**Comment by cuackles** [comment]
i grew to like the shark

**Comment by Djiq** [comment]
while i understand the reasoning behind the jaunt changes i feel, like they may make the heretic paths feel a lot more homogenous, which in my opinion is the opposite direction which we should be taking heretics.

**Review by ToasterBiome — APPROVED** [review]

**Comment by cowbot92** [comment]
> while i understand the reasoning behind the jaunt changes i feel, like they may make the heretic paths feel a lot more homogenous, which in my opinion is the opposite direction which we should be taking heretics.

I think that's definitely fair! I wouldnt mind taking a look at heretics as a whole with you to see about giving them all a fresh coat of paint, however at their current level and designs this baseline homogenization was very much so needed. Feel free to reach out to me on discord @Cowbot93 and maybe we can look at opening up a dev channel for heretics

**Pull request merged**
