### PR TITLE
removes a space

### PR DESCRIPTION
**Pull request by ktlwjec0**
just check the file change, removes a space and adds punctuation. no i did not test it i refuse.

### CODE REVIEW

**Comment by Yarinoi** [comment]
revolutionizing yogs

**Review by SapphicOverload — APPROVED** [review]
no more space

**Comment by iloveloopers** [comment]
why is this good for the game

**Comment by ShoziOffical** [comment]
wheres the change logs

**Comment by patpol4** [comment]
Ktl singlehandedly keeping yogstation afloat

**Pull request merged**
