### PR TITLE
reskin and new flavortext  to morphlings

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request

this pr changes the flavortext of the morphling and its sprite to a big rat with the objective to steal everything instead of consuming everything, this is still a work in progress and the pr was made mosly to see general feedback about it
ratboy front
ratboy ass
ratboy side
ratboy dead
the morph would become the master thief or rat thief with the objective to steal everything on the station, its abilities would stay the same but if someone provides interesting ideas they migth get implemented
image

# Wiki Documentation

new images and text for the morph page on the wiki, noting the changes in flavor text and sprites

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
wip: This is work in progress  
imageadd: added some icons and images  for the rat thief
imagedel: deleted some icons and images from the old morph 
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Why not keep both Morplhings and new Rat thief?

**Comment by cuackles** [comment]
> Why not keep both Morplhings and new Rat thief? 

It could be a possibility, but in that case i would like it to be different enough to not have to identical antags taking up space and weight of other midrounds

**Comment by Marmio64** [comment]
> > Why not keep both Morplhings and new Rat thief?
> 
> It could be a possibility, but in that case i would like it to be different enough to not have to identical antags taking up space and weight of other midrounds

you can reduce the weight of morph and add this in without changing the probability of other midrounds to spawn. Right now morph has a weight of 5 so you could lower it to 3 and give this one 2.

**Comment by ToasterBiome** [comment]
> > > Why not keep both Morplhings and new Rat thief?
> > 
> > 
> > It could be a possibility, but in that case i would like it to be different enough to not have to identical antags taking up space and weight of other midrounds
> 
> you can reduce the weight of morph and add this in without changing the probability of other midrounds to spawn. Right now morph has a weight of 5 so you could lower it to 3 and give this one 2.

give this one 4 and morph 1

**Review by Hopekz — CHANGES_REQUESTED** [review]
changelog

**Comment by Smudged** [comment]
If you want to make Master Rat Thief it's own antag, I would suggest probably making it so it can't eat people, and have a focus on simply stealing things. *Ideally, maybe it shouldn't be able to steal dead bodies, but still be able to suck people's soul to get health back.

If you want MORE depth, maybe let it transform into everything it previously stolen. But I don't know how you'd code that.

**Comment by maxion12345** [comment]
honestly? Rat morph reskin doesn't make sense to me. How can a rat change into a lightbulb? Hear me out:

It can transform into a rat, and ventcrawl in that form to go steal shit.
Ratform, vent into place, unratform, steal, repeat.

**Comment by cuackles** [comment]
> honestly? Rat morph reskin doesn't make sense to me. How can a rat change into a lightbulb? Hear me out:
> 
> It can transform into a rat, and ventcrawl in that form to go steal shit.
> Ratform, vent into place, unratform, steal, repeat.

I like that idea, i will steal it

**Pull request closed without merging**
