### PR TITLE
Station bounce radio QoL changes and tweaks

### PR DESCRIPTION
**Pull request by warface1234455**
Bounce radio extension pack: Encryption key

# Document the changes in your pull request
- You can now add encryption key to station bounce radio and remove it by altclicking on it after its panel is opened
- You can use prefix ";" , as well as ":(channel_prefix)" to send comms message while the bounce radio is in your pocket, belt or in hands.

# Wiki Documentation
- You can now add encryption key to station bounce radio and remove it by altclicking on it after its panel is opened
- You can use prefix ";" , as well as ":(channel_prefix)" to send comms message while the bounce radio is in your pocket, belt or in hands.
# Changelog

:cl:  
rscadd: You can now add encryption key to station bounce radio and remove it by altclicking on it after its panel is opened
tweak: You can now use prefix ";" , as well as ":(channel_prefix)" to send comms message while the bounce radio is in your pocket, belt or in hands.
/:cl:

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
this seems like powercreep in my opinion, what is the use case for this?

**Comment by ShoziOffical** [comment]
> this seems like powercreep in my opinion, what is the use case for this?

uh when tcomms is down? how is this powercreep please explain further

**Comment by ReddicusDragon** [comment]
This is a bad pr because the point of having these are as a means to communicate when tcomms go down as a 'backup'. Common is a general use frequency and should be used as such when tcomms goes down, being able to slap an encryption key into station bounced radios gives a buff to command and security staff when tcomms goes down, making taking out tcomms less fun for antagonists. Instead of using these and their encryption keys when tcomms goes down, how about fixing tcomms instead? It's not that difficult, you link a receiver to a bus, bus to a processor, bus to a broadcaster and set up the frequencies. I think it greatly upsets the balance.

**Comment by ShoziOffical** [comment]
> This is a bad pr because the point of having these are as a means to communicate when tcomms go down as a 'backup'. Common is a general use frequency and should be used as such when tcomms goes down, being able to slap an encryption key into station bounced radios gives a buff to command and security staff when tcomms goes down, making taking out tcomms less fun for antagonists. Instead of using these and their encryption keys when tcomms goes down, how about fixing tcomms instead? It's not that difficult, you link a receiver to a bus, bus to a processor, bus to a broadcaster and set up the frequencies. I think it greatly upsets the balance.

I don't think taking out tcomms less fun for antag gonna do anything with this, people can still use bounce to scream for help on common. Sec can use their transceiver to communicate on sec comms. Also not many players know how to fix tcomms.

**Comment by ReddicusDragon** [comment]
> > This is a bad pr because the point of having these are as a means to communicate when tcomms go down as a 'backup'. Common is a general use frequency and should be used as such when tcomms goes down, being able to slap an encryption key into station bounced radios gives a buff to command and security staff when tcomms goes down, making taking out tcomms less fun for antagonists. Instead of using these and their encryption keys when tcomms goes down, how about fixing tcomms instead? It's not that difficult, you link a receiver to a bus, bus to a processor, bus to a broadcaster and set up the frequencies. I think it greatly upsets the balance.
> 
> I don't think taking out tcomms less fun for antag gonna do anything with this, people can still use bounce to scream for help on common. Sec can use their transceiver to communicate on sec comms. Also not many players know how to fix tcomms.

There is a guide on wiki on how to fix tcomms, additionally, we have mentors who can help players set it up.

**Comment by ShoziOffical** [comment]
> There is a guide on wiki on how to fix tcomms, additionally, we have mentors who can help players set it up.

still most of the rounds players rarely fix tcomms

**Comment by ReddicusDragon** [comment]
> > There is a guide on wiki on how to fix tcomms, additionally, we have mentors who can help players set it up.
> 
> still most of the rounds players rarely fix tcomms

Then encourage them to over common. I maintain that this is not the proper way to do this.

**Comment by ShoziOffical** [comment]
> > > There is a guide on wiki on how to fix tcomms, additionally, we have mentors who can help players set it up.
> > 
> > 
> > still most of the rounds players rarely fix tcomms
> 
> Then encourage them to over common. I maintain that this is not the proper way to do this.

i am encouraging people to use bounce

**Comment by ShoziOffical** [comment]
gonna fix some bugs

**Comment by RG4ORDR** [comment]
> This is a bad pr because the point of having these are as a means to communicate when tcomms go down as a 'backup'. Common is a general use frequency and should be used as such when tcomms goes down, being able to slap an encryption key into station bounced radios gives a buff to command and security staff when tcomms goes down, making taking out tcomms less fun for antagonists. Instead of using these and their encryption keys when tcomms goes down, how about fixing tcomms instead? It's not that difficult, you link a receiver to a bus, bus to a processor, bus to a broadcaster and set up the frequencies. I think it greatly upsets the balance.

Lol what.

Sec already has their own version of a station bound radio, so this entire idea of it being a power creep or a buff to sec/command is just invalid. Being to slap encryption keys into the radios is fine. You can walk up to intercomms and set them to the correct frequency and do :I or turn their voice activation on do that route as well, which AFAIK you can tune station bounds to the same frequency too. This just adds the ability to make departmental station bound radio.

**Comment by ReddicusDragon** [comment]
> > This is a bad pr because the point of having these are as a means to communicate when tcomms go down as a 'backup'. Common is a general use frequency and should be used as such when tcomms goes down, being able to slap an encryption key into station bounced radios gives a buff to command and security staff when tcomms goes down, making taking out tcomms less fun for antagonists. Instead of using these and their encryption keys when tcomms goes down, how about fixing tcomms instead? It's not that difficult, you link a receiver to a bus, bus to a processor, bus to a broadcaster and set up the frequencies. I think it greatly upsets the balance.
> 
> Lol what.
> 
> Sec already has their own version of a station bound radio, so this entire idea of it being a power creep or a buff to sec/command is just invalid. Being to slap encryption keys into the radios is fine. You can walk up to intercomms and set them to the correct frequency and do :I or turn their voice activation on do that route as well, which AFAIK you can tune station bounds to the same frequency too. This just adds the ability to make departmental station bound radio.

I still feel like this is wrong, but if it gets merged it gets merged

**Comment by CMOisLing** [comment]
Make it so the key overrides common. Then radios are still at a major disadvantage but you can still have department radios.

**Comment by ReddicusDragon** [comment]
> Make it so the key overrides common. Then radios are still at a major disadvantage but you can still have department radios.

I am amenable to this idea

**Comment by warface1234455** [comment]
> Make it so the key overrides common. Then radios are still at a major disadvantage but you can still have department radios.

instead of this, i will just make it not accept command or sec encryption

**Comment by MajManatee** [comment]
Why a multitool when headsets use a screwdriver?

**Comment by ShoziOffical** [comment]
> Why a multitool when headsets use a screwdriver?

~~because screwdriver is already used for something else (to open panel) headset now uses same proc as bounce radio~~
you know what ill change it back, idk why i changed it smh

**Comment by ReddicusDragon** [comment]
> > Make it so the key overrides common. Then radios are still at a major disadvantage but you can still have department radios.
> 
> 
> 
> This is not going to change anything, people can still popout their encryption key and switch channel
> 
> 
> 
> instead of this, i will just make it not receive command or sec frequency

This is NOT the way, I really enjoyed the one idea to make it so people can't use common while using an encryption key

**Comment by ShoziOffical** [comment]
> > > Make it so the key overrides common. Then radios are still at a major disadvantage but you can still have department radios.
> > 
> > 
> > This is not going to change anything, people can still popout their encryption key and switch channel
> > instead of this, i will just make it not receive command or sec frequency
> 
> This is NOT the way, I really enjoyed the one idea to make it so people can't use common while using an encryption key

that is dumb

**Comment by ReddicusDragon** [comment]
> > > > Make it so the key overrides common. Then radios are still at a major disadvantage but you can still have department radios.
> 
> > > 
> 
> > > 
> 
> > > This is not going to change anything, people can still popout their encryption key and switch channel
> 
> > > instead of this, i will just make it not receive command or sec frequency
> 
> > 
> 
> > This is NOT the way, I really enjoyed the one idea to make it so people can't use common while using an encryption key
> 
> 
> 
> that is dumb

How is that dumb?

**Comment by ShoziOffical** [comment]
> How is that dumb?

doesnt make any sense also and 
> people can still popout their encryption key and switch channel

**Comment by ReddicusDragon** [comment]
> > How is that dumb?
> 
> 
> 
> doesnt make any sense
> 
> 

In what way?

**Comment by ShoziOffical** [comment]
> > > How is that dumb?
> > 
> > 
> > doesnt make any sense
> 
> In what way?

Encryption keys are used for adding additional channel not overwriting it

**Comment by ReddicusDragon** [comment]
> > > > How is that dumb?
> 
> > > 
> 
> > > 
> 
> > > doesnt make any sense
> 
> > 
> 
> > In what way?
> 
> 
> 
> Encryption keys are used for adding additional channel not overwriting it

Yes, for HEADSETS. Station radios are not headsets 🙂

**Comment by ShoziOffical** [comment]
> Yes, for HEADSETS. Station radios are not headsets 🙂

Headsets are radios subtype

**Comment by ReddicusDragon** [comment]
Headsets Are headsets, station bounced radios are station bounced radios

**Comment by ReddicusDragon** [comment]
You edited your message after I replied rip

**Comment by ShoziOffical** [comment]
> You edited your message after I replied rip

no i did it before

**Comment by ShoziOffical** [comment]
wait why label java.. CRAP

**Comment by CMOisLing** [comment]
Bounced radios are stupid primative tech that doesnt use Bluespace, SAD! Single channel operation should be its limiting factor.

**Comment by ShoziOffical** [comment]
> Bounced radios are stupid primative tech that doesnt use Bluespace, SAD! Single channel operation should be its limiting factor.

Do you even know what bluespace is? It doesn't do anything with this, radios use network frequency to transmit message across the network

**Comment by CMOisLing** [comment]
> Do you even know what bluespace is? It doesn't do anything with this, radios use network frequency to transmit message across the network

My B I thought tcomms transmitters were called "bluespace transmitters"

**Comment by warface1234455** [comment]
> > Do you even know what bluespace is? It doesn't do anything with this, radios use network frequency to transmit message across the network
> 
> My B I thought tcomms transmitters were called "bluespace transmitters"

What. It's called "broadcaster"

**Comment by ShoziOffical** [comment]
> > > Do you even know what bluespace is? It doesn't do anything with this, radios use network frequency to transmit message across the network
> > 
> > 
> > My B I thought tcomms transmitters were called "bluespace transmitters"

 What. It's called "broadcaster" and has nothing to do with bluespace

**Comment by ReddicusDragon** [comment]
The way I view it is like this. I'm against this PR in general because at this point it completely invalidates tcomms as a concept. There's no reason a station bounced radio would be able to act as a departmental radio. Or accept encryption keys in general. My reasoning here is because each tcomms channel at bare minimum requires a subspace receiver (which station bounced radios can act as), a bus (which station bounced radios can't/shouldn't be able to act as, as that's basic common sense), a processor (which station bounced radios can act as for processing common) and a subspace broadcaster (which station bounced radios act as because a station bounced radio has a tx + rx). A station bounced radio would not be able to act as a bus in regards to tcomms.

**Comment by ShoziOffical** [comment]
> The way I view it is like this. I'm against this PR in general because at this point it completely invalidates tcomms as a concept. There's no reason a station bounced radio would be able to act as a departmental radio. Or accept encryption keys in general. My reasoning here is because each tcomms channel at bare minimum requires a subspace receiver (which station bounced radios can act as), a bus (which station bounced radios can't/shouldn't be able to act as, as that's basic common sense), a processor (which station bounced radios can act as for processing common) and a subspace broadcaster (which station bounced radios act as because a station bounced radio has a tx + rx). A station bounced radio would not be able to act as a bus in regards to tcomms.

You know that only people with bounce radio can hear each other during comms blackout right

**Comment by ShoziOffical** [comment]
Encryption or not it's still the same shit

**Comment by ReddicusDragon** [comment]
> > The way I view it is like this. I'm against this PR in general because at this point it completely invalidates tcomms as a concept. There's no reason a station bounced radio would be able to act as a departmental radio. Or accept encryption keys in general. My reasoning here is because each tcomms channel at bare minimum requires a subspace receiver (which station bounced radios can act as), a bus (which station bounced radios can't/shouldn't be able to act as, as that's basic common sense), a processor (which station bounced radios can act as for processing common) and a subspace broadcaster (which station bounced radios act as because a station bounced radio has a tx + rx). A station bounced radio would not be able to act as a bus in regards to tcomms.
> 
> 
> 
> You know that only people with bounce radio can hear each other during comms blackout right

Yes I'm well aware of this, but what's stopping people from powergaming and using these instead of their headsets?

**Comment by ShoziOffical** [comment]
> Yes I'm well aware of this, but what's stopping people from powergaming and using these instead of their headsets?

What are you gonna powergaming with the station bounce radio lmao

**Comment by ReddicusDragon** [comment]
> 
> 
> > Yes I'm well aware of this, but what's stopping people from powergaming and using these instead of their headsets?
> 
> 
> 
> What are you gonna powergaming with the station bounce radio lmao

Shove your headset encryption key in it and exclusively use it because "oh the comms might go out I can still talk to my engineer friends now if it does"

**Comment by ShoziOffical** [comment]
> > > Yes I'm well aware of this, but what's stopping people from powergaming and using these instead of their headsets?
> > 
> > 
> > What are you gonna powergaming with the station bounce radio lmao
> 
> Shove your headset encryption key in it and exclusively use it because "oh the comms might go out I can still talk to my engineer friends now if it does"

Hey you know common exists too, and they can set frequency to talk privately

**Comment by ShoziOffical** [comment]
And how is that powergaming? That is literally communication

**Comment by ShoziOffical** [comment]
**Powergaming** is the the act of using an in-game mechanic, any external information, or a roleplay concept to favor their own character or story, and give them an unfair or unrealistic advantage. Powergaming can take several forms, but it is generally rooted in “playing to win” or a focus on playing the game, instead of honoring the creative roleplay. Playing your character should always be more important than playing the game.
I think you misunderstood what is powergaming here

**Comment by ReddicusDragon** [comment]
> > > > Yes I'm well aware of this, but what's stopping people from powergaming and using these instead of their headsets?
> 
> > > 
> 
> > > 
> 
> > > What are you gonna powergaming with the station bounce radio lmao
> 
> > 
> 
> > Shove your headset encryption key in it and exclusively use it because "oh the comms might go out I can still talk to my engineer friends now if it does"
> 
> 
> 
> Hey you know common exists too, and they can set frequency to talk privately

Being able to chat on common is a non issue because it throws departments into disarray. You can't collaborate with departments easily over common. By allowing easy interdepartmental communication during comms going down, you give a disadvantage to antagonists who rely on the chaos of comms going down and the lack of departments being easily able to communicate to accomplish their goals.

**Comment by ShoziOffical** [comment]
> Being able to chat on common is a non issue because it throws departments into disarray. You can't collaborate with departments easily over common. By allowing easy interdepartmental communication during comms going down, you give a disadvantage to antagonists who rely on the chaos of comms going down and the lack of departments being easily able to communicate to accomplish their goals.

Frequency exists

**Comment by ShoziOffical** [comment]
Antagonist still be affected by common frequency

**Comment by ReddicusDragon** [comment]
> Antagonist still be affected by common frequency 

Not to the extent they would be if taking down comms had no effect at all.

**Comment by ShoziOffical** [comment]
> > Antagonist still be affected by common frequency
> 
> Not to the extent they would be if taking down comms had no effect at all.

At this point, you literally want to remove bounce radio, is that what you meant

**Comment by ReddicusDragon** [comment]
> > > Antagonist still be affected by common frequency
> 
> > 
> 
> > Not to the extent they would be if taking down comms had no effect at all.
> 
> 
> 
> At this point, you literally want to remove bounce radio, is that what you meant

No. I like what you did for the QoL tweaks but I fundamentally disagree on the inclusion of the ability to give them encryption keys.

**Comment by ShoziOffical** [comment]
> No. I like what you did for the QoL tweaks but I fundamentally disagree on the inclusion of the ability to give them encryption keys.

Honestly i don't know how people gonna take advantage with this but i did this pr just to make a failsafe setup for SM

Don't think this will affect gameplay much, because its just a bounce radio, people whether to get it or not to communicate with the other person with the same network, usually in space or during tcomms blackout

**Comment by ReddicusDragon** [comment]
> 
> 
> > No. I like what you did for the QoL tweaks but I fundamentally disagree on the inclusion of the ability to give them encryption keys.
> 
> 
> 
> Honestly i don't know how people gonna take advantage with this but i did this pr just to make a failsafe setup for SM

A failsafe setup for the supermatter saying it's delaminated?

**Comment by ReddicusDragon** [comment]
Er, delaminating

**Comment by ShoziOffical** [comment]
> A failsafe setup for the supermatter saying it's delaminated?

yeah, basically the bounce radio will pickup the message from sm and will send it to a voice activator triggering signaler then activate failsafe procedure

**Comment by ReddicusDragon** [comment]
If that's all you want to do you might be able to get away with changing the SM alert radio to broadcast on common if subspace is unavailable. If that's something you wanna explore I'll be available in 5 hours, I'd love to help out with something like that it sounds really intelligent

**Comment by ShoziOffical** [comment]
> If that's all you want to do you might be able to get away with changing the SM alert radio to broadcast on common if subspace is unavailable. If that's something you wanna explore I'll be available in 5 hours, I'd love to help out with something like that it sounds really intelligent

Uh i don't want to touch sm alert shit, its already broadcast on common when below 20%, but i want here to catch the message while it broadcasts in engi comms above 20%

**Comment by ReddicusDragon** [comment]
> > If that's all you want to do you might be able to get away with changing the SM alert radio to broadcast on common if subspace is unavailable. If that's something you wanna explore I'll be available in 5 hours, I'd love to help out with something like that it sounds really intelligent
> 
> 
> 
> Uh i don't want to touch sm alert shit, its already broadcast on common when below 20%, but i want here to catch the message while it broadcasts in engi comms above 20%
> 
> 

I see. It'd be funny if we allowed headsets to be attached to assemblies lmao

**Comment by Moltijoe** [comment]
Problem with fixing tcomms is that its complicated enough that when it gets damaged, it's already mid-round or later so it's not worth the time to fix
More often that not, someone just sets up a new tcomms setup elsewhere that just fixes common and calls it a day.

**Comment by ShoziOffical** [comment]
> Problem with fixing tcomms is that its complicated enough that when it gets damaged, it's already mid-round or later so it's not worth the time to fix More often that not, someone just sets up a new tcomms setup elsewhere that just fixes common and calls it a day.

fixing tcomms is so easy ahhhh

**Comment by Moltijoe** [comment]
> fixing tcomms is so easy ahhhh

requires people to learn it and then actually do it. 
It's basically limited to engineers and maybe scientists otherwise it's powergaming too.
scientists are usually too self-centered to do it.
engineers are either the antag or already dead and stripped by the antag for their access/tools.

**Comment by ReddicusDragon** [comment]
> > fixing tcomms is so easy ahhhh
> 
> 
> 
> requires people to learn it and then actually do it. 
> 
> It's basically limited to engineers and maybe scientists otherwise it's powergaming too.
> 
> scientists are usually too self-centered to do it.
> 
> engineers are either the antag or already dead and stripped by the antag for their access/tools.

It is a net negative to remove departmental interaction. I'll literally apply for mentor just to answer tcomms questions

**Comment by ReddicusDragon** [comment]
still think this is a bad way to do it, but I can't think of an alternative. Let me know when you do the funny haha voice-activated SM vent

**Comment by ShoziOffical** [comment]
Not really bad

> still think this is a bad way to do it, but I can't think of an alternative. Let me know when you do the funny haha voice-activated SM vent

This is the only way to do it, since it transmits on coms

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Eh, was against this, but lets see how it works

**Comment by ShoziOffical** [comment]
> Eh, was against this, but lets see how it works

It will just be the same thing, won't affect much to gameplay

**Comment by Rdrazga** [comment]
You may want to check what this is doing to headset radio uplinks, since someone just had a problem where they can't put TC into their uplink due to it being closed, returning this line: 'You cannot put anything in when the service radio headset's panel is closed!' and radio headsets can't be opened...

**Comment by ShoziOffical** [comment]
> You may want to check what this is doing to headset radio uplinks, since someone just had a problem where they can't put TC into their uplink due to it being closed, returning this line: 'You cannot put anything in when the service radio headset's panel is closed!' and radio headsets can't be opened...

Alr

**Pull request merged**
