### PR TITLE
Makes EMPs disable robotic limbs and cause stamina damage instead of completely paralyzing you for having one

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Yes, it still does burn damage on top of this. It just won't fully paralyze you anymore, though it will still knock you down if you have robotic legs.

# Changelog

:cl:  
tweak: EMPs disable robotic limbs and cause stamina damage instead of paralyzing you
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
maybe distribute it across all robotic limbs if you can? (mainly for ipcs)

**Comment by iamthesilly** [comment]
> maybe distribute it across all robotic limbs if you can? (mainly for ipcs)

i did

**Comment by iamthesilly** [comment]
i may have completely broken my pr

**Comment by iamthesilly** [comment]
nevermind

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
invisible conflicts.

**Comment by JamieD1** [comment]
Still have invisible conflcits

**Pull request merged**
