### PR TITLE
Fixes the Dota suit not actually playing sounds properly.

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Document the changes in your pull request

Fixes the Dota suit not actually playing sounds properly.

# Changelog

:cl:  BurgerBB
bugfix: Fixes the Dota suit not actually playing sounds properly.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Feature Freeze

**Comment by BurgerLUA** [comment]
I got PERMISSION.

**Comment by BurgerLUA** [comment]
image

**Comment by ynot01** [comment]
works

**Review by ynot01 — APPROVED** [review]

**Comment by BurgerLUA** [comment]
> works

look, the only reason it didn't work last time is because of someone reviewing my code, and me not reviewing their code that they submitted smh

**Review by ynot01 — APPROVED** [review]

**Pull request merged**
