### PR TITLE
gives bullshit russian ruin a pulse pistol at the end

### PR DESCRIPTION
**Pull request by boodaliboo**
the ruin is incredibly bullshit for the bad loot you get at the end
#### Changelog

:cl:  
rscadd: Added pulse pistl,l
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
image
heres the ruin actually look at it

**Comment by Hopekz** [comment]
IMO this is a bad idea because pulse pistols and rifles are not balanced at the moment.
They actually feel like debug admin weapons vs weapons that are meant to be acquired in-game. They even delete walls with 1 shot

**Comment by Mesalikepie** [comment]
This is a shitpost

**Comment by athena413** [comment]
pulse guns are literally admin weapons

**Comment by Hopekz** [comment]
> pulse guns are literally admin weapons

I think the main miscommunication with them being admin weapons was that half our ERT's had these rifles for some reason before my rework for them.

**Comment by patpol4** [comment]
lmao

**Pull request closed without merging**
