### PR TITLE
Disables midround OOC

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request
Midround OOC is rarely used except to ick ock either intentionally or accidentally.

# Changelog

:cl:  
rscdel: Removed midround ooc
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
I see your thumbs down, but someone tell me one good reason to leave this enabled.

**Comment by solwashere** [comment]
Bad PR, how else will I tell my discordless yoggers good night?
It's factually wrong to assume that it's only used for ick ocking only as I've seen it used quite a bit as a small means of general discussion several times, and I don't think it can possibly be that hard to OOC mute someone who's ick ocking or being a shit

**Comment by adamsong** [comment]
> I don't think it can possibly be that hard to OOC mute someone who's ick ocking or being a shit

Its not hard, but a single OOC message can do irreparable harm to a round.

**Comment by solwashere** [comment]
> > I don't think it can possibly be that hard to OOC mute someone who's ick ocking or being a shit
> 
> Its not hard, but a single OOC message can do irreparable harm to a round.

It is fairly noticeable whenever someone decides to abuse info that they acquired OOC
If someone says "oh great I'm dead in science maints" then it's safe to assume that anyone who stops what they're doing and goes to sci maints is abusing said information
Also this information can be just as easily said in the discord server, and I've seen it happen before
Anyone with the ability to spread information or access to the discord can ick ock fairly easily, this is like trying to cover one small hole on a sinking ship with 20
And arguably it's easier to enforce ick ock rules in OOC rather than anywhere else

**Comment by adamsong** [comment]
If someone says in ooc "bobby tables is the last headrev in the library" then I have to second guess everyone who goes to the library, or who thinks bobby tables is a rev/headrev. Its possible they knew from something else, etc, should I sit and boink every member of sec who goes to the library in the next 20 minutes?

**Comment by Cartlord** [comment]
Midround O.O.C. is fun and a good way for new players (who, let's face it, won't read all the fucking tabs in the top-right) to ask for simple help (e.g. "how unbuckle") in ways that won't disrupt the round too much
You ask us to provide one good reason for it to stay, I ask you to provide one good reason for it to be REMOVED that isn't just "sometimes people use it for bad things" - which is an admin issue.

**Comment by Marmio64** [comment]
Could make ooc messages delayed and reviewable by admins

**Comment by JamieD1** [comment]
No

**Comment by adamsong** [comment]
> No

Thank you for your thoughtful response

**Comment by SomeguyManperson** [comment]
> Midround OOC is rarely used except to ick ock either intentionally or accidentally.

erm... source? 🤓

**Comment by Therandomhoboo** [comment]
Someone speed merge this for the bants

**Comment by MajManatee** [comment]
inadequate rationale

**Comment by N3D6** [comment]
what the fuck this is the worst I’ve ever seen

**Comment by N3D6** [comment]
Lmao this PR sucks and is a good example of senior devs being extremely out of touch. Instead of disabling OOC, how about you do your job as an admin, and ban those who ick ock intentionally instead of punishing the entire server? I am fed up with these code solutions to obvious admin issues

**Comment by Moja10** [comment]
while I agree some shit like "what's this R Above my head" can fuck up a round, I think that OOC is generally not a problem enough to kill it

**Comment by ToasterBiome** [comment]
Not worth it currently

**Pull request closed without merging**
