### PR TITLE
Revert "Should allow you to drag-click pulled objects onto weeds"

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Reverts yogstation13/Yogstation#11836
seems to break shit like ever being able to touch weeds

### CODE REVIEW

**Comment by Bibby0110** [comment]
hmm that's weird. Should just pass the click onto the turf beneath it in addition to the weed. Parent call should probably be moved to the top but idk why this wouldn't have worked.

**Comment by alexkar598** [comment]
likely click cooldown

**Comment by Bibby0110** [comment]
> likely click cooldown

sounds about right

**Comment by Bibby0110** [comment]
Should probably be closed unless the other PR still didn’t fix it

**Pull request closed without merging**
