### PR TITLE
im a dumbass (actually ports autotomy because i somehow managed to forget in my pr that said it added it)

### PR DESCRIPTION
**Pull request by boodaliboo**
im just going to copy and paste the original prs description "Adds a new mutation to genetics: Autotomy. This allows a creature to shed a limb on command, mostly when in danger to distract predators." https://github.com/tgstation/tgstation/pull/45988
#### Changelog

:cl:  
rscadd: Added a new genetics power
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Genetics power creep.

**Comment by boodaliboo** [comment]
Everything power creep robotics power creep nanites powercreep xeno power creep virology power creep (technically this makes genetics harder because the more mutations the harder it is to get the specific one you want

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Unneeded icon changes, sort that out

**Comment by boodaliboo** [comment]
what its for the ability it uses its needed

**Comment by alexkar598** [comment]
You need spell card to use the ability?

**Comment by boodaliboo** [comment]
no i need the autonomy icon for activation of it

**Comment by boodaliboo** [comment]
oh i see im a dumbass ill change it

**Comment by AsV9** [comment]
You literally did nothing in that commit. How the fuck do you manage?

**Comment by boodaliboo** [comment]
The icon change does absolutely nothing what so ever as it’s identical to our current one if you want me to remove it from this commit I can do that

**Comment by AsV9** [comment]
I want you to remove the unnecessary icon changes.

**Comment by boodaliboo** [comment]
fixed it

**Comment by alexkar598** [comment]
You didnt

**Comment by boodaliboo** [comment]
but i litterally deleted the duplicate spell card

**Comment by AsV9** [comment]
image

**Pull request closed without merging**
