### PR TITLE
Replays 2.0

### PR DESCRIPTION
**Pull request by monster860**
# Document the changes in your pull request

This is the new and improved replay system! Including such features as, animations, sounds, vis_contents (that means doors and consoles and apcs and shit show up correctly now), and more!

[Take a look for yourself though!](https://replays.yogstation.net/?demo_url=https://cdn.jsdelivr.net/gh/yogstation13/demo-viewer@cd717a13026e83ff28e0bb02a69a3bb6bdc18c41/cppdemotest.xz#258;10.50;174.50;2;monster860;0.5)

image

Demo writer: https://github.com/yogstation13/demo-writer
Demo viewer: https://github.com/yogstation13/demo-viewer

:cl: monster860
add: Replays 2.0
/:cl:

### CODE REVIEW

**Comment by LazennG** [comment]
yiiking out rn

**Comment by Necrosium** [comment]
Important question: will this one lag like the one 2 years ago?

**Comment by bruhlookatthisdood** [comment]
amazing work
cant wait to use this!

**Comment by monster860** [comment]
> Important question: will this one lag like the one 2 years ago?

Nope, it's in c++, runs much faster

**Comment by JamieD1** [comment]
Checking with Monster

**Comment by LazennG** [comment]
for clarity's sake, how would you see what's going on in unlit areas like maint or lavaland?

**Comment by monster860** [comment]
I'll have to add a toggle to the replay viewer somewhere.

**Comment by bruhlookatthisdood** [comment]
It'd be nice if we had a way of seeing who was an antagonist and who wasnt (maybe it already is i havent looked at it that closely yet)

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
