### PR TITLE
Makes Borg Exoskeletons no longer fit in bags

### PR DESCRIPTION
**Pull request by jcatjmeow**
#### Changelog

:cl:  
tweak: Borg exoskeletons no longer fit in bags
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Thanks ling

**Comment by zxmongoose** [comment]
Why

**Comment by jcatjmeow** [comment]
because you can't fit a borg in your bag...so why can you fit several borg shells in your bag? Doesn't make a whole lot of sense.

**Comment by jcatjmeow** [comment]
Thanks nich <3

**Pull request merged**
