### PR TITLE
Gives icemeta a plasmariver so that chaplain no longer "buries" bodies by slamming them into a wall 2 feet infront of the mass driver

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Previously, on a yogstation near you:

https://github.com/yogstation13/Yogstation/assets/42524344/9407fd86-fd55-4ade-86f2-a92e8057c173

Now, Icemeta. New and improved:

https://github.com/yogstation13/Yogstation/assets/42524344/0bac14c0-d3de-414a-a64d-bf7616c18622

image

# Why is this good for the game?
plasma river is fucking cool and also chaplain now has a way to properly dispose of bodies

# Wiki Documentation
Icemeta map may need changing

# Changelog
:cl:  
mapping: Chaplain no longer throws people into snow on Icemeta
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
imo just setting wise a plasma river is out of place on the station map because in the current lore the whole point of the station existing is to mine plasma.
If there's a whole river of plasma on the surface like that there would be no point in having a mining operation in the first place because they'd be able to just pump it out of that river.

Also might confuse people that don't know better when they need plasma for something so they think they can go to the plasma river right outside to somehow extract it from there.

**Comment by azzzertyy** [comment]
> imo just setting wise a plasma river is out of place on the station map because in the current lore the whole point of the station existing is to mine plasma. If there's a whole river of plasma on the surface like that there would be no point in having a mining operation in the first place because they'd be able to just pump it out of that river.
> 
> Also might confuse people that don't know better when they need plasma for something so they think they can go to the plasma river right outside to somehow extract it from there.

they should be able to use a beaker on it to get liquid plasma that would make sense
but i dont agree on the first point at all, the station was put there for plasma research, and theres a plasma river there. maybe theres just LESS plasma on the surface.

**Comment by SomeguyManperson** [comment]
> imo just setting wise a plasma river is out of place on the station map because in the current lore the whole point of the station existing is to mine plasma. If there's a whole river of plasma on the surface like that there would be no point in having a mining operation in the first place because they'd be able to just pump it out of that river.
> 
> Also might confuse people that don't know better when they need plasma for something so they think they can go to the plasma river right outside to somehow extract it from there.

map already has plasma river spawns everywhere on the other two z-levels at least so this doesn't particularly change much

Assuming the plasma river is a normal one you can totally just scoop plasma reagent out of it

**Comment by neeshacark** [comment]
wicked sick.

**Review by neeshacark — APPROVED** [review]

**Comment by hairykidney** [comment]
could of probably been a hole to the bottom layer to help with lore, and seems like a even better solution for dumping bodies. Fits in the spirit of the original where you change Z-levels. Probably would need a more convenient ladder though

**Pull request merged**
