### PR TITLE
Traitors can no longer deflect energy projectiles with the desword

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Only nukies can deflect energy projectiles because they are true masters of the sord

The desword is getting removed if this isn't merged I don't make the rules

# Changelog

:cl:  
tweak: Only nukies may utilize the double-bladed energy sword to deflect energy projectiles now
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
it definitely needs a price decrease if half of it's appeal is getting removed for traitors

**Comment by ToasterBiome** [comment]
> The desword is getting removed if this isn't merged I don't make the rules

says who

**Comment by ynot01** [comment]
> says who

the shadow council

**Comment by MajManatee** [comment]
but why is this a good change (it isnt)

**Comment by Moja10** [comment]
would rather have reflection than 300 morbillion damage, security can deal with a traitor who is reflecting shit but not also doing 4 hit kills in the process

**Comment by Moltijoe** [comment]
Ynot knows why it's denied, but for everyone else:
>This isn't the way we should go about handling the desword being a problem

**Pull request closed without merging**
