### PR TITLE
Removes extract sting

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
Instead of clicking 8 people on the shuttle, changelings now have to absorb 3 to 5 of them.
https://forums.yogstation.net/index.php?threads/change-ling.17348/
:cl:  
rscdel: Changelings no longer have the extraction sting.
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
Goon lings when lol

**Comment by Oakboscage** [comment]
Oh fuck yeah

**Comment by Amelia0010** [comment]
Gonna merge this tomorrow if noone has any actual complaints :)

**Comment by Moja10** [comment]
If you merge this, don't merge your adrenaline PR because now lings will essentially forced to go loud.

**Comment by Amelia0010** [comment]
>If you merge this, don't merge your adrenaline PR because now lings will essentially forced to go loud.

They don't though? Lings have both mute and blind stings, not to mention the armblade and the weird fucking tentacle thing. Their shtick should be to be somewhat stealthy and eliminate people, not to openly fight groups of people. They still have a large amount of tools for this exact purpose, and changing the adrenaline sacs encourages them to use it to get out of combat, rather than as a boost during combat.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Or they could play like a sane person and go stealthy?

**Pull request merged**
