### PR TITLE
Voice analyzer starts on exclusive

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
tweak: Voice analyzer no longer starts on inclusive so it won't detonate on hearing anything automatically
/:cl:

### CODE REVIEW

**Comment by Altoids1** [comment]
Did you actually have to swap around these things everywhere, or can you just change the default mode?

**Comment by SomeguyManperson** [comment]
changing the default would look a bit sloppy but it'd work I guess

**Comment by HomocidlePancakes** [comment]
I don’t get it

**Comment by SomeguyManperson** [comment]
The analyzer currently starts on inclusive scanning, which means if the activating phrase shows up at all it'll activate. The base phrase is literally nothing meaning the thing will pulse if anything is said next to it if there's no code set. tldr if you don't touch the analyzer at all before putting it on a grenade it'll explode if it hears anything, this should stop that from being the default behavior

**Comment by HomocidlePancakes** [comment]
Oh wow. This is pure ided

**Pull request merged**
