### PR TITLE
Ports "Adds a camera viewing app, SecurEye, for Laptops and Modular Consoles" #54225 and adds a version for mining base cams

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Ported [SecurEye](https://github.com/tgstation/tgstation/pull/54225) from TG and added OverWatch, an uncreatively named version of SecurEye that only shows mining base cams but also takes less space and only requires mining access. One issue that I have not been able to fix is with is bodycams as they only show a black screen, though other than that it works fine.

Capture

# Wiki Documentation

Nothing will need to be changed. 

# Changelog

:cl:  zxaber
rscadd: Adds a camera viewing app, SecurEye, available for download on laptops and modular consoles to those that have security access.
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Feels a bit op. @SomeguyManperson

**Comment by Bibby0110** [comment]
Feels OP for laptops, plus fix bodycams

**Review by Bibby0110 — DISMISSED** [review]
bodycam fix

**Comment by nmajask** [comment]
> Feels OP for laptops, plus fix bodycams

Ill look at the bodycams when I get home. As for it being overpowered, its an app that requires sec to go out of their way to get a modular laptop to use and even then it still requires NTnet and probably wont be used constantly due to the slowdown from carrying an open laptop. In addition, TG has had them in their code base for over a year and it has not been reverted (as far as I can tell). This was the response the creator of the original PR said to a similar question brought up on the original PR.
image

**Comment by nmajask** [comment]
> bodycam fix

Done

**Comment by JamieD1** [comment]
Fuck it, if its op we can take it out.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
