### PR TITLE
Removes tricorder for having bad code

### PR DESCRIPTION
**Pull request by alexkar598**
I have no problems against tricorders as a feature but as it stands it involves heavy amount of duplicated code which is terrible practice.

Left the sprite in tho

gtfo with your "improve dont remove"

Closes: #6550

#### Changelog

:cl:   
rscdel: Removed tricorders for having terrible code  
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
yeah ok pretty sure all of tricoder code could've been done under 20 < lines by just using the already existing fucking procs

**Comment by yacabo** [comment]
Pure procs doesn't work, the gas analyzer function doesn't have a proc while the medical scanner had to be gutted to prevent it from becoming "medical scanner with extra features".

**Comment by Time-Green** [comment]
Then make the gas scanner a global, and add a "restricted" parameter to the medical scan

**Comment by Readystorm546** [comment]
"C O P Y C O D E B A D"
-Like two people

**Comment by alexkar598** [comment]
"C O P Y C O D E B A D"
-The people who have to review your shitty PRs

**Comment by Readystorm546** [comment]
Someone is salty geeze. Its not even my PR

**Comment by yacabo** [comment]
I redid the Tricorder code, PR's here:
https://github.com/yogstation13/Yogstation-TG/pull/6564

**Comment by alexkar598** [comment]
Closing this in favour of #6564

**Pull request closed without merging**
