### PR TITLE
Adds a new job : Artist

### PR DESCRIPTION
**Pull request by Djiq**
### Intent of your Pull Request

Adds a new job role as per bounty i found on yogstation forum.

I will be blunt here i did it for money.

here is the thread:
https://forums.yogstation.net/threads/15-add-a-new-assistant-tourist-tier-role-of-artist-ss13-server.22274/

reason for why he wants the job added with the guy that made the bounty, i personally have no opinion on the subject whatsoever.

#### Changelog
:cl:  
rscadd: Added a new Tourist/Assistant tier role: Artist! He spawns with a few art supplies already in his backpack.
rscadd: Added a new suit for the artist: Post-modern suit, exclusive to artist spawn
rscadd: Added a new scard for the artist: Post-modern scard exclusive to artist spawn
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
I really feel as if the artist should have some sort of personal study, his room so to speak. It should be pretty easy to convert the art storages into small studies that feel like a room for a person instead of just storage.

**Comment by Djiq** [comment]
> I really feel as if the artist should have some sort of personal study, his room so to speak. It should be pretty easy to convert the art storages into small studies that feel like a room for a person instead of just storage.

i mean art storage kind of _is_ his small office. I guess i could rename the area to Art Coven or something like that.

**Comment by MegaEmpirical** [comment]
Part of the bounty was improving the room.

**Comment by Djiq** [comment]
> Part of the bounty was improving the room.

will do so then

**Review by Partheo — APPROVED** [review]
Nice sprites.

**Review by Amelia0010 — APPROVED** [review]
Code is fine, awaiting map and merge conflict resolution

**Comment by Djiq** [comment]
maps have been updated.

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
@EdgeLordExe can you fix the line endings on  code/__DEFINES/jobs.dm

**Review by patpol4 — CHANGES_REQUESTED** [review]
Not gonna lie, this was pretty low effort but technically fine since you made it look not as bland.
opera_ZuvYydxSmV
Some technical details and it should be good to go : 
1. Please move the busts so they don't clip through the window like this on every map
chrome_fm0qNSiEHY
2. Poster offsets for x and y should be always 32
3. For Deltastation, add firelocks for the door, replace the inner windows that dont touch space with shutterless versions, add proper areas for the outside lattices. Add a vent, scrubber, and air alarm.
4. For delta and meta, fix apc names.
5. Air alarm for Eclipse

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Line Endings

**Comment by maxion12345** [comment]
this feels more like something you'd just play as assistant to do, especially with the no-access paint room in fitness and art storage being the same. Not sure why it needs an entirely separate job. Does this mean that assistants that do art are now technically power gaming, because they aren't artists and wouldn't have the skills of one

**Comment by Djiq** [comment]
@JamieD1 the line endings look fine there

**Comment by UselessTheremin** [comment]
yeah this seems just like assistant and nothing else really, if i want to do art i go service borg or drone. maybe the artist could have an infinite use spraycan? idk, just a thought.

**Review by patpol4 — CHANGES_REQUESTED** [review]
On delta, fix lightswitch in glass
chrome_Nxg5JtaYJe

you put 3 firelocks here, should be 2, also switch the inner windows to not reinforced(should have told you before sorry), and remove the firelocks from under the windows, only keep the 2 in the airlock 
chrome_27gvRPMbJF

Don't put vents on the same tile as apc nodes as it obscures them
chrome_d4VZnmcknT

Do those changes and this should be good to go mapwise after you fix the conflict

**Review by patpol4 — APPROVED** [review]
Maps are fine

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
@EdgeLordExe Contact Moja or Xantam or myself on Discord for bounty.

**Pull request merged**
