### PR TITLE
Adds royal skeleton templars and royal spear

### PR DESCRIPTION
**Pull request by sam0oneau**
Adds royal skeleton templars to the game.
These mobs have a 1% chance of spawning instead of a normal undead templar.
These mobs are significantly stronger but drop two royal spears.
Royal spears are powerful melee weapons that can be wielded in two hands. 
When thrown they deal reasonable brute damage but break on impact.
Ashwalkers cannot touch a royal spear.

Royal guard

Spear 5

#### Changelog

:cl:  
Added royal skeleton templar
Added royal spear
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
Wasn't this supposed to be a clock cult spear?

**Comment by Readystorm546** [comment]
> Wasn't this supposed to be a clock cult spear?

No

**Comment by Xoxeyos** [comment]
Add the effect from genetics, the one with the orange yellow sphere around the avatar, that way it'll make them truly holy.

**Comment by neeshacark** [comment]
not being able to be used by ashwalkers is sad. should be only whoever killed the templar can use it, if thats possible.

**Comment by alexkar598** [comment]
Im meh on giving miners even more insta kill weapons.

**Pull request closed without merging**
