### PR TITLE
Revolution now has a timelimit

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

Revolution is now on a timer, with the end result being nuked if either side doesn't defeat each other in the time frame. The nuke timer starts after 40 minutes into the round, and explodes after 6 minutes. Also, no one wins if the nuke goes off, for it is a centcom victory.

#### Changelog

:cl:  
rscadd: Revolution is now timed, the nuke timer starts at 40 minutes, and explodes after 6 minutes. the gamemode will announce that it's a revolution after 30 minutes.

/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Forgot about the shuttle lock, whoops.

**Comment by Sir-Lagsalot** [comment]
🍿

**Comment by Bibby0110** [comment]
You just modified speedy revolution, nice

**Comment by MegaEmpirical** [comment]
I'm fine with Revs as it is now, not a fan of this. Especially with such a short timer.

**Comment by Bibby0110** [comment]
Indeed, not a fan. Revs needs a soft-end when it takes too long, not just ending the round.

**Comment by Alexandria404** [comment]
Not every round is a rush not every player rushes it, forcing them to is questionable at best.

**Comment by Chuggachar** [comment]
This is very much not fun.

**Comment by neeshacark** [comment]
This is literally just speedyrevs but now its every round, and im pretty sure speedyrevs isnt in rotation for a reason. (being that its bad)

**Comment by ghost** [comment]
There, now there's a warning that it's a revolution.

**Comment by alexkar598** [comment]
It's been more than two weeks,noone merged it. Maints,feel free to reopen if one of you actually wants it.

**Pull request closed without merging**
