### PR TITLE
ai thingie

### PR DESCRIPTION
**Pull request by Beeper-Skeeper**
# Document the changes in your pull request

# Why is this good for the game?

# Testing

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images
mapping: This is a mapping change
spellcheck: fixed a few typos  
experimental: This is experimental
/:cl:

### CODE REVIEW

**Review by ynot01 — APPROVED** [review]
Compiles

**Comment by azzzertyy** [comment]
what

**Review by Moltijoe — APPROVED** [review]
code looks good to me

**Comment by ShoziOffical** [comment]
Bro added a file and then removed it funny shit

**Comment by iamthesilly** [comment]
Please add actual changes to your PR

**Comment by iloveloopers** [comment]
This is one of the pull requests of all time

**Review by ToasterBiome — APPROVED** [review]
LGIM!

**Review by Moltijoe — APPROVED** [review]
Looks just as good the second time

**Review by AshCorr — APPROVED** [review]
Great change!

**Review by ynot01 — CHANGES_REQUESTED** [review]
sorry, don't agree with these changes and neither do the straw men i came up with

**Review by warface1234455 — CHANGES_REQUESTED** [review]
```suggestion
 (Insert something here)
```

**Comment by JohnFulpWillard** [comment]
No GBP + Headcoder approval required beforehand + Breaks GitHub ToS + Breaks contributing guidelines

**Comment by Maia-J** [comment]
> No GBP + Headcoder approval required beforehand + Breaks GitHub ToS + Breaks contributing guidelines

It hasn't been 24 hrs

**Comment by ShoziOffical** [comment]
> > No GBP + Headcoder approval required beforehand + Breaks GitHub ToS + Breaks contributing guidelines
> 
> It hasn't been 24 hrs

Doesn't matter ìf th3y break guidelines 
Screenshot_2023-10-30-17-02-27-64_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Beeper-Skeeper** [comment]
I, I made this while trying to do something with a fork of the yogstation code I downloaded because I was trying to set up a private server. How the fuck did this end up as an actual pr for the master?

**Pull request closed without merging**
