### PR TITLE
Holopads will no longer automatically accept calls from non-heads

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

You WILL use the "accept call" button I'm TIRED of people being able to just spam holopads everywhere

# Changelog

:cl:  
tweak: Auto-accept holopad calls are now only for heads of staff
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Wouldnt this make a niche thing even nicher? Either way, should be head level so they can easily talk to their staff instead of just captain. But i still think it practically removes calls considering like 3 people use them.

**Comment by azzzertyy** [comment]
> Wouldnt this make a niche thing even nicher? Either way, should be head level so they can easily talk to their staff instead of just captain. But i still think it practically removes calls considering like 3 people use them.

this is not a niche thing, every round a scientist with a brped will use it to instantly upgrade everyones machine

**Comment by azzzertyy** [comment]
i prefer this over #19894

**Comment by Hislyna** [comment]
> > Wouldnt this make a niche thing even nicher? Either way, should be head level so they can easily talk to their staff instead of just captain. But i still think it practically removes calls considering like 3 people use them.
> 
> this is not a niche thing, every round a scientist with a brped will use it to instantly upgrade everyones machine

Ha thats funny. Idk why yall dont want upgrades but whatevs. Id still suggest making it heads not just capt tho

**Review by ToasterBiome — DISMISSED** [review]
heads

wait isnt it already head only cause of keycard auth

**Comment by Hislyna** [comment]
> heads
> 
> wait isnt it already head only cause of keycard auth

Apparently scientists are memeing with being able to autocall, so apparently not?

**Comment by SomeguyManperson** [comment]
switched to heads

**Review by JohnFulpWillard — APPROVED** [review]

**Pull request merged**
