### PR TITLE
lets you see food in the microwave

### PR DESCRIPTION
**Pull request by ktlwjec0**
https://github.com/tgstation/tgstation/pull/70203

Lets you see food inside the microwave and updates the sprite.

Tested, works, can't find any issues.
# Spriting
image image image

:cl:  Ktlwjec, Mothblocks
tweak: You can now see food inside the microwave.
/:cl:

### CODE REVIEW

**Comment by Therandomhoboo** [comment]
I dont like the person in the pic. Can we swap them out with someone cooler?

**Comment by ShoziOffical** [comment]
agree replace with a gigachad chef

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
honestly the microwave sprite is a bit of a downgrade, can we have the new required sprites be the style of the old one and just make it so the old one can see what’s inside?

**Comment by iloveloopers** [comment]
big nerf to chemical payloads, now people know theres a bomb inside the microwave when you bring it to medbay

**Comment by ktlwjec0** [comment]
> honestly the microwave sprite is a bit of a downgrade, can we have the new required sprites be the style of the old one and just make it so the old one can see what’s inside?

sure, done

**Comment by ShoziOffical** [comment]
Screenshot_2023-08-07-04-37-16-55_40deb401b9ffe8e1df2f1cc5ba480b12

Not a spriter but this perspective of the door is a bit weird it feel likes the door isnt wide and isn't much aligned. Just my opinion

**Comment by ktlwjec0** [comment]
> Not a spriter but this perspective of the door is a bit weird it feel likes the door isnt wide and isn't much aligned. Just my opinion

this is literally the current sprite i havent changed this

**Comment by ShoziOffical** [comment]
> > Not a spriter but this perspective of the door is a bit weird it feel likes the door isnt wide and isn't much aligned. Just my opinion
> 
> this is literally the current sprite i havent changed this

wait it does this now?? Guh last time it doesn't do this

**Comment by ShoziOffical** [comment]
Been like months since i touched the microwave

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
