### PR TITLE
Makes greed slot ,achine deal damage to max health

### PR DESCRIPTION
**Pull request by SomeguyManperson**
BUT REMEMBER
THE HOUSE
ALWAYS
WINS

:cl:  
tweak: Greed slot machine deals damage to max health
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
hope you like living on an IV drip of brave bull

**Comment by boodaliboo** [comment]
make it easier to win if you do this

**Comment by Mesalikepie** [comment]
Another ruin that will be ignored. First the ice biome now this. If this keeps up eventually you will have ruins just be ignorable and get in the way.

**Comment by SomeguyManperson** [comment]
if you downvote you are powergamer this is for a fucking die of fate of course it should be a pain in the ass

**Comment by boodaliboo** [comment]
> if you downvote you are powergamer this is for a fucking die of fate of course it should be a pain in the ass
no thats not the reason, why should i go to the ruin if all thats going to happen is that i die and theres a 1 percent change i get a item that can also instantly kill me

**Comment by ghost** [comment]
good pr

**Review by alexkar598 — DISMISSED** [review]
Update the comment about what the machine does on line 3

**Comment by Marmio64** [comment]
yeah if you play it, you have a 1% chance to get a one use die of fate that has a 9 in 20 chance to do something bad to you.

aka, this PR sucks, and theos literally plays too much SS13 and is probably going insane.

**Comment by jcatjmeow** [comment]
,achine

Also you remove health, then on a jackpot you add health, lol, why not just make it so it only removes health on a non-jackpot

**Comment by jcatjmeow** [comment]
> Another ruin that will be ignored. First the ice biome now this. If this keeps up eventually you will have ruins just be ignorable and get in the way.

Good

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
