### PR TITLE
Give nightmares veil

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Nightmares are currently incredibly weak and have no room to escape if anyone corners them in a lit room because they would need to destroy all the lights in addition to the attacker's lights. Hopefully veil might make this easier and make nightmare viable.
# Spriting

# Wiki Documentation

Give nightmares veil

# Changelog

:cl:  
tweak: Gave nightmares veil
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
lmao

**Comment by Simplehorror** [comment]
Mqiib downvoted this PR because of "lmao". Truly compelling reasoning and criticism

**Comment by Moltijoe** [comment]
lmao

**Comment by Simplehorror** [comment]
Moltijoe downvoted this PR because of "lmao". Truly compelling reasoning and criticism

**Comment by Cartlord** [comment]
Nightmares can already just fucking kill a person, they're not really meant to wage war on the station

**Comment by Bibby0110** [comment]
They're not supposed to be in lit rooms, they're a side antagonist, keep to the shadows matey.

**Comment by Simplehorror** [comment]
> They're not supposed to be in lit rooms, they're a side antagonist, keep to the shadows matey.

	new_objective.explanation_text = "This station is an insult to the void. Return it to darkness."
But I guess you're just not allowed to leave maintenance ever as a side antagonist or die instantly

**Pull request closed without merging**
