### PR TITLE
Enables mother drone as a roundstart AI lawset

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Enables Mother drone as a roundstart AI lawset with the same weight as reporter

# Changelog

:cl:  
tweak: Enabled mother drone as a roundstart AI lawset
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
DRONE AI
DRONE AI
DRONE AI

**Comment by adamsong** [comment]
This one is probably not a good idea, but I'm just making a bunch of prs to give options

**Comment by Xoxeyos** [comment]
I think this is a pretty bad idea. https://github.com/yogstation13/Yogstation/blob/c2f0f7f380a680ba29455809ed942d9b443d17f0/code/datums/ai_laws.dm#L155

**Comment by Marmio64** [comment]
You pretty much cant do anything with this lawset, so it doesnt sound fun
edit: a better version of this lawset would be the 'maintain' lawset, which i kind of like actually

**Comment by alexkar598** [comment]
https://github.com/yogstation13/Yogstation/blob/c2f0f7f380a680ba29455809ed942d9b443d17f0/code/datums/ai_laws.dm#L155-L158

**Pull request closed without merging**
