### PR TITLE
[JAMIE] Cyborgs automatically get PDA messengers & AI has a tablet now

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

hnng

# Changelog

:cl:  
tweak: AI now spawns with an integrated tablet instead of a deprecated PDA
tweak: Cyborgs and AIs now spawn with PDA messengers pre-installed and set-up
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
what happens if you use bomberman on AI

**Comment by ynot01** [comment]
> what happens if you use bomberman on AI

it dies

#16949

**Review by Moltijoe — APPROVED** [review]
PROGRESS

**Comment by Moltijoe** [comment]
Can't find any problems with this, can't keep borgs in the dark forever
no clue how this fucks with bibby's AI rework, but that's a problem for him to sort out

**Pull request merged**
