### PR TITLE
Dirty Zero Destroyer (Eclipse Station)

### PR DESCRIPTION
**Pull request by MayhemSailor**
### Removes (pixel_y = 0) and (pixel_x = 0) instances from Eclipse Station.

Removes 264 instances of Dirty Zero from Eclipse Station

#### Changelog

:cl:  
bugfix: Removed Dirty 0
/:cl:

### CODE REVIEW

**Comment by MayhemSailor** [comment]
@Ktlwjec1 conflict resolved

**Comment by Hopekz** [comment]
What map editor did you use initially?
Won't these just be re-created the next time someone edits your map with that creator?

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
Can you remove all the empty lines like on line 11822, and the semi-colons before } like on line 11821?

**Comment by MayhemSailor** [comment]
@Hopekz I didn't use a map editor, I edited the file itself.

**Comment by MayhemSailor** [comment]
@Ktlwjec1 White Space and artifact colons are removed.

**Review by Ktlwjec1 — APPROVED** [review]

**Pull request merged**
