### PR TITLE
Adds the botanist garb. A cool apron alternative for botanists

### PR DESCRIPTION
**Pull request by Hopekz**
uxmVQJVXmd

Z4Bn6e3K6D8CXn3lUiDp
wXAsOdHSWK

#### Changelog

:cl:  Hopek
rscadd: Added the botanist garb. A cool apron alternative for botanists
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
this makes them look like fuckin aliens

**Review by Partheo — CHANGES_REQUESTED** [review]
Sprite needs improvement, since it just isn't really an SS13 sprite. In its current form it doesn't fit in the game.

I would do a fix myself but I've been really busy. Either you can wait till I get to it or do something else with this.

**Comment by gaminada** [comment]
I like it, even though it gets replaced with durathread most of the time.

**Comment by alexkar598** [comment]
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

**Pull request closed without merging**
