### PR TITLE
Fuck you *Ungreens your Peacekeepers*

### PR DESCRIPTION
**Pull request by Scrambledeggs00**
# Document the changes in your pull request

Turns the Peacekeeper ERT from the green menace into the space UN by giving their equipment unique sprites.
All new items added in by this PR have no stat changes from their original versions and are added to further the new blue and white color scheme.
Only change that affects other ERTs is the new sprite for the tactical breath mask as multiple ERTs use them, though I believe it to be basic enough to fit in with their gear.
I've tested it and, as far as I can tell, all sprites are implemented correctly and do show up on the officer, heavy, and commander roles.

# Spriting

Mob Sprites:
PeacekeeperClothing
PeacekeeperUniforms
Peacekeepermob1
Peacekeepermob2m

Object Sprites:
PeacekeeperObjects

Animated Sprites:
PeacekeeperBatonActive
PeacekeeperBatonActiveMob

# Wiki Documentation

Peacekeeper's ERT images on the Wiki should be changed to have their newly colored equipment

# Changelog

:cl:  
rscadd: Peacekeeper helm, belt, vest, and uniforms added    
imageadd: Peacekeeper riot suit, helm, beret, tactical stunprod, and tactical breath mask have new sprites 
imagedel: Most Peacekeeper gear is no longer green tinted Security gear
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Man literally stole my unique item.
because of that i like everything except the beret

**Comment by azzzertyy** [comment]
agreed berets colours are off from the other items

**Comment by Scrambledeggs00** [comment]
> Man literally stole my unique item. because of that i like everything except the beret

Sprite-0001
Top is this PR's beret, bottom is yours.
The only thing in common is that they're both blue with gold insignias. Besides that, yours is a different, brighter blue, has a bigger insignia, and is animated. They're similar, but I used the HoS beret for mine and just added a brighter version of the vest's blue while yours is a more modified beret with a bigger insignia and more subtle shading for the object sprite.
image

**Comment by Scrambledeggs00** [comment]
> agreed berets colours are off from the other items

The beret's blue is just a lighter shade of blue than the vest's blue, with the difference between the beret's darkest blue and the vest's brightest blue being 4 value. The reason why is because most cloth items are brighter than items that are clearly armor, so I made it lighter. Plus it helps the commander stick out more.

**Comment by cuackles** [comment]
> > Man literally stole my unique item. because of that i like everything except the beret
> 
> Sprite-0001 Top is this PR's beret, bottom is yours. The only thing in common is that they're both blue with gold insignias. Besides that, yours is a different, brighter blue, has a bigger insignia, and is animated. They're similar, but I used the HoS beret for mine and just added a brighter version of the vest's blue while yours is a more modified beret with a bigger insignia and more subtle shading for the object sprite. image

ok so first of all before the actual review, u should not have a beret similar to the one of manatees donor item, the sprite is great and it absolutely fits, but i cannot in good faith add that to the game as its visually the same thing to an exclusive item for manatee, would be injust to them, specially cus i know that the item has sentimental value to them, another form of hat or another interpretation of the beret could work but as it currently its i cannot add that

**Review by MajManatee — APPROVED** [review]
looks fine to me

**Review by cuackles — APPROVED** [review]

**Review by Hopekz — APPROVED** [review]
Creator of Peacekeeper and Amber task force approved (#8223, #10326)


Shame about the beret recolor but that's yogdev

**Pull request merged**
