### PR TITLE
Allows felinids to laugh

### PR DESCRIPTION
**Pull request by patpol4**
### Intent of your Pull Request
Port of https://github.com/BeeStation/BeeStation-Hornet/pull/2854
 I don't know if this is right im not code, i just copypaste

### Why is this good for the game?
They are genetically modified humans, they should be able to laugh

#### Changelog

:cl:  
bugfix: felinids can laugh
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
no

**Comment by patpol4** [comment]
> no

why

**Comment by Marmio64** [comment]
no

**Comment by patpol4** [comment]
> no

why

**Pull request merged**
