### PR TITLE
Renables & Improves Stalwart + Fixes Stalwart's Loot Drop & Improves It + Adds New Stalwart Drops

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Makes Stalwart's loot properly drop, and expands the loot from only a plasma cutter to also include a new unique spear, and some bluespace & dilithium crystals, all on RNG. This accounts for there being four of them possible

also made some attempts to fix up plasmacutter muzzle flashes/tracers/impacts but uhhh...yeah seems that entire system is broken anyway.

**Ancient Control Rod**
A spear with 3 tile range that does 0 damage if not wielded, and only does 8 damage at all to non-fauna. Lavaland fauna however, receive 30 damage instead, making this an excellent tool for picking off Goliaths and poking megafauna from range

**Ancient Focusing Crystal**
A self-charging plasma-shotgun with a range of 4 tiles, or 10 tiles through rock (+6). Does stamina damage, but only 5 per pellet, with 4 pellets per shot. Fires through glass, over tables, and through grilles. Fires blue plasma cutter projectiles. Does bonus Brute damage to Fauna
See it in action here: https://www.youtube.com/watch?v=zrXAXhH3Y8I

**Bluespace Data Crystal**
Stalwart's unique gem, which can be used like a CPU for AI servers! Can also be overclocked
ss (2022-09-01 at 07 28 35)
4x overclocked stalwart gem CPUs
ss (2022-09-01 at 07 29 54)
the rack glows (stops glowing inside a server)
there's a gem bounty for 16,500cr, and without the bounty they export for 9,800cr

# Sprites

Ancient Control Rod
download
colasedspear
download (1)
spear
ss (2022-09-01 at 07 04 35)
ss (2022-09-01 at 07 04 41)
ss (2022-09-01 at 07 04 48)
ss (2022-09-01 at 07 04 54)
ss (2022-09-01 at 07 05 00)
ss (2022-09-01 at 07 05 05)
ss (2022-09-01 at 07 05 14)
ss (2022-09-01 at 07 05 20)

Ancient Focusing Crystal
download
Sprite-0003

Bluespace Data Crystal
download (2)
funnyrock
ss (2022-09-01 at 07 04 02)
There's an unused purple variant, exactly the same shape and lighting however.

# Sound

New music track for Stalwart's battle music, by @Hey-Holokin!
https://soundcloud.com/hey-holokin/stalwart

# Wiki Documentation

Fairly certain we still lack a page for Stalwart, or an entry on any megafauna page? But one definitely needs to be made.

# Changelog

:cl:  VaelophisNyx, @KillerOrcaCora, @Hey-Holokin, @cuackles
rscadd: Adds new loot to Stalwart
bugfix: Stalwart can spawn again
imageadd: adds new sprites for stalwart's new loot, and old loot
imageadd: adds new sprites for purple muzzle-flashes (system unused/bugged?)
soundadd: adds new music for Stalwart
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
It would be neat if we knew what it is.

**Comment by VaelophisNyx** [comment]
https://github.com/yogstation13/Yogstation/pull/11096

**Comment by N3D6** [comment]
Stalwart is broken currently probably shouldn’t merge this until it’s fixed

**Comment by VaelophisNyx** [comment]
I keep seeing this said, and just

how
I tested Stalwart
nothing seemed outright broken

**Comment by VaelophisNyx** [comment]
pending new gun sprite before PR description and title are updated*

**Comment by JamieD1** [comment]
> Stalwart is broken currently probably shouldn’t merge this until it’s fixed

Bit more info?

**Comment by VaelophisNyx** [comment]
turns out its loot didn't drop at all, and even if it did, it was (is) spriteless.

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
The "Ancient Control Rod" Sprite in its current form is not approvable. If you need any help with it, you can ask me or our other Spriters.

**Comment by UselessTheremin** [comment]
PRAISE BE VAEL. Thanks for fixing this thing up, glad players will finally be able to have fun with the thing I made. 
also i’ll probably be saying hi to a gitban from this comment but i don’t care.

**Comment by VaelophisNyx** [comment]
just needs spear sprites and I think it's ready to go

**Comment by VaelophisNyx** [comment]
track preview link updated!

**Comment by VaelophisNyx** [comment]
drafting for now until I have the sprites for the spear

**Review by KillerOrcaCora — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
