### PR TITLE
Lesser shadowlings can't use guns anymore

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Lesser shadowlings can't use guns anymore. This is to keep consistency with shadowlings as well as stop them being invisible and attacking.

# Wiki Documentation
Lesser shadowlings can't use guns anymore
# Changelog

:cl:  
tweak: Lesser shadowlings can't use guns anymore
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
@The-Sun-In-Splendour state your reasoning for leaving a downvote
image
nvm, makes sense

**Comment by The-Sun-In-Splendour** [comment]
Got a problem? How about you state your reasoning for why you keep making shit PRs?

**Comment by Simplehorror** [comment]
i'm not taking shit from some no-namer who has never opened a PR and solely exists on github to shittalk people without giving constructive criticism, GTFO from my pr

**Comment by The-Sun-In-Splendour** [comment]
> i'm not taking shit from some no-namer who has never opened a PR and solely exists on github to shittalk people without giving constructive criticism, GTFO from my pr

I don't need to give constructiv criticism. Common sense is enough to know why 99% of your PRs are better off never even being opened in the first place.

**Comment by Simplehorror** [comment]
> > i'm not taking shit from some no-namer who has never opened a PR and solely exists on github to shittalk people without giving constructive criticism, GTFO from my pr
> 
> I don't need to give constructiv criticism. Common sense is enough to know why 99% of your PRs are better off never even being opened in the first place.

ok, are you going to say why or are you just going to keep being a retard on this github? this is the first time i've ever seen you comment

**Comment by iamthesilly** [comment]
can you two maybe calm down a little? there are better places to argue than here

**Comment by The-Sun-In-Splendour** [comment]
> can you two maybe calm down a little? there are better places to argue than here

There aren't because this simplehorror guy is a literal who outside of this github yet he keeps insisting I need to make my github account the same name as my ckey so that he knows who I am to even consider the fact he's been pumping out the worst PRs i've seen for the past 3 days.

**Comment by Moltijoe** [comment]
> @The-Sun-In-Splendour state your reasoning for leaving a downvote image nvm, makes sense

My dude taking downvotes on a pr so personally he starts searching up the people that do it

**Comment by CMOisLing** [comment]
> My dude taking downvotes on a pr so personally he starts searching up the people that do it

He put his heart and soul into this one, I cant blame him.

**Comment by LoliconSlayer** [comment]
> > can you two maybe calm down a little? there are better places to argue than here
> 
> There aren't because this simplehorror guy is a literal who outside of this github yet he keeps insisting I need to make my github account the same name as my ckey so that he knows who I am to even consider the fact he's been pumping out the worst PRs i've seen for the past 3 days.

Mfw he's calling someone a no-namer whilst also maintaining his own anonymity on his garbage tier PRs

DeDeDe Laughing

**Comment by Simplehorror** [comment]
https://www.youtube.com/watch?v=_MuuMgWSQEY

**Comment by ReddicusDragon** [comment]
> i'm not taking shit from some no-namer who has never opened a PR and solely exists on github to shittalk people without giving constructive criticism, GTFO from my pr

this is my reason for downvoting this PR. Nobody is required to give you a reason for a downvote, and the fact that you are so hostile toward a funny little emote indicates to me that you should not be making PRs here. Make more PRs once you learn to accept that people can downvote you for any reason, and that they don't have to tell you a reason. Additionally, ad hominem attacks make you look really bad. Something to consider for the future.

**Comment by Bibby0110** [comment]
Be nice to the other players

**Comment by Maia-J** [comment]
> Be nice to the other players

I doubt he actually plays

**Comment by CMOisLing** [comment]
its adams alt he cant hes community banned

**Pull request closed without merging**
