### PR TITLE
AI can now properly dab

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request
Default dab animation default is not much dabbing, now much dabbing

# Changelog

:cl:  
bugfix: fixed ai having weak dabs
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
No gif???

**Comment by ReddicusDragon** [comment]
Lacking rationale

**Comment by adamsong** [comment]
> Lacking rationale

Bugs are bad, patching bug

**Comment by ReddicusDragon** [comment]
> > Lacking rationale
> 
> 
> 
> Bugs are bad, patching bug

Valid rationale 😔

**Review by MajManatee — APPROVED** [review]
epic dab

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
