### PR TITLE
Lets people carry chairs and wheelchairs on their back

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
idfk, time_urss asked me to

:cl:  
tweak: People can carry chairs and wheelchairs on their back
/:cl:

### CODE REVIEW

**Comment by ju45he** [comment]
I swear to God someone is going to steal a cripple's wheelchair, put it onto a monkeys back, cripple the monkey, then make the two cripples fight to the death over a wheelchair. Be it me or some other person this WILL happen if this PR is merged.

**Comment by MajManatee** [comment]
How the hell do you expect to carry a chair on your back?

**Comment by iloveloopers** [comment]
> How the hell do you expect to carry a chair on your back?

you can carry a fire axe on your back

**Comment by ShoziOffical** [comment]
> > How the hell do you expect to carry a chair on your back?
> 
> you can carry a fire axe on your back

you can carry a shotgun on your back

**Review by ToasterBiome — APPROVED** [review]
what

**Comment by azzzertyy** [comment]
> How the hell do you expect to carry a chair on your back?

image

**Pull request merged**
