### PR TITLE
adds Phencyclidine (pcp) a new drug to use and abuse

### PR DESCRIPTION
**Pull request by boodaliboo**
adds pcp which boosts your surgery chance and gives you aneslegia while in use
od is 30
addiction is 15
made with morphine,  nitrous oxide, pump up, and epinephrine
adds more variety to the game and adds more drugs for chemistry to pump out, and we cant have ketamine without its predeccesor pcp 
:cl:  
rscadd: Adds a new drug for the crew to abuse
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Add a stun reduction as well, similar to the lack of self awareness trauma

**Comment by maxion12345** [comment]
"missing rationale"

someone has clearly never done pcp before 👌

**Comment by boodaliboo** [comment]
why is the .m not working

**Comment by SomeguyManperson** [comment]
image

**Pull request closed without merging**
