### PR TITLE
readds seperated chems

### PR DESCRIPTION
**Pull request by boodaliboo**
some guy in ooc wanted it. im not going to make any efforts on doing any requested changes and if this doesnt compile im closing it
#### Changelog

:cl:  
rscadd: readds seperated chems   
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
haha im goig to throw this tomato at you but haha it fucking EXPLODED ON IMPACT

**Comment by ynot01** [comment]
haha im goig to throw this tomato at you but haha it fucking EXPLODED ON IMPACT

**Comment by ynot01** [comment]
haha im goig to throw this tomato at you but haha it fucking EXPLODED ON IMPACT

**Comment by boodaliboo** [comment]
> haha im goig to throw this tomato at you but haha it fucking EXPLODED ON IMPACT

yup thats how it works

**Comment by SomeguyManperson** [comment]
no

**Comment by MrHorizons** [comment]
Eh, nah. I'm a botany man myself and Separated Chemicals basically has no purpose beyond making "hee hoo explosion" plants, especially with the existence of Gaseous Decomposition.

**Pull request closed without merging**
