### PR TITLE
New vampire roundstart sound effect + adds a specific sound for becoming a new blood

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Normal Vampire: https://cdn.discordapp.com/attachments/544802231481008130/887814914989760552/newvampire.ogg
Alternate Vampire (10% chance of playing): https://cdn.discordapp.com/attachments/544802231481008130/887852812208336926/newvampire_alt.ogg
New Blood: https://cdn.discordapp.com/attachments/544802231481008130/887856272140021760/lilithspact.ogg
The vampire "succ" sound is funny, but I feel it should be more serious and eerie like the other antagonist ambient start sounds. 
Music bit taken from Toccata and Fugue, the most vampire-y song ever made.

EDIT: Mixed a version that includes the original succ, makes it happen 10% of the time.

https://commons.wikimedia.org/wiki/File:Toccata_et_Fugue_BWV565.ogg

Bat sounds taken from freesound.org

https://freesound.org/people/felix.blume/sounds/245768/

It's a bit longer than the rest of them, I can try to trim it down further if told but everything I do to make it shorter absolutely FUCKS the quality, give me some feedback!

# Changelog

:cl:  
rscadd: added new vampire roundstart ambient sound
tweak: replaced old vampire roundstart sound with new vampire roundstart sound in antag datum

/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
I'd say this is a bit too long, try and cut it down to 5 to 7 seconds.

**Comment by ToasterBiome** [comment]
> I'd say this is a bit too long, try and cut it down to 5 to 7 seconds.

https://cdn.discordapp.com/attachments/544802231481008130/887814914989760552/newvampire.ogg

I got it down from 14 seconds to 10 seconds, putting it firmly in the middle of notable antag noises, and placing it on par with solo/small team antags.

Darkspawn/Sling: 9 seconds
Ling: 9 seconds
Traitor: 10 seconds
Clock Cult: 11 seconds
Nuclear Ops: 12 seconds
Cult: 13 seconds
Malf: 14 seconds

**Comment by Jarod1200** [comment]
succ is iconic

**Comment by ToasterBiome** [comment]
> succ is iconic

I gave you a little bit of succ as a treat

**Comment by Mqiib** [comment]
We got succ back boys, mission **succ**ess.

**Comment by Tipy1802** [comment]
I like the new sound very much!

The sound clip you placed in the PR description is 15 seconds long but you said it you cut it to 10 seconds, can you share the cut version as well as I am worried that the cut may sound weird and I do like the full 15 seconds version, it's not really that long

**Comment by ToasterBiome** [comment]
> I like the new sound very much!
> 
> The sound clip you placed in the PR description is 15 seconds long but you said it you cut it to 10 seconds, can you share the cut version as well as I am worried that the cut may sound weird and I do like the full 15 seconds version, it's not really that long

Sorry for the late response, the shorter version is in the post where I go over the lengths of other antag sounds! I edited the original post now too to include the shorter one and the alternative with added succ.

**Pull request merged**
