### PR TITLE
Removes maps that people hate

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Apparently people hate these maps, and we don't play them often, so why bother keeping them?
Alternative to #17877

Deletes the following maps:
- Yogsmeta
- YogsDelta
- GaxStation
- AsteroidStation

# Changelog

:cl:  
rscdel: Removed rarely used maps that people don't like
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
you forgot 1 map

**Comment by iamthesilly** [comment]
Would be nice to include a list of which maps were removed in the pr

**Comment by adamsong** [comment]
> Would be nice to include a list of which maps were removed in the pr

Everything but yogstation

**Review by patpol4 — APPROVED** [review]
bold

**Comment by MajManatee** [comment]
Gax, Asteroid, and meta are played all the time

delta sucks tho

**Comment by adamsong** [comment]
image
Are they though?

And when I inquired as to why we don't encourage their use, I was told because people hate them.

**Comment by Moltijoe** [comment]
asteroid is too big for our server to get proper use out of imo, the others have their place though.
Annoys me to no end that people will vote against gax when it's graveyard hours lowpop

**Comment by Moltijoe** [comment]
> And when I inquired as to why we don't encourage their use, I was told because people hate them.

people that hate them are also the same kind of people that just want to eat the same food all the time because they don't like something that isn't what they always have

**Comment by MajManatee** [comment]
i dont think people hate gax/asteroid, they just hate change, and like box.

Add delta to that graph

**Comment by Moltijoe** [comment]
> Add delta to that graph

hasn't delta been disabled in rotation for a while now?

**Comment by MajManatee** [comment]
then why is it mentioned in this pr?

**Comment by adamsong** [comment]
> Add delta to that graph

It is lol

**Comment by Moltijoe** [comment]
> then why is it mentioned in this pr?

because this is literally deleting the map file, and i think it was the only map that was disabled, but still in the code

**Comment by adamsong** [comment]
image
There, delta is in the graph, time range is 2 years

**Comment by MajManatee** [comment]
I think it would be better for the server if we went with the other option, and just played these maps more. Once they get used more, improvements can be made on parts people dont like.

**Comment by adamsong** [comment]
> I think it would be better for the server if we went with the other option

It would, but at this point I'm tired of having a bunch of maps that are rarely played, so I want Jamie to decide between these two prs, because doing neither is worse than either.

**Comment by Moltijoe** [comment]
> It would, but at this point I'm tired of having a bunch of maps that are rarely played, so I want Jamie to decide between these two prs, because doing neither is worse than either.

If this pr gets merged, I have no clue what biome will do to us

**Comment by JamieD1** [comment]
Meme PR

**Comment by adamsong** [comment]
> Meme PR

I'm completely serious, if we aren't going to play them regularly, and people hate them, why keep them in the code base?

**Comment by patpol4** [comment]
I wouldnt call this a meme pr

**Comment by JamieD1** [comment]
Not a meme Pr, A dumb PR.

**Pull request closed without merging**
