### PR TITLE
Nearly every (reasonable) item to the game can now be rolled in maintenance loot.

### PR DESCRIPTION
**Pull request by BurgerLUA**
This PR should be testmerged for balance purposes.

# Document the changes in your pull request

SPREADSHEET: https://docs.google.com/spreadsheets/d/1zk-VuNrYI6r5MFO6lGC8NKdPL5xllbogXYkDtGynAhE/edit?usp=sharing

The amount of loot that spawns in maint is now between x1 and x6 of what it normally is (per maint loot).

I spent maybe a total 6 hours going through every item in the game, seeing if it was reasonable to add to maintenance loot, then adding it to maintenance loot weights if I deemed it necessary. 

The system is put into 5 categories:
- Regular maintenace stuff (like tools and stuff engineers would just leave around) is the most common to find.
- Engineering tools, toolboxes, storage, equipment, etc is a 1 in 2 chance to get the loot table for. (Examples: Empty backpacks, boxes, bags, tools, toolboxes)
- Makeshift stuff and general assistant garbage is a 4 in 10 chance to get the loot table for. (Examples: Makeshift welder, floorpills).
- Minorly powerful stuff is a 1 in 10 chance to get the loot table for. (Examples: Bodybag, incomplete ed209 assembly).
- Moderately powerful stuff is a 1 in 100 chance to get the loot table for. (Examples: First aid kit, Pepperspray).
- Majorly powerful stuff is a 1 in 1000 chance to get the loot table for. (Examples: Random piece of chamelon equipment, weedkiller grenade)
- Crazy stuff and whatnot is a 1 in 10000 chance to get the loot table. (Examples: Cyanide pill, pipebomb)

Chances are based on each instance of maint loot. If in the case where Crazy stuff, majorly powerful stuff, or moderately powerful stuff is rolled, the loot count for that pile will always be 1 instead of multiple.

# Changelog

:cl:  BurgerBB
experimental: Increases the quantity and quality of loot you can find in maintenance.
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
We're going to need balance council on this probably

**Comment by patpol4** [comment]
Here is a spreadsheet to make this easier to review
https://docs.google.com/spreadsheets/d/1IIBLoM7JeN5N6MnJEKkRBH4rWr1ACp5QXv1o12p4F54/edit?usp=sharing

**Comment by Moltijoe** [comment]
the main balance point i can think of by diluting the pool is vastly reducing the spawn rate of sunglasses, making flashes even more oppressive.

**Comment by BurgerLUA** [comment]
I converted the data into a spreadsheet and yes, that seems to be a problem. I will have to adjust chances for "essential" items like sunglasses.

**Comment by BurgerLUA** [comment]
Note that this will not affect loot for things like randomly generated maint areas where sometimes they will have a grantee to spawn something.

**Comment by BurgerLUA** [comment]
I'm going to basically need a list of every single maintenance item that people think is important enough to be a nearly guaranteed spawn so the balance of the game isn't thrown out the window.

**Comment by Rdrazga** [comment]
Be aware if chameleon gear is in the roll table, literally nobody except traitors will be able to interact with it since last I checked chameleon stuff does not show up on the UI unless you are a traitor.

**Comment by Rdrazga** [comment]
Almost through the list a few more things to note:
-Capitalisium and stallinium (in major) can be used to create mass conversion golems
-Syndie toolbox should prob not be in the traditional section as it can be used to unlock illegal tech
-YOU CAN GET A METEOR GUN?

**Comment by Rdrazga** [comment]
And yes it may be a good idea to make a separate high chance of spawning category for things that already can spawn in maint. Donk pockets, sunglasses, MREs, maint-pumpup, Briefcases, ect.

**Comment by Rdrazga** [comment]
Be aware as well your math for rolling probabilities is off. Serious gets 1 chance of rolling, Major gets 9 chances of rolling (not 10), Moderate gets 90 chances of rolling (not 100), minor gets 900 chances of rolling (not 1000), ect.

**Comment by Rdrazga** [comment]
Be aware due to how you did the RNG your number for how often things rolls is off. 
Serious is       1/10,000
Major is          9/10,000
Moderate is    90/10,000
Minor is          900/10,000
Makeshift is    4,000/10,000
Traditional is   5,000/10,000

**Comment by Rdrazga** [comment]
And because I was bored I added in the % spawn chance for every individual item into an excel version of your google doc
[maint loot pr.xlsx](https://github.com/yogstation13/Yogstation/files/10471294/maint.loot.pr.xlsx)

**Comment by Hopekz** [comment]
> the main balance point i can think of by diluting the pool is vastly reducing the spawn rate of sunglasses, making flashes even more oppressive.

If people think glasses don't appear enough after this change I'd imagine they'd make some other way to get them or increase the probability.

Hard to tell from this PR alone how it will effect things

**Comment by MajManatee** [comment]
assistant exploring maints
open box
pipebomp
Explode and set off fuel tank, killing me instantly

**Comment by BurgerLUA** [comment]
> 

working as intended

**Comment by BurgerLUA** [comment]
I tested it locally.

Previous settings didn't really spawn enough loot because the loot table was so concentrated. I did a bunch of tests and there were about maybe 1 sunglasses spawns out of 45 spawns.

This PR should be test merged so people can give feedback on how rare or common something is.

**Comment by MajManatee** [comment]
/obj/item/stack/sheet/capitalisium = W_MYTHICAL,
	/obj/item/stack/sheet/stalinium = W_MYTHICAL,
	
	didnt realize these existed but im happy they do.
	
	A few items seem like they are in the wrong categories, as in too high up. Luxury bar capsules are 1/10,000? I can get like 100 of them in a mining shift. Things like that.
	
	looking forward to seeing more stuff in maints. Make exploring a bit more fun.

**Comment by CMOisLing** [comment]
> Almost through the list a few more things to note: -Capitalisium and stallinium (in major) can be used to create mass conversion golems -Syndie toolbox should prob not be in the traditional section as it can be used to unlock illegal tech -YOU CAN GET A METEOR GUN?

The crew can have a little illegal tech, as a treat.

**Comment by Mqiib** [comment]
Me like maint buff

**Comment by MajManatee** [comment]
i see an awful lot of sheets of glass/metal, and cheap sunglasses.

**Comment by Rdrazga** [comment]
Notes after playing this for a quite a few rounds
- Donksoft and Foamforce guns should NOT be in the low tiers of this, if in this at all. The foamforce pistol is normally a traitor weapon, and the foamforce smg/LMG are very robust for maint loot.
- WHY SO MANY CHEAP SUNGLASSES
- Me need more food, me lacking on maint donk pockets, me hunger
- Sec tape/holobarrier projectors are not exactly dangerous or anything, but don't make sense to be as common as they are
- The weird spawnpiles of stuff in just random places of maint should be looked at, they don't even spawn on a table or anything. Would understand more if it was singular items but they normally come in 3+ item piles
- Overall amount of items that spawn in most places should be reduced slightly
- STILL METEOR GUN (even though haven't seen it, the one time this does come up its going to get removed anyways because the weapon is stupid)
- Iv seen far less actual toolboxes in maint, but far more just piles of tools.
- Iv seen syndie playing cards spawn a few times, slightly too high chance.

**Comment by patpol4** [comment]
Probably just keep the old loot amounts, this is what the piles are caused by. Loot amounts are already set on maps.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
please make the changes specified by others in here

**Review by cuackles — COMMENTED** [review]
took a little look at the items and there are some i believe should definingly be removed

- the slaughter demon spawner
- the uplink implant
- the improvised emag
- the meteor pen
- the homerun bat
some others i think probably should go but maybe it isn't necessary i would like to see other people input in it

- the fate d20
- edagger
- sleepy pen

**Review by ynot01 — CHANGES_REQUESTED** [review]
On behalf of balance council:
- Remove the more extreme items that can spawn, like Cuackles said. Although rare, people are still very unhappy that this stuff can just randomly show up
- Like said earlier, donksoft weapons have been way too prevalent, especially higher tiers like the SMG and LMG. Maybe look into making the shotgun/crossbow more common but the pistol and other auto-weapons much more uncommon.
- Big piles of several items are bad, at most only a few items should be on a given tile, right now people just skim through maint right clicking these piles and picking out what they like. This is not what we want.

We understand that this is a process and that tweaks will be necessary, so we look forward to getting back to you on the next testmerge.

**Comment by JamieD1** [comment]
Remove the sunglasses.

**Comment by cuackles** [comment]
> Remove the sunglasses.

To be fair sunglasses where on the maint loot table before they where just EXTREMELY rare

**Comment by Moltijoe** [comment]
> Remove the sunglasses.

my dude, they were already in the maint loot table and pretty important considering how much an antag gets fucked without them. Only other ways are fairly loud (breaking into bartender or sec room). Why do you have such a hardon for flashes being one click insta-wins?

**Comment by BurgerLUA** [comment]
mommy and daddy are fighting on my fluff pr

**Comment by neeshacark** [comment]
> Remove the sunglasses.

my guy what? sunglasses have always been on maint loot tables???? also we should be adding more if anything given the one guaranteed "fuck you you lose" button we have are flashes which for some reason still arent nerfed

**Comment by Hopekz** [comment]
> Remove the sunglasses.

!Jamie moment

**Comment by BurgerLUA** [comment]
smh marked as stale because I didn't work on it during the weekend

I'M WORKING ON IT

**Comment by Mqiib** [comment]
> smh marked as stale because I didn't work on it during the weekend
> 
> I'M WORKING ON IT

_Whip crack_
HARDER, CODERSLAVE!

**Comment by BurgerLUA** [comment]
Here is what I did in the last 2 commits.

Loot piles will only spawn on turfs with dense objects, usually lockers, tables, or racks. In other cases, it will just spawn 1 item regardless of rarity.

Donkpockets (and food in general) were made much more common.

Sunglasses (cheap and normal) were made much rarer.

Holobarriers and tape were made rarer.

Foamforce weapons (and riot darts) were made much rarer.

Empty uplink implant was removed.

Laughter demon spawner was removed.

one-use d20 stealthy die of fate was made much rarer

the meteor pen, edagger pen, and sleepy pen was removed

the homerun baseball bat was removed

**Comment by MajManatee** [comment]
@JamieD1 should probably re-test merge this

**Comment by BurgerLUA** [comment]
testmerge when

**Comment by ChuChu42** [comment]
why is gromit mug 1 in a quintillion chance

**Comment by BurgerLUA** [comment]
Any new thoughts?

**Review by ToasterBiome — APPROVED** [review]

**Review by ynot01 — APPROVED** [review]

**Pull request merged**
