### PR TITLE
Updates the storage implant's button sprite

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
This replaces the crusty ass storage implant's button sprite with a newer, more evil looking one.

# Why is this good for the game?
Sprite is no longer old and crusty.

# Testing
image
Works as intended (sprite updated since this ^)

# Spriting
Based on the mining satchel, and I'm happy to make changes if requested
Updated sprite:
image

<details><summary>The current sprite for comparison</summary>
<p>

image

</p>
</details> 

# Wiki Documentation
The current sprite isn't documented anywhere so this one shouldn't need it either.

# Changelog

:cl:  
imageadd: Updated the storage implant's toggle sprite
/:cl:

### CODE REVIEW

**Comment by AdamPrime314** [comment]
High-effort, fits in with the artstyle instead of just copying nu-TG sprites for the thousandth time.

**Comment by ynot01** [comment]
The shade of red used on the upper half is hard on the eyes

**Comment by ofscarletdreams** [comment]
thats on purpose the syndicate are EVIL do you expect them to go easy on peoples eyes with colour palette

**Review by cuackles — CHANGES_REQUESTED** [review]
image
need that in the red part the difference between the light and dark red becomes more notable, apart from that i like the idea and the design

**Comment by AMyriad** [comment]
> image need that in the red part the difference between the light and dark red becomes more notable, apart from that i like the idea and the design

Forgot the highlights, now updated with this on the latest commit:
image

**Comment by cuackles** [comment]
> > image need that in the red part the difference between the light and dark red becomes more notable, apart from that i like the idea and the design
> 
> Forgot the highlights, now updated with this on the latest commit:
> image

Very good, will re review when off work

**Review by cuackles — APPROVED** [review]

**Review by MajManatee — APPROVED** [review]
hmm yeos

**Pull request merged**
