### PR TITLE
Gives BB a chameleon kit and Agent ID

### PR DESCRIPTION
**Pull request by ynot01**
I'm gonna keep trying to buff BB until something works. They're literally just traitor but harder. You are paired with a random unselectable unloyal mindslave (7TC for the opposite) and expected to complete normal traitor objectives (like assassinations, steal objectives (EVEN STEALING NUKE DISK)) with no equipment.

This PR will not give them a leg up in combat, but it will AT LEAST let them hide when they commit any form of crime, which is something they can't really do without waiting for everyone around them to stop looking.

:cl:  
rscadd: Blood Brothers now spawn with a chameleon kit and agent ID to better avoid security with their lack of equipment
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
You forgot to say that they both have an objective to keep an idiot alive, which was the worst objective on traitor when it was in.

**Comment by gilvian** [comment]
In my opinion it shoudnt get merged for few reasons.

1. Blood brothers should use both forces to collect items for their goals and not a whole kit of semi-usefull items thats just gonna sit in their bag to security to search them

2. Some idiot gonna get banned for memeing with a voice changer

3. Easly breakable metashield stuff

**Comment by Ratvar** [comment]
Point 1 rebuke: items sitting in your bag is a problem with bloodcult, with nukecore box item, with any antag starting with gear in it's backpack. It's universal and is only a problem because random search is a problem that requires fixing, not items themselves. If you advocate for chameleon box being a search tell, would you also say nukebox/clockcult have a search tell that should be removed? Consistency, eh, if you are not lazy.
You could also wear all chamgear, compared to nukebox container or bloodcult runed metal.

Point 2 rebuke: someone dumb'll just do it without a mask, someone griefy will use multiaccount.

Point 3 rebuke. I would like to point out that oldyogs had a feature where nobody but traitor could recognize chameleon gear: https://github.com/yogstation13/yogstation/pull/1524 . Someone forgot to port it, whoops.

**Comment by ynot01** [comment]
imagine complaining that you shouldnt give traitor gear to another antag because they'll grief with it

**Comment by boodaliboo** [comment]
i am ynot and i approve of this pr

**Comment by ynot01** [comment]
maintainers have still not told me why it's conflicting

**Comment by Nickvr628** [comment]
What a shame

**Pull request closed without merging**
