### PR TITLE
Adds vials and vial lockboxes

### PR DESCRIPTION
**Pull request by nmajask**
# Github documenting your Pull Request

Adds vials and vial lockboxes to the game and some maps. Vials are small beakers that can hold only 15u, but look cool. The lockboxes can store up to six vials, can be locked, and show them on the icon. There are three different boxes, with only two that appear in game, the standard vial box that contains 6 vials and requires medical access to open, the blood sample box that's just a renamed vial box, and the virology vial box which contains six vials, four empty, one that contains the could virus and one that contains the flu.

Blood sample vial boxes have been added to the mining base and the brig infirmaries on box, delta, and meta, and the virus box has been added to the virology lab on those same maps

image

# Wiki Documentation

May need to mention the new boxes, but its not that important. 

# Changelog

:cl:  
rscadd: Added vials and vial lockboxes
/:cl:

### CODE REVIEW

**Review by adamsong — APPROVED** [review]

**Review by patpol4 — APPROVED** [review]
Looks ok, just fix conflict and it's good to go

**Comment by nmajask** [comment]
> Looks ok, just fix conflict and it's good to go

think its fixed

**Comment by nmajask** [comment]
it is not fixed

**Comment by nmajask** [comment]
there, now its fixed

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
