### PR TITLE
Makes crew monitor venry smol

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Crew monitor no longer taking up your entire screen on rounds with more than 20 people

# Changelog

:cl:  
tweak: Made crew monitor UI more compact
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
god bless the lines
don't suppose you can add some form of zebra striping while you're at it?

**Comment by ToasterBiome** [comment]
if we're doing smaller font can you use one that looks less terrible on smaller sizes on the ntos one

**Comment by ynot01** [comment]
i was unable to achieve zebra stripes

**Comment by ShoziOffical** [comment]
🎉

**Comment by Burger1998** [comment]
would it be possible to make the columns more discernible by making them cycle between lighter a darker?

**Comment by Moltijoe** [comment]
> would it be possible to make the columns more discernible by making them cycle between lighter a darker?

that's zebra striping, already said he was incapable of adding it

**Review by Moltijoe — APPROVED** [review]
Visibility is greatly appreciated

**Pull request merged**
