### PR TITLE
Gives preternis universal bloodtype

### PR DESCRIPTION
**Pull request by Moltijoe**
Stable plasma was boring, it was too stable, and made them yet another species that was immune to bloodsucker and vampire
This instead gives them a universal bloodtype that can be donated to anyone

:cl:  
tweak: Gives preternis universal blood type instead of stable plasma
tweak: Universal blood type is universal donor, in addition to recipient
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
So. Is this o neg blood or is this a new chem that they have

**Comment by Moltijoe** [comment]
> So. Is this o neg blood or is this a new chem that they have

this is a special blood type that's literally every blood type (including lizard)
other PR was a new chem, but the code was shitty and basically did exactly this

**Comment by wonderinghost** [comment]
Can't o negative transfuse with lizards? Because if not then yeah this is neat

**Comment by Cartlord** [comment]
i do not like them being able to just ignore the blood type system

**Comment by Moltijoe** [comment]
> i do not like them being able to just ignore the blood type system

just drain all their blood for yourself and you can too

**Comment by MajManatee** [comment]
consider
saline

**Comment by wonderinghost** [comment]
Saline isn't permanent though

**Comment by MajManatee** [comment]
I'm saying make their blood saline instead of universal

**Comment by Moltijoe** [comment]
> I'm saying make their blood saline instead of universal

Thats not a terrible idea

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
