### PR TITLE
Rebe change very controversial (Poland)

### PR DESCRIPTION
**Pull request by Readystorm546**
So like i want to change clock cult to make it more "fun" and though hey what can we change to make this more "fresh" Well make it so clock cult has to defend 360 degree. Yeah this seems dumb but hey it could be fun. Who the hell knows.

ezgif com-optimize

This gif is weird for some reason but just know that the + goes clock wise around while moving. Also for those who dont know this replaces that arrow that is at the south of the current clock cult base.

image

The Center of the clock area

Clcok gif

A rough look at the outline around the base. Its about 10 tiles between the outside of the inner circle and the circle to where the culties can build.

🆑
rscadd: >whole new 360 clock cult map.
rscadd: >Changed arrows to a + so it makes more sense with this update.
rscadd: >Changed the clock cult paper to match the new map.
/🆑

### CODE REVIEW

**Comment by Szyszkrzyneczka** [comment]
Speedmerge when
oh wait travis said no
sad

**Comment by Readystorm546** [comment]
TRAVIS WILL SAY YES ONE DAY

**Comment by Szyszkrzyneczka** [comment]
this is not the day

**Comment by Readystorm546** [comment]
TRAVIS HAS DONE IT

**Comment by MegaEmpirical** [comment]
Do invaders start behind the pre-made wall that requires tools or internal to it?

**Comment by Readystorm546** [comment]
Yes but if your not coming into rebe without tools your not doing it right

**Comment by Xoxeyos** [comment]
Where would the sigils to convert be?

**Comment by Nickvr628** [comment]
my concern is that this would end up being a huge nerf to clock cult because of the added difficulty of defending an entire circle.

**Comment by Readystorm546** [comment]
> Where would the sigils to convert be?

You put the the vigil where ever you want so. you choose


> my concern is that this would end up being a huge nerf to clock cult because of the added difficulty of defending an entire circle.

This i think could be true but i would have to see it play out to know for sure. I think the crew would also be nerfed as they are dumb and cant coordinate anything

**Comment by nesisknesis** [comment]
Was this change even discussed on whether it would be viable? From this PR it just seems you've created it for the sake of changing something. I haven't been active lately but may you say why this change is good and what balance it may affect.

**Comment by Readystorm546** [comment]
> Was this change even discussed on whether it would be viable? From this PR it just seems you've created it for the sake of changing something. I haven't been active lately but may you say why this change is good and what balance it may affect.

Clockies have been in the "news" and i have been trying to make them more playable and or enjoyable. Having said that. i have no idea if this will be good or not. After all it could be a flop and should probably be tesrmerged before anything else.

**Comment by Amelia0010** [comment]
image

I'll decide between these two tomorrow

**Comment by monster860** [comment]
This PR reduces Reebe to the equivalent of Poland.

**Comment by Nickvr628** [comment]
Clock cult has a difficult enough time defending one direction because of the two-dozen methods the crew has to cheese their defenses. Making it 360 means they have to build a lot more defenses and the defending cultists are super spread out.

I don't even know if it is possible for the cult to have enough resources and time to build competent defenses all the way around. It is a neat idea, but I see this nerfing an already-weak clock cult.

**Comment by Amelia0010** [comment]
This PR has been testmerged based on maintainer feedback.

**Comment by Ratvar** [comment]
Could anyone say what said feedback was? You know, so everyone knows why they think this map is better then others.

**Comment by ghost** [comment]
There's not enough space to give breathing room for the attackers, adding the attacker rooms to North, south, west and east would be a great change, since even with the walls, the judical visor leaves about 1-2 tiles of space of breathing room.

**Comment by Readystorm546** [comment]
> There's not enough space to give breathing room for the attackers, adding the attacker rooms to North, south, west and east would be a great change, since even with the walls, the judical visor leaves about 1-2 tiles of space of breathing room.

i like this idea

**Comment by Readystorm546** [comment]
So this is what i added

image

This is the new crew spawner location  as requested by @Trustback 

There is one on the north south east and west

The picture is of the west one

I should mention the other spawn points were removed

**Comment by Ludox235** [comment]
So by the name change I assume the cult got absolutely destroyed?

**Comment by Readystorm546** [comment]
> So by the name change I assume the cult got absolutely destroyed?

Funny enough as far as i know its at one win and one loss

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
