### PR TITLE
moves maps out of the maps/yogstation folder, and removes duplicate tg maps

### PR DESCRIPTION
**Pull request by Amelia0010**
Big scary PR, almost 1M lines changed, 80 files changed.

Basically, deleted duplicate TG maps that we have yogs versions of, like boxstation, deltastation, etc., and moved all the lava & space ruins from the yogstation folder to the normal folder

### CODE REVIEW

**Comment by Nickvr628** [comment]
Why wouldn't you leave the files in the yogs specific folder? It makes it easier to port stuff. Even though modulization is no longer required it is still nice to follow the rules for future PRs and such.

**Comment by Amelia0010** [comment]
how does it make it easier to port stuff?

**Comment by alexkar598** [comment]
Ignore Nick he's special

**Comment by Amelia0010** [comment]
Also, several reasons why this is a good thing:
1. less confusion over which template is in-use, since duplicates no longer exist
2. we don't have to maintain 2 copies of several ruins or travis'll assassinate us
3. travis now actually checks the ruins which we added, since they're in the correct folder

Additionally, keeping the TG versions around no longer serves a purpose since the mirrorbot isn't there anymore, so we won't have any forced map edits.

**Comment by MayhemSailor** [comment]
I'm excited for this one.

**Comment by Amelia0010** [comment]
watch this break everything

**Pull request merged**
