### PR TITLE
Honker blast knockdown 

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Clown mech Honkerblast 5000 will no longer hard stun you, and instead knocks you down.
It does still have the 30% chance to knock you out, which DOES still stun you, but that's different, sorta.

Also halves the stun timer for the knock out that occurs. Sorta makes sense that when you are woken up from being knocked out, you don't just jump up right away.

# Changelog

:cl:  
tweak: clown mech Honkerblast hard stun -> not hard stun
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
don't suppose you could swap it to check for `/datum/component/wearertargeting/earprotection` instead of specifically earmuffs?

**Comment by MajManatee** [comment]
Its supposed to only target ear muffs. Bowmans arent enough to stop it

**Comment by Moltijoe** [comment]
> Its supposed to only target ear muffs. Bowmans arent enough to stop it

at least make bowmans mitigate it then, what's the point of wearing hearing protection if it doesn't protect your hearing

**Comment by MajManatee** [comment]
No that's dumb as hell.
Propose made headphones to reduce noise are NOT the same as an over-ear headset.
There's a reason people wear big ear muffs when they work around loud noises (Airport jets, Concerts, Factories, Sawmills, Etc) instead of fuckin razor headphones

**Comment by Moltijoe** [comment]
> No that's dumb as hell. Propose made headphones to reduce noise are NOT the same as an over-ear headset. There's a reason people wear big ear muffs when they work around loud noises (Airport jets, Concerts, Factories, Sawmills, Etc) instead of fuckin razor headphones

the earmuffs we have in game aren't noise cancelling, they're the fuzzy kind meant for cold weather

**Comment by MajManatee** [comment]
> > No that's dumb as hell. Propose made headphones to reduce noise are NOT the same as an over-ear headset. There's a reason people wear big ear muffs when they work around loud noises (Airport jets, Concerts, Factories, Sawmills, Etc) instead of fuckin razor headphones
> 
> the earmuffs we have in game aren't noise cancelling, they're the fuzzy kind meant for cold weather

we have the noise cancelling ones. Theres a pair that spawns in RnD on box above the AI secondary core, and they can be printed from auto laithes. I have never once seen cold-weather ones.

**Comment by Moltijoe** [comment]
> we have the noise cancelling ones. Theres a pair that spawns in RnD on box above the AI secondary core, and they can be printed from auto laithes. I have never once seen cold-weather ones.

huh, maybe i'm blind, lemme go check
edit: yup, blind, they're bright red and everything, no clue why i always thought they were the cold-weather kind

still, at least making bowman headsets reduce the duration of the cc rather than outright negating it would surely be a reasonable change

**Comment by MajManatee** [comment]
no

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
