### PR TITLE
Reinforced cheese, Cheese golems, Cheesus Statue

### PR DESCRIPTION
**Pull request by missatessatessy**
Adds reinforced cheese, cheese golems and the Cheesus statue.

Reinforced cheese is made by using a welding tool on a cheddar wheel, the result can be used to craft the Cheesus statue or make a cheese golem from a golem shell.
I have further plans for reinforced cheese but I wanna get the few things I had done already out there.

cheese stack3
cheese1

:cl:  
rscadd: Added reinforced cheese, cheese golems, and the Cheesus statue
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Are you able to eat the statue?
Can you eat the reinforced cheese? Maybe give a message saying that it's too hard to chew or something.
Also maybe add more cheese names to the special golem names list.
Are mice able to just oneshot the golem and statue since they eat the entire food at once?

**Comment by missatessatessy** [comment]
> Are you able to eat the statue?
> Can you eat the reinforced cheese? Maybe give a message saying that it's too hard to chew or something.
> Also maybe add more cheese names to the special golem names list.
> Are mice able to just oneshot the golem and statue since they eat the entire food at once?

Can't eat the statue, can't eat the reinforced cheese (it isn't a food type), names can be added at a later date, and mice cant eat the statue/golem, because they aren't food.
This is by no means a final iteration of this stuff, I just wanna get something out there that works xD

**Review by Partheo — APPROVED** [review]

**Comment by Marmio64** [comment]
fucking amazing PR

a suggestion though: Let cheese golems click themselves with reinforced cheese in order to heal themselves, perhaps they must stand still for a few seconds, can only heal with one piece at a time, and heal 20 health.

**Comment by ilikesaying** [comment]
reinforced cheese tiles

**Pull request merged**
