### PR TITLE
Bouncer gun now shoots freezer balls instead of suffocating balls

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Anoxia balls were in this very strange balance state where it was seemingly very strong because you can't recover oxygen damage very quickly or without advanced medicine but also it takes 10 of your 17 shots without missing once to down a person and applies no damage slowdown.

For this, I say fuck anoxia balls, and we create a new hybrid gun that shoots freeze beams.

Freeze balls take 250 energy to shoot. That is 1/4 of your clip. Shoot wisely. Your teammates will also HATE you if you hit them. Have fun!

Also I renamed the old energy gun sprites so it's no longer a duplicate and won't show up when people are mapping, as well as created a gun that uses that sprite for shits and giggles.

Will need buffs once the temperature gun nerfs come through

# Changelog

:cl:  
tweak: The bouncer energy gun now shoots freeze balls instead of suffocating balls
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Printable sec temp gun, pretty cringe imo

**Comment by 00ze-cyclone** [comment]
> Printable sec temp gun, pretty cringe imo

my lizard in christ there's literally the design to print the temp gun in the beam weaponry node where you get the bouncer design.

**Comment by ReddicusDragon** [comment]
image
balance council approved

**Review by Moltijoe — APPROVED** [review]

**Review by cuackles — APPROVED** [review]
files do be changed but they do be basically the same

**Pull request merged**
