### PR TITLE
[READY][AI] Reworks AI CPU + RAM. Turns the Sig Tech into the Network Admin. Adds overclocking

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

### Racks
Instead of inserting CPU & RAM cards into the Expansion Card Holder you now combine printed CPUs with RAM in the "rack creator" to build a rack to insert into the card holder. The CPUs are printed and are physical objects, while the RAM is printed and instantly attached to the rack by the rack creator.
image

Upgraded base CPUs and RAM is unlocked through normal science. Uses special points made by AIs dedicating leftover CPU to research.
Racks are also only able to hold 1 CPU and 1 RAM at the start and require architecture upgrades. These are global and instantly unlocked when researched. Uses same system as CPU and RAM.

### Overclocking
Adds a new console, the overclocking workstation.
Here you'll be able to increase clock speed at the cost of power efficiency.
This is done as a "minigame" where you try to maximize clock speed with the lowest power multiplier.
All CPUs are different and therefor have differing overclocking statistics. Some CPUs will be able to be overclocked at high speed at low power, while others will require lots of power to reach maximum speed. Some can't even draw enough power to reach max speed.

### The Network Admin
The Signal Technician has now been renamed to the Network Admin
Their new duties are taking care of the AI by upgrading it using the above system, and making sure all of its cores are working.
They retain their old access to NTSL. They now have access to the AI core on Box

### Misc
AI server overview now tracks AI data cores too, (area + coords + temp + status)
Allows AI to assign fractional CPUs since we have fractional CPU power from overclocking.
(Additionally fixes off-station downloading and AI hijacking)

## TODO

- [x] Add a circuit imprinter for the netmin so they don't have to walk so far
- [x] Finish rack creator
- [x] Make CPUs printable
- [x] Overclocking machine
- [x] New researches. (AI research points + integration with above)
- [x] Make AI able to generate new points
- [x] Ensure fractional CPU works
- [x] Sig Tech -> Sys Admin
- [x] Rename Expansion Card Buses
- [x] Rework the buses/servers
- [x] proper changelog 
- [x] Upgrades for rack creator like normal fabricators
- [x] Examine to see overview of rack
- [x] Fractional CPU in the resource distribution thing
- [x] Final test for overclocking

# Wiki Documentation

See above

# Changelog

:cl:  
rscadd: The Sig Tech has been renamed to Network Admin and is now in charge of general AI upgrades
rscadd: The Network Admin can combine CPUs and RAM to create racks to upgrade the AI, instead of using individual cards.
rscadd: This is done using the new rack creator machine. You insert printed CPUs and then add RAM sticks. Then you finalize and it will print the full rack.
rscadd: The AI is now upgraded by inserting server racks into expansion card holders (Now called server cabinets)
rscadd: The Network Admin can now overclock CPUs in their workshop. Increase the speed as much as possible while minimizing the power draw!
rscadd: Adds up to tier 3/4 AI hardware, unlockable through Research.
tweak: AI cpu now works off of percentage, adds support for fractional CPU speeds (Overclocking)
bugfix: Fixes off-station hijacking and downloading of the AI
/:cl:

### CODE REVIEW

**Comment by Altoids1** [comment]
many good commit names, such as `e`

**Comment by Bibby0110** [comment]
> many good commit names, such as `e`

agreed

**Comment by JamieD1** [comment]
Can you make sure that this does not have a negative effect if there is no netmin ie low pop.

**Comment by Bibby0110** [comment]
> Can you make sure that this does not have a negative effect if there is no netmin ie low pop.

Nothing about the roundstart balance changes.
A round without a netmin will play out exactly like a round does now without the PR

**Comment by JamieD1** [comment]
Please fix compile

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Can merge when art approved

**Comment by Bibby0110** [comment]
Merge conflicts.
Not going to deal with them

**Pull request merged**
