### PR TITLE
Adds Access to Warden for infirmary but Prevents access to sleeper.

### PR DESCRIPTION
**Pull request by JamieD1**
# Document the changes in your pull request

People have disagreements whether warden should be allowed into infirmary.

There are two arguments, one for access for security purposes and one for medical purposes.

Due to the fact the whole point of medical physician is designed to be in the brig doing medical duties they should obviously be the first point of call.

The second argument about security of the brig is agreeable, so this should be the best of both worlds, giving the warden what he had before but hopefully meaning brig physician can still be relevant without warden overstepping.

# Changelog

:cl:  
tweak: Changed access to brig physician room and denied to sleeper in room.
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Someone may need to check if access on the sleeper works as I have intended.

**Comment by Cartlord** [comment]
Should he get sleeper access at skeleton crew? I myself am not sure, but I figure it's worth proposing.

**Review by adamsong — CHANGES_REQUESTED** [review]
Update at least meta and kilo to include this, and its "5;3" not "5,3" for multiple accesses.

**Comment by maxion12345** [comment]
this works
wardens can at minimum vend some patches from the nanomed to heal people but those are a limited supply item
at least prisoners will be able to get healed

**Comment by bruhlookatthisdood** [comment]
every day i wake up, hoping for this to be merged
every day i cry.

**Comment by patpol4** [comment]
Stale, reopen if conflicts get fixed

**Pull request closed without merging**
