### PR TITLE
Adds pride jackets

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Adds pride jackets! Coming soon to a hacked clothing vendor near you.

#20185 should be merged first to prevent conflicts.

# Spriting

image
Sprites made by Cuackles, slightly edited by me.

# Changelog

:cl:  @cuackles, @SapphicOverload
rscadd: adds pride jackets to hacked clothing vendors
imageadd: pride jackets
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Them being contraband means you can be arrested for being gay. 

Id like to see them either regular items, or donator items (or maybe both). Maybe only sell the rainbow one normal and the rest a contraband? A bit too on the nose? 

I’ll sprite review these soon.

**Comment by neeshacark** [comment]
my blessed MLM hoodie that I couldn't have as a personal donor item due to the oppressive council refusing to allow any more unique donor items shaking my smh

can i flex due to the concept being my idea and ask you to make them donor items + regular items

**Comment by MajManatee** [comment]
im no spriter but something about them looks... off

**Comment by ToasterBiome** [comment]
> im no spriter but something about them looks... off

Explain further

**Comment by cuackles** [comment]
> > im no spriter but something about them looks... off
> 
> Explain further

No no they are right, some of the ways I put the color make some of the jackets look just off, not well integrated, I will eventually get to fixing it I just keep forgetting or not having the time

**Comment by ToasterBiome** [comment]
Reopen when Cuackles does the stuff

**Comment by cuackles** [comment]
> Reopen when Cuackles does the stuff

The stuff is done the pr just needs updating

**Comment by iamthesilly** [comment]
We're so back

**Comment by cuackles** [comment]
> We're so back

😎

**Review by ToasterBiome — APPROVED** [review]
lol gay

**Comment by Hislyna** [comment]
I still think making them contraband sends the wrong message

**Pull request merged**
