### PR TITLE
Increase run speed slightly

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

QOL life. Everyone likes going faster, but when we walk right now it's very very sluggish. Especially if you're hungry - it compounds into an awful experience to where you can't get anywhere. I believe some people have been trapped in between firelocks because they cant move fast enough for the firelock to stay open. There's no reason for speed to be THIS slow anymore ever since we did a ton of performance fixes.
# Spriting

# Wiki Documentation

Run speed goes from 2 to 1.7, walk from 6 to 5
# Changelog

:cl:  
tweak: Run speed goes from 2 to 1.7, walk from 6 to 5
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
what if we didnt

**Comment by ynot01** [comment]
tg player

would require testmerge before actual merge

**Comment by ToasterBiome** [comment]
I don't like going fast, I think the movement on other servers that are faster is weird. I think yogs is a good speed. I don't know why you're so hungry all the time and suffer from the slowdown so often, just eat

**Comment by Simplehorror** [comment]
our current run speed is what walking speed should be

**Comment by ToasterBiome** [comment]
> our current run speed is what walking speed should be

no

**Comment by Cartlord** [comment]
I'm not a fan of this idea. I've already had scenarios where people can steal shit or break into somewhere and leave before Sec can even be called, and I think this'd just make it worse.

**Comment by Simplehorror** [comment]
so just report their name, if they can do it now they can still do it after this

**Comment by Moltijoe** [comment]
A lot of things are currently balanced around current speeds
This would cause problems
not to mention, the game can only handle things going so quickly, so it would reduce the effectiveness of stacking speed boosts

**Comment by Simplehorror** [comment]
> A lot of things are currently balanced around current speeds This would cause problems not to mention, the game can only handle things going so quickly, so it would reduce the effectiveness of stacking speed boosts

a lot of things are balanced around tg speed too

**Pull request closed without merging**
