### PR TITLE
Removes sheltered quirk

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Sheltered isn't good for the game, it gives people an excuse to completely avoid conversation
if you want to be quirky and have difficulty speaking, there is ineloquent and social anxiety

:cl:  
rscdel: sheltered quirk
/:cl:

### CODE REVIEW

**Comment by ThatGuyPhil** [comment]
ah yes, the 'remove x i dont like' pr

**Review by JamieD1 — APPROVED** [review]
Fuck yes, literally the best pr in the fucking world, please merge this, I hate cringelords using this as an excuse to be a snowflake cringe twat who uses the excuse of sheleted to not even try and talk to people.

**Comment by ThatGuyPhil** [comment]
I have never seen a single person do this, except for lizardpeople maybe. Also multilingual perks exist too. All this will achieve is that sheltered enthusiasts will just find another -2 trait and set their default language to non-common.

**Comment by neeshacark** [comment]
I think you're looking at this the wrong way, I use sheltered because it's fun to have a reason to try to communicate in ways other than speaking.  I've had a lot of fun with communicating via emotes, in much the same way as playing mime without actually being restricted to one role like you are as mime.

**Comment by Therandomhoboo** [comment]
I mean yeah its annoying but I don't think its that big of an L to warrant this. Some people rp sheltered well, others dont. I think its a non-issue really.

**Comment by iloveloopers** [comment]
Let people enjoy things

**Comment by Moltijoe** [comment]
> Let people enjoy things

i hope you realize how terrible that argument is

**Comment by N3D6** [comment]
Always hated this trait please be based molti

**Pull request closed without merging**
