### PR TITLE
Some detective gear is no longer invisible

### PR DESCRIPTION
**Pull request by Moltijoe**
# Testing
trust me, i ALWAYS test my prs
forensic

:cl:  
bugfix: Some detective gear is no longer invisible
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
image

that looks weird

**Comment by Moltijoe** [comment]
> image
> 
> that looks weird

that's how it's supposed to be, idk

**Review by MajManatee — DISMISSED** [review]
No way those gloves are SUPPOSED to have that rogue white pixel

**Comment by Moltijoe** [comment]
> No way those gloves are SUPPOSED to have that rogue white pixel

bro, you dumb? that's out of scope, that's always been an issue

**Comment by MajManatee** [comment]
not out of scope to remove a single pixel

**Comment by Moltijoe** [comment]
> not out of scope to remove a single pixel

it IS out of scope, this doesn't edit a single icon, editing an icon would require sprite approval

**Comment by MajManatee** [comment]
I believe in you :)

**Review by Chubbygummibear — APPROVED** [review]
cark told me to

**Comment by neeshacark** [comment]
i must have my det drip

**Pull request merged**
