### PR TITLE
makes yogstation EXTREMELY BASED

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Github documenting your Pull Request

Bridge and captain's and hos office are now clockcult protected areas no more sniping the captain idiots
Captain's office maint is now half plated with reinforced walls and the bathroom is fully reinforced with reinforced walls to make it harder to get to the captain's ❤️bedroom❤️ because they aint a beta
Armory has been flipped like a coin and it landed on tails, guns are on the inside useless crap is on the outside, armory has also been put through a coin press and is flatter since it needs less space to exist now, also the barrier between the outer and inner armory is now SUPER REINFORCED

image

# Changelog

:cl:  
tweak: [box] bridge and cap/hos offices are now clockcult proofed fuck you fuck yuo fucmk you
tweak: [box] captain's bedroom is now properly reinforced to prevent interruptions
tweak: [box] armory guns are on the inside
tweak: [box] sec has some more reinforced walls on the outside
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Good PR.
Undocumented changes of reinforcing the right-side of the sec area connecting to airlocks.

**Comment by Hopekz** [comment]
Good PR.
Imo you're overstating the captain office changes in the changelog so someone that doesn't actually look at the map won't know that all you're doing is replacing the bathroom walls with reinforced.

If you just read your changes it sounds like you added a whole other layer or two of reinforced walls

**Comment by LoliconSlayer** [comment]
Based

**Comment by patpol4** [comment]
Was the reinforcement with thindows next to the outer wall in the armory intentional, because if not I see no reason for them to stay since they look really bad.

**Comment by SomeguyManperson** [comment]
removed all the spare windows in the outer room

**Comment by Xoxeyos** [comment]
I think these changes will limit how the players want to change the brig, I don't believe the Captain's bathroom, or the brig really needs this change. It's difficult enough to get in as it is. In exchange for this PR, I'd think re-adding tasers would help, and it'd make things more enjoyable for security, rather than the mundane walls and windows being slightly harder to break into.

**Comment by SomeguyManperson** [comment]
> I don't believe the Captain's bathroom, or the brig really needs this change.

Yes, they do

> It's difficult enough to get in as it is.

No, it isn't

> I'd think re-adding tasers would help

No, they won't

> It'd make things more enjoyable for security

No, it won't

**Comment by maxion12345** [comment]
new armory for those that cannot be fucked to look at the checks

as for impressions, flat armory with 1x1 hallway is going to be a bitch to arm up in, but I like the idea of having the riot gear one shutter away in case you need to go curbstomp some greysuits

**Comment by Marmio64** [comment]
i think armory should just get a turret instead of all the other stuff and have it be called a day

**Comment by SomeguyManperson** [comment]
> i think armory should just get a turret instead of all the other stuff and have it be called a day

no that's "powergaming" and "against the rules" - no fun allowed police

**Comment by SomeguyManperson** [comment]
armory has been de-flatfuckified

**Review by patpol4 — CHANGES_REQUESTED** [review]
vivaldi_YAtp1FLyIg
Was there any intent behind putting the red decal here? if not move it to lethal rounds because it makes sense to colorcode it, also the middle two decals are missing.
Other than that I don't really agree with putting the shutter in the lower room but you play the game more so yeah balance is up to you.
Rest looks good.

**Comment by Bibby0110** [comment]
literal hugbox

**Review by patpol4 — CHANGES_REQUESTED** [review]
The change for the captain quarters has been rightfully atomized in #12054.
Please remove it here.

**Pull request closed without merging**
