### PR TITLE
Recenters some sprites

### PR DESCRIPTION
**Pull request by Partheo**
ACCIDENTALLY MADE THE BRANCH HERE INSTEAD OF ON MY FORK, I APOLOGIZE AND WILL CORRECT THAT IN THE FUTURE

Tiny PR, just recenters some hydro sprites. It was the first on the list here so I did it quickly. https://docs.google.com/document/d/12ZcilWRyf1rSKvs-zfD4g2--_6RyEk1vVP4wZKuY53M/edit?usp=sharing

image

Original PR is here. Teddy doesn't exist so I didn't recenter it.
https://github.com/yogstation13/yogstation/pull/2722

### CODE REVIEW

**Comment by Amelia0010** [comment]
Wouldn't it be better to add a seperate DMI in the yogs folder and then set the icon of the object to whichever DMI you used?

**Comment by Partheo** [comment]
@nichlas0010 
Given how quick of a fix this is, I think changing the icon for all of these objects would be even more prone to errors in the future. I'll keep my eye out for if ever this file gets changed again.

**Comment by Amelia0010** [comment]
if you say so /shrug/

**Comment by Amelia0010** [comment]
oh and noone minds you making branches here rather than on your own fork, I do it for webedits so 🤷‍♂️

**Pull request merged**
