### PR TITLE
[""""BUGFIX"""] Makes it so you cannot have infinite money selling syrup from cargo after ordering it. 

### LINKED ISSUE #21178: You can print infinite money with coffee syrups.
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: You make 700 credits back with the manifest and crate, and you get both a crate and manifest with coffee syrups. The coffee syrups crate in cargo costs 200 credits. not a bug, but still a potential flaw

 Submitted by: englishscotsman (740223180806946946)

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Adjusts the price of the syrup crate from 200 to 1400, because we can't have nice things. Ever.

Closes https://github.com/yogstation13/Yogstation/issues/21178

# Changelog

:cl:  

bugfix: removes infinite money in the form of syrup

/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
Let people enjoy things 🤓🤓🤓

**Comment by Runian** [comment]
Closes #21178?

**Comment by cowbot92** [comment]
> Closes #21178?

yes

**Comment by Runian** [comment]
can you put it in so it autocloses the issue

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
