### PR TITLE
Removes half broken mime ability

### LINKED ISSUE #2453: Invisible touch doesn't work
```
runtime error: Cannot create objects of type null.
proc name: ChargeHand (/obj/effect/proc_holder/spell/targeted/touch/proc/ChargeHand)
  source file: touch_attacks.dm,40
  usr: Big Booty (/mob/living/carbon/human)
  src: Invisible Touch (/obj/effect/proc_holder/spell/targeted/touch/mime)
  usr.loc: the floor (113,112,2) (/turf/open/floor/plasteel)
  src.loc: null
  call stack:
Invisible Touch (/obj/effect/proc_holder/spell/targeted/touch/mime): ChargeHand(Big Booty (/mob/living/carbon/human))
Invisible Touch (/obj/effect/proc_holder/spell/targeted/touch/mime): cast(/list (/list), Big Booty (/mob/living/carbon/human))
Invisible Touch (/obj/effect/proc_holder/spell/targeted/touch/mime): perform(/list (/list), 1, Big Booty (/mob/living/carbon/human))
Invisible Touch (/obj/effect/proc_holder/spell/targeted/touch/mime): choose targets(Big Booty (/mob/living/carbon/human))
Invisible Touch (/obj/effect/proc_holder/spell/targeted/touch/mime): Click()
Invisible Touch (/obj/effect/proc_holder/spell/targeted/touch/mime): Click()
Invisible Touch (/datum/action/spell_action/spell): Trigger()
Invisible Touch (/obj/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=17;icon-y=16;left=1;scr...")
```

https://github.com/yogstation13/Yogstation-TG/blob/master/yogstation/code/modules/spells/spell_types/mime.dm#L4

``/obj/item/weapon/melee/touch_attack/nothing`` doesn't exist and wasn't ported over.

### PR DESCRIPTION
**Pull request by alexkar598**
Fixes #2453

### CODE REVIEW

**Comment by Hopekz** [comment]
Not a bugfix. 
------
You're straight up removing the feature instead of fixing it tf kind of lazy "bugfix" is this?
while you're at it "bugfix" secborgs

**Review by monster860 — CHANGES_REQUESTED** [review]
Get a better title

**Comment by MegaEmpirical** [comment]
Still says fix

**Review by ThatLing — CHANGES_REQUESTED** [review]
What Hopekz said, this is not a fix

**Comment by alexkar598** [comment]
What is the fix for a half ported feature? As it stands it's broken, adding it in would be a feature, removing a skeleton is a fix

**Comment by ThatLing** [comment]
Deleting broken code isn't a "fix". I guess adding it in is a feature then. Doesn't change the fact that this is a shitty PR

**Comment by boodaliboo** [comment]
lol

**Comment by Hopekz** [comment]
As I see it this feature was intended to work when it was first merged.

I do not see your "not a feature yet" argument because we don't merge half finished features. We add WIP to them or close them if the project is left unfinished.

The way to bugfix this would be to ensure it works per the original intent of it being added to the game (:

This is a removal.

**Comment by alexkar598** [comment]
Lets keep broken code in the codebase cant go wrong

**Pull request merged**
