### PR TITLE
Gives some new spawn in sounds to clown ERT and clownops

### PR DESCRIPTION
**Pull request by swissloaf**
Gives some new spawn in sounds to 

Clown Ops, HONK Squad, The Circus ERT: https://www.youtube.com/watch?v=PcRyjkYdDxM (not entire song, like first 8-16 seconds)

#### Changelog

:cl:  
rscadd: Adds new spawn in sounds for some antags
soundadd: Adds new sounds
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Clown ops intro sounds decent, but I don't like any of the other sound effects.

**Comment by Hopekz** [comment]
The amber/death squad one is weird (the song ends as it finally builds up)
The ERT one fits but sounds more like it would be amber's theme since it is a soldier like feel.

**Comment by Partheo** [comment]
> 
> 
> Clown ops intro sounds decent, but I don't like any of the other sound effects.

Agreed with this. Clown ops is immersion breaking enough on its own that the amusing into music is warranted (also it's a great track.)

The other two just feel out of place and needlessly "epic"... I don't think they need any introduction at all, it's not like there's going to be music playing on the station speakers anyway.

**Comment by swissloaf** [comment]
> > Clown ops intro sounds decent, but I don't like any of the other sound effects.
> 
> Agreed with this. Clown ops is immersion breaking enough on its own that the amusing into music is warranted (also it's a great track.)
> 
> The other two just feel out of place and needlessly "epic"... I don't think they need any introduction at all, it's not like there's going to be music playing on the station speakers anyway.

cant have shit in detroit

**Comment by swissloaf** [comment]
> > Clown ops intro sounds decent, but I don't like any of the other sound effects.
> 
> Agreed with this. Clown ops is immersion breaking enough on its own that the amusing into music is warranted (also it's a great track.)
> 
> The other two just feel out of place and needlessly "epic"... I don't think they need any introduction at all, it's not like there's going to be music playing on the station speakers anyway.

fixed

**Review by Partheo — APPROVED** [review]

**Pull request merged**
