### PR TITLE
MultiZ lavaland

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Adds an additional lavaland level

 - [ ] Make this a little less shitcodey
 - [ ] Add a way up
 - [ ] Fix bugs
 - [ ] Probably add elevator to mining station
 - [ ] Make chasms delete any walls below them

# Changelog

:cl:  
rscadd: New lavaland layer
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
Godspeed, you madman

**Comment by Marmio64** [comment]
not sure miners need double the amount of possible powergame loot from ruins and megafauna, unless ruins and stuff are going to be split half and half between them rather than an increase.

**Comment by MenacingManatee** [comment]
> not sure miners need double the amount of possible powergame loot from ruins and megafauna, unless ruins and stuff are going to be split half and half between them rather than an increase.

Worth noting that people have been going through the ruins and replacing the powergame loot with less egregious alternatives

**Comment by Marmio64** [comment]
> > not sure miners need double the amount of possible powergame loot from ruins and megafauna, unless ruins and stuff are going to be split half and half between them rather than an increase.
> 
> Worth noting that people have been going through the ruins and replacing the powergame loot with less egregious alternatives

twice the amount of mediocre powergame loot is still just that, so im still not in full agreement with it.

**Comment by maxion12345** [comment]
port /tg/ multiz when

**Comment by redmoogle** [comment]
It'd probably be 10x easier to restart the multiz port and remove crap from there

**Pull request closed without merging**
