### PR TITLE
Fixes the virology machine bluescreen

### PR DESCRIPTION
**Pull request by ReddicusDragon**
# Document the changes in your pull request
Solves #17320 by replacing Pandemic.js with Pandemic.js ([stolen mercilessly from TG](https://github.com/tgstation/tgstation/pull/65050))
# Changelog

:cl: ReddicusDragon, ThatLing, and JamieD1
bugfix: The virology machine no longer bluescreens
experimental: Pandemic bluescreen fix is experimental. Please report any bugs!
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
a simple 600 lines of code for a bugfix

**Review by MajManatee — APPROVED** [review]

**Review by ynot01 — CHANGES_REQUESTED** [review]
Vaccines show up as "Nothing detected." on PanDEMIC

**Comment by ReddicusDragon** [comment]
> Vaccines show up as "Nothing detected." on PanDEMIC

No clue how to fix it. Ling told me to do this to fix the blue screen. I don't know TGUI 🤪

**Comment by Moltijoe** [comment]
> No clue how to fix it. Ling told me to do this to fix the blue screen. I don't know TGUI 🤪

does that mean another PR should be made to fix the pandemic after this gets merged, or should that be incorporated into this PR

**Comment by ReddicusDragon** [comment]
Probably be fixed in this one. I'll see if I can bother Ling into helping me out

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
