### PR TITLE
Particle accelerator emag update

### PR DESCRIPTION
**Pull request by Readystorm546**
So pretty much you go up to the control console of the PA and emag it. This sets the strength to +4. If someone is fast enough they can revert it but if your not quick enough this will most likely cause a loose goose. I also tested it everything works fine and on top of that i made new sprites to identify that this is a +4 PA.
I wanted to add this because theos once told me you could do this but he lied and so i made it happen.

### CODE REVIEW

**Comment by AsV9** [comment]
Idea: good
sprite: bad

**Comment by Readystorm546** [comment]
there is a reason im not a spriter

**Comment by nesisknesis** [comment]
I can look into making a better sprite

**Comment by Readystorm546** [comment]
Sure then you can add it or something i dont know how it works

**Comment by Nickvr628** [comment]
Maybe if you had the outline pulse different brightnesses, as if the extra energy was making it glow and flash, it would be better.

Would not be that hard to do either.

**Pull request merged**
