### PR TITLE
(Hopefully) Improves Goat King arena

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Expands and (hopefully) improves goat king arena.
Made it a round arena with a few "pillars" that exist to hide line of sight/hide behind. Hope this is an improvement

goatkingfix

# Spriting

# Wiki Documentation

# Changelog

:cl:  

mapping: Goat King arena is now round with pillars

/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
realized a small error lemme fix

**Comment by thegoldencat413** [comment]
more space = good, because goat king is actually a tad slower than you

**Comment by solwashere** [comment]
fixed

**Review by Aquizit — APPROVED** [review]
It's wild even how with debug tools to test shit out how hard that things hits.

**Pull request merged**
