### PR TITLE
[Meta] Adjusts Meta AI/Tcomm Sat

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Kinda reverts #15285

Fixes the AI cooking itself in under 2 minutes by reworking the AI chamber's internal setup almost entirely
trims out the newscaster, requests console, and two AI wall displays
Telecomms & the AI now use separate cooling system, and their respective freezers and connector ports are inside their respective chambers.
upgraded the AI APC to the same high-capacity one used on Box
removes all the old shitty borg statues from the sat
moved the AI display to the Foyer
made the external ring not vent to space when you exit it to space by using a proper airlock; also gave it scrubbers.
made structural changes to the AI part of the sat, as well as swapping glass for walls wherever there was wall mounted objects on glass
removed the tiny fan under the AI chamber's door  and made it into a pseudo-airlock
rearranges the flashers in the sat
makes the AI half of the sat not dummy thicc in some spots
rearranges & decorates the telecomms server room
rearranges the telecomms workshop
The telecomms Server Room door is now a button-operated airlock

check mapdiffs for better detail:
ss (2022-08-23 at 03 38 42)

# Changelog

:cl:  
bugfix: Yogsmeta AI no longer cooks to death in 60s
tweak: Yogsmeta Telecomms/AI satellite reworked
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
this thing is absurdly hard to get proper usable screenshots of

**Comment by VaelophisNyx** [comment]
photos mildly out of date; check mapdiffs

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
keep the sat with it's own scrubber network injecting into space, only pull air in

can you find some way to make the glass ring around it more symmetrical vertically?

use box's 3x1 airlock into the chamber
cyborg stays spawning in middle
holes in grilles idk

everything else looks nice,

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
can you make it even more symmetrical

**Review by ToasterBiome — APPROVED** [review]
looks good

**Pull request merged**
