### PR TITLE
Bluespace Disposals

### PR DESCRIPTION
**Pull request by monster860**
https://streamable.com/uq5se

:cl: monster860
rscadd: Adds bluespace disposals. Can be built using RnD, and a machine frame construction. It's basically a quantum pad that can be attached to a disposals pipe. Once built, simply wrench it onto a disposals trunk. 
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
no

**Comment by ghost** [comment]
ah nice, the instant teleport into space cannon i can put in the middle of central primary

**Comment by Ktlwjec** [comment]
rip

**Comment by monster860** [comment]
wow that took like 5 seconds for you to close.... reeeeee

**Comment by monster860** [comment]
@AdamElTablawy you mean this instant teleport into space cannon you can put in the middle of central primary? built without this feature?

https://streamable.com/uimjs

**Comment by AsV9** [comment]
i actually want this in the game for as admin spawnable only

**Comment by Time-Green** [comment]
When you jump in disposals its already a leap of faith and since the bluespace pipe is visible above ground it makes it obvious aswell

@nichlas0010 
This is such a cool feature you couldve at least kept it open for other people to view and give opinion on

**Pull request closed without merging**
