### PR TITLE
Adds TEG Heater

### PR DESCRIPTION
**Pull request by Aquizit**
Adds a Heater to the TEG Heating Loop

This is a way to create a stable TEG engine that a sole inexperienced engineer can set up to provide sufficient power to the station. I have discussed the desired state of the TEG setup with Mapping and Wiki at length, as well as my own experimentation before making this final decision/map. I've also tested this method and specific map to make sure it works.

**Please see my thread here to see my experimentation:** https://forums.yogstation.net/threads/teg-shortcomings-and-solutions.23920/

I can easily write up a bullet-pointed how-to on how to set the engine up with this heater for the wiki.

:cl:  
rscadd: Added heater to TEG heating loop.
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
The url 404's

**Comment by patpol4** [comment]
https://github.com/yogstation13/Yogstation/pull/11864

**Comment by Aquizit** [comment]
the forum link works now

**Comment by Aquizit** [comment]
I fucked up how to update this stupid thing and I don't know how to fix it.

**Comment by patpol4** [comment]
https://github.com/yogstation13/Yogstation/pull/12194

**Pull request closed without merging**
