### PR TITLE
Readds scrying orb and makes it only useable with wiz clothes

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#14394

### CODE REVIEW

**Comment by JamieD1** [comment]
Doesnt stop the shitters working with sec in rounds its not made for like dynamic.

**Comment by Bibby0110** [comment]
> 

That's against the rules. That is 100% an admin issue

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
This doesnt make it usable with wiz clothes?

**Comment by Bibby0110** [comment]
> This doesnt make it usable with wiz clothes?

i havent gotten that far

**Pull request closed without merging**
