### PR TITLE
Nukie mechs no longer get discount

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Companion PR to #16371 but I thought I'd atomize it. Nukie mechs are only viable if they're on discount which makes them hard to balance, so remove the discount so we can balance them.
# Changelog
:cl:  
tweak: Nukie mechs no longer get discount
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
God please

also this is like...SO never getting in. I tried. Everyone hates it for no good reason.
Mechs & Borgs should never be discounted, they're in an entirely different universe of power-scale compared to nearly every other item in the uplink

everyone loves the concept of "heehoo triple Dark Gygax" but no, in practice that's genuinely unfun to be on the receiving end of, in a way most other options aren't.

**Comment by Reed0506** [comment]
dark HONK should be able to be discounted, its not THAT good, and clown ops is all about being funny. otherwise, PR is probably fine or something.

**Comment by Simplehorror** [comment]
> dark HONK should be able to be discounted, its not THAT good, and clown ops is all about being funny. otherwise, PR is probably fine or something.

that gamemode never fucking runs it'd be like balancing jungle fever or meteors

**Comment by Moltijoe** [comment]
> that gamemode never fucking runs it'd be like balancing jungle fever or meteors

not with hisa around

**Comment by Bibby0110** [comment]
Yeah there's no way this is going in without the other PR

**Comment by JamieD1** [comment]
On hold till #16371

**Review by JamieD1 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
