### PR TITLE
Wall breaker mob

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Skeleton with a bomb that blows up the nearest walls
# Spriting

image

# Wiki Documentation

n/a
# Changelog

:cl:  
rscadd: New wall breaker mob
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
needs the hat

**Comment by Simplehorror** [comment]
> needs the hat

i cant sprite

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Missing/Inadequate rationale

**Comment by Simplehorror** [comment]
i want to add it as a new xenobio reaction later but i'd like to atomise it by getting the mob in first

**Comment by Bibby0110** [comment]
add the mob with the reaction. don't add bloat

**Pull request closed without merging**
