### PR TITLE
Removes the makeshift laser rifle's requirement for makeshift weapons book because it's garbage

### PR DESCRIPTION
**Pull request by SomeguyManperson**
10 5 damage shots or 1 17 damage shot 👏 

:cl:  
tweak: everyone can now craft makeshift laser rifles, not like you'd want to
/:cl:

### CODE REVIEW

**Review by jcatjmeow — APPROVED** [review]
Not a fan of this but I tested it and it works

**Comment by Hopekz** [comment]
> Not a fan of this but I tested it and it works

Why did you need to fully test this 2 line change outside of reading it to make sure it does what is described?

**Comment by MegaEmpirical** [comment]
Because the right thing is to always test.

**Comment by Marmio64** [comment]
to be honest i think makeshift lasergun should be buffed or something instead of making it craftable by anyone, but this is a good fix too i guess.

**Comment by MegaEmpirical** [comment]
Under what conditions was this available before?

**Comment by SomeguyManperson** [comment]
Have to buy a book for a few tc as traitir to craft it and othed stuff

**Review by Amelia0010 — APPROVED** [review]

**Comment by boodaliboo** [comment]
> Under what conditions was this available before?

be aware the book is infinite use

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
