### PR TITLE
changelings get 5 second succs if they succ multiple times

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

https://github.com/ShadowDeath6/-tg-station-yog-rebase/commit/642ecac7713881f316ef9574ba4c6a0584cdbde8#diff-ff0f7fbda1991f9f352d3fb26f6d6ec2
https://github.com/yogstation13/yogstation/pull/688/files#diff-ff0f7fbda1991f9f352d3fb26f6d6ec2

#### Changelog

:cl:  
tweak: lings get better at absorbing the more they absorb
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
change your title to something more informative

**Comment by Amelia0010** [comment]
happy?

**Comment by Ratvar** [comment]
(16 - changeling.absorbedcount) * 10
First you absorb at 160 (or 150 because you already have your own genes? I dunno) seconds
After one absorb it's 150, two-140, and so on, capping at 5 after 16(15?) absorbs

**Comment by Amelia0010** [comment]
It starts at 16 seconds (the numbers in the code are in deciseconds), and after each absorb it falls by one second (so it's 16, 15, 14, 13... 7, 6, 5).

Meaning it would take you 11 absorbs to go from 16 seconds to 5.

Also this is still per-stage, and there's 3 stages, so it starts at 48 seconds, then falls with 3 seconds every absorb down to 15, if you're counting it altogether

**Pull request merged**
