### PR TITLE
[admin] Port ahelp tickets panels to TGUI

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Ports ahelp ticket viewer to TGUI

Ticket list:
image

Individual ticket as admin:
image

Individual ticket as player:
image

# Changelog

:cl:  
rscadd: ported ahelp ticket viewer to TGUI
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
please add:
filters (my tickets, all tickets, unclaimed tickets)
button to reply from ticket menu (without having to View the ticket)
button to open regular reply menu (i dont like the chat box reply)
buttons from ticket popup that are missing from ticket menu:
(TP) (LOGS) (SMITE) (WIKI) (BUG) (MHELP)

**Comment by adamsong** [comment]
The missing buttons were missing from the old one, but I will add them

**Comment by adamsong** [comment]
> button to open regular reply menu (i dont like the chat box reply)

Hit send message with the message empty

**Comment by maxion12345** [comment]
where's the man up button
also new mhelp ticket menu when

**Comment by adamsong** [comment]
> where's the man up button

Verbs list

> also new mhelp ticket menu when

Planned

**Comment by ToasterBiome** [comment]
I loved this menu the one time I got to use it, plz finish

**Comment by Bibby0110** [comment]
I need to take a look at this.

If you merge this before I do Jamie I will personally ensure that you will be pinged on the Discord.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
