### PR TITLE
KILLS OFF SSNETWORK. [PORT TG]

### PR DESCRIPTION
**Pull request by wonderinghost**
all of this for ic circuits 
# Document the changes in your pull request
kills off ssnetworking from the game, signalizing whatever was used by it to help improve server stability.

Portholders of tg; JohnFulpWillard, Mothblocks, TGstation community (probably some people i overlooked but these are the heavy weights)

# Why is this good for the game?
helps lower initialization time and gets off code we havent touched since the dawn of its implementation. 

# Testing
TBD

# Spriting
TBD
# Wiki Documentation

# Changelog

:cl:  
rscdel: removes SSnetworking code  
wip: This is work in progress  
experimental: This is experimental
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
will begin work once i awake

**Comment by JohnFulpWillard** [comment]
WHERE'S THE CODE

wheres the code

**Comment by wonderinghost** [comment]
Soon

**Comment by Cartlord** [comment]
finally, the optimal implementation of modular computers

**Comment by wonderinghost** [comment]
re shifting goals, modular components is off the menu

**Comment by wonderinghost** [comment]
lets see if this was updated

**Comment by wonderinghost** [comment]
sterilizing branch

**Pull request closed without merging**
