### PR TITLE
Ports Roxie from Old Old Yogs!

### PR DESCRIPTION
**Pull request by fluffe9911**
Changelog
🆑 fluffe9911 for porting and (I have no idea who first made roxie) for making it!
add: Roxie after many years has now returned and can be found on the ancient shuttle ruin!
/🆑

### CODE REVIEW

**Comment by Nickvr628** [comment]
speedmerge

**Comment by HomocidlePancakes** [comment]
ughhhhhhhhhhhhhhh why does it have nipples ughhhhhhhhhhhhhhhhhhhhhh

**Comment by fluffe9911** [comment]
Thats just the original sprite *shrug*

**Comment by Amelia0010** [comment]
only on the relic shuttle so it's fine

**Pull request merged**
