### PR TITLE
Forces first time players to play assistant on their first round

### PR DESCRIPTION
**Pull request by ynot01**
:cl:  
tweak: New players must now play at least 1 round before playing a job other than assistant
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
How is this ided?

**Comment by nesisknesis** [comment]
because ynot got killed by an incompetent first-time chemist which then lead to him making this pr

**Comment by HomocidlePancakes** [comment]
10012F2C-621B-466B-8FE6-843177749666

This one?

**Comment by nesisknesis** [comment]
probably

**Comment by ThatLing** [comment]
Thanks for selecting the carefully written PR body that details how to make a good PR and stresses the importance of explaining why your PR should be merged, and deleting all of it. -1.5

**Comment by Lynameep** [comment]
i ded

**Comment by ynot01** [comment]
ye

**Comment by Nickvr628** [comment]
bad PR. Make them play as cargo tech or janitor or chef instead. All three jobs are better for new people to learn than useless assistants.

**Comment by alexkar598** [comment]
The vote didn't pass.

**Comment by Amelia0010** [comment]
https://forums.yogstation.net/index.php?threads/vote-merge-6379.19448/

**Pull request closed without merging**
