### PR TITLE
YogStation Bridge Redesign

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Redesign Bridge

New:
image

Old:
image

- Uses the fancy trimline to make the bridge look cooler.
- Also adds a few minor things to the bridge

### Why is this good for the game?

Utilizes the undervalued trimlines to make a sleek looking design

#### Changelog

:cl:  
tweak: YogStation Bridge has been redesigned
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Kinda prefer the current one but this ain't bad either

**Comment by Tipy1802** [comment]
Maybe give the MedSci purple or blue and purple decals

**Comment by redmoogle** [comment]
> 
> 
> Maybe give the MedSci purple or blue and purple decals

They do, it's just it's uhhh kinda hard due to command and medical having to share the same trimline(made medical brighter for now) Jamies working on command trimlines so they'll be better later.

**Comment by athena413** [comment]
8fb
trimlines are very cool and good

**Comment by Hopekz** [comment]
It's alright

**Comment by patpol4** [comment]
What if you did the outside of the bridge too :flushed: 
I could do it, just give me a pass to mess with your PR in that way

**Comment by redmoogle** [comment]
> 
> 
> What if you did the outside of the bridge too 😳
> I could do it, just give me a pass to mess with your PR in that way

Also yeah sure, not sure on how I could do the outside

**Review by patpol4 — APPROVED** [review]
Trimlines are good, no idea why would you move the light in cap office though

**Pull request merged**
