### PR TITLE
Disables the centcom raven cruiser for having fucked atmos

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

This shuttle kills everyone on it

# Changelog

:cl:  
rscdel: Disabled CentCom Raven Cruiser
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
What specifically is wrong

**Comment by ChuChu42** [comment]
> What specifically is wrong

shuttle spawns
has broken atmos
everybody gets on
30 seconds later
infinite pressure starts to suck everything in the shuttle to the right side of backroom chrushing everything with every object over and over nonstop with infinite force until a admin fixes the atmos

note: there are no holes in the shuttle

**Comment by 00ze-cyclone** [comment]
Simply add a billion magboots at the entrances of the shuttle
ez

**Review by patpol4 — APPROVED** [review]
lets hope auxmos helps (?)

**Comment by JamieD1** [comment]
> # Document the changes in your pull request
> This shuttle kills everyone on it
> 
> # Changelog
> 🆑 rscdel: Disabled CentCom Raven Cruiser /🆑

What the fuck, this is not the issue with this shuttle. Such a stupid PR for a kneejerk reaction

**Comment by ChuChu42** [comment]
> Simply add a billion magboots at the entrances of the shuttle
ez


even if you have magboots you are still going to get hit by a ton of floortiles, items and people

**Comment by patpol4** [comment]
> > # Document the changes in your pull request
> > This shuttle kills everyone on it
> > # Changelog
> > 🆑 rscdel: Disabled CentCom Raven Cruiser /🆑
> 
> What the fuck, this is not the issue with this shuttle. Such a stupid PR for a kneejerk reaction

its a hotfix for a serious issue, of course we're not deleting it

**Pull request merged**
