### PR TITLE
Updates all the space suits

### PR DESCRIPTION
**Pull request by nesisknesis**
Edits, adds, and removes some space suits.

Edits: 
- all the space suits with improvements to colours
- the paramedic to spacesuit to be consistent with the new spacesuits and remove its armoured appearance
- the black and red, medical, and engineering syndicate space suits to stand out and look more interesting
- the command EVA suit to be consistent with the new designs

Adds:
- a cosmonaut space suit. needs to be implemented at some point
- a new sprite ported from Tau Ceti for the EVA suit.
- an emergency space suit with very limited resistances and has a chance to become torn when the wearer is attacked, was previously unused. needs to be implemented at some point

Removes:
- several syndicate space suits that had uninteresting designs and were unused
- The EVA suit path, now merged with the base path

#### Changelog

:cl:  grimm hollow knight
rscadd: A new space suit, the Cosmonaut space suit. Currently unattainable.  
bugfix: The command space suit only protected from flashes, but now has welding protection as all space suits do.  
imageadd: Several edits to the new space suit sprites.
imageadd: A new sprite for the paramedic to space suit to show it is not armored.
imageadd: A new sprite for the command space suit.
imageadd: A new sprite the for EVA suit ported from Tau Ceti.
imagedel: Removes unused syndicate space suit designs. 
tweak: Moves all hardsuit code in the spacesuit file to the hardsuit file.
spellcheck: Renames the Shielded Deathsquad Mk3. SWAT suit to Death commando hardsuit from Death command space suit because it is very clearly a hardsuit even though it stated it was a space suit in a comment which is false.
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
we're gonna force you to atomize every single addition and edit, sorry kid, gonna have to make 4599488 PRs now.

**Comment by Hopekz** [comment]
Paramedic spacesuit has a red cross on the back sprite

image

**Comment by ynot01** [comment]
id love to see this testmerged

who knows if they give a fuck about what the players think though

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Missed the following map files:
DJstation.dmm : 100/101
crashedship.dmm:2219-2222
lavaland_surface_xeno_nest.dmm:155-157
wildwest.dmm:2048-2049
challenge.dmm:28-29, 60-61, 72-73
moonoutpost19.dmm:1885,1888,2061-2063

**Comment by nesisknesis** [comment]
> Paramedic spacesuit has a red cross on the back sprite
> 
> image

yeah i know i put it there

> id love to see this testmerged
> 
> who knows if they give a fuck about what the players think though

this doesnt need a testmerge

**Comment by Partheo** [comment]
Paramedic suit is way better.

I trust you with any removals so the fat trimming doesn't bother me at all.

Clothing sprites are like black magic to me, seeing you replace an ever more significant portion of them is quite inspiring.

image
My one issue with this design is the lack out outline on the sole of the feet. This can lead to cases where the feet blend in with what they're standing on. A clear distinction between the floor and the mob is important IMO. Drawing soles is a very easy way to add nontrivial detail to a shoe/boot sprite.

**Comment by Partheo** [comment]
soul detected

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
