### PR TITLE
Removes Stalinium & Capitalisium Bars/Golems

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Dead memes
unbalanced
yes admeme only but used like, once in a blue moon
also lore conflicts

# Changelog

:cl:  
rscdel: Deleted All Capitalisium + Stalinium Content
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
arent they used for a money religion

**Comment by VaelophisNyx** [comment]
not that I can see?

**Comment by neeshacark** [comment]
> not that I can see?

i do know the chaplains money sect lets you make someone into a golem as their highest cost ritual, but i don't know if this would remove that one specifically

**Comment by Rdrazga** [comment]
The chaplain capitalist golem is a different golem (granted it may use the same code just removing their ability) since the non chaplain one can physically convert people to capitalism, the chaplain version cannot

**Comment by VaelophisNyx** [comment]
yeah it looks like the chap-cap is safe

**Comment by KillerOrcaCora** [comment]
Keepeth

**Pull request closed without merging**
