### PR TITLE
The Great Demodularization

### PR DESCRIPTION
**Pull request by jcatjmeow**
### What is this

I'm moving all the stuff from the yogstation folder into it's corresponding regular folder.

### Why

We no longer follow those rules anyway. All having two code folders, two modules folders, two admin folders etc is create hassle and confusion. 

### What will change

Literally nothing. This has no gameplay impact and nothing needs to be updated on the wiki. It's just code cleanup!

### How can we tell whats yogs and what's not

It's all yogs babeeeeeeeeeeeeeeeeeeeeeeeee but also I am putting all the stuff from the yogs folder under a //yogs start heading.

Here is a handy mspaint drawing:
image

### What did you delete
Duplicate files, and a readme about modularization that literally said "this is depreciated" in it. **No code has been removed or altered, with the exception that references to things in the yogstation folder have been redirected.**

### Will this cause merge conflicts with everything?
Probably. But merging master into your pr should be easy. Only the icon changes will really be a pain (sorry)

### CODE REVIEW

**Comment by Readystorm546** [comment]
i did this before but got yelled at so good luck

**Comment by jcatjmeow** [comment]
> i did this before but got yelled at so good luck

oh shit I forgot 😔

**Comment by Bibby0110** [comment]
And your reason for destroying hours of work and making porting stuff even harder is?

**Comment by jcatjmeow** [comment]
> And your reason for destroying hours of work and making porting stuff even harder is?

Explain how either is true?

**Comment by Bibby0110** [comment]
Work being lost: This is hours upon work of keeping the codebase modularized being lost for no particular reason, (that you've stated at the very least)

Regarding porting shit: Merge conflicts.

Read this:
https://stackoverflow.com/questions/23958942/git-merge-conflicts-101

**Comment by jcatjmeow** [comment]
> Work being lost: This is hours upon work of keeping the codebase modularized being lost for no particular reason, (that you've stated at the very least)

This isn't work worth keeping. It's literally depreciated. All the effort spent on perfecting the steam engine is not a reason to ignore combustion engines.

> Regarding porting shit: Merge conflicts.

The yogstation folder does not assist in porting shit anyway, especially since roughly half of the yogs-exclusive shit **isn't even in the yogs folder as is**. There is literally no benefit.

**Comment by jcatjmeow** [comment]
> that you've stated at the very least

Sorry, the pr was a WIP. I've since updated it with a more proper description

**Comment by Bibby0110** [comment]
> > Work being lost: This is hours upon work of keeping the codebase modularized being lost for no particular reason, (that you've stated at the very least)
> 
> This isn't work worth keeping. It's literally depreciated. All the effort spent on perfecting the steam engine is not a reason to ignore combustion engines.

Yes with the difference being that the combustion engine was better than the steam engine.

This does nothing but remove the modularisation we already have for still no reason. The fact that we don’t enforce modularisation isn’t a reason to undo work.

> > Regarding porting shit: Merge conflicts.
> 
> The yogstation folder does not assist in porting shit anyway, especially since roughly half of the yogs-exclusive shit **isn't even in the yogs folder as is**. There is literally no benefit.
Yes it does.. Merge conflicts are hellish when the code is part TG and part yog, so doubling those is just stupid.

**Comment by Szyszkrzyneczka** [comment]
Soon The Great Demodularization shall begin! But when it does the weight of your ERP shall stay your feet.

**Comment by jcatjmeow** [comment]
I am busy with midterms atm will work on this later

**Pull request closed without merging**
