### PR TITLE
Adds the derringer pistol, a tiny 3TC traitor double-chamber gun loaded in .357

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

3TC, loaded in .357 by hand, two chambers, two shots, fits in boots

Cannot be loaded with speedloaders, bullets must be inserted individually

In stealth weapons section

# Spriting
Sprite from Whitesands
image

# Wiki Documentation

See above

# Changelog

:cl:  
rscadd: Added the derringer pistol to the uplink for 3TC
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
ah yes, revolver with no fire delay, walk to someone and erase them instantly, very fun, very interesting.

**Comment by ynot01** [comment]
> ah yes, revolver with no fire delay, walk to someone and erase them instantly, very fun, very interesting.

2 shots wont kill, it is meant to be effective in the way you describe it

**Comment by solwashere** [comment]
I like the idea of it

**Comment by Marmio64** [comment]
3tc for a pocket double barrel shotgun seems a little cheap, maybe 4tc instead?

**Comment by Notamaniac** [comment]
> > ah yes, revolver with no fire delay, walk to someone and erase them instantly, very fun, very interesting.
> 
> 2 shots wont kill, it is meant to be effective in the way you describe it

Have you considered the fact that you can buy two of them

**Comment by ynot01** [comment]
> 3tc for a pocket double barrel shotgun seems a little cheap, maybe 4tc instead?

It's essentially a revolver with 2 bullets (and no speedloaders allowed), at 4TC you'd just buy the revolver instead (2TC more) or a stechkin (1TC more)

**Comment by neeshacark** [comment]
its all fun and games until I buy 6 of them and print 357 from an autolathe and run around juggling and shooting, destroying the enemy with my epic skill

**Comment by ilikesaying** [comment]
Pull two derringers from boots since they can fit two tiny items
Magdump into unaware target
???
Greentext

**Comment by ynot01** [comment]
> Pull two derringers from boots since they can fit two tiny items Magdump into unaware target ??? Greentext

At 6TC you may as well have skipped the middle man and bought a revolver (6TC) which is easier to reload and has more bullets at the cost of 2 deciseconds per shot

**Comment by MajManatee** [comment]
i like the funny pistol

**Comment by Xoxeyos** [comment]
Can you make sure you can't reload this using a quick-loader .357 on the derringer? (See Detective's gun and the technology that can be used to quick load it.)

**Comment by ynot01** [comment]
> Can you make sure you can't reload this using a quick-loader .357 on the derringer? (See Detective's gun and the technology that can be used to quick load it.)

https://github.com/yogstation13/Yogstation/pull/18898/commits/6577d4fbc97b61edf06a826739012b19e4b92ffb

**Comment by Addust** [comment]
shiptest has a good icon for this, borrow it

**Review by cuackles — APPROVED** [review]
i do think it should have a held icon but stelth so idk

**Review by cuackles — APPROVED** [review]
i do think it should have a held icon but stelth so idk

**Comment by ynot01** [comment]
> i do think it should have a held icon but stelth so idk

It does have a held icon, it's a subtype of the revolver

**Comment by ynot01** [comment]
> i do think it should have a held icon but stelth so idk

image

**Comment by solwashere** [comment]
> > i do think it should have a held icon but stelth so idk
> 
> image
> 

Maybe shave off the inhand barrel pixels a bit

**Pull request merged**
