### PR TITLE
Update premadepapers.dm

### LINKED ISSUE #9559: Mech Request Form has poor formatting.
They have "Write" on them instead of actual fields.

## Reproduction:
Use the Bluespace Paperwork Printer found on certain PDA cartridges or perhaps the RD's clipboard.

### PR DESCRIPTION
**Pull request by ReddicusDragon**
fixes #9559

:cl:  
bugfix: fixed mech request form formatting
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
Thanks.

**Review by MrHorizons — APPROVED** [review]
Yep, this makes the field functional. Thanks.

**Comment by jcatjmeow** [comment]
would review but have no idea what I'm looking at so someone else pls

**Comment by JamieD1** [comment]
Can you reduce the lines, you dont need to put br on a seperate line

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Tidy up

**Review by JamieD1 — APPROVED** [review]
Better

**Pull request merged**
