### PR TITLE
wip egg accent

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
adds a fun new eggciting accent with eggcelent puns and i hope your eggstatic for this to be merged
#### Changelog

:cl:  
rscadd: Adds a new accent  
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Yes, this is exactly what Accents was meant for

image

**Comment by Hopekz** [comment]
Don't forget to modify strings\accents\accents.json  to add your accent otherwise it won't show up in the game

**Comment by boodaliboo** [comment]
thanks i will

**Comment by CMOisLing** [comment]
Hurt-Cracked
Gibbed-scrambled
Burned-boiled
Ill think of more later

**Comment by boodaliboo** [comment]
lost inspiration to code this sorry

**Pull request closed without merging**
