### PR TITLE
Port ice moon from tg

### PR DESCRIPTION
**Pull request by SomeguyManperson**
original pr: tgstation/tgstation#49680

a new planetside map with multiple z-levels and some new ruins and fauna

#### Changelog

:cl:  whoneedspacee
rscadd: Icebox Station has been added, explore the depths of the Ice Moon with boxstation right on top of it, don't forget your coat and internals!
rscadd: You can now mine rock flora into volcanic ash to make glass.
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
okay now this is epic

**Comment by Readystorm546** [comment]
Pictures or it is not real

**Comment by Whoneedspacee** [comment]
https://www.youtube.com/watch?v=kX-mH4k8b6k&t=

**Comment by SomeguyManperson** [comment]
the fucKinG station ruins can get scraped to space this might take a bit to find out

**Comment by boodaliboo** [comment]
> the fucKinG station ruins can get scraped to space this might take a bit to find out

i need ruins

**Comment by SomeguyManperson** [comment]
station has no random rooms since I haven't been able to stop them from getting space stuck under them, otherwise the map should be ready

**Comment by Hopekz** [comment]
I don't like how this PR ruins all map variations because they just straight up don't load and it is something that I enjoy.

This would probably need to be fixed sometime if we plan on using this.

**Comment by SomeguyManperson** [comment]
there's no other maps aside from normal box that have variations afaik save for maybe the bars, no other map variations are changed this one just doesn't get them until I can find out how to make them not strip to space

**Pull request merged**
