### PR TITLE
Reduce taser range

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
The taser has a very high range for being an instant point & click stun. 7 tiles is almost the entire screen horizontally so I've made it into more of a close-range weapon.

# Changelog

:cl:  
tweak: Taser range goes from 7 to 5
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
what

**Comment by Simplehorror** [comment]
> what

??

**Comment by Cartlord** [comment]
Tasers, as far as I'm aware, can only be spawned by administrators. They're out of standard gameplay entirely.

**Comment by Simplehorror** [comment]
> Tasers, as far as I'm aware, can only be spawned by administrators. They're out of standard gameplay entirely.

well even so don't forget about the energy shotgun or the powergamers who steal AI turrets and place them in armory in like clockcult or something

**Comment by 00ze-cyclone** [comment]
> Tasers, as far as I'm aware, can only be spawned by administrators. They're out of standard gameplay entirely.

TECHNICALLY there's one singular golden bolt remaining in charliestation, literally only one taser shot with the prototype egun before it need to recharge. So theoretically it could come to the station without admeme but yeah taser is still pretty much only stun mode of deathsquad's pulse weaponry and tactical egun of code red ERT.

**Comment by Bibby0110** [comment]
This isn’t needed

**Pull request closed without merging**
