### PR TITLE
Legion skulls no longer do the sound thing

### PR DESCRIPTION
**Pull request by LazennG**
Reverts yogstation13/Yogstation#16908
mass produced mobs dont need noises to play on death

### CODE REVIEW

**Comment by Moltijoe** [comment]
good boy lazenn waiting the 48 hours to make a revert PR
should probably change the death text so someone doesn't remake that original PR later down the road

**Comment by LazennG** [comment]
> should probably change the death text so someone doesn't remake that original PR later down the road

dont know how needed this is since it's the only pr to do this despite how long legions have been around and i'm sure everyone whose had the same idea decided not to act on it because it's stupid and annoying

**Comment by Bibby0110** [comment]
They absolutely do need noises

**Comment by LazennG** [comment]
> They absolutely do need noises

why do you think fauna that are killed en masse need to make noise every time they die

**Comment by Simplehorror** [comment]
> They absolutely do need noises

no they don't, you clearly have never played mining once in your life if you think legions need a death noise. farming tendrils is the most annoying action you can take upon yourself due to this PR

**Comment by MajManatee** [comment]
its not even a spammy sound, i dont see the big deal. I like having it.

**Comment by Bibby0110** [comment]
If it bothers you a lot add a global cooldown or make the volume lower

**Comment by JamieD1** [comment]
Revert Rules

**Comment by Bibby0110** [comment]
this isn't a revert

**Comment by KillerOrcaCora** [comment]
200 IQ bibby mode

**Comment by Simplehorror** [comment]
amazing how people who don't play miner can add random annoying noises to mining that they will never hear or find annoying because they don't play mining

**Comment by KillerOrcaCora** [comment]
Welcome to a open source project

**Comment by Hopekz** [comment]
> this isn't a revert

What is it then

**Comment by MajManatee** [comment]
the legion skulls... dont do the sound thing?
the main legion mob does.

**Comment by Hopekz** [comment]
> the main legion mob does.

This PR is about the mini skulls

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
