### PR TITLE
[MIRROR] Removes lizards from the game

### PR DESCRIPTION
**Pull request by ThatLing**
Original PR: https://github.com/tgstation/tgstation/pull/21770
-----
## About The Pull Request
This deletes the lizardpeople from the game.

## Why It's Good For The Game
Lizardpeople stink and need to be exterminated

## Changelog
:cl: Jerry Derpington
del: Nanotrasen is no longer hiring lizardpeople.
/:cl:

### CODE REVIEW

**Comment by FatalEYES** [comment]
lmao

**Comment by TheReddDragon** [comment]
bad mirror please remove

**Comment by fluffe9911** [comment]
>Gets triggered at meme labels
>Makes a meme pr

Heck off ling ye meme

**Comment by ThatLing** [comment]
today is a legendary day

**Comment by GenericDM** [comment]
lol

**Comment by ishitbyabullet** [comment]
[Hey, jackass, what's the deal here? You aren't me.](https://i.imgur.com/Ou1Mt30.png)

**Pull request merged**
