### PR TITLE
Adds a new round end sound

### PR DESCRIPTION
**Pull request by monster860**
This adds a new round end sound effect. Credits: Awoo by me, screaming at top of lungs with potato microphone by, SurfinNinja, help with finding sound effects MrHorizons

Here it is: https://cdn.discordapp.com/attachments/411919031260545024/754932165271224340/heresy_announced_cut.ogg

:cl: monster860, SurfinNinja, MrHorizons
soundadd: Adds a new round end sound
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
[For those that don't want to download it to hear it in all its utter glory.](https://voca.ro/ofU9YMpwBSe)

**Comment by deathslayer2481** [comment]
You goddamn motherfucker does this add awoo.

**Comment by MrHorizons** [comment]
> You goddamn motherfucker does this add awoo.

No, it doesn't.

**Comment by Amelia0010** [comment]
can we not do earrape thank you

**Review by JamieD1 — APPROVED** [review]

**Comment by Moja10** [comment]
This really shouldn't have been speedmerged.

**Comment by Partheo** [comment]
smh

**Pull request merged**
