### PR TITLE
[READY] Gives ability for free golem, free miner and delta station crew to research on a new research network, also minor tweaks

### LINKED ISSUE #16228: Ghost spawners (Charlie station, free miners, free golems) cannot research or use any science machine
### Severity

Inconvenience

### Short Description

Speaking from the charlie station POV as I've played it a few times, you cannot either research stuff from the console (which I assume makes sense since it's tied to the main station's research points, but still detrimental to the ghost spawn) nor use the robotics machine in the area, which prevents them from making borgs. Furthermore, the fact that the imprinter and the protolathe are science-department and not omni, like they used to be before, it is not directly possible to make an ore silo or other machines, which is once more detrimental to the spawn.

### Reproduction

1. Join as charlie station crew (any role).
2. Fix the stuff, as it's done always.
3. Go to science, fight xenos and risk your life many times through it.
4. Find out that almost the entirety of science is unusable due to ID restrictions.
5. Give up and ghost.

### Round ID

Most of the rounds that the ghost spawn has appeared. Posting this during Round 43469.

### Test Merges

_No response_

### BYOND Username

Time_URSS

### Additional information

I'm aware that this can be both a bug report and a feature one, thus i will bring it up here and in the forums as well. At the very least it'd be nice to fix the ID restrictions in Charlie Station so it can be minimally playable to an extent while something else is thought to make it less impacting to the station (which I do not think it is since most of the stuff charlie researches are teleporters or tcomms from my experience).

It kinda feels weird for a charlie "scientist" not to have access to his science machines. I'd understand if it was other roles, but the scientist should at least have access to those machines. Also it's annoying both to me and probably the admins to have to ahelp everytime to get this fixed.

I apologise as well if this was posted before and/or closed/discussed out, but I truly feel it kills the role enough to make it more unpopular than it was already.

### LINKED ISSUE #16254: Free miners not able to build their own mech on the new ship
### Severity

Inconvenience

### Short Description

The new free miner ship features a clarke wreck chassis and exosuit fabricator at the start the head, arms and torso are unobtainable without the station researching the Clarke themselves. which especially on lower pops isn't going to happen

### Reproduction

join as a free miner engineer see the chassis and no arm see no clarke tab on exosuit fab and cry yourself to sleep.

### Round ID

Round#43497

### Test Merges

_No response_

### BYOND Username

Burger1998

### Additional information

Somewhat related to https://github.com/yogstation13/Yogstation/issues/16228

### LINKED ISSUE #16303: Delta Station R&D
## Test Merges: 
Not Supplied / None
## Reproduction:

Optional fields: Cannot print ore silo from R&D console at delta station even though its researched also maybe just maybe put a tool belt or two on that station please.

 Submitted by: FatNasty91 (249055761454333952)

### PR DESCRIPTION
**Pull request by warface1234455**
They should be able to, why do they have RnD stuffs but not able to research that's uncool and less fun for these ghost spawns
- resolve #16303 
- resolve #16228
- resolve #16254

# Document the changes in your pull request
- Gives ability for free golem, free miner and delta station crew to research on a new research network
- Fix exosuit techfab on free miner ship facing into wall result in not able to print stuffs
- Ghost spawns Rnd will now run on different research network

# Wiki Documentation

- Gives ability for free golem, free miner and delta station crew to research on a new research network
- Fix exosuit techfab on free miner ship facing into wall result in not able to print stuffs
- Ghost spawns Rnd will now run on different research network

# Changelog

:cl:  warface1234455, baiomu
tweak: Gives ability for free golem, free miner and delta station crew to research on a new research network
mapping: Gives ability for free golem, free miner and delta station crew to research
mapping: Fix exosuit techfab on free miner ship facing into wall result in not able to print stuffs
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
dumb, why can ghost roles spend our points

**Comment by ShoziOffical** [comment]
> dumb, why can ghost roles spend our points

~~I will make a seprate research network then~~

**Comment by ShoziOffical** [comment]
> dumb, why can ghost roles spend our points

Also, it has been like this for a long time even before the research access change, did you just notice this

**Comment by ShoziOffical** [comment]
ok i think it might not be to make another sperate one as they run on the same subsystem

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
We have support for more than 1 techweb, see how the research subsystem creates them on the initialization of it.

machinery that utilize techwebs are controlled with stored_research or linked_techweb variable. see how these are utilized too.

**Comment by ShoziOffical** [comment]
~~@ToasterBiome They will still be linked to the same subsystem, that means even i changed to a new techweb it still have the same points value, someone will have to refactor the subsystem so it can process different techweb as well~~

**Comment by ShoziOffical** [comment]
done

**Comment by Bibby0110** [comment]
> > dumb, why can ghost roles spend our points
> 
> Also, it has been like this for a long time even before the research access change, did you just notice this

that doesn't make it less dumb

**Comment by Bibby0110** [comment]
> done

how do they get more points then

**Comment by ShoziOffical** [comment]
> > > dumb, why can ghost roles spend our points
> > 
> > 
> > Also, it has been like this for a long time even before the research access change, did you just notice this
> 
> that doesn't make it less dumb

help me make a seperate research network then

**Comment by ShoziOffical** [comment]
currently not working atm any suggest

**Review by ToasterBiome — APPROVED** [review]
Maps fine, I helped in coding this so will need someone else to review code

**Comment by CrazyDrakkon** [comment]
Don't know if because of this, but I wasn't able to research at all on the freeminer shuttle. Reconstructing the R&D console gave it all the station's research, but still unable to research.

**Comment by ShoziOffical** [comment]
> Don't know if because of this, but I wasn't able to research at all on the freeminer shuttle. Reconstructing the R&D console gave it all the station's research, but still unable to research.

There was a patch that fixed it already?

**Pull request merged**
