### PR TITLE
Bluespace Trash bag in-hand sprite

### PR DESCRIPTION
**Pull request by zigguy**
# Document the changes in your pull request

Adds an in-hand sprite for bluespace trashbags because they didn't have one before.
I tested it and there were no conflicts on my end

# Spriting
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
image
image
image
image
image
image
image

# Changelog
:cl:  
rscadd: added code for the sprites
imageadd: added in hand sprites for bluespace trash bag
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Very blue... not very spacey...

**Comment by MajManatee** [comment]
@cuackles @KillerOrcaCora

**Comment by cuackles** [comment]
Could you show us how it looks if you remove the bottom left most and right most pixels at the bottom, wanna see how it looks a bit more rounded

**Comment by zigguy** [comment]
image
image
image
image
image
image
image
image

**Comment by cuackles** [comment]
Yeee like that more, another thing that it's not absolutely necessary would be to make the inhand sprite have a defined direcction as in like,don't make it go over the body in the back view, but i don't consider this necessary as its supposed to be a big bag and i woundnt doubt that it would be able to show in front and back view, i will give some time to see if orca has any comments on it but as for me, doing or not doing the previously stated its still good to go

**Comment by KillerOrcaCora** [comment]
Looks like a trash bag, smells like a trash bag, tastes like a trash bag, good to go.

**Pull request merged**
