### PR TITLE
Gives Metastation atmos a non-maint path to incinerator to make it more similar to box

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Github documenting your Pull Request

People hate meta
They love box
We make meta more like box
Give them a shower + radiation lockers (why didnt we have these before wtf)
Thank you

chrome_MnYdmnqUHM

# Wiki Documentation

It needs a new sprite wiki

# Changelog

:cl:  
tweak: changed meta incinerator access to make it more like box incinerator access.
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
replace meta with box when

**Review by patpol4 — CHANGES_REQUESTED** [review]
Only skimmed the mapdiff for now and i spotted one thing. The maint airlock needs to have a maint area on top of it. I'll do a full review in a bit

**Review by patpol4 — CHANGES_REQUESTED** [review]
There's an airlock in an airlock here
image

Other then that I didn't spot any issues

**Comment by Hopekz** [comment]
This is a really good catch btw. Good quality maptainer
Praise to @wejengin2

**Review by patpol4 — APPROVED** [review]
Looks good now

**Pull request merged**
