### PR TITLE
Removes keybindable emotes

### PR DESCRIPTION
**Pull request by ThatLing**
# Document the changes in your pull request
Adding this was a mistake, this rectifies that mistake.

# Changelog

:cl:  
rscdel: Removed keybindable emotes
/:cl:

### CODE REVIEW

**Comment by Ethan4303** [comment]
Discrimination against people who don't want to type every emote they use >:(

**Comment by dukeofnothing** [comment]
Bad PR
If the issue of spinning or flipping too many times is really that much of an issue, I'd recommend adding a cooldown to prevent the same emote from being used over and over in quick succession, but I really fail to see how it is one

**Comment by MajManatee** [comment]
this got shit on almost as much as jamie's felinid PRs.

Yeah we like keybinded emotes.

**Comment by UltraBigRat** [comment]
if i want to spam an emote ill just control c control v it in  command bar anyways, no need to shut it down for everyone else  while providing absolutely no reasoning other then "it was a mistake"

**Comment by Mqiib** [comment]
easy solution to make it less obnoxious: limit the number of keybind emotes you can do to like once per second so people cant bind multiple to the same key or just mash a bunch of keys and fill your chat box with pointless messages

**Comment by Addust** [comment]
you little shit LET ME FLIP WITH R

**Review by ToasterBiome — APPROVED** [review]
Code looks great

**Comment by Bibby0110** [comment]
Add cooldowns or similar, no need to remove it fully

**Pull request closed without merging**
