### PR TITLE
A.R.G.U.S Skin for SlicerV

### PR DESCRIPTION
**Pull request by JamieD1**
Adds A.R.G.U.S Custom Skin.

Tested in Game

# Wiki Documentation

No Changes

# Changelog

:cl:  
imageadd: Skin for A.R.G.U.S
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Atleast fucking module lock it, it already barely looks like a borg
https://camo.githubusercontent.com/4b5db8397341820597994e5521d9149f3bb40379f8e7d555f1ce5d0c8cde1916/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f3132303936363333362f333331363638323233312f312f61667465722e676966

**Comment by ToasterBiome** [comment]
> Atleast fucking module lock it, it already barely looks like a borg
> https://camo.githubusercontent.com/4b5db8397341820597994e5521d9149f3bb40379f8e7d555f1ce5d0c8cde1916/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f3132303936363333362f333331363638323233312f312f61667465722e676966

I love ARGUS but what module is this supposed to be?

**Comment by Marmio64** [comment]
if i had to guess this would be a service borg module, yet its probably going to be used as an engineering one most of the time, so maybe lock it and perhaps even change how it looks?

**Review by nesisknesis — COMMENTED** [review]
There's been contention with borg skins not being representative of their module or being a borg at all. While not much has been done about this, to prevent from making the problem worse, I can't approve this in its current state. 

Other skins do exist where they throw any standards out the park but this is as good opportunity as any to begin phasing some out, which I will do.

A remedy to the problem is restricting borg skins to their silhoulette, making their status as 'skins' absolute. 

To put it plainly, currently the skin needs to be module locked, and then made to conform to that module's general shape. To give an example: 
image
Yes, this is very restricting but the issue of lack of clarity with borg skins needs to be fixed.

**Comment by JamieD1** [comment]
Sorry Ident, you cant put in a policy after someone has paid for a skin to be added when this ruling was not in place before.
I am merging this with the condition that future sprites will need to be more conformed to your statement.

**Pull request merged**
