### PR TITLE
puts all 4 ka mod disks in one necropolis chest roll because they suck

### PR DESCRIPTION
**Pull request by LazennG**
# Document the changes in your pull request

disks used to take up two slots in the necropolis loot pool and now they all occupy one because it'll make them all more available and try making up for the quality of these disks with quantity

# Wiki Documentation

maybe merging the death syphon, rapid repeater, resonator blast and aoe mods into one row on the loot table

# Changelog

:cl:  
tweak: tweaked ka mod disk loot placement
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
heavily dislike this approach, if you think they aren't worthy of the necro chest loot then put them somewhere else

**Comment by Moltijoe** [comment]
Maybe roll them all into one disk that unlocks everything?

**Comment by LazennG** [comment]
> Maybe roll them all into one disk that unlocks everything?

tried that and the way mod disks worked it didn't like that but maybe i can give it another shot

**Comment by LazennG** [comment]
after giving it another shot i have decided i can't condense them

**Comment by MajManatee** [comment]
nobody uses mod disks

**Comment by UltraBigRat** [comment]
Better then having em be split, but could honestly just remove them from tendrils altogether and make them buyable for points at the vendor?

**Comment by ynot01** [comment]
i would say make them orderable from cargo as a reward for one of the bounties

**Comment by LazennG** [comment]
closing since the alternative pr at least gets rid of the tedium of going from lavaland to rnd

**Pull request closed without merging**
