### PR TITLE
Renames Yogstation to YogsBox

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Remade this to fix some issues, original PR is #12869.

Renames Yogstation to YogsBox in, hopefully, the map vote and internally, as that is what everyone refers to it as and naming it after the server probably isn't the best idea. Will probably cause merge conflicts, but it shouldn't be hard to fix. Untested, should work.

# Wiki Documentation

If Box is referred to as Yogstation, it should be changed to YogsBox. 

# Changelog

:cl:  
tweak: Yogstation has been renamed to YogsBox
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
You seem to unironically want this so here are real reasons not to merge this outside of "this is a box hate PR". Anti-boxers might as well dislike this post now without providing any real feedback as per usual:

- This PR is fucking with the data collection we've been accumulating for years on the map named "yogstation". This presents an issue because all of a sudden a map named "yogstation" doesn't exist and this issue would have to be solved if this PR is to be merged. This problem doesn't exist if we just keep the same name.

- A Rename to a map is not a good idea game-design wise. People tend to associate the name with a map over playing it for years.
Think renaming dust2 from counter strike to "desert strike" or whatever. Dust2 never even had the number changed from 2 no matter how many iterations it got because of this reason.

- How a map name "feels" is subjective at best.

- This change is enforcing a standard that does not exist and is a slippery slope that will have to be applied to other maps for consistency. 

What this means: we have had a full map created recently and we have named it Kilo Station. We did not name it YogsKilo. If this PR goes through it would make sense to update all other existing maps to the Yogs___ syntax which doesn't make sense for the above reasons as well.

 - yogstation has evolved way past the original "box" map over the years. This change is downplaying the transformation and effort that has gone in to the map. I myself have submitted full rework PR's for 'yogstation' over the years and took no inspiration from other "box" styled maps meaning that it is insulting in terms of the effort I put in to this project.

- This is the most played map on our server. Not even by like a close majority I'm talking about being played 96%+ of the time. Why would you not want to associate what people have chosen to play and constantly maintain with the server name. This is why I personally thought this was originally a meme box hate PR because for some reason it is just completely ignoring that fact.

To back up this point please refer to the solid line under 'yogstation' from our official data given by our head mapper:
unknown-17-1


Subjective opinion:
Who actually cares about what the map is called. I personally mainly care that it is being changed after being implemented for years. I would be fine if this map was originally named "YogsPoop" as long as the map name stays consistent. 

Subjective opinion 2:
"YogsBox" doesn't sound as cool as "YogStation"

**Comment by nmajask** [comment]
> * This PR is fucking with the data collection we've been accumulating for years on the map named "yogstation". This presents an issue because all of a sudden a map named "yogstation" doesn't exist and this issue would have to be solved if this PR is to be merged. This problem doesn't exist if we just keep the same name.

Im not too sure about the way we keep that data, though I don't think like this would be too much of an issue as there are probably ways to fix this without too much work

> * A Rename to a map is not a good idea game-design wise. People tend to associate the name with a map over playing it for years.
>   Think renaming dust2 from counter strike to "desert strike" or whatever. Dust2 never even had the number changed from 2 no matter how many iterations it got because of this reason.

I'm fairly sure they don't. Usually when I hear someone refer to it as "Box", like how you are referring to this as an Anti-Box PR and not an Anti-Yogstation PR, though I may just have not noticed people refer to it as yogstation.

> * This change is enforcing a standard that does not exist and is a slippery slope that will have to be applied to other maps for consistency.
> What this means: we have had a full map created recently and we have named it Kilo Station. We did not name it YogsKilo. If this PR goes through it would make sense to update all other existing maps to the Yogs___ syntax which doesn't make sense for the above reasons as well.

I don't see the issue with this, as it's not enforcing the standard much more as its already following it.

> * yogstation has evolved way past the original "box" map over the years. This change is downplaying the transformation and effort that has gone in to the map. I myself have submitted full rework PR's for 'yogstation' over the years and took no inspiration from other "box" styled maps meaning that it is insulting in terms of the effort I put in to this project.

Thats why its named YogsBox and not Box Station, as it's our verson of Box with stuff we have added and changed

> * This is the most played map on our server. Not even by like a close majority I'm talking about being played 96%+ of the time. Why would you not want to associate what people have chosen to play and constantly maintain with the server name. This is why I personally thought this was originally a meme box hate PR because for some reason it is just completely ignoring that fact.
> To back up this point please refer to the solid line under 'yogstation' from our official data given by our head mapper: unknown-17-1

Naming it the same as the server can make it easy to mix up the server and the map. For example, I tried seaching up yogstation on the discord to see if anyone actually refers to the map as yogstation and it brought up a ton of stuff not related to the map.

**Review by adamsong — APPROVED** [review]
Having a map the name name as the server causes ambiguity that this will clear up.

**Review by patpol4 — APPROVED** [review]

**Comment by nmajask** [comment]
I think i am incapable of fixing merge conflicts without editing tails.dm

**Comment by patpol4** [comment]
@JamieD1 are we doing this or not

**Comment by nmajask** [comment]
> @JamieD1 are we doing this or not

If you do, tell me and ill fix the conflicts. I'm not going to fix them every time a new one pops up.

**Comment by patpol4** [comment]
> If you do, tell me and ill fix the conflicts. I'm not going to fix them every time a new one pops up

That is why I'm trying to get Jamie to respond here

**Review by nesisknesis — APPROVED** [review]

**Comment by patpol4** [comment]
@JamieD1 Please, yes/no

**Pull request merged**
