### PR TITLE
Moving will no longer interrupt breaking out of cuffs

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request
Stuns and everything else still interrupts it, but you can no longer just stand with someone in cuffs and move them back and forth. Also allows you to break out of cuffs while running away.

#### Changelog

:cl:  
tweak: You can now break out of cuffs while moving
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Definitely a major plus for the game.

**Comment by alexkar598** [comment]
You can literally flash anyone you cuffed to reset the timer at literally no cost, and if you don't have a flash you can just disarm them. 

The only situation where this can be useful is when you are in a hall trying to evade sec and someone runs into you unintentionally which usually doesn't change anything to the fact your going to get out.

**Comment by ghost** [comment]
@alexkar598 exactly - a non brain damaged sec still has plenty of options to keep someone detained. This is a greytide nerf more than any other.

**Comment by alexkar598** [comment]
I'd go with a greytide buff,only nerf is not being able to restrain people without disarming them

**Comment by ghost** [comment]
so wait basically you need to repeatedly blind people or waste stun charge on them if you want to  keep them handcuffed and detained properly during revs where you have like 4 people in cells and if someone gets away from you while handcuffed as an officer they can run away at mach 10 and uncuff themselves the entire time

that's a huuuuge nerf to handcuffs since one of their major points was basically that you had to find a safe place to stay while uncuffing yourself, leaving you vulnerable

**Comment by ynot01** [comment]
They called me a madman

**Comment by ghost** [comment]
@AdamElTablawy handcuffs are stuns on crack. In fact, one could argue cuffs are the reason stuns are considered overpowered.

Either way, the fact that this is a huuuuge nerf to them is a good thing.

I'd like to finish off by addressing the revs thing.
1. Bucklecuff

Thank you for coming to my Ted Talk.

EDIT: Alternatively, you can spend all of about two minutes getting a screwdriver and no less than five spare batteries for your stunbatonning needs.

**Comment by ynot01** [comment]
> In fact, one could argue cuffs are the reason stuns are considered overpowered.

did you know you have enough time to cable tie someone during a disarm push stun

**Comment by ghost** [comment]
@ynot01 did you know you can aggressive grab while cuffing to essentially guarantee success?

**Comment by MegaEmpirical** [comment]
Hmm what about when aggressive grabbed? Also, when arresting several people, I could seriously run out of charges on shit.

**Comment by HomocidlePancakes** [comment]
To anyone complaining:
1)Bucklecuff
2)Disarms

**Comment by ghost** [comment]
@MegaEmpirical 
Aggressive grab forces them to spam resist, generally letting you hold them in place for a few seconds. Add that to the disarm stun and you get a guaranteed cuff.

In terms of charges, carry around batteries and a screwdriver. That's all you need to do.

**Comment by alexkar598** [comment]
Or use the superior stun in security,the flash

**Comment by ghost** [comment]
@alexkar598 sec mains are always brainlets who never set up the flashers. However, they are indeed god-tier.

**Pull request merged**
