### PR TITLE
PORTS: DISARM REWORK, STUNBATON REWORK, BLOCK REWORK FROM BEE AND TG

### PR DESCRIPTION
**Pull request by SomeguyManperson**
read these tgstation/tgstation#45377
tgstation/tgstation#42958
BeeStation/BeeStation-Hornet#1642
also i fucking forgot to reset the branch iw as forking from
basically: nerfs batons, specifically classic batons/telescopic batons deal stamina damage, and stunbatons have a delayed stun that can be mitigated with stun resistance chems
disarms are now based(tm) on location and can hardstun again if you disarm someone who is knocked down (for a short time, less easy to chain), currently shoving is required to move past people who are not on help intent
weapon blocking is now more active, with attacks coming from certain directions being blocked by certain weapons, this area can be increased on several weapons by walking, and several less weapons are capable of blocking bullets. additionally, certain weapons (usually swords) will cause damage to people if the weapon blocks an unarmed attack

all changes are subject to further change if it works better

:cl:  actioninja for disarm rework, cobby for baton rework, qwerty for blocking rework
rscadd: ports disarm rework from tg
rscadd: ports stunbaton rework from tg
rscadd: ports block rework from bee
tweak: ghost sword block power is based(tm) on ghosts
rscadd: buffs bannanium frying pan
rscadd: walk toggle
tweak: reinforced and cult bolas only immobilize instead of doing a hard stun
/:cl:

### CODE REVIEW

**Comment by Alexandria404** [comment]
sounds like a tidebuff and a nerf to your average sec officer

**Comment by Xantam-13** [comment]
I cannot express my dislike for this enough. What little decent sec we get should not be made harder for them. 

If anyone plans to merge this, I am ruling this will be a council vote first.

**Comment by Xoxeyos** [comment]
security officers on suicide watch

**Comment by ThatLing** [comment]
> 
> 
> I cannot express my dislike for this enough. What little decent sec we get should not be made harder for them.
> 
> If anyone plans to merge this, I am ruling this will be a council vote first.

Both /tg/ and bee use this already, they'll be fine.

Also, obligatory "muh seperation of codebase and staff"

**Comment by SomeguyManperson** [comment]
if the baton nerf hits sec too hard it can be tinkered with to make it less of a pain to deal with, the disarm and block reworks are mostly in the favor of the security department though seeing as they can use riot armor to become immune to disarm stuns and get shields which are good for blocking

**Comment by Moja10** [comment]
Neutral, I blocked these when I was Council eons ago because the changes were shitty, haphazard, and not fleshed out, it's more than a year since then and there have been numerous additions and total changes. It's still a lot to throw on the playerbase, and not as many will quickly adapt as you and other robustos. There's plenty to argue about some of these changes being bad and it's harder to digest when it's either reject your porting work entirely or sit here nitpicking for eons about each individual change and how it will affect status quo on Yogs. However, i'm not in favor of nitpicking to eternity and I would lean on the side of it being merged and then the faults coming through and being fixed. I will yodel the sentiment, we should not make sec lives harder given the rule enforcements and their inability to use the armory in certain situations.

**Comment by DeadlyBag** [comment]
Stunbaton rework is amazing, have tried it and i like it alot. It gives you atleast some chance to respond to it instead of just being dead because someone pulled out an item out of their backpack and hit you with it in less than a second.

Not sure how i feel about the disarm rework. I think we do need to change the RNG disarm stun because its fucking cancerous to die because someone got a lucky 1 hit. Stun length on second shove might be a little too long but i dont actually know and would like to see it in action first before giving an opinion on it

Bola rework is really good and a buff to sec since reinforced bolas are almost always used by antags.
Block rework looks really nice and would buff both sec and certain antags. If this PR doesnt get merged atleast open a second pr with only this block rework i think we really need it.

Can we atleast testmerge this pr before shooting it down. I dont think this will hurt security as much as everyone thinks

**Comment by alexkar598** [comment]
This PR needs to be atomized. This is not a denial of the contents of this PR but the form it currently exists in. As for the feedback on the features in this PR which actually have content other than I liek or I disliek, I will copy them to the new prs if they are made. For the feedback that is only I like or I dislike. You should be making proper points for or against the PR as that has more weight than "nerf bad". 

The following need to be in separate PRs:
Baton rework
Disarm rework
Blocking rework

The rest of the changes may be bundled within one of these prs or pr'd individually if you so wish to.

EDIT: Moving over existing feedback is a pain. Wont be doing that.

**Comment by alexkar598** [comment]
I will be locking this PR to limit the amount of feedback going into the void. Please wait for the atomized PRs to leave your feedback in.

:heart:

**Pull request closed without merging**
