### PR TITLE
Fixes non lethal bullets doing damage

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

as title

# Wiki Documentation

values will have to be updated on guide to combat and maybe mention that pacifists can use them now

# Changelog

:cl:  
tweak: Fixes non-lethal bullets accidentally doing damage in addition to their stamina damage
tweak: Cleans up some code to account for non-lethal bullets now being actually non-lethal
/:cl:

### CODE REVIEW

**Comment by Lichton** [comment]
This is very clearly an intentional design decision and not a bug - please alter your PR.

**Comment by iamthesilly** [comment]
This doesn't let pacifists use them, you need to set harmful to FALSE on the ammo casings for that

**Comment by 00ze-cyclone** [comment]
Who are you and what have you done to the real Skrem

**Comment by TheBombMakerJL** [comment]
These were never non lethal, they’re less than lethal as they are irl. Not a “fix”, it’s a buff to pacifism. Rubber shots can kill people irl, they should be able to in game

**Comment by Skrem7** [comment]
okay i'm ending this shitpost

**Comment by Therandomhoboo** [comment]
Someone reopen this

**Pull request closed without merging**
