### PR TITLE
Blob now generate research points/money if contained in containment field, and slight tweaks to blob

### PR DESCRIPTION
**Pull request by warface1234455**
**Disclaimers**: Blob containment is possible through supermatter delamination with miasma, attempting to contain a blob created by round event is impossible. Only put blob containment further from the station(DO NOT GO TO ANOTHER Z OR IT WILL PUT BLOB ON THE STATION) to avoid anomalies spawning and emping station. It is recommended to put two layers containment, and remove ALL TURFS, LATTICES connecting blob to station. Failing to contain blob via supermatter will likely get you jobbanned, do at your own risk. Successfully containing a blob will generate a huge amount of research points and money per tick

image-2

## Guide to supermatter blob containment (without getting banned):
Make at least 4000> miasma and put in whatever container that is movable
Acquire 4 containment generators and at least 1 emitter
Acquire 1 supermatter beacon via cargo
Acquire the important tools: Engi hardsuit (to fight the rad in space i guess) full toolbelt with RCD, RPD, holofan, APC frame, electronic, small cell and one backpack firefighting tank

<details><summary>STEPS:</summary>

0. DO THIS ON STATION Z LEVEL OR THE BLOB WILL BREAK FREE

1. Setup a 3x3 area with holofan in the middle, go inside, press the button bottom right on your screen to create an area
image

2. Build a temporary wall and build an apc then delete the wall, turn apc on
image

3. Setting up containments like in the picture
image

4. Turn 3 containment generators in the corner and place some resin foam walls with your backpack firefighting foam like in the pic
image

5. Place supermatter in the middle and wrench it down (If you dont it will yeet away and kill the containment field), turn on the last containment generator and place the holofan after the gas from supermatter is cleared off. ALSO REMEMBER TO PUT PLASMA GLASS AROUND THE EMITTER SO IT DOESN'T GET FUCKED BY THE RAD ANOMALY
image

6. Put the miasma canister in place, wrench it down.. Once you see the zapping or fucking big ass text in engi coms fucking run and use holofan in your hand to space the chamber (it will make sm delam faster in space)
image

7. If it says controlled biohazard in engi coms then you are doing good, just wait a bit and you will get your own blob
image

8. CONGRATS!!! Now whatever you do, always keep the containment on or you will be fucked FUCKING FUCKED
image

</details>

# Document the changes in your pull request
Blob now generate research points/money if inside a containment field
Shuttle will leave when blob is contained inside a containment field
Supermatter blob delam now create blob without ghost poll (you can still click the blob camera to enter the blob if ur not banned or the blob is not occupied by another ghost)

# Why is this good for the game?
Allows blob creation for good purpose and not just murderboning. Allow more interesting stuffs to happen. Get your own blob pet today!
And since blob couldn't break containment then it shouldn't be stopping shuttle from leave

# Testing
### Controlled blob delam and containment breach
https://github.com/yogstation13/Yogstation/assets/89688125/ce568e3f-a35f-4d27-8062-b1d391c7e980

### unControlled blob delam breach
https://github.com/yogstation13/Yogstation/assets/89688125/73d238fa-73fc-4673-8e5d-63946cf184d9

# Wiki Documentation
Documents of change to blob wiki i guess

# Changelog

:cl:  
tweak: Blob now generate research points if inside a containment field
tweak: Shuttle will leave when blob is contained inside a containment field
tweak: Supermatter blob delam now create blob without ghost poll (you can still click the blob camera to enter the blob if ur not banned or the blob is not occupied by another ghost)
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
cool as shit

this cannot possibly go wrong

**Comment by ShoziOffical** [comment]
> cool as shit
> 
> this cannot possibly go wrong

Just follow the guide and everything will be fineee

**Comment by AMyriad** [comment]
*Do remember to keep your emitters protected so the anomalies don't destroy it, releasing the horror you're containing

**Comment by ShoziOffical** [comment]
> *Do remember to keep your emitters protected so the anomalies don't destroy it, releasing the horror you're containing

YeH... That's what i fucked up last time... Shit was wild lemme note that in the guide

**Review by ToasterBiome — APPROVED** [review]
i can't wait to bait a bunch of people to try this and get banned

**Comment by ShoziOffical** [comment]
> i can't wait to bait a bunch of people to try this and get banned

Ill be the first in line

**Comment by Yarinoi** [comment]
out of curiosity, does it have to be contained in the 3x3 containment field as seen in the video?

**Comment by ShoziOffical** [comment]
> out of curiosity, does it have to be contained in the 3x3 containment field as seen in the video?

Nah you can extend it 5x5 or smth

**Comment by ShoziOffical** [comment]
i recommend doing 1x1 chamber as you can still fire emitter through the field to damage the blob core directly and reduce its hp by 70% or smth

**Comment by ofscarletdreams** [comment]
it went wrong

**Comment by ShoziOffical** [comment]
> it went wrong

because people fucked up, mistakes happen.. 1x1 is safest, larger containment requires more emitters

**Pull request merged**
