### PR TITLE
Revert "Adds Kevlar Armor Plating (AKA The Great Sec Buff)"

### PR DESCRIPTION
**Pull request by ToasterBiome**
Reverts yogstation13/Yogstation#14799

Will close this TM when fuckin uhhhhhhhhh jamie beats up Orca

### CODE REVIEW

**Comment by tattax** [comment]
hello,, very good pr. good job sir..

**Comment by ynot01** [comment]
testmerges are for cowards

**Comment by Georgeur** [comment]
ive been busy so i didnt get around to commenting on the previous pr
first of all both you and ynot need to put a "why its good for the game" section cause I have no fucking clue what either of your takes are 
and WHY THE FUCK DOES MK1 ARMOR HAVE MINUS SLOWDOWN, literally just no, I shouldnt need to explain that

**Review by KillerOrcaCora — APPROVED** [review]
*sniffle h...he...here...*wine

**Comment by JamieD1** [comment]
Idea was fine, Orca has been shouted at.

**Pull request closed without merging**
