### PR TITLE
STAHP EMPING THE APC REE

### PR DESCRIPTION
**Pull request by monster860**
FastDMM was being really fucky and I couldn't get mapmerge to work so I did this fuckery with a text editor. Ree.

:cl: monster860
tweak: moves the experimentor APC out of range of its EMP
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Dis dum

**Comment by ThatLing** [comment]
Descriptive title

**Comment by Amelia0010** [comment]
I quite like the APC being in EMP range >:/

**Comment by ThatLing** [comment]
Decent downside to the experimentor

**Pull request closed without merging**
