### PR TITLE
rename german coat to GREEN coat

### PR DESCRIPTION
**Pull request by YouCanBeBetterThanThat**
# Document the changes in your pull request

Some people found it offensive so I changed the name and description.

# Changelog

:cl:  
tweak: Remove controversial historic references
/:cl:

### CODE REVIEW

**Comment by YouCanBeBetterThanThat** [comment]
hold on it's not even black

**Comment by Bibby0110** [comment]
how are you offended by *german*

**Comment by YouCanBeBetterThanThat** [comment]
> how are you offended by _german_

I'm not

**Comment by Bibby0110** [comment]
> > how are you offended by _german_
> 
> I'm not

image

**Comment by Xoxeyos** [comment]
I'd like to keep the "show your true colors" in the description, you can remove the german snow and whatnot, but I think it's subtle enough to make a good joke.

**Comment by Hopekz** [comment]
IMO I think it is more offensive to remove a german reference from the game just for being german.
The people in your vague example need to rethink their life if they care enough to get offended at something like this.

Maybe tell them to not be nationalists to the point where they need to suppress other nationalities in a space manz game.

**Comment by Marmio64** [comment]
I HATE NATIONALITIES, I HATE NATIONALITIES

**Comment by JamieD1** [comment]
Can come back to this

**Pull request closed without merging**
