### PR TITLE
Can only apply so much healing a second | STOP CLOSING BEFORE 24 HOURS

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Say goodbye to heal-stacking, now you can't combine meds/nanites/virus/whatever to become an unkillable monster

# Spriting

# Wiki Documentation

You can now only heal so much per second now - add to chemistry page
# Changelog

:cl:  
tweak: You can now only heal so much per second
/:cl:

before you complain, 5 heal a second is a lot

### CODE REVIEW

**Comment by isotope436** [comment]
mfw he thinks this is a chemist nerf
mfw this is actually a miner pen nerf in deguise

**Comment by thegoldencat413** [comment]
miner pen would be unaffected so no it’s not a miner pen nerf

**Comment by ronnikin** [comment]
Reaching 5 heal per second with virus and nanites isn't even that straightforward, not to mention all the shit this will break balancing on like cryo and nukie heals.  Absolute meme.

**Comment by ronnikin** [comment]
> miner pen would be unaffected so no it’s not a miner pen nerf

are you sure about that?  does miner pen use a completely different piece of code to heal?  if so why wouldn't it be included in this meme?

**Comment by thegoldencat413** [comment]
Miner pen doesn’t heal fast enough to be affected

**Pull request closed without merging**
