### PR TITLE
Adds canned food

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Adds canned food(snack subtype). It is food that is required to be opened before eating it. Yes.

Also i fucked up with merging so i wasted like 45 minutes of my live.

# Wiki Documentation

It is a code change, so fuck wiki documentation

# Changelog
E

:cl:  
rscadd: Adds canned food
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
And again i forgot to change the name before pushing

**Comment by JamieD1** [comment]
In what universe does popcorn and crisps come in a can.

**Comment by ghost** [comment]
> In what universe does popcorn and crisps come in a can.

I will fix it, but canned popcorn exists in real life.

**Comment by ghost** [comment]
Fixed

**Comment by JamieD1** [comment]
I honestly dont see the point, if you were adding new stuff, sure maybe, but you are literally just converting crap to canned for no reason.

**Comment by ghost** [comment]
> I honestly dont see the point, if you were adding new stuff, sure maybe, but you are literally just converting crap to canned for no reason.

It is a subtype for food items that need to be opened before eating, so i think it will be usefull if someone will want to add such food items as described above

**Comment by JamieD1** [comment]
I dont want everything replaced with a can, can you come up with new items instead, replacing old items for the sake of "can", just feels wrong.

**Comment by ghost** [comment]
Uhhh

**Comment by JamieD1** [comment]
Add the functionality of the can and one unique item and then this can be merged, no point in changing old stuff, or you can duplicate an old item for a "canned" version. This way the framework is in place for future canned items.

**Comment by ghost** [comment]
> Add the functionality of the can and one unique item and then this can be merged, no point in changing old stuff, or you can duplicate an old item for a "canned" version. This way the framework is in place for future canned items.

Ok

**Comment by JamieD1** [comment]
> > Add the functionality of the can and one unique item and then this can be merged, no point in changing old stuff, or you can duplicate an old item for a "canned" version. This way the framework is in place for future canned items.
> 
> Ok

Can you do it then?

**Comment by ghost** [comment]
I don't know, maybe

**Comment by JamieD1** [comment]
Reopen it when you do it then

**Pull request closed without merging**
