### PR TITLE
Perfectly balanced, as all things should be

### PR DESCRIPTION
**Pull request by SomeguyManperson**
not final numbers, adjustments can be made if this is too good or too bad
:cl:  
tweak: The bananium frying pan can now randomly crit
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
Random crits are fair and balanced

**Comment by HomocidlePancakes** [comment]
Play bassboosted BONK on every crit

**Comment by HomocidlePancakes** [comment]
Or maybe the killstreak sound from TF2

**Comment by Codeatmos** [comment]
On crit just make it play demopan.

**Comment by SomeguyManperson** [comment]
I've somehow managed to conflict the entire new datum file

**Comment by SomeguyManperson** [comment]
ok

**Comment by SomeguyManperson** [comment]
damn I'm good at this

**Pull request merged**
