### PR TITLE
Adds Server <-> Yogbot Discord linking

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
**This requires the YogBot PR to also be merged, for obvious reasons**
https://github.com/yogstation13/yogbot/pull/140

This allows people to link their Discord account to their CKey on the server.
This will allow some fun stuff when it comes to notification, YogBot ban management, adminning and such in the future.

HOW TO LINK YOUR ACCOUNT 101:
Go to Special Verbs.
Click 'Link Discord Account'
Insert your Discord ID, this can be found by typing !myid in any channel on the Discord
Type !verify [yourckey] in any channel, and your account should be linked!

If you for some reason need to change accounts or similar, ask an admin for help, they can unlink your account the following ways:
!unlink [ckey] in any Discord Channel
The Discord Manipulation verb in Admin, where they can search by Ckey or Discord ID

#### Changelog
:cl:  
rscadd: You can now link your Discord on the server! 
/:cl:

### CODE REVIEW

**Comment by Firewolf34** [comment]
Oh shit, this is big. I tried doing something similar a year back but gave up because it was a pain to write.

Can I enthusiastically suggest you make it provide the **Discord ranks** to the BYOND clients? 

This is important because then we can make the PR which allows the OOC Preferences to *mute DISCORD OOC* which would be fantastic. Prior, we couldn't do this because if we muted Discord OOC globally we'd be muting Admin OOC's which need to make it through the OOC preferences.

So the client needs a way to see the rank of the person on Discord from the Yogbot, and then allow the OOC message to pass if the player is a Admin rank. One could also check the local ranklist, I suppose, but if you're linking them it would be really nice to have this rank functionality.

**Comment by Bibby0110** [comment]
So you want to be able to block user Discord OOC?

**Comment by Firewolf34** [comment]
> So you want to be able to block user Discord OOC?

That's the end goal, but in order to do that I need **Discord rank data.**

If your link could provide Discord rank data for a linked username, then I can write something to mute Discord OOC.

**Comment by Bibby0110** [comment]
Just use the Discord ID to find their ckey, and then check their perms

**Comment by Firewolf34** [comment]
>Just use the Discord ID to find their ckey, and then check their perms

That'll work. Great job on this!

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
