### PR TITLE
Reworks Sleeping Carp

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Completely overhauls the sleeping carp martial art with a new moveset and mechanics. This will likely need some balance testing before being ready.

Innate:
>Sleeping carp innately grants some resistance to damage slowdown, as well as temporary resistance to space while focused. Space carps will also no longer consider the user hostile.

Focus:
>Using throw mode to deflect has been replaced with a focus level, which is built up by landing hits and acts as a temporary barrier to incoming damage. Stamina damage is easier to deflect.

>Focus level and incoming damage cancel each other out 1:1, for example being hit with a 20 damage laser with 15 focus will use up the remaining focus result in 5 damage taken, or if you have 30 focus and get hit with a 20 damage laser you will deflect it and be left with 10 focus. Focus will start to decay by 5 points per second after not landing any hits for at least 2 seconds.

Basic Hits:
>Regular punches deal 10 damage, plus up to 5 damage based on your focus level. Their attack cooldown is 25% shorter, and landing a hit on someone that has already taken 80 brute damage will knock them out for a few seconds and give them a concussion. Adds 10 focus.

Flying Kick:
>Disarms are replaced with a kick that deals more damage than basic punches and knocks down for a very short time (0.8 seconds) but has a longer cooldown before being able to act again. This also knocks back the opponent back, meaning they will take additional damage and be knocked down longer if they hit a wall. Attempting to do this at range will make you lunge forward in a flying kick to close the distance. Adds 20 focus.

Suplex:
>Attempting to punch a grabbed opponent will suplex them for 10-30 damage based on your focus level. This will also knock them down for a short time (1.5 seconds). Adds 20 focus.

Stomach Knee:
>Attempting to disarm a grabbed opponent will knee them in the stomach, immobilizing them for a very short time (0.5 seconds) and causing 30 suffocation damage. Adds 20 focus.

Wrist Wrench:
>Grabbing twice forces an opponent to drop what they're holding, dealing 5 damage to one of their arms in the process. Immobilizes them for 1 second and you for 0.4 seconds. Adds 10 focus.

Elbow Drop:
>Attempting to punch an opponent on the ground will bodyslam them for 10 damage plus your focus level, instantly killing anyone in critical condition. This uses up all of your focus, but you gain 30 (or 50 if you killed them) back from landing the hit. Has a longer cooldown before attacking again.

# Why is this good for the game?
Currently sleeping carp grants free immunity to bullets and a grab that makes you automatically win any 1v1. This is not a good recipe for a balanced martial art, and should have been reworked ages ago to account for the removal of tasers and one-hit batons.

# Testing

https://github.com/user-attachments/assets/1d4cf99f-cfad-4413-a9c7-7e95a0d20bbf

# Spriting
(Transparency scales with focus level)
image

# Wiki Documentation

On the list of syndicate items under sleeping carp, change the recall teachings section to match this:

image

# Changelog

:cl:  
experimental: Completely reworked sleeping carp, exact details can be found on github or by using "recall teachings" in-game.
imageadd: Added a shield overlay effect to indicate a sleeping carp user's focus level.
/:cl:

### CODE REVIEW

**Comment by LassiH** [comment]
if you miss the kick do you get a knockdown ?

**Comment by iamthesilly** [comment]
> if you miss the kick do you get a knockdown ?

No, but you can't attack for a short time after if you miss.

**Review by cuackles — APPROVED** [review]

**Comment by StupidTums** [comment]
Will a holographic, color changing carp sprite pop up real quick after completing a move? If not, why :(?

**Comment by LassiH** [comment]
isnt the point of sleeping carp to force people into melee combat if focus drains when they arent in combat for 2 seconds it just makes it cqc with extra steps after security knows you have the martial you have no way of dealing with ranged weapons unless you run at them while the martial art user cant use guns

**Comment by iamthesilly** [comment]
> isnt the point of sleeping carp to force people into melee combat

That's what the flying kick is for, it easily closes the distance almost immediately and knocks them down if you land the hit.

**Comment by LassiH** [comment]
also isnt this like really similliar to ultra violence both have to fight to gain style/focus and lose it without being in combat

**Comment by iamthesilly** [comment]
> also isnt this like really similliar to ultra violence both have to fight to gain style/focus and lose it without being in combat

They do different things. Focus cancels out incoming damage and reflects projectiles, ultra violence's style increases speed and at high levels allows dual-wielding the revolvers.

**Comment by LassiH** [comment]
do you gain focus by using the bo staff with the martial art?

**Comment by ToasterBiome** [comment]
interesting

**Comment by ju45he** [comment]
The Flying Kick move in the image for recalling teachings says left click but last time I disarmed someone I think it was right click.

**Pull request merged**
