### PR TITLE
Revert "Replaces chasm destruction spawn from tendrils with lava"

### PR DESCRIPTION
**Pull request by MajManatee**
Reverts yogstation13/Yogstation#17340

#17686 was added to hugbox chasms a lot. This PR is no longer needed.
#bringbackchasms 

All yall talk about is "Grr I hate miners, too OP, power gaming, etc. etc."
and yet you make it easier for them on lava land.
Put miners back in their place. Make their workplace MORE hazardous.
# Changelog

:cl:  
rscadd: I love massive holes. Chasms are back now that miners get a jaunter.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
I stand by removing chasms, this doesn't make miner harder, just more punishing.
Chasms also remove work from the mining medic job because it either deletes the body or jaunts them next to the station

**Comment by Moltijoe** [comment]
if you really want the miner's job to be more difficult, make the size of the lava field spawned larger.

**Comment by MajManatee** [comment]
The jaunter gives you a get out of jail free card. if you fall in TWO chasms, and you DIDNT buy a second jaunter then thats a skill issue.

**Comment by Moltijoe** [comment]
> The jaunter gives you a get out of jail free card. if you fall in TWO chasms, and you DIDNT buy a second jaunter then thats a skill issue.

you know what, reverting it to chasms actually makes miners job easier, jaunters don't activate on lava, meaning they actually have to be really careful or burn to death rather than having the "get out of jail free card" of a jaunter.

**Comment by Moltijoe** [comment]
this also doesn't factor in antag miners using chasms to round remove targets.

**Comment by Mqiib** [comment]
Ok but deleting people because their movement key got stuck (byond moment) is pretty lame and I'm not a huge fan of letting miners just outright delete corpses with literally no evidence when it suits them.

**Comment by MajManatee** [comment]
> 

yeah thats why they have the jaunter now. if you fall in two chasms then there something else going on.

**Comment by ReddicusDragon** [comment]
no opinion

**Review by Moltijoe — APPROVED** [review]
Literally just the inverse of my code, so it checks out

**Pull request merged**
