### PR TITLE
FUCK YOU. NERFS CLUWN CURSE

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request
increases cooldown on cluwn curse to 3 minutes from the previous 1 minute

# Why is this good for the game?
for a ability this is the most annoying shit to be afflicted with. afflicting you with some of the most debilitating brain traumas while severely damaging your brain to the point a papercut can kill it, along with muting, slow down, and perma equipping a setup you cant destroy, preventing surgeries. only method of correcting is to clone for organics (preternis counts) or knocking the head off (ipc) and pray there is something that can spill your organs to get your brain.

this ability isnt helped by the fact that ranking can decrease the cooldown by 12.5 seconds

probably a bit overkill however the ability to spam this with no tell or method of prevention you can access warrants it, maybe a minute less

# Wiki Documentation
changes the value of cooldown if its on the wiki

# Changelog

:cl:  

tweak: Cluwncurse takes 3 minutes instead of 1 minute

/:cl:

### CODE REVIEW

**Comment by PibeCantina** [comment]
I would prefer to be kept on a cycle of perma stunned by hammer and dead by fireball that spend more than 10 seconds as a clowne

**Comment by Mantlecrawler** [comment]
Just remove the spell. Cluwne is the antithesis of fun, realistically. It forces players to incredibly oppressive situations, and they have largely no control and no ability to fix it

**Comment by RG4ORDR** [comment]
Pointless wizard nerf.

You have multiple measures to stop being cluwned or reverse it. For how easy it is you shouldn't nerf a spell that already has an antagonizing long cooldown.

**Comment by wonderinghost** [comment]
> Just remove the spell. Cluwne is the antithesis of fun, realistically. It forces players to incredibly oppressive situations, and they have largely no control and no ability to fix it

you do it then. if it goes through it goes through, however it only takes someone and a given amount of time to try and get it back

**Comment by cowbot92** [comment]
yeah this spell is actually very cancer and the whole clewne thing is an old joke that has personally run it's course- especially because this spell makes people affected by it valid to be killed by anyone.

**Comment by MajManatee** [comment]
2 minutes not 3.

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
should probably just be removed, but this is """"removed""""

**Pull request merged**
