### PR TITLE
(port) coconuts and bongs

### PR DESCRIPTION
**Pull request by boodaliboo**
original pr: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10319
adds coconuts and bongs
#### Changelog

:cl:  
rscadd: Added coconuts and bongs
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
why did icons fail but it passed icon diffs

**Comment by redmoogle** [comment]
> 
> 
> why did icons fail but it passed icon diffs

Icon diffs just generate differences
but you didnt merge both icon files together. i recommend pulling out the individual icons from their dm file and importing it to ours

**Comment by boodaliboo** [comment]
> > why did icons fail but it passed icon diffs
> 
> Icon diffs just generate differences
> but you didnt merge both icon files together. i recommend pulling out the individual icons from their dm file and importing it to ours

i did exactly that

**Review by Partheo — CHANGES_REQUESTED** [review]
These are really out of place, not a fan.

**Pull request closed without merging**
