### PR TITLE
New brain damage line: Can space dragons commit murders?

### PR DESCRIPTION
**Pull request by alexkar598**
Can space dragons commit murders?

https://forums.yogstation.net/index.php?threads/vote-allow-space-dragons-to-murderbone.20939/

### CODE REVIEW

**Comment by ThatLing** [comment]
Pretty shitty, not gonna lie

**Comment by ReddicusDragon** [comment]
dew it

**Review by Hopekz — APPROVED** [review]
Personally can see your new line relating to the one just above it but eh

image

**Comment by alexkar598** [comment]
imma remove brain damage lines all together at some point

**Pull request merged**
