### PR TITLE
Adds bones

### PR DESCRIPTION
**Pull request by Bibby0110**
Introducing...

### BONECODE

All human bodyparts now simulate bone damage!

They're split into 3(4) different types of damage states.

You have your non-fractured state. Damage while in this state does nothing.

**Hairline fractures:**
At 40% towards max bone damage you get a hairline fracture. Slows you down a little. You take additional damage to the bone when moving until it's fixed. The bodypart is progessively damaged as long as you have this, only 1 damage wrapped in a prob(5)

**Fractures**
At 60% towards max bone damage you get an actual fracture.
These cause you to drop stuff in your hands, if the hands are broken that is. You take more passive damage too. Slowdown gets bigger.
On moving you also take some organ damage while taking a bit more bone damage. 

**Compound Fractures**
At 80% stuff starts getting bad. You've gottten a compound fracture.
This disables the limb and you start bleeding a bit from the bodypart. All other effects (passive damage, walking damage) are also increased. 
You get dizzy too. Look up a compound fracture, they hurt. 

Special cases:
Hairline fractures to legs do 2x slowdown.
Fractures and above cripple legs, not arms though. 

### How to take bone damage.
NUMBERS SUBJECT TO CHANGE.
Any hit that does more than 20 BRUTE damage, and isn't caused by a sharp item, transfers that 1:1 to bone damage.
Subject to change, system supports less damage for specific bodyparts, and higher/lower threshold too.

### How to heal bone damage

**Splints**:
These are applied to a bodypart and passively heal it. These can fix fractures. 
There are splints in first aid kits.
You can craft improvised ones with 2 metal rods. These heal at 45% the speed of regular ones.

**Chems/Ibandronate acid**
Made in chem by combining 1 unit bicaridine, 1 unit styptic powder, 1 unit neurine.
Heals 0.5 bone damage per tick. Overdosed at 30 units where it causes 0.1 bone damage per tick.
Can also fix fractures.

**Surgery:**
Organ manipulation but instead of manipulate organs you do bonegel + bonesetter. Fully heals the area + all fractures.
ONLY WAY TO FIX COMPOUND FRACTURES.

**Miner special case:**
Their survival pens contains Ibandronate acid.

### TODO:

- [ ] A lot of testing + tweaking numbers
- [ ] HEALTH ANALYZERS SHOULD IDENTIFIY FRACTURES WHAT WAS I THINKING
- [x] Refactor bone-ability to be species based
- [ ] Removing bones from some races (Slimepeople, etc)
- [ ] Look at damage thresholds + Fracture threshold
- [ ] Make normal splints orderable + printable.
- [ ] Lasers burning bones?
- [ ] Antag balance (Nukeops especially, clockwork, normal cult, ZOMBIES)
- [ ] Think about miners(only mining medics can heal bones?) and compound fractures.
- [ ] Find more TODO items
- [ ] Fill changelog when finalized

### Changelog
:cl:  
rscadd: Bones have been added
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Personally I'm a big fan of bones

**Comment by enkidienne** [comment]
it's happening... baymed underway!!

**Comment by ChesterTheCheesy** [comment]
"_Anyway, that's how i lost my medical licence._"
obraz

**Comment by cuackles** [comment]
Boneless crew

**Comment by alexkar598** [comment]
spam

**Comment by Bibby0110** [comment]
bonecode lives!

**Comment by Moja10** [comment]
I would say that getting smashed with a heavy object makes sense to transfer it at 1:1 bone damage, but I could see this getting out of hand with guns that auto transfer it to bone damage, like every nuke op gun. Maybe perhaps bullets could have a reduced rate or a percentage chance to transfer to bone damage to represent flesh getting hit rather than every bullet homing to the precious fibia to shatter it to dust. Otherwise, really cool PR!

**Comment by Bibby0110** [comment]
> I would say that getting smashed with a heavy object makes sense to transfer it at 1:1 bone damage, but I could see this getting out of hand with guns that auto transfer it to bone damage, like every nuke op gun. Maybe perhaps bullets could have a reduced rate or a percentage chance to transfer to bone damage to represent flesh getting hit rather than every bullet homing to the precious fibia to shatter it to dust. Otherwise, really cool PR!

Might add a multiplier for ranged weapons I guess

**Comment by TheLinuxOS** [comment]
Bibby coding a major change to the game without a bounty? IS THIS HEAVEN

**Comment by Cartlord** [comment]
Would like to ask you consider how Bone Hurting Juice fits into all this.

**Comment by ghost** [comment]
MERGE this then add more depth to medical. A patch shouldn't be the one and only solution to getting shot by someone. Add the need to bandage heavy or light bleeds, then use chems.

**Comment by boodaliboo** [comment]
buff skeletons bones lol

**Comment by maxion12345** [comment]
does drinking calcium do anything

**Comment by CMOisLing** [comment]
Don't forget to buff Bone hurting juice

**Comment by Bibby0110** [comment]
Theos is porting TG wounds in the future so there’s no real need for this anymore. 
bonecode

**Comment by patpol4** [comment]
Bonen't 😢

**Pull request closed without merging**
