### PR TITLE
[ADMIN] setting nuke code via request now sets beer nuke code aswell

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

as god intended

closes #14527

# Changelog

:cl:  
tweak: When admins give you the nuke codes, those codes now also work for the beer nuke
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Cheers

**Comment by redmoogle** [comment]
> # Document the changes in your pull request
> 
> as god intended
> # Changelog
> 
> 🆑 tweak: When admins give you the nuke codes, those codes now also work for the beer nuke /🆑

feels like someone could potentially misuse this and set off the beer nuke instead of the real nuke

**Comment by N3D6** [comment]
Are both codes the same or is it different for each nuke

**Comment by redmoogle** [comment]
> Are both codes the same or is it different for each nuke

both are the same from the look at the code

**Comment by ynot01** [comment]
> feels like someone could potentially misuse this and set off the beer nuke instead of the real nuke

oh no how terrible someone set of f the beer nuke instead of destroying the entire station ahh oh no ive made such a horrible mistake

**Comment by ynot01** [comment]
to add onto this, people commonly request nuke codes with the express purpose of requesting beer nuke codes; everyone already thinks this is how it works, but it doesn't: admins have to manually varedit the beer nuke code; now they wont have to

**Comment by redmoogle** [comment]
> to add onto this, people commonly request nuke codes with the express purpose of requesting beer nuke codes; everyone already thinks this is how it works, but it doesn't: admins have to manually varedit the beer nuke code; now they wont have to

Ultimate station prank set off the real nuke instead of the beer one

Add a Beer button to set the beer code instead

**Comment by ynot01** [comment]
no that is stupid

**Comment by TheLinuxOS** [comment]
> no that is stupid

and people being able to set off the real nuke isn't?

**Comment by JamieD1** [comment]
> 

I agree, the intention was that beernukes spawned with a code already so mods/admins can just look at the code and send it to them instead of setting the code on the nuke itself

**Pull request closed without merging**
