### PR TITLE
Nerf reinforced windows

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

These fuckers are used in EVERY WINDOW ON THE MAP instead of being niche security windows, they're protecting the medbay lobby ffs. Since I'm not allowed to remove the dumb ones from the map I've gone and nerfed them overall by about 40%. (they take almost a solid minute to break)
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Nerf reinforced windows so they don't take a minute to open
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
To make it clear, decon time was nerfed. I want to lower the lower bound of damage for them as well but I don't think that'll get in

**Comment by Moltijoe** [comment]
this cuts off 14 seconds, considering how i never see people actually deconstruct them and instead just break them, i think this should be fine. I would personally consider having the welding step be a bit longer than only 8 seconds though.

**Comment by patpol4** [comment]
sounds sensible to me, i always hated rwindows

**Comment by Sniblet** [comment]
yeah it's uhhhh a little weird that they're like four times as secure as solid steel

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
