### PR TITLE
Buffs stormtrooper armor

### PR DESCRIPTION
**Pull request by Bibby0110**
# General Documentation

### Intent of your Pull Request

3x for 10k is expensive for something isn't the best for most of what you will encounter.

Gives it a buff so it's more in line with regular armor which is much much cheaper, nerfs the actual good laser resistance so it's not *that* much better

# Changelog

:cl:  
tweak: stormtrooper armor is better rounded
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
If this is related to the star wars armor, it is weird that it has worse laser resistance since it primarily defends against lasers in the source material.

**Comment by Bibby0110** [comment]
> If this is related to the star wars armor, it is weird that it has worse laser resistance since it primarily defends against lasers in the source material.

Very well aware, but staying close to the reference material isn't really wise considering practically no antags use lasers.

At current it's a bit of a newbie trap, since you'd expect 10k armor to be better in most cases than the regular cheap kind.

It's still not better than it, but it's not as garbage.
Wouldn't want it to be the natural upgrade imo.

Still has great laser resistance, just isn't paper mache when you get hit by some naked assistant.

**Comment by Marmio64** [comment]
kinda defeats the purpose of it being anti-laser armor. Don't think of it like regular armor, think of it like armory armor, where it protects against a specific weapon but not much else. The ablative vest is only good against energy/laser weapons yet no antags use those, so now it should have its stats changed? If you want an armor that covers the whole body, is very protective, and slows you down, theres already the swat armor you can order from cargo. If you're looking to make it not be a noobie trap, change the desc so that it says its good against lasers and not much else, and while you're at it, reduce the slowdown to be like 0.75 since the slowdown makes the armor pretty damn trash.

**Comment by Bibby0110** [comment]
> kinda defeats the purpose of it being anti-laser armor. Don't think of it like regular armor, think of it like armory armor, where it protects against a specific weapon but not much else. The ablative vest is only good against energy/laser weapons yet no antags use those, so now it should have its stats changed? If you want an armor that covers the whole body, is very protective, and slows you down, theres already the swat armor you can order from cargo. If you're looking to make it not be a noobie trap, change the desc so that it says its good against lasers and not much else, and while you're at it, reduce the slowdown to be like 0.75 since the slowdown makes the armor pretty damn trash.


If anything this should be buffed without having it's laser armor reduced

As it stands this armor is on par with a reflective jacket when it comes to laser armor, at more than 3 times the cost per armor.

For 2k+ extra credits you get:
Slowdown
10 more melee + bullet armor

As it stands the reflective vest is just so much better, less slowdown same stats bar 10 melee + bullet armor.

This way it is at least semi-reasonable as a heavy armor weighted towards lasers.

**Comment by Marmio64** [comment]
removes its niche as a fullbody 'ablative vest' but gives it a different niche i guess

**Pull request merged**
