### PR TITLE
Remove uplink entry for shielded hardsuit

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

you get shot 3 times and then it is worse than a regular hardsuit. nice joke. plain noob bait
# Spriting

# Wiki Documentation

Remove uplink entry for shielded hardsuit
# Changelog

:cl:  
rscdel: Remove uplink entry for shielded hardsuit
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
it's worse? i recall seeing it having the same stats in addition to being always EVA proof and always covering the face but never inflicting slowdown

**Comment by Simplehorror** [comment]
last time i checked it had wrose stats

**Comment by ynot01** [comment]
syndicate hardsuit
`armor = list(MELEE = 40, BULLET = 50, LASER = 30, ENERGY = 15, BOMB = 50, BIO = 100, RAD = 50, FIRE = 50, ACID = 90, WOUND = 25)`
elite hardsuit
`armor = list(MELEE = 60, BULLET = 60, LASER = 50, ENERGY = 25, BOMB = 90, BIO = 100, RAD = 70, FIRE = 100, ACID = 100, WOUND = 25)`
shielded hardsuit
`armor = list(MELEE = 40, BULLET = 50, LASER = 30, ENERGY = 15, BOMB = 80, BIO = 100, RAD = 50, FIRE = 100, ACID = 100, WOUND = 30)`

**Comment by Simplehorror** [comment]
still noob bait for 30 tc

**Comment by Marmio64** [comment]
> still noob bait for 30 tc

This is in no way noob bait. While not worth 30 TC if you have more important things to buy, its also a worthwhile investment since healing while in a hardsuit is often a pain, and the shields can often protect you from that. In addition, the no slowdown offered from the suit while still always providing spaceproofness is really useful for when you plan to use bombs a lot to space parts of the station, you'll always have the speed advantage unless the crew has space adaption, at which point both sides are now equal. No reason at all to be removing this. If you think it's not worth the TC then just make it cheaper, why would you need to remove it?

**Comment by Rdrazga** [comment]
This is getting into the range of 'oh I can't possibly find a use for this in my specific playstyle, and everything in game has to be minmaxed to only allow the gear that gives the best chance of winning'. Bad PR built around losing perspective that a lot of the fun in this game is experimenting, trying out strats, doing gimicks, ect. Stuff shouldn't just be wiped off the board because it doesn't fit one specific playstyle of a highly experienced player.

**Comment by JamieD1** [comment]
maybe just reduce the cost

**Comment by Simplehorror** [comment]
other guy has better PR

**Pull request closed without merging**
