### PR TITLE
Resprites Slimes because this server is full of color blind people. 

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
Increased color range and designs of the harder-to-tell slimes. You shouldn't really have trouble figuring out which is which now. 

# Spriting
image

# Wiki Documentation
sslimes

# Changelog

:cl:  

imageadd: Resprites slimes so the powergamers can micro-manage easier. 
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
those gold any pyrite ones look awfully similar...

**Comment by MajManatee** [comment]
also update your DME like damn

**Comment by cuackles** [comment]
Check your code u r eliminating 3 code thingies with this PR

**Comment by MajManatee** [comment]
Smh this is why you dont let the ART people handle CODE

**Comment by KillerOrcaCora** [comment]
1f4b1da3714061625130329889e293e2

**Review by cuackles — APPROVED** [review]
mmmmm slimes

**Pull request merged**
