### PR TITLE
Makes head coders no longer own preferences

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

why do you own this

# Wiki Documentation

# Changelog

### CODE REVIEW

**Comment by adamsong** [comment]
Because prefs are easy to fuck up

**Comment by Bibby0110** [comment]
> Because prefs are easy to fuck up

last time they merged a prefs change it broke all of prefs

**Comment by JamieD1** [comment]
Because preferences are editing all save files on the host which we really don't want to do. So its best to have a check with them. So no it is staying.

**Comment by Bibby0110** [comment]
> Because preferences are editing all save files on the host which we really don't want to do. So its best to have a check with them. So no it is staying.

but last time you did it you broke everything 🚶

**Pull request closed without merging**
