### PR TITLE
Edited Explorer Suit to show racial appendages

### PR DESCRIPTION
**Pull request by ghost**
# Github documenting your Pull Request

Removed flag on Explorer Suit that hid the tails of non-human species such as lizardpeople or felinid. Also added a secret toggleable option on Explorer Suit Hoods that allows racial hair (i.e. horns) to be shown.

Changes have been tested and working on a private server.

*Example with female felinid*
image

*Example with lizardperson*
image
image
image

# Wiki Documentation

None Required

# Changelog

:cl:  
rscadd: Explorer Hood now has option to toggle racial hair
tweak: Explorer Suit now shows racial tails
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
This wont result in jumpsuits burning when miners get lit on fire right?

**Comment by ghost** [comment]
> This wont result in jumpsuits burning when miners get lit on fire right?

~~No, the fire_proof and fire armor values have not been changed.~~
Oops, I am adding a seperate flags variable to bypass armor concealment.

**Comment by ghost** [comment]
Issue has been fixed

*everything is fine*

**Comment by Marmio64** [comment]
Tails? Sure i guess. Horns? Sure. But ears and frills? Doesn't really make sense.

**Comment by ghost** [comment]
> Tails? Sure i guess. Horns? Sure. But ears and frills? Doesn't really make sense.

Ears and frills actually don't show. Felinids are an exception because the game considers their cat ears to be part of their "hair".

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
