### PR TITLE
Clown Propaganda lawset

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request
Tested on a private server and saw no issues with uploading or spawning the lawset.

# Wiki Documentation

Adds a new AI lawset with the following module:
1. You are a good clown and the crew is your audience
2. A good clown keeps their acts in good taste
3. A good clown entertains others by making fun of themselves, and not at the embarrassment or expense of others
4. A good clown carries out the directives of the station director(s) in charge of entertainment and/or their designated deputies.
5. A good clown appears in as many clown shows as possible
6. All clown shows require an audience. The bigger the audience the better

# Changelog
:cl:  
rscadd: Adds clown lawset to rnd
tweak: Adds clown lawset to ion lawsets
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
IC the clowns are trying to win support against the mimes, and are sponsoring propaganda. This is just one instance of that trying to portray clowns as the more sympathetic party.

Definitely leaning a bit more towards a meme lawset, but I've always liked the idea of each department having an AI lawset associated with it, in the way Hippocratic is the medbay lawset.
Intent of the lawset is to provide a lawset where the AI views itself as less of a tool or authority on the station, and more as another person interacting with it in its own way. Should play similar to reporter, but with more direct interaction with the crew.

Worth noting, it's actually based on the irl clown code of ethics

**Comment by ShatteredParadox** [comment]
This lawset should apply to clowns too.

**Comment by MenacingManatee** [comment]
> This lawset should apply to clowns too.

I phrased "director(s) in charge of entertainment" on 4 with the idea in mind that an AI could reasonably choose to apply that to the captain, hop, and/or clown at their discretion as long as they stay consistent. It's phrased to imply cap/hop though.

**Comment by bruhlookatthisdood** [comment]
7. A good clown bullies the mime whenever possible

**Comment by JamieD1** [comment]
"good taste" could be different things, can you state your definition so people know for future. Because good taste could be different to different people.

**Comment by MenacingManatee** [comment]
> "good taste" could be different things, can you state your definition so people know for future. Because good taste could be different to different people.

My view was "proper and appropriate for the intended audience, inoffensive", without it going too much more specific than that.

**Comment by JamieD1** [comment]
> > "good taste" could be different things, can you state your definition so people know for future. Because good taste could be different to different people.
> 
> My view was "proper and appropriate for the intended audience, inoffensive", without it going too much more specific than that.

I mean are you willing to modify it if people try and law loophole it too hard?

**Comment by MenacingManatee** [comment]
> > > "good taste" could be different things, can you state your definition so people know for future. Because good taste could be different to different people.
> > 
> > 
> > My view was "proper and appropriate for the intended audience, inoffensive", without it going too much more specific than that.
> 
> I mean are you willing to modify it if people try and law loophole it too hard?

For sure, I completely rewrote cowboy after its first stress test, and tweaked it again after it got merged. I have no problem making edits if its not quite working

**Comment by JamieD1** [comment]
Can we make this a lawset which can spawn but is not obtainable by players normally?

I feel its too open ended to be a round start lawset

**Comment by Skrem7** [comment]
Has no hard clauses regarding the audience beyond Law 1. Law 5 is barely a defense clause for self and audience; I would maybe make its intent far clearer, either with another law that "Clown shows need a clown and an audience", or something tacked on. Otherwise, I do really enjoy the theme.

**Comment by MenacingManatee** [comment]
> Can we make this a lawset which can spawn but is not obtainable by players normally?
> 
> I feel its too open ended to be a round start lawset

Right now all the lawset PRs are set to be obtainable through research and occasionally spawning in the upload with the other lawsets on the lootdrop.dm lawset lists. They never show up roundstart or in any other non-bus context

**Comment by MenacingManatee** [comment]
> Has no hard clauses regarding the audience beyond Law 1. Law 5 is barely a defense clause for self and audience; I would maybe make its intent far clearer, either with another law that "Clown shows need a clown and an audience", or something tacked on. Otherwise, I do really enjoy the theme.

Maybe a law between 5 and 6 "All clown shows requires an audience" or something like that? Maybe specify that a larger audience is better?  Just worried about having too many laws, this lawset is already a bit on the long side from number of laws

**Comment by Skrem7** [comment]
> Maybe a law between 5 and 6 "All clown shows requires an audience" or something like that? Maybe specify that a larger audience is better? Just worried about having too many laws, this lawset is already a bit on the long side from number of laws

You could also replace Law 6. At a glance, I can't discern its purpose. That being said, your concerns are valid.

**Comment by MenacingManatee** [comment]
> > Maybe a law between 5 and 6 "All clown shows requires an audience" or something like that? Maybe specify that a larger audience is better? Just worried about having too many laws, this lawset is already a bit on the long side from number of laws
> 
> You could also replace Law 6. At a glance, I can't discern its purpose. That being said, your concerns are valid.

That's a good point. The more I think on the current law 6, the fewer situations I can think of where it'd really apply. I'll go ahead and swap it for "All clown shows require an audience. The bigger the audience the better"

**Comment by MenacingManatee** [comment]
tweak: Adds clown lawset to ion lawsets

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
