### PR TITLE
egg-based food is vegetarian friendly

### PR DESCRIPTION
**Pull request by ktlwjec0**
Removes meat tag from egg-based foods containing no meat, since they're not meat.

# Wiki Documentation

food type on guide to food i'll do this

:cl:  Ktlwjec
tweak: Egg-based foods are no longer meat by default.
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Last time I checked eggs aren't a vegetable...
While this is a good change in theory, you should make anyone that wouldn't eat meat also not eat egg.

**Comment by ktlwjec0** [comment]
> Last time I checked eggs aren't a vegetable... While this is a good change in theory, you should make anyone that wouldn't eat meat also not eat egg.

literally 6 foods, and this feels like it'll fit in a new pr not merged into this one. also eggs are..not meat

**Comment by neeshacark** [comment]
does manatee not know how vegetarians work?

**Comment by boodaliboo** [comment]
> > Last time I checked eggs aren't a vegetable... While this is a good change in theory, you should make anyone that wouldn't eat meat also not eat egg.
> 
> literally 6 foods, and this feels like it'll fit in a new pr not merged into this one. also eggs are..not meat

eggs can be accidently fertalized and have meat so wrong

**Review by Moltijoe — APPROVED** [review]
there's also an egg foodtype, if people REALLY can't eat eggs because of some reason or another, they should probably care about that foodtype instead of meat

**Pull request merged**
