### PR TITLE
disables icemeta until bug is fixed

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

atmos bugs crash the server on dock :(

### CODE REVIEW

**Comment by N3D6** [comment]
fix it or I will un-fix your skull from your head

**Comment by Hislyna** [comment]
Literally worst day of my life

**Comment by Addust** [comment]
just fix it yourself man

**Comment by N3D6** [comment]
> just fix it yourself man

need auxtools

**Comment by Moltijoe** [comment]
auxmos merged

**Pull request closed without merging**
