### PR TITLE
Adds a new crayon decal

### PR DESCRIPTION
**Pull request by Moltijoe**
image

:cl:  @cuackles 
rscadd: new crayon decal
/:cl:

### CODE REVIEW

**Comment by ChuChu42** [comment]
SUSUSUSUSUSUSUSUSUS

**Comment by Maia-J** [comment]
⠀⠀⠀⠀⣠⡴⠞⠛⠛⠛⠛⢶⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⢀⡾⠃⠀⠀⠀⠀⠀⠀⠀⠈⢷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⣼⡷⠶⠒⠒⠒⠶⢶⣄⠀⠀⠀⢻⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢠⡞⠁⠀⠀⠀⠀⠀⠀⠀⢻⡄⠀⠀⠈⣧⠀⠀⠀⠀- I support it
⢸⡅⠀⠀⠀⠀⠀⠀⠀⠀⣼⠃⠀⠀⠀⣿⠛⠛⢻⡆⠀⠀⠀⠀⠀
⠀⢹⡷⠶⣤⣤⣤⣤⣤⡾⠃⠀⠀⠀⠀⢻⠀⠀⠈⣧⠀⠀⠀⠀⠀
⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡄⠀⠀⣿⠀⠀⠀⠀⠀
⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠀⣿⠀⠀⠀⠀⠀
⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠀⣿⠀⠀⠀⠀⠀
⠀⠸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢷⣤⡴⠟⠀⠀⠀⠀⢀
⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠶⢤⣤⣤⠶⢾⡿
⠀⠀⠸⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡾⠋⠀
⠀⠀⠀⠈⠛⠶⠶⠶⣤⣀⠀⠀⠀⠀⢠⡶⠞⠛⠒⠛⠋⠁⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠳⠶⠴⠶⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

**Comment by Cartlord** [comment]
joke p.r.

**Comment by cuackles** [comment]
Ur existance is the joke PR, this shit is as serious as it gets, probably the biggest PR in yogstation history

**Review by ToasterBiome — APPROVED** [review]

**Review by ReddicusDragon — APPROVED** [review]

**Comment by ReddicusDragon** [comment]
NO I ADDED AMOGUS

**Comment by N3D6** [comment]
> joke p.r.

Mfw when someone has the nerve to have fun and try and make funny changes

**Pull request merged**
