### PR TITLE
TEG Revengence

### PR DESCRIPTION
**Pull request by wonderinghost**
_so apparently there was a merge to delete teg when i was in the process of updating the teg engine to be not ass_

# Document the changes in your pull request

Overhauls both meta and box teg engine to be quicker to assemble and have more starting fuel
(during play over i achieved a burn time of 45 minutes to near empty tanks on max settings on box teg)

adds unlocked air alarms to both maps so engineers can do stuff

Desktop Screenshot 2023 08 04 - 00 58 50 69
Desktop Screenshot 2023 07 31 - 01 30 33 28

# Wiki Documentation

overhaul the teg wiki to be better to understand for newcomers

# Changelog
:cl:  
rscadd: adds new meta and box files
mapping: a better engine map set
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
this could have been simpler to update then just coder gunning

**Comment by LoliconSlayer** [comment]
Either you or whoever ends up merging this PR (If it gets merged at all) has to provide an actual fucking guide this time.

If not, wiki will fight this PR as much as possible.

**Comment by wonderinghost** [comment]
> Either you or whoever ends up merging this PR (If it gets merged at all) has to provide an actual fucking guide this time.
> 
> If not, wiki will fight this PR as much as possible.

dont worry im working on it tomorrow.

**Comment by N3D6** [comment]
Also - If you wish to have it actually be able to be picked, you have to edit the engine landmarks. You can probably just steal the code from when I removed it. Also need a config option to force it, another thing you can just steal from the code I removed. Make sure there is a guide though, I support this PR only if there's a proper guide

**Comment by wonderinghost** [comment]
> Also - If you wish to have it actually be able to be picked, you have to edit the engine landmarks. You can probably just steal the code from when I removed it. Also need a config option to force it, another thing you can just steal from the code I removed. Make sure there is a guide though, I support this PR only if there's a proper guide

yeah im working on a guide first before i go and scavenge code to re enable.

**Comment by Moltijoe** [comment]
> this could have been simpler to update then just coder gunning

No, it requires someone that knows atmos AND how to map, thats not exactly many people

**Comment by wonderinghost** [comment]
> 

so was darkspawn and shadowlings and they got coder gunned because no one really bothered to fix it. the teg is one of those rotted boards in yogbase. we build up problems until they actually become the problem. we fall through the boards and be mad about it

(3am bullshit)

**Comment by Hislyna** [comment]
Ew fuck no, stop trying to throw your atmos engines in engineering with 0 guides where the station has 0 power. Throw it in atmos and stop trying to bring it back

**Comment by wonderinghost** [comment]
> Ew fuck no, stop trying to throw your atmos engines in engineering with 0 guides where the station has 0 power. Throw it in atmos and stop trying to bring it back

I'm working on the wiki. Also you aren't reliant on Atmos for fuel most of the round

**Comment by wonderinghost** [comment]
I was doing this before n3's pr came in

**Comment by Hislyna** [comment]
> > Ew fuck no, stop trying to throw your atmos engines in engineering with 0 guides where the station has 0 power. Throw it in atmos and stop trying to bring it back
> 
> I'm working on the wiki. Also you aren't reliant on Atmos for fuel most of the round

Not really no

**Comment by N3D6** [comment]
The amount of hate this PR is getting is really fucking silly. The reason the TEG sucked so bad when it was in the game boiled down to two things: an inconclusive guide, and a shitty roundstart build. This PR aims to fix both of those things, and it's unfair to hate on something that has been greatly improved on because it USED to suck. Had I known this was even being in the process of being done, I wouldn't have made the TEG deletion PR to begin with. I think as a collective, we should give it a chance, instead of shitting on it before it has been tested on the server ONCE.

**Comment by azzzertyy** [comment]
i dont even get why TEG is hated, it is the simplest engine
hot thing one side
cold thing other side
it is so utterly simple i dont understand how anyone doesnt get it

**Comment by LoliconSlayer** [comment]
For the record, wiki will be working rigorously with @wonderinghost to make sure that the guide is up to the standard of every other engine's guide.

**Comment by SomeguyManperson** [comment]
> The amount of hate this PR is getting is really fucking silly. The reason the TEG sucked so bad when it was in the game boiled down to two things: an inconclusive guide, and a shitty roundstart build. This PR aims to fix both of those things, and it's unfair to hate on something that has been greatly improved on because it USED to suck. Had I known this was even being in the process of being done, I wouldn't have made the TEG deletion PR to begin with. I think as a collective, we should give it a chance, instead of shitting on it before it has been tested on the server ONCE.

did I miss a discord conversation about this because this doesn't seem to be particularly controversial

Personally, I don't like the TEG because it's just an adapter for atmos techs to turn fusion into power, and therefore lacks unique mechanics, so I don't see why it should take up roundstart engine space

**Comment by wonderinghost** [comment]
If it has pipes it is a atmos engine

**Comment by SomeguyManperson** [comment]
> If it has pipes it is a atmos engine

did you read what I said or just see who said it because I have no clue what this has to do with any of it

**Comment by azzzertyy** [comment]
> If it has pipes it is a atmos engine

behold, an atmos engine!
512px-SuperMatterGasLoopGuide

**Comment by wonderinghost** [comment]
closing to reset my repository

**Pull request closed without merging**
