### PR TITLE
changes the nightmare's objective to something more thematic

### PR DESCRIPTION
**Pull request by SomeguyManperson**
### Intent of your Pull Request

change the flavortext for the free objective nightmares get from "kill" to "return the station to darkness"

### Why is this good for the game?

it's not but an objective just saying to kill people is worse

#### Changelog

:cl:  
tweak: nightmare objective is now more T H E M A T I C
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
good and cool PR may encourage nightmares to be cool and good

**Review by MrHorizons — APPROVED** [review]
vary nais

Keep the userdanger span class, though.

**Comment by Ratvar** [comment]
Keeping station in darkness sounds like -Release engine lol-. Is it actually better than awful kill one

**Comment by SomeguyManperson** [comment]
it's better than the "kill" objective because it's more open to interperetation and functions more closely to what you'd expect a darkness related antag to be rather than being a malf AI "hijack the shuttle" equivalent that actively reduces your ability to have gimmicks

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
