### PR TITLE
adds a reactive tesla armor to the secret hilberts hotel room

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
currently the ruin is shit besides the boh which is obtainable normally so this gives a reward for solving a hard (kinda) puzzle

#### Changelog

:cl:  
rscadd: Adds a reactive tesla armor to the hilbert's hotel lore room
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
YAY THE MAP THING WORKED

**Comment by MegaEmpirical** [comment]
Having your own private room is pretty powerful in of itself.

**Comment by Codeatmos** [comment]
mah immaursian has improved thank you good sir now I can powergame harder

**Comment by AsV9** [comment]
This is too strong.

**Pull request closed without merging**
