### PR TITLE
Readd Drunken Resilience's effect because we forgot it existed for a brief minute

### PR DESCRIPTION
**Pull request by Therandomhoboo**
# Document the changes in your pull request

I forgot to add a ~~cringy~~ quip here. Now I've given alcoholics a reason to drink again. They now get minor heals from being drunk and maintaining their drunkness. Just like my Uncle.

Antag PR removed Drunken Resilience Trait working, so i've put it back in with an addition healing benefits for later drunk levels
This are kinda cumulative btw, they stack up to meet each heal drunk level criteria which means the overall heal has been slightly nerfed
 
Drunk level 11- 0.12 brute, -0.06 burn
Drunk level 41- 0.3 brute, -0.15 burn 
Drunk level 71- 0.4 brute, -0.2 burn 
Drunk level 81-0.45 brute, -0.25 burn 
Drunk level 101-0.6 brute, -0.4 burn 

# Why is this good for the game?
Makes a Quirk work
[EDITED]
I also think this is good considering it is a 4 trait point & a rng check on the drunk table. 

Around 51 drunkness you have a 3% to vomit per tick which is 15% per 10 seconds, then you get dizzy, confused, blurry vision, you can fall asleep as well and finally you take liver, brain & toxin damage. So for trying to risk and survive all of that (the damage non avoidable) I think it would be fine to do some minorly healing up.

# Testing
Its a couple line changes, it works

# Changelog

:cl:  

bugfix: Drunken Resilience back into the fray
rscadd: Drunk Level 81 & Drunk Level 101 giving heals
tweak: Drunk Resilience no longer is culmative healing 

/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
We didn't realize that all of those healing effects stack. Please change it so they don't.

**Comment by Therandomhoboo** [comment]
> We didn't realize that all of those healing effects stack. Please change it so they don't.

I mentioned a few reason in my why this is good part. I would like my side heard out at least because I think people see the culmative heals (which is minor at 101) and shit a brick. Taking into consideration the drunkness table. You start taking damage by the time you hit the 1 brute heal mark. Damage that you can't heal (toxin and brain damage). So yeah you're healing, but you're also taking damage. If you're then healing for the toxin damage and have meds, why aren't you using meds then since charcoal isn't around that often and only experts use ghetto.

I also forgot to mention, at 51 you also get a 3% to vomit. ANd if you vomit, you purge all the booze chemicals, so you would have to restart drinking as well and if you push yourself pass the 101 limit, you comatose yourself.

**Comment by Moltijoe** [comment]
Balance Council:
>make it so the heal isn't cumulative with previous thresholds

**Comment by Therandomhoboo** [comment]
> Balance Council:
> 
> > make it so the heal isn't cumulative with previous thresholds

Can I ask Balance council if they taken into consideration like I said the drunk effect levels to the actual heal, because again. You don't heal the toxin, brain or liver damage from it. 

I feel like at this rate, I would have to make a video of how ineffective it genuinely is for a 4-point slow heal that requires you to fumble through the drunk rng table

**Comment by Moltijoe** [comment]
> Can I ask Balance council if they taken into consideration like I said the drunk effect levels to the actual heal, because again. You don't heal the toxin, brain or liver damage from it.
> 
> I feel like at this rate, I would have to make a video of how ineffective it genuinely is for a 4-point slow heal that requires you to fumble through the drunk rng table

They are aware, i made sure of it

**Comment by Therandomhoboo** [comment]
> > Can I ask Balance council if they taken into consideration like I said the drunk effect levels to the actual heal, because again. You don't heal the toxin, brain or liver damage from it.
> > I feel like at this rate, I would have to make a video of how ineffective it genuinely is for a 4-point slow heal that requires you to fumble through the drunk rng table
> 
> They are aware, i made sure of it

Thank you, fine. I'll amend it.

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
