### PR TITLE
Adds self surgery

### PR DESCRIPTION
**Pull request by GuppyLaxx**
People like Hippie features now for some reason so I'm porting my favorite hippie feature :)

### CODE REVIEW

**Comment by Amelia0010** [comment]
>self surgery

**Comment by Ktlwjec** [comment]
please do not i beg you

**Comment by Bibby0110** [comment]
please do this i beg you

**Comment by CMOisLing** [comment]
Should only work for simple surgeries like tooth implants. redoing your own nervous system or doing a lung transplant ruins muh immersion

**Comment by MegaEmpirical** [comment]
As CMOisLing said, could limit it. Appendicitis could be do able for example, maybe up the brute damage/failure rates?

**Comment by GuppyLaxx** [comment]
The fact you're standing up straight up shits on your chances by fucking 1000000000, doing a surgery with multiple steps will consists of you stabbing yourself for 2 whole minutes just to replace something

**Comment by Ratvar** [comment]
Just splash yourself with alcohol and buckle yourself to bed. Or you can't?

**Comment by GuppyLaxx** [comment]
nope

**Comment by Nirnael** [comment]
>26th century
>not having an autosurgeon machine doing it all for you, instead having to dig into your own shit like fucking doctor house pulling tumors out of his leg

ss13 makes sense

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
The point of surgery is that you need a second person to get all these cool implants and whatnot.

**Pull request closed without merging**
