### PR TITLE
One handed crusher (With new sprites)

### PR DESCRIPTION
**Pull request by Xander3359**
# Document the changes in your pull request
Crusher can be held in 1 hand.
Wield the crusher to use, using the crusher unwielded will drop whatever you are holding in both hands.
Adds new crusher sprites, both item and in-hands.

# Spriting

image
image

# Wiki Documentation
Update crusher sprite and it can be carried in 1 hand now.

# Changelog

:cl:  
tweak: Crusher can now be carried in 1 hand, wield it before using or you will fumble.
imageadd: Added new crusher sprites and in-hands.
imagedel: Old Crusher sprites are gone
/:cl:

### CODE REVIEW

**Comment by Xander3359** [comment]
@MajManatee @Moltijoe Now sprites are added.

**Comment by Xander3359** [comment]
This is the same PR as https://github.com/yogstation13/Yogstation/pull/17496 but with sprites added basically, linking for the sake of discussion.

**Comment by ThatLing** [comment]
Balance council approved

**Comment by MajManatee** [comment]
Gotta wait for jamie and a sprite maintainer (6-12 buisness years)

**Review by ToasterBiome — APPROVED** [review]
sprite fine

**Pull request merged**
