### PR TITLE
Kills items-and-weapons.dmi

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Moves almost everything out of items-and-weapons.dmi and renames it to misc.dmi as the old name doesn't fit it and this one makes more sense. Also reorganizes some other files that made sense when I was fixing stuff up. Probably going to have some issues as its touching so many files, but it builds so it's ready to merge.

# Wiki Documentation

No changes needed. 

# Changelog

No player facing changes

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
don't worry soldier scout was lying items-and-weapons.dmi is not real
thank
GOD

**Comment by JamieD1** [comment]
What does TG do with this file these days?

**Comment by JamieD1** [comment]
@nmajask Following up

**Comment by nmajask** [comment]
> What does TG do with this file these days?

they have it organized like we do currently

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
