### PR TITLE
The Den of Sin Jungleland ruin

### PR DESCRIPTION
**Pull request by Marmio64**
# Document the changes in your pull request

thedenofsin

Adds the Den of Sin, an immortal gambling house of sin, run by a demon of greed who wants to make as much money as possible. The owner is indeed an actual demon of sin which i recognize is probably going to be controversial. They do have a punishing teleporter implant that hurts and teleports them back if they try to go off planet, but there is still an ability to abuse this, and I can just make them a normal person instead if it is too much.

Other than that, this is just a big casino and bar, not unlike the Inn from icemoon.

# Why is this good for the game?

Cool new jungleland ruin with an extra ghost role. Potential for extra rp.

# Testing
ran on a private server, all works well
thedenworks

# Wiki Documentation
thedenofsin

The Den of Sin is a casino run by a demon of greed who wants to get as much money as possible. If you're willing to risk some cash, or even your life, maybe you might get rich too...

# Changelog

:cl:  
rscadd: Adds the Den of Sin, a jungleland casino run by a demon.
/:cl:

### CODE REVIEW

**Comment by milk-is-cool** [comment]
it would be awesome if there was the greed slot machine like the lavaland one. that way it would actually justify having the guy who runs the place be a demon of greed because they arent able to use the greed slot machine

**Comment by Marmio64** [comment]
> it would be awesome if there was the greed slot machine like the lavaland one. that way it would actually justify having the guy who runs the place be a demon of greed because they arent able to use the greed slot machine

the demon of greed can summon the slot machine, they are the antag itself, so I didn't bother with adding a stand alone one.

**Comment by patpol4** [comment]
Did you test this for lighting? There's lots of empty space

**Comment by patpol4** [comment]
Ok i just noticed you did, nvm

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
