### PR TITLE
Modular Computer Tweaks P1

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request

moves ntmonitor software into engineering folder (organization)
construction bag can now hold computer parts
both pda and phone can now accept small computer parts
advanced network card is now a small size item compared to tiny
wired network card is now a normal size item compared to bulky

telescreens can now download camera programs 
microprocessors max tabs have been tweaked (cheep - 2, micro -3, photo -4)

# Why is this good for the game?
attempting to revitalize modular computers, tweaking things to try and warrant upgrades along with minor changes and qol before any massive changes (things like programming hardware failure or more features/faster apps with better equipment) 

allowing telescreens that couldnt download them just felt weird. for being a wall mounted console you get a free tile and a visually cool item

moving pda and phone to accept small items allows for more upgrades, things like better batteries or storage (those are next on the block)

rebalancing of those two network card sizes just makes assembling of devices easier, mainly for the wired network card becuase again its weird that it cant be accepted while visually the advanced network card is the same size sprite but was classified tiny 

# Testing
checked to make sure nothing is applied weirdly multiple times

cheep microprocessor
image

image
image
image

# Changelog

:cl:  

tweak: max tabs in microprocessors have been reduced by one
tweak: telescreens can now download camera software
tweak: construction bag can now hold computer parts
tweak: wired network card has added one bulk to advanced network card
tweak: pdas and phones can accept small computer parts

/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
accidentally pressed enter when making the title

**Comment by wonderinghost** [comment]
there updated

**Comment by MajManatee** [comment]
who knew microprocessors were made of baby chickens. Why else would they be "Cheep"

**Review by MajManatee — DISMISSED** [review]
Also include a gif, picture, or other proof of testing

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
