### PR TITLE
[s] redoes the armoury and warden's office layout

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Armoury looks much less cluttered now, with roughly the same contents. 
image

#### Changelog

:cl:  
tweak: The armoury and warden's office have been remapped, so now they're much less cluttered.
/:cl:

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
r o u g h l y

**Comment by Amelia0010** [comment]
yeah, roughly

**Comment by jcatjmeow** [comment]
I like, also people coming from space don't risk deconning a wall to find a filing cabinet blocking the way

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Armory looks nice, the flashers look kinda strange in the middle there

**Comment by Nirnael** [comment]
Where do the barrier grenades, pins, secway, training bomb, contraband locker, canister go? Can the AI see the warden's office air alarm? Also, those windoors to the armory are really bad. Right now they are outside the armory. Now they are inside and it's much much easier to break in, not to mention that they aren't reinforced. Are there firelocks on the armory doors? Fire alarm?

**Comment by Amelia0010** [comment]
>barrier grenades
>pins
>contraband locker
>training bomb

Forgot those

>secway

this was removed from the armoury in a previous PR

>Canister

Why's there even a canister in there, there wasn't prebase and it serves no purpose, as there's already 3 canisters in the transfer room.

>Can the AI see the warden's office air alarm?

Yes.

>Also, those windoors to the armory are really bad. Right now they are outside the armory. Now they are inside and it's much much easier to break in, not to mention that they aren't reinforced.

They weren't reinforced before, and the warden can still see the windoors from his seat, so meh. 

>Are there firelocks on the armory doors? Fire alarm?

No, and there weren't before.

**Comment by Nirnael** [comment]
> They weren't reinforced before, and the warden can still see the windoors from his seat, so meh.

That's because they didn't lead into the armory before. They led outside. With your change they lead inside.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
:confused:

**Pull request closed without merging**
