### PR TITLE
adds my donator item before it becomes illegal

### PR DESCRIPTION
**Pull request by thegoldencat413**
# Document the changes in your pull request

i have no idea if i did any of this right

thanks for the help from blutsu, lazenn, and sol

# Spriting
mojadripr

mojadripf

# Wiki Documentation

none

# Changelog

adds a torn up jacket as ckey donator item
:cl:  
imageadd: Added torn jacket donator item

/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
2 things u have conflics issues and also it deletes like 3 clothing items

**Comment by thegoldencat413** [comment]
IM WORKING ON IT

**Comment by thegoldencat413** [comment]
ok oops it doesnt say conflict anymore (does that mean im okay now?) 

and i dont see any red so i think im not accidentally removing anything anymore

**Comment by solwashere** [comment]
If you ever feel bad just ask Cuackles what happened when he tried to add my item

**Comment by Moltijoe** [comment]
incorrect changelog formatting
please include the spriteadd changelog tag and change the tag description to mention exactly what is added

**Review by Moltijoe — APPROVED** [review]
code checks out

**Comment by thegoldencat413** [comment]
okay uhhmmmmmmm i think i did that stuff?

**Comment by adamsong** [comment]
On hold while new procedures for donator items are implemented

**Review by cuackles — APPROVED** [review]

**Comment by thegoldencat413** [comment]
uhh nevermind i dont really want to deal with all that

**Pull request closed without merging**
