### PR TITLE
Bye now pointless spell (Cluwne Curse removal)

### PR DESCRIPTION
**Pull request by Therandomhoboo**
# Document the changes in your pull request

3 minutes = ided & noobbait. Could of done anything else but who cares at this point.
Long story short, removing Cluwne curse because 3 minutes is excessive could of made Cluwne curse temp, or easier to remove or even shorten the curse distance.
I've had to also amend the shitwiz getting a chance to get cluwnecurse due to it now being gone and so i replaced it with slip. Because slip is funny.

# Why is this good for the game?

People shit themselves over being changed against their will anyway, plus the 3 minute timer is cbt so its good for the game because it stops people noob-baiting themselves and saves the crew from crying cause they got changed for one round.

# Testing

Lol no

# Wiki Documentation

Wiz spell for Cluwne curse needs to be removed and scrubbed from the records

# Changelog

:cl:  
rscdel: Cluwne Curse is gone because 3 minutes might as well be 1 use per round
rscdel: Shitty wizards can't have a chance to spawn with Cluwnecurse spell
rscadd: Shit wiz's now have Slip spell instead of Cluwnecurse
/:cl:

### CODE REVIEW

**Comment by CrazyDrakkon** [comment]
Curse of Madness deserves the bullet more imo, or at least its most annoying traumas.

**Comment by Therandomhoboo** [comment]
> Curse of Madness deserves the bullet more imo, or at least its most annoying traumas.

Curse of Madness only happens via event. According to code. 
https://github.com/yogstation13/Yogstation/blob/05277192c5d4badd2e1a56e00f323b50ef9200fa/code/modules/events/wizard/madness.dm#L25

SO na they dont

**Comment by GrowlTheLost** [comment]
I do not want the spell to be removed because it has been amusing to me in the past.

Your code looks reasonable and I like slip. Please just add slip and don't remove Cluwnecurse.

If you insist on removing the spell from the spell book, please don't remove the file containing it; that is just shitting on the coders that worked on coding the actual spell at that point. Last I checked, you can also get Cluwned from putting on the mask of a dead floor cluwne, so... there is that reference too...

Curse of madness is caused by an event, yes. You can trigger this event yourself from a spellbook if you are a wizard.

I'd mention certain other things that change people, but I do not like the idea of even more game mechanics being taken away... again.

**Comment by Therandomhoboo** [comment]
> I do not want the spell to be removed because it has been amusing to me in the past.

It is amusing but the 3 minute timer has just snuffed its gimmicky use. It is 3 minutes and only has a range of 3 tiles. It is just pointless to have a spell like this in

> If you insist on removing the spell from the spell book, please don't remove the file containing it; that is just shitting on the coders that worked on coding the actual spell at that point. Last I checked, you can also get Cluwned from putting on the mask of a dead floor cluwne, so... there is that reference too...

Its easier to remove the file containing it because if this pr gets through and someone wants it back, all they have to do is revert this pr. It doesn't erase the work of coders completely. Also the spell cluwne and the floor cluwne/mask are separate things so this shouldn't affect the code or affect it lore wise.

> I'd mention certain other things that change people, but I do not like the idea of even more game mechanics being taken away... again.

I already know the spells that do, as im pretty sure most coders/people do. I am against really the hate of "shape-shifting" spells cause its just part of the game. People hate being changed hence why that cluwne spell got slapped.

**Comment by MajManatee** [comment]
Or you could just do a partial revert and instead do your changes while leaving the time unchanged or less affected.

**Comment by wonderinghost** [comment]
called it

if more fuel is going to be tossed here i suggest a compromise.

2 minutes at most for cool down, however add a cure and/or a tell to when its being casted
being cluwned is among the worse things to be afflicted with, the ability to cure it by say, holy water or something other than being permanently debuffed unless dead and cloned

**Comment by PibeCantina** [comment]
Fuck clown

**Comment by Therandomhoboo** [comment]
> called it
> 
> if more fuel is going to be tossed here i suggest a compromise.
> 
> 2 minutes at most for cool down, however add a cure and/or a tell to when its being casted being cluwned is among the worse things to be afflicted with, the ability to cure it by say, holy water or something other than being permanently debuffed unless dead and cloned

I would say make it 1.40(100secs) mins at least to give it some leeway if we're going to add those on tbf. I tink that is a better compromise if thats chill?

As for the cure, I'd would prefer we go with a tell like giving it the magus effect cause that is a big tell no? can also add noise if you want. Let me know what your thoughts are on it cause i would too prefer not to remove it.

**Comment by RG4ORDR** [comment]
> called it
> 
> if more fuel is going to be tossed here i suggest a compromise.
> 
> 2 minutes at most for cool down, however add a cure and/or a tell to when its being casted being cluwned is among the worse things to be afflicted with, the ability to cure it by say, holy water or something other than being permanently debuffed unless dead and cloned

There's about 4 spells current that require 1 tile range and touching to inflict a massively annoying result.
Ei'nath - instant kill but long cooldown already a noobbait spell
Pacification - Literally worse than Cluwne AND Ei'nath combined because you're turned into a simple mob.
Curse of the duffle bag - Annoying but can be countered easily by feeding it bad stuff.
Mindswap - Literally got removed from the spellbook before. because it did the job it was designed to do perfectly 

You can easily make Cluwne a 1 tile range touch spell and keep it on a 1 minute timer.

**Comment by Moja10** [comment]
I agree on not removing the spell, it could easily be used for an event and given directly via admin powers, all it needs to be for the purpose of this PR is not in the spellbook.

**Review by Moltijoe — APPROVED** [review]

**Comment by hairykidney** [comment]
more terrible prs that gut the game, amazing

**Comment by GrowlTheLost** [comment]
That's a piece of history down the drain. Therandomhoboo has a very good point about the spell being next to useless after the nerf. No two ss13 servers should be the same, but I do not like how this particular change just kept getting worse until someone had to notice the obvious and remove the thing changed completely.

**Pull request merged**
