### PR TITLE
Allows traitorvamp to roll at lowpop

### PR DESCRIPTION
**Pull request by Moltijoe**
Breaking the feature freeze for something that's probably important
from required_players = 25 to = 15
reduces number of traitors roughly by 1/2

# Why is this good for the game?
Constant traitor rounds are rough on lowpop, and it lends each round to feeling fairly tame

# Testing
number changes

:cl:  
tweak: Traitor Vampire gamemode can now roll during lowpop
tweak: Traitor Vampire now spawns less traitors to make up for the vampires it spawns
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
Oops! All vampires

**Comment by Moltijoe** [comment]
> Oops! All vampires

It should realistically only ever spawn a single vamp and traitor in that lowpop

**Comment by LassiH** [comment]
cant vampires make other people vampires or is this bloodsucker

**Comment by Moltijoe** [comment]
> cant vampires make other people vampires or is this bloodsucker

vampire can, yes, so theoretically they could make everyone a vampire
but they can always do that

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
