### PR TITLE
Map changes that ruffle my jimmies

### PR DESCRIPTION
**Pull request by Readystorm546**
So There was this one time i died because of a carp spawn that went into the line of me shooting my bomb into the testing area. I shot the bomb and then it hit the carp and when i blew up the bomb it blew up part of the station as the bomb did not reach the testing area. SO i moved the carp spawn and I also changed some turf arrangements that were inconstant with the rest of the station. This includes some near spacestaion tiles that were not coherent with the rest of the station and an extra pair of fire locks that legit did nothing. They were located in south east mait.

image

Lots of map changes because of atmos system. I had to remove some firelocks that legit made no sense and also did not baby the crew because we are not all fucking retarded i hope. Various fire firelocks have been removed along with random doors spawns in some areas. New Firelocks in some other key check points. Also fixed the maintenance area with the hidden medical area.

:cl:  
tweak: Changed around some carp spawn locations.
rscdel: Removed some useless firelock placement. inconstant spacestation tiles 
i died
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Maintainers sleeping no "i ded" label

**Comment by Readystorm546** [comment]
> Maintainers sleeping no "i ded" label

I agree

**Comment by Amelia0010** [comment]
`along with random doors spawns in some areas.`
why

**Comment by Readystorm546** [comment]
> `along with random doors spawns in some areas.`
> why

It doesn't work with the new fire-lock system. You either have a fire-lock on every door or you dont. Like sometimes the firelock would just be in a wall because the game did not decide to generate a door that round. As a result of this it gives away hidden areas in mait while also looking off because its in a fucking wall.

**Comment by Amelia0010** [comment]
>It doesn't work with the new fire-lock system. You either have a fire-lock on every door or you dont. Like sometimes the firelock would just be in a wall because the game did not decide to generate a door that round. As a result of this it gives away hidden areas in mait while also looking off because its in a fucking wall.

Correct solution would be to have the firelock get deleted when the airlock is deleted, see: https://github.com/yogstation13/Yogstation/blob/10fe677374c20ce0cf0e88b1e77bfe688a1f5bfd/code/game/machinery/doors/airlock.dm#L143

**Comment by Ktlwjec** [comment]
Approved besides the following:
- The maint_surgery.dmm file needs a maintenance area (/port/fore), not /template_noop
- Agree with Nich it would be best to do it that way.
- Weird airlock placement and pipes/wires missing underneath it:

**Comment by Readystorm546** [comment]
> > It doesn't work with the new fire-lock system. You either have a fire-lock on every door or you dont. Like sometimes the firelock would just be in a wall because the game did not decide to generate a door that round. As a result of this it gives away hidden areas in mait while also looking off because its in a fucking wall.
> 
> Correct solution would be to have the firelock get deleted when the airlock is deleted, see:
> 
> https://github.com/yogstation13/Yogstation/blob/10fe677374c20ce0cf0e88b1e77bfe688a1f5bfd/code/game/machinery/doors/airlock.dm#L143

I fixed the map for you to fix the code because im fucking dumbfounded by it

**Comment by Readystorm546** [comment]
So monster helped me out and this PR correlates with #7461

**Pull request merged**
