### PR TITLE
No more making golem shells with atmos

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
metallic hydrogen is braindead easy to make, making infinite unga golem army with stupid high inbuilt armor, fireaxes, and inbuilt antimagic (???) is fucking dumb, especially since you can make hundreds and hundreds of them. you can still make metallic hydrogen golems, you just need an inert golem shell from somewhere else, eg adamantine from xenobiology.

# Changelog

:cl:  
rscdel: metallic hydrogen can no longer produce golem shells
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
that was my pr e

**Comment by redmoogle** [comment]
image

there is about 2000 metallic hydrogen too

**Comment by TheRyeGuyWhoWillNowDie** [comment]
it just keeps getting worse because golems inherit conversion antag datums from their master

**Comment by Bibby0110** [comment]
why am I in your commits

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> why am I in your commits

because i fucked up git

**Comment by JamieD1** [comment]
Pretty sure this stems from my fucking up the metallic hydrogen math

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
