### PR TITLE
remove dolphin migration

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

this is a nothingburger event. it literally does nothing. dolphins do nothing. it is a waste of a good event slot and I weep every time I see dolphins
# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscdel: remove dolphin migration
/:cl:

### CODE REVIEW

**Comment by UltraBigRat** [comment]
Fair, dolphins do kinda suck

**Comment by Notamaniac** [comment]
simplehorror you're just meant to go into stasis, feature freeeeeeeze go to sleeeeeep

**Comment by Marmio64** [comment]
Hate aurora, hate flavor events, if it's not a monster that can demolish the solar system it doesn't deserve to take up a slot

**Comment by Simplehorror** [comment]
name one way this has had an impact on your round

**Comment by Hopekz** [comment]
> name one way this has had an impact on your round

Seeing a dolphin brought me joy even if I learned later on that it doesn't do anything.

It's okay to have features that do nothing except add to the ambiance

**Comment by ToasterBiome** [comment]
the dolphin meat is useful for cooking

**Comment by Bibby0110** [comment]
We like nothinburgers

**Pull request closed without merging**
