### PR TITLE
Fixes an absolutely disgusting mapping error in Meta maints

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request
Fixes a disgusting error in meta maints where there was a window, wall, and a sink all on the same tile. Removed the sink and the wall, it's just a window now.
image
This is untested but I don't see why it wouldn't work
# Wiki Documentation
Don't need
# Changelog

:cl:  
bugfix: Fixes a mapping error in meta maint
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
It's better if you unfuckle it by placing it somewhere else instead of removing a unique sink.
 Also theres that one cobweb next to the red airlock that's just hanging on nothing, can you get rid of that?

**Comment by N3D6** [comment]
> It's better if you unfuckle it by placing it somewhere else instead of removing a unique sink.
> Also theres that one cobweb next to the red airlock that's just hanging on nothing, can you get rid of that?

I'll try, but as far as I know the sink is only different by name but I'll check and see if I'm wrong

**Comment by N3D6** [comment]
> It's better if you unfuckle it by placing it somewhere else instead of removing a unique sink.
> Also theres that one cobweb next to the red airlock that's just hanging on nothing, can you get rid of that?

Deleted the cobweb, as far as I know the sink isn't any different to a normal one, it just has a fancy name but if you want it to be placed somewhere else I can go ahead and knock it out

**Comment by N3D6** [comment]
Gonna make this in a new PR because I'm too lazy to fix the conflicts

**Pull request closed without merging**
