### PR TITLE
aheal lizard no make tail smooth uwu

### PR DESCRIPTION
**Pull request by SomeguyManperson**
tail still smooth if it gets replaced though
:cl:
bugfix: aheal lizard no make tail smooth
bugfix: aheal no make lizard leg straight
/:cl:

### CODE REVIEW

**Comment by gilvian** [comment]
??

**Comment by SomeguyManperson** [comment]
### aheal lizard no make tail smooth

**Comment by Sir-Lagsalot** [comment]
@gilvian there's a glitch with lizardpeople, when they get ahealed it resets their customization options

Before aheal:
image
After aheal:
image

**Comment by SomeguyManperson** [comment]
yerdoingood-2

**Pull request merged**
