### PR TITLE
Adds a prisoner role/job

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Adds a prisoner role that spawns you in perma
Has 2 job slots, no access, nothing extra

# Wiki Documentation

Prisoner role has no supervisors or paychecks

# Why it is good for the game
For people who may want to RP in perma or experiment around with a mostly peaceful enviroment

# Changelog

:cl:  
rscadd: Added a prisoner job
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
rp role?? 👀 
sadly, i feel like many people are going to interpret the role as "do you want to spawn as a sanctioned self-antag?"

**Comment by redmoogle** [comment]
> rp role?? 👀 realistically i feel like many people are going to interpret the role as "do you want to spawn as a sanctioned self-antag?"

They'll probably be fairly weak as they have no starting stuff.

**Comment by LazennG** [comment]
no thanks bro i'd rather not have to deal with an extra prisoner who'll try to kill sec with a spear and bolas every time i perma someone

**Comment by redmoogle** [comment]
Although that'll be up to councils/badmins as to if they can self-antag some

**Comment by ynot01** [comment]
> many people are going to interpret the role as "do you want to spawn as a sanctioned self-antag?"

**Comment by redmoogle** [comment]
> no thanks bro i'd rather not have to deal with an extra prisoner who'll try to kill sec with a spear and bolas every time i perma someone



> > many people are going to interpret the role as "do you want to spawn as a sanctioned self-antag?"

Ok, go make a ruling on it

**Comment by patpol4** [comment]
Needs some sort of a ruleset for sure

**Comment by Xoxeyos** [comment]
Nope, never going to want to see this in game.

**Comment by redmoogle** [comment]
> Nope, never going to want to see this in game.

why not

**Comment by Xoxeyos** [comment]
> > Nope, never going to want to see this in game.
> 
> why not

Because it's just going to make the job of security a pain in the ass, it's a role that can easily lead to shittery, and I am just against it all together. Nothing will change my mind. I also don't want to deal with dumbasses that pick this just to fuck around.

**Comment by redmoogle** [comment]
> > > Nope, never going to want to see this in game.
> > 
> > 
> > why not
> 
> Because it's just going to make the job of security a pain in the ass, it's a role that can easily lead to shittery, and I am just against it all together. Nothing will change my mind. I also don't want to deal with dumbasses that pick this just to fuck around.

easy way to get rid of shitters then

**Comment by Xoxeyos** [comment]
> > > > Nope, never going to want to see this in game.
> > > 
> > > 
> > > why not
> > 
> > 
> > Because it's just going to make the job of security a pain in the ass, it's a role that can easily lead to shittery, and I am just against it all together. Nothing will change my mind. I also don't want to deal with dumbasses that pick this just to fuck around.
> 
> easy way to get rid of shitters then

What's even the point of this role?

**Comment by redmoogle** [comment]
> > > > easy way to get rid of shitters then
> 
> What's even the point of this role?

For players that may want to play around in perma and have a *mostly* peaceful enviroment

**Comment by Xoxeyos** [comment]
> > > > > easy way to get rid of shitters then
> > 
> > 
> > What's even the point of this role?
> 
> For players that may want to play around in perma and have a _mostly_ peaceful enviroment

I very much doubt people want to stay in perma, or do anything in there; If you really feel this is a good addition to the game, make a job timer so that new players can't just hop in and fuck other with other people on the server.

**Comment by redmoogle** [comment]
> > For players that may want to play around in perma and have a _mostly_ peaceful enviroment
> 
> I very much doubt people want to stay in perma, or do anything in there; If you really feel this is a good addition to the game, make a job timer so that new players can't just hop in and fuck other with other people on the server.

already done, 2 days age and 30 minute requirement; although im open to bump those values up

**Comment by Xoxeyos** [comment]
> > > For players that may want to play around in perma and have a _mostly_ peaceful enviroment
> > 
> > 
> > I very much doubt people want to stay in perma, or do anything in there; If you really feel this is a good addition to the game, make a job timer so that new players can't just hop in and fuck other with other people on the server.
> 
> already done, 2 days age and 30 minute requirement; although im open to bump those values up

Do you think it would be acceptable for a security job timer as well as a crew job timer? I'd rather those who take the prisoner job have to take time as a security officer as well, since it may make them more sympathetic towards other players within the department, while also having a higher possibility of gaining experience with space law. Knowledge of space law may lead to engaging role play opportunities.

**Comment by redmoogle** [comment]
> > > > For players that may want to play around in perma and have a _mostly_ peaceful enviroment
> > > 
> > > 
> > > I very much doubt people want to stay in perma, or do anything in there; If you really feel this is a good addition to the game, make a job timer so that new players can't just hop in and fuck other with other people on the server.
> > 
> > 
> > already done, 2 days age and 30 minute requirement; although im open to bump those values up
> 
> Do you think it would be acceptable for a security job timer as well as a crew job timer? I'd rather those who take the prisoner job have to take time as a security officer as well, since it may make them more sympathetic towards other players within the department, while also having a higher possibility of gaining experience with space law. Knowledge of space law may lead to engaging role play opportunities.

Will think about adding the job timers; shouldnt be too hard

**Comment by cowbot92** [comment]
Might be better to spawn them on the lavaland gulag imo but give them an implant that teleports them back to lavaland if they leave via shuttle. (or leave the z-level at all)

**Comment by ynot01** [comment]
> Ok, go make a ruling on it

Even if I hated every single admin on the team I would not want them to deal with this shit

**Comment by maxion12345** [comment]
>2 prisoners spawn
>no warden spawns
>prisoners now have fuckall to do

**Comment by redmoogle** [comment]
meh.

**Pull request closed without merging**
