### PR TITLE
phpminor handholds me through editing rod crafting

### PR DESCRIPTION
**Pull request by Potototatoh**
### Intent of your Pull Request
you can no longer make metal rods out of your hands and now takes a welder to do the thing

#### Changelog

:cl:  
tweak: yu cant make metla rods thorugh using your big monkey arms anymore 
bugfix: why were u able to do that
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
But my arm lathe worked fine for years wtff

**Comment by boodaliboo** [comment]
oi arm dfsl ate how

**Comment by ynot01** [comment]
so you're gonna ruin rods but leave all the other shit you can craft with your bare hands like apc frames, lockers, etc

**Comment by boodaliboo** [comment]
> oi arm dfsl ate how

you rtemoved the arm machine make it use wire cutewrs not welder dumbd

**Comment by yacabo** [comment]
>so you're gonna ruin rods but leave all the other shit you can craft with your bare hands like apc frames, lockers, etc

Don't forget the airtight walls that can withstand the pressure of a star

**Comment by Ktlwjec1** [comment]
Sort out your changelog:

- Things like "bugfix: why were u able to do that" is absolutely useless when it has nothing relating to what it fixed.
- tweak: yu cant make metla rods thorugh using your big monkey arms anymore -> tweak: You can't make metal rods using your arms anymore.

**Comment by deathslayer2481** [comment]
This is an unfun change.

**Comment by LoliconSlayer** [comment]
You realize that it still doesn't make sense to make perfectly straight metal rods out of a welder right. Why are you "fixing" a problem that didn't exist, there's no good reason to do this other than just inconveniencing people for the sake of inconvenience.

**Comment by Potototatoh** [comment]
itws broken as fuck and when i made the pr i was half asleep

**Comment by MegaEmpirical** [comment]
So what are the gameplay reasons here?

**Comment by alexkar598** [comment]
This is stupid and so are you

**Pull request closed without merging**
