### PR TITLE
Deletskub

### PR DESCRIPTION
**Pull request by Mr-Space**
### Intent of your Pull Request

I will not be silenced by alexkar

#### Changelog

:cl:  

rscdel: Deletes useless skub

/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
This is a horrible PR and the guy that made it should feel bad

**Comment by ghost** [comment]
Watch this get speed deleted.

**Comment by alexkar598** [comment]
You have no reason to close PRs bibby

**Comment by alexkar598** [comment]
Shitty PR

**Pull request closed without merging**
