### PR TITLE
Toxins change

### PR DESCRIPTION
**Pull request by Readystorm546**
There are two items that are never used for bombs and they should be on the toxins table. So i put them there and stuff. The voice analyzer which picks up a voice command to make a bomb go off. And the health one that checks your health and makes a bomb go off if your health is below a threshold.

### CODE REVIEW

**Comment by Readystorm546** [comment]
Travis is bugged and its not my fault

**Comment by Szyszkrzyneczka** [comment]
Travis hates you

**Comment by Amelia0010** [comment]
```
1.24s$ tools/travis/check_grep.sh
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_x = -6;
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_y = -1
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_x = -5;
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_y = 12
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_x = 8;
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_y = 3
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_x = -7;
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_y = -4
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_x = 7;
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_y = -4
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_x = 2;
_maps/yogstation/map_files/YogStation/YogStation.dmm:	step_y = 7
step_x/step_y variables detected in maps, please remove them.
```

Travis isn't bugged and it is your fault

**Comment by Readystorm546** [comment]
But how could i have even done this. Like what did i do to cause this?

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
