### PR TITLE
Splits the Emag into two devices: the Airlock Cracker and the Everything-Else Emag

### PR DESCRIPTION
**Pull request by Altoids1**
# Why?
EqualizerNerf

I'm normally not one to go onto the **_FeAtUrE CReEp_** bandwagon, but the Emag is a rare example of this genuinely happening in-game. There are about 100 different ``emag_act()`` definitions in the code, and with the upcoming addition of https://github.com/yogstation13/Yogstation-TG/pull/6199 I think it's high-time we separate this thing between its most common use and all of its miscellaneous ones.

## Changelog
:cl: Altoids
rscadd: The Airlock Cracker traitor item has been added, for 5 TC.
rscdel: The Emag can no longer emag airlocks. This ability has been moved over into the Airlock Cracker.
tweak: The Emag's TC cost has been lowered to 5 TC.
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
ehh i dont like it but its a good balance change

**Comment by Alek2ander** [comment]
I have a feeling that the main use case for emags is actually lockers. Doors are very easy to hack with common tools, after all.

**Comment by HomocidlePancakes** [comment]
>There are about 100 different emag_act() definitions in the code,

And most of them are either neiche and barely used, or meme. When you remove all that bloat, you are left with like 4.

**Comment by Manly-Dwarf** [comment]
pretty interesting way to take apart the emag, one for all-access and one for all the joke stuff
like the guy said above I don't really like it but it's one of those things that kinda has to be done at some point.

**Comment by nesisknesis** [comment]
Rename it to 'Door Jack', airlock cracker sounds wack

**Comment by HomocidlePancakes** [comment]
@Manly-Dwarf And why it has do be done? Never seen anyone complaining about how emag is too OP.
@Altoids1 Syndiborgs will need both items.

**Pull request closed without merging**
