### PR TITLE
[PORT] New Heretic Path Semi-Port: Void Path

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request
ALL CREDIT FOR SPRITES + MAJORITY OF CODE GO TO https://github.com/tgstation/tgstation/pull/54252 - Code was only adjusted to better fit our codebase in certain areas, attempted to keep as much authentic as possible.

Path of Void

Glimmer of Winter - Transmute a knife and a shard of glass to create a Frozen Blade

Grasp of Void - Your Mansus grasp now temporarily mutes your target for 10 seconds, additionally lowering their body temp.

Grasp Mark - Mark of The Void - Your Mansus Grasp now applies the Mark of Void. The mark is triggered from an attack with your Void Blade. When triggered, further silences the victim and swiftly lowers the temperature of their body and the air around them.

Blade Upgrade - Shiva's Kiss - Your blade will now inject a freezing venom into your targets.

T1- Void Cloak - Allows you to transmute a glass shard, a bedsheet, and any outer clothing item (such as armor or a suit jacket) to create a Void Cloak. This cloak will greatly increase the user's speed, but will cause them to take significantly more damage.

T2- Void Blast - Grants you Void Blast, a spell that shoots out a freezing blast in a cone in front of you, freezing the ground and any victims within.

T3 - Diamond Dust - A powerful spell that calls forth memories of ice, will create a large area of ice around you, freezing the ground for a long period of time

T1 ability - Void Phase - Grants you Void Phase, a long range targeted teleport spell. Additionally causes damage to heathens around your original and target destination.

T2 ability - Aristocrat's Way - Grants you immunity to cold temperatures, and removes your need to breathe. Gain immunity to slipping on ice. You can still take damage due to a lack of pressure.

T3 ability - Void Pull - Grants you Void Pull, a spell that pulls all nearby heathens towards you, stunning them briefly.

Ascension - Waltz at the End of Time - Bring 3 corpses to a transmutation rune to complete the ritual. When completed, causes a violent storm of void snow to assault the station, freezing and damaging heathens. Additionally, you will become immune to the effects of space and take reduced damage

https://github.com/yogstation13/Yogstation/assets/75333826/c8ba0f8f-0f67-4e85-9aba-5904cd859da0

# Why is this good for the game?
More heretic paths! Much more fun options to choose from!

# Testing
I tested all of the abilities, items and item creation, and ascension as well as the lore that comes when you end the game. 

# Spriting

Void_blade
Void_blade_inhand
Void_blade_inhand_left

VoidPhase_Pull

Void_cloak_floor
Void_cloak_body

# Wiki Documentation

As per my previous PRs, there's too much documentation to be sent here, will provide to wiki at a later date.

# Changelog

:cl:  
rscadd: Adds new heretic path - Void
soundadd: Adds new sounds to go with heretic abilities 
imageadd: Adds new sprites for Void Blade and abilities
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
should heretics really have 3 escape abilities?

**Comment by cowbot92** [comment]
> should heretics really have 3 escape abilities?

This will be addressed in future PRs I have planned.

**Comment by ManofSan** [comment]
now i wait for the knife path port

**Review by cuackles — APPROVED** [review]

**Comment by Moltijoe** [comment]
oh fuck misclick

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
has conflicts with mqiib's lizard fetish pr

**Comment by Hislyna** [comment]
SNOWWWWWWWWWWWWWWWWWWWWWWWWW

**Comment by GDRdev** [comment]
heretics are coolio

**Comment by bruhlookatthisdood** [comment]
add fulp's void ascension music <3

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
