### PR TITLE
Lowers dynamic weight

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Our version of dynamic is very ungood and thus should roll less

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Dynamic weight has been lowered from 12 to 7
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Make it gooder

**Comment by neeshacark** [comment]
but i LIKE dynamic!!!!!

**Comment by Hislyna** [comment]
Dynamic, aka fuck all happens

**Comment by JohnFulpWillard** [comment]
This is just hiding a bad feature by making it rare, making it less likely to be fixed by a contributor in the future.
I'd rather we deal with it ASAP than try to kick it further down the road.

**Comment by iamthesilly** [comment]
Agree with John on this one, dynamic being bad is a reason to make it better, not to make it less common.

**Comment by Hislyna** [comment]
Mfw Slings and Dspawn still spawn on Dynamic (They still dont work right)

**Comment by JohnFulpWillard** [comment]
It's been over 24 hours and still no maintainer showed support for this PR, if a maint disagrees they can reopen the PR

**Pull request closed without merging**
