### PR TITLE
Adds bluespace pipes

### PR DESCRIPTION
**Pull request by monster860**
They were added to tg a while ago, but they made it so you could make them for free using RPD's which got them removed. This PR adds them here but with the following changes:

- you need to make them using science
- you can specify the name of a bluespace pipe network to attach to

:cl: monster860
add: Adds bluespace pipes. You make them using science, and you can specify a network to attach to by using it in your hand.
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
oh no

**Comment by ghost** [comment]
Still really strong and considering everyone researches bluespace tech ASAP it's not much of a gate. Increase the diamond costs.

**Review by Amelia0010 — APPROVED** [review]
don't see anything immediately wrong, but I'm wondering whether these use layers or not

**Comment by monster860** [comment]
unless there's a way to change the layer of a pipe item, no it doesn't work with layers.

**Comment by Amelia0010** [comment]
ok cool

**Pull request merged**
