### PR TITLE
fixes a chair in meeting room

### PR DESCRIPTION
**Pull request by redmoogle**
###  Intent of your Pull Request

- Fixes a "gamebreaking" bug of where 2 chairs are stacked on each other in the meeting room.

#### Changelog

:cl:  
rscdel: Removed a stacked chair from command meeting room
/:cl:

### CODE REVIEW

**Review by patpol4 — APPROVED** [review]
cool

**Review by patpol4 — CHANGES_REQUESTED** [review]
Actually hold on, why did you keep the teal chair and not the black chair, it stands out for no reason

**Comment by redmoogle** [comment]
> 
> 
> Actually hold on, why did you keep the teal chair and not the black chair, it stands out for no reason

didnt think it mattered I'll go re-add it(also didnt notice the pattern because the area stuff was blocking some of the color out)

**Review by patpol4 — APPROVED** [review]
Alright now it's cool.

**Review by Ktlwjec1 — APPROVED** [review]

**Pull request merged**
