### PR TITLE
Rescales Negative Armor Piercing Effectiveness

### PR DESCRIPTION
**Pull request by Mqiib**
This is a weird one. AP right now is REALLY BORING because it's just a linear plus/minus and anything with really high AP just totally ignores all armor. Stuff with negative AP also gets super ultra shafted by low amounts of armor. This rescales it so that negative AP isn't donked as hard by low amounts of armor (but the same amount of armor is required to stop it completely) while weapons with high AP values are still at least partially affected by armor. There will likely need to be a lot of AP rebalancing but weapons can now have SIGNIFICANTLY higher AP values without making them just completely ignore armor. AP is ROUGHLY half as effective so most things will pretty much need to get doubled. Also slightly reorganizes the ordering in the code for what message it displays.

Below are charts displaying the final armor values based on the initial armor value (shown by color) and armor piercing (x-axis)

image

image

POST-EDIT: This change now only affects negative AP values, ignore everything over 0.

# Wiki Documentation

Negative AP scaling changed from Final Armor = (Armor - AP) to Final Armor = (Armor / (1 + AP/100))

Credit to @tmtmtl30 from shiptest for the actual scaling formula

# Changelog

:cl:  tmtmtl30, Mqiib
tweak: Negative AP scaling has been rescaled and is no longer linear
/:cl:

### CODE REVIEW

**Comment by Rdrazga** [comment]
I’ll look into making notes about how this will affect different weapons and possible value changed that need to be done for them. Some things to note for anyone taking up balancing: 
   lavaland megafauna do AP and rely on this to do damage a lot of the time (secretly this is an hidden miner buff hehe)
   nukie gear against crew and crew gear against nukies need to be buffed very fast as there tends to be lots of armor and AP usage on both sides of this gamemode,

**Comment by Skrem7** [comment]
I'll hold off on doing a code-wide sweep of HP to try and refactor it if it's going to actually be semi-viable to balance via cool math now.

That being said theoretical values should be made now for a follow-up PR because I don't want to imagine the cornflakes that will happen just trying to get the new formula in if it overhauls EVERYTHING.

**Comment by Mqiib** [comment]
> I'll hold off on doing a code-wide sweep of HP to try and refactor it if it's going to actually be semi-viable to balance via cool math now.
> 
> That being said theoretical values should be made now for a follow-up PR because I don't want to imagine the cornflakes that will happen just trying to get the new formula in if it overhauls EVERYTHING.

[armorpenetration.xlsx](https://github.com/yogstation13/Yogstation/files/9457507/armorpenetration.xlsx)

This is the file i used for the figures. I'm pretty sure @Rdrazga is going to cook up some values to make balancing stuff easier.

**Comment by Rdrazga** [comment]
Alright for all those who love numbers and want to see what this does to EVERY item with AP value in game (assuming I didn't miss any) here is a sheet for that:
[Yogstation AP Rework.xlsx](https://github.com/yogstation13/Yogstation/files/9459085/Yogstation.AP.Rework.xlsx)

**Comment by JamieD1** [comment]
@Mqiib Gimmie a shout

**Comment by Mqiib** [comment]
I'm gonna change this to just affect negative AP, rebalancing all the positive AP items is gonna be a pain. Will reopen when I get to it.

**Comment by Mqiib** [comment]
@JamieD1 this makes hollow point weapons more fun and should be fine now unless anyone else rees about negative AP weapons being op

**Comment by Skrem7** [comment]
#15675 does not consider this but can certainly keep an eye on performance or do more robust testing

**Comment by redmoogle** [comment]
Make sure debug armor isnt effected

**Comment by Mqiib** [comment]
> Make sure debug armor isnt effected

It only affects NEGATIVE armor piercing values now, so debug armor with 100 in everything should still work the same

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
