### PR TITLE
Airalarm draught mode now set scrubber range from normal to expanded

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Airalarm draught mode now set scrubber range from normal to expanded

# Why is this good for the game?
make it faster replacing gas

# Testing
crate

# Changelog

:cl:  

tweak: Airalarm draught mode now set scrubber range from normal to expanded
/:cl:

### CODE REVIEW

**Comment by ofscarletdreams** [comment]
"is this pr tested" TRUST ME BRO

**Comment by ShoziOffical** [comment]
> "is this pr tested" TRUST ME BRO

LOOK AT THE FUCKING LINE CHANGE

**Comment by ShoziOffical** [comment]
smh baiomu i tested it, it works

**Comment by ShoziOffical** [comment]
there happy, you guys really making me test a one value change

**Review by MajManatee — APPROVED** [review]
It do be tested tho

**Pull request merged**
