### PR TITLE
Changes borg buckling delay from 1.5 seconds to 0.75 seconds, adds a 1 second delay to *spin with included chat and audio tells

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Github documenting your Pull Request

Jamie stuck by his decision to keep the 1.5 delay in to stop *spin nonsense. I believe this compromise will help stop the insta-spin that Jamie, Hopek, and many others are complaining about in my PR removing the delay.

Now when you spin you will have a very obvious tell in both audio and chat. Moving or cancelling it will not spin them as to keep it fair.

I also changed it to 2 seconds to give you more time to react so you cant get cheesed

# Changelog
:cl:  
tweak: moved 1.5 second delay from buckling to spinning
tweak: made 1.5 second delay into 2 second delay
soundadd: adding borg flinging sounds, one for when it starts, finishes, fails, and fails (in a different way!) 
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
I wasn't really 'complaining' about the spin because I like that part.
I do it to others when I play borg.

I think spinning to launch someone is a fun feature (:

**Comment by ToasterBiome** [comment]
> I wasn't really 'complaining' about the spin because I like that part.
> I do it to others when I play borg.
> 
> I think spinning to launch someone is a fun feature (:

I also agree it is a fun feature, you had a lot of good arguments and i feel like this PR is a good middle ground, hope you find this one more acceptable.

**Comment by SomeguyManperson** [comment]
Consider as well that borgs completely ignore the fireman carry system, giving them no slowdown modifier for having people buckledm and that people who are buckled to borgs can't uncuff themselves, making being buckled to a borg while cuffed effectively impossible to escape

**Comment by ToasterBiome** [comment]
They should be given the ability to uncuff themselves then

**Comment by ToasterBiome** [comment]
They should be given the ability to uncuff themselves then, always seemed stupid that they couldn’t uncuff. You’re saying one very specific situation though as any borg that isn’t standard or sec can’t make that happen by themselves. Hit me up on discord if you wanna talk about a good compromise.

**Comment by Hopekz** [comment]
>  making being buckled to a borg while cuffed effectively impossible to escape

How is this any different than being cuffed and a human dragging you around. 
It is already impossible to escape when you get moved and your uncuff progress bar gets interrupted.

**Comment by SomeguyManperson** [comment]
> > making being buckled to a borg while cuffed effectively impossible to escape
> 
> How is this any different than being cuffed and a human dragging you around.
> It is already impossible to escape when you get moved and your uncuff progress bar gets interrupted.

if a human wants to fireman carry someone to reduce their slowdown they have to keep the target from standing up and stay still for like 5 seconds or something without glove modifiers, and even doing that causes them to be slower, just less slow than if the person they're dragging is resting constantly. As well as if you are buckled to something you have to first unbuckle yourself, doubling the uncuff time if they stop moving for any reason, and if you're being pulled as well as buckled you're shit out of luck anyways
if a non silicon wants to bucklecuff someone and still move they have to either eat a speed penalty or spend inventory space on metal or roller beds, if a silicon wants to do it they have it as an innate ability with no downsides

**Comment by adamsong** [comment]
> if a non silicon wants to bucklecuff someone

You don't need to bucklecuff, you cuff, grab, and walk

**Comment by JamieD1** [comment]
Its also the fact that borgs can instant pick up people which was the reason for the buckle pr. Spinning was less of the issue. But I like the noises.

**Comment by JamieD1** [comment]
Going to close this PR considering we want the do after to be on buckling not on spinning as spinning was not the crux of the issue, however if you want to salvage some of it,
You could add the noises to the current spin.

**Comment by ToasterBiome** [comment]
> Going to close this PR considering we want the do after to be on buckling not on spinning as spinning was not the crux of the issue, however if you want to salvage some of it,
> You could add the noises to the current spin.

Who’s we? You didn’t even review it. I tried to do a compromise to stifle the problem at hand (the insta buckling and spinning spam) that’s been pointed out as “the problem” this entire time while keeping the original, helpful way that borgs can use insta buckling but neither of you seem to like that. 

Every time I asked what’s wrong it’s always came back to the way that they insta buckle and *spin but now you’re trying to ice my PR out instead of working with me and making a compromise

**Comment by Hopekz** [comment]
> Who’s we? You didn’t even review it. 

image

**Comment by ToasterBiome** [comment]
adds 0.75 second borg buckle timer to borgs, moves spin time from 2 seconds to 1 second per jamie's requests

**Comment by patpol4** [comment]
Sounds ok to me

**Comment by Hopekz** [comment]
> > Who’s we? You didn’t even review it.
> 
> image

This hasn't aged well I should have put 8 weeks

**Pull request merged**
