### PR TITLE
chaplain black templar outfit (pr for war)

### PR DESCRIPTION
**Pull request by Ktlwjec1**
Imagine war pr'd this, I can't remember why but I said I'd do it for him.

This PR aims to add more stuff to the Chaplain's armaments beacon. It adds a new kit named "Founder of the Black Templars Kit", the kit itself contains 4 sets of armor. A chaplain set and three regular sets, the armors itself are based on WH40K. They're pretty weak to keep it balanced.

blacktemplar1
blacktemplars
noheresyonlyhonks

:cl:  War
rscadd: Adds a new Chaplain armaments beacon kit named "Founder of the Black Templars Kit". It's purchasable at the Chaplain's vendor.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Its "cool" but my first thoughts are this seems to be better than all the other kits.
I didn't compare the armor values yet but you get 4 full armor sets so it's 4x better than the Crusader kit because you can armor 4 people instead of 1.

Also looking at the armor values it looks like the chaplain full armor is better than the follower armor as well so something to note.

It's better than the "follower" kit as well because you can kit the same amount of people. Before what made the "follower" kit viable to be in the game was that it allowed you to kit 4 people instead of just yourself but now you have this except you fully armor them so there is literally no point getting the follower kit because this is a direct upgrade.

**Some ideas on things that can make this PR balanced:**

- Make the armor give more of a slowdown on movement? (Didn't test the 0.8 speed in-game yet)

- Change it from giving 4 kits to giving 1 kit (to match it on-par with the crusader kit since both sets now give 1 armored option after this change).

- I'd be okay with changing the number of armor sets to 2 (1 of chaplain and 1 of the follower) because this kit doesn't contain a weapon, unlike the crusader kit.

**This PR is "cool" but otherwise, because of balance reasons in this current state it might not fit**

**Comment by ClassyName** [comment]
- **_I didn't compare the armor values yet but you get 4 full armor sets so it's 4x better than the Crusader kit because you can armor 4 people instead of 1._**

> 
- **_Also looking at the armor values it looks like the chaplain full armor is better than the follower armor as well so something to note._**
> 
- _**It's better than the "follower" kit as well because you can kit the same amount of people. Before what made the "follower" kit viable to be in the game was that it allowed you to kit 4 people instead of just yourself but now you have this except you fully armor them so there is literally no point getting the follower kit because this is a direct upgrade.**_
The follower kit is more cult like, whilst this is more of a group crusader type thing. The chaplain full armor is better because the person wearing it leads the group, the armor itself has the lowest armor rating compared to all the other armors. I believe it's about 50% weaker than the crusader kit, so it'd be 2x times better than the crusader kit. So that still reigns supreme compared to the other kits. The reason this kit exists is pretty much the same as the cult of the chaplain kit, for RP reasons. People who get the chaplain cult kit usually get it to start their own cult, this kit would be good for starting their own crusade.

**Comment by ClassyName** [comment]
> * **_I didn't compare the armor values yet but you get 4 full armor sets so it's 4x better than the Crusader kit because you can armor 4 people instead of 1._**
> 
> > 
> 
> * **_Also looking at the armor values it looks like the chaplain full armor is better than the follower armor as well so something to note._**
> 
> > 
> 
> * _**It's better than the "follower" kit as well because you can kit the same amount of people. Before what made the "follower" kit viable to be in the game was that it allowed you to kit 4 people instead of just yourself but now you have this except you fully armor them so there is literally no point getting the follower kit because this is a direct upgrade.**_
>  

The follower kit is more cult like, whilst this is more of a group crusader type thing. The chaplain full armor is better because the person wearing it leads the group, the armors themselves have the lowest armor rating compared to all the other armors. I believe it's about 50% weaker than the crusader kit. So that still reigns supreme compared to the other kits. The reason this kit exists is pretty much the same as the cult of the chaplain kit, for RP reasons. People who get the chaplain cult kit usually get it to start their own cult, this kit would be good for starting their own crusade.

**Comment by Xoxeyos** [comment]
If you do reduce the number of followers, I would like to suggest adding "[Devotion Manacles](https://vignette.wikia.nocookie.net/warhammer40k/images/1/1c/Bolter_Manacle_%26_Chain.jpg/revision/latest?cb=20120528145702)" which can attach to any melee weapon, and it makes you incapable of dropping it, unless your arm gets chopped off, or something. Or maybe if the manacle breaks, overtime.

**Comment by Xoxeyos** [comment]
And if you want the chaplain armor to be like the actual black templar armor, you could replace the helmet with the [Chaplain](https://imgur.com/a/T5feGh9) skull helmet.

**Comment by ClassyName** [comment]
It originally had a skull helmet, however that didn't work properly unless it was a separate piece. I couldn't figure out why, same goes for some coders that looked at the code.

**Pull request merged**
