### PR TITLE
Significantly adjusts minimum age requirements for most jobs

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Goes through and adjusts a lot of the age requirements for each job as well as adding comments with general justification and thinking behind each one. Even those that haven't been changed have received a line indicating that they're the base value to explain WHY they're being left at that value of not feasibly requiring education.

Inspired by a lot of things but namely a level of absurdity that comes around from situations such as a bartender younger than 21 and a station engineer that can somehow put together MARVELOUSLY EXPERIMENTAL ENGINES as well as having perfect mechanical knowledge at the age of 18. I understand apprenticeships exist but being that NT is a corporation that wants at least baseline competency from their workers I assume documentation or otherwise evidence of certain knowledge or skills is warranted.

# New Minimum Age per Job
**Artist**: 18 (from 18)
**Assistant**: 18 (from 18)
**Atmospheric Technician**: 24 (from 18)
**Bartender**: 21 (from 18)
**Botanist**: 22 (from 18)
**Brig Physician**: 26 (from 24)
**Captain**: 35 (from 28)
**Cargo Technician**: 18 (from 18)
**Chaplain**: 18 (from 18)
**Chemist**: 24 (from 18)
**Chief Engineer**: 30 (from 25)
**Chief Medical Officer**: 30 (from 25)
**Clerk**: 18 (from 18)
**Clown**: 18 (from 18)
**Cook**: 18 (from 18)
**Curator**: 18 (from 18)
**Detective**: 22 (from 18)
**Geneticist**: 24 (from 18)
**Head of Personnel**: 26 (from 25)
**Head of Security**: 28 (from 28)
**Janitor**: 20 (from 18)
**Lawyer**: 24 (from 24)
**Medical Doctor**: 26 (from 24)
**Mime**: 18 (from 18)
**Mining Medic**: 26 (from 24)
**Network Admin**: 22 (from 18)
**Paramedic**: 20 (from 24)
**Psychiatrist**: 24 (from 24)
**Quartermaster**: 20 (from 18)
**Research Director**: 26 (from 26)
**Roboticist**: 22 (from 18)
**Scientist**: 24 (from 18)
**Security Officer**: 18 (from 18)
**Shaft Miner**: 18 (from 18)
**Station Engineer**: 22 (from 18)
**Tourist**: 18 (from 18)
**Virologist**: 24 (from 18)
**Warden**: 20 (from 18)

# Wiki Documentation

If you want to have a minimum age thing per job to make it clear and accessible it wouldn't be the worst thing would be a nice thing to fill in the baseline format

# Changelog

:cl:  
tweak: Most, if not all jobs have had their minimum ages given a pass-over
experimental: Code-enforced RP
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
What is the point of this, nobody ever looks at anybodys age

**Comment by Skrem7** [comment]
> What is the point of this, nobody ever looks at anybodys age

What's your issue with it then if it promises to satisfy some level of sensibility to those who care while it doesn't affect anyone who doesn't

**Comment by VaelophisNyx** [comment]
whoops

**Comment by Skrem7** [comment]
Like how is it that I have to emphasize how contradictory it is to go "nobody cares about other's ages" then not want this PR to happen because it clearly shows some level of care on the subject

Could you offer any actual argument other than trying to speak for every person on yogs because it's more than presumptuous

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
