### PR TITLE
Metal shutters no longer immune to gun

### PR DESCRIPTION
**Pull request by Mqiib**
# Document the changes in your pull request

Sets the bullet, laser, and energy armor of metal shutters to 80 (instead of 100).

# Changelog

:cl:  

tweak: Metal shutters now take damage from projectiles

/:cl:

### CODE REVIEW

**Review by adamsong — APPROVED** [review]
Code looks fine, not sure about the balance of that, pull from master to fix the linter

**Comment by Hopekz** [comment]
To give more context to my down doink:

In my opinion, the whole point of those shutters being there is to be bullet-resistant.
Whenever a blast door shutter rolls down in any game/media, it is meant to offer that protection, and because of this, it is what people expect the shutters to do.

**Review by Bibby0110 — COMMENTED** [review]
probably up the armor a bit? 80-90?

**Comment by Marmio64** [comment]
shutters should be near immune but not completely immune imo

**Comment by Mqiib** [comment]
80 armor now - effectively doubles their health against gun

**Comment by Hopekz** [comment]
A compromise was suggested and implemented now; it legally has to be merged because we like to make compromises here

**Review by Bibby0110 — APPROVED** [review]

**Comment by JamieD1** [comment]
Can try it I guess

**Pull request merged**
