### PR TITLE
new hand tele item sprite

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
new hand tele item sprite

# Spriting
telepurter

# Wiki Documentation

update the wiki image 

# Changelog

:cl:  
imageadd: added some icons and images  for handheld teleporter
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
shading?

**Comment by tattax** [comment]
why not flip it 90 degrees

**Comment by cuackles** [comment]
> shading?

Never heard of it

**Comment by cuackles** [comment]
> why not flip it 90 degrees



> shading?
telepurter

like this ?

**Review by KillerOrcaCora — APPROVED** [review]
It has been flipped back peace in the spriter kingdom was restored and everyone made friendships bracelets except for the one who mentioned the idea they are banished to the edge of the equator

**Comment by KillerOrcaCora** [comment]
God is grace god is good amen

**Pull request merged**
