### PR TITLE
Enables widescreen mode

### PR DESCRIPTION
**Pull request by ThatLing**
I'm just leaving this here. :eyes:

### CODE REVIEW

**Comment by Amelia0010** [comment]
oh I thought you had it be a preference like on citadel...

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/4374
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/5338
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/5822
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/5874

**Comment by Nickvr628** [comment]
:thonk: This breaks balance because now I can see further left and right but comparatively less up and down. This is a nerf to sec and the crew since the sec department hallway is vertical.

Denied.

**Comment by Amelia0010** [comment]
not to mention this would fuck all the huds over exceptionally, since they'd still be 15x15

**Comment by ThatLing** [comment]
@nichlas0010 
Making it a pwefewence is unbalanced though and we can edit the HUDs.

**Comment by Nickvr628** [comment]
Also all the overlays for crit, etc since those are 15x15

**Comment by Amelia0010** [comment]
if it's unbalanced then so be it, it's a really really really nice thing to have. And yeah, I was only mentioning it since it hadn't been edited here. I mostly want it to be a preference since some people won't like it, and them choosing not to doesn't impact other people negatively, only themself

**Comment by Nickvr628** [comment]
Inb4 the new meta is for sec to only patrol the horizontal hallways where they have the advantage with tasers. 

Auto kick sec and nuke ops who do not use widescreen mode.

**Comment by ThatLing** [comment]
Okay I'm just gonna leave this open to get feedback on whether people want this or not.

**Comment by Bawhoppen** [comment]
Don't do this.

**Comment by Amelia0010** [comment]
why not?

**Comment by Bawhoppen** [comment]
Being able to see horizontally more than vertically is the silliest thing, and this does not make the game look better in any way. I am all for change, but having the square viewport is absolutely classic ss13.

**Comment by Amelia0010** [comment]
that sounds like a very anti-change argument to me. Claiming something is classic and shouldn't be changed is grounds for execution, you know.

**Comment by ThatLing** [comment]
Okay let's revert back to old yog icons because it is classic

**Comment by Amelia0010** [comment]
*executes @ThatLing*

**Comment by deathride58** [comment]
TG already has support for widescreen as a config option, it just requires an edit of the titlescreen and the fullscreen overlays.

DEFAULT_VIEW in config.txt is what controls resolution. Trying to set widescreen in world.dm will break shit beyond repair.

**Comment by ShadowDeath6** [comment]
why is this needed

**Comment by Amelia0010** [comment]
>why is this needed

This is why noone likes you

**Comment by ThatLing** [comment]
@deathride58 
I noticed when I tested it. This is more of a way to get feedback if people want this. I'll implement it correctly if there is enough positive feedback.

**Comment by Jc1469** [comment]
expecting players to check the rebase git :thinking: 

:balance_scale: :police_car: balance police say no. :police_car: :balance_scale:   sec powercreep. can see more cells at once. :-1:

**Comment by Amelia0010** [comment]
>expecting players to check the rebase git 

If only we had a channel on discord that posted all the PRs made here

**Pull request closed without merging**
