### PR TITLE
adds wisp lantern back to necropolis

### PR DESCRIPTION
**Pull request by boodaliboo**
image

#### Changelog

:cl:  
rscadd: readds wisp lantern to necropolis
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
Necropolis loot has been severely weakened from it's past state, but one glaring removal was not needed from the nerf by Adam. Spooky Lantern. Despite it's removal from necro chests it stayed at a ruin in lavaland from then till now and hasn't once even been abused. It is a fantastic mining tool allowing you to put your GPS in your pocket instead of a flashlight, giving you thermals to not run into the numerous dangerous fauna, and being limited utility on station with thermals being generally best for hiding or hunting which miners can rarely do. Genetics also has thermals but are able to get them within 15-30 minutes easily and for the whole station. Also necropolis loot as is needs some redoing (removing shit like possessed sword, cursed heart, and armblade), and this is one loot item which fits well and is great for lavaland.

**Comment by LazennG** [comment]
i disagree.

**Comment by Takahiru** [comment]
why dont you just have flashlight - gps in your pocket lol

**Comment by VVivec** [comment]
i agree.

**Comment by Mesalikepie** [comment]
@Takahiru satchel goes in one pocket to maximize space

**Comment by ToGWtF** [comment]
Thermals is entirely too OP

Xray got yeeted from genetics, and thermal from genetics is being made to cost 3x the price because of validhunters
Miners are known as the validhunting job
See where the problem is

If you want it for lavaland purposes? Sure. Just make it so the thermals turn off if you're off Lavaland Zlevel, because youre too far away from the magic or whatever.

**Comment by ghost** [comment]
if it gets readded i'm just making it give orevision instead and replace the use of the mining scanner

**Review by jcatjmeow — APPROVED** [review]
Dislike the change. Code is fine

**Comment by Reed0506** [comment]
imagine not putting your flashlight on your KA
also adam if you do change it to be an ore scanner, perhaps it could automatically stabilize gibtonite near you or something like that as a generally useful mining ability.

**Comment by LazennG** [comment]
automatically stabilizing gibtonite would be shit since nothing strong would come of it

**Comment by Mesalikepie** [comment]
Readd this then let what Adam wants happen. Wisp lantern is cool sprites and aesthetically and good as even just a light. Replacing thermals with permanent ore vision would be so dope.

**Comment by ghost** [comment]
free x-ray with the option to still get flash protection is a little too much for a necro chest, but then again that would bring other loot into scrutiny

**Comment by redmoogle** [comment]
Make the thermal work on lavaland. problem mostly solved

**Comment by JamieD1** [comment]
@boodaliboo Make it only work on lavaland

**Comment by boodaliboo** [comment]
> @boodaliboo Make it only work on lavaland

no

**Pull request closed without merging**
