### PR TITLE
Revert "Restricts Hypnotic Flash to Psychiatrist"

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Let them eat cake

Reverts https://github.com/yogstation13/Yogstation/pull/3721

# Wiki Documentation

Hypno Flash no longer role restricted and is in Misc. Gadgets section

# Changelog

:cl:  
tweak: Hypnotic Flash is no longer role restricted
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
@ynot01 What's the goal here?

**Comment by ynot01** [comment]
> @ynot01 What's the goal here?

I don't want to be forced to play Psychiatrist (bad role) for hypnotic flash

**Comment by ThatLing** [comment]
> > @ynot01 What's the goal here?
> 
> I don't want to be forced to play Psychiatrist (bad role) for hypnotic flash

It's the prime reason to play Psychiatrist (rp role)

**Comment by ynot01** [comment]
> > > @ynot01 What's the goal here?
> > 
> > 
> > I don't want to be forced to play Psychiatrist (bad role) for hypnotic flash
> 
> It's the prime reason to play Psychiatrist (rp role)

If we remove antag rolling as the prime reason to play psych then someone will have to either make it worth playing or remove it

**Comment by ThatLing** [comment]
> > > > @ynot01 What's the goal here?
> > > 
> > > 
> > > I don't want to be forced to play Psychiatrist (bad role) for hypnotic flash
> > 
> > 
> > It's the prime reason to play Psychiatrist (rp role)
> 
> If we remove antag rolling as the prime reason to play psych then someone will have to either make it worth playing or remove it

Isn't that what you are doing with your rework

**Comment by MajManatee** [comment]
Psych is used exclusively by trolls and greifers. Cant name one psych player I've liked.

You CAN get the flash from null crates but that is kinda useless by then. since you aren't stealthy at ALL.

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
