### PR TITLE
Nerf moderators

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Down with the moderators (also, AOs had access to these lol)

# Changelog

:cl:  
bugfix: fixed a few bus buttons being available to moderators
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
I could see a valid need for cure all traumas, otherwise a sad day for moderators

**Comment by MajManatee** [comment]
Maintainer nerf 😢 no more testing martial arts on live

**Comment by Hislyna** [comment]
> Maintainer nerf 😢 no more testing martial arts on live

I mean Bai/Jamie could prolly edit the perms if needed *shrug

**Comment by adamsong** [comment]
Oh shit, didn't mean to nerf maints, please hold

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
