### PR TITLE
Removes Chem Dispensers from psych pt 2: Sol is slightly less stupid hopefully

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Removes chem dispenser from the psychiatrist office.
If they want chems they should have to ask chem, just like how gene has to ask chem for anti rad, and viro has to ask chem for unstable mutagen.
# Spriting

# Wiki Documentation

# Changelog

:cl:  

mapping: no more psych office chem dispenser.

/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
pls no merge conflict

**Comment by DylonBR** [comment]
let people enjoy things

**Comment by solwashere** [comment]
> let people enjoy things

it takes away from chemistry's job.
guess we should give cargo one for bounties, botany one for unstable mutagen and saltpetre, virology one for the various viro recipes, genetics one for potassium iodine, sec one so they can make healing chems when they get hurt, engineering one to make potassium iodine and penetic acid, the bartender one so they can make iron and ethanol.

**Comment by wonderinghost** [comment]
well does it. its one guy trying to treat mental afflictions. also botany is self reliant as they can just print those two from their bioregenerator... also the maint ruin which produces free chems. and if no one is doing fuck all in chemistry then people are willing to break in to deal with bounties or just build new ones from engineering

barkeep can grind metal sheets for iron and i think spray paint has ethanol in it... and who asks for iodine in gene. why do they care if their monkey dies. also why would sec get a chem station. that's like giving them a all access fabricator.

**Comment by solwashere** [comment]
> well does it. its one guy trying to treat mental afflictions. also botany is self reliant as they can just print those two from their bioregenerator... also the maint ruin which produces free chems. and if no one is doing fuck all in chemistry then people are willing to break in to deal with bounties or just build new ones from engineering
> 
> barkeep can grind metal sheets for iron and i think spray paint has ethanol in it... and who asks for iodine in gene. why do they care if their monkey dies. also why would sec get a chem station. that's like giving them a all access fabricator. 

Why does one person who relies on medication get the ability to have a chem dispenser to themselves and therefore take away from chems job slightly?

**Comment by wonderinghost** [comment]
> Why does one person who relies on medication get the ability to have a chem dispenser to themselves and therefore take away from chems job slightly?

experimentation. isnt that what the psychiatrist rework was all about... or did that get closed

**Comment by solwashere** [comment]
> > Why does one person who relies on medication get the ability to have a chem dispenser to themselves and therefore take away from chems job slightly?
> 
> experimentation. isnt that what the psychiatrist rework was all about... or did that get closed
> 

Is it really that hard to ask a chemist or CMO "hey I need happy pills real quick please"

**Comment by wonderinghost** [comment]
It depends on the situation. Are both chemists antags or ssd. Cmo being a asshat or is gone/dead. How new are these people to chemistry and would they fuck it up. Or is chemistry fucked. 

Besides at least it isn't in public back when they moved psychiatrist out of medbay

**Comment by solwashere** [comment]
> It depends on the situation. Are both chemists antags or ssd. Cmo being a asshat or is gone/dead. How new are these people to chemistry and would they fuck it up. Or is chemistry fucked. 
> 
> Besides at least it isn't in public back when they moved psychiatrist out of medbay

Then that's an L situation, you can't win all the time. and honestly if shits that bad I don't think making happy pills is your biggest worry

**Comment by wonderinghost** [comment]
Well what else are they gonna do. Sit on their asses and wait 20 minutes to get something

**Comment by solwashere** [comment]
> Well what else are they gonna do. Sit on their asses and wait 20 minutes to get something 

News flash psych is a mainly rp role with almost nothing to do unless you find other people to go along with it
Making happy pills isn't going to consist of much entertainment value anyways because chem is arguably boring outside of experimenting with healing mixes and pyrogenics, which psychiatrist cannot do within the rules

**Comment by wonderinghost** [comment]
Again there was a psychiatrist rework. #17721

**Comment by solwashere** [comment]
> Again there was a psychiatrist rework. #17721

Yes they can use drugs to help cure a trauma however again I fail to see why they need a whole ass dispenser when there is only a small amount of drugs that can be used by them for said treatment
All it does is decrease departmental interaction
Having one person be self sufficient in their ability to do their job is bad design

**Comment by wonderinghost** [comment]
Inter department relations is hard. The only department that is usually on all cylinders is security. Medbay is usually the main 3. Chemistry, medical, and genetics.

 How many times do you see a medical doctor tell a patient to see a psychiatrist. How many times do you see a Atmos tech be fighting fires

**Comment by wonderinghost** [comment]
Hell some departments it's more worth breaking in then to communicate.

Sci as a whole is a good example. Weather rain snow or shine there is no one manning the reception to produce parts or tools.

Robotics is also becoming more of a problem with closing both shutters. 
Only those with AA can drop off a dead IPC or a body for borging

**Comment by tattax** [comment]
why do you wanna gatekeep the chemistry machine so hard what do you want to tell us

it's bad design cause it's literally chemistry but you get to close shutters and do fuckall (very funny)
pills are remarkably easy to make and chem has no reason to deny it since they'll be bored after the 20 minute mark if nothing is happening (and they aren't the antagonist)

also your examples don't make sense since psych isn't some random assistant asking for hard drugs they're literally part of medbay and can ask the CMO or someone else + they get like 3 bottles of pills roundstart

**Comment by wonderinghost** [comment]
How is that gatekeeping

And any of those departments I've mentioned can also do that. Close shutters and do fuck all

**Comment by wonderinghost** [comment]
Worse is if they go ssd in the department

**Comment by solwashere** [comment]
That's a player issue though, I'm attempting to look at this from a pure gameplay standpoint
If someone isn't doing their job or going SSD you can ahelp them
Also as someone with 560 hours as CMO and 350ish Medical Doctor, chem is more reliable than not and generally will make something when asked like 3/4ths of the time
This is moreso about the fact that the psychiatrist gets a chem machine to fulfill a somewhat niche purpose

**Comment by Therandomhoboo** [comment]
Bruh, why would psychs have a chemistry unit in their place? It doesn't really make sense and just gives antags/pysch antags the ability to hide and make any chemical unless AI checks on them. Don't be brain dead, pysch dont need chem, we have chemists for a reason

**Comment by thegoldencat413** [comment]
"psychiatrist has nothing to do so we will give them a chem setup as a consolation prize" is STUPID

**Comment by iamthesilly** [comment]
Better to give the psychiatrist a few spare bottles of meds they need than an entire dispenser, chemistry is in the SAME DEPARTMENT as them so the chemist or CMO or anyone else with access can make it or let them in if they need more

**Comment by ChuChu42** [comment]
> > let people enjoy things
> 
> it takes away from chemistry's job. guess we should give cargo one for bounties, botany one for unstable mutagen and saltpetre, virology one for the various viro recipes, genetics one for potassium iodine, sec one so they can make healing chems when they get hurt, engineering one to make potassium iodine and penetic acid, the bartender one so they can make iron and ethanol.

this is called being a piece of shit

**Comment by Moja10** [comment]
I don't think there's been enough time with ynot's psyche rework to justify this yet.

**Comment by solwashere** [comment]
I think it's been plenty of time and I've yet to see the dispenser be used in a productive way
Imo the chem dispenser is an item that is unique to the chemistry job and is part of their identity, and should stay that way

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
> Better to give the psychiatrist a few spare bottles of meds they need than an entire dispenser, chemistry is in the SAME DEPARTMENT as them so the chemist or CMO or anyone else with access can make it or let them in if they need more

do this

**Comment by solwashere** [comment]
> > Better to give the psychiatrist a few spare bottles of meds they need than an entire dispenser, chemistry is in the SAME DEPARTMENT as them so the chemist or CMO or anyone else with access can make it or let them in if they need more
> 
> do this

I think the psych starts with them in their locker but I can check when I get home, and throw a few pills on their desk either way

**Comment by Therandomhoboo** [comment]
Oh yeah I just noticed cause I can play, is that Psychs office is now in medbay? (probabl;y been there for ages but oh well) So they defo dont need a chem dispenser since chemistry is around the corner

**Comment by solwashere** [comment]
each psych office now comes with psicodine pills and mindbreaker gummies

**Review by MajManatee — APPROVED** [review]
I work in a psych hospital (more or less). They don't make their own drugs.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
