### PR TITLE
Change some reinforced windows to normal windows

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

# Spriting

We buffed reinforced windows, but then we forgot to change some windows that don't need to be reinforced to normal windows. Why does secondary tool storage need reinforced windows which take a minute to deconstruct? If we overuse reinforced windows, they become the norm and that's unhealthy for the game.

# Wiki Documentation

Map thumbnails
# Changelog

:cl:  
mapping: Change some reinforced windows to normal windows
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
You forgot to say which windows you changed.

**Comment by ToasterBiome** [comment]
These are all places greyshits should not be breaking into, and if you're antag you have ways to break these windows.

**Comment by patpol4** [comment]
I agree with your point but what bibby said, give a picture and explanation for each of the changes

**Comment by ynot01** [comment]
Why would genetics' public facing door be a normal window but the ones facing medical are reinforced?

**Comment by Simplehorror** [comment]
> Why would genetics' public facing door be a normal window but the ones facing medical are reinforced?

oversight, would fix but instaclosed


> I agree with your point but what bibby said, give a picture and explanation for each of the changes

no point now

**Comment by Simplehorror** [comment]
> These are all places greyshits should not be breaking into, and if you're antag you have ways to break these windows.

how many times has someone died sitting outside of medbay lobby because they couldnt break a window

**Comment by patpol4** [comment]
At this point baiomus opinion here takes priority.

**Pull request closed without merging**
