### PR TITLE
Ports fishkeeping from Paradise

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request
Ports fishkeeping from Paradise. It can be an alternative food source for the kitchen. More information about it you can get on the official wiki of ss220: https://paradisestation.org/wiki/index.php/Fish

Also it ports some seafood, but since i am a noob, recipes of that food are ported not very good(they all are made through crafting and food processor, because i didnt find recipes code for grilling or cooking).

# Wiki Documentation

Add a guide for fishkeeping. 
Add a new vendomat to vendor list - CritterCare
Add more recipes to cooking guide.
Add aquariums into guide to construction. 

# Changelog
:cl:  

Original PR: https://github.com/ss220-space/Paradise/commit/9074629123d8e6d2d9f23141f89b2d49d31df764
Author of original PR: FalseIncarnate

rscadd: Adds a new sidejob - fishkeeping
rscadd: Adds a new vedor machine - CritterCare
rscadd: Adds some new toys
rscadd: Adds a new kit
rscadd: Adds some new food
rscadd: Adds some new cooking recipes
imageadd: Adds icons for fish items and seafood.
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
This PR has also the traitor plant code you might wanna delete that part or something

**Comment by ghost** [comment]
> This PR has also the traitor plant code you might wanna delete that part or something


Yes, but i dont know how to remove it from here, i am dont know how to work with github very good.

**Comment by SomeguyManperson** [comment]
put the original PR's author in the changelog on the first :cl: line & link the original pr please

check history on one of the fishing related files and it should lead you to it eventually

**Comment by TymurShatillo** [comment]
> put the original PR's author in the changelog on the first 🆑 line & link the original pr please
> 
> check history on one of the fishing related files and it should lead you to it eventually

Fuck, how can i check an alredy closed/meged PR?

**Comment by ghost** [comment]
> put the original PR's author in the changelog on the first 🆑 line & link the original pr please
> 
> check history on one of the fishing related files and it should lead you to it eventually

Done.

**Comment by Cartlord** [comment]
https://paradisestation.org/wiki/index.php/Fish In English, because Tymur didn't include that for some reason

**Comment by ghost** [comment]
> https://paradisestation.org/wiki/index.php/Fish In English, because Tymur didn't include that for some reason

I didnt know about existing of the english version. Thank you for giving it, i will insert it into description.

**Comment by ghost** [comment]
Fucking ambrosia shit ruined the fun, i need to close this PR and then open a new one without it when i will be at home.

**Comment by SomeguyManperson** [comment]
so the changelog is properly formatted, the pr link needs to be outside and the author's name should be on the same line as the changelog and only changelog information should be inside

ParadiseSS13/Paradise#1295 < original pr pushed to paradise's git, the commit for fish stuff wasn't moved the way I expected. This bit can also be at the top of the pr
:cl: author's name
changelog
/:cl:

**Comment by ghost** [comment]
Need to fix something

**Pull request closed without merging**
