### PR TITLE
Gives the implanted rev flash a unique sprite

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

As per the new metashield rules established after council vote 990, a sighting of a syndicate flash is now sufficient evidence to confirm a revolution, so this PR adds a unique sprite for it.

# Spriting
image
image
image
image
image
syndicate_flash

# Wiki Documentation

Maybe add an image of this to the revolution guide?

# Changelog

:cl:  
imageadd: adds unique sprite for rev flash  
/:cl:

### CODE REVIEW

**Comment by Therandomhoboo** [comment]
If it is just for the spirte for the rev flash Im fine with that but I heard you want to make the actual flash light red too is that true?

Cause if so, this will just ruin revs.

**Comment by iamthesilly** [comment]
> If it is just for the spirte for the rev flash Im fine with that but I heard you want to make the actual flash light red too is that true?
> 
> Cause if so, this will just ruin revs.

The flash doesn't actually make light and this doesn't change that

**Comment by ChuChu42** [comment]
just make it the amongus flash nobody is gonna see it expect for you anyways

**Review by cuackles — CHANGES_REQUESTED** [review]
image
right back hand looks odd, the flash should appear under the hand but it looks like its over it

**Comment by iamthesilly** [comment]
> image right back hand looks odd, the flash should appear under the hand but it looks like its over it

all flashes do this so that you can tell someone is holding one when they're facing up
image

**Comment by Hopekz** [comment]
The revs aren't a part of the syndicates I thought unless now they actually are and I missed it?

**Comment by JohnFulpWillard** [comment]
> The revs aren't a part of the syndicates I thought unless now they actually are and I missed it?

```
/obj/item/organ/cyberimp/eyes/hud/security/syndicate
	name = "Contraband Security HUD Implant"
	desc = "A Cybersun Industries brand Security HUD Implant. These illicit cybernetic eye implants will display a security HUD over everything you see."
	syndicate_implant = TRUE
```

Revolutionaries are funded by the Syndicate to overthrow Command, lore-wise.

**Review by cuackles — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
