### PR TITLE
[PORT] Adds a stone floor sprite from TG

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

the amount of times I've been mapping and thought "damn, I wish I had a stone floor right now." is much more than you would think, so this adds one from this TG pr: https://github.com/tgstation/tgstation/pull/70479

strictly speaking in order for anyone but mappers to use these i'd need to do some more stuff but i'm not overly concerned about that right now

# Why is this good for the game?
more options for mappers instead of the same 3 floor types again

# Spriting
image

# Changelog

:cl:  Cark, Paxilmaniac
imageadd: added a stone floor icon
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
don't @ me i know this isn't done right im just a mapper ok :(

**Review by cuackles — APPROVED** [review]

**Review by Moltijoe — CHANGES_REQUESTED** [review]
pretty sure it also needs a description, as well as a floor_tile

**Review by Moltijoe — DISMISSED** [review]
should be fine

**Comment by neeshacark** [comment]
> should be fine

ok cool but you requested changes you goofy ahh

**Pull request merged**
