### PR TITLE
Objectives in stat panel + show completion

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Relying on note memory bad

Auto updating objectives panel good

Gets marked with green and (COMPLETED) when complete

# Changelog

:cl: 
rscadd: Added objective view in status panel
experimental: The syndicate now notifies its agents whether their objectives have been completed to satisfaction
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Now this i like

**Review by MajManatee — APPROVED** [review]
While i think it might be better a bit lower on the pannel, this works.

**Comment by Moja10** [comment]
wouldn't this give you information you might not have, like a miner target dying on lavaland and you only know because your objective is green?

**Comment by Sniblet** [comment]
And that's a good thing

**Pull request merged**
