### PR TITLE
fixes t45b sprites

### LINKED ISSUE #13998: Salvaged power armor broken sprite
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: When lightened up, the helmet looks like this (on all sides):
## Supplied Image:

SuppliedImage
 Submitted by: Marunias (368473582981873664)

### PR DESCRIPTION
**Pull request by tattax**
self explanatory

closes https://github.com/yogstation13/Yogstation/issues/13998

:cl:  
bugfix: t45b now looks normal
/:cl:

### CODE REVIEW

**Review by nesisknesis — COMMENTED** [review]
What was wrong with them

**Comment by tattax** [comment]
> What was wrong with them

https://github.com/yogstation13/Yogstation/issues/13998

**Review by nesisknesis — APPROVED** [review]

**Comment by JamieD1** [comment]
Cornflakes

**Comment by JamieD1** [comment]
Fix cornflakes then dm me.

**Comment by tattax** [comment]
@JamieD1

**Pull request merged**
