### PR TITLE
Stechkin APS sprite update.

### PR DESCRIPTION
**Pull request by nesisknesis**
# Document the changes in your pull request

Updates Stechkin APS sprite.

image

Sprited with the intent to look as much like an actual stechkin as possible. Current sprite resembles a makarov more in my opinion.

image

# Changelog

:cl:  Identification
imageadd: New sprites for Stechkin APS.
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
i like it

**Comment by CMOisLing** [comment]
I like it but id be lying if I said I wasnt gonna miss the old sprite.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
de-souling the game smh... new sprite looks better though

**Comment by JamieD1** [comment]
Why is the bottom bit so pronounced when on the real gun the scale of it is tiny compared. Also why is the back cut out and not rounded like the original.
image

**Comment by KillerOrcaCora** [comment]
Literally my same thoughts in #spriting
image

**Review by cuackles — APPROVED** [review]

**Comment by cuackles** [comment]
sprites are ment to take the more notable parts of something as it, having that pronuced part make it more recognizable for a sketchin

**Comment by nesisknesis** [comment]
Cuackles has hit the nail on the head. Scale from a reference to a sprite is not 1:1. Its a detail I want to communicate and i've done so. Not a detriment at all. 

I can't help if its not round enough for you, thats a limitation of pixel art I would say.

also thanks for compliments guys

**Comment by cuackles** [comment]
> Cuackles has hit the nail on the head. Scale from a reference to a sprite is not 1:1. Its a detail I want to communicate and i've done so. Not a detriment at all. 
> 
> I can't help if its not round enough for you, thats a limitation of pixel art I would say.
> 
> also thanks for compliments guys

Fix conflicts so i can merge tho

**Pull request merged**
