### PR TITLE
Re-enables jungle fever

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Pretty interesting and unique game mode, didn't really have a reason to be disabled. Re-enables monkey mode/jungle fever in the dynamic roundstart rules.
# Wiki Documentation
Monkey is back in rotation.
# Changelog
:cl:  
tweak: Jungle fever is back in rotation.
/:cl:

### CODE REVIEW

**Comment by Mantlecrawler** [comment]
The gamemode is buggy & incredibly unfun, hence its disabled

**Comment by Simplehorror** [comment]
> The gamemode is buggy & incredibly unfun, hence its disabled

it's not buggy, maybe it is unfun subjectively, but not buggy. works just fine

**Comment by Bibby0110** [comment]
Monkey has been disabled for a reason and it’s staying disabled for that reason

**Comment by Simplehorror** [comment]
> Monkey has been disabled for a reason and it’s staying disabled for that reason

that reason being...?

**Comment by JamieD1** [comment]
Nope

**Pull request closed without merging**
