### PR TITLE
Clown Station!

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 fluffe9911
add: A new admeme only map called clown station! pretty much a yogstation clown reskin
/🆑
Added a new map I like to call clown station where almost every job is a clown, medbay is deathbay, everything is made out of bananium and a ton of other minor and silly details have fun!

### CODE REVIEW

**Comment by Nickvr628** [comment]
where are the screenshots?

**Comment by fluffe9911** [comment]
one moment takes me a bit to take screenshots 
nevermind nich ninjaed me with a much better solution

**Comment by Amelia0010** [comment]
http://mapdiffbot.dextraspace.net/Files/120966336/36918662/0/after.png

**Comment by Nickvr628** [comment]
the bar looks like such cancer and I love it

**Comment by monster860** [comment]
literally the definition of a meme pr

**Comment by thehighwayman** [comment]
needs someone to maintain it

**Pull request closed without merging**
