### PR TITLE
Cluwnes can no longer be cloned

### PR DESCRIPTION
**Pull request by fluffe9911**
One does not escape from the curse so easily...

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Cluwnify them on cloning instead you nerd. Death is not an escape.

**Comment by fluffe9911** [comment]
That would be better but im not certain how to make the mutation always transfer over

Edit will be once https://github.com/tgstation/tgstation/pull/43134 is merged

**Comment by HomocidlePancakes** [comment]
Make cluwns seperate race and have them somehow not process mutation toxins? Iam not a coder so I will be speweing dumb shit

**Comment by fluffe9911** [comment]
ok time greens fix didnt work seems this is the best solution atm so yeah lets just go with this

**Comment by Altoids1** [comment]
I'unno, I'm personally against this.

**Comment by Jc1469** [comment]
why not just have a personal floor cluwne hunt those dumb enough to get cloned.  if they survive the second coming, they get to live.

**Pull request closed without merging**
