### PR TITLE
Lizard mask variants

### PR DESCRIPTION
**Pull request by BlueishTsunami**
This PR adds lizard mask variants for around 17 masks in game. See full list below. This was created as part of a sprite request on the Yogstation discord. 

- On top of adding the sprites, the code was tweaked to allow for lizard mask variants, and to override the snout removal upon equipping a mask. This is handled similarly to the digitigrade clothing. 
- Also had to add a variable and check for the mask having an "adjusted" variant just for the explorer mask, to avoid having duplicate sprites for all adjustable variant masks
- Missing 1 or 2 bandanas in the screenshot but they all basically look the exact same. 

Full mask list: 

- Gas mask
- Welding gas mask
- Explorer mask
- Syndie mask
- Swat mask
- Medical mask
- Breath mask
- Sechailer 
- Balaclava
- All bandanas (botany, skull, durathread, red, blue, green, yellow, black)

Note: This is my first code PR so apologies if I'm doing this stupidly. Also, for some reason, i had to set the mutantrace_variation variable on every item in gasmask.dm or else they wouldn't appear in game on a lizard. This isn't the case for any other file that was changed with masks in it so not sure what happened there. 

# Spriting
masks

# Changelog
:cl:  
rscadd: Added lizard variants for around 17 masks
rscadd: Added code to handle mutant mask variants 
tweak: tweaked code handling snout removal to take mask variants into account
imageadd: Added sprites for lizard mask variants
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
can we get front views?

**Comment by Moltijoe** [comment]
code looks good at first glance, but i'm half asleep so i'm not going to approve it yet
gonna want to make sure it doesn't break anything else

**Comment by BlueishTsunami** [comment]
> can we get front views?

Front views are actually the same for these. Didnt feel a need to change them since they all still look good from the front, but i can tweak if needed

**Comment by BlueishTsunami** [comment]
> code looks good at first glance, but i'm half asleep so i'm not going to approve it yet gonna want to make sure it doesn't break anything else

Ok just realized there is still an issue that i need to fix, gonna hopefully get that done here in a sec. 
Any of the "light" nose variants layer on front of the masks for some reason.

image

Like above

**Comment by BlueishTsunami** [comment]
Ok, fixed the issue by reordering the layers in misc.dm. I tested in game and didnt see this messing anything up, and issue is fixed, so yay?

**Comment by iamthesilly** [comment]
image
Should probably remove the HIDEFACE flag from the explorer suit hood so this doesn't happen

**Comment by iamthesilly** [comment]
> image Should probably remove the HIDEFACE flag from the explorer suit hood so this doesn't happen

Actually cultist hoods and the witch hunter hat have this issue as well
image
image

**Comment by iamthesilly** [comment]
I can make a separate PR to fix the clothing flags since it's not really an issue with your PR but rather just the fact that certain things have clothing flags they shouldn't have, but if you want to include it in yours, go ahead.

**Review by cuackles — APPROVED** [review]

**Comment by iamthesilly** [comment]
> image Should probably remove the HIDEFACE flag from the explorer suit hood so this doesn't happen

#18666 it's been fixed, no longer an issue

**Review by Moltijoe — APPROVED** [review]
approved, but i won't be surprised if some other bug crops up down the road

**Pull request merged**
