### PR TITLE
Changelings will be set to an absorbable species on antag gain

### LINKED ISSUE #16284: Changeling Unabsorbable bug
## Test Merges: 
Not Supplied / None
## Reproduction:
Changelings that have the obj to absorb other changelings cant absorb 'incompatible with your biology' aka skeletons and tons of other random bs

 Submitted by: Lichton (271438688100024320)

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Fixes #16284

# Changelog

:cl:  
bugfix: fixed lings spawning as unabsorbable species
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
Interesting how B00B5 the static IPC suddenly decides to become a human

**Comment by ynot01** [comment]
> Interesting how B00B5 the static IPC suddenly decides to become a human

Set to replace name with pref name or random name if pref unavailable

**Review by ReddicusDragon — APPROVED** [review]

**Comment by Notamaniac** [comment]
Hate to bring up the obvious issue, but getting changeling midround and getting transformed right in front of people might be a dead giveaway something is up. While it seems fully_replace_character_name does handle the ID/manifest issue, maybe give it a delay so that the changeling has a chance to go somewhere private first?

**Comment by The-Sun-In-Splendour** [comment]
Is it not possible to just make changeling IPCs and etc absorbable instead of forcing random appearance on you?

**Comment by Simplehorror** [comment]
> Is it not possible to just make changeling IPCs and etc absorbable instead of forcing random appearance on you?

yeah, changeling IPCs should just be robots that aren't robots but just flesh pretending to be robots

**Comment by Notamaniac** [comment]
> Is it not possible to just make changeling IPCs and etc absorbable instead of forcing random appearance on you?

Then you've got to code in IPC husks and surgeries/treatments to unhusk an IPC.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
