### PR TITLE
Introducing Eclipse Station

### PR DESCRIPTION
**Pull request by MayhemSailor**
Minsky what?

### Goodbye Minsky, hello Eclipse

Map can be viewed here (Polish Commit): https://mdb.affectedarc07.co.uk/Files/120966336/542052497/0/after.png

Station that was produced under the working title Minsky2.0 is complete and has been rebranded Eclipse Station. 

Vital station systems are complete. While maintenance could use some extra TLC, I will do that following a server test.

Interesting tidbit: there are 97 jobs on the station. 

#### Changelog

:cl:  
rscadd: Added Eclipse Station and associated files
rscdel: Removed Minsky Station and associated files
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
That bomb sat doesn't look so hot.

**Comment by MayhemSailor** [comment]
@Xoxeyos elaborate please?

**Comment by Xoxeyos** [comment]
https://imgur.com/a/8CJB3bP

I just don't think it leaves much room between dorms and the bomb deck.

**Comment by MayhemSailor** [comment]
@Xoxeyos I've moved the test area and added some rwall shielding between the range and the station.

**Comment by MonsWTF** [comment]
I'm still peering over the map and thinking of targeted feedback for my own personal opinions on "map balance", but before that I definitely had something to request for both compression and balancing. 

Three things: 
- Xenobiology has a lot of "dead space" that really isn't going to be used and pseudo-time-gates via the slime killing process. In the event the space is used, it's going to give the Xenobiologist(s) enough space to reinforce themselves even more from the two maintenance doors that lead into it.

One of the direct counters to Xenobio in Box is that maint is 2 steps away from the console, and it's very tight in terms of spacing. Not a lot of room to add onto it during the round except for the hallway that is specifically only for accessing the slime pens. 

image

It's still an inefficient setup, which will maintain the meta narrative that "departments don't start out efficiently organized". It also gives you room to 'chop off' 3-4 rows of space from the compression. 

- Can we combine the Xenobiology lab into the space of R&D + Testing Room? Based on the dimensions you will probably have to push the Tesla/Singu site down a bit, however if combined with the first point, it just barely fits the same dimensions. 

image

This change means Xenobiology is public-facing and can directly interact with people outside of science; which will reduce the amount of complaints of the department being "in hiding" and "having no way to interact with the rest of the station". This is something I've mentioned offhand in Discord (and I think to you too) for power balancing on Boxstation, and if we can balance it on Minsky too, that'd be a good step forward.

- If it can't be moved, or if it does merge with RnD/Testing, Xenobiology does not need to be surrounded by Rwalls. Theorhetically, only the public-facing walls need to be, and even the Rwalls for the Kill Chamber can be entirely (or mostly) surrounded with RGlass. The only other bit that needs Rwalls is the Xeno kill pen/Fulton Recovery pen.

**Comment by MayhemSailor** [comment]
@MonsWTF I'll take the internal setup of Xeno under consideration. I'll need to play with it to see if it is workable. 

As far as moving the department, after conducting some polling, there really isn't that much interest in making xeno a public facing department. While I personally believe that the redux in the importance of the R&D section by adding the department autolathes would justify it, it's really not something I can get general support for. In the interest of moving Minsky forward now, I am delaying that conversation until later.

As far as rWalls, R&D is a secure department and R&D is contained by them like security & engineering.

**Comment by MonsWTF** [comment]
The main reason behind the proposition of combining it is because, on default Yogs Boxstation, every time Xenobiology gets brought up, the anti-Xenobio detractors say the major faults with the job is "They hide in their reinforced bunkers and do slime work" and "They never interact with the rest of the crew".

If it was just their opinions on the subject and ungrounded, it wouldn't really be worth further consideration. However, being a regular Xenobio myself, there is indeed a lack of things happening AND available to Xenobiologists that are simply because of the mechanics of the job's design. Top-tier Xenobio requires constant slime management, there's little time to leave the Console and interact with others. 

Conversely, being at the console at almost all times - and being so deep inside the Science department - means that the Xenobiologist(s) never have opportunities to interact with crew.

Lastly, they fill a niche that R&D used to have. R&D was the place to request advanced tools; that mostly changed with the Department Protolathe change. Now people generally only go to it for RPED + parts, and BoH's. Combining the two departments will be a good move for the future, because it'll start increasing Xenobio's visibility to the crew, and enable them to more easily contribute to the station.

I can understand needing to hold off on room conversion, since Minsky has a huge amount to be worked on. In the meantime, it's worth other people contemplating such a balance change and what it could mean for Xenobio's future.

**Comment by MayhemSailor** [comment]
After fiddling with your suggestions I like the new xeno better:

Xeno MonsFTW

**Comment by Ktlwjec1** [comment]
Let me know when this is out of WIP and we can test merge it to make sure there's no major issues. From a quick glance though, looks fine to me.

**Comment by MayhemSailor** [comment]
@Ktlwjec1 and @alexkar598 this is ready for testmerge.

**Comment by MayhemSailor** [comment]
With the Z-Level issues, I am taking this down to work through compressing the east end of the station. Thank you to all of you who have provided feedback thus far. Stay tuned, Eclipse will be back shortly!

**Pull request closed without merging**
