### PR TITLE
Ports 'Adds area-based wire layouts to airlocks'

### PR DESCRIPTION
**Pull request by Bibby0110**
Ports https://github.com/tgstation/tgstation/pull/52563 and https://github.com/tgstation/tgstation/pull/52679

### About The Pull Request
Modifies the area datum to specify an airlock wire datum for that area.

Modifies various areas to include unique departmental wire datums.

A brief overview of area wire designations from Space_Station_13_areas.dm

MAINT
/area/maintenance/...

COMMAND
/area/bridge/...
/area/crew_quarters/heads/...
/area/teleporter/...
/area/gateway/...
/area/security/nuke_storage/...
/area/ai_monitored/nuke_storage/...

SERVICE
/area/crew_quarters/kitchen/...
/area/crew_quarters/bar/...
/area/quartermaster/...
/area/janitor/...
/area/hydroponics/...

SECURITY
/area/security/...
/area/ai_monitored/security/armory/...

ENGINEERING
/area/engine/...
/area/solar/...
/area/tcommsat/...

MEDBAY
/area/medical/...

SCIENCE
/area/science/...

AI
/area/ai_monitored/storage/satellite/...
/area/ai_monitored/turret_protected/...
/area/aisat/...

PUBLIC
/area/hallway/...
/area/crew_quarters/...
/area/library/...
/area/chapel/...
/area/lawoffice/...
/area/construction/...
/area/storage/...
/area/ai_monitored/storage/eva/...

Public is basically the generic airlock wire assignments (in other words, these areas do not override the default wires). All other areas use generic airlock wire assignments, however it would not be difficult to add "ss13_generic" wire datum if you want the station in its entirety to have a different wirenet from anything off-station.

Of course, re-using on-station areas in off-station locations will share wire assignments.

Because wire assignments are set on airlock Init(), this means that ANY airlock constructed will have its wires automatically assigned based on the area. If necessary, I can include a mapload check in Initialise and make all doors created after round-start just have generic wires.

There should probably be a map sweep before merging to identify edge cases where maint doors are covered under departmental areas and doors that border multiple departments aren't appropriate set.

Things that come to mind are Delta's vault, which has a door assigned to the hallway area and Delta's Engi/Xenobio maint, that has maint doors covered under their respective department areas.

### Why It's Good For The Game
Hacking takes a little bit more effort than learning just one set of wires, however hacking isn't totally random. Departmental areas will share a common wire layout.

Encourages more cooperation and reliance between players when hacking. This includes sharing wire assignments for specific areas, stealing blueprints, grabbing insuls, asking engy borgos to read wire assignments for you, or figuring out another means of access that isn't hacking - Including bombs, B&E, finding weak walls to deconstruct/turn into hidden doors, finding higher level access ID cards to just walk in, etc.

### Changelog
:cl:
tweak: CentCom scientists and engineers have upgraded airlock doors throughout NanoTrasen stations. When constructed, airlock doors now automatically configure themselves based on location, adopting unique wire layouts in different station areas. Pray your CE knows how to read his blueprints, pack your marigolds and joyride a cyborg into a new age of departmental security.
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
>There should probably be a map sweep before merging to identify edge cases where maint doors are covered under departmental areas and doors that border multiple departments aren't appropriate set.

Couldn't you just set the wires on the maint door subtype to always be /datum/wires/airlock/maint ?

**Comment by Bibby0110** [comment]
> > There should probably be a map sweep before merging to identify edge cases where maint doors are covered under departmental areas and doors that border multiple departments aren't appropriate set.
> 
> Couldn't you just set the wires on the maint door subtype to always be /datum/wires/airlock/maint ?

They could have, but that would just be weird

**Comment by Amelia0010** [comment]
Why would that be weird?

**Comment by Bibby0110** [comment]
> Why would that be weird?

Shitcode

**Comment by MegaEmpirical** [comment]
Fuck yeah, I wanted this a long time ago but it didn't seem to get added. Nicely done.

**Comment by Amelia0010** [comment]
It's not shitcode though, it's a simple solution to the problem

**Comment by Bibby0110** [comment]
> It's not shitcode though, it's a simple solution to the problem

No need to hardcode it. If a maint door needs department based wires or maint based wires it's up to the mapper

**Comment by MrHorizons** [comment]
I had just finished making this same PR, but fine, I guess. +1.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
