### PR TITLE
Adds Rejuvenate to every mobs right click menu for Admins

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

QoL fix for admin menu, adds rejuvenate to all mobs via right click menu

#### Changelog

:cl:  
rscadd: Adds Rejuv to mobs, helpful for reviving ghosted bodies or mobs
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
If your intent is to change which bodies can be right-click -> rejuvenate, change the first argument in https://github.com/yogstation13/Yogstation/blob/34444062fd77ea0da96581215406612f2e2e3669/code/modules/admin/verbs/randomverbs.dm#L534 instead.

**Comment by JamieD1** [comment]
> If your intent is to change which bodies can be right-click -> rejuvenate, change the first argument in
> 
> https://github.com/yogstation13/Yogstation/blob/34444062fd77ea0da96581215406612f2e2e3669/code/modules/admin/verbs/randomverbs.dm#L534
> 
> instead.

No its the fact the verb doesn't appear unless what ive added is added.

**Comment by JamieD1** [comment]
Added another verb,

 [Screenshot from Gyazo](https://gyazo.com/7168dd92795206a04a1aba484ed564ec)

Useful for quick cleanup of areas

**Comment by Bibby0110** [comment]
> Added another verb,
> 
> [Screenshot from Gyazo](https://gyazo.com/7168dd92795206a04a1aba484ed564ec)
> 
> Useful for quick cleanup of areas

We already have buildmode which can restore an area to roundstart, which is useful for griefers.

**Comment by JamieD1** [comment]
Reverted the Floor commit

**Comment by athena413** [comment]
good

**Comment by swissloaf** [comment]
> good

who are you

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Either remove it from debug verbs or close this PR because its already in the debug verbs thing

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
