### PR TITLE
removes goliath stun in favor of more damage

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

no more goliath stun
significant damage and knockdown instead

### Why is this change good for the game?

stun is bad game design

:cl:  
tweak: Removed goliath stun in favor of more damage
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Amazing idea, goliath stunlocking is shitty

**Comment by ChesterTheCheesy** [comment]
where's the "ided" tag?

**Comment by ToasterBiome** [comment]
BABYMINING, simply do not walk onto the goliath spikes

**Comment by UselessTheremin** [comment]
yeah the stun is fine until you get more than 2 goliaths then it becomes a factor of dumb luck. good change, skill better than luck

**Comment by UselessTheremin** [comment]
also did you get stunlocked by a goliath ynot

**Comment by ynot01** [comment]
> also did you get stunlocked by a goliath ynot

 once or twice in the distant past

**Comment by ToasterBiome** [comment]
Someone just got stunlocked and ded this round, simply do not walk into the spikes, you are sonic speed on lavaland anyway

**Comment by ChesterTheCheesy** [comment]
You literally cannot be grabbed if you move diagonally, you're just bad if you think that stunlocking goliaths is an issue. The only time that happens is at goliath tendrils, but that's literally the only challenge goliaths ever pose to a PKA user.

Oh and stunlock ends at melee range, so it's not even a true stunlock.

**Comment by N3D6** [comment]
> You literally cannot be grabbed if you move diagonally, you're just bad if you think that stunlocking goliaths is an issue. The only time that happens is at goliath tendrils, but that's literally the only challenge goliaths ever pose to a PKA user.
> 
> Oh and stunlock ends at melee range, so it's not even a true stunlock.

New miners constantly dying to being fucked by goliaths is an issue that makes a lot of people give up on playing miner. I agree the stunlock is easy to avoid but its a shitty mindset to say "just get better" about it.

**Comment by ToasterBiome** [comment]
> > You literally cannot be grabbed if you move diagonally, you're just bad if you think that stunlocking goliaths is an issue. The only time that happens is at goliath tendrils, but that's literally the only challenge goliaths ever pose to a PKA user.
> > Oh and stunlock ends at melee range, so it's not even a true stunlock.
> 
> New miners constantly dying to being fucked by goliaths is an issue that makes a lot of people give up on playing miner. I agree the stunlock is easy to avoid but its a shitty mindset to say "just get better" about it.

I died to regular goliath the first time and all it did was want to make me kill all goliaths. It fueled my love for mining because of how fast things can go to shit. 38h mining. That's just part of the game like all other aspects of ss13

**Comment by ynot01** [comment]
> Oh and stunlock ends at melee range, so it's not even a true stunlock.

if you get hit by a goliath tentacle, you stand still for a bit and take damage, you take maybe 2-3 hits from the goliath, and you walk away and kill it, no biggie.

the idea of this PR is that I'm cutting the stun and you take all the damage straight away (numbers to be adjusted if necessary)

all this is realistically doing is making it so you cant get stunfucked by 2 goliaths

**Comment by ChesterTheCheesy** [comment]
Yeah, the mining is supposed to be a dangerous job. Also, getting double-snared is an instant crit in this change, so i'd say it's even worse than being stunned and beaten once or twice.

**Comment by ToasterBiome** [comment]
making goliath not stun is also goliath erasure. Lets replace all the lavaland mobs with spiders that do nothing unique

**Comment by N3D6** [comment]
> > > You literally cannot be grabbed if you move diagonally, you're just bad if you think that stunlocking goliaths is an issue. The only time that happens is at goliath tendrils, but that's literally the only challenge goliaths ever pose to a PKA user.
> > > Oh and stunlock ends at melee range, so it's not even a true stunlock.
> > 
> > 
> > New miners constantly dying to being fucked by goliaths is an issue that makes a lot of people give up on playing miner. I agree the stunlock is easy to avoid but its a shitty mindset to say "just get better" about it.
> 
> I died to regular goliath the first time and all it did was want to make me kill all goliaths. It fueled my love for mining because of how fast things can go to shit. 38h mining. That's just part of the game like all other aspects of ss13

If thats the way you see it, I understand why you say that really, but I just think it'd be better to get rid of the stun and go straight to the goliath dealing more damage.

**Comment by ynot01** [comment]
> Also, getting double-snared is an instant crit in this change, so i'd say it's even worse than being stunned and beaten once or twice.

getting double snared before was literally guaranteed death, the change is that you can now dodge the second snare and not guaranteed die

**Comment by ChesterTheCheesy** [comment]
Have to agree with the Toaster lad, just damage is boring, how about you make it knocks you down to the groud instead?

**Comment by N3D6** [comment]
> Have to agree with the Toaster lad, just damage is boring, how about you make it knocks you down to the groud instead?

This also seems nice.

**Comment by ynot01** [comment]
> Have to agree with the Toaster lad, just damage is boring, how about you make it knocks you down to the groud instead?

i can agree with this as long as there's no stun/paralyze

**Comment by ChesterTheCheesy** [comment]
> 
> 
> > Also, getting double-snared is an instant crit in this change, so i'd say it's even worse than being stunned and beaten once or twice.
> 
> getting double snared before was literally guaranteed death, the change is that you can now dodge the second snare and not guaranteed die

Goliaths stack their attacks on top of each other, that's what i meant by "double snare"

**Comment by ToasterBiome** [comment]
That would be a change that I could get behind, falling down is better than just doing damage. It seems like a change that doesn't need to happen still

**Comment by N3D6** [comment]
I feel like a healthy medium here would be a slight slowdown or the knocking down thing, which just makes you crawl, less chance to be stunlocked and fucked over.

**Comment by ToasterBiome** [comment]
> I feel like a healthy medium here would be a slight slowdown or the knocking down thing, which just makes you crawl, less chance to be stunlocked and fucked over.

I agree with this change. I don't think you should be spared from the change of dying to a goliath if you don't know what you're doing, so this makes it slightly better. I think it SHOULD knock you down though, because a slowdown is already the watcher ability.

**Comment by UselessTheremin** [comment]
"mining is supposed to be a dangerous job"
mining is supposed to be a fun job nerd and nobody likes it when all the miners immediately die, stunlocks aint fun and "git gud scrub" is a shitty mindset to have for newer players especially

**Comment by ChesterTheCheesy** [comment]
Make it like the goliath broodmother one for consistency sake. It knocks you down and makes you drop your held items.

**Comment by ToasterBiome** [comment]
Oh shit I actually like Someguy's change better,



> "mining is supposed to be a dangerous job"
> mining is supposed to be a fun job nerd and nobody likes it when all the miners immediately die, stunlocks aint fun and "git gud scrub" is a shitty mindset to have for newer players especially

I'm not implying that, I'm saying there should be _some_ danger to mining. It's not fun getting instastunned at the start but also if there's nothing to actually fight it's just boring mining.

**Comment by ynot01** [comment]
knockdown for 5 seconds implemented

**Comment by N3D6** [comment]
Theos' pr is also pretty good, I like them both really

**Pull request closed without merging**
