### PR TITLE
i don't know how to code but this should make the detmatrix always succeed

### PR DESCRIPTION
**Pull request by ghost**
it probably won't work though

anyway why would you spend TC on a traitor item that has a non-zero chance to fail every fucking time you try for it???
why??

i guess you could call this a port because we had this feature on old yogs
#### Changelog

:cl:  
tweak: Detomatrix now always succeeds.
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
>tweak: changelogs don't even work anymore why do we bother?
🤔

**Comment by ThatLing** [comment]
thats not a valid changelog

**Comment by daklj** [comment]
it was nerfed for a reason, maybe dont buy it and if you cant succeed without insta remote undetectable paralysis + delimb + 40 damage + id removal 6TC 5 uses tool maybe disable traitor

**Comment by ghost** [comment]
congratulations dak

that was the stupidest comment i've ever read on github and i've had to suffer through aphielansin's bullshit

**Comment by ghost** [comment]
holy shit i'm giggling

i'd break it down but holy shit

is- i can't

**Comment by ThatLing** [comment]
I'm all for this if you lower the amount of charges or up the price

**Comment by ghost** [comment]
you can buy far more effective and lethal weapons for far less 

this is functionally a meme item, there's no reason it should randomly fail to

**Pull request merged**
