### PR TITLE
removes the nukies' nuke, makes them use the self-destruct device

### PR DESCRIPTION
**Pull request by Amelia0010**
Do you ever just see the nuke being armed, and wonder (hmm, maybe I can find it and do something about it? Well, now you can, since it will no longer be armed in places like "lower left solars" and shit like that, instead being the vault nuke!

:cl:
tweak: the nuclear self-destruct device will now be used by nuclear operatives, instead of them bringing their own nuclear device
/:cl:

sidenote, why do they need a nanotrasen nuke disk to blow up their own bomb, that shit don't make sense.

### CODE REVIEW

**Comment by Moja10** [comment]
You stupid fucking twat. You s stupid stupid fucking twat. That isn't there own nuke, retard. It's a stolen nanotrasen nuke. From nanotrasen. That uses nanotrasen nuclear authentication codes. Not syndicate codes. It's not a syndicate nuke. You dense motherfucker. Gdt this through your thick skull or there's going to be hell to pay.

**Comment by Nickvr628** [comment]
I like it, it might be really fun, but I foresee a lot of super fortified vaults being created once people start shouting nukies.  

War Ops would be suicidal since the crew would just fill the vault with Rwalls and turrets and ignore the rest of the station. 

I am open to trying it

**Comment by fluffe9911** [comment]
*laughs in syndie bomb*

Edit or if rd *laughs in toxins bomb*

**Comment by Moja10** [comment]
I'd be fine with this being merged on the condition that it is removed if it's especially retarded in practice.

**Comment by Amelia0010** [comment]
do you even know how to revert a PR?

**Comment by Smudged** [comment]
Sometimes it's hard enough as a nukie not sure how i feel about it saddly

**Comment by ghost** [comment]
bad pr

**Comment by ghost** [comment]
this is really just fucking stupid all around.

**Comment by jcatjmeow** [comment]
can we dont?

**Comment by zxmongoose** [comment]
No.

Make it work similar to blood cult instead: ops get three rooms where the nuke can be armed. Something something "structural weakness" or something.

**Comment by ShadowDeath6** [comment]
wasn’t the lore behind it that they stole the nuke from an old NT munitions area so they have those codes but still need the disk to authorize it

**Comment by Amelia0010** [comment]
I cannot fathom a good way specific areas to bomb would work.

**Comment by jcatjmeow** [comment]
Just uh make it so the place they bomb needs to be an area not safe from rad storms or it doesn't work, so no maint no solars no space

**Comment by Amelia0010** [comment]
yes but the bomb can be moved, so what happens if it gets moved after having been planted? does it stop the countdown when it gets outside the area, does it simply just explode but where it was moved to, does it say they failed?

**Comment by jcatjmeow** [comment]
Only check where it is when it explodes, say that being in space causes the heat to dissipate and results in a smaller explosion/minor victory

**Comment by zxmongoose** [comment]
I don't think anything should change if it gets moved unless it explodes in space. It shouldn't affect the countdown or win condition if the bomb is moved from the area it had to be armed in. I think if they want nukies should be able to arm the nuke somewhere and move it somewhere else if they want to take the time to do so. The point is just to get them to an actual room somewhere INSIDE the station again before they can just jump to the safety of their ship without making every nukes ops round "everyone stand in front of the vault and wait for them to run out of bullets"

**Pull request closed without merging**
