### PR TITLE
[READY] Goon Genetics (#41258)

### PR DESCRIPTION
**Pull request by Amelia0010**
GENETICS

    The random hexadecimal rng game has been replaced with gene sequencing from goon.

    Adds mutation activators and mutators

    You can now store mutations

    Everyone now has their own set of unique mutations

    Limited mutations per person to 8 (including one always being monkey)

    Adds race specific mutations (See fire breathing for lizads)

    You can inspect discovered mutations, undiscovered mutations use an alias to recognize them by

    Adds a sequence analyzer. Can be used to scan someones genes sequence. Useful for determing what mutations they can safely have and or collecting data for very difficult sequences

    Adds mutation combining. It's currently only RADIOACTIVE + STRONG = HULK (So yes you will now need 2 mutations for to get hulk)

    Adds several other mutations. Telepathy, firebreath, glowy, radioactive and strength

#### Changelog

:cl:  Time-Green
add: Goon genetics!
add: More mutations! Fire breath for lizards! Radioactive! Telepathy! Glowy! Strength, though its cosmetic and should be combined with radioactivity instead! Fiery sweat!
add: Adds void magnet mutation by @tralezab !
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
jesus christ nich where did you get all this free time

**Comment by Time-Green** [comment]
reeeeeee

**Comment by Amelia0010** [comment]
This is what happens when you PR upstream time :^)

**Comment by Time-Green** [comment]
I know :^)

**Comment by CMOisLing** [comment]
Time to put genetics on medium again

**Comment by Time-Green** [comment]
honk i accidently added cluwne injectors as a side effect

**Comment by fluffe9911** [comment]
nice

**Comment by Amelia0010** [comment]
@Time-Green the locked var prevents them occuring naturally, right?

**Comment by Time-Green** [comment]
> @Time-Green the locked var prevents them occuring naturally, right?

Yeah, but unless cluwne is hidden it can still be extracted through dna consoles

**Comment by Amelia0010** [comment]
As in extracted FROM a cluwne?

**Comment by Time-Green** [comment]
Yep

**Comment by Amelia0010** [comment]
ok I'm fne with that

**Pull request merged**
