### PR TITLE
Bible is only antimagic if you are a true worshipper

### PR DESCRIPTION
**Pull request by ToasterBiome**
image
# Document the changes in your pull request

atheists after saying "lol god isn't real" when someone say wizard is on station

image

you only get the antimagic benefits if you are a true believer of your god

# Wiki Documentation

bible only work if you are a chad

# Changelog

:cl:  
tweak: no bible antimagic if you are a powergamer
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
wtf alexkar lie??

**Comment by Jarod1200** [comment]
You do realize that "holy" antimagic is like only good against ocular wardens and conversion. Its like how having holy water in your system makes you unable to be converted but you still suffer spell effects.

**Comment by ToasterBiome** [comment]
> You do realize that "holy" antimagic is like only good against ocular wardens and conversion. Its like how having holy water in your system makes you unable to be converted but you still suffer spell effects.

yes, alexkar misrepresented the truth (that bible is what makes chaplain immune to magic)

**Comment by Moja10** [comment]
This is very needed

**Review by Bibby0110 — APPROVED** [review]
bad code

**Comment by bruhlookatthisdood** [comment]
maybe getting converted by a tech priest or eldritch god or something like that by the Chaplin will cause you to become a believer?

on another point maybe make it so you cant use the bible to do altar rites as a non believer (dunno if its fixed, i saw someone convert the Chaplin by using a bible while Chaplin was on the altar)

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
