### PR TITLE
[Box] Removes door from science research room

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

Removes the door leading into R&D research room.

This is a map change for an admin issue, and also punishes Robos because they can't get in. People powergaming into R&D is an admin issue, not a map issue.

# Spriting

# Wiki Documentation

# Changelog

:cl:  
mapping: removes door blocking science research room on box
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
thank you

**Comment by cuackles** [comment]
adding to that, the rnd console its id locked now so even if an assistant or someone else broke in, without access they cannot research anything

**Comment by ToasterBiome** [comment]
remove id locking period

**Comment by Moja10** [comment]
Neutral, I don't care either way. But I would check since I think you are technically going against a council vote (I recall a council vote on this but can't recall)

**Comment by Maia-J** [comment]
I unlock the door as RD anyway, why keep it?

**Comment by N3D6** [comment]
> Neutral, I don't care either way. But I would check since I think you are technically going against a council vote (I recall a council vote on this but can't recall)

There wasn't a council vote made on this issue, as far as I can tell

**Comment by N3D6** [comment]
> remove id locking period

Let's see how this goes first

**Comment by JamieD1** [comment]
This was a Xantam issue

**Comment by JamieD1** [comment]
Would prefer you made it the same before we changed it.
image

**Comment by N3D6** [comment]
> Would prefer you made it the same before we changed it.
> 
> image
> 
> 

Will do

**Comment by ToasterBiome** [comment]
> > Would prefer you made it the same before we changed it.
> > image
> 
> Will do

when doe

**Comment by N3D6** [comment]
- [x] Haha jonothan you have zero motivation to map as of right now

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
