### PR TITLE
replaces the thousand color floor tile sprites

### PR DESCRIPTION
**Pull request by Potototatoh**
Screenshot (2401)

replaces old tiles; they (mostly) use 8 seperate colors as opposed to the ancient 300* something the currently in-place ones use 

alters the 3 common floor-types (grey, dark, light and respective overlay variants (mostly)), also adds an absent dark floor mech bay animation for the sake of consistency

# Changelog

🆑
imageadd: floor tiles
imagedel: old floor tiles
tweak: changes common floor tiles
/🆑

### CODE REVIEW

**Comment by Potototatoh** [comment]
Screenshot (2402)

forgot to show off the white tiles theyre really tame in comparison

**Comment by ToasterBiome** [comment]
I kinda fuck wit this HARD

**Comment by cuackles** [comment]
Hot

**Review by cuackles — APPROVED** [review]

**Comment by ToasterBiome** [comment]
They're a bit too strong honestly, seeing them in-game

**Comment by Potototatoh** [comment]
i suspect youre talking about the black tiles but yeah they are

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
There are multiple issues with this PR other than from the black tiles, Everything is too strong. When I ran this through It made me feel like every tile on my screen was wet with space lube. 
floortest

The scorched replacement also does not really hold a candle to the old one it's replacing and instead of looking scorched looks more like someone just spray-painted the tiles black.
Firetest

Finally, I found some oddity with the combinations of explosion hull damage, Everything in that regard looks fine except for this one egged-shaped asset that looks out of place and does not go well with the other ones, Could be better used as a one-spot of impact sprite but for it to be spread around like this is kinda off. 
Explosion

**Comment by JamieD1** [comment]
I really dont like how they are just squares on squares now, they in my opinion do not look as good at all.

**Comment by KillerOrcaCora** [comment]
Many things are being replaced that just don't outperform what is already here, If you need specific help on anything you can send me a friend request with this, Orca Cora#9145.

**Comment by ToasterBiome** [comment]
Said they were actively looking at changes from feedback

**Comment by Potototatoh** [comment]
the damaged tiles were sort of a crude fix and just used overlays from a baystation dmi and tacked them on over the tops of them, i definitely wouldve used what was already here if i couldve found a reference

**Pull request closed without merging**
