### PR TITLE
Adds staff of variables

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
image

### CODE REVIEW

**Comment by Nickvr628** [comment]
This needs to be speedmerged immediately

**Comment by k-k-karma** [comment]
oh god oh fuck

**Comment by Amelia0010** [comment]
🤔

**Comment by Amelia0010** [comment]
Having this in is just asking for some retarded admin to give it as a TC-trade because they don't know how anything works, leading to the round being ended because the lad used the staff on the nuke causing it to explode.

**Pull request closed without merging**
