### PR TITLE
Revert "Revert "Stuns and Stamcrit Now Radio Mute""

### PR DESCRIPTION
**Pull request by SomeguyManperson**
on god this is why we have testmerges

### CODE REVIEW

**Comment by Reed0506** [comment]
"hmm yes today we shall buff stun combat, the thing that everyone generally agrees is overpowered and not fun"

**Comment by maxion12345** [comment]
this doesn't even mute your radio it just makes it so when you try to use a radio it literally won't go into the chat, even if your not muted

**Comment by ghost** [comment]
what do you know it was a shit idea and everyone is bitching to me about it

**Comment by alexkar598** [comment]
This just makes stun even more powerful then they already are

**Pull request closed without merging**
