### PR TITLE
removes ashwalkers first aid kit

### PR DESCRIPTION
**Pull request by boodaliboo**
with all of marmios tribal medicine prs they dont need this and it will encourage them to actually make these
they still have a health analyzer though
#### Changelog

:cl:  
rscdel: Removed ashwalkers medical kit
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
the health analyzer is actually incredibly useful, even if it doesn't fit the tribal theme. Please keep it.

**Comment by boodaliboo** [comment]
> the health analyzer is actually incredibly useful, even if it doesn't fit the tribal theme. Please keep it.

sure

**Comment by patpol4** [comment]
Am i missing something? I cant find the pr's you talk about, just cheese and mushroom alcohol.

**Comment by boodaliboo** [comment]
> Am i missing something? I cant find the pr's you talk about, just cheese and mushroom alcohol.

they were merged

**Review by patpol4 — APPROVED** [review]
Alright. it was pretty far back the list.

**Pull request merged**
