### PR TITLE
adds shlong sizes to men (and women)

### PR DESCRIPTION
**Pull request by GuppyLaxx**
men now have a random shlong size (usually)
goes by your ethnicity to simulate realism

women too sometimes.

### CODE REVIEW

**Review by Kmc2000 — APPROVED** [review]

**Comment by HomocidlePancakes** [comment]
Look at this nerd stealing features from citadel. NEEEEEEEEEEEEEEEEEEEERD

**Comment by ErwinSnowden** [comment]
reopen now or no admin yogstation 2

**Comment by Amelia0010** [comment]
what

**Comment by alt0173** [comment]
Based and floorpilled

**Comment by OrderoftheDarkOats** [comment]
merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it d merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it o merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it n merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it merge it t merge it merge it merge it merge it merge it merge it

**Comment by Codeatmos** [comment]
reopen now

**Pull request closed without merging**
