### PR TITLE
Add auxmos to the minor filter

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

instead of saying "auxmos" IC you will now say "La Li Lu Le Lo"

# Why is this good for the game?

the nanites in your bloodstream react violently to this word

# Testing

goodbye_auxmos

# Changelog

:cl:  
rscadd: Adds auxmos to the minor filter
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
add aux mos too

**Comment by iloveloopers** [comment]
1984 where is our freedom of speech

**Comment by ShoziOffical** [comment]
:shipit:

**Comment by ShoziOffical** [comment]
> add aux mos too

uh i dont think that is enough

**Comment by cowbot92** [comment]
> add aux mos too

added it

**Review by adamsong — CHANGES_REQUESTED** [review]
Please provide evidence of testing

**Comment by cowbot92** [comment]
> Please provide evidence of testing

Testing section updated

**Comment by Yarinoi** [comment]
the la li lu le lo..

**Review by adamsong — APPROVED** [review]
I'm glad we have the instruction manual on leadership titled "1984"

**Review by ToasterBiome — APPROVED** [review]

**Comment by ToasterBiome** [comment]
> I'm glad we have the instruction manual on leadership titled "1984"

who watches the watchers

**Comment by Beeper-Skeeper** [comment]
why is there a borg
what is he doing there.

**Pull request merged**
