### PR TITLE
readds suit storage bind

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

image

# Changelog

:cl:  
bugfix: fixed suit storage bind missing
bugfix: fixed rest hotkey not working
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
Did you test this?

**Comment by Bibby0110** [comment]
Feature freeze

**Comment by ynot01** [comment]
> Did you test this?

No I can't compile locally

**Comment by JamieD1** [comment]
> > Did you test this?
> 
> No I can't compile locally

Can you readd the rest hotkey too

**Comment by ynot01** [comment]
ok i was able to compile locally

**Pull request merged**
