### PR TITLE
Adds a new PDA ringtone

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

More modern, two beeps is severely outdated, we live in 2523 guys

# Changelog

:cl:  
soundadd: added a new PDA ringtone
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
2517

**Comment by Hislyna** [comment]
216 charlie is my favourite ringtone

**Comment by JohnFulpWillard** [comment]
This PR is racist

**Comment by Mqiib** [comment]
I am so torn on this because it's funny but also I'm going to kill you.

**Comment by Yarinoi** [comment]
good

fucking



RIDDANCE

**Pull request closed without merging**
