### PR TITLE
Removes all hard stuns from the codebase

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

wahhh hardstuns bad :(

# Wiki Documentation

# Changelog

:cl:  
rscdel: Hardstuns are gone, and no, before you ask, we haven't bothered to balance any antags relying on them
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
You forgot Stun()

**Comment by bruhlookatthisdood** [comment]
Fetish Content
Seems like another shadowling nerf to me.

**Comment by Bibby0110** [comment]
> You forgot Stun()

Doesn't count

**Comment by Marmio64** [comment]
Genius. This is best PR

**Comment by Bibby0110** [comment]
> Genius. This is best PR

thank you

**Comment by bruhlookatthisdood** [comment]
I love this PR

**Comment by Cartlord** [comment]
I was under the impression that "joke" P.R.s weren't really allowed any more.

**Comment by Anvilman6** [comment]
Now this is epic

**Comment by Hopekz** [comment]
> I was under the impression that "joke" P.R.s weren't really allowed any more.

This ain't no joke.
The future is now old man

**Comment by Bibby0110** [comment]
> I was under the impression that "joke" P.R.s weren't really allowed any more.

why do you even care lol

**Comment by Moja10** [comment]
Shit change

**Comment by Bibby0110** [comment]
> Shit change

ok """moja"""

**Comment by Altoids1** [comment]
I love the respecting, constructive discourse this community has about balance changes

**Comment by Moja10** [comment]
> I love the respecting, constructive discourse this community has about balance changes

Simp harder bitch, no cap

**Pull request closed without merging**
