### PR TITLE
Adds emergency spare, a temporary ID with AA that heads can print

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Pressing the button on the comms console will trigger a command report, and print a temp ID. After 50 seconds, the ID will start to smolder. 10 seconds later, it will catch fire and turn to ash. Don't be holding it when this happens.

The ID has the same access as the spare, without heads, or id change access.

# Changelog

:cl:  
rscadd: Added a temp spare heads can print from the comms console.
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
but why

**Comment by Anvilman6** [comment]
Maybe just make it fizzle out
rather than start a fire

Would be neat if you could examine it to check how much time it has left

**Comment by adamsong** [comment]
> rather than start a fire

You get 10 seconds warning, past that, its on you

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Authentication check

**Comment by JamieD1** [comment]
@adamsong

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Replace your authentication check with authenticated_as_silicon_or_head
You’ll have to create the proc but that shouldn’t be hard

**Pull request merged**
