### PR TITLE
Random Body/Appearance Banned now randomised between Normal and Digigrade legs

### PR DESCRIPTION
**Pull request by JamieD1**
Random Body/Appearance Banned now randomises between Normal and Digigrade legs

:cl:  
rscadd: Random Body/Appearance Banned now randomises between Normal and Digigrade legs
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Fill out the template

**Comment by JamieD1** [comment]
> Fill out the template

.....

**Comment by Bibby0110** [comment]
> > Fill out the template
> 
> .....

Do it.

**Comment by JamieD1** [comment]
> > > Fill out the template
> > 
> > 
> > .....
> 
> Do it.

Tell me what I need to fill out mr. Never fill out a fucking changelog in his life.

**Comment by Bibby0110** [comment]
> > > > Fill out the template
> > > 
> > > 
> > > .....
> > 
> > 
> > Do it.
> 
> Tell me what I need to fill out mr. Never fill out a fucking changelog in his life.

All of it. You can't just delete the headers

**Comment by JamieD1** [comment]
> > > > > Fill out the template
> > > > 
> > > > 
> > > > .....
> > > 
> > > 
> > > Do it.
> > 
> > 
> > Tell me what I need to fill out mr. Never fill out a fucking changelog in his life.
> 
> All of it. You can't just delete the headers

If they dont apply.. yes I can?

**Comment by Bibby0110** [comment]
> > > > > > Fill out the template
> > > > > 
> > > > > 
> > > > > .....
> > > > 
> > > > 
> > > > Do it.
> > > 
> > > 
> > > Tell me what I need to fill out mr. Never fill out a fucking changelog in his life.
> > 
> > 
> > All of it. You can't just delete the headers
> 
> If they dont apply.. yes I can?

How does wiki documentation not apply?

**Comment by JamieD1** [comment]
> > > > > > > Fill out the template
> > > > > > 
> > > > > > 
> > > > > > .....
> > > > > 
> > > > > 
> > > > > Do it.
> > > > 
> > > > 
> > > > Tell me what I need to fill out mr. Never fill out a fucking changelog in his life.
> > > 
> > > 
> > > All of it. You can't just delete the headers
> > 
> > 
> > If they dont apply.. yes I can?
> 
> How does wiki documentation not apply?

Show me the wiki page. Ill wait.

**Comment by Bibby0110** [comment]
> > > > > > > > Fill out the template
> > > > > > > 
> > > > > > > 
> > > > > > > .....
> > > > > > 
> > > > > > 
> > > > > > Do it.
> > > > > 
> > > > > 
> > > > > Tell me what I need to fill out mr. Never fill out a fucking changelog in his life.
> > > > 
> > > > 
> > > > All of it. You can't just delete the headers
> > > 
> > > 
> > > If they dont apply.. yes I can?
> > 
> > 
> > How does wiki documentation not apply?
> 
> Show me the wiki page. Ill wait.

That’s not an argument. “There’s missing wiki documentation so I don’t have to provide any :DDD”

**Comment by SomeguyManperson** [comment]
I don'tttt think people should be randomly made disabled at the start of the round if they are randomizing

**Comment by JamieD1** [comment]
> I don'tttt think people should be randomly made disabled at the start of the round if they are randomizing

wat

**Comment by ToasterBiome** [comment]
appearance ban should species ban you

**Pull request closed without merging**
