### PR TITLE
[PORT] [READY] Kitchen Rework part 1: I just want to griddle!

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Ports https://github.com/tgstation/tgstation/pull/55319

This PR essentialy moves away from the extremely microwave dependent cooking we have for meat right now, and making it a bit more sensical by making you use a grill to grill meat. The grill takes a different time (with variation) for different grilled things. Once finished it will turn that food into something else.

Yes, this does mean creating burgers takes longer, but in return you can make more patties at once (YOGS: with upgrades), and you are not required to stay at the grill while its going. This lets you cook as much as you want at once, just make sure your meat doesn't burn!

This includes uncraftable chicken patties/meatballs, for the future

Maps:

Box (you get the idea):
image

Meta:
image

Delta: 
image

Eclipse (is this the only cook area on eclipse?):
image

Kilo:
image

# Wiki Documentation

The recipes will have to be changed on the wiki, basically all burgers that require slabs require patties now. Look at the changelog to gleam

# Changelog

:cl:  
add: adds protein nutriment
add: Adds the griddle, a panless stove/grill for you to bake your meat products on. Nanotrasen has decided to move away from microwaving everything
add: added them to the maps
tweak: Burgers are now made from patties, patties are grilled on the griddle, raw patties are made by using a rolling pin on a raw meatball
tweak: Most meat is grilled on the griddle now instead of microwaved
sprite: new meatball, patty and sausage sprites
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
You forgot omega, also yes, eclipse does have more kitchen areas, in its own templates and scattered around the map

**Comment by ToasterBiome** [comment]
> You forgot omega, also yes, eclipse does have more kitchen areas, in its own templates and scattered around the map

I don't even think omega is selectable as a map anymore? There was the bounty to replace it with Kilo.

**Comment by patpol4** [comment]
> > You forgot omega, also yes, eclipse does have more kitchen areas, in its own templates and scattered around the map
> 
> I don't even think omega is selectable as a map anymore? There was the bounty to replace it with Kilo.

Yes but then HD decided to keep omega for some reason, despite the bounty and me pressuring for it to be removed.

**Review by patpol4 — APPROVED** [review]
Maps looks fine, simple change.

**Comment by Cartlord** [comment]
Can griddles be upgraded?

**Comment by ToasterBiome** [comment]
> Can griddles be upgraded?

tg doesn’t even let you deconstruct them, i added that functionality, upgrades do nothing

**Review by nesisknesis — APPROVED** [review]

**Comment by TheBombMakerJL** [comment]
This is quite possibly the worst speed merge I have ever seen, and the worst PR I have ever had the displeasure of participating in

Meat is a factor in almost half of the food recipes, and almost all of them that are worthwhile (high nutriment, high vitamins)

If you leave the griddle for more than half a second and it cooks, then well, too bad, it's now burnt to a crisp
If you don't grab the meat after half a second, too bad, it's now burnt to a crisp

Have fun making food during highpop, when you have to stand next to the griddle for however long it takes to cook

**Comment by ToasterBiome** [comment]
> This is quite possibly the worst speed merge I have ever seen, and the worst PR I have ever had the displeasure of participating in
> 
> Meat is a factor in almost half of the food recipes, and almost all of them that are worthwhile (high nutriment, high vitamins)
> 
> If you leave the griddle for more than half a second and it cooks, then well, too bad, it's now burnt to a crisp If you don't grab the meat after half a second, too bad, it's now burnt to a crisp
> 
> Have fun making food during highpop, when you have to stand next to the griddle for however long it takes to cook

Skill issue. All the meat has 40-90 second grilling timers, enough time to do other things.
Also better food = more “skill” required??

TG does fine with the griddle AND the oven AND more food changes where things take more time. Hugbox.

**Comment by Cartlord** [comment]
You say "TG does fine"...
Have you looked at the pop on BYOND? We, Goon, and even _ERP servers_ have eclipsed /tg/station in playercount. I don't think they're doing fine, and even if they are, us having higher numbers means we're CLEARLY doing something better. Why try to be more like something less popular?

**Comment by TheBombMakerJL** [comment]
sKiLl iSsUe
Ya'know what we need, when chefs are already bad 75% of the time? 
More "skill", more complexity

This is a bad change, should have been test merged, is not a right fit for Yogs

**Comment by ToasterBiome** [comment]
> You say "TG does fine"... Have you looked at the pop on BYOND? We, Goon, and even _ERP servers_ have eclipsed /tg/station in playercount. I don't think they're doing fine, and even if they are, us having higher numbers means we're CLEARLY doing something better. Why try to be more like something less popular?

Yogs cooking is a holdover from primitive SS13, we've had some advances like the crafting menu, but functionally it's still ridiculously simple to make even the best things in the game. This adds more compexity to keep the job _interesting_, and tg does it in a sufficient way that it does add another dimension to it. If you're a terrible chef in the game, don't use the griddle. You don't get to get ridiculously good food if you don't want to put in the effort nor is your attention span can't handle clicking on some brown meat.

Also tg manuel has comparable numbers to us at this moment (70 vs 68 pop) and tg sybil is not far behind with 56. They're doing just fine with more complex cooking. Stop being babies and cook the damn patties.

**Comment by Cartlord** [comment]
I also want to point out: we already, actually, HAVE something that functions pretty-much exactly like these griddles and works on every food type.
You can make a bonfire and add metal rods to make a primitive grill, which you can apply raw food to and the fire will then (after some time) turn it into its cooked state. Leaving it on the fire will result in a burned mess, if memory serves.
Your PR adds a high-tech version of something we have a low-tech version of already, and your high-tech version is _worse_ than the low-tech version.

**Comment by ToasterBiome** [comment]
> I also want to point out: we already, actually, HAVE something that functions pretty-much exactly like these griddles and works on every food type. You can make a bonfire and add metal rods to make a primitive grill, which you can apply raw food to and the fire will then (after some time) turn it into its cooked state. Leaving it on the fire will result in a burned mess, if memory serves. Your PR adds a high-tech version of something we have a low-tech version of already, and your high-tech version is _worse_ than the low-tech version.

then cook with the low-tech version if you think it's worse

**Comment by Cartlord** [comment]
Alright, I'll make a point of making bonfires outside Botany until this gets reverted

**Pull request merged**
