### PR TITLE
MASSIVE BUFF TO ASH DRAKE

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
tweak: ash drakes now actually speak draconic
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Good we can now use ashdrakes to translate the savage gibberish of lizards

**Comment by SomeguyManperson** [comment]
this might be too basic to effect shapeshifted drakes but I'll pretend that's intended until I work around language to do that

**Comment by jcatjmeow** [comment]
I'm not sure this works. Have you tested it?
I'll boot up DM and test this shortly

**Review by jcatjmeow — APPROVED** [review]
Tested.
It works. Note that in order to switch languages you have to do it via the IC menu, maybe add it as an action button? Idk. But it works as intended

**Comment by jcatjmeow** [comment]
@SomeguyManperson 
Also note: Draconic is not the default language. Not known if that's intentional

**Comment by SomeguyManperson** [comment]
it's intentional you can use ,o to speak it without using the language menu

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
