### PR TITLE
Possible donor race draft

### PR DESCRIPTION
**Pull request by nesisknesis**
The two I had conceptualized is a Shade race or 'Insectoid' race.

The shade is a ghost and spooky wow great, catch is has no arms or legs, floats, picks up items through a magic bubble sprite where the hand would be. customization would be a mask to hide their barren faces and cloaks to hide their spooky rib cages.

Shade:
image
with cloak:
image
thought the no hands and legs would be a bit tricky but passable however my real problem is balancing along side making it an actual ghost. probably a bad idea to continue

Second idea was an 'Insectoid' race. Discovered hollow knight art and thought it was the best thing ive ever seen so took inspiration from that.

wanted them to be psionic because thats cool to have. can toggle a floating animation in where their arms move behind their backs and instead pick up items using a magic sprite placed where the hand would be to create the illusion of psionic powers. purely cosmetic.

ability is that they crawl faster than the average person. their insect legs allow them to do so because theyre space insects. would be a different animation where i might animate it if possible since its probably easier than the human sprite.

they like sugary foods like ants. cant wear any clothing except bags because humans are aliens and aliens dont bond well with aliens as you might expect. however they can utilise pockets and other features without a jumpsuit because playability. exotic blood type 'X' for Xeno because aliens. cant use guns because aliens(though faster crawling will increase their dodging ability). dont smell becuase  no sweat glands. and they have digi feet because look at the sprite

this means they cant go into space but maybe ill just ask a code wizard to help me make it so they can possess hardsuits using psionics and control their slave in a short enough range to set up a singularity.
guess psionics arent as purely cosmetic now but at least they can go into space within a short range.

nothing too powerful like rad immunity or cold immunity like other races, but a faster crawl and psionic feature that has not yet decided whether is PURELY cosmetic or can have cool functions like hardsuit possession. 

drawbacks are exotic blood, absolutely no clothing (no armor, protective suits. damn ayys), no guns. 

imo nothing thatll be pAy2WiN or i payed and got [insert stupid drawback]?, clothing can be made up in cosmetic options, ie masks because hollow knight does that and thats cool 😎 or cloaks (hollow knight does that too and xcomm for their psionic enemies)

if you think im spewing shit out my keyboard then tell me to fuck off and ill come up with something else in like a year or so
First concept:
image
(ripped from the ref tbh)
spiced up:
image
happy with this one:
image
greyscale:
image
reference: (context nothing to do with the race except maybe it does)
image
simplified reference because i like it, look how cool it looks, i think its good art and therefore i took it as inspiration: (the text says: "Bravo, my friend, you're a fast learner!"
image
this draft will be closed in like 3 days or so since its for the council to look at, tell me im a sick fuck, then scrap the idea
:cl:  
experimental: probably more effort than its worth trying to pitch
/:cl:

### CODE REVIEW

**Comment by Smudged** [comment]
I'm still personally hesitant on the whole Donor race prospect.

I'm abouuut neutral, I just don't like the idea of pay-to-play.

**Comment by drderp3635** [comment]
Snails are the first priority donor race dumbass

**Comment by Moja10** [comment]
I don't like the appearances of these races and I think it's complete nonsense for literal ghosts to be working on a space station. I mean I get the appearance of plasmamen might be considered similar, but this is just pushing it too far for me.

**Comment by Smudged** [comment]
The ant/hornet race looks cool as hell doe

**Comment by HomocidlePancakes** [comment]
We are reaching snoflake levels that shouldn't even be possible...
But seriously. Ghosts? Moths 2.0.? They look cool but feel a tad bit out of place.

**Pull request closed without merging**
