### PR TITLE
Adds huge scrubbers to miner/meta Whiteship

### PR DESCRIPTION
**Pull request by ghost**
Adds a huge scrubber to clean out miasma.

### Intent of your Pull Request
Since the miasma PR, cleaning out the stuff is nearly hard without the proper equipment on these shuttles, which don't have any.

#### Changelog

:cl:  
rscadd: Added huge scrubbers to whiteship  

/:cl:

### CODE REVIEW

**Comment by Ktlwjec** [comment]
Needs mapmerge + meta shuttle copying to yogs folder

**Comment by ghost** [comment]
I don't even know where the mapmerge button is.

**Comment by Moja10** [comment]
Believe in yourself!!

**Comment by Altoids1** [comment]
I'll do this my damned self if you don't wanna

**Pull request closed without merging**
