### PR TITLE
Allows photogeists to plant bushes and flowers

### PR DESCRIPTION
**Pull request by Marmio64**
Kudzu sect photogeists can now plant bushes and flowers into the floor with a 20 second cooldown. They are purely decorative but might make photogeists ever so slightly more fun other than praying to god that there are some podpeople/wood golems so that you have a small fragment of purpose.

# Changelog

:cl:  
rscadd: Allows photogeists to plant bushes and flowers.
/:cl:

### CODE REVIEW

**Review by nesisknesis — APPROVED** [review]
plant

**Comment by bruhlookatthisdood** [comment]
can they convert tiles into grass?
please?

**Comment by Marmio64** [comment]
> can they convert tiles into grass? please?

i was going to, but humans can already do that and i dont feel like wasting time trying to make sure it cant be abused (sealing space tiles with grass, fixing atmos in rooms, fucking up lavaland atmosphere)

**Comment by bruhlookatthisdood** [comment]
> 

seems like we should deploy them to lavaland.

**Pull request merged**
