### PR TITLE
No more wearable collars

### PR DESCRIPTION
**Pull request by LoliconSlayer**
# Document the changes in your pull request
Pet collars are for PETS leave your petplay fetish out of this

# Why is this good for the game?
Less weirdos is good for the game

# Testing
Absolutely none, I did this in webedit.

# Wiki Documentation
I hope to god we don't have wearable collars mentioned on the wiki.

# Changelog
:cl:  
rscdel: Pet collars are for actual pets
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
bai denied my one...

**Comment by Therandomhoboo** [comment]
"It's too hard for me to ignore people wearing collars, can we nerf wearable collars so I can have an easier time saying everything is less fetish now"

**Comment by ToasterBiome** [comment]
Second verse same as the first , see reason here: 

https://github.com/yogstation13/Yogstation/pull/19495

`don't like this precedent of astroturfing the entire game cause furries cant keep it in their pants`

Nothing new has been added to the argument

**Comment by Therandomhoboo** [comment]
> "It's too hard for me to ignore people wearing collars, can we nerf wearable collars so I can have an easier time saying everything is less fetish now"

Morder not understanding the joke. Oof

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
> `don't like this precedent of astroturfing the entire game cause furries cant keep it in their pants`

there is no world where WEARING A PET COLLAR isn't gonna cause weird fetish ideas
you can't give people things that are exclusively made to be weird, and be annoyed when they're weird about it.

**Review by JohnFulpWillard — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
What does this item provide to the game anyways that outweighs the negative

**Comment by MajManatee** [comment]
really no reason for this to exist except for people projecting their fetishes

**Comment by azzzertyy** [comment]
bruh where were all you when i made my pr man

**Comment by JohnFulpWillard** [comment]
Not here

**Comment by Darkstick** [comment]
this would ruin some of my hard work on this code ;-;
also no testing seems like a bad idea. Kneejerk PRs are shit and end up spaghettifying the code even more than it should.
See: ratvar burning heretics once he's summoned

**Comment by azzzertyy** [comment]
> this would ruin some of my hard work on this code ;-; also no testing seems like a bad idea. Kneejerk PRs are shit and end up spaghettifying the code even more than it should. See: ratvar burning heretics once he's summoned

this doesnt need testing its a one line change, i can tell you now it works

**Review by MajManatee — APPROVED** [review]

**Comment by Hopekz** [comment]
> bruh where were all you when i made my pr man

Your attempt was trash all you wrote was "gross".
Next time if you want a change to go through you should do the bare minimum and make it not look like a low effort meme PR

**Comment by adamsong** [comment]
Y'all got so tied up in your crusade your merged bad code lol

**Pull request merged**
