### PR TITLE
Security Lethal Melee: Vibration Blade

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Retractable vibration blades (Normal sized when retracted, bulky when out)

Stats inspired by combat knife

No block chance

3 start in armory and they can be printed once hardlight tech is researched

Glows slightly in the dark

# Spriting

New handle-only sprites made for retracted form

# Wiki Documentation

23 damage
10 wound bonus
10 throw damage
25 armor penetration

# Changelog

:cl:  
rscadd: Added vibration blades to the armory
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Ah yes the printable superior combat knives

**Comment by MajManatee** [comment]
I didn't know how badly I wanted to fight people with swords until now.

**Comment by ynot01** [comment]
> Ah yes the printable superior combat knives

These don't embed like combat knives (if you could print them and throw them for good damage people would just spam them out) and also yes a sword should be better than a knife, bit silly for the knives to be armory locked in the first place

They also don't fit in boots like knives which I found to be surprisingly useful a couple rounds ago

**Comment by MajManatee** [comment]
Can they be made recolourable akin to an esword? or is that out of scope.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
why do sec get backpack esword airlock busters especially since they can be mass printed at no cost (and you get three for free anyways)

**Comment by ynot01** [comment]
> why do sec get backpack esword airlock busters 

takes 30 hits to break an airlock with this (i counted)

> especially since they can be mass printed at no cost (and you get three for free anyways)

breaching shotguns are normal sized and break airlocks in 0.8 seconds and you can print rounds for that and keep boxes of those rounds in your belt

**Comment by MajManatee** [comment]
What mapping software do you use that removes readability?? Removing like a billion spaces from random bits of code.

**Comment by patpol4** [comment]
Will we get sued if we call it vibroblade

**Comment by ynot01** [comment]
> Will we get sued if we call it vibroblade

It's not a vibroblade

> What mapping software do you use that removes readability?? Removing like a billion spaces from random bits of code.

[StrongDMM](https://github.com/SpaiR/StrongDMM)

**Comment by MajManatee** [comment]
mf doesnt even use fast2dmm that monster made smh

**Comment by 00ze-cyclone** [comment]
> > Ah yes the printable superior combat knives
> 
> These don't embed like combat knives (if you could print them and throw them for good damage people would just spam them out) and also yes a sword should be better than a knife, bit silly for the knives to be armory locked in the first place
> 
> They also don't fit in boots like knives which I found to be surprisingly useful a couple rounds ago

Oh yeah sorry totally isn't better because it's less effective at range (where sec already has 36293424 options to kill you).
Yeah the sword should be better than a knife, however since when do we need something better than the knife other than powercreep?

**Comment by ynot01** [comment]
> however since when do we need something better than the knife other than powercreep?

combat knives arent real (cargo locked) and many people have been begging for a lethal melee option

if i was lazier i would just put combat knives in the armory (people have suggested this in the past)

**Comment by 00ze-cyclone** [comment]
> > however since when do we need something better than the knife other than powercreep?
> 
> combat knives arent real (cargo locked) and many people have been begging for a lethal melee option
> 
> if i was lazier i would just put combat knives in the armory (people have suggested this in the past)

« Many people » (you)

**Comment by CMOisLing** [comment]
Can we refer to them as vibrators for short?

**Comment by MajManatee** [comment]
Will there be a unique sound effect, or are you settled on the normal sword sound

**Comment by ynot01** [comment]
> Will there be a unique sound effect, or are you settled on the normal sword sound

It could use a funny sound but I don't know of any that would fit and I'm not making them sound like energy swords

**Comment by Marmio64** [comment]
should be normal sized when retracted, to further enforce that these are supposed to be bigger better combat knives and to make combat knives more distinct (if you really need space but also want a secondary melee weapon: combat knife.)

**Comment by ynot01** [comment]
> should be normal sized when retracted

This is possible

**Comment by TheBombMakerJL** [comment]
Why not add combat knives to the armory and lock this behind hardlight tech? Combat knives don't get enough action anyways and this just being a better version of the combat knife & in the armory roundstart means combat knives will see even less if any station action

It feels like the sprite for the blade clashes with the typical security theme, seems out of place. It looks like something security /should not/ be using, nothing about it screams "security" to me imo

**Comment by ynot01** [comment]
> Why not add combat knives to the armory and lock this behind hardlight tech? Combat knives don't get enough action anyways and this just being a better version of the combat knife

Combat knives are fucking ugly and bad and have gamer throws/embeds

**Comment by ynot01** [comment]
Made normal sized

**Comment by Rdrazga** [comment]
Personal thoughts:
-this has a lot of positives and no real negatives.
IE: this has around 30 on the wound roll, and has AP, and does good damage, and is foldable.
   -most items that have good AP often have less wound, and vice versa so that you are not causing constant bleeding with already robust items
-Does this roll against energy armor to stay consistent with other hardlight stuff? And if it does you can give it negative AP to compensate for normally low energy armor.

**Comment by Rdrazga** [comment]
Also where my syndie version that is better so I can have cool looking sword that isn’t esword

**Comment by ynot01** [comment]
the syndie version that is better IS the esword bozo

**Comment by Moja10** [comment]
Personally I don't think a sec officer's melee damage should be more than harmbaton's damage unless they go get a combat knife. I never looked at sec balance and was like "if only they could execute people in melee more easily". In fact the opposite, I think they have plenty of ways to execute people already especially if they are getting shit out of the armory, and melee damage doesn't matter if they are able to disable or stun the person who needs to be lethaled in any way.

**Comment by Moltijoe** [comment]
> No block chance

give it block chance, but only against mechs and mech weapons

**Comment by cuackles** [comment]
( not an art review comment ) kinda iffy on them from a logic standpoint as in, i don't see a company giving their security force swords, feel like they would either fit better as foldable knifes like a combat knife and and NT produced or a solid baton like the det ones but bigger and harder hitting 
 ( bit of an art review) i agree with bombmaker that they don't really feel like sec equipment, i would be more inclined for a contractor baton slightly redesigned to be bladed and more sec like

**Comment by MajManatee** [comment]
something like this would allow for an antag that has major resistances to any form of ranged damage, and force melee combat, which would be dope as hell

**Comment by Moja10** [comment]
does sec really have to have every tool possible to murder every possibility of danger on the station? does this gap REALLY need to get filled?

if anything IMO this should be cargo crate only

**Comment by MajManatee** [comment]
If its cargo only then its in the exact same spot as the combat knife and never used ever

**Review by MajManatee — APPROVED** [review]
codewise its fine

**Review by patpol4 — APPROVED** [review]
map fine it just adds the blades to armories

**Comment by JamieD1** [comment]
Balance council

**Comment by MajManatee** [comment]
balance council seems in favour, @ynot01 map conflicts

**Comment by ynot01** [comment]
Cornflakes resolved

**Review by ToasterBiome — APPROVED** [review]
Sprites don't much fit the sec style, but if someone wants to touch them up in the future they're free to. I see no reason to hold it.

**Comment by ynot01** [comment]
self merge time

**Pull request merged**
