### PR TITLE
Removes do_atom, do_after_mob and do_mob (also interaction key stuff)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

Removes ``do_atom``, ``do_after_mob`` and ``do_mob``, merging it all into ``do_after``.
Also adds interaction keys, so people can (generally) no longer stack multiple progress bars on stuff

This helps massively in maintainability, as these 4 things are all copy pastes of eachother, and there's not much reason to keep them all around when they all essentially do the same thing.
It also makes adding new instances of it way easier.

### What is a do_after

Nearly anything in-game that uses progress bars (like surgery) used to be stackable.
With interaction keys, you can only do one interaction on a thing at a time. Example; this removes being able to do surgery on multiple limbs at once.

# Wiki Documentation

You can no longer stack do afters, if that's a thing in surgery or something.

# Changelog

:cl: JohnFulpWillard & Mothblocks
bugfix: Removes being able to stack do_afters on things (like surgery on several limbs on the same person).
rscdel: Removed do_mob, do_after_mob and do_atom.
tweak: You now do CPR faster after the first attempt.
/:cl:

### CODE REVIEW

**Comment by TaelynTheLost** [comment]
Stacking actions is extremely important to medical.  CPR for example, is near useless since it's like 4 times slower than before.   It ruins the tempo, and it used to have the perfect tempo of real CPR.  I don't see why you would even need to remove it.  Chaining actions allowed you to keep a continuous flow, even when the server has a lag spike.  A flow, that for med, can mean life or  death.

**Comment by athena413** [comment]
can you add an exception for advanced roasting stick. stacking 1287037819 actions to make a supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled supermatter-grilled sausage is funny and i want it

**Comment by JohnFulpWillard** [comment]
😦

**Comment by iloveloopers** [comment]
LET ME WALK AND EAT AT THE SAME TIME

**Comment by Yarinoi** [comment]
awful pr

i cant wait for it to take 5x10^28 years for me to cpr away the oxygen damage of someone i just defibbed
i cant wait for secoffs to have to spend an eternity having to strip one guy

this may help coders in some way but its awful for the people who actually play the game. surely theres a way of doing whatever you wanted to do without this shit.

**Comment by JohnFulpWillard** [comment]
Idk if you're still just playing on the first commit or what but both those things were addressed

**Comment by Yarinoi** [comment]
> Idk if you're still just playing on the first commit or what but both those things were addressed

oh


nice

**Comment by iloveloopers** [comment]
You can't draw bows while moving. Pretty sure you could draw bows while moving before

**Comment by JohnFulpWillard** [comment]
Bows fixed, i read the code wrong and accidentally swapped it backwards.

**Comment by Mqiib** [comment]
Horror soul suck gets cancelled when the host moves which makes it half impossible to do your objective. It's not supposed to be cancelled.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
