### PR TITLE
substantially decreases the amount of plasma present on the burn test holodeck program

### PR DESCRIPTION
**Pull request by SomeguyManperson**
it is still quite a lot of burning the effect of one holodeck activation is however not as capable of covering the whole station
probably
#### Changelog

:cl:  
tweak: burn test program for holodeck now contains substantially less burn
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
Speedmerge

**Comment by Darkstick** [comment]
Just flat out remove it

**Review by fluffe9911 — APPROVED** [review]
what a progamer moment

**Comment by MegaEmpirical** [comment]
Fucking yes, this was insane.

**Pull request merged**
