### PR TITLE
Removes mining medic

### PR DESCRIPTION
**Pull request by ghost**
If we're rebasing to citadel might as well throw this one in there too

Mining medic is the world's most useless role and exists for gamers who want to rush megafauna and ruins without any obligation to collect ores

This change will be more significant than the last rebase and the MRP changes

### CODE REVIEW

**Comment by Cartlord** [comment]
On the one hand I don't want this because one of the best RPers I know runs Mining Medic very often and they do an EXCELLENT job with the role, on the other hand I also personally saw a Mining Medic rush into a Legion Barracks ruin and die like a bitch a day or two ago.

**Comment by ghost** [comment]
> On the one hand I don't want this because one of the best RPers I know runs Mining Medic very often and they do an EXCELLENT job with the role, on the other hand I also personally saw a Mining Medic rush into a Legion Barracks ruin and die like a bitch a day or two ago.

See this is a perfect example of why they need to be eliminated as they die like little bitches and are in dchat before the antag rolling assistant is

**Comment by UselessTheremin** [comment]
lmao ronan you chad you made this on your master branch

**Comment by ghost** [comment]
> lmao ronan you chad you made this on your master branch

I don’t even know what that means

**Comment by Marmio64** [comment]
council should make a quickfire vote for this. They did one for psych, and psych is arguably far less important and more useless. Also are you going to keep the mining medic locker, their spawns, and all that? I believe all you changed in the code was the removal of their job and nothing else.

**Comment by Cartlord** [comment]
Why closed...?

**Comment by Cartlord** [comment]
Been thinking, and I honestly think this is a good change. Fer one thing, a Mining Medic's sleeper will NEVER be upgraded, because nobody upgrades the mining base; secondly, the mining medic's got basically nothing to do for a GRAND majority of the shift, because a lot of Miners just don't get seriously injured; thirdly, the Mining Medic seems to mostly lack the stuff necessary to deal with lavaland mobs, which is an issue if someone was actually KILLED by one and the mob's still at the body - and due to this, they (in my experience) often just end up taking blood samples and podcloning people with Replica Pod seeds taken from Hydroponics - and if you're just podding people, IMO that's a Botanist's job.

**Pull request closed without merging**
