### PR TITLE
Redesigns a good chunk of charliestation

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

## Reasoning
The station has weird design issues (See RnD, Engineering, and Kitchen)
I've been asked to add some food since its painful to get it
This is supposed to be _new player_ friendly
Not the most fun gameplay wise

Changes:
 - Engineering
    - SMES Storage
    - Tool Storage 
    - A small amount of materials added
    - Added smart foam grenades
    - Put voidsuit in a suit storage unit
 - Kitchen/Eating Area
    - Seperated
    - Added a fridge
    - Added food
    - Added oven
 - Hydroponics
    - Replaced soil with trays (Mostly for gameplay, would use the old sprites but they dont work)
    - Add seed and nutrient vendor
 - Security
    - Added a cell
    - Added a armory
    - Added some tables
 - R&D
    - Redesigned
    - Removed bottles infavor of chem lab for gameplay
    - Added break lounge
    - Added a _proper_ surgery room
    - Makes the room feel less spacious
 - Other
    - Added some more wires on solar array
    - Added sandbags
    - Added some barricades to delta side
    - Removed access requirements on delta doors (what?)
    - Added some windows on the mining bridge

Images:
image
image
image
image
image

# Wiki Documentation

Update Map

# Changelog
:cl:  
tweak: Redesigned charlie station
/:cl:

### CODE REVIEW

**Comment by GraveHat** [comment]
Charlie station looks much more habitable now, the only minor gripe I have is the sec windows. They should be done the same way as the science operating room windows as I think that would look better instead of having 3 separate windows next to each other.

**Comment by redmoogle** [comment]
> Charlie station looks much more habitable now, the only minor gripe I have is the sec windows. They should be done the same way as the science operating room windows as I think that would look better instead of having 3 separate windows next to each other.

yeah I fixed that. I put them down so I could focus on other design

**Comment by ToasterBiome** [comment]
does all that stuff come in the rd lab?

**Comment by redmoogle** [comment]
> does all that stuff come in the rd lab?

Erm what?

**Comment by ToasterBiome** [comment]
> > does all that stuff come in the rd lab?
> 
> Erm what?

yes it does, thanks

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
