### PR TITLE
Fixes Ai wanted status HUD - Issue #4064

### LINKED ISSUE #4064: AI can no longer see arrest status
Exactly as the title says, I just can't see them at all as an AI. I think borgs are okay.

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Fixes #4064

#### Changelog

:cl:   
bugfix: Fixes AI Sec HUD  
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
good

**Comment by HomocidlePancakes** [comment]
Not a bug for the same reason as to why it can’t see implants. AI is literally omnipotent and people already play it like a cop. Don’t encourage it even further. If you want it go after someone, order it so.

**Comment by MegaEmpirical** [comment]
This will assist with the enforcement of space law, your cooperation is greatly appreciated.

**Comment by HomocidlePancakes** [comment]
*nom* *nom* ugh this security cock tastes **SP GOOD**! I am a 10 braincell AI validhunter I can’t stop sucking it.

**Comment by Hopekz** [comment]
I like that it shows wanted status.
That part is alright.

I do not like how the AI can now see who is mindshielded.
That part is what effects balancing on this PR.

**Comment by maxion12345** [comment]
Honestly, is this even an issue anymore? I think it keeps the "muh valid" aspect of playing AI on the downlow, if such a thing is even possible lmao

**Pull request merged**
