### PR TITLE
removes thermal vision from genetics unlockable powers because it's basically just xray

### PR DESCRIPTION
**Pull request by ghost**
might as well get this in before i finish up the cybernetics pr 

i'm going back to making dinner now

:cl:  
rscdel: you can't get thermals in genetics anymore
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Good PR, should have went with Moja's x-ray removal in my opinion.

**Comment by Moja10** [comment]
And again, thermals still exist, but only as medical implants you get from research  I believe.

**Comment by ghost** [comment]
or from certain antagonists like nightmares and shadowlings and xenomorphs eyes, which if you remove and implant them, give thermal vision

**Comment by Tipy1802** [comment]
Removing x Ray was fine but thermals is a bit too much in my opinion

**Comment by Ratvar** [comment]
Tipy, could you explain why it is too much - argumenting would help thermals stay ingame more then dislike emoji, and you probably want that

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
