### PR TITLE
Lets the bible go in the belt slot

### PR DESCRIPTION
**Pull request by Moltijoe**
It's annoying having to store it in my backpack constantly as a priest

:cl:  
tweak: Lets the bible go in the belt slot
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
love it, can you make it able to go in the exosuit slot of chaplain clothes (such as the monk robes) as well?

**Comment by Moltijoe** [comment]
> love it, can you make it able to go in the exosuit slot of chaplain clothes (such as the monk robes) as well?

it was, at least in the scholar clothing

**Comment by Moltijoe** [comment]
> love it, can you make it able to go in the exosuit slot of chaplain clothes (such as the monk robes) as well?

yeah, not gonna do this until after my tgui nullrod PR as it'll cause terrible conflicts

**Comment by Hislyna** [comment]
I no longer have to ~~steal~~ beg the curator for their spare book bag

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
