### PR TITLE
TG UPDATE (More then 4 Days Edition)

### PR DESCRIPTION
**Pull request by JamieD1**
TBD

:cl:  
rscadd: TBD
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
I have no idea what any of this is but I'm glad you're doing it jamie!

**Comment by cuackles** [comment]
Fuck that's a lot of files

**Comment by Xoxeyos** [comment]
thanks for all the hard work Jamie!

**Comment by MajManatee** [comment]
really hoping this includes the typescript update they did. that would be poggers.

**Comment by ghost** [comment]
Sex

**Comment by LemonInTheDark** [comment]
Hey jamie if you're going to port our/my code, could you please credit the prs you're porting from?
Noticed you did in the garbage subsystem pr, thanks for that.

**Comment by Bibby0110** [comment]
> Hey jamie if you're going to port our/my code, could you please credit the prs you're porting from? Noticed you did in the garbage subsystem pr, thanks for that.

based

**Comment by JamieD1** [comment]
> Hey jamie if you're going to port our/my code, could you please credit the prs you're porting from? Noticed you did in the garbage subsystem pr, thanks for that.

Yep, as the list keeps growing im going to through everything I added at the end and make a massive list of the ports, dont worry I will credit and mention all the people involved, the issue is our code is so old and outdated the list keeps going hence the TBD.

**Comment by Bibby0110** [comment]
stale also lots of conflicts

**Comment by JamieD1** [comment]
Ah fuck it, might as well start again..

**Pull request closed without merging**
