### PR TITLE
Replaces some consoles with modular computer consoles

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Added more mod console presets, replaces some normal consoles with them, and adds them in a few places:

- Security: Comes with Secureye
- Tcomms: Comes with NTNet Diagnostics and Monitoring and NTnet Chat Client
- Cargo: Comes with Bounty Board
- QM: Comes with Bounty Board and OverWatch
- Mining: Comes with OverWatch
- HoP: Comes with ID Card Modification, Chat Client, Job Manager, Crew Manifest, Bounty Board, and OverWatch
- HoS: Comes with ID Card Modification Chat Client, and Secureye
- CE: Comes with ID Card Modification Chat Client, Power Monitor, Alarm Monitor, Supermatter Monitor, and Energy Harvester Controler
- RD: Comes with ID Card Modification, Chat Client, NTNet Diagnostics and Monitoring, AI Integrity Restorer, and Bot Remote Controller
- CMO: Comes with ID Card Modification and Chat Client

# Wiki Documentation

Images will need to be updated. 

# Changelog

:cl:  
tweak: Replaced some normal consoles with modular ones
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
> RD: Comes with ID Card Modification, Chat Client, NTNet Diagnostics and Monitoring, AI Integrity Restorer, and Bot Remote Controller

Didn't the RD already get one?

**Comment by patpol4** [comment]
ugh how am i supposed to review this

**Comment by nmajask** [comment]
> Didn't the RD already get one?

Yes they did, but it was done in a weird way. The RD's console was just console/preset/research, but what I ended up doing is making all of the head's consoles subtypes of console/preset/command, so i just made a new type path for the RD's console, that being console/preset/command/rd. It still has all of the same programs on it, but also includes the ID mod program as it is now replacing the department console. As for console/preset/research, that is being used as a console for robotics, currently only having the bot command program.

> ugh how am i supposed to review this

For every map I replaced the department management console with the new command presets, added a research preset to robotics, added a cargo preset to the cargo office, added a qm preset to the qm's office, replaced the outpost cams with the mining preset, added a tcomms preset to tcomms, replaced the card console at arrivals and in the caps office with command presets, replaced a few of the consoles in the bridge if there are mod console alternatives (mainly the outpost cams) and replaced the security cams with a security preset in the warden's office and the brig phys office if it has one.

**Review by patpol4 — APPROVED** [review]
Good

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
