### PR TITLE
[YOGSTATION] [99% LAG FREE] Biggest Blackest Medbay edition 3.141592 (we merge the right one edition)

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

haters won bro.. it's jover

image

ive readded surgery so CMO can metagame your brainwashing gimmick (go directly to perma)

# Wiki Documentation

box medbay looks like this
image

# Changelog

:cl:  ToasterBiome, Skrem7
mapping: box has private surgery again
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
> Biggest blackest medbay
> Not black

**Comment by ktlwjec0** [comment]
yeah much better than the one you accidentally merged. I will say though shit like the more public surgery table+computer should be stuff engineers have to build - it shouldn't be made perfect from roundstart in regards to things like that. But it's so much nicer than the current one I will beg for a speedmerge anyway

**Comment by ynot01** [comment]
> # Wiki Documentation
> box medbay looks like this image

where is cloning

**Review by Aquizit — CHANGES_REQUESTED** [review]
image

Camera getting showered on again.


image

This surgery bag should probably be in the surgery room (which currently does not have a surgery bag).


image

Missing firelocks. Firelock placement under windows doesn't seem terribly consistent across station, but in the Treatment Room they all have them so I just figure this one should too.

**Comment by Moja10** [comment]
Needs a syringe gun in medical storage

**Comment by ToasterBiome** [comment]
> 

1. done
2. encouraging doctors to use that area instead
3. done

**Review by Aquizit — APPROVED** [review]

**Pull request merged**
