### PR TITLE
You can now convert mindshielded people into vampires

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request
Turns out mindshields prevent you from being turned into a vampire but it still uses up blood anyway cause bad coding so rather then fix that cause im lazy im just gonna make it so you can convert mindshielded people cause a mindshield preventing you from being turned into a vampire is stupid and dumb.
:cl:  
tweak: Mindshielded people can now be turned into vampires
/:cl:

### CODE REVIEW

**Comment by overlord12345** [comment]
vampire cap bad

**Comment by fluffe9911** [comment]
vampire cap good

**Comment by maxion12345** [comment]
>So you know how some heads can spawn as vamps?

>Lets do that, but now vamps can turn security and head of security, the people that are trustworthy, into antags aswell.

**Comment by fluffe9911** [comment]
trust no one not even yourself

**Comment by boodaliboo** [comment]
i feel like this is fine because vampire converts cost 500 blood and take a minute and if they move the bloods still wasted

**Comment by Marmio64** [comment]
its not much different from a ling absorbing cap and now becoming captain, someone who is supposed to be trustworthy. The ling cap can always just get a new mindshield secretly.

**Comment by Jarod1200** [comment]
Liliths pact is supposed to use up the blood even if it fails I'm pretty sure. Gotta be sure you actually want to use it before you do

**Comment by Hopekz** [comment]
This PR makes sense because it is consistent with what mindshields represent.
If we want to make restrictions on whether sec get converted that should probably be done in another way.

Also; let's not forget that vampire rounds can now happen after a conversion antag failed meaning there is a change for everyone to be mindshielded

**Comment by JamieD1** [comment]
Player view: This is stupid, we should not have captain vamps.

Code View: Looks good.

**Review by JamieD1 — APPROVED** [review]

**Comment by Featherfield** [comment]
I was in for a round where HoS was a vampire and nobody knew and literally all of sec ended up dead from the big succ fuck that

**Comment by alexkar598** [comment]
Yeah no, I dont want vamp hos

**Pull request closed without merging**
