### PR TITLE
Ynot has no idea how strong explosions are

### PR DESCRIPTION
**Pull request by Mqiib**
Returns the PDA bomber thing to just a light explosion instead of a heavy explosion (which kills you and deletes most of your equipment)

# Changelog

:cl:  
 
tweak: PDA bomber is no longer a free kill

/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
Mr maintainer slap the i ded label on this pr right now

**Comment by Maia-J** [comment]
How about instead of that we make it cost more?

**Comment by Mqiib** [comment]
> How about instead of that we make it cost more?

no
You suggesting this means you don't understand WHY this is a bad thing. it's bad because currently it's a way to nuke from orbit someone and almost all of their equipment without putting yourself at risk AT ALL. There's no tracing it, there's no reacting to it, and there are pretty solid odds you'll just straight up die. it's like "What if esword but instead of being a melee weapon it was infinite range, you didn't need to see the target, it destroyed almost all of their equipment, it hard stunned them with a good chance to delimb, and it did 120 damage but oh no it only has 4 uses!!!"

**Comment by 00ze-cyclone** [comment]
It has the ided label, we are required to merge it now.

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
