### PR TITLE
Minsky 2.0 - For Use and Abuse I - DO NOT MERGE

### PR DESCRIPTION
**Pull request by MayhemSailor**
### **THIS IS A WORK IN PROGRESS**

Since you autist's have been looking for a chance to gripe and complain about new minsky, feel free to take a gander and provide your feedback.

The map can be found at /maps/yogstation/map_files/minskystation/wip

Map can be viewed here: https://mdb.affectedarc07.co.uk/Files/120966336/249116440/0/after.png (AI Chamber commit).

**Areas through first pass:**
- AI
- Atmospherics
- Bridge
- Cargo
- Chapel
- Engineering
- Hydroponics
- Library
- Medical
- Mining
- Science
- Security
- Telecommunications

**Areas awaiting first pass:**
- Maintenance
- Near Station
- Public Hallways

Please note that feedback regarding areas that have yet to undergo first pass is pretty much _pointless_.

**Systems installed:**
- Pipenet
- Powernet

**Systems yet to be installed:**
- Cameranet
- Disposal Piping
- Intercomms
- Bot Nav Net
#### Changelog

:cl:  
rscadd: adds WIP Minsky 2.0
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
https://mdb.affectedarc07.co.uk/Files/120966336/248587739/0/after.png

alternatively just look at the image.

**Comment by MonsWTF** [comment]
First thing I was focusing on and came to mind: maintenance tunnels look a little too clean. There is no wasted space that gives maintenance the room/obfuscation required for "unsavory activities" to occur, such as Dawkspawn/Blood Cult/Traitey hidey-hole. There's a lot of straight paths with only a few obvious bends, even the piping demonstrates this. Almost Every non-path has some door connected to it. On top of this, several parts of maint are multiple-blocks wide. Even if it's a big station, the back areas should feel more 'claustrophobic' than the hallways.

There was at least one spot that did this, and it's directly north of Tech Storage on the starboard side, but I don't think one hollow room will cut it.
image

**Comment by MayhemSailor** [comment]
> 
> 
> First thing I was focusing on and came to mind: maintenance tunnels look a little too clean. There is no wasted space that gives maintenance the room/obfuscation required for "unsavory activities" to occur, such as Dawkspawn/Blood Cult/Traitey hidey-hole. There's a lot of straight paths with only a few obvious bends, even the piping demonstrates this. Almost Every non-path has some door connected to it. On top of this, several parts of maint are multiple-blocks wide. Even if it's a big station, the back areas should feel more 'claustrophobic' than the hallways.
> 
> There was at least one spot that did this, and it's directly north of Tech Storage on the starboard side, but I don't think one hollow room will cut it.
> image

Maintenance will not be cavernous, even once it is through first pass (please read updated OP). These antags will need to learn to deal with that.

**Comment by MayhemSailor** [comment]
Use and Abuse I is now closed. Expect Use and Abuse II by mid October, 2019.

**Pull request closed without merging**
