### PR TITLE
Fixes #8856 - Snow golem sprites

### LINKED ISSUE #8856: Snow golem sprite bug
Issue reported from  Round ID: 29968 (Yogstation 13)

Reporting client version: 513.1525

There is a bug where the snow Golem sprite turns invisible if you use pride's mirror in Lavaland

### PR DESCRIPTION
**Pull request by jcatjmeow**
### Intent of your Pull Request
fixes #8856
Also deletes a duplicate icon
#### Changelog
:cl:  
bugfix: fixes snow golem sprites
/:cl:

### CODE REVIEW

**Comment by ToGWtF** [comment]
Good First PR

**Review by alexkar598 — DISMISSED** [review]
Lacks a fire closet

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Where is the cup?

**Comment by ToGWtF** [comment]
You filled the British Mug with Coffee. This is lore-breaking.

**Comment by boodaliboo** [comment]
image
?

**Comment by jcatjmeow** [comment]
> image
> ?

> Also deletes a duplicate icon

Learn to read, please :)

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
