### PR TITLE
Adds Granite to Lavaland

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

ss (2022-09-03 at 02 43 24)

adds Granite, orange stones that are hardness 3, to Lavaland. Granite has increased chances to spawn valuable ores (reduced for Iron), including magmite, but is itself not as common as Hardened Basalt. Granite ores also give just a little more ore per tile, to make it worth your time to mine them

# Why?
Well, we've got a lot of ways to just...1-shot hardened basalt right now, at hardness 2. This means there's still some rocks you can't just plough through as easy, but you will be rewarded for taking the time to do it.

# Wiki Documentation

*absolutely* needs to be documented on the mining page I think

# Changelog

:cl:  
rscadd: Adds Granite to Lavaland, a high-richness stone that is hardness 3!
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
explosion proof rock when

**Comment by SomeguyManperson** [comment]
clown borgs.......................................................................

**Comment by VaelophisNyx** [comment]
> explosion proof rock when

honestly if I knew how, I would, but would also blacklist magmite because that'd be a dick move

**Comment by redmoogle** [comment]
```
.../ex_act(severity, target)
 return
```

**Comment by VaelophisNyx** [comment]
I might use that in the future for some hardness 4 stone that can't be exploded, but thanks for the info!

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
no bananiym

**Comment by VaelophisNyx** [comment]
boo but alright

**Review by redmoogle — CHANGES_REQUESTED** [review]
title smh

**Review by ToasterBiome — APPROVED** [review]
fine enough

**Review by redmoogle — APPROVED** [review]

**Pull request merged**
