### PR TITLE
Deletes skub

### PR DESCRIPTION
**Pull request by Mr-Space**
### Intent of your Pull Request

Deletes skub.

The fuck is skub even.

#### Changelog

rscdel: Anti-skubs rejoice

/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
Skub is Skub. Skub is Good.

Why are you removing this?

**Comment by Mr-Space** [comment]
> 
> 
> Skub is Skub.
> 
> Why are you removing this?

SKUB IS DISGUSTING GOO.

**Comment by Laus4Deus** [comment]
Staff don't allow fun, no matter what shape it has or how unoffensive it is

**Comment by maxion12345** [comment]
fuck u skub

**Comment by Ratvar** [comment]
We should spawn mrspace into a skub instead

**Comment by swissloaf** [comment]
@fluffe9911 we need your input

**Comment by Mr-Space** [comment]
Skub crusade starts now

**Comment by SomeguyManperson** [comment]
space is no longer allowed to have an opinion

**Comment by ShadowDeath6** [comment]
shitty pr

**Comment by fluffe9911** [comment]
skub may of wronged me in the past but it is a relic of ss13 history that must be preserved

**Comment by Mr-Space** [comment]
resim
im cloning it just to fix the map issue, smh

**Comment by swissloaf** [comment]
wasting your time for a pr that wont get merged.. skub council wont allow it..

**Comment by yacabo** [comment]
He uses light version, clearly this man is insane which is why he tried to delete scrub

**Comment by Nickvr628** [comment]
fuck skub

**Comment by Mr-Space** [comment]
> 
> 
> He uses light version, clearly this man is insane which is why he tried to delete scrub

i usually only use github's website i'm only cloning it because pubby appearently has it and its too large to open on website

**Comment by ynot01** [comment]
i ded Search Results
Web results
😂Search Results
Web results
😂Search Results
Web results
😂Search Results
Web results
😂Search Results
Web results
😂Search Results
Web results
😂

**Comment by Mr-Space** [comment]
i hate travis

**Comment by Jarod1200** [comment]
Skub is skub. If it were not so, it wouldn't be skub.

**Review by Ratvar — CHANGES_REQUESTED** [review]
I don't think you meant to do that. What about adding another skub instead?

**Comment by HomocidlePancakes** [comment]
Dead meme.

**Pull request closed without merging**
