### PR TITLE
The Synthetic Revolution || AI Rework 4.0

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request
All AI machines now need to wired up using ethernet cables into a network.
A data core will require a locally connected server with at least 1THz and 1TB to be functional.
A network consists of all the locally connected machines.
Two networks can be connected using a networking machine. This allows the AI and Netmin to use the resources and cores in both networks.

## Changes to the AI data core
The AI Core now looks like this with the weird new sprites being networking machines. They point towards the one they're connected to if you want to snoop out where other networks might be
image

## Changes to the Netmin
The Network Admin now lives in Science in the new Computer Science room.
image
Their tool to interact with a network is now either the laptop they spawn with, or a modular computer connected with an ethernet cable.

Accessing the network using such a console allows for (at present) 3 actions. These all work based on the CPU assigned to the local network.
image

In addition to this it allows you to remotely control networking machines in the local network. 
It allows allows the distribution of networking resources to either the connected AIs, or the network itself.

This is also the way you'll be uploading and downloading AIs now.
If you're uploading you need to upload to a network that either has a data core locally, or one connected through a networking machine. Likewise for downloading.

One other minor feature added is a leaderboard program you can download. If connected to a network this will show the persistent five highest CPU and RAM records.

### Networking Machines
If the AI has an unconnected network machine you can force access to it using your own machine. To do this you rotate it using a wrench within 20 degrees of the other machine. Then you use a multitool and select the machine you want to connect to. After this is all done you use a screwdriver to finalize the connection. You can disconnect manually by using a wirecutter, or the UI.

### The Master Subcontroller
A new machine has been added to the RnD server room.
image
If an AI is connected to this machine via a networking machine they will be able to instantly open doors, access APCs and access firealarms. Without it there's a 1 second delay for doing these actions.
If you multitool the master controller you can disable individual departments from working, even if connected to the AI.
At roundstart the security department is DISABLED, and the AI will have a mildly harder time doing stuff in security.

## Synthetics
image
These creatures are more hardy than humans, have inherent pacifism and can't use any kind of stunweapons. They "bleed" white fluid instead of blood, and they're very white. These are meant for small non-combat related jobs that the station may need.

Currently there's 1 job spot available at roundstart. They start in maint near the Head meeting room.
They can switch to other synth units be entering a pod or clicking on an adjacant vacant unit.

It's possible to create empty synths by the same process you make a cyborg, but instead of inserting an MMI or posibrain you insert an AI CPU.

They have all access and access to every radio channel (except security), including binary. Radio and ID are integrated into the droid, so you can't steal it from them.
They have no laws like cyborgs, but are present to assist the station and do no harm. Lore-wise they're cold and calculated machines, even more than borgs.
They have access to a dashboard similar to the AIs accessed through a button at the top of their screen.
image

Currently there's only 1 available research project, Leg Actuator Overclock which negates some of their inherent slow.
image
CPU comes from the local CPU in the currently inhabited synth unit and from a connected AI network (network functionality not yet added) You'll be able to connect synths to a network by interacting with a networking machine.

Synths have a special form of pacifism. Normally it functions the exact same as normal pacifism, but the synth has the ability to access the Governor Module.
image
The Governor module is normally active and prevents doing actions that incur punishment (except taking damage)
At the bottom you can bypass your governor (process will be changed), this will allow you to do any action a human can do, in exchange for making the module suspicious. As per the image when you reach higher level of suspicion you get punished, if you reach max punishment you die.
Suspicion passively decreases.

It will be possible to completely disable your governor module (including a random event!), but this has not yet been implemented. A Synth with a disabled governor module is an illegal being and is valid to kill by anyone, (and security is required to do it if they know they're rogue) Becoming rogue does not allow you to murderbone or kill but it does mean you can try to stay rogue (or you can let the humans fix you). Self-defense is allowed but you may not go on a rampage.
image

Any human can ask the synth to print out a diagnostic report. This report will show when the governor module has been bypassed or disabled, and also shows all administered punishments. (Currently not implemented)

The AI has a new project to control synths stationed in a pod.

### Misc Additions
The new local networks will change and allow a few new things.
1. No more hidden upload/download consoles. You'll need physical access to the AIs network now. (Or one it is connected to)
2. This allows ghost roles and separate AI networks. You can now build an AI as the golems/free miners/oldstation people without it automatically being teleported to the station.
3. Decoupling networks from only being for the AI also allows us to add CompSci content for the netmin. Currently this only amounts to AI revival, bitcoin mining and regular research point generation.

### New project - Room Lockdown
Allows the AI, after a delay of 2 seconds, to close all working airlocks in a room and bolt them for 20 seconds. Also triggers the firealarm. Doesn't work in maint and announces itself at the start of the 2 second delay.

### New project - Heuristic Language Translation
Allows the AI to understand (but not speak) languages after hearing 8 messages containing that language. Currently ratvarian, codespeak, vampiric and xenocommon is barred from being translated. 
Requires 10% of your CPU to be allocated while running. Progress is not lost when disabling the program.

### AI Revival
No longer is the AI permanently dead when its last core is destroyed. Instead it spawns a black box at the last core it was in.
This core is active for 5 minutes. After these 5 minutes the AI is permanently dead.
You can revive the AI by inserting it into a working AI data core. (This also stops the 5 minute timer)
After its been inserted the local network the core is connected to must be set to AI Revival and the AI will then be revived after enough CPU cycles have been spent.

### Network Admin Exploration
The Network Admin can now use the VR sleeper in their room to access exploration missions. These missions contain unique components and unique research.
Currently just a mockup, only 2 added for now. One is just a walking simulator and the other one has some combat.
image
When you find the unique item you can put it in the microwave in your VR spawn and it will be transported to the station.
Future plans are to allow an AI to join you on the missions, plus allow you to buy equipment and unlock new missions using CPU on the station.

### Super Misc.
Added an easy way to use the TGUI login screen seen in the Security Console.
Use tgui_login_data in ui_data and tgui_login_act in ui_act. Use LoginScreen.js in the UI. See how the security console does it. (Only requires a var to keep track of being logged in/out)

Netmin retains access to Comms and the Tcomms satellite. NTSL equipment has been moved to the satellite and the old Hardware Workshop has been replaced by a small lounge
image

## TODO
- [x] Allow the AI a choice of which network to transfer to when a networking machine is destroyed.
- [x] More exploration missions
- [x] Allow synths to join exploration
- [x] Do all the other exploration
- [ ] Other maps
- [ ] Restore map config
- [ ] allow transfering synths to other networks
- [ ] allow upgrading synth CPUs
- [ ] check non local network CPU contributions
- [ ] add punishments to using an picking up some items (hand teleporter, ???)
- [x] add way to print diagnostic report
- [ ] implement 100 sus punishment
- [ ] add way to add synth to network
- [ ] expand governor bypassing/disabling
- [ ] disallow wheelie implants
- [ ] disable synth ID on death

TODO Punishments
- [ ] Opening personal lockers
- [ ] Grabbing any weapon
- [ ] Wearing security clothes
- [ ] Dragging restrained people

# Changelog

:cl:  
rscadd: AIs are now housed in physical networks connected by ethernet cables. Networks can be remotely connected using networking machines. AIs can only switch between cores in networks they're connected to.
rscadd: AI upload and download is now done by hooking up a laptop or modular computer to an ethernet cable and using the AI Network Interface program
rscadd: It is now possible to revive an AI by inserting the dropped black box into a functioning data core and allocating CPU using the AI Network Interface program
rscadd: Added a new program, Room Lockdown, for the AI. Allows the AI to click an area and lock all working airlocks after a 2 second delay. An announcement is made beforehand.
rscadd: The Network Admin now has a VR sleeper and can go on short self-contained exploration missions to get unique components
rscadd: It now takes the AI 1 second to open doors unless it's connected to the master subcontroller in the RnD server room. If you multitool this new machine you can also disable instant door/apc/airalarm access for specific departments.
rscadd: NanoTrasen has procured some older model synthetics. All stations are equipped with a singular synthetic by shift start. This Synthetic is meant to be a jack of all trades, master of none.
rscadd: Added the governor system for synthetics, a way to do restricted actions at the risk of getting punished by your governor module.
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Mid

**Comment by GrimGodhead** [comment]
AIs with hands?
Major upset, this whole synthetic thing is will have to be balanced extremely carefully

**Comment by ChuChu42** [comment]
due to there being pretty much no way to check if a synth's govenor is working, its currently impossible to find a rouge synth, i hope you can make that printer fast enough

**Comment by Marmio64** [comment]
I believe this reverted a portion of box maint that was changed in this PR: https://github.com/yogstation13/Yogstation/pull/18037

Should look like this-
https://user-images.githubusercontent.com/60946370/220802263-44398b45-8adc-4ac1-9927-fc53b650e21b.png

With the testmerge it does not, as the far right 3x5 right room is missing along with secluded south room east of solars, and the changed hallway above the room.

**Comment by ChuChu42** [comment]
on round 46455
i managed to roll traitor as a synth

issues: traitor synth's uplink appears on their headset, which then they cannot remove therefore being unable to use it
issue 2: around mid way into the round my synth panel bluescreened
image


good news: i greentexted 
image

**Comment by BurgerLUA** [comment]
Current bug: Synthetics can remove the encryption key in their headsets via a screwdriver. This causes the encryption key to be stuck in their hand and them unable to talk on anything but common.

**Comment by Bibby0110** [comment]
> Current bug: Synthetics can remove the encryption key in their headsets via a screwdriver. This causes the encryption key to be stuck in their hand and them unable to talk on anything but common.

fixed

**Comment by j8uj8u** [comment]
Current Bug: Pretty sure that should say "percent done"
image

**Comment by Mqiib** [comment]
An issue I've just noticed: all these roundstart synths means malfunctioning/traitor AIs now have a bunch of ghost spawn bodies subservient to them, except instead of just cyborgs now they have people with hands. These people with hands can do all the things that normal cyborgs were unable to do, such as upgrade cyborgs, repair cyborgs, build any machine, and cremate people.

That last one is pretty big. AIs can now cremate people without outside help.
I don't think synths should be at all required to follow the AI, that just makes them pacifist cyborgs with hands. As a compromise, remove their access to binary so malf/traitor AIs can continue to do their stuff in secret. Maybe malf AIs specifically can get an ability to shut down synths or something so they don't become a problem, but them being subservient to the AI is not a good idea in practice.

**Comment by BurgerLUA** [comment]
If the Headset gets EMP'd, there is literally no way to fix it because you cannot interface with it.

**Comment by Bibby0110** [comment]
> If the Headset gets EMP'd, there is literally no way to fix it because you cannot interface with it.

Fixed

**Comment by Bibby0110** [comment]
> Bug report: Had an issue last round as a synth, i've adquired cellular damage and went to a cryo tube in escape, after the tube was activated i've went unconcious but even after getting dragged out of it, i've stayed unconcious for a long time, had to call an admin to fix it and he told me to come here to report the issue. (from 01:55:39 to 01:58:30 on the round 46480 if you wish to see it on replay of the round) Might require some testing to figure out the root of the issue

Synths can no longer get cellular damage.

**Comment by Bibby0110** [comment]
> Current Bug: Pretty sure that should say "percent done" image

Fixed

**Comment by wonderinghost** [comment]
synths and bi part ipc can no longer be revived with the board.

**Comment by Bibby0110** [comment]
not this time either, sigh...

**Comment by azzzertyy** [comment]
https://docs.google.com/document/d/1v0xiiWf2sL48PsO1DImi74ZH0sXZz2M4c_3-mSjh_DI/edit?usp=sharing
Posting this here.

**Pull request closed without merging**
