### PR TITLE
Legion skulls now actually wail on death like the flavor says

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request
	visible_message(span_warning("The skulls on [src] wail in anger as they flee from their dying host!"))

# Changelog

:cl:  
soundadd: Legion skulls now audibly wail as they flee from their host
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
this going to get real old real fast

**Review by MajManatee — APPROVED** [review]
Waaaaaaaaaaa

**Comment by MajManatee** [comment]
This applies to the legion mob, and doesnt affect the skulls at all. is that supposed to be?

**Comment by ynot01** [comment]
> This applies to the legion mob, and doesnt affect the skulls at all. is that supposed to be?

You want to hear 5 screams from different directions when a legion dies?

**Review by Moltijoe — APPROVED** [review]
It works, but is this something we actually want?

**Comment by MajManatee** [comment]
yes

**Pull request merged**
