### PR TITLE
Resprites marrow weavers

### PR DESCRIPTION
**Pull request by Notamaniac**
# Document the changes in your pull request

Resprites marrow weavers

lavaland_monsters

TBH I'm not really happy with this, they're on the small side for lavaland mobs and their palette sticks out a tiny bit.

lavaland_monsters

Second attempt, lowered the saturation and luminosity a bit and changed the legs. Kept ice weavers as is for now.

# Wiki Documentation

None
# Changelog

:cl:  
imageadd: Marrow weavers and their counterpart frostbite spiders (AKA ice weavers) have been resprited  
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
Why make the P.R. if you aren't happy with the sprite?

**Comment by ChesterTheCheesy** [comment]
I like the sprites!

**Comment by Notamaniac** [comment]
> Why make the P.R. if you aren't happy with the sprite?

Just want to see if people prefer it to the current marrow weaver sprite. If there's an overwhelming majority who dislike it, I'll take another attempt at respriting it.

**Comment by Marmio64** [comment]
the sprites arent bad per say, but look much much less intimidating, dont fit in with the other mobs, and look too similar to giant spiders.

**Comment by Marmio64** [comment]
new sprite is def more worthy of lavaland but i still prefer the look of the original, just fits in more. Frostbite spider is still not intimidating but works better for iceland i suppose. I do think that the new sprite is good though but i think it could maybe work better if it was given to the jungle that was being worked on. Maybe as a compromise at least keep in the old sprite so it can easily be readded later if needed?

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
