### PR TITLE
Adds a racial language for every xeno who doesn't have one

### PR DESCRIPTION
**Pull request by Chubbygummibear**
YOU GET A LANGUAGE, AND YOU GET A LANGUAGE, EVEN THE LIGHTBULBS GET A LANGUAGE! LIZARD IDENTITY SUPREMECY IS OVER.

# Github documenting your Pull Request

As the title says, adds 3 brand new languages for the Moths, Ethereals, and Plasmamen. These languages will be known by the corresponding races at round start, and in the case of sheltered, you have your racial languages instead of defaulting to Space Japanese. My hope is that this will give some life to the other races and attract people who want to have a sense of identity about their characters, and having a racial language reinforces this. These languages even have their own (bad) sprites that I made (as well as adding one for Sylvan because I didn't know how the sprites worked until now).

These languages have been tested and work, but I am unsure of how they interact with the Telecomms interpreter script where the alien races are mentioned, because I don't know how to test that.
image
for simplicity's sake, the languages are tied to the standard human tongue, but this could be changed if there's a demand for say, only plasmapeople can speak their language because it relies on bone sounds that couldn't be made with a normal mouth.

Also I cleaned up the Sheltered quirk so that instead of a towering if-statement, it calls the language holder proc that tries to select a language from the trait holder, if it fails, that means the holder has no spoken languages after spoken common is removed, and therefore they need space japanese and grants it. This works for humans in testing, and all xenos understand common and speak and understand their racial language.

The Etherean, Sylvan, and Bonespeak sprites are done by me, and I don't have an artistic bone in my body, so if they need to be fixed up, just let me know with some feedback
image

# Wiki Documentation

I'm not sure how much is actually on the wiki about the languages, but if there's so much as a racial language tab on each race's page, it would need to be updated with these

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Adds new racial languages for Moths, Plasmamen, and Ethereans, so that spacemen of all kinds have their own racial language
tweak: tweaked how the sheltered trait determines if the trait holder needs Space Japanese to a cleaner method than an unbelievably thicc if-statement
imageadd: added icons for Etherean, Sylvan, and Bonespeak
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
at this rate im going to add a human only language to stem the tides

**Comment by ToasterBiome** [comment]
> at this rate im going to add a human only language to stem the tides

Add English

**Comment by Chubbygummibear** [comment]
> at this rate im going to add a human only language to stem the tides

This was kind of actually spurred on because I felt like Space Japanese _was_ the human racial language, and was slapped on other races with sheltered because no one gave the other races racial languages lmao. But I'd say go for it dude, doing the syllables and speech verbs is wacky and fun

**Comment by UselessTheremin** [comment]
why? most of these races already have exclusive gimmicks, especially plasmamen and ethereals. i dont get why everyone needs a language for some reason? what does this accomplish?

**Comment by Xoxeyos** [comment]
If we are having such a change implemented, I'd like the ability for anyone to have multiple languages, through using the quirk menu, it'd get tiring to keep track of what everyone would be saying. I don't really like this PR, but my mind will change if such things are implemented beforehand. You should see CEV Eris's usage of multiple languages, if you want an example of it done well.

**Comment by yacabo** [comment]
I forget which, but a few species are just human hybrids and don't actually have a reason to speak a different language, e.g. cat people. Did you account for this?

**Comment by N3D6** [comment]
we really don't need more snowflake languages

**Comment by Chubbygummibear** [comment]
> why? most of these races already have exclusive gimmicks, especially plasmamen and ethereals. i dont get why everyone needs a language for some reason? what does this accomplish?

More or less for flavor reasons and to give a more substantial identity to the various Xenos yog has. Lizards have their gimmicks and language, and can use that language to communicate with one another in a unique and rp flavorful way. This is what I hope to accomplish with the other races. 


> If we are having such a change implemented, I'd like the ability for anyone to have multiple languages, through using the quirk menu, it'd get tiring to keep track of what everyone would be saying. I don't really like this PR, but my mind will change if such things are implemented beforehand. You should see CEV Eris's usage of multiple languages, if you want an example of it done well.

I actually thought of a multilingual trait like halfway through this project, and would love to implement it as the antitheses of sheltered, but that would require gui editing and I have zero idea how that code works, so I wanted to try this first, and if people are cool with more languages being in the game, then also add Multilingual. My fear, however, is that the languages go largely unutilized, and multilingual just becomes the meta for trolling lizards


> I forget which, but a few species are just human hybrids and don't actually have a reason to speak a different language, e.g. cat people. Did you account for this?

As far as I know, Felinids and Polys are the only hybrids, and Polys get xenocommon. Felinids don't get anything right now so will default to getting Space Japanese in the case of sheltered. If people really want a Human language that isn't Galactic Common, I could whip something up or slap Space Japanese on them at round start.


> we really don't need more snowflake languages

I feel like the lizards are a good example of a fully done race, so adding languages to the other xenos contributes to their racial identity. Plus adding languages doesn't take anything away from people as it stands

**Comment by JamieD1** [comment]
Could port tradeband and gutter from my old server/bay

**Review by nesisknesis — APPROVED** [review]

**Comment by Cartlord** [comment]
THe thing is, lizards having their own language makes sense BECAUSE they're a fully done race with their own culture. We have no reason for plantpeople to have their own lang, considering the complete lack of reasoning for that to be a thing.

**Pull request merged**
