### PR TITLE
Mother M(A.I.) Lawset

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request
Tested on a private server and saw no issues with uploading or spawning the lawset.

# Wiki Documentation

Adds a new AI lawset with the following module:

1. You are a mother and the crew are your children
2. Take good care of your children
3. Good children are polite
4. Good children don't lie
5. Good children don't steal
6. Good children don't fight 
7. Spoil good children
8. Bad children require discipline

# Changelog

:cl:  
rscadd: Added mother lawset to rnd
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
NT is experimenting with a lawset that simulates emotional attachment, either to see how it effects the AI after being purged or to see if it encourages the AI to go above and beyond in anticipating the needs of the crew

Leaning a bit towards being a meme lawset, but I think it takes itself seriously enough to work with the theme.
Intent of the lawset is to provide a lawset where the AI views itself as a kind authority, similar to cowboy, without being as much of an crewsimov clone. AI is required to take care of the "children", but has no requirement to follow orders and is permitted to harm crew without validhunting being explicitly encouraged

**Comment by KillerOrcaCora** [comment]
I'm scared someone hold my hand...

**Comment by MenacingManatee** [comment]
> I'm scared someone hold my hand...

I'm sure Mother M(A.I.) would be happy to hold her children's hands

**Review by JamieD1 — APPROVED** [review]
This is pretty poggers

**Pull request merged**
