### PR TITLE
Makes icemoon surface less bright

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Makes the icemeta surface much less bright (still being bright enough to hurt darkspawn/nightmares/etc) because I think it looks a lot cooler and bright lights hurt my eyes

# Why is this good for the game?

Looks a lot cooler and hurts my eyes less

# Testing

image

# Changelog

:cl:  
tweak: icemoon surface is less bright
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
i knew something felt off last time i played on icemeta

**Comment by neeshacark** [comment]
i prefer full brightness tbh, as a CM player anything that looks like daytime instead of pitch black is a foreign concept to me and is therefore cool

**Comment by VaelophisNyx** [comment]
personally I'd prefer to not go snowblind playing SS13

**Comment by LassiH** [comment]
will this effect phytosians

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
