### PR TITLE
Attempts the porting of the syndicate contract hub

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request
This is an attempt to port over the syndicate contract hub from tgstation. Currently it doesn't have the icons and the indentation is all over the place.

#### Changelog

:cl:  
rscadd: Adds the Syndicate contract hub!
wip: This is work in progress  
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Ehh, I really feel like this should be mirrored instead of me trying to do a direct port.

**Comment by ghost** [comment]
Actually, lets try it one more time.

**Comment by Alexandria404** [comment]
If I understand this correctly, this trades TC for multiple (or infinite?) valid kills (wiki says bring the contracted people dead or alive)? (I´m aware you can also bring them allive for a few more TC) By this circumventing murderbone rules since it makes new objectives and then you by the rules are fine to kill in relation to that objective.

**Comment by Firewolf34** [comment]
This is in the game now, is it not? I just played a few shifts with the Contract Kit and by god it was fun as hell! Great work, if so.

**Comment by Akrilla** [comment]
I'm the dev making this over on TG (and soon will be starting making them a full antag based on a recent poll that got made). I'm over in the Yog Discord too if you need help with anything, I don't mind even doing the port over myself once my current PR gets merged over there.

**Comment by Akrilla** [comment]
> If I understand this correctly, this trades TC for multiple (or infinite?) valid kills (wiki says bring the contracted people dead or alive)? (I´m aware you can also bring them allive for a few more TC) By this circumventing murderbone rules since it makes new objectives and then you by the rules are fine to kill in relation to that objective.

I don't know Yog antag rules very well, but the rewards are like 0-2 for dead, and more like 6-12 for alive. You're very very much encouraged to not kill them, and was made for TG where murderbone is fine (and this is my attempt at making an interesting system that dissuaded that)

**Comment by Firewolf34** [comment]
I personally prefer them as a Traitor item because it gives me more things to do as a traitor, which can get old. Hopefully we keep it as such on Yogs. 

Great work though! It's *so* cool.

And if it becomes a problem with murderbone on Yogs we can just disable the killing portion (no rewards for killing,  just capture).

**Comment by Akrilla** [comment]
Yeah you could always just keep the policy that you still can't kill them, the system is already balanced around that anyway. Super easy to also just remove TC for killing them as well. Got another PR now in on TG for adding brand new sprites, and some QoL fixes for the system.

**Comment by Amelia0010** [comment]
@Trustback

**Comment by ghost** [comment]
Just use the mirror bot for this.

**Pull request closed without merging**
