### PR TITLE
[Bounty] Add symptom sprites to the PanD.E.M.I.C UI

### PR DESCRIPTION
**Pull request by hedgehog1029**
Adds new symptom sprites to the PanD.E.M.I.C UI.

example image

The symptom UI has been rearranged a bit to fit the new icons in.

# Why is this good for the game?

Gives symptoms some recognizable identity

This is for an approved bounty:
https://forums.yogstation.net/threads/60-2-4-add-plague-inc-style-gui-to-virology-pand-e-m-i-c-2200.24325/

# Testing

I have tested these changes by spawning random virus bottles and checking the UI.

### Known issues

Currently the "Sentient Resistance" symptom has no icon and will show a placeholder.  
I'm not a virology player, do they ever actually analyze sentient viruses?

# Spriting

All sprites provided by papi:

symptoms spritesheet

Some of these have animated variants which are used instead.

# Wiki Documentation

These sprites could presumably be uploaded to the wiki as well, check with the spriter?

# Changelog

:cl: hedgehog1029 & papi  
imageadd: Added new symptom sprites to the PanD.E.M.I.C UI  
/:cl:

### CODE REVIEW

**Comment by hedgehog1029** [comment]
i may have gone slightly overboard with autodoc, but more docs is always good right

**Comment by Moltijoe** [comment]
Who the hell is the photo realistic guy first row 4th column?

**Comment by hedgehog1029** [comment]
i'm pretty sure that's David
image

**Comment by bruhlookatthisdood** [comment]
might be some of the best sprites in the game lmao

**Comment by Laus4Deus** [comment]
Virology made vissualy appealing.

**Comment by Moltijoe** [comment]
Artistic ability = 1/sanity
Papi is one of the least sane people i've met

**Comment by cuackles** [comment]
the sprites are of very high quality and made with a lot of talent, issue is im not sure how much they do actually fit in the game, i will consult with some of the other poeple in the art team and get a decition based of that

**Comment by MajManatee** [comment]
poeple

**Comment by cowbot92** [comment]
I think the sprites look really good :)

**Review by ToasterBiome — APPROVED** [review]
nice sprites

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Can you actually pad the sprites so they're 64x64?

**Comment by hedgehog1029** [comment]
Static sprites (everything in the dmi file) have been padded to 64x64, biome said I could leave the gifs as they're a PITA to resize/regenerate.

symptoms 64px

Also updated invalid.png (the placeholder) to look less out of place

**Comment by ToasterBiome** [comment]
> Static sprites (everything in the dmi file) have been padded to 64x64, biome said I could leave the gifs as they're a PITA to resize/regenerate.
> 
> symptoms 64px
> 
> Also updated invalid.png (the placeholder) to look less out of place
> 
> 

Do these still show up properly in game?

**Comment by hedgehog1029** [comment]
@ToasterBiome Yep, I updated the class name and removed the extra margin that was being applied in the CSS. Tested after merging latest master.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
