### PR TITLE
Clownbugs have 20 lives

### PR DESCRIPTION
**Pull request by JamieD1**
Clownbugs have 20 lives

Clownbugs are annoying as fuck and there should be some downside other then them being an unkillable mob who can move under tables and pull people around

:cl:  
tweak: Clownbugs have 20 lives
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
make it 69 lives please

**Comment by CMOisLing** [comment]
Didnt know clownbug had infinite lives. I got eaten by the janitors pet lizard and was permaded

**Comment by ChuChu42** [comment]
thank god
i had suffered by the clownbug who was dragging away wounded people from medbay yesterday

tried just continuously punching, drowning him in pool, shooting it and even went out of my way to make a flamethrower just to kill it
 tried very hard but wasnt able to do shit because it kept reviving everytime it died, thank gpd there is a limit being added now
+1 i like this change
althrough make lives 30

**Comment by 00ze-cyclone** [comment]
Make flyswatter permakill it instead if you want a way to get rid of it for good.

**Comment by Bibby0110** [comment]
No rationale provided

**Comment by Hopekz** [comment]
> No rationale provided 

Even though I like this PR I like people providing reasoning more so +1

**Comment by JamieD1** [comment]
Clownbugs are annoying as fuck and there should be some downside other then them being an unkillable mob who can move under tables and pull people around

**Comment by Bibby0110** [comment]
No rationale provided in PR body

**Comment by Hopekz** [comment]
> No rationale provided in PR body

It says:

"Clownbugs are annoying as fuck and there should be some downside other then them being an unkillable mob who can move under tables and pull people around"

Before the PR body was blank so it's an upgrade from what we had before

**Comment by Bibby0110** [comment]
only downvotes

**Comment by Bibby0110** [comment]
yes it is

**Comment by JamieD1** [comment]
Fuck off bibby

**Pull request closed without merging**
