### PR TITLE
Steals bounty cubes from TG

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Steals the TG bounty cubes, modifying them to be slightly better

## Todo

- [x] Give each job their bounty category
- [x] Fix nagging not sending bank alerts
- [x] Fix runtime in price tag
- [x] Add to the maps
- [x] Linter
- [x] Less punching
- [x] Mechs
- [ ] Add a way for cargo personnel to get bounty lists for other people
- [ ] Make the cooldown not give decimal minutes
- [ ] Add anti id yoink protections
- [ ] Add way for non movable objects to be compacted

# Wiki Documentation

The global bounty list has been replaced with 3 bounties per account based on the job of account, that can be re-rolled every 5 minutes. To view your bounties place your ID in the bounty console in front of cargo. When the bounty items have been collected, the bounty can be selected in the console, and then placed onto the belt feeding into the NanoTrasen Bounty Encapsulation Device. When all the items are inserted, a bounty cube will be released.

This bounty cube contains the bounty items, and the data of the person who completed the bounty. When the bounty cube is shipped via the supply shuttle, it sends 30% of the bounty to the person who filled it, and an additional 10% to the cargo tech who places it on the shuttle and then scans it with their export scanner. An additional 20% of the bounty will be awarded for shipping in less than 5 minutes.

# Changelog

:cl:  
rscadd: Added bounty cubes
rscdel: Removed old bounty system  
imageadd: added bounty cube image
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
I don't think you can complete the comfy chair bounty since the chairs are anchored

**Review by nesisknesis — APPROVED** [review]

**Comment by bruhlookatthisdood** [comment]
does this remove the normal bounties that cargo gets?

**Comment by adamsong** [comment]
Yes

**Comment by JamieD1** [comment]
This ongoing or what? Ive left it due to unchecked tickboxes.

**Comment by adamsong** [comment]
I'll get back to this at some point soon, been a bit busy with school

**Review by ghost — APPROVED** [review]

**Comment by JamieD1** [comment]
Something something, get on with it <3

**Comment by JamieD1** [comment]
Reopen when you complete this.

**Pull request closed without merging**
