### PR TITLE
Centers a lot of food objects

### PR DESCRIPTION
**Pull request by ynot01**
fuck you

### CODE REVIEW

**Review by Partheo — CHANGES_REQUESTED** [review]
90ZsU3Qa8W

Also, you were inconsistent with some of the pizzas:
image
image
Please center them all the same.

**Comment by Partheo** [comment]
what the fuck turdis

**Comment by ynot01** [comment]
ill fix the migrawr but i dont have this fancy cross program you use im just eyeing these

**Comment by Georgeur** [comment]
I personally prefer most of them lower, as especially on the chefs counter, it makes it seem less top down, 2d perspective.

**Comment by ynot01** [comment]
> I personally prefer most of them lower, as especially on the chefs counter, it makes it seem less top down, 2d perspective.

maybe but for practicality sake placing something and then having it appear below your cursor is annoying

**Review by Partheo — APPROVED** [review]

**Pull request merged**
