### PR TITLE
Adds new craftable food: Vegan Donuts

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Adds a new craftable donut type for 1 tofu and 1 donut

# Why is this good for the game?

food

# Testing

yes

# Changelog

:cl:  
rscadd: Adds new donut recipie

/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Who hurt you

**Comment by cowbot92** [comment]
> Who hurt you

god gave me wings so I could fly high

**Comment by iloveloopers** [comment]
Vegan is bad

**Comment by ktlwjec0** [comment]
just make them with soy milk theyre already vegann aioedhjwoiaejoiajeroiwajropwjaa

**Comment by JamieD1** [comment]
Why we encouraging vegans

**Comment by JamieD1** [comment]
> just make them with soy milk theyre already vegann aioedhjwoiaejoiajeroiwajropwjaa

Also this

**Comment by cowbot92** [comment]
> just make them with soy milk theyre already vegann aioedhjwoiaejoiajeroiwajropwjaa

no this is funnier

**Comment by Reed0506** [comment]
how does adding tofu to something suddenly make it vegan

**Comment by cowbot92** [comment]
> how does adding tofu to something suddenly make it vegan

you wrap it around it

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
