### PR TITLE
Shadowling Balance

### PR DESCRIPTION
**Pull request by JamieD1**
Thralls and Shadowlings now cannot be implanted.

#### Changelog

:cl:   
tweak: Thralls and Shadowlings now cannot be implanted.
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
five minutes is excessive make it 2.5 minutes

**Comment by ghost** [comment]
Five minutes is an incredibly excessive timespan that would make it easier to simply deimplant the HoS with surgery.

In fact, the timespan doesn't matter, because all you need IS a surgery table to cut one out, and that's not longer than 30 seconds.

You would be better off simply making it that thralls resist implants, so you can't reimplant a thrall to have them be disguised.

**Comment by Marmio64** [comment]
this is retarded. The HoS can get fucked if they got captured by a shadowling. You can already fuck over shadowlings pretty easily, and like adam said, surgery isn't very hard, but its nice to just do the whole thrall thing.

**Comment by JamieD1** [comment]
> this is retarded. The HoS can get fucked if they got captured by a shadowling. You can already fuck over shadowlings pretty easily, and like adam said, surgery isn't very hard, but its nice to just do the whole thrall thing.

I dont see shadowlings walking round with surgery tools do you?

**Review by alexkar598 — DISMISSED** [review]
Duplicated code, make line 66 be 
```
if(target.mind.has_antag_datum(/datum/antagonist/gang/boss) || is_shadow_or_thrall(target))
```

**Comment by Reed0506** [comment]
if the slings cant do surgery
that is what is known as
not planning ahead

adam is correct

**Review by fluffe9911 — APPROVED** [review]
ok

**Pull request merged**
