### PR TITLE
Hand teleporter portals now links atmospherics together

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

was hoping this was going to be hard and then someone added a var for it 4 years ago. sad. Still, this makes it so you can't brute force hand teleporter random into the AI upload or something, and now it is truly deserving of the high risk designation.
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Hand teleporter portals now links atmospherics together
/:cl:

### CODE REVIEW

**Comment by isotope436** [comment]
does this mean i can now teleport fusion gas into medbay at the push of a button and single handedly game end the station in one go :o

**Comment by Simplehorror** [comment]
i mean you could already do that with a bluespace pipe :-)

**Comment by Simplehorror** [comment]
or just opening your incinerator doors to medbay maintanence to medbay since equalisation is instant

**Comment by Simplehorror** [comment]
besides, fusion is worse than a plasma flood because fusion will just burn straight through the floor tiles.

**Comment by Maia-J** [comment]
I for some reason like this way too much

**Comment by iamthesilly** [comment]
Time to warp fusion-heated CO2 and BZ into the central primary hallway

**Comment by Moltijoe** [comment]
both a terrible and great idea at the same time

**Comment by iamthesilly** [comment]
Would love to see how this plays out honestly, it could go well or very poorly but there's only one way to find out

**Comment by CMOisLing** [comment]
Has this been tested with our atmos. It was probably just made to work with LINDA

**Comment by Simplehorror** [comment]
it'll work fine

**Comment by CMOisLing** [comment]
> it'll work fine

You uhhh tested it right?

**Comment by Bibby0110** [comment]
While being very cool, this opens up a few too many laggy and unbalanced interactions

**Pull request closed without merging**
