### PR TITLE
Fixes Nich's mistakes

### PR DESCRIPTION
**Pull request by GrayRachnid**
Doesn't fix that he exists sadly

### CODE REVIEW

**Comment by ghost** [comment]
Maps with diff:<br><details><summary>_maps/map_files/YogStation/YogStation.dmm</summary>

Old | New
--- | ---
 | 

Status | Region | Logs | Raw
--- | --- | --- | ---
Modified | (38, 49) => (188, 188) | [Logs](https://dextraspace.net/MapDiffBot/Files/120966336/447/0/logs.txt) | [Old](https://dextraspace.net/MapDiffBot/Files/120966336/447/0/before.png) \| [New](https://dextraspace.net/MapDiffBot/Files/120966336/447/0/after.png)

</details>





<br>Last updated from merging commit 3b2f81b1d0c47ad8b85f1a64abc58360d8f3e0b9 into 5911c80cbd356d1d86810048711905e36b2b88f5



Full job logs available [here](https://dextraspace.net/MapDiffBot/Files/120966336/447)



Please report any issues [here](https://github.com/MapDiffBot/MapDiffBot/issues).

**Comment by GrayRachnid** [comment]
i'm probably getting yelled at by nich tomorrow for somehoe fucking up map merge

**Comment by GrayRachnid** [comment]
Map is now ready for rebase

**Comment by Amelia0010** [comment]
honk

**Pull request merged**
