### PR TITLE
Makes the Academy die of fate one-use

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
Its really not a great idea to have an item that gives you a 5% chance to get wizard per roll, which you can roll multiple times. 

#### Changelog

:cl:  
tweak: Changed the Academy die of fate to a single use one.
/:cl:

### CODE REVIEW

**Comment by Codeatmos** [comment]
Right after a round where 2 d20s rolled,thats what a 2.5% chance? i ded.

**Comment by Bibby0110** [comment]
Kind of ided pr, even though I was not playing I guess.
I have seen wizard rolls once or twice per day for quite a while .-.

**Comment by Bibby0110** [comment]
Could also just nerf the die even more, but eh

**Review by AsV9 — APPROVED** [review]

**Comment by Nickvr628** [comment]
I died tiem to opun a pee arr

**Comment by Bibby0110** [comment]
how can it be i ded if i never play the game

**Review by SomeguyManperson — APPROVED** [review]

**Comment by HomocidlePancakes** [comment]
1)Ever since this was implemented I rolled wiz thrice, and only saw 4 other people do it, not to mention all the times I got instagibbed. 
2)You can rig dies to modify the percentage of certain outcomes, do that instead.

**Comment by Bibby0110** [comment]
must remove feature

Lets just rig it to 1 then

**Comment by SomeguyManperson** [comment]
epic B)

**Pull request merged**
