### PR TITLE
Removes the 24605 poster

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request

Unfunny old joke.

#### Changelog

:cl:  
rscdel: There has been no such event as '24605' and all conversation about the topic is a capital crime in accordance with Galactic Law Section 64-F
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
why? if your going to remove posters if anything remove nickvrs

**Comment by fluffe9911** [comment]
good poster sprite that is fine even without the origin knowledge

**Comment by Bibby0110** [comment]
> good poster sprite that is fine even without the origin knowledge

My man what, the sprite isn't that good....

**Comment by Bibby0110** [comment]
> why? if your going to remove posters if anything remove nickvrs

Because this a PR to remove the 24605 poster, a poster that doesn't even look like a poster.

If this was a PR to remove the nickvr poster this comment would make sense.

**Comment by fluffe9911** [comment]
the instant 7 downvotes says otherwise

**Comment by yacabo** [comment]
C u l t u r e

**Comment by Bibby0110** [comment]
> the instant 7 downvotes says otherwise

Downvotes mean nothing old man, we live in the age of absolutism.

**Comment by MrHorizons** [comment]
What Bood said. 24605 can at least be somewhat divorced from the person who caused it (you). Meanwhile, there's a literal-ass poster just to advertise Nickvr, who doesn't even want to be associated with Yog anymore.

**Comment by Bibby0110** [comment]
> What Bood said. 24605 can at least be somewhat divorced from the person who caused it (you). Meanwhile, there's a literal-ass poster just to advertise Nickvr, who doesn't even want to be associated with Yog anymore.

Yet this isn't a PR to remove the Nickvr poster, I don't mention Nickvr anywhere I don't know what this whataboutism is about.

**Comment by Readystorm546** [comment]
I suck at making sprites and I still thought that one was pretty good when I made it

**Comment by Bibby0110** [comment]
> I suck at making sprites and I still thought that one was pretty good when I made it

:) Keep at it, practice makes perfect

**Review by Partheo — APPROVED** [review]
If you want to remove the nickvr poster, then remove the nickvr poster. This PR is unrelated.

**Comment by Bibby0110** [comment]
> If you want to remove the nickvr poster, then remove the nickvr poster. This PR is unrelated.

Yo Partheo, if you ever feel up for it the Singularity poster could use some pizzazz, mainly a border so it doesn't look horrendous.

**Pull request closed without merging**
