### PR TITLE
ports possums from desert rose

### PR DESCRIPTION
**Pull request by boodaliboo**
https://github.com/judgex/desertrose/pull/82

### Intent of your Pull Request
adds possums and a special one called poppy the safety possum to engineering
#### Changelog

:cl:  
rscadd: Added possum
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
image

**Comment by ynot01** [comment]
where do we see possum_aaa

**Comment by boodaliboo** [comment]
> where do we see possum_aaa

 i uh had to remove the interactions to make it pass travis

**Comment by boodaliboo** [comment]
> > where do we see possum_aaa
> 
> i uh had to remove the interactions to make it pass travis

may look on adding them backj using petting for it or soemthing

**Review by Partheo — CHANGES_REQUESTED** [review]
Don't put two changelog entries for the same thing.

**Review by patpol4 — CHANGES_REQUESTED** [review]
Pet oversaturation again. Map is fine but honestly i would prefer if you put Poppy in both the engines instead of just outside the CE office where Poly is.

**Comment by boodaliboo** [comment]
> Pet oversaturation again. Map is fine but honestly i would prefer if you put Poppy in both the engines instead of just outside the CE office where Poly is.

that can be done

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Merge when mappers are happy.

**Comment by boodaliboo** [comment]
> Merge when mappers are happy.

did requesteed changes

**Review by Partheo — APPROVED** [review]
Fixed it for you

**Review by patpol4 — APPROVED** [review]
mappers are happy

**Pull request merged**
