### PR TITLE
!!!(Fight against racism) ~Resprites the Grinder~ (Fight against racism)!!!

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
What have I changed? Have I really changed anything? You can never change racism, Only prolong it. Grinders now have the colors Black and Yellow strips on them like all the other disposals.

Feeling lesser already? ahhh shit son we haven't even got to the meat yet.

Because NT is far more concerned over a free slip-and-slide ride rather than labeling the machine that literally destroys objective items and crewmembers alike like me in the morning eating morning ribs for breakfast. 

Tested, Worked. Racism always works...

The purpose of this PR, I would say consistency but it's much more than that...Its racism. 

evidently too blind to see it but it's there trust me. 

I'm losing it.

# Spriting
disposalstuff
disposal
disposalblood

# Wiki Documentation

Update a png somewhere...

# Changelog

:cl:  

imageadd: Grinder now has caution strips painted on but in reality, they should paint one on you! 

/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
What the fuck?

**Comment by Burger1998** [comment]
good change and sprite but my man is going through a schizophrenic episode here

**Comment by Sniblet** [comment]
Fuck racism!

**Comment by KillerOrcaCora** [comment]
image

I'm at the fucking top, now the silencers come and send Conflicts and random files into my pr BUT I AINT HAVING NONE OF THAT SHIT GET THAT SHIT OFF OF ME! The radical racist are trying to put conflicts in my PR! SEE HOW THEY TRY TO BRING ME DOWN SEE HOW THEY TRY TO KEEP US DOWN! BRING THIS SHIT TO LIVE TV AND HAVE THEIR FACES KNOWN AND SHOWN!!!

**Comment by iamthesilly** [comment]
are you okay

**Comment by Hopekz** [comment]
Good PR

**Comment by Hopekz** [comment]
> are you okay

The radical racists are attacking their PR!!

**Comment by Bibby0110** [comment]
are you okay orca

**Comment by Moltijoe** [comment]
we're here if you need to talk orca

**Review by cuackles — DISMISSED** [review]
love it but could you turn down the color a bit so it matches better with the current yellow lines in the other things ? seems a bit to brigth at the moment, but very good idea overall

**Comment by KillerOrcaCora** [comment]
ill be updating all the caution strips to match my new scheme (well it's not new these are the same colors stripped off disposals, but as you know our sprites are more inconsistent than a mentors wiki edit)

**Review by cuackles — APPROVED** [review]
talked with orca and they are gonna do an overhaul of all the dimmer lines so they are the same brigthness as this one, that would be given in another pr tho so for now this one is aproved

**Comment by Potototatoh** [comment]
why bother changing everything

**Comment by Hopekz** [comment]
> why bother changing everything

You just tried to replace all floors like a week ago

**Comment by KillerOrcaCora** [comment]
> why bother changing everything

**Comment by KillerOrcaCora** [comment]
Oops

**Comment by KillerOrcaCora** [comment]
> why bother changing everything

Quitter talk or racism talk, Pick one.

**Comment by Potototatoh** [comment]
> > why bother changing everything
> 
> You just tried to replace all floors like a week ago

i will replace your liver with a rock

**Pull request merged**
