### PR TITLE
adds ninja suit to necropolis chest

### PR DESCRIPTION
**Pull request by boodaliboo**
it is good decisionm balance wise i blieve thaT IT IS imporotant to include the other people

#### Changelog

:cl:  
rscadd: Added ninja necropolis chest
/:cl:

### CODE REVIEW

**Comment by gar4** [comment]
Wasn't this removed from the russian ruin as it was deemed too OP?

**Comment by boodaliboo** [comment]
> Wasn't this removed from the russian ruin as it was deemed too OP?

no

**Comment by Hopekz** [comment]
Replacing the ERT hardsuit with this would be a better change IMO.

**Comment by gar4** [comment]
#5644

**Comment by boodaliboo** [comment]
> #5644

wrong codebase

**Comment by Ratvar** [comment]
Making PRs just to spite others probably should not happen.
image
image

**Comment by boodaliboo** [comment]
> Making PRs just to spite others probably should not happen.
> image
> image

i would never

**Comment by boodaliboo** [comment]
got my reaction

**Pull request closed without merging**
