### PR TITLE
Fixes jaunt

### LINKED ISSUE #13860: Wizard Jaunt is bugged
### Severity

Round Breaking

### Short Description

As wizard, tried to jaunt and it locked my camera on that tile, didn't mist me, and then moved my character back and forth.

### Reproduction

Blinked into sec pod, prepared El Nath, and tried to jaunt.

### Round ID

Round #40662

### Test Merges

_No response_

### BYOND Username

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Something bad can happen if your location isn't a turf. Now it checks is your location a turf, and if not gets a turf of your location(if you somehow are sitting in a morph that has been eaten by a space dragon it will, maybe, still be bugged, but i don't think that it commonly happens.)

Closes https://github.com/yogstation13/Yogstation/issues/13860 (Maybe)

# Changelog

:cl:  
bugfix: Fixes jaunting while not on a turf
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Proper title

**Comment by JamieD1** [comment]
Better Title please

**Comment by tattax** [comment]
the wizard wasn't in an obj or whatnot, he got disarmed when he started the jaunt, which prioritized force moving him to the shoved tile and out of the spell, pretty rare situation tbh and has to be perfectly timed to work like it did there

**Comment by ghost** [comment]
Hmmm

**Comment by ghost** [comment]
Dude said that he was in a space pod

**Comment by tattax** [comment]
sec pod (escape pod)

**Comment by ghost** [comment]
Ok based

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
we have is_turf helper, use it

**Comment by Bibby0110** [comment]
7 days of no activity. Doesn’t compile, likely won’t fix the bug in the first place

**Pull request closed without merging**
