### PR TITLE
Microwaving tin foil hats now creates explodes (Technically not an explosion but a flash)

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

I'm sure this won't go wrong

# Wiki Documentation

Title

# Changelog

:cl:  
tweak: In addition to warping your tin foil hat, microwaving it now also creates a minor blast
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
did you make it so I can microwave forks and die yet

**Comment by Bibby0110** [comment]
> did you make it so I can microwave forks and die yet

no

**Comment by Cartlord** [comment]
Bibby what the fuck are you doing

**Comment by Bibby0110** [comment]
> Bibby what the fuck are you doing

What I want :)

**Pull request closed without merging**
