### PR TITLE
Preference for Valentines with added laser cannon

### PR DESCRIPTION
**Pull request by alexkar598**
Players can now opt out of Valentines events

🆑
rscadd: Opt out for Valentines for Donators
/🆑

Also lol i put more effort into this, jamie's pr is an opt IN, not an opt OUT

laser gif

https://user-images.githubusercontent.com/25136265/153955320-8d50de03-36ec-4662-b28d-5a05408d83be.mp4

### CODE REVIEW

**Comment by Mqiib** [comment]
Quality coding

**Comment by num1bamf** [comment]
Hmmm yes. Good change. Improves RP. Given 2 bamf thumbs up.

**Comment by KittyNoodle** [comment]
speedmerge

**Comment by Moja10** [comment]
Bro add that as a smite 10/10

**Comment by Darkstick** [comment]
> Bro add that as a smite 10/10

this but unironically, this really does look like a smite from heaven or centcomm orbital laser canon. It looks great!

**Pull request closed without merging**
