### PR TITLE
adds eggman to charged black and magic mirror and prides mirror 

### PR DESCRIPTION
**Pull request by boodaliboo**
there not op so why not
#### Changelog

:cl:  
rscadd: adds eggman to charged black and magic mirror and prides mirror 
/:cl:

### CODE REVIEW

**Review by JamieD1 — APPROVED** [review]

**Review by Hopekz — CHANGES_REQUESTED** [review]
Fix your changelog.
Current: "rscadd: egg <@250285065039380481>"

**Comment by patpol4** [comment]
Maybe update the comment in the file

**Review by alexkar598 — DISMISSED** [review]
Remove the comment

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Fix your changelog

**Comment by JamieD1** [comment]
@boodaliboo

**Comment by boodaliboo** [comment]
> Fix your changelog

what?

**Comment by JamieD1** [comment]
> > Fix your changelog
> 
> what?

Fix your changelog... its has <@250285065039380481> in it

**Comment by boodaliboo** [comment]
> > > Fix your changelog
> > 
> > 
> > what?
> 
> Fix your changelog... its has <@250285065039380481> in it

that was to tag someone on discord on creation of the pr. it was colburn

**Comment by JamieD1** [comment]
> > > > Fix your changelog
> > > 
> > > 
> > > what?
> > 
> > 
> > Fix your changelog... its has <@250285065039380481> in it
> 
> that was to tag someone on discord on creation of the pr. it was colburn

Please just remove it and ill suggest its merged.

**Comment by Hopekz** [comment]
> > > > > Fix your changelog
> > > > 
> > > > 
> > > > what?
> > > 
> > > 
> > > Fix your changelog... its has <@250285065039380481> in it
> > 
> > 
> > that was to tag someone on discord on creation of the pr. it was colburn
> 
> Please just remove it and ill suggest its merged.

Maintainers or whoever merges it can just modify that right before a merge once they are aware of it.

**Comment by JamieD1** [comment]
> > > > > > Fix your changelog
> > > > > 
> > > > > 
> > > > > what?
> > > > 
> > > > 
> > > > Fix your changelog... its has <@250285065039380481> in it
> > > 
> > > 
> > > that was to tag someone on discord on creation of the pr. it was colburn
> > 
> > 
> > Please just remove it and ill suggest its merged.
> 
> Maintainers or whoever merges it can just modify that right before a merge once they are aware of it.

I know, I have sent this to alexkar with the note to edit the changelog

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
