### PR TITLE
Replaces the normal vent clog events with smoke instead of foam

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

A little less laggy
A bit more funny

image

# Wiki Documentation

Normal, Threatening, and Catastrophic now smoke

# Changelog

:cl:  
tweak: Replaces the normal vent clog events with smoke instead of foam
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
problem is smoke bricks the lighting engine

**Comment by redmoogle** [comment]
> problem is smoke bricks the lighting engine

Depends on lag levels it typically breaks under heavy lag

**Comment by JamieD1** [comment]
Can we just increase the async on the foam?

**Review by Bibby0110 — APPROVED** [review]
lets try it

**Comment by Sniblet** [comment]
This kills 20% of the station every time it trips and also kills the lighting system as predicted
Foam did neither of these things

**Comment by redmoogle** [comment]
> This kills 20% of the station every time it trips and also kills the lighting system as predicted
> Foam did neither of these things

Foam was freezing up subsystems

**Pull request merged**
