### PR TITLE
Makes lava & anomaly hallucinations actually sometimes hurt you

### PR DESCRIPTION
**Pull request by Altoids1**
DotLyna paid me to do this.

#### Changelog
:cl:  Altoids
rscadd: Lava and Anomaly hallucinations now have a 5% chance of actually hurting you like the real thing!
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
@Lynameep Why?

**Comment by Lynameep** [comment]
It's a 5% chance to be shocked/catch on fire from an already rare event that you can avoid easily.

What's wrong with it? @ThatLing @Assblater @Alexandria404 @Alek2ander @ThatLing @nichlas0010

**Comment by ThatLing** [comment]
I'm asking you, why?

**Comment by Ktlwjec** [comment]
they're not real that's what's wrong with it

**Comment by Lynameep** [comment]
I just told you; it's a relatively amusing thing that has a small chance of happening while also being easily avoided. Also this only happens if you're already hallucinating so...

**Comment by ThatLing** [comment]
Any other reasons before I close this?

**Comment by Lynameep** [comment]
@ThatLing 

Are you not going to give your reason for closing it or you just brigading?

**Comment by ThatLing** [comment]
"becuz xD funny pr" isn't a valid reason

**Comment by Oakboscage** [comment]
Yeah no

**Comment by Oakboscage** [comment]
Also if you want this merged you're going to need a council vote because this is some real dumb shit.

**Comment by Lynameep** [comment]
Sure I don't mind sending this to a council vote. 

At Least then you'd be required to give a valid reason instead of just "oh lyna made it".

**Comment by ThatLing** [comment]
I just gave you your reason. Also, you didn't make this, Altoids did :)

**Comment by Lynameep** [comment]
Still waiting on your reasoning against Ling.

Edit: No you haven't.

**Comment by ThatLing** [comment]
Ok, you might want to actually read my post then

**Comment by Lynameep** [comment]
2 posts demanding my reason
1 threating to close it
1 telling my reason isn't good enough for you

Where is **Your** reason against this again?

**Comment by Bowmayor** [comment]
imagine being mad over your meme pr getting declined

**Comment by Lynameep** [comment]
@Assblasters 
Assuming anger over the internet is kind of old and relatively childish. If you have something productive to say feel free to do so.

**Comment by Lynameep** [comment]
>they're not real that's what's wrong with it

@Ktlwjec  You do know plenty of the hallucinations do actually stun and have actual effects on you right..? I know not every admin/player is aware of all the tiny ins and outs of this game but that's kind of a redundant reason when some already do have real effects.

**Comment by Bowmayor** [comment]
> @Assblasters
> Assuming anger over the internet is kind of old and relatively childish. If you have something productive to say feel free to do so.

ok retard

**Comment by Ktlwjec** [comment]
yes

**Review by monster860 — CHANGES_REQUESTED** [review]
Make it so the hallucination has to be really high and also add a delay, so that for the first like 2 seconds of the thing's existence it can't hurt you in case one appears right in your path.

**Comment by Lynameep** [comment]
@monster860 

I told altoids about this as the possible change but yeah this seems great. Thanks for the input.

**Comment by ThatLing** [comment]
> 
> 
> > they're not real that's what's wrong with it
> 
> You do know plenty of the hallucinations do actually stun and have actual effects on you right..? I know not every admin/player is aware of all the tiny ins and outs of this game but that's kind of a redundant reason when some already do have real effects.

You do know plenty of the hallucinations don't actually kill and are pretty harmless right..? I know not every admin/player is aware of all the tiny ins and outs of this game but that's kind of a redundant reason when none already don't have real effects.

**Comment by DLCabbose** [comment]
I know you're typically not ever here on the server but we had a rebase and things are not exactly the same as they once were _LYNA._ They could of been a perfectly fine pr before the rebase but as they've said they are not entirely familiar with things now that they've changed.

**Comment by Alexandria404** [comment]
Let´s step back a bit and think this over, try saying it out aloud:
Why should a hallucination set you on fire? Why should your mind breaking, and making you imagine things that are not there, set you on fire?
This is straight up backwards.

The question stays in the open: By what reason and for what purpose.

You being insane, reality and illusion might be one and the same at times, but for sane and even the insane people, while they might imagine fire there is none.

**Comment by Mr-Space** [comment]
> 
> 
> Let´s step back a bit and think this over, try saying it out aloud:
> Why should a hallucination set you on fire? Why should your mind breaking, and making you imagine things that are not there, set you on fire?
> This is straight up backwards.
> 
> The question stays in the open: By what reason and for what purpose.
> 
> You being insane, reality and illusion might be one and the same at times, but for sane and even the insane people, while they might imagine fire there is none.

This man is a doctor and I trust him 100%.

**Comment by Lynameep** [comment]
@ThatLing 
> You do know plenty of the hallucinations don't actually kill and are pretty harmless right..?

None of them kill you yes that's true but they're not pretty harmless at all. False information over the radio at critical times, not getting an accurate reading on a health scanner, randomly "dying" and being unable to move or speak for over 5 seconds, having to avoid something that stuns you for a few seconds.

These aren't "pretty harmless" as some of them do actually affect the game and yourself to quite a varying degree.

> I know not every admin/player is aware of all the tiny ins and outs of this game but that's kind of a redundant reason when none already don't have real effects.

Just goes to show you not knowing about this leads to you rejecting something based on a lack of information. Try again.

@Alexandria404 

> Why should a hallucination set you on fire? Why should your mind breaking, and making you imagine things that are not there, set you on fire?

I already does set you on fire though it's just the damage has the potential to be real instead of just being fake. 

>By what reason and for what purpose.

to add an additional layer of confusion and potential doubt to an easily avoidable set of hallucinations that more often than not doesn't affect players on a normal day to day basis.

> You being insane, reality and illusion might be one and the same at times, but for sane and even the insane people, while they might imagine fire there is none.

Just so you know there are mages, eldritch horrors, and literal gods yet you're trying to rationalize the logic in an anomaly that only you can see and interact with and take real and lasting damage? What...??

@DLCabbose 
I saw a bit of my promotion application in yours... I guess you're picking up bad habits from me.

**Comment by Alexandria404** [comment]
I am aware it appears to the person hallucinating he´s on fire, what I meant of course why should it hurt, you in case that was not apparent.
If you want to spice it up do so in the frame of a hallucination, but not by there coming real damage for no reason out of nowhere.
If this was a spell, a curse etc I´d agree with your attempt to derail my logic, but we are talking about hallucinations here.

**Review by monster860 — APPROVED** [review]
This is a meme PR

**Comment by Lynameep** [comment]
A little bit of meme magic goes a long way.

**Comment by HomocidlePancakes** [comment]
I regret I haven't noticed this PR sooner. Would've been a fun discussion

**Pull request merged**
