### PR TITLE
Revert "Update toxin_reagents.dm (#17068)"

### PR DESCRIPTION
**Pull request by areaven**
This reverts commit 099b9e9e3635ea6a3d0930b436cc3e7afa8dc57b.

# Document the changes in your pull request
Adds back Rotatium's effect.

# Changelog
:cl:  
tweak: Rotatium is back!
experimental: This is experimental
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
I don't know how I feel about this
Rotatium made me feel a bit motion sick whenever I got hit by it, and I've heard other people complain about this too

**Comment by areaven** [comment]
Yeah. I'm leaving this up to the devs to merge or not. I tried it just now and it feels bearable, but it's something that's up to debate.

**Comment by yacabo** [comment]
From the PR that was reverted:

image

Was a fix found?

**Comment by Moja10** [comment]
If people are concerned about the rate, it could be a little slowed down to still disrupt gameplay but not make people vomit.

**Comment by neeshacark** [comment]
afaik it was removed because people were using it to crash peoples games.

**Review by Moltijoe — CHANGES_REQUESTED** [review]
has there been a fix for it crashing people?

**Comment by Moltijoe** [comment]
no response in a week, there doesn't seem to be people clamoring for rotatium to be brought back either

**Pull request closed without merging**
