### PR TITLE
Resprites pressure tanks

### PR DESCRIPTION
**Pull request by AMyriadseviltwin**
# Document the changes in your pull request

Sprited entirely, through a lot of trial and error (including accidentally having to redo the whole thing), by @cuackles 

image

# Why is this good for the game?
Yes it is

# Testing
Yes

# Spriting

image --> image

# Changelog
:cl:  Cuackles
imageadd: Completely resprited pressure tanks
/:cl:

### CODE REVIEW

**Comment by StupidTums** [comment]
Right when we got our beloved old pressure tanks back, you come and rip it away from us again...

**Comment by Cartlord** [comment]
Why?

**Comment by ktlwjec0** [comment]
I know how much work has gone into these and I appreciate that, but I really dislike how they look and don't think they fit in well.

**Comment by StupidTums** [comment]
I wouldn't go as far to say they look bad or out of place. Both look good. Just as long as they aren't those solid blocks of color that we had for way too long, I'm cool with them.

Edit: Though I will say, the new tank having a flat top is not a great look. You'd be hard pressed to find tanks irl that are flat on top like that.

**Comment by Cartlord** [comment]
I recall some kinds of barrels having similar designs, so that - in the event of a rupture - it just blows the top & bottom off instead of turning the whole thing into deadly fragments.
Whether that's a good design in the context of gas tanks in an outpost on a hostile world, or whether N.T. would care - that's not my argument to make.

edit: just realized this is being made by amyriadseviltwin right after amyriad's p.r. to change their sprites to the old ones got merged, what the fuck?

edit 2: they joined on the ninth, and opened this on the tenth. **what** the fuck

**Review by Mqiib — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
