### PR TITLE
Fixes 2 bugs with blastdoor crafting

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Make them start open so you can actually link them
Removes stupid message that I had already put there

### Why is this good for the game?

Bugs bad

#### Changelog

:cl:  
bugfix: Fixed blastdoors being unlinkable
bugfix: Got rid of duplicate message
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
since when are these craftable in the first place?

**Comment by redmoogle** [comment]
> 
> 
> since when are these craftable in the first place?

since https://github.com/yogstation13/Yogstation/pull/10548

**Comment by ToGWtF** [comment]
This made it so you cant toggle APC power off and crowbar open blast doors.

**Comment by redmoogle** [comment]
> 
> 
> This made it so you cant toggle APC power off and crowbar open blast doors.

Fixed

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
