### PR TITLE
Much bigger holodeck, enables actual chess games now.

### PR DESCRIPTION
**Pull request by JamieD1**
Adds 10x9 Holodeck

Chess and shit

image

#### Changelog

:cl:  
rscadd: 10x9 Holodeck
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
POG

**Review by athena413 — CHANGES_REQUESTED** [review]
image
image
image


Perma on IceBox, Eclipse, and Box are still 5x10

**Comment by Tipy1802** [comment]
Finally! Would be great if the pieces were different for the two sides. Maybe white being NT themed and black Antagonist based

**Comment by alao3alao3** [comment]
don’t we have to change the other holodeck environments to accommodate for the 10x9 holodeck or no

**Comment by athena413** [comment]
image
the carpet here makes it kinda look like ass

**Comment by athena413** [comment]
> don’t we have to change the other holodeck environments to accommodate for the 10x9 holodeck or no

theyre already changed

**Comment by MrHorizons** [comment]
I still think it should be a full 10x10.

**Comment by patpol4** [comment]
All the existing maps are there, i ported them from tg with adjustements 
vivaldi_qVi7oGMW5Q
, this is how i fit the holodeck in box perma: 
vivaldi_qyaSH6thDf

**Review by patpol4 — APPROVED** [review]
Maps reviewed

**Pull request merged**
