### PR TITLE
MonsterMOS Balance (Makes windoors have more health)

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

These got missed with monsterMOS balances.

Up for debate, but its better then what they are right now.

#### Changelog

:cl:  
tweak: Windoor Health Values
/:cl:

### CODE REVIEW

**Review by alexkar598 — APPROVED** [review]

**Comment by Marmio64** [comment]
they already have enough health. Sometimes its even easier to just smash the walls nearby down, and immovable rod cant space areas with windows cause they only break the window and leave the shutter

**Comment by Hopekz** [comment]
I think of the window shutter as a move of a "are you sure about that" layer that shouldn't really be too strong.

**Comment by MegaEmpirical** [comment]
They're definitely not strong enough. Plenty of people are happy to break into engineering through the delivery windoor or break into cargo though the delivery office. It doesn't take that long.

**Comment by Hopekz** [comment]
> They're definitely not strong enough. Plenty of people are happy to break into engineering through the delivery windoor or break into cargo though the delivery office. It doesn't take that long.

These are window shutters not windoors . So basically the ones that go down when you break a window to the outside

**Comment by MegaEmpirical** [comment]
The changelog and code say windoor

**Comment by MegaEmpirical** [comment]
I see now that Hopek changed the name and incorrectly at that. Shame him.

**Comment by JamieD1** [comment]
> > They're definitely not strong enough. Plenty of people are happy to break into engineering through the delivery windoor or break into cargo though the delivery office. It doesn't take that long.
> 
> These are window shutters not windoors . So basically the ones that go down when you break a window to the outside

Always been the windoors not the shutters.

**Comment by Hopekz** [comment]
> I see now that Hopek changed the name and incorrectly at that. Shame him.

whoops my b

**Comment by Hopekz** [comment]
So what does this have to do with monstemos? 
You confused me because windoors have nothing to do with monstemos

**Comment by MegaEmpirical** [comment]
Mostly to do with how Monsteratmos doubled the health of all windows (reinforced and normal) but didn't touch windoors. This PR doesn't go so far as to double Windoor health, just adds an extra 50 (about a third more for normal windoors and not even 20% more on reinforced ones). Discourages greytiding a little and gives a little more protection from atmos.

**Comment by alexkar598** [comment]
This does a bad job at discouraging greytiding as they will simply click 5 more times which isnt an issue. 

I dont see why this change is needed.

**Comment by MegaEmpirical** [comment]
Okay, lets double it then

**Pull request closed without merging**
