### PR TITLE
Fix swarmer killing AI

### PR DESCRIPTION
**Pull request by warface1234455**
Fix swarmer being able to kill AI because AI data core is a machinery now
# Document the changes in your pull request

Swarmer can no longer kill AI

# No Wiki doc because this exists

# Changelog

:cl:  

bugfix: Swarmer can no longer kill AI
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
i dont think this is right

**Comment by Hopekz** [comment]
You just forgot to space it correctly otherwise it was good to go

**Comment by ShoziOffical** [comment]
> You just forgot to space it correctly otherwise it was good to go

Nah, they should be able to kill AI because it's not organic

**Comment by ShoziOffical** [comment]
They can kill borgs anyway

**Comment by Hopekz** [comment]
> Nah, they should be able to kill AI because it's not organic

The lore team can figure out the why.
The reason you would change this is because it's overpowered in gameplay since the AI can't do anything about it.

**Comment by Hopekz** [comment]
> They can kill borgs anyway

But Borgs can fight back and move away.
I get that. It doesn't make sense for the lore aspect of it until someone makes sense of it but this is a gameplay balance change

**Pull request closed without merging**
