### PR TITLE
Makes sentient diseases less trash when they first start

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request

Sentient diseases now start with 2 stealth 2 resistance

# Changelog

:cl:  
tweak: Sentient diseases now start with 2 stealth 2 resistance
/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Much needed PR now it will feel less like a med-hud test examination for medbay.

**Comment by Sniblet** [comment]
doesn't this mean that sentient diseases are now fully safe to afk after getting the role and 8/10 times they'll still greentext

**Comment by MenacingManatee** [comment]
> doesn't this mean that sentient diseases are now fully safe to afk after getting the role and 8/10 times they'll still greentext

Possibly, but why? It wouldn't be the only midround to have essentially a free greentext, but it's just boring as fuck to afk, and heavily toes the line on breaking server rules as far as being active as an antag. Being a midround grants some leeway, but fully afk I don't think would be OK.

**Comment by Absolucy** [comment]
Good PR. Much less likely to have Joe Shmoe the assistant with 30 brute damage be your starter, who immediately bumbles into Medbay and outs your existence to the first doctor with a medhud.

**Review by ToasterBiome — APPROVED** [review]
skill issue

**Comment by Marmio64** [comment]
> doesn't this mean that sentient diseases are now fully safe to afk after getting the role and 8/10 times they'll still greentext

nightmares can just jaunt into a maint room and sit there for the entire round and still 'greentext' but they dont because its boring as fuck and the possibility of fun outweighs the possibility of death

**Pull request merged**
