### PR TITLE
Local fool who doesn't know how to sprite attempts to make tool sprites less jank + overhauls

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
This PR attempts to improve several sprites by tweaking many tool sprites added in #21009 and bringing some old ones up to date with them. Many (not all) of the new tools are off-putting, and there are many inconsistencies that I'll try to fix here.

Why am I doing this? Three reasons:
I gave myself some time to get used to it, and I like some of the new tool stuff, but a lot of it looks quite bad
I have heard next to zero positive reception to most of the tool changes, excluding a few outliers
Some things are out of place and inconsistent with the new sprite update, I'll also try to fix those errors in addition to the main changes here

# Why is this good for the game?
I'm not against change and new sprites, but a lot of them look bad, and not everyone is happy with them.

How are they bad??
- They're too shiny
- The screwdriver's tip is too thick
- Welders have ASS
- The caravan/experimental tools still use the old sprites and aren't centered
- The old experimental welder was fine
- Fire extinguisher cabinets use the old extinguisher sprites, and there's no sprite for foam extinguishers in there (easy to add)
- Inducer cell overlay uses a different sprite for power cells that doesn't match ours

# Testing
I'll load up tests later to make sure it looks okay in practice

# Spriting
<details><summary><b>Current sprites for comparison (everything I plan to change)</b></summary>
<p>

Screwdriver
image image image

Wrench
image image image image

Crowbar
image image image image image

Wirecutters
image image image

Welder
image image image image image

Multitool
image image image

Misc
image
image
image (Inducer battery overlay)
image image

</p>
</details>

<details><summary><b>New sprites (will be updating as work progresses)</b></summary>
<p>

Screwdriver
image

Wrench
image image image

Crowbar
image image image image

Wirecutters
image image

Welder
image (Revert cause the old one was fine)

Multitool

Misc
image (Credit to @SapphicOverload for the design)
image
image (Inducer battery overlay)

</p>
</details> 

IMPORTANT NOTES:

Unless I die, I'm planning to overhaul the experimental and brass tools later in separate PRs. I'll do some minor updating here though for consistency's sake.

And everything is subject to change based on zeus' ire, the alignment of the stars, the level of the tide, and YOUR FEEDBACK! :)

# Changelog

:cl:  AMyriad, SapphicOverload
wip: There's a lot more to be done and I have PLANS
tweak: Tweaked certain sprites to be more consistent
imageadd: Updated numerous tool sprites to be less jank, and added some new ones
imagedel: Replaced several old sprites
/:cl:

### CODE REVIEW

**Comment by ofscarletdreams** [comment]
image????s

**Comment by AMyriad** [comment]
> image????s

Dropdown menus here:

image

**Comment by iamthesilly** [comment]
The crowbars look very dull compared to the other tools.

**Comment by iamthesilly** [comment]
Wrong button

**Comment by Yarinoi** [comment]
> The crowbars look very dull compared to the other tools.

agreed, i like the current version
also, can you fix the extinguisher sprites being switched for some reason?

**Comment by Cartlord** [comment]
I agree that your crowbars look odd, but that's mostly just in comparison to your other sprites - it's like an awkward middle ground between old-school crowbar sprites (which i do prefer) and the "new" tool sprites.

**Comment by ToasterBiome** [comment]
reopen when work continues

**Pull request closed without merging**
