### PR TITLE
rebases to citadel

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# General Documentation

### Intent of your Pull Request

god bless the united states of america

### Why is this change good for the game?
increases player agency by increasing our customization

# Changelog

:cl:  
rscadd: rebase to citadel
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
jesus fuck it's been like 2 fucking minutes

**Comment by ToasterBiome** [comment]
Sounds good

**Comment by Mqiib** [comment]
mm yes more player choice, perhaps we should re-add plasma vessels to polysmorphs

**Comment by Marmio64** [comment]
fuck you

**Comment by ghost** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by Cartlord** [comment]
But why?

**Comment by wraith-54321** [comment]
if you have to ask you dont get the... because yes

**Comment by overlord12345** [comment]
based

**Comment by ghost** [comment]
why hasn’t this been merged yet

**Comment by Reed0506** [comment]
i thought we were going to rebase to bee?

**Comment by MrAsbestos** [comment]
you see having players fap to their computers to 32x32 pixel sprites is a more effective way to get more players at the cost of our humanity and sanity, this PR is totally perfect, do it boys!

**Comment by Bibby0110** [comment]
comment

**Comment by patpol4** [comment]
what

**Comment by SomeguyManperson** [comment]
due to overwhelming negative feedback the rebase is cancelled :((

**Pull request closed without merging**
