### PR TITLE
Removes filling fire extingushers with chems

### PR DESCRIPTION
**Pull request by alexkar598**
ive given up trying to put words on my PRs, its just a coin flip if it gets merged or not anyways. if you cant see why allowing something that wasnt designed around being refillable in mind is a bad idea, i cant help you.

Hurr durr how do i put chems on people??? You use a spray cleaner or a medical spray

:cl:  
rscdel: You can no longer fill fire extinguishers with random chems
/:cl:

### CODE REVIEW

**Comment by burn1cycle** [comment]
It was nerfed before for good reason. I'm not sure what the thinking was for bringing it back because it was going to give chem coders a hassle to nerf over powered chem sprays that were previously limited to a few items.

**Comment by maxion12345** [comment]
Does this also mean you cannot refill them with water?
What about advanced extinguishers that use chems in them (firefighting foam)?

**Comment by alexkar598** [comment]
Normal extinguisers need to be refilled using water tanks, the advanced ones need to be refilled using foamtanks which are currently only available from cargo which seems like an oversight but thats out of scope.

**Comment by Moggram** [comment]
> 
> 
> Normal extinguisers need to be refilled using water tanks, the advanced ones need to be refilled using foamtanks which are currently only available from cargo which seems like an oversight but thats out of scope.

ummmm... advanced can be refilled whit just water tanks.

**Comment by alexkar598** [comment]
Nope! They require foamtanks which are only available at cargo. Unless you refill it by hand using a beaker/syringe

**Comment by Marmio64** [comment]
nobody even does creative stuff with it, they just fill it with synthflesh/styptic and spam click on anyone who doesn't have full health

**Review by JamieD1 — APPROVED** [review]

**Comment by Moggram** [comment]
@alexkar598 just tested it a water tank.

**Comment by alexkar598** [comment]
bug moment, dont really care tho

**Pull request merged**
