### PR TITLE
You can no longer circumvent the permissions system to activate buildmode using proc calls

### PR DESCRIPTION
**Pull request by Amelia0010**
seems pretty self-explanatory to me

### CODE REVIEW

**Comment by Oakboscage** [comment]
Could you explain it to me?

**Comment by alexkar598** [comment]
This PR was made specifically made to nerf me

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Finally, a new challenge

**Comment by Bibby0110** [comment]
While nobody should be doing this, having the possibility is still nice, it allows regular admins to access build mode to fix griefers if no primary admins+ are online.

But this is fine I guess, maybe it will make Alexkar stop whining.

**Comment by alexkar598** [comment]
I wasent the one to bring it up

**Comment by Bibby0110** [comment]
HMMMMMMMM doubt

**Comment by DLCabbose** [comment]
Lame

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
