### PR TITLE
Scrubber and Huge scrubber are now buildable, also make them upgradable

### PR DESCRIPTION
**Pull request by warface1234455**
There's no way to make these which is suck

# Document the changes in your pull request
Scrubber and Huge scrubber are now buildable and upgradable
Scrubber construction requirement: 5x laser, 5x cable, 1 diamond (WHY diamond? Because i dont wanna see people spamming these around station)
Huge scrubber construction requirement: 10x laser, 10x cable, 10 diamond

The better lasers, the faster it would suck gas in

# Wiki Documentation

Scrubber and Huge scrubber are now buildable and upgradable
Scrubber construction requirement: 5x laser, 5x cable, 1 diamond
Huge scrubber construction requirement: 10x laser, 10x cable, 10 diamond

The better lasers, the faster it would suck gas in

# Changelog

:cl:  
tweak: Scrubber and Huge scrubber are now buildable and upgradable
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
does this mean they are upgradable now?

**Comment by ShoziOffical** [comment]
> does this mean they are upgradable now?

no

**Comment by ShoziOffical** [comment]
maybe i could make them upgradable

**Comment by bruhlookatthisdood** [comment]
do it

**Comment by ShoziOffical** [comment]
> do it

there

**Comment by bruhlookatthisdood** [comment]
is it gonna be better with better lasers now?

**Comment by ShoziOffical** [comment]
> is it gonna be better with better lasers now?

yes, the better faster gas will be sucked in

**Comment by bruhlookatthisdood** [comment]
feel like these should be locked behind industrial engineering

**Comment by ShoziOffical** [comment]
> feel like these should be locked behind industrial engineering

industrial or base, its gonna be the same thing, it will get unlocked anyway

**Comment by JamieD1** [comment]
Nope, too strong to be made. Sorry

**Comment by ShoziOffical** [comment]
> Nope, too strong to be made. Sorry

Yeah you're right it's fine

**Pull request closed without merging**
