### PR TITLE
allows you to find shock touch in ethereals but also keeps its normal recipe

### PR DESCRIPTION
**Pull request by boodaliboo**
it works like firebreath and lizards only findable with them but anyone can use but this also keeps its normal crafting of insulated + radioactivity incase you want to go the longer route
#### Changelog

:cl:  
rscadd: eletrical creatures should have this already
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
ethereal powercreep

**Comment by Tipy1802** [comment]
Just wanted to say I appreciate you touching up genetics since it and viro are one of the jobs that really need a rework

**Comment by Hopekz** [comment]
Neat now etherials have stun baton hands

**Comment by boodaliboo** [comment]
> Just wanted to say I appreciate you touching up genetics since it and viro are one of the jobs that really need a rework

no problem my idea of balancing and adding on to the stuff is adding significantly more variety so that its harder to find exactly what you want but allows you to get cool things instead of just hulk now you can get thick skin and extendo arms

**Review by Hopekz — APPROVED** [review]
Well, no negative response can always revert if people don't like it afterward.

**Pull request merged**
