### PR TITLE
Reworks meta medbay (Old)

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Reworks meta medbay, featuring 2 patient rooms that double as surgery rooms, a locker room holding paramedic and doctor gear, a paramed room conected to medbay, a genetics reception window, and lots of decals. Should more or less work, though there are bound to be some issues.

# Images

image

# Wiki Documentation

Map images. 

# Changelog

:cl:
tweak: reworked meta medbay
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Paramed lockers and suit hidden away from the parameds, floor decals seem a bit inconsistent (see normal box medbay, meta atmospherics, the entirety of gaxstation)

I love the use of the new trims I ported though, very nice. 

Can go over with Jamie soon.

**Comment by Cartlord** [comment]
why are there more op tables than stasis beds

**Comment by VaelophisNyx** [comment]
because they want to nerf stasis in a different PR so people use the OR tables :|

**Comment by nmajask** [comment]
> why are there more op tables than stasis beds

Because it's like that on literally every other playable map. The only time it is different is for maps designed for higher pop which needs more because there are more players.

**Comment by JamieD1** [comment]
Under Review with Baiomu

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
- more cryo beakers
- trim
image

- storage is kinda ugly and 1 tiles width because of the tables
- paramed lockers are in medical storage instead of paramed area
- don't know how i like this area
image
- trims here again
image
- don't know how much i like security getting into their area from outside of the department
- Can you update the trim in virology sat too?

**Comment by nmajask** [comment]
> * more cryo beakers

There were some in the back storage room, but i just moved them over

>     * trim

Fixed

>     * storage is kinda ugly and 1 tiles width because of the tables

Tried to rearrange it, dont know if this is any better
image

>     * paramed lockers are in medical storage instead of paramed area

The locker room was intended to be for both paramedics and doctors, but i move it back into the paramedic staging area anyways
image

>     * don't know how i like this area

Don't know what is wrong with it, so i tried adding glass to prevent bumping
image

>     * trims here again

Fixed

>     * don't know how much i like security getting into their area from outside of the department

Not sure what I could do about that, maybe switch the front desk with it and have the front desk be accessible only to paramedics?

>     * Can you update the trim in virology sat too?
Done
image

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image

**Review by ToasterBiome — APPROVED** [review]
fine enough just gotta wait for Jamie to look at it

**Comment by nmajask** [comment]
New PR [here](https://github.com/yogstation13/Yogstation/pull/14848)

**Pull request closed without merging**
