### PR TITLE
Preternis Changes version 2 

### PR DESCRIPTION
**Pull request by Marmio64**
- [ ] Try to make oil show up from bleeding, unlike other species exotic bloods, right now it is just invisible.
- [ ] Try to fix low fuel mode not slowing you down
- [ ] See about finishing a unique preternis stomach maybe.
- [ ] Other stuff?

My goal is to make preternis more unique, and also make them a more high maintenance species but get more upsides. They will have unique blood (oil), HAVE to drink welding fuel or be slowed down (possibly other side effects), they won't be rad immune, they start with a cybernetic liver (which is better than a normal one, but not much), and they won't have to deal with increased brute damage. Also oil is now a amber color, might even make it black, since I have never heard of pink oil.

Making this a draft to get thoughts on changes.

#### Changelog

:cl:   
tweak: many preternis changes
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
-They will have unique blood (oil),
Don't care
-HAVE to drink welding fuel or be slowed down (possibly other side effects),
Hate
-they won't be rad immune,
Hate
-they start with a cybernetic liver (which is better than a normal one, but not much),
Don't care
-and they won't have to deal with increased brute damage.
Don't like
Nice job!

**Comment by jcatjmeow** [comment]
> -they won't be rad immune,
> Hate

powergamer lol

**Comment by MegaEmpirical** [comment]
Something horrible I've always thought would be funny: when cloned, they come back as a human.

**Comment by Bibby0110** [comment]
> > -they won't be rad immune,
> > Hate
> 
> powergamer lol

lol

**Comment by Moggram** [comment]
>Unique blood. (oil)

Can vampires still drink our blood like how a changeling can eat our DNA even if we don't have it? If so, cool.

>Drink welding fuel or be slowed down (possibly other side effects),

I am ok whit this so long as beer works to. "Alcohol recharges my fuel cells, smoking just makes me look cool." -Bender
Keep the low fuel slowing us down but if you run out, you die.

>Won't be rad immune.

Ok, but I want to be immune to flash/welding so I don't go blind trying to fix myself.

>Start with a cybernetic liver and stomach.

This is a good trade for the fuel mechanic.

>Removing 1.25 brute damage mod.

This does not need to be removed. Don't get hit bro.

**Comment by UselessTheremin** [comment]
marmio, slowdown makes me cry. please do not do this. :(

**Comment by Marmio64** [comment]
> marmio, slowdown makes me cry. please do not do this. :(

you only get a slowdown with fuel loss. It is either slowdown or death.



> > Unique blood. (oil)
> 
> Can vampires still drink our blood like how a changeling can eat our DNA even if we don't have it? If so, cool.
> 
> > Drink welding fuel or be slowed down (possibly other side effects),
> 
> I am ok whit this so long as beer works to. "Alcohol recharges my fuel cells, smoking just makes me look cool." -Bender
> Keep the low fuel slowing us down but if you run out, you die.
> 
> > Won't be rad immune.
> 
> Ok, but I want to be immune to flash/welding so I don't go blind trying to fix myself.
> 
> > Start with a cybernetic liver and stomach.
> 
> This is a good trade for the fuel mechanic.
> 
> > Removing 1.25 brute damage mod.
> 
> This does not need to be removed. Don't get hit bro.

brute damage mod makes no sense, and flash immunity/welding immunity may be too powerful, i'd have to nerf preternis somewhere else then. Alcohol, maybe? Don't know how i'd do it besides maybe making the drunk status effect give fuel. If vampires can drink ethereal blood then they should be able to drink preternis blood, i'd have to check

**Comment by Moggram** [comment]
> brute damage mod makes no sense, and flash immunity/welding immunity may be too powerful, i'd have to nerf preternis somewhere else then. Alcohol, maybe? Don't know how i'd do it besides maybe making the drunk status effect give fuel. If vampires can drink ethereal blood then they should be able to drink preternis blood, i'd have to check

   From the top.
>brute damage mod makes no sense

We have the damage mod because we have the cyborg language. I am ok whit this.


>flash immunity/welding immunity may be too powerful, i'd have to nerf preternis somewhere else then.

We got the burn mod and death by EMP for rad immune. Radiation is a slow death and it is hard to find protection form it.
Flash/welding protection can be found all over the station. Only sec, rodo, and some heads will have a flasher. (oh ya, engineering can get one to) Seems like a good trade off to me.


>Alcohol, maybe? Don't know how i'd do it besides maybe making the drunk status effect give fuel.

    if(H.drunkenness <=1)
        fuel = clamp(fuel + drunkenness)
        if(H.fuel <=PRETERNIS_FUELLEVEL_WELL_FED 450)
            drunkenness =0

(I think this will work, if not or its shitcode then disregard)
My thoughts about Alcohol is it should not be as good as fuel. Up to you.

**Comment by MegaEmpirical** [comment]
Not being immune to flash seems more like a sensible trade off for being able to heal yourself.

Also, this would make you completely immune to revs and other effects. Whereas plasmamen are only immune because of their helmet. 

Not a fan of the flash proof on the actual race.

**Comment by Sniblet** [comment]
One of the things I like most about preternis is that I can keep annoying speed hindrances like hunger and wounds off my back without much downtime, as long as I have the stuff on me. It’s not about the speed making me robust in combat - I expect to lose in a fight because I take 125% damage and medicine doesn’t work on me, and anyone targeting me specifically brought dissonant screech or EMP kit or EMP spell or Disable Technology or the ion setting on their X-01.
This PR undoes all of that in the dumbest ways for reasons I just can’t comprehend.
Mass amounts of welding fuel take up much more space and are much harder to get on average than one highcap cell. More maintenance. This is what I come to preternis to avoid.
Wearing a radiation suit around the SM is a chore and a pleasure to skip, but that’s going too. Preternis don’t _have_ genes. Why would they get radiation poisoning? What’s getting poisoned? Their circuits? You mean like cyborgs? I suppose that’d be fair if they had a much lighter aluminum or something frame, but, no, they have no brute weakness now. They just, get irradiated, because... I don’t like atmos techs being them? Because I have to take something away for some reason?
Their blood type is oil? They already can’t regenerate their blood and rely on transfusions, you’re making that even harder on the race that used to pretty much center around being low maintenance? _Why should they 180 from that?_
What good is a cybernetic liver when they already have an automatic reagent purge and aren’t going to be eating poisoned anything? Let’s not forget, either, that any preternis who actually for some reason wants a basic cyberliver can literally put it in themselves with minimal issue, right now, as is. Is this your idea of a buff?
Like what is this? What are you doing? What’s the angle? Do you know what a preternis is?

**Comment by Marmio64** [comment]
> One of the things I like most about preternis is that I can keep annoying speed hindrances like hunger and wounds off my back without much downtime, as long as I have the stuff on me. This PR removes both of those (mass amounts of welding fuel take up much more space and are much harder to get on average than one highcap cell) and also means wearing a radiation suit around the SM for a little extra jab.
> Preternis don’t have genes. Why would they get radiation poisoning? What’s getting poisoned? Their circuits? You mean like cyborgs? I suppose that’d be fair if they had a much lighter aluminum or something frame, but, no, they have no brute weakness now. They just, get irradiated, because... I don’t like atmos techs being them.
> Their blood type is oil? They already can’t regenerate their blood and rely on transfusions, you’re making that even harder on the race that used to pretty much center around self-sufficiency?
> What good is a cybernetic liver when they already have an automatic reagent purge and aren’t going to be eating poisoned anything?
> Like what is this? What are you doing? What’s the angle? Do you know what a preternis is?

you don't need mass amounts of fuel, it is going to be draining at the same rate of power if not less, right now it was set to really high since i was using it for testing purposes but never changed it yet.  Radiation can break apart and cause current leakage in circuitry. Oil is easy to make in chemistry, and doesn't require exact 'bloodtypes'. It also allows you to easily drink any oil you find to regenerate blood, and you can literally scoop up oil from motor oil piles around the station to drink. Automatic reagent purge only takes effect after 20 cycles or so, upgraded livers increase the capacity at which you can totally ignore poisons. Normal livers can instantly remove toxins at 3 units or below, while cybernetic ones can remove toxins at 3.3 units or below, and cybernetic ones take less damage from poisons and alcohol. Cybernetic liver is not supposed to be a major buff or anything noticeable. Yes I know what a preternis is, and the angle is to make them seem more robotic, since they're these all metal machine looking guys that are just humans but they weld and wire their skin instead of using normal medicine. Anyways, i'll likely close the PR soon since nobody seems to like having to worry about radiation and going to a fuel tank for a sip every once in a while.

**Comment by Marmio64** [comment]
> One of the things I like most about preternis is that I can keep annoying speed hindrances like hunger and wounds off my back without much downtime, as long as I have the stuff on me. It’s not about the speed making me robust in combat - I expect to lose in a fight because I take 125% damage and medicine doesn’t work on me, and anyone targeting me specifically brought dissonant screech or EMP kit or EMP spell or Disable Technology or the ion setting on their X-01.
> This PR undoes all of that in the dumbest ways for reasons I just can’t comprehend.
> Mass amounts of welding fuel take up much more space and are much harder to get on average than one highcap cell. More maintenance. This is what I come to preternis to avoid.
> Wearing a radiation suit around the SM is a chore and a pleasure to skip, but that’s going too. Preternis don’t _have_ genes. Why would they get radiation poisoning? What’s getting poisoned? Their circuits? You mean like cyborgs? I suppose that’d be fair if they had a much lighter aluminum or something frame, but, no, they have no brute weakness now. They just, get irradiated, because... I don’t like atmos techs being them? Because I have to take something away for some reason?
> Their blood type is oil? They already can’t regenerate their blood and rely on transfusions, you’re making that even harder on the race that used to pretty much center around being low maintenance? _Why should they 180 from that?_
> What good is a cybernetic liver when they already have an automatic reagent purge and aren’t going to be eating poisoned anything? Let’s not forget, either, that any preternis who actually for some reason wants a basic cyberliver can literally put it in themselves with minimal issue, right now, as is. Is this your idea of a buff?
> Like what is this? What are you doing? What’s the angle? Do you know what a preternis is?

can you like, not edit your comment and instead just post a new comment instead of making it hard to know when you've responded. And once again, cybernetic liver is not supposed to be anything noticeable but to make them be less human, since they've been augmented to such a point where they aren't human. And, once again, oil is fucking easy to get and is a buff to preternis if anything, and makes them more self sufficient. No more having to go to medbay after an injury that made you lose a fifth of your blood, just drink oil off the floor or something.  If you really want low maintenance, podperson exists and does a better job at being low maintenance than preternis, considering they automatically heal and feed themselves so long as you are in the light, which is easy to produce. Anyways, I am closing this since nobody has really liked the idea so far and I will respect their wishes to not have it in the game.

**Pull request closed without merging**
