### PR TITLE
Some changeling changes

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Since lesser form was nerfed to shit by increasing it DNA and chemical cost, i slightly buffed it by allowing to use armblade while in monke form.

Also now when prying an airlock open lings have 1% chance to say "Heeeeeeeeeerrre's Johnny!" phrase.

# Changelog

I ded

:cl:  
rscadd: Allows to use armblade while monke
rscadd: Lings have 1% chance to say "Heeeeeeeeeerrre's Johnny!" when prying airlocks open
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
if it was nerfed it was nerfed for a reason??

**Comment by ghost** [comment]
It was nerfed too hard, so now i don't imagine a person who will use this shit

**Comment by Runian** [comment]
why add the phrase?

**Comment by ghost** [comment]
> why add the phrase?

For fun. But i can remove it if you want.

**Comment by JamieD1** [comment]
Nahhhhhh

**Pull request closed without merging**
