### PR TITLE
Ghosts can now examine pipes and canisters to see their contents

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Ghosts can now examine pipes and canisters to see their contents

#### Changelog

:cl:  
rscadd: Ghosts can now examine pipes and canisters to see their contents
/:cl:

### CODE REVIEW

**Review by monster860 — CHANGES_REQUESTED** [review]
change it to do it on /examine for ghosts

**Comment by JamieD1** [comment]
> change it to do it on /examine for ghosts

REEEEE

**Comment by JamieD1** [comment]
Fixed!

**Review by monster860 — CHANGES_REQUESTED** [review]
but with a ghost check for yser - you don't want just anyone to be able to examine pipes and canisters.

**Review by monster860 — DISMISSED** [review]
still needs a typecheck

**Comment by LemonInTheDark** [comment]
Don't ghosts have gas scan?

**Comment by Xoxeyos** [comment]
> 
> 
> Don't ghosts have gas scan?

Gas scan doesn't work on pipes.

**Comment by JamieD1** [comment]
> > Don't ghosts have gas scan?
> 
> Gas scan doesn't work on pipes.

Or canisters

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
