### PR TITLE
Nukie shield texture update

### PR DESCRIPTION
**Pull request by GDRdev**
# Document the changes in your pull request

Changes the sprite of the nukie shield suit to be a tad different

# Spriting
Fullsheildsuit
NukieSheildHelm-export
sheildhelmcombat
heldsheild
wearingsheildhelm2
wearingsheildhelm1

# Changelog
:cl:  
wip: The textures for wearing the helm is a bit fucked and therefore shouldnt be merged yet
imageadd: New Nukie Shield Textures
/:cl:

### CODE REVIEW

**Comment by GDRdev** [comment]
to note the bugs are
- The helm goes right to eva instead of combat (texture wise making a desync with what it shows and what it actually is)
- The icon for the helm is missing
- Once trying eva it completely breaks the helm forcing you to get a new one if you want the shitty textures

**Comment by GDRdev** [comment]
the bug of toggling eva still yet remains however I fixed the icon for the helm

**Comment by GDRdev** [comment]
imma see if I can fix this issue by swapping things around a bit

**Comment by GDRdev** [comment]
Looks like the combat/eva system is just not working

**Comment by GDRdev** [comment]
"The helm goes right to eva instead of combat (texture wise making a desync with what it shows and what it actually is)" by the looks was not a desync and it just broke it for some reason

**Comment by GDRdev** [comment]
new weird thing! a different kind of "Once trying eva it completely breaks the helm forcing you to get a new one if you want the shitty textures" bug has appeared! it now uses the classic nukie suit instead of the new shielded helm

**Comment by Xoxeyos** [comment]
Looks rad, might be interesting to see some slight particle effects in between the shield anchorages.

**Comment by ToasterBiome** [comment]
Reopen when done

**Comment by Yarinoi** [comment]
im only a nukie after all..

**Pull request closed without merging**
