### PR TITLE
emergency layer of anticringe

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# General Documentation

### Intent of your Pull Request

small layer of hyperspace around the bluespace locker in case someone somehow manages to get out of it

:cl:  
bugfix: slightly harder to break out of the simulation
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
cring

**Comment by patpol4** [comment]
You sure you mapmerged this? The code diffs are weird

**Comment by ChesterTheCheesy** [comment]
YOU UNDERESTIMATE MY POWER!

**Comment by redmoogle** [comment]
> 
> 
> You sure you mapmerged this? The code diffs are weird

keys likely got regenerated, map diff looks fine

**Review by patpol4 — APPROVED** [review]
Right

**Pull request merged**
