### PR TITLE
adds a slugcat plushie

### PR DESCRIPTION
**Pull request by thegoldencat413**
# Document the changes in your pull request

adds slugcat (catslug) plushie to vendors and donator items

the sprite is loosely based on the abductor plushie and the inhand is loosely based on the blahaj sprite 
# Why is this good for the game?
new plushies probably can't hurt, I really would like one, I guess it could be construed as bloat but reception was pretty positive
a couple people said it might be too big and cover antagonist gear, so i made it smaller, hopefully small enough to be okay
# Testing
tested locally and everything works I think

# Spriting
image
image
image
image
image

# Wiki Documentation

shouldn't be anything other than it being added to the vendor contents
Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. -->

# Changelog

:cl:  
rscadd: added slugcat plushie

imageadd: added sprites for slugcat plushie and inhands

/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
I cant wait to cut out the stuffing and put a minibomb inside

**Comment by thegoldencat413** [comment]
artificer

**Review by ynot01 — APPROVED** [review]

**Comment by cuackles** [comment]
image
what has been done to shark ? seems identical

**Comment by MajManatee** [comment]
why do plushies have a gender variable anyways.

**Review by ToasterBiome — APPROVED** [review]

**Comment by LoliconSlayer** [comment]
> image what has been done to shark ? seems identical

The facing forward sprite got moved up a few pixels

**Pull request merged**
