### PR TITLE
New EclipseStation bar variants

### PR DESCRIPTION
**Pull request by MrHorizons**
Since my last PR (#9072) to replace the EclipseStation bar with something more unique was rejected due to:
image

I undertook a project to create a set of original variants based off the original PR. I initially did this in about a week or so, but it's taken me until now to do it simply because I forgot three lines of code (thanks, Nich), which resulted in it just not working. But now that it does work, it has become time for me to unleash it upon the world.

Currently, there are six Eclipse bar templates, starting with a default inspired by the default Box/"Citadel" variant.

<details>
<summary>Eclipse/Default</summary>

image

</details>

Along with five other variants, two of which unique to Eclipse:
<details>
<summary>Beach</summary>

image

</details>
<details>
<summary>Casino</summary>

image

</details>
<details>
<summary>Clockwork</summary>

image

</details>
<details>
<summary>Disco</summary>

image

</details>
<details>
<summary>Western/Saloon</summary>

image

</details>

I know that these are fewer in number than Box's variations, but I did so to be able to make sure their quality was better since I am still but a mortal. If anyone would like to add more variants, I negligently left in the blank template for the bars under `ebar_blank.dmm`.

Also, I'd like it if any feedback is marked towards either a specific variant or all of them so I don't have to figure out from context or just trial and error.

#### Changelog

:cl:  
rscadd: Adds a brand new set of primary bar and kitchen variants to EclipseStation.
tweak: Shifts around some maintenance tunnels and loot spawners on EclipseStation.
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
... weird, it converted to TGM on its own. I won't object.

**Review by patpol4 — CHANGES_REQUESTED** [review]
I really like the beach one, just glanced this over for now and will do a full review later. You used the old firelocks in the kitchen area instead of the new monstermos ones, also you included like 4 generic event spawners in each variant, maybe keep it at two per template instead? One for bar one for kitchen

**Comment by MrHorizons** [comment]
@wejengin2 Well, the normal kitchens use the old firelocks, but it does make sense you'd want me to use the monstermos ones. At a later point, I could make a PR to replace the other kitchens' firelocks with monstermos ones. I can definitely cut down on the number of event spawners, too.

Personally, I quite like the beach bar as well, but I found out that a part of it near the middle is rather dark, so I'll use your changes to sneak in a few lighting tweaks.

**Review by patpol4 — CHANGES_REQUESTED** [review]
I Eclipse and general:
1. Stray areas on the eclipse map in the clown place
2. Bananaphone
3. Clown place apc is wrong
4. What's up with these areas, maybe leave just the theatre one on the door?
chrome_10TUSTVliu
5. Please dont put lights on glass
chrome_kV8ZhsNgqZ
6. I really like how bar sign on glass looks 
dreamseeker_NMuPsE4IZZ
7. No firelocks on kitchen cold room door
8. Blast doors for kitchen is overkill, use shutters
9. I don't like how when you walk into the kitchen the big oil tank blocks your path, might be hard to move but could you try something so it's not a 1 tile walkway, same for the left part. Maybe remove one of the meathooks?
chrome_mXxNSfVI7R
10. Regarding kitchen closets, there should be freezer/kitchen and freezer/fridge, confusing and stupid naming i know, see box kitchens for reference
11. Kitchens use bowl grinders now
12. Check pipes for things like this, easiest way would be to boot up a private server and do admin tab > current logs > map errors (ignore the apc errors, look just for pipenet errors)
chrome_7gq50H1Oxl
13. Bar backroom has no air alarm.
14. Idk if we need a blank variant but it was useful for reviewing this, i guess its up to ktl
General part is overi think, now i will look over the variants themselves

**Review by patpol4 — CHANGES_REQUESTED** [review]
II Beach
1. Firelock near bartender entrance, either remove it all or encase the bartender place with it
2. This is more centered
chrome_KZghKodjBm

III Disco
1. That's a lot of bouncers

IV Casino
1. Christmas tree in the casino?
2. Add uno and turn tracker
3. Fill this part up a bit so its not so empty
chrome_pxECJ3xiSf
4. That's way too much cash for a bartender, also put some in a safe.

V Clock
1. You didnt include the armor sets and clocks for people&bartender

VI
1. It's soo empty, try spreading the tables out a bit maybe? 
chrome_MKWQbdKO17
2. Another xmas tree

VII Eclipse
1.If you put down a basketball hoop make sure to include a basketball
2. It's always better if pipes don't go under objects when its possible
chrome_EoY7ZZZOTw

VIII Saloon
1.A more public piano would look really good
2.Yeehaw

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
- Remove a bar APC as there's 2 now
- The bartender and kitchen disposals don't link to the disposals loop in maint
- Make the kitchen + cold room all one area. Alternative would be to add another APC for the cold room, but since it's since a small room making it all one area is preferred
- For the bars without a theatre area, change the north bar camera c_tag as it's currently "theatre stage"
- Bar backroom camera needs adding
- Kitchen camera needs adding
- Add plating under the bar backroom maint airlock and theatre maint airlocks
- Make these disposals straight
image
- Remove a theatre RC
- The camera in the theatre has c_tag "Theatre Storage", needs changing to "Theatre"
- Don't need a blank variant
- Casino variant makes the dorms light switch appear over a window
- Arcade machine(s) in the casino variant would be nice (optional)
- The rack in bar maint needs moving as it blocks the bar delivery flaps
- Space turfs are currently under the bar sign (clock)
- For the variants with a theatre stage, make the walls connecting the bar+theatre have theatre areas instead of bar areas
- Add a wall under the smart-fridge (botany/kitchen)
- Change the Birdboat bed to a new bed in bed.dm instead of editing it on the map

**Comment by MrHorizons** [comment]
... MapDiffBot, what?

**Review by patpol4 — APPROVED** [review]
Idk about the speedbike but my requested changes are done

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
Remove the speedbike then this is fine to merge.

**Comment by MrHorizons** [comment]
I've set the speedbike to be anchored in place, so I think it should be fine.

**Comment by MrHorizons** [comment]
> Idk about the speedbike but my requested changes are done

> Remove the speedbike then this is fine to merge.

@Ktlwjec1 The speedbike is anchored, so it _shouldn't_ move, which I imagine would be the worst part of having one. However, to be safe, I have also set `max_drivers` to 0, which means that, while people can get in, they shouldn't be able to drive it even if unanchored.

**Review by Ktlwjec1 — APPROVED** [review]
It was rideable when just anchored, this is fine now.

**Pull request merged**
