### PR TITLE
Mirror on your hand

### PR DESCRIPTION
**Pull request by warface1234455**
place the mirror on the wall

# Document the changes in your pull request
you can now craft mirror and put it on wall using 1 silver, 1 rod and 1 glass

# Wiki Documentation
* document of changes

# Changelog

:cl:  
rscadd: you can now craft mirror and put it on wall using 1 silver, 1 rod and 1 glass
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
Give atmos a chem dispenser next

**Comment by ShoziOffical** [comment]
> Give atmos a chem dispenser next

this doesnt have anything to do with atmos?

**Comment by solwashere** [comment]
> > Give atmos a chem dispenser next
> 
> this doesnt have anything to do with atmos?

Almost guarantee that this derived from
1: Oh no I got irradiated and my hair changed
2: I don't want to leave my Atmos bunker and go to medbay to change it :(

**Comment by ShoziOffical** [comment]
> > > Give atmos a chem dispenser next
> > 
> > 
> > this doesnt have anything to do with atmos?
> 
> Almost guarantee that this derived from 1: Oh no I got irradiated and my hair changed 2: I don't want to leave my Atmos bunker and go to medbay to change it :(

i really dont mind being bald at all i just feel like adding this to the code

**Comment by Runian** [comment]
Feel like this should take more to make instead of needing only one piece of glass.

**Comment by ShoziOffical** [comment]
> Feel like this should take more to make instead of needing only one piece of glass.

what are your suggestions

**Comment by iloveloopers** [comment]
silver? or maybe metallic hydrogen so atmos and science can have a monopoly on mirrors

**Comment by ShoziOffical** [comment]
ok silver then

**Comment by MajManatee** [comment]
why are people not on board with... a mirror...?

**Comment by neeshacark** [comment]
I fail to see any reason to deny this, I don't know why we're losing our minds.

**Review by MajManatee — APPROVED** [review]
Mee ror

**Pull request merged**
