### PR TITLE
nerfs killer tomatos i think

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
image
morderhel did the math tell me if its wrong
#### Changelog

:cl:  
tweak: tweaked killer tomato stats <@97786617422417920>
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
this decreases the amount of damage they do at maximum from 10 to 5 by doubling the potency required to get a higher attack damage

**Comment by Marmio64** [comment]
i don't think killer tomatoes need nerfs but i will stay neutral

**Comment by Hopekz** [comment]
This nerf is a little heavy imo

**Comment by boodaliboo** [comment]
changed it from 20 to 15

**Review by Hopekz — APPROVED** [review]
Going to let this marinate for a few more hours if no-one seems to have anything against it I will merge it.

**Comment by JamieD1** [comment]
> Going to let this marinate for a few more hours if no-one seems to have anything against it I will merge it.

Its marinated for so long is now gone off.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
