### PR TITLE
Replace roundstart PDA (2010) with PDA (2021) SECOND TRY BABYYY

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Latest commit tested & working

Everyone now starts with an NTOS PDA or variant (phone for heads, tablet for netadmin)

New program, PDA Messenger, SpaceMessenger V4.0.0 (an update to the PDA's V3.9.6)

PDA Messenger can be used to access syndicate uplink (To prevent new player confusion, the computer itself holds the uplink, not any of its parts)

NTOS PDA will be selected to hold syndicate uplink if you select "PDA" as your preferred uplink location

You will be notified of incoming PDA messages regardless of the program being active or even if the device is off, unless Ringer is silenced.

**PDA pens preserved**

**PDA donor skins preserved**

**PDA bombing preserved**

## KEY DIFFERENCES IN PDA MESSENGER

NTOS & legacy PDA servers are separate. You cannot message between them.

-

You can rename yourself very easily. Your username will start out as your real name, but you can edit it with just a click.

This is a necessity, as NTOS PDAs exist independently of IDs

-

You can now block people. Don't want Urist Tider spamming you? Block him. No more tider. He can still taunt you outside of messages though.

-

Messages have a 1 second cooldown to prevent spam, as spam would be a lot easier given how fast and easy NTOS is to use ;)

-

You can view all messages sent by providing the monitor decryption key from the message history menu (5 second cooldown to prevent brute force attacks)

## PDA BOMBING

Ordering the BomberMan program from the uplink will spawn a data disk containing it, preloaded with its code but it will tell you the code anyways in case you forget it.

The program will look like this and operates exactly how Detomatix did

# Changelog

:cl:  
rscadd: Added NTOS PDA Messenger
rscadd: Added pens to tablets
rscadd: Added BomberMan, a NTOS replacement for Detomatix, to the uplink for the same price
tweak: Replaced PDAs with NTOS PDAs
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Legendary

**Comment by Cartlord** [comment]
What will be the gain from this?

**Comment by Hopekz** [comment]
> What will be the gain from this?

Better looking
Faster
Less buggy
Much Easier to add new features
You don't need to be proficient in html to add features
You don't need to be proficient in html to rework parts
Cool battery and part system that can maybe be expanded on
Already has more apps than the 2010 PDA system
Modern
Takes us out of 2010

**Comment by ToasterBiome** [comment]
how PDA bomb now?

**Comment by ynot01** [comment]
> how PDA bomb now?

cartridges don't exist in NTOS, they're called programs

**Comment by warface1234455** [comment]
hot

**Comment by ToasterBiome** [comment]
> > how PDA bomb now?
> 
> cartridges don't exist in NTOS, they're called programs

how PDA bomb now?

**Comment by redmoogle** [comment]
> > > how PDA bomb now?
> > 
> > 
> > cartridges don't exist in NTOS, they're called programs
> 
> how PDA bomb now?

make the harddrive blow up smh

**Comment by Altoids1** [comment]
Okay but when is PDA styling going to be ported too

**Comment by Hopekz** [comment]
>  ~~Okay but~~ when ~~is PDA styling going to be ported too~~

You code it

**Comment by ynot01** [comment]
> Okay but when is PDA styling going to be ported too

there are 10 styles

1 is default
1 is NTOS
1 is syndicate
1 is abductor (bland)
the rest are vomit inducing and there's good reason you never see them

**Comment by nmajask** [comment]
~~Donor skins will probably have to be implemented if this is going to get merged, luckily there are sprites for it in #15019, if you want to use them.~~ nvm, cant read for shit

**Comment by JamieD1** [comment]
> > > how PDA bomb now?
> > 
> > 
> > cartridges don't exist in NTOS, they're called programs
> 
> how PDA bomb now?

Please answer @ynot01

**Comment by neeshacark** [comment]
i like this change but there's quite a few things that need to be done before this gets merged.  job-specific sprites for the phones would be nice though not needed.  changing the sprite in general might be a good idea, seems a bit too bricky but that might just be me.

the big one is allowing for pda bombing here, and the other big one is allowing a slot for a pen for those people who, like me, use the pen uplink.

OH and maybe add a new donor pda option which are the legacy sprites for pda

**Comment by ynot01** [comment]
> the big one is allowing for pda bombing here, 

Done

> and the other big one is allowing a slot for a pen for those people who, like me, use the pen uplink.

Done

> OH and maybe add a new donor pda option which are the legacy sprites for pda

Would be too confusing since old PDAs still exist

**Comment by ynot01** [comment]
> > > > how PDA bomb now?
> > > 
> > > 
> > > cartridges don't exist in NTOS, they're called programs
> > 
> > 
> > how PDA bomb now?
> 
> Please answer @ynot01

**Comment by Hopekz** [comment]
> i like this change but there's quite a few things that need to be done before this gets merged.  

Up to people with merge privileges to decide

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
