### PR TITLE
Stimulants stamina damage heal buff (5->30)

### PR DESCRIPTION
**Pull request by ynot01**
#### Changelog

:cl:  
tweak: Stimulants now erase stamina damage as effectively as they reduce stun times
/:cl:

### CODE REVIEW

**Comment by Takahiru** [comment]
literally an ided pr

**Comment by alexkar598** [comment]
New ided policy: No ided prs immediatly after death. Feel free to PM on Discord in 24 hours to reoopen the PR

**Comment by Hopekz** [comment]
> New ided policy: No ided prs immediatly after death. Feel free to PM on Discord in 24 hours to reoopen the PR

What are you going to make this more official somewhere or just in this comment

also; how do you even enforce knowing what's an ided PR and what's a "real" PR

**Comment by ynot01** [comment]
> New ided policy: No ided prs immediatly after death. Feel free to PM on Discord in 24 hours to reoopen the PR

lol ok

**Comment by alexkar598** [comment]
12 hours*

**Comment by Hopekz** [comment]
> 12 hours*

This was one of the most pointless temporary PR closes IMO

**Comment by Marmio64** [comment]
what is the point of temporarily closing a PR for 12 hours if you're not gonna keep it closed. It sounds very VERY pointless.

**Review by Hopekz — CHANGES_REQUESTED** [review]
Let's get a proper title

**Review by alexkar598 — APPROVED** [review]

**Review by Hopekz — APPROVED** [review]

**Pull request merged**
