### PR TITLE
Getting Shocked has a chance to cause your heart to fail

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Chance scales with damage, divided by 3.
force-contract heart-failure

# Changelog

:cl:  
tweak: Your heart does not like being electrocuted
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
Hard disagree. This lets things like the wizard lightning spell, tesla gun, tesla armour, electric grille tesla shocks, ect, have a non insignifigant chance to fuck you over in one blast. If it was a damage threshold maybe. Even then having a high wattage shocked door kill you in one shock, with no possible way to know that door was shocked is not going be a good experience.

Unless you think that everyone should now be perpetually afraid to open any airlock anywhere out of the remote chance it might be shocked is compelling gameplay?

**Comment by VaelophisNyx** [comment]
reminder that heart failure disease is not fast, thus this doesn't make anything a "one-shock-kill"
this just means you should seek insuls for hacking, you know?

**Comment by Marmio64** [comment]
Your argument seems to keep being 'just get insuls for hacking'. As it happens, getting some form of shock protection (grey bull, budget insuls, or even normal insuls) isn't very hard and the majority of hackers take the time to do so. This is really just fucking up the people who get shocked out of their control (tesla blast, rogue ai, some douche shocked their door), and i guess the people who just want to quick hack their vendor and don't want to waste 5 minutes calling for someone or getting something for the shock, which if the latter is the goal i don't think its worth it.

**Comment by VaelophisNyx** [comment]
>try to balance something
>100 people flood in from the shadows to argue against it
>yog does not change ever
>same 100 people whine that yog is old and never changes

**Comment by 00ze-cyclone** [comment]
Your change is just a random « fuck you » to anyone that get shocked for no good reasons, you haven’t given us a single reason why it should be changed.
You make random bullshit for « balance », refuse to provide a good reasons, disregard the arguments of everyone else then act like WE are the problem. Most of the people who are downvoting and commenting haven’t appeared out of thin air, they made comment and even PRs for some of them, stop acting like they are just randoms with no ideas of what they’re talking about.

**Comment by VaelophisNyx** [comment]
Hacking shouldn't be something you can just Do relatively safely. This adds a present danger to hacking, that is 100% *nullified* if you take a pair of insuls. or budget insuls. or insulated mutation. or a grey bull. or nerve grounding. or are a golem, or darkspawn. Or use remote signalers.
There are plenty of options that exist to safely hack, and the only argument against this style of change I have seen is that it makes those options needed; which is a really dumb argument to be making.
this was the -compromise- version of this, instead of globally increasing shock damage directly, or dealing straight damage to your heart. It's also *RNG*. you dont get your heart fucked ALWAYS, only on a chance that scales with the damage you took. Everyone is acting like I made EVERY SHOCK ALWAYS kill you instantly instead of 2-3 minutes down the road, when you can go to medical and get corazone, or a new heart, both things chemistry or medical will gladly do for you in 90% of cases.

**Comment by Maia-J** [comment]
Wow nice so now I am at a 10% risk of being banned for "Murderboning" as AI when I shock a lizard once. Thats like my entire asimov gimmick!

> you dont get your heart fucked ALWAYS, only on a chance that scales with the damage you took.
> Everyone is acting like I made EVERY SHOCK ALWAYS kill you instantly instead of 2-3 minutes down the road

This is exactly the reason why people dislike rng mechanics, its not like it will kill you, BUT it can kill you and most likely will kill you in a reasonable timeframe. And if it doesnt fuck over you, it may as well fuck someone else. It's just a unfairness factor directly going against any sort of balance.

**Comment by Sniblet** [comment]
> be me
> karen stahl, catgirl maint skulker extraordinare
> hop didnt want to give me access this shift so i go testing wires to get in like usual
> wrong one
> welp guess im going to medbay for a scan
> "myocardidal infarcation" drivels the random name moth working the treatment center alone
> sit through about 12 minutes of riveting gameplay on a stasis bed while i try to explain to the doctor how this works
> "if it'd just been a burn i wouldn't even have had to come here" i grumble
> grid check
> 100 valeophisnixes flood in from the shadows and i have the heart attack
> disconnect for the night
> make the revert pr this deserves

> be me
> brand new greytider fresh from goon
> ask a fellow assistant how to hack doors here, get right to work breaking into sci so i can do my funny goon things there
> hit the wrong wire
> oops haha
> get shocked again cause i didnt know the door was still electrified
> try a different one
> get into sci
> 100 valeophisnixes flood in from the shadows and i fall unconscious 4noraisin
> die
> never come back

> be me
> malf ai
> today's strategy: steal every insul, hotwire the engine, and go delta at 30 minutes
> it works just as planned, i shock everything while the login text is going
> drop potwater on the chemists at their dispensers
> delta hits, everyone starts moving, everyone hits a door
> its like lemmings
> hold the line for another five minutes
> 100 valeophisnixes flood in from the shadows and people are dropping left and right in the medbay lobby
> there are 12 people dead with 30 burn 170 suffocation on suit sensors
> post amogus on the comms console

> be me
> charlie station scientist
> somebody else has the insuls SOMEWHERE and the solars aren't done right
> drop one wire node
> shock
> well at least that means it's working
> 100 valeophisnixes flood in from the shadows and i see that heart failure message
> ghost

> be me
> super wanted traitor
> i have unfortunately been lawed as nonhuman without my knowledge
> touch door
> 100 valeophisnixes flood in from the shadows and You feel your pulse fluttering!
> uuuhhhhhhh
> well i guess that's it

**Comment by VaelophisNyx** [comment]
:\

**Comment by VaelophisNyx** [comment]
just seeing the same dumb arguments of "this makes greytiding harder!!!" and like
Yeah
why are you arguing tiding shouldn't be hard?

**Comment by VaelophisNyx** [comment]
also its not like you're unaware your heart is dying. You get big scary red text about it. And you should probably get burns treated anyway?

**Comment by Sniblet** [comment]
If tiding is supposed to be hard why do we let budget insuls exist

**Comment by VaelophisNyx** [comment]
because they are limited use items. Grey bull also exist
I'm just saying tiding shouldn't be so easy you can just ignore being shocked up to three times in a row

**Comment by Sniblet** [comment]
First: why?
And:
Is the damage not punishing enough? Does it add anything good to the game for there to also be a random chance that you fall over dead in two to six minutes? Do you think anyone involved in the process of three myocardial infarctions walking or being dragged into medbay every shift is happy about it?
Won't it be a joy next time engineering is vacant and a wire in maint gets cut, and we'll all cheer every time any silicon is rogue and medbay actually can't keep up, and Drake's going to be pushing the limits on this with advanced release teslium grenades that set the whole sec team on the road to death and you know what? Everyone involved will be laughing, they’ll all be so glad this got merged.

This game is not designed for shocks to have a random chance to give you a fatal disease.

**Comment by VaelophisNyx** [comment]
this game is barely designed to do anything that isn't atmos simulation, by that logic.
Again this was the *compromise* version of this PR. And just making this happen in one place was frowned upon, so take it up with the maints.

**Comment by Sniblet** [comment]
How about instead of a compromise you don't make shocks more lethal
You do have a choice

**Comment by VaelophisNyx** [comment]
Or I could make them more lethal and people can learn to go use the numerous ways to not be shocked? Not hard at all.

**Comment by Sniblet** [comment]
I've hinted at this a few ways but I'm not sure it's landing so let me try to be clear: just because there are mostly consistent ways to avoid a bad mechanic in the most common of the many situations where it can arise, doesn't mean it is a good mechanic
I don’t see a way that this adds anything but annoyance and frustration to the game, for anybody

**Comment by Maia-J** [comment]
> Or I could make them more lethal and people can learn to go use the numerous ways to not be shocked? Not hard at all.

Ok but imagine this: RNG mechanics suck ass and are unfair and unfun for everyone (Except gambling addicts(?))

There is more moments you can get shocked in other than blatant tiding. Fixing wires gloveless because engineers are lousy, charlie station, malf ai, teslium, etc. You cant just focus on one variable and ignore the other 10 you also affect.

**Comment by Notamaniac** [comment]
> try to balance something
> 100 people flood in from the shadows to argue against it
> yog does not change ever
> same 100 people whine that yog is old and never changes

Okay normally I would try to keep my comments to the PR at hand, but this sort of mentality actually ticks me off.

Let's go with the fabled food analogy. I complain that I'm tired of the same old dish. In the name of 'changing things up' you decide to take a shart in that dish. You should not be surprised when people complain about your new addition to the dish.

Now game design isn't exactly equal to cooking food. Some balance changes might be good for the overall health of the game, but disliked heavily (e.g. removing most sources of hard stuns, making combat overall riskier and drawn out rather than ggnore on one taser shot). Some balance changes might be liked, but terrible for the overall game (i.e. the recycler being able to print out minerals when upgraded fully). And even then we have changes that are going to be subjective based on how people play. All we can do is try to make changes that benefit the overall game, to make it either more fun, more engaging, for as many people as possible, or at least whatever the hell is meant to be the target audience for this game.

Now you might believe that adding a low chance for someone to suffer a heart attack on getting shocked by anything is 'fun and engaging'. You might believe forcing medical to deal with a heart replacement surgery every shift might be more 'engaging' for medical players. You might believe it adds 'depth' for everyone to immediately rush for insuls or grey bull if they even want to consider hacking a door/machine. You might believe that this will curb the insatiable grey tide who are constantly hacking everything, and that every person who plays a departmental role will rejoice as this grey tide suffers heart attacks and die.

But here, we have a lot of people saying no, that's not fun or engaging, they won't want to deal with an rng chance of having a heart attack. They don't want to deal with an AI who can shock every single door, with virtually no tells to see if a door is shocked or not, potentially killing them in 5 minutes if they're unlucky enough to be also bolted in the same room. They don't want to deal with teslium nade spam, or anything that could spam out tesla shocks.

Now you can continue to believe what you want to believe. I know that people will not change their beliefs, even in the face of hard evidence to the contrary.

But please for the love of fucking god, if '100 people flood in from the shadows' to tell you something is bad idea, please entertain the possibility that it might be a bad idea. It's called criticism, and acknowledging it, and adjusting your changes for valid pieces of criticism can make a bad idea into a good idea.

Or you know you can be like oranges and merge things that are heavily disliked by the playerbase and force them to adapt. I don't know anymore, I'm not someone who's interested in dealing with people who have their head up their own ass.

**Comment by JamieD1** [comment]
Makes sense though

**Comment by Maia-J** [comment]
> just seeing the same dumb arguments of "this makes greytiding harder!!!" and like Yeah why are you arguing tiding shouldn't be hard?

Ah yes, definetely arguing about that and not the fact that RNG isnt hard, its just unfair. Also you still keep forgetting that shocks dont come just from tiding (Or most likely ignoring that fact. Because why should you listen to other people's opinions). Do you have a serious dent or a superiority complex? Because so far it seems like it.

**Comment by Bibby0110** [comment]
Dumb

**Comment by VaelophisNyx** [comment]
"dumb" literal worst maintainer jesus christ

**Pull request closed without merging**
