### PR TITLE
frog pAI holoform

### PR DESCRIPTION
**Pull request by ktlwjec0**
https://github.com/tgstation/tgstation/pull/78537

Adds a frog pAI holoform.

# Why is this good for the game?
frogs are really cool so it makes our server cooler

# Testing
yes look at spriting this is what i did
# Spriting
image image image image

:cl:  xPokee
rscadd: Adds a frog holoform for pAIs.
/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]
Frogs are infact,very cool

**Comment by MajManatee** [comment]
does it have an animation for moving? or do it just glide?

**Comment by ktlwjec0** [comment]
yes icondiffbot shows it otherwise just download the file to see it

**Review by MajManatee — APPROVED** [review]
Froge

**Pull request merged**
