### PR TITLE
Implant Breaker cost have been upped to 40 points

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑
tweak: Sec now stands a slightly better chance against gangs
/🆑

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
I’d rather buy me an uzi and kill officers now instead of converting.

**Comment by GuppyLaxx** [comment]
add a rule against that
rules fix everything

**Comment by gar4** [comment]
I mean if you have them in a position to convert you can just as easily kill them. As homocidle said, if i have to spend 50 points to convert i would just as well buy and uzi and give them two bursts point blank to the head and even save a few seconds.

**Comment by fluffe9911** [comment]
Ok I lowered it to 40 but if you still decide to buy the 60 point uzi and just shoot them to death instead then thats your feken choice ye jerk

**Comment by HomocidlePancakes** [comment]
10 points is barely any diffrence. Still makes more sense to kill. Also (insert reasons why mindslave implant cost was lowered here).

**Comment by SomeguyManperson** [comment]
Fluffe you f o o l gangs doesn't have a high enough winrate to warrant being nerfed

**Comment by Codeatmos** [comment]
just remove implant breaker tbh,or not at all because "MUH GRAPHIC CHART SAYS GANG BALANCED"

**Comment by fluffe9911** [comment]
Eh screw it

**Pull request closed without merging**
