### PR TITLE
[Finally] Reworks pubby monastery into a proper space ruin and removes it from the space ruin blacklist (it will now spawn)

### LINKED ISSUE #11851: Bring pubby monastery back as space ruin
### Severity

Low

### Short Description

I said i was going to do it and then I didn't, now it's just rotting on the space ruin blacklist. this is a reminder for me to do it or else it will stay on the mapping issue list forever.

### Reproduction

1. open a map editor
2. do the thing
3. pr

### Round ID

does not apply

### Test Merges

_No response_

### BYOND Username

_No response_

### Additional information

Links for reference:
removal pr: https://github.com/yogstation13/Yogstation/pull/9301
attempt to bring it back without fixing the map: https://github.com/yogstation13/Yogstation/pull/11273

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Yes I understand this doesn't change anything on live, Jamie please update our secret config

Closes https://github.com/yogstation13/Yogstation/issues/11851

Does the thing wej said he was gonna do and reworks it into a space ruin

dreamseeker_7RMECu3U3e
dreamseeker_qKJOYk4cmp

dreamseeker_tgFEaMjPJP
dreamseeker_vCuZBwZTfU
dreamseeker_FAAO4362BM

# Changelog

:cl:  
rscadd: removes pubby monastery from blacklist
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
https://github.com/yogstation13/Yogstation/issues/11851

**Comment by ToasterBiome** [comment]
Will be adapting this to actually making the ruin work (thanks wej)

**Comment by ToasterBiome** [comment]
> #11851

shut up

**Comment by ToasterBiome** [comment]
Ok now I have adapted it

**Comment by cowbot92** [comment]
A god amongst men

**Comment by maxion12345** [comment]
does it have fire locks

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
