### PR TITLE
Nerfs Weaver Nest Guns

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑
tweak: c20r and wt550 have been replaced with a double barrel shotgun and a moss negant!
/🆑

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
|>:(

**Comment by ghost** [comment]
you're nerfing the weaker and cargo orderable wt-550 by making it a sixty damage desert fucking eagle

**Comment by fluffe9911** [comment]
well one has 30 bullets and the other has 7 but yeah I get what your saying will switch it with something else when I get back

**Comment by HomocidlePancakes** [comment]
Muh c-20r. Muh powergame

**Pull request merged**
