### PR TITLE
Echolocation for quirky blind people | TESTMERGE READY, CONFIRMED WORKING LOCAL 

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

adds echolocation for people with the blind quirk
credz to https://github.com/tgstation/tgstation/pull/43752 thanks bman

# Changelog
:cl:  
rscadd: adds echolocation for people with the blind quirk
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Pictures please

**Comment by Bibby0110** [comment]
In addition did you fix the performance problems brought up in https://github.com/tgstation/tgstation/pull/43777?

**Comment by Simplehorror** [comment]
image

**Comment by Simplehorror** [comment]
> In addition did you fix the performance problems brought up in [tgstation/tgstation#43777](https://github.com/tgstation/tgstation/pull/43777)?

no, bman did but the PR was closed anyways. he removed getflaticon and cached all the images which was the reason performance was dogshit

**Comment by Bibby0110** [comment]
> > In addition did you fix the performance problems brought up in [tgstation/tgstation#43777](https://github.com/tgstation/tgstation/pull/43777)?
> 
> no, bman did but the PR was closed anyways. he removed getflaticon and cached all the images which was the reason performance was dogshit

Put some performance measures then

**Comment by Simplehorror** [comment]
ok. td is 0 when testing locally

**Comment by Bibby0110** [comment]
> ok. td is 0 when testing locally

From a profiler

**Comment by Simplehorror** [comment]
> > ok. td is 0 when testing locally
> 
> From a profiler

before cache or after cache

**Comment by Bibby0110** [comment]
> > > ok. td is 0 when testing locally
> > 
> > 
> > From a profiler
> 
> before cache or after cache

Just measure the cpu time of each proc you're introducing

**Comment by Simplehorror** [comment]
/datum/component/echolocation/proc/echolocate                                              0.030        0.135        0.185        0.000           48
/datum/component/echolocation/process                                                      0.000        0.135        0.185        0.000           48
/datum/component/echolocation/proc/show_image                                              0.021        0.050        0.050        0.000          832
/datum/component/echolocation/proc/generate_image                                          0.003        0.047        0.047        0.000          171
/datum/component/echolocation/proc/fade_image                                              0.006        0.023        0.023        0.000          832

**Comment by Simplehorror** [comment]
also it'd be like 10x better on 515

**Comment by Bibby0110** [comment]
Doubtful about performance, check on testmerge.

**Comment by Simplehorror** [comment]
i am 100% confident this won't cause lag

**Comment by Moltijoe** [comment]
> i am 100% confident this won't cause lag

Top 10 sentences spoken moments before extreme lag

**Comment by Bibby0110** [comment]
> i am 100% confident this won't cause lag

X to doubt

**Comment by BurgerLUA** [comment]
The code looks like it will cause lag. I mean only like 1-3 people a round play blind but as someone who has dealt with BYOND, I'm seeing a lot of unoptimized code and lots of usages of icon procs.

Profiler doesn't look bad though which is surprising.

**Comment by Simplehorror** [comment]
> The code looks like it will cause lag. I mean only like 1-3 people a round play blind but as someone who has dealt with BYOND, I'm seeing a lot of unoptimized code and lots of usages of icon procs.
> 
> Profiler doesn't look bad though which is surprising.

it gets cached so it doesn't matter how bad the initial icon manipulation is

**Comment by Simplehorror** [comment]
+ the initial first few icons wont cause lagspikes because check tick and background subsystem

**Comment by neeshacark** [comment]
i never expected to love simplehorror, but this might change everything if it fucking wortks

**Comment by Simplehorror** [comment]
> i never expected to love simplehorror, but this might change everything if it fucking wortks

works on my machine

**Comment by KillerOrcaCora** [comment]
The hell am I looking at, all this time making the server look good and y’all wanna go back to black and white? Fucking unbelievable

**Comment by Bibby0110** [comment]
does the lagging

**Comment by Simplehorror** [comment]
no it doesnt

**Pull request closed without merging**
