### PR TITLE
Conditions

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

New framework for more medbay content, conditions.

Conditions will allow you to introduce conditions that are not necessarily caused by a disease, but could be idiopathic or genetic. They will have a robust framework for testing (you'll need to test for hormones, or other blood chemicals) instead of just allowing you to health scan someone.
Most conditions will probably be able to be treated with pharmaceuticals but some will require surgery, some may need cloning, etc.

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: new medbay content: conditions check the wiki
/:cl:

### CODE REVIEW

**Comment by Potototatoh** [comment]
if this is implemented good maybe itll help cut down on the amounts of time doctors end up just standing around medbay looking pretty

**Comment by Simplehorror** [comment]
i hope so

**Comment by Simplehorror** [comment]
the plan is you'll actually need to diagnose with your brain

**Comment by ReddicusDragon** [comment]
I am curious to see where this goes

**Comment by Bibby0110** [comment]
Open this when it's in a testable state

**Comment by Simplehorror** [comment]
sure but i have a feeling it'll be closed before a testmerge

**Pull request closed without merging**
