### PR TITLE
Updates armored greatcoat sprite to be red and pathologic 2-ised.

### PR DESCRIPTION
**Pull request by nesisknesis**
image
image
image
image
Security Chief Skellig after contracting a flesh-eating disease.

Old armoured greatcoat was dull.

Inspired by the Army officer from Pathologic 2 
image

#### Changelog

:cl:  Identification
imageadd: Armored greatcoat sprite updated, design inspired by Pathologic 2.
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
Hey that looks pretty cool

**Review by alexkar598 — CHANGES_REQUESTED** [review]
dont replace,just add another one

**Comment by nesisknesis** [comment]
there's no room for more clothing, it's choca block

**Comment by Firewolf34** [comment]
Yeah the HoS locker is literally so full of stuff right now that it can't close and fit all the items in it.

It needs a HoSdrobe. But if we make a HoSdrobe, then we need to make a CMOdrobe, and a RDrobe, and a CEdrobe, and then the next thing we know we'll be making QMdrobe too

I heavily suggest he just replaces it. HoS has enough gear already.

You want to give someone new apparel, do a non-sec, like CE or something. There's already a shit-ton of sec clothing.

**Comment by Amelia0010** [comment]
```
It needs a HoSdrobe. But if we make a HoSdrobe, then we need to make a CMOdrobe, and a RDrobe, and a CEdrobe, and then the next thing we know we'll be making QMdrobe too
```
1. We don't have to give other heads an autodrobe just because the HoS has em, if they don't need em.

2. Even if we did, that's not a bad thing.

**Comment by Firewolf34** [comment]
> Even if we did, that's not a bad thing.

I mean, you could say something about feature-creep there.

But yeah.

**Comment by Amelia0010** [comment]
feature-creep is a retarded term, based on the idea that there's such a thing as too many features

**Comment by Firewolf34** [comment]
> too many features

Not in my SS13!

**Comment by alexkar598** [comment]
"Hello I am a capdrobe, please don't ignore me"

**Comment by Alexandria404** [comment]
Looks mighty fine

**Pull request closed without merging**
