### PR TITLE
allows you to wear a unholy pitchfork on your back 

### PR DESCRIPTION
**Pull request by boodaliboo**
the title
#### Changelog

:cl:  
tweak: allows you to wear unholy pitchfork on back 

/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
chaplain powercreep

**Comment by boodaliboo** [comment]
> chaplain powercreep

yes it is what you going to do about it

**Comment by boodaliboo** [comment]
thanks ktl

**Comment by MegaEmpirical** [comment]
I really want to be able to do this with mops too.

**Comment by Hopekz** [comment]
No back sprite?

**Comment by boodaliboo** [comment]
i uh dont really want to sprite this

**Review by JamieD1 — APPROVED** [review]
No sprite which would be a bit crap, but code is fine.

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Sprite it or close it

**Pull request closed without merging**
