### PR TITLE
Slime glomp uses a radial menu

### PR DESCRIPTION
**Pull request by Amelia0010**
image
image

### CODE REVIEW

**Comment by Ktlwjec** [comment]
looks disgusting nich

**Comment by nichlas0010** [comment]
you look disgusting

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Radials are nice but couldn't you just *click on the target* instead of clicking on their button

**Comment by Amelia0010** [comment]
🤔

**Comment by Ratvar** [comment]
radials for the sake of radials, rethink your meems

**Comment by Amelia0010** [comment]
well the current option is using the input which just gives you a pop-up box where choose between 2 names. Which do you think is preferable? this, or the popup box

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
neither

**Comment by Amelia0010** [comment]
it's either or.

**Comment by Moja10** [comment]
This is decent, I like

**Comment by ShadowDeath6** [comment]
Uhhh doesn’t drag and drop work?

just remove the verb

**Comment by Amelia0010** [comment]
staying as a regular input box it is.

**Pull request closed without merging**
