### PR TITLE
spelling fix

### PR DESCRIPTION
**Pull request by Ktlwjec1**
:(

### CODE REVIEW

**Review by Colburn3000 — APPROVED** [review]
Yep that’s a misspelling. Thank you ktl

**Review by Bibby0110 — APPROVED** [review]

**Review by ThatLing — APPROVED** [review]

**Review by ThatLing — APPROVED** [review]
Took me a while to review but now I can confidently say that there is a typo in the code that gets fixed if this pull request gets merged into our master branch.

**Review by ThatLing — CHANGES_REQUESTED** [review]
Wait a second...

**Review by ThatLing — APPROVED** [review]

**Review by ThatLing — CHANGES_REQUESTED** [review]
chicken

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
