### PR TITLE
Adds Yogspubby

### PR DESCRIPTION
**Pull request by Ktlwjec**
i hope this doesn't scare ling
i will update it when needed don't worry
i used gray's clerk office
i did all the pipes too
i had to move the gravity gen a bit too

image

### CODE REVIEW

**Comment by thehighwayman** [comment]
close this nobody around to maintain it

**Comment by ThatLing** [comment]
hello i am back from the hospital, i had a heart attack when i saw this pr. uhhh, can't wait for this to get merged

**Comment by Ktlwjec** [comment]
sorry to hear that ling, I'll move this to the yogs folder too when nich finishes his mapmerge things xoxo

**Comment by Ktlwjec** [comment]
hmst've

**Comment by Ktlwjec** [comment]
ok fuck it I'll just redo this

**Pull request closed without merging**
