### PR TITLE
The Baseball Bat PR

### PR DESCRIPTION
**Pull request by MrHorizons**
The baseball bat: the humble, typically wooden instrument of human and non-human harm alike. After all, what else would you do with it? There aren't any balls to base on the station.

The normal wooden bat deals 10 brute damage and requires:

- 25 wooden planks
- A hatchet

Since some have deemed the Makeshift Weapons book "useless" without the baseball bat (in spite of the three other recipes it grants), I have come up with a replacement for it. The new, traitor-exclusive metal bat deals 15 brute damage and requires:

- 6 plasteel sheets
- 1 metal rod
- A welder

Both bats have also been changed to have a constant one tile of knockback. This keeps the gimmick intact whilst making it more consistent to fight against and somewhat harder to do the wall-based stunlock that was supposedly the reason it was removed.

Also, on a less-major note, the Makeshift Weapons book now has remarks whilst reading it, consisting of vague crafting recipes. I couldn't come up with witty dialogue and, frankly, I found it unnecessary for it.

#### Changelog
:cl:
rscadd: Introducing the metal baseball bat, an item craftable from the Makeshift Weapons book! Due to its denser materials, it hits harder.
rscadd: The Makeshift Weapons book now has remarks when you read it.
rscdel: The ablative baseball bat is no more. The reflection part of its code remains, but commented out until it can be made better.
tweak: Baseball bats are now craftable by anyone with the materials and tools to do so.
tweak: Baseball bats have a flat one tile of knockback.
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
yes please, even if its kind of busted (and i dont think it will be) i want to see baseball bats and the baseball burger back in the game for a time

**Comment by ToGWtF** [comment]
I get someone to make me a baseball sprite
I code it
Yogs denies it
TG ports it
We rebase to TG
We PR to re-add baseball bats

the state of it

**Comment by MrHorizons** [comment]
> I get someone to make me a baseball sprite
> I code it
> Yogs denies it
> TG ports it
> We rebase to TG
> We PR to re-add baseball bats
> 
> the state of it

Mind you, before the PR to supposedly readd them, there was _another_ PR to readd them, but as part of a traitor crafting recipe book.

**Comment by overlord12345** [comment]
Change the name of the metal baseball bat as one alredy exists

**Comment by MrHorizons** [comment]
> Change the name of the metal baseball bat as one alredy exists

I removed the one that previously existed and replaced it with a new one. The laser reflection property of the original I've kept commented in the file.

Also, the new metal baseball bat has a different path.

**Comment by alexkar598** [comment]
Strong negative support + encourages makeshift greytide weaponery

**Pull request closed without merging**
