### PR TITLE
FIXES MISTAKES TO BOX LAWOFFICE

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request
realized i made a few oopsie's before #21174 got merged
removes the reinforced glass from between lawyer's consulting area
the camera consoles are no longer accessible through the otherside of the wall

current:
image

intended:
image

# Changelog

:cl:  

bugfix: fixed my mistakes
mapping: makes the prior pr picture perfect
/:cl:

### CODE REVIEW

**Review by Aquizit — CHANGES_REQUESTED** [review]
The office as a whole is missing a camera. On the wall above the fax machine or the paper tray would be fine.

**Comment by wonderinghost** [comment]
> The office as a whole is missing a camera. On the wall above the fax machine or the paper tray would be fine.

Is it the same across the other law offices?

**Review by Aquizit — CHANGES_REQUESTED** [review]
1) Yes the other stations have a camera in the law office.

2) Please make sure to add the appropriate info to the c_tag variable so it will show up on lists appropriately. "Law Office" should be fine, you can look at how they're labeled on other maps if you want.

**Comment by wonderinghost** [comment]
Yeah I noticed when I checked this morning. Have to get home and fix the camera to be good

**Comment by Aquizit** [comment]
Merge conflict

**Comment by Aquizit** [comment]
There's a changelog file being deleted there not sure if it was your thing to fix the conflict or whatnot but get rid of that file in the commit somehow and we're golden

**Review by Aquizit — APPROVED** [review]

**Pull request merged**
