### PR TITLE
Fixes a bug where preternis legs just disappeared sometimes

### LINKED ISSUE #16918: suit has hide legs  flag make pretermis legs go invisible
### Severity

Inconvenience

### Short Description

title

### Reproduction

1. Join as pretermis
2. Wear atmos hydrogen suit
3. Sees pretermis dissappear

### Round ID

N/A

### Test Merges

_No response_

### BYOND Username

Warface1234455

### Additional information

_No response_

### LINKED ISSUE #16962: Pink Resarch directors uniform makes legs invisble as preternis
## Test Merges: 
Not Supplied / None
## Reproduction:
Desc: Pink Resarch directors uniform makes legs invisble as preternis

 Submitted by: Braedon (940453206511743066)

### PR DESCRIPTION
**Pull request by Moltijoe**
Somehow i forgot to include these

closes: #16962 
closes: #16918

:cl:  
bugfix: Fixes a bug where preternis legs just disappeared sometimes
imageadd: adds preternis squished digitigrade leg sprites
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Probably a good idea to make a default sprite too for that parent since the original author apparently forgot. That way if anything else ever goes wrong at least there's a default people can see

**Comment by Moltijoe** [comment]
> Probably a good idea to make a default sprite too for that parent since the original author apparently forgot. That way if anything else ever goes wrong at least there's a default people can see

i'd rather it be invisible so it gets noticed faster

**Comment by Hopekz** [comment]
> i'd rather it be invisible so it gets noticed faster

The best bugs are the one's no one notices because then you don't have to fix them (:

**Comment by Moltijoe** [comment]
> The best bugs are the one's no one notices because then you don't have to fix them (:

i'd rather they get fixed

**Review by cuackles — APPROVED** [review]

**Pull request merged**
