### PR TITLE
Adds a new technical ammo type, Thundershot

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Have you ever thought "Man I wish there was a way to electrocute that guy, but he's way over there and I only have this shotgun."?
Well worry no longer, with the brand new Thundershot (TM)

a new technical ammo type that fires projectiles that zap, and arc to nearby people, really making them regret pissing you off.

image

# Wiki Documentation

Add the new ammo to the ammo section on the wiki

# Changelog

:cl:  
rscadd: Adds cool new electrical buckshot ammo
imageadd: adds a new yellow, electrically charged shell
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
the tesla revolver exists explicitly to do this one single purpose

**Comment by MajManatee** [comment]
but it fucking sucks and this doesnt

**Comment by MajManatee** [comment]
TODO is add a crafting recipe

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
