### PR TITLE
gives faxes to centcomm an admin notification sound

### PR DESCRIPTION
**Pull request by wonderinghost**
probably did this wrong but its just a simple edit i can quickly fix
# Document the changes in your pull request
adds a new admin notification sound for sending, togglable in game settings with prayer

https://github.com/yogstation13/Yogstation/assets/88801435/1148b2bb-ab9a-49b2-8824-2f454aac2173

# Why is this good for the game?
instead of looking for blue text when a message is sent to centcomm, there is now a notification to associate with it so lawyers or others don't have dead letters to centcom

# Changelog

:cl:  
soundadd: adds admin fax sound
bugfix: fixes centcom dissapearing from fax list if switching off
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Please ensure there is a mute button for this.

**Comment by wonderinghost** [comment]
> Please ensure there is a mute button for this.

¯\_(ツ)_/¯
ill figure it out in the morning

**Comment by wonderinghost** [comment]
placing on hold, got to port something so i can work on a toggle.

**Comment by wonderinghost** [comment]
nvm, linked to prayer toggle

**Comment by bruhlookatthisdood** [comment]
make messages to cc from the comms console do it too
torture the admins

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
