### PR TITLE
Fixes missing air alarm in genetics

### PR DESCRIPTION
**Pull request by alexkar598**
# Wiki Documentation

Update genetics image

# Changelog

:cl:  
mapping: Fixes missing air alarm in genetics on box
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
incorrect changelog

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
and where does that fire alarm live now

**Comment by alexkar598** [comment]
On the other side of the room, there was 2 of them

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image
Remove the fire alarm on the right instead and put the air alarm above the door to the hallway

**Comment by alexkar598** [comment]
That's too close to the scrubber

**Comment by ToasterBiome** [comment]
> That's too close to the scrubber

move the scrubber

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
