### PR TITLE
Adds the military VOX from Black Mesa

### PR DESCRIPTION
**Pull request by yacabo**
We have the VOX from Half Life, this PR adds the military VOX from Black Mesa.

Here's an example sound file:
https://cdn.discordapp.com/attachments/613150985224716308/697896429984809111/c1a3_05_switchover.wav

Worth noting that the pop up for which voice the AI will select will now give the options "male, female, military" so maybe we should consider changing that, something like changing them to actual names

:cl:  
rscadd: Added the VOX from Black Mesa to the AI's VOX
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Amazing

**Comment by Jarod1200** [comment]
now we just need the sound of the AI from the movie WALL-IE going "GIVE ME THE PLANT"

**Comment by Xoxeyos** [comment]
YES FINALLY

**Comment by athena413** [comment]
good

**Comment by Firewolf34** [comment]
Fuck that sounds good

**Comment by yacabo** [comment]
The Crowbar Collective are a bunch of brilliant people

**Pull request merged**
