### PR TITLE
Updates contribution guidelines to mention that you should only changelog VISIBLE and PLAYERFACING changes

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

See title

(Why would a player need to see that we did something that made the game 1.2 * 10 ^ (-29) times faster?)

# Wiki Documentation

idk nothing

# Changelog

NO CHANGELOG BECAUSE THIS ISN'T PLAYERVISIBLE DUH

### CODE REVIEW

**Comment by adamsong** [comment]
Why shouldn’t I document admin facing changes?

**Comment by Bibby0110** [comment]
> Why shouldn’t I document admin facing changes?

Because the changelog is for players...

**Comment by maxion12345** [comment]
player facing changes?
how do changes have a face??

**Comment by patpol4** [comment]
admins are players in this context though

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
