### PR TITLE
Changes Hacked AI Module price

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

lol why the fuck do you spend 9tc on something you could achieve with a freeform (which you can easily get to if you have access to an AI upload anyways)

#### Changelog

:cl:   
tweak: Hacked AI Module price changed from 9TC to 4TC
/:cl:

### CODE REVIEW

**Review by alexkar598 — DISMISSED** [review]
hahhahahaahhahahahhahhaa                     

_________




# no just no.2 tc is wayyy too low

**Comment by ynot01** [comment]
i dont value your opinion after https://github.com/yogstation13/Yogstation-TG/pull/6518 but after reconsideration i think 4 or 5TC would better fit

**Comment by AsV9** [comment]
Is this a serious pull or are you just fucking about?

**Comment by ynot01** [comment]
this is a serious pull

**Review by alexkar598 — APPROVED** [review]
Code compiles I guess,might be worth seeing how this goes

**Pull request merged**
