### PR TITLE
Fixes plasma rivers giving invisible unfixable limbs

### PR DESCRIPTION
**Pull request by Moltijoe**
there was so much wrong that it's hard to explain

# Testing
image
image

:cl:  
bugfix: Fixes plasma rivers giving invisible unfixable limbs
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
long overdue

**Comment by Moltijoe** [comment]
> long overdue

i assumed someone had already dealt with it by commenting it out

**Comment by Addust** [comment]
> > long overdue
> 
> i assumed someone had already dealt with it by commenting it out

_a_

**Review by SapphicOverload — APPROVED** [review]

**Comment by MommaDragon** [comment]
Should've mentioned her when this was getting fixed.
Now we no longer have possibly round-breaking limbs!

**Pull request merged**
