### PR TITLE
Makes metal hydrogen armor look a bit less weird with digitigrade legs

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Adds an alternate sprite for metal hydrogen armor so it looks slightly less weird with digitigrade legs

# Spriting

image
image
image
image

# Changelog

:cl:  
tweak: metal hydrogen armor no longer covers feet
imageadd: adds alternate sprite for metal hydrogen armor
/:cl:

### CODE REVIEW

**Review by MajManatee — CHANGES_REQUESTED** [review]
Either document the armor doesn't cover feet or revert that change.
otherwise fine.

**Comment by warface1234455** [comment]
It supposed to cover feet aswell

**Comment by ShoziOffical** [comment]
Oh yeah i shouldn't have done the feet coverage when i was porting this

**Comment by iamthesilly** [comment]
> Either document the armor doesn't cover feet or revert that change. otherwise fine.

done, thanks for reminding me

**Review by MajManatee — APPROVED** [review]
jokes on you it was an art PR, my opinion is irrelevant

**Review by cuackles — APPROVED** [review]

**Pull request merged**
