### PR TITLE
GIVE CHEF SOAP

### PR DESCRIPTION
**Pull request by boodaliboo**
https://forums.yogstation.net/threads/why-does-chef-have-no-soap-at-kitchen.22451/#post-192274
#### Changelog

:cl:  
rscadd: GIVES THE MAN HIS SOAP
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
not balanced

**Comment by Hopekz** [comment]
What's next?
Giving them pulse rifles?
Giving them the ninja katana?

**Review by patpol4 — CHANGES_REQUESTED** [review]
If you want this you have to place them in the actual bar templates

**Comment by boodaliboo** [comment]
> If you want this you have to place them in the actual bar templates

oh ok ill re pr it

**Comment by MegaEmpirical** [comment]
The issue isn't soap, it's the broken rag.

**Pull request closed without merging**
