### PR TITLE
Ports hyposprays MK. II

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Ports ["Hypospray Mk. IIs" #20](https://github.com/Whitesands13/Whitesands/pull/20) by [MarkSuckerberg](https://github.com/MarkSuckerberg) (though its based on ["[READY] Hypospray MK IIs" #5722](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/5722) by [Poojawa](https://github.com/Poojawa)) and hypospray sprites from ["Resprites and Beaker (and Bottle) Lids" #31](https://github.com/shiptest-ss13/Shiptest/pull/31) by [triplezeta](https://github.com/triplezeta), cleaned up and slightly refactored to be much easier to read and use our vials. Sprites for the hyposprays are by me, and they are subject to change. Makes vial boxes less of a pain to use and gives one to the CMO with large vials with a bunch of healing chems. The new hypospray can be obtained either through a new medkit in the medical vendor also containing various vials or through the advanced biotech tech node.

# Spriting
image
image
image

# Wiki Documentation

Add the hypospray to the vendor page, add the designs to the research page. 

# Changelog

:cl:  Poojawa, MarkSuckerberg, triplezeta, nmajask
rscadd: Added new hyposprays that replace the CMO's hypospray and available to doctors which can be loaded with vials 
rscadd: Added bluespace (60u) and large (30u) vials 
rscadd: Added a new medkit containing a hypospray and some vials for 300 credits in the medical vendor
tweak: vials can now be renamed with pens
tweak: vials boxes no longer have a lid, so you can unlock them with alt click
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Please for the love of god give brig phys one on round start so they can actually heal sec on the go

**Review by KillerOrcaCora — COMMENTED** [review]
Suggest going back to the old sprite and just with a updated design for the hypospray

**Comment by VaelophisNyx** [comment]
I think the new sprites look fantastic tbh

**Comment by ynot01** [comment]
dont like the sprites

**Comment by nmajask** [comment]
Sprites now use shiptest's hypospray with a little overlay to indicate the amount/color of the reagents in the vial. Also added sprites for a syringe like hypospray.
image

**Comment by ynot01** [comment]
hot

**Review by ToasterBiome — APPROVED** [review]
Map approval

**Comment by redmoogle** [comment]
Very cool

**Review by KillerOrcaCora — APPROVED** [review]
Emir approve this

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
