### PR TITLE
Let's hear some tunes - volume 1 second edition

### PR DESCRIPTION
**Pull request by burn1cycle**
Adds some house-y style tunes as well as few chill tracks. 
Removed Rock is Dead for sound level reasons.

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Inb4 "Atomize your PR"

**Comment by JamieD1** [comment]
@Partheo Jesus have mercy.

**Comment by patpol4** [comment]
That's a lot

**Comment by JamieD1** [comment]
I appreciate the work you put into this, but I feel im going to move the jukebox to a youtube based system instead as this is ALOT of extra files for people to download for almost no reward as their playtime will be several rare.

**Comment by alexkar598** [comment]
but they are loaded dynamically and only downloaded when the song is played..

**Comment by alexkar598** [comment]
A youtube system would also require downloading the song on the server and sending it to the client at runtime, theres 0 difference apart from the fact that YouTube dl is kinda janky sometimes

**Comment by maxion12345** [comment]
> A youtube system would also require downloading the song on the server and sending it to the client at runtime, theres 0 difference apart from the fact that YouTube dl is kinda janky sometimes

But youtube would allow more flexibility for songs, so that could be pretty fun

**Pull request closed without merging**
