### PR TITLE
ADDS THE GRILL

### PR DESCRIPTION
**Pull request by SomeguyManperson**
GRILL

ports tgstation/tgstation#46844
NUKEOPS THIS, BLOODCULT THAT,
I JUST WANNA GRILL FOR GODS SAKE

:cl:  Fikou and Twaticus for sprites (thank you too tralezab and whoever else helped)
rscadd: Adds the Grill, which can be powered by coal and wood, increases food nutritional value, taste, and adds grill marks.
rscadd: Adds a new drink, Monkey Energy, works as fuel for the grill and increases your speed if you're a monkey, also adds a new reagent, Char, which works the magic in the grill.
tweak: Coal now turns into CO2 at high temperatures and is now a stack
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
https://www.youtube.com/watch?v=28--5aEV1Z0

**Comment by MegaEmpirical** [comment]
Moth grill gimmick here I come.

**Review by Amelia0010 — APPROVED** [review]
Code is fine

**Comment by Mr-Space** [comment]
can we grill the AI in a intellicard to kill it

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
