### PR TITLE
Edits common backpack's mob sprites to have no straps.

### PR DESCRIPTION
**Pull request by nesisknesis**
# Document the changes in your pull request
Straps = the literal straps of the backpack.

Straps on backpacks can obfuscate details of other sprites which would be superior to clearly show. Only applies to the mob sprites.

*Includes satchels and duffelbags.

Explorer's backpack and satchel as well as the engineer backpack still has straps as their harness style is unique and actually visually pleasing.

Items such as jetpacks, tanks, and weapons still have straps. 

I would assume this change is minor so if you really want images ping me in #spriting
# Changelog

:cl:  Identification
imagedel: Common backpacks have had their straps removed on mob sprites to improve clarity.
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
make it toggable?

**Comment by nesisknesis** [comment]
> make it toggable?

No

**Comment by Mqiib** [comment]
I always thought they looked terrible anyways. Very cool.

**Review by Partheo — APPROVED** [review]

**Comment by JamieD1** [comment]
So whats holding the backpack on now

**Comment by Marmio64** [comment]
what, are they magnetically attached?

**Pull request merged**
