### PR TITLE
Arconomy 1.0: Final Stage Capitalism

### PR DESCRIPTION
**Pull request by swissloaf**
Credit: https://github.com/tgstation/tgstation/pull/52007

Read that PR for all the information on it because it's so much.

- [x] Bring the stuff over from the PR

- [x] Fix all the compiling errors

- [x] The sprites that are needed

- [x] The mapping required

- [x] The tgui.bundle.js nonsense

#### Changelog

:cl:  
rscadd: The Civilian Bounty Pad and Console have been added to every map. Using your ID on the console will allow you to aquire a civilian bounty, which can be sent away for additional profit similar to cargo bounties.
rscadd: Midround, the widely unstable space market can occasionally briefly completely collapse, resulting in vendor prices skyrocketing for short periods of time.
rscadd: For admins, there are new debug items to fiddle with the economy.
rscadd: Several new small bounties have been added to accompany the new sets of civilian bounties per job.
rscdel: The Coin mint has been removed from the code and all maps.
tweak: Miasma Exports have been nerfed from 10 credits/mol to 2credits/mol when sold.
experimental: Crew now start with higher starting balances, but lower passive income throughout the round.
experimental: A new economy mechanic has been added, the inflation value. In short, if player accounts hold more money than the station should probably have at a given time, the prices of vendors will go up. If vendor prices are unreasonably high, spend money with cargo or vendors.
imageadd: New telepad sprite
soundadd: Telepads now make a whoopy teleport sound.
/:cl:

### CODE REVIEW

**Review by Partheo — APPROVED** [review]
Sprites good

**Comment by swissloaf** [comment]
log_econ needs to be CONFIG.txt read config/config.txt file for what needs to be added. literally 1 line

**Comment by Jarod1200** [comment]
bruh how am i supposed to print more moneh to solve all my problems if theres no mint

**Comment by swissloaf** [comment]
> bruh how am i supposed to print more moneh to solve all my problems if theres no mint

inflation go brrrrrrrr

**Comment by MrHorizons** [comment]
+1 for all the changes except the miasma export price nerf. I like the CentCom fart gas memery there is now.

**Comment by Alexandria404** [comment]
"Additionally, the starting balance for each crewmember is now 6 paychecks of the above values."

what

**Review by patpol4 — APPROVED** [review]
Map is fine now

**Comment by swissloaf** [comment]
> "Additionally, the starting balance for each crewmember is now 6 paychecks of the above values."
> 
> what

thats how its always been. roundstart balance is generated by a set number multiplied by their job's paycheck amount. it moved from 5 to 7 multiplier paychecks.

**Comment by Marmio64** [comment]
neutral for now,

miasma export value nerf is too hard, should be decreased to 5 credits/mol not decreased to only 2.

mint remover seems nice

inflation happens far too fast however IMO.

**Comment by boodaliboo** [comment]
make 5credits per mole for miasma

**Comment by swissloaf** [comment]
> make 5credits per mole for miasma

deal

**Comment by boodaliboo** [comment]
then this pr is perfect excited for it

**Comment by MrHorizons** [comment]
Maybe the other gases could receive a price increase or other tweaks? If we're going off of relative "worth", it doesn't make sense to have gamer farts, a fusion prerequisite, and super oxygen all export for the same price.

Though I can make that my own PR later.

EDIT: Yeah, I'll definitely make that my own PR, checking with Colton and other atmosians about the best prices to make each gas. Besides, I'd like to avoid making this PR too much of a bundle.

**Comment by MegaEmpirical** [comment]
Wish we'd we'd keep the mint but oh well. Looks like a good chshge overall.

**Comment by Georgeur** [comment]
Good PR. Hoping the stocks will still be somewhat consistent to value after this, as it seems to add more variables. 
I'm hoping "experimental: Crew now start with higher starting balances, but lower passive income throughout the round." will be balanced basically solely for warops, as the HoP cant afford a gun at roundstart right now, and I think that just makes warops greytide but rule exempt.

**Comment by ghost** [comment]
The miasma export nerf was done on TG due to randomized lavaland atmos resulting in fart canister exports constituting more than 50% of station GDP, as that is not the case on yogstation, that need not be added.

**Comment by MegaEmpirical** [comment]
Sad.

**Pull request closed without merging**
