### PR TITLE
who the absolute fuck made the liver immortal

### PR DESCRIPTION
**Pull request by ghost**
liver damage should still be a fucking thing, seriously, reducing it to 0.01 is ridiculous come on

### CODE REVIEW

**Comment by fluffe9911** [comment]
Seems it was nich about 3 months ago https://github.com/yogstation13/Yogstation-TG/pull/975

Edit nevermind he waa just manually porting a thing cause travis

**Comment by ghost** [comment]
Make sure you put yogs in that comment line to specify this is different than TG.  Modularization and all that.

**Comment by Amelia0010** [comment]
>Seems it was nich about 3 months ago #975

https://github.com/tgstation/tgstation/pull/37175

**Comment by DLCabbose** [comment]
lol

**Pull request merged**
