### PR TITLE
Increase fire axe throw damage

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

15 throw force is pretty low for a fire axe. Throw force should generally be higher than melee force on sharp objects
# Spriting

# Wiki Documentation

not documented
# Changelog

:cl:  
tweak: Increase fire axe throw damage (15 -> 25)
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
fire axe is pretty heavy. Doubt you could throw it hard enough to do more damage than actually hitting stuff with it normally

**Comment by Simplehorror** [comment]
i reckon i'd be pretty fucked if you threw a fire axe at me

**Comment by Hopekz** [comment]
> fire axe is pretty heavy. Doubt you could throw it hard enough to do more damage than actually hitting stuff with it normally

After having real world experience throwing a fire axe I can tell you that it isn't that difficult.

All you have to do is let go of it during an overhead swing.

Effort wise I'd actually argue that throwing a fire axe is easier than swinging it because you don't have to commit to the full strike.

**Comment by Marmio64** [comment]
in real life throwing a fire axe isn't too hard and can still be devastating. However, this is ss13, and axes are generally balanced as being great melee weapons but poorer at range and throwing than spears.

**Comment by Bibby0110** [comment]
> > fire axe is pretty heavy. Doubt you could throw it hard enough to do more damage than actually hitting stuff with it normally
> 
> After having real world experience throwing a fire axe I can tell you that it isn't that difficult.
> 
> All you have to do is let go of it during an overhead swing.
> 
> Effort wise I'd actually argue that throwing a fire axe is easier than swinging it because you don't have to commit to the full strike.

there's no overhead throws, this is a 2D game

**Comment by Hopekz** [comment]
> there's no overhead throws, this is a 2D game

How do you know what type of throw it is we have no throw animations

**Pull request closed without merging**
