### PR TITLE
Adds Blue-Eye, a lore accurate drug frequented by Wizards

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Adds Blue-Eye, a drug composed of bluespace crystals, diphenhydramine, iodine, hydrogen and sugar.
Provides a small stamina buff, but causes your screen to go blue and for random movement and twitches to occur.
Will spit out random wizard spell text at you, and on high dosages will make your hands do wizard gang signs and drop your items.
Will teleport you randomly on metabolism, and during an overdose.
If you're not a cult member, it will turn your eyes blue
If you are a wizard, you will have less downsides and have unconcious protection, paralyze protection and reduced stamloss (nowhere near as strong as meth so really youre still probably better off using meth if you really want to powergame)

# Spriting
Adds a fullscreen sprite when the drug is in use:
uber

# Wiki Documentation
New chemistry drug will need to be added, recipe is as follows:
Diphenhydramine 1
Bluespace 2
Iodine 1
Hydrogen 1
Sugar 1

# Changelog
:cl:  
rscadd: Added new drug, blue-eye
imageadd: Added fullscreen overlay for blue-eye
/:cl:

### CODE REVIEW

**Comment by battlestar-gafraktika** [comment]
should have an alternative effect for actual wizards

**Comment by azzzertyy** [comment]
i did also consider giving it an incredibly incredibly rare chance of turning you into a wizard but the maintaners would yell at me

**Comment by iamthesilly** [comment]
Shadow wizard money gang

We love casting spells

**Comment by UltraBigRat** [comment]
> i did also consider giving it an incredibly incredibly rare chance of turning you into a wizard but the maintaners would yell at me

Could just give it a list of spells it has a small chance to randomly and unpredictably cast. Like forcewall, slip, smoke, spacetime distortion, repulse, magic missile, tesla blast, and the other ones that dont need targeting and dont cause much permament damage.

**Comment by cuackles** [comment]
show how it looks aplied in game pls

**Comment by azzzertyy** [comment]
> show how it looks aplied in game pls


https://github.com/yogstation13/Yogstation/assets/42524344/12e93994-c3b5-420d-9720-e66babd50da9

**Review by ToasterBiome — APPROVED** [review]
i like this

**Pull request merged**
