### PR TITLE
IPC smokes when overheating

### PR DESCRIPTION
**Pull request by Moltijoe**
Visual indicator that they've fucked up since they don't gasp

# Spriting
image

:cl:  
rscadd: IPC smokes when overheating
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
there's gotta be a better way to do this

**Comment by ToasterBiome** [comment]
you can change the particles spawning to 0 to turn them off and 1 to turn them on instead of making new particles every time

https://www.byond.com/docs/ref/#/{notes}/particles

**Comment by Moltijoe** [comment]
>there's gotta be a better way to do this

turns out there is

> you can change the particles spawning to 0 to turn them off and 1 to turn them on instead of making new particles every time

yeah, i'm new to particles, so i assumed this wouldn't be the best way to do it

**Comment by Moltijoe** [comment]
gotta wait for #16778 to be merged before i can fix this PR

**Comment by JamieD1** [comment]
> gotta wait for #16778 to be merged before i can fix this PR

job done

**Review by MajManatee — APPROVED** [review]
Ssssssssmokin!!

**Pull request merged**
