### PR TITLE
Gives the Clerk a baseball bat for 4tc

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
gives the clerk a baseball bat for 4tc. as i believe this fits them well and they dont already have a item
#### Changelog

:cl:  
rscadd: Added a baseball bat to the clerks role exclusive uplink 
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
no

**Comment by boodaliboo** [comment]
i also dont know how to change the icon on github website

**Comment by ynot01** [comment]
ok but why

**Comment by boodaliboo** [comment]
> no

why?

**Comment by boodaliboo** [comment]
> ok but why

i want the clerk to have a item that i feel fits them

**Comment by jcatjmeow** [comment]
Baseball bat as a traitor item? Sure why not. But why curator?

Here is what a short list of what I think the curator is known for:
Being an adventurer
Living in the past
Speaking cool languages
Reading
Devil worship
Questionable morals

Here is an abridged list of what the curator is not known for:
Playing baseball

Edit: it says clerk :( not curator

**Comment by boodaliboo** [comment]
> Baseball bat as a traitor item? Sure why not. But why curator?
> 
> Here is what a short list of what I think the curator is known for:
> Being an adventurer
> Living in the past
> Speaking cool languages
> Reading
> Devil worship
> Questionable morals
> 
> Here is an abridged list of what the curator is not known for:
> Playing baseball

it says clerk not curator

**Comment by Hopekz** [comment]
Completely ignoring the fact that this item in particular doesn't fit the Curator I'd like to bring attention to balancing of this item.

For 4TC you are getting an item that is quite weak
This item has a force of `force = 10` on its own is too weak for 4TC.

If this bat can do home runs then it might actually be too powerful for 4TC. 
I think the homeruns at the moment make the target explode?
`user.visible_message("<span class='userdanger'>It's a home run!</span>")`
		`target.throw_at(throw_target, rand(8,10), 14, user)`
		`target.ex_act(EXPLODE_HEAVY)`
I think I remember bat meta before (with homeruns) was to stun, charge up your bat then "home run" them.

If you make a bat that behaves differently I couldn't see why not if we completely ignore the fact that it doesn't fit the curator like Jcat said.

**Comment by jcatjmeow** [comment]
I'm so sorry! Completely forgot we even had the clerk role, useless.

Why does clerk have a baseball bat tho? I dunno, but it makes marginally more sense than curator

Sorry for confusing myself and hopekz

**Comment by Hopekz** [comment]
> I'm so sorry! Completely forgot we even had the clerk role, useless.
> 
> Why does clerk have a baseball bat tho? I dunno, but it makes marginally more sense than curator
> 
> Sorry for confusing myself and hopekz

Oh yeah good catch the posts in this discussion for some reason made me think we're talking about the curator

**Comment by HomocidlePancakes** [comment]
Bat can chainstun people in to walls an Nich doesn’t like that because Nich.

**Comment by Amelia0010** [comment]
:)

**Comment by Hopekz** [comment]
> Bat can chainstun people in to walls an Nich doesn’t like that because Nich.

well lets not forget our current combat system is touch to death meaning that if you attack someone with something like a stun baton you basically killed them on the first hit you just now need to hit them a few times.

Keeping that in mind I don't see how stunlocking someone against a wall and doing 10 damage to them each hit is different then stunning them and beating them over and over on their stunned body.
This bat is currently around 9-11 hits to light crit (120 damage, bat deals 10 damage and organ damage works in mysterious ways so its not 12 hits)

Does this bat get past stun immunity?

Also, to add to this bat in particular I think this one only stun locks if you're against a wall so there are situations where this does not happen on the first hit compared to other stun methods in our game which are stun to kill on first hit.

**Comment by ynot01** [comment]
honk

**Comment by Hopekz** [comment]
We need to rework our combat system to either get rid of stun to kill on a single hit or make it more rare.

**Pull request closed without merging**
