### PR TITLE
Revert "Dark spirit now only lets you move 21 tiles away"

### PR DESCRIPTION
**Pull request by Mqiib**
Reverts yogstation13/Yogstation#16553

Now with new and improved mqiib branch! Anyways this is still a bad change, my reasoning isn't any different from the last revert pr.

### CODE REVIEW

**Comment by Simplehorror** [comment]
to maintainers: check the previous PR for why this shouldn't be merged

**Comment by Notamaniac** [comment]
> to maintainers: check the previous PR for why this shouldn't be merged

Please show a valid demonstration of someone using dark spirit to solo an entire station. Even just a thought experiment, showing all us unenlighted fools how exactly 'perfect information' gives such a decisive advantage.

**Comment by Simplehorror** [comment]
what? you just check their body and then you can counter everything they have.

**Comment by Notamaniac** [comment]
Okay we're halfway there. Elaborate clearly on the measures one needs to take to 'counter' someone.

**Comment by Notamaniac** [comment]
> what? you just check their body and then you can counter everything they have.

Okay elaborate on the steps and measures someone needs to take to 'counter' someone.

**Comment by chemistrymain2** [comment]
> Reverts #16553
> 
> Now with new and improved mqiib branch! Anyways this is still a bad change, my reasoning isn't any different from the last revert pr.

y'know, if you want to actually take a middle line between the utility of perfect ghost information and restricting how powerful it can get, you can make said dark spirit visible to humans once cult passes above the red eye threshold through the same mechanism by having their set_invisibility adjusted once the ghost is created

then the cult ghost can actually be seen and you can know if you're being stalked by the ghost, which is handy. but i'm gitbanned what do i know

**Comment by Mqiib** [comment]
> > Reverts #16553
> > Now with new and improved mqiib branch! Anyways this is still a bad change, my reasoning isn't any different from the last revert pr.
> 
> y'know, if you want to actually take a middle line between the utility of perfect ghost information and restricting how powerful it can get, you can make said dark spirit visible to humans once cult passes above the red eye threshold through the same mechanism by having their set_invisibility adjusted once the ghost is created
> 
> then the cult ghost can actually be seen and you can know if you're being stalked by the ghost, which is handy. but i'm gitbanned what do i know

[#9707]

**Comment by chemistrymain2** [comment]
> > > Reverts #16553
> > > Now with new and improved mqiib branch! Anyways this is still a bad change, my reasoning isn't any different from the last revert pr.
> > 
> > 
> > y'know, if you want to actually take a middle line between the utility of perfect ghost information and restricting how powerful it can get, you can make said dark spirit visible to humans once cult passes above the red eye threshold through the same mechanism by having their set_invisibility adjusted once the ghost is created
> > then the cult ghost can actually be seen and you can know if you're being stalked by the ghost, which is handy. but i'm gitbanned what do i know
> 
> [#9707]

i know it was denied, it's just that was an always visible ghost, and this would be a 'visible when cult is starting to win' ghost

**Review by Moltijoe — APPROVED** [review]

**Comment by ynot01** [comment]
> i know it was denied, it's just that was an always visible ghost, and this would be a 'visible when cult is starting to win' ghost

No actually this is exactly what my PR did, "ascension" triggers when a certain % of the station is cultist, ie halos appear

**Pull request merged**
