### PR TITLE
Holy Whip now has 3 range

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

the chaplain's whip now can reach 3 tiles away in exchange for not being able to fit in a pocket. very cool stuff.
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Holy Whip now has 3 range
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
3 range is massive, might wanna tweak the damage or cooldown like with spear

**Comment by Simplehorror** [comment]
> 3 range is massive, might wanna tweak the damage or cooldown like with spear

your null rod not being able to fit in your pocket is an even worse disadvantage. if it cant fit in your pocket, you have to keep it in your hand which means you can lose it if you get stunned by a cultist or such, other null rods are also better than this

**Comment by Simplehorror** [comment]
but I could probably lower the damage yeah but I think not being able to fit in pocket or bag is bad enough

**Comment by ynot01** [comment]
it fits on belt if you missed that

**Comment by Simplehorror** [comment]
> it fits on belt if you missed that

alright let me make it YUGE

**Comment by Moltijoe** [comment]
maybe people will actually use the whip this way

**Comment by Simplehorror** [comment]
can finally cosplay castlevania

**Review by JamieD1 — APPROVED** [review]
Cant wait for the nerf

**Pull request merged**
