### PR TITLE
Readds Blood Brother Traitor Kits

### PR DESCRIPTION
**Pull request by Xoxeyos**
Readds Blood Brother traitor kits, I think we should try this out again, before we remove BB from our server.

:cl:  Xoxeyos
rscadd: Readds the Blood Brother Traitor Kits.
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
poor solution

**Comment by AsV9** [comment]
The reason blood brothers is such a shit gamemode is because you are forced to rely on RNG to not get an incompetent or useless brother. Giving a pair of brothers 40 fuckin TC is a terrible solution to the problem which basically just makes it so you can ignore your brother 100% of the time instead of 90% of the time.

I ran the numbers on the bundles located [here](https://github.com/yogstation13/Yogstation/blob/master/code/game/objects/items/storage/uplink_kits.dm#L122). On average you're going to get about 30 TC worth of items, and all the bundles are fairly good, definitely not meme-tier. Imagine both brothers getting decent bundles and you now have somewhere between 40 and 120 TC to complete your objectives. Imagine three way blood brother teams who end up with so much fucking gear they are basically nukies. Yeah that's what this PR does.

I'd rather you just remove blood brothers completely than re-implement this.

Original PR: #5310
Removal PR: #6348
Council vote that approved removal: [Vote-merge-6348](https://forums.yogstation.net/index.php?threads/vote-merge-6348.19434/)

**Comment by UselessTheremin** [comment]
Yeah this pretty much makes BB's lone operatives at this point like we should just remove them, they are beyond saving.

**Comment by boodaliboo** [comment]
good solution

**Comment by MrHorizons** [comment]
My solution would have been to give them Syndicate radio implants (or just normal Syndicate encryption keys), but I guess that's barely above removing them.

**Comment by Xoxeyos** [comment]
I figured I'd try, I agree, Blood Brothers is absolutely retarded.

**Pull request closed without merging**
