### PR TITLE
internal affairs agent death pill is much stronger

### PR DESCRIPTION
**Pull request by Marmio64**
This gives the internal affairs agent pill some coniine and initropidril so that it kills you within about 10-20 seconds instead of just like, not killing you at all, since cyanide is super fucking weak. This is good for the game since it allows IAA to actually kill themselves.

#### Changelog

:cl:  
tweak: IAA pill is a fuckton more deadly
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
even though nobody ever uses it, if they were to use it, it would work. good change.

**Comment by Hopekz** [comment]
...why not just buff cyanide?
Backward solution

**Comment by Marmio64** [comment]
> ...why not just buff cyanide?
> Backward solution

cyanide is super easy to make, you can't make it very strong

**Comment by alexkar598** [comment]
beaker, water, syringe, syringe gun


honk

**Comment by SomeguyManperson** [comment]
I mean if you want to get the pill out of your mouth if you can even do that you'd need to have someone surgically remove it I think, and you can just buy a poison kit for the same poisons but in higher volumes so having some poisons in the pill that aren't easily attainable shouldn't be too terrible

**Review by redmoogle — APPROVED** [review]
Code is good

**Comment by alexkar598** [comment]
yeah fair enough, forgot it was an implant now

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
