### PR TITLE
Bunch of lighting utilities/items

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request
image

APCs
 - Can now toggle area lights on a 10 second cooldown
 - Shares the cooldown with the nightshift lighting
 - Minor refactors/cleanup

Remote Light Switch (RLS)
 - Toggles the lights in an area
 - Can be built at the autolathe and service protolathe

Light Switch Frame
 - Can be built for 1 metal
 - Attached to walls
 - No steps other than attach

# Why is this good for the game?
Some rooms dont start with lightswitches making craftable frames useful; I thought the APCs with the lighting switch would be a neet idea.

Remote Light Switch is mostly just a meme item (thought about a traitor (clown maybe?) item that overloads lights)

# Testing
Tested that everything works and doesnt look super weird

# Spriting
See above picture

# Wiki Documentation

APC has a new option // 10 Second Cooldown
2 new objects

# Changelog

:cl:  
rscadd: Remote Light Switch
rscadd: Light Switch Wallframe
tweak: APCs can now toggle lights
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
ok the RLS isnt gonna get abused by antag right? like when you want to quickly turn off light in an area, im thinking that shouldnt be printable and put those for heads only like the remote door controller

**Comment by redmoogle** [comment]
> ok the RLS isnt gonna get abused by antag right? like when you want to quickly turn off light in an area, im thinking that shouldnt be printable and put those for heads only like the remote door controller

I see what you mean but most of time people are just gonna hear it or scream. a greytider would probably just be really annoying with it

**Review by cuackles — APPROVED** [review]

**Comment by MajManatee** [comment]
Id personally like to see a lightswitch need wire then screwdriving

**Comment by redmoogle** [comment]
> Id personally like to see a lightswitch need wire then screwdriving

Wallframe code is a smidge weird let me see if I can do that

**Comment by redmoogle** [comment]
> Id personally like to see a lightswitch need wire then screwdriving

Done; I also added a wire interaction because fuck it why not

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
