### PR TITLE
Ice Cream Rework Part 2: I can't think of a funny name

### PR DESCRIPTION
**Pull request by Scrambledeggs00**
# Document the changes in your pull request

This PR does multiple things, though the main thing is switching the icecream vat from the in-game UI to TGUI. The new UI lets you select and dispense both ice cream cones and scoops. It also has tabs, with a vat tab storing the UI elements for selecting and dispensing cones and scoops while an information tab tells users how to use and restock the vat, along with how to make new scoops and cones.

Using the new icecream vat:
Left-clicking on the vat with an empty hand opens the UI.
The select button will select the item for scooping in the case of scoops or for easy dispensing in the case of cones.
Selected scoops are what will be scooped into cones.
Selected cones can be dispensed by alt-clicking the vat, meaning you won't need the UI for dispensing selected cones.

Storage:
The vat has a maximum capacity of 120 scoops and cones combined. I plan on decreasing it and giving ways of increasing it, but that will not be done in this PR.
To store items, either left-click on the vat with a scoop or cone.
You can also use ice cream cartons on the vat to move all of its contents into the vat for quick storage of multiple scoops.
Cones that have a scoop cannot be stored.
Vats start with 10 of every cone and 5 of every scoop in their starting list, which currently are all the available scoops and cones.

The vat now stores actual items:
This means that you can poison a scoop and then later put it on a cone, making said cone poisoned too.
When deciding what scoop/cone to dispense, the vat dispenses the most recent item put in it, so if the spiked scoop was the last scoop of the selected/dispensed type you put in it, it will dispense that scoop first.

New cones*:
*They're essentially just the old ones but coded slightly differently.
They can be made by processing their raw forms in a food processor.
Their raw form can be crafted in the crafting menu in the misc. food section.
Why the food processor? To make it easy to make lots of cones since T4 processors give out 3x the output.
I plan on adding cone boxes that can ordered from cargo similar to how ice cream cartons can be ordered, but not in this PR.

Possibly easy info tab editing?:
The information sent to the info tab is not stored in the tsx. file, but in the backend file of info_tab.dm.
This should* mean that if someone wants to add, remove, or modify something within the info tab, they can just mess with this file rather than the tsx. file.
*Should because I'm no TGUI expert so for all I know, changing it could implode the server so... ;}

Cool! Nothing but cool things added :]
Not true, I had to remove some things because I do not want to work on this PR for another 2-3 weeks ;[

Things that were removed:
Borgs can no longer dispense ice cream, as they used the old ice cream which this PR removes in place of a new system for scoops and cones.
The Creamatorium was also removed due to using the old ice cream.

What about recipes that used the old ice cream?:
Recipes that used the old ice cream cones now use the new ice cream cones.

# Why is this good for the game?

Old UI loud and ugly, new UI good :]

# Testing

Video proof of testing basic vat functions and cone crafting:
https://www.youtube.com/watch?v=dKkyZ1z5CHU

Old cones in recipes replaced by new cones:
image

Raw cones recipes:
image

Borgs no longer having access to ice cream:
image

No run time errors after test video:
image

# Spriting

New sprites for raw cones:
RawCones

# Wiki Documentation

Vat:
Left-click to store items, both singular and, if an ice cream carton, as much of its contents that will fit.
Cones with scoops cannot be stored.
Vat stores actual items, so poisoned or half-eaten items can be dispensed later.
Right-click with a cone in active hand and with a scoop selected via the UI to scoop said cone with the selected scoop.
Alt-click to dispense the selected cone if there is one.

Cones:
Raw cake cone is made with one raw pastry base and 2u of sugar.
Raw chocolate cone is made with one raw pastry base and 2u of coco powder.
Processing raw cones with the food processor turns them into finished cones.

# Changelog

:cl:  
rscadd: You can now make raw ice cream cones and process them into finished cones.
rscdel: Borgs cannot dispense ice cream and Creamatorium removed.    
tweak: New UI for ice cream vat.
imageadd: Added sprites for raw cones.
/:cl:

### CODE REVIEW

**Comment by Necrosium** [comment]
Every good chef knows that an ice vat is essential for the summer. Speedmerge!!!!!

**Comment by ktlwjec0** [comment]
A lot of the things on the information tab are just bloat and should be external on the wiki or something small that appears in the ice cream vat description. You shouldn't need five sections of poorly structured text just to explain how this works. Especially sections such as "creating new scoops", are you just going to have an endless list of ice cream flavors when new ones are added?

I also think raw cone sprites look far too similar to raw pastry bases, it's not a huge deal but having them look more different would be better.

**Comment by Scrambledeggs00** [comment]
> A lot of the things on the information tab are just bloat and should be external on the wiki or something small that appears in the ice cream vat description. You shouldn't need five sections of poorly structured text just to explain how this works. Especially sections such as "creating new scoops", are you just going to have an endless list of ice cream flavors when new ones are added?
> 
> I also think raw cone sprites look far too similar to raw pastry bases, it's not a huge deal but having them look more different would be better.

For the information tabs, I can remove some of the more verbose parts of them, though I plan on keeping the tabs since A: I spent way too much time on them and B: I've heavily commented the code, so it'll be useful for people who want to know how TGUI tabs work without needing to spend hours like I did learning it from uncommented code.

For the sprites, yea I copied the dough slice sprite which the pastry sprite also copies from since I'm more focused on coding the UI and backend code, though they're serviceable for now. I don't plan on changing them for awhile if at all since I've got another PR I want to do with ice cream that could take awhile.

**Comment by ktlwjec0** [comment]
> > A lot of the things on the information tab are just bloat and should be external on the wiki or something small that appears in the ice cream vat description. You shouldn't need five sections of poorly structured text just to explain how this works. Especially sections such as "creating new scoops", are you just going to have an endless list of ice cream flavors when new ones are added?
> > I also think raw cone sprites look far too similar to raw pastry bases, it's not a huge deal but having them look more different would be better.
> 
> For the information tabs, I can remove some of the more verbose parts of them, though I plan on keeping the tabs since A: I spent way too much time on them and B: I've heavily commented the code, so it'll be useful for people who want to know how TGUI tabs work without needing to spend hours like I did learning it from uncommented code.
> 
> For the sprites, yea I copied the dough slice sprite which the pastry sprite also copies from since I'm more focused on coding the UI and backend code, though they're serviceable for now. I don't plan on changing them for awhile if at all since I've got another PR I want to do with ice cream that could take awhile.

If it's better worded information and not fully bloat that explains every single detail on how ice cream works and all the flavors then sure, it can be kept. But currently it's just walls of text that are hard to read with most of the information not needing to be written there. I know it took you a while to make it but that shouldn't be a reason just to keep it in, you can use this to write your own guide if wanted and get it pinned in a development channel so it doesn't go to waste, I'm sure someone will do that. Just honestly if I was new and opened the ice cream vat and saw paragraphs of explanations  about how to use it I'd just walk away and not bother with it.

**Review by Mqiib — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
