### PR TITLE
Add a new song to the lobby music playlist thing

### PR DESCRIPTION
**Pull request by ThatGuyPhil**
### Intent of your Pull Request

I want The Great Strategy to be one of the lobby themes because it sounds good and to trigger the roblox sleeper agents.
https://www.youtube.com/watch?v=QC4UKsoQqyY

#### Changelog

:cl:  
soundadd: adds The Great Strategy as a lobby music
/:cl:

### CODE REVIEW

**Comment by ThatGuyPhil** [comment]
oh  i put the song title and the artist in the wrong spots oops

**Comment by jcatjmeow** [comment]
I have listened to this once through, and nice. Maybe a bit high-key and bombastic for what should basically be elevator music, but it's not bad at all.

**Comment by Partheo** [comment]
Yeah imo this is way too intense. It also feels pretty crappy tbh. It's just the same kind of sound repeating the whole time with varying intensity.

**Comment by ThatGuyPhil** [comment]
at least two of our lobby songs can be described with your comments

**Comment by jcatjmeow** [comment]
I default to par's judgement, as he is the superior art

**Comment by Partheo** [comment]
> 
> 
> at least two of our lobby songs can be described with your comments

Lemme know which and I'll purge 'em

**Comment by ThatGuyPhil** [comment]
how about we get more people to think about this song

**Review by JamieD1 — APPROVED** [review]

**Comment by patpol4** [comment]
Maybe it fits but it's pretty bad ngl

**Comment by ThatGuyPhil** [comment]
understandable have a good day

**Pull request closed without merging**
