### PR TITLE
Adds toggleable movement animations.

### PR DESCRIPTION
**Pull request by GuppyLaxx**
Ported from https://github.com/Baystation12/Baystation12/pull/22068 ! 😄 

Can be toggled in the secrets menu, requires +FUN to use.
I can move it to the Fun thing in client instead if you wanna go the extra mile in modular

### CODE REVIEW

**Comment by Altoids1** [comment]
Does it look ok on non-humanoid mobs?

**Comment by GuppyLaxx** [comment]
it in fact looks amazing

**Comment by Altoids1** [comment]
Including Bubblegum or the other multi-sprite mobs?

**Comment by GuppyLaxx** [comment]
It shouldn't, no. Most it should do is make the charging look slightly odd for a bit and that's all

**Comment by HeyBanditoz** [comment]
Oh wow you guys were quick

**Comment by GuppyLaxx** [comment]
i keep up with bay, even for the non-memey stuff 😉

**Comment by Ratvar** [comment]
Autoenable on clumsy people even if it's off, let clown toggle it

**Comment by Sbotkin** [comment]
@HeyBanditoz because this is next level shit and needs to be merged into all servers asap!

**Review by ThatLing — CHANGES_REQUESTED** [review]
Refer to https://github.com/tgstation/tgstation/pull/38817.
I don't like you overriding Move() to check for something that won't be enabled 99.9% of the rounds. If you make this using components I'd gladly merge this (I think someone even posted the component code in /tg/ discord). But in it's current state, no.

**Comment by Colburn3000** [comment]
:(

**Comment by ThatLing** [comment]
Stale, feel free to re-open or make a new PR when you are working on this again.

**Pull request closed without merging**
