### PR TITLE
Commits the new yarn.lock file per Alex's and Bibby's suggestion

### PR DESCRIPTION
**Pull request by Hopekz**
Follow-up to #13618
image

image

### CODE REVIEW

**Comment by Altoids1** [comment]
Annoying that this file is both one that
- Actually can meaningfully affect the result of a build, and 
- is basically automated garbage clogging my unstaged diffs

very anti-git IMO

**Comment by Hopekz** [comment]
> very anti-git IMO

I would have gotten away with ignoring it forever if it weren't for those meddling kids ):<

IMO this file should be git ignored then a maintainer or HC (or script) pushes out a new  file once in a while

**Review by Bibby0110 — APPROVED** [review]

**Comment by alexkar598** [comment]
> Annoying that this file is both one that
> - Actually can meaningfully affect the result of a build, and 
> - is basically automated garbage clogging my unstaged diffs
> 
> very anti-git IMO

> complains about non reproducible builds/security issues because of dependencies updating thanks to semver

"wtf is this bullshit, javascript bad"
> adds a lock file for dependency pinning except when explicitly updating

"wtf is this bullshit, javascript bad"


Lock files are a must for any language with dependencies managed by a package manager.

**Comment by alexkar598** [comment]
Also lock files dont change unless asked to. I believe someone merged a dependabot PR without looking so yarn started trying to fix the lock file to match the new dependencies

**Comment by Simplehorror** [comment]
Would not be an issue if TGUI did not require a million libraries for fancy buttons

**Pull request merged**
