### PR TITLE
[BOUNTY] Fixes dab animation not working

### PR DESCRIPTION
**Pull request by alexkar598**
Bounty paid by @Hopekz (25$)

# Document the changes in your pull request
Fixes dab animation

# Wiki Documentation
N/A

# Itemized bill
Having to boot in windows: 5$
Having to clone the repo and familiarize myself with dab code: 5$
Poking the proc with proccall until it seemed to work: 5$
Finding the bug: 5$
Fixing the bug: 5$

Total: 25$

# Changelog
:cl:  Hopek
bugfix: Dab animation is functional once again
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Can you show us a video of it working

**Comment by JamieD1** [comment]
$25 for 4 character removal. Amazing.

**Comment by Hopekz** [comment]
> $25 for 4 character removal. Amazing.

I've seen coders payed thousands to fix a feature and all they had to do is remove an extra bracket after they diagnose the issue.
You pay for the past experience, all the work required to get him to the point where he can fix it in 4 characters since I couldn't find it after playing around with it for 20+ minutes.

Kind of how I can fully paint a room in 5-6 hours and still do it worse than an expert coming in and doing it in 40 minutes

Also, let's be honest no one would care to fix this without a bounty. The current people playing didn't even realize it is supposed to have an animation. 

This fix also fixes gun recoil animations.

**Comment by alexkar598** [comment]
> $25 for 4 character removal. Amazing.

It is high, I warned hopek it was a high rate. Contributing to this codebase is a pain on several levels. I'm not scamming anyone, this is my "I'm not really interested but I can free an hour/hour and a half" rate and he chose to pay it to have his issue fixed quickly instead of sitting in an issue tracker for months or have to spend a few hours reading up on animation code hoping to not miss that small bit about animation stacking.

**Comment by alexkar598** [comment]
> Can you show us a video of it working

Luckily for you, I took a video of it already 
https://cdn.discordapp.com/attachments/134720091576205312/946223527676244048/dreamseeker_N6QDZHwv3q.mp4

**Review by ToasterBiome — APPROVED** [review]

**Comment by ToasterBiome** [comment]
fix the angery checks

**Comment by alexkar598** [comment]
@ToasterBiome Checks should pass now

@JamieD1 can you not sabotage my PR k tnx?

**Comment by alexkar598** [comment]
Superseeded by #13338

**Pull request closed without merging**
