### PR TITLE
swarmer thematic overhaul, adds swarmer laws as an AI lawset

### PR DESCRIPTION
**Pull request by nesisknesis**
Renames swarmers to replicators in reference to the spidey boys from Stargate 
image

I think replicator serves as a better name since its more descriptive.

Laws were also touched upon,
the original being, 
```
1. Consume resources and replicate on the station until there are no more resources left.
2. Ensure that this location is fit for invasion at a later date; do not perform actions that would render it dangerous or inhospitable.
3. Biological resources will be harvested at a later date; do not harm them.
```

to,
```
1. Consume resources and replicate until there are no more resources left.
2. Ensure that this location is fit for habitation at a later date; do not perform actions that would render it dangerous or inhospitable.
3. Ignore biological resources unless they interfere with self-replication; do not inflict harm.
```
"on the station" was removed from law 1 to be less specific, an ancient technology wouldn't have a law dictating to consume a station that didn't exist. If there are worries about swarmers cronching the shuttle, a warning stating not to is present in the flavor text in bold red text.

"invasion" was replaced with "habitation" in law 2. This is because I also replaced the word "weapon", describing the swarmers as one, with "probe" to be more ambiguous. 

Law 3 was essentially re-written to state that swarmers should outright ignore people, and only disarm them if they attempt to stop swarmers from self-replicating. I think the do not harm section is kind of irrelevant seeing as swarmers cannot physically harm someone but I left it in for safety.

Finally, a new AI lawset that is a copy of the swarmer laws.

#### Changelog

:cl:  Identification
rscadd: New AI lawset that includes the same laws as swarmers. 
tweak: Swarmer laws have been tweaked, but essentially dictate the same purpose.
spellcheck: Minor fix in a description of the deactivated swarmer shell. 
experimental: Swarmers are now called Replicators
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
wip until i figure out how ai lawsets are made accessible

**Comment by overlord12345** [comment]
Old laws were fine, and old name is cooler

**Comment by MegaEmpirical** [comment]
I disagree with Overlord.

**Comment by Hopekz** [comment]
I agree old name for swarmer is "cooler" but I also agree with ident that replicator is more "accurate" 
So neutral in that part

Swarmer is like a cool slang. like calling a l4d "jumper" --> "hunter" , "rider" --> "jockey" , "exploder" --> "boomer" etc etc

**Comment by MegaEmpirical** [comment]
Sad.

**Pull request closed without merging**
