### PR TITLE
This must be the work of an enemy stand

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
tweak: Fluke ops can now buy holoparasites to live out their fantasies of being dead
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
image

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
image

**Comment by HomocidlePancakes** [comment]
Wot. Pretty sure they were always available to ops. And if they somehow got removed it’s most likely due to support being a massive cheese

**Comment by SomeguyManperson** [comment]
So basically what happened:
Prebase holoparasites were made available to only ops
On rebase, holoparasites were restricted to only tots
A pr was made and merged to change this back
For some reason some upstream merge tomfoolery set it back

**Comment by ThatLing** [comment]
@SomeguyManperson Link to the PR that unrestricted it?

**Comment by SomeguyManperson** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/3814 returned it to tot only restriction

**Pull request merged**
