### PR TITLE
Shuttle now takes 20 minutes instead of 2 minutes to arrive to Central Command

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

appeasing yogurt, our lord
XwO59mp

#### Changelog

:cl:  
tweak: Shuttle now takes 20 minutes instead of 2 minutes to arrive to Central Command
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
Absolutely terrible idea what the fuck are you supposed to do for these 20 minutes

**Comment by Featherfield** [comment]
Immersive and RP worthy

**Comment by ynot01** [comment]
> Absolutely terrible idea what the fuck are you supposed to do for these 20 minutes

praise moja for 20 minutes

**Comment by Moja10** [comment]
this will drastically increase RP, get to say your goodbyes to crewmembers, things will be more heartfelt

**Comment by monster860** [comment]
wtf

**Comment by Hopekz** [comment]
How about the shuttle being a mini station that everyone can still "work" in.
That way you can have some stupid amount of time to arrive like even 30 min but have it be integrated in to gameplay.

**Comment by Ktlwjec1** [comment]
no

**Pull request closed without merging**
