### PR TITLE
Fixes the CE's holosign creator

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

This has been broken since it was added and no one seemed to have noticed, well **I** did when I was looking into a bug report on update_appearance.
Also adds autodoc and repaths the item so vscode doesn't treat it like a define.

before
image

after
image

# Changelog

:cl:  
bugfix: The CE's holosign creator now doesn't give you the raw path of the sign it is creating.
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
can you rename it to advanced instead of CE because it gets used in places that arent just the CE locker (out of scope 🥺)

**Comment by Maia-J** [comment]
> well I did when I was looking into a bug report on update_appearance.

Can you link this bug report?

**Comment by JohnFulpWillard** [comment]
https://github.com/yogstation13/Yogstation/issues/19702

**Comment by JohnFulpWillard** [comment]
> can you rename it to advanced instead of CE because it gets used in places that arent just the CE locker (out of scope 🥺)

done and i also made them call parent so they respect signal and nointeract trait

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
