### PR TITLE
Zombies can no longer pull objects

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Can't balance zombies if they can stun people with water tanks.

# Changelog

:cl:  
tweak: Zombies can no longer pull objects
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
problem is, without welding tanks there's literally nothing they can do to get through walls, if zombies start taking over, just rcd a wall around evac and you're good

**Comment by Simplehorror** [comment]
> problem is, without welding tanks there's literally nothing they can do to get through walls, if zombies start taking over, just rcd a wall around evac and you're good

you can still shove them

**Comment by Moltijoe** [comment]
> you can still shove them

the vast majority of welding fuel tanks are in corners, you can't shove them out of corners
not to mention that even if they weren't, most are in maints, where they'd quickly get stuck
also, i don't think zombie can shove

**Comment by Simplehorror** [comment]
they're not meant to break walls

**Comment by Moltijoe** [comment]
> they're not meant to break walls

If theres an easy way for a single person to basically save most of the station, that sounds boring

**Comment by Burger1998** [comment]
ided

**Comment by ShoziOffical** [comment]
Lol zombies only have their claws, why they need to be balanced?

**Comment by Moja10** [comment]
Cringe change, zombies have basically nothing at the moment to kill anyone but the most incompetent validhunters or people completely unaware of their existence

**Comment by Sniblet** [comment]
I tried to chase down and kill a zombie callout as a doctor once and lost because he was actually thoughtfully prepared while I only brought my saw :(

**Pull request closed without merging**
