### PR TITLE
Ports catwalk tiles from AI Rework 3.5

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Steals the catwalk tile code from https://github.com/yogstation13/Yogstation/pull/16876
I wanted these for a while but ai rework was preventing them from being in the game

# Spriting

will get screenshots in a second

# Changelog

:cl:  
rscadd: Adds catwalk tiles, which are tiles that can be opened and closed, protecting the pipes/wires underneath.
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
how do you build them

**Comment by Bibby0110** [comment]
Credit the original authors

**Comment by Firewolf34** [comment]
Love this idea.

**Comment by ReddicusDragon** [comment]
feature freeze

**Comment by JamieD1** [comment]
Wheres the pics

**Comment by Bibby0110** [comment]
> Wheres the pics

on the AI pr

**Comment by JamieD1** [comment]
wheres the sprites

**Comment by ReddicusDragon** [comment]
this is stale

**Comment by ReddicusDragon** [comment]
Closing in 24h due to no response from Byemoh in 3 weeks

**Comment by ReddicusDragon** [comment]
Closed due to inactivity.

**Pull request closed without merging**
