### PR TITLE
Gives us a bit of memory wiggle room

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Changes the amount of random ruin z levels from 7 to 4,

Also disables hotel from being able to spawn

This will hopefully reduce memory usage and make it so we crash less due to OOM

#### Changelog

:cl:  
bugfix: Changed z level ruins from 7 to 4
/:cl:

### CODE REVIEW

**Review by alexkar598 — APPROVED** [review]

**Comment by ynot01** [comment]
powergamers BTFO

**Comment by boodaliboo** [comment]
stupid pr this is bad and it removes alot of fun from curators and shaft miners

**Comment by boodaliboo** [comment]
a good way of giving us more wiggleroom is to use youtube-dls for the disco songs instead of having them stored

**Comment by JamieD1** [comment]
> a good way of giving us more wiggleroom is to use youtube-dls for the disco songs instead of having them stored

You alright bood?..

Thats not memory..

**Comment by boodaliboo** [comment]
fuck you alex

**Pull request merged**
