### PR TITLE
Surgical Toolset Implant Tools Can Be Replaced With Alien Tools

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
You can now replace the normal/augment surgery tools in your surgical toolset implant. To do this, attack the augmented surgery tool with its alien version.

# Why is this good for the game?
Makes people who use surgical toolset implant not feel so bad when the rare alien tech is researched.

# Changelog
:cl:  
rscadd: You can replace the surgery tools in your surgical toolset implant with the alien version.
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
That reminds me I should give it a emag effect

**Comment by MajManatee** [comment]
Why not made it doable with any level of tool?

**Comment by Runian** [comment]
> Why not made it doable with any level of tool?

Because that would be downgrading since not many tools have a tool speed better than 0.5.

**Comment by Moltijoe** [comment]
Balance Council:
>The downside of alien tools is that they're rare and powerful, but they take up more space than the advanced tools, this removes that potential downside and threatens to make the implant more powergamey than it already is

**Pull request closed without merging**
