### PR TITLE
Renames the incinerator mouse to Becquerel

### PR DESCRIPTION
**Pull request by athena413**
also gives them their own examine text

context; becquerel is the guy that kind of discovered radiation
#### Changelog

:cl:  
tweak: incinerator mouse now has a name and examine text
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
We need a mouse named Oppenheimer somewhere too

**Comment by athena413** [comment]
> We need a mouse named Oppenheimer somewhere too

that was my first idea but i felt like directly referencing a player would not be the best thing

**Comment by Jarod1200** [comment]
Perhaps but also Oppenheimer was a science dude who did in fact unleash the power of the sun.

**Comment by boodaliboo** [comment]
i dont like this name

**Comment by ynot01** [comment]
no one knows who becquerel is

**Comment by Ratvar** [comment]
I believe more people will think this is a homestuck reference

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
