### PR TITLE
lavaland movespeed is now the same as on /tg/

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Well, as the title states, this makes our movespeed be the exact same as the default is, so that fighting megafauna isn't complete trash. 

#### Changelog

:cl:  
tweak: lavaland now has weaker gravity (you move faster)
/:cl:

### CODE REVIEW

**Comment by Gintoki1** [comment]
Colossus will now be killable, bloodminer, and dance dance remix boss as well will be more doable ! HYPERPOGGERS •3•!

**Comment by ThatLing** [comment]
not happy

**Comment by drderp3635** [comment]
Creative and good fix 👍

You probaby want to change the other lavaland stuff to match though

**Comment by Amelia0010** [comment]
what other lavaland stuff?

**Comment by SomeguyManperson** [comment]
colossus got nerfed to work better with yogs speed so that might need to get reverted to make it not a free VoG
specifically #1702

**Pull request merged**
