### PR TITLE
Minor bloodbrother rework

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Syndicate realised that it is a very bad idea to send their agents on a mission without any cool toys, so now:
Bloodbrothers now would have a roundstart storage implant, containing one random low-cost traitor item!
Possible items:
Syndie-soap, sleepy pen, e-dagger, codespeak manual, noslip chameleon shoes, armor polish, box with 3 c4, box of throwing weapons, toy c20r, emp kit, agent card, reverse card, ai detector, chameleon kit, syndie smokes.

# Wiki Documentation

Write about this on wiki???

# Changelog

:cl:  
rscadd: Now bloodbrothers start with a storage implant, containing one random lowcost traitor item
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Actually it was meant to make them get more powerful items to the pool if they gain a hijack objective, but i don't know how to do this.

**Comment by DylonBR** [comment]
make them have makeshift weapons by default

**Comment by ghost** [comment]
> make them have makeshift weapons by default

Okay

**Comment by JamieD1** [comment]
@SomeguyManperson

**Comment by SomeguyManperson** [comment]
prefer #14094 to this since it's more of an antag concept to play around than having a single random traitor item

**Pull request closed without merging**
