### PR TITLE
Gathering of the Old Gods Religious Sect

### PR DESCRIPTION
**Pull request by Marmio64**
A new sect that will allow you to bless meat upon your altar and sacrifice it in order to get ruinous metal, which is used for healing fountains that can heal you but damage your mental health, and additional altars to place wherever you'd like.  You can also use favor for cool cult knives that don't do anything special, and have a mediocre amount of damage (12)

~~Ruinous metal can also be used to make special golems that move slightly slower than average, but are tougher and have a weakened voice of god ability. Though, there is no way to make golem shells using the sect so you'd have to work together with xenobiology~~ Ruinous metal can still be used to make golems but you can also turn people directly into golems for a higher price. Golems also lost their slowdown and voice of god but now talk loud and cool (cosmetic only) and have telepathy.

oldgodsaltar

# Wiki Documentation
I think I've said everything that could be said in the wiki already.

# Changelog

:cl:  
rscadd: Adds the gathering of the old gods religious sect. Loosely Lovecraftian.
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
I want you to stop, and consider: Hydroponics can make infinite monkey cubes, and each monkey gives - I think - three slabs of meat when butchered. And they can make those cubes faster than you can butcher the monkeys, once they get rolling.
So making a sect that runs entirely on meat might not be a great idea.

**Comment by Marmio64** [comment]
already responded to the above on discord but ill say it here too that the candle sect and kudzu sect already allow you to do that

**Comment by Marmio64** [comment]
the ruinous golem has received some changes, read the commit description for more info

**Review by nesisknesis — APPROVED** [review]
this shall pass i think

**Comment by tralezab** [comment]
I just wanted to say that as someone who spent a large amount of time working on sects and expanding the system, this is really antithetical to the actual design of changing how the chaplain acts and plays to give their religion flavor as you're just turning it into a sect-enabled skinner box.

I'm gonna cite the Punished God as an example of a good, gameplay and flavor modifying sect:
https://github.com/tralezab/tgstation/blob/6040a4a7306e7d3d28e05f4f77634980ee6c2652/code/modules/religion/religion_sects.dm#L307

**Comment by Marmio64** [comment]
> I just wanted to say that as someone who spent a large amount of time working on sects and expanding the system, this is really antithetical to the actual design of changing how the chaplain acts and plays to give their religion flavor as you're just turning it into a sect-enabled skinner box.
> 
> I'm gonna cite the Punished God as an example of a good, gameplay and flavor modifying sect:
> https://github.com/tralezab/tgstation/blob/6040a4a7306e7d3d28e05f4f77634980ee6c2652/code/modules/religion/religion_sects.dm#L307

i've been going off of the original sects which mostly just gave you stuff to do and if you did it you got a reward, but I could maybe change the sect to be more based on your brain health or something so that the playstyle would be managing your brain health in order to use the abilities.

**Comment by adamsong** [comment]
Works with synth meat
image

**Comment by Marmio64** [comment]
> Works with synth meat
> image

intended, but im thinking of reducing synth-meats value and maybe increasing the value of other meats, since it seems that everyone just goes straight for synth meat (myself included)

**Comment by adamsong** [comment]
Also, make it not mute the chaplain

**Comment by Marmio64** [comment]
> Also, make it not mute the chaplain

dont think thats possible, gotta work around it by saying something else every once in a while, or i'll have to just make it so you dont say anything for the rite

**Comment by adamsong** [comment]
Give it a random line, so it changes each time
Also, gloves of the north star don't mute (I'm pretty sure) so maybe look at that

**Comment by Marmio64** [comment]
> Give it a random line, so it changes each time
> Also, gloves of the north star don't mute (I'm pretty sure) so maybe look at that

I already commited a fix quite a while ago

**Comment by Marmio64** [comment]
new information: golems are now nerfed to 40 armor, but gain a slight speedboost (1.5 instead of 2) and have the flagellate ability. Flagellete is mostly useless but a good flavor ability that lets them inflict some pain on a disobedient. Synth meat is now heavily nerfed and only gives 10 favor per slab, while normal meat is buffed to 75 favor.

**Comment by Marmio64** [comment]
think ive fixed the outstanding issues and made sure theres enough content here. Ready to be merged whenever the code gods feel like it.

**Comment by Marmio64** [comment]
this isn't even testmerged whys it still got the testmerged label

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
@Marmio64 Can you fix conflicts then it will auto merge. Please do them right.

**Pull request merged**
