### PR TITLE
WIP grinch antag

### PR DESCRIPTION
**Pull request by boodaliboo**
this antag is meant to be the opposite of santa and cause misery. im trying to make it so they cant kill to do so

current to dos
make him green in someform
get him a event
get him to spawn during christmas
whatever people suggest
#### Changelog

:cl:  
rscadd: Added the grinch
wip: This is work in progress  
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Sounds like a "go be a dick" antag

**Comment by boodaliboo** [comment]
> Sounds like a "go be a dick" antag

thats the point its a go be a dick antag without the murder

**Comment by Hopekz** [comment]
Can't murder?
Alright, valid squad lets get him he can't murder us!!

**Comment by boodaliboo** [comment]
> Can't murder?
> Alright, valid squad lets get him he can't murder us!!
>  

IT PASSES TRAVIS FIRST TRY

**Comment by Marmio64** [comment]
make him have objectives to steal non important things and things that arent weapons, so no stealing traitor objectives or stunbatons or shit but it can steal heads of staffs cloaks, insuls, diamonds, cash, all that shit. Could also have a goal to just spraypaint random shit and vandalize in minor ways like smashing windows and breaking hallway doors apart. Also let him murder people in self defense only, a sec officer trying to arrest you does not warrant death but a sec officer shooting you with a laser gun does.

He should start with a grinch ID card that has maint on it, some grinch clothes and bag, and maybe 'knock' like waldo has or maybe a getaway spell like blink.

**Comment by boodaliboo** [comment]
not sure how to get a bunch of different antag objectives instead of just one but love that idea

**Comment by boodaliboo** [comment]
ill reopen this when its done dont want prs open if their not finished

**Pull request closed without merging**
