### PR TITLE
Revert "Ports 3/4 crates sprites and mule bot from FTL13"

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
Seen these crates a few times in-game, they are very jarring and don’t really fit with anything around them and the perspective suddenly swapping on just these crates also feels a bit off.

### CODE REVIEW

**Comment by tattax** [comment]
lockers and coffins literally already had the front-up view, crates were the one missing out, not vice-versa

**Comment by JamieD1** [comment]
Oof, will need Cuackles and maybe parth or ident to chime in here.

**Comment by cuackles** [comment]
> Oof, will need Cuackles and maybe parth or ident to chime in here.

thinking of it, im ok with both but one has to be better for the game but i cant decide wich one

**Comment by KillerOrcaCora** [comment]
The point of this PR is to go back to the old perspective, I can easily resprite the looks of the newer crates onto the old ones but rather have one perspective overall for crates.

**Comment by KillerOrcaCora** [comment]
After discord vote, will be making a new PR to revert back to the old perspective but also take some of the aspects people wanted from the new one to make a compromise for both groups.

**Pull request closed without merging**
