### PR TITLE
adds the ability to tickle feet (req. by Ktlwjec1)

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

adds the ability to tickle feet, requested by user Ktlwjec1 via bounty (prepaid)

#### Changelog

:cl:  
experimental: This is experimental  
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
AAAAAAAAAAAAAAAAAAAAAAAHHHH

**Comment by DerelictDrone** [comment]
Add the ability to tickle drones next.

**Comment by overlord12345** [comment]
no

**Comment by GoreDem** [comment]
Why

**Comment by fluffe9911** [comment]
no

**Comment by Hopekz** [comment]
@fluffe9911 24H rule open er back up

**Comment by nesisknesis** [comment]
Duel_on_Coruscant

no

**Comment by SomeguyManperson** [comment]
No

**Pull request closed without merging**
