### PR TITLE
Sunders mentions of "Trey" the lizard wizard

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
Removed the following:
- A simplemob called "Trey of the Shattered Voice"
- Icon file for said mob
- Paper for a removed ruin referencing the character

# Why is this good for the game?
whilst perusing the code I found what I'm pretty sure is a player reference, some kind of stuttering lizard wizard
I know not of this man, but I'm pretty sure player references are a no-no, and this one was probably missed when the rest of the wizard academy was expunged

# Testing
these are just deletions, but I can if ye really want me to

# Changelog
:cl:  
rscdel: Deleted a simplemob referencing someone
imagedel: Deleted images said simplemob were using
/:cl:

### CODE REVIEW

**Comment by Darkstick** [comment]
that's me ;-;
I was excluded from the purge back when it happened, a long time ago. I think it's because I was so active all the time, and also because I was so popular and liked. You'd have to ask whoever deleted all the player references back then to know for sure.

**Comment by Moltijoe** [comment]
Player references are best when theyre unrecognizeable

**Comment by azzzertyy** [comment]
can you remove moja while youre at it then

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]
sad

**Comment by Firewolf34** [comment]
Aww... :( this one hurts the soul. Time continues on, Trey, but I'll remember! You left your mark on all our hearts. <3

**Pull request merged**
