### PR TITLE
Fixes happy cluwne mask, removes the shitcode and documents it

### PR DESCRIPTION
**Pull request by alexkar598**
Way less shitcody now, also it works also this is a bounty PR

### CODE REVIEW

**Comment by Marmio64** [comment]
what does this do though. And you say its a bounty but dont link anything? You made ynot put a description in his narsie gets killed by singularity PR why should this be any different.

**Comment by alexkar598** [comment]
It actually works now, also theres nothing to link, it used to just make you a cluwne 100% of the time instead of the intended 1% and 0.1% to spawn a floor cluwne, now it works as intended

**Comment by maxion12345** [comment]
where changelog

**Review by fluffe9911 — APPROVED** [review]
Ok

**Pull request merged**
