### PR TITLE
Plasma Glacite Part 2: Glacite EVERYTHING

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

Adds glacite versions of every upgradable mining tool, you can now get a glacite plasma cutter, glacite plasma shotgun, and a glacite KA, aswell as the already in the game glacite crusher.

Screenshot 2024-10-13 195838

# Why is this good for the game?
They're pretty AF and it's a bit lazy to use the same sprites for every version of magmite guns.

# Testing
Tested, everything works (somehow)

# Spriting
All 3 guns
Screenshot 2024-10-13 195838

Plasma cutter showcase

https://github.com/user-attachments/assets/6417674a-33d6-4f8a-94f6-e57fd04266ba

Plasma shotgun showcase

https://github.com/user-attachments/assets/15bb2846-c28d-47dc-96af-55f94338b602

KA Showcase

https://github.com/user-attachments/assets/3235832c-e388-40cf-97bc-8df4ad803ddd

# Wiki Documentation

Wiki reach out to me and I'll start finally working on the icemeta page

# Changelog

:cl:
rscadd: glacite plasma cutter shotgun, glacite plasma cutter, glacite KA
imageadd: sprites for new glacite weapons
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
Just waiting for the next magmite to turn the weapons into the half life alien weapons

**Comment by N3D6** [comment]
> Just waiting for the next magmite to turn the weapons into the half life alien weapons

Jungle shittite when

**Comment by wonderinghost** [comment]
Jungle galungtite

**Review by ToasterBiome — APPROVED** [review]
can't get worse

**Pull request merged**
