### PR TITLE
Exploding the SM with 50% miasma and 5000 moles will spawn a Blob

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
As title, when the SM has 50% miasma in its environment and 5000 total moles a blob will spawn, this is fairly difficult to do and i dont forsee it ever really happening but it can, and its funny.

The blob has 350 starting resource and a flat 1.5x point increase to make up for the fact it spawns in an incredibly compromising area and the crew will instantly know its location, as well as the fact it has 3 emitters pointed directly at its core

# Why is this good for the game?
Its funny, more interesting SM delams.

# Testing
Works

# Wiki Documentation
Add that SM's will spawn blobs when they have 50% miasma in them and atleast 5000 moles

# Changelog
:cl:  @Simplehorror, @azzzertyy 
rscadd: SM delams with miasma will now spawn a blob
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Really good feature, one of those "1 in 1000 rounds" type of events that gives SS13 its spice of life

**Comment by ShoziOffical** [comment]
> Really good feature, one of those "1 in 1000 rounds" type of events that gives SS13 its spice of life

1000 rounds you will get ~200 sm normal delams and ~150 blob midround spawn so yeah it will still be a normal ss13 experience

**Comment by iloveloopers** [comment]
2500+ mols of miasma means this is practically locked behind the HFR. Good PR. Atmos must have a monopoly over special SM delams

**Comment by ShoziOffical** [comment]
> 2500+ mols of miasma means this is practically locked behind the HFR. Good PR. Atmos must have a monopoly over special SM delams

I'm glad it has the recipe for it because 200 monkies in one chamber will require botany or xenobio shit

**Comment by ShoziOffical** [comment]
But this delam could be prevented by spacing it even when you reach the requirements, unlike antinoblium delam once you hit the requirements shit cannot be stopped

**Comment by azzzertyy** [comment]
> 2500+ mols of miasma means this is practically locked behind the HFR. Good PR. Atmos must have a monopoly over special SM delams

the level 100 botanist with max potency max yield max every stat corpse flowers in question:

**Comment by Yarinoi** [comment]
finally corpse flowers have a use 🥲

**Comment by ShoziOffical** [comment]
botanist has to become an engineer then

**Comment by SomeguyManperson** [comment]
watching the atmos tech with martyr fill the supermatter with miasma before jumping into it to also get a chance to become the blob they made (which has buffed stats) and kill everyone instead of needing to vaguely impact the destination of a singularity or tesla

**Comment by ShoziOffical** [comment]
> watching the atmos tech with martyr fill the supermatter with miasma before jumping into it to also get a chance to become the blob they made (which has buffed stats) and kill everyone instead of needing to vaguely impact the destination of a singularity or tesla

Yeah this sounds like a neat idea

**Comment by iloveloopers** [comment]
> watching the atmos tech with martyr fill the supermatter with miasma before jumping into it to also get a chance to become the blob they made (which has buffed stats) and kill everyone instead of needing to vaguely impact the destination of a singularity or tesla

you're competing against 10 other ghosts at minimum

**Comment by ShoziOffical** [comment]
> > watching the atmos tech with martyr fill the supermatter with miasma before jumping into it to also get a chance to become the blob they made (which has buffed stats) and kill everyone instead of needing to vaguely impact the destination of a singularity or tesla
> 
> you're competing against 10 other ghosts at minimum

should be like a 5% chance for the guy that dusts himself

**Comment by ShoziOffical** [comment]
cool concept but i dont like how its coded, because its simple horror's old pr. It's TOO easy to prevent the delam from happening, for the code i can tell you have a lot of times to prevent this from 100% integrity to the moment when the countdown starts, you can still space it in time to prevent the blob delam, technically this delam can happen with any other delams like resonance cascade, singulo or even tesla

**Comment by SomeguyManperson** [comment]
> cool concept but i dont like how its coded, because its simple horror's old pr. It's TOO easy to prevent the delam from happening, for the code i can tell you have a lot of times to prevent this from 100% integrity to the moment when the countdown starts, you can still space it in time to prevent the blob delam, technically this delam can happen with any other delams like resonance cascade, singulo or even tesla

shouldn't overlap with other delaminations since it's both first and returns when finished spawning the blob and deleting the supermatter

**Comment by ShoziOffical** [comment]
> > cool concept but i dont like how its coded, because its simple horror's old pr. It's TOO easy to prevent the delam from happening, for the code i can tell you have a lot of times to prevent this from 100% integrity to the moment when the countdown starts, you can still space it in time to prevent the blob delam, technically this delam can happen with any other delams like resonance cascade, singulo or even tesla
> 
> shouldn't overlap with other delaminations since it's both first and returns when finished spawning the blob and deleting the supermatter

i mean when you put more supermatter in the chamber with it and seperate the supermatter gas

**Comment by iamthesilly** [comment]
Miasma decays to oxygen at the temperatures needed for it to delaminate in the first place so I doubt this is even possible to achieve without using hypernoblium.

Also the SM chamber has 9 tiles which spreads out the gas you add to it, so to have 5000 moles per tile you'd actually need a total of 45,000 moles unless you're using a custom setup.

**Comment by ShoziOffical** [comment]
> Also the SM chamber has 9 tiles which spreads out the gas you add to it, so to have 5000 moles per tile you'd actually need a total of 45,000 moles unless you're using a custom setup.

i mean i can jus make it a 1x1 for the blob-sm one instead of 9x9, also for some reason there would be a fire when the sm core is placed resulting the blob getting killed on the tile

**Comment by ShoziOffical** [comment]
> Miasma decays to oxygen at the temperatures needed for it to delaminate in the first place so I doubt this is even possible to achieve without using hypernoblium.

this can be avoided easily, delam sm integrity to 0% once it starts counting, space the chamber and flow in miasma

**Review by Moltijoe — APPROVED** [review]

**Comment by Simplehorror** [comment]
Thanks for the credit

**Pull request merged**
