### PR TITLE
Add missing chat preferences

### PR DESCRIPTION
**Pull request by ThatLing**
# Document the changes in your pull request
Forgot these with new preferences

# Changelog

:cl:  
rscadd: You can once again toggle LOOC, typing indicators and ghost ckey preferences
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
typing indicator toggle is incorrect, toggling it makes all typing indicators invisible to you, and you still produce them.

**Review by ToasterBiome — DISMISSED** [review]
add a description for the typing indicator toggle

**Comment by MajManatee** [comment]
> typing indicator toggle is incorrect, toggling it makes all typing indicators invisible to you, and you still produce them.

pretty sure that's intended, no?

**Comment by ToasterBiome** [comment]
> > typing indicator toggle is incorrect, toggling it makes all typing indicators invisible to you, and you still produce them.
> 
> pretty sure that's intended, no?

yeah he had the wrong description

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
description for indicator toggle

**Comment by MajManatee** [comment]
:waaa:

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
