### PR TITLE
Bloodsucker patch

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

stuff

# Wiki Documentation

# Changelog

:cl:  
bugfix: bloodsucker mobs no longer take their attack damage as unarmed damage when punched
bugfix: possessed armor will no longer activate and target restrained people, and will not attack bloodsuckers
tweak: rabidism no longer causes you to attack yourself
bugfix: tear now actually works
tweak: rewriting and spellchecks in some descriptions
tweak: both wolf head accessories now provide armor to the head
/:cl:

### CODE REVIEW

**Comment by LazennG** [comment]
'sorry im late i was doing stuff'
"im stuff"
'omg blooduckers no!'
haha theos you are unshitting the gamemode

**Comment by Simplehorror** [comment]
wtf happened in this branch

**Comment by UltraBigRat** [comment]
Should also probably wiki document the possessed armor stuff  if this gets merged

**Review by MajManatee — APPROVED** [review]
im stuff
also i hate whitespace

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
