### PR TITLE
removes monkey gamemode

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

:)

#### Changelog

:cl:  
rscdel: monkey gamemode gone
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
why?

**Comment by boodaliboo** [comment]
Bad pr

**Comment by ynot01** [comment]
why?

**Comment by Amelia0010** [comment]
image
image

9 times, in a year and a half.

**Comment by boodaliboo** [comment]
Do more rounds then

**Comment by Amelia0010** [comment]
Not my responsibility.

**Comment by Readystorm546** [comment]
I agree with this

**Comment by Hopekz** [comment]
This is a poo poo PR. Lets remove Thanos mode too since we only had that round once in a year and a half under that logic.

**Comment by yacabo** [comment]
Unless this gamemode is breaking something there is no need to remove it.

**Comment by Amelia0010** [comment]
@Hopekz We don't have a Thanos gamemode.

**Comment by Hopekz** [comment]
> @Hopekz We don't have a Thanos gamemode.

Okay Nations. You know what I meant not sure why you are technically picking apart my sentences much like a robot instead of taking the meaning of my message.

**Comment by Amelia0010** [comment]
We don't have nations either. And I am picking apart your sentence because your whole point is predicated on "if we have X, why are you removing Y", when we don't actually have X.

**Comment by Hopekz** [comment]
> We don't have nations either. And I am picking apart your sentence because your whole point is predicated on "if we have X, why are you removing Y", when we don't actually have X.

You have a good point and I have no retort. My argument is very weak in this instance.
Thank you!

**Comment by neeshacark** [comment]
under this logic we can finally remove mothpeople and clerk

**Pull request merged**
