### PR TITLE
Adds a new drink: Cilk (cola milk)

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

**SOUND THE ALARMS!!**

Adds a new drink called Cilk, or Cola Milk.

This drink can be synthesized with 1 part milk and 1 part space cola.

This was tested

# Wiki Documentation

Add the recipe for cilk in the drinks page, 1 part milk, 1 part cola

# Changelog

:cl:  
rscadd: Added cilk
imageadd: Added sprites for cilk
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Do you not fear God's judgement on your immortal soul?

**Comment by cuackles** [comment]
Make it do brain damage

**Comment by Anvilman6** [comment]
I'm crying and vomiting

**Comment by N3D6** [comment]
> Do you not fear God's judgement on your immortal soul?

God has inspired me to do this

**Review by nesisknesis — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
