### PR TITLE
Revert "Changes Antag Coefficient to increase traitor, changeling and blood brother population relative to total station population (Increases total number of atnags"

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Reverts yogstation13/Yogstation#17905
It sucked

:cl:
tweak: blood brothers and changelings scale slower
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Its been great, you are smoking crack, don't full revert if you think its too high. Just tweak the numbers a little. Previous was way too low and resulted in greenshifts if sec was successful whatsoever at their job.

**Comment by MegaEmpirical** [comment]
More antags bad

**Comment by solwashere** [comment]
If I have to suffer through one more round with 10 antagonists on like 30-40 pop I'm going to lose it

**Comment by MajManatee** [comment]
if I have to suffer through one more greenshift on 60 pop I'm going to go postal

**Comment by PibeCantina** [comment]
It doesnt need to be reverted, just need to lower the rates a bit, before it was too little, now it's too much, we need to find the sweetspot.

**Comment by Therandomhoboo** [comment]
The only people that dislike the revert are the ones that antag-roll go figure

**Comment by stwordcitizen** [comment]
> If I have to suffer through one more round with 10 antagonists on like 30-40 pop I'm going to lose it

I'd be ok with raising the traitor coefficient by like one or just keeping it unchanged because the chaos is great imo

**Comment by Burger1998** [comment]
> The only people that dislike the revert are the ones that antag-roll go figure

sir aren't you banned?

**Comment by MegaEmpirical** [comment]
I'd rather see events increase rather than antags. Maybe increase as antags go down or something. Plus new events would be nice.

**Comment by namjay1170** [comment]
> I'd rather see events increase rather than antags. Maybe increase as antags go down or something. Plus new events would be nice.

I love greytide and meteors lets get more of that, lowpop didn't have nearly enough issues to deal with.

**Comment by Moja10** [comment]
Antag spawn rates have been so low and lower than what it was historically for a bug that ynot fixed that was persistent for years, and now people who have only ever known bugged antag spawn rates are saying there are too many antags. 

This is actually close to what the spawning rate was historically, if only a tad bit more. Arguably, Its spawning things like BB in too high numbers, but that can be tweaked and its honestly spawning things like traitors, heretics in fine rates. 

Absolutely no more 1 heretic for 50 pop, that's a 20x bigger issue than a little chaos and spicier rounds. Spicier rounds are only an issue if they get literally too spicy for crew/sec to handle, but that's not really been the case.

**Comment by UltraBigRat** [comment]
Better to have a round that is too chaotic then one where theres two antags that get caught immediatly or do absolutely nothing of note as the crew  dies of boredom.

**Comment by Hislyna** [comment]
It should scale with sec, not pop.

**Pull request merged**
