### PR TITLE
3D webclient: Makes the game 3D

### PR DESCRIPTION
**Pull request by monster860**
Todo:

- [x] Figure out why people keep getting disconnected
- [x] Fix drawing of tall objects
- [x] Add support for AI
- [x] Support images
- [ ] Support maptext
- [x] Fix DD blocking people's IP's due to lots of concurrent HTTP connections
- [x] Fix radials
- [x] Fix buildmode
- [x] Improve ghosting
- [x] Diagonal shuttle walls
- [ ] Fix shitty GPUs having lag when looking at objects with lots of overlays, such as players
- [ ] Right click menus
- [x] Fix `BUG: Maximum number of unique webclient images exceeded (65535)!`. Will likely require noping out the relevant code and handling .dmi parsing client-side
- [x] Fix network message spam from having turfs within vis_contents
- [x] Fix overlay lighting (god damn it ling)
- [x] Fix chat scrolling breaking half the time. The fact that chrome isn't respecting my breakpoints in the chat iframes is really cringe though.
- [ ] Add pop-out options for multi-monitor users

### Multi-Z?

There would be challenges in getting BYOND to send over the appropriate information both up and down without having performance issues relating to vis_contents recursion. In addition vis_contents has issues relating to turfs being in it on webclient. However I can see the most basic iteration being doable.

### Non-tile-based movement?

There are three major challenges to non-tile-based movement in SS13: BYOND's networking model, the mess that is layering in SS13, and all the reworking that would need to be done. The first two could be partially alleviated with this 3D thing - obviously, 3D eliminates a lot of the layering issues that have plagued SS13, and the custom client would allow taking some of movement code client-side. The main issue with the networking model that makes pixel movement hard is that how far a player moves is very timing-based - it's based on when a KeyDown event is sent to the server and when the KeyUp event is sent to the server. This means that if you lag out you could end up moving farther than intended. This is already an issue with tile-based movement, but would be exacerbated with pixel movement. There is one small minor issue unique to 3D though - while step_x/step_y are both floating point vars, they are converted into shorts when sent over the wire. A lot of reworking would need to be done to collision/movement code as well but it is likely doable.

### VR support?

It's absolutely possible, using [WebXR](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API). However, it would require a complete rewrite of the UI. All tgui / browser-based UI stuff would have to be migrated to something else, because without embedding HTML into SVG, which would have performance issues, as well as a lack of interactivity, as well as having CORS limitations, browsers cannot be rendered into a WebGL context.

# Document the changes in your pull request

This makes the game 3D. 

image

image

image

image

If you want to try this out download the branch, run build.bat as you normally would, and then run `.\tools\build\build.bat run-webclient-proxy` in the root directory to run the webclient proxy. After that, run Dream Daemon using port 6060 and then you can connect via the url http://localhost:18234/

# Spriting

There's a few 3d-specific sprites I put in, for the windoors, and firelocks. Yes the windoors look like coder art:
image

I also put together some construction sprites for firelocks.

# Wiki Documentation

Wiki will need updated instructions on hosting to account for needing the webclient proxy.

# Changelog

:cl: monster860
add: The game is now 3D.
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
SS3D but not in the way we ever expected

**Comment by Kapu1178** [comment]
god is dead

**Comment by CMOisLing** [comment]
Fetish content

**Comment by maxion12345** [comment]
cant wait

**Comment by carlopault** [comment]
Next step in SS13 gaming

**Comment by LemonInTheDark** [comment]
fucking deranged as expected. godspeed

**Comment by tralezab** [comment]
i love that you put in all this effort to still have three fuckawuckas downvote the pr like are we looking at the same pull request??

**Comment by Iamgoofball** [comment]
@tralezab they hated her because she told the truth

**Comment by redmoogle** [comment]
`what the fuck`

**Comment by Draggeru** [comment]
Make it VR headset accessible so I can justify vomiting thanks

**Comment by nikothedude** [comment]
god has left us

**Comment by Imaginos16** [comment]
unbelievably based

**Comment by JohnFulpWillard** [comment]
holy crap

**Comment by Zonespace27** [comment]
Monster what the fuck

**Comment by KeRSedChaplain** [comment]
what the fuck

**Comment by RimiNosha** [comment]
This is oddly terrifying, and I love it.

**Comment by CMDR-Gungnir** [comment]
Based as fuck.

**Comment by GoldenAlpharex** [comment]
I swear, Monster always comes up with the wildest ideas, and somehow pulls them off. Godspeed sister.

**Comment by GoldenAlpharex** [comment]
> I swear, Monster always comes up with the wildest ideas, and somehow pulls them off. Godspeed sister.

**Comment by moonheart08** [comment]
godspeed, this is possibly the best hack i've seen in a while

**Comment by silicons** [comment]
WHAT

**Comment by Laboredih123** [comment]
truly quite fascinating

**Comment by geneva-breaker** [comment]
this fucks hard

**Comment by unit0016** [comment]
Been fuckin' with this because of how cool it is, in my testing a few issues not mentioned in your to-do list have popped up and I figured I'd best write them down.

Client Issues:
- ! After enabling/disabling mouselock a few times, the hotkeys for switching hands, dropping items, and using the item in your selected hand no longer respond. This is fixed by a window refresh, and's consistent across Chromium and Firefox.
~~- Backpacks' UI is slightly broken, only shows the one box.~~
- Roundend credits is pretty broken as well, starting at the bottom of the screen and rolling down from there.
- Wall faces are culled next to airlocks.
- Clicks are always centered, as far as the game's concerned. Most prominently affects putting stuff on tables.
- Mesons, Thermals, X-Ray don't function as intended - and will probably need some reworking to make them somehow fit in first person.
- Plastitanium Windows appear to have some funky rendering issues, best visualized on the infiltrator after opening the blast doors.

Server Issues:
- !! Dream Daemon crashes upon restarting the world.

Icon Issues:
- Grilles are currently part of the floor, visually.
- Indestructible fake windows' underlay doesn't render correctly on the webclient.
- Indestructible fake windows' opacity isn't actually taken into account be the webclient, with all objects (minus turfs and the decals applied to them) behind them being culled.
- The abductor ship. Just kinda in general.
- Railings need adjusting for the new perspective, though I WILL admit having them hang from the ceiling fucks in it's own right


Absolutely legendary work though, this completely exemplifies the paranoia in spacemans.

**Comment by PowerfulBacon** [comment]
I am still in awe that you manage to pull this off and have the sprites work amazingly well

**Comment by OctusGit** [comment]
What the actual fuck

**Comment by Tsar-Salat** [comment]
only ~250 file changes? well done

**Comment by Laboredih123** [comment]
if only this could be ported to goon

**Comment by Simplehorror** [comment]
why is the changelog so small?

**Comment by patpol4** [comment]
monster being the goat as usual, i love you gal

**Comment by Yogbot-13** [comment]
#### Test Merge Deployed

##### Server Instance
test

##### Merged By
Alexkar598

##### Revision
Origin: 7239fda7857d4e83a4fccb81f10dd1bb4dbe4058
Pull Request: 583776be1db6439b2a3a5757608488228e4e6fb5
Server: 9b5820076eae29ade48f1d64c0bd3917d851aaeb

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20test)

**Comment by namjay1170** [comment]
Okay but what if ftl13 but 3d

**Comment by ToasterBiome** [comment]
image

Flips the menu here, do not like

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
test

##### Merged By
Alexkar598

##### Revision
Origin: c447d39ccaeb802820dbbe0eb247708625ef9ff5
Pull Request: 4cffcd8b3e5b96fbaac9acceea4a24f27117612f
Server: 3645c596fb87cdcc8c4297ba179e7dd5f3af6b55

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20test)

**Comment by 567Turtle** [comment]
Was pretty cool but every popup window for me was an nTOS error so I couldn't really do much. This included the chat panel, preferences menu, character setup menu and pretty much everything else.

**Comment by gamefreak2998** [comment]
Now add proximity based voice chat and make it even more cursed.

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
test

##### Merged By
monster860

##### Revision
Origin: 516130463a5358f20c13d054f796d30d1ba3a5c2
Pull Request: 7669fdf781051cce4b1dabfb73974c37ac932752
Server: b315438a2a31d50189429f10fea43c3277d75e4d

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20test)

**Comment by murder357** [comment]
is it possible to host this hell to friends via port forwarding? (forgot to put im using ngrok to port forward, my bad)

update 1: idk if this helps but when i do "ngrok http 18234", then go ahead and put that in while the server is running, it says CANT GET / or something similar to that

**Comment by monster860** [comment]
> is it possible to host this hell to friends via port forwarding? (forgot to put im using ngrok to port forward, my bad)
> 
> update 1: idk if this helps but when i do "ngrok http 18234", then go ahead and put that in while the server is running, it says CANT GET / or something similar to that

The default configuration only supports localhost for hosting. You'll need to copy `config.example.json`, rename it to `config.json`, and then change the webclient_origin and browse_origin to match the origin that users will actually type into their URL bars. The reason they are separate is for security reasons. You can set them to the same thing if you want to but yeah

**Comment by murder357** [comment]
> 
> 
> The default configuration only supports localhost for hosting. You'll need to copy `config.example.json`, rename it to `config.json`, and then change the webclient_origin and browse_origin to match the origin that users will actually type into their URL bars. The reason they are separate is for security reasons. You can set them to the same thing if you want to but yeah

thanks, i'll try it out and i'll tell you if something doesn't work (aka i'll tell you when i reach my smart limit)

**Comment by murder357** [comment]
> > The default configuration only supports localhost for hosting. You'll need to copy `config.example.json`, rename it to `config.json`, and then change the webclient_origin and browse_origin to match the origin that users will actually type into their URL bars. The reason they are separate is for security reasons. You can set them to the same thing if you want to but yeah
> 
> thanks, i'll try it out and i'll tell you if something doesn't work (aka i'll tell you when i reach my smart limit)

yea... so its multiplayer and everything but when i give my friend the ngrok link, it makes him connect with my key and not his own which disconnects me, does the same with guest accounts

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
test

##### Merged By
monster860

##### Revision
Origin: ff8bcc5650a3998adbd3846327a3939487ff8d20
Pull Request: 143151cbbdbd7af8c73d824ea2c87906be870435
Server: 95b5fd82c47961afced54a081898dea0a173fd36

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20test)

**Comment by Gurkenglas** [comment]
All AI VOX words are played at the same time. Also, the test server is showing everyone black screens (2D portions of the UI still work), allegedly until Alex updates something.

**Comment by Yogbot-13** [comment]
#### Test Merge Removed

**Comment by Laboredih123** [comment]
damn

**Comment by alexkar598** [comment]
Project is considered abandoned, relevant repos have been archived and server resources have been terminated.

**Comment by Iamgoofball** [comment]
awww

**Comment by Tsar-Salat** [comment]
Goodnight, sweet prince

😢

**Comment by Laboredih123** [comment]
:(

**Comment by LemonInTheDark** [comment]
sad days ahead

**Comment by Ch1tt0** [comment]
I'm sorry for pinging this old thread, but I figured out how you can run it locally.

1. Clone the repo with this command: `git clone -b webclient-3d --depth 1 https://github.com/monster860/Yogstation-TG.git`
2. Execute `Build.bat` in the root of the repo.
3. Host the game by right-clicking on `yogstation.dmb` and choosing `Host` , it should be right bellow `Open`
4. Check what port the game is being hosted on, also allow the web client to join by enabling it in the dream daemon window.
5. Open (starting point is root of repo) `/webclient/config.example.json` and modify the `byond_addr` variable to look like this `127.0.0.1:[YOURPORT]` (of course replace [YOURPORT] with the port you got from the dream daemon window)
6. Finally in root of repo open a terminal and execute this: `.\tools\build\build.bat run-webclient-proxy`
7. Go to [http://localhost:18234/](http://localhost:18234/) , if it says connecting, good job! Just wait a few seconds and you should be in game! It takes a while to load because BYOND.

Again, I'm sorry for pinging but I wanted to make it easier for others who wanted to try it.

**Pull request closed without merging**
