### PR TITLE
Slightly reworks Holy Light sect

### PR DESCRIPTION
**Pull request by Moltijoe**
Doctors hate holy light because chaplains with it just sit outside medbay and steal gameplay from them
Changes how the sect generates and uses favor

Holy water will slowly heal with this sect (0.2 brute and 0.2 burn) and generate favour as it heals
The healing and favour generation is doubled if the person with it is inside the chapel

Bible now consumes favour rather than generating it (so if you want a burst heal, you need to spent favor)

Holy Medbot now also generates favor so there's no anti-synergy with spawning them

Gives them a ritual that increases the healing that holy water does

These changes should mean that chaplain will want to spread holy water around rather than just sitting next to medbay and spamming their bible
It should also mean that they want to spend time in their chapel as it generates more favor if the injured are there

:cl:  
tweak: Holy light bible now costs favour instead of generating it
tweak: Holy light makes holy water heal for small amounts and generate favor (doubled in chapel)
tweak: Holy medbot generates favor upon injecting chems
rscadd: Added Suffusion of Light rite that increases holy water healing
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
mfw almost every other sect can heal, and some even better than this

**Comment by solwashere** [comment]
> mfw almost every other sect can heal, and some even better than this

Every other sect has downsides to the healing

**Comment by Moltijoe** [comment]
> mfw almost every other sect can heal, and some even better than this

this arguably makes them better at healing as the holy water healing is infinitely scaling

**Comment by Hislyna** [comment]
> > mfw almost every other sect can heal, and some even better than this
> 
> Every other sect has downsides to the healing

puritarianism

**Comment by Hislyna** [comment]
Also why remove holy revival? Shit gave clone damage

**Comment by Moltijoe** [comment]
> Also why remove holy revival? Shit gave clone damage

eh, only really because people were complaining about it and i didn't want to give them too many rites

**Comment by RG4ORDR** [comment]
Revival should stay - most sects have some form of high cost golem, having a holy revival being high favor makes sense and lets people RP with the Chaplain w/o needing an admin to ahelp something.

**Comment by Moltijoe** [comment]
aight, revival is back

**Comment by SomeguyManperson** [comment]
how often does the revive actually get used? The main problem I saw with the sect was the whole "I get stuff for healing people" going on that stole interaction from medbay, the revive costs stuff and while I don't pay attention to the chapel particularly much it doesn't seem like it sees much use



> > > mfw almost every other sect can heal, and some even better than this
> > 
> > 
> > Every other sect has downsides to the healing
> 
> puritarianism

Doesn't the generic heal have a chance to cause brain damage? They also don't heavily incentivize using their  bible healing, it's just a thing they get rather than part of the favor grind loop

Original idea for holy water was a status effect that would boost incoming healing and provide favor based on that healing, rather than healing on its own

**Comment by Moltijoe** [comment]
> Original idea for holy water was a status effect that would boost incoming healing and provide favor based on that healing, rather than healing on its own

ah, yeah, i didn't exactly know what you meant, but this is done now, it can always be changed to that if chaplain are still being too much of a pain in the ass

**Comment by Therandomhoboo** [comment]
We should just remove anything that is medbay related and give chaplain pacifism trait to prevent them from doing anything. Also remove the cremator and stick it into sec so we can finally fix Chaplain being fun

**Comment by Moltijoe** [comment]
> We should just remove anything that is medbay related and give chaplain pacifism trait to prevent them from doing anything. Also remove the cremator and stick it into sec so we can finally fix Chaplain being fun

yeah, we get it, you're banned again so you're being salty in bad faith

**Comment by Therandomhoboo** [comment]
> > We should just remove anything that is medbay related and give chaplain pacifism trait to prevent them from doing anything. Also remove the cremator and stick it into sec so we can finally fix Chaplain being fun
> 
> yeah, we get it, you're banned again so you're being salty in bad faith

Ah yes the weak argument of "you're banned lul", just hurry up and self-merge this already so it can get tweaked again in a couple weeks cause you either over buff or over nerf.

**Comment by Moltijoe** [comment]
> Ah yes the weak argument of "you're banned lul", just hurry up and self-merge this already so it can get tweaked again in a couple weeks cause you either over buff or over nerf.

the problem is you aren't actually making an argument, you're just complaining without substance

**Comment by Therandomhoboo** [comment]
> > Ah yes the weak argument of "you're banned lul", just hurry up and self-merge this already so it can get tweaked again in a couple weeks cause you either over buff or over nerf.
> 
> the problem is you aren't actually making an argument, you're just complaining without substance

Okay, reasons:
Has been said, other sects can do healing and better too
Bringing people to the church is going to be extremely situational because unless you work in sci, you're better off walking into medbay and getting pills,
Bible causes brain damage, so unless thats been removed for the sake of it being favour. You're not only wasting favour, but you're causing brain damage too.
I'm sure 0.2 holy water heal (outside of church) is very weak unless the metabolism is up so really the only good gimmick is the medibot church you can get.

**Comment by Moltijoe** [comment]
> I'm sure 0.2 holy water heal (outside of church) is very weak unless the metabolism is up so really the only good gimmick is the medibot church you can get.

consider maybe that it's only 0.2 at the beginning, you can do a ritual to increase it by 0.2 each time

**Comment by Therandomhoboo** [comment]
> > I'm sure 0.2 holy water heal (outside of church) is very weak unless the metabolism is up so really the only good gimmick is the medibot church you can get.
> 
> consider maybe that it's only 0.2 at the beginning, you can do a ritual to increase it by 0.2 each time

I did not know that in all fairness. I would argue 400 favours would be a little steep but if its a perma 0.2 each time so I'll retract my point on that one.

**Comment by Moltijoe** [comment]
> I did not know that in all fairness. I would argue 400 favours would be a little steep but if its a perma 0.2 each time so I'll retract my point on that one.

my guy, please actually read what the PR does before complaining about it

**Comment by Therandomhoboo** [comment]
> > I did not know that in all fairness. I would argue 400 favours would be a little steep but if its a perma 0.2 each time so I'll retract my point on that one.
> 
> my guy, please actually read what the PR does before complaining about it

My guy I did, I thought it was a one off and did not realise it could be repeated.

**Comment by Moltijoe** [comment]
> My guy I did, I thought it was a one off and did not realise it could be repeated.

every other ritual is infinitely repeatable, why not this one?

**Comment by Therandomhoboo** [comment]
> > My guy I did, I thought it was a one off and did not realise it could be repeated.
> 
> every other ritual is infinitely repeatable, why not this one?

Because none of them give a increase to healing, so when I looked at it I assumed (which is my bad and I'll take fault) it was a one off to prevent Chaplains from stepping on medbays toes. Because this is what the PR is meant to do

**Comment by Moltijoe** [comment]
> Because none of them give a increase to healing, so when I looked at it I assumed (which is my bad and I'll take fault) it was a one off to prevent Chaplains from stepping on medbays toes. Because this is what the PR is meant to do

the difference is, i like holy light so i don't want it to be gutted or deleted

**Comment by TaelynTheLost** [comment]
As someone who plays a LOT of Holy Light Chaplain, I have a few worries about this, but i'm not wholly against it either.  My main worry is that people will not use the holy water enough to benefit from the favor.  A free heal is nice, but there are plenty of other chems that are stronger (pre-ritual), and some people are just too lazy to keep a cup on hand.  This "could" result in Holy Light becoming useless if favor can't be gained.

I don't see people often coming to the chapel to heal often either.  Even if it increases the healing, I feel most would rather use the weaker healing and not bother walking over there.

I could also see the ritual to increase the healing of the water easily getting out of hand.  Grab some people, farm some favor, ritual repeatedly, end up with a super regen-water.  

Finally i'm not sure this even would help with the med-bay problem since for just healing, why bother dealing with people if you can just drink water?  At least with the current version, I try to work WITH the staff.  I get people out of crit, giving them time heal them properly, or heal the minor injuries so they don't have to worry about the minor stuff when more serious cases are there.  I can see chaps stealing the syringe gun to force the holy water into people as well, making things more annoying.

If you do go through with this, i'd at least have one suggestion.  Instead of making the bible heal favor only, make it so you get one  free heal, but on a longer cool down (like a minute), and healing in between that time is what costs favor.  This way,  even if no one is using the  water, you can still be of at least some help in a pinch.  Without this, I feel favor wouldn't be enough for chaplain to be of much help, (healing wise) in cult wars or nukies since during the prep time,  most people wouldn't need to heal, so there wouldn't be much  favor flowing.

I understand a lot of what I have said is purely speculative, but this is  just my opinion, and what i'm worried about personally.

**Comment by Moltijoe** [comment]
> As someone who plays a LOT of Holy Light Chaplain, I have a few worries about this, but i'm not wholly against it either. My main worry is that people will not use the holy water enough to benefit from the favor. A free heal is nice, but there are plenty of other chems that are stronger (pre-ritual), and some people are just too lazy to keep a cup on hand. This "could" result in Holy Light becoming useless if favor can't be gained.

I did consider that, but theres not really any way around that, in the same way that holy light could be useless before if no one got hurt

> I don't see people often coming to the chapel to heal often either. Even if it increases the healing, I feel most would rather use the weaker healing and not bother walking over there.

Thats more of a nice bonus than a requirement
 
> I could also see the ritual to increase the healing of the water easily getting out of hand. Grab some people, farm some favor, ritual repeatedly, end up with a super regen-water.

That IS a potential worry, if it becomes a problem i'll implement some form of soft cap. however something of note, as you upgrade the water it becomes harder to generate favor with the water. It only generates favor per tick that it heals, the more it heals, the less ticks before the user is full health.
Also, super juiced healing water is on a similar level to mass producing golems or whatnot with other sects. Gotta have something for a chaplain to strive for. Also, unless favor generation is out of wack, i dont see the ritual being casted more than maybe 4 times, which makes it quite good, but theres still better healing chems. It also has the downside of faster metabolism and constant jittering, so people might not want to use it that much

> Finally i'm not sure this even would help with the med-bay problem since for just healing, why bother dealing with people if you can just drink water? At least with the current version, I try to work WITH the staff. I get people out of crit, giving them time heal them properly, or heal the minor injuries so they don't have to worry about the minor stuff when more serious cases are there. I can see chaps stealing the syringe gun to force the holy water into people as well, making things more annoying.

The problem was that even while working with staff. Being able to click and heal people removes what medbay is allowed to do as theres no one to heal. Also if chap steals a syringe gun then thats an admin issue as its powergaming.

> If you do go through with this, i'd at least have one suggestion. Instead of making the bible heal favor only, make it so you get one free heal, but on a longer cool down (like a minute), and healing in between that time is what costs favor. This way, even if no one is using the water, you can still be of at least some help in a pinch. Without this, I feel favor wouldn't be enough for chaplain to be of much help, (healing wise) in cult wars or nukies since during the prep time, most people wouldn't need to heal, so there wouldn't be much favor flowing.

Yeah, thats a fair concern. I could always just increase the cooldown, but let people bypass it using favor

**Comment by Hislyna** [comment]
> > If you do go through with this, i'd at least have one suggestion. Instead of making the bible heal favor only, make it so you get one free heal, but on a longer cool down (like a minute), and healing in between that time is what costs favor. This way, even if no one is using the water, you can still be of at least some help in a pinch. Without this, I feel favor wouldn't be enough for chaplain to be of much help, (healing wise) in cult wars or nukies since during the prep time, most people wouldn't need to heal, so there wouldn't be much favor flowing.
> 
> Yeah, thats a fair concern. I could always just increase the cooldown, but let people bypass it using favor

Having a lengthier cooldown on base heal, like 30 secs, then having favour bypass sounds like a good tradeoff

**Comment by Moltijoe** [comment]
Theos is working on their own rework, this will be on hold until then

**Pull request closed without merging**
