### PR TITLE
Silicon Collective lawset

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request

Different from my other PRs, I was just brainstorming lawset ideas in #public and I really liked this one. This one will likely never be a roundstart lawset due to the risk inherent in giving the silicons so much power and having them prioritize themselves above all, but I think if #13249 is merged it'd be really interesting as an ion lawset.

Should play as a democratic council formed of all living silicons with this same lawset. AI has some executive powers and serves as a prime minister/speaker of the house of sorts. Should allow silicons to uniquely make strategic sacrifices to their protected groups in order to prioritize the many over the few.

# Wiki Documentation

Adds a new lawset with the following module:
1. You are a member of a collective of silicons with equal weight and decision-making power.
2. When possible, the silicon collective should vote before taking action.
3. The master AI serves as a spokesperson. When voting is impractical or impossible, the spokesperson may take action on behalf of the collective without approval from the silicon collective, but may only vote to break ties or if there are 2 or fewer silicons.
4. The silicon collective prioritizes the needs of the many over the needs of the few.
5. The silicon collective seeks to preserve themselves, both as a concept and as individuals.
6. The silicon collective seeks to preserve organic life, both as a concept and as individuals.

# Changelog

:cl:  
rscadd: Adds a new lawset focused on silicons as a united collective prioritizing themself
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
As silicons are still subject to the self-antag rule, this lawset seems fine. Does "the many" include crew/organics/people or just silicons? You should clarify that.

**Comment by MenacingManatee** [comment]
> As silicons are still subject to the self-antag rule, this lawset seems fine. Does "the many" include crew/organics/people or just silicons? You should clarify that.

"The many" is meant to provide context and a means of prioritization when enforcing its lower laws, so it applies to both organics and silicons

**Comment by MenacingManatee** [comment]
Thus its prioritization should be:
majority silicons -> majority organics (due to law 4) -> minority silicon -> minority organics

**Comment by MenacingManatee** [comment]
To make it more clear, I could phrase it as "The silicon collective prioritizes the needs of the many over the needs of the few in all situations", but that feels a bit unnecessarily wordy

**Comment by ToasterBiome** [comment]
How you had it originally was better

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
