### PR TITLE
REEEEEEEEEEEEEEEEELOADINGGGGGGGGGGGGGGGG

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Allows you to set something to say on a gun when fully reloading a gun (swapping in a magazine that has bullets to a gun that doesn't or applying bullets to a gun that is empty)

:cl:  
rscadd: you can now say REEEEEEEEEEEEEELOADINGGGGGG when reloading a gun
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Make it say "RELOADING, COVER ME!" if they're nukies, ert, deathsquad, or sec pls

**Comment by Ratvar** [comment]
PR description is incorrect, I just checked if I can say REEEEEEEEEEEEEELOADINGGGGGG when reloading a gun and I already can

**Comment by SomeguyManperson** [comment]
yes but you won't because it is slow

**Comment by JamieD1** [comment]
Kinda feels a bit meh, maybe make the gun say magazine empty or something, kinda feels like CM RELOADING

**Comment by JamieD1** [comment]
If people complain im reverting this

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
