### PR TITLE
Refactors rad collectors and adds a new mode

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Marginally less shitty code

(For standard setup)
Adjust Research Mode to product about 125 points per collector per minute
Adds Money Mode which produces about 120 points per collector per minute

# Wiki Documentation

Rad collectors can make money now

# Changelog

:cl:  
rscadd: Rad collectors can make money now
tweak: Rad collectors make a descent amount of science now
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
also working on making the research viable

**Comment by warface1234455** [comment]
Money payout based on how much power it stored?

**Comment by redmoogle** [comment]
> Money payout based on how much power it stored?

yes

**Comment by JamieD1** [comment]
@TheGamerdk MONEY

**Review by JamieD1 — APPROVED** [review]
We will see how much money it actually makes

**Pull request merged**
