### PR TITLE
Besides, this isn't even my sword

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Adds a new item, the musarama, and its sheath. This will likely be a traitor and/or nukeop item for around 15 TC

Weapon stats:
35 damage
60 AP
40 blockchance

Special bullshit:
Using the sheath in-hand will lock it to your DNA (mind) allowing you specifically to use two special abilities by sheathing the sword and using alt+click.
Alt+click yourself to prepare a short ranged, wide slash. After 2 seconds, anyone directly in front of you will be hit and the sword will be placed in your active hand
Alt+click a far tile to prepare for 2 seconds, then dash to your target, cutting anyone along your path for half the sword's normal damage. Coming into contact with a mob will end your dash and slash them for 50% more damage

While preparing either ability, and for the duration, you will be unpullable and unpushable, and the sheath gains 200 blockchance, allowing you to effectively block any incoming damage as you are forced to remain completely still.

Currently no cooldowns have been implemented however they are planned

# Wiki Documentation

new item this will be flesehed out later

# Changelog

:cl:  
rscadd: memories broken the truth goes unspoken ive even forgotten how to code
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
It sounds kinda OP, but i like this item

**Review by ghost — APPROVED** [review]

**Comment by Absolucy** [comment]
a metal gear rising reference is always good

**Comment by SomeguyManperson** [comment]
I can't ever see this being good or properly balanced as a tool anywhere

**Comment by ghost** [comment]
Noooooooooo

**Pull request closed without merging**
