### PR TITLE
veil mind costs 6 lucidity up from 1 to unlock

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Github documenting your Pull Request

Stop taking it first you unoriginal fucks you might learn something

# Wiki Documentation

veil mind lucidity cost is now 6

# Changelog

:cl:  
tweak: veil mind now costs 6 lucidity points to unlock up from 1
/:cl:

### CODE REVIEW

**Review by adamsong — APPROVED** [review]
I don't play enough darkspawn to know if this is a good change, but the code checks out

**Comment by Marmio64** [comment]
This and the one that turns them into a shadow are like their only good abilities though

**Comment by Cartlord** [comment]
then maybe darkspawn just suck, marmio

**Comment by SomeguyManperson** [comment]
I'd rather nerf this and buff the other stuff since as is it's only useful because it lets people play as shadowlings and steamroll vs other abilities which don't let you do that

**Pull request merged**
