### PR TITLE
Revert "Stupid proofs erts"

### PR DESCRIPTION
**Pull request by boodaliboo**
people want this reverted this is the pr that made most centcom ids undroppable

### CODE REVIEW

**Comment by ynot01** [comment]
The reason this was merged is because people were using stolen CC IDs like ERT ones to return to CC, get into the test chamber, then come back to the station or grief the shuttle with their newfound items.

**Comment by boodaliboo** [comment]
> The reason this was merged is because people were using stolen CC IDs like ERT ones to return to CC, get into the test chamber, then come back to the station or grief the shuttle with their newfound items.

its imposible to go the test chamber now as a ert or normal crew

**Comment by ynot01** [comment]
> > The reason this was merged is because people were using stolen CC IDs like ERT ones to return to CC, get into the test chamber, then come back to the station or grief the shuttle with their newfound items.
> 
> its imposible to go the test chamber now as a ert or normal crew

someone can just go through the damn shutters by gunning them down until they reach the shuttle dock where the portals are

**Comment by boodaliboo** [comment]
> > > The reason this was merged is because people were using stolen CC IDs like ERT ones to return to CC, get into the test chamber, then come back to the station or grief the shuttle with their newfound items.
> > 
> > 
> > its imposible to go the test chamber now as a ert or normal crew
> 
> someone can just go through the damn shutters by gunning them down until they reach the shuttle dock where the portals are

where would they get the guns ert spawn with these guns and i have never seen them able to break through

**Comment by ToGWtF** [comment]
Still a bad idea. Especially now with Blue ERT not even having weapons. That's just a free all access at that point.

**Comment by Hopekz** [comment]
You can probably remove people's main argument on CC if you just make the loot room unavailable by turning the breakable windows in to walls (or make them walls with sprite or some other HP solution to them)

**Comment by Hopekz** [comment]
> You can probably remove people's main argument on CC if you just make the loot room unavailable by turning the breakable windows in to walls (or make them walls with sprite or some other HP solution to them)

But he's the main reason as ToG has stated is the "free" all access.

**Comment by LoliconSlayer** [comment]
The grilles between loot room and thunderdome are unbreakable IIRC, but RCD and Portal gun still exists.

**Comment by alexkar598** [comment]
This is stupid

**Pull request merged**
