### PR TITLE
Makes it harder for the HoS to break into Box RnD, without adding 2 ugly airlocks (by adding indestructible walls)

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

# Wiki Documentation

# Changelog

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Pictures please

**Comment by Bibby0110** [comment]
> Pictures please

nope

**Comment by JamieD1** [comment]
> 

image

**Comment by ToasterBiome** [comment]
> image

Looks good

**Comment by Spacemanspark** [comment]
you madman

**Comment by Marmio64** [comment]
how will mastr ever recover from this...

**Pull request merged**
