### PR TITLE
[Gax] [Meta] [Box] [Asteroid] Places One IPC Revival Board in Robotics

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

IPCs literally are cucked out of being revived until R&D researches a tech. One that they will actively avoid unless an R&D player is an IPC, or a medical doctor harasses them to get an IPC revived. This mitigates this by just placing a single board in robotics in all in-rotation maps.

# Changelog

:cl:  
tweak: GAX Robotics now has a single IPC Revival Board in the Robotech Vendor
tweak: META Robotics now has a single IPC Revival Board
tweak: BOX Robotics now has a single IPC Revival Board
tweak: ASTEROID Robotics now has a single IPC Revival Board
/:cl:

### CODE REVIEW

**Comment by GraveHat** [comment]
This would help newer players know the difference between the Cyborg Rebooter and the IPC Revival Board as they would see the correct type of board on the table before they come to the conclusion that the only reboot module they can access which being is the cyborg rebooter is capable of reviving IPCs. As, of this moment, IPC revival is locked behind research that most people would most likely overlook if they don't know about it beforehand, I could see this alleviating that problem.

**Comment by ToasterBiome** [comment]
add it to the vending machine for gax!!!

**Comment by VaelophisNyx** [comment]
but biome how will people know it's there!
Noone opens the damned vendor :C

**Comment by VaelophisNyx** [comment]
done tho

**Comment by GraveHat** [comment]
> but biome how will people know it's there! Noone opens the damned vendor :C

Can confirm, first thought that there were no flashes on gax but it turns out they were all free from the vendor which also subsequently pay locks them for the tiders.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
add it in the actual vending machine not mapedited!!

**Pull request closed without merging**
