### PR TITLE
ports medical kiosk from TG

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

main relevant PRs
https://github.com/tgstation/tgstation/pull/46676
https://github.com/tgstation/tgstation/pull/46884
https://github.com/tgstation/tgstation/pull/47578
https://github.com/tgstation/tgstation/pull/47591

image

mapping commit

kiosk in foyer

# Wiki Documentation

https://tgstation13.org/wiki/Machines#Medical_Kiosk

# Changelog

:cl: ArcaneMusic, MrDoomBringer, ynot01
rscadd: Added Medical Kiosk
/:cl:

### CODE REVIEW

**Comment by Anvilman6** [comment]
Interesting concept, though it feels like this will get near zero usage, as Health Analyzers do this for free and are relatively plentiful.

**Comment by ynot01** [comment]
> Interesting concept, though it feels like this will get near zero usage, as Health Analyzers do this for free and are relatively plentiful.

ok medical main that always has access to infinite health analyzers

**Comment by Chubbygummibear** [comment]
what about for placement having it be between the waiting chairs in the front lobby? I feel like if you make people walk right up to the door they're going to bwoopbwoopbwoopbwoopbwoopbwoop the door rather than do the checkup machine. if it's a bit closer to the entrance it incentivizes that before going to the door to press it 100 times

**Comment by ynot01** [comment]
> what about for placement having it be between the waiting chairs in the front lobby? I feel like if you make people walk right up to the door they're going to bwoopbwoopbwoopbwoopbwoopbwoop the door rather than do the checkup machine. if it's a bit closer to the entrance it incentivizes that before going to the door to press it 100 times

in front of the table? im not sure what you mean

**Comment by Chubbygummibear** [comment]
> > what about for placement having it be between the waiting chairs in the front lobby? I feel like if you make people walk right up to the door they're going to bwoopbwoopbwoopbwoopbwoopbwoop the door rather than do the checkup machine. if it's a bit closer to the entrance it incentivizes that before going to the door to press it 100 times
> 
> in front of the table? im not sure what you mean

like removing the middle chair from the line of 3 here 
image

**Review by nesisknesis — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
