### PR TITLE
adds a singular ecutlass to lavaland pirate ruin

### PR DESCRIPTION
**Pull request by boodaliboo**
you have to fight a mob with a infinite use energy gun and two mobs that rush at you. reward them

#### Changelog

:cl:  
rscadd: Added ecutlass
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
unless it was changed, you already get e-cutlasses from killing the mobs, and laserguns from killing the ranged ones. Even if you don't its incredibly, and i mean INCREDIBLY easy to kill them they don't need to be rewarded a 30 damage melee weapon with a 50% projectile block chance.

**Comment by Mesalikepie** [comment]
It was changed marmio. It currently drops uhhh 2 10 damage normal cutlasses and no egun. I like the pr on the reasoning it gives traitors band blood bros more shit to work with occasionally. I also understand if this is no

**Comment by boodaliboo** [comment]
> unless it was changed, you already get e-cutlasses from killing the mobs, and laserguns from killing the ranged ones. Even if you don't its incredibly, and i mean INCREDIBLY easy to kill them they don't need to be rewarded a 30 damage melee weapon with a 50% projectile block chance.

it was changed

**Comment by ghost** [comment]
>Give miners an energy sword

Give them a different reward. Esword is too strong.

**Comment by boodaliboo** [comment]
> > Give miners an energy sword
> 
> Give them a different reward. Esword is too strong.

any ideas?

**Pull request closed without merging**
