### PR TITLE
get rid of the roundstart ATs

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

removes the hey listen message for now

# Changelog
:cl:  
bugfix: no more hey listen
/:cl:

### CODE REVIEW

**Review by patpol4 — COMMENTED** [review]
what

**Comment by Simplehorror** [comment]
> what

?

**Comment by Simplehorror** [comment]
@wejengin2

**Review by N3D6 — COMMENTED** [review]
all this modifies is maps bro

**Comment by Simplehorror** [comment]
> all this modifies is maps bro

yeah

**Comment by JamieD1** [comment]
Can you do it again please, conflicts.

**Comment by Simplehorror** [comment]
> Can you do it again please, conflicts.

:trollface:

**Comment by JamieD1** [comment]
Need to do again as map was updated.

**Pull request closed without merging**
