### PR TITLE
Add laptop/pc vendors around cargo and clerks shop

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

_Quite literally the commit name_

Add laptop/pc vendors around cargo desk
Add pc vendors around clerks shop

### Why is this good for the game?

Encourage use of modular computers ~~if you're not poor~~

#### Changelog

:cl:  
rscadd: Add PC/Laptop vendors by cargo and science on Yogstation and YogsMeta
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
Specify in the changelog on what maps the vendors have been added.

**Comment by patpol4** [comment]
Aren't they broken though, i thought new tgui made them nonfunctional

**Comment by redmoogle** [comment]
> 
> 
> Specify in the changelog on what maps the vendors have been added.

oops



> 
> 
> Aren't they broken though, i thought new tgui made them nonfunctional

Possibly

**Comment by redmoogle** [comment]
Nah it's all G it works fine

**Review by patpol4 — CHANGES_REQUESTED** [review]
Robotics lab made this conflict, pushing a commit should also generate diffs

**Comment by redmoogle** [comment]
> Robotics lab made this conflict, pushing a commit should also generate diffs

Merge that first then

I didnt mean to dick him over

**Comment by patpol4** [comment]
> Merge that first then

I did, that is where the conflict came from

**Pull request closed without merging**
