### PR TITLE
Taking too much diphenhydramine makes you hallucinate

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Taking too much (30u) of diphenhydramine (the active ingredient in benadryl) will now cause you to get high and hallucinate

# Wiki Documentation

Mention this on the guide to chemistry

# Changelog

:cl:  
tweak: diphenhydramine makes you hallucinate if you take too much
/:cl:

### CODE REVIEW

**Comment by stwordcitizen** [comment]
Good pr

**Comment by Moltijoe** [comment]
huh? care to explain why it's good for the game?

**Comment by iamthesilly** [comment]
> huh? care to explain why it's good for the game?

Thought it would be funny to make it possible to get high and hallucinate from too much diphenhydramine (aka benadryl)

Effects are harmless so it doesn't affect balance at all, just a funny feature I felt like adding

**Review by Moltijoe — APPROVED** [review]

**Comment by TheRyeGuyWhoWillNowDie** [comment]
ah hell nah spunch bop took 40 benadryls

**Comment by Cartlord** [comment]
are these actually the harmless hallucinations or can it give you the bubblegum hallucination that causes stamcrit

**Review by ReddicusDragon — CHANGES_REQUESTED** [review]
Awaiting balance council

**Comment by ThatLing** [comment]
that was quick
image

**Review by ReddicusDragon — APPROVED** [review]

**Pull request merged**
