### PR TITLE
Adds torture racks to vastly increase RP between prisoners and security

### PR DESCRIPTION
**Pull request by ChesterTheCheesy**
# INCREASES RP

https://user-images.githubusercontent.com/71487903/111911152-9e2c5400-8a64-11eb-963f-499a7262d05c.mp4

# Changelog
:cl:  
rscadd: Adds a torture rack craftable with 20 wood
imageadd: Adds a sprite of a torture rack
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
see #10695

**Comment by ChesterTheCheesy** [comment]
It's not an execution method, it's for torturing/curing dwarfism/making people more attractive to women by increasing their height,

**Comment by ChesterTheCheesy** [comment]
So anyway, will you be willing to put in a valid reason for closing the PR?

**Comment by patpol4** [comment]
lol

**Pull request closed without merging**
