### PR TITLE
Corporations II: Adds corporate discounts to the traitor uplink

### PR DESCRIPTION
**Pull request by Amelia0010**
Traitors now get up to a 20% discount (multiply the price by 0.8 and round up if necessary) if the company they're working for produces the thing they wanna buy.
image
:cl:
tweak: Traitors now get an employee discount on certain uplink items
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Oh neat, Synicate companies actually exist in game now!

**Comment by Tipy1802** [comment]
But I don't think you should be able to buy 20 TC for 16 TC...

**Comment by Marmio64** [comment]
stonks

**Comment by boodaliboo** [comment]
> But I don't think you should be able to buy 20 TC for 16 TC...

no keep it

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
