### PR TITLE
makes floor tiles awful and bad and ruins the game forever

### PR DESCRIPTION
**Pull request by Potototatoh**
### Intent of your Pull Request

fixes the more common floor tilesw on the station from having more than 60 identical shades for shits and giggles
edit: thw white tiles are no olonger noticeably pink but theyre still actually pink because im a bad person
Screenshot (927)

Screenshot (924)
(only updates floor tiles))
#### Changelog

:cl:  
wip: maybe more actual turfs for the station in the future if we obtain the ability tto cooperate
imageadd: turfs updated 
imagedel: turfs updated 
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
Post a proper picture

**Comment by Potototatoh** [comment]
Screenshot (929)

**Comment by Moja10** [comment]
too noisy, tone down the noise IMO

**Comment by Moja10** [comment]
(((otherwise looks great!!!!!!)

**Comment by Hopekz** [comment]
Why do all the white tiles have a shade of pink
Makes no sense
Unless these are breast cancer awareness tiles

**Comment by monster860** [comment]
oops sorrym anyways it looks like jpeg.

**Comment by monster860** [comment]
I think Ill give it a testmerge later and let the players decide later if they like it

**Comment by Potototatoh** [comment]
Screenshot (932)
op is lying

**Comment by Ktlwjec1** [comment]
Yeah I agree with monster's "it looks like jpeg", but I'm fine with a testmerge of these.

**Comment by Hopekz** [comment]
Not sure if my monitor is fucky but I see a lot of pink
image
image
image

**Comment by Potototatoh** [comment]
good thing tht you cant notice themn ingame right haha

**Comment by boodaliboo** [comment]
after seeing them ingame i don't like this

**Comment by Darkstick** [comment]
IMO they look too sharp and detailed, it contrasts poorly with the rest of the "art style". Plus whenever I see them all I can think about is needing to mop the floor because it looks dangerously similar to the filthy tiles you find in perma, it's violently scraping at my brain. Any dirt on floor tiles should be cleanable, not part of the floor tile.

**Comment by nesisknesis** [comment]
The grey ones look too grimy, so much so that they would make people think they would and can clean them, when they cannot. The highlights on them also make them look wet, the old tiles looked very dry in contrast. 

You CAN notice the pink on the white tiles and it looks horrific.

Dark tile shading is scuffed, there no reason to it and looks like you just picked a corner and waved your cursor about. Though surprisingly it looks better than the other ones because it doesn't look grimy nor wet. However, id still prefer the old ones.

Un-testmerge this immediately and put more thought into the design of the tiles and how players would react to them because this is probably the most controversial thing you can change in this entire game since floor tiles take up 50% of a player's screen.

**Comment by Hopekz** [comment]
Yeah, what ID said in terms of these tiles looking both wet and dirty at the same time + the pink not being magically invisible in-game.
image

RE: the pink maybe you have a filter on for your screen? (Bluelight etc)

**Comment by monster860** [comment]
the sprites suck, make better ones and open a new PR

**Comment by Hopekz** [comment]
For reference here is how it looks when for example a hallway tile is wet:
(The tile in the middle of the screenshot is wet)

dreamseeker_keiufqwEQD

**Pull request closed without merging**
