### PR TITLE
Updates All 5 Whiteships To Be Vaguely Consistent AND Modernizes Their Shapes and Layouts

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Overhauls basically every whiteship, making them consistent across all five of being somewhat dangerous but having somewhat interesting loot (ranging from actual items, to usable machines, etc). ALL of them have had Large engines put in, in place of some 2x2 small engine setups. And none have engines inside walls anymore. All of them have had their lights correctly populated instead of using a lot of 100% empty sockets

Whiteship 1 (Medical): Overhauled EXTREMELY heavily, now less long but features a complete chemistry setup and a stasis bed. Atmos system updated to be fully functional! More zombies too. CMO suit lockers are now paramedic space suits instead. The "loot" here is more that you get a 100% mobile functional medbay.

Whiteship 2 (Mining?): Some structural changes to make it less...weird. Added Xeno mobs and some decals, and a functional but unequipped Clarke mech. +1 set of Caravan tools, which are the fastest possible tool set. Added a Kinetic Spear Gun and a handful of spears with a quiver to the bridge, with a mining hardsuit locker. Also added two explorer suit lockers and a manual mining scanner + jaunter to cement this as a mining ship. Gonna be real I...cant think of a lot to do with this ship.

Whiteship 3 (Centcomm): Atmos system totally overhauled, added one atmos hardsuit storage to the engineering room. Not much else changed in this one that I recall?

Whiteship 4 (Cargo): Completely redesigned kitchen and hydro, which uses old-hydro trays. Nuked the million quarter-tile decals and used full or opposing-corner decals where appropriate. Replaced the table of booze with a booze-o-mat and a snack vendor. Added 1 syndie mob

Whiteship 5 (Lootbox???): Improved shape of the ship and also filled it with hostile eyeball mobs; replaced medibeam with a rapid syringe gun and the CE hardsuit with an atmos hardsuit, and the oxygen tank has been upgraded to a Tactical variant for your troubles. Not much else changed, not a lot of room to do much to this ship...

# Changelog

:cl:  
tweak: All 5 Whiteships Updated To Be Less Variable On Loot Vs Danger
/:cl:

### CODE REVIEW

**Comment by Jumps0** [comment]
could you add pictures?

**Comment by VaelophisNyx** [comment]
Mapdiff bot exists.

**Review by ToasterBiome — APPROVED** [review]
Maps b fine, balance time

**Comment by JamieD1** [comment]
Will leave more time for the balance peeps

**Comment by ToasterBiome** [comment]
Balance Council says "whatever"

**Comment by Addust** [comment]
you fool large engines don't like rotating

**Pull request merged**
