### PR TITLE
[s] [admin] kills naughty players

### PR DESCRIPTION
**Pull request by ToasterBiome**
image

:cl:  
tweak: admins are alerted when you try to check if you're a late awaken antagonist
/:cl:

### CODE REVIEW

**Review by ynot01 — CHANGES_REQUESTED** [review]
instead of this useless message, just hide the fact that they're traitor and only tell admins that they're traitor (when traitor and unawakened)

**Review by TheRyeGuyWhoWillNowDie — CHANGES_REQUESTED** [review]
remove the fucking stupid traitor delay

**Comment by DylonBR** [comment]
What advantage does checking if youre tot possibly give you? A 3 minute headstart? Lol

**Comment by ynot01** [comment]
> What advantage does checking if youre tot possibly give you? A 3 minute headstart? Lol

Antag rolling
1. check if antag
2. if antag, play; if not, cryo
3. repeat

**Comment by DylonBR** [comment]
If you're constantly trying to antag roll, wouldn't it be really obvious to the admins? "This guy cryos every single time he isn't antag"

**Comment by ToasterBiome** [comment]
> If you're constantly trying to antag roll, wouldn't it be really obvious to the admins? "This guy cryos every single time he isn't antag"

this makes it more obvious

**Comment by DylonBR** [comment]
I guess so. But why is traitor the only antag that gets this delay timer? Why even have a delay at all?

**Comment by ChuChu42** [comment]
suicide verb can also be used to check it.

**Comment by Hopekz** [comment]
Message is too generic imo. Should have more detail like "what did they do exactly?" or else it'll probably just be ignored. Make someone that isn't "in the know" understand why they potentially fucked up.

**Comment by ynot01** [comment]
> If you're constantly trying to antag roll, wouldn't it be really obvious to the admins? "This guy cryos every single time he isn't antag"

admins are not omnipotent and it is difficult to act on something as arbitrary as "antag rolling" and reliably enforce it on someone who might just have decided they wanted to stop playing

it's likely that some players already do this and admins are just unaware or not confident enough to act

invariably, the best way forth is code changes

**Comment by ToasterBiome** [comment]
literally admin issue lol

**Pull request closed without merging**
