### PR TITLE
[Hugbox] Comms Consoles AutoLogout After 3 Minutes

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Comms consoles automatically log out 3 minutes after logging in. This does not care if you're using the console, but who's going to be using the console for that long??
and just like....
log back in.

# Changelog

:cl:  
tweak: Comms Consoles automatically log out after 3 minutes pass.
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Why does the console need to logout by itself?

**Comment by VaelophisNyx** [comment]
why does your bank website need to log out by itself irl

it's important

**Comment by 00ze-cyclone** [comment]
The station got plasma that is separated from distro by just one pump, cheap insuls that can shock you more, an engine that obliterate the station if left unattended, a room full of gun separated from space by a single wall, an AI with absurd laws, a fucking nuke just sitting there and bags that destroy reality if handled improperly.
Problem is the retard captain, not the code.

**Comment by VaelophisNyx** [comment]
please explain to me what this would break if I add it

because all I'm hearing is "because its always been that way"

**Comment by Moggram** [comment]
Sec consoles don't auto log out to. Will you add a timer to them also?

**Comment by VaelophisNyx** [comment]
I mean if that became an issue I could
but it's not as prevalent as captains not logging out
or as is usually the case
some other head, not logging out

**Comment by Maia-J** [comment]
> why does your bank website need to log out by itself irl

It checks for inactivity however

**Comment by VaelophisNyx** [comment]
yes but this unfortunately is a game running on miles of shitcode that doesn't have a way to make a timer refresh instead of letting it tick down

**Comment by Bibby0110** [comment]
Too hugboxy, sorry

**Pull request closed without merging**
