### PR TITLE
Buffs the ebow to be faster

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Ebow chemicals reduced from 8 units to 6 units, reducing their lifespan from ~13 to ~8 chem ticks (~16 seconds)
Ebow cooldown reduced from 20 seconds to 10 seconds
Ebow polonium removed from reality for being annoying and giving the weapon an identity crisis

# Wiki Documentation

I am going to get wiki vetoed for this

# Changelog

:cl:  
tweak: Ebow chemicals reduced from 8 units to 6 units, reducing their lifespan from ~13 to ~8 chem ticks (~16 seconds)
tweak: Ebow cooldown reduced from 20 seconds to 10 seconds
tweak: Ebow polonium removed from reality for being annoying and giving the weapon an identity crisis
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Hugbox + i ded + fetish content + donor benefit + controversial + ON HOLD - HD + awaiting action - maintainer

**Comment by SomeguyManperson** [comment]
awaiting action - balance

**Comment by LazennG** [comment]
least shitty ebow pr i've seen in like 2 weeks

**Review by Moltijoe — APPROVED** [review]
pretty simple changes

**Pull request merged**
