### PR TITLE
Add Old PDAs station trait

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

New station trait that gives everyone the old PDAs instead of the new ones. We have the old PDA code still so we may as well use it, plus more station traits are always good. I also like the old PDA sprites.
# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: New station trait that gives everyone old pdas
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
...

**Comment by iamthesilly** [comment]
guh

**Comment by Simplehorror** [comment]
why close

**Comment by knightshade0** [comment]
I believe we're actively attempting to move away from the extremely questionable legacy code.

**Comment by Simplehorror** [comment]
still cant talk to the AI over pda btw

**Comment by iamthesilly** [comment]
fastest close in the west

**Comment by Simplehorror** [comment]
> I believe we're actively attempting to move away from the extremely questionable legacy code.

dude the new PDAs fucking suck my balls

**Comment by Simplehorror** [comment]
they're half-baked as fuck and they are so unresponsive

**Comment by SapphicOverload** [comment]
fastest close in the west

**Comment by Simplehorror** [comment]
"extremely questionable" i'll show you something extremely questionable in my pants

**Comment by Simplehorror** [comment]
"ITS OLD SO IT MUST BE BAD"

**Comment by SomeguyManperson** [comment]
fastest close in the west

**Comment by ToasterBiome** [comment]
We should instead remove the old PDA code

**Comment by iamthesilly** [comment]
> they're half-baked as fuck and they are so unresponsive

make them better then

**Comment by Chubbygummibear** [comment]
if you can identify all the issues with the new pdas then it's within your power to fix those issues to bring them up to your expectations

**Comment by Simplehorror** [comment]
> if you can identify all the issues with the new pdas then it's within your power to fix those issues to bring them up to your expectations

ok.
step 1. removing tgui

**Pull request closed without merging**
