### PR TITLE
Full preternis resprite

### PR DESCRIPTION
**Pull request by Moltijoe**
fulfills this bounty
https://forums.yogstation.net/threads/35-adds-new-preternis-sprites-to-replace-old-ones-ss13-server.25660/
(code was free, all money is going to the artist)

Huge thanks to @grimm-hollowknight for the sprites

# Why is this good for the game?
They've been using reused augmentation sprites since they were first created
this gives them a new appearance that gives them a proper visual identity

# Testing
https://github.com/yogstation13/Yogstation/assets/108117184/993e6684-be80-4712-94ac-750fa2ef29d0

# Spriting
refer to testing

:cl: Identification, Molti, lore team (rip skrem)
imageadd: new preternis sprites
imagedel: old preternis sprites
/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
hell yeah

**Comment by iamthesilly** [comment]
hell yeah

**Comment by DeadlyBag** [comment]
hell yeah

**Comment by MajManatee** [comment]
Very cool. Personally, I'm concerned about the one that looks almost exactly like a clockie golem.

**Comment by Moltijoe** [comment]
> Very cool. Personally, I'm concerned about the one that looks almost exactly like a clockie golem.

if you're referring to the bronze colour, that's a reasonable concern but i don't think it's going to be an issue

**Comment by MajManatee** [comment]
Let the copper oxidize then when he turns greenish I'm sure it will be fine, but right now they are practically identical.

**Comment by Moltijoe** [comment]
> Let the copper oxidize then when he turns greenish I'm sure it will be fine, but right now they are practically identical.

i'm saying, even if they did look identical, which they don't, that shouldn't be an issue
there's many instances of things that are non-antag that look incredibly similar to antag items, and they're actually useful as a balance point
clockies usually carry a number of distinguishing items if they've gone war, so even if the head looks somewhat similar, you should still be able to tell whether the person is a threat or not at a glance since
The preternis will only look somewhat close to a clock golem if they both pick no antenna and a specific eye type and colour it red, at that point it's similar to a lizard colouring themselves like a draconid
Assuming none of this mattered, and they looked 1:1 identical with clock golems, even then, that'd just be a slight buff to war clockies while on the station as they'd get a fraction of a second where someone needs to react to them rather than immediately knowing they're an enemy

**Comment by MajManatee** [comment]
I just work here man

**Comment by Moltijoe** [comment]
> I just work here man

They used to have green as an option, but it looked terrible when adding the weathering so i removed it

**Review by cuackles — APPROVED** [review]
🐴

**Review by MajManatee — APPROVED** [review]
It looks fine, but i feel like their might be spriting issues with clothes

**Comment by wonderinghost** [comment]
you ever open up a manuel for a game. this is something like that

**Comment by ofscarletdreams** [comment]
oh my god I CAN BE A CLOCKWROK GOLEM

**Pull request merged**
