### PR TITLE
RTS moment

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

This PR makes that aliens and blobs get a message when their teammate dies(blob gets a message when a blobbernaut dies, and aliens get a message if a humanoid alien dies). It actually makes sense, because they act as a hivemind and should feel when other hivemind member gets fucked. Also sometimes it is confusing when your blobernaut goes away to... idk... do something? and you don't understand did he die or not.

# Changelog

:cl: SuperSlayer
rscadd: Blob gets a message when a blobbernaut dies
rscadd: Alliens get a message when a humanoid alien dies
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
what about humans with hive nodes

**Comment by ghost** [comment]
> what about humans with hive nodes

Uhhhh... Probably their also get the message

**Comment by Marmio64** [comment]
Should only send the message to the queen/over mind honestly

**Comment by ghost** [comment]
> Should only send the message to the queen/over mind honestly

It is ok. And in the blob part only the overmind gets the message.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
