### PR TITLE
Remove triple refill mode from air alarms

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
del: Removes triple refill mode from air alarms
/:cl:

It's outdated with the new atmos, and just results in rooms being 300 kPa.

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
I'll cut you.

**Comment by Hopekz** [comment]
> I'll cut you.

Ok Google call the police

**Comment by Readystorm546** [comment]
Does this mean Plasma flood via AI is a pain in the ass

**Comment by MegaEmpirical** [comment]
If you're using triple refill to plasma flood, you've already fucked up.

**Comment by monster860** [comment]
if you really need to jack up the pressure on the air vents you can do it yourself better.

**Comment by alexkar598** [comment]
It has a use to flood gas onto the station

**Pull request merged**
