### PR TITLE
disables pheromone receptors

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

in my [last attempt](https://github.com/yogstation13/Yogstation/pull/7056) people seemed to really like the absorb ling objective which i didnt really care about so im remaking it with just this bit

**how does this benefit the game?**
lings that want to get mega uber will now have to manipulate or deceive other lings or keep a keen eye out for other lings and capitalize on their low chemicals/being lynched

**lings will be hesitant to work together now because they could be deceived into being succed while before they could just be easily hunted from the shadows unless they themselves wasted 2 points on pheromones which was pretty much the meta if you didnt want to get bumfucked by mr. powerling**

this will not encourage ling metagangs, if anything it will massively discourage it for reason(s) listed above

as a side note ive had ling disabled for quite a long time

input welcome

#### Changelog

:cl:    
experimental: Pheremone Receptors have been disabled
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Terrible PR.

New Meta with this PR:
-------
**if you have absorb another ling objective:**
Talk and try to get the other guy to give you information otherwise you're fucked. Be fucked anyway because no-one else has this objective so no-one wants to cooperate.
**else:**
stay quiet so you don't get succed by another ling.

Yes people play like assholes you know this.
If we have the "absorb another ling" objective we need to have a way to locate them in my opinion.

**Comment by ynot01** [comment]
> If we have the "absorb another ling" objective we need to have a way to locate them in my opinion.

which is why my last pr removed it aswell but people like it and dont care about this apparently

**Comment by monster860** [comment]
Either have both pheremone receptors and absorb-a-ling objective, or neither. Not this.

**Comment by overlord12345** [comment]
I dont get why people like the "absorb another ling" objective anyway this is good cause now they atleast have to talk.

**Comment by ynot01** [comment]
> Either have both pheremone receptors and absorb-a-ling objective, or neither. Not this.

see https://github.com/yogstation13/Yogstation/pull/7056

if you disagree with asv9 closing it feel free to reopen it and close this one in return (or don't)

**Comment by Hopekz** [comment]
> Either have both pheremone receptors and absorb-a-ling objective, or neither. Not this.

I agree with monster. 
**Its a either both or none type of deal.**

**As far as removing both:**
 I like this changeling objective and like the gameplay it adds (yes including your "sneak from the shadows" method you mentioned).
It doesn't "take away" from the experience in my opinion. I like this feature.
Keeping my -1 on this PR.

**Comment by MegaEmpirical** [comment]
I have no issue with the objective but removing this without removing the objective is dumb. Changelings avoid each other normally even with this power already in play.

**Comment by alexkar598** [comment]
Closing due to mostly negative feedback and personally I don't like this change either  it's the frustration of where the fuck is my steal objective gone to mixed in with my steal objective can camouflage itself and attack me, that's where this analogy starts to break down but I just see frustration here. I don't think being surprised attack is such a problem for lings as they have more than the tools needed to fight back

**Pull request closed without merging**
