### PR TITLE
Some minor YogsMeta fixup

### PR DESCRIPTION
**Pull request by Absolucy**
:cl: Lucy
tweak: YogsMeta no longer has bruise packs and ointment in front of medbay, they have been replaced with regenerative mesh and sutures
tweak: YogsMeta's AI MiniSat is now properly wired up at roundstart.
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
thanks a ton

**Review by patpol4 — APPROVED** [review]
Is good

**Comment by Absolucy** [comment]
oh wait i need to fix for this ai revamp

**Review by patpol4 — DISMISSED** [review]
Actually not, there's a conflict

**Comment by Absolucy** [comment]
merge conflict fixed :)

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
