### PR TITLE
Ports Bounty Boards

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
Ports
https://github.com/tgstation/tgstation/pull/51449

Feauturing sprites from the lovely Partheo :3
image

#### Changelog

:cl: ArcaneMusic
rscadd: The bounty board has been added to all standard NT stations, for making and paying out bounties for credits made by crew members across the station. Available as a standalone machine, as well as a modular app.
/:cl:

### CODE REVIEW

**Review by Partheo — CHANGES_REQUESTED** [review]
Sprites need improvement, working on it now.

**Comment by Partheo** [comment]
Allow edits from maintainers and I'll commit the sprite changes.

**Comment by Partheo** [comment]
ya done fucked up

**Comment by Bibby0110** [comment]
> ya done fucked up

just revert it lmao easy

**Review by Partheo — APPROVED** [review]

**Pull request merged**
