### PR TITLE
fixes the server forever

### PR DESCRIPTION
**Pull request by athena413**
it fixes the entire fucking server, including every single issue this server has. its just the best fucking PR ever made, you don't need to thank me for this

### CODE REVIEW

**Comment by patpol4** [comment]
Bro you have a merge conflict

**Comment by ynot01** [comment]
this joke has been done a thousand times you're cringe

**Comment by Marmio64** [comment]
Yeah I see at least 500 merge conflicts... gonna have to fix em bro...

**Comment by Hopekz** [comment]
I already did this exact may may 2 times

**Comment by JamieD1** [comment]
Need to clear out the garbage, Sorry Janitor here.

**Pull request closed without merging**
