### PR TITLE
No more IPC brains in organic chests

### PR DESCRIPTION
**Pull request by Moltijoe**
No putting an ipc brain into a brainless bodies' chest and cloning them to make an organic ipc

:cl:  
bugfix: No more IPC brains in organic chests
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
It’s a feature

**Comment by Annoying-plant** [comment]
this is really cool and if it wasn't intended to be a feature it should be

**Review by ReddicusDragon — APPROVED** [review]
bruh

**Comment by bruhlookatthisdood** [comment]
make it so you can put a ipc brain into an mmi then put the mmi in a human brain

**Comment by Moltijoe** [comment]
> make it so you can put a ipc brain into an mmi then put the mmi in a human brain

that would break so much shit

**Comment by JamieD1** [comment]
Is this one of those circumstances where an oversight becomes a feature?

**Comment by Moltijoe** [comment]
> Is this one of those circumstances where an oversight becomes a feature?

seems like it might be

**Pull request closed without merging**
