### PR TITLE
Adds COVID-19 to the game

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

**Changed from covid-19 to covid-2556**

This adds COVID-~~19~~ 2556 (coronavirus) to the game which mimics the flu but is harder to cure and has higher contagion.

#### Changelog

:cl:  
rscadd: Adds coronavirus 
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
what a shitty web edit

**Comment by swissloaf** [comment]
> what a shitty web edit

shut the fuck up!!!!

**Comment by Bibby0110** [comment]
it's not even a .dm file
it's not even in the dme

**Comment by jcatjmeow** [comment]
I think this is distasteful, and not conducive to the higher standard of rp we are going for

**Comment by swissloaf** [comment]
we got da monstar

**Comment by boodaliboo** [comment]
In bad taste

**Comment by swissloaf** [comment]
it's like 9/11, we'll give it a month

**Comment by Featherfield** [comment]
I will rather have hard to cure cough than fucking brainrot from an event

**Comment by alexkar598** [comment]
Imagine someone having their grand mother die of corona virus, they were really close to her, they play a game and get a memey virus. Yeah how about no, maybe in 3 years.

**Pull request closed without merging**
