### PR TITLE
Decrease cult scaling coefficient

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Cult seems to be feeling a little unloved nowadays, with how easy it is for one member to slip up which breaks the initial snowball that cult requires to gain a foothold, so let's give them a few more members at roundstart..
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Cultists now get more members at roundstart
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
pretty sizable buff, not against it, but i worry this might be overdoing it, this would give them 2 additional people in a 50 person round

instead of going from 9.3 to 7.3 i'm wavering closer somewhere between 7.8 and 8.3

**Comment by Simplehorror** [comment]
yeah 2 extra people is what i'm aiming for, you have to understand you're going to get either 1. a dud or 2. good player, and you need atleast 2 good players to win, which is what i'm trying to go for since if I tried to do it from playtime my PR would get closed
i'm hedging bets basically

**Comment by Simplehorror** [comment]
unfortunately if your entire team is good players it'll be a stomp for you but that's the way the game goes and nothing i can do it without playtime stuff

**Comment by Moltijoe** [comment]
> yeah 2 extra people is what i'm aiming for, you have to understand you're going to get either 1. a dud or 2. good player, and you need atleast 2 good players to win, which is what i'm trying to go for since if I tried to do it from playtime my PR would get closed i'm hedging bets basically

problem with this is that it's sorta multiplicative, not only does cult have two more players, but given the exponential growth of cults, this can put them significantly futher in their goals.
It gives the cult as a whole a broader net of influence as their starting members are usually spread out between departments.
not to mention, most early converts are people that are utterly useless and just let themselves get captured, where as these 2 players being selected from the entire crew means it can pick some very competent people

**Comment by JamieD1** [comment]
Lets try one extra first

**Comment by Simplehorror** [comment]
@JamieD1 done

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
