### PR TITLE
Icon smoothing, and Rendering overhaul, and Camera fix, and mapmerge.py fix, and Multi-z, and THE PLANE CUBE

### PR DESCRIPTION
**Pull request by Chubbygummibear**
# Document the changes in your pull request
I ain't going to heaven after this one. I changed like everything about rendering. All in the name of bitmask smoothing for @ToasterBiome . I don't even know if I can really summerize what I did anymore after everything I changed. Players aren't really going to notice a difference, but everything is different code wise. Sorry and you're welcome

Unholy fusion of 
- https://github.com/yogstation13/Yogstation/pull/21001
and
- https://github.com/yogstation13/Yogstation/pull/21062

With more I forget

Special thanks to @cowbot92, @JohnFulpWillard, @ToasterBiome, @LazennG, @Moltijoe, @LemonInTheDark, @azzzertyy  and  other people I love you

## List of things I gotta fix: (updated 1/11/24)
- [x] bluespace locker planes/layer
- [x] stations slowly getting overtaken by darkness probably due to static/dynamic lighting mismatch from roundstart
- [x] wood walls have no sprites
- [x] reinforced plasma windows
- [x] centcomm bays aren't fullbright
- [x] some stair icons missing
- [x] windoors not stopping people sometimes
- [x] people not slipping right

## List of things I gotta fix: (updated 1/23/24)
- [x] reinforced windows can we walked through when sliding
- [x] holodeck broken on icemeta
- [x] pda double message sent (ignored for now)
- [x] vents and scrubbers under floor tiles
- [x] ai static layer broken
- [x] false walls disappear when opened
- [x] ice sheets icon broken
- [x] gps arrows broken
- [x] dragging mats not collecting
- [x] clockies don't have consoles

## List of things I gotta fix: (updated 1/29/24)
- [x] ventcrawling visuals
- [x] laser pointer overlay
- [x] borg not being able to return to ai on death??
- [x] modular consoles not having screens for bridge
- [x] atmos not updating between space and rooms (maybe my fault?)

# Why is this good for the game?
Trust

# Testing
Dude Trust

# Spriting
Tables are different

# Wiki Documentation
Uhhhh

# Changelog

:cl:  Chubbygummibear, cowbot92, JohnFulpWillard, ToasterBiome, LazennG, Moltijoe, LemonInTheDark, azzzertyy
rscadd: Rendering backend is like 200% different
rscadd: stuff glows in the dark
rscdel: Overlay smoothing is dead
bugfix: Cameras and other popup maps work on clients >1615
bugfix: mapmerge tool shouldn't blow up multi-z maps anymore
wip: Yes
mapping: icemeta got flipped but it should be the same from top to bottom
experimental: yeah
/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
Good first PR

**Comment by neeshacark** [comment]
So real

**Comment by LemonInTheDark** [comment]
bonfire

**Comment by LaOubliette** [comment]
I noticed that slips didnt work and also windoors can be walked through from some sides

**Comment by Chubbygummibear** [comment]
> I noticed that slips didnt work and also windoors can be walked through from some sides

thankie i added those to the todo

**Review by neeshacark — APPROVED** [review]
Doesn't mess with maps in any meaningful way, although I do think it changes exotic carpets into normal ones in some spots but that's not really a big deal.

**Comment by cowbot92** [comment]
> Doesn't mess with maps in any meaningful way, although I do think it changes exotic carpets into normal ones in some spots but that's not really a big deal.

no it actually currently changes the color of all tiles with decals on them

**Comment by AMyriad** [comment]
bug with this involving gibtonite activation not showing up when triggered, several miners have been round removed because of this RIP

**Comment by Chubbygummibear** [comment]
> bug with this involving gibtonite activation not showing up when triggered, several miners have been round removed because of this RIP

just pushed a commit to hopefully fix this. tested briefly with a standard rock wall that has gibtonite and it showed up after i struck it so i'm hoping that's it

**Comment by JamieD1** [comment]
Im out of the Loop, im happy if @ToasterBiome is.

**Comment by AMyriad** [comment]
love the general vibe the new lighting/rendering gives off, especially the glow from the stars actually illuminating space
not a fan of the undocumented grille sprite change though, the ones we have rn are quite fine, and have a better look than these new over-simplistic ones imo

(ditto with reinforced tables but that's not as big of a gripe to me)

**Review by ToasterBiome — APPROVED** [review]
LGIM

**Pull request merged**
