### PR TITLE
Service Radio is now Blue-Green

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Changes the color of service channel

image

#### Changelog

:cl:  
tweak: Service channel is now readable
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
<3

**Comment by Hopekz** [comment]
We change the hue of the service channel every few months

**Comment by Tipy1802** [comment]
Looks too much like common

**Comment by redmoogle** [comment]
image
Changed color

**Review by MrHorizons — APPROVED** [review]
I've always been annoyed by the shitty contrast of the service channel. This is good.

**Review by jcatjmeow — APPROVED** [review]
Tested and it looks lovely

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
