### PR TITLE
Adds Nanite Sting

### PR DESCRIPTION
**Pull request by CMOisLing**
Original PR: https://github.com/tgstation/tgstation/pull/46907
#### Changelog
Adds nanite sting so people stop asking for it in devpublic
:cl:  
rscadd: Nanite Program: Nanite Sting   
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
I'm going to fucking hate this.

**Comment by Ratvar** [comment]
Stop buckling under pressure of griefers and powergamers asking to remove the only weakness of nanites

**Comment by CMOisLing** [comment]
Dont drag me into this im neutral about it, im doing this as a favor

**Comment by ShadowDeath6** [comment]
not a huge fan of this, isn't there already an infection program that basically does this job? I don't think we need the same thing but more accessible

**Comment by oklews** [comment]
I’d much rather port the nanite button, this will be painfully overpowered

**Comment by oklews** [comment]
This will be the new radball, I swear

**Comment by boodaliboo** [comment]
Shadow the only other infection tool is from aliens

**Comment by alexkar598** [comment]
This is restricted behind a lot of tech but again. This is nanites and I hate those

**Comment by LoliconSlayer** [comment]
This is just... bad.

**Comment by Quartich** [comment]
I thought infection didn't create new nanites in people, just copied over it's own cloud ID

**Comment by alexkar598** [comment]
Generally negative feedback

**Pull request closed without merging**
