### PR TITLE
YOU CAN NOW PUT HATS ON HARDSUIT HELMETS

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Drip Central
All my homies hate modsuits
It does not give you more armor
image
image

# Changelog

:cl:  
tweak: You can now place hats on hardsuit helmets for purely visual effect.
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
armor stack armor stack?!?!?!?!

**Comment by PibeCantina** [comment]
Can i take them out though

**Comment by RG4ORDR** [comment]
This is the best PR you've ever done.

**Comment by ynot01** [comment]
> Can i take them out though

Taking off the hardsuit helmet drops the hat

**Comment by azzzertyy** [comment]
can you do this for clown/mime masks but for cigarettes

**Comment by ynot01** [comment]
> can you do this for clown/mime masks but for cigarettes

another time perhaps

**Comment by JohnFulpWillard** [comment]
Good attempt at making this an Element here https://github.com/tgstation/tgstation/pull/64123 if you want to generalize this.

**Comment by ynot01** [comment]
> Good attempt at making this an Element here [tgstation/tgstation#64123](https://github.com/tgstation/tgstation/pull/64123) if you want to generalize this.

overengineered

**Comment by JohnFulpWillard** [comment]
> overengineered

Is what elements are not.

**Comment by ynot01** [comment]
> Is what elements are not.

image
image
they werent even done
image

**Comment by JohnFulpWillard** [comment]
Lines changed does not mean overengineered. The lines changed there is also including the removal of the feature that was copy pasted onto plasmamen helmets and modsuit helmets.
You also miss the point of an Element, making it one means you can noy only put it on hardsuit helmets, but plasmamen helmets (like TG) and even borgs, removing the need to copy paste the code everywhere. It's better for the codebase as a whole.

**Comment by Addust** [comment]
give nukie leaders syndicate cap and beret

**Review by ToasterBiome — APPROVED** [review]
this is stupid

**Pull request merged**
