### PR TITLE
Mining Base No longer sucks atmos wise

### LINKED ISSUE #9909: Tile that feeds mining station atmos from the exterior vent is not updating
Mining atmos cannot refill itself due to the tile that feeds the vent that feeds the system not updating. Once it has siphoned the air on that tile (assuming it starts with any) no new air flows in and it remains at 0 kpa. Alexkar was able to fix it on the live server during a round, appears to be an area/turf issue.

### PR DESCRIPTION
**Pull request by JamieD1**
Fixes: #9909 

### Intent of your Pull Request

Mining Base No longer sucks atmos wise

#### Changelog

:cl:  
bugfix: Mining Base No longer sucks atmos wise
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
Wait, do we not need to break a window to get in and out anymore if this gets merged? Holy shit

**Comment by patpol4** [comment]
What did you do, diffs didnt generate a preview

**Comment by JamieD1** [comment]
> What did you do, diffs didnt generate a preview

Added atmos miners instead of using atmosphere

**Review by patpol4 — APPROVED** [review]
Map is fine now but made by me, Jamie is apparently still doing some changes though

**Comment by MegaEmpirical** [comment]
I don't see these miners, where they at?

**Comment by patpol4** [comment]
The miners were not added in the end because it was deemed too dangerous for lavaland atmos.

**Pull request merged**
