### PR TITLE
Nicotine-free cigarettes

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

cigarettes with 15 units of carbon instead of nicotine
added to cig vendor + syndicate cig vendor
for people that want to smonk for cool look but dont want the shit nicotine jitters
U2DyngW
pack
```
name = "nicotine-free cigarette packet"
desc = "A dull-looking pack of cigarettes."
```
cig
```
desc = "A nicotine-free cigarette."
```

#### Changelog

:cl:  
rscadd: Added Nicotine-free cigarettes
/:cl:

### CODE REVIEW

**Review by Hopekz — APPROVED** [review]

**Comment by deathslayer2481** [comment]
Whats the fucking point

**Comment by SomeguyManperson** [comment]
> Whats the fucking point

>for people that want to smonk for cool look but dont want the shit nicotine jitters

**Comment by boodaliboo** [comment]
maybe have it give carbon itself as its just paper

**Comment by alexkar598** [comment]
^

**Comment by Hopekz** [comment]
Both Carbon and silicon provide the same effect when smoked so it's virtually the same except flavor text at this point.

You changed it regardless looks good to go

**Pull request merged**
