### PR TITLE
Steals camera sprites from TauCeti

### PR DESCRIPTION
**Pull request by cowbot92**
FULL CREDIT TO THE ORIGINAL SPRITES GO TO THE ORIGINAL PR:  https://github.com/TauCetiStation/TauCetiClassic/pull/10813

# Document the changes in your pull request

new camera sprites

# Why is this good for the game?

I like them they look cooler

# Testing

image

# Spriting

yep

# Wiki Documentation

probably

# Changelog

:cl:  

imageadd: adds new camera sprites
imagedel: deletes old camera sprites

/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
looks cool but very shiny, and less detail for attachments/mods
we could do better methinks

**Comment by cowbot92** [comment]
> looks cool but very shiny, and less detail for attachments/mods we could do better methinks

When was the last time you noticed an upgraded camera vs a regular one

**Comment by AMyriad** [comment]
> > looks cool but very shiny, and less detail for attachments/mods we could do better methinks
> 
> When was the last time you noticed an upgraded camera vs a regular one

Every time I go past armory, every time I upgrade cameras, etc. I _do_ notice them quite often

**Comment by cowbot92** [comment]
> > > looks cool but very shiny, and less detail for attachments/mods we could do better methinks
> > 
> > 
> > When was the last time you noticed an upgraded camera vs a regular one
> 
> Every time I go past armory, every time I upgrade cameras, etc. I _do_ notice them quite often

nuh uh

**Review by cuackles — APPROVED** [review]

**Comment by neeshacark** [comment]
not a big fan of them being smaller but no issues besides

**Pull request merged**
