### PR TITLE
Ports TGUI Crew Manifest

### PR DESCRIPTION
**Pull request by ThatLing**
# Document the changes in your pull request

Ports the following PRs, credits to the original authors.
- https://github.com/tgstation/tgstation/pull/58275
- https://github.com/tgstation/tgstation/pull/58300
- and some other misc fixes

image

# Changelog

:cl: celotajstg
rscadd: Crew manifest has been converted to TGUI
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Give heads a rank they deserve, why would they be privates

**Comment by MajManatee** [comment]
Can we show heads with symbols other than a singular chevron? Such as the HoP having 3 and the HoS having two, while the rest remain 1 to show they are lower and less important or something?

**Comment by ThatLing** [comment]
> Can we show heads with symbols other than a singular chevron? Such as the HoP having 3 and the HoS having two, while the rest remain 1 to show they are lower and less important or something?

We can if you sprite it (or find a suitable free font-awesome icon)

**Review by ynot01 — DISMISSED** [review]
Having `(x positions open)` feels very out of place on the manifest

**Pull request closed without merging**
