### PR TITLE
Hierophant becomes old hierophant again

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

It looks better compared to the current one tbh 

hierophant_old

hierophant

#### Changelog

:cl:  
tweak: Changes icon for hierophant
/:cl:

### CODE REVIEW

**Comment by Takahiru** [comment]
How about let's not completely rip off hld and keep the current Hierophant, the current one looks good with the style.

**Review by Partheo — CHANGES_REQUESTED** [review]
I think this change is unnecessary but let's see what people think.

Change the appropriate descriptions too. This is an extremely lazy PR.

**Comment by MrHorizons** [comment]
What if we gave the current Hierophant sprite the clothes of the old one?

**Comment by Readystorm546** [comment]
Yo thats badass

**Comment by Reed0506** [comment]
i dont like this at all

**Pull request closed without merging**
