### PR TITLE
Adds the 'Assistant Pod' Ruin to space

### PR DESCRIPTION
**Pull request by UselessTheremin**
This PR adds the ruin called 'Assistant Pod' to space. The ruin has some fun stuff such as a toolbox, insulated gloves, a clown bedsheet, a Gold ID Card (with no access), a fake Emag, two corpses, and some carps. This is my first PR and map I have ever made, so if I made a dummy mistake please keep that in mind.

🆑 
add: fixed the turf error and some other mapping problems.
tweak: removed one of the three carps
add: added a honkbot named 'medibot v2' and renamed the gold id to 'captains spare id'
/🆑

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
Remove assitantpod.dmm from root, remove the .dme edit, make the area a subtype of the areas other ruins use, not space. Will take a look at the actual map later

**Comment by UselessTheremin** [comment]
fuck i committed the same thing 3 times smh

**Comment by monster860** [comment]
just for the memes you should totally rename the gold id card to captain's spare id

**Review by patpol4 — CHANGES_REQUESTED** [review]
chrome_NDGeeBrP4Z
1. Space turf under engine, use sand or template
2. two engines stacked on top of each other
3. Don't use indestructible sand, use /turf/open/floor/plating/asteroid/airless
4. heater flipped 180 degrees
5. The carpet starts with atmos, edit this variable to match the others since we dont have airless carpet,
chrome_xnaF5byT6b
6. The linter error on github can be fixed by getting rid of the .dme edit, just delete it and paste a fresh updated one. Or just update your branch from upstream.
7. The posters should be inside the shuttle and pixelshifted 32 pixels onto the wall, look at posters in boxstation to see what i mean.
8. Pretty sure the hollow window spawner already contains a grille, no need to add another one under it, leave just the spawner
9. I'll kiss you if you set the name of the id to captains spare, also this is not going to work, access is set with numbers.
chrome_YebAqFKrBr

10. No way to get from here to there other than over the table, unless this is supposed to be cluttered, this is bad.
chrome_LwSCxxk38Q
11. I think you went a little overboard with the floor decals, no need to have them on every tile.
12. 3 carps for this ruin is overkill, use 1 or 2 , if you want two make sure to separate them so they dont attack you all at once, put one inside and the other outside

**Review by patpol4 — CHANGES_REQUESTED** [review]
1. Access is set by numbers, not words, also you got a tyop in there
chrome_uC7lRJ9qM1

2. Grille is not needed
chrome_rlAake3V1n
 
Just fix this and it should be good to go, sorry for the delay

**Comment by patpol4** [comment]
Closing by authors request

**Pull request closed without merging**
