### PR TITLE
Nerfs the centcomm endround beam rifle

### PR DESCRIPTION
**Pull request by fluffe9911**
:cl: 
tweak: The beam rifle on centcomm is now a normal beam rifle instead of instakill rifle v2
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
why

**Comment by swissloaf** [comment]
delete this

**Comment by ynot01** [comment]
hoes mad

**Comment by Ludox235** [comment]
**HOES MAD**

**Comment by Firewolf34** [comment]
thank god

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
