### PR TITLE
[Hugbox] AI Can reset to asimov within 2 minutes of being created

### PR DESCRIPTION
**Pull request by JamieD1**
Sometimes people just don't want to be forced into stuff they don't want to do, this at least gives an easy way out without having to forced to do sketchy lawsets.

:cl:  
rscadd: [Hugbox] AI Can reset to asimov within 2 minutes of being created
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
So theres two possibilities here, a reset cannot conflict with the current laws or it can. Both are bad
If it never conflicts:
>be ai
>created by traitor robo
>have malf laws
>reset to asimov
>rat out robo

If it can conflict, then it would violate most lawsets to reset your laws because it breaks your laws to make it so that you dont need to follow your laws anymore

**Comment by Marmio64** [comment]
I feel like you accept the risk of getting a shitty lawset when you play AI and just need to roll with it. If someone is purposely being an ass with your laws that's likely an ooc issue.

**Comment by Xantam-13** [comment]
I come from an era where reportotron laws didn't exist, and when you started on asimov laws 100% of the time. I loved playing AI and Robo's. I know I am not alone in saying that the random laws, or rather - the pool of lawsets in the random laws at roundstart are incredibly stupid and in some cases unfair. 

As an AI - I just like being the overloard all seeing eye who opens doors and says no to the clown, why should I - because someone PRd it - be forced to report on every single thing that I see and exaggerate the truth? Naaaah. 

I'd even be happier with the pool laws being changed to incorporate more user-friendly laws - with reportotron and others being left to being added by the captain or RD. 

I don't see why the AI and Borgs should have to endure random crappy lawsets just because they do a role they enjoy? It makes no sense. This PR is good as it reverts you back to standard. 

I don't agree with Alex's take on it either. This is for within 2 minutes of round start. Which is not enough time even for a competent traitor to change the lawsets. 

If this applies to anything outside roundstart, I'd suggest that is changed. Mid-round AI's should start from a pool as, as alex said, traitors run the risk of the AI rebooting their laws. This button should only happen from round-start AI's from within 2 minutes of round-start.

**Comment by JamieD1** [comment]
> 

This is an OOC decision, dont involve current laws into this button. Thats kinda stupid to say this is limited by your current lawset.

**Comment by alexkar598** [comment]
I argued that both possibilities are bad. If it's OOC it allows for fuckery with traitor laws

**Comment by JamieD1** [comment]
> I argued that both possibilities are bad. If it's OOC it allows for fuckery with traitor laws

No it doesnt because it doesnt clear zeroth laws. If you are just talking about ais later on in the game I can fix that.

**Comment by ynot01** [comment]
i think this is a good change, AIs will roll into lawsets that they either hate or are too long for them to care about and YES while optimally we would have those AIs just play better 4head that's not going to happen and it's not enforceable, it just creates shit for everyone

if AIs don't feel like curating a RNG gimmick then so be it

alexkar's points are valid but they don't defeat what this PR aims for, he just wants to make sure people can't abuse this and break rounds, which i of course agree with

**Comment by Xantam-13** [comment]
I would suggest that this only applies to round-start AI's, not late-joins or mid-round creations. On round-start you get 2 minutes to click the button, which won't mess with anything. 

Mid-late joins/creations have the potential of being subverted within 2 minutes, for the AI to reset. And this is a situation which cannot be allowed to happen. 

Lastly, the AI should automatically state laws when it presses the button, stating only the core 3 it reverts to. This is to ensure crew are well informed, and to prevent AI's stating laws before the change either accidentally or to fuck with the crew, to then press the button and have the crew none the wiser. 

Please can these changes be made?

**Comment by maxion12345** [comment]
imo if you cant navigate the roundstart lawsets then you probably shouldn't be playing AI, especially when you will be encountering more confusing ion laws and even more confusing player-uploaded laws

That being said having a 'preferred lawset' would be nice, but I'm afraid people will only choose to take this choice if their lawset is one that disallows hunting of antagonists on lawsets that prevent harm globally (crewsimov, reportertron, etc)

**Comment by JamieD1** [comment]
Solved with #14699

**Pull request closed without merging**
