### PR TITLE
Perspective Structures.

### PR DESCRIPTION
**Pull request by nesisknesis**
Perspective structures are Walls, windows, and airlocks that have a 3/4 perspective. 

For instance:
image
image
image

Some areas are scuffed and these are only examples. I am aware of the sprite issues as well.

The windows look a bit aids but this will be rectified, and transition issues will also be looked at.

As of yet, I have not started on airlocks, which will both be 3/4 and directional. 

Throughout the summer holidays, I will work on these and this draft is to allow people to post their thoughts on it.

The issue of objs on the southern side of rooms is also known and may require a remap of every map that will have perspective walls.

Also, these sprites were made a while back, and so this is the earliest stage.

#### Changelog

:cl:  Identification
experimental: Perspective Structures.  
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Can you post a screenshot without xray?

**Comment by GenericDM** [comment]
Baystation has some good assets that could be ported for this. Not sure about licensing on them though.

**Comment by AsV9** [comment]
@GenericDM 
image

basically it's fine to take stuff aslong as you state changes, and their license permits relicensing to our license

**Comment by Bibby0110** [comment]
@AsV9 Not exactly true I am afraid

**Comment by AsV9** [comment]
well enlighten me then mr lawyer

**Comment by Kmc2000** [comment]
The smoothing on these kind of sprites is tricky to pull off. From your screenshots, I can see a few errors ( south three way wall, corner going into two other walls ). You'll need to fix those before adding these in game.

**Comment by Bibby0110** [comment]
@AsV9 https://lmgtfy.com/?q=agpl+v3&s=

**Comment by AsV9** [comment]
I know what AGPL is, I'd like you to tell me why what I said was incorrect.

**Comment by Bibby0110** [comment]
because it is

**Comment by Ratvar** [comment]
nooo

**Pull request closed without merging**
