### PR TITLE
[ALL MAPS] Fixes a bunch of wrong access requirements in engineering

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
For help with reviewing:
10 = Engineering access
17 = Teleporter access
32 = Construction access
65 = AI sat access
19 = Bridge access

I remember first noticing this one when someone had issues going into engineering after I changed their access as a hop a few months back.

The problem was most engineering doors had construction access instead of engineering, and the little area to the right where one would go to the AI sat had really weird access reqs
(this area)
image

So thas fixed now. Most of engineering now has engineering req, and the windoor in the aforementioned area now needs AI sat access to get to (makes sense), which the net admin has so I don't think there will be any issues.

# Testing

https://github.com/yogstation13/Yogstation/assets/143908044/6a44c13b-887a-45ed-ae6c-720acb140e95

https://github.com/yogstation13/Yogstation/assets/143908044/808301cd-e922-46cc-82f5-5bb1f5b8032b

https://github.com/yogstation13/Yogstation/assets/143908044/ef026a2f-1d5e-48fc-ac0c-3dafd0b73070

# Changelog
:cl:  
bugfix: Fixed a lot of engineering doors having incorrect access requirements
tweak: Curators may now only go as far as where the protolathe is in engineering
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
im pretty sure some of this is intentional

**Comment by AMyriad** [comment]
> im pretty sure some of this is intentional

Is there a certain area ye were thinkin about?
None of these access reqs either make sense or follow consistency

**Review by neeshacark — CHANGES_REQUESTED** [review]
Set the foyer/lathe access to either/or construction/engineer so that roles who have construction access don't need their access modified to retain the same reach they have now

**Comment by AMyriad** [comment]
> Set the foyer/lathe access to either/or construction/engineer so that roles who have construction access don't need their access modified to retain the same reach they have now

nice that's a better solution than anything I would've thought of
done as of last commit

**Review by neeshacark — APPROVED** [review]

**Pull request merged**
