### PR TITLE
[AI] AI Revamp | AI runs off of actual servers now

### PR DESCRIPTION
**Pull request by Bibby0110**
### For the AI
Your 'core' now consists of a physical server placed on the station. If this server is destroyed you're transferred to any other functioning server. You die when you run out of servers to transfer to. Theoretically there can be infinite servers, but it is up to the crew to build them.

You have 1 new button in your HUD:
image
Clicking this opens the following menu:
image

As you can see at the top it shows how much health you have (Currently placeholder, will show server health in the future)
You can see the location and the temperature, which can't be too high
On the second line you can see how much CPU/RAM you have.
CPU is used for researching new upgrades. RAM is used for running them.

You research by typing in the amount of your CPU you want to allocate into the following box:
image

After a project is completed it will go into the 'Completed Projects' folder where you can start/stop programs as seen below:
image

The third tab contains an overview of all available processing power network wide. You can't interact with these unless they're assigned to you. Read more about assigning processing resources in the "For the Crew" section.

### For the Crew
The AI is now dependent on you creating new Expansion Card Busses, which are regular machines you can create like any other. The circuitboard is gotten through the 'Artificial Intelligence' science project. This also unlocks the printing of CPU and RAM cards.
Adding CPU and RAM cards to an expansion card bus allows those resources to be assigned to the CPU. A bus can hold a maximum of 3 cards each.
Be aware that the Expansion Card Bus needs to be in a cool environment, which is not exposed to space, to be able to function.
The power usage is dependent only on the amount of CPU cards inserted. There's a penalty every time you add a CPU card to a bus in the form of exponential power drain.

When you've created an Expansion Card Bus for the AI you can assign the resources to it by using the 'AI system resource distribution console' in the room next to the old AI core.
It looks like this and is pretty self-explanatory:
image
There's also an 'AI server overview console' which has the following UI:
image

#### AI Data Cores and you
AI Data cores are a new type of machine just like the expansion card bus. Instead of accepting CPU and RAM cards this machine is only used for hosting an AI. Consider it like an extra 'life' incase the AI loses its current data core. It too needs to be in a cooled room, and should not be in the same room as another data core as that negates the purpose. (Both would likely be destroyed at the same time)

#### Making new AIs and carding the current one
Using the last new console, the 'AI control console' you can upload new AIs to the network. This is done by either:
1. Hitting the console with an active posibrain.
2. Inserting an intellicard with an AI already in it.
The UI for uploading looks as following:
image
Downloading looks like this:
image
It requires an IntelliCard to be inserted. When the download is started the AI is notified and told where the download is coming from. After a certain amount of time which the AI can change using upgrades, the AI is transferred to the inserted IntelliCard.

## PR Concept
Old PR: https://github.com/yogstation13/Yogstation/pull/12262 (For stealing your comment ideas)

Malf will not be touched other than to make it function besides this system. Not in this PR at least.

Instead of being based on a singular core the AI is now an actual computer living through servers on the AI sat.
There is no core to kill, instead when an AI is created it's uploaded to the cloud and run through these servers.

Some AI roundstart abilities have been removed and moved to upgrades. (Being able to see mindshields is a prime example of this.)

The core itself requires cooling which is mapped in at roundstart. More cooling is potentially needed if enough additional CPU cards are installed. (RAM cards don't produce a noticeable amount of extra heat.)

Turns the Sig Tech into the Network Admin, in charge of general AI upgrades and caretaking.

### WIP (For this PR, aka MVP):

- [x] Make malf function properly (Allow malf AI to stop downloads for example)
- [x] Check that servers don't run in a vacuum.
- [ ] Make AI Data Cores actually require cold.
- [x] The other maps need this too
- [x] Potentially do something about clockcult/infiltrators?
- [x] Fix AI display core being density = FALSE
- [x] Clicking datacore kicks the AI, most likely because it's on the same tile?
- [x] Resource console is human_only = 1, make = 0.
- [x] Roundstart AI should probably be assigned the roundstart CPU/RAM
- [x] Sensor augmentation not working correctly?
- [x] Integrate with Infiltrator mode

Additional PRs will do the following:
- [ ] Network Admin role
- [ ] Multiple tiers of CPU and RAM cards
- [ ] Overclocking CPUs
- [ ] A bunch more upgrades for the AI
- [ ] ??? Suggest what you want

# Changelog

:cl:  
wip: This changelog
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
merge conflicts lmao

**Comment by maxion12345** [comment]
> merge conflicts lmao
Welcome to the merge zone
Only merge mapping prs
yogstation changes
Double mapping pr
Fresh changes
Elegant mapping
First the merge...
...then the conflict

**Comment by TerryTehCoder** [comment]
Is there a list of things still under development anywhere? This is a really cool project and i'd like to follow it.

**Comment by Bibby0110** [comment]
> Is there a list of things still under development anywhere? This is a really cool project and i'd like to follow it.

everything is still under development

**Comment by KittyNoodle** [comment]
doesn't seem to be compiling with the build command, is their another way of compiling for testing

**Comment by KittyNoodle** [comment]
tried to build it, got this:
code\modules\asset_cache\asset_list_items.dm:6:error: 'tgui/public/tgui-common.chunk.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:12:error: 'tgui/public/tgui.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:13:error: 'tgui/public/tgui.bundle.css': cannot find file
code\modules\asset_cache\asset_list_items.dm:19:error: 'tgui/public/tgui-panel.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:20:error: 'tgui/public/tgui-panel.bundle.css': cannot find file
yogstation.mdme.dmb - 5 errors, 0 warnings (11/20/21 12:38 pm)
Total time: 3:52
ExitError: Process exited with code: 4294967295
    at ChildProcess.<anonymous> (C:\Users\jacks\Desktop\PARASERVER\Yogstation-hal9001\tools\build\cbt\process.js:88:23)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  code: 4294967295
}

**Comment by Bibby0110** [comment]
> 

Compile the TGUI

**Comment by Bibby0110** [comment]
Closing the PR to re-open with new title + description for visibility.

**Pull request closed without merging**
