### PR TITLE
Scripting code improvements

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

This makes the telecomms scripting code actually readable to anyone who contributes to the codebase by removing Goonstation-type coding standards and replacing it with our own.
I also removed some (read: some) single letter vars, and just generally tried to make it as nice as possible to read.

I also removed ``sleep`` here because it was messing a bit with dmlang, though a previous PR already did this with ``operator``, I renamed that one too because ``oper`` is not much better.

# Why is this good for the game?

game?

# Testing

thanks to Scrambledeggs00 for the script, Amma for the help hunting down a very annoying bug, and Bup for teaching me how to run Scripts, I can confirm this works on my machine ™️ 

image

# Spriting

# Wiki Documentation

# Changelog

:cl:  
experimental: Refactored a lot of code related to scripting. Please report any bugs.
/:cl:

### CODE REVIEW

**Comment by Scrambledeggs00** [comment]
I could post my mega script here if you want to use it as a test. ~16,000 characters long with about everything on the wiki so it would probably catch any bugs that you didn't see.

**Comment by JohnFulpWillard** [comment]
You’d have to tell me how to do it in game too and sure

**Comment by Scrambledeggs00** [comment]
[megaScript.log](https://github.com/yogstation13/Yogstation/files/13120065/megaScript.log)

You upload scripts to tcomms with the "telecommunications traffic control console". You'll need to insert an ID with Tcomms Admin access into it, after which you'll see a list of all the servers. Select the server you want to compile to and then switch signal execution to always by pressing the blue words next to it. After that you'll want to press [edit code] which will bring up the server's screen. Copy/paste the code in and then press compile; if it works it'll say so at the bottom in blue. If not then it'll give an error and the line it is on if it is a syntax error.

For the megascript, some of the scripts require your sig.source to be "Promethium LXI" so you'll either want to make a character with that name or add something at the top that changes your sig.source to it if you want to test those parts put. Also ignore the Announcer Welcome Phrase part as that is something I add to the station announcer to let me modify its welcome messages.

**Comment by JohnFulpWillard** [comment]
> [megaScript.log](https://github.com/yogstation13/Yogstation/files/13120065/megaScript.log)
> 
> You upload scripts to tcomms with the "telecommunications traffic control console". You'll need to insert an ID with Tcomms Admin access into it, after which you'll see a list of all the servers. Select the server you want to compile to and then switch signal execution to always by pressing the blue words next to it. After that you'll want to press [edit code] which will bring up the server's screen. Copy/paste the code in and then press compile; if it works it'll say so at the bottom in blue. If not then it'll give an error and the line it is on if it is a syntax error.
> 
> For the megascript, some of the scripts require your sig.source to be "Promethium LXI" so you'll either want to make a character with that name or add something at the top that changes your sig.source to it if you want to test those parts put. Also ignore the Announcer Welcome Phrase part as that is something I add to the station announcer to let me modify its welcome messages.

It says it compiles but what is this supposed to do in-game so I know it actually works?

**Comment by Scrambledeggs00** [comment]
The mem() scripts use the mem function to store names and then apply their affects to them, such as the random title script adding a random title to their sig.source or the sans underhell script giving them funny filters. The translation scripts just translate stuff, with the prefix one having some options while the others only translate to GC. Sig.source script just adds time and the sig.job to sig.source. Facts and logic bot will randomly say one thing in its pick() list. S.A.B. just tells people about the scripts I want them to know about and how to use them. Announcer script modifies what the announcer says by picking from a list. The uwu and Morse translation scripts use 2 lists to translate messages. Signal Script uses a person's message to get a frequency and code and then sends a signal with them, though I've noticed it doesn't work all the time for some unknown reason. The rest of the scripts are more or less these but combined or just slightly changed.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
