### PR TITLE
Completely removes people wearing pet collars

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
gross

# Changelog
:cl:  
tweak: People can no longer wear pet collars
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
I recommend changing ishumanbasic() to ishuman() instead because removing it just makes nothing able to equip it

**Comment by SomeguyManperson** [comment]
perhaps make it not a clothing item, I believe pets handle collars completely seperately of them being equipped

**Comment by azzzertyy** [comment]
> I recommend changing ishumanbasic() to ishuman() instead because removing it just makes nothing able to equip it

thats the point, animals wear it fine still

**Comment by neeshacark** [comment]
honestly i dont see the point of this

degens are still going to be degen, removing the ability to wear a collar isnt going to change it.

**Comment by azzzertyy** [comment]
> honestly i dont see the point of this
> 
> degens are still going to be degen, removing the ability to wear a collar isnt going to change it.

removing capabilities of being a degenerate is going to attract less degenerates

**Comment by ToasterBiome** [comment]
don't like this precedent of astroturfing the entire game cause furries cant keep it in their pants

**Pull request closed without merging**
