### PR TITLE
Nitroglycerin no longer explodes inside of bodies

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Nitroglycerin will no longer explode when inside a body.

# Wiki Documentation

Might be worth mentioning on the guide to chemistry.

# Changelog

:cl:  
tweak: nitroglycerin no longer explodes inside of bodies
/:cl:

### CODE REVIEW

**Comment by milk-is-cool** [comment]
why

**Comment by iamthesilly** [comment]
> why

because being able to instantly kill people with no counter is bad? this is already the case with meth explosions for the same reason

**Comment by wonderinghost** [comment]
its steady progress to stop ark's nettles

**Comment by milk-is-cool** [comment]
> > why
> 
> because being able to instantly kill people with no counter is bad? this is already the case with meth explosions for the same reason

the problem i have with it is that it still doesnt solve that issue, it was still a one shot kill without the nitro and still will be after this. its too indirect to fix the one shot kill problem because there are still many other ways of doing it. the real problem is with the method of reagent transfer. just like with chem and removing the syringe gun, removing the ability to inject chems into people at all is what would be the real solution. its not the solution people will want but its not like everyone was happy about the syringe gun being removed either.

**Comment by iamthesilly** [comment]
> the problem i have with it is that it still doesnt solve that issue, it was still a one shot kill without the nitro and still will be after this. its too indirect to fix the one shot kill problem because there are still many other ways of doing it. the real problem is with the method of reagent transfer. just like with chem and removing the syringe gun, removing the ability to inject chems into people at all is what would be the real solution. its not the solution people will want but its not like everyone was happy about the syringe gun being removed either.

we can do more than one thing

**Comment by milk-is-cool** [comment]
> > the problem i have with it is that it still doesnt solve that issue, it was still a one shot kill without the nitro and still will be after this. its too indirect to fix the one shot kill problem because there are still many other ways of doing it. the real problem is with the method of reagent transfer. just like with chem and removing the syringe gun, removing the ability to inject chems into people at all is what would be the real solution. its not the solution people will want but its not like everyone was happy about the syringe gun being removed either.
> 
> we can do more than one thing

i am also bias towards chem so i am just generally against nerfs. for chemistry this also prevents things like monkey bombs which i feel deserve to be possible because of how much more work you need to put into those. also black powder still reacts in the body so that is still an alternative to do the same thing, just not near as powerful. 

in short: i dont like it because its also an indirect chemistry nerf on something that is already very difficult to obtain.

**Comment by wonderinghost** [comment]
well what about botany though

**Comment by milk-is-cool** [comment]
> well what about botany though

like i said before its not the chems that are the issue, its the method of reagent transfer. aka the hypodermic needles trait.

**Comment by wonderinghost** [comment]
> > well what about botany though
> 
> like i said before its not the chems that are the issue, its the method of reagent transfer. aka the hypodermic needles trait.

hypodermic needles is too powerful. increasing potency in a plant just makes it have more chems in it and upon getting hit once you would be in crit while also burning to death by sulfuric acid.

**Comment by milk-is-cool** [comment]
> > > well what about botany though
> > 
> > 
> > like i said before its not the chems that are the issue, its the method of reagent transfer. aka the hypodermic needles trait.
> 
> hypodermic needles is too powerful. increasing potency in a plant just makes it have more chems in it and upon getting hit once you would be in crit while also burning to death by sulfuric acid.

yes and thats just one example of many which is why the hypodermic needles trait is the problem and not nitro

**Comment by wonderinghost** [comment]
ide be down if the traits got debuffs. like hypodermic needles having a regent leak or the chances of them injecting while thrown is far less

**Comment by wonderinghost** [comment]
however the problem is that botany can just mass produce these. And there isnt a good way of destroying them without a conveyor that warps them to lavaland into a pool of lava

**Comment by milk-is-cool** [comment]
> however the problem is that botany can just mass produce these. And there isnt a good way of destroying them without a conveyor that warps them to lavaland into a pool of lava

just throwing a death nettle on a stack of plants will cover them all in acid and burn them into goo

**Comment by wonderinghost** [comment]
> > however the problem is that botany can just mass produce these. And there isnt a good way of destroying them without a conveyor that warps them to lavaland into a pool of lava
> 
> just throwing a death nettle on a stack of plants will cover them all in acid and burn them into goo

yeah but then there is also the plant and the seeds that you also have to destroy. and if cargo isnt brain dead and doesnt activate their conveyers then botany can just take the trash and start the cycle anew

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
