### PR TITLE
[MDB IGNORE] [IDB IGNORE] Replaces Space Station 13 with Yogstation 13

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
Too many changes to describe, you need to play the game to experience it

# Why is this good for the game?
it came to me in a dream

# Testing
> image

also see below

# Changelog
:cl:
tweak: Replaced Space Station 13 with Yogstation 13
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
What’s the point of this?

**Comment by AMyriad** [comment]
> What’s the point of this?

So in all seriousness this changes the name of the walls we use to overlay splash screens onto, i.e. the first thing people see when they connect to the server. Right clicking/examining these walls from the menu would show the walls are named "Space Station 13"

This change is minor as all hell, but I thought why not. Makes it less generic, as this do be in fact Yogstation 13 we're seeing.
image

**Comment by Moltijoe** [comment]
> > What’s the point of this?
> 
> So in all seriousness this changes the name of the walls we use to overlay splash screens onto, i.e. the first thing people see when they connect to the server. Right clicking/examining these walls from the menu would show the walls are named "Space Station 13"
> 
> This change is minor as all hell, but I thought why not. Makes it less generic, as this do be in fact Yogstation 13 we're seeing.

pretty sure you only see this when adminned

**Comment by AMyriad** [comment]
> pretty sure you only see this when adminned

image

**Review by Moltijoe — APPROVED** [review]
Nuh uh

**Pull request merged**
