### PR TITLE
Adds Katanas to the Uplink, 10 TC

### PR DESCRIPTION
**Pull request by Altoids1**
Supernoodles paid me to do this.

Has 33% more force than an esword, but it's also a lot harder to hide. Real degenerate, real weebish, real deadly.

#### Changelog
:cl:  Altoids
rscadd: Katanas are now available on the Uplink, for 10 TC.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
:(

**Comment by HomocidlePancakes** [comment]
Dakimakuras when?

**Comment by Lostlarry** [comment]
but its not loud AF to activate

**Comment by Codeatmos** [comment]
If it doesn`t have a sudoku suicide or a high delimb chance is a bit sad

**Pull request merged**
