### PR TITLE
[DNM] "Revert "Revert "[MIRROR] Rework of admin rank loading to support punctuation""

### PR DESCRIPTION
**Pull request by ThatLing**
Reverts yogstation13/Yogstation-TG#4054

DONT MERGE
NOT READY

### CODE REVIEW

**Comment by Amelia0010** [comment]
@ThatLing

**Comment by Amelia0010** [comment]
ples

**Comment by Altoids1** [comment]
🤔

**Comment by Altoids1** [comment]
@ThatLing ?

**Comment by ThatLing** [comment]
hi

**Comment by Altoids1** [comment]
I ded

**Comment by Amelia0010** [comment]
pls

**Pull request closed without merging**
