### PR TITLE
Darker in-game UI.

### PR DESCRIPTION
**Pull request by TheGoobers**
# Document the changes in your pull request

# Why is this good for the game?

# Testing

# Spriting

# Changelog

:cl:Osbidian_inGame_UI 
imageadd: screen_obsidian.dmi with new, darker sprites based on the midnight in game 
tweak: hud.dm so the new theme will be selectable in game preferences.
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Definitely not, Obsidian is good to be added but Midnight should still be available (and default)

**Comment by TheGoobers** [comment]
> Definitely not, Obsidian is good to be added but Midnight should still be available (and default)

Midnight is still available and still default. Is it not?

**Comment by ToasterBiome** [comment]
> > Definitely not, Obsidian is good to be added but Midnight should still be available (and default)
> 
> Midnight is still available and still default. Is it not?

no, it’s fixed in the other pr though

**Comment by ToasterBiome** [comment]
Closing in favor of https://github.com/yogstation13/Yogstation/pull/20821

**Pull request closed without merging**
