### PR TITLE
Adds balloon alert preference and balloon_or_message proc

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Adds a preference to disable balloon alerts, and a proc that will send a balloon alert or a chat message depending on user's preference toggle. 

# Spriting
No

# Wiki Documentation

Not needed

# Changelog

:cl: SuperSlayer
rscadd: Added disable/enable balloon alerts preference
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
I don't believe this should be a toggle. Keep it on for everyone and tweak it.

In the future most actions should be converted to balloon alerts which could get us close to removing the chat window itself

**Comment by ghost** [comment]
> I don't believe this should be a toggle. Keep it on for everyone and tweak it.

Why not?

> In the future most actions should be converted to balloon alerts which could get us close to removing the chat window itself

I agree with this, and I will make a PR that will convert some things to them

**Comment by Bibby0110** [comment]
> > I don't believe this should be a toggle. Keep it on for everyone and tweak it.
> 
> Why not?

I'm guessing this is a classic case of "change is bad." Let it stay for a while and grow on people. Address any complaints (too large, too small, stays too long etc) They're better game design and we should strive to replace most smaller pieces of textual information with these

**Comment by ghost** [comment]
Ok

**Comment by Cartlord** [comment]
I don't think anything TheGamerdk said holds water, frankly, and I still think this should be a toggle due to balloon alerts not being readable for than two seconds later (which chat messages can) and not showing up instantly (which chat messages do).

**Comment by SomeguyManperson** [comment]
> I don't think anything TheGamerdk said holds water, frankly, and I still think this should be a toggle due to balloon alerts not being readable for than two seconds later (which chat messages can) and not showing up instantly (which chat messages do).

basically this, balloon alerts show up slow and tend to overlap, and are extremely temporary. One of the main things they cause problems with is beaker transfer unit switching where the lack of immediate feedback, lack of a permanent record and the fade-in all combine to make it much more difficult to tell what the current transfer amount is.

However pref toggles for mechanical stuff like this are dumb and the issue should be addressed in some way rather than allowing people to ignore it.

**Comment by Cartlord** [comment]
honestly the only solutions i can think of are "make balloon alerts come _alongside_ chat messages" and "remove balloon alerts"

**Comment by adamsong** [comment]
I agree with the idea that the preference is bad. Don't take bad design, and say "oh, well, its a preference so it doesn't matter, anyone who doesn't like it will turn it off." Tweak it to improve it or remove it entirely.

**Comment by neeshacark** [comment]
this should be a preference for one reason; its a fucking preference

i dont want text that i dont need flashing in my face every time i do anything when i can look slightly to the right and see it there.  this is the same reason i dont use runechat, i don't like it, i don't PREFER it over not having it.  you might PREFER having runechat and this on, but for the love of god do not force it on everyone because not everybody wants it

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
