### PR TITLE
Adds RP

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Found the reason we have not moved to RP Yet.

### Why is this good for the game?

R0l3Pl4y

#### Changelog

:cl:  
rscadd: RP
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
haha 420

**Comment by bowlofcereal** [comment]
Well boys we did it, validhunting and powergaming is no more, we RP now

**Comment by Darkstick** [comment]
This is stupid enough that it might just work. Remember how drastically different the server became because we had "new player friendly" on the server name?

**Comment by fluffe9911** [comment]
yeah unironically this may actually work or atleast help quite a bit

**Pull request merged**
