### PR TITLE
Revert "Moving will no longer interrupt breaking out of cuffs"

### PR DESCRIPTION
**Pull request by AsV9**
Reverts yogstation13/Yogstation#7002

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Yog playerbase is too unrobust to click someone every 60 seconds. Sad.

**Comment by Hopekz** [comment]
How about just making it to where you can't break out of cuffs when held?

**Comment by HomocidlePancakes** [comment]
>How about just making it to where you can't break out of cuffs when held?

Look, it’s already ridiculously trivial to keep someone handcuffed. I don’t even know what to say when people want to make it even easier.

**Comment by boodaliboo** [comment]
The original pr was really good

**Comment by boodaliboo** [comment]
The original pr was really good

**Comment by AsV9** [comment]
https://forums.yogstation.net/index.php?threads/vote-unmerge-7002.20112/

**Comment by alexkar598** [comment]
"Unmerge" lol

**Comment by ghost** [comment]
Jesus christ I wouldn't think yogs would be this fucking braindead but here we are

**Pull request merged**
