### PR TITLE
New Traitor Item: Low-Orbit Ion Cannon Remote

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Port of vgstation-coders/vgstation13/pull/27503.

A new traitor item called the "low-orbit ion cannon remote" which can be used every 20 minutes to generate an ion storm.
Costs 5 TCs. Cannot be purchased by Nuclear Operatives or Clown Operatives.
Can only be purchased once per person.

It can only be used while on station; you cannot be off the z-level or be in space.
Reveals the general location of the device when used to all communication consoles.

What it looks like (these are not new sprites, just unused/barely used ones that are getting use now):
image

Different ion storm message:
image

General location printed at all comms consoles:
image

# Wiki Documentation
New traitor item called "low-orbit ion cannon remote". 5 TCs. Triggers the ion storm event. Usable every 20 minutes. Generates a different announcement noting it is abnormal. Prints a command report at all comms console that says the location's room name.
# Changelog
:cl:  
rscadd: A new traitor item called the low-orbit ion cannon remote. Capable of generating an ion storm every 20 minutes, but will reveal your location on all communication consoles.
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
reminds me of FTL

**Comment by iloveloopers** [comment]
would this be considered sabotage or grand sabotage if you use it and get caught by sec?

**Comment by Runian** [comment]
> would this be considered sabotage or grand sabotage if you use it and get caught by sec?

If the ion storm changed the AI's laws to the point where AI can/is "seriously threatening [the] crew or station", I think that the AI's actions would be effectively yours under space law (and thus considered grand sabotage). But if the ion storm generated a harmless law, it would just be sabotage.

**Comment by azzzertyy** [comment]
not me buying 4 of these and using them every 20 minutes

**Comment by Runian** [comment]
> not me buying 4 of these and using them every 20 minutes

Forgot to mention it's limited stock to 1.

**Comment by solwashere** [comment]
I think Surface to Satellite Ion Cannon Designator (surface to satellite = lavaland surface to orbital body) may be a better name, although that's just a minor nitpick of mine

**Review by cuackles — APPROVED** [review]

**Comment by pyronie** [comment]
> I think Surface to Satellite Ion Cannon Designator (surface to satellite = lavaland surface to orbital body) may be a better name, although that's just a minor nitpick of mine

the name is a reference to a script kiddie ddos tool

**Review by MajManatee — APPROVED** [review]
seems ok

**Comment by azzzertyy** [comment]
why didnt balance council vote on this

**Pull request merged**
