### PR TITLE
Saphics gaskmasks are in suitstorages in atmos now and ce locker

### PR DESCRIPTION
**Pull request by Ethan4303**
# Document the changes in your pull request

put the new atmos gas mask from saphic in the atmos suitstorages instead of those nasty cringe icky yucky plebian normie gasmasks also in ce lockers

# Spriting

# Wiki Documentation

something something gasmasks are atmos version now :)

# Changelog

:cl:  
rscadd: adds atmos gasmasks to the suitstorages and ce lockers
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
This is not a mapping change

**Comment by Ethan4303** [comment]
> This is not a mapping change

im a retard B)

**Comment by azzzertyy** [comment]
can you add them to the engidrobe?

**Comment by Ethan4303** [comment]
> can you add them to the engidrobe?

ask saphic, also its literally an ATMOS gas mask and theres pairs in the lockers and if this is merged, the atmo suit storages, I vote no >:)

**Comment by Ethan4303** [comment]
added to CE lockers too on request from sapphic

**Review by ynot01 — APPROVED** [review]

**Pull request merged**
