### PR TITLE
Surrender text clarity revive

### PR DESCRIPTION
**Pull request by Hopekz**
### Intent of your Pull Request

Revives #6988 
I fixed the line endings which killed the original PR and also replaced the span with a much easier to see type even mid-combat per Nich's original point in #6988. 

Dark's original edit:
----
image

This PR:
-----
image

-----------------------------

CURRENT:: EDIT per Xoxeyos's suggestion. 
-----

Surrender text now has its own custom span to make it very much unique and not take up the whole screen. I personally like this edit.

image

EDIT 2:: I STOLE A ANIMATED SPAN FROM Alex thank you! 
----
J7YLA0J

#### Changelog

:cl:  Hopek
tweak: Surrender emote is now much easier to see. Even mid-combat
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
I'd support trying a color other than red, red is usually used for aggressive/attacks.

**Comment by Xoxeyos** [comment]
I don't see why we need this, as I hardly see anyone use it, and I believe it is much too big of a font, perhaps you can try cutting it down by half. And perhaps a color change, like blue. I will change my vote if I like where it's going.

**Comment by MegaEmpirical** [comment]
I think the font should be big and obvious. And he's making it because it's hardly used and this makes it more attractive/viable.

and because something is hardly used is good reason to improve it, not ignore it. I didn't even know it was a thing before. Plus, you could just not use it if you don't like it as it has no effect on you if you don't.

**Comment by Hopekz** [comment]
> I don't see why we need this, as I hardly see anyone use it, and I believe it is much too big of a font, perhaps you can try cutting it down by half. And perhaps a color change, like blue. I will change my vote if I like where it's going.

**Xoxeyos,**
Made an edit per your suggestion. Its still pretty easy to read (if not more). Thank you for the feedback!

**People that care let me know if this new edit is more preferred by upbwoinking and down ogga'ing this comment**

image

**Comment by MegaEmpirical** [comment]
How does it look in dark mode?

**Comment by Hopekz** [comment]
J7YLA0J
This PR just got 10x cooler with @alexkar598  's span text

Here is how it looks now 
-----

**Comment by MegaEmpirical** [comment]
I guess that works in light and dark mode.

**Comment by Darkstick** [comment]
oh shit, this is a lot better than I could have done it, it's great

**Pull request merged**
