### PR TITLE
chaplain holyparasites don't stop mulligan

### PR DESCRIPTION
**Pull request by SomeguyManperson**
this POSSIBLY delays mulligans or round end when on antagonist death stuff triggers

:cl:  
bugfix: holyparas probably don't prevent round end on antagonist death/mulligan
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Mind adding a way to pull up holoparasites then? I don't care if they turn a round into extended, I care about bring to identify them.

**Comment by SomeguyManperson** [comment]
this would only remove the chaplain's holyparasite, other holoparasites aren't effected

**Comment by MegaEmpirical** [comment]
Whilst that's good, I was referring to all (holy included).

**Comment by Hopekz** [comment]
I don't like this change because right now there is no easy way to pull up all holo-paras (yes including the holy one).
Until that feature exists not adding them in is just kind of a "fuck you" to admins.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
Set holoparasite antag datums' `prevent_roundtype_conversion` to `FALSE` instead

**Review by Amelia0010 — APPROVED** [review]

**Comment by alexkar598** [comment]
Lyis and hopek points have been fixed so I will disregard their opinions

**Pull request merged**
