### PR TITLE
Adds a new totally innocent Rabbit Costume for Easter Sprites made by Frans_Feiffer

### PR DESCRIPTION
**Pull request by fluffe9911**
# Document the changes in your pull request
Adds the rabbit costume as seen below guaranteed to increase fun levels by atleast 10% sprites made by Frans_Feiffer from the CM dev team using his sprites with permission
Untitled

# Changelog
:cl:  
rscadd: Adds a new rabbit costume to the clown autodrobe sprites made by Frans_Feiffer!
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Big chungus

**Review by adamsong — APPROVED** [review]

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Comment by nesisknesis** [comment]
I think we would be better off without someone parading around as big chungus.

**Comment by ghost** [comment]
Nooooooo big chungus

**Comment by fluffe9911** [comment]
> I think we would be better off without someone parading around as big chungus.

1984

**Pull request closed without merging**
