### PR TITLE
Bedsheet Bliss

### PR DESCRIPTION
**Pull request by Firewolf34**
...and also some bugfixes.

### Virology Blankets

This commit adds the new Virology Blanket, inspired by ticket #4314. This is a type of medical bedsheet that has a green cross instead of a blue one:
new-blanket
I have replaced all of the bedsheets for Virology in all of the 4 maps with the new Virology Blanket. 
viro-blankets

### Prisoner's Blankets

The Virology Blanket was a good start but it gave me a bad case of bedsheet fever and I knew I wasn't ready to stop editing anything and everything blanket-related completely cold turkey. My blanket-fueled furvour quickly extended to the brig where I saw those damned white things sitting around on all the brig beds. We have like 15 types of blanket and they choose white? How droll.
euphoria
Now there is a custom bedsheet which matches the uniform for the prisoners. It's also grungey and dirty and covered with nasty stains, probably from the Clown. I rolled them out to the Brigs in all the 4 Yogs stations:
prison
Now when greytiding Assistants run out into the hall with stolen prison blankets around their neck, they'll be easier to spot and take down to get those sweet, sweet bedsheets back. 

### Assorted Bugfixes

I fixed two bugs and made a small change. 

The first bug is issue #4332. I added a wood floor tile underneath the Lawyer door because it is missing on TG.

The second bug is that there was a syndi-cake trash item clipping into a wall in the Syndicate Lavaland Base. I moved it into the maint tunnel a few tiles over.

The improvement is that I added a defib to the Syndicate Lavaland Base. It didn't have one, for some reason. So if someone died, you were S.O.L.. No more problem. Now the syndicates can revive each other and continue to cause trouble over the intercom system.

defib trash

#### Fixed Tickets

Fixes issue #4314.
Fixes issue #4332.

#### Changelog

:cl: Firewolf34
rscadd: Adds 2 new types of bedsheet: Prisoner's and Virology Blankets.
bugfix: Added a floor tile underneath the Lawyer's Office airlock.
tweak: Added a defib to Syndicate Lavaland Base Medical.
tweak: Changed Brig/Perma Cell bedsheets to Prisoner's Blankets in all maps.
imageadd: Added an icon for the Virology Blanket.
imageadd: Added an icon for the Prisoner's Blanket.
/:cl:

### CODE REVIEW

**Comment by Firewolf34** [comment]
If you guys like the idea of Orange Bedsheets in the Brig Cells, lmk and I'll add them to the rest of the maps as well as Box.

I think they highlight the fact that the user is a prisoner, given prisoners often wear them. The colored bedsheets are under-utilized imho. There is already an orange bedsheet in the icons DMI so I didn't  make a new one for this, but I suppose a "Prisoners Blanket" could be made too.

I didn't want to put the effort in, until I knew everyone was okay with the orange bedsheets change.

**Comment by Firewolf34** [comment]
Also if anyone has any good bedsheet-related ideas, I would be happy to work on them here. 

**Note to Maintainer:** I edited the Syndicate Lavaland Base mapfile directly. There wasn't one in the Yogstation folder so I wasn't sure how to modularize it. Let me know if this needs to be changed.

**Review by monster860 — CHANGES_REQUESTED** [review]
image
WTF is this random ass bedsheet doing embedded in the wall?

**Comment by Firewolf34** [comment]
> image
> WTF is this random ass bedsheet doing embedded in the wall?

OH NOES! I don't know how that happens. It's happened to me when I was working on the viro area too. I'll take care of it. I'm still getting used to the map editor thing, I'm more of a programmer and this map editor is hella clunky lol

I must be doing something wrong, somehow. Now I'm worried they're ending up in other areas of the map, too :0

Edit: FIXED. And I checked all the other maps, I don't think there were any more of those mistakes.

**Review by monster860 — CHANGES_REQUESTED** [review]
To modularize the lavaland ruin, copy-paste the map into _maps/yogstation/whatever and then change the path in the ruin datum so it points to the new map.

**Comment by Firewolf34** [comment]
Introducing... the **Prisoner's Blanket**!

I decided the orange blankets were a little weird, the color wasn't right, and I wanted it to be uniform across all the maps so I made a special blanket for the prisoners. I then rolled them out to all the four Yogs maps. They're in the brigs, and the perma cells now. Soon I'm going to see if I can get the bedsheet bin to provide custom bedsheet types.

**Comment by Firewolf34** [comment]
> To modularize the lavaland ruin, copy-paste the map into _maps/yogstation/whatever and then change the path in the ruin datum so it points to the new map.

Thanks @monster860, I've performed the changes you requested. I returned the lavaland ruins file I had changed back to the way it was on my master branch. Then I added a line changing the datum to refer to the Yogstation file prefix.

However, this has me wondering, does this mean that every single upstream update to the Lavaland Syndicate Base TG makes, needs to now be manually hand-copied over to our Yogstation modularized version, whenever they make a change? Just because of these tiny little fixes? Seems like a lot of work for a bugfix. Or do you guys automate it somehow?

**Comment by monster860** [comment]
thats how it works for the main map files too

**Review by monster860 — CHANGES_REQUESTED** [review]
you accidentally removed a corner here:

image

If you can fix that one minor issue then this should be good.

**Review by monster860 — APPROVED** [review]

**Comment by Time-Green** [comment]
you didnt add cape sprites for the sheets

**Comment by Firewolf34** [comment]
> you didnt add cape sprites for the sheets

Yeah, I realized that now - it's fixed in another PR.

**Pull request merged**
