### PR TITLE
using a fork on the ark creates spaghetti

### PR DESCRIPTION
**Pull request by SomeguyManperson**
clock cultists don't get any food if they didn't empty all the vending machines or something so this lets them get food

:cl:  
rscadd: Hitting the ark of the clockwork justicar with a fork will produce spaghetti
rscadd: the city of cogs now has forks to harvest spaghetti with
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
what

**Comment by SomeguyManperson** [comment]
what

**Comment by Tipy1802** [comment]
what

**Comment by Jarod1200** [comment]
We will finally free ratvar from the spaghetti

**Review by patpol4 — APPROVED** [review]
Map part of this looks ok to me, its just 5 forks.

**Comment by JamieD1** [comment]
Stupid but sure.

**Review by JamieD1 — APPROVED** [review]

**Comment by SomeguyManperson** [comment]
it's not stupid it's vitally important for the integrity of the clock cult lore

**Comment by deathslayer2481** [comment]
Yeah this is important

**Pull request merged**
