### PR TITLE
AAAAAAAA!! A G-G-G-G-GHOST!! - more ghost sprites

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
image
image
image
Adds 3 new ghost types because i want more ghost types

# Why is this good for the game?
more = better because i hate seeing 300 of the same ghost they are ugly

# Spriting

see above I guess?

# Changelog

:cl:  
rscadd: Added 3 new ghost types  
/:cl:

### CODE REVIEW

**Comment by LaOubliette** [comment]
SNNNNNNNAAAAAAAAAAAAAAAAAAKKKKKKKKKKEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by cuackles** [comment]
Very impartial to the crab but God the snake looks good dead

**Comment by MajManatee** [comment]
is that your official review mr art team?

**Comment by cuackles** [comment]
> is that your official review mr art team?

no

**Review by cuackles — APPROVED** [review]
this one is

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
