### PR TITLE
Spaceland - BACK TO THE ASTEROID 2

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

asteroid. reminiscent of the old style, with a new mining base in the south.

WE ARE HERE TO MINE, MINE WE WILL

no special bosses (yet)
no ruins (yet)
requires spaceland minetype (might just make it randomly choose)

# Why is this good for the game?
I want a chance for slower paced mining where it isn't just hyper-optimized boss killing. New areas to explore + RP in.

I realized if I kept waiting for motivation to bring it feature-complete to Lavaland that I would be here forever. Better to have something in the game that can be added on my others than keeping it sealed away.

# Testing

# Wiki Documentation

Spaceland added to yogstation

# Changelog

:cl:  
mapping: Adds spaceland (the old asteroid)
/:cl:

### CODE REVIEW

**Review by neeshacark — APPROVED** [review]
I hate reviewing biome's prs because I don't know if I'm not finding issues because im blind and or missing them or if it's just because he hasn't made any due to being so based.

That being said the copy-pasted labor camp from lavaland has SHIT THICK decals and I kindly ask that you fix them to be the standard thin ones we use now :)  (there is also a extra corner decal under the biogen incase you somehow miss it when you redo the decals there)

Besides that I haven't been able to locate any other errors but whether that's because im shit at my job or because biome is good at his idk

Code needs review it's a bit out of my realm of knowledge (its not DATUMS)

**Review by neeshacark — CHANGES_REQUESTED** [review]
i meant to request changes see my last message

**Comment by Yarinoi** [comment]
holy big

**Review by MajManatee — CHANGES_REQUESTED** [review]
Engerland :(

**Review by MajManatee — APPROVED** [review]
it seems fine ngl but I cant map so

**Review by neeshacark — CHANGES_REQUESTED** [review]
ITS STILL THEREE YOU FUCKING FUCK
image_2023-09-26_122208332

**Review by neeshacark — APPROVED** [review]
i am going to shit in your pants biome

seems fine

**Review by neeshacark — CHANGES_REQUESTED** [review]
local HD has the audacity to complain to me that i missed this and then didnt fix it himself SMH
image_2023-09-27_113826529

**Comment by MajManatee** [comment]
We will never return to asteroid

**Review by neeshacark — APPROVED** [review]
biome didnt ping me i didnt know massive L

**Comment by MajManatee** [comment]
So is this DONE done or are we TMing this for a bit? @ToasterBiome

**Comment by ToasterBiome** [comment]
Back to cooking

**Pull request closed without merging**
