### PR TITLE
New Lavaland test merge

### PR DESCRIPTION
**Pull request by JamieD1**

### CODE REVIEW

**Comment by patpol4** [comment]
any descrpition at all please?

**Comment by redmoogle** [comment]
Lavaland went from 250,250 to 500,500 @wejengin2

**Comment by redmoogle** [comment]
he changed lavaland size(which is normally 250x250) all the way upto 500x500, making it 4x as big and also quite a bit more laggy @wejengin2 @MrHorizons

**Comment by JamieD1** [comment]
THIS SHALL BE BACK!

**Pull request closed without merging**
