### PR TITLE
gives the bridge, ai upload, and tcomms reinforced plasma windows.

### PR DESCRIPTION
**Pull request by UselessTheremin**
in my opinion the windows are underused, and with the rwindow buff probably being changed, i thought that to add more security the bridge should have the strongest windows nanotrasen could pay for. they are nanotrasens finest on their new fancy research station, are they not?
🆑
tweak: rwindows on bridge and such
/🆑

### CODE REVIEW

**Comment by jcatjmeow** [comment]
As the window buffer- the rplasma windows are fuckin stronk as fuck bro. You basically have to have a gun or decon them.


Just keep that in mind.

**Comment by patpol4** [comment]
1. they look absolutely atrocious
2. i dont think this level of security is needed, overfortifying everything roundstart is bad
3. i would wait for the rwindow change first to see what we go with in the end

**Comment by ghost** [comment]
tcomms and ai upload at most

**Comment by patpol4** [comment]
Closing due to above and negative votes

**Pull request closed without merging**
