### PR TITLE
Prevents venus human traps from breaking their own space vines

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
do i really need to explain?
they need to defend the vine, why can they hurt it

:cl:  
tweak: Prevents venus human traps from breaking their own space vines
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
admin ruling in the past has been venus traps can selectively prune vines to ensure beneficial mutations prosper i.e removing shitty normal vines so flowering can grow 

ive never seen a venus trap abuse this ability to harm their team and if they did it's an admin issue 

this should remain possible imo

**Comment by Moltijoe** [comment]
> admin ruling in the past has been venus traps can selectively prune vines to ensure beneficial mutations prosper i.e removing shitty normal vines so flowering can grow
> 
> ive never seen a venus trap abuse this ability to harm their team and if they did it's an admin issue
> 
> this should remain possible imo

I was plaing venus human trap and it was annoying as hell when id accidentally break a vine with a misclick

**Comment by ShoziOffical** [comment]
Issue with the vine blocking firelock from being destroyed by venus, it has been annoying please fix that too make vine able to fry firelock open like they did to airlock

**Review by MajManatee — APPROVED** [review]
I have no issue but I do understand wanting to break it willingly, so I wont merge it

**Comment by Moltijoe** [comment]
> I have no issue but I do understand wanting to break it willingly, so I wont merge it

yeah, i think there's reason enough to allow them to break it still, so i'll just close this

**Pull request closed without merging**
