### PR TITLE
Fixes some stuff with the aux base construction expansion

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Fixes some minor errors I missed when making the original PR, mainly duplicate stuff. Untested, should work.

- Removed duplicate catwalks, lattice, and grills, around solars and the construction area
- Added an extra grill by the left solars to make it symmetrical
- Added some missing lattices under some of the grills
- Added a light inside of the construction storage

# Wiki Documentation

Image for aux base will need to be updated. 

# Changelog

:cl:   
tweak: tweaked and fixed some minor issues with the aux base construction area
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
If you briefly list all the small changes for me it will be much easier to review. No need to use many words, literally just summarise it in other way than "fixes things" so i know what to look at.

**Comment by nmajask** [comment]
> If you briefly list all the small changes for me it will be much easier to review. No need to use many words, literally just summarise it in other way than "fixes things" so i know what to look at.

Added it to the description, sorry about that.

**Review by patpol4 — APPROVED** [review]
Looks good to me, to be merged after #12422

**Review by patpol4 — CHANGES_REQUESTED** [review]
Genpop made a conflict, sorry

**Review by patpol4 — APPROVED** [review]
Good to go after checks go green.

**Pull request merged**
