### PR TITLE
Unopresses Mentors (adds mbwoink)

### PR DESCRIPTION
**Pull request by monster860**
### Intent of your Pull Request

Explain what the purpose of your PR is.
Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool.

Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged. This is much easier for everyone.

Edit the changelog at the bottom for changes that are noticeable by the players. Remove it if this isn't the case.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.
Include [admin] in the title if it's something admin related.
Include [s] in the title if you don't want it to be announced on discord and the server.

#### Changelog

:cl:  
add: Mentors can now mentor-PM people via right-click
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
But why?

**Comment by Codeatmos** [comment]
DUH!!!
Mentors are getting tools?
Why???
Mentors don't even need tools,they all metacomm with their m-helps anyway
Hold up,I'm setting up tcomms to all staff right now so we can get this council voted and vetoed, I'm shaking right now, giving mentors the tools to help players out who ask shit in OOC but don't know how to m-help?
I'm shitting and crying right now,I've run out of tendies and I've run out of patience for mentors,close pr Post-Haste!
<Unironic Time>
This is good,along with mentor menu updates and m-bwoink(which you could already do,just with a bit of finicky magic) I can't wait for m-point and I actually appreciate monster for taking time out to request a feature we have been waiting for a long time that helps us deal with OOC:WHY IS THERE A RED R ABOVE MY HEAD? or maybe a SM setup that a player is having trouble with.While there is the threat of mentor variation with what is bwoink and not bwoinkable such as a SM that would fail  perhaps considered nudging the round too much the same happens with mins and their own choices, but I have trust in our mentors not to fuck this up mostly since we have 0 mentor complaints and no official or unofficial reports of m-ghosting,thanks monster I will be sending you the 50$ of coding socks you asked for.

**Comment by Jarod1200** [comment]
Now we just need the ability to do !mwho in discord

**Comment by Hopekz** [comment]
> But why?

Main reason for this is that the current system of using discord to mhelp someone requires a ckey.

When observing; mentors seem to want to go out of their way to try to help people that are struggling.

Right now if someone is clearly struggling to do something they either have to get an admin to communicate something to him or do something weird like spawning spawning them in as a helpful ERT to give them a mini tutorial on how to do something (for example on how to sett up the engine etc)

We as staff have very convenient tools to help (PM bwoink or Subtle message) but assisting us by delegating these types of inquiries to mentors is what they are for.
Having this tool be in the right click menu will only stop them having to go through a backwards method, asking for a ckey etc. Right now some mentors even suggested going through replays to try to get a ckey just to mhelp someone which is stupid and out of the way.

I see no reason why a mentor should not be able to offer someone assistance when appropriate by right clicking similar to how staff can message players.

**Review by Hopekz — APPROVED** [review]
>But why?

Main reason for this is that the current system of using discord to mhelp someone requires a ckey.

When observing; mentors seem to want to go out of their way to try to help people that are struggling.

Right now if someone is clearly struggling to do something they either have to get an admin to communicate something to him or do something weird like spawning spawning them in as a helpful ERT to give them a mini tutorial on how to do something (for example on how to sett up the engine etc)

We as staff have very convenient tools to help (PM bwoink, Subtle message, narrate , osay (to make objects talk) etc ) but assisting us by delegating these types of inquiries to mentors is what they are for.

Having this tool be in the right click menu will only stop them having to go through a backwards method such as asking admins for a ckey etc. 

Right now some mentors even suggested going through replays to try to get a ckey just to mhelp someone which is too indirect and out of the way but they literally don't have other options.

I see no reason why a mentor should not be able to offer someone assistance when appropriate by right clicking similar to how staff can message players.

**Comment by ReddicusDragon** [comment]
BWOINK! The thing goes in the thing

**Comment by Hopekz** [comment]
merge please I need this too

**Comment by athena413** [comment]
but how will we oppress mentors now

good

**Comment by alexkar598** [comment]
Id really much have it as an ability only observers can use

**Pull request merged**
