### PR TITLE
deletes roundstart morphine (at least on box because i dont care about other maps)

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
i dont think it even needs explaining why #16994 is a horrible idea, and you know you've fucked up if i'm the voice of reason on the topic of game design

# Changelog

:cl:  
rscdel: roundstart morphine is gone
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
bibby missed the whole reasoning for this, but it's fair since it was one of my schizo rants in development public, basically molti wanted to **prevent new players from playing as ANY medical role** because one ban evader uses morphine spray to grief people. this is like carpet bombing a spider with the amount of overkill it was, and removing the morphine removes the grief tool

**Review by MajManatee — CHANGES_REQUESTED** [review]
Change on all maps

**Comment by TheRyeGuyWhoWillNowDie** [comment]
No

**Comment by Hopekz** [comment]
> No

I wouldn't either

**Pull request closed without merging**
