### PR TITLE
makes it no longer possible to break into test chamber before round end

### PR DESCRIPTION
**Pull request by boodaliboo**
all reinforced windows are now admin windows
#### Changelog

:cl:  
rscadd: Added reinforced windows 
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
bad, let them come to the test chamber and let admins smite them. its really funny

**Comment by boodaliboo** [comment]
> bad, let them come to the test chamber and let admins smite them. its really funny

no i need this for strategies

**Comment by GenericDM** [comment]
If somebody makes it to the test chamber they can fuck with round-ending items. I've seen this happen before when I summoned an ERT and looked away for a few minutes while they were gearing up.
I now spawn admin walls to block off the rest of Central Command from them, but this should work too.

**Comment by alao3alao3** [comment]
Wait wasn't CC on a z-level that's only appears during round ends (or due to admemery) and can't be reached during the round anyway?

**Comment by boodaliboo** [comment]
no

**Review by patpol4 — CHANGES_REQUESTED** [review]
Do these as well please
chrome_qqp4gVMTbI

**Comment by Reed0506** [comment]
this seems like a change along the same lines as the ones that specifically changed the area around the ERT spawn to be all admin windows and the admin wall barrier around the ferry. all i can see this doing is limiting the things you can do at roundend. for ERTs, just blocking their area by default would solve that issue, seeing as thats already been mostly done anyways.

**Comment by Darkstick** [comment]
I do enjoy escaping/breaking into the test room during round end to join up with friends or just go to the recovery shuttle. It would be a shame to loose that ability...

**Review by patpol4 — APPROVED** [review]
Darkstick has a good point, as it is right now this just changes the windows at the bottom of the test chamber and I'm fine with that.

**Pull request merged**
