### PR TITLE
Replaces slime love potions with slime empathy potions

### PR DESCRIPTION
**Pull request by ghost**
# Intent of your Pull Request

Love potion while being meant for RP was basically just used as a pseudo mindslave. This nerfs xenobio by changing it to an empathy potion that grants slime language and makes AI slimes not attack the drinker (player slimes still can of course). Love potion can be brought back but it'd need some admin clarification. Love code is still intact since I think it gets used by obsessed and if not it can be reused for brain traumas.

#### Changelog

:cl:  
rscadd: Adds slime empathy potion, allowing you to understand slimes
rscdel: Removes love potion
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
eh i think personally that removing the mind slave is fine but i dont really like just granting them slime language kinda seems like a bit to little reward for it

**Comment by maxion12345** [comment]
how the fuck is granting a language that barely anyone fucking uses too big a reward

next time we're removing curator for having access to literally all languages

**Comment by ghost** [comment]
@boodaliboo yeah tbh, how about if I add slime friendliness to it?

**Comment by Tipy1802** [comment]
Love potions aren’t really a pseudo mindslave, just because you are in love with someone it doesn’t mean you will follow every single order they give you. Most sane people won’t kill someon because their girlfriend told them to. Yes there is the romantasied aspect of love driving someone to criminal acts, if someone wants to take their roleplay to that aspect more power to them but you are not forced to. The way I see it is that just because you are in love with someone it doesn’t mean you must follow every last of their orders but perhaps you may trust your crush more, play cover for them etc. 
 
This opens room for some very interesting scenarios. A detective finding the prints of his loved one on the murder weapons. He faces a very unique dilemma, does he trust his mind or his heart? What’s more important, his duty to be fair and just as a detective or his burning love?

**Comment by Marmio64** [comment]
> Love potions aren’t really a pseudo mindslave, just because you are in love with someone it doesn’t mean you will follow every single order they give you. Most sane people won’t kill someon because their girlfriend told them to. Yes there is the romantasied aspect of love driving someone to criminal acts, if someone wants to take their roleplay to that aspect more power to them but you are not forced to. The way I see it is that just because you are in love with someone it doesn’t mean you must follow every last of their orders but perhaps you may trust your crush more, play cover for them etc.
> 
> This opens room for some very interesting scenarios. A detective finding the prints of his loved one on the murder weapons. He faces a very unique dilemma, does he trust his mind or his heart? What’s more important, his duty to be fair and just as a detective or his burning love?

we dont allow RP here so im pretty sure the detective would just valid the loved one still

**Comment by Tipy1802** [comment]
> we dont allow RP here so im pretty sure the detective would just valid the loved one still 

We are supposed to be moving towards MRP, it doesn’t matter if we don’t have rp now we should be pushing changes that encourage rp and push back on changes that discourage rp

**Comment by boodaliboo** [comment]
> @boodaliboo yeah tbh, how about if I add slime friendliness to it?

yeah that seems like its fine and also kinda keeps with the theme of pink being friendship and love

**Comment by ghost** [comment]
> Love potions aren’t really a pseudo mindslave, just because you are in love with someone it doesn’t mean you will follow every single order they give you. Most sane people won’t kill someon because their girlfriend told them to. Yes there is the romantasied aspect of love driving someone to criminal acts, if someone wants to take their roleplay to that aspect more power to them but you are not forced to. The way I see it is that just because you are in love with someone it doesn’t mean you must follow every last of their orders but perhaps you may trust your crush more, play cover for them etc.
> 
> This opens room for some very interesting scenarios. A detective finding the prints of his loved one on the murder weapons. He faces a very unique dilemma, does he trust his mind or his heart? What’s more important, his duty to be fair and just as a detective or his burning love?

I have literally never seen a love potion used to roleplay and have only ever seen them used for powergaming. This game is played by virgin teenagers who have no idea how love works and find that being forced to roleplay falling in love with a bunch of pixels that forcefed them pheromone swill is repulsive and would instantly prefer the alternative explanation that they are now mindslaves with a light touch of RP. 

For the rest of the playerbase that is willing to RP and is actually capable of it, in how many instances of a love potion being made by a non-antag so they can find """love"""" through an extremely forceful and repulsive manner, versus a traitor going "haha mass producible free mindslave go BRRRRRR"?

As it stands this item simultaneously exists in 2 diametrically opposed areas, an RP-only item that takes far too much time and resources to make given what it does, or an extremely cheap mass-produced knockoff mindslave. That's just bad design either way, moreso that it somehow occupies both at once. Either get the admins to make rulings on what "love" in this context is, which is terrible, or replace it entirely.

**Comment by Tipy1802** [comment]
Love potions are not free you actually have to do a lot of xenobiology work which is harder than “use 7 tc” and once again you can easily roleplay your way out of being a mindslave, it’s the player’s fault for being stupid 

Xenobiology has been nerfed so hard that no one does it beside maybe Nerissa Ratclif, we don’t need more xenobio nerfs

**Comment by Georgeur** [comment]
This seems unnecessary. I know the general consensus is 'lets nerf xenobio is op volvo pls fix'. But this item would be outclassed by the slime mutation toxin, in virtually every way, in ease, and in its current implementation its power. They get the slime language, and theyre friendly with them. All you need for the slime mutation toxin is one single green slime core too, instead of a living adult tier 3 slime, mixed with 10 cores of a tier 2 slime on the other end of the mutation flowchart. Furthermore, moving away from a perspective of balance, this item is just effectively useless, and xenobio already has items that are useless, such as the slime speed potion (which was made to not work with anything, and then they kept the same description for it, in game and on the wiki, which I thought was a really scummy thing to do, but whatever).

**Comment by ghost** [comment]
>Love potions are not free

Spend 40 minutes getting the cores, then produce like 10 of them at once. 70TCs worth of crap should not be producible by xenobio. Furthermore it misses my primary argument about RP being that most greytide players _won't_ RP out of love potion, they'll just use it as an excuse to valid. And when they get bwoinked for it, you get into the mess of admins making rulings on the definition and actions of love. 

Furthermore, slime mutation toxin turns you into a filthy slime, this one lets you keep your humanity/race.

**Comment by ghost** [comment]
REEEE I HATE GIT

**Comment by ghost** [comment]
wtf it compiles on mine but not on Turdis?

**Comment by ghost** [comment]
BUT IT DOES??????

**Comment by Ludox235** [comment]
Why yes let's nerf a part of the game that already got gimped to shits. Good idea!

**Comment by Ratvar** [comment]
Xenobio has no redeeming qualities, Ludox, it has only powergaming shit to cut. Maybe one day someone will rework it in a way that is not -add more powergaming toys, splice some useless items that nobody makes as a cover-,crossbreeds, but for now timestop grenades, golems, antistuns, permaheals, changeling, wizard transformations are cut one by one. 
I remember how xenobio mains kept saying xenobio was nerfed to shit when xenoling was removed because they did nothing but xenoling, because they only get funny op validhunting powers and there is nothing else to job.

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
