### PR TITLE
Makes medkits actualy useful for medbay

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Adds items to medkits and nerfs medical sprays so that medbay actually has a reason to use them. Main changes are that brute/burn kits now have their respective medical sprays in them, medical sprays now hold half the reagents (this does take into account synthflesh sprays in vendors), brute kits now have salicyclic acid pills, oxygen kits now have two epipens and 4 syrignes of perfluorodecalin acid, and advanced health kits have been completely reworked and now store the same amount as surgical kits.

# Spriting
Brute
image

Burn
image

Oxy
image

Advanced
image

# Wiki Documentation

Need to have the kits updated in the medical supplies page.

# Changelog

:cl:  
tweak: brute/burn kits now have their respective medical sprays in them 
tweak: medical sprays now hold half the reagents (this does take into account synthflesh sprays in vendors)
tweak: brute kits now have salicyclic acid pills
tweak: oxygen kits now have two epipens and 4 syrignes of perfluorodecalin acid
tweak: advanced health kits have been completely reworked and now store the same amount as surgical kits  
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
Pog

**Review by KillerOrcaCora — APPROVED** [review]
6 pixel edits

**Comment by Notamaniac** [comment]
> medical sprays now hold half the reagents

What? Why? So now styptic/sulf sprays can heal a grand total of 30 damage +32.5 over time? Making them even less useful than a stack of sutures that can heal 150 in total? Was there someone seriously abusing sprays? Can't you just leave them out of the kits, or add a nerfed version and leave the ones in the medivendor alone?

**Comment by VaelophisNyx** [comment]
sprays just invalidated the existence of the medkits. Source: an MD Main

**Comment by Notamaniac** [comment]
> sprays just invalidated the existence of the medkits. Source: an MD Main

Am I missing something here? When does medical EVER use their medical kits? You're using up a finite supply of medicine, when you have sleepers and tend wounds surgery which dispense an infinite amount of healing. You could put medicated sutures and advanced meshes in them, and they still wouldn't see use because they're finite. And you're somehow telling me that 60 + 72.5 (overtime) of healing completely invalidates a medkit? When, again a stack of SUTURES in the BASIC WHITE MEDKIT heal 150 total points of damage? When the ONLY instance medkits should be used in medbay is when power is completely out?

Sure I mean I'd understand buffing the patches to 30/35 units. But this change does not make medkits useful in medbay. It makes sprays useless, sure. It means you should steal the white medkits instead of the other medkits when you tele into medbay storage as a wizard/ninja (but that's always been the case).

This PR doesn't fix the issue it claims to do (woop de doo, you get 5 more units of sulf/styptic per brute/burn kit), and is attempting to fix something that isn't even broken.

**Pull request closed without merging**
