### PR TITLE
Revert "Revert "Removes felinid language""

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#17856

Failed to follow guidelines

### CODE REVIEW

**Comment by JamieD1** [comment]
I've said my piece, please respect it.

**Comment by Bibby0110** [comment]
Rules my good sir

**Comment by JamieD1** [comment]
Im using my HD authority to override the guidelines for this situation.

**Comment by MajManatee** [comment]
1984

**Pull request closed without merging**
