### PR TITLE
Singularity Monitor, salvaged from MDonalds code

### PR DESCRIPTION
**Pull request by ghost**
This was originally intended for mdonalds but that project is on ice so I'm finishing this feature and PRing it.
### Intent of your Pull Request

Adds the singularity monitor, a great way to tell where the lord is at all times, and how hungry he is. 

#### Changelog

:cl:  
rscadd: Adds the singularity monitor
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I'll add the icons and sprites soon.

**Comment by ghost** [comment]
Oh yeah the color selector is some prototyped code I haven't updated yet, I'll fix that tomorrow maybe I dunno.

**Comment by UselessTheremin** [comment]
It better be ominous.

**Comment by ghost** [comment]
I have no energy to work on PRs at the moment. Will redo this sometime in the future.

**Pull request closed without merging**
