### PR TITLE
Revert "Removes Gamer's unfunny memes"

### PR DESCRIPTION
**Pull request by boodaliboo**
Reverts yogstation13/Yogstation#9528
it isnt a bug fix and admin commands dont need to be sanitized if theirs a issue with them abusing it they can just get striked

### CODE REVIEW

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
The status panel needs to remain clean of memes, along with the title screen, its the first thing people see. What happens in announce verb doesn't matter but the status panel does as its associated with yogstation as a whole, not gamer himself

**Comment by alexkar598** [comment]
Wrong button but im still probably going to close this

**Comment by Bibby0110** [comment]
no you're not

**Comment by Reed0506** [comment]
alexkar if you close this im going to tell xantam you suck

**Comment by JamieD1** [comment]
I was against this but its the map name, dont be cocking with that gamer.

**Pull request closed without merging**
