### PR TITLE
Minor objectives

### PR DESCRIPTION
**Pull request by Amelia0010**
Adds minor objectives. Small flavour objectives that realistically won't be that hard to complete (like "Kill Ian" or "Delete your security records"). Any traitor without Hijack or Die a Glorious Death will have a 50% chance to receive a minor objective as well,

Please give me more suggestions for minor objectives, 2 ain't enough.

:cl:
tweak: traitors can now receive minor flavour objectives that pose no real challenge but should add a bit of flavour
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
Ironic I was thinking about this when I woke up

**Comment by MonsWTF** [comment]
"Leave a photocopy of your ass in the Bridge."

"Desecrate the Chapel with an icon of cult influence." (Get a Ratvar/Nar'Sie plushie in there once)

"Put 4 vending machines inside of X Area" (X = Arrivals shuttle, Escape Hallway, Chapel, Dorms)

**Comment by Tipy1802** [comment]
I like this! Other minor objectives I can come up with are: " Steal x ammount of money'' ''Get x ammount of people addicted to drug y'' ''Give cigaretts/alcohol to minor x''  ''Frame x of crime y'' ''swap documents with agent x''

**Comment by Xoxeyos** [comment]
Steal X amount of cash from the station's budget would also be a nice idea, now that budget cards are mostly removed.

**Comment by boodaliboo** [comment]
steal 3 ids

**Comment by Xoxeyos** [comment]
1. You could keep a person in X area for a short or lengthy amount of time
2. Put up X contraband posters in X area(s)
3. Put X handheld radios in these X rooms, X, X, and X.
4. Put a camera bug in X room.
5. Implant X with X implant.
6. Capture a picture of X in X area.

**Comment by Tipy1802** [comment]
What about ''Sabotage the science servers''

**Comment by Marmio64** [comment]
make minor objectives not count towards a redtext if you fail them, but be PURELY optional objectives encase you finish your main ones and are bored. Then, if you do that, just have traitors, lings, and bloodbros have a ~75% to receive 1-3

**Comment by Darkstick** [comment]
This is great because killing Ian makes you officially valid

**Comment by JamieD1** [comment]
Is this considered done? Still set as WIP

**Comment by ghost** [comment]
Steal a crown?

**Comment by Amelia0010** [comment]
@JamieD1 I suppose this is done, I intended to have more objectives than this but the suggestions are kinda bad and the ideas I've got require me to do up other stuff like the photo datum, so that'll be for other PRs

**Review by JamieD1 — APPROVED** [review]
Soap

**Pull request merged**
