### PR TITLE
removes "RP" from the server title because it's stupid and makes us look like citadel RP or any other HRP furry server

### PR DESCRIPTION
**Pull request by SomeguyManperson**
it was funny for like maybe a month
# Changelog

:cl:  
tweak: server title changed
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
flip flop, yogstation cant decided on what it is

**Comment by SomeguyManperson** [comment]
it was added as like a joke or something to belike LOOK WE'RE RP WE'RE COOL but just made us look like clown
having "RP" in the title gives vibes of like baystation levels of RP

**Comment by Marmio64** [comment]
lets be honest, yogstation doesn't rp.

**Comment by The-Sun-In-Splendour** [comment]
Yogstation 13 Roleplay - RP (Adult +18 Furry inclusive server) Successor to Hitman Yogstation [ENGLISH] [99% LAG FREE] High roleplay, boxstation map, furry & anthropomorphic inclusive server that focuses on inter-personnel friendships and relationships. ERP mechanics. "UwU what's this?"

**Comment by Hopekz** [comment]
> Yogstation 13 Roleplay - RP (Adult +18 Furry inclusive server) Successor to Hitman Yogstation [ENGLISH] [99% LAG FREE] High roleplay, boxstation map, furry & anthropomorphic inclusive server that focuses on inter-personnel friendships and relationships. ERP mechanics. "UwU what's this?"

Thanks for taking a break from Citadel to stop by our repo

**Comment by The-Sun-In-Splendour** [comment]
> 
> 
> > Yogstation 13 Roleplay - RP (Adult +18 Furry inclusive server) Successor to Hitman Yogstation [ENGLISH] [99% LAG FREE] High roleplay, boxstation map, furry & anthropomorphic inclusive server that focuses on inter-personnel friendships and relationships. ERP mechanics. "UwU what's this?"
> 
> Thanks for taking a break from Citadel to stop by our repo

No problem. Would you like maid nukies?

**Comment by SomeguyManperson** [comment]
> > > Yogstation 13 Roleplay - RP (Adult +18 Furry inclusive server) Successor to Hitman Yogstation [ENGLISH] [99% LAG FREE] High roleplay, boxstation map, furry & anthropomorphic inclusive server that focuses on inter-personnel friendships and relationships. ERP mechanics. "UwU what's this?"
> > 
> > 
> > Thanks for taking a break from Citadel to stop by our repo
> 
> No problem. Would you like maid nukies?

yes

**Comment by JamieD1** [comment]
I mean.. I didnt add it as a joke.

**Comment by Hopekz** [comment]
> I mean.. I didnt add it as a joke.

That's what makes it funny

**Pull request merged**
