### PR TITLE
In 2777, what makes someone a criminal?

### PR DESCRIPTION
**Pull request by Yarinoi**
# Document the changes in your pull request

Adds a brand new bundle to the Syndi-Kit Special, titled the 'Solo' kit, with a weight of 1.
Contains:
One (1) Neural Overclocker autosurgeon (no way)
Two (2) Mantis Blade autosurgeons (no way)
One (1) EMP Shield implant
One (1) Upgraded Cybernetic Lungs autosurgeon
One (1) Solo's Jacket (Marginally better sec armor vest)
One (1) Synaptizine Pill Bottle (take your drugs david)

Big thanks to riquegameplays for the initial idea

# Why is this good for the game?
More bundles good. Edgerunners reference also good. Gameplay variety. David why are you going cyberpsycho David get to work you have a job to do take your drugs David get to work.

# Testing
works now
pill bottle is empty but i can figure that out too
(p.s. the pill bottle being empty should have been fixed too, so dont worry about it)

# Spriting
None

# Wiki Documentation
update syndicate items

# Changelog

:cl:
rscadd: Welcome to Space Station 13. The only limit to what you can do, is what you're willing to become. Adds a new Solo bundle to the Syndi-Kit Special.
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Give it the giga-gar sunglasses(no huds),Combat Boots

**Comment by Yarinoi** [comment]
> Give it the giga-gar sunglasses(no huds),Combat Boots

tell me how it relates to edgerunners and i shall relent

**Comment by Moltijoe** [comment]
https://www.youtube.com/watch?v=C4gXH7uqraY

**Comment by RG4ORDR** [comment]
> > Give it the giga-gar sunglasses(no huds),Combat Boots
> 
> tell me how it relates to edgerunners and i shall relent

They wear boots - mostly.
Sunglasses are thematic and the Gars harken to Johnny's

**Comment by Yarinoi** [comment]
dont merge this till i can figure out whats causing it to be empty when rolled
molti..

**Comment by Yarinoi** [comment]
okay all the issues are (probably) fixed now, dont merge until the cyberpunk jacket is no longer donator restricted pr is also merged :)

**Review by MajManatee — CHANGES_REQUESTED** [review]
please add up the TC value like the other kits do with comments. Makes it WAY easier for balancing later if needed.

**Comment by Yarinoi** [comment]
> please add up the TC value like the other kits do with comments. Makes it WAY easier for balancing later if needed.

will do

**Review by MajManatee — APPROVED** [review]
Kits are cool and random so im sure its fine

**Comment by Yarinoi** [comment]
wait

**Comment by Yarinoi** [comment]
image
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
image
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Pull request merged**
