### PR TITLE
add maid job

### PR DESCRIPTION
**Pull request by SomeguyManperson**
yes
:cl:  
rscadd: add maid as alternate janitor job title
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
crying in the club rn

**Comment by Hislyna** [comment]
Im ready for some ~~E~~MRP!

**Comment by Anvilman6** [comment]
Theos the fetishcoder

**Comment by Cartlord** [comment]
Title unclear, makes it sound like you're adding a whole new job

**Comment by SomeguyManperson** [comment]
> Title unclear, makes it sound like you're adding a whole new job

is that a challenge

**Comment by Cartlord** [comment]
No, it's a serious criticism of the PR.

**Comment by Mqiib** [comment]
Local headcoder makes pr so he can rp as a shy xeno maid.

**Review by adamsong — APPROVED** [review]

**Pull request merged**
