### PR TITLE
Fixes Misaligned Random Maintenance Door in Starboard Quarter Boxstation Maint

### PR DESCRIPTION
**Pull request by alao3alao3**
bpng
This PR intends to realign a maintenance door and subsequent affected maintenance.
cpng
also I think that door had a wall in it

### Changelog
:cl:  
tweak: realigned maintenance door. 
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
You forgot monstermos firelocks

**Comment by alao3alao3** [comment]
all good

**Review by JamieD1 — APPROVED** [review]
@wejengin2

**Review by patpol4 — APPROVED** [review]
Alright all good

**Pull request merged**
