### PR TITLE
Clock cult kindle

### PR DESCRIPTION
**Pull request by Readystorm546**
Kindle was changed by me a while ago. But for some reason this thing was not changed. It was supposed to be. #7916

:cl:     
tweak: kindle lasts only 5 seconds instead of 15 and takes 4 seconds to conjour. This refers to the time that kindle is in your hand, the stun time is not effected.
tweak: >Kindle now costs more power. from 125 > 150
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
so how is clockcult supposed to get its converts when kindle stuns for only 5 seconds. And I think it was you that said this was supposed to make kindle a combat spell, but 4 seconds to conjure is not a combat spell. Make kindle last 8 seconds instead please, so there's enough time to cuff and teleport out, even then with how short kindle will be, if you try to take anyone they'll be able to radio in time that there's a clockcult so there'll be even less of a reason to not go to war.

edit: yes i know you can cuff relatively quick but kindle is SUPPOSED to be a ambush spell for converts and it was good that way. Clockcultists focus on ambush and setting up traps and defences, not rushing into battle. Their only tools for a direct fight is their visor, armor, and spear.

**Comment by Readystorm546** [comment]
> so how is clockcult supposed to get its converts when kindle stuns for only 5 seconds. And I think it was you that said this was supposed to make kindle a combat spell, but 4 seconds to conjure is not a combat spell. Make kindle last 8 seconds instead please, so there's enough time to cuff and teleport out, even then with how short kindle will be, if you try to take anyone they'll be able to radio in time that there's a clockcult so there'll be even less of a reason to not go to war.
> 
> edit: yes i know you can cuff relatively quick but kindle is SUPPOSED to be a ambush spell for converts and it was good that way. Clockcultists focus on ambush and setting up traps and defences, not rushing into battle. Their only tools for a direct fight is their visor, armor, and spear.

This was promised in a  previous PR that was already merged. This change was just. Never implemented. You should know that you can also use kindle while moving now. Thats the part that was merged in the previous PR. The kindle stun timer is not changed. It still stuns for the same amount of time. That 4 seconds is up from 3 seconds and you can use it while moving. Im up for making it last longer after cast but 5 seconds is still a lot of time. As for why this happened. You can still ambush with it its just  a bit harder. Also people are tired of the "teleport, stun, cuf, teleport back.

**Comment by Marmio64** [comment]
> > so how is clockcult supposed to get its converts when kindle stuns for only 5 seconds. And I think it was you that said this was supposed to make kindle a combat spell, but 4 seconds to conjure is not a combat spell. Make kindle last 8 seconds instead please, so there's enough time to cuff and teleport out, even then with how short kindle will be, if you try to take anyone they'll be able to radio in time that there's a clockcult so there'll be even less of a reason to not go to war.
> > edit: yes i know you can cuff relatively quick but kindle is SUPPOSED to be a ambush spell for converts and it was good that way. Clockcultists focus on ambush and setting up traps and defences, not rushing into battle. Their only tools for a direct fight is their visor, armor, and spear.
> 
> This was promised in a previous PR that was already merged. This change was just. Never implemented. You should know that you can also use kindle while moving now. Thats the part that was merged in the previous PR. The kindle stun timer is not changed. It still stuns for the same amount of time. That 4 seconds is up from 3 seconds and you can use it while moving. Im up for making it last longer after cast but 5 seconds is still a lot of time. As for why this happened. You can still ambush with it its just a bit harder. Also people are tired of the "teleport, stun, cuf, teleport back.

teleport, stun, cuff, teleport back is how clockcult plays because they're bad at direct combat, especially at the start when they literally only get kindle and no spear, armor, or visor.

**Comment by Hopekz** [comment]
I personally think the power cost is insignificant as it is already very inexpensive to cast almost making the change kind of irrelevant.

If you are going to increase it I say increase it further to where it matters

**Comment by Readystorm546** [comment]
> > > so how is clockcult supposed to get its converts when kindle stuns for only 5 seconds. And I think it was you that said this was supposed to make kindle a combat spell, but 4 seconds to conjure is not a combat spell. Make kindle last 8 seconds instead please, so there's enough time to cuff and teleport out, even then with how short kindle will be, if you try to take anyone they'll be able to radio in time that there's a clockcult so there'll be even less of a reason to not go to war.
> > > edit: yes i know you can cuff relatively quick but kindle is SUPPOSED to be a ambush spell for converts and it was good that way. Clockcultists focus on ambush and setting up traps and defences, not rushing into battle. Their only tools for a direct fight is their visor, armor, and spear.
> > 
> > 
> > This was promised in a previous PR that was already merged. This change was just. Never implemented. You should know that you can also use kindle while moving now. Thats the part that was merged in the previous PR. The kindle stun timer is not changed. It still stuns for the same amount of time. That 4 seconds is up from 3 seconds and you can use it while moving. Im up for making it last longer after cast but 5 seconds is still a lot of time. As for why this happened. You can still ambush with it its just a bit harder. Also people are tired of the "teleport, stun, cuf, teleport back.
> 
> teleport, stun, cuff, teleport back is how clockcult plays because they're bad at direct combat, especially at the start when they literally only get kindle and no spear, armor, or visor.

You know how many people hate that. You can counter it but its dificult. Sure people should pay more attention but because this was already promised in the previous pr. It needs to be added

**Comment by Readystorm546** [comment]
> I personally think the power cost is insignificant as it is already very inexpensive to cast almost making the change kind of irrelevant.
> 
> If you are going to increase it I say increase it further to where it matters

Generally considering you have maybe 10 cult boys. If they all use this that's alot of power. You gotta be careful.

**Review by Hopekz — APPROVED** [review]

**Comment by SomeguyManperson** [comment]
sir this is a timer on the duration of kindle in the slab not the duration of the stun

**Comment by Hopekz** [comment]
> sir this is a timer on the duration of kindle in the slab not the duration of the stun

Looks intentional to me 
image

**Comment by Readystorm546** [comment]
> sir this is a timer on the duration of kindle in the slab not the duration of the stun

That was thy point

**Comment by SomeguyManperson** [comment]
yes marmio was complaining about the stun time being lowered I think since most of his complaints were about being able to stun/cuff

**Pull request merged**
