### PR TITLE
Cryopods display a unique warning when the occupant cannot be treated

### PR DESCRIPTION
**Pull request by Hopekz**
When the occupant cannot be treated with the TRAIT_MEDICALIGNORE trait (Preternis for example) the cryopod will display a unique message, play a unique sound, and shut down.

Feels great in-game. 
No longer will anyone be able to leave preterni in cryo pods for 20 minutes at a time!! (Not an ided I haven't played preternis in over a year)

image

(Image by Wejengin2)
image

#### Changelog

:cl:  Hopek
rscadd: Cryopods display a unique warning when the occupant cannot be treated.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
speedmerge please

**Comment by athena413** [comment]
PLEASE
I BEG YOU

**Comment by Jarod1200** [comment]
What if you are a traitor and your intention is to kill a preternis with this method?
I like the warning it gives but shutting it down seems kinda hugboxy imo. Makes doctors have to think less.

You should add a warning for slimepeople too since they get melted by cryo unless you put cyanide or other irregular chemicals in instead of cryoxadone

**Comment by Hopekz** [comment]
> You should add a warning for slimepeople too since they get melted by cryo unless you put cyanide or other irregular chemicals in instead of cryoxadone

Too lazy; hopefully someone else will get to it in a future PR or maybe I'll get the motivation for it in the future.

**Comment by Moggram** [comment]
No more dying in a god dam cryopod, Fuck Yay!

**Comment by Firewolf34** [comment]
Bout damn time

**Comment by Tipy1802** [comment]
Non human bad

**Review by fluffe9911 — APPROVED** [review]
lets be honest medics will keep trying 5 more times then just attempt to clone you anyway

**Pull request merged**
