### PR TITLE
De-modularize Plants

### PR DESCRIPTION
**Pull request by Readystorm546**
Plants will now be in one file. Instead of some duplicate bullshit
:cl:  
rscadd: Added yogs plants to original file  
rscdel: Removed yogs file
/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
This compiled on my end. The fuck?

**Comment by Hopekz** [comment]
> This compiled on my end. The fuck?

Turdis breaks more often than Travis

**Comment by athena413** [comment]
good

**Comment by monster860** [comment]
@FLME Can you please stop with the worthless one word comments? If you have binary feedback (eg. "good" or "bad") use the thumbs-up/down reacts.

**Pull request merged**
