### PR TITLE
Adds Some Cool New Weapon Sound Effects

### PR DESCRIPTION
**Pull request by UselessTheremin**
### Intent of your Pull Request

new sounds for the fire axe, armblades, and katana. i think they sound cool and i enjoy variety, i may want to help revamp some of our sound design to help make us stand out from other stations from just a close glance. idk, new thing fun

god save me i spent all night combing through royalty free stock sounds aaaaah

### Why is this good for the game?

better sound effects are just very easy quality of life changes, really. it makes spacemans all the more tiny bit polished.

#### Changelog

:cl:    
soundadd: new axe sound
soundadd: new cool katana sound
soundadd: new icky visceral armblade sound
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
mediocre sounds, but the katana one is like, really bad, sounds nothing like a katana.

**Comment by UselessTheremin** [comment]
> mediocre sounds, but the katana one is like, really bad, sounds nothing like a katana.

it sounds like a katana from an arcade game to me, but idk

**Comment by Xoxeyos** [comment]
Yeah the katana sound kinda sucks. The other ones sound fine to me however.

**Comment by JamieD1** [comment]
Surely there is a better katana sound out there.

**Comment by JamieD1** [comment]
@UselessTheremin New katana sound or this is being closed

**Pull request closed without merging**
