### PR TITLE
Atmos gas mask + alternate mask sprite tweaks

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Adds atmos gas masks, a slightly better and cooler looking gas mask for atmospheric technicians. Also adds an alternate sprite for sterile masks and edits the existing alternate sprites of a few other masks.

Atmos gas mask sprite ported from tgstation/tgstation#46732

# Spriting
Atmos gas mask
image
Standard gas mask
image
Welding gas mask
image
Syndicate mask
image
Sterile mask
image

# Changelog

:cl:  SapphicOverload, carlarctg
rscadd: adds atmos gas masks
tweak: edits a few alternate mask sprites
imageadd: adds atmos gas mask sprites
imageadd: adds sterile mask alternate sprite
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
The more snout compatible things we add the closer we move to furry station 13

**Review by cuackles — CHANGES_REQUESTED** [review]
need the object icon of the atmos gas mask to have its outline toned down a bit, seems to dark so it sticks out a bit more than usual, normal gasmask has the same outline but since its grey the outline doesnt look so big

**Comment by iamthesilly** [comment]
> need the object icon of the atmos gas mask to have its outline toned down a bit, seems to dark so it sticks out a bit more than usual, normal gasmask has the same outline but since its grey the outline doesnt look so big

Is this a bit better?
image

**Comment by cuackles** [comment]
image
difference is to slightly to actually tell, outline is still to dark

**Comment by SapphicOverload** [comment]
image
is this better?

**Comment by iamthesilly** [comment]
image
Is this better?

**Review by cuackles — APPROVED** [review]

**Review by JohnFulpWillard — APPROVED** [review]

**Pull request merged**
