### PR TITLE
removes the captains laser from lavaland snow ruin and gives them a gluon grenade

### PR DESCRIPTION
**Pull request by boodaliboo**
gives them a one time use grenade for going into here and doesnt completely make it worthless except for shelter
#### Changelog

:cl:    
tweak: tweaked lavaland snow run
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
What does a gluon grenade do?

**Comment by Mqiib** [comment]
lizard repellant

**Comment by boodaliboo** [comment]
> What does a gluon grenade do?

freeze slow greande

**Comment by Mesalikepie** [comment]
Good pr then. Love this and definitely needs to happen. Maybe adding a flavor note of it being the first ever gluon grenade would be kinda cool as well! Flavor notes are always awesome

**Comment by ghost** [comment]
terrible idea, feeds into miner antag hunting as usual.

gluon grenades are nukeop weapons as well.

**Comment by boodaliboo** [comment]
> terrible idea, feeds into miner antag hunting as usual.
> 
> gluon grenades are nukeop weapons as well.

this is a singular one

**Review by patpol4 — APPROVED** [review]
I like this one better then the plant but ultimately it's up to the hc's

**Pull request closed without merging**
