### PR TITLE
Bloodsuckers now resist damage slowdown

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Bloodsuckers have no crit but can't really make any use of it because of how new damage slowdown works, fucking you particularly hard once you reach around 90 damage

I saw a bloodsucker clown get gamed up while he tried to dodge with his 500 slowdown and it made me sad so I made this

# Changelog

:cl:  
tweak: Bloodsuckers are now affected less by damage slowdown
/:cl:

### CODE REVIEW

**Comment by Mantlecrawler** [comment]
You should also make it not white out the screen because it basically blinds you

**Comment by ynot01** [comment]
> You should also make it not white out the screen because it basically blinds you

maybe in another pr idk how to do thaqt

**Comment by MajManatee** [comment]
same blind issue but when you go into frenzy and the screen is just paintbucketed red and its impossible to navigate.

**Comment by Moltijoe** [comment]
> You should also make it not white out the screen because it basically blinds you

#17890

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
