### PR TITLE
floor cluwne can't be sentienced

### PR DESCRIPTION
**Pull request by SomeguyManperson**
lol
:cl:  
bugfix: floor cluwne can't be sentienced
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
NO

**Comment by LazennG** [comment]
rip floor cluwne mains

**Comment by Reed0506** [comment]
bruh moment

**Review by alexkar598 — APPROVED** [review]

**Comment by alexkar598** [comment]
Floor cluwne cannot control its abilities so it shouldn't be be PC'd

**Pull request merged**
