### PR TITLE
Re-enable infiltrators

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

This gamemode is well-balanced, why not include it? Why do we just have code rotting around in this repo that goes unused as even admins don't play this gamemode
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Re-enable infiltrators
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
It was cool but also monumentally greenshifty

**Comment by Simplehorror** [comment]
so are traitors and blood brothers if they don't get hijack

**Comment by Simplehorror** [comment]
can give more evil objectives

**Comment by Firewolf34** [comment]
Okay okay hear me out. Make it a random event

If the issue is that it's too stealthy, then just make it something happening in the background during dynamic. If you need to scale the amount of infiltrators down in the team, so be it. It definitely seems like it's too weak of a threat to be the entire focus of the round, at least.

Infiltrators needs to pull ghosts out from the pool in lategame, for a random operation the same way the ninja / revenant / lone op / etc. do. Unless that's what this change enables?

**Comment by Simplehorror** [comment]
that might happen once i implement my Dungeon Master system

**Comment by neeshacark** [comment]
i would not have an issue with reenabling infiltrators if we can fix it to where they have a way to get more objectives so the round isnt just a greenshift once they do their things.

**Comment by VaelophisNyx** [comment]
I leave and everyone loses their damned minds it seems
they were disabled for being colossally shit

improve that shit before you bother re-enabling them

**Comment by Simplehorror** [comment]
can't fix them until i see some gameplay

**Comment by Bibby0110** [comment]
watch replays

> can't fix them until i see some gameplay

**Pull request closed without merging**
