### PR TITLE
Readds makeshift laser gun

### PR DESCRIPTION
**Pull request by boodaliboo**
i dont see why the guass rifle needs to be mutaully exclusive
:cl:  
rscadd: readds makeshift laser gun

/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
> i dont see why the guass rifle needs to be mutaully exclusive 🆑 rscadd: readds makeshift laser gun
> 
> /🆑

vaeolphyus nyx just downvotes my prs cause i made them lol

**Comment by ghost** [comment]
Makeshift laser gun sucks ass it is a useless 5 damage weapon lol

**Comment by VaelophisNyx** [comment]
> > i dont see why the guass rifle needs to be mutaully exclusive 🆑 rscadd: readds makeshift laser gun
> > /🆑
> 
> vaeolphyus nyx just downvotes my prs cause i made them lol

I downvote them because they're poorly thought out or already rejected ideas :/

**Comment by boodaliboo** [comment]
> Makeshift laser gun sucks ass it is a useless 5 damage weapon lol

no it isnt you can charge it you clearly havent used it

**Comment by boodaliboo** [comment]
> > > i dont see why the guass rifle needs to be mutaully exclusive 🆑 rscadd: readds makeshift laser gun
> > > /🆑
> > 
> > 
> > vaeolphyus nyx just downvotes my prs cause i made them lol
> 
> I downvote them because they're poorly thought out or already rejected ideas :/

i dont believe this

**Comment by boodaliboo** [comment]
> Makeshift laser gun sucks ass it is a useless 5 damage weapon lol

looking at the code and people in the pr removing that, that isnt the case its base damage does that but you can charge it for up to 17 damage per shot

**Comment by 00ze-cyclone** [comment]
Yes, you can charge it up to use 1000j PER SHOT to deal less than a regular laser (and everyone already think they suck)

**Pull request closed without merging**
