### PR TITLE
Makes Genetics and Xenobiology less insular. Boogaloo edition.

### PR DESCRIPTION
**Pull request by Lovebird-Frungy**
aka it actually works edition.
This is just me messing up my prs, this is the same as the old one, just starting fresh.
Many thanks to @maxion12345 for helping fix this mess. Also thanks to @Marmio64 for the feedback.
Also thanks to @JamieD1 for fixing this mess too, as well as for a lot of input.

# Document the changes in your pull request

Expands the station by adding a new hallway.
−> Gives genetics and xenobiology some much needed public access, complete with desks!
−> Service hall was brought back to the forefront so it is easier to access.
Maintenance was rearranged to fit the new size.
CMO office slightly bigger. Runtime now has a toy and a milk bowl.
Botany backroom expanded.
Cloning expanded.
Blob has a new spawner since maints are bigger.

Pictures:
image
image
image

# Wiki Documentation

Xenobiology and genetics now have desks to interact with crew members.
Service hall is now accessible via main hallways, like old times!
A new area: Aft Starboard Hallway.

# Changelog

:cl:  
rscadd: added a new hallway.
rscadd: added desks to xenobio and genetics.
tweak: botany backroom, cloning, cmo office are also slightly bigger.
tweak: moved back service hall.
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
'ery nice
now we need to get this merged before any other map changes get merged and cause a conflict

**Comment by ToasterBiome** [comment]
don’t think we need the horizontal airlocks in the hallway, one’s separating the new hall are fine imo

**Comment by JamieD1** [comment]
Hmm.. will need to talk with weje about this.. @wejengin2

**Comment by Lovebird-Frungy** [comment]
Ok, i have no idea what went wrong with the code.
Did a map change get merged in the meantime?
It doesn't make any sense, it was working before and now it isn't.

**Comment by JamieD1** [comment]
I like some aspects of it but dont like some others, can you dm me on discord when you see this so we can go over it?

**Comment by JamieD1** [comment]
Map review with Author, changes ongoing

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
