### PR TITLE
[Ready][Bounty] Adds new racial martial arts

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

https://forums.yogstation.net/threads/50-add-new-racial-martial-arts-ss13-server.22144/

I am planning to make from it only preternis, plasmamen and podpeople arts, because I simply don't know how to do pounce thingies(and also I don't like races that are just based on alredy existing animals/insetcs(and also lizard martial art from that bounty and also some parts of the "nonlethal" martial art were already made(respectively flying fangs and reworked cqc))), so instead of 50 dollars I think that 24 dollars will be ok(The bounty says that 8$ for each martial art).

image

# Wiki Documentation

Add this to traitor items

# Changelog

:cl: SuperSlayer
rscadd: Adds three new martial arts
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Fuck

**Comment by 95Roadkill** [comment]
I was about to ask about the hivemind changes but nevermind, seems you fixed it.

**Comment by ghost** [comment]
> I was about to ask about the hivemind changes but nevermind, seems you fixed it.

I am just a dumbfuck, who doesn't learn on his mistakes

**Comment by ynot01** [comment]
Remove the instant aggro grabs

**Comment by ghost** [comment]
> Remove the instant aggro grabs

There is no such

**Comment by ghost** [comment]
image
oh fuck i need to somehow code this shit

**Comment by ghost** [comment]
It is almost ready, the only thing left is a sprite for vine snatch action

**Comment by Mqiib** [comment]
If this actually works I'm gonna be SO PUMPED!! Only been waiting like two years for these. If it gets merged I can do any rebalancing and tweaks after some testing.

**Comment by MegaEmpirical** [comment]
I've always dreamed of a martial art for janitors with their mops but this looks cool too.

Looking forward to unleashing my firey fists of death.

**Comment by JamieD1** [comment]
@KillerOrcaCora Sprite if you have time

**Comment by cowbot92** [comment]
Plasmamen are unable to read their martial arts scroll.

**Comment by cowbot92** [comment]
> Plasmamen are unable to read their martial arts scroll.

They also cannot "remember" their moves using the button, rest of it seems to work fine.

**Comment by Mqiib** [comment]
Couple bugs with the plant one I found:
1: Splinters don't have a sprite. They don't have to be at all fancy because you'll never see them as an item so I'm sure you can just make one that's passable.
2: For some reason once i hit the level 2 vine grab all my harm intent attacks were doing the neck grab thing instead of actually doing the harm combo
3: splinter stab doesn't do damage to the user's arm, which is pretty minor really
4: I definitely might need to do some rebalance stuff, maybe make the grab combo disarm/grab/grab so it's not explicitly an instant aggro grab but the second hit will always be instant aggro grab. If you wanna change that be my guest

**Comment by Mqiib** [comment]
5: the vine mark seems to either not get applied or the timer on it is bugged because it is never able to be used even if activated right after the second strike

**Comment by Mqiib** [comment]
Preternis one is near perfect, just a few things
1: stab combo should be pointed not slashing damage so it can make a puncture wound, and is also supposed to stun for one second
2: the finger gun combo is only supposed to have ONE shot from the gun not a full clip (as hilarious as that is)

**Comment by ghost** [comment]
Ok, will fix it today

**Comment by ghost** [comment]
> 5: the vine mark seems to either not get applied or the timer on it is bugged because it is never able to be used even if activated right after the second strike

What does it say when you fail to mark someone?

**Comment by Mqiib** [comment]
Ok putting this here just so I can keep track of it. You don't actually have to make these changes but these are just balance changes I'll do later once this is full merged

Plant martial art:
 - reduce splinter damage and removal timer
 - make the vine grab ability 3 tile range and always knock down (3 seconds)
 - increase block chance on the active block to 75% so it's more consistent and actually conveys an advantage
 - give some kind of slow or SOMETHING to the second hit of choke combo because its way too easy to break out of. Maybe just a short 1 or 2 second stun to get it going since it's on the second hit anyways OR make the grab harder to break out of
 - get a different icon for the scroll (a leaf/wooden plank?) and name it something else in the uplink like "garden warfare [thing]"

No bugs found after second testing on the plant combo!

For the preternis one
- reduce sodium thiopentol to 4 units since 8 is a guaranteed knockout without immediate intervention

Plasmeme martial art
- not enough testing, but from what i can tell the fire immunity duration should be longer so you dont get rekt
- probably should have a vent combo that resets your body temp (and maybe heals some burn damage based on temp?)


Anyways this is EXCELLENT so thank you for PRing these!

**Comment by Mqiib** [comment]
ok messing around with the plasma man one the thing that checks for a helmet doesnt work but i
m not too concerned about that, could probably just let that one go. Life force succ doesnt heal brute though, which I'll fix if you dont get to it before it's merged (please merge this eventually jamie i want to do more work)

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
