### PR TITLE
let's hear some tunes - volume 1

### PR DESCRIPTION
**Pull request by burn1cycle**
adds some tunes to the jukebox

### CODE REVIEW

**Review by redmoogle — APPROVED** [review]
Songs are all well songs

I'd recommend removing Rock is dead as the intro will _probably_ destroy peoples ears

**Comment by redmoogle** [comment]
<details open>
<summary>All the songs tracked to the best of my ability</summary>
<br>
https://www.youtube.com/watch?v=U4U19zwFENs
<br>
https://www.youtube.com/watch?v=WmqTJceo11w
<br>
https://www.youtube.com/watch?v=eJQhPpYozz0
<br>
https://www.youtube.com/watch?v=L-kyRh7N-kE
<br>
https://www.youtube.com/watch?v=uenM0nb8Vz8
<br>
https://www.youtube.com/watch?v=uxPvEJhw0fM
<br>
https://www.youtube.com/watch?v=HEXWRTEbj1I
<br>
https://www.youtube.com/watch?v=37-WR-SyTxs
<br>
https://www.youtube.com/watch?v=EL_pBJN_O3M
<br>
https://www.youtube.com/watch?v=GeVufklHMsA
<br>
https://www.youtube.com/watch?v=X3NA8cRn2l8
<br>
https://www.youtube.com/watch?v=A_WvipqGAbw
<br>
https://www.youtube.com/watch?v=0C3pUpqmuis
<br>
https://www.youtube.com/watch?v=7Co24vXk5GM
<br>
https://www.youtube.com/watch?v=ZWmrfgj0MZI
<br>
https://www.youtube.com/watch?v=hwdKSGWb29c
<br>
https://www.youtube.com/watch?v=DcHKOC64KnE
<br>
https://www.youtube.com/watch?v=vEc9nXErU-Y
<br>
https://www.youtube.com/watch?v=N3E4xtbV9AM
<br>
https://www.youtube.com/watch?v=bqgPjgXbzv4
<br>
https://www.youtube.com/watch?v=IC-DwCRX2I0
<br>
https://www.youtube.com/watch?v=p8VRlOSlDEY
<br>
https://www.youtube.com/watch?v=mA_VCkHrPvA
<br>
https://www.youtube.com/watch?v=BhErMeQuZyU
</details>

yeah it's _alot_

**Comment by Marmio64** [comment]
these are some great songs, i support

**Comment by burn1cycle** [comment]
> Songs are all well songs
> 
> I'd recommend removing Rock is dead as the intro will _probably_ destroy peoples ears

 I'm a bit new to github but I suspect I can't remove the single song without redoing the whole request?

**Comment by Marmio64** [comment]
> > Songs are all well songs
> > I'd recommend removing Rock is dead as the intro will _probably_ destroy peoples ears
> 
> I'm a bit new to github but I suspect I can't remove the single song without redoing the whole request?

you can just go back in, remove the song you don't want, and commit it. You can't go back into things you've already commited and change them, but you can make a new commit to change a past one.

**Comment by burn1cycle** [comment]
Removing Rock is Dead due to leveling issues

**Pull request closed without merging**
