### PR TITLE
Stunprods can now be utilized for ghetto revival surgery

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
# Document the changes in your pull request

Stunprods can now be used in revival surgery, at a 60% chance to succeed.

I have tested this, and yes, it works.

# Wiki Documentation

Update the surgery page to show that you can now use stunprods.

# Changelog

:cl:  
tweak: Stunprods can now be used for revival surgery
/:cl:

### CODE REVIEW

**Comment by nmajask** [comment]
Don't see a reason to remove the ability to use guns with a shock round in the chamber, as it can still be useful for the charlie station or some ERTs, which still has access to them. Also, add Tweak: in front of all your entries in the change log.

**Review by adamsong — CHANGES_REQUESTED** [review]
Stun prod is fine, readd taser

**Comment by nmajask** [comment]
Have you tried using a stun prod in game for the surgery? They are a subtype of batons, so unless they have a weird way of checking if it's active then this is pointless.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Tested it ingame, does work without the code changes. Sorry.

**Pull request closed without merging**
