### PR TITLE
Adds random rarity tiers to the game for every item, lets players reroll their stats, and adds super credits for donators.

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Adds some rarity tiers, and lets players use an "enchantment anvil" in the station to reroll these!

Normal items get +0 to force and armor
Uncommon get +2
Rare get +5
Legendary get +10
and Mythical gets a whopping +25!

Here are the percentages for spawning and rerolling!
image

Donators can use special "Super Credits" to increase their roll chance. Free players are given ten super credits to play around with, while mentors and admins get ten more! non-admin/non-mentor donators get an incredible TWENTY super credits per round to bring their total to thirty! With this, donators surely will have better rolls. Donate today to do more damage!

image

# Why is this good for the game?
A big part of what is killing yogs is that there's not enough randomness in each round. With this new system we can have more interesting both roleplay and combat oriented rounds, and this can help balance certain antags like lings!

Also increases donators and donator retention by giving them 20 free super credits!

# Testing

https://github.com/yogstation13/Yogstation/assets/5091394/2784ee33-a3dd-48d7-990d-b5752a3162e8

Here I enchant a completely legitimate fireaxe

# Wiki Documentation

All items in the game now get new rarities. The enchantment anvil is available in each station for this.

# Changelog

:cl: baiomu, chubbygummibear
rscadd: Adds a new rarity system for players to use!
/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
cool TGUI biome your best work yet

**Comment by Chubbygummibear** [comment]
if you don't find a way to keep this ui relevant i'm killing you

**Comment by N3D6** [comment]
*checks date*

Thank god, it’s real! I’ve always supported microtransactions, we should try and work those in aswell.

**Comment by Yarinoi** [comment]
not enough gui elements and visual noise, i want the only functional viewing area being the size of a goddamn tiktok

**Comment by ktlwjec0** [comment]
thank you for fixing yogstation

**Pull request closed without merging**
