### PR TITLE
Gastrectomy

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

https://github.com/tgstation/tgstation/pull/50807

Gastrectomy, another organ healing surgery aimed directly to remove a portion of your duodenum to make food digesting be more appealing after being dead for quite a while.

#### Changelog

:cl:  
rscadd: Adds Gastrectomy surgery
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
like i like this but is it needed we dont have organ health as much of a problem as tg due to there chems damaging organs

**Comment by Ratvar** [comment]
That does not explain why it is not needed, bood

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
Bloat

**Comment by Marmio64** [comment]
BRUH

**Pull request closed without merging**
