### PR TITLE
Change Service Channel back to Dark Green 

### PR DESCRIPTION
**Pull request by Spl99**
### Intent of your Pull Request

Changes the Service Channel back to dark green from the lime green.

From Feature Request: https://forums.yogstation.net/index.php?threads/bring-back-the-better-service-channel-color.20337/

**// Maintainer edit:** 
Below is the color for reference 
image

#### Changelog

:cl:  Spl99
rscadd: Service is now Dark Green

/:cl:

### CODE REVIEW

**Comment by Spl99** [comment]
Sorry, I was adding something I didn't want to.

**Comment by Spl99** [comment]
Can you tell I'm a noob?
Ignore the space dust stuff, thats for something different that I'm working on. I've revered those changes so they shouldn't now be included in this PR if I've done this right.

**Comment by JamieD1** [comment]
Would it be mean to ask you to do this on a new branch without all the commits?

**Comment by Hopekz** [comment]
> Would it be mean to ask you to do this on a new branch without all the commits?

Not sure why this would be necessary at all?
The commits do not matter only the end result of what is being merged into the code.

**Review by Hopekz — APPROVED** [review]

**Comment by JamieD1** [comment]
> > Would it be mean to ask you to do this on a new branch without all the commits?
> 
> Not sure why this would be necessary at all?
> The commits do not matter only the end result of what is being merged into the code.

I mean its no problem, just feels a bit overkill for four lines with 10 commits, its just triggering me.

**Comment by alexkar598** [comment]
Can you show this next to the common channel in game? I fear that the colors may be too smililar

**Comment by Readystorm546** [comment]
Show it in dark mode too. I fear

**Comment by Spl99** [comment]
Sorry for the delay:

img

Maintainer edit: Made the link an image

**Comment by alexkar598** [comment]
Colors are way too close

**Comment by Hopekz** [comment]
I think the reason this was initially changed was because of Alex's point.
They are similar especially when you skim over the chat

**Comment by alexkar598** [comment]
Going to close this due to the colors being too close

**Pull request closed without merging**
