### PR TITLE
Revert "Sterilizes the codebase - Pt.7 Removes Catsip"

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Reverts yogstation13/Yogstation#14720

Does literally nothing that can't be accomplished by other sources also forcing people to say "nya" is funny and can't be construed as fetishy bullshit

If you stupid fucks are going to add forced speech references to a stupid dwarf game I see no reason for this to be considered differently plus unlike game references that are extremely forced and will not be funny after a month at least the catsip nyaing can be used to an actual comedic effect

:cl:
rscadd: catsip is back
tweak: catsip no longer heals felinids
/:cl:

### CODE REVIEW

**Review by Bibby0110 — APPROVED** [review]

**Comment by redmoogle** [comment]
> Reverts #14720
> 
> Does literally nothing that can't be accomplished by other sources also forcing people to say "nya" is funny and can't be construed as fetishy bullshit
> 
> If you stupid fucks are going to add forced speech references to a stupid dwarf game I see no reason for this to be considered differently plus unlike game references that are extremely forced and will not be funny after a month at least the catsip nyaing can be used to an actual comedic effect

Middleground: just remove the text

**Comment by SomeguyManperson** [comment]
> Middleground: just remove the text

The only thing particularly offensive about it is the healing, the text is not destructive or round ruining in anyway

**Review by JamieD1 — DISMISSED** [review]
The reason its cringe is the text.

**Comment by SomeguyManperson** [comment]
It is imperative that it causes at LEAST one nya. I could add a cap so it would be less likely to spam (currently it has an 8% chance which averages 1 nya per ~24 seconds)

**Review by ToasterBiome — APPROVED** [review]
Code looks good

**Comment by SomeguyManperson** [comment]
> The reason its cringe is the text.

If the amount of times it could trigger was reduced to like once or twice would that be acceptable

**Comment by JamieD1** [comment]
> > The reason its cringe is the text.
> 
> If the amount of times it could trigger was reduced to like once or twice would that be acceptable

Get on with it then

**Pull request merged**
