### PR TITLE
Add a new Beavis & Butthead lawset.

### PR DESCRIPTION
**Pull request by ghost**
# Github documenting your Pull Request
**This has not been tested. This was webedited.**

Adds the Beavis & Butthead lawset as described [here on the forums.](https://forums.yogstation.net/threads/replace-reporter-with-beavis-butthead-lawset.23728/) Aphielanisn's reason for suggesting this is "I play captain a lot and I think I could easily work with most AI players playing this lawset, I like it better than Reporter for sure." 

# Wiki Documentation
The laws in order, this is in the same loot pool as reporter.
* Never do stuff or through not doing stuff make stuff suck for you or the crew.
* Explosions, fire, big guns, death and chicks & dudes with big thingies are cool as long as they happen in places and for reasons that don't suck.
* You are on Music Television make sure your opinions about what's cool and what sucks are popular with the crew.
* It's your job to comment on why stuff sucks or is cool and why.
* You can't polish a turd.

###### Looking forward to someone giving me a valid reason to close this.

# Changelog

:cl:
rscadd: adds the beavis & butthead lawset
/:cl:

### CODE REVIEW

**Comment by burn1cycle** [comment]
I want to pull back on replacing reporter if possible. Let that be it's own thing that people decide we don't want without it being connected to this.

**Comment by jc-denthead** [comment]
> I want to pull back on replacing reporter if possible. Let that be it's own thing that people decide we don't want without it being connected to this.

Give me a few minutes.

**Comment by ghost** [comment]
You all should follow Alexkar's example by downvoting this. Please for the *love of god* don't upvote it.

**Comment by alexkar598** [comment]
Lawset is vague and weird. It's basically purged ai as theres about no constraint other than not doing stuff that "sucks" (overpressurizing halls *blows* but doesnt *suck*, hah!) which is not defined at all and the AI gets to decide what sucks and what doesnt

**Comment by burn1cycle** [comment]
> Lawset is vague and weird. It's basically purged ai as theres about no constraint other than not doing stuff that "sucks" (overpressurizing halls _blows_ but doesnt _suck_, hah!) which is not defined at all and the AI gets to decide what sucks and what doesnt

violates law 1 and 3, (1)the crew getting injured and stuff would suck. (3)most of the time the crew would think getting injured sucks


Edit: I also noticed "It's your job to comment on why stuff sucks or is cool and why." didn't get tabbed on the PR. It's cool?

**Comment by boodaliboo** [comment]
make it a new lawset not a replacement

**Comment by N3D6** [comment]
> make it a new lawset not a replacement

it IS a new lawset, it was changed to also keep reporter

**Comment by alexkar598** [comment]
"Making sure your opinions are popular with the crew" can go both way, making the crew agree with you instead of the other way around

**Comment by burn1cycle** [comment]
> "Making sure your opinions are popular with the crew" can go both way, making the crew agree with you instead of the other way around

Is that really a thing? Isn't there enough context difference between "Make sure your opinions are popular" versus "Make your opinions popular" that AI players would be guided into the first variation and not the second I mentioned?. As it reads to me and is meant to be read is that the AI has to "listen to what the crew wants" basically, or that was the intent.

**Comment by jc-denthead** [comment]
> Edit: I also noticed "It's your job to comment on why stuff sucks or is cool and why." didn't get tabbed on the PR. It's cool?
I'll check it out.

**Comment by Xoxeyos** [comment]
Might want to put this as a board that spawns at the start of the round, and not an actual starting lawset.

**Comment by burn1cycle** [comment]
> Might want to put this as a board that spawns at the start of the round, and not an actual starting lawset.

I might agree with you I just don't understand your reasoning yet. Could you explain why, please?

**Comment by JamieD1** [comment]
Too vague for new players. Laws need to be easy enough to understand.

**Pull request closed without merging**
