### PR TITLE
Constructable Filing Cabinets

### PR DESCRIPTION
**Pull request by Pitohuii**
### Intent of your Pull Request

Filing Cabinets can be made from 5 metal sheets.

#### Changelog

:cl:  
rscadd: Filing Cabinets can be made from metal sheets now.
/:cl:

### CODE REVIEW

**Review by alexkar598 — APPROVED** [review]

**Comment by Pitohuii** [comment]
I didn't mean to request the second commit, too new to this fancy program

**Review by alexkar598 — CHANGES_REQUESTED** [review]
You will need to remove that second commit to get this merged

**Comment by athena413** [comment]
good

**Comment by alexkar598** [comment]
Remake a new PR when you fixed your branch

**Pull request closed without merging**
