### PR TITLE
Renames Spite drink to Spit

### PR DESCRIPTION
**Pull request by Moja10**
I think that Spite is a cool name, but the idea of someone ordering a drink named 'Spit' from a vending machine and drinking it on a state of the art space station gotta be the funniest shit i've ever heard, so I wish to share this all with the Yogstation 13 player base as well

### CODE REVIEW

**Comment by solwashere** [comment]
can't wait for it to just be called "t" in 2 months

**Comment by TerraTheUnwise** [comment]
"hey bro wanna drink some spit??"

**Comment by Therandomhoboo** [comment]
No

**Comment by ynot01** [comment]
im going to Spit in youdr nik

**Review by Moltijoe — CHANGES_REQUESTED** [review]
too similar to acid spit, a different drink

**Comment by neeshacark** [comment]
rename it to Spriter Juice and make it come with a free collectible card on the inside with the face of a famous Spriter

**Comment by Moja10** [comment]
> too similar to acid spit, a different drink

This cannot be fixed, if it can't be accepted as just 'Spit' then I suppose it has to stay as 'Spite'

**Pull request closed without merging**
