### PR TITLE
gives laser tag armor 5 melee resist

### PR DESCRIPTION
**Pull request by boodaliboo**
its a hunk of plastic and it has armor in its name. this allows you to defend yourself a small ammount with laser tag armor
#### Changelog

:cl:   
tweak: gave melee resist to laser tag armor

/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Why not; I think a wet floor sign gives you 5 at least.

**Comment by boodaliboo** [comment]
> Why not; I think a wet floor sign gives you more armor than 5.

na wet floor sign gives you 5 aswell so there about equal

**Comment by maxion12345** [comment]
FUCKINC LASER TAG POWER CRESPSD REE

**Comment by Marmio64** [comment]
i mean, its generally a downside to just go around wearing the armor since a random tard can just pick up the opposite color and stamina crit you in 6 shots. This is good.

**Review by fluffe9911 — APPROVED** [review]
Harmless

**Pull request merged**
