### PR TITLE
Adds a duelist sword mining loot

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Adds a new necropolis chest loot - duelist's sword

It is an item that can be used in mining, while also making it usefull for antag dudes.

It is a sharp edged sword with a force of 16, no armor penetration, and 0 block chance. The fun thing in it is when it is used inhand, it will make you block any incoming projectiles for 0.5 seconds. This action has a 1 second cooldown. 

# Spriting
Has a sprite of a claymore lol

# Wiki Documentation

As i remember guide to mining has something about lavaland loot, so yeah

>a sharp edged sword with a force of 16, no armor penetration, and 0 block chance,  that can be used inhand to make you block any incoming projectiles for 0.5 seconds, with a cooldown for 1 second.

# Changelog

:cl: SuperSlayer
rscadd: Added a duelist sword item, and added it to necropolis tendrills
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
dont think miners need more of this, the basalt katana or whatever already exists and basically does the same thing but better.

**Comment by SuperSlayer0** [comment]
> dont think miners need more of this, the basalt katana or whatever already exists and basically does the same thing but better.

The point of this item is blocking things like colossus projectiles rather then fighting in melee

**Comment by ghost** [comment]
> dont think miners need more of this, the basalt katana or whatever already exists and basically does the same thing but better.

Katana has been moved into a ruin and doesn't drop from necropolis chests

**Comment by GraveHat** [comment]
> > dont think miners need more of this, the basalt katana or whatever already exists and basically does the same thing but better.
> 
> Katana has been moved into a ruin and doesn't drop from necropolis chests

I'll be moving a lot more when I get down to it.

**Comment by Skrem7** [comment]
A 1 sec cd on a 0.5 projectile invulnerability with zero downsides that can be spammed is asking for trouble, we don't need to give miners more ways to be indifferent to sec, at least the basalt katana roll can have you crash into walls + it inflicts staminaloss on doing it

**Pull request closed without merging**
