### PR TITLE
Gaminada's map bugfix

### PR DESCRIPTION
**Pull request by maxion12345**
# If this is your first PR, or not, take the time to read our your mom o yea rea

# Document the changes in your pull request

Moved xenobio camera down 2 tiles
Changes access to xenobio door shutter button thingy 
obliterated rogue wall light under robotics

# Wiki Documentation

Remove this text and write all information regarding your changes that should be known and documented through the Yogstation Wiki. 
Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
bugfix: fixed xenobiology camera not seeing the entire lower-righthand cell + xenobio shutter button access, and a rogue wall light under robotics
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
So you know when I said map fixes are paused
You can either do all these changes again once my map is merged or I can add them to my map for you.

**Comment by maxion12345** [comment]
its 3 changes it'll be easier to add to your map changes

**Comment by gaminada** [comment]
Praise be

**Comment by JamieD1** [comment]
Added into my map change and credited in changelog

**Pull request closed without merging**
