### PR TITLE
new lavaland mobs sprites (majority of them)

### PR DESCRIPTION
**Pull request by tattax**
Updates lavaland sprites (that are i believe over 7 years old to this point) to new ones from TG.

Some sprites are up for the debate so i left old sprites that i believe would be most controverisal on the file for easy re-implementation just in case, since some of these can be argued with.

Ports:
    https://github.com/tgstation/tgstation/pull/64174
    https://github.com/tgstation/tgstation/pull/74299

# Spriting
  
x5nqQh4L5h

<details>
  <summary> hmmmm </summary>

image

image

image

image

image

image

image

image

image

</details>

closes: **https://github.com/yogstation13/Yogstation/issues/19257**

:cl: Sheets
tweak: tweaked how legion splitting works so it allows sprites, splitting into more little skulls than before
imageadd: added new sprites for all lavaland mobs!
bugfix: tweaks some balloon alerts to be show up correctly
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
These look terrible and incongruous with the rest of the game's sprites

**Comment by Smudged** [comment]
These sprites do bring a breath of fresh air into the game, and I do implore people to give them a try

**Comment by Marmio64** [comment]
i think the sprites look cool but the original sprites still look pretty neat regardless, but I'd prefer the current style of the Necropolis and tendril over the fleshy style that the new sprites seem to go for though im neutral over all.

**Comment by milk-is-cool** [comment]
dont we have a pretty strict guide for sprites or something regarding art style. i also have personal bias cause i never liked how the tg sprites looked.

**Comment by Mantlecrawler** [comment]
IMO these sprites are incredibly bad, and heavily clash with what lavaland should be and its current theme. Legion alone looks more like a cartoon boss than a infectious magic necromancy thing, goliaths look like a pile of flesh? Bubblegum looks like a character from doom, gold grub looks more like a snowman made of gold, why does colossus have a gun? Herald looks like another doom enemy

**Comment by tattax** [comment]
my brother in christ you want to say "bubblegum looks like it's from doom" when the original sprite had that intention in the first place

**Comment by Marmio64** [comment]
I do think the hierophant and Pandora do look pretty cool though and the ash drake looks great too but looks less threatening and smaller, looks like a baby version. Colossus lobster looks pretty dumb though.

**Comment by Moja10** [comment]
Cool shit! I dig it

**Comment by MajManatee** [comment]
No baby ashdrake sprite?
I do think BG looks a bit too bright, but maybe that's just me.
Also seems like colossus is missing the last frame of his animation.

**Comment by cuackles** [comment]
OK so to address some comments, no this shit aint bad, if you are incapable of distinguish between badly made sprites and sprites that are bad u stupid, we do have some relatively strict rules about the art style, but its mostly that doesn't clash or stands out to much in against its surroundings with its surroundings, this ones dont specially cus its a major resprite so it makes most of the most lavaland creatures look with a similar art style, on the note of the moves i will make actual change request a bit later today if i dont forget, but the ones where i think the old ones work better and feel more grounded as their original designs would be colossus and bg, new colossus looks to humanoid, it looses the aberration factor of his lanky arms and being slightly on the uncanny valley of looking humanoid but not enough, the new one just looks monstrous but more human for some reason, the new Bg looks to pink and the extra spikes and horns seems a bit to much for me so it reaches the overburdened mark, new drake i could go for both as both look good, tho i think the new one gets a lot more of an animal feel,  that being said i do agree he looks less imposing due to being a lot closer to the ground, so they loose the imposing factor for more of an animal predating look, legion looks a bit goofy in the new look but only as at max integrity, after being divided it looks a lot more serious, for the normal fauna i like a lot the new goliaths, they look a lot more clear and readable, new tentacle also looks great, legions look good too tho i have to take a closer look at them, what im not a fan of is goldgrub and watchers, making them wider doesn't fit right with me and also watcher looks doesn't fully convince me, also people saying it looks ugly without a further argument on why it does will not be taken into account for my decision to approve/not approve

**Comment by Mqiib** [comment]
Herald kinda looks like just some kind of red gobliny demon dude, not a huge fan of that. Everything else looks cool though. Cuackles may not be a fan of the watchers but I like the new look tbh.

**Comment by Yarinoi** [comment]
yeah no i think _maybe_ lavaland could do with a resprite but not.. not these. no.

this wins an **[EXTREMELY LOUD BUZZER]**/10

**Comment by RG4ORDR** [comment]
These aren't bad.
But holy fuck they literally do not fit the art style at all, animated 2.5 sprites??

**Comment by Necrosium** [comment]
I don't have a problem with those being added in at all, they look vivid imo

**Review by MajManatee — CHANGES_REQUESTED** [review]
please document all of the other minor changes you made.

**Comment by neeshacark** [comment]
they stick out a lot, but that's fine imo. the only ones i dislike are ash drake and colossus. colossus only because he has a gun???

i dont like the gat but hes cool besides

**Comment by tattax** [comment]
> please document all of the other minor changes you made.

all the other changes are non player facing except for the legion one

and the other one just corrects some balloon alerts that were setup incorrectly

**Comment by Mqiib** [comment]
> they stick out a lot, but that's fine imo. the only ones i dislike are ash drake and colossus. colossus only because he has a gun???
> 
> i dont like the gat but hes cool besides

The crusher trophy from the colossus is called "blast tubes" because its right arm is actually a bunch of barrels. Its arm IS a gun.
image

**Comment by ToasterBiome** [comment]
reopen when cuackles does stuff on here

**Pull request closed without merging**
