### PR TITLE
Makes donkpocket boxes on Box station into random spawners

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Replaces all donkpocket boxes on Box Station, and all its bar/kitchen variants, and the mining base, with random donkpocket box spawners. Makes the new flavored pockets more available in general.

Also gives sec a random donkpocket box and a microwave

screenshots of the new donkpocket boxes (and new microwave for sec) in action
ss (2022-07-12 at 05 19 41)
ss (2022-07-12 at 05 21 33)
ss (2022-07-12 at 05 22 30)
ss (2022-07-12 at 05 23 26)
ss (2022-07-12 at 09 19 25)

Also adds a random donkpocket spawner to the Mining Base kitchen.

# Wiki Documentation

Wiki screenshots of the kitchen, security office, virology lab, and telecommunications needs to be brought up to date in general, but also with this PR if it is merged

# Changelog

:cl:  
rscadd: Box Station: adds a box of randomized donkpockets and a microwave to the security office
tweak: Box Station: Basic donkpocket boxes in the mining base, kitchen, virology, and tcomms have been replaced with randomized donkpocket boxes
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Too many also the sec microwave is in a bad place :(

**Comment by VaelophisNyx** [comment]
Where would you put it then?
Also the quantity in sec specifically or in general? I added 4 to the kitchen so they don't roll bad and get one honkpocket box only, so we can see some variety from chefs; and 2 to tcomm and viro for similar reasons.

**Comment by N3D6** [comment]
> Where would you put it then?
> Also the quantity in sec specifically or in general? I added 4 to the kitchen so they don't roll bad and get one honkpocket box only, so we can see some variety from chefs; and 2 to tcomm and viro for similar reasons.

Perhaps by the trashcan, is my 2 cents

**Comment by VaelophisNyx** [comment]
oh the disposal chute
I had considered that; guess I can do it

**Comment by Marmio64** [comment]
Too many donk pockets in general, too much free, filling, and accessible food right off the bat, when donk pockets are supposed to tie people over while service makes food, not be the main course

**Comment by VaelophisNyx** [comment]
thing is honestly, donk pockets aren't even that filling
and if they're set to random spawners but left as single boxes there's entirely the chance you get a type that is unpalatable to you (see: Lizard Tcomm agent)

**Comment by VaelophisNyx** [comment]
Besides, its rare that the kitchen actually makes any real food, instead of fried messes and deep fried monkey steaks. I don't think the amount of donk pockets laying around is that bad

**Comment by Marmio64** [comment]
> thing is honestly, donk pockets aren't even that filling and if they're set to random spawners but left as single boxes there's entirely the chance you get a type that is unpalatable to you (see: Lizard Tcomm agent)

That would be more interesting, since then they may be assed to get up and maybe exchange it with some one else.

**Comment by VaelophisNyx** [comment]
Come on dude, you know that won't happen
they'll just buy four bags of jerky instead

the only people who get round-start donk pockets are: miners, chefs, virologist, telecomms agents, and now sec. And I guess maintainence crawling greytiders since it's in the maint loot pool

**Comment by VaelophisNyx** [comment]
^ this commit also moves the microwave, forgot to mention

**Comment by GraveHat** [comment]
Don't forget to show the mining base donk screenshot and update the changelog.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Too many boxes everywhere. No place should have more than one box except Kitchen.

Further removes Cook's position in the station.

As per the "ohh but what if you get a really sucky one", you could always ask one of our very good spriters to make a "variety pack" sprite and have random ones in there. That would be interesting I think.

**Comment by VaelophisNyx** [comment]
> Too many boxes everywhere. No place should have more than one box except Kitchen.

But *why* is my question. This reeks of "because it was always that way"

> Further removes Cook's position in the station.

I disagree, the cook is still useful to 85% of the crew. This just makes lowpop more bearable and highpop relatively unaffected.

> As per the "ohh but what if you get a really sucky one", you could always ask one of our very good spriters to make a "variety pack" sprite and have random ones in there. That would be interesting I think.

I mean sure, I'd love that, but actually getting one of them to do it without money is the hard part

**Comment by VaelophisNyx** [comment]
screenshots aren't updated because I;m fucking tired, but I reduced it to 1 random spawner everywhere but the kitchen

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Too many in the kitchens still, 2 max

**Comment by VaelophisNyx** [comment]
this will be the painful one. That's a *lot* of maps to reopen and edit

**Comment by VaelophisNyx** [comment]
Done, screencaps remain unupdated*

**Review by ToasterBiome — APPROVED** [review]

**Comment by JamieD1** [comment]
Maybe this? 
image

**Comment by VaelophisNyx** [comment]
swap the guns and bomb, and the microwave? I can do that yeh

**Comment by VaelophisNyx** [comment]
why do you conflict NOW
god I hate byond mapping code

**Comment by VaelophisNyx** [comment]
time to get to redo this again because tiny shit keeps getting merged 👍

**Comment by VaelophisNyx** [comment]
....

**Pull request merged**
