### PR TITLE
Moves several APCs into Maintenance or into their rooms.

### PR DESCRIPTION
**Pull request by alao3alao3**
# General Documentation

# Intent of your Pull Request

Move several APCs out into maintenance (or in on one occasion) in accordance with how all the other APCs are.
The following departments are affected:
Cryopod Room
Vacant Commisary
Mining Dock
Construction Area
Morgue
Mech Bay
Dormitory Bathroom
Incinerator (APC moved into the incinerator room on the basis that Incinerator is now a part of Atmos and is therefore secure)

Note: Rooms with Techfabs have their APCs inside them regardless of whether there is appropriate maintenance to put it in (See service Techfab room) so Medbay Storage Room's APC remains inside of it.

# Why is this change good for the game?

Uniformity, so anyone who needs to find the APC knows where to look instead of it arbitrarily being inside the damn room or outside for no reason.

# Wiki Documentation

Images for the above mentioned departments may need to be changed.

# Changelog

:cl:  
rscadd: Adds APCs into rooms or into maintenance 
rscdel: Removes APCs from said rooms or respective maintenance  
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
APCs are hard to fix and comparatively easy to break. Its annoying to have to fix 50 apcs in maint because someone with a high damage weapon was bored

**Comment by alao3alao3** [comment]
we'd have to move all the APCs into their respective rooms, since they're all ass to fix. As safer as it is to just have it in the rooms, it goes against the uniform to just have some of them inside their rooms and some of them out.

**Comment by Jarod1200** [comment]
Not sure how I feel about this since its a massive buff to slings, blood cult, and others

**Comment by patpol4** [comment]
While this is good for uniformity and makes sense to have a power thing in maint, there remains the issue of apc's being really easy to destroy, and hard(lengthy) to rebuild. I would be ok with this if apc's were buffed(?) somehow.
But right now, moving some of those to maint would mean technically buffing some antags which im not sure is a good thing.

Also, no point in moving some of those out of maint in a uniformity pr

**Review by patpol4 — CHANGES_REQUESTED** [review]
Just don't touch medbay for now due to how important but at the same time easy to break these apc's would become.

Don't move the ones in central maint since it would make it empty and pointless.

For mech bay, just move the atmos alarm up and place the apc behind the console, it's not pretty but it's better then putting it in a different room.

The rest should be fine

**Comment by JamieD1** [comment]
I have been fighting to have apcs moved into rooms for the past 6 months.

**Comment by alao3alao3** [comment]
isn't/shouldn't central maint just be useless, it should serve as just an entry point for MULE bots. Given how all secure places with reinforced walls have APCs inside of them, bridge shouldn't be different. Or is this one of those "allows for more antag play" clauses or some shit lmao.

**Review by patpol4 — CHANGES_REQUESTED** [review]
>Or is this one of those "allows for more antag play" clauses or some shit lmao.

Yeah so please move them back

What's up with this
vivaldi_jsHJrAgveN

This isnt a reinforces the tp pr, i get the other rwalls because they are just cosmetic fixes but this needs to be atomized if you want to pr it
vivaldi_CAMunWRJwL

**Comment by alao3alao3** [comment]
what the hell?

**Comment by alao3alao3** [comment]
alright what the fuck that was one thing

**Comment by Cartlord** [comment]
Consider that people playing preternis might not have maint access tho, and they need APCs to live

**Comment by alao3alao3** [comment]
they'll have to stick to purposely public APCs in halls, or get maint access if they know whats good for them. APCs were never designed to be available for IPCs to eat out of and players playing that race should recognize and play bearing that risk in mind.

**Comment by alao3alao3** [comment]
See #11226
and they said there's no reason to make a whole nother PR over some conflicts

**Pull request closed without merging**
