### PR TITLE
Adds hitscan laseser variants

### PR DESCRIPTION
**Pull request by ToGWtF**
### Intent of your Pull Request

Adds hitscan variants to normal lasers.

### Why is this change good for the game?

because I want to see what its like

### What should players be aware of when it comes to the changes your PR is implementing?

lasers go pew

### What general grouping does this PR fall under? 

completely changes the balance of the game

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 

guns do less damage

# Changelog

:cl:  
rscadd: Added hitscan variants of laserguns
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Would disablers also get the hitscan mode?

**Comment by maxion12345** [comment]
what, no, no no no no

**Comment by Hopekz** [comment]
I remember this when I played on VG, wasn't a big fan.

I'm fine with this being test merged for others to see, but I already have experience with this, and it doesn't really work too well besides being "cool."

Main problems:
- Doesn't work in the real world with lag. The laggier the game gets, the easier it is to kill someone since you can click slower-moving people easier (no "dodging" with high time dilation)
- Hitscan weapons are always better than projectile weapons, which will definitely affect balance in things like nuke ops.
- Codebases with hitscan weapons have more problems with aimbots since now you can click on people to hit them vs you having to guide a projectile to someone (account for their movement). People using aimbots are usually indistinguishable from lag in ss13 when it comes to hitscan weapons

**Comment by Tipy1802** [comment]
Would be interesting to try out, if it sucks we can revert it, worth a test merge at least

**Comment by ToGWtF** [comment]
I didnt even touch the regular guns I just added admin-spawnable variants

**Comment by Hopekz** [comment]
> I didnt even touch the regular guns I just added admin-spawnable variants

Oh. Well, make it replace the regular ones; otherwise, what is the point.

**Comment by ghost** [comment]
God help you all.

**Comment by Xoxeyos** [comment]
No thanks, I've seen hit scan weaponry in SS13 and I am not interested.

**Comment by Tipy1802** [comment]
Considering it's admin only I see no harm

**Comment by Smudged** [comment]
> I remember this when I played on VG, wasn't a big fan.
> 
> I'm fine with this being test merged for others to see, but I already have experience with this, and it doesn't really work too well besides being "cool."
> 
> Main problems:
> 
> * Doesn't work in the real world with lag. The laggier the game gets, the easier it is to kill someone since you can click slower-moving people easier (no "dodging" with high time dilation)
> * Hitscan weapons are always better than projectile weapons, which will definitely affect balance in things like nuke ops.
> * Codebases with hitscan weapons have more problems with aimbots since now you can click on people to hit them vs you having to guide a projectile to someone (account for their movement). People using aimbots are usually indistinguishable from lag in ss13 when it comes to hitscan weapons

Even then it "kinda" works on VG with how slow it is

Yogs, even with its slow speed is still too fast for hit scan weapons to work

**Comment by alexkar598** [comment]
Stale I suppose

**Pull request closed without merging**
