### PR TITLE
Revert "Stops Supermatter Shards being spawned in the bluespace locker.."

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#17463

Reverts https://github.com/yogstation13/Yogstation/pull/17463 because it was a selfmerged change nobody wanted

### CODE REVIEW

**Comment by JamieD1** [comment]
Find a different solution if you dont like the one I came up with.

**Comment by ThatLing** [comment]
Delete the SM if it delams in BS locker. Allows people to make SM engines but prevents people from cheesing by spawning anomalies

**Comment by Cartlord** [comment]
Jamie, please explain why an anomaly-filled bluespace locker is bad.
I understand it lets you kill dudes instantly by shoving them in, but also consider: it's a massive pain in the ass to set up, you need to make a compact supermatter setup that still doesn't delaminate while maintaining high enough energy to produce anomalies, you need to actually GET a supermatter shard from Cargo, AND anyone you want to kill with this will see you running at them with a suspicious locker - and all that on TOP of you actually needing to FIND the damn locker in the first place!

**Comment by JamieD1** [comment]
> Jamie, please explain why an anomaly-filled bluespace locker is bad. I understand it lets you kill dudes instantly by shoving them in, but also consider: it's a massive pain in the ass to set up, you need to make a compact supermatter setup that still doesn't delaminate while maintaining high enough energy to produce anomalies, you need to actually GET a supermatter shard from Cargo, AND anyone you want to kill with this will see you running at them with a suspicious locker - and all that on TOP of you actually needing to FIND the damn locker in the first place!

LOL WHAT? You call the beacon and throw a crowbar at it and run away? HELLO?

**Comment by Cartlord** [comment]
I have a hard time believing that a supermatter shard will maintain anomaly levels of energy without delaminating in standard room atmos, and even if that's true and I just don't remember how they work, this still necessitates breaking in to Cargo (difficulty varies by shift), stealing the board for a supply drop pod computer, stealing everything else you need to build one, SOMEHOW getting auth on the one you made (remember, they need quartermaster access to work!), making a beacon, _finding the bluespace locker_, placing the beacon IN that locker, getting back to wherever you built your console, ordering a shard to that beacon, getting back to the locker, activating the shard, and hoping you can shove someone in - y'know, despite them seeing you running at them with a locker - AFTER the anomalies start and BEFORE it blows up.

**Comment by Cartlord** [comment]
Reposting this from Discord so I can get more opinions:
...I feel like the obvious solution [to shards being on fire and lasting ten minutes before delamination] is just to make shards less hardy, then, so that such a setup can't last nearly as long - that, or remove those beacons so people actually have to DRAG a shard (or crate) all the way over to the locker for their setup, since that makes this much more noticeable.
If you feel neither of these is a good solution, you could also make the beacon Bulky with a distinctive sprite, so you can't bring it anywhere without people noticing

**Comment by JamieD1** [comment]
Code doesnt actually do anything, people are stupid

**Comment by JamieD1** [comment]
Fuck it, you can all die to the Supermatter in the Locker, See if I care.

**Comment by Maia-J** [comment]
> Fuck it, you can all die to the Supermatter in the Locker, See if I care.

jamiesm

**Pull request merged**
