### PR TITLE
Cause there's magic in my bones

### PR DESCRIPTION
**Pull request by Moltijoe**
Wounds are a big part of combat, makes wound immunity slightly more special for species

Podpeople have insane passive healing
Polysmorph have innate wound resistance anyways

Ethereals are just bad and are sorta squishy thematically

Also deletes redundant podpeople file as it creates confusion

:cl:   
tweak: Podpeople and Polysmorph have bones
tweak: Ethereals don't have bones
/:cl:

### CODE REVIEW

**Review by ToasterBiome — COMMENTED** [review]
>races should be unique

>adds bones to two races

classic

**Comment by wonderinghost** [comment]
Aren't xenomorphs based off of ants. If so then this is a blunder for they have a exoskeleton instead of bones

**Comment by Moltijoe** [comment]
> Aren't xenomorphs based off of ants. If so then this is a blunder for they have a exoskeleton instead of bones

they ALSO have a skeleton decal in the game for some reason
also this
image

**Review by ToasterBiome — APPROVED** [review]
i hate you

**Pull request merged**
