### PR TITLE
Brings back darkspawn as a roundstart antag with a low weight

### PR DESCRIPTION
**Pull request by Moltijoe**
just increases the weight to 1 so they can maybe show up and properly get maintained (most likely by me(why do i do this to myself?(i did it with the battle royale mode, but why?)))

"they're bugged"
what are the bugs? they've been disabled so long that no one seems to remember.

"they're unbalanced"
that's a matter of time and effort to fix, which will never happen so long as they're disabled

:cl:  
tweak: brings back darkspawns at a low % chance round start
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
YOU WERE THE CHOSEN ONE, HOW COULD YOU DO THIS TO ME

**Comment by Therandomhoboo** [comment]
Only bug I know was something to do with lighting. But even then, I don't even think it was a massive issue cause they were fine whenever I saw/played them.

Only unbalanced part was the fact that crew could get glowy and fuck everything over but that got fixed by letting darkspawn temp disable them. (not sure about shadowlings though) So yeah I dont know why they got disabled in the first place.

**Comment by Moltijoe** [comment]
i could always just bring back one or the other, to more properly focus on it
any preference?

**Comment by wonderinghost** [comment]
Can't wait for bitching about dspawn thralls having night vision but slings dont

**Comment by Hislyna** [comment]
> i could always just bring back one or the other, to more properly focus on it any preference?

Whichever one dies the most pls thx xoxox

**Comment by Moltijoe** [comment]
> Whichever one dies the most pls thx xoxox

ah, so gus level feedback, ty

**Comment by Hislyna** [comment]
> > Whichever one dies the most pls thx xoxox
> 
> ah, so gus level feedback, ty

Jokes aside, just see how both are ig, see how it is, worst comes to worst, they get disabled again

**Comment by Moltijoe** [comment]
> Jokes aside, just see how both are ig, see how it is, worst comes to worst, they get disabled again

i hope it doesn't come to that, but i suppose that's always an option

**Comment by wonderinghost** [comment]
Why not merge the two. They got aspects to each.

Could probably help balance it

**Comment by Therandomhoboo** [comment]
> Why not merge the two. They got aspects to each.
> 
> Could probably help balance it

What is actually unbalanced about them though?

This is what confuses me, I don't know what is "unbalanced" about them.

**Comment by Moltijoe** [comment]
> This is what confuses me, I don't know what is "unbalanced" about them.

same, that's why i'm bringing them back, to find out

**Comment by wonderinghost** [comment]
> > Why not merge the two. They got aspects to each.
> > 
> > Could probably help balance it
> 
> What is actually unbalanced about them though?
> 
> This is what confuses me, I don't know what is "unbalanced" about them.

One is a speed runner with shittier thralls while the other isn't as fast but has better thralls

**Comment by Therandomhoboo** [comment]
> 

That still doesn't answer how that is unbalanced? They're both technically speed runners since they're objective is to take over the station pretty much (Shadowling (I think??) has ascension but it is still pretty much the same)

**Comment by wonderinghost** [comment]
Counterpoint. Slings know Kung Fu and can fling themself across station.

Shadow people do not have this luxury

**Comment by Therandomhoboo** [comment]
> Counterpoint. Slings know Kung Fu and can fling themself across station.
> 
> Shadow people do not have this luxury

Darkspawn can snuff lights out & stun people without having to spend points. There are perks and cons to them.

That, to me is like saying. Traitors get TC and uplinks, but BB's don't have that luxury and then removing them both. 

Could you actually tell us what is genuinely unbalanced about them? Cause to me, it seems like it is a personal preference and not that they're unbalanced.

**Comment by wonderinghost** [comment]
How about you get your head out of your ass and recollect

How many times have you seen sling wins then shadow wins

Slings usually win the most then shadow people. Because of their abilities. There isn't really a point to thrall people as a sling.  Because they can get 3 different abilities by eating souls and can fly across the station doing flips. Even in space
Their thralls also get shafted as they don't get anything but a big telling sign

Shadow people are more teathered to the station and require converts. Who's thralls have actual abilities but with a very miniscule tell

Shadow people are also harder to destroy without a mech or a cremator. And you can't remove their organs

**Review by ToasterBiome — APPROVED** [review]
better to face it and fix it then have it perpetually disabled

**Comment by Therandomhoboo** [comment]
> How about you get your head out of your ass and recollect
> 
> How many times have you seen sling wins then shadow wins
> 
> Slings usually win the most then shadow people. Because of their abilities. There isn't really a point to thrall people as a sling. Because they can get 3 different abilities by eating souls and can fly across the station doing flips. Even in space Their thralls also get shafted as they don't get anything but a big telling sign
> 
> Shadow people are more teathered to the station and require converts. Who's thralls have actual abilities but with a very miniscule tell
> 
> Shadow people are also harder to destroy without a mech or a cremator. And you can't remove their organs

Your points are poor, your takes are bad and you should feel bad about them both.

The "BIG TELL" sign can be subverted by wearing anything that covers the eyes or face. Only time it gets outed is when people metaknowledge the antag. This also applies to bloodsuckers (certain class) so that is a really moot point.

The thrall part really doesn't say anything about them being unbalanced, so I don't get what you're waffling on about. And slings can't go into space, it actually stops them.

Shadow people aren't harder to destroy, one fire slug or any light renders them useless.

Can you actual provide any hint of "unbalanced" to them instead of just having a personal dislike to them.

**Comment by wonderinghost** [comment]
Tell me have you ever performed surgery on a shadow person. Have you ever done surgery on a sling?

Shadow people do a aoe when you try to remove their brain and it doesn't do it. Slings you can do whatever with

Even then what happens when they are no longer exposed to light

Slings have etchings all over the body that you can't hide
Shadow people have shadowy eyes but you can just wear eye protection 

And why the hell do you come in to antagonize. Weve been through this before with you going l plus ratio without providing anything while I'm trying to provide shit

**Comment by Mantlecrawler** [comment]
From what i've seen admin side on _certain_ dynamic rounds, Slings are unable to hatch, their hivemind doesn't work, and veil still doesn't work. Since they cant hatch i don't know any other bugs beyond that. Dspawn seem to work fine, as does nightmare (bring it back as a midround)

**Comment by RG4ORDR** [comment]
Nightmare AFAIK is still a midround - it only reworks be the nightmare has like 3 conditions it follows.
Is it dark? - Heal,Revive, teleport.
Is it light? - Die
Is it a lightsource and/or hostile? - Armblade.

Nightmares dont have to convert, just survive. They're also in possesion of extremely robust armblades that eat any lightsource on a person.

**Comment by Hislyna** [comment]
> Nightmare AFAIK is still a midround - it only reworks be the nightmare has like 3 conditions it follows. Is it dark? - Heal,Revive, teleport. Is it light? - Die Is it a lightsource and/or hostile? - Armblade.
> 
> Nightmares dont have to convert, just survive. They're also in possesion of extremely robust armblades that eat any lightsource on a person.

Nightmares are admin only spawns atm no? I love em, they should be reenabled if anything

**Comment by Moltijoe** [comment]
Sounds like its mostly shadowlings that are bugged.
Since some people also just hate their design i'll leave them disabled until i can get time to completely rework them.

**Comment by MajManatee** [comment]
The darkest timeline... We should just purge both shitty "dark" antags from the game.

**Pull request merged**
