### PR TITLE
Fixes door remotes on yogsmeta and asteroid

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
fixes door remotes not unbolting secure tech storage on meta and asteroid

# Changelog
:cl:  
mapping: fixed door remotes for yogsmeta and asteroid
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
ignore the weird commits github was being weird

**Comment by Aquizit** [comment]
Can you check Gax's secure tech storage door just to make sure that one is also set to 76?

**Comment by adamsong** [comment]
> ignore the weird commits github was being weird

Don't use your master branch for prs

**Review by Aquizit — APPROVED** [review]
I checked myself, Gax is already set correctly.

**Comment by azzzertyy** [comment]
> > ignore the weird commits github was being weird
> 
> Don't use your master branch for prs

it wasnt, it was on branch "storage-fix" but that was being weird so i had do some cloning trickery and junk to fix it, hopefully when all my prs are closed/merged ill be able to fix the root cause but for now this will have to do

**Pull request merged**
