### PR TITLE
Fix talking bug

### PR DESCRIPTION
**Pull request by ghost**
Fixes the talking radio bug thing

:cl:  
bugfix: fixes the radio talking bug thing
/:cl:

### CODE REVIEW

**Comment by Fillywonk** [comment]
Is this the one where you hear it twice?

**Comment by Amelia0010** [comment]
lol

**Comment by ghost** [comment]
This is the one with a null in player_list causing speech to go wack and only go through radio headsets.

**Comment by Amelia0010** [comment]
what even is upstreaming fixes lol

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
PR it upstream

**Comment by ThatLing** [comment]
This code isn't good enough for upstream

**Comment by Amelia0010** [comment]
lol

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
They'll help him make it better

**Comment by Amelia0010** [comment]
lol

**Comment by ThatLing** [comment]
They won't, oranges will just say some meme shit and close it

**Comment by Amelia0010** [comment]
lol

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
And someone competent will pick it up

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
two headcoders were a mistake

**Comment by Amelia0010** [comment]
lol

**Comment by ThatLing** [comment]
wanna fire eachother?

**Comment by Amelia0010** [comment]
lol

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Gladly

**Comment by Amelia0010** [comment]
lol

**Comment by ThatLing** [comment]
Come at me bro

**Comment by Amelia0010** [comment]
lol

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
ur mom

also thanks was about to shut nich up

**Comment by simonset55** [comment]
lol

**Comment by ThatLing** [comment]
i'm not the one that bussed so hard HC powers got limited

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
At least it was more fun than being turned into a catgirl

**Comment by ThatLing** [comment]
what?

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
yeah

**Comment by ThatLing** [comment]
what kind of argument was that

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
as dumb as this whole argument

**Comment by ThatLing** [comment]
this isn't an argument

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
we're arguing whether this should be PRed upstream or here

**Comment by ThatLing** [comment]
is this even an issue upstream

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I can't think of anything we added that would cause this but let me check

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
screw it I'll just resolve the conflict if they fix this

**Pull request merged**
