### PR TITLE
Add polysmorph to HOS whitelist

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

They look cool in sec gear and thematically appropiate
# Spriting

# Wiki Documentation

Polysmorph can play HOS
# Changelog

:cl:  
tweak: Add polysmorph to HOS whitelist
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Dumbfuck

**Comment by Simplehorror** [comment]
> Dumbfuck

fuck is your problem

**Comment by 00ze-cyclone** [comment]
You

**Comment by Simplehorror** [comment]
stop testing your brain damage gun on yourself

**Comment by bruhlookatthisdood** [comment]
why did you just create this to close it

**Comment by Simplehorror** [comment]
i remembered how hos needs to be balanced as a human and they have laser weakness

**Pull request closed without merging**
