### PR TITLE
Ports cock and ball torture from TG

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Allow to kick dudes in their groin to apply a negative mood effect. Ported from TG with some balance changes from me.

https://github.com/tgstation/tgstation/pull/65399

# Changelog

:cl: Pickle-Coding, SuperSlayer
rscadd: You can now kick people into their groin for a mood debuff
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
why is the blob overmind file changed

this is stupid

**Comment by ghost** [comment]
> why is the blob overmind file changed
> 
> this is stupid

Because I had a very bad time with my repository, that killed two PR's that I could made and also left this shit with the overmind file, that I dont know how to fix

**Comment by Marmio64** [comment]
Almost no one uses mood and I'm not sure you'd want to further make it worse by allowing shitty greytiders to click you once to inflict a bunch of mood damage.

**Comment by ghost** [comment]
> Almost no one uses mood and I'm not sure you'd want to further make it worse by allowing shitty greytiders to click you once to inflict a bunch of mood damage.

I can decrease the time of mood event duration or mood decreasement if it is too much

**Pull request closed without merging**
