### PR TITLE
Tech shells are now roundstart & available at hacked autolathes

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Tech shells are difficult to craft as is (as they should be), placing them behind arbitrary science timelocks (as if science would research them anyways lol) and restricting them to security and science(???) makes them stupidly rare and hard to obtain, to the point where you may as well not try due to out-of-control factors.

Crafting recipes for reference

Pulse Slug Shell: 1 unloaded technological shell, 2 advanced capacitor, 1 ultra-high-power micro-laser 

Dragonsbreath Shell: 1 unloaded technological shell, 5 Phosphorus 

Ion Scatter Shell: 1 unloaded technological shell, 1 ultra-high-power micro-laser, 1 ansible crystal 

FRAG-12 Shell: 1 unloaded technological shell, 5 Glycerol, 5 Fluorosulphuric acid 

Laser Buckshot Shell: 1 unloaded technological shell, 1 advanced capacitor, 2 high-power micro-laser 

Thundershot Shell: 1 unloaded technological shell, 1 super capacitor, 5 Teslium 

Depleted Uranium Slug Shell: 1 unloaded technological shell, 2 uranium, 2 metal rod, 5 Thermite 

Cryoshot Shell: 1 unloaded technological shell, 5 Rhigoxane 

# Changelog

:cl:  
tweak: Technological shells are no longer locked behind research and are also now available at hacked autolathes
/:cl:

### CODE REVIEW

**Comment by DylonBR** [comment]
so fucking based. actually enabling stuff to be used

**Comment by TheRyeGuyWhoWillNowDie** [comment]
i had a small heart attack because i thought you were finally off your rocker enough to put finished and completed frag-12 shells in autolathes

**Comment by ChuChu42** [comment]
remove pulse slug
reason: 40 damage reinf wall destroying laser
gives you third degree burns once you get shot
usually resticted to deathsquad and its not very balanced.

**Comment by 00ze-cyclone** [comment]
> remove pulse slug
> reason: 40 damage reinf wall destroying laser
> gives you third degree burns once you get shot
> usually resticted to deathsquad and its not very balanced.

Don’t worry it isn’t that OP compared to the other techshells, the thing that worry me is how the fucking pulse isn’t even the best thing tech shells can provide, it could be fine or we could behold a new era of shotgun dominating existence even harder than before.

**Review by ToasterBiome — APPROVED** [review]

**Comment by Moja10** [comment]
Fucking roundstart frag 12, also this needs discussion on rules effects because if it's available roundstart, can the warden start immediately crafting a billion frag 12 if he gets the chems. my brain fried from just waking up but please consider le rules applications

**Comment by ynot01** [comment]
> if it's available roundstart, can the warden start immediately crafting a billion frag 12 if he gets the chems.

Consider whether he can do this once it's researched and you have the same question without this PR

**Comment by Moja10** [comment]
also while you are at it, mind putting the syringe gun back in medical storage k thanks

**Comment by UltraBigRat** [comment]
> Fucking roundstart frag 12, also this needs discussion on rules effects because if it's available roundstart, can the warden start immediately crafting a billion frag 12 if he gets the chems. my brain fried from just waking up but please consider le rules applications

consider that frag 12 needs glycerol, which would mean the cooperation of both botany and chem, which is gonna be a pretty damn rare occurance that would only really happen if the crew have a reason to start powergaming hard. Im quite sure there is no tech shell that can be acquired without using chem or another protolathe. This really isnt that unbalanced on the sec side.

**Pull request closed without merging**
