### PR TITLE
Changes lizard hiss and increases staff, mentor, and donor retention by allowing felinids to hiss.

### PR DESCRIPTION
**Pull request by ReddicusDragon**
# Document the changes in your pull request
Felinids can hiss now.
[Sounds are here](https://drive.google.com/drive/folders/1Fi-jWWAcvnY3qsScXzDassCiSZXnszIj?usp=sharing)
# Wiki Documentation
Hiss now also works as a felinid
# Changelog
:cl:  
rscadd: Felinids can now hiss.
tweak: Lizard hiss sound changed.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
> [Sounds are here](https://drive.google.com/drive/folders/1Fi-jWWAcvnY3qsScXzDassCiSZXnszIj?usp=sharing)

**Comment by ynot01** [comment]
Yogs will be rich

**Comment by 00ze-cyclone** [comment]
Yog is dying, its requiem is sung by catgirls meowing while they feast on its corpse.
Lizard weep, their kin having been overthrown in the degeneracy cursed kingdom.
This hatred toward sanity, humanity and god.
Speedmerge that crime NOW!!

**Comment by MajManatee** [comment]
im OK with this, as long as any cat person that hisses at me becomes valid and I can blow them away.

**Comment by ReddicusDragon** [comment]
it won't be phoron, but instead catgirls
https://www.youtube.com/watch?v=4goUdEQ5ifA

**Comment by Hopekz** [comment]
> Yog is dying,

This will save Yog

**Comment by ThatLing** [comment]
Please give them brain damage every time they hiss/purr

**Comment by ReddicusDragon** [comment]
> Please give them brain damage every time they hiss/purr

no

**Comment by TheBombMakerJL** [comment]
we can have this but not foxpeople? 1984

**Comment by JamieD1** [comment]
what the fuck, no

**Comment by ToasterBiome** [comment]
24 hours

**Comment by ReddicusDragon** [comment]
> what the fuck, no

Hisa requested this be added, you're telling me you want to alienate staff?

**Comment by Hopekz** [comment]
> Hisa requested this be added, you're telling me you want to alienate staff?

Weird argument.
Alienate staff by not allowing people to hiss and purr?
Does this mean we should now add everything that is proposed by staff without question?

If "alienating" staff is a primary reason for this existing the staff that feel alienated by us not being a furry codebase should just join one of the other furry codebases imo since there's lots of options available for that.

**Comment by MajManatee** [comment]
> > what the fuck, no
> 
> Hisa requested this be added, you're telling me you want to alienate staff?

Hisa asked for my 40k pr that took like 2 weeks to make and that got shutdown. Cant have everything you want.

**Comment by ReddicusDragon** [comment]
> > > what the fuck, no
> 
> > 
> 
> > Hisa requested this be added, you're telling me you want to alienate staff?
> 
> 
> 
> Hisa asked for my 40k pr that took like 2 weeks to make and that got shutdown. Cant have everything you want.

Jamie said it's fine if I got rid of purring

**Comment by MajManatee** [comment]
why change lizard hiss?

**Comment by ReddicusDragon** [comment]
> why change lizard hiss?

Jamie disliked the rattle

**Comment by MajManatee** [comment]
should you... put that in a seperate pr?

**Comment by ReddicusDragon** [comment]
> should you... put that in a seperate pr?

jamie said toss it in here

**Comment by MajManatee** [comment]
also "Jamie disliked the rattle" 
jamie is a silicon main, why does he care about how the lizard hiss sounds??

**Comment by ReddicusDragon** [comment]
> also "Jamie disliked the rattle" 
> 
> jamie is a silicon main, why does he care about how the lizard hiss sounds??

Ask him yourself.

**Comment by JamieD1** [comment]
> also "Jamie disliked the rattle" jamie is a silicon main, why does he care about how the lizard hiss sounds??

its a fucking rattlesnake

**Pull request merged**
