### PR TITLE
jellypeople ce/rd/cmo

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

I might give them hop later but I doubt it their lore still isn't final and I don't care about them

I will die before these little shits get hos

Why did we need them

Who plays them

Why

Why

Why

# Wiki Documentation

Where's the jellyperson page?!

# Changelog

:cl:  
experimental: JELLYPEOPLE GET TO BE HEADS OF STAFF I GUESS?????
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
5 BTC in my wallet rn or we're doing human only heads again

**Comment by Therandomhoboo** [comment]
I want my jelly people lore, i want the jelly people love.

**Comment by Skrem7** [comment]
> 5 BTC in my wallet rn or we're doing human only heads again

better idea we revert jellypeople

better better idea we remove all jelly species

**Comment by solwashere** [comment]
> > 5 BTC in my wallet rn or we're doing human only heads again
> 
> better idea we revert jellypeople
> 
> better better idea we remove all jelly species

I agree

**Comment by Therandomhoboo** [comment]
You guys mad because Jelly people will become the new meta. 

That's it, im writing jelly people lore and making it so they are political overlords

**Comment by Moltijoe** [comment]
> I will die before these little shits get hos
> 
> Why did we need them
> 
> Who plays them

jamie said "we need more species"
I saw jellypeople and thought "eh, least work"
I can never atone for my sins that day, the balance implications of them existing is reason enough to hate them

**Comment by MajManatee** [comment]
Irrelevant since #18864 was approved. Re-open if that changes.

**Pull request closed without merging**
