### PR TITLE
Revert "Adds monkey gamemode V3"

### PR DESCRIPTION
**Pull request by Amelia0010**
Reverts yogstation13/Yogstation#7934

image

### CODE REVIEW

**Comment by swissloaf** [comment]
no

**Comment by Takahiru** [comment]
essential

**Comment by Hopekz** [comment]
Lazy PR.
You left most of the out of rotation game modes so this doesn't even accomplish what you set out to do.

**Comment by Amelia0010** [comment]
I set out to remove monkey. Alexkar wanted to remove all the other ones. Reading ain't your strong suit, is it?

**Comment by Moja10** [comment]
this is a violation of staff rights to waste players time for an hour with nonfunctional modes

**Comment by alexkar598** [comment]
Out of rotation gamemodes can remain in the codebase for now with absolutly NO support in terms of issues, all bug reports regarding them will be immediatly closed

**Pull request closed without merging**
