### PR TITLE
REAGENT STATES, NEW CHEMS, FORGE STUFF MY GOD SO MUCH THINGS PROPER CREDIT EDITION!

### PR DESCRIPTION
**Pull request by fluffe9911**
CREDITS: Fluffe9911 for porting, banthebantz for coding all this amazing stuff (like holy cow), GuyonBroadway for fixing bans original Reagent Material PR, yoyobatty for maintaining it so its not broken as heck and Jujumatic for the neat fire extinguisher rewrite/mutation toxins please tell me if I missed anyone

🆑 A ton of cool guys
add: Reagent States!
add: New Chems!
add: Reagent Forge to make custom weapons and things!
add: Alot of other things that would be to much to list in here!
/🆑

This is a huge port that ports many things in the goal of getting the reagent forge to be a thing. To see whats in it look at these prs
https://github.com/HippieStation/HippieStation/pull/5756
https://github.com/HippieStation/HippieStation/pull/3480
https://github.com/HippieStation/HippieStation/pull/3043
https://github.com/HippieStation/HippieStation/pull/7670
https://github.com/HippieStation/HippieStation/pull/7357

### CODE REVIEW

**Comment by ThatLing** [comment]
but what does it do

**Comment by fluffe9911** [comment]
Read the changelog and all the pr links at the bottom to see what it does

**Comment by Ratvar** [comment]
atomize whence

**Comment by Nickvr628** [comment]
yeah this needs atomization, stat

**Comment by fluffe9911** [comment]
atomizing this would be a pain in the butt due to the fact the thing I want (the reagent forge relays on things from regeant state and CASS CHEM pr and vice versa) so it is much easier to just have it be put together in one pr

**Comment by Moja10** [comment]
So far from what little I read I like some things and am iffy with others. I could be wrong, will have to look into detail. I've always wanted to have milk extinguishers...

**Comment by fluffe9911** [comment]
one more close to fix a map merge conflict sorry

**Pull request closed without merging**
