### PR TITLE
Buff SM and singulo power gen due to rad nerf and station needing more power

### PR DESCRIPTION
**Pull request by warface1234455**
ok high radiation only gives out few kw while tesla can just shit out 1mw per bolt
people will less likely do singulo because its not efficient as for power generation
One single teg can produce more than 6 rad collectors bombined
Rad was nerfed and hard

# Document the changes in your pull request

Increase SM radmod from 1.1 to 1.5
Added radmod var, defaulted to 50 for singulo and tweaked singulo so it shits more rad, Singulo will be significantly better than tesla after this point. THis will make players feel like singulo is a fucking engine not a shitty solar alike

# Wiki Documentation

Increase SM radmod from 1.1 to 1.5
Added radmod var, defaulted to 50 for singulo and tweaked singulo so it shits more rad, Singulo will be significantly better than tesla after this point. THis will make players feel like singulo is a fucking engine not a shitty solar alike
# Changelog

:cl:  
tweak: Increase SM radmod from 1.1 to 1.5
tweak: Added radmod var, defaulted to 50 for singulo and tweaked singulo so it shits more rad, Singulo will be significantly better than tesla after this point. THis will make players feel like singulo is a fucking engine not a shitty solar alike

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
just make RAD_COLLECTOR_COEFFICIENT whatever the hell it's supposed to be instead of adding in random numbers

**Comment by ToasterBiome** [comment]
SM buff, nerf tesla instead

**Comment by warface1234455** [comment]
> SM buff, nerf tesla instead



> SM buff, nerf tesla instead
SM and tesla is good as it is, its just the rad collector is not good enough

**Comment by ShoziOffical** [comment]
> just make RAD_COLLECTOR_COEFFICIENT whatever the hell it's supposed to be instead of adding in random numbers

Ya ya ya

**Comment by ShoziOffical** [comment]
> > SM buff, nerf tesla instead
> 
> > SM buff, nerf tesla instead

SM and tesla is good as it is, its just the rad collector is not good enough

**Comment by ToasterBiome** [comment]
> > > SM buff, nerf tesla instead
> > 
> > 
> > > SM buff, nerf tesla instead
> 
> SM and tesla is good as it is, its just the rad collector is not good enough

....the SM is going to generate waaaaaaaaaay more power now

**Comment by ShoziOffical** [comment]
> > > > SM buff, nerf tesla instead
> > > 
> > > 
> > > > SM buff, nerf tesla instead
> > 
> > 
> > SM and tesla is good as it is, its just the rad collector is not good enough
> 
> ....the SM is going to generate waaaaaaaaaay more power now

It generates very less currently like 100-300kw for a co2 engine. This pr will make it generate 3x times higher, i tested it with co2 sm engine

**Comment by Bibby0110** [comment]
10x increase???

**Comment by ShoziOffical** [comment]
> 10x increase???

You think that's big but it's actually nothing, currently turbine is better than rad collectors when upgraded to t2-3 also rad collectors gen is way too low 60-90kw for N2 engine, this is not enough for station needs because the power consumption will be higher during midshift

**Comment by ShoziOffical** [comment]
maybe a tm request, so we will see how it affects the round and maybe gets tweaked, but still i tested it in my private server, one rad collector for N2 engine can produce 200kw-400kw

**Review by ReddicusDragon — APPROVED** [review]
with how much ai server racks use in power, this makes sense

**Comment by JamieD1** [comment]
This seems ridiculous.

**Comment by ReddicusDragon** [comment]
Numbers may be weird Jamie, but with the sheer power bibby's server racks pull it may be a necessary PR, even with number changes

**Comment by warface1234455** [comment]
> This seems ridiculous.

Not at all

**Comment by ShoziOffical** [comment]
> > This seems ridiculous.
> 

 Not at all, rad was nerfed hard making collectors not generating enough power for station

**Comment by ToasterBiome** [comment]
> maybe a tm request, so we will see how it affects the round and maybe gets tweaked, but still i tested it in my private server, one rad collector for N2 engine can produce 200kw-400kw

A basic setup should not generate 1.2 - 2.4 MW. Even with the change from 10x to 5x, that's still 600KW to 1.2MW, which I think is still insane for a beginner setup. 

I don't think buffing rad collectors is a good idea at all. Singulo should generate more rads instead if singulo is not keeping up. If the number changes at all I HIGHLY advise instead of a 500% increase, something lower like a 20-25% increase, as this still wildly buffs SM.

**Comment by ShoziOffical** [comment]
> > maybe a tm request, so we will see how it affects the round and maybe gets tweaked, but still i tested it in my private server, one rad collector for N2 engine can produce 200kw-400kw
> 
> A basic setup should not generate 1.2 - 2.4 MW. Even with the change from 10x to 5x, that's still 600KW to 1.2MW, which I think is still insane for a beginner setup.
> 
> I don't think buffing rad collectors is a good idea at all. Singulo should generate more rads instead if singulo is not keeping up. If the number changes at all I HIGHLY advise instead of a 500% increase, something lower like a 20-25% increase, as this still wildly buffs SM.

Since the rad nerf, the rad collectors getting much less rad also tesla already generating over 1mw

**Comment by ShoziOffical** [comment]
> > > maybe a tm request, so we will see how it affects the round and maybe gets tweaked, but still i tested it in my private server, one rad collector for N2 engine can produce 200kw-400kw
> > 
> > 
> > A basic setup should not generate 1.2 - 2.4 MW. Even with the change from 10x to 5x, that's still 600KW to 1.2MW, which I think is still insane for a beginner setup.
> > I don't think buffing rad collectors is a good idea at all. Singulo should generate more rads instead if singulo is not keeping up. If the number changes at all I HIGHLY advise instead of a 500% increase, something lower like a 20-25% increase, as this still wildly buffs SM.

 Since the rad nerf, the rad collectors getting much less rad also tesla already generating over 1mw, also when i tested the collectors dont generate that much power

**Comment by ShoziOffical** [comment]
Ok this should be least not too high and not too low

**Comment by ToasterBiome** [comment]
> > > maybe a tm request, so we will see how it affects the round and maybe gets tweaked, but still i tested it in my private server, one rad collector for N2 engine can produce 200kw-400kw
> > 
> > 
> > A basic setup should not generate 1.2 - 2.4 MW. Even with the change from 10x to 5x, that's still 600KW to 1.2MW, which I think is still insane for a beginner setup.
> > I don't think buffing rad collectors is a good idea at all. Singulo should generate more rads instead if singulo is not keeping up. If the number changes at all I HIGHLY advise instead of a 500% increase, something lower like a 20-25% increase, as this still wildly buffs SM.
> 
> Since the rad nerf, the rad collectors getting much less rad also tesla already generating over 1mw

This is not a valid reason to make all the engines also generate 1mw. You should instead make the tesla generate less.

**Comment by ShoziOffical** [comment]
> > > > maybe a tm request, so we will see how it affects the round and maybe gets tweaked, but still i tested it in my private server, one rad collector for N2 engine can produce 200kw-400kw
> > > 
> > > 
> > > A basic setup should not generate 1.2 - 2.4 MW. Even with the change from 10x to 5x, that's still 600KW to 1.2MW, which I think is still insane for a beginner setup.
> > > I don't think buffing rad collectors is a good idea at all. Singulo should generate more rads instead if singulo is not keeping up. If the number changes at all I HIGHLY advise instead of a 500% increase, something lower like a 20-25% increase, as this still wildly buffs SM.
> > 
> > 
> > Since the rad nerf, the rad collectors getting much less rad also tesla already generating over 1mw
> 
> This is not a valid reason to make all the engines also generate 1mw. You should instead make the tesla generate less.

Baiomu i literally said rad got nerfed, and it generates less than before

**Comment by ToasterBiome** [comment]
> Baiomu i literally said rad got nerfed, and it generates less than before

Explain further please, and providing a PR link would be greatly appreciated.

**Comment by ShoziOffical** [comment]
> > Baiomu i literally said rad got nerfed, and it generates less than before
> 
> Explain further please, and providing a PR link would be greatly appreciated.

- #15112 
- #16154 

Rad collectors  generated less than before due to these prs

**Comment by ShoziOffical** [comment]
SM was already generate over 1mw with co2 engine before

**Comment by JamieD1** [comment]
Change it per engine instead, like I have already if its actually needed.

**Comment by warface1234455** [comment]
Wdym

**Comment by ShoziOffical** [comment]
~~currently testing singulo~~

done testing

**Review by JamieD1 — APPROVED** [review]

**Comment by ShoziOffical** [comment]
bless

**Pull request merged**
