### PR TITLE
Removes saltpetre  from the Biogenerator after it was stealth-added by Majkl-j

### PR DESCRIPTION
**Pull request by Cartlord**
For some reason, https://github.com/yogstation13/Yogstation/pull/18326 added saltpetre to the biogen and the person making it didn't see fit to tell anyone. This removes it.

:cl:    
rscdel: Botany's Biogenerator can no longer make saltpetre.  
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
mutagen has been in the  biogenerator for a long time (#4094) & imo should stay since it's directly related to progression

saltpetre can go to hell though 100%

**Comment by Cartlord** [comment]
editing p.r. now

**Comment by Cartlord** [comment]
okay mutagen's back in

**Comment by Moja10** [comment]
make it cost something stupid like 1000 to 10000 and it would give the late game Biogen something to do

**Comment by Cartlord** [comment]
You massively underestimate the difficulty present in fueling the Biogenerator if you think there's such a thing as a prohibitive biomass cost.

**Comment by Moja10** [comment]
> You massively underestimate the difficulty present in fueling the Biogenerator if you think there's such a thing as a prohibitive biomass cost.

Make it something silly like 100,000 or 1,000,000 then, I am well aware of how much the biogen can store

**Review by ToasterBiome — APPROVED** [review]

**Comment by tattax** [comment]
merge it...

**Comment by Cartlord** [comment]
The core problem with adding saltpetre to the biogenerator is that it's very easy to make underpowered or overpowered - making it prohibitively expensive would effectively require that either Botany spend _the entire round_ building up to get enough to max Potency, at which point the boost is too late to mean anything; making it too cheap means that someone can just get a fuckload of watermelon plants, FILL the biogen with them, then use the resulting saltpetre to make the melons more potent and therefore fill the biogen faster to get even more saltpetre. The best idea I have for it would be to make it absurdly and comically expensive, such that it can only be reasonably obtained by having Sci upgrade the biogen to halve or quarter the mass required... but the effort taken to get Sci to upgrade Botany is greater than the effort needed to walk over to the Chemist and ASK for the damn saltpetre, and really, Sci gains nothing from Botany having saltpetre or stronger plants due to the near-total lack of interaction between the two departments.

**Comment by Rdrazga** [comment]
For reference on current speedrun tactics: It would take around 5 minutes shift time to have a potency 100 plant with this in game as is. This involves being fast at clicking, knowing exactly what plants to get, and using nutriment 20 grass instead of watermelons. Why having potency 100 5 minutes in is bad: Potency 100 death nettle on the FIRST harvest (normally takes a long time to grow, then mutate, then grow again), Potency 100 gaia on the first harvest (massively speeds up a lot of other stuff in botany), Potency 100 anything in perma (since perma has a bio generator), potency 100 space vines.

**Pull request merged**
