### PR TITLE
Turns off nightmare and shadowling from dynamic

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

https://github.com/yogstation13/Yogstation/pull/18459

# Changelog

:cl:  
rscdel: Nightmare and shadowling have been disabled on dynamic
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
disable dynamic while at it

**Comment by Zer0Tactics** [comment]
But why? Sling I get because it's broken, but why nightmare?

**Comment by ynot01** [comment]
> But why? Sling I get because it's broken, but why nightmare?

1. Cringe
2. Disabled in non-dynamic midround pool
3. IceMeta

**Comment by Zer0Tactics** [comment]
> > But why? Sling I get because it's broken, but why nightmare?
> 
> 
> 
> 1. Cringe
> 
> 2. Disabled in non-dynamic midround pool
> 
> 3. IceMeta

Personal Opinion

How does this matter? Different round types have different settings.

Why in the name of god would we remove an entire antag from rotation because one map is bad? The fact that slings are fucked on ice meta is a map issue, not an issue with the core mechanic of multiple antags.

**Comment by Moltijoe** [comment]
dynamic is a bunch of midrounds, shadowling probably shouldn't be a midround EVER
i don't see the problem with leaving nightmares though

**Comment by ToasterBiome** [comment]
Fix the bugs related to them instead of disabling them

**Pull request closed without merging**
