### PR TITLE
Revert "Farewell Syringe Guns (#17466)"

### PR DESCRIPTION
**Pull request by ReddicusDragon**
This reverts commit ee2ded102dc52318027e0c4b55114a647260df4f.

# Changelog
:cl:  
bugfix: Syringe guns are back 
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Just remove the illegal weapons requirement from researching medical weapons

**Comment by Moltijoe** [comment]
I want to make cool chemicals, if syringe guns are easy to get that makes balancing cool chemicals harder

**Comment by TheRyeGuyWhoWillNowDie** [comment]
What do syringe guns add to the game except being a boring instant-win in one click?

**Comment by ReddicusDragon** [comment]
> What do syringe guns add to the game except being a boring instant-win in one click?

player choice

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> player choice

In that case, can I choose to use a taser?

**Comment by ThatLing** [comment]
@ReddicusDragon Inadequate reasoning, please add it to your original post or I will close this

**Pull request closed without merging**
