### PR TITLE
[MDB IGNORE] Revives [#14835] [[Hug-]Box] Kills Off Quarter-Tile Decals* Literally just the decals edition

### PR DESCRIPTION
**Pull request by GraveHat**
Now I have to deal with merge conflict central.

# Document the changes in your pull request

#14835 Revives this pr because the entire branch got deleted. Look at it for more details. God help us all maptainer.

Should literally just be the decals now. I quite literally removed every single quarter and Trimline decal on an updated map of the station then copy-pasted the decals back onto it. Let me know if I missed anything.

# Changelog

:cl: @VaelophisNyx 
tweak: replaced every quarter-tile square decal with a line decal of the same or similar color station-wide, except where used to recolor a floor tile.
tweak: replaces individual quarter tile decals being used instead of opposing
bugfix: moved the light switch in the window in the garden to somewhere accessible
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
BUT THE SOUL

fr tho this looks so much better

**Comment by monster860** [comment]
You still got some quarter-tiles in RnD

**Comment by Spacemanspark** [comment]
Please merge this soon

**Review by JamieD1 — CHANGES_REQUESTED** [review]
I really wish you just did the damn decals and didnt do loads of seperate PRS in this one, like robotics I think looks worse etc etc. Misleading title in order to get loads changed.

**Comment by JamieD1** [comment]
Also put MDB ignore or we will get banned.

**Comment by GraveHat** [comment]
> Also put MDB ignore or we will get banned.

I have no idea what that means but I'll find out tomorrow, will also come with the reversions.

**Comment by ToasterBiome** [comment]
what's with the sprites?

**Comment by GraveHat** [comment]
What the fuck is with the 228 file changes

**Pull request closed without merging**
