### PR TITLE
removes clownstation

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

We have now, 4 times, had the fucking clownstation prefs load instead of the yogstation ones, and I genuinely have no fucking clue why. Deltastation prefs don't load, but this shit does for some unknown reason, so here we are.

#### Changelog

:cl:  
rscdel: clownstation is gone
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
Dont remove the salt shaker its a buyable shuttle in normal playthrough for 500k btw lol

but yeah the prefs bug sucks

**Comment by monster860** [comment]
uh this also removes saltshaker

**Comment by monster860** [comment]
also this touches yogstation.dmm for literally no reason

**Comment by Amelia0010** [comment]
Which was bundled with clownstation.https://github.com/yogstation13/Yogstation-TG/pull/3910/files#diff-9518505c6f6487dbe92fd4290f560eaeR447

**Comment by fluffe9911** [comment]
Yeah so? theres a shit ton of other stuff bundled with it as well The Salt Shaker is not causing prefs to be broken theres no reason to remove it lol

**Comment by Amelia0010** [comment]
And it edited yogstation because I had some leftovers of a project I was working on that I accidentally committed, fixed it in woops 2 though

**Pull request merged**
