### PR TITLE
Removes normal legs from lizards to solve some issues and because I'm an evil bastard

### PR DESCRIPTION
**Pull request by Mqiib**
sorry i took your legs you're a snake now

Just kidding, lizards can only have digitigrade legs now because it's no longer as much of a powergaming issue and straight legs on lizards still look godawful agh it's horrible

# Testing
image
image

Remarkably easy

# Why is this good for the game
Because chubby can't figure out how to make cloning work and species changing is funky doodly and digitigrade legs are in an eternal semi-state of being, so this saves a lot of headache code-wise by just forcing it. Also they look better and the downsides are less downsidey now compared to a long time ago. Insert something about species uniqueness or whatever here.

# Changelog

:cl: 

tweak: Vuulek no longer have normal legs

/:cl:

### CODE REVIEW

**Review by Moltijoe — DISMISSED** [review]
surely there's other code related to this feature, please remove it too

**Comment by Mqiib** [comment]
> surely there's other code related to this feature, please remove it too

I'm unsure what will break things and what wont so I didn't mess with anything else

**Comment by Yarinoi** [comment]
please mqiib let them have socks....

**Comment by StupidTums** [comment]
Well, there goes my self-hating liznerd character. Killed my rp >:L

**Comment by Smudged** [comment]
I'd certainly say, 
Add in footwraps for all lizards if you're gonna change this.
This in itself is a balance change too considering ALL lizards are gonna be affected and not everyone is gonna want digitgrade legs. 
At least giving them the option of having footwraps let's them have shoes.

**Review by SapphicOverload — APPROVED** [review]

**Pull request merged**
