### PR TITLE
[Omega] Fixes the Engine Atmos loop

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Changes Atmos on Omega

#### Changelog

:cl:  
tweak: Fixes atmos engine loop on omega to actually work
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Should have just reversed the loop!


But good work.

**Comment by JamieD1** [comment]
> Should have just reversed the loop!
> 
> But good work.

You shut your damn mouth.

**Comment by Bibby0110** [comment]
C O N F L I C T

**Comment by JamieD1** [comment]
How the hell does it conflict

**Comment by Bibby0110** [comment]
Someone else changed the map :3

**Comment by MegaEmpirical** [comment]
This is obviously because you didn't just reverse the loop.

**Comment by JamieD1** [comment]
> This is obviously because you didn't just reverse the loop.

Ill throw you into the supermatter next time I see you.

**Comment by Hopekz** [comment]
bafda36531f1cbacb0252bc8c636c3762

**Comment by JamieD1** [comment]
Weje is going to incorporate

**Pull request closed without merging**
