### PR TITLE
Port codebase to 515

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Move the codebase to 515, changes are likely backward compatible

Regex used:
```
 \.proc/(\w+)
 PROC_REF($1)
 
 ([\w/]+?)/?\.proc/(\w+)
 TYPE_PROC_REF($1, $2)

,\.proc/(\w+)
, PROC_REF($1)

,([\w/]+?)/?\.proc/(\w+)
, TYPE_PROC_REF($1, $2)
```

# Changelog

:cl:  
experimental: Update to byond 515
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
>On hold until Auxmos (fuck extools)

gotcha, see you in a few months then

**Comment by adamsong** [comment]
Did not expect that to close the pr lol

**Comment by adamsong** [comment]
Seems to work in 514, should work in 515, can't quite be sure yet though

**Review by ToasterBiome — APPROVED** [review]
didnt instantly crash after 15 minutes lets punch it

**Pull request merged**
