### PR TITLE
Reduces flash paralyze duration on paralyzed targets

### PR DESCRIPTION
**Pull request by Moltijoe**
Might as well throw my hat in the ring

This will either force people to burn out their flash faster to keep them down
Or give them a brief moment where they can escape or fight back

:cl:  
tweak: Flashes paralyze for a shorter duration on already paralyzed targets
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
nice. if there must be something done about flashes for some reason I prefer this

**Comment by ynot01** [comment]
10 seconds of stun is death/cuff, this doesnt do much besides making group arrests harder i guess?

**Comment by Moltijoe** [comment]
> 10 seconds of stun is death/cuff, this doesnt do much besides making group arrests harder i guess?

Not like any other change is getting approved

**Comment by Moltijoe** [comment]
> 10 seconds of stun is death/cuff, this doesnt do much besides making group arrests harder i guess?

also, maybe it's just me, but i don't think a single secoff should be able to easily make group arrests with just a flash

**Review by MajManatee — APPROVED** [review]
chain flashing was cringe anyways

**Pull request merged**
