### PR TITLE
RBMK from NSV

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request
Continuation of #13512

Todo

- [x] Combine programs
- [x] Redesign the engine room
- [ ] Fix the random bugs
- [x] Test gasses

# Spriting
Reactor
image
Uranium 235
image
Plutonium
image
Depleted
image
Telecrystal 
image
Bananium
image

# Wiki Documentation

image

Basic Fuel Rods (from cargo)
5000 for 3 U235
15000 for 3 U239
15000 for 3 Bananium (Contraband)

Roundstart setup is stable (50/50 Moderator mix)

# Cooling
No special effects

# Moderators
Plasma counts as 1 fuel mole
Tritium counts as 10 fuel moles

Tritium increases radioactivity

Power Modifier is Oxygen Mole / (Fuel Mole * 10) [0-1]
Power Produced (Fuel Moles / Moderator Moles) * Power Modifier

Makes nitryl at 20%+ power

Control Moles (Increase control rod effectiveness)

Nitrogen counts as 1 Control Mole
CO2 Counts as 2 Control Moles
Pluoxium Counts as 3 Control Moles
Effectiveness = (Control Moles / 250) * 0.65

Nitrogen reduces radiation by 25x
CO2 by 12.5x

Permeability (Increases cooling effectiveness)
BZ 1 Mole
Water Vapor 2 Moles
Hypernobilium 10 Moles

Gas Absorption Constant 0.5-0.6
Gas Absorption = GAC + ( Perm Moles / 500)

Degradation
Nitryl 1 Mole

Degredation Modifier Deg Moles / 15 (Every 15 Moles reduces rod by 1%)

# Changelog

:cl:  Redmoogle, maxion12345, NSV
rscadd: Added RBMK
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
rbmk is cursed
maybe you'll succeed somehow

**Comment by Cartlord** [comment]
What will be the gain from porting this?
What can this engine do that the five we have already, three of which (supermatter, turbine, thermo-electric) already use gases, can't?
Where is the fun of optimizing this engine?
What even IS the R.B.M.K.?
_How is this good for the game?_

**Comment by redmoogle** [comment]
> What will be the gain from porting this?
> What can this engine do that the five we have already, three of which (supermatter, turbine, thermo-electric) already use gases, can't?
> Where is the fun of optimizing this engine?
> What even IS the R.B.M.K.?
> _How is this good for the game?_

How are you good for yogstation (tip: your not)

**Comment by ilikesaying** [comment]
Everybody working until the station turns into Chernobyl 2 Electric Boogaloo Extra Cost Cuts Edition

**Comment by JamieD1** [comment]
Jesus Christ

**Comment by redmoogle** [comment]
I think this is ready but someone should help me redesign the mechanics to not just be a really slow progress bar

**Review by warface1234455 — APPROVED** [review]
cool engine 
image

**Comment by Bibby0110** [comment]
come back moogle :(

**Pull request closed without merging**
