### PR TITLE
Church of the Blood bloodborne sect

### PR DESCRIPTION
**Pull request by Marmio64**
# Document the changes in your pull request
Adds the Church of the Good Blood, pretty much the healing church from bloodborne.

Minister to people by drawing blood and healing them with your bible in order to gather 20 favor to spend on various things. You can also sacrifice hearts for a 15 favor.
The bible effect heals people for 5 health (its not supposed to be the primary way of healing) and always succeeds though has a 10 second cooldown. It also draws some of their blood. Species with no blood will not be able to be drawn from nor healed.

Rites-
Good Blood Vial- A vial of 'Good Blood' is summoned for 50 favor. It acts as a weaker omnizine by default, but you can also purposefully overdose to get stronger healing at the cost of brain damage, toxin damage, vision blurring, and hallucinations. You can also get addicted to it, though addiction is mostly flavor and cannot truly hurt you.
Church Attire- Creates some boots, black gloves, and a choir garb and hat. The choir armor is identical to the witchhunter garb but looks like the choir set from bloodborne. Costs 150 favor.
Churchblood Sight- Exactly the same as the holy light medhud rite, spawns a autosurgeon which gives you a medhud. Costs 150 favor.
Augur Heart- Spawns a 'augur heart'. Upon reaching about 25% of your health, it injects you with 10 units of Good Blood with a long cooldown. Similar to the Heart of Freedom. Surgery will have to be done manually with this. Costs 50 favor.
Augur Eyes- Spawns 'augur eyes'. They act as a slightly weaker version of night vision eyes that things such as nightmares have. Surgery will also have to be done manually to put this in. Costs 50 favor.
Augur Liver- Spawns a 'augur liver'. They're similar to a slightly stronger cybernetic liver without EMP downsides, as they are more resilient and can flush out more toxins. Manual surgery will be needed to put this in. Costs 50 favor.

# Why is this good for the game?
A new sect that focuses more on helping other people but also gives cool stuff for the chaplain to work with. 

# Testing
See screenshot below. I made sure the items all have correct states, made sure favor gain works as intended, and all rites work as intended.

# Spriting
image
The augur eyes and heart, along with the altar and choir set.
image
augur liver

# Wiki Documentation

The Church of the Blood is a heavily bloodborne inspired sect which is geared towards healing people in an unorthodox way via drawing blood and then administering the addictive 'good blood' substance. You are also able to give people strange alien organs to enhance them, and create snazzy choir garbs.

# Changelog

:cl:  
rscadd: Adds the church of the blood sect, heavily inspired by bloodborne.
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
why must every chaplain sect be about healing

**Comment by Hislyna** [comment]
Yo thats pretty dope

**Comment by Marmio64** [comment]
> why must every chaplain sect be about healing

i wouldn't say the technophile, old gods, and candle sect are 'about healing', and the capitalist and kudzu sects are rather loose on their role on healing too. However, I would say that the reason why healing is often a bigger theme is because the chaplain was always able to heal with their bible, and healing is an easy way to make their role interact with other people more and give them something to do without having to come up with a big unique gameplay loop for every sect, which is rather hard to do. This sect anyhow doesn't have to go out and heal anyone if they don't feel like it as they don't get favor for giving out good blood and they can focus on surgery and such instead if they would rather. I am still probably going to see about other augur organs as well maybe to further push it away from healing.

**Comment by Moltijoe** [comment]
Balance Council:
>This is all just strictly powergame stuff for chaplain

**Pull request closed without merging**
