### PR TITLE
[BOX] Redoes Engineering Foyer, switches Engine Entrance and CE room, puts another door between the protolathe (GREYTIDFERS GO HOME)

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Alternate to https://github.com/yogstation13/Yogstation/pull/19747

chrome_LREgwiw8Xt

Adds to the security while not completely mucking everything up

Switches entrance to engine and CE room (and adds a way to get into CE room from space)

slightly shortens construction room to fit the maint room and vending machines

# Wiki Documentation

Looks like the picture

# Changelog

:cl:  Athena413, Aquizit, ToasterBiome
mapping: Reworks BoxStation Engineering Foyer and CE room for more security
/:cl:

### CODE REVIEW

**Comment by Aquizit** [comment]
now *this*

this is the shit

**Comment by athena413** [comment]
yeag

**Comment by ynot01** [comment]
lathe room looks kinda empty, maybe a locker or something like what meta has in that room

**Comment by iamthesilly** [comment]
I like this

**Comment by hedgehog1029** [comment]
but what if 
another one

**Comment by neeshacark** [comment]
image_2023-07-21_191407706
why is this a manifold?

**Comment by neeshacark** [comment]
hey whats that doing there 
image_2023-07-21_191658005

**Comment by neeshacark** [comment]
you can take the CE office out of the space but you cant take the CE office out of the spac
e

**Comment by Reed0506** [comment]
if the lathe room's access isnt identical to the foyer's access i will be very disappointed (just construction access from what i know), otherwise yeah this is probably a good thing and a lot of maps we have had in rotation over the years did have dedicated lathe rooms.

**Review by Aquizit — CHANGES_REQUESTED** [review]
image
Should probably have a unique name.

I agree with ynot about there being a like an O2 or a fire locker in there -- or just a plant.

CE's office and the new shared storage room could use Air Alarms.

**Comment by athena413** [comment]
> image Should probably have a unique name.
> 
> I agree with ynot about there being a like an O2 or a fire locker in there -- or just a plant.
> 
> CE's office and the new shared storage room could use Air Alarms.

opinion:

O2 locker or tool locker in the bottom left corner of the room below the door (i'd like a tool locker)
Plant or maybe borg recharger in top left corner of the room

**Comment by ToasterBiome** [comment]
image

**Review by Ethan4303 — DISMISSED** [review]
Shared storage and CE office still need their air alarms

image

**Review by Aquizit — APPROVED** [review]

**Pull request merged**
