### PR TITLE
Library fix

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Adds another camera to library, so half of the left section isnt missing camera overview and changes the stairs so that they dont look gross and weird by removing what i assume to be a ramp, but it just looked stupid.

# Spriting
added a sprite for wooden_stair_middle

image

# Changelog
:cl:  
mapping: Changed box library slightly to have nicer stairs and another camera.
imageadd: wooden_stair_middle added, just a variation on the existing wooden stairs
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Add the spriting in the changelog pls

**Review by Lefttoe12 — APPROVED** [review]

**Comment by Ethan4303** [comment]
Document your brig phys changes please :)))

**Comment by azzzertyy** [comment]
> Document your brig phys changes please :)))

fixed, idk why it was there but it was

**Comment by iamthesilly** [comment]
not wheelchair accessible

**Comment by azzzertyy** [comment]
> not wheelchair accessible

image

**Review by ToasterBiome — DISMISSED** [review]
make changelog reflect what map you're changing

**Comment by azzzertyy** [comment]
> make changelog reflect what map you're changing

done

**Review by cuackles — APPROVED** [review]
artproved

**Review by ToasterBiome — APPROVED** [review]
bark bark ruff ruff ruff ruff

**Pull request merged**
