### PR TITLE
Sterilizes the codebase - Pt.3 Removes Wound Licking

### PR DESCRIPTION
**Pull request by JamieD1**
Removes Wound Licking

:cl:  
rscdel: Removes Wound Licking
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
How was this even allowed into the codebase in the first place?

**Comment by Smudged** [comment]
Small change, I don't care, but it's a bad change.

**Comment by VaelophisNyx** [comment]
...ok so I wasn't aware you could lick *other people's* wounds

what
why

**Comment by GraveHat** [comment]
An unused feature ported downstream discovered completely on accident gets axed.

**Comment by SomeguyManperson** [comment]
Unfortunately you cannot kill people for doing this on yogs so this is necessary :(((

**Comment by Hislyna** [comment]
I don't really see it as fetishy, It's a nice added touch to the flavour of felinids, and other than personally using it alot, it's not the worst thing that can go if it does.

**Comment by LazennG** [comment]
I'm biased despite never using this myself but I thought it was an alright feature since first seeing it a while back and I don't recall anybody getting weird with it in my like 5 times of seeing it happen. It's mild and doesn't seem to have much potential for abuse (idk how wounds work) so I'm not a fan of the removal.

**Comment by Smudged** [comment]
Change it so you can only lick your own wounds, and lord forbid even add a negative to doing it, like extra bleed (Suggested by Sauce cat), This would solve most problems with anybody being weirded out from felinids licking.

**Comment by VaelophisNyx** [comment]
so looking at it, it's also a very strong way to negate bleeding if you lack sutures and happen to have a felinid nearby

**Comment by Marmio64** [comment]
since when did felinids get free unlimited clotting to use on other people, when the race has zero tangible downsides?

**Comment by Smudged** [comment]
> since when did felinids get free unlimited clotting to use on other people, when the race has zero tangible downsides?

This why I really suggest, felinids only being able to lick and benefit from licking their own wounds.

Also, the "donor race can have no positive features" is a laughable joke Imo, you're paying for this, so you might as well get something from it.

**Comment by Marmio64** [comment]
> > since when did felinids get free unlimited clotting to use on other people, when the race has zero tangible downsides?
> 
> This why I really suggest, felinids only being able to lick and benefit from licking their own wounds.
> 
> Also, the "donor race can have no positive features" is a laughable joke Imo, you're paying for this, so you might as well get something from it.

i dont think you can lick your own wounds at all right now, and that allowing people to do that would make the situation worse since now you can directly powergame yourself rather than just helping other people.

pay-to-win aside, any race can have positive features but they should be balanced with some sort of downside.

**Comment by Smudged** [comment]
> pay-to-win aside, any race can have positive features but they should be balanced with some sort of downside.

As I've suggested earlier, make it so felinids can only lick their own wounds, and add a negative. 
Also if it's any consolation, licking wounds doesn't heal, that's a misconception, it only stops bleeding.  

Worse case, make it slower to stop bleeding.

**Comment by Smudged** [comment]
(Also to preface: The stop bleeding rate is 0.5) 
I don't think needs to be removed at all, but yeah, just make it so felinids can only lick their own wounds, if people think it's so weird

**Comment by maxion12345** [comment]
If someone licks my wounds instead of just using gauze, I'm beating them to crit on the spot

**Comment by JamieD1** [comment]
How about we make it only usable on yourself, sounds good.

**Comment by Georgeur** [comment]
No this has always been retarded, should be axed. 
Mechanically I even hate it, force disease transmission, and less effective than simply bandaging or cauterising, meaning its needlessly risky as a wound treatment.

**Comment by Marmio64** [comment]
> How about we make it only usable on yourself, sounds good.

0.5 bloodloss removal every 3 seconds which is unlimited without downsides and can be used on yourself is actually decently powerful, especially considering it's free (though its not very common for you to need to use it, but still). A weeping avulsion starts off with 4.25 bloodloss, for reference. If you're going to do this, maybe reduce it to 0.2 bloodloss removal or something so it's quite a bit worse than suturing youself (which for reference heals 0.6 bloodloss at the same rate).

**Comment by Smudged** [comment]
I would honestly also suggest bringing this up to Donor if that's even possible, or to the opinions of people who actually play Felinids to make the choice.

**Comment by Marmio64** [comment]
> I would honestly also suggest bringing this up to Donor if that's even possible, or to the opinions of people who actually play Felinids to make the choice.

well the people playing the race are going to be biased since they benefit from this remaining good. In any case, the PR is public, they can just look at it and comment if they want.

**Comment by Hislyna** [comment]
Well my question is are people really getting freaked out about it? I found it more balanced it not being useable on yourself but works on others, but if people are really freaked out about getting their bleeding stopped by a felinid licking you then sure make it self only

**Comment by SomeguyManperson** [comment]
On further introspection I believe this is roughly on par with CPR wherein people _can_ be weird about it but it's not inherently weird in that way

Either it should be removed entirely or left as is, if it's just a self care thing it's just a personal upgrade for picking a race with no particularly present downsides, and if it's staying the treatment time should probably be increased to separate it further from proper medical care

**Comment by Sniblet** [comment]
I've used this like twice, it's slow and people generally panic and run when a felinid passive grabs them, but anything that can make a weeping avulsion go away instead of juiceboxing you is pretty big for a race that's supposed to be slightly worse than human
I don't get the fetish content thing but maybe I've seen too much anime

**Comment by Georgeur** [comment]
At the least remove the force infection thing cause that’s powergamey as fuck.

**Comment by SomeguyManperson** [comment]
> At the least remove the force infection thing cause that’s powergamey as fuck.

How it infects the catgirl not the (un)willing participant

**Comment by JamieD1** [comment]
Sorry, its just weird.

**Pull request merged**
