### PR TITLE
Fuck the Police : Unfucks labor camp

### PR DESCRIPTION
**Pull request by ToGWtF**
### Intent of your Pull Request

Bluespace Crystal. Changed from 50 to 75. Its the rarest, and the most limiting material for things like bags of holding or teleporters. If you found one of these, you were actually fucking usefull
Diamond. From 25 to 50. Again. You're actually usefull. You did your service to the station
Titanium. From 20 to 35. Another rare ore. Needed for t4 part upgrades.
Uranium. From 25 to 35
Gold. From 20 to 30
Silver. From 20 to 25
Plasma. From 20 to 25
Glass. From 1 to 5.
Rglass. From 4 to 6.
Plasma Rglass. From 23 to 30.

Oh also fixes a bug where the ore machines on labor/old mining would pick up any item put infront of them and put it somewhere unreachable. No more losing your ore bag

#### Changelog

:cl:  

tweak: tweaked a few things about labor camp

/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
there's a reason glass is so low, because you can just dig the dirt for a bunch of it

**Comment by ynot01** [comment]
~~uhhh isnt this sell value? doesnt this buff the shit out of cargo lol~~

know what forget what I said I could use an easy cargo shift

**Comment by Moja10** [comment]
Glass should still be cheap because you can get loads from digging, rglass can be new price so that prisoners can make it from the glass and metal they get for bonus. otherwise agree with all this PR

**Comment by SomeguyManperson** [comment]
think the point values are mining point values and the labor camp uses mining point values

**Pull request merged**
