### PR TITLE
Moves many icons out of items_and_weapons.dmi and reorganizes it

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

image

image

Didn't do many of them but its a start, may go back and do some more later. Also may have missed a few issues while testing.

# Wiki Documentation

No changes needed. 

# Changelog

There should be no player facing changes

### CODE REVIEW

**Comment by ToasterBiome** [comment]
can you list every single icon you changed please thanks

**Review by nesisknesis — APPROVED** [review]
m4

**Comment by nmajask** [comment]
Cant spel

> can you list every single icon you changed please thanks

just look at the icon diff list

**Comment by Firewolf34** [comment]
Amazing. Love this <3

**Pull request merged**
