### PR TITLE
Reworks CQC

### PR DESCRIPTION
**Pull request by Moltijoe**
Guh, i just sorta went and didn't pay attention to what i changed
one moment

Overall changes
- All cases of stamina damage now respect melee armour

Harm intent
- Leg sweep no longer Paralyzes
- Immobilizes for 1 second instead of 1.5
- has an attack cooldown of 0.4 instead of 0.8

Disarm intent
- Chance to disarm is 100% instead of 65%
- No longer picks up the item disarmed
- does 10 damage instead of 5
- has an attack cooldown of 0.4 instead of 0.8

Grab intent
- has an attack cooldown of 0.2 instead of 0.8
- no longer stuns

Slam combo
- Now Harm Disarm instead of Grab Harm
- No longer paralyzes
- does 20 stamina damage instead of 15

Kick Combo
- Now Disarm Disarm instead of Disarm Harm
- Kicking someone on the ground resets their stamina regen

Pressure point combo
- Now Disarm Harm instead of Disarm Grab
- Now called dislocate
- Now applies the dislocated limb wound in addition to 50 stamina damage

Consecutive Combo
- Now Harm Harm instead of Harm Harm Harm Harm Harm
- Now called discombobulate
- no longer paralyzes or knocks down
- now does 50 stamina damage instead of 25
- now applies a 4 second confusion, stacking up to 8 seconds

Chokehold and Restrain
- Now stuns for one second upon achieving an aggro grab
- Disarm hitting someone you have aggro grabbed begins the chokehold
- Functions as normal after that

# Why is this good for the game?
CQC among many other martial arts are hated for being one click win buttons
This seeks to remove one click wins while still giving a sense of power to the user
General idea is that it's a one-two combo sorta thing
one quick and weak hit, leading into a more impactful hit based on the combo

Also moves abilities around to make it feel better with combat mode (mainly removing grab from things)

also, despite everyone complaining, no one else decided to actually do anything about it

# Testing
image

:cl:  
tweak: reworks CQC to have less 1 click wins
/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
https://www.youtube.com/watch?v=B62ACxuq8Pw

**Comment by Moltijoe** [comment]
> https://www.youtube.com/watch?v=B62ACxuq8Pw

way ahead of you buddy
image

**Comment by neeshacark** [comment]
not a fan of automatic chokehold or the changes to disarm, i think 65% chance to disarm and you automatically get the disarmed item in hand is cooler

**Comment by Moltijoe** [comment]
> not a fan of automatic chokehold or the changes to disarm, i think 65% chance to disarm and you automatically get the disarmed item in hand is cooler

i hate rng
and grabbing the disarmed item makes doing the disarm combos far more difficult

you still take the target's weapon on the throw mode counter attack

and fine, i'll see what i can do with the chokehold thing

**Comment by StupidTums** [comment]
Might be needed to add a third harm onto the consecutive cqc or decrease the stamina damage from 50 to 40 considering how easy the combo is in respect to what it can do (i.e. confusing some into stam crit). Also, does the kick combo still mute the victim? That is important to keep for silent takedowns.

**Comment by Moltijoe** [comment]
> Might be needed to add a third harm onto the consecutive cqc or decrease the stamina damage from 50 to 40 considering how easy the combo is in respect to what it can do (i.e. confusing some into stam crit). Also, does the kick combo still mute the victim? That is important to keep for silent takedowns.

Considering it checks for melee armour now it remains to be seen if 50 is too much
And yes, it does mute, but only on someone lying down

**Comment by Moltijoe** [comment]
balance council has long since died
don't bother using the label until someone revives it

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
