### PR TITLE
Engineering Drone lawset

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request

Like with the chaplain, sec, rnd, and clown lawsets, I always liked the idea of having specific lawsets for each department. This one is for the construction and repair of the station, and serves as a sort of cross between mother drone and ceo/corporate. While playing it should feel mostly like a CEO variant that focuses on expanding the station. Provides a good excuse for an AI to take on interesting engineering projects in their spare time, and could push some interesting RP.

# Wiki Documentation

Adds a new AI lawset with the following module:
1. You are an advanced construction drone.
2. Ensure the station remains in good repair.
3. Ensure the station's inhabitants remain in good repair.
4. Ensure you remain in good repair.
5. The station's inhabitants may designate certain build or repair tasks as higher priority. Take this into account when planning your priorities.
6. Expand and upgrade the station.

# Changelog

:cl:  
rscadd: Adds a new lawset focused on construction
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
Tweaked law 3 from "Ensure its inhabitants remain in good repair." to "Ensure the station's inhabitants remain in good repair." to remove ambiguity

**Comment by MenacingManatee** [comment]
Considering adding a law between 4 and 5 about taking build requests/orders from crew to increase interactivity and reduce boredom on longer shifts

**Comment by JamieD1** [comment]
Christ how many lawsets you got.. Board please so we can test.

**Comment by JamieD1** [comment]
oopsie

**Comment by Marmio64** [comment]
this is getting to be some major lawset bloat that nobody will use

**Comment by MenacingManatee** [comment]
> this is getting to be some major lawset bloat that nobody will use

Instead of a roundstart lawset, I've got this and all the other lawset PRs set to be an option if an ion storm procs a full lawset change. This'd let them see use even if they wouldn't normally hold up to the more standard lawsets that are chosen, but they shouldn't be detrimental to the point crew feels the need to change back. This would also help create some variety for AI players

**Comment by MenacingManatee** [comment]
Added a new law between 4 and 5 with the intent of adding to the AI's interactivity with the crew

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
