### PR TITLE
Apparently people dont like zombies, who knew

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑
tweak: Lowered zombie event spawn rate to 0 so its now admeme only since atleast 4 people yelled at me they dont like it on the discord
/🆑

### CODE REVIEW

**Comment by yacabo** [comment]
What if you get an overwhelming bad reaction to this PR?

**Comment by fluffe9911** [comment]
Im gonna be confused and sad

**Comment by jcatjmeow** [comment]
I have added my +1 and i hope to see the zombies in hell

**Comment by Xoxeyos** [comment]
I would rather see zombies on the station, not in hell. Atleast the station isn't forever.

**Comment by yacabo** [comment]
Can't we make it so that zombies still crop up but it's a very _very_ rare chance for it to happen

**Comment by ynot01** [comment]
zombies being its own gamemode would be cool but midround antag is so fucked

**Comment by MegaEmpirical** [comment]
I love zombies, you're a monster.

**Comment by Szyszkrzyneczka** [comment]
Random zombies are fun you absolute disgustang

**Comment by Sir-Lagsalot** [comment]
I was under the impression that 👎 was the fuck zombies option. I have switched my vote to 👍 accordingly. Zombies get out.

**Comment by GuppyLaxx** [comment]
if i had maintainer i would close this pr even if it ment getting demoted

**Comment by alexkar598** [comment]
That's why you aren't a maint even less an HC

**Comment by Bibby0110** [comment]
set weight to 1

**Comment by fluffe9911** [comment]
More people downvoted this pr then upvoted it so im just gonna go ahead and close it

**Pull request closed without merging**
