### PR TITLE
Syndicate Icemoon Revision 3 - Uranium At Last

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Adds the following to Syndicate Icemoon:

- Nuclear Power Station
- Moves xenobio to science wing
- Adds agent retrieval implants, because I don't trust you
- A memorial to the previous capabilities of the base
- Engineering is also entirely redone
image
image
image
image

# Changelog

:cl:  
rscadd: While Nanotrasen has been doing whatever, the Syndicate has rebuilt the engineering and research wings of their icemoon research base from the ground up.
bugfix: A Syndicate engineer also rewired the turrets because SOMEONE DIDN'T MAKE THEM FUCKING INHERIT AREA. Whoever made that decision, I will find you. I will devote my continued existence to the eradication of every fucking cell of your being and the splitting of every fucking atom that made up those cells. I will eradicate your genome from the face of the planet. Every trace of your being will be fed to the Sun. Start running.
/:cl:

# Testing:

i did test it but OBS saved it as mkv

fixed all issues encountered

### CODE REVIEW

**Comment by ShoziOffical** [comment]
God bless

**Review by ToasterBiome — APPROVED** [review]

**Comment by Addust** [comment]
my fucking GOD i need this reviewed

**Comment by Addust** [comment]
oops

**Comment by LassiH** [comment]
why the xenobiology smaller and worse  its already a pain doing xenobiology in the current one  i dont  think it will be any better with 3 cages that are 2x1

**Comment by MajManatee** [comment]
1 Week no activity. Please re-open when you can fix the issues w/ the linter.

**Comment by Addust** [comment]
gonna do this again with a new pr and new map, fuelled only by cheddar cheese

pray

**Pull request closed without merging**
