### PR TITLE
Adds The Holy Flame, for it is prayer day.

### PR DESCRIPTION
**Pull request by Marmio64**
Divine blessings, brothers. It is a glorious day today. Even better, it is prayer day.
The chaplain now has a unique bible skin and name for the holy flame. Naming your religion "holy flame", "the holy flame", or "okran" will rename your bible to 'The Holy Flame'. You can also select this unique bible skin.

theholyflame
theholyflame

# Changelog

:cl:  
rscadd: Adds the Holy Flame bible reskin and custom name.
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
EYYYYY! kenshi reference gud reference.

**Comment by cowbot92** [comment]
I do enjoy kenshi but im unsure about adding a religion dedicated to misogyny would really be a good idea

**Comment by Marmio64** [comment]
> I do enjoy kenshi but im unsure about adding a religion dedicated to misogyny would really be a good idea

You can just praise the flotsam ninja's version instead. They're okranites who believe in gender equality. In addition, this isn't 'adding a religion', it's adding an authentic name and bible skin. You can be a incel with or without it, I just want to hate on skeletons.

**Comment by cowbot92** [comment]
> 

"Naming your religion "holy flame", "the holy flame", or "okran" will rename your bible to 'The Holy Flame'."
It is in fact a religion, it is not a 'sect', and referencing it at all is still just wrong. I understand you like the game & the reference, but it's still crude to invite hate speech into the game just because "I want to hate on skeletons" when other people can use it for their own misogyny. I would suggest perhaps renaming it entirely to something different, so that nobody sees your book and thinks "Wow marmio hates women, that's not surprising."

**Comment by Marmio64** [comment]
> > 
> 
> "Naming your religion "holy flame", "the holy flame", or "okran" will rename your bible to 'The Holy Flame'." It is in fact a religion, it is not a 'sect', and referencing it at all is still just wrong. I understand you like the game & the reference, but it's still crude to invite hate speech into the game just because "I want to hate on skeletons" when other people can use it for their own misogyny. I would suggest perhaps renaming it entirely to something different, so that nobody sees your book and thinks "Wow marmio hates women, that's not surprising."

i'll see what more people think. I can rename it to The White Flame if we really are this scared of this managing to provoke real hate speech.

**Comment by cowbot92** [comment]
> > > 
> > 
> > 
> > "Naming your religion "holy flame", "the holy flame", or "okran" will rename your bible to 'The Holy Flame'." It is in fact a religion, it is not a 'sect', and referencing it at all is still just wrong. I understand you like the game & the reference, but it's still crude to invite hate speech into the game just because "I want to hate on skeletons" when other people can use it for their own misogyny. I would suggest perhaps renaming it entirely to something different, so that nobody sees your book and thinks "Wow marmio hates women, that's not surprising."
> 
> i'll see what more people think. I can rename it to The White Flame if we really are this scared of this managing to provoke real hate speech.


For anyone who may not be aware of the religion in game that this PR is referencing, it is essentially 'All men are superior to everyone else, women & aliens are evil and bad", if people are fine with adding it then add it. I have no doubt if anyone does anything stupid with it in game they'll be banned anyhow.

**Comment by JamieD1** [comment]
I love drama in my PRs.

**Pull request merged**
