### PR TITLE
Tweaks and Rearranges the Medbay Storage Room to have a door leading to the Secondary Storage

### PR DESCRIPTION
**Pull request by GraveHat**
# Document the changes in your pull request

Removes a R_wall and replaces it with a second "Medbay Secondary Storage" door, including firelocks. Rearranges Medbay Storage by moving the Protolathe to the position of the sink no one uses, creating a new separate storage case for the Brute and Burn Kits in the corner after moving the lathe, and stuffing the bodybag and prescription glasses onto one table. Medbay Secondary Storage gets rearranged to make a clear path to Medbay Storage, removing 3 roller beds 2 wheelchairs and adding in 2 folded wheelchairs on the remaining tables while moving an IV drip.
image

I thought this would be a convenient change to getting around boxstations medbay a bit faster while also simultaneously making it easier for antagonists and medical staff to escape if they happened to get cornered in the storage room without jaunts or teleports.
This PR is untested and has been made via FastDMM Commit Maps.

Edit: Explains the changes in the Changelog in detail.

# Changelog

:cl:  
rscadd: New Door with firelocks leading to Secondary Storage
rscadd: 2 Foldable Wheelchairs
rscdel: 3 Rollerbeds
tweak: Rearranged Medbay Storage and Secondary Medbay Storage
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
This looks excellent imo; a better use of space and a good side route opened for crew and antags alike

**Comment by Moggram** [comment]
I don't know 100% if this is on the other side of the wall or the storage case, but you may need to move it

**Comment by ToasterBiome** [comment]
where'd the sink go?

**Comment by VaelophisNyx** [comment]
I was talking to him about the sink and we both came to the conclusion that both: no one uses it, and there's already another sink nearby in medbay

**Comment by GraveHat** [comment]
I appear to have accidentally committed the patch to the master branch of my fork but I have since then merged the Pull Request for the patch by uploading the maps exported map file directly into this branch after renaming it to replace the old one.
image

**Review by ToasterBiome — APPROVED** [review]
if https://github.com/yogstation13/Yogstation/pull/14466 is ultimately not merged

**Pull request closed without merging**
