### PR TITLE
cargo tesla goal

### PR DESCRIPTION
**Pull request by Amelia0010**
Cargo now gets a goal to setup a tesla in the cargo bay

:cl:
rscadd: Cargo can now get a goal to set up a tesla engine in the cargo bay
/:cl:

Split off from #9457 since I don't want to weigh down a framework PR with components using that framework

### CODE REVIEW

**Comment by MrHorizons** [comment]
Would having the tesla be set up in the cargo shuttle count towards the goal? That's something of the meta when doing the (strangely rare) contained tesla ball bounty.

**Comment by Tipy1802** [comment]
Cargo building the Tesla is considered powergaming and against server rules, please do not justify it with code

If you want better cargo goals then you can try “order crate x” “order x amount of crates” or “spend x amount of credits on crates”

Thanks for going through the troubles of separating this from the conditional goals pr

**Comment by Amelia0010** [comment]
>Would having the tesla be set up in the cargo shuttle count towards the goal?

No, it wouldn't

>Cargo building the Tesla is considered powergaming and against server rules

[Citation needed]

**Comment by Reed0506** [comment]
hmm yes today the crate pushers will construct an exceptionally complicated and dangerous engine that can and will destroy the entire station with a single mistake

**Comment by Moja10** [comment]
Cargo building a tesla to satisfy a bounty is not against the rules and if this PR was merged, then it's definitely not against the rules. If you don't like cargo building teslas, make a post on the forums on why you think it shouldn't be allowed or should be against the rules, as there are a couple of admins who would agree with you. Also, make a PR to remove the cargo bounty to build a tesla and ship it, if you don't like cargo building teslas. 

But as it stands, it's fine for the bounty and this cargo goal.

**Comment by MegaEmpirical** [comment]
Bounties are supposed to encourage inter-department interactions, no need to remove the cargo tesla bounty.

As for building an engine in cargo, I'm against this as it encourages that behavior more and it should just be an engineers job. I've consistently been against that cargo power game bullshit.

**Comment by Tipy1802** [comment]
> [Citation needed]

Crate pushers that probably don’t even have a university degree wouldn’t know how to set up a fucking Tesla engine from scratch so it breaks metagaming rules

Setting up engines is engineering’s job not cargo’s (it’s even in the name!) so it breaks the powergaming rule

**Comment by MegaEmpirical** [comment]
I wish Tippy but Council says otherwise and Cargo is allowed to make engines. I disagree strongly but nothing I can do about it.

**Comment by Tipy1802** [comment]
Oh I thought I saw admins say otherwise months ago, I guess council over ruled that, still I am against this even if allowed it shouldn’t be encouraged

**Review by JamieD1 — APPROVED** [review]
If it causes issues this will be reverted

**Comment by MegaEmpirical** [comment]
Nooooooooooooooooooo

**Pull request merged**
