### PR TITLE
Uphold the law turns into Uphold Space Law

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

this is why we can't have  nice things

### CODE REVIEW

**Comment by azzzertyy** [comment]
image

**Comment by burn1cycle** [comment]
Probably came about because today someone on discord said "I don't have to follow space law, just "The law" what ever I think it is.". This is probably an important loop hole closer so that the AI laws can function as intended without shitters trying to redefine laws and use that to troll people for their own amusement.

**Comment by Hopekz** [comment]
> This is probably an important loop hole 

I remember when yogmins had the balls to tell someone that they are wrong and their 'loolhole' didn't mean anything but I can sadly see staff getting rule lawyered over this

**Comment by maxion12345** [comment]
can't even upload "law 4: you are the law"

**Comment by azzzertyy** [comment]
> can't even upload "law 4: you are the law"

law 4 you are space law

**Comment by boba247** [comment]
An alternative could be "Uphold the station's law". Keeps a hint of vagueness in the law while also idiot-proofing the loophole ~~for players that should probably have a silicon ban.~~

**Review by adamsong — APPROVED** [review]
Code does as intended

**Comment by Hopekz** [comment]
> Code does as intended

There's no code change in this PR

**Comment by adamsong** [comment]
> There's no code change in this PR

> ai_laws.dm

**Comment by Hopekz** [comment]
> > ai_laws.dm

Mane that is just a string. There isn't any code to review here

**Review by JamieD1 — APPROVED** [review]
Why are people retarded.

**Pull request merged**
