### PR TITLE
buffs mega arachnid and gives it loot

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
upgrades a currently unused mob to up its stats and up its loot giving it a syndie elite corpse and a bee boy corpse when its killed

its current health right now is 1.5k

#### Changelog

:cl:  
rscadd: Added new items to leapers drop list and edited its stats
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
it litterally doesnt spawn currently so theres no problem about balancing this around players

**Comment by Hopekz** [comment]
> it litterally doesnt spawn currently so theres no problem about balancing this around players

Did you actually test this? 
Like spawn it in and fight it as a miner? If no you're just kind of changing values for the fun of it.

**Comment by boodaliboo** [comment]
> > it litterally doesnt spawn currently so theres no problem about balancing this around players
> 
> Did you actually test this?
> Like spawn it in and fight it as a miner? If no you're just kind of changing values for the fun of it.

yes i did actually test this pr and it was a challenge due  to how mega arachnids can restrain you but its not a insta death like a collosus bolt

**Comment by alexkar598** [comment]
I dont like this PR and 4 thumbs down

**Pull request closed without merging**
