### PR TITLE
improvised bandages heal less and last less long

### PR DESCRIPTION
**Pull request by boodaliboo**
these prs are mostly for ashwalkers
#### Changelog

:cl:  
tweak: makes improvised bandages worse  
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
why tho

**Comment by JamieD1** [comment]
Because whats the point of medical?

**Comment by Reed0506** [comment]
christ they heal 40? thats a lot i never knew it was that high. i cant see this really being terrible in practice though. this is probably a fine change or something i dunno. 40 -> 30 is a moderate nerf but i cant see it making basically any negative impact.

**Comment by UselessTheremin** [comment]
"you know whats op? improvised bandages."

-nobody

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
