### PR TITLE
Polysmorphs can crawl slightly faster

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Polysmorph tails will now increase crawling speed by a bit.

# Why is this good for the game?

Adds a minor upside to a species that has far more drawbacks than benefits

Also I just thought it would be funny

# Testing
they do in fact go a bit faster when crawling

# Wiki Documentation

Add this to their list of racial benefits

# Changelog

:cl:  
tweak: polysmorph tails slightly increase crawl speed
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
wait does this stack with flying fang crawl speed

**Comment by AdamPrime314** [comment]
Slight difference that has no effect on species meta, won't be a reason to switch your current 100% optimized rad-proof stone-cold infinite welder healing with free implant self-surgery race to reptile while also making things just slightly different, just like the custom, miniscule change in speed coefficient that got removed by [the same author](https://github.com/yogstation13/Yogstation/pull/20422) while ignoring the fact that polysmorphs have [the same thing](https://github.com/yogstation13/Yogstation/blob/224c21c806d5020585f9514c3c33f8697120a2c5/code/modules/mob/living/carbon/human/species_types/polysmorphs.dm#L20), but he didn't seem to remove that one. [**I WONDER WHY.**](https://forums.yogstation.net/threads/cephalopoet-report-by-sapphicoverload.27227/#post-223354)
ClipboardImage

**Comment by iamthesilly** [comment]
> just like the custom, miniscule change in speed coefficient that got removed by the same author while ignoring the fact that polysmorphs have the same thing

The polysmorph's modifier was added in a [different PR](https://github.com/yogstation13/Yogstation/pull/18112), and was actually intended and documented in the description and changelog. The other was an undocumented change the author meant to revert.

You went through all the player complaints and PRs I've made and somehow managed to miss these comments on the very PR you brought up, and didn't even read the changelog on the other.
image

I take offense to you claiming that I only make PRs to powergame, especially since most of my PRs are bugfixes or new features or reworking things rather than balance tweaks, and I'm not afraid to nerf things that [I](https://github.com/yogstation13/Yogstation/pull/18671) [actually](https://github.com/yogstation13/Yogstation/pull/18591) [use](https://github.com/yogstation13/Yogstation/pull/20933) when I think they're too strong.

> he

Also wrong.

**Comment by AdamPrime314** [comment]
> The polysmorph's modifier was added in a [different PR](https://github.com/yogstation13/Yogstation/pull/18112), and was actually intended and documented in the description and changelog. The other was an undocumented change the author meant to revert.

I lost this argument argument completely and you are right. I can't refute anything without making my original point seem pointless and not thought out, which it was. 

> You went through all the player complaints and PRs I've made and somehow managed to miss these comments on the very PR you brought up, and didn't even read the changelog on the other.

You overestimate me. This isn't a hate campaign against you where I read everything you post. I just don't like that you, Moltjoe and the balance team decided that the work speed coefficient was bad enough to be removed, just like how people seem to be showing their disapproval to this PR by downvoting while leaving no productive comments. Having species do even some things at a slightly different pacing than others is rather fun when you read the code and it has made me enjoy the game more when learning about it's mechanics in-depth.

> I take offense to you claiming that I only make PRs to powergame, especially since most of my PRs are bugfixes or new features or reworking things rather than balance tweaks, and I'm not afraid to nerf things that [I](https://github.com/yogstation13/Yogstation/pull/18671) [actually](https://github.com/yogstation13/Yogstation/pull/18591) [use](https://github.com/yogstation13/Yogstation/pull/20933) when I think they're too strong.

The truth is more in the middle. I have not said that, but I understand that the tone of my comment seemed to indicate that I hinted at it. You are a maintainer after all, so I cannot argue that you are "just stupid" and "don't know anything about the game". You do, and most of your changes reflect your programming and general game knowledge. Sometimes bias does slip in, like in all creators. I don't dislike you, nor this PR, [just this PR](https://github.com/yogstation13/Yogstation/pull/20422) and the fact you made it.

**Comment by iamthesilly** [comment]
> I don't dislike you, nor this PR, [just this PR](https://github.com/yogstation13/Yogstation/pull/20422) and the fact you made it.

To be completely honest, I have made a few PRs that were definitely influenced too much by my own bias, but I don't think this is one of them. I made that PR to revert an unintended change that someone else made, and considering the modifier was so low that it took around 8 months before anyone even noticed it was added, I don't really think removing it was noteworthy.

**Comment by iamthesilly** [comment]
Changed it to polysmorphs instead of lizards

**Comment by Cartlord** [comment]
i actually think it's neat for polysmorphs to crawl faster, since the creature they're based on is known for slipping (crawling) through tight spaces & vents

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
