### PR TITLE
Lets you start mechanical surgeries with a handdrill

### PR DESCRIPTION
**Pull request by Moltijoe**
It's the upgraded screwdriver, so why not

:cl:  
tweak: Handdrill can be used to start mechanical surgeries
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
Surgical drill as a makeshift substitute NOW

**Comment by Moltijoe** [comment]
> Surgical drill as a makeshift substitute NOW

no

**Comment by Burger1998** [comment]
> Surgical drill as a makeshift substitute NOW

thats not how screws work.

**Comment by Sniblet** [comment]
> thats not how screws work.

How long have you been playing this game? You can perform brainwashing with a roll of package wrapper
Surgical drill NOW!!!

**Comment by Moltijoe** [comment]
> How long have you been playing this game? You can perform brainwashing with roll of a package wrapper Surgical drill NOW!!!

Time to remove brainwashing with wrapping paper

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
