### PR TITLE
Adds (a smaller) pAI button back to ghost hud

### PR DESCRIPTION
**Pull request by Jumps0**
### Intent of your Pull Request

Requested by @wejengin2 
Add's the pAI button back that was recently swapped out by another one of my PRs. (Though smaller this time)
**This does not remove the ghost role button** it simply just puts the pAI button back on the HUD.
pai

Thanks to JamieD1 for the smaller pAI sprite. <3

#### Changelog

:cl:  
tweak: Adds (a smaller) pAI button back to ghost hud
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
I'd have have a link to sign up in the ghost pai notification instead of a fifth button

**Comment by Jumps0** [comment]
> I'd have have a link to sign up in the ghost pai notification instead of a fifth button

A link where? Inside the ghost role options?

**Comment by JamieD1** [comment]
> I'd have have a link to sign up in the ghost pai notification instead of a fifth button

Thing is if you submit personalities then it sends a ping to the devices, if you take that away it will be only one way.

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
Make it a verb in the right hand panel instead. We are quickly going to get the menu cluttered if we keep adding buttons like that

**Comment by Jumps0** [comment]
> Make it a verb in the right hand panel instead. We are quickly going to get the menu cluttered if we keep adding buttons like that

verb
it's been a verb. If you feel like this button PR is unnecessary then you can close it.

**Comment by JamieD1** [comment]
> > Make it a verb in the right hand panel instead. We are quickly going to get the menu cluttered if we keep adding buttons like that
> 
> verb
> it's been a verb. If you feel like this button PR is unnecessary then you can close it.

How about if you add it a small button underneath he speech bubble?

This would not clutter the menu and keep it looking nice :)

**Comment by JamieD1** [comment]
@Jumps0

**Comment by Jumps0** [comment]
seems do-able, though downscaling the sprite is gonna be tricky cause i'm not a good spriter
image

I'll try to do it tomorrow

**Comment by JamieD1** [comment]
Hows this?
Small Pai

**Comment by Jumps0** [comment]
Jamie wanted it moved so i moved it

**Comment by alexkar598** [comment]
This is small enough to be fine

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
