### PR TITLE
eggplants now contain a small ammount of nicotine

### PR DESCRIPTION
**Pull request by boodaliboo**
image

:cl:  
rscadd: gave eggplants nicotine like irl
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
I mean the amount is so small the liver will instantly just eat it.. I mean..

**Comment by Moggram** [comment]
> 
> 
> I mean the amount is so small the liver will instantly just eat it.. I mean..

What if its at 50 potency?

**Comment by boodaliboo** [comment]
what is missing ???????????????

**Comment by MegaEmpirical** [comment]
Inherently small would actually be a good thing, curious how it'll ramp up with potency though as that'll be what really matters.

**Review by alexkar598 — APPROVED** [review]
Code is good.... i guess

**Comment by JamieD1** [comment]
Pointless.

**Comment by MegaEmpirical** [comment]
Every Botany PR is pointless. Doesn't make it bad.

**Pull request closed without merging**
