### PR TITLE
[BOX] CMO office changes

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Rearranges the CMO office a bit. A surgery table is on the east side of the room now like the Meta CMO office, there are shutters on the south side, and the desk has been rotated.

cmoofficechange1
cmoofficechange1shutters

# Spriting

# Wiki Documentation

# Changelog

:cl:  

mapping: CMO office is now fully surrounded by window shutters, has an operating table, and desk rotation

/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
Ruh roh check failed

**Comment by Aquizit** [comment]
I like this, the failed check is likely just a bug I'll kick a new check tomorrow when I do a review.

**Comment by Aquizit** [comment]
jk I mean I'll do it now

**Comment by Moja10** [comment]
Am I hallucinating or are the two screenshots the same

**Comment by solwashere** [comment]
> Am I hallucinating or are the two screenshots the same

With shutters and without shutters

**Review by Aquizit — CHANGES_REQUESTED** [review]
Couple things:
1. CMO area should be extended into the western wall. It's not like that on live now might as well fix it (primarily a power issue, as if medbay lobby power goes out suddenly those shutters don't work).
2. Anesthetic tank and operating computer for the surgery area (Meta needs an anesthetic tank too but that's not important here obviously).
3. Surgery Holosign button and sign addition. Meta also has this I've included an image to point them out to you, can just yoink them from there pretty sure and shift the pixels around if needed.

image
image

**Comment by solwashere** [comment]
Where did you want the holosign button to go?

**Comment by Aquizit** [comment]
Corner of the tile above the display case looks good with that current setup. A second shutters button wouldn't go amiss there either, so you don't need to walk around the desk in case you want to close them for said surgery.

**Comment by solwashere** [comment]
> Corner of the tile above the display case looks good with that current setup. A second shutters button wouldn't go amiss there either, so you don't need to walk around the desk in case you want to close them for said surgery.

moved it to above the table and moved the newscaster to above the trophy case
image

**Review by Aquizit — APPROVED** [review]

**Pull request merged**
