### PR TITLE
SMES Visual Update

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request
Gives the SMES a slightly minor visual update

image
p1
(grey pixels at the bottom are transparent)

Move the position of the charge/input/output visuals slightly
The charge level has 6 instead of 5 states
SMES has a slightly more square and thinner design

# Changelog

:cl:  
imageadd: SMES Icon changed slightly
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
too square imo

The open panel states looks much better though

**Comment by redmoogle** [comment]
> too square imo
> 
> The open panel states looks much better though

Debated on try to keep it circle but the sprite conflicts at the bottom and it looks very strange(when keeping it circular)

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
Very nice

**Review by KillerOrcaCora — APPROVED** [review]

**Comment by redmoogle** [comment]
~~Jamies requirements are weird~~
IMO more worthwhile to start from scratch

**Comment by redmoogle** [comment]
:|

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
