### PR TITLE
Borgstuff

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

👏 

#### Changelog

:cl:  
rscadd: Borg module selection now uses a radial
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
image
 except with a tophat borg in the bottom left instead of standard

**Comment by Kmc2000** [comment]
I want my initial(nich) back

**Comment by ShadowDeath6** [comment]
I hope this displays in text which module is which, otherwise this is a huge drop in qol

also does this affect choosing skins or is it the same

**Comment by Amelia0010** [comment]
will merge after this (hopefully) gets merged https://github.com/tgstation/tgstation/pull/41765

**Pull request merged**
