### PR TITLE
snowflake bandaid fix for blood not working

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

I don't know what the fuck is going on but this should fix something

# Changelog
:cl:  
bugfix: blood works also I hate life code
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Find the actual fix, this can stay test merged in the meantime.

**Comment by SomeguyManperson** [comment]
> Find the actual fix, this can stay test merged in the meantime.

actual fix is related to the typing animation/chat bubble pr, I assume due to it calling stoplag or SOMETHING stupid through the amount of stuff it does

**Comment by ToasterBiome** [comment]
> > Find the actual fix, this can stay test merged in the meantime.
> 
> actual fix is related to the typing animation/chat bubble pr, I assume due to it calling stoplag or SOMETHING stupid through the amount of stuff it does

typing indicators now no longer use async procs, any ImmediateInvokeAsync procs in the profiler are now someone else's problem

**Comment by JamieD1** [comment]
No longer required

**Pull request closed without merging**
