### PR TITLE
[admin]Revert "Revert "Stupid proofs erts""

### PR DESCRIPTION
**Pull request by Hopekz**
Reverts yogstation13/Yogstation#8514

We now have to deal with people coming in masses to centcom like literally every single time an ERT is sent. Why did this get merged without an alternative fix who knows.

Even the shift that made me start this revert there were like 8 people that shouldn't be there on centcom and removing this without having a backup is dumb

### CODE REVIEW

**Review by JamieD1 — APPROVED** [review]

**Comment by boodaliboo** [comment]
lol this was never a problem before we had the original pr didnt expect it to become one

**Comment by Hopekz** [comment]
> lol this was never a problem before we had the original pr didnt expect it to become one

Why do you think it became undropable in the first place AAH
Yes undropable items are bad but we have no other clever solution to replace this at the moment and we can't just have this be a thing in the time being while waiting for a new solution to replace this one.

**Comment by ToGWtF** [comment]
So let me get this straight

We are now rebalancing the rebalance, of the rebalance, of the balance of ERTs. 

The absolute state of it

**Comment by ynot01** [comment]
what if you idk

sent the ERT shuttle up after ERT arrive??

**Comment by Hopekz** [comment]
> sent the ERT shuttle up after ERT arrive??

Then you remove those cool evacuation moments for ERT (a.k.a every time they're wiped out)
I want the ERT to be able to do things on their own without having an admin baby them.

We need another solution for this that isn't no-drop but not having a solution in place at all is worse.

**Comment by alexkar598** [comment]
Nodrops are bad

**Pull request closed without merging**
