### PR TITLE
Remove reinforcement chromosome

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

this is just a validhunting/antag chromosome and does not really have a place here. being able to counter a genetics counter by injecting yourself with more genetics is dumb. hardcounters like this are bad and should not be in the game.
# Spriting

# Wiki Documentation

Reinforcement chromosome gone
# Changelog

:cl:  
rscdel: Remove reinforcement chromosome
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Improve dont remove smh

**Comment by Simplehorror** [comment]
> Improve dont remove smh

i'm improving genetics by removing it

**Comment by Simplehorror** [comment]
really this should be a 1 TC item for geneticists

**Comment by Simplehorror** [comment]
closed until I see the result of the other PR

**Comment by Bibby0110** [comment]
add more mutadoney mutadone and counter the genetics counter-counter

**Pull request closed without merging**
