### PR TITLE
corrects sausage snipping to not work if you are snipping it while holding it

### LINKED ISSUE #17201: Sosig in hand gets snipped out of existence
### Severity

Inconvenience

### Short Description

Sausage deleted by being snipped with knife when in hand

### Reproduction

1. Be someone with sosig and knife
2. Cut sosig with knife, in-hand and not anywhere else
3.
4. where did it go

### Round ID

44631

### Test Merges

_No response_

### BYOND Username

CurrTheLost

### Additional information

I AM THE BUG FINDER

### PR DESCRIPTION
**Pull request by ReddicusDragon**
# Document the changes in your pull request
You can no longer snip a sausage into an american sausage if you are holding it in your hand.

I blame @ToasterBiome for the disappearance of a countless numbers of sausages from the station

fixes #17201 

# Changelog

:cl:  
bugfix: adds sanity check to sausage code 
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
why not make it drop on turf // use the put in hands proc if the loc is a mob

**Comment by ReddicusDragon** [comment]
> why not make it drop on turf // use the put in hands proc if the loc is a mob

if you want good code ask byemoh, if you want quick, shitty fixes ask me :)

the real answer is I tried that and am tired and don't want to debug it

**Comment by ReddicusDragon** [comment]
> why not make it drop on turf // use the put in hands proc if the loc is a mob

plus, i just stole meatball code for this pr

**Comment by Moltijoe** [comment]
> why not make it drop on turf // use the put in hands proc if the loc is a mob

A lot of other cooking actions require the object to be on a table or otherwise, so this wont be all that different

**Review by adamsong — APPROVED** [review]
The issue with cutting your sausage while you hold it is the American sausage spawns inside you, but not somewhere you can access it. Still agree with the fix. No more internal sausages.

**Comment by CurrTheLost** [comment]
SO THAT'S WHERE MY SOSIGS HAVE BEEN GOING.

**Pull request merged**
