### PR TITLE
Traitor: Episode III - Revenge of the Desword

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Baby, I'm sorry; can you ever forgive me?

# Changelog

:cl:  
rscadd: Added the double-bladed energy sword back to the traitor uplink
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
YOOOOO

**Comment by Blundir** [comment]
Maybe it's time to go further and add desword crafting from two normal eswords?

**Comment by solwashere** [comment]
Full energy reflection kinda just makes it so that you can run at sec and win every time unless they bring out shotguns, in which case it won't really matter all that much cause you killed all of sec anyways.
I dislike the disabler meta but the ability to kinda just kill sec instantly early on is a bit meh.
You can kinda just buy desword, armor polish, and uno reverse and instantly dab on any sec even when they bring out shotguns.

**Comment by Moja10** [comment]
> Full energy reflection kinda just makes it so that you can run at sec and win every time unless they bring out shotguns, in which case it won't really matter all that much cause you killed all of sec anyways. I dislike the disabler meta but the ability to kinda just kill sec instantly early on is a bit meh. You can kinda just buy desword, armor polish, and uno reverse and instantly dab on any sec even when they bring out shotguns.

The point of the desword is that its such a menacing beast that it forces sec to back up and rethink strategy beyond "batong/disabler them til horizontal". Desword is a real threat and sec operated just fine, they have the answers they need to deal with a desworder.

Answers to desword for sec:
1. flashes
2. shields for block chance
3. shotguns
4. hardlight pistol? (I have no idea how these would interact, I think its a bullet subtype with energy damage? I don't think its an energy projectile)
5. lucky batonging/mass batonging
6. flashbangs
7. pepper spray if no protection
8. bolas
9. guns

answers to desword all crew have:

1. spear/floor tile/toolbox/saw/glass shard throwing 
2. slips
3. embeds of any kind
4. wooden shields for block chance

Other niche answers to deswords:
1. ballistic guns
2. block chance blades of any kind
3. botany bluespace tomatoes/lube tomatoes
4. water/lube in general (unless no slips)
5. shocked airlocks
6. craft a bola

For people who worry about people going full gamer and gamerboning with desword, that is naturally counterbalanced by the murderbone rules, it would not be a valid instance of "I had to steal the RD armor so I shrimply had to murderbone all of science + robotics to do so with my desword". For surprise killings, not much is gonna change since the regular esword will slow you in two hits, three if sec (aka death), same with desword. Desword just crits in 3 - 4 hits as opposed to 4 - 6 hits. 

I support antag tools that force sec to reconsider their strategy and how they approach dealing with John Antag, not everything should be easily and quickly resolved by a batonging/disablering, same way that we already have a deadly melee antag item that reflects ALL projectiles, sleeping carp. Sec handles sleeping carp just fine, I think desword will be fine too.

**Comment by Rdrazga** [comment]
By the way DEsword works it negates any block chance you may have agsinst it, and due to how it’s block chance works it will block most ballistics and mele attacks. So 90% of those ways of ‘dealing’ with it are just false.

**Comment by ynot01** [comment]
> By the way DEsword works it negates any block chance you may have agsinst it, and due to how it’s block chance works it will block most ballistics and mele attacks. So 90% of those ways of ‘dealing’ with it are just false.

Negates 35 block chance due to AP, similarly the vibration sword will remove some block chance from the desword

**Comment by Rdrazga** [comment]
> 

Block chance also negates block chance because coders

**Comment by Notamaniac** [comment]
> For people who worry about people going full gamer and gamerboning with desword, that is naturally counterbalanced by the murderbone rules,

And if they have hijack, I guess you can just go get fucked. And of course it's a massive consolation to sec and heads who are apparently also protected by the murderbone rule.

> Answers to desword for sec:
> 
>     1. flashes
Made irrelevant by sec huds or any sunglasses, which you can probably get from the first seccie you kill
> 
>     2. shields for block chance
> 
https://github.com/yogstation13/Yogstation/assets/17688334/0cd7318b-037c-48e5-843a-47de0d757b0c
>     3. shotguns
> 
https://github.com/yogstation13/Yogstation/assets/17688334/ab6dfaf6-7844-4aaf-a8e4-01b0705239fd
>     4. hardlight pistol? (I have no idea how these would interact, I think its a bullet subtype with energy damage? I don't think its an energy projectile)
> 
https://github.com/yogstation13/Yogstation/assets/17688334/8eeffb0f-629b-4ab6-8d3e-7bc4667909d4
>     5. lucky batonging/mass batonging
> 
Just rely on random chance guys, that's fun.
>     6. flashbangs
> 
Irrelevant with protection
>     7. pepper spray if no protection
Which they will have after jumping their first sec guy, or raiding a locker
> 
>     8. bolas
> 
Congratulations, you slowed them down. Now you need to play baton RNG again, which is again going to be so, so fun.
>     9. guns
> 
????

> I support antag tools that force sec to reconsider their strategy and how they approach dealing with John Antag, not everything should be easily and quickly resolved by a batonging/disablering, same way that we already have a deadly melee antag item that reflects ALL projectiles, sleeping carp. Sec handles sleeping carp just fine, I think desword will be fine too.

By reconsider, you mean mass up, hope your bola lands, rush with a baton and pray to RNG jesus. That or bomb them. Sleeping carp already has a drawback, you can't use guns, and reflecting projectiles depends on you having throw mode on.

But everyone wants the dual esword back. So again, there's zero point in arguing this. I don't even want to consider what happens when people who know how to make roundstart nitrium *cough* Tim *cough* get their hands on this again, but hey, neither do any of you.

**Comment by 00ze-cyclone** [comment]
You don’t rethink strategies or do things differently, you just go full gamer mode because that’s the only thing that work, the very healthy game design of sec being encouraged being sweatlords and antags ending up being mauled if they don’t take desword because sec is now even more tryhard than before.
All of this for the braindead murderbone stick with the incredible gameplay of run to spaceman and click until horizontal.

**Comment by DeadlyBag** [comment]
The videos from the other before showed options that would already be pretty weak versus armored targets / high block chance targets, lets take a look at weapons with AP abilities that hopefully would be able to deal with these types of weapons.

Desword vs DU slugs

https://github.com/yogstation13/Yogstation/assets/31378243/14e17797-e3ef-4d73-aebe-c7491018a1fd

Desword vs WT-550 AP

https://github.com/yogstation13/Yogstation/assets/31378243/a2584674-4729-4414-8fec-23cc177587fb


Desword vs Vibroblade

https://github.com/yogstation13/Yogstation/assets/31378243/c37b112d-6f42-49d8-80f5-d9da431b03d5

**Review by ToasterBiome — APPROVED** [review]

**Comment by Moltijoe** [comment]
fucking FINE, i GUESS

**Pull request merged**
