### PR TITLE
I hate horrors I hate horrors I hate horrors

### PR DESCRIPTION
**Pull request by Mqiib**
# Document the changes in your pull request

Preface this by saying my gitkraken is being fuckywucky and thinking I'm replacing the entire file when I'm not and it refuses to believe otherwise. I've checked to make sure it's all the same and as far as I can tell everything is exactly identical before I added the changes. Anyways, to the actual PR.

Horrors are cool! They're neat! They're a weird semi-stealth antag that goes around being malicious without just murdering everyone (nightmares zombies blobs and all the others I'm forgetting) and that makes them COOL.

They're also kinda bullshit.

This pr makes the supposed "counters" marginally more effective by way of removing a couple really stupid ability upgrades that they just hands down shouldn't get (the knockout aoe stun and the invisibility on leaving a host) as well as making the exit time a full minute as opposed to 10 seconds and extending how long it takes to transfer to another host directly. It also makes soul sucking take a minute so its a little bit more of a risk to hop into someone that's actually near help. The upgrade to health is now only +75% instead of +100% (just don't get shotgunned lmao). They also take an extra second to hop into someone's head (timing is tighter but still guaranteed.)

The REASON for these nerfs is simple: horrors are infuriating and nearly impossible to actually bring down without having a perfect setup to do so. A crowd of people around a surgery table, all armed with saws and whatnot, were consistently unable to kill a horror despite being trapped in a small room, such as the surgery theater. Additionally, the ability to not just stun but _sleep_ everyone in an aoe around them with no way to stop it was remarkably stupid, and the ability to silently and invisibly leave someone and slink away without anyone possibly being able to catch it equally so. The other small general nerfs are just a little extra because even without those abilities horrors are still incredibly hard to deal with under normal circumstances. Call it an ided pr all you want, they just have too many tools in practice.

# Wiki Documentation

Does it even have a wiki page yet?

# Changelog

:cl:  

rscdel: Removed invisible escape and funny aoe knockout ability upgrades
tweak: Massively increased escape time and soul eating time
tweak: Moderate increases to direct host transfer time
tweak: Increases time to crawl into someone's ear
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
This cannot legally be marked as an ided because we didn't die

**Comment by Bibby0110** [comment]
Your changelog doesn’t actually mention horrors…

**Comment by Mqiib** [comment]
> Your changelog doesn’t actually mention horrors…

Did you READ the pr description

**Comment by patpol4** [comment]
Changelog appears on its own ingame, not the description

**Comment by Bibby0110** [comment]
> > Your changelog doesn’t actually mention horrors…
> 
> Did you READ the pr description

No because the PR DOESNT show up in the changelog

Also fix your line endings else we can’t review the PR

**Review by Bibby0110 — DISMISSED** [review]
Fix line endings for review

**Comment by tattax** [comment]
ok fine but why remove the sleep it synergizes with revenant and you're pretty much dead if you miss it near one competent enough person, if you want to raise the price or reduce the sleep but i wouldn't outright remove it

**Comment by Mqiib** [comment]
> Fix line endings for review

Genuinely not sure how to fix this, my gitkraken refuses to discard any changes to the files despite them being identical. It's all number tweaks and just removing the things related to the paralysis and invisibility upgrades (which were held primarily in if statements so it was pretty simple).

**Comment by Mqiib** [comment]
> ok fine but why remove the sleep it synergizes with revenant and you're pretty much dead if you miss it near one competent enough person, if you want to raise the price or reduce the sleep but i wouldn't outright remove it

No

**Comment by tattax** [comment]
> > ok fine but why remove the sleep it synergizes with revenant and you're pretty much dead if you miss it near one competent enough person, if you want to raise the price or reduce the sleep but i wouldn't outright remove it
> 
> No

elaborate

**Comment by ChesterTheCheesy** [comment]
Seems to really fuck up horror balance, it's designed to be constantly jumping from host to host, and being vulnerable while doing so. Basically, the sleep upgrade for tentacle was used exactly as i designed it: allows horror to enter a person within a crowd. Without this upgrade, all you can do is knock everyone down and get beaten to death before you enter anyone. If horror successfully hits everyone in a crowd with a high-risk ability that has a cooldown of 20 seconds, i don't see why he shouldn't be rewarded with it.

**Comment by JamieD1** [comment]
Please fix line endings

**Comment by Anvilman6** [comment]
> Does it even have a wiki page yet?

You could've asked myself or the team - or looked it up on the Wiki.
It does, so if the changes here are relevant to what we have documented, let me or the team know and give us the full rundown on changes (post-merge, if merged).

**Comment by Mqiib** [comment]
Soul sucking and leaving are now 30 seconds instead of 60, and the mandatory health upgrade has been brought back up to 2x.

**Review by JamieD1 — APPROVED** [review]
Please inform Wiki team about additions needing done.

**Pull request merged**
