### PR TITLE
[Admin] admins no longer immediately spoiled roundtype at roundstart on sling rounds

### PR DESCRIPTION
**Pull request by ynot01**

### CODE REVIEW

**Comment by boodaliboo** [comment]
why would this matter

**Comment by Takahiru** [comment]
because no other gamemode is done like this

**Comment by JamieD1** [comment]
Why dont you add a check that if its the gamemode or a midround

**Comment by Takahiru** [comment]
slings arent a midround?? jamie dont be bad

**Review by JamieD1 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
