### PR TITLE
I HATE LOWPOP CLOCK I HATE LOWPOP CLOCK

### PR DESCRIPTION
**Pull request by Hislyna**
**Document the changes in your pull request**

Changes both cults to 35, and revs to 30 because theyre not fucking lowpop modes

**Changelog**

🆑
tweak: Both Cults are 35 Pop, Revs is now 30 Pop
/🆑

### CODE REVIEW

**Review by Moltijoe — CHANGES_REQUESTED** [review]
Please properly fill out the changelog

**Comment by Hislyna** [comment]
> Please properly fill out the changelog

I will, the online editor is shit, I followed the guide on it (blame bai)

**Review by Moltijoe — APPROVED** [review]

**Comment by Moja10** [comment]
Should be atomized, lowpop clock I get but low pop bloodcult is functional. it's an opportunity to players get then Admin Legal ™️ validhunting on and show the cult who is who. 35 minimum is WAY too high for blood.

Revs I suspect is affected by a bug where it's  not checking the conditions right, a PR made it require 3 heads minimum but it can generate one anyways. I think it's fine where it is but 30 minimum isn't too bad. 

However, some people can only play on low pop due to time zones and we should not use rhe opportunity to strangle gamemodea away from them

**Comment by UltraBigRat** [comment]
> Should be atomized, lowpop clock I get but low pop bloodcult is functional. it's an opportunity to players get then Admin Legal ™️ validhunting on and show the cult who is who. 35 minimum is WAY too high for blood.
> 
> Revs I suspect is affected by a bug where it's not checking the conditions right, a PR made it require 3 heads minimum but it can generate one anyways. I think it's fine where it is but 30 minimum isn't too bad.
> 
> However, some people can only play on low pop due to time zones and we should not use rhe opportunity to strangle gamemodea away from them

as a european i approve this message

**Comment by MajManatee** [comment]
clock cult low pop ALWAYS steamrolls. Blood cult is bearable, and potentially fun. Revs is dumb and i wouldn't mind it just being gone altogether, but this is a good start.

**Comment by Hislyna** [comment]
> Should be atomized, lowpop clock I get but low pop bloodcult is functional. it's an opportunity to players get then Admin Legal ™️ validhunting on and show the cult who is who. 35 minimum is WAY too high for blood.
> 
> Revs I suspect is affected by a bug where it's not checking the conditions right, a PR made it require 3 heads minimum but it can generate one anyways. I think it's fine where it is but 30 minimum isn't too bad.
> 
> However, some people can only play on low pop due to time zones and we should not use rhe opportunity to strangle gamemodea away from them

See this would be fine, however theres one huge issue that effects the pop. And that is non ready upers effect the bloody pop. Remove that and all is fine and dandy. But because for some god awful reason we count them, the numbers are completely skew whiffed. 14 crew blood cult is not okay.

**Comment by UltraBigRat** [comment]
> > Should be atomized, lowpop clock I get but low pop bloodcult is functional. it's an opportunity to players get then Admin Legal ™️ validhunting on and show the cult who is who. 35 minimum is WAY too high for blood.
> > Revs I suspect is affected by a bug where it's not checking the conditions right, a PR made it require 3 heads minimum but it can generate one anyways. I think it's fine where it is but 30 minimum isn't too bad.
> > However, some people can only play on low pop due to time zones and we should not use rhe opportunity to strangle gamemodea away from them
> 
> See this would be fine, however theres one huge issue that effects the pop. And that is non ready upers effect the bloody pop. Remove that and all is fine and dandy. But because for some god awful reason we count them, the numbers are completely skew whiffed. 14 crew blood cult is not okay.

this is cause half of em latejoin, and if they werent counted hope you like traitors and blood brothers

**Comment by Hislyna** [comment]
> > > Should be atomized, lowpop clock I get but low pop bloodcult is functional. it's an opportunity to players get then Admin Legal ™️ validhunting on and show the cult who is who. 35 minimum is WAY too high for blood.
> > > Revs I suspect is affected by a bug where it's not checking the conditions right, a PR made it require 3 heads minimum but it can generate one anyways. I think it's fine where it is but 30 minimum isn't too bad.
> > > However, some people can only play on low pop due to time zones and we should not use rhe opportunity to strangle gamemodea away from them
> > 
> > 
> > See this would be fine, however theres one huge issue that effects the pop. And that is non ready upers effect the bloody pop. Remove that and all is fine and dandy. But because for some god awful reason we count them, the numbers are completely skew whiffed. 14 crew blood cult is not okay.
> 
> this is cause half of em latejoin, and if they werent counted hope you like traitors and blood brothers

I can assure you at lowpop, they do not

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
