### PR TITLE
Medbots have a chance to say "You are a good" when you help them

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Tipped over medbots will now sometimes say "you are a good" to you if you save them (unless you're the one who tipped them over)

image

https://user-images.githubusercontent.com/93578146/217065956-1e05927f-1237-443a-b9e0-656872b0df80.mp4

# Changelog

:cl:  
rscadd: you are a good
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Could the sound clip please be included in the PR?

**Comment by MajManatee** [comment]
Feels like too much of a weird in-joke.

We already have the "Good person" line, and this is just a more nonsense version if it because...?

**Comment by iamthesilly** [comment]
> Could the sound clip please be included in the PR?

Can't add sound files to PRs, I tried

**Comment by MajManatee** [comment]
> > Could the sound clip please be included in the PR?
> 
> Can't add sound files to PRs, I tried

You have to convert it to an MP4, and you can attach that.

**Comment by iamthesilly** [comment]
> You have to convert it to an MP4, and you can attach that.

pretty sure that's a video format but okay, i'll see what i can do

**Comment by iamthesilly** [comment]
yeah don't think i can do that

**Comment by iamthesilly** [comment]
okay i got it to be an audio-only mp4

https://user-images.githubusercontent.com/93578146/217065813-b2e2bc00-452a-4a9b-aa49-277f5425b042.mp4

**Comment by Hopekz** [comment]
Imo seems too rare for what it is. One in 100 * of untipping them

**Comment by Moltijoe** [comment]
> Imo seems too rare for what it is. One in 100 * of untipping them

for it being an in-joke, it's probably for the best if it's that rare

**Comment by MajManatee** [comment]
Not a fan of in-jokes being added.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
