### PR TITLE
[PORT] Metallic hydrogen armor and helmet from tg

### PR DESCRIPTION
**Pull request by warface1234455**
# Added atmosian hydrogen armor and helmet (Ported from tg: [https://github.com/tgstation/tgstation/pull/53013](url)
Hydrogen metal can be more useful now, this will make the atmos tech job more interesting for atmosian.

# Wiki doc
Metallic Hydrogen Armor: Req 10 metallic hydrogen
Metallic Hydrogen Helmet: Req 5 metallic hydrogen
Metallic Hydrogen Hardsuit: Req 1 Hydrogen Armor, 1 Hydrogen Helmet, 1 Atmos Firesuit, 1 Atmos firesuit helmet, 5 diamond, 10 Metallic hydrogen
New bounty for Metallic hydrogen armor, helmet and axe

<details>
    <summary>images</summary>
     
image

110857604-4af11f00-8276-11eb-98e1-4053d7f9aa25 (2)
temporary sprite for hydrogen atmos hardsuit
image

</details>

# Changelog

:cl:  dawsonkeyes(Sprite) Ghilker(code)
rscadd: hydrogen armor
rscadd: hydrogen helmet
rscadd: new cargo bounty for hydrogen armor, helmet and axe
rscadd: New hydrogen hardsuit

/:cl:

### CODE REVIEW

**Review by cuackles — CHANGES_REQUESTED** [review]
The suit sprites are good but where the item form sprites at?????

**Comment by warface1234455** [comment]
> The suit sprites are good but where the item form sprites at?????

I can't find it kek

**Comment by cuackles** [comment]
> > The suit sprites are good but where the item form sprites at?????
> 
> I can't find it kek



> > The suit sprites are good but where the item form sprites at?????
> 
> I can't find it kek



> > The suit sprites are good but where the item form sprites at?????
> 
> I can't find it kek

You better find them or make some new ones cus u need em ඞ

**Comment by warface1234455** [comment]
> > > The suit sprites are good but where the item form sprites at?????
> > 
> > 
> > I can't find it kek
> 
> > > The suit sprites are good but where the item form sprites at?????
> > 
> > 
> > I can't find it kek
> 
> > > The suit sprites are good but where the item form sprites at?????
> > 
> > 
> > I can't find it kek
> 
> You better find them or make some new ones cus u need em ඞ

**Comment by warface1234455** [comment]
oops wrong button

**Comment by warface1234455** [comment]
> > > The suit sprites are good but where the item form sprites at?????
> > 
> > 
> > I can't find it kek
> 
> > > The suit sprites are good but where the item form sprites at?????
> > 
> > 
> > I can't find it kek
> 
> > > The suit sprites are good but where the item form sprites at?????
> > 
> > 
> > I can't find it kek
> 
> You better find them or make some new ones cus u need em ඞ

the thing is idk how to sprite lmo

**Comment by warface1234455** [comment]
i think i found it

**Comment by warface1234455** [comment]
image

**Comment by warface1234455** [comment]
so now how do i run workflow

**Comment by Marmio64** [comment]
i dont think we should be giving atmos the ability to make armor that is a straight up, no down-sides upgrade to standard armor. 40 melee, 30 laser, 30 bullet, and 30 energy with full-body coverage and no slowdown. At the very least, this should require you to first acquire normal armor and helmets and then you craft it together with metallic hydrogen to upgrade them, so it isn't so easily available to powergamers. If you don't know how to do that I can help you.

A positive though is that this armor has no right looking so badass (ODST armor???)

> so now how do i run workflow

as a first time contributor to the repository you'll need a maintainer to approve the workflow

**Comment by warface1234455** [comment]
> i dont think we should be giving atmos the ability to make armor that is a straight up, no down-sides upgrade to standard armor. 40 melee, 30 laser, 30 bullet, and 30 energy with full-body coverage and no slowdown. At the very least, this should require you to first acquire normal armor and helmets and then you craft it together with metallic hydrogen to upgrade them, so it isn't so easily available to powergamers. If you don't know how to do that I can help you.
> 
> A positive though is that this armor has no right looking so badass (ODST armor???)
> 
> > so now how do i run workflow
> 
> as a first time contributor to the repository you'll need a maintainer to approve the workflow

sure

**Comment by Marmio64** [comment]
> > i dont think we should be giving atmos the ability to make armor that is a straight up, no down-sides upgrade to standard armor. 40 melee, 30 laser, 30 bullet, and 30 energy with full-body coverage and no slowdown. At the very least, this should require you to first acquire normal armor and helmets and then you craft it together with metallic hydrogen to upgrade them, so it isn't so easily available to powergamers. If you don't know how to do that I can help you.
> > A positive though is that this armor has no right looking so badass (ODST armor???)
> > > so now how do i run workflow
> > 
> > 
> > as a first time contributor to the repository you'll need a maintainer to approve the workflow
> 
> sure

if you want to make it require the armor vest and helmet as prerequisite:

```
/datum/crafting_recipe/hydrogenarmor
	name = "Metallic Hydrogen Armor"
	result = /obj/item/clothing/suit/armor/elder_atmosian
	time = 6 SECONDS
	reqs = list(/obj/item/clothing/suit/armor/vest = 1,
                        /obj/item/stack/sheet/mineral/metal_hydrogen = 5)
	category = CAT_APPAREL
	subcategory = CAT_ARMOR
	
/datum/crafting_recipe/hydrogenhelmet
	name = "Metallic Hydrogen Helmet"
	result = /obj/item/clothing/head/helmet/elder_atmosian
	time = 6 SECONDS
	reqs = list(/obj/item/clothing/head/helmet = 1,
                        /obj/item/stack/sheet/mineral/metal_hydrogen = 3)
	category = CAT_APPAREL
	subcategory = CAT_ARMOR
```
	
This code should work, you can put it into code/datums/components/crafting/tailoring.dm underneath the Carp Space Dragon Armor recipe (so it is organized). Then you'd want to remove the stack recipes that you initially added.

**Comment by warface1234455** [comment]
maybe i could make the armor slow you down to the speed like wearing riot armor

**Comment by warface1234455** [comment]
@cuackles

**Review by cuackles — APPROVED** [review]

**Comment by Marmio64** [comment]
by the way you never removed the recipes that you initially added, that allow you to make the armor with only metallic hydrogen, instead there is right now 2 ways to make the armor: One that requires the vest/helmet + metallic hydrogen, and one that is just metallic hydrogen. Check your first commit stack_recipes to see what im talking about. You also removed the code for their item_states in your "Fixes???" commit, then added the sprites in the next commit, but never restored the item_states code, so it isnt going to work.

**Comment by warface1234455** [comment]
Yeah forgot bout that

**Comment by Smudged** [comment]
What's the reasoning behind the armour anyways? 

Why is atmos of all departments getting armour?

**Comment by warface1234455** [comment]
> What's the reasoning behind the armour anyways?
> 
> Why is atmos of all departments getting armour?

To give atmos more content and make atmosian interesting job

Wdym only atmos? Xenobio, botany, security, miner and even cargo themself can order one

**Comment by warface1234455** [comment]
wrong merge heh

**Comment by Georgeur** [comment]
what they mean is, something must serve a purpose. we could add hydrogen swords for example, it wouldn't really serve a purpose for the game from the perspective of a atmos tech, both traitor or crew. 
its my ignorant insight but it's still an idea, drop armor values to something like this.
list(MELEE = 50, BULLET = 30, LASER = 30, ENERGY = 30, BOMB = 85, BIO = 20, RAD = 50, FIRE = 75, ACID = 40, WOUND = 15)
to
list(MELEE = 35, BULLET = 10, LASER = 10, ENERGY = 25, BOMB = 100, BIO = 100, RAD = 100, FIRE = 100, ACID = 40, WOUND = 10)
and then reduce the slowdown, or remove it. 

Has lower armor than normal vests in bullet and laser, 5 more in melee, but now it protects atmos techs from their job more, bombs, radiation, fire.

**Comment by Smudged** [comment]
> Has lower armor than normal vests in bullet and laser, 5 more in melee, but now it protects atmos techs from their job more, bombs, radiation, fire.

You read my mind certainly, I do think these changes would apply more and be more relevant to atmos-techs (Even though the atmos hardsuit already exists).
I would suggest that the sprite be also changed a little to reflect it's purpose as gear for atmos techs to do their job better, like an enclosed mask, but that would be after this is merged.

**Comment by warface1234455** [comment]
> what they mean is, something must serve a purpose. we could add hydrogen swords for example, it wouldn't really serve a purpose for the game from the perspective of a atmos tech, both traitor or crew. its my ignorant insight but it's still an idea, drop armor values to something like this. list(MELEE = 50, BULLET = 30, LASER = 30, ENERGY = 30, BOMB = 85, BIO = 20, RAD = 50, FIRE = 75, ACID = 40, WOUND = 15) to list(MELEE = 35, BULLET = 10, LASER = 10, ENERGY = 25, BOMB = 100, BIO = 100, RAD = 100, FIRE = 100, ACID = 40, WOUND = 10) and then reduce the slowdown, or remove it.
> 
> Has lower armor than normal vests in bullet and laser, 5 more in melee, but now it protects atmos techs from their job more, bombs, radiation, fire.

hmmm.. kinda like the idea. Sure i will change it. but isn't like metallic hydrogen is kinda tough metal so I will keep the laser and energy at 25 and bullet will stay at 30


> > Has lower armor than normal vests in bullet and laser, 5 more in melee, but now it protects atmos techs from their job more, bombs, radiation, fire.
> 
> You read my mind certainly, I do think these changes would apply more and be more relevant to atmos-techs (Even though the atmos hardsuit already exists). I would suggest that the sprite be also changed a little to reflect it's purpose as gear for atmos techs to do their job better, like an enclosed mask, but that would be after this is merged.

I'm not much a spriter but i like the idea I will ask someone about this 
do you prefer the first or the second one

**Comment by warface1234455** [comment]
@Marmio64 I have been thinking about changing the vest upgrade to something else, I kinda hate asking sec for vest and they probally wouldn't give it to atmos tech

**Comment by warface1234455** [comment]
@Marmio64 I was thinking about changing the helmet and armor recipe.. Instead of the sec vest and helmet. I will combine diamond + hydrogen vest/helmet into this new Atmos Hardsuit (Temporary sprite look cool tho)
image
The normal hydrogen vest/helmet will have normal stat while the upgraded hardsuit hydrogen armor one will give the user more protection like fire rad and space

**Comment by warface1234455** [comment]
@cuackles What do you think about this?

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
