### PR TITLE
Sterilizes the codebase - Pt.2 Removes Felinid Table Mood

### PR DESCRIPTION
**Pull request by JamieD1**
Removes Felinid Table Mood

:cl:  
rscdel: Removes Felinid Table Mood
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
just what i like to see, massive game-changing felinid nerfs

**Review by ToasterBiome — APPROVED** [review]
Ok this one is good

**Comment by VaelophisNyx** [comment]
bibby wait this one was fine

**Comment by Smudged** [comment]
This is awful, and the comment Baimou made doesn't reflect what actually happens at all.

**Comment by ToasterBiome** [comment]
> This is awful, and the comment Baimou made doesn't reflect what actually happens at all.

Get my name out of your mouth

**Comment by Smudged** [comment]
> > This is awful, and the comment Baimou made doesn't reflect what actually happens at all.
> 
> Get my name out of your mouth

You don't want me to bring out the receipt, this is your fault.

**Comment by ToasterBiome** [comment]
> > > This is awful, and the comment Baimou made doesn't reflect what actually happens at all.
> > 
> > 
> > Get my name out of your mouth
> 
> You don't want me to bring out the receipt, this is your fault.

Bring out this receipt

You're mom

**Comment by VaelophisNyx** [comment]
> This is awful, and the comment Baimou made doesn't reflect what actually happens at all.

it does at minimum need to be fixed since it still goes off causing an automatic meow, if the felinid in question is *Unconscious* and aggressively slammed onto a table.

**Comment by Spacemanspark** [comment]
What does this even mean

**Comment by VaelophisNyx** [comment]
Felinids, as of now, get a mood buff for being on tables

**Comment by Smudged** [comment]
> You're mom
image

So just put it on record, No, nobody is tabling Felinids to "get them wet" Baimou.

**Comment by VaelophisNyx** [comment]
thing is Smudge, that moodlet fires if they're put onto an OR table. It shouldn't be removed imo, just needs a lot more checks.

**Comment by SomeguyManperson** [comment]
> This is awful, and the comment Baimou made doesn't reflect what actually happens at all.

Awful how

**Comment by Hislyna** [comment]
Okay yeah this can get sterilized

**Comment by Smudged** [comment]
> > This is awful, and the comment Baimou made doesn't reflect what actually happens at all.
> 
> Awful how

Okay, I will admit I think my feelings were flaring as I made this comment.

I wouldn't be opposed to removing tabling Mood Change as it is kind of weird, BUT NOT ON THE LEVEL OF WEIRD THAT BAIMOU SAID.

I'd be okay with removing this feature

**Comment by ToasterBiome** [comment]
> > > This is awful, and the comment Baimou made doesn't reflect what actually happens at all.
> > 
> > 
> > Awful how
> 
> Okay, I will admit I think my feelings were flaring as I made this comment.
> 
> I wouldn't be opposed to removing tabling Mood Change as it is kind of weird, BUT NOT ON THE LEVEL OF WEIRD THAT BAIMOU SAID.
> 
> I'd be okay with removing this feature

I also was a bit heated and I apologize. I think from nearly all the felinid related things, this is the most egregious and out of all of them is what I would put first on the chopping block.

**Comment by JamieD1** [comment]
Nice

**Pull request merged**
