### PR TITLE
[BOX] Disposals Fixes + 2 Tiny Fixes

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Dorms
Medbay
Toxins
Xenobio
Library
Fixes disposal pipe to Perma...again
fixes RD office not even being connected to the disposal network
deleted a rogue corner pipe in the security office, which was layered over a T-Pipe

# Changelog

:cl:  
bugfix: BOX Fixes Disposal system for Medbay/Xenobio/Toxins/Dorms/Perma/RD Office/Library
tweak: Toxins and Xenobio now feature a Disposals Unit/Outlet (Respectively)
bugfix: BOX Fixes missing segment of pipe by the CMO office
bugfix: BOX Fixes Brig Medical Camera being a cloned Interrogation camera
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
removed a plant in dorms

toxins one is in a weird place

dunno how i like the xeno one

@JamieD1

**Comment by VaelophisNyx** [comment]
got any ideas for better locations for things then? Toxins room I wont touch for fear of retribution from toxins players. Xenobio I couldn't think of anywhere easy to place the chute

I forgot to undo that plant's deletion

**Comment by VaelophisNyx** [comment]
Changes made

plant un-deleted

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
where bio hazard closet

**Comment by VaelophisNyx** [comment]
hazard closet gone

all sold

someone please help


but real talk does it really need to be there, its not much use to the toxins guys and takes up space
I can put it in that maint airlock, that'd be safe

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
.

**Comment by ToasterBiome** [comment]
NO MORE LOCKER

**Comment by VaelophisNyx** [comment]
okaaaaaay

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
change some files

**Comment by VaelophisNyx** [comment]
I changed some files

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
