### PR TITLE
crusher resprite

### PR DESCRIPTION
**Pull request by LazennG**
# Document the changes in your pull request

new sprite

# Spriting
image
old sprites: 
crusher
crusher_uncharged
new ones:
neocrusher
neocrushercd

# Wiki Documentation

dont think there's any crusher images on the wiki so nah

# Changelog

:cl:  
imageadd: added new crushersprite
imagedel: deleted old crusher sprite
/:cl:

### CODE REVIEW

**Review by KillerOrcaCora — APPROVED** [review]
Finally a blade that does not have 70 layers of banding.

**Comment by Moltijoe** [comment]
gonna be honest, it always seemed like some weirdly shaped hammer to me, it never actually looked like a blade

**Comment by Moltijoe** [comment]
#17496

**Comment by KillerOrcaCora** [comment]
uh oh

**Comment by KillerOrcaCora** [comment]
I and cuackles decided we will be taking the crusher sprites from TG instead and making some modifications to it to fit our server with the other crusher PR. I didn't notice till now but even though the crusher does a lot of slice-natured things it's classified as a hammer and if you look closely it's just a badly sprited hammer.

**Comment by MajManatee** [comment]
orca cant even use proper grammar, smh

**Pull request closed without merging**
