### PR TITLE
Fixes the stupid fucking emote pop up

### PR DESCRIPTION
**Pull request by GuppyLaxx**
Title. No more having to click like 3 more fucking times because "is it heard??? is it visible???"

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
Speed merge or else

**Comment by ThatLing** [comment]
But why though?

**Comment by Amelia0010** [comment]
lol

**Comment by ThatLing** [comment]
Closing this because it is stale, feel free to re-open or make a new PR if you are working on this again.

**Comment by ShadowDeath6** [comment]
good change imo, asking if it’s visible or hearable just adds a layer of complication and annoyance that doesn’t influence the game much and doesn’t stop people who abuse emotes either way

**Pull request closed without merging**
