### PR TITLE
(port) Ashwalker sharpeners and core stabilizer

### PR DESCRIPTION
**Pull request by boodaliboo**
original pr https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11473
doesnt port diamond sharpener 
thought it was cool and allows ash walkers to stay alive better
#### Changelog

:cl:  
rscadd: Adds a new way for ashwalkers to stabalize cores and sharpeners
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
i can see craftable whetstones becoming a potential powergaming tool for miners, it should probably require mithril which would make it much more exclusive and also give the mithril an actual use, seeing as its generally worthless.

**Comment by boodaliboo** [comment]
> i can see craftable whetstones becoming a potential powergaming tool for miners, it should probably require mithril which would make it much more exclusive and also give the mithril an actual use, seeing as its generally worthless.

you do know mithril is the key ingredient for probably the best consistantly available armor in the game

**Review by Amelia0010 — APPROVED** [review]
Code is fine but I'm indifferent about this so I'll let another @yogstation13/maintainers decide

**Review by Partheo — CHANGES_REQUESTED** [review]
The sprites used in this PR don't exist

**Comment by Partheo** [comment]
Test your stuff before making a PR

**Comment by boodaliboo** [comment]
im a dumbass i have been committing to wrong branch

**Pull request closed without merging**
