### PR TITLE
Sound on law changes

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Law changes now play a noise,

Noise is crap but it will do for now.

#### Changelog

:cl:  
rscadd: Noise on Ion/Emag/Law upload
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
only for the AI I assume? not everyone

**Comment by JamieD1** [comment]
> only for the AI I assume? not everyone

Yes, only for the affected user.

**Comment by yacabo** [comment]
Can you give us the audio file?

**Comment by JamieD1** [comment]
> Can you give us the audio file?

Its in the PR, you want me to pm you it on discord?

**Comment by MegaEmpirical** [comment]
Is there a cooldown for when you're getting spammed? Or something

**Comment by azzzertyy** [comment]
a totally non biased opinion
very useful and will help as law changes sometimes go unnoticed for a length of time as AI, as eyes arent always on the state laws button (or in the case of the new PR, the status tab)

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
