### PR TITLE
Adds "Sequence Break", a song by kilozombie, to the titlescreen.

### PR DESCRIPTION
**Pull request by Xoxeyos**
The link for the song is here, for your enjoyment. https://www.youtube.com/watch?v=lWi6ebOH0sU

🆑
rscadd: Adds the Song "Sequence Break" to the title screen.
/🆑

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Also fixes some line issues with the previous two songs.

**Review by Hopekz — APPROVED** [review]
Nice you even replaced super ugly spaces
Our almighty creative lead will decide your fate.

**Comment by Xoxeyos** [comment]
Yes, I am slowly learning the true powers of the dark side.

**Comment by Xoxeyos** [comment]
I'm in compile hell https://imgur.com/a/oFKdyXK

**Comment by Hopekz** [comment]
Push another commit. Should pop right back up fingers crossed

**Comment by JamieD1** [comment]
@Hopekz

**Comment by Hopekz** [comment]
> @Hopekz

What?

**Pull request closed without merging**
