### PR TITLE
Nightmares can now thrall people

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Nightmares can now thrall dead people, similar to changelings' absorb. This thralling sets their species to a shadowperson, and tells them they need to obey the nightmare. Once the thrall gets killed, they revert to their previous species and are therefore able to be cloned.

This is the first part of a nightmare improvement, turning it from a "lol let's murderbone" to something that's actually somewhat interesting. The second part will be giving the nightmare objectives to fullfill, but I haven't thought those out yet.

#### Changelog

:cl:  
rscadd: Nightmares are now able to thrall dead people, turning them into much weaker nightmares.
/:cl:

### CODE REVIEW

**Comment by drderp3635** [comment]
Slowly remaking shadowlings

**Comment by AsV9** [comment]
> The second part will be giving the nightmare objectives to fullfill, but I haven't thought those out yet.

**Comment by MacHac** [comment]
How about an objective related to their new thralling powers?  Say, they have to accumulate a certain number of thralls.  You could further incentivize it by giving them more night-related powers as they got more thralls, and maybe some sort of rediculous god mode once they get to the top.

Don't forget the reason that shadowling was removed in the first place.  It had severe balance issues, a tendency to snowball hard, and just wasn't very much fun to play.  It got removed altogether because the fundamental premise of a baddie that squats in maint all round and picks all its fights was pretty heavily flawed.  Let's at least get some lip service to the mistakes of the past before we make them all again.

Also, the lack of stuns or ranged options makes them somewhat useless in the current meta.  You can just wander into maint with a flashlight and a stunprod and start opening up the hidey holes, and you have a decent chance of hitting it before it hits you.  Then just keep it stunlocked while you beat it to death with a welder.  The original shadowling veil ability was AoE for a damn good reason, and if you don't give that to nightmares and want them to be an actual threat you had better fill that hole.

**Comment by ThatLing** [comment]
Don't know how to feel about making another conversion event. I know we have Alien Infestation but I've seen nightmare trigger more than xenos. Perhaps make it admin-only until you've finished objectives and what not?

Why this when there's a sling PR up?

**Comment by ghost** [comment]
There's already a sling PR up, so there's not much point to this unless the sling gets closed.

As a side note, this runs into somewhat of a similar problem as conversion antags can, as this basically turns any nightmare that gets entrenched into 5+ people bumrushing anyone stupid enough to enter maint alone, supported by a teleporting asshole with a fuck-you blade. 

Even with objectives, this pretty much makes nightmare into yet another 'call-the-shuttle-the-antag-spawned' random event.

**Pull request closed without merging**
