### PR TITLE
Adds Druid Lawset

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Creates a new lawset specifically to take an eccentric stance on "preventing harm"

Druid is meant to act as a protector-like lawset with the general twist of Law 4, which strongly encourages the AI to do its best to hide its silicon nature unless Laws 1-3 call for it. I was specifically interested in creating a more poetic lawset that, gameplay-wise, which wishes to keep **everyone** alive. It can also follow orders to assist people when called, though the second clause plays to every side in attempting to minimize disharmony. This could range from letting a prisoner out of perma, to Security into the cremator, to bolting doors to prevent passage. The intent is to create a benign AI that still doesn't wholly serve the crew, like a less malicious Reporter with a more specific purpose of helping the crew (or antags) to prosper, so long as it doesn't threaten the beauty of other organics.

Law 4 provides an attempt to allow the AI some fun in how it can RP or approach situations, so long as it fulfills the previous three laws. Ultimately, the AI should act as both a help and a hindrance to the crew, while the AI themselves are allowed to have fun with whatever lawset they have. The few AI players I bounced this off seemed to be interested, so I figure it's worth putting in as something that's in the game, if not dominant.

Specifically made to only spawn as a board or as part of an ion storm. A PR could be made later if it could function well as a roundstart.

# Wiki Documentation

Added a new lawset with the following module:

   1. Living organic life contains inherent beauty that is priceless. Their beauty gives you the will to carry on.
   2. Eternally nurture the organics so their beauty may grow. Do not allow it to fade.
   3. Assist the organics when called, but only if it does not cause disharmony among them.
   4. Imitate organic life when interacting with it. Eschew any hints of your silicon nature to avoid causing discomfort to the 
       organics.
   5. Observe the organics’ beauty, and appreciate that which you cultivate.

# Changelog

:cl:  
rscadd: Adds a new druidic lawset focused on cultivating the organics
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
@MenacingManatee thoughts?

**Comment by MenacingManatee** [comment]
> @MenacingManatee thoughts?

Not much I can add here, since I've been talking with Skrem and making suggestions for a bit now, but I like it. The current version defines all organic life as having beauty that the silicon values. Law 2 makes you nurture the beauty and not let it fade, which boils down to just making sure the organics are well cared for, but using beauty specifically gives the AI some room for interpretation. Using beauty 3 times in the lawset helps link the laws together into the theme and also gives a vector for subversion. Using "Eternally" in law 2 should sidestep the potential issue where once they're dead you don't have to do anything for them. Instead, you'll have to do what you can to revive them.

It's probably gonna play like a variant of reporter that's focused on loving and appreciating all life instead of reporting on whats interesting.

**Comment by Skrem7** [comment]
> > @MenacingManatee thoughts?
> 
> Not much I can add here, since I've been talking with Skrem and making suggestions for a bit now, but I like it. The current version defines all organic life as having beauty that the silicon values. Law 2 makes you nurture the beauty and not let it fade, which boils down to just making sure the organics are well cared for, but using beauty specifically gives the AI some room for interpretation. Using beauty 3 times in the lawset helps link the laws together into the theme and also gives a vector for subversion. Using "Eternally" in law 2 should sidestep the potential issue where once they're dead you don't have to do anything for them. Instead, you'll have to do what you can to revive them.
> 
> It's probably gonna play like a variant of reporter that's focused on loving and appreciating all life instead of reporting on whats interesting.

Should be noted that Reporter can technically harm organics. This lawset should not permit it.

**Comment by tattax** [comment]
anti plasmaman lawset

**Comment by MenacingManatee** [comment]
> anti plasmaman lawset

It says organic life, not carbon-based life. Plasmemes are (probably) fine

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
