### PR TITLE
Hypospray revamp (Vendor & Upgrades)

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Adds HypoMed and adds it to all in-rotation stations, a new wall-mounted vendor that carries equipment exclusively designed for hyposprays

Nothing in it is free to doctors, all of it has a price, to keep some form of balance

Everything hypospray related in NanoMed Plus was moved to HypoMed and prices were adjusted to make them more affordable to doctors

In the vendor there is 10 vials of every type, 5 of each general kit (basic/adv), and 3 of each type kit (there was only 1 of each before this??? you know theres more than one doctor right?)

Adds a quickload & piercing upgrade for hyposprays, one purchasable, one printable

Removes styptic powder and silver sulfadiazine sprays from NanoMed Plus and NanoMed

Box | Meta | Gax
  

## Why?

Having a separate vendor makes hyposprays much simpler and more approachable to newer players or players that have not played medical since their addition

I hate saving up to buy the kits. They are still available and are at a discounted price than buying vials individually (bundle deal and whatnot), but letting players pick and choose and budget exactly what they want is a huge QoL upgrade

Some old kits were also ridiculously expensive for no good reason so the price has been reduced on those

Hyposprays are purchased separately as part of the "pick and choose" deal

Players were massively upset that they couldn't quickload vials (unless they were mining medic hehehehhe) so there's a purchasable upgrade for that now!

Removing styptic powder and silver sulfadiazine sprays is a necessity because they eliminate one of the hypospray's core purposes

## Counterpoint

Yes, this devalues chemistry a bit for the specific chemicals that it offers. However, this shit ain't free or cheap. **Doctors are paid extremely shit wages**, so refills from chemistry are still completely viable, especially once bluespace vials are researched.

# Spriting
 

# Wiki Documentation

## Contents of the HypoMed are as follows:

- 5 hyposprays - 50 credits each
- 5 hypospray quickload upgrades - 50 credits each
- 10 libital vials - 25 credits each
- 10 aiuri vials - 25 credits each
- 10 charcoal vials - 25 credits each
- 10 perfluorodecalin vials - 25 credits each
- 10 epinephrine vials - 25 credits each
- 10 styptic powder vials - 30 credits each
- 10 silver sulfadiazine vials - 30 credits each
- 10 salicyclic acid vials - 50 credits each
- 10 oxandrolone vials - 50 credits each
- 10 calomel vials - 50 credits each
- 10 coagulant vials - 50 credits each
- 5 basic hypospray kits (no hypospray included) - 100 credits each (with hypo was 300)
- 5 advanced hypospray kits (no hypospray included) - 200 credits each (was 300, with hypo was 500)
- 3 brute hypospray kits (no hypospray included) - 100 credits each
- 3 burn hypospray kits (no hypospray included) - 100 credits each
- 3 toxin hypospray kits (no hypospray included) - 100 credits each
- 3 oxygen hypospray kits (no hypospray included) - 100 credits each

## Hypospray piercing upgrade

- Locked behind Advanced Biotechnology
- list(/datum/material/glass = 2000, /datum/material/diamond = 1000)

# Changelog

:cl:  
rscadd: Added HypoMed to Box, Gax, and Meta stations, a hypospray vendor filled with hyposprays, upgrades, vials, and kits
rscadd: Reduced the prices of some hypospray kits and removed the hypospray from them
rscadd: Added hypospray quickload upgrade, purchasable from HypoMed
rscadd: Added hypospray piercing upgrade, printable alongside piercing syringes once Advanced Biotechnology is researched
rscdel: Removed hypospray equipment from NanoMed Plus
rscdel: Removed styptic powder and silver sulfadiazine sprays from NanoMed Plus and NanoMed
/:cl:

### CODE REVIEW

**Comment by GraveHat** [comment]
A good source of vials as chemistry would still refuse to actually make use of them on the day-to-day. Giving a reason for med docs to do bounties and ask for a cut of the bounty so they can buy the kits without waiting for half the round, as simply giving the doctors more medicine, in general, would be quite the buff so I'm glad it isn't totally free but the option still exists.

**Review by ToasterBiome — APPROVED** [review]
map fine i dunno if it's balanced

**Comment by JamieD1** [comment]
Anyway you could move it to a wall without another decal on? Just makes it look less crap in the map. @ToasterBiome Should know better D:

**Comment by ynot01** [comment]
> Anyway you could move it to a wall without another decal on? Just makes it look less crap in the map. @ToasterBiome Should know better D:

wasn't any open spaces, it looks fine ingame though

**Review by KillerOrcaCora — DISMISSED** [review]
It needs to not be submerged into other decals on the walls.

**Comment by ToasterBiome** [comment]
> Anyway you could move it to a wall without another decal on? Just makes it look less crap in the map. @ToasterBiome Should know better D:

only one I would think about changing is box's, we have a lot of overlapping things where it can be reasonably assumed that you will not be seeing both at the same time (see, metas) If ynot really wants to be gungho, move the board since it's a good place for the vendor.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
fix the box one and the meta one *rolling eyes emoji*

**Comment by ToasterBiome** [comment]
image

**Review by ToasterBiome — APPROVED** [review]

**Review by cuackles — APPROVED** [review]
Ye

**Pull request merged**
