### PR TITLE
Makes polysmorphs mentor only

### PR DESCRIPTION
**Pull request by Mqiib**
Ok so I had a hard think about this one and what CM has to worry about with the whole intellectual property thing and I had a BRAIN BLAST while taking a shower (because that's where the best thinking happens as we all know.) It occurred to me that if we make xeno-hybrids a donor race not only would lots of people maybe possibly play a supposedly rare species but also we'd basically be "selling" someone else's intellectual property (xenomorphs kinda) so INSTEAD I am making it so that mentors (me included) have them available round start since we don't pay for them we just are volunteers and are rewarded something something court case harder to get DMCA'd or whatever. This also means that we might actually start seeing polysmorphs played in real rounds.

Anywho, credit to @EdgeLordExe for his code that I 100% shamelessly stole to make this work (the relatively tiny changes they may be) from pr #10186 ! I appreciate you immensely and have the bits that are most definitely gonna need fixed, depending on whose pr gets merged first. Thank you and please don't shoot me I'm just bad at code is all!

core/modules/client/preferences line 1416-1430ish, if("species") var/result section
"                                                    line 1890-1920ish, var/datum/species/chosen_species  if(roundstart_checks && ...) bit

#### Changelog

:cl:  
rscadd: Makes polysmorphs mentor-only
experimental: Empowers mentors
/:cl:

### CODE REVIEW

**Comment by LazennG** [comment]
THIS IS JUST A SEGWAY INTO SEEING THE HUGE PLASMA VESSELS YOU SPRITED

**Comment by Mqiib** [comment]
> THIS IS JUST A SEGWAY INTO SEEING THE HUGE PLASMA VESSELS YOU SPRITED

I did not sprite those, that was tex/arthas/war0100, I just want to fucking play the goddamn race. Hell, I actually REMOVED one of the plasma vessels.

**Comment by LazennG** [comment]
fuck i thought i saw you say the other day you made some additional resprites and posted huge fuckign vessels

**Comment by Mqiib** [comment]
> fuck i thought i saw you say the other day you made some additional resprites and posted huge fuckign vessels

No I added new heads and dorsal tubes as well as digitigrade legs. I only ever removed plasma vessels and changed the shading on them to fit the colors of when I had to greyscale polysmorphs. I'm not bad, I swear.

**Comment by cuackles** [comment]
While you are on it add the plasma vessels back 👀

**Comment by Mqiib** [comment]
> While you are on it add the plasma vessels back 👀

haha that's a funny joke you're a funny guy

**Comment by ynot01** [comment]
as long as these "plasma vessel" titties exist at all i will never support polysmorph being added in any way

also this is stupid

**Review by SomeguyManperson — APPROVED** [review]
napalm (2)

**Comment by Tipy1802** [comment]
I am pretty sure the one day plasma vessels are the same size as human titties

**Comment by Marmio64** [comment]
mentor brain supports this, i say yes

**Comment by Hopekz** [comment]
If DMCA is the real concern the only real option should be full removal. 

Also, I don't like where this is going in terms of game direction. You're locking a full feature to a select few.
A feature with upsides and downsides since this isn't a reskin.
**Features locked to a handful of people should NOT have upsides and downsides.**

**Comment by jcatjmeow** [comment]
I do not support this for a few reasons.
1) Donor races in general are scummy. Especially when they have upsides.
2) It's entirely reasonable that people would either confuse these guys and xenos together (or pretend to as an excuse to grief) and lead to a lot of confusion and damage to both parties.
3) The race is nonsensical in our 'lore' little as it might be. Why would these hybrids exist? Why are they employed on a space station?
4) The race is fetish content. Obviously, plasma vessels nonwithstanding, (lol) the spriter and creator of these has admitted that they are fetish content. They're literally tiddy xenos. It's the xenomaid meme but even worse.
5) We are not citadel.

And obviously
6) we do not own the copyright to this. CM already got hit.

obviously leaving this open for the 24, yadda yadda, but unless these are addressed this will be closed.

**Comment by Hopekz** [comment]
> 6) we do not own the copyright to this. CM already got hit.

Bad reason for this PR since this PR isn't adding them to the codebase; they're already here.

**Comment by Mqiib** [comment]
> I do not support this for a few reasons.
> 
> 1. Donor races in general are scummy. Especially when they have upsides.
> 2. It's entirely reasonable that people would either confuse these guys and xenos together (or pretend to as an excuse to grief) and lead to a lot of confusion and damage to both parties.
> 3. The race is nonsensical in our 'lore' little as it might be. Why would these hybrids exist? Why are they employed on a space station?
> 4. The race is fetish content. Obviously, plasma vessels nonwithstanding, (lol) the spriter and creator of these has admitted that they are fetish content. They're literally tiddy xenos. It's the xenomaid meme but even worse.
> 5. We are not citadel.
> 
> And obviously
> 6) we do not own the copyright to this. CM already got hit.
> 
> obviously leaving this open for the 24, yadda yadda, but unless these are addressed this will be closed.

Alright some of these issues can be dealt with.
1: Yes, pay to win is kinda bad but in this case it isn't strictly pay to win, it's volunteer to sidegrade at best. Plus we can, with your removal of the titties, arguably make it a roundstart race since it's significantly less controversial. Alternatively we could even make a *gasp* whitelist.
2: They look distinctly different from normal xenomorphs to the point that I really don't think this is a problem. The posture is COMPLETELY different as well as the shading. They also don't move super fast and do actual xenomorph stuff.
3: The lore is something like genetic experimentation by NT to make more obedient xenomorphs or something. It can be expanded upon if need be.
4: It's significantly LESS fetish content with the advent of #10243 which I have decided I now support fully.
5: Correct.
6: That's the idea behind making it specifically not donor-only: so that we aren't "making money" off of it albeit indirectly.

I hope this addresses some of your concerns.

**Comment by jcatjmeow** [comment]
> Alright some of these issues can be dealt with.
> 1: Yes, pay to win is kinda bad but in this case it isn't strictly pay to win, it's volunteer to sidegrade at best. Plus we can, with your removal of the titties, arguably make it a roundstart race since it's significantly less controversial. Alternatively we could even make a _gasp_ whitelist.
> 2: They look distinctly different from normal xenomorphs to the point that I really don't think this is a problem. The posture is COMPLETELY different as well as the shading. They also don't move super fast and do actual xenomorph stuff.
> 3: The lore is something like genetic experimentation by NT to make more obedient xenomorphs or something. It can be expanded upon if need be.
> 4: It's significantly LESS fetish content with the advent of #10243 which I have decided I now support fully.
> 5: Correct.
> 6: That's the idea behind making it specifically not donor-only: so that we aren't "making money" off of it albeit indirectly.
> 
> I hope this addresses some of your concerns.

Eh.
They do look differentish from normal xenos. I would like a distinct color, perhaps. 
Lore is still ass. Wether it's your job to fix that or not I'm not sure. Probably a wiki thing I guess? I just don't really get what justifies their existence. It was made as "xenopeople" first and then the justifications were decided after the fact. 

Still don't like it, but it's not "close this right now" bad. Just, not my cup of tea, not something I think belongs here, but it's not unsalvageable.

**Review by jcatjmeow — APPROVED** [review]
Code's fine

**Comment by Mqiib** [comment]
I have been trying my damndest to make these more than haha fetish xenopeople. I'd rather commit to putting a bit more work in now than just having all the stuff I've already done yeeted. If I have to be the one to add some lore to them then so be it.

**Comment by Marmio64** [comment]
If all else fails, make polysmorph be slightly more powerful and lock it behind xenobiolgy

**Comment by Mqiib** [comment]
> If all else fails, make polysmorph be slightly more powerful and lock it behind xenobiolgy

Yeah but then you can't customize them, you're stuck with (mostly) random features.

**Comment by swissloaf** [comment]
No.

**Comment by Mqiib** [comment]
> No.

Please use more than one word to explain why you don't like this pr. See ynot's comments for reference.

**Comment by swissloaf** [comment]
Sorry, my bad.

Double no.

**Comment by boodaliboo** [comment]
why do we need alien booby race were not vore

**Comment by Mqiib** [comment]
> why do we need alien booby race were not vore

See #10243

**Comment by Amelia0010** [comment]
The entire race is stupid and so is the notion of locking them to mentors

**Comment by JamieD1** [comment]
Lets see if its viable with mentors first, they will be our guinea pigs for seeing if its a viable station species.

**Pull request merged**
