### PR TITLE
Give the chaplain his pet back

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Gives Chaplain his bat back
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Gives Chaplain his bat back
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
@00ze-cyclone

**Comment by ReddicusDragon** [comment]
Simple, do other maps have this bat already?

**Comment by Simplehorror** [comment]
no

**Comment by ReddicusDragon** [comment]
add him to other maps too

**Comment by JamieD1** [comment]
other maps

**Comment by Simplehorror** [comment]
@JamieD1 ok done

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
every map in rotation

**Comment by Simplehorror** [comment]
> every map in rotation

im not touching WIP maps and gax and asteroid are still wip

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Gax is a fully released map. Months old at this point.

**Comment by ReddicusDragon** [comment]
Asteroid is dogshit

**Comment by Simplehorror** [comment]
gax done

**Comment by JamieD1** [comment]
Do asteroid too

**Comment by Simplehorror** [comment]
argh

**Comment by ToasterBiome** [comment]
Reopen when asteroid done

**Comment by Marmio64** [comment]
unless this is related to the pet assassination objective, this is stupid that you have to add something as trivial as a pet to every map. Not only may you just not want to do it (map creators forcing others to spend more effort on map modifications), but there can be variety in maps in that some may have something while others don't.

**Comment by N3D6** [comment]
> unless this is related to the pet assassination objective, this is stupid that you have to add something as trivial as a pet to every map. Not only may you just not want to do it (map creators forcing others to spend more effort on map modifications), but there can be variety in maps in that some may have something while others don't.

consistency

**Comment by KillerOrcaCora** [comment]
The whole maps having things other dont is the whole reason no one wants to play anything but box

**Comment by Simplehorror** [comment]
i can't add it to asteroid, it's WIP

**Pull request closed without merging**
