### PR TITLE
Gives detective access to the sec office

### LINKED ISSUE #4788: Detective lacks department lathe access
Detective cannot reach the department lathe since he doesn't have sec office access.

### PR DESCRIPTION
**Pull request by adamsong**
# General Documentation

### Intent of your Pull Request

Gives the detective to the sec office where the sec protolathe is.

### Why is this change good for the game?

The detective needs access to a protolathe, this gives it to them.

# Changelog
Fixes #4788

:cl:  
tweak: adds forensics access to the sec protolathe
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Fixes #4788

**Comment by Bibby0110** [comment]
> Fixes #4788

add it to the PR body

**Comment by adamsong** [comment]
Thanks

**Comment by patpol4** [comment]
Probably wiser to just change the access on his id so this applies to all stations

**Comment by adamsong** [comment]
That would also give him access to the equipment room

**Review by patpol4 — CHANGES_REQUESTED** [review]
Oh right, well this seems fine then, just make this consistent for all the other stations too

**Comment by adamsong** [comment]
Working on that now, some of the stations already had it

**Review by patpol4 — APPROVED** [review]
Map is fine, I want HC to decide on this since opinions seem to be divided.

**Comment by adamsong** [comment]
I would appreciate the reason for the downvotes, is it because detective shouldn't have sec lathe access, or because they shouldn't have access to the room the sec lathe is in?

**Comment by maxion12345** [comment]
Protolathe access? Good idea. Not only can det print more ammo, he'll gain access to all the upgrades sec gets (new scanner, bodycam, whatever).

**Comment by JamieD1** [comment]
Will expand on this with bibbys PR.

**Pull request merged**
