### PR TITLE
[Semi-Port] New Heretic Path: Knock

### PR DESCRIPTION
**Pull request by cowbot92**
Full credit for most of everything in this PR goes to the original: https://github.com/tgstation/tgstation/pull/78108
Sprites for the blade go to @thegoldencat413 

# Document the changes in your pull request

Adds a new heretic path: Knock

"A Locksmith’s Secret" - Allows you to transmute a knife and a crowbar into a Key Blade. Additionally, your grasp will open up numerous locked things when used upon them.

"T1 - Key Keeper’s Burden" - Allows you to transmute a wallet, an iron rod, and an ID card to create an Eldritch Card. It functions the same as an ID Card, but attacking an ID card with it fuses them, causing it to gain the original's access (like an agent ID). You can use it in-hand to change its form. Does not preserve the card used in the ritual. Will also allow you to open portals at airlocks to travel between, with a maximum of two."

"Grasp Mark - Mark of Knock" - Your Mansus Grasp now applies the Mark of Knock. Attack a marked person to bar them from all passages for the duration of the mark. People marked will be unable to access doors their ID has access to for 10 seconds (I.e engineers cannot access engineering doors, sec cannot access sec)

"T2 - Burglar's Finesse" - "Grants you Burglar's Finesse, a single-target spell that puts a random item from the victims backpack into your hand."

"Blade Upgrade - Opening Blade" - "Your blade will be able to pry open unlocked airlocks." (This is like a changeling armblade when used on harm intent)

"T3 - Freedom Forever" - "Grants you Freedom Forever, a spell that will cause reality to warp around you for a few seconds, confusing enemies and allies alike."

"Ascension Rite - Many secrets behind the Spider Door" - Bring 3 corpses to a transmutation rune to complete the ritual. When completed, you gain damage resistance, and stun immunity and in addition, create a tear to the Spider Door; a tear in reality located at the site of this ritual. Eldritch creatures will endlessly pour from this rift who are bound to obey your instructions." - (cannot summon ascension level monsters like armsky/armsky prime/star gazer)

# Why is this good for the game?

More options! Huzzah! This is the final pre-existing TG path, meaning once it gets merged (or doesn't...) I can start working on the final few minor things, balance changes, and ascension updates! This path, much like cosmic, is focused a LOT on utility versus combat capability, which will hopefully help to round out the options heretics have to choose from to create a good balance of "What type of heretic you want to play"

# Testing
All testing for EVERYTHING was done in the video below. 

https://github.com/yogstation13/Yogstation/assets/75333826/54f0b83c-c64b-4682-afa8-432325f0984e

# Spriting

image
knock_blade

reality_crack
yackitysax

# Wiki Documentation

I will add this to the wiki

# Changelog

:cl:  
rscadd: Adds new heretic path
soundadd: Adds new heretic sounds
imageadd: Adds new heretic portal icon and abilities
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
this pr fails LINTS!
Laugh at this person!

**Comment by Yarinoi** [comment]
lets fucking GOOO

**Comment by MajManatee** [comment]
Whos there?

**Review by cuackles — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]
code looks fine

**Comment by thegoldencat413** [comment]
### _Sooner or later, every locksmith has the Dream. Now we recite its seven phases..._

**Review by ToasterBiome — APPROVED** [review]
sound ok

**Pull request merged**
