### PR TITLE
Massive MetaStation service changes

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

This PR does many different things to the service area on MetaStation

- Moves the theater backstage from the south of theatre to the north of the theater
- Shortens theater height by 1 to fit bigger theater backstage in the north
image
- Moves kitchen receiving from south of the cold room to the east of the cold room.
image
- Pushes all of hydroponics back 5-6 tiles east (their backroom now takes up where Janitor's closet used to be)
image
- Removes the room leading to hydroponics in favor of a hallway with a maint door
- moves janitors closet to where the hydroponics entry room used to be
image
- moves service hall slightly up to accommodate hydroponics back room
image

# Wiki Documentation

All of these need new images

# Changelog

:cl:  
tweak: Moves the theater backstage from the south of theatre to the north of the theater
tweak: Shortens theater height by 1 to fit bigger theater backstage in the north 
tweak: Moves kitchen receiving from south of the cold room to the east of the cold room.
tweak: Pushes all of hydroponics back 5-6 tiles east (their backroom now takes up where Janitor's closet used to be)
tweak: Removes the room leading to hydroponics in favor of a hallway with a maint door
tweak: moves janitors closet to where the hydroponics entry room used to be
tweak: moves service hall slightly up to accommodate hydroponics back room
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Ah fuck me, it undid the RD's hardsuit change, how to fix?

**Comment by Cartlord** [comment]
Question - would it be possible to create a little nook of some kind by Hydro or Kitchen, similar to Box's recessed counter, for the placement of a public drying rack for raisins or jerky? Possibly remove the table with the books between the seed machines, move the books to the public garden if that room doesn't have books already?

**Comment by ToasterBiome** [comment]
> Question - would it be possible to create a little nook of some kind by Hydro or Kitchen, similar to Box's recessed counter, for the placement of a public drying rack for raisins or jerky? Possibly remove the table with the books between the seed machines, move the books to the public garden if that room doesn't have books already?

If Wej approves of my requests I can change it. Waiting for Wej's response

**Comment by patpol4** [comment]
Bold of you to make such a big pr before another metastation pr is merged but sure

**Comment by TheLinuxOS** [comment]
> Bold of you to make such a big pr before another metastation pr is merged but sure

Bold of him to assume that the effects of this PR will even be appreciated by the player base in their undying hatred for metastation

**Comment by ToasterBiome** [comment]
> > Bold of you to make such a big pr before another metastation pr is merged but sure
> 
> Bold of him to assume that the effects of this PR will even be appreciated by the player base in their undying hatred for metastation

I hate metastation

will fix merge conflicts tomorrow (help wej)

**Comment by ToasterBiome** [comment]
merge conflicts broken

**Pull request closed without merging**
