### PR TITLE
[ADMIN] SHITTER system. A system for catching obvious lowpop griefers

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

Basically, we track a score of how bad you've been.
If this score is above a threshold you're kicked out of the round.

Only applies to lowpop rounds and people below 25 hours of playtime

Kicked out upon reaching 75 points. You lose 1 point per 10 seconds

Points gained by:
Attacking non-antags: 5
Stunbatoning non-antags: 3
Setting air alarms to anything but filtering: 25
Touching pipes in atmospherics: 20
Breaking the pretty filter: 20

- [ ] atmos tech exemption
- [ ] sec officer exemption

# Wiki Documentation

# Changelog

:cl:  
experimental: Experimental system for catching lowpop griefers
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Thanks Bibby

**Comment by N3D6** [comment]
Can we make it so that if they’re sec it doesn’t give you points for batoning anybody so you don’t get banned for playing the game

**Comment by neeshacark** [comment]
Inb4 lowpop atmospheric technicians get banned for making infinite metallic hydrogen

**Comment by bruhlookatthisdood** [comment]
be atmospheric technician > do your job > make burn chamber > kicked for touching pipes > rejoin > set air alarms to contaimineted/cycle/siphon because medbay is on fire > get kicked for stopping fire

**Comment by N3D6** [comment]
This only applies to people who don’t have that many hours I doubt any brand new players are gonna be cranking out atmos projects

**Comment by patpol4** [comment]
Make sure it only applies to nonantags and probably give admins ability to toggle it for players who are actually legit. 
Pretty good idea 👍

**Comment by gaminada** [comment]
This is great. Though i would also include blowing up welding fuel tanks and triggering firebombs. Shouldnt it also include opening canisters containing plasma? In case they get access to toxins storage?

**Comment by Bibby0110** [comment]
> Make sure it only applies to nonantags and probably give admins ability to toggle it for players who are actually legit. Pretty good idea 👍

not sure you'd be able to judge a person in 25 hours, other than metacomming



> This is great. Though i would also include blowing up welding fuel tanks and triggering firebombs. Shouldnt it also include opening canisters containing plasma? In case they get access to toxins storage?

it can include anything we want

**Comment by maxion12345** [comment]
what does SHITTER stand for, gamer

**Comment by AnCopper** [comment]
> what does SHITTER stand for, gamer

S - Shitter
H - Hitter
I - Itter
T - Tter
T - Ter
E - Er
R - R

**Pull request closed without merging**
