### PR TITLE
Adds a little sound effect that plays when speaking

### PR DESCRIPTION
**Pull request by Moltijoe**
Stolen from monkestation code, but i couldn't find the PR (i just went directly into their code)

# Why is this good for the game?
makes it easier to tell when someone is speaking

# Testing
https://github.com/user-attachments/assets/dae8b0da-f6bc-4722-88fd-1b497d4a50b7

:cl:
rscadd: Adds a little sound effect that plays when speaking
soundadd: Speach sound effects
/:cl:

### CODE REVIEW

**Comment by Oblisk234** [comment]
Does this respect deafness (Both quirk and ear damage)?

**Comment by CrazyDrakkon** [comment]
A moment of remembrance for our dearly departed TTS sadge

**Comment by ToasterBiome** [comment]
test this

**Review by ToasterBiome — APPROVED** [review]
i dont really like the noises but it's whatever

**Pull request merged**
