### PR TITLE
Correctly makes mood required for Family Heirloom quirk

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

What it says on the tin

# Changelog

:cl:  
bugfix: sets mood to TRUE for family heirloom quirk
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
Wait it still has the total of 0? Lmao

**Comment by Aquizit** [comment]
Yeah it's considered "neutral"

**Comment by KingSuperBOB** [comment]
So why do you need mood if its worth 0 (even though it should clearly be a -1)

**Comment by Aquizit** [comment]
Not the scope of the PR really. I'm just fixing an error as the heirloom is coded to affect mood so mood should be mandatory to use it. Quirk value isn't the thing I'm trying to fix.

**Comment by neeshacark** [comment]
nooo my neet free trinkets!!

**Review by ToasterBiome — APPROVED** [review]

**Comment by Hislyna** [comment]
Why would you take this quirk when its literally a debuff without any benefits

**Pull request merged**
