### PR TITLE
Revert "Makes station threats trigger gamma alert" because Its a stupid change because it prevents events on nukies and clockies

### PR DESCRIPTION
**Pull request by alexkar598**
Reverts yogstation13/Yogstation#12134

Its a stupid change because it prevents events on nukies and clockies

### CODE REVIEW

**Comment by adamsong** [comment]
It was approved, and I waited 24 hours to merge it

**Comment by Marmio64** [comment]
I kinda like the pr but self merging a decently major change within a single day while other PRs have to sit around rotting for weeks?

**Comment by yacabo** [comment]
> I kinda like the pr but self merging a decently major change within a single day while other PRs have to sit around rotting for weeks?

**Comment by alexkar598** [comment]
Pr reasoning changed from self merge to:
Its a stupid change because it prevents events on nukies and clockies

**Review by Bibby0110 — APPROVED** [review]

**Comment by JamieD1** [comment]
Abductors spawned today on a clockies round literally 5 seconds before gamma was called and completely fucked up the round.

This itself has completely justified the need for this PR for me.

**Comment by Bibby0110** [comment]
> Abductors spawned today on a clockies round literally 5 seconds before gamma was called and completely fucked up the round.
> 
> This itself has completely justified the need for this PR for me.

And the abductors did what exactly for the 5 seconds where people were still on the station?

**Pull request closed without merging**
