### PR TITLE
Removes felinid language and allows felinids to speak english

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Felinids are human, therefore they should be able to speak the human racial language. Alternatively I could make it so they can only understand english. Untested, should work.

# Wiki Documentation

If languages are mentioned on the wiki, then it should probably be added that felinids are able to speak english. 

# Changelog

:cl:   
tweak: felinids can now speak english 
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
pay for two racial languages, degenerate pay2win

**Comment by ToasterBiome** [comment]
upvote

**Comment by nmajask** [comment]
> pay for two racial languages, degenerate pay2win

In that case, maybe they shouldn't have their own language

**Comment by Marmio64** [comment]
felinids arent british, therefor they shouldnt know the language. Space ninjas going to start speaking english again cause they're humans even though they are japanese and not british?

**Comment by boodaliboo** [comment]
> > pay for two racial languages, degenerate pay2win
> 
> In that case, maybe they shouldn't have their own language

we already have donor lizard metagang we dont need another

**Comment by ToasterBiome** [comment]
> > > pay for two racial languages, degenerate pay2win
> > 
> > 
> > In that case, maybe they shouldn't have their own language
> 
> we already have donor lizard metagang we dont need another

felinid metagang was created to destroy lizard metagang

**Comment by Marmio64** [comment]
> > > > pay for two racial languages, degenerate pay2win
> > > 
> > > 
> > > In that case, maybe they shouldn't have their own language
> > 
> > 
> > we already have donor lizard metagang we dont need another
> 
> felinid metagang was created to destroy lizard metagang

if so, it failed, since lizard metagang still exists along with felinid metagang

**Comment by Hopekz** [comment]
Each species already has their own language including feline.
You have provided no reasoning to the obvious change outcome which would be felines having two languages except brushing it off as "maybe they shouldn't".
Your PR doesn't even get you closer to the "maybe they shouldn't" vision of the game therefore this is a bad PR.

**Review by adamsong — CHANGES_REQUESTED** [review]
Remove felinid langauge

**Comment by ToasterBiome** [comment]
> Remove felinid langauge

dont remove felinid language

**Comment by nmajask** [comment]
> Remove felinid langauge

done

**Comment by ToasterBiome** [comment]
not cool

**Comment by nmajask** [comment]
> not cool

i just do as the council man says

**Comment by ToasterBiome** [comment]
misleading title, please close

**Comment by nmajask** [comment]
> misleading title, please close

better?

**Comment by ToasterBiome** [comment]
> > misleading title, please close
> 
> better?

no, seems like you’re removing something just to be a dick about it.

**Comment by KillerOrcaCora** [comment]
Please don't remove felind language and give absolutely boring "haha britush" language.

**Comment by nmajask** [comment]
> no, seems like you’re removing something just to be a dick about it.

The entire reason I made this PR with the only justification being that they are human was to maybe get council or anybody to take a stronger stance on felinids being reskins of humans or changing how they are handled to allow for differences from humans. Clearly this didn't work and now I am doing the opposite to try to get someone to say something about this.

**Comment by ToasterBiome** [comment]
> > no, seems like you’re removing something just to be a dick about it.
> 
> The entire reason I made this PR with the only justification being that they are human was to maybe get council or anybody to take a stronger stance on felinids being reskins of humans or changing how they are handled to allow for differences from humans. Clearly this didn't work and now I am doing the opposite to try to get someone to say something about this.

It's pretty clear where they're stood: Equal. They have extremely negligible differences (the 3 I can point out are felinid language, liking seafood, and potentially healing from cilk). These are on par or even less than different races, none being pay to win as everyone still speaks common. If felinids had a slime network that all felinids could talk on then that would be pay to win, but as it stands right now they're the same, which is how it's been the entire time.

**Comment by N3D6** [comment]
This is a stupid ass remove. Every other race gets a snowflake language. Why do we need to remove a unique language so felinids can get a recycled language literally no felinid players want.

**Comment by MegaEmpirical** [comment]
This is a good change and makes sense. Felinids are surgically modified humans so this should be their language.

**Comment by Hopekz** [comment]
> This is a good change and makes sense. Felinids are surgically modified humans so this should be their language.

So a preterni is a human when they get "surgically modified"? "Surgically modified " is just lore flavour text to show that another species has been created.

According to what we have in how they're represented in-game and mechanics, they're a separate species.

Having an item be a child of something in-code is done for ease of coding versus being meant to be "related" in-lore.

The surgical argument is feeble, in my opinion, since yes, you can remove the tail and ears from them, but even after you remove the tail, a feline isn't going to transform into a human; they remain a feline (just like how a lizard isn't a human just because you take their tail)

**Comment by MegaEmpirical** [comment]
> So a preterni is a human when they get "surgically modified"? "Surgically modified " is just lore flavour text to show that another species has been created.
> 
> According to what we have in how they're represented in-game and mechanics, they're a separate species.
> 
> Having an item be a child of something in-code is done for ease of coding versus being meant to be "related" in-lore.
> 
> The surgical argument is feeble, in my opinion, since yes, you can remove the tail and ears from them, but even after you remove the tail, a feline isn't going to transform into a human; they remain a feline (just like how a lizard isn't a human just because you take their tail)

Yes.

Yes but irrelevant. 

No idea what the significance is here.

That is how we've justified it lore wise. If the code refuses to reflect it that's not my problem.

**Comment by KillerOrcaCora** [comment]
No one even wants this...look at the downvotes...

**Comment by ToasterBiome** [comment]
> No one even wants this...look at the downvotes...

Sadly, downvotes mean nothing when it comes to what people will strong arm into or out of the game. It’s ultimately up to the HCs to decide this or host if it comes down to it.



> > So a preterni is a human when they get "surgically modified"? "Surgically modified " is just lore flavour text to show that another species has been created.
> > According to what we have in how they're represented in-game and mechanics, they're a separate species.
> > Having an item be a child of something in-code is done for ease of coding versus being meant to be "related" in-lore.
> > The surgical argument is feeble, in my opinion, since yes, you can remove the tail and ears from them, but even after you remove the tail, a feline isn't going to transform into a human; they remain a feline (just like how a lizard isn't a human just because you take their tail)
> 
> Yes.
> 
> Yes but irrelevant.
> 
> No idea what the significance is here.
> 
> That is how we've justified it lore wise. If the code refuses to reflect it that's not my problem.

language in game refers to making a language to talk between felinids besides the humans who made them.

**Comment by Hopekz** [comment]
> Yes.
> 
> Yes but irrelevant.

Completely relevant.  
You just agreed on the preterni similarity meaning that to justify removing the feline language from the feline, you would also have to be in favor of eliminating encoded audio from Preterni and replacing it with the English language.

Your argument is weak and all over the place.

**Pull request closed without merging**
