### PR TITLE
Adds a fax machine to IceMeta LawOffice. (minor edits)

### PR DESCRIPTION
**Pull request by wonderinghost**
we are not going to forget law office here either.
# Document the changes in your pull request
adds a fax machine to law office. along with pens and a table
removes a cable running through the middle of the office.
removes dately pda cartridge

NOTE:
README file details mapmerge breaking multi z maps and to build with fastdmm2

# Changelog

:cl:  
mapping: Minor changes to law office
mapping: Deletes old pda cartridge
mapping: Adds printer and pens
Mapping removes wire running through middle of the office
/:cl:

### CODE REVIEW

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
Document the other changes in your PR please :)

**Review by wonderinghost — COMMENTED** [review]
fixed it

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
image
youve got a wooden table under robotics part vendor that probably shouldnt belong there

**Review by Ethan4303 — APPROVED** [review]
Yippee Fax

**Pull request merged**
