### PR TITLE
Ports tgui-next

### PR DESCRIPTION
**Pull request by Amelia0010**
see: https://github.com/orgs/tgstation/projects/3#card-29553852

TGUI-next is TGUI but objectively better, it opens faster and looks much much nicer.

Only UI I've scrapped that we use is the mint, since that requires a rework (I'll probably just end up removing the mint entirely)

I'll keep updating this PR as more TGUI-next PRs are merged on /TG/, and after this is merged I'll do some QoL reworks like adding tgui-id and ui_x, ui_y vars to objects

PRs merged since this PR was completed
- [x] https://github.com/tgstation/tgstation/pull/47990

### CODE REVIEW

**Comment by boodaliboo** [comment]
is this going to have the traitor uplink ui change and is there anything that needs to be changed with it if so

**Comment by Xoxeyos** [comment]
I believe chem machines already got macros removed from them, it's been like that for a while.

**Comment by boodaliboo** [comment]
> I believe chem machines already got macros removed from them, it's been like that for a while.

tg has macros and hes porting tg ui stuff

**Comment by Xoxeyos** [comment]
> 
> 
> > I believe chem machines already got macros removed from them, it's been like that for a while.
> 
> tg has macros and hes porting tg ui stuff

Oh, thanks for letting me know.

**Pull request merged**
