### PR TITLE
Modifies homophobic code / entries before the github police gets here

### PR DESCRIPTION
**Pull request by Hopekz**

### CODE REVIEW

**Comment by azzzertyy** [comment]
how are rainbow shoes homophobic when its literally the gay flag

**Comment by nesisknesis** [comment]
🏳️‍🌈

**Comment by Hopekz** [comment]
> how are rainbow shoes homophobic when its literally the gay flag

I don't think its bad here but TG literally got taken down for a similar reason.

I just don't want this place to be taken down over having the word "gay" in the wrong place according to what github deems acceptable.

I'm fine with removing the possibility of this happening and losing "gay" being used the right way on these clown shoes.

**Comment by Alexandria404** [comment]
When github is so idiotic and vague about what is an issue and what is not.
This becomes the response.
Dark times.

**Comment by athena413** [comment]
good

**Pull request merged**
