### PR TITLE
stabilized red extract makes you a bit faster but doesnt have slowdown immunity

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
me completely ignoring game mechanics because i spent 20 minutes in my xenobio mancave so now i have a nukeop elite hardsuit with no downsides (also you cant slow me with damage)

# Changelog

:cl:  
tweak: stabilized red extracts make you faster instead of giving you slowdown immunity
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
did you forget about the speed potion? also, walking slower is not a game mechanic. make it slowdown immune for clothing

**Comment by UltraBigRat** [comment]
> did you forget about the speed potion? also, walking slower is not a game mechanic. make it slowdown immune for clothing

speed potions basically dont work on anything anymore

**Comment by JamieD1** [comment]
Pile them on, fuck xenobio

**Review by JamieD1 — APPROVED** [review]

**Comment by Simplehorror** [comment]
actually i'm happy with this, speed is OP

**Comment by Simplehorror** [comment]
wait no i'm not fuck xenobio

**Pull request merged**
