### PR TITLE
brings gangs minimum requirement back to 30

### PR DESCRIPTION
**Pull request by boodaliboo**
the title explains it peoepl discord tlaking about it
:cl:  
tweak: tweaked a few things  

/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
holy shit fill out the fucking template

**Comment by boodaliboo** [comment]
> holy shit fill out the fucking template

the title explains absolutely everything

**Comment by Tipy1802** [comment]
Finally, it's so fucking stupid that I haven't had a gangs round since fucking June

**Comment by Jarod1200** [comment]
Because the title is no longer indicative of what actually changed I will note that this pr changed the min pop for gangs to 35 not 30 players

**Pull request merged**
