### PR TITLE
Chaplains can now choose their chapel

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
As title

# Testing
works

# Changelog
:cl:  
tweak: Chaplain can now choose their chapel
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
this feature blows
people should be playing different maps instead of trying to reflavor the single played one

**Comment by neeshacark** [comment]
> this feature blows people should be playing different maps instead of trying to reflavor the single played one

the correct take but we unfortunately short of removing box, cant force people to not play it as much as possible. might as well make it as varied as possible

imo we should just remove box though

**Comment by Hopekz** [comment]
> imo we should just remove box though

Wut yogstation is literally our dust2 or 2fort
You wouldn't remove those maps from counter strike or tf2 why would do you a dumb decision like that here specifically 🙃

**Comment by JohnFulpWillard** [comment]
I would remove 2fort if I could

**Comment by JohnFulpWillard** [comment]
Anyways the argument is not comparable at all. 2fort has never changed at all really, and is generally not seen as the map you "play the game" on. It's for friendlies, duels, random thoughtless fun, or trying out gimmicks. This is fine for a game like TF2 which has hundreds of thousands of players and servers. If you want to play 2fort you can join 2fort. If you don't want to, don't. There's only 1 yogstation, if they're running 2fort 24/7 then there's no way to "play the game", which you can see if you observe a round, orbit the HoS, and watch them check every bit of maintenance from memory in case of any bloodsucker lairs.

**Comment by Hopekz** [comment]
> I would remove 2fort if I could

 I can see that I'm talking to someone without a sense of game direction or what people want in a game so whatever you wrote in that giant wall or text above is probably invalid.

**Comment by azzzertyy** [comment]
> Anyways the argument is not comparable at all. 2fort has never changed at all really, and is generally not seen as the map you "play the game" on. It's for friendlies, duels, random thoughtless fun, or trying out gimmicks. This is fine for a game like TF2 which has hundreds of thousands of players and servers. If you want to play 2fort you can join 2fort. If you don't want to, don't. There's only 1 yogstation, if they're running 2fort 24/7 then there's no way to "play the game", which you can see if you observe a round, orbit the HoS, and watch them check every bit of maintenance from memory in case of any bloodsucker lairs.

can you guys argue about this literally anywhere but my pr im just fixing a mistake piss off

**Comment by azzzertyy** [comment]
> this feature blows people should be playing different maps instead of trying to reflavor the single played one

except that this feature is not just used on box and is used on other maps and i intend to bring more of the variations to other maps, like i have been doing with the pr literally right before this one.
saying this is wrong, incorrect, stupid and ignorant because this system is not exclusive to box, never was, and never will be.

**Comment by ToasterBiome** [comment]
How do i unsubscribe?

**Comment by Moltijoe** [comment]
reopen when you continue work

**Comment by JohnFulpWillard** [comment]
> can you guys argue about this literally anywhere but my pr im just fixing a mistake piss off

You're adding a feature that I don't agree with, this is where I am discussing it. My argument is directly in point to your PR.

> except that this feature is not just used on box and is used on other maps and i intend to bring more of the variations to other maps, like i have been doing with the pr literally right before this one. saying this is wrong, incorrect, stupid and ignorant because this system is not exclusive to box, never was, and never will be.

You are currently PRing it to solely just Box by just clicking on files changed. If this is already a feature that exists, then I don't see why you're adding a whole new pref on top while not touching the old one.

**Comment by azzzertyy** [comment]
> > can you guys argue about this literally anywhere but my pr im just fixing a mistake piss off
> 
> You're adding a feature that I don't agree with, this is where I am discussing it. My argument is directly in point to your PR.
> 
> > except that this feature is not just used on box and is used on other maps and i intend to bring more of the variations to other maps, like i have been doing with the pr literally right before this one. saying this is wrong, incorrect, stupid and ignorant because this system is not exclusive to box, never was, and never will be.
> 
> You are currently PRing it to solely just Box by just clicking on files changed. If this is already a feature that exists, then I don't see why you're adding a whole new pref on top while not touching the old one.

this feature does not exist for chaplains, who despite having chapel variations do not have a choice.
I plan on adding equivalents for other maps to match the existing chapels and bring some of their chapel designs to other maps aswell, modifying the layouts to match. If you look at the clerk pr, meta and box happened to have very similar clerk sizes and layouts so it was much easier to just drag and drop them in, I'm going to in future add a check and depending on the map load different versions using the same pref. I've been planning on doing this for a while now, and my other metastation pr to change kitchen and botany was created with the intention of making this process easier

**Review by Aquizit — APPROVED** [review]
the map stuff is ok

**Comment by JohnFulpWillard** [comment]
> who despite having chapel variations do not have a choice.

What do you mean by this?

Also this issue is still up regarding the Bar, I am not sure if it was yet addressed but I did see it happen on live myself https://github.com/yogstation13/Yogstation/issues/20587

**Comment by azzzertyy** [comment]
i forgor i fix tommorow

**Comment by MajManatee** [comment]
No activity. Reopen when work continues

**Comment by azzzertyy** [comment]
> No activity. Reopen when work continues

??? it is literally ready to go and waiting for merge

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
