### PR TITLE
Revert "Renames microwave ovens to bluespace microwave ovens"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#12316

Less than 24 hours + a self merge (Admits it was his own idea)

### CODE REVIEW

**Comment by Hopekz** [comment]
> Reverts #12316
> 
> Less than 24 hours + a self merge (Admits it was his own idea)

Where is the part where the PR is bad for the game since you're reverting it

**Comment by Bibby0110** [comment]
> > Reverts #12316
> > Less than 24 hours + a self merge (Admits it was his own idea)
> 
> Where is the part where the PR is bad for the game since you're reverting it

Breaks protocol.
Doesn't have to be bad for the game.

**Comment by Hopekz** [comment]
> Breaks protocol.
> Doesn't have to be bad for the game.

Keep your dev drama out of our codebase.

Your change is modifying our codebase to remove something you don't even think is bad so by that logic you are knowingly making it worse if this were to be merged.

There are probably other ways you can express your point without making a modification like bringing it up in staff channels or even making a staff complaint on the forums.

**Comment by nesisknesis** [comment]
why was this actually merged

**Pull request closed without merging**
