### PR TITLE
Toilet is now craftable

### PR DESCRIPTION
**Pull request by Hopekz**
This is truly a rebase moment.
Now you can be the creator of a fine toilet!

#### Changelog

:cl:  
rscadd: Toilets are finally craftable. Wow! 
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
Speed merge

**Comment by Saratoubi** [comment]
Finally

**Comment by yacabo** [comment]
Literally best PR

**Comment by overlord12345** [comment]
is urinal next?

**Comment by Hopekz** [comment]
> is urinal next?

only time will tell!

**Comment by ThatLing** [comment]
PR of the decade material

**Comment by Jarod1200** [comment]
A new era Dawns. Hop no longer has to poo in an advanced crate in the conference room

**Comment by MegaEmpirical** [comment]
Bring back toilets being hooked up to disposals.

**Comment by AsV9** [comment]
good pr

**Pull request merged**
