### PR TITLE
You can now move while opening mail

### PR DESCRIPTION
**Pull request by iloveloopers**
# Document the changes in your pull request
you can now move during the do_after of opening mail

# Why is this good for the game?
quality of life

# Testing
probably works

# Wiki Documentation
none

# Changelog

:cl:  
tweak: You can now move while opening mail
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Impossible...

**Comment by Mqiib** [comment]
You fool! Don't you know spessmen always have a hard time doing anything that takes more than 0 seconds while also having to coordinate their legs????? It's simply impossible!

**Comment by iloveloopers** [comment]
I'm being harassed by the mail metagang. of course spessman can move while doing things with their hands

**Comment by iloveloopers** [comment]
We need the council to weigh in on this.

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
