### PR TITLE
Changes robotics to only have one roboticist

### PR DESCRIPTION
**Pull request by AshCorr**
### Intent of your Pull Request

Ash mentioned passingly that she used to want robotics to only have one roboticist

#### Changelog

:cl:  Nichlas0010
tweak: one of the roboticists were executed
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
W h y

**Comment by ThatLing** [comment]
Why?

**Comment by CMOisLing** [comment]
Y

**Comment by AshCorr** [comment]
Why

**Comment by ThatLing** [comment]
No thanks, we're good.

**Pull request closed without merging**
