### PR TITLE
Makes the Janitor OP

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Adds Paint Remover, Swatters and Flashlights to the cart,

Janitor OP pls Nerf

#### Changelog

:cl:  
rscadd: Janitor QoL Part two, added more to the cart
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
powercreep

**Review by Hopekz — APPROVED** [review]

**Comment by alexkar598** [comment]
has this been tested?

**Comment by JamieD1** [comment]
> has this been tested?

I test all my PR's before posting. So yes.

**Review by monster860 — CHANGES_REQUESTED** [review]
needs overlays that go on the cart

**Comment by Hopekz** [comment]
Tested in-game with the new overlays.
Confident in this merge.

**Pull request merged**
