### PR TITLE
Adds 'Lucifer, My Love' to the Halloween Title Screen.

### PR DESCRIPTION
**Pull request by Xoxeyos**
Adds a song about a bit of human sacrifice, fancy dresses, and alotta love put into it. What a lovely voice! Listen to it here! https://www.youtube.com/watch?v=sDY9fVZRn-4 (We are using a different link, because the ladder was blocked in half the world. https://www.youtube.com/watch?v=qaQ6oJL1qQA)

🆑 Xoxeyos
soundadd: Adds Lucifer, My Love, to the Halloween Title Screen, created by Twin Temple.
/🆑

### CODE REVIEW

**Comment by JamieD1** [comment]
image

**Comment by Xoxeyos** [comment]
What link did you use? I know youtube can be picky with links, but I don't understand what the problem is on your part, perhaps a shared link would work better? https://youtu.be/sDY9fVZRn-4

**Comment by Xoxeyos** [comment]
Making an attempt to find a link that isn't blocked by half the world.

**Comment by Xoxeyos** [comment]
image

**Review by JamieD1 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
