### PR TITLE
[META] MetaStation alternate engines [Singulo/Tesla/SM/TEG]

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

This was incredibly stupid to do.

The engines on Metastation now alternate between the SM, Tesla/Singulo, and TEG.

This pr has been tested

NOTE
Instead of being directly wired to the power grid, the emitters for both engines now run off of a seperate engine SMES, located where the spare PACMAN was in engineering storage.

Big thanks to Baiomu for the layout of the tesla and teg 
# Spriting

# Wiki Documentation

Screenshot the new meta tesla and teg setup
# Changelog

:cl:  N3D6, ToasterBiome
rscadd: new landmark, meta engine spawner
rscadd: new map file for the meta tesla
rscadd: adds an engine smes to meta engineering
rscadd: code for meta random engines, 50/30/20 SM, tesla, teg
rscadd: map file for meta teg
tweak: redoes some of the meta smes to fall in line with the new engine smes
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
You can have oddly shaped templates, it looks like it will have to be shifted down to keep the cooling pipes part of the supermatter one

**Comment by N3D6** [comment]
@ToasterBiome Should be good to look at again now

**Comment by N3D6** [comment]
This is in no maptainer hell

**Comment by ShoziOffical** [comment]
why

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
