### PR TITLE
Fuck you Lyis...                                                                            and your rags.

### PR DESCRIPTION
**Pull request by JamieD1**
Fucking Rags

#### Changelog

:cl:  
bugfix: Nuclear option rags for oldest issue
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
I love it.

**Review by Amelia0010 — DISMISSED** [review]

**Review by Amelia0010 — COMMENTED** [review]
Why change it to CLEAN_STRENGTH_BLOOD instead of CLEAN_STRENGTH_MEDIUM

**Comment by JamieD1** [comment]
> Why change it to CLEAN_STRENGTH_BLOOD instead of CLEAN_STRENGTH_MEDIUM

So it cleans up blood.

**Comment by MegaEmpirical** [comment]
<.< Not fixed.

**Pull request merged**
