### PR TITLE
hey guys i found the config file and added heresy and dynamic to rotation. also why was cult set to fucking 9 probability? fucking 9???? it's 6 now and so is clock cult

### PR DESCRIPTION
**Pull request by ghost**
PROBABILITY HERESY 5
PROBABILITY DYNAMIC 9

PROBABILITY REVOLUTION 7 (down from 9, jamies request)

PROBABILITY CULT 6 (down from 9)
PROBABILITY CLOCKWORK_CULT 6 (up from 3)

### CODE REVIEW

**Comment by Jarod1200** [comment]
Might as well throw in darkspawn too

**Comment by Altoids1** [comment]
I like what you're doing, here, chef, but I want to recommend to the HCs to actually engage in a survey on the matter, like we did the last time we did a big shift of the gamemode probabilities.

https://docs.google.com/spreadsheets/d/1TIUJ7fNyL28naaHuecULDWyJopMPxLIC2bpvlYM_UOA/edit?usp=sharing

image
image

**Comment by ghost** [comment]
@Altoids1  asked jamie

that counts as one right

**Comment by ghost** [comment]
that being said yeah create a survey if u want

**Comment by Tipy1802** [comment]
Why the fuck does clock cult have the same chance as blood. 
Clock cult is so fucking unbalanced and annoying, war gamemodes should be less likely than conversion gamemodes.
Also blood cult doesn't need it's chance reduced. I am so tired of traitors or their subvaraints (lings/vamps/blood brothers), they are so boring when you are crew and even as sec you see almost no actions.

**Comment by Tipy1802** [comment]
Heretics aren't compatable with our murderbone rule and as such were left out of rotation.
Dynamic tends to be far too chaotic but I am not against it being in rotation, it can spice things up .
Revs and Blood Cult shouldn't have their chance reduced, gang is already rare as fuck so this leaves us with just boring ass traitors

**Comment by AdamElTablawy** [comment]
@Tipy1802

Why do you have such terrible takes on everything? Genuinely, you're just...so bad.

**Comment by JamieD1** [comment]
Discussion is good.

**Comment by MrHorizons** [comment]
I thought dynamic wasn't in rotation because it was broke in various, unspecified ways?

...

Actually, let's put it into rotation. We can't really debug if it happens with all the frequency of a fish being tuned.

**Comment by JamieD1** [comment]
Moved to #10023

**Comment by JamieD1** [comment]
> I thought dynamic wasn't in rotation because it was broke in various, unspecified ways?
> 
> ...
> 
> Actually, let's put it into rotation. We can't really debug if it happens with all the frequency of a fish being tuned.

Exactly my thinking

**Pull request closed without merging**
