### PR TITLE
Polysmorph (and maybe more to come) Skinny-ification

### LINKED ISSUE #10647: polysmorpth clothing, underwear and undershirts are kinda wonky
naked polysmorpth:
https://imgur.com/hmR0yPr
the bodyshape is unlike other female characters which causes some issues with clothing.

polysmorpth with babydoll underwear:
https://imgur.com/hTFjDHZ
the body shape has changed and since its see trough it looks like the polysmorpth has breasts which it dosent normaly.

polysmorpth and human in ladies' thong underwear:
https://imgur.com/k5hQ5wu
https://imgur.com/9rOsIOQ

the polysmorpth is missing 1-2 pixels.

polysmorpth in a shirt(grey) undershirt:
https://imgur.com/WuHQ7JQ
the body shape has changed.

polysmorpth with a normal jumpsuit:
https://imgur.com/314THkX
the body shape has changed.

the same issue happens with other clothing, underwear and undershirts, i picked these as it can be seen clearly

theres also this
ladies' white neko underwear human and polysmorpth: 
https://imgur.com/agkFLvW
https://imgur.com/JkYdx3C
the polysmorpth has a few extra pixels or something and is missing one pixel in the bra area.

### PR DESCRIPTION
**Pull request by Mqiib**
### Intent of your Pull Request

Fixes #10647 

This adds a new trait, TRAIT_SKINNY, that modifies the shape of any regular clothing worn by (currently only) polysmorphs. Theoretically, it could be added to other new races if they happen to also be particularly thin. The effect is only applied to jumpsuits and undershirts (for now). I've done a decent amount of testing and it seems the only bugs that occur are the clothing sprites not appearing thing that has been plaguing us for as long as I can remember, which is fixed by a reconnect.

Also tweaks the polysmorph body shape when facing north and simplifies the code for female sprites (shamelessly borrowed from citadel, thanks guys!)

Skinny:
image
image

Less skinny (the before times):
image
image

### Why is this change good for the game?

Instead of doing what was suggested, being making polysmorphs the same shape as most other humanoid species, this pr retains their quirk of being a slightly different shape and helps them stand out a bit more as an alien race.

# Wiki Documentation

Probably should mention that polysmorphs have a slightly different body shape or something. It's pretty minor, though.

### What should players be aware of when it comes to the changes your PR is implementing?

Underwear preference no longer affects the sprite, polysmorphs will always and forever look thin.

### What general grouping does this PR fall under? 

Spriting

### Are there any aspects of the PR that you would like us not to mention on the Wiki?

No

# Changelog

:cl:  
rscadd: TRAIT_SKINNY is here for all your skinny race needs! Maybe!
imageadd: Polysmorphs now look skinnier than humans in all jumpsuits and regular clothing (probably)
imageadd: skinny thingywhatsises added to uniform.dmi for the purposes of sprite modification
imageadd: Polysmorph north-facing body shape now consistent with south-facing shape
bugfix: generate_female_clothing proc probably works better
bugfix: invisible bodies should stop being a thing

/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Please do tell me if you want always-skinny or optional-skinny in thE COMMENTS BELOW AND DONT FORGET TO SMASH THAT LIKE AND SUBSCRIBE BUTTON

**Comment by redmoogle** [comment]
> 
> 
> Please do tell me if you want always-skinny or optional-skinny in thE COMMENTS BELOW AND DONT FORGET TO SMASH THAT LIKE AND SUBSCRIBE BUTTON

Theres not really much difference between skinny and not skinny

**Comment by Hopekz** [comment]
> > Please do tell me if you want always-skinny or optional-skinny in thE COMMENTS BELOW AND DONT FORGET TO SMASH THAT LIKE AND SUBSCRIBE BUTTON
> 
> Theres not really much difference between skinny and not skinny

It's the love handles

**Comment by Mqiib** [comment]
image
I should mention that the weird dark sections added to these are because the pixels removed tend to be outline pixels so the dark bits roughly fix the outline that just about all of our clothing sprites have by making those particular edge pixels darker. Without it, the clothes look a little weird because they end up not having any outlines in the modified sections,

**Comment by Mqiib** [comment]
@Partheo pls rate my sprots its been over two weeks :(

**Review by Partheo — APPROVED** [review]

**Comment by Mqiib** [comment]
Yes so I have confirmed that any issues with sprites not appearing properly is still part of the same issue that has been around for-fucking-ever and is _consistently_ fixed by a reconnect.

**Comment by Mqiib** [comment]
So this was easier than I really expected. Most everyone that I asked preferred that the polysmorphs be consistently skinny if they cared at all, so that's how it is now. Rejoice, your voices have been heard!

**Comment by JamieD1** [comment]
This is Stupid

**Comment by ThatGuyPhil** [comment]
So people have time to add this but nobody can help me make digitigrade legs actually visible for like 90% of clothing

**Pull request merged**
