### PR TITLE
Xeno queens delay shuttle

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Xeno delay is currently at 30 minutes, can be adjusted if necessary
:cl:  Xeos
tweak: Xeno queens will delay the escape shuttle for a while unless they are killed
tweak: the shuttle will get auto called at the end of the timer if the queen is alive and it hasn't been called already to prevent super xeno extended rounds
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Shouldn’t be called just based on timer TBH. Take in crew:xeno ratio in to account to and/or amount of living crew

**Comment by SomeguyManperson** [comment]
If a xeno queen is alive for 15 minutes there is very likely a problem

**Comment by HomocidlePancakes** [comment]
Or it’s being a massive wuss/incopetent/on the run and the crew is merking benos harder then 1812.

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Use timers instead of a bullshit discount for loop.

**Comment by alexkar598** [comment]
Im against the fact it auto resolves after 15 minutes,should only resolve when the queen dies.

Might be also worth giving the aliens a win condition.

**Comment by SomeguyManperson** [comment]
The auto resolve was suggested since otherwise a xeno round can go on quite long and if the admins don't want to resolve it/there are none it won't end naturally

**Pull request merged**
