### PR TITLE
Mecha Weapon: BFG-90 "Graze" Radioactive Cannon

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Adds the BFG-90 "Graze" Radioactive Cannon weapon to mech

Weapon and ammo cost some metal, diamond, and uranium to print

Has a 2 second cooldown (Solaris having 1.5)

Has a max ammo capacity of 5+10 (15) which is very low, causing it to have poor continuous battling capability

Does 43 (35+8) damage on a direct hit (Solaris doing 40)

Being adjacent (grazed) to the projectile deals 8 damage to you (or 460K fire to objects) per tile the projectile travels, which should deal 16-32 damage depending on if the projectile hits a wall, or if you are running away from the projectile (which will hurt more as you are spending more time next to it)

Also moved around some nodes to be less messy

# Spriting
image

# Wiki Documentation

See above for damage

Weapon costs
- 6x metal sheets
- 3x uranium sheets
- 1x diamond sheets

Ammo costs
- 3x metal sheets
- 3x uranium sheets
- 1x diamond sheets

# Changelog

:cl:  
rscadd: Added the BFG-90 "Graze" Radioactive Cannon mech weapon
tweak: Moved around some weapons research nodes
tweak: Exotic Ammo now requires Ballistic Weaponry research
tweak: Experimental Ammo now only requires Exotic Ammo instead of Ballistic Weaponry and Exotic Ammo
/:cl:

### CODE REVIEW

**Comment by Zer0Tactics** [comment]
Where does this fall under research? And why would anyone use anything other than this? It looks cool, but also seems like it would become a de facto option for mechs. Might need to be toned down a bit imo.

**Comment by ynot01** [comment]
> Where does this fall under research?

It is next to the other mech lasers, requiring ballistic & adv beam weaponry research

> And why would anyone use anything other than this?

It is slow firing and has very limited ammo capacity, only being a bit better than solaris overall

**Comment by Marmio64** [comment]
The projectile is classed as a beam, right? And thus would pass through grilles and windows?

If so, this weapon kind of seems like its in a incredibly weird spot in the middle between being a ballistic weapon and a laser weapon. It uses ballistic ammunition and is called a Magnum, yet fires burn damage laser beams and uses a laser mech gun sprite. Not only that, in the comments you said to think of the projectile as being an incredibly hot bar of steel, but that wouldn't make any sense since then it would just be a hot projectile rather than a laser. I'd be pretty confused seeing this thing in game, and you should probably steer more towards one way or the other.

Personally, i would go with the ballistic route since it already has ammo and the name, and change a few things. Perhaps particularly make it so it isn't a beam projectile and doesn't go through windows, which would also make it more balanced compared to the Solaris cannon.

**Comment by ynot01** [comment]
> The projectile is classed as a beam, right? And thus would pass through grilles and windows?
> 
> If so, this weapon kind of seems like its in a incredibly weird spot in the middle between being a ballistic weapon and a laser weapon. It uses ballistic ammunition and is called a Magnum, yet fires burn damage laser beams and uses a laser mech gun sprite. Not only that, in the comments you said to think of the projectile as being an incredibly hot bar of steel, but that wouldn't make any sense since then it would just be a hot projectile rather than a laser. I'd be pretty confused seeing this thing in game, and you should probably steer more towards one way or the other.
> 
> Personally, i would go with the ballistic route since it already has ammo and the name, and change a few things. Perhaps particularly make it so it isn't a beam projectile and doesn't go through windows, which would also make it more balanced compared to the Solaris cannon.

[Beam Magnum](https://gundam.fandom.com/wiki/RX-0_Unicorn_Gundam#Armaments)

**Comment by Marmio64** [comment]
> > The projectile is classed as a beam, right? And thus would pass through grilles and windows?
> > If so, this weapon kind of seems like its in a incredibly weird spot in the middle between being a ballistic weapon and a laser weapon. It uses ballistic ammunition and is called a Magnum, yet fires burn damage laser beams and uses a laser mech gun sprite. Not only that, in the comments you said to think of the projectile as being an incredibly hot bar of steel, but that wouldn't make any sense since then it would just be a hot projectile rather than a laser. I'd be pretty confused seeing this thing in game, and you should probably steer more towards one way or the other.
> > Personally, i would go with the ballistic route since it already has ammo and the name, and change a few things. Perhaps particularly make it so it isn't a beam projectile and doesn't go through windows, which would also make it more balanced compared to the Solaris cannon.
> 
> [Beam Magnum](https://gundam.fandom.com/wiki/RX-0_Unicorn_Gundam#Armaments)

Ah, alright. I'd still be confused if I were to not know the reference but I guess. Though also I don't know about Gundam, but just quickly reading it over the projectiles still seem more described as beams of plasma rather than light which would still have it make more sense to not go through windows.

**Comment by LoliconSlayer** [comment]
Might I suggest a slight modification to the name and description, mostly for the sake of my own amusement.

Name: UC-96 "Magnum" Heavy Particle Rifle
Description: A siege class weapon for combat exosuits. Shoots a destructive super-heated particle beam surrounded by a field of plasma. It is designed to use specialized external energy packs due to high power draw.

Also, just a thought, what if it was like a mech version of the Particle Acceleration/Marksman Rifle considering:

https://github.com/yogstation13/Yogstation/assets/54045237/c213556e-3913-4185-ab24-20575deaad63

**Comment by ynot01** [comment]
> Also, just a thought, what if it was like a mech version of the Particle Acceleration/Marksman Rifle

I will rename this weapon to not use "Magnum" and implement this PA weapon at a later date

**Comment by ynot01** [comment]
Last 2 commits are important, be sure to look over them

**Comment by LoliconSlayer** [comment]
> I will rename this weapon to not use "Magnum" and implement this PA weapon at a later date

Sad!

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
