### PR TITLE
Syndicate Icemoon

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Adds a Syndicate base ghostrole to the icemoon.
There are 6 crew:
_**Commander**_
Issued with a .357 revolver, esword, and chameleon GPS mask. Serves as both a comms agent and the base's commander, giving orders to staff.

All crew are issued with a 10mm Makarov (except for the boss man, he has big pistol)
_**Scientist**_ (x2)
Issued with a sniper rifle, identical to Syndicate Lavaland. Run the research and xenobiology wings of the base.
_**Security Officer**_ (x1)
Issued with a C20-R with the fucked firing pin. Defend the base against hostiles.
_**Engineer**_ (x1)
CE toolbelt and funny glasses. Do the engineering
_**Medical Doctor**_ (x1)
a professionally qualified medic

For pictures please use MDB to stay up to date.

# Wiki Documentation

add to ruins

# Changelog

:cl:  
rscadd: The Syndicate Icemoon base!
rscadd: A Syndicate research post with 6 crew, deep within the icy wastes.
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
I love the little Southern island

**Comment by Yarinoi** [comment]
icemeta hater hq

**Comment by Addust** [comment]
i hate icemeta and want a ghostrole for it so i hate it less

**Comment by N3D6** [comment]
i like this, it's very nice. something to note, the plating you used for the exit should be the smoothed option, as the tiles look like actual shit when they haven't been smoothed. otherwise this is a great PR and i'm excited to see where you can take this

**Comment by Addust** [comment]
WE ARE OUT OF DRAFT BOIS.

**Comment by Addust** [comment]
> i like this, it's very nice. something to note, the plating you used for the exit should be the smoothed option, as the tiles look like actual shit when they haven't been smoothed. otherwise this is a great PR and i'm excited to see where you can take this

i'm using unsmoothed to make it feel more like a 'bridge' where snow isnt gonna accumulate on the sides

**Comment by N3D6** [comment]
the catwalks won't work btw the plasma lava just burns them, i tried it originally when doing icemeta. probably try plating or something?

**Comment by Addust** [comment]
i'm gonna test to see what dept is causing all the test failures

**Review by neeshacark — CHANGES_REQUESTED** [review]
I'm not a fan of these turrets being hidden under trees, makes them very hard if not impossible to destroy
image_2023-08-20_011652879
image_2023-08-20_011659785

The quantity of gear here is more than a little ridiculous, please reduce it.  3 of each item at absolute max should be more than fine.
image_2023-08-20_014934558
image_2023-08-20_014945409

The decals in general are odd.  The sidings are *fine* even though I personally dislike them, but for the decals we do actually use for other maps they should at minimum be consistent with other maps when going through doors.  See how box does this
image_2023-08-20_015550690
as opposed to what Box does, which is this
image_2023-08-20_015624008

Please move this vent/scrubber combo to not be right next to eachother, we dont do that.
image_2023-08-20_020508846

No air alarm in this room 
image_2023-08-20_020640717

No air alarm in here either 
image_2023-08-20_020748879

**Comment by Addust** [comment]
> I'm not a fan of these turrets being hidden under trees, makes them very hard if not impossible to destroy image_2023-08-20_011652879 image_2023-08-20_011659785
> 
> The quantity of gear here is more than a little ridiculous, please reduce it. 3 of each item at absolute max should be more than fine. image_2023-08-20_014934558 image_2023-08-20_014945409
> 
> The decals in general are odd. The sidings are _fine_ even though I personally dislike them, but for the decals we do actually use for other maps they should at minimum be consistent with other maps when going through doors. See how box does this image_2023-08-20_015550690 as opposed to what Box does, which is this image_2023-08-20_015624008
> 
> Please move this vent/scrubber combo to not be right next to eachother, we dont do that. image_2023-08-20_020508846
> 
> No air alarm in this room image_2023-08-20_020640717
> 
> No air alarm in here either image_2023-08-20_020748879

ok done

**Review by neeshacark — APPROVED** [review]
It's RUNNING AWAY! catch it!
image_2023-08-23_114222666

Can't find anything else terribly wrong on mapping end with my eyes.  Code review still needed, though it looks fine to my eyes.  Testmerge needed too, for sure.

**Review by neeshacark — CHANGES_REQUESTED** [review]
didnt mean to approve, see above

**Comment by Addust** [comment]
> It's RUNNING AWAY! catch it! image_2023-08-23_114222666
> 
> Can't find anything else terribly wrong on mapping end with my eyes. Code review still needed, though it looks fine to my eyes. Testmerge needed too, for sure.

oh SHIT i did NOT see that let me catch it

**Comment by Addust** [comment]
> didnt mean to approve, see above

caught it

**Review by neeshacark — APPROVED** [review]
map seems fine, code review still needed.

**Review by SapphicOverload — APPROVED** [review]
Code looks fine

**Comment by N3D6** [comment]
Based police

**Pull request merged**
