### PR TITLE
Makes Polysmoprh Playable by All

### PR DESCRIPTION
**Pull request by JamieD1**
Now before you get out your pitchforks, here me out.

If we are going to give a public species out, they need common.

There are too many things in game that require communication to be both ways.

I have lessened their damage nerfs to compensate and given them night vision instead of thermals.

This will hopefully make this race balanced enough to include in a normal crew.

#### Changelog

:cl:  
rscadd: Polysmorph to all
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Atomize

You're doing round start poly AND major balance changes all at once

**Comment by Mqiib** [comment]
They should retain xenocommon as opposed to this new slowflake polysmorph language.

**Comment by MegaEmpirical** [comment]
The solution is clear: get the pitchforks out and make it a donor race.

**Comment by Marmio64** [comment]
sooo, they're just another boring human reskin like lizards now?

**Comment by Smudged** [comment]
> The solution is clear: get the pitchforks out and make it a donor race.

Pay to play is so bad, this may be a joke but I don't like the presidence for the future of PR's and >Donor only races



> sooo, they're just another boring human reskin like lizards now?

Every race is a reskinned human at the end of the day

If anything this race should be a xenobio exclusive with thermal vision.

I hope this isn't merged until possible time locks are made, because any new player playing would have an awful time with this race, and they need to have job restrictions because they would have a clear problem in security.

**Comment by TheReddDragon** [comment]
smh

**Comment by Georgeur** [comment]
Giving them common is a strange change, this removes their most major downside, removes what made them unique to play, and this came about because I told Redd that tcomms could translate xenomorph and I didn't like that I was able to effectively speak common. 
To put it briefly, thermals were okay, because you couldn't say there's a traitor, or call for help. and validhunting was a terrible idea, due to your 1.5 burn damage modifier making you a 4 hit crit by even a welder. 
Your upsides of less acid damage, and a more inefficient temperature modifier setup than lizards or any roundstart race, didn't mean or do anything effectively. 
Having acid blood meant the only person who could help you was a chemist (who you cant talk to), and because you still have such a large bloodpool like humans, syringe based transfusion was incredibly slow. 
Also you're hardcoded to not wear shoes, like ashies. 
They're not overpowered, in fact theyre one of the contenders for weakest race.

I wanted them to be made public, but not like this, as some lizard reskin with no unique advantages or disadvantages, and are outclassed entirely by preternis. 
The fact I had a hard time communicating and acted my best when mostly following orders, made it fun and difficult. 

There is not a single part of this that I like, polysmorph will just become a new ethereal race which no one plays, they're in this state just boring. 

but its ganna be merged anyway

**Comment by Marmio64** [comment]
> > The solution is clear: get the pitchforks out and make it a donor race.
> 
> Pay to play is so bad, this may be a joke but I don't like the presidence for the future of PR's and >Donor only races
> 
> > sooo, they're just another boring human reskin like lizards now?
> 
> Every race is a reskinned human at the end of the day
> 
> If anything this race should be a xenobio exclusive with thermal vision.
> 
> I hope this isn't merged until possible time locks are made, because any new player playing would have an awful time with this race, and they need to have job restrictions because they would have a clear problem in security.

there comes a point where a species is different enough to not be considered a total reskin, and it is when they have actual unique parts of gameplay added to them. Examples: Preternis have to charge themselves and have unique interactions with some chemicals, get fucked by EMPs, and have the ability to self surgery. Plasmamen have to stay in a suit but have the cool ability to survive in complete plasma outside of their suit, and they also have rad immunity, cold immunity, and virus immunity. Plantmen have some unique chemical interactions and have to stay in the light or die, but benefit from the light. Lizards have no unique gameplay besides their snowflake language, ethereals tow the line, and moths aren't too unique either. Look at the previous polysmorphs, they had trouble speaking to non-polysmorphs but gained thermal vision in return, along with near acid immunity and cold resistance (still towed the line of being a human reskin but different enough), however now they're just a lizard with inversed strengths (cold resistant instead of head resistant, but weak to heat instead of cold) along with nightvision in exchange for extra burn damage.

**Comment by Mqiib** [comment]
A suggestion for the eyes: bump up the see_in_dark to like 4 or 5 so that they can "see" further in total darkness, giving them a weakened but actually significant darkness vision advantage. It's far from real night vision but it'll actually be useful, unlike how it currently is where it's the same value as a _one point quirk_

**Pull request merged**
