### PR TITLE
Adds modular phones

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Adds modular phones to the game and does some tweaking of some stuff to make them work and balanced. They function much like our current tablets, with the only major difference being that they cannot use the ID modification program or the Intelicard slot. Tablets have had their size increased to normal and are unable to be placed in your ID slot, but now they can take small modifications (which means they can get some parts that were only for laptops and consoles). Finally, laptops were given the ability to use large parts (which doesnt mean much, as many of the parts were increased to large to prevent them from being used in tablets) and given the ability to use the AI reconstruction program. As for how to get the phones, you can get them from the Deluxe Silicate Selections or build them in the computer vendor.

## Pictures

image
image

# Wiki Documentation

If modular computers are mentioned, it may be a good idea to mention modular phones and all the tweaks to everything. 

# Changelog

:cl:  
rscadd: added modular phones
tweak: removed the ability for tablets to be stored in the ID slot, increased its weight to normal, and increased its max part size to normal
tweak: tweaked many of the weight values for modular computer parts and allowed programs
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
I cannot wait to ask someone if they have games on their phone.

Also when you said laptops get big components I immediately imagined the horrid idea of a machine board being integrated into a laptop. imagine the nightmare of a mobile ai upload

**Comment by Hopekz** [comment]
One step closer to just replacing our PDA's with these like Eris

**Comment by maxion12345** [comment]
y'know. If phones could display the name/job of the ID inside, and have a robust messaging system, they could be a decent sidegrade to the PDA

**Comment by Jarod1200** [comment]
Does sm monitor program exist on the phone?
Also are any people who currently spawn with tablets going to spawn with phones instead?
(I think this would make them actually useful)

**Comment by nmajask** [comment]
> One step closer to just replacing our PDA's with these like Eris

The dream

> y'know. If phones could display the name/job of the ID inside, and have a robust messaging system, they could be a decent sidegrade to the PDA

Ill look into making them show the ID inside, though they do have a very nice messaging system that isn't used very often as few people uses modular computers

> Does sm monitor program exist on the phone? 

It should, as it doesn't look like there are any requirements for the program.

> Also are any people who currently spawn with tablets going to spawn with phones instead? (I think this would make them actually useful)

I could do it for engi and atmos tech, but I will probably do that in a separate PR if I do.

**Comment by Anvilman6** [comment]
A concept that may be interesting to explore is giving the phones a way to act as linked radios that can communicate with one another (such as, you know, how actual phones work). Though I guess the NTNet chatrooms feature is already emulative of cell phone texting, sort of.

Might also be worth considering giving the phones the ID modification slot capability, and making them the new default item for Heads as opposed to the tablet. Cheaper and sleeker for NT to hand company phones out, but that's just a thought. (Also the Janitor having a tablet is weird, but that's another discussion).

But other than those suggestion, I love the design and idea of this and the changes it precipitates - once again, awesome work Nmajask.

**Comment by adamsong** [comment]
Just replace PDAs with these, I've been wanting to do it myself for a while, and remove the head's tablets, and just give them upgraded phones

**Comment by Hopekz** [comment]
> Just replace PDAs with these, I've been wanting to do it myself for a while, and remove the head's tablets, and just give them upgraded phones

There's a bunch of little apps that need to be created to replace the PDA ones like even the lawyer all message spam and the messaging app just needs to be redone to maybe be more like the PDA one

**Comment by adamsong** [comment]
I understand this, its still a good idea

**Review by nesisknesis — APPROVED** [review]

**Comment by nmajask** [comment]
Oh, I was not expecting this to get merged this quick.

**Comment by TheBombMakerJL** [comment]
bad

That's a tablet computer.
A _small portable microcomputer_.
It is a **normal-sized item**.

no one asked for a tablet nerf

**Comment by Hopekz** [comment]
> no one asked for a tablet nerf


Just replace the spawned in tablets with smaller phones this PR introduced. 
This PR isn't bad, it just changed things a bit.

The tablets right now aren't really better than those phones and the next step would be to work towards making those phones replace the PDA's. Definitely should probably replace the spawned-in tablets that the engineers get in a PR soon.

**Comment by nmajask** [comment]
> no one asked for a tablet nerf

Tablets really haven't been nerfed, they have just kind of been replaced with the phones. If you look at it that way, the only real nerf to tablets is their lack of ability to use the ID modification program. Overall with what I plan to add/port down the line, tablets should be better of than they were before but that's all subject to if I even get around to doing it.

> The tablets right now aren't really better than those phones and the next step would be to work towards making those phones replace the PDA's. Definitely should probably replace the spawned-in tablets that the engineers get in a PR soon.

Ill make a PR soon to replace the engi tablets with phones.

**Pull request merged**
