### PR TITLE
Adds sfx to inserting things into atmos machines

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request

Full credit to [TheBoondock](https://github.com/TheBoondock)
Ports this: https://github.com/tgstation/tgstation/pull/83840
(I edited the uninsert sound slightly as well)

# Why is this good for the game?
adds good feel

# Testing

https://github.com/user-attachments/assets/b6a7b4e5-5f25-434c-b72b-70d7dbcaebc8

# Changelog
:cl: TheBoondock, AMyriad
soundadd: Added SFX to inserting tanks into gas canisters
/:cl:

### CODE REVIEW

**Review by ToasterBiome — APPROVED** [review]
this is kinda ass but ok

**Comment by Cartlord** [comment]
I think it's weird that the removal sound is gas hissing, when no gas is released by the action.

**Comment by AMyriad** [comment]
> this is kinda ass but ok

removal sound or input sound?

**Comment by LassiH** [comment]
the sound for putting the tank in sounds like a rock being placed on another rock

**Comment by StupidTums** [comment]
After thinking about it, the sounds of putting the tank on the canister and taking it off should be reversed.

**Comment by Moltijoe** [comment]
> After thinking about it, the sounds of putting the tank on the canister and taking it off should be reversed.

i agree with this, sorta
it should really just have two mechanical sounds for adding and removing the tank
and then gas sounds for using the other buttons

**Comment by AMyriad** [comment]
imma redo this

**Pull request closed without merging**
