### PR TITLE
removes brig, makes it 100% better

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Document the changes in your pull request
You've shit your last sec, partner.
image
image

# Wiki Documentation
sec is no more
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscdel: sec is gone
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
dont worry, i know what the players REALLY want

**Comment by Moggram** [comment]
You need to add working atmo air locks to the doors going to space.
Also you have removed alot of maintenance that had pipes and power lines running in them.
The HOS gun should be moved to the cap's room.
QM should get the reflective jacket as he can order one whenever he likes now.

If you can fix these small problems, we can get your RP merged

**Comment by bruhlookatthisdood** [comment]
> You need to add working atmo air locks to the doors going to space. Also you have removed alot of maintenance that had pipes and power lines running in them. The HOS gun should be moved to the cap's room. QM should get the reflective jacket as he can order one whenever he likes now.
> 
> If you can fix these small problems, we can get your RP merged

its been fixed!

**Comment by Moggram** [comment]
you forgot disposals pipes.

**Comment by bruhlookatthisdood** [comment]
Alright guys due to legal issues I had to add a BIT of a security
Introducing, the new security!
image
image

**Comment by bruhlookatthisdood** [comment]
cant wait to see this merged in the morning

**Comment by JamieD1** [comment]
We have a rule about meme PRs

**Pull request closed without merging**
