### PR TITLE
Makes praying as chap no longer give all staff tinittus

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Reduced chap prayer volume by around ~60%

# Why is this good for the game?

Tinnitus bad. Admins muting prayer sounds bad. Admins harboring a deep-seated loathing for chaplain players, causing them to slowly but surely drain of any and all will to answer prayers, eventually becoming the thing they swore not to be, and actively ignoring prayers from them in the hopes they go away, or wont pray again, but they always do, so instead each prayer that comes in makes the admins more and more resentful until simply seeing a prayer in chat has the same effect at seeing their most hated foe, and the team as a whole mutes them leaving chaplain players alone and isolated, slowly killing the fun they once had from the job, all because it was too loud.
# Testing

😏 

# Changelog

:cl:  
tweak: staff no longer are deafened by prayer
/:cl:

### CODE REVIEW

**Comment by Aquizit** [comment]
SPEEDMERGE

**Comment by Therandomhoboo** [comment]
But, if we dont give staff tinnitus how else can we piss them off?

**Comment by Aquizit** [comment]
> But, if we dont give staff tinnitus how else can we piss them off?

By existing

**Comment by Therandomhoboo** [comment]
> > But, if we dont give staff tinnitus how else can we piss them off?
> 
> By existing

Well... better get your prays in guys before this is merged!

**Comment by cowbot92** [comment]
give this man 1 morbillion dollars

**Comment by Hislyna** [comment]
Imagine not already having it muted

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
