### PR TITLE
update pipebomb image

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request

replace with cuack's sprite

# Wiki Documentation

we don't even have pipebomb documentation do we

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
imageadd: pipebomb dmi tweak
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Review by nesisknesis — APPROVED** [review]

**Comment by nesisknesis** [comment]
Cannot merge because it would conflict with #13321 which is test merged

**Comment by tattax** [comment]
demons of sin isn't testmerged

**Comment by JamieD1** [comment]
It is now!

**Comment by maxion12345** [comment]
fek

**Pull request merged**
