### PR TITLE
asteroid turbine stuff

### PR DESCRIPTION
**Pull request by Ethan4303**
# Document the changes in your pull request

CHanges two pipes leading into turbine room on asteroid to the correct color, removes redundent unused pipe from under turbine airlock, Removes rock from around turbine to give atmos techs more space for exterior loops and such
# Spriting

# Wiki Documentation

:cl:  

mapping: removed rock, redundent pipe, changed pipe colors on asteroid turbine

/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
can you add more girders around that area instead if you're removing the rock

**Comment by Ethan4303** [comment]
> can you add more girders around that area instead if you're removing the rock

Yeah

**Comment by Ethan4303** [comment]
wait did you mean lattice or wall girders

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image
Can you do something about this area now? It's kinda ugly with the square of lattices.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
