### PR TITLE
Removes the ability for players to start a map vote

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Disables the ability for players to start a map vote. This is good for the game because map votes force box 90% of the time, and map variety is objectively good from a game design perspective.

# Changelog

:cl:  
rscdel: Removed player map votes
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
based

**Comment by N3D6** [comment]
If this passes I will cashapp you 10 million zillion dollars adamsogm

**Comment by iloveloopers** [comment]
box is litteraly the best map in the universe you can't do this to me this will KILL yogstation FOREVER and we will LOSE all of the POP!!!11111

**Comment by neeshacark** [comment]
inb4 all the admins force map votes when its not box

**Comment by TaelynTheLost** [comment]
Removing choice is not good design practice.  Easy proof of that, is if 80% of the station wants Box, then you upset 80% of your players.  If you want people to play on different maps, make those maps something more people actually want to play on.

**Comment by thegoldencat413** [comment]
i dont like this with ice meta because it has a lot of issues and is very anemic with content

**Comment by N3D6** [comment]
> i dont like this with ice meta because it has a lot of issues and is very anemic with content

this has nothing to do with icemeta its literally not even merged or testmerged for these reasons alone

**Comment by adamsong** [comment]
> then you upset 80% of your players.

The number of players who hate box is dwarfed by the number who just prefer it."I would prefer box" and "I enjoy playing other maps" are not mutually exclusive.

Additionally, the number of players who dislike non box maps will likely decrease as they are forced to play non box maps, and mappers have a reason to work on not box maps.

**Comment by N3D6** [comment]
> Removing choice is not good design practice. Easy proof of that, is if 80% of the station wants Box, then you upset 80% of your players. If you want people to play on different maps, make those maps something more people actually want to play on.

80% is a ridiculously bloated number, every map vote I have seen in the past few months asteroid or icemeta one has been very close to box and only lost by a couple votes

also the maps are great, we can’t change people refusing to adapt to change. our maps are not the problem in the slightest. the best way to grow to appreciate a map? actually give it a chance instead of whining the entire time

**Comment by Moltijoe** [comment]
only worry i have is that if we're relying entirely on rotation, that means it's possible to be forced into shitty box while at like ~8 people lowpop when gax would be far superior in that situation

**Comment by N3D6** [comment]
> only worry i have is that if we're relying entirely on rotation, that means it's possible to be forced into shitty box while at like ~8 people lowpop when gax would be far superior in that situation

add a min pop to box

**Comment by LoliconSlayer** [comment]
> Removing choice is not good design practice. Easy proof of that, is if 80% of the station wants Box, then you upset 80% of your players. If you want people to play on different maps, make those maps something more people actually want to play on.

Damn so you mean we'll be rid of Boxtards and instead retain players who are willing to play on different maps but got tired of 24/7 box?

https://github.com/yogstation13/Yogstation/assets/54045237/6dce390c-7e28-40e2-a10c-653e51b9ae9b

You don't need to gild the lily this PR is already based enough.

**Comment by Therandomhoboo** [comment]
Only problem I have with this is when it rolls gax or meta ( the smaller one Iirc) which is hellish on highpop cause the map isn't meant for 50+ players.

**Comment by neeshacark** [comment]
map min and max pops will need tweaks but this is easily preventable

> Only problem I have with this is when it rolls gax or meta ( the smaller one Iirc) which is hellish on highpop cause the map isn't meant for 50+ players.

**Comment by N3D6** [comment]
> Only problem I have with this is when it rolls gax or meta ( the smaller one Iirc) which is hellish on highpop cause the map isn't meant for 50+ players.

meta is our med-highpop 
gax caps at like 30 i think so unless the round starts lowpop and gradually gets higher this will not happen
edit: gax caps at 40 which is still fine

**Comment by MajManatee** [comment]
> Damn so you mean we'll be rid of Boxtards and instead retain players who are willing to play on different maps but got tired of 24/7 box?

SO TRUE!! Fuck em. If they don't like the other maps they can make one themselves.

**Comment by Moltijoe** [comment]
reopen when this might actually get merged

**Pull request closed without merging**
