### PR TITLE
Makes Yogs Widescreen better - End screen fades properly without weird tiles, should also make round end sounds play 85% of the time.

### PR DESCRIPTION
**Pull request by JamieD1**
# Github documenting your Pull Request

Makes Yogs Widescreen better - End screen fades properly without weird tiles, should also make round end sounds play 85% of the time.

# Wiki Documentation

N/A

# Changelog
:cl:  
bugfix: Makes Yogs Widescreen better - End screen fades properly without weird tiles, should also make round end sounds play 85% of the time.
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
Does this fix the issue with not being able to interact with things on the far edge of widescreen or was that an intended mechanic

**Review by patpol4 — APPROVED** [review]
I hope you tested this

**Review by adamsong — APPROVED** [review]

**Comment by JamieD1** [comment]
Needs a few more tweaks to figre out why cinematics only play for 75%

**Comment by Bibby0110** [comment]
Draft as per above

**Pull request merged**
