### PR TITLE
ports Radial menu for Janitorial cart from TG

### PR DESCRIPTION
**Pull request by Jumps0**
### Intent of your Pull Request

The janitorial cart now uses a radial menu instead of an HTML UI menu. Credit to **Arkatos1** for the original code.
dreamseeker_2rnWZLWlN1

#### Changelog

:cl:  Arkatos
rscadd: Janitorial cart now uses a radial menu
/:cl:

### CODE REVIEW

**Comment by Jumps0** [comment]
booo

**Comment by Jumps0** [comment]
heck yea

**Comment by Xoxeyos** [comment]
We shouldn't add too many radial menus to things, it's just going to junk things up, in my opinion.

**Comment by Jumps0** [comment]
> We shouldn't add too many radial menus to things, it's just going to junk things up, in my opinion.

could you clarify what you mean by "junk things up"?

**Comment by Marmio64** [comment]
radial menus is good though

**Comment by Hopekz** [comment]
I like the radial menu's 
They bring us to the modern age instead of weird list menus. Especially for things like this with about 7 selections.

**Pull request merged**
