### PR TITLE
test pr to ensure all files are ticked in the dme

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

https://github.com/yogstation13/Yogstation/pull/21047 SHOULD BE MERGED FIRST !!

quick port of https://github.com/tgstation/tgstation/pull/76404

This PR does a few things:
- It adds a python script (replacing the old one) that ensures every .dm and .dmf file is checked in the DME and is in order. All files that were not in the DME have been deleted, you can scroll through Files Changed to see which ones if you want to try to bring one back yourself.
- Ports a fix for Pip https://github.com/tgstation/tgstation/pull/72488 just cause I noticed some things got ported and this was left out of it. We probably need this.
- Deletes the Redirector, it didn't appear to ever be read and was completely unecessary. Its code was untouched since 2012, and isn't even needed since you can just run yogstation.dme

# Why is this good for the game?

good stuff :D

# Testing

# Spriting

# Wiki Documentation

# Changelog

:cl: san7890, Mothblocks
experimental: All files now need to be in the dme
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
https://github.com/yogstation13/Yogstation/pull/20569 removes some files that aren't in the DME so this is 100% gonna fail and it's intentional

**Comment by JohnFulpWillard** [comment]
Let's go bros it works as mods

**Comment by iloveloopers** [comment]
Controversial

**Comment by JohnFulpWillard** [comment]
i'll come back to this

**Review by ToasterBiome — APPROVED** [review]

**Pull request closed without merging**
