### PR TITLE
Gives gondolas a nice green home

### PR DESCRIPTION
**Pull request by Hopekz**
Before:
------
image

After:
-----
image

#### Changelog

:cl:  Hopek
rscadd: Space PETA has given the endangered Gondola population a nice green home.
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
So this is where they get the gondola meat in the uplink from...

**Review by patpol4 — CHANGES_REQUESTED** [review]
Put in a tinyfan under the airlock for good measure and it will be ready to merge

**Comment by Hopekz** [comment]
> Put in a tinyfan under the airlock for good measure and it will be ready to merge

@wejengin2 ;
Done

**Review by patpol4 — APPROVED** [review]
Alright

**Comment by boodaliboo** [comment]
i truthfully think the brown looks nicer

**Comment by Hopekz** [comment]
> i truthfully think the brown looks nicer

The gondolas deserve grass

**Comment by Xoxeyos** [comment]
Give them a log cabin that they built with their non hands.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
