### PR TITLE
Shaft Mining Nerf: Shaft Miners can't work on Sunday due to Union Rules.

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Document the changes in your pull request

Shaft miners are OP so I made it so that Shaft miners can't work on Sunday due to new union rules.

# Wiki Documentation

https://wiki.yogstation.net/wiki/Shaft_Miner

# Changelog

:cl:  BurgerBB
tweak: Shaft Miners can't work on Sunday due to Union Rules.
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
what

**Comment by BurgerLUA** [comment]
new Union rules

**Comment by JamieD1** [comment]
funny

**Comment by Loldaddy5676** [comment]
damn they shut the union down

**Pull request closed without merging**
