### PR TITLE
Adds wirecrawling as an Ethereal traitor item

### PR DESCRIPTION
**Pull request by Moltijoe**
Gives wirecrawling, a completely new thing that's basically ventcrawling
-Can only enter on uncovered wires or if there's an apc or other power based machine
-Can only travel from wire to wire
-Adds a visual trail as you travel
-3 seconds to enter, instant to leave

costs 8 TC because it's basically just a weirder version of an emag

# Why is this good for the game?
Gives the ethereal main something to look forward to when they roll antag

# Testing (just pretend the martial arts bit isn't there anymore)
https://github.com/yogstation13/Yogstation/assets/108117184/b654a220-964d-4b46-a1e2-22d3d4ef8959

# Wiki Documentation

How wirecrawl functions

:cl:  
rscadd: Adds wirecrawling as an Ethereal traitor item
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
but does it work on monkeys?

**Comment by Moltijoe** [comment]
> but does it work on monkeys?

no

**Comment by PibeCantina** [comment]
If the person i collide with has insuls or the insulated gene, do they still get shocked?

**Comment by Moltijoe** [comment]
> If the person i collide with has insuls or the insulated gene, do they still get shocked?

don't worry too much about it, things are still in discussion

**Review by MajManatee — APPROVED** [review]
neat

**Pull request merged**
