### PR TITLE
Adds fire crocs.

### PR DESCRIPTION
**Pull request by Leatherturtle**
Wow, fire crocs

### I have sprited, and hopefully properly coded fire_crocs in. I have almost no idea of what I am doing, but this will hopefully be something I did right for once in my life. Crocs, as in the shoe brand, not the animal.

I have not changed maps... or tested, because I can't

edit: Crocs now in clothesmate vendor
#### Changelog

:cl:  
rscadd: Added fire crocs, the only thing needed to make this server perfect
wip: This is work in progress  
imageadd: added some icons
/:cl:

### CODE REVIEW

**Comment by Leatherturtle** [comment]
Fire_crocs
Fire_crocs_worn

**Comment by Xoxeyos** [comment]
Steel toed crocs next?

**Comment by Leatherturtle** [comment]
> Steel toed crocs next?

Hell yeah

**Review by nesisknesis — COMMENTED** [review]
Are these being added anywhere? How will someone wear them?

**Comment by Leatherturtle** [comment]
> Are these being added anywhere? How will someone wear them?

They are wearable, but I don't really know how to have them put anywhere, so they'll just sort of just be admin spawnable for now,

**Comment by boodaliboo** [comment]
i got excited because i thought crocodiles were being added

**Comment by patpol4** [comment]
Why

**Comment by Leatherturtle** [comment]
> Why

Something bothering you?

**Comment by patpol4** [comment]
> > Why
> 
> Something bothering you?

Just thinking about fire crocs, that's all

**Pull request merged**
