### PR TITLE
adds regen slime pens to lavaland chemistry ruin

### PR DESCRIPTION
**Pull request by boodaliboo**
thanks to mqiib for the idea
gives the ruin some much needed loot
changelog:
added slime pen
reason for adding it
i want more lavaland loot and variety
:cl:  
rscadd: Added regen slime medipens to lavaland chemistry ruin
/:cl:

### CODE REVIEW

**Review by alexkar598 — CHANGES_REQUESTED** [review]
feature pr, add template

**Comment by boodaliboo** [comment]
> feature pr, add template

no the template is stupid and not needed when i can describe my pr in a few sentence also you rarely do the template aswell

**Review by patpol4 — CHANGES_REQUESTED** [review]
Lack of template is not negotiable

**Comment by boodaliboo** [comment]
> Lack of template is not negotiable

it very much seems to be in a large majority of prs

**Comment by patpol4** [comment]
2 weeks have passed, still no template, also not every ruin needs loot

**Pull request closed without merging**
