### PR TITLE
Do you smell that? Somethings' getting STANKY in here. (Two new emotes)

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Adds two new emotes to allow the brain damaged yoggite to better express themselves.

You can now:
Hit the griddy.
Do the stanky leg.

as you can tell these are vital to the game.

# Wiki Documentation
Emote paged addition (if any)

# Changelog

:cl:  
rscadd: Two vital emotes. You can now Hit the griddy and Do the stanky leg.
/:cl:

### CODE REVIEW

**Comment by Ethan4303** [comment]
this is a good pr and if it had anything to do with mapping id have approved it already

**Comment by Moltijoe** [comment]
honestly don't think these need to be built-in emotes
you can always *me if you want to do a custom emote

**Comment by cowbot92** [comment]
We have dab, we can have these.

**Comment by Yarinoi** [comment]
if these get merged im quitting yogs and going to another server

**Comment by Runian** [comment]
Is there going to be any effects to these emotes? Dab at least made your character   tilt so it looked like you dabbed.

**Comment by N3D6** [comment]
Ideally not

who am I kidding this is funny as fuck

**Comment by ToasterBiome** [comment]
make them donator only

**Review by Bibby0110 — APPROVED** [review]

**Comment by LoliconSlayer** [comment]
Omg he's widerawy hitting the gwiddy on Space Station 13

**Comment by Yarinoi** [comment]
goodbye yogstation

**Pull request merged**
