### PR TITLE
Corporations I: Traitors, revheads, IAA, now get paid by their alternative employer as well

### PR DESCRIPTION
**Pull request by Amelia0010**
Syndicate corporations will now pay each operative they have a modifier of their nanotrasen pay in addition to their nanotrasen pay.

:cl:
tweak: Syndicate agents now have more money available to them as they also get paid by their syndicate benefactors
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
Stonks only go up

**Comment by MegaEmpirical** [comment]
I fucking love it.

**Comment by Marmio64** [comment]
finally, traitors actually get paid for their work

**Comment by LazennG** [comment]
that guy has more money than me valid his ass

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
