### PR TITLE
Removes Mindreader from genetics

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Removes the mindreader gene from genetics & centcom
Adjusts the Cerebral Neuroplasticity gene recipie

# Why is this good for the game?

This is only used by metagamers full stop, with the only counter to be either absolutely lucky or wear a tinfoil hat and give yourself brain damage.

# Testing

yeah

# Wiki Documentation

Remove all mention of mindreading from the face of the earth!

# Changelog

:cl:  

rscdel: Removed mindreading
tweak: tweaked cerebral neuroplasticity gene

/:cl:

### CODE REVIEW

**Comment by Tenn0x** [comment]
Just remove the showing of the 'real name' and up the phrases shown from 3 to 5. Could also add some disgust when using it like the spatial instability one.

**Comment by Scrambledeggs00** [comment]
Rip my Psycho Mantis gimmick I've done like once o7

**Comment by iloveloopers** [comment]
when has mindreader ever actually gotten an antag caught?

**Comment by azzzertyy** [comment]
> when has mindreader ever actually gotten an antag caught?

many times

**Review by Aquizit — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
