### PR TITLE
Bluespace harvester can now output alien tool

### PR DESCRIPTION
**Pull request by warface1234455**
give more loots for bluespace harvester

# Document the changes in your pull request
Bluespace harvester can now output alien tool for 60000 points

# Wiki Documentation
yes above

# Changelog

:cl:  

tweak: Bluespace harvester can now output alien tool for 60000 points
/:cl:

### CODE REVIEW

**Comment by Ethan4303** [comment]
If you can get the tools from harvestor I'd suggest removing the tech node so you don't just do a one and done

**Comment by KingSuperBOB** [comment]
> If you can get the tools from harvestor I'd suggest removing the tech node so you don't just do a one and done

Alien technodes require multiple alien tools for each node last I checked also you will be fighting with everyone on station to keep them from spending all the points for hats in 0.5 seconds

**Comment by Ethan4303** [comment]
> > If you can get the tools from harvestor I'd suggest removing the tech node so you don't just do a one and done
> 
> Alien technodes require multiple alien tools for each node last I checked also you will be fighting with everyone on station to keep them from spending all the points for hats in 0.5 seconds

Still doesn't matter since the tech node will give you any tool for just 2 alien tools and you can build multiple harvestors any where so no one's going to bumrush your harvestor or use the points if you just don't tell any one or build it in science, no one uses bluespave harvestors for hats any way albeit for like 1 or 2, like I built one in the incinerator room and ran it off the turbine and no one came to use except the ce and a couple of specific people I told

**Review by MajManatee — APPROVED** [review]
Look fine

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
increase it by a LOT. 30000 is nothing for an alien tool.

**Comment by MajManatee** [comment]
"Increase it by a lot"
from a 3 to a 4
I don't think that's enough

**Comment by ShoziOffical** [comment]
@ToasterBiome

**Review by ToasterBiome — APPROVED** [review]
If it's really bad then we can increase it more

**Pull request merged**
