### PR TITLE
Ports advanced surgical medkits from TG + some new icon sprites

### PR DESCRIPTION
**Pull request by ghost**
Replaces doctor's standard medkit with the medical first aid kit.

Comes equipped with standard med supplies but also surgical tools-only the ones necessary to do tend wounds, however.. Can hold up to 12 items and anything a medbelt can hold.

Surgical tools will make it easier to do tend wounds.
#### Changelog

:cl:  
rscadd: Added the medical first aid kit to medbay. Comes equipped with some basic medical gear to encourage the use of tend wounds surgery.
imageadd: Added some new medkit icons.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
I'm not too fond of the medkit sprites.
Not even sure what would make them "better" seems like something "soulless" in a completely different art style.

You should maybe atomise your PR between adding the single medkit and respriting all medkits.

image

**Comment by patpol4** [comment]
Agree with Hopek, the new sprites feel off

**Comment by ghost** [comment]
Get used to it, there's no alternative sprite for the medkits. 

If you don't like them we can just retexture them to be old again later but give it a shot. Frankly you'll get used to how they look in a bit-I hated them too but they look fine now.

Honestly, 'soulless' is a dumb critique. They're both just boxes.

**Comment by ghost** [comment]
How the fuck did this delete half the repo? Give me a second

**Comment by ghost** [comment]
WHY ARE YOU STILL FAILING YOU PIECE OF SHIT

**Comment by ToGWtF** [comment]
I dislike both the sprites and the idea itself

**Comment by Hopekz** [comment]
> If you don't like them we can just retexture them to be old again later  

Or we can not merge this in the first place. 
Bizarre mentality why make a change that you have to revert in the future? 

These new sprites don't even make sense because our medibots use the old medkit sprite. These sprites add negative value as they're a "half measure" trying to solve a problem that doesn't exist.

LGewIyOaCe
x23FJGzgWq

 Because they seem to be in a different art style, these new sprites feel comically large, in my opinion. 
If these sprites need to come bundled with this PR then this PR should not be merged in the first place.
HLzt1JtooF

**Comment by ghost** [comment]
Hopek changed his mind after a conversation on the discord when he realized additional TG artstyle is inevitable.

**Comment by Moggram** [comment]
> 
> 
> Hopek changed his mind after a conversation on the discord when he realized additional TG artstyle is inevitable.

I would say that it is not 'inevitable' if (and that is a big IF) yog as a hole say no to the art style. It is nice that we are getting drapes as standard gear so I don't have to use bed sheets when it goes missing form the surgery room.
Going to miss the cool burn and bio icons. Maybe someone will add them back.

**Comment by ghost** [comment]
@Moggram 

It is inevitable because we can't avoid it. TG uses a different artstyle than us for things like this.

Every single time we port a PR with one of their features that we don't have an alternative sprite for, we'll have to use their sprites, because we don't have any dedicated spriters.

So there's no option to 'say no to the artstyle'. Either we tolerate the artstyle in exchange for getting their features, or we fall behind on their features-that means no new spells, antagonists, no new mob designs, et cetera.

One or the other, buddy. In this case, I couldn't port the surgical kits without porting the sprites, because no alternative sprite exists for the surgical medbay medkit that doctors now spawn with. If I only port the new-medbay medkit and give it TG's sprite, it doesn't line up with the rest of them.

**Comment by Moggram** [comment]
@AdamElTablawy 
Oh I get that three would be a cost. Just saying we could if yog made that sacrifice and I don't think we will.

**Comment by JamieD1** [comment]
Sprites are shite, atomize.

**Pull request closed without merging**
