### PR TITLE
Removes monster860 from CODEOWNERS

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Revenge for
image

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
annihilation

**Comment by neeshacark** [comment]
you imply monster was ever 'active' and not just a magical ~fairy~ furry that appeared sometimes and dropped some of the most autistically cool code in existence

**Comment by MajManatee** [comment]
i mean, hes right

**Review by Moltijoe — APPROVED** [review]
release us from our shackles

**Pull request merged**
