### PR TITLE
abductors can buy posters

### PR DESCRIPTION
**Pull request by ktlwjec0**
https://github.com/tgstation/tgstation/pull/76101 posters from this

it's just really funny, no other reason for it

Adds 8 abductor themed posters, costs 1 credit to buy a random one. Posters can now be placed on abductor walls. Abductor posters can't be ripped off by non-abductors (funny), can be taken off via wirecutters.

# Spriting
image

# Wiki Documentation

probably somewhere i will have a look

:cl:  Rhials, ktlwjec
rscadd: The abductor equipment vendor now sells decorative abductor posters, at a price of 1 research point.
rscadd: Posters can now be hung on abductor walls.
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Merge this now.

**Comment by iloveloopers** [comment]
came to earth in a silver chrome UFO

**Comment by azzzertyy** [comment]
let them place them on non abductor walls itl be funny

**Comment by ktlwjec0** [comment]
> let them place them on non abductor walls itl be funny

they can

**Review by cuackles — APPROVED** [review]

**Pull request merged**
