### PR TITLE
Dragon Slayer Nullrod + SORD sillification

### PR DESCRIPTION
**Pull request by Yarinoi**
it was a wee to big to be called a sword

im very aware this is probably going to be asked to be nerfed

# Document the changes in your pull request

Adds a new nullrod, the Dragon Slayer, boasting far more damage then the standard nullrod at the cost of swinging slower, and making you slower on hit, as well as being needed to be wielded with two hands.  People with the strength gene can wield it one-handed for it to behave like a regular nullrod, with a 0.5 second-long stun taking place between switching from onehand to twohand.
also gives the sord funnier attack verbs because it deserves better

# Why is this good for the game?
https://www.youtube.com/watch?v=hhJAEG7PC9Y

# Testing
later

# Spriting
Sprites done by the wonderful WillyBilly on discord
image
image

# Wiki Documentation

Add to the nullrod list on the chap wiki page.

# Changelog

:cl: Yarinoi & WillyBilly
rscadd: GRIFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIITH (Translation: New Dragon Slayer null rod!)
tweak: SORD buff.
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
wait shit i didnt add the endurance stuff, woopsie

**Comment by Moltijoe** [comment]
lemme know whenever it's ready for balance council

**Comment by hwseo7** [comment]
I think it should swing even slower, since it has one of the highest melee weapon damage in entire game and also cause nasty wounds. I think at least it's dps should be significantly lower compared to other nullrods.

**Comment by Yarinoi** [comment]
yeah im never finishing this at this rate LMAO

**Pull request closed without merging**
