### PR TITLE
Makes heretic spell code cleaner

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

moves literally everything from 1 long fucking file to multiple split up files

# Why is this good for the game?

its good for my eyes

# Changelog

:cl:  

tweak: moves files around

/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
The stuff added in the mansus_grasp file is being added in https://github.com/yogstation13/Yogstation/pull/20618  but im adding it here so I don't end up fucking up anything

**Review by Moltijoe — APPROVED** [review]

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
this is too many files can you split them into paths

**Comment by cowbot92** [comment]
> this is too many files can you split them into paths

can I have an example of what that means

**Comment by ToasterBiome** [comment]
> > this is too many files can you split them into paths
> 
> can I have an example of what that means

put all the mind spells into mind.dm, all void ones into void.dm, all lore ones into lore.dm, all misc ones into generic.dm

**Comment by cowbot92** [comment]
> > > this is too many files can you split them into paths
> > 
> > 
> > can I have an example of what that means
> 
> put all the mind spells into mind.dm, all void ones into void.dm, all lore ones into lore.dm, all misc ones into generic.dm

ok got it

**Comment by cowbot92** [comment]
Need to close this to make it better since other PRs got merged, will open a new one later.

**Pull request closed without merging**
