### PR TITLE
Beepsky can no longer become sentient via sentient animals event

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

idk why anyone thought to give beepsky 400 hp and sentience was a good idea

#### Changelog

:cl:  
rscdel: sentient beepsky qdel'd
/:cl:

### CODE REVIEW

**Comment by Codeatmos** [comment]
i dead plase nerf

**Comment by jcatjmeow** [comment]
Should have titled it "beepsky is no longer an animal"

**Comment by boodaliboo** [comment]
hoes mad hoes mad hoes mad (just keep it as a event and lower its health dumbass)

**Comment by alexkar598** [comment]
It's so rare, it barely matters

**Comment by SomeguyManperson** [comment]
:green_salad:

**Comment by ynot01** [comment]
Gn490kF

**Comment by ynot01** [comment]
i did some math with fluffe and determined that sentient beepsky has effectively 400hp (200hp + 0.5 brute resist) versus bullets and 667hp (200hp + 0.7 burn resist) versus laser guns and other burn methods

normal beepsky has 1/8 of the health of sentient beepsky

**Comment by Quartich** [comment]
> i did some math with fluffe and determined that sentient beepsky has effectively 400hp (200hp + 0.5 brute resist) versus bullets and 667hp (200hp + 0.7 burn resist) versus laser guns and other burn methods
> 
> normal beepsky has 1/8 of the health of sentient beepsky

Lower health instead of just removing the ability that this can happen

**Comment by MegaEmpirical** [comment]
I'm okay with removing it just because beepsky isn't an animal. Make a different pr to make a sentient beepsky in a way that makes sense if you care.

**Comment by HomocidlePancakes** [comment]
“AI LAW 2 DISABLE BEEPSKY” or EMPs. Not that hard.

**Comment by deadmomo69** [comment]
instead of deleting a super rare event, why not just lower its health?

**Comment by alexkar598** [comment]
10 no to 3 yes. Also I am strongly against the removeee :DDDDDD philosophy. If you say it has stupid amounts of health,why dont you fix that instead.

**Comment by MegaEmpirical** [comment]
I still think it should be its own event since beepsky isn't an animal. This is madness.

**Pull request closed without merging**
