### PR TITLE
removes a bunch of useless stuff from bluespace harvester

### PR DESCRIPTION
**Pull request by iloveloopers**
# Document the changes in your pull request

removes the bedsheets, carpets, cigars and pills from the harvester

# Why is this good for the game?
this stuff is completely useless and just lowers the chances of actually getting cool stuff like the slip bombs

# Testing
it works probably

# Wiki Documentation

bs harvester isn't on the wiki

# Changelog

:cl:   
rscdel: Removed many useless items from the bluespace harvester loot pool
/:cl:

### CODE REVIEW

**Comment by YashinHak** [comment]
suffer . you WILL get bedsheets and carpeting

**Comment by iloveloopers** [comment]
let me get cool items you guys suck!!!

**Comment by ShoziOffical** [comment]
those useless items can be obtained easily (except for bedsheets they are just cosmetics anyway) and they are too costly in bs harvester, removal is good

**Comment by Moltijoe** [comment]
balance council:
>That stuff is literally there to bloat the list as it reduces the ability to abuse specific items on the list

**Comment by iloveloopers** [comment]
> balance council:
> 
> > That stuff is literally there to bloat the list as it reduces the ability to abuse specific items on the list

this is stupid. you force me to make multiple harvesters so I can actually get stuff that isn't completely useless.

**Pull request closed without merging**
