### PR TITLE
renames all autoinjectors to medipen

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
autoinjectors imply that it will automatically inject into you when a certain condition is met but they dont and are just medipens so i renamed all autoinjectors to clarify that you need to manually inject them
#### Changelog

:cl:   
tweak: tweaked names and descriptions of a few medipens/autoinjectors  
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
Medipen sounds cooler

**Comment by boodaliboo** [comment]
sorry for bad desciption as usual

**Comment by alexkar598** [comment]
how can you be this dumb? auto injector means its auto aka self aka inject self without help

**Comment by boodaliboo** [comment]
> how can you be this dumb? auto injector means its auto aka self aka inject self without help

how can you be this dumb? auto injector means its auto aka automatica aka it automatically applies it to you with no outside help

**Comment by yacabo** [comment]
image

I still prefer the name change, but as it stands the current name is accurate

**Comment by boodaliboo** [comment]
the more you know well either way ill keep this open

**Comment by Ktlwjec1** [comment]
Auto-injector is fine, enjoy your new fact it is always nice to learn new things.

**Pull request closed without merging**
