### PR TITLE
[AI] [Concept] New AI upgrade that allows AI to deathmatch anyone trying to download it, in a form of virtual arena. 

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

If the downloader wins they get to download the AI, and they also get teleported to a random safe turf so the AI can't meta it by telling Sec where they are before starting the match

If the AI wins the loser gets electrocuted. (Maybe also teleported to a safe turf so you can't meta it)

Note to self:

- [ ] Make sure to specify that the AI does not have to obey its laws in the arena
- [ ] Maybe rock-paper-scissors to choose combat form (Guns, melee)

# Wiki Documentation

# Changelog

:cl:  
experimental: AI gets to fight people attempting to download it
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
how badly does the electrocution fuck the loser up

**Comment by Bibby0110** [comment]
> how badly does the electrocution fuck the loser up

Pretty bad, not a kill though.

**Comment by ynot01** [comment]
an AI may be obligated to allow downloading to avoid shocking a human and causing harm

**Comment by Simplehorror** [comment]
How will this integrate with traitors wanting to steal the AI? Will they go through the same process?

**Comment by Bibby0110** [comment]
> How will this integrate with traitors wanting to steal the AI? Will they go through the same process?

yes

**Comment by Bibby0110** [comment]
> an AI may be obligated to allow downloading to avoid shocking a human and causing harm

Asimov doesn’t deserve to have fun

**Comment by Marmio64** [comment]
this is going to be a researchable upgrade, yes?

**Comment by Bibby0110** [comment]
> this is going to be a researchable upgrade, yes?

yes

**Comment by patpol4** [comment]
I cannot believe Bibby had a good idea

**Comment by maxion12345** [comment]
should make them play Tron or something similar with using trails to try to block the other lol

**Comment by Moja10** [comment]
It should be a 30 second stun or something absurd so all AI lawsets can use it.

**Comment by Bibby0110** [comment]
okay i have time for this again

**Pull request closed without merging**
