### PR TITLE
SuperMatter now reacts with new gases + new reactions

### PR DESCRIPTION
**Pull request by CMOisLing**
New gases now actually react with SM. Added some new reactions, will add more in another PR after this is merged and experimented with because im scared what atmos mains can do.

Zauker - Increases SM damage cap 10x at full ratio
Healium - Increases healing speed 5x
Halon - Greatly reduces Heat and Waste, at 15% reduces plasma o2 ratio to 50 50
Hypernoblium - Greatly increases heat resistance

:cl:  
rscadd: Adds new SM gas reactions 
bugfix: new gases now actually react with SM
/:cl:

### CODE REVIEW

**Comment by CMOisLing** [comment]
Will fix when I figure out VSC again

**Comment by iamthesilly** [comment]
should replace halon with hypernoblium in my opinion

**Comment by CMOisLing** [comment]
Hypernoblium already stops all in chamber and loop reactions so you can get really high temps without worrying about fires. I figured it would be overkill to add an effect as well.

**Comment by iamthesilly** [comment]
> Hypernoblium already stops all in chamber and loop reactions so you can get really high temps without worrying about fires. I figured it would be overkill to add an effect as well.

it doesn't stop fires actually

**Comment by iamthesilly** [comment]
for whatever reason combustion reactions aren't stopped by hypernoblium, i've been trying to fix it but haven't been able to figure out the issue

**Comment by Rdrazga** [comment]
Halon should not kill power, it is useful in very specific SM reactions as it kills the oxygen the SM produces (lowers power slightly) but stops fires because of this. Halon is also stupidly hard to produce for how few moles of O2 it takes out of the air imo

**Comment by CMOisLing** [comment]
closing this until I get time to work on it

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
