### PR TITLE
I LOVE MY MUG ROOT BEER

### PR DESCRIPTION
**Pull request by ChesterTheCheesy**
# Document the changes in your pull request
Gives our resident mugmin @N3D6 a 4pack of his favourite beverage he deserves.

obraz

# Changelog
:cl:  
rscadd: I LOVE MY MUG ROOT BEER!
imageadd: I LOVE MY MUG ROOT BEER!
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Wait hold on is this just a drink that gives you godmode and then gibs you when it runs out?
And you're giving this god mode juice as a donator item?

**Comment by Hopekz** [comment]
Don't think this will get merged as is but personally I'd like to see the overdose amount to be lower since all it does is jitter and shout a phrase

**Comment by N3D6** [comment]
This would be funny if it was an admin only bus thing

**Comment by ChesterTheCheesy** [comment]
MUG has been toned down to be a regular drink, and as requested, is an admin spawn only thing now.

**Comment by nesisknesis** [comment]
I'm pulling my eyes out and throwing them at you

**Comment by N3D6** [comment]
L ident

**Comment by maxion12345** [comment]
L

**Pull request closed without merging**
