### PR TITLE
Gold grub guts and medicine

### PR DESCRIPTION
**Pull request by Marmio64**
Adds gold grub guts, something you can slice open from gold grubs after you genocide them. Sometimes cargo will get a bounty for gold grub guts, otherwise you can grind them up for a potent medicinal product. Although this medicinal product can quickly heal you, it isn't very hard to overdose on, and it causes liver damage when used. Just 10 units of the juice is enough to cause severe liver damage, so be careful how much you use. Sprite is a recolored changeling egg sprite.

goldgrubgutspic

#### Changelog

:cl:  
rscadd: Adds gold grub guts, and it's medicinal reagent.
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
Finally I can butcher goldgrubs. Also, it gives them a use. Good change, they were just clogging up space beforehand and were a waste of muscle strength to click on them. The golden boys get the love they deserve now

**Comment by boodaliboo** [comment]
change grub juice to grub enzyme sounds a bit better and enzymes and bacteria live in the gut i think, also a juice of a animal sounds gross

**Comment by Marmio64** [comment]
> change grub juice to grub enzyme sounds a bit better and enzymes and bacteria live in the gut i think, also a juice of a animal sounds gross

it is gross, you're grinding up raw grub intestines and slurping it down like it's soda

**Comment by boodaliboo** [comment]
> > change grub juice to grub enzyme sounds a bit better and enzymes and bacteria live in the gut i think, also a juice of a animal sounds gross
> 
> it is gross, you're grinding up raw grub intestines and slurping it down like it's soda

yeah but i dont think the term juice should be used with meat

**Comment by Marmio64** [comment]
> > > change grub juice to grub enzyme sounds a bit better and enzymes and bacteria live in the gut i think, also a juice of a animal sounds gross
> > 
> > 
> > it is gross, you're grinding up raw grub intestines and slurping it down like it's soda
> 
> yeah but i dont think the term juice should be used with meat

why you so worried, it is just some intestinal juices

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
