### PR TITLE
[Gax] Fixes MANY disposal pipes, Adjusts Central Primary Distro/Scrubber Pipes, Adds Surgical holosigns to surgical

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Fixes disposals for almost the entire station. you can now properly throw stuff away, and also properly ship items to every single tagger location.

adds disposals/outlets for Toxins and "Testing Range" which dumps into the launch room for toxins. Required minor structural tweaks. Tried to prevent making toxins easier or harder to get into as best I could.

replaces sorter pipe that led to the captain's office with a junction (there's no cap's office sorter tag, this can be rectified in a later PR)

adds a disposal outlet to virology (Made some small changes, added a table by the monkey pen while moving its windoor, swapped the nanomed for a wallmed to fit the table there for the boxes, added a grinder & plasma to the new table by the monkeys)

makes cargo's deliveries instead pop out over at the desk, replacing the delivery outlet with two crates and decals

makes central-primary hallway's vent/scrubber pipes form a proper loop so vent-crawlers have an easier time navigating the station

Adds surgical holosigns to surgery & a button to toggle them

# Changelog

:cl:  
bugfix: disposals on Gaxstation work properly
bugfix: removes random layered straight disposal pipe from security, and xenobiology
rscadd: adds a disposal outlet to virology, toxins, toxins launch chamber, and xenobiology
tweak: Central Primary Hallway pipes on Gaxstation now form a proper loop
rscadd: adds surgical holosigns to Gaxstation Surgery
rscadd: adds a grinder and two sheets of plasma to Gaxstation virology
tweak: cargo disposals outlet removed, cargo bay deliveries are pathed instead to the chute over by the desk
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
initially was going to add fire safety closets but decided against it since...honestly there's plenty of them laying around for a lowpop map

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Undo 3 and 5

3. Design decision, meta shares this style
5. Covered in the other PR

**Comment by VaelophisNyx** [comment]
I'll do it tomorrow, but will get that done

**Comment by VaelophisNyx** [comment]
> Undo 3 and 5

Did you mean 3 and 4, or 5 as in the tool addition

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
