### PR TITLE
Disables Rad Goat and Anomaly for Good

### PR DESCRIPTION
**Pull request by JamieD1**
Disables Rad Goat and Anomaly for Good

:cl:  
rscdel: Disables Rad Goat and Anomaly for Good
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
cool idea on paper unfortunately rads are terrible to deal with and get out of hand very quickly

they are fine being confined to the department of engineering as a job hazard for those who toy with elements beyond their knowledge

**Comment by TheRyeGuyWhoWillNowDie** [comment]
horrible anomaly, creates a griefy simplemob, doesn't even have its own reactive armor. good riddance

**Comment by ShoziOffical** [comment]
> horrible anomaly, creates a griefy simplemob, doesn't even have its own reactive armor. good riddance

that is about the anomaly  not about the mob

**Comment by ShoziOffical** [comment]
i should make this antag item only, or wiz item

**Comment by JamieD1** [comment]
> > horrible anomaly, creates a griefy simplemob, doesn't even have its own reactive armor. good riddance
> 
> that is about the anomaly not about the mob

THE MOB MAKES THE ANOMALY AS WELL?!?

**Comment by ShoziOffical** [comment]
> > > horrible anomaly, creates a griefy simplemob, doesn't even have its own reactive armor. good riddance
> > 
> > 
> > that is about the anomaly not about the mob
> 
> THE MOB MAKES THE ANOMALY AS WELL?!?

no, i mean its about the anomaly if it gets destroyed by neutralizer it spawns a core

**Comment by JamieD1** [comment]
> > > > horrible anomaly, creates a griefy simplemob, doesn't even have its own reactive armor. good riddance
> > > 
> > > 
> > > that is about the anomaly not about the mob
> > 
> > 
> > THE MOB MAKES THE ANOMALY AS WELL?!?
> 
> no, i mean its about the anomaly if it gets destroyed by neutralizer it spawns a core

You are clearly missing the picture here.

**Comment by ShoziOffical** [comment]
why not just disable the var that spawns radd goat instead of thiss

**Comment by ShoziOffical** [comment]
> > > > > horrible anomaly, creates a griefy simplemob, doesn't even have its own reactive armor. good riddance
> > > > 
> > > > 
> > > > that is about the anomaly not about the mob
> > > 
> > > 
> > > THE MOB MAKES THE ANOMALY AS WELL?!?
> > 
> > 
> > no, i mean its about the anomaly if it gets destroyed by neutralizer it spawns a core
> 
> You are clearly missing the picture here.

i know whats he talking about but this is not about the anomaly core, because i forgot to give the use of it

**Comment by ShoziOffical** [comment]
Wait WHy are you removing rad anomaly smhh, it did nothing wrong

**Comment by TheRyeGuyWhoWillNowDie** [comment]
because it irradiates everything and radiation is horrible to deal with and ruins parts of the station more or less forever

**Comment by ShoziOffical** [comment]
> because it irradiates everything and radiation is horrible to deal with and ruins parts of the station more or less forever

neutralizer exists, rad suit and engi hardsuit exists to deal with it. It's not like the pyro that can literally burn you and everything in one room

**Comment by JamieD1** [comment]
Also the fact you go near it, it irradiates you and puts you to sleep and then it keeps irradiating you. Its dumb.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
you can fix a room being burnt. you cannot fix a room being covered in 10 trillion shitverts of radiation

**Comment by ShoziOffical** [comment]
> you can fix a room being burnt. you cannot fix a room being covered in 10 trillion shitverts of radiation

you know rad go away faster now, and the rad anomaly doesnt emit that much radiation that can kill you instantly. Just wait like 1 min and 30 seconds then the rad will go away permanently

**Comment by ShoziOffical** [comment]
> Also the fact you go near it, it irradiates you and puts you to sleep and then it keeps irradiating you. Its dumb.

maybe at least wear a rad suit or engi hard suit when going near it?? or dont because why would you go near it naked

**Comment by JamieD1** [comment]
> > you can fix a room being burnt. you cannot fix a room being covered in 10 trillion shitverts of radiation
> 
> you know rad go away faster now, and the rad anomaly doesnt emit that much radiation that can kill you instantly. Just wait like 1 min and 30 seconds then the rad will go away permanently

This is in an ideal situation where people are competent, we cant design around best case scenarios.

**Pull request merged**
