### PR TITLE
Makes caravan ambush slightly worse

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

- Remove pulse slug and 2 taser slugs, replace them with buckshot
- Pirate no longer drops cutlass
- Changes the cutter button/turret panel positions slightly
- Removes a mini e-gun and moves one
- Removes the 40mm shells from the cutter
- Move the APS to the victim ship
- Added a crate with admiral clothing
- Victim ship has a auto/proto/circuit boards
- Cutter gets a syndicate toolbox
- Pirates no longer drop laser gun
- Pirate gives you a cutlass that does the same damage as chain of command

image

#### Changelog

:cl:  
tweak: Nerfs Caravan Ambush slightly
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Is there some sort of secret group where you discuss and coordinate all these ruin nerf pr's, i don't understand

**Comment by redmoogle** [comment]
> 
> 
> Is there some sort of secret group where you discuss and coordinate all these ruin nerf pr's, i don't understand

No ~~yes~~ 
and nowhere of course ~~totally not in the mbrain~~

**Comment by ghost** [comment]
@wejengin2 yes

**Comment by Mesalikepie** [comment]
Removing slugs fine great idea in fact. Powergamers dream there. Keep the Cutlass. It's hella fun to have an ecutlass and a good reward for getting inside the pirate ship especially as a newer ruin explorer. Removing the mini eguns doesn't really feel needed they aren't too useful and most people who loot the ruin successfully usually just give away most of the guns including that. They just aren't that strong nor good in comparison to the 30 laser guns you get (excageration). Removing 40 mm pretty damn all right idea. I am fine with that. Remove the aps? What the fuck? Why aps isn't even that good! Ammo is hard to come by for it and it's garbage at anything but close range and sucks ammo fast. The appeal of the aps is it's unique and looks cool as heck.

**Comment by redmoogle** [comment]
> 
> 
> Removing slugs fine great idea in fact. Powergamers dream there. Keep the Cutlass. It's hella fun to have an ecutlass and a good reward for getting inside the pirate ship especially as a newer ruin explorer. Removing the mini eguns doesn't really feel needed they aren't too useful and most people who loot the ruin successfully usually just give away most of the guns including that. They just aren't that strong nor good in comparison to the 30 laser guns you get (excageration). Removing 40 mm pretty damn all right idea. I am fine with that. Remove the aps? What the fuck? Why aps isn't even that good! Ammo is hard to come by for it and it's garbage at anything but close range and sucks ammo fast. The appeal of the aps is it's unique and looks cool as heck.

Specifically with the ecutlass is that it is way to spicy of a sword, as for the APS ~~oops didnt know it was shit~~

Anyways, the reason why I made this PR was that the crew shouldnt get powerful loot, much less free guns for everyone

**Comment by Mesalikepie** [comment]
Your PR doesn't stop the free guns for everyone. The reason everyone and their mother gets free guns is pirates drop laser guns. It means woopee you get a gun, I get a gun. Removing the mini energy guns does nothing for this really. Also I have never seen this amount of Lazer guns being abused by anyone is the funny thing. Our rules are strict enough and generally the people who do loot it aren't assholes and either give it up to the armory, hide it in cargo (declaring cargonia is against the rules and power game rules still apply so keeping guns on you fit it kinda), or just make their own mini armory in the white ship or the small vessel. I think crew should be allowed to get more powerful as time goes on (as it is). It encourages 
antags to focus on doing their objectives as early as possible. Sec gets advanced energy guns, and crew gets genetic powers generally. Also the energy Cutlass is a pirate staple. It's powerful yes but if abused sec can take it and I also am fairly certain in doesn't block ranged attacks

**Comment by boodaliboo** [comment]
fuck you im angrey today you stupid this is one of the hardest ruins to tackle without stockpiling healing items and you remove the rewards from it sorry

**Comment by redmoogle** [comment]
> 
> 
> Your PR doesn't stop the free guns for everyone. The reason everyone and their mother gets free guns is pirates drop laser guns. It means woopee you get a gun, I get a gun. Removing the mini energy guns does nothing for this really. Also I have never seen this amount of Lazer guns being abused by anyone is the funny thing. Our rules are strict enough and generally the people who do loot it aren't assholes and either give it up to the armory, hide it in cargo (declaring cargonia is against the rules and power game rules still apply so keeping guns on you fit it kinda), or just make their own mini armory in the white ship or the small vessel. I think crew should be allowed to get more powerful as time goes on (as it is). It encourages
> antags to focus on doing their objectives as early as possible. Sec gets advanced energy guns, and crew gets genetic powers generally. Also the energy Cutlass is a pirate staple. It's powerful yes but if abused sec can take it and I also am fairly certain in doesn't block ranged attacks

This is really just to me a reason to throw the majority of the weapons out, also crew really shouldnt be armed ever unless someone is killing everyone.



> 
> 
> fuck you im angrey today you stupid this is one of the hardest ruins to tackle without stockpiling healing items and you remove the rewards from it sorry

Prepare. dont bumrush

**Comment by Mesalikepie** [comment]
Redmoogle I would suggest a better fix to this ruin is to remove the shotgun slugs like you have, stop pirates in space from dropping laser guns, and remove the spare ammo as you have done. Then spread out the remaining guns. The reason the ruin is so abusable is all the guns are available in the middle. Move the two mini energy guns to spawn in the ship on the far left perhaps replacing their crates in the middle with a syndicate toolbox crate (not powerful really it's just weird a syndicate raid didn't bring syndicate tools) and another crate of bulletproof armor or something. The armor has no true use really and generally will not be kept and just used as flavor. Then add something to the far right ship to make it worth looting (the ship that gets it ignored presently). Doesn't have to be anything major just right now it has lost any reason to loot it with the grenade launcher being no longer there. Perhaps a sorta liberators legacy box? RND console, Protolathe, and Circuit imprinter so you can fix up your new ship you captured on the far left! That would encourage building up something for the station as a whole rather then running back going ungabunga time to valid hunt. Then maybe one last thing for the far white ship a centcomm uniform crate with a flavor note inside saying some grand admirals dresser. If the crate is shipped back to centcomm maybe it could give cargo something like 20k credits. It would be cool flavor, bring attention to damn this guy looted the signal, and if you don't wanna give the clothes back you got cool outfits.

**Comment by Reed0506** [comment]
well i guess the ruin is going to be harder now because there arent as many lasers to kill the ops with

**Comment by redmoogle** [comment]
> 
> 
> well i guess the ruin is going to be harder now because there arent as many lasers to kill the ops with

Intentional, you have access to a proto/circuit lathe and a autolathe

**Review by Partheo — APPROVED** [review]

**Comment by boodaliboo** [comment]
cutlass was added my opinion was changed now can rp as true pirate

**Comment by Mesalikepie** [comment]
Might wanna add an RnD console so one can actually use the circuit imprinters! Love these changes and am excited to create my future pirate ship y'arr

**Comment by redmoogle** [comment]
> 
> 
> Might wanna add an RnD console so one can actually use the circuit imprinters! Love these changes and am excited to create my future pirate ship y'arr

There

**Review by Ktlwjec1 — APPROVED** [review]
Map fine, need someone to look through the code still. May have a line ending issue.

**Comment by redmoogle** [comment]
> 
> 
> Map fine, need someone to look through the code still. May have a line ending issue.

That one PR was because it was in LF not CRLF like .gitattributes dictates so github was attempting to force it to CRLF

**Comment by redmoogle** [comment]
> 
> 
> > Map fine, need someone to look through the code still. May have a line ending issue.
> 
> That one PR was because it was in LF not CRLF like .gitattributes dictates so github was attempting to force it to CRLF

This does have that 'issue' but should probably just let it get changed to the proper line endings

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
