### PR TITLE
You can now select exactly which limb was lost in your tragic backstory

### PR DESCRIPTION
**Pull request by SomeguyManperson**
at the present you can select only one limb for prosthesis but i'm working on that

:cl:  
rscadd: Prosthetic limb now has sub-quirks allowing the selection of a specific limb for surprise amputation
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Can we have the limb fly off round start?

**Comment by SomeguyManperson** [comment]
No its part of your tragic backstory

**Comment by CMOisLing** [comment]
Make it so you can choose multiple limbs

**Comment by SomeguyManperson** [comment]
I'd need to aadd a system so traits can cgive less points if another trait was selected or people can stack emp vulnurability four times for free points and i havent yet divined a solution to that

**Comment by Xoxeyos** [comment]
> 
> 
> No its part of your tragic backstory

Coming to the station is your tragic backstory.

**Comment by Hopekz** [comment]
@ThatLing want to add something to clarify your down ooga?
Do you want to see a modification or do you just not like the whole idea?

**Pull request merged**
