### PR TITLE
Deletes all items in armoury roundstart of a battle royale

### PR DESCRIPTION
**Pull request by Moltijoe**
Save hisa some work

:cl:  
tweak: Battleroyale now auto deletes armoury
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Get rid of the uhh armament dispensers too?

**Comment by Moltijoe** [comment]
> Get rid of the uhh armament dispensers too?

I dont know security, what is that and where is it?

**Comment by MajManatee** [comment]
> > Get rid of the uhh armament dispensers too?
> 
> I dont know security, what is that and where is it?

The thingamabob that dispenses disablers and USPs for officers. One in the locker room, and one in the arrivals post.

**Comment by Moltijoe** [comment]
> The thingamabob that dispenses disablers and USPs for officers. One in the locker room, and one in the arrivals post.

It should be fine, i'll make a different PR if it becomes a problem.
Adding additional locations to clean up is pretty heavy on runtime

**Review by MajManatee — APPROVED** [review]
battle deese

**Pull request merged**
