### PR TITLE
GPS now actually rename round start 

### PR DESCRIPTION
**Pull request by Moltijoe**
Actually does what #16853 says it does

don't worry, i ACTUALLY tested this

:cl:  
tweak: all jobs with a gps start with it named to them
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
image

**Comment by Moltijoe** [comment]
just because it gets let in, doesn't mean someone tested it for you
there isn't exactly the manpower for it

**Comment by Simplehorror** [comment]
no I thought contents was recursive, I didn't read the ref

**Comment by Simplehorror** [comment]
you can just use GetAllContents instead though

**Comment by Moltijoe** [comment]
> you can just use GetAllContents instead though

Ah, thats far more elegant, thanks

**Review by MajManatee — APPROVED** [review]
kinda epic

**Pull request merged**
