### PR TITLE
ACTUALLY makes vial boxes fit on the medical belt

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Our coders are liars

# Wiki Documentation

No I changed the wiki already for this PR because I possess massive prophetic ability

# Changelog

:cl:  
tweak: Vial boxes now ACTUALLY go on medibelts
/:cl:

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
based, Jamie didn't want them to fit on the belt

**Review by ReddicusDragon — APPROVED** [review]

**Comment by Moltijoe** [comment]
oh damn, right, i forgot to rename the PR. didn't notice i got merged

**Comment by Moltijoe** [comment]
Wanna give vial boxes an upper case V in the print menu while you're at it?

**Comment by JamieD1** [comment]
I didnt want them to fit on the belt.

**Pull request closed without merging**
