### PR TITLE
Adds Flight Potion to all flight capable species' uplinks

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

The lizards said they would hurt me if I didn't do this

# Changelog

:cl:  
tweak: All species that can fly can now buy Flight Potions from the uplink
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Neat but I don't remember threatening you for this

**Comment by Moltijoe** [comment]
> Neat but I don't remember threatening you for this

Mqiib is "the lizards"

**Comment by ChuChu42** [comment]
if this gets merged, add a actual species restricted item for humans.

**Comment by Maia-J** [comment]
> if this gets merged, add a actual species restricted item for humans.

The racism gland when.

**Review by MajManatee — APPROVED** [review]
Humans arent special... thats kinda the whole point. they don't need a species restricted item.
also lizard wings are arguably the coolest

**Pull request merged**
