### PR TITLE
Bags of holding now require you to harvest the engine

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Introducing the Engine Containment Net

In short, it collects & holds engine fragments.

Pour collected engine fragments into a printed bag of holding to activate it.

Harvesting engines is dangerous. Keeping engine fragments inside of a net is also incredibly dangerous.

See below for details

# Wiki Documentation

Net & supermatter tools spawn in engineering secure tool storage and can be ordered from cargo for 6500 credits.

Due to the newfound prevalence of the supermatter tongs, you can no longer double-suicide dust people with it.

Bag of holding bounty doubled to 20,000 from 10,000 credits.

Currently only used for bags of holding.

You can transfer items between the nets if both nets are open.

**Dropping or setting down a net with any engine fragments in it will produce a small explosion which will fuck your shit up.** 
I have warned you and it will warn you of this ingame when using it.
Passing an item directly to another player with the Give keybind will not cause an explosion.
Dragging the net so that you never pick it up TO be able to drop it is also a valid strategy.

When a net is holding engine fragments, it will produce side effects with speed increasing with how many fragments are in the net. Thusly, a supermatter shard emits much slower than a full tesla bag because there is only 1 shard vs 4 energy balls.

These side-effects can quickly become lethal, so it is advised to have a bag of holding case at the ready. If you do it fast enough, you can avoid any side effects from occurring at all, especially in the case of the supermatter.

### Supermatter:
- Open the net by using it in hand
- Open the net by using it in hand
- Open the net by using it in hand
- **If the net is not open, the next step will kill you**
- Shard needs to be harvested using scalpel and tongs, then inserted into the **open net**
- This is very dangerous and will harm the supermatter, so you only need one shard to activate a BoH
- Side effect: Pulses radiation occasionally

### Singularity:
- Open the net by using it in hand
- Stand within 3 tiles of the singularity
- This is 3 tiles
- 
- Fragments will collect into the net automatically and weaken the singularity
- You will need 2 fragments to activate a BoH
- Side effect: Semi-regular EMPs

### Tesla:
- Open the net by using it in hand
- Stand within 3 tiles of the tesla
- Energy balls will collect into the net automatically and weaken the tesla
- You will need 4 energy balls to activate a BoH
- Side effect: Frequent harmful (but not explosive) energy arcs. Wear insulated gloves to reduce damage. **Tesla arcs will only shock the holder if they hit another mob.**

# Spriting
By cuackles
dreammaker_RczR8eTGhp

# Changelog

:cl:  ynot01, cuackles
rscadd: Added ways to harvest engines
rscdel: Removed the ability to dust other players with supermatter tongs
tweak: Bags of holding now need to be activated with fragments from a station engine
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
hmmmmmm idk man
seems kinda
snowflakey

just make it take anomaly cores

**Comment by Cartlord** [comment]
I think it's bizarre to make it require standing within three tiles of the fuck-you-up instagib engines, because that effectively means you need to maintain a tiny engine setup that doesn't do anything but provide fragments - and then you, seemingly, have an effectively infinite supply.
You haven't made Bags of Holding harder to get, you've just made it take busywork.

**Comment by ynot01** [comment]
> I think it's bizarre to make it require standing within three tiles of the fuck-you-up instagib engines, because that effectively means you need to maintain a tiny engine setup that doesn't do anything but provide fragments - and then you, seemingly, have an effectively infinite supply. 

Wear magboots and you have no risks. You stand near the edge and when the engine comes near you, it collects fragments.

> You haven't made Bags of Holding harder to get, you've just made it take busywork.

I don't see this as a flaw

**Comment by ynot01** [comment]
> hmmmmmm idk man seems kinda snowflakey
> 
> just make it take anomaly cores

Anomaly cores are RNG based and are also significantly more abusable than this solution (anomaly farms on SM produce insane amounts and have 0 risk once stored)

**Comment by Xoxeyos** [comment]
A horrifying yet delectable idea, could you also make it so science gains research points when one is created, or sold? 
I think making these things benefit the whole station upon creation would help negate some of the possible downsides.

**Comment by ynot01** [comment]
> A horrifying yet delectable idea, could you also make it so science gains research points when one is created, or sold? I think making these things benefit the whole station upon creation would help negate some of the possible downsides.

Science benefits enough from bags of holding existing because they are the sole proprietors. If you want this to benefit the entire station, start with other departments.

**Comment by Maia-J** [comment]
> Anomaly cores are RNG based and are also significantly more abusable than this solution (anomaly farms on SM produce insane amounts and have 0 risk once stored)

A reasonable way of thinking in a PR? No way.

**Comment by Sniblet** [comment]
>If you want this to benefit the entire station, start with other departments.

I am going to fertilize my banana tree with supermatter

**Comment by Xoxeyos** [comment]
> A horrifying yet delectable idea, could you also make it so science gains research points when one is created, or sold? I think making these things benefit the whole station upon creation would help negate some of the possible downsides.

... but the reason I suggested a science point increase on creation of BoH is because I would think they would generally be created in engineering, since the engine would be a usual source.

**Comment by JamieD1** [comment]
Not sure if meme

**Comment by ynot01** [comment]
world's highest effort meme if so

**Comment by JamieD1** [comment]
Appreciate the time and effort you put into this but noone will ever do this. Im sorry

**Comment by cuackles** [comment]
> Appreciate the time and effort you put into this but noone will ever do this. Im sorry

To be honest this is a lot better than the one where u need a blue space anomaly and that  one got merged

**Pull request closed without merging**
