### PR TITLE
Makes it so Friday the 13ths get spoopy halloween mode too (Thx Bibby)

### PR DESCRIPTION
**Pull request by Hislyna**
Im so fucking this up but eyo should work keke

Uhh now I gotta do this properly

Bibby made it so that Friday the 13ths get spoopy halloween mode too. 

Why it good for game?

Cause it gives people a reason to login and have more fun, thus higher player count!

Changelog

🆑 Bibby, Not Hisakaki Cause They Suck At This And Bibby Did All The Work
tweak: Halloween Event Now Works On Friday The 13ths Too!
/🆑

### CODE REVIEW

**Comment by Hislyna** [comment]
Could keep it for the month as its a rare month but eyo idc

**Comment by Hislyna** [comment]
mfw an actual coder makes it decent instead of my shitwork

**Comment by Hislyna** [comment]
Okay made it more presentable...

**Review by Moltijoe — APPROVED** [review]

**Comment by Yarinoi** [comment]
you merged this the day AFTER???

**Comment by Hislyna** [comment]
> you merged this the day AFTER???

It was TMed

**Pull request merged**
