### PR TITLE
Updated Crafting Menu

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Partial port of tgstation/tgstation/pull/71779.

Crafting menu is updated, split into two tabs, and now includes:
- Search Bar
- Sprites for Results, Materials/Ingredients, Required Tools, Etc.
- Sorting by Food Type and Material/Ingredient.

Various item recipes, particularly weapons, have been moved around to fit any new categories.
Crafted items are placed into your hands if possible.
Crafting recipes for bait wasn't been loaded. Now they do.
Makeshift pickaxe now has a sprite (uses minipick now).
Moth roach sprite now works.
Removes 'chem_catalysts' for recipes since no recipes uses it.

(This does not port any recipes.)

Craft:
image

Craft - Compact:
image

Craft - Material:
image

Cook:
image

Cook - Compact:
image

Cook - Food Types:
image

Cook - Ingredient:
image

# Spriting
Preview Sprites for 3 bolas (bola, gonbola, watcher)
image
image
image

Moth roach animal hide:
image

# Wiki Documentation
If there are any mentions of crafting (the old menu), update it to this (the new menu).

# Changelog
:cl:  
rscadd: Crafting menu has been updated to now have a search bar, sprites, sorting, and more.
tweak: Crafting menu has been split into two section: Craft and Cook.
tweak: All food recipes have been moved to the "Cook" section from the "Craft" section.
tweak: Various item recipes have been moved around to suit their category.
tweak: Crafted items will be put in your hands if possible.
bugfix: Bait recipes properly appear in the crafting menu.
bugfix: Improvised pickaxe uses the minipick sprite (instead of no sprite).
bugfix: Moth roach animal hide's sprite now properly works.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
PORT THIS INSTEAD https://github.com/tgstation/tgstation/pull/71779

**Review by cuackles — APPROVED** [review]

**Comment by azzzertyy** [comment]
> PORT THIS INSTEAD [tgstation/tgstation#71779](https://github.com/tgstation/tgstation/pull/71779)

this comes after this pr molti, this pr is a dependency of that pr

**Comment by Runian** [comment]
Nah, I'll do it in one go (maybe).

**Comment by Moltijoe** [comment]
Hol up, it was a joke, i was just parroting what you said in dev public

**Comment by Runian** [comment]
> Hol up, it was a joke, i was just parroting what you said in dev public

hate you

**Comment by Moltijoe** [comment]
> hate you

Well, now that youve started...

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
