### PR TITLE
Ports felinids with the family heirloom quirk can now roll toy mice as their family heirlooms 

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
ports https://github.com/tgstation/tgstation/pull/56790/files
# Wiki Documentation

# Changelog

:cl:  ATHATH
rscadd: Added new things   
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
Don't forget to credit author in changelog

**Comment by cuackles** [comment]
> Don't forget to credit author in changelog

i forgot i will do now

**Comment by cuackles** [comment]
original pr made by @ATH1909

**Comment by adamsong** [comment]
Put that after the :cl: so it shows up in the changelog

**Review by adamsong — APPROVED** [review]
Code looks fine

**Pull request merged**
