### PR TITLE
[NOT READY] Removes feature bloat incurred by the clothing-tide.

### PR DESCRIPTION
**Pull request by nesisknesis**
not ready, some things will be scuffed atm

any items you personally like please say and I will tell you whether it was removed or not. I'm putting my foot down when it comes to things that don't belong, however. IE. WW2 clothing items on a 2550 space station.

Removes most of the poorly sprited / out of place clothing added by #4893.

This includes all the WW2 clothing; the casual clothing as they were a worse version of the regular jumpsuits; a majority of the detective clothing due to being an absolute mess of a sprite; the robotics jackets due to being out of place and broken; most clothing that did not fit the department colour theme; the white captain suit, super-white clothes don't look good; the nam armors, redcoat uniforms, the war set. 

I will be respriting the nam armor as I like the concept of it, a space marine set will be added in a future PR. 

items in the lockers have also been modularised.

#### Changelog

:cl:  Identification
rscdel: The poorly sprited and out of place clothing added by an earlier PR have been removed.  
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
autodrobe and clothes mate will probably be left due to them being more out of the way

**Comment by Altoids1** [comment]
-4

Total: -4

**Comment by Rayisken** [comment]
Create an Admin costume vendor for the ones not being used and leave it at Central Command.

**Comment by Bibby0110** [comment]
new /obj/item/poster/firstsingularity(src)
no

**Pull request closed without merging**
