### PR TITLE
FUCK

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:
bugfix: This never happened
/:cl:

### CODE REVIEW

**Comment by Codeatmos** [comment]
FUCK

**Comment by SomeguyManperson** [comment]
travis isn't getting something but the code looks fine aaaaaaa

**Comment by oklews** [comment]
bruh moment

**Review by alexkar598 — APPROVED** [review]

**Comment by alexkar598** [comment]
You are using an outdated master branch that's why Travis doesn't work

**Comment by SomeguyManperson** [comment]
gonna fix the whole things not working thing

**Pull request closed without merging**
