### PR TITLE
Psyc Office Changes

### PR DESCRIPTION
**Pull request by Readystorm546**
I move the psyc office to a new area.

Why did I do this... Well psyc sees little to no action and I though it might be best if it was in a more open are so that more people could have access to it.  It is located where the old gift shop used to be. 

image

In medical where the old psyc office used to be there is now another medical storage closet. This stores rolling beds. Wheelchairs and IV Drips.

image

:cl:  
rscadd: Added more wheelchairs and rolling beds and iv drips in the new storage closet.
rscadd: Moved Psyc office to where old gift shop used to be. Psyc office is now bigger
rscdel: Removed the rolling beds, wheelchairs, and iv drips that were in the hallways of medical. 
rscdel: Removed old shop maintenance area
/:cl:

### CODE REVIEW

**Comment by NCRLouTenant** [comment]
Putting the psych office by arrivals is a little odd,  given that no other job that I know of has their location on that side of the main hall airlock.

Also, speaking as sometimes psych player, we don't need THAT big of an office.

Just personal opinions though, would love to see others thoughts on this.

Edit:misunderstood placement of the office changed comment to remove that point.

**Comment by Readystorm546** [comment]
> Putting the psych office by arrivals is a little odd, given that no other job that I know of has their location on that side of the main hall airlock.

This is correct. There is no job on the left side of the map really unless you include cargo. Not sure who or why we all decided that one side of the map should have everything and the other side of the map should have nothing.

> Also, speaking as sometimes psych player, we don't need THAT big of an office.

Sure you don't NEED that big of an office but Its replacing a random maintenance room that had no use otherwise. While also giving medical more storage room. 

Just some of my thoughts

**Comment by kooarbiter** [comment]
I love vacant commisary, and use it often for assistant gimmicks, if the psych office is moved here I suggest we move vacant commissary to somewhere near science

**Comment by Readystorm546** [comment]
> I love vacant commisary, and use it often for assistant gimmicks, if the psych office is moved here I suggest we move vacant commissary to somewhere near science

The Vacant commissary is still available.

**Comment by MegaEmpirical** [comment]
Here is the previous attempt at this if anyone wants to see our previous commentary:
https://github.com/yogstation13/Yogstation/pull/11149

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Psych Should be in medbay. Make it work.

**Comment by MegaEmpirical** [comment]
> Psych Should be in medbay. Make it work.

Why? Moving it out of medbay is the whole point of this change. I touch on those reasons in my comments in the last PR.

**Comment by NCRLouTenant** [comment]
I will say that part of the RP for Psych is that you have to seek out your patients too, and the office being behind department doors and tucked away makes it a lot less likely someone is going to barge in on a session you are having.

I'm all for expanding the office on Box, but I just don't think moving it is a good plan. Also I'm slightly concerned about the proposed location making the psych the first target for greytiders since they have a stash of drugs.

**Comment by Readystorm546** [comment]
> Psych Should be in medbay. Make it work.

This goes against the intent of the pull request. IF you can explain to me why psych should be in medbay ill hear you out. However just telling me to "make it work" is not a good argument.

**Comment by MegaEmpirical** [comment]
> I will say that part of the RP for Psych is that you have to seek out your patients too, and the office being behind department doors and tucked away makes it a lot less likely someone is going to barge in on a session you are having.

Moving the office doesn't impede seeking patients out; however, it does make getting them to you or letting them come to you easier.

Greytiders don't normally try to steal drugs, they're more about insulated gloves and getting into a locked locker is not particularly easy for greytiders.

**Review by JamieD1 — APPROVED** [review]
Fuck it, you are right.

**Comment by JamieD1** [comment]
@Readystorm546 Fix conflicts and ill merge it

**Comment by MegaEmpirical** [comment]
Moved to:
https://github.com/yogstation13/Yogstation/pull/13755

**Pull request closed without merging**
