### PR TITLE
minor icebox improvements

### PR DESCRIPTION
**Pull request by athena413**
### Intent of your Pull Request

replaces the podbay with public EVA and improves the mining dock and ladder a bit
a bit janky but shrug
image
image

does not fix icebox hating life

#### Changelog

:cl:  
tweak: icebox
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
Pod bay: 
1. This looks really bad, please just keep it as it was.
chrome_d1nDN60Nf4
2. Set the gps tracking variable to 0 
3. 4 boots 4 coats, 0 internals
4. The pod bay doors don't allow atv's to pass even when open, either edit some code, or change it to blast doors and add tinyfans, 
5. these firelocks past the pod doors do nothing, remove them aswell.
chrome_2vgCrWMqaD

6. The decals below the atv's on what you did are all wrong, one is under the table, one atv doesnt have a decal, other one overlaps with a warning stripe, maybe try this? Make sure to fill the leftover space with something, maybe the missing internals locker/shelf
chrome_VglU9x5FJ3
 7. Suggestion: 
chrome_b1fmyYKtbE
8. I know it's not your fault and the areas were all messed up before but can you fix them since you're already at it, just make the room a rectangle 
chrome_U6H3vZd6gj
9. The sign on the outside says: "Keep clear, docking area"

Mining part of the review in a bit

**Review by patpol4 — CHANGES_REQUESTED** [review]
Mining
1. :thinking: chrome_TefTXNMghF
2. Put one of the ores in the box, 3 is too cluttered, if you want a dirty look use the dirt/dust decal

**Comment by athena413** [comment]
image
image

**Review by patpol4 — APPROVED** [review]
I just added 2 more masks so there are equal sets

**Pull request merged**
