### PR TITLE
Makes soul vessels obtainable and adds anima fragments

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Adds a scripture to clockcult, that allows to summon a soul vessel.

Also adds anima fragment mob, a something like a shade, but for clockcult. It can be made by using inhand a soul vessel and waiting for 5 seconds after it. Drops an empty soul vessel on death.

Also clockwork maradeurs now have a slash attack animation because they use a sword.

# Spriting
No

# Wiki Documentation

I think I wrote enough in the document changes section.

# Changelog

:cl: SuperSlayer
rscadd: Added a scripture to clockcult that allows to summon a soul vessel
rscadd: Anima fragment clockwork mob that can be summonned by using a soul vessel inhand
tweak: Clockwork maradeurs now have an attack animation
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
might be more interesting to convert them into special power for revival or creating constructs

**Comment by ghost** [comment]
> might be more interesting to convert them into special power for revival or creating constructs

Good idea

**Comment by Cartlord** [comment]
why would you want to make clockies more like bloodies

**Comment by ghost** [comment]
> why would you want to make clockies more like bloodies

I want to make mindshielded people to be able to have fun during clockcult rounds

**Comment by ghost** [comment]
Removed the sacrifice part, now soul vessel is obtainable by a scripture

**Comment by Cartlord** [comment]
dude i'm gon'a be real, i get mindshielded for the express purpose of _not_ having to do cult shit

**Comment by ghost** [comment]
Lol

**Pull request closed without merging**
