### PR TITLE
Borg hypospray bugfix

### PR DESCRIPTION
**Pull request by Moltijoe**
:cl:  
bugfix: fixes a "bug" with borg hypospray recharge time being 10x what it was supposed to be
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
er. The bug was that it was too slow to recharge. Should be 5u per 10s but it was taking far longer

**Comment by Moltijoe** [comment]
> er. The bug was that it was too slow to recharge. Should be 5u per 10s but it was taking far longer

correct, this fixes the bug that made it take 10x the time
so instead of 10x the time, it takes 2x the time

**Comment by Hislyna** [comment]
Bugs are bugs and don't need balance council, should make a new pr after thisun to edit it properly like the precedent before with pacifism

**Comment by Moltijoe** [comment]
> Bugs are bugs and don't need balance council, should make a new pr after thisun to edit it properly like the precedent before with pacifism

bruh, literally making more work for me, fine

**Comment by Hislyna** [comment]
> > Bugs are bugs and don't need balance council, should make a new pr after thisun to edit it properly like the precedent before with pacifism
> 
> bruh, literally making more work for me, fine

Sowwy, just precedents

**Comment by Moltijoe** [comment]
> Sowwy, just precedents

no, no, i get it, which is why i changed the PR

**Review by MajManatee — APPROVED** [review]
I think that's how delta time works

**Pull request merged**
