### PR TITLE
We have forgotten our towel

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Adds a towel, can be a family heirloom.

- [ ] Replace codersprite
- [ ] Make it do something, possibly

# Changelog
:cl:  
rscadd: Added towel
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
yikes

**Comment by Marmio64** [comment]
maybe let it instantly remove the text that says you're wet after you take a shower if you want to give it some kind of purpose
and make it craftable with cloth

**Comment by Mqiib** [comment]
>Adds ability to be hoopy frood

**Comment by Moggram** [comment]
It also could be used for drying off floors.

**Comment by JamieD1** [comment]
> It also could be used for drying off floors.

HAH

**Comment by JamieD1** [comment]
Remake it when you find a use.

**Pull request closed without merging**
