### PR TITLE
[admin] mark an issue as mentorhelp for fun and profit

### PR DESCRIPTION
**Pull request by monster860**

### CODE REVIEW

**Comment by Bibby0110** [comment]
cant you like make it give them a button in the response text or just send it to mentorhelp straigt away idk

**Comment by Altoids1** [comment]
Can we, instead, have it so that the admin can redirect the ticketer to a mentorhelp?

Also, while we're doing this, can we make it so that an admin can ascend a mentorhelp into being a ticket, when it turns out their question was an admin-required issue?

**Comment by monster860** [comment]
no I'm too lazy

**Comment by Bibby0110** [comment]
gulag

**Pull request merged**
