### PR TITLE
Captain McShiface boops Greytide McShitter on the head!

### PR DESCRIPTION
**Pull request by alexkar598**
# Github documenting your Pull Request

Captain McShiface boops Greytide McShitter on the head!

# Wiki Documentation

N/A

# Changelog
:cl:  
rscadd: You can boop people by targetting their head on help intent
/:cl:

### CODE REVIEW

**Comment by Bluedazzled** [comment]
well this is better than tg's "fuckface pats fuckface2 on the head"

**Comment by RetroJunki3** [comment]
no




please

**Comment by Bluedazzled** [comment]
> well this is better than tg's "fuckface pats fuckface2 on the head"

i appear to be mistaken now that i give it a second thought

**Comment by nesisknesis** [comment]
There's no need. adds nothing. It's just weird

**Comment by alexkar598** [comment]
This PR is objectively non controversial, everyone is on the same side here

**Comment by ToasterBiome** [comment]
https://forums.yogstation.net/help/rules/#rule-0_2

**Comment by alexkar598** [comment]
Its not erotic

**Comment by maxion12345** [comment]
> 
> 
> Its not erotic

booping implies a snoot, we're all humans here.

also this is pretty suspiciously furry. I'll need you complete this quick test:

https://www.quizony.com/am-i-a-furry/index.html

**Comment by SomeguyManperson** [comment]
no

**Pull request closed without merging**
