### PR TITLE
[PORT] Item hover outline FX

### PR DESCRIPTION
**Pull request by warface1234455**
# About PR
Ports: ~~I know this is orginal from bee but i cant find the original pr sooo~~

- https://github.com/tgstation/tgstation/pull/57574
- https://github.com/tgstation/tgstation/pull/57659

# Document the changes in your pull request

Adds feedback when you hover over stuff.
<details><summary>images</summary>

image

image

image

image

image

image

image

</details>

# Wiki Documentation

Adds feedback when you hover over stuff.

# Changelog

:cl:  [maxymax13](https://github.com/maxymax13) ported by warface1234455
imageadd: Items in your inventory now have an outline when you hover over them, originally from BeeStation. This can be disabled in Game Preferences.
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
The blue UI outline is too light
image

**Comment by warface1234455** [comment]
> The blue UI outline is too light image

Lemme adjust

**Comment by ToasterBiome** [comment]
Honestly the only way this effect won’t look super laggy is that if it was entirely clientside

the hovers are weird because you basically have to tell the server that you’re hovering over it and then the server has to send back to put an outline on it

maybe a TM in order

**Comment by warface1234455** [comment]
> Honestly the only way this effect won’t look super laggy is that if it was entirely clientside
> 
> the hovers are weird because you basically have to tell the server that you’re hovering over it and then the server has to send back to put an outline on it
> 
> maybe a TM in order

we can testmerge to give it a shot

**Comment by KillerOrcaCora** [comment]
Turn this shift off wtf are yall doing clowns

**Comment by KillerOrcaCora** [comment]
We already have grey outlines for items guys we don't need a extra outline for every damn sprite you can hover your cursor across

**Comment by VaelophisNyx** [comment]
apparently it *might* be causing some client-side performance issues to *some* users (I personally experienced none, but Orca says he did?)

**Comment by warface1234455** [comment]
> apparently it _might_ be causing some client-side performance issues to _some_ users (I personally experienced none, but Orca says he did?)

i think orca just being mad cuz i killed him very fast into shift

**Comment by ShoziOffical** [comment]
ok ill figure this still dont know how people saying this causing performance issues, most of codes are from bee

**Comment by ShoziOffical** [comment]
okay probally yogstation players cant handle this so i guess imma close this had good run

**Pull request closed without merging**
