### PR TITLE
removes budget card, they suck and we should have removed them in the first place

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

departmental budgets are for paying your staff, not buying weird crates

# Wiki Documentation

# Changelog

:cl:  
rscdel: You can no longer steal security pension fund
/:cl:

### CODE REVIEW

**Comment by TheBombMakerJL** [comment]
Bad

Security needs easy access to equipment on gangs/revs/cult

If they don’t get it, two things will arise

1.) They will lose quickly 
2.) They will execute a LOT more people because of lack of proper equipment

People are talking about *buffing* security so we should nerf them instead yes

**Comment by Bibby0110** [comment]
> Bad
> 
> Security needs easy access to equipment on gangs/revs/cult
> 
> If they don’t get it, two things will arise
> 
> 1.) They will lose quickly 2.) They will execute a LOT more people because of lack of proper equipment
> 
> People are talking about _buffing_ security so we should nerf them instead yes

I don't care. Cargo should do their job if your whole strategy falls apart as a result of not being given 9-10k credits for free

**Comment by ghost** [comment]
> Bad
> 
> Security needs easy access to equipment on gangs/revs/cult
> 
> If they don’t get it, two things will arise
> 
> 1.) They will lose quickly 2.) They will execute a LOT more people because of lack of proper equipment
> 
> People are talking about _buffing_ security so we should nerf them instead yes

Why, in the name of god, security needs to be buffed? It just recently got a funny batton buff that alredy makes security unstopable, so for what reason do we need securjty buffs?

**Comment by ynot01** [comment]
maybe we can actually start balancing money now ;00

**Comment by ghost** [comment]
Make money not useless pleaze 🥺🥺🥺🥺

**Comment by TheBombMakerJL** [comment]
>highpop
>gangs
>cargo’s ineffectual, spent all their money on random crates and now we’re broke
>no implants
>security decides to execute 20 gang members because of no implants

The alternative is either executing 20 gang members or waiting until the gangs get so equipped that they can easily take down security 

Or you could just let security have their budget to order crates

**Comment by Bibby0110** [comment]
> > highpop
> > gangs
> > cargo’s ineffectual, spent all their money on random crates and now we’re broke
> > no implants
> > security decides to execute 20 gang members because of no implants
> 
> The alternative is either executing 20 gang members or waiting until the gangs get so equipped that they can easily take down security
> 
> Or you could just let security have their budget to order crates

The budget card, at max, only makes a difference of 6 mindshields. I'm sure our smart security players can figure out a way to get around that

**Comment by ghost** [comment]
> > highpop
> > gangs
> > cargo’s ineffectual, spent all their money on random crates and now we’re broke
> > no implants
> > security decides to execute 20 gang members because of no implants
> 
> The alternative is either executing 20 gang members or waiting until the gangs get so equipped that they can easily take down security
> 
> Or you could just let security have their budget to order crates

Ski issue. Just execute the incompetent QM and no problems. Also loosing as a crewmember is less painfull then loosing as an antagonist, that you get, like, VERY rare.

**Comment by ghost** [comment]
Also most of the rounds aren't gangs, revs, or other fun to play antagonists, and mostly they are some suffering simulators like traitors, bloodbrothers, lings, who get easily fucked by a roundstart stunbatton that every security officer has.

**Comment by TheBombMakerJL** [comment]
I’m glad knowing that mass executions were an intended feature and not just a side effect of this. I’m personally fine with executing however many people the situation needs, I’m glad we can all agree that this is what’s going to happen

**Comment by Xantam-13** [comment]
I have no idea why this is necessary, I feel that BombMaker brings up legit arguments against this and will cause a lot more players to sit rounds out and leave.

**Comment by Marmio64** [comment]
If you remove the budget at least give security an extra mindshield box or two at the start, or make them cheaper.

**Comment by Bibby0110** [comment]
> If you remove the budget at least give security an extra mindshield box or two at the start, or make them cheaper.

Mindshields have had the same price for the last 7 years, where a majority of those were without budget cards. I don't see why security suddenly needs additional assistance.

**Comment by Xantam-13** [comment]
> > If you remove the budget at least give security an extra mindshield box or two at the start, or make them cheaper.
> 
> Mindshields have had the same price for the last 7 years, where a majority of those were without budget cards. I don't see why security suddenly needs additional assistance.

Because in those  7 years, almost every useful tool security had has either been nerfed or removed...

**Comment by Bibby0110** [comment]
> > > If you remove the budget at least give security an extra mindshield box or two at the start, or make them cheaper.
> > 
> > 
> > Mindshields have had the same price for the last 7 years, where a majority of those were without budget cards. I don't see why security suddenly needs additional assistance.
> 
> Because in those 7 years, almost every useful tool security had has either been nerfed or removed...

Maybe the council shouldn’t have done that then? 

The tools that have been nerfed are primarily weapons, weapons that would allow you to use mindshields in the first place. The fact that you’re complaining specifically about mindshields show that they haven’t exactly been nerfed into the ground

**Comment by ghost** [comment]
Even with "removed usefull tools" security is still too strong to be fun playing against as most antagonists that exist.

**Comment by maxion12345** [comment]
skill issue

also how else do I get the money out from harmbatoning clown

**Comment by ghost** [comment]
> skill issue
> 
> also how else do I get the money out from harmbatoning clown

As social credits

**Comment by athena413** [comment]
adam pr

**Review by SomeguyManperson — APPROVED** [review]
We can just revert it if it is too disruptive

**Review by ToasterBiome — APPROVED** [review]
i wonder if this will break the maps

also does gax not have them?

**Comment by Georgeur** [comment]
problem mainly is that its too easy to empty the cargo budget or just siphon all the money. 
guess you could put the cargo budget in armory and remove the armory one, but that'd be fucky for obvious reasons.
that or we remove the armory budget and add some extra guns or mindshields or some shite.

**Comment by N3D6** [comment]
This change sucked and everytime you've tried to do this in the past it has sucked aswell, leave budget cards alone, they're fine

**Comment by Bibby0110** [comment]
> This change sucked and everytime you've tried to do this in the past it has sucked aswell, leave budget cards alone, they're fine

they’re not. There’s a reason TG removed them too. If we had any semblance of economy balance then maybe they could stay.

**Comment by Bibby0110** [comment]
> i wonder if this will break the maps
> 
> also does gax not have them?

gax doesn’t have them

**Comment by Bibby0110** [comment]
> > This change sucked and everytime you've tried to do this in the past it has sucked aswell, leave budget cards alone, they're fine
> 
> they’re not



> problem mainly is that its too easy to empty the cargo budget or just siphon all the money.
> guess you could put the cargo budget in armory and remove the armory one, but that'd be fucky for obvious reasons.
> that or we remove the armory budget and add some extra guns or mindshields or some shite.

You still need to get the security budget into the cargo budget to use it, unless you privately order which is more expensive I guess

**Comment by JamieD1** [comment]
We already nerfed the shit out of it bibby, im not removing it unless you have a damn good reason

**Pull request closed without merging**
