### PR TITLE
Capture the flag teams have armour inspired by Halo 2/3

### PR DESCRIPTION
**Pull request by nesisknesis**
Replaces Capture the Flag outfits with new ones

image
image

They don't have item sprites to decrease time spent and as they don't require them anyway due to being no-drop.

# Changelog

:cl:  Identification
imageadd: Capture the Flag outfits have been replaced with new outfits inspired by Halo 2/3 multiplayer characters.
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
This makes me want to add a energy sword powerup that is halo themed (if i could sprite)

**Comment by UselessTheremin** [comment]
john halo

**Comment by Reed0506** [comment]
ok thats it turn the deagle they get into halo 1 pistol

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
@grimm-hollowknight Cornflakes.

**Comment by Firewolf34** [comment]
This is so awesome I want to cry

**Pull request merged**
