### PR TITLE
Eclipse updates 1

### PR DESCRIPTION
**Pull request by Ktlwjec1**
Arrivals - Remove 2 potted plants as they were over firelocks.
Art storage - Moved vent+scrubber from under tables. Added canvases.
Aux storage - Moved some items around so it feels less empty, added a water tank, made sure it has items boxstation has (multitool, extra metal etc)
Primary tool storage - Another fire alarm and firelocks.
Chapel - Flipped mass driver windoor around. Added flowers and chairs to the tables by the windows. Changed to wooden tables. Made confession booth flooring be symmetrical. Added altar of gods. Changed area to be /area/chapel/main so it's not named "Space". Renamed airlock "Coffin Storage". A bit of plating in the cremator room. Shutters on the cremator room windows. Another morgue tray. Tiny fan under chapel blast door. Purple carpet. A light in the north confession booth. Adds burial garments.
Gift shop - Moved chair and spawn 1 tile right. Adds a shutter button.
Holodeck - Computer frame on the abandoned side.
Cafe - Fixed floating intercom.
Library - Book inventory management console added. Moved air alarm. Changed flooring in the back room to be the same as boxstation's. Added a missing chair. Fixes the uneven garden top-right.
CMO office - Moved the airlock 1 tile south. Fixed APC name. Fixed surgery areas.
Cargo - Disposals outside cargo for public use.
Solars - Fixed runtime caused by an APC.

:cl:  Ktlwjec
rscadd: Updates for Eclipse, most notably the chapel.
/:cl:

### CODE REVIEW

**Review by patpol4 — APPROVED** [review]
nice

**Comment by patpol4** [comment]
just fix the conflict and its gucci

**Comment by Moja10** [comment]
All PRs above must be documented!

**Comment by Ktlwjec1** [comment]
I'll just reopen this or w/e when I get time to fix it otherwise it'll be open for days.

**Pull request closed without merging**
