### PR TITLE
airlock painter uses a radial

### PR DESCRIPTION
**Pull request by Amelia0010**
contains https://github.com/tgstation/tgstation/pull/40318, so you can just not merge that when it gets mirrored

### CODE REVIEW

**Comment by Amelia0010** [comment]
wrong button

**Comment by Amelia0010** [comment]
https://gfycat.com/WideThreadbareHornshark @ThatLing there, now image

**Comment by AsV9** [comment]
technically not an image though

**Comment by AsV9** [comment]
man you sure like your radials

**Comment by Amelia0010** [comment]
I do, yes

**Pull request merged**
