### PR TITLE
AI core update (new look!)

### PR DESCRIPTION
**Pull request by Ktlwjec1**
PRing this for war.

Old version:
aicore_old

New version **Updated 17th**:
new

Adds:
ai-malicious

:cl:  war0100
imageadd: Changes the way the AI looks.
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Ngl I don't really like this sprite. The old one is very bad and should be replaced, but here are my issues with the new one:

-First off, it's pillow shaded. This is a very common pitfall and really doesn't help the sprite look good. It looks like it's lit from the front whereas it really should be lit from the top. The gradients are not pleasing to look at.

-The blue color looks like plastic. There's no hueshifting at all so the entire thing is just the same shades of blue. Additionally, the default AI is also blue, so you have blue on blue going on. Also the AI core has blue floors so... it's just all blue.
image


-You didn't change the construction states, which are also pretty bad. Not really your fault but I'd like to see a design that updates those too.
image

-The rounded corners give it a very cartoony shape that doesn't mesh well with the walls it's always going to be next to.

If you want some help to make it better (or with the spritesheet work, it's a huge file and I realize a lot of effort must have gone into this regardless) let me know, I'd be happy to advise.

**Comment by ghost** [comment]
If you're gonna use goon's AI sprite you might as well use the whole thing

**Comment by Xoxeyos** [comment]
I think it conflicts with the current art style, if you're going to change the art style, change it all, or don't change it at all.

**Comment by ClassyName** [comment]
> I think it conflicts with the current art style, if you're going to change the art style, change it all, or don't change it at all.

all the AI cores have been changed with this pr... (currently redoing them all AGAIN but in grey.)

**Comment by Hopekz** [comment]
> I think it conflicts with the current art style, if you're going to change the art style, change it all, or don't change it at all.

Mane how the hell are spriters expected to change the whole art style in 1 PR.
If people were expected to do a rebase every PR nothing would get done since it is volunteer coding/spriting.

**Comment by Xoxeyos** [comment]
> 
> 
> I think it conflicts with the current art style, if you're going to change the art style, change it all, or don't change it at all.

Alright, I've reread what I've said, and I think it's stupid too.

**Review by JamieD1 — APPROVED** [review]

**Review by fluffe9911 — APPROVED** [review]
Parth approved it

**Pull request merged**
