### PR TITLE
Ports multi-z disposals/power/pipes from BeeStation

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Ports https://github.com/BeeStation/BeeStation-Hornet/pull/422

Admin only or map spawn

Porting for uhhh no reason yep no reason

# Wiki Documentation

# Changelog

:cl:  
rscadd: Ports multi-z disposals/power/pipes from BeeStation 
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
nice

**Comment by Moltijoe** [comment]
deep maints gax confirmed?

**Comment by patpol4** [comment]
now we just need working multiz

**Comment by JamieD1** [comment]
> # Document the changes in your pull request
> Ports [BeeStation/BeeStation-Hornet#422](https://github.com/BeeStation/BeeStation-Hornet/pull/422)
> 
> Admin only or map spawn
> 
> Porting for uhhh no reason yep no reason
> 
> # Wiki Documentation
> # Changelog
> 🆑 rscadd: Ports multi-z disposals/power/pipes from BeeStation /🆑

Why dont you port the ones monster made

**Comment by ToasterBiome** [comment]
> > # Document the changes in your pull request
> > Ports [BeeStation/BeeStation-Hornet#422](https://github.com/BeeStation/BeeStation-Hornet/pull/422)
> > Admin only or map spawn
> > Porting for uhhh no reason yep no reason
> > # Wiki Documentation
> > # Changelog
> > 🆑 rscadd: Ports multi-z disposals/power/pipes from BeeStation /🆑
> 
> Why dont you port the ones monster made

I’m pretty sure monster ported them from tg

**Pull request closed without merging**
