### PR TITLE
Makes lobby music use youtube-dl and goonchat

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
This lets us add any song that is supported by youtube-dl as lobby music. This way we can add trillions of songs, while reducing the resource download size.

The sample config includes all songs from #3194 which weren't unavailable on youtube.

Currently trying to figure out why the volume won't change. Hopefully didn't forget any files

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
yeah, no

**Comment by ThatLing** [comment]
nice branch

**Comment by Moja10** [comment]
Why was this closed?

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
have you not noticed the 219 changed files

**Pull request closed without merging**
