### PR TITLE
felenids now take damage from coco powder and hot chocolate

### PR DESCRIPTION
**Pull request by boodaliboo**
cats and dogs are both mammals so this makes sense
#### Changelog

:cl:  
rscadd: Added toxin damage when cat people consume hot coco and coco powder
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
will fix later just need to add a toxpwr to the base chem-

**Comment by Mqiib** [comment]
Just swap it from M.adjust to H.adjust. also good pr improves immersion,

**Comment by Moja10** [comment]
My God, is this the MediumRP PR we have been desperately needing the entire time?

**Comment by boodaliboo** [comment]
> My God, is this the MediumRP PR we have been desperately needing the entire time?

yes

**Comment by jcatjmeow** [comment]
Make it so dogpeople die when they drink coffee

**Review by monster860 — CHANGES_REQUESTED** [review]
this is shitcode, do `istype(chem, whatever)` not `H.reagents.has_reagent(whatever)` like every other handle_chemicals proc.

The reason is this check runs for every reagent in the system. With your shitcode, if there are 10 different kinds of reagents in someone and one of them is hot coco/coco powder, then they'll take 10 Toxin damage per tick, which is really really OP and was not intended that way.

**Comment by boodaliboo** [comment]
> this is shitcode, do `istype(chem, whatever)` not `H.reagents.has_reagent(whatever)` like every other handle_chemicals proc.
> 
> The reason is this check runs for every reagent in the system. With your shitcode, if there are 10 different kinds of reagents in someone and one of them is hot coco/coco powder, then they'll take 10 Toxin damage per tick, which is really really OP and was not intended that way.

i copied alexkars code i also have no clue what your asking

**Pull request closed without merging**
