### PR TITLE
Cyborgs now have an "eject hat" button in their Robot Commands that will drop their hat

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

# Changelog

:cl:  
rscadd: cyborgs now get an "eject hat" button that will take off their hat and drop it
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
I did say that

**Comment by ToasterBiome** [comment]
@JamieD1

**Comment by nmajask** [comment]
Have you tested this?

**Comment by ToasterBiome** [comment]
> Have you tested this?

yes

**Review by adamsong — APPROVED** [review]

**Pull request merged**
