### PR TITLE
Replaces old axolotl sound with a better cute sound

### PR DESCRIPTION
**Pull request by warface1234455**
Replaces axolotl sound with a better one.
Old 

https://user-images.githubusercontent.com/89688125/194853721-3e0f5468-7449-4790-b9dc-b5f440b69770.mp4

New

https://user-images.githubusercontent.com/89688125/194853787-b88b696d-97bb-48eb-94bb-7f3f1e1599b1.mp4

# Document the changes in your pull request

Replaces axolotl sound

# Wiki Documentation
Replaces axolotl sound 

# Changelog

:cl:  

soundadd: Replaced old axolotl sound with a better one
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
noooooooooo i love that sound leave it waaaaaaaaaaaa

**Review by TheRyeGuyWhoWillNowDie — CHANGES_REQUESTED** [review]
close this pr the frog sound is funny

**Comment by ShoziOffical** [comment]
> close this pr the frog sound is funny

No

**Comment by ShoziOffical** [comment]
Will try to find a better sound

**Comment by ShoziOffical** [comment]
WHY IS THIS HEADCODERR

**Comment by RG4ORDR** [comment]
Do not fucking touch the MIGO

**Comment by ShoziOffical** [comment]
> Do not fucking touch the MIGO

what

**Comment by CMOisLing** [comment]
Speed merge that shit blew my fucking eardrums out when I first heard it.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
