### PR TITLE
A few atmos device improvements

### PR DESCRIPTION
**Pull request by ThatLing**
# Document the changes in your pull request

Noteable changes:
- The limits for some pump UIs are fixed (e.g. temp pump maximum temperature could be set to 45000K with the ``max`` button, even though the slider maxed at 4500K)
- Temperature pump functionality is overhauled (see https://github.com/tgstation/tgstation/pull/55926 for details)

List of PRs:
- https://github.com/tgstation/tgstation/pull/53678
- https://github.com/tgstation/tgstation/pull/55926
- https://github.com/tgstation/tgstation/pull/56611

# Wiki Documentation
Temperature pump functionality changed

# Changelog

:cl: LemonInTheDark & Donkie & esainane
bugfix: Atmos pump UI limits are fixed
tweak: Temperature pump now transfer a percent of energy instead of heat directly
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
glory to atmosia

**Comment by iamthesilly** [comment]
while you're at it could you fix the crystallizer slider as well? the slider goes up to 500 moles/sec despite it only actually being able to go up to 250

**Comment by ThatLing** [comment]
You got it homie

**Comment by applepineapplepizza** [comment]
glory to atmosia

**Review by MajManatee — APPROVED** [review]
gas... grrr

**Pull request merged**
