### PR TITLE
[PORT] Baystation Instruments! (but only kinda baystation because I rewrote it nearly from the ground up)

### PR DESCRIPTION
**Pull request by redmoogle**
Port of: https://github.com/tgstation/tgstation/pull/50549

About The Pull Request

Baystruments but almost completely refactored and rewritten by me to work on /tg/code, with a bunch of optimizations done (credit to where it's due from the folks on bay for their implementation + the samples used for the instruments).

All legacy instruments are kept.
DISCLAIMER: This adds around 7MB to the instruments folder. I've compressed the synthesized instrument samples via audacity quality 4 .ogg export, but haven't made it mono-channel as I could notice it sounding quite a bit different afterwards (or maybe I just didn't mix it properly who knows).

the tl;dr is that all instruments are now datums instead of just "folder path + extension", and you have two kinds of instruments.

Legacy instruments - these are just your good old normal instruments. The reason I'm keeping them is because they sound quite a bit different from synthesized instruments. They're 3MB out of the 10MB instruments folder. These just.. act like they always did. No new optimizations, no subsystem decay processing, no sustain, no channel management.

Synthesized instruments - These are the new bay instruments, taking up the remaining 7MB out of the 10MB folder. Theoretically you can make an instrument out of.. basically any sound, as long as it's long enough and doesn't sound too horrible when stacked (noticeable attack + sustain not being too obnoxious, I'm not an audio engineer-type guy but I hope you get the idea). They change pitch using frequency modulation, done automatically when the instrument initializes.

Synthesized instruments store all their keys cached to increase performance during playback. They're initialized during subsystem initialization. They're indexed/accessed via their text ID string. This is so more can be made at runtime (just make a new id = datum entry in the subsystem's list, include 1 or more real_samples by their key, and proc Initialize() and it'll generate the rest. Use meow.ogg or something for extra !!fun!!)

Synthesized instruments support decay, whether it's linear or exponential. A subsystem processes them for decay, but the actual note-playing loop is still sleep() based. To do this they remember which channels they're playing, and change the volume for anyone hearing them until the note is considered "dead" (below the drop threshold), at which point it's stopped from all mobs hearing them. The channel is then kept by the instrument for re-use from its internal channel stack, only asking SSsounds for a channel reservation if that runs out.
Instruments do this by asking SSinstruments to do it for them. This way you don't have a situation where all available channels are saturated by instruments. Furthermore, they can only reserve up to 128 events each. Initially, baystation had .. a similar system, but it was too complicated and probably had too much overhead, so I trashed it for /tg/'s usual subsystem approach to these things.

A ton of functions about new synthesized instruments are user customizable, from sustain to volume to sustain drop threshold. New synthesized instruments use the exact same music format as before, so just copypaste your songs in.

Oh and piano synths lost their change instrument action. It's now completely stored in the interface, and allows you to choose any non admin-only marked (don't ask why I wanted that support) instrument, legacy or synthed.
Why It's Good For The Game

Synthesized instruments support sustain and very fast music, as they more efficiently manage their channels than old instruments (somehow. Old instruments had shorter samples in general, but if you played fast music it just kinda.. broke).
They also just sound different in general. There's a buncha fun and wacky ones like bike horn (whoever said you can't play despacito on bikehorn is going to be eating their words...), chimes, beeps, boops, "ideal tones", etc etc. (although the sine tone still sounds kinda shitty but y'know, until I'm better at screwing with audio stuff I'm not able to do anything about that).

Legacy instruments are kept for the reason that synthesized instruments can't fully replace their sound in this implementation/design, it just sounds different and some things just sound better on classic piano sounds rather than new synth'd pianos.

also PSA, baystation had reverb/environment settings but I removed it from mine because you can make obnoxious instruments even worse by setting the "right" reverb values. Maybe someone can add it in the future but I don't feel like it's going to add much to the system's experience instead of just making earrape music worse.

Tested to atleast work with a synth and compile

Changelog

🆑 silicons
add: Baystation instruments are here!
tweak: Existing instruments have been rolled into the new unified instruments system.
tweak: A sound subsystem has been added, SSsounds. Use it for persistent channel management.
/🆑

### CODE REVIEW

**Comment by jcatjmeow** [comment]
you missed a few pianos specifically the luxury shuttle

**Review by jcatjmeow — CHANGES_REQUESTED** [review]
Line 153 _maps/shuttles/emergency_luxury.dmm

**Comment by Moja10** [comment]
Very impressive PR!

**Review by jcatjmeow — APPROVED** [review]

**Comment by redmoogle** [comment]
there's a 50/50 legacy instruments wont work. I had some unbridled fuckery with them that resolved itself after a bunch of compile and no changes

**Comment by redmoogle** [comment]
Alright fixed what ever the fuck that was

**Comment by redmoogle** [comment]
Alright not fixed, I dont know how to fix this as I cant peg it down

### Edit: Just DD being stupid, should work fine on the main server

**Comment by Moggram** [comment]
Can we get some sound tests?

Also, will this fix the Electric Guitar? (Its not working)

**Comment by redmoogle** [comment]
> 
> 
> Can we get some sound tests?
> 
> Also, will this fix the Electric Guitar? (Its not working)

https://www.youtube.com/watch?v=m3qpuVPD5a0
https://www.youtube.com/watch?v=pxKnUORIfSU

From when I was testing the electric guitar worked

**Comment by Moggram** [comment]
> 
> 
> > Can we get some sound tests?
> > Also, will this fix the Electric Guitar? (Its not working)
> 
> https://www.youtube.com/watch?v=m3qpuVPD5a0
> https://www.youtube.com/watch?v=pxKnUORIfSU
> 
> From when I was testing the electric guitar worked



Just from the two you shown off, now I will use the other instruments besides the guitar and Piano!

**Comment by redmoogle** [comment]
> 
> 
> > > Can we get some sound tests?
> > > Also, will this fix the Electric Guitar? (Its not working)
> > 
> > 
> > https://www.youtube.com/watch?v=m3qpuVPD5a0
> > https://www.youtube.com/watch?v=pxKnUORIfSU
> > From when I was testing the electric guitar worked
> 
> 
> 
> Just from the two you shown off, now I will use the other instruments besides the guitar and Piano!

Theres plenty more i'll make a proper video showing each one with a short song in a while

**Comment by patpol4** [comment]
So what effect will this have on actual items ingame, the old ones remain and there are new ones added? Is this togglable? I see you changed the piano object path name, what about other instruments? Do they need to be replaced on the maps aswell?

**Comment by redmoogle** [comment]
> 
> 
> So what effect will this have on actual items ingame, the old ones remain and there are new ones added? Is this togglable? I see you changed the piano object path name, what about other instruments? Do they need to be replaced on the maps aswell?

The only thing thats effectively changed are the synth/pianos as they use the new system(they can still play old sounds tho)

**Comment by Partheo** [comment]
I don't even know how I could verify all these sounds. I'm going to assume everything is fine since it's just instruments

**Comment by redmoogle** [comment]
> 
> 
> I don't even know how I could verify all these sounds. I'm going to assume everything is fine since it's just instruments

https://youtu.be/Cy-pTFbGhfU

**Review by Partheo — APPROVED** [review]

**Review by patpol4 — APPROVED** [review]
Maps are fine, you just repathed the piano object. Please hold on on merging this until random maint is merged as this touches boxstation.

**Comment by redmoogle** [comment]
> 
> 
> Maps are fine, you just repathed the piano object. Please hold on on merging this until random maint is merged as this touches boxstation.

Done, I think

**Pull request merged**
