### PR TITLE
the meatball man's return (admin only fuck you)

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
the meatball man is funny and he got straight up purged from the code instead of being made admin only which is cringe

# Changelog

:cl:  
rscadd: the meatball man
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
mmmmmmmmmmmmmm good

**Comment by Bibby0110** [comment]
Bloat. Closing in 20 hours

**Comment by MajManatee** [comment]
If this is bloat remove the egg dog and shit like that

**Comment by Bibby0110** [comment]
Bloat.

**Comment by neeshacark** [comment]
not bloat but ok

**Pull request closed without merging**
