### PR TITLE
Removes AI as a job in favor of chatgpt ||AI Rework 4.0

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request
All AI machines now need to wired up using ethernet cables into a network.
A data core will require a locally connected server with at least 1THz and 1TB to be functional.
A network consists of all the locally connected machines.
Two networks can be connected using a networking machine. This allows the AI and Netmin to use the resources and cores in both networks.

## Changes to the AI data core
The AI Core now looks like this with the weird new sprites being networking machines. They point towards the one they're connected to if you want to snoop out where other networks might be
image

## Changes to the Netmin
The Network Admin now lives in Science in the new Computer Science room.
image
Their tool to interact with a network is now either the laptop they spawn with, or a modular computer connected with an ethernet cable.

Accessing the network using such a console allows for (at present) 3 actions. These all work based on the CPU assigned to the local network.
image

In addition to this it allows you to remotely control networking machines in the local network. 
It allows allows the distribution of networking resources to either the connected AIs, or the network itself.

This is also the way you'll be uploading and downloading AIs now.
If you're uploading you need to upload to a network that either has a data core locally, or one connected through a networking machine. Likewise for downloading.

One other minor feature added is a leaderboard program you can download. If connected to a network this will show the persistent five highest CPU and RAM records.

### Networking Machines
If the AI has an unconnected network machine you can force access to it using your own machine. To do this you rotate it using a wrench within 20 degrees of the other machine. Then you use a multitool and select the machine you want to connect to. After this is all done you use a screwdriver to finalize the connection. You can disconnect manually by using a wirecutter, or the UI.

### The Master Subcontroller
A new machine has been added to the RnD server room.
image
If an AI is connected to this machine via a networking machine they will be able to instantly open doors, access APCs and access firealarms. Without it there's a 1 second delay for doing these actions.
If you multitool the master controller you can disable individual departments from working, even if connected to the AI.
At roundstart the security department is DISABLED, and the AI will have a mildly harder time doing stuff in security.

## Synthetics
These creatures are more hardy than humans, have inherent pacifism and can't use any kind of stunweapons. They "bleed" white fluid instead of blood, and they're very white. These are meant for small non-combat related jobs that the station may need.
The plan is to add a roundstart job, where the player will be able to take control of any idle synthetic units around the station. (Approximately 1 per department)
They have all access and access to every radio channel (except security), including binary. Radio and ID are integrated into the droid, so you can't steal it from them.
They have no laws like cyborgs, but are present to assist the station and do no harm. Lore-wise they're cold and calculated machines, even more than borgs.
Job functionality is currently not implemented, but the AI can take control of one of the 2 units present on the station (Bridge and Science) after researching a new project. 
image

### Misc Additions
The new local networks will change and allow a few new things.
1. No more hidden upload/download consoles. You'll need physical access to the AIs network now. (Or one it is connected to)
2. This allows ghost roles and separate AI networks. You can now build an AI as the golems/free miners/oldstation people without it automatically being teleported to the station.
3. Decoupling networks from only being for the AI also allows us to add CompSci content for the netmin. Currently this only amounts to AI revival, bitcoin mining and regular research point generation.

### New project - Room Lockdown
Allows the AI, after a delay of 2 seconds, to close all working airlocks in a room and bolt them for 20 seconds. Also triggers the firealarm. Doesn't work in maint and announces itself at the start of the 2 second delay.

### New project - Heuristic Language Translation
Allows the AI to understand (but not speak) languages after hearing 8 messages containing that language. Currently ratvarian, codespeak, vampiric and xenocommon is barred from being translated. 
Requires 10% of your CPU to be allocated while running. Progress is not lost when disabling the program.

### AI Revival
No longer is the AI permanently dead when its last core is destroyed. Instead it spawns a black box at the last core it was in.
This core is active for 5 minutes. After these 5 minutes the AI is permanently dead.
You can revive the AI by inserting it into a working AI data core. (This also stops the 5 minute timer)
After its been inserted the local network the core is connected to must be set to AI Revival and the AI will then be revived after enough CPU cycles have been spent.

### Network Admin Exploration
The Network Admin can now use the VR sleeper in their room to access exploration missions. These missions contain unique components and unique research.
Currently just a mockup, only 2 added for now. One is just a walking simulator and the other one has some combat.
image
When you find the unique item you can put it in the microwave in your VR spawn and it will be transported to the station.
Future plans are to allow an AI to join you on the missions, plus allow you to buy equipment and unlock new missions using CPU on the station.

### Super Misc.
Added an easy way to use the TGUI login screen seen in the Security Console.
Use tgui_login_data in ui_data and tgui_login_act in ui_act. Use LoginScreen.js in the UI. See how the security console does it. (Only requires a var to keep track of being logged in/out)

Netmin retains access to Comms and the Tcomms satellite. NTSL equipment has been moved to the satellite and the old Hardware Workshop has been replaced by a small lounge
image

## TODO
- [x] Allow the AI a choice of which network to transfer to when a networking machine is destroyed.
- [x] More exploration missions
- [x] Allow synths to join exploration
- [x] Do all the other exploration
- [ ] Other maps
- [ ] Restore map config

# Changelog

:cl:  
rscadd: AIs are now housed in physical networks connected by ethernet cables. Networks can be remotely connected using networking machines. AIs can only switch between cores in networks they're connected to.
rscadd: AI upload and download is now done by hooking up a laptop or modular computer to an ethernet cable and using the AI Network Interface program
rscadd: It is now possible to revive an AI by inserting the dropped black box into a functioning data core and allocating CPU using the AI Network Interface program
rscadd: Added a new program, Room Lockdown, for the AI. Allows the AI to click an area and lock all working airlocks after a 2 second delay. An announcement is made beforehand.
rscadd: The Network Admin now has a VR sleeper and can go on short self-contained exploration missions to get unique components
rscadd: It now takes the AI 1 second to open doors unless it's connected to the master subcontroller in the RnD server room. If you multitool this new machine you can also disable instant door/apc/airalarm access for specific departments.
rscadd: NanoTrasen has procured some older model synthetics. They're currently working on getting their processing cores installed, but while you wait the AI can take control of them!
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
SOMEONE TESTMERGE THIS RIGHT NOW

**Comment by Moltijoe** [comment]
Pogging out of my mind right now.

**Comment by CMOisLing** [comment]
image

**Comment by MajManatee** [comment]
bibby dropping the fattest PRs of 2023

**Comment by bruhlookatthisdood** [comment]
you're telling me the ai can have ACTUAL HANDS NOW?

**Comment by yacabo** [comment]
Holy shit, this is amazing

**Comment by airlines7** [comment]
10/10, finally I can have law sets as a humanoid. You also might wanna change synth blood to blue instead of white because Detroit: Become Human.

**Comment by MajManatee** [comment]
The androids are more based off the seigsen synths from the alien universe. Supposed to look white and un natural

**Comment by Hislyna** [comment]
Suggestion - Give Sig Tech their own hardsuit so they don't have to steal Atmos/Engis one when doing cold shiz

**Comment by Hislyna** [comment]
Will the synths be able to do combat on malf perchance?

**Comment by Moja10** [comment]
Jesus christ Bibby, well done

**Comment by ShoziOffical** [comment]
YOO WORKING JOE FROM USMC

**Comment by ShoziOffical** [comment]
Next pr: converts xeno code to usmc one

**Comment by ShoziOffical** [comment]
> Suggestion - Give Sig Tech their own hardsuit so they don't have to steal Atmos/Engis one when doing cold shiz

They got coat

**Comment by ShoziOffical** [comment]
> 10/10, finally I can have law sets as a humanoid. You also might wanna change synth blood to blue instead of white because Detroit: Become Human.

No, have you ever heard of Alien: Covenant

Maybe androids blood to blue instead

**Comment by bruhlookatthisdood** [comment]
Please give the tree in lounge a name. Maybe bob... or Raphael?

**Comment by patpol4** [comment]
tree gone

**Comment by Hislyna** [comment]
You might have broke one of the "Add Custom Ai Law" options, even if I try to hide the ion storm from crew by pressing no, it will still pop up

**Comment by Bibby0110** [comment]
> tree gone

tree is back

**Comment by Marmio64** [comment]
synthetics should have glowing eyes. I don't know what inherent_slowdown is about but making them slow is also cool.

**Comment by JamieD1** [comment]
Fix this before test merging it again.

**Comment by BurgerLUA** [comment]
Feedback on the Synths.

If you can, I'd prefer it if I didn't have to return to the AI storage every time I want to get out of the core. It's annoying being on one side of the station, someone asking for a door to get opened, and I cannot leave my synth without losing it without going back to bridge.

Giving the AI synth pacification and other limiting features like the inability to wear hats, coats, and the inability to fire guns (regardless of it being lethal or not) honestly feels like baby padding. You can be super lethal with an engineering borg or a medical borg, it doesn't make sense that a normal shell is significantly better than the AI synth.

**Comment by MajManatee** [comment]
massive malf nerf

**Comment by Bibby0110** [comment]
> massive malf nerf

they deserve it

**Comment by Bibby0110** [comment]
> Feedback on the Synths.
> 
> If you can, I'd prefer it if I didn't have to return to the AI storage every time I want to get out of the core. It's annoying being on one side of the station, someone asking for a door to get opened, and I cannot leave my synth without losing it without going back to bridge.
> 
> Giving the AI synth pacification and other limiting features like the inability to wear hats, coats, and the inability to fire guns (regardless of it being lethal or not) honestly feels like baby padding. You can be super lethal with an engineering borg or a medical borg, it doesn't make sense that a normal shell is significantly better than the AI synth.

The synthetic control upgrade for the AI is meant to allow it to inhabit a synthetic for a short amount of time in a small area.
You're not supposed to wander far from your pod, nor are you supposed to spend that much time in one. It's strictly for quickly deploying a physical body in a place where it is needed.

**Comment by ThatLing** [comment]
>The plan is to add a roundstart job, where the player will be able to take control of any idle synthetic units around the station

I feel like they might be better as latespawners instead

**Comment by Bibby0110** [comment]
> > The plan is to add a roundstart job, where the player will be able to take control of any idle synthetic units around the station
> 
> I feel like they might be better as latespawners instead

no point?

**Comment by ThatLing** [comment]
> > > The plan is to add a roundstart job, where the player will be able to take control of any idle synthetic units around the station
> > 
> > 
> > I feel like they might be better as latespawners instead
> 
> no point?

What's the point of adding it as a new job? We already have cyborgs

**Comment by Bibby0110** [comment]
> > > > The plan is to add a roundstart job, where the player will be able to take control of any idle synthetic units around the station
> > > 
> > > 
> > > I feel like they might be better as latespawners instead
> > 
> > 
> > no point?
> 
> What's the point of adding it as a new job? We already have cyborgs

cyborgs aren't synthetics

**Comment by JamieD1** [comment]
JamieSeal
Happy to merge when completed. Please work on it now.

**Comment by Bibby0110** [comment]
I won’t be able to finish this before march, no point leaving it open

**Comment by TosterIMC** [comment]
> Job functionality is currently not implemented, but the AI can take control of one of the 2 units present on the station (Bridge and Science) after researching a new project.

Biggest problem i spoted is if ai traitor or malf could build cyborgs by itself from robo wich is made specifically for ai or cyborgs to not be able to do it, also it makes one of malf abilities the humanoid to cyborg machine spawn halfway useless.

**Comment by Therandomhoboo** [comment]
based

**Comment by MajManatee** [comment]
bibby is relapsing

**Comment by Bibby0110** [comment]
Stale

**Pull request closed without merging**
