### PR TITLE
Gives warden access to brig infirmary because its like their job to handle prisoners

### PR DESCRIPTION
**Pull request by alexkar598**
# Github documenting your Pull Request

Its kinda stupid that the warden cant access parts of his brig.

# Wiki Documentation

Warden gets access to the brig medbay

# Changelog

:cl:  
rscadd: Warden now has access to brig medbay
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Warden can ask brig phys to get in, and if the brig phys isn't in there, neither should any prisoners. This just seems like a way to get the warden able to powergame with the sleeper

**Review by adamsong — CHANGES_REQUESTED** [review]
The doors don't have brig phys access

**Comment by Hopekz** [comment]
> This just seems like a way to get the warden able to powergame with the sleeper

Do you actually think using a sleeper is powergaming?
Never seen a staff member have that stance before so actually curious.

Maybe if using a sleeper as a non-doctor is against the rules you should make a PR that prevents non doctors from being able to use it entirely.

**Comment by alexkar598** [comment]
> Warden can ask brig phys to get in, and if the brig phys isn't in there, neither should any prisoners. This just seems like a way to get the warden able to powergame with the sleeper

You're telling me you'd rather have prisoniers bleed out to death than have wardens healing them? Thats ridiculous.
Furthermore, the morgue cells are in there, for executions, the brig phys is in no capacity allowed to carry out executions and locking out the morgue cells is stupid.

**Comment by adamsong** [comment]
> You're telling me you'd rather have prisoniers bleed out to death than have wardens healing them?

Warden has access to a basic first aid kit, they can use that

> the morgue cells are in there, for executions, the brig phys is in no capacity allowed to carry out executions

Why are you executing people in the brig phys office? That is what the transfer center is for.

> Do you actually think using a sleeper is powergaming?

It is, why would a sec officer know how to use a highly advanced medicine delivery system, or the proper usages of the chems it contains

> Maybe if using a sleeper as a non-doctor is against the rules you should make a PR that prevents non doctors from being able to use it entirely.

Good idea #12214

**Comment by azzzertyy** [comment]
he said the morgue cell, adam, the morgue cell, which is in brigs medical.

**Comment by Hopekz** [comment]
> Good idea #12214

No problem, buddy, just helping you flesh out your true potential (:

**Comment by adamsong** [comment]
> he said the morgue cell, adam, the morgue cell, which is in brigs medical.

Which doesn't execute people. Also, execution requires cap's auth, and they have access

**Comment by Marmio64** [comment]
> > he said the morgue cell, adam, the morgue cell, which is in brigs medical.
> 
> Which doesn't execute people. Also, execution requires cap's auth, and they have access

morgue cell, you put the dead bodies of the executed people into the morgue cell you dope.

**Comment by adamsong** [comment]
> morgue cell, you put the dead bodies of the executed people into the morgue cell you dope.

I get that, but you can just give the brig phys the executed corpse

**Comment by Marmio64** [comment]
> > morgue cell, you put the dead bodies of the executed people into the morgue cell you dope.
> 
> I get that, but you can just give the brig phys the executed corpse

this is for when there is no brig phys obviously. Like how warden has access to the armory but if there is an HoS they're supposed to ask if they can hand out weapons, otherwise its usually on their own terms.

**Comment by JamieD1** [comment]
This is the same as saying CMO should have access to the sec checkpoint because "its in their medbay"

**Comment by maxion12345** [comment]
> This is the same as saying CMO should have access to the sec checkpoint because "its in their medbay"

doesn't the CMO uh,
have access to that checkpoint? I swear I can go into the science checkpoint as RD...

**Pull request closed without merging**
