### PR TITLE
Removes tables

### PR DESCRIPTION
**Pull request by jcatjmeow**
#### Changelog

:cl:  
rscdel: Removed every single table on box
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
wtf kar u cant close my pr in 14 seconds

**Comment by jcatjmeow** [comment]
;-;

**Comment by patpol4** [comment]
Do you want us to become even more lrp or what

**Comment by Marmio64** [comment]
fuck tables, man, all my homies hate tables

**Comment by jcatjmeow** [comment]
> fuck tables, man, all my homies hate tables

me too I hate tables grr



> Do you want us to become even more lrp or what

I left that one table. You know which one.

**Comment by Darkstick** [comment]
finally lizards will never stub their toes again

**Pull request closed without merging**
