### PR TITLE
Adds MRE rations (2018 MRE Pepperoni Pizza slice and Italian breadstick with cheesy jalapeno sauce + coffee instant type 2)

### PR DESCRIPTION
**Pull request by Kmc2000**
### Intent of your Pull Request

https://gyazo.com/6125be662e4aedaa81da58deedd1975b

#### Changelog

:cl: Kmc2000 (with Steve1989MREinfo)
rscadd: Added MREs which you can buy from cargo for cheap
/:cl:

### CODE REVIEW

**Review by monster860 — CHANGES_REQUESTED** [review]
missing the actual "Instant Coffee type 2" reeeee

**Comment by Kmc2000** [comment]
It's actually coffee instant type 2

**Comment by Nickvr628** [comment]
Good ol' #38. A fine MRE, but #10 is still the best one in the box.

**Comment by Kmc2000** [comment]
I swear youre too young to serve in the military Nick...

**Comment by Nickvr628** [comment]
I have had my fair share of MREs in the field, give me Pesto Pasta, Chile Mac, or Tomato Macaroni any day.

**Comment by MegaEmpirical** [comment]
Are they flagged to trigger diet restrictions and varied enough to cater to each diet type?

Also, nicely done. Cool idea.

**Review by monster860 — APPROVED** [review]
eh good enough

**Comment by RedTekRedd** [comment]
Space Force Space Base Ruin when @nichlas0010

**Comment by Amelia0010** [comment]
why are you asking me

**Pull request merged**
