### PR TITLE
Tenticle ling arm resprite (No more abusing sprite positioning edition) 

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
Ling tentlclie arm looks more like what the actual changling mob would produce to form a tenticle and you cant face sideways to make the sprite near impossible to see anymore.

# Spriting
lingshowcase2
lingshowcase
arm
shsowcase

# Wiki Documentation

icon change somewhere

# Changelog

:cl:  
 
imageadd: Action icon and mob sprites for tenticle ling ability are respeitred

/:cl:

### CODE REVIEW

**Comment by Potototatoh** [comment]
sure

**Comment by Marmio64** [comment]
if only the skin color could change to match the mob...

**Comment by KillerOrcaCora** [comment]
> if only the skin color could change to match the mob...

This actually something I wanted when I first made these sprites like 8 months ago with the help of ident. Sadly he wasn't too sure how to do the code for that and I sure as hell wasn't so we just settled with taking the pallet off the changling mob and calling it a day. 

I could probably do it now if I really wanted to but I know how cringe mutant code is...and overall it doesn't feel too jarring being the sprite you are anyhow is just a fake cover-up for what's actually under the hood. kinda like that movie the "Thing"

**Comment by Burger1998** [comment]
maybe change the red to the same grimy red that the armblade has? for consistency's sake.

**Comment by Burger1998** [comment]
its just that the current bright red is a little strong.

**Comment by KillerOrcaCora** [comment]
> its just that the current bright red is a little strong.

Can't handle the raw unending energy of dream makers' color picker? tsk tsk tsk a shame ill dim it so you can survive another day

**Comment by KillerOrcaCora** [comment]
Lmao...I looked at arm blade coloring and that chief is true beyond dream maker quality...I am not tainting my sprite with 50 shades of red with bizarre alpha choices no thank you.
Capture

My sprite is not the odd one out anyhow, maybe arm blade needs a resprite.

**Comment by CMOisLing** [comment]
Are we going back to a fleshy horror like artstyle instead of the prototype inspired armblade?

**Comment by KillerOrcaCora** [comment]
That's what I was thinking, only issue right now I am seeing with that is the arm blade itself is a heavily overused sprite by every coder left side of the family's mother and soul warriors, I like the other ling sprites so I not even gonna do that, just the actual tentacle sprite was terrible.

**Review by cuackles — DISMISSED** [review]
i like it general but i would like to see it with the skin color changed to another color so its more universal to all speciel, maybe try something like the greys in the arm blade or the blacks in the mace apart from that i really like it and its overall a big improvement over the existing tentacle

**Review by cuackles — APPROVED** [review]
ok so after talking a bit with orca the conclusion was reached that even tho i would like the change of the skin color to be more fitting to all mob species it would either take a really long time to make it look good enough or just be a pain to do in a timely manner so for now its approved, if anyone else is willing to take a crack to fix the skin tone issue with either coding something so it applies the mutant color or makes it a muscle fleshy color that works properly without disrupting the design they are encouraged to do it

**Pull request merged**
