### PR TITLE
Maybe makes the changelog compilation automatic

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

What's the worst that could happen

#### Changelog

:cl:  
tweak: Github should now automatically compile the changelog
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Does this work

**Comment by Amelia0010** [comment]
I have no clue. It should, since the commands are taken from the changelog script we run on the host, and the action framework is sorta adapted from this PR: https://github.com/tgstation/tgstation/pull/47961

**Comment by optimumtact** [comment]
you need pyyaml and beautifulsoup4 as they are dependencies.

**Comment by Neotwr** [comment]
@nichlas0010 why you close it?

**Comment by Amelia0010** [comment]
because our master branch is protected, meaning that the action can't push to it, without a personal access token from me, and any such token fucks up any forks since they don't have personal access tokens from me.

**Comment by Neotwr** [comment]
ah

**Pull request closed without merging**
