### PR TITLE
Morphine heals in crit and when asleep now

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Morphine will heal 1 brute, burn and oxy damage per tick now, either when the patient is asleep or in critical condition, largely negating its use for combat and generally being a bit more practical for stuff like surgery.

# Spriting

# Wiki Documentation

# Changelog

:cl:  

tweak: Morphine heals in crit or when you're asleep 

/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
okay, so what's the knockout Chem then?

**Comment by solwashere** [comment]
> okay, so what's the knockout Chem then?

Chloral Hydrate

**Comment by Rdrazga** [comment]
That moment when the ‘true’ use of morphine for combat was the anti-slowdown it gave not the knockout effect

**Comment by solwashere** [comment]
> That moment when the ‘true’ use of morphine for combat was the anti-slowdown it gave not the knockout effect

True, I tend to microdose myself with morphine whenever I'd use my hardsuit

**Comment by Moltijoe** [comment]
> That moment when the ‘true’ use of morphine for combat was the anti-slowdown it gave not the knockout effect

mfw a chem can have depth by having multiple uses

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
