### PR TITLE
Protects events from being faked random by admins

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Moja said I couldn't and I proved him wrong in less than a minute when I looked up the message

You could still theoretically create the event datum yourself and fake the deadchat message but at that point you may as well spawn in 7 ninjas yourself

### CODE REVIEW

**Comment by alexkar598** [comment]
if you start baby(admin)proofing every single part of this codebase, you'll be at it for a looong time

**Comment by ynot01** [comment]
> waa waa waaa

Shut up bro you're weird!

**Comment by MajManatee** [comment]
just let them fake random events??

**Comment by ThatLing** [comment]
If it's logged, I don't see the issue

**Review by MajManatee — APPROVED** [review]
if admins want it then sure i guess

**Comment by JamieD1** [comment]
> if admins want it then sure i guess

BRUH?

**Pull request merged**
