### PR TITLE
Suppressing fire (literally) - More suppressable weaponry

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
 WT-550s and the NT-USP are now suppressable, assuming you can get the illegal tech required to PRINT said suppressors.
 
 BUT WHY you may say
 and to you I say 
Rule of cool

Suppressors arent really meant to be STEALTHY, I mean they are but that's unrelated. Its so you don't go fucking deaf when firing guns all the time. So really by adding this, we are improving the OSHA safety rating of the station.

Adding a suppressor to your USP make it larger, just like the stechkin, so it wont fit in pockets anymore. Adding it to your WT wont do much because its already big so it didn't fit anyways...

# Changelog

:cl:  
tweak: WT and USP are now suppressable.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
wanna make sure there are functioning sprites?
for the clown suppressor too

**Comment by MajManatee** [comment]
not particularly...

**Comment by Moltijoe** [comment]
> not particularly...

at least make sure it doesn't break shit, even if they're invisible

**Comment by 00ze-cyclone** [comment]
Hate ballistics but I hate useless items more so I like that the printable suppressor finally get a use.

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
