### PR TITLE
[PORT] Dragging prone mobs slows you down, fireman carrying

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request
Ports https://github.com/tgstation/tgstation/pull/44155
Ports https://github.com/tgstation/tgstation/pull/46735

**PR Quote**

Dragging prone mobs (resting, knocked down, stunned, dead, in crit, etc) that aren't buckled to anything slows you down.

You can fireman carry by aggressive grabbing then click dragging onto yourself. This causes a slight speed penalty that is lower than dragging.

Prevents the classic "stun and beat the shit out of while zipping off" which is obnoxious and I don't think anybody likes besides the people who do it.
Makes it so if you feel like being a cunt you can rest while being arrested to make you a pain to take back.
Makes it harder to steal bodies and move away before anybody can properly react, but makes dragging bodies riskier at the same time
Fireman carrying adds an element of risk reward, it takes a little while of standing still to pick them up and also slows you down slightly. More useful to move someone a long distance out of a relatively safe area than a quick pull away.

#### Changelog

:cl:  
add: fireman carrying. Aggressive grab then click drag onto yourself.
add: nitrile/latext increases fireman pickup speed
tweak: pulling prone mobs slows you down.
tweak: carrying another human slows you down.
tweak: pacifists can aggressive grab.
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
How does piggybacking work now

**Comment by redmoogle** [comment]
> 
> 
> How does piggybacking work now
 
should be the exact same just coded more modular

**Comment by Jarod1200** [comment]
Time for the double rolling chair sec meta

**Comment by Mqiib** [comment]
I love you

**Comment by redmoogle** [comment]
> 
> 
> Time for the double rolling chair sec meta

~~Implying I wont nerf that :)~~

**Comment by boodaliboo** [comment]
i dont like this

**Comment by Marmio64** [comment]
if you're going to do add this, there also needs to be a PR or something that makes it so that grabbing cuffed people who can stand up, makes them stay standing up, because it is going to be so god damn annoying to have to constantly help intent shitters as sec when arresting them. Neutral for now.

**Comment by Mqiib** [comment]
> if you're going to do add this, there also needs to be a PR or something that makes it so that grabbing cuffed people who can stand up, makes them stay standing up, because it is going to be so god damn annoying to have to constantly help intent shitters as sec when arresting them. Neutral for now.

Yeah except if someone is actively resisting being moved you're gonna have trouble moving them cuffed or not. One could argue that trying to slow down the officer intentionally could be considered resisting arrest and as such could add to your brig time. On top of that, you can still just fireman carry them and it's not like they can do anything about it.

**Comment by redmoogle** [comment]
> 
> 
> i dont like this

What do you not like about it

**Review by Amelia0010 — APPROVED** [review]

**Comment by MegaEmpirical** [comment]
Been wanting fireman carry, nice.

**Review by fluffe9911 — APPROVED** [review]
less blood loss is nice

**Pull request merged**
