### PR TITLE
Ethereal is brighter

### PR DESCRIPTION
**Pull request by Moltijoe**
I was talking to a sad Ethereal one day, I told them "lighten up, try to look on the brighter side of life"
They promptly killed themselves

:cl:  
tweak: Ethereal is brighter
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
I don't know why this change is good for the game, all I know is that it is

**Comment by Firewolf34** [comment]
As an Ethereal, I approve of this PR

**Comment by Annoying-plant** [comment]
10/10 spat my drink out reading it

**Comment by Moltijoe** [comment]
> As an Ethereal, I approve of this PR

don't lie, you don't exist

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
