### PR TITLE
[BOUNTY] Ports minesweeper to TGUI

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

## New things

The first tile you hit will always be a blank/white tile

Right clicking will place a flag instead (or you can toggle flagging mode)

Mines left are shown at the top based on how many mines are in the current level and how many flags are placed

Victory now dispenses tickets (which can be exchanged for prizes) based on difficulty instead of a prize

Stopwatch included at the top so you know your time

##

Beginner or custom equivalent (in mine:tile ratio) gives 1 ticket (estimated <1 minute playtime)
Intermediate or custom equivalent (and 13x13+) gives 4 tickets (estimated ~2 minute playtime)
Expert or custom equivalent (and 13x25+) gives 20 tickets (estimated 20+ minute playtime)
Custom board with >30% mine ratio (and 13x25+) will give 25 tickets
<10% mine:tile ratio will reward no tickets

Beginner is 10x10 with 10 mines
Intermediate is 17x17 with 40 mines
Expert is 30x16 with 99 mines

Custom will let you make boards up to 30x17 with up to 50% mine ratio

Yes you can emag the arcade machine

No emagging your PDA will not emag the minesweeper

# Changelog

:cl:  
rscadd: Added TGUI Minesweeper to NTOS and Minesweeper arcade machines
rscdel: Removed HTML Minesweeper
/:cl:

### CODE REVIEW

**Comment by Jumps0** [comment]
minesweeper

**Comment by Jumps0** [comment]
Alright well having tried it out and thinking about it here is my review for the PR.

[**X**] UI - The UI looks great, this is the main thing I was looking for in a minesweeper UI rework. It being not HTML also comes with it not being super laggy.

[**X**] Right clicking - Initially I wasn't sure if it was possible to right click to place flags (in SS13) but I am glad that its there and its something I wanted to see.

[**X**] First Tile - Also glad to see that the first tile never being a mine was implemented. Very cool to not insta-die when its emagged.

[**X**] Custom Boards - The implementation of custom made boards looks good. Not something I expected but nice to see.

[**~**] Tickets - I'm a bit iffy right now on the tickets, that being two are needed to get a prize. Though keep in mind I'm super biased on the way I play SS13 minesweeper, because I only do Beginner mode speedruns to get certain toy rewards in the shortest amount of time. **I don't expect normal people who are going to play SS13 minesweeper to have this mindset, so in that sense the balancing seems fine**.  I feel like that maybe with the re-done UI (which is now significantly less laggy), I could perhaps maintain an optimal ticket pace like before.

Overall I am happy with the work you've done and I thank you for improving the minesweeper experience. This looks great and i'm looking forward to when it gets merged.

**Review by Bibby0110 — DISMISSED** [review]
don't duplicate files like that, use a datum or something similar, (which also sucks, but less)
EDIT: Abstract the game and such into a datum and then interact with it through the consoles. That way we only have to change 1 place if we want to do anything to the game itself

**Comment by JamieD1** [comment]
@ynot01

**Comment by JamieD1** [comment]
@ynot01

**Comment by Jumps0** [comment]
@ynot01

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
