### PR TITLE
MultiZ + Monsterstation for testing and abuse

### PR DESCRIPTION
**Pull request by monster860**
Adds multiz support, and additionally adds the new map I made as well.

image
image
image
image
image

What the code side does:

- Parallax effect for lower z-levels
- Adds 3D-ification for stairs, vertical pipes/disposals/cable
- Adds vertical pipes/disposals - build with RPD
- Adds vertical cable - use cable coil on wall
- Adds move-up/down buttons to the UI for humans, aliens, ghosts, and robots.
- Adds ability for mechs,people,spacepods to go up and down in zero-gravity
- Adds glass catwalks (sprites by Partheo)
- Adds ability for bots to pathfind across z-levels
- Fixes a bug caused by shitty TG code that causes c++ atmos to segfault on multi-Z

requires 513

:cl: monster860
add: Multi-z support
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
Wicked

**Comment by Jumps0** [comment]
Nvm I see you got a button for that nice

**Comment by monster860** [comment]
there's a button you can use to move up and down z-levels whether you're wearing a jetpack or not.

**Comment by Xoxeyos** [comment]
Jetpacks will become the new way to travel. Thanks for the sweet update, Monster.

**Comment by Rdrazga** [comment]
Cargo doors leading to cargo shuttle don't have a way to open on the cargo side.

**Comment by Xoxeyos** [comment]
Also, question about the parallax, will it effect the quality of the structures beneath it, the same with space?

**Comment by Xoxeyos** [comment]
No railings, confusing station map, copy and pasted rooms, little to no use of departmental signs, so you have little way of knowing which way you are headed, HoS's pathway is a bunch of lattices, leading to his office, with no railing, lights between z-levels were a bit fucked in maintenance. That's pretty much it.

**Comment by FiveSixtyGaming** [comment]
Legit needs to be fixed with the bugs such as not being able to drag items, people, anything up and down stairs. The only way around this is to push it or throw it which is a pain. If all the bugs are mostly fleshed out I'd say this is a decent map with a new feel for the server

**Comment by immortalartisan** [comment]
after playing this map for the first time add railings

**Comment by Xoxeyos** [comment]
> 
> 
> No railings, confusing station map, copy and pasted rooms, little to no use of departmental signs, so you have little way of knowing which way you are headed, HoS's pathway is a bunch of lattices, leading to his office, with no railing, lights between z-levels were a bit fucked in maintenance. That's pretty much it.

Oh, but I really liked how the AI core and telecommunications looked. The layout of the station is all over the place, you may want to spread it out a bit.

**Comment by immortalartisan** [comment]
i think it broke suit sensors

**Comment by alao3alao3** [comment]
Cool idea, but needs alot more refining before released. Map layout is confusing and certain aspects are flat out missing (No airflaps, no request console within HoP office, no EVA, no Oresilo, no Gift Shop, No Radstorm Overlay, Maint appears to not shield from radstorms). More considerations must be made before implementing, kind of like having to ask for the "pull into firelock" feature in monstermos (moreover, pulling between stairs does not seem to work).

Certain areas where downright exposed, Someone spotted a way to enter the SM chamber, or throw things into it, from maint directly below the HoP office. The lack of railings led to most people falling off of glass walkways or lattices.

**Comment by Jarod1200** [comment]
can you do like monsterfirelocks do where if you are dragging something, and you go up a staircase it pulls it with you?

**Comment by Jarod1200** [comment]
Also station needs an ore silo and it to be linked to the department protolathes

**Comment by immortalartisan** [comment]
move evac to middle deck

**Comment by Jumps0** [comment]
HoP line has no windoors

**Comment by azzzertyy** [comment]
Map seems way more like a placeholder.
Radiation does not travel through z levels.

**Comment by DerelictDrone** [comment]
image
flour straight up floats in the goddamn air
image
can sometimes see lower floors or floors that don't exist?
image
can see transit pipe corners through walls
image
image
Why do multiZ pipes and wires CHANGE DIRECTION FROM WHERE YOU VIEW THEM AAAAA

**Comment by alao3alao3** [comment]
That’s just fancy parallax stuff to identify multi-z aspects that go up or down. Stairs do the same thing.

**Comment by Hopekz** [comment]
> That’s just fancy parallax stuff to identify multi-z aspects that go up or down. Stairs do the same thing.

No; the beauty of multiZ is being able to fully see the layers under so it isn't entirely about changing floors.

**Comment by Hopekz** [comment]
Also; as far as map feedback.
It's too overwhelming in my opinion. Out of the multiple test merges that we've had with it I couldn't even really find my department except out of pure luck. Sure the map can give you a general "area" but there isn't really any indicator on the maps on "how to get there" since it usually requires traversing the multi-Z to get somewhere.

The only reason I had to "find" the department is that everyone doesn't seem to spawn in their department in the first place. 
As Engineering I got spawned in the middle of Science for some reason and had to flush myself down disposals to get out which was weird. Then I spent about 30 minutes finding my department so I just waited in the first I found pod for it to be over at that point.

I am not the only person experiencing this issue as I've asked around.
This is too overwhelming as a map in rotation as it stands. 
It would have been better if you started with maybe 2 main floors instead of throwing 4 main floors at us.

Also, there seems to be a fundamental problem with how some areas are structured because we've had many people die just by walking off a ledge where it wasn't immediately obvious that it is a ledge. There are only floor decals but maybe make the colors varied on the floors to accentuate this.

It might be better to make each floor have its own "color" theme so we can tell what floor we even on. I think at once point I fell down because I got pushed off accidentally by someone else and I had no clue if I've fallen 1 floor, 2, or 3. It just kind of "reset" my progress in navigation because I had no idea where I was relative to the map after that fall.

The main problem with the "walking off ledges" issue is that people couldn't really seem to find medbay to bring the bodies to. So they'd just be piling up and no-one really knew what to do with them. I personally dragged a corpse around for about 5 minutes of my adventure looking for medbay before I gave up to look for my department again.

**Comment by Jarod1200** [comment]
make stairs either craftable or indestructible

**Comment by asmcint** [comment]
Map needs markings for where escape is like every other map has.

**Comment by Jarod1200** [comment]
what if landing on a bed cushions your fall

**Comment by immortalartisan** [comment]
ai upload didnt work due to ai core being on different level

**Comment by ynot01** [comment]
replays are essentially unwatchable on multiz

**Comment by immortalartisan** [comment]
exosuits cant use stairs

**Comment by DiamondSentinel** [comment]
There are too many broken cameras to list, as well as too many areas viewed by only a single camera. Medical tracking doesn't work across Z levels. 

Like, even beyond the basic technical issues, the map just isn't good. Even if you know the layout (which isn't *that* hard), it's far too strong for antags who just go in guns blazing and then duck out. Too many exits and ways for them to get out of trouble and traverse the station. Everything feels claustrophobic, and the map is too slow, both as rounds go and as just basic movement goes. The dilation is always high on the server, but at the end of a 40 minute round with no major breaches, atmos issues, or any of the usual suspects, we were rocking 42% dilation.

**Comment by Xantam-13** [comment]
I love the sheer amount of work you've put into this but it is very overwhelming. This is an event in itself because everyone would spend an entire round learning how to use stairs and the map. If we used this on a daily basis or in rotation I feel like with its complexity it'd drive our population down. 

But that doesn't take away from the hard work you've put into this, very well done monster <3

**Comment by alexkar598** [comment]
This is a neat concept but uh.... thats pretty much what it is, a neat concept. I dont really see the need in such a complex setup

**Pull request closed without merging**
