### PR TITLE
latte and coffee cups now look better (part of yogstation coffee dlc)

### PR DESCRIPTION
**Pull request by AlvCyktor**
image
# Document the changes in your pull request
Revamped the sprites for coffee cups

# Spriting
coffee1 coffee
coffee3 soy latte
coffee cafe latte

# Wiki Documentation
update the sprite for soy latte, latte, and coffee

:cl:  
tweak: better sprites
/:cl:

### CODE REVIEW

**Comment by AlvCyktor** [comment]
I got a better idea actually

**Comment by AlvCyktor** [comment]
nevermind lol

**Comment by JamieD1** [comment]
Where the fuck is my extra tea sprites.

**Review by cuackles — APPROVED** [review]

**Comment by JamieD1** [comment]
Cornflakes

**Comment by JamieD1** [comment]
Why you closing all your PRs

**Pull request closed without merging**
