### PR TITLE
Adds Plastic Chairs

### PR DESCRIPTION
**Pull request by ChesterTheCheesy**
# Document the changes in your pull request
Adds plastic chairs, craftable with 5 sheets of plastic.

Edit: Added a small easter egg: sitting in the chair for at least a minute will give you 'motivated' moodlet, and if you don't have jukeboxes muted, will blast your ears with Bury the Light (with slightly edited intro to make it more suspenseful). The song cuts as soon as you get unbuckled from the chair.

# Spriting
[If you are adding new sprites to the game please add a picture of the sprite in its relative context, ie. Clothing on a mob.](https://user-images.githubusercontent.com/71487903/186663863-c0334651-fc65-4aaa-8f43-786de4b5adff.mp4)

# Wiki Documentation
Can be added to the guide to construction or whatever, craftable with 5 sheets of plastic, functionally identical to comfy chairs

# Changelog
:cl:  
rscadd: Imports Vergils chair from DMC5
soundadd: Adds the horrid sounds of chair scrapes
imageadd: Adds plastic chair sprites
experimental: Now i'm motivated
soundadd: adds at least 3 minutes of Bury the Light
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
can you import the entirety of Bury the Light and make it play when you sit down

**Review by cuackles — APPROVED** [review]
vergil-chair

**Comment by ChesterTheCheesy** [comment]
> can you import the entirety of Bury the Light and make it play when you sit down

i might consider it playing very quietly if you sit in the chair for more than a minute, also giving you a motivated moodlet

**Comment by ChesterTheCheesy** [comment]
> can you import the entirety of Bury the Light and make it play when you sit down

Done, but only like 1/3 of the song, which is still 3 minutes long

**Comment by JamieD1** [comment]
dont add it to ambience, add it to jukebox or instruments or something people will have muted if they dont want to hear music.

**Comment by ChesterTheCheesy** [comment]
> dont add it to ambience, add it to jukebox or instruments or something people will have muted if they dont want to hear music.

obraz
if they don't want to hear music, they won't hear it anyway

**Pull request merged**
