### PR TITLE
Space Heater buff (cit port)

### PR DESCRIPTION
**Pull request by Jumps0**
### Intent of your Pull Request

All credit to the original coder **Trilbyspaceclone**.
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12241

"space heaters can now be wrenched and unwrenched to remove bolts
space heaters now have 300% more laser powering and 200% more capacitor power"

Obviously the wrench ability is a given, why they aren't able to be wrenched up until now is unknown to me. I also feel like the buff to their temp change ability is warranted given how horribly slow they are.

#### Changelog

:cl:  Trilbyspaceclone
rscadd: Space heaters can now be wrenched and unwrenched
tweak: Space heaters drain less and can reach even hotter/colder temps faster!
/:cl:

### CODE REVIEW

**Comment by Jumps0** [comment]
If you want me to adjust the buff-y-ness of the temp changing that's fine.

**Comment by JamieD1** [comment]
Are you basically just making them start with higher tier parts?

**Comment by Jumps0** [comment]
> Are you basically just making them start with higher tier parts?

from looking at the code that is what it seems

**Comment by alexkar598** [comment]
Not the prettiest way to do it but its not that bad

**Pull request merged**
