### PR TITLE
Adds Sclera (Eyes are now Minecraft)

### PR DESCRIPTION
**Pull request by YashinHak**
# Document the changes in your pull request

Distinguishes Yogstation from other servers (Shiptest is distinguished enough from us so it's okay, it's not a port still since the code was written separate from that server) by adding 2 White pixels on each outer side of the eye for most races. Races with no one pixel eyes won't have them. (Some races also do not get them but still get the original eyes, Preternis mainly) It also slightly makes the head icon less textured so the new eyes fit better.

# Spriting
Two Pixel Eyes!!!
image
image

# Wiki Documentation

Skiwow skilated, every single human image is now outdated

# Changelog

:cl:  
wip: Removing Sclera for Preternis & potentially other species
wip: Make it optional the same way textboxes are
imageadd: Minecraft Eyes
imageadd: Smoothed out Human head
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
god no please no

**Comment by ynot01** [comment]
meme pr

**Comment by solwashere** [comment]
I love it <3

**Comment by iamthesilly** [comment]
i love this

**Comment by Therandomhoboo** [comment]
People getting upset about it, when they wear head gear/glasses so it doesn't affect them.

**Comment by Notamaniac** [comment]
> People getting upset about it, when they wear head gear/glasses so it doesn't affect them.

Yes but I'm going to have to look at other people who don't wear them.

**Comment by solwashere** [comment]
I feel like the sprites add so much more life to people instead of having beady eyes

**Comment by YashinHak** [comment]
Added: wip: Make it optional the same way textboxes are, this will hopefully please both sides by letting you turn off seeing any sclera be it yours or someone elses

**Comment by Marmio64** [comment]
if its going to be optional, whatever i guess

**Comment by neeshacark** [comment]
dear god no - make it optional if anything

**Comment by Hopekz** [comment]
Lmao @ it just looks like they're cross eyed 🤣

**Comment by MajManatee** [comment]
i dont particularly care. As long as it fits with glasses sprites and doesnt cause clipping then sure

**Comment by Moja10** [comment]
I kind of dig it tbh

**Comment by MajManatee** [comment]
does this version have the blinking?

**Comment by YashinHak** [comment]
> does this version have the blinking?

No, that feature has a few larger barriers than this feature and is not yet ready for even a draft.

**Comment by CMOisLing** [comment]
Can we get some shots of all the other races?

**Comment by YashinHak** [comment]
I'll remake this later once i figure out some stuff and have more time and motivation. Putting it on hold for now!

**Comment by ToasterBiome** [comment]
Hope you get the time soon!

**Pull request closed without merging**
