### PR TITLE
Add rags and Soap to Service Borg

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Adds soap and rag to service borg

#### Changelog

:cl:  
rscadd: Add soap and rag to service borg
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
yes

**Comment by JamieD1** [comment]
Tried fixing rag but will not be a quick job, will work on later on when time permits, for now have a soap as well.

**Comment by MegaEmpirical** [comment]
I was about to comment on rags being broken. Thank you, I love you.

**Comment by alexkar598** [comment]
soap

**Pull request merged**
