### PR TITLE
[BOUNTY] Ports prisoners from TG(Conflicltless edition)

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request
Ports prisoner job from TG, and four pull requests related to it:
https://github.com/tgstation/tgstation/pull/48819
https://github.com/tgstation/tgstation/pull/49229
https://github.com/tgstation/tgstation/pull/49177
https://github.com/tgstation/tgstation/pull/49423
https://github.com/tgstation/tgstation/pull/49861

I did change every map for this role except GaxStation, because it is currently under development and i don't want merge conflicts(fuck merge conflicts).

# Wiki Documentation

A wikipage about it?

# Changelog

:cl:  Author: [RaveRadbury](https://github.com/RaveRadbury)
rscadd: Adds Prisoner role
imageadd: Adds icons for prisoner plasmeme envirosuit 
rscadd: The biogenerator can now produce soy milk.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Fucking shit

**Comment by ghost** [comment]
WHY WHY WHY WHY

**Comment by ghost** [comment]
Never again i will work with fucking map files

**Comment by ghost** [comment]
Okay it is fucked

**Comment by Bibby0110** [comment]
I would contact Jamie or one of the map maintainers and work on pausing other maps while this gets merged
You're probably going to have to remake this PR to fix the maps and icons so I'm doing you the favor of closing it.

**Pull request closed without merging**
