### PR TITLE
 Added Decal painter 

### PR DESCRIPTION
**Pull request by warface1234455**
# Added decal painter (tg: https://github.com/applepineapplepizza/Yogstation/tree/decalpainterport)
image
You can now add some cool decals on floor 

# Wiki Documentation
Decal painter??

# Changelog

:cl:  
- Added decal painter
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
make please normal description, leave a link to the original PR and credit the authors

**Comment by ghost** [comment]
and you need to include the prite images in the description

**Comment by warface1234455** [comment]
> and you need to include the prite images in the description

there

**Comment by warface1234455** [comment]
@TymurShatillo

**Comment by ghost** [comment]
> @TymurShatillo

I am not a maintainer, im just giving you an advice :)

**Comment by warface1234455** [comment]
lemme do checks!!!

**Comment by ghost** [comment]
> lemme do checks!!!

I can't

**Review by KillerOrcaCora — APPROVED** [review]
Epic

**Pull request merged**
