### PR TITLE
adds bluespace crystals to the swarmer ruin

### PR DESCRIPTION
**Pull request by boodaliboo**
gives some bluespace crystals alongside the ones you already get from killing the lavaland swarmers to hopefully incentive people to do this ruin more
#### Changelog

:cl:  
rscadd: Added bluespacer crsysal
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
how did it fail?

**Comment by boodaliboo** [comment]
@Ktlwjec @Ktlwjec1 not sure which one is the active one but any clue why this is happening and what i need to do to go about fixing it

**Comment by Reed0506** [comment]
many bloospess

**Comment by patpol4** [comment]
This change is bad because it buffs something that doesnt need a buff. Push a commit to fix the check, mapdiffbot is fucky sometimes.

**Comment by jcatjmeow** [comment]
Alexkar or jamie can restart the bot for you. Just don't worry about it for now

**Comment by boodaliboo** [comment]
> This change is bad because it buffs something that doesnt need a buff. Push a commit to fix the check, mapdiffbot is fucky sometimes.

have you fought the swarmer ruin?

**Comment by patpol4** [comment]
> > This change is bad because it buffs something that doesnt need a buff. Push a commit to fix the check, mapdiffbot is fucky sometimes.
> 
> have you fought the swarmer ruin? 

nope im just pulling opinions out of my ass

**Comment by patpol4** [comment]
That being said, ruin ≠ place that has to contain loot

**Comment by patpol4** [comment]
Ok i changed my mind, what you put in isnt just miner gamer gear used to murder people but actually things that they should get through mining. Good change

**Review by patpol4 — CHANGES_REQUESTED** [review]
Just fix the checks and put a single varedited sheet instead of placing multiple.

**Comment by boodaliboo** [comment]
> Just fix the checks and put a single varedited sheet instead of placing multiple.

give me a bit

**Comment by Mesalikepie** [comment]
Okay ummm the ruins hella annoying to do. You already get way too many bluespace crystals from killing the swarmers so there's no point. Maybe put something else in the ruin that's replication or teleporting focused. This ruin is hot garbage though and does need a reason to actually be cleared out otherwise it's just ignored which is boring

**Comment by Marmio64** [comment]
would be cool if destroying it dropped a swarmer catwalk creator, you go up to lava and click on it with the item and it makes a swarmer catwalk there, which you can walk across safely. Make it have like 15 uses or make it require ammo, one bluespace crystal refuels 3 uses. Could also have a kinetic crusher trophy that is like the legionnaire one, where it spawns skulls to fight for you for a bit, but instead the skulls could be reskinned to swarmer drones. My last idea is to make it give a stabilized legionnaire core that has a blue center instead of a red one, and is renamed to 'Swarmer Core'. It's description could be that its the thing inside the replicator machine that allows it to generate materials with which to make more swarmers, and that you can apply it to yourself to regenerate.

**Pull request closed without merging**
