### PR TITLE
Better Chess - Part 1

### PR DESCRIPTION
**Pull request by JamieD1**
image

Stay tuned for Part 2 - Will include a chess playing console and AI interaction

Credit to: https://opengameart.org/content/chess-pieces-1

#### Changelog

:cl:  
rscadd: Better Chess
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
How would one go about getting extra pieces for the board when you promote a pawn?

**Comment by Marmio64** [comment]
> How would one go about getting extra pieces for the board when you promote a pawn?

i believe the lockers in the upper and lower right have those extra pieces

**Comment by patpol4** [comment]
Thin carpet strips look really bad ingame

**Comment by patpol4** [comment]
How's this
chrome_X3CEtrcbJ7
keep in mind grafitti-holodeck interactions are not tested

**Comment by alexkar598** [comment]
Why tho, just play fucking chess if you want to play chess, ss13 is not a chess simulator, its a space station chaos PvP simulator

**Comment by neeshacark** [comment]
> Why tho, just play fucking chess if you want to play chess, ss13 is not a chess simulator, its a space station chaos PvP simulator

because c h e s s

**Pull request merged**
