### PR TITLE
[CONFIG] MOTD Update

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

This updates the MOTD to be grammatically correct, factually correct, etc.. a bunch of shit pretty much. Look at changelog for changes.

###**This will need to be updated in the Config.**

#### Changelog

:cl:  
tweak: Changes repo link to modern version
rscdel: Removes Yogs General Survey from MOTD
rscadd: Adds mentor reference and application link
rscadd: Adds more examples of donor features
tweak: Bolds forum keyword
tweak: Fixes admin application link
tweak: Fixes grammatical errors
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
I need a maintainer to approve the HTML changes but a HC is going to need to update it to the host

**Review by JamieD1 — CHANGES_REQUESTED** [review]
A couple line breaks wouldn't hurt, seems a bit bunched up. New lines in the code doesn't mean new lines in the html remember.

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Swiss..
You need to add </br> where you want breaks.. pressing enter doesn't work like that in html.

**Comment by swissloaf** [comment]
> Swiss..
> You need to add
> where you want breaks.. pressing enter doesn't work like that in html.

Sorry, I thought you wanted it actually spaced out in the code not in game

**Review by JamieD1 — APPROVED** [review]
Much better

**Pull request merged**
