### PR TITLE
TEG visual update

### PR DESCRIPTION
**Pull request by Partheo**
### Intent of your Pull Request

This PR completely revamps the visual experience surrounding the TEG. Special thanks to Pawn for making these beautiful sprites and allowing us to use them here.

image

The primary change is how the TEG looks- rather than looking like a large machine, the three parts of it are clearly distinguished, yet connected. Both circulators, instead of spinning, emit light that reflects the mode they are in and how well they are performing.
The secondary change to this PR is how the TEG behaves. **Power generation and interaction with gasses is unaffected.** However, many of the building steps to build, deconstruct, and move the TEG around have been changed. You'll feel it's much smoother now, and the TEG will act more like a cohesive unit rather than a bunch of adjacent parts. This was done to avoid the odd visual situation of half-connected parts or whatnot.
The TEG now has broken state sprites, created by myself. I made a large amount of other minor edits to make it feel more at home here on Yogs. Sorry Pawn, I added more colors.

Here is a mockup of the TEG's animations; they have been altered slightly:

Sprite-0002

Old TEG:

image

#### Changelog

:cl: Pawn, Partheo
tweak: the TEG's construction steps have been altered slightly for visual consistency.
imageadd: the TEG's visuals have been completely redone. Sprites by Pawn.
tweak: the TEG circulators can now be flipped with a crowbar.
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Gallery:

2sayHaYT8k

(Everything below this is slightly out of date)

1JmdyDG9AH

5OJY6kGUF6

N5gUXnHh2D

**Comment by ghost** [comment]
Time to make flaming monkey TEG engine set up

**Comment by redmoogle** [comment]
To me the sprites feels out of place because it's too detailed compared to the rest of the game ~~I love it though~~

**Comment by Partheo** [comment]
I anyone can suggest some good sounds to use for the TEG (either from within the codebase, on other servers, or elsewhere) please let me know!

**Comment by patpol4** [comment]
The artstyle doesn't fit our current one but it looks fucking amazing

**Comment by ghost** [comment]
> 
> 
> To me the sprites feels out of place because it's too detailed compared to the rest of the game ~I love it though~
image

**Comment by Readystorm546** [comment]
> To me the sprites feels out of place because it's too detailed compared to the rest of the game ~I love it though~



> The artstyle doesn't fit our current one but it looks fucking amazing

I think it fits way better then some other sprites that are in this game. Not to mention how amazing it looks. I think that it will work just fine

**Comment by redmoogle** [comment]
> 
> 
> > To me the sprites feels out of place because it's too detailed compared to the rest of the game ~I love it though~
> 
> > The artstyle doesn't fit our current one but it looks fucking amazing
> 
> I think it fits way better then some other sprites that are in this game. Not to mention how amazing it looks. I think that it will work just fine

I think it would look better if stuff got a visual detail overhaul

**Comment by Partheo** [comment]
You'll get used to it, and before long you'll find it fits perfectly fine. Granted, I have been forced to stare at this TEG for a while now, but it looks super awesome in Eclipse's natural teg habitat. The 3/4 perspective helps it fit in much nicer than the old one, I believe.

image
image

The actual design of it is quite simple too, I don't think it's too detailed. The components are mostly just big chunks of metal, besides the turbine/heatsink bits on the circulators. The old teg is arguably more detailed.

**Comment by Partheo** [comment]
The TEG now has icon states for when the panel is open, and this now has consequences on the deconstruction steps.

The circulators can now be flipped with a crowbar.

image

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
