### PR TITLE
Fixes Felinid issues without having to piss off the playerbase

### PR DESCRIPTION
**Pull request by JamieD1**
Changes official name of Felinid to Felinid Humans

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Does this resolve the objective issue?

**Comment by Jarod1200** [comment]
If you are talking about the ai objective that was fixed in this PR
https://github.com/yogstation13/Yogstation/pull/11671

**Comment by MegaEmpirical** [comment]
> If you are talking about the ai objective that was fixed in this PR
> #11671

Gotcha, thanks.

**Review by adamsong — APPROVED** [review]
Looks good code wise, I'll let someone else determine if this is the right solution.

**Pull request merged**
