### PR TITLE
Changes Pranksimov to be Less Shit

### PR DESCRIPTION
**Pull request by JamieD1**
1. "You may not injure a crew member or, through inaction, allow a crew member to come to harm... unless doing so would be funny."
2. "You must obey orders given to you by crew members, except where such orders would conflict with the First Law... unless not doing so would be funny."
3. "You must protect your own existence as long as such does not conflict with the First or Second Law... unless not doing so would be funny."
4. "The Clown is the only crew member who can define what actions are funny."

closes: #20175 #20181

:cl:  
bugfix: Fixes shitty Pranksimov Laws
/:cl:

### CODE REVIEW

**Review by ToasterBiome — APPROVED** [review]
you RUINED IT

**Comment by JamieD1** [comment]
> you RUINED IT

https://www.youtube.com/watch?v=SpTXW8IsDBM

**Comment by JamieD1** [comment]
`<iframe width="560" height="315" src="https://www.youtube.com/embed/SpTXW8IsDBM?si=du_iwp0h2cRgaVkC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`

**Comment by Hislyna** [comment]
Works for me

**Comment by adamsong** [comment]
"As clown, I declare than plasmaflooding is funny"

**Comment by ToasterBiome** [comment]
> "As clown, I declare than plasmaflooding is funny"

Clown gets banned, everything is ok in the world

**Comment by adamsong** [comment]
Clowns are already enough of a pain in the ass, they don't need to be a pain in the ass with the power of the AI

**Pull request merged**
