### PR TITLE
ports makeshift laser from hippie (port)

### PR DESCRIPTION
**Pull request by boodaliboo**
https://github.com/HippieStation/HippieStation/pull/12366 original pr not much info given on original pr so heres its item descrption
this item is only available with the traitor makeshift items 101 book
:cl:  
rscadd: ports makeshift laser
imageadd: ports makeshift laser sprite   
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
pewpew unga

**Comment by Ktlwjec1** [comment]
what if this was added to /obj/item/book/granter/crafting_recipe/weapons just a medium brain idea

**Comment by boodaliboo** [comment]
> what if this was added to /obj/item/book/granter/crafting_recipe/weapons just a medium brain idea

ok i like that idea

**Review by Hopekz — CHANGES_REQUESTED** [review]
Your gun is literally the only gun in our codebase that is facing the wrong way.
For consistency going to have to ask you to flip the sprite.

image

**Review by Hopekz — APPROVED** [review]

**Review by alexkar598 — CHANGES_REQUESTED** [review]
additional arms + dual weilding = free instant 100damage kills, haha, no.

Too overpowered, nerf it or close it

**Comment by Hopekz** [comment]
> additional arms + dual weilding = free instant 100damage kills, haha, no.
> 
> Too overpowered, nerf it or close it

What? Literally any laser rifles in the game and every ranged weapon you can buy do the same thing if you buy additional arms.
How is your strat specific to this weapon?

**Comment by alexkar598** [comment]
That would require breaking in the armoury, this you can sit in maint for a few minutes and you are a death machine

**Comment by boodaliboo** [comment]
> That would require breaking in the armoury, this you can sit in maint for a few minutes and you are a death machine

that is frankly ridiculous because first of all this costs 4tc to even get and arms cost 5 tc so at most you can do 75 damage, and whats stopping someone from doing this exact same thing with stechkins or pkas or plasmacutters

**Comment by boodaliboo** [comment]
and what do you even want changed

**Comment by Hopekz** [comment]
> That would require breaking in the armoury, this you can sit in maint for a few minutes and you are a death machine

Sounds like a creative strat.
Currently traitors can just buy a revolver or whatever other gun to be a "death machine"
If someone wants to do this wacky arm strat I think it should be encouraged especially for traitors. I can see this being an issue if done with non antagonists somehow but I can't see the issue at the moment with syndicates vs the tools they already have access to round start with the TC they start with.

If we are tackling this problem I think it should be addressed in the multiple arms so they can't all fire at once instead of in this weapon being weaker just in-case someone uses that strat if it is decided that it isn't something that is wanted

**Comment by alexkar598** [comment]
Just drop the damage to something like 15, still a powerful weapon but not an instant win

**Comment by boodaliboo** [comment]
lowered max damage from 25 to 17

**Pull request merged**
