### PR TITLE
Revert "Handcuffed people may no longer just walk through turnstiles"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#13952

Lets allow this to get some more opinions yeah? 
3v3 isn't exactly decisive

### CODE REVIEW

**Comment by maxion12345** [comment]
turnstiles, like airlocks, only care about scanning that ID card and not if you have handcuffs

that being said having new handcuff types sounds fun
shock cuffs that zap you if you walk away from the person who placed them, gps tracking cuffs, strong cuffs, etc

**Comment by NCRLouTenant** [comment]
> turnstiles, like airlocks, only care about scanning that ID card and not if you have handcuffs
> 
> that being said having new handcuff types sounds fun shock cuffs that zap you if you walk away from the person who placed them, gps tracking cuffs, strong cuffs, etc

I completely agree with this.  Making those cuffs locked behind a research node would also add to that choice of what to spend points on, with sec having to try to convince Sci that it's the most important thing to do.  

Would definitely be more interested in it being related to the cuffs instead of just making handcuffs lock turnstiles, but again, that's a personal opinion based on the way I play.

**Comment by patpol4** [comment]
Good Bibby PR, i don't say this often so you know it's serious.

**Comment by maxion12345** [comment]
turnstiles are meant to be pushed through with your body

if you use your hands then your body is weak and you need to git gud on the turnstile because that is unsanitary

**Comment by JamieD1** [comment]
This is fixing a oversight in the original PR, No.

**Pull request closed without merging**
