### PR TITLE
Donator End-Round Item

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Donators can now choose any item from any uplink (as long as it's 20TC or lower) to have spawned on them when the round ends

image

# Changelog

:cl:  
rscadd: Donators can now choose an item from the uplink to spawn with when the round ends
/:cl:

### CODE REVIEW

**Comment by MortimerTMorose** [comment]
I support this wholeheartedly and am in no way biased

**Comment by DylonBR** [comment]
EORG pay to win

**Comment by Moltijoe** [comment]
Hello? Based department?

**Comment by Chubbygummibear** [comment]
reminds me of the community tf2 servers where if you're a donator you're just invincible during the end of round where the winning team kills the losing team because people with money are better than the poors

**Comment by MajManatee** [comment]
Secretly a buff to encourage people to try and stay alive to the end of the shift, rather than giving their life for some nonsense reason, or just to try to make someone red text.

**Comment by neeshacark** [comment]
an interesting idea

will get shot down by Xantam calling it now

**Comment by ynot01** [comment]
> an interesting idea
> 
> will get shot down by Xantam calling it now

he approved it

**Comment by MajManatee** [comment]
Any way to make it like a button you can press that appears only once the round ends, as opposed to it just sort of appearing in your hand?

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
