### PR TITLE
Nuclear Apocalypse: Metro Starter Pack

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
Probably does not fit, adds an area you can use for mapping that requires people to wear a special gas mask. The gas mask needs a filter that slowly degrades.
A flashlight that requires a battery, loses brightness when its close to running out of juice.
An admin only spawner for fun times.

:cl:  
rscadd: Added a battery powered admin only flashight
rscadd: Added a gasmask+filter for admin fun
rscadd: Added an admin only spawner for fun things
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
*heavy breathing*

**Comment by Bibby0110** [comment]
Imagine being overshadowed by a preternis PR

**Comment by alexkar598** [comment]
Imagine realizing preternis are better

**Comment by Bibby0110** [comment]
haha guess what

**Comment by Bibby0110** [comment]
@nichlas0010 is bad

**Comment by Amelia0010** [comment]
:(

**Pull request closed without merging**
