### PR TITLE
Nanite Extra Setting UI Bugfix

### PR DESCRIPTION
**Pull request by GilbertEGomez**
:cl: 13gome0220
bugfix: fixed every single Programmable Nanite which did not show or allow you to edit values for their extra settings in the Nanite Programmer Machine. Like "send code" or "sentence" for voice sensor. Now you can finally customize nanites to their full potential!

wip: Nanite Cloud Controllers still won't show the edited values for extra settings. Still investigating to see if I can find a fix for this. Don't worry, the changes will still apply for the Nanite programs even though it won't show the extra settings in the cloud.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Ooof.....


Already fixed in https://github.com/yogstation13/Yogstation/pull/8912

**Comment by GilbertEGomez** [comment]
> Ooof.....
> 
> Already fixed in #8912

Smh... Did you fix nanite cloud controllers too?

**Comment by Bibby0110** [comment]
Depends on what the problem is with the nanite cloud controllers

**Comment by GilbertEGomez** [comment]
> Depends on what the problem is with the nanite cloud controllers

They do not show extra settings either like nanite programmer.

**Comment by JamieD1** [comment]
Fixed in #8963 Thanks for helping 13gome0220

**Pull request closed without merging**
