### PR TITLE
gives ashwalkers a bamboo seed

### PR DESCRIPTION
**Pull request by boodaliboo**
gives ashwalkers more variety in possible weapons allowing them to make blowguns and spears
#### Changelog

:cl:  
rscadd: Added bamboo seeds to ashwalker ruin
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
where would they get syringes/darts from? I don't think they're craftable

**Comment by boodaliboo** [comment]
> where would they get syringes/darts from? I don't think they're craftable

they can make 5 unit syringes with bamboo

**Review by patpol4 — APPROVED** [review]
Map technically fine, no idea about the balance implications of this, what is the goal here?

**Comment by boodaliboo** [comment]
> Map technically fine, no idea about the balance implications of this, what is the goal here?

make them more tribal and allowing them to do tribal things like blowguns and stuff

**Pull request merged**
