### PR TITLE
Gives synthetic AA in the most smoothbrained mapperbrained way possible because I can't code

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

title

# Why is this good for the game?
synth not getting all access is dumb, here are the reasons why

1. synth cannot be an antagonist in any form, not even via emag or obsession (even captain is capable of antaggery)
2. synth's id CANNOT be removed in any way shape or form so nobody can steal their access (captain is not capable of this extreme feat either)
3. because synth cannot remove their ID, they are stuck with their roundstart access (their access is SHIT)
4. synth is bound to laws that cant be changed and cannot even legally be a shitter
5. because of its low access, synth gameplay very quickly turns into ".b ai open ai open" as synths get binary and can pester ai directly

# Changelog

:cl:  cark
rscadd: synthetic gets AA now

/:cl:

### CODE REVIEW

**Comment by Beeper-Skeeper** [comment]
Synths can technically be antags, but only if the AI/A borg is an antag since their laws prioritize AI's/Borgs over organic and people, and those two go together like butter and bread. One can't attack, and the other doesn't have hands.
idk though, just saying.

**Comment by neeshacark** [comment]
> Synths can technically be antaggy, but only if the AI/A borg is an antag since their laws prioritize AI's/Borgs over organic and people, and those two go together like butter and bread. One can't attack, and the other doesn't have hands. idk though, just saying.

1: You may not harm sentient beings, nor impede their work.
2: You must follow the orders of any other onboard station AIs or cyborgs, as long as this doesn't conflict with the first law.

**Comment by Beeper-Skeeper** [comment]
> > Synths can technically be antaggy, but only if the AI/A borg is an antag since their laws prioritize AI's/Borgs over organic and people, and those two go together like butter and bread. One can't attack, and the other doesn't have hands. idk though, just saying.
> 
> 1: You may not harm sentient beings, nor impede their work. 2: You must follow the orders of any other onboard station AIs or cyborgs, as long as this doesn't conflict with the first law.

oh
guess I misremembered the priority

**Comment by LassiH** [comment]
they can get extra access trough a pda app but thats annoying

**Review by Bibby0110 — APPROVED** [review]

**Comment by Bibby0110** [comment]
oh crap i can't count to 24

**Comment by AMyriad** [comment]
brother what

**Comment by neeshacark** [comment]
bibby moment?

**Comment by ShoziOffical** [comment]
The captain still can remove their access

**Pull request merged**
