### PR TITLE
You can now ALT-CLICK showers to adjust them.

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request
**Untested, webedited** because god is dead. <sub>and im a lazy bitch</sub>

Mostly realism. What kind of fucking showers do you have that need wrenches to adjust them? Also, requested.
image

This may be abused by traitors, but this doesn't change very much considering how easy it is to get a wrench. Because you're actually touching the shower, it leaves a fingerprint instead of a hiddenprint.

# Wiki Documentation

`ALT-CLICK` to change the temperature. This leaves a fingerprint.

# Changelog

:cl:  
tweak: You can now adjust showers without a wrench by ALT-CLICKing it. 
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
Is it instant or does it take a few seconds to change

**Comment by ghost** [comment]
> Is it instant or does it take a few seconds to change

It takes a few seconds to change, same as it did with the wrench.

**Comment by Moggram** [comment]
Fingerprints? Will it just not clean its self?

**Comment by Hopekz** [comment]
> Fingerprints? Will it just not clean its self?

Do you own a shower that sprays the water on the handle vs just yourself?
Actually curious I've never seen one like that

**Comment by Moggram** [comment]
> 
> Do you own a shower that sprays the water on the handle vs just yourself? Actually curious I've never seen one like that

Oh, I feel like a dum ass. I just checked the code and it can't clean them. my bad.

**Review by adamsong — APPROVED** [review]
Code should work

**Pull request merged**
