### PR TITLE
Removes greentext and adds custom objective

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

The complaint about this last time was that there was no code changes to supplement it so I added custom objective and we're trying this again

Discourages the 'win' and gloating mindset
Discourages the validhunt/murderbone to 'win' and 'must redtext the traitor' mindsets
Encourages the addition of more creative and liberal objectives without worrying about how possible it is to track within code

Custom objective brings up a prompt
You input what you want and it tells the admins
From there the admins can decide if they want to approve it or not or discuss with you further about it.

# Changelog

:cl:  
rscadd: Added custom objectives
rscdel: Removed greentext
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
You really think letting people slap whatever text as their objective and then following it will work? what happens when this antag is bwoinked by an admin "why did you maxcap all of medbay, brig, and escape?" and they reply with "my objective is 'b cuben pete' lol"? You really think objectives like 'steal the Captain's medal", "Steal the nuclear disk", "Kill X" and all the other reasonable objectives are so bad that we need to just drop the whole system and just let whatever happens happens? Do you think this will do a single thing about the other gamemodes that have objectives and have problems with validhunting, like cults, gangs, shadowlings, darkthralls, etc? 

All i'm saying is that if this PR gets merged then I encourage players to set their objective as "Exterminate all lizards", or "Exterminate all humans" in the case of lizard mains.

This at BEST should be something that is added to the existing objectives, like you have the chance to spawn with a free objective that you can enter, rather than this being the only option.

**Comment by patpol4** [comment]
Great idea but needs to be supplemented by rules to babysit the players trying to circumvent current rules.

**Comment by ynot01** [comment]
> You really think letting people slap whatever text as their objective and then following it will work? what happens when this antag is bwoinked by an admin "why did you maxcap all of medbay, brig, and escape?" and they reply with "my objective is 'b cuben pete' lol"? You really think objectives like 'steal the Captain's medal", "Steal the nuclear disk", "Kill X" and all the other reasonable objectives are so bad that we need to just drop the whole system and just let whatever happens happens? Do you think this will do a single thing about the other gamemodes that have objectives and have problems with validhunting, like cults, gangs, shadowlings, darkthralls, etc?
> 
> All i'm saying is that if this PR gets merged then I encourage players to set their objective as "Exterminate all lizards", or "Exterminate all humans" in the case of lizard mains.
> 
> This at BEST should be something that is added to the existing objectives, like you have the chance to spawn with a free objective that you can enter, rather than this being the only option.

I should have explained better, the "custom objective" prompt lets you put in whatever you want and that is then sent to the online admins who then approve it or not. If the objective is overtly destructive or round ruining then it then lies on the admin and should be treated just as if they added the objective otherwise.

The objective doesn't trigger if there are no admins.

**Comment by Moja10** [comment]
Greentexting was never an issue, people want to complete objectives. This isn't a HighRP server where its purely based on 'muh narrative' or some shit, there is actual gameplay going on on Yogs that warrants actual mechanics to facilitate that gameplay, like measuring traitor success as a greentext or redtext. 

Not to mention that I think that the traitor objectives are some of the best designed antag objectives compared to the endless antags that are just "OBLIDERATE EVERYTHING........" A traitor with steal hypo kill chef plays completely differently than traitor with steal nuclear disk kill hos which plays completely differently than a traitor with die glorious or hijack. The objectives make the gamemode. 

I don't know what you expect with this either, Wej is right that literally a billion different rules and stipulations now need to be drafted and there's none. You expect this PR to be merged and then we deal with the shit after the fact? Or are we supposed to just draft rules like this is getting merged even though it's extremely cringe and shit? 

Custom objectives already can be made via admin abilities and most of the time, even with careful consideration and curation, it's not that easy at all to create custom objectives. There's barely a guideline for admins creating their own objectives for players, much less any guidelines for players creating their own objectives and then getting admins to approve/disapprove them.  

It'll all depend on mindset, if someone gives an reasonable custom objective, and an admin approves it, and later down the line it is used in a way that the admin didn't fully approve of, who is at fault here? The admin not considering all possible avenues of the objective or the player for doing something that the admin didn't consider in their purview? It's neither because it's not the goal of admins to specify "you can do X Y and Z with Objective "ERP the lizards" but you can't do 1 2 and 3 either" for literally every single traitor in every single round. It's also not the goal of players to have to memorize literally every possible thing for every possible custom objective possible especially since this is just going to cause massive headaches when they try to be creative at all in a good way, but an admin didn't approve so they catch a note/ban. 

Also this does really nothing about the win or lose mindset, that will still exist after these changes, this reminds me of playing TF2 with normal objectives to capture the intelligence 3 times, control all the CPs, defend the base within a timeframe, versus TF2 with meme objectives like capture the intelligence 300000 times, CP_highertower, base defense with 9999:99 time limit, aka just because you removed the ability to 'win' or 'lose' doesn't mean that the people playing the game aren't going to keep trying to 'win' or 'lose'. If an antag exists, it can be validhunted.

 Christ I don't even know what problems have been existing for this drastic of a change to even be warranted. 

EDIT: I rather puke than at the idea of getting 9 different meme objectives every traitor round and then having to sift through every single one going like "Okay you want to do X but you can't do Y" or "No, you can't do X but you can rephrase it as Y" or "Yes you can do X" but then the player actually ends up doing Y. What a literal fucking nightmare just because you couldn't handle how some players go "WOOOO GREENTEXT" at the end of the round after they stole a slime extract and killed a Botanist

**Comment by ynot01** [comment]
> Greentexting was never an issue, people want to complete objectives. This isn't a HighRP server where its purely based on 'muh narrative' or some shit, there is actual gameplay going on on Yogs that warrants actual mechanics to facilitate that gameplay, like measuring traitor success as a greentext or redtext.

I believe that the removal of greentext will supplement a mindset that will lead to more RP: security not instakilling a traitor because there's no gratifying redtext at the end; a traitor not instakilling the security team because there's no AAHH MUST GREENTEXT AAHHHHH

> Not to mention that I think that the traitor objectives are some of the best designed antag objectives compared to the endless antags that are just "OBLIDERATE EVERYTHING........" A traitor with steal hypo kill chef plays completely differently than traitor with steal nuclear disk kill hos which plays completely differently than a traitor with die glorious or hijack. The objectives make the gamemode.

I agree but I don't see how this discounts this PR

> I don't know what you expect with this either, Wej is right that literally a billion different rules and stipulations now need to be drafted and there's none. You expect this PR to be merged and then we deal with the shit after the fact? Or are we supposed to just draft rules like this is getting merged even though it's extremely cringe and shit?
>
> Custom objectives already can be made via admin abilities and most of the time, even with careful consideration and curation, it's not that easy at all to create custom objectives. There's barely a guideline for admins creating their own objectives for players, much less any guidelines for players creating their own objectives and then getting admins to approve/disapprove them.

The only drafting I can think of that would be necessary would be telling the admins not to approve retarded objectives, which shouldn't be an issue to begin with. Admins should know how to manage the round properly, and if they don't, that's an issue we need to deal with staff-side.

> It'll all depend on mindset, if someone gives an reasonable custom objective, and an admin approves it, and later down the line it is used in a way that the admin didn't fully approve of, who is at fault here? The admin not considering all possible avenues of the objective or the player for doing something that the admin didn't consider in their purview? It's neither because it's not the goal of admins to specify "you can do X Y and Z with Objective "ERP the lizards" but you can't do 1 2 and 3 either" for literally every single traitor in every single round. It's also not the goal of players to have to memorize literally every possible thing for every possible custom objective possible especially since this is just going to cause massive headaches when they try to be creative at all in a good way, but an admin didn't approve so they catch a note/ban.

We do run this risk with custom objectives, but shit happens. Same issue exists within prayers and chaplain RP. There's nothing saying that you have to approve an objective if you think it'll go poorly. The goal of it is to create an easier avenue to get gimmicky playstyles approved.

> Also this does really nothing about the win or lose mindset, that will still exist after these changes, this reminds me of playing TF2 with normal objectives to capture the intelligence 3 times, control all the CPs, defend the base within a timeframe, versus TF2 with meme objectives like capture the intelligence 300000 times, CP_highertower, base defense with 9999:99 time limit, aka just because you removed the ability to 'win' or 'lose' doesn't mean that the people playing the game aren't going to keep trying to 'win' or 'lose'. If an antag exists, it can be validhunted.

I have no guarantee for you or even myself that this will work in improving those mindsets, but I believe it is worth trying, and I believe that the cost of removing some roundend text is extremely minor compared to what could be accomplished.

> Christ I don't even know what problems have been existing for this drastic of a change to even be warranted.

You made a whole document trying to verbally persuade the playstyles of players. I'm not sure what is so "drastic" about this change to cause you to be so dramatic over it.

**Comment by ToasterBiome** [comment]
might as well remove antags completely if you’re gonna go this far

booooooring

the green text is the reward for doing your objectives, just seems like a party pooper move

Holy shit this literally removes the success and fail from your objectives at the results screen KEK 

I like the idea of custom objectives but it should pretty much function like a rare objective you can customize, supplemented by the regular objectives. If that was the only thing in the PR it would get a lot of approval

**Comment by maxion12345** [comment]
guess someone didn't get a greentext

anyways, removal of greentext and letting people chose their own objectives is stupid, because I know what i'd do with it

anyways, greentext is what makes tator fun. it certainly gives incentives to avoid security, do my shit stealth-like, and generally be the super badass space spy on a space station, and then everyone is shown my greentext for my effort :)

**Comment by LazennG** [comment]
not trying to be mean but this is a dumpsterfire of an idea

**Comment by Moggram** [comment]
Admins do alot of work as is. If they wanted to be a DM, then they would go play D&D.

**Comment by Hopekz** [comment]
I don't like this because redtext and greentext are a big defining part of the actual game itself. In my opinion this PR just kind of removes that iconic aspect without replacing it with something equally as good leaving us with something underwhelming

**Comment by Cartlord** [comment]
i thought this was a meme pr or something when i clicked the title
i am so disappointed

**Comment by Aquizit** [comment]
I appreciate what this pr is trying to do, but I don't think it's a thing that will work.

As I read it, it's trying to promote more free-form RP. Not a bad thing really, but I still don't really see that working here. We struggle to even claim to be MRP sometimes, and actually having RP objectives limited only by imagination and RP is more of an HRP thing overall, to me, at least. There still needs to be some structure for MRP I think.

Also this will never fly as long as the RP identity is still so ridiculously nebulous.

Get the players and staff on the same page then look at mechanics.

Or just admit we are LRP. I wish it weren't so but I can't even pretend anymore.

**Comment by adamsong** [comment]
This idea has been proposed more than once, it has been rejected every time. Additionally, the removal of specifically the end of round 'you succeed' or 'you didn't' isn't going to remove the win/lose mindset from the game, people will still discuss it, and internally make note of if they have or have not completed all their objectives. This also prevents the last second loss (assassinate cloned in secret) or accidental win (assassinate died unrelated) which is an interesting aspect of the gamemode.

This has been stale for a while, with overwhelming negative reviews, closing.

**Pull request closed without merging**
