### PR TITLE
REAGENT STATES, NEW CHEMS, FORGE STUFF MY GOD SO MUCH THINGS WHATS A MAP MERGE CONFLICT EDITION!

### PR DESCRIPTION
**Pull request by fluffe9911**
CREDITS: Fluffe9911 for porting, banthebantz for coding all this amazing stuff (like holy cow), GuyonBroadway for fixing bans original Reagent Material PR, yoyobatty for maintaining it so its not broken as heck and Jujumatic for the neat fire extinguisher rewrite/mutation toxins please tell me if I missed anyone

🆑 A ton of cool guys
add: Reagent States!
add: New Chems!
add: Reagent Forge to make custom weapons and things!
add: Alot of other things that would be to much to list in here!
/🆑

This is a huge port that ports many things in the goal of getting the reagent forge to be a thing. To see whats in it look at these prs
HippieStation/HippieStation#5756
HippieStation/HippieStation#3480
HippieStation/HippieStation#3043
HippieStation/HippieStation#7670
HippieStation/HippieStation#7357

### CODE REVIEW

**Comment by Ktlwjec** [comment]
the room above surgery is ugly i dont like it

**Comment by fluffe9911** [comment]
Eh its simple and serves its purpose up to ideas to improve it though

**Comment by ThatLing** [comment]
what does this even do

**Comment by k-k-karma** [comment]
can you fucking dont

**Comment by Amelia0010** [comment]
I'll just say that I'm adamantly against this, but that @ThatLing can decide, since I don't play anyways :)

**Comment by Manly-Dwarf** [comment]
Reagent Forge is very easily abused to create exceedingly powerful weapons and reagent states can cause a myriad of issues, particularly with crashing the server.
If you're just going to port it then you may as well be prepared for the classic methsmoke recipe, Neurotoxin daggers, breaking the SM, etc.

**Comment by fluffe9911** [comment]
Can we have a test merge to see if this ends up being bad or not?

@ThatLing please read the description and linked prs

Edit also neurotoxin got made to no longer stun by adam and methsmoke got nerfed on hippie (thus ported here) so shouldnt crash the server

Edit Edit also tgui works fine as far as I can tell in my testing

**Comment by yoyobatty** [comment]
They fell for the forge meme guys.

**Comment by fluffe9911** [comment]
heck I been bamboozled

**Comment by ThatLing** [comment]
Hippiestation came to my door and threatened to boil my eyebrows if I merged this

**Comment by fluffe9911** [comment]
eh fair enough

**Pull request closed without merging**
