### PR TITLE
CNS Rebooter 12TC ->4TC

### PR DESCRIPTION
**Pull request by Burger1998**
# Document the changes in your pull request
A STATION AVAILABLE IMPLANT FOR 12TC WHAT WERE WE THINKING CUT THAT SHIT TO 4TC.

# Wiki Documentation
change price on https://wiki.yogstation.net/wiki/Syndicate_Items#Implants to reflect change.

# Changelog
:cl:  
tweak: CNS REBOOTER WAS 12TC NOW ITS 4TC RIP THE GENE WHO GOT SCAMMED BY HIS BOSS
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
just get the reusable implanter for one more TC and save yourself a lot of time and trouble

**Comment by Rdrazga** [comment]
You know you could make the traitor version better then the regular one like offering even lower stun times or not being empable like the normal one

**Comment by 00ze-cyclone** [comment]
An example of why putting crew shit in uplink is a bad idea.

**Comment by Burger1998** [comment]
> You know you could make the traitor version better then the regular one like offering even lower stun times or not being empable like the normal one

**Comment by Burger1998** [comment]
alright i actually really like that idea so im gonna try to replace the item cheers

**Pull request closed without merging**
