### PR TITLE
Aspergillum and Aspersorium

### PR DESCRIPTION
**Pull request by Moltijoe**
Sorta works like a fire extinguisher, but instead uses holy water

https://github.com/yogstation13/Yogstation/assets/108117184/a7b0b2bb-0846-4adf-be8d-45efdca39907

# Why is this good for the game?
adds another nullrod option that's a bit more unusual compared to what we currently have

thanks to @Scrambledeggs00 for the sprites
image
image

:cl:  @Moltijoe @Scrambledeggs00 
rscadd: Adds new nullrod, aspergillum and aspersorium
soundadd: Sprites for aspergillum and aspersorium
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
what does it do

**Comment by iloveloopers** [comment]
power washing machine?

**Review by SapphicOverload — CHANGES_REQUESTED** [review]
Could you include in your PR what it actually does?

**Comment by Moltijoe** [comment]
> Could you include in your PR what it actually does?

working on it, i'm suddenly finding so much to nit pick about the particle effect movement

**Comment by MajManatee** [comment]
Damn those particle effects got hands

**Review by cuackles — APPROVED** [review]

**Comment by LassiH** [comment]
will this bless tiles the water goes on ?

**Comment by Moltijoe** [comment]
> will this bless tiles the water goes on ?

nope

**Comment by MajManatee** [comment]
still doesnt say what it does

**Comment by Moltijoe** [comment]
> still doesnt say what it does

this just in, local man is blind
image

**Review by SapphicOverload — APPROVED** [review]

**Pull request merged**
