### PR TITLE
Grandpa Koko now flies in on a wheelchair on round start pod station trait

### PR DESCRIPTION
**Pull request by JamieD1**
Grandpa Koko now flies in on a wheelchair on round start pod station trait

Paraplegic people now get a wheelchair on the pod station trait

:cl:  
rscadd: Paraplegic people now get a wheelchair on the pod station trait
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
but
i hate cripples

**Comment by ToasterBiome** [comment]
Does this... work?

**Comment by JamieD1** [comment]
> Does this... work?

Dunno, will test at some point. Cool idea though innit

**Comment by JamieD1** [comment]
Dont you stale me

**Comment by Bibby0110** [comment]
stale

**Pull request closed without merging**
