### PR TITLE
BEPIS port from tg

### PR DESCRIPTION
**Pull request by boodaliboo**
quote from the original pr https://github.com/tgstation/tgstation/pull/48040
"This is ArcaneMusic's feature number 2 designed to force you to squirrel out your hard earned cash in a round in a constant effort to give money real value within a round. All values here are tentative, up for discussion, and right now are meant to give a vastly higher value payout at higher levels, subject to a degree of random chance.

About The Pull Request
The BEPIS, what is it, and how does it work?
I'm glad you asked! The BEPIS, or Business Exploration Protocol Incubation Sink, is a machine meant to sit nestled right next to the E.X.P.E.R.I-MENTOR in science. Think of the two machines as brother and sister, actually. If the E.X.P.E.R.I-MENTOR uses brute force methods to discern the nature of objects and phenomena, then the B.E.P.I.S. takes a gentler approach, by committing tons of resources to the problem so that someone else will either figure it out, or give you an excuse to fire them.
image
The B.E.P.I.S. and 6 of it's possible, beneficial rewards.

Specifically, the B.E.P.I.S. runs off of 2 main resources, Money, in all its shapes and sizes, and Electricity, which during a long shift are the two things the station should have in DROVES. How the machinery works is you begin by inserting money into the machine, for example, 7000 credits. Then, based on Gaussian distributions, your investment will either increase in value due to it having research merit, or fall due to being an exceptionally terrible idea but hey, you're the one funding it so whatever. If you pass either the major or minor threshold, the B.E.P.I.S. will produce either individual products, or technology disks allowing you to reveal new techs within the tech tree.

THE TECHS TO BE ADDED TO THE TREE ARE NOT INTENDED TO BLOCK OFF OLD, EXISTING TECHS.
It's JUST for interesting, but otherwise not irreplaceable items that serve as a fun mid-end game tech tree additions.
If you obtain a Major Investment threshold, right now the only prize is a tech disk containing the Illumination Applications, which is unlocked via the deconstruction analyzer, allowing access to a smaller version of the RLD and a new, upgraded version of the fire helmet.
The Minor Investment threshold rewards include a new way of painting on decals onto floor tiles, the Decal Painter (The blue airlock painter), and the Polycircuit Aggregate, which acts as a functional adaptive psudocircuit which if interrupted will slice you up because it's a nightmare of circuits thrown together into a mess.

In the off chance you don't meet either threshold, you'll get a funny reason for why your venture capitol project didn't pan out. It pays to invest deeply, if your goal is to get a reward.
In the even more unlikely chance that you not only don't meet either threshold, but you somehow LOSE money in the process, The machine will malfunction, and cause a power surge, burning through a lot of power in the APC. Also something about bucks?
image
Breakdown of the UI and the variables on the bottom of the screen.
Deposited Credits: Money currently being risked by testing.
Investment Variability: How wide of a margin your money can fluctuate both positively and negatively. Upgrading makes your investment more consistent.
Innovation Bonus: Provides a static bonus to the value of any test.
Risk offset: Decreases the cost of both the Minor and Major reward linearly.
Average Technology Cost: The mean, raw value needed to obtain a new tech disk. NOTE: Because this uses Gaussian distribution, this is the point where your odds are 50% even, NOT guaranteed.

Quick aside, I also wound up running into an issue that Skoglol helped me out with, turns out that the copy_research_to proc was written in a way so that it only really added the tech and the designs from a disk if you uploaded the tech twice, so that's been re-ordered to future-proof that for the next time hidden nodes get added.

Why It's Good For The Game
This has been an idea I've been dreaming up for awhile now, with three expressed goals:
A.) Give the Science Budget something to spend they money towards.
B.) Create a Money Sink in the Science department, which fits with the theme of NT being absolutely nuts about their bottom line and making a profit.
C.) Give an excuse for there to be more diverse methods of gaining hidden tech nodes within a single round.
At least until someone makes a way for heads to buy crates straight from their department budget within their own department, I'll consider this a win in terms of A and B. This also at least lays the groundwork for C, as other people will be free to add more minor and major rewards and techs.

To-Do List:
 Add the basic functionality.
 Add at least one major, and one minor reward for using the B.E.P.I.S.
 Set up an easy framework for being able to add new methods of unlocking new, blocked techs. (Close enough for now.)
 Set up machine upgrades to improve odds/Show odds of success (Ugh, MATH).
 Maybe add another tech/ a few extra minor rewards.
 Add the B.E.P.I.S. to all or most map's RnD departments.
 Bucks?"
Changelog
🆑
add: The RnD department has been gifted a state-of-the-art new research tool, the B.E.P.I.S. by Nanotrasen's Venture Capital Labs, after repeatedly wasting all of their funds. Hopefully you'll find a... wiser use for it.
add: A new Tech Node can be unlocked through proper investment with the B.E.P.I.S.
add: In an unrelated piece of news, a deer was recently found to be the culprit of Nanotrasen Venture Capital Labs's onboard nuclear failsafe device detonating. Yes, we're sure it wasn't the Syndicate this time. Yes, we wish we were joking too.
fix: Fixes a small bug with tech disks containing hidden nodes not researching.
/🆑

### CODE REVIEW

**Comment by boodaliboo** [comment]
im to tired to fix any possible travis errors please help

**Comment by monster860** [comment]
that's a whole lot of "Add files via upload". Maybe you need to learn how to git.

**Comment by boodaliboo** [comment]
> that's a whole lot of "Add files via upload". Maybe you need to learn how to git.

i know how to use git and i have a git client i just dont like to use it as i mainly code when not at home and git is not available

**Comment by boodaliboo** [comment]
> > that's a whole lot of "Add files via upload". Maybe you need to learn how to git.
> 
> i know how to use git and i have a git client i just dont like to use it as i mainly code when not at home and git is not available

and all the added files are icons

**Comment by Ktlwjec1** [comment]
nice stormtrooper helmets

**Comment by Krysonism** [comment]
the BEPIS has loads of pending additions on the tg github you can take a look at when considering if this is something for your codebase.

**Comment by boodaliboo** [comment]
> nice stormtrooper helmets

loser

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Just fucking fix your shit, im not even touching this PR before its a clean branch

**Comment by boodaliboo** [comment]
> Just fucking fix your shit, im not even touching this PR before its a clean branch
going to you loser

**Comment by boodaliboo** [comment]
dont have the motivation to continue this currently

**Pull request closed without merging**
