### PR TITLE
[WIP] Mentor Event

### PR DESCRIPTION
**Pull request by ghost**
This is a test.

### CODE REVIEW

**Comment by athena413** [comment]
what is this

**Comment by Readystorm546** [comment]
> what is this

A test

**Comment by ghost** [comment]
>Mapbot works
>Compile test fails because the testing server crashed instead

Okay Turdis

**Comment by patpol4** [comment]
Just ping me when the map is out of the wip phase and when you need a review

**Comment by patpol4** [comment]
@AutisticFroggy is this going anywhere?

**Comment by ghost** [comment]
We're waiting on sprites

**Comment by ghost** [comment]
Archived until further interest pops up.

**Pull request closed without merging**
