### PR TITLE
Makes scrubber event less laggy

### PR DESCRIPTION
**Pull request by Mqiib**
It has a 1/3 chance of spawning 3 cockroaches PER SCRUBBER. There are a lot of scrubbers. This causes unneeded lag, and who's gonna miss the cockroaches anyways?

# Wiki Documentation

Scrubber event no longer spawns cockroaches.

# Changelog

:cl:  

rscdel: Removes cockroach spawns from scrubber event to reduce the lag

/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
> It has a 1/3 chance of spawning 3 cockroaches PER SCRUBBER. There are a lot of scrubbers. This causes unneeded lag, and who's gonna miss the cockroaches anyways?

In what world would this have _relevant_ performance impact. I mean the change is fine itself but I doubt this will have a noticeable effect other than AIs no longer hearing turret noises.

**Comment by VaelophisNyx** [comment]
> > It has a 1/3 chance of spawning 3 cockroaches PER SCRUBBER. There are a lot of scrubbers. This causes unneeded lag, and who's gonna miss the cockroaches anyways?
> 
> In what world would this have _relevant_ performance impact. I mean the change is fine itself but I doubt this will have a noticeable effect other than AIs no longer hearing turret noises.

depending on RNG this can have an absolute fuckton of roaches spawning, and more simplemobs pathfinding adds up fast

**Comment by redmoogle** [comment]
> > > It has a 1/3 chance of spawning 3 cockroaches PER SCRUBBER. There are a lot of scrubbers. This causes unneeded lag, and who's gonna miss the cockroaches anyways?
> > 
> > In what world would this have _relevant_ performance impact. I mean the change is fine itself but I doubt this will have a noticeable effect other than AIs no longer hearing turret noises.
> 
> depending on RNG this can have an absolute fuckton of roaches spawning, and more simplemobs pathfinding adds up fast

They dont path they just randomly move

**Comment by Mqiib** [comment]
> > > It has a 1/3 chance of spawning 3 cockroaches PER SCRUBBER. There are a lot of scrubbers. This causes unneeded lag, and who's gonna miss the cockroaches anyways?
> > 
> > 
> > In what world would this have _relevant_ performance impact. I mean the change is fine itself but I doubt this will have a noticeable effect other than AIs no longer hearing turret noises.
> 
> depending on RNG this can have an absolute fuckton of roaches spawning, and more simplemobs pathfinding adds up fast

Go count the number of scrubbers on the station and on average that's how many cockroaches it'll spawn. Spoiler: the answer is a metric fuck ton of extra mobs that the game is processing.

**Review by KillerOrcaCora — APPROVED** [review]

**Pull request merged**
