### PR TITLE
Revert "Adds a new round end sound"

### PR DESCRIPTION
**Pull request by JamieD1**
Reverts yogstation13/Yogstation#9698

### CODE REVIEW

**Review by Partheo — APPROVED** [review]
bruh

**Comment by Moggram** [comment]
Z7HeRxU

**Comment by patpol4** [comment]
why though

**Comment by Tipy1802** [comment]
What’s the problem with it? Considering you yourself merged it the first time then it isn’t the sound itself. Did it break something or is it too low quality? Sorry for being annoying but I hate it when people don’t state the reasoning behind their pr

**Comment by UselessTheremin** [comment]
It is funny, please do not remove it

**Comment by alao3alao3** [comment]
don’t act like it can’t be disliked lmao, people just don’t like that round end sound.

**Comment by JamieD1** [comment]
For one I did not get approval from partheo before merging it, two its controversial, three: dunno but there is always a three.

**Pull request merged**
