### PR TITLE
Adds a Clown Restaurant

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request
Adds a new map template `restaurant`

Thought about making this a admin only spawn too or an event
Would like feedback from staff due to it having a ghost beacon

Anyways

Adds a new ship that contains a **ghost beacon**
It contains a hydroponics, kitchen, and dining area

68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3132303936363333362f31383238313936333732372f612f5f6d6170735f73687574746c65735f726573747572616e745f63

# Why is this good for the game?
Allows for a little more variation in the rounds when da clown gang rolls up

# Testing
Made sure it actually spawns in correctly

# Wiki Documentation
New Page: Clown Restaurant 

# Changelog

:cl:  
rscadd: Clown Restaurant
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Restaurant

**Comment by Addust** [comment]
could give it a more unique hull

since its clown-based could give it bananium

**Comment by redmoogle** [comment]
> could give it a more unique hull
> 
> since its clown-based could give it bananium

my eyes were bleeding I want it to not look like eye vomit

**Comment by neeshacark** [comment]
this isn't very fitting as a whiteship tbh - it uses the generic eshuttle frame.  i would prefer it as an emergency shuttle if you want to keep it as it currently looks

**Comment by MajManatee** [comment]
Its not white, theres nothing clown-y about it.

**Comment by redmoogle** [comment]
> this isn't very fitting as a whiteship tbh - it uses the generic eshuttle frame.  i would prefer it as an emergency shuttle if you want to keep it as it currently looks

The design came out like that

**Comment by Necrosium** [comment]
Restaurant ship would work as an emergency shuttle, looking forward to testing this

**Comment by redmoogle** [comment]
> Restaurant ship would work as an emergency shuttle, looking forward to testing this

it would not. am I am not doing that

**Comment by Necrosium** [comment]
> > Restaurant ship would work as an emergency shuttle, looking forward to testing this
> 
> it would not. am I am not doing that

Why not? We have a bar shuttle, a kitchen one would defo work as well (without the beacon but yeah)

**Comment by redmoogle** [comment]
> > > Restaurant ship would work as an emergency shuttle, looking forward to testing this
> > 
> > 
> > it would not. am I am not doing that
> 
> Why not? We have a bar shuttle, a kitchen one would defo work as well (without the beacin but yeah)

Because I don't want to do that???? I want something to spawn in the round when everything isnt fucked

**Comment by Necrosium** [comment]
> > > > Restaurant ship would work as an emergency shuttle, looking forward to testing this
> > > 
> > > 
> > > it would not. am I am not doing that
> > 
> > Why not? We have a bar shuttle, a kitchen one would defo work as well (without the beacin but yeah)
> 
> Because I don't want to do that???? I want something to spawn in the round when everything isnt fucked

Yeah you dont get my point, whatever

**Review by MajManatee — COMMENTED** [review]
not white. would be cool as a shuttle.

**Review by neeshacark — COMMENTED** [review]
I'm with manatee, I think whiteships have a certain aesthetic to them.  The current ones all have the following features

> unique hull/shape
> are often dirty/unkempt
> arguably save the ufo, (debatable) are all grounded in realism

without these features this being a whiteship doesnt fit to me

**Comment by redmoogle** [comment]
> I'm with manatee, I think whiteships have a certain aesthetic to them.  The current ones all have the following features
> 
> > unique hull/shape
> > are often dirty/unkempt
> > arguably save the ufo, (debatable) are all grounded in realism
> 
> without these features this being a whiteship doesnt fit to me

Just using the whiteship as a template will split it off in day or two

**Comment by MajManatee** [comment]
well now it looks like a whiteship but you removed the whiteship part from the title?

**Comment by redmoogle** [comment]
> well now it looks like a whiteship but you removed the whiteship part from the title?

Is that important

**Comment by MajManatee** [comment]
No its just weird.

**Review by ynot01 — CHANGES_REQUESTED** [review]
Test it and make sure it can dock and stuff

**Comment by redmoogle** [comment]
> Test it and make sure it can dock and stuff

I did i actually found out it was too big this way. Need to have the docking port runtime when the ship is too big

**Review by neeshacark — CHANGES_REQUESTED** [review]
Still not the biggest fan of this conceptually, not sure if I like putting a ghost beacon with such easy access to the station - even if they cant physically leave the ship.

image These doors here lack firelocks

image Replace the booths here with the end variants of the booth booth/end_left and booth/end_right.  Additionally, the atmos pipes here are scuffed, consolidate them onto one tile.

image The pipe manifolds at the bottom do not connect to anything, also remove the pipes running under the tables and oven.  it makes them difficult to fix 

image Portions of the ship are not designated as the right area, and the circled portion in this image is designated as a bar when its not

**Comment by Moja10** [comment]
There's literally a bananium clown ship ruin that's made out of bananium, just get a bozo to make actual 45 degree sprites and it'll look 1000% better that it would with existing bananium tiles and definitely better than just using white shuttle walls.

**Comment by Moja10** [comment]
Also bananium windows be a thing... even those replacing all glass windows would be 10x better

**Comment by Moltijoe** [comment]
Balance Council:
>Probably not a good idea to have a ghost beacon in an area that can get unusually close to the regular play area

crypods that have clowns with the teleport implant (same thing as the gas station employee) would be safer
but honestly, i like the chaos that FAR too many clowns in one kitchen could create, so i personally don't entirely agree
hold out a bit on making any changes and i'll see if i can change minds

**Comment by ToasterBiome** [comment]
Reopen when upstream/master is merged into this and work continues.

**Comment by redmoogle** [comment]
> Reopen when upstream/master is merged into this and work continues.

Tbf balance council basically said no. I'm not going to work on it unless theres a possible solution

**Comment by ToasterBiome** [comment]
> > Reopen when upstream/master is merged into this and work continues.
> 
> Tbf balance council basically said no. I'm not going to work on it unless theres a possible solution

either remove the capability for it to interact with people in round or remove the ghost beacon, those are really the two options.

**Pull request closed without merging**
