### PR TITLE
[BOUNTY] Fixes felinid tails

### PR DESCRIPTION
**Pull request by alexkar598**
Yay!

https://forums.yogstation.net/index.php?threads/5-00-fix-missing-felinid-tail-sprite.20561/#post-175188

### CODE REVIEW

**Comment by alexkar598** [comment]
Stop downvoting a fix you pieces of shit

**Comment by MegaEmpirical** [comment]
Down voted because players shouldn't be paying to fix donator features.

**Comment by Hopekz** [comment]
> Down voted because players shouldn't be paying to fix donator features.

Well, who else is going to do it?
Don't downvote a fix just because server leadership has a counter-intuitive system for bounties.
The PR itself is good. It fixes the issue.

If players don't take initiative nothing will get done under our current system.
Instead of down-voting a good PR that works you should probably be taking this up with whoever created our bounty system as it is clearly not working as intended (if we even actually have a system in the first place)

**Comment by MegaEmpirical** [comment]
Head coders and/or council.

**Comment by Hopekz** [comment]
> Head coders and/or council.

Odd.
Don't remember seeing a bugfix bounty by them.
The last thing I remember is the bug raffle.

**Comment by alexkar598** [comment]
This is a private player funded bounty. The fact they have to pay for their paid features to be fixed is unfortunate but it has to be done as I can't really see the council forcing someone to code and since we have no way to reward coders who fixes stuff, what we get is a bunch of small features that don't really add anything to the game if it is even noticable and no bug fixes because noone likes to do that(except me lol, i do bug fixes sometimes and i fix 5-6 issues at once but im unique and noone likes me)

**Comment by LoliconSlayer** [comment]
Where's the fetish content label

**Review by Ktlwjec1 — APPROVED** [review]

**Comment by Sniblet** [comment]
This has not in fact fixed the issue
Reproduction:
-Be felinid
-Use reviving stasis

**Comment by Hopekz** [comment]
> This has not in fact fixed the issue Reproduction: -Be felinid -Use reviving stasis

Dude it's been 2 years odds are someone broke it again

**Comment by Sniblet** [comment]
I’m on a necroposting spree and no amount of being wrong will stop me

**Comment by alexkar598** [comment]
gtfo of my pr

**Pull request merged**
