### PR TITLE
Clerk Variations for metastation and Box

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Depends on #20281

As title, uses the station variations from that pr and adds them to Meta. Meta's shop is also added as a new variation.
Makes some modifications to the old ones to keep them more consistent, removes the south connection to atmos/wiring and now only uses the top connection.

image
image

# Why is this good for the game?
Allows any clerk store to be used on Meta

# Testing
Works fine
image

# Changelog
:cl:  
mapping: Icemeta uses box's clerk variation
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Sick

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
decals r fucked

**Comment by azzzertyy** [comment]
> decals r fucked

mapdiff moment

**Comment by azzzertyy** [comment]
> decals r fucked

unless you mean the command decals south of the spawner which i have no idea what to do with they have varying door positions

**Comment by N3D6** [comment]
> > decals r fucked
> 
> unless you mean the command decals south of the spawner which i have no idea what to do with they have varying door positions

Jut the landmark out another tile and do that specific section of decals specific to how the template is, you might have to make a special subtype of templates for meta

**Comment by azzzertyy** [comment]
> > > decals r fucked
> > 
> > 
> > unless you mean the command decals south of the spawner which i have no idea what to do with they have varying door positions
> 
> Jut the landmark out another tile and do that specific section of decals specific to how the template is, you might have to make a special subtype of templates for meta

thats lame and cringe though for decals alone

**Comment by N3D6** [comment]
> > > > decals r fucked
> > > 
> > > 
> > > unless you mean the command decals south of the spawner which i have no idea what to do with they have varying door positions
> > 
> > 
> > Jut the landmark out another tile and do that specific section of decals specific to how the template is, you might have to make a special subtype of templates for meta
> 
> thats lame and cringe though for decals alone

Or you can just be lazy and just like make the decals skip it or something just try and make it look less shit imo

**Comment by azzzertyy** [comment]
Something came up. Cant finish working on this right now.

**Pull request closed without merging**
