### PR TITLE
ushanka resprite

### PR DESCRIPTION
**Pull request by Potototatoh**
### ushanka
Screenshot (784)
ushanka
(ушанки)

#### Changelog

:cl:  
tweak: ushanka  resprite
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
But there already is one and the changelogs isn’t good

**Comment by deathslayer2481** [comment]
feature

**Comment by overlord12345** [comment]
nice

**Comment by Potototatoh** [comment]
hmm i wonder whyw theres no new code

**Comment by boodaliboo** [comment]
If there’s no coding did you make sure the sprite paths link correctly

**Comment by nesisknesis** [comment]
shut the fuck up bood

**Comment by boodaliboo** [comment]
> shut the fuck up bood

that isnt nice also changing down to a up as the changelog is fixed

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
