### PR TITLE
adds the new oblivious onion

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
a brand new onion mutation that has impedrezene
image

#### Changelog

:cl:  
rscadd: Added new onion 
imageadd: added new onion
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
If I remember correctly, one of the HCs had previously said they did not like these kinds of direct player references, especially with the AI face that was just Yacabo.

Also this probably won't be used for anything but for a regular who wants to throw an onion at jarod and be like 'look haha its you'.

**Comment by boodaliboo** [comment]
> If I remember correctly, one of the HCs had previously said they did not like these kinds of direct player references, especially with the AI face that was just Yacabo.
> 
> Also this probably won't be used for anything but for a regular who wants to throw an onion at jarod and be like 'look haha its you'.

either way its more mutations and i personally want their to be more mutations so its harder to bumrush the same things everytime same with genetics

**Review by Hopekz — CHANGES_REQUESTED** [review]
This branch is out-of-date with the base branch . I am unable to merge this until you update this.

I recommend updating your "master" branch in the future so you don't have to do this to every PR you create.

**Comment by boodaliboo** [comment]
yeah my master branch is fucked up and im not sure how to fix it without deleting it

**Comment by Hopekz** [comment]
It's still "out of date". The system will literally not let me merge this unless it is fixed
I recommend using a git client for your future PR's

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Fix up your line endings

**Comment by boodaliboo** [comment]
> Fix up your line endings

did i do it?
also how to i have it made so it auto updates my branch

**Pull request merged**
