### PR TITLE
Makes cautery tool do burn damage + adv drill sharp

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
The nerf to welding tools will weaken being able to fight space vines
Since vines take 4x damage to burn, and 4x damage to sharp (16x if both)
this will give another weapon to fight vines for those that feel like running into maints after the vines without giving another civilian weapon

Also this just sorta makes sense, it's hot, it's gonna burn

:cl:  
tweak: Cautery tools have 3 force and do burn damage
tweak: Advanced Catuery tools in drill mode are sharp and have 4 force
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Do not make it sharp.
Medical tools got rightfully nerfed because of the Medical Hivemind that swarms and attacks antags and other such threats that violate the medbay. The drill was a secret weapon because it dealt like 10 damage but basically would guarantee a bleed wound. 
One hit was able to cause lacerations and repeated hits would upgrade to weeping. I dont think MDs need to have that type of power again.

**Comment by MajManatee** [comment]
I don't think the dmg reduction is enough to warrant a change like this

**Comment by Moltijoe** [comment]
> Do not make it sharp. Medical tools got rightfully nerfed because of the Medical Hivemind that swarms and attacks antags and other such threats that violate the medbay. The drill was a secret weapon because it dealt like 10 damage but basically would guarantee a bleed wound. One hit was able to cause lacerations and repeated hits would upgrade to weeping. I dont think MDs need to have that type of power again.

Dude, its 4 force, thats not enough to ever be useful as a weapon, the regular drill had like 10 force

**Comment by Moltijoe** [comment]
> I don't think the dmg reduction is enough to warrant a change like this

The change makes welding tools go from 1 hitting vines to 2 hitting them, for a weapon based on charges that greatly hurt it.
This also doesnt make it a good weapon, it'll still be worse than the laser scalpel which has 11 force.
All this change does is add another "common" weapon thats useful against spacevines, but thats only because it abusing the damage modifiers that vines have

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
