### PR TITLE
fix unnable to change vent mode to scrubbing

### PR DESCRIPTION
**Pull request by warface1234455**
this wasnt fully imported from tg

# Document the changes in your pull request
fix unnable to change vent mode to scrubbing

https://github.com/yogstation13/Yogstation/assets/89688125/3cdaa7ad-3dc2-40b8-bf8c-b6c168a2add5

# Changelog

:cl:  

bugfix: fix unnable to change vent mode to scrubbing
/:cl:

### CODE REVIEW

**Review by Moltijoe — APPROVED** [review]

**Comment by ToasterBiome** [comment]
So vents can suck things in?

**Comment by Moltijoe** [comment]
> So vents can suck things in?

It doesnt suck specific things in like the scrubber, it sucks everything in. Recall emped vents

**Review by JohnFulpWillard — APPROVED** [review]

**Comment by JamieD1** [comment]
I didnt know this was how it was supposed to be

**Comment by ShoziOffical** [comment]
now you know

> I didnt know this was how it was supposed to be

**Comment by ShoziOffical** [comment]
pls merge

**Pull request merged**
