### PR TITLE
Mushi Kombucha for Moths

### PR DESCRIPTION
**Pull request by Therandomhoboo**
# Document the changes in your pull request

So, with additions to making some species drinks. I settled on doing Mushi Kombucha for Moths, some moths do eat certain shrooms so I thought this would make sense. I've currently attached it to toxins so as to change up having the same species drinks do the same thing over and over. I've also put up the adjustment to I believe match Charcoals due to the complexity of the drink

# Wiki Documentation

Note: If you're playing a Moth, this heals toxin damage. Be careful not to get too drunk though.

# Changelog

:cl:  
rscadd: Mushi Kombucha now heals Toxins in Moths
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
i look forward to the pod person drink

**Comment by Moja10** [comment]
> i look forward to the pod person drink

Podperson drink is just blended meat smoothie with fingernails boba

**Comment by MajManatee** [comment]
boba tea 🤢

**Comment by Moltijoe** [comment]
> boba tea 🤢

my dude, boba is just sweet tea with tapioca, you can usually ask for the tapioca to be excluded too.
unless you hate literally all sweet teas, there's no way you hate boba

**Review by MajManatee — APPROVED** [review]
I hate tea. Also wheres the lizard drink smh

**Pull request merged**
