### PR TITLE
Renames worldshaker to worldbreaker because yall can't be trusted

### PR DESCRIPTION
**Pull request by Moltijoe**
YALL COULDN'T FUCKIN KEEP IT IN YOUR PANTS, NOW SEE WHERE THAT'S GOTTEN YOU

:cl:  
tweak: Worldshaker is now called Worldbreaker because everyone's incredibly immature
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Ided PR

**Comment by Therandomhoboo** [comment]
No reason to change it, doesn't make sense thematic wise

**Comment by LoliconSlayer** [comment]
You people keep calling it "Thugshaker" which is a term from porn

**Comment by azzzertyy** [comment]
its the thugshaker whether you like it or not even if this pr is accepted we will STILL call it the thugshaker

**Comment by Moltijoe** [comment]
> its the thugshaker whether you like it or not even if this pr is accepted we will STILL call it the thugshaker

please refrain, if someone googles it out curiousity they will be met with unsightly images

**Pull request closed without merging**
