### PR TITLE
Adds chapel variations, Adds chapel 2.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Adds variation to the chapels, allowing for anyone to add a custom chapel for box.
Also adds in Chapel 2, a variation of chapel with stairs (sorry koko) and an alternate layout.

# Spriting
Adds, yet another middle stair sprite, this time for dark_stairs.

image

# Changelog
:cl:  
mapping: Added Chapel Variation for box
mapping: Added Chapel 2 for box
imageadd: Added sprite for dark_stair middle
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
add pref?

**Comment by Marmio64** [comment]
the alt layout probably shouldn't have ultra easy to break windows leading to the chap's private office. Should probably be replaced with walls for some privacy or be upgraded to reinforced.

**Comment by azzzertyy** [comment]
> the alt layout probably shouldn't have ultra easy to break windows leading to the chap's private office. Should probably be replaced with walls for some privacy or be upgraded to reinforced.

I based whether or not it should be reinforced on Asteroid, since their chapel also has windows which are not reinforced, although I do agree that they probably should be.

**Comment by azzzertyy** [comment]
> add pref?

Don't know how.
If you can link me to a PR that adds prefs for station variations (tg or here) then i could give it a shot though.

**Comment by cuackles** [comment]
hey so the pr is deleting the land mark of sig tech and space bartender, i know the sigtech is replaced by other thing but what about the space bar tender one ?

**Comment by azzzertyy** [comment]
> hey so the pr is deleting the land mark of sig tech and space bartender, i know the sigtech is replaced by other thing but what about the space bar tender one ?

no clue why ive never opened this file in my life but its fixed

**Comment by cuackles** [comment]
> > hey so the pr is deleting the land mark of sig tech and space bartender, i know the sigtech is replaced by other thing but what about the space bar tender one ?
> 
> no clue why ive never opened this file in my life but its fixed

works for me

**Review by cuackles — APPROVED** [review]

**Review by MajManatee — CHANGES_REQUESTED** [review]
Add a pref like we have with the bar system. Then this will be baller

**Comment by azzzertyy** [comment]
> Add a pref like we have with the bar system. Then this will be baller

Prefs are not only something I really do not know how to do right now but also highly out of the scope of the pr. I'd prefer to merge this now as random chance and later add Prefs.

**Comment by MajManatee** [comment]
Reopen when work continutes.

**Comment by azzzertyy** [comment]
> Reopen when work continutes.

why did you just ignore what i said?

**Comment by Bibby0110** [comment]
Pref is out of scope

**Comment by N3D6** [comment]
I hate the “everything should be a preference” movement just let the man live bro

**Pull request closed without merging**
