### PR TITLE
Ports mothroach from tgstation

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

image
Ports https://github.com/tgstation/tgstation/pull/68763/
Orderable from cargo for 7500cr

**LGTM!**

# Spriting
See above

# Changelog

:cl:  
rscadd: Added mothroach
/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]
M o t h 👁️ 👄 👁️

**Comment by Marmio64** [comment]
awesome
im going to kill all of them

**Comment by redmoogle** [comment]
> awesome im going to kill all of them

>:(

**Comment by JamieD1** [comment]
Why cant you make moth caterpillars instead :(

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
