### PR TITLE
Removes AsteroidStation

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

- Abandoned before full release
- Uses a lot of non-unique box related templates which makes it feel samey
- Had fundamental department placement issues (Science...)
- Amateurish mapping (look at some of the maints)
- Almost never played (6 times in the last month)

# Wiki Documentation

All Asteroid things must be removed from the game

# Changelog

:cl:  
mapping: AsteroidStation has been removed from the game.
/:cl:

### CODE REVIEW

**Comment by StupidTums** [comment]
I think asteroid is a fun map, and it offers unique sections, inside the map, that differentiate it from other maps. Does the map have problems? No doubt, but does it deserve to be removed because of these issues? No. Outright removing a map should be the nuclear option. Instead, we should take a comprehensive look at not just asteroid but other maps to bring them up to par to maps like Box, to expel the negative elements of these maps, and to create a diverse portfolio of map options for our player base.

**Comment by PibeCantina** [comment]
I like asteroid, and it not being voted is because i am sure you can only vote for it when there is some decently high pop for the map to show on the vote menu.
Besides that, even if science omega sucks, it has many very cool places and maints are the best out of every map we have.

**Comment by cowbot92** [comment]
wait can you merge my pr before you remove it so I dont have conflicts

**Comment by Aquizit** [comment]
It's too big a map for current population counts and yes the chief designer did kinda vanish but it's been maintained when stuff has been brought to our attention.

I could see the case for maybe disabling it based solely in population issues but I'm not sure if deleting it is the best idea (yet).

**Review by Aquizit — APPROVED** [review]
The above post of mine being said the map changes are fine as it's just a file deletion.

**Comment by wonderinghost** [comment]
im fine with the removal if it means a rework for it comes out. asteroid is fundamentally flawed station, static maints, everything else is too big while also being tiny (more hallways than a room) and taking a while to get to a place

im pretty sure more people know where the kitchen is than the ai sat or teleporter room

**Comment by AMyriad** [comment]
> * Abandoned before full release
> * Uses a lot of non-unique box related templates which makes it feel samey
> * Had fundamental department placement issues (Science...)
> * Amateurish mapping (look at some of the maints)
> * Almost never played (6 times in the last month)

As a mapper I completely agree. Asteroid has a lot of problems our teams don't have time to fix (vs other things) so a canning's long overdue. That being said, I can't imagine this would help us keep players rn. We do be needing as much content in the game as possible in these times, so I'm worried removin something big like this would leave players disappointed.

**Review by Moltijoe — APPROVED** [review]

**Comment by ToasterBiome** [comment]
you may keep your asteroid station... for now...

**Pull request closed without merging**
