### PR TITLE
Message emphasis and fonts stuff (cool awesome)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

Ports
https://github.com/tgstation/tgstation/pull/59073
https://github.com/tgstation/tgstation/pull/61543
https://github.com/tgstation/tgstation/pull/64366
https://github.com/tgstation/tgstation/pull/69137
https://github.com/tgstation/tgstation/pull/76356

# Why is this good for the game?

Brings awesome fonts to the game and also cuts down on some copy paste & brings in some code improvement ports that I think yogstation is lacking as mods.

# Testing

image

# Spriting

# Wiki Documentation

# Changelog

:cl: ninjanomnom, Ryll-Ryll, Bizzonium, KylerAce, Sinsinins, lessthnthree
experimental: Added new fonts and refactored runechat. Also some backend stuff it's fine.
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Finally BOLD TEXT

**Comment by MajManatee** [comment]
> Finally BOLD TEXT

this guy doesn't know that two exclamation marks bolded your message.

**Review by ToasterBiome — APPROVED** [review]
sure

**Comment by Beeper-Skeeper** [comment]
pretty sure this breaks languages and makes them all show normally instead of how they should?
like they all show up understandable above your head even if you don't speak the language
pretty bad for revs or any other convert antag

**Pull request merged**
