### PR TITLE
Signal-Skill-Cape update! *BzZzZT*

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
Change the color and animated the signal tech's skill cape.

Saw someone grind to the 300+ hour cape and was immensely disappointed with what they worked so hard for. The old cape does not complement what a sigtech wears at all and the symbol was just not a solid choice and was awkward.

Mines is more conformed to the yellow and green style that you see with signal techs and also includes a better symbol with a nice animation to it.  

Has been tested.

:cl:  

imageadd: Resprited Signal Tech cape to look better and complement their colors. 

/:cl:

https://user-images.githubusercontent.com/82983051/133380206-131d5052-c5e6-48ca-983c-727381fe8e52.mp4

### CODE REVIEW

**Comment by tattax** [comment]
if you're gonna animate one of them you'll have to animate all of them, people grind just as hard on other jobs why should a specific one be better than all the other ones

**Comment by Anvilman6** [comment]
I think the icon looks awesome, much better than the headset it was prior

However, I'm with Tattax on this one - the animation is a little over the top for just one cape specifically.

**Comment by tattax** [comment]
also trimmed is supposed to be better than the default one but it doesn't even have the animation?

**Comment by KillerOrcaCora** [comment]
> if you're gonna animate one of them you'll have to animate all of them, people grind just as hard on other jobs why should a specific one be better than all the other ones

If others want theirs animated they can come to talk to me.

**Comment by KillerOrcaCora** [comment]
> also trimmed is supposed to be better than the default one but it doesn't even have the animation 

Trim is pure gold and just a different flavor and I don't really want to give what should be gold bars taped to a cape a moving animation. Ive already broke enough rules with the first cape alone.

**Comment by ToasterBiome** [comment]
It would be cool if all the trimmed skillcapes had animations

Love it

**Comment by Tipy1802** [comment]
Skillcapes are already rather out of place, this only makes it worst

**Comment by KillerOrcaCora** [comment]
Cape overall size is taken down by request of identification!

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
