### PR TITLE
Removes the happy cluwne mask from the autodrobe

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request
In another case of cluwne things slowly getting more and more broken over time the happy cluwne mask now rather then being a chance always cluwnes whoever wears it and since im too lazy to fix it im just gonna remove it from easy access for now.
#### Changelog

:cl:  
rscdel:  Happy Cluwne Mask gone from autodrobe 
/:cl:

### CODE REVIEW

**Comment by Lichton** [comment]
No!

**Review by Lichton — CHANGES_REQUESTED** [review]
Please don't do this, it's a fun item that has many interesting uses and is in general just fun.

**Comment by Jarod1200** [comment]
Maybe people are just lucky

**Comment by fluffe9911** [comment]
fineeee

**Pull request closed without merging**
