### PR TITLE
Ice tile no longer has a slowdown

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

If it slips you why the hell is it going to slow you down when you have the proper equipment to not slip

Ice will no longer slow you down

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: ice will no longer slow you down by 1
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Lazy PR because people that don't have the proper equipment will not be slowed down as well

Your PR just assumes that everyone that touches ice has the proper equipment

**Comment by N3D6** [comment]
> Lazy PR because people that don't have the proper equipment will not be slowed down as well
> 
> Your PR just assumes that everyone that touches ice has the proper equipment

If they don’t have the proper equipment to not slip guess what

they slip

**Comment by Simplehorror** [comment]
this and the other snow pr made snowdin sad by the way

**Comment by N3D6** [comment]
> this and the other snow pr made snowdin sad by the way

and they also made icemoon playable, I’d rather have a map that’s about to be used a lot more playable for mining than a random unused away mission

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
