### PR TITLE
HOS' trenchcoat is now thick

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

no more instakill chem syringes on the toughest guy on the station

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: HOS' trenchcoat is now thick
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
ided

**Comment by Simplehorror** [comment]
I don't die

**Comment by Notamaniac** [comment]
> I don't die

evidence not provided

**Comment by Marmio64** [comment]
Target head

**Comment by Simplehorror** [comment]
helmet should block syringes

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
