### PR TITLE
Removes attk

### PR DESCRIPTION
**Pull request by Mqiib**
Goddamit cuackles

# Changelog

:cl:  

bugfix: Stops balloons from spamming EVERYONE ON THE SERVER

/:cl:

### CODE REVIEW

**Review by ToasterBiome — APPROVED** [review]

**Comment by cuackles** [comment]
I DIDNT CODE IT WAAAAAAAAAAAAAAAAAAAA

**Comment by Mqiib** [comment]
pls merge b4 next round literally gamebreaking bug pls i cant plkay my spessmans it ruins my iimmersion

**Comment by ShoziOffical** [comment]
It was @redmoogle lmo

**Comment by redmoogle** [comment]
> It was @redmoogle lmo

Jamie should have caught it

**Pull request merged**
