### PR TITLE
[DONUT] Fixes weird door access on donut (other misc stuff too)

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# Document the changes in your pull request

Anyone with maintenance access could open janitor closet, this is no longer the case.
Security maintenance door required maintenance access along with brig access to open, now it only requires brig access asi s everywhere else.
I also did this for one of the "security" doors lower down, you no longer need maintenance access, only brig.
Medical's cryo room now only will accept those with medical access.
Medical's cryo room door was also.. under geneticists area? If the freezer is in exam room area the door should be too that makes no sense.

# Why is this good for the game?

Doors having correct access and lining up with rest of the map is good.
As for the cryo room (in the picture below) I don't think its right for anyone with normal maintenance access from an assistant to an officer to be able to walk into that room. That freezer is semi-sensitive equipment to medical. I could undo this if needed.

Also, the area. Why was it in gene, that makes no sense. Its now under exam room.
image

# Testing
None needed

# Wiki Documentation

None

# Changelog

:cl:  
bugfix: donut janitor closet/security maintenance doors have better access requirments.
bugfix: donut medical cryo freezer room maintenance door no longer lets those with maintenance access in and is now under the exam room's area.
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
This isn't Gax?

**Comment by bruhlookatthisdood** [comment]
> This isn't Gax?

i get donut and gax confused
mb

**Review by neeshacark — APPROVED** [review]
all seems well

**Comment by neeshacark** [comment]
if this causes merge conflicts with my donut pr i am going to kill you

**Comment by bruhlookatthisdood** [comment]
> if this causes merge conflicts with my donut pr i am going to kill you

womp womp

**Pull request merged**
