### PR TITLE
[PORT TG] ports some disposal changes, reroutes box and more disposals

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request

Portholders: @Comxy (disposal rotators), @ArcaneMusic (disposal bins can hold destination taggers), @TheBonded (disposal junction sprites), and @Profakos (disposal fix and mapping sort helpers)

ports disposal routers:
[Transit Tube Fix and New Rotator Disposal Pipe #77843](https://github.com/tgstation/tgstation/pull/77843)
destination tagger holder:
[Disposal bins can now hold a destination tagger, and adds a few throughout maps. #81991](https://github.com/tgstation/tgstation/pull/81991)
junction resprites:
[New disposals junction sprites #66217](https://github.com/tgstation/tgstation/pull/66217)
wrap disposal fix:
[Package delivery sorter fix, autodocs #72865](https://github.com/tgstation/tgstation/pull/72865)
mapping helpers:
[Mail sorting helper, and disposals fixes #70861](https://github.com/tgstation/tgstation/pull/70861)

resprites for disposal junctions since they are more easily readable
adds a rotator disposal pipe, items that enter will be rotated 90 degrees 
disposal bins can now hold destination taggers, right click to put on and take off a destination tagger from a bin 
adds a new mapping helper, mail sorting is quicker to configure by dropping a helper over a mail sort junction 
wrap pipes now pull wrapped packages from disposal system

all heads, the warden, virologist, and xenobiologist have destination tags on their bins (xeno and virology now have bins)

Blue = new route/items
Red = old route
diff pipes master

# Why is this good for the game?
gives disposals some needed love. for mappers the rotator might be useful for more neat disposal lines.
with the new helper it will automatically configure mail sorting pipes on lateload. instead of configuring a pipe in a bunch of variables you can just drop the mail sorting helper over the pipe to configure
holders on the bins means it can be easier to deliver stuff in between departments. dotted in head offices (qm included), cargo, viro and warden's bin
if you ever saw our current disposal junction sprites you'll understand why
wrap pipes always existed but was broken, now wrapped packages will be pulled out of the disposal loop if isnt delivered or unmarked

#Wiki 
update guide to mapping disposal section with mentioning of new disposal pipes and helpers
# Testing
edited box to reorganize and test pipes, more to be routed once i get other stuff done

# Spriting
image
image

# To Do

- [x] map compilers hates this rotator pipe, dont look at me ive got no idea how to fix it

# Changelog

:cl:  
rscadd: adds a destination tagger holder to bins and a disposal rotator
rscadd: adds a sort mail helper, drop on sort pipe to configure
mapping: reroutes box disposal pipes for the moment
bugfix: wrap pipes now pull wrapped packages out to the side
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
atomizing a project

**Comment by AMyriad** [comment]
Could you please link what you're porting, give credit to the authors in the changelog, or explain at all what any of this does?

**Comment by wonderinghost** [comment]
> Could you please link what you're porting, give credit to the authors in the changelog, or explain at all what any of this does?

technically my first port, so i dont have a exact idea how to do things, give me a moment

**Comment by Cyberboss** [comment]
The OG authors are @Comxy and @ArcaneMusic. Not me and the other guy

**Comment by wonderinghost** [comment]
noticed one more disposal change that can be helpful for mappers, drafting to work on

**Comment by wonderinghost** [comment]
> The OG authors are @Comxy and @ArcaneMusic. Not me and the other guy

shit sorry, didnt notice that

**Review by AMyriad — DISMISSED** [review]
Just taking a cursory glance here, but this is a semi-significant change to box maint.
Since it's not crucial to what you're tryin to do here, I suggest you do this in a separate PR if you really want to take this area out of space, so please revert it for the time being.
image

**Comment by AMyriad** [comment]
Also why add this section, if I may ask?
image

**Comment by wonderinghost** [comment]
Rerouting disposal lines. If there wasn't more then something may have fucked up on my end because I relooped the disposal line to not run like before

**Comment by wonderinghost** [comment]
> Also why add this section, if I may ask? 

image

**Comment by Profakos** [comment]
I am always happy when people use the disposal sorting helpers.

**Review by cuackles — APPROVED** [review]

**Comment by wonderinghost** [comment]
couldnt update my branch for some reason

**Review by ToasterBiome — APPROVED** [review]
didnt break so it's good

**Pull request merged**
