### PR TITLE
Nuke ops Hud Update!

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
# Github documenting your Pull Request

My first PR will change the current Nuke ops Hud logo into a animated new Hud I made while deleting the old one. Has been tested. 

# Wiki Documentation

Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
 
imageadd: added some icons and images  
imagedel: deleted some icons and images  

/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
there is a wight pixel on the fourth icon. (I think) Its show up in dark mode.

**Comment by Xoxeyos** [comment]
Can we get a gif, or a photo of what it looks like?

**Comment by Moggram** [comment]
> 
> 
> Can we get a gif, or a photo of what it looks like?

Go to checks, Then IconDiffBot.

**Comment by KillerOrcaCora** [comment]
> there is a wight pixel on the fourth icon. (I think) Its show up in dark mode.

Can you screenshot what your talking about I don't see anything odd on the fourth panel (But I am very blind as a bat anyhow)

**Comment by nmajask** [comment]
Nice PR, the new icon and animation looks nice and fits well in my opinion. I do have one suggestion though, in the changelog you should probably do "imageadd: added a new icon for nukies" instead of "imageadd: added some icons and images" & "imagedel: deleted some icons and images" so players can easily see what is changed.

> there is a wight pixel on the fourth icon. (I think) Its show up in dark mode.

> Can you screenshot what your talking about I don't see anything odd on the fourth panel (But I am very blind as a bat anyhow)

I think that's just an issue with the  [IconDifBot](https://github.com/yogstation13/Yogstation/pull/11896/checks?check_run_id=3166808286) cause when I took a look at the changed file I didn't see it.

> Can we get a gif, or a photo of what it looks like?

Here is a gif, but its a bit small as I don't know how to resize it.
synd

**Comment by alexkar598** [comment]
I can see it being animated getting rather annoying, hud icons are all static, why should this one be animated?

**Comment by nmajask** [comment]
> I can see it being animated getting rather annoying, hud icons are all static, why should this one be animated?

There are many hud icons that are animated (mindshield, changeling icon, a ton of medical hud icons), most of which are flashing. The animation on this one is very minor and doesn't stand out that much.

**Comment by KillerOrcaCora** [comment]
> I can see it being animated getting rather annoying, hud icons are all static, why should this one be animated?

Many Iconic Antags have moving Huds. Some baring more moving animations then any other thing in the game ***COUGH BLOOD CULT***

Also you cant tell me this isn't badass 

https://user-images.githubusercontent.com/82983051/127228572-7c089bb4-12c8-4878-bbbc-899ba23817d0.mp4


https://user-images.githubusercontent.com/82983051/127228582-5b6e4489-9a97-4b76-a87d-5fce69c0458b.mp4

**Comment by Moggram** [comment]
> 
> Can you screenshot what your talking about I don't see anything odd on the fourth panel (But I am very blind as a bat anyhow)

This is what I see. it could be the just IconDifBot doing odd stuff.

**Comment by adamsong** [comment]
What about the syndicate balloon?

**Comment by KillerOrcaCora** [comment]
> What about the syndicate balloon?

Jamie brought this up and decided I will make a separate PR for that if this one gets accepted.

**Comment by KillerOrcaCora** [comment]
> > Can you screenshot what your talking about I don't see anything odd on the fourth panel (But I am very blind as a bat anyhow)
> 
> This is what I see. it could be the just IconDifBot doing odd stuff.
> 

Went over it and I'm not seeing this in-game or while using dark mode in the panel. think its just the bot too until proven otherwise.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
