### PR TITLE
buff kindle

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

kindle is the worst fucking spell in the game i swear. you need 5 seconds to charge it up and then it lasts for 5 seconds so ???. also if you miss you're just fucked and the entire gamemode is over because everyone knows it is clockcult now, and you can't stack 4 unmissable stuns like bloodcult
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: kindle lasts IN YOUR HAND for 30 seconds, takes 1 second to charge
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
also you can fucking dodge the projectile hahahahahaha

**Comment by chemistrymain2** [comment]
dude

**Comment by Simplehorror** [comment]
> dude

stop making me look bad

**Comment by MajManatee** [comment]
skill issue, dont miss

**Comment by Simplehorror** [comment]
> skill issue, dont miss

tell that to Mr. 10 Hours and Just Enabled All Antags who just fucked over my clockcult round because I didn't babysit him enough by taking out tcomms within 5 minutes

**Comment by Simplehorror** [comment]
## TO MAKE IT CLEAR, THE STUN IS UNCHANGED. THE SPELL LASTS 30 SECONDS IN YOUR HANDS. THIS MEANS YOU JELLYRAIN

**Comment by Sniblet** [comment]
Oh good now I can fire my irresistible hardstun on full auto

**Comment by ReddicusDragon** [comment]
ided

**Comment by JamieD1** [comment]
Skill Issue

**Pull request closed without merging**
