### PR TITLE
Add the Lavaland Science Probe(L.P.M) to auxbase

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Make auxbase useful by placing an immovable machine that makes 500 science points per minutes

Also has calibration to make it so you have to slightly manage it

_No you can not move it_

Calibration takes ~18 Minutes to fall to 0%

image

P.S. old picture new one has points per minute not per minute

### Why is this good for the game?

Add usefulness to the auxbase by adding a science generator(ps it has to be on lavaland to work)

#### Changelog

:cl:  
rscadd: Add a science generator to the auxbase
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
What's the megafauna detection for? Is it just something to go "fuck, GET OUT" for or does dead megafauna increase point generation from the LPM?

**Comment by redmoogle** [comment]
> 
> 
> What's the megafauna detection for? Is it just something to go "fuck, GET OUT" for or does dead megafauna increase point generation from the LPM?

Decoration. Could add it as an actual feature but meh. It's kinda just a "here's a shiny rock" kind of thing

**Review by patpol4 — APPROVED** [review]
Map ok

**Review by jcatjmeow — APPROVED** [review]
Code ok

**Pull request merged**
