### PR TITLE
Medical analyzer beeps now only play for the user and target

### PR DESCRIPTION
**Pull request by Absolucy**
:cl: Lucy
tweak: You can no longer hear a lizard spamming a health analyzer on a person in a stasis bed from across the room.
/:cl:

### CODE REVIEW

**Comment by Smudged** [comment]
I would rather that medbay have sound.

**Comment by Absolucy** [comment]
What about a cooldown on the beep, then?

**Comment by adamsong** [comment]
Closing in favor of #14362 and due to massive downvotes

**Comment by adamsong** [comment]
#13462

**Pull request closed without merging**
