### PR TITLE
AI data cores now have a backup powercell

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

i hate blackouts.
Uses 97.5% less power when running off of cell because ??? (makes sure you don't drain the cell instantly, high cap cell lasts approx. 2 minutes)

# Changelog

:cl:  
rscadd: AI data cores now have a backup powercell.
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
cool but if there's no power you die in probably ~10 seconds from freezers not working

**Comment by Bibby0110** [comment]
> cool but if there's no power you die in probably ~10 seconds from freezers not working

no, outputs less heat

**Comment by Moltijoe** [comment]
> no, outputs less heat
Powersaver mode?

**Comment by Bibby0110** [comment]
> > no, outputs less heat
> > Powersaver mode?
> > yes

**Review by Moltijoe — APPROVED** [review]
Effectively adds a countdown timer to death rather than it being instant death, pretty good, numbers might need tweaking in the future, but that is not now.

**Pull request merged**
