### PR TITLE
Fuck adam and ling

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request
MMIs now accept changeling brains, but upon trying to place them in a borg it gives the person trying to do it the same message as when they're jobbanned from cyborg, meaning the only way to legitimately know whether they're a fucking changeling or not would be to find the ckey of the brain's owner, then cross-reference it with the banlist, which is pretty deep down the metagaming rabbithole.

#### Changelog

:cl:  
tweak: Adam El-Tablawy can no longer lingcheck people by cutting their brains out and shoving them in machines.
/:cl:

### CODE REVIEW

**Comment by thehighwayman** [comment]
ye boi fuck Adam balance this game around the shitler top tier people

**Comment by jcatjmeow** [comment]
Add the whole "ling blood reacts to being ignited" thing back instead.

**Comment by Amelia0010** [comment]
@thehighwayman this literally doesn't change anything for people who aren't doing what adam did, or are being done upon what adam did. So why are you complaining?

**Comment by ghost** [comment]
@jcatjmeow ling blood never reacted that way

also, i mean, if the council okayed it as a test, then i don't see why this is a problem but okay

**Comment by Time-Green** [comment]
you could also just shove the brain in the cloner

**Pull request merged**
