### PR TITLE
removes plate from green eggs and ham

### PR DESCRIPTION
**Pull request by ktlwjec0**
it was only removed from the first frame, this removes it from all of the frames

### CODE REVIEW

**Comment by MajManatee** [comment]
thank god

**Review by cuackles — APPROVED** [review]

**Comment by ThatLing** [comment]
meme pr

**Comment by ktlwjec0** [comment]
> meme pr

You're just upset you don't have the spriting skills to remove plates

**Comment by cuackles** [comment]
guess i should have merge this a long time ago

**Comment by ynot01** [comment]
best pr of 2023

**Pull request merged**
