### PR TITLE
Corporate Go Brrrr

### PR DESCRIPTION
**Pull request by JamieD1**
All this module/lawset does it cause drama, we have the superior ceo lawset now.

And.... Discuss/Council vote.

#### Changelog

:cl:  
rscdel: Yeets Corporate
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Did you take a vacation? Our council recently voted on this and it was voted to stay.

**Comment by Xoxeyos** [comment]
Why fully remove it anyhow? Put it in the hazardous region of the AI upload, with the other lawsets, like antimov.

**Comment by swissloaf** [comment]
you should remove it from roundstart only

**Comment by Jumps0** [comment]
ladies and gentlemen, we got em

**Comment by JamieD1** [comment]
> Did you take a vacation? Our council recently voted on this and it was voted to stay.

Because this was before the ceo replacement was in (:

**Comment by maxion12345** [comment]
haha yes

**Comment by alexkar598** [comment]
As far as im aware, people want it removed from round start. Not from being accessible in game

**Comment by alexkar598** [comment]
Eh, il keep it open for a bit

**Comment by JamieD1** [comment]
> Eh, il keep it open for a bit

I can change it to round start, thats easyyy! Dont close ;-;

**Comment by yacabo** [comment]
For refrence and histroy keeping, this is the poll at the time of writing
image

https://forums.yogstation.net/index.php?threads/can-we-please-remove-corporate.21590/page-2#post-185291

**Comment by MenacingManatee** [comment]
I'd upvote removing from roundstart, but removing entirely is a no from me

**Comment by Hopekz** [comment]
> this is the poll at the time of writing

We never use forum polls for merge. 
Server community poll or bust.

**Comment by yacabo** [comment]
It's relevant, it may be a symptom of a recent problem and not the cause, but it's relevant

**Comment by alexkar598** [comment]
I never use no votes lol.

Votes are a way of getting some sort of feedback but isnt binding

**Comment by Ratvar** [comment]
Remember when server votes were used and people thought xenoling is a changeling

**Comment by ynot01** [comment]
DUMP IT

**Comment by alexkar598** [comment]
Yeah this is a config thing. Corporate is nice in the codebase atm

**Comment by alexkar598** [comment]
Staff is going to apply law hierarchy to corporate to make it asimov with another name. it's a shame

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
