### PR TITLE
Steals TG's red alert sound + Sydnicate Announcment (not syndicate anymore)

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
### All sound added in this PR was made by **DrDiasyl,** all credit of this PR should go to him
# Document the changes in your pull request

I wasn't able to port ALL of the pull request, I might later if people want it.
For now, i have red alert sound and syndicate announcement.
Although, we do not have syndicate announcements (unless?), so i renamed it in the code to announcement2 and its now just a more... creepy announcement.
Uhh I think that's all unless I forgot something
**I am willing to remove the new announcement and only add red alert sound**

### PREVIEW:
https://github.com/yogstation13/Yogstation/assets/89947174/26689e0b-85b0-40cc-9b55-423855ddfaf4

# Why is this good for the game?
To me, I feel like red alert announcement is just too.. lacking.
This will give it a bit more of pizzas

As for the announcement.
It kinda sounds cool

# Testing
Ahhhhh yeah so my VS code is broken and i cant test it at all! Fun!
I assume it would work though, dosen't look too complicated.
# Wiki Documentation

nuh uh

# Changelog

:cl:  DrDiasyl
rscadd: New red alert sound
rscadd: New announcement sound for specific announcements
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
if this gets merged someone should make delta and omega alerts pants-shittingly terrifying

epilson is good enough as it is

(also hijack announcement????)

**Comment by bruhlookatthisdood** [comment]
> if this gets merged someone should make delta and omega alerts pants-shittingly terrifying
> 
> epilson is good enough as it is

1. i didn't merge delta alert because we already had one 

2. the fuck is an omega alert

**Comment by Yarinoi** [comment]
>     2. the fuck is an omega alert

i somehow mixed up delta and gamma and got gamma wrong, kill me now

**Comment by bruhlookatthisdood** [comment]
> > ```
> > 2. the fuck is an omega alert
> > ```
> 
> i somehow mixed up delta and gamma and got gamma wrong, kill me now

i think gamma is already terrifying enough
i don't make sounds, if people have sound suggestions they can tell me them (or dm the sound files to me, my discord is liljackrabbit25)

**Comment by RG4ORDR** [comment]
The new Red Alert is stinky.
The Hijack/Cult one is fine.

**Comment by bruhlookatthisdood** [comment]
> The new Red Alert is stinky. The Hijack/Cult one is fine.

It's not the best, but its better than the one that sounds identical to blue alert.

**Review by Moltijoe — APPROVED** [review]
easy code, i don't care for the new red alert sound, but that's not up to me

**Comment by bruhlookatthisdood** [comment]
> easy code, i don't care for the new red alert sound, but that's not up to me

being fair, i don't like it much either
but until someone who makes sound is able to come up with one i think this is better than the same alert sound for blue alert.
blue alert and red alert are VERY different.

**Comment by DrDiasyl** [comment]
Hey, I'm here not to tell any important information, I just like to search up my name and see what I find.
I'm here to just say - your Delta has cooler alarm sound.

I'm out.

**Review by warface1234455 — CHANGES_REQUESTED** [review]
do you realize that when you trigger the red alert, both sounds will play? see minor_announce proc

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
