### PR TITLE
adds a variety of exosuit sprites that are reflected from back sprites

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

also fixed up some bone axe sprites because they were irking me

the current list of items i added (i know not all of these can fit on exosuits or are realistically in the game and there are more i could do that would be super cool) is
- shotgun
- riot shotgun
- combat shotgun
- double barrel
- glass spear
- ion rifle
- laser cannon
- pulse rifle
- improvised shotgun
- holy blade
- cult blade
- claymore
- bomb spear
- sniper
- bone axe
- bone spear
- mosin
- bamboo spear
- chitin spear
- bone sword

backpack overlaps exosuit which overlaps belt, by the way for those who aren't in the know. So a HoS with a backpack and a shotgun on their coat will have the shotgun showing beneath the backpack

# Changelog

:cl:  
imageadd: Fixes up some bone axe sprites
imageadd: Exosuit sprites for a handful of stuff which had back sprites
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
please don't merge this before https://github.com/yogstation13/Yogstation/pull/18514 , i beg you

**Comment by Skrem7** [comment]
> please don't merge this before #18514 , i beg you

ye das oke

may i ask why

**Comment by cuackles** [comment]
this deletes 2 icons of bows on back, is it intended ?

**Comment by Skrem7** [comment]
> this deletes 2 icons of bows on back, is it intended ?

unused because bows can't be nocked + stowed anymore

so yes

**Comment by tattax** [comment]
> ye das oke
> 
> may i ask why

it takes a while to fix the icons on that branch after a merge on master

**Review by cuackles — APPROVED** [review]

**Comment by cuackles** [comment]
@Skrem7 conflict on the pr, pls fix for merge

**Pull request merged**
