### PR TITLE
Ports NSV13's Genpop Brig System

### PR DESCRIPTION
**Pull request by maxion12345**
# Github documenting your Pull Request
I've been wanting something better than the normal brig timers we currently use. This is a pretty good upgrade from our previous way to brig people. Basically, to brig with this system, you utilize a GenPop interface.
This interface looks like this:

It has buttons to quickly set for common crimes such as trespassing, assault, and theft. It doesn't have all the crimes currently, but something like that could come later. Pushing a button automatically sets the timer to the time required for that crime.

Now lets give it a shot. Brodie here has just committed the crime of CREATING A WORKPLACE HAZARD! So, I'll go ahead and mash that button. 

The timer has automaticly been set to 5 minutes, and the crime set to Creating a Workplace Hazard. Now, we'll input Brodies name...

And now we'll generate the temporary prisoner ID that will be used in the second step of brigging someone with the GenPop system. Upon hitting the Finalize button, it prints a prisoner ID and a piece of paper you can hand to the warden for him to file.
Next, we'll go a GenPop locker and open it. We'll strip Mr Brodie of his items inside of the locker as usual (represented by the random shit in the locker)

We'll close the locker and swipe the ID to assign it to Brodie. 

Damn. Looks like we have a bit to go until we're released.

Let's look at the other things the GenPop system will do for us. Namely, it will automatically update our security status AND security record with the crime, so every officer knows what you did!

This status is changed to DISCHARGED at the end of our time in the brig. Anyways, Mr Brodie has suffered enough in the brig, so we'll release him early. 

This was made to be used with the one-way turnstiles, as when you are discharged the ID gets a special "exit" access added to it that'll let you walk out of the cell without an officer. We'll get our random shit back by slotting the ID back into the locker, where it is removed and the locker ready for the next prisoner.

This was made to be used with the Turnstile update, but I'm having issues getting it to work in the same branch so I'll just wait until the Turnstile PR is merged then I'll add them onto this branch. The benefit to using the Turnstiles lets you have a single large "General Population" cell, as pictured here. 

The only people that can enter/exit are officers and prisoners that have that special discharge access. You could also use normal cells as pictured in the demonstration photos.

TODO:

- [x] Add all crimes
- [x] make the crimes different by category somehow
- [x] Make crimes stack
- [ ] Add turnstiles
- [x] add to all maps that I think are in rotation
- [ ] not really needed but if we can make it do separate sec records that'd be cool

NEW MAPS (turnstiles to be added later)
Yogurtstation: Turned two cells into genpop, one left for "problematic prisoners"

Meta: has basically the same layout as yogurtstation so I added a genpop here

Kilostation: just changed the terminals and lockers to genpop and added flasher button under em

Delta: Only two cells so no room for genpop

# Wiki Documentation

You'll need to update Space Law brig procedures to reflect the new system. Whenever it comes out of the draft.

# Changelog

:cl:  
rscadd: Ported NSV's GenPop brigging system!
rscadd: GenPop system automaticly adds sec records, sets status, and discharges prisoners with patent pending turnstile.
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
fuck this ruins the tried and true lie to sec about sec timers to get 1 minute for grand theft

**Comment by ToasterBiome** [comment]
Interesting concept, would like to at least see a testmerge.

**Comment by maxion12345** [comment]
I'd love to modify this to have the entire spacelaw tree on there, but I don't know enough about TGUI to make that happen in a way that's easy on the eyes.

**Comment by adamsong** [comment]
Lay out the crimes in a table similar to space law, it would speed up finding crimes

**Comment by maxion12345** [comment]
managed to get the crimes lined up vertically, but I don't know how I can separate the different crimes by type inside of TGUI. They are all stored on one big list, and I don't know how i could break that list down into smaller lists while keeping the functionality of the gen pop system. If anyone wants to help tackle the problem feel free to help out, as I'd love a way to have all the crimes on there in a neat organised manner

**Comment by patpol4** [comment]
very promising

**Comment by Anvilman6** [comment]
This is an excellent addition, love the concept and execution here. Just have to get it tweaked up to Yogs relevancy.

EDIT: How does it handle multiple applications of the same crime?

**Comment by maxion12345** [comment]
> This is an excellent addition, love the concept and execution here. Just have to get it tweaked up to Yogs relevancy.
> 
> EDIT: How does it handle multiple applications of the same crime?

as of yet, it doesn't. The timer maxes out at 25 minutes (Maximum before perma per space law), but I haven't touched the timer system at all yet. Should be easy to make it add time onto already existing time. Planning on making nice rows/bows that fit all the crimes first

**Comment by maxion12345** [comment]
I've got work and school for a few days, so progress on this will stagnate for a bit

**Comment by maxion12345** [comment]
quick update, got all the crimes on there. next step will be making the crimes stack so the timer increases each crime button you push

**Comment by patpol4** [comment]
Also remember to update all maps with this after the turnstiles are merged

**Comment by maxion12345** [comment]
> Also remember to update all maps with this after the turnstiles are merged

not all maps will have enough room for a genpop cell but I'll see what I can fit

in other news, I made nice lines to separate the different crime categories

**Comment by maxion12345** [comment]
added some new icons, and got crimes to add onto eachother. the timer still doesn't wanna work out correctly though yet
and the list of applied crimes is pretty ugly

**Comment by maxion12345** [comment]
can't seem to get crime stacking work properly. Basically, instead of doing 1+1, it does some weird math bullshit and ends up with 1.1
and then 1.1000000000009888 or whatever
It's that division thing but removing it just fucks it all up even more
https://i.gyazo.com/485dd96e93b4928201dd59d6cf237c5a.mp4
heres a video

**Comment by patpol4** [comment]
Just round it? Do we really need decimals for crime stacking?

**Comment by JamieD1** [comment]
Use rounding to minutes instead of using seconds.

**Comment by maxion12345** [comment]
I'll start working on this again soon, still gotta get turnstiles wrapped up so we can move em into this pr

**Comment by maxion12345** [comment]
got crime stacking working, epic poggers moment
issue was that MINUTES is SECONDS*60, and seconds is *10, but it was already seconds so it just added a zero and did *60

**Comment by maxion12345** [comment]
THE
LINTER
IS
GREEN

**Comment by maxion12345** [comment]
NEW MAPS (turnstiles to be added later)
Yogurtstation: Turned two cells into genpop, one left for "problematic prisoners"


Meta: has basically the same layout as yogurtstation so I added a genpop here


Kilostation: just changed the terminals and lockers to genpop and added flasher button under em


Delta: Only two cells so no room for genpop

**Comment by maxion12345** [comment]
waiting on turnstiles before this goes any further
soontm

**Comment by maxion12345** [comment]
fucking 
WHY

**Comment by maxion12345** [comment]
why is it that every time I change a map it gets conflicts
im sad

**Comment by maxion12345** [comment]
there we go 
now I gotta go re-do all the work

**Comment by maxion12345** [comment]
im going to go fix all the shit thats wrong and then open another PR, this isn't working whatever im doing

**Pull request closed without merging**
