### PR TITLE
Adds a tan detective coat and fixes other detective coats

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Adds a lighter detective coat because there aren't many bright colors in the detective's stash. Follows the exact same patterning as the OG coat, just in a lighter tone.

In addition, this PR fixes the weird sprite glitches with the other two trenchcoats because they weren't lizard-friendly for some reason.

# Spriting
Mob Sprites:
image
image
image
image

In-Hand Sprite:
image

The Dubious Creature:
image
image
image
image

# Wiki Documentation

Don't think any of the coats are documented anywhere, could maybe add this and others under gear in the Detective page, though that seems largely unnecessary and like a lot of bloat if all alternative uniforms were to be documented (consider heads of staff then as well).

# Changelog

:cl: Skrem_7, @nmajask for sprites
bugfix: Fixes the weird digitigrade sprites for the default and grey trenchcoats for detective
imageadd: Adds a brighter coat for those beachside detectives
/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]

**Review by KillerOrcaCora — APPROVED** [review]
For some reason, only one of the coats has an in-hand sprite; ill deal with that later for now need you to create one only for what you're adding.

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
what I said above stupid buttons

**Comment by Skrem7** [comment]
> For some reason, only one of the coats has an in-hand sprite; ill deal with that later for now need you to create one only for what you're adding. 

Should be one for the new one, unless you mean a mob sprite for holding it.

**Comment by KillerOrcaCora** [comment]
Yes a mob sprite for holding.

**Review by KillerOrcaCora — APPROVED** [review]

**Pull request merged**
