### PR TITLE
Ports antag info UI from TG

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Ports "Dissecting Biddle Traitors: Toned down traitor flavor + antag info tgui"

https://github.com/tgstation/tgstation/pull/60311

Through i don't know how does tgui work and maybe fucked up with everything by brainlessly copiyng code, i pray that it will work.

Also it doesn't include traitor part, because i don't want to fuck with codebase diferensies.

# Changelog

:cl: tralezab, ported by SuperSlayer
rscadd: a few antags now have a tgui menu instead of a greet. spiffy! they include antag info you need.
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
did you test

**Comment by ghost** [comment]
> did you test

I can't test anything ingame, i don't have anywhere to launch it

**Comment by ynot01** [comment]
this means we have to do tgui for every antag that we have that tg doesnt? no ty

**Comment by ghost** [comment]
> this means we have to do tgui for every antag that we have that tg doesnt? 

No?

**Comment by ghost** [comment]
> this means we have to do tgui for every antag that we have that tg doesnt? no ty

Actually it just makes so that if you want you can add a tgui window to an antagonist, to make them have a button to show it. You are not forced to add it, but it makes so it is possible if you want.

**Comment by Bibby0110** [comment]
We don't have TypeScript support for TGUI

**Pull request closed without merging**
