### PR TITLE
Ports stasis beds from TG

### PR DESCRIPTION
**Pull request by SomeguyManperson**
image
:cl:  JJRcop and Kmc2000 (sprites) for the code, theos for porting and QoL stuff
rscadd: Adds the stasis bed, a medical machine that can stabilize a patient and stops the body from deteriorating after death
rscadd: The stasis bed is capable of being used as a fully functional surgical platform, though the patient will need to be buckled to it to apply advanced surgeries
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
that wasn't supposed to happen

**Comment by fluffe9911** [comment]
why would you do dis

**Comment by SomeguyManperson** [comment]
because random crits are out of scope for this PR

**Comment by Altoids1** [comment]
Theos is the best mirrorbot

**Comment by MegaEmpirical** [comment]
Uhh, is this a replacement of sleepers? Or we just adding the content?

**Comment by SomeguyManperson** [comment]
Ok it's been funny enough by now. No, sleepers are not being removed. The stasis bed is being added as a standalone medical upgrade.

**Comment by SomeguyManperson** [comment]
For fucks sake the stupid vore removal pr is causing cancer since the stomach proc doesn't exist any more

**Pull request merged**
