### PR TITLE
The syndicate has come out with a new combat mech prototype: The Black Mamba

### PR DESCRIPTION
**Pull request by Mqiib**
It's a sidewinder, but silent and can use guns. That's it. HOWEVER it does come with two COOL NEW WEAPONS:

1: A carbine that fires venom rounds, same as from the c-20r!
2: Stabby knives that inject venom! (see a theme here?)

All for the low low price of 75 tc!

# Why is this good for the game?

Cool new nukie mech that is a bit different from the others and relies on venom instead of brute force. Variety is fun!!!! Also it's a cool sprite!!!!

# Testing

image
image

And the cooldown works:
image

# Spriting

New sprites for the two weapons as well as for the black mamba itself:
image
image
image
image

# Wiki Documentation

Weapons:
"Snakebite" Carbine: Identical to hades carbine but fires c45 venom rounds (20 damage, inject 4u of venom on hit)
"Razerfang" Dual Daggers: lunge attack (5s cooldown), double strike, -25 damage (min 10) with 80(!) ap, injects 12u of venom on a 5s cooldown, slow attack speed

Black Mamba: Same numerical stats as sidewinder across the board, but moves silently and can mount guns

# Changelog

:cl:  
rscadd: Adds the new Black Mamba for nuclear operatives to play with
rscadd: Adds two new venom-related weapons for the Mamba

/:cl:

### CODE REVIEW

**Comment by PibeCantina** [comment]
What are the hp and armor values of it?

**Comment by Mqiib** [comment]
> What are the hp and armor values of it?

image

**Comment by Mqiib** [comment]
Bonus points if you can figure out all three references in the name of the daggers

**Comment by RG4ORDR** [comment]
Mqiib once again taking my inane ramblings and turning them into gold.  
I highly await the salt mining that this exosuit will bring.

To anyone who thinks the sidewinder is OP - you aint seen nothing yet.

**Comment by Hislyna** [comment]
Yall are voting up on this, but I cannot WAIT for yall to whinge on how powerful this is, and how mechs should be removed, and theyre unfun~

**Comment by MajManatee** [comment]
image

**Comment by DeadlyBag** [comment]
Venoms pretty fucky especially when you can apply it in big doses
12u per hit on the blades seems like a ton (especially if the blades themselves already deal 20 damage)
and being able to just back off with a fast mech and then continuously  reapply 4u of venom with the Carbine seems strong

Hard to tell how strong the venom would be without having seen the mech in action though

**Comment by Mqiib** [comment]
> Venoms pretty fucky especially when you can apply it in big doses 12u per hit on the blades seems like a ton (especially if the blades themselves already deal 20 damage) and being able to just back off with a fast mech and then continuously reapply 4u of venom with the Carbine seems strong
> 
> Hard to tell how strong the venom would be without having seen the mech in action though

The venom injection on the daggers has a 5 second cooldown so you can't spam it super easily, and on top of that the lunge has the same cooldown. I plan on doing a little bit of thunderdome testing once this gets merged since nukies are relatively rare so I might be able to see if it's a bit TOO much. But remember, this is 75 tc that is competing with all the other incredibly powerful nukie weapons so it kind of needs to be really good to be worth it.

**Comment by JamieD1** [comment]
@Mqiib Conflicts, but good to go after that.

**Review by JamieD1 — APPROVED** [review]

**Review by cuackles — APPROVED** [review]
@Moltijoe

**Pull request merged**
