### PR TITLE
ports the syndicate ban hammer from hippe

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
it adds a damaging ban hammer that does 20 damage per hit to the uplink under the stealth item section for 8 tc when you hit someone it makes no noise but it sure packs punch

original item and shit were made arzion5 on hippie
https://github.com/HippieStation/HippieStation/pull/4230 original pr
#### Changelog

:cl:  
rscadd: ports hippie hammer
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Seven tc for twenty damage? You gotta raise that price man, or make it buyable when it's a higher pop only.

**Comment by boodaliboo** [comment]
i make more expensive

**Comment by fluffe9911** [comment]
give proper credit (link to pr and author name in body)

**Comment by boodaliboo** [comment]
> give proper credit (link to pr and author name in body)

sure one sec

**Comment by HomocidlePancakes** [comment]
M e h

**Comment by ynot01** [comment]
changing my thumbs up to thumbs down because why the FUCK would i spend 14TC on this when i could buy a 10TC 3-hit-crit katana or a revolver (13TC) (imagine using revolver as a balance point) or a stechkin+silencer or ebow or anything else that does this job but better? if you go 2TC higher you literally have a desword even

the 100 armor pen is nice and all but the second that blue health doll goes bluen't people are going to notice, not worth 14TC at all

**Comment by HomocidlePancakes** [comment]
I didn't even look at the stats. It's just an item with it's damage value VV'd. Meh. Katanas are at least cool.

**Comment by ghost** [comment]
Increase damage to 25, yog players are more unrobust on average than hippie players.

**Comment by alexkar598** [comment]
Im done with the low effort this but with damage traitor items. No thanks.

This is absolute cancer from gameplay point of view,someone in a UI has no chance to reply to this and before you nerds start talking about the katana,its next on the chopping block pun intended.

**Comment by ghost** [comment]
@alexkar598 

You do realise this item causes a loud-ass bwoink and a massive red message to appear on the screen, right?

**Pull request closed without merging**
