### PR TITLE
Removes cluwne mask from autodrobe and disables cluwning on equip

### PR DESCRIPTION
**Pull request by ThatLing**
Why is this a thing when cluwnes are valid?

### CODE REVIEW

**Comment by fluffe9911** [comment]
The one in the autodrobe is a variant of the cluwne mask that can only be found in the autodrobe that only has a 1% chance to turn a person into a cluwne ye meme

**Comment by fluffe9911** [comment]
You are aware of that right? I mean if the 1% thing is bothering you I can just remove that instead of completely removing it from the autodrobe lol

**Comment by ThatLing** [comment]
It's more about the fact that people confuse this with real cluwnes and since cluwnes are valid, kill the person wearing the mask

**Comment by ShadowDeath6** [comment]
why not just make cluwnes not valid

**Comment by fluffe9911** [comment]
Ehhhhh I mean cluwnes also have a cluwne suit and shoes which are ONLY available to actual real cluwnes so if someone kills a person for wearing the autodrobe one its going to be because of ignorance or being silly

**Pull request merged**
