### PR TITLE
Attempts to fix dynamic wizard again

### PR DESCRIPTION
**Pull request by Xoxeyos**
- Raginmages.dm and spare wizard.dm file is no longer held in yogstation/code, now just in /code/.

- ROLE_RAGINMAGES & ROLE_BULLSHITMAGES are now made specifically for their roles.

- Vampires, Traitors, BB, and Changelings now all cost the same threat.

:cl:  Xoxeyos
rscadd: ROLE_RAGINMAGES and ROLE_BULLSHITMAGES  
tweak: Antag threat costs, and raginmages.dm has been relocated to /code/ instead of yogstation/code/
bugfix: Just tries to make Ragin and Bullshit wizards behave appropriately.
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Can you confirm the bullshit and raging mages are going to be rare as fuck.. they are supposed to be admin spawned only for a reason

**Comment by Xoxeyos** [comment]
Yeah, I can see if I can make them even rarer, I may just keep both on 100 Threat.

**Comment by Xoxeyos** [comment]
Alright, it's done.

**Review by fluffe9911 — APPROVED** [review]
2nd times the charm

**Pull request merged**
