### PR TITLE
removes food erp

### PR DESCRIPTION
**Pull request by Ktlwjec**
it said "deep throat" this is absolutely DISGUSTING we are a NO ERP server!!!

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
awww.......

**Comment by thehighwayman** [comment]
since when are we not ERP?

**Comment by Nickvr628** [comment]
Can we close this meme PR? We are not a baby hugbox server

**Comment by deadmomo69** [comment]
don't ruin the sausage deepthroat meme you prudes

**Comment by patpol4** [comment]
What the fuck

**Pull request merged**
