### PR TITLE
Re-adds/Fixes Light Pink Stabilized Slime Speed Buff 

### PR DESCRIPTION
**Pull request by burn1cycle**
As it was working correctly in TG and the description had claimed it provided a speed buff many people considered this a bug until a coder stepped forward and said they removed it.

Speed enhancement will be 0.54 . For comparison Meth speed is 1.00 and DNA vault speed is .76

also Github sucks ass, it's Githubs fault if this PR is funky but it works totally fine.

### CODE REVIEW

**Comment by Marmio64** [comment]
speed buff should at the very most be 0.33, since there is no downside whatsoever for using it, and it isn't as hard to get the DNA vault. DNA vault also doesn't have a guaranteed chance to net you a great ability like the speed buff and could get you a pretty mediocre one instead.

**Comment by ToGWtF** [comment]
Really against any more movement speed buffs

**Review by JamieD1 — APPROVED** [review]

**Comment by Georgeur** [comment]
The movement speed really requires in game testing, as it would with all pr's like this, just a number alone will be arbitrary until seen in practice by the general player base. But considering for all intensive purposes, this is fixing a bugged item, and making it do exactly what it says it should do, it's a productive PR.

**Review by jcatjmeow — APPROVED** [review]
> Really against any more movement speed buffs

I am also against this.
But, the code's fine. I tested it, and it seems reasonable at least in a vacuum. So have my approval AND my thumbs down! Take that!

**Comment by ghost** [comment]
i'm the one who removed it and if it gets merged i'll remove it again

**Comment by burn1cycle** [comment]
I'm kind of mad at all of you and Adam's incompetence specifically(fix item descriptions when you change item function!). I took one look at the item description "it makes you go faster" and knew how it's supposed to function in TG, tested it for that and it failed. It took me 9 hours of struggling with code and github but the item now functions correct to it's item description.

 Merge it for a week at least, please. We can pull it or turn the speed down after.

**Comment by FatalEYES** [comment]
Just add and remove it weekly, let it rotate in and out duh.

**Comment by ToGWtF** [comment]
With new fireman carrying, and dragging speed slowdowns, I would rather have this remove the movement speed penalty of dragging a body rather than full-time speed-up

**Comment by Georgeur** [comment]
Adam cant remove or add shit on his own even if the coders never hold him to his comments when proven wrong. Don't get me fucking started when it comes to xenobio stealth nerfs, just look at PR #5171 / issue #5164. Quite a few PR's are making people think shit is bugged when its just been stealth nerfed.
Fix this fucking item, or don't make shitty stealth nerfs.

**Comment by Georgeur** [comment]
In light of @LoliconSlayer PR. I suggest dropping the speed mod to 0.05-0.1
passive speed boost is powerful and fitting with the slime cores intended use, it should be used to escape an attacker when both not effected by hurt slowdown, or to remove the slowdown when carrying a body

**Comment by Georgeur** [comment]
also yes the reason I was given when bringing this up, the reason why loliconslayer made the PR was, adam made a mistake, blame maintainers. You're 100% right to be annoyed by this crap.

**Pull request closed without merging**
