### PR TITLE
Changes Yogs' 99% Lag Free!! to 386% Lag for Free!!

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

It will attract more players.

# Changelog

:cl:  
tweak: Changes up Yogs' status display
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
PR of the century

**Comment by murder357** [comment]
even better

add [DDOS] in it too so players emotions are balanced perfectly

**Comment by Therandomhoboo** [comment]
Get this man Senior HC already, Based PR. Speed merge when?

**Comment by Bibby0110** [comment]
not funny

**Comment by solwashere** [comment]
I think it's very funny

**Comment by Necrosium** [comment]
Not only funny but makes a lot of sense, just remember our record has surpassed the 1000% time dilation though, highest one I've personally seen was about 695% I think

**Pull request closed without merging**
