### PR TITLE
RCD can now spit out Catwalk

### PR DESCRIPTION
**Pull request by warface1234455**
# About PR
When you want to move around in space or do some wiring but are too lazy to acquire lattice, you may use a catwalk instead of laying tile since it is less expensive. Tile costs 3 and Catwalk only costs 1 for RCD

# Wiki Documentation
RCD can place catwalk now

# Changelog

:cl:  
rscadd: RCD can now place catwalk!
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
I'm pretty sure catwalks are generally more expensive than platings when building without RCDs, since they require 2 rods instead of a rod + a tile

**Comment by warface1234455** [comment]
> I'm pretty sure catwalks are generally more expensive than platings when building without RCDs, since they require 2 rods instead of a rod + a tile

ok thats kinda true but uh 1 metal into 2 rods is kinda dumb, it literally reduced the size just for two sticks

**Comment by warface1234455** [comment]
whatever

**Comment by warface1234455** [comment]
pointless pr anyway

**Pull request closed without merging**
