### PR TITLE
Robotics Refresh V2 (Jamie and Fatal Edition)

### PR DESCRIPTION
**Pull request by FatalEYES**
### Intent of your Pull Request

"To makes robotics not shit." - Jamie 2020
Refreshes the robotics lab in such a way to be a little more efficient and visually appealing(imo) while still taking up the same space.

### Why is this good for the game?

It's OUR own personal robotics lab, I don't see that as any bad thing.

#### Changelog

:cl:  
rscadd: Added a whole new robotics lab
/:cl:

### CODE REVIEW

**Comment by FatalEYES** [comment]
Screenshot_1

**Comment by bowlofcereal** [comment]
not bad actually

**Comment by jcatjmeow** [comment]
I like it! But you messed up your pr. Not sure what happened but...I think you may have pushed the wrong branch?

**Comment by PrinceKirze** [comment]
i love the lobby. good shit

**Comment by FatalEYES** [comment]
OKAY ITS HERE NOW

**Comment by alexkar598** [comment]
TBH it feels rather cramped. The decal spam doesnt help either, theres alot going on here.

**Comment by Tipy1802** [comment]
Outstanding work, I really like the lobby! I do kinda miss the conveyors but nobody else really used them

**Comment by Mesalikepie** [comment]
I like how it looks but I also agree with alexkar and it looks cramped

**Comment by JamieD1** [comment]
> I like how it looks but I also agree with alexkar and it looks cramped

Can you explain how?

**Comment by JamieD1** [comment]
> TBH it feels rather cramped. The decal spam doesnt help either, theres alot going on here.

Can you explain how?

**Comment by Tipy1802** [comment]
I do agree the work station is too cramped like only one square per machine but it's not that bad

**Comment by patpol4** [comment]
The long horizontal danger line looks super weird imo, I'll try to make this a bit prettier with decals when i do the review, just please dont merge this without a review.

**Comment by patpol4** [comment]
@ynot01 you're the biggest robo main i know, what do you think of this?

**Comment by alexkar598** [comment]
I explained how, it looks very cluttered and small. Probably a result from the spam of decals everywhere making the floor pattern very chaotic

**Comment by Moja10** [comment]
I like conveyors

**Comment by Moja10** [comment]
I like PR

**Comment by redmoogle** [comment]
Local man accidentally fails at merge conflict

**Review by patpol4 — CHANGES_REQUESTED** [review]
chrome_8nazJ8BZr9
:thinking:

**Comment by FatalEYES** [comment]
Screenshot_1
The current iteration of it, hopefully a bit less cramped. Now with added mech bay light switch.

**Review by patpol4 — APPROVED** [review]
You really got to start naming airlocks properly. 
chrome_7Np3Ma5gnv
I didnt change the bottom decals in the end, just added some at the top, aside from that, added shutters for surgery, moved some buttons, the request console, added vents, firelocks, moved things, moved stuff, considered adding some transport belts but eh. 
To be honest with you i personally don't like it, bit too wide for my taste.

**Pull request merged**
