### PR TITLE
gives cherry bombs sulfur

### PR DESCRIPTION
**Pull request by boodaliboo**
someone asked for this in discord a bit back
:cl:  
rscadd: gives cherry bombs sulfur
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
like
I'm fine with this
but...why?

cherry bombs are not crew accessible since it turned out giving botany infinite black powder was a smidge overpowered

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Undocumented changes

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
has extra random stuff

**Comment by JamieD1** [comment]
Reopen when you do it properly or document the rest of the changes

**Pull request closed without merging**
