### PR TITLE
Revert "Revert "renames broodmothers back to midwives""

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#7902
there was no reason to name them broodmothers, and i think midwife sounds better.

theres also a spider in hollow knight called midwife so

Changelog
🆑 Identification
spellcheck: Broodmothers are called midwifes again.
/🆑

### CODE REVIEW

**Comment by ThatLing** [comment]
I'll self-close it

**Comment by LoliconSlayer** [comment]
> There was no reason to name them Broodmothers

Broodmother is a fucking common term in games for a large spider that gives birth to other spiders

> Midwife sounds better

Midwives assist in the birthing process, they don't do the birthing themselves

> There's a spider in hollow knight called midwife so

There are also spiders called Broodmother in: Dota 2, ARK Survival Evolved, Darksiders, Fucking World of Warcraft

In short: Shit reasoning, Broodmother makes way more sense than midwife

**Comment by Bibby0110** [comment]
no

**Comment by Ktlwjec1** [comment]
Actual non-issue so going by up/downvotes.

**Pull request merged**
