### PR TITLE
The round ends when the MALF is destroyed (Only applies to solo MALF rounds).

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Document the changes in your pull request

Killing the MALF ends the round.

The justification here is that most MALF AIs are so destructive in their goals, the station is near beyond salvaging and killing a MALF AI always results in an immediate shuttle call (to beat code delta) or because the destruction is so extreme. It would kind of like be making it so that nuke ops doesn't end the round when the operatives are killed; regardless of how bad the destruction the station is, the shuttle will be called anyways.

It's also unfair to people who get midrounded as well as to anyone left in the round because a lot of the high value items are stolen and the remaining survivors are gamered out on gear.

# Changelog

:cl:  BurgerBB
tweak: Killing the MALF ends the round.
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
Maybe instead of the round ending immediately, an un-recallable 5 minute shuttle is called? So there's time for people to wrap things up.

**Comment by ThatLing** [comment]
> It's also unfair to people who get midrounded

And ending the round early with little to no warning is fair?

**Comment by MajManatee** [comment]
> > It's also unfair to people who get midrounded
> 
> And ending the round early with little to no warning is fair?

See: Revs, Nukies, Clock cult (sorta), darkspawn, shadowling

**Review by MajManatee — APPROVED** [review]
literally just added a pound sign

**Comment by BurgerLUA** [comment]
> literally just added a pound sign

i good coder

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
