### PR TITLE
Standardizes Ratvar's title from "Justicar" to "Justiciar"

### LINKED ISSUE #21205: Clockwork typo
### Severity

Low

### Short Description

Clockwork typos for clockwork things.

### Reproduction

"Servant of the Justiciar" vs "cog lattice. A lightweight support lattice. These hold the Justicar's station together."

Different spellings in different places, former is a legitimate word in most dictionaries, latter is seemingly used in fantasy, should be consistent?

### Round ID

50906

### BYOND Username

Aquir

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
Alright I'm tired of seeing both, we're picking one and sticking to it.
This aims to standardize Ratvar's title to the Clockwork "Justiciar", as it's split between that and "Justicar".
Closes #21205 too (lol)

# Why is this good for the game?
Lore team hasn't pointed out one being more correct than the other when I asked them, so I'm going by the fact that "Justiciar" is mentioned twice for every time "Justicar" is in code, and that it's an actual word, whereas "Justicar" is a fantasy term.

# Testing
Here are some images of the game functioning:
image
image

# Wiki Documentation

And I plan to do the same on the wiki as well. Nothing will be safe!

# Changelog
:cl:  
spellcheck: Standardized all mentions of the Clockwork "Justicar" into "Justiciar"
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
justice car

**Comment by Moltijoe** [comment]
Test it, make sure the dme changes didnt break something

make sure to include screenshots or something
(we're trying to be more consistent with requiring actual testing)

**Review by Moltijoe — APPROVED** [review]

**Comment by AMyriad** [comment]
Images added

**Review by JamieD1 — APPROVED** [review]

**Comment by N3D6** [comment]
Always thought this had a better ring to it

**Comment by AMyriad** [comment]
> Always thought this had a better ring to it

which, the original or the new one?

**Pull request merged**
