### PR TITLE
🦀 OVERTHROW IS GONE 🦀

### PR DESCRIPTION
**Pull request by ynot01**
#### Changelog

:cl:  
rscdel: Removed Overthrow
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
YES

**Comment by ynot01** [comment]
i fixed the fucking conflicts you bot

**Comment by nesisknesis** [comment]
why is this good for the gaem

**Comment by yacabo** [comment]
m a p   d i f f   c o n f l i c t

**Comment by Readystorm546** [comment]
A great and truly astonishing PR i have to say

**Comment by Amelia0010** [comment]
Get the council to change the weight of the gamemode to 0 in the config, I'm not gonna approve removing a gamemode from the code completely unless it has actually been disabled on the server for a while and noone has made an active attempt at fixing it and bringing it back.

**Pull request closed without merging**
