### PR TITLE
NVS Gax 2.0: a little bit of multiz

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Expands Gax engineering and SW maints. Adds areas for maint, and adds a little playground for engineering.

I didn't want to add a whole bunch of multiz elements so it doesn't get too overwhelming. This lets us have a nice testbed where it doesn't matter much so we can find out issues.

chrome_IaNybr10Gm

# Why is this good for the game?
Little bit of multiz to get players adjusted.

# Testing
dreamseeker_nb8lpq7TP2

# Wiki Documentation

Engineering is much bigger, expect this to change more

# Changelog

:cl:  
mapping: Adds a Multi-Z area under gax that stores some maint and engineering.
/:cl:

### CODE REVIEW

**Comment by GDRdev** [comment]
my atmos...

**Comment by ToasterBiome** [comment]
> my atmos...

Explain

**Comment by azzzertyy** [comment]
my medical...

**Comment by Scrambledeggs00** [comment]
Cool besides how any plasma canister mishap will immediately plasma flood all of engineering. Probably a good idea to add an airlock and some walls/windows near the stairs leading to SM so that doesn't happen.

**Comment by AMyriad** [comment]
this is extraordinary tech-wise, I've been wanting to see multi-z in for ages and I'm glad I'm going to live to see it

and for my critique that you're totally going to ignore:
I think it would be best if this part looped, because dead ends in maint suck.
idk, something like this but without it being a 1-tile-wide hallway
image

**Comment by ToasterBiome** [comment]
> this is extraordinary tech-wise, I've been wanting to see multi-z in for ages and I'm glad I'm going to live to see it
> 
> and for my critique that you're totally going to ignore: I think it would be best if this part looped, because dead ends in maint suck. idk, something like this but without it being a 1-tile-wide hallway image

image

**Comment by ToasterBiome** [comment]
Back to when I have time (tm)

**Pull request closed without merging**
