### PR TITLE
Removes "WARNING. THE WAY AI IS PLAYED HAS CHANGED"

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
As title.

# Why is this good for the game?
Its been like this for a very long time now.

# Testing
Two line change

# Changelog
:cl:  
rscdel: Removes the "WARNING. THE WAY AI IS PLAYED HAS CHANGED" message when joining as AI
/:cl:

### CODE REVIEW

**Comment by ofscarletdreams** [comment]
the ai main coming in from like bee or something wondering why they are burning to death:

**Comment by azzzertyy** [comment]
> the ai main coming in from like bee or something wondering why they are burning to death:

L thats on them we dont explain to tg players why chemistry is actually good

**Comment by Yarinoi** [comment]
> the ai main coming in from like bee or something wondering why they are burning to death:

mfw different codebases have differences in their code

**Review by ToasterBiome — APPROVED** [review]
we will have to readd when bibby finishes

**Pull request merged**
