### PR TITLE
Change the poison kit

### PR DESCRIPTION
**Pull request by 00ze-cyclone**
# Document the changes in your pull request

Poison kit is full of neat toxins but it's kind of unuseable (you get ONE syringe so good luck getting any amount of poison in someone) and some of the poisons in it kinda just bloat it: yeah cyanide is neat but it does the same thing as initropidil and curare while being obtainable as crew (it's basically discount curare for crew), fentanyl is piss easy to make, formaldehyde is just useless, 

Now each poison come in a 30u syringe that inject 10u per use, the syringe is labelled and also describe what the poison do so you don't need to pull out the wiki to have a rough idea of what you are using.
Fentanyl, formaldehyde and cyanide have been removed from the kit because things you can already get as crew in the uplink are lame.
Added muscle relaxant to the kit because it's a neat toxin that deserve to be seen more than just in the ebow.
Also replaced the regular syringe with a big syringe to stay in line with the rest.

It also cost one less TC, making it more easy to fit in your budget.

# Wiki Documentation

Poison kit is now 5 TC and contain:
-polonium
-venom
-spewium
-histamine
-initropidil
-pancuronium
-sodium thiopental
-curare
-amanitin
-coniine
-muscle relaxant

All poisons come in special 30u syringes instead of a bottle. Also has one empty 30u syringe.

# Changelog

:cl:  
rscadd: Added large syringe containing 30u, only available in the poison kit, also added muscle relaxant to the kit
rscdel: Removed fentanyl, formaldehyde and cyanide from poison kit
tweak: poison kit has the toxin coming prepackaged in 30u syringes, price lowered to 5 TC
/:cl:

### CODE REVIEW

**Comment by Rdrazga** [comment]
Some notes I mentioned in discord:

-locking non-botany players out of having very powerful poisons in the ‘poison kit’ makes no sense.

-30u syringes adds a lot of annoyance for the lower metabolism chems as you only realistically want to use 5u of them at a time

-‘bloat’ in this kit is a safety net, since these are resources you use up over time, having backups even if they are worse then the main is not a horrible thing
IE: cyanide is not as good as I intripodil but once you use up all your intripodil you can use cyanide as a still powerful poison that can occasionally stun

-the quantity of certain chems in this kit just don’t make sense. Intripodil and coniine can have 6 uses while sodium thio realistically only has 1-2, histamine only has 1, venom has around 3, ect.

**Comment by Sniblet** [comment]
Coniine is extremely powerful and amanitin is pretty interesting and most traitors would appreciate the opportunity to skip having to grow one specific berry mutation branch/mutate a weed to get them
No one's gonna miss formaldehyde and fentanyl though

**Comment by Mqiib** [comment]
Put cyanide, amanitin, and coniine back in the kit.

**Comment by 00ze-cyclone** [comment]
Alright putting back amatoxin and coniine, cyanide is just redundant with initropidil and curare so have muscle relaxant instead.

**Review by ThatLing — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
