### PR TITLE
I fix the spare cabinet access without moving it somewhere dumb

### PR DESCRIPTION
**Pull request by maxion12345**
# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Github documenting your Pull Request

i change something

# Wiki Documentation

no

# Changelog

:cl:  
bugfix: Spare cabinet uses normal captain access now
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
> `req_access = list(20)`

Are you sure this works in map files? `req_access_text` exists presumably because that doesn't work

**Comment by maxion12345** [comment]
> > `req_access = list(20)`
> 
> Are you sure this works in map files? `req_access_text` exists presumably because that doesn't work

Its the same access as the captain's door (20)

**Comment by adamsong** [comment]
But cap's door uses the `req_access_text` variable, I'm not sure this can initialize a list

**Comment by patpol4** [comment]
you need to use the text one

**Comment by patpol4** [comment]
i only skimmed this but #11984 seems to do the same thing but with fireaxe too

**Comment by JamieD1** [comment]
Bad, do it in code initialize instead.

**Comment by JamieD1** [comment]
Code change better

**Pull request closed without merging**
