### PR TITLE
OMG IM GOING TO CRY IM SUCH SAD RN IM SADNESS INCORPORATED :((((

### PR DESCRIPTION
**Pull request by alexkar598**
bruh this sucks who made it a welding mask under a weld proof syndicate hardsuit helmet??? it makes you blind like wtf how do you people live with yourself

image
HOW AM I SUPPOSED TO BURN MY FUCKING CATGIRLS THIS WAY??

### CODE REVIEW

**Comment by UselessTheremin** [comment]
why are you like this

**Comment by alexkar598** [comment]
i dunno mane,

**Comment by Hopekz** [comment]
This is very important

**Comment by Marmio64** [comment]
imagine not pressing the toggle welder mask button

**Comment by Jarod1200** [comment]
Local dude neither turns on the hardsuit helmet nor turns off the welding mask view

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
