### PR TITLE
Networked fibers more like gone

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

feels like a long time coming, vote down if you disagree

#### Changelog

:cl:  
rscdel: Commented out networked fibers
/:cl:

### CODE REVIEW

**Comment by AsV9** [comment]
Why is this a good idea? Please explain in depth.

**Comment by Ratvar** [comment]
I propose you remove all chemical blobs that are ignored by borgs, anyone in spacesuit, make blobbernauths useless and die to stupid shit like double welder damage/extinguishers,

 leave synchronised mesh and networked fibers as the only blobs and then balance them.

**Comment by ynot01** [comment]
> Why is this a good idea? Please explain in depth.

personally I believe that networked fibers is "win mode" and is agreed by all to be the most powerful blob type, as it generates more resources and if you even get close it can just snake out and instacrit you, just for the price of not being able to autogenerate blobs

**Comment by fluffe9911** [comment]
*laughs in emp blob*

**Comment by JamieD1** [comment]
ided rise up

**Pull request closed without merging**
