### PR TITLE
makes cutlass do 20 damage

### PR DESCRIPTION
**Pull request by boodaliboo**
wanted to do a quick pr today dont really care if this or reds is merged
#### Changelog

:cl:  
tweak: tweaked cutlass force 
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Random pirate nerf?

**Comment by boodaliboo** [comment]
> Random pirate nerf?

this doesnt effect the antag pirate in any form this is for the mob drop cutlass

**Comment by alexkar598** [comment]
Why

**Comment by boodaliboo** [comment]
> Why

there bad

**Pull request closed without merging**
