### PR TITLE
Blood Brothers Rework: Objectives for TC

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Blood brothers will now spawn with an empty uplink and a folder that they can open to review or check completion of a custom objective. Each blood brother has their own uplink and folder.

Once a folder objective is redeemed, the brother will be given the telecrystal reward, the objective will be permanently added to their team objectives as an incentive to keep it completed, and a new folder will be spawned in a random location that they will be told of and have to go seek.

Each folder can spawn a new folder up to two times, giving the brother team up to 6 additional objectives (or 9 if a three-person team)

Easy objectives will reward 2-3 TC
Medium objectives will reward 3-5 TC
Hard objectives will reward 5-7 TC

<details>
  <summary>Easy Objectives</summary>

- Download research nodes
- Kill a pet
- Steal 28 moles of plasma (full tank)
- Steal an unused slime extract

</details>

<details>
  <summary>Medium Objectives</summary>

- Kill someone once
- Steal a reflective jacket
- Steal a hand teleporter
- Steal CE magboots
- Steal a medal of captaincy
- Steal the hypospray
- Steal reactive tele armor
- Steal secret documents

</details>

<details>
  <summary>Hard Objectives</summary>

- Kill an AI
- Steal antique laser gun
- Steal HoS gun
- Steal captain's jetpack
- Steal nuke disk
- Steal an AI
- Steal the blueprints
- Steal the blackbox

</details>

<details>
  <summary>Images</summary>

Display

Completion & next location

Finding next folder

When you have exhausted your allotted objectives

</details>

# Changelog

:cl:  
rscadd: Blood Brothers now each spawn with an empty uplink and objective folder that lets them do additional objectives for TC
spellcheck: assasinate -> assassinate pets
bugfix: Fixed a bunch of objectives runtiming if they couldn't find what they wanted
tweak: Made caplaser objective 10 difficulty from 5
tweak: Made captain's jetpack objective 10 difficulty from 5
tweak: Made nuke disk objective 15 difficulty from 5
tweak: Made reflective vest objective 5 difficulty from 3
/:cl:

### CODE REVIEW

**Comment by UltraBigRat** [comment]
Why is stealing cmos hypo or rds reactive teleport put as medium, while ce's blueprints are hard? Also why do the folders spawn in random locations that may just be completely out in the open? that sounds like itd just get picked up by a random assistant.

**Comment by ynot01** [comment]
> Why is stealing cmos hypo or rds reactive teleport put as medium, while ce's blueprints are hard?

It is based on their difficulty rating, which was unchanged here (except reactive teleport armor was made easy->medium)

**Comment by ynot01** [comment]
> Also why do the folders spawn in random locations that may just be completely out in the open? that sounds like itd just get picked up by a random assistant.

Folders are spawned in locations where no one can see them for 12 tiles. You are told where it is so you should go for it quickly, lest someone pick it up before you. Most people will find a random folder uninteresting anyways.

I added the random location mechanic to add a bit of spice to the whole objective hunting ordeal. You now have to go somewhere, something to do, a little risk, maybe you'll have to break in, and what if someone takes it? What if another *syndicate* takes it and completes the objective themselves? Many fun possibilities

**Comment by MajManatee** [comment]
blood brother is now off-brand contractor

kinda goes against the orignal idea of them "Having to prove themselves" in order to be made full agents, however this makes it actually seem fun so im down

Also, hopefully something like this will lay the ground work and allow normal traitors to automatically get more objectives.

**Comment by Hislyna** [comment]
I feel that them getting 9 objectives if a trio might be a little overpowered depending on the objectives, but I love the idea none the less!

**Comment by Therandomhoboo** [comment]
Do they share the telecrystal or do they each get one? Cause if so, I think that is a little too strong. Since basically the point of blood brothers was to prove themselves and basically giving them the ability to purchase tator items on top of working together would make them formidable and be able to take over a lot easier. Especially since blood brothers usually spawn with tators making it more incentive for tators to team up with blood brothers.

**Comment by ynot01** [comment]
> Do they share the telecrystal or do they each get one? Cause if so, I think that is a little too strong.

Each blood brother gets one folder, when a folder is redeemed it turns into telecrystals

> Since basically the point of blood brothers was to prove themselves

Shitty design excuse, this is a real antagonist and should be treated as one. Weaker than traitors is understandable but being 2-man revs isn't.
and besides, what better way to prove yourself by completing several objectives and getting rewarded for it?

**Comment by Therandomhoboo** [comment]
> Shitty design excuse, this is a real antagonist and should be treated as one. Weaker than traitors is understandable but being 2-man revs isn't. and besides, what better way to prove yourself by completing several objectives and getting rewarded for it?

I don't think it is wrong to reward them but for 10-15 TC (that is if you get 1 easy ,1 med, 1 hard lets say) I think it might topple the balance especially since most BB's are spawned with other antags. However, I guess the downside is that the folders are spawned in random places so it could maybe be picked up so I guess thats the con to it, but i also feel like once people start knowing what random folders equate to, maybe some meta-ing will happen?

**Comment by ynot01** [comment]
> I don't think it is wrong to reward them but for 10-15 TC (that is if you get 1 easy ,1 med, 1 hard lets say) I think it might topple the balance especially since most BB's are spawned with other antags.

A pair of brothers should be equivalent to a traitor. So if the both of them, through hard work, get 20 collective TC, then that is optimal. Contract kit has similar scaling but you don't see anyone complaining about it because working with 0 TC to get objectives done is difficult as hell, even with a head start of some items.

**Comment by KingSuperBOB** [comment]
It does filter out areas clockies cant teleport to for the folders but I can still see issues with bad folder spots such as the armory or literally just 12 tiles away from someone but in the middle of the hall where someone can walk 5 tiles and see a random suspicious folder (which if they know about the PR) will pick up

**Comment by ynot01** [comment]
> It does filter out areas clockies cant teleport to for the folders but I can still see issues with bad folder spots such as the armory 

Clockies are not intended to be able to teleport into the armory, if they can it is a bug

**Comment by ynot01** [comment]
> literally just 12 tiles away from someone but in the middle of the hall where someone can walk 5 tiles and see a random suspicious folder (which if they know about the PR) will pick up

I will personally lay random folders on the floor to fuck with people

**Comment by MajManatee** [comment]
give them a tracker like IAA gets to point them to the folder?

Also in terms of it being a "prove themselves" antag, thats dumb and im all for a re-write of what BB is, if it means the gamemode is actually fun to play.

**Comment by ynot01** [comment]
> give them a tracker like IAA gets to point them to the folder?

A pinpointer would defeat the scenario where another syndicate finds the folder and is able to use it for themselves

**Comment by Hopekz** [comment]
> kinda goes against the orignal idea of them "Having to prove themselves" in order to be made full agents, however this makes it actually seem fun so im down

That lore was created to make the previous changes fit.
Current lore will change to make these changes fit.
Lore in this codebase exists to explain in-game changes in a way that works with the universe/setting.

**Comment by UltraBigRat** [comment]
> > give them a tracker like IAA gets to point them to the folder?
> 
> A pinpointer would defeat the scenario where another syndicate finds the folder and is able to use it for themselves

if anything it would make that scenario more interesting, causing conflict between them as the blood brothers would have to try to get it back. Otherwise its just  your only way of getting tc is gone and you have no way to find it. Stealing it SHOULD be risky.

**Comment by MajManatee** [comment]
Plus the inevitable shmuck assistant powergamer that picks it up to deny someone TC would be able to be tracked, and shot in the head.

**Comment by Marmio64** [comment]
honestly should change the whole blood brother flavor text and name and whatever for this eventually if this is merged

**Comment by kooarbiter** [comment]
this is just tg prog traitor, but kinda worse, because in tg prog traitor all of your objectives are handled in a tgui menu you can drag and drop objectives in, and when completed you can redeem it from the same menu and automatically get tc beamed into your uplink. This version you have more random search fodder which is likely to get some blood brothers fucked over at round start, and if security finds the folder then they have to raid the most armed department for stuff they EARNED. I think TG got rid of prog traitor because it just involved people getting super safe and boring objectives like killing pets and making grafiti, which ended up not contributing to the round at all.

**Comment by ynot01** [comment]
Inferno

**Pull request closed without merging**
