### PR TITLE
Removes borgs

### PR DESCRIPTION
**Pull request by Bibby0110**

### CODE REVIEW

**Review by adamsong — DISMISSED** [review]
This reintroduces a bug fixed in the original PR

**Review by JamieD1 — DISMISSED** [review]
This reintroduces a bug fixed in the original PR

**Comment by adamsong** [comment]
Meme PR

**Comment by nmajask** [comment]
Jesus

**Review by adamsong — DISMISSED** [review]
Atomize these changes

**Comment by KillerOrcaCora** [comment]
A fight between gods is what we are seeing here folks.

**Review by nmajask — COMMENTED** [review]
This reintroduces a bug fixed in the original PR

**Comment by Bibby0110** [comment]
> This reintroduces a bug fixed in the original PR

hmm

**Comment by N3D6** [comment]
this is my favorite pr

**Comment by JamieD1** [comment]
Bibby has been removed from Maintainer for a week.

**Pull request merged**
