### PR TITLE
Redesigns Seed Vault Ruin to look like a ship

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Redesigns the general design looks like a ship now. Also has some extra room to do stuff in
image

# Wiki Documentation

Looks different now

# Changelog

:cl:  
tweak: Seed vault redesigned
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Buncha empty room with nothing to really put there, while making the main place they'll be in (the botany area) incredibly tiny, while also forcing them to go much further to get to their biogen and such? This just seems like it makes it all a hassle and much more cramped when you just want to do botany stuff, unless you're willing to wrench and move everything over to the big room.

**Comment by redmoogle** [comment]
> Buncha empty room with nothing to really put there, while making the main place they'll be in (the botany area) incredibly tiny, while also forcing them to go much further to get to their biogen and such? This just seems like it makes it all a hassle and much more cramped when you just want to do botany stuff, unless you're willing to wrench and move everything over to the big room.

What if I swapped the middle and bottom room

**Comment by Marmio64** [comment]
> > Buncha empty room with nothing to really put there, while making the main place they'll be in (the botany area) incredibly tiny, while also forcing them to go much further to get to their biogen and such? This just seems like it makes it all a hassle and much more cramped when you just want to do botany stuff, unless you're willing to wrench and move everything over to the big room.
> 
> What if I swapped the middle and bottom room

would make it a lot better

**Comment by redmoogle** [comment]
> > > Buncha empty room with nothing to really put there, while making the main place they'll be in (the botany area) incredibly tiny, while also forcing them to go much further to get to their biogen and such? This just seems like it makes it all a hassle and much more cramped when you just want to do botany stuff, unless you're willing to wrench and move everything over to the big room.
> > 
> > 
> > What if I swapped the middle and bottom room
> 
> would make it a lot better

done

**Comment by Cartlord** [comment]
The seed vault isn't really a ship in the way that the free golem ruin is a ship, though - the seed vault isn't meant to take off, it's just meant to land somewhere and stay there while the lifebringers terraform the planet.

**Comment by redmoogle** [comment]
> The seed vault isn't really a ship in the way that the free golem ruin is a ship, though - the seed vault isn't meant to take off, it's just meant to land somewhere and stay there while the lifebringers terraform the planet.

that doesnt exactly justify it not looking like a ship. Also imo it looks strange not being symmetrical

**Comment by SomeguyManperson** [comment]
looks like 3 of the trays got removed

**Comment by redmoogle** [comment]
Meh this doesnt even me interested in working on anymore.

**Pull request closed without merging**
