### PR TITLE
Budget singularity gravitational lensing effects

### PR DESCRIPTION
**Pull request by Kaithyl**
Added a plane master for singularity effects that acts as a render target for a displace filter which is applied onto almost every other plane. Also added a custom displacement map for gravitational lensing which is held as an object by the base singularity class. Also made it immune to radiation because the glow filter was being applied on the displacement map and causing incorrect pixels to distort.

[singularity.webm](https://user-images.githubusercontent.com/90080475/225518818-b85211b3-2cd9-4fe6-ab35-7fd502fd6e82.webm)

# Spriting

Added new sprite to 512x512.dmi

# Wiki Documentation
None required

# Changelog
:cl:  
rscadd: added gravitational lensing distortion effects to the singularity
tweak: edited singularity vars, plane masters, layer defines, radiation component ignore list
imageadd: added gravitational_lensing sprite
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
woopy

**Comment by yacabo** [comment]
Cool as hell

**Comment by iamthesilly** [comment]
Very cool, can't tell if the effect scales with the size of the singularity but that would be even more cool

**Comment by Skrem7** [comment]
when are you adding tail compatible hardsuits

**Comment by Moltijoe** [comment]
visual effect size definitely needs to scale more based on singularity size, the effect is huge for the smallest size, but probably seems big enough for the biggest size

**Comment by Kaithyl** [comment]
The effect already is scaled depending on size, with 0.5 for a stage 1 singularity and 1.75 at stage 6.

**Review by cuackles — APPROVED** [review]
Hot

**Review by cuackles — APPROVED** [review]
sure a second review idk why but yes

**Review by Moltijoe — APPROVED** [review]
i can't seem to find anything wrong with it

**Comment by Maia-J** [comment]
> i can't seem to find anything wrong with it

Narrator voice: He did indeed find something wrong with it

**Pull request merged**
