### PR TITLE
You have to build .357 rounds manually instead of building speedloaders :dab:

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  die
tweak: No more carrying 20 .357 speedloaders, .357 bullets are made individually
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
make it an ammo box like every other ammo type in the autolathe

**Comment by HomocidlePancakes** [comment]
>make it an ammo box like every other ammo type in the autolathe

You do realize that speedloaders are ammo boxes, right?

**Comment by HomocidlePancakes** [comment]
I’d suggest upping the cost of the revolver a bit and spawn it with speedloaders. Have them be empty if you think it’s better.

**Comment by Mr-Space** [comment]
just recycle speedloaders, good PR.

**Comment by Hopekz** [comment]
What now I won't be able to murder the whole station with minimal effort DELETE THIS

**Comment by Xoxeyos** [comment]
Perhaps you should have to craft speed loaders?

You get some metal rods, cable cutters, metal, a welding tool, and some other thing. 

And you can't quick craft it, if it's possible.

**Comment by Hopekz** [comment]
> Perhaps you should have to craft speed loaders?
> 
> You get some metal rods, cable cutters, metal, a welding tool, and some other thing.
> 
> And you can't quick craft it, if it's possible.

This doesn't remove speedloaders from the game to the best of my knowledge. 
You can still buy speedloaders in the traitor panel like buying magazines to every other gun.

**Comment by HomocidlePancakes** [comment]
>You can still buy speedloaders in the traitor panel like buying magazines to every other gun.

Yeah, but 4TC mate. I’d rather buy carp at this point

**Comment by Hopekz** [comment]
> > You can still buy speedloaders in the traitor panel like buying magazines to every other gun.
> 
> Yeah, but 4TC mate. I’d rather buy carp at this point

Isn't the thing with the speedloader that you can re-use it with common station components (printing ammo) and all the other magazines use super special syndicate bullet sizes that can't be gotten outside of TC (or lavaland for 9mm)? 

I can see your argument for this though.
I'd be ok with making that less expensive to around 2-3TC if it bothers people.

**Comment by HomocidlePancakes** [comment]
>Isn't the thing with the speedloader that you can re-use it with common station components (printing ammo) and all the other magazines use super special syndicate bullet sizes that can't be gotten outside of TC (or lavaland for 9mm)?

Umm, no? This never was a thing.

**Comment by Hopekz** [comment]
> > Isn't the thing with the speedloader that you can re-use it with common station components (printing ammo) and all the other magazines use super special syndicate bullet sizes that can't be gotten outside of TC (or lavaland for 9mm)?
> 
> Umm, no? This never was a thing.

This is a thing because you can't construct the syndicate bullet types on the station. 9mm, whatever the rifles use etc. The only thing you can construct is shotgun shells because the crew has shotguns and the revolver rounds because making speedloaders on-station was the feature of this weapon.

**Comment by SomeguyManperson** [comment]
you can build basic 10mm and 9mm rounds as ammo boxes. You cannot build more magazines for pistols though, so you have to take the magazine out and reload it with the ammo box. This is roughly the same thing for .357 rounds except making it more ass to carry 30 rounds as a funny joke

**Comment by Hopekz** [comment]
> you can build basic 10mm and 9mm rounds as ammo boxes. You cannot build more magazines for pistols though, so you have to take the magazine out and reload it with the ammo box. This is roughly the same thing for .357 rounds except making it more ass to carry 30 rounds as a funny joke

Thanks for clearing it up

@HomocidlePancakes  My B

**Comment by boodaliboo** [comment]
I think theos died from a revolver

**Comment by SomeguyManperson** [comment]
The issue is moreso that everyone including the people who use the revolver sya the revolver is stupidly goodand needs a nerf. I haven't died to someone having 20 speedloaders in a while if ever but I have seen replays where people get 20 speedloaders and turn the station to mush

**Comment by Ratvar** [comment]
I like how entire bood's argument is an ad hominem that ignored the issue of revolvers being OP and speedloaders letting you ignore the entire ammo management... and that's basically the only argument people against revolver nerfs will ever have.
Revolver kill sprees are not done often only because 1. It's boring to use 2. People don't know about speed loaders. Not because it's not OP.

**Comment by Hopekz** [comment]
@alexkar598 ;
Do you have any input as to why you don't like this change?

**Comment by ynot01** [comment]
The major advantage revolver based weapons in this game have over magazine-fed ones is that you click a few times less to reload. While it takes unloading the magazine, feeding it with the ammo box, putting it back in, and loading a round in the chamber, it only takes one click of the speedloader to load a revolver. (This assumes you only have one magazine available)

I would not be against replacing the revolver in the uplink with a syndicate desert eagle that has the same damage values but requires you to purchase additional magazines if you want the convenience of having multiple mags for one-click reloading.

Another idea that was discussed in discord: a special cardboard box type that holds only 357 rounds and can hold up to 30 items, so your inventory space isn't completely fucked by this change

**Pull request merged**
