### PR TITLE
[BOUNTY] [ADMIN] admin v admin tickets

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

https://forums.yogstation.net/threads/5-add-admin-v-admin-bwoinking-ss13-server.25197/

you now create tickets when PMing other admins

you can create a ticket by PMing yourself, i left this in intentionally because i know jamie likes to delay the round with self-made tickets, but could be easily changed by a src vs recipient check

### CODE REVIEW

**Comment by Marmio64** [comment]
mortal kombat

**Comment by N3D6** [comment]
CIVIL WAR

**Comment by ToasterBiome** [comment]
is this tested

**Comment by ynot01** [comment]
yes works on my machine

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
