### PR TITLE
Fixes plort machine turning invisible when using a screwdriver on it

### LINKED ISSUE #17046: Plort Redemption Machine becomes invisible when maintenance cover unscrewed
### Severity

Inconvenience

### Short Description

When you use a screwdriver on the Plort Redemption Machine in Xenobiology it becomes invisible

### Reproduction

Use screwdriver on Plort Redemption Machine

### Round ID

44315

### Test Merges

#16989 (likely unrelated)

### BYOND Username

Firewolf34

### Additional information

_No response_

### LINKED ISSUE #17065: Plort redemption machine is permamently invisible after screwdrivering it.
### Severity

Inconvenience

### Short Description

When you use a screwdriver on a plort redemption machine (to upgrade it for instance) it will become completely invisible, and even after using the alt click menu to close it up, it will still be invisible until an admin fixes it.

### Reproduction

1. go to xenobio
2. screwdriver plort redemption machine
3. no matter what it will now permamently be invisible

### Round ID

44358

### Test Merges

#16989 #17049

### BYOND Username

UltraNumeron

### Additional information

_No response_

### LINKED ISSUE #17066: Sepia tinted camera does not work
### Severity

Inconvenience

### Short Description

Sepia tinted camera just acts like a normal one use camera, and does not stop time as it should.

### Reproduction

1. make burning sepia extract
2. turn it into sepia tinted camera
3. take a picture of someone
4. it makes a normal picture and time is not stopped
5. the camera no longer has any pictures left it can take
6. Have spent 10 orange extracts and an adult sepia slime on one normal photo.

### Round ID

44358

### Test Merges

#16989 #17049

### BYOND Username

UltraNumeron

### Additional information

I did also click it around after using it, and yep there is only a standard mode, and no other modes to switch to.

### PR DESCRIPTION
**Pull request by Notamaniac**
# Document the changes in your pull request

Fixes #17065 
Fixes #17046  (dupe issue)
# Spriting

New plort maintenance hatch sprite : credit ~~cuackles~~ orca

# Wiki Documentation

None

# Changelog

:cl:  
bugfix: Plort machine no longer turns invisible when screwdrivered
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
no i did not link the wrong issue shut up

**Comment by cuackles** [comment]
fun fact i gave manatee an icon to fix that issue 3 days ago , so this is legally not my fault B)

**Comment by cuackles** [comment]
ok so viewing the sprite i really like the idea of the orange part being a cover from the circuits and it going up, issue i see is that at the most bottom it breaks the illusion of a cylinder , here specifically 
image
, it also removes the bottom grey part wich i  also see as an issue, thats the issues i see with the desing, maybe the ligthing could use some more work too as the pieces move, if you are willing to do that and do it ping me when its done to give it another review/aproval, that being said if you consider that to much hassle i can give you the one i did and gave to manatee for you to use it instead, that one looking like this 
image
image

**Comment by Notamaniac** [comment]
yeah it was just a quick five minute sprite, I'll just use yours

**Review by MajManatee — APPROVED** [review]
haha oops

**Comment by cuackles** [comment]
eyeyaysidnasjiond
here is the orca aproved version, please update the dmi so we can merge

**Review by Bibby0110 — APPROVED** [review]

**Review by KillerOrcaCora — APPROVED** [review]
Rip

**Pull request merged**
