### PR TITLE
Resprites lizards and digitigrade legs and a lot of jumpsuits and suits and other stuff

### PR DESCRIPTION
**Pull request by Mqiib**
This has taken me longer than is reasonable but it's FINALLY HERE with the help of @Ebin-Halcyon doing MOST OF THE WORK YAAAAAAY!

Resprites include:
Vast majority of jumpsuits and their digitigrade versions
image

Biosuits, lots of softsuits, many armors (vests and security armor stuff), and labcoats. Also includes digitigrade versions of some of these (but not all because I didn't quite have a full set and I'm out of energy).
image
_Ignore the rogue pixels I'll fix those shortly_

A complete resprite of lizards and digitigrade legs in general primarily coming from @Ebin-Halcyon with various tweaks by me.
image
image
image

And finally some tweaks to footwraps, preternis legs, and polysmorph legs to make them fit the new shape. UNFORTUNATELY we will have to wave goodbye to the light tiger stripe tail (for now) as I couldn't make it look good, but I promise to bring it back later when I'm not so drained by this mess.

# Document the changes in your pull request

Resprites for lizards, digitigrade legs, most jumpsuits, many suits (armor vests, labcoats, biosuits, space suits (not hardsuits)), tweaks to various pieces of clothing. Removal of light tiger stripe tail (for now, I'm genuinely sorry about this one).

Follow-up stuff I'll need to work on in later PRs:

- [ ] Digitigrade version of some underwear like boxers because they dont really fit and look goofy
- [ ] Return light tiger stripe tail
- [ ] Use some of these extra sprites I have laying around for cool stuff like skirtlenecks

# Why is this good for the game?

IT LOOKS BETTER

# Spriting

See above

# Wiki Documentation

None, actually.

# Changelog

:cl:  @Mqiib  @Ebin-Halcyon 
imageadd: TONS of updated sprites for lizards, jumpsuits, and some external wear  
imageadd: Some new digitigrade versions of biosuits/armors
rscdel: (Temporary) removed light tiger stripe tails
rscdel: Removes soul
experimental: I can't believe it's finally done
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
man cant deny the lizard leg allegations anymore

**Comment by neeshacark** [comment]
tbh i cant tell a difference

**Comment by iloveloopers** [comment]
digitigrade legs make no sense. are their knees on their hips?

**Comment by cuackles** [comment]
> digitigrade legs make no sense. are their knees on their hips?



No it's still the same place, hell is more up tho

**Comment by cuackles** [comment]
Hell ? Hel ? The funny back part of the foot, English hard

**Comment by Mqiib** [comment]
> Hell ? Hel ? The funny back part of the foot, English hard

The heel

**Comment by Chubbygummibear** [comment]
footcode

**Comment by Yarinoi** [comment]
fetish content




(had to say it)

**Comment by Mqiib** [comment]
It's only fetish content if you fetishize it (you are)

**Comment by cuackles** [comment]
image
:(

**Review by MajManatee — APPROVED** [review]
hmm yes all good
also, a certified "suit.dmi" moment (blame whoever merged #19927)

**Comment by MajManatee** [comment]
engineering jumpsuit looks like pee
idk if intentional or not...

**Comment by Ethan4303** [comment]
you forgor rad suits ;-;

**Comment by Ebin-Halcyon** [comment]
Enjoy it, Yoggers. Spent way too much time doing these myself, lmao.

**Comment by RG4ORDR** [comment]
There's several things I like and dislike here - some are partial, some are total.

Likes: Sec jumpsuits, Void Suits, Biosuit,Cargo jumpsuits are fine + bonus for the miniskirt

Dislikes: 
Armor - I hate these big poofy vests sec has, even the slim version looks worse it's just darkened
Warden's blue jacket is lamer, looks over designed now, lacks that simple blue leather drip I love about it.
Warden's default jacket is sorta fine
Winter jackets look better closed
Captain's stuff looks too dark, like it looks super dark.
Botany is too teal.
Syndicate Space Suits are gross. Helmet is fine


Partial - Labcoats some look good, others look meh. I prefer the old ones, but I like some of the small details on the others.
Engineering is a bit too orange and muted. Yellow looks better

**Comment by TaelynTheLost** [comment]
The Chaplain Crusader armor isn't working properly.  Just shows letters.

image

**Comment by cuackles** [comment]
> There's several things I like and dislike here - some are partial, some are total.
> 
> Likes: Sec jumpsuits, Void Suits, Biosuit,Cargo jumpsuits are fine + bonus for the miniskirt
> 
> Dislikes: 
> Armor - I hate these big poofy vests sec has, even the slim version looks worse it's just darkened
> Warden's blue jacket is lamer, looks over designed now, lacks that simple blue leather drip I love about it.
> Warden's default jacket is sorta fine
> Winter jackets look better closed
> Captain's stuff looks too dark, like it looks super dark.
> Botany is too teal.
> Syndicate Space Suits are gross. Helmet is fine
> 
> 
> Partial - Labcoats some look good, others look meh. I prefer the old ones, but I like some of the small details on the others.
> Engineering is a bit too orange and muted. Yellow looks better

I appreciate this feedback and it will be taken in mind for the review

**Comment by thgvr** [comment]
respect

**Comment by solwashere** [comment]
Not the biggest fan of the new colors for the CMO labcoat and jumpsuit, and it looks odd when you have the labcoat "unbuttoned", but that's more of a small personal gripe and I can live with it

**Comment by Mqiib** [comment]
> Not the biggest fan of the new colors for the CMO labcoat and jumpsuit, and it looks odd when you have the labcoat "unbuttoned", but that's more of a small personal gripe and I can live with it

I might tweak the colors back to be more similar to the original, or closer to the cloak, not 100% sure.

**Review by cuackles — APPROVED** [review]
Any issues that migth come with this pr will be fixed as they are found, lots of sprites on this one so somethig might escape my eye

**Comment by Am37000** [comment]
Not exactly sure what to think about this...

**Pull request merged**
