### PR TITLE
Unreverts #14842, Adds new content to Gax, and fixes some stuff

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Unreverts #14842, which appears to have accidentally been reverted entirely.

- adds shutters to medbay storage, cloning, and genetics, and removes the unusable curtains
- adds buttons in the CMO office to remotely open any shutters in medbay
- fixes missing CMO shutter button
- adds a desk to the paramedic office, and a window into the storage room
- adds doors to the Hop Lobby, and Cargo Lobby
- replaces the hop lobby outer wall with an enclosed garden area
- adds more firelocks to the primary hallway, should be easier to contain a plasmaflood/fire now.
- adds more windows to space in Security (all electrified)
- fixes medbay treatment lacking an APC
- puts the evac sec checkpoint on its own APC
- adds Kreb to arrivals checkpoint
- adds many more random event spawner locations so its harder to metagame where things happen
- adds maint doors to the arrivals and evac sec-checkpoints
- electrified all heads office windows (and the QM's office)
- changes most instances of 1x2 double airlocks into a single double-wide airlock in public areas
- perma now has fireshutters on the windows
- completely redid electrified window wiring in perma, prison cells, and the bridge (wall-wires are bad)
- adjusts the medbay security office so it has better window visibility
- adds one electrified reinforced plasma-glass window to the captain's bedroom (so he can see space better :D )
- does some interior design work to the heads & det & law offices (better carpeting)
- fixes the placement of the CE office disposals so you can reach all the computers
- readds the bridge, cap's, and hop's weapon rechargers
- fixes the APCs and areas for most of the maints
- adds robotics shutters
- pre-wires one solar array (sometimes there's literally noone to do it)
- probably missing some stuff, if you see an undocumented change, poke me and I'll document it

# Changelog

:cl:  
experimental: [Gaxstation start]
rscadd: adds shutters to medbay storage, cloning, and genetics, and removes the unusable curtains
rscadd: adds buttons in the CMO office to remotely open any shutters in medbay
bugfix: fixes missing CMO shutter button
rscadd: adds a desk to the paramedic office, and a window into the storage room
rscadd: adds doors to the Hop Lobby, and Cargo Lobby
tweak: replaces the hop lobby outer wall with an enclosed garden area
rscadd: adds more firelocks to the primary hallway
rscadd: adds more windows to space in Security
bugfix: fixes medbay treatment lacking an APC
rscadd: puts the evac sec checkpoint on its own APC
rscadd: adds Kreb to arrivals checkpoint
rscadd: adds many more random event spawner locations
rscadd: adds maint doors to the arrivals and evac sec-checkpoints
rscadd: electrified all heads office windows (and the QM's office)
tweak: changes most instances of 1x2 double airlocks into a single double-wide airlock in public areas
rscadd: perma now has fireshutters on the windows
tweak: completely redid electrified window wiring in perma, prison cells, and the bridge
tweak: adjusts the medbay security office so it has better window visibility
tweak: adds electrified r-plasma-glass windows to the captain's bedroom
tweak: heads/det/law office carpets have been upgraded/added
tweak: medbay/bridge maints now not all "central" maint
tweak: one solar array comes pre-wired
rscadd: adds shutters to robotics
bugfix: the CE can now reach all three computers
bugfix: re-adds the hop/cap/bridge rechargers 
experimental: [Gaxstation end]
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
- way too many firelocks, notable ones include the ones in viro, the ones in genetics, the ones by the medkits, the ones in cloning, the ones in xenobio, the ones in disposals, the ones in the supermatter (the normal glass seperating the normal floors from the engine area are fine i guess), armory, perma, uhh i think execution? Pretty much any area with a directional window does not get a firelock. I also see a lot of fulltile windows that don't get firelocks either, the only places that really get firelocks on windows are medbay leading from the entrance to the treatment area.
- too many double wide airlocks. At minimum, I'd like cargo to not have any, dorms to have the normal sized ones, and the one removed from science/HOP. Library, Chapel, and Bar can stay, they look very nice there. Also floor decals need to be adjusted for these double wide ones.
- output for toxins test room is weird with the glass, feel free to extend it 1 down to be able to fit it better.
- Don't know how I feel about the maint doors leading into nearly every security area, for a lowpop map this basically means the antag gets free security equipment for basically nothing. at the minimum, the red floor trim needs to be fixed at least. Looking at the other maps, at max you should have the arrivals one and _maybe_ the escape one be accessible from maint and nothing else.
- Evidence is supposed to be a bit private and secure, I'm good with one window facing to space (maybe even electrified) but having 3 + the 2 in the hallway leaves it a bit too open.

Overall looks pretty nice and I like the flooring you've added.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
- lots of firelocks hidden around still in windows, look at map diffs to get a sense of where they are
- tile edge decals incorrect on the maint doors from the two security posts you added doors to, look how other departments merge in
- dun like the double widedoor on hop!
- can you fix this too
image
(look at the floor decals)

the rest looks great thank you

**Comment by VaelophisNyx** [comment]
pretty sure I have everything other than the windows around medbay treatment cleared of firelocks

**Comment by VaelophisNyx** [comment]
ss (2022-08-01 at 02 46 56)

**Comment by VaelophisNyx** [comment]
ss (2022-08-01 at 02 47 35)

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
firelocks still
image
image
image
image
image

**Comment by VaelophisNyx** [comment]
guh
I've removed the fitness room ones like three times now
what the fuck fastdmm

**Comment by VaelophisNyx** [comment]
also the cargo changes in that last screenshot were removal of firelocks

**Comment by VaelophisNyx** [comment]
> also the cargo changes in that last screenshot were removal of firelocks


actually I am a blind fuck

**Comment by VaelophisNyx** [comment]
or not I was on the wrong branch lmao

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
