### PR TITLE
Revert "Resprites the power fist because nothing is better then losing your weapon to the grey floors down below"

### PR DESCRIPTION
**Pull request by Simplehorror**
Reverts yogstation13/Yogstation#16991

the old powerfist sprite was better and as the only person to use this we should revert it

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Oh…he’s actually serious…that’s a damn shame 😔

**Comment by cuackles** [comment]
Lol, no, the fact that you don't like the sprite doesn't make it bad, this new sprite has more clarity , it's notable that is a fist and resembles more the original material, even if we excluded that, being "the only one that uses the item" does not give you the right to decide how something should look, i cannot even think of how you are able to see the news sprite as worst that the old one, the old one way literally a block of grey and black

**Comment by cuackles** [comment]
Adding to that 
IMG_20221208_094429
Not game breaking and not 48 hours

**Comment by MajManatee** [comment]
See above

**Pull request closed without merging**
