### PR TITLE
sacrifices a toolbelt to add an autolathe to the syndicate lavaland outpost

### PR DESCRIPTION
**Pull request by athena413**
image

#### Changelog

:cl:  
rscadd: autolathe in syndicate lavaland outpost
rscdel: oi josuke, i used 『Z A  H A N D O』 to remove the toolbelt from the syndicate lavaland outpost
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
why remove the belt

**Comment by patpol4** [comment]
You could just move the toolbelt though yeah

**Comment by FLME** [comment]
listen sometimes you have to preform a ritual sacrifice in order to get what you need

**Review by Hopekz — DISMISSED** [review]
Undocumented changes
image

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
People scream so move the toolbelt onto the table. I don't _think_ there will be an issue with adding an autolathe, but I'm wary about this so I may revert this PR in the future.

**Comment by JamieD1** [comment]
@FLME

**Comment by Ktlwjec1** [comment]
#8813

**Pull request closed without merging**
