### PR TITLE
Revert "replaces all instances of adult bookcases with religious ones"

### PR DESCRIPTION
**Pull request by ynot01**
Reverts #10779
No longer an issue as of #10853

# Changelog

:cl:  
tweak: Exchanged some religious texts with adult literature
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
No? Literal ban bait

**Comment by ynot01** [comment]
> No? Literal ban bait

??? explain further please

**Comment by alexkar598** [comment]
> Adult fiction


Hmm guess I can put erotic content in here?
*gets banned*
Bro wtf didnt you read the rules?

**Comment by ynot01** [comment]
> > Adult fiction
> 
> Hmm guess I can put erotic content in here?
> _gets banned_
> Bro wtf didnt you read the rules?

the adult section exists independently of this PR, you are in the wrong place amigo

**Review by patpol4 — APPROVED** [review]
Check the library alexkar, adult fiction is for adult books that do not break the rules, not everything has to be erotic

**Pull request merged**
