### PR TITLE
I was just suppose to fix a rogue pixel...D.O.T.A SUIT RESPRITE

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
Look at this man 
image
He looks very uncomfortable being here tonight. 

Resprites the D.O.T.A Suit that I specially told Jamie not to merge yet. 

# Spriting
suitshowcase2
sutishowcase

# Wiki Documentation
suites

# Changelog

:cl:  

imageadd: Never played a half-life game, honestly the series is boring and I rather go play Aseprite. 

/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Went from a Half Life reference to generic sci-fi armor. Sad.

**Comment by KillerOrcaCora** [comment]
Other way around the old one is missing a lot of details.

**Comment by RG4ORDR** [comment]
> Other way around the old one is missing a lot of details.

No you're wrong, that's all that's really it.
It's louder, it's less distinguishable, doesn't even look the HEV suit other than color alone.

**Comment by KillerOrcaCora** [comment]
Yes I had to modify it a tiny bit so it at least half looked like belonged in its dmi

**Comment by LoliconSlayer** [comment]
Might as well remove the suit entirely and replace it with something else

**Comment by RG4ORDR** [comment]
> Yes I had to modify it a tiny bit so it at least half looked like belonged in its dmi

You modified it so much that it's a totally new item. 
Sure make it some new item if you want, but it's not remotely close to the source material it's referencing at all.

**Comment by Moltijoe** [comment]
Despite the newer one being a better sprite, it's a far worse representation
image

**Comment by KillerOrcaCora** [comment]
I don't really care about it perfectly fitting the look of what is referencing, what I care about is it fitting the dmi of sprites its going in. The old sprite is simply not how suits are done anymore.

**Comment by Moltijoe** [comment]
> I don't really care about it perfectly fitting the look of what is referencing, what I care about is it fitting the dmi of sprites its going in.

i mean, i'll never see it, so i don't care either way. just get clearance from one of the other sprite people and it gets in, regardless as to what people think.

**Comment by Marmio64** [comment]
Bruh, this look like enclave power armor 😩

**Review by TheRyeGuyWhoWillNowDie — CHANGES_REQUESTED** [review]
bad

**Comment by Maia-J** [comment]
> bad

Yup

**Comment by BurgerLUA** [comment]
Here is what I suggest.

I will improve the codersprite known as the dotasprite.

Implement the DOTA 2 Suit (MK2) where it is significantly better than the DOTA 1 suit, using a modified version of these sprites.

**Comment by UltraBigRat** [comment]
icky, old one wasnt anything grand because it didnt need to be. It was just good for its purpose.

**Comment by ReddicusDragon** [comment]
I for one enjoy these sprites

**Comment by cuackles** [comment]
ok so, lots of stuff here, so first of all the original sprite does need still a bit more work, more specifically the lower legs (not the shoes tho), and the gloves, that being said apart from those issues it does stick closer to the base material, now for orcas retake on it, it is done with more experience and knowledge on spriting, that being said, it does not look like the original hazardous environment suit, as it took as reference this take one the suit 
image
and it does stick to the reference image in that case, even in that case this suit should be based on the original HE suit, as its a reference to it, even if that wasn't the case i see some issues with the new sprite, this issues being that the design taken on the chest looks warped in a way, as in, you cannot perceive which part is on front of what part, it lacks depth onto it, this only appears on the front and back view, the rest of the sprite is good and stick to orcas reference, tho maybe the arms on the side views could some defining to, on the end, i will not accept this sprite as its clear that, even as a good sprite, a vocal majority does not which for this to be the look of dota suit, i would encourage to give it a recolor maybe and have it stashed for use on another item that wants a bulky and well designed armor, and i would like it for either orca to edit the old sprite to be better developed or the original spriter BurgerLUA to try to polish the issues denoted here, anyway that's that, will leave some time for responses to see if any makes me change my mind and if not the PR will be closed soonish

**Comment by JamieD1** [comment]
kinda annoying how it says the message everytime you wear it, ive seen people take it off and put it on over and over to spam it.

**Comment by Moja10** [comment]
> kinda annoying how it says the message everytime you wear it, ive seen people take it off and put it on over and over to spam it.

Admin issue, same thing can happen with constant shuttle early launch noises but that's a bwoinkable and bannable issue.

**Comment by JamieD1** [comment]
> > kinda annoying how it says the message everytime you wear it, ive seen people take it off and put it on over and over to spam it.
> 
> Admin issue, same thing can happen with constant shuttle early launch noises but that's a bwoinkable and bannable issue.

Or we just give it a cooldown..?

**Pull request closed without merging**
