### PR TITLE
Botany now gets four random chem seeds up from 2 per vendor

### PR DESCRIPTION
**Pull request by alexkar598**
Some guy told me on discord to do this. Idfc if this gets merged or not. 
:cl:  alexkar598 
tweak: Botany now gets 4 exotic seeds per vendor up from two. 
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
THANKS FRIEND

**Comment by HomocidlePancakes** [comment]
Too bad botany gets only one box of disks so they won't be able to store all their chem traits.

**Comment by ThatLing** [comment]
Why?

**Comment by alexkar598** [comment]
Ask what's his name @boodaliboo

**Review by Altoids1 — CHANGES_REQUESTED** [review]
I ain't merging until I actually hear a reason to do this.

**Review by Altoids1 — APPROVED** [review]
After talking with fellow staff about it, and hearing @boodaliboo's explanation, I'm making this just be an increase from
# 2 to 3
and leaving it at that for now.

**Pull request merged**
