### PR TITLE
syndie minibombs now cost 4tc

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Requested by @Moja10, so take your qualms up with him

#### Changelog

:cl:  
tweak: minibombs have been taken from 7 to 4TC
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Just how it was pre-rebase :sunglasses:

**Comment by Amelia0010** [comment]
prebase*

**Comment by ShadowDeath6** [comment]
Do these still gib if you’re unarmored because I’m pretty sure that was nerfed as well

**Comment by Amelia0010** [comment]
[it wasn't](https://github.com/FluffySurvivor/-tg-station-yog-rebase/pull/1)

**Pull request merged**
