### PR TITLE
Adds a beaker holder to mediborgs.

### PR DESCRIPTION
**Pull request by ghost**
# Github documenting your Pull Request
**This has been tested.**  This is **also a port** of [this PR.](https://github.com/tgstation/tgstation/pull/45494)

The cyborg beaker holder will let you pick up any beaker and insert them into machines. This will let them do Virology and Chemistry without any help needed. This may result in a few bombings. But the capabilities are fairly limited, you only get one hand. It starts with a large beaker.

This will let mediborgs put beakers into cryogenics, aswell as letting you make your own ~~bombs~~ healing chemicals. More activities for medical cyborgs to do rather than standing around waiting for corpses to come in would be nice.

It can't hold your hand yet, I'll add that in the future as a donator feature.

# Wiki Documentation
Nothing I really need to repeat, everything this PR does is above.

# Changelog

:cl: Zxaber
rscadd: Replaced the beaker module with a beaker storage apparatus to mediborgs, that can carry beakers and place them into machines. Starts with a Large Beaker by default.
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
i feel this is too strong of a buff for borgs and will lead to things such as borgs suiciding while holding 300u beakers of black powder

**Comment by Moja10** [comment]
Borgs have a variety of built in chems and can get more from robotics upgrades, that's how they do their chemistry, if this happened they would be totally superior to the entirety of medbay staff. They would be able to do virology, genetics, all of chemistry, all of paramedical, anything a medical doctor can do and more (besides wrench the o2 canisters and suicide with medical wrench), all while being able to generate infinite chems on top of their beaker chemistry. Their weakness of having weak poisons and limited ways to stop people will go away when they will be able to flash, remove gas mask, and feed you the worst shit imaginable as well. Just fire the lizard CMO and replace it with a fucking borg at this point

**Comment by maxion12345** [comment]
> Borgs have a variety of built in chems and can get more from robotics upgrades, that's how they do their chemistry, if this happened they would be totally superior to the entirety of medbay staff. They would be able to do virology, genetics, all of chemistry, all of paramedical, anything a medical doctor can do and more (besides wrench the o2 canisters and suicide with medical wrench), all while being able to generate infinite chems on top of their beaker chemistry. Their weakness of having weak poisons and limited ways to stop people will go away when they will be able to flash, remove gas mask, and feed you the worst shit imaginable as well. Just fire the lizard CMO and replace it with a fucking borg at this point

Borgs can already do genetics. They just can't do injections.
Virology is something of an issue, but I've always hated it when I go to make a vaccine as a cyborg only to find I cannot put beakers into the machine. Or having to slowly transfer chemicals to my internal beaker with a syringe to carry them.

I think this is a good change, as it'll enable medborgs to be more then a mobile surgery area. However, it wouldn't work with the other bits of equipment. We could ditch the cyborg hypospray and replace it with a chemical storage so borgs would need to mix and store their own chemicals

**Comment by adamsong** [comment]
> Just fire the lizard CMO and replace it with a fucking borg at this point
I see no problem with this

**Pull request closed without merging**
