### PR TITLE
[admin] Silicon Law Manager, Antag AI Buff, and other related fixes/tweaks

### LINKED ISSUE #18952: Cyborg Laws Not Updated On Manual Sync
## Test Merges: 
Not Supplied / None
## Reproduction:
Cyborgs laws do not get updated when they're initially manually synced which can cause a cyborg to keep their old laws while having a master AI who has different/new laws.

 Submitted by: Rune Knight (257721577028714496)

### LINKED ISSUE #19567: You can purge an AI by adding too many laws.
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: By applying a law board to the AI that, combined with the old one, results in more than 10 laws, the AI will be purged with no feedback in admin logs that this has occurred. The only warning is '[USERNAME] tried to upload laws to [AI] that would exceed the law cap.'

 Submitted by: genericdm (205840324407459840)

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
This ports the Law Manager from Baystation12/Baystation12/pull/8486 and ParadiseSS13/Paradise/pull/14636.
This is considered [admin] since it replaces "Change Silicon Laws" (old) with "Manage Silicon Laws" (new).

Major changes:
- Law Manager for Silicons and Admins. They can use it to see their laws, set if they want to state it or not, what channel to announce to, notify themselves/AI or their cyborgs of their laws, and more.
- "State Laws" button is rename to "Law Manager". It re-directs to Law Manager instead of the old state law menu.
- Admins can modify the laws of any silicon of their choice. This includes laws given by antag status.
- Antag AIs can modify their own laws except for their zeroth law.
- An admin log/message everytime a law is added, removed, or modified (from the Law Manager).

Minor changes:
- AI/Cyborgs can auto announce into Hologram and Binary.
- You can no longer view a law module's laws by using it in hand.
- The description of the law module now include it's laws if you are standing next to it or are an observer. Now with fonting!
- All supplied law boards now respect the law capacity and thus will overflow properly.
- RoboTact's laws section now longer has things like `<font>` due to certain laws using fonting.
- A bug was fixed that prevented MMIs with modified laws (via usage of law boards on the MMI) from transferring said modified laws when they became an unconnected Cyborg.
- Changing a pAI's laws with their pAI card is now logged in their law history.
- The unused and unobtainable "malfunction" lawset was removed.

Closes #18952 since non-bug: it is one thing to be connected to a master AI and another to have law sync on. No law sync = no copying laws from the AI.
Closes #19567 since can't recreate. I messed around too much with AI laws so I might of made it impossible for this to happen again.

Here is a bunch of images of the Law Manager from different perspectives:
[Admin View for non-antag AI after adding a Zeroth law (Law Management)](https://github.com/yogstation13/Yogstation/assets/30399783/ebbd0990-ec12-4f1e-8b0a-ab6775ba5103)
[Admin View for non-antag AI (Lawsets)](https://github.com/yogstation13/Yogstation/assets/30399783/6e8a127a-9cba-459c-af2c-e4c818bf5841)
[Antag AI View (Law Management)](https://github.com/yogstation13/Yogstation/assets/30399783/bb65d0f2-8da7-48a1-a353-e861b74cef26)
[Antag AI View (Lawsets)](https://github.com/yogstation13/Yogstation/assets/30399783/6f874b22-9649-4a41-a77e-768a25453d58)
[Connected Cyborg w/ Lawsync](https://github.com/yogstation13/Yogstation/assets/30399783/cbe44a9e-559b-40fc-9cdc-ec811e8a2b6d)
[Connected Cyborg w/o Lawsync](https://github.com/yogstation13/Yogstation/assets/30399783/0585badd-6115-43c6-9ef0-d7db19ae3085)
[Unconnected Cyborg](https://github.com/yogstation13/Yogstation/assets/30399783/f86fd801-fc5c-429d-bc8d-ed42a82c124a)
[pAI](https://github.com/yogstation13/Yogstation/assets/30399783/fd76c163-f94d-4f1e-aac5-91f8e685dfa4)
[Admin View for pAI](https://github.com/yogstation13/Yogstation/assets/30399783/e94495fb-fad7-4291-95b8-40176bff7689)
[Non-antag AI with one law of every category (Admin View)](https://github.com/yogstation13/Yogstation/assets/30399783/8c3f77fc-b98e-4558-b952-a38593422466)

# Wiki Documentation
Briefly mention that an [antag AI](https://wiki.yogstation.net/wiki/AI#I'm_sorry,_Dave._I'm_afraid_I_can't_do_that.) can modify their laws with exceptions. They cannot modify their zeroth law (and devil laws).

# Changelog
:cl:  
rscadd: Silicon Law Manager has been added.
rscadd: Admins now have an easier time modifying the law set of any silicon.
rscadd: Antag AIs can modify their laws with exceptions. They cannot remove their zeroth law (or their devil laws).
rscdel: "State Laws" has been replaced/moved to the Law Manager.
rscdel: "Set Auto Announce Mode" has been replaced/moved to Law Manager.
rscdel: You can no longer view a law module's laws by using it in hand.
rscdel: The unused and unobtainable "malfunction" lawset was removed.
tweak: Examining a law module has been improved and reveals the laws on it if you are near it or are an observer. Now with formatting!
tweak: AI and Cyborgs can auto announce to Holopad and Binary.
tweak: Uploading supplied laws via law module now respects the law capacity.
tweak: Changing a pAI's laws is now logged in their history.
bugfix: MMIs with modified laws now properly transfer said laws if they become an unconnected Cyborg.
bugfix: RoboTact's law section displays laws without any formatting that comes from things like ion/hacked laws.
experimental: The social experiment of allowing an antag AI modify their own laws.
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
So if an admin wanted to change the 0th law for whatever reason, how would we go about doing it?

**Comment by Marmio64** [comment]
> So if an admin wanted to change the 0th law for whatever reason, how would we go about doing it?

why would you really need to change it? It just tells you to accomplish your objectives, so wouldn't you just edit their objectives instead?

**Comment by Xoxeyos** [comment]
> > So if an admin wanted to change the 0th law for whatever reason, how would we go about doing it?
> 
> why would you really need to change it? It just tells you to accomplish your objectives, so wouldn't you just edit their objectives instead?

Who knows, my question is more of a "what if?". Something on the panel could break, we might need another way to edit their objectives.

**Comment by Runian** [comment]
> So if an admin wanted to change the 0th law for whatever reason, how would we go about doing it?

Remove antag status and then edit/remove the zeroth law. I can remove the check so that they can edit/remove the zeroth law despite the AI being antag if desired.

**Comment by Runian** [comment]
> > > So if an admin wanted to change the 0th law for whatever reason, how would we go about doing it?
> > 
> > 
> > why would you really need to change it? It just tells you to accomplish your objectives, so wouldn't you just edit their objectives instead?
> 
> Who knows, my question is more of a "what if?". Something on the panel could break, we might need another way to edit their objectives.

Changed it so this is possible now w/o having to remove antag status.

**Comment by MajManatee** [comment]
Yeah I really don't like "You can no longer view a law module's laws by using it in hand."
So when I'm printing a law board I have to... alt tab and look it up on the wiki, or code dive?

**Comment by Runian** [comment]
> Yeah I really don't like "You can no longer view a law module's laws by using it in hand." So when I'm printing a law board I have to... alt tab and look it up on the wiki, or code dive?

Changed to examine only:
"tweak: Examining a law module has been improved and reveals the laws on it if you are near it or are an observer. Now with formatting!"

**Pull request closed without merging**
