### PR TITLE
ports agave fruit from bad deathclaw

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
adds agave fruit which has kelotane and lipolicide in it
im going to make a few prs porting some of the real plants from bad deathclaw
### Changelog

:cl:  
rscadd: Added agave from fruit as i like fallout like the person i am
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
the cheese touch

**Comment by Moja10** [comment]
#7252

**Comment by ynot01** [comment]
does the erp come with it

**Comment by alexkar598** [comment]
Not needed, lavaland plants are unused for the most part and as far as I can see, this is admin only content

**Pull request closed without merging**
