### PR TITLE
GAHHHH GIVE ME 40 CABLE COIL MAXSTACKS BACKK!!!

### LINKED ISSUE #21443: Cable coils only come in stacks of 30 instead of 40 due to an undocumented change
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Caused by #21221

 Submitted by: masterdrake (598557108551811073)

### PR DESCRIPTION
**Pull request by warface1234455**
undocumented change by #21221
resolve #21443

# Document the changes in your pull request
cable coil maxstacks is now 40

# Changelog

:cl:  
 
bugfix: cable coil maxstacks is now 40
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
buff it to 60 because cable cuffs take 15 coils and i like 30 because its easier to divide n shit

**Comment by ShoziOffical** [comment]
> buff it to 60 because cable cuffs take 15 coils and i like 30 because its easier to divide n shit

how about change cable cuff to take 10 intead

**Comment by Yarinoi** [comment]
> > buff it to 60 because cable cuffs take 15 coils and i like 30 because its easier to divide n shit
> 
> how about change cable cuff to take 10 intead

the cable cuff economy will be in ruins, do it

edit: or nerf it to take 20...

**Comment by MajManatee** [comment]
what if it was 50...

**Review by SapphicOverload — APPROVED** [review]

**Pull request merged**
