### PR TITLE
My brain hurts - Dynamic fixes, small additions to station traits to make dynamic not cry.

### PR DESCRIPTION
**Pull request by Xoxeyos**
# Document the changes in your pull request

Ports [Station trait command report is now generated independly](https://github.com/BeeStation/BeeStation-Hornet/pull/5477)
Another dynamic fix as well to try and ensure Command Staff don't roll antag. My fingers are crossed.
Addition 1.31.22: Darkspawn shouldn't roll below 35 players now; 15 are needed for ascension.

# Changelog
Heads should no longer roll antag during dynamic, and station trait command reports are now generated separately from the command reports.

:cl: Archanial, Xoxeyos
rscadd: Station traits are now generated separately from the command reports.
bugfix: Heads should no longer roll antagonist.
:tweak: Darkspawn shouldn't roll below 35 players.
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
|= will merge two lists without duplicates, don’t have the restricted roles be added with +=, also does this include the code in trim_candidates for roundstart rulesets from the bug we found yesterday?

**Comment by Xoxeyos** [comment]
> |= will merge two lists without duplicates, don’t have the restricted roles be added with +=, also does this include the code in trim_candidates for roundstart rulesets from the bug we found yesterday?

image

Yes, I've fixed the trim_candidates for roundstart rulesets, it matches latejoin, or whatever it was.

**Comment by ToasterBiome** [comment]
> > |= will merge two lists without duplicates, don’t have the restricted roles be added with +=, also does this include the code in trim_candidates for roundstart rulesets from the bug we found yesterday?
> 
> image
> 
> Yes, I've fixed the trim_candidates for roundstart rulesets, it matches latejoin, or whatever it was.

This was me being confused on which side was yogs and which side was bee’s tg and bee both have |=, i even said that it wasn’t the bug!

**Review by ToasterBiome — APPROVED** [review]
Will still need a HC to review as you're changing config stuff, the |= and the restircted roles are okay though.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
