### PR TITLE
Chem heaters now heat up linerarly

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Chem heaters now heat up linearly instead of as a logarithmic curve, makes actual precision heating viable

Base Tier: 10K per cycle
Max Tier: 40K per cycle

#### Changelog

:cl:  
tweak: Chem heaters heat up linearly now
/:cl:

### CODE REVIEW

**Review by jcatjmeow — APPROVED** [review]

**Comment by Moja10** [comment]
Actual precision heating is viable if you know what you are doing, for example, optimal meth heating is 1000K for one tick, then 420K for one tick. Bam, perfect meth temperature. This is unneeded for anyone who knows chemistry and easy to learn for those who don't.

**Comment by redmoogle** [comment]
> 
> 
> Actual precision heating is viable if you know what you are doing, for example, optimal meth heating is 1000K for one tick, then 420K for one tick. Bam, perfect meth temperature. This is unneeded for anyone who knows chemistry and easy to learn for those who don't.

yet we still see the chem lab blow up *alot*

**Comment by MegaEmpirical** [comment]
Get used to logs babies.

**Comment by redmoogle** [comment]
Dont see any point in keeping this open. Was fun to learn how chem heaters work

**Pull request closed without merging**
