### PR TITLE
Removes DNA & ID locking mechs

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Removes the ability for players to change DNA/ID lock. It still exists for purposes of syndie mechs and other special mechs, but players cannot set them.

## Rationale

Mechs are strong, there is no denying that

In the right hands, a mech can be devestating to an entire unprepared station, especially if security's EMP tooling is targeted early

With the DNA/ID lock currently, a player can create a mech and simply forget about it until they need to use it, indefinitely declaring it their own, and have absolutely no risks to creating this weapon of mass destruction

This creates the risk of players having to watch over their weaponry, lest it be used against them, in a similar fashion to any other weapon in the game

Leaving your mech will leave you even more vulnerable than before, forcing you to either deal with the consequences of living inside a mech permanently (move slow as hell, not be able to interact with any items directly, not being able to repair it with a welding tool) or risk it being hijacked and turned against you

I believe this creates an interesting risk dynamic and opens up great opportunities to turn the tide of battle for both antagonists and security

It also encourages roboticists to hand over their weapons to those who are more able to protect it, like **security**

##

**Protect the weapon you have created, or face the consequences**

# Changelog

:cl:  
rscdel: Removed DNA/ID locking mechs
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
We should remove mindshield firing pins because when you print sec weapons you should be worried someone is going to use them against you

**Comment by ynot01** [comment]
> We should remove mindshield firing pins because when you print sec weapons you should be worried someone is going to use them against you

true actually

**Comment by KillerOrcaCora** [comment]
I like this approach honestly

**Comment by ynot01** [comment]
gonna test this locally in a bit cause hrefs are wacky

**Comment by adamsong** [comment]
I would support removal of dna locking, because while it can be spoofed its hard, but I think id locking is fine

**Comment by ynot01** [comment]
> I would support removal of dna locking, because while it can be spoofed its hard, but I think id locking is fine

ID locking is just DNA locking but slightly less secure (your only threat is the captain, the other roboticist, and the RD)

a robo main made sure to point this out to me when i proposed the idea

**Comment by adamsong** [comment]
Or a traitor who stole AA

Time for medbay to not get to use their mech because some greyshit walked off with it

**Comment by ynot01** [comment]
> Time for medbay to not get to use their mech because some greyshit walked off with it

In my experiences as a medical and roboticist player odysseuses very rarely get DNA locked and are never ID locked and theft has never been an issue. Medical usually doesn't actually care about odysseuses and just lets them sit there or lets whoever DOES care take it away, because at least someone is using it and hopefully healing.

Anyways, on the smaller, civilian scale like this, it actually bears great consequence. Stealing a mech (something usually fucking impossible due to DNA locking) is directly cited under space law as being grand theft. Some shithead steals the odysseus (which has shit armor) and their round is now over.

**Comment by Marmio64** [comment]
Sounds really annoying that you can't lock it when you just want to quick get out for something. You're not paying attention for a second and now someone takes your mech and now you can't get it back without destroying the mech or convincing them to get out. For this to not be a problem sec needs a way to capture and force out Mecha inhabitants without breaking their very expensive machine. Or maybe at the least allow temporary ID locking that lasts like 60 seconds?

**Comment by ynot01** [comment]
> Sounds really annoying that you can't lock it when you just want to quick get out for something. You're not paying attention for a second and now someone takes your mech and now you can't get it back without destroying the mech or convincing them to get out. For this to not be a problem sec needs a way to capture and force out Mecha inhabitants without breaking their very expensive machine. Or maybe at the least allow temporary ID locking that lasts like 60 seconds?

This is exactly the kind of situation I am aiming to create with this PR. Leaving your mech is leaving it vulnerable. Pay attention, be careful, or face the consequence. If you are so careless with your big expensive WMD that a greytider would take it, what do you think will happen if an actual threat shows up to steal it?

**Comment by Notamaniac** [comment]
Make DNA locking an upgrade that costs diamonds/research?

**Comment by adamsong** [comment]
I always make sure mechs I give out are department locked, because it's useful.

**Comment by ynot01** [comment]
> Make DNA locking an upgrade that costs diamonds/research?

locking the problem behind research and mining doesn't make it not a problem

**Comment by ynot01** [comment]
> I always make sure mechs I give out are department locked, because it's useful.

then you are wiser than most

**Comment by RG4ORDR** [comment]
Why not make mech ignition keys?

**Comment by ynot01** [comment]
> Why not make mech ignition keys?

I am removing the security altogether, not softening it. You, the player, are the sole defender of your mech. Not DNA locking. Not "car keys". You must protect your mech or risk losing it. Adding workarounds like this defeats what I am trying to implement.

**Comment by Cartlord** [comment]
Not a fan of this one, I don't think grand theft should be easy and I agree with Marmio.
I would suggest either a way to force people OUT of mechs (I don't think the exosuit tracking beacon counts since it just E.M.P.s the shit out of the mech), or keeping a lock mechanism but adding a way to bypass it.

**Comment by VaelophisNyx** [comment]
> > Why not make mech ignition keys?
> 
> I am removing the security altogether, not softening it. You, the player, are the sole defender of your mech. Not DNA locking. Not "car keys". You must protect your mech or risk losing it. Adding workarounds like this defeats what I am trying to implement.


ok but consider: this is a fucking terrible idea

**Comment by RG4ORDR** [comment]
> > Why not make mech ignition keys?
> 
> I am removing the security altogether, not softening it. You, the player, are the sole defender of your mech. Not DNA locking. Not "car keys". You must protect your mech or risk losing it. Adding workarounds like this defeats what I am trying to implement.

Great idea, Einstein. 

I now have full reign to create mechs and if anyone tries to force me out, or steal it I can robust them. I forsee zero issues,tickets, or complaints about tiders stealing Durands,Gygaxes, or other exosuits to fuck around. Exosuits are strong, and you literally buffed them by removing the ability to place exosuit beacons on them while they weren't in maintenance mode. So now the bigger idea is unironically allow someone to go on a powertrip because they need to defend their exosuit.

**Comment by GraveHat** [comment]
Look, I understand removing the DNA lock because it's just a way to completely cockblock everyone out except the ai if the mech has an ai control beacon. But removing the security altogether would just incentives bad gameplay and encourage greytiding.

I understand you want every roboticist with an exosuit extremely paranoid of attempted break-ins into the mech bay, theft, whatever, but pushing this would force the already powergaming player base of roboticists to bunker down even harder, literally walling off the entrance to mech bay and the side entrance to robotics on box to buy more time to stop the shitters from getting in for example. Now ask yourself, is that really the kind of gameplay you want to see coming from robotics, just because they dared make the WMD that they have to go through extreme lengths to protect?

Hell, if we go by my previous example, then even antagonists who would be the only people who would legally be allowed; to even hijack a mech would get cucked. At least if it were ID locked, then they would be incentivized to get the access either from stealing the id, which may or may not involve killing them, or through some other means than, I must emag my way to the combat mechs get in before the roboticist notices and go on a killing spree before getting executed because I didn't eject out of the mech as it gets destroyed.

The complete removal of any form of security would, 1, Incentivise shitters to continue being shitters because of the haha funny, 2, Incentivise the roboticist to be paranoid power gaming crackheads that would now have a reason to execute you for breaking into robotics in the first place just because they have a combat mech, and 3, Incentivise antagonists to bypass the roboticist and the crew entirely before they go on a rampage.

Overall, you really overshot with your objectives here and ended up just making the players play worse to even be optimal in the first place. Although, I do agree that DNA locking is blatantly overpowered and is better off just removed as it is too easy to do but prevents so much.

**Comment by ynot01** [comment]
> GraveHat

this is not something i had considered, and yet the argument of "roboticists will be shittier players because we nerfed them" does not appeal to me

**Comment by GraveHat** [comment]
> > GraveHat
> 
> this is not something i had considered, and yet the argument of "roboticists will be shittier players because we nerfed them" does not appeal to me

Powergamers be powergaming unfortunately and I can see this from a mile away. Also, this would increase the workload for the staff because of shitters being shitters, and also power gamers will always find a way to break into any fortification to go fucking grief now that they know that all they need to do is get to the mech to get in the mech. Don't expect roboticists to babysit it 24/7 and don't expect security to do it either. Security is just hard to get into, the roboticist would just make robotics equally as hard to get into.

**Comment by Sniblet** [comment]
I'm not following how this makes the game better instead of worse

Haha I love getting out of my Odysseus to fix it in the middle of a blob fight and having some literal clown walk over and run it in to try to fight the blob with no warning because I couldn't lock clowns out of it for reasons of uhhh
Ummm
Lol, it's funnier when the greytide can steal a griefing roboticist's Gygax?? (and subsequently get bwoinked for committing grand theft?)
So anyway how is this my problem as a doctor or an innocent roboticist or a sec officer who doesn't have a warden on the team

If you wish a locked and unoccupied mech didn't exist, the solution is to **destroy it.** You know, click it a few times. You know how to do that, right?
This is much faster, much easier, much more effective, makes much more sense, and causes much less collateral damage than coding out both the DNA lock and the ID lock so literally anyone can steal any mech and be a huge ass with it at any time
https://github.com/yogstation13/Yogstation/pull/15114

**Comment by JamieD1** [comment]
No, im not having shitters jumping in mechs that are being left to charge for example.

**Pull request closed without merging**
