### PR TITLE
Revives my mood event PR

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

A revival of my https://github.com/yogstation13/Yogstation/pull/14469 mood related PR, that i closed because i was... in bad mood(ironic). 

I was asked to revive it in discord, so... yeah...

https://github.com/tgstation/tgstation/pull/47254
https://github.com/tgstation/tgstation/pull/46296
https://github.com/tgstation/tgstation/pull/49553
https://github.com/tgstation/tgstation/pull/50192
https://github.com/tgstation/tgstation/pull/49918

# Spriting

image
image

# Changelog

:cl: RaveRadbury, ghost, wesoda25, tralezab, nemvar. Ported to YogStation by SuperSlayer
rscadd: The science department now gets a mood bonus for petting borgs.
rscadd: Mutually exclusive Clown and Mime Fan perks
rscadd: Clown and Mime pins
imageadd: Clown pin and Mime pin
rscadd: Adds a couple new mood events for being held up and put in an electric chair/guillotine.
rscadd: The Psychology Office now has a small positive moodlet, and some ambience
spellcheck: Renamed "My mental status" to "My current sanity" in the mood printout.
/:cl:

### CODE REVIEW

**Review by KillerOrcaCora — APPROVED** [review]
Approved last time approved again

**Comment by KillerOrcaCora** [comment]
@JamieD1

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
cornflakes

**Comment by JamieD1** [comment]
Dm me when you fix the conflicts.

**Comment by ghost** [comment]
AAAAAAAAAAAAA

**Pull request closed without merging**
