### PR TITLE
Added new clothe to the clothemate vendor

### PR DESCRIPTION
**Pull request by enkidienne**
**General Documentation.**
list of added clothes: 

regular (50$):

cowboy boots: lizard
cowboy boots: lizard masterwork
cyborg mask
trainers
trainers: red
trainers: white
trainers: zebra
trainers: dark brown
trainers: black
winter coat: captain
winter coat: medical
winter coat: science
winter coat: atmos
winter coat: telecommunication
winter coat: engineering 
winter coat: botanist
winter coat: cargo
winter coat: mining
black suit
black suit jacket
gothic coat
gothic suit 
White and black sweatshirt
white suit

premium (75$): 
dr. freeze coat
Pharoah tunic
Dracula coat
Russian gangster suit
messiah robes

**Why is this change good for the game?**
moar options = good. 
.
.
.

no?

**Wiki Documentation**
none?

**Changelog**
🆑
adds more clothes to clothemate vendor's list
/🆑

### CODE REVIEW

**Comment by Tipy1802** [comment]
Why are you putting departmental winter coats in the public clothes vendor?

**Comment by enkidienne** [comment]
Because it's pure vanity, most departments already don't use it and some of those are just not available in-game. So why not giving everyone the chance to grab one, seeing as it changes nothing for the department in question.

**Comment by UselessTheremin** [comment]
Sec and captain coats are literally armor

**Comment by athena413** [comment]
image

**Comment by ToGWtF** [comment]
Have to agree

No department clothes
No masterwork lizard boots because they literally sell for $1,000 at cargo.
Some things should be put in clown costume machine instead
You completely invalidated the cargo sneakers crate by making the shoes cost not only 1/2 as much but also made them available.

**Comment by enkidienne** [comment]
I don't think invalidating a single crate in cargo is that bad, seeing as it never actually ordered... as in I've never seen it in-game in my 2 years of playing here.

**Comment by athena413** [comment]
> 
> 
> I don't think invalidating a single crate in cargo is that bad, seeing as it never actually ordered... as in I've never seen it in-game in my 2 years of playing here.

youre still invalidating crates in cargo

**Comment by Marmio64** [comment]
invalidating crates is bad, even if it doesn't matter too much. The real bad things though is the departmental coats and the fact you are putting well armored coats (cap and sec) in there. Pretty sure you removed the cap and sec ones now but there is still no possible way to excuse the fact that you're putting departmental clothes into vendors. It's like putting a public sec drobe in the hallways, so that people can dress themselves up as security and confuse everyone.

**Comment by enkidienne** [comment]
see last commit

**Comment by alexkar598** [comment]
Hippiy hoppity FEATURE FREEZE

**Pull request closed without merging**
