### PR TITLE
Adds snails

### PR DESCRIPTION
**Pull request by Szyszkrzyneczka**
This PR is going to add snails, they are cute and can be acquired with gold slime cores.

Why is this good for the game? : The bot told me to code it, also they are cute.
#### Changelog

:cl:  
rscadd: Added Snails  
imageadd: Added my shitty sprites for snails
/:cl:

### CODE REVIEW

**Comment by Szyszkrzyneczka** [comment]
Ignore the first four things, they are from my mosin pr thing

**Comment by AsV9** [comment]
Stop using the master branch I swear to god.

**Review by nesisknesis — CHANGES_REQUESTED** [review]
sprite bad, ill ping you in spriter

**Comment by Bibby0110** [comment]
maybe just port the TG snail person PR :))))))))) (wink wink $$$ wink wink))

**Comment by Szyszkrzyneczka** [comment]
Time to see the icon bot get stroke and die

**Comment by Szyszkrzyneczka** [comment]
Travis says pr good, that means its good right guys

**Comment by Bibby0110** [comment]
sure is baybe

**Comment by neeshacark** [comment]
the snail reign on yogstation is growing near. now we just need to get the snailpeople added and make them the only race allowed to be a head of staff.

**Review by fluffe9911 — CHANGES_REQUESTED** [review]
Give it directionals you silly, dont have to make front and back sprites just do what goats do.

**Review by nesisknesis — APPROVED** [review]
yeah

**Review by fluffe9911 — APPROVED** [review]
ye

**Pull request merged**
