### PR TITLE
Blobs no longer get a free win on icemeta.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
nice one, blob_allowed = false on icemoon/surface

# Changelog
:cl:  
bugfix: blob no longer gets a free win on icemeta
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
thx bro

**Comment by ShoziOffical** [comment]
conflict bro

**Comment by neeshacark** [comment]
this is so sad

could we make it so it just cant place on surface but can grow there? : (

**Comment by N3D6** [comment]
> this is so sad
> 
> could we make it so it just cant place on surface but can grow there? : (

that would be ridiculously OP. blob drops in a secluded place and wins because it expanded throughout the snow and got a free win

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
