### PR TITLE
Lets flying vehicles (and mobs) convey their flight to the rider

### PR DESCRIPTION
**Pull request by Moltijoe**
Flight potion lets you carry people over lava and chasms now

:cl:  
tweak: Flying people can carry others over chasms or lava without killing them
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
are these the correct ways to add/remove flags?

**Comment by Moltijoe** [comment]
> are these the correct ways to add/remove flags?

You tell me, because im pretty sure it is, at the very least, it worked when i tested it

**Review by MajManatee — APPROVED** [review]
boy I sure hope this doesn't backfire and have unintended consequences. :)

**Review by SapphicOverload — CHANGES_REQUESTED** [review]
I recommend you use ```&= ~FLYING``` instead of ```-= FLYING``` or it'll break things

**Review by SapphicOverload — APPROVED** [review]
Looks good

**Comment by Moltijoe** [comment]
merge it then bruh

**Pull request merged**
