### PR TITLE
Makes floor cluwne slippery floor last longer

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request
It lasts way too short
#### Changelog

:cl:  
tweak: Made floor cluwne slippery floor last longer
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
No it doesn't lol

**Comment by JamieD1** [comment]
> No it doesn't lol

Care to explain?

**Review by DoubleTapper — CHANGES_REQUESTED** [review]
way too fuckin long jesus make it 60 seconds max

**Comment by JamieD1** [comment]
> way too fuckin long jesus make it 60 seconds max

Deciseconds

**Comment by PettyOfficer** [comment]
Nice clowning around.

**Comment by alexkar598** [comment]
Floor cluwnes are challenging enough and requires several people to kill. Its not like hes going to be salty...

**Pull request closed without merging**
