### PR TITLE
Short and Long Telomeres Quirks

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Two new quirks:

**Short Telomeres**: Due to hundreds of cloning cycles, your DNA's telomeres are dangerously shortened. Your DNA can't support cloning without expensive DNA restructuring, and what's worse- you work for Nanotrasen.
**Value**: -2

You cannot be scanned the cloner no matter what upgrades it has, and consequently - you cannot be cloned through the cloner.

**Long Telomeres**: You haven't been cloned much, if at all. Your DNA's telomeres are still largely unaffected by repeated cloning, enabling cloners to work faster.
**Value**: 2

Makes you clone 20% faster.

Cannot take either if you have no DNA (IPC)

# Wiki Documentation

https://wiki.yogstation.net/wiki/Quirks

Need to be added to this page.

# Changelog

:cl:  
rscadd: Adds two new quirks - Short and Long Telomeres, either making you unable to be cloned or boosting your clone speed.
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
there may be a case to making short telomeres be the full -2 points, since smoker is also -2 points but also wont perma kill you if medbay happens to be bad the same round you die. (or if medbay is super busy)

**Review by Moltijoe — CHANGES_REQUESTED** [review]
species that can't be cloned shouldn't be able to take them

**Comment by Hopekz** [comment]
I think no cloner is more than a -1 imo

**Comment by neeshacark** [comment]
baiomu what, no more cloner should probably be more than a single point, not a bunch because you can be fixed otherwise and generally wont ever get cloned but there are 100% times where medbay will just not be able to work out how to revive you.  two points atleast

**Comment by Moltijoe** [comment]
> baiomu what, no more cloner should probably be more than a single point, not a bunch because you can be fixed otherwise and generally wont ever get cloned but there are 100% times where medbay will just not be able to work out how to revive you. two points atleast

Taking no clone as either plasmeme or preternis is basically just round removal on death

**Comment by Moltijoe** [comment]
both being 2 (either + or -) seems to be better, 
no clone is really bad if you die and medbay is useless
fast clone is useless if you're not dying or medbay is allergic to cloning

**Comment by ReddicusDragon** [comment]
closed due to no activity in a week.

**Review by Moltijoe — APPROVED** [review]
good enough for me

**Comment by Hopekz** [comment]
> good enough for me

Did you forget to merge?

**Comment by ReddicusDragon** [comment]
Merging in 5 days

**Comment by Hopekz** [comment]
> Merging in 5 days

Why five days?
OP is a maintainer

**Comment by ReddicusDragon** [comment]
> > Merging in 5 days
> 
> Why five days?
> OP is a maintainer

Feature freeze, innit

**Comment by Hopekz** [comment]
> Feature freeze, innit 

It doesn't apply to maintainers last I've seen unless I'm wrong

**Comment by ReddicusDragon** [comment]
> > Feature freeze, innit 
> 
> It doesn't apply to maintainers last I've seen unless I'm wrong 

Jamie said the holobanana projector is the last feature getting merged til the 16th

**Comment by Hopekz** [comment]
> Jamie said the holobanana projector is the last feature getting merged til the 16th

Alright didn't realize the rules kept changing on the fly like that 🙂

**Comment by Moltijoe** [comment]
> Alright didn't realize the rules kept changing on the fly like that 🙂

yogdev

**Pull request merged**
