### PR TITLE
CLOCK CULT MAJOR BUFF

### PR DESCRIPTION
**Pull request by Readystorm546**
CLOCK CULT NEEDED A GOOD ASS BUFF

:cl:  
rscadd: Buffed Clockcult
experimental: This is experimental  
/:cl:

### CODE REVIEW

**Comment by Jumps0** [comment]
based

**Comment by yacabo** [comment]
image

**Comment by athena413** [comment]
this needs to get merged RIGHT NOW

**Comment by alexkar598** [comment]
[based on the hardware](https://cdn.discordapp.com/attachments/484188983061118977/725182287284797440/based_on.mp4)

**Pull request closed without merging**
