### PR TITLE
Mech Extinguisher Buff

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Mech extinguisher now uses the firefighting foam that the advanced fire extinguisher has instead of water. Also fixes some stuff and makes the code better.

# Why is this good for the game?

Maybe someone other than me will actually use it for once? Seriously, I've never seen anyone else use it, ever.

# Testing
image

# Changelog

:cl:  
tweak: mech extinguisher uses firefighting foam instead of water
bugfix: fixed extinguisher particles not disappearing when they stop moving
bugfix: fixed blocking your own extinguisher when moving forward
/:cl:

### CODE REVIEW

**Comment by LassiH** [comment]
dosent the extinquisher on the mech have a really fast firerate ?

**Comment by wonderinghost** [comment]
Not really. It's about standard

**Comment by wonderinghost** [comment]
Also fire fighting foam is a lot more useful than spritsing water everywhere

**Comment by wonderinghost** [comment]
Now we need a tile layer for a mech. Can probably take the cable coiler tool because that rips up floors

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
