### PR TITLE
Adds 8 new ethereal faces

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
Hi I made some new faces for our starry frens
image
In order: Druid - Full - Stars - Onion - Cheese - Nova - M.C. - Shard

# Why is this good for the game?
https://the-under-presents.fandom.com/wiki/Masks

# Testing
Ye see first section

# Spriting
I might give these some shading to look nicer in the future

image

# Changelog
:cl:  
rscadd: Added 8 new faces for ethereals to choose from
/:cl:

### CODE REVIEW

**Comment by Scrambledeggs00** [comment]
Bottom right corner ethereal is facing the wrong way ;]

**Comment by ynot01** [comment]
AmyCH3-ezgif com-webp-to-gif-converter

**Review by ynot01 — APPROVED** [review]
Code is good

**Comment by MommaDragon** [comment]
Novakids.

**Comment by AMyriad** [comment]
> Bottom right corner ethereal is facing the wrong way ;]

They know what happens to the ones who step outta line

image

**Comment by LassiH** [comment]
image
machine

**Review by ynot01 — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
