### PR TITLE
Revert "what idiot forgot to make shock touch have a fucking proximity check i swear to god " this readds ranged shock touch

### PR DESCRIPTION
**Pull request by boodaliboo**
Reverts yogstation13/Yogstation#9749
stupid pr mabd

### CODE REVIEW

**Comment by N3D6** [comment]
lol no

**Comment by TheLinuxOS** [comment]
Literally says TOUCH for a reason

**Comment by maxion12345** [comment]
ok, but
emperor palpatine

**Comment by SomeguyManperson** [comment]
no

**Pull request closed without merging**
