### PR TITLE
may fix the storm trooper armor not showing

### PR DESCRIPTION
**Pull request by boodaliboo**
awlays fucking something doesnt work fuck me
#### Changelog

:cl:  
bugfix: fixed a few things  
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Test this first SCREEEEEEEEEE

**Comment by boodaliboo** [comment]
> Test this first SCREEEEEEEEEE

i did for once

**Comment by Hopekz** [comment]
> > Test this first SCREEEEEEEEEE
> 
> i did for once

I mean before you create 2-3 followup PR's because your original PR wasn't working

**Comment by boodaliboo** [comment]
helmets invisable on ground and armors bugged but they now appear properily on the character

**Comment by boodaliboo** [comment]
> helmets invisable on ground and armors bugged but they now appear properily on the character

i truthfully dont know what to do to fix it not appearing when held/onground 

please someone help

**Comment by boodaliboo** [comment]
spriter men please help

**Comment by boodaliboo** [comment]
missa said she would make one

**Pull request closed without merging**
