### PR TITLE
GaxStation fixes + more loot + REDOS BRIDGE

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

airlock by fitness room had a wall in it, sign was fucked, etc etc etc.

image

# Changelog

:cl:  
rscadd: adds more loot to gax
tweak: redoes the gax bridge
bugfix: actually adds antique laser
bugfix: remove wall from being in the fitness airlock on gax
bugfix: hopefully fixes gax disposals by science
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
Just an outsider comment about Gax station: The engineering setup for the SM engine diverges enough from the wiki guide that newer players are a bit lost trying to get it running.

**Comment by ToasterBiome** [comment]
> Just an outsider comment about Gax station: The engineering setup for the SM engine diverges enough from the wiki guide that newer players are a bit lost trying to get it running.

Can you explain further?

**Comment by JamieD1** [comment]
> > Just an outsider comment about Gax station: The engineering setup for the SM engine diverges enough from the wiki guide that newer players are a bit lost trying to get it running.
> 
> Can you explain further?

What happened to the stairs bridge

**Comment by ToasterBiome** [comment]
> > > Just an outsider comment about Gax station: The engineering setup for the SM engine diverges enough from the wiki guide that newer players are a bit lost trying to get it running.
> > 
> > 
> > Can you explain further?
> 
> What happened to the stairs bridge

Nothing, I just haven’t pushed it yet

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
