### PR TITLE
Fixes the creamator not creamating

### PR DESCRIPTION
**Pull request by Moltijoe**
# Testing
image
image

:cl:  
bugfix: Fixes the creamator not creamating
rscadd: creamator can sometimes replace the cremator at roundstart
/:cl:

### CODE REVIEW

**Review by SapphicOverload — APPROVED** [review]
cannibalism

**Comment by Moltijoe** [comment]
they still need a button bound to them to activate, but i guess it's fine?

**Comment by neeshacark** [comment]
can you make it a 1% chance to replace the normal cremator?

**Comment by Moltijoe** [comment]
> can you make it a 1% chance to replace the normal cremator?

uh, sure i guess

**Comment by neeshacark** [comment]
exceedingly based

**Pull request merged**
