### PR TITLE
Ballistics shield for nukies | NO RUDENESS EDITION

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

30 TC shield that blocks all incoming ballistic projectiles, but not energy. This is so they don't just spec into autorifles roundstart and make energy combat shields completely worthless.
# Spriting

# Wiki Documentation

30 tc ballistic shield, check files changed for desc
# Changelog

:cl:  
rscadd: Ballistics shield for nukies
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
last pr was closed for rudeness so there will be no rudeness in this one fellas

**Comment by Notamaniac** [comment]
This is a bad idea because someone can purchase a e shield and a ballistic shield for complete projectile immunity, then use a ranged holoparasite with zero range to shoot people with impunity without being hit themselves (58 TC total, doable on war ops). The only counterplay I can see are bombs, slips, or mechs the first being dangerous, the second not dealing with the holoparasite, the third requiring mining to rush minerals and R&D to completely ignore other tech nodes.

Not to mention the hideous price if you were to buy this standalone (why not just buy an elite hardsuit and stims/medkit instead for half the price, doesn't deal with lasers which at least some of the crew will have)

inb4 holoparasites don't do enough damage, it's just a meme loadout, there's counterplay so why complain, just melee them bro there's no holoparasite there.

**Comment by Simplehorror** [comment]
> This is a bad idea because someone can purchase a e shield and a ballistic shield for complete projectile immunity, then use a ranged holoparasite with zero range to shoot people with impunity without being hit themselves (58 TC total, doable on war ops). The only counterplay I can see are bombs, slips, or mechs the first being dangerous, the second not dealing with the holoparasite, the third requiring mining to rush minerals and R&D to completely ignore other tech nodes.
> 
> Not to mention the hideous price if you were to buy this standalone (why not just buy an elite hardsuit and stims/medkit instead for half the price, doesn't deal with lasers which at least some of the crew will have)
> 
> inb4 holoparasites don't do enough damage, it's just a meme loadout, there's counterplay so why complain, just melee them bro there's no holoparasite there.

To beat the holoparasite, shoot it until it dies.

**Comment by Marmio64** [comment]
This + extra arm + double esword + stimpack/adrenals does sound unreasonably powerful with little counterplay at all

**Comment by Simplehorror** [comment]
YOU CANNOT BUY EXTRA ARMS

**Comment by MajManatee** [comment]
blantantly too powerful, even for me

**Comment by Sniblet** [comment]
```
/datum/uplink_item/device_tools/arm
	name = "Additional Arm"
---
	exclude_modes = list(/datum/game_mode/nuclear)
```
Clown ops can't do the combo because they can't buy the ballistic shield.

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
A shield outright ignoring 100% damage of something makes no sense and is not how balancing works, please turn this into something more presentable before I ping balance council and they just vote this out

**Comment by Marmio64** [comment]
> YOU CANNOT BUY EXTRA ARMS

still would be able to do the immortal holoparasite strat as said above then

**Comment by JamieD1** [comment]
Half the TC and make it consumable, so after so many bullets it falls apart.

**Pull request closed without merging**
