### PR TITLE
adds venus human trap to hostile gold extract spawn

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
a unused mob with a unique feature of dragging things to it with vines and also rarily seen and i thought it would be cool to add it
#### Changelog

:cl:  
rscadd: Added venus human trap to gold extract 
/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
Pictures or it didn't happen

**Comment by boodaliboo** [comment]
Pcitue

**Comment by Jarod1200** [comment]
are these the things that come out when you get the flowering space vines?

**Comment by boodaliboo** [comment]
Yes

**Comment by overlord12345** [comment]
How is it unused if vines spawn it

**Comment by boodaliboo** [comment]
> How is it unused if vines spawn it

have you ever seen kudzu flower ever

**Comment by Hopekz** [comment]
**Bad PR. Untested.**
Fix them first.

**2 issues with them when player-controlled:**
1: They don't have a cooldown on their attack (spam attack)
2: They don't have a range on their melee attack (can attack as far as they can click)

This is an issue when someone gets control via someone putting a ghost inside of them (admin), sentience or mind transfer potion.

**Comment by boodaliboo** [comment]
ill reopen this when tg tg rework of venus is done

**Pull request closed without merging**
