### PR TITLE
Adds new captain and deathsquad armor sprites, slightly increases captain's SWAT suit armor

### PR DESCRIPTION
**Pull request by MrHorizons**
Captain:

 

Deathsquad:

Sprites made by Tex.

The original (SWAT suit) values: `("melee" = 40, "bullet" = 50, "laser" = 50, "energy" = 25, "bomb" = 50, "bio" = 100, "rad" = 50, "fire" = 100, "acid" = 100)`

The new captain's SWAT suit values: `("melee" = 60, "bullet" = 50, "laser" = 50, "energy" = 35, "bomb" = 75, "bio" = 100, "rad" = 75, "fire" = 100, "acid" = 100)`

Deathsquad suit values (unchanged): `armor = list("melee" = 80, "bullet" = 80, "laser" = 50, "energy" = 50, "bomb" = 100, "bio" = 100, "rad" = 100, "fire" = 100, "acid" = 100)`

I wanted to try giving the SWAT suit some kind of night vision as a more "tactical" alternative to a helmet light, but after much frustration, I decided to forgo it for now.

#### Changelog

:cl:  War-Tex, MrHorizons
rscadd: Added new sprites for the captain's SWAT suit and deathsquad armor.
tweak: The armor values of the captain's SWAT suit have been increased slightly.
/:cl:

### CODE REVIEW

**Review by Hopekz — CHANGES_REQUESTED** [review]
You didn't modify any armor values as of right now so either fix your title + changelog or commit them.

Also, you're adding an extra icon called "default state" that seems to be all the icons mashed into one according to the icon bot so fix that if it is actually an issue.

**Comment by Moja10** [comment]
Too much protection on the Captain's suit, it will become just straight more obnoxious to fight and deal with.

**Comment by ynot01** [comment]
atomize

**Comment by Marmio64** [comment]
i think everything looks good besides the 100 bomb protection, since it just straight up steps on the toes of the RDs unique space bomb suit. Sprites are amazing, tex is good, but please, nerf bomb protection to 75, 75 should be the very most it can have.

Still going to thumbs up for now though.

**Comment by MrHorizons** [comment]
I've decided to reduce the bullet armor to only 50, so that it, overall, is only slightly better than the captain's carapace armor-wise, save for the bomb resistance.

**Comment by JamieD1** [comment]
Atomize these please. @MrHorizons

**Pull request closed without merging**
