### PR TITLE
Revert "Revenant Balance Check"

### PR DESCRIPTION
**Pull request by Mqiib**
Reverts yogstation13/Yogstation#15874

What's the point of having a balance council if stuff gets merged anyways despite us agreeing that it's not a good change?

image

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
if you read jamie's comment, you'd know its because he wants to see it in action first

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> if you read jamie's comment, you'd know its because he wants to see it in action first

isnt this why we have testmerges

**Comment by VaelophisNyx** [comment]
tell that to the people who seem allergic to test merges

**Comment by Bibby0110** [comment]
> tell that to the people who seem allergic to test merges

This is a joke right?

**Comment by Maia-J** [comment]
> tell that to the people who seem allergic to test merges

Examples? Just state idk, 4 people who are actually active in doing dev stuff. The only thing we are getting allergic to is you nerfing/buffing in orders of magnitude higher than what is required.

**Comment by VaelophisNyx** [comment]
the people who can merge stuff, or set up a test merge, dont do it often. That is what I mean.

**Comment by Bibby0110** [comment]
> the people who can merge stuff, or set up a test merge, dont do it often. That is what I mean.

someone wasn't around a few months ago

**Comment by JamieD1** [comment]
Can we make it so the revenant can see dead chat and not talk on it instead?

**Comment by VaelophisNyx** [comment]
thing is they just talk normally; all they could do is hear dead chat
dead players can hear the entire round as a mechanic so...
removing it was the way to fix that.
Since the changes this PR wants to revert were added, I've seen revenants actually play the game more now, and even cause chaos in a round (instead of just getting ganked by the salt & scalpel brigade)

**Comment by Marmio64** [comment]
> thing is they just talk normally; all they could do is hear dead chat dead players can hear the entire round as a mechanic so... removing it was the way to fix that. Since the changes this PR wants to revert were added, I've seen revenants actually play the game more now, and even cause chaos in a round (instead of just getting ganked by the salt & scalpel brigade)

how would nerfs be making the antag better at causing chaos?
Also you could just remove a revenant's ability to speak period if you want them unable to talk to deadchat. As far as i know their speech serves zero purpose except for talking to other ghosts.

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
