### PR TITLE
[PORT] Ethereal crystalization upon death

### PR DESCRIPTION
**Pull request by Moltijoe**
no clue what PRs this is from, i just ripped it out of the tgcodebase
tartu found it for me
https://github.com/tgstation/tgstation/pull/57225

# Why is this good for the game?
Gives ethereals an interesting mechanic that realistically only helps in silly deaths rather than affecting antag balance

# Testing
image
image

# Spriting

colour changes to match the ethereal
anim
crystal

:cl:  Qustinnus, Kryson, uglykoala, Ghost, @Moltijoe 
rscadd: Ethereals now crystallize upon death, reviving after a delay
soundadd: Sounds for crystalization starting, finishing, and being interrupted
imageadd: Sprites for ethereal crystallization
/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
Wait this is actually badass??

**Comment by ManofSan** [comment]
ethereal mains will rise

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
make the BRUTE_DAMAGE_REQUIRED_TO_STOP_CRYSTALIZATION a way way way way lower amount if the user isn't a ethereal

**Comment by ShoziOffical** [comment]
how can you not find the pr https://github.com/tgstation/tgstation/pull/57225
credit them

**Comment by Moltijoe** [comment]
> how can you not find the pr [tgstation/tgstation#57225](https://github.com/tgstation/tgstation/pull/57225)

apparently searching "ethereal" and "crystallize" doesn't bring it up for some reason

**Comment by azzzertyy** [comment]
not sure how i feel about the brain trauma, punishes ethereal players for something they cant exactly control.
maybe if you could decide to not let yourself get crystallized on death and instead just turn into a normal corpse?

**Comment by Moltijoe** [comment]
> not sure how i feel about the brain trauma, punishes ethereal players for something they cant exactly control. maybe if you could decide to not let yourself get crystallized on death and instead just turn into a normal corpse?

it's a 5 minute delay to crystalization, at that point, who knows how long you're gonna stay dead

**Review by ToasterBiome — APPROVED** [review]

**Review by cuackles — APPROVED** [review]

**Pull request merged**
