### PR TITLE
[READY]Shadowling reworkish

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Lings are weak, they have many useless abilities and also always loose. This will make some changes to them.

Enthralling - now start of every enthralling stage will knockdown your target, so it cannot easily break handcuffs and run away(wtf). 

Null Charge - This ability is also fucking useless shit. it is removed.

Void Touch - New one! - It replaces null charge. It is a godhand spell. Hitting a borg, carbon or a mech with it will EMP it, and hitting an APC with it will, after 4 seconds channeling have the same effect as old null charge.

Destroy Engines - Through it is and was usefull, killing your allies isn't really cool, so now it will, instead of killing a dude, will turn him into a husk an set his maximum health to 30.  

# Wiki Documentation

Document this...

# Changelog

:cl:  SuperSlayer
rscadd: Adds Void Touch ability to slings
rscdel: Removed Null Charge from slings
tweak: Destroy Engine sling spell now doesn't kill a thrall, instead it makes the thrall weaker
tweak: More knockdowns on Enthrall
/:cl:

### CODE REVIEW

**Comment by stwordcitizen** [comment]
shadowlings aren't weak at all, they have 2 overpowered abilities (icy veins and glare) that carry them the entire game unneeded rework

**Comment by ghost** [comment]
> shadowlings aren't weak at all, they have 2 overpowered abilities (icy veins and glare) that carry them the entire game unneeded rework

I don't think so. While they are not very easy to kill, their goal is not to survive untill the end, but get 15 thralls, which is not very easy for them. It takes like... Many time to get one, and then they get deconverted in mosy cases, all your teammates die, and you are left alone to suffer. Glare isn't OP at all, it is just a shitty targeted stun, and icy veins were nerfed, making them more defensive than usefull. And having very ninche use and weak spells such as rapid re-hatch and null charge is not cool.

**Comment by SomeguyManperson** [comment]
important to note rapid rehatch isn't meant to do anything practical it's for cases you end up without sling shit for some reason

**Comment by ghost** [comment]
> important to note rapid rehatch isn't meant to do anything practical it's for cases you end up without sling shit for some reason

Ok

**Comment by ghost** [comment]
Actually most of the people that think that slings aren't weak only played against them, and never played as a shadowling

**Comment by ghost** [comment]
Fuck

**Comment by ghost** [comment]
Actually ready now

**Comment by JamieD1** [comment]
They are not weak in the slightest.

**Pull request closed without merging**
