### PR TITLE
Remove slowdown from snow tiles

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

"What if we made a mining map, and it was a really cool and well designed mining map, BUT, we gimped all the miners with every block giving you a 2 slowdown"

Slow snowing you down sucks, and the main gripe people usually hold about ice stations is the incessant slowdown given to you by walking in snow.

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: snow no longer slows you down 
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
GIVE THEM SNOWSHOES!!!

**Comment by N3D6** [comment]
> GIVE THEM SNOWSHOES!!!

As far as I’m aware there’s no way to do that. If you would like to try, and make shoes that take away slowdown on snow and ice only I’ll close this.

**Comment by Annoying-plant** [comment]
> GIVE THEM SNOWSHOES!!!

would it be possible to make shoes with a reduction to slowdown only when your on snow tiles?
I actually really like simple horrors idea of snow shoes as someone who loves using geldakinesis to decorate areas with snow tiles.

**Comment by N3D6** [comment]
> > GIVE THEM SNOWSHOES!!!
> 
> would it be possible to make shoes with a reduction to slowdown only when your on snow tiles? I actually really like simple horrors idea of snow shoes as someone who loves using geldakinesis to decorate areas with snow tiles.

I don't think we have support for that

**Comment by MajManatee** [comment]
in RP our now is an inch deep, or maybe two. Either way that wouldn't slow anyone down.

**Comment by JamieD1** [comment]
make it half as slow

**Comment by N3D6** [comment]
> make it half as slow

Ice mining is still going to be painfully garbage then, there's no point

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
