### PR TITLE
new miant doors

### PR DESCRIPTION
**Pull request by Potototatoh**
### Intent of your Pull Request

alters/updates the maintenance door to be slightly less generic and adds some sounds to this alongside the overlays to the door and it fucking sucked to make this

Screenshot (702)

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#### Changelog

:cl:   
soundadd: added ne w sounds 
imageadd: added a new maint door 
imageadd: added a new folder w/ a overlay file
imagedel: deleted the old maint door
/:cl:

### CODE REVIEW

**Comment by overlord12345** [comment]
Thats one nice looking door but not shure if its gonna fit in

**Comment by LoliconSlayer** [comment]
Why is the image slightly rotated

**Review by nesisknesis — COMMENTED** [review]
what does it look like in game

**Comment by boodaliboo** [comment]
> what does it look like in game

it foenst

**Comment by Potototatoh** [comment]
engrish

**Comment by patpol4** [comment]
Why would it open vertically if all other airlocks open horizontally.

**Comment by nesisknesis** [comment]
> Why would it open vertically if all other airlocks open horizontally.

space airlocks open vertically too

**Comment by oklews** [comment]
Looks like a hippiestation sprite ngl

**Comment by nesisknesis** [comment]
closed due to dislikes + week old

**Comment by deathslayer2481** [comment]
I liked it :(

**Pull request closed without merging**
