### PR TITLE
Blue vacuum lights are now at regular brightness instead of at 25%

### PR DESCRIPTION
**Pull request by ghost**
# Intent of your Pull Request

Vacuum lights are blue but now at regular brightness instead of 25% (4 is 25% of 8 fight me nerds)

#### Changelog

:cl:  
tweak: tweaked a few things  
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Yes

**Comment by Hopekz** [comment]
Here is how this change looks compared to a room over

image

**Comment by MegaEmpirical** [comment]
Fuck yeah.

**Review by SomeguyManperson — APPROVED** [review]
yes

**Comment by Georgeur** [comment]
thank fucking god, this always bugged me.

**Review by JamieD1 — APPROVED** [review]

**Comment by Ktlwjec1** [comment]
I know I'm days late but for future reference please make your changelogs more descriptive, as "tweaked a few things" means absolutely nothing to players reading the server changelog.

**Pull request merged**
