### PR TITLE
Moves Syringe Gun to Armoury and Rapid to Armoury Lathe

### PR DESCRIPTION
**Pull request by JamieD1**
This will be controversial, the issue is the syringe gun is 99% of the time used by valid hunters, so i'm moving to to sec who are allowed to valid hunt.

:cl:  
tweak: Moves Syringe gun to Armoury and Rapid to Armoury Lathe
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
This is certainly interesting to say the least

**Comment by iamthesilly** [comment]
could maybe put one in the CMO locker too

**Comment by Moltijoe** [comment]
probably for the best rather than nerfing them into the ground

**Comment by Skrem7** [comment]
> could maybe put one in the CMO locker too

CMO has their flash and baton AND instant hypospray, why do they need the syringe gun?

**Comment by Mantlecrawler** [comment]
This gets a medical lizard sticker of approval

**Comment by Moltijoe** [comment]
> CMO has their flash and baton AND instant hypospray, why do they need the syringe gun?

i see it less as giving cmo a syringe gun and more as restricting the doctor's syringe guns to only CMO.
that way assuming something happens, the cmo can always either use it or provide it to a trusted medbay member without needing access to the armoury.

also, adds another reason for people to break into the cmo office

**Comment by 00ze-cyclone** [comment]
> > CMO has their flash and baton AND instant hypospray, why do they need the syringe gun?
> 
> i see it less as giving cmo a syringe gun and more as restricting the doctor's syringe guns to only CMO. that way assuming something happens, the cmo can always either use it or provide it to a trusted medbay member without needing access to the armoury.
> 
> also, adds another reason for people to break into the cmo office

Yeah but it’ll still probably only be used for validhunting by non sec in that case and that’s what we want to stop

**Comment by Moltijoe** [comment]
> Yeah but it’ll still probably only be used for validhunting by non sec in that case and that’s what we want to stop

if it's in the cmo's office, that means for it to be used in valid hunting,
either someone needs to break into the office. 
(if they're valid hunting that means they're not an antag and this could very easily be bwoink or even ban worthy)

or the CMO authorized it's used
(which any sane CMO would not allow unless the situation actually calls for it)

or the CMO themselves is using it
(Which, if they're valid hunting as a command role that isn't HoS, could end up as a command ban)

**Comment by SomeguyManperson** [comment]
Just remove it entirely?

**Comment by Notamaniac** [comment]
I think it's of very limited utility to sec, considering they have access to reagent shotgun darts, and it's in a rare blue moon that security and chemistry ever cooperate together. To the point that I would say remove it entirely- but then we're progressing down the route of removing every single dangerous thing from every department because it could be used to valid hunt.

I don't know if hugbox station is what we're going for but it's certainly setting a precedent for it.

**Comment by Sniblet** [comment]
The only source of useful syringe gun chemicals immediately available to security is the lethal injection syringes
This is an excellent idea

**Comment by Moja10** [comment]
I don't think anything needs to be changed about syringe guns at all, but if you are channeling aggressive Jamie autism and are hellbent on this, give it to the CMO in CMO so he can distribute it as needed, rather than this change. This makes literally no sense, why would literally ANYONE in security bother with a syringe gun when they have shotguns with slugs, buckshot, incendiaries. If those wouldn't satisfy them and they want to work with another department for meme results, why would they bother with a syringe gun over tech rounds in a shotgun with pulse beams, frag-12, more incendiaries, and meteor-shot. 

Also, imagining security validhunting with a syringe gun, the literal only application I can realistically think of is that they validhunt someone with the lethal syringes they get, which sounds pretty horrible, and doesn't improve the round in the slightest.

**Review by ToasterBiome — APPROVED** [review]
map is fine, this is not a code approval

**Pull request merged**
