### PR TITLE
Makes bloodsucker passive heal also heal metal limbs (don't question it)

### PR DESCRIPTION
**Pull request by Moltijoe**
Can't have an antag be objectively terrible just because they picked the wrong species

:cl:  
tweak: Bloodsucker healing can heal metal limbs but at half power(balance reasons, don't question the logic)
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Blood needs iron to carry oxygen > more blood more iron > iron fixes mechanical limbs  👍

**Comment by cuackles** [comment]
Hold on I was thinking of vampires nevermind

**Comment by Moltijoe** [comment]
> Blood needs iron to carry oxygen > more blood more iron > iron fixes mechanical limbs 👍

preterni need iron to repair their plates > more iron > more plates

**Comment by tattax** [comment]
it's intentional in the sense preternis can repair burn damage and brute with welders and cables, which is far more common than meds, which just makes them just better bloodsuckers since you'd have the tools already anyways (you need them to build the base)

**Comment by Moltijoe** [comment]
> it's intentional in the sense preternis can repair burn damage and brute with welders and cables, which is far more common than meds, which just makes them just better bloodsuckers since you'd have the tools already anyways (you need them to build the base)

welders are more common, but not so much stronger or more common that it warrants removing a big mechanic of an antag to balance

**Comment by UltraBigRat** [comment]
should probably also do this for blood cult healing crystal thing passive heal. could be out of scope for the pr though

**Comment by Moltijoe** [comment]
> should probably also do this for blood cult healing crystal thing passive heal. could be out of scope for the pr though

It is, but id argue that ones more reasonable for it to not work since its a team antag ability rather than solo antag

**Review by ToasterBiome — APPROVED** [review]
Can you make the healing slower on mech limbs instead? Tatax raises a good point balance wise. Robotic limbs have a near endless amount of free repair anywhere in the station.

**Comment by Moltijoe** [comment]
> Can you make the healing slower on mech limbs instead? Tatax raises a good point balance wise. Robotic limbs have a near endless amount of free repair anywhere in the station.

yeah, i can do that, will probably require rewriting to account for limbs rather than the body as a whole

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
do pls

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
