### PR TITLE
Marker beacons are dimmer

### PR DESCRIPTION
**Pull request by Sniblet**
# Document the changes in your pull request

They don't need to glow brightly to be seen on lavaland. If they're not on Lavaland, they're being used to validhunt.

# Changelog

:cl:  
tweak: Marker beacons are dimmer
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
marker beacons don't do shit against slings, what are you on, they get wreckt by veil

**Comment by UltraBigRat** [comment]
maybe just make them able to be shut off by shadowlings in general, they really shouldnt be a tool used for validhunting at all.

**Comment by Simplehorror** [comment]
> maybe just make them able to be shut off by shadowlings in general, they really shouldnt be a tool used for validhunting at all.

they CAN

**Comment by Sniblet** [comment]
Veil has a cooldown. Marker beacons are cheap, plant in 1 second, and stack up to 30 at a time.

**Comment by Simplehorror** [comment]
> Veil has a cooldown. Marker beacons are cheap, plant in 1 second, and stack up to 30 at a time.

Try thralling the miners

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Lol people defending powergaming the system against slings

**Comment by MommaDragon** [comment]
Marker Beacons are now useless... because they were apparently being abused? Why didn't you just make them _not_ work (or not plantable) unless it was on Lavaland?

**Pull request merged**
