### PR TITLE
Revert "White Caps from Chernobyl 2: Electric Bogaloo"

### PR DESCRIPTION
**Pull request by Amelia0010**
Reverts yogstation13/Yogstation-TG#5838

Code bloat

### CODE REVIEW

**Comment by Mr-Space** [comment]
Nich gets upset by code bloat 2019

**Comment by ThatLing** [comment]
but u merged it nich

**Comment by Amelia0010** [comment]
yes but space complained about code bloat so fuck him

**Comment by Mr-Space** [comment]
There's no code bloat comrade, you're delusional

**Pull request closed without merging**
