### PR TITLE
Adds mutadone pills to cloning room for better access to them

### PR DESCRIPTION
**Pull request by JamieD1**
Adds a pill bottle of mutadone into the cloning pod room and some monkey cubes.

:cl:  
rscadd: Adds pill bottle of mutadone and cubes to cloning room. 
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
Will this make people less willing to break into Genetics for monkey cubes despite monkey cubes being one of the less efficient ways to get synthmeat early on?

**Comment by JamieD1** [comment]
> Will this make people less willing to break into Genetics for monkey cubes despite monkey cubes being one of the less efficient ways to get synthmeat early on?

Yes. This is one of the reasons for the PR as well.

**Comment by Aquizit** [comment]
> Will this make people less willing to break into Genetics for monkey cubes despite monkey cubes being one of the less efficient ways to get synthmeat early on?

There are *four* breakers of cryox next to the tubes at start of round. Just grab a syringe and inject it with your own blood and boom instant synthmeat.
Do it right next to cloning for most convenient results.

Edit: I'm dumb you said less efficient derp.

**Review by patpol4 — CHANGES_REQUESTED** [review]
Remove the ones in genetics so we dont double the roundstart materials suddenly

**Comment by patpol4** [comment]
Also i dont like this because it removes human interaction and makes things more hugboxy by handing you items on a platter

**Comment by JamieD1** [comment]
> Remove the ones in genetics so we dont double the roundstart materials suddenly

Considering I already nerfed the pill amount before, I dont think this is an issue

**Comment by Hopekz** [comment]
> Also i dont like this because it removes human interaction and makes things more hugboxy by handing you items on a platter

This.
What's the point of having requirements for something if you are just handed the items you need every single time?
Defeats the purpose of having them in the first place since it just goes back to free cloning

**Comment by Cartlord** [comment]
> 
> 
> > Also i dont like this because it removes human interaction and makes things more hugboxy by handing you items on a platter
> 
> This. What's the point of having requirements for something if you are just handed the items you need every single time? Defeats the purpose of having them in the first place since it just goes back to free cloning

I agree TBH, I think this is a shortsighted change that'll reduce greytiding but also reduce skill severely

**Review by patpol4 — APPROVED** [review]
Map is fine in a technical sense, i still stand by my previous statements.

**Comment by patpol4** [comment]
Not only does this contribute to material availabilty powercreep and thus raise hugboxiness, but also goes against the philosophy of item scarcity that drives player interaction forwards and gives cargo a job

**Comment by JamieD1** [comment]
> Not only does this contribute to material availabilty powercreep and thus raise hugboxiness, but also goes against the philosophy of item scarcity that drives player interaction forwards and gives cargo a job

Also prevents lots of admin/player issues. I think thats worth it compared to all the arguments here which are people complaining about pills people can make quite easily in chemistry

**Comment by patpol4** [comment]
Stale and bad

**Pull request closed without merging**
