### PR TITLE
makes the gravity generator SMES on box be wired to the wirenet

### PR DESCRIPTION
**Pull request by athena413**
why wasnt it wired?????????

it has enough charge to not matter but theoretically it still can run out of power

#### Changelog

:cl:  
rscadd: fixes wirenet connection to smes
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Also ai is not powered, I mentioned this in the first week I joined here and people said it was intentional?!?!?!

**Comment by Mick1299** [comment]
They were intentionally not wired because of power sinks. If they were wired, you could essentially turn off gravity, knock out the ai and all its sat defences, turn off comms, and cause mass chaos with a single item.

**Comment by athena413** [comment]
closing this for reasons

**Comment by alexkar598** [comment]
Powersinks dont drain smes, they just drain APCs and prevent SMES from charging

**Comment by JamieD1** [comment]
> Powersinks dont drain smes, they just drain APCs and prevent SMES from charging

Finally someone with sense

**Pull request merged**
