### PR TITLE
You can now create bomb payloads from materials on the station.

### PR DESCRIPTION
**Pull request by Xoxeyos**
You can create said bomb payload with three plasteel, a bluespace crystal, three IEDs, cable coil, two empty grenade canisters, and a matter bin.

:cl:  
rscadd: You can now create a bomb payload out of things found on the station.
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
But why?

**Comment by Bibby0110** [comment]
We can already make this using C4, which is better imo

**Comment by jcatjmeow** [comment]
But c4 is antag only

**Comment by Bibby0110** [comment]
> But c4 is antag only

So?

**Comment by Takahiru** [comment]
but gamer c4 is traitor only not even antag only

**Comment by Bibby0110** [comment]
So?

**Comment by Takahiru** [comment]
gamer stop acting like gamer

**Comment by Bibby0110** [comment]
> gamer stop acting like gamer

It's locked behind traitor only for a reason innit.

**Comment by Hopekz** [comment]
> It's locked behind traitor only for a reason innit.

Honestly, this argument doesn't apply unless we move maxcaps/bombs/grenades to traitor only.
This is just usual chem/sci/whatever bomb-making except there is a less powerful ghetto version with lots of steps.

**Comment by JamieD1** [comment]
> > It's locked behind traitor only for a reason innit.
> 
> Honestly, this argument doesn't apply unless we move maxcaps/bombs/grenades to traitor only.
> This is just usual chem/sci/whatever bomb-making except there is a less powerful ghetto version with lots of steps.

They have an IC reason to exist..

**Comment by Hopekz** [comment]
> They have an IC reason to exist..

Alright, I'll bite and try to understand your logic what's your IC reason for chem having quick bombs and grenades.

**Comment by Ratvar** [comment]
I believe payloads are much more balanced alternatives to TTVs and chembombs: this pr either enables to cut on other variants or makes people realize that bombs are bullshit to fight and need a nerf overall again, and I support both

**Comment by Firewolf34** [comment]
This is something we've needed for a while. There's all these mechanics surrounding bomb payload removal and etc. and it's useless because traitors aren't going to mess with that.

**Comment by JamieD1** [comment]
> > They have an IC reason to exist..
> 
> Alright, I'll bite and try to understand your logic what's your IC reason for chem having quick bombs and grenades.

Honestly, this argument doesn't apply unless we move maxcaps/bombs/grenades to traitor only.

Research?.. Whole point of toxins testing

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
Its a traitor weapon, why could you craft a traitor weapon from a couple of cans of soda

**Pull request closed without merging**
