### PR TITLE
Removes stupid boxes containing only one item

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Now implanters buyed through syndicate uplink do not come in boxes, because it is stupid to send a sole item in a storage box(wtf). 

# Changelog

:cl:  
tweak: Implanters no more come in boxes
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
What are you kidding me

**Comment by ghost** [comment]
I fucking did clean all the hivemind shit out, why it is fucking here

**Comment by MegaEmpirical** [comment]
A perfectly valid change, I just so happen to like my free box.

**Comment by ghost** [comment]
> A perfectly valid change, I just so happen to like my free box.

You can easily make it without purchasin an item through an uplink.

**Comment by redmoogle** [comment]
dont forget to remove from the centcomm station

**Comment by Bibby0110** [comment]
Reopen when it compiles

**Pull request closed without merging**
