### PR TITLE
Revert "removes all maps except box from rotation because the playerbase is always right"

### PR DESCRIPTION
**Pull request by LoliconSlayer**
Reverts yogstation13/Yogstation#12813

You all know how I feel about Box at this point

### CODE REVIEW

**Comment by Mqiib** [comment]
speedmerge dis

**Comment by Junkyshell** [comment]
speedclose dis

**Comment by Hopekz** [comment]
Can you at least wait a day before you post a panic reaction revert?
I think we may have a rule about this

Side note:
I'm actually interested if we're allowed to instantly revert PR something just merged because I wanted to do that a few times before and if it stays open it also means we don't really have to have an argument to make these PR's (since there is no real description or reasoning provided).
If the precedent is set I'll be doing it in the future as well whenever a PR is merged that I don't like.

**Comment by KillerOrcaCora** [comment]
I am contracted to side with mords opinion in anything good bye box ;-;

**Comment by patpol4** [comment]
#12812
#12813

**Comment by patpol4** [comment]
Any rationale behind this outside of "i dont like box" ?

**Comment by LoliconSlayer** [comment]
> Any rationale behind this outside of "i dont like box" ?

Box is too small for highpop and playing it over and over nonstop on end is bad, even the small amount of variety that existed before disabling all the other maps is better than no variety at all.

**Comment by adamsong** [comment]
> Any rationale behind this outside of "i dont like box" ?

Reverting a config change that was made without HC review

**Comment by Marmio64** [comment]
I hope you plan on maintaining them yourself then

**Comment by Hopekz** [comment]
> Reverting a config change that was made without HC review

Are you high the PR that you are referring to was made by a HC

**Comment by patpol4** [comment]
It was merged without the other hc reviewing it

**Comment by Hopekz** [comment]
> It was merged without the other hc reviewing it

There is no "other HC must approve the first HC's PR" workflow to the best of my knowledge.
If it is a thing then sorry HC's self merge their PR's all the time.

**Review by SomeguyManperson — APPROVED** [review]

**Comment by bruhlookatthisdood** [comment]
So we might as well remove the map vote too right?

**Comment by LoliconSlayer** [comment]
> So we might as well remove the map vote too right?

Ideally, yes.

**Pull request merged**
