### PR TITLE
[admin] Xamtam asked us to

### PR DESCRIPTION
**Pull request by TheReddDragon**
:cl:  
tweak: default now links to forum
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Outrageous pr,mine is better

horror

**Comment by TheReddDragon** [comment]
I’m sorry who uses an iPod?

Regardless, mine at least contains a CHANGELOG

**Comment by alexkar598** [comment]
It’s 200$ cheaper and it can still call using wifi so Fork you. Also no change logs because it’s not a game issue it’s a byond hosting thing :P

**Comment by TheReddDragon** [comment]
ItS a TwEaK

**Comment by Fillywonk** [comment]
Just use Android, they're 200 dollars cheaper and they allow you to use a SIM.

**Comment by TheReddDragon** [comment]
iPhone for the win

**Comment by alexkar598** [comment]
filly you don’t understand,I got this iPod for free via a gift thing with points

**Comment by TheReddDragon** [comment]
iPhOnE xR iS bEsT pHoNe

**Pull request closed without merging**
