### PR TITLE
Centcom and ClockCult - Slimfast Edition

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Removed alot of crap from centcom z level and clock cult to save on memory

#### Changelog

:cl:  
bugfix: Took out the garbage
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
you removed laser tag and the ninja ruin if ninjas send anyone this pr will make them instantly die off suffocation the clock part is ok

**Comment by boodaliboo** [comment]
> you removed laser tag and the ninja ruin if ninjas send anyone this pr will make them instantly die off suffocation the clock part is ok

ignore me

**Comment by JamieD1** [comment]
This has not been tested,

Let me know if this might be merged and ill refine it and test it properly.

**Review by patpol4 — CHANGES_REQUESTED** [review]
1. Rogue and missing areas:
huQCKoOFcK
VqcmU3GcT0.
2. If we really do go through with this i would suggest backing up the ctf arena to a separate map file instead of just deleting it.

**Comment by JamieD1** [comment]
Redundant now due to linux memory

**Pull request closed without merging**
