### PR TITLE
Adds a job blacklist to certain quirks

### PR DESCRIPTION
**Pull request by Moltijoe**
Adds a job_blacklist variable to quirks, if someone rolls a job and one of their quirks is in the blacklist, all their quirks will be removed

Currently applies to the following quirks for all of command and security (minus detective because they're a meme)

- blind
- brain tumor
- deaf
- pacifist (security only)
- paraplegic (security only)
- social anxiety
- sheltered
- ineloquent
- brain damage

# Why is this good for the game?
Certain jobs shouldn't be allowed to take quirks that basically make them incapable of properly doing their job
it's basically just head jobs and
If someone wants to be quirky then they shouldn't be taking a highly impactful job (why have i barred RD then i wonder)
Allows for easy modifications so if i've forgotten a quirk, or one seems overly restrictive, it's super quick to MAKE YOUR OWN PR CHANGING IT

main thing i'd want is adding some sort of way to tell which jobs are blacklisted from a quirk

# Testing
image

:cl:  
rscadd: Adds a job blacklist to certain quirks
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
Now this is nice. No more seccies in wheelchairs

**Comment by neeshacark** [comment]
brain tumor is perfectly fine as command, you just need to take your mannitol pills. if you're smart about it it's never an issue

**Comment by Moltijoe** [comment]
> brain tumor is perfectly fine as command, you just need to take your mannitol pills. if you're smart about it it's never an issue

aight

**Comment by UltraBigRat** [comment]
You clearly have never had the law zoom at you at supersonic speeds with a fire extinguisher.

**Comment by Moltijoe** [comment]
> You clearly have never had the law zoom at you at supersonic speeds with a fire extinguisher.

I have, but ive also seen a single click unbuckle them and doom them.
They dont need to have fucked up legs to use a wheelchair

**Comment by UltraBigRat** [comment]
Either way being serious i dont particularily see why this is necesarry outside of perhaps blind or deaf which does severely limit you. Most of these quirks arent that debilitating, and usually if someone is daring enough to take it it tends to just make the round more interesting rather then make them dead weight. This is just my opinion though, but i really dont see why this is necesarry for most of these, other then the ones that SEVERELY limit interaction like blind, deaf and maybe sheltered. 

I myself embrace our brain damaged paraplegic overlords far more then the usual power trippers.

**Comment by Moltijoe** [comment]
> Either way being serious i dont particularily see why this is necesarry outside of perhaps blind or deaf which does severely limit you. Most of these quirks arent that debilitating, and usually if someone is daring enough to take it it tends to just make the round more interesting rather then make them dead weight. This is just my opinion though, but i really dont see why this is necesarry for most of these, other then the ones that SEVERELY limit interaction like blind, deaf and maybe sheltered.
> 
> I myself embrace our brain damaged paraplegic overlords far more then the usual power trippers.

I understand the sentiment, i think its worth waiting to be seen

**Comment by neeshacark** [comment]
aw damn i just realized this kills paraplegic warden, so sad, massive f

**Comment by Moltijoe** [comment]
> aw damn i just realized this kills paraplegic warden, so sad, massive f

Security really shouldnt be taking quirks that actively make them worse at doing their only job, especially when its one that affects the round so much.
Mining taking paraplegic is just as bad, arguably worse, but they just ruin the round for themselves, not others by letting antags walk all over then

**Comment by neeshacark** [comment]
> > aw damn i just realized this kills paraplegic warden, so sad, massive f
> 
> Security really shouldnt be taking quirks that actively make them worse at doing their only job, especially when its one that affects the round so much. Mining taking paraplegic is just as bad, arguably worse, but they just ruin the round for themselves, not others by letting antags walk all over then

imo this is my take as someone who frequently did paraplegic warden - its not overly a concern when you are mostly confined to one area that really isnt that large. worst case someone manages to take your wheelchair but even without you still have more guns than god so...

thats just my take though idc i dont really play paraplegic anymore

**Review by ToasterBiome — APPROVED** [review]

**Comment by Am37000** [comment]
HECK NAH! Wheelchair security is proven to be way faster than normal security! Plus you cant really be slipped.

**Comment by Am37000** [comment]
> > You clearly have never had the law zoom at you at supersonic speeds with a fire extinguisher.
> 
> I have, but ive also seen a single click unbuckle them and doom them. They dont need to have fucked up legs to use a wheelchair.


Nah, only bad seccies get unbuckled. Its like when a seccie is still learning how to use eguns and flashbangs and stuff like that effectively. You'll kinda suck at first but you will get used to it. The skill ceiling is high and the wheelchair sec knows no speed limit. Plus Warden being in brig most of the time doesn't need a speed boost, because they effectively turn into a wall.

**Comment by Am37000** [comment]
Atleast make paraplegic compatible with security officer.

If they suck at it, then they'll stop.

**Pull request merged**
