### PR TITLE
Removes plasma tits from polysmorph

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

all traces of plasma vessels are now wiped from the code
tested in private server, works, no runtimes
fuck your massive tits this isnt skyrat

#### Changelog

:cl:  
rscdel: Removed plasma vessels from polysmorph
imagedel: Removed plasma vessels from polysmorph
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
I am indifferent in regards to whether or not this is merged. Thank you for doing something and not just complaining forever, ynot.

**Comment by Mesalikepie** [comment]
Let's gooooooo!

**Comment by Tipy1802** [comment]
While you are at it remove the tits from the human sprite (pretty sure they are the same size as plasma vessals). I have been stuck staring at my monitor and masterbating for 3 months now, free me from this fetish content

**Comment by jcatjmeow** [comment]
> While you are at it remove the tits from the human sprite (pretty sure they are the same size as plasma vessals). I have been stuck staring at my monitor and masterbating for 3 months now, free me from this fetish content

I know you're being facetious but I unironcially support this and will be pring it later today

**Review by jcatjmeow — APPROVED** [review]

**Comment by UselessTheremin** [comment]
bro give bubblegum clothes he is too raging hot i cant take it, i just find 32x32 spacemen so sexually attractive and fulfilling uwu 🥵 🌶️ 🔥

**Comment by ynot01** [comment]
idrc about the blocky human tits, they have no where near the amount of detail the plasma vessels have

but if you want to remove them ill support it

**Comment by JackKindred** [comment]
Get 'em outta here, coach! +1 I support.

**Review by SomeguyManperson — APPROVED** [review]

**Comment by UselessTheremin** [comment]
> idrc about the blocky human tits, they have no where near the amount of detail the plasma vessels have
> 
> but if you want to remove them ill support it

Kek how tf are blocky tits sexual it would be weirder for the people to just be completely blank with ss13’s style of pseudo realism, but I do feel like the xenos are too far.

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Goodbye Tits

**Pull request merged**
