### PR TITLE
Increases the price of Australian Slime Mutator from 10 TC to 25 TC.

### PR DESCRIPTION
**Pull request by nesisknesis**
Same points from #6097 

Large grief potential with spiders. As well as this, it is comparable with romerol, perhaps even more destructive seeing as spiders have an easier time of laying eggs. 

As a 10 TC item, it is a no-brainer if a syndi took this every time they were a scientist as it gives them a huge advantage when causing chaos and bringing the station to its knees. Raising it to 25 TC will make it a larger investment for how powerful spiders are and require another uplink. In my opinion, it is also an item intended for traitors with hijack rather than the common folk with steal the ce's magboots.

#### Changelog

:cl:  Identification 
tweak: The price of the Australian Slime Mutator is now 25 TC rather than 10 TC. 
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Thats dumb. It's a hijack item, restrict it to such.

**Comment by ynot01** [comment]
i dislike this because it's actually controllable. xeno sentients are forced to listen to your every command, and broodmothers can set directives for their offspring. it's never "out of control" unless you have players blatantly breaking rules.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
maybe restrict it to hijack and glorious death instead?

**Comment by ghost** [comment]
@ynot01 It isn't controllable in the slightest.

Broodmothers can set directives for their offspring, which other broodmothers can remove without being noticed. Also, NPC spiders will attack people indiscriminately regardless.

**Comment by ynot01** [comment]
wait so this is intended for hijack traitors but is being made 25TC? how are they supposed to get it if they only start with 20TC? this makes it so only nukies and IAA could purchase this

**Comment by nesisknesis** [comment]
forgot this existed. its put to the same level of romerol because its practically just as destructive. also 'restrict to hijack and glorious death' is not done for any other item that ive seen so why would this have that restriction

**Comment by Amelia0010** [comment]
https://github.com/yogstation13/Yogstation-TG/blob/08462f1cf4e053d0d8d9254d66723f49cc3699c3/yogstation/code/modules/uplink/uplink_item.dm#L45 It's done for his grace and romerol https://github.com/yogstation13/Yogstation-TG/blob/08462f1cf4e053d0d8d9254d66723f49cc3699c3/yogstation/code/modules/uplink/uplink_item.dm#L29

**Review by Amelia0010 — APPROVED** [review]
someone else can make a PR to reduce the price if they're unhappy with this

**Pull request merged**
