### PR TITLE
[admin] Removes admin logging of smoke machine activations

### PR DESCRIPTION
**Pull request by Nickvr628**
What the title says. Seems unnecessary and just spam for the adminlogs.

### CODE REVIEW

**Comment by Ratvar** [comment]
Can we gitban nickvr already?

**Comment by Nickvr628** [comment]
why do we need admin approval for this smh

**Comment by alexkar598** [comment]
>admin log is supposedly spammed
not an admin

>why admin approval required
big thonk

**Comment by MasterPenguin5** [comment]
-3

**Comment by Rayisken** [comment]
No thanks, please do not touch

**Comment by Moja10** [comment]
All mass distribution of chems are logged, grenades, foam, anything that spreads chems in an area is logged because otherwise there would be no way to identify who exactly spread what across the station, where it is in the form of bomb, smoke, lube, foam, etc, aka: all things necessary to be logged in an easy way which you are removing with this PR. aka: hard no.

**Comment by Ratvar** [comment]
Moja, he knows that perfectly well, he just now added a smoke machine roundstart to security fnr and it was approved, then started bragging about it being broken if you upgrade it/swap it's chems. This PR is here literally just so he can abuse it even more then he intended.

**Comment by MegaEmpirical** [comment]
The only logging I want changed for spamming are bombs.

**Comment by AsV9** [comment]
No.

**Pull request closed without merging**
