### PR TITLE
Adds IAA to dynamic mode.

### PR DESCRIPTION
**Pull request by Xoxeyos**
:cl:  
rscadd: Adds IAA to Dynamic.
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
"Adds random hjack traitors that kill other antags as their only priority" might be not the best addition to the dynamic

**Comment by Xoxeyos** [comment]
Always can raise the threat level

**Comment by JamieD1** [comment]
@Xoxeyos Can you resubmit without the changelog stuff, I have add it to gitignore so it should work now for you.

**Comment by Xoxeyos** [comment]
> 
> 
> @Xoxeyos Can you resubmit without the changelog stuff, I have add it to gitignore so it should work now for you.

sure!

**Pull request closed without merging**
