### PR TITLE
TGUI Stripping

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request
Ports https://github.com/tgstation/tgstation/pull/57889

Old PR (2021), can be updated as we update required features from tg (i have not looked into it)

In any case, much better than what we had previously
image

# Why is this good for the game?
TGUI > no TGUI

# Testing
Setting internals works, pockets work, stripping works

# Changelog

:cl:  
rscadd: Added TGUI stripping menu
bugfix: Fixed xenos not having footsteps
/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
methinks these buttons could be organized better to avoid the great dedicated row of shoe
image
but hey it's leagues better than what we got rn so I'm not complaining

**Comment by ynot01** [comment]
> methinks these buttons could be organized better to avoid the great dedicated row of shoe image but hey it's leagues better than what we got rn so I'm not complaining

This is exactly how /tg/ had it (as can be seen in linked PR), and it's best to keep things as similar for future upgrading

**Comment by Cartlord** [comment]
I think this is an un-necessary change, and I think the squished/stretched icons in the menu look ugly. I also agree that it's not well-organized.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
can we make the icons not look awful?

**Comment by ynot01** [comment]
> can we make the icons not look awful?

Forced all icons 64px, required some resizing
No I don't know how to make the sides not touching the edges
No I don't know why the internals icon is so small and it won't get bigger
image

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
make the underlay icons also not poorly scaled

**Comment by ynot01** [comment]
> make the underlay icons also not poorly scaled

Done 
image

**Comment by ynot01** [comment]
image

**Comment by AMyriad** [comment]
> image

oooooooh very nice
would this by chance change based on UI preference?

**Comment by ynot01** [comment]
> oooooooh very nice would this by chance change based on UI preference?

No

**Comment by AMyriad** [comment]
> No

damn fair enough :^)

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
