### PR TITLE
Ports JukeBuild from TG Station

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

We really needed this
Ports: https://github.com/tgstation/tgstation/pull/59390 and updates it to its latest version

Will likely need heavy review to ensure compatibility

Major thanks for stylemistake for creating this

### CODE REVIEW

**Comment by redmoogle** [comment]
Ill figure out what part of dependency hell im in later *or never*

**Comment by redmoogle** [comment]
Needs testing (pretty sure it all works)

**Comment by Bibby0110** [comment]
> Needs testing (pretty sure it all works)

test it then

**Comment by Bibby0110** [comment]
@JamieD1

**Comment by redmoogle** [comment]
pretty clear this isnt being worked on to figure out if it will work with the live server

**Comment by Bibby0110** [comment]
> pretty clear this isnt being worked on to figure out if it will work with the live server

Sorry moogle :(

**Comment by JamieD1** [comment]
Now I feel like a shit.

**Pull request closed without merging**
