### PR TITLE
Disable demonic frost miner ruin on icemoon

### PR DESCRIPTION
**Pull request by N3D6**
# Describe the changes in your pull request

Disable the ruin that spawns the demonic ice miner megafauna

# Why is this good for the game?

Shit megafauna with shit AI, shit attacks, and drops literally nothing. No reason for it to exist unless someone improves it for some reason
# Testing
I didn’t test this but it should work as long as the ice ruin blacklist works
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: demonic frost miner no longer spawns
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
improve dont remove

**Comment by N3D6** [comment]
> improve don’t remove

No eat shit it’s an unfinished boss from a different codebase it either needs to be re-ported, finished or disabled and I’m not re-porting it or finishing it

**Comment by JohnFulpWillard** [comment]
:trollface:

**Comment by MajManatee** [comment]
planet dangerous uhh dont go outside dummy. occupational hazard.

**Comment by N3D6** [comment]
The “ided” label is laughably fucking stupid considering I haven’t had internet in around 4 months and the boss literally drops nothing and is useless noob bait, plus this is extremely easy to revert if someone decides to fix/finish it

**Comment by N3D6** [comment]
> planet dangerous uhh dont go outside dummy. occupational hazard.

It shouldn’t be possible for the human mind to be this silly
Did you even read the PR or are you just commenting to chat shit?

**Review by ToasterBiome — APPROVED** [review]
i expect you to fix this when you're back

**Comment by N3D6** [comment]
> i expect you to fix this when you're back

to fix it I’d have to unshit an entire boss fight to make it even worth fighting and no

**Pull request merged**
