### PR TITLE
Heads of staff now spawn together in the conference room.

### PR DESCRIPTION
**Pull request by Hopekz**
Why:
-----

If the heads of staff spawn in the conference room together it lets them see each other "face to face" as they start their day.
It forces them to "slow down" and even greet each other to maybe share what plans they have or to share some gimmick they want to do.

Before this PR the first point of contact for heads is someone asking "Do we have a [insert head here]?"
With this change heads of staff will be able to physically see each other making them more familiar with each other.

image

#### Changelog

:cl:  Hopek
rscadd: Heads of staff now spawn in the conference room to promote higher RP and familiarization.
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Love it

**Comment by maxion12345** [comment]
Not sure it's really required. At this point we might as well make the entire station spawn on the arrivals shuttle and rp commuting to work for three minutes.

**Comment by athena413** [comment]
i think this is good on paper, bad in practice

the reason most heads-of-staff spawn in their own office is so that they can immediately get their stuff and get to work, i think people are just gonna be like "hi" and then immediately walk off back to their departments

also this only applies to box, please make it like this on all maps

**Comment by Hopekz** [comment]
> At this point we might as well make the entire station spawn on the arrivals shuttle and rp commuting to work for three minutes.

I don't think so.
Regular staff are not appropriate for this dynamic. 
Heads of staff are the only people on the station that need to work closely together across departments. All other staff is fine with meeting each other in their own department.

**Comment by Jarod1200** [comment]
This is interesting but in the back of my head im thinking "cant wait for the traitor CMO and RD to sleepypen or pull out a stetchkin and kill everyone else in the first 2 minutes"

**Comment by MrHorizons** [comment]
I think it's an interesting idea, as well, but it seems that it'd just result in people trying to book it to their respective departments to get their shit together. I think it'd be better if it was something that had to be done some minutes into the shift, so people can get themselves set up and then be able to do all the planning.

**Comment by Mesalikepie** [comment]
I really like this PR. Such a good idea. As HOP or Cap it's so annoying calling off at the beginning of round heads sound off and half the heads never do. This encourages more rp and more connection between heads

**Comment by Xoxeyos** [comment]
Hell yeah. **I know where you're getting this from Hopek.**

**Comment by Hopekz** [comment]
> Hell yeah. **I know where you're getting this from Hopek.**

Yeah, I'm mimicking the idea itself from other RP,MRP servers.
The one that made me think to make this here was Eris (:

**Comment by Tipy1802** [comment]
I absolutely love it!

Just one small nit pick, I feel like the HoP should be the one to the right of the captain since he is the second of command and the captain’s right hand man

**Comment by Hopekz** [comment]
> Just one small nit pick, I feel like the HoP should be the one to the right of the captain since he is the second of command and the captain’s right hand man

The way I currently organized this is the two mindshielded head of staff get put on the top together while the 4 heads of staff that do not start mindshielded get put into the remaining groups based on the location of their department (to the side of where their departments are)

When the captain dies the HoS is usually the one to take over the captainship because he starts mindshielded and cannot be an EOTC.

Also, because of the orientation of the Captain facing down to the table: **the HoP is actually to the right hand of the Captain**. If we were to put the HoP to the right tile of the captain he would actually be on the left hand of the Captain.

**Comment by ynot01** [comment]
bruh what if one is like a ling or something and kills everyone else

**Comment by patpol4** [comment]
Love it

**Comment by Moggram** [comment]
If you have the Spiritual quirk, you will now spawn in the Chapel.

**Comment by athena413** [comment]
you know what i changed my mind i like this

heads of staff be like "who do we have" and then nobody fucken responds so this is cool

**Comment by Tipy1802** [comment]
> When the captain dies the HoS is usually the one to take over the captainship because he starts mindshielded and cannot be an EOTC.

That is not true, the hop is always the second in the chain of command, if the captain dies the hop becomes acting captain not the HoS

Also while not mindshielded the HoP cannot roll any antagonist role

It just makes more sense for the second in command to be right next to the captain and in front of everyone and not on the side but the hos beeing there is also fine

**Review by Amelia0010 — APPROVED** [review]
Will be merged after https://github.com/yogstation13/Yogstation/pull/9806 to avoid merge conflicts as this is the simpler PR to remake

**Review by patpol4 — APPROVED** [review]
What Nich said

**Comment by Hopekz** [comment]
@nichlas0010 , @wejengin2 

Fixed after Wej's PR. Good to go!

**Comment by MegaEmpirical** [comment]
Holy fuck I actually really like this.... I am concerned about Rev game though.

**Comment by alao3alao3** [comment]
Maybe those shiny lowpops where nobody griefs because there's nobody to grief isn't the best place to get ideas from huh. Hope the revert is swift.

**Pull request merged**
