### PR TITLE
removes RCD from autolathe

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request
everyone has an RCD now. Its fucking absurd. Last round I played sec, literally EVERYONE had one. Genetics, clerk, scientist, assistant, cargo tech, the doctors, EVERYONE. Maybe having it built in an autolathe is good for accessibility, but now everyone gets one. Its an absurdly powerful tool and should be limited to engineering. Just ask an engineer for one. Or break into engineering yourself, coward.
untested webedit
# Wiki Documentation
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscdel: Removed RCD from autolathe
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
You monster how could you

**Comment by maxion12345** [comment]
> You monster how could you

too powerful a tool to be so accessible

**Comment by Mqiib** [comment]
Then you get the one guy that runs in, buys all the RCDs and fucks off with them leaving NOBODY with an rcd. There needs to be SOME way to get new ones if the roundstart RCDs disappear.

**Comment by maxion12345** [comment]
> Then you get the one guy that runs in, buys all the RCDs and fucks off with them leaving NOBODY with an rcd. There needs to be SOME way to get new ones if the roundstart RCDs disappear.

aye
cargo packs can refill vendors. Also you start with 5 RCDs in the engivend now, so you really shouldn't be running out unless someone hoards them like a twat. It'll be like the hardsuits.

**Comment by ToasterBiome** [comment]
make them an engi protolathe item :^)

**Comment by maxion12345** [comment]
> make them an engi protolathe item :^)

probably a bad idea. being linked to the ore silo think of the amount of RCDs people could make in a short amount of time (ten at a time aswell)

**Comment by ToasterBiome** [comment]
> > make them an engi protolathe item :^)
> 
> probably a bad idea. being linked to the ore silo think of the amount of RCDs people could make in a short amount of time (ten at a time aswell)

Pretty much all material that would be in the autolathe that isn't roundstart comes from the protolathe ore silo links anyway, no different except you have to commit a B&E Restricted to get one

**Comment by N3D6** [comment]
yeah nah this sucks

**Comment by ZACSO-X** [comment]
Well RCDs are really just arguably better at breaking and entering then just, y'know, tools. RCDs have been printable on the autolathe for what? years? why is it only a problem now? and to only you? it has not been removed from being printed yet. You boast about it being too powerful a tool, even when the only thing that makes them better then tools and regular building is time, they aren't a weapon of mass destruction like the baseball bat, which was removed from standard crafting for good reason. They are more like a convinience, quickly building things to speed up the process of some project or fixing the station, they cant destroy reinforced airlocks, they cant destroy reinforced walls/non metal walls and really, when we are talking about breaking and entering, hacking is more effective, mostly because it's theoratically faster and doesn't destroy the airlock, or better yet, just use a jaws of life.

**Comment by knightshade0** [comment]
There aren't enough RCDs for engineering half the time anyway, so our solution is to remove them from autolathes? Hard pass.

**Comment by ynot01** [comment]
the reason there's 5 RCDs in engivend is because there can be 5 engineers roundstart

**Comment by Cartlord** [comment]
What if the Engi protolathe could make a disk you could put in autolathes to make them able to print RCDs?

**Comment by knightshade0** [comment]
I'm not sure if Cartlord's suggestion actually works with how the client works, but I'd take it as _something_. As it is we usually have greytiders breaking into engineering within the first minute or two anyway and if we're busy setting up the engine or some such it's very difficult to prevent them from grabbing an RCD and getting out.

You can say RCDs are a problem, but there needs to be a way to get more of them that doesn't rely on a QM that usually doesn't exist. 

Move it to the engineering protolathe? I don't know, but this is a blunt force solution that is overkill for the problem.

**Comment by Moggram** [comment]
There should be one RCD for each hardsuit in the engineering department and no more. If you want more, order them from cargo.

**Comment by Cartlord** [comment]
I just remembered: The Free Golem ship Lavaland ruin starts with a disk ont ehf lor, which has an autolathe design for free golem shells.
This means we can have disks that spawn roundstart which have designs on them.
What if there was a disk in Engi, roundstart, with the RCD design on it?

**Comment by maxion12345** [comment]
basically what I'm hearing is 
rcd autolathe bad
but not adding another way to make them worse
will think on it

**Comment by JamieD1** [comment]
Lets try this and if its too much we can add it back to the engi protolathe.

**Review by JamieD1 — APPROVED** [review]

**Comment by Junkyshell** [comment]
God fucking damnit

**Comment by Reed0506** [comment]
if this solution to RCDs existing turns out to be too annoying just make RCDs researchable or something

**Comment by sdk2013** [comment]
That just makes it annoying for everyone- engineers can't get RCDs easily, and the moment they're researched _everyone_ can get RCDs. It's a middle ground that accomplishes nothing but irritates everyone.

If it's too much, we can add it to the engineering protolathe so people at least have to break into the engineering foyer if they want one.

**Pull request merged**
