### PR TITLE
Moves the ORM to a place where people will like it

### PR DESCRIPTION
**Pull request by thehighwayman**
### Intent of your Pull Request

ORM is now connected to outside the supply office. I dunno if the mapmerge hook worked but I think it did

Fixes issue #1059

#### Changelog

:cl:  
tweak: Moved ORM around
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
This isn’t that necessary anymore with the emergence of ore vault

**Comment by ThatLing** [comment]
What Time said. Also, why?

**Comment by MegaEmpirical** [comment]
I have heard the ore vault mentioned but not learned what it is, can someone please explain?

**Comment by Bawhoppen** [comment]
@MegaEmpirical The ore silo, located in the vault, automatically "bluespaces" materials to machines it's connected to. It also receives materials from the ORM if it is connected. At default roundstart, it is connected to all of the departmental lathes and the ORM, meaning that there is no need to manually transfer ore and minerals around.

**Comment by MegaEmpirical** [comment]
I see, good to know. Then that would eliminate the need, and does explain how things have been restocking lately. Thanks.

**Comment by thehighwayman** [comment]
seems there isn't enough of a will to move it.

**Pull request closed without merging**
