### PR TITLE
[META] UPDATES DISPOSAL PATHING AND TECH

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request

#21983 but for meta. 
replaces all premade sort pipes with helpers
closes loops in the system and cleans up some wonky pathing 
gives departments their destination tagged bins 

# Why is this good for the game?
because no one was going to do it otherwise. look at the bug reports, make the bug reports, don't squat on bugs. and try other maps other than box

signed,
asshole

# Testing
coming back to this after i make a new image and load in

# Changelog

:cl:  

bugfix: it is now possible to mail to dormitories and the janitors closet
mapping: reroutes meta layout

/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
encountered a hiccup with it not going into recycle room

**Comment by wonderinghost** [comment]
doesnt actually goto the disposal room on box either. do not merge. need to figure out what is happening

**Comment by wonderinghost** [comment]
figured out the problem. something in the wiring for sorting pipes is breaking the system

**Comment by wonderinghost** [comment]
doesnt look to be wires

**Comment by wonderinghost** [comment]
#22202 fixed the issue so now it enters disposal room. rest is set and good

**Comment by Firewolf34** [comment]
The hero the non-box-maps deserve (and needed)

**Comment by wonderinghost** [comment]
i love having to update branch and it deletes my commits

**Comment by Moltijoe** [comment]
reopen this when you come back

**Comment by wonderinghost** [comment]
review libo'd

**Pull request closed without merging**
