### PR TITLE
more ice cream flavors from tg

### PR DESCRIPTION
**Pull request by ktlwjec0**
https://github.com/tgstation/tgstation/pull/77174

Adds new ice cream flavors to the ice cream cart, just the ones shown here:
**cherry chocolate chip is now just cherry chocolate**
image

Ups some ingredients amount in the food cart by 1 and adds the ingredients for the new ice creams.

# Spriting
I'm too stupid to get colors to only change on the ice cream top so I just sprited them individually.
image

# Wiki Documentation

ice cream vat on guide to food I can do this

:cl:  YakumoChen, Thalpy, Ktlwjec
rscadd: Lots more ice cream flavors in the ice cream vat.
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
this is just reminding me i need to TGUI the ice cream cart interface because it's so god damn bad 🥲 
however i think that also requires me to update our ice cream to how TG does it too

**Comment by BlueishTsunami** [comment]
My favorite flavor, blue

**Review by BlueishTsunami — APPROVED** [review]
Sprites look decent enough, ain't no chocolate chips in that cherry ice cream tho.

**Comment by ktlwjec0** [comment]
> Sprites look decent enough, ain't no chocolate chips in that cherry ice cream tho.

I'll just change it to cherry chocolate if that's an actual issue

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
