### PR TITLE
what idiot forgot to make shock touch have a fucking proximity check i swear to god 

### PR DESCRIPTION
**Pull request by ghost**
there it's fixed and now it only works on adjacent targets as intended

#### Changelog

:cl:  
bugfix: Shock touch now only works on ADJACENT targets, so that you can't shoot people through walls with it. Yes, this was a bug. 
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
UNLIMITED POWAR!!

**Comment by boodaliboo** [comment]
tg

**Comment by Mesalikepie** [comment]
No no this was intended Adam. Don't worry about it. (Laughs in dark lord)

**Comment by maxion12345** [comment]
>as intended

like the fucker who coded it wasn't thinking of ghetto emperor palpy in his spacemans

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
