### PR TITLE
remove a undroppable id from centcom

### PR DESCRIPTION
**Pull request by boodaliboo**
#### Changelog

:cl:   
bugfix: makes it so you cant pick up a undroppable id on centcom by removing it

/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Just wondering, why?

**Comment by Jarod1200** [comment]
I will note that ERT ids are normally not droppable. I assume this is intended and I have no idea if its related to this id you're messing with, but it is probably relevant.

**Comment by JamieD1** [comment]
Seems like a pointless PR as no-one ever uses the id and if they do they are admin, and if they are admins they can delete it if it needs to be deleted.

**Comment by Hopekz** [comment]
> Seems like a pointless PR as no-one ever uses the id and if they do they are admin, and if they are admins they can delete it if it needs to be deleted.

We've removed things in the past because our staff team can't be expected to delete the same item preventatively every shift. Much more efficient use of everyone's time to just remove this ID and give an ID to people that need it.

An ID spawning in this exact location is the equivalent of an all access ID spawning on the HoP console except once you pick up this ID you are unable to drop it.

If you hack/thermite blast doors or whatever you choose to get in you can very much pick up this ID on accident not knowing that it sticks to you with the power of magic.

**Review by Hopekz — CHANGES_REQUESTED** [review]
Fix your changelog.
You are removing an ID from the map and no fix is being applied to the ID itself.
If you want to "fix" this item you can make it drop-able by changing it's variable otherwise this is a removal.

**Comment by JamieD1** [comment]
> > Seems like a pointless PR as no-one ever uses the id and if they do they are admin, and if they are admins they can delete it if it needs to be deleted.
> 
> We've removed things in the past because our staff team can't be expected to delete the same item preventatively every shift. Much more efficient use of everyone's time to just remove this ID and give an ID to people that need it.
> 
> An ID spawning in this exact location is the equivalent of an all access ID spawning on the HoP console except once you pick up this ID you are unable to drop it.
> 
> If you hack/thermite blast doors or whatever you choose to get in you can very much pick up this ID on accident not knowing that it sticks to you with the power of magic.

People shouldn't even be doing this..

**Comment by Hopekz** [comment]
> People shouldn't even be doing this..

All the more reason to remove that possibility IMO.
It is good game design to remove what isn't meant to be played. In this case its using the all access ID.

Central Command (not counting the test section) is relatively tame in regard to what loot is given besides a few outliers such as this ID and armory contents, officer's vault etc.

If an antagonist manages to break in to central command possibly via a official being taken over and is able to get rid of a few blast doors with some explosives I personally wouldn't stop them outside of IC means but ensure that nothing "OP" gets left behind by deleting the few items before they get to them. Separate PR's should be opened to balance central command around the parts people are able to break in to.

I as an admin would not want one of these rewards to be an undroppable all access ID so that possibility should be removed entirely in my opinion.

**Comment by JamieD1** [comment]
> > People shouldn't even be doing this..
> 
> All the more reason to remove that possibility IMO.
> It is good game design to remove what isn't meant to be played. In this case its using the all access ID.
> 
> Central Command (not counting the test section) is relatively tame in regard to what loot is given besides a few outliers such as this ID and armory contents, officer's vault etc.
> 
> If an antagonist manages to break in to central command possibly via a official being taken over and is able to get rid of a few blast doors with some explosives I personally wouldn't stop them outside of IC means but ensure that nothing "OP" gets left behind by deleting the few items before they get to them. Separate PR's should be opened to balance central command around the parts people are able to break in to.
> 
> I as an admin would not want one of these rewards to be an undroppable all access ID so that possibility should be removed entirely in my opinion.

Erm what? 

They wouldnt be allowed into centcom. 

Are you mixing reality with yours again?

**Comment by Hopekz** [comment]
> They wouldnt be allowed into centcom.

You can intentionally break in to CentCom from the station in perfectly valid ways.

Just mentioning 2 ways off the top of my head:
- You can hide in the back compartment of the Shuttle (it is intentionally separated to allow for this)
- You can use the official's ID. It is the only droppable ID to make this specifically possible.

> Are you mixing reality with yours again?

Very rude.
Not everyone plays this game the same way you do. Yes I guess my "reality" is different in this case.

**Comment by boodaliboo** [comment]
> Fix your changelog.
> You are removing an ID from the map and no fix is being applied to the ID itself.
> If you want to "fix" this item you can make it drop-able by changing it's variable otherwise this is a removal.

done

**Comment by boodaliboo** [comment]
> > > People shouldn't even be doing this..
> > 
> > 
> > All the more reason to remove that possibility IMO.
> > It is good game design to remove what isn't meant to be played. In this case its using the all access ID.
> > Central Command (not counting the test section) is relatively tame in regard to what loot is given besides a few outliers such as this ID and armory contents, officer's vault etc.
> > If an antagonist manages to break in to central command possibly via a official being taken over and is able to get rid of a few blast doors with some explosives I personally wouldn't stop them outside of IC means but ensure that nothing "OP" gets left behind by deleting the few items before they get to them. Separate PR's should be opened to balance central command around the parts people are able to break in to.
> > I as an admin would not want one of these rewards to be an undroppable all access ID so that possibility should be removed entirely in my opinion.
> 
> Erm what?
> 
> They wouldnt be allowed into centcom.
> 
> Are you mixing reality with yours again?

ert pick this up all the time in the hopes to give themselves all access

**Comment by Hopekz** [comment]
> ert pick this up all the time in the hopes to give themselves all access

ERT spawn with all access already (except the Amber Task Force but they can't remove their ID's as well)

**Comment by boodaliboo** [comment]
> > ert pick this up all the time in the hopes to give themselves all access
> 
> ERT spawn with all access already (except the Amber Task Force but they can't remove their ID's as well)

the more you know

**Comment by Moja10** [comment]
It should not be intentional that an ID isn't removable, if an ERT is spawned and an antag validly kills them, they should be able to loot it off their body, not have it surgically attached. 

It is also not valid to break into Centcomm because every method involves bug abuse usually, and it is not allowed. It's not a gamer lootcrate area like space ruins. Don't break into Centcomm, even if you get an ERT ID IMO. It's not intended to be looted by any means.

**Comment by boodaliboo** [comment]
> It should not be intentional that an ID isn't removable, if an ERT is spawned and an antag validly kills them, they should be able to loot it off their body, not have it surgically attached.
> 
> It is also not valid to break into Centcomm because every method involves bug abuse usually, and it is not allowed. It's not a gamer lootcrate area like space ruins. Don't break into Centcomm, even if you get an ERT ID IMO. It's not intended to be looted by any means.

would you like if i reverted the pr making them undroppable?

**Comment by Moja10** [comment]
I have no clue why a literal ID would be undroppable in the first place.

**Comment by JamieD1** [comment]
> I have no clue why a literal ID would be undroppable in the first place.

Super Glue

**Comment by Ktlwjec1** [comment]
Does seem better to just make it droppable imo.

**Comment by Ktlwjec1** [comment]
I'm going to close this in favor of #8514 or, assuming that doesn't get merged, potentially redesign centcom a little to make the placement of the ID more secure. Otherwise this PR this just going to sit open for too long.

**Pull request closed without merging**
