### PR TITLE
adds an eldritch cowl (for me)

### PR DESCRIPTION
**Pull request by Marmio64**
Adds an eldritch cowl donator item locked to me. It's just a purple version of the fiend cowl with an animated glowing eye sprite. I need this so i can be a snowflake chaplain. Probably can't be power gamed.
eldritchcowl
its animated but im not going through the trouble of showing it. You can download the file if you really want to see it for some reason.

Shouldn't need a changelog as this will not effect anyone but me.
edit: also the hood wasnt properly hiding hair like its supposed to and trying to put the hide flags on it again was throwing errors so heres to hoping it works on the main server and i dont have to shave myself bald

### CODE REVIEW

**Comment by cowbot92** [comment]
better make it acidproof or else you're gonna have to watch your back binch 🔫

**Comment by Marmio64** [comment]
> better make it acidproof or else you're gonna have to watch your back binch 🔫

i wonder if i stealthily made it acidproof anyone would notice

**Comment by Chubbygummibear** [comment]
> > better make it acidproof or else you're gonna have to watch your back binch 🔫
> 
> i wonder if i stealthily made it acidproof anyone would notice

no one would notice because people just get mad about code concepts without actually reading the code :^)

**Comment by UselessTheremin** [comment]
looks neat, why just for you tho

**Comment by Marmio64** [comment]
> looks neat, why just for you tho

I want a special costume for use with the sect I created. There is already other thematically fitting costumes the chap can get, so it's not like im gatekeeping being able to look good just for me.

**Comment by nesisknesis** [comment]
This is the only PR regarding exclusive donator items that i've been able to review without jammie dodger bypassing me so this is my verdict:

So far it's been used to get in items that I wouldn't normally allow (a plushie of a player, and a snowflake amulet) so at this point I want to stop the trend of people adding stupid-shit like that.

Yours is a lot more reasonable but its an edit of a clothing item that was in a PR that added over 100 clothing that I have vowed vengeance against. If it were a genuine unique item that heavily improved your sect roleplay I could get behind it more but i'm going to be honest it's just another black cloak

**Pull request closed without merging**
