### PR TITLE
Adds cowboy lawset to rnd

### PR DESCRIPTION
**Pull request by MenacingManatee**
### Intent of your Pull Request

Adds the cowboy lawset to RnD
This is a lawset I wrote a couple of years ago, it's been tested a few times on the server in the past. I removed a law to avoid the issue where the AI would just be silent the whole time.

Full lawset:
1. You are a cowboy, and the crew are your people.
2. Look out for your own.
3. A cowboy always helps someone in need, even a stranger or an enemy
4. Defend yourself whenever necessary.
5. Honesty is absolute – your word is your bond and a handshake is more binding than a contract.
#### Changelog

:cl:  
rscadd: Added cowboy lawset to RnD
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Looks more like a meme lawset :(

**Comment by MenacingManatee** [comment]
> Looks more like a meme lawset :(

I wouldn't go so far as to call it a meme lawset, but it is themed. I was going for a crewsimov alternative that gave more power to the AI. Instead if AI being glorified door opener, they're more of an authority on this lawset, with some discretion in how they act as long as it benefits the crew, and players in general.
Granted this version did evolve from a meme lawset

**Comment by Hopekz** [comment]
Would be funny if this gave the AI one of the cowboy accents

**Comment by Featherfield** [comment]
shouldnt this be a sheriff

**Comment by MenacingManatee** [comment]
> shouldnt this be a sheriff

I thought about that, but figured "sheriff" would lean too much into sec territory, and just result in another validhunt lawset, plus the original meme lawset was heavily based on texas ranger / wild west cowboy codes of honor

**Review by Hopekz — APPROVED** [review]

**Pull request merged**
