### PR TITLE
Makes an attempt to remove Skewium in a way that's no longer retarded

### PR DESCRIPTION
**Pull request by LoliconSlayer**
Read the title

### Why is this good for the game?

Maybe crashing people with a chem is bad game design

#### Changelog

:cl:  
rscdel: Skewium has been removed.
/:cl:

### CODE REVIEW

**Review by jcatjmeow — CHANGES_REQUESTED** [review]
This is not how you blacklist a chem.

**Comment by LoliconSlayer** [comment]
I know

**Comment by Mqiib** [comment]
But if it works and does the job, is it stupid?

**Comment by LoliconSlayer** [comment]
In this case, yes.

**Comment by PrinceKirze** [comment]
From purely a game perspective, skewium's entire purpose is just to fuck with someone's game and maybe crash it. It deals inferior toxin damage compared to other poisons so that's just an added bonus as opposed to its main purpose. On the other hand, most of the time I see it used it's by shitlord chemists self-dosing or asking anyone if they want any rather than filling a syringe gun and finding a target to fuck. I'm sure it happens, but I doubt that's how it is in most use cases. I propose making the reaction yield less or modifying its recipe to make it require more things that chemistry doesn't have easy access to rather than removing it outright so that it's extremely unviable as far as toxins go, but dedicated chemists can still take a trip if they so desire.

**Comment by ghost** [comment]
time to add it to the traitor poison kit

**Comment by ToGWtF** [comment]
crash-based combat.

unironically ive seen someone use it for that purpose

**Comment by boodaliboo** [comment]
in all my years playing i have never once seen it being used as a weapon but i would be for adams suggestion of adding it to traitor chemical kit

**Review by jcatjmeow — APPROVED** [review]

**Comment by Reed0506** [comment]
ok so basically its still gonna be in strange seeds right? something something skewium bees.

**Comment by boodaliboo** [comment]
> ok so basically its still gonna be in strange seeds right? something something skewium bees.

that is not at all how its going to work if this pr is merged he is removing the chem outright not just removing the recipe

**Comment by LoliconSlayer** [comment]
> > ok so basically its still gonna be in strange seeds right? something something skewium bees.
> 
> that is not at all how its going to work if this pr is merged he is removing the chem outright not just removing the recipe

I'm actually just removing the recipe the fuck are you on

**Comment by LoliconSlayer** [comment]
image
:)

**Pull request merged**
