### PR TITLE
[PORT] Attack animation 

### PR DESCRIPTION
**Pull request by warface1234455**
# About pr
I hate blank animation attack
- ports https://github.com/tgstation/tgstation/pull/52517

# Document the changes in your pull request
Adds an attack animation from tg

sorry moja

https://user-images.githubusercontent.com/89688125/184866595-9db64dd6-8a2d-4ae3-902d-413a07a13f64.mp4

# Wiki Documentation
New attack animation
# Changelog

:cl:  
rscadd: Added attack animation
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Maybe

**Comment by 00ze-cyclone** [comment]
Look like you’re dabbing when punching.
Idk how I feel about that.

**Comment by ghost** [comment]
Cool i always wished to kill my enemies by dabbing

**Comment by SomeguyManperson** [comment]
mf got those pengiuin iears

**Comment by ShoziOffical** [comment]
this is wholesome feature

**Comment by ShoziOffical** [comment]
people disliking probally dont want to get dabbed on while being beaten up

**Comment by JamieD1** [comment]
Looks a bit funky sorry mate

**Comment by ShoziOffical** [comment]
:(

**Comment by ShoziOffical** [comment]
looks fine for me

**Pull request closed without merging**
