### PR TITLE
COGGERS but in ratvarian

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
bugfix: help 
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
coggers more like pbttref

**Comment by SomeguyManperson** [comment]
it's vitally important to translate into ratvarian for immersion and lore

**Comment by jcatjmeow** [comment]
I am very against putting coggers in the game.

But any time I voice this opinion the other guy vomits up some oil and gears and says "coggers" and then my head explodes

**Review by JamieD1 — APPROVED** [review]
Booo

**Pull request merged**
