### PR TITLE
Nar-Sie attracts the singularity

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

Nar-Sie will now more likely die upon a singulo release

### CODE REVIEW

**Comment by Marmio64** [comment]
ynot codes for goonstation?

**Comment by Hopekz** [comment]
@TheGamerdk quick another PR remind them of autodoc!!

**Comment by ynot01** [comment]
i did my autodoc dues

**Review by alexkar598 — DISMISSED** [review]
Fix the title and description

**Comment by ynot01** [comment]
woe is me

**Review by fluffe9911 — APPROVED** [review]
Narsie Thick

**Pull request merged**
