### PR TITLE
FIXES SENTINEL'S COMPROMISE

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
i do not know how this broke, i don't want to know how this didn't work. i shouldn't need to wonder why this didn't work. sentinel's compromise will currently just kill your teammates by inflicting toxin damage on them and not healing them.

# Changelog

:cl:  
bugfix: sentinel's compromise no longer kills your teammates
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Did you test it

**Comment by ShadowDeath6** [comment]
bad change I think that this spell should remain unusably bad

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> Did you test it

yeah

**Comment by redmoogle** [comment]
image

????? how does this actually fix anything

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> image
> 
> ????? how does this actually fix anything

i do not know. do not wonder why, for it fixes everything.

**Pull request closed without merging**
