### PR TITLE
Fixes VTEC and disabler cooler modules

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

bugfix

#### Changelog

:cl:  
bugfix: Fixed VTEC and disabler cooler modules
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
i dont know how to make this work someone help me

**Comment by Ratvar** [comment]
I really would love if features that were innately OP and didn't have speed changes yog went through in mind... weren't readded back, no matter bugfix or no.

**Comment by MegaEmpirical** [comment]
I'd rather it bug fixed rather than left broken.

**Comment by Ratvar** [comment]
I'de rathr bug be fixed by removing/rebalancing features in process.

**Comment by MegaEmpirical** [comment]
I'm not opposed to that but between fixing and not fixing, I'll take fixing.

**Comment by oklews** [comment]
I love you, I’d been waiting for this for ages

**Comment by alexkar598** [comment]
No effort

**Pull request closed without merging**
