### PR TITLE
New Psyc Office YAY

### PR DESCRIPTION
**Pull request by Readystorm546**
I move the psyc office to a new area.

Why did I do this... Well psyc sees little to no action and I though it might be best if it was in a more open are so that more people could have access to it.  It is located where the old gift shop used to be. 

image

In medical where the old psyc office used to be there is now another medical storage closet. This stores rolling beds. Wheelchairs and IV Drips.

image

:cl:  
rscadd: Added more wheelchairs and rolling beds and iv drips in the new storage closet.
rscadd: Moved Psyc office to where old gift shop used to be. Psyc office is now bigger
rscdel: Removed the rolling beds, wheelchairs, and iv drips that were in the hallways of medical. 
rscdel: Removed old shop maintenance area
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Way too much space for an RP role. Can you fit it in something this size?

image

Even with this reduction in size it's nearly 66% bigger than before

**Comment by Readystorm546** [comment]
> Way too much space for an RP role. Can you fit it in something this size?
> 
> image
> 
> Even with this reduction in size it's nearly 66% bigger than before

I present to you 
image

An RP role with a bunch of space

**Comment by ToasterBiome** [comment]
> 

Awesome, you've shown me a guy that runs a store. Can you fit it in something the size that I sent?

**Comment by Readystorm546** [comment]
> > 
> 
> Awesome, you've shown me a guy that runs a store. Can you fit it in something the size that I sent?

No I cant. But There are RP roles with bigger sizes is all I was pointing out.

**Comment by MegaEmpirical** [comment]
What the hell is it with people talking about the size. It was a useless random room before, this is meant to be a usable space and it isn't even that big.

**Comment by ToasterBiome** [comment]
> What the hell is it with people talking about the size. It was a useless random room before, this is meant to be a usable space and it isn't even that big.

I'd rather have a 5x4 psych room and a 5x3 maint room over a 5x8 psych room

**Comment by NCRLouTenant** [comment]
Also calling a random maintenance room useless is silly considering that one especially has a tendency to be a mech workshop, cloning lab, nanite room, or surgery center. That stuff in there is hardly what I would call useless.

I am willing to give the room move a chance though, who knows it might improve that job a little.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
