### PR TITLE
Mad scientist kit buff

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Wow these kits suck

Mad scientist kit now gets:

- A restricted list of moderately useful cluster busters for a syndicate instead of being able to roll things like smoke or cleaner grenades
- EZ Clean grenade box

This sets it to being worth around 20-30 TC depending on your rolls whereas before it was nigh useless always

# Changelog

:cl:  
tweak: Mad scientist special syndie kit buffed with better grenades and a box of EZ Clean grenades
/:cl:

### CODE REVIEW

**Review by patpol4 — COMMENTED** [review]
Are you sure you want to name it /syndie/, wouldnt full /syndicate/ be better since that is what most of other objects use

**Review by patpol4 — APPROVED** [review]
Map fine

**Comment by ynot01** [comment]
> Are you sure you want to name it /syndie/, wouldnt full /syndicate/ be better since that is what most of other objects use

**Comment by patpol4** [comment]
must have been a dream

**Review by MajManatee — APPROVED** [review]
Re-paths all syndicate cluster grenades. Probably wont cause problems in the future. I hope. Would like to see that change documented in the PR.

otherwise it looks fine.

we should really go through every single kit and change them up because my god, a lot of these suck.

**Pull request merged**
