### PR TITLE
Removes roundstart blue alert

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Removes roundstart blue alert and antag report
#### Changelog

:cl:  
rscdel: Removes roundstart blue alert
rscdel: Removes antag report too
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
im pretty sure cap will just blue alert anyways

**Comment by Marmio64** [comment]
also imagine liking your own PR you bastard

**Comment by swissloaf** [comment]
> im pretty sure cap will just blue alert anyways

we can bwoink them cause theres no reasonable cause to

**Comment by aaqe** [comment]
A step in the right direction.

**Comment by Marmio64** [comment]
as soon as one assistant starts toolboxing another caps gonna blue alert instantly

**Comment by swissloaf** [comment]
this will need a council vote

**Comment by ghost** [comment]
if you get a list of possible threats on the station you raise to blue automatically, @swissloaf 

'no reason to'

whaat the fuck do you think blue alert is dumbass, it's 'suspected threat aboard the station', and you get a message from central command literally telling you there's a possible threat. that's the reason. that's why it auto-raises to blue and that's why every captain will immediately just raise it to blue again because of the report

unless you're going to bwoink captains for raising to blue because 'there's no reason to be on the suspected threat alert level' when the antag report is right there from cc telling you there's a suspected threat you're being inconsistent

remove the report too if you want to have a reason to stay on green, it's not like it accomplishes anything but encouraging metagame

**Comment by swissloaf** [comment]
> if you get a list of possible threats on the station you raise to blue automatically, @swissloaf
> 
> 'no reason to'
> 
> whaat the fuck do you think blue alert is dumbass, it's 'suspected threat aboard the station', and you get a message from central command literally telling you there's a possible threat. that's the reason. that's why it auto-raises to blue and that's why every captain will immediately just raise it to blue again because of the report
> 
> unless you're going to bwoink captains for raising to blue because 'there's no reason to be on the suspected threat alert level' when the antag report is right there from cc telling you there's a suspected threat you're being inconsistent
> 
> remove the report too if you want to have a reason to stay on green, it's not like it accomplishes anything but encouraging metagame

good idea

**Comment by overlord12345** [comment]
i like this because bolting secure areas as ai on green alert is agaings the SOP so no more round start bolting of every blue door

**Comment by ghost** [comment]
there now it's good

**Comment by MegaEmpirical** [comment]
https://forums.yogstation.net/index.php?threads/vote-remove-auto-blue-alert-and-the-roundstart-report.18754/

You'll need to fight council first.

**Review by JamieD1 — CHANGES_REQUESTED** [review]
If we are no longer intercepting can we rename the procs?

**Comment by alexkar598** [comment]
Config issue, get out of my codebase

**Pull request closed without merging**
