### PR TITLE
adds a contraband sec hud implant to the uplink (3tc)

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
allows you to purchase a sec hud implant autosurgeon that replaces your eyes for only 3 tc
#### Changelog

:cl:  
rscadd: Adds a new autosurgeon for a unused item and then adds that autosurgeon to uplink
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
I have concerns about being able to modify sec records at almost no risk.

**Comment by ynot01** [comment]
you cant modify sec records without a sec access ID

**Comment by HomocidlePancakes** [comment]
Can you please stop polluting the uplink please? It’s already full of random shit.

**Comment by boodaliboo** [comment]
I’m working on making more categories to not flood things

**Comment by alexkar598** [comment]
Bloat,the headset encryption key does the spying on sec but better. We are starting to have a cargo console class tgui lag with the uplink already

**Pull request closed without merging**
