### PR TITLE
Fixes augmented genders

### PR DESCRIPTION
**Pull request by Moltijoe**
I was initially just removing the genders, but then someone pleaded me to not do it
image
Head mentor ladies and gents

Apparently the female sprites weren't tailored to the female model so there were stray pixels everywhere
Also makes genderless species just default to the male icon so they don't turn invisible

default (also engineering because that one just used default)
regular
mining
mining
security
security

:cl:  Papi, Mqiib
bugfix: Genderless species no longer turn invisible when augmented
bugfix: Female characters no longer have too many pixels when augmented
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
2023-01-16 14_05_08-Untitled  C__Users_Cuackles_Downloads_augments_security dmi  - Dream Maker
2023-01-16 14_05_15-Untitled  C__Users_Cuackles_Downloads_augments_security dmi  - Dream Maker
i have some issues with the female belly where the red part is, this applies to all the other ones too it looks odd in my eyes and i would consider backing up a bit so its on the same line

**Comment by MajManatee** [comment]
Mib is a simple guy, with simple needs

**Comment by Moltijoe** [comment]
>i have some issues with the female belly where the red part is, this applies to all the other ones too it looks odd in my eyes and i would consider backing up a bit so its on the same line

This was me just following the other female bodies i saw

**Comment by cuackles** [comment]
> >i have some issues with the female belly where the red part is, this applies to all the other ones too it looks odd in my eyes and i would consider backing up a bit so its on the same line
> 
> This was me just following the other female bodies i saw

Oh shit really ???, I'm not at my PC at the moment could you post some other side views of different torsos ?, As in the one u used as reference

**Comment by Moltijoe** [comment]
> Oh shit really ???, I'm not at my PC at the moment could you post some other side views of different torsos ?, As in the one u used as reference

Lizard
image
Human
image
Golem (i thought they were genderless)
image

Something of note, pod people, plant people, jelly people, luminescent, stargazers, and probably a few others, despite being gendered don't have differences in the side sprite between genders, but they do for front and back facing sprites.

**Comment by cuackles** [comment]
> > Oh shit really ???, I'm not at my PC at the moment could you post some other side views of different torsos ?, As in the one u used as reference
> 
> Lizard
> image
> Human
> image
> Golem (i thought they were genderless)
> image
> 
> Something of note, pod people, plant people, jelly people, luminescent, stargazers, and probably a few others, despite being gendered don't have differences in the side sprite between genders, but they do for front and back facing sprites.

Oooooh ok ok got it, so, your sprite is in line so it's aproved, on the other side the torsos you mentioned should be given a different side sprite for consistency too,not saying that you should add it on this PR, just making note of it

**Review by cuackles — APPROVED** [review]

**Review by ynot01 — APPROVED** [review]

**Pull request merged**
