### PR TITLE
Icy veins injects mutadone

### PR DESCRIPTION
**Pull request by Sniblet**
# Document the changes in your pull request

Slings have counterplay to powered glowy now. Use reinforced instead, or carry 8 mutators because of course you will.

# Changelog

:cl:  
tweak: Icy veins injects mutadone
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
HAHAHAHAHAHAHAHA

**Comment by Mqiib** [comment]
You could just have it directly remove the glowy gene rather than inject mutadone and fuck over _all_ mutations of anyone nearby.

oh also fuck slings thumbs down

**Comment by Simplehorror** [comment]
someone just lost a sling game

**Comment by Sniblet** [comment]
> You could just have it directly remove the glowy gene rather than inject mutadone and fuck over _all_ mutations of anyone nearby.

I'm not sure how many other mutations people use on slings. Space adapt is always around, sure, but that's also used to cheese icy veins.
Still, I'd have it specially target glowy if I knew how.

**Comment by Simplehorror** [comment]
> > You could just have it directly remove the glowy gene rather than inject mutadone and fuck over _all_ mutations of anyone nearby.
> 
> I'm not sure how many other mutations people use on slings. Space adapt is always around, sure, but that's also used to cheese icy veins. Still, I'd have it specially target glowy if I knew how.

"this ability has counterplay so it's bad"
perhaps glare the man with space adapt?
perhaps get a syringegun with mutadone?
perhaps have a thrall do any of the above?

this is a TEAM GAMEMODE you are not solo, you are the most escapable antag in the game, if you cant fight, RUN

**Comment by Sniblet** [comment]
Space adapt isn't really an issue.
Slings can't use guns.
Thralls can't get a reliable supply from medbay without being dogpiled, because it's medbay and at least genetics isn't converted.
You can't run when everyone has powered glowy.

**Comment by Simplehorror** [comment]
sir have you heard of our lord and savior blindness smoke (which blocks light long enough for you to thrall a glowy?)

**Comment by Sniblet** [comment]
Cool. This way's less cheesy and makes mindshielded glowy people not invincible.

**Comment by Simplehorror** [comment]
Wait until you learn you can counter deswords with a stunbaton too. They're very much not invincible, slings have many many ways to deal with "mindshielded glowy people" (1% of the station)

**Comment by RG4ORDR** [comment]
There's about 5000 ways to counter slings.
Slings have absolutely 0 counter play against glowy, no matter what argument is put forth a single person with glowy will be able to 1v1 slings. Thralls are not a counter to this. Players are often allowed to validhunt slings and thralls too.
This is a great change because it means that glowy users cannot cuck slings, and it means mass glowy production can be countered effectively.

**Comment by Burger1998** [comment]
> There's about 5000 ways to counter slings. Slings have absolutely 0 counter play against glowy, no matter what argument is put forth a single person with glowy will be able to 1v1 slings. Thralls are not a counter to this. Players are often allowed to validhunt slings and thralls too. This is a great change because it means that glowy users cannot cuck slings, and it means mass glowy production can be countered effectively.

are slings even meant to be able to fight prepared attackers? aren't they supposed to like jaunt and fuck off and get the glowy user dogpiled by their thralls

**Comment by ReddicusDragon** [comment]
powercreep

**Comment by Marmio64** [comment]
Would make more sense for it to be veil, and if it only took off glowy and not all mutations.

**Comment by RG4ORDR** [comment]
> > There's about 5000 ways to counter slings. Slings have absolutely 0 counter play against glowy, no matter what argument is put forth a single person with glowy will be able to 1v1 slings. Thralls are not a counter to this. Players are often allowed to validhunt slings and thralls too. This is a great change because it means that glowy users cannot cuck slings, and it means mass glowy production can be countered effectively.
> 
> are slings even meant to be able to fight prepared attackers? aren't they supposed to like jaunt and fuck off and get the glowy user dogpiled by their thralls

Slings are fully capable of fighting groups of attackers, however the presence of glowy can legitimately make that entirely impossible as it's an irremovable light-source. It's routinely handed out like candy, it's often very easy to spam it with powered chromosomes, and it blocks certain sling abilities and base sling movement.  Likewise, you can 1 shot a sling by hitting it with a incend shotgun round.

**Comment by Sniblet** [comment]
Recall that people other than geneticists can be given powered glowy
Recall that unlocking powered glowy takes 20 minutes at most, if RNG hates the geneticist, and that at that point the slings are just getting started, and the very best slings have maybe 3 thralls
Keep in mind that someone with glowy in any form cannot be enthralled if the shadowling doesn't have access to mutadone, which requires access to medbay, which is where the glowy is coming from

I don't know what you people are thinking when you say "just use your thralls" - what I'm saying is what thralls? Everyone with a high enough IQ to understand what do mutadone mean was smart enough to get glowy, wyd

If someone else knows how to make veil remove specifically glowy, go right ahead, I'll close this. Glowy is not fine as-is.

**Pull request closed without merging**
