### PR TITLE
Removes the rock paper scissors "joke"

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
it was probably an april fools only thing, but it's overstayed it's welcome

:cl:  
rscdel: Removes the rock paper scissors "joke"
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
remove the proc too tf

**Comment by Moltijoe** [comment]
> remove the proc too tf

apparently bibby specifically wants it

**Comment by Bibby0110** [comment]
Will fix later

**Comment by Moltijoe** [comment]
24 hours

**Comment by AMyriad** [comment]
this is retarded
it doesn't matter if this will do something or does nothing, polling 3 random players at the start of every single round is incredibly annoying and confusing to people who don't know what it's about (everyone)

**Pull request closed without merging**
