### PR TITLE
Ports Gangs ... Again!

### PR DESCRIPTION
**Pull request by fluffe9911**
Gangs Baby someone had to do it

Known Issues:
Poser Tags Dont Work (bit confused on this one to be honest)

### CODE REVIEW

**Comment by Smudged** [comment]
I hope this is yogs gangs and not hippy gang

**Comment by fluffe9911** [comment]
uhhhhhhhhh *hides hippie code under rug* yep one hundred percent yogs gangs no bamboozle guarantee!

**Comment by jcatjmeow** [comment]
Gangs sucks I rate this a downvote/10

**Comment by Smudged** [comment]
Dang it Fluffe, We HAD A testing of hippie gang, and it suuucked

**Pull request closed without merging**
