### PR TITLE
rebalances collars for catpeople

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

You can now instantly grab anyone with a collar on, meaning anyone wearing a collar is severely disadvantaged in combat :) how's this for fetish content?

#### Changelog

:cl:  
fix: catpeople are now gonna lose combat if they wear collars
/:cl:

### CODE REVIEW

**Comment by Ktlwjec** [comment]
can you remove the question from your pr desc please this is a non-erotic server

**Comment by thehighwayman** [comment]
One time a speed merge would be in order

**Comment by Nickvr628** [comment]
OwO UwU Owu

**Comment by Alexandria404** [comment]
That was my idea.

**Pull request merged**
