### PR TITLE
I run the codebase through a neural network and see if it passes Turdis

### PR DESCRIPTION
**Pull request by Hopekz**
Let's see what it did

#### Changelog

:cl:  Hopek
experimental: Oh boy
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
what the fuck is that

**Comment by SomeguyManperson** [comment]
MY GOD FREEMAN WHAT HAVE YOU DONE

**Comment by Jumps0** [comment]
speedmerge

**Comment by deathslayer2481** [comment]
MY GOD FREEMAN, YOU JUST KILLED A MAN!

**Comment by Hopekz** [comment]
What if it works if I only remove the changelog changes

**Comment by ynot01** [comment]
it passed compile and run tests

**Comment by Hopekz** [comment]
Now we wonder what code it added because it compiles and runs fine on a local test server
image

**Comment by deathslayer2481** [comment]
I'm scared...

**Comment by Hopekz** [comment]
Alright, I got what I needed from this test.
Needs more .js file training data because it messed up most of the .js files according to Lints test

**Pull request closed without merging**
