### PR TITLE
Attmpts to remove Rotciv from the wizard academy again

### PR DESCRIPTION
**Pull request by LoliconSlayer**
Kicking this fucking hornet's nest again
Pretty much the exact same as #9564 because Jamie closed the PR without saying anything :)

:cl:  
rscdel: Rotciv the Dented has been expelled from the Wizard Academy and was asked to leave his wizard hat!
rscadd: Colton the Afterburner has transferred into the Wizard Academy!
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Let's just finally remove the whole ruin

**Comment by LoliconSlayer** [comment]
That was already attempted in #9549

**Review by jcatjmeow — APPROVED** [review]

**Comment by swissloaf** [comment]
Just remove all player references anyway they shouldn’t be venerate like Trey

**Comment by Hopekz** [comment]
> Just remove all player references anyway they shouldn’t be venerate like Trey

That was attempted in #9547

**Review by patpol4 — APPROVED** [review]
Remove all the other people you don't like while you're at it

**Pull request merged**
