### PR TITLE
Fake Nuke disk is now set to mythical to prevent free illegal tech

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
No more free illegal tech, now its very rare.

# Changelog
:cl:  
tweak: fake nuclear disk is now mythical rarity
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
> cringe

no i cant get my epic powergamer security loot for free without doing anything roundstart!!!
(you still can its just rarer)

**Comment by VomitPukeLover123** [comment]
👍

**Comment by Therandomhoboo** [comment]
Lets make it that only traitors can make illegal tech so we know who is the bad guys

**Comment by azzzertyy** [comment]
> Lets make it that only traitors can make illegal tech so we know who is the bad guys

agreed

**Comment by Addust** [comment]
maybe
hear me out here
a fake, plastic replica of a nuclear authentication disk
does not need to be illegal tech compatible in the first place

_also syndicate lavaland gets one that maybe teleports itself to station (unsure) and i refuse to change that_

**Comment by azzzertyy** [comment]
> maybe hear me out here a fake, plastic replica of a nuclear authentication disk does not need to be illegal tech compatible in the first place
> 
> _also syndicate lavaland gets one that maybe teleports itself to station (unsure) and i refuse to change that_

hugbox

**Review by ynot01 — APPROVED** [review]
Way too common in current state

**Pull request merged**
