### PR TITLE
Readds old space ruins from old yogs!

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 fluffe9911 for porting matskuman5 for making the hippie van Yewmi for yogsifying the academy
add: 3 new/old space ruins the space bar, academy and hippie van have returned!
/🆑

 decided to readd some old yogs space ruins only differences is with the Academy which no longer has a wizard spawner cause thats stupid  also no idea who made the space bar cant seem to find any info on it please let me know if you figure it out

### CODE REVIEW

**Comment by fluffe9911** [comment]
ignore travis its being the big mean

**Comment by Amelia0010** [comment]
Fix travis.

**Comment by fluffe9911** [comment]
mk

**Comment by alao3alao3** [comment]
What happened to the hippie van?

**Pull request merged**
