### PR TITLE
Remove spaceproof from HECK Suit

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Miners do not need a "kill malf AI" suit. They should get spaceproof suits like everyone else, especially when mining has ZERO benefit to having a spaceproof suit. Go get an EVA suit, or use xenobio stuff like everyone else

# Wiki Documentation

HECK Suit is no longer spaceproof
# Changelog

:cl:  
tweak: Removed spaceproof from HECK Suit
/:cl:

### CODE REVIEW

**Comment by UltraBigRat** [comment]
they already have hardsuits for space exploration, nothing wrong with the heck suit having it  especially considering they killed a pretty darn tough megafauna for it.

**Comment by Simplehorror** [comment]
> they already have hardsuits for space exploration, nothing wrong with the heck suit having it especially considering they killed a pretty darn tough megafauna for it.

literally every megafauna is cannon fodder because they're down to patterns in the end, and if you know them you know them.
they don't need this unless they're validhunting, where they shouldn't

**Comment by ShoziOffical** [comment]
> > they already have hardsuits for space exploration, nothing wrong with the heck suit having it especially considering they killed a pretty darn tough megafauna for it.
> 
> literally every megafauna is cannon fodder because they're down to patterns in the end, and if you know them you know them. they don't need this unless they're validhunting, where they shouldn't

Cool idea, let's prevent miner from validhunting by removing pressure proof from hecksuit.

**Comment by CMOisLing** [comment]
Another gem thank you Mr simplehorror

**Comment by MajManatee** [comment]
let me know when you can consistently beat BG and get the heck suit, then ill consider considering this

**Comment by Simplehorror** [comment]
> let me know when you can consistently beat BG and get the heck suit, then ill consider considering this

i clear lavaland easily, it isn't difficult

**Comment by The-Sun-In-Splendour** [comment]
HECK suit was never meant to be space proof

**Comment by Sniblet** [comment]
Miners have no reason to be spaceproof within the confines of their job.
If they need to be spaceproof anyway, they can buy as many mining hardsuits as they want. Maybe they shouldn't be spaceproof and _also_ have more better armor than a riot suit and a regular armor vest combined, to go with their ranged weapon that does more damage than an energy sword using a damage type that most armor (except their own) doesn't cover well.

Bubblegum is strong, but like horror said in an actually good take for once, if you know him you know him. Most players can't beat him. Those who can, can beat him every time, and then it's another one of those rounds where no antag is safe in space, and admins just kind of watch the miner man go and don't ask questions.

Also, "A suit designed to withstand the wide variety of hazards _from Lavaland._" Lol. Lmao.

**Comment by Simplehorror** [comment]
> Bubblegum is strong, but like horror said in an actually good take for once, if you know him you know him. Most players can't beat him. Those who can, can beat him every time, and then it's another one of those rounds where no antag is safe in space, and admins just kind of watch the miner man go and don't ask questions.

exactly what I mean, thank you. once you beat him once, you beat him forever. and if hierophant trophy crusher cheese is still a thing...

**Comment by ReddicusDragon** [comment]
> Miners have no reason to be spaceproof within the confines of their job. If they need to be spaceproof anyway, they can buy as many mining hardsuits as they want. Maybe they shouldn't be spaceproof and _also_ have more better armor than a riot suit and a regular armor vest combined, to go with their ranged weapon that does more damage than an energy sword using a damage type that most armor (except their own) doesn't cover well.
> 
> Bubblegum is strong, but like horror said in an actually good take for once, if you know him you know him. Most players can't beat him. Those who can, can beat him every time, and then it's another one of those rounds where no antag is safe in space, and admins just kind of watch the miner man go and don't ask questions.
> 
> Also, "A suit designed to withstand the wide variety of hazards _from Lavaland._" Lol. Lmao.

I concur with Sniblet, I think this one might actually be a good change

**Comment by Marmio64** [comment]
i cant downplay miners for being able to kill bubblegum since ive yet to do it (only got hierophant and ashdrake), but also there is a point where you need to cap loot off. The suit having spaceproof serves no purpose in their job at all. I'm really not sure why they even have normal mining hardsuits in their vendors still either, let alone the souped up validhunt armor they get for not doing their job (which is to mine, not kill megafauna. Killing megafauna is just a fun sidequest to level up, which is a hot take but technically the truth).

**Comment by neeshacark** [comment]
This is such a minor nerf to where all it accomplishes is some annoyance.  The armor nerf while on station PR does what this PR is trying to do but actually does it.

Oh no my spaceproof is gone? Time to inject one of my 5 morbillion survival pens and ignore space

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
