### PR TITLE
Moves Yellow gloves from Map to Engineer Loadouts

### PR DESCRIPTION
**Pull request by JamieD1**
Moves Yellow gloves from Map to Engineer Loadouts

:cl:  
tweak: Moves Yellow gloves from Map to Engineer Loadouts
/:cl:

### CODE REVIEW

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Doesn't actually do what it claims to do

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Missing maps, also there needs to be some out for engineers that get job transfered.

**Comment by Moltijoe** [comment]
> Missing maps, also there needs to be some out for engineers that get job transfered.

there are some in one of the vending machines iirc, since roundstarts will spawn with them, these vending machine ones will be left for transfers

**Comment by JamieD1** [comment]
forgot to push. nice.

**Comment by neeshacark** [comment]
All this will do is make assistants break into engineering and steal their vendor so they can get the gloves from that.

**Comment by Maia-J** [comment]
> there are some in one of the vending machines iirc, since roundstarts will spawn with them, these vending machine ones will be left for transfers

Those have only 1 pair if I am correct

**Comment by ReddicusDragon** [comment]
> > there are some in one of the vending machines iirc, since roundstarts will spawn with them, these vending machine ones will be left for transfers
> 
> Those have only 1 pair if I am correct

I shall look into this

**Comment by ReddicusDragon** [comment]
> > there are some in one of the vending machines iirc, since roundstarts will spawn with them, these vending machine ones will be left for transfers
> 
> Those have only 1 pair if I am correct

The vending machine has 4 pairs of insuls, and the secure lockers to my knowledge provide 2 so jamie didn't even fully remove them from the maps.

**Comment by ReddicusDragon** [comment]
> Missing maps, also there needs to be some out for engineers that get job transfered.

see my previous comment

**Comment by patpol4** [comment]
This just causes assistants to raid the vending machine

**Comment by ReddicusDragon** [comment]
> This just causes assistants to raid the vending machine

we just id lock the vending machine

**Comment by SapphicOverload** [comment]
what if there are no engineers (or no competent engineers) and atmos techs have to do their job for them? (this happens often)

**Comment by iamthesilly** [comment]
having the gloves in the vending machine instead of the map makes it so you can't get them if there isn't any power, and fixing said power usually requires insulated gloves which you can't get without fixing the power first, which you can't fix because you don't have insuls, which you can't get because there's no power, and so on

**Comment by Moltijoe** [comment]
> having the gloves in the vending machine instead of the map makes it so you can't get them if there isn't any power, and fixing said power usually requires insulated gloves which you can't get without fixing the power first, which you can't fix because you don't have insuls, which you can't get because there's no power, and so on

the ones in the map were usually immediately snatched up round start by the engineers or any assistants that are feeling particularly gray. This ensures the gloves go specifically to engineers, and any late join engineers won't need to worry about searching for far too long to find a pair. This change would reduce the situations where one is without gloves but needs to fix the power, as it would only be either engineers that lost their pair, or someone from another job.

**Comment by JamieD1** [comment]
Aint stale

**Comment by ReddicusDragon** [comment]
> Aint stale

stale until you finish updating the maps

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
stale, other maps

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
actually thinking about this more, leave some on the table (1-2)

also you don't even remove it from the problematic location, please fix.

also other maps.

**Comment by ThatLing** [comment]
@JamieD1 Inadequate reasoning, please add it to your original post or I will close this

**Comment by ReddicusDragon** [comment]
2 weeks without an update or reply to the requested changes. Closed.

**Comment by JamieD1** [comment]
> 2 weeks without an update or reply to the requested changes. Closed.

Been busy with preferences.

**Comment by Moltijoe** [comment]
un-draft it when it's ready then

**Comment by ThatLing** [comment]
> > 2 weeks without an update or reply to the requested changes. Closed.
> 
> Been busy with preferences.

Re-open when that fuck is merged

**Comment by JamieD1** [comment]
Shoo

**Comment by ThatLing** [comment]
@JamieD1 Then fix it!

**Comment by MajManatee** [comment]
By every definition of our rules, this PR should be closed long ago

**Comment by patpol4** [comment]
blueshield status

**Comment by patpol4** [comment]
image

**Pull request closed without merging**
