### PR TITLE
Makes the majority of mild/severe brain traumas silent

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Brain traumas are now silent besides; Special Traumas, Phobias, Blindness, and Paralysis

Stops the ability to Metagame your brain damage

Edit _forgot to mention why_

#### Changelog

:cl:  
tweak: The majority of brain traumas are now silent
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
Like you don't get the "you feel dumber" or whatever text?

**Comment by redmoogle** [comment]
> 
> 
> Like you don't get the "you feel dumber" or whatever text?

Yes, the ones that have flavor message like "you feel light headed" are still in

**Comment by Xoxeyos** [comment]
Hell yeah.

**Comment by alexkar598** [comment]
Why? anyone with half a braincell will know why their words are being reordered. This just impacts UX for new players without anything it fixes

**Comment by redmoogle** [comment]
> Why? anyone with half a braincell will know why their words are being reordered. This just impacts UX for new players without anything it fixes

There are other traumas with delayed effects, makes gameplay slightly more interesting rather than.
 Oop saw funny text medbay time!1!!1

**Comment by alexkar598** [comment]
Then make those silent. User experience is an important thing in a game, if things happen to you and you dont know why, you're going to have a bad time.

**Comment by redmoogle** [comment]
> 
> 
> Then make those silent. User experience is an important thing in a game, if things happen to you and you dont know why, you're going to have a bad time.

Because now that can be used as a justification to add the rest, you should be at bare minimum be learning you have a brain trauma from whats happening, not because you were somehow aware enough to know exactly which trauma you have from text on the screen

**Comment by Reed0506** [comment]
hmm yes i sure do feel my mind being split in half yep sure do

**Comment by jcatjmeow** [comment]
The issue is right, spontaneous brain trauma is an event, and people will literally out of the blue have no idea why they suddenly are handicapped

**Comment by redmoogle** [comment]
> 
> 
> The issue is right, spontaneous brain trauma is an event, and people will literally out of the blue have no idea why they suddenly are handicapped

to me it just seems weird to tell a person they have brain trauma, then they just head off to medbay pretty much universally.

**Review by Amelia0010 — APPROVED** [review]
Code is fine, @yogstation13/maintainers I'm split on this, please someone either merge or close it

**Pull request merged**
