### PR TITLE
Reworks ranged alien neurotoxin into a melee ability

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Document the changes in your pull request

Adds a new reagent: Alien Neurotoxin, a tweaked version of the actual drink called Neurotoxin. Causes stamina loss, loss of limbs, and item drop.
Xenos can no longer spit neurotoxin.
Xenos now have a new ability called "Neurotoxin Bite" which injects Alien Neurotoxin into a nearby target for 80 plasma cost. Functions similar to warden CQC where you activate the ability then click on a target.

# Spriting

Neurotoxin bite icon:
image

# Wiki Documentation

https://wiki.yogstation.net/wiki/Xenos

# Changelog

:cl:  
rscdel: Removes ranged neurotoxin ability from Xenos.
rscadd: Adds a new neurotoxin bite ability to Xenos that injects Neurotoxin into a nearby living being.

/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]
ayo thats a really good sprite, sprite more

**Comment by BurgerLUA** [comment]
> ayo thats a really good sprite, sprite more

I stole it from the existing sprite lmao

image

**Comment by cuackles** [comment]
> > ayo thats a really good sprite, sprite more
> 
> I stole it from the existing sprite lmao
> 
> image

i have never been so disapointed in my entire life, you gave me hope, i gave you my aproval and you spit on my face and disrespect me, your art aproval will be removed and you shall be executed, stinky

**Comment by cuackles** [comment]
> > > ayo thats a really good sprite, sprite more
> > 
> > 
> > I stole it from the existing sprite lmao
> > image
> 
> i have never been so disapointed in my entire life, you gave me hope, i gave you my aproval and you spit on my face and disrespect me, your art aproval will be removed and you shall be executed, stinky

sprite more or suffer the consequences

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
At least try to keep the lore from the original source, just make it a tackle or something

**Comment by BurgerLUA** [comment]
> At least try to keep the lore from the original source, just make it a tackle or something

god damn it I spent like 2 hours on this, there is nothing wrong with having a neurotoxin bite even if the original aliens movie didn't have it

gameplay > lore

**Comment by MajManatee** [comment]
We already have a tackle

**Comment by tattax** [comment]
i'd say neurotoxin is very necessary in space fights where you'd want to be the most as a xeno since mechs exist + allows space maneuver as queen so you don't get spaced for a minor technical hiccup and doesn't make riot helmets the mega hardcounter to xenos

this is redundant as tackle and pounce do the same thing but better (instant) and cost nothing. Besides this would only be used if someone has stun immunity, which is a rare case and still not as useful as punching them (0 plasma cost)

**Comment by BurgerLUA** [comment]
I forgot to write the blurb why this is good for the game.

Ranged Neurotoxin is pretty OP since it's an instant ranged stun. Tasers were removed for this reason and it makes sense to now remove it and replace it with something else. I rather not make a PR that just removes neurotoxin, as that would make the neurotoxin gland completely useless.

The something else being replaced is an ability that injects a Neurotoxin at melee range that lasts a bit. The neurotoxin can be used in the middle of combat if shoves/tackles cannot be used effectively, or as a supplement to be used by a skilled player to keep someone who was shoved down.

**Comment by Moltijoe** [comment]
This seems like a bit of an over nerf, 
Just making the old ranged attack inject the new chemical instead of stunning seems better
This is just my personal opinion though, probably wait on balance council to decide

**Comment by Moltijoe** [comment]
https://github.com/yogstation13/Yogstation/pull/18552

has been approved instead

**Comment by githubuser4141** [comment]
Since xenos in the original film didn't have any ranged attack whatsoever surely the rem

> At least try to keep the lore from the original source, just make it a tackle or something

The original source didn't have ranged spits for the xenos at all, this replaces their ranged attack with an attack that injects poison when melee'd, which isn't shown in the film but seems a lot more natural--- since it's slow-acting one could say it's the alien's bacteria or something, I'm not sure anyone in the original film actually lived long enough to prove this wrong anyway? IIRC there wasn't 1 scene where a person was 'bitten' by a xeno, then survived to tell everyone of the experience

**Comment by BurgerLUA** [comment]
balance council strikes again

**Comment by BurgerLUA** [comment]
if the balance council is balanced how come they denied 2 out of 2 of my prs instead of 1 out of 2 of my prs

**Pull request closed without merging**
