### PR TITLE
Conveyor code clean up + New sprite

### PR DESCRIPTION
**Pull request by warface1234455**
- partially port https://github.com/tgstation/tgstation/pull/63240
- Sprite is from https://github.com/discordia-space/CEV-Eris/pull/3893

# Document the changes in your pull request
Added tooltip for conveyor upon examinating
Removed some useless procs and codes
Added new sprite for conveyor, better visual of direction it is moving to

# Spriting
gif
image

# Wiki Documentation

Added tooltip for conveyor upon examinating
Removed some useless procs and codes
Added new sprite for conveyor, better visual of direction it is moving to

# Changelog

:cl:  warface1234455(port man), WalterJe(sprite),  GoldenAlpharex(code)
rscadd: Added tooltip for conveyor upon examinating  
rscdel: Removed some useless procs and codes  
imageadd: Added new sprite for conveyor, better visual of direction it is moving to  
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
sprite looks weird

**Comment by ShoziOffical** [comment]
> sprite looks weird

you are weird

**Comment by KillerOrcaCora** [comment]
Fight fight fight fi- ahem…cut it out you 2

**Comment by Simplehorror** [comment]
image
arrows are all fucking lumpy

**Comment by ShoziOffical** [comment]
> image arrows are all fucking lumpy

~~that doesn't affect much, unless you want to stare at that tiny pixel of arrow on your screen entire round~~

thats vs code problem processing the sprite, it always does that but the sprite is still fine

**Comment by Simplehorror** [comment]
@KillerOrcaCora

**Comment by cuackles** [comment]
I like the lever but the belt does look a bit Bland

**Comment by ShoziOffical** [comment]
> @KillerOrcaCora

Ph wait, it's just vscode problem processing the sprite, the sprite is still fine, i just checked it

**Comment by ShoziOffical** [comment]
image
all sprites are fine

**Comment by ShoziOffical** [comment]
> I like the lever but the belt does look a bit Bland

well, least it looks better than the old one

**Comment by applepineapplepizza** [comment]
i like theses sprites because i can tell which direction it goes

**Comment by Potototatoh** [comment]
only thing i see going for the conveyor sprite is the bottom half/the fact you can tell what direction its going; otherwise its L conveyor segment translates sort of roughly, and the top is a bit too plain/clean (the places you often see these are going to be cargo or _disposals_)

**Review by KillerOrcaCora — APPROVED** [review]
The people have voted, these will be our new conveyors.

**Pull request merged**
