### PR TITLE
Ports desk bells and ashtrays

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Ports desk bells and ashtrays from vg/bay. Desk bells are craftable with metal and roundstart ones announce a message over the department comms when rung, though this has a cooldown and only works if it is in the area it starts in. Uses a mix of code from the following PRs and some more taken from bay, though I can't find the PR:
https://github.com/vgstation-coders/vgstation13/pull/2044
https://github.com/Baystation12/Baystation12/pull/31526

# Spriting
image

# Wiki Documentation

Add desk bells and buttons to the metal/plastic crafting list. 

# Changelog

:cl:  comma, DeityLink, Spookerton, nmajask
rscadd: Added desk bells and ashtrays
/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]

**Comment by Cartlord** [comment]
Can these desk bells also be made & hooked up with assemblies, such as signallers & speakers?

**Comment by AlvCyktor** [comment]
last chance to look at me hector.... 🛎💥 🛎💥🛎💥🛎💥🛎💥🛎💥

**Comment by nmajask** [comment]
> Can these desk bells also be made & hooked up with assemblies, such as signallers & speakers?

They can be crafted with 1 metal/plastic sheet, and they can have devices like signalers inserted into them which is how the department announcement works.

**Comment by ToasterBiome** [comment]
cute time to break the game

**Review by ToasterBiome — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
