### PR TITLE
Ports Runescape Chat bubbles from TG-station

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
Ports
https://github.com/tgstation/tgstation/pull/50608/files

image
image
image

#### Changelog

:cl:  TheGamerdk for porting, bobbahbrown for code
rscadd: Ported Runescape Chat bubbles
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
This cannot be ported before we find a way to use MeasureText in 512, or update to 513

EDIT:
Works on 512

**Comment by Kmc2000** [comment]
> This cannot be ported before we find a way to use MeasureText in 512, or update to 513

You're still on 512..?

**Comment by Bibby0110** [comment]
> > This cannot be ported before we find a way to use MeasureText in 512, or update to 513
> 
> You're still on 512..?

Yes, I am also very disappointed and confused

**Comment by JamieD1** [comment]
513 When

**Comment by alexkar598** [comment]
Moving to 513 requires work we haven't done yet

**Comment by Bibby0110** [comment]
> Moving to 513 requires work we haven't done yet

This is 512 compatible

**Comment by BOBsHERE** [comment]
Ahh this is the best pr ever.

**Review by monster860 — CHANGES_REQUESTED** [review]
Make sure it shows up above the blindness overlay (the plane has to be above). After all you can still hear things when you're blind. Same with lighting, it should show up above that as well.

**Comment by MenacingManatee** [comment]
> Make sure it shows up above the blindness overlay (the plane has to be above). After all you can still hear things when you're blind. Same with lighting, it should show up above that as well.

If it shows above the blindness overlay, couldn't that cheese blindness a bit by showing the location of the speaker? Since the words appear directly above them

**Comment by monster860** [comment]
Speaking should reveal your location to anyone who's blind but capable of hearing though.

**Comment by MenacingManatee** [comment]
> Speaking should reveal your location to anyone who's blind but capable of hearing though.

Valid point, makes sense

**Comment by Darkstick** [comment]
What dictates which color someone's text is?

**Comment by Bibby0110** [comment]
> What dictates which color someone's text is?

Each person gets a random color, so you can see who is who

**Comment by Darkstick** [comment]
> > What dictates which color someone's text is?
> 
> Each person gets a random color, so you can see who is who

Are the colors static, or do they change each round?
Could you change it in the preference menu?

**Comment by Bibby0110** [comment]
> > > What dictates which color someone's text is?
> > 
> > 
> > Each person gets a random color, so you can see who is who
> 
> Are the colors static, or do they change each round?
> Could you change it in the preference menu?

They're random for each round.
I would like to keep it that way, so we don't get overlap on all the "nice" and "liked" colors
A bunch of people would pick their favorite color etc

**Review by Bibby0110 — COMMENTED** [review]
click button go BRRR

**Comment by yacabo** [comment]
I actually like the idea of being able to choose your color, it'd be like picking what your character sounds like

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Update your branch

**Comment by Bibby0110** [comment]
Darkness changes have been removed as they didn't work anyways

**Pull request merged**
