### PR TITLE
Belts can now be worn while naked

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Remove this text and explain what the purpose of your PR is.

Why is a jumpsuit needed to wear a belt?

# Changelog

:cl:  
rscadd: Buffed belt mains, jumpsuit no longer required 
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Hopekz** [comment]
Doesn't this also make it so you can attach non-belt items to your naked body?
You're hyper-focusing on belts when there are lots of non-belt items that can go in that slot

**Comment by adamsong** [comment]
> You're hyper-focusing on belts when there are lots of non-belt items that can go in that slot

Like what?

**Comment by Hopekz** [comment]
> Like what?

Just to name a few things off the top of my head:
KA for miners, tools for engineers, weapons etc.

With this PR they just kind of "magnetically" attach to your naked body. 
Would be better to just make an exception for belts vs allowing all items to bypass this by deleting that check

**Comment by Anvilman6** [comment]
Good concept, but a potentially questionable way to execute it

**Comment by ToasterBiome** [comment]
no loops, cant wear a belt bro

**Comment by JamieD1** [comment]
No loops, belt will literally fall down your arse unless you tighten it above your hips.

**Comment by Hopekz** [comment]
> no loops, cant wear a belt bro

> No loops, belt will literally fall down your arse unless you tighten it above your hips.

Loopless belts are a thing + ss13 is based in the future

https://groovelife.com/products/groove-belt-black-black?variant=32118085386307&gclid=Cj0KCQjwl7qSBhD-ARIsACvV1X0Z1VHD_m_Q3L6o7gPlvcWgj1hQ4lLWJvtLhkgoEKGASO5mEjdRSrwaAsvsEALw_wcB

**Comment by Sniblet** [comment]
1girl naked_belt -rating:s

**Comment by Moja10** [comment]
Moja buff

**Comment by JamieD1** [comment]
If there is ANY weight on the belt it will be very uncomfortable.

**Comment by Hopekz** [comment]
> If there is ANY weight on the belt it will be very uncomfortable.

If we cared about mood I'd say to force a mood debuff

**Comment by JamieD1** [comment]
Nah, sorry. Its more then just a convenience thing, it impacts a lot of things including combat.

**Pull request closed without merging**
