### PR TITLE
[bugfix] Fixes flesh heretic grasp bouncing off everything (including humans)

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Makes it so that the Flesh heretic grasp works properly like the other grasps (doesn't work on tiles/walls ((except rust)) but works on humans ((and dead ones)) )

# Testing

tested it live on discord dot com slash yogstation public

# Changelog

:cl:  

bugfix: fixed flesh grasp no worky 

/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
I gotta figure out why that happens, might be because of the same reason signal handler wasnt working nicely.
Since itd be nice if the other returns were there, so itd only get used if the corpse actually gets turned into a ghoul

**Comment by cowbot92** [comment]
> I gotta figure out why that happens, might be because of the same reason signal handler wasnt working nicely. Since itd be nice if the other returns were there, so itd only get used if the corpse actually gets turned into a ghoul

if you end up making a better fix than this just ping me on discord and ill close this

**Comment by cowbot92** [comment]
Accidentally already fixed with https://github.com/yogstation13/Yogstation/pull/20684 god im good

**Comment by Moltijoe** [comment]
bro, close this then

**Pull request closed without merging**
