### PR TITLE
Renames Yogstation to YogsBox

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Renames Yogstation to YogsBox in, hopefully, the map vote and internally, as that is what everyone refers to it as and naming it after the server probably isn't the best idea. Will probably cause merge conflicts, but it shouldn't be hard to fix. Untested, should work.

# Wiki Documentation

If Box is referred to as Yogstation, it should be changed to YogsBox. 

# Changelog

:cl:  
tweak: Yogstation has been renamed to YogsBox
/:cl:

### CODE REVIEW

**Comment by nmajask** [comment]
Oh, I forgot to not commit the tail whitespace changes

**Review by patpol4 — APPROVED** [review]
This is most likely fine

**Comment by alexkar598** [comment]
Cornflakes

**Comment by nmajask** [comment]
> Cornflakes

Sorted

**Review by adamsong — CHANGES_REQUESTED** [review]
Revert your changes to tails.dm

**Comment by Hopekz** [comment]
Literally no point in doing this and people playing here for years know this map as yogstation

**Comment by UselessTheremin** [comment]
> Literally no point in doing this and people playing here for years know this map as yogstation

what about new players

**Comment by Hopekz** [comment]
> what about new players

What do you think this PR does for new players?

All this PR is doing is changing the name of a map, something that will only effect people that know what this map is called.

**Comment by patpol4** [comment]
Makes the word boxstation less synonymous with the word yogstation, good change just for that.

**Comment by Hopekz** [comment]
> Makes the word boxstation less synonymous with the word yogstation, good change just for that.


Oh this is one of those yogdev moments.
Didn't realize this was an anti-box PR until you said that and when you take away the anti-box energy this PR is just a seemingly pointless name change. 

Not even sure what the vision is here anymore but if renaming a map gets you closer to it I guess it should be done?

Are any other maps being renamed to the yogs[name] syntax or is this just going to apply to box because of the recent drama? Like YogsKilo

**Comment by JamieD1** [comment]
Missed a trick calling it YogBox. But also this feels extremely pointless. People know its box already. I dont know to be honest.

**Comment by Cartlord** [comment]
Actually, when I got here it was days - might've been weeks - before I realized it was just your name for BoxStation. Good change.

**Comment by adamsong** [comment]
In common usage the map is referred to as box, so why isn't the official name that?

And how is this an anti-box pr? It just clears up some ambiguity surrounding the term "yogstation"

**Pull request closed without merging**
