### PR TITLE
Sandbox Mode

### PR DESCRIPTION
**Pull request by swissloaf**
##Intent of your Pull Request
This re-adds the sandbox gamemode

Changelog
🆑
rscadd: Adds the sandbox gamemode
/🆑

### CODE REVIEW

**Comment by swissloaf** [comment]
> github-actions bot added the Config label 2 minutes ago

are you sure about that

**Comment by alexkar598** [comment]
why

**Comment by swissloaf** [comment]
> why

possible fun on lowpop rounds, maybe building or something. just for fun, not a serious rotation gamemode

**Comment by boodaliboo** [comment]
nich is seething

**Comment by alexkar598** [comment]
Yeah I dont want yet another mode to maintain.

**Pull request closed without merging**
