### PR TITLE
Lavaland not up to OSHA standards, increase in mining medic pay

### PR DESCRIPTION
**Pull request by Moltijoe**
You're telling me there's lava and chasms everywhere, skyscraper tall murder animals walking around, and everything within a five mile radius wants you dead, and you only get paid as much as a regular doctor?

They also often need to buy their own synthflesh spray if their first one gets used.

:cl:  
tweak: Mining Medic now gets paid the same amount as a Miner
/:cl:

### CODE REVIEW

**Comment by NCRLouTenant** [comment]
Hell, pay them more for having to come out there and save us

**Comment by githubuser4141** [comment]
> You're telling me there's lava and chasms everywhere, skyscraper tall murder animals walking around, and everything within a five mile radius wants you dead, and you only get paid as much as a regular doctor?
> 
> They also often need to buy their own synthflesh spray if their first one gets used.
> 
> 🆑 tweak: Mining Medic now gets paid the same amount as a Miner /🆑

I don 't think any animals are 'skyscraper tall', because then they'd either crumple under their own weight, or, they'd be absurdly tough to the degree of not being able to be damaged. At the moment you can reliably kill megafauna with buckshot rounds if you have enough (like 50+ shells) - so clearly they're not skyscraper sized because their durability and damage then would be insane, they'd insta-gib you. It's funny, because IRL most even lightly armoured cars are proofed against buckshot or .357 magnum pistol ammo, so a WW2 armoured car is actually tougher then Bubblegum.

**Comment by Moltijoe** [comment]
> > You're telling me there's lava and chasms everywhere, skyscraper tall murder animals walking around, and everything within a five mile radius wants you dead, and you only get paid as much as a regular doctor?
> > They also often need to buy their own synthflesh spray if their first one gets used.
> > 🆑 tweak: Mining Medic now gets paid the same amount as a Miner /🆑
> 
> I don 't think any animals are 'skyscraper tall', because then they'd either crumple under their own weight, or, they'd be absurdly tough to the degree of not being able to be damaged. At the moment you can reliably kill megafauna with buckshot rounds if you have enough (like 50+ shells) - so clearly they're not skyscraper sized because their durability and damage then would be insane, they'd insta-gib you. It's funny, because IRL most even lightly armoured cars are proofed against buckshot or .357 magnum pistol ammo, so a WW2 armoured car is actually tougher then Bubblegum.

🤓

**Comment by ilikesaying** [comment]
> > You're telling me there's lava and chasms everywhere, skyscraper tall murder animals walking around, and everything within a five mile radius wants you dead, and you only get paid as much as a regular doctor?
> > They also often need to buy their own synthflesh spray if their first one gets used.
> > 🆑 tweak: Mining Medic now gets paid the same amount as a Miner /🆑
> 
> I don 't think any animals are 'skyscraper tall', because then they'd either crumple under their own weight, or, they'd be absurdly tough to the degree of not being able to be damaged. At the moment you can reliably kill megafauna with buckshot rounds if you have enough (like 50+ shells) - so clearly they're not skyscraper sized because their durability and damage then would be insane, they'd insta-gib you. It's funny, because IRL most even lightly armoured cars are proofed against buckshot or .357 magnum pistol ammo, so a WW2 armoured car is actually tougher then Bubblegum.

yeah okay but we're not very realistic, and if you shoot the same spot multiple times the spot will give out eventually
or
image

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
