### PR TITLE
[meta] adds fax machines to each department

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

This was a huge pain in the ass
Shame on whoever didn't do this
# Spriting
no

# Wiki Documentation

not needed
# Changelog

:cl:  
tweak: adds fax machines to each department on meta
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
do....do fax machines even get used

**Comment by N3D6** [comment]
> do....do fax machines even get used

Not really but consistency

**Comment by ToasterBiome** [comment]
CMO and RD?

Oh wait the fucking images didnt load all the way

**Review by ToasterBiome — APPROVED** [review]

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
conflict

**Comment by N3D6** [comment]
Why wasn't this merged before a shit ton of other stuff broke it anyway, I'm not even sure why it's fucking broken anyway. I'll redo this in another PR

**Pull request closed without merging**
