### PR TITLE
Adds Polysmorph digitigrade leg option (and some other tweaks to the race)

### PR DESCRIPTION
**Pull request by Mqiib**
OK so tex/war0100/arthas/that horny spriter guy we all know (maybe) sprited xenos with a couple issues that I really disliked. The primary issue was that their legs were sorta-but-not digitigrade legs that look awful and weird. This pr does a couple things to make the polysmorphs better (imo) and hopefully maybe possibly we can get them as a special/donor/roundstart/other race which would be cool as heck. See changelog for details.

#### Changelog

:cl:  
rscadd: Adds digitigrade leg option to polysmorphs 
rscadd: Added species traits that force male or female to pair with the agender trait
tweak: Greyscaled polysmorph body parts (but not the mutant parts) and sets a fixed mutant color
tweak: technically they can have their mutant color changed but it doesn't do anything (I hope (please don't yell at me for psychadelic rainbow xeno babes as a result of admin shenanigans)) and also byond is picky about mutant colors for no apparent reason
tweak: Polysmorphs are now always female
imageadd: New xenomorph digitigrade legs!
imagedel: Large plasma vessels have been removed for being excessively large
experimental: oh god oh fuck making fetish content less bad and more accurate to proper xenos ban me now before I improve something else
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
image

Image for how they look now without/with dome and without/with digitigrade legs.

**Review by Partheo — APPROVED** [review]
Nice work.

**Review by ynot01 — CHANGES_REQUESTED** [review]
remove the tits

**Comment by Mqiib** [comment]
> remove the tits

They're technically "plasma vessels" and I was never for the tits in the first place. I wouldn't be against removing at least the large version (because holy shit they're huge, god damnit tex) but that'll be a different pr if it happens.

**Comment by ynot01** [comment]
> you

remove the tits

**Comment by alexkar598** [comment]
I'm still concerned they look way too much like xenos to be a roundstart race

**Comment by Mqiib** [comment]
> I'm still concerned they look way too much like xenos to be a roundstart race

image

This is what they look like in comparison (ignore the maid outfit, this is just what I have handy). Also, I haven't set them as a roundstart race as that's not something I should be the one to decide on.

**Comment by missatessatessy** [comment]
Glad you managed to figure out the female thing because I could not and I gave up trying xD

**Comment by Mqiib** [comment]
After looking at the sprites again the large plasma vessels were actually so big they stuck out of the clothing sprites and rather than try and fix them they have been yeeted by popular demand.

**Comment by Marmio64** [comment]
> After looking at the sprites again the large plasma vessels were actually so big they stuck out of the clothing sprites and rather than try and fix them they have been yeeted by popular demand.

tex will be angry

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
