### PR TITLE
BOX LAW OFFICE REWORK

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request

updates the layout of box law office 
image

adds holopad, filing cabinet, pencil holder, and prison camera consoles to box law office (its uniform to every station except for box when it comes to seeing prisoners)
arranges equipment and walls to account for additions

# Why is this good for the game?
becuase lawyers should know that there is perma prisoners and can yell at brig Phys to fix them and attempt to negotiate with sec on the innocence of said prisoners.

# Changelog

:cl:  
rscadd: Adds holopad, pencil holder, prison camera consoles, and a filing cabinet to box law office
mapping: alters the arrangement of box law office

/:cl:

### CODE REVIEW

**Comment by Aquizit** [comment]
Again?

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Vendor there is nasty, I don't like it

**Comment by wonderinghost** [comment]
I'll get on that in the morning

**Review by wonderinghost — COMMENTED** [review]
have updated the layout hopefully

**Comment by AMyriad** [comment]
pod windoors here look wonky imo

**Review by neeshacark — CHANGES_REQUESTED** [review]
The divider just looks bad and there's nothing that looks anything like it for a reason.  Do it differently or revert it back to how it was

**Comment by wonderinghost** [comment]
was updating

**Comment by wonderinghost** [comment]
this pr is broken

**Pull request closed without merging**
