### PR TITLE
Revert "Adds a new crayon decal"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#18292

Yeah... no

### CODE REVIEW

**Comment by Cartlord** [comment]
Aren't Reverts supposed to be on a 48-hour delay?

**Comment by SomeguyManperson** [comment]
> Aren't Reverts supposed to be on a 48-hour delay?

I'm sorry gamer but hes right youre going to have to close your own pr for "48 hour rule"

**Comment by Bibby0110** [comment]
i want a second opinion

**Comment by SomeguyManperson** [comment]
image

**Comment by Bibby0110** [comment]
> image

cant trust github search

**Comment by SomeguyManperson** [comment]
image

**Comment by Bibby0110** [comment]
> image

doctored image

**Comment by Moltijoe** [comment]
48 hours

**Comment by ynot01** [comment]
> Awaiting - Action - HD

image

**Comment by MajManatee** [comment]
The darkest timeline...

**Comment by Moja10** [comment]
bad revert

**Comment by JamieD1** [comment]
Why are we adding dated memes?

**Pull request merged**
