### PR TITLE
nan detection

### PR DESCRIPTION
**Pull request by monster860**
makes it throw a runtime if an attempt is detected to set the temperature to nan or infinity

### CODE REVIEW

**Comment by JamieD1** [comment]
Fixes #8743

**Comment by ghost** [comment]
Bruh my NaN gas, I haven't given immortality to the entire station with it yet.

**Comment by Marmio64** [comment]
my naan bread

**Comment by JamieD1** [comment]
@monster860 Please update with the fixed dlls

**Comment by monster860** [comment]
included in jamie's PR thing now I guess

**Pull request closed without merging**
