### PR TITLE
Adds Coconuts and other coconut things (Partial Port)

### PR DESCRIPTION
**Pull request by boodaliboo**
# Document the changes in your pull request
adds coconuts, coconut bombs, and coconut milk you can even use them as a reagent container
also readds seperated contents as its vital for the coconut bomb but the trait continues to stay  unobtainable
# Spriting
will do this later want to stop coding so i  can finish my essay
# Wiki Documentation

add coconuts and coconut milk to the wiki

# Changelog

adds coconuts, coconut bombs, and coconut milk you can even use them as a reagent container

:cl:  
rscadd: adds coconuts, coconut bombs, and coconut milk you can even use them as a reagent container
imageadd: added coconut sprites that i will show on this page later just need to finish essay
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
what do we gain from this

**Comment by boodaliboo** [comment]
> what do we gain from this

coconuts

**Comment by boodaliboo** [comment]
how do i make seperated chems not appear in strange seeds

**Comment by Maia-J** [comment]
Ok can we cut the coconut shells to use them as bottles?

**Comment by Marmio64** [comment]
is there a coconut gun and does it fire in spurts?

**Comment by boodaliboo** [comment]
> Ok can we cut the coconut shells to use them as bottles?

yes

**Comment by boodaliboo** [comment]
> is there a coconut gun and does it fire in spurts?

sprite it

**Comment by Cartlord** [comment]
I'm concerned because we already have a lot of plants that seem to already be effectively useless because they only exist for flavor & you can barely do anything with them that matters (Limes, onions, peas, cinnamon, garlic...), and I'm afraid that coconuts will just be yet another entry on that list.

**Comment by boodaliboo** [comment]
> I'm concerned because we already have a lot of plants that seem to already be effectively useless because they only exist for flavor & you can barely do anything with them that matters (Limes, onions, peas, cinnamon, garlic...), and I'm afraid that coconuts will just be yet another entry on that list.

ok and? i dont see the issue it gives variety

**Comment by Bibby0110** [comment]
Doesn't actually compile, no work done in 16 days

**Pull request closed without merging**
