### PR TITLE
Protects perma from radstorm

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Protects perma from getting fried

# Changelog

:cl:  
bugfix: Perma nolonger gets irradiated from the storm
/:cl:

### CODE REVIEW

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Bit hugbox

**Comment by Smudged** [comment]
For the few people that are gonna stay in perma until the cows come home, I welcome this change.

**Comment by Georgeur** [comment]
I gotta agree with jamie, hugbox. 
It effecting perma means two things, sec can pretend people they perma literally dont exist, and perma prisoners get the slightest chance to escape (they wont) if theyre protected from the storm by sec/AI. Don't really see the upside. 
It should be people like warden or like brig psy who help you with this, and them not doing their jobs is the issue.

**Comment by JamieD1** [comment]
Make it to the bathroom instead

**Review by Bibby0110 — DISMISSED** [review]
make it the bathroom instead like jamie said

**Comment by redmoogle** [comment]
> make it the bathroom instead like jamie said

That involves a new area and APC for a 2 tile room

**Comment by JamieD1** [comment]
> > make it the bathroom instead like jamie said
> 
> That involves a new area and APC for a 2 tile room

Get on it then

**Pull request merged**
