### PR TITLE
Add dynamic into rotation.

### PR DESCRIPTION
**Pull request by Absolucy**
Dynamic is a really fun mode. It encapsulates the "chaotic metal death trap" feeling of SS13 really well, and creates really unique rounds due to it's unpredictability.

🆑 Lucy
rcsadd: Dynamic Mode is now in rotation :)
/🆑

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
The bane of meta-gamers and sec

**Comment by ToasterBiome** [comment]
the bane of admins

let’s do it

**Comment by A-Distinguished-Axolotl** [comment]
It is time for violence

**Comment by Xoxeyos** [comment]
There are some bugs with how certain ghost antagonists are created, as far as I know, Zombies improperly spawn as a normal human, however I haven't had time to get around to it. Otherwise I feel dynamic should be fine. I've tried my best to keep everything up to date, please point out anything that may be missing, compared to other codebases, and I shall see if it is warranted. https://github.com/yogstation13/Yogstation/issues/8950

**Review by JamieD1 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Might need to change the prob, lets see.

**Pull request merged**
