### PR TITLE
Fixes Accents Incorrectly Capturing on the Middle of Words

### PR DESCRIPTION
**Pull request by Altoids1**
Hopek paid me to do this.

## Overview

I've completely reconfigured how the accent system does its replacement. It should now correctly capture on whole words, and also be capable of altering the pronunciation of non-word sequences.

## Coder Warning

Every single Key in the accent .jsons is now a regex string.
In order to make your word replacement a true word replacement, you must encase the key with ``\b``'s, like so:
```json
"\bcat\b" : "kitty"
```

Additionally, there is now a priority system. Phrases are replaced first, then words, then non-words. This should make it easier to say, change all Rs to Ws in a catgirl language while also doing word-replacements on words that have Rs in them, as the Rs won't be changed until after the word replacement takes place.

Otherwise, priority should be sequential, as it was before; replacements described at the top of the .json are done before the ones below it. There's no real way of making them all work at once in parallel so you're going to have to keep that in mind if you ever create or modify accents.

There is also a small optimization when it's just replacing plaintext words; it skips over running the regex engine and instead just tries accessing the word-to-replacement table with each word in the sentence, replacing them when it hits something.

## Changelog
:cl:  Altoids
bugfix: Accents now work moreso as intended, and do not capture incorrectly on the middle of words as much.
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
so you are telling me that for a single message, 900 regexs are being executed?

**Comment by Hopekz** [comment]
> so you are telling me that for a single message, 900 regexs are being executed?

In addition to fixing the word issue this change to the framework allows most accents to be converted into a mix of speech pattern/word replacements.

What this means:
Accents can now mostly converted down to simple regexes in addition to word replacements.

Here is one example of many where this would actually save a lot of regexes being run because it won't have to go through a list every time:

In this one example if we were to have "ing" replace with "in'" we could remove hundreds of word translations and convert that part to a speech pattern.

image


This change overall is "faster" once the accents are revamped the way this frameworks lets them be not that performance was ever an issue for accents in the first place.

**Comment by Featherfield** [comment]
No more hied as god this is good

**Comment by Altoids1** [comment]
image
# Ready for Review.

**Comment by alexkar598** [comment]
once again, running 300 regexs, per word, per message?

**Comment by Hopekz** [comment]
Forgot to post this here but this also fixed #7780

**Review by Hopekz — APPROVED** [review]

**Comment by alexkar598** [comment]
This was test merged for a bit and didnt break

**Comment by Amelia0010** [comment]
It actually does break.

\btest\b will catch testär because of byond's very lacklustre support for unicode, and the swedish speech impediment actively replaces stuff with äöå. So you know, it'll break

https://regex101.com/r/R03hTV/1

**Pull request merged**
