### PR TITLE
RAM Research Bugfix

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Changes the RAM research requirements to require the PREVIOUS tier instead of just needing blue space tech and the first tier.

# Changelog

:cl:  
bugfix: AIs cant skip a RAM research anymore
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
This is intentional due to the fact that experimental CPUs are a sidegrade, not an upgrade.

**Comment by ToasterBiome** [comment]
24 hours

**Comment by MajManatee** [comment]
ok then

**Comment by Bibby0110** [comment]
ok i will see you all in 21 hours

**Comment by MajManatee** [comment]
Bibby if this is intentional then maybe it shouldn't be in line with the other upgrades? Visually it looks like a direct upgrade in the techweb.

**Comment by Bibby0110** [comment]
> Bibby if this is intentional then maybe it shouldn't be in line with the other upgrades? Visually it looks like a direct upgrade in the techweb.

then move it

**Comment by MajManatee** [comment]
out of scope

**Comment by Bibby0110** [comment]
This is intentional due to the fact that experimental CPUs are a sidegrade, not an upgrade.

If you want, you can move the techweb node placement instead.

**Pull request closed without merging**
