### PR TITLE
removes katana from the necropolis chest pool

### PR DESCRIPTION
**Pull request by stwordcitizen**
# Document the changes in your pull request
Removes the katana from the lavaland chest pool, having a 40 damage 50 block chance item thats only downside is that you can't put it on your back or belt slot is too op and its only real use is to validhunt. 
# Wiki Documentation
Remove katana from necropolis chest wiki page.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:    
rscdel: removed cursed katana from necropolis chest  
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13917 also removes it from the pool

**Comment by Georgeur** [comment]
thank fucking christ

**Comment by tattax** [comment]
change it from rand(1,24) to rand(1,23)

**Comment by Georgeur** [comment]
fuck

**Comment by stwordcitizen** [comment]
> change it from rand(1,24) to rand(1,23)

fixed

**Comment by JamieD1** [comment]
13917 covers this

**Pull request closed without merging**
