### PR TITLE
[Admin] Adds New Admin "Offer Rename" Verb

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Adds a right-click verb for admins to offer a mob a rename (Accept, Decline, Random Name)
Admins are first prompted if they want to allow the mob in question to decline the rename at all, if they don't let them, you are presented with only Accept or Random Name

if you attempt to enter a blank name, or somehow enter a *null* name, or enter the same name you already had, it defaults to random instead and notifies admins
if you Decline, it notifies admins that you declined
if you enter a name that does not pass sanitization, you're told to ahelp if you want a second chance, and it's also messaged to admins that your name was filter-rejected
if you choose a random name instead of manual naming, it's messaged to admins
if you're a carbon, your name is also updated in your DNA and mind to prevent Weirdness
Uses your Real_name to prevent (as Name Lastname) popping up on second offers
if you are somehow deleted before you can finish renaming yourself, that is messaged to admins

ALL of the above is also admin logged

In-game Examples:
https://youtu.be/MvBQKjPvgdg

slightly out of date gifs that do well enough to show off the prompts:
dreamseeker_UdKcFPMXE8
dreamseeker_x8CA9EOau6

# Changelog

:cl:  @Chubbygummibear 
rscadd: Admins can now offer a mob a rename prompt.
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
Pardon the lack of visible prompts in the video, it was the best I could do with OBS

**Comment by ToasterBiome** [comment]
are these interactions admin logged too?

**Comment by VaelophisNyx** [comment]
yep, should be
Unless you specifically mean the conditional stuff like "denied a name change" in which case, it can be if you want

**Comment by ToasterBiome** [comment]
> yep, should be Unless you specifically mean the conditional stuff like "denied a name change" in which case, it can be if you want

do eet

**Comment by Hopekz** [comment]
Good PR

**Comment by Hopekz** [comment]
The only thing that I could think of is that picking a random name is not immediately obvious to the person that is being renamed.

It would be nice if they didn't have to have previous knowledge that they have to leave it blank to get a random name

**Comment by VaelophisNyx** [comment]
they dont have to leave it blank, you can choose a random name as an option before manual naming; the GIFs dont show it and my OBS setup failed to capture the popups

**Comment by VaelophisNyx** [comment]
PR updated to reflect prior comment

**Comment by ShoziOffical** [comment]
epic

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
