### PR TITLE
Reverts Removes putting collars on Humans

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Revert of #14717 
Allows everyone to wear it

Original PR was disliked quite heavy and tbh people wearing collars could make for something funny idk

# Wiki Documentation

Collars can be worn by everyone

# Changelog
:cl:  
tweak: Everyone can wear pet collars now
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
Reverts redmoongle's birth

**Comment by Addust** [comment]
like seriously keep that fetish content CONTAINED to one thing

**Comment by redmoogle** [comment]
> like seriously keep that fetish content CONTAINED to one thing

I just hear people continuously complain about it

**Comment by VaelophisNyx** [comment]
remember that it makes for funny moments too, when a secoff has a collar put on them by the HoS for example


also """muh fetish content"""
fuck off this isn't splurt, if you think it's fetish content maybe stop being horny

**Comment by Sniblet** [comment]
I argue that it is more fetishy to only let the fetish race wear the collar

**Comment by Cartlord** [comment]
what if we just made nobody able to wear them

**Comment by Addust** [comment]
just


delete collars being used as clothing for humanoids

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
