### PR TITLE
Moving while doing a surgery hurts the patient

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Makes it so moving during an operation cause it to damage the patient, like on bay.  Makes the surgery room much more important and funny medbay suffering. Is tested, does work.

# Spriting
None.

# Wiki Documentation

May want to mention it on the wiki. 

# Changelog

:cl:  
tweak: moving while doing a surgery now hurts the patient
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
can't wait to toss a patient's guts like a salad because someone who isn't even supposed to be in medbay keeps walking through me :^)

**Comment by VaelophisNyx** [comment]
not to mention be unable to back out of a surgical step to ask a question :^)

**Comment by nmajask** [comment]
> not to mention be unable to back out of a surgical step to ask a question :^)

press x

**Comment by maxion12345** [comment]
me about to walk into medbay on help intent just so I can shuffle through the doctors doing surgery before leaving (I did not need medical attention)

but good change, only issue is that people might put themselves on disarm/harm to avoid shuffling and accidentally force themselves to fail a surgery step "wtf why won't it work this pr sucks" type shit

**Comment by SomeguyManperson** [comment]
I don't particularly agree with this bc moving is the usual way of interrupting yourself + quite easy to occur on accident

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
