### PR TITLE
Engineering sprite update

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Updates a few engineering sprites to fit the recent clothing sprite changes. Includes hard hats, magboots, radiation suits, firesuits, work boots, insulated gloves, hazard vests, fire axes, all the basic engineering tools, the network admin's winter coat, and resprites the elder atmosian hardsuit into looking like an armored firesuit. Also gives the bluespace RPED and advanced extinguisher their own unique in-hand sprites.

Uses sprites from all these, some of which are edited to fit in better with our current sprites.
tgstation/tgstation#58616
tgstation/tgstation#67000
tgstation/tgstation#60119
tgstation/tgstation#65199
tgstation/tgstation#72736
tgstation/tgstation#78236
BeeStation/BeeStation-Hornet#2677

# Why is this good for the game?

Engineer gaming

# Spriting
scrnshot_engi_1
scrnshot_engi_2

# Changelog

:cl:  
imageadd: updates a bunch of engineering-related sprites
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Thanks for doing the thing i definitely wasn't supposed to do myself but put off forever

**Comment by AMyriad** [comment]
> https://github.com/BeeStation/BeeStation-Hornet/pull/2677

these really being included too?
I feel mixed on the designs/styles

image
image
image
image

**Comment by iamthesilly** [comment]
> these really being included too? I feel mixed on the designs/styles

Just the boots from that one

**Comment by azzzertyy** [comment]
that hazmat suit design :heart_eyes:

**Comment by 00ze-cyclone** [comment]
Not sure for the tools.
The clothes look wonderful tho.

**Comment by AMyriad** [comment]
> https://github.com/tgstation/tgstation/pull/78236

No, thank you.

**Comment by iamthesilly** [comment]
> Not sure for the tools. The clothes look wonderful tho.

Which tools?

**Comment by 00ze-cyclone** [comment]
> > Not sure for the tools. The clothes look wonderful tho.
> 
> Which tools?

Mainly the screwdriver, t-ray scanner, analyzer and the inducers.
Multitool actually is the one I have no problem with.
Rest of the tools are « eeeeeh »

**Comment by ShoziOffical** [comment]
finally in-hand advanced fire extinguisher sprite

**Review by cuackles — APPROVED** [review]
was waiting for iconbot to fix itself but it never happend, so this is a lot of sprite changes but they do fit along with the previous big pr got in, it also refreshes some old sprites that needed a face lift, so i will be approving it

**Pull request merged**
