### PR TITLE
Pound dirt you filthy ban evader/banned computer sharer

### PR DESCRIPTION
**Pull request by Bibby0110**

### CODE REVIEW

**Comment by adamsong** [comment]
And if the banned account was banned to prevent multikeying?

**Comment by Bibby0110** [comment]
> And if the banned account was banned to prevent multikeying?

tough luck, if this is triggered you've already multikeyed

**Comment by adamsong** [comment]
If we get someone on the discord saying "Hey, I no longer login with foo, I now use bar," we will ban foo, and give bar all their notes to bar. This is fine and allowed, but not under this new PR

**Comment by Bibby0110** [comment]
> If we get someone on the discord saying "Hey, I no longer login with foo, I now use bar," we will ban foo, and give bar all their notes to bar. This is fine and allowed, but not under this new PR

I'm well aware of how you do things..

Solution is to tell them to pound sand and stick to their original ckey :)

**Comment by num1bamf** [comment]
Why don’t you come up with a better sticky ban rather than this that no one asked for.

**Comment by Bibby0110** [comment]
> Why don’t you come up with a better sticky ban rather than this that no one asked for.

Sticky ban has nothing to do with this

**Comment by Moggram** [comment]
>
> 
> Solution is to tell them to pound sand and stick to their original ckey :)

And what if they lost their original account?

**Comment by Bibby0110** [comment]
> > Solution is to tell them to pound sand and stick to their original ckey :)
> 
> And what if they lost their original account?

If you manage to lose your email and thereby lose access to your account that is 100% on you

**Pull request closed without merging**
