### PR TITLE
Ethereal hair and beard port.

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request
**Tested.** This is a **port** of [these](https://github.com/tgstation/tgstation/pull/49934) [PRs.](https://github.com/tgstation/tgstation/pull/62321)

This PR gives Ethereals hair and beards. Ethereals **desperately** need more customization, I'm 99% sure the only thing you can change as an Ethereal are preset colors.

# Wiki Documentation
Ethereals now get hair and beards.

# Changelog

:cl: Qustinnus and Likteer
tweak: Ethereals can have beards and hair.
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Give them also hair gradients stuff and shit

**Comment by patpol4** [comment]
Doesnt make any sense and looks stupid

**Comment by cuackles** [comment]
> Doesnt make any sense and looks stupid

Ethereals already don't make any sense biologically and they have just 1 customization feature, let them have this at least to see if the ethereal playerbase grows and likes it, if they don't they can always stay bald

**Comment by Marmio64** [comment]
i'd prefer if it was just beards and no rainbow gradient nonsense or anything

**Review by JamieD1 — APPROVED** [review]
As long as we agree this is all stick on hair

**Pull request merged**
