### PR TITLE
Updates heretic target menu

### PR DESCRIPTION
**Pull request by cowbot92**
Thank you so much to Baiomu for all the assistance on the PR

# Document the changes in your pull request

This PR updates the stupid list of names to a radial menu of targets w/ their current outfit & name

image

# Why is this good for the game?

Should help people a little bit more when picking out targets (not choosing the guy wearing a space suit)

# Testing

So I wasn't able to get this to work on my own private server, but when baiomu ran the code on his it was fine?? And we tested it together so. Like, we'll see about that. Code works perfectly fine though.

# Changelog

:cl:  

tweak: tweaked heretic target menu 

/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Bruh this is literally my screenshot

**Comment by cowbot92** [comment]
> Bruh this is literally my screenshot

well yeah I need some proof that it works!!

**Comment by Moltijoe** [comment]
Oops wrong button

**Comment by ManofSan** [comment]
good good, now make heretics less likely to target eachother

**Comment by ToasterBiome** [comment]
> good good, now make heretics less likely to target eachother

feature

**Comment by Moltijoe** [comment]
huge buff to heretics, no longer are they gonna pick someone and realize they picked a miner that's already wearing a heck suit 5 minutes into a round

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
