### PR TITLE
Makes pipe bombs antag crafting book restricted

### PR DESCRIPTION
**Pull request by Mqiib**
They chain-react so you can just slap a bunch in a few boxes and instantly kill people with minimal effort. Also, only antags should be mailbombing people ANYWAYS. Label this an ided pr, fuck you

# Wiki Documentation

Restricted to the antag crafting book, might want to mention it somewhere.

# Changelog

:cl:  

tweak: Pipe bombs are no longer available to everyone and mass-producible by a monkey with an autolathe.

/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
These aren't antag only??? lmfao

**Comment by cowbot92** [comment]
mqiib gonna mail a pipebomb to the coders irl

**Comment by KillerOrcaCora** [comment]
Knew this was coming sooner or later...Cant have anything nice on ss13!

**Comment by SomeguyManperson** [comment]
THE mousetrap ied (always activates on time)

**Comment by maxion12345** [comment]
me when I make normal potassium water pipebombs instead of crafted pipebombs because I'm not an antagonist

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
