### PR TITLE
Adds IPCs back in the game(hopefully)

### PR DESCRIPTION
**Pull request by burn1cycle**
Credits to BeeStation(Credits would be a milelong if I listed each individual port)

Adds IPCs
Vid: https://www.youtube.com/watch?v=eWWDqZTMs3k

They're a synthetic race different from preternis, mainly with chassis customization and TV screens. They have a high burn mod

also they cant be cloned because they're robots. so you can use a cyborg rebooter in place of that.

They lose limbs easily but can be attached easily, Head is stored in the chest and can live without a head

Wiki Documentation:

There a race. They are robotic (they already have been given pictures needed, and from what I've heard are already working on the page)

System Cleaner | 1 part Ethanol, 1 part Chlorine, 2 parts Phenol, 1 part Potassium | Quickly purges toxin damage in the rare case an IPC gets said damge.

Solder: | 1 part Ethanol, 1 part Copper, 1 part Silver, Temperature 374K | Quickly heals brain damage and traumas, but only for IPCs

 Remove that liver runtime
:cactus:  Test Mechfabs
:cactus:  Test Chemicals
:cactus:  Test Charging
:cactus:  Test ORGANIC/SYNTHETIC Chemicals
:cactus:  Fix Limb Issue
:cactus:  Test Revival/Surgery
Why is this good for the game?
Is a very cool race and could easily have some cool interactions

Changelog
:cl:
rscadd: Add IPCs from Beestation
/:cl:

### CODE REVIEW

**Comment by burn1cycle** [comment]
I beg everyone to please be patient and stop asking me when this feature will be added back into the game. It's not up to me because I don't have the power to merge. I will make every attempt to have it merged as soon as possible on my end.

**Review by redmoogle — CHANGES_REQUESTED** [review]
Pull Request Template.

**Comment by Cartlord** [comment]
So since you have the "Missing/Inadequate Rationale" tag, I'll be the one to ask: why? I have my reasons for wanting to play IPC, but I want to hear why you want to add them.

**Comment by burn1cycle** [comment]
> Pull Request Template.

 If you're having a problem with the way I am doing things you could do it yourself?

**Comment by redmoogle** [comment]
> > Pull Request Template.
> 
>  If you're having a problem with the way I am doing things you could do it yourself?

This is a requirement.

**Comment by burn1cycle** [comment]
> > > Pull Request Template.
> > 
> > 
> > If you're having a problem with the way I am doing things you could do it yourself?
> 
> This is a requirement.

I fixed it, take the tag off.

**Comment by redmoogle** [comment]
> > This is a requirement.
> 
> I fixed it, take the tag off.

I already gave up my maintainer perms, I left like a couple hours ago so you're going to have to grab someone else.

**Comment by burn1cycle** [comment]
> > > This is a requirement.
> > 
> > 
> > I fixed it, take the tag off.
> 
> I already gave up my maintainer perms, I left like a couple hours ago so you're going to have to grab someone else.

Your last official act was to nasty-tag my PR just before you quit? You're also the one who pulled the feature out of the game a few days earlier "because you're quitting". 

Are you having a problem?

**Comment by redmoogle** [comment]
> 
> 
> > > > This is a requirement.
> > > 
> > > 
> > > I fixed it, take the tag off.
> > 
> > 
> > I already gave up my maintainer perms, I left like a couple hours ago so you're going to have to grab someone else.
> 
> Your last official act was to nasty-tag my PR just before you quit? You're also the one who pulled the feature out of the game a few days earlier "because you're quitting".
> 
> Are you having a problem?

So what. it's not getting speedmerge, it doesnt really do anything. and so? im not maintaining for months on ends.

and also you're not competent enough to port ipcs you already fucked a very simple merge conflict up. on top of having to fix the bugs with them

you clearly demonstrated you really dont know what the fuck you're doing. You're best option is to just close this pr and give up.

**Comment by burn1cycle** [comment]
>and also you're not competent enough to port ipcs you already fucked a very simple merge conflict up. on top of having to fix the bugs with them

Get off your high horse. If you hadn't screwed up a simple legacy hand off I wouldn't be here. Since you screwed up and nobody else is stepping up I'm the best you've got. You can either do it yourself, support me, or get out of my way while I do what you won't do. This "ex-employee hanging out in development crapping on people trying to fix their F#-you-on-the-way-out feature removal" is beyond irritating.

**Comment by redmoogle** [comment]
> 
> 
> > and also you're not competent enough to port ipcs you already fucked a very simple merge conflict up. on top of having to fix the bugs with them
> 
> Get off your high horse. If you hadn't screwed up a simple legacy hand off I wouldn't be here. Since you screwed up and nobody else is stepping up I'm the best you've got. You can either do it yourself, support me, or get out of my way while I do what you won't do. This "ex-employee hanging out in development crapping on people trying to fix their F#-you-on-the-way-out feature removal" is beyond irritating.

heres what you need to do then :)

Remove IPCs spawning as changelings, probably update the save file, fix their missing icon states from the merge conflict you fucked up, make other people taste things.

and before you ask. no I will no help you. get fucked asshole

**Comment by burn1cycle** [comment]
> and before you ask. no I will no help you. get fucked asshole

That's cool
Don't come back
Ever.

**Comment by redmoogle** [comment]
> 
> 
> > and before you ask. no I will no help you. get fucked asshole
> > That's cool
> > Don't come back
> > Ever.

ok mr I keep spamming wiki and keep getting banned and dont know how to code

**Comment by redmoogle** [comment]
also you have a fucking 100% close rate. "yeah this will get merged for sure" yeah no.

**Review by SomeguyManperson — CHANGES_REQUESTED** [review]
fix IPCs being changelings, fix the taste thing mentioned in the previous pr and stop being a shit
if I see any more "guys please merge my pr I have so many people asking about it" or other begging ESPECIALLY before issues with the last pr are addressed this is getting closed
if all the current issues and any issues that come up get fixed ping me

**Comment by burn1cycle** [comment]
Citing harassment from ex-coder and hostile work environment to complete projects in. Even if I did fix the issues brought up there would no doubt be other "new issues" to keep my PR from being merged.

**Comment by Cartlord** [comment]
redmoogle's posts on this are some of the rudest I've seen in a LONG time, wow. I had my own set of issues with IPCs that'd likely need fixed (particularly involving Floor Cluwne), but that's just too far, especially them bad-tagging this and then leaving.

**Comment by redmoogle** [comment]
> 
> 
> redmoogle's posts on this are some of the rudest I've seen in a LONG time, wow. I had my own set of issues with IPCs that'd likely need fixed (particularly involving Floor Cluwne), but that's just too far, especially them bad-tagging this and then leaving.

He was rude first and has generally been unwanted. He's earned this and also it's not bad tagging.

I have actual reasons to be rude to him. mainly that he wont be nice back and ends up pissing everyone else off. He blamed me when I closed the PR "that I fucked everyone over" this is my choice and I didnt even do that. It was warranted.

**Comment by Cartlord** [comment]
I don't mean the tagging was bad, I mean the tag itself was one that makes the PR look bad; you added a "Missing/Inadequate Rationale" tag, then seemingly left maintainers before it was removed - that seems very rude, as though adding the tag was a final act of spite before your departure. I don't know what other drama this user may or may not have been up to, and frankly I hardly care; I don't think it should be brought up in this PR. I'm frustrated to see that IPCs, a race I like and want to be added, are being shot down because of drama that seems to have precious little to do with the race itself.

**Comment by redmoogle** [comment]
> 
> 
> I don't mean the tagging was bad, I mean the tag itself was one that makes the PR look bad; you added a "Missing/Inadequate Rationale" tag, then seemingly left maintainers before it was removed - that seems very rude, as though adding the tag was a final act of spite before your departure. I don't know what other drama this user may or may not have been up to, and frankly I hardly care; I don't think it should be brought up in this PR. I'm frustrated to see that IPCs, a race I like and want to be added, are being shot down because of drama that seems to have precious little to do with the race itself.

also consider burn1cycle _really_ doesn't know what he's doing. and I'm already considering someone who knows what they're doing.

**Pull request closed without merging**
