### PR TITLE
vaccines must be injected to have effect

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

something i thought of when watching a sentient virus unfold today

small virus buff, vaccine pills (0.1u) have become a staple of instantly defeating viruses en masse and it's a bit too easy imo

doctors will hopefully be playing a more active role in inocculation now

image

# Changelog

:cl:  
tweak: Vaccines must be injected to have effect, eating them will do nothing
/:cl:

### CODE REVIEW

**Comment by Altoids1** [comment]
a bit of an i ded

**Comment by ynot01** [comment]
> a bit of an i ded

i was playing sec that round, invalid

**Comment by VaelophisNyx** [comment]
make sentient diseases less ass, not nerfing vaccines

**Comment by ynot01** [comment]
> make sentient diseases less ass, not nerfing vaccines

i see no issue with sentience disease scaling, only the issue that once one person cures it it is effectively game over

**Comment by VaelophisNyx** [comment]
the issue is they get metagamed instantly and cured at light speed before their potential cure is hard to make

**Comment by 00ze-cyclone** [comment]
A random pointless nerf that won't solve anything, med will just leave syringes full of water with 0.5u of vaccine or use syringe gun/CMO hypo on 1u

**Comment by ynot01** [comment]
> med will just leave syringes full of water with 0.5u of vaccine or use syringe gun/CMO hypo on 1u

i see this as medical being crafty, nothing wrong with this

requires syringes to be made and mixed with water actively as opposed to shitting out 150 pills instantly

**Comment by RG4ORDR** [comment]
People can't sit around long enough to be syringed.
Some sentient viruses roll with actually hard to make chems, and know how to stealth and kill a lot of people.
This is the space age where you can literally cure death by a defibulator.

Making problems where there aren't any... Pushing a /tg/ styled changed when even they don't do it.

**Comment by ynot01** [comment]
> People can't sit around long enough to be syringed. 

then they die

**Comment by milk-is-cool** [comment]
I would actually agree with you ynot01 on this one. The 0.1u vaccine pills are absolutely nuts, but with this change it finally gives docs a valid helpful reason to use the rapid syringe gun for its actual intended purpose. I do think this will make curing people more fun.

**Comment by VaelophisNyx** [comment]
I mean you could just
make pills require 1u or more to be made

**Comment by JamieD1** [comment]
I think changing the amount of vaccine required will be a better step, meaning they will actually need to keep working to keep curing people, if you produce 100u of vaccine at the moment thats 1000 people cured. Maybe make it require 10u instead, Im not sure but I dont think this is the right solution, especially when medbay gets overworked really quick.

**Comment by VaelophisNyx** [comment]
I think the only problem with that one, Jamie, is that the PANDEMIC literally couldn't keep up with a disease then; vaccines have a cooldown of something like 60s

**Comment by JamieD1** [comment]
> I think the only problem with that one, Jamie, is that the PANDEMIC literally couldn't keep up with a disease then; vaccines have a cooldown of something like 60s

Then modify it, we dont want 0.1 curing a disease, we kinda want it to be a challenge and not insta game over for the sentient disease for example.

**Comment by neeshacark** [comment]
the issue i foresee with this is people rushing medbay en-masse not only to get a vaccine but to steal a syringe to inject themselves because they dont want to wait for the doctor to inject them because there's 30 other people needing a shot and also they are combusting and exploding constantly.

**Comment by CMOisLing** [comment]
I agree this is a sentient disease problem. Viruses need to be quickly cureable on mass because they can spread so fast. Maybe give sentient diseases passive 2 stealth.

**Comment by JamieD1** [comment]
> > I think the only problem with that one, Jamie, is that the PANDEMIC literally couldn't keep up with a disease then; vaccines have a cooldown of something like 60s
> 
> Then modify it, we dont want 0.1 curing a disease, we kinda want it to be a challenge and not insta game over for the sentient disease for example.

^ @ynot01

**Comment by JamieD1** [comment]
Closing as no Response, reopen it when you look at comments above.

**Pull request closed without merging**
