### PR TITLE
adds a new enclave special kit and 2 new weapons a plasma rifle and laser rifle, and makes a syndicate x01 power armor that is stronger 

### PR DESCRIPTION
**Pull request by boodaliboo**
# Document the changes in your pull request
gives you x01 power armor, 3 stim pack, 3 healing stimpaks, and a new plasma rifles and adds a new stimpak that has identical reagents to the survival medipen.

ports sprites from bad deathclaw for laser rifle and plasma rifle
seperately adds a laser rifle 

# Spriting
image

# Wiki Documentation
gives you t45 power armor a stim pack and a new laser rifle 

# Changelog

gives you t45 power armor a stim pack and a new laser rifle 

:cl:  
rscadd: Added a  new 20tc uplink kit based off of the brotherhood of steel from fallout
imageadd: added  a new aer9 laser rifle
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
20TC?

T45B is kinda weak, ngl

**Comment by boodaliboo** [comment]
> 20TC?
> 
> T45B is kinda weak, ngl

ill make it enclave armor

**Comment by Marmio64** [comment]
x-01 armor has less armor than the salvaged t-45 armor when un-upgraded, perhaps the kit should come with 10 weaver chitin or something so it is actually good, or make a subtype.
I also think syndis shouldn't get powerful laser weaponry like this as it doesn't fit the syndicate (or the enclave). You could turn it into a plasma gun instead (can just be the same stats but no glass passthrough or recharge), there are fallout servers you can likely borrow a high quality sprite from.

**Comment by boodaliboo** [comment]
> x-01 armor has less armor than the salvaged t-45 armor when un-upgraded, perhaps the kit should come with 10 weaver chitin or something so it is actually good, or make a subtype. I also think syndis shouldn't get powerful laser weaponry like this as it doesn't fit the syndicate (or the enclave). You could turn it into a plasma gun instead (can just be the same stats but no glass passthrough or recharge), there are fallout servers you can likely borrow a high quality sprite from.

yea plasma is a good idea and it fits enclave better

**Comment by VaelophisNyx** [comment]
note, do 20 chitin not 10, because it needs the helmet upgraded too

**Comment by boodaliboo** [comment]
> note, do 20 chitin not 10, because it needs the helmet upgraded too

you can upgrade them? im not aware of this mechanic

**Comment by Bibby0110** [comment]
Merge conflicts + Doesn't Compile + Not draft.
Reopen when you resume working on it

**Pull request closed without merging**
