### PR TITLE
Removed code bloat from servitor skull

### PR DESCRIPTION
**Pull request by Moltijoe**
didn't actually use this since it immediately overwrote it.
just a heads up to any spriters, if you are wanting to add something, just ask me and I'll handle the code. (assuming it isn't too much work)
I don't want something like orca's bedsheet code in the game if possible.

### CODE REVIEW

**Comment by tattax** [comment]
why do you guys keep making changelogs for this lol
who is gonna join the game and see "Removed code bloat from servitor skull" and be "how nice"

**Comment by Moltijoe** [comment]
> why do you guys keep making changelogs for this lol who is gonna join the game and see "Removed code bloat from servitor skull" and be "how nice"

because whenever i don't add a changelog someone goes "err hurr umm mr CODER where is my CHANGELOG!?"

**Comment by cuackles** [comment]
god bless molti for fixing my shitcode

**Review by ynot01 — CHANGES_REQUESTED** [review]
Changelog is for player-facing changes only

**Review by ynot01 — APPROVED** [review]

**Comment by Moltijoe** [comment]
doesn't need to happen right away and would cause conflicts with my tgui PR (it's also fixed there)

**Pull request closed without merging**
