### PR TITLE
[PORT] Axolotl

### PR DESCRIPTION
**Pull request by warface1234455**
- ports https://github.com/tgstation/tgstation/pull/69973
- ports https://github.com/tgstation/tgstation/pull/70290
<details><summary>Did you fucking test this??</summary>

### _**yes, all sprites work**_

</details>

# Document the changes in your pull request

Adds axolotl
Axolotl can be ordered from cargo for 4000 crw
Axolotl can be fished from fishing pool as uncommon loot
Axolotl can be worn on head
Petting mothroach now make a heart effect and give mood buff
AI now has axolotl hologram

**Map changes** (Box, gax, meta)
Adds axolotl pet called "Bop" for tcomms
Adds axolotl pet called "Bap" for botany

# Spriting
image
image
image
image

# Wiki Documentation
Axolotl (Probally a new wiki page)
Axolotl can be ordered from cargo
Axolotl can be fished from fishing pool as uncommon loot
Axolotl can be worn on head
Petting mothroach now make a heart effect and give mood buff
AI now has axolotl hologram

**Map changes** (Box, gax, meta)
Adds axolotl pet called "Bop" for tcomms
Adds axolotl pet called "Bap" for botany

# Changelog

:cl:  kawoppi, warface1234455
rscadd: Adds Axolotl
rscadd: Axolotl can be fished from fishing pool as uncommon loot
rscadd: Axolotl can be worn on head
rscadd: Adds axolotl pet called "Bop" for tcomms
rscadd: Adds axolotl pet called "Bap" for botany
rscadd: AI now has axolotl hologram
tweak: 4 Axolotls can be ordered from cargo for 4000cr
tweak: Petting mothroach now make a heart effect and give mood buff
mapping: Adds axolotl to gax, box, meta
mapping: 
imageadd: added Axolotl sprites
/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]
Add them to the fishing pool and also make them be able to be put on buckets

**Comment by ShoziOffical** [comment]
> Add them to the fishing pool and also make them be able to be put on buckets

@cuackles i can try the fishing pool one, but for bucket it kinda hard
image

**Comment by AlvCyktor** [comment]
make them immortal. NOW

**Comment by ShoziOffical** [comment]
> make them immortal. NOW

Would love to lol

**Comment by ShoziOffical** [comment]
oh my god github

**Comment by ShoziOffical** [comment]
can you remove the mapchange label

**Review by KillerOrcaCora — APPROVED** [review]

**Comment by warface1234455** [comment]
WHAT

**Comment by warface1234455** [comment]
i added sound and it gives me icon merge conflicts wtf

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]
stupid map review

**Comment by kawoppi** [comment]
There's inhand sprites for them now as well
https://github.com/tgstation/tgstation/pull/70290

**Comment by ShoziOffical** [comment]
> There's inhand sprites for them now as well [tgstation/tgstation#70290](https://github.com/tgstation/tgstation/pull/70290)

Alright ill check it out, thanks

**Comment by ShoziOffical** [comment]
sorrry @ToasterBiome

**Pull request merged**
