### PR TITLE
Makes the Cluwnification Burger Kit slightly less terrible Branch Edition

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 Fluffe9911
tweak: Cluwnification Burger now comes in a happy meal box complete with two mimanas a small toy and a emag!
/🆑

### CODE REVIEW

**Comment by ThatLing** [comment]
Good idea, not sure about the free emag though

**Comment by fluffe9911** [comment]
Eh its to help give a slightly better incentive to buying it over romerol depending on what gimmick you wanna do so like on one hand everyone dies on the other hand everyone gets disabled but I get a free emag as well

**Comment by ThatLing** [comment]
How about giving them a stenchkin instead?

**Comment by fluffe9911** [comment]
Eh alrighty fair enough

**Pull request merged**
