### PR TITLE
Adds new Fish Fear Me hat

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Adds a new hat based on this meme hat: 
unknown
the description matches the hat's text

4 are available in gift vendors as a premium item
It was unclear if this was for general use or if this had been made at my request as my donor item, which has since elapsed. so for now...vendor item.

the hat provides 5 fishing power.

adds a Legendary variant that provides 15 fishing power and has an on-equip chat message. Can be caught as rare fishing loot

# Spriting
ss (2022-07-10 at 10 48 38)
all four facings (hat can be flipped but the sprites are just facing-swapped)
and the item sprite.

# Wiki Documentation

will need to add this hat to the gift vendor's stock on the vendor page

# Changelog

:cl:  VaelophisNyx, @AlvCyktor
rscadd: Adds new Fish Fear Me meme hat
rscadd: Adds new Fish Fear Me meme hat to the gift vendor
imageadd: adds new icon and mob sprites to handle the new hat
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
sure would love if github could tell me what PR is causing this merge conflict!

**Comment by VaelophisNyx** [comment]
oh ffs the fucking hydrogen hat

**Comment by VaelophisNyx** [comment]
conflict resolution in progress

**Comment by VaelophisNyx** [comment]
literally no conflict but ok, go off github

**Comment by VaelophisNyx** [comment]
If anyone knows how to mark the conflict as resolved that'd be great

**Comment by VaelophisNyx** [comment]
there we fucking go
christ

**Comment by ToasterBiome** [comment]
no fishing bonus?

**Comment by VaelophisNyx** [comment]
oh-
I mean

sure I can do that

**Review by KillerOrcaCora — APPROVED** [review]
Good sprites I saw this hat at my job today

**Pull request merged**
