### PR TITLE
Fixes accidental nerf to every two-handed weapon in the game

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

When the two handed component as added, the way damage changes based on wielding was changed, but the damage of most two-handed weapons were never adjusted to account for this so now they all do 5 less damage than before because of an oversight.

Damage increase from wielding now works the way it used to, because it's easier to account for increases in weapon damage this way.

# Changelog

:cl:  
bugfix: fixed unintended change to damage of every two-handed weapon
bugfix: fixed runtime error when trying to use certain two-handed weapons with one hand
/:cl:

### CODE REVIEW

**Comment by Therandomhoboo** [comment]
Tch... Atmos powercreep

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
can you check spears too? i remember this being an issue

**Comment by iamthesilly** [comment]
> can you check spears too? i remember this being an issue

Turns out it was a lot more than just spears

**Comment by SapphicOverload** [comment]
@ToasterBiome

**Review by JohnFulpWillard — COMMENTED** [review]
i think it would be better to bring back the old behavior of adding the force ontop of the existing one, that way you can remove things like the component checking for sharpening.

**Comment by bawbbawbins** [comment]
> i think it would be better to bring back the old behavior of adding the force ontop of the existing one, that way you can remove things like the component checking for sharpening.

hi jhony :DDDDD

**Comment by JohnFulpWillard** [comment]
blocked

**Review by Moltijoe — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
