### PR TITLE
Adds human descriptions

### PR DESCRIPTION
**Pull request by Majkl-J**
# Document the changes in your pull request

Added some baseline human descriptions so it isn't just a TBD.

# Changelog

:cl:  
rscadd: Humans are now described
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Dude qctually just copy pasted wikipedia

**Comment by Maia-J** [comment]
> Dude qctually just copy pasted wikipedia

Yes.

**Comment by Skrem7** [comment]
This explains nothing about what humans have been doing between our current time and this fictional future. I would rather have a TBD that imply some "full backstory" that's lazily copy-pasted here.

You could have actually filled it out yourself just fine with stuff on the timeline if you cared about lore and making this description what it should be.

**Comment by Moltijoe** [comment]
meme PR

**Pull request closed without merging**
