### PR TITLE
New tracking revolver

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Adds a new weapon/tool for Security, the Caldwell Tracking Pistol

It is an innately silenced revolver which fires a new round-type, .32 TRAC. It's effectively the same as .38 TRAC regarding the tracking implant, but it does 5 damage and no stamina damage. In addition, the speed loader for it (and as a result, the revolver's ammo capacity) is seven rounds. .38 TRAC is gone and replaced with this new ammo type.

It is able to be printed at the security protolathe for 10000 metal, 3000 silver, and 2000 titanium once Subdermal Implants are researched (the same node that unlocks implant injectors and .32 TRAC).

It can also fit on the secbelt because it is very much a TOOL and not a weapon.

image
image

# Spriting
image
tracrevolver
courtesy of @AlvCyktor 

Full .32 TRAC sprite: 
image
Individual state sprites:
32trac
32trac-0
32trac-1
32trac-2
32trac-3
32trac-4
32trac-5
32trac-6
32trac-7

# Wiki Documentation

Adds the Caldwell Tracking Revolver, an innately suppressed revolver that can only fire .32 TRAC rounds. It can be printed at the Security lathe after Subdermal Implants is researched; the same node unlocks implant injectors, including chemical and tracking implants, and TRAC ammo.
The detective's revolver can no longer load .38 TRAC rounds
The new .32 TRAC does 5 damage and no stamina damage

Ammo crate from Cargo has had the TRAC speed loader removed.

# Changelog

:cl:  
rscadd: Adds the Caldwell Tracking Revolver, a weapon, once researched, that is able to be printed by Security officers
imageadd: Fancy new tracking revolver sprites
rscadd: Adds .32 TRAC, a smaller bullet that is functionally identical to normal TRAC rounds.
imageadd: Seven-shot speedloader for the new caliber type
rscdel: .38 TRAC removed, all instances replaced with new .32 TRAC
bugfix: Fixes some typos in .38-related descriptions
tweak: .32 TRAC speedloader removed from ammo crate from Cargo
/:cl:

### CODE REVIEW

**Comment by Skrem7** [comment]
Tested it in-game, revolver sprite is a bit large but other than that, everything should be working fine.

.32 TRAC might get a new, smaller bullet sprite, just waiting on good 'ol Orca to give feedback

**Review by ToasterBiome — APPROVED** [review]
Map approval not thing approval

**Review by KillerOrcaCora — APPROVED** [review]
We will fix the gun of banding later…

**Comment by JamieD1** [comment]
Fix cornflakes then good to go

**Review by KillerOrcaCora — DISMISSED** [review]
The Gutterpunch ammo is a bit too much and should be excluded from this PR

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
The Gutterpunch ammo is a bit too much and should be excluded from this PR

**Comment by Skrem7** [comment]
> The Gutterpunch ammo is a bit too much and should be excluded from this PR

The changes have been made you egg go ahead and give your approval

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
and because orca is an idiot and merged the ammo after the gun there are now 100 conflicts, please fix

**Comment by Skrem7** [comment]
image
@KillerOrcaCora

**Review by KillerOrcaCora — APPROVED** [review]

**Pull request merged**
