### PR TITLE
Attempting to wrest someone's gun from their hands will force them to fire it where they are aiming

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Shoving someone holding a gun now has the side effect of forcing them to fire wherever they are aiming 70% of the time

The resultant shot also has 10 extra degrees of spread

Martial arts with overriding disarms will not trigger this

# Why is this good for the game?

[Inspired by this r/ss13 comic](https://www.reddit.com/r/SS13/comments/18ljzuy/the_traitor/?utm_source=share&utm_medium=web2x&context=3)

# Testing
Can't test by myself

# Changelog

:cl:  
tweak: Disarming someone holding a gun now has a high chance to force them to fire
/:cl:

### CODE REVIEW

**Comment by Beeper-Skeeper** [comment]
this is funny and all but imagine tactically shoving someone to waste their ammo

**Comment by 00ze-cyclone** [comment]
> this is funny and all but imagine tactically shoving someone to waste their ammo

They would generally be already aiming at you if you have a reason to shove them so you’ll just get shot, not really a waste

**Comment by azzzertyy** [comment]
way too common

**Comment by Therandomhoboo** [comment]
I would rather the chance be lowered because this can just screw over CQC antags and any other melee combo antag. It is annoying and it makes sense the gun would go off but the chance is too high to get potentially blasted in the face with a ton of damage.

**Comment by cowbot92** [comment]
make the chance higher

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
what's the worst that could happen

**Pull request merged**
