### PR TITLE
permabrig toilet now starts open

### PR DESCRIPTION
**Pull request by boodaliboo**
theos is doing perma nerfs i do perma buffs
this pr allows you to hide shit on the toilet roundstart
#### Changelog

:cl:  

tweak: permabrigs toilets cistern is open roundstart

/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
perma = permanent

i'd rather have perma be difficult to escape from than have sec mains blast the heads off of people when they escape from perma since its easy as shit to escape from

**Comment by boodaliboo** [comment]
> perma = permanent
> 
> i'd rather have perma be difficult to escape from than have sec mains blast the heads off of people when they escape from perma since its easy as shit to escape from

this doesnt help anyone escape this allows you to hide a singular item in the toilet

**Comment by ghost** [comment]
So if it doesn't buff anything and you're only doing it because theos, does this count as a buff spite PR?

**Comment by boodaliboo** [comment]
> So if it doesn't buff anything and you're only doing it because theos, does this count as a buff spite PR?

yes

**Comment by Moja10** [comment]
I like this PR my dude but this doesn't help the server increase RP. The opposite of "RP" is "PR." Please consider medRP next time.

**Review by patpol4 — APPROVED** [review]
Literally just a toilet that you can store small items in, ready to merge after https://github.com/yogstation13/Yogstation/pull/10632

**Pull request merged**
