### PR TITLE
Paramedic Hardsuit 2: Monstermos Compensation Edition

### PR DESCRIPTION
**Pull request by Nickvr628**
Recreated at the request of Smudgels and others. Monstermos means the station lacks air a lot more than normal, and paramedics cant rescue people if they die from a vacuum. Hence the need for their spacesuit. The design is based on the Cyberpunk 2077 Trauma Team suits, who are cool future paramedics.

A new Paramedic Hardsuit is available to paramedics. Designed for when paramedics have to go to a more dangerous than normal location to save people, like space, the front line of a blob fight, or Reebe. Has slightly better armor than the normal medical hardsuit, but does not have virus or rad protection. 

EDIT: The red cross has been replaced with a blue cross for regulatory compliance. 
image

image

:cl:  
rscadd: A hardsuit for Paramedics. Has slightly better armor than the medical hardsuit but loses virus and rad protections. Good for rescuing people from dangerous situations
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
It shouldn't loose virus protection, all space suits have virus protection, they're an entirely separate environment that a virus can never touch else it isn't a functional space suit

**Comment by boodaliboo** [comment]
its illegal to have a red cross

**Comment by Moja10** [comment]
Powercreep. Any sane AI or Captain or HoP would see a reason to let a paramedic into EVA, he could even show the handheld crew monitor/tracker to show that someone is clearly dead in space to be let in. Not to mention that these are the only suits that defy normal suit mechanics of being in a secure suit storage with all the features that come with those, rather they are just shoved into a locker. If this PR was to go through, I would prefer a new room was somehow created in EVA specifically for paramedics to enter, with these suits. Or a personal room in medbay, dedicated to these suits. I know there's not a lot of room, but this is just how every other suit in the game works, they always have dedicated suit storage in a dedicated room.

**Comment by Nickvr628** [comment]
I can change the red cross easily enough. The hand and feet accents are staying red though.

**Comment by Marmio64** [comment]
how about make the paramedic space suits be specifically just for rescuing people from space, and have no actual protection, nor flash protection, cause this sounds like powercreep tbh.

**Comment by Nickvr628** [comment]
> how about make the paramedic space suits be specifically just for rescuing people from space, and have no actual protection, nor flash protection, cause this sounds like powercreep tbh.

That is just a medical hardsuit or EVA suit. Also, this has no flash protection. The armor isn't that much better than other hardsuits, BTW.

**Comment by Nickvr628** [comment]
It has less armor than many of the hardsuits, in fact.

**Comment by Hopekz** [comment]
This can just be a regular suit with a sprite change and be fine.
Why a "hardsuit" with armor and different protections?

**Comment by Nickvr628** [comment]
I am confused by what you are asking for. Do you want it to be like the miner exploration suit thing? Because the whole point is it being spaceproof. If people don’t think it looks enough like a hardsuit, I can just give it a fluff name like “Paramedic Hazard Suit”.

**Comment by Hopekz** [comment]
> I am confused by what you are asking for. Do you want it to be like the miner exploration suit thing? Because the whole point is it being spaceproof. If people don’t think it looks enough like a hardsuit, I can just give it a fluff name like “Paramedic Hazard Suit”.

I fully agree that the paramedic needs a space proof suit.
That is my main question is this: Why does he need a "hardsuit"?

It does 2 things:
- Makes it a valuable item so it is now more sought after than regular space suits (more people will steal this
- Makes it a counter item to playstyles such as chemists, gangs (since they can't get stabbed through a hardsuit) etc. You are giving this "hardsuit" unintentional strong characteristics when your intent is to make it only space proof.

side note:
- Even adding it as a hardsuit and removing all armor makes it more sought after vs the regular suit as this is a 1 piece (helm built-in) vs a more inconvenient 2 piece space suit.

**Comment by Nickvr628** [comment]
The hardsuit aspects of it are because paramedics are supposed to be mobile rescuers getting people out of dangerous situations and taking them to medbay. Thus, it is reasonable both gameplay and lore wise that they are a bit more armored than a standard medical hardsuit, but are still less armored than proper "combat" hardsuits by a large margin. 

In situations like clock cult attacks, blob fights, nuke ops, and many other dangerous group activities, a robust paramedic can make a huge difference. But currently, they are neutered by the fact that the station ends up without air very rapidly meaning they can't actually go rescue anyone. 

Plus, it adds a cool aspect to the paramedic job that differentiates them from doctors more.

**Comment by Nickvr628** [comment]
The red cross has been removed, and replaced with a blue cross. 
image

**Comment by Hopekz** [comment]
I support paramedics having space protection via a spacesuit. That is a good idea in my opinion.

I do not like them having a hardsuit with armor (syringe, gang protection etc) + armor values + 1 piece so if that part changes you'll get my +1

**Comment by Smudged** [comment]
> Powercreep. Any sane AI or Captain or HoP would see a reason to let a paramedic into EVA, he could even show the handheld crew monitor/tracker to show that someone is clearly dead in space to be let in. Not to mention that these are the only suits that defy normal suit mechanics of being in a secure suit storage with all the features that come with those, rather they are just shoved into a locker. If this PR was to go through, I would prefer a new room was somehow created in EVA specifically for paramedics to enter, with these suits. Or a personal room in medbay, dedicated to these suits. I know there's not a lot of room, but this is just how every other suit in the game works, they always have dedicated suit storage in a dedicated room.

I'd be nice to have at the very least, a small side room in EVA for a suit storage to exist, I know KTL was talking about adding it in Waaayyy long ago, when this PR first existed, but that was before it got denied. Also, I think making it a little more special like giving it a suit storage (VG does this by just having a suit storage unit inside their prep-rooms) makes sense.



> I support paramedics having space protection via a spacesuit. That is a good idea in my opinion.
> 
> I do not like them having a hardsuit with armor (syringe, gang conversion protection etc) + armor values + 1 piece so if that part changes you'll get my +1

Nick did say he was only adding *minor* armour, which, if anything protects them vaguely against space-carp and it makes sense. Now, I still do agree, that the suit should still be vulnerable to the usual, gang-conversion, syringes, but also be sealed like yacabo said to viruses, which would make sense.

With what you said too Robert, just call it "The Paramedic Hazard Suit" the "hard" part of it was if anything just a holdover because (well to me it sounded cool), if we wanted to make it more serious, or lessen confusion to any other suits, just call it the "Paramedic Hazard Suit"

**Comment by Marmio64** [comment]
Literally no reason for paramedics to get armored hardsuits, if they get suits at all it should have no armor and just be for emergency rescue. No flash resistance and armor but very little slowdown would be great for paramedics, especially since paramedics aren't supposed to be fighting or taking any hits.

**Comment by maxion12345** [comment]
Pretty sure softsuits are also considered pen/syringeproof due to the thick fabric required for like, you know, space. I think paramedics should just have a reskinned EVA suit, or something of the sort. No need to make it fancy for them, although the color and cross look nice

**Comment by TheGamerdk** [comment]
It looks like those mermaid suits you see in movies

**Comment by BOBsHERE** [comment]
Didnt we add some type of paramedic space suit at one point? What happened to it? I like the idea of the paramedics having a shitty space suit that doesnt add armor/flash resistence/stab proofing.

**Comment by Nickvr628** [comment]
Nah it never got merged, this is a redo of that PR.

**Comment by BOBsHERE** [comment]
If you really want to avoid power creep, make the suits have a limited time they can be in space before starting to take damage. Not crazy shirt, but no permanent spacing the station or sitting out in space.

**Comment by overlord12345** [comment]
wheres the visor though

**Comment by MegaEmpirical** [comment]
Yessss

**Comment by Smudged** [comment]
> If you really want to avoid power creep, make the suits have a limited time they can be in space before starting to take damage. Not crazy shirt, but no permanent spacing the station or sitting out in space.

I think that defeats the purpose of having a suit like this in the first place, again, I think because of the massive change that monstermos brought, this IS a nessasary addition. 

Marimio makes a good point, the suit might want to have some level of slow down to make it worse in combat situations, but ATLEAST make it slightly armoured, be pennable, and also convertable. 

And when I say slightly we can just make it SO LITTLE, this puts the responsability to the paramedic as to not abuse the suit since it's for their *now* very dangerous job.

**Comment by maxion12345** [comment]
Why does it need to be pennable? It's a fucking spaceprood suit. You gonna make engineer hardsuits pennable because they also walk around with em?

**Comment by Smudged** [comment]
> Why does it need to be pennable? It's a fucking spaceprood suit. You gonna make engineer hardsuits pennable because they also walk around with em?

Everybodies just complaining that it just *can't* be hard, Because powercreeep? Even though Paramedics... by all intents and purposes should have a hardsuit, I think every other station, or well, baycode for sure, has *I think* a hard space suit. 

I mean it comes down to how it will vibe with paramedics, this IS a nessasary tool now, before it might have been harder to justify.

**Comment by OppressedCactus** [comment]
I am tired from dying to monstermos while trying to save people as paramedic. I like this idea.

**Comment by Ktlwjec1** [comment]
merge conflict this is so sad

**Comment by Nickvr628** [comment]
Fucking hell this is why we merge PRs in the order they are made, so we don't have old PRs be broken because someone wanted to speedmerge a sprite change to the captain's carapace.

/salt

**Comment by MegaEmpirical** [comment]
Bring me the head of the one that has fucked us.

**Comment by Nickvr628** [comment]
See #8693 for new merge conflict free PR

**Pull request closed without merging**
