### PR TITLE
Adds Wall Rechargers

### PR DESCRIPTION
**Pull request by JamieD1**
Adds wall rechargers, basically the same as normal rechargers without having to take up space!

eCN8lUVO6F

Add them to box for now, will add to rest of maps when the paperwork update hits, this is literally to make placing the new objects easier as well.

# Wiki Documentation

N/A

# Changelog

:cl:  
rscadd: Wall Rechargers, they are normal rechargers except they go on the wall, you place a gun into the item which is on the wall and it rechargers the internal power cell, whilst this is happening the sprite changes to indicate charging. Once it is done the sprite changes to a flashing yellow one which indicates the item you have placed has stopped charging and is ready to be picked up again. After which the sprite returns to a normal slow flashing red. They cannot currently be constructed, however they drop a normal recharger board IF deconstructed. They can also be upgraded like normal rechargers.
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Hugbox

**Comment by yacabo** [comment]
This is genuinely just a good idea with with no downsides

Good PR

**Comment by JamieD1** [comment]
> Hugbox

WHAT?!?

**Comment by Hopekz** [comment]
Your changelog is hot garbage.
You don't get any information from it at least put in where people can find them or that they're for guns

**Comment by adamsong** [comment]
> here people can find them or that they're for guns

They find them on the map, its not reasonable to list every location they are added to
What else might they be for? Borgs?

**Comment by N3D6** [comment]
Are they able to be constructed normally or are they just a roundstart spawn?

**Comment by Moggram** [comment]
> 
> 
> Are they able to be constructed normally or are they just a roundstart spawn?

From what I can see, no.

**Comment by Partheo** [comment]
Actually looks fine, but god yes like Hopek said, please improve your changelogs, they suck

**Comment by Hopekz** [comment]
> What else might they be for? Borgs?

That is literally the point I had no idea just reading the changelog.

There is no "map" to look at or picture to reference in the changelog there is just text that says "Wall Rechargers".

If a changelog exists for a player facing change it needs to be somewhat verbally descriptive because it is usually referenced in text form only.

**Comment by maxion12345** [comment]
taser icon???
taser being re-added soon??????????

**Comment by JamieD1** [comment]
I mean if you dont know what a normal recharger is im not going to spoon feed you what a wall version of it is..
But sure you want me to put dumb ass things in the changelog. Why not.

**Comment by burn1cycle** [comment]
As long as it doesn't replace anything it seems fine. I would hate to have to move those during blob.

 Also, could you integrate pepper spray chargers with it? So you aren't fighting for wall space in security locations.

**Pull request merged**
