### PR TITLE
moves the vault over to be next to the bridge, and aux tool storage as an extension of primary

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Moves vault over to be between cargo warehouse and the bridge, instead of being in primary tool storage.

Basically: breaking into the vault is incredibly easy as is, with almost noone noticing so here's to actually making the game a challenge

#### Changelog

:cl:  
tweak: vault and aux tool storage exchanged places
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Add pictures you nerd.

**Comment by Amelia0010** [comment]
@HomocidlePancakes look at mapdiffbot you nerd.

**Comment by MegaEmpirical** [comment]
Please add the removed space heater and light box to aux storage at least. The ones lost from destroying port emergency storage. Or in the new nook in maintenance where it used to be.

**Comment by Moja10** [comment]
Also the air canister!!!

**Comment by MegaEmpirical** [comment]
The can could easily be dropped into the maintenance bit.

**Comment by Amelia0010** [comment]
Right, that one disposals pipe was fixed. speaking of disposals, i'll do a complete redo of disposals to fix pipes -> walls

**Pull request merged**
