### PR TITLE
pAI Redux

### LINKED ISSUE #22094: pAI door jacking doesn't reset after door is opened
### Severity

Inconvenience

### Short Description

Door jacking doesn't cancel itself when the door has been opened, leading you to have to cancel it yourself.

### Reproduction

Be a pAI, try to door jack something with assistance from a person, put the cable in a second door to find it hasn't cancelled jacking after it finished jacking.

### Round ID

52648

### Test Merges

#21835

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Oblisk234**
Fixes #22094

# Document the changes in your pull request

Makes the pAI card insertable into PDAs again, as well as adding an updated interface for pAIs. Also fixes an issue with ghosts not being notified of pAI requests.

Enables usage of the Sunglasses image display, which seems to not have been available at all and left in the code.
image

For now, disables security and medical records modules as I can't figure out how to implement them currently.

Changes a lot of the underlying pAI code since it relied mostly on the HTML UI.

# Why is this good for the game?
While it may work, the original HTML panel is very crappy, and over 10 years old at this point. pAIs would benefit from a new UI that looks a lot better and is more functional.

Putting pAIs into PDAs kind of got phased out after modular PDAs became the standard and wasn't made compatible, and the feature was limited to old PDAs, which were removed recently. This PR reintroduces that feature, unless we switch to another different PDA system down the line and this happens again.

# Testing
pAI in PDA:
image

Directives tab:
image

Software download tab:
image
image

pAI card:
image
image
image
image

Interface module testing: (Please be mindful there is a lot of white and black at times because I needed to use two computers, one of which can't render SS13)
https://youtu.be/y9dr3LlzAek

# Wiki Documentation

Pretty sure this PR makes that one tip in Guide to Awesome Miscellaneous Stuff about inserting pAIs into PDAs accurate again.

# Changelog

:cl:
rscadd: pAIs now have a new interface to use. 
rscdel: Removed old pAI interface  
bugfix: Fixed pAI door jacking not auto-canceling after hacking completes
tweak: pAI cards have had their connectors changed, and can now fit in modular PDAs! 
/:cl:

### CODE REVIEW

**Comment by Scrambledeggs00** [comment]
Based TGUI PR

**Review by AMyriad — APPROVED** [review]
just path changes, map is gut

**Comment by neeshacark** [comment]
fucking F I N A L L Y

'while it may work'

NUH UH. a lot of shit is broken with the html ui. you have saved me

**Review by ToasterBiome — APPROVED** [review]
TGUI could use some work but it's good

**Pull request merged**
