### PR TITLE
Better techweb UI

### PR DESCRIPTION
**Pull request by monster860**
I'm not PRing this to TG, TG can go suck a dick.

image

If you dont like this UI you can use the Expert View.

:cl: monster860
add: The techweb UI looks better now. Click on a node to view it and alt-click to research it.
/:cl:

### CODE REVIEW

**Comment by Nirnael** [comment]
Can you still see the items each tech unlocks?

**Comment by monster860** [comment]
yeah just click on the tech and it will show you

**Comment by GenericDM** [comment]
looks good but travis angery

**Comment by monster860** [comment]
travis is angery because nich fucked up.

**Comment by GenericDM** [comment]
How is scrolling through the panel done?

**Comment by monster860** [comment]
you click and drag

**Pull request merged**
