### PR TITLE
makes dabbing prevent gaining special traumas so it can't be spammed for relatively safe trauma generation

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
tweak: you can no longer get special traumas from dabbing
/:cl:

### CODE REVIEW

**Review by monster860 — CHANGES_REQUESTED** [review]
jesus this is some horrifying levels of shitcode

**Comment by Darkstick** [comment]
"relatively safe trauma generation" is what I'll call high school now

**Comment by JamieD1** [comment]
Awaiting council vote on dabbing. Vote 722: pr: #9733

**Comment by SomeguyManperson** [comment]
I'll fine tune this if it passes the vote

**Pull request closed without merging**
