### PR TITLE
Disables Changeling and tatorling until someone fixes it

### PR DESCRIPTION
**Pull request by solwashere**
Changeling isn't working as intended, they get infinite chems now and can just spam abilities, I tried looking at whatever the problem was but I'm not smart enough to figure it out

# Spriting

# Wiki Documentation

# Changelog

:cl:  

tweak: Disabled changeling and tatorling

/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
fix it instead

**Comment by solwashere** [comment]
> fix it instead

 "tried looking at whatever the problem was but I'm not smart enough to figure it out"

**Comment by Aquizit** [comment]
> fix it instead

Bruh some of us don't know how to do that kind of advanced troubleshooting and it's not fun when people who do don't seem to want to bother.

This is why I made the PR to disable slings: I can map, I can do basic byond code but I can't figure out errors or read and parse error reports. People bitched and moaned and yet despite the outcry wow no one has bothered to try and fix it. I didn't want to take ticket after ticket after ticket of people wanting tokens because they rolled sling and veil didn't work again.

Why force people to deal with shit that is not fun because the people who have the talent and ability to fix it don't seem to care?

**Comment by ToasterBiome** [comment]
> Why force people to deal with shit that is not fun because the people who have the talent and ability to fix it don't seem to care?

If we disable ling it will never be fixed and never be re-enabled, look at slings and dspawn :)

**Comment by tattax** [comment]
it was already fixed a week ago i need someone to testmerge my pr

**Comment by tattax** [comment]
by week  i mean 3 days that is just how time goes sometimes

**Pull request closed without merging**
