### PR TITLE
adds a small ammount of damage that a few boots can do when used as melee

### PR DESCRIPTION
**Pull request by boodaliboo**
steel toed boots should do damage
every shoe but miners shoe does 3 damage and miners shoe does 6
#### Changelog

:cl:  
rscadd: Added damage to shoes
/:cl:

### CODE REVIEW

**Comment by johnnyboyz25** [comment]
Miners' boots have twice the damage of other boots? Sounds like this PR reinforces the miner powergaming meta.

**Comment by maxion12345** [comment]
>tfw jackboots don't so extra grey tide beating damage

**Comment by Marmio64** [comment]
going to have to take off peoples shoes in prison now, which adds extra pain, since they'll start smashing lightbulbs and windows otherwise

**Comment by GenericDM** [comment]
All boots should have the same amount of damage. You also forgot engineering workboots, which are presumably also steel toed.

**Comment by boodaliboo** [comment]
> All boots should have the same amount of damage. You also forgot engineering workboots, which are presumably also steel toed.

oh

**Comment by ynot01** [comment]
so now we have to strip their shoes when brigging someone? no fucking thanks

**Comment by ynot01** [comment]
so now we have to strip their shoes when brigging someone? no fucking thanks

**Comment by ynot01** [comment]
so now we have to strip their shoes when brigging someone? no fucking thanks

**Comment by GenericDM** [comment]
It's only boots.

**Comment by alexkar598** [comment]
This is stupid, stop slapping people with your shoes

**Pull request closed without merging**
