### PR TITLE
[wip] adds MAFIA mode to Yogstation13

### PR DESCRIPTION
**Pull request by swissloaf**
Ported from: https://github.com/tgstation/tgstation/pull/51788, https://github.com/tgstation/tgstation/pull/52065, https://github.com/tgstation/tgstation/pull/52066, https://github.com/tgstation/tgstation/pull/52168, https://github.com/tgstation/tgstation/pull/52243, https://github.com/tgstation/tgstation/pull/52244, https://github.com/tgstation/tgstation/pull/52083

Credit to tralezab for making the gamemode and EOBGames for an extra map

>it's town of salem, it's werewolf, it's mafia. you got people in a funny little town trying to find out who is killing people every night using special town powers.

more info here cause i copied the shit: [the wiki of mafia](https://wiki.yogstation.net/wiki/Mafia)

**this is a minimode for ghosts not real people**

#### Changelog

:cl:  
rscadd: Adds mafia minimode for ghosts  
imageadd: adds mafia sprites
wip: This is work in progress
experimental: This is experimental  
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
gross I hate it

**Comment by Partheo** [comment]
actually pretty neat tbh, I'm usually against ghost roles but this doesn't affect the round at all correct?

**Comment by swissloaf** [comment]
> actually pretty neat tbh, I'm usually against ghost roles but this doesn't affect the round at all correct?

noi

**Review by Partheo — APPROVED** [review]
sprites good

**Comment by swissloaf** [comment]
??? i didnt request one from asvee?

**Comment by boodaliboo** [comment]
finally

**Comment by tralezab** [comment]
greetings lads!

🎉 i'm adding last wills next pr, so make sure you grab that too. right now the game mechanics feel good, but balance is REALLY not town favored. gonna work on last wills, MAYBE turn on night kill-revealing and see how it feels. I got a lot of testing to do to find out what fairly tips it a bit more in town's favor

**Comment by Marmio64** [comment]
> greetings lads!
> 
> 🎉 i'm adding last wills next pr, so make sure you grab that too. right now the game mechanics feel good, but balance is REALLY not town favored. gonna work on last wills, MAYBE turn on night kill-revealing and see how it feels. I got a lot of testing to do to find out what fairly tips it a bit more in town's favor

you should add a warden role that is basically the jailor, they can put someone in jail at night and roleblock them, they can also execute them while they have them in jail, but if they execute a townie they should be demoted to assistant or be "perma'd" for their crimes, removing them from the game.

could also add a bartender role that is basically the veteran, can go alert 2 times and while alert they will shoot anyone who comes into their house, killing them.

just some ideas, but this is really cool to see anyhow

**Comment by swissloaf** [comment]
I am having trouble resolving these last 4 compiling errors

**Comment by alexkar598** [comment]
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

**Pull request closed without merging**
