### PR TITLE
New Map - YogsTheta [WIP]

### PR DESCRIPTION
**Pull request by athena413**
### Intent of your Pull Request

Adds a new, work-in-progress map.

Fills the population gaps between box and omega, since there's no real middle ground between those.

image
image
image
image
image
image
image
image
image

TODO:

- [x] Curator/Chaplain
- [x] Escape
- [x] Security
- [x] Supply
- [x] Arrivals
- [x] Science
- [x] Engineering
- [x] AI Sat
- [ ] Pass over and "populate" each area
- [ ] Maintenance
- [ ] Electrical cables
- [ ] Atmos pipes
- [ ] Whatever I forgot

#### Changelog

:cl:  
rscadd: New map
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
That's what meta is for and nobody wants to play on it lol

**Comment by Readystorm546** [comment]
> That's what meta is for and nobody wants to play on it lol

Fuck Meta

**Comment by MegaEmpirical** [comment]
Meta is for above Box.

Pubby was for between Box and Omega.

**Comment by Xoxeyos** [comment]
I suggest making outlines for each department, before going all out, so you know what you want to do, instead of doing one department at a time.

**Comment by patpol4** [comment]
I believe it is the easiest to make a station if you do the outlines and general locations of rooms and important machinery first. Think of the flow of the map, ways to get into rooms, places people will be often and use their workplace objects the most. Focus on the details like wiring or decals at the end. It looks nice but doesnt affect the turfs, you lay out everything in relation to the turfs windows and airlocks you place.

**Comment by TheLinuxOS** [comment]
I would also suggest that when doing the design for the atmos area that you make it similar in design to box's atmos as the one on meta is horrible layout in my opinion.

**Comment by alexkar598** [comment]
Oh, between box and Omaga, yeah that was pubby before it got killed kek.

To be honest, I dont see the need for yet another map that needs to be maintained while having no one voting to play on the damn map

**Comment by Firewolf34** [comment]
Why not call it YogsEta to go with the current naming-scheme. Eta is H in the Greek Alphabet.

**Comment by athena413** [comment]
> Why not call it YogsEta to go with the current naming-scheme. Eta is H in the Greek Alphabet.

OOH
i kinda like that, or YogsTheta

**Comment by patpol4** [comment]
Any work being done on this?

**Comment by patpol4** [comment]
Closing due to inactivity. rip

**Pull request closed without merging**
