### PR TITLE
Adds the beepeople (apids) race

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Credit: https://github.com/BeeStation/BeeStation-Hornet/pull/1571
Credit to thatguyother03 for the sprites

Adds the apids (beepeople) race to the game

image

> Existence
> Take more damage to flyswatters
> Take more damage to pestkillers
> Can breathe in pressures of 8kPA thanks to the many spiracles in their body (bullshit).
> The Apidite language, consisting of one syllable: Bzz.
> Apid Wings that permanently take up your neck slot and allow you to dash forward 4 tiles.
> Take twice as much heat, cold, burn, and stamina damage.

#### Changelog

:cl:  
rscadd: Adds apids to the game
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
image

**Comment by Partheo** [comment]
Did we even have flypeople

**Comment by swissloaf** [comment]
> Did we even have flypeople

ignore that lmao

**Comment by MrHorizons** [comment]
We do have flypeople, but not at roundstart.

Also, these look more like wasp-people than beepeople.

**Comment by Partheo** [comment]
Looks like a well made race, but I personally don't see why we need more races. There doesn't seem to be anything particularly interesting about it.

**Comment by swissloaf** [comment]
> Looks like a well made race, but I personally don't see why we need more races. There doesn't seem to be anything particularly interesting about it.

why do we need lizards, flypeople, plasmamen etc etc etc

**Comment by Partheo** [comment]
> 
> 
> > Looks like a well made race, but I personally don't see why we need more races. There doesn't seem to be anything particularly interesting about it.
> 
> why do we need lizards, flypeople, plasmamen etc etc etc

I'll ignore the fact that this is a retarded argument and give you an answer.
(we don't)

But we like them for a few reasons:
Lizards: Go-to "lesser" race niche, which just happens to be filled with unathi in this case. They're fairly ingrained in SS13 canon by this point. Plus they exist as a cousin species of the tribal ashwalker species on Lavaland.
Flypeople: we don't have these
Plasmamen: A genuinely unique race idea that can only really exist in SS13 lore. They are a creative idea with fairly radical changes in gameplay. They are realistically the one race from SS13 that have sci-fi merit beyond the game.
Phytosians: Botany and hydroponics are a fairly major component of SS13 gameplay and have been for a while. The inclusions of a plant-person race doesn't seem too far fetched. Also, fairly interesting consequences on gameplay.
Mothpeople: I have no idea where these came from, but they're probably the most alien looking of the races. People also really like their appearance.
Ethereals: Idk. Bright person. I could see these being removed.
Preternis: Cyborgs are absolute core to nearly any sci-fi work, these fit like a glove in SS13 lore. There's even an entire robotics gameplay feature in the game.

**Comment by Partheo** [comment]
Have some spine. I can be convinced. Besides, my word is not the final call on changes like this. These could still be a good race to add, just (IMO) not as a roundstart one.

**Comment by swissloaf** [comment]
> Have some spine. I can be convinced. Besides, my word is not the final call on changes like this. These could still be a good race to add, just (IMO) not as a roundstart one.

this pr is all yours now mate, i have no intention of adding the code to whatever bee toxin mutation thing you want

**Comment by swissloaf** [comment]
sorry if I came off hostile, its just that im genuinely uninterested in making a bee felinid toxin but ill help anyone restore the work i made in this pr

**Comment by Partheo** [comment]
> 
> 
> sorry if I came off hostile, its just that im genuinely uninterested in making a bee felinid toxin but ill help anyone restore the work i made in this pr

All good. I just think it'd be worth keeping the PR open so others could give their input if necessary.

**Comment by War-Tex** [comment]
NOT THE BEES! NOT THE BEES! AAAAHH!!!
https://www.youtube.com/watch?v=vhOgYN5SDQg

**Pull request closed without merging**
