### PR TITLE
Holoparasite price increased to 15

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Price was reduced since "you might get a bad one" but it's quite difficult to be bad at being the sentry gun from team fortress 2 (primary holoparasite usage)

# Spriting

# Wiki Documentation

uplink items page see title

# Changelog

:cl:  
tweak: holoparasite price increased from 12 to 15
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Honestly - disable holoparas for IAA.
Regular traitors using them is no foul, but IAA it's a meta strat.

**Comment by athena413** [comment]
fair pr

**Comment by Therandomhoboo** [comment]
Fair to increase it. Would say 14 would be best so you can choose some of the 6 tc options (like emagggg).

**Comment by Zer0Tactics** [comment]
Good pr, holopara being 15 makes it actually riskier to take, and considering the holopara already acts like:
A gun
An emag (by breaking doors down)
I think bringing it above 14 is good

**Comment by Therandomhoboo** [comment]
> Good pr, holopara being 15 makes it actually riskier to take, and considering the holopara already acts like: A gun An emag (by breaking doors down) I think bringing it above 14 is good

Yes because blasting a door which takes over 6 hits is just as effective as an emag?

**Comment by Moltijoe** [comment]
Balance Council:
>Holoparasites are rather strong so this is warranted, however melee holoparas might end up needing a buff in the future to counter-act this nerf

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
