### PR TITLE
mice changes + carrying animals (+monkeys)

### PR DESCRIPTION
**Pull request by tattax**
https://github.com/tgstation/tgstation/pull/49439

# Document the changes in your pull request

to grab a grabbable animal simply grab it passively then drag it to yourself,
this makes transporting animals easier for those who don't have cages or people who just want to play with pets

AbwuEYHY5Z

refactors the holding mob stuff using a bit of the code from the TG pr for it, adds some extra stuff and actually makes the mob on head sprite work.

refactors some stuff in dog code that was written poorly, makes eggdog a dog for carrying purposes

image

image

image

monkeys get nobreath when grabbed so as to not suffocate

-------------------------------------------------

additionally makes plaguerat not spawn roundstart and refactors some mouse code (it was meant to be a mouse PR first and still is)

# Wiki Documentation

mention you can grab pets and which ones, also plaguerat and stuff

:cl:  imsxz, Twaticus, tattax
rscadd: you can now grab animals by dragging them to you while they're grabbed
bugfix: carrying and carrying sprites now work,  cats and dogs now ACTUALLY see in the dark and eggdogs can now choose their name on sentience
tweak: plaguerat doesn't spawn roundstart anymore 
imageadd: added new icons for holding and equipping certain animals 
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
YES

**Comment by Chubbygummibear** [comment]
literally the best pr

**Comment by Moggram** [comment]
will this work on PAI?

**Comment by tattax** [comment]
> will this work on PAI?

yes

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
