### PR TITLE
Adds a new bag for miners and ashwalkers.

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Adds a new bag, craftable from some lava land fauna bits, that allows you to hold lots of lava land fauna bits...
makes sense right?

# Spriting
oh yeah I guess it needs a sprite. Damn...

# Wiki Documentation

new bag :)

# Changelog

:cl:  
rscadd: Adds the new bag
imageadd: added sprites for said bag
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
@KillerOrcaCora @cuackles

**Comment by cuackles** [comment]
No no no no no, those sprites won't do, please get another ones, I'm sure either orca or mako can help you with them, if i fix my PC in a timely manner i will try to help them improve it too

**Comment by KillerOrcaCora** [comment]
BAHAHHAHAHAHAHHAHAHAAAA WHAT THE HELL ARE THOSE!!! oh my god I’ll sprite some for you poor little thing

**Comment by JamieD1** [comment]
Awaiting sprites

**Comment by JamieD1** [comment]
Awaiting sprites check 2. @KillerOrcaCora

**Comment by JamieD1** [comment]
Reopen when you have the new sprites.

**Pull request closed without merging**
