### PR TITLE
20 TC Chaplain Item: 'Sect of the Blood Gods'

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
WARNING, THIS ISN'T NORMAL CULT, DON'T WORRY

Chaplain can, using the sect mechanics, start a blood cult after purchasing a 20 TC item.
Please suggest abilities/rites/sacrifice items, etc

TODO:

Sect Rites/Abilities:
- [ ] Conversion, max 3 'Acolytes' (Medical Doctor can get Brain Washing, this isn't that bad)
- [ ] Summon a Ritual Dagger (X favor)
- [ ] Summon a whetstone (X favor)
- [ ] EMP Spell. (X favor) Max 1, can only be gotten at the altar (No randomly drawing one up)
- [ ] Stun Hand. (X favor) Max 1, can only be gotten at the altar (No randomly drawing one up) (Less stun than normal cult hand, less mute duration) (Chaplain starts with one when he makes cult)
- [ ] Turn ONE of your Acolytes into a construct. Max 1. Does not reset on construct death. No wraith.
- [ ] Summon Altar. Create a new altar. (X favor)
- [ ] Summon Infernal Hemosapper (X favor) (Hook humans up to it, sucks their blood and gives favor. Does not suck enough blood to be lethal. Gives more favor than blood bagging them)

---HIJACK ONLY ITEMS RITES---
- [ ] Full cult gear. (X favor). Max 1 (For Chaplain), can be sharpened with whetstone.
End Game Abilities:
Mutually exclusive! 
- [ ] Apocalypse Rune. Requires 3 living Acolytes. Causes everyone to go bersek, like the blood contract. Risky, but deadly. Chaplain & Acolytes not affected. Each get a cult sword.
OR
- [ ] Infernal Juggernaut. Requires 3 living acolytes. Acolytes get sacrified. Chaplain gets moved into a Nar'Sie shell. Basically a stronger Juggernaut with the following abilities:
Regular Juggernaut Abilities
Goliath tentacles, but they look like the Juggernaut hand.
'Blood Storm' Fires a strong projectile in the direction the Chaplain is looking. High damage, high cooldown.

Sect Sacrifices:
- [ ] All Station Pets (X favor per)
- [ ] Chaplains targets (X favor in total. If multiple targets, split X favor between each sacrifice)
- [ ] TC (X favor per)
- [ ] Chaplains steal targets (X favor in total, if multiple, split X between each. Mark objective as complete)
- [ ] Acolytes. (X favor per) This reduces your max acolytes, so you can't just convert and sacrifice
- [ ] Blood bags. (X favor per)

Other Notes:
- [ ] Acolytes deconvertable with mindshields. Reset max acolytes to 3 on deconversion

#### Changelog

:cl:  
rscadd: Traitorious Chaplains can now start bloodcults!
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Rename it, this will be too confusing

**Comment by Bibby0110** [comment]
> Rename it, this will be too confusing

no

**Comment by patpol4** [comment]
nerd

**Comment by ynot01** [comment]
suggest using the draft feature for things like this

**Comment by Bibby0110** [comment]
> suggest using the draft feature for things like this

I forgot to press it, eat my pants

**Comment by Jarod1200** [comment]
I like this because now some greytide shouting RUNES IN MAINT might not actually mean its a blood cult.

**Comment by Hopekz** [comment]
Any big differences besides maybe not giving them the OP cult gear?
Usual conversion method?

**Comment by Bibby0110** [comment]
> Any big differences besides maybe not giving them the OP cult gear?
> Usual conversion method?

Mane I've said multiple times this isn't like bloodcult, so no.

**Comment by Marmio64** [comment]
Let them sacrifice plasteel for cult whetstones, get ritual daggers (for combat purpose only), and perhaps a EMP spell that you can only have one at a time of. (Traitors can buy a box of EMP grenades and like a 4 use EMP implant for like only 4 TC or even less,so this isn't OP)

**Comment by boodaliboo** [comment]
ahhaha it doesnt pass travis

**Comment by HomocidlePancakes** [comment]
Make the jugg as fast as a normal humie, or it will suck ass.

**Comment by Tipy1802** [comment]
Rip

**Comment by boodaliboo** [comment]
rip

**Pull request closed without merging**
