### PR TITLE
Removes "Tuvan Throat Signing" from the lobby music because its awful.

### PR DESCRIPTION
**Pull request by alexkar598**
What the fuck is this shit

https://www.youtube.com/watch?v=qx8hrhBZJ98

It's:
1) Awful
2) Not even credited properly

### CODE REVIEW

**Review by jcatjmeow — APPROVED** [review]

**Comment by jcatjmeow** [comment]
fuck this codeowner bullshit why cant i spedmerge wtffffffffffffffffffffffffffffffffffffff

-Jcat, Maintainer, 2021

**Comment by patpol4** [comment]
sad

**Comment by swissloaf** [comment]
a remnant of identification creative lead times that I hope will stay with partheo

**BabyYoda: Complaining about something in OOC and making a PR to remove it a few minutes later.**

**Comment by N3D6** [comment]
Yes

**Comment by UselessTheremin** [comment]
i mean sure its not terrible but how the hell does this suit space station 13? honestly an ss13 title screen isnt the place for it, does not even slightly match the other title musics.

**Comment by Moja10** [comment]
This was always a shit meme, thank GOD this is being removed.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
