### PR TITLE
ports Titanium Resprite from /tg/

### PR DESCRIPTION
**Pull request by nesisknesis**
https://github.com/tgstation/tgstation/pull/50454

image

#### Changelog

:cl:  Onule
imageadd: Recent changes in the manufacture of titanium sheets introduces a fresh new look! Expect your shuttles to look different.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
If you're planning to keep this PR open today for feedback I'll hop in to see how it looks in-game sometime today otherwise I am unsure.

**Comment by nesisknesis** [comment]
image

**Comment by ynot01** [comment]
heavily conflicts with the current artstyle

**Comment by nesisknesis** [comment]
ill be the judge of that

**Comment by deathslayer2481** [comment]
This is bad.

**Comment by Marmio64** [comment]
me no like

**Comment by Alexandria404** [comment]
doesn´t fit

**Pull request merged**
