### PR TITLE
Adds more music to the jukebox 

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request

Added the following songs to the jukebox
Simon Viklund - Break the Rules
Simon Viklund - DonAcDumb
Simon Viklund - Dead Man's Hand
Simon Viklund - Hot Pursuit
Simon Viklund - Razormind
OVERKILL Software - Nightclub music
OVERWERK - 1230
Carpenter Brut - Roller Mobster
Deadmau5 - Ghosts N Stuff
Caravan Palace - Lone Digger
IAMTHEKIDYOUKNOWWHATIMEAN - Run
Jasper Byrne - Miami
M.O.O.N - Hydrogen
M.O.O.N - Crystals
El Huervo - Daisuke
Noisestorm - Crab Rave
# Wiki Documentation

# Changelog
:cl:  
rscadd: Added more songs to the jukebox. Mainly from Payday 2, because Simon Viklund is a god among men.
rscadd: due to rampant lobbying from local defense contractors I am adding more hotline Miami songs
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
I'd suggest putting one song in at a time, for quality's sake.

**Comment by maxion12345** [comment]
> I'd suggest putting one song in at a time, for quality's sake.

17 pull requests coming right up

**Comment by JamieD1** [comment]
Problem is every song adds to the rsc file download size.

Can you try and reduce the file size as much as possible without sacrificing quality too much.

**Comment by maxion12345** [comment]
> Problem is every song adds to the rsc file download size.
> 
> Can you try and reduce the file size as much as possible without sacrificing quality too much.

can certainly try

**Comment by patpol4** [comment]
This is too many, I'd say keep crab rave and some hotline miami one

**Comment by JamieD1** [comment]
Still going to add 43 MB.. Could you half that somehow by removing some of the worst songs?

**Comment by maxion12345** [comment]
> Still going to add 43 MB.. Could you half that somehow by removing some of the worst songs?

what do you mean worst songs
they are all good songs

**Comment by patpol4** [comment]
Subjective, and adding this many means bloating the library

**Comment by maxion12345** [comment]
Can a get a hard size limit I should try to limit to? something like 30mb, etc?

**Comment by patpol4** [comment]
I really don't think this is a good idea with this many songs

**Comment by JamieD1** [comment]
> Can a get a hard size limit I should try to limit to? something like 30mb, etc?

25MB.

**Comment by maxion12345** [comment]
All Right: new strat. I'm going to compress all those OLD SONGS ASWELL!

after more compression, the total MB added is 27.254.
however, by compressing other songs I have removed 20.216MB

the total file size is 50.3MB



whereas on master it is currently 43.4



totaling an increase of only 6.9MB ( nice )

that gives us 18.1 MB of songs to add later (plenty with proper compression that I've only just now found)

**Comment by patpol4** [comment]
By adding songs in a batch like this we sacrifice quality for quantity, Xoxeyos is right.

**Comment by maxion12345** [comment]
> By adding songs in a batch like this we sacrifice quality for quantity, Xoxeyos is right.

These songs are both songs that I wanted to add, and other members asked me to add. They are all pretty good quality songs from popular games to boot, with a few ordinary songs tossed in.

basically: it's the jukebox, I and others wanted more songs, I made a pr to add these songs. You don't have to play them, or even like them. You can use the old songs if you want. Hell, we have space to spare after compressing the other files. If you want to request a song, now is the time.
 

But closing the PR based on the fact people wanted so many songs seems a bit dumb. Especially with the recent jukebox changes that make them more available then the old "did bartender roll disco bar"

As to why this PR was not atomized, there are a lot of songs. I could open a PR for each and every one, but opening 17 PRs in a row would probably be considered spam

**Review by JamieD1 — APPROVED** [review]

**Comment by patpol4** [comment]
goddamit

**Comment by maxion12345** [comment]
> goddamit

LETS BREAK THE RULES
AND REALLY PUT OUR BACKS INTO IT,
MAX OUT, PURSUE IT!
WHATS A BETTER TIME THAN NOW TO CROSS THE LINEEEEE

**Pull request merged**
