### PR TITLE
Revert "Light water"

### PR DESCRIPTION
**Pull request by Hislyna**
Reverts yogstation13/Yogstation#20178. There are so many issues with Light Water. For starters, noone will drink holy water because of the jitters. Secondly, have you tried to get favour with this sect? It was tested for a whole round with someone constantly getting damaged and healed inside of the chapel, 80 fucking points. 80. Fucking. Points. In. A. ROUND. You can literally throw some synthmeat on a table and have 1000 in 10 mins! Alongside this, you can literally just go puritarianism and heal better than old holy light (and clearly this pile of shite) sect did too. 

Light Water was just an Ided PR that made a couple players happy when it is worse for the game. If you wanna nerf holy light, make it heal less the higher HP the players at or put a HP cap on, but even then its fine. Med should be the fastest for heavy damage, but also to treat injuries, illness, toxins, rads, and revival, which it is. All Holy Light did was burns and bruises and did not heal to max, it would still be quicker to go to medical.

Changelog

🆑

tweak: Reverts Holy Light back to Holy LIGHT not fucking Water

/🆑

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
As long as the sect's favor gain is tied to directly healing people it will suck. It doesn't matter if it can heal 1 point or 100, it will produce a feeling of entitlement in the chaplain to personally heal any and all damage. This is what I am trying to avoid with the switch to holy water and its status effect. If the favor gain is low, it can be buffed, but I feel there is something up with this example, since in testing I was able to get around 50 favor just from making sure the sect worked (a process that takes at most 1-5 minutes).

Also, if you plan on calling it "holy light not holy water" you should rename the sect to "holy bible" because it has no reliance on light whatsoever

**Comment by Hislyna** [comment]
> As long as the sect's favor gain is tied to directly healing people it will suck. It doesn't matter if it can heal 1 point or 100, it will produce a feeling of entitlement in the chaplain to personally heal any and all damage. This is what I am trying to avoid with the switch to holy water and its status effect. If the favor gain is low, it can be buffed, but I feel there is something up with this example, since in testing I was able to get around 50 favor just from making sure the sect worked (a process that takes at most 1-5 minutes).
> 
> Also, if you plan on calling it "holy light not holy water" you should rename the sect to "holy bible" because it has no reliance on light whatsoever

It can only heal burns and brute. Its a none issue that made a few people cry.

**Comment by SomeguyManperson** [comment]
> Reverts #20178. There are so many issues with Light Water.

They can be addressed

> For starters, noone will drink holy water because of the jitters.

Jittering will only negatively effect people who have mood on. Unless you are injecting someone with over 10 units of holy water at a time, the remaining effects won't be a problem. If the dizziness at 10 units is horrible, which it could be, it can be addressed.

> Secondly, have you tried to get favour with this sect? It was tested for a whole round with someone constantly getting damaged and healed inside of the chapel, 80 fucking points. 80. Fucking. Points. In. A. ROUND.

During testing, I was able to gain 80 favor in a couple minutes using sutures and surgery. If it took 2 hours to get 80 points, it is likely someone fucked up. Regardless, the favor gain speed was in fact significantly nerfed (1:1 with the increase of healing, or 20% of whatever is healing the person, rather than 1:1 of the 40 points a bible bash heals), and could be doubled or tripled if it is unreasonably slow.

> You can literally throw some synthmeat on a table and have 1000 in 10 mins!

The sect that does this only gains access to a knife, and a golem transformation for their favor. Not multiple actually useful medical-adjacent items.

> Alongside this, you can literally just go puritarianism and heal better than old holy light (and clearly this pile of shite) sect did too.

How often do you see someone sectless/puritan actually bible heal someone? Now how often do you see them not get the shit kicked out of them immediately after, because the heal is unreliable and causes brain damage on failure? The default heal provides nothing to the chaplain, and can be detrimental to the person being healed, so it is rarely used to actually help people outside of extreme emergencies like plasmafloods. The heal is certainly better, but it isn't _incentivized_ or _required for progression_. If you want a better example, use the capitalist sect, which is actually awful and should be removed outright.

> Light Water was just an Ided PR that made a couple players happy when it is worse for the game.

I am improving the sect by making it more healthy for the game, and trying to incentivize cooperation over job theft. We don't have a sect that gains favor based on power (incentivizing the chaplain to make their own engine), or one that gains favor by sacrificing antags (incentivizing the chaplain to become a security officer)

> If you wanna nerf holy light, make it heal less the higher HP the players at or put a HP cap on, but even then its fine.

This won't help. As long as job theft is REQUIRED to gain favor, there will be job theft. At best, it damages the sect's utility significantly.

> Med should be the fastest for heavy damage, but also to treat injuries, illness, toxins, rads, and revival, which it is.

I don't believe the chaplain should be allowed to shove medical out of healing all common injuries and relegating an entire department to niche and rare damage types because they need to do so for their job

> All Holy Light did was burns and bruises and did not heal to max, it would still be quicker to go to medical.

This is false, and I'm not sure how someone can come to the conclusion that instantly healing 40 points of damage with no cost to any party and with no special requirements is slower than walking to medical

**Comment by Hislyna** [comment]
> > Reverts #20178. There are so many issues with Light Water.
> 
> They can be addressed
> 
> > For starters, noone will drink holy water because of the jitters.
> 
> Jittering will only negatively effect people who have mood on. Unless you are injecting someone with over 10 units of holy water at a time, the remaining effects won't be a problem. If the dizziness at 10 units is horrible, which it could be, it can be addressed.
> 
> > Secondly, have you tried to get favour with this sect? It was tested for a whole round with someone constantly getting damaged and healed inside of the chapel, 80 fucking points. 80. Fucking. Points. In. A. ROUND.
> 
> During testing, I was able to gain 80 favor in a couple minutes using sutures and surgery. If it took 2 hours to get 80 points, it is likely someone fucked up. Regardless, the favor gain speed was in fact significantly nerfed (1:1 with the increase of healing, or 20% of whatever is healing the person, rather than 1:1 of the 40 points a bible bash heals), and could be doubled or tripled if it is unreasonably slow.
> 
> > You can literally throw some synthmeat on a table and have 1000 in 10 mins!
> 
> The sect that does this only gains access to a knife, and a golem transformation for their favor. Not multiple actually useful medical-adjacent items.
> 
> > Alongside this, you can literally just go puritarianism and heal better than old holy light (and clearly this pile of shite) sect did too.
> 
> How often do you see someone sectless/puritan actually bible heal someone? Now how often do you see them not get the shit kicked out of them immediately after, because the heal is unreliable and causes brain damage on failure? The default heal provides nothing to the chaplain, and can be detrimental to the person being healed, so it is rarely used to actually help people outside of extreme emergencies like plasmafloods. The heal is certainly better, but it isn't _incentivized_ or _required for progression_. If you want a better example, use the capitalist sect, which is actually awful and should be removed outright.
> 
> > Light Water was just an Ided PR that made a couple players happy when it is worse for the game.
> 
> I am improving the sect by making it more healthy for the game, and trying to incentivize cooperation over job theft. We don't have a sect that gains favor based on power (incentivizing the chaplain to make their own engine), or one that gains favor by sacrificing antags (incentivizing the chaplain to become a security officer)
> 
> > If you wanna nerf holy light, make it heal less the higher HP the players at or put a HP cap on, but even then its fine.
> 
> This won't help. As long as job theft is REQUIRED to gain favor, there will be job theft. At best, it damages the sect's utility significantly.
> 
> > Med should be the fastest for heavy damage, but also to treat injuries, illness, toxins, rads, and revival, which it is.
> 
> I don't believe the chaplain should be allowed to shove medical out of healing all common injuries and relegating an entire department to niche and rare damage types because they need to do so for their job
> 
> > All Holy Light did was burns and bruises and did not heal to max, it would still be quicker to go to medical.
> 
> This is false, and I'm not sure how someone can come to the conclusion that instantly healing 40 points of damage with no cost to any party and with no special requirements is slower than walking to medical

Just change how the job gets favour and keep the rest as it was then if thats your main arguement. Like I said, all it does is brute and burn, not reviving, not toxins, surgery, rads, revival. Make a different sect instead of reworking one that worked perfectly fine as it did before. It never took away from medical, theres just a minority of whingers.

**Comment by SomeguyManperson** [comment]
> Just change how the job gets favour and keep the rest as it was

That is LITERALLY WHAT I DID

**Comment by Hislyna** [comment]
> > Just change how the job gets favour and keep the rest as it was
> 
> That is LITERALLY WHAT I DID

No, you made the favour almost impossible to get, and made the healing impossible to do.

**Comment by TaelynTheLost** [comment]
Holy Light was the one sect that worked really well and was fun.  It wasn't game-breaking in the slightest.  Favor even felt at a good rate to me.  There are plenty of bigger issues to focus on than something that for the most part was in a good place.

**Comment by SomeguyManperson** [comment]
> Holy Light was the one sect that worked really well and was fun. 

The favor rewards are all cohesive and the favor gaining by healing works well in a vacuum, but in practice it just means the chaplain stands outside medical intercepting patients, or chases injured people because they NEED to to get favor. The chaplain, of course, doesn't notice this, because they are focused on playing the game the way the game tells them to play it. The person playing medical just to hug lizards for 2 hours won't notice, because healing people is an unwelcome pause in their routine.

**Comment by SomeguyManperson** [comment]
Also, I'd like to know where this "80 favor in one round" comes from. Which round? How were they being healed? Considering the favor gain is entirely based on the amount of healing applied, you could have "tested" it with a slow method of healing, found that a fraction of slow is also slow, and just gone "wow this sucks"

**Comment by TaelynTheLost** [comment]
By the end of the round, I think I actually had about 140 something.  "Almost" enough to get a med hud.

**Comment by TaelynTheLost** [comment]
> > Holy Light was the one sect that worked really well and was fun.
> 
> The favor rewards are all cohesive and the favor gaining by healing works well in a vacuum, but in practice it just means the chaplain stands outside medical intercepting patients, or chases injured people because they NEED to to get favor. The chaplain, of course, doesn't notice this, because they are focused on playing the game the way the game tells them to play it. The person playing medical just to hug lizards for 2 hours won't notice, because healing people is an unwelcome pause in their routine.

I work WITH med, not against them.  I tend the light injuries, or keep someone stable until they can get to med.  Or heal them in places where med can't (in combat).  Chem is able to do FAR more to stop people from getting to the doctors than Holy Light ever could.  With chem, I can make a single patch that heals you to full of all damage types, or even resurrect you.  Chem doesn't need to get favor the whole shift to bring back one person either.  They can do it in mass, and pretty early in the shift if lucky.  Holy Light is not the issue.

**Comment by Bibby0110** [comment]
48 hour rule

**Comment by Hislyna** [comment]
Its been 48 hours

**Comment by Bibby0110** [comment]
> Its been 48 hours

not yet

**Pull request closed without merging**
