### PR TITLE
Alternate techpriest robes

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
changes the sprite of the techpriest and add 2 to the robo vendor

# Wiki Documentation
none
# Changelog
changes the sprite of the techpriest and add 2 to the robo vendor
2021-12-06 21_28_22-Space station 13_ Festive Province India
2021-12-06 21_28_32-Space station 13_ Festive Province India
2021-12-06 21_28_13-Space station 13_ Festive Province India
:cl:    
tweak: tweaked a few things    
imageadd: added some icons and images  
imagedel: deleted some icons and images  
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Gonna make em darker so they look better

**Comment by Marmio64** [comment]
does this remove the old ones?

**Comment by cuackles** [comment]
> does this remove the old ones?

it would  but it will also stay closed until i make the new sprite good enogh to replace the old one with the lest quantity of poeple displeased

**Comment by Marmio64** [comment]
> > does this remove the old ones?
> 
> it would but it will also stay closed until i make the new sprite good enogh to replace the old one with the lest quantity of poeple displeased

why not just keep both?

**Pull request closed without merging**
