### PR TITLE
Adds object sprites to CTF armor

### LINKED ISSUE #22801: CTF hardsuits have no item sprite
### Severity

Low

### Short Description

It has a sprite for when worn but not in hand as an item

### Reproduction

image
image

### Round ID

54420

### Test Merges

#22095, #22683, #22796

### BYOND Username

Oblisk234

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Scrambledeggs00**
# Document the changes in your pull request

This just adds the CTF armors' south sprites as their object sprites. Before this, they had no sprites as stated in issue #22801.

# Why is this good for the game?

Fixes #22801

# Testing

All of the object sprites show correctly and the mob sprites stay as they should be.
Screenshot (278)
Screenshot (279)
Screenshot (280)

# Spriting

As said in the description, the sprites are just the armor's south facing sprites, though I moved the suits' boots to be inline with other suit object sprites. You can see them in the testing section.

# Changelog

:cl:
bugfix: Solved issue #22801
imageadd: Added object sprites to CTF armors  
/:cl:

### CODE REVIEW

**Comment by Oblisk234** [comment]
May want to include specifically "Fixes #22801" so it'll be autoclosed.

**Comment by Scrambledeggs00** [comment]
> May want to include specifically "Fixes #22801" so it'll be autoclosed.

Anywhere specific I would include it? Can I just put it anywhere in the PR description?

**Comment by Oblisk234** [comment]
> > May want to include specifically "Fixes #22801" so it'll be autoclosed.
> 
> Anywhere specific I would include it? Can I just put it anywhere in the PR description?

Anywhere works I think, although I usually just put it at the top.

**Comment by Scrambledeggs00** [comment]
> > > May want to include specifically "Fixes #22801" so it'll be autoclosed.
> > 
> > 
> > Anywhere specific I would include it? Can I just put it anywhere in the PR description?
> 
> Anywhere works I think, although I usually just put it at the top.

Thanks :]

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
