### PR TITLE
Chocobo

### PR DESCRIPTION
**Pull request by alexkar598**
### Intent of your Pull Request

I got asked to make this.
#### Changelog

:cl:  
rscadd: Chocobos are now in the game! You can spawn them with xenobiology gold slime or order it via cargo for 8000 points.You can ride and control them all while looking....special.
/:cl:

Screenshots:
https://i.imgur.com/0ln1V4M.gif

chococolors

image

Orderable via cargo for 8000 points
Spawnable via gold slime friendly reaction
You can ride them
Drops 2 meat on death
No corpse because no dead sprite

### CODE REVIEW

**Comment by alexkar598** [comment]
Il add a dead chocobo sprite when i get to my coding computer

**Comment by Moja10** [comment]
I don't think the sprites fit into the game at all, and the game's style and items don't necessarily translate into "This is a thing from another game/universe/show just hamfisted into the game." If they were resprited to not look 100% like chocobos, fit into the universe of this game, had any explanation other than "It's chocobos from final fantasy" then I could see this being potentially good. I don't want to just diss this PR but it needs more to fit in.

**Comment by thehighwayman** [comment]
moja is right make this fit better and I'd allow it

**Comment by alexkar598** [comment]
Chocobos now show a corpse on death and unbuckle any mob on it and is unridable until revival(duh)

image

Also they now have 60 hp on the request of @fluffe9911

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
[02:15] SLRaptor (Oakboscage): @Merry Nichmas its fine it just looks like dumb fun
[02:17] Ktlwjec ifunny.c☻: chocobo should be admin spawned imo, don't fit in in the slightest
[02:17] Ktlwjec ifunny.c☻: or some weird shit to get when emagging cargo
[02:17] Merry Nichmas: fight fight fight fight
[02:19] SLRaptor (Oakboscage): No
[02:19] Ktlwjec ifunny.c☻: ^
[02:19] Merry Nichmas: :thinking:
[02:19] Merry Nichmas: okay so I'll tell him lock it emagging?
[02:19] Ktlwjec ifunny.c☻: Sure

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
