### PR TITLE
using a nice tool gives you a small mood boost

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

trying to add more flavor

using anything with a toolspeed under 1 counts as a "nice tool"

gives you +2 for 2 minutes
# Changelog

:cl:  
rscadd: Small mood buff for using nice tools
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
"Nice tool" man what

**Comment by Yarinoi** [comment]
what a nice tool

i love tools

**Comment by MajManatee** [comment]
now I know when someone says "You're a tool" they really mean I make them happy.

**Review by ynot01 — APPROVED** [review]
I hate this game

**Pull request merged**
