### PR TITLE
bigotry rule: A new hope!

### PR DESCRIPTION
**Pull request by Amelia0010**
completely forgot about this

### CODE REVIEW

**Comment by Alexandria404** [comment]
What does that do.
I get the meatball thing, which I personally find stupid, but what does the speech thing do.

**Comment by ghost** [comment]
there's things like brain damage that replace random words, nich just replaced any of the /mean/ words

**Comment by Amelia0010** [comment]
yeah but they're **mean**

**Comment by ThatLing** [comment]
hugbox

**Comment by ThatLing** [comment]
oh god i should've squashed that

**Pull request merged**
