### PR TITLE
Removes mediator from roundstart AI.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Lawset is highly vague, unhelpful to crew and not fun to play.
Does not have anything to do with harm, reducing harm, helping dead people or anything of the sorts.
Causes issues when implementing it in-game, as, AI's that do all the things listed are not fun to play with or against, and is incredibly hard to interpret in most situations. Just use asimov, it does everything this wants to do but better.

# Why is this good for the game?
As stated in the previous paragraph.

# Testing
Does not need.

# Changelog
:cl:  
rscdel: Mediator is no longer roundstart.
/:cl:

### CODE REVIEW

**Review by Moltijoe — CHANGES_REQUESTED** [review]
modify the number rather than deleting the entire config
also leave the ion law number alone if you're just touching roundstart

**Comment by azzzertyy** [comment]
> modify the number rather than deleting the entire config also leave the ion law number alone if you're just touching roundstart

fixed woops

**Review by Moltijoe — APPROVED** [review]
code checks out

**Comment by ju45he** [comment]
Can you tell us what the mediator lawset is for those of us who are too lazy to go to the wiki?

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
