### PR TITLE
Engineering hardsuit gets full rad resistance

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

atmos hardsuit gets full fire + heat resistance... engi hardsuit gets 75% rad resistance? what a joke.
the singularity got buffed so this is required to safely go near it

# Spriting

# Wiki Documentation

change the armor values in the hardsuit page

# Changelog

:cl:  
tweak: Engineering hardsuit gets full rad resistance
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
but clearly engineers should just be REQUIRED to play one of the rad immune races to play engineering

**Comment by Simplehorror** [comment]
ikr

**Comment by Moltijoe** [comment]
rad resistance is often a binary anyways, either you're immune or you're slowly dying

**Comment by Moltijoe** [comment]
new idea, having rad immunity on clothing protects from a radstorm

scratch that, apparently it already does that

**Comment by N3D6** [comment]
Good change, had to fix something on the singulo the other day as a human engi and got mutation level rads from it

**Comment by ShoziOffical** [comment]
good change

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
Yeah, needing to either be a rad immune species, or have the CE hardsuit to work on a singulo is kinda dumb

**Pull request merged**
