### PR TITLE
Fixes ghosts being able to manipulate machine boards

### PR DESCRIPTION
**Pull request by Mqiib**
# General Documentation

### Intent of your Pull Request

Ghosts can no longer put machine boards in machines

### Why is this change good for the game?

Ghosts shouldn't be able to do that

### What general grouping does this PR fall under? 

Bug fix

# Changelog

:cl:  

bugfix: Removed ability for ghosts to build machines

/:cl:

### CODE REVIEW

**Comment by ChesterTheCheesy** [comment]
bro thats a lot of commits lmao

**Review by SomeguyManperson — CHANGES_REQUESTED** [review]
put the check at the beginning of the proc so it'll catch anything else

**Comment by Mqiib** [comment]
> put the check at the beginning of the proc so it'll catch anything else

👍

**Comment by Bibby0110** [comment]
What exactly is happening here?
I'm guessing ghosts can drag adjacent boards onto the frame?

**Review by SomeguyManperson — APPROVED** [review]

**Comment by SomeguyManperson** [comment]
yes

**Pull request merged**
