### PR TITLE
Remove debug hardsuit slowdown

### PR DESCRIPTION
**Pull request by adamsong**
# General Documentation

### Intent of your Pull Request

Removes the slowdown from the debug hardsuit

### Why is this change good for the game?

The debug hardsuit has the same slowdown as the regular space suit, which is annoying when testing. This removes that

# Changelog

:cl:   
tweak: Removes the slowdown from the debug suit
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
admin power creep.

**Comment by UselessTheremin** [comment]
its for debug purposes, id recommend just setting it to 0 for testing speed changing things, as you can easily varedit the slowdown if need be

**Comment by patpol4** [comment]
0 makes more sense yeah, if you can spawn in as one, you can varedit it

**Comment by adamsong** [comment]
I've set it to 0

**Review by Cartlord — APPROVED** [review]

**Pull request merged**
