### PR TITLE
adds gigadrill to mining vendor for 15000  mining points

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
alex quit working on xenoarch but i dont want such a cool item to go waste so now you can buy it at a mining vendor for 15k mining points

:cl:  
rscadd: Added gigadrill to mining vendors
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
HAHAHAHAHHAHAHA, no

**Comment by alexkar598** [comment]
The giga drill is stupid OP, can level lava land within minutes and doesn't have any downsides 

The reason it is this OP because it was xenoarch end game loot that's hard to get

**Comment by boodaliboo** [comment]
Miners can already do the same but I’ll make it 15k points then

**Comment by boodaliboo** [comment]
> The giga drill is stupid OP, can level lava land within minutes and doesn't have any downsides
> 
> The reason it is this OP because it was xenoarch end game loot that's hard to get

if you get 15k points your done mining at this point anyways

**Comment by Codeatmos** [comment]
What is the xenoarch since alexkar seems hellbent on snowflake secret arch(dont look!!!)

Yeah neverfucking mind
>Methspeed
>3x3
>15k points
You could literally flatten all of lavaland with this,as a matter of fact you probably could assuming you mine what,100 rocks per second?

**Comment by boodaliboo** [comment]
> What is the xenoarch since alexkar seems hellbent on snowflake secret arch(dont look!!!)
> 
> Yeah neverfucking mind
> 
> > Methspeed
> > 3x3
> > 15k points
> > You could literally flatten all of lavaland with this,as a matter of fact you probably could assuming you mine what,100 rocks per second?

yeah im closing this

**Pull request closed without merging**
