### PR TITLE
I CHANGE THE CLOCK CULT MAP FOREVER

### PR DESCRIPTION
**Pull request by Readystorm546**
This may get rid of the lag round start so people in OOC dont go "Fuck its clock cult" due to long load times.

:cl:  
bugfix: fixed a load time maybe  by making the map smaller
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
In case anyone is wondering, what he did is make the map smaller.

In the future, please put details like this in the PR description so us maintainers don't have to either be big brained enough to think through the thought process of figuring out how we would achieve the same thing you did, or try to read through diffs.

**Comment by Readystorm546** [comment]
They are not big brain enough but ill fix it

**Comment by Bibby0110** [comment]
hey monster
it's called the mapdiffbot

**Comment by monster860** [comment]
the map diff bot is really fucky. sometimes it doesnt work, sometimes it decides the entire map is diff and then crashes, sometimes you have varedits and they don't show up because the map looks exactly the same

**Comment by Ktlwjec1** [comment]
ok let's try it, if it breaks anything it's an easy revert

**Pull request merged**
