### PR TITLE
Adds hallway to behind armoury to make it more secure

### PR DESCRIPTION
**Pull request by JamieD1**
Adds hallway to behind armoury to make it more secure

Alternative to #17347

image

Ill do other maps depending on which design is chosen

:cl:  
rscadd: Adds hallway to behind armoury to make it more secure
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
what the fuck is this

**Comment by cowbot92** [comment]
I actually really like the hallway, not even for security reasons just that its cool having random hallways next to space, kinda like how a space station should have.

**Comment by Hislyna** [comment]
Could we maybe make the camera actually alert security instead of just the AI too?

**Comment by JamieD1** [comment]
> Could we maybe make the camera actually alert security instead of just the AI too?

Could do

**Comment by Hopekz** [comment]
Have you tested these changes?

Not a "will it run" type thing but actually spawn yourself with some traitor tools that you'd expect them to be able to break in with and try it.

You've got 7 layers of security now (technically 8)

1. Outside the hallway to get in the hallway
2. Potential sec officers can now get in (they can also flank you from perma)
3. Going past another layer of hallway to get to space
4. Meanwhile the camera has been watching you the whole time during 1-3; now deal with the camera
5. get past the reinforced wall while still fighting sec in step 2
6. You now have to deal with the beepsy there. If you get distracted you'll just be chain stunned.
7. You can now be attacked from sec from inside the armory from warden's door and windows so when you make it in the armory you have 3 sides to worry about. Sec always has a flank on you with these changes where as before they could only come from one side.
8. (hidden): while you're dealing with 1-5 that gives sec ample time to clear the armory since the camera makes them aware of the attempt so there's nothing there once you get in

image

**Comment by Moltijoe** [comment]
210885650-c127c58d-dc76-45dd-95ce-efc782a074e9
idea courtesy of paint editing

**Comment by RG4ORDR** [comment]
Not a good idea, this just allows perma prisoners to easily break out without spacing the entirety of the perma section. 
They can go through one door and break down the other two + a window with the weapons that can be crafted in perma. 
Easy access to the gear room and even the armory.

**Comment by Hopekz** [comment]
> They can go through one door and break down the other two + a window with the weapons that can be crafted in perma. Easy access to the gear room and even the armory.

You forget where your methods makes you end up. What happens after you get to space? 
Wait on an airlock opening up while space walking? 
Cycling airlocks destroyed space walking.

The more realistic option is to continue breaking doors.
If a perma prisoner is able to break through 5 doors to escape prison without getting caught I think they probably deserve to get out of perma.
first perma door > second perma door in to new hallway > 3rd sec door in to sec lockers > 4th sec door out of sec locker room > 5th sec door in to brig

**Comment by Moltijoe** [comment]
> Not a good idea, this just allows perma prisoners to easily break out without spacing the entirety of the perma section. They can go through one door and break down the other two + a window with the weapons that can be crafted in perma. Easy access to the gear room and even the armory.

call me weird, but people breaking out of perma can be interesting if it's obvious enough and takes long enough

**Comment by RG4ORDR** [comment]
> > They can go through one door and break down the other two + a window with the weapons that can be crafted in perma. Easy access to the gear room and even the armory.
> 
> You forget where your methods makes you end up. What happens after you get to space? Wait on an airlock opening up while space walking? Cycling airlocks destroyed space walking.
> 
> The more realistic option is to continue breaking doors. If a perma prisoner is able to break through 5 doors to escape prison without getting caught I think they probably deserve to get out of perma. first perma door > second perma door in to new hallway > 3rd sec door in to sec lockers > 4th sec door out of sec locker room > 5th sec door in to brig
 
 It's not difficult to space walk to arrivals from perma, if you don't get zapped or thrown out into deepspace by the atmos you're more than likely going to make it to arrivals with air to spare.
 Secondly giving perma prisoners more options to bust out sorta defeats the entire purpose of the prison wing. Being able to bust down 2-3 doors and a window to get gamer gear is way to big of a reward. It's more than possible now for someone to get into the locker room, steal gear and retreat back into perma to fight. They're no longer confined or bottle necked by space and the only entrance.

**Comment by patpol4** [comment]
Closing in favour of https://github.com/yogstation13/Yogstation/pull/17379

**Pull request closed without merging**
