### PR TITLE
Replaces surgery table in the Operating Theatre with a stasis bed

### PR DESCRIPTION
**Pull request by Hopekz**
PR'ing this to discuss and possibly change if wanted.

What brought this PR:
image

**My medbay stasis PR didn't seem like the right place for that change so I'm bringing it over here**

image

**My personal opinion:**
Neutral on it but I do see people do this a lot.
Not sure if this falls within "making a department perfect so no upgrades need to be done" part.

#### Changelog

:cl:  
tweak: Surgery table in the Operating Theatre is now a stasis bed.
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Good pr.

Lowers the capacity for newbie doctors to make mistakes with lasting consequences, and makes it easier for them to learn the surgeries since less is at stake.

Since med is often both a new player role, and a role that many players from all over the station depend on, I strongly agree with this change.

Plus, it will mean the surgery room is used more often for the healing surgeries, since they are more effective when the patient isn't constantly dying as you attempt them

**Comment by Ktlwjec1** [comment]
Choose this one or #7824 , this one seems better to me but I don't mind, just don't want them both.

**Comment by CMOisLing** [comment]
I dont like this but tbh I cant find a real strong reason not to have it other than, I like the idea of just having a normal surgery table at start, and its not really that much better in most situations.

**Comment by Moja10** [comment]
this is just superior to the surgery table, which has no point now being on the station. muh powercreep!!!

**Comment by Hopekz** [comment]
Alright. I gave this PR a chance but I need to close one of my medbay PR's.
Keeping #7824 because it has more positive support and closing this one.

**Pull request closed without merging**
