### PR TITLE
Morph antag weight changed from 0 to 5

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request
Morphs are cool

#### Changelog

:cl:  
tweak: Morph antag weight changed from 0 to 5
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
*eats the entire armory and all traitor objectives*
Nothing personnel kid

**Comment by Ratvar** [comment]
If morphs were indeed cool, they would be a solo, side or midround antag this whole time. Morph gameplan:
1. Eat armory, so security cannot do anything against rest of antags
2. Eat antag objectives, so antags have nothing to do
3. Eat corpses, so medical has nothing to do and people cannot get back into the round
4. Eat APC, so nobody can do or repair anything, and protolathes, for the same
5. Hide by becoming a button, vent, lightbulb, blooddrip or any other small object crew will not be able to find

They are like a mix of nightmares and solo swarmer without any good mechanics, 0 weakness and even more murderbone and general grief

**Comment by boodaliboo** [comment]
there cool and weak see no problem with adding them

**Comment by jcatjmeow** [comment]
Morphs suck donkey dick they aren't even fun for either side

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
We can easily revert it back if it becomes an issue.

**Pull request merged**
