### PR TITLE
Minor Medical Changes

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request
removes Positronic brain from medical protolathe 
makes revival surgery available round start
updates nodes to reflect revival's movement.

# Why is this good for the game?
the movement of revival surgery is there to remove the tedium of sourcing a monkey or scream at science to research organs to revive a pod person. having to wait to revive a species that doesn't normally start with a heart isn't fun. plus IPC have this round start with their own surgery.
# Testing
ran in a private server a few times to check that the changes apply

# Wiki Documentation

move revival out of advanced surgery to basic surgery. 

# Changelog
:cl:  
tweak: removes positron brain from medical lathe
tweak: makes Revival surgery available round start

/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
15k is extremely high, no one uses the limbs that much

Those limbs can be crafted easily, medical budget or cargo budget usually don't have thatv much to afford that. I say remove the pack because no one will ever buy it
Other changes are fine

**Comment by ShoziOffical** [comment]
the surplus limbs are more fragile than the standard cyborg limbs 20 compared to 50 max damage, the limbs are used when you have nothing to replace

**Comment by solwashere** [comment]
Revival surgery should not be a roundstart surgery

**Comment by ShoziOffical** [comment]
> Revival surgery should not be a roundstart surgery

why so

**Comment by solwashere** [comment]
> > Revival surgery should not be a roundstart surgery
> 
> why so

Because it strips even more important shit away from R&D and completely invalidates cloning and strange reagent as a form of revival, and makes it so that there are no downsides to revival surgery.

Cloning downside: memory loss, potential bad mutation and clone damage unless upgraded
Strange Reagent downside: Hard to make and requires interaction with two different individuals
Revival downside: takes a while to get and a lot of the time will require interaction with science or the AI

**Comment by ShoziOffical** [comment]
> > > Revival surgery should not be a roundstart surgery
> > 
> > 
> > why so
> 
> Because it strips even more important shit away from R&D and completely invalidates cloning and strange reagent as a form of revival, and makes it so that there are no downsides to revival surgery.
> 
> Cloning downside: memory loss, potential bad mutation and clone damage unless upgraded Strange Reagent downside: Hard to make and requires interaction with two different individuals Revival downside: takes a while to get and a lot of the time will require interaction with science or the AI

you click few buttons and you already got the tech, that isnt really the problem and revival surgery does have downsize of damging your brain, cloning and strange reagent dont have anything to do with this like cloning is literally cloning your entire body into a new fresh with small downsizes, revival only just help you back up when you have been rot over 15 mins. If a person was brought in being rot, i would prefer cloning them instead of revival unless they have dna telometres

**Comment by solwashere** [comment]
> > > > Revival surgery should not be a roundstart surgery
> > > 
> > > 
> > > why so
> > 
> > Because it strips even more important shit away from R&D and completely invalidates cloning and strange reagent as a form of revival, and makes it so that there are no downsides to revival surgery.
> > 
> > Cloning downside: memory loss, potential bad mutation and clone damage unless upgraded Strange Reagent downside: Hard to make and requires interaction with two different individuals Revival downside: takes a while to get and a lot of the time will require interaction with science or the AI
> 
> you click few buttons and you already got the tech, that isnt really the problem revival surgery do have downsize of damging your brain 

Have you even played science or medical? I generally don't get revival surgery until about 45 minutes to an hour 15 minutes in, and I'm fairly certain that it takes a bit to get to that point as science doesn't and shouldn't prioritize endgame medical shit roundstart

**Comment by ShoziOffical** [comment]
> > > > > Revival surgery should not be a roundstart surgery
> > > > 
> > > > 
> > > > why so
> > > 
> > > 
> > > Because it strips even more important shit away from R&D and completely invalidates cloning and strange reagent as a form of revival, and makes it so that there are no downsides to revival surgery.
> > > Cloning downside: memory loss, potential bad mutation and clone damage unless upgraded Strange Reagent downside: Hard to make and requires interaction with two different individuals Revival downside: takes a while to get and a lot of the time will require interaction with science or the AI
> > 
> > 
> > you click few buttons and you already got the tech, that isnt really the problem revival surgery do have downsize of damging your brain
> 
> Have you even played science or medical? I generally don't get revival surgery until about 45 minutes to an hour 15 minutes in, and I'm fairly certain that it takes a bit to get to that point as science doesn't and shouldn't prioritize endgame medical shit roundstart

i do play med and sci, i always urge sci to do shit and they take it seriously on my request when i need most i had no problem, as sci i just do mining tech and shit first then medical later

**Comment by ShoziOffical** [comment]
sci points can be earned easily through xenobio, bombs and from engineering that isnt the problem you should get surgery tech in like 30 mins into round if sci isnt lazy

**Comment by Moltijoe** [comment]
@wonderinghost is the limb box cost a typo? did you mean 1500?

**Comment by ShoziOffical** [comment]
> @wonderinghost is the limb box cost a typo? did you mean 1500?

not typo, thats on purpose you can see him clearly set it to 15000 in code and comment. You can literally get 3 crates of uranium fuel rods with this amount of credits

**Comment by ShoziOffical** [comment]
that shit is already craftable, doesnt need to be bought from cargo

**Comment by wonderinghost** [comment]
> 15k is extremely high, no one uses the limbs that much
> 
> Those limbs can be crafted easily, medical budget or cargo budget usually don't have thatv much to afford that. I say remove the pack because no one will ever buy it
> Other changes are fine

I can tweak the price. I made this PR in 4 in the morning and knew that might be too high. Also people do use prosthetics. Just people like to grab the limbs of a decapitated person to be reattached.

 specifically prosthetics can't be crafted. You can make Borg limbs but those aren't the same as surplus prosthetics. And saying it doesn't get used is also the same for most of cargo's wears if it was added. People aren't going to go out of the way to order most of medical unless it is the one person that does restock inventory 

Yogs economy is fucked but that is another can of worms to deal with

**Comment by Moltijoe** [comment]
> specifically prosthetics can't be crafted. You can make Borg limbs but those aren't the same as surplus prosthetics.

You can ghetto craft prosthetics

**Comment by wonderinghost** [comment]
> > specifically prosthetics can't be crafted. You can make Borg limbs but those aren't the same as surplus prosthetics.
> 
> You can ghetto craft prosthetics
> 
> 

No? If it was then I would have noticed scrolling through the crafting tab. Unless it is in hand crafting

**Comment by ShoziOffical** [comment]
> > > specifically prosthetics can't be crafted. You can make Borg limbs but those aren't the same as surplus prosthetics.
> > 
> > 
> > You can ghetto craft prosthetics
> 
> No? If it was then I would have noticed scrolling through the crafting tab. Unless it is in hand crafting

image

**Comment by ShoziOffical** [comment]
real?

**Comment by ShoziOffical** [comment]
> specifically prosthetics can't be crafted. You can make Borg limbs but those aren't the same as surplus prosthetics. And saying it doesn't get used is also the same for most of cargo's wears if it was added. People aren't going to go out of the way to order most of medical unless it is the one person that does restock inventory

people can literally make limbs from limb grower (doesnt need proshetics unless indeed neccessary, yes the borg limbs are more dureable than the surplus

**Comment by wonderinghost** [comment]
Guess I'm blind then

**Comment by wonderinghost** [comment]
> > > Revival surgery should not be a roundstart surgery
> > 
> > why so
> 
> Because it strips even more important shit away from R&D and completely invalidates cloning and strange reagent as a form of revival, and makes it so that there are no downsides to revival surgery.
> 
> Cloning downside: memory loss, potential bad mutation and clone damage unless upgraded
> Strange Reagent downside: Hard to make and requires interaction with two different individuals
> Revival downside: takes a while to get and a lot of the time will require interaction with science or the AI 
> 

Wouldn't it be the hardest though on the account that ghetto surgery is wonkey. How often do you need to get your hands on lasers or a baton to revive someone. There is also the problem of it being ghetto surgery and if it is not at least sprayed with sterilzine you will fail far more often. 

Interaction and wait for something as basic as revival is dumb. Older then ipc revival boards which needed to get researched. And before you say that their revival surgery is mainly done in medbay. It is a lot more common to see a doctor or a paramed drop off a ipc body to robotics then it was when we still had revival boards. Where it was a 50/50 of it not being researched and robotics fuck off to go mine. Or it was researched and robotics doesnt revive you on the grounds of not knowing. This is also when we were breaking into robotics all the time.

This isn't for the one chance antag ghetto reviving a fellow antag. This is to make reviving people that happened to pick the species that doesn't normally start with a heart easier. Hell since this makes it available round start, Doctors might go for the revival after failing chest defib

**Comment by solwashere** [comment]
> > > > Revival surgery should not be a roundstart surgery
> > > 
> > > why so
> > 
> > Because it strips even more important shit away from R&D and completely invalidates cloning and strange reagent as a form of revival, and makes it so that there are no downsides to revival surgery.
> > 
> > Cloning downside: memory loss, potential bad mutation and clone damage unless upgraded
> > Strange Reagent downside: Hard to make and requires interaction with two different individuals
> > Revival downside: takes a while to get and a lot of the time will require interaction with science or the AI 
> > 
> 
> Wouldn't it be the hardest though on the account that ghetto surgery is wonkey. How often do you need to get your hands on lasers or a baton to revive someone. There is also the problem of it being ghetto surgery and if it is not at least sprayed with sterilzine you will fail far more often. 
> 
> Interaction and wait for something as basic as revival is dumb. Older then ipc revival boards which needed to get researched. And before you say that their revival surgery is mainly done in medbay. It is a lot more common to see a doctor or a paramed drop off a ipc body to robotics then it was when we still had revival boards. Where it was a 50/50 of it not being researched and robotics fuck off to go mine. Or it was researched and robotics doesnt revive you on the grounds of not knowing. This is also when we were breaking into robotics all the time.
> 
> This isn't for the one chance antag ghetto reviving a fellow antag. This is to make reviving people that happened to pick the species that doesn't normally start with a heart easier. Hell since this makes it available round start, Doctors might go for the revival after failing chest defib 
> 
> 
> 
> 
> 
> 
> 

God forbid the game is hard for someone
When you pick a species like plasmamen you know the risks.
This isn't a "minor medical tweak" this is a hugbox PR, if you want to revive someone without a defib at roundstart then use cloning

**Comment by Moltijoe** [comment]
Balance Council:
>Revival surgery should not be available round start, much less without even needing a surgery computer
There are other ways to revive species that would benefit from revival surgery, including getting a heart from monkeys or cloning
Please revert that change (it'll just be the mmi change remaining)

**Pull request closed without merging**
