### PR TITLE
Revert "Heads of staff now spawn together in the conference room."

### PR DESCRIPTION
**Pull request by JamieD1**
Fucking couldn't go one day before it was abused, we need some rules or some player tweaks before this can be merged with our current murder hungry players.

https://gyazo.com/7ada99c0e6b54ba6d5fc8a5ac6f61bbd

### CODE REVIEW

**Comment by Jarod1200** [comment]
im not gonna say i didnt mention that on the original PR. but i kinda did

**Comment by Amelia0010** [comment]
>we need some rules


0.0: Don't be a dick. 
Don't behave in a manner that goes out of its way to deprive the enjoyment of others. These rules are not an exhaustive list. Rules-lawyering is strongly discouraged. If an admin asks you to knock something off, 'well it's not in the rules' is not really an argument.
1.1: Do not grief. 
If you are not a round antagonist, do not cause major station damage, cause major chaos, create fires or hull breaches, release harmful gasses, spread harmful diseases, force disabilities or powers without consent, turn people into monkeys, distribute harmful injectors, severely harm, decapitate, or murder people, trap people in places from which they cannot escape, or any other action that would be considering agonizing for other players. As a rule of thumb, don’t commit crimes worthy of capital punishment as a non-antagonist. This list is not conclusive.

**Comment by boodaliboo** [comment]
how was it abused?

**Comment by jcatjmeow** [comment]
Simply make it so heads cant be antag

**Comment by Hopekz** [comment]
What happened to banning for muderbone like every other instance?
Other servers don't need these rules this is a staff issue here if a player is able to rule lawyer their way in to murdering all heads round start being valid.

We already have rules in place for this now start enforcing them In a way that promotes higher RP

**Comment by patpol4** [comment]
The problem is the player who does this, not the feature..

**Comment by alao3alao3** [comment]
Hope that gets reverted or we got a nasty precedent to look up with law 0 to that's sure as hell going to get cited.

**Comment by Amelia0010** [comment]
>Hope that gets reverted or we got a nasty precedent to look up with law 0 to that's sure as hell going to get cited.

What did he mean by this

**Comment by Moja10** [comment]
> > Hope that gets reverted or we got a nasty precedent to look up with law 0 to that's sure as hell going to get cited.
> 
> What did he mean by this

Admins and Council, please state all laws, INCLUDING any law 0's. Law 2

**Comment by MegaEmpirical** [comment]
I don't want it reverted, maybe temporarily if we have to but I would rather work on the issue. I really like the idea of them being in the head meeting room and I think it's a good jumping off point for working on various issues that we should deal with.

**Comment by Mesalikepie** [comment]
This was a problem player not a problem merge. Player issue not code

**Comment by patpol4** [comment]
PR made due to a shitstorm, not a code but player issue, we have other pr's working on heads being antag now. Closing due to that and overwhelming negative votes.

**Pull request closed without merging**
