### PR TITLE
Sterilizes the codebase - Pt.9 Removes The King of Felines

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Oranges is no more

# Changelog

:cl:  
rscdel: Removed extradimensional oranges
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Improve don't remove

**Comment by ynot01** [comment]
> Improve don't remove

im sorry i cant see any possible way to improve Oranges

**Comment by Cartlord** [comment]
What's wrong with them, though?

**Comment by VaelophisNyx** [comment]
As a botany plant they kinda....don't do much
they exist as a meme

I'm fine with this removal, but an improvement would be interesting
maybe give them oxygen production, one of the few things botany still doesn't get access to

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
