### PR TITLE
ports cucumbers and pickles

### PR DESCRIPTION
**Pull request by ktlwjec0**
https://github.com/tgstation/tgstation/pull/69639
Ports most of this, not the plushie and the jar (tg had like 3 fixes for it and i still cant get it to work!!!).

- Adds cucumber to wildcard cook ingredients box.
- Pickles and cucumber bounties.
- Adds cucumber seeds to seeds crate.
- Adds cucumber to vegetables crate.
- Danish hotdog
- Adds pickle to super bite burger and increases nutriment and vitamin amount
- Pickles and cucumbers
- Gin Garden and Cucumber Lemonade drinks
- Cucumber seeds and plant.

# Why is this good for the game?
More food and drink variety, being hungry is bad, plus needed for future ports.

# Testing
yes i checked it works

# Spriting
cucumber (top) and pickle, and cucumber seeds
image image
cucumbergrowing

the original sprites for these are lovely but don't fit with our current sprites so I had to redo them so they are not as epic sorry:
danish hotdog next to its hotdog friend
image
gin garden (top-left) and cucumber lemonade (bottom-left) next to their friends iced coffee and vodka tonic
image

:cl:  Vishenka0704, Ying-The-Pando, ktlwjec
rscadd: Cucumbers. Seeds found in the seed vendor. Can be juiced to make cucumber juice.
rscadd: Pickles. Crafted with 5u water, 2u salt and 1 cucumber.
tweak: Super bite burger now needs a pickle to craft.
rscadd: Danish hotdog. Crafted with 1 bun, 1 sausage, 1 pickle, 5u ketchup and 1 onion slice.
rscadd: Gin Garden drink. Made with 1 part lemon juice, 1 part sugar, 3 parts gin, 3 parts cucumber juice, 5 parts sol dry and 2 parts ice.
rscadd: Cucumber Lemonade. Made with 3 parts spite, 2 parts cucumber juice and 1 part ice.
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
make it so felinids start with a phobia of cucumbers

**Comment by iloveloopers** [comment]
this is ERP

**Review by cuackles — APPROVED** [review]
image

**Comment by AnywayFarus** [comment]
👍🏻

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
