### PR TITLE
Fuck off Space Dragons - Space Dragon Tweaks

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Nerfs RWALL Breaking
Increases Tail Sweep Cooldown
Unable to spawn with less then 30 people

Also prevents this shit: 

https://yogstation13.github.io/demo-viewer/?roundid=29141#59260;166.63;177.50;2;thegamer01

#### Changelog

:cl:  
tweak: Space Dragon Balance
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
I'd say this was a ided PR if you weren't already dead when gamer spawned. I agree with the no spawning with less than 30 people and the spess dragon being unable to break Rwalls, but you seemed to have DOUBLED the cooldown of tailsweep, something I don't agree with, I do think it could use a LITTLE bit longer of a cooldown but not double.

**Comment by MegaEmpirical** [comment]
What the fuck is "ided"? I keep seeing it and at first I thought it was a typo and now I'm thinking you people are having a stroke.

Also, space dragons can have an objective to kill an already dead head which is fucky.

**Comment by Moja10** [comment]
I don't see a reason to nerf the Rwall breaking.

**Comment by overlord12345** [comment]
> What the fuck is "ided"? I keep seeing it and at first I thought it was a typo and now I'm thinking you people are having a stroke.

ided is when a nerf PR is made after you die to something in game, its the ''i ded pls nerf'' meme.

Also duble cooldown is too much

**Comment by JamieD1** [comment]
>Gamer says double the cooldown
>Gamer Downvotes the thread
>What

**Comment by JamieD1** [comment]
Tailsweep now has Slightly higher cooldown then base.

Also did you watch the replay.

**Comment by Bibby0110** [comment]
> > Gamer says double the cooldown
> > Gamer Downvotes the thread
> > What
> > Gamer also upvotes the thread
> > 1 upvote + -1 upvote = 0 upvotes

**Comment by Xoxeyos** [comment]
> I will change my vote if you keep the tail spin the same. I watched the replay, and the RWall busting was insane.

The PR doesn't do anything to the rwall breaking (or really any wall breaking) . 
Its like a "fake nerf" IMO by adding a small delay . It seem doesn't do what it was set out to do.

**Comment by ghost** [comment]
why not port the actual space dragon changes made on tg to address this exact issue

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
