### PR TITLE
Adds dynamic to rotation

### PR DESCRIPTION
**Pull request by swissloaf**
########################################
########################################
### Intent of your Pull Request

I think it'd be a good rotation mode, so I gave it a 10% chance of occurring.

#### Changelog

:cl:  
rscadd: Adds dynamic to rotation
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Buff to 50% chance please

**Comment by swissloaf** [comment]
> Buff to 50% chance please

nah. thats practically giving a 50% buff to traitors, lings, vamps, cause those are the most common ones. I keep it low

**Comment by Amelia0010** [comment]
You realize this doesn't do anything, right?

**Comment by swissloaf** [comment]
> You realize this doesn't do anything, right?

i was told this was where the gamemode probability was controlled

**Comment by Bibby0110** [comment]
But you realize the config on the server isn't the one on the GitHub, and that this requires a council vote too

**Comment by swissloaf** [comment]
> But you realize the config on the server isn't the one on the GitHub, and that this requires a council vote too

and that might be why this has the config label?

**Comment by Bibby0110** [comment]
> > But you realize the config on the server isn't the one on the GitHub, and that this requires a council vote too
> 
> and that might be why this has the config label?

?!?!??!?!?
You're changing the config yeah, but that doesn't do anything you dingus

**Comment by boodaliboo** [comment]
hi

**Comment by swissloaf** [comment]
> > > But you realize the config on the server isn't the one on the GitHub, and that this requires a council vote too
> > 
> > 
> > and that might be why this has the config label?
> 
> ?!?!??!?!?
> You're changing the config yeah, but that doesn't do anything you dingus

you stupid or something? ive asked for this to be moved to the server config as well?

**Pull request closed without merging**
