### PR TITLE
Makes Changes To Venomous Mobs*

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Makes Snakes into Vipers that actually inject 10u of Venom into you per bite. Replaces the snakes from the original cargo pack with a variant that injects 0u like before, so mostly harmless. Adds a Contraband cargo pack that contains 3 vipers

renames Viper spiders into Void Recluses to avoid confusion, and also because it's cooler

Makes Giant Spiders inject Acid
Makes Nurse Spiders and Brood Mothers inject Tirizine

Makes Weavers use 5u Spore Toxin by default, and inject 8u Venom when angry (at or below 33% hp)

# Sprites

Maybe could use a new sprite for venomous snakes, but it's not critical.

# Wiki Documentation

Will need to be documented on the hostile mobs pages

# Changelog

:cl:  
rscadd: Added Viper Crate Contraband Cargo Pack 
rscadd: Added Vipers, snakes that inject Venom into you on bite
tweak: Weavers now inject Spore Toxin by default, and Venom when enraged
tweak: Giant Spiders now inject Acid on bite
tweak: Nurse Spiders/Broodmothers inject Tirizine on bite
spellcheck: Viper Spiders have been Renamed Void Recluses
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
1 unit of venom injected does almost literally nothing because it gets instantly purged and does just a teeny tiny amount of damage due to its damage being based on volume. Three units of sodium thiopentol, on the other hand, will do a chunk of damage and with only two bites can theoretically stam crit people, assuming they were timed close enough together. I suggest NOT using that one, but rather just use tirizene at like 4 units or so.

**Comment by VaelophisNyx** [comment]
> 1 unit of venom injected does almost literally nothing because it gets instantly purged

will probably adjust, alright

>Three units of sodium thiopentol, on the other hand, will do a chunk of damage

it does no damage tho, according to the wiki? just 10 ticks and then sleep

>and with only two bites can theoretically stam crit people

err...isn't that Tirizine's thing as well?

**Comment by Marmio64** [comment]
why make giant spiders inject acid? They were already injecting actual toxins before, they're not xenomorphs.

**Comment by VaelophisNyx** [comment]
because a spider injects digestive fluids into prey usually
so
acid

**Comment by Marmio64** [comment]
> because a spider injects digestive fluids into prey usually so acid

nurse spiders do that already when they eat and cocoon people, not to mention spiders generally inject normal venom first then digestive fluids.

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
