### PR TITLE
[BOX] Bar Improvements + Coffee

### LINKED ISSUE #21110: There is a missing disposals pipe in the new bar design
### Severity

Inconvenience

### Short Description

For some reason there is no disposals pipe at the bar

### Reproduction

1. Round starts
2. There is a missing disposals pipe underneath the airlock
3. Stuff going to disposals ends up in the bar

### Round ID

50656

### Test Merges

_No response_

### BYOND Username

_No response_

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Screenshot (6)

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

shrinks bar backroom by 1 tile, adds more lights, adds coffee setup (#21107 Is included in this PR), tweaks access so barman can enter his own maint

fixes #21110

# Changelog

:cl:  cark, cowbot93
mapping: improves new bar by fixing issues and adding coffee
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image
revert this back to like this
also remove that door into the hallway that's STUPID

rest looks fine

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
also you can close/open the blinds from the hallway

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image

remove shadows on either of these the top or the bottom here this isnt how shadows work!!

**Comment by azzzertyy** [comment]
> image
> 
> remove shadows on either of these the top or the bottom here this isnt how shadows work!!

i told him... he ignored me....
(he still did them weirdly... remove the top ones only, keep the bottom ones and extend them across the entire length of the stage....)

**Comment by neeshacark** [comment]
> i told him... he ignored me.... (he still did them weirdly... remove the top ones only, keep the bottom ones and extend them across the entire length of the stage....) 

nuh uh you committed to the pr to fix it i thought

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
