### PR TITLE
Adds the Medical Inducer

### PR DESCRIPTION
**Pull request by TheReddDragon**
### Intent of your Pull Request
Chem Mains rejoice. Adds a medical inducer which unlocks when you research Electromagnetic Theory. Requires (per the code I wrote):
- Iron 3000
- Glass 2000
- Gold 1000
- Diamond 50

### Why is this good for the game?
This is a balanced tool for chemistry mains and other medical staff to recharge certain medical items including but not limited to the chem master, chem dispenser and defib.
#### Changelog

:cl:  
rscadd: Adds the Medical Inducer
/:cl:

### CODE REVIEW

**Comment by TheReddDragon** [comment]
ignore the see description commit I fucked up my typing there

**Comment by Georgeur** [comment]
finally I wont be deconstructing my machine, recharging my cell at medbay lobby, then reconstructing my machine again, over and over and over.

**Comment by TheReddDragon** [comment]
"A chemical dispenser is like a high end car. You need to maintain it to keep it running."

**Comment by ynot01** [comment]
this defeats interaction between chem and sci/engi

**Comment by UselessTheremin** [comment]
> this defeats interaction between chem and sci/engi

no it doesnt, chem will still blow themselves up all the time

**Comment by Georgeur** [comment]
In 9/10 times it's faster to deconstruct the machine, put the cell onto a cell charger, then reconstruct. There isn't a lot of interaction between chem and sci unless they want to be lazy. Which sometimes I do.

**Comment by Tipy1802** [comment]
> no it doesnt, chem will still blow themselves up all the time

But they won’t ask science for inducers

**Comment by TheReddDragon** [comment]
it still leaves interactions between sci and chem by reducing this inducer's charge rate to 200 down from 500 @Tipy1802 @ynot01

**Comment by ghost** [comment]
Hooray, removing more interdepartmental cooperation in the name of 'quality of life.'

Quality of life is shit. QOL is an awful fucking component that has been slipped into the game time after time that just translates to 'powercreep' and 'I don't want to ask for things.'

Ask. Go ask science for an inducer. It's not that fucking hard. It is a two minute walk to science to ask them for an inducer. If it's 'more time consuming', then GOOD, we want things to be time consuming, and we want things-any job, really-to depend on other people doing their fucking jobs in turn.

**Pull request closed without merging**
