### PR TITLE
[PORT] Ports traitor backstories from BEE

### PR DESCRIPTION
**Pull request by cowbot92**
All credit goes to the original PR located here - https://github.com/BeeStation/BeeStation-Hornet/pull/9126

# Document the changes in your pull request

Adds unique backstories to be assigned to traitors based on some preferences, including some involving the character being forced into it, others where they are doing it for gain, and then just the straight up insane.

Backstories are selected by the player after their objectives are picked, but before they are given an uplink or codewords. The backstory determines whether you receive codewords or not, and your objectives provide hints to the backstory/faction selector (if you are murderbone or not) which will tell the user that certain backstories are recommended or not.

It is up to the player to choose a fitting backstory for their character, and there is no gameplay incentive to follow it or other mechanics related to it. This is purely a roleplay tool. The only gameplay interaction is that independent and black market traitors do not get codewords and thus may not be able to team with other traitors as effectively.

# Why is this good for the game?

Provides players with an easier way to motivate their roleplay as an antagonist, and better shows the player that roleplay is of a priority when playing as an antagonist through in game means rather than external motivators like rules. It makes green texts and objectives themselves less central and incentivizes thinking about the character.

# Testing

image
image
image
image

# Changelog

:cl:  
rscadd: Adds traitor backstories from bee
experimental: This is experimental
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
image
fear

**Comment by AMyriad** [comment]
holy based
I'd love to see lore team add some more flavor to this, but that'll no doubt be done at some point or another if this is seen through (please see it through)

**Review by Chubbygummibear — APPROVED** [review]
looks good to me
(at least the part i had to fix)

**Comment by Beeper-Skeeper** [comment]
these backstory names remind me of binding of isaac name schemes (for the character achievements)

**Pull request merged**
