### PR TITLE
Adds Public Art consoles to all libraries

### PR DESCRIPTION
**Pull request by Bibby0110**
# General Documentation

### Intent of your Pull Request

Renames curator console to art console.
Adds an additional art console in public parts of library so people can print art.
Adds an art console to private curator part of Kilo (Wej forgot :( )
Map merges Kilo because it wasn't (?)

### Why is this change good for the game?

Art

# Changelog

:cl:  
rscadd: You can now print art without the help of the Curator
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Brain blast what if you add this functionality to the curators console

**Comment by adamsong** [comment]
I think you may have pushed the wrong version of kilo

**Comment by Marmio64** [comment]
the curator's only way to interact with the crew asides from posters and bibles... obliterated.

**Review by patpol4 — CHANGES_REQUESTED** [review]
kilo looks not mapmerged

**Comment by patpol4** [comment]
Still broken

**Comment by Bibby0110** [comment]
> Still broken

Kilostation is broken seemingly, see Brig Physician PR for example.

**Comment by Bibby0110** [comment]
> Still broken

be happy, do it nooow

**Review by patpol4 — APPROVED** [review]
Unbroken

**Pull request merged**
