### PR TITLE
makes romerol unbuyable for nuke ops

### PR DESCRIPTION
**Pull request by Amelia0010**
PRs to this branch: https://github.com/yogstation13/Yogstation-TG/pull/3179
see: https://github.com/yogstation13/Yogstation-TG/pull/3061

### CODE REVIEW

**Comment by fluffe9911** [comment]
First off your the one who orignally gave nuke ops romerol like a couple months ago though you closed it because you left again secondly CAN YOU GIVE IT A SHOT ATLEAST BEFORE GETTING RID OF IT
Like jesus chrsit

**Comment by Ktlwjec** [comment]
I can merge this, it's a sign. Down with romerol!

**Comment by Amelia0010** [comment]
>CAN YOU GIVE IT A SHOT ATLEAST BEFORE GETTING RID OF IT
Like jesus chrsit

Hey why don't we remove the station and just spawn everyone in in space. We have to give it a shot before getting rid of it :^)

**Comment by fluffe9911** [comment]
I mean we would atleast learn if removing the station is a bad idea or not 100% lol

**Comment by Amelia0010** [comment]
We already know it is :)

**Comment by fluffe9911** [comment]
We dont know if this is though lol

**Comment by Amelia0010** [comment]
We do though :)

**Pull request merged**
