### PR TITLE
Revert "Updates the base captain uniform sprites."

### PR DESCRIPTION
**Pull request by JamieD1**
Reverts yogstation13/Yogstation#8351

They look fucking awful,

Peoples opinions please

[Screenshot from Gyazo](https://gyazo.com/2bb2112a9884c810691bc9daf85306ca)

### CODE REVIEW

**Comment by Nickvr628** [comment]
Agree, the new one looks washed out like a faded T-Shirt. It is supposed to be bright and distinguishable. It is a formal uniform.

The new "art director" needs to go back to art school methinks.

**Comment by maxion12345** [comment]
carapace does look alot less armor-like then before

**Comment by chaoko99** [comment]
>The new "art director" needs to go back to art school methinks.

Make your own replacement, then. Expert.

**Comment by Marmio64** [comment]
> > The new "art director" needs to go back to art school methinks.
> 
> Make your own replacement, then. Expert.

my idea for a replacement is the old sprites cause I like them more.

**Pull request closed without merging**
