### PR TITLE
DJ Station ghost role

### PR DESCRIPTION
**Pull request by Hopekz**
new DJ Station ghost role

Basically a Russian themed syndicate comms outpost except manned by a "DJ Man"

Ideally, I'd want this to be like a hippie station Radio Host but we don't have the framework for it yet.

Before
-----
djstation1

After
-----
djstation2
djstation3

**In a future PR:** Maybe make this guy able to play youtube music or do something close to the Hippie radio host.

#### Changelog

:cl:  Hopek
rscadd: New Russian DJ station ghost role
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Nice;
bubblegum spawned in my Turdis test

image

**Comment by Xoxeyos** [comment]
Yes please, be sure to add a limiter to the songs that you can play, like at around seven minutes a song should end.

**Comment by alexkar598** [comment]
This feels like the lava land comms agent but with the ability to shitpost in secure channels instead of simply listening

**Comment by Hopekz** [comment]
> This feels like the lava land comms agent but with the ability to shitpost in secure channels instead of simply listening

Yeah probably; Who really knows.
I imagine it as people having weird conversations or people doing news reporting with what they see in the camera console. No idea I just think its "cool" so I made it.

> Yes please, be sure to add a limiter to the songs that you can play, like at around seven minutes a song should end.

There are no songs; not in this PR.
With this PR it's just like a Russian themed lavaland comms agent basically

**Comment by Jarod1200** [comment]
Lavaland comms agenr CAN shitpost in secure channels already

**Comment by Bibby0110** [comment]
This is just lavaland comms agent without the Syndicate encryption key, or the message monitor

**Comment by Hopekz** [comment]
So @alexkar598 do you not like the map? The idea of this PR? 

You kind of preemptively downdoinked my WIP PR when there is no code in place for the ghost role in the first place

Any feedback besides it being like the comms agent? How can I improve?

**Comment by alexkar598** [comment]
Command and sec channels can be read but not talked in by lavaland command agents AFAIK, this is just copy pasting it but to be in a space ruin, not even counting the other space ruin listening post

**Comment by Jarod1200** [comment]
lavaland comms agent can use the intercom on his desk to shitpost or whatever he wants on any channel including command and security. I believe this is the same for the intercoms on the dj ruins too

**Comment by HomocidlePancakes** [comment]
See post above.

**Comment by Marmio64** [comment]
it adds more variety

**Comment by alexkar598** [comment]
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

+

This PR is just the lavaland comms agent without much that makes it actually different

**Comment by Addust** [comment]
> Command and sec channels can be read but not talked in by lavaland command agents AFAIK, this is just copy pasting it but to be in a space ruin, not even counting the other space ruin listening post

wrong

**Comment by Hopekz** [comment]
> wrong

imo the juice isn't worth the squeeze in this case argument-wise.

Regardless; You have my permission (not that you'd realistically need it) to revive any of my unfinished PR's since I have a few I can remember including this one.

Even if you don't turn it into what was envisioned on making a hippie station Radio Host role a quick and easy PR would be just using the map itself since it should be a nice ghost ruin vs what they already have.

Thank you!

**Pull request closed without merging**
