### PR TITLE
Nerfs chemical bombs

### PR DESCRIPTION
**Pull request by ynot01**
# Why is this change good for the game?

Chem nades too stronk

# Document the changes in your pull request

https://forums.yogstation.net/threads/vote-set-maxcap-to-3-6-12-and-make-the-syndie-bomb-use-the-current-bombcap.19515/

Dynamic explosion scale at this time was `0.5`, which meant a `200` power chemical grenade exploded at exactly `5/10/20`

To make the formula explode at exactly `3/6/12`, we would need it to be around `0.4147411088308`, but since floating point imprecision is a bitch and also BYOND rounds down, it's being set at `0.415`, which places us squarely at around
`3.0046570227/6.0093140454/12.0186280908`
Which conveniently rounds to `3/6/12` when being calculated by the explosions subsystem

And before you say anything, no, dynamic explosion scale does not have a config entry.

# Changelog

:cl:  
tweak: Dynamic explosion scale has been nerfed to reflect the bomb cap that was nerfed 4 years ago
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
What is a practical example of a 200 power explosion? How will this change the size of a Syndicate bomb's explosion?

**Comment by Cartlord** [comment]
nevermind i'm stupid

**Comment by ynot01** [comment]
> What is a practical example of a 200 power explosion? 

2340 units of black powder, 2000 units of pre-nerf water+potassium, 1200 units of methamphetamine, or 400 units of nitroglycerine

These levels are obviously quite hard to obtain, but it also effects lower levels.

50 units of water + potassium was 0/1/3 and is now 0/1/2

200 units of meth, the most common bomb, has an explosion level of ~33.3333. This leads to an explosion of 2/4/8, but after this nerf, is 1/2/5.

600 units of meth, the step up, was 3/7/14, and is now 2/4/9.

> How will this change the size of a Syndicate bomb's explosion?

Syndicate bomb uses a set explosion, so it is unaffected

**Comment by Georgeur** [comment]
Do 0.516, I won’t elaborate why, trust me on this.

**Review by Moltijoe — APPROVED** [review]
Code works.
I personally feel like it should aim for 4/8/16 from a 200 power bomb rather than 3/6/12

**Comment by Moja10** [comment]
How many stacking chemistry bomb nerfs before we realize we removed the entire possibility of it being a thing? why does science get rhe only monopoly on explosions? why are we acting like the 2 minutes science takes to make a bomb is good and balanced and fair and permitted but chemistry having to make 2000 units of a single, difficult to make Chem in masse is cringe and should be excised from the game?

**Pull request merged**
