### PR TITLE
Issiah 48:22 - There is no peace, saith the LORD, unto the wicked. - Round End Report Changes

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Removes Green / Red text on roundend reports.
Hisa said "do this"
Also the lord said "do this because they want to add vox, and you are my righteous blade that shall deliver their punishment"
idk I've never read the bible

# Why is this good for the game?

Less focus on the TDM greenset grind = good.

# Testing

Not yet because I know this is gonna cause a lot of whinging and such, but it's literally just removing colour in a textbox. It cannot not work.

# Changelog

:cl:   
tweak: Endround summary now doesn't display win/lose in green/red, but simply states your objectives.
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
I realize span isn't a thing, and ill fix it later.

**Comment by Yarinoi** [comment]
image

**Comment by JamieD1** [comment]
Religion bad

**Comment by Hislyna** [comment]
There is a god

**Comment by ToasterBiome** [comment]
Doesn't address the actual problem, just throws a blanket over it. 🙈 If you can't see it it doesn't exist

**Comment by Hislyna** [comment]
God has left us

**Pull request closed without merging**
