### PR TITLE
Grenadier belt changes

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Removes the completley useless flashbang and 4 smokes that you would just throw out anyways in exchange for 2 more frags that you actually WILL use.

# Changelog

:cl:  
tweak: Useless grenades removed from grenadier belt
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
change the uplink description to tell nuke ops they get 23 grenades in it instead of 26 now.

**Comment by JamieD1** [comment]
Smoke can be useful, kinda feels like you are forcing your preference onto other people here.

**Comment by Mantlecrawler** [comment]
I have never seen a nukie use the flashbangs or smoke grenades asides from myself and even then that was one time.

**Comment by MajManatee** [comment]
@JamieD1 do a poll then and we can find out. I'm willing to bet everyone would rather have more killing grenades than some smokes. Especially on nukies.

**Comment by ReddicusDragon** [comment]
I'm gonna slap awaiting action HD here since Jamie seems to be considering this PR

**Review by ynot01 — CHANGES_REQUESTED** [review]
> change the uplink description to tell nuke ops they get 23 grenades in it instead of 26 now.

**Comment by ynot01** [comment]
no point in holding this PR for HD

**Comment by Moja10** [comment]
why not 1 smoke and 1 flashbang on top of the two new frags? they can have niche use, syndies didn't need multiple though

**Comment by MajManatee** [comment]
i dont care enough to change it

**Pull request closed without merging**
