### PR TITLE
NT-USP revamp

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Feature freeze over

Of note (Not changed by this PR):
- NT-USP magazines charge much slower (about 2x slower or more with lag) compared to disabler, which charges 2-8 shots per tick while the magazines charge 1-4 shots per tick
- Even if rechargers were made to charge 10% of a magazine per tick (which would probably fuck things up with delta time because you cant have half of a bullet) disablers would still outclass magazines due to them having 12 rounds (1.2 per charge) vs disabler's 20 rounds (2 per charge)

See wiki documentation for player-facing changes

# Spriting
By baiomu

Magazine modkit that changes magazines from non-lethal to lethal and vice versa

New mag sprite and lethal mag sprite

Bolt will glow red when loaded with lethal magazine

# Wiki Documentation

- NT-USP mag now has 12 bullets (for a total of 24+1) (Disabler has 20 total)
- NT-USP bullets now travel a bit slower (0.4 -> 0.55) (projectiles default at 0.8)
- NT-USP lethal mag has 8 bullets (for a total of 16+1) (Laser gun has 12 total)
- NT-USP magazine conversion kits are printable at the armory protolathe for 500 iron, 200 glass, and 200 silver
- NT-USP mags will have empty chambers when converted
- NT-USP lethal mags should be considered a sidegrade to laser guns
- NT-USP lethal bullets do 18 burn damage and resolve against laser armor
- NT-USP lethal bullets create blood splatter so people know they're lethal
- NT-USP lethal bullets have -15 wound bonus and 5 bare wound bonus

# Changelog

:cl: Skrem, ynot01, baiomu
tweak: NT-USP mag now has 12 bullets
tweak: NT-USP bullets changed to be slower (0.4 -> 0.55)
tweak: NT-USP magazines and bullets reflavored
rscadd: Armory lathe now contains NT-USP conversion kits which can be used on NT-USP mags to make them print .22LS laser rounds instead of .22HL disabler rounds, but has less ammo capacity 
imageadd: New sprites for NT-USP magazine and NT-USP when a lethal mag is loaded
/:cl:

### CODE REVIEW

**Comment by Skrem7** [comment]
Only thing I would change is equalizing out the wound bonus to overall be higher but not have a ludicrous bare wound bonus; that's something pretty unique to the laser gun in how it fires a searing beam, whereas this lethal conversion is a "bullet" beam thingy that doesn't pass through glass?

Otherwise let's give it a shot

**Comment by ynot01** [comment]
Changed wound bonus to -15 and bare wound bonus to 5 based on Skrem's suggestion

**Comment by maxion12345** [comment]
.45 conversation kit when

I cannot wait for when I can finally have a laser pistol

**Comment by Mqiib** [comment]
The wounding compared to lasers:
Lethal NTSP (18 damage, -15 bonus, 5 BWB)
any armor: rolls (-15) - 42 (3.5% chance to wound)
no armor: rolls (-10) - 47 (12% chance to wound)

Lethal laser (20 damage, -30 bonus, 40 BWB)
any armor: rolls (-30) - 36 (can't wound)
no armor: rolls 10 - 76 (54% chance to wound)

Note that actual armor values (which can have significant impact) and other modifiers are not taken into account here so these numbers can be higher/lower, especially on some species with higher burn modifiers like pods (who can get critical burns instantly lmao). Light burns have a threshold of 40 to appear, severe 80, and critical 140

**Comment by Hopekz** [comment]
@Mqiib so what's your feedback you just wrote out the damage

**Comment by ynot01** [comment]
> Lethal NTSP (18 damage, -15 bonus, 5 BWB) 
> any armor: rolls (-15) - 42 (3.5% chance to wound) 
> no armor: rolls (-10) - 47 (12% chance to wound)
> 
> Lethal laser (20 damage, -30 bonus, 40 BWB) 
> any armor: rolls (-30) - 36 (can't wound) 
> no armor: rolls 10 - 76 (54% chance to wound)

seems fine to me

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Looks cool

**Comment by MajManatee** [comment]
Any other way to make the evil mag besides just... painting it redder?

**Comment by ynot01** [comment]
Awaiting baiomu sprites

**Review by cuackles — APPROVED** [review]
sprites seem good to me

**Comment by ynot01** [comment]
i forgot there was more than 1 art guy

**Comment by JamieD1** [comment]
Balance Council finally do a good?

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
