### PR TITLE
[DRAFT] Multi-Z Centric Station (To yet be named)

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

New station, centered around multi-z and different floors with "themes" to each.

# Why is this good for the game?

Variety good!

# Testing

Still in draft mode.

# Wiki Documentation

Draft mode

# Changelog

:cl:  
rscadd: New Station designed around multiple z-levels
mapping: 1: Bridge, Head Offices, Vault, Armory
mapping: 2: Security, Medbay, Science, Comms, AI Upload, Teleporter Room
mapping: 3: "Main" floor, Arrivals, Evac, Dorms, most Service & Civilian areas (HoPline undecided)
mapping: 4: Janitor & Maints (there will be maints on all floors but this one is primarily maint)
mapping: 5: Cargo, Engineering
mapping: Random Level: AI Sat (quantum jump pad like Gax AI Whale)
experimental: Theoretical, unsure if server can handle a 5-level station
/:cl:

### CODE REVIEW

**Comment by MommaDragon** [comment]
Call it Manifold.

**Comment by MommaDragon** [comment]
Or Burrito.

**Comment by N3D6** [comment]
Not box, downvoted

**Comment by MajManatee** [comment]
Id like to see more things support multi-z before making a full map around it. Things like pinpointers and sensors especially should have a way of displaying a Z level

**Comment by Aquizit** [comment]
Got distracted from this by needing to move I will come back to it at another point.

**Pull request closed without merging**
