### PR TITLE
Adds Jumpsuit/Jumpskirt Preference

### PR DESCRIPTION
**Pull request by Absolucy**
# Document the changes in your pull request

This adds a jumpsuit/jumpskirt preference, which is pretty much self-explanatory - it allows you to spawn in with a jumpskirt (if your job has an equivalent available)

Mostly a port of https://github.com/tgstation/tgstation/pull/44883, although I opted to add a `uniform_skirt` var to outfits, as it seems less hacky than doing string manipulation on the path.

# Changelog

:cl: Lucy
rscadd: You can now spawn in with a jumpskirt if you want!
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
wait i thought this already existed am i insane

**Comment by Absolucy** [comment]
@UselessTheremin where?

**Comment by ilikesaying** [comment]
isn't it present in the character setup?

**Comment by Absolucy** [comment]
@ilikesaying  i'm blind or don't see it 
image

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
