### PR TITLE
A wild empty line has appeared!

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
I've had this as an issue on a downstream.
Mirroring it to here so guys don't have to run into it in the future.

(Probably possible to fix it with proper regex magic, but regex hurts)
#### Changelog

:cl:  
bugfix: No longer shall empty lines crash our scientific progress!
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
imagine not knowing that ! is higher than > and making a fucked up thing

**Comment by Bibby0110** [comment]
oops

**Comment by Bibby0110** [comment]
it compiled okay?

**Comment by Bibby0110** [comment]
> imagine not knowing that ! is higher than > and making a fucked up thing

Technically correct, but my shitcode made it work anyways

**Pull request merged**
