### PR TITLE
Removes Corporate Agents

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
As title says

# Why is this good for the game?
- "Why?"
Saves on file space

- "It's not that much space."
There wasn't much to begin with

- "They don't need to be removed."
Yo mama

# Testing
It will compile, not much to do besides that

# Changelog
:cl:  
rscdel: Corporate Agents are now gone. Don't know what they are? Exactly nobody does, they won't be missed
/:cl:

### CODE REVIEW

**Comment by LassiH** [comment]
not the speedy agents noooo

**Comment by ofscarletdreams** [comment]
i know what they are you FUCK

**Comment by MajManatee** [comment]
Id argue that's not enough of a reasoning

**Comment by 00ze-cyclone** [comment]
Tbh those agents are so obscenely OP you can’t even use them for a bus anyway(unless you count blatant abuse as bus).
Might as well get rid of them, we aren’t going to get any use out of them.

**Comment by neeshacark** [comment]
d'awwww these guys were funny

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
