### PR TITLE
It doesn't even matter... (Engivend Stock Change)

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Adds 2 more compressed matter to the engineering vendor, so that each RCD comes with one charge.
im TIRED of showing up only to see 1-2 RCDs and no matter.
or on a busy shift, 3 or 4 RCDs and one selfish fuck takes them all.

# Why is this good for the game?
no more arguments about people taking more material than they should
common sense
why would you want people to deliberately NOT have ammo

# Changelog

:cl:   
tweak: The engineering vendor now has one compressed matter per RCD instead of 3/5
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
You know the greedy fucks will just take more matter now and leave none for the others

**Review by ToasterBiome — APPROVED** [review]
hugbox

**Comment by ShoziOffical** [comment]
its all fun and games till one engi steal every matter

**Comment by N3D6** [comment]
Make it gib the atmos techs who powergame them

**Pull request merged**
