### PR TITLE
Traitor AI's 20 Nonexistent TCs just for an AI Camera Laser Gun

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
A new AI upgrade disk that can used at an AI Control Console to give an ability to an AI; disk item only obtained from adminbus.

The selected AI gets the ability to enter a burst mode which lets them shoot a laser from any functioning camera every second. It lasts for 30 seconds and be re-activated every 60 seconds. Cameras used in this matter are hit with a heavy EMP.

Installing one of the few AI upgrades (i.e, surveillance/malf upgrade) no longer runtimes.

Traitor AIs start with this ability.

More AI-centric than #20955.

# Why is this good for the game?
Traitor AI is just traitor except you trade all of your TCs to be an AI. Those 20 TCs should get them something special, so here it is without giving them actual malf powers.

# Testing
Shooting with nearby cameras at a distance.
moja-nocam

Shooting with an EMP-proof camera at pointblank range.
moja-cam

# Spriting
No new sprites. This is what button looks like.
image

# Wiki Documentation
Traitor AI gets this ability. Information in documentation above. Mention in the AI's wiki page in the antag section if there is a traitor specific category for it.

# Changelog
:cl:  
rscadd: Only obtainable via a camera laser upgrade disk (or by being a traitor), the AI can get an ability based around lasers and their cameras.
rscadd: This new AI ability lets them enter a burst mode which lets them shoot a laser from any functioning camera every second. It lasts for 30 seconds and be re-activated every 60 seconds. Cameras used in this matter are hit with a heavy EMP.
bugfix: Hitting an AI control console with an upgrade no longer runtimes.
spellcheck: Logging regarding upgrading the AI with disks has better formatting.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
So its exactly the same but its adminbus only? But why

**Comment by Runian** [comment]
> So its exactly the same but its adminbus only? But why

image

**Comment by Moltijoe** [comment]
Ah, didnt see that, ty

**Comment by Moltijoe** [comment]
I still like moja's idea of it being an active where for a duration you can rapid fire shoot, and then it goes on cooldown

**Comment by Moja10** [comment]
Yeah like I said in the previous PR:
Make it so it can shoot rapidly, honestly anywhere between .5 to 1 second per shot, for a limited time, say 30 seconds, and then go on cooldown for 1 minute. Change numbers as you see fit, but that creates sudden burst of action and chaos rather than just 1 stinker every 10 seconds

otherwise, awesome idea

**Comment by JamieD1** [comment]
I mean feels a bit useless, like when will you actually use other then to try and snipe people when they are already low. I mean we can try but it feels like a bit of a noob trap.

**Comment by Bibby0110** [comment]
> I mean feels a bit useless, like when will you actually use other then to try and snipe people when they are already low. I mean we can try but it feels like a bit of a noob trap.

Mojas suggestion would be better, imo

**Comment by Runian** [comment]
@Moltijoe changed. reapprove for balance council if need be
@Moja10 @TheGamerdk suggestion done

**Comment by cowbot92** [comment]
((didnt mean to remove it tried to click on the wrong stuff, lol!))

**Comment by Runian** [comment]
@Moltijoe Testing updated

**Review by Bibby0110 — APPROVED** [review]
Code owner review. Did not perform code review

**Comment by Moltijoe** [comment]
Do not merge label added so manatee doesnt merge it without realizing

**Comment by CrazyDrakkon** [comment]
No podperson is safe

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
