### PR TITLE
Adds Deluxe Agent ID

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

10TC item from uplink, deluxe agent ID, comes with AA. 

# Changelog

:cl:  
rscadd: Added deluxe agent ID to the traitor uplink, comes with AA
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Hmmmm

**Comment by SomeguyManperson** [comment]
wtf

**Comment by Anvilman6** [comment]
What if
we didn't

**Comment by adamsong** [comment]
@SomeguyManperson Why?

**Comment by maxion12345** [comment]
THE
EMAG + AGENT ID FOR ONLY 10 TC
AKA
NOBODY BUYS AGENT CARD ANYMORE
AKA
NOBODY BUYS EMAG ANYMORE
AKA
ELIMINATE THE CONCEPT OF STEALING ACCESS WITH AN AGENT CARD
AKA
THE LAZY MAN'S WAY TO RUSH THINGS WITHOUT LEAVING TRACES
AKA
its just bad idea man

**Pull request closed without merging**
