### PR TITLE
[1984] Appearance banned people can no longer set their accents [1984]

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

suffer

# Wiki Documentation

# Changelog

:cl:  
tweak: Appearance ban applies to accent choice too
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
litteraly 1984

**Comment by Hopekz** [comment]
Would be funnier if it forced a random accent.
You'll be able to get away with it too since everything else rolls for random

**Comment by bruhlookatthisdood** [comment]
i like hopekz's idea

**Review by Hopekz — CHANGES_REQUESTED** [review]
Here's the code to make it work if you want to do that.

Picks a random accent:
pick(assoc_list_strip_value(GLOB.accents_name2file))

**Review by ToasterBiome — APPROVED** [review]
I like hopek's idea too but this will do

**Pull request merged**
