### PR TITLE
Resprites all the PDAs, PDA cartridges and IDs.

### PR DESCRIPTION
**Pull request by War-Tex**
Resprites all the PDAs, PDA cartridges and IDs. PDAs now have a 3/4 perspective, whilst the PDA cartridges and IDs have been given a new look.

oldvsnew
(The detomatrix PDA cartridge was used for the comparison)

All Old vs New PDAs (you can view them better by clicking on em)
oldvsnewpdas

The PDA donator variants:
donatorpdas

Some people were saying the IDs look like DOOM key cards.. I don't see that one

(Doom Keycards)
doomkeycards
vs
(My IDs)
IDs

Ingame Pic
ingamepic

Cap with emag what he gon' do
capwithemag

The second step of the Great (Resprite) Journey.

"There are those who said this day would never come. What are they to say now?" - Prophet of Truth

🆑
tweak: Resprited all the PDAs, PDA cartridges and IDs.
/🆑

### CODE REVIEW

**Review by Partheo — CHANGES_REQUESTED** [review]
Your atmos changes are in this PR by accident.

**Comment by War-Tex** [comment]
> Your atmos changes are in this PR by accident.

lmao yep, just found that out. No clue how to revert those specific changes

**Comment by Partheo** [comment]
Will leave this up for a while to get opinions. Some more pics of what these look like in-game would be appreciated.

The emag is especially important too.

**Comment by jcatjmeow** [comment]
I like the cartridge.
I'm iffy on the IDs. They look too much like dog tags to me. But I do like most of them, maybe if the corners were not snipped off so they looked more like a card shape?
The pda's look awful. The screen is fine, but the outside is just so...noisy.

**Comment by Tipy1802** [comment]
It would be great if you could provide a picture with all the sprites 

I like how the cartridge looks, the PDA is alright but I don’t like the T.T. Honestly the old IDs are better imo but I haven’t seen all the IDs

**Comment by Darkstick** [comment]
The cartridges are a total upgrade, no doubt. But I don't like the PDA and ID card. They look more like doom keys than identifications

**Comment by Hopekz** [comment]
I like the PDA's but dislike the new ID's.

The new ID's just kind of remind me of what every codebase is doing for some reason. Everyone seems to be straightening them out in their art style changes. They're not "ugly" its just not a direction I'd personally like to go with the ID art style.

Nice PDA's +  Better cartrages + "worse" ID's = Neutral from me

**Comment by boodaliboo** [comment]
i like the pdas dislike ids make them square

**Comment by Marmio64** [comment]
neutral on PDAs and IDs, the new cartridges look amazing though, love them.

**Comment by maxion12345** [comment]
Pda with that perspective seems weird. IDs are also in a strange place, like the syringes that were angled. I prefer the angled ones, new IDs just feel too cubey.

**Comment by War-Tex** [comment]
> i like the pdas dislike ids make them square

done

**Comment by War-Tex** [comment]
> The cartridges are a total upgrade, no doubt. But I don't like the PDA and ID card. They look more like doom keys than identifications

I don't get what you mean by this, as they don't look similar at all. I did however change the IDs now to be more square.

doomkeycards
IDs

**Review by Partheo — CHANGES_REQUESTED** [review]
I like the cartridges, although their color is a bit bold/intense.

PDA is nice too, but I think you could make the crew ones look a bit more generic.

The centcom ID and emag need to be more distinct.

Centcom should be immediately distinguishable from a regular ID. Also consider that this is the ID sprite that operatives get.

Emag needs to look more dangerous. The old one has some nice contrast going on at least, yours looks fairly washed out. Consider that this is a very important traitor item, and adjust your design accordingly.

Also, you have staircasing on your wires. Ping me if you want advice on how to make nice curved wires.
image

Side note: I am curious to see what the ID would look like if you had one side square and the other side chamfered like you did before. Could be a best of both worlds sort of thing.

**Comment by Moggram** [comment]
Now, this could just be me but, I like the ideal of Doom key cards. 
Doom ss13 keycard

**Comment by Hopekz** [comment]
The emag looks like a jury-rigged homemade device vs the original feeling of a professional syndicate tool.

Can we maybe either keep the original emag sprite or make something that looks more "professional" rather than glued together?

image

**Comment by Partheo** [comment]
> The emag looks like a jury-rigged homemade device

That's... literally how it always has been.

image

**Comment by Partheo** [comment]
> The emag looks like a jury-rigged homemade device

It's... always been that.

image

> a professional syndicate tool.

It's literally just an ID card with wires and a chip taped onto it. Were you describing yourself?

**Comment by UselessTheremin** [comment]
I like them, but the regular ID cards look bland and too simple of a shape, I would prefer if they stayed diagonal. Other than that, I absolutely love the PDAs and how the new PDAs are more than one shape. Oh also- dont you dare make the clown ID something else than a rainbow gif.

**Comment by Firewolf34** [comment]
I agree with the general sentiment that the PDA and especially the cartridges look great.

However I really don't like the square IDs. I think they should be diagonal, being diagonal also gives more of a Y-axis to click, doesn't make the pixel snipe entirely X-axis dependent.

Personally I think it might be cool to take some cues from the old Yogs pre-base IDs.

I love the work you're doing with these resprite PRs.

**Comment by Partheo** [comment]
Personally, I like the PR overall. The PDAs and cartridges seem to be more or less liked by everyone, so if you were to atomize that into its own PR I would merge it. However, unless you respond to the concerns and feedback about the IDs/Emag, I will be closing this PR in a week. @War-Tex 

Personally I think they look fine, but there are some valid points to listen to here; I do think they could be improved a bit.

**Comment by Partheo** [comment]
Tex has taken his leave so I will be picking up the torch for this PR.

**Pull request closed without merging**
