### PR TITLE
Removes the mapping icons for bar and engine.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request

Personally I HATE these. I find myself trying to pick an object from the bar almost every single time i open boxstation, before realising once again that its a fake icon. Its annoying as hell and provides obscurity to how the system works.

Just makes everything more consistent, more clear, and easier to work with.  Engines does nothing to begin with, mayswell remove the entire folder since its not needed.

# Why is this good for the game?
Nothing player facing

# Changelog
Nothing player facing

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
bro actually falling for the wall painted like a road

Anyway these probably should just be the outlines of the funky shapes so you know where they start and end

**Comment by azzzertyy** [comment]
> bro actually falling for the wall painted like a road
> 
> Anyway these probably should just be the outlines of the funky shapes so you know where they start and end

you do know that though by the passthrough turfs
i dont think theres a situation where it isnt obvious what something is

**Comment by ToasterBiome** [comment]
> > bro actually falling for the wall painted like a road
> 
> > 
> 
> > Anyway these probably should just be the outlines of the funky shapes so you know where they start and end
> 
> 
> 
> you do know that though by the passthrough turfs
> 
> i dont think theres a situation where it isnt obvious what something is

Making a new map reusing the templates (asteroid) thoughts???

**Comment by azzzertyy** [comment]
> > > bro actually falling for the wall painted like a road
> > 
> > 
> > > 
> > 
> > 
> > > Anyway these probably should just be the outlines of the funky shapes so you know where they start and end
> > 
> > 
> > you do know that though by the passthrough turfs
> > i dont think theres a situation where it isnt obvious what something is
> 
> Making a new map reusing the templates (asteroid) thoughts???


https://github.com/yogstation13/Yogstation/assets/42524344/aa1d7174-9276-48d9-9cef-0a4f6c66c711

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
