### PR TITLE
Buffs stechkin + supressor price

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

The stechkin being the same price as the 357 makes no sense, especially considering how weak it is in comparison. This changes the price of the stechkin from 6 tc to ~~4~~ 5 tc, and the price of the suppressor from 3 tc to ~~2~~ 1 tc so you can have a weaker but stealthier weapon for the same price

# Spriting

# Wiki Documentation

# Changelog

:cl:  

tweak: Stechkin costs 5 now
tweak: Suppressor costs 1 tc now 

/:cl:

### CODE REVIEW

**Comment by DeadlyBag** [comment]
Hey!
We have been talking (Balance council) about the prices of the Stechkin & suppressor.
Since theres another Stechkin buff going through soon having the Stechkin be as expensive as a dart pistol doesnt make much sense as its roughly on the same terms as the revolver. 
Suppressors never get used since theres drawbacks to using them (size) and they are also quite expensive for what you are getting.
We think that the Steckin being lowered to 5 TC and the suppressor to 1 TC would be the best thing going forward.

**Comment by solwashere** [comment]
Aye I'll agree, I'll go ahead and change that in a few hours

**Comment by solwashere** [comment]
updated

**Comment by Moltijoe** [comment]
Just replace the changelog rather than making it a strikethrough

**Review by ynot01 — DISMISSED** [review]
Just replace the changelog rather than making it a strikethrough

**Comment by MajManatee** [comment]
i like the strikethrough

**Comment by solwashere** [comment]
1984, strikethroughs are based

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
