### PR TITLE
Revert "Cloning now requires meat."

### PR DESCRIPTION
**Pull request by boodaliboo**
Reverts yogstation13/Yogstation#10970
no one notices it requires biomass and theres no indicator besides a examine that it even uses it, its been a issue i have continually noticed and even then its just tedium to make it

### CODE REVIEW

**Comment by UselessTheremin** [comment]
template

**Comment by boodaliboo** [comment]
> template

no template shows up when you do a revert you should know this

**Comment by Cartlord** [comment]
I've noticed myself that this doesn't even work all the time anyways, I've seen a cloner work with -366% biomass.

**Comment by boodaliboo** [comment]
> I've noticed myself that this doesn't even work all the time anyways, I've seen a cloner work with -366% biomass.

its also just stupid if we had the proposed cloning system that the guy that started with a s and had a long name was working lon

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Templateeee

**Comment by burn1cycle** [comment]
Believe it or not this isn't the first time someone tried "cloning requires meat" you just don't remember because it was so long ago and we removed the requirement for being retarded. I would be over-joyed to see it removed AGAIN for being retarded AGAIN and finally have it known once and for all that this is a retarded feature and to stop implementing it.

**Pull request closed without merging**
