### PR TITLE
Space Pirate Energy Saber Resprite! 

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
**SIKEEEE GOT EMMM** im not a coder, but your still gonna be murderboned the same way by them just now they look cooler while doing it!

Pirate sabers don't flash uneven 2004 color scheme anymore. 

My permission slip: 
image

# Spriting

https://user-images.githubusercontent.com/82983051/211218637-b6835168-b827-4c08-998e-f9e73f28fca5.mp4

newsaber
Aseprite_yHys6I9zTG

# Wiki Documentation
sword

# Changelog

:cl:  

imageadd: Resprites Pirate saber

/:cl:

### CODE REVIEW

**Review by ynot01 — DISMISSED** [review]
misleading changelog

**Comment by KillerOrcaCora** [comment]
HAHAHAHHAHAHAHAHAHAH

**Comment by cuackles** [comment]
give it more seconds on the frames so the glitching effect is not constant

**Comment by cuackles** [comment]
oh nevermind it already has 10 seconds on the first frame

**Review by cuackles — APPROVED** [review]

**Comment by KillerOrcaCora** [comment]
already did for both, backed on like 12-2-1 now

**Comment by cuackles** [comment]
great

**Comment by ReddicusDragon** [comment]
Please do not merge your own PR, nor merge it before 24 hours have elapsed.

**Comment by KillerOrcaCora** [comment]
image

**Pull request merged**
