### PR TITLE
Minsky Signs #4

### PR DESCRIPTION
**Pull request by MayhemSailor**
### Next Iteration of Minsky Signs

This PR adds the following departmental signs:
- Evacuation
- Quantum Hub

Additionally, directional signs for:
- Bridge
- Engineering
- Evacuation
- Medical
- Science
- Security
- Supply

ForPR4

#### Changelog

:cl:  
imageadd: added some icons and images  
/:cl:

### CODE REVIEW

**Review by nesisknesis — COMMENTED** [review]
conflicts

**Comment by athena413** [comment]
yeah

**Comment by alexkar598** [comment]
Merge conflicts, Please fix

**Comment by MayhemSailor** [comment]
close for fix

**Pull request closed without merging**
