### PR TITLE
Adds Headpats (I am dead serious)

### PR DESCRIPTION
**Pull request by Majkl-J**
# Document the changes in your pull request

This adds headpats. As the name implies.
There is no joke here.

# Changelog

:cl:  
rscadd: You can now headpat people to make them feel better
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
I have liked my own PR as I believe it is THAT good

**Comment by BurgerLUA** [comment]
no

**Comment by ynot01** [comment]
i wish someone would pat my head

**Comment by SomeguyManperson** [comment]
Mr headcoder ban this individual immediately

**Comment by YashinHak** [comment]
historical, legendary, if every pr is a step closer to just being splurt, this is a leap

**Comment by Moltijoe** [comment]
sorry i took so long to close this, i was doing a database quiz
anyways, meme PR that adds ERP

**Comment by Maia-J** [comment]
> sorry i took so long to close this, i was doing a database quiz anyways, meme PR that adds ERP

spider-man-norman-osborn

**Comment by Moltijoe** [comment]
bruh, apparently not a meme? gonna at least give this 24 hours then

**Comment by YashinHak** [comment]
please make this into a pr that keeps getting killed but at least once every week comes back from the dead to haunt everyone involved

**Comment by Aquizit** [comment]
In this PR's defense: we already pat borgs. It doesn't say "head pat" because robot might not have a head but I mean... I dunno.

I'm neutral I dun care if this gets merged or not.

**Comment by ReddicusDragon** [comment]
I'm closing this after 24 hours for 2 reasons. Reason one is to attempt to preserve the sanity of Jamie. Reason 2 is this adds a feature that will only serve to increase the amount of weird, borderline creepy shit going on in the server imo.

**Comment by solwashere** [comment]
Sitting back and watching the world burn

**Comment by MajManatee** [comment]
This is WELL beyond the "haha fetish content" things we sometimes have. 

This is just adding in a genuine fetish. Weird thing for people that weren't held or loved enough as a child and need to be "Patted" on the head like an animal to get any emotional gratification.

**Comment by Maia-J** [comment]
> Weird thing for people that weren't held or loved enough as a child and need to be "Patted" on the head like an animal to get any emotional gratification.

I feel called out

**Comment by Hislyna** [comment]
Are yall really scared of a virtual headpat? Go touch some grass. Just say you don't like it and move on, no need for wild reasonings on why its a fetish, why its bad ect. If its added its added, if not, then so be it.

**Comment by BurgerLUA** [comment]
image

**Review by Moltijoe — CHANGES_REQUESTED** [review]
make this tussle someone's hair if they have hair and aren't wearing a hat

**Comment by Hislyna** [comment]
> image

Oh shit my pfp is so out of date

**Review by BurgerLUA — CHANGES_REQUESTED** [review]
make it so that if they have a tail, it wags their tail too

**Comment by Maia-J** [comment]
> make this tussle someone's hair if they have hair and aren't wearing a hat


> make it so that if they have a tail, it wags their tail too

I am willing to do these as a compromise

**Comment by Maia-J** [comment]
But only one of the two

**Comment by MajManatee** [comment]
that makes it worse

**Comment by Therandomhoboo** [comment]
I've never seen so many people shit their pants over head pats before.

God damn it yogstation, keep up the hijinks

**Comment by JamieD1** [comment]
No

**Comment by SomeguyManperson** [comment]
> No

don't worry jamie hisa was lying headpats aren't real
thank
GOD

**Comment by DylonBR** [comment]
Headpats? What next? Kissing? The slippery slope is real

**Comment by Maia-J** [comment]
> Headpats? What next? Kissing? The slippery slope is real

Kissing is allowed actually, we just do not have it mechanically

**Comment by Snellie12** [comment]
The more I ever look at this the more disappointed I feel for this entire community. Not because of the PR...but because people think headpats are sexual.

**Comment by namjay1170** [comment]
Bloodsuckers was and still is fetish content, how are headpats fetish? you live in a time where you have to pay money to be a fetish race ((donators get felinid)) but patting a head is across the line. lets take a look at *help oh look you can hold hands WAIT YOU CAN KISS???? FETISH CONTENT IN MY YOGS???? shit man you're right honestly lets remove the ability to hold hands, moan, wag, smile, kiss hell lets get rid of shaking hands just to be sure nothing could possibly be warped by your twisted mind as a "fetish" but lets forget the forms of vore that already exist thats perfectly fine.

**Pull request closed without merging**
