### PR TITLE
Refactors IPC, Preternis, and Ethereal charging to be more consistent + minor tweaks

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Refactors the charge levels of all the power-hungry species to so that the code is much easier to work with, and generalizing something to work with everything 

Also, when at low charge preternis will slow down and start suffocating instead of just dropping dead randomly when they hit zero, and radiation can charge ethereals now because I thought it would be funny.

# Why is this good for the game?

Makes the code easier to maintain, makes ethereals more fun and unique, and makes preternis death from low charge less out of nowhere.

# Wiki Documentation

Mention that radiation charges ethereals on their wiki page.

# Changelog

:cl:  
tweak: preternis now slow down and suffocate when low on charge instead of just instantly dropping dead when they hit zero
tweak: liquid electricity can now actually charge species that run on electricity
tweak: radiation charges ethereals now
experimental: preternis, ethereal, and IPC charging have been refactored, please report any bugs you find
/:cl:

### CODE REVIEW

**Review by Moltijoe — APPROVED** [review]
code looks good, but i have this nagging feeling that something's being forgotten and is gonna break

**Comment by ShoziOffical** [comment]
> code looks good, but i have this nagging feeling that something's being forgotten and is gonna break

i hope i wont lose all my charges upon spawning into the round

**Comment by iamthesilly** [comment]
> i hope i wont lose all my charges upon spawning into the round

Won't happen, I tested that

**Comment by ShoziOffical** [comment]
> > i hope i wont lose all my charges upon spawning into the round
> 
> Won't happen, I tested that

just a joke, i know you are a good

**Pull request merged**
