### PR TITLE
Scrubs the second "m" from the last mentions of "Centcomm" and the capital "T" from all mentions of "NanoTrasen"

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
I saw that "Centcom" with one m is the standard, so I corrected the two outliers.
Also fixed another typo, very minor stuff.
UPDATE: Also corrected all mentions of "NanoTrasen" to "Nanotrasen".

# Why is this good for the game?
Grammar good.

# Testing
Hopefully isn't needed.

# Changelog
:cl:  
spellcheck: Scrubbed the second "m" from the last mentions of "Centcomm"
spellcheck: All mentions of "NanoTrasen" have also been corrected to "Nanotrasen"
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
semi-related

image

**Comment by AMyriad** [comment]
> semi-related
> 
> image

good idea, I'll get that here too then

**Review by ReddicusDragon — APPROVED** [review]
Seems good to me

**Review by JohnFulpWillard — COMMENTED** [review]
There's a unit test in ``check_grep.sh``, lines 41 to 47, preventing the use of 'centcomm', can you expand that to include NanoTrasen?

**Comment by AMyriad** [comment]
unless there's an issue I don't see, this should be done now

**Review by Moltijoe — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]
Sounds good boss

**Pull request merged**
