### PR TITLE
Adds department-specific footwraps

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Adds four new, department-specific, footwraps! For Science, Engineering, Cargo, and Medical.

Adds the new footwraps to their relevant vendors.

Engineers and medics will spawn with their new shoes rather than the default footwraps.

back
Front
left
right

image
this is the most recent version of medical shoes
# Wiki Documentation

New footwraps will have to be added to the clothing pages. 

# Changelog

:cl:  
rscadd: Adds four new footwraps
:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Waiting for my lazy spriter to finish spriting so I can add them

**Comment by nmajask** [comment]
Shit

**Comment by JamieD1** [comment]
The amount of lizard feet prs is getting on suspicious levels.

**Comment by MajManatee** [comment]
To be fair, the original idea was just these, but cuack really wanted to have the other ones

**Review by nesisknesis — APPROVED** [review]

**Review by nesisknesis — CHANGES_REQUESTED** [review]
Actually I meant to say the medical footwraps are not consistent with the rest of them, as in there's no hole where the foot goes

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
