### PR TITLE
Adds shutters/bolt button to medbay to contain the tiders

### PR DESCRIPTION
**Pull request by maxion12345**
# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Document the changes in your pull request

Reinforces medbay entrance. CMO can now completely cut off the entrance from the rest of the station in case of plague/massive tide

# Wiki Documentation
n/a
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added some new funky buttons to CMO office so you can close medbay 
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
If this spot was meant to keep people out there would be shutters/rwindows there already, see https://github.com/yogstation13/Yogstation/pull/12555

**Comment by maxion12345** [comment]
> If this spot was meant to keep people out there would be shutters/rwindows there already, see #12555

getting real tired of "UHHHHHHH I HAVE 10 BRUTE DAMAGE IM GONNA SMASH DOWN DUH WINDOWS AND SPAM DUH AIRLOCK UNTIL I GET TWEATMENT DURRRRR"

**Comment by ShatteredParadox** [comment]
Thank you. You are my hero

**Comment by JamieD1** [comment]
@wejengin2

**Comment by Moja10** [comment]
Barring off medbay is what you aren't supposed to do during a disease outbreak, wat

**Comment by maxion12345** [comment]
> Barring off medbay is what you aren't supposed to do during a disease outbreak, wat

in case someone in med gets one and decides they want to ignore everyone screaming at them to stop walking out of medbay

anyways it'll also keep the sick plague rats from trying to bust into medbay and cure themselves and give the chemists time to actually make a cure

**Comment by maxion12345** [comment]
ah fuck me merge conflict

hnnnng you know what I'll do this later after the other mapping prs get merged

**Pull request closed without merging**
