### PR TITLE
Penlight can now be made in the Lathe

### PR DESCRIPTION
**Pull request by Hopekz**
Fixes issue #6434
Here you go Lyis

Costs 100 metal and 20 glass.

#### Changelog

:cl:  Hopek
rscadd: Penlight can now be made in the Lathe
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Already tested. It worked.

**Comment by boodaliboo** [comment]
TO OVER POWERED PLEASE DONT DO

**Comment by Hopekz** [comment]
> TO OVER POWERED PLEASE DONT DO

MY PLAN TO MAKE PENLIGHTS EVERYWHERE IS ALREADY IN MOTION YOU FOOL YOU CANNOT STOP THIS. WORLD PENLIGHT DOMINATION IS FINALLY THE REALITY EVERYONE WILL EXPERIENCE

**Comment by CMOisLing** [comment]
Medbay powercreep

**Pull request merged**
