### PR TITLE
Remove repeated message chat badge animation that causes huge performance issue for low-end users and replaces it with flashing

### PR DESCRIPTION
**Pull request by warface1234455**
# TESTMERGE REQUEST

gotta make sure it works for other users in game

# Document the changes in your pull request
Remove repeated message chat badge animation that causes huge performance issue for low-end users and replaces it with flashing

# Why is this good for the game?
this animation happens once is fine but with 1000 actions at the same time causes the entire chat screen to flicker and cause lag, potentially crashing a client

# Testing

ATTTT

# Changelog

:cl:

experimental: Remove repeated message chat badge animation that causes huge performance issue for low-end users and replaces it with flashing
/:cl:

### CODE REVIEW

**Review by ynot01 — APPROVED** [review]

**Review by ynot01 — APPROVED** [review]

**Comment by ToasterBiome** [comment]
This is actually related to looking up/down being expensive, i will fix this when i do a bulk multiz bug fixing update

**Comment by LoliconSlayer** [comment]
FIGHT! FIGHT! FIGHT! FIGHT! FIGHT! FIGHT! FIGHT! FIGHT! FIGHT!

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
test on something that isn't look up down left right

**Comment by ShoziOffical** [comment]
> test on something that isn't look up down left right

Dude thats just an example for the repeated messages

**Comment by ShoziOffical** [comment]
> This is actually related to looking up/down being expensive, i will fix this when i do a bulk multiz bug fixing update

This has nothing to do with this, it's about the animation flickers when you type something twice

**Comment by ShoziOffical** [comment]
> test on something that isn't look up down left right

wish granted

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
