### PR TITLE
Beware of Meaty Ores, for the Meatball Man comes

### PR DESCRIPTION
**Pull request by fluffe9911**
A great surplus of Meat has been spotted near the station!

Beware, for once in a blue moon the station may pass through a even greater density of meaty ores than normal, bringing new types of meaty ores. Rumor has it, the dreaded Meatball Man might even be hidden within, ever-consuming even as they spread meat to the universe.

Pr by Buggy123 ported by me https://github.com/tgstation/tgstation/pull/49271
🆑
add: The Nanotrasen Meateorology Department has reported that the station is passing through a extra-meaty region of space. Meaty Ore storms may sometimes be substantially larger. This still wouldn't be particularly dangerous, if not for the Meatball Man... by Buggy123
/🆑

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Real shit, full support

**Comment by redmoogle** [comment]
Im sorry, wtf did I just read

**Comment by fluffe9911** [comment]
for reference https://www.youtube.com/watch?v=ErQHVUQ6QCk&t=5s

**Review by Partheo — CHANGES_REQUESTED** [review]
How common is this? The sprite is really out of place. I don't mind if it's a rare event though.

**Review by Partheo — APPROVED** [review]
image

**Comment by Jarod1200** [comment]
now THIS is gaming

**Comment by jcatjmeow** [comment]
Another lolrandom event that isn't actually *fun*.

If this hits you, you instadie. And it causes massive damage to random parts of the hull.

Strongly against.

**Comment by boodaliboo** [comment]
> Another lolrandom event that isn't actually _fun_.
> 
> If this hits you, you instadie. And it causes massive damage to random parts of the hull.
> 
> Strongly against.

you do know meteors already exist? this doesnt do anything but add a percent ontop of a percent for a simple mob to spawn

**Comment by Jarod1200** [comment]
make the chef able to suplex the meatball man like the RD can suplex an immovable rod

**Comment by Marmio64** [comment]
make chefs deal 50 damage per punch against meatballmen.

**Comment by ynot01** [comment]
> If this hits you, you instadie.

according to the code (incredibly all over the fucking place what are these diffs???) the meatball man is much, MUCH slower than any other meteor and you are unlikely to die to it unless you are AFK

**Review by JamieD1 — APPROVED** [review]

**Comment by Rdrazga** [comment]
Im not going to lie, you made me watch that video just to figure out what the meatball man is, and my brain is now broken.

**Pull request merged**
