### PR TITLE
Revert "Updates Byond to 1589. Special offer, comes with extools for free for a limited time"

### PR DESCRIPTION
**Pull request by Simplehorror**
Reverts yogstation13/Yogstation#16389
this broke my version

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Stop playing on Linux

**Comment by Simplehorror** [comment]
it wouldnt even be that bad if there was a backup atmos system

**Comment by ReddicusDragon** [comment]
@TheGamerdk close this.

**Comment by Simplehorror** [comment]
dude get off his dick

**Comment by ReddicusDragon** [comment]
> dude get off his dick

I have said it before but it is not our duty nor place to support unsupported setups. Linux falls under this.

**Comment by LoliconSlayer** [comment]
Playing on unsupported versions is your problem, don't make it everyone else's

**Comment by Simplehorror** [comment]
how is 1583 unsupported

**Comment by LoliconSlayer** [comment]
The Linux version of byond is unsupported

**Comment by Simplehorror** [comment]
not for servers

**Comment by Simplehorror** [comment]
and i don't use linux im on a bsd

**Comment by ReddicusDragon** [comment]
> and i don't use linux im on a bsd

The terms are interchangeable. Both are Unix-like. We are using Linux to denote unix-like systems in general. Unix-like versions of byond are only supported for compiling and hosting, not playing. Update your version of byond, as 1589 is available for unix-like operating systems.

**Comment by Simplehorror** [comment]
> > and i don't use linux im on a bsd
> 
> The terms are interchangeable. Both are Unix-like. We are using Linux to denote unix-like systems in general. Unix-like versions of byond are only supported for compiling and hosting, not playing. Update your version of byond, as 1589 is available for unix-like operating systems.

yeah i'm saying hosting doesnt work on my byond version

**Comment by LoliconSlayer** [comment]
If you're not on windows, your version of Byond isn't supported. If you can't get it to work then that's your problem, don't try to change the server's version of Byond like a fool.

**Comment by Simplehorror** [comment]
> If you're not on windows, your version of Byond isn't supported. If you can't get it to work then that's your problem, don't try to change the server's version of Byond like a fool.

yes it is, byond.com says linux is supported for hosting servers

**Comment by LoliconSlayer** [comment]
> > If you're not on windows, your version of Byond isn't supported. If you can't get it to work then that's your problem, don't try to change the server's version of Byond like a fool.
> 
> yes it is, byond.com says linux is supported for hosting servers

If your problem is just you can't host it then change it locally, what the hell are you trying to change Yogstation's version for

**Comment by ReddicusDragon** [comment]
> > If you're not on windows, your version of Byond isn't supported. If you can't get it to work then that's your problem, don't try to change the server's version of Byond like a fool.
> 
> yes it is, byond.com says linux is supported for hosting servers

uninstall and reinstall byond, beyond that there is nothing more we can do for you.

**Comment by Simplehorror** [comment]
then my master branch is out of sync and i cant test my prs

**Comment by ReddicusDragon** [comment]
> then my master branch is out of sync and i cant test my prs

uninstalling and reinstalling byond will not affect your master branch

**Comment by LoliconSlayer** [comment]
Tough shit figure it out yourself

**Comment by Bibby0110** [comment]
Unfortunately Yogstation only officially supports 1589. If you find any problems with 1589 feel free to detail them in a new PR

**Comment by Bibby0110** [comment]
The server is hosted on Linux at 1589 for reference. Client versions do not have to match to connect.

**Comment by Simplehorror** [comment]
1589 doesnt work on my computer

**Comment by Bibby0110** [comment]
> 1589 doesnt work on my computer

If you provide details of your setup in #development-public we may be able to help, but the only supported version for hosting is 514.1589

**Comment by Simplehorror** [comment]
i am not in the discord

**Comment by ReddicusDragon** [comment]
> i am not in the discord

who do you play in game

**Comment by Bibby0110** [comment]
> i am not in the discord

Unfortunately in that case we can’t provide any more support than telling you to uninstall BYOND and make sure you install 514.1589

**Comment by Simplehorror** [comment]
> > i am not in the discord
> 
> who do you play in game

why

**Comment by ReddicusDragon** [comment]
> > > i am not in the discord
> > 
> > 
> > who do you play in game
> 
> why

I have no reason, I am curious

**Comment by Simplehorror** [comment]
then there is no reason to tell you

**Comment by ReddicusDragon** [comment]
> then there is no reason to tell you

fair enough

**Pull request closed without merging**
