### PR TITLE
you can now go full undertale mode with the flower tendril loot

### PR DESCRIPTION
**Pull request by LazennG**
# Document the changes in your pull request

I'm changing the way emberflowers work a bit: Now named to 'enchanted flowers' because they're no longer orange. you still have to do a 1.5 second channel to make normal fauna friendly towards you, but now you can tame megafauna after hitting them with the item 35 times. Additionally, you can call tamed normal fauna to your location as long as you're not on the station z level after using it inhand with a 1 minute cooldown. 

# Spriting

image

# Wiki Documentation

for https://wiki.yogstation.net/wiki/Shaft_Miner#Necropolis_Chest_Loot
in the part where emberflowers are, change the sprite, change the name to 'enchanted flowers,' and mention how it takes 35 hits to tame a megafauna, along with being able to summon tamed creatures by using the flowers inhand.

# Changelog

:cl:  Lazenn, @Chubbygummibear @ToasterBiome @KillerOrcaCora 
tweak: tweaked necropolis flower loot a bit
imageadd: added new sprite for the flowers
/:cl:
thanks to chubby, baiomu, and orca for their assistance in coding and spriting

P.S yes i know about the 40 commits i had to reinstall vsc and this won't show up again in future prs

### CODE REVIEW

**Comment by Mqiib** [comment]
Are you sure being able to tame what is generally mostly unkillable on-station is a good idea?

**Comment by VaelophisNyx** [comment]
From what it sounds like, you can't use it outside lavaland.

**Comment by LazennG** [comment]
> From what it sounds like, you can't use it outside lavaland.

lastminute realized a way to make it work as long as the user isn't stationside so just gonna do that in a sec

**Comment by SomeguyManperson** [comment]
Do not let this teleport megafauna or i will kill you

**Review by KillerOrcaCora — APPROVED** [review]
Amazing sprite was mind-shattering how good it is the colors, the textures, the perfect execution of banding. I downloaded the sprite on my phone and showed it to my mother, and she has been in a coma ever since with nothing but a smile on her face and a tear of joy that slowly trickles down her face in an ever-lasting bliss. I don't usually say this, but...Thank you for expanding my eyes on what it truly means to make a sprite god bless you and your entire generation, and may they prosper for times to come.

**Comment by KillerOrcaCora** [comment]
What’s a undertail?

**Pull request merged**
