### PR TITLE
Donor hats now get placed on borgs

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Roundstart borgs get their selected donor hat, and hats are no longer dropped on module selection

# Changelog

:cl:  
tweak: borgs can spawn with donor hats if enabled in preferences
tweak: borgs no longer drop hats on module change
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
if you get a module reset via cutting wires will it still drop the hat?

**Comment by adamsong** [comment]
Probably not

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Can you add a toggle for borg specific hatting? with your donor hat on a human, you have the option to throw it down or never put it on in the first place.

**Comment by Mosslick** [comment]
Cringe

**Comment by adamsong** [comment]
> Cringe

Thank you for your feedback

> Can you add a toggle for borg specific hatting?

Sounds like a lot of work

**Comment by ToasterBiome** [comment]
> > Cringe
> 
> Thank you for your feedback
> 
> > Can you add a toggle for borg specific hatting?
> 
> Sounds like a lot of work

🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺

**Comment by adamsong** [comment]
Added a preference toggle

**Review by ToasterBiome — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
