### PR TITLE
Blocking Rework

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

This reworks blocking into a right-click action instead of random chance. Holding right click with combat mode enabled will block incoming attacks in the direction of your cursor with any held items that are capable of doing so, causing some stamina damage to yourself in the process (or oxygen damage if stun-immune). Holding block will also slow you down slightly and cannot be done while attacking.

Different items can block different things in different ways, for example most melee weapons cannot block ranged weapons but if the block is timed correctly, can parry to increase their blocking power. Shields generally have a higher blocking power but most cannot parry and take damage when blocking attacks.

There are also a few special cases, such as energy swords and other similar weapons deflecting laser-like projectiles when blocking them, dual energy swords and the bo staff being able to block in any direction, and the chaplain's holy weapons having a higher blocking power against attacks from cultists.

Additionally, certain exceptionally strong weapons like rockets, cannonballs, and supercharged vxtvul hammers cannot be blocked and will disarm you if you try.

# Why is this good for the game?

This rework changes blocking to be a tactical decision rather than completely passive, making combat more fun in general. Blocking by random chance is boring and the way it stacks makes it extremely easy to abuse..

# Testing

https://github.com/yogstation13/Yogstation/assets/93578146/53ad11b1-4915-47f1-a52b-5e871d53c5e5

# Wiki Documentation

Later

# Changelog

:cl:  
experimental: Removes block chance, adds right-click blocking
/:cl:

### CODE REVIEW

**Comment by ofscarletdreams** [comment]
does it make the tink sound from blood cult shields if parrying melee

**Comment by iamthesilly** [comment]
> does it make the tink sound from blood cult shields if parrying melee

Yes

**Comment by MommaDragon** [comment]
Make it clear if it's a parry or a block with sounds (and text), perhaps?

**Comment by wonderinghost** [comment]
image

**Comment by iamthesilly** [comment]
> Make it clear if it's a parry or a block with sounds (and text), perhaps?

Yeah it has a different sound when parrying as opposed to blocking

**Comment by PibeCantina** [comment]
Does it have a cooldown?
Can i block and attack at the same time?

**Comment by iamthesilly** [comment]
> Does it have a cooldown? Can i block and attack at the same time?

You can't block and attack at the same time, and parrying does have a cooldown but blocking normally doesn't.

**Review by AMyriad — APPROVED** [review]
map ist gut, godspeed with the rest

**Comment by LassiH** [comment]
isnt this a buff to every item that can block by giving them 100% block if you press right click

**Comment by iamthesilly** [comment]
> isnt this a buff to every item that can block by giving them 100% block if you press right click

Yes and no. It lets you have a guaranteed block, but it causes you stamina damage and you can't attack at the same time.

**Comment by LassiH** [comment]
> > isnt this a buff to every item that can block by giving them 100% block if you press right click
> 
> Yes and no. It lets you have a guaranteed block, but it causes you stamina damage and you can't attack at the same time.

so if you got attacked by a tot you can just take out a ancient saber and ignore  hits while calling for help
also does it prevent you from using secondary hand ?

**Comment by iamthesilly** [comment]
> so if you got attacked by a tot you can just take out a ancient saber and ignore hits while calling for help

You can only block in the direction you're facing, they can just walk behind you while you're typing. Not that you'd be typing very fast with one hand anyway.

Also yes it does just cancel the block if you try to do anything else.

**Comment by LassiH** [comment]
> > so if you got attacked by a tot you can just take out a ancient saber and ignore hits while calling for help
> 
> You can only block in the direction you're facing, they can just walk behind you while you're typing. Not that you'd be typing very fast with one hand anyway.

"block incoming attacks in the direction of your cursor " is it where your character is facing or where your cursor is facing ? and you can always walk into a corner to give yourself time

**Comment by iamthesilly** [comment]
> "block incoming attacks in the direction of your cursor " is it where your character is facing or where your cursor is facing ? and you can always walk into a corner to give yourself time

It makes your character face your cursor. Also do keep in mind you can't block forever, if you try you'll eventually get knocked down and disarmed.

**Comment by LassiH** [comment]
how does it work for the mech weapons with block ?

**Comment by iamthesilly** [comment]
> how does it work for the mech weapons with block ?

Mechs still use deflection chance, I haven't changed that system (yet)

**Comment by LassiH** [comment]
is the slowdown 0.5 ? it would make blocking near useless if you have to chase people
and does the makeshift desword have 360 block too ?

**Comment by iamthesilly** [comment]
> is the slowdown 0.5 ? it would make blocking near useless if you have to chase people

Yes.

> and does the makeshift desword have 360 block too ?

Also yes, and so does the bo staff.

**Comment by LassiH** [comment]
what about the adamantite shield from xenobiology its only purpose is to block and already gives a slowdown for just holding it or the energy shields and do deswords reflect laser projectiles when not blocking

**Review by Moltijoe — APPROVED** [review]
can't find anything wrong, but with a pr this large it's inevitable that some bug is going to surface

you have a pretty good track record of fixing bugs you cause, so i'm sure it'll be fine

**Pull request merged**
