### PR TITLE
Revert "Adds the rest of the roundstart race languages to multilingual quirks"

### PR DESCRIPTION
**Pull request by JamieD1**
Why..

### CODE REVIEW

**Comment by MajManatee** [comment]
Lizards speaking felinid did make me pretty suicidal

**Review by ReddicusDragon — COMMENTED** [review]
i approve of this

**Comment by Hislyna** [comment]
So why are you removing a feature that people enjoy and brings RP?

**Comment by solwashere** [comment]
Bad PR
Quirk is decently expensive and has the opportunity to add an extra layer of RP to a character, no good reason to remove it besides "it's cringe", although I think taking away from people's harmless fun is cringe

**Comment by adamsong** [comment]
I see no problems with people knowing one extra language of their choosing.

**Pull request closed without merging**
