### PR TITLE
Makes Fire Extinguishers Bulky (Adv. Fire Extinuishers & Mini Extinguishers Exempt) + Adds Mini Extinguishers To Mining Vendor + Survival Boxes & Makes Non-Pocket Extinguishers Hold More

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

idk man just
doesn't make much sense
sucks for balance (when the sling has no consequences from fire because they just whip out one of 5 fire extinguishers in their bag?)
also this makes advanced extinguishers more unique other than foam contents.
also also gives you reasons to bother printing mini extinguishers from the autolathe

additionally makes normal and advanced extinguishers larger (100u/150u respectively) as a compromise for making normal extinguishers bulky.

# Wiki Documentation

Would have to be documented I'm pretty sure, on whatever page fire extinguishers are covered?

# Changelog

:cl:  
tweak: red fire extinguishers are now bulky
tweak: puts 1 pocket fire extinguisher in every survival box
tweak: pocket fire extinguishers can now be bought in the mining vendor (and golem/free-miner vendors) for 50 points
tweak: normal and advanced extinguishers are 100u and 150u volume respectively
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
miner nerf

**Comment by VaelophisNyx** [comment]
miners can just buy mini extinguishers in the vendor
this changes nothing other than now they don't steal station-side extinguishers?

**Comment by ToasterBiome** [comment]
> miners can just buy mini extinguishers in the vendor this changes nothing other than now they don't steal station-side extinguishers?

there's none in there besides the free one if you redeem a crusher

also mining base

**Comment by VaelophisNyx** [comment]
the-
wait I've seen a mini extinguisher in the vendor for points tho

**Comment by Runian** [comment]
you can print a mini-extinguisher at an autolathe
image

**Comment by VaelophisNyx** [comment]
I mentioned this much in the PR

**Comment by ghost** [comment]
> sucks for balance (when the sling has no consequences from fire because they just whip out one of 5 fire extinguishers in their bag?)

Okay lets then make shadowlings instantly dust when they get even one stuck of fire, WHY NOT???

**Comment by TheRyeGuyWhoWillNowDie** [comment]
incendiary weapons (and anything that lights people on fire in general, like fireball) now useless because everyone gets a fire extinguisher roundstart. also completely and totally cucks blazing oil blob, also makes taking a fire extinguisher worthless except for bashing someone with because they're bulky and only have slightly more water than the miniature ones

**Comment by VaelophisNyx** [comment]
look, no one will be happy in any direction here
if I don't give people pocket extinguishers they're "useless"
if I do they're "overpowered"
if I leave extinguishers normal size it won't fix the issues with their balance

**Comment by ghost** [comment]
Just don't change fire extinguishers they are already okay

**Comment by VaelophisNyx** [comment]
> Just don't change fire extinguishers they are already okay

but they demonstrably aren't ok. You can just walk around with 300u of water in your back pack and not care very easily.

**Comment by ghost** [comment]
Otherwise fire is a stun with some damage, and if you use a fire shotgun slug or a flamthrower you get a weapon that is litteraly stronger then a fucking taser(because tasers doesn't deal damage).

**Comment by neeshacark** [comment]
> > Just don't change fire extinguishers they are already okay
> 
> but they demonstrably aren't ok. You can just walk around with 300u of water in your back pack and not care very easily.

why not make having a roundstart extinguisher a pref that is off by default, that way incendiary ammo might work sometimes? personally though i think the reasons are kinda weak, logic isn't something that should be considered in cases like this.

maybe instead make it so you can only fit one extinguisher in your bag?

**Comment by VaelophisNyx** [comment]
> why not make having a roundstart extinguisher a pref that is off by default

because I will not touch preference code, I went through that hell once before.

> maybe instead make it so you can only fit one extinguisher in your bag?

Because that is not a system we *have*

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
