### PR TITLE
The ORM will now play a "ping" when you claim mining points.

### PR DESCRIPTION
**Pull request by ghost**
# Github documenting your Pull Request
**Untested, webedited..** [Requested by one of our donors on the forums.](https://forums.yogstation.net/threads/firewolf34s-super-idea-list-2021-07.23738/)

This makes claiming any points from the ORM cause a satisfying "ping" sound. This will help let people know what jackass is running off with their ORM points, aswell as injecting dopamine directly into the veins of miners because the sound is just that satisfying. The sound is the same one used when a positronic brain activates.

# Wiki Documentation
The ORM makes a ping sound whenever you claim points, boosting the survival rate of our [more](https://cdn.discordapp.com/attachments/134720091576205312/859723171513761792/unknown.png) [suicidal](https://cdn.discordapp.com/attachments/134720091576205312/859723129554599966/unknown.png) [miners](https://cdn.discordapp.com/attachments/134720091576205312/859723007839961098/unknown.png) to 100 percent!

# Changelog

:cl:  
rscadd: the ORM now emits a "ping" whenever you claim points
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
oh fuck he's going

**Comment by ghost** [comment]
> oh fuck he's going

Ain't no brakes on this coderbus..

**Comment by Firewolf34** [comment]
Yessss!! This will make those mining points ***extra*** addictive!

imagine all the sweet ores those miners will be dragging in 🎉 

I think this is just a much needed UI touchup. So many of our UI and even some items are lacking any sounds or feedback of their use, but lil touches like this are the polish that gives games substance. 

Thanks for coding the suggestion!

**Review by adamsong — APPROVED** [review]
Simple enough change, gotta train the miners somehow

**Pull request merged**
