### PR TITLE
Snappop shuttle now has a brig, now does not have a REAL giant pit or a "Greentext"

### PR DESCRIPTION
**Pull request by jcatjmeow**
### Intent of your Pull Request
This shuttle is pretty cool EXCEPT for the big fucking pit and the haha xd greentext. So I fixed it.

Plus it's a personal pet peeve of mine to have shuttles that do not line up with ALL the airlocks. 

Also added: Flashers for both brig and cockpit

Compiled, not tested but I think the accesses on the airlocks are good? I hope? screm

And yes this is part of my mrp stuff. 
#### Changelog

:cl:  
rscadd: Added a proper brig to snappop, added a door, added flashers and a fake chasm brig tile  
rscdel: Removed the real chasm and the greentext book from the snappop shuttle
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
I like the shuttle as it is but you do have a valid point. Will review in a bit

**Review by patpol4 — CHANGES_REQUESTED** [review]
dreamseeker_GInNK4JpjL

This looks gross, i don't think this shuttle should even have a designated sec area. I can't accept this change as is. How about something like this? 
dreamseeker_gLyauOKE8k
Removes the lrp chasm and greentext, gives the crew something fun, makes it pleasant to the eye.

**Comment by jcatjmeow** [comment]
> This looks gross, i don't think this shuttle should even have a designated sec area.

I disagree, I think it NEEDS a designated sec area, same as every other shuttle.

Because like, think about it this way. If there is no brig, there is zero incentive to keep prisoners alive or bring them with you. How it was with the old shuttle was you'd just throw them in the chasm. If we don't have any sort of brig, prisoners will get executed or left to rot on the station, and that's lrp as far as I'm concerned, plus it takes some of the fun that can potentially come from last minute rescues.

If you have suggestions on how to make it look better be my guest but I want the sec area, that's like half the entire point of the pr.

I don't have to go with the chasm tiles, I did just do that to keep with the original chasm look. But I could easily do something else, maybe using the ballpit tiles? Maybe something soft like a padded cell? Idk

**Comment by TheLinuxOS** [comment]
I like what wejengin suggested, I dont believe a shuttle that is meant to be a clown shuttle should have a designated brig area and the layout he suggested looks nice to me

**Comment by patpol4** [comment]
I just don't feel like every shuttle needs to be up to standards and equipped with the exact same rooms/machinery, especially when it's evident that it's not a serious shuttle and instead a gimmick one. Wouldn't it be better to go along with the gimmick rather then making all shuttles almost the same? If you really want the sec area, maybe try a ballpit and beds, that could look better than chairs on chasm. I will accept that for the sake of mrp but my point about gimmick shuttles stands, they are supposed to be unique.

**Comment by jcatjmeow** [comment]
Gimmicks should never impede or ruin gameplay and roleplay.

The gimmick of snappop is the snappops, not the lack of a brig

**Comment by jcatjmeow** [comment]
@wejengin2 ballpit looks a bit ugly, I think the sprite itself is kinda bad, but how does this look?

I could always go back to regular floors, with anti-sec graffiti on them I think it would look fun

**Comment by athena413** [comment]
> i don't think this shuttle should even have a designated sec area.

ALL non-emag shuttles need a sec area to shove prisoners into.

**Comment by maxion12345** [comment]
You fools
The pit is the brig. They'll redtext anyways

**Review by patpol4 — APPROVED** [review]
Map is fine, we went with this as a compromise :
vivaldi_thUdzI9wpr

**Pull request merged**
