### PR TITLE
[Space Bar] Aquizit's favorite map gets MORE STUFF

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

Me: damn I can't cook pizza I need a tomato
Also me: I'll make my own damn tomatoes!!!
Small hydroponics area added next to kitchen.

Other odds and ends: sink added to kitchen so making dough is more convenient because water. Added hoochmaster since every bar has one on station.

image

# Changelog

:cl:  
mapping: Small hydroponics area added to Space Bar kitchen
mapping: Hoochmaster and chem heater added to Space Bar
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image

Stunning view

**Comment by Aquizit** [comment]
of all the things I miss.............

**Review by ToasterBiome — APPROVED** [review]

**Comment by MajManatee** [comment]
Not really a fan of giving the space bar a full chem setup

**Comment by Aquizit** [comment]
A space bartender cannot leave their bar (they are forcibly returned if they leave the z-level), so there's no risk of the bartender themselves making shit and causing trouble. As for other people coming in to use it, there are much easier ways to get access to these machines, like breaking into the psych's office.

**Comment by Moja10** [comment]
I'm fine with the chem dispenser and botany area, I like the PR!

**Comment by Aquizit** [comment]
Final adjustments: Removed chem heater since it's not *really* needed. HoochMaster stays since every bar has one (on station, anyway, I should know I made that PR). Table to put metal and glass sheets on with the new free tile since I'm weird and hate dropping the extra stuff on the floor since it cannot all fit into the lathe.

**Pull request merged**
