### PR TITLE
Revert "Adds snails"

### PR DESCRIPTION
**Pull request by Amelia0010**
Reverts yogstation13/Yogstation#6678

No snails allowed.

### CODE REVIEW

**Comment by Nickvr628** [comment]
Why

**Comment by Readystorm546** [comment]
#6707 Fuck off nich

**Comment by Amelia0010** [comment]
it wasn't requested by AsV, dunno how you'd even get to the conclusion that it was "more than likely" requested by him.

As for the `why`, I'm not gonna give up on my stance of "no snails allowed", especially not because someone merged something that isn't even included in the compile, on the one day where both headcoders happened to be busy with something else

**Comment by Szyszkrzyneczka** [comment]
Oppresive Headcoder wants to remove snails, we must oppose him

**Comment by AsV9** [comment]
now I don't actually care so long as those fucking whitespace changes get sent to oblivion

**Review by ThatLing — CHANGES_REQUESTED** [review]
You forgot deleting the file from the dme

**Comment by Readystorm546** [comment]
> You forgot deleting the file from the dme

Its not in the DME #6707

**Comment by ThatLing** [comment]
Oh ok then

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
