### PR TITLE
Xeno bar

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request

Adds a new bar template for a xeno-themed bar

# Changelog

:cl:  
rscadd: Adds a new bar template for a xeno-themed bar
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
image

**Comment by Xoxeyos** [comment]
downvoting out of personal opinion, I do not enjoy the theme, I apologize for my tastes

**Comment by ChesterTheCheesy** [comment]
don't like the idea of unfixable bar

**Comment by 00ze-cyclone** [comment]
The bar can be fixed, go kill xenos and take their resin spinner, it's not easy and rely on chance to an extent but it's doable. Beside, let's trust people to not be dicks and destroy the bar (or brig them for grand sabotage since the bartender workplace is almost irreversably ruined).

**Comment by Chubbygummibear** [comment]
please where is she, where is the xeno barmaid gf i need her

**Comment by JamieD1** [comment]
Wait are these real?

**Comment by Marmio64** [comment]
basalt looks ugly in the kitchen, and i dont really like adding more antag themed bars.

**Comment by JamieD1** [comment]
Make it not real tiles

**Comment by MenacingManatee** [comment]
I'll be swapping the weeds for a new fakeweeds tile when I get some free time, the current version was just to get something I can see to see if I like it. This will also make the bar fixable @ChesterTheCheesy since it'll drop a fakeweeds tile on crowbar instead of being destroyed by a random assistant with a lighter

**Review by ghost — APPROVED** [review]

**Comment by JamieD1** [comment]
Fix Cornflakes

**Comment by Anvilman6** [comment]
Not a fan of this, I'm afraid

**Comment by JamieD1** [comment]
Fix cornflakes

**Comment by JamieD1** [comment]
Reopen when fixed please.

**Pull request closed without merging**
