### PR TITLE
Moves Law 4 of Silicon Collective to the end so the "needs of the many" can't be voted to be "redtexting an antagonist"

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Alternative to https://github.com/yogstation13/Yogstation/pull/13548

Simply do not kill people

# Wiki Documentation

switches some laws around

# Changelog

:cl:  
tweak: moves law 4 to the end for silicon collective lawset
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
I prefer this option to the other.

**Comment by Hopekz** [comment]
Both of these PR's are hugbox.
Where in your thinking process did you conclude that the only thing that should be able to redtext an antag now is strictly security and if anyone else even attempts to do anything it is valid hunting.

This law was initially created with this 'loophole' in mind.

This new variation also comes pre-subverted now since you reorganized the laws so anyone can just say "hey AI I'm going to destroy you" 
"The silicon collective seeks to preserve themselves, both as a concept and as individuals." kicks in.

Since "The silicon collective prioritizes the needs of the many over the needs of the few." is on the bottom of the list now this means that anyone can instantly subvert the AI and all they have to do is threaten it.

**Comment by Hopekz** [comment]
> I prefer this option to the other.

These alternatives only exist to give the illusion of choice.
The best course of action is to close both.

**Comment by MenacingManatee** [comment]
This change has roughly the same effect as if you removed law 4 entirely. The purpose of law 4 (now 6) is to give the AI a priority system when laws 5 and 6 (now 4 and 5) conflict with each other or themselves. Without the change the priority is majority silicon > majority organics > minority silicon > minority organics. With the change the priority is majority silicons > minority silicons (as prioritizing majority organics would break law 5 (now 4)) majority organics, minority organics, making the loophole worse as any threat to any singular silicon can be met with lethal force, even against the entirety of crew. 
This also breaks the lawset as laws 5 and 6 (now 4 and 5) now have majority and minority in both on the same priority, because they're on the same line so prioritizing one over the other would break that law, breaking law 4 (now 6).

The only reason this is better than your alternative is because law 6 still has some function, in giving a system of priority when both are achievable, allowing the theme to still shine through a bit.

**Comment by MenacingManatee** [comment]
If this line of thinking with the lawset absolutely needs to be prevented, adding a law above 4 or below 6 about acting diplomatically to prevent killing/combat, possibly with the exception of immediate defense of self or others could be added. Something like "When possible, the silicon collective should treat other large entities such nanotrasen or the syndicate diplomatically to prevent political incidents", but 6 laws was already pushing it a bit especially considering the length of law 3, and 7 is too much imo.

**Comment by ToasterBiome** [comment]
> If this line of thinking with the lawset absolutely needs to be prevented, adding a law above 4 or below 6 about acting diplomatically to prevent killing/combat, possibly with the exception of immediate defense of self or others could be added, but 6 laws was already pushing it a bit especially considering the length of law 3, and 7 is too much imo.

I will look at implementing something similar while also keeping the identity of the list in tact in a little

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/13548

**Pull request closed without merging**
