### PR TITLE
Resolves a player complaint

### LINKED ISSUE #3312: Report on Rylan Sandys
Issue reported from  Round ID: 19432 (Yogstation 13)

Reporting client version: 512

Rylan Sandys kept attacking me, John Vaun Shaun, for no reason. He was not antag. He poisoned me and smashed bottles overhead. I had not threatened nor attacked him beforehand.

### PR DESCRIPTION
**Pull request by Kmc2000**
fixes https://github.com/yogstation13/Yogstation-TG/issues/3312

:cl:  
rscdel: Removes Rylan Sandys from the game
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
fuck

**Comment by Kmc2000** [comment]
LMAO

**Comment by HomocidlePancakes** [comment]
Can we remove... REEEEEEE i was typing when you closed it

**Comment by Ktlwjec** [comment]
please do not edit my serious comments

**Comment by Kmc2000** [comment]
Why was this closed?

**Comment by Partheo** [comment]
cooltext304243011773547

**Comment by DLCabbose** [comment]
Wut

**Pull request closed without merging**
