### PR TITLE
Boxstation its time to go. You won't be missed 🖖 

### PR DESCRIPTION
**Pull request by Therandomhoboo**
# Document the changes in your pull request

I carry this torch for @LoliconSlayer . For too long, Boxstation has been the main staple. People like it for its familiarity to other servers, the maints, the locations all of it. But nay, no more. We need to move on, we are separating ourselves from the dastardly servers that we take our code from. It will be sad, it will feel like you're losing a part of yourself. But this needs to be done so we can finally be MRP

# Why is this good for the game?

Encourages Players to try new things, get out of their comfort zone, be someone not some boring copycat ripoff of john wick going around the same map day in and day out. It has to be cut loose.

# Wiki Documentation

A memorial page should be dedicated to Boxstation to at least give it honour for the time it served us.

# Changelog

:cl:  

rscdel: Removed the blight and mangey appendage that is boxstation, long live the other stations

/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Incredibly based

**Comment by YashinHak** [comment]
LET'S FUCKING GOOOOOOOOOOOOO

**Comment by neeshacark** [comment]
finally, a good fucking pr

**Comment by Marmio64** [comment]
We should start a counter of how many times this exact same pr has been made

**Review by MajManatee — COMMENTED** [review]
Good ending

**Comment by azzzertyy** [comment]
when will people understand that box isnt the problem and removing box solves nothing

**Comment by ShoziOffical** [comment]
Just disable map vote

**Comment by Therandomhoboo** [comment]
Guys, i dont need to disable map-vote. Removing Box is mandatory and imperative to our progress. It has to be done and im so sad to see people unwilling to change or let go. Box is dying, we need to separate ourselves and flourish. Don't make us have to cut you guys off the rotten flesh too. Just join the MRP squad already and upvote.

**Comment by Spacemanspark** [comment]
In the event that this isn't a joke...

it may be more wise to have box be still in rotation--but, instead, have it crop up in votes and/ or autopicked by the server far less often. Box is dull to those of us who've played it for years and years and years, yes, but it is still one of, if not the best maps made for SS13, given how long its been maintained. Keeping it while enabling other maps to have a higher chance of being chosen would be best imo.

Edit: also yes, disable mapvote. Fuck mapvote.

**Comment by Therandomhoboo** [comment]
> In the event that this isn't a joke...
> 
> it may be more wise to have box be still in rotation--but, instead, have it crop up in votes and/ or autopicked by the server far less often. Box is dull to those of us who've played it for years and years and years, yes, but it is still one of, if not the best maps made for SS13, given how long its been maintained. Keeping it while enabling other maps to have a higher chance of being chosen would be best imo.
> 
> Edit: also yes, disable mapvote. Fuck mapvote.

I never make joke Pr's.
I understand the love for the familiarity and how it makes us feel comfortable but this is the time we get out of our comfort zones this server has been going around for 10+ yrs now. We are becoming adults and it is evident we need to cut ties with our childish past. The reason I am straight up removing it is because if it stays in the votes or makes a rotation then it will remind us of our past, our sins and transgressions and our... LRP days. This is needed to improve our roleplaying, improve our selection of maps (and encourage mappers to make more) and to improve our server by becoming separate from the others. 

It is time to finally put down boxstation, it will be missed but its time to move on. 😸

**Comment by Spacemanspark** [comment]
I have quite literally watched servers straight up die because they opted to full on remove box. Yogs as is has already shown signs of struggling to maintain players, and you may very well push it over the edge with this. I do not disagree that box can get very stale (I've said this myself many, many times) but the problem is mainly in how often it's forced onto us, not the map itself.

As for RP--unless the map itself is touting massive LRP features (which Box doesn't) I don't think you're going to encourage roleplay very much through a removal.

Again, you're better off reducing the chance it will come up in play. Remove it from mapvotes (or remove mapvotes :^)).

**Comment by neeshacark** [comment]
if removing box kills yog, it deserved to die

**Comment by Moltijoe** [comment]
image

**Comment by ShoziOffical** [comment]
> image

I would miss box atmos and incinerator

**Comment by ToasterBiome** [comment]
no lol

**Pull request closed without merging**
