### PR TITLE
Gib(t)onite sellable! wow!

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Gibtonite is no longer purely for griefing, and blowing yourself up. Miners can bring it up to be sold for 1000 credits per rock.

# Changelog

:cl:  
tweak: sellable gib(t)onite! wow! 😲 
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
It was also usable in creation of chembombs, but that required multi-department co-operation.

**Comment by ShoziOffical** [comment]
makes so that the more charged gibtonite, the more credits payout

**Comment by JamieD1** [comment]
> makes so that the more charged gibtonite, the more credits payout

This

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
That can be part of a different PR

**Comment by ShoziOffical** [comment]
guh

**Pull request merged**
