### PR TITLE
Ports some funni midround rulesets from TG

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

More midround rulesets form more antagonists!

It ports:
https://github.com/tgstation/tgstation/pull/60281/ (But no pirates)
AND
https://github.com/tgstation/tgstation/pull/59574/

# Wiki Documentation

Not required.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  [IndieanaJones](https://github.com/IndieanaJones) and [Watermelon914](https://github.com/Watermelon914), ported to Yogstation by SuperSlayer
rscadd: Ports some PR's from TG that add some midround rulesets for dynamic
/:cl:

### CODE REVIEW

**Comment by NCRLouTenant** [comment]
Ooh, blob without needing a ghost is a cool one.

**Comment by ghost** [comment]
Yes

**Comment by JamieD1** [comment]
@Xoxeyos

**Comment by Xoxeyos** [comment]
> @Xoxeyos

Sorry for responding so late, it looks good to me.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
