### PR TITLE
Makes AI Download 50% Faster

### PR DESCRIPTION
**Pull request by JamieD1**
Makes AI Download 50% Faster

At the moment it takes ages to download the AI if you are a traitor for example and have the steal AI objective. Which forces you to either have to make your own or find a different way of doing this. Failing this, maybe we could have an item which traitors can get which makes it silent or perhaps doubles the speed?

:cl:  
tweak: Makes AI Download 50% Faster
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Why?

**Comment by Hopekz** [comment]
> Why?

Ye kind of sucks he never puts his reasonings in a PR

**Comment by Bibby0110** [comment]
Missing rationale

**Comment by JamieD1** [comment]
Added Rationale

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Change it in the defines

**Comment by ThatLing** [comment]
I think it would be better to add an item for a few TC that downloads the AI instant (or a few seconds)

**Comment by Bibby0110** [comment]
> I think it would be better to add an item for a few TC that downloads the AI instant (or a few seconds)

Sounds like a horrible idea.
At best the item should reduce the time it takes by 50% or so, max

**Comment by ThatLing** [comment]
> > I think it would be better to add an item for a few TC that downloads the AI instant (or a few seconds)
> 
> Sounds like a horrible idea. At best the item should reduce the time it takes by 50% or so, max

Who's gonna spend TC to get a measly 50% download speed increase? If you're gonna spend TC, it should be worth it

**Comment by Bibby0110** [comment]
> > > I think it would be better to add an item for a few TC that downloads the AI instant (or a few seconds)
> > 
> > 
> > Sounds like a horrible idea. At best the item should reduce the time it takes by 50% or so, max
> 
> Who's gonna spend TC to get a measly 50% download speed increase? If you're gonna spend TC, it should be worth it

It should be worth it, but not that worth it

**Comment by Moltijoe** [comment]
Created my own that fixes the problem bibby has

**Pull request closed without merging**
