### PR TITLE
Resprites walls.

### PR DESCRIPTION
**Pull request by nesisknesis**
> [!IMPORTANT]
>  **PLEASE GIVE THIS PR YOUR FULL ATTENTION**
>  **FEEDBACK IS PARAMOUNT**

## Document the changes in your pull request

Updates the station's standard walls as per a commission.

## Why is this good for the game?
These walls are designed to be easier to work with and be able to be built upon later. For example, decals and different colouration.

# Spriting (THE IMPORTANT PART; PLEASE READ)
Before you reach a conclusion, I would like this PR to be treated as a review and not as a final implementation.

I do not expect to have gotten a significant change like this right first time. Therefore, I would like feedback on it, and the more specific the better.

I recognise it can be hard to put into words how you feel about a sprite so I will post a FAQ-type comment.

Without futher ado:
<details>

<summary>IMAGES</summary>

image

image

image

image

image

</details>

Either write your feedback in the github comments, the #spriting channel in discord, or DM me. My discord is Identification/nesisknesis.
If your feedback descends into toxicity I will write a player complaint.

Thank you.

## Changelog

:cl:  Identification
imageadd: Updates walls.
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
obligatory DO NOT MERGE

**Comment by nesisknesis** [comment]
Are they too clean?

Are they too bright/Should it be darker?

Do you like the two tone design?

Do you like the lower-trim design or prefer it to be more blocky?

Does it blend well with the surrounding turf? 

Is it easy on the eyes?

Is it too distracting?

Should the design of the reinforced wall be changed?

Does the reinforced wall repeat well in a pattern?

**Comment by ynot01** [comment]
Rwalls are a bit "jagged" as in they dont blend well together. When I look at the AI core I see a bunch of dots rather than one continuous wall. They stand out a LOT

**Comment by azzzertyy** [comment]
really really not a fan of these at all
1. too much contrast, why are they so white?
2. the reinforced walls don't look at all what i imagine these should look like
3. if we change walls i would much prefer we did the actual cool 3/4th walls

**Comment by yacabo** [comment]
I have an awful eye for art, but to me the reinforced walls look a bit weird, like the reinforced bit is disconnected from everything else.

**Comment by LassiH** [comment]
they look too bright, distracting and same point as ynot

**Comment by AMyriad** [comment]
Real excited about this, but help me understand this here.
image
We got like 3 layers here, and it's a tad difficult to tell if they're supposed to signify thickness or depth. On one hand it looks like the wall has many layers of metal, on the other hand it looks almost like a 3/4ths wall.

Now with R-walls, these stand out as they don't seem to seamlessly connect/smoothe with one another. I think the square shape on top of these could use some detail inside to signify bolts holding them together, as that's one of the strong points of our current R-walls.
image

Those are my first impressions, looking forward to seeing more yogsriginal art wherever we can get it.

**Comment by hwseo7** [comment]
I think they have too much highlights (3 layers with big color contrast) for ordinary wall we have to see entire round. Same goes to new rwall sprite, and it also doesn't seem to be connected with each other at all and feels like individual structures.

**Comment by Beeper-Skeeper** [comment]
I guess it kinda looks coo- IS THAT GRIMM HOLLOW KNIGHT

**Comment by Xantam-13** [comment]
> Real excited about this, but help me understand this here. image We got like 3 layers here, and it's a tad difficult to tell if they're supposed to signify thickness or depth. On one hand it looks like the wall has many layers of metal, on the other hand it looks almost like a 3/4ths wall.
> 
> Now with R-walls, these stand out as they don't seem to seamlessly connect/smoothe with one another. I think the square shape on top of these could use some detail inside to signify bolts holding them together, as that's one of the strong points of our current R-walls. image
> 
> Those are my first impressions, looking forward to seeing more yogsriginal art wherever we can get it.

The top image looks fine.

The bottom image of the R-Walls looks pretty awful. Not trying to insult anyones artistic skills as I couldn't do better, but, it looks so out of character and looks like a syndie bomb is placed on them re-sprited. 

Please can the R-Walls be fixed up before this is merged? Or if I am the only one with this view, put it to a community quickfire?

**Comment by dcxgame** [comment]
I'm trying to wrap my head around WHY the rwalls look so off in the AI sat and I have a theory.

First, the current sprite for the r-wall has the edge of the reinforcement at a slightly brighter value, while this one is quite a bit darker.
Second, the outer border of the complete wall has visible reinforcement in the current sprite, while this new one defines a completely solid outer layer. If a spaceman were to look at the wall from the outside, there'd be no way to discern if it were a regular wall or a reinforced one.
I think these two details create the perception that the reinforcement appears more like solitary patches on a normal wall, rather than a continuous barrier, which should feel thicker than said normal wall.

If you want the player to be immediately comfortable with the new designs, my suggestion would be: to experiment and see if you can bring the darker value in the reinforcement closer to the value of the rest of the inner portion of the wall, lengthen the branches of it a little further, and make some indication of reinforcement visible on the edges of the wall as well.

Another option would just be to let it ride for a week or two and see if people get used to the look. I QUITE enjoy the normal wall, and even reinforced walls when they're 1-wide, and even the AI sat has a very solid sense of shape with the new border design. The reactions you're getting might just be mild shock from the change in style, so I'd say you should let it simmer for a bit.

**Comment by cowbot92** [comment]
R-walls design logo is too... big. Make it smaller, or different

**Comment by RG4ORDR** [comment]
I do not like these walls, I do not like them at all.

**Comment by neeshacark** [comment]
honestly if we're redoing wall's 3/4ths walls might be nice.

and you should probably look into respriting windows as well since whatever change you make is almost certainly going to make them look odd

**Comment by Moltijoe** [comment]
I personally think theyre just a bit too bright, and the reinforced ones should smooth together

**Comment by Spl99** [comment]
I think it has potential but my main concern would be what other people have already said relating to R-Walls. In general, the walls seem to stand out more than I'm used to seeing but thats not strictly a bad thing. I can't tell if the floors would need similar treatment to 'blend' in with the walls or is it just the way I'm not used to seeing it like this.

Not opposed to these changes but curious if the R-walls could be altered in some way based on peoples above opinions.

**Comment by StupidTums** [comment]
The regular walls look pretty good. The r-walls are not very good, no offense. They don't really meld together very well. Glad effort is being made to get us new wall sprites, so I appreciate that greatly.

Edit: These new walls remind me of goon's walls a lot. Might be worth using their walls for inspiration on potential ideas.

**Comment by Moltijoe** [comment]
> I personally think theyre just a bit too bright, and the reinforced ones should smooth together

Reflecting on this, i dont think its necessarily too bright, but the contrast between the dark and the light is too large

**Comment by Cartlord** [comment]
They look too flashy, too shiny, too detailed. I'm of the stance that, the more frequently a player sees a sprite, the less attention-grabbing the sprite should be - you never want the walls to be the most detailed or interesting thing on-screen, and these seem overdesigned.

**Comment by ToasterBiome** [comment]
No work for a month+ I miss you :(

**Comment by AMyriad** [comment]
this is so sad

**Pull request closed without merging**
