### PR TITLE
Remove meteorgun from king of goats loot

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Lol

:cl:  
rscdel: king of goats no longer drops a meteor gun
/:cl:

### CODE REVIEW

**Review by jcatjmeow — APPROVED** [review]

**Comment by boodaliboo** [comment]
how about giving the king goat plushie as a replacement?

**Comment by SomeguyManperson** [comment]
it already drops the king goat plushie you dense

**Comment by Hopekz** [comment]
> you dense

rude.

**Comment by boodaliboo** [comment]
> it already drops the king goat plushie you dense

you dense

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
