### PR TITLE
Attempt to code a new race: Polysmorph

### PR DESCRIPTION
**Pull request by missatessatessy**
Attempts to try and code @War-Tex 's new race idea.
I've never tried adding a race before so it's very... bad, and mostly incomplete (i haven't actually added in the full sprites), and some things I put in just to try em out, haven't been reworded yet for the purpose of this race.
This is what it is, a draft to maybe get help on it. 

I'm personally not too fussed about the "success" of this code on being merged eventually, I'm mainly doing it because it seemed like a fun challenge

:cl:  
rscadd: Adds polysmorph race
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
excellent a new race to oppress on asimov

**Comment by missatessatessy** [comment]
I'm struggling to figure out how to get green blood damage_overlay/trails, instead of red..

**Comment by GrimGodhead** [comment]
big tiddy xeno hybrid goth gf

**Comment by MegaEmpirical** [comment]
So what's the idea?

**Comment by missatessatessy** [comment]
> So what's the idea?

https://forums.yogstation.net/index.php?threads/feedback-needed-on-new-race.21787/

**Comment by missatessatessy** [comment]
tail sprites just wont work

**Comment by Tipy1802** [comment]
Looks like a very interesting race

**Comment by alexkar598** [comment]
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

**Comment by Tipy1802** [comment]
F

**Comment by missatessatessy** [comment]
I've opened up a second non-draft PR for this, but there's a chance I might be working on it again to finish it off.
But I'm gonna close this since I know having it open isn't going to actually get me the help I need either way.

**Pull request closed without merging**
