### PR TITLE
Catsip, Higher and Clearer (3rd attempt)

### PR DESCRIPTION
**Pull request by Therandomhoboo**
# Document the changes in your pull request

Look, I know it seems like I'm being annoying but what if... We got the felinids really high and they could heal their ears so they can hear better? Yes?

Credit goes to @Hislyna by the way for the idea

# Wiki Documentation

Catsip, it may contain catnip which is why it makes Felinids really high but also heals their ears

# Changelog

:cl:  
rscadd: Catsip now heals the ears in exchange for being very high  
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
I don't like it.

**Comment by Therandomhoboo** [comment]
> I don't like it.

Any reason why?

**Comment by Hislyna** [comment]
image

Council has approved this dono feature

**Review by Moltijoe — APPROVED** [review]

**Comment by JamieD1** [comment]
Council get out of my Code, when we removing catsip

**Pull request merged**
