### PR TITLE
[GAX] Open Air Bar

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

Opens up the area for more RP

# Changelog

:cl:  
mapping: Opens up NVS Gax bar for more RP
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Would be cool to have a sort of almost food court.

**Review by ReddicusDragon — APPROVED** [review]
Screenshot 2023-04-03 180059

anyways, lighting might be a little wacky but I see no issues otherwise.

**Review by patpol4 — APPROVED** [review]
Missing suck pipe but lets keep that in mind for a later pr not to cause conflicts

**Comment by patpol4** [comment]
Oh nvm it already has conflicts

**Pull request merged**
