### PR TITLE
armory starts with a random contraband in the contraband locker

### PR DESCRIPTION
**Pull request by boodaliboo**
the title explains everything meta currently has contraband spawning but no other station does
:cl:  
rscadd: Added new things  
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
there's a reason only meta has it and the reason is its a bad feature

**Comment by boodaliboo** [comment]
> there's a reason only meta has it and the reason is its a bad feature

why is it one

**Comment by N3D6** [comment]
> > there's a reason only meta has it and the reason is its a bad feature
> 
> why is it one

not necessarily terrible but i can’t seem to stop seeing meta spawning with really op shit like desert eagles or unica revolvers, if it’s added to all maps it really needs a nerf of what it spawns

**Comment by ynot01** [comment]
i double tapped a wizard once with the deagle in the armory that was pretty funny

**Comment by boodaliboo** [comment]
> > > there's a reason only meta has it and the reason is its a bad feature
> > 
> > 
> > why is it one
> 
> not necessarily terrible but i can’t seem to stop seeing meta spawning with really op shit like desert eagles or unica revolvers, if it’s added to all maps it really needs a nerf of what it spawns

meta has a different spawn list then im using for this

**Comment by alao3alao3** [comment]
Closed due to overwhelming downvotes.

**Pull request closed without merging**
