### PR TITLE
Bigger, blacker medbay

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

Not even close to final. I like TG's idea of an open medbay with no surgery, so I'm wondering what it would be like if we adapted it for yogs.  The point of the big medbay is that on highpop (since we play box on highpop, seperate issue) it gets cluttered with all of medical + all of security + clown + mime + botanist + 2 shaft miners with the 3rd waiting to get revived, I'd at least like to see how it would go in real games.

Doors can be added if it turns out having the open floor plan is too easy for greytiders to abuse.

# Changelog

:cl:  
tweak: tweaks boxstation medbay to have more open space for higher populations
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
I don't hate this layout, though will state that the go-to on Box is to revive, and drag 3 tiles south to the cryo cells, to toss the now alive person in for quick damage repair and auto-CPR. Saves time and effort especially in high-pop when you don't have time to CPR someone because there will just be another corpse to deal with immediately. I would like to see the doors restored separating medbay treatment from the main hallway though, as sometimes it's nice to not let the unharmed, non-ill clown in so he can disrupt surgery until the CMO batons him and throws him out.

**Comment by MusselMain** [comment]
I don't like this idea simply because of how often i've been robbed by people when I get surgery (AND THIS IS WITH DOORS TO SURGERY, imagine them without that so any greytider can rob me), usually not the doctors, just some schmuck who bugs the door enough that they let him in and surprise, surprise, he steals my ID, bag, and other useful items, maybe if departmental sec officers actually stayed in their departments this wouldn't be a issue, but currently it is.

**Comment by MusselMain** [comment]
I forgot to mention this, but also: why add a break room containing snacks, when there's the bar, kitchen, and botany within sneezing distance north, and a few snack vendors just outside the paramedics? It seems a bit repetitive, I could understand it for a place like cargo or engineering, but it's literally the closest to multiple food options.

**Comment by ToasterBiome** [comment]
> I don't like this idea simply because of how often i've been robbed by people when I get surgery (AND THIS IS WITH DOORS TO SURGERY, imagine them without that so any greytider can rob me), usually not the doctors, just some schmuck who bugs the door enough that they let him in and surprise, surprise, he steals my ID, bag, and other useful items, maybe if departmental sec officers actually stayed in their departments this wouldn't be a issue, but currently it is.

admin/IC issue, doctors shouldn't let everybody and their mom into medbay

**Comment by ToasterBiome** [comment]
> I don't hate this layout, though will state that the go-to on Box is to revive, and drag 3 tiles south to the cryo cells, to toss the now alive person in for quick damage repair and auto-CPR. Saves time and effort especially in high-pop when you don't have time to CPR someone because there will just be another corpse to deal with immediately. I would like to see the doors restored separating medbay treatment from the main hallway though, as sometimes it's nice to not let the unharmed, non-ill clown in so he can disrupt surgery until the CMO batons him and throws him out.

If it turns out to be a problem without doors, they can very easily be readded :)

**Comment by maxion12345** [comment]
> > I don't like this idea simply because of how often i've been robbed by people when I get surgery (AND THIS IS WITH DOORS TO SURGERY, imagine them without that so any greytider can rob me), usually not the doctors, just some schmuck who bugs the door enough that they let him in and surprise, surprise, he steals my ID, bag, and other useful items, maybe if departmental sec officers actually stayed in their departments this wouldn't be a issue, but currently it is.
> 
> admin/IC issue, doctors shouldn't let everybody and their mom into medbay

doctors usually don't they just barge in after spamming the door so they can rush to medbay storage to steal an entire brute medkit to heal their 12 brute damage from accidentally hitting themselves before smashing the window to get out of the storage area

basically, it'd be a good idea to tider-proof medbay a little bit because if you don't it'll be hell for both admins/security to deal with instances of 'get this person out of medba- oh my god another 5 just walked in to steal shit'
i'd be down with a 2x4 airlock system like other maps have
(also kiosk inside of medbay huh)

Also having cyro close to the surgical area/defib area/stasis bed is verrrrryyy nice. Having cyro like, stuck in the corner of medbay when its such a big facet of medbay is sad.

**Comment by KillerOrcaCora** [comment]
Select the entire setup and flip it and everything will be fine.

**Comment by JamieD1** [comment]
> > I don't like this idea simply because of how often i've been robbed by people when I get surgery (AND THIS IS WITH DOORS TO SURGERY, imagine them without that so any greytider can rob me), usually not the doctors, just some schmuck who bugs the door enough that they let him in and surprise, surprise, he steals my ID, bag, and other useful items, maybe if departmental sec officers actually stayed in their departments this wouldn't be a issue, but currently it is.
> 
> admin/IC issue, doctors shouldn't let everybody and their mom into medbay

I do agree, this is an issue, the whole point of surgery is its private for potential antag situations and the fact stuff can get stolen pretty easily, I don't like surgery being so open like that. And saying its an admin issue means you really don't know how rounds go.

**Comment by ToasterBiome** [comment]
I've been thinking about this for a while and I'll address these issues:
> I do agree, this is an issue, the whole point of surgery is its private for potential antag situations

No, the point of surgery is to get surgery. Things do not exist only for antagonists. Borgs do not exist to give more antag situations. Chemicals don't exist to give more antag situations.
Surgery being semi-private does not work in yogs. Yesterday I watched a CMO look at the surgery console to discover that the medical doctor brainwashed a person because 

*drumroll* 

**Nobody uses the surgery room.**

So much so that somebody using the surgery room is a cause of investigation. I'll echo my sentiments that we've discussed privately: Nobody wants to be put under, and if you close the shutters, people you do surgery on will straight up get up and **leave** because they know you're gonna do shit to them. Otherwise you wouldn't do it.
"Hey can you do surgery on me"
"Sure, come into the surgery room"
*just walks out*

Honestly the problem is that brainwashing is comically easy to meta. Hmm this guy doesn't need surgery but he got it and nothing's obviously different, time to check the console! Maybe this will help Medical Doctors not be extremely obvious in their brainwashing (that gets them instantly arrested). I proposed making brainwashing basically be a silent action by disguising it as some surgery like Organ Manipulation (outwardly people seeing you do it) but you did laugh in my face on that one.

Still want to brainwash?
- Do it in your secret hidey-hole in maint. You're already suspicious by closing shutters, might as go all the way
- Sync it to an advanced med scanner or surgery processor. This way, you can do your awesome brainwashing in full view of everyone!

> and the fact stuff can get stolen pretty easily, I don't like surgery being so open like that. 

Observing any round on semi-high population will show that you have 1-2 active medical doctors. Conveniently, there's a suspicious correlation with the amount of stasis beds and active doctors, while the rest just sorta hover around the stasis bed. Because nobody gets surgery in the surgery room, and anyone else that isn't in dire need is either 1) thrown in the sleeper or 2) thrown into cryo.

And guess what? Stasis beds aren't behind a locked door. They're right there in the open, with all your shit on the floor. Do you know what happens to your shit on the floor? Nothing, really. Occasionally you get a greyshit stealing, but a lot of the time the 300 medical doctors surrounding your body will rapidly kick the ass of whoever tries to swipe your stuff (they live for it). Again, this is not really an issue with surgery tables, because you're still sitting your cheeks ass naked on that stasis bed in full view of the 4 doctors/CMO/geneticist/bored paramedic/3 miners/the janitor/mime/clown/two security officers. 

I have seen through IC and OOC observation that with these surgery tables in the main room, they are used for more than any other time. You're not automatically suspicious for using them, you're not wasting a bunch of time getting people ready, dragging them around.

Here, I've even made a meme
image

**Comment by VaelophisNyx** [comment]
smol issue idk if it got reported already; the doors into medbay treatment aren't set up like the old medbay where one was an exit door with directional access (public exit, private entry)

**Comment by ToasterBiome** [comment]
> smol issue idk if it got reported already; the doors into medbay treatment aren't set up like the old medbay where one was an exit door with directional access (public exit, private entry)

Whoops fixed just forgor the testmerge

**Comment by Sgtdevel** [comment]
The security checkpoint isn't connected to the powernet at all which is a major issue

**Comment by Mqiib** [comment]
sec office security door needs firelocks

**Comment by ToasterBiome** [comment]
> sec office security door needs firelocks

fixed

**Comment by ToasterBiome** [comment]
> The security checkpoint isn't connected to the powernet at all which is a major issue

oh this is also fixed

**Comment by boba247** [comment]
I don't believe this improves medbay. Removing surgery is fine you're right it isn't used very often, but this design breaks up the flow of medbay too much. It feels like this floor plan tries to move each medbay equipment as far away from each other as possible. The sleeper is further away from the stasis bed which is far away from cryo. 

- The grass pillar in the middle needs to be removed. It forces everyone to go around it and causes groups of people to be more of a nuisance crowding around the medical equipment. Saw a patient die because of this issue.

- The surgical tool set is rather unsecured spawning in the main treatment area instead of its own room. Can it get a secured locker or spawn in medbay storage?

- The main treatment area footprint remains the same, but loses space because of that pillar and walls are turned into large doors that can't have equipment against them.

- Medbay storage is larger than it needs to be, not causing immediate problems but just an inefficient use of space.

- The breakroom being off to the side means less use overall. Could be intended, previous location meant more traffic going through it.

**Comment by ToasterBiome** [comment]
> It feels like this floor plan tries to move each medbay equipment as far away from each other as possible. The sleeper is further away from the stasis bed which is far away from cryo.

Yes. Per my explanation post above, on higher populations in the old method, everything was so comically close together that with your 4 doctors you were all standing around watching the one person work on the stasis bed. Splitting them further (and thus giving them more space more more machines between them) gives each individual doctor more area to work. This can seem like a drawback when you have only one doctor, but the benefit of multiple doctors being able to.... actually work on higher population far outweighs the 2 extra tiles that they are separated.

> The grass pillar in the middle needs to be removed. It forces everyone to go around it and causes groups of people to be more of a nuisance crowding around the medical equipment. Saw a patient die because of this issue.

This is agreeable.

> * The surgical tool set is rather unsecured spawning in the main treatment area instead of its own room. Can it get a secured locker or spawn in medbay storage?

This is agreeable.

> * The main treatment area footprint remains the same, but loses space because of that pillar and walls are turned into large doors that can't have equipment against them.

There is a spot for defibs on every wall, you don't attach anything else.

> * Medbay storage is larger than it needs to be, not causing immediate problems but just an inefficient use of space.

Medbay storage also contains the charger and the medical doctor's lockers which should be in storage anyway.

> * The breakroom being off to the side means less use overall. Could be intended, previous location meant more traffic going through it.

Not intentional but I like how it's playing out. Instead of having to tear through medbay breakroom, you show up in medbay itself. I see this as no different from Meta's, where the maint door leads straight into treatment.

I have made some changes through your feedback.

**Comment by boba247** [comment]
> * The main treatment area footprint remains the same, but loses space because of that pillar and walls are turned into large doors that can't have equipment against them.
> 
> There is a spot for defibs on every wall, you don't attach anything else.

What I meant by this is machines like sleepers and stasis beds need a wall or window to be next to, they can't be placed blocking a door. By adding more doors the treatment area lost space for equipment. 

My only other comment is if there's a way to better use the cryo room space. Right now it feels like a big storage closet that cryo got shoved into.

Thanks for taking this feedback into consideration.

**Comment by ToasterBiome** [comment]
> > * The main treatment area footprint remains the same, but loses space because of that pillar and walls are turned into large doors that can't have equipment against them.
> > 
> > There is a spot for defibs on every wall, you don't attach anything else.
> 
> What I meant by this is machines like sleepers and stasis beds need a wall or window to be next to, they can't be placed blocking a door. By adding more doors the treatment area lost space for equipment.
> 
> My only other comment is if there's a way to better use the cryo room space. Right now it feels like a big storage closet that cryo got shoved into.
> 
> Thanks for taking this feedback into consideration.

Will look to further improve, thank you for having actual talking points instead of "EWWW BAD!!!"

**Comment by MegaEmpirical** [comment]
Not a fan of the surgery change. I prefer the aesthetics of a private surgery but also it makes shenanigans with surgery vastly more difficult (bomb implants, brain washing, etc.). There's no privacy, for which there are many reasons to have.

**Comment by Smudged** [comment]
> admin/IC issue, doctors shouldn't let everybody and their mom into medbay

I completely disagree, It might be an admin/IC issue, this shouldn't mean doctors need to suffer for it.
I'm already dubious of a medbay without a surgery room, letting it be open, where literally anybody can just barge in is just bad. Already people barge into the previous medbay center even when the doors are there. 

Also, if you're gonna have the blood bags/prosthetics near some glass, add in a windoor and put the setup against a wall. 
This change does make it easier to find the blood bags, but again, I'm never crazy about them just being out in the open for risk of them being stolen, or misplaced.

**Comment by Tipy1802** [comment]
I much prefer having a seperate surgery room, much better for privacy and comfort

**Comment by ToasterBiome** [comment]
Fixed cornflakes

**Comment by ToasterBiome** [comment]
toxic work environment

**Pull request closed without merging**
