### PR TITLE
Revert "Replaces gibbing on being heretic sacrificed with being sent to brazil"

### PR DESCRIPTION
**Pull request by Cartlord**
### Document the changes in your pull request
Reverts yogstation13/Yogstation#12548

MF selfmerged an antag rework without even a testmerge first and seemingly refuses to accept even the possibility that his PR isn't great
I know this probably doesn't follow template, but clicking the Revert button doesn't _have_ a template so I'm improvising

### Wiki Documentation
Not sure, I doubt Theos's change has been added to wiki yet anyways

### Changelog
:cl:
rscdel: Being Heretic sacrificed gibs you again
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Is this a hate PR?

Your reasoning for why it is bad for the game is "Theos bad self merged MF evil dude"

Not every PR needs a test merge that's just something Jamie started when he became HC

**Comment by SomeguyManperson** [comment]
All changes were tested locally and as such a testmerge wasn't required

**Comment by Cartlord** [comment]
also 
image

**Comment by Cartlord** [comment]
> 
> 
> All changes were tested locally and as such a testmerge wasn't required

I'm not just concerned about it WORKING, I'm concerned about whether it's a GOOD IDEA. The succumb changes were testmerged, and whaddya-know, it turned out people _fucking hated those_, so they weren't fullmerged.
I see the point of testmerging reworks as not just being to make sure they work, but to make sure people WANT them before you just throw shit in.

**Comment by Hopekz** [comment]
> also 
> image
> 

Okay so how does your revert get us closer to what that tl;Dr says they want to see?
The point of a PR description is to get to the reasoning for your exact change. 

Your change reasoning should be about why getting gibbed is better for the game

**Comment by SomeguyManperson** [comment]
I'm not a spriter

**Comment by Cartlord** [comment]
I unironicly think it's better for people to be gibbed, or at LEAST dead, because _you're performing a fucking blood ritual with them, of course they'd be fucking slaughtered_

**Comment by Cartlord** [comment]
also relevant 
image

**Comment by Xoxeyos** [comment]
> 
> 
> I'm not a spriter

Orca and I have both volunteered, it's not like there isn't any spriters in our discord that you could ask for help.

**Comment by Cartlord** [comment]
Frankly Theos, here and in the Discord you seem to have been nothing but a dick about this. Your first response when I asked how your version was better was "guess you dont[sic] play", and you still refused to elaborate when I pressed you.
image
Also this, where you called the entire playerbase idiots and implied nothing you'd heard was usable criticism

**Comment by patpol4** [comment]
Hilarious changelog, also github is not a maintainer complaint forum.

**Comment by SomeguyManperson** [comment]
> I unironicly think it's better for people to be gibbed, or at LEAST dead, because _you're performing a fucking blood ritual with them, of course they'd be fucking slaughtered_

so that's what this is about
I don't know why you particularly like people being permanently removed from the round, but I can assure you the majority of the playerbase does not agree

> > I'm not a spriter
> 
> Orca and I have both volunteered, it's not like there isn't any spriters in our discord that you could ask for help.

I also would rather focus my efforts on the actual GAMEMODE rather than putting in several more hours to add some basic visual effects for people who aren't going to see them for more than 4 minutes at a time which people would inevitably bitch at me about when they don't match some arbitrary standards. There's a reason the vast majority of information in game is conveyed through flavortext and it's because it's far easier to type something out than add a bunch of effects or cinematics people won't care about
I would REALLY like allowing people to remember exactly what happened but this is yogstation and if people can remember information "for story" they'll blatantly abuse this to call out both what and who the antag is as well as the location, so unless heretics are particularly strong in the future the "i forgot" text has to stay in place of outright killing people

**Pull request closed without merging**
