### PR TITLE
Ports TG's Limbgrower refactor, design expansion, and TGUI update. With added Yog feature

### PR DESCRIPTION
**Pull request by Chubbygummibear**
# Document the changes in your pull request

Ports [TGUI Limbgrower + Limbgrower refactoring and design expansion #57955](https://github.com/tgstation/tgstation/pull/57955)

Interface update:
image
image

- Refactors the limbgrower to modernize the code. Now, the limbgrower can accept any type of reagent in limbgrower designs.
- Adds felinid ears and tails, lizard digitigrade legs, lizard tongues, fake lizard tails (unusable in lizard-wine and similar recipes), plasmaman organs, and ethereal organs (minus the heart) to the limbgrower via limbgrower design disks. These disks can be printed from the medical lathe once the required technology has been researched.
- Adds a technology node to unlock the limbgrower design disks after advanced biotech, xenoorgan biology.

# Yog Specific change: 
You can insert meat slabs into the limb grower to generate synthflesh, so it's baseline functionality is achievable if you use it exactly like a cloner for body parts and organs.

Polysmorph stuff

image

# Wiki Documentation

Limbgrower can grow limbs of all races, has it's own tech node in the tech tree that requires advanced biotech first, and then lets you print design disks from the medbay lathe that update the limb grower's options. Now accepts meat as fuel and converts it to synthflesh

# Changelog

:cl:  Melbert, Chubbygummibear
add: Limbgrower design disks. Science now has a new tech node after advanced biotechnology, "XenoOrgan Biology" which allows medbay to print new designs for the limbgrower, including various felinid, lizard, plasmaman, polysmorphs and ethereal organs.
add:(Yog specific change) Meat can be fed into the limb grower to generate synthflesh for fuel
add: TGUI Limbgrower
tweak: Refactored the limbgrower to modernize the code and allow for more types of designs.
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
capitalize them categories bro

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
This not a bit op now it accepts meat?

**Comment by Chubbygummibear** [comment]
> This not a bit op now it accepts meat?

it's definitely strong to be able to accept meat and print parts, but i made sure to try and keep the meat to synthflesh low, especially in the case of synthmeat, the most abundant resource roundstart. I had talked to mqiib about this because i was nervous that no one would go out of their way to build it if it required synthflesh because, well. cloner go brr and that's easy for yog players who don't know the ins and outs. mqiib told me that synthflesh was easy enough to make that this wouldn't be a cheesy way to convert meat to synthflesh, so i stuck with the idea. Additionally, i felt the meat made sense since our cloner just uses meat, so if 3 steaks makes a person, surely like 1-2 steaks is enough to make an arm. also it's not a roundstart spawn which i was kinda considering asking you or someone else if it would have a place spawning roundstart if it actually works

**Review by ToasterBiome — APPROVED** [review]

**Comment by ToasterBiome** [comment]
This tgui is kinda cheeks but for a port it's fine

**Pull request merged**
