### PR TITLE
makin mah waffle house

### PR DESCRIPTION
**Pull request by Yarinoi**
no clue if im accidentally fucking anythign up

# Document the changes in your pull request

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Added new things  
rscdel: Removed old things  
bugfix: fixed a few things  
wip: This is work in progress  
tweak: tweaked a few things  
soundadd: added a new sound thingy  
sounddel: removed an old sound thingy  
imageadd: added some icons and images  
imagedel: deleted some icons and images
mapping: This is a mapping change
spellcheck: fixed a few typos  
experimental: This is experimental
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
oh wait oh no no no

**Comment by Yarinoi** [comment]
accident, sorry, first time making a pr lol

**Comment by neeshacark** [comment]
banned

**Comment by DylonBR** [comment]
ban this man immediately

**Pull request closed without merging**
