### PR TITLE
Reverts Sleepers to tgui and fixes them

### PR DESCRIPTION
**Pull request by Lostlarry**
removes some shit code for the sleeper
fixes the tgui part of it

:cl:  
tweak: Reverts sleepers to now working tgui
/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
Can you provide screen shots.

**Comment by Lostlarry** [comment]
image
haven't touched the visuals anyway

**Comment by Nickvr628** [comment]
finally!

**Review by Amelia0010 — APPROVED** [review]

**Comment by Amelia0010** [comment]
also you don't have to do //yogs start and //yogs end anymore

**Pull request merged**
