### PR TITLE
ghost of poly is now boss sentience

### PR DESCRIPTION
**Pull request by ynot01**
are you nuts

#### Changelog

:cl:  
tweak: Ghost of Poly now has SENTIENCE_BOSS
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
What does this imply

**Comment by ynot01** [comment]
> What does this imply

you cannot use a sentience potion on Ghost of Poly

**Comment by Jarod1200** [comment]
Sad. Truly the end of an era

**Comment by JamieD1** [comment]
Fun police
image

**Comment by alexkar598** [comment]
-The guy who wanted to remove 4way heatexchange

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
