### PR TITLE
Continues the war on booba, nurse dress edition

### PR DESCRIPTION
**Pull request by Mqiib**
Removed extra pixels that stick out on the nurse dress to bring it in-line with standard jumpsuit sprites. Again, this is to prevent the uniform sprite from sticking out under armor sprites and stuff.

# Changelog

:cl:  

imagedel: Nurse dresses (the white ones not the purple/green/blue/red ones) no longer have extra padding on the chest area.

/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Actually it’s pretty uniform for most dresses to have boobs, by doing this you are making the sprites less uniform and more messy.

Also can we get pictures of how the dress looks before and after to judge if it actually looks better

**Comment by UselessTheremin** [comment]
Man it’s fucking hilarious how much you guys care about the amount of spaceman titty pixels 
17ACD20B-9367-4239-A2CF-271D915924D7

**Comment by Tipy1802** [comment]
> Man it’s fucking hilarious how much you guys care about the amount of spaceman titty pixels

Why do you think I told him, funniest shit seeing someone wasting their time removing implications that females have boobs in a vide game for no reason and then having it start a contraversy

**Comment by Hadoje** [comment]
Mqiib's kill count rises to 5 pixels

**Comment by Mqiib** [comment]
The de-boobing is a joke, I'm more concerned about how much the sprites stick out compared to the other uniform sprites. I am in fact NOT making the sprites more messy by ensuring the clothing sprites are more uniform. What I'm doing is literally the opposite. If you would like me to stop being silly with my prs I can do that, but that's no fun.

Old:
image

New:
image




> Mqiib's kill count rises to 5 pixels

Seven, actually.

**Comment by Tipy1802** [comment]
It really doesn’t stick out. No one noticed the boobs on the security skirt until made the PR. Not a single soul. And also yes the nurse dress sticks out but that’s because it’s a fucking dress while everything else is a uniform jumpsuit. It sticks out by design and the only way for it to not would be if it gets removed

**Comment by Tipy1802** [comment]
It really doesn’t stick out. No one noticed the boobs on the security skirt until made the PR. Not a single soul. And also yes the nurse dress sticks out but that’s because it’s a fucking dress while everything else is a uniform jumpsuit. It sticks out by design and the only way for it to not would be if it gets removed

**Comment by Mqiib** [comment]
> It really doesn’t stick out. No one noticed the boobs on the security skirt until made the PR. Not a single soul. And also yes the nurse dress sticks out but that’s because it’s a fucking dress while everything else is a uniform jumpsuit. It sticks out by design and the only way for it to not would be if it gets removed

It does stick out from under suits. Ident illustrated this quite nicely in the dev-public channel. I noticed the sec jumpskirt issue long ago but thought it was just me. Theos then pointed it out and I realized I was right to believe there was something wrong with it. The only reason this one flew under the radar is because it so very rarely gets used and is often used in conjunction with a _white_ labcoat if any outer suit at all. Lobby all you want, get people to downvote this pr, but this is still primarily an actual fix rather than an aesthetic change.

**Comment by Tipy1802** [comment]
I guess I am missing it as I see no pictures of the dress with another coat on it.
Only compared to a naked body

**Comment by overlord12345** [comment]
> I guess I am missing it as I see no pictures of the dress with another coat on it.
> Only compared to a naked body

hnng
here

**Comment by Tipy1802** [comment]
Even with your changes the dress will still clip over, as you showed it’s not just the boobs poking out but the front and the back as well. 
Honestly this can be said probably for any clothing in the game, if you miss match it with enough other clothes you may end up with some bad combos. Like who even wears the nurse dress with what I assume is the HoS’s optional tenchcoat? 
And once again even with this PR the clipping will still exist as it’s the nature of the clothing

**Comment by patpol4** [comment]
sad awooga

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
RIP Boobs

**Pull request merged**
