### PR TITLE
Adds Some Old Some New and Some Classic Songs to the Lobby Screen!

### PR DESCRIPTION
**Pull request by fluffe9911**
We really do need more music and I really liked some of the old music we had here is a list of the new songs

https://www.youtube.com/watch?v=s7dTBoW5H9k - Mr Blue Sky (Old Yogs)
https://www.youtube.com/watch?v=CfMMlT8Lyns - Get Lucky 8 Bit (Old Yogs)
https://www.youtube.com/watch?v=dLrdSC9MVb4 - Turn the Lights Off
https://www.youtube.com/watch?v=YAXc87bmgLA - Nightcall
https://www.youtube.com/watch?v=UPHmazxB38g - Thunderdome (Old Yogs)
https://www.youtube.com/watch?v=pLJ85XExZtQ - & (amazing song title)
https://www.youtube.com/watch?v=At8ao5iABFg - Ruler of Everything
https://www.youtube.com/watch?v=VGQZItOMz6k - Good Day
https://www.youtube.com/watch?v=YgGzAKP_HuM - RASPUTIN
https://soundcloud.com/jeffimam/title-plasma-attack - Plasma Attack (Made by Moja10 Old Yogs)
https://www.youtube.com/watch?v=L0VjlFqp47g - Next Town Over
https://www.youtube.com/watch?v=KKny_ia8Fvo - Dont Stop Me Now
https://www.youtube.com/watch?v=iYYRH4apXDo - Space Oddity  (Old Yogs im pretty sure I cant find it for the life of me but I swear to god it was)

### CODE REVIEW

**Comment by Smudged** [comment]
https://youtu.be/KaOC9danxNo
We used this song for space oddity, also, I'm also inclined to go towards a more. . . community orientated base on the lobby songs, not to say yours are bad, but I don't like some of 'em
https://forums.yogstation.net/index.php?threads/current-lobby-songs.15845/ and these were the old lobby songs too.

If there was an easier way to pick and choose specific songs besides using a single github post, I think that'd be best, um, maybe by putting this github entry into the forums so we can get more eyes and ears on it.

I'll give my opinion of each song you've chosen though, once I find time.
*Edit: I didn't realise how much work I've got ahead of me, but I'll uh, give my opinion on a few and. . . probably not all of them, I really do like & and Next town over though*

**Comment by fluffe9911** [comment]
Alrighty thank you

**Comment by Smudged** [comment]
okay let's see
So
Mr.Blue Sky - A yogs classic: must keep.
Mr. Syndicate - I don't like the singing, guitar riffs are pretty good, but Overall I don't like this one. 
8 Bit Get lucky - Classic: must keep.
Turn the lights off- This is a pretty fun song: I'd keep this one.
& - I like this song, is a gooood one. 
Ruler of Everything - This one's nice, I'd like this one kept
Good Day - The more I listen to Tally Hall, the more I like 'em, Keep this one too
Rasputin Remix - I'm liking where this is going too, keep this one too. 
Plasma Attack By Moja - Yogs Classic, keep it
Next Town over - I like the wavy feeling of this song, Keep it
Don't stop me now - Queen's a classic, and this one fits
Chris Hadfields Space Oddity - https://youtu.be/KaOC9danxNo - Maybe one of the best yogs classic's there is.

Just to condense the list 
Keep: 
Mr.Blue Sky
8 bit Get lucky
Turn the  lights off
&
Ruler of Everything
Good Day
Rasputin Remix 
Plasma Attack By Moja
Next Town Over
Don't stop me now
Chris Hadfield's Space Oddity 

Discard: 
Mr. Syndicate

So everything but Mr.Syndicate

We can make a community vote later, to see what the community thinks as well. And to add or remove songs as we see fit. 

Thanks for the good work Fluffeee, sorry for the late response.

**Comment by fluffe9911** [comment]
Yeah was debating if I should get rid of that song or not as well plus it has a bad word so prob not really the best for the server lol

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I think [FTL - Lanius Battle](https://www.youtube.com/watch?v=mG6Ys2opFD0) fit really well too, you can find the ogg in the old files
edit: Don't forget [Kavinsky - Nightcall](https://www.youtube.com/watch?v=YAXc87bmgLA) and [thunderdome.ogg](https://www.youtube.com/watch?v=UPHmazxB38g=)

**Comment by fluffe9911** [comment]
Not the biggest fan of the FTL song its not bad I just dont like how serious sounding it is if that makes sense Nightcall and thunderdome are def being added though

**Comment by fluffe9911** [comment]
Closing cause Mcdonald is doing a cool thing

**Pull request closed without merging**
