### PR TITLE
Add LEMMiNO - Firecracker to lobby playlist

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Just lemmino

image

# Changelog

:cl:  
soundadd: Added LEMMiNO - Firecracker to lobby playlist
/:cl:

### CODE REVIEW

**Review by Moltijoe — CHANGES_REQUESTED** [review]
the comment is wrong i think?

**Comment by ynot01** [comment]
> the comment is wrong i think?

https://www.lemmi.no/music
image

**Comment by ynot01** [comment]
oh wrong song

**Review by ToasterBiome — APPROVED** [review]
lol noob

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
