### PR TITLE
Emagged peaceborg hug follows insulation

### PR DESCRIPTION
**Pull request by Moltijoe**
one click insta-stun with no counterplay is no fun
now it checks for insulation

:cl:  
tweak: Emagged peaceborg hug follows insulation
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
counterplay is a flash in this case

**Comment by Moltijoe** [comment]
> counterplay is a flash in this case

flashes aren't fun either

**Comment by TheRyeGuyWhoWillNowDie** [comment]
#15408

**Comment by Moltijoe** [comment]
> #15408

not the same, that PR lets it be negated simply by using insulated gloves
this one requires using a hardsuit or other suit slot item with a siemens coefficient of 0 or less, similar to a tesla zap
also this doesn't make the shock hug consume power

currently the only things that will prevent it are literally just hardsuits and reactive armour

insulated gloves will reduce the damage by 50%, but it's not enough to negate the shock

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
