### PR TITLE
Borg Brain-jar skin unlock

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
image
Unlocked brain borg skin as per request

# Changelog

:cl:  
tweak: Brain borg skin now available to all.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Screenshot of skin?

**Comment by Hopekz** [comment]
I think I remember this one not looking like the Borg module so it would maybe be removed instead

**Review by Moltijoe — APPROVED** [review]
code is simple, whether this skin should even be made widely available is something the art team will need to decide on

**Comment by Moltijoe** [comment]
image
not module specific

**Comment by aaqe** [comment]
image
This is the skin.

**Comment by aaqe** [comment]
It doesn't have to be a medical borg if the art team wants to find a place for it elsewhere, identification did an amazing job creating this masterpiece.

**Comment by Cartlord** [comment]
I'm in favor of the skin's removal, since it's an all-module skin and I think those suck in general

**Comment by aaqe** [comment]
> I'm in favor of the skin's removal, since it's an all-module skin and I think those suck in general

I agree that it shouldn't be an all-module skin but there may be a place for it as a medical borg or standard borg.

**Comment by MajManatee** [comment]
Its still someones skin, its not getting removed. If you dont want it public, its going to remain as is.

**Comment by cuackles** [comment]
Don't remove the skin, but please make it module specific, i would say either standard module or medical

**Review by cuackles — CHANGES_REQUESTED** [review]
pls lock it to a single module as i said in my last comment

**Comment by MajManatee** [comment]
Should go through and unlocked the skins for anyone thats banned

**Review by cuackles — APPROVED** [review]
Comunism

**Pull request merged**
