### PR TITLE
Adds to the list of antags that mindshield nanites don't work on

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Its currently possible for a large number of antags to get mindshield from nanites. This shouldn't be possible.

Yes, I did get my ass beat by a thrall with a mindshield.

# Changelog

:cl:  
bugfix: fixed some antags getting mind-shielded from nanites
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
you died LOL!

**Comment by Tipy1802** [comment]
Why are you taking someone else's nanites as an antag in the first place?
Kinda the point of nanites can make you strong but they can also be used to fuck you up. It's a gamble.
Plus what's even the point of the mindshield programme if it can't work on conversion antagonists?

**Comment by TheLinuxOS** [comment]
> Why are you taking someone else's nanites as an antag in the first place? Kinda the point of nanites can make you strong but they can also be used to fuck you up. It's a gamble. Plus what's even the point of the mindshield programme if it can't work on conversion antagonists?

I might be mistaken but I believe nanites automatically update in your body when someone uploads new programs to the cloud, so lets say its a conversion game mode like revs and someone with nanites gets converted halfway through the round and they already had nanites in em, they then have no way to remove those nanites from themselves and any chucklehead can go along and upload a mindshield program into the cloud instantly deconverting them.

**Comment by adamsong** [comment]
You can also get infective exolocomotion on your nanites, which turns them into airborne mindshields

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
