### PR TITLE
bring back old boh bombs

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

seeing 2 bags of holdings is very rare nowadays. we should make the boh bomb better now since they're rare and not every shitter can create a singularity out of his ass for no reason. 2 bohs should be feared, not "oh I'll just go up a ladder haha". plus, we can kill ascended slings again
# Spriting

# Wiki Documentation

boh bombs are singulos again
# Changelog

:cl:  
tweak: bring back old boh bombs
/:cl:

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
I'm going to be real I don't remember why we removed this

**Comment by RG4ORDR** [comment]
> I'm going to be real I don't remember why we removed this

BOH Sings could basically force admins to restart the server if a griefer got a hold of them. The tear was less destructive.

**Comment by Simplehorror** [comment]
> I'm going to be real I don't remember why we removed this

people were whining because john shithead could get 2 bags because science was always busted open

**Comment by Burger1998** [comment]
just make the singularity created unable to move. the person your bombing is likely pulled in and the whole station doesn't get destroyed because the psychiatrist saw an open windoor.

**Comment by Simplehorror** [comment]
you need anomaly cores to make bohs now

**Comment by UltraBigRat** [comment]
> just make the singularity created unable to move. the person your bombing is likely pulled in and the whole station doesn't get destroyed because the psychiatrist saw an open windoor.

This wouldnt occur though? the reason for it being readded is the fact this would take two anomaly cores now or one + rd item. Making it very difficult to get, and tradingoff the ability to use those anomaly cores for a myriad of other great stuff such as phazons and reactive teleport armor. It should be powerful with it needing two anomaly cores or one+a head item.

**Comment by neeshacark** [comment]
ok i think making a singularity might be a little too much even if it is really hard to get two

i thought this was reverting it to where the tear was the same size it used to be which would be fine.

**Review by Moltijoe — APPROVED** [review]

**Comment by MajManatee** [comment]
i like singularity

**Comment by ChuChu42** [comment]
i agree with this since you need anomaly cores to make BoHs now

**Comment by ShoziOffical** [comment]
heheheheheheheh co2 engine go brrrr

**Comment by ShoziOffical** [comment]
Also, this is not how you expand singularity to stage 3, see how sm creates singulo

**Comment by ShoziOffical** [comment]
because without energy, it will just disappear

**Comment by Simplehorror** [comment]
> heheheheheheheh co2 engine go brrrr

you can make a singulo with the SM already bro

**Comment by ShoziOffical** [comment]
> > heheheheheheheh co2 engine go brrrr
> 
> you can make a singulo with the SM already bro

yeah you can make inf singulo with this bro, SM only creates 1 singulo on detonation

**Comment by JamieD1** [comment]
> I'm going to be real I don't remember why we removed this

Because they were used to grief a fuck tone with.

**Comment by Hopekz** [comment]
@Simplehorror if you're still around making a boh stop the singularity in 1 bag should be a thing now that they're rare because currently it's like 9-12 bags

**Pull request merged**
