### PR TITLE
NEW FEATURE: Thermite can now burn Reinforced Walls

### PR DESCRIPTION
**Pull request by Simplehorror**
Thermite kinda sucks since clf3 just does its job but better, so now I made it so you can use thermite on reinforced walls with a random chance to try and get through it.

🆑
tweak: mineral walls can now be burnt with thermite
tweak: reinforced walls can now be burnt with thermite
/🆑

### CODE REVIEW

**Comment by Annoying-plant** [comment]
Thermite is funny make it burn walls again!

**Comment by TheRyeGuyWhoWillNowDie** [comment]
🤡

**Comment by LazennG** [comment]
clown reasoning but then again the original pr was also made by a clown

**Comment by Moltijoe** [comment]
i'd be fine with it taking multiple applications if it really MUST be nerfed, but seriously, making it useless on Rwalls might as well remove it

**Comment by ReddicusDragon** [comment]
@TheGamerdk close this please, for violating the Yogstation GitHub Guidelines, specifically the section stating 'In regards to revert Pull Requests, these should only be opened if there is a reason for the reversion ie. the feature is broken or is not as expected when it was merged. Otherwise please wait at least 48 hours before reversing a change.'

**Comment by ReddicusDragon** [comment]
in case anybody is curious, https://docs.google.com/document/d/1DNGBnkMQAWrNHs-wgR5AkxSrigPUMB9KbH_SJGkbv7I/edit?usp=sharing

**Comment by Simplehorror** [comment]
> @TheGamerdk close this please, for violating the Yogstation GitHub Guidelines, specifically the section stating 'In regards to revert Pull Requests, these should only be opened if there is a reason for the reversion ie. the feature is broken or is not as expected when it was merged. Otherwise please wait at least 48 hours before reversing a change.'

this isn't a revert PR, this is brand new feature

**Comment by Moltijoe** [comment]
oh wow, new feature, this is actually a pretty interesting idea, i like it

**Comment by Bibby0110** [comment]
> > @TheGamerdk close this please, for violating the Yogstation GitHub Guidelines, specifically the section stating 'In regards to revert Pull Requests, these should only be opened if there is a reason for the reversion ie. the feature is broken or is not as expected when it was merged. Otherwise please wait at least 48 hours before reversing a change.'
> 
> this isn't a revert PR, this is brand new feature

No it isn’t

**Pull request closed without merging**
