### PR TITLE
Steals floors from Dripstation

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

steals from
https://github.com/Blundir/Dripstation/commit/e5a8722e18c00619c5d1828329b21668406d3359
which steals from tau ceti

holy shid these look nice

# Spriting
gax (best map)
image
image
image
image

# Changelog

:cl:  Blundir, Tau Ceti
imageadd: backports floors from dripstation
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
God please no.

**Comment by Marmio64** [comment]
permanently slippery looking tiles

**Comment by solwashere** [comment]
I love them so much

**Comment by Moltijoe** [comment]
How do they look with the wet overlay?

**Comment by neeshacark** [comment]
not a fan, they look so... wet

**Comment by solwashere** [comment]
I dunno how they look wet to people
They look perfectly fine to me

**Comment by tattax** [comment]
> I dunno how they look wet to people They look perfectly fine to me

wetposting

**Comment by Moltijoe** [comment]
> I dunno how they look wet to people They look perfectly fine to me

I dont think they do, im just curious as to how the overlay appears

**Comment by Blundir** [comment]
> How do they look with the wet overlay?


dreamseeker_Xehy13ynKY
here is example of dirt and lube/water, tho there needs to be 2 pixels added

**Comment by solwashere** [comment]
I think that they look more sterile than wet, which I like because it comes across more as a floor tile that would be on a state of the art research station

**Comment by RG4ORDR** [comment]
The current default floor tiles are fine because they're in effect entirely noise less, they aren't distracting, they're very harmless.
Any changes to floor tiles outside of entire overhauls provided to the station, not including walls looks weird. The change in floor tiles makes them visually noisy.

**Comment by azzzertyy** [comment]
i loathe these

**Comment by RG4ORDR** [comment]
Put them in science ONLY as a test merge to conduct research - otherwise  if the condition this some how gets merged, have it be a station trait or something. The default tiles are completely fine and I don't need to be removed
"DELUXE TILES - Your station has received new and more expensive floor tiles. Don't screw up or Centcom will dock your pay"

**Comment by MajManatee** [comment]
there are bugs in my floors

**Review by cuackles — APPROVED** [review]
After thinking on it for a bit i have decided that this floors are ok to port, they are better designed that the old ones, they do look just sligthly odd for long time yogs players cus they way the light hits them is from the side instead of the top as our current ones do, but that aint a negative its just something different, i will still not merge this pr yet i would like to hear the opinions of anyone with an actual valid point apart from " they ugly, i dont like em" and shit like that

**Comment by azzzertyy** [comment]
I just think they're too noisy.
If you look at the floors on Paradise, they have the similar grid detailing but it doesnt go around the entire floor and instead only on the borders of the tiles, its a lot more muted in terms of colour difference causing less noise.
I'd prefer if the grid pixels that arent on the border were removed similar to paradises' but keeping the overall style the same.

**Comment by azzzertyy** [comment]
image
Wouldn't let me post an image earlier, here.

**Comment by neeshacark** [comment]
essentially what azerty said, they are very loud. i worry they might actually give me a headache much like Kilostation did due to the excessive decal use.

also they look wet to me idk what is wrong with people saying that they don't

**Comment by TerraTheUnwise** [comment]
:(

**Comment by neeshacark** [comment]
the maint plating is just outright bad. it's so DARK and looks really out of place. pluss it looks like a tile, has 4 sections for some weird reason (???)

the Paradise version of these tiles are much less of an assault to my eyes, the main cause of why i dislike them is the grid of dots in the middle and Paradise's removes all but the very outer set of them.  I would go ahead and remove all of the dots but at very minimum do what Paradise did,

**Comment by ToasterBiome** [comment]
going with alternate option

**Pull request closed without merging**
