### PR TITLE
Adds a new 'unique' item to the autodrobe, the lamp-dress.

### PR DESCRIPTION
**Pull request by nesisknesis**
First and foremost, this PR has been paid for by Alexandria404.

Added to the autodrobe is a white dress with an inbuilt lamp, the lamp is not very powerful and is really only there for aesthetic. It is also in the premium section.

I forgot to take pictures and Dream daemon takes too long to load.

For now look at the reference: 
image

As a proud supporter of more clothing for the autodrobe, I see no problem with this.

#### Changelog 

:cl:  Identification
rscadd: Adds a new clothing item to the autodrobe, the lamp-dress.
imageadd: Lamp-dress, light off and light on version.
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
is this fetish content

**Comment by Mr-Space** [comment]
> 
> 
> is this fetish content

yes

**Comment by Mr-Space** [comment]
Can we see the dress pictures from ingame?

**Comment by Alexandria404** [comment]
Best PR. 10/10.
Money well spent.
This is NOT fetish content.

This is a perfectly harmless dress that happens to have a light function built in.
Nothing more.

**Comment by Hopekz** [comment]
**heavy podperson breathing**

**Comment by nesisknesis** [comment]
i found an up-close picture

image

**Comment by Nickvr628** [comment]
oh that does not look as sexy

**Comment by Nickvr628** [comment]
image
nich made an edit to it

**Comment by Ratvar** [comment]
Someone write a fanfic: Poor assistant in a lamp suit prowls maintenance for loot. Suddenly, a nightmare appears! He pursues the poor bald soul, slashing them in process: first PDA falls apart, light growing dim, then suit itself unbinds at seams, leaving beady-eyed graytider trembling in the thick darkness...

**Review by alexkar598 — CHANGES_REQUESTED** [review]
What's up with the edit of the ancient hardsuit helmet?

**Comment by nesisknesis** [comment]
probably altered a pixel or two when i copied the light from it, it shouldnt be noticeable but ill rectify it when i get the chance

**Comment by nesisknesis** [comment]
edit on helmet fixed

**Pull request merged**
