### PR TITLE
Clown Car is now hijack only

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
i will repay my sin with code changes

# Wiki Documentation
Must be hijacker/martyr to clown around

# Changelog
:cl:  
tweak: Clown car is now hijack/martyr only
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
Huff copium

**Comment by KingSuperBOB** [comment]
Martyr SM clown car in question

**Comment by azzzertyy** [comment]
image
if you aint allowed to murderbone then dont give them a tool almost perfectly suited to do such a thing is what i say

**Comment by Moja10** [comment]
> image if you aint allowed to murderbone then dont give them a tool almost perfectly suited to do such a thing is what i say

If yOu ArEnT AlLoWeD tO MuRdErBoNe ThEn DoNt GiVe ThEm ToXiNs and BoMbMaKiNg and TtVs 

bitch we have a whole subdepartment for making things you aren't allowed to use, why would a clown car potentially leading to murderbone be enough to justify it being hijack only

**Comment by azzzertyy** [comment]
> > image if you aint allowed to murderbone then dont give them a tool almost perfectly suited to do such a thing is what i say
> 
> If yOu ArEnT AlLoWeD tO MuRdErBoNe ThEn DoNt GiVe ThEm ToXiNs and BoMbMaKiNg and TtVs
> 
> bitch we have a whole subdepartment for making things you aren't allowed to use, why would a clown car potentially leading to murderbone be enough to justify it being hijack only

why would thugshaker potentially leading to murderbone justify it being hijack only?

**Comment by azzzertyy** [comment]
sure you can argue that you dont want this because its lame and boring, but dont use the excuse that clown car isnt made to murderbone, it is. its hard NOT to kill a non-target if you use it for killing, which, is its only real purpose.
I personally agree, this pr is lame and boring and I dont personally want it merged, but the flaw in the logic that "oh its not made to murderbone" is very much a thing because, yes, it really is.

If you only want to kill one person, just moving them to somewhere to kill them will pick up random ass people.

**Pull request closed without merging**
