### PR TITLE
Removes appendix from darkspawn

### PR DESCRIPTION
**Pull request by Moltijoe**
They can't have surgery done on them to remove it

:cl:  
rscdel: Darkspawn appendix
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
you should make the event ignore their antag datums (/datum/round_event/spontaneous_appendicitis/start())


appendix gang

**Comment by tattax** [comment]
or if you really want to.. you could make a no appendix trait.. since we have NOLIVER and NOSTOMACH already

**Comment by tattax** [comment]
you could also just add trait_nohunger to darkspawns since it removes appendix
and hunger (which sling has but dspawn doesn't)

**Comment by Moltijoe** [comment]
> you could also just add trait_nohunger to darkspawns since it removes appendix and hunger (which sling has but dspawn doesn't)

huh, didn't know nohunger did that, that's probably better so dspawns don't need to eat either

**Pull request merged**
