### PR TITLE
Adds the infinity gauntlet and a game mode to go with it

### PR DESCRIPTION
**Pull request by Putnam3145**
### Intent of your Pull Request

Adds the infinity gauntlet to wizards. When the infinity gauntlet is spawned by a wizard, the infinity zones are all given to heads of staff or random members of the crew (not decided, this isn't even remotely finished). The wizard must locate and take the infinity stones from the individual crew members who have them, but this is difficult, as the stones provide their wielder with great power.

:cl:  
rscadd: Infinity gauntlet as another sort of mini-game mode for wizard
wip: It's really not done yet, this is just a draft pull request so people can point and laugh at the code as I write it, I'll only make this not a draft when I've thoroughly tested it. I'm going to bed, I'll edit this as I go
/:cl:

### CODE REVIEW

**Comment by Oakboscage** [comment]
Hard no from me on this.

**Comment by Moja10** [comment]
This is a cool idea and I like it a lot but the execution isn't all there and it's not fleshed out enough. I think this PR entirely depends on the execution.

**Comment by Altoids1** [comment]
This will probably end up bring a fringe wizard gamemode, in similarity to Ragin' Mages. Keep that in mind when reviewing this.

**Comment by Putnam3145** [comment]
i wouldn't be surprised if it only ever happened due to adminbus or similar

**Comment by k-k-karma** [comment]
lmao hippie's way ahead of u

**Comment by Putnam3145** [comment]
That's about all I can do for now, I think, I got no idea how to test a game mode.

**Pull request closed without merging**
