### PR TITLE
removes fully stocked sec locker from delta maint

### PR DESCRIPTION
**Pull request by UselessTheremin**
north of dorms, there was a fully stocked sec locker by the beer nuke. sure, it was by security, but still. thats a bruh moment right there i tell ya 😳 
🆑
rscdel: removes sec locker from delta maint
/🆑

### CODE REVIEW

**Comment by Hopekz** [comment]
the real bruh moment is playing on delta

**Review by patpol4 — APPROVED** [review]
haha what?

**Comment by UselessTheremin** [comment]
> haha what?

yeah that was my thought how has it been there so long
image

**Comment by boodaliboo** [comment]
damn

**Pull request merged**
