### PR TITLE
THE GREAT ECONOMY REWORK | WE ARE ALL BROKE EDITION

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Cargo budget & bank machine removed from all maps

Security budget stays, but you cannot take from it directly, it should be used directly with the supply console

Paychecks have been consolidated and mostly reduced

Vendor items have been reduced in price to accomodate for paycheck changes

Vendor items that were ridiculously expensive are no longer so

Assistants are paid 7 credits, up from 5, per paycheck

<details>
<summary>EASY jobs, now 10 credits per paycheck, from 20</summary>
Bartender, Chaplain, Cook, Curator, Janitor, Lawyer, Clerk, Psychiatrist, Tourist
</details>

<details>
<summary>MEDIUM jobs, now 12 credits per paycheck, from 30</summary>
Botanist, Cargotech, Gene, Robo, Scientist, Miner, Engineer, Paramedic
</details>

<details>
<summary>HARD jobs, now 15 credits per paycheck, from 40</summary>
Atmostech, Chemist, Det, Doctor, QM, Officer, Viro, Warden, Brigphys, MiningMed, NetAdmin
</details>

Command staff are paid 20 credits, down from 100, per paycheck

## Why budgets?

Budgets made economy pointless entirely. Why would you wait for a paycheck when a single crate is worth 500 credits?

## Why paycheck reductions?

Certain jobs acted similarly. An assistant would make 5 credits where a command staff would make 100. The numbers were so spread apart that you would feel almost useless in comparison to a head as their balance exponentially outpaced yours. This works out well in real life, but on a station limited to 50 people, not so much. It usually ended up where you could just ignore your balance and ask a head to dish out their huge money pit so that you could buy anything you wanted. Certain items were balanced around this inflation, and ended up being absolutely ridiculous in price that didn't at all justify its contents (Adv. medkit for example)

# Changelog

:cl:  
rscdel: Removed cargo budget from QM office
rscdel: Removed withdrawing from budgets
rscdel: Removed bank machine from all maps
tweak: Everyone's paychecks have been significantly consolidated
tweak: All vendor item prices have been made not ridiculous and generally have been reduced
tweak: Vendors no longer give you items for free if you are of their department, instead items are half-off
tweak: Certain jobs are now paid more and others less
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
?????

**Comment by Bibby0110** [comment]
doesn’t compile

**Comment by VaelophisNyx** [comment]
this is a PR seeking an issue

**Comment by 00ze-cyclone** [comment]
That’s the fucking laziest « rework » I’ve seen, you just changed numbers and pretend you solved something. Money got problem in how it work, not in how much there is.

**Comment by VaelophisNyx** [comment]
>This works out well in real life

lmao no the fuck it doesn't

but that's unrelated to the PR

I think NOW it's alright since it means money is less inflated, but so are prices

**Review by adamsong — DISMISSED** [review]
Revert hoverboard price

**Comment by Marmio64** [comment]
Assistants dont need a raise, they're supposed to get a damn job.
In addition, command should get paid more (50 credits or something) so they can afford to give bonuses to good employees and use money incentives to get assistants to do a job they may need done.

**Comment by ynot01** [comment]
> Assistants dont need a raise, they're supposed to get a damn job.

This is funny, but for gameplay purposes, sucks.

> In addition, command should get paid more (50 credits or something) so they can afford to give bonuses to good employees and use money incentives to get assistants to do a job they may need done.

I have been very careful with how much money is spread between each tier. Even a small amount of credits amounts to a huge difference over the course of the shift. 50 more credits would amount to 900 more credits over the entire shift. What the hell are you going to spend 900 credits on? That's more money than anyone would need anything for.

**Comment by Marmio64** [comment]
> > Assistants dont need a raise, they're supposed to get a damn job.
> 
> This is funny, but for gameplay purposes, sucks.
> 
> > In addition, command should get paid more (50 credits or something) so they can afford to give bonuses to good employees and use money incentives to get assistants to do a job they may need done.
> 
> I have been very careful with how much money is spread between each tier. Even a small amount of credits amounts to a huge difference over the course of the shift. 50 more credits would amount to 900 more credits over the entire shift. What the hell are you going to spend 900 credits on? That's more money than anyone would need anything for.

i literally just said that you'd spend it on giving other people a raise or as a money incentive
and i also meant that their paycheck be increased to 50, not by 50.

also dont see how for gameplay purposes that it sucks assistants get paid like shit, they're supposed to try to make ends meet in other ways like doing cargo bounties in exchange for some of the cut (though this won't be possible any longer...), scouring maint for loot to sell and to find money there, doing one off jobs for others, etc.  Or you know, just getting a real job.

**Comment by ynot01** [comment]
> i also meant that their paycheck be increased to 50, not by 50.

numbers numbers, maybe a maint will help us out

> scouring maint for loot to sell and to find money there, doing one off jobs for others, etc. 

this shouldn't be an assistant exclusive thing, economy should be present for everyone

> Or you know, just getting a real job.

~~pretty sure job changes at HoP doesn't adjust your paycheck~~ it does

**Comment by ToasterBiome** [comment]
> pretty sure job changes at HoP doesn't adjust your paycheck

when you code it

**Comment by Bibby0110** [comment]
A better approach to letting crew have more money is to merge something like bounty cubes or similar. Devaluing everything doesn't really solve anything. Balancing might be in order but you should probably do that in a different PR and list all your changes.

**Pull request closed without merging**
