### PR TITLE
[admin] Admins can now view antagonists easier through the orbit menu

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Ligma

I hate swapping between orbit and check antagonists

### CODE REVIEW

**Comment by ChuChu42** [comment]
make it for everyone so players dont have to orbit each people and check inventories

**Comment by ynot01** [comment]
> make it for everyone

When everyone gets check antagonists verb I will

**Review by adamsong — APPROVED** [review]
lgtm

**Comment by adamsong** [comment]
> make it for everyone

[Form for requesting access](https://forums.yogstation.net/form/18/select)

**Pull request merged**
