### PR TITLE
Resprites Henrys favorite coat

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
unknown
GreenCoat
coat4
coat3 ong
coat2
Coat1

wiki - image

# Changelog

:cl:  

imageadd: One of HoS coats don't look like paper anymore

/:cl:

### CODE REVIEW

**Review by ToasterBiome — DISMISSED** [review]
darkest dark is too dark to match other clothing items

**Comment by VaelophisNyx** [comment]
so why are we keeping a direct nazi reference to satisfy one man?

**Comment by KillerOrcaCora** [comment]
That change request is by far the most ignorant thing I've seen all week there is literally a suit in the same dmi with a higher RGB darker than mine what kinda weed are you smoking? I want a puff! 

Also why is a C*der reviewing a sprite only PR.

**Comment by JamieD1** [comment]
> so why are we keeping a direct nazi reference to satisfy one man?

Sigh

**Review by cuackles — CHANGES_REQUESTED** [review]
Darks are still to dark, and side looks to thick, resembles a chest piece , also reminder that mostly everyone opinions is valid over the sprite indepentant on if they are spriters or not

**Comment by KillerOrcaCora** [comment]
> Darks are still to dark, and side looks to thick, resembles a chest piece , also reminder that mostly everyone opinions is valid over the sprite indepentant on if they are spriters or not

Coders shouldn’t be reviewing sprite PRs just as spriters can’t review coder PRs

**Comment by cuackles** [comment]
> > Darks are still to dark, and side looks to thick, resembles a chest piece , also reminder that mostly everyone opinions is valid over the sprite indepentant on if they are spriters or not
> 
> Coders shouldn’t be reviewing sprite PRs just as spriters can’t review coder PRs

Anyone with coding knowledge that notice something odd looking on code can give insight, same for sprites, but that comes more easily as artistic critique doesn't need to learn a coding lenguaje, also biome is an spriter too

**Comment by KillerOrcaCora** [comment]
> > > Darks are still to dark, and side looks to thick, resembles a chest piece , also reminder that mostly everyone opinions is valid over the sprite indepentant on if they are spriters or not
> > 
> > 
> > Coders shouldn’t be reviewing sprite PRs just as spriters can’t review coder PRs
> 
> Anyone with coding knowledge that notice something odd looking on code can give insight, same for sprites, but that comes more easily as artistic critique doesn't need to learn a coding lenguaje, also biome is an spriter too

I agree but that is different from what I am saying here.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
anyone can review PRs, only certain ones block merging, moogle reviews code all the time, feel free to review code ones when you learn to read

**Review by cuackles — APPROVED** [review]

**Pull request closed without merging**
