### PR TITLE
Gives ethereals special eyes

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Gives ethereals an interesting and unusual mechanic

(was initially moths until i was bullied into giving it to ethereals instead)

# Testing
image
image

# Spriting
image

:cl:  
tweak: Ethereal eyes now give +1 view range
/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
*etherealscream.ogg

**Comment by UltraBigRat** [comment]
As an ethereal main, moths deserved this more. By the way is there any way to toggle the view range like how species with night vision can toggle it?

**Comment by Yarinoi** [comment]
agreed, moths should have it

**Comment by Moltijoe** [comment]
> As an ethereal main, moths deserved this more. By the way is there any way to toggle the view range like how species with night vision can toggle it?

Ive already made a sprite, its staying like this

Also, unfortunately the code is janky enough that a toggle wouldnt be ideal

**Comment by UltraBigRat** [comment]
> > As an ethereal main, moths deserved this more. By the way is there any way to toggle the view range like how species with night vision can toggle it?
> 
> Ive already made a sprite, its staying like this
> 
> Also, unfortunately the code is janky enough that a toggle wouldnt be ideal

fair enough, albeit a bit worried itll make it harder to click things with the smaller sprites having increased view range gives.

**Comment by MajManatee** [comment]
pretty based

**Comment by neeshacark** [comment]
> > > As an ethereal main, moths deserved this more. By the way is there any way to toggle the view range like how species with night vision can toggle it?
> > 
> > 
> > Ive already made a sprite, its staying like this
> > Also, unfortunately the code is janky enough that a toggle wouldnt be ideal
> 
> fair enough, albeit a bit worried itll make it harder to click things with the smaller sprites having increased view range gives.

this is a good point which makes it more of a sidegrade, maybe make this a toggleable thing?

**Comment by neeshacark** [comment]
> > > > As an ethereal main, moths deserved this more. By the way is there any way to toggle the view range like how species with night vision can toggle it?
> > > 
> > > 
> > > Ive already made a sprite, its staying like this
> > > Also, unfortunately the code is janky enough that a toggle wouldnt be ideal
> > 
> > 
> > fair enough, albeit a bit worried itll make it harder to click things with the smaller sprites having increased view range gives.
> 
> this is a good point which makes it more of a sidegrade, maybe make this a toggleable thing?

i cant read, i dunno. guess we'll have to wait and see

**Review by cuackles — APPROVED** [review]

**Review by MajManatee — APPROVED** [review]
i mean if there was balance issues it surely would have been mentioned by now

**Pull request merged**
