### PR TITLE
Lets vampires drink blood packs to increase usable blood & fixes horrendously broken code

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Vampires can now sip from IV blood packs to gain 5 usable blood per sip
Vampires will sip 10u per sip, which will result in 100 usable blood per pack (200u roundstart)

Using a live human + IV setup would result in twice as much usable blood and total blood alongside it

Shouldn't be too broken and adds some useful interaction for a vampire down on their luck 

Also fixes misused reagent functions from bloodsucker interaction with blood packs & changes all the stupid `user` checks to `target` checks so you don't get blood from feeding other people

# Wiki Documentation

Vamps can now drink from IV blood packs

# Changelog

:cl:  
rscadd: Vampires can now drink from IV blood packs
bugfix: Fixed bloodsuckers not drinking properly from IV blood packs 
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
tested?

**Comment by VaelophisNyx** [comment]
aren't vampires slated for eventual removal

**Comment by ynot01** [comment]
> aren't vampires slated for eventual removal

what, for 4 months now? sure

**Comment by Marmio64** [comment]
this seems like it further encourages vampire passivity and friendliness. Why not buff the blood regen of the vampire cloak instead or something?

**Comment by ynot01** [comment]
> this seems like it further encourages vampire passivity and friendliness. Why not buff the blood regen of the vampire cloak instead or something?

personally if i were to buff the vampire cloak id set the blood threshold to like 200 or something it kinda sucks tbh but thats not what im going for here

**Comment by MegaEmpirical** [comment]
I like it. Now I can finally do the blood bank idea I've always wanted to do. If i ever get vampire, never been a vampire, ever.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
