### PR TITLE
Darkspawn gamemode

### PR DESCRIPTION
**Pull request by SomeguyManperson**
After 9 years in development, hopefully it will have been worth the wait
Original PR: tgstation/tgstation#35033
Original original PR with (semi-outdated) information: tgstation/tgstation#24267
Darkspawn need to use their devour will ability on 15-30 (population scaled) different people, as well as purchase all passive abilities to unlock their win condition.
Possible changes:
Increasing or decreasing stun times on the pass harm intent attack and/or adding a psi cost to using it (currently causes a short stun on hit, alongside a knockdown)
~~Adding veils (thralls) back~~ done
Make progenitor more fun than just a super powerful simplemob
~~Scaling the number of unique devour will victims for winning by population similarly to shadowlings~~ done
Buff scream ability since it's kinda trash for how expensive it is, alternatively give it a better cost

ABILITY LIST:
Actives:
**Devour Will:** Baseline, costs 5 psi. Puts a dark bead in the user's hand that they can use on a conscious human to drain psi and lucidity. The dark bead lasts 3 seconds after being prepared, you have to hit someone before then.
**Pass:** Baseline, Costs no psi to use. Morphs a free hand into a mass of tendrils that have many uses. For instance, you can attack a floor tile on help intent to stealthily and "undetectably" pull yourself to it, or use harm intent to throw it, stunning for one second and knocking down the first person it hits, disarm intent allows you to open doors and smash down bolted doors at a cost of psi.
**Demented Outburst:** Costs 2 lucidity to unlock, costs 50 psi to use. After five seconds, unleashes a shockwave that bowls over everyone nearby and sends objects flying. Not interrupted by movement and can only be cancelled by going unconscious.
**Simulacrum:** Costs 1 lucidity to unlock, costs 20 psi to use. Creates an illusion that mimics you and runs forward for ten seconds. The illusion is revealed when examined.
**Tagalong:** Costs 2 lucidity to unlock, costs 30 psi to use. Melds with a nearby target's shadow, allowing you to "ride" them into lit areas. Use this in any way you can think of; spying, stealth. This ability is canceled if the target enters a dark area, as they won't have a shadow anymore.
**Silver Tongue:** Costs 1 lucidity to unlock, costs 60 psi to use. Recalls the emergency shuttle if the umbrage has access to a comms console. 
**Creep:** which costs 5 psi to use plus 5 psi per ~second and 2 lucidity to unlock, which lets you not die in light as long as it's active
**Time dilation:** 75 psi to cast and 3 lucidity to unlock,  which makes you immune to slowdown and do actions faster for a minute
**Veil mind:** costs 60 psi to cast and 1 lucidity to unlock, converts nearby people who have recently had their will devoured into veils, which are loyal to the darkspawn but can be deconverted with mindshield implants.
Passives:
25% faster healing in darkness for 1 lucidity
halved burn damage from light and resistance from dimmer lights for 2 lucidity
25 extra maximum psi for 2 lucidity
faster psi regen and 5 more psi regeneration for 1 lucidity
spaceproofing for 3 lucidity
upgraded pass tendrils for 1 lucidity, allowing them to drag people to you and stunning them twice as long on harm intent
:cl:  Xhuis for code, Theos for porting
rscadd: Adds darkspawn, a shadowling-like gamemode without the pesky thrall count
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
So this isn't replacing any gamemodes, correct?

**Comment by SomeguyManperson** [comment]
This doesnt touch any shadowling code, just adds the new mode

**Comment by Alexandria404** [comment]
DIslike it, not every rev round is a rush. Forcing everyone to rush is shitty.

**Comment by AsV9** [comment]
I guess we can see if this works

**Comment by SomeguyManperson** [comment]
Veils have been added, with the requisite ability costing 1 lucidity and 60 psi to cast. Currently there's no tells. Throwing pass will now also cause a short stun, alongside the knockdown. The requirement for winning is now scaled similar to shadowling thrall scaling.

**Comment by ynot01** [comment]
🦀 testmerge is gone 🦀

**Pull request merged**
