### PR TITLE
Changes Free Miner Engineer flavor text slightly

### PR DESCRIPTION
**Pull request by Ktlwjec**
So people don't get confused like in #3372

### CODE REVIEW

**Comment by Ktlwjec** [comment]
help what happen

**Comment by thehighwayman** [comment]
didn't modularize dummy

**Comment by thehighwayman** [comment]
okay I think travis failed due to a network problem causing it to stall

**Comment by Ktlwjec** [comment]
imagine thinking you have to modularise in the yogs folder :laughing: :rofl:

**Review by Amelia0010 — APPROVED** [review]
travis man bad

**Pull request merged**
