### PR TITLE
Removes the flamethrower from the hacked autolathe

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Let's remove weapons from machines that p much anyone has access too, yay

#### Changelog

:cl:  
tweak: flamethrower is no longer obtainable through the autolathe
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
You still need a plasma tank and all the tools to make a flame thrower are already in the autolathe(screwdriver,rods,welder)

**Comment by Xoxeyos** [comment]
Flamethrower is easy to make anyhow, not that it's used too much.

**Comment by MonsWTF** [comment]
Were these flamethrowers still needing to be filled, or did they come pre-loaded?

**Comment by alexkar598** [comment]
Nich did bring up good points on discord

Its not like anyone cant make a flame thrower with this change anyways

```
1. I figure that people who craft the flamethrower rather than getting it from the lathe are people who are already intent on getting it, whereas some who get it from the lathe might just be getting it cause ayy lmao it's there (and yes I know it's only when it's hacked, but that just takes a screwdriver and a crowbar to do, so it's not really that large of a hurdle)

2. It's kinda hard to justify that you can't walk around with random weapons if said weapons are easily available all over the place. Like how scientists for some reason got a free pass for the AE gun, just because "ayy lmao it's printed in science"``` -Nichboi 2019

**Pull request merged**
