### PR TITLE
Adds New Lavaland Ruin, The Displaced Bar And Kitchen

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

A partial player reference ruin (Player unnamed and the references are vague)
Copied from and modified from the Box bar variant

included loot is a bunch of random food and drinks, a lot of trash, some mobs, a bunch of money, some gold trophies, one Shark Hoodie, and one Secret Recipe

# Wiki Documentation

ss (2022-09-13 at 04 34 14)

requires addition to the Lavaland Ruins page

# Changelog

:cl:  
rscadd: Added a new Lavaland Ruin, the Displaced Bar And Kitchen
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
How bout some girders around, broken parts of floor, etc. Can definitely make it look more destroyed!

**Comment by VaelophisNyx** [comment]
fastest maptainer input in the west

will do

**Comment by GraveHat** [comment]
> fastest maptainer input in the west
> 
> will do

Speaking off make it more obvious where the point of entry came from and maybe use some destroyed plating to help make it more visually distinct.

And also update the image.

**Comment by VaelophisNyx** [comment]
I know I know

also nothing physical changed with that commit, it was fixing the file name

**Comment by VaelophisNyx** [comment]
Made more destroyed
used fake lattice decals*

**Comment by VaelophisNyx** [comment]
when you get ghosted by the coolest maptainer

**Review by ToasterBiome — APPROVED** [review]
yeah looks mint

**Comment by Addust** [comment]
fake lattice is shit

**Pull request merged**
