### PR TITLE
Removes sloth ruin

### PR DESCRIPTION
**Pull request by Takahiru**
# Intent of your Pull Request

The sloth ruin is simply a waste of space on lavaland. It provides nothing except maybe tricking a newbie miner one time only for them to never enter it again. 
I tried thinking of improving it, but sloth is literally the most boring of the seven sins so I can't think of anything.

#### Changelog

:cl:   
rscdel: Removes sloth ruin
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
> sloth is literally the most boring of the seven sins so I can't think of anything.

this almost makes me want to keep it for the irony

**Comment by boodaliboo** [comment]
keep it

**Comment by fluffe9911** [comment]
eh Ill get around to merging this eventually maybe meh

**Review by patpol4 — CHANGES_REQUESTED** [review]
Don't remove it from the game, blacklist it.

**Comment by MrHorizons** [comment]
I think we should keep it, if only to keep the "sins" theme whole. Though we could certainly cut the size of the ruin down heavily: perhaps they didn't even have a ruin to add,

**Comment by Takahiru** [comment]
> I think we should keep it, if only to keep the "sins" theme whole. Though we could certainly cut the size of the ruin down heavily: perhaps they didn't even have a ruin to add,

It seems like they did intend to expand on it based on one of the comments, but it never happened.

**Comment by Takahiru** [comment]
> Don't remove it from the game, blacklist it.

its in the blacklist config by default e

**Comment by UselessTheremin** [comment]
the point is that it sucks and is a waste of space. i find it funny, and it helps balance out how there are really good ruins.

**Comment by MegaEmpirical** [comment]
Not all ruins need to be 'good'. Miners have enough loot.

**Comment by Takahiru** [comment]
> Not all ruins need to be 'good'. Miners have enough loot.

It dosen't even look good, it's just a waste of space, i didn't want to give them another item either so idk

**Comment by Takahiru** [comment]
brr people really think its a great part of the game so goodbye pr

**Pull request closed without merging**
