### PR TITLE
Revert "Suiciding no longer counts towards completing the "Die a glorious death." objective"

### PR DESCRIPTION
**Pull request by ynot01**
yogstation13/Yogstation#2947

suicide is glorious sometimes & you can just punch yourself into crit then succumb anyways let people get creative

### CODE REVIEW

**Comment by Mqiib** [comment]
Yeah but this is lame.

**Comment by Partheo** [comment]
The suicide command is never glorious. You can kill yourself in so many other ways, which is exactly what this objective intended

**Comment by yacabo** [comment]
Say you wanted to sacrifice yourself cultist style, the best way to do this via the suicide command. We should assume good faith in the player in the case of suiciding with glorious death

**Comment by Potototatoh** [comment]
i ded becausd i died a glorious death

**Comment by Mr-Space** [comment]
go out with a bang, literally who gives a shit when you bite your tongue and die

**Comment by Ratvar** [comment]
Actually make a cult to sacrifice yourself and it will be glorious compared to just lazy and edgy. Ya have hypnosis, emag and surgeries for that, all options you would not think ta use if suicide was an easy way out

**Comment by Moja10** [comment]
if you want to die so badly just walk out an airlock lmao

**Comment by ShadowDeath6** [comment]
What if you want to airtank explode or something, that’s a suicide

**Comment by Ktlwjec1** [comment]
Nah, preventing suicide forces people to get at least a little bit creative. You shouldn't be able to just *suicide and that's your entire objective done. Just beat yourself to death or walk out an airlock if it's really an issue for you.

**Pull request closed without merging**
