### PR TITLE
Moves angel potion to stealthy tools category. New angel potion sprite. Gives syndicate angel potion it's own unique sprite.

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Moves angel potions from race restricted to stealthy tools.
Makes it REALLLLLLLY fucking obvious if someone finds your potion.

uplink description: "After many failed attempts, the syndicate has reverse engineered an angel potion smuggled off of Lavaland. \
			Preliminary testing could only sprout wings in Humans, Vullen, Ex'hau, Preterni, IPCs, and Phytosians."

# Spriting
image
image

Description: "An ornate red bottle, with an \"S\" embossed into the underside. Filled with an experimental flight potion. Mileage may vary."

When it's empty it will just be "An ornate red bottle, with an \"S\" embossed into the underside."

# Wiki Documentation

Angel potion has a new sprite and a different uplink category.

# Changelog

:cl:  
tweak: moves syndicate angel potion to stealthy tools
imageadd: Angel potion has a new sprite
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
some species still can't use it

*checks list*
-ethereals
-polysmorph

nevermind, we're good

**Comment by ToasterBiome** [comment]
> some species still can't use it
> 
> _checks list_ -ethereals -polysmorph
> 
> nevermind, we're good

also added in the description

**Comment by tattax** [comment]
the tg beaker sprite style... you have to port it now.... you have to seal the beaker sprite pact.... biome...

**Comment by MajManatee** [comment]
I wish there was a difference between the syndicate wings and the non-syndicate wings so I could shoot all those retarded lizards that buy it just to be cutesie or something else thats dumb.

**Review by cuackles — APPROVED** [review]

**Pull request merged**
