### PR TITLE
Add vampire help button since people actually can't read unless they click a button that tells them to read

### PR DESCRIPTION
**Pull request by SomeguyManperson**
yes
#### Changelog

:cl:  
rscadd: Adds a button for vampires to click that tells them how to get blood
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
how suck help

**Comment by Hopekz** [comment]
Can also maybe throw in somewhere that bloodbags don't work because that's also a big point of confusion.
One of the first things people try when you tell them they need blood.

**Comment by ynot01** [comment]
mentorhelp how do I suck blood?

**Review by Hopekz — APPROVED** [review]
Ideal way would be something similar to how goon does it with a popup tutorial box when you get antag but otherwise, this is alright code-wise. Hilarious to do it as a spell though but not sure how to get people to read otherwise like you said.

**Comment by SomeguyManperson** [comment]
If its in greet text, it's ignored
If its in a popup window, it'll probably alsp be ignored by several Who just close it for funsies
Putting it into a spell means if someone needs to know how to suck blood they'll be able to find out by blindly panicking and scrolling over all their ability buttons

**Review by JamieD1 — APPROVED** [review]

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
