### PR TITLE
Borgs can no longer heal themself when they are over crit threshold

### PR DESCRIPTION
**Pull request by alexkar598**
Borgs has a nasty tendency to fuck you up, and just when you get the upper hand, they retreat, bolt the door, and 30 seconds later you have a borg fully ready to fuck you up again because they healed like a NERD.

:cl:  
tweak: Borgs can no longer heal themself when they are over 0 health(health goes from -100 to 100)
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
this very much fucks minerborgs without the self repair module, as they need to be able to self repair to handle mobs effectively

they also have an emergency welding tool, so unlike engiborgs they can't take massive damage and constantly self repair, it only holds a little welding fuel and dragging a tank around with them is a weakness in and of itself

limit this to engineering cyborg self repair, as minerborgs do need to be able to self repair to be able to do anything on lavaland

**Comment by alexkar598** [comment]
They can still heal themself, just not to full health

**Comment by Mqiib** [comment]
I really think it should be the other way around, where once they take >100 damage it turns it all into burn damage resulting in them not being able to repair that. Maybe even only 75 or something, but borgs should be able to fix superficial damage to themselves just fine.

Last module on a borg goes down at -50, meaning this cuts the amount of repairs they can do on themselves to 1/3 of what it was but in the wrong direction. Hell, even if they had "armor plates" or something that had 50 health and were the only things they could repair that would be FINE.

**Comment by ghost** [comment]
@alexkar598 
no they can't lol. not being at full health as a minerborg on lavaland is, for all intents and purposes, the same as not being able to repair at all. if you get hit once, you lose a module, potentially your last module, because you can't fully repair.

if you want to make yet another stupid change that inevitably gets reverted a month later when everyone realizes how terrible it is be my guest, i don't play here so it doesn't affect me, but i'm telling you outright it'll fuck minerborgs

**Comment by Ratvar** [comment]
I am not sure we will have a single mining borg player to complain in a whole month, really: they are not the most popular module.
or they can just stop hunting fauna and retreat once damaged, which is an available option: they are made at maximum to mine stuff if all miners are dead, anyway, and have no need to hunt goliaths.

**Comment by boodaliboo** [comment]
please make engi borgs not able to heal themselves

**Comment by nesisknesis** [comment]
cant wait to revert this a month later

**Pull request merged**
