### PR TITLE
Remove donor priviledges from mentors

### PR DESCRIPTION
**Pull request by alexkar598**
Remove donor priviledges from mentors

This will never pass, i just wanna see everyone hatin' on me

### CODE REVIEW

**Comment by alexkar598** [comment]
I thought you said 24 hours jamie

**Comment by JamieD1** [comment]
Meme PR, stop rocking the boat.

**Comment by alexkar598** [comment]
This is not a mémé

**Comment by JamieD1** [comment]
Want me to council vote it?

**Comment by alexkar598** [comment]
# YES

**Comment by JamieD1** [comment]
Awaiting Vote #826

**Comment by alexkar598** [comment]
# OH NO THERES A MERGE CONFLICT!

**Comment by alexkar598** [comment]
SPEEDMERGE TIME

**Review by adamsong — APPROVED** [review]
Looks good, no errors

**Comment by JamieD1** [comment]
.....

**Comment by JamieD1** [comment]
Time to Remove alexkars Admin from github

**Comment by N3D6** [comment]
oh god our righst are gone

**Pull request merged**
