### PR TITLE
Nerd shit (updates prescription glasses sprite)

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Nerd powercreep, makes the prescription glasses that you can get not look ugly and white. Sprite is partially ported from CEV Eris, which was likely ported from Baystation 12, but is heavily altered. Couldn't find the original spriter after poking around for like two hours.

# Spriting
image
image

# Wiki Documentation

# Changelog

:cl:  
 
tweak: Updated prescription glasses sprite
imageadd: added sprite for prescription glasses 

/:cl:

### CODE REVIEW

**Comment by thegoldencat413** [comment]
finally… it’s all coming together…

**Review by BlueishTsunami — APPROVED** [review]
Nerd

**Comment by iamthesilly** [comment]
Nerd

**Comment by Moltijoe** [comment]
🤓

**Comment by neeshacark** [comment]
not a fan personally, imo we should be able to alt click glasses to customize them

**Comment by solwashere** [comment]
> not a fan personally, imo we should be able to alt click glasses to customize them

If you wish to do that personally then go ahead. However this looks infinitely better than the current glasses as the current glasses contrasts horribly with most clothes and skin tones

**Comment by Therandomhoboo** [comment]
nerd

**Pull request merged**
