### PR TITLE
Sharing is bad

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Adds a line to the job description of syndicate ghost role spawners that prevents them from just... giving away their stuff to their most hated enemies, and instead encourages violence. 

Why would they do that? idk, but they do.

# Changelog

:cl:  
tweak: Syndicate Ghost Roles aren't allowed to share with NT.
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
But sharing is caring!

**Comment by SomeguyManperson** [comment]
what happened here

**Comment by MajManatee** [comment]
I hate curators

**Review by Moltijoe — APPROVED** [review]
Text changes

**Comment by Addust** [comment]
I WILL DRAFT THE FREE MINERS INTO THE SYNDICATE

**Pull request merged**
