### PR TITLE
Updates sprites of the standard security uniforms.

### PR DESCRIPTION
**Pull request by nesisknesis**
images with additions from hopekz' feedback

security
image
warden
image
hos
image

i might instate a standard colour scheme for security uniforms since i used a standard here

#### Changelog

:cl:  Identification
imageadd: The security, head of security, and warden uniform have been updated. 
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
maybe security gear could do with an update

**Comment by MegaEmpirical** [comment]
Does this affect the plasmaman uniforms too? Which by the way are still fucking great.

**Comment by Hopekz** [comment]
Can you like maybe post screenshots?

**Comment by HomocidlePancakes** [comment]
>Does this affect the plasmaman uniforms too? Which by the way are still fucking great

>Can you like maybe post screenshots?

Icon diff bot? Hello?

**Comment by Hopekz** [comment]
> > Does this affect the plasmaman uniforms too? Which by the way are still fucking great
> 
> > Can you like maybe post screenshots?
> 
> Icon diff bot? Hello?

making me do actual work was this a part of your master plan

**Comment by Hopekz** [comment]
Opinion inbound
------
I have circled which one I think is better out of all the sets being modified.
Since there is more of the "old" than "new"(6 vs 3) I'm going to -1 this PR. 

What I don't like: I don't like that the uniforms are becoming more "plain" as I like the added detail. Turns an in-command style jumpsuit into a rookie officer jumpsuit.

image

**Comment by Hopekz** [comment]
Reworked my opinion after your update
-----

Circled preferred out of all sprites. 
Legend: +1 is good , +0 is as good as original sprite in its own way but not really "better" (so okay) , -1 means old sprite was better in my opinion.

New opinion score: -1 vs original -3
-----
image

Feedback
----
Notes on what I personally think the +0 sprites are missing:
While the sprites marked 0 are okay as-is if you want to make them "better" than the original I suggest making the shoulder line outlines more pronounced. In the original it "pops" out of the sprite .
You have better colors overall just needs a little more "popping" to put it ahead of original sprite. 
OLD VS NEW:
image image


OLD vs NEW: 
-----
Another thing that I think your sprites need work on to make them overall better is the collars.
Please see how these collars are implemented. The dressed collars even are more puffy at times and have that white accent while the collars in your PR seem to be non existent. Your sprites almost seem to be built for someone without a neck. 

image image

**Comment by nesisknesis** [comment]
image
image
image
image

**Pull request merged**
