### PR TITLE
Adds a new crusher trophy: malformed bone

### PR DESCRIPTION
**Pull request by LazennG**
# Document the changes in your pull request
sk

Adds a new crusher trophy, malformed bone, to the Legion megafauna. On detonation, everything within a few spaces of the user each has a 40% chance to get a crusher mark applied to them.

# Changelog

:cl:  
rscadd: Adds a new crusher trophy for the legion megafauna 
imageadd: adds a sprite for the new trophy too
/:cl:
thanks to @Chubbygummibear and @ToasterBiome for helping me out when I couldn't get the newly applied crusher mark working correctly, along with @cuackles for spriting the trophy.

### CODE REVIEW

**Comment by Junkyshell** [comment]
omggg powergameing! donvote

**Comment by LazennG** [comment]
> omggg powergameing! donvote

i HATE maine admins >:(

**Comment by Junkyshell** [comment]
> > omggg powergameing! donvote
> 
> i HATE maine admins >:(

doxing bro rly?

**Comment by ToasterBiome** [comment]
who helped u wit dis

**Comment by Chubbygummibear** [comment]
thanking me when my contribution was 
"hold on let's try this... that doesn't work either" like 5 times
you're too kind lmao

**Comment by cuackles** [comment]
Trophy be doing the :v face

**Review by nesisknesis — COMMENTED** [review]
Edit the changelog so that people reading it know what you are actually adding

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
