### PR TITLE
Ynot01's borg skin

### PR DESCRIPTION
**Pull request by Kmc2000**
At ynot01's request, this PR adds a police borg skin.
Just make sure to present your skin license when using it.

#### Changelog

:cl: Kmc2000 
rscadd: Added a police themed donor borg skin
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Kinda looks like the base module

**Comment by Kmc2000** [comment]
That's the point

**Comment by FatalEYES** [comment]
It's a base sec module recolor with a police hat, yes. Good eye.

**Comment by ThatLing** [comment]
Stale

**Comment by ThatLing** [comment]
yeah ok just wanted to make sure the merge conflict was still there carry on gamers

**Pull request closed without merging**
