### PR TITLE
Revert "[PORT] Dragging prone mobs slows you down, fireman carrying"

### PR DESCRIPTION
**Pull request by boodaliboo**
i dont like it

### CODE REVIEW

**Comment by redmoogle** [comment]
image
care to explain more about **what you dont like**

**Comment by Reed0506** [comment]
classic bood moment right here

**Comment by boodaliboo** [comment]
> image
> care to explain more about **what you dont like**

its annoying

**Comment by alexkar598** [comment]
PRs aren4 speed reverted just because "you dont like it"

**Pull request closed without merging**
