### PR TITLE
Theos commits an atrocity upon the pure and good toolset implant code to make it actually worth using under any circumstances

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Allows the toolset implant's radial menu to be selected by using the currently active tool in hand
this takes a massive amount of shitcode compared to the relatively minor QOL provided but will increase the speed of  actually using the implant massively since it doesn't take like 5 clicks to simply switch tools any more

currently feature complete but icons are still being fucky wucky + potentially some other stuff

https://user-images.githubusercontent.com/24857008/160841305-dc02fbf0-5ae0-4b3d-baf6-9d8641ef91b6.mp4

# Wiki Documentation

toolset implants can have their tools switched by using in hand

# Changelog

:cl:  
tweak: toolset implants can have their tool switch menu opened by using the currently active tool in-hand
bugfix: fixes a runtime caused by welding fuel tanks attempting to refill any TOOL_WELDER then expecting them to actually be welders
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
@SomeguyManperson ok now weld something

**Comment by SomeguyManperson** [comment]
> @SomeguyManperson ok now weld something

the welder's icon is currently the main mess however it DOES turn on even though it doesn't look like it

https://user-images.githubusercontent.com/24857008/160951112-97592ed3-efbc-4acc-b4c0-da4fc3b58ebc.mp4

**Comment by Anvilman6** [comment]
Oh no it's so sleek and robust

**Comment by ToasterBiome** [comment]
image

**Comment by SomeguyManperson** [comment]
> image

Draft + already fixed

**Comment by Reed0506** [comment]
while you can technically achieve a similar effect ingame already by just moving the toolset's button closer to the middle of the screen, this is definitely cooler.

**Comment by JamieD1** [comment]
Interesting

**Comment by LazennG** [comment]
implant no longer ultimately more of a hassle than just using a toolbox

**Comment by SomeguyManperson** [comment]
all the welder icon bullshit is fixed and this is effectively feature complete

**Review by JamieD1 — APPROVED** [review]
Epic

**Pull request merged**
