### PR TITLE
Removes the lizard wine from planetcracker

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Removes the 2u requirement of planetcracker
Still keeps the 4u output

### Why its good for the game
Good luck ever getting a lizard tail lol

# Wiki Documentation

Remove L. Wine Requirement

# Changelog

:cl:  
tweak: Planet Cracker no longer takes 2u of lizard wine
/:cl:

### CODE REVIEW

**Comment by ThatGuyPhil** [comment]
"good luck ever getting a lizard tail" 

empty clones exist

**Comment by redmoogle** [comment]
> "good luck ever getting a lizard tail"
> 
> empty clones exist

yees but who would do that reasonably

**Comment by SomeguyManperson** [comment]
what is having a drink hard to make a bad thing

**Comment by redmoogle** [comment]
> what is having a drink hard to make a bad thing

Yes because theres very little incentive to make it

**Comment by ThatGuyPhil** [comment]
> > "good luck ever getting a lizard tail"
> > empty clones exist
> 
> yees but who would do that reasonably

Whoever's not afraid to ask really. I've had lizard clones made for the cargo bounty for lizard tail. 
yall just lack initiative

**Comment by ThatGuyPhil** [comment]
> > what is having a drink hard to make a bad thing
> 
> Yes because theres very little incentive to make it

there is a lot of hard to make drinks and people still make them

**Comment by SomeguyManperson** [comment]
Should we remove the blue cherry juice from its related drinks too because nobody makes them

**Comment by redmoogle** [comment]
> Should we remove the blue cherry juice from its related drinks too because nobody makes them

just make it easier to craft

**Comment by Chubbygummibear** [comment]
if you really want to make it more accessible you can remove the synthetic tail crafting blacklist from the limb grower port i did

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
