### PR TITLE
Increases head time requirements. Crew buff??

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request
Increases the amount of time required to play a head role and captain. I feel that this is good for the game as it lets people gain somewhat more experience before clicking on the shiny head position and potentially ruining a round with incompetence
CMO, CE and HoS require 25 hours from their respective departments
RD requires 20 hours (Doesn't need to know as much)
HoP is 12 hours as it doesn't require all too much skill to play but you do need to have played enough to know that handing out AA to a clown isn't advised
Captain requires 15 hour head experience.
as for the buff biome said to buff something and uh... I feel like this is a buff to the crew, I dunno. 
# Spriting

# Wiki Documentation

# Changelog

:cl:  
 
tweak: increased time that heads need in their respective departments

/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
perhaps a bit overly restrictive imo

**Comment by solwashere** [comment]
> perhaps a bit overly restrictive imo

honestly not restrictive enough but I knew if I threw in more people would have my head
head positions are expected to be knowledgeable in their respective departments and when they aren't they can ruin a round in so many ways.

**Comment by ChuChu42** [comment]
captain requires people to know and be able to do most of the jobs on the station, i suggest increasing captain to 30 or more
15 hours captains arent experienced enough to do every job
one can become cap and just not touch the disk

**Comment by MajManatee** [comment]
25 hrs in a department is NOT a lot. You can reach that in like 3 days of gaming. Two if you dont have a life.

**Comment by solwashere** [comment]
There are just a lot of points in time where I'll come across heads that still come across as being new and generally cause a lot of harm to a round due to incompetency and I'll look up their ckey and they'll have like 12-13 hours as paramed or whatever
This will hopefully negate that a tiny bit

**Comment by Marmio64** [comment]
> 25 hrs in a department is NOT a lot. You can reach that in like 3 days of gaming. Two if you dont have a life.

8 hours of ss13 a day is a unhealthy assumption for a server often marketed as new player friendly

**Review by Moltijoe — APPROVED** [review]
Number changes are easy

**Comment by MajManatee** [comment]
> > 25 hrs in a department is NOT a lot. You can reach that in like 3 days of gaming. Two if you dont have a life.
> 
> 8 hours of ss13 a day is a unhealthy assumption for a server often marketed as new player friendly

and yet we have players consistently hitting 13 hours or more a day

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
