### PR TITLE
adds two new sects blood and jesters

### PR DESCRIPTION
**Pull request by boodaliboo**
this is altoids code i have gotten permission to use it
adds two new sects
blood sect uses blood and organs for favor
jester uses bannana peels and bannanium 
clowns can turn people into clowns for 500 favors
if you have any ideas for rites let me know
:cl:  
rscadd: Adds two new religious sects
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
For another clown rite, 50-100 favor to get a pie?

I understand why you are going for organs and not skulls. I'm not joking when I say that the GW lawyers may come for us.
As for rites?
Redrum: Turn all the lights on the station red.
The Blood must flow: All the station scrubbers over flow blood.
DOOM: Play the DOOM song.


If you are a antag and for a high amount of favor.
Clown: Summon a HONK demon.
Blood: Summon a slaughter demon.

**Comment by boodaliboo** [comment]
all the ideas are good except slaughter demon, a summonable laughter with a limit of 1 would be cool though

**Comment by Drowzyleaf** [comment]
> DOOM: Play the DOOM song.

you gotta give em access to the entire soundtrack of Doom 1 so the chaplain becomes a blood-soaked DJ powered by death and synthesized metal

**Comment by boodaliboo** [comment]
> > DOOM: Play the DOOM song.
> 
> you gotta give em access to the entire soundtrack of Doom 1 so the chaplain becomes a blood-soaked DJ powered by death and synthesized metal

just e2m1

**Comment by Bibby0110** [comment]
Make it compile and we can talk about it

**Pull request closed without merging**
