### PR TITLE
Adds the anniversary of 24605 as a holiday

### PR DESCRIPTION
**Pull request by Bibby0110**
# General Documentation

### Intent of your Pull Request

There's already a poster, so why not a holiday, too?

Like most of the other holidays, there isn't too much to it. A drone hat (the atmos tech beret), a specific lobby song ([Johnny Cash's "Ring Of Fire"](https://www.youtube.com/watch?v=5WyLhwYFgmk), feel free to suggest more), and a new set of star-related station prefixes..

# Changelog
:cl:  
rscadd: Adds the anniversary of 24605 (August 2nd) as a holiday.  
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Honestly this meme should enter end of life, its been long enough that alot of players are starting to wonder what's that and the event isnt remarkable enough to warrant trying to tell everyone what it was about.

**Comment by Cartlord** [comment]
I'll bite, what is/was 24605?

**Comment by Bibby0110** [comment]
> I'll bite, what is/was 24605?

Atmos tech turned station into literal surface of a star

**Comment by Cartlord** [comment]
> 
> 
> > I'll bite, what is/was 24605?
> 
> Atmos tech turned station into literal surface of a star

....So they opened a fusion can?

**Pull request merged**
