### PR TITLE
Introduces Skubman, the world's worst superhero and Anti-Skubman, the world's worst villain

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

https://github.com/tgstation/tgstation/pull/51316

Skubsuit to the autodrobe
image
Pro-skubbers only

#### Changelog

:cl:  
rscadd: Adds the skubsuit
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
Who are these anti-skubbers downvoting? Skub is good, skub is life

**Comment by boodaliboo** [comment]
how did this manage to fail compiling

**Comment by patpol4** [comment]
This makes skub have a purpose, it looks great but it defies the nature of skub.

**Comment by swissloaf** [comment]
closed for now, encountered some errors while testing it

I plan to add a anti-skub and pro-skub suit too

**Pull request closed without merging**
