### PR TITLE
removes clownmutation-removal from a few antags

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Tatortottle, changelings, and cultists. Revheads keep it since they need to use their flash. 

#### Changelog

:cl:  
tweak: Clowns now keep their clumsy trait when they become an antag (except for revheads)
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Why?

**Comment by Nickvr628** [comment]
This is a shitty change

**Comment by Amelia0010** [comment]
> This is a shitty change

just use the fucking downvote button you inbred mongrel

**Comment by Ktlwjec** [comment]
can you delete this please

**Comment by Alexandria404** [comment]
Rather not.

**Comment by Amelia0010** [comment]
> Rather not.

> can you delete this please

Just use the fucking downvote button, christ

**Comment by Amelia0010** [comment]
> Why?

[19:34] Time-Green: but a traitor clown shooting himself in the dick is funny

**Comment by Kmc2000** [comment]
no

**Comment by Time-Green** [comment]
Tbh im not sure what to think. Clownmut is debilitating but there’s literally a fucking bottle of mutadone on the table in genetics.
Though I dont think many clowns know that
That and a cultist cuffing himself infront of the talisman stunned HoS is pretty funny

**Comment by ghost** [comment]
no

**Comment by simonset55** [comment]
This would bring goodod changes to jtehe srever, i upvotoe this becuase Nicgalass todl me too

**Comment by Kmc2000** [comment]
on second thought this is the best pr I, a humble mortal, have ever had the pleasure of witnessing, in my numerous years of existence

**Comment by Oakboscage** [comment]
Holy shit this is amazing

**Comment by Amelia0010** [comment]
something something upvote/downvote

**Comment by ShadowDeath6** [comment]
Doesn't make sense that changelings would have it since they can just remove it and cultists don't have anything that clumsy influences iirc so that won't change much

tbh pr not worth it since traitor clowns aren't very common and this gives even less diversity to them

**Comment by Moja10** [comment]
I don't think this is a good idea but I don't think I'll kill myself if it gets merged, but chances are I will want to kill myself after enough time with it implemented. Clowns already are clumsy with conversion antags but I've never enjoyed the fact that clowns are clumsy as an antag at all

**Comment by ThatLing** [comment]
yes

**Comment by Amelia0010** [comment]
no

**Comment by Amelia0010** [comment]
sad

**Pull request closed without merging**
