### PR TITLE
Stunbaton now discharges battery when left on

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

Stunbaton, similarly to the welder (but not constant like the welder), will now discharge battery when left on by careless sec officers

drains 500 cell or 5% on default (high capacity) cell

#### Changelog

:cl:  
tweak: Stunbaton now discharges 500 battery occasionally when left on
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
Cool, now I am not shitsec if I put a bluesapce power cell in my stunbaton now.

**Comment by boodaliboo** [comment]
this wasnt already a thing?

**Comment by yacabo** [comment]
Correct me if I'm wrong, but doesn't 13 processes = 0.65sec? That seems a bit fast

**Comment by ynot01** [comment]
> Correct me if I'm wrong, but doesn't 13 processes = 0.65sec? That seems a bit fast

a process happens approx every 2 seconds (in optimal conditions)
this means drain will happen 26 seconds after turning the baton on, and then additionally every 14 seconds thereafter until it turns off

**Comment by ynot01** [comment]
tested

**Review by fluffe9911 — APPROVED** [review]
thought it did this at first anyway when I first played

**Pull request merged**
