### PR TITLE
Adds in the Guide to Modern Toxins by Retro Junkie to the Jukebox

### PR DESCRIPTION
**Pull request by GraveHat**
https://youtu.be/SytXoE3dpCQ

The guide in question. Thanks again to Retro Junkie for letting me stick this unholy abomination in the game.

# Document the changes in your pull request

Title. I personally find this hilarious. The guide is not entirely coherent without visuals.

This has been tested and does work.

# Wiki Documentation

Added a new song to the jukebox.

# Changelog

:cl: RetroJunkie
rscadd: Adds the Guide to modern toxins to the Jukebox  
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
this isn't a song

**Comment by GraveHat** [comment]
> this isn't a song

Unfortunately.

**Comment by maxion12345** [comment]
Keep jukebox for songs. You might be better off making an "audiobook" type item that just plays the mp3. Or transcribe it into a holodisk similar to the AI construction one.

Ensure he's credited properly in the license files if you do add to the jukebox (see other jukebox pr's for info). You'll also want to compress this as much as possible due to music files taking up a rather big chunk of space

**Comment by NCRLouTenant** [comment]
Yeah, can we not have this on the Jukebox. Last thing I want is that one idiot who comes in and constantly stops the music to play a meme song now not even playing a song at all.

**Comment by cuackles** [comment]
Ok so even if this is usefull, it doesn't fit on the jukebox theme, i would recommend making another machine that allows you to hear it, something like a tape recorder perhaps

**Pull request closed without merging**
