### PR TITLE
Mechs no longer can swing swords with their feet

### PR DESCRIPTION
**Pull request by Mqiib**
Bump smash no longer uses melee weapon module attacks. I'll test this later probably.
Gygax mains BTFO

# Changelog

:cl:  

tweak: Bump smashing will no longer use melee weapon attacks for mechs.

/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Durand fanatics against the gygax being any good, they only want Durand with armor module, repair droid and Solaris.
Soon they'll come for our leg actuators then they'll give Durand even more defense and less speed, they despise speed, they just want to wield indestructible bricks that wait in a corner for people to come at them.

**Comment by ChuChu42** [comment]
why not just remove this for other mechs and keep it in mauler and durand instead?

**Comment by Mqiib** [comment]
> why not just remove this for other mechs and keep it in mauler and durand instead?

Durands dont have bump smash and the weapon maulers get doesnt override the base melee attack.

**Comment by Mqiib** [comment]
fuck you turdis it compiles fine

**Comment by JamieD1** [comment]
Something not right with this

**Pull request closed without merging**
