### PR TITLE
readds blood bros having kits

### PR DESCRIPTION
**Pull request by boodaliboo**
all of this code is originally from xoxoeyes i just added it back to the code 
this is the pr https://github.com/yogstation13/Yogstation/pull/9665/files 

but yea blood bros are like the antag you get pissed you rolled because its so boring we previously had them having kits and it made being one significantly more enjoyable

:cl:  
rscadd: Adds back them having kits
tweak: tweaked blood bros balance wise as its shit

/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
Blood brothers have sufficient tools I feel with makeshift crafting, no reason to give them 20+ tc worth of items.

**Comment by Moltijoe** [comment]
Blood brothers have sufficient tools I feel with makeshift crafting, no reason to give them 20+ tc worth of items.

**Comment by Therandomhoboo** [comment]
Blood brothers have sufficient tools I feel with makeshift crafting, no reason to give them 20+ tc worth of items.

**Comment by ynot01** [comment]
I don't really like makeshift items that much, but while kits are underutilized for traitors and this would definitely make them seen more, I don't think it's the right path.

- Blood brothers are supposed to be one antag, split into two people. Giving them kits makes them two traitors that are loyal to each-other.
- Being forced into the kit gimmick you spawn with is bad for player agency

I would rather blood brothers get like 4 telecrystals each or something, but even that could go very poorly

**Comment by Moltijoe** [comment]
> I don't really like makeshift items that much

It might be worth creating additional items for makeshift crafting

**Comment by Moltijoe** [comment]
don't even need 24 hours
sorry bood, i appreciate you coding, but this is more complicated than i think your current skills are capable of
and this doesn't seem like a feature anyone other than you wishes for

**Pull request closed without merging**
