### PR TITLE
Highers population for Shadow based TEAM antags. 26 and 3 were lings? lol

### PR DESCRIPTION
**Pull request by JamieD1**
Makes sure there are at least some crew to fight on these modes, its kinda dumb on low pop, they just steam roll

Alternative to: #17782

Closes: #17782

:cl:  
tweak: Highers pop limit for shadow antags
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
scale them with pop

**Comment by JamieD1** [comment]
> scale them with pop

Out of scope

**Comment by MajManatee** [comment]
just lower their chance smh

**Comment by ThatLing** [comment]
Balance council said this one

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
