### PR TITLE
Removes Robocop as a law set

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
I don't know if it was just forgotten or intentionally ignored.

After the removal of secborgs in an attempt to reduce the AI's valid hunting capabilities, I've taken away this law set for two reasons.

1.) Without secborgs, its nigh impossible for an AI to enforce space law. Just casing a lot of hair pulling as they flail about helplessly. Made worse with low sec.
2.) The AI should not be valid hunting at all, let alone criminals to enforce space law, which is encouraged in this law set.

You could argue "Nuh uh, you don't have to valid hunt!!! this make the AI arrest people for ANY crime!!!" 
yeah ok retart and I don't HAVE to gib you, but I WILL. And so will 95% of the player base upon seeing the law "Uphold space law"

# Wiki Documentation
No more robocop lawset

# Changelog

:cl:  
rscdel: The AI can no longer be given a law set that encourages valid hunting. Robocop is no more.
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
not much point to this considering it requires subverting an ai to do so and the only way youre doing that is if your ai is being particularly annoying, so, a punishment is fair.

**Comment by MajManatee** [comment]
it absolutely does not require subverting the AI what?

**Comment by iloveloopers** [comment]
of course, AIs will clearly just let their laws be changed for no reason

**Comment by KingSuperBOB** [comment]
Not only does this lawset never happen naturally you will have to wrangle the AI to even use this lawset no matter what roundstart lawset it is on having to fight tooth and nail to either break into upload or hope the AI doesnt see you sneaking into tech storage (which would pretty obvious if you are a command staff doing so) also Robocop can also backfire as again the laws of Robocop applies to everyone

**Comment by azzzertyy** [comment]
the SAME room has oxygenistoxic for a lawset

**Comment by Marmio64** [comment]
can't you just use free form and purge law boards to achieve this anyways

**Comment by bruhlookatthisdood** [comment]
obvious solution is to re-add sec borgs

**Comment by ToasterBiome** [comment]
we love validhunting

**Pull request closed without merging**
