### PR TITLE
Adds bluespace canisters

### PR DESCRIPTION
**Pull request by Lostlarry**
mostly copied from https://github.com/tgstation/tgstation/pull/44502
except for the sprites
image

reason trying stuff out and for all gas storing needs

balance-wise don't judge me i have no clue how to balance stuff and feel free to change the values

:cl:  
rscadd: add bluespace canisters which have higher capacity
rscadd: adds bluespace canister parts to Miniaturized Bluespace Research so it can be made
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Would like to add some input since I was the one in #development-public who was pushing to have this PR. Thanks again to LostLarry for doing the PR mirror from TG.

3000L as stated in the original PR is insufficient justification for a bluespace canister as it has very marginal benefits, except maybe pluoxium canisters on a CO2 SM. If we bump it up to something around 10000L, it could very well function as mobile emergency gas storage for rapidly repressurizing large sections of the station (or god forbid the captain buys the build your own shuttle kit). If we bump it up to 20000L or 50000L, we could use it as a ghetto burn chamber, saving the atmos tech the 10~20 minutes that he'd take setting up a new burn chamber in space.

**Comment by HomocidlePancakes** [comment]
Gee. These sprites look even worse then on OG pr

**Comment by AsV9** [comment]
god these sprites though

**Comment by Firewolf34** [comment]
Aren't those the normal sprites with a little box over them to indicate they're bluespace? Dunno what the floating stuff top right is, though.

**Comment by Lostlarry** [comment]
yes they are since i'm not a good spriter and don't want to make new canister the floating stuff in top right are parts which then construct the canister

**Comment by ThatLing** [comment]
Stale, feel free to remake/reopen the PR when you fixed the merge conflicts.

**Pull request closed without merging**
