### PR TITLE
Adds 4 Variations to bomb testing range

### PR DESCRIPTION
**Pull request by Hopekz**
**Spice!**

Capture_ingame

Variations:
-----
Regular Bomb Range

Bunker Bomb Range
image

Syndicate Bomb Range

Clown Bomb Range

#### Changelog

:cl:  Hopek
rscadd: Added 4 new variations to the bomb testing range!
/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
Fuck why didn't i think of this

**Comment by MegaEmpirical** [comment]
Is the camera being on the glass pane in the bunker one going to be a problem?

**Comment by Hopekz** [comment]
> Is the camera being on the glass pane in the bunker one going to be a problem?

It works functionally the same but nonetheless good catch. 
I want to keep everything consistent and since there are no window cameras to the best of my knowledge I will be modifying this when I get home later tonight.

**Comment by Hopekz** [comment]
The camera now moved over per Lyis's catch.
image

**Comment by Xoxeyos** [comment]
I love all these new variation changes.

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
Few things:
- I'd remove testingrange1, as it's the original and really boring, then rename the others (eg testingrange2 -> testingrange1).
- Add windows to testingrange2, this looks super ugly from space and there's no reason to remove them.
image
- Replace space areas with /area/template_noop on the yogbox map.

**Comment by Hopekz** [comment]
- Replaced original variation (rip)
- Reorganized the variations
- Added windows to bunker variation.
image


Ready for review.
----

**Comment by Hopekz** [comment]
KTL caught this but it looks like the original map didn't use the corner pieces.
Updated. It looks super pretty now!
image

**Pull request merged**
