### PR TITLE
spectral curse no longer has the holy water id as its cure text

### PR DESCRIPTION
**Pull request by boodaliboo**
fix, suprised no one has found this till recently because these infections have been in the game for years
#### Changelog

:cl:  
bugfix: fixed a few things  
/:cl:

### CODE REVIEW

**Review by redmoogle — APPROVED** [review]
Functional Boodcode? lets go. On a serious note codes good.

Also changelog.

**Comment by redmoogle** [comment]
You'll have to grab the latest code from yogstation before it compiles

**Review by patpol4 — CHANGES_REQUESTED** [review]
You're reverting the latest russian bunker PR, please get rid of this map change

**Comment by patpol4** [comment]
Reminder this one is still waiting on a map change

**Pull request closed without merging**
