### PR TITLE
i port gun kits from /tg/ except done in a way that makes sense for our codebase

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
ok heres the quick rundown:
instead of being able to hit the x10 button for guns on the armory protolathe and being able to instantly replace an entire stolen/lost armory for no effort, you now print kits instead. hit a kit with the weapon it wants and wait a few seconds, and then you get the gun that the kit drops.

stuff that's affected:
teleshield, kit requires a normal riot shield to make
aeg, kit requires a normal energy gun to make
xray laser gun, kit requires a normal laser gun to make
beam rifle, kit requires an xray laser gun to make
tesla revolver, kit requires a laser gun
decloner, kit requires a laser gun
tempgun, kit requires an energy gun
ion carbine, kit requires a laser gun
ebow, kit requires a PKA
hardlight bow, kit requires an energy gun

But why?
Currently, stealing or destroying the armory is a complete waste of time and totally irrelevant, sans the 3 shotguns. Any losses to any weapons security has are replaced in seconds with a click of a button on a machine that spawns roundstart in the armory. This PR aims to help with security officers carrying an entire armory of advanced guns (all mindshield pinned, obviously) in their backpack, which is fucking despised and with good reason. Also makes cargo arming people actually matter because unlike cargo security pulls from an essentially unlimited source, that being the ore silo which will ALWAYS have enough materials to make tons of guns unless there's no shaft miners or the silo was destroyed. And, unlike Cargo, printing guns is instantaneous instead of having to wait for the shuttle. 

firing pins and weapon charge are retained before and after putting a gun through a kit because i cant fucking stand security officers draining all of the diamonds in the ore silo to make firing pins

# Changelog

:cl:  
rscadd: added gunkits to the armory protolathe, which turn into an advanced weapon when hit with their required gun
rscdel: armory protolathes now cant make infinite guns for free, rip
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
you seem to be entirely overlooking that sec printing all those guns requires sci to research them all, which takes tens of thousands of points to get the top-level stuff

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> you seem to be entirely overlooking that sec printing all those guns requires sci to research them all, which takes tens of thousands of points to get the top-level stuff

ai law 2 research advanced energy guns

**Comment by applepineapplepizza** [comment]
> you seem to be entirely overlooking that sec printing all those guns requires sci to research them all, which takes tens of thousands of points to get the top-level stuff

just get science to make a big boom or atmos to produce gases. seems fine to me

**Comment by Hopekz** [comment]
> you seem to be entirely overlooking that sec printing all those guns requires sci to research them all, which takes tens of thousands of points to get the top-level stuff

What is even your point?

How is this a positive or negative point

**Comment by Marmio64** [comment]
Should allow the temp gun, ion carbine (ion carbine is actually pretty good for it's specific scenarios but i think antags dont need a buff for using station equipment instead of antag equipment, and borgs dont need the buff either), and tesla revolver to still be printable straight out without kits, considering that they're not very good and they have very specific case uses, and even then its usually just as good or even better to just grab a different gun. (me personally, i would never trade in a lasergun for a fuckin tesla revolver).

**Comment by 00ze-cyclone** [comment]
Just make mindshield pins an upgrade you slap on a pin instead of a free pin, that’s a more elegant option that adding another shitty system that try to do the same thing as firing pins.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> Should allow the temp gun, ion carbine (ion carbine is actually pretty good for it's specific scenarios but i think antags dont need a buff for using station equipment instead of antag equipment, and borgs dont need the buff either), and tesla revolver to still be printable straight out without kits, considering that they're not very good and they have very specific case uses, and even then its usually just as good or even better to just grab a different gun. (me personally, i would never trade in a lasergun for a fuckin tesla revolver).

eh
temp gun: instantly stops you from moving when you get shot once, winning pretty much every fight with a human in 1 click unless they have a survival pen or leporazine or something
ion carbine: backpack sized, you can carry like 10 of them to shit on mechs/borgs/anyone else with energy weapons
tesla revolver: yeah its bad but im not making a special exception for it, it already doesn't get used

**Review by KillerOrcaCora — APPROVED** [review]
In the future make sure to fill out the spriting template correctly.

**Comment by RG4ORDR** [comment]
A suggestion I gave to Gus was allowing the armory lathe the ability to print base laser guns and disablers, gunkits for the required weapons, and maybe getting some T1-4 parts to complete them.  
Egun - laser gun and disabler
Adv Egun - Egun and T3 laser, maybe a powercell and capacitor
Xray gun - Advs egun, T4 laser, maybe some Uranium.

Basically you can craft the base guns, and kits and need the parts to assemble the guns themselves. So this doesn't make arming the crew in the event of emergencies such as War Antags or Blob. But it means you can't production line PAs,Xrays, and Eguns.

**Comment by UltraBigRat** [comment]
> A suggestion I gave to Gus was allowing the armory lathe the ability to print base laser guns and disablers, gunkits for the required weapons, and maybe getting some T1-4 parts to complete them. Egun - laser gun and disabler Adv Egun - Egun and T3 laser, maybe a powercell and capacitor Xray gun - Advs egun, T4 laser, maybe some Uranium.
> 
> Basically you can craft the base guns, and kits and need the parts to assemble the guns themselves. So this doesn't make arming the crew in the event of emergencies such as War Antags or Blob. But it means you can't production line PAs,Xrays, and Eguns.

How does this prevent production lining them? Considering if you can print energy guns and  lasers, you can probably just as easily get stock parts. This just has the same effect as lightly increasing material costs which due to how mining is structured matter very little if miners are any bit active.

**Review by ReddicusDragon — APPROVED** [review]
I see no issues with this. @JamieD1 you might want to flag this for review for balance reasons

**Comment by JamieD1** [comment]
Will test merge, im on the fence to be honest.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
uh oh

**Comment by TheRyeGuyWhoWillNowDie** [comment]
ok we're good

**Comment by Hislyna** [comment]
Not a fan of them in the test merge tbh, makes it so limiting.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
The point is to be limiting, preventing infinite gun printing is the entire point of this PR. If you have a better idea, I'd love to hear it.

**Comment by Hislyna** [comment]
Security can already get shat on by most antags, especially if theyre in low numbers. They do not need a nerf to the only thing they have going for them. Make armoury fort knox if you even want to think of this

**Comment by Hislyna** [comment]
Forgot to mention, also guts ghost roles such as charlie station and free miners

**Comment by isotope436** [comment]
you cannot make kpas and i dont believe you can order them so i recommend the E-bow be changed but thats just me :) (also isnt it a illegal tech item anyways)

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> Forgot to mention, also guts ghost roles such as charlie station and free miners

but they can't even use printed guns in the first place? they don't have firing pins

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> you cannot make kpas and i dont believe you can order them so i recommend the E-bow be changed but thats just me :) (also isnt it a illegal tech item anyways)

shaft miner starter crate contains a PKA

**Comment by 00ze-cyclone** [comment]
> > Forgot to mention, also guts ghost roles such as charlie station and free miners
> 
> but they can't even use printed guns in the first place? they don't have firing pins

Charliestation has a box of firing pins

**Comment by chemistrymain2** [comment]
> > Should allow the temp gun, ion carbine (ion carbine is actually pretty good for it's specific scenarios but i think antags dont need a buff for using station equipment instead of antag equipment, and borgs dont need the buff either), and tesla revolver to still be printable straight out without kits, considering that they're not very good and they have very specific case uses, and even then its usually just as good or even better to just grab a different gun. (me personally, i would never trade in a lasergun for a fuckin tesla revolver).
> 
> eh temp gun: instantly stops you from moving when you get shot once, winning pretty much every fight with a human in 1 click unless they have a survival pen or leporazine or something ion carbine: backpack sized, you can carry like 10 of them to shit on mechs/borgs/anyone else with energy weapons tesla revolver: yeah its bad but im not making a special exception for it, it already doesn't get used

while true, most of these are niche edgecases honestly

nobody wants to trade in a fucking laser gun for a tempgun and at least SOME toys deserve to exist

**Comment by chemistrymain2** [comment]
> Security can already get shat on by most antags, especially if theyre in low numbers. They do not need a nerf to the only thing they have going for them. Make armoury fort knox if you even want to think of this

this is kind of disingenuous, honestly

this is absolutely not 'the only thing sec has going for them' and security's ability to respond to antagonists varies from round to round because, of course, regulars rolling antag means they win and regulars rolling sec means sec wins

likewise, there's no need for security to have a hyper-secure armory when in all honestly most antagonists that lay quiet long enough for sec to roll out super guns are ones that can be stopped stone cold by basic officer loadouts

you're portraying it as though it's a significant nerf to sec and totally limiting their ability to deal with antagonists when, in reality, it's _not_-the cases when security actually has time and availability to print out guns en masse from science to deal with an antagonist are more or less mutually exclusive from rounds where the antagonist is powerful enough that security _needs_ those guns/the armory has been hit

cargo exists, can order guns en masse, et cetera-this is not the only thing security has going for them and it's certainly not majorly game changing except in certain edge cases (slow boil cult, clock cult, etc) and in most of those cases you _should_ be able to hit up cargo anyway

while it's a nerf in that not everyone can carry their own private armory, that's...more or less a good thing

**Review by cuackles — APPROVED** [review]
mmmmmm box

**Pull request closed without merging**
