### PR TITLE
Adds new clown name - Altoids

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

:honk: Adds a new fun and wacky name to clowns - Altoids, After all this name is so funny, and goofy that surely some clown folk should have it as a name!

#### Changelog

:cl:  
rscadd: new thematic name to clowns, joy for all!

/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
haha what an epic and original joke that i haven't seen on tg github at all

**Comment by fluffe9911** [comment]
Its almost like this pr was made upon the author seeing that pr... nah totally as coincidence

**Comment by fluffe9911** [comment]
Also nickvr is more of a clown then altoids honk

**Comment by Amelia0010** [comment]
shit PR tbh

**Pull request closed without merging**
