### PR TITLE
Adds traction floors to the showers in Delta and Meta Medbay

### PR DESCRIPTION
**Pull request by nmajask**
# Github documenting your Pull Request

I got slipped by showers in medbay, so now I will "fix" it. In all seriousness, many of these showers are in places people commonly stand or walk on.

# Wiki Documentation

Delta and Meta medbay images will need to be updated.

# Changelog

:cl:  
tweak: added traction floors to the showers in Delta and Meta medbay
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
Yellow stripes decal being on top of yellow tiles is a bad idea. Also stacking it with the blue box decals makes it look even worse. Remove both, try to keep it in line with the one on boxstation.

**Comment by nmajask** [comment]
> Yellow stripes decal being on top of yellow tiles is a bad idea. Also stacking it with the blue box decals makes it look even worse. Remove both, try to keep it in line with the one on boxstation.

I'll make the requested changes, though I do want to say that boxstation has both of these issues too.

**Comment by patpol4** [comment]
> > Yellow stripes decal being on top of yellow tiles is a bad idea. Also stacking it with the blue box decals makes it look even worse. Remove both, try to keep it in line with the one on boxstation.
> 
> I'll make the requested changes, though I do want to say that boxstation has both of these issues too.

oh

**Review by patpol4 — APPROVED** [review]
Got to fix the issue on box some day, will put it on the list

**Comment by nmajask** [comment]
> Got to fix the issue on box some day, will put it on the list

Ill do that in a sec

**Pull request merged**
