### PR TITLE
Adds Partheo's amazing artwork to the title screen

### PR DESCRIPTION
**Pull request by Hopekz**
**YES; I know this only effects the github build as the real server title screens are on the host**

Credit to @Partheo for the artwork.

**What I did:**
- Upscaled it from 256 x 256 to 480 x 480 (with no loss from what I can tell)
- Added it in addition to our dumb Yogscast April fools title screen so that one isn't "removed" for anyone that wants it.

EDIT:
Partheo created a 480 x 480 version of his artwork making my upscale obsolete

Original:
------
moja

Partheo created a 480 x 480 version of his artwork! 
------

**Now it's super amazing and also there is a build-up to Moja showing up so it's more spooky and awesome!** (about 60 seconds)

mojabig

My Upscaled gif (obsolete thanks for Partheo's contribution)
-------

moja-export

It looks really nice in-game. 
It would be awesome if we considered it for rotation but I am fully aware it is only for this github build.

dreamseeker_WV0jT0tkCL

#### Changelog

:cl:  Partheo , Hopek
rscadd: Adds Partheo's amazing artwork to the title screen
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
i just noticed now, in the gif moja has two left hands

**Comment by Hopekz** [comment]
> i just noticed now, in the gif moja has two left hands

I think this is intentional. He has weird body parts to add to the spooky vibe

**Comment by Hopekz** [comment]
Partheo created a 480 x 480 version of his artwork! 
------

**Now it's super amazing and also there is a build-up to Moja showing up so it's more spooky and awesome!** (about 60seconds)

mojabig

**Comment by Tipy1802** [comment]
It's not a bad tittle screen or anything but it doesn't really fit the game. Looks like it belongs to a horror game.

**Comment by boodaliboo** [comment]
thats what moja looks like i imagined him as a insane old man

**Review by JamieD1 — APPROVED** [review]
Better then YogurtStation.

**Comment by MegaEmpirical** [comment]
Fuck yeah.

**Comment by Readystorm546** [comment]
Love it but it should say yogstation somewhere no?

**Comment by alexkar598** [comment]
Added to server files.

**Pull request closed without merging**
