### PR TITLE
adds rain on brick to the jukebox

### PR DESCRIPTION
**Pull request by thorium90cent**
adds https://www.youtube.com/watch?v=-9s63ZNKSzg to the jukebox 
i'll be completely honest, i did not test this
this is also my first pr 
i have no idea what i am doing

# Changelog

:cl:  
rscadd: rain on brick from katana zero is now apart of the jukebox
/:cl:

### CODE REVIEW

**Comment by thorium90cent** [comment]
how do i add a changelog

**Review by Moltijoe — CHANGES_REQUESTED** [review]
changelog and please include a link to the song

**Comment by thorium90cent** [comment]
> changelog and please include a link to the song

i do not know how to add a changelog and where do i add the song link
figured out where the link should be 
confused about the changelog still

**Comment by Moltijoe** [comment]
> > changelog and please include a link to the song
> 
> i do not know how to add a changelog and where do i add the song link figured out where the link should be confused about the changelog still

You ended up deleting the parts for changelog
just put stuff between this
:cl:
/:cl:

and just put the link literally anywhere in the pr description

**Comment by thorium90cent** [comment]
> > > changelog and please include a link to the song
> > 
> > 
> > i do not know how to add a changelog and where do i add the song link figured out where the link should be confused about the changelog still
> 
> You ended up deleting the parts for changelog just put stuff between this 🆑 /:cl:
> 
> and just put the link literally anywhere in the pr description

done

**Comment by Moltijoe** [comment]
i suppose that's on me for not saying it, changelog stuff needs to be prefaced with various things
i think in this case it's 
soundadd: 
or something

**Comment by thorium90cent** [comment]
> i suppose that's on me for not saying it, changelog stuff needs to be prefaced with various things i think in this case it's soundadd: or something

done

**Review by thorium90cent — COMMENTED** [review]
nothing was changed just details like a proper changelog

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
