### PR TITLE
Plumbing

### PR DESCRIPTION
**Pull request by YouCanBeBetterThanThat**
# Document the changes in your pull request

image

# Wiki Documentation

All of plumbing, steal from TG wiki?
https://tgstation13.org/wiki/Plumbing

# Changelog

:cl: TG's busy bees
rscadd: Plumbing is now actually in the game
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
Automated chemistry bad

**Comment by ToasterBiome** [comment]
> Automated chemistry bad

for once theos is right

**Comment by YouCanBeBetterThanThat** [comment]
Can you explain why?

**Comment by ilikesaying** [comment]
Chemistry mains on their way to take 10 minutes to set up an omnifactory that prints out meds for every type of damage except cellular so they can produce drugs and meth willy nilly
also funny phlogiston reaction for infinite automated plasma-gas generation

**Comment by ToasterBiome** [comment]
> Can you explain why?

Powerful chems are gatekeeped by being both a bitch to make in both of knowledge and time spent, with time spent proportional to how many units you get. This keeps a nice balance of powerful chemicals existing but not being able to make 1000 powergame chemicals in a round.
This eliminates the time spent part besides the initial setup. Functionally, this would be as if an atmospheric technician set up a hydrogen setup but it actually made 4000 morbillion units of Pentetic Acid (something much more useful) instead.

We even removed the recipe saving that TG has (where it saves what buttons you press for easy making of complex chemicals).

**Comment by ghost** [comment]
We definitely need it, at least to make cytology compatible and port it

**Comment by Moja10** [comment]
Adding plumbing AFAIK also came with 2 morbillion chem nerfs, because it is a very dramatic change to go from the average skilled chemist making 300 units of chems, to 3000. I think Yogs would prefer to have stronger but more limited chems than weaker but 300,000 gallons of them. If somehow we could keep chemistry balance where things are relatively and still having plumbing somehow, that would be neat. Perhaps ... T5... Parts.... Yoggers...?

**Comment by YouCanBeBetterThanThat** [comment]
> > Can you explain why?
> 
> Powerful chems are gatekeeped by being both a bitch to make in both of knowledge and time spent, with time spent proportional to how many units you get. This keeps a nice balance of powerful chemicals existing but not being able to make 1000 powergame chemicals in a round. This eliminates the time spent part besides the initial setup. Functionally, this would be as if an atmospheric technician set up a hydrogen setup but it actually made 4000 morbillion units of Pentetic Acid (something much more useful) instead.
> 
> We even removed the recipe saving that TG has (where it saves what buttons you press for easy making of complex chemicals).

Chems are quite easy to make. Except those that require chems from outside the dispenser. All this does is remove the boring stuff of chemistry (pressing the same button over and over) and keep the exciting stuff.

**Comment by Moja10** [comment]
Also correct me if i'm wrong, but it doesn't seem that you've ported the plumbing room, so Chemists don't exactly have a spot to build a plumbing setup. Good luck fitting that 14x14 or whatever sized room on any station lmoa 

Maybe this is actually a good compromise? Plumbing is added, but they don't get the sandbox room and have to make it somewhere else, like construction. Could limit the power of plumbing with our stronger than /tg/ chems.

**Comment by maxion12345** [comment]
Factorio chem fun. More interesting to choomists.
However, automated chem factory does take a lot of the interaction from medbay. This is good on chaotic rounds when medbay is swarmed with dead and dying, or bad on slow rounds when the doctors are hanging themselves in the storage area because they haven't had to treat a single crew member in 45 minutes straight

I'd be interested in a testmerge at the least just to see what sort of bullshit the chemists will do. It'll probably be funny.

**Comment by SomeguyManperson** [comment]
there's no "exciting" part of chemistry it's all buttons

**Comment by JamieD1** [comment]
Unfortunately this has been a hot topic for a while amongst the players, staff and devs and we do not wish for plumbing as of right now, perhaps in the future and im grateful for your time on the PR. But it's just not a good fit for yogs.

**Pull request closed without merging**
