### PR TITLE
Some ion laws changes

### PR DESCRIPTION
**Pull request by patpol4**
### Intent of your Pull Request
Got inspired to change some of ours by this: https://github.com/BeeStation/BeeStation-Hornet/pull/3124

Some got reworded a bit, added some new things and places, removed some silly ones like "certain roguish charm", replaced the "other laws" category with just specific worded laws:
Code_YL27Y6ZT81

See file changes for a full list of the file changes

### Why is this good for the game?
It's fixes, clarifications, and improvements

#### Changelog

:cl:   
tweak: some ion laws changes
/:cl:

### CODE REVIEW

**Comment by Nechronom** [comment]
how about we remove all except "All are to be verbally abused at all times"

**Comment by athena413** [comment]
KEEP IT CLEAN

**Comment by boba247** [comment]
The "Do harm" ion law seems like it would lead to plasma flooding, as a non-antag.

**Comment by Hopekz** [comment]
> The "Do harm" ion law seems like it would lead to plasma flooding, as a non-antag. 

To the best of my knowledge Ion laws allow antagonistic action.

**Comment by patpol4** [comment]
> The "Do harm" ion law seems like it would lead to plasma flooding, as a non-antag. 

There's a really low chance to roll it and I'm pretty sure ion laws let you do this if they're this direct in their wording

**Comment by boba247** [comment]
Yea it wouldn't be against the rules to follow that law but seems like a low RP ion law. Any round that law does get rolled could ruin the round just because the AI got an "everyone valid" ion law randomly.

**Pull request merged**
