### PR TITLE
Adds russian beepsky

### PR DESCRIPTION
**Pull request by monster860**
heres what it sounds like:

https://cdn.discordapp.com/attachments/134720091576205312/711868167433093120/insult.ogg

:cl: monster860
add: Beepsky now has a 5% chance of being imported from Russia
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
wait this means beepsky breaks rule 0.6, meaning we need to ban beepsky

**Comment by Bibby0110** [comment]
nooooo

**Comment by Marmio64** [comment]
is this just a 5% chance to happen every time a insult is played or is it a 5% chance for beepsky to always use this instead of the normal one

**Comment by monster860** [comment]
5% chance of beepsky being russian when spawned, and then always using the russian lines

**Comment by Hopekz** [comment]
Beepsky seems more German to me but then again HoS has the whole soviet thing going on.

**Review by Hopekz — APPROVED** [review]

**Pull request merged**
