### PR TITLE
LOTS OF DEMODULAIZATION

### PR DESCRIPTION
**Pull request by Readystorm546**
I like code that looks good
This relates to #8213 just had to do somethings and ended up making a new PR

This PR is done. It has a merge conflict so its ready to be merged but ill need to make a PR after this to fix it.

:cl:  
tweak: tweaked a "few" files around to make them all in the main folder.  All thats left in the yogs folder is "Code" and "Icons"
/:cl:

### CODE REVIEW

**Comment by Altoids1** [comment]
Whenever we have to rebase again, this is going to bite the poor fuck who has to do it in the ass.

**Comment by fluffe9911** [comment]
what the heck is wrong with people that they feel obligated to demodulurize everything

**Comment by Readystorm546** [comment]
Imagine
needing to rebase

**Comment by Readystorm546** [comment]
> Whenever we have to rebase again, this is going to bite the poor fuck who has to do it in the ass.

Your the one who said we should stop...

**Comment by Readystorm546** [comment]
hah hah merge go brrrrrrrr.

On a serious note this can be merged. Then ill make a tiny PR after that would fix an otherwise merge conflict.

**Comment by Xoxeyos** [comment]
Could you possibly fix the goon stair textures also?

**Comment by ThatLing** [comment]
A lot of effort for no real value

**Comment by alexkar598** [comment]
Theres no real reason to shuffle sound and icon files around, code files I can see why but moving sounds and icons feels like moving stuff for the sake of moving stuff. I appreciate the effort that went into this but I cant really find a reason to merge this

**Pull request closed without merging**
