### PR TITLE
Moved AI Sat over 1 tile

### PR DESCRIPTION
**Pull request by Ethan4303**
# Document the changes in your pull request

Shifted the entire AI Minisat over one tile to the right for five tiles of extra space in between the Minisat and Turbine

# Wiki Documentation

nope

# Changelog

:cl:  
tweak: Moved AI core one tile to the right 
/:cl:

unknown

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Why though

**Comment by Ethan4303** [comment]
> Why though

Adds 5 extra tiles of space between the Ai Minisat and the Turbine room

**Comment by patpol4** [comment]
Ok but why do you want 5 tiles of extra space, why is that good for the game?

**Comment by Ethan4303** [comment]
A little extra space there for Atmospheric Technichians to add things if they need or could expand the room when needed.

**Comment by Cartlord** [comment]
More room for space-based heat exchange pipes

**Review by patpol4 — CHANGES_REQUESTED** [review]
1. I don't think this was supposed to be here
image

2.
Undocumented change, this can stay but please remove the lattices under the catwalks
image

Other than this i can't find any real issues, good job.

**Comment by patpol4** [comment]
Also remember to mention which station are you editing in the changelog

**Comment by Ethan4303** [comment]
Fixed those issues, and ill make sure to mention all changes and the map i used next time i make a map change

**Review by patpol4 — APPROVED** [review]
Looks like everything checks out, thank you for your first contribution.

**Pull request merged**
