### PR TITLE
Fixes a incorrectly coloured and unnamed pipe and manifold in meta station atmos

### PR DESCRIPTION
**Pull request by Annoying-plant**
# Document the changes in your pull request

Changes a pipe and manifold leading to waste on mix loop to the correct type in meta station atmos 

# Changelog

:cl:  
tweak: Changes  a pipe and manifold to the correct one in meta station atmos
/:cl:

> Also we don't mapedit pipes like this. Use the available ones that are coded in.

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Which map? reflect it in the PR and changelog.

**Comment by ToasterBiome** [comment]
Also we don't mapedit pipes like this. Use the available ones that are coded in.

**Comment by Annoying-plant** [comment]
ahhh okay will do ill update it now

**Comment by Annoying-plant** [comment]
> Also we don't mapedit pipes like this. Use the available ones that are coded in.

ahh yeah I see what you mean that should all be good now

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
