### PR TITLE
Lizard Buff: You can now defib "no activity in patient's brain"

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

no longer need to do snowflake revival surgery because someone disconnected or something

# Changelog

:cl:  
tweak: Defibrillation now works even if it can't grab a ghost
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
how is this a lizard buff?

**Comment by MajManatee** [comment]
yeah im lost on that too.

**Comment by ynot01** [comment]
You must choose, lizard mains. Succumb to your stereotypes, or reject the medbay buff.

**Review by Moltijoe — APPROVED** [review]
code works

**Pull request merged**
