### PR TITLE
[PORT] Ports light turn-on delay and sound effects + roundstart lights off from bee

### PR DESCRIPTION
**Pull request by Moltijoe**
Ports 
https://github.com/BeeStation/BeeStation-Hornet/pull/9246
https://github.com/BeeStation/BeeStation-Hornet/pull/9483
https://github.com/BeeStation/BeeStation-Hornet/pull/9500
https://github.com/BeeStation/BeeStation-Hornet/pull/9546

# Why is this good for the game?
Adds to the ambience of the game, lighting is always nice

# Testing
https://github.com/yogstation13/Yogstation/assets/108117184/c0eab3e0-ee3c-44be-923e-0cd7e552a642

# Wiki Documentation
Shouldn't need anything

:cl:  Apogee-dev, Azarak, CydiaLamiales, PestoVerde322, BriggsIDP, Absolucy, Molti
add: Added a random 1-3 second delay to lights turning on, plus a sound
soundadd: added a sound for light fixtures being turned on
add: Added a station-wide light flicker after a powerful explosion or worldbreaker stomp
tweak: Made unstaffed departments start off with their lights turned off
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
not sure how i feel about a delay, whats the reason for this?
the light switch in my house doesnt take 1-3 seconds to turn on, it turns on the second i flip it

**Comment by Moltijoe** [comment]
> not sure how i feel about a delay, whats the reason for this? the light switch in my house doesnt take 1-3 seconds to turn on, it turns on the second i flip it

these are old flourescent lights that the station uses for some reason, they have a delay

**Review by alexkar598 — APPROVED** [review]
my codeownerr is irrelevant

**Comment by neeshacark** [comment]
podpeople when they start in the dark

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
