### PR TITLE
Fix meteor lag

### PR DESCRIPTION
**Pull request by YouCanBeBetterThanThat**
# Document the changes in your pull request
Should fix meteor lag. Tested working on local.
Closes #14023
# Changelog
:cl:  
bugfix: Meteors are less laggy.
/:cl:

### CODE REVIEW

**Comment by YouCanBeBetterThanThat** [comment]
Please test merge before merging

**Comment by JamieD1** [comment]
Isnt this just a half ass port of the massive pr linked earlier from tg?

**Comment by YouCanBeBetterThanThat** [comment]
It's an alternate solution and what was recommended by oranges (when he attempted to move it to the throw subsystem). I do not have time to move all walk procs to a movement manager subsystem so this is the simplest solution I can do. Perhaps when I have enough time

**Comment by JamieD1** [comment]
Fixed in : https://github.com/yogstation13/Yogstation/pull/14144

**Pull request closed without merging**
