### PR TITLE
Removes flashes from borgs, giving all borgs an instant stun is op

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Removes flash from all borgs, as giving all borgs an instant stun is op.

# Wiki Documentation

Remove flash from all modules

# Changelog

:cl:  
rscdel: Removed flash from all borgs
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
damn, even the syndi cyborgs...

**Comment by adamsong** [comment]
> damn, even the syndi cyborgs...

The consensus seems to be that borgs having stuns is op, so I remove stuns from borgs

**Comment by cowbot92** [comment]
Perhaps adding them to the illegal-modules would be better?

**Comment by adamsong** [comment]
> Perhaps adding them to the illegal-modules would be better?

No

**Comment by jc-denthead** [comment]
I'd recommend nerfing flashes alltogether, this doesn't really fix the problem of flashes being an instant stun.

**Pull request closed without merging**
