### PR TITLE
Removes corn syrup from catsip

### PR DESCRIPTION
**Pull request by ReddicusDragon**
# Document the changes in your pull request
Catsip no longer requires corn syrup
# Wiki Documentation
Catsip no longer uses corn syrup in the recipe
# Changelog

:cl:  
tweak: makes catsip healthy by removing corn syrup 
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
thinly veild felinid buff smh

**Comment by Hislyna** [comment]
> thinly veild felinid buff smh

It doesnt heal felinids anymore, thus it should be easier to make (or it should heal again)

**Comment by SomeguyManperson** [comment]
Are you trying to get Codebase Sterilization 2 (The Second One) with guest star the :-1: button
Because this is how you get Codebase Sterilization 2 (The Second One) with guest star the :-1: button

**Review by Moltijoe — APPROVED** [review]
code works

**Pull request merged**
