### PR TITLE
Adds a new melee-focused exosuit: The Sidewinder!

### PR DESCRIPTION
**Pull request by Mqiib**
# Document the changes in your pull request

Adds a new mech called the "Sidewinder." Its stats are as follows (compared to gygax in parentheses)
Max Integrity: 200 (gygax 250)
Armor: MELEE = 40, BULLET = 20, LASER = 20, ENERGY = 15, BOMB = 40, BIO = 100, RAD = 75, FIRE = 100, ACID = 100
(gygax MELEE = 25, BULLET = 20, LASER = 30, ENERGY = 15, BOMB = 0, BIO = 100, RAD = 40, FIRE = 100, ACID = 100)
step_in/move speed: 2.5 (gygax 3, odysseus 2)
Base melee force: 15 (gygax 25)
Melee cooldown: 0.7 seconds (gygax 1.0 s)
Internal damage threshold: 25 (gygax 35) (% hp at which internal damage can occur)
Deflect chance: 10% (gygax 5%)

**Special:**
- Omni-directional attacks! Standing behind this mech is not safe, as it can quickly twist around to smack you in the back of the face!
- Turn on a dime! Clicking will immediately rotate the mech to face the click direction. This is temporarily disabled by EMPs, allowing you to pump it full of lead when you want it dead.
- No guns! This mech is unable to mount ranged weaponry, but melee weapons and other tools are still fair game. Keep your distance if you can!

- [x] Add primary mech sprites
- [x] sidewinder.dm
- [ ] Add construction sprites/parts
- [ ] Background allowable weapon tweaks
- [ ] Stop my local servers from imploding (again)
- [x] Internal screaming
- [ ] Tech nodes n stuff
- [ ] Add mech part/board designs
- [ ] Make sure it works
- [ ] Make sure it works _as intended_

# Spriting

Normal:
image

Open:
image

Thank you to @cuackles doe these lovely sprites!
Construction/individual part sprites coming soon!

# Wiki Documentation

Equipment slots: 3

Movement speed: Fast

Special properties: Omni-directional attacks, can turn instantly via clicking rather than having to move, and can only mount melee weapons

Armor:  40 melee, 20 bullet, 20 laser, 15 energy, 40 bomb, 75 rad. 25.000°K max temperature.

Integrity: 200

Description: A squat, nimble, and rather confining exosuit taking advantage of advanced synthetic muscles to move around. Originally used for entertainment in mech "sports", many have found it to be well-suited for more practical applications.

# Changelog

:cl:  Mqiib, Cuackles
rscadd: Adds the new Sidewinder mech, for those mech-sword-fighting enthusiasts!
tweak: Code changes to how mechs check for allowed weapon modules, no gameplay impact (WIP)
imageadd: Sprites for the new mech
experimental: Will need number tweaks to make sure it isn't busted
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
it looks like a salamander

**Comment by MajManatee** [comment]
crab mech crab mech crab mech

**Comment by Xoxeyos** [comment]
https://youtu.be/oGdhBOvpZiI?t=10

**Comment by ynot01** [comment]
i think new players are going to look at this and not realize it's a mech wmd

**Comment by Mqiib** [comment]
> i think new players are going to look at this and not realize it's a mech wmd

well it'll sound like a mech and move like a mech and play like a mech soooooooooo

**Comment by Mqiib** [comment]
> https://youtu.be/oGdhBOvpZiI?t=10

I'm going to vomit out the crappy lore I wrote for this mech because this video is spot-on:

Originally designed as a sort of entertainment mech for gladiatorial mech combat, the Sidewinder has been found to be quite a versatile mech. From its first introduction as a "nimble, fast-hitting exosuit perfect for robotic sports" people have been finding all kinds of other applications for it. Its dexterous nature on account of the relatively thin plating mounted over its high-strength artificial muscle fibers make it a natural fit for complex work on heavy machinery. The light armor plating has also been found to be very useful in expedition-type missions that require a working mech that can also weather harsh conditions of a hostile planet for short durations. Despite the apparent versatility of the Sidewinder, it still shines as a remarkably effective melee combatant, almost as nimble as the pilot within but with far greater strength. However, it sorely lacks in terms of ranged effectiveness. The frame itself has a tendency to twitch due to it taking in very small inputs by the pilot, resulting in significantly decreased accuracy with ranged weapons as well as having difficulty withstanding the high recoil of such large ballistic weapons. On top of that, its more compact, high-efficiency power core has difficulty supporting most energy weapons due to an emphasis on low power draw and high resistance to impacts rather than raw power output.
Notably, its shorter stature, tendency to twist and turn rapidly from small inputs, and imperfect and often uncomfortable cockpit shape has caused it to be nicknamed the "backbreaker" by some more experienced pilots, often blaming chronic back pain on their extended use of the suit.

**Comment by Moltijoe** [comment]
image

**Comment by KillerOrcaCora** [comment]
image

**Comment by UltraBigRat** [comment]
scrungled little mecha crab-fu master, i like it.

**Comment by Burger1998** [comment]
Will this be banished to red alert only like 50% of the mechs?

**Comment by Mqiib** [comment]
> Will this be banished to red alert only like 50% of the mechs?

it is a combat mech

**Comment by Marmio64** [comment]
All the other combat mechs look intimidating while this looks like a silly crab frog that you really wouldn't expect to kick your ass, not very sure on the sprite.

**Comment by Mqiib** [comment]
> All the other combat mechs look intimidating while this looks like a silly crab frog that you really wouldn't expect to kick your ass, not very sure on the sprite.

Take sprite complaints/suggestions to @cuackles

**Comment by cuackles** [comment]
> All the other combat mechs look intimidating while this looks like a silly crab frog that you really wouldn't expect to kick your ass, not very sure on the sprite.

dunno man i like frogs and i like crabs, also i had kaijus in the head while making it so thats why it looks like that

**Comment by KillerOrcaCora** [comment]
Sprite will be worked on more by the both of us when this PR is off draft.

**Comment by Simplehorror** [comment]
why don't you take the opportunity to make a mech that isnt 64x64

**Comment by Moltijoe** [comment]
WUH?

**Pull request closed without merging**
