### PR TITLE
Adds the pool shuttle

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

You can now pay CC a small fee of 15000 credits to install a swimming pool on your escape shuttle!

You can purchase this shuttle by buying the "Pool Party!" Escape shuttle.

This PR has been tested.

image

image

# Wiki Documentation

Add this to the wiki page

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: adds the pool party shuttle, available for purchase
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
It be cool if someone hijacks the shuttle the floor becomes wet, but that maybe other RP.

**Comment by N3D6** [comment]
> It be cool if someone hijacks the shuttle the floor becomes wet, but that maybe other RP.

That would be pretty cool but i don't know how to code for shit

**Comment by Marmio64** [comment]
Honestly think it'd be better if you made the shuttle a tad bit bigger (2 tiles wider?) to compensate for lost walking space. It'd also be nice to remove the windows in the medbay and readd the lockers there so people can lay low if they'd like.

**Comment by NCRLouTenant** [comment]
I know I made a mass drowning joke on discord but I'd almost prefer most of the shuttle to be a pool.

**Comment by N3D6** [comment]
> I know I made a mass drowning joke on discord but I'd almost prefer most of the shuttle to be a pool.

Maybe in the future i'll look into doing something as funny as that. I don't really know how to map shuttles, this one was really a copy of the box shuttle that i made funny

**Comment by maxion12345** [comment]
> I know I made a mass drowning joke on discord but I'd almost prefer most of the shuttle to be a pool.

gotta keep it somewhat pool-less so felinid mains don't shit and piss themselves

also firelocks for pool edge when

**Comment by N3D6** [comment]
> > I know I made a mass drowning joke on discord but I'd almost prefer most of the shuttle to be a pool.
> 
> gotta keep it somewhat pool-less so felinid mains don't shit and piss themselves
> 
> also firelocks for pool edge when

tomorrow if I remember

**Comment by neeshacark** [comment]
you need to add holodeck pools.

if someone turns off the holodeck pool while you are in it you lose your legs

**Comment by N3D6** [comment]
> > I know I made a mass drowning joke on discord but I'd almost prefer most of the shuttle to be a pool.
> 
> gotta keep it somewhat pool-less so felinid mains don't shit and piss themselves
> 
> also firelocks for pool edge when

done

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
