### PR TITLE
[s] [admin] stand proud button

### PR DESCRIPTION
**Pull request by ynot01**
for event

can only be toggled in-lobby

post-spawn, half of the players are dusted and turned into randomly generated stands for the other half

:cl:
tweak: Stand arrows now have a 15% chance to roll ranged
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
based

**Comment by Bibby0110** [comment]
Event over

**Comment by MajManatee** [comment]
what event

**Comment by ynot01** [comment]
I do not see any test-merge logs that would indicate that this event had already run

This was also intended to be merged as an addition to the secrets panel, not test-merged

**Comment by MajManatee** [comment]
id love to see this fully added

**Comment by ChuChu42** [comment]
STANDO POWA

**Comment by Yogbot-13** [comment]
#### Test Merge Deployed

##### Server Instance
main

##### Merged By
ynot01

##### Revision
Origin: 8099eac2e52331348d5183acdfe9c29aadbd1923
Pull Request: 75241d1e7043123151f6e4d519afd7253fc6ba4c
Server: cbeb05db94a50bb88ebd4f531d60e5b951251b1c

##### Comment
Event try no 2
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
ynot01

##### Revision
Origin: 14108b6563f966e94e255e7aba4c44859c7f4a9a
Pull Request: 75241d1e7043123151f6e4d519afd7253fc6ba4c
Server: a46a232c50afb2e80a0807f62a80a74320ef8e05

##### Comment
Event try no 2
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Removed

**Pull request closed without merging**
