### PR TITLE
[PR NECROMANCY] Adds a new purrbation option for donors: fox

### PR DESCRIPTION
**Pull request by Moltijoe**
original pr in question: https://github.com/yogstation13/Yogstation/pull/16644
was only closed last time because jamie was being weird about it and orca was being orca

# Why is this good for the game?
More donator options
They're basically just reskinned felinids which are reskinned humans

# Testing & Spriting
image

:cl:  theos and molti for code, orca for sprites
rscadd: adds fox tails and ears
rscadd: fox purrbation selection for donors
imageadd: fox parts
/:cl:

### CODE REVIEW

**Comment by teh4565** [comment]
UH OH

**Review by Mqiib — APPROVED** [review]
image

"ear sinner"

Also SPEED APPROVAL WE NEED THIS NOW TO SAVE YOGS

**Comment by SomeguyManperson** [comment]
Five. Hundred. Merge branch 'master' of https://github.com/yogstation13/Yogstation

**Comment by PibeCantina** [comment]
The day hath cometh

**Comment by cowbot92** [comment]
HA approved

**Comment by LazennG** [comment]
incredible

**Review by ToasterBiome — APPROVED** [review]
smashing approve so fast i accidentally ran checks again

**Review by cuackles — APPROVED** [review]
you know i think this pr doesnt have enogh art aprovals so here goes one more

**Comment by N3D6** [comment]
hopefully this doesn’t get hard blocked for literally no reason at all this time

**Comment by Cartlord** [comment]
jamie was right

**Pull request merged**
