### PR TITLE
Revert "[admin] More admin only ghost spawners!"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#4595

Bloat

### CODE REVIEW

**Comment by MajManatee** [comment]
Terrible reasoning

**Comment by Bibby0110** [comment]
> Terrible reasoning

No

**Comment by Addust** [comment]
if they're bloat then make maps for them instead of just deleting them you useless fuck

**Comment by Addust** [comment]
you may have made them but you cannot take them out of this world

**Comment by Moja10** [comment]
fuck no, I am very happy to learn of this features existence

**Comment by Bibby0110** [comment]
> fuck no, I am very happy to learn of this features existence

What feature??

**Comment by Bibby0110** [comment]
> if they're bloat then make maps for them instead of just deleting them you useless fuck

readd them when you make maps for them

**Comment by Moja10** [comment]
> > fuck no, I am very happy to learn of this features existence
> 
> What feature??

admin ghost spawners. I was literally gonna bounty the assistant spawner until I noticed you had already added it

**Comment by MajManatee** [comment]
Improve dont remove

**Comment by Bibby0110** [comment]
> > > fuck no, I am very happy to learn of this features existence
> > 
> > 
> > What feature??
> 
> admin ghost spawners. I was literally gonna bounty the assistant spawner until I noticed you had already added it

there isn't an assistant spawner

**Comment by Bibby0110** [comment]
purgatory

**Pull request closed without merging**
