### PR TITLE
New polysmorph and lizard options

### PR DESCRIPTION
**Pull request by Mqiib**
Adds several now bits and bobs for lizards and polysmorphs. Also tweaks dorsal tubes to look better and fixes an errant spelling mistake I caught.

Lizards: tiny horns, long horns, full frills, and long frills.
Polysmorphs: hunter dome, drone dome, and double dorsal tubes

Why am I doing work on a race that may never see the light of day? I don't even know! Anyways here are some pictures.

image
image
image
image
And the tiny horns are self-explanatory.

#### Changelog

:cl:  
rscadd: New customization options for lizards and polysmorphs!
imageadd: Plus sprites by yours truly!
spellcheck: Angeler -> Angler
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
Still only obtainable through magic mirror, correct?

**Comment by Mqiib** [comment]
Forgot to put in a picture of the long frills. Will get to it shortly,

**Comment by Mqiib** [comment]
> Still only obtainable through magic mirror, correct?

Yes polysmorphs are still not a roundstart race and you can't even customize them yet, so me adding these parts doesn't actually do anything.

**Comment by Mqiib** [comment]
image
image
image

Long frills

**Review by Partheo — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
