### PR TITLE
Adds 8 different variations to the Custodial closet

### PR DESCRIPTION
**Pull request by Hopekz**
Variety is the spice of life!

**Edit:**
------
Now looking at this I agree that these variations are terrible.
I made these while learning how to use the new mapping tool.

This project is on WIP as a re-creation of all of these are in order if I want to be satisfied with 
getting this merged.
I am not happy with how this project looks at the moment with my current mapping ability.

Variations:
-----

image

#### Changelog

:cl:  
rscadd: Added 8 different variations of the Custodial closet. Wow!
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Wut

image

**Comment by deathslayer2481** [comment]
But wai tho

**Comment by alexkar598** [comment]
Unless looking side by side and tracking objects, I can't see a difference so this is wasted computing power and making mapping harder for all I care

**Comment by MegaEmpirical** [comment]
Get rid of the vendrobe and you have my vote.

**Comment by Hopekz** [comment]
Putting more spicy into these.. Stand by!

**Comment by alexkar598** [comment]
Lyis, fuck off with telling people to violate contribution rules, this PR will not be merged if it includes removing the vendors as it goes against the atomization rule

**Comment by MegaEmpirical** [comment]
I have no idea what you're talking about Alex but you and your attitude can fuck off.

And since my previous comment was marked off topic whilst being on topic: I still say do away with the vendrobes.

**Comment by Ktlwjec1** [comment]
I'm agreeing with Alex the more I look at this, not enough difference for template usage even though it's nice. I'll leave this open since it's got the work in progress label but close it if you don't plan on changing anything else.

**Comment by Hopekz** [comment]
Now looking at this I agree that these variations are terrible.
I made these while learning how to use the new mapping tool.

This project is on WIP as a re-creation of all of these are in order if I want to be satisfied with 
getting this merged.
I am not happy with how this project looks at the moment with my current mapping ability.

**Pull request closed without merging**
