### PR TITLE
[s]removes syndicate tech from flashlight

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

Removes syndicate tech from flashlight
#### Changelog

:cl:    
bugfix: Removes syndicate tech from flashlight  

/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
it was right on the first commit

**Review by Altoids1 — DISMISSED** [review]
It was right on the first commit.

**Comment by ghost** [comment]
happy?

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
You saw nothing

**Review by 1fbff5f83b23d39d38b1dfcb4cac8d9b — APPROVED** [review]

**Pull request merged**
