### PR TITLE
Gives the fucking syndicate agent card access to ORM

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Gives the fucking syndicate agent card access to ORM

# Why is this good for the game?
self explanatory
image

# Testing
YES I CAN ACCESS TO ORM NOW!!!

# Changelog

:cl:  
 
tweak: Gives the fucking syndicate agent card access to ORM
/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
why da hell does a comms base even have an ORM

**Comment by ShoziOffical** [comment]
> why da hell does a comms base even have an ORM

Not comms, it's syndie/jungle base

**Comment by AMyriad** [comment]
> Not comms, it's syndie/jungle base

yea they're there to spy on NT, not mine lol

**Comment by N3D6** [comment]
> > Not comms, it's syndie/jungle base
> 
> yea they're there to spy on NT
Uhhh well you see it’s my favorite ghost role and I need free respawns

**Review by Moltijoe — APPROVED** [review]

**Comment by LassiH** [comment]
> > Not comms, it's syndie/jungle base
> 
> yea they're there to spy on NT, not mine lol

they have the unlimited ore tiles that perma has so they can mine without leaving base

**Pull request merged**
