### PR TITLE
[GAX] She Russian on my Revolver

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

[Extremely Loud Incorrect Buzzer]

image

# Changelog

:cl:  
mapping: Adds a russian revolver to the NVS Gax
/:cl:

### CODE REVIEW

**Comment by stwordcitizen** [comment]
downvoted based on title

**Comment by milk-is-cool** [comment]
upvoted based on title

**Comment by solwashere** [comment]
upvote based on title

**Comment by Marmio64** [comment]
downvoted based on description

**Comment by LazennG** [comment]
upvoting based on title

**Review by ynot01 — APPROVED** [review]

**Comment by MajManatee** [comment]
upvoted based on title

**Comment by BurgerLUA** [comment]
downvoted based on missing period on changelog

**Comment by solwashere** [comment]
PR is in purgatory L

**Review by Ethan4303 — APPROVED** [review]
Pr is going to save all the Gaxians bored in the bar with this new revolver.... +1???

**Pull request merged**
