### PR TITLE
Removes NTSL randseed

### PR DESCRIPTION
**Pull request by ThatLing**
https://github.com/yogstation13/yogstation/pull/2991

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
AAAAAAAAAAAAA UNUSED VARIABLE WARNING

**Comment by Altoids1** [comment]
:(

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Commented code is bad,get rid of it

**Comment by ThatLing** [comment]
@alexkar598 says who?

**Comment by Amelia0010** [comment]
Getting rid of the function would break compatibility with older scripts, and I don't really see why we need to do that?

**Pull request merged**
