### PR TITLE
Cultist shield robe nerf

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Combined with the mirror shield, this makes a cultist WAY too durable

:cl:  
tweak: Cultist shield robe has 1 shield charge, but regens after 45 seconds of not getting hit
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Confer with the council but I liked what you said about it in discord.

1 charge but it'll regen.

**Comment by MajManatee** [comment]
I feel as though it should regen with two. It not doing so seems like it was either an oversight or just poor planning

**Comment by MajManatee** [comment]
45 seconds with one charge is an AWFULY long time

**Comment by Moltijoe** [comment]
> 45 seconds with one charge is an AWFULY long time

make another PR after if you think that way

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
