### PR TITLE
AI Multicamera Mode

### PR DESCRIPTION
**Pull request by Cruix**
image

:cl: Cruix
add: AIs now have an experimental multi-camera mode that allows them to view up to six map areas at the same time, accessible through two new buttons on their HUD.
/:cl:

The AI is often expected to be keeping an eye on multiple different parts of the station at all times, which usually entails smashing the "show camera list" and "track with camera" buttons for their entire play time. This PR makes it possible for the AI to store several important map locations and be able check on them all with one button press, then switch back and zoom around the map as normal.

Due to the limitations of vis_contents, I had to make a new area with no darkness and no camera static to park the AI's client eye while it looks at the different screens. You can make up to six windows, and they can be resized and moved wherever you want them on your screen. Darkness, camera static, huds, and click interaction all work normally through the windows. Parallax does not, because you cannot see space. AI detection multitools properly detect the different cameras as if they were the AI's primary camera.

All the sprites are, naturally, terrible, but maybe someone will step up and make better-looking ones.

This version comes without the /TG/ station nerfs, and with the experimental Picture-in-Picture-Follow-Mob and Picture-in-Picture-Follow-Client verbs/VV dropdown options for administrators. They open a picture-in-picture window following a selected mob or client. Their layering with the rest of the world is iffy, because they do not get their eye sent to a specially-tailored room like the AI's client does.

### CODE REVIEW

**Comment by Cruix** [comment]
I would recommend testmerging this first if you have things set up to do that.

**Comment by ThatLing** [comment]
I'd love to merge this but the code has to be modular, or we get loads of merge conflicts with upstream.

**Comment by AsV9** [comment]
@ThatLing hmm that sounds easy

**Comment by Amelia0010** [comment]
okay so if TG is gonna merge it **with the nerfs**, wouldn't it then be easier to wait for the mirror and then just make a PR undoing those nerfs?

**Comment by Cruix** [comment]
Guess we are waiting for the TG PR machine.

**Comment by Amelia0010** [comment]
could always close the one on TG 😉

**Comment by Amelia0010** [comment]
if you could fix the conflicts i'll figure out how testmerging with TGS works and then get it testmerged till TG decides on whether or not they wanna merge it or whatever they wanna do

**Comment by Amelia0010** [comment]
So after fucking around with it a bit I found a few things:

Radiation is invisible: 
image
image

If you lose power your screen will look like this, which looks odd:
image

It reverses the layering of items:
image
image

**Comment by Cruix** [comment]
I made it so losing power disables multicamera mode.

The object layering and weather not showing up are both quirks of vis_contents. Weather does not show up because it works by altering the sprite of the area, and areas never show up in vis_contents. The only way I could fix that would be to rewrite weather code to use overlays instead, which would probably hurt performance significantly.

**Comment by Amelia0010** [comment]
can't testmerge because of the conflict 😭

**Comment by Amelia0010** [comment]
IT GOT MERGED ON TEEGEE 👏 🎉 🎈 🎂

**Pull request closed without merging**
