### PR TITLE
Give protolathe some basic stuffs

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
 camera, camera film, earmuff, kitchen knife, rcd ammo, pillbottle, igniter, turret control frame, tablet, phone, laptop, pda and spray can are now printable via protolathe

# Wiki Documentation
everything in document of changes

# Changelog

:cl:  

tweak: camera, camera film, earmuff, kitchen knife, rcd ammo, pillbottle, igniter, turret control frame, tablet, phone, laptop, pda and spray can are now printable via protolathe
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
We should remove the autolathe and replace it with protolathe designs

**Comment by ShoziOffical** [comment]
> We should remove the autolathe and replace it with protolathe designs

true but yeah no more freely printing ammo :)

**Comment by ToasterBiome** [comment]
Dislike. I don’t even agree with flashlights being in protolathes. Use the multiple machines!

**Comment by ShoziOffical** [comment]
> Dislike. I don’t even agree with flashlights being in protolathes. Use the multiple machines!

there are already flashlights in there and im just adding some fogotten stuffs

**Comment by ShoziOffical** [comment]
why are you even disliking these are just normal stuffs

**Comment by ToasterBiome** [comment]
> why are you even disliking these are just normal stuffs

because it's covered in the autolathe and you should either
1) build an autolathe if you want these things. if you can't do this rules wise, you probably shouldn't have any of the stuff in there without 2:
2) go to science, service or cargo (or engineering), all places with autolathes, and _talk_ to the people in there to get what you want

**Comment by ShoziOffical** [comment]
> > why are you even disliking these are just normal stuffs
> 
> because it's covered in the autolathe and you should either
> 
> 1. build an autolathe if you want these things. if you can't do this rules wise, you probably shouldn't have any of the stuff in there without 2:
> 2. go to science, service or cargo (or engineering), all places with autolathes, and _talk_ to the people in there to get what you want

Some items here printable via protolathe are restricted in that department, also these items I listed here are supposed to be in protolathe like the igniter for example because its part of "assemblies" tab in the protolathe and the pillbottle which has ```PROTOLATHE``` tag but not isnt included in the protolathe for some reason. Not everything from autolathe i put in the protolathe because some items are pretty much restricted. If you find any item here isnt suitable for the protolathe please tell me to remove it you dont have to close my pr

**Pull request closed without merging**
