### PR TITLE
New clown tech: Holobanana projector

### PR DESCRIPTION
**Pull request by Majkl-J**
# Document the changes in your pull request
Clown tech seems kinda barren, with the only interesting part being the mech and the borg, time to spice it up with some actual items. 
This adds a holobanana projector, which produces slippery hardlight holobananas in approximately 0.69 seconds each.

The item version can have only 2 projections, 
the borg version can have up to 5 projections.

(I additionally need this so I can give one to the spiderbot aswell without cucking clowns.)

# Spriting
Projector made by me (Literally just changed the palette of the engineer projector)
Bananaproj

Holobanana peel made by papi
banana32

## Upscaled versions

BananaprojUPSCALE
banana512

# Wiki Documentation
Added holobanana projector under clown tech.
Printable from SERVICE LATHE (2000 iron, 1000 glass, 500 plastic, 1000 bananium)

# Changelog

:cl:  Majkl-J and Papi
rscadd: The best clown scientists introduce new technology: The holobanana projector
imageadd: Holobanana sprites (Courtesy to Papi)
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Does the holonana disappear after it slips someone or does it stay ?

**Comment by Maia-J** [comment]
> Does the holonana disappear after it slips someone or does it stay ?

It stays, mainly because it is one hit to remove it.

**Review by cuackles — CHANGES_REQUESTED** [review]
ok so review time,
eeeeeeeeee
the banana one looks similar to the rest but it has some aspects that make it stand out in a way that makes it feel slightly uncanny, i recomend taking out the strong bounce of the letters, either making it a lot less mild or just removing it and changing it for another movement, about the device, it looks to similar to the engi one and the color makes it look odd and without sufficient shade, i would recomend in that case using the engi one as a base and adding something like lines of colors or dots, maybe base it off the clown jumpsuit, apart from that i absolutly love the idea of a holo banana

**Comment by Maia-J** [comment]
> i recomend taking out the strong bounce of the letters, either making it a lot less mild or just removing it and changing it for another movement

New idea: **Making the bouncy text only show on slip**. I originally thought the text bounce looked pretty silly and fitting with the clown's job, come to think of that, it does stand out a bit too much.

> about the device, it looks to similar to the engi one and the color makes it look odd and without sufficient shade, i would recomend in that case using the engi one as a base and adding something like lines of colors or dots, maybe base it off the clown jumpsuit

Honestly not a bad idea, Ill see what I can do

**Comment by ReddicusDragon** [comment]
simply, why

**Comment by Burger1998** [comment]
> simply, why

same reason that clown exists. its funny

**Comment by Maia-J** [comment]
> simply, why

See "Clown tech is kinda barren", which is true, it brings no new clowning options apart from griefmech 1000

**Review by ReddicusDragon — COMMENTED** [review]
no spelling issues, pog

**Review by ReddicusDragon — COMMENTED** [review]
Not giving my approval til Cuackles provides another review. Ran it by Orca, they mention that the projector sprite is fine but the holo sprite itself needs to lose it's bounce and text should be re-added. Cuackles may provide a differing opinion.

**Comment by Maia-J** [comment]
> Not giving my approval til Cuackles provides another review. Ran it by Orca, they mention that the projector sprite is fine but the holo sprite itself needs to lose it's balance and text should be re-added. Cuackles may provide a differing opinion.

I am not touching sprites anymore until the art directors provide a definitive opinion on how it should look. Currently, I have one changed version of the projector and the holobonana without text sprited:
banana32honkless512

clownproj512

image

**Review by cuackles — APPROVED** [review]
Ok so orca left this PR to my discretion so, i felt that the words moved on an odd way where it half spined and half did a jump making it confusing on sight, for the device i wanted more of an unique feeling to it and this new one definitely gives it to it, i am a bit devised about it but by reds word orca seems to accept it so that leans me towards accepting it myself, so basically, aproved

**Review by ReddicusDragon — APPROVED** [review]

**Comment by ReddicusDragon** [comment]
Feature Freeze until the 16th, this was created during that. I'll be back to merge on the 16th.

**Comment by Moltijoe** [comment]
> Feature Freeze until the 16th, this was created during that. I'll be back to merge on the 16th.

I get the feeling that was out the window until re-enforced earlier this month, with the goal being 0 PRs this will either get merged or closed.
I'm still gonna leave it to jamie's discretion though.

**Comment by JamieD1** [comment]
Last fucking one. No more.

**Pull request merged**
