### PR TITLE
another try to get my cloak

### PR DESCRIPTION
**Pull request by Marmio64**
It's been two months

https://streamable.com/9i0ia3

its a donator item for me
it is hopefully unique and edgy enough this time around to be accepted

doesn't need a changelog
edit:apparently does????
# Changelog

:cl:  
rscadd: new donator item for marmio64: eldritch cowl
/:cl:

### CODE REVIEW

**Review by nesisknesis — CHANGES_REQUESTED** [review]
changelog

**Comment by JamieD1** [comment]
Changelog

**Comment by Marmio64** [comment]
> Changelog



> changelog

Done but my PC broke yesterday so we'll see how long it'll be til I can fix conflicts

**Comment by Marmio64** [comment]
> > Changelog
> 
> > changelog
> 
> Done but my PC broke yesterday so we'll see how long it'll be til I can fix conflicts

nevermind it was just a webedit i needed

**Comment by Marmio64** [comment]
> changelog

changes requested done, changes requested done.

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Comment by Marmio64** [comment]
I suppose it'll be another 2 months

**Comment by JamieD1** [comment]
Done waiting

**Pull request merged**
