### PR TITLE
shrimp cocktail is a drink not food

### PR DESCRIPTION
**Pull request by ktlwjec0**
makes shrimp cocktail a drink instead of a food. Crafted the same, just in drink category.

# Why is this good for the game?
annoys me that you can EAT the glass. it's a cocktail, not a food

# Testing
yes

# Spriting
no new sprites, moves one to a different file

:cl:  ktlwjec
tweak: Shrimp cocktail moved from seafood crafting, to drinks. It is now a drink instead of food.
/:cl:

### CODE REVIEW

**Comment by BlueishTsunami** [comment]
Is this a joke or do you actually not know what shrimp cocktail is? 

https://en.m.wikipedia.org/wiki/Prawn_cocktail

**Comment by ktlwjec0** [comment]
> Is this a joke or do you actually not know what shrimp cocktail is?
> 
> https://en.m.wikipedia.org/wiki/Prawn_cocktail

in game it is in a glass, as a juice with prawns added. idc what it is irl

**Review by MajManatee — CHANGES_REQUESTED** [review]
image
the "Drink" is a sauce you dip your shrimp in.

**Comment by ktlwjec0** [comment]
yeah again, it's what shows in game. i'll remake it to have the trash be a drinking glass, i really dont care i just dont want to eat glass

**Pull request closed without merging**
