### PR TITLE
Updates health analyzer sprite.

### PR DESCRIPTION
**Pull request by nesisknesis**
image

light is now above rather than, uh, at both sides?
#### Changelog

:cl:  Identification
imageadd: Small lighting tweak to health analyzer sprite. 
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
you literally changed like 2 pixels

**Comment by Nickvr628** [comment]
image

**Comment by nesisknesis** [comment]
No, I changed 40 pixels.

**Comment by alexkar598** [comment]
I've passed the last 15 minutes using different tools to find a difference and just..just no,i can't find anything different and even if something was infact different,it's  so minor it's pointless.

**Comment by Amelia0010** [comment]
I like it

**Pull request merged**
