### PR TITLE
Ports monkey cube suicide

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Original author: Cyberboss
Original PR: https://github.com/tgstation/tgstation/pull/50125

> if you try to commit suicide with a monkey cube, it gibs you and spawns a monkey (also works with gorilla cubes). see, monkey cubes activate in water, and when you think about it, stomach acid is really just spicy water. so if you swallow a monkey cube...
> 
> also: the suicide fails for species with TRAIT_NOHUNGER -- plasmamen, ethereals, skeletons, abductors, etc., since their biology doesn't involve stomach acid / saliva and thus they can't activate the monkey cube

#### Changelog

:cl:  
rscadd: Adds monkey cube suicide
/:cl:

### CODE REVIEW

**Comment by Alexandria404** [comment]
very nice

**Comment by swissloaf** [comment]
> very nice

thanks

**Comment by Jarod1200** [comment]
monke

**Comment by Hopekz** [comment]
Good enough for prod

**Pull request merged**
