### PR TITLE
emagging an airlock now requires the wires to be exposed

### PR DESCRIPTION
**Pull request by athena413**
# Document the changes in your pull request

port of BeeStation/BeeStation-Hornet/pull/9545

untested just like the PR its based on (i will test it soon)

image

you now need to expose the wires with a screwdriver in order to emag a door

you cant do this on doors that have metal placed over them (theres a single digit amount of them on the station anyway)

players can now counter the Unamagger by placing metal over the airlocks they dont want emagged

alternative to all the other emag rework pull requests

also "improves" the code to be like beestation's (i am not a good coder)

# Spriting

no

# Wiki Documentation

an extra line to https://wiki.yogstation.net/wiki/Emag#Airlock

# Changelog
:cl:  
tweak: emag now needs the airlock wires exposed in order to emag an airlock
/:cl:

### CODE REVIEW

**Comment by Therandomhoboo** [comment]
This will just encourage literally everyone to plasteel doors once they see one emagged door. As well, iirc the doors towards armoury already have plasteel on them so that will render them un-emaggable. 

Massive sec buff, with massive emag nerf. Na

**Comment by athena413** [comment]
> This will just encourage literally everyone to plasteel doors once they see one emagged door. As well, iirc the doors towards armoury already have plasteel on them so that will render them un-emaggable.
> 
> Massive sec buff, with massive emag nerf. Na

all they really need to continue the emaggaganza is a toolbelt and a welding helmet if they want to get into armory. as is they can emag all the way into armory on a lowpop round roundstart and take 81 different guns and create the funny syndie station. this doesnt stop them but it does slow them down and make them grab a toolbelt first

**Comment by RG4ORDR** [comment]
This such a stupid idea.
Like literallt ao fucking stupid, not shocking that it came from Beestation. They atleast have the excuse that they pretend to be an RP server.

All this pr does attempt to fix an issue where none exsist. The mere idea of suggesting this reeks of bone headed thinking. Explain your thesis to even why this is a good idea lmao.

**Comment by solwashere** [comment]
> This such a stupid idea. Like literallt ao fucking stupid, not shocking that it came from Beestation. They atleast have the excuse that they pretend to be an RP server.
> 
> All this pr does attempt to fix an issue where none exsist. The mere idea of suggesting this reeks of bone headed thinking. Explain your thesis to even why this is a good idea lmao.

Explain why you think this is a bad idea first instead of simply stating that it is a bad idea.

**Comment by Therandomhoboo** [comment]
> > This will just encourage literally everyone to plasteel doors once they see one emagged door. As well, iirc the doors towards armoury already have plasteel on them so that will render them un-emaggable.
> > Massive sec buff, with massive emag nerf. Na
> 
> all they really need to continue the emaggaganza is a toolbelt and a welding helmet if they want to get into armory. as is they can emag all the way into armory on a lowpop round roundstart and take 81 different guns and create the funny syndie station. this doesnt stop them but it does slow them down and make them grab a toolbelt first

All they need to do is basically become even more sus, and then get caught out because what non-antag (apart from shittlers) would actively start undoing doors with the metal over the wires? It slows people on lowpop sure, but when there are full sec & AI this will basically bait them out hard.

As well, another thought I just had was this then encourages Emaggers to go emag crazy, since they know once the emag is spotted its game over they might as well just emag everything as fast as they can. 

All in all, just make a PR to remove emag instead of making it so restrictive.

**Comment by Reed0506** [comment]
potentially better solution would be to make fixing emagged doors not require printing new airlock circuits for every single emagged door. if emagged doors could be fixed via hacking, there wouldnt be any issue with someone going "unamagger" all over the station.

**Comment by athena413** [comment]
> All they need to do is basically become even more sus, and then get caught out because what non-antag (apart from shittlers) would actively start undoing doors with the metal over the wires? It slows people on lowpop sure, but when there are full sec & AI this will basically bait them out hard.

people hacking into plasteel-secure areas are ALREADY suspicious. anyone disassembling a door reinforcement is ALREADY obviously breaking in. slowing down emaggers is also the point they should have a slight bit of time investment into an emag instead of drivebying every single one of them as they walk thru a hallway

> As well, another thought I just had was this then encourages Emaggers to go emag crazy, since they know once the emag is spotted its game over they might as well just emag everything as fast as they can.

i dont think the crew will go Nuke Ops levels of reaction to a single isolated emag incident and even then if they wanna start globally powergaming over a single breakin into the RDs office then thats a server issue and not a problem with this PR

> All in all, just make a PR to remove emag instead of making it so restrictive.

you make the PR then

its not really that aggressive of a restriction. it just adds 1 extra step between you and most doors and makes the doors that are explicitly reinforced to be actually reinforced against the emag. deconstructing reinforced covers isnt too long either its not like its an rwall.

**Comment by athena413** [comment]
> This such a stupid idea. Like literallt ao fucking stupid, not shocking that it came from Beestation. They atleast have the excuse that they pretend to be an RP server.
> 
> All this pr does attempt to fix an issue where none exsist. The mere idea of suggesting this reeks of bone headed thinking. Explain your thesis to even why this is a good idea lmao.

what did i do to you

**Comment by iamthesilly** [comment]
> As well, another thought I just had was this then encourages Emaggers to go emag crazy, since they know once the emag is spotted its game over they might as well just emag everything as fast as they can.

Why do you think aren't they already encouraged to do this? Isn't it already a clear giveaway they have an emag when they emag a door?

**Comment by Therandomhoboo** [comment]
> > As well, another thought I just had was this then encourages Emaggers to go emag crazy, since they know once the emag is spotted its game over they might as well just emag everything as fast as they can.
> 
> Why do you think aren't they already encouraged to do this? Isn't it already a clear giveaway they have an emag when they emag a door?

So we encourage it even more?

**Comment by Therandomhoboo** [comment]
> people hacking into plasteel-secure areas are ALREADY suspicious. anyone disassembling a door reinforcement is ALREADY obviously breaking in. slowing down emaggers is also the point they should have a slight bit of time investment into an emag instead of drivebying every single one of them as they walk thru a hallway

I dont think you're understanding that with this PR regardless of it being "already sus", if you have to undo the door reinforcement to emag it, it literally outs you faster than you emagging it. It isn't time investment you're basically asking people to only use it on lowpop where sec don't do patrols every 20 seconds.

> i dont think the crew will go Nuke Ops levels of reaction to a single isolated emag incident and even then if they wanna start globally powergaming over a single breakin into the RDs office then thats a server issue and not a problem with this PR

Its a "server issue" caused by a idented PR, so no it is a PR issue. 

> you make the PR then

I dont have a problem with Emags

> its not really that aggressive of a restriction. it just adds 1 extra step between you and most doors and makes the doors that are explicitly reinforced to be actually reinforced against the emag. deconstructing reinforced covers isnt too long either its not like its an rwall.

It is an aggressive restriction, you either now get people spam emags all the time or all departments get reinforced so emag becomes useless. Do keep in mind as well, that most doors apart from two areas have reinforcements on them. So when an emag gets called out and more reinforcements get put on the doors you're just stagnating the round. 
Do what everyone is suggesting and just make it easier to fix emagged doors jfc.

**Comment by athena413** [comment]
> I dont think you're understanding that with this PR regardless of it being "already sus", if you have to undo the door reinforcement to emag it, it literally outs you faster than you emagging it. It isn't time investment you're basically asking people to only use it on lowpop where sec don't do patrols every 20 seconds.

i mean yeah thats kind of the point. pretty much no doors start reinforced outside of ai upload, ai sat, vault and armory start reinforced and all but one of those spawn bolted.

> Its a "server issue" caused by a idented PR, so no it is a PR issue.

player behaviour is not my problem. again i doubt the entire damn crew is gonna respond like its nuke ops after a single incident. repeated emags maybe but thats part of the intent

> I dont have a problem with Emags

ok

 
> It is an aggressive restriction, you either now get people spam emags all the time or all departments get reinforced so emag becomes useless. Do keep in mind as well, that most doors apart from two areas have reinforcements on them. So when an emag gets called out and more reinforcements get put on the doors you're just stagnating the round.

the "spam emags all the time" gimmick is already being done and if a traitor starts taking the piss and begins emagging every door they walk past they deserve to be reacted to. thats part of antagonism.

> Do what everyone is suggesting and just make it easier to fix emagged doors jfc.

no

**Comment by Therandomhoboo** [comment]
> i mean yeah thats kind of the point. pretty much no doors start reinforced outside of ai upload, ai sat, vault and armory start reinforced and all but one of those spawn bolted.

Ided

**Comment by neeshacark** [comment]
traitor buys emag + storage implant as get out of perma free card

cant escape because lol fuck u no screwdriver

**Comment by athena413** [comment]
> traitor buys emag + storage implant as get out of perma free card
> 
> cant escape because lol fuck u no screwdriver

what if i made it so that emagging a sustenance vendor or something else in perma allows it to dispense 1 of each tool

**Comment by Scrambledeggs00** [comment]
Too lazy to see if someone else mentioned this, but this could lead to a single person with a screwdriver completely nullifying the emag's ability to open airlocks since they could just close the hatch as soon as the emagger opened it. Granted, they'd need at least a metal sheet over the hatch to have enough time to close it, but I could still see this being a problem as the same strategy can and has been used against airlock hackers.

**Comment by Scrambledeggs00** [comment]
> traitor buys emag + storage implant as get out of perma free card
> 
> cant escape because lol fuck u no screwdriver

Kinda your own fault for not using the implant to sneak in tools as well, unless storage implant has had its storage massively nerfed since I used it last.

**Comment by RG4ORDR** [comment]
There is no reason to even consider merging because this is attempting to create a non-existent problem and solving said problem.

   Yogs is NOT an RP server, it is LRP server, no matter how we wanna proclaim we are MRP - we focused exclusively on balance as it affects the rounds as a GAME. Not a roleplay server. Beestations port you're attempting to do works for Beestation because Bee tends to have way more greenshifts and much longer rounds than we do. We dont have many rounds with intention greenshift or rounds lasting longer than close to 2 hours.
   This change does not provide healthy balance or change due to a false notion that emags are problematic. They aren't.
I will say this with 100% confidence as nobody on yogs has ever asked for a emag nerf, nobody bemoans that the emags exsists, nobody makes discord rants,OOC rants, or dead chat rants about the emag. They don't, if you say they do you're lying I know you are so dont pull that with me :).
   This not a needed change because it adds an unneeded interaction. It is needlessly clunky, and is a disaster for new players coming on because they are already conditions to know emag on doors opens doors. It is not good because the way the emag works on other objects will leave a big question mark to why don't you need to deconstruct a computer to emag it, or why can you emag firing pins, or why you can emag bots w/o turning them off, why can you emag vendors,etc,etc,etc,etc.
   
   In even simpler terms I can put this how can you justify to me right now for this PR why this is good for the game? If you cannot do it in a single sentence then there is no reason to alter the emag anymore than it has already been altered.
   
   
   There is NOTHING wrong with people being the Unamagger - it's funny, it's a player fucking around, people whine antags dont do enough shit. But we have this PR right here directed at antags doing antag actions that aren't even that harmful. All this does is opens up powergaming by players to start adding metal and plasteel to doors, this hampers antags. This doesnt work for the benefit of the server and players it works in the exact opposite.

**Comment by SomeguyManperson** [comment]
> There is no reason to even consider merging because this is attempting to create a non-existent problem and solving said problem.
> 
> Yogs is NOT an RP server, it is LRP server, no matter how we wanna proclaim we are MRP - we focused exclusively on balance as it affects the rounds as a GAME. Not a roleplay server. Beestations port you're attempting to do works for Beestation because Bee tends to have way more greenshifts and much longer rounds than we do. We dont have many rounds with intention greenshift or rounds lasting longer than close to 2 hours. This change does not provide healthy balance or change due to a false notion that emags are problematic. They aren't. I will say this with 100% confidence as nobody on yogs has ever asked for a emag nerf, nobody bemoans that the emags exsists, nobody makes discord rants,OOC rants, or dead chat rants about the emag. They don't, if you say they do you're lying I know you are so dont pull that with me :). This not a needed change because it adds an unneeded interaction. It is needlessly clunky, and is a disaster for new players coming on because they are already conditions to know emag on doors opens doors. It is not good because the way the emag works on other objects will leave a big question mark to why don't you need to deconstruct a computer to emag it, or why can you emag firing pins, or why you can emag bots w/o turning them off, why can you emag vendors,etc,etc,etc,etc.
> 
> In even simpler terms I can put this how can you justify to me right now for this PR why this is good for the game? If you cannot do it in a single sentence then there is no reason to alter the emag anymore than it has already been altered.
> 
> There is NOTHING wrong with people being the Unamagger - it's funny, it's a player fucking around, people whine antags dont do enough shit. But we have this PR right here directed at antags doing antag actions that aren't even that harmful. All this does is opens up powergaming by players to start adding metal and plasteel to doors, this hampers antags. This doesnt work for the benefit of the server and players it works in the exact opposite.

needing to repair doors once or twice is fine
needing to repair doors a hundred twenty times because someone's emagging them the second you leave the area is irritating, especially since there is no need to stick around in any given area, meaning they can't be effectively tracked or handled by security (and if you try yourself you're gunning for a validhunting bwoink)

People reserve the right to emag literally every door on the station but engineers should also reserve the right to have a method to slow that down after the first or second "I've had to replace every door in science, cargo, medical, and security" loop

**Comment by RG4ORDR** [comment]
Your argument has the same application to every single department.

"Doing X once or twice is fine."
"Doing X more than that is annoying."

It's literally not a fault of the emag or the player that engineering is doing menial labor that isn't off crafting some secondary engine,turbine shenanigans, some NEET shuttle to explore space. You should be relived that you're having to fix a bunch of broken doors instead of massive gaping bomb holes in the station. You're being lightly inconvenienced by an antag who isn't committing mass murder because you're fixing a broken hole they caused because they have hijack. Hell I haven't mentioned that now people with screwdrivers can be considered suspicious when a door gets emagged. I've seen aggressive attempted implants checks w/o evidence to search for implants. Whats to say that players wont start abusing this for valid hunt more extensively? Which again goes back to my original point.

How does this help the game, why is it beneficial to nerf it. Why are we imposing a needless restriction onto the emag without considering every other emaggable item in the game will now have to be looked at in the same light?
Nah it's never considered because it's short sighted. It's unnecessary. This is a game, this part of the game doesn't need to be made more needlessly clunky to feint false balance.

**Comment by SomeguyManperson** [comment]
> Your argument has the same application to every single department.
> 
> "Doing X once or twice is fine." "Doing X more than that is annoying."

one must imagine Sisyphus happy

**Comment by MajManatee** [comment]
engineering players being driven to suicide bc they have to RCD a door away and back a couple times.

Also yeah, no rationale besides "I dont like it"

**Comment by solwashere** [comment]
> Your argument has the same application to every single department.
> 
> "Doing X once or twice is fine."
> "Doing X more than that is annoying."
> 
> It's literally not a fault of the emag or the player that engineering is doing menial labor that isn't off crafting some secondary engine,turbine shenanigans, some NEET shuttle to explore space. You should be relived that you're having to fix a bunch of broken doors instead of massive gaping bomb holes in the station. You're being lightly inconvenienced by an antag who isn't committing mass murder because you're fixing a broken hole they caused because they have hijack. Hell I haven't mentioned that now people with screwdrivers can be considered suspicious when a door gets emagged. I've seen aggressive attempted implants checks w/o evidence to search for implants. Whats to say that players wont start abusing this for valid hunt more extensively? Which again goes back to my original point.
> 
> How does this help the game, why is it beneficial to nerf it. Why are we imposing a needless restriction onto the emag without considering every other emaggable item in the game will now have to be looked at in the same light?
> Nah it's never considered because it's short sighted. It's unnecessary. This is a game, this part of the game doesn't need to be made more needlessly clunky to feint false balance.
> 

Have you ever played engineering?
I'd rather fix a bomb hole than a bunch of emagged doors, it's slightly more "engaging"
Unamaggers aren't fun because not only did they undoubtedly steal shit, a bunch of shitter tiders now have easy access into wherever they need to be to steal shit.

**Comment by athena413** [comment]
code sucks less now. ready for review

**Comment by iamthesilly** [comment]
Merge conflicts, also PR description should include your reasoning for why it's good for the game.

**Comment by iamthesilly** [comment]
You reverted your fix when resolving the merge conflict

**Comment by athena413** [comment]
> You reverted your fix when resolving the merge conflict

looks correct on my end

**Comment by iamthesilly** [comment]
> looks correct on my end

Weird, it showed up as your old changes for a moment. Oh well, it's fixed now.

**Comment by ToasterBiome** [comment]
Don't like that you have to carry around more than 1 item to emag + bolting is the way to counter emags

**Pull request closed without merging**
