### PR TITLE
Ports many sprite related PR's from TG

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Ports some sprite related PR's from TGstation

https://github.com/tgstation/tgstation/pull/67069
https://github.com/tgstation/tgstation/pull/67725
https://github.com/tgstation/tgstation/pull/66942
https://github.com/tgstation/tgstation/pull/66794
https://github.com/tgstation/tgstation/pull/66746
https://github.com/tgstation/tgstation/pull/65828
https://github.com/tgstation/tgstation/pull/65489
https://github.com/tgstation/tgstation/pull/65081

# Spriting

nightmare cardboard
image
baton
image
welding effect
image
burning effects
image
extinguishers
image
screen alerts
image
mass driver and shield thing
image

# Changelog

E

:cl: SmArtKar, SpadesSlick, UDaV73rus, Tokoriso, dragomagol, PositiveEntropy, Retlaw34, PacifistDalek, DarthSidiousPalpatine, Wallem, JosephJomama, unit0016. Ported by SuperSlayer
imageadd: New sprites for xenobio shield wall generators
rscadd: welding now has an animation!
imageadd: icon for welding animation
imageadd: Resprites the fire extinguishers 
imageadd: Regenerative core and wounded status effects now have different icons
imageadd: Mob fire sprites have been updated!
imageadd: Resprites the mass driver
imageadd: The police baton has been resprited into a handsome beatin' stick worthy for a lone-wolf detective who doesn't play by the rules to whack perps with.
imageadd: HONK Co. Pranks have released a new set of stencils for any cardboard cutouts you might find lying around, these ones EXTRA "RR-REAL HELP M-". Whatever that means.
/🆑
/:cl:

### CODE REVIEW

**Comment by stwordcitizen** [comment]
can you post a picture of the sprites?

**Comment by ghost** [comment]
> can you post a picture of the sprites?

Check original PR's or icon diff bot please.

**Comment by ghost** [comment]
Also i will post them, but at this koment i can't

**Comment by KillerOrcaCora** [comment]
Please follow the templates we have set, this includes showing the sprites in the sprite section even if there is a original sprite and also try to port 1-2 sprites at a time.

**Review by KillerOrcaCora — COMMENTED** [review]
This PR has too many sprites at one time and I am a bit iffy on how much half of these will really fit. Please try to keep ports to 1-2 sprites as in category not literal 2 sprites and for the shield generator, I would like to see how that looks in-game.

**Pull request closed without merging**
