### PR TITLE
gives handcuffs 4 damage

### PR DESCRIPTION
**Pull request by boodaliboo**
there metal
:cl:  
rscadd: gave damage to handcuffs and all its subtypes
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
ah yes 4 damage to zipties

**Comment by boodaliboo** [comment]
> ah yes 4 damage to zipties

read the code

**Comment by patpol4** [comment]
~Asimov secborgs~👀
EDIT: ok i read the code, makes sense i guess

**Comment by ChesterTheCheesy** [comment]
If i threw handcuffs at someone the only damage they'd suffer would be emotional damage.

**Comment by alexkar598** [comment]
Follow the template

**Review by alexkar598 — CHANGES_REQUESTED** [review]
template

**Comment by boodaliboo** [comment]
> template

what template?

**Comment by patpol4** [comment]
The PR description template that you deleted

**Comment by boodaliboo** [comment]
> The PR description template that you deleted

how do i get it back

**Comment by athena413** [comment]
can we start auto closing prs that remove the template because people arent code literate

(for not nerds: hitting people with handcuffs or throwing handcuffs at them will deal 4 damage - you will NOT take damage while cuffed)

**Comment by SomeguyManperson** [comment]
cuffs generally get thrown around a lot and we don't need more reasons for people to scream shitsec from someone accidentally hitting them with cuffs

**Pull request closed without merging**
