### PR TITLE
Adds """some dude""" as a pre legion fight definitely a miniboss(just a mob)

### PR DESCRIPTION
**Pull request by Ethan4303**
# Document the changes in your pull request

Adds a new miniboss(mob) to fight just before knocking on Legions Gate, Jim The Door Technician
image
May He stand tall and guard well, While also keeping the door in functioning order :)

# Spriting

N/A

# Wiki Documentation

Maybe mentioned on legions page if theres a legion page

# Changelog

:cl:  
mapping: Added Jim The Door Technician to the Gates of legions Temple
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
fuck im gonna need to make Jim lore

**Comment by Ethan4303** [comment]
> fuck im gonna need to make Jim lore

sounds like you want to make jim lore
You agree jim is a good addition, thank you

**Comment by ToasterBiome** [comment]
needs to be descended from megafauna to get the right bonuses

**Comment by Ethan4303** [comment]
> needs to be descended from megafauna to get the right bonuses

What do you mean? hes supposed to be weak

**Review by Aquizit — APPROVED** [review]

**Comment by Aquizit** [comment]
Oh I get biome's comment. The title of the pr is misleading if it's just some dude.

**Pull request merged**
