### PR TITLE
adds cryopod to syndicate listening post

### PR DESCRIPTION
**Pull request by boodaliboo**
syndicate is a big company they can afford to give there employees cryogenic sleep
#### Changelog

:cl:  
rscadd: Added cryopod
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
This would probably only work if you made a special cryo subtype that made the person in cryo into a ghost spawner. If it deletes them this just makes it harder for everyone to get more people in.

**Comment by boodaliboo** [comment]
> This would probably only work if you made a special cryo subtype that made the person in cryo into a ghost spawner. If it deletes them this just makes it harder for everyone to get more people in.

doesnt it offer you to ghosts?

**Comment by patpol4** [comment]
It gives you the option to offer yourself and deletes you after 5 minutes if nobody took it.

**Comment by patpol4** [comment]
Closing since this is pointless with the way the cryo we have works

**Pull request closed without merging**
