### PR TITLE
(port) Adds Malt Liquir

### PR DESCRIPTION
**Pull request by boodaliboo**
Original Pr https://github.com/tgstation/tgstation/pull/51830
adds malt liquor a new type of liquor with a new bottle sprite only obtainable through boozemat
#### Changelog

:cl:  
rscadd: Added malt liquor bottle to the boozemat
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
please compile

**Comment by boodaliboo** [comment]
yay

**Comment by maxion12345** [comment]
Do we have vinegar yet

**Comment by maxion12345** [comment]
Do we have vinegar yet

**Review by Partheo — CHANGES_REQUESTED** [review]
Don't create a second changelog entry for changes that are described in the first.

Sprite is fine.

**Comment by boodaliboo** [comment]
> Don't create a second changelog entry for changes that are described in the first.
> 
> Sprite is fine.

but im refererring to adding a alcoholic drink then referring to adding a sprite

**Comment by Partheo** [comment]
> but im refererring to adding a alcoholic drink then referring to adding a sprite

Adding the alcoholic drink (a feature) *implies* that you are adding a sprite for said feature. If there was no sprite, the feature would be incomplete and you wouldn't PR it.

The "imgadd" changelog entries are only for when you're making a visual change that is significant enough to warrant a changelog entry on its own. For example, updating an existing sprite, or otherwise making a change that only affects visuals.

**Comment by boodaliboo** [comment]
> > but im refererring to adding a alcoholic drink then referring to adding a sprite
> 
> Adding the alcoholic drink (a feature) _implies_ that you are adding a sprite for said feature. If there was no sprite, the feature would be incomplete and you wouldn't PR it.
> 
> The "imgadd" changelog entries are only for when you're making a visual change that is significant enough to warrant a changelog entry on its own. For example, updating an existing sprite, or otherwise making a change that only affects visuals.

ah i understand that ill do that for now on

**Review by Partheo — APPROVED** [review]

**Review by fluffe9911 — APPROVED** [review]
k

**Pull request merged**
