### PR TITLE
chaplain stat passover: armor edition

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

State of chaplain with its armor and weaponry is fairly dull and uninteresting so here I go making bad balance decisions to try and spicen them up. All armors from the ARMAMENT BEACON SPECIFICALLY have gotten some kind of passover. The gist of each is basically now:

- Crusader: Very good melee armor, moderate bomb armor, meh everything else. Chestpiece has 0.3 slowdown, helmet 0.05
- Profane Scholar: Negative armor on both head and body (not as significant as flagellant), but makes you faster. Chestpiece has -0.2 slowdown, helmet -0.1
- Stone Sentinel: EVEN slower than Crusader, but better overall; not as good against bombs, though. Chestpiece has 0.4 slowdown, helmet 0.1
- Witch Hunter: Has good melee armor, and that's about it. Chestpiece has 0.1 slowdown, helmet 0
- Followers of the Chaplain: Okay armor all around; worse than a sec vest. Follower hoodies have less armor; practically non-significant. Chestpiece has 0 slowdown, hood 0
- Black Templars: The helmet no longer has flash protection because no lmao. Provides good melee, fire, and acid protection, as well as possessing some of everything else. The apprentice armor isn't as good, once again. Chestpiece has 0.25 slowdown, helmet none (because... hardsuit)

Also re-organized the armors in code position to make more sense

Balance discussion highly encouraged I didn't run any numbers on these and slowdown is pretty miserable but so is fighting someone who will NOT DIE and while the chaplain should feel like a threat on cult rounds and playing one should semi-feel like protagonist syndrome it should not be absurd and obnoxious on other round types

# Wiki Documentation

Armaments beacon will have to be updated on the Chaplain page and the armors should be detailed at the bottom of Guide to Combat; I can honestly just do it myself since I didn't list the specific values in this PR so they just exist in the code

# Changelog

:cl:  
tweak: Chaplain armors from the armament beacon are actually now all different instead of just deriving armor from the crusader armor or having basically none; the hardier the armor, the better but it'll also make you slower
tweak: Removes flash protection from the Black Templar armors
spellcheck: Changes descriptions of most of the chaplain armament armors with "cool lore" involved and implied
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
SPEED ROBE WITH ARYTHMIC KNIFE, BECOME THE HERALD OF SPEED.
YES YES YES YES YES

**Comment by Simplehorror** [comment]
stop adding slowdown to shit, there's a reason nobody uses the duffel bag aside people who want to be slow

**Comment by Simplehorror** [comment]
if you add slowdown to any item, you kill the item

**Comment by Marmio64** [comment]
I actually liked the items being the same, since I want to use them for fashion and armor. Being able to select any armor without worrying about one being better statswise, and not having to suffer from stupid and annoying slowdown, is more important to me than this.

**Comment by Skrem7** [comment]
> I actually liked the items being the same, since I want to use them for fashion and armor. Being able to select any armor without worrying about one being better statswise, and not having to suffer from stupid and annoying slowdown, is more important to me than this.

Very good point, would 100% cut back most of the changes to focus on universalizing them if other people feel the same way

**Comment by Simplehorror** [comment]
> > I actually liked the items being the same, since I want to use them for fashion and armor. Being able to select any armor without worrying about one being better statswise, and not having to suffer from stupid and annoying slowdown, is more important to me than this.
> 
> Very good point, would 100% cut back most of the changes to focus on universalizing them if other people feel the same way

just make it so you have to intall the armor plating or some shit

**Comment by Moltijoe** [comment]
> Very good point, would 100% cut back most of the changes to focus on universalizing them if other people feel the same way

i think it's worth to cut back on the specific armour sets that are clearly more aesthetic, but redoing ones that people have come to expect to have some sort of function seems fair. Slowdown is rough, most people won't want it if it isn't a hardsuit or other suitably HIGHLY useful item

also, for crusader armour, full plate armour isn't actually as restrictive as you'd think, not to mention that the crusader set actually seems to have a great deal of mail, which might as well just be a slightly heavier shirt

Something that might be worth considering is implementing some other anti-cult effect since chaplain honestly don't have any aside from holy water and anti-magic when specifically holding their null rod

**Comment by Skrem7** [comment]
> i think it's worth to cut back on the specific armour sets that are clearly more aesthetic, but redoing ones that people have come to expect to have some sort of function seems fair. Slowdown is rough, most people won't want it if it isn't a hardsuit or other suitably HIGHLY useful item

Cut down on the slowdown; I might make an option for "standardized versus unique" to basically make it so you could just have a standard set of armor that would be shared across all of them (aka good melee armor, no slowdown, little else) but then still have the option to take the more thematically appropriate variant

> also, for crusader armour, full plate armour isn't actually as restrictive as you'd think, not to mention that the crusader set actually seems to have a great deal of mail, which might as well just be a slightly heavier shirt

Slowdown was cut down yes

> Something that might be worth considering is implementing some other anti-cult effect since chaplain honestly don't have any aside from holy water and anti-magic when specifically holding their null rod

Issue is that pretty much covers all the bases minus getting hit by a sword/spear/what have you, since arrows also resolve against melee armor so they're already pretty well-rounded on all those bases. Cool anti-cult effects could be applied to make some null rods* more tricky

**Comment by Rdrazga** [comment]
Doing a quick glance of the armor values I don't see anything overly bad or good. Chaplain due to the ruleset is often not a combat role anyways so don't think there is much to say about any of this armor.

**Comment by Rdrazga** [comment]
> Doing a quick glance of the armor values I don't see anything overly bad or good. Chaplain due to the ruleset is often not a combat role anyways so don't think there is much to say about any of this armor.

I must agree though I like the idea of speedup armor but hate the armor it is on for asthetic reasons.

**Comment by neeshacark** [comment]
i dont think the armor should affect your speed positively or negatively

**Comment by Rdrazga** [comment]
> i dont think the armor should affect your speed positively or negatively

It used to even before this, most of the armors used to just be riot gear with a slowdown

**Comment by Skrem7** [comment]
> > i dont think the armor should affect your speed positively or negatively
> 
> It used to even before this, most of the armors used to just be riot gear with a slowdown

so curiously a lot of the armors actually derived from crusader which gave 40 melee armor and some other stuff which was pretty robust for no slowdown

the black templar armor had WORSE armor but it gave flash protection and slowdown because lol???

and the follower hoodie sucked

so this was some attempt to make it not... stupid...?

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
