### PR TITLE
Revert "Chem heaters now heat up linerarly"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#10108

I did this for Lyis see his comment I guess

### CODE REVIEW

**Comment by Moja10** [comment]
Please, it's legitimately a feature that they scale logarithmically ...

**Comment by redmoogle** [comment]
Why dont you fix the log instead of reverting.

**Comment by Bibby0110** [comment]
> Why dont you fix the log instead of reverting.

depends on whats wrong with it

**Comment by redmoogle** [comment]
> > Why dont you fix the log instead of reverting.
> 
> depends on whats wrong with it

Scales incorrectly, this was the saner of two methods

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
