### PR TITLE
Remove Hijack as it just leads to murderbone

### PR DESCRIPTION
**Pull request by JamieD1**
Remove Murderboning Hijack objectives

:cl:  
rscdel: Removed Hijack
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
That’s the point of hijack, we have it for the rare chance to let people kill people, it’s rarely ever a problem as it comes up so little and you do know there’s more then one murderbone  enabling objective (tldr this is a dumb pr as hijack allows you to murderbone and it’s intended to do so)

**Comment by boodaliboo** [comment]
Also add I ded tag

**Comment by overlord12345** [comment]
Ided

**Comment by JamieD1** [comment]
Fair enough, close it if you wish

**Comment by overlord12345** [comment]
Also if you want to remove the objective you gotta get rid of the are where it lands after hijack

**Pull request closed without merging**
