### PR TITLE
Reworks batons

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Reworks stun batons to focus more on stamina damage over the paralysis and makes it effected by energy armor. With these changes batons are a two hit for a knockdown on someone with no armor, though if you hit a disabler shot before, it will instantly stun. Note this is assuming they have no armor, which effects baton stuns at two times the normal amount (so 50 energy armor prevents all of the stamina damage). Also, batons do 70 stamina damage, prods do 45 and the delay for the paralysis is removed (though I may re-add that later).

# Wiki Documentation

None needed if the way batons work aren't mentioned. 

# Changelog

:cl:  
tweak: reworks stun batons to focus more on stamina damage over the paralysis
tweak: stun batons are now effected by energy armor
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
Shotgun meta

**Comment by TheLinuxOS** [comment]
not only does this change affect security it also completely screws over antags as it makes it much more difficult for them to fight security and gives more time for a crew member to walk up and stop them

**Comment by nmajask** [comment]
> not only does this change affect security it also completely screws over antags as it makes it much more difficult for them to fight security and gives more time for a crew member to walk up and stop them

The main way this affects sec is that it requires them to tag their target with a disabler twice before/after hitting someone or just hit them again because they are still slowed down from the 70 stamina damage they are taking. If they have notable energy armor, they should consider getting lethals or using the other security weapons. As for antags, if they got their baton from an officer they probably also have a disabler, so they can do the above. If they don't have a disabler they can still just hit them again, and if their opponent has energy armor they should either run away, use a lethal weapon like an axe or a knife, use a bomb, or use traitor gear if they have any. The only antag I can see having an issue is slings as prods were nerfed, but it's still a two hit on an unarmed target. As for crew members stepping in, if they have no reason to attack you that's an admin issue and if they do you should have picked your fights better or gotten a weapon like an axe or a knife for the wounds.

**Comment by SomeguyManperson** [comment]
suggest using apply_damage or another damage proc that calculates armor internally to avoid the effective damage reduction from limbs when using adjust procs

**Comment by Cartlord** [comment]
definite ided

**Comment by nmajask** [comment]
> suggest using apply_damage or another damage proc that calculates armor internally to avoid the effective damage reduction from limbs when using adjust procs

done

**Comment by maxion12345** [comment]
>delay for paralysis removed

we're taking steps back here people

**Comment by nmajask** [comment]
> we're taking steps back here people

I can re-add the delay if people want it.

**Comment by N3D6** [comment]
Can we stop with these fucking hugbox ass nerfs

**Comment by nmajask** [comment]
> Can we stop with these fucking hugbox ass nerfs

Could you please give any other criticism apart from "hugbox lmao" so I can improve the PR. The point of the PR is not to make it so people don't get killed, its to make it so one of the strongest melee weapons in the game less of a necessity for sec and antags and allow for other weapons to be somewhat useful in combat.

**Comment by Hopekz** [comment]
Good PR that is leading us in a better game direction vs what we currently have.
Ignore the haters most of them don't even know what this PR does besides seeing it as "sec nerf" or "sec buff"

**Comment by LazennG** [comment]
good pr, helps make people-antag and sec- rely on other things besides batong more

**Comment by KittyNoodle** [comment]
Sec players when they cannot 1v1 a traitor anymore

**Comment by ToasterBiome** [comment]
Maint pump ups make you pretty much immune to batons now for a very long time, watched an antag absolutely wail on this security officer that used one and got 8 hits in with the baton and they never even thought about going down

**Comment by SomeguyManperson** [comment]
> Maint pump ups make you pretty much immune to batons now for a very long time, watched an antag absolutely wail on this security officer that used one and got 8 hits in with the baton and they never even thought about going down

pump up has no effect on the stamina damage though

**Comment by ToasterBiome** [comment]
> > Maint pump ups make you pretty much immune to batons now for a very long time, watched an antag absolutely wail on this security officer that used one and got 8 hits in with the baton and they never even thought about going down
> 
> pump up has no effect on the stamina damage though

uh oh 

i’ll have to look at what happened, guy said they used a pump up

**Comment by nmajask** [comment]
> Maint pump ups make you pretty much immune to batons now for a very long time, watched an antag absolutely wail on this security officer that used one and got 8 hits in with the baton and they never even thought about going down

Pump-up should only reduce the length of the paralysis, which I'm going to assume usually isn't the thing that downs you as its much more likely you're going to hit the 100 stamina damage threshold around the same time as the 90 damage one. I could however change it so that the stun resistance trait cuts the stamina damage in half or something so the pump-up is somewhat useful. Also, could make the reboot implant give you the stun resist trait as I hear it's not very useful, though I don't know if that's true or if that's a good idea.

**Comment by KittyNoodle** [comment]
God this has shown me how much slings need actual stuns, our current sling stuns are shit.

**Comment by The-Sun-In-Splendour** [comment]
Step 1. Take the reflective energy armor
Step 2. laugh

**Comment by burn1cycle** [comment]
I think your design works counter to game design theory for SS13.

 We want effective security equipment so that antags are encouraged to remain covert or else face the stun of a baton.

**Comment by KittyNoodle** [comment]
> I think your design works counter to game design theory for SS13.
> 
> We want effective security equipment so that antags are encouraged to remain covert or else face the stun of a baton.

And when an antag gets a baton?

having one weapon instantly win a fight is bad game design

**Comment by BobTheButton** [comment]
The stamina damage from the first hit will be enough to slow unarmored people down to hit them again easy, it doesnt effect the balancing that much because most antags use stun batons too! This might finally end the stun meta and promote actual fighting instead of clicking someone with a baton once.

**Comment by BobTheButton** [comment]
I dont think abductor batons should be effected by this.

**Comment by Sniblet** [comment]
This isn't necessarily a two-hit, because batons and prods have a short recharge time between zaps before they can zap again, and also energy armor makes a very conspicuous difference
This means that a lot of the time, in a fight between an eldritch sword and a stunbaton, the sword wins

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
