### PR TITLE
Removes tasers from darkspawn

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Removes "micro"stun from darkspawn tentacles

I was under the impression that they didn't stun you, don't know how this slipped by me, you now can reasonably fight back

# Changelog

:cl:  
tweak: Removed hardstun from darkspawn tentacles
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Change it to an immobilize or something so you cant just immediately crawl away when they try to dark bead

**Comment by 00ze-cyclone** [comment]
Iliv

**Comment by ynot01** [comment]
> Change it to an immobilize or something so you cant just immediately crawl away when they try to dark bead

Dark bead hardstuns the target specifically so that you can complete the beading, non issue

**Comment by TheRyeGuyWhoWillNowDie** [comment]
(Uland Christman goes into maintenance alone as a detective with nothing except for a revolver and gets attacked by a darkspawn)
Uland Christman says, "MICROSTUN"
Uland Christman says, "Their tentacle stuns you for two seconds"

Makes you think...

**Comment by ynot01** [comment]
Thank you for detailing my shock and horror at this revelation

**Review by MajManatee — APPROVED** [review]
i hate darkspawns

**Comment by Hopekz** [comment]
> (Uland Christman goes into maintenance alone as a detective 

What a valid hunter

**Comment by Marmio64** [comment]
cant you already fight back with something called a shield

**Comment by ynot01** [comment]
> cant you already fight back with something called a shield

you can do the same vs tasers

**Comment by Simplehorror** [comment]
> > cant you already fight back with something called a shield
> 
> you can do the same vs tasers

no you can't

**Comment by Simplehorror** [comment]
tasers were perfectly balanced and we should add them back

**Comment by Burger1998** [comment]
dont we literally have a full counter to tentacle already? if your hunting without a shield thats kinda on you

**Comment by ynot01** [comment]
> dont we literally have a full counter to tentacle already? if your hunting without a shield thats kinda on you

what is the full counter to tentacle? shields only have a 50% chance to block tentacles like everything else

**Comment by Sniblet** [comment]
Spawn kind of rely on that "micro"stun to get off devour will, they still have to click you

also like... oh no, man... shields don't let me always win a 1v1 with a darkspawn...

**Comment by ynot01** [comment]
> Spawn kind of rely on that "micro"stun to get off devour will, they still have to click you

They most certainly do not. If you cannot click someone crawling away then you have a skill issue

**Pull request merged**
