### PR TITLE
TG-ify our DNA code Round 2: Headcoders aren't safe from me

### PR DESCRIPTION
**Pull request by Chubbygummibear**
- closes my first attempt https://github.com/yogstation13/Yogstation/pull/14067
# Round 2?

yeah i'm like 90% certain i ironed out the preference savefile quirks and it won't break your characters into grayscale monstrosities

Your prefs will auto save with the full hexcode colors while retaining your color choices next time you launch and this is active

# Document the changes in your pull request

More specifically ports

- [Makes mutant bodyparts and mutcolors into editable genetic traits](https://github.com/tgstation/tgstation/pull/59636)
- [DNA code now supports unique identity and features blocks of different size.](https://github.com/tgstation/tgstation/pull/62303)

# What does this actually do?
well if i did everything perfectly right, 90% of players won't notice anything changed. xeno traits such as lizard frills, pod hair, and moth wings are all stored in a separate chunk of dna that everyone has, meaning they can be edited through genetics as well as dna injectors working on the same species instead of only working for and on humans.

# Did you spend a ~~week~~ month porting tg's dna code just to buff genetics?
yeah

# Wiki Documentation

I'm unsure how much the wiki covers about dna, but maybe a blurb about DNA storing mutant features now, and genetics being able to alter these

# Changelog

:cl:  @Y0SH1M4S73R, @Ghommie, Chubbygummibear
rscadd: The DNA console can now edit the nonhuman features of its occupants, as well as allowing injectors to apply those features. Look for the "Features" tab in the DNA console.
rscadd: everyone has a whole new dna block called unique_features that holds things like mutant color and alien bits settings. unique features can be altered and copied onto other people through genetics. this only works on people of the same species 
wip: this is probably going to need a lot of ongoing work  
tweak: hexcolors are handled differently 
experimental: Whole lotta DNA and color code reworking
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Can you dm me when its conflict fixed and we can test it on the test server to make sure things dont break

**Comment by JamieD1** [comment]
@Chubbygummibear DM me please when its conflict resolved

**Comment by Bibby0110** [comment]
Cornflakes. Reopen and DM me or Jamie and we will promptly testmerge it :)

**Comment by Chubbygummibear** [comment]
will get this sorted in like a week, busy with school stuff atm

**Pull request closed without merging**
