### PR TITLE
Utility Exosuit Update

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

This PR adds new types of equipment for utility mechs, and additional functionality to some of the existing ones. Also adds new sounds for the hydraulic clamp, and for APLU mech movement.

Added equipment:
- RPD - works just like a handheld RPD, but ranged like the RCD
- RCS thrusters - allows using the internal air supply as a jetpack to maneuver in space
- T-ray scanner - has twice the range of the handheld version, and no downtime
- Pressure washer - sprays water at things to clean them
- Heavy mop - sweeps and cleans items in front of the mech while moving forward, can be swung to sweep a larger area
- Comically large flyswatter - for killing comically large bugs

New equipment features:
- Hydraulic clamp - works as a crowbar or wrench depending on setting, can pry powered doors
- Plasma cutter - can act as a welder the same way a handheld cutter can
- RCD - now has the full functionality of an actual RCD

RCD tgui is from tgstation/tgstation#71710, RCS thruster is from tgstation/tgstation#47554

# Why is this good for the game?
Gives utility mechs more actual utility, currently they're very under-used and bad at their intended purpose.

# Testing
Ripley movement and clamp sounds:

https://github.com/yogstation13/Yogstation/assets/93578146/c192af63-a3d7-4c5a-86fc-58889a677b51

RCS thrusters:

https://github.com/yogstation13/Yogstation/assets/93578146/520e7cc6-b2db-41f0-84c4-812228afd0c6

RCD tgui:
image

# Spriting
Equipment
image
image

Action Buttons
image
image
image

# Wiki Documentation

Add the new equipment to the list of exosuit equipment on the guide to robotics, edit the existing mech equipment to reflect the changes documented above.

# Changelog

:cl:  sapphicoverload, syncit21, zxaber
rscadd: added a bunch more equipment for utility mechs
soundadd: adds new sound effects for hydraulic clamp and APLU mech movement
tweak: hydraulic clamp works as a wrench or crowbar and can pry powered doors
tweak: mech plasma cutter can be used as a welder like the handheld version
tweak: mech RCD works like an actual RCD now
tweak: adds tgui RCD menu
tweak: strafe button icon shows whether or not you're strafing
tweak: APLU and Clarke mechs now have radiation shielding
bugfix: fixed clarke movement not working correctly
bugfix: fixes and re-adds multi-Z mech movement (no phasing through floors or teleporting to other z-levels this time)
/:cl:

### CODE REVIEW

**Comment by PibeCantina** [comment]
Speedmerge please

**Review by cuackles — APPROVED** [review]

**Comment by ofscarletdreams** [comment]
wheres molti with his balance council cohorts wheres like everyone else this is such a cool pr WHY IS IT FORSAKEN

**Comment by wonderinghost** [comment]
Imagine being healed by a plasma cutter

**Review by ToasterBiome — APPROVED** [review]

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
I want the radial menu back for RCD

**Review by JamieD1 — APPROVED** [review]
Looks good, Baiomu thinks the tgui looks like "poo poo shit shit" so he probably wants the radial menu back.

**Comment by iamthesilly** [comment]
> I want the radial menu back for RCD

Radial menus don't show up if you're inside a mech or anything else that isn't a turf, it has to be tgui for now until that gets fixed.

**Comment by ShoziOffical** [comment]
you know on CM where the mechs can carry heavy structures, i want that

**Comment by ofscarletdreams** [comment]
a mech mounted health analyzer that can scan at range would be cool

**Comment by wonderinghost** [comment]
It be interesting if mechs could discharge into the station net if they got the portable or wireless charger

**Comment by JamieD1** [comment]
> > I want the radial menu back for RCD
> 
> Radial menus don't show up if you're inside a mech or anything else that isn't a turf, it has to be tgui for now until that gets fixed.

Alright, im happy if @ToasterBiome Is, do we know if fixing the radial menu is on anyones todo list?

**Review by ToasterBiome — APPROVED** [review]
tenor

stupid ass rcd tgui menu I HATE IT

**Comment by ShoziOffical** [comment]
> > I want the radial menu back for RCD
> 
> Radial menus don't show up if you're inside a mech or anything else that isn't a turf, it has to be tgui for now until that gets fixed.

https://github.com/yogstation13/Yogstation/pull/21407

Good job with this now dew it

**Comment by Hislyna** [comment]
Wait so how does the mime mechs RCD work then?

**Comment by iamthesilly** [comment]
> Wait so how does the mime mechs RCD work then?

The same way handheld RCDs work, but silently

**Comment by Hislyna** [comment]
> > Wait so how does the mime mechs RCD work then?
> 
> The same way handheld RCDs work, but silently

Wait so why does this one specifically need to use TGUI and not the Mime Mech? (Unless mime mech does and i derping)

**Comment by wonderinghost** [comment]
> Wait so why does this one specifically need to use TGUI and not the Mime Mech? (Unless mime mech does and i derping)

Because the page hasn't updated yet. Supposedly the bubbles will work for both rcd types for the mechs

**Comment by iamthesilly** [comment]
> Wait so why does this one specifically need to use TGUI and not the Mime Mech? (Unless mime mech does and i derping)

Both use it

**Comment by wonderinghost** [comment]
Real

**Pull request merged**
