### PR TITLE
hey guys it's adam again i decided to remove some content 

### PR DESCRIPTION
**Pull request by ghost**
specifically i decided to get rid of methspeed light pink extracts for you

instead they double down on the ambulance feature by adding some saline glucose for very very slow healing and slight blood replacement for anyone in crit around them

it's not going to save anyone severely injured but it'll provide mild healing enough to keep people fluctuating at -5 to 5 hp OK and avoids letting them die to bloodloss quite as easily

:cl:  
tweak: light pink slime stabilized extracts no longer grant you methspeed, and instead is slightly better at helping keep critted people alive. watch xenobiologists never make this again because they're all selfish bastards.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
you can't thumbs down my PR trustback you haven't responded to any of my funny soundclouds

**Comment by Oakboscage** [comment]
powergamers on suicide watch, now watch Alexkar yeet my on topic comment for being off topic

**Comment by Saratoubi** [comment]
Can't we keep a little of the speed? That was the main point of making them anyway. If you remove the speed NO one will make them. Or could something else give speed instead?

**Comment by Oakboscage** [comment]
> Can't we keep a little of the speed? That was the main point of making them anyway. If you remove the speed NO one will make them. Or could something else give speed instead?

No

**Comment by ghost** [comment]
>no one will make them

🆑
tweak: light pink slime stabilized extracts no longer grant you methspeed, and instead is slightly better at helping keep critted people alive. watch xenobiologists never make this again because they're all selfish bastards.
/🆑

**Comment by yacabo** [comment]
Yeah, a bit of a speed up would be nice but priority of making it not sanic speed

**Comment by ghost** [comment]
🆑
tweak: selfish bastards.
/🆑

**Comment by Nickvr628** [comment]
"I died remove this feature please"

Imagine making pink slimes just to get slightly better epi pens.

**Comment by ghost** [comment]
well frankly the main reason it's not cool is because chemistry can't get permanent methspeed without side effects from, well, meth, but for ten minutes of effort xeno can

we could give it a little speedup, but, like, why

**Comment by Oakboscage** [comment]
> "I died remove this feature please"

He literally can't even play on this server you absolute spastic

**Comment by MonsWTF** [comment]
Going to the design documents for each of the crossbreed trees, the Stabilized Light Pink was: 
"Holder moves slightly faster. Nearby (not the holder) are stabilized in crit."

As far as I could understand from Fel, the person who pretty much made Crossbreeding, the intention is supposed to be faster paramedics/mobile doctors dragging victims back to Medbay. Obviously -1 is a hell of a lot more than "slightly faster". 

The only circumstance I'm thinking where it could/should give a speed boost is if the person is actually holding onto a dying (NOT dead) body, to drag them to medbay faster? ...But I feel like with that kind of narrow condition, we'll see people dragging dying bodies around just to get that -0.3 or whatever speed boost out of it.

Implemented as-is, or with the conditional speed boost, this is still the best Xenobio PR we've had to tackle the powergamers in it.

**Comment by Ratvar** [comment]
Lemme explain why conditional speed boost is bad:
Xenobio stuns a dude, beats him while pulling, gets faster as target is critted and gets away
And it would be also worse at treating multiple people at once

**Pull request merged**
