### PR TITLE
Adds round end sound "Rick Hentai"

### PR DESCRIPTION
**Pull request by Mr-Space**
The title should be clear enough

:cl:  
rscadd: New round end sounds  
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
are we talking uh, rick sanchez or some other rick.

**Comment by Mr-Space** [comment]
Check dev-public innit

**Comment by Nickvr628** [comment]
no it is bad

**Comment by ynot01** [comment]
can u include sound in here my scroll wheel doesn't deserve this abuse

**Comment by Mr-Space** [comment]
You can literally download it thru Files changed tab, ynot.

**Comment by ynot01** [comment]
ends abrubtly, doesn't even include the best part of the song

0/10

https://youtu.be/X-cfWM0BC_4 source for the curious

**Comment by Mr-Space** [comment]
It was made and shown to Oak to comply with rules, that's why it ends abruptly.

**Comment by Ludox235** [comment]
Yes but why?
It doesn't have anything to do with SS13 or anything that could apply to it

**Comment by Mr-Space** [comment]
Same goes for a couple other roundend sounds, that doesn't make sense

**Comment by Amelia0010** [comment]
image

**Pull request closed without merging**
