### PR TITLE
Adds plasma cutter to Miner Cyborg

### PR DESCRIPTION
**Pull request by JamieD1**
Add Advanced Plasma Cutter to cybords as an upgrade,

Same cost as normal advanced plasma cutter,

Tested but might need tweaks in future if its op

#### Changelog

:cl:  
rscadd: Added plasma cutter to mining cyborg

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
It has been discussed so many times that I’ve lost count. Borgs, in general, are very powerful. They can perform simpler tasks much more effective than humans (engiborgs perform actions faster, janiborgs are very robust at cleaning etc.), but as a counterweight, they can’t perform more advanced tasks and have to rely on humans for maintenance. 

Mining borgs already have access to a KA, which can be upgraded with AOE, and that is enough. It’s immune to storms, can’t be stunned/slowed by fauna and can cross lava after an upgrade. Do not push it further.

**Comment by athena413** [comment]
maybe

**Comment by Bibby0110** [comment]
I mirror what Pancakes said

**Comment by Xoxeyos** [comment]
Make it an upgrade!

**Comment by JamieD1** [comment]
> Make it an upgrade!

It is an upgrade, 

image

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
