### PR TITLE
Removes neurotoxin spit from the xeno organ kit

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Taser spit funy and balanced
Also fixes a typo
Documents an undocumented change in #11528

Review code before merging a PR please

# Wiki Documentation

Remove the neurotoxin spit from the kit

# Changelog

:cl:  nmajask
rscadd: Added the xeno organ kit
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Reduce the price to like 10 or 12 then.

**Comment by ynot01** [comment]
> Reduce the price to like 10 or 12 then.

Tell a maint to tell me to do it then, I personally don't care whether this kit exists or not, I just want the taser spit off it

**Review by adamsong — APPROVED** [review]
Code looks fine

**Comment by Iplayforss13** [comment]
Maybe just add more counters to it, like melting all items in hand first, has a cooldown, inflicts knockdown and stamina damage,

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
