### PR TITLE
Poly can now tolerate plasma in the air

### LINKED ISSUE #14251: polys plasma breathing
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: POLYS CANT BREATHE PLASMA ANYMORE... LITERALLY UNPLAYABLE (im not certain its a bug but i havent heard anything about it being a feature)

 Submitted by: witherc6 (429012660869136394)

### PR DESCRIPTION
**Pull request by Altoids1**
Uh... ? I guess? Jamie: Doesnt fix the stated PR -snip-

Poly still needs to breathe oxygen and not be on fire, so this isn't really a *huge* buff to the bird, but uh.. I don't know.

## Changelog
:cl: Altoids
tweak: Poly has been in Engineering for long enough that he now better withstands the effects of airborne plasma.
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
I think they meant Polysmorphs, but this is fine too.

**Comment by tattax** [comment]
it's related to how atmos handles breathing, so unless if you want to contribute to the testmerge directly i don't think you'd be able to get it fixesd

**Comment by MusselMain** [comment]
Finally, an update that successfully makes Poly more based then they already are, PERFECT!

**Comment by JamieD1** [comment]
Oh Altoids, you out of touch magnificent bastard.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
