### PR TITLE
Detectives can have a little special ammo, as a treat.

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Re-adds Iceblox and Gutterpunch as fully non-lethal ammo, under experimental ammo.

The issue seemed to be "detective validhunting bad" so i mean just remove the damage. They were 20 dmg rounds like thats crazy. Anyways now its zero.

# Why is this good for the game?

Cool utility items locked behind later game tech, and with no damage so it just causes its effects, allowing det's to be useful on alert levels above blue (60% of them)
# Testing

Not yet, but it will work ive done it 6 morbillion times before.

# Spriting

Not yet, im just re-suing the old ones tho.

# Wiki Documentation
I'm sure it wasn't removed in the first place.

# Changelog

:cl:  
rscadd: IceBlox + Gutterpunch are back (pretty much)
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
We actually have .38 frost, it’s literally just iceblox, does exactly the same thing. It got added to replace Iceblox when it was removed.

**Comment by MajManatee** [comment]
yeah I saw but its named worse

**Comment by azzzertyy** [comment]
could we get some roundstart? would be nice not to have to babysit dets as asimov

**Comment by MajManatee** [comment]
you dont deserve it roundstart

**Review by ToasterBiome — APPROVED** [review]
having interesting ammo influences you to shoot people, but we can try it

**Review by Moltijoe — APPROVED** [review]

**Comment by ToasterBiome** [comment]
Reopen with conflicts fixed

**Pull request closed without merging**
