### PR TITLE
Add extremely immersive sound when dropping metal pipe

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request

adds metal pipe falling sound when you drop or throw metal rods

- [ ] make it so placing rods on tables won't play the sound
- [ ] also make it have a cooldown

https://user-images.githubusercontent.com/23666142/212774745-0b5d01ac-ad0b-43ec-a8cb-c15d9f52e01e.mp4

# Spriting
n/a

# Wiki Documentation

n/a
# Changelog

:cl:  
soundadd: metalpipefalling.ogg plays when dropping a metal rod
/:cl:

### CODE REVIEW

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/82983051/212775298-f8077792-ee42-46b0-b6d8-2247d77cd861.mp4


Please for the love of god put a cooldown on the very spammable loud noise. My eardrums are bleeding.

**Comment by maxion12345** [comment]
> dreamseeker_Uy3x4F8IVj.mp4 
> Please for the love of god put a cooldown on the very spammable loud noise. My eardrums are bleeding.

ok

**Comment by ThatLing** [comment]
Can you make it louder?

**Comment by patpol4** [comment]
sad

**Pull request closed without merging**
