### PR TITLE
Makes IAA good (Spawn more IAA, No more TC, Anti-tampering dust implant)

### PR DESCRIPTION
**Pull request by ynot01**
# Why is this change good for the game?

The goal of this PR is ultimately to extend IAA rounds past greenshifting them 20 minutes into the round, which I see all too often. It only takes one player that knows what they're doing to rush every other IAA down and leave only themselves to hijack/martyr. Even worse, if they do that and then get killed by an actual-competent security team, there are no antags left in the round. Security now gets an incentive to confirm kills themselves instead of "letting them sort themselves out".

# Document the changes in your pull request

IAA now drop a "syndicate button" on death. Pressing this as a syndicate grants you **one item picked from 3 random items** and **spawns a new IAA** to further press on the gamemode. Security are expected to retrieve these buttons and keep them from IAA in order to minimize station chaos.

The newly created IAA should have a decently sized buffer to work with, as no one will have them as a target until *another* IAA dies and they get randomly picked.

Hijack/martyr is still possible if the IAA you kill is the last spawned. Creating a new IAA with this button will not take away your hijack/martyr but you will not receive any new targets for your pinpointer/objectives.

#

IAA dusting implants now activate automatically if attempted to be removed.

#

New reward is no longer 5TC, but instead a picked item (chosen from 3 random items) from the following list:
- /obj/item/storage/backpack/duffelbag/syndie/x4,
- /obj/item/storage/box/syndie_kit/throwing_weapons,
- /obj/item/gun/syringe/syndicate,
- /obj/item/pen/edagger,
- /obj/item/pen/sleepy,
- /obj/item/flashlight/emp,
- /obj/item/book/granter/crafting_recipe/weapons,
- /obj/item/clothing/shoes/chameleon/noslip/syndicate,
- /obj/item/storage/firstaid/tactical,
- /obj/item/clothing/shoes/airshoes,
- /obj/item/clothing/glasses/thermal/syndi,
- /obj/item/camera_bug,
- /obj/item/storage/box/syndie_kit/imp_radio,
- /obj/item/storage/box/syndie_kit/imp_uplink,
- /obj/item/clothing/gloves/krav_maga/combatglovesplus,
- /obj/item/reagent_containers/syringe/stimulants,
- /obj/item/storage/box/syndie_kit/imp_freedom,
- /obj/item/storage/belt/chameleon/syndicate,
- /obj/item/storage/belt/military/shadowcloak,
- /obj/item/grenade/syndieminibomb/concussion/frag,
- /obj/item/card/id/syndicate,
- /obj/item/storage/pill_bottle/gummies/omnizine

Identical to current contract kit random items, but with riot c20r removed

# Changelog

:cl:  
rscadd: Internal Affairs Agents now drop a special item on death. To get your kill reward as a syndicate, you must pick this item up and use it. Doing this spawns another Internal Affairs Agent.
tweak: Internal Affairs kill reward is now a random syndicate item instead of 5TC
tweak: Internal Affairs dusting implant now activates automatically if tampered with
bugfix: Internal Affairs dusting implant is now automatically removed (safely) when the antag status is removed
/:cl:

### CODE REVIEW

**Comment by DylonBR** [comment]
Why remove additional arm though?

**Comment by ynot01** [comment]
> Why remove additional arm though?

Ripe for abuse in IAA where additional TC is a factor. Even one additional arm and three eswords leaves you at a permanent 87.5% blockchance.

**Comment by UltraBigRat** [comment]
If you are blacklisting items, probably should exclude holoparasites too because as awesome as they are they define the iaa meta to the point everyone takes them when they are available on iaa.

**Comment by ynot01** [comment]
> If you are blacklisting items, probably should exclude holoparasites too because as awesome as they are they define the iaa meta to the point everyone takes them when they are available on iaa.

I do not think this is *necessary*, especially with https://github.com/yogstation13/Yogstation/pull/19324, but it can be considered as holoparasites are basically a straight upgrade from not having them; as they are fully autonomous you can essentially do your own thing while your holoparasite adds damage or uses abilities.

**Comment by wonderinghost** [comment]
Dude the 2 shot toolbox

**Comment by Yarinoi** [comment]
finally, no more iaa miners waiting in lavaland for their targets to get killed, now they actually have to do shit

**Comment by ynot01** [comment]
Additional arm has been restored

**Comment by Xoxeyos** [comment]
Might I suggest in addition to the current items to be obtained instead of TC;
/obj/item/storage/belt/military/shadowcloak
/obj/item/doorCharge
A frag grenade
/uplink_item/stealthy_tools/agent_card
/obj/item/reagent_containers/syringe/mulligan
Omnizine Gummy Bears

**Comment by ynot01** [comment]
> Might I suggest in addition to the current items to be obtained instead of TC; /obj/item/storage/belt/military/shadowcloak /obj/item/doorCharge A frag grenade /uplink_item/stealthy_tools/agent_card /obj/item/reagent_containers/syringe/mulligan Omnizine Gummy Bears

will add everything besides mulligan and door charge

**Comment by Marmio64** [comment]
having some way to partially pick your reward (like a selection of 3 random items) would be a lot better, since you can easily miss out on a reward by having already gotten the item previously or having purchased it. For example, you purchased a radio implant and after killing your first target your reward is... a radio implant.

**Comment by ynot01** [comment]
> having some way to partially pick your reward (like a selection of 3 random items) would be a lot better, since you can easily miss out on a reward by having already gotten the item previously or having purchased it. For example, you purchased a radio implant and after killing your first target your reward is... a radio implant.

Implemented

**Comment by ToasterBiome** [comment]
Seeing viability of infernal affairs

**Review by JohnFulpWillard — APPROVED** [review]

**Pull request merged**
