### PR TITLE
Makes brass skewers actually bad to step on

### PR DESCRIPTION
**Pull request by Mqiib**
# Document the changes in your pull request

Being stabbed on a brass skewer no longer makes you unclickable. Apparently this was intentional???
You have to actually click on the skewer itself to pull someone off, but can now freely stab them to shit without first destroying the skewer if that's more your style. Also stuns the stabee for 2 seconds (not very long, same stun as borgs) because they just got IMPALED which would reasonably knock the wind out of you. People running in, getting impaled, and then just freely shooting to death the nearby clockie who was all "HAHA I GOT YOU IN MY GIANT SPEAR KEBAB TRAP" is kind of dumb. Skewers are criminally underused anyways for how cool they are, and now this'll make them actually spooky scary and give you an incentive to NOT just ignore them while running in screaming and firing akimbo laser guns.

# Changelog

:cl:  

bugfix: Brass skewers no longer make the shishkebabbed mob unclickable by normal means
tweak: Brass skewers stun for 2 seconds upon skewerification

/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Won a clockie shift just spamming this on defense god bless miqribb

**Review by ToasterBiome — COMMENTED** [review]
has the mouse opacity been tested in-game

**Comment by Mqiib** [comment]
> has the mouse opacity been tested in-game

yeah I played with it and seems to work fine, you can click on the skewer itself to remove them rather than just anywhere on the tile.

**Review by ToasterBiome — APPROVED** [review]
sussy

**Pull request merged**
