### PR TITLE
Randomizes xenobio bridge

### PR DESCRIPTION
**Pull request by AsV9**
## Intent of your Pull Request
Basically makes it so that the bridge below xenobio in maints is loaded from a template.
Either you get the normal bridge, or you'll get one that is open to space and has external airlocks in it.

I'm probably eventually going to add more pseudorandom elements to maints, but that'll have to come in a different PR.

Balance thoughts: Well, it shouldn't fuck up anything massively, except you now need external airlock access to get across the space.. You should also be able to get over the space without dying provided you are at high HP when you make your attempt. I was able to do it, anyway. Other than that I think it's probably not a terrible idea to fragment maints a bit more and make them less of a backup hallway and more of a utility area.

Old bridge:
image

New exposed:
image

#### Changelog

:cl:  
rscadd: The bridge in maintenance below xenobiology is now sometimes open to space.
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Greytide nerf, I love it.

**Comment by SomeguyManperson** [comment]
This'll also deal some damage to people being moved through the disposals pipe

**Comment by HomocidlePancakes** [comment]
Greytide buff, love it

**Comment by yacabo** [comment]
Neat idea, but you really shouldn't need to have an EVA suit to repair a wire that doesn't lead to a sat.

**Comment by Hopekz** [comment]
Good change +1 . 
Looking forward to more random maintenance elements.

Can we also look in to putting reinforced windows in the 2 circled places or do you specifically want this area uncrossable without external airlock access or hacking?
I'm fine with hacking these airlocks in open space but I think an unintentional side-effect of this might be people trying to hack these or use them when they're shocked then die because of the stun you get in open space. 
image

Might actually just add to the risk of being in maints which I also like.
Actually this might be a good thing regardless if intended.

**Comment by Codeatmos** [comment]
RNG BAD,BUT YET,THIS CHANGE INTERESTING..

**Comment by fluffe9911** [comment]
Deja vu

**Comment by HomocidlePancakes** [comment]
>This'll also deal some damage to people being moved through the disposals pipe

Disposals are not the intended to be a mean transportation

**Comment by AsV9** [comment]
@Hopekz I'll add some more windows to make it idiot proof today.

@SomeguyManperson I didn't actually think of that. I'll check how much damage you take in a moment.

EDIT: So I actually just figured out that the disposal line that runs across that bridge is actually the viro/xenobio disposal that goes straight to space. So if you're in that one without wearing a spacesuit in the first place, you're already in big trouble :))

**Comment by Bibby0110** [comment]
How do shadowmemes get past

**Comment by MegaEmpirical** [comment]
Go around obviously. That said, they're not simply in space so are they fine?

**Comment by Bibby0110** [comment]
Well they can't walk through walls in space.
There is no "going around" this is the only link without lights between Viro/medbay maint & science maint

**Comment by MegaEmpirical** [comment]
I never said there wouldn't be lights in the way.

**Comment by Bibby0110** [comment]
So this is a major debuff to shadowmemes, that don't have it easy already

**Comment by Hopekz** [comment]
> So this is a major debuff to shadowmemes, that don't have it easy already

After Asv adds the reinforced window to each side per my suggestion this should also as a side effect make shadowlings not nerfed. They'll just be able to cross as per normal then heal up any damage they might receive almost immediately after crossing to the other side through the broken windows.

**Comment by Moja10** [comment]
You should add the shutters with a button to open and close the area to space like it is on Metastation maint, to the west of brig, that way people have the choice to open and close it to space

**Comment by MegaEmpirical** [comment]
Doesn't it start open on meta? I always thought it was kind of redundant.

**Comment by AsV9** [comment]
> So this is a major debuff to shadowmemes, that don't have it easy already

@TheGamerdk Shadowlings get past if they use veil to knock out the rightmost lightbulb. They take like very marginal damage which is nearly instantly healed when they get back into the darkness, so it's actually more like a minor buff to shadowlings.

@Hopekz The windows are in place.

**Comment by Darkstick** [comment]
Seems like an inconvenience for the sake of it. Makes escaping via maint harder and helps murderers with fast and convenient spacing using medbay maint, with the catwalks and what not.

**Comment by Darkstick** [comment]
> Doesn't it start open on meta? I always thought it was kind of redundant.

Nah, they start closed. I walked through them often, it's usually pressurized.

**Comment by Hopekz** [comment]
> @Hopekz The windows are in place.

Don't forget to update your PR original post screenshot so that the discussions can reflect on it being different.

**Comment by Lostlarry** [comment]
also the bridge is visible from the xeno south cam so ask AI about it if can't be bother to go back for a hard suit

**Comment by Nickvr628** [comment]
Not sure I like it. That is a critical path for a lot of antags (ESPECIALLY shadowlings) who now cannot traverse that section of the station without using the main halls.

**Comment by AsV9** [comment]
I swear to fucking god @Nickvr628

**Pull request merged**
