### PR TITLE
MK.II SWAT mask

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

Introduces a new mask, currently only for deathsquad
This mask puts a new language on the user while equipped, Encrypted, and removes every other language (due to trying to decrypt the other languages), while hiding the user's true voice
When the user talks through the mask in this way, they will emit 1 of 27 garbled chatter sounds

https://youtu.be/zcFq586YSJ4
**tested, working 100%**

### Why is this change good for the game?

Encrypted deathsquad chatter, coolness factor, creepy factor, counterpart to codespeak?

# Changelog

:cl:  
rscadd: Added a new mask that encrypts your voice so that only others with the mask can understand you
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
@ynot01 can you post a sample audio pls

**Comment by swissloaf** [comment]
wait nvm you really used hl2 cp voices

**Comment by alexkar598** [comment]
Licensing will be an issue here.

**Comment by ynot01** [comment]
> Licensing will be an issue here.

i marked this draft because i was going to add battlefront 2 voicelines as another mask, let me know now if this is unmergable

**Comment by alexkar598** [comment]
> rips assets of a commercial game

Oh wait i cant do that, lemme rip off the assets of another commercial game.

You'd need to find something compatible under creative commons or whatever were using rn

**Comment by JamieD1** [comment]
Please confirm these are fine within our github license otherwise it cannot be merged.

**Comment by Cartlord** [comment]
We already use sounds from Half-Life 2 (Combine death sound, heard it in fights with Sec), why is Combine chatter bad?

**Comment by ynot01** [comment]
no more combine make everybody hapy

**Comment by Cartlord** [comment]
I mean, Combine voices are clearly already OK, given that Sec officers make Combine death noises when killed (in my experience).

**Comment by ynot01** [comment]
> I mean, Combine voices are clearly already OK, given that Sec officers make Combine death noises when killed (in my experience). 

i heard something about valve being cool about stuff but being that i dont know i removed them

if anyone knows more on this subject id love to use them

**Comment by Cartlord** [comment]
I will admit that I myself am somewhat unsure, because Valve uses a lot of stock sounds - so the Combine death noise COULD be a stock sound, while the Combine chatter could be something they made in-house; that would explain the disrepancy if true, but I don't have anything to back up either of those specific sounds being Valve-owned or stock.

**Review by JamieD1 — APPROVED** [review]

**Comment by Sniblet** [comment]
These sound a lot more aggressive and unintelligible than the combine lines were anyway, pretty cool

**Pull request merged**
