### PR TITLE
Adds new outfit for mimes to use to the theater drobe

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

This adds the REALLY sexy mime outfit (byond wont let me put 2sexy2mime)

# Why is this good for the game?

more variety

# Testing

image

# Spriting

image
image

# Wiki Documentation

add "really sexy mime outfit" to the wardobe

# Changelog

:cl:  
rscadd: Adds the REALLY sexy mime outfit to the theaterdrobe

/:cl:

### CODE REVIEW

**Comment by ofscarletdreams** [comment]
what is this a reference to

**Comment by cowbot92** [comment]
> what is this a reference to

ss13

**Review by BlueishTsunami — APPROVED** [review]
Hot

**Review by Moltijoe — APPROVED** [review]
Banned for enterprise resource planning

**Pull request merged**
