### PR TITLE
Adds cosmic ruin from before rebase

### PR DESCRIPTION
**Pull request by Ktlwjec**
Not exactly the same, removed a few things for balance reasons, would appreciate someone giving this a look through to see if I missed anything.

:cl:  
rscadd: The cosmic ashwalker ruin is much bigger.
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
why?

**Comment by ThatLing** [comment]
didnt mean to close it, misclick

**Comment by Kmc2000** [comment]
Map pr with no pictures

**Comment by Ktlwjec** [comment]
the small current one makes me cry that's why

**Comment by ThatLing** [comment]
@Kmc2000 
https://github.com/yogstation13/Yogstation-TG/pull/5542/checks?check_run_id=136525406

**Comment by HomocidlePancakes** [comment]
You should remove the crashed UFO ruins. They are pretty much redundant now.

**Comment by Lynameep** [comment]
I was thinking about adding this back myself but you beat me to it!

**Pull request merged**
