### PR TITLE
Disallows NTSL translation between languages that aren't common, draconic or machine.

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

i hate ntsl language

# Wiki Documentation

# Changelog

:cl:   
rscdel: NTSL can only translate to and from common, draconic and machine.
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
why draconic, why not british, japanese, or monkey?

**Comment by Bibby0110** [comment]
> why draconic, why not british, japanese, or monkey?

because the above 3 languages were the ones established in #9393

**Comment by Bibby0110** [comment]
i dont want to make this work

**Comment by Sniblet** [comment]
isn't the problem just that you said allowed_translation instead of allowed_translations

**Pull request closed without merging**
