### PR TITLE
fixes icy veins being terrible

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
bugfix: Icy veins will no longer get you to -200 KELVIN
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
Like actually lower than absolute zero?

**Comment by SomeguyManperson** [comment]
yes

**Comment by MegaEmpirical** [comment]
I think cyro sting did this too soemtimes

**Comment by SomeguyManperson** [comment]
Cryo sting just adds an ungodly amount of frost oil which if I'm right isn't the problem since you can only be reduced to 50 kelvin from it unless things don't work as intended

**Pull request merged**
