### PR TITLE
syringe gun is back

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

syringe gun is back

Most problem chemicals were resolved and i want to find the rest. Particularly explosions no longer triggering in tge body
# Spriting

# Wiki Documentation

syringe gun is back
# Changelog

:cl:  
rscadd: syringe gun is back
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
More rationale present than most prs you can remove the label

**Comment by solwashere** [comment]
This is technically a revert so only Jamie or Biome can touch it

**Comment by Moltijoe** [comment]
I like syringe guns in theory, but so long as they can be used to turbo kill people i worry about giving them to civilians

**Comment by Moja10** [comment]
95% of problematic syringe gun use has been removed, theos is right. Whatever is left can be tweaked after

**Comment by hwseo7** [comment]
We should nerf last 5% (bath salt) and this should be good to go I guess

**Review by Moltijoe — CHANGES_REQUESTED** [review]
revert the change to the uplink as well please

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
