### PR TITLE
MASSIVELY BUFFS MINERS BY MAKING STUFFED LEGION HAVE 5 VITAMINS INSTEAD OF 3

### PR DESCRIPTION
**Pull request by SomeguyManperson**
### Intent of your Pull Request

see title

### Why is this good for the game?

more reason to make processed foods = good

#### Changelog

:cl:  
tweak: stuffed legion now has 5 vitamins when crafted up from 3
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
MINNMGG POWERGMAE BASD!11!!!1 WTF IS RRWRONG WIT U

**Comment by Hopekz** [comment]
Who is going to stop this Theos guy

**Comment by Mesalikepie** [comment]
WOW BUFFING YOUR MAIN!!! ADMEMES PLEZE NERF THIS MAN!!!

**Review by redmoogle — APPROVED** [review]
No need to test this, plus seems like a good change to make processed foods relevant.

**Pull request merged**
