### PR TITLE
Half of snowdin to random space ruin

### PR DESCRIPTION
**Pull request by Readystorm546**
Alright this map is fucking massive and i cant screenshot it but just know its half of the original map snowdin. Some guy on discord requested i do this map so i did. Its got alot of loot for space explorers and im sure they will love it.

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
>inb4 this gets removed a month later because It was abused

**Comment by Amelia0010** [comment]
\>I can't screenshot it

**Comment by Readystorm546** [comment]
image
 
Its big okay

**Comment by Amelia0010** [comment]
mane you must've had to open it in some visual map editor, which you could just screenshot, right?

**Comment by Readystorm546** [comment]
Yeah but the map is so huge it does not fit on my screen

**Comment by Amelia0010** [comment]
s o t a k e m u l t i p l e p i c t u r e s i n n i t

**Comment by Readystorm546** [comment]
i d o n t t h i n k y o u u n d e r s t a n d

**Comment by Readystorm546** [comment]
image

image

image

image

image

I had to merge old folders so this is not the up to date version but all that changed was i removed the away portal and i added 4 entrances to the top of the map

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
1) why did you rename _maps/RandomZLevels/snowdin.dmm to _maps/RandomZLevels/snowdin(old).dmm?

2) This doesn't really fit very well with the *general theme* of space ruins, that being that they're at least kinda spacey. This is just a giant lump of snow randomly that was originally made to fill up an entire z-level

3) away missions were originally disabled because they're just random large off-station Z-levels with a bunch of loot which just serve to take people away from the station (before kojuh asks, yes that is also exactly what mining is, and no I don't like that either), adding a literal copy of one back into the game as a space ruin is pretty much just circumventing that decision

4) For the love of god just use fastDMM to take a screenshot

**Comment by Readystorm546** [comment]
1. The reason i changed it to old is because i only included half of snowdin and not the other half. no reason to get rid of the other half because someone might want to use it.
2. I agree with this
3. I also agree with this but for the love of god dont change mining the only reason its fun is because of ruins.
4. Dont know what this means but ill try and figure it out

**Pull request closed without merging**
