### PR TITLE
Removes the unmaintained Battle Royale gamemode

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

Half of the time this doesn't work, and when it works it's always messy. New areas aren't supported.
Nobody has made any effort to fix this in years

# Changelog

:cl:  
rscdel: Removed the Battle Royale gamemode
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
nooooooooooooooooooooooooooooo but my bus!!!

**Comment by Moja10** [comment]
Fix it 
smug

**Comment by Bibby0110** [comment]
> Fix it smug

no :)

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Ided + Hugbox

**Comment by solwashere** [comment]
Remember what they're taking from us

**Comment by MajManatee** [comment]
Remember kilo!!

**Comment by MajManatee** [comment]
Remember kilo!!

**Comment by ChuChu42** [comment]
you arent removing my adminbus

**Comment by MajManatee** [comment]
Improve dont remove

**Comment by ToasterBiome** [comment]
We can keep this in the game to entice people to fix it in the future.

**Comment by Bibby0110** [comment]
This PR is their enticement.

**Comment by ToasterBiome** [comment]
Head Developer says this is closed

**Comment by Bibby0110** [comment]
I would like confirmation from both Head developers.

**Comment by Moltijoe** [comment]
> I would like confirmation from both Head developers.

man's head dev fishing

**Comment by solwashere** [comment]
Bibby Moment

**Comment by Cartlord** [comment]
Im-prove, don't re-move.

**Comment by MajManatee** [comment]
its being maintained as we speak

**Comment by Moltijoe** [comment]
maintaining painfully in process, trust me

**Pull request closed without merging**
