### PR TITLE
Airlock scan

### PR DESCRIPTION
**Pull request by Lostlarry**
checking airlock access requirement without disassembling it. you have to attempt to open the door before it works properly.

I'll continue work on this and PR when i'm sure what i want to do with it
:cl:  
rscadd: adds airlock scanner for looking at airlock access requirements
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Resolves this: https://github.com/yogstation13/Yogstation-TG/issues/4584

**Comment by MegaEmpirical** [comment]
Will this work on buttons and windoors too?

**Comment by Lostlarry** [comment]
no its only airlocks but it could be modified to work on about anything

**Comment by MegaEmpirical** [comment]
Doooo it.

Por favor.

(Then rename it to Access Scanner)

**Comment by Bibby0110** [comment]
>show_accses
:)

**Comment by Lostlarry** [comment]
you sure about that? you want to accidentally click a wall and see that it needs no access?

**Comment by MegaEmpirical** [comment]
I meant more like add windoor and button support, but if it also does walls and shit, I'm fine with that. Means you won't have to update it to work on other things at least (should we think of something else or something get added).

**Comment by Lostlarry** [comment]
well the thing is req_access and req_one_access which are the variables that i read and output are inherent to obj class. that means machinery, mechs, items turfs(so even space), structures (grilles and such). the problem is most of these don't use this feature at all so i'd have to remove the static somehow which would be messy af.
that's assuming i find a way to get the airlock scan file past travis. i may end up throwing it to airlock painter.

**Comment by AsV9** [comment]
Fuckin fatfingered that

**Comment by ThatLing** [comment]
@AsV9 meanie

**Comment by MegaEmpirical** [comment]
You monsters.

**Pull request closed without merging**
