### PR TITLE
Makes hacked lawboards unavailable if you need to destroy the AI

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

#"¤!%%#: Destroy yourself

#### Changelog

:cl:  
tweak: You can no longer buy the experimental lawboard if you need to destroy the AI
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
lame

**Comment by Amelia0010** [comment]
>lame

So is writing a single sentence and getting the AI to off itself :^)

**Comment by Nickvr628** [comment]
Seems like someone is salty.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
image

**Comment by Nickvr628** [comment]
Nich seems to think it is an “I Win” button, when it is far from it. It takes up valuable TC for exclusively one objective, when you have two other to buy stuff for, and you still need an upload console to use it. 

To quote a disgusting furry, “should we remove the revolver because it is a two click win button for kill objectives?”

This is a reactionary change to salt, and should be closed.

**Comment by Nickvr628** [comment]
Also the upload board costs 14 TC, if you are willing to dedicate almost 75% of your TC for completing a single objective (out of two or three), I think it is fine that you get an effective tool to do the job.

**Comment by fluffe9911** [comment]
The floor is salt the walls are salt even the air is salt

**Comment by Ratvar** [comment]
Not just using a freeform after asking what laws AI has.
Not wasting 14 TK on a chance of malf AI knowing you are a traitor trying to fuck it over.
Not asking emagged borg to off AI's APC and beat it with wrench.
Not getting an AI that announces that it's about to die and giving everyone full instruction to repairs.
Lame PR, remove nich, hacked AI board is weak and too random.

**Comment by MacHac** [comment]
14 TC is a lot of TC.  For 11, you can bomb the AI, which is similarly shitty and uncounterable but also near guarantees a shuttle call and lots of chaos.  For 6 (soon to be 8 if nich nerfs the thing) TC, you can emag a borg and have it go beat the AI to death with a wrench.

Most of the ways to kill someone in this game are shitty and uncounterable.  If you're subverting an AI to kill itself, you still have to go to the trouble of getting an upload board, and building the computer without catching a flashbang in the teeth.  That's frankly more effort than most murders take.

If we're going to do this, we might as well remove everything else that can get objectives done low-effort.  
Steal objective?  No emag for you!
Gotta murder someone?  Revolvers and sleepy pens are too easy!  
Marooning someone?  Why do you need an ebow, you bad?  Winning that objective should be more difficult than making two mouse clicks!

Or, alternately, we can avoid making up arbitrary special rules as a kneejerk way to counter a very specific and perfectly reasonable tactic that we're salty about.  

As it stands, short of thermiting into the AI core high on meth and beating it to death with a toolbox, any method of killing the AI is going to be a little bit of setup work followed by a low effort bullshit killing.  Compared to the other ways of killing the AI that currently stand (bombing, emag a borg), buying a lawboard is actually a waste of telecrystals.

**Comment by Amelia0010** [comment]
>For 11, you can bomb the AI, which is similarly shitty and uncounterable but also near guarantees a shuttle call and lots of chaos.

If you use the syndicate bomb, and place it inside the bridge maint (considering that's the closest you can get without going inside the bridge, where a bomb would be immensely obvious) you can't kill the AI:

image

>For 6 (soon to be 8 if nich nerfs the thing) TC, you can emag a borg and have it go beat the AI to death with a wrench.

And during the wrenching, the AI is able to yell that said borg is beating it with a wrench, and that it was emagged, something it isn't able to do if it gets a law saying "suicide immediately, without telling anyone"

>Most of the ways to kill someone in this game are shitty and uncounterable.

What a great reason not to remove shitty and uncounterable ways to kill someone. And regardless, most other ways you actually get to be murdered, or get a chance to potentially fight back. You don't get that if you just have to suicide because a person on the opposite side of the station, in one of the 25 maint rooms told you to.

>you still have to go to the trouble of getting an upload board, and building the computer without catching a flashbang in the teeth.

This really isn't hard at all. It's hacking into 1 unsecure place, then hacking into maint if you don't already have access.

>Steal objective? No emag for you!

Most steal objectives are either something that is carried by a person (IE hypospray or blueprints) or it's in a secure area (IE ablative vest or captain's laser), so just emagging in and taking it is a surefire way to get caught.

>Gotta murder someone? Revolvers and sleepy pens are too easy!

As stated above, this gives you an ability to fight back. with sleepy pens they have time where they can PDA people they were sleepy penned, with the revolver you have potential disarm spam/fighting back if you have a weapon yourself.

>Marooning someone? Why do you need an ebow, you bad? Winning that objective should be more difficult than making two mouse clicks!

See above statement about the ability to fight back.

>perfectly reasonable tactic

It's really not.

>that we're salty about.

Why do you retards keep saying i'm salty when this has never happened to me?

>any method of killing the AI is going to be a little bit of setup work followed by a low effort bullshit killing.  

Which is a bad thing.

>Compared to the other ways of killing the AI that currently stand (bombing, emag a borg), buying a lawboard is actually a waste of telecrystals.

Ok so it's shit to the AI, and it's a waste for the user, why should they get it then? Every other method requires more interaction, which is better for both the AI and the traitor.

**Comment by Ratvar** [comment]
If you are really opposed to idea of forced AI suicide - let AI outright ignore such laws in _rules_?
Like, you know, anyone might try to suicide AI with or without using hacked lawboard.
On any round, antag or not, destroy AI objective or not, with various reasons. This one PR just bandaides one little hole without fixing the problem you might have with idea itself.
Oor you can do fancy upload law redux PR or something, but _heh_.

**Pull request closed without merging**
