### PR TITLE
Readds Turn the Lights Off by Tally Hall

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request
We had this song once but it got removed by swiss cause ident didnt like it but I still think its a good song that really fits well with ss13
:cl:  
rscadd: Readded Turn the Lights Off to lobby music
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
great song

**Review by Partheo — CHANGES_REQUESTED** [review]
Sounds kinda cringe honestly. I don't see how this relates to SS13 at all. It's also takes a lot of room as a lobby song.

**Comment by MrHorizons** [comment]
I think a good compromise would be to add it as a Halloween lobby song.

**Review by JamieD1 — APPROVED** [review]
Seems ok, maybe as a halloween song, but im for it either way, More variety is always good.

**Comment by Mqiib** [comment]
This song makes happy ss13 round end memories bubble back up, please bring it back :)

**Review by Partheo — APPROVED** [review]

**Pull request merged**
