### PR TITLE
resprites molten nougant

### PR DESCRIPTION
**Pull request by Potototatoh**
Screenshot (2412)

alters the mosin nagant sprite to be slightly chunkier

# Changelog

:cl:  
imageadd: resprites mosin nagant 
imagedel: resprites mosin nagant 
/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
This resprite is in no way approvable, I highly beg you to join the yogstation discord so I can help you with your future PRs before you push them out.

**Comment by cuackles** [comment]
ok now for an actual review

**Review by cuackles — CHANGES_REQUESTED** [review]
mosin
so the diference is clear the old sprite is more rough and dark with a less defined outline, the new sprite on the other hand has a more defined shape and a more pleasant view, i would like to see if you can turn the outlines that look a bit to green for my liking into more of a brown outline, and maybe add a bit more contrast overall to the colors on the gun, apart from that i see no issue with the gun and as it is its already better that the one we have but i would like to see how it looks with said changes

**Comment by Potototatoh** [comment]
okay i guess the only other thing is figuring out how to edit files mid-pr also the merging thing wasnt intentional and i dont know how to undo that if it does anything

**Comment by JamieD1** [comment]
Fine when issues are fixed

**Comment by Potototatoh** [comment]
i dont know how to edit prs im stupid ill just make another one with the new sprites

**Pull request closed without merging**
