### PR TITLE
Strength Makes You Strongerer

### PR DESCRIPTION
**Pull request by Mqiib**
# Document the changes in your pull request

The strength mutation now also gives you +1 punch damage, increasing to +2 with a power chromosome. This means you can live out your dreams as a professional boxer or something through genetic doping and rule the ring (on average).
Credit to @Chubbygummibear for the idea!

# Wiki Documentation
 
Include in mutations page that it increases your punch damage slightly.

# Changelog

:cl:  
rscadd: The strength mutation now also makes you punch harder, because you're strong!
bugfix: Removed superfluous variables that I forgot to delete like a year ago from thick skin
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Fun fact this is a martial arts buff

**Comment by Mqiib** [comment]
Ok it actually works now I promise

**Comment by Chubbygummibear** [comment]
didn't even credit me for my idea i h8 you 😠 😠 😠 😠 😠 😠

**Comment by stwordcitizen** [comment]
genetics buff 🤮

**Comment by Mqiib** [comment]
> didn't even credit me for my idea i h8 you 😠 😠 😠 😠 😠 😠

I'm sorry, I fixed it don't yell at me D:

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
