### PR TITLE
Shields now give 0.2 slowdown

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

If you have used the adamantine shield, this is how much slowdown it has as well

# Changelog

:cl:  
tweak: All handheld shields now have slowdown
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
I think this is actually a pretty clever nerf to shields without nuking their usefulness

**Comment by ynot01** [comment]
Credit to hisakaki, i couldnt think of a reasonable nerf myself

**Comment by Hislyna** [comment]
That rare moment where my shit takes actually bare fruit

**Comment by TheRyeGuyWhoWillNowDie** [comment]
0.4 or go home

**Comment by ynot01** [comment]
0.2 is a good point for me, MAYBE 0.25

**Comment by DukeBobRoss** [comment]
Could shields go back to 100% block chance in exchange for a worse slowdown?
randomness in combat really sucks

**Comment by ynot01** [comment]
> Could shields go back to 100% block chance

image

**Comment by Simplehorror** [comment]
this kills shields. i would not take a 100% block chance shield for 0.2 slowdown seeing how slow we already are, being slower than your opponent is how you lose a fight

**Comment by TheRyeGuyWhoWillNowDie** [comment]
we literally just had this fucking simplehorror shitpost comment will you leave the github alone

**Review by Moltijoe — CHANGES_REQUESTED** [review]
needs
item_flags = SLOWS_WHILE_IN_HAND

**Review by Moltijoe — APPROVED** [review]
Looks good, can't say anything about balance though

**Pull request merged**
