### PR TITLE
Makes wooden barricades disassemblable

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

You can now disassemble wooden barricades with a crowbar(takes ~10 seconds)

#### Changelog

:cl:  
tweak: You can now disassemble wooden barricades with a crowbar 
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
isnt the whole point of the barricades to make an obstacle that you have to destroy to get through?

**Comment by redmoogle** [comment]
> 
> 
> isnt the whole point of the barricades to make an obstacle that you have to destroy to get through?

I mean yeah true, but they also turn into walls, so this is just to make getting rid of them easier

**Comment by boodaliboo** [comment]
24 seconds is a reasonable time especially for its goal which is a barricade

**Comment by redmoogle** [comment]
I remembered it from some codebase, couldnt hunt it back down so I had to come up with my own time

**Comment by Marmio64** [comment]
> I remembered it from some codebase, couldnt hunt it back down so I had to come up with my own time

paradise had barricades removable with a crowbar. Took like 10 seconds.

**Comment by Jarod1200** [comment]
24 seconds sounds good.

**Comment by Hopekz** [comment]
A good feature that I felt was missing but 24 seconds is a long time.
Could easily turn in to almost a full minute with lag and time dilation.

Just make it the same amount of time as beating a barricade with the tool so you have both options as basically flavortext on how you want to take it down

**Comment by redmoogle** [comment]
> 
> 
> A good feature that I felt was missing but 24 seconds is a long time.
> Could easily turn in to almost a full minute with lag and time dilation.
> 
> Just make it the same amount of time as beating a barricade with the tool so you have both options as basically flavortext on how you want to take it down

should be somewhere around 10s now, tooldelay is weird, it doesnt seem to be in any semi-standard unit of time

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
