### PR TITLE
Adds new player friendly to the server title

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Maybe it will attract more players

#### Changelog

:cl:  
  
tweak: changes hub line
/:cl:

### CODE REVIEW

**Comment by Firewolf34** [comment]
I dunno about this. Keep the newbies on Beestation until they can learn the game, then send em our way, imho.

But maybe I'm just a sour old git being judgmental...

**Comment by swissloaf** [comment]
> I dunno about this. Keep the newbies on Beestation until they can learn the game, then send em our way, imho.
> 
> But maybe I'm just a sour old git being judgmental...

we get newbies too, its not that bad. of course, there are some shitters, but most learn the game and actually stay. it would be nice for us to have some fresh faces and also pop increase

**Comment by Bibby0110** [comment]
Newbies stay at the server they started on

**Review by SomeguyManperson — APPROVED** [review]
yes

**Comment by GenericDM** [comment]
port lag

**Comment by ShadowDeath6** [comment]
why put a lie in the server title

**Pull request merged**
