### PR TITLE
Adds a few more berets

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Adds chemistry beret, research director beret, and head of personnel beret.

# Spriting

image

# Changelog

:cl:  
rscadd: adds chemistry, research director, and head of personnel berets
/:cl:

### CODE REVIEW

**Review by cuackles — CHANGES_REQUESTED** [review]
rd one looks good in item form, sadly the other 2 do not match the quality of rd one, hops lacks a bit of the gradient in colors that the rd one has it just jumps from light to dark and the red thingy doesn't seem to have the details, the chemistry one looks like it was passed thru a paper shredder, checking the file i just noticed that there are a few berets that look like they where ran over so i would say just pallete swap the rd one with white for a more solid look, or the ce one that is already white

**Comment by cuackles** [comment]
oh god we have so many berets why do mostly of them look so diferent waaaaaaaaaaaaaaaaaaaaaaa

**Comment by iamthesilly** [comment]
image
is this better?

**Comment by cuackles** [comment]
Yes i like that a lot more

**Review by cuackles — APPROVED** [review]

**Pull request merged**
