### PR TITLE
More turtlenecks!!

### PR DESCRIPTION
**Pull request by Mqiib**
Adds turtlenecks and skirtlenecks for cargo (QM and cargo tech):

image

And for CMO:

image

Very fabulous. These sprites were as of yet unused because I forgot to add them.

Edit: and also hop versions

:cl: Mqiib, @Ebin-Halcyon 

imageadd: Added new turtlenecks for cargo, CMO, and HoP!

/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
but can they be adjusted like other turtlenecks?

also where hop turtleneck :(

**Review by SapphicOverload — CHANGES_REQUESTED** [review]
Your changelog is missing

**Comment by kooarbiter** [comment]
I think cargo techs should be forced to wear shorts so the QM can express dominance by having pants

**Comment by Mqiib** [comment]
> but can they be adjusted like other turtlenecks?
> 
> also where hop turtleneck :(

yes and I just added it, thank you for reminding me

**Review by SapphicOverload — APPROVED** [review]
I forgor

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
