### PR TITLE
adds magmite crusher to the things you can make at the world anvil

### PR DESCRIPTION
**Pull request by LazennG**
# Document the changes in your pull request

adds the magmite crusher, which is pretty much the same thing as the original but it shoots orange bolts instead of blue and cuts through rocks like a plasma cutter

# Spriting
image

# Wiki Documentation
https://wiki.yogstation.net/wiki/Shaft_Miner#The_Wonders_of_Plasma_Magmite
image The Mega Proto-Kinetic Crusher: Functions identically to a normal crusher but additionally cuts through rocks similar to plasma cutters.

# Changelog

:cl:  @ToasterBiome , @Chubbygummibear 
rscadd: Added magmite crusher
imageadd: added magmite crusher icon
/:cl:
thanks to baiomu for spriting literally everything and chubby for coding everything

### CODE REVIEW

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
The animation and the sprite overall could use some more development. The full maxed out white heavily works against everything on it and when it goes through the animation looks like one big swore thumb and in no way feels fluid. shading is very inconsistant throughout the sprite and the blade bit at some points has 4 layers of banding.

**Comment by KillerOrcaCora** [comment]
image

I'm sure everyone here will be very satisfied with the remake I did.

**Comment by ReddicusDragon** [comment]
> The animation and the sprite overall could use some more development. The full maxed out white heavily works against everything on it and when it goes through the animation looks like one big swore thumb and in no way feels fluid. shading is very inconsistant throughout the sprite and the blade bit at some points has 4 layers of banding.

as much as I hate to agree with Orca, I also think the animation looks a bit bad. I like the concept of the animated pulse but it doesn't feel fluid, it feels like half the blade changes then a split second later the rest of the head changes.

**Comment by Moltijoe** [comment]
also if the crusher is supposed to be a hammer, then the sprite should be tweaked to reflect that

**Comment by Mantlecrawler** [comment]
This seems preety damm weak for a magmite upgrade, by the time most miners are getting this its more than likely they already have a plasma cutter. Perhaps double the mark detonation damage for backstabs and normal detonations?

**Comment by LazennG** [comment]
> This seems preety damm weak for a magmite upgrade, by the time most miners are getting this its more than likely they already have a plasma cutter. Perhaps double the mark detonation damage for backstabs and normal detonations?

doubling the detonation damage would be ridiculously powerful, and it's not like cutters and kas get that type of boost from magmite pieces either. the magmite crusher was made because i think it's mildly annoying to drag the crusher around when cutters are unlocked and i wanted to cut out the middle man

**Comment by MajManatee** [comment]
This plus the potential one handed ability of the crusher would make it a million times better. Not having to get a spare item to mine and having to drag it around is game changing. 
also sprite looks cool idk what they are all on

**Review by MajManatee — APPROVED** [review]
probably epic, jamie you should merge this one

**Comment by ThatLing** [comment]
Balance council approved

**Review by JamieD1 — APPROVED** [review]
Good to merge when cuackles approves

**Comment by Moltijoe** [comment]
#17778 was merged so now you have a load of conflicts to deal with

**Comment by MajManatee** [comment]
@cuackles PLEASE bro

**Comment by cuackles** [comment]
> @cuackles PLEASE bro

IM STILL WAITING ON THEM TO UPDATE THE SPRITEEEE

**Review by cuackles — APPROVED** [review]
To not hold up this PR anymore biome PROMISED to get us the sprites when they come back from vacations or sumthing idk, so the changed sprites will be added with another or, so this goes in as a temporary placeholder ish sprite or sumthing idk

**Pull request merged**
