### PR TITLE
Nerfs curator whip to be less human combat oriented

### PR DESCRIPTION
**Pull request by alexkar598**
# how
- Damage reduced from 15 to 12
- Attacks on simple mobs deal 8 additional damage before armour reduction
- Disarm effect removed

# why
its a rather strong weapon that's still rather powerful even late game to be given roundstart to a non combat role. The simple mob damage encourages fighting NPCs which is pretty ok for a curator to do. With 12 damage, its still a weapon that does considerable damage.

# meme
watch players playing curator go to 0 because ive removed the only reason they play it lmao

:cl:  
rscadd: Curator whip does 8 additional damage on simple mobs
rscdel: Curator whip no longer guarantees an instant disarm
tweak: Curator whip damage decreased from 15 to 12
/:cl:

### CODE REVIEW

**Review by jcatjmeow — APPROVED** [review]

**Review by SomeguyManperson — APPROVED** [review]
validhunt curator mains crying and shaking and podding rn

**Comment by ghost** [comment]
bowek on suicide watch

**Comment by Marmio64** [comment]
bruh, how could you, how tf am i going to validhunt antags as curattor, wtf are you a antag sympathizer?/??????

**Comment by JamieD1** [comment]
Have you not seen indiana jones?

**Comment by alexkar598** [comment]
Haven't you seen Rambo? I should be able to murder the entire station with nothing but a pistol and my butt cheeks

aka since when are we balancing a game around movies

**Pull request merged**
