### PR TITLE
ports tgstation new mutation autotomy and changes olfactory

### PR DESCRIPTION
**Pull request by boodaliboo**
this new mutation allows a person to instantly discard a limb of there choice but doesnt allow them to reattach it but combined with ligament hooks its pretty cool

### Intent of your Pull Request
this new mutation allows a person to instantly discard a limb of there choice but doesnt allow them to reattach it but combined with ligament hooks its pretty cool and can be used to escape some deadly situations

now olfactorys ability is worst the more dirty you are and has diffrent messages depending on its level

#### Changelog
ported a mutation from tg
:cl:  /tg/station
rscadd: Added a new genetics perk, mutation autonomy, allowing you to pop your limbs off.
/:cl:

### CODE REVIEW

**Review by GenericDM — CHANGES_REQUESTED** [review]
Undocumented changes regarding olfactory mutation.

**Comment by boodaliboo** [comment]
i didnt realize that tg made any changes on it ill change the descrption to reflect this

**Comment by Firewolf34** [comment]
the changelog comment is extremely vague/default

**Comment by boodaliboo** [comment]
> the changelog comment is extremely vague/default

does it need to be more you can just read the descrption

**Comment by Amelia0010** [comment]
@boodaliboo I'm gonna need a link to the PR this is ported from.

**Comment by Ratvar** [comment]
I would like to say that mutation discards *random* limb for balance reasons, and boodaliboo incorrectly explained what mutation does.
https://github.com/tgstation/tgstation/pull/45988

**Pull request closed without merging**
