### PR TITLE
Fixes a stupid blindspot for AI on box

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# Document the changes in your pull request

Fixes a blind spot for AI on box station
image

# Wiki Documentation

None needed

# Changelog
:cl:  
rscadd: Camera Rearanged in box station's sci to fix blindspot for AI infront of door.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Imo it's good to have blind spots for the AI and imo we should probably add more

**Comment by JamieD1** [comment]
> Imo it's good to have blind spots for the AI and imo we should probably add more

Piss off, this has been a problem for years.

Thanks OP for fixing.

**Comment by bruhlookatthisdood** [comment]
> > Imo it's good to have blind spots for the AI and imo we should probably add more
> 
> Piss off, this has been a problem for years.
> 
> Thanks OP for fixing.

i got sick of people screaming at me to open door only to see that they were wanting out of sci.

**Review by patpol4 — APPROVED** [review]
Hopek is right imo but this specific place should be fixed

**Pull request merged**
