### PR TITLE
I love refridgerators

### PR DESCRIPTION
**Pull request by Amelia0010**
I 👏 LOVE 👏 REFRIDGERATORS

#### Changelog

:cl:  tgstation
mirrors galore
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Microwaves are better tho

**Comment by jcatjmeow** [comment]
*i love refrigerators

**Comment by Nickvr628** [comment]
atomize PRs pls ty

**Comment by Amelia0010** [comment]
I'm just gonna end up gitbanning you at this rate

**Pull request merged**
