### PR TITLE
TEST MERGE ONLY - ROUND 50K SYNDIE STATION AND DJ CHU SHIP

### PR DESCRIPTION
**Pull request by Addust**
# test merge only

syndifies the Gax (ORIGINAL WILL NOT BE ACCESSIBLE WHILE PR TM'D) and adds the DJ Chu ship to the shuttle manipulator

# Changelog

:cl:  
rscadd: SOMEONE FUCKED UP
rscadd: admins may now spawn DJ Chu's ship at will
rscadd: the gax is now syndicate because of this fuckup
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
image
kek

**Comment by N3D6** [comment]
This is gonna be so fucking cramped on gax

**Comment by ShoziOffical** [comment]
oh my god 40 people on gax

**Comment by Moltijoe** [comment]
Closed until its needed once more

**Pull request closed without merging**
