### PR TITLE
Fixes systematic discrimination

### PR DESCRIPTION
**Pull request by Bibby0110**
# Github documenting your Pull Request

# Wiki Documentation

### CODE REVIEW

**Review by adamsong — APPROVED** [review]

**Review by adamsong — APPROVED** [review]

**Review by JamieD1 — CHANGES_REQUESTED** [review]
wrong file

https://github.com/yogstation13/Yogstation/blob/master/html/templates/header.html

**Review by JamieD1 — CHANGES_REQUESTED** [review]
You dont need to update the changelog, bibby, pick a name. not three.

**Comment by Bibby0110** [comment]
> You dont need to update the changelog, bibby, pick a name. not three.

I have three names I pick 3 names

**Comment by JamieD1** [comment]
> > You dont need to update the changelog, bibby, pick a name. not three.
> 
> I have three names I pick 3 names
pick a Name or ill pick your github one.

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Pick one name bibby.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
