### PR TITLE
Adds The Penis

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

adds The Penis (Eek!) to the list of lobby songs

# Why is this good for the game?
variety 

# Changelog

:cl:  cark
soundadd: adds "The Penis (Eek!)" by Surasshu to the lobby music options.
/:cl:

### CODE REVIEW

**Comment by Beeper-Skeeper** [comment]
penis

**Comment by ShoziOffical** [comment]
penus

**Comment by Moltijoe** [comment]
i don't suppose there's a version of the song with a different name, is there?
the song is good, but i don't trust yoglodites

**Comment by JohnFulpWillard** [comment]
https://www.youtube.com/watch?v=g7q-OItcRfw

**Comment by neeshacark** [comment]
> i don't suppose there's a version of the song with a different name, is there? the song is good, but i don't trust yoglodites

nope you can only have The Penis (Eek!) there is no alternative

**Review by Moltijoe — APPROVED** [review]
Code checks out

**Pull request merged**
