### PR TITLE
Revert "[PORT] Examine Block"

### PR DESCRIPTION
**Pull request by ShadowDeath6**
Reverts yogstation13/Yogstation#15267

Original PR forgot to include a preference for the examine thing and it doesn't look very good

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
so add a preference

**Comment by adamsong** [comment]
People really do hate change

**Comment by ToasterBiome** [comment]
Not liking this "everything is a preference" movement

Also improve don't remove

**Comment by ShadowDeath6** [comment]
"everything is a preference" stems from adding graphical changes that people don't think looks good
the only way to improve this is to remove it or to add a pref so I guess I'll be adding a pref once I figure out how to do it

**Pull request closed without merging**
