### PR TITLE
Overhauls plasma cutter modding

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

# Will need to be balance tested

All mods are now available to all variants of the plasma cutter

image
image

# Why is this good for the game?
More customization

# Testing
Made sure negative mod capacity doesnt work

# Wiki Documentation
More upgrades

# Changelog
:cl:  
rscadd: PC Range Upgrade
rscadd: PC Cooldown Upgrade
bugfix: Vending machines not containing upgrades
tweak: All plasma cutters can be upgraded
tweak: Plasmacutters can be recharged with one click now
/:cl:

### CODE REVIEW

**Comment by GDRdev** [comment]
I dont know how much use this is gonna get since the upgraded plasma cutter is already pretty strong for mining

**Comment by redmoogle** [comment]
> I dont know how much use this is gonna get since the upgraded plasma cutter is already pretty strong for mining

this makes the adv ones upgradable :)

**Comment by ToasterBiome** [comment]
Should they still be called PS Upgrades?

**Comment by redmoogle** [comment]
> Should they still be called PS Upgrades?

That should be all changed

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
