### PR TITLE
readds random spellbook in lavaland wizard den for @vatavayu

### PR DESCRIPTION
**Pull request by boodaliboo**
readds spellbook in miners wizard den room, @VataVayu asked for this so blame him ultimately i dont care how this goes i dont really play miner a ton but i do think maybe a rework of the room in general to give less of some stuff and more of others.
but even though i dont really play miner much now i still know how bullshit this ruin was in difficulty, i feel like strong monsters that can oneshot you or nearly kill you instantly, should have a good reward

image

:cl:  
rscadd: readded spellbook to lavaland wizard ruin
tweak: readded spellbook to lavaland wizard ruin
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
in the end i do not care if this is merged or not but please leave legitmate critique alongside the thumbs down i feel like theirs some ways to rework it wheir everyone is happy. i just feel like high risk = high reward, i think the staff of healing ill problably remove then put the book in their

**Comment by Therandomhoboo** [comment]
> in the end i do not care if this is merged or not but please leave legitmate critique alongside the thumbs down i feel like theirs some ways to rework it wheir everyone is happy. i just feel like high risk = high reward, i think the staff of healing ill problably remove then put the book in their

Na

**Comment by 00ze-cyclone** [comment]
> in the end i do not care if this is merged or not but please leave legitmate critique alongside the thumbs down i feel like theirs some ways to rework it wheir everyone is happy. i just feel like high risk = high reward, i think the staff of healing ill problably remove then put the book in their

You don’t care for the PR so why should I care to give an explanation to what is obvious.

**Comment by MajManatee** [comment]
The book was always a random garbage spell like "smoke" or "light yourself on fire" which was fun. That being said this isn't a difficult ruin by any sense of the word.

**Comment by azzzertyy** [comment]
> in the end i do not care if this is merged or not but please leave legitmate critique alongside the thumbs down i feel like theirs some ways to rework it wheir everyone is happy. i just feel like high risk = high reward, i think the staff of healing ill problably remove then put the book in their

no

**Comment by boodaliboo** [comment]
> > in the end i do not care if this is merged or not but please leave legitmate critique alongside the thumbs down i feel like theirs some ways to rework it wheir everyone is happy. i just feel like high risk = high reward, i think the staff of healing ill problably remove then put the book in their
> 
> You don’t care for the PR so why should I care to give an explanation to what is obvious.

why are you so obsessed with me your reply to everything i say on discord making yourself look like a fool, i dont want this weird drama. you had to fix code from a pr i made 2 years ago is that seriously what your so annoyed or mad at me about, otherwise i have no clue your issue with me, continue if you want its hilarious. just recognize its pretty one sided.

SORRY EVERYONE ELSE

**Comment by AMyriad** [comment]
I haven't been around long enough to grow attached to, abuse, or be abused by this item. I say this to preface so you understand I'm not biased one way or another. And as no one else wants to spend their time on explaining what's wrong with this PR, I'll try and explain the issues I see, which may also explain why others feel the same way:

1. Miners already have a lot of powergamey loot; Wizard spells are usually pretty powerful (even if they're limited to a select few) and I can imagine people don't like seeing miners with more stupid strong loot at their disposal.

2. The ruin already has a lot of incredibly strong loot including a suit which nullifies most of the danger in said ruin.

3. The rationale in #18839 for removing them in the first place.

4. If this is a revert I imagine the construct shells should go too? Like in the PR you're trying to revert that replaced the book for the shells? If that image is right this isn't a revert, it's a buff.

5. L doesn't compile.

**Comment by boodaliboo** [comment]
> I haven't been around long enough to grow attached to, abuse, or be abused by this item. I say this to preface so you understand I'm not biased one way or another. And as no one else wants to spend their time on explaining what's wrong with this PR, I'll try and explain the issues I see, which may also explain why others feel the same way:
> 
> 1. Miners already have a lot of powergamey loot; Wizard spells are usually pretty powerful (even if they're limited to a select few) and I can imagine people don't like seeing miners with more stupid strong loot at their disposal.
> 2. The ruin already has a lot of incredibly strong loot including a suit which nullifies most of the danger in said ruin.
> 3. The rationale in [replaces the spellbook in the lavaland wizard den with 3 construct shells #18839](https://github.com/yogstation13/Yogstation/pull/18839) for removing them in the first place.
> 4. If this is a revert I imagine the construct shells should go too? Like in the PR you're trying to revert that replaced the book for the shells? If that image is right this isn't a revert, it's a buff.
> 5. L doesn't compile.

i can remove the construct shells but they are very useless to the average miner who isnt going to have anyway to use it, and of course they got loot, i havent played in a bit and their seems to be alot of new ruins and even megafauna so i cant particularly say much on the balance, but i appreciate legit pointing out the problems with it, but also like mining is dangerous and you can die really fast its just the issue of finding balance on whats fair to give them to help defeat things and whats to strong, i made this pr because it was requested but im happy to completely rework the ruin if you have ideas, i just think most anything but construct shells would make sense, even a used spellbook would make more sense because atleast that is very apparent it will be useless towards you

**Comment by Therandomhoboo** [comment]
> i can remove the construct shells but they are very useless to the average miner who isnt going to have anyway to use it, and of course they got loot, i havent played in a bit and their seems to be alot of new ruins and even megafauna so i cant particularly say much on the balance, but i appreciate legit pointing out the problems with it, but also like mining is dangerous and you can die really fast its just the issue of finding balance on whats fair to give them to help defeat things and whats to strong, i made this pr because it was requested but im happy to completely rework the ruin if you have ideas, i just think most anything but construct shells would make sense, even a used spellbook would make more sense because atleast that is very apparent it will be useless towards you

> I haven't played in a bit
> i made this pr because it was requested

Can we request you play the game before making "requested" prs so you actually don't look dented?
Plus you cried to the wrong person about "drama", embarrassing.

**Comment by UltraBigRat** [comment]
Before they got removed i never rreally saw them being abused, and the books were mostly just used for fun. If this doesnt get through would be nice if the ruin at least got some soulstones so the shells are a bit less worthless.

**Comment by MajManatee** [comment]
No activity. Reopen when work continues

**Pull request closed without merging**
