### PR TITLE
Syndicate Icemoon - Revision 2

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

basically

adds extra materials

universal enzyme

syndie suits

fixes the bridge shutters

emergency fish lazarus

fixes vendors (finally)

mech recharger with broken-down dark gygax (irrepairable unless a maintainer says i can)

also this
image

additionally adds the Western Island, where the AGCNR will go once that is merged

also reinforces the outer hull

the armoury also now has an OMEGA SHIT emag with 3 charges, mandatory uranium replenishment, and only meant for hacking cyborgs with a big fat bold warning label

# Spriting

# Wiki Documentation

# Changelog

:cl:  
bugfix: syndicate icemoon is slightly less shit. _**I CANNOT FIX THE RANDOM FAUNA SPAWNS. THAT'S THE ICEMOON DEV'S PROBLEM.**_
/:cl:

### CODE REVIEW

**Review by neeshacark — CHANGES_REQUESTED** [review]
Document all your changes please, I notice the mech equipment isn't listed

Map itself is fine

**Comment by N3D6** [comment]
what’s the issue with the vendors
does shit cost money

**Review by N3D6 — CHANGES_REQUESTED** [review]
set the onstation variable on the vendors to 0 to properly make everything free

**Comment by Addust** [comment]
> Document all your changes please, I notice the mech equipment isn't listed
> 
> Map itself is fine

done

**Comment by Addust** [comment]
why cant turdis call mysql

**Comment by MajManatee** [comment]
he broke the linter...

**Comment by neeshacark** [comment]
hm thats interesting

**Review by neeshacark — APPROVED** [review]

**Pull request merged**
