### PR TITLE
removes security's ability to cockblock antagonist that rely on stealing weapons

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
no more printing mindshield firing pins. guns that start with them eg pulse weapons still have them, you just cant shit out billions of them from the seclathe anymore

being able to make every weapon ever essentially unlootable cucks over antagonists like vampires and BBs and such extremely badly, and completely removes the risk of people breaking into the armory to steal guns because they wont be able to use them  without opening the mindshield lockbox which is time consuming and requires specialized equipment to do as well as making you stick out like a sore thumb on sechuds. this should also help cull every security officer having 15 mindshield firing pin AEGs in their boh, since science guns are still a problem i'm going to try to address in the future, but this is a good start for it, plus there's no such thing as too many nerfs for security.

you can still print and use science guns with the fucking 10 electronic firing pins that start in the armory, if you somehow fucking run out? buy more from cargo it's 2k credits for another 10

# Wiki Documentation

tech webs page

# Changelog

:cl:  
rscdel: mindshield firing pins can no longer be created
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
pins can be removed. Why not make normal pins craftable

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> pins can be removed. Why not make normal pins craftable

Infinite guns bad. if you somehow use all ten standard firing pins that spawn in one of the normal boxes, that's on you, and you can buy more with cargo its literally 2k credits for an additional 10

**Comment by redmoogle** [comment]
> Infinite guns bad. if you somehow use all ten standard firing pins that spawn in one of the normal boxes, that's on you, and you can buy more with cargo its literally 2k credits for an additional 10

2k for 10 feels cheap like cargo can make that amount of money pretty easy

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> > Infinite guns bad. if you somehow use all ten standard firing pins that spawn in one of the normal boxes, that's on you, and you can buy more with cargo its literally 2k credits for an additional 10
> 
> 2k for 10 feels cheap like cargo can make that amount of money pretty easy

it's the thought that counts, and as anyone who has ever complained about me trying to restrict things to cargo says, 'Money is worthless anyways and cargo always has infinite of it so no price matters and it'll be gotten roundstart' that and 'Restricting it to cargo effectively removes it from the game'

**Comment by ynot01** [comment]
merge upstream/master into this branch

**Comment by TheRyeGuyWhoWillNowDie** [comment]
god fucking damn it git

**Comment by TheRyeGuyWhoWillNowDie** [comment]
oh my fucking god

**Pull request closed without merging**
