### PR TITLE
fixes economy [adds critter money admin toggle]

### PR DESCRIPTION
**Pull request by tattax**
fixed economy

JT52zUlLzZ

money now makes you happy

image

adds the thing to VV and fun secrets panel if you want to make MONEY give HAPPINESS

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
I know it’s just a meme PR but it should be made into an admeme button to turn money into random cute critters because that’s pretty cool.

**Comment by Hislyna** [comment]
felinid buff?

**Comment by JamieD1** [comment]
Unironically pretty funny, should make it an admin toggle

**Comment by tattax** [comment]
@JamieD1

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
