### PR TITLE
Mentor ops - BEWARE OF SHIT CODE - Test Merge Only

### PR DESCRIPTION
**Pull request by JamieD1**
Mentor ops - BEWARE OF SHIT CODE

#### Changelog

:cl:  
rscadd: Mentor ops - BEWARE OF SHIT CODE
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
Thanks Jamie!

**Comment by Hopekz** [comment]
This ended days ago.

**Comment by patpol4** [comment]
Should this still be open

**Comment by JamieD1** [comment]
THIS SHALL BE BACK!

**Comment by Marmio64** [comment]
it won't...

**Pull request closed without merging**
