### PR TITLE
Sterilizes the codebase - Pt.5 Removes Lizard Eye Licking

### PR DESCRIPTION
**Pull request by JamieD1**
Removes Lizard Eye Licking

:cl:  
rscdel: Removes Lizard Eye Licking
/:cl:

### CODE REVIEW

**Comment by Smudged** [comment]
Lizards lick their eyes.

**Comment by VaelophisNyx** [comment]
I don't see the issue with this emote, and would love further explanation that points out why its bad in a well-put manner that isn't just "lizard bad"

**Comment by AlvCyktor** [comment]
1984!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! y no Lick lizar eye!!!!!?!?!?!

**Comment by JamieD1** [comment]
Give me a reason WHY this should be in, other then people just being weird with it.

**Comment by Smudged** [comment]
> Give me a reason WHY this should be in, other then people just being weird with it.

Because it's a neat feature, why are we removing this? 

Lizards lick their eyes and it's hurting nobody.

Why do YOU want to remove it in the first place?

**Comment by SomeguyManperson** [comment]
Personally I don't like lizard eye licking however I can't really find any reason mechanically or directionally why it shouldn't exist. It's not jarring to the point it should be removed or handled or whatever

**Comment by KillerOrcaCora** [comment]
emote bloat

**Review by KillerOrcaCora — APPROVED** [review]

**Pull request merged**
