### PR TITLE
New nullrod hat

### PR DESCRIPTION
**Pull request by Moltijoe**
More options for nullrods 👍 
ty to @cuackles for the sprite

slowly heals if not taken damage in 16 seconds
heals more the lower hp the wearer is

https://user-images.githubusercontent.com/108117184/237004718-12c6cf81-cf2c-4e34-bb9b-59afcd15a6b6.mp4

:cl:  @cuackles @Moltijoe 
rscadd: Adds a new clothing nullrod option
imageadd: adds sprites for the new nullrod
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Sounds cool but extremely useless compared to the other rods

**Comment by Moltijoe** [comment]
> Sounds cool but extremely useless compared to the other rods

how about stat buffs?

**Comment by Hislyna** [comment]
> > Sounds cool but extremely useless compared to the other rods
> 
> how about stat buffs?

I've got an idea, nodrop

**Comment by Moltijoe** [comment]
> I've got an idea, nodrop

no need, it's a hat that isn't dropped by slipping

**Comment by Hislyna** [comment]
> > I've got an idea, nodrop
> 
> no need, it's a hat that isn't dropped by slipping

Ahh gotcha!16 seconds to wait for slow healing though, maybe a slower regen when attacked vs none?

**Comment by Moltijoe** [comment]
> Ahh gotcha!16 seconds to wait for slow healing though, maybe a slower regen when attacked vs none?

maybe, passive healing is pretty strong and can break many things though
i worry making it too strong will just make it preferred by validhunters too

**Comment by SomeguyManperson** [comment]
> Sounds cool but extremely useless compared to the other rods

This gives a passive 5 point heal of all types with the single condition being "not currently taking damage"
And you believe this is so substantially weaker than "spear but with slight AP" or "spear but it can block sometimes" that it wouldnt be worth picking

**Comment by Hislyna** [comment]
> > Sounds cool but extremely useless compared to the other rods
> 
> This gives a passive 5 point heal of all types with the single condition being "not currently taking damage" And you believe this is so substantially weaker than "spear but with slight AP" or "spear but it can block sometimes" that it wouldnt be worth picking

16 fucking seconds

**Comment by cuackles** [comment]
> > > Sounds cool but extremely useless compared to the other rods
> > 
> > This gives a passive 5 point heal of all types with the single condition being "not currently taking damage" And you believe this is so substantially weaker than "spear but with slight AP" or "spear but it can block sometimes" that it wouldnt be worth picking
> 
> 16 fucking seconds

16 is reasonable, it's not supposed to be used for combat, it's supposed to be a fix after combat or accidents that damage you, mostly something to keep you healthy

**Comment by 00ze-cyclone** [comment]
Yes so if you don’t get killed by the initial strike and just fuck off for long enough you get regenerated from **EVERYTHING** that isn’t a motherfucking decloner.
This is absurdly strong, mid combat healing is good but that doesn’t mean outside combat healing is not, especially when it’s that egregious.

**Comment by Moltijoe** [comment]
too strong of an effect to go on a nullrod, regardless of the numbers

**Pull request closed without merging**
