### PR TITLE
Fixes my fuck up

### LINKED ISSUE #16998: THE SLIME DOES NOT WIGGLE AAAAA
## Test Merges: 
Not Supplied / None
## Reproduction:
description: metal slimes arent animated

 Submitted by: zealot (343805692710486017)

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request

baby slimes ( metal ) move again
Also Fixes #16998

# Spriting

yes

# Wiki Documentation

None

# Changelog

:cl:  
imageadd: added missing frames
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
@cuackles 
comment in your change "Fixes #16998"

**Review by MajManatee — APPROVED** [review]
such sloppy work sheesh

**Review by Moltijoe — APPROVED** [review]
so, as the only sprite maint, since you made this, literally only jamie can merge it

**Comment by cuackles** [comment]
> so, as the only sprite maint, since you made this, literally only jamie can merge it

hhhmmm lemme see if i can fix that

**Comment by cuackles** [comment]
nope that didnt fix it
@Ebin-Halcyon migth you aprove this pr please when you have time

**Review by Ebin-Halcyon — APPROVED** [review]

**Pull request merged**
