### PR TITLE
[s] Plasmastation event

### PR DESCRIPTION
**Pull request by patpol4**
# Intent of your Pull Request
Requested by @MegaEmpirical 
The idea is, all oxygen is replaced by plasma, crew spawn as plasmamen, if you don't want to spawn as plasmaman, you get to huff oxygen all round
Going to need some spriter and coder cooperation for this to work since I don't know how to do certain things
Already done this:
image
Also redefined what air is

Todo:

- [x] /obj/structure/closet/emcloset needs a plasma sprite instead of oxygen sprite - Identification did this one, thanks!
- [x] job tweaks so plasmamen can be command
- [x] test if what i've done works
- [x] swap the rest of oxytanks to plasmatanks
- [x] animals die - Thanks to Theos for providing monkeycode
- [ ] possibly some other changes i missed

### CODE REVIEW

**Comment by ChesterTheCheesy** [comment]
Pretty bad, one jackass trying to cut a wall with a welder will result in massive plasmafire...

**Comment by patpol4** [comment]
> Pretty bad, one jackass trying to cut a wall with a welder will result in massive plasmafire...

no oxygen no fire

**Comment by Moggram** [comment]
You are going to need to remove all the o2 tanks on the map for plasma tanks, also the mixed air ones to.

**Comment by MegaEmpirical** [comment]
If possible, my original plan wasn't for all to be plasmaman, it was humans to spawn in as plasmamen and plasmamen to spawn in as humans.

Alternatively, just let people choose

**Comment by patpol4** [comment]
> You are going to need to remove all the o2 tanks on the map for plasma tanks, also the mixed air ones to.

all o2 closets contain plasmaman tanks, i didnt swap the other ones yet

**Comment by Cartlord** [comment]
Would like to bring up that Station Engineers, Atmospheric Technicians, and Shaft Miners (I've heard Sec Officers too) all spawn with different emergency boxes; I've had this not work with other things that modify the internals box, so I'm bringing it up here. I also want to ask - what will the Atmos Tech be left to do in the event of this event popping? Pluox is useless for plasmemes, so there's little do actually do beyond fusion or Stim manufacturing.

**Comment by ToasterBiome** [comment]
> Would like to bring up that Station Engineers, Atmospheric Technicians, and Shaft Miners (I've heard Sec Officers too) all spawn with different emergency boxes; I've had this not work with other things that modify the internals box, so I'm bringing it up here. I also want to ask - what will the Atmos Tech be left to do in the event of this event popping? Pluox is useless for plasmemes, so there's little do actually do beyond fusion or Stim manufacturing.

Crystallizer

**Review by nesisknesis — APPROVED** [review]

**Comment by patpol4** [comment]
Air tanks and cans now contain a plasma-nitrogen mixture, air alarms are fixed. Only big issue left right now is probably all pets dying roundstart. 
Tested and good to run as event

**Comment by patpol4** [comment]
Animal problem solved, i don't see any major issues anymore. Good for event testmerge

**Pull request closed without merging**
