### PR TITLE
Pranksimov Lawset

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
New lawset called "Pranksimov". It costs 1000 glass (0.5 sheets) and 2000 bananium (1 sheet) and is locked behind Artificial Intelligence.

New cmagging capabilities:
- Crewsimov law board: Converts it into a Pranksimov law board.
- AI's shell: Change module to Clown.
- Cyborg (non-AI): Disconnects from the AI (if any) and replaces laws with Pranksimov and **NO LAW ZERO.**

Both the lawset and what exact laws will be after cmagging a cyborg:
image

# Wiki Documentation
Add laws to AI modules. Mention new interactions in Cmag's description in Syndicate Items.

# Changelog
:cl:  
rscadd: Pranksimov, a funny variant of Crewsimov, has been added. 
rscadd: Cmagging a Crewismov law board converts it to a Pranksimov law board.
rscadd: Cmagging a AI's B.O.R.I.S shell will set their module to Clown.
rscadd: Cmagging a Cyborg will disconnect them from the AI and set their laws to Pranksimov. However, be warned that there won't be a law zero! Hope they find helping you more funnier than not.
/:cl:

### CODE REVIEW

**Comment by KingSuperBOB** [comment]
"AI help me kill the captain it'll be funny I will use a HONK mech"

**Comment by RG4ORDR** [comment]
"I need to detonated the station nuke - gone wild"

**Comment by Hislyna** [comment]
God I can't wait for the migraine of ahelps from this

**Comment by bruhlookatthisdood** [comment]
Admin: "Why did you plasmaflood the medbay and set it on fire?"
AI: "You see, it was quite comical."

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
