### PR TITLE
possibly fixes russians "mapper forgot to set this"

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
this is a untested webedit it may or may not work just wanted to see if this fixed it also i dont know if russian characters work so im fine with changing them if they dont
https://github.com/yogstation13/Yogstation/issues/7653
#### Changelog

:cl:   
bugfix: fixed a spawner bug  
/:cl:

### CODE REVIEW

**Comment by overlord12345** [comment]
Alot of fugative and hunter stuff is bugged

**Comment by monster860** [comment]
Try:
```
&#x411;&#x43E;&#x431; &#x420;&#x43E;&#x431;&#x435;&#x440;&#x442;&#x441; &#x431;&#x44B;&#x43B; &#x437;&#x434;&#x435;&#x441;&#x44C; &#x432;&#x43E;&#x434;&#x43A;&#x430; &#x43F;&#x440;&#x438;&#x432;&#x435;&#x442; &#x432;&#x435;&#x441;&#x435;&#x43B;&#x43E; &#x43F;&#x435;&#x440;&#x435;&#x432;&#x435;&#x441;&#x442;&#x438; &#x44D;&#x442;&#x43E;
```

That way it would work regardless of whether its 512 or 513.

**Comment by boodaliboo** [comment]
> Try:
> 
> ```
> &#x411;&#x43E;&#x431; &#x420;&#x43E;&#x431;&#x435;&#x440;&#x442;&#x441; &#x431;&#x44B;&#x43B; &#x437;&#x434;&#x435;&#x441;&#x44C; &#x432;&#x43E;&#x434;&#x43A;&#x430; &#x43F;&#x440;&#x438;&#x432;&#x435;&#x442; &#x432;&#x435;&#x441;&#x435;&#x43B;&#x43E; &#x43F;&#x435;&#x440;&#x435;&#x432;&#x435;&#x441;&#x442;&#x438; &#x44D;&#x442;&#x43E;
> ```
> 
> That way it would work regardless of whether its 512 or 513.

thanks

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Change the text, "Bob roberts was here vodka hi fun translate this" is not something we want in the codebase

**Comment by boodaliboo** [comment]
Your mean but ok it was a funny joke and the average player won’t go and translate that

**Comment by boodaliboo** [comment]
Обо Эборегф Юнф Урер ибкхн ув Ша Генафынгр Гуф monster can you do the conversion thing for this

**Comment by monster860** [comment]
`&#x41E;&#x431;&#x43E; &#x42D;&#x431;&#x43E;&#x440;&#x435;&#x433;&#x444; &#x42E;&#x43D;&#x444; &#x423;&#x440;&#x435;&#x440; &#x438;&#x431;&#x43A;&#x445;&#x43D; &#x443;&#x432; &#x428;&#x430; &#x413;&#x435;&#x43D;&#x430;&#x444;&#x44B;&#x43D;&#x433;&#x440; &#x413;&#x443;&#x444;`

**Comment by boodaliboo** [comment]
> `&#x41E;&#x431;&#x43E; &#x42D;&#x431;&#x43E;&#x440;&#x435;&#x433;&#x444; &#x42E;&#x43D;&#x444; &#x423;&#x440;&#x435;&#x440; &#x438;&#x431;&#x43A;&#x445;&#x43D; &#x443;&#x432; &#x428;&#x430; &#x413;&#x435;&#x43D;&#x430;&#x444;&#x44B;&#x43D;&#x433;&#x440; &#x413;&#x443;&#x444;`

xoxo

**Comment by Hopekz** [comment]
Missed opportunity should have changed it to an Amazon referral link to generate infinite income

**Comment by Ktlwjec1** [comment]
Can you not just have it say "You are a space-russian smuggler!"?

**Comment by boodaliboo** [comment]
I could but I personally think it’s more fun if it’s actually in Russian

**Comment by AsV9** [comment]
> Can you not just have it say "You are a space-russian smuggler!"?

**Pull request closed without merging**
