### PR TITLE
Fixes code that apparently does not work but monster didn't care enough to actually describe what he's doing. For all we know he's adding a backdoor.

### PR DESCRIPTION
**Pull request by monster860**
I don't know how to briefly describe what I'm changing.

### CODE REVIEW

**Comment by GenericDM** [comment]
speedmerge 🔫

**Comment by Amelia0010** [comment]
nich is bad at code, because he finds a way to completely modularize it?

**Comment by HomocidlePancakes** [comment]
I agree. Nich is bad. Please remove

**Comment by monster860** [comment]
Modularization is nice, but whats nicer is having code that actually works

**Comment by Altoids1** [comment]
Thanks Mac

**Comment by monster860** [comment]
Yes, I'm totally the only one that does this.

#3701 #3930 #4283 #3392

**Comment by Amelia0010** [comment]
:^)

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
nich being a shit doesn't allow you to be a shit too

**Comment by Amelia0010** [comment]
lol

**Pull request merged**
