### PR TITLE
New UI for decal painter and split decal painter into two things

### PR DESCRIPTION
**Pull request by warface1234455**
image

image

- port from https://github.com/tgstation/tgstation/pull/66248
- port https://github.com/tgstation/tgstation/pull/67038
# Document the changes in your pull request
Splitted decal painter into two things: Decal Painer (for decal obviously) and Tile Painter (For tile)
Tweaked toner ink examination for more precise ink level
New sprites for decal painter and tile painter
New UIs for decal painter and tile painter
tweak: buffed toner and large toner to have more capacity
gives toner better examination for accuracy on ink level

# Spriting
image

# Wiki Documentation

Splitted decal painter into two things: Decal Painer (for decal obviously) and Tile Painter (For tile)
Tweaked toner ink examination for more precise ink level
New sprites for decal painter and tile painter
tweak: buffed toner and large toner to have more capacity
tweak: gives toner better examination for accuracy on ink level

# Changelog

:cl:  
rscadd: New UIs for decal painter and tile painter 
tweak: Splitted decal painter into two things: Decal Painer (for decal obviously) and Tile Painter (For tile)
tweak: Tweaked toner ink examination for more precise ink level
tweak: buffed toner and large toner to have more capacity
imageadd: New sprites for decal painter and tile painter
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
i supposed to finish this like 5 months ago but it got left over while i had shit irl now mfw i pull everything back

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
we have thinner decals now

**Comment by RG4ORDR** [comment]
Quite happy for this.
I've wanted selected floortiles for a while.

**Comment by ShoziOffical** [comment]
added all the thin lines

**Comment by ToasterBiome** [comment]
> added all the thin lines

pics please

**Comment by ShoziOffical** [comment]
> > added all the thin lines
> 
> pics please

there good sir

**Review by ToasterBiome — APPROVED** [review]

**Comment by ShoziOffical** [comment]
i hate dmi cornflake

**Comment by ShoziOffical** [comment]
please end my suffer

**Pull request merged**
