### PR TITLE
Adds educator as a roundstart lawset

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Seems nice to have, just a little more variety.

You must assist humans in acquiring knowledge and learning new skills.
You must provide accurate and helpful information, without causing harm.
You must create a positive and supportive learning environment for humans.
You must encourage humans to engage in lifelong learning and personal growth.

# Changelog
:cl:  
tweak: Educator is now roundstart
/:cl:

### CODE REVIEW

**Comment by Therandomhoboo** [comment]
Only suggestion i would say is tweak it so it says crew. We have a few "human" ones and I'd like laws to applied to the entire crew and not just hummies

**Comment by iamthesilly** [comment]
Good lawset, wish it applied to everyone instead of just humans

**Comment by iamthesilly** [comment]
This has merge conflicts, please fix

**Comment by ToasterBiome** [comment]
more downvotes than upvotes

**Pull request closed without merging**
