### PR TITLE
[admin] Record player living playtime in notes

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Makes it easier for admins to determine frequency of rule breaks. 

image

# Changelog

:cl:  
rscadd: Admin notes now record the living playtime of a player when they were noted. 
/:cl:

### CODE REVIEW

**Review by alexkar598 — COMMENTED** [review]
I'd rather this be an SQL TRIGGER instead so that all services compute the playtime in the same way in a single place ngl

**Comment by adamsong** [comment]
> I'd rather this be an SQL TRIGGER instead so that all services compute the playtime in the same way in a single place ngl

Mysql does not allow for modification of the new row in the trigger.

**Comment by alexkar598** [comment]
Worked for me on mariadb 10.11
 ```sql
DELIMITER $$
CREATE TRIGGER add_playtime
BEFORE INSERT
ON erro_messages FOR EACH ROW
BEGIN 
    SET NEW.playtime = (SELECT minutes FROM erro_role_time rt WHERE rt.ckey = NEW.targetckey AND rt.job = 'Living');
END$$
DELIMITER ;
```

**Review by alexkar598 — APPROVED** [review]
Looks poggers

**Pull request merged**
