### PR TITLE
Adds second drone shell to the drone hole

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

adds one more drone shell to the Drone Hole maint ruin, so the drone isn't lonely

this mostly exists to test the new mapping changelog tag, but also it does suck being the only drone in a round

# Changelog

:cl:  
mapping: Added a second drone shell to the Drone Hole 3x3 maint ruin
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
why maptag no work :C

**Comment by Marmio64** [comment]
cant the drone just make more drone shells?

**Comment by VaelophisNyx** [comment]
yeah but it's a hassle to do.
also as mentioned this was *mostly* for testing a change to yogbot

**Comment by VaelophisNyx** [comment]
ultimately this was just a tester, so. eh

**Comment by VaelophisNyx** [comment]
reopening to test bot tagging

**Comment by VaelophisNyx** [comment]
will reopen when bot is actually up to date

**Comment by VaelophisNyx** [comment]
forgor to reopen

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
