### PR TITLE
Adds spawnpoints for space ninja on IceMeta for when it rolls

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

I don't see why this event shouldn't be allowed to roll on this station.

# Why is this good for the game?

Not technically a bugfix but I like space ninjas

# Testing

image

# Changelog

:cl:  

mapping: Adjusts it so that space ninjas can spawn on icemeta properly

/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
I think this might make carp spawn on icemeta too
Instead add a backup, so if ninja fails to pick a location, instead have it spawn based on other criteria

**Comment by cowbot92** [comment]
> I think this might make carp spawn on icemeta too Instead add a backup, so if ninja fails to pick a location, instead have it spawn based on other criteria

this is smart

**Comment by cowbot92** [comment]
> I think this might make carp spawn on icemeta too Instead add a backup, so if ninja fails to pick a location, instead have it spawn based on other criteria

I added a double check without needing the map part

**Comment by RG4ORDR** [comment]
> I think this might make carp spawn on icemeta too Instead add a backup, so if ninja fails to pick a location, instead have it spawn based on other criteria

Is there a way to flavor text Spacecarp to Icecarp???

**Comment by cowbot92** [comment]
> > I think this might make carp spawn on icemeta too Instead add a backup, so if ninja fails to pick a location, instead have it spawn based on other criteria
> 
> Is there a way to flavor text Spacecarp to Icecarp???

yes and you can do it!

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
