### PR TITLE
Disabler now shoots twice as fast

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

I think the most annoying part about having to use a disabler is the fact that it shoots as fast as a taser but it still takes so many clicks to down someone. I think you should be able to fire faster because even if you have someone in a corner, it's still going to take like 10 seconds to down them because of how slow it is. 

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Disabler now shoots twice as fast
/:cl:

### CODE REVIEW

**Comment by thegoldencat413** [comment]
._.

**Comment by Maia-J** [comment]
1.5x. Take it or leave it.

**Comment by Simplehorror** [comment]
1.5x could be good, but I think this is the sec buff we've been needing

**Comment by 00ze-cyclone** [comment]
Skill issue, just use King Crimson to erase the time of the cooldown

**Comment by Moltijoe** [comment]
better than them relying solely on flashes and stun batons, but 2x is probably too fast

**Comment by 00ze-cyclone** [comment]
> better than them relying solely on flashes and stun batons, but 2x is probably too fast

They already rely a lot on the disabler, that shit is already cosmically robust with it's ability shoot a fuckton of beams, very good damage that is not very well stopped by most armors and able to be used from the safety of behind of one of the 1237042874 reinforced windows that will eat 10 bullets before breaking.

**Comment by ReddicusDragon** [comment]
solution: delete sec

**Comment by Moltijoe** [comment]
they're good in their current spot, a good security officer should use different tools based on the situation

**Pull request closed without merging**
