### PR TITLE
Reduces RPD material requirement

### PR DESCRIPTION
**Pull request by warface1234455**
Too costly
# Document the changes in your pull request

Iron: 45000 -> 22000
Glass: 37500 -> 18000

# Wiki Documentation

Iron: 45000 -> 22000
Glass: 37500 -> 18000

# Changelog

:cl:  

tweak: Adjusted RPD material requirement Iron: 45000 -> 22000, Glass: 37500 -> 18000
/:cl:

### CODE REVIEW

**Review by Bibby0110 — DISMISSED** [review]

**Comment by Bibby0110** [comment]
Maybe not so cheap

**Comment by ShoziOffical** [comment]
> Maybe not so cheap
Imma increase both material type with additional 2000 mats

**Comment by JamieD1** [comment]
Try half or a third first.

**Comment by ShoziOffical** [comment]
> Try half or a third first.

@JamieD1 done

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
