### PR TITLE
Ports two virology symptoms from bee

### PR DESCRIPTION
**Pull request by boodaliboo**
########################################
########################################
original pr:https://github.com/BeeStation/BeeStation-Hornet/pull/1203
########################################
########################################

### Intent of your Pull Request

adds two new viro symptoms from bee
"Pituitary Disruption (level 7):
At base level, makes you bigger, scaling with stage speed. at 8 stage speed, causes passive brute healing, at the cost of occasionally vomiting up blood and guts. at 12 stage speed, quadruples the healing, but causes you to slowly die of cell damage, and puke up more advanced tumors, which may come to life and attack! (not sure what the brute heal/cell damage ratio per tick should be. at the moment it's 4 brute heal/ .2 cell damage, not sure if this should be changed. it also unpredictably knocks you down while you have it and makes your hitbox larger, so that should be enough downside...)

Hyperperspiration(level 6):
at base level, causes sweating, lowering firestacks and rarely leaving short-lived pools of water. at 6 transmission, causes sweat to extinguish fire and clean messes in a 2-tile radius every so often. At 8 transmission, heals toxin and purges reagents, spraying them in the same 2-tile radius."
#### Changelog

:cl:  
rscadd: Added two new intresting viro symptoms from bee and various limbs and lootdrops for its symptoms
/:cl:

### CODE REVIEW

**Review by Hopekz — CHANGES_REQUESTED** [review]
Undocumented changes

**Comment by boodaliboo** [comment]
> Undocumented changes

in what sense?

**Comment by Hopekz** [comment]
> > Undocumented changes
> 
> in what sense?

in the following files: 
- code/game/objects/effects/spawners/lootdrop.dm
- code/modules/mob/living/carbon/monkey/monkey.dm
- code/modules/surgery/bodyparts/bodyparts.dm
- code/modules/surgery/bodyparts/head.dm

**Comment by boodaliboo** [comment]
> > > Undocumented changes
> > 
> > 
> > in what sense?
> 
> in the following files:
> 
> * code/game/objects/effects/spawners/lootdrop.dm
> * code/modules/mob/living/carbon/monkey/monkey.dm
> * code/modules/surgery/bodyparts/bodyparts.dm
> * code/modules/surgery/bodyparts/head.dm

ok

**Review by Partheo — APPROVED** [review]

**Comment by boodaliboo** [comment]
ill come back to this later

**Comment by jcatjmeow** [comment]
Ok so:

In the line above every new variable, type /// and then a short description of what the variable means.

Before each proc, do a block comment like so
/**
  \* Short description of the proc
 \*
 \* Longer detailed paragraph about the proc
  \* including any relevant detail
  \* Arguments:
  \* \* arg1 - Relevance of this argument
  \* \* arg2 - Relevance of this argument
  */

Before each datum, do a similar comment like so
/**
  \* Short description
  \*
  \* Longer detailed paragraph about the proc
  \* including any relevant detail
  */

You don't have to document any var that is inherited, but you can if you feel it's relevant.
Since I'm not quite sure what this stuff does at a glance I can't offer any helpful examples, but feel free to show me your in-progress comments and I will look them over

**Comment by boodaliboo** [comment]
i cant figure out how to define heal_amt

**Comment by Ratvar** [comment]
I do not believe passive brute healing is a good idea. Althought, it causes knockdown for 5 seconds with 5% chance each second. 
Tetsuo tier Pituitary Disruption causes player to vomit **ghostrole monkeys** with goal to wreck non-lethal chaos, and they will ignore non-lethal part because they are made from dead idiot players, and that tier generally will cause whole station to spam killmobs with no way to stop it
This needs better changelog, maybe, and PR text

**Pull request closed without merging**
