### PR TITLE
Expands BoxStation incinerator to have a TEG tinkering area in it

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

https://forums.yogstation.net/threads/expanding-atmos-on-yogsbox.24691/#post-208259

wej upvoted this so i take this as permission

~pour one out for the 5x10 maint room that was there (blood cult winrate diving)~

OLD IMAGE: https://user-images.githubusercontent.com/5091394/154788565-4015dffe-b8ca-4e50-abeb-f29f0234d554.png

**People didn't like removing the maint room so this expands it down (also moves AI sat 3 tiles down to fit this)**

NEW IMAGE: 
image

# Wiki Documentation

map change

# Changelog

:cl:  
rscadd: expands box incinerator to have a little tinkering area 
tweak: moves AI sat 3 tiles down on box
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
@Marmio64 why do you don't like this

**Comment by bruhlookatthisdood** [comment]
noooo my maint room ):

**Comment by bruhlookatthisdood** [comment]
why is there an injector into space (that isnt connected to the pipes)

**Review by Bibby0110 — DISMISSED** [review]
Proper changelog

**Comment by ToasterBiome** [comment]
> why is there an injector into space (that isnt connected to the pipes)

For venting whatever you want, it has no pipes on purpose.

**Comment by ToasterBiome** [comment]
> Proper changelog

The changelog is proper

**Comment by Marmio64** [comment]
> @Marmio64 why do you don't like this

because i think that removing maint space to include random stuff like this isn't necessary especially when the atmos tech can just make the room themselves. In fact, its more interesting to have to create a new room rather than it just being given to you from the start.

**Comment by bruhlookatthisdood** [comment]
i agree with Marmio64. if you want that teg just grab a rcd and take the walls down.

**Comment by patpol4** [comment]
I'm conflicted on this

**Comment by Moja10** [comment]
You killed one of the best maint template rooms for atmos mains

**Comment by ToasterBiome** [comment]
> I'm conflicted on this

mayhaps we can extend atmos down more to get an area while also having that maints stay in tact? This would required ai sat to be moved a few tiles downward.

**Comment by patpol4** [comment]
Then you end up with two similarly sized areas, one of which is redundant. On the other hand it's much easier for atmos techs to start something if they have a room ready to be built in that isn't perfect in on itself(missing tiles, lights, etc) but doesnt require extra deconstruction like the maint one would.

**Comment by zen373** [comment]
I try to either clear that maint room or make separate room but its just to time consuming,. In most cases i run out of time.

**Comment by Bibby0110** [comment]
> > Proper changelog
> 
> The changelog is proper

No it isn't

**Comment by JamieD1** [comment]
Can you put the maint room somewhere else so we dont lose it?

**Comment by bruhlookatthisdood** [comment]
> Can you put the maint room somewhere else so we dont lose it?

Lets just replace the brig with it, wasnt being used anyways.

**Comment by patpol4** [comment]
You could always just move the maint room here, I'm a bit hesitant though since i feel sentimental for the bridge
image

**Comment by patpol4** [comment]
No don't move it there, that's stupid

**Comment by MegaEmpirical** [comment]
Glorious, I've wanted this for a long time.

**Review by patpol4 — CHANGES_REQUESTED** [review]
This is unironically a tough decision for me to make seeing as i play engi often. This clearly would benefit the atmos techs a lot but at the cost of reducing maint space for everyone.
If you find a way to implement this (maybe reduce the room size or move the turbine a bit?) without compromising the maint room then it's fine, otherwise we can't do this.
We would end up with a great room for atmosians that makes maint a lot smaller and only gets used sometimes.

**Comment by MegaEmpirical** [comment]
I've no idea why there's this weird emphasis on maintenance. Atmos has been losing it's spaces in maintenance any way too.

If someone wants to preserve the same amount of maintenance space then just expand one of thr other corners, there's plenty of options. I'd favor the bottom right of the station myself.

**Comment by bruhlookatthisdood** [comment]
wouldnt the windows get irradiated from the turbine's output?

**Comment by bruhlookatthisdood** [comment]
> only gets used sometimes.

Maybe instead of replacing the room, a teg maintance template?

**Comment by ToasterBiome** [comment]
@MegaEmpirical Are you happy with this new version?

**Comment by JamieD1** [comment]
image

**Review by patpol4 — APPROVED** [review]
Totally didnt forget to merge this

**Pull request merged**
