### PR TITLE
Shadowling balance changes

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Marker beacons are now disabled by veil as god intended
Icy veins now injects 5 frost oil and reduces temperature by 100, with its cooldown increased to 1 minute from 25 seconds, but also injects shadowfrost, a reagent which drastically slows whoever it is injected with
Icy veins burn damage halved honestly nobody cares lmao
thralling now properly removes frost oil rather than pretending to due to old reagent code not causing warnings anywhere
Empowered thralls moved to a new ability, Dark Acceleration, unlocked at 5 thralls since 9 thralls is a bit late to pretend people will use them

# Wiki Documentation

Marker beacons are now disabled by veil
Icy veins now injects 5 frost oil and reduces temperature by 100 (down from 15 and 200), with its cooldown increased to 1 minute from 25 seconds, but also injects shadowfrost, a reagent which drastically slows whoever it is effecting (base metabolism)
Icy veins burn damage halved, likely not actually written anywhere
thralling removes frost oil
Empowered thralls moved to a new ability, Dark Acceleration, unlocked at 5 thralls
collective hivemind cooldown reduced from 30 seconds to 10 seconds

# Changelog

:cl:  
bugfix: thralling someone now removes frost oil and stabilizes their body temperature as intended
tweak: marker beacons now extinguished by veil
tweak: icy veins now injects 5 frost oil (down from 15) and reduces temperature by 100 (down from 200) and has had its cooldown increased from 25 seconds to 1 minute
tweak: icy veins now injects shadowfrost, a new reagent that reduces the speed of whoever it is effecting
tweak: empowered thralls are no longer created with the dark recuperation ability, instead from a new ability, dark acceleration, unlocked at 5 thralls
tweak: collective hivemind's cooldown has been reduced to 10 seconds since 30 is limiting for an ability you can fail to cast and that is vital for progression
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Rest in peace offensive icy veins…

**Comment by Simplehorror** [comment]
Make it so thralling keeps frost oil so you're incentivised not to use it to glare and then thrall

**Comment by Marmio64** [comment]
making empowered thralls available earlier still doesn't change the fact that they're doodoo even in spite of me making like 3 PRs to buff them on several occasions. Empowered thralls still need a movement ability of some sort.

**Comment by Simplehorror** [comment]
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature. 
This commit was created on GitHub.com and signed with GitHub’s verified signature.

**Comment by SomeguyManperson** [comment]
> making empowered thralls available earlier still doesn't change the fact that they're doodoo even in spite of me making like 3 PRs to buff them on several occasions. Empowered thralls still need a movement ability of some sort.

They also don't have a gimmick outside getting a couple shadowling abilities and dying faster than normal thralls. Potentially shafowlings shpuld lose their nightmare jaunt copy and give it to empowered thralls

> This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature. This commit was created on GitHub.com and signed with GitHub’s verified signature.

I make all my changes on the shitter so they can be both figuratively and literally shit code

**Comment by ghost** [comment]
Make empowered thrall ability turn thralls into nightmares with light eater blade and shadow walk 👍

**Comment by JamieD1** [comment]
Probably worth a test merge

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
