### PR TITLE
Adds Turbo Killer by Carpenter Brut to the lobby music list

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

we need more music that gets you pumped to play

https://www.youtube.com/watch?v=wy9r2qeouiQ Song in question

I'll let it speak for itself

# Changelog

:cl:  
soundadd: Added Turbo Killer by Carpenter Brut to the lobby music list
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
> we need more music that gets you pumped to play

just add basically all carpenter brut's stuff then?

**Comment by VaelophisNyx** [comment]
yeah but you're supposed to do it at like, one per PR
which is lame

**Comment by Moltijoe** [comment]
disregard rules, add the entire Nier OST in one PR

**Comment by JamieD1** [comment]
> yeah but you're supposed to do it at like, one per PR which is lame

Because some will fit some wont.

**Comment by JamieD1** [comment]
Unfortunately I feel this is a bit heavy and too much,

**Pull request closed without merging**
