### PR TITLE
adds nuclear bombs to the list of things the ai might roll for ion storms

### PR DESCRIPTION
**Pull request by athena413**
# Document the changes in your pull request

please imagine the following ion laws for me:

TIME FOR NUCLEAR BOMBS

YOU ARE NUCLEAR BOMBS PERSONIFIED

it would be funny i think

# Spriting

no

# Wiki Documentation

not documented

# Changelog

:cl:  
rscadd: Ion storms can now roll with NUCLEAR BOMBS as 'ion things' for ai ion laws
/:cl:

### CODE REVIEW

**Comment by Zer0Tactics** [comment]
"Legalize Nuclear Bombs"

**Comment by Yarinoi** [comment]
nuke radio

**Comment by Hislyna** [comment]
I cant wait for the AI to blow up the nuclear reactor

**Review by SapphicOverload — APPROVED** [review]
Legalize nuclear bombs

**Pull request merged**
