### PR TITLE
New Emergency Shuttle: The Cozy Shuttle

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

adds a new shuttle, the cozy shuttle.  comes with three fireplaces, multiple longue areas, a brig and a medical bay.

image_2023-09-23_153050717

# Why is this good for the game?
more shuttle = more good

# Wiki Documentation

i dont think we have a shuttles page but if we do this goes there

# Changelog

:cl:  cark
mapping: adds a new shuttle - the cozy shuttle
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
WHERES THE TV

**Comment by solwashere** [comment]
"accidentally" causing a turf fire

**Comment by maxion12345** [comment]
No firelocks?

**Comment by neeshacark** [comment]
> No firelocks?

heh

**Comment by maxion12345** [comment]
updated photo
68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3132303936363333362f31373032303837383537392f612f5f6d6170735f73687574746c65735f656d657267656e63795f636f7a792f302d61646465642e706e67

**Comment by maxion12345** [comment]
Also, in the brig, are those brig tiles retextured or just red carpet? If they're carpet, see if you can put some brig tiles in there so security/hijackers can use it properly

**Comment by neeshacark** [comment]
> Also, in the brig, are those brig tiles retextured or just red carpet? If they're carpet, see if you can put some brig tiles in there so security/hijackers can use it properly

i thought we changed how that worked to be based around cuffs

**Comment by ShoziOffical** [comment]
> > Also, in the brig, are those brig tiles retextured or just red carpet? If they're carpet, see if you can put some brig tiles in there so security/hijackers can use it properly
> 
> i thought we changed how that worked to be based around cuffs

yep we did #14209

**Review by Aquizit — CHANGES_REQUESTED** [review]
image

Surgery bag would be nice.

---

image

I'd say give command staff some nice booze and some cigars or something more than just empty tables.

**Comment by neeshacark** [comment]
> image
> 
> Surgery bag would be nice.
> 
> image
> 
> I'd say give command staff some nice booze and some cigars or something more than just empty tables.

I'll redo the bridge some but I don't see any reason to give the medbay a surgery bag, its stocked the same as the default shuttle

**Review by Aquizit — APPROVED** [review]
I find the command room to be more luxurious but less useful a fantastic exchange.

**Pull request merged**
