### PR TITLE
Glockroaches

### PR DESCRIPTION
**Pull request by Hopekz**
Ports tgstation/tgstation#47900

Apparently simple mobs and projectiles work differently in our codebase.
Fixed and tested. 

Original PR description:
"
Adds glockroaches, a cockroach with a fucking gun.
Currently only obtainable through gold core spawns/admin spawning.
They drop 0.9mm ammo casing, so you know when an assistant in maintenance was murdered by a cockroach.
there's honestly not much to say about this pr
image

"

#### Changelog

:cl:  
rscadd: Added glockroaches. Literally cockroaches with Glocks. Meet them via gold core spawns or praying to your local admeme
/:cl:

### CODE REVIEW

**Comment by Oakboscage** [comment]
Speedmerge fucking now

**Comment by CMOisLing** [comment]
yes totally bro

**Review by nesisknesis — APPROVED** [review]
theres honestly not much to say about this sprite

**Comment by SomeguyManperson** [comment]
H

**Comment by Hopekz** [comment]
> H

E

**Pull request merged**
