### PR TITLE
Reverts #8620, replaces it with regular spacesuits

### PR DESCRIPTION
**Pull request by ynot01**
reverts https://github.com/yogstation13/Yogstation/pull/8620
who the fuck thought it was a good idea to give spacepol deathsquad suits

new shit looks like this

### CODE REVIEW

**Comment by nesisknesis** [comment]
lol

**Comment by Ktlwjec1** [comment]
me i love chaos

**Review by Ktlwjec1 — APPROVED** [review]
could someone merge that revert so i can implement what  i meant to

**Comment by boodaliboo** [comment]
fuck off ynot im a living god

**Pull request merged**
