### PR TITLE
[META] Fixes some issues with the TEG and cleans up some decals

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

properly connects teg injectors to console, replaces the scrubber with a vent
cleans up on some ugly decals i missed when making the map

# Why is this good for the game?
bugfix
# Testing
none

# Spriting

# Wiki Documentation

# Changelog

:cl:  
mapping: makes meta teg console work
mapping: cleans up on some meta decals
/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
decals in the sat were just put in the other day, as I standardized all AI satellites having command decals rather than the lighter shade of blue which is reserved for medical areas
same deal in the bridge too, see #21554 for everythin that changed
also missing corners here
image
image

**Comment by N3D6** [comment]
> decals in the sat were just put in the other day, as I standardized all AI satellites having command decals rather than the lighter shade of blue which is reserved for medical areas same deal in the bridge too, see #21554 for everythin that changed also missing corners here image image

oh wtf my master wasn't up to date oopsies let me redo this

**Comment by N3D6** [comment]
i closed the wrong fuckin pr man i'm cooked af

**Comment by N3D6** [comment]
fuck me dude i gotta pay attention before i make prs 💀

**Pull request closed without merging**
