### PR TITLE
Adds random chapels again but this time without merge conflicts

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Adds variation to the chapels, allowing for anyone to add a custom chapel for box.
Also adds in Chapel 2, a variation of chapel with stairs (sorry koko) and an alternate layout.

# Spriting
Adds, yet another middle stair sprite, this time for dark_stairs.

image

# Changelog
:cl:  
mapping: Added Chapel Variation for box
mapping: Added Chapel 2 for box
imageadd: Added sprite for dark_stair middle
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
Im not going to add a pref.

**Comment by KingSuperBOB** [comment]
Cant wait for the 20 comments saying add pref

**Comment by MajManatee** [comment]
As biome said last time, add a pref

**Comment by azzzertyy** [comment]
> As biome said last time, add a pref

as bibby said last time, prefs are out of scope.

**Review by cuackles — APPROVED** [review]

**Review by Aquizit — CHANGES_REQUESTED** [review]
Both Chapel APCs are in the Chaplain's office. They need to be in the actual Chapel area.

Edit: oh I see what you've done, manually changed the APC areastring. Ok let me confirm something and I'll get back to this.

**Review by Aquizit — APPROVED** [review]

**Comment by Aquizit** [comment]
ok it's fine after all

maps are fine

**Comment by azzzertyy** [comment]
> Both Chapel APCs are in the Chaplain's office. They need to be in the actual Chapel area.
> 
> Edit: oh I see what you've done, manually changed the APC areastring. Ok let me confirm something and I'll get back to this.

tbh i dont remember doing this so it might just be a mistake ill check in a bit

**Comment by MajManatee** [comment]
i no longer care

**Pull request merged**
