### PR TITLE
Map and Flare are now a preference toggle

### PR DESCRIPTION
**Pull request by JamieD1**
Map and Flare are now a preference toggle

#### Changelog

:cl:  
rscadd: Map and Flare are now a preference toggle
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
please god no this will only make transitioning to non-box maps even harder because a ton of people wont have maps because preferences

**Comment by jcatjmeow** [comment]
Why

**Comment by Mesalikepie** [comment]
Dumping your map and flare aren't that hard. I agree with FLME. Transfer to less known maps will be a pain in the arse

**Comment by JamieD1** [comment]
> Dumping your map and flare aren't that hard. I agree with FLME. Transfer to less known maps will be a pain in the arse

You have the map name before you spawn and you have every chance to change your preferences before you start.

**Comment by JamieD1** [comment]
> Why

Because every round I ever play on box I am literally showing them away.

**Comment by Amelia0010** [comment]
this PR is bad and literally killed my grandmother

**Comment by Firewolf34** [comment]
I made 2/3 of the flares and even I think this is a good idea.

**Comment by athena413** [comment]
> > Dumping your map and flare aren't that hard. I agree with FLME. Transfer to less known maps will be a pain in the arse
> 
> You have the map name before you spawn and you have every chance to change your preferences before you start.

Every time we change maps we get one person that doesnt realize we're on that map and is likd "OH I DIDNT REALIZE IT WAS meta/delta/eclipse/omega"

even then you'd still get people who refuse to turn the preference on despite the map or dont even remember that it even IS a preference

sure, it's good QOL for BOX. but it makes the transition to other maps go from "somewhat annoying and difficult" to "AGONIZING and damn near impossible"

**Comment by Firewolf34** [comment]
That is all a very good point.

Here's the fix - make it selectable based on the map.

Or even better, involve playtime. If you have >100 hours on a map you can choose to hide it.

**Comment by Hopekz** [comment]
The negative reception here is dumb because it is literally just adding more player control to not take items if people don't want them.

**Review by patpol4 — APPROVED** [review]
It has map in the title, I approve

**Pull request merged**
