### PR TITLE
removes the stun from the hand because someone on discord told me to idk

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

gibongToday at 3:32 PM
@Redmoogle name something overpowered for me to nerf
RedmoogleToday at 3:32 PM
The hand

stuns bad

knockdown good

more fairer

#### Changelog

:cl:  
tweak: The Hand stand ability now knockdowns your opponent instead
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
apparently redmoogle made me do this because he got salty he died to a wizard

everyone laugh at him

**Comment by ynot01** [comment]
when you're so i ded that you get adam to make the PR during the round

**Comment by redmoogle** [comment]
image


I just said what was on my mind shush

**Comment by LoliconSlayer** [comment]
Adam is actually gibogne?????????
Aphie actualli roight!!!!!
Swissload actually do bad!!!!!!!!!!!!

**Review by fluffe9911 — APPROVED** [review]
i ded

**Pull request merged**
