### PR TITLE
makes floor cluwnes not emp 36 times

### PR DESCRIPTION
**Pull request by ShadowDeath6**
not sure if this is intended or not but this is cancer
yes this is an i ded pr

:cl:  ShadowDeath6
tweak: Floor cluwnes emp once rather than 36 times when emerging from the floor dimension
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
make the lube last a bit longer if you gonna nerf the E M P

**Comment by fluffe9911** [comment]
also it was emping so much because people kept dragging the victim which caused it to reset its attack stage causing it to emp again lol

**Comment by ShadowDeath6** [comment]
no it's because you put the emp in a for loop

**Comment by fluffe9911** [comment]
still buff the lube time

**Comment by SomeguyManperson** [comment]
:ok_hand: nice :ok_hand:

**Pull request merged**
