### PR TITLE
Re-alphabetizes sheet crafting menus

### PR DESCRIPTION
**Pull request by Cartlord**
# Document the changes in your pull request

A while back, I made a P.R., https://github.com/yogstation13/Yogstation/pull/11663 , which alphabetized the menus that pop up when you use sheets in-hand. Since others have made changes to these menus, some of my changes have been undone, so I'm fixing that. I also removed one gramatically incorrect hyphen in one sheet type's Examine text.
i honestly expect this to have an error that gets found during the lints check, but i think i'll be able to resolve that error myself, unlike last time - it'll just be a question of where the error is
EDIT: yep, linter found an error and i fixed it

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
tweak: Sheet crafting menus should be alphabetized, again!    
spellcheck: Bronze is now "wholly unsuitable" and not "wholly-unsuitable".  
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
I removed the ) that was causing the error, so I don't know what to do now. Do I need to close & reopen?

**Comment by Cartlord** [comment]
the linter errors are on files i did not change
how am i to cope

**Comment by Cartlord** [comment]
let's see if closing...

**Comment by Cartlord** [comment]
...and reopening works

**Comment by Cartlord** [comment]
nope

**Comment by JamieD1** [comment]
Compile

**Comment by Cartlord** [comment]
I probably shouldn't be surprised that the actual errors weren't showing at all - I only found it because I decided to dig through the files changed again, and I noticed two closed brackets needed moved.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
