### PR TITLE
Implements Nitrogen Narcosis

### PR DESCRIPTION
**Pull request by Altoids1**
## *Raptures of The Deep*

https://en.wikipedia.org/wiki/Nitrogen_narcosis

image

So I was googling about the maximum pressure humans can survive when I discovered that, apparently, nitrogen at high enough pressures can cause a giddy, hallucinogenic high. I thought this was really cool, and decided to add it into my video game.

I think this will help buff high-pressure environments, making their danger more resemble how it is in real life.

#### Changelog
:cl:  Altoids
rscadd: Nitrogen Narcosis has been added! Now N2O isn't the only thing that can get you giddy, and BZ ain't the only thing that can get you high.
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
You have all of these fun effects and you only added giggling and hallucinations

**Comment by MegaEmpirical** [comment]
Is this saying 480 kpa is needed for you to start seeing shit?

**Comment by Altoids1** [comment]
> Is this saying 480 kpa is needed for you to start seeing shit?

I believe so, yes.

**Comment by MegaEmpirical** [comment]
Interesting. Not sure how fast that level of pressure kills but I can't imagine many will live long to hallucinate. Still, should make for some funny last moments.

**Pull request merged**
