### PR TITLE
[Asteroid] Make atmosias pipes less cancer + minor atmos incinerator change

### PR DESCRIPTION
**Pull request by applepineapplepizza**
# Document the changes in your pull request

Expanded atmospheric distribution one tile north in order to make piping less chaotic (bendy pipes are messy)
Toxin firing ranged moved 1 tile north in order to make room for the additions

Changed walls to reinforced walls on neighboring department (tox mix -> atmos)
Changed some "inner" reinforced walls in atmos to walls (the outside is already reinforced)

Eliminated scrubbers/vents on layer 3 in atmos again (lmao why was this a thing)
Vaporized unneed manifolds in atmos (this was because the scrubbers/vents were on layer 3)

change the weird 2x2 shape of the incen to 1x3 (the reduction from 1x4 was good, but 2x2 seem awkward and bendy pipes)

~~Added incen access airlock from engine to incen (no maints access from incen, having another escape route is nice and allows for better collaboration between engineers & atmos)~~

the area below the incen is now dubbed "Construction Area". you can access it through engine bay (access for engineers) or by the incen(atmos acess). This change will allow better collaboration between engineers and atmos gamers

Better pipe layout for air supply pipes & dispose in atmos (weird to see air pipes go through walls/glass. they are now stack tighter together and go through airlocks)

resync'd the console in atmospheric distrbution to the corresponding gas tank (all the id's were set to AIR tank mix, they have now been properly resync'd)

Moved disposal to space pipe to a better location ( helps with clutter a bit in atmos)

Removed 3 water tanks near incen and replaced it with a high capacity water tank ( merge 3 into 1)

added a bit more lights to atmos to give more visibility 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl: 
mapping: expanded atmos distribution & toxins launch area one tile north
mapping: a few walls have changed in atmos to reinforced/regular walls
mapping: better pipe layout for atmospheric distribution 
mapping: resync'd atmos gas tank console to their respective gas
mapping: added more decals to atmospherics
mapping: add more lights to atmospheric distribution
mapping: atmos incen is now 1x3 instead of a 2x2
mapping: the area below the incinerator has changed to the construction area 
/:cl:

### CODE REVIEW

**Comment by applepineapplepizza** [comment]
BEFORE
oldatmos

AFTER
newatmos

pipes are being straighten out, removal of additional manifolds, and air/disposal pipes are stacked better in atmos

**Comment by MenacingManatee** [comment]
Looks a lot cleaner overall. Not seeing any major issues from the screenshots alone, but later today or tomorrow I'll open it up to look it over closer. Only issue I can see from the screenshot is this:

image

Shutter here needs to be moved down 1 tile OR walls need to be added to the left of this shutter

**Comment by ShoziOffical** [comment]
are the layer 2 and 4 (air pipe and scrubber) hidden behind a floor

**Comment by applepineapplepizza** [comment]
> are the layer 2 and 4 (air pipe and scrubber) hidden behind a floor

I went to check to double make sure and they are!
pipesarehiden

pipes are indeed hidden

**Comment by ShoziOffical** [comment]
hmm look clean

**Comment by applepineapplepizza** [comment]
The reimagined atmos port room!
BEORE
oldatmospt2

AFTER
newatmospt2

**Comment by MenacingManatee** [comment]
Just looked it over.

image

Not sure about a new entrance connecting atmos and engineering through the turbine, especially since the door is atmos access (code 24) allowing atmos techs direct access to the engine room, need an opinion from @ToasterBiome or Jamie on this

Other than that, no real feedback. All connections seem to be there, the decals look good, and I am astonished at how clean you got the piping

**Comment by MenacingManatee** [comment]
After talking it over with baiomu, this is the solution we agreed on.

image


Please change the atmos door I highlighted in my previous post to an engineering door, and add 2 atmos doors separating the turbine from the build area. This designated the build area as a sort of communal area for both atmos and engineering, while providing neither free access to the others' space

**Comment by applepineapplepizza** [comment]
uh oh it no workey

**Comment by Moltijoe** [comment]
my god that changelog is a nightmare to read

i don't play atmos, but all changes look like they would be rather nice

**Comment by applepineapplepizza** [comment]
ugh it keeps closing due to me re-merging with the upstream. sorry.

**Comment by applepineapplepizza** [comment]
OK MERGED WORK!! WOOHOOO!!

Some of the changes as requested: 
constructionarea

Since this is going to be a communal area, the area has been designated as the construction area. New area has been outfitted with APC, camera, fire extinguisher and 3 new doors! one door leads to the engine room and has access only given to engineers. The other two doors are for atmos techies.

EDIT: gonna recheck everything. manatee found a sus windoor in toxins area 😢

**Comment by applepineapplepizza** [comment]
> my god that changelog is a nightmare to read
> 
> i don't play atmos, but all changes look like they would be rather nice

i reduced it. let me know if its still a nightmare to read!

**Comment by MenacingManatee** [comment]
image

This tile needs its area fixed

After a once over everything else looks good!

**Review by MenacingManatee — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
