### PR TITLE
Adds back command EVA suits

### PR DESCRIPTION
**Pull request by Ktlwjec**
KMC's suits from prebase, added to box and delta.

:cl:  
rscadd: Command EVA suits, available in boxstation and deltastation EVA.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Stop making me go to the icon bot and post screenshots or pretty pictures

**Comment by MegaEmpirical** [comment]
I'm going to arrest people so hard.

**Comment by alexkar598** [comment]
SMH Lyis is hard

**Review by nesisknesis — APPROVED** [review]
chrono legionnaires

**Pull request merged**
