### PR TITLE
Removes "Ghosts N Stuff" 

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request

turns out the youtube video I got it through has some dudes intro in it woops

ah whatever, we can replace it with something /cooler/ later.

# Wiki Documentation

Remove this text and write all information regarding your changes that should be known and documented through the Yogstation Wiki. 
Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscdel: Removed a song
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
If only this was reviewed before it was merged

**Comment by JamieD1** [comment]
Can you just upload an edited sound please instead of just yeeting it?

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Get a version that doesn't have the intro in it instead of yeeting it out

**Comment by maxion12345** [comment]
k

**Pull request closed without merging**
