### PR TITLE
Removes STATE YOUR LAWS from god speak. Fed up of its abuse.

### PR DESCRIPTION
**Pull request by JamieD1**
Removes STATE YOUR LAWS from god speak. Fed up of its abuse.

### CODE REVIEW

**Review by adamsong — APPROVED** [review]

**Comment by Bibby0110** [comment]
Fill out the template

**Comment by Hopekz** [comment]
u ded

God speak is supposed to be something rare not just bussed in every round. If it is actually obtained the proper way why is this an issue and considered "abuse" when it is one of the abilities?

this is on bad admemes if god speak is just being given out all the time.
Maybe make a different version of god speak that doesn't have any of the actual abilities if staff want to keep handing it out.

**Comment by N3D6** [comment]
> u ded
> 
> God speak is supposed to be something rare not just bussed in every round. If it is actually obtained the proper way why is this an issue and considered "abuse" when it is one of the abilities?
> 
> this is on bad admemes if god speak is just being given out all the time.
> Maybe make a different version of god speak that doesn't have any of the actual abilities if staff want to keep handing it out.

Staff aren't even handing it out, you get it from killing an easy megafauna with attacks that can be mostly ignored.

**Comment by N3D6** [comment]
maybe a better change than all out deleting it would just be to make it not state hacked/malf laws

**Comment by Cartlord** [comment]
But then why have it at all?

**Comment by maxion12345** [comment]
this is a sole ability intended to cuck malf/rogue borgs. Hell, my last AI round I got subverted and we only got found out after a miner decided to go checking laws with god-voice

we murdered them afterward, but still

**Pull request merged**
