### PR TITLE
removes all the stupid murderbone bubblegum loot

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

goodbye

# Wiki Documentation

bubblegum only drops heck suit and knuckles

# Changelog

:cl:  
rscdel: bubblegum only drops heck suit and knuckles
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
stomach is murderbone?

**Comment by 00ze-cyclone** [comment]
> stomach is murderbone?

Vomit is a very deadly bioweapon apparently.

**Comment by SomeguyManperson** [comment]
> stomach is murderbone?

do i need to add "validhunt" to get the point across for an item that gives you the ability to turn invisible and fuck around with noclip

**Comment by ToasterBiome** [comment]
> > stomach is murderbone?
> 
> do i need to add "validhunt" to get the point across for an item that gives you the ability to turn invisible and fuck around with noclip

if i rework it to be less stupid can we keep it

**Comment by SomeguyManperson** [comment]
> > > stomach is murderbone?
> > 
> > 
> > do i need to add "validhunt" to get the point across for an item that gives you the ability to turn invisible and fuck around with noclip
> 
> if i rework it to be less stupid can we keep it

how

**Comment by MusselMain** [comment]
> > stomach is murderbone?
> 
> do i need to add "validhunt" to get the point across for an item that gives you the ability to turn invisible and fuck around with noclip

There's a lot of purging going on, which kinda sucks, I feel like there needs to be more reworking, or better yet adding items to fill this gap, only having a couple items as a reward for beating the hardest boss in the game seems problematic

**Comment by ToasterBiome** [comment]
> > > > stomach is murderbone?
> > > 
> > > 
> > > do i need to add "validhunt" to get the point across for an item that gives you the ability to turn invisible and fuck around with noclip
> > 
> > 
> > if i rework it to be less stupid can we keep it
> 
> how

Flip between pools of vomit like a sentient disease through their hosts, can only “move” through tiles that have vomit in them, so you can’t just noclip through walls and see the vamp sucking a guy in maint

**Comment by ToasterBiome** [comment]
https://github.com/yogstation13/Yogstation/pull/14215

**Comment by Simplehorror** [comment]
🥱

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
