### PR TITLE
Transfer mix

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request
image
image

Adds Transfer Mix a *very* expensive alcohol that kills you made with 5 bacchus, 5 hooch, and 5 beepsky smash to make 1u.

Will kill you in a couple of sips

#Wiki
5 bacchus, 5 hooch, and 5 beepsky smash to make 1u.

# Spriting
Above

# Changelog

:cl:  
rscadd: Adds transfer mix drink
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
its ok because chemistry is already broken

**Comment by Georgeur** [comment]
have you considered this might be used on someone who perhaps doesnt want to mcfucking die

**Comment by KillerOrcaCora** [comment]
Wha- Huh? Is there a punchline I'm missing or something?

**Comment by redmoogle** [comment]
> Wha- Huh? Is there a punchline I'm missing or something?

as I missing something. All I see is people downvoting and giving no reason. if its because its "broken" consider other chemicals that are easier to make.

**Comment by ghost** [comment]
Make it explode like a maxcap so it will be totaly balanced and not useless

**Comment by Marmio64** [comment]
> > Wha- Huh? Is there a punchline I'm missing or something?
> 
> as I missing something. All I see is people downvoting and giving no reason. if its because its "broken" consider other chemicals that are easier to make.

booze will fuck you up fast and also destroy your liver, making it a lot more annoying to revive you. Couple that with the fact that the bartender can make shotgun darts and the drink's booze power is extremely dense, its really not a good mix. At least chemistry is for the most part restricted to the chemists, i dont think you need to give other jobs more ways to completely fuck over someone with a small amount of chems.

**Review by KillerOrcaCora — APPROVED** [review]
Death syringe shaped cup is funni

**Comment by JamieD1** [comment]
Don't like the idea of being able to kill people so easy with a drink which is not hard to use,

**Pull request closed without merging**
