### PR TITLE
[box] makes outside of lawyers office a little less goofy and splits lawyer's office

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

Buttons open a table + window between the two if they wanna talk and stuff.

Wiki Documentation:

Lawyer's Office looks different again

:cl:  
mapping: Outside of Lawyer's Office on BoxStation is a little less goofy with protruding maint
mapping: BoxStation Lawyer's Office CHANGED AGAIN
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
Where the hell is dets office

**Review by Ethan4303 — APPROVED** [review]
YUH HUH

**Comment by Ethan4303** [comment]
> Where the hell is dets office

dets office is in arrivals hall now, kinda where the abandoned clerk store was

**Comment by wonderinghost** [comment]
Ah ok. Now I can build a inspection booth on the other wall

**Review by Ethan4303 — APPROVED** [review]
YOWZAAA!!!!!!!

**Comment by Ethan4303** [comment]
Imagine having merge conflicts, couldnt be me

**Pull request merged**
