### PR TITLE
Makes nullrods being reskinnable after first reskin

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Gets rid of useless code that makes it annoying to fix stuff

### Why is this good for the game?

Less nuisance to admins

#### Changelog

:cl:  
tweak: Nullrods now dont stop eachothers reskinning
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
This is not a fix?

**Comment by MrHorizons** [comment]
Not a fix, but good PR.

**Comment by Amelia0010** [comment]
Not a fix.

**Comment by MegaEmpirical** [comment]
What is this doing exactly?

**Comment by redmoogle** [comment]
> What is this doing exactly? 

Making it so admin spawning nullrods allows reskinning and reset the holyweapon ert get

**Comment by MegaEmpirical** [comment]
Are you saying that once a null rod has been used that any other null rod spawned in that round currently takes on the form of the first?

**Comment by MrHorizons** [comment]
> Are you saying that once a null rod has been used that any other null rod spawned in that round currently takes on the form of the first?

As of right now, yes.

**Pull request merged**
