### PR TITLE
Ninjas speak Japanese

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

I mean, they're ninjas, they shouldn't be doing muh friendly ninja hi just gimme all your research!!!!!

syllables shamelessly stolen from here: https://www.freejapaneselessons.com/lesson01.cfm

#### Changelog

:cl:  
tweak: The Spider Clan has recently been teaching their ninjas japanese, since it's the language used within their command structure
/:cl:

### CODE REVIEW

**Comment by GenericDM** [comment]
Maybe their headset could only be able to broadcast on Syndie/NT channel?

**Comment by HomocidlePancakes** [comment]
Just make ninjas talk in MGS refrences.

**Comment by Altoids1** [comment]
You could also have them speak in Space Japanese, meaning they have to be manually translated by some translator or NTSL script or something.

**Comment by GenericDM** [comment]
this new one is cool and good 👍

**Comment by Altoids1** [comment]
I like the new change, is nice. 👍 


Let it be remembered that Nichlas was the one who added *Japanese* to the game.

**Comment by ThatLing** [comment]
watashi

**Comment by Amelia0010** [comment]
wa

**Pull request merged**
