### PR TITLE
Initial yogstation

### PR DESCRIPTION
**Pull request by Amelia0010**
Added psych, clerk and paramedic and removed the gateway. @ThatLing i'd say this is mergable

### CODE REVIEW

**Comment by DLCabbose** [comment]
Looking through these git updates is like being the fly on the wall of a solitary cell listening to the occupant slowly go mad.

**Comment by Bawhoppen** [comment]
What are you even doing? Looks like weird stuff in your commits.

**Comment by Amelia0010** [comment]
well you see, ninja did a rework of shuttles, which removed turf_type, which I then had to mirror in my map :)

**Comment by Amelia0010** [comment]
oh right the turf_types

**Pull request merged**
