### PR TITLE
Gives QM access to mining sec checkpoint

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

The checkpoint is in the QM's department, therefore they should have access.

# Changelog

:cl:  
tweak: Added QM access to the cargo sec checkpoint
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
why tho

**Comment by adamsong** [comment]
Its in their department, they should have access to it

**Comment by Reed0506** [comment]
why would the QM need to ever go in there for non-antag activites

**Comment by ynot01** [comment]
QM is not a head and cargo is not theirs it is the HoP's, they are basically the warden of cargo

**Comment by maxion12345** [comment]
qm not a hed
hop is head of cargo as cargo is a civilian department and thusly gets access to that sec area

**Comment by JamieD1** [comment]
Yeah I know you are doing this because of the whole brig Phys thing. But its not worth it. Its just not.

**Comment by Marmio64** [comment]
this is a different case since wardens often need medical stuff to treat prisoners when there is no brig phys, since warden's job is to protect and care for prisoners, meanwhile the QM doesn't need anything from the sec checkpoint in order to do his job.

**Pull request closed without merging**
