### PR TITLE
Tweaks to IPC martial arts

### PR DESCRIPTION
**Pull request by Moltijoe**
Now that is actually been used, finally got some feedback

Cutting off limbs to force drop the guns doesn't cause them to disappear
There's no sound or visual feedback to the grab intent action
Too easy to get dismembered, ends the fun too fast
Gives the revolver it's own bullet type, rather then using det's negative armour pen bullet

new dash sound effect courtesy of ynot01
https://user-images.githubusercontent.com/108117184/206584706-4d3086bb-b69c-47dc-8049-b274bb22317b.mp4

:cl:  
bugfix: IPC martial art guns disappear when the limb gets cut off
tweak: IPC martial art now plays a sound when doing the grab intent action
tweak: IPC martial art gives TRAIT_NODISMEMBER
tweak: IPC martial art revolver now uses a special ammo
/:cl:

### CODE REVIEW

**Review by MajManatee — APPROVED** [review]
Still havent seen it myself, but sure

**Review by MajManatee — APPROVED** [review]
smh this guy, doesn't mark his PR as a draft when he's still working on it.

**Comment by Moltijoe** [comment]
> smh this guy, doesn't mark his PR as a draft when he's still working on it.

that's the thing, it WAS done, until people gave more feedback

**Comment by Burger1998** [comment]
Please god merge this the martial art aint worth it right now

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
