### PR TITLE
Reverts (fixes) pressure tanks looking like garbage

### LINKED ISSUE #21669: oh god oh fuck what happened to the air tanks
## Test Merges: 
Not Supplied / None
## Reproduction:
why are they colored blobs
## Supplied Image:

SuppliedImage
 Submitted by: yarinoi (718841144351522967)

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
Added in GAGS, these pressure tank sprites seem to support smoothing but are objectively worse and look like they were designed in 20 seconds. Smoothing is cool but isn't needed when these tanks can't even be interacted with, and the old sprites we had were more detailed and straight up better.

also biome said reverting this was fine
actually closes #21669 

# Why is this good for the game?
don't think this was done intentionally

# Testing
(From left to right: air, co2, plasma, oxygen, nitrogen)
image

image

# Spriting
What they currently be lookin like (courtesy of yarinoi):
image

What they should be lookin like:
image

# Changelog
:cl:  
rscdel: Reverted ugly ass pressure tanks
bugfix: Fixed pressure tanks unintentionally looking ugly as hell, they now look normal
imagedel: Deleted ugly ass pressure tank sprites
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
This sprite could definitely use GAGS I think

**Comment by cuackles** [comment]
Oh yeah this ones look horrid idk how i didn't catch it

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
make them use GAGS

**Comment by AMyriad** [comment]
> make them use GAGS

sure but then I'm making the nitrogen tanks green

**Comment by Cartlord** [comment]
Errors in RuntimeStation checks seem to start at https://github.com/yogstation13/Yogstation/actions/runs/8479703135/job/23234189980?pr=21715#step:12:27, hope that helps you narrow down the problem

**Comment by Cartlord** [comment]
Compile's hitting problems at & around https://github.com/yogstation13/Yogstation/actions/runs/8501731777/job/23284950036?pr=21715#step:6:22 and https://github.com/yogstation13/Yogstation/actions/runs/8501731777/job/23284950036?pr=21715#step:6:27

**Comment by AMyriad** [comment]
Didn't forget about this, going to finish it after exams are over

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
