### PR TITLE
Added OmegaStation to vote list

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Adds OmegaStation to vote list

#### Changelog

:cl:  
rscadd: Added Omegastation to vote list
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Might as well add IceBox since this is a config change so both get knocked out at once with 1 approval

**Comment by JamieD1** [comment]
Thought Icebox crashed a lot? 

Maybe we shouldn't let that one be votable without admins on to reboot.

**Comment by Hopekz** [comment]
> Thought Icebox crashed a lot?
> 
> Maybe we shouldn't let that one be votable without admins on to reboot.

I'm not aware of any crashes at the moment. 
If this is actually true then maybe it is best to leave them out.

@SomeguyManperson ;
Does IceBox crash our server?

**Comment by alexkar598** [comment]
Icebox is still in a beta ish phase atm as far as I am aware

**Comment by Jarod1200** [comment]
Can you make it so if there is more than a certain number of players it's removed from the list? This station is kinda aids with more than like 40 people

**Comment by JamieD1** [comment]
> Can you make it so if there is more than a certain number of players it's removed from the list? This station is kinda aids with more than like 40 people

It has a max player count of 35 I believe.

**Comment by alexkar598** [comment]
Omegastation is a really bad map compared to pubby which is omega but better. I'd rather have the map pool bring quality instead of quantity

**Comment by MegaEmpirical** [comment]
I fucking like omega and want it and it's by player choice

**Comment by aaqe** [comment]
I love this map. Please let us play it on low pop!

**Comment by Hopekz** [comment]
Seeing the support on this; reopening it as it was closed for a weird opinion reason.
We have lowpop on our server which pubby doesn't fulfill. 

If we plan to remove this from the vote rotation we need to remove it entirely because what is the point of keeping the map itself if it'll not be used?

Even on the admin side, you making this not a part of the actual vote forces us to make a weird Janky map vote from scratch which is just awkward to create.

Also; it is a matter of opinion because I personally think pubby is shit compared to omega.

**Comment by alexkar598** [comment]
No.

**Comment by Hopekz** [comment]
Alright well, I won't let 1 opinion stop this without a fair decision seeing as this has support. 
I want an official decision to be made so I guess the council now needs to vote on it since you're turning this "controversial"

Opening right now; do not merge until this gets settled.

**Comment by MegaEmpirical** [comment]
It's definitely not controversial if only one person dislikes it

**Pull request merged**
