### PR TITLE
Bluespace locker only has a 33% chance to spawn

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

makes it less useful

# Wiki Documentation

# Changelog

:cl:  
tweak: Bluespace locker only spawns 33% of the time
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Consistency is good game design.

A good example I was given in the past is instead of making wood randomly not set on fire when you use fire starting item on it, instead change how that wood burns.

So in this case instead of making it inconsistent it would be better for the game design to change how the locker behaves.

This change would only belong if there was an in-game way to know if the locker spawned so someone that spends 40 minutes looking for it doesn't get shafted.

**Comment by Bibby0110** [comment]
> Consistency is good game design.
> 
wrong

> A good example I was given in the past is instead of making wood randomly not set on fire when you use fire starting item on it, instead change how that wood burns.
>
sounds like bad game design

> So in this case instead of making it inconsistent it would be better for the game design to change how the locker behaves.
> 
disagree
> This change would only belong if there was an in-game way to know if the locker spawned so someone that spends 40 minutes looking for it doesn't get shafted.
don't care, don't spend 40 minutes looking for it. the bluespace locker is supposed to be a fun gimmick if you find it, not something you spend your whole shift hunting for

**Comment by Hopekz** [comment]
> > Consistency is good game design.
> 
> wrong

We won't find any common ground if you don't think consistency is good for game design since that is a fundamental design principle.

This change goes against consistency whether you agree or disagree.

**Comment by N3D6** [comment]
This sucks

**Comment by Notamaniac** [comment]
Did the bluespace locker hurt you deeply at some point or something

**Comment by JamieD1** [comment]
Prefer #14288

**Pull request closed without merging**
