### PR TITLE
Add new alt title for captains "Big Boss"

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Adds a new alternate title for fans of the metal gear series to use when being captain

# Why is this good for the game?

https://www.youtube.com/watch?v=m2OR_JaXDaM

# Testing

I've done this PR before refer to my ripperdoc pr

# Wiki Documentation

we dont document these

# Changelog

:cl:  
rscadd: Adds new alt title for captains "Big Boss"

/:cl:

### CODE REVIEW

**Comment by Am37000** [comment]
yeah sure why not

**Comment by nesisknesis** [comment]
Informal titles should be left to people to change themselves in game. 

The station as we develop it should at least be believeable in the ss13 setting, and lazy references like this will just confuse and devalue it.

**Comment by cowbot92** [comment]
> Informal titles should be left to people to change themselves in game.
> 
> The station as we develop it should at least be believeable in the ss13 setting, and lazy references like this will just confuse and devalue it.

I disagree and think that more references makes the game much more enjoyable, whether the media referenced is something obscure and popular it allows people to better connect with the game.

**Comment by nesisknesis** [comment]
> > Informal titles should be left to people to change themselves in game.
> > The station as we develop it should at least be believeable in the ss13 setting, and lazy references like this will just confuse and devalue it.
> 
> I disagree and think that more references makes the game much more enjoyable, whether the media referenced is something obscure and popular it allows people to better connect with the game.

I am not saying references are bad for the game, I am aware this game is built on references but there is a definitely an art to implementing them. Ideally you want them to be subtle or make sense within the context of our game so that we have our own identity. 

For instance we do or did at some point, have stormtrooper armour available from cargo. It was literally called and looked like stormtrooper armour. As a result this is just Star Wars, not SS13. Compare this to e-swords which are a good reference. They act and look like lightsabers but in context they are available as concealable weapons for the Syndicate, and aren't literally called lightsabers. 

I hope this explains my point. There are good references that serve our identity and setting, and then there are bad references that detract from it and take you out of it. I believe this is the latter.

If players really want to, they can change their ID to be "Big Boss" and I think that is perfectly fine. As I said before: "The station as we develop it should at least be believeable in the ss13 setting,"

**Comment by Chubbygummibear** [comment]
how can the captain be big boss if he can't cqc me. you should give captains using the "big boss" title cqc just for authenticity :^)

**Comment by cowbot92** [comment]
> how can the captain be big boss if he can't cqc me. you should give captains using the "big boss" title cqc just for authenticity :^)

no it'd be too authentic then the reference would be too on-the-nose

**Comment by LazennG** [comment]
the man who sold the nuke disk

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
requires headdev approval, but i don't see why not
references are the lifeblood of ss13

**Review by ToasterBiome — APPROVED** [review]
if you make more MGS references i explode your head

**Pull request merged**
