### PR TITLE
Mimes can't talk or whatever

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Mimes can't talk or whatever

#### Changelog

:cl:  
tweak: mimes can't break their vow of silence anymore
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
Doesnt stop mimes from just messaging people with there pda which is what most mimes use to bypass the no talking thing so eh

**Comment by HomocidlePancakes** [comment]
This is dumb. Just make them puke blood every time they talk

**Comment by Jc1469** [comment]
**The Mime** i dont understand what this fixes
**The Mime** i can just use me to talk instead lmao like every mime does anyway
**The Mime** why not just delete mime

**Comment by HomocidlePancakes** [comment]
>Council Vote

W h y?

**Comment by Altoids1** [comment]
https://forums.yogstation.net/index.php?threads/vote-merge-this-pr-https-github-com-yogstation13-yogstation-tg-pull-5068.18845/

Closed.

**Pull request closed without merging**
