### PR TITLE
Fixes plastic surgery only working via putting in pretty filter names

### LINKED ISSUE #17134: Plastic Surgery Doesn’t Work
### Severity

Inconvenience

### Short Description

Plastic Surgery doesn’t work / do anything.

### Reproduction

1.) start plastic surgery 
2.) get to the step where you get to change the pt’s name
3.) input name into box
4.) name change does not go through 
5.) cry 

### Round ID

N/A

### Test Merges

_No response_

### BYOND Username

_No response_

### Additional information

This has happened on multiple rounds, and it’s widely known amongst high level medical players that it’s broken, but for some reason no one’s made an issue about it??

I remember being able to successfully do plastic surgery when you had to choose a random name out of a list.

### PR DESCRIPTION
**Pull request by Notamaniac**
# Document the changes in your pull request

Fixes #17134

would notpretty() return false if it was not the case that notpretty() would not not return true on not inputting words that would not be in the prettyfilter list?

# Spriting
N/A

# Wiki Documentation

N/A

# Changelog

:cl:  
bugfix: You no longer need to practice racism or bigotry to finish plastic surgery
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
There was a mechanic like that?

**Comment by ChuChu42** [comment]
> There was a mechanic like that?

i tested this on a version of yog master from 2 months ago

plastic surgery names didnt work correctly but putting the N word in the name box worked

**Comment by 00ze-cyclone** [comment]
This is actually a nerf of the plastic surgery, having the N word as your name made you impossible to snitch since anyone trying to say your name trigger the filter, stopping them.
The balance is forever ruined now that the bigot memetic shield is gone.

**Comment by KillerOrcaCora** [comment]
You can never take my slurs

**Comment by Maia-J** [comment]
> You can never take my slurs

No way based and lizard ERPilled

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
