### PR TITLE
changes up some plasmaman helmets sprites, adds some new ones

### PR DESCRIPTION
**Pull request by tattax**
despite being kind of just this i rewrote the code so it is easier to make a new mask variant and doesn't require you to make a new sprite for every mask you make

# Document the changes in your pull request

as above, changes up how some sprites look, open to feedback

# Spriting

<details>
 <summary> </summary>

moved slit a bit to the side, and made it a bit chunkier
image
image

adds more fluff to nyan
image
image
image

adds bane v2
image
image
image
image

resprite wizard's look on item
image
image

adds enviroplate
image
image
image
image

and envirolow
image
image
image
image

</details>

:cl:   
imageadd: new sprites + new plasmaman helmet variants
/:cl:

### CODE REVIEW

**Review by cuackles — CHANGES_REQUESTED** [review]
not a fan of changing the bane one that much cus, its not based of bane its based on this 
image
and gassy one wasnt based on just a gasmask it was based on dreams gasmask from dc
image
would preffer if the ones i made stayed as they are
on other note, does the overlay also apply in the item form ? could you show how does the new system looks ingame ?

**Comment by cuackles** [comment]
Forgot to say but i do like the bane one pls make that one a thing without killing the other

**Comment by tattax** [comment]
> on other note, does the overlay also apply in the item form ? could you show how does the new system looks ingame ?

same as before, nothing changed much except how they're handled internally, that's why it's not cited

**Comment by cowbot92** [comment]
Not bad changes.

**Comment by cuackles** [comment]
allrigth then just remove the changes from both of the ones i mentioned, the rest of the changes are fine and probably add the bane one as a separate mask, but also i do want ingame screenshots of the new ones you added

**Comment by tattax** [comment]
zQblwYFXOt

woqFyXMPHK

**Comment by tattax** [comment]
image

**Comment by MajManatee** [comment]
we have league of legends content in our game...

**Comment by cuackles** [comment]
Hmmm not really a fan of enviroface, feels a bit like a gimp suit mask and it's kinda simplistic, think there is a way u can make it a bit more interesting or notable ? Maybe copy the style of a sky mask or a luchador mask ? Tho i very much like the envirolow

**Comment by tattax** [comment]
Yecj3xddOf

**Review by cuackles — APPROVED** [review]
ok thats a very very good update

**Pull request merged**
