### PR TITLE
Enable cowboy as a roundstart AI lawset

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Enables Cowboy as a roundstart AI lawset with the same weight as CEO, Crewsimov, or Asimov

# Changelog

:cl:  
tweak: Enabled cowboy as a roundstart AI lawset
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
this one is based

**Comment by MenacingManatee** [comment]
yes pls :D

**Comment by Cartlord** [comment]
YYYY****EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE****-

**Comment by Marmio64** [comment]
i like the lawset but i feel like 6 is too high of a weight

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
