### PR TITLE
Polysmorph tweaks

### PR DESCRIPTION
**Pull request by Mqiib**
Makes polysmorphs more xeno-ey by giving them straight up acid blood, making them extremely resistant to acid damage, but take 1.5x burn damage. This means that now you can actually refill their blood as well as making them a bit more unique since acid resistance isn't really something anyone else has. To counter this relatively minor buff, they now take significantly more damage from lasers and fire.

Quick addition: you can also select whether or not you want a tail as opposed to having a 50/50 chance of being cursed with no tail.

#### Changelog

tweak: Polysmorphs now take 1.5x burn damage  
tweak: Polysmorphs now have actual acid blood and very high resistance (80% reduction) to acid damage.
bugfix: You can now select if you want a tail.
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
I remember the original plan for them was to have a unique hivemind chat (like the one xenos have) with the drawback of not being able to talk outside of said hivemind

**Comment by Mqiib** [comment]
That's too much work

**Comment by Marmio64** [comment]
> I remember the original plan for them was to have a unique hivemind chat (like the one xenos have) with the drawback of not being able to talk outside of said hivemind

that would just make polysmorphs be abductors version 2

**Comment by UselessTheremin** [comment]
> > I remember the original plan for them was to have a unique hivemind chat (like the one xenos have) with the drawback of not being able to talk outside of said hivemind
> 
> that would just make polysmorphs be abductors version 2

i mean the radio is kinda already like that kek
"SSssssSsssssssSSSSSSssssss"
"sssSSSSsssSsssssSSSSSSsssSSss"
"ssSSSSssssSSSSSSsssSSSSSS"

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
