### PR TITLE
Fixes oversight with RPD not obeying density

### PR DESCRIPTION
**Pull request by Simplehorror**
Anyone with a Rapid Pipe Dispenser could use it to go through windows or any tiles containing dense atoms given the proper equipment due to the fact it could place disposal pipes on dense atoms, this should not break any pre-existing behaviour aside from the fact you may need to break some windows if you want to fix a disposals network.
:cl: maxion12345, Simplehorror
bugfix: Rapid Pipe Dispensers can no longer print transit tubes, disposal pipes or plumbing pipes on turfs containing dense atoms.
/:cl:

### CODE REVIEW

**Review by tattax — CHANGES_REQUESTED** [review]
yarn

**Comment by bruhlookatthisdood** [comment]
will it still work on windows?

**Comment by Simplehorror** [comment]
> will it still work on windows?

no, description updated

**Comment by Simplehorror** [comment]
https://github.com/tgstation/tgstation/pull/62387 - example of TG PR that serves a similar purpose

**Comment by bruhlookatthisdood** [comment]
> > will it still work on windows?
> 
> no, description updated

download

**Comment by bruhlookatthisdood** [comment]
it should be able to go under windows (only air pipes not disposals or transits)

**Comment by Simplehorror** [comment]
Air pipes were not modified, behaviour is the same

**Comment by bruhlookatthisdood** [comment]
> Air pipes were not modified, behaviour is the same

yes but on maps alot of pipes go through windows (i think) so I think that its only walls that should be blocked from having atmospheric piping going through them.
obviously there shouldnt be transit tubes/disposal tubes going through windows because those are too large but realisticly the atmospheric pipes could probably just stick to the tile underneath the window itself.

**Comment by Simplehorror** [comment]
> > Air pipes were not modified, behaviour is the same
> 
> yes but on maps alot of pipes go through windows (i think) so I think that its only walls that should be blocked from having atmospheric piping going through them. obviously there shouldnt be transit tubes/disposal tubes going through windows because those are too large but realisticly the atmospheric pipes could probably just stick to the tile underneath the window itself.

Again, I haven't touched the code for air pipes, they are the same behaviour as they were before. If they go through walls and windows already, which I believe they do, this PR will not change that

**Comment by bruhlookatthisdood** [comment]
> > > Air pipes were not modified, behaviour is the same
> > 
> > 
> > yes but on maps alot of pipes go through windows (i think) so I think that its only walls that should be blocked from having atmospheric piping going through them. obviously there shouldnt be transit tubes/disposal tubes going through windows because those are too large but realisticly the atmospheric pipes could probably just stick to the tile underneath the window itself.
> 
> Again, I haven't touched the code for air pipes, they are the same behaviour as they were before. If they go through walls and windows already, which I believe they do, this PR will not change that

ah, i misread plumbing pipes as atmospheric pipes (dont ask me how)

**Comment by patpol4** [comment]
seems intended

**Comment by Simplehorror** [comment]
Does not seem intended considering the fact it blocks on closed turfs, and one could initially assume it would block windows as it closes a turf from air.

**Comment by Simplehorror** [comment]
References:
https://github.com/tgstation/tgstation/pull/29262
https://github.com/tgstation/tgstation/issues/16855
https://github.com/tgstation/tgstation/pull/14809

Seems that you could place (disposal) pipes under any walls, including indestructible walls. Someone made a PR to fix it and blocked it on all dense turfs and then someone made a PR to unblock it on turfs that have no walls but are dense.

**Review by SomeguyManperson — APPROVED** [review]
the only reason people are confused about this is probably because nobody has done it here so they don't know how bad i t'd be

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
