### PR TITLE
[BOX] Removes Psychiatrist Straight Jacket & Muzzle, Moves Medbay SJ&M to CMO Locker, Adds Muzzle to Perma

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Removes the straight jacket and muzzle from the psych office, because people keep using it to grief as per Cowbot93's notification to me about this

Moves the ones in the Medbay Aft area into the CMO locker, because you need a head to sign off on that

Adds a Muzzle to brig for those unruly ~~prisoners using thier right to free speech~~ Voice of God havers

# Changelog
:cl:  
rscdel: BOX Psychiatrists no longer get a straight jacket and muzzle in their office
rscadd: BOX Perma now has a spare Muzzle  
tweak: BOX Medbay's Straightjacket and Muzzle are now in the CMO Locker
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
I think it isn't people but one guy with helluva lot of alts

**Comment by VaelophisNyx** [comment]
likely
but
good change

**Comment by cowbot92** [comment]
thank christ

**Comment by GraveHat** [comment]
It doesn't make thematic sense and puts another load onto the CMO for them to get the equipment for the psychiatrist just because there's one guy who keeps coming back to grief. I don't want this to signal to any other griefers that even something as minor as this would get them to affect the codebase when this problem could easily be ahelped.

**Comment by VaelophisNyx** [comment]
remember to switch branches kids

**Comment by cowbot92** [comment]
> 

How often do you see a psych, or anyone really, use the straight jacket for anything that isn't either straight up just kidnapping people, or baby-jailing them so hard that they may as well ghost? Why did we add a bomb limit? Because griefers kept maxcapping. Why did we make it so you need CE/head permission to use the PA generator outside engineering? Because griefers kept ruining rounds upon rounds by building a singularity generator. If we could just *handle* it with a simple ahelp we would, and it's not being straight up removed so it's not like if you don't have a legitimate cause you can't just ask your dumb boss you get you the dumb baby-jail jacket.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> How often do you see a psych, or anyone really, use the straight jacket for anything that isn't either straight up just kidnapping people, or baby-jailing them so hard that they may as well ghost? Why did we add a bomb limit? Because griefers kept maxcapping. Why did we make it so you need CE/head permission to use the PA generator outside engineering? Because griefers kept ruining rounds upon rounds by building a singularity generator. If we could just _handle_ it with a simple ahelp we would, and it's not being straight up removed so it's not like if you don't have a legitimate cause you can't just ask your dumb boss you get you the dumb baby-jail jacket.

okay but this doesn't prevent them from making zipties or printing handcuffs from a hacked autolathe so i dont know what this is supposed to accomplish outside of making a meme job even less useful

**Comment by VaelophisNyx** [comment]
those things take even a hair of effort to do, not just
unlock a locker
grab the thing
go greif-

**Comment by Maia-J** [comment]
> those things take even a hair of effort to do, not just unlock a locker grab the thing go greif-

- Spawn in on boxstation. Go left for one minute. Get cable ties from one of the 5 toolboxes. Timeloss: 2 minutes

**Comment by cowbot92** [comment]
> > How often do you see a psych, or anyone really, use the straight jacket for anything that isn't either straight up just kidnapping people, or baby-jailing them so hard that they may as well ghost? Why did we add a bomb limit? Because griefers kept maxcapping. Why did we make it so you need CE/head permission to use the PA generator outside engineering? Because griefers kept ruining rounds upon rounds by building a singularity generator. If we could just _handle_ it with a simple ahelp we would, and it's not being straight up removed so it's not like if you don't have a legitimate cause you can't just ask your dumb boss you get you the dumb baby-jail jacket.
> 
> okay but this doesn't prevent them from making zipties or printing handcuffs from a hacked autolathe so i dont know what this is supposed to accomplish outside of making a meme job even less useful

How does them having a straight jacket make them "useful" to the station? The jacket isn't being removed. As for the zipties and handcuffs, the zipties are much quicker to escape from, and them having to hack the autolathe and print handcuffs are 1. much more noticable and 2. delay their grief so that players/admins can have more of a notice for them doing it/preparing it. If security catches them with zipties/cuffs then they're going to get them taken away. If security catches them with a straight jacket then nobody will look two ways.

**Comment by 00ze-cyclone** [comment]
> How often do you see a psych, or anyone really, use the straight jacket for anything that isn't either straight up just kidnapping people, or baby-jailing them so hard that they may as well ghost? Why did we add a bomb limit? Because griefers kept maxcapping. Why did we make it so you need CE/head permission to use the PA generator outside engineering? Because griefers kept ruining rounds upon rounds by building a singularity generator. If we could just _handle_ it with a simple ahelp we would, and it's not being straight up removed so it's not like if you don't have a legitimate cause you can't just ask your dumb boss you get you the dumb baby-jail jacket.

TTV crashed the servers, PA generators make a singulo destroying everything.
The straight jacket and muzzle can be used to incapacitate ONE person and it can be fixed in 10 seconds.
That shit can be handled with one simple ahelp, the comparison is ridiculous.

I don’t like one shitter dictating our game design because they log in to do some low effort grief.

**Comment by VaelophisNyx** [comment]
Jelly do you know how persistent this guy is?

**Comment by cowbot92** [comment]
> 

At this point im too tired from working 13hr shifts and then still having him log in to care. I'll just delete the stupid straight jackets every round and deal with it like a big boy admin

**Pull request closed without merging**
