### PR TITLE
Removes burst autorifles again

### PR DESCRIPTION
**Pull request by ghost**
Who the hell thought that was a good idea?

No.

They're staying gone. You don't need 40 damage burst weapons in cargo that outclass the stetchkin.

### CODE REVIEW

**Comment by maxion12345** [comment]
obligatory "remove not improve" reference and insult to the size of your female parental figure

**Comment by ghost** [comment]
@maxion12345

Then you should have come up with a way to improve it before you readded it.

"Improve, not remove" is not a reason to revert a removal without improving it.

**Comment by Hopekz** [comment]
I understand why these changes should take place because I had to create a whole new variant for the rifles because the original ones in my balance testing are OP.

The "Can't be shot akimbo welded" thing doesn't matter and wasn't even factored into my initial tests when I concluded it was OP (was only testing with 1 gun at a time)

**Comment by maxion12345** [comment]
> @maxion12345
> 
> Then you should have come up with a way to improve it before you readded it.
> 
> "Improve, not remove" is not a reason to revert a removal without improving it.

What I'm trying to say here is that autorifles, in my opinion, are in a decent enough spot. They are rifles, they should be lethal as all hell and able to put down a decent amount of lead at a target rather then a bullet every so often. 

If damage is an issue, lower the damage. This way you'll still have to connect both shots to maximize dps, but you won't be punished with the fire delay if you miss a bullet. Although you'll just opt to remove burst, make every weapon in cargo come with rubber bullets, and then charge cargo an absurd amount of money for them most likely so then you won't have to bother with any actual balancing

Ultimately, it'll be a question for Jamie of "Do we want to make autorifles a viable option along with shotguns in the hope the shotgun meta isn't the meta anymore?"

**Comment by ghost** [comment]
I already have a plan in mind to make shotguns not the meta.

‘they are rifles’ is not an excuse. They’re ballistics. NT is shit at ballistics.

the default WT is powerful enough regardless. I do not need to make things broken and overpowered just because ‘they’re rifles why do they not kill people instantly’ or I would make lasers hitscan.

They are not in a ‘decent enough spot’. They do 40 damage. If I reduce the damage, then they go back to being, in your opinion, worthless, because they don’t kill people instantly anymore.


40 damage is too much. We removed laser cannons from R&D for a reason. 30 damage makes them the c-20r. 20 damage keeps them where they are now. So they stick with 20 damage. 

Now stop crying and let me fix your fucking server without you constantly trying to revert every little thing I do.

**Comment by ghost** [comment]
In fact, let me go into more detail.

>They are rifles, they should be lethal as all hell and able to put down a decent amount of lead at a target rather then a bullet every so often.

This is a non sequitur statement. Just because it is a rifle does not mean it should be 'lethal as all hell.' What an item is in real life is irrelevant to game balance. It could be the size of a fucking truck and fire cannon rounds, but it won't instantly kill anyone, because that's bad for balance.

It won't be 'lethal as all hell' because nothing should be 'lethal as all hell' and anything being 'lethal as all hell' is bad for balance, which I intend to undo.

> If damage is an issue, lower the damage. 

Then that is the same thing as what i'm doing. If the WT bullets only do 10 damage apiece and it fires in bursts of 2, so it does 20 damage, then it's still just as it was before. If I make it do 15 damage apiece, then it's a 30 damage burst, and that's too strong for station crew weapons.

No ranged weapon available to the crew should be able to output more than 20 damage at a time if it has equivalent stats otherwise to the laser gun.

For example. The stetchkin does more than 20 damage, but it has a smaller ammo capacity than the laser gun. 

The particle beam gun does more than 20 damage, but requires there to be an aiming period.

The shotgun is overpowered, and thus irrelevant to the discussion.

The Mosin Nagant does a staggering 60 damage, but fires slowly, has low ammo capacity, and is due for a nerf anyway by which I intend to give it negative armor piercing value so that it is worthless against anyone in standard armor and thus significantly weaker.

Any crew weapon that does more than 20 damage in that vein is thus due for review. If it does more than 20 damage, it should have lower ammo capacity. 

The WT-550 is statistically, at the moment, equivalent to the laser gun, except it can be loaded with 4 variant ammo types. It is adaptable and reloadable on the spot. It is a good weapon. However, giving it burst made it broken and overpowered as fuck, as it instead does 40 damage, which is ridiculous. If I decrease the damage, I haven't changed that it's still better than the laser gun, which no cargo-available gun should be without sacrificing ammo capacity at minimum and likely more than that.

That is the way balance will be going.

> Although you'll just opt to remove burst, make every weapon in cargo come with rubber bullets, and then charge cargo an absurd amount of money for them most likely so then you won't have to bother with any actual balancing

Idiotic ad hominem, especially considering i'm the only person who actually understands how to balance at this point. I'll remove burst and then see where we need to go from that. Cargo money pricing is fucking irrelevant at the moment-I don't care where it currently stands, because i'm changing all of it. Bounties are going, stocks are going, budget cards are going, et cetera. 

> Ultimately, it'll be a question for Jamie of "Do we want to make autorifles a viable option along with shotguns in the hope the shotgun meta isn't the meta anymore?"

This is a bad attitude to take. We do not make things viable alternatives to strong guns by buffing them. We nerf the strong gun. 
Shotguns will be receiving some nerfs soon so that the shotgun nerf is no longer the meta. The temporary shotgun crate price increase was a bandaid fix I implemented to stem that tide while in the meantime I work on adjusting buckshot, slug, et cetera values and make them fit rather than our current basis.

Shotguns are used and abused because they are high-damage near instant-kill weapons that dominate in close quarters, and being that this is a fucking space station, EVERYTHING is a fucking close quarters combat environment. They fit any environment and half their shit is overpowered as fuck. In order for anything to 'compete' with the shotgun, it has to be overpowered as shit.

So we're not doing that. The idiotic 'we make it viable by making it overpowered' age of balancing has come and gone.

**Comment by Mqiib** [comment]
Currently, autorifles would do just fine with single rounds. Since they got a damage buff they're not COMPLETE ass and they'd arguably be more accurate without the two-round burst. You just have to actually aim and can't just meatshot people point blank as easily.

**Comment by maxion12345** [comment]
> Currently, autorifles would do just fine with single rounds. Since they got a damage buff they're not COMPLETE ass and they'd arguably be more accurate without the two-round burst. You just have to actually aim and can't just meatshot people point blank as easily.

I don't recall there being a damage buff. Adam's rifles are actually a step back due to you needing to purchase lethal ammo separately, increasing cost for a weapon that was never used when it had no associated ammo costs. Maybe with the planned shotgun changes (whenever those are finished), these tweaks may work. But in the current shotgun meta, these tweaks will just make an already not-used rifle even less used.

**Comment by ghost** [comment]
@maxion12345 You're lying through your teeth.

It's used heavily, and it's flatly better than the laser gun.

No more.

And yes, there was a damage buff. It used to be 15 damage-now it is 20. "Ammo costs" is irrelevant. Cost doesn't matter. Money is infinite. Get that through your skull.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
