### PR TITLE
Sniper rifle is now bolt-action

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

The sniper rifle is now bolt-action, instead of having 4 second delay with no indication for when it can fire again. Functions similar to a mosin but using magazines and takes longer to work the bolt.

# Spriting

Bolt open
image
Bolt closed
image

# Changelog

:cl:    
tweak: sniper rifle is now bolt-action
imageadd: adds sprites for sniper rifle bolt
/:cl:

### CODE REVIEW

**Comment by DylonBR** [comment]
don't you only have like a 10% chance to get the sniper?

**Comment by iamthesilly** [comment]
> don't you only have like a 10% chance to get the sniper?

It's in the nukie uplink too

**Comment by iamthesilly** [comment]
Alright made it just take longer to work the bolt instead of nerfing the ammo for it

**Comment by Addust** [comment]
_**ALSO**_ syndicate lavaland

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
