### PR TITLE
chisels cash slots into vending machines. PARTIAL REVERT [#2649]

### PR DESCRIPTION
**Pull request by wonderinghost**
if you can read this then i ask for help in making economy viable. help make it more lively then just another game mechanic 
# Document the changes in your pull request
readds functionality to use cash on vending machines (creds, coins, and cash)

# Why is this good for the game?
with how the economy is on yogs and with the aging codework we are built on, this is to make cash, physically important. actually, used outside of stealing to an id. allows free miners or those who lack an id/account the ability to still use the vending machine if they have cash on hand

# Testing
in the process of testing 

# Changelog

:cl:  

tweak: can now use cash on vending machines

/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
still a work in progress so this may not be out for a while

**Comment by azzzertyy** [comment]
can you revert coins on a string too i used to love doing that

**Comment by wonderinghost** [comment]
I'll see what I can do once I get it to work

**Comment by Necrosium** [comment]
> can you revert coins on a string too i used to love doing that

lmao

**Comment by ToasterBiome** [comment]
Reopen when more work is done

**Pull request closed without merging**
