### PR TITLE
Gives network admin ai upload access

### PR DESCRIPTION
**Pull request by warface1234455**
Network admin maintains AI so they should be able to access ai upload, also to turn off turrets to not getting shot at when saving AI 

# Document the changes in your pull request
Gives network admin ai upload access

# Wiki Documentation
Gives network admin ai upload access

# Changelog

:cl:  

tweak: Gives network admin ai upload access
/:cl:

### CODE REVIEW

**Comment by Noobetski** [comment]
finaly i can revive the AI without turning into char

**Comment by MajManatee** [comment]
unnecessary until the ai rework is merged.

**Comment by Simplehorror** [comment]
honestly i feel like the network admin should be allowed to fuck with the AI's laws

**Comment by ShoziOffical** [comment]
> unnecessary until the ai rework is merged.

i dont think that touches the access

**Review by MajManatee — APPROVED** [review]
i mean sure i guess
Having thought about it, it makes sense so whatever.
Will hopefully encourage more co-operation with the AI, and more expansion of it.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
sigtech traitors roundstart one-humanning the ai

**Comment by Noobetski** [comment]
> sigtech traitors roundstart one-humanning the ai

validhunter RD roundstart decapping sigtech.

**Comment by Bibby0110** [comment]
Network Admin is not supposed to have anything to do with AI laws. That is left up to the RD/Captain

**Comment by Noobetski** [comment]
that's it boys, AI rework 3.5 is not allowed because netmin can't have fun with new AI content, wrap up.

**Pull request closed without merging**
