### PR TITLE
Revert "REEEEEEEEEEEEEEEEELOADINGGGGGGGGGGGGGGGG"

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Reverts yogstation13/Yogstation#9201
it's been like several months and not even I have seen a use for this

### CODE REVIEW

**Comment by ghost** [comment]
people don't know it exists

**Comment by fluffe9911** [comment]
can confirm am maint and didnt know this existed

**Comment by Hopekz** [comment]
I like it.
There isn't a "use" for it but it was "cool" the one time I used it.

IMO it should just be forced for people with the option of changing/disabling it instead of it starting blank.
Okay feature; bad implementation.

**Comment by Marmio64** [comment]
i use it...

**Comment by yacabo** [comment]
I know of its existence but I have no idea how to use it

**Pull request closed without merging**
