### PR TITLE
Improved explosion echoes (PORT)

### PR DESCRIPTION
**Pull request by MrHorizons**
This is a port of Citadel-Station-13/Citadel-Station-13#13282, in turn a port of Skyrat-SS13/Skyrat13#3295.

From the original PR:
[Tesloose footage](https://streamable.com/yel0od)
[Remote explosion](https://streamable.com/6xap9j)

#### Changelog

:cl:  
rscadd: New explosion echoes.
tweak: Explosion echoes carry much farther now.
soundadd: Five new explosion-related effects.
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Holy shit my ears had an orgasm when the tesla went off

**Comment by jcatjmeow** [comment]
clearly untested 😓

**Comment by MrHorizons** [comment]
Fuck sound code.

**Comment by UselessTheremin** [comment]
Echoes? Yes please. Port from cit? Yes please. Sounds fun!

**Pull request closed without merging**
