### PR TITLE
Ports "Half-Ports (????) the CMO turtleneck" and "Adds New CentCom Clothing Sprites!"

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Ports some PRs from TG which add some new clothing options, adding them instead of replacing our uniforms. The two PRs ported are [Adds New CentCom Clothing Sprites! #57023](https://github.com/tgstation/tgstation/pull/57023) by [Imaginos16](https://github.com/Imaginos16) and [Half-Ports (????) the CMO turtleneck #64223](https://github.com/tgstation/tgstation/pull/64223) by [VladinXXV](https://github.com/VladinXXV). Also codersprites a new icon for the centcom armor because I was bored and replaced the captain's jumpskirt icon with one that matches the current worn icon. Also added replicas for our current centcom official uniforms and added it to the hacked closes vendor. All of the new centcom clothing is unused, but I can add them to some uniforms if wanted.

# Wiki Documentation

Icons for the changed uniforms and mentioning the replica uniforms in the clothes vender. 

# Changelog

:cl:  Imaginos16, Vladoricious, Michiyamenotehifunana
rscadd: Added the CMO turtleneck and turtleneck skirt
rscadd: NanoTrasen has now graciously created new outfits for their esteemed members of Central Command! These include new turtlenecks, a fancy coat, a new cap, and a skirt edition of the current Official jumpsuit.
imageadd: added a new icon for the unused centcom armor and captains jumpskirt icon
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
aaaaaa im gonna have to change some of these too if this gets merged

**Comment by maxion12345** [comment]
We'll need to make the current centcomm uniform unused before we go adding it to the hacked vendor, so that it'll maintain it's legitimacy

**Comment by maxion12345** [comment]
> We'll need to make the current centcomm uniform unused before we go adding it to the hacked vendor, so that it'll maintain it's legitimacy

Nevermind I see they got renamed to replicas

**Review by nesisknesis — COMMENTED** [review]
CentCom is too proud to wear a turtleneck so adding it doesnt fit. Billionaires wear turtlenecks to faux humility, CentCom don't give a shit. Also don't think the crew should get access to CentCom branded uniforms because I like the rareness of it.

The CentCom armour being a duped deathsquad/captain hardsuit is boring, keep the classic only.

The new jacket is alright though if it is unused, mark it as such in the dmi.

ill get back to you on the CMO turtleneck

**Review by nesisknesis — COMMENTED** [review]
I would like to keep the turtleneck out the game, would only associate the RD with having one. I know the CE and RD has one but i'm not that big on cookie cutter clothing for heads.

I'm also on edge about the messiness of head of staff clothing so as little contribution to that would be appreciated. I'm hoping I can do partly do something about that soon though.

**Comment by JamieD1** [comment]
Yikes

**Pull request closed without merging**
