### PR TITLE
Adds monkey gamemode: nich isnt here v2

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Reverts yogstation13/Yogstation#6879

🆑 
rscadd: Monkey gamemode is back!
/🆑

### CODE REVIEW

**Comment by yacabo** [comment]
Stealth merge

**Comment by AsV9** [comment]
thunk

**Comment by Mr-Space** [comment]
I am so proud of this community

**Comment by yacabo** [comment]
Let it be known that this PR lasted a total of nineteen minutes

**Comment by Amelia0010** [comment]
I live on, inside of AsV

**Pull request closed without merging**
