### PR TITLE
Spiderbots 1.0 - The big spiderbot update

### PR DESCRIPTION
**Pull request by Majkl-J**
# Reasoning behind PR
Current spiderbots are not exactly up to speed and as I have no clue what the original creator (SuperSlayer) intended, this is just my idea of how to get them working.

This PR hopes to reimagine spiderbots into more interesting and dynamic parts of the station and not just a purgatory for all the unlucky MMIs to be put inside one. (Or just kleptomaniac MMIs who requested it)

# Document the changes in your pull request
## Manipulator levels
Adds a 4 "levels" to the spiderbot, based off of the manipulator used during construction. These affect the amount of upgrades the spiderbot can have at once (From 1 to 4 respectively), as well as its working speed.

## Upgrades
Allows spiderbots to be upgraded with bot assemblies. To not make them samey, each will have their own twist.

### Medibot assembly
- Medical radio access
- Sutures and patches (These are slower to apply than regular ones)
- ??? (Throw ideas at me)
### Janibot assembly
- Service radio access
- Cleanmode (When activated, lowers move speed but cleans tiles directly under)
- Light replacer (10 charges which slowly refill)
- If combined with the Honkbot: The slipmop 1000. Cleans floors, but wets them in lube instead!!!
### Floorbot
These were always niche, time for some creative genius.
- Able to place and replace floors
- Get a welder to fix other probably broken stuff aswell
- Floor decal painter
### Honkbot
- Honks with each step
- Annoying
- Holografic banana (We are reaching levels of clowning never before available)
### Atmosbot
- Atmos holofan
- Can explode into smart metal foam (This destroys the spiderbot)
### Firebot
- Extinguisher (Or the firefoam extinguisher if combined with atmosbot)
- Lighter (Know your enemy)
- Makes the spiderbot fire resistant
### Any secbot
I actually don't have any not too validhunty ideas for this, so throw them at me.

## Aditional minor changes
The spiderbot's 10hp is way too fragile. Changes it to 25hp, based on the hp of the average bot. (Their speed might need a minor nerf later down the line, for balance reasons)
Adds factions to spiderbots, notably the spider faction. (It's a spider afterall)
Gives spiderbots default radios.
New spiderbot sprites

- [x] Get decent enough new sprites
- [x] Get the upgrade system baseline working
- [ ] Medibot upgrade features
- [ ] Janibot upgrade features
- [ ] Floorbot upgrade features
- [ ] Honkbot upgrade features
- [ ] Atmosbot upgrade features
- [ ] Firebot upgrade features
- [ ] Slap together some decent GUI
- [ ] Allow them to ride spiders
- [ ] Fix additional shitcode in the spiderbot code

# Spriting
New, more spidery sprites!
botto1pr

# Wiki Documentation
A lot to document, I will probably add all but the sprites myself (I am held at gunpoint by wikistaff)

## Sprites
spiderbot_0000_empty 
spiderbot_0001_brain 
spiderbot_0002_posi

# Changelog

:cl:  
rscadd: Added upgrading spiderbots with bot chassis
wip: This is work in progress  
tweak: Tweaked spiderbot HP
imageadd: Changed spiderbot icons
experimental: This is experimental
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
got em

**Comment by Maia-J** [comment]
> got em

Bold to assume it will be finished by January

**Comment by cuackles** [comment]
The sec could be related stuff but not for actually arresting people like the ability to put on search or with a warrant, print fines ??? Idk maybe tag people for a short time so that they can be tracked for a bit

**Comment by UltraBigRat** [comment]
secbot could maybe get sec radio (With the ability to call the sec codes to easily dispatch sec)  and a forensic analyzer. they would probably work better as detective like rather then secoff like, since thats far less validhunty and their manueverability helps with that. Or for funsies could give them a donut machine gun that deals no damage and just shoots donuts at people.

**Comment by Firewolf34** [comment]
> The sec could be related stuff but not for actually arresting people like the ability to put on search or with a warrant, print fines ??? Idk maybe tag people for a short time so that they can be tracked for a bit

Ooh that's a good idea. Have these guys operate the medical and sec records that always get ignored :)

**Comment by Moltijoe** [comment]
is the new positron spiderbot icon animated like positrons normally are?

**Comment by Maia-J** [comment]
> is the new positron spiderbot icon animated like positrons normally are?

Yes

**Comment by KillerOrcaCora** [comment]
Ok from author to close.

**Pull request closed without merging**
