### PR TITLE
[Box] The Big Boxstation Decal Update

### PR DESCRIPTION
**Pull request by GraveHat**
228 File Changes

# Document the changes in your pull request

#14835 Revives this pr because the entire branch got deleted. #15092 Revives the revival because of updates and 228 _Changed files_.

Copies over the decals done by the first pr removed some white corner tiles in front of the kitchen and reordered some things so they won't get recolored by the trim lines, also moved the light switch in the garden from outside the window to somewhere people can actually use it.

# Changelog

:cl: @VaelophisNyx 
tweak: replaced every quarter-tile square decal with a line decal of the same or similar color station-wide, except where used to recolor a floor tile.
tweak: replaces individual quarter tile decals being used instead of opposing
bugfix: moved the light switch in the window in the garden to somewhere accessible
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
eh at this point no credit is due to me; you've basically redone the whole map yourself

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Don't avoid machines like this:
image
image
image

Fucked tiles: 
image
Various decals stuck in walls:
image
image
image
image
image

Overlaid decals (NO):
image

Warning lines and trims don't mix:
image
image
image
image
image
image
image



Decals don't connect sometimes:
image
Can also go around here:
image
image


in airlocks like this it's better to just have the black and yellow warning lines since the colored ones poke out:
image
image

Differing airlock styles:
image

Stop the trim right before the blast doors:
image
image


Don't like the genetics color, just make it the science one:
image

Same with chemistry, refer to Gax:
image

Too much:
image

Remove the checkerboard accents if we're adding trim here:
image

Too much:
image

Color + blast doors:
image

Refer to how Gax handles these decals:
image

Refer to how Gax handles these decals:
image

Outline all of EVA with blue:
image

Medical trim in the hallway around chem:
image

Medical trim around morgue and behind cloning:
image

Science trim around all of xeno and robo:
image

Wall missing trim:
image

Dunno how I like toothpaste psych office:
image

Bridge still has remnants of stairs:
image

Continue the grey tril around the two sides:
image

**Comment by GraveHat** [comment]
> eh at this point no credit is due to me; you've basically redone the whole map yourself

Still, its a revival of a revival of your pr. Even if I'm being asked to change and cut a lot about it, it still roots back. I think the decals need to be updated and you did it first, so even if I hijack it I still have to give some credit to the foundation. That and I have no idea how referencing authors work in the changelog in-game so I'm waiting to see if this would credit both or just you.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Uneven:
image

Ends abruptly, you can loop here:
image

Extend blue down around morgue:
image

Can remove the purple warning lines here since the loader area:
image

This:
image

You got one set of blast doors but not the left one:
image

Warning line + Trim = no:
image
image
image
image
image

Trim on left side and bottom:
image

Stair remnant:
image

Can remove the two trim pieces for the yellow decals:
image

Half tiles on this top and bottom can be removed:
image

Overlap:
image

This trim:
image

**Review by ToasterBiome — APPROVED** [review]
I'm confident enough after reviewing this again that anything else wrong can be fixed in a future PR, thanks for going through multiple reviews

**Pull request merged**
