### PR TITLE
holoparasites nukeops only, price increased to 30 tc

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# General Documentation

### Intent of your Pull Request

too easy heehoo traitor murderbone weapon

### Why is this change good for the game?
stop posting about amongus
# Wiki Documentation

holoparasites uplink item restricted to ops and increased to 30 TC

# Changelog

:cl:  
tweak: no more traitor holoparasites
tweak: holoparasites cost increased to 30 TC from 15 for ops
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
i’ve wanted this for a while, objectively great pr because now one traitor can’t kill an entire unaware sec team

**Comment by Marmio64** [comment]
40 TC is a lot to be honest, holoparasites on nukies are mostly only good for the hand and teleporting you back to the ship, so it'll be a huge waste of your resources to try anything else.

**Comment by Readystorm546** [comment]
I dont like this PR because 40TC is alot for the risk you run even getting a holoparisite. You could get someone who its just shit and you just wasted 40 TC on someone who cant play. On top of that your description scream i ded so you should add the tag..

**Comment by SomeguyManperson** [comment]
> 40 TC is a lot to be honest, holoparasites on nukies are mostly only good for the hand and teleporting you back to the ship, so it'll be a huge waste of your resources to try anything else.

have you not seen the holopara meta build because it involves none of that "fancy ability" stuff they're supposed to do



> I dont like this PR because 40TC is alot for the risk you run even getting a holoparisite. You could get someone who its just shit and you just wasted 40 TC on someone who cant play. On top of that your description scream i ded so you should add the tag..

good holoparasite is worth more than a gun plus you don't play so you don't get to say what's an i ded or not

**Comment by ghost** [comment]
They're really not all that great traitor wise. We've already nerfed a few abilities in the past why remove them from traitors? If its a ranged holo it is a massive fucking target and if its a melee holo it is nearly useless. Most of the time they are a hindrance to traitors, I do not think they should be nukie only.

**Comment by boodaliboo** [comment]
stupid pr

**Pull request closed without merging**
