### PR TITLE
morrow wolf forced me to do this at gunpoint

### PR DESCRIPTION
**Pull request by Kmc2000**
### Intent of your Pull Request

Explain what the purpose of your PR is.
Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool.

Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged. This is much easier for everyone.

Edit the changelog at the bottom for changes that are noticeable by the players. Remove it if this isn't the case.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.
Include [admin] in the title if it's something admin related.
Include [s] in the title if you don't want it to be announced on discord and the server.

#### Changelog

:cl:  
tweak: Departmental protolathes are now ID locked  
/:cl:

### CODE REVIEW

**Comment by Alexandria404** [comment]
Solid PR.

**Comment by ghost** [comment]
Did you even test that this works?

**Comment by Nickvr628** [comment]
No fun allowed. Nobody in the department builds things with their protolaythe except mining, now researchers cannot build stuff for medbay, security, etc using the laythes.

**Comment by ghost** [comment]
KMC this shit doesn't even work.

**Comment by Amelia0010** [comment]
why would you close someone else's PR because it doesn't work 🤔

**Pull request closed without merging**
