### PR TITLE
Surgery tweaks 2

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request
Tweaks many things about surgery, with the main objective being to add more QoL to some surgeries, making triage outside of medbay more viable while making reviving patients with a lot of organ rot more dependent on medbay. May break the more controversial tweaks down into their own PRs if needed and Ill add on to this tomorrow. Has been tested a bit, but i probably missed a few issues.

Ports ["Experimental Cobbisection [150+ Hours and Ready]" #44821](https://github.com/tgstation/tgstation/pull/44821) by [ExcessiveUseOfCobblestone](https://github.com/ExcessiveUseOfCobblestone) and the dissection parts of ["actively made research creates a usable item instead of making them get added to techweb instantly" #47088](https://github.com/tgstation/tgstation/pull/47088) by [Tlaltecuhtli](https://github.com/Tlaltecuhtli)

Bone sounds from [freesound.org](https://freesound.org/people/carlito62/sounds/176745/)

# Spriting
image
image
image

# Wiki Documentation

Just DM me and I can break down what needs to be changed. 

# Changelog

:cl:  Nmajask, Cobby, Tlaltecuhtli
rscadd: Added surgical mats, holomats, and a goliath mat
tweak: all surgery steps now have sounds 
tweak: using surgeries downloaded on an advanced health analyzer now requires you to have the analyzer in your off hand
tweak: reworked dissection to be a tiered operation and provide notes instead of being instantly added to the research server
tweak: added a radial menu for implant manipulation and organ manipulation
tweak: reworked implant removal into implant manipulation, making it repeatable, available on simple mobs, and able to implant implants with cases
tweak: plastic surgery now allows you to type out the name
tweak: brainwashing surgery now asks you for the objective at the end of the surgery
tweak: surgery designs now use the surgery icon if available
tweak: added mechanical versions of many surgeries that were missing them
tweak: coronary bypass and lobectamy now make the organ count as operated on if the operation fails
imageadd: added more icons for surgeries and icons for the mechanical versions of surgeries 
bugfix: fixed debug surgery disks not working
soundadd: more bone crunchy sounds
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
I dont like how good the mats are considering they defeat the point of bringing anyone to medbay, Also make drapes the starting radial menu. Dont make them irrelevant.

**Comment by VaelophisNyx** [comment]
Thing is jamie, it's pretty unanimous that the drapes don't need to exist, among doctors. They are just there to slow down surgery. They don't even present a cost issue since you rarely ever need to make new drapes. Noone will miss them if they're made irrelevant

**Comment by nmajask** [comment]
> I dont like how good the mats are considering they defeat the point of bringing anyone to medbay, Also make drapes the starting radial menu. Dont make them irrelevant.

Mats are now as good as tables and holobeds are as good as regular beds, but if they are still an issue then I can just remove them. If you want drapes made useful, then there is code on a branch on the repo that reverts tools starting surgery, though im not making the PR for that.

**Comment by JamieD1** [comment]
@KillerOrcaCora @cuackles

**Review by KillerOrcaCora — APPROVED** [review]
Pinging me like some kind of dog

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
