### PR TITLE
Converts the syllables in the japanese language into actual hiragana

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

image
image

Might as well take advantage of unicode support now that we have it

#### Changelog

:cl:  
tweak: The japanese language uses hiragana symbols now
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
This is cool. When can we add an emoji language for preternis?

**Comment by Mr-Space** [comment]
weeb

**Review by JamieD1 — APPROVED** [review]

**Comment by maxion12345** [comment]
weeb

**Comment by ThatLing** [comment]
watashi me no understand

**Review by Hopekz — APPROVED** [review]

**Pull request merged**
