### PR TITLE
adds snail emoji to ooc

### PR DESCRIPTION
**Pull request by ktlwjec0**
image
image
good for the game because everyone likes snails
# Wiki Documentation

emoji cheat sheet page needs snail emoji added

:cl:  ktlwjec
rscadd: Snail emoji for OOC.
/:cl:

### CODE REVIEW

**Comment by Snellie12** [comment]
I believe this is a 100% needed thing, and I 100% Support this.

**Comment by ThatLing** [comment]
Fetish content

**Comment by Bibby0110** [comment]
Good fetish

**Comment by ThatLing** [comment]
You disgust me

**Review by cuackles — APPROVED** [review]

**Pull request merged**
