### PR TITLE
Removes the obsolete healing surgeries

### PR DESCRIPTION
**Pull request by Moltijoe**
With the existence of tend wounds, these surgeries just simply are never worth doing, and are potentially a noob trap
They take far more steps, consume resources, and are simply slower than basically any other form of healing

note, that the burn heal surgery being removed is NOT the same as the burn wound healing surgery, despite both using the word debride at some point in their code

# Why is this good for the game?
Code cleanup

:cl:  
rscdel: Removes the obsolete healing surgeries 
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
the ones that appear when you target a limb that isnt the chest?

**Comment by Moltijoe** [comment]
> the ones that appear when you target a limb that isnt the chest?

it also appears on the chest, but it always appears last

**Comment by ehj236** [comment]
Muda muda da

**Review by MajManatee — APPROVED** [review]
They fuckin sucked anyways.

**Pull request merged**
