### PR TITLE
Port Primitive Technology - Paper Filters

### PR DESCRIPTION
**Pull request by boodaliboo**
"This PR adds a simple method for filtering certain chemicals out of liquids. You can now craft a filter bowl with two wooden planks. Inserting paper into the bowl creates a blank filter - pouring a reagent container into the bowl with a blank filter installed keys the filter to whatever chemical is most present in the reagent container at the time. From that point on, while the filter is in the bowl, the bowl will only accept that reagent, leaving the others inside the original container.

Filters can be removed with alt click, allowing you to reuse the bowl for a variety of purposes. Additionally, while the bowl lacks a filter, it simply acts as a regular 50u reagent container."

#### Changelog

:cl:  
rscadd: Added a new filter system
imageadd: added some new sprites for the filters
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
one error fixed 5 more pop up lol
work on this more later but may forget

**Comment by jcatjmeow** [comment]
This code is undocumented, untested, doesn't compile, and contains references to stuff that exists in other codebases but not in yogs.

Make a draft pr next time if your pr is in this type of state. 

If you get this to a mergeable state, ping a maintainer or me and we'll reopen this.

Be sure to follow our [contributing guidelines](https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md)
Capture+_2020-08-16-08-32-15

**Comment by jcatjmeow** [comment]
Also you did not credit the original base as per our guidelines

**Comment by boodaliboo** [comment]
> Also you did not credit the original base as per our guidelines

i forgot to oh well

**Pull request closed without merging**
