### PR TITLE
Pill bottles now fit in chem bags

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Makes pill bottles fit in chem bags

# Changelog

:cl:  
tweak: tweaked chem bags to hold pill bottles
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Powercreep

**Comment by adamsong** [comment]
> Powercreep

What else makes a good PR?

**Comment by adamsong** [comment]
I'll make it count the contents of the pill bottles toward capacity, so the total storage doesn't change

**Comment by JamieD1** [comment]
Get on with it adam

**Comment by adamsong** [comment]
Stale, and making my proposed change will require changing how storage calculates weight, or make pill bottles really big

**Pull request closed without merging**
