### PR TITLE
Increase emag price

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Just noticed that the emag got its price decreased for some reason despite being the best bang for your buck item in the traitor department.

To increase variety in purchased traitor items, increasing the cost of the emag so that less people are likely to buy it would be a good solution. It also avoids having every borg get emagged every round, cargo emagged, and every station door emagged in the same round because of all the utility it has.

# Spriting

# Wiki Documentation

Emag price is now 8
# Changelog

:cl:  
tweak: Emag price is now 8
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
image

**Comment by ynot01** [comment]
Emag is a hard sell even at 6TC, 8TC wipes it off the table for anyone except for new players or players that would buy it no matter how much it costs

**Comment by Simplehorror** [comment]
> Emag is a hard sell even at 6TC, 8TC wipes it off the table for anyone except for new players or players that would buy it no matter how much it costs

yes having a borg army and all access is a hard buy for 6 TC

**Comment by Marmio64** [comment]
i do believe it was reduced to 6 TC so that it would allow more combos to be done with other items. Many traitor items are cheaper than they should be but it's done so that you're not extremely limited with your options. It is much more fun to be able to  get 3 or 4 items and work out a good combination than having to just rely entirely on 2 good items.

**Comment by Rdrazga** [comment]
> > Emag is a hard sell even at 6TC, 8TC wipes it off the table for anyone except for new players or players that would buy it no matter how much it costs
> 
> yes having a borg army and all access is a hard buy for 6 TC

As compared to having a borg army for free if you are just willing to break into sci for an upload board, or having AA for 1tc using a syndie toolbox, 6tc using fedora which doubles as a weapon, 0tc if using a RCD or jaws of life...

**Comment by Rdrazga** [comment]
> Emag is a hard sell even at 6TC, 8TC wipes it off the table for anyone except for new players or players that would buy it no matter how much it costs

To this point though, I don't agree with increasing the price, but there are a few items that can be emmaged that make it worth far more then 6tc tbf. Some examples are the cargo console for obvious reasons, the trash grinder, and defibs. But this is an issue with the things you can emag not the emag itself.

**Comment by JamieD1** [comment]
Maybe give it a small chance of breaking like 5% or something to make emagging actually risky

**Comment by Simplehorror** [comment]
i really dislike RNG in traitor items. what if you swipe it once and then your emag instantly breaks

**Comment by JamieD1** [comment]
> i really dislike RNG in traitor items. what if you swipe it once and then your emag instantly breaks

Luck of the draw innit

**Comment by JamieD1** [comment]
Closing for now, open to alternatives in future

**Pull request closed without merging**
