### PR TITLE
Readds druid as a roundstart lawset

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request

As an avid ai player, I see no reason this lawset should've been removed.
Having only really 3 lawsets as an ai player is getting incredibly boring, esspecially since we dont have malf, theres almost no variety in playing AI anymore. We need more lawsets.

# Changelog
:cl:  
tweak: Druid is back as a roundstart lawset
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
No.

**Comment by azzzertyy** [comment]
> No.

good reasoning very cool

**Comment by Runian** [comment]
Druid is alright if you're okay with:
- Stopping xenobiology from doing their job. They are literally killing organic monkeys every minute with their slime farm.
- Stopping genetics from doing their job. They will likely over radiate their humanized monkeys to the point of being damaged aka having over 100% radiation.
- Stopping the kitchen from getting non-synth meat. They have animal cubes that can be grown into an organic and those animals will die to feed the crew. If botany starts giving animal cubes to the kitchen, you're compelled to deconstruct the biogenerator (for their cube creation).
- Allowing any space vines to spread everywhere and stopping everyone from preventing it. Unlike Reporter, you cannot wall off the vines to keep them alive because that wouldn't be nurturing as they would become stagnant.
- Reviving every single organic possible; this can range between executed criminals, braindead humanized monkeys, and animals (which will be hard to do).
- Killing IPCs if they decide to harming any organic.
- Releasing prisoners of all variety, including permabrig prisoners, if they won't cause disharmony. A permabrig prisoner could be released secretly, be given plastic surgery, a new set of clothing, and a vouch from the AI that they are not the escaped prisoner.

Also, it sucks that Druid is not on Silicon Policy as it would be nice to have some guide on how to play on this lawset.

**Review by ToasterBiome — APPROVED** [review]
more upvotes than downvotes

**Pull request merged**
