### PR TITLE
[BOX] CMO Office Update

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Updates the CMO office a bit, redecorating it to look less like a cafeteria

Also adds a surgery nook for the CMO, and makes the windows properly electrified like other maps
Also made the shutters cover all directions instead of just the hallway and lobby

ss (2022-10-08 at 01 40 17)

# Changelog

:cl:  
mapping: BOX CMO office has been remodeled and now features a mini surgery room just for the CMO
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
I didn't even particularly like the one in meta :(

**Comment by VaelophisNyx** [comment]
what part specifically tho
if it's the table there's a gameplay reason for that

**Review by ToasterBiome — APPROVED** [review]
maps ok, up to jamie

**Comment by VaelophisNyx** [comment]
will fix conflict soon

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Why is there a surgery in there, like you are removing all the risks of having surgery rooms by hugboxing it.

**Comment by VaelophisNyx** [comment]
See: Metastation Medbay; it's there for Heads mostly, so the CMO can do/get surgery on them without Shitter Mcgee sprinting over to steal their bag/clothes/etc

**Comment by VaelophisNyx** [comment]
honestly its frustrating when ANY QOL improvement is labeled "hugboxxing"

**Comment by ToasterBiome** [comment]
@JamieD1

**Comment by JamieD1** [comment]
I dont like it im afraid,

**Pull request closed without merging**
