### PR TITLE
AI Rework 3.5 || Exploration and Distributed Computing

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request
All AI machines now need to wired up using ethernet cables into a network.
A data core will require a locally connected server with at least 1THz and 1TB to be functional.
A network consists of all the locally connected machines.
Two networks can be connected using a networking machine. This allows the AI and Netmin to use the resources and cores in both networks.

## Changes to the AI data core
The AI Core now looks like this with the "solar panels" (sprite pending) being networking machines. They point towards the one they're connected to if you want to snoop out where other networks might be
image

## Changes to the Netmin
The Network Admin now lives in Science in the new Computer Science room.
image
Their tool to interact with a network is now either the laptop they spawn with, or a modular computer connected with an ethernet cable.

Accessing the network using such a console allows for (at present) 3 actions. These all work based on the CPU assigned to the local network.
image

In addition to this it allows you to remotely control networking machines in the local network. 
It allows allows the distribution of networking resources to either the connected AIs, or the network itself.

This is also the way you'll be uploading and downloading AIs now.
If you're uploading you need to upload to a network that either has a data core locally, or one connected through a networking machine. Likewise for downloading.

One other minor feature added is a leaderboard program you can download. If connected to a network this will show the persistent five highest CPU and RAM records.

### Networking Machines
If the AI has an unconnected network machine you can force access to it using your own machine. To do this you rotate it using a wrench within 20 degrees of the other machine. Then you use a multitool and select the machine you want to connect to. After this is all done you use a screwdriver to finalize the connection. You can disconnect manually by using a wirecutter, or the UI.

### Misc Additions
The new local networks will change and allow a few new things.
1. No more hidden upload/download consoles. You'll need physical access to the AIs network now. (Or one it is connected to)
2. This allows ghost roles and separate AI networks. You can now build an AI as the golems/free miners/oldstation people without it automatically being teleported to the station.
3. Decoupling networks from only being for the AI also allows us to add CompSci content for the netmin. Currently this only amounts to AI revival, bitcoin mining and regular research point generation.

### New project - Room Lockdown
Allows the AI, after a delay of 2 seconds, to close all working airlocks in a room and bolt them for 20 seconds. Also triggers the firealarm. Doesn't work in maint and announces itself at the start of the 2 second delay.

### AI Revival
No longer is the AI permanently dead when its last core is destroyed. Instead it spawns a black box at the last core it was in.
This core is active for 5 minutes. After these 5 minutes the AI is permanently dead.
You can revive the AI by inserting it into a working AI data core. (This also stops the 5 minute timer)
After its been inserted the local network the core is connected to must be set to AI Revival and the AI will then be revived after enough CPU cycles have been spent.

### Network Admin Exploration
The Network Admin can now use the VR sleeper in their room to access exploration missions. These missions contain unique components and unique research.
Currently just a mockup, made a quick mission that contains 1 unique item. Just a walking simulator at present:
image
When you find the unique item you can put it in the microwave in your VR spawn and it will be transported to the station.
Future plans are to allow an AI to join you on the missions, plus allow you to buy equipment and unlock new missions using CPU on the station.

### Super Misc.
Added an easy way to use the TGUI login screen seen in the Security Console.
Use tgui_login_data in ui_data and tgui_login_act in ui_act. Use LoginScreen.js in the UI. See how the security console does it. (Only requires a var to keep track of being logged in/out)

Netmin retains access to Comms and the Tcomms satellite. NTSL equipment has been moved to the satellite and the old Hardware Workshop has been replaced by a small lounge
image

## TODO
- [ ] Allow the AI a choice of which network to transfer to when a networking machine is destroyed.
- [ ] More exploration missions
- [ ] Allow AI to join exploration
- [ ] Do all the other exploration (USB lock-doors, upgrades from CPU)
- [ ] Other maps
- [ ] Restore map config

# Changelog

:cl:  
rscadd: AIs are now housed in physical networks connected by ethernet cables. Networks can be remotely connected using networking machines. AIs can only switch between cores in networks they're connected to.
rscadd: AI upload and download is now done by hooking up a laptop or modular computer to an ethernet cable and using the AI Network Interface program
rscadd: It is now possible to revive an AI by inserting the dropped black box into a functioning data core and allocating CPU using the AI Network Interface program
rscadd: Added a new program, Room Lockdown, for the AI. Allows the AI to click an area and lock all working airlocks after a 2 second delay. An announcement is made beforehand.
rscadd: The Network Admin now has a VR sleeper and can go on short self-contained exploration missions to get unique components
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
There is a god

**Comment by Moltijoe** [comment]
VR missions? Consider my interest piqued

**Comment by cuackles** [comment]
can we get a screenshot of all the new tiles too please ?

**Comment by Bibby0110** [comment]
> can we get a screenshot of all the new tiles too please ?

new tiles?

image

**Comment by ShoziOffical** [comment]
hot hot hot

**Comment by ShoziOffical** [comment]
speed test merge

**Comment by MajManatee** [comment]
gonna have to become a sigtech main if this "Army of Two" shit gets added. Bad ass.

**Comment by ShoziOffical** [comment]
i love that sigtech gotta go all the way from tcomms to ai sat just to monitor ai now

**Comment by Moltijoe** [comment]
Any chance sigtech could get atmos alarm access? They need it to set up additional AI cores

Also, any chance another transfer tube to ai sat could be added? Either that or an eva suit

**Comment by ShoziOffical** [comment]
> Any chance sigtech could get atmos alarm access? They need it to set up additional AI cores

When you make a new airalarm it doesn't require access

> Also, any chance another transfer tube to ai sat could be added? Either that or an eva 

Why do we need a new one, there's already a tube to ai sat from engi

**Comment by Moltijoe** [comment]
> When you make a new airalarm it doesn't require access

This is for air alarms in existing rooms, tried to turn the empty room above engi storage into an extra core but had no access to the alarm. AI won't necessarily be alive to do it for you either.

> Why do we need a new one, there's already a tube to ai sat from engi

it's a hell of a long treck from rnd, and there's no shortcut through maints (not that they have maint access anyways)
a teleporter linked directly to ai sat would also work

**Pull request closed without merging**
