### PR TITLE
Adds Lavaland Ruin Behind Legion

### PR DESCRIPTION
**Pull request by alao3alao3**
# General Documentation

### Intent of your Pull Request

Creates a Dragons Lair lavaland ruin behind the Legion and is lodged in the wall itself. With the contribution from Chester the door should be locked to only open once the Legion is defeated.
dpng

### Why is this change good for the game?

Adds something behind the legion so that it isn't "wasted space." This also apparently makes the legion worth fighting.

# Wiki Documentation

Ruin should be added to the list of ruins on the wiki, along with the loot inside of it (large pile of gold, mithril, stack of diamonds, immortality talisman).

# Changelog

:cl:  
rscadd: Adds static Dragons Lair ruin within the Legion's wall that will only open upon Legion's death
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
Legion is already kinda worth it. The champions hardsuit is pretty nice. What kind of ash drake ai is it? Vasgrul or normal?

**Comment by alao3alao3** [comment]
Should just be a regular ash drake ai.

**Comment by N3D6** [comment]
Eh? I'd like this as long as the drake didn't aggro and bumrush you while fighting Legion. A guranteed ash drake would make a good addition

**Comment by ChesterTheCheesy** [comment]
Ash drake immediately crushes all the wooden tables around it...

**Review by patpol4 — CHANGES_REQUESTED** [review]
I like the idea of it but it still needs some tweaks.
First make sure to make this a new unique area and set it to hidden = TRUE and noteleport = TRUE, that will at least lessen the cheesability of it a bit.
Remove the duplicate dust
vivaldi_L4glM2TWm1
Also maybe try adding some cobwebs for looks.
Last part is light, the torches and lanterns won't be on by default and it's going to be really dark, if you want some cool thematic lighting try using /obj/effect/light_emitter/tendril in some corners.

Also a note for whoever decides on the balance part of this, the ashdrake loot stash contains(sheets):
457 gold
50 mythril
100 diamond
That is a lot but considering what you have to go through to get it, it might be justified.

**Comment by LazennG** [comment]
legion is fucking garbage so this is neat

**Comment by alao3alao3** [comment]
ashdrake itself is a loot too dont forget that

**Comment by boodaliboo** [comment]
eh i love the idea of the ruin but i personally think something other then the ash drake would be cool there. even just a retextured ash drake that looks like it was taken over by legion or something

**Review by patpol4 — APPROVED** [review]
Your newest changes were reverting the gulag fire extinguisher so I fixed that, also added two more lights 
image

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Remove 33-50% of the loot

**Comment by alao3alao3** [comment]
gold should now total to 282

**Review by patpol4 — CHANGES_REQUESTED** [review]
Oh god please don't do this, 
image
Use .../mineral/gold and set the amount on that,
Or just reduce the amount of objects.

**Review by patpol4 — APPROVED** [review]
The change was implemented

**Pull request merged**
