### PR TITLE
Hides Asay and Dsay for non-admins

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# Document the changes in your pull request

People who are not admins should not be able to see it now

# Why is this good for the game?
Moves it so non-admins don't have to see it

# Testing
Works as intended

# Wiki Documentation

No

# Changelog

:cl:  
bugfix: ASay and DSay are now no longer visible to non-admins
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
What nothing about this should work. Did you replicate it, test it, and made sure it went away. or are you chasing a ghost

**Comment by bruhlookatthisdood** [comment]
> What nothing about this should work. Did you replicate it, test it, and made sure it went away. or are you chasing a ghost

yeah, i thought that too. but before, i would see it as nonadmin and admin, then after i would see it only as admin. still worked as intended function.

**Comment by redmoogle** [comment]
> > What nothing about this should work. Did you replicate it, test it, and made sure it went away. or are you chasing a ghost
> 
> yeah, i thought that too. but before, i would see it as nonadmin and admin, then after i would see it only as admin. still worked as intended function.

Sounds like a byond bug maybe.

**Comment by bruhlookatthisdood** [comment]
> > > What nothing about this should work. Did you replicate it, test it, and made sure it went away. or are you chasing a ghost
> > 
> > 
> > yeah, i thought that too. but before, i would see it as nonadmin and admin, then after i would see it only as admin. still worked as intended function.
> 
> Sounds like a byond bug maybe.

maybe
and this fixes it

**Comment by JamieD1** [comment]
Need to verify if this is an issue before we merge random shit

**Comment by bruhlookatthisdood** [comment]
> Need to verify if this is an issue before we merge random shit

i belive this is all you need to see

image

**Comment by MajManatee** [comment]
> > Need to verify if this is an issue before we merge random shit
> 
> i belive this is all you need to see
> 
> image

well im convinced

**Comment by JamieD1** [comment]
> > Need to verify if this is an issue before we merge random shit
> 
> i belive this is all you need to see
> 
> image

Looks good to me.

**Pull request merged**
