### PR TITLE
People without science access can no longer use R&D consoles to research [#2 electric boogaloo]

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

It’s powergaming

Note: doesn’t prevent anyone in the current science department from researching.

# Wiki Documentation

Self evident

# Changelog

:cl:  
tweak: Researching is now locked behind science access
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
Does this allow Free Miners and Golems to research things?

**Comment by Bibby0110** [comment]
> Does this allow Free Miners and Golems to research things?

The powergaming rule applies to them too.
They shouldn't be researching

**Comment by SomeguyManperson** [comment]
meme pr

**Comment by Bibby0110** [comment]
Not a meme PR, not sure what Theos is on about

**Comment by SomeguyManperson** [comment]
regardless this is stupid and bad for a myriad of reasons including the part where what counts as powergaming is extremely situational

**Pull request closed without merging**
