### PR TITLE
Adds a new brain damage line.

### PR DESCRIPTION
**Pull request by Hopekz**
Adds Rotciv's "**THESE NOOBS ARE RUINING MY FAVOURITE FUCKING SERVER.**" to our brain damage lines.

### CODE REVIEW

**Comment by alexkar598** [comment]
i personally dont know how i feel about insulting players with our code

**Comment by Hopekz** [comment]
> i personally dont know how i feel about insulting players with our code

If you look through our current brain damage lines we already have lines that insult certain types of players and even our council so it wouldn't be "out of place".

As far as if we should remove all that I am neutral. If players feel victimized by what is already in the game we can work to remove it.

Also, keep in mind that putting this line in "brain damage" is pointing out the irony of the statement. It should not be taken literally by any means just like most of the brain damage lines.

**Comment by boodaliboo** [comment]
caN YOU MAKE FUN OF ME NEXT

**Comment by fluffe9911** [comment]
merge conflict

**Pull request merged**
