### PR TITLE
Reformats robotics on box so that it is easier to access.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Reformats robotics to move surgery away from its entrance so that when the assistant inevitably breaks in, they dont infect whoevers getting augments with their greytide virus.

# Wiki Documentation
Will need to have the image of robotics changed.

image

# Changelog
:cl:  
mapping: Swapped position of box surgery & robotics lobby so that it is easier to access and cleaner.
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
oh sweet glass doors. can finally drop ipc off at the back door

**Comment by hedgehog1029** [comment]
imo there should still be a door from lobby to surgery, so we can let the people who want to get augmented in directly. i like the extra door from lobby though

**Comment by wonderinghost** [comment]
i dont like the shutters to public. kinda a fuck you to dead ipc

**Comment by azzzertyy** [comment]
> i dont like the shutters to public. kinda a fuck you to dead ipc

Unsure what you mean, shutters are generally the same as it already is on box.
Box already has shutters that block visibility into surgery from the lobby, and also block access to the lobby.

> imo there should still be a door from lobby to surgery, so we can let the people who want to get augmented in directly. i like the extra door from lobby though

I will consider this.

**Comment by wonderinghost** [comment]
They do however robotics now have to take care of IPC as they can't be revived via defib and need a board they print (likely not researched). And a fair chunk of the time is people breaking in to fix ipc because either shutters are closed or robotics is ssd,dead, or missing

**Comment by ynot01** [comment]
bit of an awkward blind spot imo, not sure about alternatives

**Comment by azzzertyy** [comment]
> 
> 
> bit of an awkward blind spot imo, not sure about alternatives

Thought about this, situations like this however were why the bells were added, so I'm not sure if its too much of an issue anymore.

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
image
the surgery shutters wont close to the button in surgery, the buttons got the wrong ID, you can change the variables of it pretty easily

image
Theres an overlapping pipe under the lobby door

image

Theres an overlapping shutter here

but other then that, i think its a pretty neat looking lab and personally i like it

**Comment by azzzertyy** [comment]
> image the surgery shutters wont close to the button in surgery, the buttons got the wrong ID, you can change the variables of it pretty easily
> 
> image Theres an overlapping pipe under the lobby door
> 
> image
> 
> Theres an overlapping shutter here
> 
> but other then that, i think its a pretty neat looking lab and personally i like it

Fixed pipe, but I can't see any additional shutters?
image

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
the extra shutters were totally not me accidentally clicking once :)                                  (it was...)
but the button in surgery is still unlinked to the surgery shutters
image

**Comment by azzzertyy** [comment]
> the extra shutters were totally not me accidentally clicking once :) (it was...) but the button in surgery is still unlinked to the surgery shutters image

Fixed

**Pull request closed without merging**
