### PR TITLE
Decrease R&D single-server income by 15%

### PR DESCRIPTION
**Pull request by AsV9**
Partial revert of tgstation/tgstation#33857

Research has more ways of generating points now, and the passive cookie clicker gain should reflect that.

:cl:  
tweak: Decrease R&D single-server income by 15% 
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
ok so the other ways of  getting points which is expermental dissection which needs points in the first place or toxins and people only do toxins for bombs or dont do it at all

**Comment by alexkar598** [comment]
I don't like this PR for these reasons:

1) It doesn't fix the problem of RnD being noninteractive and just makes it take more time before the grey button becomes blue
2) It doesn't fix the problem of RnD(and roboticts depending on mining) being powerful after 30 minutes by doing nothing at all,this just makes it take 35 minutes instead

**Comment by Oakboscage** [comment]
> I don't like this PR for these reasons:
> 
> 1. It doesn't fix the problem of RnD being noninteractive and just makes it take more time before the grey button becomes blue
> 2. It doesn't fix the problem of RnD(and roboticts depending on mining) being powerful after 30 minutes by doing nothing at all,this just makes it take 35 minutes instead

Better than nothing innit

**Comment by Alexandria404** [comment]
> 
> 
> > I don't like this PR for these reasons:
> > 
> > 1. It doesn't fix the problem of RnD being noninteractive and just makes it take more time before the grey button becomes blue
> > 2. It doesn't fix the problem of RnD(and roboticts depending on mining) being powerful after 30 minutes by doing nothing at all,this just makes it take 35 minutes instead
> 
> Better than nothing innit

**Comment by alexkar598** [comment]
Tbh it's not better than nothing,it's just makes science more frustrating without actually fixing or starting to fix any of the underlying issues

**Comment by ynot01** [comment]
lets lock point generation behind a node and force you to beg engineering or toxins to make points for you :))

**Comment by alexkar598** [comment]
This doesn't fix or improve any of the core issues in research as it is currently implemented and the time difference between old and new RnD will barely be noticeable as advanced mining and T4 will still Be rushed although maybe a 5 minutes later and by the time mining gets enough mats to make mechs science will have plenty of points to research mechs and xeno will have their console research alongside the T4 anyways so all the three biggest points of impact to the round science can have will not be impacted on by this PR.

**Pull request closed without merging**
