### PR TITLE
Moves 2 cameras by 2 tiles to delete 2 blindspots

### PR DESCRIPTION
**Pull request by alexkar598**
# Wiki Documentation

Update the science hallway and the starboard hallway images

# Changelog

:cl:  
mapping: Fixes 2 blindspots in public hallways on box
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
incorrect changelog

**Review by ToasterBiome — APPROVED** [review]
Not a bugfix

**Comment by Marmio64** [comment]
feel like some blindspots can be cool ways to hide from people on the cams and the AI. Not sure specifically how useful this blindspot area would be for that purpose but nonetheless i think some blindspots are nice game design.

**Comment by alexkar598** [comment]
Maybe, but not in public hallways, thats just the map being unpolished

**Pull request merged**
