### PR TITLE
buffs clock cult to be infinitely stronger due to a <50% winrate by adding removing player agency and adding a sentinel's compromise quick action button

### PR DESCRIPTION
**Pull request by SomeguyManperson**
#### Changelog

:cl:  
rscadd: Sentinel's compromise on quick action button list for clockwork slab
tweak: sentinel's compromise fixes robotic limb damage too
/:cl:

### CODE REVIEW

**Review by Hopekz — APPROVED** [review]

**Comment by Hopekz** [comment]
**simple TL;DR for people because of the title:**
- Sentinels compromise (the healing spell) is now on the quickbar by default meaning it doesn't need to be added in the slab menu.
- Preterits are healed by this spell

**Comment by Takahiru** [comment]
but literally every gamemode has a 50% or lower winrate, clock cult winning more than blood.
Something alexkar posted
image

**Comment by MegaEmpirical** [comment]
47% is pretty damn good.

**Comment by athena413** [comment]
wack

**Comment by ghost** [comment]
less than 50% is a good balance

**Comment by alexkar598** [comment]
Im going to merge this simply to prove that once its mainstream, sentinel compromise is completly OP

**Pull request merged**
