### PR TITLE
Debones your plantpeople

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Plants do not have bones and plants do not self-repair broken bone wounds because they should not have bones
# Spriting

# Wiki Documentation

maybe lore or something

# Changelog

:cl:  
tweak: Plant people no longer have bones
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
how they gonna walk then lmao

**Comment by Simplehorror** [comment]
this just affects wounds and maybe surgery in the future

**Comment by ShoziOffical** [comment]
cool plant buff

**Comment by CMOisLing** [comment]
They have wood for bones but ya good change

**Comment by Simplehorror** [comment]
why arent the checks running

**Comment by Hopekz** [comment]
> how they gonna walk then lmao

This PR is where you try to bring reality into the game? How do plant people even exist in the first place under reality? We have people that are eggs where were you during that PR

**Comment by Simplehorror** [comment]
he thought bones were needed for walking in the game

**Comment by Moltijoe** [comment]
can i get the uuuuuhh **_BONELESS_** plant people?

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
