### PR TITLE
fixes buster arm abilities being usable while incapacitated

### PR DESCRIPTION
**Pull request by LazennG**
# Document the changes in your pull request

fixes buster arms working when they shouldn't

# Changelog

:cl:  @LazennG @Chubbygummibear 

bugfix: fixed buster arm working when the user was incapacitated 

/:cl:
thanks chubby for figuring out why the callbacks weren't working and how to fix it

### CODE REVIEW

**Comment by ynot01** [comment]
that is not how you use the check_flags

**Comment by ynot01** [comment]
keep the check_flags, make `/datum/action/cooldown/IsAvailable()` call its parent like it should, not this snowflake code

**Comment by Chubbygummibear** [comment]
> keep the check_flags, make `/datum/action/cooldown/IsAvailable()` call its parent like it should, not this snowflake code

i feel like maybe this should be a different PR specifically titled to reflect changing the action/cooldown code rather than change a core proc under a pr for an item fix

**Comment by ynot01** [comment]
> > keep the check_flags, make `/datum/action/cooldown/IsAvailable()` call its parent like it should, not this snowflake code
> 
> i feel like maybe this should be a different PR specifically titled to reflect changing the action/cooldown code rather than change a core proc under a pr for an item fix

This fixes the issue and affects no other items that use this datum. Applying snowflake code because of a broken datum instead of just fixing the datum is the wrong way to go about it.

If you are fixing something, fix the root of it, do not apply bandaid and say fuck it and make someone clean it up later.

**Comment by Chubbygummibear** [comment]
> > > keep the check_flags, make `/datum/action/cooldown/IsAvailable()` call its parent like it should, not this snowflake code
> > 
> > 
> > i feel like maybe this should be a different PR specifically titled to reflect changing the action/cooldown code rather than change a core proc under a pr for an item fix
> 
> This fixes the issue and affects no other items that use this datum. Applying snowflake code because of a broken datum instead of just fixing the datum is the wrong way to go about it.
> 
> If you are fixing something, fix the root of it, do not apply bandaid and say fuck it and make someone clean it up later.

i'm agreeing that what you're saying about fixing the cooldown subtype is the way to go for this, but i just feel like having it under a pr made for an item fix makes it hard to understand that's what's getting changed y'know? i just mean to make a new pr like "cooldown actions isavailable now calls parent proc", not "fixes buster arm issue" by changing a core datum proc that's seemingly unrelated by nature

**Comment by ynot01** [comment]
> i'm agreeing that what you're saying about fixing the cooldown subtype is the way to go for this, but i just feel like having it under a pr made for an item fix makes it hard to understand that's what's getting changed y'know? i just mean to make a new pr like "cooldown actions isavailable now calls parent proc", not "fixes buster arm issue" by changing a core datum proc that's seemingly unrelated by nature

Users do not need to understand what is being changed internally

The changelog is purely for user-facing changes

The changelog can remain the same as this does not affect the other two things that use /datum/action/cooldown

**Review by Moltijoe — CHANGES_REQUESTED** [review]
> keep the check_flags, make `/datum/action/cooldown/IsAvailable()` call its parent like it should, not this snowflake code

do this

**Comment by LazennG** [comment]
closing for #17889

**Pull request closed without merging**
