### PR TITLE
Ports 514 compat from beestation

### PR DESCRIPTION
**Pull request by alexkar598**
for test merge

also yoinks funny airlock fix

yoink

### CODE REVIEW

**Comment by boodaliboo** [comment]
ChAnGeLog

**Comment by Cartlord** [comment]
What... is this?

**Comment by Bibby0110** [comment]
update readme too

is bee a 1:1 fork of monstermos or do we have weird changes they don't and vice-versa?

**Comment by Hopekz** [comment]
> ChAnGeLog



> What... is this?

image

Why are you guys leaving feedback and providing input to something you don't understand

**Comment by alexkar598** [comment]
> update readme too
> 
> is bee a 1:1 fork of monstermos or do we have weird changes they don't and vice-versa?

I believe it's not 1:1 but the modules are the same. We havent experienced any crashes so far I believe

**Comment by Bibby0110** [comment]
> > update readme too
> > is bee a 1:1 fork of monstermos or do we have weird changes they don't and vice-versa?
> 
> I believe it's not 1:1 but the modules are the same. We havent experienced any crashes so far I believe

get one of the autis... i mean valuable atmos mentors to make sure nothing is weird with monstermos maybe? probably doesn't matter

**Comment by TheLinuxOS** [comment]
> > ChAnGeLog
> 
> > What... is this?
> 
> image
> 
> Why are you guys leaving feedback and providing input to something you don't understand

Because they are idiots

**Comment by boodaliboo** [comment]
> > > ChAnGeLog
> > 
> > 
> > > What... is this?
> > 
> > 
> > image
> > Why are you guys leaving feedback and providing input to something you don't understand
> 
> Because they are idiots

because downvotes mean nothing on a pr of this nature

**Comment by alexkar598** [comment]
Y'all lacking braincells

**Review by nesisknesis — APPROVED** [review]

**Comment by alexkar598** [comment]
HIPPITY HOPPITY
SELF MERGE

**Pull request merged**
