### PR TITLE
A vain attempt to make the minigun more viable

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
big funny gun go brrrt
Hopefully this makes it more viable. Or viable at all, actually.

Increases heat limit from 30 to 50
Reduces slowdown slightly by 0.1 (because this was reduced in the other L6 PR recently)
Increases bullet damage by 2 (Now one more than basic L6 Ammo, 34 to 36)
Reduces its cost by 6TC (36 to 30)

Will this be enough? Idk, I'm open to suggestions. 

# Wiki Documentation

TC Price reduction - 36 to 30
Dmg increase - 34 to 36
Slowdown reduction (1.5 to 1.4)
Heat limit increased (30 to 50)

# Changelog

:cl:  
tweak: Minigun TC Price reduction - 36 to 30
tweak: Minigun Dmg increase - 34 to 36
tweak: Minigun Slowdown reduction (1.5 to 1.4)
tweak: Minigun Heat limit increased (30 to 50)
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
The issue that the Osprey in the singular time I used it is that you're unironically going to need to be the Heavy and Medic from TF2 to make it viable. 
Buffing the damage and reducing the head is great but you still lose your backpack slot, and you still are slow as fuck. Whatever hardsuit you're have is subject to getting their ass stomped in by a chemist or some methed up guy wearing bullet proof armor with a riot shotgun. I'd honestly rather the L6 be given an extended drummag or back pack magazine because the L6 does everything the Osprey does, but better in EVERY area.

**Comment by Burger1998** [comment]
> The issue that the Osprey in the singular time I used it is that you're unironically going to need to be the Heavy and Medic from TF2 to make it viable. Buffing the damage and reducing the head is great but you still lose your backpack slot, and you still are slow as fuck. Whatever hardsuit you're have is subject to getting their ass stomped in by a chemist or some methed up guy wearing bullet proof armor with a riot shotgun. I'd honestly rather the L6 be given an extended drummag or back pack magazine because the L6 does everything the Osprey does, but better in EVERY area.

dont nukies actually have a medbeam with ÜberCharge in the uplink?

**Comment by RG4ORDR** [comment]
> > The issue that the Osprey in the singular time I used it is that you're unironically going to need to be the Heavy and Medic from TF2 to make it viable. Buffing the damage and reducing the head is great but you still lose your backpack slot, and you still are slow as fuck. Whatever hardsuit you're have is subject to getting their ass stomped in by a chemist or some methed up guy wearing bullet proof armor with a riot shotgun. I'd honestly rather the L6 be given an extended drummag or back pack magazine because the L6 does everything the Osprey does, but better in EVERY area.
> 
> dont nukies actually have a medbeam with ÜberCharge in the uplink?

I think so, but unless everyoine is gonna stay together(literally impossible)

**Comment by MajManatee** [comment]
> The issue that the Osprey in the singular time I used it is that you're unironically going to need to be the Heavy and Medic from TF2 to make it viable. Buffing the damage and reducing the head is great but you still lose your backpack slot, and you still are slow as fuck. Whatever hardsuit you're have is subject to getting their ass stomped in by a chemist or some methed up guy wearing bullet proof armor with a riot shotgun. I'd honestly rather the L6 be given an extended drummag or back pack magazine because the L6 does everything the Osprey does, but better in EVERY area.

id rather kill myself, than buff the L6

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
