### PR TITLE
An NT Union Buster Squad is sent in when revs convert 80% of the station or kill all the heads

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

no unions allowed

# Spriting
If you are adding new sprites to the game please add a picture of the sprite in its relative context, ie. Clothing on a mob.

# Wiki Documentation

# Changelog

:cl:  
rscadd: NT hates unions
/:cl:

### CODE REVIEW

**Comment by Altoids1** [comment]
e

**Comment by Altoids1** [comment]
Honestly in general, it might be cool to have several of the conversion gamemodes mechanically spawn ERT or an ERT-like force in some circumstances, to reduce the amount of time spent where the victor is clearly going to be the antagonists.

**Comment by Bibby0110** [comment]
> e

i love e

**Comment by Bibby0110** [comment]
> Honestly in general, it might be cool to have several of the conversion gamemodes mechanically spawn ERT or an ERT-like force in some circumstances, to reduce the amount of time spent where the victor is clearly going to be the antagonists.

iirc we've had this discussion before

**Comment by tattax** [comment]
is this gonna be after or before roundend

**Pull request closed without merging**
