### PR TITLE
Adds a Gym in Perma

### PR DESCRIPTION
**Pull request by Hopekz**
gDOzFinWEw
zepcIsCHyQ

:cl:  Hopek
rscadd: Perma now has a gym
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
doesn't the holodeck have a gym

**Comment by Hopekz** [comment]
> doesn't the holodeck have a gym

Digital VR weights are weightless how do you expect someone to work out with virtual weights

**Comment by KillerOrcaCora** [comment]
It's about **drive** 😤
It's about **_power_** 🤯
We stay **hungry** 😩
**We devour** 👹
Put in the _work_ 👨‍💼
Put in the _hours_ 🕜
**And take what's our**!!! ✊🏻

**Review by patpol4 — APPROVED** [review]

**Comment by bruhlookatthisdood** [comment]
> > doesn't the holodeck have a gym
> 
> Digital VR weights are weightless how do you expect someone to work out with virtual weights

Give them beatsaber

**Comment by JamieD1** [comment]
cornflakes

**Comment by Hopekz** [comment]
> cornflakes

It's waiting on the map name revert

**Comment by Hopekz** [comment]
Update:
Still waiting on #13268

**Comment by patpol4** [comment]
The rename revert was merged, rerunning checks to make sure this works

**Review by patpol4 — APPROVED** [review]
Somehow it didn't break. You can work out now

**Comment by Hopekz** [comment]
> Somehow it didn't break. 

Well yeah that's why we patiently waited for the box name revert
(Unless you mean you merged other map PR's first then I got lucky)

**Pull request merged**
