### PR TITLE
[ADMIN] Post-round lobby music will no longer interrupt admin music

### PR DESCRIPTION
**Pull request by ynot01**
Sets a timer forward of the expected duration of the song and if the round ends before it's expected to be over then it won't play lobby music

### CODE REVIEW

**Comment by Simplehorror** [comment]
what if i have admin midis disabled and round end theme enabled. so now i don't get to hear the round end theme because admins thought it'd be funny to play 1 hour of michael jackson noises

**Comment by Moltijoe** [comment]
> what if i have admin midis disabled and round end theme enabled. so now i don't get to hear the round end theme because admins thought it'd be funny to play 1 hour of michael jackson noises

get fucked then i guess

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
make it so that if you have admin midis disabled the roundend music will still play

**Comment by ynot01** [comment]
done

**Review by Moltijoe — APPROVED** [review]
[goodbye ](https://www.youtube.com/watch?v=omgSWqwVTjY)

**Review by ToasterBiome — APPROVED** [review]

**Review by Bibby0110 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
I hate admins and their stupid new music.

**Pull request merged**
