### PR TITLE
 Add a new advanced decontamination storage and suit storage snit QoL tweaks [REVIVE] 

### PR DESCRIPTION
**Pull request by warface1234455**
- Revive https://github.com/yogstation13/Yogstation/pull/16112
# Document the changes in your pull request

- **When emagged decontamination storage, it will be very devastating to mob**
<details><summary>hacked spoiler</summary>

- Extend the cycle time (3->7)
- Give mob a lot of burn damages (20, 36)
- Increase 500 rads per cycle (3500 rads total)
- Burn mob
- emits radiation
- Makes mob scream
- When done cycling, delete everything inside except for mob and spread bad smoke

</details>

- An upgraded version of the normal suit storage unit (Same code as suit storage unit but tweaked a bit and smartfridge combination). This storage can contain upto 1000 items
- Normal suit storage can no longer clear mob radiation (not contamination) due to the lack of tech, now the advanced decontamination storage will do the job.
- Add sound for suit storage unit

1. Close sound

https://user-images.githubusercontent.com/89688125/200490372-8f51fb54-df5d-4994-bfc7-3857076effcf.mp4

2. Open sound

https://user-images.githubusercontent.com/89688125/200490378-6e808a54-72dd-4919-9781-95e0c775106a.mp4

- Suit storage can now be buit
 
- Fixes being able to open suit storage unit with alt click while panel is open
 
- Fixes being able to open suit storage unit with alt click while machine is running
 
# Spriting
Sprite ported from tg
decon

# Wiki Documentation
- An upgraded version of the normal suit storage unit (Same code as suit storage unit but tweaked a bit and smartfridge combination). This storage can contain upto 1000 items
- Normal suit storage can no longer clear mob radiation (not contamination) due to the lack of tech, now the advanced suit storage will do the job.
- Add sound for suit storage unit
- Suit storage can now be buit
- Fixes being able to open suit storage unit with alt click while panel is open
- Fixes being able to open suit storage unit with alt click while machine is running
- **When hacked decontamination storage, it will be very devastating to mob**
<details><summary>emagged spoiler(Sprite is not updated)</summary>

- Extend the cycle time (3->7)
- Give mob a lot of burn damages (30, 46)
- Increase 500 rads per cycle (3500 rads total)
- emits radiation
- Burn mob
- shock mob
- Makes mob scream
- When done cycling, delete everything inside except for mob

</details>

# Changelog

:cl: Warface1234455
rscadd: add an upgraded version of the normal suit storage unit (Same code as suit storage unit but tweaked a bit and smartfridge combination). This storage can contain upto 1000 items
tweak: Normal suit storage can no longer clear mob radiation (not contamination) due to the lack of tech, now the advanced suit storage will do the job.
soundadd: Add sound for suit storage unit
rscadd: Suit storage can now be buit
bugfix: Fixed being able to open machine with alt click while panel is open for suit storage unit
bugfix: Fixed being able to open suit storage unit with alt click while machine is running
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
i will upload a template sprite in the PR soon, kinda lazy. you can look in icondiff tho

**Comment by JamieD1** [comment]
this is going to look funny when they get moved and people see the hole in the ground

wait..

**Comment by ShoziOffical** [comment]
> this is going to look funny when they get moved and people see the hole in the ground

funny shit

**Review by JamieD1 — APPROVED** [review]

**Comment by ShoziOffical** [comment]
will repaint the sprite to look more industrial engineering

**Pull request merged**
