### PR TITLE
Implant slot shuffle

### PR DESCRIPTION
**Pull request by Moltijoe**
Renames some organ defines and shifts them around for readability
Merges the two different brain implant organ slots into one

Adds some amount of decision for which implants you want inside you rather than just including everything possible

I also considered combining reviver implant and nutriment pump implant slots, but decided against it.

:cl:  
tweak: Can no longer use both CNS rebooter and Antidrop implants at the same time
tweak: IPC powercord implant no longer takes up the arm implant slot
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
but why though

**Comment by Moltijoe** [comment]
> but why though

in preparation for potential future plans

**Comment by MajManatee** [comment]
IPC buff, everyone else nerf.

**Comment by Moltijoe** [comment]
> IPC buff, everyone else nerf.

Correct

**Review by MajManatee — APPROVED** [review]
All my homies hate IPCs

**Pull request merged**
