### PR TITLE
adds "Traitor's Motif" to the lobby music

### PR DESCRIPTION
**Pull request by JayBaez**
**Intent of your Pull Request**

Add a sound that I find is suitable for SS13

**Why is this change good for the game?**

traitor man music good (first PR for yog don't murder me)

🆑
rscadd: Traitor's Motif as lobby music
/🆑

### CODE REVIEW

**Review by monster860 — CHANGES_REQUESTED** [review]
The format is artist then song title

**Comment by JayBaez** [comment]
> The format is artist then song title

Changes have been made

**Review by JayBaez — COMMENTED** [review]
Changed the formate from Song - Artist to Artist - Song

**Review by monster860 — APPROVED** [review]

**Comment by JayBaez** [comment]
closing PR and reopening it because I deleted my old repository and messed some stuff up on my side. Also on the side note, I forgot to add a , after the song URL

**Pull request closed without merging**
