### PR TITLE
gives yogs its own lavaland

### PR DESCRIPTION
**Pull request by Amelia0010**

### CODE REVIEW

**Comment by ThatLing** [comment]
why?

**Comment by Amelia0010** [comment]
so we can edit lavaland

**Comment by ThatLing** [comment]
well, did you make any edits?

**Comment by Amelia0010** [comment]
no, I copied the previous one because I like to atomize my PRs

**Comment by ThatLing** [comment]
i don't see the point of this doing this if there's no lavaland edits yet. if you actually edit it, sure go ahead.

**Comment by Amelia0010** [comment]
mane

**Comment by Nickvr628** [comment]
Can we make the lavaland lava yogstation purple since it is planet we mine for PLASMA?

**Comment by Amelia0010** [comment]
please off yourself

**Comment by Nickvr628** [comment]
no u

**Pull request closed without merging**
