### PR TITLE
Lets cargo order tasers if war gets declared

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

so people actually have a reason to use energy weapons or buy an energy shield.
# Spriting

# Wiki Documentation

Cargo can order tasers if nukies declare war
# Changelog

:cl:  
tweak: Cargo can order tasers if nukies declare war
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Sounds terrible. Buy adrenals/double e-sword/e-shield or else you're fucked in one click? It wasn't too great back then, and it won't be now either. E-shields are already good enough without forcing people to buy them.

**Comment by Simplehorror** [comment]
> Sounds terrible. Buy adrenals/double e-sword/e-shield or else you're fucked in one click? It wasn't too great back then, and it won't be now either. E-shields are already good enough without forcing people to buy them.

tasers were easier to play around when you weren't slow as fuck, i'll reduce taser projectile speed, also nobody buys eshields because nobody buys energy weapons in warops because why would you?

**Review by TheRyeGuyWhoWillNowDie — CHANGES_REQUESTED** [review]
Close this pull request

**Comment by Simplehorror** [comment]
> Close this pull request

why

**Comment by Marmio64** [comment]
> > Sounds terrible. Buy adrenals/double e-sword/e-shield or else you're fucked in one click? It wasn't too great back then, and it won't be now either. E-shields are already good enough without forcing people to buy them.
> 
> tasers were easier to play around when you weren't slow as fuck, i'll reduce taser projectile speed, also nobody buys eshields because nobody buys energy weapons in warops because why would you?

Nobody buys them but people still use the energy weapons in the armory, lathe, and sec off disablers if the ops DONT bring eshields. I still see e-shields being useful all the damn time, especially when crew is spamming windows in the hallways and its the only thing forcing the crew to come into actual sightlines with you.

**Comment by Simplehorror** [comment]
> > > Sounds terrible. Buy adrenals/double e-sword/e-shield or else you're fucked in one click? It wasn't too great back then, and it won't be now either. E-shields are already good enough without forcing people to buy them.
> > 
> > 
> > tasers were easier to play around when you weren't slow as fuck, i'll reduce taser projectile speed, also nobody buys eshields because nobody buys energy weapons in warops because why would you?
> 
> Nobody buys them but people still use the energy weapons in the armory, lathe, and sec off disablers if the ops DONT bring eshields. I still see e-shields being useful all the damn time, especially when crew is spamming windows in the hallways and its the only thing forcing the crew to come into actual sightlines with you.

nobody uses those they're noob bait

**Comment by JamieD1** [comment]
No

**Pull request closed without merging**
