### PR TITLE
Mimes Mask = Gas mask

### PR DESCRIPTION
**Pull request by Gh0sT2242**
Buff the mime a bit, by allowing their gas mask to feed them oxygen, in plasma rich, or oxygen devoid areas.

*wave

Suggestion from a player...

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Ummmm. But. Thats. Already. A. Thing.
Are. You. Troling?

**Comment by Gh0sT2242** [comment]
honestly, he's the mime main, he asked if it I could do it, I did this, lol

**Comment by Ktlwjec** [comment]
https://github.com/yogstation13/Yogstation-TG/blob/master/yogstation/README.md I thonk you'll need to make this modular.

**Comment by jcatjmeow** [comment]
This NERFS the mask. Now you need to take it off to eat...this is shameful

**Comment by HomocidlePancakes** [comment]
ffsghost

You are a dumdum Ghost.

**Pull request closed without merging**
