### PR TITLE
Re-adds Partheo's atmos changes

### PR DESCRIPTION
**Pull request by Ktlwjec**
### Intent of your Pull Request
Re-adds Partheo's atmos changes, with an added pump+pipe to engine. Also Partheo's changes to virology and turbine + moves tcomms location slightly south. I've had to add one of the old maint rooms and tweak east engineering slightly to avoid a giant gap in maint and the engineering escape pod having no room.
Have tested it, should work correctly. Blame Highwayman if anything is broken because he helped me make the pr.

Fixes issue #2794 

#### Changelog

:cl:  
rscadd: Re-adds Patheo's atmos
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
Pictures?

**Comment by ThatLing** [comment]
Omg you forgot map merge!

**Comment by ThatLing** [comment]
Why did you delete ai_modules?

**Comment by thehighwayman** [comment]
yes yes and yes

**Comment by Ktlwjec** [comment]
Ling I fucking uploaded a test I was doing then tried to remove it then deleted the entire thing I will fix I promise and give you pictures

**Comment by MegaEmpirical** [comment]
I love you guys.

**Comment by Ktlwjec** [comment]
image
image
Now I hope these images work. Are these ok or do you need them without area things or from in-game too?

**Comment by Amelia0010** [comment]
nerfs AI 👎

**Comment by Ktlwjec** [comment]
frick u nich i fixed it

**Comment by Amelia0010** [comment]
It's still an AI nerf, since there's a meter in between the mixing chamber and incin, meaning you can see just by looking at it that the pump is set to 0 👎

**Comment by MegaEmpirical** [comment]
I don't see how a meter between mix and incinerator matters, there's one on the other atmos too.

**Comment by Amelia0010** [comment]
image
where?

**Comment by MegaEmpirical** [comment]
image

All tanks have a top and bottom meter, I was going to put a bug report in the other day that they're only visible if you right click on them (whereas they used to be visible entirely) but with the change to Parth's atmos I said fuck it.

**Comment by Amelia0010** [comment]
that meter still doesn't impact the function of an AI setting the pipe to incin to 0, but turning it on. This way the meter still shows the pipe as being full

**Comment by MegaEmpirical** [comment]
I don't understand what you're saying.

**Comment by Amelia0010** [comment]
Okay, as a malf AI, I like filling up the mix chamber with a burnmix so I have it ready for when I need to flood. This looks suspicious to literally anyone who looks at it, so I usually set the pump to 0 but turn it on, meaning it looks like it's on, but it doesn't pump anything through. With this change, there's a meter inbetween the mix chamber and the incin, meaning i'd have to fill that entire section up with burnmix as well, in order to cheat the fucking meter

**Comment by MegaEmpirical** [comment]
So, if the issue with the meter on the current map is fixed you would still have this problem. Also, that's not too bad and pretty easy to do. You've more then enough burn mix to spread.

**Comment by ThatLing** [comment]
What could go wrong?

**Pull request merged**
