### PR TITLE
[Asteroid] Expands Cargo

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request

Increases the size of cargo bay, shifts the mules from cargo storage to the cargo bay
Also adds bells to every office because I was giving one to cargo anyways

# Changelog

:cl:  
mapping: Expands the size of Asteroid cargo bay
mapping: Moves the mulebots from Asteroid cargo warehouse to cargo bay
mapping: Adds bells to all required locations (Asteroid)
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
image

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
mulebots are really far back, spending 16 tiles on 4(2) machinery dudes, see about bringing it forward

**Comment by Bibby0110** [comment]
put the map name in the changelog

**Comment by MenacingManatee** [comment]
> put the map name in the changelog

Whys it need to be in the changelog if its in the PR name?

**Comment by ToasterBiome** [comment]
> > put the map name in the changelog
> 
> Whys it need to be in the changelog if its in the PR name?

Changelog doesn't show PR titles only the log

**Comment by MenacingManatee** [comment]
ihatecornflakesihatecornflakes

**Review by ToasterBiome — APPROVED** [review]

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
almost perfect just needs the changelog

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
