### PR TITLE
Reduces cold slowdown

### PR DESCRIPTION
**Pull request by Moltijoe**
The slowdown from being cold is so punishing that often it's impossible to get anywhere fast enough to heat up.
That's just not fun imo.

:cl:  
tweak: Reduces cold slowdown
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
Lizard buff

**Comment by iamthesilly** [comment]
> Lizard buff

lizards are getting additional cold slowdown in another pr made by the same person

**Comment by Notamaniac** [comment]
temp gun nerf too

**Comment by MegaEmpirical** [comment]
Softy.

**Review by ynot01 — APPROVED** [review]
Code works

**Pull request merged**
