### PR TITLE
chem heater on sprite

### PR DESCRIPTION
**Pull request by ToGWtF**
## Intent of your Pull Request

adds a new sprite for chem heaters to show if  they are on or not

### CODE REVIEW

**Review by nesisknesis — APPROVED** [review]

**Comment by Darkstick** [comment]
giv picture pls

**Comment by boodaliboo** [comment]
image

**Review by monster860 — CHANGES_REQUESTED** [review]
I'd prefer something like:
```
icon_state = "mixer[beaker ? 1 : 0][on ? "a" : "b"]"
```

In general the code you've come up with is a bit messy though - you should be putting the more specific options first (reverse of what you have), and then using `else if` to abort out once a decision has been made. What you made works but I don't like it

**Comment by Hopekz** [comment]
Holy shit monster reviews PR's

**Review by monster860 — APPROVED** [review]

**Pull request merged**
