### PR TITLE
Stops Supermatter Shards being spawned in the bluespace locker..

### PR DESCRIPTION
**Pull request by JamieD1**
Fucking horrible round, this is cheese which should not be allowed to happen again.

:cl:  
bugfix: Stops Supermatter Shards being spawned in the bluespace locker..
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
Borg does something else than plasmaflooding on do not allow organics to escape.
> This gets created

(Also ided)

**Comment by JamieD1** [comment]
> Borg does something else than plasmaflooding on do not allow organics to escape.
> 
> > This gets created
> 
> (Also ided)

Those objectives should not be given to a TRAITOR ai, that will be in a new pr.

**Comment by iamthesilly** [comment]
> Those objectives should not be given to a TRAITOR ai, that will be in a new pr.

then make that PR instead

**Comment by Moltijoe** [comment]
Hold up. What happened for this PR to be made?

**Comment by Moja10** [comment]
ided?

**Comment by JamieD1** [comment]
> > Those objectives should not be given to a TRAITOR ai, that will be in a new pr.
> 
> then make that PR instead

Both

**Comment by UltraBigRat** [comment]
with how difficult this would be to pull off needing both finding the bluespace locker and  having access to cargo and opening the sm shard crate, i really dont see the need to remove an interesting tactic like this other then boohoo ided.

**Comment by RG4ORDR** [comment]
> Hold up. What happened for this PR to be made?

What I understand is someone created a portable SM engine in the BS locker.
Apparently the AI was also Malf and found out about this so... I dunno why this would need to be PR'd. There's a multitude of factors and means a player has to actively go through to even attempt this.

**Comment by Maia-J** [comment]
The main issue was reportedly the anomalies, making it effectively a death chamber. Why not disable those is beyond me. (Also you can use the crystaliser to get a sm shard there anyway)

**Comment by RG4ORDR** [comment]
> 

So what.
This even a bug or even an OP thing someone can do. You need to do specific set ups and collaborate with multiple departments to make a bluespace locker engine in the first place.

**Comment by iamthesilly** [comment]
Guh

**Comment by ShoziOffical** [comment]
Guh indeed

**Comment by UltraBigRat** [comment]
This is one of the dumbest self merges ive seen so far.

**Pull request merged**
