### PR TITLE
Runechat can be seen while blind

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
This *should* work, but it might not due to planes
#### Changelog

:cl:  
rscadd: Runechat is visible while blind
/:cl:

### CODE REVIEW

**Review by monster860 — CHANGES_REQUESTED** [review]
you might also need to change the plane

**Comment by Bibby0110** [comment]
> you might also need to change the plane

I know
I just don't want to, but it seems I have to

**Comment by ThatLing** [comment]
Why did you ping the Harvard Computer Society?

**Comment by Bibby0110** [comment]
> Why did you ping the Harvard Computer Society?

We need proper code review

**Pull request closed without merging**
