### PR TITLE
makes Ash (in liquid form) grey

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Ash kinda looks not like ash so I changed it
coder of the year amirite

# Spriting

# Wiki Documentation

# Changelog

:cl:  

tweak: ash is now grey

/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
That’s not ash, you changed charcoal.

**Comment by solwashere** [comment]
> That’s not ash, you changed charcoal.

Guh
I shouldn't make PRs on 4 hours of sleep

**Comment by solwashere** [comment]
fixed

**Review by Moltijoe — APPROVED** [review]
one of the changes of all time

**Pull request merged**
