### PR TITLE
Deletes syndicate bounties

### PR DESCRIPTION
**Pull request by Moltijoe**
Deletes syndicate bounties

# Why is this good for the game?
It should be difficult for traitors to get over 20tc, this isn't a particularly interesting way for them to do it either
it's only really used by the "gamer" traitors trying to get insane setups only possible with more than 20tc which is not what we're wanting to encourage our antag players to do

# Testing
gotta

:cl:  
rscdel: Syndicate bounties
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
Syndicate bounties were the alternative to the absolute bs that were null crates.
They were less stupid but still stupid.
Maybe we can finally do the right thing now and instead add a few crates that DON’T give uplink shit for free.
This is a step in the right direction.

**Comment by AMyriad** [comment]
wholly support this if #15579 gets merged

**Comment by RG4ORDR** [comment]
We've come full circle.  
There were several ways of fixing null crates such as upping their cost, removing or reducing what items came in, and my personal favorite suggestion was adding a 50% chance that it would spawn a hostile General Griefsky in the box. The bounties were done as a compromise because it rewarded stealing and selling objectives that could be other traitor objectives and rewarding you for being more of an antagonist. This further got abused before the IAA rework where IAAs were doing bounties ontop of killing their targets and getting way to many TCs. Otherwise this was merely a way for creative traitors to get some extra TC because admins never answer hacked comms consoles.

TC bounties aren't mandatory for optimal traitor play but it's pretty clear that this is done because some players are once again doing nothing but min-maxxing their antag rounds via this. I dont remotely support the idea of removing this because a few players are once again causing issues by over doing it.

**Comment by Yarinoi** [comment]
we should just ban people we dont like

**Comment by Therandomhoboo** [comment]
There is honestly a simple way to stop all this.
Add a limit to how many bounties you can do? 
Like make that you can do x amount of easy ones, x amount of med, x amount of hard ones. I'd rather we think of ways to improve syndie bounties instead of just removing cause lazy

**Comment by Moltijoe** [comment]
> There is honestly a simple way to stop all this. Add a limit to how many bounties you can do? Like make that you can do x amount of easy ones, x amount of med, x amount of hard ones. I'd rather we think of ways to improve syndie bounties instead of just removing cause lazy

The way to improve them is removing this and adding ynot's pr

**Comment by Therandomhoboo** [comment]
> > There is honestly a simple way to stop all this. Add a limit to how many bounties you can do? Like make that you can do x amount of easy ones, x amount of med, x amount of hard ones. I'd rather we think of ways to improve syndie bounties instead of just removing cause lazy
> 
> The way to improve them is removing this and adding ynot's pr

Ah yes free bounties that come with your uplink, what is this Uno? I don't think its better to allow traitors roundstart potentially get more TC for mediocre missions really. At least with this you have to either go to supply, be a supply job role or build your own machine and still have to use the transport shuttle so you're stuck to one spot. Whereas... Ynots, its go to location you know about and hope sec dont meta it or traitors arent an asshole....

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
