### PR TITLE
maybe fixes vxtvul wielded force

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

hmmm i love tinkering with funky code completely oblivious to the consequences of my own actions

# Changelog

:cl:  
bugfix: vxtvul hammer should probably properly adjust its wielded force now?
/:cl:

### CODE REVIEW

**Review by Moltijoe — APPROVED** [review]

**Comment by iamthesilly** [comment]
for whatever reason it does 16 damage after breaking things with supercharge

**Comment by iamthesilly** [comment]
also the supercharge attack only does 28 damage instead of 40

**Comment by Skrem7** [comment]
> also the supercharge attack only does 28 damage instead of 40

try having the first proc just set force_wielded to 36, then have the second one unchanged

i would test this myself but my test server is bronk rn and i don't have the motivation to fix it atm

wait no i know what the problem is I'll fix it in a moment theos pointed it out hours ago

**Comment by iamthesilly** [comment]
now it does 4 damage when wielded and the supercharged does 16

**Comment by Moltijoe** [comment]
maybe try
force = initial(force) + wielded ? force_wielded : 0
and
force = initial(force) + 12 + wielded ? force_wielded : 0

**Pull request merged**
