### PR TITLE
Operation Steel Rain (Question the pixel frame count and your getting ddos) For real) Im surious) Like really) Dead ass)

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
assault pod targeter remote thing actually has its own sprite now instead of reusing some gang tool one for obj

Dont question the frames dont question my methods dont question anything I do or I will ddos you...

Update- Biomes mother is like the remote sprite, compact, and fits in the UI respectfully. 

Update- If you ever find out cartlords IP please send me a DM, He told me to take my meds and I think I should make him take his own medicine -Hard grounded- 

Update- Ever heard of sherlock? Easy way to find stashes of erotica 

# Spriting

https://user-images.githubusercontent.com/82983051/198533429-218c6d62-a575-43d7-b243-47be6a5f6710.mp4

Capture

# Wiki Documentation

XAXAXAXAXXAXA

# Changelog

:cl:  
 
imagedel: The assault pod remote has its own sprite, too bad your never gonna buy it! 

/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
advanced mining scanner + fridge locker + file cabinet

**Comment by KillerOrcaCora** [comment]
Your missing one more thing 

> advanced mining scanner + fridge locker + file cabinet

**Comment by ToasterBiome** [comment]
> Your missing one more thing
> 
> > advanced mining scanner + fridge locker + file cabinet

what thing

**Comment by KillerOrcaCora** [comment]
image

The remote itself

**Comment by KillerOrcaCora** [comment]
90% of insperation, I scrapped the scanner 30 mins in this 3 hour pain train 

Compacted and fits in the UI Just like your mother

**Comment by Cartlord** [comment]
I like the sprite (specificly the frame shown on the right side of your video), but I think the animation is... overkill. Would absolutely support if this wasn't animated.
Also, please get your shit together, it's disheartening to see an art director asking for my I.P. address because I told them to take their meds after they had what looks like a breakdown, and it also sucks to see you posting stuff like "Dont question the frames dont question my methods dont question anything I do or I will ddos you...".

**Comment by cuackles** [comment]
can i have a video of it animated in game ?

**Comment by KillerOrcaCora** [comment]
> I like the sprite (specificicly the frame shown on the right side of your video), but I think the animation is... overkill. Would absolutely support if this wasn't animated. Also, please get your shit together, it's disheartening to see an art director asking for my I.P. address because I told them to take their meds after they had what looks like a breakdown, and it also sucks to see you posting stuff like "Dont question the frames dont question my methods dont question anything I do or I will ddos you...".

This not being animated would not make sense, especially if you know where I got the chasis for this from. Also 90% of what I say in my PRs is a joke if you take my rambles to heart oh well

**Comment by KillerOrcaCora** [comment]
> can i have a video of it animated in game ?

ill send it later tonight I got school and my beyond is being slower then visual studio codes search speed

**Review by cuackles — APPROVED** [review]

**Comment by Moltijoe** [comment]
my complaint? not animated enough, it only uses like half the display screen in the animation

**Comment by KillerOrcaCora** [comment]
> my complaint? not animated enough, it only uses like half the display screen in the animation

Fuck...I swear ill step my game up next time

**Pull request merged**
