### PR TITLE
Adds Cryostasis to Ninja Jail (Dojo)

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

Adds two cryostasis pods to ninja dojo. They are in the back room behind the kitchen.

# Changelog

:cl:  
mapping: Adds cryo pods to dojo because it's depressing to see a bunch of catatonic people all over
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
Ide be down. Wish there was a system though to retrieve dead bodies in there. Cause when a person does in there their body gets trapped when everyone gets released

**Comment by patpol4** [comment]
Not sure if they dont need the console thing to function

**Comment by Aquizit** [comment]
they don't but it's easy to throw in

**Review by patpol4 — APPROVED** [review]
Alright

**Pull request merged**
