### PR TITLE
Boxstation brig changes

### LINKED ISSUE #7517: Either re-add the teleporter gulag to Box or a locker room
There is no reasonable way to store peoples shit and let them reclaim it on Box. With the telegulag they can collect their shit when they exit. In the absence of that, add a damned locker room with lockers.

### PR DESCRIPTION
**Pull request by Ktlwjec1**
Fixes #7517 , if this isn't liked I can try something else.

Moved beepsky's mom room to the top of the equipment room (currently completely empty), added a bed and turned the secbot into an assembly. May add shutters to the windows in the future, pretty sure we used to have them.
image

Replaced the old (unused) beepsky's mom room with a small locker room to store labor camp prisoners' equipment.
image

A label maker has been added in order to label the lockers if desired.
image

:cl:  ktlwjec
rscadd: Boxstation has a prisoner locker room, located south of the labor camp shuttle dock.
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
Why is cody arrested

**Comment by Ktlwjec1** [comment]
Bluespace locker theft.

**Comment by MegaEmpirical** [comment]
Is the windoor sec locked? (it shouldn't be so that they can get their shit).

Can we get personal lockers instead of generic ones so that only the prisoner with the right ID can open their specific locker?

**Comment by monster860** [comment]
yeah ideally the labor camp system should be such that security doesn't need to do any work to let out prisoners who have gotten their points.

**Comment by MegaEmpirical** [comment]
Exactly my point.

**Comment by Ktlwjec1** [comment]
Windoor has no access requirements. I'll switch them to personal lockers for you, will add some fluff paper on the table to be a security notice or something, stating to use their ID card.

**Pull request merged**
