### PR TITLE
Changes pill capacity from 10 u to 15 u

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request
I rarely see chemists use pills anymore outside of like 2 u inacusiate and oculine, this PR aims to make them more viable for medicines such as neurine and mannitol, 

# Spriting

# Wiki Documentation
None I dont think

# Changelog

:cl:  

tweak: change pill capacity from 10 u to 15 u

/:cl:

### CODE REVIEW

**Review by Moltijoe — CHANGES_REQUESTED** [review]
change the tgui to match

**Comment by solwashere** [comment]
that do it?

**Comment by Moltijoe** [comment]
> that do it?

no, you'll want to revert that.
you want to go into chemmaster.js and edit this
image

**Comment by Moltijoe** [comment]
image
sorry, you actually did want one of those changes, didn't realize they were together in a commit

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
