### PR TITLE
Makes yellow toolboxes spawn with budget insuls 50% of the time instead of real gloves 10% of the time

### PR DESCRIPTION
**Pull request by alexkar598**
Imagine needing an admin meeting and 5 minutes of talking to figure this out

@JamieD1

### CODE REVIEW

**Comment by Georgeur** [comment]
No.

**Review by JamieD1 — APPROVED** [review]

**Comment by Moja10** [comment]
You missed the entire point of the staff meeting, no one had issues with them existing. It was about bwoinking people for having insulated gloves despite there being valid ways to get them on the station. You are completely missing the point entirely with this PR.

**Comment by Tipy1802** [comment]
Great pr! Should probably get completely removed from the loot table imo but baby steps

**Comment by Georgeur** [comment]
no seriously, no.

**Comment by Hopekz** [comment]
Now that we have departmental wires, learning wires for hacking needs to be done a lot more often (multiple times a shift) so I think this PR is appropriate since we have no extra support since that was being required.

**Comment by jcatjmeow** [comment]
I want to first point out that budget insuls are actual trash. They might protect you a little, sure, but they don't protect against the stun, and that's the actual important bit.

Insuls being god tier items that are sought after by powergamers is a bit of a meme, but it's rooted in truth. Shocking doors is incredibly strong and the ability to be entirely immune to that was and is still a huge deal.

I think the issue is not the insuls being too strong, but the ridiculous strength of electric shocks, even small ones but certainly when the power grid gets cranked up for whatever reason. It's actually absurd, and it leads to this arms race where people NEED these golden op as fuck gloves to do anything or they are at a major handicap, and then we nerf those people by taking away the shiny gloves cause the gloves ended up too strong...all the while the real issue is and always has been the stupid shock mechanics.

But uh, manifesto aside 😓 budget insuls are pretty much worthless. I would fully support this change if shocking was nerfed, or the budget insuls were buffed to not stun you even if you take damage (or at least not knock you down for a million years) so they are actually usable. As it stands right now I'm neutral on it.

**Comment by Runian** [comment]
I'm down to rush medical for burn meds (to heal after hacking wires, cuz I'm still gonna do it anyway) and latex gloves that have better protection than insulated budget gloves.

**Comment by Marmio64** [comment]
like jcat said, i'd be down for this if budget insuls were actually made useful. Maybe make budget insuls remove the stun from shocks but not provide any damage resistance.

**Comment by ToGWtF** [comment]
f in chat for the chosen assistants

**Comment by Amelia0010** [comment]
@yogstation13/head-coders you two decide please

**Pull request merged**
