### PR TITLE
baiomu forgot the lawyer spawns

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

# Testing
none needed

# Changelog

:cl:  
mapping: box lawyer office actually has spawns now
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
Sol is going to call Biome dumb

**Comment by ShoziOffical** [comment]
Fix the button access as well

**Comment by ShoziOffical** [comment]
IMG_20231025_084059

**Comment by Aquizit** [comment]
What about the button? There was a recent PR fixing both and yes I tested it.

**Review by Aquizit — APPROVED** [review]
People have to play lawyer to notice these things I guess. Though I guess I also didn't notice it when I fixed the buttons.

**Comment by ShoziOffical** [comment]
> What about the button? There was a recent PR fixing both and yes I tested it.

oh? didnt notice lol

**Pull request merged**
