### PR TITLE
meatballs in food boxes are raw instead of cooked

### PR DESCRIPTION
**Pull request by ktlwjec0**
changes the meatballs in three ingredient boxes from cooked to raw

# Why is this good for the game?
allows them to be used for other stuff too, such as patties. also i think it looks weird when you get a box full of raw meat and then this random meatball cooked

# Testing
yes

:cl:  ktlwjec
tweak: Meatballs in ingredient boxes start off raw.
/:cl:

### CODE REVIEW

**Review by MajManatee — CHANGES_REQUESTED** [review]
image

And what the fuck does "Bigotry rule" mean related to meatballs? ik you didn't but it there but I'm just wondering.

**Comment by neeshacark** [comment]
> image
> 
> And what the fuck does "Bigotry rule" mean related to meatballs? ik you didn't but it there but I'm just wondering.

dont search up british word for meatball

**Comment by ktlwjec0** [comment]
> image
> 

image
here whatever this is stupuid

**Review by MajManatee — APPROVED** [review]
Shmeat

**Pull request merged**
