### PR TITLE
Remove egun from cap locker, gives it to cap on spawn

### PR DESCRIPTION
**Pull request by Ktlwjec**
Kooarbiter -> "captains should spawn with an Egun like hos"
and I agree

:cl:  
tweak: Captains now spawn with their egun.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Why >:l

**Comment by Kmc2000** [comment]
This is an affront to assistants everywhere.

**Comment by ThatLing** [comment]
So, no reason apart from "i want this"?

**Comment by Nickvr628** [comment]
"I died from not having egun pls fix"

**Comment by Ktlwjec** [comment]
Yeah nick, all those 0 times I have died whilst captain because I didn't have an egun. I'm not a child so I don't produce salt whilst playing unfortunately. This was made since a captain (koober) late-joined and got downed almost instantly due to them having no ranged weapon. I've seen this happen far too often. It doesn't bother me either way if this is merged or not as I don't play the role, do as you want with it.

**Comment by Bibby0110** [comment]
I have activated all 7 brain cells and at my disposal, and this now makes sense.

**Comment by Amelia0010** [comment]
Nick cannot comprehend that others may have reasons for their beliefs if they differ from his, so he just goes "I ded" at everything

**Review by Amelia0010 — APPROVED** [review]

**Comment by ghost** [comment]
but then revs or traitors can't break into the captain's office to steal his energy gun before he arrives

also, powercreep, yaddah yaddah, intentional period of vulnerability, etc. honestly none of those matter but it's a downside to anyone who manages to grab the cap's locker that they can't grab the gun as well.

it'd be better to make him spawn with the saber first instead of the gun, if you insist he needs to spawn armed-but note that security doesn't spawn fully outfitted as well, and while the hos does spawn with a gun, cap's not hos

**Comment by Amelia0010** [comment]
You're right in that cap's not hos, he is in fact the only person who spawns with full access to the entire station, including the armoury :)

**Comment by ghost** [comment]
oh right i forgot you guys don't enforce the powergame rule on the captain and that's why zero and i could take half the armory at roundstart

**Comment by Amelia0010** [comment]
Great for you 👍

**Pull request merged**
