### PR TITLE
Replaces cloning, Paramedic area, Morgue and other bits (full rework)

### PR DESCRIPTION
**Pull request by Hopekz**
Replaces cloning and various areas (including paramedic area) with a new improved version.
**MADE WITH MONSTER'S MAP EDITOR!**

image

Why it is good for the game:
-----
image

1
------
**Adds 4 sleepers to medbay and 2 medboxes.**
Nich removed the public medkits so I'm putting them back in and also crew get to have 4 sleepers if they break in through the bronze windows

2
-----
**Medbay now has 2 cogscrabs to fix medbay whenever people are trying to all storm medbay.**
Medbay now gets an eminence to look out for people that are hurt around the station and act as the second CMO.

3
------
**This is where the Paramedics sit.** 
The Teleporting consoles now support 6 paramedics at once ready to teleport right to where they need to be

4
-----
**Medbay now has a lounge!** 
This is where people can relax. Had extra space so put this in

5
------
**The MORGUE pit.**
Medbay now has a central structure connecting all the important rooms. This layout makes a lot more sense.
Also comes with a portal bottomless pit so you can dump dead bodies (since morgue got reworked)

Also
------
This medbay rework makes medbay have a lot of cool sounds like **steam sounds** which add to the ambiance

#### Changelog

:cl:  Hopek
tweak: Replaced Cloning. Paramedic area. Lots of areas! Fully rework!
/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
Literally the best PR

**Comment by yacabo** [comment]
Speed merge

**Comment by Jarod1200** [comment]
EPIC SPEEDMERGE NOW!

**Comment by deathslayer2481** [comment]
Open this shit you cunts

**Pull request closed without merging**
