### PR TITLE
fixes backstories sometimes crashing if you're hijack or martyr bound 

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

fixes this

# Testing

removing returns is how to fix this

# Changelog

:cl:
bugfix: Fixed bacjstorises crashing

/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
you could probably just setup the backstories right before each return

**Comment by cowbot92** [comment]
> you could probably just setup the backstories right before each return

done @ToasterBiome

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
pretty sure you need to pass some args into those procs

**Comment by cowbot92** [comment]
> pretty sure you need to pass some args into those procs

dont be a baby the proc can figure it out itself

**Pull request closed without merging**
