### PR TITLE
DJ station ruin revamp

### PR DESCRIPTION
**Pull request by Hopekz**
salvages from #8354

This was originally going to be a new ghost role but I didn't get time to finish that part so releasing this remade ruin instead since the map is finished.

You can now basically fully live in this ruin if you so chose.
Too many improvements to list including a power system, monstermos protection, an atoms system, etc.

The main "loot" in this ruin is the camera console otherwise it is full of insignificant items such as costumes and maint junk.

Before:
-----
image

After:
-------
image

EDITS:
-----

**EDIT 1:**
Redid the pipes here to be pretty
image

#### Changelog

:cl:  Hopek
rscadd: The DJ station ruin has been redone
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
EDIT:
----

Redid the pipes here to be pretty

image

**Review by patpol4 — CHANGES_REQUESTED** [review]
Couple of minor things:
1. Areas: 
Since you're already working on it,  /area/ruin/space/djstation should be /area/ruin/space/has_grav/djstation
The lattices shouldnt be /area/space/nearstation , use /area/ruin/unpowered/no_grav for ruins, 
also remember the air injector needs to be in a powered area
2. This is how the main table looks ingame, move the vodka so the table is not as empty
dreamseeker_YsiL1jlclh

3.Please set the apc to pixel_y = -23  so we get it out of the way when redoing all the other apc's in our codebase EDIT: Ignore this, solving it in another PR
4. Tinyfan under the entrance please
5. You could make the arcade machine random, unless you prefer orion trail. I don't like how cramped the room is but i guess it's just a ruin so it's ok, purely cosmetic change:
dreamseeker_4id96eULI9
6. A pressure sensor in this spot in a pressure tank setup is always nice to have:
dreamseeker_3bgtx0d8XO

**Comment by patpol4** [comment]
@Hopekz Are you going to be working on this?

**Comment by patpol4** [comment]
Closing due to no author response

**Comment by fluffe9911** [comment]
lets let ktl look at this first

**Comment by alexkar598** [comment]
Stale

**Pull request closed without merging**
