### PR TITLE
Removes cryo syringes and darts

### PR DESCRIPTION
**Pull request by Mqiib**
After careful observation and a small amount of testing I have come to the conclusion that there is literally no reason to every have a cryo syringe for any reason at all other than it being a slightly larger syringe (1/3 size of a bluespace syringe still) or for using it as an instant death explosion dart for oneshotting people. it being barely larger than a regular syringe is weird in the first place since shotgun cryo darts were only 10u anyways and them being a oneshot projectile that only require like a minute of prep time to vomit out four or five easily is not good gameplay. 

# Changelog

:cl:  

rscdel: Removes cryo syringes and cryo darts because they have no gameplay value

/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
nerfing shit just to nerf it

**Comment by Mqiib** [comment]
> nerfing shit just to nerf it

No, removing shit to remove one-shot mechanics.

**Comment by VaelophisNyx** [comment]
make explosive reactions less cancer then

**Comment by Mqiib** [comment]
> make explosive reactions less cancer then

That's 10x as much work for the same result and also impacts other things I don't want to change.

**Comment by ToasterBiome** [comment]
> nerfing shit just to nerf it

classic

**Comment by Maia-J** [comment]
Is this an ided? It feels like a ided.

Anyways, I do get that actually writing interesting solutions to problems is hard because removing code is simply easier. But here's a bunch of ideas I got in like 5 minutes: 

1. The syringes hold the reagent in what is basically a cryostasis, so you could make it it takes time for it to transfer chems instead of it being a instant transfer. Maybe so that it takes some time to start transfering so people get a time to react and get rid of the syringe.
2. Make the syringe lose reagents the further it flies like that cartoonish one that always has that dripping on its end or something.

There is so many creative things you can do with it to make it a dynamic part of combat.

**Comment by Mqiib** [comment]
> Is this an ided? It feels like a ided.
> 
> Anyways, I do get that actually writing interesting solutions to problems is hard because removing code is simply easier. But here's a bunch of ideas I got in like 5 minutes:
> 
> 1. The syringes hold the reagent in what is basically a cryostasis, so you could make it it takes time for it to transfer chems instead of it being a instant transfer. Maybe so that it takes some time to start transfering so people get a time to react and get rid of the syringe.
> 2. Make the syringe lose reagents the further it flies like that cartoonish one that always has that dripping on its end or something.
> 
> There is so many creative things you can do with it to make it a dynamic part of combat.

Not an ided actually, I've mostly just seen other people get oneshot by them (which is not a fun experience). Anyways:
1 - That's already how they work, they inject a certain amount on hit and then a little bit over time. This still causes explosions.
2 - Reducing the capacity for them is not the solution, them losing reagents would just turn them into an instant death melee weapon rather than ranged weapon

The POINT is that there's no way to make noreact syringes that are actually useful for anything a normal syringe or cryo beaker can't ALREADY do beyond instant explosions on impact. I genuinely have failed to find any other use for them that isn't done far better by a bluespace syringe or nearly mimicked by a regular syringe. Really, I've tried to think of decent ways to change them but they just have no interesting use cases at all.

**Comment by Maia-J** [comment]
> Anyways: 1 - That's already how they work, they inject a certain amount on hit and then a little bit over time. This still causes explosions.

You may have misunderstood. I imagined it as instead of exploding you the moment they touch your body, they need to be pulled out in the next 10 seconds or they would transfer. Thus making it instead of a instakill on hit to a more dynamic part of combat.

**Comment by redmoogle** [comment]
> > Anyways: 1 - That's already how they work, they inject a certain amount on hit and then a little bit over time. This still causes explosions.
> 
> You may have misunderstood. I imagined it as instead of exploding you the moment they touch your body, they need to be pulled out in the next 10 seconds or they would transfer. Thus making it instead of a instakill on hit to a more dynamic part of combat.

What about every other mixes of chemicals then
All this would do is allow someone to pull out a shotgun with normal ammo and kill them or force them to die

**Comment by Rdrazga** [comment]
Good pr, haven’t personally seen cryo syringes used for anything in the past long while other than instant win explosives. It would be more interesting or useful if we had chems that actually needed to stay cool or they end up degrading for some high end healing chems.

**Comment by Moltijoe** [comment]
removing them is boring, giving them a proper purpose isn't

**Comment by CMOisLing** [comment]
ided
Just ban Drake already so chem doesnt get all the fun interesting stuff sucked out of it.

**Comment by Moltijoe** [comment]
> ided Just ban Drake already so chem doesnt get all the fun interesting stuff sucked out of it.

Drake isn't the problem though, if drake can do this stuff, anyone can. plus i would argue that insta-kill syringes aren't a fun interesting thing. there are definitely other ways to go about this nerf though

**Comment by GraveHat** [comment]
Instant kill syringes were the reason we nerfed the syringes to inject slowly in the first place.

**Comment by Maia-J** [comment]
> What about every other mixes of chemicals then All this would do is allow someone to pull out a shotgun with normal ammo and kill them or force them to die

Congrats, you figured out a niche dynamic combo that would require a chem to obtain both cryo syringes and a shotgun. Which would probably work on about 2 gamemodes and only with really shitty sec around.

**Comment by redmoogle** [comment]
> > What about every other mixes of chemicals then All this would do is allow someone to pull out a shotgun with normal ammo and kill them or force them to die
> 
> Congrats, you figured out a niche dynamic combo that would require a chem to obtain both cryo syringes and a shotgun. Which would probably work on about 2 gamemodes and only with really shitty sec around.

* forgetting traitors
* forgetting any gamemode

**Comment by Mqiib** [comment]
> removing them is boring, giving them a proper purpose isn't

Did you read what I wrote? They have no purpose, the reaction prevention is _only_ useful for explosions. It has no practical use beyond explosions because there's no reason to delay a chem reaction unless it's an explosion. Maybe possibly there are some extreme edge cases where it might maybe have some impact but I can't find any feasible use for it beyond "you can do this thing that isn't helpful."

I'm not going to try to make noreact syringes useful with some kind of crazy complicated rework of how chemicals work. If we had tg chem maybe they can get re-added and someone can find a use for them, but for now explosions are all they can do.

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
