### PR TITLE
Makes luxury shuttle an emag_buy

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

Luxury shuttle causes lots of problems for pretty much everyone, especially on early shuttle call
People are forced in the back in a tiny space where one flamethrower shot kills the entire crew
Additionally, this shuttle makes it ASS for antags
Any antag that isnt a carbon can't get on
Any antag that is a carbon needs to yoink an ID to get on
Any antag that wants to bomb the shuttle can't because it's fucking **invulnerable** (for memes lol)
Nukies schmukies, good fucking luck doing anything to this shuttle
You wanted to hijack? Well you better do it before anyone gets on because you can't bomb it and once the shuttle's in flight you can't get to the other area

Oh and it's **no_teleport** aswell, because fuck you

Been meaning to make this PR for a while

#### Changelog

:cl:  
tweak: Luxury shuttle is now emag only
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
100% agree, its the most stupid shuttle.

**Comment by overlord12345** [comment]
just replace it dont lock it under emag

**Comment by Jarod1200** [comment]
replace it with disco inferno

**Comment by Xoxeyos** [comment]
Don't remove it.

**Comment by Hopekz** [comment]
I fully agree it is OP compared to the other shuttles but I still think its really "cool" to have and adds to the experience.
Neutral and will probably stay neutral

**Review by Hopekz — APPROVED** [review]

**Comment by Leatherturtle** [comment]
I rather like the idea of a redesign, not liking it behind emag. Make it not invulnerable to all damage, maybe add another class for people, full removable just isn't the right thing here.

**Comment by Marmio64** [comment]
make luxury shuttle way more expensive so its harder to get

**Comment by HomocidlePancakes** [comment]
Just port TG luxury shuttle.

**Comment by MegaEmpirical** [comment]
Why not remove the problematic issues with it?

**Comment by ynot01** [comment]
merge this until someone makes the changes, subjective improvement

**Comment by alexkar598** [comment]
Make it able to teleport and make the walls destructible. Doesnt sound hard to fix

**Comment by alexkar598** [comment]
Closing due to overwhelming negative support

**Pull request closed without merging**
