### PR TITLE
No more clowns getting clown ops gear... for cheaper than the ops do. Who did this??

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Clown op dark honk = 35 TC
Traitor dark honk = 20 TC

To be clear, there is a SECOND instance of the dark HONK that is STILL in the code, that's for the clown ops. Idk why this was done so dumbly but here we are. Anyways the traitor honk is gone now.

They are identical. Who thought this was a good idea???

# Spriting

:cl:  
tweak: traitor clowns cant buy nukie gear because that's dumb
/:cl:

### CODE REVIEW

**Comment by LazennG** [comment]
lol

**Comment by Mqiib** [comment]
because it's FUNNY

**Comment by Hislyna** [comment]
Literally the most controversial PR to ever be put on the github, also Ided cause funny

**Comment by MajManatee** [comment]
They removed the Ided tag because people were crying or something idk.

ALTERNATIVE to this PR, is just letting clowns buy the dark HONK that nukies can get for the nukie price so they have to co operate

**Comment by Hislyna** [comment]
> They removed the Ided tag because people were crying or something idk.
>
This is the saddest news I've heard this week

**Comment by Hislyna** [comment]
Maybe let them buy a regular loaded H.O.N.K but rename it so people know its an antag one?

**Comment by TheRyeGuyWhoWillNowDie** [comment]
SIGNIFICANT OPPOSITION

**Comment by TheRyeGuyWhoWillNowDie** [comment]
CONTROVERSIAL

**Comment by 00ze-cyclone** [comment]
Nuke ops having to pay more TC for stuff isn’t new, they have to pay more for holopara. TC balance is wildly different between traitors and nukies, dark honk for clown ops is a bunch of TC, dark honk for a traitor is all their TC.
Anyway clown tier PR.

**Comment by Burger1998** [comment]
Nukies pay a premium for items traitors get for like 2tc all the time.(TC inflation)

**Comment by UltraBigRat** [comment]
This was specifically lowered so traitor clowns can afford it, its not even that good of a mech. Antag with a completely different level of power that can stack a ton more gear on top of the mech getting it for more isnt a reason to disable it. Regular clown tots meanwhile need to decide if they want a mech or literally anything else.

**Comment by Moja10** [comment]
So far i've only seen it used once, and the clown had hijack, I think that's a perfectly reasonable thing to have if you have hijack. The murderbone is kept down and not an issue because nonhijack clowns are still bound by the murderbone rules (aka don't dark honk every single round and kill all sec and random people in the bar and shit)

**Comment by Moltijoe** [comment]
significant opposition

**Pull request closed without merging**
