### PR TITLE
[ADMIN] [MENTOR] Mentor new people alert

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Mentors now get alerted to new players connecting for the first time, and their Ckey so they can try to be helpful

# Testing

Not really able to do on local, but should work.

# Changelog

:cl:  
rscadd: Mentors get alerted to new players connecting for the first time.
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
if this uses the same code as the way admins are pinged it will ping even if the player has say a 2012 account. you should probably either have it state account age in the message or make it only ping if the account itself is new - new connects to yogs are generally decently aged accounts.

**Comment by MajManatee** [comment]
> if this uses the same code as the way admins are pinged it will ping even if the player has say a 2012 account. you should probably either have it state account age in the message or make it only ping if the account itself is new - new connects to yogs are generally decently aged accounts.

Done, thanks for the heads up.

**Comment by ynot01** [comment]
Can you exclude dementored mentors

**Review by ynot01 — CHANGES_REQUESTED** [review]
^

**Comment by MajManatee** [comment]
As its written right now, it should not include de-mentored mentors. This is handled the same way things like Msays are handled.

**Comment by ynot01** [comment]
cringe! someone should change that

**Review by ynot01 — APPROVED** [review]

**Comment by ynot01** [comment]
oh god it doesnt have any formatting its just gonna be white thats ugly whatevr

**Pull request merged**
