### PR TITLE
Adds infrared sights attachment

### PR DESCRIPTION
**Pull request by ynot01**
Bravo Six, going dark

# Document the changes in your pull request

Uses built in BYOND infrared system

Added infrared sights

Also cleaned up some minor stuff with laser sights

# Mechanics

"A polarizing camera that picks up infrared radiation. The quality is rather poor, so it ends up making it harder to aim."

Infrared sights make you slightly worse at aiming (2 degrees variance) for balance, good when paired with the laser sight

Must be held and turned on (toggle with action) to have infrared sight, it will not work in your vest

All humans will show up white and you will have black & white vision

Cyborgs will not show up on infrared

Mechs will show up on infrared

Mobs will show up on infrared at a range depending on their body temperature

- Default body temperature, 37C, will show up at 11 tiles range
- 20C will show up at 6 tiles
- 10C will show up at 2 tiles
- 0C will not show up on infrared

You will be able to see people in the dark as long as the gun with the sights are held

Holstering the gun will remove the infrared vision

# Spriting

# Changelog

:cl:  
rscadd: Added infrared weapon sights, locked behind the Weapon Development Technology node
bugfix: Laser sights icons update properly now
bugfix: Laser sights now play their sound properly when turned on/off on a gun
/:cl:

### CODE REVIEW

**Review by ReddicusDragon — APPROVED** [review]
code looks good

**Comment by Simplehorror** [comment]
this is thermal sights not infrared sights

**Comment by ynot01** [comment]
> this is thermal sights not infrared sights

i'm by no means an expert but reading [this](https://www.flir.com/support-center/oem/what-is-the-difference-between-active-ir-and-thermal-imaging/) from an FLIR company seems to line up completely with my implementation

additionally we already have an established "thermal" mechanic in place so it would be very confusing to players to have both named the same

also BYOND literally names the implementation "infrared"

**Review by cuackles — APPROVED** [review]

**Comment by githubuser4141** [comment]
> this is thermal sights not infrared sights

it's just thermals but with actual thought put into it instead of just "lol xray vision"

Idea: Add a mech module for this too. It's kind of shocking how mechs don't improve your vision in any way (save for Clarke/Ody diag/med HUDs. It'd be totally plausible for a... sci-fi fighting vehicle to have thermals/infrared sights just like IRL (gasp!) fighting vehicles do! Realistically it should be somewhat improved too as it could be a lot heavier and run of off the vehicle-grade power source

**Review by ReddicusDragon — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
