### PR TITLE
Adds access to the clerks office to Security and Engineering Service Jobs.

### LINKED ISSUE #10117: sec service access
- on at least YogsMeta, it seemed that service guard has access to all service areas **except** the gift shop main plus inner door, yet once they're inside, they have access to the shutters, plus the gift shop maintenance.

### PR DESCRIPTION
**Pull request by Bibby0110**
# Github documenting your Pull Request

Fixes https://github.com/yogstation13/Yogstation/issues/10117

# Wiki Documentation

# Changelog

:cl:  
tweak: Security officers assigned to the service department are now allowed in the clerks shop.
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
Will this also apply to Service Engineers?

**Comment by JamieD1** [comment]
Apply to service engineers as well please.

**Comment by Bibby0110** [comment]
> Apply to service engineers as well please.

Not in the scope of this PR

**Review by adamsong — APPROVED** [review]
Simple enough change

**Pull request merged**
