### PR TITLE
Makes healing items less tedious to use

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Healing items such as sutures, mesh, etc. now heal a random damaged limb if the targeted one is fine, in order to make them less tedious to use.

# Changelog

:cl:   
tweak: healing items like sutures heal a random damaged body part instead if the selected one is fine
/:cl:

### CODE REVIEW

**Comment by UltraBigRat** [comment]
does this work for welder and cable healing too?

**Comment by iamthesilly** [comment]
> does this work for welder and cable healing too?

Yes

**Comment by SomeguyManperson** [comment]
Can't you just switch the limb you are targetting?

**Comment by iamthesilly** [comment]
> Can't you just switch the limb you are targetting?

Yes but mashing the keyboard like that is tedious and annoying

**Comment by Therandomhoboo** [comment]
I think its fine where it is at. Yeah it is tedious/annoying but all healing shouldn't be just a breeze to do. Unless its bardrinks then that should always be a breeze.... a _seabreeze_ that is.

As well as I think this also stops antags/sec dipping into a side standing still and then healing all limbs up.

**Comment by Scrambledeggs00** [comment]
Is it canceled if it tries healing a body part that can't be heal? An example being head with something that blocks healing items like the envirohelm.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
