### PR TITLE
New Station Trait: Cybernetic Revolution + Body Purist Quirk 

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Port of https://github.com/tgstation/tgstation/pull/71229

Adds a new positive station trait, Cybernetic Revolution. Weight of 1.
It gives every station job an organ, implant, or ability that is themed around cybernetics (if possible).
The given organ/implant/abilities are:

- AI: Relay Speech
- Assistant / Artist / Janitor / Tourist: Cybernetic Heart
- Atmospheric Technican: Breathing Tube Implant
- Bartender: Upgraded Cybernetic Liver
- Brig Phys/Mining Medic/Paramedic: Medical Hud
- Botanist: Nutriment Pump Implant
- Captain / Lawyer: Upgraded Cybernetic Heart
- Cargo Technican / QM: Cybernetic Stomach
- Chaplain / HoS: Anti-Drop Implant
- Chemist / Scientist: Science Hud
- CE: Thrusters Implant
- Clerk: Cybernetic Stomach
- Clown: Anti-Stun Implant
- CMO / Miner: Reviver Implant
- Cook: Nutriment Pump+ Implant
- Curator: High Luminosity Eyes
- Detective: Upgraded Cybernetic Lungs
- Doctor: Surgical Toolset Implant
- Engineer/Network Admin: Engineering Toolset Implant
- Geneticist: Fly Stomach
- Mime: Robotic Tongue
- Security Officer: Arm Flash Implant
- Psychiatrist: Cybernetic Ears
- RD / Roboticist: Diagnostic Hud
- Virologist: Upgraded Cybernetic Lungs
- Warden: Security Hud

Halves (and rounds up) any implant-related items in the traitor Uplink. Affected items are:

- Everything in the Implant Category
- Vxtvul Hammer Implant: 10 -> 5
- Arm Mounted Medical Beamgun: 8 -> 4

Doubles or triples the cost of any EMP-related items in the traitor Uplink. Affected items are:

- 10mm EMP Magazine: 2 -> 6
- EMP Grenades and Implanter Kit: 2 -> 6
- Syndicate EMP Bomb: 7 -> 14
- EMP Flashlight: 2 -> 6
- Illegal Ammo Design Disk: 4 -> 12

Adds a new negative mood quirk, Body Purist.
It gives 2 quirk points on selection and is incompatible with all quirks that offer robotic limbs/organs.
It gives -10 mood points per robotic limb/organ you currently have.
It prevents Cybernetic Revolution from giving its effects to your character.

Swaps the initialization order for Station and Research.
Adds missing signals related to the loss or gaining of organs/limbs.

# Why is this good for the game?
Spices up the game with a rare station trait by letting cybernetics/implants showcase themselves every now and then. Lets people, particularly people who don't know that implants exist, feel what having cybernetic organs/implants and maybe consider getting them on a round where it is not forced on them (which they can opt out of via quirk).

# Testing
Relevant uplink prices halved / tripled:
image
image

Relevant tech nodes costs halved:
image

Doctors spawned in with surgical toolset.
Geneticists spawned in with insectoid (fly) stomach.
Body Purist correctly prevents the effects of the station trait.
Replaced robotic limb/organ with autosurgeon while having Body Purist correctly updatesmood.

# Wiki Documentation
Add new quirk to https://wiki.yogstation.net/wiki/Quirks.
Name: "Body Purist"
Balanced: +2
Desc: "You believe your body is a temple and its natural form is an embodiment of perfection. Accordingly, you despise the idea of ever augmenting it with unnatural parts, cybernetic, prosthetic, or anything like it."
Gameplay: "Your mood substantially decreases for each robotic/synthetic limb or organ your character has."
Mood locked: yes.

# Changelog
:cl:  
rscadd: Positive station trait, Cybernetic Revolution.
rscadd: Negative mood quirk, Body Purist.
bugfix: Limping is properly given/removed when attaching/detaching limbs.
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
I actually love this quirk

**Comment by Yarinoi** [comment]
wardens start with a sechud implant if they have the nearsighted quirk, if i had to guess it's probably the same for the RD for the diagnostic hud so it might need some work
other then that, cool stuff! ~~now code cyberpsychosis~~

**Comment by iamthesilly** [comment]
Body purist should probably care much less about cybernetic organs than actual augments, since you need them to live.

**Comment by PibeCantina** [comment]
BASED????????????

**Comment by Maia-J** [comment]
I just woke up, so I wont read the actual code, but are body purists protected from the station trait?

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
