### PR TITLE
SOME FUCKING DUMBASS MOVED THE MAGIC MIRROR TO THE BATHROOM

### PR DESCRIPTION
**Pull request by boodaliboo**
WHY WOULD YOU DO THIS IT MAKES NO SENSE
#### Changelog

:cl:  
tweak: PUT THE MAGIC MIRROR WHERE IT ORIGINALLY WAS
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
nice

also the entire reason it was moved was because of how easy to get to it. that reasoning is now baseless due to the """good change""" of making everything admin walls and admin windows.

**Comment by jcatjmeow** [comment]
mirror goes in the bathroom tho

**Comment by patpol4** [comment]
no u

**Comment by patpol4** [comment]
Mirrors belong in bathrooms, not head wizard offices. Also see the thing Reed commented.

**Comment by Reed0506** [comment]
bruh wej did you even read what i said

**Pull request closed without merging**
