### PR TITLE
New AI VOX: Cass

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

_Introducing C.A.S.S (male), the latest edition to Nanotrasen's line of AI Binary-To-Speech program. Cass features over 500 common and unique sounds as well as all of the basis sentence structure components for you to build a unique sentence of your own!_

Cassie is the announcer/AI program that is featured in the game SCP: Secret Laboratory. Cassie contains a lot of nouns and verbs that are highly related to the station and can be used by the AI to effectively make a VOX message. All of the basis alphabet letters are included (a, b, c, etc..) as well as their sounds. Basic sentence structure words like the, it, him, who, why, were, etc.. are all included as well as advanced words such as foundation, facility, emergency, evacuate, hello, nuclear, etc.. are all included.

https://www.youtube.com/watch?v=_ZXWLPKn2pk

Here's an example of the VOX voice. Most of the lines featured in that video are assembled from individual words below, so players can re-arrange them in order to make it fit on SS13.

This took me many hours dont let this flop, i want my sounder role too

#### Changelog

:cl:  
rscadd: Adds Cass, a new AI Vox
soundadd: Adds 522 sound files for the Cass AI vox  
experimental: This is experimental  
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
Isn't Cassie a girl name? This is a male voice. 

It might be smart to give it a slightly different name so people don't select it thinking it will be a female voice when it plays their message.

**Comment by swissloaf** [comment]
> Isn't Cassie a girl name? This is a male voice.
> 
> It might be smart to give it a slightly different name so people don't select it thinking it will be a female voice when it plays their message.

It's Cass now. Cassie was the original name in SCP but I see the point.

**Review by JamieD1 — APPROVED** [review]
Need a bigger boy then me to check this.

**Review by JamieD1 — CHANGES_REQUESTED** [review]
You have a lot of Cassie references still in here.

**Comment by swissloaf** [comment]
> You have a lot of Cassie references still in here.

Fixed

**Review by nesisknesis — COMMENTED** [review]
Checked it out in game and i'm going to have to admit, it's pretty shoddy.

Because it's just a blanket voice, it just 'plays', sounding rather out of place. 

The OG Vox works because it has an amount of echo which makes it sound like its originating across the station.

**Comment by swissloaf** [comment]
> Checked it out in game and i'm going to have to admit, it's pretty shoddy.
> 
> Because it's just a blanket voice, it just 'plays', sounding rather out of place.
> 
> The OG Vox works because it has an amount of echo which makes it sound like its originating across the station.

yeah I know, im working on that.

**Comment by swissloaf** [comment]
update: hopek is supposedly working on echo

**Comment by swissloaf** [comment]
I haven't gotten around to working on it but I will soon

**Pull request closed without merging**
