### PR TITLE
Adds Soccer to the game

### PR DESCRIPTION
**Pull request by dcxgame**
Adds a soccer ball, which can be found in the gift vendor, and a holodeck soccer field, with goal nets included.
The ball can be kicked by attacking it with any item or an open hand. It will fly similarly to a golf ball, except that it will bounce off of walls.
The goal net is three separate pieces, a net and two posts. The posts will block shots, and the net will confirm or deny a goal similarly to a basketball hoop, though the ball will fly back out for easier collection.
Finally, while two soccer balls are available for purchase in the gift shop, a full field is available in the holodeck. This is to give you the complete experience without having to dig into someone's department or play in the hallways, you lousy kids!

# Spriting

dreamseeker_CXREAsP0N8
Moja here was kind enough to pose with all the new sprites. Collect his rookie card now, it'll SKYROCKET when he makes it to the Galaxy Cup!

# Wiki Documentation

The presence of the soccer ball should make it into any pages related to toys, and the field into any concerning the holodeck, if there are either. The net does not currently have a construction method.

# Changelog

:cl:  
rscadd: added soccer to the game
imageadd: added sprites for a soccer ball and goal net
mapping: new holodeck room to play soccer in
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Its called Football you uncultured swine

**Comment by LoliconSlayer** [comment]
> Its called Football you uncultured swine

Soccer*

**Comment by Hislyna** [comment]
> > Its called Football you uncultured swine
> 
> Soccer*

Americans when they cant win a sports game so they make a game thats a worse version of another game and call it by a totally different games name

**Comment by cuackles** [comment]
As art director i request this to be named correctly ( football ) (( real review tomorrow))

**Review by Aquizit — APPROVED** [review]
As the easiest part of this PR: map's fine!

**Review by Aquizit — CHANGES_REQUESTED** [review]
Just kidding, please make sure you're using this type of turf 
image

**Comment by solwashere** [comment]
SOCCER!!!!! SOCCER WOOOOOOO!!!!! SOCCER NOT FOOTBALL, USA NUMBER ONE!!!! USA USA USA USA 🇺🇲🇺🇲🇺🇲🇺🇲🇺🇲🇺🇲🇺🇲🇺🇲

**Comment by DeadlyBag** [comment]
downvoted

Use the name thats used across the entire world you fucking yank

**Comment by Therandomhoboo** [comment]
Its football

**Comment by azzzertyy** [comment]
its football specifically because this is a british server and not an american server and all words in code match this, even "colour"

**Comment by Therandomhoboo** [comment]
> its football specifically because this is a british server and not an american server and all words in code match this, even "colour"

except for sulphuric which is sulfuric

**Comment by MajManatee** [comment]
BRAZIL ES NUMERO UNO!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Review by cuackles — APPROVED** [review]
apart from the horrid issue of calling football an incorrect name, everything else spritewise seems fine, there might be some banding in the ball but the colors are so similar and im so fucking blind its hard to tell

**Review by Aquizit — APPROVED** [review]

**Comment by Aquizit** [comment]
omg molti set me up

**Pull request merged**
