### PR TITLE
Lag removal, try 2

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
Does that thing with the thing I did once where a dll measures time taken by byond to send map updates and it's included in master controller calculations so lag spikes are reduced but not completely eliminated cause its not clairvoyant so don't be upset if you get a lag spike caused by the shitty database driver lib or tgui or garbage collection and then you die because of it

[cod](https://github.com/MCHSL/extools/blob/master/byond-extools/src/maptick/maptick.cpp)

Don't testmerge along with dos protection it might explode

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I forgot to switch branches and only partially successfully tried to move my changes

**Comment by Hopekz** [comment]
Travis is upsetti

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Who cares

**Comment by Bibby0110** [comment]
make it stop

**Comment by optimumtact** [comment]
The funny thing about this is the more common lag you eliminate, the more annoying the edge case spikes become.

**Comment by MCHSL** [comment]
bsql is killing me

**Comment by alexkar598** [comment]
person coder told me its safe to merge

**Comment by AshCorr** [comment]
Code needs to be added to the yogs repo.

**Pull request merged**
