### PR TITLE
Updates Security to Council Standards

### PR DESCRIPTION
**Pull request by Bibby0110**
# Github documenting your Pull Request
Adds 47 pulse rifles, 11 mechs and admin only walls to Security.
According to Council you're allowed to fortify the brig to extreme levels so I thought, why not remove the middle man and just add it directly to the station.

Security is fully independent now. They have a supermatter crystal in the armory and their own gravity generator

# Changelog
:cl:  
bugfix: Fixed a few missing items from Security.
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Please add screenshots of any map changes

**Comment by SomeguyManperson** [comment]
still can't add a disabler turret to the armory 😿

**Comment by JamieD1** [comment]
Dont see anything wrong with this, @wejengin2 need your eye on this.

**Review by patpol4 — APPROVED** [review]
Powercreep but im sure our sec can handle the extra responsibility

**Comment by Moggram** [comment]
Hey, there is no exosuit fab. How are we going to make ammo and guns?

**Comment by adamsong** [comment]
'Borrow' one from robotics, I'm sure they won't put up much argument for long

**Comment by JamieD1** [comment]
This meme fucked a round up, so well done everyone including myself.

**Pull request closed without merging**
