### PR TITLE
removes sex

### PR DESCRIPTION
**Pull request by Bibby0110**
pg-13

### CODE REVIEW

**Comment by Maia-J** [comment]
Remove the sprite too + meme pr + remove references + no maidens + ratio

**Review by Moltijoe — APPROVED** [review]

**Comment by Moltijoe** [comment]
should probably also remove the sprite tho

**Comment by iamthesilly** [comment]
Sex bad, do not the sex

**Comment by Maia-J** [comment]
> should probably also remove the sprite tho

Or just not remove it because there's still the lusty xenomorph one... and pictures of ass... and vorecode....


Or he could change the description instead? It's been spawning on station for years and nobody even noticed.

**Pull request merged**
