### PR TITLE
Replaces Feweh in the wizard academy 

### PR DESCRIPTION
**Pull request by LoliconSlayer**
Feweh's not even associated with Yogs
Anvil's a great member of our community and very popular

:cl:  
tweak: Feweh the Replicator has been expelled from the wizard academy! In his place, Anvil the Archivist has transferred in.
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
If you hate bowl then actually suggest someone else instead because Feweh's got to go.
And it can't be Colton, Wej is replacing Rotciv with Colton if he's gonna keep his word.

**Comment by Hopekz** [comment]
It doesn't need to be replaced with anyone tbh
Just make him generic

**Comment by LoliconSlayer** [comment]
Didn't realize that Bowl was already in here, time to brainstorm someone else

**Review by patpol4 — APPROVED** [review]
I don't care enough anymore

**Pull request merged**
