### PR TITLE
makes worldshaker and ultrakill admin only because nobody knows how to do game balance

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
Krav Maga: These gloves provide a useful stun if the prisoners are getting uppity, can't be disarmed either. Can also KO them with several hits! Only useful in the brig though.

CQC: Good for stealth! You can drop someone to the ground and silence them before they can scream, be careful though, you don't have any advantage at range!

Sleeping Carp: You do plenty of damage in melee. You can deflect bullets too! However, you can't use guns, rendering you committed to your art once you've learned it.

Flying Fang: You do a lot of damage in melee, although without as many stuns. Unlike the other martial arts, you get a ranged attack! Also, you can heal a bit off of fallen enemies, this leaves you vulnerable though, so be careful! No guns or armor either.

V1: I KNOW SUMMON GUNS IS A WIZARD ITEM, BUT LET'S GIVE IT TO TRAITORS TOO. WHILE WE'RE AT IT, WE'LL DOUBLE THEIR MAX HEALTH. NEED TO BE SURE THE TRAITOR'S UNSTOPPABLE TOO, SO NO EMPS! NO STUNS EITHER! ALSO, THE TRAITOR CAN CONSTANTLY HEAL OFF OF EVERYONE BY PUNCHING THEM, AND IF THEY GET IN TROUBLE THEY CAN DASH AWAY AT A MILLION MILES PER HOUR, WHICH ALSO MAKES THEM INVINCIBLE

Worldshaker: ENOUGH BEING SUBTLE. YOU HAVE 100% DAMAGE RESISTANCE. YOU GET AOE STUNS. YOU GET MELEE STUNS. YOU GET RANGED STUNS. GO FUCKING NUTS.

Do you see the problem with the last two martial arts?

# Changelog

:cl:  
rscdel: V1 and worldshaker are admin-only
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
How the hell this got conflicts already

**Comment by Moltijoe** [comment]
> Worldshaker: ENOUGH BEING SUBTLE. YOU HAVE 100% DAMAGE RESISTANCE. YOU GET AOE STUNS. YOU GET MELEE STUNS. YOU GET RANGED STUNS. GO FUCKING NUTS.

correct

**Comment by UltraBigRat** [comment]
improve dont remove

**Comment by Moltijoe** [comment]
What a joke, just after desword got readded too

**Comment by ToasterBiome** [comment]
Conflict of interest

**Comment by ToasterBiome** [comment]
Yeah this idea is not good, there’s nerf PRs up.

**Pull request closed without merging**
