### PR TITLE
shadowlings can no longer catch fire

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

remove cheese tactic

Sister PR to #16598
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: shadowlings can no longer catch fire
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
Step 1. Get shot with Dragonsbreath
Step 2. Die because I cannot counter it

**Comment by Ethan4303** [comment]
simplehorrors Prs are the funniest of PR's

**Comment by Simplehorror** [comment]
ok so people whining in other PR that shadowlings are too weak and now people are crying that they're too strong here.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
🤡

**Comment by Simplehorror** [comment]
@KillerOrcaCora ?

**Comment by KillerOrcaCora** [comment]
Low effort, didn’t fill templates correctly

**Pull request closed without merging**
