### PR TITLE
Sling sacrifice now dusts to prevent defib scumming 

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

saw theos doing this yesterday, naughty theos
it was supposed to prevent revive before, this just reinforces it

#### Changelog

:cl:  
tweak: Shadowling shuttle sacrifice now dusts to prevent revival
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
creative use of game mechanics

**Comment by ynot01** [comment]
> creative use of game mechanics

its literally supposed to disable revive but you can just defib them

**Comment by boodaliboo** [comment]
> > creative use of game mechanics
> 
> its literally supposed to disable revive but you can just defib them

creative use of game mechanics

**Comment by Ratvar** [comment]
Could just husk em instead

**Review by JamieD1 — APPROVED** [review]

**Comment by Darkstick** [comment]
I don't agree with this, but if it has to happen:

how about it turns them into shadow people instead? You know, the shitty kind, that all it does is burn to death in the light.

That, or simply make it husk, like ratvar said.

**Comment by ynot01** [comment]
i feel like you guys miss the comment written right next to the code stating its intention

`//sacrificed thrall is permadead`

**Comment by boodaliboo** [comment]
still dont care

**Comment by alexkar598** [comment]
A bug fix is a bug fix you fucking retards

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
