### PR TITLE
Gives people adminhelp verb when admins respond

### PR DESCRIPTION
**Pull request by Amelia0010**

### CODE REVIEW

**Comment by ThatLing** [comment]
Why?

**Comment by Amelia0010** [comment]
because otherwise they can't respond to the adminhelp

**Comment by Amelia0010** [comment]
I think

**Comment by ThatLing** [comment]
They can, this is used for making a new ticket

**Comment by Amelia0010** [comment]
huh, mitchnoff had an issue where he couldn't respond to the ticket after he made it. OH WELL

**Comment by ThatLing** [comment]
But literally everyone else could respond without a problem

**Pull request closed without merging**
