### PR TITLE
Ports https://github.com/tgstation/tgstation/pull/66299

### PR DESCRIPTION
**Pull request by Simplehorror**
About The Pull Request

Implements soft pings, as it was previously done in Goonchat.

Before: Pings were initiated by tgui-panel and sent continuously in a 2.5 second loop.

Connection quality is based on how many pings were lost, and alert is shown if 3 pings consecutively timed out.

After: Pings are no longer initiated by tgui-panel, and instead are initiated by the ping subsystem in DM. It runs every 4 seconds and sends a "soft" ping, which isn't really a ping, but more of a status update about the client, with information on how long they have been inactive since the last soft ping cycle. If client is active, ping is sent by tgui-panel. That's the only time when the ping number changes, and all other time it will remain the same.

Connection quality is still calculated based on how many pings were lost, but alert is shown only if soft-pings were not received in 10 or so seconds.
Why It's Good For The Game

Inactive and deadminned players will now be properly kicked out of the game, because pings will not be sent by inactive players and will not reset the AFK code.

Both manual reconnect and automatic reconnect now work 100% of the time, because previously pings interfered with the reconnect message sent by Dreamseeker (it's a BYOND bug, blame Lummox for not fixing it for years).

This might also reduce some stress on the server, because AFK players will get kicked, semi-AFK players will not send pings, and frequency of pings is generally much slower now (but it does add a subsystem for sending extra soft pings, so ¯\_(ツ)_/¯)
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  stylemistake
rscadd: Ping system of tgui-panel has been reworked, which fixes things mentioned below.
bugfix: AFK players now get properly detected and kicked
bugfix: Automatic reconnect should now work 100% of the time
bugfix: Manual reconnect should now work 100% of the time
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
copy the pr body of the port

**Comment by Simplehorror** [comment]
idk why its whining at me hold on

**Comment by ShoziOffical** [comment]
> bugfix: AFK players now get properly detected and kicked 

why is this a bug?

**Comment by Simplehorror** [comment]
quit blowing smoke in my face

**Comment by ShoziOffical** [comment]
also fix ur lint

**Comment by Simplehorror** [comment]
:trollface:

**Comment by Bibby0110** [comment]
it never compiled

**Comment by Simplehorror** [comment]
it compiled, linter failed

**Pull request closed without merging**
