### PR TITLE
You no longer heed a helmet to be space-proof if you don't have a head

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Why would you need a helmet if you don't need a head?

# Changelog

:cl:  
tweak: you no longer heed a space helmet if you don't have a head
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
Heed the helmet

**Comment by Marmio64** [comment]
most suits probably are designed for people with heads so the top of it would just be entirely open unless you cover the hole to stop your body from being exposed.

**Comment by Bibby0110** [comment]
hello how are you going to seal the suit???

**Comment by MajManatee** [comment]
they got a point

**Comment by githubuser4141** [comment]
> most suits probably are designed for people with heads so the top of it would just be entirely open unless you cover the hole to stop your body from being exposed.

maybe nanotrasen are inclusive enough to put some spare material at the neck cuff to seal the suit if you don't have a head?
it is 25th century after all :)

**Comment by wonderinghost** [comment]
It's slime fuckery

**Comment by iamthesilly** [comment]
Mainly made this for IPCs because they can live without a head but can't wear a helmet  without it so if they lose it (which is somewhat common) they have no way to be spaceproof whatsoever but making it so space helmets can be used without a head would break a lot of stuff

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
