### PR TITLE
Removes the wombarian fugu from xenobiology (xeno nerf 1/5)

### PR DESCRIPTION
**Pull request by ghost**
This is the first thing xeno's losing.

Why? Well, it makes already dangerous mobs even more dangerous and hard to kill for basically nothing, and it lets them smash rwalls, et cetera. You do NOT want to see wht happens when you make a Mi-Go the size of a tank that hits twice as hard as one. 

After this, i'm gonna see what I can do about limiting the number of actile hostile mobs, removing magicarp from xenobiology, and nerfing the bluespace core regenerative extract so that you can't use it to teleport megafauna to the station anymore.

:cl:  
rscdel: Removes the wombarian fugu from xenobiology. You know why.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
You can take your downvote and shove it unless you have a reason for it beyond 'but why nerf'. Like, if you can give me a genuine, honest reason it should stay, or an alternative, i'll do it.

**Comment by Bibby0110** [comment]
> You can take your downvote and shove it unless you have a reason for it beyond 'but why nerf'. Like, if you can give me a genuine, honest reason it should stay, or an alternative, i'll do it.

:)

**Comment by ghost** [comment]
A.maxHealth = 1.5
        A.health = min(A.maxHealth,A.health1.5)
        A.melee_damage_lower = max((A.melee_damage_lower * 2), 10)
        A.melee_damage_upper = max((A.melee_damage_upper * 2), 10)

just to clarify what the wombarian fugu gland does

take, for instance the giant spider

200 health

20 damage max

now it does 30 damage, has 300 health and can smash rwalls

this is producable effectively indefinitely-every xeno mob made can be made to hit like a truck and have massive amounts of health and break rwalls in one hit

it is, in the hands of a competent xenobiologist, a shuttle call reason in its own right

**Comment by ghost** [comment]
@MonsWTF 

If you had a better idea-which you seem to, going by discord logs that I got sent-why the hell didn't you just say that? Instead you just downvote and walk off wordlessly. Fuck off with the entitled elitism of 'well that makes too much sense'-nobody suggested it.

Fucking speak. Use your words, twat.

**Review by jcatjmeow — APPROVED** [review]
Fugu is literally cancer

**Comment by boodaliboo** [comment]
needed

**Comment by Reed0506** [comment]
bruh moment

**Pull request closed without merging**
