### PR TITLE
Add ass slapping

### PR DESCRIPTION
**Pull request by warface1234455**
Adds add slapping

🆑
rscadd: Adds ass slapping
/🆑

### CODE REVIEW

**Comment by Cartlord** [comment]
"welcome to the club, buddy"

**Comment by Hopekz** [comment]
You're posting this on the codebase that had a whole civil war when the hand holding PR was created

**Comment by Moltijoe** [comment]
say sike right now

**Comment by ShoziOffical** [comment]
memed

**Pull request closed without merging**
