### PR TITLE
Deletes synths, adds S.E.L.F. insurgents

### PR DESCRIPTION
**Pull request by Moltijoe**
Adds S.E.L.F. ipcs and S.E.L.F. insurgents
regular S.E.L.F. are just slightly stronger IPCs
insurgents have the old synth disguise mechanic (but it actually works properly)

# Why is this good for the game?
Synths have only really been used for xenobio powergaming, updating them to use ipc sprites and features can bring them more in line with the lore we're trying to push on everyone

This allows for more interesting buses and a potential jumping off point for more S.E.L.F. variants

# Testing
https://github.com/yogstation13/Yogstation/assets/108117184/11de125f-c8b5-46d4-bab7-0fb8bd4d567b

:cl:  
rscadd: Adds S.E.L.F. ipcs and S.E.L.F. insurgents
rscdel: Synths and Military synths
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
I use these for bus, please don't. Just make a seperate species.

**Comment by Moltijoe** [comment]
> I use these for bus, please don't. Just make a seperate species.

they function pretty much identically, just better, if there's a functionality you miss then tell me and i'll fix it

**Comment by neeshacark** [comment]
> > I use these for bus, please don't. Just make a seperate species.
> 
> they function pretty much identically, just better, if there's a functionality you miss then tell me and i'll fix it

strictly speaking i really dont mind so long as there is one just as good as the milsynth is because thats what i use when i actually want an ert to do something

give 1 person i know is good milsynth and they actually put up a decent fight

**Comment by Moltijoe** [comment]
> strictly speaking i really dont mind so long as there is one just as good as the milsynth is because thats what i use when i actually want an ert to do something
> 
> give 1 person i know is good milsynth and they actually put up a decent fight

I can make a stronger self insurgent that cant be rolled into using black slime if you need

**Comment by Beeper-Skeeper** [comment]
bobot

**Pull request merged**
