### PR TITLE
Detective gets a pet

### PR DESCRIPTION
**Pull request by Hopekz**
Introducing Detective Coffee.
He's going to help you out by keeping you company while you crack the toughest cases.

image

Picture of Detective Coffee hanging out with Officer Kreb
image

#### Changelog

:cl:  
rscadd: Detective has a pet! Say hello to Detective Coffee!
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
bro make it something that isnt already a pet we don't need two crabs

**Comment by Moja10** [comment]
I think the trend of every single person on the station having a pet is a dumb trend, especially since the new pet additions to the game are basically ignored and uncared for.

**Comment by Marmio64** [comment]
i'd like it if only heads of staff got pets, nobody even cares for any of the pets anyhow except Ian. No more pets.

**Comment by HomocidlePancakes** [comment]
Give him a rat that only he can pick up and store in his pockets.

**Comment by alexkar598** [comment]
Usually, each department has a single pet pened by the head of staff, security already has two, they domt need a third one

**Comment by Hopekz** [comment]
What are you guys even talking about there are lots of non head pets. We have the Janitor, Chef, public garden, perma even constant maintenance spawns like birdboat. 
Even departments get their own pets. Sci gets a penguin, cargo gets a fox. 

Also FYI this isn't a code PR this is a creative direction PR so I'll let our creative lead make the final choice on whether or not non heads can continue to have pets

**Comment by boodaliboo** [comment]
WE A;.READY CRAB BAD

**Comment by Marmio64** [comment]
> What are you guys even talking about there are lots of non head pets. We have the Janitor, Chef, public garden, perma even constant maintenance spawns like birdboat.
> Even departments get their own pets. Sci gets a penguin, cargo gets a fox.
> 
> Also FYI this isn't a code PR this is a creative direction PR so I'll let our creative lead make the final choice on whether or not non heads can continue to have pets

Yeah, I don't like that there's so many fucking pets. Science's Anadear penguin is fine though because the RD's 'pet' is lamar, who stays locked up in a display case. Perma is also fine cause it's just a rat who keeps the prisoners company. The chef's 'pet' is also not even his pet, they get eaten unless it's a cow, and then it's kept around for its milk or it is also eaten. Janitor, public garden, and maybe cargo fox are un needed. QM is basically /almost/ a head of staff so autumn is basically his pet, but janitor doesn't need its stupid lizard, nobody even notices it is there. Birdboat is meh, its just taken out and dragged around so it can throw up all over.

**Comment by Tipy1802** [comment]
Maybe give the det a dog or an owl, crab seems odd and it's already in use. I know that HoP already has a dog but the HoS (I think) also has a carb and a dog fits a dective more imo. A wolf would also be an interesting choice. 

Maybe Det's pet could also have a use unlike most pets. It could smell contraband or maybe something to that one mutation that lets you track things by smell

**Comment by Oakboscage** [comment]
Mane not another damn crab

**Comment by Moja10** [comment]
The additional pets besides the Heads' pets and the  lizard that spawns in Janitor's office were all additions by Fluffe, and I didn't support it then, so I again, wouldn't support this either.

**Comment by JamieD1** [comment]
Perry the platypus or bust. Dont forget his fedora.

**Comment by Ktlwjec1** [comment]
I'm gonna close this since Ident isn't touching it, just based on the majority of comments+half the votes being negative. Can I get an F in chat for detective crab?

F

**Comment by Hopekz** [comment]
detective crab died before they were born

**Comment by MegaEmpirical** [comment]
You monsters!

**Pull request closed without merging**
