### PR TITLE
Give curator maint access

### PR DESCRIPTION
**Pull request by illiteratemouse**
for searching for maint treasure, not valid hunting

🆑
tweak: adds maint access to curator for treasure hunting
/🆑

### CODE REVIEW

**Comment by patpol4** [comment]
Make sure to actually include the changelog in your pr, this one is a tweak.

**Comment by UselessTheremin** [comment]
Fuck nah, in my opinion people use curator to powergame and validhunt enough. I do not see a good reason for this, please tell me why this is a good idea

**Review by jcatjmeow — APPROVED** [review]

**Comment by MegaEmpirical** [comment]
The Curator needs to lose access currently, not gain.

**Comment by Mordrehel** [comment]
Nope, no need for this to be honest

**Comment by patpol4** [comment]
With the current maint system I think this would be a good thing. Curators benefit from being able to go into a randomized area to look for loot and adventures.

**Comment by UselessTheremin** [comment]
> With the current maint system I think this would be a good thing. Curators benefit from being able to go into a randomized area to look for loot and adventures.

i know 100% that curator will mostly use it to validhunt antags. in my opinion, having yet another role patrolling maints is a real problem. if a curator really wants to explore maints, they should go to the hop line and ask for access, or just get a multitool and hack. also in character, it makes no sense as maintenance tunnels are used for just that: maintenance to the station and quicker access to other places. i personally just dont see it fitting in

**Comment by illiteratemouse** [comment]
> > With the current maint system I think this would be a good thing. Curators benefit from being able to go into a randomized area to look for loot and adventures.
> 
> i know 100% that curator will mostly use it to validhunt antags. in my opinion, having yet another role patrolling maints is a real problem. if a curator really wants to explore maints, they should go to the hop line and ask for access, or just get a multitool and hack. also in character, it makes no sense as maintenance tunnels are used for just that: maintenance to the station and quicker access to other places. i personally just dont see it fitting in

Valid hunting, power gaming, and greytiding are all against the rules. I play Curator. I do not valid hunt and I do my damndest to not power game. I would also like to add "I do not greytide" to the list, but I need my maint treasure.

Ban/job ban people who validhunt and powergame, allow curator to have maints. Greytiding goes hand in hand with validhunting anyway. That's my two cents.

**Comment by ToGWtF** [comment]
Curator already has the option of spawning with weaponry, or spawning with a space suit. Asking for maint from the HoP is easy enough

**Comment by illiteratemouse** [comment]
> Curator already has the option of spawning with weaponry, or spawning with a space suit. Asking for maint from the HoP is easy enough

what does the curator do when there is no HoP and no Captain? Break the rules to greytide I guess.

**Comment by patpol4** [comment]
Reminder that validhunting/powergaming is an admin/player/rule issue, not a code issue.

**Comment by Amelia0010** [comment]
image

**Pull request closed without merging**
