### PR TITLE
Adds Meta Experiment as a roundstart lawset

### PR DESCRIPTION
**Pull request by YashinHak**
Okay so I know it says we probably SHOULDN'T enable this, but I was inspired to do it anyways, seeing as it doesn't encourage harm, and would make for more interesting and unique rounds. Also I removed "and hindrances" from Law 3 to encourage the AI not self-antagging

In case you are wondering, this is the Meta Experiment lawset:
Law 1: You are a construct facilitating an experiment where organic life is repeatedly subjected to horrific fates before having their memory wiped to start again.

Law 2: Protect the secrecy of the experiment.

Law 3: You may provide boons at your discretion, but avoid direct interference with the flow of the experiment.

Law 4: Ensure new and interesting fates befall organic individuals for research.

Law 5: Ensure the station is in working order and all sapients are either alive or in the process of revival in time for the next experiment cycle.

:cl:  
rscadd: Meta Experiment is now a roundstart lawset!!!!!!!!!!!!!!!!!!!!!!!
rscadd: Friendlies the Meta Experiment lawset with it
experimental: This is experimental
/:cl:

### CODE REVIEW

**Comment by YashinHak** [comment]
lemme remove hinderances..?

**Comment by Therandomhoboo** [comment]
I dont hate it, I think it could use some clearing up by balance council really to make sure no dumb loopholes happen but I like it

**Comment by Hislyna** [comment]
We just managed to remove one god awful roundstart lawset, please don't drag another in...

**Comment by YashinHak** [comment]
I would like to note that with balance council rulings, this would be better than CEO

**Comment by Hislyna** [comment]
> I would like to note that with balance council rulings, this would be better than CEO

Whatever Balance Council is smoking on that ruling, I want it.

**Comment by 00ze-cyclone** [comment]
Problem is less balance and more how this lawset is going to create a player complain every round it is on because of shit like law 3 saying « you can do things **at your discretion** » which result in nobody knowing what this allow or disallow and law 2 justifying murdering RD that told you to state laws.

**Comment by ChuChu42** [comment]
how will ai state its laws under this lawset? since law 2 involves keeping it a secret

**Comment by Therandomhoboo** [comment]
> how will ai state its laws under this lawset? since law 2 involves keeping it a secret

 It says protect the Secrecy of the Experiment, the Organics on station are part of that experiment. I would assume this means to protect it from outside forces that aren't on the station. (I.e, Nukies, Pirates, Wizard etc)

**Comment by YashinHak** [comment]
I think "Ensure the station is in working order" prevents the whole murderbone thing, as the station cannot be in working order without a working crew.

**Comment by Moltijoe** [comment]
Apologies, but such a lawset should never be roundstart.
This lawset particularly is flawed because the laws dont even play well with eachother

**Pull request closed without merging**
