### PR TITLE
db shotgun

### PR DESCRIPTION
**Pull request by Potototatoh**
### Intent of your Pull Request
newer double barrel sprites

Screenshot (714)

@coders pls off ur ass so i can usw the broken open state that i have also
edit: changed bottom section of thw shotguns dont referr to the image refer to the dmi
#### Changelog

:cl:   
imageadd: replace db shotgun sprite 
imagedel: replaces db shotgun sprite  e
/:cl:

### CODE REVIEW

**Comment by overlord12345** [comment]
these sprites are nice very good change

**Comment by Bibby0110** [comment]
Please, learn to spell

**Comment by Potototatoh** [comment]
no

**Comment by Bibby0110** [comment]
You have to fix the changelog errors.

**Comment by Potototatoh** [comment]
why

**Comment by Bibby0110** [comment]
It's know as "Basic Quality Control"

**Comment by Potototatoh** [comment]
who is basic quality control

**Review by nesisknesis — COMMENTED** [review]
the wood below the barrel wraps around the right barrel which makes the perspective look a little bit off.

image
as seen it doesnt wrap around
if you lower the whole shaft by 1 pixel itll probably fix it and allow you add an outline to the left barrel

**Comment by Potototatoh** [comment]
i get all those arguements excluding the lefft barrel gtting a outline because then it'd look like this
Screenshot (716)

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
