### PR TITLE
Railing resprite

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Adds new sprites made by Ident for rails, and uses a hacky solution to get the perspective to work. Also moves the sprite out of fluff.dmi, items_and_weapons.dmi's less popular relative. Is tested, does work.
image

# Wiki Documentation

Map images will need to be updated. 

# Changelog

:cl:  Identification
imageadd: added new icons for railings
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by bruhlookatthisdood** [comment]
make corner railings craftable while your at it please i beg you ):<
or do what jamie said below

**Comment by JamieD1** [comment]
Can we not make corners seamlessly join?

**Comment by JamieD1** [comment]
Hows it going?

**Comment by nmajask** [comment]
> Hows it going?

The images are old, it _should_ join seamlessly already but I will need to test it to confirm.

**Review by nesisknesis — APPROVED** [review]

**Comment by nmajask** [comment]
> > Hows it going?
> 
> The images are old, it _should_ join seamlessly already but I will need to test it to confirm.

Fixed
image



> make corner railings craftable while your at it please i beg you ):< or do what jamie said below

Added

**Review by JamieD1 — APPROVED** [review]
Epic

**Pull request merged**
