### PR TITLE
Removes geysers from lavaland

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

We don't have plumbing, have no way to get a plunger, and any questions I had about putting chemicals in them were met with an "i dunno", so now we don't have them again.

# Changelog

:cl:  
rscdel: No more useless geysers
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Improve not remove

**Comment by ToasterBiome** [comment]
> Improve not remove

Shut up

**Comment by LoliconSlayer** [comment]
> Improve not remove

Improve it yourself or stfu

**Comment by ghost** [comment]
> Shut up

Cry about it

**Comment by ghost** [comment]
> Improve it yourself or stfu

I had already made a PR that changes geysers to be usefull instead of just removing them

**Pull request closed without merging**
