### PR TITLE
Yogsmeta escape has proper airlocks

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Yogsmeta has fucky airlocks where if 2 people try to go out the airlock at once all of escape is depressurized, this aims to fix that

**Also** The decal has been changed from stripes/boxes encompassing the whole room to just by the airlocks

Also fixed the shocked windows in the checkpoint

### OLD
image

### NEW
image

#### Changelog

:cl:  
rscadd: Yogsmeta has proper escape airlocks
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
trying to debug some funkyness in this, they dont act like how yogstation does

**Comment by patpol4** [comment]
What's up with the decals?

**Comment by redmoogle** [comment]
If you mean why I changed them, it just looked strange like one giant box so I tried to tune it to be somewhat similar to yogstation escape decals

**Comment by patpol4** [comment]
Idk i don't like it it looks barebones now, maybe add some corner decals instead if you want change?

**Comment by redmoogle** [comment]
yeah Ill take another comb for decorations but i didnt find anything that suited escape

**Comment by redmoogle** [comment]
Imma be really sad if mapdiffs is displaying this correctly

**Comment by redmoogle** [comment]
> 
> 
> Idk i don't like it it looks barebones now, maybe add some corner decals instead if you want change?

Take a look at this new iteration of decorations

also w h a t did yogstation13/map just get ownership or something

**Review by patpol4 — APPROVED** [review]
Yes now it's better

**Pull request merged**
