### PR TITLE
chance to slip on blood

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

1% chance to slip for 1 second on blood when running over it if you are not walking

janitor mechanics are good for the janitor role

will be funny in combat

# Changelog

:cl:  
tweak: Blood is now wet and slippery
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
This is not a good idea. Not even close

**Comment by cuackles** [comment]
does this work with polys acid blood ?

**Comment by patpol4** [comment]
This is a great idea

**Comment by ynot01** [comment]
> does this work with polys acid blood ?

yes

**Comment by ynot01** [comment]
> This is not a good idea. Not even close

janitor mechanics

**Comment by Bibby0110** [comment]
> This is a great idea

This is not a good idea

**Comment by Bibby0110** [comment]
> 

This isn't the way to do that.
When everything is chaos there will be blood everywhere and most definitely no janitor to clean it up.
The moment anything becomes the least bit chaotic it's going to be hell-ish moving around.

**Comment by Bibby0110** [comment]
oh no i slipped in blood

**Comment by maxion12345** [comment]
clown making the entire halls bloody for slips

**Comment by ChesterTheCheesy** [comment]
does this slip flying mobs and people with noslips shoes?

why not use slippery component?

**Comment by ynot01** [comment]
> does this slip flying mobs and people with noslips shoes?

untested

> why not use slippery component?

prob(1)

**Comment by Junkyshell** [comment]
insert super smash bros brawl reference

**Comment by ToasterBiome** [comment]
> > does this slip flying mobs and people with noslips shoes?
> 
> untested
> 
> > why not use slippery component?
> 
> prob(1)

atomize slippery to take in a random chance to slip

**Comment by JamieD1** [comment]
@ynot01 Make medical tiles non slippable on blood, make it 100% slip chance on pools of blood and not footprints.

**Comment by Moja10** [comment]
Great idea

**Comment by Bibby0110** [comment]
> Great idea

Not great idea

**Comment by Smudged** [comment]
>This isn't the way to do that.
When everything is chaos there will be blood everywhere and most definitely no janitor to clean it up.

This sounds like so much fun, and would incentivize people to sometimes *walk* over blood.

ALSO, because it's a 1% chance this won't affect you more than you think it will.

>@ynot01 Make medical tiles non slippable on blood, make it 100% slip chance on pools of blood and not footprints.

no, make it so medbay is still slippable on 1%, this makes it so doctors who aren't already spraying down medbay of blood has a chance to slip which is fantastic.

**Comment by bruhlookatthisdood** [comment]
>This sounds like so much fun, and would incentivize people to sometimes _walk_ over blood

maybe we need a mood debuff for having soggy shoes (bloody feet/shoes)
i also kinda like this, makes janitor more of a necessity

**Comment by Runian** [comment]
Most people don't use mood anyways. But if mood reduction is gonna be included, mood users will just countering all of this by getting light step which prevents their shoes from being bloodied in the first place.

This gives more reason to beat up people who spam butcher corgis (because science strange tech) and throw those blood tomatos around. Test merge?

**Comment by ynot01** [comment]
stale + bad + lost motivation

**Comment by bruhlookatthisdood** [comment]
he figured out his own mistakes

**Pull request closed without merging**
