### PR TITLE
fuck drones

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

1. drones cannot hit anyone at all ever, thanks to pacifist
2. drones cannot fire any harmful guns, due to pacifist
3. drones can't fire any other guns, due to noguns

thank me late.r

#### Changelog

:cl:  
fix: drones are now further towards a state where I might consider making them somewhat not as horrible to build
/:cl:

### CODE REVIEW

**Comment by GenericDM** [comment]
this isnt a bad idea tbh

**Comment by tsaoToast** [comment]
Drones are already virtually worthless to build in the protolathe, it's just everyone forgets to.

Maybe this means re-adding the drone dispenser?

**Comment by fluffe9911** [comment]
What about those admeme syndie drones that get spawned sometimes

**Comment by Amelia0010** [comment]
fuck them.

**Comment by Ktlwjec** [comment]
> 
> 
> What about those admeme syndie drones that get spawned sometimes

once

**Comment by Altoids1** [comment]
> What about those admeme syndie drones that get spawned sometimes

I don't think anyone has to worry about that until I get +SPAWN again.

**Comment by tsaoToast** [comment]
Shit and what about people who are wabbajack'd in to drones.

**Comment by Amelia0010** [comment]
>Shit and what about people who are wabbajack'd in to drones
image

**Pull request merged**
