### PR TITLE
inhands sprots that arent unbearable to look at and then some

### PR DESCRIPTION
**Pull request by Potototatoh**
### yes

items such as the claymore were made more bearable to look at and then some other stuff
yell at me and more might happe
Screenshot (749)

#### Changelog

:cl:  
tweak: some swords are nows facing down rather than across spessman
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
I think it should go up instead of down.

**Comment by Potototatoh** [comment]
that would look doofy

**Comment by monster860** [comment]
isnt that what like eswords and shit do

**Comment by Potototatoh** [comment]
what happen whnen uo point the handle of the esword down

**Comment by Ktlwjec1** [comment]
imageadd: replaced stuff
imagedel: repalced stuff

^ remove these or I'll edit them out for you anyway. Useless, give no actual information.

**Comment by alexkar598** [comment]
Ugly

**Comment by Potototatoh** [comment]
ou are :)

**Comment by Ktlwjec1** [comment]
I just fucking did the changelogs myself since you're ignoring me.

**Comment by Potototatoh** [comment]
ii was about to my sweet child

**Comment by alexkar598** [comment]
Ok fine ident, I think its ugly because the sword is too low, from a realism point, you probably cant kill shit if you hold a sword like that and from a gameplay point, i think the sword being up and more centered makes it mroe obvious the person has a sword

**Comment by Potototatoh** [comment]
holding it like that makes it more visible from all sides literally
its held outwar not ontop of ur chest like a retard

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Grammar issues in changelog

**Comment by overlord12345** [comment]
Who holds a sword like that

**Comment by Potototatoh** [comment]
image

**Comment by deathslayer2481** [comment]
As someone who has used a sword, you generally hold it low when you wanna hit someone’s legs or to do specific stances.

**Comment by deathslayer2481** [comment]
Saying it’s incorrect to is 100% wrong. It’s one of the like, five most common stances.

**Comment by deathslayer2481** [comment]
https://i.pinimg.com/originals/15/af/66/15af66e1a3fa3b458fced61203773b02.jpg

**Comment by alexkar598** [comment]
Not a single one of those stances has the sword held parallel to the user facing downwards

**Comment by deathslayer2481** [comment]
So its not because it’s low, its because it’s to the side??

**Comment by deathslayer2481** [comment]
Porta Di Ferro.
http://www.chivalrynow.net/images/sword/tutta.jpg

**Comment by deathslayer2481** [comment]
Wake the fuck up Samurai
We got a station to burn

**Pull request merged**
