### PR TITLE
Demodularizes Uplinks

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Documents all of the uplink variables
Unfucks the code funky code from the modularized section

and well
Reintegrates it back into the main folder

### CODE REVIEW

**Comment by Cartlord** [comment]
i thought we were back to trying to modularize shit

**Comment by redmoogle** [comment]
> i thought we were back to trying to modularize shit

Mfw the changes i made dont work because it was overriden in another folder

**Review by Altoids1 — CHANGES_REQUESTED** [review]
As the person who had to endure wasting hundreds of hours on TG merge conflicts caused by unmodular code, and in the name of what remains of Jamie's sanity, I strongly recommend against this PR.

Making the decision to demodularize is up to the Head Devs and Allah.

**Comment by redmoogle** [comment]
> As the person who had to endure wasting hundreds of hours on TG merge conflicts caused by unmodular code, and in the name of what remains of Jamie's sanity, I strongly recommend against this PR.

So were going to keep really bad changes? Such as half the weird overrides above. Or the 3 line changes you will never find

**Comment by redmoogle** [comment]
going to just remove the categories because thats whats bugging me the most

**Comment by redmoogle** [comment]
uh oh fucked up the branch

**Pull request closed without merging**
