### PR TITLE
Adds chameleon chest rig

### PR DESCRIPTION
**Pull request by ynot01**
# Github documenting your Pull Request

chest rig useless 
no one buy
i make chameleon
useful for storage without getting caught for valid chest rig
people now buy(?)

can only disguise as other storage belts
effectively a box for your waist for 1 tc
worth? no
but its better now at least

# Wiki Documentation

chest rig is now chameleon

# Changelog

:cl:  
rscadd: Added the Chameleon Chest Rig and added it to the syndicate uplink
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
should just add it to the cham kit and extend the price by 1tc

**Comment by ynot01** [comment]
> should just add it to the cham kit and extend the price by 1tc

this would be a nerf to cham kit

**Comment by maxion12345** [comment]
> > should just add it to the cham kit and extend the price by 1tc
> 
> this would be a nerf to cham kit

how if anything it'll be a buff because cham-kits would come with a toolbelt
also it'll let you just have an all-in-one kit for all the jobs

**Comment by ynot01** [comment]
> > > should just add it to the cham kit and extend the price by 1tc
> > 
> > 
> > this would be a nerf to cham kit
> 
> how if anything it'll be a buff because cham-kits would come with a toolbelt
> also it'll let you just have an all-in-one kit for all the jobs

giving this to cham kit would be a pure buff
upping cham kit's price by 1TC for this waist box is a nerf, keep it separate, let it be an option

**Comment by Drowzyleaf** [comment]
note that there's already a chameleon tool belt in the Ninja syndi-kit bundle if you want to replace either with the other

**Comment by ynot01** [comment]
> note that there's already a chameleon tool belt in the Ninja syndi-kit bundle if you want to replace either with the other

slipped me

**Comment by ynot01** [comment]
fixed

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
