### PR TITLE
Spell icons redone part 1

### PR DESCRIPTION
**Pull request by Hopekz**
More to come
**EDIT: Incorporated borders into the icons.**

**Left to right in the screenshot:**
Fireball, Barnyard, arcane barrage and magic missiles
image

**All icons changed in this PR:**
image
image

#### Changelog

:cl:  
rscadd: New spell icons for Fireball, Magic Missile, Barnyard, Bolt action rifles, Arcane barrage, time stop, sacred flame, Skeleton, Mutate, Lightning and Mime spell.
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
GOOD

**Comment by HomocidlePancakes** [comment]
All of these are dank except for the mosin one. Looks more like a canon than a gun barrel.

**Review by nesisknesis — COMMENTED** [review]
could maybe do with some sort of outline

spells come with a background applied to them via code, maybe you could work with that

**Comment by Hopekz** [comment]
@Idinuum 
Modified; All icons now work with the border.

image

**Comment by Darkstick** [comment]
Shouldn't arcane barrage be purple? The spell shoots out small purple fire balls after all. Even then, these icons look amazing, they remind me of MMORPG spell icons

**Comment by Hopekz** [comment]
> Shouldn't arcane barrage be purple? The spell shoots out small purple fire balls after all. Even then, these icons look amazing, they remind me of MMORPG spell icons

RE: the arcane barrage I just copy and pasted the hand sprite with its exact colors and then whipped up a blurry fiery like background to match the others.
So if that hand sprite isn't purple it was never purple

**Pull request merged**
