### PR TITLE
The great AI blindspot fixining

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# Document the changes in your pull request

So, i was playing AI one time, right?
Then I saw a blind spot, and it annoyed me.
Then i saw more. And more. And more!
So, I fixed it

# Why is this good for the game?
Blindspots for the ai are good, but not in places that are supposed to be visible!
Maints can be blind to AI thats fine, but science and heads of staff offices? No

# Testing
i can see 

# Changelog

:cl:  
bugfix: fixed a lot of ai blind spots
/:cl:

### CODE REVIEW

**Comment by Beeper-Skeeper** [comment]
holy based

**Comment by azzzertyy** [comment]
Changes look good to me, removes unnecessary cameras while doing so.

**Comment by Aquizit** [comment]
it do be having conflicts

**Comment by bruhlookatthisdood** [comment]
> it do be having conflicts



> it do be having conflicts

nuh uh

**Review by Aquizit — CHANGES_REQUESTED** [review]
Bar Southwest and Theater camera names are swapped. Other than that looks good.

**Review by Aquizit — APPROVED** [review]

**Comment by MommaDragon** [comment]
Swiss Cheese Filler.

**Pull request merged**
