### PR TITLE
Adds a new purrbation option for donors: fox

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Adds fox parts, drops from fox mobs, and roundstart fox human variant for donors accessible from the purrbation toggle

# Spriting
image

# Wiki Documentation

Fox human variant race, nothing particularly special about them similarly to cat human variant

# Changelog

:cl:  theos for code, orca for sprites
rscadd: adds fox tails and ears
rscadd: fox purrbation toggle for donors
imageadd: fox parts
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
wtf?

**Comment by Chubbygummibear** [comment]
furry

**Comment by LazennG** [comment]
holy fucking real

**Comment by Simplehorror** [comment]
go play paradise pls

**Comment by SomeguyManperson** [comment]
> go play paradise pls

sorry that im doing your job better than u

**Comment by KillerOrcaCora** [comment]
and so it begins I expect a good show. 
download

**Comment by 00ze-cyclone** [comment]
I mean why the fuck not, we already have fucking catgirls for those who pay so let’s just go all the way.
Go big or go home.

**Comment by Moltijoe** [comment]
Always love more species to be racist towards

**Comment by Marmio64** [comment]
> I mean why the fuck not, we already have fucking catgirls for those who pay so let’s just go all the way. Go big or go home.

Yup, let's get vore in here too while we're at it.

**Comment by cuackles** [comment]
Can they wag ?

**Comment by SomeguyManperson** [comment]
> Can they wag ?

Mmi didnt get animated wagging sprites so no regrettably

**Comment by KillerOrcaCora** [comment]
I’ll animate it if you code it will just take me a second to get it right

**Comment by MajManatee** [comment]
he wasnt joking... wow...
this really is the darkest timeline

**Comment by cuackles** [comment]
can we get a side view ?

**Comment by Sniblet** [comment]
it was real
where are their unique audible emotes

**Comment by CMOisLing** [comment]
image0 - 2021-01-22T210547 217

**Comment by Potototatoh** [comment]
gross

**Comment by Hislyna** [comment]
Let the Feline Fox wars commence.

**Comment by JamieD1** [comment]
Maybe in the future
Not right now, other shit going on.

**Comment by Bibby0110** [comment]
Close for no reason

**Comment by 00ze-cyclone** [comment]
The future? Let all hell break loose NOW!

**Comment by Simplehorror** [comment]
if this gets merged i'll be adding my OC race

**Comment by Burger1998** [comment]
> > I mean why the fuck not, we already have fucking catgirls for those who pay so let’s just go all the way. Go big or go home.
> 
> Yup, let's get vore in here too while we're at it.

already exists

**Comment by KillerOrcaCora** [comment]
I would like to see a better reason then whatever the hell above is

**Comment by CMOisLing** [comment]
Anime has destroyed an entire generation of people

**Comment by Maia-J** [comment]
This is significantly better than lizards

**Comment by 00ze-cyclone** [comment]
> Anime has destroyed an entire generation of people

Time to merge this an finish the job

**Comment by Bibby0110** [comment]
Bad orca

**Comment by KillerOrcaCora** [comment]
GRRRR WOLF WOLF RAWR WOLF WOOF WOOF WONFOOW FONWOIF GRRR WOF WOOF WOOF YIP YIP YIP

**Comment by CMOisLing** [comment]
live_anomalocaris_reaction

**Comment by KillerOrcaCora** [comment]
https://static.wikia.nocookie.net/dimensional-heroes/images/d/d1/Momiji.jpg/revision/latest/scale-to-width-down/600?cb=20210618142740

**Comment by Moja10** [comment]
Better than medbay lizards.

**Comment by Simplehorror** [comment]
stop opening this

**Comment by monster860** [comment]
We need to ensure maximum degeneracy within our codebase.

**Comment by Moltijoe** [comment]
fight fight fight

**Comment by JamieD1** [comment]
Do it again you are losing your perms. Cut it out. Last fucking warning.

**Comment by KillerOrcaCora** [comment]
Fuck you I quit

**Comment by JamieD1** [comment]
Im not being held hostage by you because I wont merge a PR you want Orca.

**Comment by Simplehorror** [comment]
it's ok, I will be the new art director

**Comment by JamieD1** [comment]
> it's ok, I will be the new art director

Too soon.

**Pull request closed without merging**
