### PR TITLE
Uranium/iron now has a maxcap of 200

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Uranium/Iron now has a maxcap of 200, which is 16/28 heavy/light
#### Changelog

:cl:  
tweak: Uranium/Iron mixes have been nerfed, so 200u is now the limit
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
You're welcome

**Comment by ShadowDeath6** [comment]
context?

**Comment by Amelia0010** [comment]
`01:17:23.31    GAME    EMP with size (75, 128) in area Toxins Test Area`

is the context

**Comment by alexkar598** [comment]
Not weak enough for a 5 steps grenade

**Comment by oklews** [comment]
Fun fact: if you are a chemist, you could EMP literally the entire station (save the top half of perma) if you buy C4 and manually make a bomb then fill it up with iron and uranium.

This PR is needed

**Pull request merged**
