### PR TITLE
[PORT] Sus hud

### PR DESCRIPTION
**Pull request by warface1234455**
# About pr

- ports https://github.com/tgstation/tgstation/pull/65339

Provides a way to keep track of your suspects without having beepsky body them. Keeps assistants from instantly hating sec.. more than usual.

I hope there is some instant bwoinks the moment the HoS tells the warden to set the clown to 'Sussy'
# Document the changes in your pull request
Adds "Suspected" to available sec record tags
image

# Wiki Documentation
Added suspected hud indicator for seccie

# Changelog

:cl:  [AtoriBirb](https://github.com/AtoriBirb) ported by warface1234455
rscadd: Added suspected hud indicator, set people to suspected if they are sus
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
well isnt this a bit... sussy

**Comment by TheRyeGuyWhoWillNowDie** [comment]
📛

**Comment by ToasterBiome** [comment]
I like it but I will still set assistants to arrest

**Comment by ghost** [comment]
Amog

**Comment by JamieD1** [comment]
Is this a replacement for search or additional to it.

**Comment by ShoziOffical** [comment]
> Is this a replacement for search or additional to it.

Probally additional

**Review by cuackles — APPROVED** [review]

**Pull request merged**
