### PR TITLE
removes donksoft from asteroidstation

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
image

# Changelog
:cl:  
mapping: Removed the donksoft vendors from asteroidstation
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
I don't like this

**Comment by azzzertyy** [comment]
> I don't like this

giving people access to a machine which gives them guns that can shoot actual lethal foam forces roundstart was a bad idea

**Comment by Moja10** [comment]
Map diversity is cool

**Comment by ChuChu42** [comment]
ITS NERF OR NOTHING
ITS NERF OR NOTHING
ITS NERF OR NOTHING
ITS NERF OR NOTHING

**Comment by azzzertyy** [comment]
> Map diversity is cool

its map diversity like this that makes no one like these maps

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
can you make a hugbox one instead

**Comment by azzzertyy** [comment]
> can you make a hugbox one instead

define hugbox

**Comment by ToasterBiome** [comment]
> > can you make a hugbox one instead
> 
> 
> 
> define hugbox

one that's still fun without all the cringe stuff

**Comment by SomeguyManperson** [comment]
> > > can you make a hugbox one instead
> > 
> > 
> > define hugbox
> 
> one that's still fun without all the cringe stuff

That would mean no guns, since foam force period means riot darts means oops :3

**Comment by azzzertyy** [comment]
> one that's still fun without all the cringe stuff

that will come in my next pr (why are there space manatees)

**Comment by ToasterBiome** [comment]
> > one that's still fun without all the cringe stuff
> 
> that will come in my next pr (why are there space manatees)

menacingmanatee is the creator of the map

**Comment by azzzertyy** [comment]
also not to mention, donksoft are all listed as contraband.

**Comment by MajManatee** [comment]
"Traitors can use it" is the lamest excuse ive ever heard

**Comment by azzzertyy** [comment]
> "Traitors can use it" is the lamest excuse ive ever heard

anyone with an autolathe can get riot darts

**Comment by azzzertyy** [comment]
/datum/design/riot_dart
	name = "Foam Riot Dart"
	id = "riot_dart"
	build_type = AUTOLATHE
	materials = list(/datum/material/iron = 1000) //Discount for making individually - no box = less metal!
	build_path = /obj/item/ammo_casing/reusable/foam_dart/riot
	category = list("hacked", "Security")

**Comment by MajManatee** [comment]
one week+ no activity and changes unaddressed. Reopen if work continutes

**Comment by azzzertyy** [comment]
> one week+ no activity and changes unaddressed. Reopen if work continutes

what?
what changes?
name a change requested.

**Pull request closed without merging**
