### PR TITLE
changes poppys chemicals from libital to bicardine to promote botanists actually using them

### PR DESCRIPTION
**Pull request by boodaliboo**
changes poppys chemicals from libital to bicardine to promote botanists actually using them
:cl:  

tweak: tchanges poppys chemicals from libital to bicardine to promote botanists actually using them

/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Hell yes opiate crisis in SS13

**Comment by VaelophisNyx** [comment]
mmmm, this feels....unbalanced

what if we did the barotrauma thing and made it morphine

**Comment by boodaliboo** [comment]
> mmmm, this feels....unbalanced
> 
> what if we did the barotrauma thing and made it morphine

i would honestly rather have it give like codeine that could resist damage slowdown slightly, ill pay someone 3$ to make that code

**Comment by 00ze-cyclone** [comment]
Libital heal 3 brute per tick while bicaridine is only 2, it also metabolize slower than bicaridine making it overall more effective. Botanists can get silibilin to cure the liver damage, negating the one relatively small downside of libital. That PR is making poppy less valuable instead of promoting its production.

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Respond to the above comment

**Comment by boodaliboo** [comment]
> Respond to the above comment

what about it i read it and still want bicardine

**Comment by Bibby0110** [comment]
Weak/non-existent reasoning.

**Pull request closed without merging**
