### PR TITLE
Makes the surrendering text more noticeable

### PR DESCRIPTION
**Pull request by Darkstick**
The surrender emote is currently useless. It being simple generic black text makes it very hard to notice, especially in the middle of combat, where you would want to use the emote. This PR simply makes that text huge and red so that it can be seen even when you're about to shoot some poor bloke in the face.
#### Changelog

:cl:  
tweak: added the "userdanger" class to the text that appears after using the surrender emote.
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
+1 good pr

**Comment by Codeatmos** [comment]
+1 very nice rp change i love very much
i can now spam chat with *surrender to instantly nullify comms thank you

**Comment by Hopekz** [comment]
This is how it looks in-game:
----
Bringing this image from our discord:
image

**Comment by HomocidlePancakes** [comment]
Time to get hulk and spam it

**Comment by Xoxeyos** [comment]
People are just going to spam this.

**Comment by yacabo** [comment]
The delay is too long to spam effectively

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Line endings,fix em

get a better git client too

**Comment by MegaEmpirical** [comment]
This might be nice as a button on the IC tab.

**Comment by Amelia0010** [comment]
If used in the middle of combat, this'll look like a combat message, since it uses the same span.

**Comment by MegaEmpirical** [comment]
Some kind of color change then? Yellow would work for dark mode.

**Comment by AsV9** [comment]
Please fix these line endings.

**Comment by alexkar598** [comment]
Been a week without sign of life from the author.

**Pull request closed without merging**
