### PR TITLE
Cyborg Cycling no longer tries to switch to the legendary 「fourth slot」

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

It make runtimes I unga bunga fix

### Why is this good for the game?

Fix runtime
Good ye

### CODE REVIEW

**Comment by patpol4** [comment]
Won't this make slot 3 unusable because it will instantly swap to slot 1

**Comment by redmoogle** [comment]
> Won't this make slot 3 unusable because it will instantly swap to slot 1

Ah mybad ill go fix it in a bit

**Comment by redmoogle** [comment]
theres some fuckery going on here that im going to investigate

**Comment by redmoogle** [comment]
Tested

**Comment by redmoogle** [comment]
will deal with this later. code is cursed

**Comment by patpol4** [comment]
oh god

**Pull request closed without merging**
