### PR TITLE
Fuck off Icebox

### PR DESCRIPTION
**Pull request by JamieD1**
Fuck off Icebox

#### Changelog

:cl:  
rscdel: Removed Icebox for now
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
are we not even gonna fucking attempt to fix it or are we just gonna kneejerk remove it

**Comment by Hopekz** [comment]
> are we not even gonna fucking attempt to fix it or are we just gonna kneejerk remove it

It's been broken for a long time I don't think sitting on it is going to fix it sadly.

**Comment by MrHorizons** [comment]
> are we not even gonna fucking attempt to fix it or are we just gonna kneejerk remove it

It doesn't look like it's being removed from the code, just the config.

**Comment by alexkar598** [comment]
If we are removing icebox, it needs to be done properly, not just removing it from the config.

**Pull request closed without merging**
