### PR TITLE
Hugboxes Changelings

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

lings is basically fleshy IAA at this point

#### Changelog

:cl:  
rscdel: Pheremone Receptors has been removed and absorb another ling is no longer an objective
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
this is not hot

**Comment by ynot01** [comment]
> this is not hot

its not i ded because i actually have ling disabled and thus cannot ded

**Comment by monster860** [comment]
your pr sucks, it wont compile properly. you have to prevent it from being chosen, not remove the objective, other wise it will error because the thing doesnt exist.

**Comment by ynot01** [comment]
> your pr sucks, it wont compile properly. you have to prevent it from being chosen, not remove the objective, other wise it will error because the thing doesnt exist.

please suggest a change that would fix this, i tried looking but could not see the mention of "pheremones" anywhere other than the 2 files i edited

**Comment by monster860** [comment]
search for /datum/objective/absorb_changeling

**Comment by ynot01** [comment]
> search for /datum/objective/absorb_changeling

aye i actually completely forgot about the 2nd half of my pr thanks for reminding me <3

**Comment by SomeguyManperson** [comment]
Also pretty sure the point for absorb another ling objectives is to make it so lings have even less reason to turn themselves into an unstoppable murderbone party to kill sec

**Comment by HomocidlePancakes** [comment]
MMMMM YES! THE GOOD OLD DAYS OF LING METAGANGS TAKING OVER THE STATION! HAHA GUYS, YOU THOUGHT FIGHTING A SOLO LING WAS FUN? WAIT UNTIL YOU FIGHT 4 AT ONCE THAT CAN INSTANTLY COMMUNICATE TELEPATHICALLY BECAUSE FUUUUUUUCK YOU! FUN, AMARITE?(no)

**Comment by ShadowDeath6** [comment]
retarded strawmen aside, I think this pr can be done right outside of just removing everything, ling vs ling interaction is ok but having it be forced by an objective is annoying. I’m permanently biased against double agent-esque modes though since it was so shitty to play

maybe make it so pheromone receptors are less effective under certain circumstances

I honestly wouldn’t be opposed to changing hivemind as well (maybe making it cost points to use or something) in order to avoid lings snowballing

**Comment by HomocidlePancakes** [comment]
>aving it be forced by an objective is annoying
I’m permanently biased

Did you just make a point and then instantly made it loose any value in the next sentence? Wow.

>maybe make it so pheromone receptors are less effective under certain circumstances

Elaborate. 

>I honestly wouldn’t be opposed to changing hivemind as well (maybe making it cost points to use or something) in order to avoid lings snowballing

Elaborate.

**Comment by ghost** [comment]
@HomocidlePancakes second point doesn't need much elaboration

'make changeling hivemind take points'

not a hard concept. instead of having :g  pre bought as lings do, make them have to evolve it

or, you know, just go full goon ling, that'd be better

**Comment by HomocidlePancakes** [comment]
If he gave it even a little thought then he would understand that it ends up in the same situation as the tot key, thats why I wanted him to explain further. He is pretty much proposing to remove it w/o realizing it.

**Comment by ynot01** [comment]
if i figure out how to code it im all for making hive link purchaseable

**Comment by Oakboscage** [comment]
Absorb another is a good objective, objectively.

**Comment by AsV9** [comment]
If you want to make the telepathic link thing purchasable that belongs in a different PR.

This on the other hand..

**Pull request closed without merging**
