### PR TITLE
[box] makes engineering door the right access

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

maint door was general maint access

# Changelog

:cl:  
mapping: engineering lobby door access fixed on boxstation
/:cl:

### CODE REVIEW

**Review by Aquizit — APPROVED** [review]

**Comment by iloveloopers** [comment]
image
good to see sec office in engineering is radproof

**Comment by Aquizit** [comment]
> image good to see sec office in engineering is radproof

That... what?

Pretty sure rad storms are /area/ based and that room didn't change areas... wtf

**Comment by Aquizit** [comment]
image
yeah it's not actually happening I dunno what you're looking at

**Comment by iloveloopers** [comment]
Probably just some visual glitch then

**Comment by ShoziOffical** [comment]
no more free access for assistants

**Pull request merged**
