### PR TITLE
Garbage day event

### PR DESCRIPTION
**Pull request by ThatLing**
What could go wrong?

:cl:  
rscadd: The garbage collection pipes have shrunk
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
no.

**Comment by ThatLing** [comment]
why not?

**Comment by Amelia0010** [comment]
Because having the garbage subsystem not fire is a very good way to kill everything that depends on things getting qdel'd

**Comment by ThatLing** [comment]
That's the point of this event, so you're okay with killing rand but not this?

**Comment by Amelia0010** [comment]
1. I didn't merge that PR
2. I didn't review that PR
3. I didn't comment on that PR

And yes, I'm more happy with killing rand() & prob() than I am with qdel()

**Pull request closed without merging**
