### PR TITLE
Resprite t45b

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
resprites the t45b harsuit
image

# Wiki Documentation
 

# Changelog

:cl:  
imageadd: added t45b new sprite 
imagedel: deleted t45b old sprite  
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
i prefer the NCR salvaged power armor sprite theme, its a bit more iconic and more colorful, and less drab and boring, but this sprite definitely does a better job conveying it as a bulky set of armor.

**Comment by cuackles** [comment]
> i prefer the NCR salvaged power armor sprite theme, its a bit more iconic and more colorful, and less drab and boring, but this sprite definitely does a better job conveying it as a bulky set of armor.

from what i saw on the code and while playing it wasnt the NCR armor it was called the T45B so i used that as a base for the new one, while its true that the old one had more color i wouldnt call it iconic, it was hardly seen and it had just some specs of red and yellow, and in my opinion it was hard to see and messy, this new sprite makes it more similar as whats based on and its a lot more easy on the eyes and as you said, it does look more chunky wich makes it look more like a power armor and not a bag of chips someone put over their head

**Comment by Smudged** [comment]
> i prefer the NCR salvaged power armor sprite theme, its a bit more iconic and more colorful, and less drab and boring, but this sprite definitely does a better job conveying it as a bulky set of armor.

Imo, the NCR salvaged power armour looked nothing like what it was supposed to represent from what Cuackles showed me. 
This does look much closer to it's source material, rather than a bright bunch of pixels that quiet frankly look nothing like what it's portraying.

**Comment by LoliconSlayer** [comment]
Old sprite:
68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f3132303936363333362f353334373432373335332f342f6265666f72652e706e67
NCR Salvaged T-45d
image_2022-02-28_231357

I can see the resemblance, I think the issue is that Bethesda changed how Power Armor worked in lore from Fallout 3/NV to Fallout 4 leaving us with wildly different interpretations of how it looks.

**Comment by cuackles** [comment]
> Old sprite:
> 68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f3132303936363333362f353334373432373335332f342f6265666f72652e706e67
> NCR Salvaged T-45d
> image_2022-02-28_231357
> 
> I can see the resemblance, I think the issue is that Bethesda changed how Power Armor worked in lore from Fallout 3/NV to Fallout 4 leaving us with wildly different interpretations of how it looks.

Oh then i must have done a mediocre job researching cus i found other power armor searching, and yeah that looks more like the sprite

**Review by nesisknesis — COMMENTED** [review]
The helmet needs an object sprite.

**Comment by cuackles** [comment]
> The helmet needs an object sprite.

done

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
