### PR TITLE
Adds Buttplug.io support and integrates it with taking damage

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

This PR allows you to locally configure your preferred device to recieve inputs from the server.

It is triggered based on how much damage you've taken. There's a sensitivity setting.

Admins can remotely trigger this.

# Spriting
No

# Wiki Documentation

Setup guide coming

# Changelog

:cl:  
rscadd: Adds buttplug.io support based on your health percentage
rscadd: Admin manipulation of above support
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
wrong repo

**Comment by ktlwjec0** [comment]
based

**Comment by DeadlyBag** [comment]
are we not getting the setup guide now?

**Comment by Simplehorror** [comment]
???

**Comment by Maia-J** [comment]
This is great. We need this

**Comment by JamieD1** [comment]
Never.

**Comment by flleeppyy** [comment]
you can do this on 516 now without needing to PR anything, you just need to know how to inject javascript into the chatbox window and connect to the websocket

**Comment by flleeppyy** [comment]
> you can do this on 516 now without needing to PR anything, you just need to know how to inject javascript into the chatbox window and connect to the websocket

yeah so i... made this a thing. i need a life.

**Comment by alexkar598** [comment]
I don't care

**Comment by alexkar598** [comment]
Let's not necropost ancient ass PRs please

**Pull request closed without merging**
