### PR TITLE
Beartraps now need to be anchored in order to deal damage when triggered

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Stacking 100 in a locker and dragging it anywhere on the station is boring and uninspired, it instantly kills someone without requiring any real setup or plan
Spending 5 minutes anchoring 100 beartraps to a specific tile and then luring someone to step on that tile is based, as it actually requires the bare minimum of thought to pull off

# Testing
image

:cl:  
tweak: Beartraps now need to be anchored in order to deal damage when triggered
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
no more 

https://github.com/yogstation13/Yogstation/assets/44718209/a10ff31c-dca9-4ac0-967a-120a842f42c3

**Comment by Moltijoe** [comment]
> no more
> 
>  2023-06-05.16-41-09_Trim.mp4

is that mqiibothy?

**Comment by LassiH** [comment]
acthually lockers can only hold 30 beartraps

**Comment by Moltijoe** [comment]
> acthually lockers can only hold 30 beartraps

🤓

**Comment by LassiH** [comment]
also this dosent really change anything as xenobio can make extracts that force teleport people without a counter

**Comment by Moltijoe** [comment]
> also this dosent really change anything as xenobio can make extracts that force teleport people without a counter

that's more of a xenobio issue than a beartrap issue

**Comment by LassiH** [comment]
true

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
