### PR TITLE
some retard argued with me over something so now i am punishing the entire server by nerfing mechs

### PR DESCRIPTION
**Pull request by ghost**
specifically i'm moving the SRM missile rack and the clusterbang launcher behind illegal tech
#### Changelog

:cl:  
rscadd: clusterbang and SRM-8 missile launchers now take syndicate weaponry to unlock due to balance issues
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
merge or riot

**Comment by boodaliboo** [comment]
no

**Comment by Ktlwjec** [comment]
lovely changelog adam

**Comment by MegaEmpirical** [comment]
I had a similar idea about illegal tech when mulling over the decentralization stuff.

**Comment by nesisknesis** [comment]
//yogs comments or riot

**Comment by Bibby0110** [comment]
undocumented changes

**Comment by AsV9** [comment]
bad changelog lmao

**Comment by ghost** [comment]
changelog fixed

**Comment by HomocidlePancakes** [comment]
:omegalul:

**Pull request merged**
