### PR TITLE
Neurotoxin Knockdown

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Sort of an alternate to #18537
Replaces the 100 (or 50 for zombies) tick stun with a knockdown.
Becuase tazers were removed for a reason

"Wuhuhbuh wont this nerf xenos to being unplayable?!??!?!"
my brother in Christ they have the disarm intent to stun lock you, and the tackle to leap at you and stun lock you, and the face hugger to throw at 90% of the crew that don't have masks to stun lock them. They are fine.

# Changelog

:cl:  
tweak: Neurotoxin knocks you down instead of paralyzing you.
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
very cool, now make it not work against you if you have TRAIT_TOXIMMUNE

**Comment by MajManatee** [comment]
no wtf

**Comment by iamthesilly** [comment]
> no wtf

why? it's a neuroTOXIN

**Comment by iamthesilly** [comment]
it doesn't make any sense whatsoever that something that's immune to all toxins would be affected by this

**Comment by MajManatee** [comment]
powercreeping your race smh

**Comment by Moja10** [comment]
1. From my understanding in a round an HoS got xeno spit gland and spat at people and used it like a taser and this has caused some talk, it looks like this PR could be a result of that round. Not confirmed. 

2. This utterly fucks the Queen at the most crucial step of being a beno, which is when you are the fat slow queen and you have no children and no easy ability to get children unless people walk directly into an egg or you find a pile of maint monkeys. In this stage, like 90% of the time the xeno queen gets beaned from a distance from lasers and can't reach with disarm or eggs. the ONLY defense is spit and its the only reason a xeno Queen can survive in this stage. You won't be seeing any of the shit like pounce because that requires the Queen to be successful at this stage, and more often than not, they don't.

I don't want spit nerfed because one HoS used it in one round like a taser. It will fuck the only ability Queens have to even make a hive to begin with when the crew has lasers and brain cells

**Comment by MajManatee** [comment]
I made this PR because the idea of making it melee was worse, and we have removed stuns everywhere else. 
A HOS getting the spit as a glad is based as hell and I wish I was there to see it

You can also, you know, spit multiple times...
its got like a 3 second cooldown

**Comment by Moltijoe** [comment]
https://github.com/yogstation13/Yogstation/pull/18552

has been approved instead

**Pull request closed without merging**
