### PR TITLE
Adds Reviver Implant to syndicate uplink for 3TC, and adds it to the implant Syndi-Kit tactical impant kit

### PR DESCRIPTION
**Pull request by boodaliboo**
adds the reviver implant as it seems very fitting and also adds it to the implant kit which kinda frankly fucking sucks

:cl:  
rscadd: Adds Reviver Implant to syndicate uplink for 3TC, and adds it to the implant Syndi-Kit tactical impant kit
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
I HAVE COME TO NOTICE REVIVER IMPLANT IS ALREADY A UPLINK ITEM BUT IT ALSO COSTS 8tc should i just remove it and keep the 3tc version

**Comment by Maia-J** [comment]
> I HAVE COME TO NOTICE REVIVER IMPLANT IS ALREADY A UPLINK ITEM BUT IT ALSO COSTS 8tc should i just remove it and keep the 3tc version

Certified coder moment

**Comment by boodaliboo** [comment]
> > I HAVE COME TO NOTICE REVIVER IMPLANT IS ALREADY A UPLINK ITEM BUT IT ALSO COSTS 8tc should i just remove it and keep the 3tc version
> 
> Certified coder moment

i think 8tc is a horrible cost

**Comment by boodaliboo** [comment]
> Reference

the other reviver is nukies only

**Comment by VaelophisNyx** [comment]
so unlimit it.

**Comment by 00ze-cyclone** [comment]
Can you make it a syndicate reviver implant that work the same but doesn’t die to EMP because:
1) uplink items that are just things crew can already get is kinda lame
2) that thing just straight up kill you if EMPed and as an antag you kinda need to use EMPs

That way it can be worth TCs.

**Comment by VaelophisNyx** [comment]
tbh....yeah? That ^

**Comment by boodaliboo** [comment]
> Can you make it a syndicate reviver implant that work the same but doesn’t die to EMP because:
> 
> 1. uplink items that are just things crew can already get is kinda lame
> 2. that thing just straight up kill you if EMPed and as an antag you kinda need to use EMPs
> 
> That way it can be worth TCs.

i can do that is there any implants that are already emp proof

**Comment by boodaliboo** [comment]
> so unlimit it.

it costs to much as is no one is spending 8tc for that, im likely going to make two reviver implants a emp proof one for 8tc and a normal one for 3tc

**Comment by Bibby0110** [comment]
Conflicts + stale + you never removed the old one

**Pull request closed without merging**
