### PR TITLE
Better Brig mod for forge and fabric (1.12.2)

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Moves all the guns inside and reduces the amount of blindspots between the armory sections

image

# Wiki Documentation

map update!!!!!!!!!!!!!!!

# Changelog

:cl:  
mapping: armory is now enhanced
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
thats crazy u reverted the syringe gun thing

**Comment by JamieD1** [comment]
The issue is now its easier to break into from inside

**Comment by SomeguyManperson** [comment]
> The issue is now its easier to break into from inside

yes but the warden will be able to very easily tell if there is a giant fucking hole in the security area by the ominous blue lighting and thusly react to it while the antagonist attempts to break down 2 windoors and a reinforced table (the great wall of china)

**Comment by ToasterBiome** [comment]
i like this

**Comment by Moja10** [comment]
this is better than the hallway or double wall solution

**Comment by neeshacark** [comment]
I like this, in order to raid the armory you might actually need to deal with the warden instead of just him not noticing.

**Comment by patpol4** [comment]
best option imo, would be nice if the map edit wasnt all over the place though

**Comment by patpol4** [comment]
Closing in favour of https://github.com/yogstation13/Yogstation/pull/17379

**Pull request closed without merging**
