### PR TITLE
Autopsy surgery

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Detective is useful

**New surgery: Autopsy**

Target chest of a dead body with drapes, scalpel until results acquired

Not holding a forensic scanner in your off-hand makes you suffer an additional 75% fail rate on a 15 second long step

Upon completion, tells you what last damaged the patient and shreds the fuck out of the patient (you are a bad doctor) (autopsy requires cutting the patient up I think)

Make sure no one accidentally kicked the shit out of body on the way to the surgery table

image

image

# Wiki Documentation

new surgery - autopsy - can only be performed on the dead
step 1: scalpel
step 2: /obj/item/scalpel = 75%, /obj/item/kitchen/knife = 30%, /obj/item/shard = 15%, hold forensic scanner in offhand or you suffer additional 75% fail rate
tells you what last hit the patient

# Changelog

:cl:  ynot01, maxion12345
rscadd: Added the autopsy surgery, performed by detectives
rscadd: Gave detective an autopsy room on boxstation with accompanying tutorial paper
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
Would be interesting to see an advanced autopsy to let you know who the last person they saw was, like TTT. Gated behind what research?

**Comment by Moggram** [comment]
>TTT

[That's a man's head](https://youtu.be/6LFHZDXhUI8)

**Comment by UselessTheremin** [comment]
Ynot make it so that it ends by sealing up the patient and on examination you can see a y-shaped stitch across their chest as that's how autopsies are finished

**Comment by bruhlookatthisdood** [comment]
Will it be like dissectoin and render revival not an option?

**Comment by ynot01** [comment]
> Will it be like dissectoin and render revival not an option?

No it just deals 200 brute damage to the patient

**Comment by ynot01** [comment]
> Ynot make it so that it ends by sealing up the patient and on examination you can see a y-shaped stitch across their chest as that's how autopsies are finished

Despite the cool-factor, I would prefer the "reckless" ending to give some reasonable cost to this procedure

**Comment by nmajask** [comment]
It might be better to make the autopsy step require a forensic scanner (either as the tool or in the offhand like what tend wounds uses for exact health values) instead of checking for forensic gloves as it is a weird way of doing it. Also, if you end up keeping the gloves, it would be a good idea to mention it in the surgery description like with DNA recovery mentioning that you need rezadone.

**Comment by Hopekz** [comment]
> Despite the cool-factor, I would prefer the "reckless" ending to give some reasonable cost to this procedure

Why not both?

**Comment by bruhlookatthisdood** [comment]
i agree- oh shit i fell and dropped some code!
image
image
image

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
does this cover every single type of damage so if you die no matter what you will have something in the last_damage variable

**Comment by ynot01** [comment]
> does this cover every single type of damage so if you die no matter what you will have something in the last_damage variable

~~review the code lazy shit~~

mostly

damage procs do not have the courtesy of telling you what exactly damaged you, they just apply damage and fuck off, so i have to go around and look for damage procs around the code and shove in my last_damage variable

i've covered every common damage (items, projectiles, various creature attacks) and some extra, if you see more then please tell me/submit a code request

**Comment by ynot01** [comment]
> It might be better to make the autopsy step require a forensic scanner

good idea

**Comment by ToasterBiome** [comment]
> > does this cover every single type of damage so if you die no matter what you will have something in the last_damage variable
> 
> ~review the code lazy shit~

Time to forget to review this!

**Comment by bruhlookatthisdood** [comment]
if some idiot det tries to do autopsy on a suicide victim, what will it say?

**Comment by Moggram** [comment]
> if some idiot det tries to do autopsy on a suicide victim, what will it say?

Even in real life when they know its a suicide, it has to be done. It would be a RP thing to do.

   P.S. Epstein didn't kill himself

**Comment by ynot01** [comment]
> > Despite the cool-factor, I would prefer the "reckless" ending to give some reasonable cost to this procedure
> 
> Why not both?

it would not make sense for a currently-mutilated body to also have stitches from that mutilation

**Comment by ynot01** [comment]
> if some idiot det tries to do autopsy on a suicide victim, what will it say?

self-inflicted

**Comment by ynot01** [comment]
with the addition of the scanner i have removed the gloves requirement, making things a little smoother and less restrictive

you can now perform the surgery without det gloves

you can perform the surgery without the forensic scanner in your offhand but it will only have a 25% chance to pass without it (not affected by surgery success chance; in addition to the already 75% chance success rate, multiplicatively) and it is a 15 second long step so it will take a while if you are not lucky and not the detective

**Comment by JamieD1** [comment]
Queued for Map Review

**Comment by JamieD1** [comment]
@ynot01 I dont really like the idea its a tiny sealed room, is there a way we can make it a bit more open, maybe even using curtains? Just seems like a 1x2 death box with no visibility or cameras.

**Comment by ynot01** [comment]
> @ynot01 I dont really like the idea its a tiny sealed room, is there a way we can make it a bit more open, maybe even using curtains? Just seems like a 1x2 death box with no visibility or cameras.

det office is pretty small, it's cramped as it is with the addition of the autopsy box

and uh, it is a death box.. you're supposed to be performing on dead people

**Comment by Moggram** [comment]
Just make the room like it is on meta

?

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
fix the conflicts (lol!)

**Comment by ynot01** [comment]
mapdiffbot is having  a moment the map is correct

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image

@maxion12345 fix

**Comment by Tipy1802** [comment]
Have been asking for this for a long time. Thank you Ynot, you are epic

**Comment by ynot01** [comment]
> image
> 
> @ maxion12345 fix

i must have not been clear enough in my previous comment

the new map is up to date with the master branch and has no unintentional changes, the bot is incorrect

you would see this if you looked at the changes in sci, which are a part of a recently merged PR

**Comment by maxion12345** [comment]
> image
> 
> @maxion12345 fix

looking at the "old" photo, the vents there are of the old server room. Those changes were recently merged, and the map file is up-to-date from master. 

aye, look at what the bot thinks is the "old" yogstation file. You'll see two vents in the server room airlock, where the new one only has the one dual-vent. These changes were merged as of 2 days ago https://github.com/yogstation13/Yogstation/pull/13473

**Review by ToasterBiome — APPROVED** [review]
ok , map diff being stupid as the changes are the same with master, room looks fine, up to jamie

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
