### PR TITLE
Changes not paradises wall chargers sprite to better fit yog stations anti taser agenda 

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
Wall chargers show a disabler instead of a taser now 

Wiki might have to update their image of a charger 

# Changelog

:cl:  

imageadd: Wall chargers now show a image of a disabler instead of a taser!

/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
did you accidentally get the holopads modified or am I tripping

**Comment by ToasterBiome** [comment]
icon bot says you changed holopads reee

**Comment by KillerOrcaCora** [comment]
Iconbot is framing me I never touched those!

**Review by Hopekz — CHANGES_REQUESTED** [review]
You have a rogue pixel in icon wrecharger2.
Top left corner. Looks like a yellow-ish pixel mid-animation for a single frame

**Comment by KillerOrcaCora** [comment]
No stray pixel bot is being bad.

**Comment by JamieD1** [comment]
Not from paradise :^)

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
