### PR TITLE
Removes implant breaker from the gang tool

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

this has no reason to exist and just says "fuck you" to security efforts

#### Changelog

:cl:  
rscdel: Removed implant breaker from the gang tool
/:cl:

### CODE REVIEW

**Comment by overlord12345** [comment]
this makes rushing mindsheilds and cucking gangs too easy

**Comment by ynot01** [comment]
> this makes rushing mindsheilds and cucking gangs too easy

then dont let sec rush mindshields
what do you think revs do

**Comment by monster860** [comment]
revs have 75% of the station flashed before any sec or heads know anything.

**Comment by ynot01** [comment]
> revs have 75% of the station flashed before any sec or heads know anything.

then play stealthily, if one gang decides to out themselves they face the punishment just as hard as you do

**Comment by bragew** [comment]
i though we already went through this earlier. If you remove implant breaker then gangs are just going to kill instead. The time it takes to implant is longer than the time it will take to switchblade the person to death. This way the perosn does not get killed but rather converted.

**Comment by gar4** [comment]
We have already been through this. Remove implant breaker and gangs will just kill instead of convert. If you have someone for longe enough to implant break then you can also kill them. People already dislike gangs due to all the people being taken out of the round, this will make it worse.

https://github.com/yogstation13/Yogstation/pull/6037

**Comment by ynot01** [comment]
FJ3x4NZ

**Comment by Ratvar** [comment]
I myself dislike gangs because 1 gang converts security/heads and wins, which is too easy with implant breakers/heads being convertable . At least killing them doesnt give you as much power. Really, taking out cargo consoles n protolathes will remove new mindshields from coming, why do I never see people do it

**Comment by Hopekz** [comment]
Imagine having an item that just lets you go up to sec, push them and convert them on the spot past their implant.
Now stop imaging because this already exists in game.

I don't like how it is viable to do this kind of cheap strategy both as sec and as gang.

**Comment by SomeguyManperson** [comment]
I have an idea why not make gangs not terrible

**Review by alexkar598 — CHANGES_REQUESTED** [review]
I like this but for the love of god remove the code, dont comment it out.

**Comment by AsV9** [comment]
this will be reconsidered in a week or two, but I'm merging the PR because I can't be fucked to deal with a testmerge for two weeks

**Pull request merged**
