### PR TITLE
edits rebreather mask descrption to make it more apparent on how it worked

### PR DESCRIPTION
**Pull request by boodaliboo**
the mask currently gives 0 indication on how it works so for the longest time i thought it was broken turns out it isnt and it just needed to be more clear on how to use it
#### Changelog

:cl:  
tweak: tweaked rebreather mask description to be more apparent on what it does
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
terrible grammar

**Comment by ynot01** [comment]
crikey you could at least put some effort in

**Comment by MrHorizons** [comment]
While the intention is good with this PR, I don't think the parenthetical is the best way to do it. I believe something like replacing the last sentence with "Seems to lack any air supply tube, though, **as if it doesn't need one.**" would be more streamlined and less matter-of-fact.

**Comment by boodaliboo** [comment]
> While the intention is good with this PR, I don't think the parenthetical is the best way to do it. I believe something like replacing the last sentence with "Seems to lack any air supply tube, though, **as if it doesn't need one.**" would be more streamlined and less matter-of-fact.

ok

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
