### PR TITLE
Revert "Ports TG balloon alerts"

### PR DESCRIPTION
**Pull request by Cartlord**
Reverts yogstation13/Yogstation#15041 because there's already been a bit of "Don't make it a pref, just improve or remove" on https://github.com/yogstation13/Yogstation/pull/15246 and I figured I'd offer the "remove" option so that balloon alerts aren't as likely to stay in shitty limbo where they're in the game but nobody's making them better
This is obviously an alternative to SuperSlayer0's P.R., one should be closed if the other's merged

:cl:  
tweak: balloon alerts are gone
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Improve don't remove

**Comment by VaelophisNyx** [comment]
not much to improve here honestly, they still suck for permanent record

keep both and we're good
remove balloons, and we're good

**Comment by Cartlord** [comment]
As far as I am concerned, the only options to make balloon alerts better are "make them come with chat messages" and "check the entire list of things that have balloon alerts and change it so only things that won't matter in eight seconds (like *gun clicks*) have balloon alerts" - the former of which could be a pref, the latter of which would be a good bit of effort for remarkably little gain.

**Comment by tattax** [comment]
lol

**Comment by Hopekz** [comment]
> Improve don't remove

When you code it

**Comment by SuperSlayer0** [comment]
Cope lol

**Comment by redmoogle** [comment]
should have included images

**Comment by Bibby0110** [comment]
I think we all agree that removal isn’t the way to go

**Comment by ghost** [comment]
Ez skill isue

**Pull request closed without merging**
