### PR TITLE
DOOR CRUSHES NOW TEAR OFF YOUR BODY PARTS

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

DOORS BEFORE: PUSSY SHIT
DOORS NOW: `REAL SHIT`

#### Changelog

:cl:  
tweak: Doors will now delimb on crushing you
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
stun? yeah
plenty of damage? yeah
delimb? maybe we've gone too far

next we'll make em just fucking gib you. no brain, no limbs left. just gibs. your round is over bucko, next time dont hack doors

**Comment by Mqiib** [comment]
Good lord, delimbing would be annoying as hell. This is an AI buff my dude, and nobody wants to buff AIs.

**Comment by ynot01** [comment]
> Good lord, delimbing would be annoying as hell. This is an AI buff my dude, and nobody wants to buff AIs.

STUN TIME IS REDUCED BY 4X NOW MAKING IT AN AI NERF

**Comment by jcatjmeow** [comment]
Clearly untested, and it's shitcode.

This will always get the first body part, the head. And even if it picked a random limb, having even a CHANCE to behead at all is not good.

Literal meme pr

**Comment by jcatjmeow** [comment]
Leaving it open for 24 hours but even if this worked correctly it would be not good. And it doesn't

**Comment by ynot01** [comment]
a spamming crowbar/AI crushes you once every ~1.3 seconds
paralyze is set to 0.9 seconds
if you hold a direction you should be able to escape

doors are no longer permastun weapons as a result

PR is tested and works as intended
it no longer rips off your head (it was funny though)
you will be stunned for 0.9 seconds instead of 10 seconds (stuns are bad for the game)
at worst, if someone tries to use this as a weapon you should congratulate them for being so creative and you won't be stunlocked like before

**Comment by maxion12345** [comment]
if AI times it perfectly enough to trap you in a door after going through that laggy door menu to disable safeties it deserves the kill

**Comment by jcatjmeow** [comment]
Still cycles through the limbs one at a time and cuts them off in order. Super unnecessary and broken for loop 

And no, supply pod code is not good either

**Comment by Darkstick** [comment]
would be cool if it broke your bones instead but we don't have a system like that.

**Comment by Hopekz** [comment]
I like shutter crushing to be able to be used as a warning.
There are instances where you don't want any lasting effects for example for kitchen, Robo and science shutters etc.

With this change the chef for example can't really give people a "slap on the wrist" by slamming the shutter on people for hopping over the counter.

**Comment by alexkar598** [comment]
Normally im against closing balance PRs within less than a week but this is stupid

**Pull request closed without merging**
