### PR TITLE
Conditional department goals

### PR DESCRIPTION
**Pull request by Amelia0010**
Adds conditional department goals, IE goals that will only be added if certain conditions are true. Two examples added here are based on engineering:

If the station has a supermatter engine, the objective will be to setup a singularity. If the station has a singularity/tesla, the objective will be to setup a supermatter.

~~Also adds a goal for cargo to make a tesla engine in the cargo bay. Because you know, cargo ain't gonna have other goals.~~

:cl:
rscadd: Engineering will now get a goal to set up the opposite engine of what they spawn with. 
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
I like the idea of this PR and the framework of what it allows for the future.

The example you implemented with it of giving cargo an excuse to be engineering isn't too great in my opinion.
Hopefully, people won't take this framework to just make Cargo be every department ("Create a full RnD lab", "make an armory", "create a full medbay setup + cloning")

+1 good framework
-1 odd implementation to normalize cargo powergaming
= True neutral.

**Comment by Tipy1802** [comment]
Please for the love of god do not justify cargo powergaming. Cargo technicians are not supposed to know how to set up engines, maybe move it to engineering

**Comment by Amelia0010** [comment]
OK hugboxer

**Comment by JamieD1** [comment]
This has been a hot topic with admins, most admins want engineering to be part of this and not just let cargo powergame. Will come back to this.

**Comment by Amelia0010** [comment]
The cargo tesla goal has been split off into https://github.com/yogstation13/Yogstation/pull/9469 to avoid dragging this PR down with it.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
