### PR TITLE
Makes syndibase look nicer

### PR DESCRIPTION
**Pull request by Ktlwjec**
Mostly https://github.com/tgstation/tgstation/pull/44373 with a few changes.

image

:cl:  kittymaster0, ktlwjec 
tweak: Cleaned up Syndiebase after TC station removal.
/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
looks good.  A very welcome change

**Comment by HomocidlePancakes** [comment]
Too. Much. Empty. SPAAAAAAAAAAACR

**Comment by alexkar598** [comment]
@Readystorm546 If you don't have any specefic comments,you can use the Thumbs up/ Thumbs down reaction on the post instead to reduce the spam of needless comments.

**Comment by HomocidlePancakes** [comment]
Can you atleast put some posters where the TC stations used to be? I dunno why but that space being empty really triggers me

**Pull request merged**
