### PR TITLE
Disables Profiler which has not been running for 6 months or anything.

### PR DESCRIPTION
**Pull request by JamieD1**

### CODE REVIEW

**Comment by alexkar598** [comment]
Why was it turned on in the first place? This has actual performance impacts on the game bruh

**Comment by JamieD1** [comment]
> Why was it turned on in the first place? This has actual performance impacts on the game bruh

To profile.

**Comment by alexkar598** [comment]
I don't remember anyone ever using it

**Comment by JamieD1** [comment]
> I don't remember anyone ever using it

I used it.

**Pull request merged**
