### PR TITLE
Adds a pipebomb recipe, for all your mailbombing needs

### PR DESCRIPTION
**Pull request by maxion12345**
https://user-images.githubusercontent.com/23666142/160318454-3995d51d-2f38-48bb-aec9-c153c1fea7f3.mp4

# Document the changes in your pull request

Adds a pipebomb, crafted with
50 units of welder fuel
a stack of cables
one igniter
one pipe
and one mousetrap

uses a welder, wrench, and wirecutters.

The explosion is the same as an IED, so no breaching space

Not super lethal, unless you detonate more then one at a time.

You arm it, stick it in a container, and the next person who opens it gets a bomb in they face

now with codersprites
68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f3132303936363333362f353731333837313038322f312f61667465722e706e67

# Wiki Documentation
Add to crafting wiki page

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added a pipebomb for your IRA roleplay needs.
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
bruh i made you a sprite with all my love and kindness and you didnt use it??? sad bro, sad

**Comment by Cartlord** [comment]
why would you use this and not a t.t.v. prox sensor mailbomb

**Comment by Marmio64** [comment]
uh, cant you already do this with mouse trap bombs? Is this just adding a more accessible way to do it, one that doesnt require grenade frames (which are already easily accessible) and doesnt require finding water+pot or other explosive substances?

**Comment by maxion12345** [comment]
> bruh i made you a sprite with all my love and kindness and you didnt use it??? sad bro, sad

you never gave me the sprite after you got banned for posting cock and ball in the discord smh

nevermind you did I just didn't notice ping me when you notice me not noticing and I'll swap it

**Comment by maxion12345** [comment]
> uh, cant you already do this with mouse trap bombs? Is this just adding a more accessible way to do it, one that doesnt require grenade frames (which are already easily accessible) and doesnt require finding water+pot or other explosive substances?

Yes. But, IEDs are a thing and I always was pretty disappointed you cant mailbomb with improvised bombs like IEDs. 
Also, we don't have any pipebombs, and those are essential for proper mailbombing.

**Review by nesisknesis — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
