### PR TITLE
cult dark spirits are now visible during ascension

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

this is barely even a nerf anymore you all suck

#### Changelog

:cl:  
tweak: Cult dark spirits are now visible 
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
I mean it kinda defeats the point. as the dark spirits cant do much, there are probably better ways to nerf it

**Comment by ynot01** [comment]
> I mean it kinda defeats the point. as the dark spirits cant do much, there are probably better ways to nerf it

the point is that you become a literal aghost and you are effectively omniscient

**Comment by redmoogle** [comment]
> 
> 
> > I mean it kinda defeats the point. as the dark spirits cant do much, there are probably better ways to nerf it
> 
> the point is that you become a literal aghost and you are effectively omniscient

then why is a ghost visible 👀

**Comment by ynot01** [comment]
> > > I mean it kinda defeats the point. as the dark spirits cant do much, there are probably better ways to nerf it
> > 
> > 
> > the point is that you become a literal aghost and you are effectively omniscient
> 
> then why is a ghost visible 👀

because becoming a literal aghost and being effectively omniscient is overpowered
like many things in bloodcult
there's only one other thing in the game that lets you do this and it costs 2 wizard points
making the dark spirit visible at least lets the person you're orbiting know that they're being watched and if the cult is not already revealed, reveals them and outs you as a cultist

**Comment by Marmio64** [comment]
how about, the ghost only is visible when the cult has blood halos. Otherwise, if the cult uses this ability while trying to be stealthy, its such a horrible fucking nerf. Downvoting for now, please make ghost invisible when no halos.

**Comment by JamieD1** [comment]
Think of another way of doing it, people dont like it.

**Pull request closed without merging**
