### PR TITLE
adds mond emote

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
adds the mond emote
image

# Changelog
:cl:  
rscadd: Added mond emote
/:cl:

### CODE REVIEW

**Comment by breadtoucher** [comment]
motherucker

**Comment by Therandomhoboo** [comment]
Player references aren't allowed

**Comment by breadtoucher** [comment]
> Player references aren't allowed
mond harder

**Comment by SomeguyManperson** [comment]
Are we just turning any string of four letters into an emote now

**Comment by azzzertyy** [comment]
> Are we just turning any string of four letters into an emote now

try monding

**Comment by Maia-J** [comment]
_monds_

**Comment by azzzertyy** [comment]
L

**Pull request closed without merging**
