### PR TITLE
adds space gorilla ruin

### PR DESCRIPTION
**Pull request by boodaliboo**
original pr: https://github.com/Citadel-Station-13/Citadel-Station-13/pull/8627
image
its pressurized
#### Changelog

:cl:  
rscadd: Added new ruin 
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
is it monstermosproof

**Comment by boodaliboo** [comment]
fuck you nich

**Comment by boodaliboo** [comment]
> is it monstermosproof

tiny fans

**Review by patpol4 — CHANGES_REQUESTED** [review]
Map appears fine, i like it, also you got to add the ruin to config/spaceruinblacklist.txt

**Comment by boodaliboo** [comment]
> Map appears fine, i like it, also you got to add the ruin to config/spaceruinblacklist.txt

will do

**Review by JamieD1 — APPROVED** [review]

**Review by patpol4 — APPROVED** [review]
Assuming Jamie changed the config this should be good to go

**Pull request merged**
