### PR TITLE
Adds a map of the station to players' boxes

### PR DESCRIPTION
**Pull request by monster860**
Screenshot of my shitty programmer art:

image

Actual map:

image

there's a tooltip when you hover over an area.

:cl: monster860
add: Adds a map of the station to players' boxes
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
This is good PR! Absolutely nothing wrong with it!

**Comment by boodaliboo** [comment]
will it say the names of the area when hovered over

**Comment by Mr-Space** [comment]
Could this be a PDA option instead of a whole new item?

**Comment by monster860** [comment]
> will it say the names of the area when hovered over

yes

**Comment by Hopekz** [comment]
> Could this be a PDA option instead of a whole new item?

No it must stay as a separate item PDA can't handle a full color map are you crazy PDA's are basically pagers with messaging functionality. Tablets maybe but PDA's?

**Comment by Amelia0010** [comment]
I'll add this to PDAs or tablets eventually

**Comment by MegaEmpirical** [comment]
This fucking threw me off the first round, was trying to put my usual shit into my box in a hurry and was getting frustrated.

Nice addition though.

**Pull request merged**
