### PR TITLE
Eminence tweaks and buffs

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Now eminience clicking on an atom will call attack_eminience(mob/user, params) proc, rather then handling all interactions in it. Wall heating, activating traps and other shit now uses this proc.

Also now eminience can break lights(it can be helpfull some times, but since clockwork cultists also need light to see it is not very OP), and also interact with cogged APCs(experimental).

# Spriting
No

# Wiki Documentation

Eminence can interact with APCs and break lights

# Changelog

:cl: SuperSlayer
rscadd: Eminence can break lights
experimental: Eminence can interact with cogged APCs
tweak: Slightly refactored eminence code
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
but why can the eminemce break lights

**Comment by ghost** [comment]
> but why can the eminemce break lights

Why not? Eminence is currently useless shit, so giving it additional things would be ok.

**Comment by Sniblet** [comment]
it’s such a random power

**Comment by ghost** [comment]
> it’s such a random power

The idea is stolen from bee clockcult rework

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
