### PR TITLE
Remove hulk recipe

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

bye bye tider gene

# Wiki Documentation

hulk is gone

# Changelog

:cl:  
rscdel: hulk is no longer attainable
/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
God bless

**Comment by Moja10** [comment]
Cringe, do something like making it not fit anything else because of stability before literally chopping it out. maybe remove some of the stupid buffs people keep piling on it before chopping it out. I don't when exactly the hulk smash got added, but hulks didn't have that in the past.

**Comment by Simplehorror** [comment]
and what will hulk be replaced with in something like clockwork cult

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> and what will hulk be replaced with in something like clockwork cult

thats the thing, it's nothing. clockwork cult dies extremely badly to mechs anyway, having a stun-proof enemy when most of your attacks are incapacitating is bad, not to mention hulk smashes ignore the clockwork armor. and unlike mechs genetics can mass produce hundreds of thousands of hulk mutators to negate every single cultist ability

**Comment by Simplehorror** [comment]
> > and what will hulk be replaced with in something like clockwork cult
> 
> thats the thing, it's nothing. clockwork cult dies extremely badly to mechs anyway, having a stun-proof enemy when most of your attacks are incapacitating is bad, not to mention hulk smashes ignore the clockwork armor. and unlike mechs genetics can mass produce hundreds of thousands of hulk mutators to negate every single cultist ability

so sabotage genetics? with your instant teleport to almost anywhere for free?

**Comment by ghost** [comment]
Sex

**Comment by maxion12345** [comment]
hulk? based
fighting hulks? not based

just make it so hulks have to rest to pass through doorways, have massive fuckall sprites, delayed attack speed and idk incurable asscancer after it gets used

**Comment by ghost** [comment]
> hulk? based
> 
> fighting hulks? not based
> 
> 
> 
> just make it so hulks have to rest to pass through doorways, have massive fuckall sprites, delayed attack speed and idk incurable asscancer after it gets used

And make them take 99x damage from any sources

**Comment by SomeguyManperson** [comment]
> Cringe, do something like making it not fit anything else because of stability before literally chopping it out. maybe remove some of the stupid buffs people keep piling on it before chopping it out. I don't when exactly the hulk smash got added, but hulks didn't have that in the past.

Stability doesnt matter when its the only thing people use
The strength is a combination of full stun immunity, high armor ignoring melee damage, and effectively no downside for having it

**Comment by N3D6** [comment]
> and what will hulk be replaced with in something like clockwork cult

Skill

**Comment by ghost** [comment]
> and what will hulk be replaced with in something like clockwork cult

Cry about it

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Unfortunately I agree, Hulk is just too much trouble then its worth, if someone wants to bring it back in the future with fixes sure. But as of right now. Its just pain.

**Comment by Simplehorror** [comment]
if we keep removing powers from genetics due to admin issues then we're not going to have any left

**Pull request merged**
