### PR TITLE
[ASTEROID] Replaces Hydroponics setup with DA WIENER

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

The asteroidstation setup for hydro is really cool with the different levels but it's CBT to actually walk around in it because the entire place is just 1x1 hallways around it.

So I introduce: THE WIENER
image

# Wiki Documentation

Asteroid Hydro looks like this 
image
# Changelog

:cl:  
mapping: Changes AsteroidStation's hydroponics to be more open
/:cl:

### CODE REVIEW

**Comment by Ethan4303** [comment]
Good PR Merger As Soon As Possible

**Comment by Cartlord** [comment]
i don't actually know what it looked like before but i like this look

**Comment by RG4ORDR** [comment]
No soul.
Looks boring

**Comment by Aquizit** [comment]
Conflict probably due to #18371

**Review by Ethan4303 — APPROVED** [review]
Looks good map wise but i have to ask why you used the corner tiles for every single green square?????

**Review by patpol4 — APPROVED** [review]
nice cock bro

**Pull request merged**
