### PR TITLE
Moves combat powers from xenolings to antagling-only

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request
image

Abilities moved to antagling-only:
Armour
Shield
Armblade
Tentacle
Dissonant shriek
Resonant shriek
Spiders
Armblade sting
Cryo sting

#### Changelog

:cl:  
tweak: Xenobio changelings no longer have access to combat focused powers, such as armblades or armour.
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
What about removing their hivemind radio because it's only used to validhunt antags out?

**Comment by Amelia0010** [comment]
baby steps.

**Comment by Ktlwjec** [comment]
beautiful pr dear

**Comment by GuppyLaxx** [comment]
How dare you include me in the screenshot, now my erp is revealed

**Comment by ghost** [comment]
changelog is misleading

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
fixed

**Comment by Amelia0010** [comment]
sorry I mistyped, but mc fixed it

**Pull request merged**
