### PR TITLE
smoking is now bad for you

### PR DESCRIPTION
**Pull request by SomeguyManperson**
% chances subject to change it's the same % as ephedrine currently
:cl:  
rscadd: Nicotine addictions now can cause you to drop items
rscadd: overdosing on nicotine will cause lung damage
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
How do you even fix lung damage? New lung?

**Comment by SomeguyManperson** [comment]
Or lobectomy surgery iup think its called, organs will heal on their own if they haven't entirely failed they are just slightly less efifcient untilу the damage is under certain amounts

**Comment by Hopekz** [comment]
So how long of chain smoking to see effects? (looks like about 30-40ish minutes to me but I may be doing mental math wrong)

**Comment by Moja10** [comment]
dropping items is too powerful of an addiction, keep in mind that dropping items was added to ephedrine in order to weaken it's use in combat and here we are adding a 40% drop chance just because someone smoked for very little in game benefit.

**Comment by SomeguyManperson** [comment]
It's not because they smoked a little for antistuns, it's because they either A: smoked long enough to become addicted then didn't keep the addiction up, or B: took the smoker trait which currently has no downside for people without mood enabled since nicotine's addiction is completely harmless aside from the baseline addiction mood debuffs

**Comment by Hopekz** [comment]
Not completely against it but maybe dropping items seems a bit too much of a side-effect?
Not sure what it would be replaced with just never seen smokers literally drop items because they can't get a smoke

**Comment by deathslayer2481** [comment]
Fucking Cigars are lethal.

**Pull request merged**
