### PR TITLE
fixes ai core icon thingy

### PR DESCRIPTION
**Pull request by Bibby0110**
bla bla bla

thanks toasterbiome for actually doing his job with sprites

### CODE REVIEW

**Review by adamsong — DISMISSED** [review]
Changelog

**Comment by Bibby0110** [comment]
> Changelog

nope, not playerfacing since it just makes an already added feature work as intended

**Review by adamsong — DISMISSED** [review]
Bugfixes are player facing, as the bug was player facing

**Comment by ToasterBiome** [comment]
where's my credit bro

**Pull request merged**
