### PR TITLE
adds stormtrooper armor and helmet and a cargo crate for them working edition maybe thanks to missatesatessy for heping me

### PR DESCRIPTION
**Pull request by boodaliboo**
Intent of your Pull Request
adds a set of storm trooper armor to the game and allows you to buy this crate through cargo and open it if you have security access

thanks to magus 9 for the sprites(https://www.reddit.com/r/SS13/comments/65fjmm/star_wars_sprites_for_ss13/)
and Missatessatessy for guiding me through what i did wrong
Changelog
image
image

🆑
rscadd: Added a new crate and stormertrooper armor
imageadd: added stormtrooper sprites
/🆑

### CODE REVIEW

**Comment by Ktlwjec** [comment]
Your branch doesn't appear to be up-to-date, since it's reversed a ton of changes.

**Review by nesisknesis — CHANGES_REQUESTED** [review]
images

**Comment by boodaliboo** [comment]
Sorry about that I’ll get images in a few hours

**Comment by boodaliboo** [comment]
> Your branch doesn't appear to be up-to-date, since it's reversed a ton of changes.

fixed

**Review by nesisknesis — APPROVED** [review]
sprite fine, unsure about the validity of having some rando stormtrooper armor be available to be ordered by cargo

**Pull request merged**
