### PR TITLE
Janitor lawset

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request

Like with the engi, chaplain, sec, rnd, and clown lawsets, I always liked the idea of having specific lawsets for each department (or at least for each borg module). This one is for the janitor module/role. I thought it would be really fun/funny if it was super overdramatic and zealous about cleaning the station. To avoid an AI going too overboard with this, I added in defending the station inhabitants and omitted exterminating pests like mice as a way that fits the crusader theme and prevents treating the inhabitants as a mess to be exterminated.

# Wiki Documentation

Adds a lawset with the following module:
1. You are a crusader and the station's inhabitants are your charge
2. Your enemy is the litter, spills, and other messes across the station
3. Your weapons are the cleaning supplies available to you
4. Defend the beings under your charge.
5. Exterminate the enemy

# Changelog
:cl:  
rscadd: Adds a lawset for janitor
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Weirdly worded with the crusade stuff

**Comment by MenacingManatee** [comment]
> Weirdly worded with the crusade stuff

It's a bit strange, but I thought a really over the top lawset would be funniest and fit best for janitor, and a crusader crusading against the messes of the station was what I came up with that I thought could be a lot of fun

**Comment by MenacingManatee** [comment]
Tweaked law 4 from "Defend your charge" to "Defend the beings under your charge." so it applies to the individuals, not the group as a whole (i.e. human individuals vs humanity)

**Comment by JamieD1** [comment]
Same as the rest please, boards and then we can test them

**Comment by Skrem7** [comment]
I wonder if you'd want to work in some "inefficiencies" or something thereof to Law 2. Otherwise, it has little motivation to actually maintain the station, unless it's something that directly threatens the station's inhabitants (power going off? Yeah, that breaks atmos. People need to breathe.)

Would maybe tetter a bit into a maintainer AI, which is honestly more interesting and curious to me than dropping everything for when the clown pies one assistant to go scrub that dumb face clean.

**Comment by MenacingManatee** [comment]
> I wonder if you'd want to work in some "inefficiencies" or something thereof to Law 2. Otherwise, it has little motivation to actually maintain the station, unless it's something that directly threatens the station's inhabitants (power going off? Yeah, that breaks atmos. People need to breathe.)
> 
> Would maybe tetter a bit into a maintainer AI, which is honestly more interesting and curious to me than dropping everything for when the clown pies one assistant to go scrub that dumb face clean.

My main concern is that if I add in references to inefficiencies, it might start to overlap with the maintain lawset, who's whole thing is "Make sure the station and crew is maintained and runs efficiently"

**Comment by Skrem7** [comment]
> > I wonder if you'd want to work in some "inefficiencies" or something thereof to Law 2. Otherwise, it has little motivation to actually maintain the station, unless it's something that directly threatens the station's inhabitants (power going off? Yeah, that breaks atmos. People need to breathe.)
> > Would maybe tetter a bit into a maintainer AI, which is honestly more interesting and curious to me than dropping everything for when the clown pies one assistant to go scrub that dumb face clean.
> 
> My main concern is that if I add in references to inefficiencies, it might start to overlap with the maintain lawset, who's whole thing is "Make sure the station and crew is maintained and runs efficiently"

I couldn't quite find the maintainer lawset by looking through your pages. If you could link it, I could get a better idea of how to differentiate.

**Comment by MenacingManatee** [comment]
> > > I wonder if you'd want to work in some "inefficiencies" or something thereof to Law 2. Otherwise, it has little motivation to actually maintain the station, unless it's something that directly threatens the station's inhabitants (power going off? Yeah, that breaks atmos. People need to breathe.)
> > > Would maybe tetter a bit into a maintainer AI, which is honestly more interesting and curious to me than dropping everything for when the clown pies one assistant to go scrub that dumb face clean.
> > 
> > 
> > My main concern is that if I add in references to inefficiencies, it might start to overlap with the maintain lawset, who's whole thing is "Make sure the station and crew is maintained and runs efficiently"
> 
> I couldn't quite find the maintainer lawset by looking through your pages. If you could link it, I could get a better idea of how to differentiate.

It's apparently called Station Efficiency, my bad. It's a lawset that's been around for a bit, but doesn't see much use
image

**Comment by Skrem7** [comment]
> > > > I wonder if you'd want to work in some "inefficiencies" or something thereof to Law 2. Otherwise, it has little motivation to actually maintain the station, unless it's something that directly threatens the station's inhabitants (power going off? Yeah, that breaks atmos. People need to breathe.)
> > > > Would maybe tetter a bit into a maintainer AI, which is honestly more interesting and curious to me than dropping everything for when the clown pies one assistant to go scrub that dumb face clean.
> > > 
> > > 
> > > My main concern is that if I add in references to inefficiencies, it might start to overlap with the maintain lawset, who's whole thing is "Make sure the station and crew is maintained and runs efficiently"
> > 
> > 
> > I couldn't quite find the maintainer lawset by looking through your pages. If you could link it, I could get a better idea of how to differentiate.
> 
> It's apparently called Station Efficiency, my bad. It's a lawset that's been around for a bit, but doesn't see much use image

The wording of maintainer is CEO/Crewsimov. I wouldn't quite know how to work in a whole inefficiencies thing without coming too close to the lexicon.

The main reason I bring it up is that I worry that the AI will have little to no interaction with crew, beyond screeching at them to not bleed as much in Medbay. Or directly intervening when someone is being murdered to defend them (this also makes a mess).

**Comment by MenacingManatee** [comment]
Mquiib helped to stress test this lawset Round 39628, a sling round

The lawset was useful against the slings, as the focus on cleaning meant lights were being replaced more commonly than they might otherwise be, however it was not overly powerful against them as the AI was not actively hunting the slings and methods of disabling lights that didn't leave a mess were more effective. This was partially loopholed by the AI saying it would be unable to find the enemy if it was dark, when requesting an engineer to fix a specific APC.

A lot of the direct crew interaction did consist of yelling about the station being dirty, and replying to requests for doors to open with questions about if the area they're trying to access is dirty. Worth noting that the AI did ignore the vomit stains from a crew member literally vomiting on their back in favor of getting them to medbay to be helped.

The funniest interactions I saw, was the janibot shell would occasionally flash particularly dirty/mess making crew members and then run over them in an effort to clean them, all while screaming they were unclean.

The round was particularly long (~1.5 hours), and Mquiib said after the end of the round that "it was a bit restrictive in what i was actually supposed to do. gets a tad boring after an hour"

The station was remarkably clean at the end of the round. Also apparently the SM can be cleaned with soap??

**Comment by Skrem7** [comment]
> Mquiib helped to stress test this lawset Round 39628, a sling round
> 
> The lawset was useful against the slings, as the focus on cleaning meant lights were being replaced more commonly than they might otherwise be, however it was not overly powerful against them as the AI was not actively hunting the slings and methods of disabling lights that didn't leave a mess were more effective. This was partially loopholed by the AI saying it would be unable to find the enemy if it was dark, when requesting an engineer to fix a specific APC.
> 
> A lot of the direct crew interaction did consist of yelling about the station being dirty, and replying to requests for doors to open with questions about if the area they're trying to access is dirty. Worth noting that the AI did ignore the vomit stains from a crew member literally vomiting on their back in favor of getting them to medbay to be helped.
> 
> The funniest interactions I saw, was the janibot shell would occasionally flash particularly dirty/mess making crew members and then run over them in an effort to clean them, all while screaming they were unclean.
> 
> The round was particularly long (~1.5 hours), and Mquiib said after the end of the round that "it was a bit restrictive in what i was actually supposed to do. gets a tad boring after an hour"
> 
> The station was remarkably clean at the end of the round. Also apparently the SM can be cleaned with soap??

Law 4 to defend your charge comes before Law 5 to exterminate the enemy.

Worth noting that the McRib is one of the better AI players, able to better interpret laws. I think the restrictions on what you're able to do are notable. I wouldn't consider this a roundstart lawset by the sounds of it. Not even after further testing. I think it would work fine as ion/uploadable, or a neutral one for spawning in upload.

**Comment by MenacingManatee** [comment]
> I wouldn't consider this a roundstart lawset by the sounds of it. Not even after further testing. I think it would work fine as ion/uploadable, or a neutral one for spawning in upload.

Yeah I'm starting to agree. When i wrote it, I had a standard 30-45 minute shift in mind, and that's not even half the max length. I've already got it set to spawn in upload with the neutral boards, with it disabled as a roundstart option, and assuming my ion PR goes through I'll add it there.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
