### PR TITLE
reduce hunger slowdown

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

why is skipping food the most punishing shit in the game? also this code was very hard to find. imagine getting hungry in the middle of a fight and then you lose because you are now the slowest entity in the game, second only to the AI
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: reduce hunger slowdown
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
only reason nobody did this before is nobody could find the fucking code

**Comment by bruhlookatthisdood** [comment]
thank you so much
no longer do i have to walk at the pace of snellie snailington when i forgor to eat in the last 5 seconds

**Comment by Simplehorror** [comment]
DINOSSAUROdoACRE — Today at 11:21 PM
its almost like starving to death is a actual issue that kills people
and that you should eat

if you are starving to death after 20 minutes of not eating you should see a doctor

**Comment by Simplehorror** [comment]
frankly chef-made food should bring you benefits instead of being punished for not eating, that way people are motivated to eat chef made food but aren't missing out on anything otherwise

**Comment by Hopekz** [comment]
Should probably add a comment in there to help others find it in the future

**Comment by Simplehorror** [comment]
> Should probably add a comment in there to help others find it in the future

i'm not letting anyone slow it down again

**Comment by JamieD1** [comment]
Hunger is incredibly avoidable. Chef Nerf

**Pull request closed without merging**
