### PR TITLE
viro Emp symptoym

### PR DESCRIPTION
**Pull request by boodaliboo**
# Document the changes in your pull request

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: will add description after i get compile errors
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
downvotes before its even described the virus emps yourself only

**Comment by wonderinghost** [comment]
no

**Comment by iamthesilly** [comment]
why does this need to exist

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
fill out the form

**Comment by Moltijoe** [comment]
Balance council deemed this idea as generally bad, emps are common enough as it is.

**Pull request closed without merging**
