### PR TITLE
adds different cuffs sprites to different huds

### LINKED ISSUE #18571: Cant see which hand is active
## Test Merges: 
Not Supplied / None
## Reproduction:
I had the dono role, then it got removed, but the ratvar hud stayed, but I couldnt see which hand was the active hand in the hud.
## Supplied Image:

SuppliedImage
 Submitted by: Nickie (842223373789691913)

### PR DESCRIPTION
**Pull request by tattax**
detective hud looks hella weird with normal cuffs sprites + clockwork has gauntlets to work with so why not

also makes the right hand on all huds not 1 pixel above the left one (which would make it just not fit the handcuff icon)

Closes https://github.com/yogstation13/Yogstation/issues/18571 since the my other pr will never get merged and this is pretty major

# Spriting

9wYkDxBaL2

updated one 

image

:cl:  
imageadd: adds different cuff sprites to clockwork and det hud
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
typical type mistake

**Comment by tattax** [comment]
det cuff might look a tad bit weird and i am open to changing it

**Comment by cuackles** [comment]
> det cuff might look a tad bit weird and i am open to changing it

yes please change it so its more similar to the others, currently it isnt really clear if your not used to the hud

**Review by cuackles — APPROVED** [review]

**Comment by tattax** [comment]
@Moltijoe

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
