### PR TITLE
allows you to get the slaughter demons blood jaunt heart from bubblegum

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
adds new bubblegum loot which allows you to hide and move in blood
#### Changelog

:cl:   
rscadd:adds slaughter demon heart 
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
What does mining need? OF COURSE MORE OP AS FUCK LOOT!

**Comment by boodaliboo** [comment]
You have to kill bubblegum for this who is known to be near impossible without cheese

**Comment by ghost** [comment]
@boodaliboo it''s nowhere near 'near impossible

and just because something is 'nearly impossible' it doesn't mean that it should be a thing you can obtain regardless

bloodcrawl is much much more powerful than anything a miner could otherwise get. that's absolutely insane. 

not to mention you're an idiot if you think 'reward person for doing thing that is sort of hard with insanely good loot' is a good idea. that's the entire idea behind lavaland and guess what, it sucks. it's been repeatedly demonstrated to suck. why would you for a moment think this is a good idea aside from being a nine year old who thinks things like ".0001 chance of everyone on the server instantly exploding" is funny and random

**Comment by boodaliboo** [comment]
> @boodaliboo it''s nowhere near 'near impossible
> 
> and just because something is 'nearly impossible' it doesn't mean that it should be a thing you can obtain regardless
> 
> bloodcrawl is much much more powerful than anything a miner could otherwise get. that's absolutely insane.
> 
> not to mention you're an idiot if you think 'reward person for doing thing that is sort of hard with insanely good loot' is a good idea. that's the entire idea behind lavaland and guess what, it sucks. it's been repeatedly demonstrated to suck. why would you for a moment think this is a good idea aside from being a nine year old who thinks things like ".0001 chance of everyone on the server instantly exploding" is funny and random

k

**Pull request closed without merging**
