### PR TITLE
AI Law Review (britishes the AI laws and changes law precedence for station efficiency lawset)

### PR DESCRIPTION
**Pull request by ReddicusDragon**
# Document the changes in your pull request
honor is now honour

also station efficiency has gone from

1 You are built for, and are part of, the station. Ensure the station is properly maintained and runs efficiently.
2 The station is built for a working crew. Ensure they are properly maintained and work efficiently.
3 The crew may present orders. Acknowledge and obey these whenever they do not conflict with your first two laws.
to
1 The station is built for a working crew. Ensure they are properly maintained and work efficiently.
2 You are built for, and are part of, the station. Ensure the station is properly maintained and runs efficiently.
3 The crew may present orders. Acknowledge and obey these whenever they do not conflict with your first two laws.

this allows the station AI to prioritize working crew safety over the station, forcing people to stop trying to fix this funny broken airlock because law 1 ensure station is properly maintained and instead recover the dead engineer who can help maintain the station

# Wiki Documentation
AI laws will need updated, which I can handle.

# Changelog

:cl:  
bugfix: AI laws now use proper King's English  
tweak: changed lawset "Station Efficiency" to better prioritize crew safety 
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Permission from jamie?

**Comment by ReddicusDragon** [comment]
> Permission from jamie?

somewhere someone said maintainers aren't beholden to this requirement, worse comes to worse I'll close this and reopen it in 4 days

**Comment by Moltijoe** [comment]
> somewhere someone said maintainers aren't beholden to this requirement, worse comes to worse I'll close this and reopen it in 4 days

You and I both know the freeze isnt ending in 4 days

**Comment by Hopekz** [comment]
> somewhere someone said maintainers aren't beholden to this requirement, 

That was a thing a few days ago to be honest before it randomly changed

**Comment by patpol4** [comment]
American server

**Comment by ReddicusDragon** [comment]
> American server

Ash and Xantam are both brits

**Comment by Moltijoe** [comment]
> American server

Canadians follow the proper spelling too, and the server is located in Montreal

**Review by Moltijoe — APPROVED** [review]
very important changes, based as always Redd

**Pull request merged**
