### PR TITLE
Adds a define for multiplying power consumption

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
It would be easier to balance power consumption in the future with a single multiplier instead of manually editing all machines.
# Changelog
No user facing changes

### CODE REVIEW

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
No need for this to be a config option, make it a define in machines.dm or power.dm

**Review by Bibby0110 — APPROVED** [review]

**Comment by CMOisLing** [comment]
I have a feeling people are not gonna like the follow up PR

**Comment by ReddicusDragon** [comment]
> I have a feeling people are not gonna like the follow up PR

yes.

**Review by JamieD1 — APPROVED** [review]
No do it per engine like I have for SM and for Tesla

**Review by JamieD1 — DISMISSED** [review]
No do it per engine like I have for SM and for Tesla

**Comment by Simplehorror** [comment]
so you want a define for power generation instead?

**Pull request merged**
