### PR TITLE
New flashbang ring noise

### PR DESCRIPTION
**Pull request by Chubbygummibear**
# Update as of 10/13/21
I figured out audacity for babies and have toned down the ring by 25%, and the demonstration video has been updated to reflect the toned down version

# Document the changes in your pull request

This has been talked about for like months in the public chat but i finally actually did it. i honestly don't expect this to get merged, it's just fun.

I tested this in a private server and it works when you get flashbanged. the old deafened noise is still in, in the event of hearing loss by genetics or damaged ears, because this new noise is awfully debilitating.

I am not a sound engineer so sorry if the file is completely wrong it in the wrong bitrate or something

Demonstration:
https://youtu.be/pnV-tUIx-9w

# Wiki Documentation

Sound change, so i don't think those are documented. you win this time morde and anvil

# Changelog

:cl:  
tweak: Old deafened noise is kept for regular hearing loss
soundadd: New sound for getting hit by a flashbang
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
think fast chucklenuts

**Comment by Cartlord** [comment]
I dislike the sound

**Comment by Hopekz** [comment]
Ow, why do people want a flashbang sound to make your ears ring IRL?

It is just supposed to be some sound that represents you being deaf, not make the player deaf

**Comment by Chubbygummibear** [comment]
> Ow, why do people want a flashbang sound to make your ears ring IRL?
> 
> It is just supposed to be some sound that represents you being deaf, not make the player deaf

apologies, i'm aware of how awful the sound is. this was just something i keep seeing come up in the discord public whenever someone posts that mp3 of the ringing, so now going forward if someone posts it again and people go "dude let's pr this" we can show that people were either for or against it and put it to bed.

also as i said in the first line, i don't expect a lot of support for this, or for it to get merged, but i figured i'd toss it into the pr box just to see what happens

**Comment by Hopekz** [comment]
> also as i said in the first line, i don't expect a lot of support for this, or for it to get merged, but i figured i'd toss it into the pr box just to see what happens

Might just be able to maybe turn down the sound code-wise.
My feedback is strictly from the demonstration video sound (:

Like maybe make it the volume of a soft hum in the background

**Comment by maxion12345** [comment]
csgo flash sound

**Comment by Bluedazzled** [comment]
my ears really hurt please turn the volume down
other than that yeah good pr 👍 
(you can use audacity to lower volume)

**Comment by Chubbygummibear** [comment]
> my ears really hurt please turn the volume down other than that yeah good pr 👍 (you can use audacity to lower volume)

thank you and to commodore because turning down a file isn't actually something i knew how to do, so thanks to your help i reduced it by 25% and updated the demonstration vid

**Comment by JamieD1** [comment]
Not sure on this to be honest, the old one is fine, this one feels a bit cheap.

**Pull request closed without merging**
