### PR TITLE
tcomms achievement

### PR DESCRIPTION
**Pull request by Lostlarry**
adds two hidden achievements that concern a certain bird

:cl:  
rscadd: adds more things to be achieved when scripting NTSL
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
I like these achievements even if the AI + any borgs can modify Poly to give the signal tech the achievement.

**Comment by Amelia0010** [comment]
the AI/borg can't.

**Comment by Hopekz** [comment]
> the AI/borg can't.

I still don't see it then.
From my understanding of it this change it creates a virtual radio that listens to Poly and if Poly is loud on that radio (or silent) by comparing what was done to the sig and it gives the achievement to the signal tech.

From my understanding this a;sp means that the AI or borgs can modify the NTSL script themselves for this achievement to trigger. Not necessarily that it is a bad thing but it is an observation.

**Comment by Amelia0010** [comment]
It's a wrong observation. It only runs the test if the person compiling is a signal tech, if the AI/borg compiles it then the test won't run.

**Pull request merged**
