### PR TITLE
New maint rooms made by me! (3x5_onioncult by Ezhan)

### PR DESCRIPTION
**Pull request by jcatjmeow**
### Intent of your Pull Request

Look at em!

I am very open to feedback and changes. PLEASE have a maptainer review this, preferably wej, before merging. This means you jamie

#### Changelog

:cl:  
rscadd: Added a whole new bunch of maint rooms
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
I do appreciate the updoots but I know for a fact at least 2 of these rooms need major changes. Criticism is welcome and direly needed, even if you like the pr as a whole

**Comment by Moggram** [comment]
where are them pics man?

**Comment by Moja10** [comment]
For pics, go to the checks tab and check MapDiffBot.

**Comment by Moggram** [comment]
> 
> 
> For pics, go to the checks tab and check MapDiffBot.

did not know that.

**Review by patpol4 — CHANGES_REQUESTED** [review]
10x10_aquarium - what if you put a carp costume in the suit storage
10x10_junction - is that rotating shutter system tested?
10x10_lasertag - keep 2 lockers in each, idk about rechargers in maint, maybe leave just one and make the other one broken? make the tinted rwindows regular windows, place platings under them, firelocks in iron doors.
chrome_Gs8WZcOk46
10x10_ninetofive - love it
10x10_vault - PLATINGS UNDER WINDOW SPAWNERS JCAT OH MY GOD
10x10_ward - you put two lootcrates on each other in the surgery room, same for charred skeletons, keep it to just one per tile. also i think 4 lootcrates is a bit much. surgery room needs window spawners, not just lone windows. Also i think you mistaken the viro biohood for the viro plasmaman helmet, unless that is intentional.

Review will continue

**Review by patpol4 — CHANGES_REQUESTED** [review]
10x5_factory - there's no lever for the conveyor. Halve the amount of crowbars, i see what you're going for here but that is a little excessive.
10x5_insomnia - great theme, i think you want the laptop to be the preset civilian version or otherwise it wont work, not sure though
10x5_transit - this is going to be so obnoxious, love it
3x3_memorial - you didnt set the area
3x3_singularity - how about this
chrome_zaaaEn9pUT
3x5_checkpoint - missing 2nd firelock on the desk
5x3_firebot - probably only one that I actually don't like, idk it just feels weird
5x4_icicle - i dont think we want a cold room like this to spread bad atmos all over maint. Make the snow temperate, i think that makes it not cold, same for ice and cold plating. You can leave the freezer setup but make it off by default.

Overall i think these are really good and thought out, great job.

**Comment by jcatjmeow** [comment]
@wejengin2

**Comment by patpol4** [comment]
Yes yes i know, just need to give them another post review look and I'll merge. Just give me some time, you won't get conflicts on this one.

**Review by patpol4 — APPROVED** [review]
Gave them a brief look to see if you fixed the things and it appears you did

**Pull request merged**
