### PR TITLE
Redoes NVS Gax Robotics

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

# Why is this good for the game?

Got some feedback and changed it up to be more open in the middle.

# Wiki Documentation

Robo bay looks like that now on gax

# Changelog

:cl:  
mapping: Changes NVS Gax Robotics to be more open
/:cl:

### CODE REVIEW

**Review by neeshacark — CHANGES_REQUESTED** [review]
image
the door here needs to be sci maint area, consistency my good man

image
this railing will probably be overlayed by the vendor, and will look CRINGE

image
the tables will connect like they do and this railing will also look buttfuckugly probably

**Comment by Spacemanspark** [comment]
absolutely based

**Comment by ToasterBiome** [comment]
> this railing will probably be overlayed by the vendor, and will look CRINGE
image
nuh uh

image

**Review by neeshacark — CHANGES_REQUESTED** [review]
image

railing overlays monitor partially, still looks bad

**Comment by ToasterBiome** [comment]
> image
> 
> railing overlays monitor partially, still looks bad

cant go anywhere else, it would be blocked by the table if it were south (also looks like shit) 5 pixels is a good compormise

**Comment by neeshacark** [comment]
> > image
> > railing overlays monitor partially, still looks bad
> 
> cant go anywhere else, it would be blocked by the table if it were south (also looks like shit) 5 pixels is a good compormise

i would just remove it but you are the boss

**Review by neeshacark — APPROVED** [review]

**Pull request merged**
