### PR TITLE
Adds modular PDA and Telescreen and cleans up some of the preset code

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request
## Changes
Adds modular PDA and Telescreen and cleans up some of the preset code. PDAs function as phones with a much smaller number of component slots, number of max active programs, and available programs, which I plan on using as a replacement for normal PDAs once I add some more features to modular computers (also added a clown version with an obnoxious pink color and the ability to slip). 

Telescreens are ported from Bay, which was added with ["[READY] Large amount of modular computer tweaks" #15656](https://github.com/Baystation12/Baystation12/pull/15656) by atlantiscze, and function similarly to how they do there except for how they are built (they are made with five metal and are hung on a wall like APC frames) and where they appear (right now, just box engi). 

Presets have been changed to use lists of programs/parts instead of each device doing their own thing and each device has their own preset file. Additionally, PDAs were added to the mod pc vender and tablets/phones were made to be premium items. And finally, I added a bunch of tiny fixes while I was messing around with mod pc code, mainly fixing a runtime when inspecting consoles with an aux ID slot and converting 1 & 0 to TRUE & FALSE where it makes since in a few files. Much more testing is going to be needed, but its builds fine when I tested it. If staff wants it atomized, I can do it but it would take some time for me to do as many of the changes are intertwined with each other.
## Pictures
image
image
image

## To Do

- [x] Fix telescreens not being able to be opened with a normal click
- [x] Add more program sprites for the PDAs
- [x] Clean up some unused stuff
- [x] Check spelling and grammar
- [x] Test stuff

# Wiki Documentation

Map images will need to be updated. 

# Changelog

:cl:  atlantiscze & nmajask
rscadd: Added modular PDAs  
rscadd: Added modular Telescreen  
tweak: Some consoles now start with programs active
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
isnt this wip

**Comment by nmajask** [comment]
> isnt this wip

Almost everything functions as intended, with the majority of things that need to be done being polish and stuff that I can fix tomorrow. If you want to make it a draft PR feel free to do so, though I would probably end up removing the draft tomorrow.

**Comment by Hopekz** [comment]
Legendary PR

PDA code hasn't really been touched since prebase except for the language bounty I made a year ago so this is really refreshing to see.

Hopefully this rework keeps messaging being done in the primary language chosen.

**Comment by nmajask** [comment]
> Legendary PR
> 
> PDA code hasn't really been touched since prebase except for the language bounty I made a year ago so this is really refreshing to see.
> 
> Hopefully this rework keeps messaging being done in the primary language chosen.

This doesn't touch PDA code, all this does is add two new modular computer types and clean up some code. I'm waiting until I add more stuff from PDAs to modular computers before I have them replace regular PDAs, mainly a way to DM people, skins for different jobs, and allowing you to see ID information when you have an ID in a modular computer worn in your ID slot.

**Comment by Hopekz** [comment]
> > Legendary PR
> > 
> > PDA code hasn't really been touched since prebase except for the language bounty I made a year ago so this is really refreshing to see.
> > 
> > Hopefully this rework keeps messaging being done in the primary language chosen.
> 
> This doesn't touch PDA code, all this does is add two new modular computer types and clean up some code. I'm waiting until I add more stuff from PDAs to modular computers before I have them replace regular PDAs, mainly a way to DM people, skins for different jobs, and allowing you to see ID information when you have an ID in a modular computer worn in your ID slot.

Ah, my bad I misunderstood this PR

**Comment by nmajask** [comment]
PR is all set now, main mapping changes are engi on most maps getting a telescreen. Additionally, PDAs replace engineer and atmos tech phones as they can download all of the programs that they often use. If people want that atomize, I can do that.

**Review by patpol4 — APPROVED** [review]
Map is fine

**Comment by patpol4** [comment]
Very nice pr, truly a revolution

**Review by nesisknesis — APPROVED** [review]

**Comment by adamsong** [comment]
Would these be a viable replacement for regular PDAs?

**Comment by nmajask** [comment]
> Would these be a viable replacement for regular PDAs?

I don't think so yet, as modular computers still don't have a messaging program, don't have any doner skins (working on it with a lot of help from Ident), and ~~they still don't show jobs~~ (added if #12799 is merged) along with many other minor things that people would miss.

**Comment by JamieD1** [comment]
Fix cornflakes please.

**Comment by nmajask** [comment]
> Fix cornflakes please.

Done

**Comment by warface1234455** [comment]
The nanotrasen micro arcade "Outbomb Cuban Pete Ultra" doesn't have any texture on the telescreen 
Screenshot_687

**Comment by nmajask** [comment]
> The nanotrasen micro arcade "Outbomb Cuban Pete Ultra" doesn't have any texture on the telescreen 

Make a big report

**Pull request merged**
