### PR TITLE
Give advanced firefighting cargo crate 4 atmos gloves and advanced fire extinguishers

### PR DESCRIPTION
**Pull request by warface1234455**
theses arent available in cargo is sad
# Document the changes in your pull request
Give advanced firefighting cargo crate 4 atmos gloves and advanced fire extinguishers

# Wiki Documentation
Give advanced firefighting cargo crate 4 atmos gloves and advanced fire extinguishers

# Changelog

:cl:  

tweak: Give advanced firefighting cargo crate 4 atmos gloves and advanced fire extinguishers
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
Might want to increase the cost because of how much more you get out of it

**Comment by ShoziOffical** [comment]
> Might want to increase the cost because of how much more you get out of it

right

**Comment by athena413** [comment]
increase it more

**Comment by iamthesilly** [comment]
I think 4000 would be a fair price

**Comment by ShoziOffical** [comment]
honestly 3000 is good enough since uh 2000 is already from the suits and just the gloves or the extinguishers shouldnt cost that much

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
