### PR TITLE
Vermin bite is now considered a junk food

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Lizards getting to completely ignore cook because something that's bought from the vendor is just genuinely good food is bad

no longer gives vitamins, and is classified as junkfood

# Testing
image
image
image

:cl:  @cuackles @Moltijoe 
rscadd: Adds fat mouse that counts as junk food when eaten
tweak: Vermin bites now gives a fat mouse rather than a regular mouse
rscadd: Vermin bites now creates trash
imageadd: Sprites for fat mouse
imageadd: new sprites for vermin bites and it's trash
/:cl:

### CODE REVIEW

**Review by SapphicOverload — APPROVED** [review]

**Comment by MajManatee** [comment]
now I have to eat even less. yippie
although the healing was nice

**Comment by Moltijoe** [comment]
> now I have to eat even less. yippie although the healing was nice

it's the same amount of nutrition, it's just no satiety

**Comment by cuackles** [comment]
You forgot to add in why it's god for the game : fat rats

**Review by ToasterBiome — APPROVED** [review]
lol fat mouse

**Pull request merged**
