### PR TITLE
Removes Summon Ghosts

### PR DESCRIPTION
**Pull request by Absolucy**
# Document the changes in your pull request

It's like an inevitably that any wizard that picks summon ghosts will be unrobust and die very quickly, leading to a mulligan, and then the resulting new antags get fucked over by ghosts, some of whom will intentionally out them to security, with _absolutely nothing_ that the antag can do about it.

Rest in piss, summon ghosts.

# Changelog

:cl: Lucy
rscdel: Summon Ghosts is gone, finally.
/:cl:

### CODE REVIEW

**Comment by LazennG** [comment]
lol

**Comment by ToasterBiome** [comment]
cry?

**Comment by alexkar598** [comment]
the event is actually useful for bussing, i used to use it to put an end to rev rounds that went on forever. was a nice IC... ish way to force the game to an end

**Comment by N3D6** [comment]
Can we please stop attempting to remove things solely because we don't like them

**Comment by Bibby0110** [comment]
> Can we please stop attempting to remove things solely because we don't like them

can we remove n3d6?

**Comment by IsProbablyCatto** [comment]
Created immediately after being outed by ghosts on a ling round, rage PRs shouldnt be merged

**Comment by Hopekz** [comment]
> Can we please stop attempting to remove things solely because we don't like them

I thought that's what every removal is about

**Comment by Hopekz** [comment]
> Created immediately after being outed by ghosts on a ling round, rage PRs shouldnt be merged

Created now, in an hour or in a week what's the difference.
Connecting a PR to a recent in-game event is circumstantial at best

**Comment by Marmio64** [comment]
liking your own pr?
we dont do that here

**Comment by maxion12345** [comment]
if you cast summon ghosts I will make security arrest random people by pointing at them

Ghosts are the best antag

**Comment by Absolucy** [comment]
Meh, I'll just make a different PR that un-summons ghosts whenever all wizards are dead.

**Pull request closed without merging**
