### PR TITLE
Removes MetaStation and IceBox in favor of IceMeta

### PR DESCRIPTION
**Pull request by patpol4**
### Intent of your Pull Request
Removes IceBox and Yogsmeta, replaces it with IceMeta
Basically this https://github.com/tgstation/tgstation/pull/52017 but Yogs edition

### Why is this good for the game?

We don't play Icebox because it's unmaintained, we don't play meta because it's barely maintained and some people don't like it. This solves this problem by merging the two together and removing the amount of maps me and other mappers have to maintain.

I just made it work and now it needs a lot of tweaks to work better
To do:

- [x] make the dithering of manually placed ice walls look better

- [x] gulag

- [x] icemeta outside areas

- [x] active turfs

- [x] transfer centre death pit

- [x] probably some other things 

- [x] cooled rooms like rd server without freezer

- [x] tinyfans in small airlocks because screw monstermos

- [x] atv bay

- [x] EVA needs changing

- [x] Remove the ugly lattices, maybe try snow platings and fences instead?

- [x] gravgen

vivaldi_HwybIzTkof

#### Changelog

:cl:  
rscadd: IceMeta
rscdel: removes metastation and icebox 
wip: This is work in progress  
/:cl:

### CODE REVIEW

**Comment by burn1cycle** [comment]
We play Meta about once a day or once every two days. It's supposed to be our +50 population map but everyone likes to struggle with Box which wasn't designed for +50 population.
 People don't like IceBox and you think their going to jump at IceMeta with a feature they already don't like on a map they don't prefer?  If it's a labor issue than BOOM bye-bye Icebox. Meta shouldn't even need much work just ports from TG  to stay updated anyways, Meta is the most preferred map on TG and probably the most maintained.

**Comment by patpol4** [comment]
> People don't like IceBox 

citation
>and you think their going to jump at IceMeta with a feature they already don't like on a map they don't prefer?

yeah
>Meta shouldn't even need much work just ports from TG to stay updated anyways, 

It's all volunteer work so you can't really be picky when someone takes their time to update it

>Meta is the most preferred map on TG and probably the most maintained.

we're not TG

**Comment by Jarod1200** [comment]
This is based as hell. Nice

**Comment by Tipy1802** [comment]
Wej, you are the greatest developer on yogs
Bloody genius!

**Comment by burn1cycle** [comment]
> > People don't like IceBox
> 
> citation


It's never voted for, people don't choose it in map preference, and everyone groans and complains in OOC when it comes up in rotation.

 I'll make a cash bet that 90% of our player base will not like this map.

**Comment by alao3alao3** [comment]
Monstermos airlocks work on those ice settings now, right?

**Comment by patpol4** [comment]
> It's never voted for, people don't choose it in map preference, and everyone groans and complains in OOC when it comes up in rotation.

It's not in rotation and disabled in config so you can't even vote for it. It's been that way for some time now

**Comment by patpol4** [comment]
> Monstermos airlocks work on those ice settings now, right?

yeah Jamie fixed it

**Comment by patpol4** [comment]
chrome_gSFm9CinXL
chrome_slCMTt2anu

Made it a little bit less artificial and with a way to get back up

**Comment by Tipy1802** [comment]
> > > People don't like IceBox
> > 
> > 
> > citation
> 
> It's never voted for, people don't choose it in map preference, and everyone groans and complains in OOC when it comes up in rotation.
> 
> I'll make a cash bet that 90% of our player base will not like this map.

Yeah nobody votes for it. Because it's not even in rotation since it was bugged for the longest time xD

**Comment by TheLinuxOS** [comment]
I love IceBox, the only reason it never gets played is because it has to be admin forced and no one maintains it. I would love to see an IceMeta as it would add more variety then fucking box station every round

**Comment by patpol4** [comment]
This
vivaldi_R9gel5LiCw

Drops 2 levels deep into this

vivaldi_CYMqhRPbZE

**Comment by burn1cycle** [comment]
I apologize. I would have to say I was previously wrong. We did a server vote for Yes/No Icebox station. Yes won 13/12. The round started and a few people wised up that we were doing Icebox and got pretty irritated(3-4 people) and one person fired back that they liked Icebox. 
I said mostly nothing, only waiting until the three or four people complaining about Icebox had stopped to mention that we were losing Yogsmeta and that Icebox concept would become part of our Meta map(YogsIceMeta? Sounds like a beer?). They either weren't paying attention or didn't care because they said nothing back.

**Comment by ghost** [comment]
My favorite job is shaft miner so understand the bias in this opinion, but I think ice box is a shitty map.

For starters, it's boring for shaft miners because of the slowdown (which yes, can be worked around with boots or an atv). On top of that, the fauna are extremely basic and boring. Wolves deal next to no damage so they're not really a threat. The polar bears move too slow and usually fail to land an attack on you for whatever reason. There are next to no ruins, and the ones that do exist are boring and shit. When it comes to megafauna, there is exactly one. I have yet to build up the tolerance for icebox to play a game long enough to fight this megafauna, called a wondering miner or something, so I can't really say much on him. Still sucks that it's just him though.

Beyond the shaft miner role being butchered when this map is being played, I feel like having a map that's not in space is too distant from what **_SPACE_** station 13 really is at its core. You're limited by the fact that there is no longer space at all, which causes problems for other jobs on the station like engineering. There also are no ghost roles as well, as far as I am aware.

This is just my opinion, and I am sure there are some holes in it, so let me know if I am wrong. I just really do not like playing this map and it really kills my mood when I have the time to log in for a game of SS13 and it's icebox.

**Comment by patpol4** [comment]
> I think ice box is a shitty map.

 me too
> For starters, it's boring for shaft miners because of the slowdown (which yes, can be worked around with boots or an atv). 
>On top of that, the fauna are extremely basic and boring. Wolves deal next to no damage so they're not really a threat. The polar bears move too slow and usually fail to land an attack on you for whatever reason. [...]  When it comes to megafauna, there is exactly one. I have yet to build up the tolerance for icebox to play a game long enough to fight this megafauna, called a wondering miner or something, so I can't really say much on him. Still sucks that it's just him though.

I have hopes getting icemoon going again with this pr will motivate our coders to fix those issues

>There are next to no ruins, and the ones that do exist are boring and shit.

I'm probably maybe hopefully going to work on that

> Beyond the shaft miner role being butchered when this map is being played, I feel like having a map that's not in space is too distant from what **_SPACE_** station 13 really is at its core. You're limited by the fact that there is no longer space at all, which causes problems for other jobs on the station like engineering. 

I think of it as a twist on the classic space theme, the problems can always be resolved

>There also are no ghost roles as well, as far as I am aware.

I'll maybe try working on that as well i think

> This is just my opinion, and I am sure there are some holes in it, so let me know if I am wrong. I just really do not like playing this map and it really kills my mood when I have the time to log in for a game of SS13 and it's icebox.

me too

**Comment by patpol4** [comment]
vivaldi_t9SdpB8ot0
vivaldi_XAoBdexuL5

**Comment by patpol4** [comment]
This should now work on the same level as icebox and maybe a little better. Requesting testmerge.
vivaldi_HwybIzTkof

**Comment by burn1cycle** [comment]
> > It's never voted for, people don't choose it in map preference, and everyone groans and complains in OOC when it comes up in rotation.
> 
> It's not in rotation and disabled in config so you can't even vote for it. It's been that way for some time now


We had a map vote last night this sucker crashed and burned in the vote 20 to 2

**Comment by DiamondSentinel** [comment]
This is the stupidest PR I've ever seen. 

Icebox sucks
Meta is good. 

Removing Meta for Icemeta is a doubly stupid idea.

**Comment by patpol4** [comment]
Currently the only huge issue that we need to solve before a full merge is injectors leaking their gas into the planet's atmosphere and making it entirely unhabitable. That is going to need a code solution, probably chimneys.

**Comment by JamieD1** [comment]
Will work on the issue today or tomorrow

**Comment by patpol4** [comment]
Doesnt look like this is going anywhere without coder help. Closing in a week.

**Comment by patpol4** [comment]
A week has passed

**Comment by patpol4** [comment]
Sad but ok

**Comment by Cartlord** [comment]
TBH Meta is fine, I just wish it had gas miners
If you are going to add a map, I'd like to request it have signs properly set on at least some corners, so newbies can get their bearings without pulling the wiki
Gas miners would be nice (maybe change flavor text to explain them getting the gas from deep beneath the surface) but I guess not necessary

**Comment by UselessTheremin** [comment]
rest in peace icemeta, you were too good for this world...

**Comment by Cartlord** [comment]
> > For starters, it's boring for shaft miners because of the slowdown (which yes, can be worked around with boots or an atv).
> > On top of that, the fauna are extremely basic and boring. Wolves deal next to no damage so they're not really a threat. The polar bears move too slow and usually fail to land an attack on you for whatever reason. [...]  When it comes to megafauna, there is exactly one. I have yet to build up the tolerance for icebox to play a game long enough to fight this megafauna, called a wondering miner or something, so I can't really say much on him. Still sucks that it's just him though.
> 
> I have hopes getting icemoon going again with this pr will motivate our coders to fix those issues

So instead of fixing what's been pointed out as (seemingly) a rather glaring flaw with this map, you're just hoping someone else will care enough to take care of it?
> 
> > There are next to no ruins, and the ones that do exist are boring and shit.
> 
> I'm probably maybe hopefully going to work on that
> 
> > Beyond the shaft miner role being butchered when this map is being played, I feel like having a map that's not in space is too distant from what **_SPACE_** station 13 really is at its core. You're limited by the fact that there is no longer space at all, which causes problems for other jobs on the station like engineering.

This I wholeheartedly agree with, and I imagine it'd also require adjusting some events like meteors or electrical storms to account for the presence of a planetside atmosphere - which I doubt you, or most people, want to bother with.

> > There also are no ghost roles as well, as far as I am aware.
> 
> I'll maybe try working on that as well i think
> 
I hope you do.

**Comment by JamieD1** [comment]
@wejengin2 Can you fix conflicts I am going to try resolve this today.

**Comment by patpol4** [comment]
This now has blueshield levels of momentum and i lost interest,
Going into cold storage.

**Comment by burn1cycle** [comment]
Hell FUCKING NO. 
Meta is our above 40 population map and it's already a hard sell to get people to do it so we're not upping the revulsion of Meta by also making it ice. It's not our "kookie let's have a weird ice map" it exists for the serious and specific reason that Box is too small for +40 persons.

**Comment by burn1cycle** [comment]
Oh. I already said nay. Well it's the same bad idea it was in November

**Comment by Cartlord** [comment]
The external airlock in the maints between the engine room and holodeck has its airlock controller set wrong, it doesn't depressurize or repressurize.

**Comment by Cartlord** [comment]
Played a whole round here, it was weird and I don't know how much was because of the station and how much was because the antags sucked.
We had the space dust event late in, which multiple questioned - we're planetside, why are we getting space dust?
Breaches are laughable. I was able to stand in a room that had two holes - and, therefore, was exposed directly to the exterior - with just roundstart Engineer garb and the stuff that was in my internals box; I was able to _walk outside_, _during a blizzard_, to retrieve the metals from the busted wall - with no real consequence despite my complete lack of protective garb.

**Comment by Darkstick** [comment]
I like this map but I still really wish we could walk at normal speeds there. That slight speed boost feels so weird.

**Comment by Cartlord** [comment]
This feels like you just made MetaStation cold, and completely ignored all the ACTUAL issues people have with Meta.
TComm is still cut off at roundstart.
Atmos still has no access to hazmat suits, meaning turbine tritburns are suicide.
Botany still has barely any room to place looms, barrels, and drying racks.
I want to ask a serious question: why would a player choose this map instead of regular MetaStation? What is improved?

**Comment by patpol4** [comment]
> I want to ask a serious question: why would a player choose this map instead of regular MetaStation? What is improved?

snow

**Comment by Cartlord** [comment]
A good few people seem to view that snow as a DOWNside.

**Comment by patpol4** [comment]
The atmos issues that we had in the beginning remain but they aren't as serious as we thought, people were still able to play on this during the testmerge.
Don't want this sitting in limbo, let's either merge this or close. @yogstation13/head-coders

**Comment by patpol4** [comment]
Seriously @JamieD1 , please either close or merge, i dont really care that much about this project anymore so it can be closed if you don't want it.

**Comment by patpol4** [comment]
blueshield moment

**Comment by JamieD1** [comment]
Will revisit later. When we have more time.

**Comment by N3D6** [comment]
:((

**Pull request closed without merging**
