### PR TITLE
removes the delay from oil slime extracts so xenobiologists blow themselves up

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
image

Now you can't carry a bag full of 0,4,8 explosions, wowie!
Explosion strength isnt enough to gib you, but it will hurt real bad and maybe remove a limb or two.

# Changelog

:cl:  
tweak: oil slime explosions are now instant
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
Why would you grief xenobiologists instead of nerfing this in a sane way

**Comment by Burger1998** [comment]
maybe people will actually use large grenades now(probably not)

**Comment by Simplehorror** [comment]
@TheRyeGuyWhoWillNowDie I'm replacing this interaction with my wallbreakers

**Comment by milk-is-cool** [comment]
> maybe people will actually use large grenades now(probably not)

large grenade casings cant even be printed in sci so thats mostly the problem iirc

**Comment by isotope436** [comment]
this is a terrible way to nerf oil cores espeically because all i have to do now is use clones to make instant unavoidable suicide bombers lol new meta

**Comment by isotope436** [comment]
but yeah no this is a terrible way to go about nerfing oil cores since it basically makes an entire 8 extracts useless outside of trolling in a way thats even more griefy

**Comment by JamieD1** [comment]
> but yeah no this is a terrible way to go about nerfing oil cores since it basically makes an entire 8 extracts useless outside of trolling in a way thats even more griefy

There a better way to nerf it?

**Comment by JamieD1** [comment]
Closing in favour of https://github.com/yogstation13/Yogstation/pull/16805

**Pull request closed without merging**
