### PR TITLE
Moves some UI stuff around

### PR DESCRIPTION
**Pull request by Bibby0110**
# General Documentation

### Intent of your Pull Request

pretty

image

Ports of https://github.com/tgstation/tgstation/pull/57448, https://github.com/tgstation/tgstation/pull/57527 and https://github.com/tgstation/tgstation/pull/57531

Works best with #11129 (Also known as causing a merge conflict)
# Changelog

:cl:  
tweak: Moves stuff around in the UI
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
But why?

**Comment by Bibby0110** [comment]
> But why?

Prettier + neatly organized

**Comment by MegaEmpirical** [comment]
Looks nice.

**Comment by JamieD1** [comment]
Wait? why didnt you just do both in one pr?

**Comment by Bibby0110** [comment]
fuck

**Pull request closed without merging**
