### PR TITLE
Deletes owo accent

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

This is worse than the kawaii script

#### Changelog

:cl:  
rscdel: Deletes weeb accent
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
uwu whats this???????????????????????????????????????????????????????????????

**Comment by ynot01** [comment]
bad pr

**Comment by swissloaf** [comment]
image

**Comment by Hopekz** [comment]
Let people have their fun?

**Comment by monster860** [comment]
if people want to speak in owo
let them
if they want to be lynched
let them

**Comment by swissloaf** [comment]
only degeneracy results from this, yogstation is falling

**Comment by Potototatoh** [comment]
lmao uo sound like orange

**Comment by Mr-Space** [comment]
OWO accent breaks the fucking netspeak rule. I fucking swear to god.

**Comment by alexkar598** [comment]
Let it live for 24h atleast

**Comment by nesisknesis** [comment]
give it to donors

**Comment by deathslayer2481** [comment]
Let clown have it

**Comment by ynot01** [comment]
> Let it live for 24h atleast

nice one asv

**Pull request merged**
