### PR TITLE
Maybe, potentially, hopefully fixes the Vore Panel

### PR DESCRIPTION
**Pull request by Bibby0110**
god i'm tired

### CODE REVIEW

**Comment by ilikesaying** [comment]
is this vore or vote

**Comment by UselessTheremin** [comment]
> is this vore or vote

vore.

**Comment by maxion12345** [comment]
The
What

**Comment by Cartlord** [comment]
wait what

**Comment by SomeguyManperson** [comment]
fix

**Comment by Bibby0110** [comment]
> fix

never

**Comment by JamieD1** [comment]
Gamer to Fix

**Pull request closed without merging**
