### PR TITLE
Ports TG balloon alerts

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Ports balloon alerts from TG

Links:
https://github.com/tgstation/tgstation/pull/59130
https://github.com/tgstation/tgstation/pull/59256
https://github.com/tgstation/tgstation/pull/61035

# Changelog

:cl: Mothblocks, Ghommie, ported by SuperSlayer
rscadd: Ports balloon alerts from TG
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
we need the majority of the bugfixes and tweaks too

**Comment by ghost** [comment]
> we need the majority of the bugfixes and tweaks too

Done

**Comment by Bibby0110** [comment]
> > we need the majority of the bugfixes and tweaks too
> 
> Done

blessed

**Comment by TheRyeGuyWhoWillNowDie** [comment]
idk but i really hate these things, please add a toggle preference or something because the balloon alerts are super distracting imo

**Review by Bibby0110 — APPROVED** [review]

**Comment by Cartlord** [comment]
I would've much preferred a toggle preference.

**Pull request merged**
