### PR TITLE
reworks zombie gamemode

### PR DESCRIPTION
**Pull request by tattax**
if the description sucks too hard i'll update it later

credit to https://github.com/tgstation/tgstation/pull/57084 for mouse_override_icon that is used here
## TODO
- [x] new objectives
- [x] change ui
- [ ] change mutation gain (points for upgrades) depending on feedback and stuff
- [x] fix morph ability

zombie gamemode is kinda slow and underwhelming so i changed it to not be so, hopefully
NORMAL zombies on gamemode can`t infect anymore (up for debate) so the only the SPECIAL (roundstart) ones can infect and gain points for infecting (for objectives and upgrades)

# CLASSES
new classes which are sometimes heavily based on that one valve game and sometimes not
before we get started i need to establish some terms and concepts

THESE CLASSES ARE SUPPOSED TO BE DIFFERENT GAMEPLAY OPTIONS but also still work as a team! (maybe)

DEFAULT ABILITY: An ability that you get on evolve, each class (except brainy) has one, costs points to use and keep it on.

STARTING ABILITY: An ability that classes start with, no costs but has cooldowns.

CLAW PASSIVE: A ability triggered by attacking with claw, be it at range or close quarters.

## Smoker
SMOKERS REGEN INFECTION POINTS AFTER ~5 SECONDS AFTER NOT USING THEIR DEFAULT ABILITY
image
DEFAULT ABILITY: Make smoke in a roughly ~5 tile area around you, costs 10 to activate and constantly costs 5 to maintain.
STARTING ABILITY: Get a damage boost in a 20 burn damage ability to any limb, that mutes on targeting mouth and does eye damage when targeting eyes.
CLAW PASSIVE: Tongue that slips and pulls people closer, till they are one tile next to you. Claw does stamina damage till they are stam critted, then does brute damage.

## Runner
RUNNERS REGEN INFECTION POINTS WHILE WALKING at 1 point every 2 tiles (1/2 p tile)
image
DEFAULT ABILITY: Gain slowdown immunity but become unable to attack during that period.
STARTING ABILITY: Jump over 5 objects that you walk onto.
CLAW PASSIVE: Bleed stacks for a ton of damage when stacks are maxed out.

## Spitter
SPITTERS ALSO NATURALLY REGEN INFECTION POINTS, THOUGH NATURALLY AND ALL THE TIME
image
DEFAULT ABILITY: Spit neurotoxin (You know this one)
STARTING ABILITY:  Micro manageable ability like cursed heart that when micro managed properly boosts your acid regen and cooldowns significantly.
CLAW PASSIVE: Apply acid stacks to any objects you touch. Regens after 30 seconds. Each hand has an acid charge, examine reveals cooldowns.

## Juggernaut
JUGGS REGEN INFECTION POINTS BY TAKING DAMAGE, 1 DAMAGE IS EQUAL TO 1/5 (0,2) (damage/infection_regen) POINTS
image
DEFAULT ABILITY: Change your starting ability into a scarier one.
STARTING ABILITY:  Charge into a living being or a wall, doing great damage and knocking down, breaking down any walls you encounter. | (Charged one) Slam into the ground dealing AOE damage but more on the tile you fell on, basically charge but AOE.
CLAW PASSIVE: Click to toggle between defensive and offensive mode, which changes your speed and damage taken. You get two types of claws, one deals great damage, and opens doors faster, the other one is weak but has good armor pen.

## Brainy
REGENS POINTS JUST LIKE ELDRITCH HORROR, INSIDE HOSTS
image
STARTING ABILITY: Knockdown your target for a while to be able to get inside. | Takeover their mind instantly | Mimic the gun they are holding and hold that in memory for later use | Infect them with the zombie virus from inside

<details>
  <summary> Current UI </summary>
      
image
image
image

</details>

# Spriting

image
image

<details>
  <summary> Abilities </summary>
      
image

</details>

# Wiki Documentation

Not sure if there is a page about this gamemode since it isn`t on rotation but if there is:

add way to infect (alt clicke)
add classes and class sprites (check above sections)
add abilities and upgrades (above)

# Changelog

:cl:  
rscadd: new zombie tgui
rscadd: new classes and changes in zombie gamemode
rscdel: disables the 2nd zombie evolutions, for now  
bugfix: fixes zombie antag IPC not turning into a zombie
imageadd: new zombie sprites and ability sprites to distinguish between them
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
buhbuhbased

**Comment by wonderinghost** [comment]
wait so ipc's can turn into zombies?

**Comment by dukeofnothing** [comment]
I feel like IPCs should remain as not being able to be infected as they have absolutely no organic bits in them, it would make about as much sense as a borg being able to be infected

**Comment by tattax** [comment]
the antag was broken in the sense if you were an IPC ROUNDSTART zombie antag you could not turn. Same case as basically an etheral dspawn hatching

**Comment by tattax** [comment]
IPCs not roundstart zombies still are unable to be infected

**Comment by wonderinghost** [comment]
ipc get a lot of broken antag.  like a couple of times i got converted into a human to then become changeling. so i could be doing something then drop dead becuase i changed into a ling. there is also the problem if you come in mid round and it happens. cause you still got the ipc cooling tank

**Comment by tattax** [comment]
> ipc get a lot of broken antag. like a couple of times i got converted into a human to then become changeling. so i could be doing something then drop dead becuase i changed into a ling. there is also the problem if you come in mid round and it happens. cause you still got the ipc cooling tank

you mean you want me to exclude them from getting the antag then?

**Comment by ChuChu42** [comment]
left 4 dead spess

**Comment by Moltijoe** [comment]
> you mean you want me to exclude them from getting the antag then?

they at least still get resistance to infection from being metal, right?

**Comment by tattax** [comment]
> they at least still get resistance to infection from being metal, right?

as i said:
roundstart zombie IPC, much like a roundstart dspawn Etheral can become a zombie now, because it wouldn't work before.
not roundstart zombie IPC shouldn't happen.

**Comment by Moltijoe** [comment]
> as i said: roundstart zombie IPC, much like a roundstart dspawn Etheral can become a zombie now, because it wouldn't work before. not roundstart zombie IPC shouldn't happen.

Ah, gotcha, wasnt clear what you meant, an IPC can roll becoming the antag round start, but cant be infected by the antag later down the road.

I assumed you meant there was a distinction between this type of zombie and regular midround zombies for IPC infection.

**Review by cuackles — APPROVED** [review]
yeah so everything looks ranging from ok to very good, there are some stuff that look a bit scuffed tho, i would say mostly the most issue i have is the juggerhand wich doesnt really look like a hand or the mace/hand the jugg has, apart from that i only see minor things that dont need to be adressed as of now, maybe in the future yes, but now no, tho something that im wanna know is that if you could put all the mouse pointer dmis into a one singular dmi ?

**Comment by tattax** [comment]
>wanna know is that if you could put all the mouse pointer dmis into a one singular dmi ?

no

**Comment by Moltijoe** [comment]
@tattax this done?

**Comment by tattax** [comment]
> @tattax this done?

actually i tested somethings and i'll ping you when i update it

**Comment by tattax** [comment]
on hold till https://github.com/yogstation13/Yogstation/pull/18514 is merged, as that pr comments out zombie proc holders and other antag stuff that is vital here

**Comment by Bibby0110** [comment]
Stale, reopen when you return

**Pull request closed without merging**
