### PR TITLE
ports infection from tg

### PR DESCRIPTION
**Pull request by SomeguyManperson**
I really need to stop doing this

# Document the changes in your pull request

A new team-based antag, blob 2 to darkspawn's shadowling 2
tgstation/tgstation#45485
Functions similar to the infection event, wherein the crew has to fight against a neigh unstoppable blob that can upgrade itself over time and has an almost inpenetrable core defense, requiring special weapons gained by killing bosses in special attack waves that occur throughout the round.
The crew is defended by a number of beacon generators placed around the station, which prevent the blob's tiles from passing them unless it can kill the generator itself by expanding near it. Killing a generator causes a large explosion which wipes out any blob tiles in a large radius around it and gives the blob and all of its minions an upgrade point. If all the beacon generators are destroyed, the blob wins
The blob additionally starts with several player controlled defenders, which will not permanently die on being killed, instead respawning after some time has passed. More of these can be created if crew corpses are dragged to the blob's core. If no ghosts take control of the new minion, the blob instead gains another upgrade point.

The intended crew response (they get 7 minutes to prepare) is to gather as much weaponry as possible, and retreat vital station resources as the blob encroaches on them. Of course this is yogstation and people will probably start asking why science isn't researching mining tech when they forget to move the science department away from the blob but we can pretend it will work

# Wiki Documentation

to do probably

# Changelog

:cl:  whoneedspacee for the gamemode, Fury McFlurry for sprites, theos for porting and compatability
rscadd: theos adds another new gamemode this time with blobs
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
So it needs a separate map? It doesnt take place on the station?

**Comment by SomeguyManperson** [comment]
> So it needs a separate map? It doesnt take place on the station?

needs landmarks on each map for the location of the blob (spawns further from the arrivals shuttle iirc) the beacons (placed in a rough line throughout the station I think) and the backup gravity generator (placed around the arrivals shuttle area)

**Comment by adamsong** [comment]
What is this bit for?

image

**Comment by SomeguyManperson** [comment]
> What is this bit for?
> 
> image

Starting area for the infestation that crashes into the station after four and a half minutes
The crew isnt meant to instantly be able to game the core so it starts off with a bunch of defenses

**Comment by KittyNoodle** [comment]
slime healing needs to be increased massively

**Comment by KittyNoodle** [comment]
maybe shuttles shouldn't be able to be called a la meteor

**Comment by ghost** [comment]
1. Weapons + tools such need tool tips

2. The unique sword should proc on the destruction of structures (?)

3. Maybe more time should be given to crew, Nukies for example has around 20 minutes to prepare. 10 minutes itself should be enough to move stuff/prep.

**Comment by nmajask** [comment]
Should make them ghost visible antags for observer QoL

**Comment by TheLinuxOS** [comment]
Add a way for the infection to jump to its slimes cause it’s annoying trying to figure out where they are when they want you to do something

**Comment by Notamaniac** [comment]
Personal feedback from just observing

1. There needs to be damage sprites on strong walls and nodes so that crew know what node is being focused on without having to shift click on them. Strong walls also seem very, very strong requiring several laser guns worth of accurate firepower to take down.  And it's very hard to be accurate with the amount of clutter and mobs on the screen. The health either needs to be lowered, or it needs to be more cost prohibitive to put up strong walls.

2. The explosion from the beacons causes a breach. Since no one wants to remove monstermos, this rapidly creates inhospitable areas. While the infection tiles themselves have normal atmos, breached areas can rapidly kill anyone without a suit on, and can prevent them from reaching the actual fight until the infection has gotten a good foothold in the area. Basically the explosion needs to be weakened so it no longer breaches.

3. Legendary weapons also need a big glowing visual indicator that they're on the ground and that someone is wielding one, and possibly should be increased in size to bulky so they can't be stuffed into backpacks and forgotten about. The spinel tonic should probably also be changed into something that drops on death, so if the person who uses it does die, someone else can pick it up and use it.  While the GPS signal is fine for locating a legendary weapon, no one but miners and paramedics carries a GPS by default. The round is often going to be far too hectic to print off a GPS, especially since R&D might get taken out. 

4. While the drops from infection mobs are a nice idea, the only immediately useful ones are the laser gun and drill. Magboots and insulated gloves may be good for utility, but they don't immediately help a crewmember. Something like an infection material dropping that can be quickly crafted into medium grade armour and autoinjectors with bicard/kelo/tricord/regenjelly/omnizine/somesuperweakhealingchem  which can help sustain crew in a fight without having to limp all the way back to medbay for treatment, or rely on medibots that will eventually murder their eyes/liver (especially since those first aid kits are going to run out quickly, and chem might be incompetent/missing/busy making hellfoam or other useless stuff). A loot table with weighted loot might also need to be implemented, so that the crew doesn't end up suffocating on auto injectors and the like. Maybe consider removing credits too, and instead make infection material sellable for a certain amount of credits.

5. It ends up being a meatgrinder fest. Maybe the infection could give unique departmental equipment (or some kind of infection material that can be used to upgrade stuff), so that it doesn't force everyone to charge and die to the blob, and give some better backline logistics work to do. Maybe a unique bounty could be posted to cargo, selling unique infection drops, and in turn centcom will start selling higher tier weaponry? Maybe med bays surgical tools could be upgraded so that they can heal people in the field. Maybe chem could use infection material or drops to make more powerful chems? This might be a lot of work though, but it might encourage people who don't want to fight (or are just simply unrobust) to at least do something vaguely productive.

**Comment by Absolucy** [comment]
please make it so i can select "never for the round" for the ghost prompts

**Comment by BobTheButton** [comment]
I think the crew needs some more time

**Comment by Notamaniac** [comment]
Not sure if this is balance or not but it seems that mobs made by doom events don't have access to infection radio, so it's hard to coordinate or respond to critical threats, especially if the area has been made into a vacuum so you can't even talk.

**Comment by Whoneedspacee** [comment]
I'm gonna be honest with you this is basically unfinished and thats why the pr was closed you're definitely gonna need to do a lot of work to make it viable.

A lot of this was done before I was decent at designing anything on ss13 so the base of it is a bit funky and outdated as well. If you guys merge the mob abilities pr that I made recently it'd probably make it easier to make specific abilities to grant to infection slimes.

Major issues with the game were that beacons don't do their job properly (slow down the game so that people focus on research) and are annoying / confusing for the infection to destroy for the most part, defeating slimes doesn't feel rewarding at all and mores feels like beating a brick wall, and the infection is just generally overpowered against normal crew and legendaries are overpowered against the infection. 

Being a normal crew member is basically so boring people would kill themselves to become a slime, and often admins would be forced to call in ERT's and such to prevent the infection from curbstomping the crew.

There's multiple ways to solve these problems, though it's quite impressive that you managed to bring it to a workable state so that's really impressive, hope you can take it where I could not.

**Comment by bruhlookatthisdood** [comment]
When will this be Testmerged?

**Comment by nmajask** [comment]
> When will this be Testmerged?

Judging by the fact that the last commit was 2 months ago and the creator left the server, probably not any time soon.

**Comment by ghost** [comment]
Is it still alive?

**Comment by bruhlookatthisdood** [comment]
no
sadly

**Comment by ghost** [comment]
Okay now it is my time to try to revive this gamemode, while having minimal knowledge in ss13 code.

**Comment by ghost** [comment]
> Okay now it is my time to try to revive this gamemode, while having minimal knowledge in ss13 code.

Okay i failed with it, i hope someone else will try to revive it again

**Comment by bruhlookatthisdood** [comment]
it finnaly happened
he finnaly let it rest

**Pull request closed without merging**
