### PR TITLE
Removes Pyroclastic Anomaly as its just pain for our atmos system

### PR DESCRIPTION
**Pull request by JamieD1**
Removes Pyroclastic Anomaly as its just pain for our atmos system
:cl:  
rscdel: Removes Pyroclastic Anomaly as its just pain for our atmos system
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
a widdle tiny plasmafire is a pain on our system? I'm surprised our atmos works at all then, if a single anomaly is such a pain. don't like this change at all

**Comment by JamieD1** [comment]
> a widdle tiny plasmafire is a pain on our system? I'm surprised our atmos works at all then, if a single anomaly is such a pain. don't like this change at all

It makes every room nearby unusable for 20 years. Because of the shitty way our temp system works

**Review by Bibby0110 — APPROVED** [review]

**Comment by Marmio64** [comment]
We're down to like 2 anomalies now...

**Comment by JamieD1** [comment]
it will be added back when auxmos is merged

**Comment by ShoziOffical** [comment]
> > a widdle tiny plasmafire is a pain on our system? I'm surprised our atmos works at all then, if a single anomaly is such a pain. don't like this change at all
> 
> It makes every room nearby unusable for 20 years. Because of the shitty way our temp system works

It can easily be fixed by just spacing the room (technically, the room would already be spaced by the fire) and refill it with a new fresh air

**Pull request merged**
