### PR TITLE
Adds a "Probabilistic Anomaly" event

### PR DESCRIPTION
**Pull request by Altoids1**
## Ling's biggest gripe about NTSL, made into a random event

The gimmick of this event is that it forces the seed of the randon number generator to be stuck on a certain value, which causes the same numbers to be generated over and over. 

This could result in anything from, say:
- The emitters not shooting enough lasers to keep the SM going or the singulo contained (although the latter would only realistically occur if there was barely enough containment already, which is not by default really the case)
- Arcade machines always outputting the same reward
- Disarms always not working, or always working
Etc, etc, etc.

#### Changelog

:cl: Altoids
rscadd: New random event, "Probabilistic Anomaly," in which RNGesus gives up and moves to Mount Fuji.
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
It should last a lot longer than just a minute or so IMO, 90 seconds could pass without anyone realizing what it changed.

**Review by monster860 — APPROVED** [review]
There is absolutely no way at all in any possible way this could go wrong in any way whatsoever.

**Comment by alexkar598** [comment]
Make it last like 10 minutes

**Comment by ThatLing** [comment]
BIGGEST GRIPE WHY DO YOU ALWAYS HUMILIATE ME IN YOUR PRS FUCK OFFFFFFFF

**Comment by ThatLing** [comment]
ALSO THIS IS A GREAT EVENT THANKS FOR THE CONTRIBUTION ALTOIDS

**Review by ThatLing — APPROVED** [review]

**Comment by Firewolf34** [comment]
This is a really cool concept. _META_

**Pull request merged**
