### PR TITLE
Revert "[MIRROR] Removes stun and item drop from all slips. They will…

### PR DESCRIPTION
**Pull request by Jc1469**
_… instead knock people down (force crawling) for their duration."_

Interestingly, this worked just being outright reverted despite being a PR from a good while ago.
+fun
+pile of people slipping AND NOT MOVING AROUND WHEN SLIPPED
+clown buff

learn to walk instead of being a little bitch kevinz

#### Changelog

:cl:  
bugfix: You now slip and bang your head on the floor and get stunned when you slip, as intended.
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
image

**Review by monster860 — CHANGES_REQUESTED** [review]
While I agree with this I'd prefer if it was modularized just a bit with some //yogs tags

**Comment by oklews** [comment]
A hero, a goddamn hero

**Review by ThatLing — CHANGES_REQUESTED** [review]
Laziest modularized PR I have ever seen

**Comment by Amelia0010** [comment]
Your PR is bad and you should feel bad.

**Comment by Alexandria404** [comment]
VERY NICE

**Comment by Jc1469** [comment]
> Laziest modularized PR I have ever seen

hey man. its a lot of effort to put // yogs after every single line of code that was changed.

**Review by oklews — COMMENTED** [review]
We actually doing the lube slide? Unless I am stupid, didn’t this nerf the lube to a one tile slide? (Trying to learn the code, so there is a fat chance I am wrong here)

**Comment by Jc1469** [comment]
I tested it and it seemed like it was 4-5-ish tiles, not sure if it extends per lube tile, but I doubt it.   Not full hallway though.  Ice slips you til the end of the line of ice though.

**Comment by oklews** [comment]
Regardless of the lube slide possibly, I NEED this back in my life, the greytide’s time proven defense against security is back

**Comment by Jc1469** [comment]
see what you did now. you made me actually get git out.  and now its being a bitch

**Comment by Jc1469** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/4890

**Pull request closed without merging**
