### PR TITLE
vxtvul now respects pronouns

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

asdo

# Changelog

:cl:  
spellcheck: vxtvul hammer now respects your pronouns
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
joe many liberals?

**Review by Moltijoe — APPROVED** [review]
their works in pretty much every situation, but i guess this is more correct

**Comment by iamthesilly** [comment]
based and vxtrin-pilled

**Comment by MajManatee** [comment]
weird but ok

**Pull request merged**
