### PR TITLE
Gamma alert is no longer aurora alert

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Adds more events to spawning on ~~aurora~~ gamma alert and higher

# Changelog

:cl:  
tweak: tweaked the events that can spawn on gamma alert and higher
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
innocent newline remorselessly murdered

**Comment by adamsong** [comment]
> innocent newline remorselessly murdered

Added

**Comment by KittyNoodle** [comment]
No its funny

**Comment by Altoids1** [comment]
I like most of this, but keep the aurora. Aurora popping off moments before the station detonates is funny, actually.

**Comment by adamsong** [comment]
> I like most of this, but keep the aurora. Aurora popping off moments before the station detonates is funny, actually.

Aurora can still trigger, its just not only aurora

**Review by ToasterBiome — APPROVED** [review]

**Comment by JamieD1** [comment]
Not sure about the ion law. Considering that can really fuck up a round if it gets a wacky lawset and it will be alot higher chance of happening or multiple.

**Comment by JamieD1** [comment]
See above

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
