### PR TITLE
[Asteroid] Gives power to camera and exhaust port outside ai sat maint

### LINKED ISSUE #17698: i dont think this is meant to be off
## Test Merges: 
Not Supplied / None
## Reproduction:
description: ai sat waste ejector isnt in a powered area so it doesnt work
## Supplied Image:

SuppliedImage
 Submitted by: zealot (343805692710486017)

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

fixes #17698 

# Changelog

:cl:  
bugfix: Sets machinery outside ai sat maint to a powered area
/:cl:

### CODE REVIEW

**Review by patpol4 — APPROVED** [review]

**Comment by patpol4** [comment]
Just out of curiosity, what map editor did you use for this?

**Comment by Aquizit** [comment]
The fastdmm2 thing why?

**Comment by patpol4** [comment]
Trying to determine what is causing all those spaces

**Comment by MajManatee** [comment]
Spaces are good. Imagine not liking readability.

**Pull request merged**
