### PR TITLE
[[Hug-]Box] Kills Off Quarter-Tile Decals* & Cargo/Robotics/Telecomms Changes

### LINKED ISSUE #14887: Warden's disposal bin breaks if you put anything on it.
### Severity

Inconvenience

### Short Description

Title says it all.

### Reproduction

1. Be warden.
2. Put paper on bin.
3. Watch the pipe right in front of Perma's entrance burst.
dreamseeker_m5UzQK20ez

### Round ID

41900

### Test Merges

#14466, #14582

### BYOND Username

Andrymeda

### Additional information

It happened twice in the round, as the warden dog got thrown into the bin after a Cluwne skill issue'd me and burst the pipe as well.

### PR DESCRIPTION
**Pull request by VaelophisNyx**
I figured if I'm touching this much of the station, why bother atomizing it?-

closes #14887

# Document the changes in your pull request

ss (2022-07-23 at 02 24 20)
ss (2022-07-23 at 02 24 28)
ss (2022-07-23 at 02 28 38)
ss (2022-07-27 at 06 10 56)
ss (2022-07-27 at 06 10 44)
ss (2022-07-27 at 06 08 32)

notable changes: 
HoP Line now has an arrow indicator line, and uses dark flooring so it and the now-white markers pop a bit better. Might help communicate to newcomers which direction the line flows in.

the telecomms hardware workshop now has dark carpeting instead of the old grimey tiles. Looks better imo, though could be swapped back if for some reason grimey floors fit it better

Telecomms maintenance now uses normal plating instead of dark plating, with the formerly bright white tiles in the top right being dark tiles now. Kills off the pipe dispenser as RPDs exist and are easy for a telecomm agent to acquire, and excessive lack of use doesn't warrant there being one in telecomms. it is replaced with a modular PC vendor.

Telecomms itself is now wired to the gird properly round-start, and has had the pipes and wires moved off the wall tiles and instead now goes under the floor through the airlock. The AAS is now located in telecoms maint.

some decals were stacked to attempt to achieve a specific color in the telecomms server room, to distinguish command and medical.

kills quarter-tile decals everywhere they weren't used to fully recolor a floor. There's...too much to talk about. I would if it wouldn't be 4 paragraphs long.

Cargo now has a shutter button and a new conveyor for moving crates and such into the lobby without opening the door for Tider John to sprint through to get to the lathe. Deliveries also has shutters and a button for them, as well as the QM office, who also gets buttons for the cargo and delivery office shutters

Robotics got a makeover, now having a little more workable room, as well as looking a bit better. Changes made as per suggestion from a very well respected roboticist player. Also gave them shutters for the mechbay and moved the lobby shutters so you can still come in to use the laptop vendor if robotics goes turbo-hermit.

Replaced carpets in Arrivals, HoP office, Captain's Office, RD office, and the Psych office, so they don't look as ugly (we really need new carpet sprites)

Moves all hallway firelocks so they are on the same tile as their counterparts, instead of multiple instances where they were spaced out two tiles.

Adds firelocks to many more internal windows, anywhere that they'd otherwise cause depressurization or fire spread if a window had broken.

Engineering now has blast doors near the SMESes and Gravity Generator that close with Lockdown.

# Changelog

:cl:  
tweak: added modular PC vendor to telecomms maintenance
tweak: added a fire safety closet to telecomms maintenance
tweak: removed pipe dispenser from telecomms maintenance
tweak: replaced every quarter-tile square decal with a line decal of the same or similar color station-wide, except where used to recolor a floor tile.
tweak: did some interior decoration changes to telecomms, captain's office, HoP office, CE office, Arrivals, and the Psych office
tweak: adjusts and redecorates Robotics. Should be more roomy and modern.
tweak: makes adjustments to cargo, including shutters, an outgoing delivery conveyor, and adjustments to the shuttle unload conveyor belt.
tweak: adds new firelocks at the north end of the aux-base assembly hallway
tweak: adds firelocks to tons of windows
tweak: engineering lockdown now closes blast doors to the gravgen/SMES area.
tweak: added public-access doors to Cargo's lobby, and the north end of the security access hallway
tweak: adds a door to the nanite lab that requires research access
tweak: the CE locker now contains a spray bottle of Rad Scrub Plus
bugfix: fixes the warden's perma-deliveries disposal piping. You can now give those SSD prisoners something to do.
bugfix: wires the telecomms SMES up properly so it can charge from the grid without engineering intervention
bugfix: fixes single missing distro pipe in front of the morgue in medbay's inner hallway
/:cl:

### CODE REVIEW

**Comment by GraveHat** [comment]
My only gripe is this part 
image
not matching this part 
image
making it asymmetrical. 
image

I insist you try and check out if symmetry would look better on the hopline if it's even possible.

**Comment by redmoogle** [comment]
My only gripe is that now the telecomms maint floor looks kinda weird but it doesnt bother me much

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
I would prefer the trim all the way around if we're gonna do it, look at GaxStation for reference

**Comment by VaelophisNyx** [comment]
oh, alright! I was just emulating how it was on the off-chance you wanted it the way it was

**Comment by VaelophisNyx** [comment]
Changes made as requested

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image

**Comment by VaelophisNyx** [comment]
That was actually already covered-
I just noticed after tanking the screenshot

**Comment by VaelophisNyx** [comment]
Will handle the merge conflict tomorrow.

**Comment by VaelophisNyx** [comment]
actually I'll hold off on this until the donkpocket spawner change goes through

**Comment by JamieD1** [comment]
Ugh, so much unnecessary decals though

**Comment by VaelophisNyx** [comment]
technically this is reducing the # of decals, by using the better looking and more efficient line decals.

**Comment by VaelophisNyx** [comment]
Spent six hours on this 💀

**Comment by Spacemanspark** [comment]
Glorious

**Comment by JamieD1** [comment]
Arrivals has way way too much in it, we dont need to white one everywhere also we dont need the eva one in the sec hallway, also the sec one on the lower half, please just reduce the unnecessary ones.

**Comment by VaelophisNyx** [comment]
lot of decals removed, EVA hallway fully sec colored now
also nuked a bunch of quarter-tiles under the SMESes and Gravgen, replacing them with single full-tile decals that perform the same function but in a quarter the amount of decals

check mapdiff raw's

**Comment by Hopekz** [comment]
No hidden pulse rifle under flooring -1

**Comment by VaelophisNyx** [comment]
stop merging tiny, new, map PRs please. I beg you.

**Pull request closed without merging**
