### PR TITLE
Gives miners 1 jaunter at round start (in locker)

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

Should I have made this 2 weeks ago? Yes. But I was dumb and forgot I knew how to do locker things.

I feel like this is the compromise between people who want to keep their chasm and people who don't want to punish people for not knowing where chasms may appear (if new) or if you lag into one. To note I am in the second camp.

One free get out of jail card. If you lose the first one and don't get a second and fall in another chasm, well that's on you, buddy.

If people like this -- can revert #17340 and close #17685 

# Changelog

:cl:  
tweak: Miners get a jaunter in their locker
experimental: If people like this chasms can come back
/:cl:

### CODE REVIEW

**Comment by Aquizit** [comment]
I am perfectly willing to have this closed if the judgment is "nope shoulda said something when the first PR was open."

**Comment by patpol4** [comment]
This is better

**Review by MajManatee — APPROVED** [review]
we ALL shoulda thought bout this before. Bring back chasams

**Comment by patpol4** [comment]
@Aquizit i guess you can try a revert now

**Pull request merged**
