### PR TITLE
Just removes beam rifles

### PR DESCRIPTION
**Pull request by Sniblet**
# Document the changes in your pull request

The laser anti-material gun is used for nothing except BTFOing blobs and they are far too excellent at it, they're basically uncounterable if the wielder knows to keep their distance
I am not intelligent enough to rework them in a way that doesn't, according to sec mains, make them useless
Therefore, the alternative to a [big nerf](https://github.com/yogstation13/Yogstation/pull/13099): just remove them

# Wiki Documentation

Just remove them

# Changelog

:cl:  
tweak: The Centcom prototype documents for particle accelerator rifles have mysteriously decayed due to an unidentified fungal growth
tweak: Special thanks to blob overmind (49) for the code, rest in peace my man
/:cl:

### CODE REVIEW

**Comment by Georgeur** [comment]
ya
theyre even too powerful to be used in conjunction with fighting other crew members, the friendly fire is unavoidable when fighting anything other than a actual tile.

**Comment by KillerOrcaCora** [comment]
Only practical use is deleting blob from the game get this trash outta here

**Comment by ToasterBiome** [comment]
cry?

**Comment by Sniblet** [comment]
I'm a bad coder, hold on

**Pull request closed without merging**
