### PR TITLE
Adds the plasmaman security envirosuit and helmet to the SecDrobe

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

I AM SO TIRED OF THIS BURNING OFF OR LOSING THE HELMET

# Why is this good for the game?

IT MAKES ME HAPPY

# Testing

NO

# Wiki Documentation

WIKI THIS

# Changelog

:cl:  
rscadd: Added Sec Plasmaman stuff to the SecDrobe
/:cl:

### CODE REVIEW

**Comment by LassiH** [comment]
every ipc security officer getting welding immunity with this one

**Comment by ShoziOffical** [comment]
im going to get drippy with this one

**Review by MajManatee — CHANGES_REQUESTED** [review]
image

**Comment by Moltijoe** [comment]
image
it works

**Review by Moltijoe — APPROVED** [review]

**Review by SapphicOverload — APPROVED** [review]

**Review by MajManatee — APPROVED** [review]
mmm i love testing

**Pull request merged**
