### PR TITLE
Secbelt + shotgun shell boxes rework, shoulder holster and bandolier buff

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Makes sec belts bulky again at the trade-off of being able to hold rubbershot, lethalshot, breacherslug, and beanbag ammo boxes. Each of these shotgun ammo boxes can now only hold shotgun shells. Secbelts can also now hold telescopic shields.

Also buffs sec webbing and hoS belt to hold 7 items. For clarification, secbelts can currently hold 6 items as well. The HoS' extra slot spawns with a teleshield, moved into it from the locker. The HoS now begins with their belt but does not spawn with the extra baton, flash, or cuffs. They're instead found in the locker.

Also also makes the shoulder holster normal-sized again as it unintentionally called the parent bulky size of belts, when it barely gives an inventory advantage.

Also also also makes the bandolier able to hold 24 shells as a bit of a makeup for the fact that secbelts can hold significantly more shotgun ammo now.

Also also also also the assault belt from the SWAT crate is now identical to the tactical webbing that Syndicates get.

Very minor change but the beanbag boxes are full now instead of having one slot missing.

# Wiki Documentation

Secbelt and all variants can now hold shotgun shell boxes and teleshields
Shotgun shell boxes can now only hold shotgun shells (doesn't have to be matching type)
Security webbing and HoS belt can hold 7 items now, instead of 6
HoS belt starts with the locker's teleshield in it
HoS spawns with their belt on, moves extra baton/flash/cuffs to locker
Assault belt now identical to tactical webbing
Shoulder holster is normal-sized again, still only holds 3 items
Bandolier can now hold 24 shells, instead of 18

# Changelog

:cl:  
tweak: Secbelt + variants can hold shotgun shell boxes and teleshields, bulky now.
tweak: Shotgun shell boxes can now only carry shotgun shells.
tweak: Beanbag boxes spawn with 7 beanbags, rather than 6.
tweak: Security webbing and HoS belt storage buffed.
tweak: HoS now spawns with their belt and teleshield from the locker, extra baton/flash/cuffs moved to locker.
tweak: Assault belt now identical to tactical webbing.
tweak: Shoulder holster normal-sized again.
tweak: Bandolier holds more shells.
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
how many batons can it carry now
asking for a friend

**Comment by Skrem7** [comment]
> how many batons can it carry now asking for a friend

Secbelt? 6, like before. Webbing should fit NINE now

None of the sec belt variants care about weight afaik

**Comment by 00ze-cyclone** [comment]
I don't think secbelts should fit the shotgun shells boxes because:
1. They can actually accept other things than shotgun shells so now the basic secbelt can fit pretty much any small item and in large amount
2. Even if we decided to make those box not accept things that aren't shotgun shells there's still the issue that now with 3 boxes inside a secbelt you can carry 21 shells (bandolier only allow you to carry 18) while still having room for more stuff.

The rest of the changes are fine but letting the secbelt hold boxes is way too strong.

**Comment by Skrem7** [comment]
> I don't think secbelts should fit the shotgun shells boxes because:
> 
> 1. They can actually accept other things than shotgun shells so now the basic secbelt can fit pretty much any small item and in large amount
> 2. Even if we decided to make those box not accept things that aren't shotgun shells there's still the issue that now with 3 boxes inside a secbelt you can carry 21 shells (bandolier only allow you to carry 18) while still having room for more stuff.
> 
> The rest of the changes are fine but letting the secbelt hold boxes is way too strong.

1) Could be hard-coded to only hold any kind of shotgun shell, which is probably the best idea tbh.

2) The primary difference between holding a box and a raw shell is hotkeys. Bandolier excels because of its SHIFT+E potential to quickly reload a shotgun. This cannot be done with a box. This also brings the secbelt further in line with other belts which allow you to store SEVERAL other containers, such as construction bags on toolbelts or pill bottles on medbelts (before chemistry bag got rightfully nerfed).

I'm not quite sure what you want to give secbelts to accommodate them being bulky because the primary reason they were glossed over in the PR that made all belts bulky is because they simply didn't hold that much relative to other belts.

**Comment by nmajask** [comment]
> 1) Could be hard-coded to only hold any kind of shotgun shell, which is probably the best idea

Could make it stack the shells like ore bags/chemistry bags, or add a new bag that can only hold ammo if you want to do something crazy

**Comment by Skrem7** [comment]
> Could make it stack the shells like ore bags/chemistry bags, or add a new bag that can only hold ammo if you want to do something crazy

Issue is as soon as you get some bag or container that can more effectively hold ammunition then you bypass one major issue with ballistics, which is holding onto ammunition. This already toes the line just a little with that, but the boxes are few and far between, and trying to store shotgun shells is absurdly difficult relative to any other weapon. If secbelts themselves could stack the shells, that'd be another thing, but that also encroaches on the bandolier then, when this is already establishing bulk over convenience.

**Review by JamieD1 — APPROVED** [review]

**Comment by Hopekz** [comment]
> I don't think secbelts should fit the shotgun shells boxes because:

In a perfect world, we'd have a handful of shells like on CM vs a box but no-one has made that here yet

**Pull request merged**
