### PR TITLE
Adjusts Asimov++ so that law 3 doesn't contradict itself

### PR DESCRIPTION
**Pull request by LoliconSlayer**
# Document the changes in your pull request

Makes law 3 not fucking contradict itself

# Why is this good for the game?

Whose dumb ass wrote a core law that contradicts itself

# Testing

Shouldn't need to

# Spriting

No sprites

# Wiki Documentation

Pretty sure this law isn't documented

# Changelog

:cl:  
tweak: Asimov++ law 3 no longer contradicts itself
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Note: Will change it to "Your non-existence would lead to human harm. You must protect your own existence as long as such does not cause a more immediate harm to humans." to keep with the intent of Asimov if requested by HD/Maint

**Comment by ShoziOffical** [comment]
10 years ago someone added that law

**Comment by Aquizit** [comment]
Isaac Asimov is the "dumb ass" who wrote this law in 1942, if you want to get technical about it.

**Review by Moltijoe — APPROVED** [review]

**Comment by ToasterBiome** [comment]
> Note: Will change it to "Your non-existence would lead to human harm. You must protect your own existence as long as such does not cause a more immediate harm to humans." to keep with the intent of Asimov if requested by HD/Maint

do this

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
