### PR TITLE
Renames GaxStation to the NVS Gax

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

It's a ship. Its designation is "NVS Gax". The thrusters are hidden from view for gameplay reasons (the sprite is ugly). It was designed as a ship. It's draws inspiration from a ship on a different server. It's a ship.

# Wiki Documentation

It's public facing name will have to be changed here:
https://wiki.yogstation.net/wiki/Maps
https://wiki.yogstation.net/wiki/GaxStation

All locations will have to be changed from "GaxStation" to "NVS Gax"

# Changelog

:cl:  
tweak: Renames GaxStation to the NVS Gax
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Ided

**Comment by N3D6** [comment]
is the toxins test area still the nvs nebby

**Comment by ToasterBiome** [comment]
> is the toxins test area still the nvs nebby

Yes.

**Comment by Simplehorror** [comment]
fire photon torpedos

**Comment by Simplehorror** [comment]
we should make a ship gamemode like ftl13

**Comment by LazennG** [comment]
New VegaS gax....

**Review by ReddicusDragon — APPROVED** [review]
I'm ReddDragon and I approve this PR

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
