### PR TITLE
Adds new 10x10 Maint Ruin

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

A new 10x10 ruin containing some loot, and a coin press, and featuring some false walls

loot is as such:

ss (2022-08-22 at 09 11 21)
6x Gold Coin & functional coin press

Real Insulated Gloves, A pAI card, an eyepatch, a cheap lighter, and one Laser Pointer (Blue)
ss (2022-08-22 at 09 11 40)

the usual contents of a personal wardrobe, 5x random lipstick, an electric razor, true-random bedsheet, and two bottles of hair dye
ss (2022-08-22 at 09 12 25)

1x hydroponics crate with everything needed to set up one apiary, one empty crate, a multitool, 4x contraband posters, a Flash Dark, one single Bandage (Callback to dead content), and a fake item spawner
ss (2022-08-22 at 09 13 11)

false walls shown
ss (2022-08-22 at 09 01 17)

false walls hidden
ss (2022-08-22 at 09 01 29)

# Changelog

:cl:  
rscadd: Adds a new 10x10 Maint Ruin
/:cl:

### CODE REVIEW

**Comment by GraveHat** [comment]
The second most stacked ruin next to the other 10x10 with the atmos holofan, although I think the insuls might be a little too much.

**Comment by VaelophisNyx** [comment]
wouldn't be the first time real insulated gloves were in maint

**Comment by GraveHat** [comment]
> wouldn't be the first time real insulated gloves were in maint

I mean in terms of there's a lot of useful things here already, the sus puppy ruin just had the glove.

**Comment by JamieD1** [comment]
It feels like 4 3x3 maint rooms stuck together, but sure, just feel its a bit boring.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
