### PR TITLE
Ports Bees supermatter delam effects and sprite

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request

Ports https://github.com/BeeStation/BeeStation-Hornet/pull/9438
Also ports the sprite:
image

Video is Bees, but should look roughly the same for us.

https://github.com/yogstation13/Yogstation/assets/42524344/119b075a-7caa-4e6d-ab3d-b5d0693c0a59

# Why is this good for the game?
supermatter is EXOTIC@!@!@!

# Testing
works, i think atleast

# Spriting
image

# Changelog
:cl:  
tweak: Supermatter is awesome now (visual upgrade)
imageadd: New SM sprite
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
Currently, for some reason its way more visible than bees, looks cool still but way more, and it seems to not be destroying properly.

**Comment by ToasterBiome** [comment]
Talking with Cuackles about this. We previously declined the new sprite that other servers use because it’s very big.

**Comment by ShoziOffical** [comment]
You need to update the supermatter crystal building sprites as well

**Comment by ShoziOffical** [comment]
see `/obj/structure/supermatter_base_structure`

**Comment by RG4ORDR** [comment]
NO THE CANDY ROCK RETURNS.
I will use SOUL for this - I love the gross little SM sprite we have.

**Comment by azzzertyy** [comment]
> NO THE CANDY ROCK RETURNS. I will use SOUL for this - I love the gross little SM sprite we have.

average "muh soul" comment

**Comment by RG4ORDR** [comment]
> > NO THE CANDY ROCK RETURNS. I will use SOUL for this - I love the gross little SM sprite we have.
> 
> average "muh soul" comment

It's so delightfully shitty

**Comment by ShoziOffical** [comment]
image
so are you gonna tell someone to resprite this because you deleted them both

**Comment by ShoziOffical** [comment]
and this 
image
change the layer

**Comment by azzzertyy** [comment]
> image so are you gonna tell someone to resprite this because you deleted them both

woops

**Comment by ShoziOffical** [comment]
just seperate the pr

**Comment by ShoziOffical** [comment]
the effects are cool but i dont like the sprite its out of place and too big when you try to click the tile north of sm and not dusting yourself for doing it

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
i like the effects can we have the old sprite tho

**Comment by azzzertyy** [comment]
> i like the effects can we have the old sprite tho

i added sprite in this pr because it looks like shit with our sprite but ill seperate it so you can see how shit it looks with our sprite

**Comment by ToasterBiome** [comment]
> > i like the effects can we have the old sprite tho
> 
> i added sprite in this pr because it looks like shit with our sprite but ill seperate it so you can see how shit it looks with our sprite

thanks

**Comment by ToasterBiome** [comment]
Reopen when work continues

**Pull request closed without merging**
