### PR TITLE
10x5 Ballpit Random Maint

### PR DESCRIPTION
**Pull request by alao3alao3**
Ballpit, now with less maint corpses.
apng
No more playing minewsweeper for an hour and only getting like 3 tiles.

:cl:  
rscadd: maint ballpit
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
the pr we needed

**Comment by patpol4** [comment]
Cute, i suggest adding vomit to the pool if you want realism

**Review by jcatjmeow — CHANGES_REQUESTED** [review]
ballpit tiles are ugly as sin
image
Look at this it's gross

**Comment by jcatjmeow** [comment]
To be clear I'm aware that u didn't make the sprite and it's not your fault but maybe we should give this a resprite after this is merged or before idk

**Review by patpol4 — CHANGES_REQUESTED** [review]
You have to add this to 
/yogstation/code/datums/ruins/station.dm and /yogstation/code/game/objects/effects/landmarks.dm , 
also place it in the correct directory.

If you don't want to mess with this just send the file to me, close the pr and I'll add it bundled with other random maint submissions

**Comment by patpol4** [comment]
User sent me files so i Pr them in bulk, closing

**Pull request closed without merging**
