### PR TITLE
Adds the song Glorious Morning from the Flash Game Golden Age to the Jukebox

### PR DESCRIPTION
**Pull request by fluffe9911**
Its a good song https://www.youtube.com/watch?v=7T_YtklLyyo
:cl:  
soundadd: New Jukebox song Glorious Morning!
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
IT'S NOT JUST FROM AGE OF EMPIRES YOU PHILISTINE, IT'S THE ANTHEM OF FLASH GAMING AND YOU WILL RESPECT IT AS SUCH

**Comment by fluffe9911** [comment]
> IT'S NOT JUST FROM AGE OF EMPIRES YOU PHILISTINE, IT'S THE ANTHEM OF FLASH GAMING AND YOU WILL RESPECT IT AS SUCH

Fixed

**Comment by maxion12345** [comment]
how much more do you think you could compress it

**Comment by fluffe9911** [comment]
> how much more do you think you could compress it

Probably not that much

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
