### PR TITLE
adds an out-of-bounds onion to the city of cogs

### PR DESCRIPTION
**Pull request by athena413**
#### Read our contributing.md if you haven't already: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# General Documentation

### Intent of your Pull Request

idk how it got there it just did

image

### Why is this change good for the game?

funny

# Wiki Documentation

no new documentation wanted or needed

# Changelog

:cl:  
rscadd: a very robust onion managed to get outside of the city of cogs
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
i would like this but theres literally already a player reference to jarod, in the clockwork maint template. i feel as if this is a bit overboard tbh

**Comment by Hopekz** [comment]
> i would like this but theres literally already a player reference to jarod, in the clockwork maint template. i feel as if this is a bit overboard tbh

Yes because Jarod is the owner of all things onion related

**Comment by swissloaf** [comment]
"why the fuck is there an onion there i dont understand"

**Comment by Jarod1200** [comment]
they took the onion out of the maint template a while back

**Comment by athena413** [comment]
> 
> 
> i would like this but theres literally already a player reference to jarod, in the clockwork maint template. i feel as if this is a bit overboard tbh

damn someone beat me to the punch

**Pull request closed without merging**
