### PR TITLE
Toolbelts can hold smart metal foam grenades

### PR DESCRIPTION
**Pull request by Hopekz**
Seems like another oversight.
The sprite has a little pull tab that you'd be able to mount on a belt 

image

#### Changelog

:cl:  Hopek
rscadd: Toolbelts can hold smart metal foam grenades
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
That's the...
That's the uhh...
The grenade lever

**Comment by Hopekz** [comment]
> That's the...
> That's the uhh...
> The grenade lever

I know what it is; but you pull the pin first otherwise, it doesn't move
Lever implies motion and this is stationary due to the pin being jammed in.

**Comment by maxion12345** [comment]
there are numerous reasons to not hold a grenade by its lever but I want my toolbelt grenade

**Comment by Bibby0110** [comment]
> > That's the...
> > That's the uhh...
> > The grenade lever
> 
> I know what it is; but you pull the pin first otherwise, it doesn't move
> Lever implies motion and this is stationary due to the pin being jammed in.

Yeah I'm just saying that's not a good reason to do it, I don't mind it, but don't base it on the fucking sprite mane

**Comment by Hopekz** [comment]
> Yeah I'm just saying that's not a good reason to do it, I don't mind it, but don't base it on the fucking sprite mane

image

**Comment by Marmio64** [comment]
who cares if you get a little metal foam all over yourself, then you can be a iron golem!

**Comment by Jarod1200** [comment]
Is this the only type of grenade that will fit? Or will chem grenades also fit?

**Comment by Hopekz** [comment]
> Is this the only type of grenade that will fit? Or will chem grenades also fit?

Only smart foam grenades

**Comment by Hopekz** [comment]
> Is this the only type of grenade that will fit? Or will chem grenades also fit?

Only smart foam grenades

**Pull request merged**
