### PR TITLE
Adds the anniversary of 24605 as a holiday

### PR DESCRIPTION
**Pull request by MrHorizons**
There's already a poster, so why not a holiday, too?

Like most of the other holidays, there isn't too much to it. A drone hat (the atmos tech beret), a specific lobby song ([Johnny Cash's "Ring Of Fire"](https://www.youtube.com/watch?v=5WyLhwYFgmk), feel free to suggest more), and a new set of star-related station prefixes..

#### Changelog

:cl:  
rscadd: Adds the anniversary of 24605 (August 2nd) as a holiday.
/:cl:

### CODE REVIEW

**Comment by MrHorizons** [comment]
Perhaps I could figure out a way to have a way to let newer players know the events of 24605, like a "story of" paper or something. Or we could just keep it entirely OOC.

**Comment by MegaEmpirical** [comment]
What?

**Comment by alexkar598** [comment]
While this is arguably funny, im probably going to end up closing this, its too vague to be referenced as a proper holiday, the amount of active players from that period is declining and alot of them probably dont know what this meme is.

**Review by alexkar598 — APPROVED** [review]
Code is fine tho

**Comment by Jarod1200** [comment]
sad. the younger generations forget the sins of their fathers.

**Pull request closed without merging**
