### PR TITLE
Revert "Buff radioactive goat, radiation anomaly now spawns radioactive goat!"

### PR DESCRIPTION
**Pull request by JamieD1**
Reverts yogstation13/Yogstation#16615

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
i love you jamie no homo I was just about to do this

**Comment by TheRyeGuyWhoWillNowDie** [comment]
🥺

**Comment by JamieD1** [comment]
Test merged until author can fix it

**Comment by JamieD1** [comment]
@warface1234455

**Comment by Simplehorror** [comment]
lmfao

**Comment by warface1234455** [comment]
guh how is it op it only have 30-40 hp

**Comment by ShoziOffical** [comment]
Jamie review my nerf pr

**Comment by ShoziOffical** [comment]
life is pain huh

**Comment by MajManatee** [comment]
Improve dont remove smh

**Pull request closed without merging**
