### PR TITLE
(port) Bamboomk2

### PR DESCRIPTION
**Pull request by boodaliboo**
original pr: https://github.com/BeeStation/BeeStation-Hornet/pull/598

Ah yes, the return of the vietcong PR, lets do this again:

I saw the assets for bamboo on the code, but then i noticed they werent used, so i decided to finish the port they where meant to be and throw some extras in:

-You get bamboo from mutating sugarcane

-Behaves similarly to a towercap, giving out bamboo branches you can cut into cuttings, for crafting.

-Punji sticks: the most simple use for bamboo. Create some on the floor and watch as everyone trips and gets poked everywhere they shouldnt. It is very brittle, though.

-Bamboo spear: A spear made of 25 bamboo cuttings, wich works exactly as a normal glass spear, but more organic, for the ecologists. Watch as botanists quickly devolve into cavemen with weed.

-Blowgun and syringes: you can also make a blowgun from bamboo, able to shoot syringes with a delayed windup and a cost for stamina/oxygen damage. You can also make crude syringes that hold meagre 5 units of reagents, for cheap ammo.

#### Changelog

:cl:  
rscadd: Added new bamboo things
imageadd: replace bamboo and punji sprites
spellcheck: fixed a few typos  
/:cl:

### CODE REVIEW

**Review by Partheo — APPROVED** [review]
Sprites are good. Even if this PR doesn't get merged, I'd like to see those new sprites in our codebase some day.

**Comment by MrHorizons** [comment]
I was thinking of porting this one over, actually! Though I didn't know what I expected by sharing my "Neat Stuff to Port" document. Still, +1.

**Comment by ghost** [comment]
>craftable syringe guns from botany

ahahahahahaha
ahahahaahha

you idiots

you fucking idiots

botany has traitor poisons that decay so slowly 5u is a death sentence

**Comment by boodaliboo** [comment]
> > craftable syringe guns from botany
> 
> ahahahahahaha
> ahahahaahha
> 
> you idiots
> 
> you fucking idiots
> 
> botany has traitor poisons that decay so slowly 5u is a death sentence

botany can print normal syringes and use normal syringes

**Comment by ynot01** [comment]
make it so the bamboo gun can only hold the 5u syringes

**Comment by ynot01** [comment]
also i kinda like the old punji sticks better idk @Partheo what do yo uthink

**Comment by Partheo** [comment]
I like these better honestly

**Comment by boodaliboo** [comment]
> make it so the bamboo gun can only hold the 5u syringes

why the blowgun is bad anyways you have to stand still for a few seconds and if your pushed it doesnt shoot

**Comment by Reed0506** [comment]
blowgun really doesnt seem like a huge issue to me seeing as botany can just whip up ultramegahyperdeath plants and throw them at people to more or less instacrit them already

**Pull request merged**
