### PR TITLE
Syndicate Icemoon Revision 3, with reduced atmos fuckery

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Adds the following to Syndicate Icemoon:

- Nuclear Power Station
- Moves xenobio to science wing
- Adds agent retrieval implants, because I don't trust you
- A memorial to the previous capabilities of the base
- Engineering is also entirely redone
- Adds a bar
- Other minor tweaks to improve QOL

image
image
image
image
image

- old PR is at #20929

# Why is this Good for the Game
The previous revision is mildly buggy (atmos of the vault is fucked, cant think of much more off the top of my head) and lacks a bar and other comforts. At the same time, the original plan from the start of development of the base was to have it nuclear-powered.

# Testing

I made sure the reactor didn't damage station or irradiate it after meltdown and I also made sure that everything worked

# Changelog

:cl:  
rscadd: The Syndicate facility on the Icemoon has recently resumed standard transmissions after an abnormally long period of maintenance work. We're also picking up significant radiation from the west side of the base. Keep an eye out.
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
image
FUCK

**Comment by Addust** [comment]
probably a forgot-to-compile error

**Comment by Addust** [comment]
was a forgot to compile error, continuing testing

**Comment by GDRdev** [comment]
sad no more funny hardsuit... I wish you atleast got hardsuits from the syndie base soo its actually worth going there as a syndie op. It makes for good roleplay...

**Comment by Addust** [comment]
> sad no more funny hardsuit... I wish you atleast got hardsuits from the syndie base soo its actually worth going there as a syndie op. It makes for good roleplay...

theres a bunch in cargo iirc

**Comment by AMyriad** [comment]
imma be real I don't think the glass panes should be on the inner tiles, there's a risk of the glass shattering from pressure
image
also brother make yo decals consistent 💀

**Comment by Addust** [comment]
> imma be real I don't think the glass panes should be on the inner tiles, there's a risk of the glass shattering from pressure image also brother make yo decals consistent 💀

will do once i finish modding box for an event

**Comment by Addust** [comment]
image
image

**Comment by LassiH** [comment]
xenobio seems too small compared to last one i dont think anybody is doing xenobiology with 2 people maybe the space used by second console could be replaced with a another contaiment cage

**Comment by Addust** [comment]
> xenobio seems too small compared to last one i dont think anybody is doing xenobiology with 2 people maybe the space used by second console could be replaced with a another contaiment cage

ill consider it

**Review by AMyriad — CHANGES_REQUESTED** [review]
Icemoon

Aight, all in all this redesign is pretty cool. I'm a fan of your use of fencing and the reactor, so I dig it.
Here are some problems I noticed at a glance:

- **Red:** Please remove the inner plasma Rwindows and firelocks, it's a bit overkill and looks cluttered.
- **Yellow:** Please remove these air alarms, ye don't need 3-4 air alarms in those areas, just one.
- **Orange:** Please replace heavy firedoors with the standard directional ones we use, and add directional firedoors to the highlighted airlocks that are missing them.
- **Blue:** Fire alarms that are upside-down, pls fix. Also remove one of the fire alarms in the kitchen area, they're on top of each other and the room only needs one.
- **Brown:** Please either replace the heavy firedoors in the windows to the gas miner chambers with directional firedoors or remove em, they're a bit unecessary.
- **Green:** Just a nitpick, not required, I'd recommend moving the left button to the same tile as the right button and pixel shifting them above/below each other. Also swapping the flexi-seal and the computer may look better.
- **Purple:** The water canister, the tiny fans, and the whole nitrogen setup you have going for the kill chamber are unecessary. Take a look at other maps, two vents and a cooler cycling/cooling regular air works just fine, and if you want to save on space, use an airlock instead of shutters.


- Please remove the plasma and co2 canisters in the engine room too, they're not necessary to generating power here.
- Please remove the random mineral walls, they shouldn't have access to mining more materials.
- **Lastly,** there are a BUNCH of instances of plastitanium Rwalls. You can tell since they're a subtype of /wall/r_wall/ and are called "hull". Please replace these with regular plastitanium walls. A bit of a mouthful, all this, but hopefully shouldn't take that long to fix!

**Review by AMyriad — APPROVED** [review]
nice, map looks good

**Review by SapphicOverload — APPROVED** [review]
Code looks good

**Pull request merged**
