### PR TITLE
Reworks yogstation medbay 

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Reworks yogstation medbay, redesigning it to have two patient rooms, a separate locker/storage room, a more central sec office, and a better connected paramedic staging area.

# Images
image

# Wiki Documentation

Map images will need to be updated. 

# Changelog

:cl:  
tweak: reworked the yogstation medbay 
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
don’t know how that main area will work with the table in the middle 

also too many firelocks on windows, does the previous version have them besides the main room and the hallway leading?

**Comment by Xantam-13** [comment]
I am not a fan of how large the "break room" on the left is, compared to the actual medbay itself
Personal opinion of course

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Can you cut down the break room a bit? I'd rather have the lockers for the medical doctors be in storage

**Comment by nmajask** [comment]
> I am not a fan of how large the "break room" on the left is, compared to the actual medbay itself Personal opinion of course

> Can you cut down the break room a bit? I'd rather have the lockers for the medical doctors be in storage

Both fixed

**Comment by MenacingManatee** [comment]
Not sure how I feel about the paramed have regular hall access instead of a maint access. What purpose does the paramed desk serve? Also missing a fire closet for paramed.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
what manatee said

**Comment by JamieD1** [comment]
Feels like medbay is being reworked every other week

**Comment by ToasterBiome** [comment]
@JamieD1 would like your thoughts

**Comment by Bibby0110** [comment]
Stale and conflicted for 19 days. Feel free to reopen later :) Looks nice

**Pull request closed without merging**
