### PR TITLE
Ports the Hypertorus Fusion Reactor: Fusion in a machine

### PR DESCRIPTION
**Pull request by ThatLing**
# Document the changes in your pull request
This ports over the Hypertorus Fusion Reactor (HFR) from /tg/. This is basically a fancy machine that performs fusion internally, adding a new layer of depth for atmos techs to play with. **Open-tile and canister fusion are not being removed!** This is something that can be considered at a later date, depending how this change is received.

In addition to the HFR, it also ports over 1 new gas: Anti-noblium. Which can be created using the HFR. I will add funny reactions soon™️.

All gas changes:
- Anti-noblium:
  - Increases SM heat generation while decreasing power generation
- Nitrium:
  - New gas which combines the effects of Nitryl and Stimulum
  - Requirements for formation:
    - 20 moles of nitrogen
    - 20 moles of plasma
    - 20 moles of BZ
    - 5 moles of n2o as a catalyst
    - Minimum temp of 50000K
  - 0.002 mol per breath for stun immunity (old stim effect), 0.005 mol per breath for speed boost (old nitryl effect)
- Healium:
  - Makes your text go small when you breathe it in
image

<details>
    <summary>HFR UI</summary>

image
</details>

Incomplete list of PRs ported, this is basically the most up-to-date version currently. Credits to the original authors, especially Ghilker and esainane.
- https://github.com/tgstation/tgstation/pull/54379
- https://github.com/tgstation/tgstation/pull/55189
- https://github.com/tgstation/tgstation/pull/57901
- https://github.com/tgstation/tgstation/pull/58506
- https://github.com/tgstation/tgstation/pull/61593
- https://github.com/tgstation/tgstation/pull/61737

Some additional changes:
- Fixes heat exchanger runtimes
- Removes broken atmos grenade and added correct one to atmos mail
- Adds dynamic lighting to canisters

# Spriting
Sprites are ported from /tg/

<details>
    <summary>Sprites</summary>

image
</details>

<details>
    <summary>Map changes</summary>

image
</details>

<details>
    <summary>Finished HFR build</summary>

image
</details>

# Wiki Documentation
Yes, I will get to that. In the meantime you can read /tg/'s wiki article: https://tgstation13.org/wiki/Guide_to_the_Hypertorus_Fusion_Reactor

# Changelog

:cl: 
rscadd: Atmospherics received a new toy to play with. The Hypertorus Fusion Reactor can soon be found on a station near you to create more funny meme gases.
tweak: Atmospherics has been(slightly) redesigned on all maps.
/:cl:

### CODE REVIEW

**Comment by SapphicOverload** [comment]
does this remove fusion as a gas reaction?

**Comment by ThatLing** [comment]
> does this remove fusion as a gas reaction?

image

**Comment by iamthesilly** [comment]
nice

**Comment by iamthesilly** [comment]
would be nice if there was a way to remove excess fusion fuel from the reactor, like an emergency fuel dump button in the interface to send fuel into the waste output

**Comment by ThatLing** [comment]
> would be nice if there was a way to remove excess fusion fuel from the reactor, like an emergency fuel dump button in the interface to send fuel into the waste output

Changing the recipe currently dumps it back into the fuel pipenet (although it might delete some of it). You can add a wall injector to delete any unwanted gas. Althought I do agree, it would be nice and I'll look into it.

**Comment by iamthesilly** [comment]
> Changing the recipe currently dumps it back into the fuel pipenet (although it might delete some of it). You can add a wall injector to delete any unwanted gas. Althought I do agree, it would be nice and I'll look into it.

you can't change the recipe while the reactor is active, and the injector only works for getting rid of gases that are already outside of the reactor

**Comment by ThatLing** [comment]
> > Changing the recipe currently dumps it back into the fuel pipenet (although it might delete some of it). You can add a wall injector to delete any unwanted gas. Althought I do agree, it would be nice and I'll look into it.
> 
> you can't change the recipe while the reactor is active

Simply stop the fusion reaction :^)

**Comment by iamthesilly** [comment]
> Simply stop the fusion reaction :^)

you can't do that unless the temperature is low enough, and i don't think changing the recipe is an intended way of getting rid of fuel anyway

**Comment by ThatLing** [comment]
> > Simply stop the fusion reaction :^)
> 
> you can't do that unless the temperature is low enough, and i don't think changing the recipe is an intended way of getting rid of fuel anyway

All gas, no brakes on the fusion train

**Review by alexkar598 — CHANGES_REQUESTED** [review]
porque libbyond-extools changes?

**Comment by ThatLing** [comment]
> porque libbyond-extools changes?

https://github.com/yogstation13/extools/pull/18

**Comment by MajManatee** [comment]
the confusion between healium and helium

**Comment by ThatLing** [comment]
> the confusion between healium and helium

But helium will make your voice be funny

**Comment by Moja10** [comment]
uhhh, English, poindexter????

**Comment by Moltijoe** [comment]
> But helium will make your voice be funny

just make healium do that and remove helium

**Comment by iamthesilly** [comment]
> just make healium do that and remove helium

Healium makes you sleep so there's no point

**Review by cuackles — APPROVED** [review]
individual sprites look off but when the whole thing is built they work

**Comment by Cartlord** [comment]
I don't see the point of the new gases, helium is going to wind up being another junk gas that nobody ever makes (REMEMBER ZAUKER????) and antinob is already a traitor item

**Comment by ThatLing** [comment]
Waiting for auxmos to update this

**Comment by Yogbot-13** [comment]
#### Test Merge Deployed

##### Server Instance
main

##### Merged By
JamieD12

##### Revision
Origin: d5b749684fbdb33e3585c3ab9976a3e40a1d6431
Pull Request: 78ee2a0bc850cd8dfd5406507a277864ebb9bbbc
Server: 7accb187f169e96147116fcb6c2e6dd0633093a3
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
JamieD12

##### Revision
Origin: f7be2f55b2fb273994059ff50991795fb6750975
Pull Request: 78ee2a0bc850cd8dfd5406507a277864ebb9bbbc
Server: fc044f2fcb97c29858edd49d531c9c5211b3475d
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
JamieD12

##### Revision
Origin: f7be2f55b2fb273994059ff50991795fb6750975
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 2df4ebf30b32e03127ae11e34ef1c77a3a16477a
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
JamieD12

##### Revision
Origin: 378ec01135c60a38f8903bc43b5f3382d6ce84fc
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 9ee5c0c521e6d2bd2aadc4c70587af706da35094
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
JamieD12

##### Revision
Origin: 950154b6c666d27343b9fc9e00d5be75b6eca16b
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 6ed458e7e3295f26b5a7e56cb84529704507e7b4
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
JamieD12

##### Revision
Origin: 950154b6c666d27343b9fc9e00d5be75b6eca16b
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 4579eae886f849344562650e4905115f0ac7c9ed
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
JamieD12

##### Revision
Origin: 8099eac2e52331348d5183acdfe9c29aadbd1923
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 2fbf5c384a78bff27ea9c9fba280a2ef8b429a14
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
baiomu

##### Revision
Origin: 8099eac2e52331348d5183acdfe9c29aadbd1923
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 3284c348effb4925727e6d05c689b28e46874e5a

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
baiomu

##### Revision
Origin: 8099eac2e52331348d5183acdfe9c29aadbd1923
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: cbeb05db94a50bb88ebd4f531d60e5b951251b1c

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
baiomu

##### Revision
Origin: 14108b6563f966e94e255e7aba4c44859c7f4a9a
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: a46a232c50afb2e80a0807f62a80a74320ef8e05

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
ynot01

##### Revision
Origin: 14108b6563f966e94e255e7aba4c44859c7f4a9a
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 13c9f97c732b7bdd024c8c9752a60f2bfeec5f88

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
ynot01

##### Revision
Origin: 02f86b602a9a466f4635593d7336cea3772edc89
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 88b1a95ee81b78d1072d0ddc894aadb69d2c19ed

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
ynot01

##### Revision
Origin: 135036f9e994bd1ccbc916ea567041d3c19487c5
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 5178319911050064a98c799418677103f581cd7b

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Review by patpol4 — APPROVED** [review]
not a big fan of it being roundstart but the map is workable

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
ynot01

##### Revision
Origin: bc254de4aea5477331c2b78016521126b002465d
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 614e92c3ba203cf284f38fa5842aaf31c0074d04

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
ynot01

##### Revision
Origin: 36f1019a12e96f16ed0d63530628f646c5c395fa
Pull Request: 37bf98cc4a948253416253f16e9f269ed26419c0
Server: 0b19b425912d3f7a304ff0356486e774552eb8d8

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
thatling

##### Revision
Origin: 36f1019a12e96f16ed0d63530628f646c5c395fa
Pull Request: 1b0e498fbc6d66af49e0ecd37e5fffefe5e72d83
Server: 318b65f5363419b92f4d7a51b18179e42555e746

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
thatling

##### Revision
Origin: 8ddea87549034dd1e9bc258a3ad897241ea63978
Pull Request: 1b0e498fbc6d66af49e0ecd37e5fffefe5e72d83
Server: 8438194323911fe3f431f4aa826fac68bc847111

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
thatling

##### Revision
Origin: 81634e614aee6be53ee8a764c9fcc4a4ea85cf85
Pull Request: 1b0e498fbc6d66af49e0ecd37e5fffefe5e72d83
Server: 130f546c6604b3e33212b216b6ec7196508b4847

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
thatling

##### Revision
Origin: 5c0342c4ebfe045cd0631065a0c6ca61baecadfc
Pull Request: 1b0e498fbc6d66af49e0ecd37e5fffefe5e72d83
Server: 7562a977fc06df367cbbe59c813e00ed456e8313

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
thatling

##### Revision
Origin: bfb55db217c3691a32412deebd51758b3ba0b273
Pull Request: 1b0e498fbc6d66af49e0ecd37e5fffefe5e72d83
Server: 256de8481d09166256d49120244a4b4a969edcb6

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
thatling

##### Revision
Origin: 0dfe5809c53dc1d642334cad23d7a2c39af5cff9
Pull Request: 1b0e498fbc6d66af49e0ecd37e5fffefe5e72d83
Server: 725757d3abdbc98744dfb11e5945f52f6783c15c

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
thatling

##### Revision
Origin: a2285ba0d2f3083fb790b81e35c70a7a6a5b48b7
Pull Request: 1b0e498fbc6d66af49e0ecd37e5fffefe5e72d83
Server: dc984987b9acee076d776f9befb499574b381582

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Removed

**Review by ToasterBiome — APPROVED** [review]
If you're confident in it, I'm confident in it

**Pull request merged**
