### PR TITLE
Makes me codeowner of all maps

### PR DESCRIPTION
**Pull request by Ktlwjec**
image

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Why?

**Comment by Ktlwjec** [comment]
I'm headmapper but only codeowner for station maps currently, makes it easier for me since it'll give me an email for all map changes.

**Comment by ThatLing** [comment]
no woman can hold so much power

**Comment by Hopekz** [comment]
+1 
ktl has basically unofficially had this role anyway might as well write it in.

**Pull request merged**
