### PR TITLE
Makes powergamers mad by removing captain gun from lavaland

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

Fixes the """oversight""" committed by some powergaming mapper that thought it would be appropriate to add an antag objective item to lavaland for shits and giggles. Courtesy of Adam.

#### Changelog

:cl:  
rscdel: Removed captain's antique laser gun from lavaland
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
plant > gun 
Use a random plant spawner though, photosynthesize makes blue light and it would look shit next to the light fixture

**Comment by ghost** [comment]
okok will do gimme a moment

**Comment by Mesalikepie** [comment]
Perhaps leave something of good value in their otherwise the ruin will be completely passed over. Perhaps an ice focused weapon? Like a ice grenade or a wand of some cooling or slowdown or something

**Comment by ghost** [comment]
no

**Review by jcatjmeow — APPROVED** [review]

**Comment by boodaliboo** [comment]
fuck you im making a better pr

**Comment by boodaliboo** [comment]
> fuck you im making a better pr

sorry

**Comment by SomeguyManperson** [comment]
replace with the useless temperature gun

**Review by patpol4 — APPROVED** [review]
Heads will decide whether we get plant or gluon grenade

**Review by Ktlwjec1 — APPROVED** [review]

**Comment by Marmio64** [comment]
add a cryokinesis and geladikenisis mutator in the ruin please

**Pull request merged**
