### PR TITLE
Resprites security belts, adds HoS belt, and misc belt tweaks

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Adds/tweaks various belt things like new sprites for the security belt, a new HoS belt, belt overlays for more stuff, and more. Has been tested, does work

# Spriting
image

# Wiki Documentation

Images will need to be updated 

# Changelog

:cl:  
rscadd: Added Head of security belt and admin belt
tweak: abductor belt and sec webbing now use belt overlays
tweak: medical stacks, some analyzers, telescopic batons, abductor batons, and surgical drapes now show up in belts
imageadd: resprited security belt and medical belts
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Looks good, don't know why the hos belt has a kind of chief engi orange and white motif going on though, considering sec outfits never use those colors

**Comment by nmajask** [comment]
> Looks good, don't know why the hos belt has a kind of chief engi orange and white motif going on though, considering sec outfits never use those colors

image
resprited it to use crimson instead

**Comment by KillerOrcaCora** [comment]
This was my only issue will this pr will approve sometime tmr.

**Review by KillerOrcaCora — APPROVED** [review]
Sprites are fine.

**Pull request merged**
