### PR TITLE
Felinid buff: Dairy is now a liked food group

### PR DESCRIPTION
**Pull request by Chubbygummibear**
Why are Moths the only race that specifically LIKE milk?? 
Cats like milk and I want to make it canon

((Don't say I never tried to do anything for any race that isn't Pods))

# Wiki Documentation

Cats like milk

# Changelog

:cl:  
rscadd: Dairy is now a liked food group for felinids
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
dude cats are lactose intolerant

**Comment by Hopekz** [comment]
> dude cats are lactose intolerant

image

Felind people are snowflakes so it is safe to assume that their species would be one of those that can since it would make them special.

#notallcats

**Comment by patpol4** [comment]
adult cats really shouldnt drink milk

**Comment by Tipy1802** [comment]
> adult cats really shouldnt drink milk

People who play felind cannot be considered adult in mind

**Comment by Tipy1802** [comment]
C'mon it's a trope that cats like milk

**Review by adamsong — APPROVED** [review]
Code does as described

**Pull request merged**
