### PR TITLE
Removes Belter

### PR DESCRIPTION
**Pull request by LoliconSlayer**
Hey kids, Belter's kind of a sad excuse for an accent so lets get rid of it

Honestly I have no idea what the fuck I'm doing

#### Changelog

:cl:  
Belter accent removed
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Ignore the first two commits I don't really understand how all this git stuff works, I'm learning though

**Comment by boodaliboo** [comment]
Who’d Breuer

**Comment by athena413** [comment]
please yes merge asap

**Comment by Ktlwjec1** [comment]
Only last commit matters, so don't worry in future. Literally what is this accent, I'll merge it provided there's not like 100 downvotes tomorrow.

**Comment by Hopekz** [comment]
Stupid but I understand that we need to cater yogs to people like LoliconSlayer in the same way Paradise needs to cater to their furry player base.

**Comment by LoliconSlayer** [comment]
Really gonna compare me to para furries just because I and several others don't like your sad excuse for an "accent" huh

**Pull request merged**
