### PR TITLE
Removes the donk-soft vendor from roundstart asteroid

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Removes the roundstart vendor 

image

# Why is this good for the game?

Leads to less problems for admins and players alike when riot darts get out of control.

# Changelog

:cl:  

rscdel: Removes the donksoft vendor from asteroid

/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
never

**Comment by cowbot92** [comment]
> never

god's silliest soldier needs a rest

**Comment by patpol4** [comment]
hugbox

**Comment by MajManatee** [comment]
Terrible pr. Horrible. Abysmal.

**Comment by cowbot92** [comment]
fine ill just ban people with riot darts forever

**Comment by cowbot92** [comment]
I lied, waiting on bibby's freeze, admins be damned

**Comment by AMyriad** [comment]
how about replacing it with something so people won't hate this as much?

**Comment by cowbot92** [comment]
> how about replacing it with something so people won't hate this as much?

nope

**Comment by ofscarletdreams** [comment]
replace it with the syndicate shuttle console or im going to pull strings and get your goofy ass wiped from living memory

**Comment by cowbot92** [comment]
> replace it with the syndicate shuttle console or im going to pull strings and get your goofy ass wiped from living memory

ill replace it with the america vendor, the only way to stop a bad guy with a gun is a good guy with one

**Comment by azzzertyy** [comment]
who couldve made this pr previously and got denied... https://github.com/yogstation13/Yogstation/pull/18985

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
