### PR TITLE
Reenables metastation

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Some map variety is good, this reenables metastation, so hopefully some effort can be put into it.

# Changelog

:cl:  
rscadd: Added metastation to rotation
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
#12813

**Comment by Hopekz** [comment]
The reason these maps were removed is that no one bothered to update them when PR's with map changes are created because each map adds additional work to update. For example in Bibby's AI rework he had to do 4x the amount of work because we were maintaining all of these maps.

I get that you "want variety" by re-adding this map but it'll become outdated with time (not that this map is updated in the first place). 
Even if you yourself FULLY update this map to be current ss13 dev is a team effort so if everyone isn't on-board with keeping this map updated as the game evolves it'll become outdated over time (again not saying that this map is even updated in the first place).

That and because box was chosen 98%+ of the time so any dev work done on these alternative maps was kind of a "waste" of dev time.

Going back to the updating argument even simple changes have not been ported to these alternative maps such as heads all starting in a single room. It has been a whole year since that change and it just really shows that people literally cannot be bothered to update these alternative maps.

>  this reenables metastation, so hopefully some effort can be put into it.

Metastation has been enabled for YEARS.
There was no development effort put into it just because it has been around in the background.
There is no difference with you just readding this outdated map back in terms of community effort given to update it.
Metastation will most likely not be maintained to the same level as boxstation as per usual.

**Comment by N3D6** [comment]
Meta holds up well, it's a great map that lacks some QoL features.

Taking out any and all variety just because you don't like it is bullshit, it's not fair to the people who DO like it

**Comment by Hopekz** [comment]
> Taking out any and all variety just because you don't like it is bullshit, it's not fair to the people who DO like it

No one here said meta is not liked. 
If you follow the reasoning behind it being taken away from votes, you will be informed that it isn't being maintained anymore and because the alternative maps don't get chosen.

Maintaining all maps means putting the same amount of dev effort across all supported maps.
These alternative maps have been ignored for a long time.

**Comment by adamsong** [comment]
Map variety is good, with just two maps enabled, it still greatly reduces the amount of work required to maintain the maps, while also allowing some variety.

**Comment by Hopekz** [comment]
> with just two maps enabled, it still greatly reduces the amount of work required to maintain the maps,

This PR doubles the amount of map work because it is taking us from 1 map to 2.

**Review by patpol4 — APPROVED** [review]

**Comment by patpol4** [comment]
Irrelevant now because theos backed out and reverted all of them

**Pull request closed without merging**
