### PR TITLE
[MDB IGNORE] Donutstation: Glazed

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

This brings back one of my favorite maps Yogs used to have, albeit a very controversial one.  It was taken out of rotation, I believe due to being unmaintained.  

I have updated so much shit and fixed _so fucking many insane mapping choices_ to get to this point.  There is still some things left to do, but this is ready to become a draft PR.

- [x] fix disposals not working (get biome to do it like he said he would)
- [x] randomized engines (generic DM)
- [x] fix atmos (generic DM)
- [x] randomized maint
- [x] move tcomms somewhere more sensible
- [x] redo dorms/holodeck
- [x] decal overhaul
- [x] fix camera names
- [x] fix lighting in certain spots
- [x] fix camera coverage
- [x] general polish

All changes from old Donut are as follows:

- Made maintenance randomized.
- Cut out a lot of maintenance loot spawners to make it on the same level as other maps.
- Redesigned Medical Treatment Centre.
- Moved morgue from chapel to medical.
- Added a paramedic office.
- Added a separate air system for virology to make it consistent with other maps.
- Moved all scrubber and air pipes onto the correct layers.
- Replaced old firelocks with "new" border firelocks, and added lots more where there should've been some.
- Replaced old style directional windows with window spawners.
- Made holodeck bigger to allow it to function.
- Added a pool to fitness.
- Redesigned Dormitories.
- Made all airlocks modernized so they function with monstermos without spacing EVERYTHING.
- Significantly reduced the size of the chapel.
- Made AI upload not only accessible by maintenance.
- Made AI core not only accessible by maintenance
- Made vault not only accessible by maintenance.
- Made telecomms not only accessible by maintenance.
- Moved all the APC's for departments and misc. areas out of maintenance.
- Redid the singularity engine to be more logically wired, and removed stupid emitter hallways.
- Added desks to departments that didn't have one.
- Replaced static plants with randomized variants.
- Redesigned atmospherics to make the pipes not weirdly done.
- Made it so the gas miner tanks were not one wall from filling the entire station with deadly gasses.
- Added a Transfer Centre.
- Added Security Posts to departments that didn't have one.
- Redesigned Evac so that most shuttles could actually dock there.
- Added a podbay.
- Unshocked a lot of windows that shouldn't have been shocked.
- Made solar panel areas the correct ones.
- Removed departmentally named maintenances such as "Security Maint" when it should've just been the normal area it was in.
- Made solar panels the 96% chance spawners we use nowadays.
- Removed some garden trays from the garden that were preventing beepsky from pathing.
- Moved head of staff spawns to the meeting room on bridge.
- Modernized decals
- Expanded maint
- A shitload of minor fixes not listed.

image_2023-08-11_110757714

# Spriting

i would die

# Wiki Documentation

needs new map page

# Changelog

:cl:  Cark, GenericDM, Baiomu, N3D6
mapping: adds donutstation back to the game
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
Sec buff

**Comment by azzzertyy** [comment]
general enjoyment of the game buff

**Comment by MajManatee** [comment]
smh update the station with the tubes

**Comment by neeshacark** [comment]
Disposals are still broken but besides that everything is ready for playtesting.

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
i did not forget to hit the submit review button yester day i swear

image
those secondary docking spots dont need the near station area under them

image
and the ferry dock for the centcom ferry would lead to shuttle slammage unless you have a specific donut ferry that i cant find.....

once i get off work tomorrow ill look through atmos, distro,scrubbers,medbay, and science

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
image
 would prefer if you made these corners less solid blocks of r walls
 
 in other news, this is why you double and tripple check things
 
image
no wire connection from maint to kitchen Apc
image
Tcoms SMES to tcom apc is just something cringe, two SMES is also overdoing it 
image
no connection here for medbay to foyercontrol
image
cloning connection
image
no HOS apc
image
no wire connection from brig cells to the rest of brig
image
no wire through warden or perma for their APCS
image
no connection from cargo bay to secpoint apc
image
this whole grid section isnt connected to the SMES in engineering 
image
no apc for aux construction mining base
image
wire just ends here, place nodes on grilles and connect or remove that wire
image
this isnt connected 
image
2/4 of these windows are electrified
image
all other walls are Rwalls but these 3
image
library has not a single wire in it, you forgor the fucking corner wall in maint above the random ass Rwalls in library backroom thing
image
Unshocked HOs grilles
image
lawyer office has no wire, its wireless lawyer time

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
image
DISKPOSAL

**Review by Ethan4303 — CHANGES_REQUESTED** [review]
image
these still shouldnt be double walled
image
we both laughed about this in call together and its in my old RC Please fix this!!!11!!1!1!!!
image
your forgor the other emitters werent reconnected
image
Your forgot the auxmining base construction APC too
image
this potted plant should not be hard wired to the power grid (destroy this wire)
image
xenobio-maint walls should be reinforced, so should that one wall to the left of the maint airlock
image
this wall should also be reinforced
image
Genetics is typically surrounded in R walls too
image
viro-phsych walls shouldnt be doubled here


Please remember to do all the changes that are requested......... ;-;

**Review by Ethan4303 — APPROVED** [review]

**Comment by Ethan4303** [comment]
Meant to put a message with that approval, but my eyes cant find anything else thats terribly wrong 👍

**Comment by maxion12345** [comment]
Round 48821 noted issues

### **SECURITY DEPARTMENT ISSUES**

- The law office lacks an air alarm.
- Main brig area lacks air alarms.
- The windows by the brig entrance don't have shutters, but the doors do, leaving it vulnerable.
- GAME BREAKING: security desk lacks office chair
- Brig has no turnstiles, so prisoners will need to bang on the door to exit.
- Perma lacks an air alarm.
- Perma lacks a prisoner ID box for prisoners. The labor shuttle area has one, but it is in the corner, like a shunned child who has gotten bad grades on a test.
- Either the security office/meeting area lacks a scrubber, or it is hidden from view. It also lacks an air alarm.
- The security locker room lacks an air alarm.
- The armory does not have a vent (that I could see). 
- The windoors from the warden area to the armory are not the reinforced variant.
- HoS office lacks an air alarm.
- Interrogation room lacks an air alarm.'
- Officer meeting room has no meeting room button.
- Officer meeting room lack donuts and snacks.
- Armory does not contain any rechargers.
- Gulag area uses the teleporter instead of the processing machine.
- Gulag area lacks ways for prisoners to exit on their own. Once they return and grab their items, they'll need to wait to be let out. Don't think you can map in a solution, but it's something to keep in mind.
- 

### **ENGINEERING DEPARTMENT ISSUES**

- Engineering SMES lacks a vent/scrubber, despite having an air alarm.
- The engineering airlock to the engine is not set up correctly, spacing the department whenever used.
- Engineering Storage scrubber is hidden under a suit storage unit.
- Engineering Desk area either lacks a vent/scrubber or is hidden under machines. Also, no air alarm.
- Engineering sec outpost either lacks a vent or is hidden under a machine.
- Grav Gen lacks an air alarm.
- Sigtech sat use two vents? Why not use the two-way vent?
- Sigtech sat has an airlock where the tube arrives. Unnecessary, as there is an airlock on the other side. 
- Sigtech sat tube airlock has a vent under the tube.
- Sigtech sat tube airlock on the other side has a vent under a locker.
- Incinerator has a delivery flaps area, despite having no way to actually get deliveries. Also introduces a weak point to what would otherwise be surrounded by reinforced walls, like other maps.
- Community feedback says that using singulo EMPs grav gen.
- Community feedback says you cant reach back of the engine

### **SERVICE DEPARTMENT ISSUES**

- Chef's freezer room has freezer tiles that drop the temp round start, causing atmos alarms to it and the surrounding area. Use floor/open/plasteel/showroomfloor instead.
- The theatre vent is in the corner, while the scrubber is offset a bit towards the middle. This isn't a dealbreaker, It just made my eye twitch a bit once I noticed. Also lacks an air alarm in the enclosed theatre area, but this is less of an issue.
- Botany back room lacks an air alarm.
- Service hall lacks vent/scrubber/air alarm.
- Chapel lacks an air alarm. 
- Chaplain's Office lacks an air alarm.
-  Cremator area lacks vent/scrubber combo.
- The bartender bar room lacks an air alarm.
- The bar itself lacks an air alarm, despite being its separate area.
- Bar lacks shutters for its table.
- Public Garden lacks an air alarm.
- Roundstart donk-soft vendor in the lounge. Antagonists will be rushing riot darts and SMGs.
- Janitor area lacks pimping ride, cleaning grenades, and beartraps found on other maps.
- Maybe add a fishing hole to the public garden? A pond?
- No clear denotation of where the bar area begins, and where it ends. You use decals to denote the separation between the dining area and the hallway, but nothing separates the bar area from the kitchen. Maybe some carpet, or a different floor?
- so uh, whats the docking port near the holodeck for anyways?

### **SCIENCE DEPARTMENT ISSUES**

- RD server room does not have a vent/scrubber combo or air alarm despite being a separate area.\
- Secondary AI core either lacks vent, or it is under a machine.
- Research entrance vent/scrubber combo looks ugly. I'm just saying.
- Science security post, despite having an air alarm, lacks vents/scrubbers.
- The experimentation lab lacks window blast doors.
- Toxins Storage lacks an air alarm.

### **MEDICAL DEPARTMENT ISSUES**

- Chemistry either lacks a scrubber, or it is hidden under a machine.
- Medbay security post lacks vend/scrubber combo, despite having an air alarm.
- CMO office lacks an air alarm.
- Morgue lacks air alarms, vents, and scrubbers.
- The hallway to virology lacks any sort of air alarm. In fact, that whole open area lacks an air alarm.
- Medbay storage lacks an air alarm. The scrubber is hidden under a locker.\
- Virology quarters (with the bed) lack an air alarm. Virology also lacks an air alarm. Virology either lacks a vent, or it is hidden under a machine.
- Medbay surgery area lacks an air alarm.
- Psych office lacks an air alarm. Additionally, carpet under the door. Additionally, scrubber under the chair.

### **CARGO ISSUES**

- Cargo mail room lacks an air alarm, vents, and scrubbers.
- QM office lacks an air alarm.

### **COMMAND DEPARTMENT ISSUES**

- Upper AI Upload lacks an air alarm. The entryway does have one, but if someone breached the area with the actual computers there would be no alert. 
- Also, computers can be accessed via deconstructing a rwall, bypassing the turrets. Perhaps move them to the middle of the room?
- The hoP office scrubber is hidden under a filing cabinet.
- Vault lacks an air alarm
- Captains office lacks an air alarm.
- Teleporter hand tele is stuck in a corner on a table. Consider removing the corner, and just having the rack.
- Bridge meeting desk lacks meeting button.

### **EVERYTHING ELSE**

- Several areas cut up by firelocks lack vents in each segment to refill the area in the event of a blowout (Not a dealbreaker, but to refill the rooms they'll need to open firelocks and let the air rush in, and that'll cause mayhem)
- Holodeck office (with the console) lacks an air alarm.
- The evacuation hall lacks an air alarm. The only air alarm is in a box, with the security stuff.
- Evac area lacks evac signage. 
- The arrival hall lacks an air alarm.
- All dorms lack air alarms. Alternatively, use the randomized ones.
- Unisex Shower vent is under a locker.
- Departures pod bay uses blast doors AND the pod-lock ontop of eachother.
- Perhaps move the evac security area to butt up against the security entrance on most shuttles, as seen in other maps? You have the room for it. It'd be the leftmost airlock.
- Lots of rooms have empty space. Maybe add in some things to make it less roomy, and more space station-y.
- Department desk bells when
-

**Comment by MajManatee** [comment]
just a couple tweaks...

**Comment by iamthesilly** [comment]
Cryo freezer isn't connected to the pipes
image

**Comment by MajManatee** [comment]
The disposals system connecting the CEs office and chute by the engine do not function, and shoot out to each other.

**Comment by GenericDM** [comment]
where it go

**Pull request closed without merging**
