### PR TITLE
gives wizard a box with internals

### PR DESCRIPTION
**Pull request by boodaliboo**
oversight
#### Changelog

:cl:  
rscadd: Added a box with internals to wizard spawn 
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
This is without a doubt the worst fix to this problem and @yacabo should feel bad for upvoting it. 

https://github.com/yogstation13/Yogstation/blob/ff4e27fde39f252b1d32128b1aac8b8507b683ba/code/modules/clothing/outfits/standard.dm#L255
https://github.com/yogstation13/Yogstation/blob/ff4e27fde39f252b1d32128b1aac8b8507b683ba/code/game/objects/items/storage/boxes.dm#L125

:)

**Comment by boodaliboo** [comment]
> This is without a doubt the worst fix to this problem and @yacabo should feel bad for upvoting it.
> 
> https://github.com/yogstation13/Yogstation/blob/ff4e27fde39f252b1d32128b1aac8b8507b683ba/code/modules/clothing/outfits/standard.dm#L255
> 
> 
> https://github.com/yogstation13/Yogstation/blob/ff4e27fde39f252b1d32128b1aac8b8507b683ba/code/game/objects/items/storage/boxes.dm#L125
> 
> :)

i guess

**Comment by patpol4** [comment]
So are you adding it to the map or the code? No reason to have both here and the code fix is way better.

**Comment by boodaliboo** [comment]
> So are you adding it to the map or the code? No reason to have both here and the code fix is way better.

both just because it doesnt hurt for there to be extra boxes for apprentices or other things wizards or admemes may spawn

**Review by patpol4 — APPROVED** [review]
Fair enough, map fine

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
