### PR TITLE
Ports "Adds borg tablets, and RoboTact as a borg self-management app"

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

A very rough port of ["Adds borg tablets, and RoboTact as a borg self-management app" #53373](https://github.com/tgstation/tgstation/pull/53373) by zxaber from TG with some code barrowed from SandPoot on citadel to work around the lighting changes on TG. This is currently in the "I can do basic stuff without runtimes" stage, and I will need to have a testmerge done to see if everything is good. I don't play borg very often, so if anyone has any feedback on what to change please send it.

## Images

image
_robotact UI_

image
_borg UI_

## To Do

- [x] Do more testing
- [x] ~~Port ["Fixes the borg tablet being unusable without power, and borgs usually being unable to print pictures" #54339](https://github.com/tgstation/tgstation/pull/54339)~~ Doesn't really apply to our codebase
- [x] Port ["Allows emagged and syndicate borgs to self-detonate" #61915](https://github.com/tgstation/tgstation/pull/61915)
- [x] Port ["Adds the ability to download a borg's logs using SiliConnect." #57300](https://github.com/tgstation/tgstation/pull/57300)
- [x] Allow borgs to download programs/give certain modules certain starting programs
- [ ] Maybe remove redundant borg items/upgrades

# Wiki Documentation

Probably will need to change the borg page to mention the new stuff. 

# Changelog

:cl:  zxaber & SandPoot
rscadd: Added tablets to borgs.
rscadd: Added RoboTact, a borg self-management app to said tablet. This replaces most borg verbs.
rscdel: Removed many borg verbs in favor of the app.
tweak: Some lesser-used elements on the borg hud are now in the management app.
/:cl:

### CODE REVIEW

**Comment by nmajask** [comment]
damn, forgot to make it a draft

**Comment by maxion12345** [comment]
NGL that UI looks pretty big. Also do different modules come preinstalled with programs? Also where is the alert viewer on the ui

**Comment by nmajask** [comment]
> NGL that UI looks pretty big. 

image

I tried messing around with it to make it much more compact, mainly moving the laws to its own tab and merging the details and status areas into one area. I can add it if people preferer it

> Also do different modules come preinstalled with programs?

Currently not right now, as the original author of the PR wanted borgs to have to work with people to get programs. I may add that or just allow them to use the downloader, as asking our players to work together to do something always ends up failing.

> Also where is the alert viewer on the ui

image
This is what the new UI looks for borgs. There is still a button for the alert viewer for the time being, but later down the line I may just make the motion/cam/burglar alarms their own app and have borgs start with it.

**Review by nesisknesis — APPROVED** [review]

**Comment by nmajask** [comment]
I probably should have checked my PR before I asked it to get test merged, thanks Theos.

**Comment by ToasterBiome** [comment]
lamp power slider is janky as fuck, would also like choosing lamp power through the button still.

**Comment by warface1234455** [comment]
This is kinda cool but if the tcoms shit is down, you can't use the ntos tablet..

**Comment by nmajask** [comment]
> lamp power slider is janky as fuck, would also like choosing lamp power through the button still.

I added some buttons to the tgui for adjusting lamp power, I may readd some of the removed UI stuff later on.

> This is kinda cool but if the tcoms shit is down, you can't use the ntos tablet..

Are you talking about borgs not being able to interact with their tablet, or them not being able to use apps that require NTnet access?

**Comment by maxion12345** [comment]
no way to toggle ion thrusters

**Comment by nmajask** [comment]
> no way to toggle ion thrusters

did you check robotact?

**Comment by adamsong** [comment]
Why cam borgs download the id modification program?

**Comment by maxion12345** [comment]
> > no way to toggle ion thrusters
> 
> did you check robotact?

didn't see a button for it, no

**Comment by nmajask** [comment]
> > > no way to toggle ion thrusters
> 
> > 
> 
> > did you check robotact?
> 
> 
> 
> didn't see a button for it, no

Looks like it should appear in the action sub tab, though only if you have the thruster installed.

**Comment by Bibby0110** [comment]
> > lamp power slider is janky as fuck, would also like choosing lamp power through the button still.
> 
> I added some buttons to the tgui for adjusting lamp power, I may readd some of the removed UI stuff later on.

I'm pretty sure you can click the slider to manually input numbers

**Comment by JamieD1** [comment]
Would it be possible to keep the thruster button and to move the management to the left of the camera instead?

I feel like the thrusters need to be used on and off in situations where opening a menu is not the best.

**Comment by nmajask** [comment]
> Why cam borgs download the id modification program?

Fixed

> Would it be possible to keep the thruster button and to move the management to the left of the camera instead?
> 
> I feel like the thrusters need to be used on and off in situations where opening a menu is not the best.

I'm just going to readd the verbs and buttons that were removed in the original PR latter, there is very little reason to remove them

**Pull request merged**
