### PR TITLE
Adds whitelist for jobs

### PR DESCRIPTION
**Pull request by Bibby0110**
see title

### CODE REVIEW

**Comment by Moja10** [comment]
For synths, I presume?

**Comment by Bibby0110** [comment]
> For synths, I presume?

maybe

**Comment by 00ze-cyclone** [comment]
Literally useless since you use it for nothing.

**Comment by Bibby0110** [comment]
> Literally useless since you use it for nothing.

so?

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Admin only + Bloat + Closed

**Review by ynot01 — CHANGES_REQUESTED** [review]
Add a way for admins/council/literally anyone to whitelist without having to reach into the server and modify the json file directly

**Comment by KingSuperBOB** [comment]
Only possible job I can see needing a use for this is synths

**Pull request closed without merging**
