### PR TITLE
Baseball Bat Rework + New Bats

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

you can't use baseball bats to knockback yourself for turbo-speed movement (can still hit yourself)
Baseball bats can now be made by crew again with wood; but to compensate Traitors and BloodBrothers can now craft Titanium Baseball Bats, which hit harder and have knockback, and a 30% chance to stun if your target's head is uncovered and you aim at the head.
Swaps wooden bat recipe for titanium bat recipe in the makeshift weapons book
tweaks costs and values for wooden bats as well
baseball bats in general do more damage now, 16 for wood, 18 for titanium, but have severely reduced AP (-30/-25 respectively), and have positive wound bonuses (with huge bare wound bonuses)

had to repath a bunch of shit because of making baseball bats two handed

# Spriting

tatorbat
toybat

Inhand sprites:
ss (2022-09-01 at 08 53 06)

# Wiki Documentation

Will need new entries added to the uplink items page, vendor page, possibly anywhere toy items are mentioned, and guide to combat

# Council

 Might...need to add the donk bats to the metashield, potentially

# Changelog

:cl:
rscadd: Adds new Toy Baseball Bat crafted with 6 plastic, and puts them in the Donksoft vendor normal stock
rscadd: Adds new "Toy" Baseball Bat (It's a baton) to the Uplink for 6TC & 2 in the Hacked Donksoft Vendor
rscadd: Adds recipe for metal baseball bats to the makeshift weapons book, for 10 titanium with a welder
rscdel: removes recipe for wood baseball bats from the makeshift weapons book
bugfix: baseball bats now check if the person they're knocking back is their own user
tweak: wooden baseball bats may now be crafted for 10 wood by everyone, but can't throw people when hit
tweak: reenables baseball bat bounties
tweak: Baseball bats dont hurt if thrown
tweak: Titanium and Wooden bats are now two-handed only
tweak: baseball bats do more damage with negative armor penetration, but cause lots of wounds
soundadd: added new sounds for baseball bats, and some future setup for wood noises
imageadd: added new toy and donk baseball bat sprites
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
I'm not sure if making wooden bats break is much of a nerf, since wood is plentiful enough (assuming competent Botanists) that you can just make dozens - even if the bats can't be carried, you can have a metric fuckton of wood in your backpack.

**Comment by 00ze-cyclone** [comment]
The crew baseball bat doesn’t need durability now that it can’t knockback imo.

**Comment by VaelophisNyx** [comment]
what if we made wood bulky?

**Comment by VaelophisNyx** [comment]
> The crew baseball bat doesn’t need durability now that it can’t knockback imo.

I agree but I want @ToasterBiome or @JamieD1's input on this

**Comment by Cartlord** [comment]
It MIGHT be a good idea to make bats (either wooden bats or both types, but not just syndiebats) Wielded, to keep people from dual-wielding them to make durability moot - it looks like five swings break it, but dual-wielding will mean you can comfortably kill anyone who isn't armored up or dosed with healing chems without worrying about running out of killing power.

**Comment by Marmio64** [comment]
dont know if im reading it right, but wooden baseball bats will now have durability (really poor durability at that), cant knock people back, AND are two handed? What purpose will there be to make a baseball bat when spears deal way more damage, have the reach advantage, are sharp, have more durability, and can be thrown for a bunch of damage? Is the only advantage that it can be made with just wood?

**Comment by VaelophisNyx** [comment]
pretty much. I don't want to hand out decent melee weapons for incredibly cheap material costs to the crew, but baseball bats being traitor-only at all sucked

**Comment by VaelophisNyx** [comment]
drafting because I expect merge conflicts soon

**Comment by VaelophisNyx** [comment]
baseball bats now do not break, but also do 2 more damage to be in line with a toolbox.

**Review by cuackles — APPROVED** [review]
yes

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
