### PR TITLE
Stops Staff Crapping Eggs - Disables Rad Goat from Anomaly for now

### PR DESCRIPTION
**Pull request by JamieD1**
Disables Rad Goat from Anomaly for now

Staff yelled at me.

:cl:  
rscdel: Removed goat from anoms for now
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
admin egg rp is real

**Comment by Moltijoe** [comment]
hold up, how was this fucking with staff? is radiation that much of a nightmare?

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> hold up, how was this fucking with staff? is radiation that much of a nightmare?

me making anomaly slimes (already unfun to admin) except they are invincible and shit radiation literally everywhere and also 20 of them come out of 1 anomaly instead of 1

**Comment by ShoziOffical** [comment]
> > hold up, how was this fucking with staff? is radiation that much of a nightmare?
> 
> me making anomaly slimes (already unfun to admin) except they are invincible and shit radiation literally everywhere and also 20 of them come out of 1 anomaly instead of 1

its only 1 per anomaly

**Comment by neeshacark** [comment]
> > > hold up, how was this fucking with staff? is radiation that much of a nightmare?
> > 
> > 
> > me making anomaly slimes (already unfun to admin) except they are invincible and shit radiation literally everywhere and also 20 of them come out of 1 anomaly instead of 1
> 
> its only 1 per anomaly

not true, last time i saw it (yesterday) it spawned 4 or 5

**Comment by ShoziOffical** [comment]
> > > > hold up, how was this fucking with staff? is radiation that much of a nightmare?
> > > 
> > > 
> > > me making anomaly slimes (already unfun to admin) except they are invincible and shit radiation literally everywhere and also 20 of them come out of 1 anomaly instead of 1
> > 
> > 
> > its only 1 per anomaly
> 
> not true, last time i saw it (yesterday) it spawned 4 or 5

read changelogs, it has been updated yesterday

**Comment by BurgerLUA** [comment]
> hold up, how was this fucking with staff? is radiation that much of a nightmare?

I think what was happening is that in a lot of cases, the goat killed 10+ people because of how immortal the goat actually is. The nuclear particles heal 10 brute and 10 burn per hit on the goat, and many particles spawn on demand via the new goat spell.

The radiation is probably a problem too. It passively harms when near people so if you don't attack it, it can radiate the crew. If you do attack it, it straight up can kill you and outheal any damage done by the crew (even with powerful melee weapons or ranged weapons).

**Comment by ShoziOffical** [comment]
> > hold up, how was this fucking with staff? is radiation that much of a nightmare?
> 
> I think what was happening is that in a lot of cases, the goat killed 10+ people because of how immortal the goat actually is. The nuclear particles heal 10 brute and 10 burn per hit on the goat, and many particles spawn on demand via the new goat spell.
> 
> The radiation is probably a problem too. It passively harms when near people so if you don't attack it, it can radiate the crew. If you do attack it, it straight up can kill you and outheal any damage done by the crew (even with powerful melee weapons or ranged weapons).

i have nerfed the goat health and healing from particles in another pr, also radiation is not really a problem you can kill the rad goat and gib it to remove rad

**Review by MajManatee — APPROVED** [review]
Hmm yeah i guess this code checks out... Not the best ive seen but alright

**Pull request closed without merging**
