### PR TITLE
Babby's first PR - autolathe and service protolathe can now make mousetraps

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

Mousetraps are a finite resource on the station for some reason and janitors can run out of them. Also adds to autolathe since every other ob/item/assembly/ thingy including signallers are printable on autolathe so

#### Changelog

:cl:  
rscadd: Mousetraps now printable in autolathe and service protolathe
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
nice

**Comment by monster860** [comment]
you can already make these using cardboard but that's just as limited as mousetraps.

**Comment by Ratvar** [comment]
Cardboard is massprinted  by cargo and botany both, and you can reuse your own box. I have suspicions you're adding ot to autolathes because it's ob/item/assembly/ thingy, aka grenade component.

**Comment by ghost** [comment]
> Cardboard is massprinted by cargo and botany both, and you can reuse your own box. I have suspicions you're adding ot to autolathes because it's ob/item/assembly/ thingy, aka grenade component.

"Also adds to autolathe since every other ob/item/assembly/ thingy including signallers are printable on autolathe so"

Yes, I did say I'm adding it there since every other grenade assembly is available under autolathe.

**Comment by MegaEmpirical** [comment]
What's the point of mouse traps for mice? I just bash them.

**Pull request merged**
