### PR TITLE
Adds the Citadel bar as a bar template

### PR DESCRIPTION
**Pull request by monster860**
It's a pretty decent bar

image

:cl: monster860
add: Adds the bar from Citadel as a bar template that can spawn sometimes
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
erp is bad

**Comment by ynot01** [comment]
no erp

**Comment by athena413** [comment]
erp

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
It's a nice bar, a few issues though:
- Copy across the dinnerware vendor across from the other bar maps, since the one you used has mustard which doesn't exist here, and also has different contraband which is map edited in.
- 2 sofas need their left and right sides switched.
- Firelocks need changing from the full tile ones.
- The theatre airlock tile should be the theatre area, not bar, just to keep the standard across all the bar maps.
- The north bar camera has no name (c_tag).
- I'd change the flooring under the theatre + hallways airlocks to normal plasteel (instead of dark). Kitchen airlock flooring should be changed to the kitchen floor instead of the bar floor.
- Add another arcade machine above the current one.

**Comment by monster860** [comment]
did the things

**Pull request merged**
