### PR TITLE
Da great American foods update. Many many hamberders, resprites and more!

### PR DESCRIPTION
**Pull request by Hopekz**
ports tgstation/tgstation#48050

**Wow, this one was a doozy. FUCK**
fixed for our codebase.
Lots of content tested it as much as I could.

Original Description:
"
This PR adds the following new dishes:

Cheese burger
Soylent burger
McRib
McGuffin
Chicken Sandwich
Fiesta Skewer
Boritos corn chips
Chicken meat & cutlet

This PR also resprites many old burgers such as:
Hamburger
Filet-o-Fish sandwich
Bacon burger
Big bite burger
Super big bite burger
Five alarm burger
Ghost burger

Some burger recipes have been changed to better match the sprite and ghostburger has been reworked to be much spookier.
69885376-15246300-12dd-11ea-97ae-ce7095c277c7 1
69885560-038f8b00-12de-11ea-922f-1b6e89610e36 1
69885558-fe324080-12dd-11ea-918c-5bf9d2bc6cf5 1

burg_comparasion
fiesta64
ghostburgerglow64

Why It's Good For The Game
Many of the current burger sprites are pretty sad and fast food is a fun chef gimmick.
"

#### Changelog

:cl:  
add: Several new burgers.
add: Fiesta skewer, corn chips & chicken meat.
del: some old burger sprites have been replaced.
tweak: The ghost burger is much spookier.
balance: some burger recipes have been tweaked.
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
big bite isnt big enough otherwise these are good

**Comment by missatessatessy** [comment]
Making me hungry D:

**Comment by Readystorm546** [comment]
Cant we get fucked for calling it a McRib??? Why dont call it something else like the N-Rib or the N-Guffin

**Comment by fluffe9911** [comment]
I dont think we ever ported the grill pr which adds the bbq stuff

**Comment by Codeatmos** [comment]
I don't think we have ported the BBQ yet, we should I need to lube up mah arteries with some alabamaian steak sauce

**Comment by Hopekz** [comment]
> I dont think we ever ported the grill pr which adds the bbq stuff

I pulled a sneaky one on you. 
I removed the BBQ sauce from the BBQ (Since BBQ sauce doesn't exist in our codebase yet).
But you are right the BBQ ribs themselves don't really have a way to spawn in to our world without admin intervention so those will lay dormant until someone ports the BBQ portion.

**Comment by Krysonism** [comment]
> big bite isnt big enough otherwise these are good

I agree, however, I need to find a good spacer layer to extend it or it won't look right. It is still pretty huge due to the increased girth compared to the old super big bite.

>Cant we get fucked for calling it a McRib??? Why dont call it something else like the N-Rib or the N-Guffin

 I did consider giving it a parody name like I did with the McGuffin. I think however that the name is quite iconic and the game already has a number of real product names with no issue so far(kahlua, patron and goldschläger for example).

**Comment by Hopekz** [comment]
@Krysonism welcome to my port of your PR

@fluffe9911  do I need to do anything about these conflicts? I thought that was maintainer responsibility.

**Comment by Hopekz** [comment]
@Ihonkification 
Its been 11 days are you going to approve or deny these sprites?

**Comment by alexkar598** [comment]
Conflicts are your responsibility

**Comment by Hopekz** [comment]
Closing this.
Unable to fix this at the moment.
Might return to it later but I'm unsure at the moment.

**Comment by Hopekz** [comment]
**To anyone that wants to pick it up:**
all that needs to be resolved for the conflicts would be the icon sprites otherwise no changes to the actual code past my edits are necessary to the best of my knowledge.

**Pull request closed without merging**
