### PR TITLE
Undoes ThatLings Stealth Zombie and Shadowman removal 

### PR DESCRIPTION
**Pull request by fluffe9911**
Atleast make a seperate pr or something really ling lol

### CODE REVIEW

**Comment by ThatLing** [comment]
Not happening

**Comment by fluffe9911** [comment]
You still stealth removed it though is that even allowed?

**Comment by fluffe9911** [comment]
And the zombie thing I can get cause of the whole hard to kill thing but why shadow man? if someone wants to be a edgy maint dweller let em lol-

**Comment by ThatLing** [comment]
How is it a stealth remove if the PR title literally was "Removes vampires and shadowlings from halloween".

**Comment by fluffe9911** [comment]
Cause no where in the title is the word zombie mentioned once?

**Comment by fluffe9911** [comment]
You dont look at the title and think oh boy they must be removing vampires shadowlings and zombies no just shadowlings and vampires this was literally a stealth removal lol

**Comment by ThatLing** [comment]
```
And the zombie thing I can get cause of the whole hard to kill thing
```
life comes at you fast

**Comment by fluffe9911** [comment]
As I said I can get it but does not change the fact it was a stealth removal lol

**Pull request closed without merging**
