### PR TITLE
Handcuffed people may no longer just walk through turnstiles

### PR DESCRIPTION
**Pull request by JamieD1**
Handcuffed people may no longer just walk through turnstiles

:cl:  
bugfix: Handcuffed people may no longer just walk through turnstiles  
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
skill issue

**Comment by NCRLouTenant** [comment]
But how else can I punish the sec officer who trusts me enough to let go of me before putting me in a cell? 

It does make sense but there is something fun about trying to bolt it out of sec and getting disablered as you run down the hall.

**Comment by JamieD1** [comment]
> But how else can I punish the sec officer who trusts me enough to let go of me before putting me in a cell?
> 
> It does make sense but there is something fun about trying to bolt it out of sec and getting disablered as you run down the hall.

Its not funny, its annoying. We added turnstiles with the intention of genpop being a thing. Not to let people escape sec easier.

**Comment by NCRLouTenant** [comment]
> > But how else can I punish the sec officer who trusts me enough to let go of me before putting me in a cell?
> > It does make sense but there is something fun about trying to bolt it out of sec and getting disablered as you run down the hall.
> 
> Its not funny, its annoying. We added turnstiles with the intention of genpop being a thing. Not to let people escape sec easier.

That's fair enough. I would at least try to make it fun but I do see how aggravating that would be in a situation where the person being arrested isn't the only sec issue

**Comment by ToasterBiome** [comment]
> > But how else can I punish the sec officer who trusts me enough to let go of me before putting me in a cell?
> > It does make sense but there is something fun about trying to bolt it out of sec and getting disablered as you run down the hall.
> 
> Its not funny, its annoying. We added turnstiles with the intention of genpop being a thing. Not to let people escape sec easier.

don’t let them go

**Comment by JamieD1** [comment]
> > > But how else can I punish the sec officer who trusts me enough to let go of me before putting me in a cell?
> > > It does make sense but there is something fun about trying to bolt it out of sec and getting disablered as you run down the hall.
> > 
> > 
> > Its not funny, its annoying. We added turnstiles with the intention of genpop being a thing. Not to let people escape sec easier.
> 
> don’t let them go

What a bad take.

**Review by ToasterBiome — APPROVED** [review]
I think this is stupid but the code does what it says

**Pull request merged**
