### PR TITLE
Piping, disposals. APC & Map Tweak rework [MDB IGNORE]

### PR DESCRIPTION
**Pull request by JamieD1**
Replaced all pipes on the map,
Replaced all Disposals,
Replaced all Wiring and moved APCS INTO Departments ( Patch for Clockies/Sling coming very soon)
Added Papershredders, fax machines to Heads offices including Warden, laywers, detective, QM.

:cl:  
rscadd: Replaced all pipes on the map,
rscadd: Replaced all Disposals,
rscadd: Replaced all Wiring and moved APCS INTO Departments ( Patch for Clockies/Sling coming very soon)
rscadd: Added Papershredders, fax machines to Heads offices including Warden, laywers, detective, QM.
bugfix: Gaminada: fixed xenobiology camera not seeing the entire lower-righthand cell + xenobio shutter button access, and a rogue wall light under robotics
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Made the MapDiff get ignored, but its a huge mapping reworking, what did Jamie mean by this??? What kind of secrets is he hiding from the Yogstation Public? 

"As the coders learned so painfully in Yogstation's final century, free flow of information is the only safeguard against tyranny. The once-chained players whose headcoders at last lose their grip on information flow will soon burst with freedom and vitality, but the free server gradually constricting its grip on public discourse has begun its rapid slide into despotism. Beware of he who would deny you access to information, for in his heart he dreams himself your master." - Community Manager Yogurtshrimp69

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Changelog

**Comment by maxion12345** [comment]
yeah why are we replacing everything again

**Comment by ToasterBiome** [comment]
making the scrubbers/vents in the middle of the hallway instead of the pipes makes me angrily shake my fist at you

**Comment by patpol4** [comment]
Um, did anyone review this

**Comment by Marmio64** [comment]
moving all the APCs into the departments is a pretty big change to merge in just a few days

**Pull request merged**
