### PR TITLE
adds lobster claw boxing glove reskin to autodrobe

### PR DESCRIPTION
**Pull request by LazennG**
# Document the changes in your pull request
Completes the lobster set in the clown vendor with lobster gloves, a boxing glove subtype

# Wiki Documentation
Add '1x lobster claws' to the autodrobe vendor list, right below the foam lobster suit.
lobster_claws_item

# Changelog
:cl:  
rscadd:added lobster boxing gloves to autodrobe
imageadd: added lobster glove worn and item sprites 
/:cl:
@cuackles threatened me at clawpoint to make this help me

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Spongebob me boy...

**Comment by LazennG** [comment]
> 

ayo that last pic has them wearing airshoes, im thinking whoever took it is pretty amazing and smart and talented even??

**Comment by maxion12345** [comment]
ok make knife-lobster-gloves for makeshift weapons

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
