### PR TITLE
some dude whined to me on discord about the large energy crossbow and sent me the stupidest OOC conversation i've ever seen so i made it literally just only a lethal weapon because you're all dumb

### PR DESCRIPTION
**Pull request by ghost**
have fun it does no stamina damage now but it still has the same damage and it also knocks down for less because one shot from that thing is a guaranteed kill anyway

### CODE REVIEW

**Comment by UselessTheremin** [comment]
uuhh are you okay

**Comment by ghost** [comment]
no i've been kind of worried about a friend recently thank you for asking

**Comment by Tipy1802** [comment]
God why it’s a late game science researchable that rarely gets researched and even more rarely used. I think security getting some actual upgrades if they work with science is actually good

**Comment by Mqiib** [comment]
What if instead of this being an infinite energy slow-firing double damage laser gun/disabler that knocks down we instead just made it do significantly less actual damage so that it's not "lethal that knocks down"?

**Comment by Tipy1802** [comment]
Also it’s not a guaranteed kill since security cannot just kill people...

**Comment by ghost** [comment]
@Tipy1802 

> security cannot just kill people

ahahahahahahahahahahah
ahahahaha
ahahahahahaha

also lategame researchable weapons are not immune to balance-the fact that the gun outright both knocks down, does 60 stam damage, 40 tox damage means that one shot guarantees the person's fucked as a second followup shot stamina crits and a third shot regular crits

it's basically an infinite, free, recharging tazer, much more powerful than the disabler, AEG etc

think about it, it's a 40 damage gun that knocks down *and* disables limbs in one hit

**Comment by ghost** [comment]
like sec gets the ion carbine, which is good, the aeg, which is good, the particle rifle, which has some good uses, lots of advanced shotgun stuff, telescopic riot shields, nightvisions, and if they cooperate with genetics thermals et cetera-they get a lot of good upgrades, and the detective will cream his fucking pants if someone researches exotic ammo

they also get smartmines, etc

the one thing that stretches this is the energy crossbow-where all other guns have some niche uses or are simply upgraded variants of the egun in the case of the aeg, the energy crossbow is just a one hit win button that doesn't have any ammo concerns

any

ammo concerns

because unlike the shotgun,or the wt rifle, there's no ammo management, and it inflicts higher damage than the laser rifle of a damage type that can't be healed in bursts because it has to be healed over time through chems, and also does a flat 2hit stamina stun while also knocking down on the FIRST hit

that's an extreme, y'know?

**Comment by ReddicusDragon** [comment]
adam strikes again

**Comment by JamieD1** [comment]
Discussion and looking into.

**Comment by Tipy1802** [comment]
yeah let's nerf sec for the 21879351672895 becuase ban evading Adam had an IDED moment, why not maybe finally people will stop playing sec and adam can get his free greentexts and we will reach the NRP greytiding shithole you want yogs to be

**Comment by Tipy1802** [comment]
Once again this is a VERY late game science researchable weapon which REQUIRES the decontrusction of a sybdicate item. Security will have to capture a traitor, find a syndie item on him then give it science (while risking said scientist being a traitor himself and just pocketing it) and research the illegal technolgoy node. Yes I do belive that security should be able to get stuff that are stronger than their round start gear in the late game if they work together with a different department, that's what MRP is, interactions between different departments and not doing things solo

**Comment by Amelia0010** [comment]
There already were 3 days of discussion 
image

**Comment by JamieD1** [comment]
> There already were 3 days of discussion
> image

Changes, not this specific PR you clown. Could change the weapon in other ways.

**Comment by Tipy1802** [comment]
Then why leave the PR that has a very specific idea of how to chanage the item open. People discus the PR in question in here. Isn't Dev-public the place for broader discussion?

**Comment by Reed0506** [comment]
imagine toxin damage being annoying to heal

this post was made by plant gang

**Comment by ghost** [comment]
@Tipy1802 

None of that matters because it's overpowered.

I'm not trying to make yogs a 'NRP greytiding shithole.' In fact, i'm doing the opposite of that.

And i'm not ban evading, contrary to what you may think. You couldn't force me to play on this shithole with a gun to my head. I'm just bored.

It's now a purely lethal weapon. There's nothing wrong with that, it just disincentivizes security players from treating it as a *nonlethal* weapon. And there's a distinction between 'stronger than roundstart' (which they should get, hence AEGs, and why I plan to buff tesla revolvers), and 'overpowered' (which is this gun.)

**Review by alexkar598 — APPROVED** [review]

**Comment by alexkar598** [comment]
Considering the weapon does 40 damage and you can can crit someone via 4 shots if theyre super armoured, 3 on average and 2 if youre lucky:

The stun honestly, doesnt really matter, from the first shot, 40 damage is more than enough to give a considerable slowdown making it super easy to chain another hit and if they're not already in crit by that point, theyre so slow you could get the person with the worst aim ever to get a hit on them. By the third shot, they need to be very armoured to not be dead.

The stamina damage doesn't matter at all, the person will be an inch from softcrit by the time they hit stamcrit so the weapon is already horrible at non lethal takedowns and only useful in lethal takedowns so there's no real purpose in merging this PR, as it stands, the large energy crossbow is currently a lethal weapon already, being overshadowed by even the standard disabler in terms of stun power. PRs shouldn't turn around and change their features two weeks after it has been opened so if you wish to tweak the large energy crossbow in another way, please do so in another PR.

**Pull request closed without merging**
