### PR TITLE
Culls Wizard Academy Outright

### PR DESCRIPTION
**Pull request by alao3alao3**
Throws the whole damn space ruin out, and fixes up where it's referenced in coding.

# Why is this good for the game?

The ruins lousy, and if not cheesed to be an utter cakewalk with the anti-magic hardsuit (the only thing that really stops magic and stops it 100%), it's terribly difficult with little payout among other things. Removal was fairly popular I heard, and it's unknown to me why more people couldn't bring themselves to remove some goddamn map file and edit some code (though I'm pretty sure fluffle talked those other prs down, wonder how).

#### Changelog

:cl:  
rscdel: Removes Wizard Academy ruins and the mentioning of it in the space ruin file  
/:cl:

### CODE REVIEW

**Comment by alao3alao3** [comment]
shit if its too far they'll be free to downvote it

**Comment by UselessTheremin** [comment]
thats not how you delete it, just make it unable to generate, doing it this way may cause errors and is overall not a good idea.

**Comment by UselessTheremin** [comment]
for an example, see this PR: https://github.com/yogstation13/Yogstation/pull/5936/files

**Review by patpol4 — CHANGES_REQUESTED** [review]
Disable it in the blacklist config file, not this.

**Comment by Marmio64** [comment]
i can just revamp this

**Comment by alao3alao3** [comment]
if you can blacklist it proper in another PR before I get to it all the better

**Comment by boodaliboo** [comment]
this pr needs to be changed to just blacklist it otherwise it wont be possible to merge

**Review by patpol4 — APPROVED** [review]
I think this should work? Jamie take a look at this

**Comment by JamieD1** [comment]
@Marmio64 If you rework it ill re-enable it.

**Pull request merged**
