### PR TITLE
Reduce the weight of asimov and crewsimov

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Reduces the spawn weight of crewsimov and asimov, as they are very similar laws. Currently an AI will get one 57% of the time, this reduces that to 40%, the same as CEO.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
tweak: tweaked weight of asimov and crewsimov
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
we really just need more lawsets :(

**Comment by adamsong** [comment]
See other PRs

**Comment by Moja10** [comment]
The point is that they are so common because they are the most sane/workable of the roundstart lawsets, its a good thing they appear so much

**Comment by JamieD1** [comment]
This is on purpose as we used to have issues where ais used to get validhunting laws every round.

**Pull request closed without merging**
