### PR TITLE
Makes vote weight and preferred map actually work

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

Vote weights are currently not considered during the voting process. Now they are.

# Changelog

:cl:  
bugfix: fixed vote weights not working
bugfix: fixed preferred map pref not working
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
yes we can

**Comment by MajManatee** [comment]
alternate idea
every 10 rounds, it picks each map to be played twice , and whatever map wins the vote gets played an additional two times, then it randomly rotates through the 10 map list until expended, and re-votes.

**Comment by adamsong** [comment]
Sounds like a meme

**Comment by Marmio64** [comment]
i personally disagree with vote weight in the first place. People already vote for other maps and they get played, why do we still need a bias against box? Only argument I could see that would make logical sense would be because a lot of players would keep the default option as their preferred map (box), but could you not just have it pick a random default map if it already doesn't do something like that?

**Comment by patpol4** [comment]
Its literally just a bugfix, this was decided long ago

**Review by ynot01 — APPROVED** [review]
Voting weights are a thing and have been for a long time (with staff and coders assuming that they worked), if you disagree with them in their current form then we can disable the weights in another PR

**Pull request merged**
