### PR TITLE
[PORT] New backpack/satchel/duffle sprites

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

A port of a couple PRs from TG:
https://github.com/tgstation/tgstation/pull/68524
https://github.com/tgstation/tgstation/pull/77398

RIPS THE SOUL OUT OF ALL THE BACKPACKS, SATCHELS AND DUFFLES IN EXCHANGE FOR NEW SOULLESS SPRITES.

This PR DOES NOT add the duffels that TG has which we don't, maybe another day.

# Why is this good for the game?
Removes soul (these look nicer)

# Spriting
image
image

These images are not exact, some of the bags we do not have for example and the clothing on the mobs is not included, this is simply the sanest way for me to showcase the sprites without manually doing what they did and slowly doing it all ingame.

# Changelog

:cl:  PositiveEntropy, Triiodine, CliffracerX, Cark
imageadd: New dufflebag/satchel/backpack sprites.
imagedel: Old duffle/backpack/satchel sprites replaced with new versions.
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Whatabout the mining satchel? or was that not touched?

**Comment by neeshacark** [comment]
> Whatabout the mining satchel? or was that not touched?

not touched by either pr

**Review by MajManatee — APPROVED** [review]
My drip is unaffected 👍 
Although there is the concern of the clashing styles, but I'm not a spriter.

**Comment by neeshacark** [comment]
after this goes through im porting messenger bags btw

**Comment by cuackles** [comment]
sorry but i consider this sprites wouldn't fit well , they have a lot of banding in general and feel out of place since they are so saturated

**Comment by neeshacark** [comment]
Maybe in 2024

**Pull request closed without merging**
