### PR TITLE
makes bullets easier to land hits with

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

All bullets have been doubled in speed (0.8 deciseconds per tile -> 0.4)

Sniper rounds have been buffed to accomodate (0.4 -> 0.3)

Energy/non-bullet projectiles untouched

## Rationale

i think this will incorporate an interesting new dynamic to bullet vs energy combat

bullets should not be outran or dodged

bullet gameplay will be improved when you click on someone and the shot connects unless they dodge it by a hair which can still happen

energy weapons can go through glass and are usually much more spammable than bullet weapons and are not bullets

# Changelog

:cl:  
tweak: bullets are now twice as fast
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
You shouldn’t dodge light either but now bullets are faster than light

**Comment by 00ze-cyclone** [comment]
You are telling me energy are more spammable than bullets when all ballistics let you carry a billion spare bullets. Are you just trolling at that point?

**Comment by ynot01** [comment]
> You are telling me energy are more spammable than bullets when all ballistics let you carry a billion spare bullets. Are you just trolling at that point?

disablers carry 20 shots
lasers carry 12

shotguns carry 5-7
stechkin carries 8
.357 carries 7

your immediate magazine is what you'll be fighting with, if you run out you are forced to reload (death) or retreat

**Comment by Notamaniac** [comment]
> > You are telling me energy are more spammable than bullets when all ballistics let you carry a billion spare bullets. Are you just trolling at that point?
> 
> disablers carry 20 shots lasers carry 12
> 
> shotguns carry 5-7 stechkin carries 8 .357 carries 7
> 
> your immediate magazine is what you'll be fighting with, if you run out you are forced to reload (death) or retreat

But shotguns crit in 3 and the stetchkin in 4. Disablers only stun in 4 and lasers need 5 to crit. And if you need to 'reload' with a laser you either have another lasergun to pull out  (not a given, and lasers take up more space than a mag), or you run away. 

Don't we already have problems with the L6 SAW being capable of gunning down a dozen crew members with a single mag?

Please remember this is a game, and that fun should probably come before realism.

**Comment by 00ze-cyclone** [comment]
Don’t bother arguing it’s just some meme PR to troll.

**Comment by Cartlord** [comment]
I figured the purpose of this was just to make it so that CHOOMists couldn't stack speed boosts and outrun lethals

**Review by Bibby0110 — APPROVED** [review]
Looks fine. Have some concerns about lag but they're not that big

**Pull request merged**
