### PR TITLE
Undoes a stupid PR that only a few people wanted

### PR DESCRIPTION
**Pull request by Nickvr628**
Reverts #6967
:cl:  
rscadd: You can now buy ALL original shuttles as the captain, just don't be an idiot and get bwoinked over it. Admins must now do their jobs instead of having HCs mechanically limit any potential rulebreaking that might occur, all because the HCs decided two years ago pre-rebase that no fun is allowed. 
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Why are you allowed here again

**Comment by HomocidlePancakes** [comment]
What did he do wrong that he shouldn't be allowed?

**Comment by Hopekz** [comment]
> Why are you allowed here again

Rude.
If Adam can be taken seriously for posting a meme PR while banned I think Nick is allowed to be taken seriously for posting a PR as well.

**Comment by OppressedCactus** [comment]
Why was the original PR merged when the majority of comments disliked it and there were almost double the thumbs down than thumbs up?

**Comment by AsV9** [comment]
No.

**Comment by boba247** [comment]
This was closed before I could even thumbs up it. Head coders are on a power trip

**Comment by ynot01** [comment]
reopen pls

**Comment by Nickvr628** [comment]
fuck you asv, the 24 hour rule applies for non-meme PRs even if you disagree with them

**Comment by alexkar598** [comment]
This PR will be closed in 22 hours

**Comment by nichlas0010** [comment]
mane the rule is to not merge PRs in 24 hours, not to not close them

**Comment by Mr-Space** [comment]
taptaprip

**Comment by nichlas0010** [comment]
nickvr is just salty since he died to a headcoder last round

**Comment by ThatLing** [comment]
@nichlas0010 If it's invalid, just close it

**Comment by MegaEmpirical** [comment]
It's my opinion that we should have been banning non-antags for buying the disco shuttle. We don't need this shit.

**Comment by MegaEmpirical** [comment]
When I say we don't need this shit, I mean this PR.  We shouldn't have to deal with people buying these shuttles when they shouldn't be buying them EVER, so locking them behind an emag makes sense.

**Pull request closed without merging**
