### PR TITLE
New sprites for food, chairs, stasis

### PR DESCRIPTION
**Pull request by jcatjmeow**
### Intent of your Pull Request

New sprites! Check the icondiff bot down below.

#### Changelog

:cl:  
imageadd: Revamped sprites for some food, chairs, and the stasis beds by Salla!
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
The foods , chairs and stasis bed should be 3 separate PR's tbh

**Comment by jcatjmeow** [comment]
> The foods , chairs and stasis bed should be 3 separate PR's tbh

if someone like a headcoder recommends this I'd be glad to!

**Comment by boodaliboo** [comment]
this sohuld be 3 prs

**Comment by Partheo** [comment]
Yeah, please atomize these categories.

**Comment by Hopekz** [comment]
if🤔🤨🤔 someone like👬 a🅰️🅰️ headcoder recommends this👇👉😑 I😜😝😜😝'd be🐝🐝🐝 glad to🤔🤔🤔!

**Comment by jcatjmeow** [comment]
sorry pressed the wrong butt

**Pull request closed without merging**
