### PR TITLE
Lizard Exclusive Emote: Weh

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Lizards can weh.

Ported from Shiptest which was ported from Skyrat.

https://github.com/yogstation13/Yogstation/assets/30399783/388619c5-bf6f-452e-a297-e9d2efc18742

# Why is this good for the game?
Improves the quality of role play that occurs on this fine server by expanding the catalog of emotes available to the player base for the purposes of socializing, role playing, and immersion as a lizard.

# Testing
I *weh as a lizard. Human Moja cannot *weh.

# Changelog
:cl:  
rscadd: Lizards can *weh.
soundadd: Weh.
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
image

**Comment by Runian** [comment]
Everyone be hating on *nya and *awoo. But good thing that this isn't that.

**Comment by Moltijoe** [comment]
> Everyone be hating on *nya and *awoo. But good thing that this isn't that.

i want those removed too
i have no problem with them existing, but people have shown time and again that they can not be trusted with such power

**Comment by Runian** [comment]
> > Everyone be hating on *nya and *awoo. But good thing that this isn't that.
> 
> i want those removed too i have no problem with them existing, but people have shown time and again that they can not be trusted with such power

I don't see how bad of an issue this is if people can already emote spam *meow, *snap, *flip, *clap, *hiss, *crack or any other emote that is very noticeable or make a sound which are all spammable (except flipping, but you can do that in moderation).

**Comment by azzzertyy** [comment]
what the fuck is a weh

**Comment by Moltijoe** [comment]
> I don't see how bad of an issue this is if people can already emote spam *meow, *snap, *flip, *clap, *hiss, *crack or any other emote that is very noticeable or make a sound which are all spammable (except flipping, but you can do that in moderation).

i don't like those either (flip really isn't that bad though, and it's funny when people faceplant)
you also forgot *scream

**Comment by Runian** [comment]
> > I don't see how bad of an issue this is if people can already emote spam *meow, *snap, *flip, *clap, *hiss, *crack or any other emote that is very noticeable or make a sound which are all spammable (except flipping, but you can do that in moderation).
> 
> i don't like those either (flip really isn't that bad though, and it's funny when people faceplant) you also forgot *scream

I think you can bypass faceplanting if you manually ctrl+v *flip into your textbox. Anyways, approve because code works? :)

**Review by Moltijoe — CHANGES_REQUESTED** [review]
please include the sound in the pr description

**Comment by Runian** [comment]
Done. 💯

**Comment by Mqiib** [comment]
> what the fuck is a weh

This is also a question I have because it doesn't sound like something a lizard would do. I would prefer tail thump from shiptest, at least that one makes sense.

**Comment by ju45he** [comment]
if this doesnt get merged then the codebase will literally implode

**Review by Moltijoe — APPROVED** [review]
code is FINE

**Comment by Hislyna** [comment]
> code is FINE

Molti tryna ensure they don't get cancelled

**Comment by SomeguyManperson** [comment]
> > Everyone be hating on *nya and *awoo. But good thing that this isn't that.
> 
> i want those removed too i have no problem with them existing, but people have shown time and again that they can not be trusted with such power

We do not have either nyaa nor awoo, they were posited in a similar scenario and rejected for similar reasons

**Comment by MajManatee** [comment]
unfortunately, I cannot close a pr for being cringe

**Comment by thgvr** [comment]
Weh.

**Comment by ShadowDeath6** [comment]
I'd rather have the screech that the xenobio frogs have as an emote than this noise, I don't think I've ever heard anything like this from any creature at all let alone a reptile

**Comment by Moltijoe** [comment]
Closed, if even lizard mains don't want it then there's no reason to add this

**Comment by thegoldencat413** [comment]
i thought the birds did weh

**Pull request closed without merging**
