### PR TITLE
Bots now turn off when the area is unpowered

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

Bots will now turn off after taking some actions in an unpowered area, whether the APC be drained of power or there be no APC at all (auto-powered areas will still support bots)
Note: bots do not consume a noticeable amount of power from APCs

Tested; functional

### Why is this good for the game?

Bots will no longer glow or function when the area is unpowered
Bots can still be used for a short amount of time before turning off due to lack of power
Better reflects the desolate feel when bravo 6 goes dark and everything electronic is unresponsive
Beepsky can ignore this because he has a potato battery

#### Changelog

:cl:  
tweak: Bots now turn off when the area is unpowered
tweak: Beepsky ignores power because he has a potato battery
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
This makes no sense. They are not connected to the powergrid they use batteries

**Comment by ynot01** [comment]
> they use batteries

No, they don't

**Comment by Hopekz** [comment]
Are you going to put in new behavior for bots to avoid moving themselves to an area without power like the space walking example you provided?
Seems weird that a bot would willingly turn itself off by moving to a powerless zone.

**Comment by patpol4** [comment]
An apc powers the area wirelessly so it probably powers the bots in it aswell, you dont put a battery in them on construction.

**Comment by ynot01** [comment]
> Seems weird that a bot would willingly turn itself off by moving to a powerless zone.

they dont have complex thought they just go to the plates under the floor

**Comment by Hopekz** [comment]
Also is there going to be any new behavior put in for beepsky now caring about a non engineer messing with APC's since it is now directly linked to it's ability to operate. Like it being attacked by someone

**Comment by jcatjmeow** [comment]
> ### Why is this good for the game?
> Bots will no longer glow or function when the area is unpowered

This isn't a "why" its just descriptive of the change.
> Better reflects the desolate feel when bravo 6 goes dark and everything electronic is unresponsive

This is an actual reason, however it does make floorbots, firebots, and to a lesser extent medbots significantly worse, since they are usually deployed in disaster areas to help clean up.

This also means that all the bots who route through maint are going to have a hard time.
Not sure if the gameplay consequences outweigh the atmosphere gained from this or not. 

> Beepsky can no longer space walk at you across 5 z-levels (unintended nerf but a welcome one)

Ok but, there are better ways to nerf beepsky if that's the concern. Maybe make it so that it doesn't function off z? That would make sense since the bot control stuff that are under the hallway floors aren't in space

**Comment by ynot01** [comment]
> This is an actual reason, however it does make floorbots, firebots, and to a lesser extent medbots significantly worse, since they are usually deployed in disaster areas to help clean up.

if you want to use wireless electronics in an area consider powering it with an APC

> This also means that all the bots who route through maint are going to have a hard time.

'bots who route through maint' are floorbots and mulebots, not really that huge a loss + maints are powered anyways

> Ok but, there are better ways to nerf beepsky if that's the concern

this was an unintended implication i realized after the fact of making this PR, i felt it was necessary to mention because beepsky is a hot topic sometimes, i welcome the nerf with open arms so im not going to do anything about it unless people make a fuss of it

**Comment by ynot01** [comment]
> Also is there going to be any new behavior put in for beepsky now caring about a non engineer messing with APC's since it is now directly linked to it's ability to operate. Like it being attacked by someone

no

**Comment by Hopekz** [comment]
> > Also is there going to be any new behavior put in for beepsky now caring about a non engineer messing with APC's since it is now directly linked to it's ability to operate. Like it being attacked by someone
> 
> no

Alright thanks for your honesty.
Imo this PR isn't a good implementation on what you're trying to accomplish but if you change anything I'll give it a second look

**Comment by neeshacark** [comment]
> > they use batteries
> 
> No, they don't

beepsky does. he runs on a potato

**Comment by neeshacark** [comment]
and i guess ill just say it. if bots can wirelessly be connected to apc power like this why would it just be the bots? why not have everything connected to the apc in this way, laser guns, disablers, stun batons, BORGS. why would not a single borg be connected to the power in this way and not just have a cell as a backup? whats the lore explanation for this? it makes zero sense in that regard.

**Comment by PrinceKirze** [comment]
> and i guess ill just say it. if bots can wirelessly be connected to apc power like this why would it just be the bots? why not have everything connected to the apc in this way, laser guns, disablers, stun batons, BORGS. why would not a single borg be connected to the power in this way and not just have a cell as a backup? whats the lore explanation for this? it makes zero sense in that regard.

all the things you described that require batteries can just be explained, lore-wise, as requiring too much power for the passive APC power supply to keep up, or they're so abundant (disablers, stun baton) that powering them as a collective is considered a strain and so it's more efficient to use rechargeable batteries (i think it's also mildly implied that stun batons use a metric fuckton of energy, at least with the semi-recent power changes they underwent).

**Comment by ynot01** [comment]
bots have no drainable power source and making them limited power would be a great hassle for roboticists to replace and recharge their cells that isn't worth their time

**Comment by maxion12345** [comment]
Jesus fuck why is this even needed
Beepsky already was tweaked so on detain it can't infinitely stun you, and the rest of the bots aren't even that powerful. Exceptions being in large numbers.

**Comment by alexkar598** [comment]
Are all your PRs i deds?

**Comment by BigBigga** [comment]
Hm. No.

**Comment by ynot01** [comment]
> Are all your PRs i deds?

just saw how bots were still out and about during a powersink so i made this because i think it would improve the game

**Comment by maxion12345** [comment]
new pr

pdas are now powered via apc

**Comment by Hopekz** [comment]
Congratulations, this PR now has enough dislikes to be randomly merged by Jamie

**Comment by Tipy1802** [comment]
> > they use batteries
> 
> No, they don't

Beepsky is powered by a potato battery. 
I really don't see any good coming out of this PR

**Comment by ynot01** [comment]
> Beepsky is powered by a potato battery.

you dont need any kind of battery to construct a securitron its just there for fluff

on the note of securitrons though i think i know how to get everyone off my dick with this i ded shit give me a bit

**Comment by ynot01** [comment]
sec mains appeased

**Comment by alexkar598** [comment]
Medibots are useful for emergencies such as blob where power isn't available. Theres really no reason for this and its just going to lead to station gets breifly depowered and all bots are offline and never turned back on because noone cares.

**Comment by ynot01** [comment]
> Medibots are useful for emergencies such as blob where power isn't available

bring them to a place where power is and then have the medibots heal them there

**Comment by Marmio64** [comment]
dont know how you'd do it, but maybe give bots a 30-60 second timer before they turn off incase they go to an area without power? Cause, it'd be pretty dumb to have arrivals APC go off and then any patrolling bot that goes over there just fucking dies instantly, at least they'd have a chance to get out after their patrol if there is a timer.

**Comment by ynot01** [comment]
> dont know how you'd do it, but maybe give bots a 30-60 second timer before they turn off incase they go to an area without power? Cause, it'd be pretty dumb to have arrivals APC go off and then any patrolling bot that goes over there just fucking dies instantly, at least they'd have a chance to get out after their patrol if there is a timer.

done, bots will now turn off after taking a certain amount of actions and steps while in no-power area

**Comment by Tipy1802** [comment]
Do they try to get out of/avoide unpowered areas?

**Comment by ynot01** [comment]
> Do they try to get out of/avoide unpowered areas?

no they arent smart they just go to the plates under the floor

**Pull request closed without merging**
