### PR TITLE
Lizards are now coldblooded + speed changes

### PR DESCRIPTION
**Pull request by Moltijoe**
Lizards are currently just humans 2
This gives them more of an identity based on the idea that they're lizards (good with heat, bad with cold)

# Wiki Documentation

Lizards have to be more careful with temperature regulation
Lizards slow down more when cold and speed up when warm

:cl:  
tweak: Lizards are now coldblooded
tweak: Lizards have a coldmod of 0.67 from 1.75 (they're cold far more)
tweak: Lizards have a heatmod of 0.67 from 0.75 (they're hot far more)
tweak: Lizards slow down more when cold and speed up when warm
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
I'm cool with this, I've always wanted lizards to feel more distinct. 

Other suggestions:
Nitrogen breathing
Metabolism that changes with temp
Heat bonus from eating

**Comment by Moltijoe** [comment]
> I'm cool with this, I've always wanted lizards to feel more distinct.
> 
> Other suggestions: Nitrogen breathing Metabolism that changes with temp Heat bonus from eating

i'll keep these in mind for the future, i think for now it should be fine

**Comment by neeshacark** [comment]
'lizards do tasks slightly slower'

lizbay fucking rip

**Review by ReddicusDragon — APPROVED** [review]

**Comment by Marmio64** [comment]
Why make them take less damage from cold? Shouldn't they just have no cold modifier?

**Comment by Marmio64** [comment]
> 'lizards do tasks slightly slower'
> 
> lizbay fucking rip

its only 5% slower so it practically doesn't exist

**Comment by Uristthedorf** [comment]
If a lizard gets heat adaption + fiery sweat do they become super fast with little downside?

**Comment by Moltijoe** [comment]
> If a lizard gets heat adaption + fiery sweat do they become super fast with little downside?

0.33 isn't super fast, but i suppose so, though i think that would burn all their clothes off, or at least risk burning other's clothes off

**Pull request merged**
