### PR TITLE
Water Vapour makes people wet

### PR DESCRIPTION
**Pull request by Moltijoe**
you can use it to put out fires now
also kill preterni

:cl:  
rscadd: Water Vapour makes people wet
/:cl:

### CODE REVIEW

**Comment by Majkl-J** [comment]
Coolio. I like more fetish content

**Comment by Mqiib** [comment]
Make it only do this below a certain temperature. Really high temperature steam shouldn't spontaneously condense on you

**Comment by MajManatee** [comment]
Last time i checked, hot steam is still wet. 
Ever been in a sauna?

**Comment by Moltijoe** [comment]
> Make it only do this below a certain temperature. Really high temperature steam shouldn't spontaneously condense on you

i already have it based on mols, if there's enough vapour in the air, it's gonna condense

**Comment by Marmio64** [comment]
Clown prank gone wrong (gone fatal on robot bozo)

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
