### PR TITLE
(port) catnip and catnip tea

### PR DESCRIPTION
**Pull request by boodaliboo**
original pr https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9109
more botany content i removed the erp shit from it and the probabilty to say nyaa on it im open to adding new things to the chem
mutate it off tea astra 
catnip tea is made from tea and catnip chemical mixed
grind catnip for catnip
#### Changelog

:cl:  
rscadd: Added catnip plant
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
What is catnip used for other than the tea? And what does the tea do? Is it any different from normal tea?

**Comment by boodaliboo** [comment]
> What is catnip used for other than the tea? And what does the tea do? Is it any different from normal tea?

catnip on citadel made you more aroused right now it does nothing i am open to suggestions though

**Comment by ghost** [comment]
make it have druggy effects on felinids, draw cats towards you and having a lot of it would cause bad effects for felinids.

**Comment by boodaliboo** [comment]
> make it have druggy effects on felinids, draw cats towards you and having a lot of it would cause bad effects for felinids.

im going to go towards having a druggy effect

**Comment by Putnam3145** [comment]
> i removed the erp shit 

so did I

**Comment by UselessTheremin** [comment]
nyaaaa~

**Review by Partheo — APPROVED** [review]

**Comment by Moggram** [comment]
I thought now maybe a good time to ask. Can you make it so the mix drink Catsip needs catnip and sugar instead of Corn Syrup?
Sorry if this makes more work for you but, it will add more of a use for catnip.

If not, can you fix Corn Syrup? The recipe wants just /datum/reagent/toxin/acid. (I have tried Sulphuric Acid and Fluorosulfuric Acid, but can't get it to work.)

Thank you for you time.

**Comment by Reed0506** [comment]
make it so it gives felinids seizures if they OD or something

**Comment by boodaliboo** [comment]
> I thought now maybe a good time to ask. Can you make it so the mix drink Catsip needs catnip and sugar instead of Corn Syrup?
> Sorry if this makes more work for you but, it will add more of a use for catnip.
> 
> If not, can you fix Corn Syrup? The recipe wants just /datum/reagent/toxin/acid. (I have tried Sulphuric Acid and Fluorosulfuric Acid, but can't get it to work.)
> 
> Thank you for you time.

yes

**Pull request closed without merging**
