### PR TITLE
Adds Treasures within the abomination to lobby music

### PR DESCRIPTION
**Pull request by Moltijoe**
https://www.youtube.com/watch?v=e3t_dbLaw-M	// DM Dokuro - Treasures Within The Abomination

also fixes some comment indenting

:cl:  
soundadd: adds Treasures within the abomination to lobby music
/:cl:

### CODE REVIEW

**Review by ReddicusDragon — APPROVED** [review]
Halo 3 theme may get us sued, but I like it so fuck it

**Comment by Moltijoe** [comment]
> Halo 3 theme may get us sued, but I like it so fuck it

if it might, then it probably shouldn't be added
i'll wait for one of the maintainers or other staff to confirm or deny that

**Comment by ReddicusDragon** [comment]
> > Halo 3 theme may get us sued, but I like it so fuck it
> 
> if it might, then it probably shouldn't be added i'll wait for one of the maintainers or other staff to confirm or deny that

to be fair there's a few that probably would open us up to getting us sued, I don't think it's necessarily a big deal, but it IS microsoft, so you never know

**Comment by Moltijoe** [comment]
> to be fair there's a few that probably would open us up to getting us sued, I don't think it's necessarily a big deal, but it IS microsoft, so you never know

i like to think this is one of those situations where they COULD sue us, but wouldn't because that's just bad press.
If it were nintendo however, they'd sue us in a heartbeat

**Comment by ReddicusDragon** [comment]
> > to be fair there's a few that probably would open us up to getting us sued, I don't think it's necessarily a big deal, but it IS microsoft, so you never know
> 
> i like to think this is one of those situations where they COULD sue us, but wouldn't because that's just bad press. If it were nintendo however, they'd sue us in a heartbeat

Probably. Besides, we're just an obscure game

**Comment by Moltijoe** [comment]
> Probably. Besides, we're just an obscure game

an obscure server of an obscure game

**Comment by JamieD1** [comment]
Pictionary is unfortunately too short, also atomize in future.

**Comment by Moltijoe** [comment]
> Pictionary is unfortunately too short, also atomize in future.

aight, i'll remove pictionary and halo

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
