### PR TITLE
fix air

### PR DESCRIPTION
**Pull request by Amelia0010**
Made in webmin©️ untested™️

### CODE REVIEW

**Comment by Bawhoppen** [comment]
I would recommend actually doing this upstream instead. I think it would be appreciated as a feature there. (Do it fast though, feature freeze is in 2 days)

**Comment by Bawhoppen** [comment]
Why the confused reaction? I just think that it'd be fine to port it upstream if you wanted, so you don't have to potentially deal with maintaining it downstream.

**Comment by ThatLing** [comment]
woops

**Comment by Amelia0010** [comment]
not like this'll need any maintaining anyways

**Pull request merged**
