### PR TITLE
Transfer votes

### PR DESCRIPTION
**Pull request by Oblisk234**
# Document the changes in your pull request

Adds transfer votes, which will trigger at 2 hours and 2 hours 30 respectively, polling all players on whether to call the emergency shuttle. Moved shuttle autocall to 3 hours.

At 2 hours, percentage required to stay is 60%
At 2 hours 30 mins, percentage required to stay is 80%

# Why is this good for the game?
At the moment, autocall prevents anyone from doing anything past 2 hours, which in my opinion is restrictive if you want to do something past that, or figured out something that you want to do around 1 hour 30 mins, but because it takes an hour to do, you'd have to wait for the next round to do it.

Transfer votes allows all players on the server (including ghosts and dead players) to decide whether to choose whether they want to continue the round or start a new one.

# Testing
<details>
<summary>Shuttle calling after transfer vote</summary>

</details>
<details>
<summary>Shuttle not calling after transfer vote</summary>

</details>
<details>
<summary>If no one votes, calls shuttle anyway</summary>

</details>
<details>
<summary>Vote menu (accessible to ghosts)</summary>

</details>
<details>
<summary>Transfer vote in create vote menu (non-admins can't make one)</summary>

</details>

# Changelog

:cl:
rscadd: Added crew transfer votes.
tweak: Shuttle autocall will now trigger at 3 hours.
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
Can you attempt to make the shuttle gets autocalled immediately once crew pops drop to 0? Assuming the station had crew members alive for a period

**Comment by Oblisk234** [comment]
> Can you attempt to make the shuttle gets autocalled immediately once crew pops drop to 0?

No, because it will cause the following:
- Only crew member cryo's.
- Shuttle is called
- Round ends
- Round starts
- Shuttle is called due to no crew.
- Round ends
- Repeat

**Comment by ShoziOffical** [comment]
> > Can you attempt to make the shuttle gets autocalled immediately once crew pops drop to 0?
> 
> No, because it will cause the following:
> 
> * Only crew member cryo's.
> * Shuttle is called
> * Round ends
> * Round starts
> * Shuttle is called due to no crew.
> * Round ends
> * Repeat

You can make a check for empty station shift start, once a crew arrived it will start the shuttle autocall code to check whether the last crew alive or not to call shuttle, and a cryopod check aswell to prevent the code mistakenly assume the last crew died

**Comment by Oblisk234** [comment]
> > > Can you attempt to make the shuttle gets autocalled immediately once crew pops drop to 0?
> > 
> > 
> > No, because it will cause the following:
> > 
> > * Only crew member cryo's.
> > * Shuttle is called
> > * Round ends
> > * Round starts
> > * Shuttle is called due to no crew.
> > * Round ends
> > * Repeat
> 
> You can make a check for empty station shift start, once a crew arrived it will start the shuttle autocall code to check whether the last crew alive or not to call shuttle, and a cryopod check aswell

There is already code to check whether crew is dead and I am not fixing it in this PR.

**Comment by ShoziOffical** [comment]
> > > > Can you attempt to make the shuttle gets autocalled immediately once crew pops drop to 0?
> > > 
> > > 
> > > No, because it will cause the following:
> > > 
> > > * Only crew member cryo's.
> > > * Shuttle is called
> > > * Round ends
> > > * Round starts
> > > * Shuttle is called due to no crew.
> > > * Round ends
> > > * Repeat
> > 
> > 
> > You can make a check for empty station shift start, once a crew arrived it will start the shuttle autocall code to check whether the last crew alive or not to call shuttle, and a cryopod check aswell
> 
> There is already code to check whether crew is dead and I am not fixing it in this PR.

Ok ill prob attempt to fix it after this pr gets merged then

**Comment by iamthesilly** [comment]
> No, because it will cause the following:
> 
>     * Only crew member cryo's.
> 
>     * Shuttle is called
> 
>     * Round ends
> 
>     * Round starts
> 
>     * Shuttle is called due to no crew.
> 
>     * Round ends
> 
>     * Repeat

This wouldn't actually happen because the round doesn't start without any players online.

**Comment by ShoziOffical** [comment]
> > No, because it will cause the following:
> > ```
> > * Only crew member cryo's.
> > 
> > * Shuttle is called
> > 
> > * Round ends
> > 
> > * Round starts
> > 
> > * Shuttle is called due to no crew.
> > 
> > * Round ends
> > 
> > * Repeat
> > ```
> 
> This wouldn't actually happen because the round doesn't start without any players online.

people can play as ghosts but whatever

**Pull request merged**
