### PR TITLE
Replaces Officer Kreb with Sergeant Areneus on Yogbox.

### PR DESCRIPTION
**Pull request by nesisknesis**
a pet spider is superior to a kreb. it's also funnier to see a hos be robusted for clicking his pet with harm intent.

areneus can also survive an entire battery of an egun so watch out for that

#### Changelog

:cl:  Identification
tweak: Cooks Officer Kreb and imports SGT. Areneus from the space nest.
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
But Officer Kreb best kreb

**Comment by boodaliboo** [comment]
dont merge i like crab

**Comment by HomocidlePancakes** [comment]
Kreb is better and he deserves a hat

**Comment by HomocidlePancakes** [comment]
Don’t try to bargain with us. Kreb deserves to be an HoS’ office

**Comment by nesisknesis** [comment]
I don't negotiate with terrorists.

**Comment by HomocidlePancakes** [comment]
Then you submit yourself to being shot

**Pull request merged**
