### PR TITLE
Trades Traitor AI (All) for Malfunctioning AI (Dynamic)

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Ports https://github.com/tgstation/tgstation/pull/59064:
Malfunctioning AI is now separate from Traitor AI.
AIs can no longer become Traitor AI (because Traitor AI no longer exists).
AIs can now become Malfunctioning AI (dynamic roundstart only).
`exclusive_roles` can be used for dynamic roundstart rulesets.

Ports https://github.com/tgstation/tgstation/pull/62774:
Malfunctioning AI now uses different flavor (as opposed to traitor's backstory flavor).
Malfunctioning AI's "View Antag Information" menu now doubles as flavor (Information) and as a second place to buy abilities (Malfunction Modules).
image

Other Changes:
Doomsday Device is no longer purchasable as a malfunction module.
Malfunctioning AI gets the same objectives that they would get if they were a traitor AI.
Removing Malfunctioning AI status properly removes actions/abilities gained from malfunction modules.

# Why is this good for the game?
Traitor AI has been working out okay so far. So, if Malfunctioning AI was made more like Traitor AI, then it should be okay. This PR more or less tries to address the concerns in [#17937] (which gave reasons why Malfunctioning AI was disabled).

# Testing
Rolling for Malfunctioning AI on Dynamic works.
- Game Panel --> Dynamic --> Force Roundstart Ruleset: Malfunctioning AI
- Client Preferences: Captain (High), Research Director (Medium), AI (Low)
- Malfunctioning AI Antag Enabled --> Got Malfunctioning AI
- Malfunctioning AI Antag Disabled --> Did not get Malfunctioning AI
- Client Preferences: Captain (High), Research Director (Medium)
- Malfunctioning AI Antag Enabled --> Did not get Malfunctioning AI

Doomsday Device does not appear in Malfunctioning Modules.
Objectives are not malf-like and more traitor-like (as image shown above).

# Wiki Documentation
Doomsday Device is no longer purchasable.

# Changelog
:cl:  
rscadd: Malfunctioning AI can be rolled as a dynamic roundstart ruleset. 
rscadd: Malfunctioning AIs get unique flavor (as opposed to traitor's backstory).
rscdel: Malfunctioning AIs can no longer buy Doomsday Device.
rscdel: Traitor AI no longer exists.
bugfix: Malfunctioning AIs properly lose their malf buttons if they lose their antag status.
tweak: Malfunctioning AI gets the same exact objectives as they would have if they were Traitor AI. 
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
there should be an admin button that provides doomsday device as an option for the AI just for Funny

**Comment by PibeCantina** [comment]
I'm all in if it means malf will finally get polished and made into another thing that isnt a plasmaflood machine

**Comment by ynot01** [comment]
Dynamic was disabled

**Comment by ToasterBiome** [comment]
Dynamic was disable and probably not coming back

**Pull request closed without merging**
