### PR TITLE
Adds Leg implants

### PR DESCRIPTION
**Pull request by Moltijoe**
Remakes #15864 but better

The effect only triggers once there is an identical implant in both legs

- [x] noslipwater (illegal research)
- [x] noslipall (traitor)
- [x] Clown shoes implant (clown research)
- [x] Jump boots implant (mining vendor or research)
- [x] Wheelies implant (research)
- [x] Airshoes implant (traitor)
- [x] Magboot implant (research)
- [x] properly convey that it requires two identical implants for them to work
- [x] let autosurgeons properly implant multiple implants at once (sorta done)
- [x] Implement them
- [x] give leg implants a sprite to differentiate them from arms

by popular demand, i have brought back the shitty terrible 90 degree rotated arm implant sprite
image

:cl:  
rscadd: Adds various leg implants
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
pretty strong for civilian stuff

**Comment by Moltijoe** [comment]
> pretty strong for civilian stuff

Notice the checkmark that say "implement them", they arent anything stuff yet

**Comment by MajManatee** [comment]
Finally, Magnetic lizard legs.
No more powerful than Thermal Eyes or Rebooter, which eveyrone can get.

**Comment by Moltijoe** [comment]
> Finally, Magnetic lizard legs. No more powerful than Thermal Eyes or Rebooter, which eveyrone can get.

Yeah, its mainly for those that want the effects of some fancy shoes, but either cant wear shoes, or require a different shoe most of the time

**Comment by Burger1998** [comment]
> pretty strong for civilian stuff

i feel alot of them are going to be locked away i think it will be something along the lines of
Normal research: magboots, wheelies and jump boots
Bananium: clown shoes
Illegal implants: noslipwater
Traitor?: Airshoes, noslipall(originally was going to think noslipall for nukies but you would have to be very special to lose your shoes as a nukeop)

**Comment by Moltijoe** [comment]
> i feel alot of them are going to be locked away i think it will be something along the lines of Normal research: magboots, wheelies and jump boots Bananium: clown shoes Illegal implants: noslipwater Traitor?: Airshoes, noslipall(originally was going to think noslipall for nukies but you would have to be very special to lose your shoes as a nukeop)

Sorta my plans

**Comment by ReddicusDragon** [comment]
please inform me when this is ready so I may review it

**Comment by Moltijoe** [comment]
> please inform me when this is ready so I may review it

inform

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
