### PR TITLE
AI VOX can now sing daisy bell

### PR DESCRIPTION
**Pull request by AlvCyktor**
male and female AI vox can now sing daisy bell. This is in reference to the IBM 704, which sung this song back in 1961.

:cl:  
rscadd: daisy daisy give me your answer do...
/:cl:

### CODE REVIEW

**Review by adamsong — DISMISSED** [review]
Remove the changes to drinks.dmi

**Comment by adamsong** [comment]
A 34 second audio clip seems a bit long

**Comment by Hopekz** [comment]
**Lazy PR:**
This isn't even in the vox voice of the voices you are trying to add this to. The female VOX has a male voice.

**Doesn't fit:**
This doesn't fit in the game because we don't play full songs with actual instruments over VOX

**Comment by AlvCyktor** [comment]
Im going to close this PR until I can find a way to make it sound like the actual AI voxes as I agree with the comments above

**Pull request closed without merging**
