### PR TITLE
[Admin] Makes the supply pod launcher locked behind +FUN

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
The supply launcher verb is now locked behind +FUN

#### Changelog

:cl:  
tweak: Admin supply pods are now locked behind +FUN
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
sure

**Review by monster860 — CHANGES_REQUESTED** [review]
you need to change the perms check in the verb itself

**Review by alexkar598 — CHANGES_REQUESTED** [review]
The right check needs to go before the datum is created

**Comment by boodaliboo** [comment]
so mods cant do gondola pods anymore?

**Comment by Hopekz** [comment]
> so mods cant do gondola pods anymore?

Yeah.
They're basically trying to take away the "fun" of being a mod.

Hopefully this doesn't discourage future mods from staying I know if I didn't have access to pods during my mod times it would be a coin toss on whether or not I'd be an admin today.

**Comment by Moja10** [comment]
I think mods should have pods because 1. it's a retard filter 2. They can't spawn things so there's a limited number of things they can pod to the station 3. It gives me reason to show on their apps all they care about is POOOODDDING

**Comment by Bibby0110** [comment]
> I think mods should have pods because 1. it's a retard filter 2. They can't spawn things so there's a limited number of things they can pod to the station 3. It gives me reason to show on their apps all they care about is POOOODDDING
1. Fair
2. Yeah, only all the things on the map, which contains the test chamber on CC, that has *all the items*

3. Fair :3

**Comment by Hopekz** [comment]
> 1. Fair
> 2. [No fair]
> 3. Fair :3

Okay so are you closing this PR?
You seem to agree more against this change then actually support it.
Not sure if "fair" means "I agree" or "I'm blowing you off with a filler answer"

**Comment by Bibby0110** [comment]
> > 1. Fair
> > 2. [No fair]
> > 3. Fair :3
> 
> Okay so are you closing this PR?
> You seem to agree more against this change then actually support it.
> Not sure if "fair" means "I agree" or "I'm blowing you off with a filler answer"
No
Fair means I understand what he means, and why he's saying it.

Doesn't mean I have to change my opinion

**Comment by JamieD1** [comment]
Surely the problem should be with the mods using the pods then the pods themselves. If they are being abused clearly they do not have what it takes to have control. No?

**Review by alexkar598 — APPROVED** [review]

**Comment by MegaEmpirical** [comment]
I'm not convinced this passed the council vote.

**Comment by Hopekz** [comment]
DNV
DNV
*seat empty
DNV
"sure lol"

**Pull request merged**
