### PR TITLE
Fixes alt click turf interaction menu malfunctioning 50% of the time

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

This fixes the error where approximately 50% of the time the alt click turf interaction menu doesn't function correctly.

# Changelog

:cl:  
bugfix: Fixes alt click turf interaction menu malfunctioning 50% of the time
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I don't think they read the files changed
image

**Comment by Notamaniac** [comment]
image

**Comment by Xoxeyos** [comment]
Thanks for the laugh, you might want to increase is so the margin for error is much lesser.

**Comment by neeshacark** [comment]
i think there is a joke here

im too smoothbrained to see it since i cant understand code

**Review by MajManatee — COMMENTED** [review]
I like to gamble :)

**Comment by ToasterBiome** [comment]
Looking at alternate options

**Pull request closed without merging**
