### PR TITLE
Buffs Antenna Mutation

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Antenna now just functions like a radio with cap level channels

And is now 15 instability

#### Changelog

:cl:   
tweak: Antenna Mutation now can listen to all channels
tweak: Antenna Mutation now cost 15 stability up from 5
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
While it does make it useful I don't think non sec and non command people should have access to the security and command channel

**Comment by redmoogle** [comment]
> 
> 
> While it does make it useful I don't think non sec and non command people should have access to the security and command channel

Out of most mutations, this one is pretty mundane, as oh wow you can snoop in on the cap ig, or see that sec is on your tail.

**Comment by TheLinuxOS** [comment]
Makes a mutation that is the equivalent of a 2 TC item, and seeing as we still have the thermal vision mutation which is also equivalent to a traitor item I personally see no problem with it.

**Comment by MegaEmpirical** [comment]
I wouldn't fight this if we had the old encryption system for tcomms that would disable those channels when they're encrypted.

**Comment by Ratvar** [comment]
TheLinusOX, see no reason why existing mutations would be a reason to add new ones without explaining why current mutations are good, or how they are related in utility instead of cost: thermal is a validhunting tool or very rarely an overpowered antagging tool, bringing almost nothing good to the round. 
It is rather hard to use sec or cap radio to validhunt, thought, so this seems to be a good thing.

**Review by JamieD1 — APPROVED** [review]
Why not, lets see how it works out

**Pull request merged**
