### PR TITLE
Detective office gets a photocopier

### PR DESCRIPTION
**Pull request by Hopekz**
Created per:
https://forums.yogstation.net/index.php?threads/add-a-photocopier-to-the-detectives-office.21390/

image

#### Changelog

:cl:  Hopek
tweak: Sacrificed the detective's plant to bring a photocopier into existence
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
rip plant... you'll be missed...

**Comment by Hopekz** [comment]
> rip plant... you'll be missed...

why are we still here? Just to suffer? Every night, I can feel my soil and my stem... even my leaves... the plant I've lost... the plant pots I've lost... won't stop hurting. It's like they're all still there. You feel it too, don't you?

**Comment by athena413** [comment]
i know the exact round that caused this pr to be made lmao

**Review by Ktlwjec1 — APPROVED** [review]
stupid approval review is required rn

**Comment by MegaEmpirical** [comment]
Maybe we can get the damn supplies I requested now.

**Pull request merged**
