### PR TITLE
NEW OBJECTIVE: Targetted organ harvesting

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

New assassinate-adjacent objective: Steal organ

You are tasked with stealing a random organ from a specific person. It has to be the original organ that they start with, not a replacement. This means that you can steal someone's lungs and then have them replaced so that they aren't round removed.

If this organ is not their brain, then you have a 50% chance of also getting a protect objective on this person, which means you can't just esword open their stomach/head contents for an easy greentext, you will have to employ "surgical" precision.

# Why is this good for the game?

Ghetto surgery, syndicate surgery kit, not necessarily lethal interactions, especially with the protect objective tacked on

# Testing
image

# Wiki Documentation
See above for exact text

# Changelog

:cl:  
rscadd: Added a new "steal organ" objective which tasks you with stealing an internal organ from someone specific. Be careful though, as you may have to replace it to keep them alive!
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
Just decap then give the head to medbay if you have a protect objective

**Comment by ynot01** [comment]
> Just decap then give the head to medbay if you have a protect objective

You certainly can, but I wouldn't consider killing someone that you want to stay alive to be too wise

**Comment by wonderinghost** [comment]
what if they got a organ replaced before you could get to them

**Comment by ynot01** [comment]
> what if they got a organ replaced before you could get to them

sucks

**Comment by Maia-J** [comment]
> what if they got a organ replaced before you could get to them

Find it thrown out somewhere and hope a lizard didn't eat it

**Comment by LassiH** [comment]
ah yes  traitors the enemies of nanotrasen protecting nanotrasen employees also  how will you get the original organ of a person who has used a mutation toxin to chance races

**Comment by ShoziOffical** [comment]
> ah yes traitors the enemies of nanotrasen protecting nanotrasen employees also how will you get the original organ of a person who has used a mutation toxin to chance races

sucks

**Pull request closed without merging**
