### PR TITLE
Makes the dead space figure's visor on the title screen green.

### PR DESCRIPTION
**Pull request by nesisknesis**
You're lying if you haven't thought that this should have been green.

Before:

image

After:

image

#### Changelog

:cl:  Identification
imageadd: Makes the dead space figure's visor on the title screen green. 
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
image

**Comment by Marmio64** [comment]
at least change the back 'health gauge' color to green too, otherwise this looks bad

**Comment by nesisknesis** [comment]
image

**Comment by nesisknesis** [comment]
tbh i still like the blue health bar

**Comment by deathslayer2481** [comment]
Why not purple at this rate

**Pull request merged**
