### PR TITLE
Toilet bong

### PR DESCRIPTION
**Pull request by Absolucy**
:cl: Lucy
rscadd: Added a toilet bong. It can be created by using a flamethrower on a toilet, while holding a crowbar in the other hand! It can be filled with tons of weed or tobacco.
/:cl:

sprite/idea by [/u/LordVollkorn](https://old.reddit.com/r/SS13/comments/qm3bjr/botanist_ok_hear_me_out_on_this_one/)

## Creating a toilet bong
9f5pWaTM86

## Smoking a toilet bong
mFjHxpUqGP

## Smoking a toilet bong (and messing up, 15% chance)
agssaULVXx

### CODE REVIEW

**Comment by Reed0506** [comment]
does it pump the contents of the flamethrower's tank into the atmosphere?

**Comment by Absolucy** [comment]
no

**Comment by Moggram** [comment]
I miss read the RP name and thought it said toilet borg. I am even more let down by this...

**Comment by Cartlord** [comment]
what purpose does this serve
anyone with the power to get cannabis and a flamethrower has the power to get a rollie

**Comment by Absolucy** [comment]
@Cartlord it's funny

also it makes a big-ass cloud so you get to smoke with your buddies

**Comment by boodaliboo** [comment]
> what purpose does this serve anyone with the power to get cannabis and a flamethrower has the power to get a rollie

why does everything need a express purpose why isnt fun a good enough reason

**Review by nesisknesis — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Comment by AtlasRules** [comment]
good PR 

BUT does it make the customgrow420 lung buster moan? https://youtu.be/GvuaQzhS5Fo

**Pull request merged**
