### PR TITLE
Removes Drone Shell Dispenser Machine

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Removes Drone Shell Dispensers from the files, both the code and sprite which was its own file. Alters the .DME file to reflect this.

Drone dispensers are antique relics of old TG code, having not been touched in 6-7 years, and causing so many admin issues on TG that they made drones nearly unplayable to compensate. Additionally you can make drones by hand, and as these machines are completely unused, there's little reason to have them around, aside from admin spawning for personal fun.

I know the mantra is "improve not remove" but in this case the improvement already exists in hand-crafting the drone shells, and as these are, again, completely unused, existing in no single map file in this code base, I don't see much reason to bother improving them. Even admin-spawning them for some event would be painful since they take a solid three minutes to cool down between shells printed, which is ample time for an admin to simply spawn a mountain of drone shells by hand.

Removal tested, compiles, and runs fine.

# Wiki Documentation

The wiki contains no mention of the drone dispenser at all, that I could find.

# Changelog

:cl:  
rscdel: Removes unused Drone Shell Dispenser machines
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
Totally open to reasons to keep them, just personally can't see any myself*

**Comment by TheRyeGuyWhoWillNowDie** [comment]
aw, no more admin fuckery with syndrone spawners

**Comment by VaelophisNyx** [comment]
I mean....does it even happen frequently enough to warrant it?

**Comment by ToasterBiome** [comment]
@KillerOrcaCora @cuackles

**Comment by KillerOrcaCora** [comment]
Eh, keeping it.

**Pull request closed without merging**
