### PR TITLE
Ports paradises door buttons

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Ports paradises door buttons from this PR https://github.com/ParadiseSS13/Paradise/pull/21304

# Spriting
Old
image

New
image

# Changelog
:cl:  
imageadd: Added new door buttons from paradise
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
feels less visually clear

**Comment by azzzertyy** [comment]
> feels less visually clear

theyre animated numbnuts

**Comment by Maia-J** [comment]
> feels less visually clear

https://github.com/yogstation13/Yogstation/pull/19725/checks?check_run_id=15130103577

**Comment by azzzertyy** [comment]
why does yogstation.dme keep moving ambience

**Comment by solwashere** [comment]
I like these as they blend in less on walls and feel more visually clear

**Comment by azzzertyy** [comment]
"less visually clear"
image
image

>we want better sprites

"ok heres some better sprites"

>NOO WE WANT OLD SPRITES

they look better in every way and yallre just muh soul if you disagree

**Comment by Marmio64** [comment]
They visually look better but also kind of seem like they're supposed to be on a different perspective wall? As if the buttons are angled down slightly while our walls are completely flat 2d. Are Para's walls a different perspective?

**Comment by azzzertyy** [comment]
> They visually look better but also kind of seem like they're supposed to be on a different perspective wall? As if the buttons are angled down slightly while our walls are completely flat 2d. Are Para's walls a different perspective?

Slightly, but not 3/4ths
image

**Review by ynot01 — APPROVED** [review]

**Comment by cuackles** [comment]
currently thinking this over, its a better sprite, its more clear but it doesnt seems to be liked, i want to see if there is another option for buttons thats more widely accepted, if no other superior sprite appears then it will merged, also conflict currently in code, also there might be some testmerge to see if more exposition turns it more liked

**Comment by Hislyna** [comment]
After looking from the testmerge, they look soooooo ugly compared to the rest. Maybe it they fit better, but damn they uggo in contrast

**Review by cuackles — CHANGES_REQUESTED** [review]
i will be making a diferent sprite so im adding this change request so no one accidently merge it and stuff

**Pull request closed without merging**
