### PR TITLE
Station trait that randomises appearances and names

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Anti metafriend PR. Also introduces some variety so people can't soft-meta focus targets that are "known" to be robust or etc. Plus, more station traits are always good.

# Spriting

# Wiki Documentation

Add station trait that randomises appearances and names (is this even a wiki thing?)
# Changelog

:cl:  
rscadd: New station trait that randomises appearances and names
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
holy shit this is the worst pr i have ever seen, you set new records every day

**Comment by Simplehorror** [comment]
> holy shit this is the worst pr i have ever seen, you set new records every day

metafriend tears

**Comment by N3D6** [comment]
> > holy shit this is the worst pr i have ever seen, you set new records every day
> 
> metafriend tears

strawman argument

**Comment by Simplehorror** [comment]
this PR literally changes nothing for you if you're not a metafriender

**Comment by N3D6** [comment]
> this PR literally changes nothing for you if you're not a metafriender

There is no kinder way for me to say this. You are retarded

**Comment by Simplehorror** [comment]
metafriend tears

**Comment by Moltijoe** [comment]
> metafriend tears

there's reasons to want to play your own character aside from metafriending. This game is a roleplaying game to some extent still. I wouldn't be surprised if people cryopod instantly if this trait ever rolls.

**Comment by Mqiib** [comment]
I have a character. I like to play this character. They have a backstory and a personality. This helps me get into the rp aspect of the game.
This pr effectively removes my character randomly. This is not something I want. If I wanted to play a random character I would, but I want to play the character I like.
In conclusion, this pr is bad.

**Comment by Simplehorror** [comment]
> I have a character. I like to play this character. They have a backstory and a personality. This helps me get into the rp aspect of the game. This pr effectively removes my character randomly. This is not something I want. If I wanted to play a random character I would, but I want to play the character I like. In conclusion, this pr is bad.

would you like me to remove dying too? shit happens

**Comment by N3D6** [comment]
> metafriend tears

Average coder moment "You don't like my pr so I am going to just lie"

**Comment by Simplehorror** [comment]
> > metafriend tears
> 
> there's reasons to want to play your own character aside from metafriending. This game is a roleplaying game to some extent still. I wouldn't be surprised if people cryopod instantly if this trait ever rolls.

"i can't metafriend so i must cryo"

**Comment by N3D6** [comment]
> > > metafriend tears
> > 
> > 
> > there's reasons to want to play your own character aside from metafriending. This game is a roleplaying game to some extent still. I wouldn't be surprised if people cryopod instantly if this trait ever rolls.
> 
> "i can't metafriend so i must cryo"

What is your ckey?

**Comment by Simplehorror** [comment]
> > metafriend tears
> 
> Average coder moment "You don't like my pr so I am going to just lie"

there's only one reason to dislike my PR and that's because you're a metafriender

**Comment by N3D6** [comment]
> > > metafriend tears
> > 
> > 
> > Average coder moment "You don't like my pr so I am going to just lie"
> 
> there's only one reason to dislike my PR and that's because you're a metafriender

What is your ckey? Who are you?

**Comment by Simplehorror** [comment]
> > > > metafriend tears
> > > 
> > > 
> > > Average coder moment "You don't like my pr so I am going to just lie"
> > 
> > 
> > there's only one reason to dislike my PR and that's because you're a metafriender
> 
> What is your ckey? Who are you?

i don't staticname so you wouldn't know me, staticnaming easiest way to get soft metagrudged

**Comment by N3D6** [comment]
> > > > > metafriend tears
> > > > 
> > > > 
> > > > Average coder moment "You don't like my pr so I am going to just lie"
> > > 
> > > 
> > > there's only one reason to dislike my PR and that's because you're a metafriender
> > 
> > 
> > What is your ckey? Who are you?
> 
> i don't staticname so you wouldn't know me, staticnaming easiest way to get soft metagrudged

What is your ingame ckey? I feel like you're either an alt making troll prs or someone who is banned

**Comment by Simplehorror** [comment]
> > > > > > metafriend tears
> > > > > 
> > > > > 
> > > > > Average coder moment "You don't like my pr so I am going to just lie"
> > > > 
> > > > 
> > > > there's only one reason to dislike my PR and that's because you're a metafriender
> > > 
> > > 
> > > What is your ckey? Who are you?
> > 
> > 
> > i don't staticname so you wouldn't know me, staticnaming easiest way to get soft metagrudged
> 
> What is your ingame ckey? I feel like you're either an alt making troll prs or someone who is banned

What does this have to do with the PR? Please keep all comments on-topic.

**Comment by N3D6** [comment]
> What does this have to do with the PR? Please keep all comments on-topic.

Just curious, because I need to see if you actually play the game so I can see how out of touch you really are

**Comment by 00ze-cyclone** [comment]
> > > > > > > metafriend tears
> > > > > > 
> > > > > > 
> > > > > > Average coder moment "You don't like my pr so I am going to just lie"
> > > > > 
> > > > > 
> > > > > there's only one reason to dislike my PR and that's because you're a metafriender
> > > > 
> > > > 
> > > > What is your ckey? Who are you?
> > > 
> > > 
> > > i don't staticname so you wouldn't know me, staticnaming easiest way to get soft metagrudged
> > 
> > 
> > What is your ingame ckey? I feel like you're either an alt making troll prs or someone who is banned
> 
> What does this have to do with the PR? Please keep all comments on-topic.

You say people are metafriender but they have to stay on topic.
WIth each PR you become even more of an hypocritical asshole

**Comment by Simplehorror** [comment]
> > What does this have to do with the PR? Please keep all comments on-topic.
> 
> Just curious, because I need to see if you actually play the game so I can see how out of touch you really are

my ckey is N3D6

**Comment by Simplehorror** [comment]
> > What does this have to do with the PR? Please keep all comments on-topic.
> 
> Just curious, because I need to see if you actually play the game so I can see how out of touch you really are

this is unrelated to this PR, take this discussion to Discord

**Comment by N3D6** [comment]
This PR just shows you don't actually play here, because there is no way someone can be this out of touch with the players and can actually think this is a good idea.

I honestly think you are ban evading or are making troll prs

**Comment by Bibby0110** [comment]
LOL

**Comment by Simplehorror** [comment]
> This PR just shows you don't actually play here, because there is no way someone can be this out of touch with the players and can actually think this is a good idea.
> 
> I honestly think you are ban evading or are making troll prs

it's a station trait, it's not every round, quit crying

**Comment by N3D6** [comment]
God bless Bibby

**Comment by N3D6** [comment]
> > This PR just shows you don't actually play here, because there is no way someone can be this out of touch with the players and can actually think this is a good idea.
> > I honestly think you are ban evading or are making troll prs
> 
> it's a station trait, it's not every round, quit crying

L + Closed pull request

**Comment by Simplehorror** [comment]
N3D6 (as Jim LaWena) — Today at 1:17 PM
@bibble 25 dollars cashapp if you close this horseshit

enjoy the money bibble

**Comment by N3D6** [comment]
Bibby has been paid

**Pull request closed without merging**
