### PR TITLE
Increases lesser form's chemical cost from 5 to 30 and DNA cost from 1 to 3

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

Why buy biodegrade when momke mode does everything it does but has more utility
closes #13804
closes #13878

# Wiki Documentation

lesser form dna cost 3 from 1 and chemical cost 30 from 5

# Changelog

:cl:  
tweak: Increases lesser form's chemical cost from 5 to 30 and DNA cost from 1 to 3
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
No please

**Comment by ghost** [comment]
Allow then to use armblade while in monkey mode

**Comment by Simplehorror** [comment]
> Allow then to use armblade while in monkey mode

why

**Comment by ghost** [comment]
> > Allow then to use armblade while in monkey mode
> 
> why

Because now they become shit. I used the monkey form only for venting and sabotaging while using an armblade. I don't give a fuck that it has a anti-cuff function, and i need it ONLY for venting, so making me to be forced to by an anti-cuff function that i would not use for 2 DNA is making my strat pretty fucked up. Perhaps making armblade work while in lesser form can neuter throwing 2 DNA points into trash.

**Comment by ghost** [comment]
Or as an alternative lesser form can be replaced by a passive ability to ventcrawl while naked

**Comment by Simplehorror** [comment]
> > > Allow then to use armblade while in monkey mode
> > 
> > 
> > why
> 
> Because now they become shit. I used the monkey form only for venting and sabotaging while using an armblade. I don't give a fuck that it has a anti-cuff function, and i need it ONLY for venting, so making me to be forced to by an anti-cuff function that i would not use for 2 DNA is making my strat pretty fucked up. Perhaps making armblade work while in lesser form can neuter throwing 2 DNA points into trash.

vent crawling is worth 3 dna, just find a different strategy. nobody guarantees your strategy will work forever

**Comment by ghost** [comment]
> vent crawling is worth 3 dna, just find a different strategy. nobody guarantees your strategy will work forever

Actually i pay normally 7 DNA for ventcrawling:
Lesser form - self explanatory 
Armblade - ventcrawling is usless if you dont have it
Fleshmend - you die in vents without it
X-Ray vision - useless, but you cant see from vents without it

Now i will pay 9 DNA for ventcrawling. Very unfun.

**Review by JamieD1 — APPROVED** [review]

**Comment by ghost** [comment]
R.I.P. lesser form

**Pull request merged**
