### PR TITLE
Readds Onule's titanium sprites

### LINKED ISSUE #9193: Shuttle door sprite broken
image

### PR DESCRIPTION
**Pull request by Partheo**
I know you all hated them, but it's time for Yogs to put on its big boy pants and swallow. If you want visual improvement over time, this is how it happens.

Brings back these:
https://github.com/yogstation13/Yogstation/pull/8252

I lightened the dark middle part of the walls because that seemed to be a common complaint.

Unless I hear a genuinely valid reason to have these removed, they are not going to be reverted. You will get used to them. They are superior to the current sprites.

This is still an issue: https://github.com/yogstation13/Yogstation/issues/9193. The door does not render correctly, presumably because of https://github.com/yogstation13/Yogstation/pull/8901.

Fixes #9193

#### Changelog

:cl: Onule
imageadd: new sprites for titanium shuttle walls
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Will leave this open for a day.

**Comment by Kmc2000** [comment]
Don't do it par, these sprites are far, far worse than the old ones. Not even a joke about SOUL, they just look like something you'd see in gamemaker.

**Comment by jcatjmeow** [comment]
Pr title is misleading.

This pr also changes other sprites besides the walls.

As for the sprites themselves, some look ok, not a fan of the windows, they look very blocky and not very well blended imo. I also don't like that you're planning to selfmerge.

**Comment by jcatjmeow** [comment]
Better name 👍

**Comment by PettyOfficer** [comment]
What does putting on big boy pants have to deal with swallowing?

**Comment by jcatjmeow** [comment]
> What does putting on big boy pants have to deal with swallowing?

I'll tell you when you're older

**Review by jcatjmeow — APPROVED** [review]
Also I slept on the sprites. Still don't like the window. But a pr can be made at a later date to re-do those specifically, and I must admit the window is a lot cleaner than the current one. So yeah

**Comment by patpol4** [comment]
The tiles are awful but i like the walls

**Comment by nesisknesis** [comment]
heavily conflicts with the current artstyle

**Comment by Partheo** [comment]
Now also fixes #9193.

**Comment by TheBimmer231** [comment]
good sprites

**Comment by Hopekz** [comment]
I remember this test merge. 
I was optimistic about these walls and floors but after playing with them for a solid week they aren't good looking in my subjective opinion.
The floors are spirited in a way that makes them look like walls when colored (Good way to see this is outside of a shuttle like for example one of the Kitchen variations with titanium floors.

The walls themselves look ugly with that weird thing in the middle going across. Titanium walls before looked more "solid" made from a single seemingly strong material but with this PR it makes them look like some cheap composite material since it has to be layered with whatever the dark stuff is in the middle.

My argument isn't that it "doesn't fit"; more of an argument that these sprites are not as good as the current ones we are replacing with this PR.

**Comment by Partheo** [comment]
Hopek raises some good points about the floors that need to be addressed. I'm going to work on those, although not now since I have some other sprites to do first.

**Comment by Partheo** [comment]
Made some tweaks to the floors which I hope solves the issues that Hopek brought up. The floor tiles have had a few tweaks to reduce their overall contrast, and the saturation of the more colorful tiles was decreased. They should be more in line with what regular floor tiles look like now.

Prior:
image

Now:
image

**Review by JamieD1 — APPROVED** [review]

**Review by alexkar598 — APPROVED** [review]

**Comment by JamieD1** [comment]
THIS WILL ONLY END BADLY

**Comment by patpol4** [comment]
crunent asrtyle hurr

**Comment by Partheo** [comment]
shuttle sprites was an inside job

**Pull request merged**
