### PR TITLE
Storytellers

### PR DESCRIPTION
**Pull request by ToasterBiome**
Filled out by Molti, not biome

ported from
https://github.com/Monkestation/Monkestation2.0/pull/461
https://github.com/Monkestation/Monkestation2.0/pull/549
https://github.com/Monkestation/Monkestation2.0/pull/552
https://github.com/Monkestation/Monkestation2.0/pull/622
https://github.com/Monkestation/Monkestation2.0/pull/952
https://github.com/Monkestation/Monkestation2.0/pull/1135
https://github.com/Monkestation/Monkestation2.0/pull/1427

among others (really just sorta stole it directly from their current codebase)

# Why is this good for the game?
Dynamic is less dynamic than would be ideal and requires more work to update, maintain, and improve that we have
Storytellers is both more flexible to start, and is a lot easier to understand from a coding perspective, making it far less of a resource drain on our dev team to maintain

# Testing
constant work in progress

# Wiki Documentation

good luck mord

:cl:
rscadd: Adds the storytellers from Monke (and originally horizon)
rscdel: Expunges dynamic from the codebase
/:cl:

### CODE REVIEW

**Comment by PibeCantina** [comment]
Hopefully will make boring as hell rounds actually have something going on!!! (idk what storytellers really do)

**Comment by Cartlord** [comment]
What are the effects of adding this feature?

**Comment by Maia-J** [comment]
Hell yea

**Comment by ToasterBiome** [comment]
just use https://github.com/yogstation13/Yogstation/pull/22661

**Pull request closed without merging**
