### PR TITLE
EMP only removes limbs on heavy emp + augmented humanoids with ligament hook

### PR DESCRIPTION
**Pull request by Moltijoe**
only merge if #18309 does

it's pretty damning to lose a limb, light emps are super common too, limits it to only heavy emps.
also makes it remove limbs from those that got ligament hook and then augmented themselves
makes it not remove the head, both because becoming deaf, blind, and mute from a single emp was dumb, and because that would instakill an augmented person with ligament hook

also moves the IPC easydismember trait to inherent from species (like it should have been)(this will make it show up in preferences)
also uses the defines rather than the "text" that the defines stand for

:cl:  
tweak: EMP now also checks for ligament hook to remove limbs
tweak: EMP only removes limbs on heavy rather than any EMP strength
tweak: EMP no longer removes head 
/:cl:

### CODE REVIEW

**Comment by milk-is-cool** [comment]
this wont affect skeleton easydismember limbs right?

**Comment by Moltijoe** [comment]
> this wont affect skeleton easydismember limbs right?

not unless you get augmented

**Comment by wonderinghost** [comment]
I think this still happens when you got prosphetics. Cause I remember losing both of them when I got emp'd by cultist

**Comment by Moltijoe** [comment]
> I think this still happens when you got prosphetics. Cause I remember losing both of them when I got emp'd by cultist

It shouldnt, unless you were an IPC, in which case it doesnt matter between regular limbs and prosthetics

**Comment by wonderinghost** [comment]
No it's a thing. Had that happen when my character would magically change to a changeling and I managed to emp my prosphetics off

**Comment by iamthesilly** [comment]
> seemingly never happens

About 23% chance that you'll lose at least one

**Comment by Moltijoe** [comment]
other emp PR preferred

**Pull request closed without merging**
