### PR TITLE
Removes malf

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

This is just greenshift and then violent plasmaflood for 5 minutes and then boring.
Dumb
(not a simplehorror alt)

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscdel: Malf is no longer playable
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
buh buh buh buh bruh?

**Comment by Simplehorror** [comment]
This commit was created on GitHub.com and signed with GitHub’s verified signature.

**Comment by RG4ORDR** [comment]
Based.
I spilled my soda on the AI, get fucked lmao - die silly computah

**Comment by Moltijoe** [comment]
>This is just greenshift and then violent plasmaflood for 5 minutes and then boring.

Yes, i agree it should be disabled, but you better fuckin hurry up on it's rework then

**Comment by N3D6** [comment]
Idk man malf is really fun to play as, but i can understand why it's boring from any nonantag's perspective
I just don't really like removing gamemodes (unless it's really bad like gangs) because we barely have any variety as is

**Comment by Simplehorror** [comment]
IMPROVE DONT REMOVE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Simplehorror** [comment]
#Encourage20MinutePlasmaFloods

**Comment by Cartlord** [comment]
Why "improve don't remove" sometimes but then you do this

**Comment by Marmio64** [comment]
i feel like MALF could be a lot more fun if it was combined with a couple single antags/midrounds right off the bat and if the malf was not allowed to destroy the station (ie, plasmaflood. Doomsday would be okay) in order to accomplish it's goals.

**Comment by Bibby0110** [comment]
> i feel like MALF could be a lot more fun if it was combined with a couple single antags/midrounds right off the bat and if the malf was not allowed to destroy the station (ie, plasmaflood. Doomsday would be okay) in order to accomplish it's goals.

Malf needs a redo tbh

**Comment by Simplehorror** [comment]
"improve dont remove"
>instacloses the improvement

**Comment by Bibby0110** [comment]
> Why "improve don't remove" sometimes but then you do this

Because sometimes it's not feasible to keep something in while it's being changed.

**Comment by Bibby0110** [comment]
> "improve dont remove"
> 
> > instacloses the improvement

wasn't an improvement

**Comment by Simplehorror** [comment]
how was it not an improvement? your complaint is that the round is a snooze for the first 90 minutes and then it's all hands on deck. this is because the AI has to farm points for doomsday device. so I made it so they get doomsday device from the start LIKE THEY USED TO and so the round time is shorter and the AI has more freedom.

**Comment by forhiti** [comment]
PR: remove all game modes except tots/bb and everyone is a tot/bb.

Let's just make this a tdm server

**Comment by ReddicusDragon** [comment]
this removes a level of enjoyment from being a silicon player

**Comment by ReddicusDragon** [comment]
> this removes a level of enjoyment from being a silicon player

and I see no issue with that honestly

**Comment by Bibby0110** [comment]
> how was it not an improvement? your complaint is that the round is a snooze for the first 90 minutes and then it's all hands on deck. this is because the AI has to farm points for doomsday device. so I made it so they get doomsday device from the start LIKE THEY USED TO and so the round time is shorter and the AI has more freedom.

My complaint is that its a gamemode where it's just the AI plasmaflooding and killing everyone. Giving them the doomsday device won't change that.

**Comment by Simplehorror** [comment]
> > how was it not an improvement? your complaint is that the round is a snooze for the first 90 minutes and then it's all hands on deck. this is because the AI has to farm points for doomsday device. so I made it so they get doomsday device from the start LIKE THEY USED TO and so the round time is shorter and the AI has more freedom.
> 
> My complaint is that its a gamemode where it's just the AI plasmaflooding and killing everyone. Giving them the doomsday device won't change that.

you can do this with every gamemode
My complaint is that it's a gamemode where it's just the clockcult converting for 30 minutes and then defending for 5 minutes.
My complaint is that it's a gamemode where it's just the heretic sacrificing for 30 minutes and then ascending.
My complaint is that it's a gamemode where it's just the shadowlings thralling for 30 minutes and then ascending.

**Comment by Bibby0110** [comment]
>you can do this with every gamemode
My complaint is that it's a gamemode where it's just the clockcult converting for 30 minutes and then defending for 5 minutes.
My complaint is that it's a gamemode where it's just the heretic sacrificing for 30 minutes and then ascending.
My complaint is that it's a gamemode where it's just the shadowlings thralling for 30 minutes and then ascending.

all of these contain gameplay, doesn't count

**Comment by Simplehorror** [comment]
as opposed to malf which doesnt have gameplay... BECAUSE IT JUST DOESNT, OK?

**Comment by Bibby0110** [comment]
> as opposed to malf which doesnt have gameplay... BECAUSE IT JUST DOESNT, OK?

There's no gameplay for 90% of people when the AI plasmafloods like usual.

**Comment by Simplehorror** [comment]
> > as opposed to malf which doesnt have gameplay... BECAUSE IT JUST DOESNT, OK?
> 
> There's no gameplay for 90% of people when the AI plasmafloods like usual.     

There's no gameplay for 90% of people when the shadowlings thrall like usual.

**Comment by MajManatee** [comment]
Malf wasnt great to begin with, but the new AI systems seem to support it less and less.
its great fun for the ai and borgs but... eh
they dont need fun

**Comment by Potototatoh** [comment]
make it so borgs are vulnerable to plasma fire???????????

**Comment by Moltijoe** [comment]
> There's no gameplay for 90% of people when the shadowlings thrall like usual.

thralling directly involves people doing things and people dying
plasmaflood involves the atmos system doing things and people dying

one changes what gameplay those people are doing
the other directly removes people from doing gameplay

i'm conviced you're either trolling or actually need mental help

**Comment by Bibby0110** [comment]
> Malf wasnt great to begin with, but the new AI systems seem to support it less and less.
> its great fun for the ai and borgs but... eh
> they dont need fun

The final goal has always been to redo malf entirely when the new AI stuff is finalized.
The new AI stuff hasn’t really taken current malf into consideration since it would just end up being hacky patches to keep it semi-working

**Comment by JamieD1** [comment]
Ugh

**Comment by Simplehorror** [comment]
> > There's no gameplay for 90% of people when the shadowlings thrall like usual.
> 
> thralling directly involves people doing things and people dying plasmaflood involves the atmos system doing things and people dying
> 
> one changes what gameplay those people are doing the other directly removes people from doing gameplay
> 
> i'm conviced you're either trolling or actually need mental help

yeah except 90% of thralls just go afk because it's not fun

**Comment by ReddicusDragon** [comment]
code prs should not be touched by non-code maintainers

**Comment by BurgerLUA** [comment]
NO CHANGE IT TO MASTER- NOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Pull request merged**
