### PR TITLE
Mind Machine

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Mostly a port of vgstation-coders/vgstation13/pull/26706.
Adds two machines (mind machine hub & mind machine pod) that must be linked together to work. Combined, they allow people to mindswap between two bodies. It can be from two sentient people or two non-sentient animals.

It takes 30 seconds to transfer from one body to another.
It can cost between 4 charges (at tier 1 capacitor) and 1 charges (at tier 4 capacitor).
There is a chance between 40% (at tier 1 matter bin) and 0% (at tier 4 matter bin) that the mindswap will malfunction.
At tier 4 scanning module, it allows for a delayed transfer (with additional 20% malfunction chance); it also allows transfer to/from silicons. AI shells are excluded.

Charges can be regained by hitting the hub with a bluespace crystal (or its variants):
- Artificial: 1
- Normal: 2
- Refined (ERT): 5
- Telecrystal: 10

If the hub is emagged or emped, all mindswaps attempts will automatically malfunction until reset.
To revert the automatic failure, open the panel (screwdriver) and use a multitool on it.

When a mindswap malfunctions, all sentient pod occupants will be mindswapped to a non-sentient mob within 50 tiles. This can include humanized monkeys, station pets, or even mice in maint. If this is not possible, they will take 75 brain damage instead.

Mind protection and certain antag datums are prevented from mindswapping.
Certain mobs are prevented from being swapped to/from.

These machine circuit boards are locked behind Alien Biological Tools.
# Why is this good for the game?
A new quirky machine for people to play around with (for fun and games or as a victim in a traitor's gimmick) & to reverse the effect from a wizard apprentice or bad wizard who lucked into getting the mindswap spell.

# Testing
Tested in local. A bunch of stuff that I definitely tested:
- [x] Printable after unlocking Alien Biological Tools.
- [x] Various mental protections (wearing tinfoil hat & mindshield) prevents mindswapping.
- [x] Being a changeling (or having one of the restricted antags datum) prevents mindswapping.
- [x] Scanner prevents/allows silicon mindswapping & delayed transfer.
- [x] Animals swap faction, speak, speak chance.
- [x] On malfunction, animals get random faction.
- [x] On malfunction, get mindswapped and trapped in the CMO's office as Runtime.
- [x] No obvious runtimes.

# Spriting
Off, Open
image

Off, Closed
image

On, Closed
active

# Wiki Documentation
Add to [Alien Biological Tools](https://wiki.yogstation.net/wiki/Tech_Webs#Alien): Mind Machine Hub Board & Mind Machine Pod Board

# Changelog
:cl:  
rscadd: A pair of machines that allows people to mind swap between bodies of their choices. For fun, science, or torture; who knows what it will be used for?
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
so you saying i can be mindswapped into a bubblegum?!

**Comment by solwashere** [comment]
Will likely need a resprite at some point

**Comment by MajManatee** [comment]
Not sure of the use cases here, and the sprites definitely will clash, but a neat concept

**Comment by KingSuperBOB** [comment]
Considering this requires abductor tech can abductors buy it

**Comment by Runian** [comment]
> so you saying i can be mindswapped into a bubblegum?!

no

**Comment by LaOubliette** [comment]
considering it's locked behind alien tech and wont be reliably abused every single round, i say seems fun and neat

**Comment by neeshacark** [comment]
this is already doable with surgery so i see no issue with it

**Comment by Moltijoe** [comment]
Balance Council:
>Approved, but this could very easily prove problematic for admins, but that will be a "wait and see" thing

**Review by cuackles — CHANGES_REQUESTED** [review]
i agree with sol, this looks good but it will stick out way to much if its merged looking like that, it needs a simpler desing with less gradiant shadings

**Comment by Runian** [comment]
If anyone has better sprites, send them and I'll replace it; otherwise, I got nothing.

**Comment by ToasterBiome** [comment]
Undraft when you have sprites

**Comment by ToasterBiome** [comment]
Reopen when you have sprites

**Pull request closed without merging**
