### PR TITLE
Adds a paramedic room and a new cave on Kilostation.

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# Document the changes in your pull request

Adds a paramedic staging area below surgery on kilo station, also adds a new cave on the asteroids nearby kilostation
Was too lazy to test, oh well!
Fixes issue 12820 https://github.com/yogstation13/Yogstation/issues/12820
(P.S. Sorry for adding the cave in the same PR, my first PR and too lazy to turn back now :D )

# Wiki Documentation

Might need to add this to the locations of paramedic staging areas.

# Changelog

:cl:  
rscadd: Added paramedic area on kilo station along with a new cave.  
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
This is too many line changes, did you use fastdmm2 for this?

**Comment by bruhlookatthisdood** [comment]
> This is too many line changes, did you use fastdmm2 for this?

Sorry for late response, yes I did use fastdmm2 for this. A coder suggested it to me.

**Comment by bruhlookatthisdood** [comment]
i think its fixed now
hopefully...
probably not
i forgot to make the s in station a capital.

**Comment by bruhlookatthisdood** [comment]
hang on, i messed map up

**Comment by bruhlookatthisdood** [comment]
i did it

**Review by patpol4 — APPROVED** [review]
This is mostly fine, ill fix the missing firelocks later not to make conflicts

**Review by patpol4 — CHANGES_REQUESTED** [review]
Actually nevermind, the conflicts made themselves, please fix and also add firelocks here
image

**Review by patpol4 — APPROVED** [review]
All fine now

**Pull request merged**
