### PR TITLE
New Jukebox Music

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Adds new songs to the jukebox,

Eurobeat1 (https://youtu.be/PmObmXQxxJ0) **MODIFED IN AUDACITY**
Eurobeat2 (https://youtu.be/up6Nxg17opQ) **MODIFED IN AUDACITY**
Master of Puppets (https://youtu.be/_jYlloUKFmg) **MODIFED IN AUDACITY**
Calamity (https://youtu.be/17IZjvr5c1I)
PartyParty (https://youtu.be/4A1SiQkPqYM) **MODIFED IN AUDACITY**
Eurobeat3 (https://youtu.be/fxx5p8KnZ3w) **MODIFIED IN AUDACITY**
Cassette7 (https://youtu.be/MKKLwahE_J8)
Sandstorm (https://youtu.be/jWMTJ0oepCU)
that heyyayayayaya song from like 2009 (https://youtu.be/FR7wOGyAzpw)
wide putin song

#### Changelog

:cl:  
rscadd: Adds new jukebox music
soundadd: Adds new ogg jukebox sounds 
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Songs that aren't too good from these in my opinion (should probably be atomized like lobby music)
- Eurobeat3
- PartyParty

**Comment by swissloaf** [comment]
> Songs that aren't too good from these in my opinion (should probably be atomized like lobby music)
> 
> * Eurobeat3
> * PartyParty

no

**Comment by Featherfield** [comment]
Eyyy my submission got in

**Review by fluffe9911 — APPROVED** [review]
Seems fine needs to be added to config though

**Comment by JamieD1** [comment]
Added to Config

**Pull request merged**
