### PR TITLE
Totally normal new mining mob PR here

### PR DESCRIPTION
**Pull request by Scrambledeggs00**
Title is vague because I want this to be a surprise for miners, so if you are a miner...
**DON'T LOOK AT THIS**

# Document the changes in your pull request

Adds in the white wolf? (ambusher in-code) to IceMeta. Looks like a regular wolf until it gets to 175 health, after which it enters an enraged state where it moves and attacks faster but does less damage. After 6 seconds, it slows down and attacks less, but does more damage. Before revealing itself, it can only be differentiated from a regular wolf by its random twitch, which plays both a sound and animation. Also adds in a new toxin called "Carpenter Toxin" which slows people down but is fully countered by Epinephrine. The mob also has some sounds, but they are sounds that were already in the code, so no new sounds

Important Stats:
Health: 225

Enraged:
Damage: 2
move_delay: 2
rapid_melee: 4

No rage:
Damage: 12
move_delay: 4
rapid_melee: 1

Toxin:
Name: Unknown Toxin
Metabolism Rate: 2u
Effect: Slows victim by 50% and shows a bubble alert warning them
Counters: Epinephrine

P.S.
Forgot to mention that you can get the toxin by grinding up the tongue it drops on butcher.

# Why is this good for the game?

I think we can all agree that IceMeta doesn't have any challenging regular fauna, since most don't have a way of catching up to miners and/or have no ranged attack. This PR tries to fix that by adding in the white wolf? (ambusher in-code) mob. It solves this with its enraged state and toxin, with the rage giving it the speed and attacks needed to inject enough toxin into the miner to make them an easy target in their calmed down state where they do more damage.

Toxin wise, I made Epinephrine completely counter it since if I were a noob that just started mining and got attack by some fleshy horror, I'd probably use my epi pen, thinking it would help me. Usually this wouldn't help since the mob would kill you in crit, but since it counters the toxin it should allow them to escape it once it loses rage.

# Testing

I had a video showing the mob in action, but I can't figure out how to show it here >:[

I've tested it and both the mob and toxin work as intended and spawn on IceMeta.

# Spriting

Twitch Animation:
FleshmorphAmbusherMob

Revealed and Tongue Sprites:
FleshmorphAmbusherRevealed

# Wiki Documentation

Would need to add both the mob and toxin to their respective wiki pages.

As mentioned previously, it is named "white wolf?" in-game. It is fast for a fauna, especially when in its rage state. It reveals itself when damaged enough. When revealed, its attacks apply "Carpenter Toxin". The toxin slows the target down and shows a bubble alert when it does so, but can be completely countered by Epinephrine. It has a fast metabolism rate of 2u, so you need a lot in you for it to slow you down for any significant amount of time. The toxin can be gained by grinding the tongue it drops on butcher. The rest of its butcher list is just the white wolf's list.

# Changelog

:cl:  
rscadd: Added a new thing to IceMeta
imageadd: Sprites for the new thing
/:cl:

### CODE REVIEW

**Comment by ofscarletdreams** [comment]
why would they call it unknown toxin if the scan already knows it gets neutralized by epinethrine

**Comment by Moltijoe** [comment]
Doesnt touch mapping files, doesnt need mapping in changelog

**Comment by Yarinoi** [comment]
what the dog doin

**Comment by ofscarletdreams** [comment]
it does in fact touch the mapping files

**Comment by Scrambledeggs00** [comment]
> why would they call it unknown toxin if the scan already knows it gets neutralized by epinethrine

Placeholder name that I am too uncreative to change.

**Comment by Scrambledeggs00** [comment]
> Doesnt touch mapping files, doesnt need mapping in changelog

Ok, thought that the file I touched to add them to IceMeta was one.

**Comment by neeshacark** [comment]
> > why would they call it unknown toxin if the scan already knows it gets neutralized by epinethrine
> 
> Placeholder name that I am too uncreative to change.

call it carpenter toxin because this shit straight out of John Carpenter's The Thing

**Comment by AdamPrime314** [comment]
> I want this to be a surprise for miners

If it's the same wolf sprite it will just enter the meta in a week and become a second IceLands weaver. **BORING!** Make it pool from the list of polar bears and wolves for the initial sprite, gib at X damage then change sprite and stats to some "???" monster so it will look scarier and make you watch yourself.

> Toxin wise, I made Epinephrine completely counter it since if I were a noob that just started mining and got attack by some fleshy horror, I'd probably use my epi pen, thinking it would help me.

The mining survival medipen **ALREADY** contains 10 units of Epinephrine so this isn't forcing you to use a secondary, more scarce first-aid. Changing it to Sanguirite would definitely help as it's uncraftable and only available both at the hypospray vendor and the default medpen.

**Comment by N3D6** [comment]
This is cool af

**Comment by Scrambledeggs00** [comment]
> > > why would they call it unknown toxin if the scan already knows it gets neutralized by epinethrine
> > 
> > 
> > Placeholder name that I am too uncreative to change.
> 
> call it carpenter toxin because this shit straight out of John Carpenter's The Thing

That's actually a really good idea

**Comment by Scrambledeggs00** [comment]
> > I want this to be a surprise for miners
> 
> If it's the same wolf sprite it will just enter the meta in a week and become a second IceLands weaver. **BORING!** Make it pool from the list of polar bears and wolves for the initial sprite, gib at X damage then change sprite and stats to some "???" monster so it will look scarier and make you watch yourself.
> 
> > Toxin wise, I made Epinephrine completely counter it since if I were a noob that just started mining and got attack by some fleshy horror, I'd probably use my epi pen, thinking it would help me.
> 
> The mining survival medipen **ALREADY** contains 10 units of Epinephrine so this isn't forcing you to use a secondary, more scarce first-aid. Changing it to Sanguirite would definitely help as it's uncraftable and only available both at the hypospray vendor and the default medpen.

It is only wolf because _The Thing_ reference. Also I don't want to spend the next month spriting twitch animations and a new mob sprite, plus I plan on making variants of the other IceMeta mobs later if I remember. As for the toxin, it isn't meant to be super useful since I don't want it to become some meta toxin. Its purpose is to allow the mob to run down its target and as a memey slowdown chem that is easily countered.

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
