### PR TITLE
[bounty] Strawberry flavored candy!

### PR DESCRIPTION
**Pull request by alexkar598**
mmmmmmmmmm candy
image

Why: Adding fun food items

How to craft: 
5u of sugar
5u of blood
1 paper
1 crayon(not consumed)

:cl:  
rscadd: You can now craft strawberry "flavored" candies with sugar, blood, paper and a crayon!
/:cl:

### CODE REVIEW

**Comment by ChesterTheCheesy** [comment]
Why is it craftable with regular paper and not wrapping paper though?

**Comment by alexkar598** [comment]
To justify the low nutritional value, wrapping paper would mean it's too annoying to craft to craft easily but since it's a stack of 30 it means it's still mass producable

To clarify no matter either one, its mass producable meaning the nutritional value must be low. But with the wrapping paper, it becomes annoying to craft and the nutritional value is too crappy to be worth it

**Comment by JamieD1** [comment]
Never seen these before in my life, but whatever.

**Comment by MegaEmpirical** [comment]
Fuck this takes me back.

**Pull request merged**
