### PR TITLE
New wood type: ash caps

### PR DESCRIPTION
**Pull request by jcatjmeow**
### Intent of your Pull Request

A new mushroom that grows on lavaland!

Produces ash-cap-logs, which are like tower cap logs, but grey. And fireproof.

Mainly for ashwalkers. NT could harvest them to grow on station of course, but they will produce fewer logs unless they are on lavaland itself since they are out of their natural habitat 

- [x] Add Ash-Cap Plants (botany)
- [x] Add Ash-Cap Plants (lavaland)
- [x] Add Ash-Cap Seeds
- [x] Ash-Caps can be mutated into tower-caps (Deep lore: NT domesticated them)
- [x] Add sprites for the seeds, plants, wood
- [x] Ash caps produce ash cap wood
- [x] Ash caps naturally generate on lavaland like the other flora there already
- [ ] wild ash caps are "depleted" after one harvest, but regrow during ash storms
- [ ] Ash cap wood can be used to craft grey versions of wood items
- [x] Ash cap wooden objects are fireproof and have fire armor
- [ ] Ash caps produce many more logs when actually on lavaland vs on station
- [x] Ash caps replace tower-caps in the ashwalker ruin
- [x] Ash caps can't be used to make firebrands or bonfires, cause they don't burn n stuff
- [ ] Add colored wood framework so future wood variants are easier to code in
- [ ] Ash cap doors, walls, barricades etc are more resistant to fauna than standard iron or wood
- [x] Do a little dance

### CODE REVIEW

**Comment by ynot01** [comment]
can we see the dance

**Comment by jcatjmeow** [comment]
> can we see the dance

https://www.youtube.com/watch?v=Bjt7mDVCLtk

**Comment by boodaliboo** [comment]
you are a god

**Comment by jcatjmeow** [comment]
will re-open when I have solid stuff for this

**Comment by jcatjmeow** [comment]
later

**Comment by deathslayer2481** [comment]
Sad

**Pull request closed without merging**
