### PR TITLE
Removes the antinobilium shard

### PR DESCRIPTION
**Pull request by Simplehorror**
This reverts commit 0c3b5c5b51975866a1a777d079ca6d46ce9bdc05.

# Document the changes in your pull request

NOBODY EVER USED THIS THING. It was the WORST BUY IN THE GAME for 10TC which you could buy a revolver and ammo to instantly delaminate it. And it was HIJACK ONLY, when an exploding SM does jackshit for hijack unless it is singularity or tesla. It also had VERY hacky code randomly spliced into the supermatter.dm instead of using components or elements. 

THERE IS ALSO 0 COUNTERPLAY WHICH IS THE MOST UNFUN THING IN THE GAME. NO MATTER WHAT YOU DO TO THIS ITEM, IT'LL ALWAYS SUCK

# Wiki Documentation
Remove the anti nobilium shard
# Changelog
:cl:  
rscdel: Remove the anti nobilium shard
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
Lol

**Comment by ShoziOffical** [comment]
Watch this gets closed

**Comment by Moltijoe** [comment]
Make it good then

**Comment by Simplehorror** [comment]
> Make it good then

every buff pr i make gets closed

**Comment by The-Sun-In-Splendour** [comment]
idk i just thought it was a cool af item but last time i played yogs (instead of observing) was 2 years ago so...

**Comment by Moltijoe** [comment]
> every buff pr i make gets closed

Make better buffs then. 
Also, not every PR needs to get merged just because its made

**Comment by ShoziOffical** [comment]
A wise man once said "improve don't remove"

**Comment by Cartlord** [comment]
I think the problem is that it just doesn't fit into what the game is now - the natural response to "there's no counterplay" is "then add some", but I think the only way to do that would be to make certain gas mixes have a possibility of delaying or preventing the delamination - which will either mean that a basic plasma cooling setup stops it (making the shard useless) or stopping it requires a funky-ass mix that keeps the supermatter as cool as a cucumber (which effectively returns us to the point of there being no counterplay, as the only counter is something people will only deploy in this specific scenario and likely won't have time to set up once the sabotage is performed)
The supermatter's a weird engine, because even though you CAN mess with it a lot, there's never really a reason to unless you're farming anomalies - the only other thing a custom mix does is make more power, but really, there's no practical use for having more than half a megawatt at any time, and extra power can even end up fucking you over if you have clockies or a rogue A.I..
There's no practical reason to learn the supermatter's intricacies, so an item that fucks with it is of questionable balance, because there's no natural scenario in which someone would learn its counterplay.
I support the removal of antinoblium, because even if it's cool to blow a massive hole in the station, there's no easy way to make it balanced without reworking either the supermatter or power generation as a whole.

**Comment by Simplehorror** [comment]
> I think the problem is that it just doesn't fit into what the game is now - the natural response to "there's no counterplay" is "then add some", but I think the only way to do that would be to make certain gas mixes have a possibility of delaying or preventing the delamination - which will either mean that a basic plasma cooling setup stops it (making the shard useless) or stopping it requires a funky-ass mix that keeps the supermatter as cool as a cucumber (which effectively returns us to the point of there being no counterplay, as the only counter is something people will only deploy in this specific scenario and likely won't have time to set up once the sabotage is performed) The supermatter's a weird engine, because even though you CAN mess with it a lot, there's never really a reason to unless you're farming anomalies - the only other thing a custom mix does is make more power, but really, there's no practical use for having more than half a megawatt at any time, and extra power can even end up fucking you over if you have clockies or a rogue A.I.. There's no practical reason to learn the supermatter's intricacies, so an item that fucks with it is of questionable balance, because there's no natural scenario in which someone would learn its counterplay. I support the removal of antinoblium, because even if it's cool to blow a massive hole in the station, there's no easy way to make it balanced without reworking either the supermatter or power generation as a whole.

yeah it's really hard to balance around newbie engineers and pro engineers. on that note i have an idea.

**Comment by Simplehorror** [comment]
#16421 idea made

**Comment by Bibby0110** [comment]
Improve don’t remove

**Comment by CMOisLing** [comment]
Boring way to delem the engine, I dont really think there is any saving the idea of the antinobilium shard. It would have to be reworked completely.

**Comment by Moltijoe** [comment]
> I think the problem is that it just doesn't fit into what the game is now - the natural response to "there's no counterplay" is "then add some", but I think the only way to do that would be to make certain gas mixes have a possibility of delaying or preventing the delamination - which will either mean that a basic plasma cooling setup stops it (making the shard useless) or stopping it requires a funky-ass mix that keeps the supermatter as cool as a cucumber (which effectively returns us to the point of there being no counterplay, as the only counter is something people will only deploy in this specific scenario and likely won't have time to set up once the sabotage is performed) The supermatter's a weird engine, because even though you CAN mess with it a lot, there's never really a reason to unless you're farming anomalies - the only other thing a custom mix does is make more power, but really, there's no practical use for having more than half a megawatt at any time, and extra power can even end up fucking you over if you have clockies or a rogue A.I.. There's no practical reason to learn the supermatter's intricacies, so an item that fucks with it is of questionable balance, because there's no natural scenario in which someone would learn its counterplay. I support the removal of antinoblium, because even if it's cool to blow a massive hole in the station, there's no easy way to make it balanced without reworking either the supermatter or power generation as a whole.

Just make the antinoblium shard delam super violent, and have spacing the supermatter stop it. That way it's defined counterplay, but actually doing the counterplay can be super risky

**Comment by JamieD1** [comment]
Make it actually do something then.

**Pull request closed without merging**
