### PR TITLE
You can now shove dwarves into ovens and it will cook them

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

yeah there's no way this will backfire

# Changelog

:cl:  
rscadd: lets you shove children into the oven
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
The fuck is wrong with you

**Comment by LazennG** [comment]
holy based

**Comment by Chubbygummibear** [comment]
oh thank god

**Comment by NCRLouTenant** [comment]
Will they become a food item like putting a nuggeted person into the frier?

Is my goal to slowly turn the kitchen into a magical department where everything can turn people into sentient foodstuff? Tune in next week on Dragon Ball Z!

**Comment by Anvilman6** [comment]
Sometimes I think Yogs PRs can't possibly get any worse or more godless
Sometimes I'm proven wrong

**Comment by Xoxeyos** [comment]
What a wonderful addition to our codebase, I whole-heartedly support this PR.

**Comment by JamieD1** [comment]
What is wrong with our community, make it ready when ready

**Comment by ToasterBiome** [comment]
no reason to keep this open

**Pull request closed without merging**
