### PR TITLE
You can now construct the pressure tank, and be able to recolor it + other features like moving it, rotating it.

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
pressure tank can now be constructed with metals.
pressure tank can be recolored and relabeled with alt-click.
pressure tank can now be unanchored with wrench (you need to open the panel first), after being unanchored you can rotate it using a wrench by right-clicking.
rotating machines now shows the direction where it facing
# Why is this good for the game?
Because atmos techs love pressure tanks

# Testing
tested on local, can upload video if requested

# Wiki Documentation

# Changelog

:cl:
rscadd: pressure tank can now be constructed with metals.
tweak: pressure tank can be recolored and relabeled with alt-click.
tweak: pressure tank can now be unanchored with wrench (you need to open the panel first), after being unanchored you can rotate it using a wrench by right-clicking.
tweak: rotating machines now shows the direction where it facing
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
if you saying transfering the gas in bulk amount with pressure tank is bad then you should remove condensing cold gas in a canister and removing the huge scrubber as well

**Comment by ShoziOffical** [comment]
but surely this wouldnt be a problem, if anyone attempting to like transporting a large amount of gas and dumping it somewhere then its admin issue

**Comment by iamthesilly** [comment]
Wouldn't these just be better canisters if you can move them? What reason would there be to still use a regular canister?

**Comment by ShoziOffical** [comment]
I will make this better

**Comment by ShoziOffical** [comment]
> Wouldn't these just be better canisters if you can move them? What reason would there be to still use a regular canister?

better canisters? wrong, they dont have port for internal tanks to be put in, they have less armor likely to be destroyed easily, no rad particles shielding, requires more times to secure it and etc

**Comment by ShoziOffical** [comment]
got something in mind

**Pull request closed without merging**
