### PR TITLE
Makes conflicting topics cause a runtime so that travis can catch it

### PR DESCRIPTION
**Pull request by alexkar598**
see title, prevents people from implementing broken features

Depends on: #9553

### CODE REVIEW

**Comment by boodaliboo** [comment]
lol

**Comment by alexkar598** [comment]
Travis will fail until #9553 is merged

**Comment by ynot01** [comment]
local travis in clinical depression due to failing literally everything forever

**Comment by alexkar598** [comment]
Travis is failing because theres a bug in the codebase, the bug isnt fixed in this pr, which is why travis is failing because it wont let push code that detects as broken but it was already pushed

**Review by Amelia0010 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
