### PR TITLE
Reinforces Armoury

### PR DESCRIPTION
**Pull request by JamieD1**
image

Way too easy to break into, fed up of randoms just going FUCK IT ARMOURY

Alternative to https://github.com/yogstation13/Yogstation/pull/17347

Ill update the other maps depending on which passes

:cl:  
rscadd: Reinforces Armoury
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
im about to trigger the armory motion sensor as a perma prisoner

**Comment by JamieD1** [comment]
> im about to trigger the armory motion sensor as a perma prisoner

oops

**Comment by patpol4** [comment]
Better solution would probably be to add another tier of reinforced wall as a new turf and put it in secure spots on the station. But this is still better then that weird hallway thing

**Comment by Moja10** [comment]
Personally I don't think this change is needed, I think its designed to exactly be cracked open like a vulnerable egg with things like C4. Good things there's a guy hired by NT to sit there, watch the armory, right next to space suits and magboots, who starts with a shotgun to deal with any sort of situation that can happen!

I think its a good thing that antags with the right tools can get a surprise jump on breaking into the armory, any sort of change with another layer means that security has plenty of time to go into the armory themselves and arm up before the actual confrontation. Before, the antag breaking into the armory with C4 had the advantage because they get the first pickings, assuming they can deal with Armsky in time. This is not necessarily a bad thing or something that needs to be changed IMO.

If anything, the problem with the armory being cracked open is that monstermos is fucking psycho and vacuums up the weapons in such shitty ways, as soon as something like C4 goes off. Then lockers start getting sucked out too and form the worst clogged asshole. 

If I had to pick a solution of yours, I would pick a double layer over another hallway. But personally, I say its fine as is.

**Comment by JamieD1** [comment]
> Personally I don't think this change is needed, I think its designed to exactly be cracked open like a vulnerable egg with things like C4. Good things there's a guy hired by NT to sit there, watch the armory, right next to space suits and magboots, who starts with a shotgun to deal with any sort of situation that can happen!
> 
> I think its a good thing that antags with the right tools can get a surprise jump on breaking into the armory, any sort of change with another layer means that security has plenty of time to go into the armory themselves and arm up before the actual confrontation. Before, the antag breaking into the armory with C4 had the advantage because they get the first pickings, assuming they can deal with Armsky in time. This is not necessarily a bad thing or something that needs to be changed IMO.
> 
> If anything, the problem with the armory being cracked open is that monstermos is fucking psycho and vacuums up the weapons in such shitty ways, as soon as something like C4 goes off. Then lockers start getting sucked out too and form the worst clogged asshole.
> 
> If I had to pick a solution of yours, I would pick a double layer over another hallway. But personally, I say its fine as is.

The issue is its way too easy to get in and out without any resistance.

**Comment by Burger1998** [comment]
> > Personally I don't think this change is needed, I think its designed to exactly be cracked open like a vulnerable egg with things like C4. Good things there's a guy hired by NT to sit there, watch the armory, right next to space suits and magboots, who starts with a shotgun to deal with any sort of situation that can happen!
> > I think its a good thing that antags with the right tools can get a surprise jump on breaking into the armory, any sort of change with another layer means that security has plenty of time to go into the armory themselves and arm up before the actual confrontation. Before, the antag breaking into the armory with C4 had the advantage because they get the first pickings, assuming they can deal with Armsky in time. This is not necessarily a bad thing or something that needs to be changed IMO.
> > If anything, the problem with the armory being cracked open is that monstermos is fucking psycho and vacuums up the weapons in such shitty ways, as soon as something like C4 goes off. Then lockers start getting sucked out too and form the worst clogged asshole.
> > If I had to pick a solution of yours, I would pick a double layer over another hallway. But personally, I say its fine as is.
> 
> The issue is its way too easy to get in and out without any resistance.

thats a problem of warden players being shits who play it as security officer+ instead of defending the armoury

**Comment by githubuser4141** [comment]
> > > Personally I don't think this change is needed, I think its designed to exactly be cracked open like a vulnerable egg with things like C4. Good things there's a guy hired by NT to sit there, watch the armory, right next to space suits and magboots, who starts with a shotgun to deal with any sort of situation that can happen!
> > > I think its a good thing that antags with the right tools can get a surprise jump on breaking into the armory, any sort of change with another layer means that security has plenty of time to go into the armory themselves and arm up before the actual confrontation. Before, the antag breaking into the armory with C4 had the advantage because they get the first pickings, assuming they can deal with Armsky in time. This is not necessarily a bad thing or something that needs to be changed IMO.
> > > If anything, the problem with the armory being cracked open is that monstermos is fucking psycho and vacuums up the weapons in such shitty ways, as soon as something like C4 goes off. Then lockers start getting sucked out too and form the worst clogged asshole.
> > > If I had to pick a solution of yours, I would pick a double layer over another hallway. But personally, I say its fine as is.
> > 
> > 
> > The issue is its way too easy to get in and out without any resistance.
> 
> thats a problem of warden players being shits who play it as security officer+ instead of defending the armoury

It's still easy as fuck to breach. RCDs, thermite - a thing that literally anyone in sci/medical/engi can make at early-round, combat mechs, emags, high SPEECH/Charisma skill, the HoP's desk "hi can i be warden please kthxbye", any weapon with 21 force or over, vent crawling, or just a toolbox with maybe 1 extra welder, all of those can breach in no problem. This just makes it less of a headache whenever there's a space dust event.

And from my experience defending the armory isn't fun even as a warden - what happens is you'll probably take 50 damage from pressure, then you'll get oneshot by a stun baton/esword/ebow/get some floor tiles thrown at you from space, go into crit, NOT EVEN GET MERCYKILLED, crawl around in crit in a space suit + internals, float off into space and die because your guy with 101 damage couldn't just reach into his bag to epi himself (but he'd be fine if he was at 100 damage)

**Comment by patpol4** [comment]
Closing in favour of https://github.com/yogstation13/Yogstation/pull/17379

**Pull request closed without merging**
