### PR TITLE
Revert " Add a new advanced decontamination storage and suit storage snit QoL tweaks [REVIVE] "

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Reverts yogstation13/Yogstation#16584

All this does is 
1: make radiation more difficult to deal with, since engineering needs to manually build new equipment to effectively reduce it. I don't know why this is here but it seems like an excuse to add the item for:
2 (important): give engineers a portable 1000-4000 item storage bin, because they need that apparently
3: add shitcode

:cl:
rscdel: removes the advanced decontamination storage thing
tweak: removes the requirement to use advanced decontamination storage things to remove radiation, instead of normal decontamination storage things
/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Contributor Relations after reading this -100/Enemy

**Comment by Simplehorror** [comment]
don't put a changelog in your revert

**Comment by ShoziOffical** [comment]
It literally just a fucking upgrade for the suit storage, the storage is for to store items and then decontaminate them just like the damn suit storage

**Comment by ShoziOffical** [comment]
what do you mean make radiation more difficult to deal with? it's there to contain it and that is not an execuse for the storage because it doesn't have anything to do with it

**Comment by ShoziOffical** [comment]
shitcode? these are copypasted

**Comment by ShoziOffical** [comment]
You don't even know what this does

**Comment by ShoziOffical** [comment]
image

You see how useful this is, when engineering get irradiated and shit, med docs rarely go there because they lack access and not wanting to get irradiated by them

**Comment by SomeguyManperson** [comment]
> You don't even know what this does

I know that it can be unsecured and dragged around without losing any functionality

**Comment by ShoziOffical** [comment]
> > You don't even know what this does
> 
> I know that it can be unsecured and dragged around without losing any functionality

ok that one i can fix, but the fact that you made this revert pr is about the storage thing does not make any sense

**Comment by ShoziOffical** [comment]
You didn't fill out the reasons why is this bad or would it break the gameplay either

**Comment by ShoziOffical** [comment]
@Cartlord and @TheGamerdk don't play so i don't mind them disliking this, the people i met in round had really good feedbacks about this as it serves not only benefit for engineering but medical aswell

**Comment by ShoziOffical** [comment]
I'm tired of seeing dead people getting cloned because they have over 50000 radiation

**Comment by SomeguyManperson** [comment]
eh I'm sure this won't cause any problems until it gets properly addressed

**Pull request closed without merging**
