### PR TITLE
Makes Partheo codeowner of holidays.dm

### PR DESCRIPTION
**Pull request by Partheo**
For holiday music

### CODE REVIEW

**Comment by swissloaf** [comment]
Is this for the purpose of holiday-only music or are you actually taking control over the holidays now

**Comment by Partheo** [comment]
> 
> 
> Is this for the purpose of holiday-only music or are you actually taking control over the holidays now

I am Santa Claus.

**Comment by ynot01** [comment]
I am inevitable.

**Comment by Readystorm546** [comment]
Based

**Review by fluffe9911 — APPROVED** [review]
Imagine being considered a code owner in anything lmao

**Pull request merged**
