### PR TITLE
Adds new Mentor Alert noise, toggle-able by admins

### PR DESCRIPTION
**Pull request by JamieD1**
Adds new mentor sound

#### Changelog
:cl:  
bugfix: Adds optional mentor sound
/:cl:

### CODE REVIEW

**Comment by SuperTeaLove** [comment]
Is it me or is this title a lie? Are you lying to us???

**Comment by SuperTeaLove** [comment]
> Is it me or is this title a lie? Are you lying to us???

YOU CANT HIDE THE TRUTH

**Review by Partheo — APPROVED** [review]
why

**Comment by JamieD1** [comment]
> why

image

**Pull request merged**
