### PR TITLE
Gives metastation's brig its own atmos.

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# Document the changes in your pull request

Gives the metastation brig its own pipeline (still connected to distro but you get the point)
image

# Wiki Documentation

Maybe a repicture or something.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Adds an atmos room in yogsmeta brig maintenance so its not directly connected to distro.
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
no plastic flaps!?!??!?!?!

**Review by patpol4 — CHANGES_REQUESTED** [review]
Flaps would be nice, also remove the safety anchor in the atmos room, if someone gets teleported there they have no way of getting out and can't even be heard from the outside

**Comment by bruhlookatthisdood** [comment]
sorry will fix in a bit

**Review by patpol4 — APPROVED** [review]
Thanks

**Pull request merged**
