### PR TITLE
Allows AStar to path find around heirophant crusher walls(vortex thropheeeee)

### PR DESCRIPTION
**Pull request by alexkar598**
AStar can now pathfind around vortex walls

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Just fix legion cores instead

**Comment by alexkar598** [comment]
Make a bug report instead of crying on PRs

**Comment by HomocidlePancakes** [comment]
#6325 I was sure up until now it was reported. In any case, I have been telling about this bug to pretty much everyone

**Comment by alexkar598** [comment]
Doesn't work in game,trying to figure out why.

**Comment by alexkar598** [comment]
Alright, this PR will not fix the issue of mobs not able to path find around this effect for the simple reason that mobs do not pathfind,they just move towards the target like the dumbasses they are.

**Comment by HomocidlePancakes** [comment]
I am dumb. Whats “Astar”? Please explain

**Comment by GenericDM** [comment]
> 
> 
> I am dumb. Whats “Astar”? Please explain

https://en.wikipedia.org/wiki/A*_search_algorithm

**Comment by Bibby0110** [comment]
it make smart

**Pull request merged**
