### PR TITLE
does uh something with sinks? who even did this

### PR DESCRIPTION
**Pull request by SomeguyManperson**
I don't know what this does but it probably fixes something
:cl:  
bugfix: something with sinks
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
If this intends to fix #11653 it does not.

**Comment by Hopekz** [comment]
> If this intends to fix #11653 it does not.

This PR fixes a crime against humanity

**Comment by SomeguyManperson** [comment]
it fixes something that's for sure, probably handwashing

**Comment by adamsong** [comment]
This now fixes #11653

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
