### PR TITLE
some atmos things

### PR DESCRIPTION
**Pull request by Ktlwjec**
Moves the pumps to where they are in the image near the windows and changes some id tags.
image

### CODE REVIEW

**Comment by thehighwayman** [comment]
you broke it goddamn

**Comment by MegaEmpirical** [comment]
Parth had moved the pumps further out due to concerns about a bug where gases from pumps would mix with pipes overlayed on them but not connected. I am unsure if the bug still exists.

**Comment by Nickvr628** [comment]
Partheo is correct, that bug might be around. Also, the output of the N2+O2 mixer should be cyan to indicate it is the breathable mix. 

I do like how clean it looks though, it is nice

**Comment by Ktlwjec** [comment]
image
I didn't die

**Comment by thehighwayman** [comment]
did you die?

**Comment by MegaEmpirical** [comment]
Good enough for this guy. By the way, was there something changed about the tube to tcomms? I can't get to the left side of atmos in space like I could before.

**Comment by thehighwayman** [comment]
> Good enough for this guy. By the way, was there something changed about the tube to tcomms? I can't get to the left side of atmos in space like I could before.

The way she did the tunnels makes it impossible

**Comment by MegaEmpirical** [comment]
I've noticed. Also, seems like the 'random' room to the top right isn't random, it's always dusty detective.

**Comment by thehighwayman** [comment]
> I've noticed. Also, seems like the 'random' room to the top right isn't random, it's always dusty detective.

Thats cause she didn't make it random. I don't think she knows how

**Pull request merged**
