### PR TITLE
Adds update_appearance (this is friggin big news)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

This is a big PR that changes nearly every single item in the game that has some form of update_icon.
This PR ports ``update_appearance``, which is a helper meant to allow you to update name/desc/icon/icon-state/overlays when needed with one proc, rather than manually redefining and re-adding update_icon, update_icon_state, update_name, etc.

This also means it is much, much easier to port stuff from TG, with a lot of work I plan on doing being held up by the lack of this.

This may or may not break anything. Please testmerge this first.

This is a revival of https://github.com/yogstation13/Yogstation/pull/19297 - Their work has not been in vain.

# Changelog

:cl:  
experimental: Adds update_appearance. REPORT ANYTHING WRONG YOU MAY FIND!!
bugfix: Eguns with a flashlight on them wont stick around in your action buttons unnecessarily.
/:cl:

### CODE REVIEW

**Comment by Chubbygummibear** [comment]
jod bless

**Comment by Xander3359** [comment]
10/10 speedmerge

**Comment by Mqiib** [comment]
Cryotubes aren't definitely not working properly here. These are two open, empty tubes.
image

**Comment by iamthesilly** [comment]
Shotgun locker shows only one shotgun instead of how many are in it
image

Canisters always appear empty
image

Flashes keep the flash animation forever when you use them
image

**Comment by ThatGuyPhil** [comment]
sometimes the APC's are just black the screen doesnt appear they kinda just do this:
image
usually reconnecting fixes it but i cant be bothered

**Comment by Firewolf34** [comment]
It is possible that atmospheric manifold pipes are affected by this.

**Comment by JohnFulpWillard** [comment]
> It is possible that atmospheric manifold pipes are affected by this.

can you give reproduction steps on how it breaks vs what is expected?
It's likely that this PR is what broke that, yes.

**Comment by ShoziOffical** [comment]
image

image


whenever i choose layer 1,2,4,5 and spawn a pipe it also include the layer 3 as well

i think it only happen on the manifolds including heat exchanger manifolds

**Comment by ShoziOffical** [comment]
image

door with emergency access direction icon is just pure white

**Comment by ktlwjec0** [comment]
cig packs + cigar cases invisible when full, sprite doesnt show correct amount inside. food cooked on the griddle keeps its cooking lines (i think if removed before the griddle is turned off), soda dispenser sprite was showing as if a glass was inside it after the glass was removed. i'll grab screenshots when i can if needed

i think it broke pancake stacking but id have to double check, i put a cinnamon pancake on another earlier and it just acted as if the second one never existed

**Comment by ShoziOffical** [comment]
image

security level interface is blank

**Comment by ShoziOffical** [comment]
image

Energy gun wont update to lethal sprite

**Comment by N3D6** [comment]
Unsure if this PR fixes it but before this PR there was a bug where the KA sprites would break when you attached a bayonet and a flashlight to it. It’s supposed to show both but instead showed a KA with no attachments. Unsure if you fixed it here though

**Comment by ShoziOffical** [comment]
image

not sure if the pr causes this, syndie smoke just going crazy on round log

**Comment by ShoziOffical** [comment]
image

cig sprite isnt showing

**Comment by JohnFulpWillard** [comment]
> Unsure if this PR fixes it but before this PR there was a bug where the KA sprites would break when you attached a bayonet and a flashlight to it. It’s supposed to show both but instead showed a KA with no attachments. Unsure if you fixed it here though

Yea
image

**Comment by ShoziOffical** [comment]
critter crate becomes invisible when opened
image

**Comment by bruhlookatthisdood** [comment]
image
drawn back bow causes game to not see the bow itself

**Comment by ShoziOffical** [comment]
image

canister is now bright

**Comment by bruhlookatthisdood** [comment]
image
solars

**Comment by ShoziOffical** [comment]
image
 
image

remote signal device and button not changing color

**Comment by ShoziOffical** [comment]
image

canister has red light even tho theres no gas in

**Review by cuackles — APPROVED** [review]

**Comment by ShoziOffical** [comment]
john... why blinking red canister when theres no gas before blinking red is when theres a small trace of moles left inside the canister, no light is when theres no gas in. This is just odd looking at them blinking thinking theres gas inside

**Comment by ShoziOffical** [comment]
image

layer adaptor not removing extended pipes

**Review by ynot01 — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Comment by Therandomhoboo** [comment]
The mask when you're toggling it on and off (the one you get in your starter box) shows twice. As if you still have it up and when you moved it to one side

**Comment by ShoziOffical** [comment]
the disposal bin handle sprite isnt moving anymore when you toggle it

**Pull request merged**
