### PR TITLE
Do NOT make a new accent. Worst mistake of my life, holy fuck.

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Adds a Russian accent. For space Russians and those who want it, I guess.

PLEASE submit suggestions for words and their replacements. 

I used our list of top 1000 most common words and replaced those that needed replacing.
 Ws mostly got turned into Vs
 Rs were extended to look more like rolling
 Some Cs were made into Ks for a harder sound
 some filler words (the, a, an) were removed because :) (it made sense at the time)
 open to suggestions for changes and additions.

# Why is this good for the game?

More accents are good. Plus space Russians speak perfect English? I don't think so.
# Testing

I'm sure it will be fine when its done...

# Wiki Documentation
New Accent

# Changelog

:cl:  
rscadd: Russian Accent
experimental: Might look wierd for a bit while its dialed in.
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
no cyka blyat replacements
-1

**Comment by Moltijoe** [comment]
> some filler words (the, a, an) were removed because :) (it made sense at the time) open to suggestions for changes and additions.

this one might make it feel sorta weird since i dont think any other accent removes words entirely, especially when considering the double spaces it makes

**Comment by MajManatee** [comment]
Im hoping it wont be too noticeable, but if it is I can change it.

**Review by Moltijoe — APPROVED** [review]
code looks fine, not sure if it'll feel like russian when reading, but it can be tweaked

**Pull request merged**
