### PR TITLE
AI now starts with doomsday device if malf

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

99% of the time spent in malf rounds is the AI trying to get points for the doomsday device, so we should just shorten the round time by giving the AI doomsday to begin with as they're not going to get anything else anyway. This is how I remember it working where the AI got Doomsday to start off with and it was the win condition and I think it works better. This should make Malf rounds less secret-extended until 1 hr and then plasmaflood.

Closes #16542

# Spriting

# Wiki Documentation

AI now starts with doomsday device if malf
cant be bought no more
# Changelog

:cl:  
tweak: AI now starts with doomsday device if malf
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Meme prs are a gitbannable offense

**Comment by Simplehorror** [comment]
this isn't a meme PR, this is how malf used to work and it was better

**Comment by Simplehorror** [comment]
read my reasoning before getting angry

**Comment by Bibby0110** [comment]
Nope

**Comment by Cartlord** [comment]
Why not?

**Comment by Simplehorror** [comment]
i made it so it must be a bad PR, ping someone to reopen it for me please

**Comment by Bibby0110** [comment]
> i made it so it must be a bad PR, ping someone to reopen it for me please

As the resident AI person this is a no.

**Comment by Simplehorror** [comment]
> > i made it so it must be a bad PR, ping someone to reopen it for me please
> 
> As the resident AI person this is a no.

who died and made you the resident AI person

**Comment by Hopekz** [comment]
Yogdev

**Comment by Bibby0110** [comment]
> who died and made you the resident AI person


me

**Comment by Cartlord** [comment]
> > i made it so it must be a bad PR, ping someone to reopen it for me please
> 
> As the resident AI person this is a no.

_Why is it a no?_

**Comment by Sniblet** [comment]
https://github.com/yogstation13/Yogstation/pull/15937#issuecomment-1259972909
Someday the Yogdevs will learn that people don't respect their ideas for the usernames attached to them alone, and actually walk someone through the reasoning behind why they're being shot down
That day was not two months ago and it is not today

One of malf's several problems is the immense meaningless artificial zero-stakes timesink of getting malf points. Every other antag that ramps in power has to affect other players to do it - the blob must expand, the bloodsucker must suck, but the mald-functioning AI must remember to click the buttons every 60 seconds. The system might as well be replaced with passive income. Or better yet, not waste 90 minutes of roundtime, and not exist at all in any form remotely like this.

**Pull request closed without merging**
