### PR TITLE
Balances Stimulants - 5 to 8 TC 2 to 3 Uses

### PR DESCRIPTION
**Pull request by JamieD1**
Balances Stimulants - 5 to 8 TC 2 to 3 Uses

:cl:  
tweak: Balances Stimulants - 5 to 8 TC 2 to 3 Uses
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
each dose now costs .1111 TC more, please state this is a nerf.

**Comment by Reed0506** [comment]
2.5 tc per use to 2.67 tc per use seems like a kinda small change. i guess this just makes it more of an investment rather than a low tc cost thing to grab?

**Comment by JamieD1** [comment]
The biggest change is now you cant buy CQC and this at the same time.

**Comment by ghost** [comment]
Stealthy batton buff

**Comment by JamieD1** [comment]
> Stealthy batton buff

what?

**Comment by ghost** [comment]
> > Stealthy batton buff
> 
> what?

Stun resistance sources nerfs = button buffs

Change my mind

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
