### PR TITLE
buffs apples

### PR DESCRIPTION
**Pull request by boodaliboo**
apples are supposedly the healthiest fruit by that one saying. this gives apples 1% more vitamin then vulgaris to go with this doctors saying
#### Changelog

:cl:    
tweak: tweaked the ammount of vitamins apples have
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
vulgaris is not a fucking fruit

**Comment by boodaliboo** [comment]
> vulgaris is not a fucking fruit

yes it is

**Comment by MrHorizons** [comment]
I mean, most "fruits" in-game seem to be only 4% vitamin or so. Debate over vulgaris being a fruit all you want, but this is a solid buff to apples.

Though perhaps increase the vitamin content of golden apples as well, to something like 8% or even 10% vitamin?

**Comment by alexkar598** [comment]
Why is this PR needed

**Comment by boodaliboo** [comment]
> Why is this PR needed

i believe it helps makes medibots quote "a apple a day keeps me away" by healing you slightly more then other fruits

**Comment by alexkar598** [comment]
Not merging prs for the sake of merging prs

**Pull request closed without merging**
