### PR TITLE
fixes nickvr

### PR DESCRIPTION
**Pull request by Amelia0010**

### CODE REVIEW

**Comment by TacticalSpacePilot** [comment]
Good lord finally. This bug was really fucking bothering me

**Comment by Nickvr628** [comment]
Nich you forgot to comment out the code component. And don't forget the 24 hour rule. This ISN'T a bugfix so you cannot mememerge it the moment travis passes. 

also how did you get it to compile if you just deleted a sprite, now code points to a sprite that doesn't exist.

**Comment by Nickvr628** [comment]
wait shit I realized you ADDED bytes to the sprite file, which means you added something to my sprite....

**Comment by Nickvr628** [comment]
fuck

**Comment by Bibby0110** [comment]
he gave you a R E D armband

**Comment by Amelia0010** [comment]
someone doesn't know how icondiffbot works

**Review by alexkar598 — APPROVED** [review]
Normally, I'd say this is too Nazi to be in the game buttttttt, it is a _contraband_ poster soooooo

**Pull request merged**
