### PR TITLE
Indicates that admin-cluwned cluwnes are very valid via flavortext

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

Adds examine text that says "Looking at [src] makes you seething with rage! Beat the shit out of [p_them()]!"

Make admincluwnes especially valid
It's a surprise tool that will help us later

# Changelog

:cl:  
rscadd: Added flavor text to admin cluwnes 
/:cl:

### CODE REVIEW

**Comment by ChesterTheCheesy** [comment]
So, there's valid and non-valid cluwnes now? Or are all cluwnes still valid?

**Comment by patpol4** [comment]
I think this just indicates that you're supposed to be beating them and its not a random event

**Comment by Tipy1802** [comment]
> So, there's valid and non-valid cluwnes now? Or are all cluwnes still valid?

All cluwns are valid but I think Ynot wants to make sure people always valid this type of cluwns

**Comment by ChesterTheCheesy** [comment]
It'll be confusing for everyone, just because a text shows you "you feel like punching them", doesn't mean you should.

**Pull request closed without merging**
