### PR TITLE
Ports *nya, *weh, and *awoo emotes from Citadel

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
soundadd: Adds "nya", "weh", and "awoo" emotes
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Ok but why

**Comment by ynot01** [comment]
based

**Comment by maxion12345** [comment]
I still can't *scream or *yell tho

**Comment by ghost** [comment]
is this bait

**Comment by Tipy1802** [comment]
> I still can't *scream or *yell tho
 
You can actually *scream

**Comment by ghost** [comment]
God should have sunk that fucking ark.

**Comment by UselessTheremin** [comment]
image

**Comment by ThatGuyPhil** [comment]
oh no

**Comment by overlord12345** [comment]
Weh good the other two bad

**Comment by boodaliboo** [comment]
download (6)

**Comment by LoliconSlayer** [comment]
Remove yourself from this codebase

**Review by Partheo — CHANGES_REQUESTED** [review]
"Awoo" sound is really bad, I bet you could record your own that would be twice as good. The other two are fine.

why tho

**Comment by patpol4** [comment]
I fully support this addition

**Comment by Moggram** [comment]
OwO

**Comment by ynot01** [comment]
awoo.ogg very low quality please revoice it

**Comment by SomeguyManperson** [comment]
napalm (2)

**Comment by Georgeur** [comment]
I. The most robust chaplain main on yogstation. The modern day Van Hellsing. Purifier of cults. 
Look forward to this new crusade against the unpure. 
thumbs up lads

**Comment by boodaliboo** [comment]
can this just be closed already, it doesnt fit with the server alot of people dont like it and its causing drama.

**Comment by boodaliboo** [comment]
trench asked me to post this "Do you know what happens if this PR is merged? Communism wins. Stalin wins. Those red bastards up in Moscow win. Do you want the hammer and sickle flying over every American home from D.C. to San Fran? Because if you do, merging this fucking PR is the straight road to that hellscape, pal."

**Comment by Mqiib** [comment]
image

Alright, this PR doesn't fit our community at all. Do we need people going "nya" or "awoo" randomly? No. Yogs isn't some funny cutsie anime with cat schoolgirls running around. I don't play on yogs for that kind of environment. If I wanted that I would go to any one of the many available furry/erp/what-have-you servers with this kind of stuff like citadel or skyrat or whatever. I really, really don't like the idea of this because it adds nothing of value to the server.

**Comment by Moja10** [comment]
This isn't happening. This is not what Yogs is about.

**Comment by Georgeur** [comment]
wow yogs staff are so bad
im ganna make so many reddit posts about this

**Comment by LoliconSlayer** [comment]
Blessed Moja

**Pull request closed without merging**
