### PR TITLE
Mechs can be repaired from destruction, capacitor no longer protects from EMP

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Mech capacitor no longer defends it against EMP damage

The mech can be fully repaired, each equipment also having a chance to not be destroyed (provided it is salvageable)

Spawned wreckage will still be unrepairable (except for the freeminer mech which is meant to be reconstructed)

See wiki section for details

# Wiki Documentation

The capacitor will always be destroyed upon mech destruction

No capacitor will render the mecha unrecoverable when destroyed

T3+ capacitor will preserve scanning module

T4 capacitor will preserve cell also (but drain it some bit)

Each equipment will have 20/40/60/80% chance to be retained depending on capacitor tier

Mech repair will take a total of 80/40/27/20 seconds depending on capacitor tier

Roboticists do this 20% faster, so 64/32/21/16 seconds instead

To repair mech, Welder->Welder->Wrench->5 Wires

# Changelog

:cl:  
rscadd: You can now repair mechs when they are destroyed
tweak: Capacitor no longer protects mechs from EMPs, but instead preserves it from total destruction
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
what the fuck is a "mecha"? we use "exosuits" and "mechs"

**Comment by ynot01** [comment]
> what the fuck is a "mecha"? we use "exosuits" and "mechs"



The term "mecha" is also used several places elsewhere, see the file name & path, and description of the wreckage (part where it says "mecha" is untouched by me)

**Comment by JamieD1** [comment]
Doesnt this just make it alot easier to get out and fix it before getting back into battle.

**Comment by ynot01** [comment]
> Doesnt this just make it alot easier to get out and fix it before getting back into battle.

not sure what you mean, the mech has to be destroyed for this to work, and would take longer than just welding the mech back to full, plus it drains cell charge even on T4

**Comment by githubuser4141** [comment]
> 

you do realize, bluespace RPEDs can carry scanmods, capacitors and T4 charged cells, and you can fit a BSRPED in your backpack 

Anyone can carry mid-game RND stuff on themselves and essentially respawn their mech whenever it's destroyed

**Comment by ynot01** [comment]
> Anyone can carry mid-game RND stuff on themselves and essentially respawn their mech whenever it's destroyed

yes, after at least ~20 seconds of standing still and repairing

if the mech is being actively attacked, the pilot will have no opportunity to repair the mech

**Review by JamieD1 — APPROVED** [review]
We can see how it goes

**Pull request merged**
