### PR TITLE
"Station adrift" station trait

### PR DESCRIPTION
**Pull request by ynot01**
We're leaving together
But still it's farewell
And maybe we'll come back
To Earth, who can tell?

# Document the changes in your pull request

Space parallax (if your parallax is on) will slowly rotate with this trait active

It is very pretty imo

Can be a bit trippy aswell

# Changelog

:cl:  
rscadd: Added "Station adrift" station trait"
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Worried about accessibility (motion sickness)

**Comment by Cartlord** [comment]
wouldn't those people have the parallax disabled anyway

**Comment by Hopekz** [comment]
> Worried about accessibility (motion sickness)

In 2D games if someone suffers from bad motion sickness the act of moving the camera when you move your character causes more of a nauseating effect vs these star sprites moving.

**Review by Moltijoe — APPROVED** [review]
Motion sickness is avoided by turning off parallax, as they probably already do

**Pull request merged**
