### PR TITLE
you can no longer absolutely destroy inhand monkeys ( :( )

### LINKED ISSUE #14493: Monkeys can be deep fried infinitely
## Test Merges: 
Not Supplied / None
## Reproduction:
description: when picking up a monkey it becomes an item in your hand, you can then take the monkey and put it in a fryer. Upon frying it and consuming it the monkey body will appear back but you will still regenerate hunger from eating the fried monkey. This can be uses to infinitely eat a fried monkey.

 Submitted by: Neptune (362425279022497813)

### LINKED ISSUE #14498: Destructive Analyzering E-N deletes him
## Test Merges: 
Not Supplied / None
## Reproduction:
description: Picking E-N up and putting him in the Destructive Analyzer as an item, then destroying him, permanently fully deletes him. Other animals when killed this way drop a corpse on the tile of the DA, but E-N ceases to exist, and throws a runtime error.

 Submitted by: Vaelophis Nyx (She/Her) (319685669586862087)

### PR DESCRIPTION
**Pull request by tattax**
closes https://github.com/yogstation13/Yogstation/issues/14493
closes https://github.com/yogstation13/Yogstation/issues/14498

# Document the changes in your pull request

:(

:cl:  
bugfix: you can no longer mess with inhand mobs
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
mentioned some further things about this in #14493

**Comment by alexkar598** [comment]
https://github.com/yogstation13/Yogstation/blob/00dfc2da17127c6f7bf1b000337d018f2377e6fc/code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm#L39-L53

**Comment by tattax** [comment]
> https://github.com/yogstation13/Yogstation/blob/00dfc2da17127c6f7bf1b000337d018f2377e6fc/code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm#L39-L53

this doesn't account for other machinery like grinders

**Comment by VaelophisNyx** [comment]
Note that you cannot put a monkey into a grinder unless it was fried

**Comment by tattax** [comment]
it's an example

**Comment by JamieD1** [comment]
> > https://github.com/yogstation13/Yogstation/blob/00dfc2da17127c6f7bf1b000337d018f2377e6fc/code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm#L39-L53
> 
> this doesn't account for other machinery like grinders

Neither does this PR, put it in the blacklist instead.

**Comment by tattax** [comment]
> Neither does this PR, put it in the blacklist instead.

it does

**Comment by Bibby0110** [comment]
> > Neither does this PR, put it in the blacklist instead.
> 
> it does

it doesn't?

**Comment by tattax** [comment]
> it doesn't?

it does

**Comment by JamieD1** [comment]
Please just add it to the blacklist.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
