### PR TITLE
Places Emergency Shuttle Console on Raven Shuttle

### PR DESCRIPTION
**Pull request by alao3alao3**
what the fuck

##### Changelog

:cl:  
rscadd: Emergency shuttle console added to Raven  
rscdel: Standard shuttle console is removed from Raven
/:cl:

### CODE REVIEW

**Review by SomeguyManperson — APPROVED** [review]
code ing

**Comment by alao3alao3** [comment]
these prs are me favourite

**Comment by Jarod1200** [comment]
speedmerge

**Review by patpol4 — APPROVED** [review]
I wonder how long did we have it like this

**Comment by MrHorizons** [comment]
> I wonder how long did we have it like this

Too long, I think.

**Pull request merged**
