### PR TITLE
Limits the contract of apprenticeship to wizards

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request
You must now be a wizard to use the contract of apprenticeship

# Changelog

:cl:  
bugfix: fixed non wizards getting apprentices
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
maybe make it apply to slaughter demon blood vials as well? those seem like a lot more of a bad idea.

**Comment by alexkar598** [comment]
Why?

Its not a bug its a tweak

**Comment by adamsong** [comment]
> maybe make it apply to slaughter demon blood vials as well

Are slaughter demons bound to their summoner? That is the main issue here, is the apprentice would be bound to a nonantag if a nonantag used it.

> Why?

Nonantag with a bodyguard that can muderbone, not a good idea

**Comment by Hopekz** [comment]
> Nonantag with a bodyguard that can muderbone, not a good idea

In what situation does this non-antag get access to this item?
There is no workaround with your fix as well so if someone wanted to use this item to bus they can't override it

**Comment by adamsong** [comment]
> In what situation does this non-antag get access to this item?

Made this pr because a wizard gave an assistant a contract and they self antagged with it

> There is no workaround with your fix as well so if someone wanted to use this item to bus they can't override it

Will add when I get back to my computer

**Comment by Jarod1200** [comment]
Slaughter demons have no allegiance. Their objective says "kill everyone" this includes the summoner

**Comment by adamsong** [comment]
Then there is no reason to prevent their summon, the main problem with the apprentice is their allegiance to the nonantag, whereas for the slaughter demon there is no difference between wizard and non wizard using it

**Comment by maxion12345** [comment]
Make it so lawyers can use em lmao

**Comment by TheLinuxOS** [comment]
> Make it so lawyers can use em lmao

Make traitor lawyers able to buy em

**Comment by adamsong** [comment]
> Make traitor lawyers able to buy em

No

**Comment by SomeguyManperson** [comment]
how would a non-antag even GET a contract the wizard would have to like buy one then not use it and not refund it then have someone else use it like ????????

**Review by Bibby0110 — DISMISSED** [review]
Code wise you need an override at the very least.

**Comment by adamsong** [comment]
> how would a non-antag even GET a contract the wizard would have to like buy one then not use it and not refund it then have someone else use it like ????????

This did happen

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
