### PR TITLE
Warden gets a brig-restricted taser in his locker | MODULAR

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
I have added a taser to the warden's locker that is restricted to use to brig only. Should help make brig feel like a no-go zone more. The Chef gets CQC to defend his kitchen, the warden gets a taser. Additionally, this will encourage more players to play warden because they want to use the taser, and encourage the warden to actually defend the brig and stop escaping prisoners.
# Wiki Documentation
Warden gets a taser, but it only works in brig.
# Changelog
:cl:  
rscadd: The warden got a bonus and spent it on a brand new taser.
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
No, we don't remove stuns then add back a taser, warden stop people trespassing in the armory with lethal ammunition, not instant win stuns.

**Comment by Simplehorror** [comment]
> No, we don't remove stuns then add back a taser, warden stop people trespassing in the with lethal ammunition, not instant win stuns.

Yes murder someone for going into brig or escaping from their 1 minute sentence and then they have to spend 15 minutes being healed instead of a 10 second stun. How incredibly unfun for both sides.

**Comment by 00ze-cyclone** [comment]
Disabler do the work just fine for greytiders and such. Actual threat get shotgunned, the tazer is just a cheap instant win. The warden is already the most armed crewmember because of their shotgun and the fact the armory is next to their office.
Also during nuke ops the warden could just take the disk, sit in the brig and cheese all the nuke ops unless they took bombs or deswords (and we don't need to make deswords even more the meta), same problem for revs, it would be awful to have to get the heads if they go to the brig because there would be a dude that stun you instantly while another laser you and you wouldn't be able to do anything.

**Comment by Simplehorror** [comment]
> Disabler do the work just fine for greytiders and such. Actual threat get shotgunned, the tazer is just a cheap instant win. The warden is already the most armed crewmember because of their shotgun and the fact the armory is next to their office. Also during nuke ops the warden could just take the disk, sit in the brig and cheese all the nuke ops unless they took bombs or deswords (and we don't need to make deswords even more the meta), same problem for revs, it would be awful to have to get the heads if they go to the brig because there would be a dude that stun you instantly while another laser you and you wouldn't be able to do anything.

The whole point of revolutionaries is that you work as a team, the taser only has so many shots and you can help eachother out. Alternatively, convert the chemist and get anti-stuns. Flashbangs are much worse than tasers right now for revolutionaries and this is a bad argument. Disablers act too slow to stop a guy walking out, and don't work for more then one person at a time so if you're fighting people with a welding mask you're screwed.

**Comment by Simplehorror** [comment]
Considering restricting it from 4 shots to maybe 3 or 2.

**Comment by Marmio64** [comment]
They already have an instant win gun called the combat shotgun. If someone isn't important enough to shoot with it then you use the disabler., Which is more than enough for unarmed prisoners being brought in by sec

**Comment by Simplehorror** [comment]
> They already have an instant win gun called the combat shotgun. If someone isn't important enough to shoot with it then you use the disabler., Which is more than enough for unarmed prisoners being brought in by sec

We need to be replacing ballistics with energy anyways

**Comment by ghost** [comment]
Make warden have powers of an ascended shadowling while in brig

**Comment by tattax** [comment]
krav maga now give you the flying fang pounce, instant agro grab, neck snap, summon guns, the traps, projectile reflection and +30 unarmed damage

**Comment by Simplehorror** [comment]
> Make warden have powers of an ascended shadowling while in brig

Please do not compare tasers to ascended shadowlings

**Comment by ghost** [comment]
> krav maga now give you the flying fang pounce, instant agro grab, neck snap, summon guns, the traps, projectile reflection and +30 unarmed damage

You forgot disintegrate

**Comment by Moja10** [comment]
People hate tasers in actual gameplay, I don't know why you would create multiple PRs all removing or nerfing various hard stuns from antags but then thinking that a taser is fine. There's a reason why admins choose to never spawn red alert ERTs

**Comment by SomeguyManperson** [comment]
eh warden already gets krav to beat up tiders

**Comment by Simplehorror** [comment]
> eh warden already gets krav to beat up tiders

nobody uses krav maga

**Pull request closed without merging**
