### PR TITLE
Ports the Rubber Pigeon from Prerebase Yogs!

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 fluffe9911 for porting Qustinnus for making and kmc for spriting
add: Rubber Pigeons and the crate has returned!
/🆑

### CODE REVIEW

**Comment by Amelia0010** [comment]
I'm starting a council vote :)

**Comment by Alexandria404** [comment]
earrape haram

**Comment by Kmc2000** [comment]
merge this

**Review by Kmc2000 — APPROVED** [review]
Looks good to me

**Comment by Amelia0010** [comment]
https://forums.yogstation.net/index.php?threads/vote-merge-this-pr-https-github-com-yogstation13-yogstation-tg-pull-4330.18189/

**Comment by fluffe9911** [comment]
oh well

**Pull request closed without merging**
