### PR TITLE
Makes balloon alerts better

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

wtf is this shit?

# Wiki Documentation

# Changelog

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
a polished turd is still a turd

**Comment by Bibby0110** [comment]
> a polished turd is still a turd

Weird way to talk about your skincare routine but ok

**Comment by JamieD1** [comment]
Video please

**Comment by Bibby0110** [comment]
> Video please

of what

**Comment by ToasterBiome** [comment]
> > Video please
> 
> of what

of them in action

**Comment by Bibby0110** [comment]
> > > Video please
> > 
> > 
> > of what
> 
> of them in action

the current BYOND version we use is bugged for them

**Comment by Cartlord** [comment]
Then why do we even have them if they can't be tested locally?

**Comment by Bibby0110** [comment]
> Then why do we even have them if they can't be tested locally?

They can? Not sure where you got that from

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
