### PR TITLE
Adds shipbreaking to Icemeta

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Adds all current shipbreaking structures to Icemeta

# Why is this good for the game?

I was too busy figuring out if I can to figure out if I should.

# Testing

it actually works wonderfully

Inside area
image

Shipbreaking area
image

# Wiki Documentation

Will be added

# Changelog

:cl:  

mapping: Adds shipbreaking to Icemeta

/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
image

**Comment by cowbot92** [comment]
> image

image

**Comment by N3D6** [comment]
Rip ATVs

**Comment by cowbot92** [comment]
> Rip ATVs

There's still one!

**Review by neeshacark — CHANGES_REQUESTED** [review]
image
warning decal in maint is messed up

image
remove the lattice under this catwalk

image
fix these two interior maint warning decals not having the corner bits while you're here

**Comment by cowbot92** [comment]
> 

Adjustments made

**Review by neeshacark — APPROVED** [review]

**Pull request merged**
