### PR TITLE
Unifies the cloaks

### PR DESCRIPTION
**Pull request by nesisknesis**
# Github documenting your Pull Request
Puts the old cloak and Kor's new cloaks into a single set made by me

image

image
image
image
image
image
image
image

I think this breathes fresh new designs into the cloaks, problems with the originals (2011) we're that colours were quite dark and dull, especially in the captain's cloak. The new designs made by myself introduce hue-shifting which tends to make colours more appealing and fuller. Furthermore, some designs like the RD's I thought were pretty lacking so they went through a re-design. As for Kor's sprites, people were generally not enthused about them, so token details from them we're also added to the new ones. 

I have attempted to retain much design from the original cloaks and details from Kor's into what I think to be a modern version of cloaks. 

Cloaks also now aren't blocked by backpacks.

# Wiki Documentation

your wiki challenge

# Changelog

:cl:  Identification, Kor
imageadd: Unifies both the old cloaks and recently added new cloaks into a single set of cloaks.
tweak: Backpacks don't appear over the top of cloaks
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Color on the CE one is bad

**Comment by ToasterBiome** [comment]
The only thing I don't like about them is how you tweaked the colors for the cloaks 

Shouldn't a person that knows the fundamentals know that the colors look, as you say, "dogshit" on the heads because of subtle difference in clothing colors vs the cloaks? At least the 2011 are faithful to their colors.

Amazing spritework, you're a force to be reckoned with, I just think the colors can use some work. Never sat with me that they're sliiiiightly different to be noticable.

if these get merged i'd like to see the colors of the head clothes changed to match the new cloaks, at least. Great work.

**Comment by Reed0506** [comment]
while i really like the old 2011 cloaks, your new ones are very good and i would not be mad to see them permanently swapped to your designs. RD cloak feels a bit too purple to me but i guess thats just because the old one has so little.

**Comment by nesisknesis** [comment]
> 
> 
> The only thing I don't like about them is how you tweaked the colors for the cloaks
> 
> Shouldn't a person that knows the fundamentals know that the colors look, as you say, "dogshit" on the heads because of subtle difference in clothing colors vs the cloaks? At least the 2011 are faithful to their colors.
> 
> Amazing spritework, you're a force to be reckoned with, I just think the colors can use some work. Never sat with me that they're sliiiiightly different to be noticable.
> 
> if these get merged i'd like to see the colors of the head clothes changed to match the new cloaks, at least. Great work.

Yes you are correct, I am aware that there is a lot of clashing with colours, however, all colours used for my cloaks have been hue-shifted which I believe makes them more superior to the original colours used. I'll provide an example.

image


My process is to introduce these higher quality sprites so that they can be "leap-frogged" off of by other people to improve the other sprites that are used. IE. taking the palette from the cloak. With this though, it'll look dodgy in the early stages but hopefully later on things should start to become consistent while also higher quality; it's like a platform if you get my meaning. 

The captain cloak I think is a special case since I had updated some of the captain's clothing beforehand so the Captain's cloak likely looks more consistent than the original did.

As for updating the head's clothing, for it to fully take advantage of the palette, it may need a sprite update. though I may take it into consideration. Right now I like to focus on single projects, and that project is security currently

**Comment by ToasterBiome** [comment]
Well said, hopefully you get to the heads clothes soon. 👍

**Comment by adamsong** [comment]
They still look excessively baggy on the shoulders

**Comment by nesisknesis** [comment]
Sorry if I sound arrogant in the (pre-edited) description of this PR, i'm used to obstinent comments of keeping originals for keepsake and was also expecting 7 downvotes instead of 7 upvotes so i'm pretty surprised and uplifted that there is the polar opposite. in light of this, i'm pretty grateful, especially so since theres are many cases of outright rejection in other codebases

**Comment by JamieD1** [comment]
> Sorry if I sound arrogant in the (pre-edited) description of this PR, i'm used to obstinent comments of keeping originals for keepsake and was also expecting 7 downvotes instead of 7 upvotes so i'm pretty surprised and uplifted that there is the polar opposite. in light of this, i'm pretty grateful, especially so since theres are many cases of outright rejection in other codebases

See comments in discord

**Comment by Firewolf34** [comment]
> Sorry if I sound arrogant in the (pre-edited) description of this PR, i'm used to obstinent comments of keeping originals for keepsake and was also expecting 7 downvotes instead of 7 upvotes so i'm pretty surprised and uplifted that there is the polar opposite. in light of this, i'm pretty grateful, especially so since theres are many cases of outright rejection in other codebases

Yeah that phenomenon is so common with spritework changes unfortunately (regardless of game/codebase/whatever). excellent work on these :) now you just gotta do the rest of the game.

**Review by Partheo — APPROVED** [review]

**Comment by adamsong** [comment]
Reopen when the conflict is fixed

**Pull request merged**
