### PR TITLE
Touching the SM with telekinesis now makes you braindead and causes permanent trauma

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Touching the supermatter with telekinesis will now make you braindead on top of giving you permanent reality dissociation syndrome and a high chance of other random traumas instead of just deleting your brain. Because it's funnier if you aren't permanently removed from the round.

# Changelog

:cl:  
tweak: touching the SM with telekinesis now kills your brain instead of deleting it
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
What's the point of giving a trauma if you still insta kill the user

**Comment by iamthesilly** [comment]
> What's the point of giving a trauma if you still insta kill the user 

So when/if they get revived they aren't just going to be completely fine

**Comment by Hopekz** [comment]
> > What's the point of giving a trauma if you still insta kill the user 
> 
> So when/if they get revived they aren't just going to be completely fine

I might be misunderstanding then because I was under the impression that healing didn't work once you killed the brain

**Comment by iamthesilly** [comment]
> I might be misunderstanding then because I was under the impression that healing didn't work once you killed the brain

If someone's brain becomes non-functional you can revive them by doing brain surgery and then revival surgery, the brain will still be severely damaged but they won't be dead anymore.

**Comment by Moggram** [comment]
> > I might be misunderstanding then because I was under the impression that healing didn't work once you killed the brain
> 
> If someone's brain becomes non-functional you can revive them by doing brain surgery and then revival surgery, the brain will still be severely damaged but they won't be dead anymore.

Mannitol can be also used on the brain if you remove it.

**Comment by iamthesilly** [comment]
> Mannitol can be also used on the brain if you remove it.

I am aware, it's just bad practice to remove someone's brain unless you need to since it causes memory loss

**Review by JamieD1 — APPROVED** [review]
Hugbox

**Pull request merged**
