### PR TITLE
estinguished

### PR DESCRIPTION
**Pull request by Sniblet**
# Document the changes in your pull request

# Changelog

:cl:  
spellcheck: extinguished
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
I don't know what's happening on the bottom line, if it's an issue tell me what to fix

**Comment by Hopekz** [comment]
Changelogs are for relevant player facing changes

**Comment by Sniblet** [comment]
Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.

**Comment by Hopekz** [comment]
> Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.

All right. if this goes through I guess I'll just be making minor spell check PRs so I can spam the changelog too

**Review by ToasterBiome — APPROVED** [review]

**Comment by MajManatee** [comment]
un-edit the changelog because it was funnier

**Comment by Sniblet** [comment]
the changelog was never edited

**Pull request merged**
