### PR TITLE
Edits the stechkin grip by 1 pixel

### PR DESCRIPTION
**Pull request by nesisknesis**
# Document the changes in your pull request

I shifted the grip up by 1 pixel, shortening it so it is more anatomically sound.

# Why is this good for the game?
Looks more nice.

# Testing
I did not test this I just went into the dmi and used the heretical dreammaker sprite editor.

# Spriting
image

# Wiki Documentation
Upload the neu sprite.
# Changelog

:cl:  Identification
imageadd: Stechkin grip edited by 1 pixel to look more anatomically correct.
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
That's what I use to make all my sprites

**Comment by azzzertyy** [comment]
such a small and simple change yet it looks leagues better

**Comment by nesisknesis** [comment]
> such a small and simple change yet it looks leagues better

Ezqjf2vXEAAbRv_

**Review by cuackles — APPROVED** [review]

**Comment by Moltijoe** [comment]
rip, the sole was stored in that pixel

**Pull request merged**
