### PR TITLE
Implements the "L-word Pass"

### PR DESCRIPTION
**Pull request by Altoids1**
image

Darkstick actually liked the idea so I'm going with it.

#### Changelog
:cl:  Altoids
rscadd: It is now possible to receive an "L-Word Pass," which allows one and only one chance at saying the L-word, per card.
/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Why isn't this a traitor item

**Comment by Codeatmos** [comment]
Who shall distribute the "L-word Pass", or will syndicate high-command have a limited supply?

**Comment by MegaEmpirical** [comment]
Clearly this is the Clerks job.

**Comment by HomocidlePancakes** [comment]
I was actually going to gamble for an L-word pass the next BR by putting a month long ban at stakes, but there hasn’t been a single BR round.

**Comment by Partheo** [comment]
This is hilarious

**Comment by Nickvr628** [comment]
so sad

**Pull request closed without merging**
