### PR TITLE
Backports several SSlighting improvements: overlay lighting

### PR DESCRIPTION
**Pull request by ThatLing**
# Document the changes in your pull request

This ports a few lighting improvements, the most exciting one is overlay lighting.

image

This should be test-merged for some time, likely some stuff related to slings will break

List of ported PRs, credits to the original authors:
- https://github.com/tgstation/tgstation/pull/43816
- https://github.com/tgstation/tgstation/pull/52413
- https://github.com/tgstation/tgstation/pull/59002

# Changelog

:cl: Rohesie
rscadd: Dynamic lights move smoother now
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
Have you tested how this looks on the replay viewer?

**Comment by ThatLing** [comment]
Nope, I don't use replays

**Comment by monster860** [comment]
Try it, go to https://replays.yogstation.net/ and hit choose file and navigate to the logs of your local testing and see what it gives you.

**Comment by ThatLing** [comment]
The overlay isn't shown in the replay, any way to make it work?

**Comment by ToasterBiome** [comment]
I'm gonna be completely honest, I don't see a difference. Comparison screenies?

**Comment by Moltijoe** [comment]
very nice in practice

**Pull request merged**
