### PR TITLE
Ports The Sky Noose From Hippie!

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 fluffe9911 for porting tortellinitony for making
rscadd: Adds a sky noose for when you want to go out in midly morbid style!
/🆑

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Is it a suicide only thing or can I execute people via hanging?

**Comment by Amelia0010** [comment]
why?

**Comment by fluffe9911** [comment]
A person on discord said they wanted the noose so im like why not and its suicide and execution

**Comment by fluffe9911** [comment]
fair enough

**Pull request closed without merging**
