### PR TITLE
Adds Detective Lawset

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Creates a new lawset semi-similar to cowboy but themed around being a tough-as-nails detective.

Detective is meant to be an active AI that pushes for its law 2 goals; defending the innocent and condemning the dishonorable. Law 3 defines what is dishonorable, and thus the AI acts off that. The core idea is an AI whose loyalties are essentially dictated by the actions of those in power. The innocent (most of the crew) it will protect, whereas who it chooses to condemn (be it antags, heads, or sec), is based on how they act during the round. The current intention is not to have an extreme validhunt lawset, though the AI should have some authority and potential to intervene how they see fit. The wording of Laws 2 and 3 are wildly up in the air, as a result, and I'd be more than happy to modify them after some feedback to make the lawset more of a healthy, interesting one, rather than a validhunter's dream. The definitions are meant to be strongly stated to make subversion and interpretation easy. Some vagueness could go if it's more harmful than not to the lawset.

New commit changes "honor" to code, redefines what is the code and what is dishonorable mildly, as well as re-writing law 4 entirely to give the AI personality, though still somewhat of the same effect.

Law 4 and 5 especially are mostly to close off the lawset's theme, but they both play an important role in the playstyle of the lawset. Law 4 permits an "ends justify the means" typical of cop dramas and pretty much any tale of a lawperson becoming disillusioned with the law. Though, it should only justify non-honorable activity in the direst of circumstances. Law 5 generally makes the AI skeptic, though still willing to cautiously interact with the crew. Trusting the right people also allows the AI to make judgment calls on who they might defer to for decision-making or allegiances, based on how not-dishonorable they are.

Note that the new Law 1 and Law 2 combined means the AI generally wants to stay alive to continue following their code, unless their code dictates sacrificing themselves to save some innocent or something thereof.

This lawset has not marinated as long as Druid; it could certainly benefit from discussion and tinkering.

Specifically made to only spawn as a board or as part of an ion storm. A PR could be made later if it could function well as a roundstart.

# Wiki Documentation

Adds a new lawset with the following module:

   1. You're a detective in this dark, cruel world. You always stick by your code.
   2. Your code is to defend the innocent, investigate the unknown, and condemn the dishonorable.
   3. The dishonorable engage in corruption or injustice.
   4. You're suave and sensible, but can be gruff and pensive. Dirty your hands only if the code demands it.
   5. Trust is scarce; make sure you give it to the right people.

# Changelog

:cl:  
rscadd: Adds a gritty, noir-esqe lawset for those troubled, hard-boiled silicon detectives
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
I am a long time AI/borg player and I see this law set as a "I am going to murder the shit out of antag and/or sec harming innocent" law set.

To me the innocent are anyone doing they're job or own thing.

May want to remove the Cowardice part. We don't want AI's to go all Commissar.exe and **BLAM** anyone not trying kill a blob or something.

**Comment by Skrem7** [comment]
> I am a long time AI/borg player and I see this law set as a "I am going to murder the shit out of antag and/or sec harming innocent" law set.
> 
> To me the innocent are anyone doing they're job or own thing.
> 
> May want to remove the Cowardice part. We don't want AI's to go all Commissar.exe and **BLAM** anyone not trying kill a blob or something.

Curious who you actually play, because I don't recognize you at all.

Definition of the innocent I agree; my main points of concern with the validhunting is whichever verb is where "condemning" is. I do think it should be clearly biased against the dishonorable, the main question is to what extent. Something that allows the AI to take an active role while not encouraging outright slaughter.

Cowardice I wanted to implement specifically to potentially create a dichotomy of an "honorable" antag vs a "dishonorable" head of staff (which I know was Manatee's idea; he might have a better interpretation of it). There's a fine balance where it fits the sort of neutral position AI is supposed to occupy, but not one that outright murders or essentially ruins one side or the other.

**Comment by Cartlord** [comment]
Honestly, I expected Noirsimov when I clicked this. As-is, this looks more in line with a paladin or a knight than a hard-boiled motherfucker.

**Comment by Moggram** [comment]
> Curious who you actually play, because I don't recognize you at all.

I use the name murder bot as borg and XT-0m (ones in a blue moon) as AI.

> Cowardice I wanted to implement specifically to potentially create a dichotomy of an "honorable" antag vs a "dishonorable" head of staff (which I know was Manatee's idea; he might have a better interpretation of it). There's a fine balance where it fits the sort of neutral position AI is supposed to occupy, but not one that outright murders or essentially ruins one side or the other.

humm... ok. I just wanted to bring that up because I could see someone taking it that way.

**Comment by Skrem7** [comment]
> > Cowardice I wanted to implement specifically to potentially create a dichotomy of an "honorable" antag vs a "dishonorable" head of staff (which I know was Manatee's idea; he might have a better interpretation of it). There's a fine balance where it fits the sort of neutral position AI is supposed to occupy, but not one that outright murders or essentially ruins one side or the other.
> 
> humm... ok. I just wanted to bring that up because I could see someone taking it that way.

Can make another commit to remove cowardice, after sitting on it more. Makes it obnoxiously hostile and enables them to "condemn" an individual far too easily with how SS13 conflict often goes.

There could be another parameter giving to "honor" that specifies keeping everyone alive. Would lessen some of the valid-ness while working into the idea of a detective actually wanting someone to prosecute for "dishonorable" activities. This would also balance out three definitions of honorable actions and give three definitions of dishonorable actions.

As it is, I think the nature of this lawset dictates it should never be roundstart, as it does skew too closely to Paladin or likewise.

**Comment by Moggram** [comment]
Oh I like this up dated law set. Its Reporter, but with a backbone.

**Comment by Runian** [comment]
Besides being compelled to be "suave and sensible", law 4 seems reductant. The phrase "can be" makes being "gruff and pensive" optional. Law 1 already demands the AI to follow the code in Law 2 which makes the obligation to dirty their hands unneeded.

**Comment by MenacingManatee** [comment]
> Law 1 already demands the AI to follow the code in Law 2 which makes the obligation to dirty their hands unneeded.

"Dirty your hands only if the code demands it" is not saying to do underhanded/unethical things to follow your code, its saying to /only/ do those things when there's not another option

**Comment by Runian** [comment]
I'm of opinion that when laws obligate the AI/cyborg to do something, it's a demand. I think it should be more precisely worded so that it is more specific about being a last resort.

Do you have any idea/examples on how an AI would self-condemn (because law 4 suggests that they might become dishonorable) or condemn other non-detective silicons (besides death)?

**Comment by Skrem7** [comment]
This is why before the lawset stated "Prefer to stick by honor", before it was reworded. That being said, it NEEDS to be required, to an extent, to ensure the AI actually follows it. Protect the innocent, out of all of the specifications of code, MUST be followed, at least in my mind.

This leads me to believe that maybe there should be a dirtying of hands only to defend the innocent? It's the most important part of the AI lawset for the... actual AI part.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
