### PR TITLE
[admin] Adds spam prevention to clients

### PR DESCRIPTION
**Pull request by AsV9**
tgstation/tgstation#45353

### CODE REVIEW

**Comment by Bibby0110** [comment]
ok

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Use timers instead of dumb tick counters

**Comment by Bibby0110** [comment]
tell that to T G S T A T I O N

**Comment by optimumtact** [comment]
@alexkar598 
\>entire datum and subsystem that may slow tick due to byond overtime
\> two vars on client that can never overtick

bro that better be a joke

**Pull request merged**
