### PR TITLE
Replace X-01 Multiphase (hos gun) ion with incapacitate (knockdown) bolt

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

EMPs are too widespread, this is more interesting

# Wiki Documentation

2 seconds of knockdown on hit, "short" range like taser bolt

# Changelog

:cl:  
tweak: Replaced the HoS X-01 Multiphase gun's ion mode with incapacitate (knockdown) mode
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
"EMPs are too widespread, this is more interesting" - 
typing

**Comment by Therandomhoboo** [comment]
I don't get why knockdown is getting all this love. What did it even do to deserve this?

**Comment by Moltijoe** [comment]
> I don't get why knockdown is getting all this love. What did it even do to deserve this?

Because its "hard" CC that still allows for some ammount of resistance

**Comment by 00ze-cyclone** [comment]
Knockdown is obnoxious, we replace stuns by knockdowns because that’s an improvement but that’s not a reason to add that shit.
Now HoS just approach you, hit you once and you need to recover your weapon from the ground and get slowed massively for 2 seconds which enough to time to unload 3 (4 if you are really fast) disabler beams in the poor fuck that got hit. And even then you can just knockdown again to finish someone off.
At least EMP just murder silicons and IPCs (both of which deserve nothing).

Also sec only has the ion rifle and HoS gun for EMPs, only if R&D is feeling fancy can they print an ion weapon.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
oh cool i was wondering when we were bringing the taser mode back

**Comment by TheRyeGuyWhoWillNowDie** [comment]
also this is obviously getting merged because:
1. ynot is on the balance council
2. this is sec powercreep

but the ion bolt mode is useful, so it's a little disheartening to see that playing smart (frying energy weapons by quickly switching to EMP mode, not something you can really do anymore after ynot's other latest sec powercreep though, i suppose) is being phased out and replaced with shoot once to win

**Comment by LazennG** [comment]
> ynot is on the balance council

he's getting ratio'd there too

**Comment by Moltijoe** [comment]
Balance council: ion mode sucks ass, but knockdown is even worse

**Comment by Necrosium** [comment]
Knockdown sucks a hell lot more than my combat skills, and it's already a very low bar

**Pull request closed without merging**
