### PR TITLE
Fixes deltas airlocks access in engineering

### LINKED ISSUE #5649: Engineers lack access to gravity on Delta
Unsure if this is intended.

### PR DESCRIPTION
**Pull request by Lostlarry**
fixes #5649
On delta only:
grav gen is now accsessible to engineers
atmos is now not accesible to engineers
engineers can still access the SM trough the maintnance

:cl: 
bugfix: Engineers now can access gravity generator on delta
tweak: Engineers now cant access atmos on delta
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
I'm pretty sure these are supposed to be inaccesible by engineers.

**Comment by Lostlarry** [comment]
i dont think you should need tcomms machinery access to get to grav gen
also im just mimicking the box when it comes to grav gen

**Comment by MegaEmpirical** [comment]
DO NOT REMOVE ATMOS ACCESS From ENGINEERS.

**Comment by MegaEmpirical** [comment]
As for gravity, engineers have access on box and I think most if not all other stations so this seemed weird for them to not have it here.

**Comment by MegaEmpirical** [comment]
Are you completely removing engi atmos access or do they have some other way in? Or based on low pop?

**Comment by Lostlarry** [comment]
i am making atmos doors only accsesible to personel with atmos access the SM is still accessible trough maint with the engine access the engi have

**Comment by MegaEmpirical** [comment]
As long as they can still access the needed associated rooms with the SM sure.

**Pull request merged**
