### PR TITLE
updates the free miner ship heavily because i can

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Entirely rebuilds the Free Miner Ship.
As with the Syndicate Lavaland PR, **please use MDB for pictures.** I really can't be assed to update them every time.

survival pod walls moment

# Changelog

:cl:  
rscadd: The Free Miner Ship has been heavily updated.
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
please add screenshots, it’s very hard to actually tell if a map looks good or not judging from mdb 

with that being said I like the other one better. this one doesn’t really fit the flavor text imo

**Comment by N3D6** [comment]
free miners also aren’t supposed to have a full r&d setup roundstart, building the orm on your own and saving up the points to buy your r&d equipment is like the whole purpose of progressing as a free miner

**Comment by Addust** [comment]
last redesign had most of RnD pre-setup, let me quickly read up on the flavour text and make the ship feel grittier

**Comment by Marmio64** [comment]
why does this even need to be changed? There is no rationale put here, this is literally just being changed 'because you can', in your own words.

**Comment by Hislyna** [comment]
Didn't it only just get updated? Seems like a slap in the face for whoever did that

**Comment by Addust** [comment]
i see your point i will find something else to remap (and maybe do this in like 3 years)

**Pull request closed without merging**
