### PR TITLE
Reverts Nickvr's xenobio changes

### PR DESCRIPTION
**Pull request by alexkar598**
#Intent of your Pull Request

Reverts the Nickvr PR that made slimes spawn on lavaland and nerfed the mutation rate on the station slimes

#Why 
Nick's change didn't fix any of the issues with xenobio, just swept them under the rug by making xenobio plain unfun to play as. Also fuck you nick for deleting your github account and all your PRs

#### Changelog

:cl: 
rscdel: Slimes no longer spawn on lavaland and they mutate normally
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
personally as a miner having slimes on lavaland gives me extra challenge and something else to do when bored

xenobio sympathizer

**Comment by Ratvar** [comment]
So you want to make xenobio issues common by taking all the trash from under the rug, it seems, making game worse for almost everyone.

**Comment by maxion12345** [comment]
I actually enjoy the changes, having to work with miners and selectively breeding your slimes instead of the good ole "suck up all slimes but one then feed and repeat until you get desired slime". I think it's as best as it'll be until something new is added, and that going back to the way it was is a step in the wrong direction.

**Comment by alexkar598** [comment]
Its a fact that in most rounds, xenobio isnt even TOUCHED as its just painful and annoying to do

**Comment by alexkar598** [comment]
I took the time to do statistics, starting from round ID 27 038 to round ID 30 939 for a total of 3 901 rounds, counting rounds where xenobiology has been used(this statistic being counted as a round where more than 20 slime cores have been used). Its been used 1 270 rounds out of 3 901 rounds, which is only 33% of rounds which is very little when compared to something like chemistry which based on rounds where more than 500 units have been mixed amounts to 3 057 rounds which is 78%.

This clearly shows that xenobiology is plain unfun to play as because of the stupid restriction where you cant do your job at all unless someone else does 70% of the work for you since mutating them just won't happen

start: 27 038
end: 30 939
total: 3 901
xeno: 1 270 (33%)
chemistry: 3 057(78%)

**Comment by Ratvar** [comment]
Xenobio is plain unfun to have in working state for people not sitting AFK in xenobio for 2 hours. Golems validhunting and griefing, spiders validhunting and griefing, healing,  tepelortation-immortality of slimepeople bodyswap, op armor, speed related extracts. There is nothing worth salvaging but gameplay loop itself, but everyone is in gameplay loop to get gaming loot and complains loudly when you remove xenoling or hyperstun timestops for a reason you probably can deduce. 
It might be worth to remove nickvr changes to encourage people to code a replacement for its horrors faster - which does not work if people who like xenobio are satisfied with worst excesses of xenobio, playing because of said shit, and almost nobody else is invested in xenobio to code for it - can look at how crossbreeds, rework aka adding more powergaming loot fnr, made xenobio so much worse to bear, by making it fun and not stale as well, like this PR will.

**Comment by Tipy1802** [comment]
Finally! Xenobio was pretty much unplayable since you couldn’t do much to progress other than wait for miners to carry you.

I do understand that people seem to really hate xenobiology for being op but there are other ways to balance it out other than make it unplayable.

Honestly the whole science department needs a rework, most positions are boring or server little to no purpose. RnD is just clicking stuff on the console upgrading all machines once and your job is done. Toxins exist to only boost RnD and xenobiology got hit so hard it’s unplayable. 

This PR solves one of those problems, on an unrelated note I think removing techfabs and have science print everything would give RnD a function (to develop equipment). I do understand that’s how it used to work but got changed because of scientist traitor printing guns but that can be easily solved by either removing the ability of the emag to hack firing pins or by keeping only the security techfab

**Comment by Tipy1802** [comment]
Also there are a shit ton of other powergaming departments.
Miners with their powergaming loot
Cargo technicians who have no other purpose than to powergame 
Botany with too many things to count

**Comment by Ratvar** [comment]
Xenobio players had a lot of time to balance their own department. Instead praise crossbreeds and cry about magicarp because they are not here for balance, never were. You are free to PR a rebalance yourself, or make a bounty, or something, but so far nobody took that step.

Miners are at least stuck on other zlevel, have a lot of powergaming loot to collect and so rarely return, sometimes die, use validhunting toys on npc mobs most of the time and are actually tricked into benefittng station with resources - had to make these autoshare because nor miners nor R&D shared their gun printer paste with other departments. And they also roll for loot, so they do not always get best shit. Xenobio is hyper safe due to walls and beind hidden from public hallways, all item targets are guaranteed, so there is no difference in endgame.
Cargo technicians and botanists are near public hallways. People come to them, ask for shit and sometimes get things - they have better map that encourages cooperation with other players, and mechanics like bounties, station projects or getting R&D parts that encourage them to walk out of department and again cooperate with people. Xenobio has reinforced walls, so nobody dares take your shit, is hidden deep in R&D, so nobody dares see or ask for shit, and only thing they need are machine parts and sometimes console, which they research these themselves and then fuck off for the rest of shift.
And then xenobio shit is more op then shit of all three departments brought together, consistently. It is worse from all sides, and even then miners, cargo, botany and friends probably need a lot of changes as well - whataboutism is not a reason to do nothing.

**Comment by Tipy1802** [comment]
Xenobiology does has to work with the rest of the station to share it’s cores. There is no point in keeping them to yourself since all you have accomplished this way is waste your time.

Xenobiology is so secured because of all the dangerous life forms it (can) contains which would be hell if they break free.

Xenobiology can gives its product to RnD who man the front desk and handle requests. On top of that if you want something from xenobiology you can just PDA the xenobiologist or ask the RnD guy

I do agree that xenobiology has some powerful and op stuff but making the whole job unplayable is not how you should solve such problems

**Comment by alexkar598** [comment]
I'm not saying xeno is all fine and dandy but that's like removing cult until it can be fixed, it's never going to happen. We cant just gut out chunks of gameplay like that

**Comment by Ratvar** [comment]
I would rather compare it to nerfing cult massively instead of removing it. Still leaves players to check out a thing and get unsatisfied, maybe enouraging them to better it instead of unnerfing it fnr - Jcat is trying to change gameplay loop, for example, making it harder compared to what this PR will do, and spooder on discord expressed wish to remap it near hallways. It is working very slowly.
Tipy1803, here is a point in keeping all cores to yourself - you get powergaming loot you might be using, since you are not making anything but powergaming loot and since nobody but people familiar with xenobio ask for it, and only xenobio players are familiar with it in good detail. And xenobio players are not shy of wasting time doing nothing, this is the entire gameplay of the job, after all.

**Comment by patpol4** [comment]
Honestly i would keep the fultons and beacons and remove just the useless slime cages, xenobio is not for slimes only, what if miners want to send some other lavaland creatures over for study etc.

**Comment by MonsWTF** [comment]
Fine with most of this since the only major nerf that Nick kicked into Xenobio was the reduction in Mutation %. There's an argument to be had for leaving the code for the Xenobio cages in the game, as they could potentially be repurposed for other Lavaland creatures later on down the line that need to be sent up to Science for further examination. 

Roundstart, 30% was what Xenobios used to have, but it really isn't necessary for skilled Xenobiologists to make progress thru the slime color varieties. Compared to 5%, even 15-20% should help open up the department for newer Xenobio's to learn the job without being pigeon-holed into spending 8-16 minutes just trying to get your first new slime color. 15-20% should on average reduce that timer to about 4-12, giving the newer Xenobio a good likelihood of their first slime split producing a color.

It's amazing how much we hear the argument of "Let's just nerf something now, and then force other people to code the fix for us." If you really don't like the gameplay mechanics of something in the game so much, and are willing to invest the time to tell others to remove features, why not just help with building/coding the new mechanic yourself? Considering some players on the discord have constantly proposed that Xenobio not be based on slimes, why hasn't there been any PR for this new version of Xenobio yet? Or any tangible design documents? Are we just going to follow TG's lead in removing content, purely because we don't like how it works?

Whether you like Xenobio, or hate Xenbio, or are indifferent to Xenobio, it's so easy to narrowly focus on the one job itself and consider it the problem, without realizing the same statements don't apply or line up to other aspects of the game and how they are handled.

**Comment by Ratvar** [comment]
"If Xenobio is bad and **I** like Xenobio, why do **you** not make it better, huh."  Because you like xenobio, probably, and it should be your job to make it great, which xenobio players failed at for years. There has not been many design documents and PRs to make it better because majority of xenobio players are content with it being shit, and those who want change do not have time or talent to do so.  
TG xenobio policy is adding powergaming content and calling it a rework, aka crossbreeds, not removing it. All it did is give xenobio timestops and super armor.
"Whether you like Xenobio, or hate Xenbio, or are indifferent to Xenobio, it's so easy to narrowly focus on the one job itself and consider it the problem, without realizing the same statements don't apply or line up to other aspects of the game and how they are handled." - Could you expand on that, is that another what-about-job-Xism, where you point out that xenobio is not the only issue plaguing this game.

**Comment by MonsWTF** [comment]
It's an absolutely unreasonable standard to expect everyone playing SS13 that enjoys playing to be able to code changes as well. I'm not sure if I need to expand on that opinion, I really don't think I should have to.

TG has denied or had to suspend any and every crossbreeding update for the last year or so from Fel and other coders who've tried to finish the rest of the crossbreeding effects list. Crossbreeding itself has literally been incomplete ever since the feature itself was added because of how complex the actual combinations are to code. What's more surprising is the fact they haven't removed it yet w/ how much Oranges dislikes its existence every single time a Xenobio PR comes up, Cobble included. So yes; nerfing/removing Xenobio would be following TG's stance.

Sure, to expand on that, context is relevant. Yes it is in part what about-ism. It's also double standards by holding something to a higher pedestal, and not holding that same stance/decision to other parts of the game. If we follow that train of logic, then we're going to go on a **Race to the Bottom** in nerfing gameplay mechanic after gameplay mechanic.

I've given my opinions and ideas about how Xenobio could be improved and where the underlying core concept of the job itself should be improved, and that's been about the extent on my end. I would love to be as competent as Fel in being able to code the rest of the content of Xenobio or to see all of those changes through, but I'm not.

**Comment by Marmio64** [comment]
i do kind of like the whole idea of making isolated jobs like xenobio require some assistance from others and i think that xenobio changes should stay, but perhaps give chemistry the ability to make a weak chemical that can boost slime mutations a bit when applied to them. It would make xenobio less of a pain while still not removing the cooperativeness xenobio can require. Could also add a new plant that when fed to slimes increases mutation rates, and possibly even a drink/food the bartender/chef could make to increase mutation rates.

**Review by Partheo — APPROVED** [review]

**Comment by alexkar598** [comment]
Theres a big difference between needing assistance to do part of a job like botany needing chemistry for fancy plants vs something like botany needing chemistry to make nutrients for plants

**Comment by maxion12345** [comment]
>xenobio is powergamey
>nerf
>it's not fun.
>unnerf
>cycle repeats

**Comment by Marmio64** [comment]
okay but, you don't need mining to do your job, its just a lot slower and more painful without it.

edit: you also dont NEED nutrient bottles at all for botany since you can compost plants and get enough nutrients from them to be able to run botany without nutrient bottles.

**Comment by Moja10** [comment]
I think Nicks solution failed and should be reverted until a proper solution can be made, his PR was shit in hindsight and shit changes shouldn't just be left in just because the outcome is slightly favorable.

**Comment by Featherfield** [comment]
Nick can eat dick good PR

**Comment by MonsWTF** [comment]
> I think Nicks solution failed and should be reverted until a proper solution can be made, his PR was shit in hindsight and shit changes shouldn't just be left in just because the outcome is slightly favorable.

Keeping the Xenobio cage + beacon code might be worthwhile, as the cages themselves may have use down the line for future Xenobiology/Science-Mining interaction PRs. @alexkar598 Thoughts?

**Comment by ghost** [comment]
I'll just remove crossbreeds instead. They're what broke it, honestly. I removed the instant heal an methspeed a while ago-but it can honestly be removed with no issue.

**Comment by Ratvar** [comment]
Then you will have xenobio doing golems and spiders. It has no redeeming quality, adam

**Review by patpol4 — APPROVED** [review]
I like how you just removed a random o2 locker on pubby. **Maps are technically fine** but i would still prefer if we kept the fultons and beacons for transportation of other creatures and materials then slimes. Mining and sci is supposed to cooperate after all.

**Comment by alexkar598** [comment]
Self merge bad hurr durr, yeah yeah, its 3 to 1 like to dislike ratio and im not going to support gutting entire sections of gameplay because it needs a rework

**Comment by jcatjmeow** [comment]
> We cant just gut out chunks of gameplay like that

why not

**Pull request merged**
