### PR TITLE
Revert "[admin] fixes fire dmg on vv"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#14750
I have better solution (uses defines instead of plaintext)

### CODE REVIEW

**Comment by Xantam-13** [comment]
What is the better solution..?

**Comment by Bibby0110** [comment]
> What is the better solution..?

i will show you

**Comment by Bibby0110** [comment]
> > What is the better solution..?
> 
> i will show you

later

**Comment by ynot01** [comment]
PR your change when it is made, do not revert a fix that made something non-functional into functional

i had to aheal someone the other day because this shit didn't work

deal with the one line merge conflict it's not hard

**Comment by JamieD1** [comment]
> > > What is the better solution..?
> > 
> > 
> > i will show you
> 
> later

Just fix it in your PR

**Comment by ynot01** [comment]
img oing kill

**Comment by Xantam-13** [comment]
Add detail to your PR or leave it closed.

**Comment by JamieD1** [comment]
Add the change in a new pr.

**Pull request closed without merging**
