### PR TITLE
Hulk code cleanup + daniel hilton bugfix

### PR DESCRIPTION
**Pull request by Moltijoe**
Deletes all the other versions of hulk from the code since theres no reason to have 3 completely different mutations that are basically identical, if we want the mutation to work differently, we modify the mutation we have

also fixes more bugs with genetics duplication

:cl:  
bugfix: No more infinitely duplicating hulk DAN
tweak: Hulk now occasionally says the brain damage hulk lines
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
DAMN

**Comment by ofscarletdreams** [comment]
we fixed daniel hillton hes gone now we patched him

**Comment by Therandomhoboo** [comment]
lookey fooken here 
image_2023-11-30_205110747

**Comment by Yarinoi** [comment]
thank you molti
although i think another good change to hulk would be blacklisting daniel hilton from ever being able to use the gene

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
