### PR TITLE
lets IPCs be CE and RD

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Lets IPCs be CE and RD

# Changelog

:cl:  
rscadd: IPCs can be CE and RD
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
doesn't seem thematic for a completely inorganic thing to work as the head of medical, which is all about treating organic stuff. RD and CE make sense, not CMO.

**Comment by iamthesilly** [comment]
> doesn't seem thematic for a completely inorganic thing to work as the head of medical, which is all about treating organic stuff. RD and CE make sense, not CMO.

humans can be roboticists, so IPCs should be able to be doctors

**Comment by Marmio64** [comment]
> > doesn't seem thematic for a completely inorganic thing to work as the head of medical, which is all about treating organic stuff. RD and CE make sense, not CMO.
> 
> humans can be roboticists, so IPCs should be able to be doctors

except we're talking the head of a department, not just normal jobs. In addition, there is a racial bias towards humans so they can do whatever they want, and also RD is about more than just robotics as well.

**Comment by iamthesilly** [comment]
> except we're talking the head of a department, not just normal jobs. In addition, there is a racial bias towards humans so they can do whatever they want, and also RD is about more than just robotics as well.

lizards can be CMO and there is a good deal of racial bias against them, and there's nothing stopping a synthetic being from learning how to be a doctor and being good enough to be in charge of the department

**Comment by Moltijoe** [comment]
> humans can be roboticists, so IPCs should be able to be doctors

IPC can be MD, that is the equivalent to roboticists, not CMO

I personally don't care for species locking head positions, but many do

**Comment by Potototatoh** [comment]
> 
> except we're talking the head of a department, not just normal jobs. In addition, there is a racial bias towards humans so they can do whatever they want, and also RD is about more than just robotics as well.

the next step is to add gender bias

**Comment by iamthesilly** [comment]
> the next step is to add gender bias

if anyone adds this i will cry

**Comment by Marmio64** [comment]
in keeping with other nonhumans only having 2 headroles they get, i would still argue for CMO to be removed, if nothing else.

**Comment by Moltijoe** [comment]
> if anyone adds this i will cry

only women can be head of staff

**Comment by iamthesilly** [comment]
alright it's just CE and RD now

**Comment by ynot01** [comment]
bozo pr, why are we letting silicons be heads

**Comment by SapphicOverload** [comment]
> bozo

?

**Comment by iamthesilly** [comment]
> bozo pr, why are we letting silicons be heads

Haha chief engineer IPC go brrrrrrr

**Comment by Moltijoe** [comment]
> bozo pr, why are we letting silicons be heads

um ackshually they're carbons in the code

**Comment by KillerOrcaCora** [comment]
Head or not your race will rot

**Comment by iamthesilly** [comment]
> Head or not your race will rot

meme-who-asked

**Comment by Moja10** [comment]
here's the real question, would you really want an IPC captain, if there's only one head and it's an IPC?

**Comment by Simplehorror** [comment]
i thought non-humans werent allowed to be acting cpatain

**Comment by Simplehorror** [comment]
> > except we're talking the head of a department, not just normal jobs. In addition, there is a racial bias towards humans so they can do whatever they want, and also RD is about more than just robotics as well.
> 
> the next step is to add gender bias

good idea

**Comment by CMOisLing** [comment]
I want to go back to the good old days of absolute no compromise racism. Not this soft hugbox milennial racism.

**Comment by JamieD1** [comment]
Here we go again. @Anvilman6

**Comment by Anvilman6** [comment]
> Here we go again. @Anvilman6

I wasn't all that involved in the development of IPCs / their lore, but seeing as this keeps to the 2 jobs standard that was established prior, I don't have any objections to it in that regard.
CE/RD seem suitable because they're robots somewhat like Preternis, though that falls to discretion / collaboration with the Lore side of things.

**Comment by Skrem7** [comment]
> I wasn't all that involved in the development of IPCs / their lore, but seeing as this keeps to the 2 jobs standard that was established prior, I don't have any objections to it in that regard. CE/RD seem suitable because they're robots somewhat like Preternis, though that falls to discretion / collaboration with the Lore side of things.

Hi hello I finally got around to commenting on this.

CE/RD is fine, I personally think CE/CMO is a better fit and would be more behind that AND it would be more unique, but either is okay.

**Comment by iamthesilly** [comment]
> CE/RD is fine, I personally think CE/CMO is a better fit and would be more behind that AND it would be more unique, but either is okay.

It was originally all 3, do you think that would be okay?

**Comment by Skrem7** [comment]
> It was originally all 3, do you think that would be okay?

short answer no, long answer it would be but dealing with this subject is so unfortunately politik so i would personally make them able to be two real heads rather than a head and a half

**Review by JamieD1 — APPROVED** [review]
Wiki and lore have spoken

**Pull request merged**
