### PR TITLE
allows you to wear mop on back

### PR DESCRIPTION
**Pull request by boodaliboo**
lyis wanted this
#### Changelog

:cl:  
tweak: allows you to wear mop on back <@123171845707923456>
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
can someone redo travis

**Comment by Hopekz** [comment]
No back sprite?

**Comment by boodaliboo** [comment]
no sorry

**Comment by Marmio64** [comment]
janitor powercreep

**Comment by Hopekz** [comment]
Not sure if I like this without a back sprite. Most things in the game that can be worn on the back have a back sprite. I can't even think of an item at the moment that doesn't have one

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
I want back sprite.

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Sprite it or close it

**Pull request closed without merging**
