### PR TITLE
Ports cogger weapons from bee

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Source - https://github.com/BeeStation/BeeStation-Hornet/pull/2124

Brass swords -  a cogger sword, that makes EMP's on hit(with a cooldown).
Brass battlehammer -  a clockwork battlehammer, that punches targets away on hit.

Also this PR makes clockwork bows actually obtainable, and nerfs their arrows to 16 damage. 20 damage for a self-recharging bow that takes 1.5 seconds to recharge a projective is kinda many.

# Spriting

image
image

# Wiki Documentation

Write about it on wiki

# Changelog

:cl:  PowerfulBacon, ported by SuperSlayer
rscadd: Added a brass battlehammer
rscadd: Added a brass sword
tweak: Nerfed clockwork arrows
tweak: Clockwork bow is now obtainable
tweak: Clockwork Armaments now can summon more various weapons
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
the clockwork bows are already attainable by inciting a scripture that isn't clockwork armaments. I'd suggest removing their seperate scripture and returning the arrow damage back to 20 or maybe 18 so that you have to specialize into the ranged attack, but still keeping it a good alternative

**Comment by ghost** [comment]
> the clockwork bows are already attainable by inciting a scripture that isn't clockwork armaments. I'd suggest removing their seperate scripture and returning the arrow damage back to 20 or maybe 18 so that you have to specialize into the ranged attack, but still keeping it a good alternative

They are already moved into clockwork armaments, and i can maybe up their damage to 15-16, but 20 is kinda too many for an easy obtainable ranged self recharging weapon

**Comment by ShadowDeath6** [comment]
The sword applying an EMP on hit is awesome. I'd honestly say that you should make it apply emp_heavy when hitting a mech, just because mechs are extremely unfun to deal with as clock cult.

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
@KillerOrcaCora

**Review by KillerOrcaCora — APPROVED** [review]
Sprites are fine

**Comment by ghost** [comment]
Coggers

**Pull request merged**
