### PR TITLE
Applies pretty filter and OOC toggle to discord OOC channel

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

You shouldn't be able to bypass global OOC toggles or the pretty filter with disocrd

# Changelog

:cl:  
rscadd: Applied the pretty filter and OOC toggle to discord OOC
/:cl:

### CODE REVIEW

**Comment by Bluedazzled** [comment]
but... but my ඞ!

**Comment by Firewolf34** [comment]
THANK GOD. _ANOTHER HAND TOUCHES THE BEACON_

I worked on muting Discord-OOC with Altoids (@Altoids1 ?) back when he was Maintainer - but we never published it because there was no easy way to only mute non-Admin Discord chats using the toggle. 

Something to consider for your PR. Admin Discord messages and such from Discord were requested to us to _not_ be muted back then regardless of player preference. I don't know if that's still the case but that's why this was not done earlier. Interacting with the Discord API/bot/thing to include Discord roles into decision was complicated and required modifications to the Discord plugin.

**Comment by JamieD1** [comment]
Hes right, kinda shitty that admins cant type, but eh might just be easier to do it this way without having to piss around with the plugin.

**Comment by adamsong** [comment]
If admins need to type, they can hop in game

**Comment by missatessatessy** [comment]
Couldn't you have a second ooc channel on the discord that only admins can access so they can bypass a mute toggle on the public one?

**Comment by adamsong** [comment]
Possibly, but that is effort, and involving systems I don't understand, while this pr involves systems I think I understand.

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
