### PR TITLE
Fixes 2 APCs being unable to be seen by the AI.

### PR DESCRIPTION
**Pull request by Lynameep**
Makes Medbay and Conference room's APCs visible to the AI.

#### Changelog

:cl:  
bugfix: fixed a few things   
tweak: tweaked a few things  
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
😂

**Comment by Moja10** [comment]
accident

**Comment by Lynameep** [comment]
Nice going Moja

**Comment by ynot01** [comment]
😂

**Comment by Lynameep** [comment]
No idea why Travis failed. Feelsbadman

**Comment by Ktlwjec1** [comment]
_maps/map_files/YogStation/YogStation.dmm:	step_x = 0;
step_x/step_y variables detected in maps, please remove them.

**Pull request merged**
