### PR TITLE
nerfs RD budget

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

fuck you rd mains

#### Changelog

:cl:
tweak: Scientific budget has been nerfed
/:cl:

### CODE REVIEW

**Comment by AsV9** [comment]
why is this a good idea?
please explain in detail

**Comment by Lynameep** [comment]
Why...?

**Comment by boodaliboo** [comment]
Ynot stop having a boner for removing shit

**Comment by ynot01** [comment]
as it currently stands, the budget has a hardcap of 5000 credits per payroll
i did not change this in the PR, as it is not my aim to make achieving this _impossible_
however, pre-nerf, it is incredibly easy to reach this cap. like, absurdly.

here's some examples pre-nerf:
20 tech nodes
or
10 T2 slimes
or
7 T3 slimes

here's what it would take post-nerf:
200 tech nodes (i nerfed tech nodes x10 because you really don't deserve a lot of money for pressing a button that says research)
or
25 T2 slimes
or
15 T3 slimes

i have hard nerfed the techweb bounty for obvious reasons. reaching the budget maximum generation because someone stumbled upon the computer 30 minutes into the round is ridiculous

xenobio generation has been lightly nerfed; as long as you have someone actively working in xenobio, you'll still be hitting the cap

this PR doesn't exactly hit the problem at it's heart, but it's more of a stepping stone towards creating a more balanced economy.

the true problem lies within the fact that the station is generating a maximum of $35,000 credits per payroll when the only place to use those credits is at cargo. there is absolutely no amount of spending to justify the million (1,000,000) credits the scientific budget accumulates by round-end

this PR by no means cripples the budget, it's just a nerf that will subdue the early generation that you get from doing effectively nothing, encouraging people to take a stroll to xeno or toxins if they truly, truly want that dosh (for 20 tesla starter kits, obviously)

**Comment by ThatLing** [comment]
Lyna is a scientist main, don't listen to him

**Comment by MegaEmpirical** [comment]
I think nerfing it is fine and there seems to be reasonable thought put into this.

**Comment by Codeatmos** [comment]
ynot...hmmmm yno/tg/,he is spy, removing balanced features, such as getting the bicycle round start and 50+ weapons crates.

**Comment by Lynameep** [comment]
I've personally never seen an issue with this but the nerf probably won't affect much as it's still fairly easy to generate credits through science with mass slime breeding.

**Comment by ghost** [comment]
hard nerf to the ability to fight nuke ops, clock cultists, and cultists through nerfing the ability for cargo to make money, though

given that by the time you'll actually be able to make enough money to do these things like selling slimes, well, you will have died to them.

more to the point though this lowers the science budget by so much that it is many times smaller than that of medical's. in fact, it's about 1/4 smaller just on techwebs.

**Comment by ynot01** [comment]
you dont deserve money for clicking techwebs

**Comment by ynot01** [comment]
you don't deserve money for tech webs

also i want to defeat the mindset that is "everything's gone to shit, lets take RD budget to cargo" because that's not the purpose of the RD budget

departmental budgets are supposed to reward departments with additional equipment that they can order from cargo based on how well they do

obviously this isn't the case and economy is severely fucked, but let's at least try to get some things right, especially with the recent addition of dump et

war ops rounds, imo, should instead consist of every department scrambling for shit to sell in order to purchase guns

**Pull request merged**
