### PR TITLE
adds oxygen to tower caps and iron to steel caps

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
trees make oxygen why dont they got the reagant and metal makes metal why  ot metal
#### Changelog

:cl:  
rscadd: Added iron reagant  to steel caps and oxygen reagant to tower caps  
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
your comments are cancer

**Comment by Nickvr628** [comment]
After rereading this twice I am still not sure what exactly this does

**Comment by boodaliboo** [comment]
> After rereading this twice I am still not sure what exactly this does

adds oxygen reagant to tower caps and iron reagant to steelcaps

**Comment by HomocidlePancakes** [comment]
@Nickvr628 Basically, a tray that shats out 13 10/10 EMPs on a tile every minute on demand. This is good because fuck silicons.

**Comment by HomocidlePancakes** [comment]
Actually, 11/11 since we don’t have the chems math fixed.

**Comment by alexkar598** [comment]
I am worried about balance implications of a new base Chem to botany

**Comment by HomocidlePancakes** [comment]
You have to drag the tray with you. It’s bulky and obvious and only screw over silicons in short range. I don’t think le epic disabler spamin’ unstanable secborg is balanced either, but he is still in.

**Comment by boodaliboo** [comment]
I didn’t think about the implication of emps should I remove it and replace the chem with like silicon

**Comment by alexkar598** [comment]
I don't like the implications of giving botany more base chemicals

**Pull request closed without merging**
