### PR TITLE
Raises Mjolnir cost to 3

### PR DESCRIPTION
**Pull request by Sniblet**
It's not funny anymore
I will NOT become an ided coder I swear, but way too many people use the Metahammer
The stun time is crazy and the throw speed is basically instant and its like tasers but worse
One one hand its wizard
On the other I beg you please stop doing this every other wizard round

# Wiki Documentation

Cost: 3

# Changelog

:cl:  
tweak: raised mjolnir cost to 3
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
i ded

make hammer have special throw that doesnt stun you when you hit a wall then lower the cost to 1

**Comment by Sniblet** [comment]
> make hammer have special throw that doesnt stun you when you hit a wall then lower the cost

when you code it

**Comment by Sniblet** [comment]
uh wait i broke it

**Review by Sniblet — COMMENTED** [review]
this was meant for a different PR how do I pull this out oh no

**Comment by Sniblet** [comment]
I've got it

**Pull request closed without merging**
