### PR TITLE
me fix altclick pda

### PR DESCRIPTION
**Pull request by warface1234455**
sorry guys i put this var in the wrong line

# Document the changes in your pull request
hotfix altclicking pda not ejecting id out

# Changelog

:cl:  

bugfix: hotfix altclicking pda not ejecting id out
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Make it eject the pen too

**Comment by ShoziOffical** [comment]
> Make it eject the pen too

awhati got it fixed hinn need to test to maKr Sur

**Review by MajManatee — APPROVED** [review]
looks functional

**Comment by ShoziOffical** [comment]
totally cuz i had my breakfast today, i didnt last time

> looks functional

**Review by ToasterBiome — APPROVED** [review]
i hate you

**Pull request merged**
