### PR TITLE
allows wizards to buy one use die of fate for 1 spell point and allows wizards to use die of fate

### PR DESCRIPTION
**Pull request by boodaliboo**
try your luck to either instant die or get another spellbook by becoming a wizard again
:cl:  
rscadd: Added die of fate as a wizard item
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
Me when the round ends 5 seconds in but it's not revs

**Comment by boodaliboo** [comment]
> Me when the round ends 5 seconds in but it's not revs

yes but unironically free antag reroll

**Comment by applepineapplepizza** [comment]
can you buy multiple?

**Comment by SomeguyManperson** [comment]
Hate to break your bibble but antags cant use the die of fate

**Comment by boodaliboo** [comment]
> Hate to break your bibble but antags cant use the die of fate

then how do i change this

**Comment by boodaliboo** [comment]
> Hate to break your bibble but antags cant use the die of fate

when was this changed i remeber using a die of fate as a traitor to get a stand

**Pull request closed without merging**
