### PR TITLE
removes the requirement for alien tech or syndi tech for advanced nanites but makes them cost 9x as much

### PR DESCRIPTION
**Pull request by boodaliboo**
you shouldnt have tech locked besides rng and if people even find it and now it takes an insane ammount of time if people do want this around 30 minutes or so
#### Changelog

:cl:  
tweak: made it so advanced nanites didnt need syndi/alien tech but are now insanely expensive
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
can i know why your downvoting this so i can address it if possible

**Comment by athena413** [comment]
might be too expensive or some shit, but otherwise, good

**Comment by ynot01** [comment]
this is stupid and takes away one of the non powergame points to space/miner ruins

**Comment by overlord12345** [comment]
ayy tech lets you make fucking zombies and illegal tech gives sec a lethal stun weapon plus gives med a tot only surgery.

**Comment by boodaliboo** [comment]
THIs is only for nanites this doesn’t affect anything else including alien tech making zombies or the likes

**Comment by athena413** [comment]
i do think that maybe you should lower the research costs to maybe like 50000 / 75000 cause currently the price is probably *too* ridiculous for anyone to really ever research

then again i've never seen what advanced nanites do so i might be entirely wrong

**Comment by boodaliboo** [comment]
> i do think that maybe you should lower the research costs to maybe like 50000 / 75000 cause currently the price is probably _too_ ridiculous for anyone to really ever research
> 
> then again i've never seen what advanced nanites do so i might be entirely wrong

if others want that im fine with doing so what do you think it should cost

**Comment by ToGWtF** [comment]
This means it takes literally half an hour of no one using points to be able to afford fucking foam guns

**Comment by ghost** [comment]
for context, this means that infectious nanites and mind control nanites will be available every round that goes on long enough

if you can't see why this is retarded you deserve the consequences

**Comment by boodaliboo** [comment]
this doesnt give you illegal tech or alien tech only the nanites

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
How about no....

I dont need to have to go and fix the entire station because an asshole decided it would be funny to get banned by blowing up everyone

**Pull request closed without merging**
