### PR TITLE
[PORT TG][BOUNTY MODSUIT] MODSUITS AND INTEGRATED CIRCUITS

### PR DESCRIPTION
**Pull request by wonderinghost**
# Document the changes in your pull request
fullfills bounty https://forums.yogstation.net/threads/60-ports-tg-modsuits-ss13-server-keeps-current-hardsuits.27179/

ports over both modsuits and integrated circuits. modsuits to complete the bounty set out by pibecantina. circuits out of interest of what they are, lumping together so a test merge can get out, not get stuck with broken items and can get two different feedbacks on the items added.

more to come in the future

# Why is this good for the game?
to help enrich science in its few limited, departmental jobs inside of the department.

more will be added later

# Testing
TBD

# Spriting
TBD

# Wiki Documentation
TBD

# Changelog

:cl:  

wip: This is work in progress   
experimental: This is experimental
/:cl:

### CODE REVIEW

**Review by Moltijoe — CHANGES_REQUESTED** [review]
atomize, both of these are fairly divisive features
if they're together there's almost no chance they'll get in

**Comment by wonderinghost** [comment]
> atomize, both of these are fairly divisive features if they're together there's almost no chance they'll get in

yeah however there is one mod which crosses over integrated circuits with modsuits, though then again i can hide it until i get the modsuit merged in. integrated circuits i at least want to get test merged because any time its boughten up i hear they are abused to lag or no one knows.

let me finish completing integrated circuits and this will become the integrated circuit branch

**Comment by MajManatee** [comment]
I believe the two are fairly reliant on each other from the last time i remember trying to port it, but that's another story.

**Comment by Moltijoe** [comment]
Please reopen this when you seek to continue working on it

**Pull request closed without merging**
