### PR TITLE
replaces the old brass knuckles sprite

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
replaces the old brass knuckles sprite
image
old
image
new
# Changelog

:cl:  
imageadd: add a new brass knuckles sprite
imagedel: deleted old brass knuckles sprite
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
@Cartlord what do you not like about the change?

**Comment by maxion12345** [comment]
Copper knuckles

**Comment by LazennG** [comment]
gone are the days of wearing glowing cheese on my hands

**Comment by Cartlord** [comment]
I do not like the new sprite because all of the holes are perfectly rectangular with the same orientation, it makes the perspective a bit fucked.

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Comment by Marmio64** [comment]
do note that they're supposed to be decorative brass knuckles, and every other decorative gang item is blinged out in gaudy gold to show that its just for vanity. The sprite itself looks better but doesn't fit in with the point of the knuckles. Maybe keep this version and add a gold version for these decorative brass knuckles, and if anyone ever adds real brass knuckles they can use this sprite?

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
