### PR TITLE
Clockcult pop requirement

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Clock cult stomping lowpop isn't new, fun, or interesting
Things brings it up to the same as nukies

:cl:  
tweak: Clockcult pop req increased to 30 from 24
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Didn't I already do this?

**Comment by Hislyna** [comment]
https://github.com/yogstation13/Yogstation/pull/19189/ Turns out this should've done it but im special and didn't know which to change so cults should be 35 and revs 30 >~>

**Comment by iloveloopers** [comment]
damn, 35 people is alot of people

**Comment by N3D6** [comment]
This will just make the mode never spawn because no more than 25 people ever ready up and that’s what it goes by

**Comment by Hislyna** [comment]
I mean it should already be 35 sooooooooooooooooo

**Comment by N3D6** [comment]
> I mean it should already by 35 sooooooooooooooooo

35 is too high and will just make it never get picked, see heretics before I (very cool) lowered it

**Comment by iloveloopers** [comment]
> This will just make the mode never spawn because no more than 25 people ever ready up and that’s what it goes by

I thought non-readied players were counted as half of a readied player? although high pop gamemodes are way too rare definitely

**Comment by iloveloopers** [comment]
would be cool if low-pop gamemodes like traitors and lings had a lower chance of being picked when high pop gamemodes are avaliable

**Comment by DeadlyBag** [comment]
I would rather get constantly killed by clockcultists round after round rather than have to endure another fucking traitor round.

**Comment by N3D6** [comment]
This PR sucks and the number is way too high. Make it 30 instead. 35 is too much, I’m sick of having hardly any game mode variety and this doesn’t help it any

**Comment by Moltijoe** [comment]
30 now

**Comment by N3D6** [comment]
> 30 now

Thank you, based maint listening to peoples opinions

**Comment by Moltijoe** [comment]
> Thank you, based maint listening to peoples opinions

balance council told me to actually

**Comment by Hislyna** [comment]
> > Thank you, based maint listening to peoples opinions
> 
> balance council told me to actually

Strange when they authed 35 on mine *sus

**Comment by Moltijoe** [comment]
spawn less clockies instead

**Pull request closed without merging**
