### PR TITLE
Medbay Rework

### PR DESCRIPTION
**Pull request by Hopekz**
Made using Monster's cool new tool!

1: **Added a west-side back door to medbay through the observation room**
-----

The observation room is public but the door circled in blue is medbay access.
------

2:  Added a window to the west side of cloning! Re-arranged some tables!
------

3: Moved the plant from cloning!
------

4: **Also fixed the privacy issue north of medical secure storage**
------

#### Changelog

:cl:  
tweak: Reworked medbay! The observation room is now public.
tweak: Made an entrance to medbay via the observation room.
tweak: Added a window to the west side of cloning
rsadd: Added a  plant to Viro entrance! Important!
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
Plant was feature not bug

**Review by Ktlwjec1 — COMMENTED** [review]
Ok I have some issues.

Mapping technical shit:
- Firelocks needed under the new cloning airlock.
- Plating turf needed under the new cloning window.
- Lights should avoid windows if possible, so the cloning light needs moving.
- White plasteel turf needed under the west airlocks.
- Firelocks needed under the west airlocks.
- Consider blue decals in the hallway outside the west airlocks.

Other:
- I really can't approve this cloning change. 2 airlocks are very much unneeded, especially when they lead to somewhere about a 2 second walk from each other. It also looks super ugly, which is the main reason.
- The west doors I've seen on other servers and always viewed it as unneeded, and it looks like lazy mapping which is why I suggested the decals. I'm wondering if it'd be better to only have them appear on highpop, since that's when they are only really "needed".
- Maps should NOT be 100% perfect. I'm aware these are somewhat common changes done in-game, but this is a result of the station not being 100% efficient in design as it should be. To me, these changes only seem a result of this. That being said, I'm willing to keep all of this except for cloning changes if people like them.
- Alternatively, instead of the west airlocks for highpop, having it randomly switch between doors and walls would be nice.

**Comment by Darkstick** [comment]
as a small detail as it is, I really don't like the window under cryo. I prefer that room to be more private.
Cloning doesn't really need two doors, but the window on the side is a nice tough.
I'd get rid of the window under cryo and that door bellow cloning.

**Comment by Hopekz** [comment]
> I'd get rid of the window under cryo and that door bellow cloning.

You play medbay a lot so I respect your opinion.
Added removing that part on my to-do when I get home tonight.

**Comment by Hopekz** [comment]
**Updated; Ready!**
------

**Comment by Hopekz** [comment]
**Ready**
----

**Comment by MegaEmpirical** [comment]
Put cloning table back where it was. The corner is useful for dragging bodies and turning.

**Comment by Hopekz** [comment]
> Put cloning table back where it was. The corner is useful for dragging bodies and turning.

Good catch!
It is done.

image

**Comment by Hopekz** [comment]
Edit:
I also added a curtain. Wow!
image

**Comment by Ktlwjec1** [comment]
Ok last things then it is merge ready:

Smoking sign is placed on the air alarm tile. It needs to be (if you want it visible on both sides of the wall) placed on the left wall where it currently looks like it is, with no pixel_x/y value, or (if only visible from surgery) it needs be placed 1 tile down with x value 0 and y value 32.
image

Add plant back here, keep the one by viro still.
image

I'd add a helper here so people can still enter the surgery room from medbay. Also consider a non-glass airlock, I found it looked a ton better.
image

Light, sign and air alarm moving.
image

**Comment by Hopekz** [comment]
Suggestions committed

**Pull request merged**
