### PR TITLE
Minecraft update (real) (Sniffer included) - Adds new animal cube sprites

### PR DESCRIPTION
**Pull request by Majkl-J**
# Document the changes in your pull request

Game design (Visually distinguishable = good)
Every animal cube now looks a bit different, and the cube files have been moved to a standalone dmi

# Spriting
image

I think it is pretty obvious which one is which.

# Wiki Documentation
No clue if you need these, but here they are anyhow

Goat
goatcube2
Gorilla
gorillacube
Sheep
sheepcube
Bee
beecube
Cow
cowcube

# Changelog

:cl:  
imageadd: Nanotrasen introduces new animal cube designs to prevent workplace accidents
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
I added a blood splotch on the goat cube as it was hard to distinguish (Cuackles please leave it alone I will cry)

image

**Comment by cuackles** [comment]
> I added a blood splotch on the goat cube as it was hard to distinguish (Cuackles please leave it alone I will cry)
> 
> image

Unblood the goat pls it doesn't fit

**Comment by cuackles** [comment]
Maybe give it some Lil beady eyes

**Comment by Maia-J** [comment]
> > I added a blood splotch on the goat cube as it was hard to distinguish (Cuackles please leave it alone I will cry)
> > image
> 
> Unblood the goat pls it doesn't fit

😢

**Comment by Maia-J** [comment]
I updated the sheep, visible in PR description

**Review by cuackles — APPROVED** [review]

**Pull request merged**
