### PR TITLE
Adds a light replacer to the Engineering borg

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
Doesn't really make sense that Engineering borgs can't build rooms with lights.

This should allow engi borgs to build sweet rooms and departure lounges

#### Changelog

:cl:  
rscadd: The Engineering borg now has a light replacer
/:cl:

### CODE REVIEW

**Comment by TheReddDragon** [comment]
please merge this

**Comment by Hopekz** [comment]
1. The light replacer does not create lights
2. The Janitor borg has this "replace" light module. 
3. The Engi borg is already really powerful. This is one of the few remaining reasons to go Janiborg because of this "light replacer" tool on slings, darkspawn, nightmare etc.

**Comment by Bibby0110** [comment]
> 1. The light replacer does not create lights
> 2. The Janitor borg has this "replace" light module.
> 3. The Engi borg is already really powerful. This is one of the few remaining reasons to go Janiborg because not Engiborgs have this "light replacer" tool on slings etc.

1. No, but it can place lights in light fixtures
2. Yes it does, for fixing broken lights.
3. I'll be happy to nerf it for you if you think slings will be an issue

**Comment by Hopekz** [comment]
> > 1. The light replacer does not create lights
> > 2. The Janitor borg has this "replace" light module.
> > 3. The Engi borg is already really powerful. This is one of the few remaining reasons to go Janiborg because not Engiborgs have this "light replacer" tool on slings etc.
> 
> 1. No, but it can place lights in light fixtures
> 2. Yes it does, for fixing broken lights.
> 3. I'll be happy to nerf it for you if you think slings will be an issue

1:  It can't?  A light replacer can only replace broken lights. If there is no light in the socket it cannot place a new one (light replacer bug)
2: Yes but you're giving the same tool to both borgs. Put whatever flavor text you want on it.
3. Yes thank you I'd like this very much (make sure the janiborg one is separate and un-nerfed)

**Comment by alexkar598** [comment]
engi borg power crêpes

**Comment by MonsWTF** [comment]
I disagree with the PR. I believe it would be more pertinent for Engiborg to be able to physically store a singular light tube/bulb in itself that it could then deploy on an empty/broken light fixture. (it picks them up after being produced at an Autolathe)

That way, the JaniBorg continues to serve the purpose of mass-replacement, while the Engiborg has minimal replacement capacity and new light installations (namely, floodlight construction).

**Comment by Bibby0110** [comment]
> engi borg power crêpes

Why would you say this now, and not when Nich allowed Engi borgs to use circuits, which is literally incredibly powerful?



> I disagree with the PR. I believe it would be more pertinent for Engiborg to be able to physically store a singular light tube/bulb in itself that it could then deploy on an empty/broken light fixture. (it picks them up after being produced at an Autolathe)
> 
> That way, the JaniBorg continues to serve the purpose of mass-replacement, while the Engiborg has minimal replacement capacity and new light installations (namely, floodlight construction).
No


> > > 1. The light replacer does not create lights
> > > 2. The Janitor borg has this "replace" light module.
> > > 3. The Engi borg is already really powerful. This is one of the few remaining reasons to go Janiborg because not Engiborgs have this "light replacer" tool on slings etc.
> > 
> > 
> > 
> > 1. No, but it can place lights in light fixtures
> > 2. Yes it does, for fixing broken lights.
> > 3. I'll be happy to nerf it for you if you think slings will be an issue
> 
> 1: It can't? A light replacer can only replace broken lights. If there is no light in the socket it cannot place a new one (light replacer bug)
> 2: Yes but you're giving the same tool to both borgs. Put whatever flavor text you want on it.
> 3. Yes thank you I'd like this very much (make sure the janiborg one is separate and un-nerfed)
1. Then fix the bug?
2. I don't even know your point with this

**Comment by Hopekz** [comment]
> > > > 1. The light replacer does not create lights
> > > > 2. The Janitor borg has this "replace" light module.
> > > > 3. The Engi borg is already really powerful. This is one of the few remaining reasons to go Janiborg because not Engiborgs have this "light replacer" tool on slings etc.
> > > 
> > > 
> > > 
> > > 1. No, but it can place lights in light fixtures
> > > 2. Yes it does, for fixing broken lights.
> > > 3. I'll be happy to nerf it for you if you think slings will be an issue
> > 
> > 
> > 1: It can't? A light replacer can only replace broken lights. If there is no light in the socket it cannot place a new one (light replacer bug)
> > 2: Yes but you're giving the same tool to both borgs. Put whatever flavor text you want on it.
> > 3. Yes thank you I'd like this very much (make sure the janiborg one is separate and un-nerfed)
> 
> 1. Then fix the bug?
> 2. I don't even know your point with this

1. No thank you. I think this "bugged" version of the light replacer works better than a "fixed" version that can place new lights. Also its a light "replacer" and not a "placer" so it fits.
2. My point is power creep basically. Only real upside Jani borg has is this light replacer. Now Engi borg performs whatever function JaniBorg had.

**Comment by Bibby0110** [comment]
> > > > > 1. The light replacer does not create lights
> > > > > 2. The Janitor borg has this "replace" light module.
> > > > > 3. The Engi borg is already really powerful. This is one of the few remaining reasons to go Janiborg because not Engiborgs have this "light replacer" tool on slings etc.
> > > > 
> > > > 
> > > > 
> > > > 1. No, but it can place lights in light fixtures
> > > > 2. Yes it does, for fixing broken lights.
> > > > 3. I'll be happy to nerf it for you if you think slings will be an issue
> > > 
> > > 
> > > 1: It can't? A light replacer can only replace broken lights. If there is no light in the socket it cannot place a new one (light replacer bug)
> > > 2: Yes but you're giving the same tool to both borgs. Put whatever flavor text you want on it.
> > > 3. Yes thank you I'd like this very much (make sure the janiborg one is separate and un-nerfed)
> > 
> > 
> > 
> > 1. Then fix the bug?
> > 2. I don't even know your point with this
> 
> 1. No thank you. I think this "bugged" version of the light replacer works better than a "fixed" version that can place new lights. Also its a light "replacer" and not a "placer" so it fits.
> 2. My point is power creep basically. Only real upside Jani borg has is this light replacer. Now Engi borg performs whatever function JaniBorg had.

1. It's 'replacing' the emptiness with something. Fits perfectly with a light replacer
2. And you know, their trashbag and they clean anything they walk over

**Comment by Hopekz** [comment]
> > > > > > 1. The light replacer does not create lights
> > > > > > 2. The Janitor borg has this "replace" light module.
> > > > > > 3. The Engi borg is already really powerful. This is one of the few remaining reasons to go Janiborg because not Engiborgs have this "light replacer" tool on slings etc.
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. No, but it can place lights in light fixtures
> > > > > 2. Yes it does, for fixing broken lights.
> > > > > 3. I'll be happy to nerf it for you if you think slings will be an issue
> > > > 
> > > > 
> > > > 1: It can't? A light replacer can only replace broken lights. If there is no light in the socket it cannot place a new one (light replacer bug)
> > > > 2: Yes but you're giving the same tool to both borgs. Put whatever flavor text you want on it.
> > > > 3. Yes thank you I'd like this very much (make sure the janiborg one is separate and un-nerfed)
> > > 
> > > 
> > > 
> > > 1. Then fix the bug?
> > > 2. I don't even know your point with this
> > 
> > 
> > 
> > 1. No thank you. I think this "bugged" version of the light replacer works better than a "fixed" version that can place new lights. Also its a light "replacer" and not a "placer" so it fits.
> > 2. My point is power creep basically. Only real upside Jani borg has is this light replacer. Now Engi borg performs whatever function JaniBorg had.
> 
> 1. It's 'replacing' the emptiness with something. Fits perfectly with a light replacer
> 2. And you know, their trashbag and they clean anything they walk over

1. Okay cool.
2. Yeah like I said; useless in terms of practicality. The light replacer is barley making them viable but only during certain shifts.

**Comment by alexkar598** [comment]
img

**Comment by Bibby0110** [comment]
See https://forums.yogstation.net/index.php?threads/vote-give-engiborgs-a-light-replacer.20924/

**Pull request closed without merging**
