### PR TITLE
Ports /tg/ sheet sprites

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request
Removes soul

`icons\obj\stack_objects.dmi` has been wiped and replaced with tg's latest version

`icons\obj\mining.dmi` and `icons\obj\telescience.dmi` have been updated with stack sprites that were placed there (goliath hide, bluespace crystals, etc)

*most* yog-exclusive sprites were already present in `yogstation\icons\obj\stack_objects.dmi` so all yog-exclusive sprite references now point there, others added

all sprites that previously had no variants have been marked to support variants (diamond, uranium, bananium, wood, cardboard, runed metal, telecrystals)

removed now-unnecessary ducttape polycrystal reference

cable coil & ethernet cable sprites are now located in `icons\obj\stack_objects.dmi`

Ore sprites ported

# Why is this good for the game?
Old sprites ugly 
image
image

# Testing
Spawned in the materials debug box, all sprites are proper

Mech fab displays new sprites correctly

No runtimes involving missing sprites

# Spriting
image
image
image
image

# Changelog

:cl:  
imageadd: Ported /tg/ sheet sprites
/:cl:

### CODE REVIEW

**Comment by Scrambledeggs00** [comment]
mmmmm
yummy rock candy plasma :]

**Comment by ShoziOffical** [comment]
Mmmmm rocky

**Comment by AMyriad** [comment]
Firstly idunno if I missed where you readded these or if ye forgot to, but these deleted icons here are still used. Correct me if I'm wrong.
image

Secondly, I despise their cable coil. I don't have the words to critique it, but the ones we got rn are better by a long shot.
image

Thirdly, if you're porting the processed ore sprites I recommend putting in their raw ore sprites too to keep suit. Up to you tho.
image

That's about it. I don't have big problem with the art since we kinda do be shifting towards that style gradually. I leave that judgement call to biome and cuackles.

**Comment by ynot01** [comment]
> Firstly idunno if I missed where you readded these or if ye forgot to, but these deleted icons here are still used. Correct me if I'm wrong. 

These are unused sprites that were moved to `code\game\objects\items\stacks\medical.dm`

> Secondly, I despise their cable coil. I don't have the words to critique it, but the ones we got rn are better by a long shot. 
> 
> Thirdly, if you're porting the processed ore sprites I recommend putting in their raw ore sprites too to keep suit. Up to you tho. 

Could, but I don't see the immediate need unless someone tells me to

> That's about it. I don't have big problem with the art since we kinda do be shifting towards that style gradually. I leave that judgement call to biome and cuackles.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
port ore sprites revert changes in bscrystal.dm

**Comment by nesisknesis** [comment]
I think keeping the old plasma sprite would be funny, the new one looks conventionally better but it's just as indiscernable so I can't say it's a total improvement really

**Comment by StupidTums** [comment]
I don't think it makes sense to update sheet sprites before updating wall sprites. For example, the iron wall matches the iron sheet, but for the new iron sheet, they are very different in color, for instance. Also, the cultist sheets and wood sheet look worse in my opinion.

**Comment by ynot01** [comment]
> I don't think it makes sense to update sheet sprites before updating wall sprites. For example, the iron wall matches the iron sheet, but for the new iron sheet, they are very different in color, for instance. Also, the cultist sheets and wood sheet look worse in my opinion.

The wall sprites suck

**Comment by StupidTums** [comment]
> > I don't think it makes sense to update sheet sprites before updating wall sprites. For example, the iron wall matches the iron sheet, but for the new iron sheet, they are very different in color, for instance. Also, the cultist sheets and wood sheet look worse in my opinion.
> 
> The wall sprites suck

Whether the current wall sprites are good or not is not what's important. Keeping the art style of yogs consistent within itself is. Grabbing sprites from tg and plastering them on to yogs will cause our non-updated sprites to stick out like a sore thumb (such as introducing a new iron sheet without updating the wall you'd use that iron sheet on).

**Comment by AMyriad** [comment]
> Whether the current wall sprites are good or not is not what's important. Keeping the art style of yogs consistent within itself is. Grabbing sprites from tg and plastering them on to yogs will cause our non-updated sprites to stick out like a sore thumb (such as introducing a new iron sheet without updating the wall you'd use that iron sheet on).

We're supposedly getting new walls soon so I wouldn't worry about this too much. Otherwise, other sprites in need of polishing will be updated in due time.

**Review by ToasterBiome — APPROVED** [review]

**Comment by Cartlord** [comment]
> > I don't think it makes sense to update sheet sprites before updating wall sprites. For example, the iron wall matches the iron sheet, but for the new iron sheet, they are very different in color, for instance. Also, the cultist sheets and wood sheet look worse in my opinion.
> 
> The wall sprites suck

i don't even know if you mean you think old wall sprites or you think the proposed new wall sprites suck... please elaborate?

**Comment by ynot01** [comment]
> i don't even know if you mean you think old wall sprites or you think the proposed new wall sprites suck... please elaborate?

i am not a fan of /tg/ wall sprites, we are getting our own wall sprites anyways so it is irrelevant

**Comment by StupidTums** [comment]
> > i don't even know if you mean you think old wall sprites or you think the proposed new wall sprites suck... please elaborate?
> 
> i am not a fan of /tg/ wall sprites, we are getting our own wall sprites anyways so it is irrelevant

Two of the sheet sprites that you show really stick out to me here as being inferior: the wood and blood cult sheet. Those two look like downgrades ngl. Also, I'm not against new sprites being added at all, and I hope my comments haven't given the idea that I'm opposed to changes in what we have.

**Comment by ynot01** [comment]
> Two of the sheet sprites that you show really stick out to me here as being inferior: the wood and blood cult sheet. Those two look like downgrades ngl. Also, I'm not against new sprites being added at all, and I hope my comments haven't given the idea that I'm opposed to changes in what we have.

just to clear up, the screenshot in the PR does not include "created" sheet sprites, so for sheets that previously had no stacking sprites but now *do* (like wood and cult metal) don't have those additional sprites in the screenshot, but if you move to the Checks tab you can find them under IconDiffBot

**Review by cuackles — CHANGES_REQUESTED** [review]
i would like it if the goliath plate didnt look like that, feels odd, think using the dragon scales as a base for them would work best, gonna need them to be changed

**Comment by ynot01** [comment]
> i would like it if the goliath plate didnt look like that, feels odd, think using the dragon scales as a base for them would work best, gonna need them to be changed

this is a port and im not a spriter, what would you like me to do?

**Comment by cuackles** [comment]
> > i would like it if the goliath plate didnt look like that, feels odd, think using the dragon scales as a base for them would work best, gonna need them to be changed
> 
> this is a port and im not a spriter, what would you like me to do?

sorry didnt get a notification from repply, the plates needs to look simpler, honesly you could just replace the colors of the dragon hide with colors from the plate and it should be good

**Comment by ynot01** [comment]
> > > i would like it if the goliath plate didnt look like that, feels odd, think using the dragon scales as a base for them would work best, gonna need them to be changed
> > 
> > 
> > this is a port and im not a spriter, what would you like me to do?
> 
> sorry didnt get a notification from repply, the plates needs to look simpler, honesly you could just replace the colors of the dragon hide with colors from the plate and it should be good

you want the dragon hide to be pink like goliath hide, or goliath hide to be red like dragon hide?

**Comment by cuackles** [comment]
> > > > i would like it if the goliath plate didnt look like that, feels odd, think using the dragon scales as a base for them would work best, gonna need them to be changed
> > > 
> > > 
> > > this is a port and im not a spriter, what would you like me to do?
> > 
> > sorry didnt get a notification from repply, the plates needs to look simpler, honesly you could just replace the colors of the dragon hide with colors from the plate and it should be good
> 
> you want the dragon hide to be pink like goliath hide, or goliath hide to be red like dragon hide?

Change Goliath sprite to dragon hide tinted pink

**Review by cuackles — APPROVED** [review]

**Pull request merged**
