### PR TITLE
New Ghost Role: Icemoon Walkers

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

Kinda sorta Icemoon version of ashwalkers (they can't respawn)

Adds a tribe of smart zombies to Icemoon with the goal to feast.  They explicitly can't board the station

THESE ARE **NOT** INFECTIOUS ZOMBIES

image_2023-09-16_080215517

# Why is this good for the game?

antagonistic ghostrole for icemeta

# Wiki Documentation

needs page on ruins wiki

# Changelog

:cl:  cark
mapping: new icemoon ghostrole - Icemoon Walkers
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
having no hands is lame esspecially as a ghost role
ashwalkers have the benefit that they can make cool weapons and have fun with them and try to survive, these guys are just
hit with hand hope go well

**Comment by neeshacark** [comment]
> having no hands is lame esspecially as a ghost role ashwalkers have the benefit that they can make cool weapons and have fun with them and try to survive, these guys are just hit with hand hope go well

they are smart zombies they have hands smh

**Comment by N3D6** [comment]
sick how do they reproduce?

**Comment by neeshacark** [comment]
> sick how do they reproduce?

i had a concept originally where they would get a chemical that is produced by some sort of plant that they could use to turn any dead carbon/ into a new spawner but i have no idea how to code so they just cant reproduce because i didnt want their flavor to just be ashwalker but again with a miniscule sprite change

the process was in my head:

find dead carbon
get chem from plant
feed chem to dead carbon
bury dead carbon in grave
grave turns into new spawner

we dont have code for like any of that so

**Review by Aquizit — CHANGES_REQUESTED** [review]
I'm dumb I forgot the spawner/ makes the grilles

**Review by Aquizit — APPROVED** [review]

**Comment by Aquizit** [comment]
Map is fine

**Pull request merged**
