### PR TITLE
Adds a new chemical recipe to make godsblood to curb botanist making instaheal plants

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
when earthsblood and omnizine are combined it creates godblood which is omnizine with a od of 150
so botanist are rewarded with a intresting new chem for combining earthsblood with omnizine but not given a instaheal mix

#### Changelog

:cl:  
rscadd: Added a new chemical recipe 
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
what

**Comment by boodaliboo** [comment]
> what

it just allows godblood to be creatable which is identical to omnizine bt with a significantly higher od

**Comment by Amelia0010** [comment]
right so what stops them from just making omnizine instead?

**Comment by boodaliboo** [comment]
they already get omnizine from ambrosia deus 

> right so what stops them from just making omnizine instead?

**Comment by Rayisken** [comment]
It's not really interesting if all it has is a different OD threshold, the current chem downsides can be mitigated by mixing with other things to minimize the effects. If you were adding another tier to these chemicals I think something closer to Atropine would make more sense.

**Comment by boodaliboo** [comment]
I’m not trying to make it more powerful  trying to make it slightly harder to make a Instant heal plant but also give something in return

**Comment by Amelia0010** [comment]
but you haven't made it harder? You've just added another chemical, you've not made it harder to get the other one

**Comment by boodaliboo** [comment]
> but you haven't made it harder? You've just added another chemical, you've not made it harder to get the other one

im not trying to make it harder im trying to prevent two chems that heal very fast being used in tandem but not just outright making them do nothing when combined

**Comment by ShadowDeath6** [comment]
Not sure on the percentages for omnizine and earthsblood, but if they're equal this should stop one plant from fully healing you instantly.

It doesn't really solve the issue at higher dosages though, since people can just take more earthsblood and then it's functionally identical to omnizine+earthsblood anyway

**Comment by boodaliboo** [comment]
> Not sure on the percentages for omnizine and earthsblood, but if they're equal this should stop one plant from fully healing you instantly.
> 
> It doesn't really solve the issue at higher dosages though, since people can just take more earthsblood and then it's functionally identical to omnizine+earthsblood anyway

that is technically true but if i remeber correctly both omnizine and earthsblood got the same percentage in there plants

**Comment by HomocidlePancakes** [comment]
>Using 2 chems with extremely different metab rates in 1 plant

>OD

B R U H

**Comment by alexkar598** [comment]
Not a problem at the moment.

**Pull request closed without merging**
