### PR TITLE
disables all the gamemodes i don't like

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
they're bad anyways, rework them and then turn them back on

# Changelog

:cl:  
tweak: all the gamemodes i don't like have been disabled
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
Based changelog

**Comment by BurgerLUA** [comment]
based

**Comment by ynot01** [comment]
sounds good merge it

**Comment by Hislyna** [comment]
Based

**Comment by Hislyna** [comment]
Smh ignoring the On Hold HD

**Comment by burn1cycle** [comment]
Sneak move not telling us what game modes you're modifying. Against just because of lack of transparency.

**Pull request closed without merging**
