### PR TITLE
another attempt at fixing cult

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

The error we get is that they physically cannot find the objective, which should never be the case as it seems to be given just fine, so my assumption is that it's being checked before the round even starts. This is a problem in other gamemodes but theyve been fixed because they respect parent, cult doesn't seem to.

# Changelog

:cl:  
bugfix: Cult works now... for real.
bugfix: Cult's antag info button now starts with the objectives, rather than having to close and reopen it to see them.
bugfix: Admins can now see Cult objectives in their TP
bugfix: IPCs can no longer roll cult target
bugfix: Cult's objective text no longer has a random <b
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Added some extra fixes with this
image

Players from the very beginning will see their objectives in their antag info button, they don't need to close and reopen the tab
Also makes these objectives visible in the admin panel without having to snowflake add objectives into the datum from their team.
^^ I DID THIS FOR ALL ANTAGS. NOT JUST CULT

Also fixes IPCs being selected as the target
Fixes the bad text in the objective desciption.

**Comment by JohnFulpWillard** [comment]
Other examples

Abductor
image

Traitor (not showing Team objectives, as they arent in one)
image

**Review by ynot01 — APPROVED** [review]
probably works idk

**Comment by adamsong** [comment]
You broke the 'Convert to traitor' button

**Pull request merged**
