### PR TITLE
Makes sling chitin item icons visible

### PR DESCRIPTION
**Pull request by Sniblet**
# Document the changes in your pull request

Well for a start you're looking in the wrong file

# Changelog

:cl:  
imageadd: sling chitin now actually uses its sprites
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
first try!!
first try

**Comment by Chubbygummibear** [comment]
i think changing both to shadowling breaks the fact that in the yogstation folder icons there is a sick pulsating sling armor named sl_shell in mob/suit.dmi. i'd recommend moving the "shadowling" inventory icons to the yogstation icon folder under obj/clothing/suit and obj/clothing/hat dmis

**Comment by Sniblet** [comment]
> i'd recommend moving the "shadowling" inventory icons to the yogstation icon folder under obj/clothing/suit and obj/clothing/hat dmis

how do i move icons

**Comment by Chubbygummibear** [comment]
> > i'd recommend moving the "shadowling" inventory icons to the yogstation icon folder under obj/clothing/suit and obj/clothing/hat dmis
> 
> how do i move icons

you just gotta copy and paste the icon into another folder, so for the helmet copy the "shadowling" icon that's the helmet from icons/obj/clothing/hats.dmi, and paste it into yogstation/icons/obj/clothing/hats.dmi. to get the icons to find the file properly though you'd most like need to add something like

item = 'yogstation/icons/obj/clothing/hats.dmi'

you could probably get by without doing this and just doing the rename along, but i wanted to suggest grouping the icons together in the yoggers folder while you're at it, since modularity and whatnot

**Comment by Sniblet** [comment]
It doesn't let me access the icons, trying to View Raw just downloads the raw, I don't know how to then make changes that are reflected here

**Comment by Chubbygummibear** [comment]
> It doesn't let me access the icons, trying to View Raw just downloads the raw, I don't know how to then make changes that are reflected here

ohhhh oof sorry that's something you have to do through dreamaker

**Comment by Sniblet** [comment]
I know how to do it in dreamaker but how do I then make the changes in dreamaker affect the github

**Comment by Chubbygummibear** [comment]
> I know how to do it in dreamaker but how do I then make the changes in dreamaker affect the github

if you're using github desktop/vscode it will recognize that the files have changed, so you then stage and commit the dmi's them after shuffling around the icons

**Comment by Sniblet** [comment]
Fifth try!!
fifth try

**Comment by Chubbygummibear** [comment]
hell yeah gamer nice!

**Review by JamieD1 — APPROVED** [review]
Moving art, none created.

**Pull request merged**
