### PR TITLE
Who the fuck thought that 20k a minute was a good idea from one rad collector?

### PR DESCRIPTION
**Pull request by JamieD1**
Who the fuck thought that 20k a minute was a good idea from one rad collector

:cl:  
tweak: Nerfs Rad Collector money by a factor of 20
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
i belive that this was a great idea so my singularity amkes 70mw

**Comment by iamthesilly** [comment]
You underestimate my power

**Comment by JamieD1** [comment]
Changed to / 20

**Comment by Rdrazga** [comment]
Jamie not realizing that 20k/minute was a LOW amount of money and some of the boys were making 2 million/minute

**Pull request merged**
