### PR TITLE
THE INEVITABLE RETURN OF NICH or how I learned to stop worrying and love the pipes

### PR DESCRIPTION
**Pull request by Amelia0010**
All supply/waste pipes are now on layer 1/3 respectively, and don't go through walls. Now, this might not sound revolutionary, but just look at this:
image
image
image
image

:cl: PIPEMASTER NICH
tweak: supply/waste piping is now much much much much much much much much much much much much better
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
oh and it includes ktl's detective thing I guess

**Comment by Moja10** [comment]
Excellent return Nich!!

**Comment by thehighwayman** [comment]
The LEGEND has returned

**Comment by Amelia0010** [comment]
should probably wait for https://github.com/tgstation/tgstation/pull/40934, but it's not necessary

**Comment by Amelia0010** [comment]
image

This is still an issue, but I've not got a fix

**Comment by Kmc2000** [comment]
bad pr

**Comment by Ktlwjec** [comment]
looks really cute

**Comment by ghost** [comment]
the fix is to put a floor tile under the door

**Comment by Cw3040** [comment]
As a /tg/code atmos player, layers 1 and 3 should be reserved to atmos projects; they should not be roundstart.

**Pull request merged**
