### PR TITLE
Adds Gift Shop to Omegastation

### PR DESCRIPTION
**Pull request by alao3alao3**
### Intent of your Pull Request
To hopefully merge correct files that were rectified in light of feedback.
Annotation 2020-07-13 231803
Should be noted that all gift shops have keys despite them serving more use.

#### Changelog

:cl:  
rscadd: Light, named gift shop maint door, rotated register, added wall.
rscdel: Removed restrictions on having a clerk on omega.
/:cl:

### CODE REVIEW

**Comment by alao3alao3** [comment]
How the hell do I address a failed check, I'm not sure if I'm just supposed to rebuild the whole damn branch, fork and map from scratch

**Comment by patpol4** [comment]
Sometimes the bot is a little shit and you have to push a commit to make it run again

**Review by patpol4 — CHANGES_REQUESTED** [review]
You didnt do the thing ktl requested,
you'll need to go to "/code/modules/jobs/job_types/clerk.dm" and remove "/datum/job/clerk/proc/OmegaStationChanges()
return TRUE"
and edit changed_maps to remove Omega. Also make sure the original clerk spawner is removed from this map if you haven't done that already, it's currently between medbay and research.

**Comment by alao3alao3** [comment]
Wrong damn things been PR’d then, I’ll just remake the whole PR. I wish changing a single file wasn’t such a pain on github.

**Comment by Ktlwjec1** [comment]
Closing due to the last comment, let me know if you end up wanting this reopened. You can ask for help on our discord so you don't have to keep opening and closing prs to change things.

**Pull request closed without merging**
