### PR TITLE
Wings colour split

### PR DESCRIPTION
**Pull request by Moltijoe**
Closes: #18565

Huge props to @BlueishTsunami for the amazing spritework

image

added some code to allow wings to be made of 2 different sprites (different colour sources usually)

:cl:  @BlueishTsunami @Moltijoe 
tweak: Lets wings have multiple colour sources
imageadd: splits phytosian wings into two different sprites
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
THESE SOME HIGH-QUALITY MFIN SPRITES YO

**Comment by Moltijoe** [comment]
> THESE SOME HIGH-QUALITY MFIN SPRITES YO

i fuckin know right?
cuackles tells me to give this guy some work because he's wanting to "learn how to sprite" and then he bangs this amazing shit out

**Comment by cuackles** [comment]
> > THESE SOME HIGH-QUALITY MFIN SPRITES YO
> 
> i fuckin know right? cuackles tells me to give this guy some work because he's wanting to "learn how to sprite" and then he bangs this amazing shit out

dont blame me im as surprised as you

**Review by cuackles — APPROVED** [review]

**Comment by CrazyDrakkon** [comment]
GOOD shit

**Pull request merged**
