### PR TITLE
[MDB IGNORE][Box] Updates Genetics Layout + fixes

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Updates Box's genetics layout, which I felt was lacking; and fixes some things:

- missing air alarm in genetics is missing no more
- adds a wall extinguisher cabinet to genetics so you can leave the one in cloning alone
- fixes a random missing distro pipe in medbay hallway

also shuffled cloning's lockers around some, and gave it a requests console

Before:
ss (2022-08-12 at 04 51 07)

After:
ss (2022-08-12 at 04 51 25)

# Changelog

:cl:  
bugfix: Genetics now features an Air Alarm
bugfix: Air pipes in medbay hallway by the CMO office connect properly now
tweak: Shuffled the layout of Genetics around
tweak: shuffled some stuff in Cloning
tweak: Cloning now has a requests console
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
Can someone who has the power put MDB2 out of its misery here please

**Comment by VaelophisNyx** [comment]
ok wait there we go

**Comment by JamieD1** [comment]
I dont like how the trash is in the middle of the room in the way

**Comment by VaelophisNyx** [comment]
if you have a suggestion for a better spot, I'm all ears

**Comment by Xantam-13** [comment]
> if you have a suggestion for a better spot, I'm all ears

image

**Comment by VaelophisNyx** [comment]
I'll look into that, thanks Xantam

**Comment by VaelophisNyx** [comment]
before you ask I somehow bricked the branch

**Pull request closed without merging**
