### PR TITLE
Adds nitrous oxide decomposition

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Makes nitrous oxide decompose into nitrogen and oxygen in an exothermic reaction when heated above 1073 Kelvin. Reaction stops at 100,000 Kelvin. Has been tested.

# Wiki Documentation

Write about this on the guides to atmospherics and the supermatter engine.

# Changelog

:cl:  
rscadd: adds nitrous oxide decomposition
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Why doe

**Comment by maxion12345** [comment]
someone years ago decided to not add this and we're probably going to figure out why

I love it let's fuck around and find out

**Comment by JamieD1** [comment]
Need to make sure this works with Auxmos

**Comment by stwordcitizen** [comment]
uneeded atmos is fine as it is

**Comment by Altoids1** [comment]
> Need to make sure this works with Auxmos

Does this even work with the current monstermos that's on master?

**Comment by SapphicOverload** [comment]
> Does this even work with the current monstermos that's on master?

Yes

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
