### PR TITLE
ports "Light Tiles use a Radial Menu and other tweaks #50703" from TG

### PR DESCRIPTION
**Pull request by Jumps0**
### Intent of your Pull Request

Some nifty tweaks for light tiles. They now use a screwdriver to select their color (with a radial menu). AI can also change the colors.

Credit to **RaveRadbury** for the original coding. +A little tweaks from me

BkkLZCArAn

#### Changelog

:cl:  RaveRadbury & Jumps
tweak: Light tiles now use a radial menu for color selection.
tweak: Light tiles need screwdrivers to be adjusted
tweak: AI can adjust the color
imageadd: adds/replaces a few light tiles from TG
/:cl:

### CODE REVIEW

**Comment by Jumps0** [comment]
inb4 turdis map error

**Comment by Jumps0** [comment]
based

**Review by Hopekz — APPROVED** [review]

**Review by alexkar598 — CHANGES_REQUESTED** [review]
The ai cant change the color this way, also I'd rather have it on screwdriver, light tiles are a fun harmless thing to add in greytide base and not every greytide has a multitool

**Comment by Jumps0** [comment]
> The ai cant change the color this way, also I'd rather have it on screwdriver, light tiles are a fun harmless thing to add in greytide base and not every greytide has a multitool

Huh didn't know AI could do that. I think that should be in my coding ability to tweak.

**Pull request merged**
