### PR TITLE
[admin] Takes the pod spawn code from TG

### LINKED ISSUE #11540: Pod's ripping the wires apart
### Severity

Inconvenience

### Short Description

The contractor's extraction pod will take everything on the tile with it. This includes wires, pipes and terminals.

### Reproduction

1. Get kidnapped by contractor
2. Contractor calls their extraction pod
3. Get shoved in the extraction pod
4. Watch in awe as the wires on the tile the extraction pod was on follows you into the dojo

### Round ID

Round #35544

### Test Merges

#11464, #11139, #11505, #11425

### BYOND Username

Darkstick

### Additional information

problem

Those wires shouldn't be there.

### LINKED ISSUE #11606: Reverse mode pick dropoff location on supply pod menu not implemented
## Test Merges: 
Not Supplied / None
## Reproduction:
The Pick Dropoff Location button is supposed to allow you to define the location in which a reversed pod will drop its payload, however, the button has no implementation.
 Submitted by: adamsogm (177073258716200961)

### PR DESCRIPTION
**Pull request by adamsong**
# General Documentation

### Intent of your Pull Request

TG made a better pod UI than the one we are currently stealing from them, so I stole that one. The [original pr](https://github.com/tgstation/tgstation/pull/52611) has a list of the features, but in general, it just allows for better podminning.

### Why is this change good for the game?

Podmins need more power, also reverse mode doesn't break everything anymore.

# Changelog
Fixes #11606 
Fixes #11540 
:cl:  
rscadd: Added pod UI from TG
imageadd: Added the TG pod textures
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
heheh. you're a podmin now, i'm proud

**Comment by adamsong** [comment]
Finally its green, Someone should probably test to make sure contractors work, I don't know how to test that solo

**Comment by adamsong** [comment]
I have confirmed contracts don't work any more, investigating the cause

**Comment by adamsong** [comment]
At this point I have tested:
 - Pod spawn menu
 - Quick pod smite
 - Podspawn
 - Express console (Regular and upgraded)
 - Choice beacons (Instrument, armaments, and hero)
 - Drive by landing station trait
 - Contractors
 - Stray cargo pod
Unless there is a source of pods in game that I am missing I think this is safe to be test merged

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
