### PR TITLE
new HUD: detective UI HUD from TG

### PR DESCRIPTION
**Pull request by tattax**
ports https://github.com/tgstation/tgstation/pull/74459

# Document the changes in your pull request

exaggerated swagger

image

looks cool as shit

:cl: kinneb
rscadd: detective UI HUD!
/:cl:

### CODE REVIEW

**Comment by ChuChu42** [comment]
exaggerated swagger

**Comment by Skrem7** [comment]
👀

**Review by cuackles — APPROVED** [review]
the is a good bit amount of banding but it isnt horribly offputing and it looks pretty good even with that so ye, maybe will retouch it later

**Comment by cuackles** [comment]
wont merge cus needs a code review just in case

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
