### PR TITLE
Revert "Stops Supermatter Shards being spawned in the bluespace locker.."

### PR DESCRIPTION
**Pull request by Cartlord**
Reverts yogstation13/Yogstation#17463 because it was a selfmerged change nobody wanted

### CODE REVIEW

**Comment by iamthesilly** [comment]
good pr

**Comment by Moltijoe** [comment]
wait till tomorrow

**Comment by Cartlord** [comment]
my mistake for not waitin'

**Comment by JamieD1** [comment]
If you want to bring this back you need a way of unlivable bluespace lockers not instakill with 20 anomalies in there.

Otherwise its not coming back, that is stupid im sorry.

**Comment by Moltijoe** [comment]
> If you want to bring this back you need a way of unlivable bluespace lockers not instakill with 20 anomalies in there.
> 
> Otherwise its not coming back, that is stupid im sorry.

how often is it realistically done for a funny gimmick like this to be removed?
Not only does it rely on finding the bluespace locker, but also ordering a supermatter shard from cargo
problem is, it also kills the funny gimmick of making a fully sustained supermatter shard inside a bluespace locker

If anything must be done, have opening and closing a bluespace locker's door transfer atmos too, that way it's a bit easier to tell when the atmos inside is fucky

**Comment by UltraBigRat** [comment]
there are already many many other ways to make locker killboxes seeing as it lets you get people in a construction of your choosing by just walking in a locker, there really is no need to self merge something (that nobody agreed with) like this because you died and got salty bout it once. Especially with the difficulty of doing it needing a rare item (locker) and ordering a supermatter from cargo and opening it.

**Comment by ToasterBiome** [comment]
> If you want to bring this back you need a way of unlivable bluespace lockers not instakill with 20 anomalies in there.
> 
> Otherwise its not coming back, that is stupid im sorry.

What if SMs will only create anomalies up to a certain density of them

**Comment by ThatLing** [comment]
>how often is it realistically done for a funny gimmick like this to be removed?

If it's not done often, why do you care it got removed?

**Comment by iamthesilly** [comment]
Because it prevents other fun things you can do like build a working supermatter engine in the locker that DOESN'T kill people

**Comment by MajManatee** [comment]
Removing it felt AWFULLY hugboxy. If somoene wants to make an SM inside a locker, let them.

**Review by MajManatee — APPROVED** [review]
its only logical jamie

**Comment by Moltijoe** [comment]
Yeah, i'm merging this, even though Jamie is "technically" the only person that is allowed to merge reverts, the original PR shouldn't have been merged in the first place.

**Comment by JamieD1** [comment]
Bruh

**Pull request merged**
