### PR TITLE
Toolbelt can now hold cable cuffs

### PR DESCRIPTION
**Pull request by Hopekz**
Another oversight?

You're telling me that if I fold/tie my cables there is now a forcefield around my belt that rejects the cables I folded?

image

#### Changelog

:cl:  Hopek
rscadd: Toolbelt can now hold cable cuffs
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Sounds like powercreep
Shouldn't be using toolbelts for cuffs

**Comment by Hopekz** [comment]
> Sounds like powercreep
> Shouldn't be using toolbelts for cuffs

Powercreep on what job?
The cable ties are made by engineering with the cables they literally spawn with.
Sec doesn't make cable ties because they have zip ties and handcuffs.

**Comment by Bibby0110** [comment]
> > Sounds like powercreep
> > Shouldn't be using toolbelts for cuffs
> 
> Powercreep on what job?
> The cable ties are made by engineering with the cables they literally spawn with.
> Sec doesn't make cable ties because they have zip ties and handcuffs.

Did you just upvote your own PR?

Yeah Engineering has no business making and storing cable cuffs unless they're antags, and in that case they should store them in their pocket or backpack, not a fucking toolbelt

**Comment by Jarod1200** [comment]
if you do this maybe zip ties should fit too

**Comment by Hopekz** [comment]
> Did you just upvote your own PR?

Yeah I support this change

> Yeah Engineering has no business making and storing cable cuffs unless they're antags, and in that case they should store them in their pocket or backpack, not a fucking toolbelt

So why not just make crafting cable ties antag only?
Your logic is flawed. You're acting like non-antags won't make these because they magically need to know not to even though the game lets them?

**Comment by Bibby0110** [comment]
> > Did you just upvote your own PR?
> 
> Yeah I support this change
> 
> > Yeah Engineering has no business making and storing cable cuffs unless they're antags, and in that case they should store them in their pocket or backpack, not a fucking toolbelt
> 
> So why not just make crafting cable ties antag only?
> Your logic is flawed. You're acting like non-antags won't make these because they magically need to know not to even though the game lets them?

Yeah you made the change

Sometimes non antags need cable ties.
They shouldn't be running around with them though.

**Comment by Hopekz** [comment]
> Yeah you made the change

Yes, Gamer I'm literally the author of this PR. 
If anyone else made it I'd credit them.

> Sometimes non antags need cable ties.
> They shouldn't be running around with them though.

Make up your mind and come back to this PR once you are not on both sides of the fence.
image

**Comment by Bibby0110** [comment]
> > Yeah you made the change
> 
> Yes, Gamer I'm literally the author of this PR.
> If anyone else made it I'd credit them.
> 
> > Sometimes non antags need cable ties.
> > They shouldn't be running around with them though.
> 
> Make up your mind and come back to this PR once you are not on both sides of the fence.
> image

Do you need me to explain it 1 by 1 for you?
Engineering shouldn't be running around with cable ties, therefor their belt shouldn't store them.
Sometimes they need cable ties, but they can make them with the cable in their belt because they shouldn't just be running around with them.

**Comment by Hopekz** [comment]
> > > Yeah you made the change
> > 
> > 
> > Yes, Gamer I'm literally the author of this PR.
> > If anyone else made it I'd credit them.
> > > Sometimes non antags need cable ties.
> > > They shouldn't be running around with them though.
> > 
> > 
> > Make up your mind and come back to this PR once you are not on both sides of the fence.
> > image
> 
> Do you need me to explain it 1 by 1 for you?
> Engineering shouldn't be running around with cable ties, therefor their belt shouldn't store them.
> Sometimes they need cable ties, but they can make them with the cable in their belt because they shouldn't just be running around with them.

Yes please explain. Your logic does not make sense to me.

How does this encourage engineers to run around with them?
They literally carry cable which becomes these cuffs. 
Every engineer spawns with 2 cable cuffs they just need to use the action button on it.
If anything this discourages it because you can now carry LESS.

Right now as an engineer if I need to cuff someone it is just the Z button + clicking or pressing enter.

**Comment by Bibby0110** [comment]
> > > > Yeah you made the change
> > > 
> > > 
> > > Yes, Gamer I'm literally the author of this PR.
> > > If anyone else made it I'd credit them.
> > > > Sometimes non antags need cable ties.
> > > > They shouldn't be running around with them though.
> > > 
> > > 
> > > Make up your mind and come back to this PR once you are not on both sides of the fence.
> > > image
> > 
> > 
> > Do you need me to explain it 1 by 1 for you?
> > Engineering shouldn't be running around with cable ties, therefor their belt shouldn't store them.
> > Sometimes they need cable ties, but they can make them with the cable in their belt because they shouldn't just be running around with them.
> 
> Yes please explain. Your logic does not make sense to me.
> 
> How does this encourage engineers to run around with them?
> They literally carry cable which becomes these cuffs.
> Every engineer spawns with 2 cable cuffs they just need to use the action button on it.
> If anything this discourages it because you can now carry LESS.
> 
> Right now as an engineer if I need to cuff someone it is just the Z button + clicking or pressing enter.

It allows them to, for no reason at all.

Yeah it sounds like it's not an issue that zipties can't go on belt. I'm not sure what the perk of allowing these in belts are, other than encouraging engineers to carry items they shouldn't?

**Comment by Hopekz** [comment]
> Yeah it sounds like it's not an issue that zipties can't go on belt. I'm not sure what the perk of allowing these in belts are, other than encouraging engineers to carry items they shouldn't?

The reason is immersion. 
I can put cables in my toolbelt but if I tie them or fold them there is now a forcefield around my belt that rejects the cables I folded.

Literally only reason I made this PR because it was "out of place" and doesn't make sense a.k.a "an oversight" in continuity

**Comment by Bibby0110** [comment]
> > Yeah it sounds like it's not an issue that zipties can't go on belt. I'm not sure what the perk of allowing these in belts are, other than encouraging engineers to carry items they shouldn't?
> 
> The reason is immersion.
> I can put cables in my toolbelt but if I tie them or fold them there is now a forcefield around my belt that rejects the cables I folded.
> 
> Literally only reason I made this PR because it was "out of place" and doesn't make sense a.k.a "an oversight" in continuity

Immersion doesn't matter. This is a game, not a simulation of life.

Yeah, toolbelts aren't made to fit folded zipties / cable cuffs, simple as that

**Comment by JamieD1** [comment]
Unfortunately have to agree, this would encourage assistants and engineers to always have cuffs on them.. takes away the negative of having to either make them or have a backpack space gone. More of a balance thing.

**Comment by Hopekz** [comment]
> Yeah, toolbelts aren't made to fit folded zipties / cable cuffs, simple as that

Yes; this is what this PR is fixing.

**Comment by Bibby0110** [comment]
> > Yeah, toolbelts aren't made to fit folded zipties / cable cuffs, simple as that
> 
> Yes; this is what this PR is fixing.

That's not what we mean Hopek, and you know that

**Comment by Hopekz** [comment]
> Unfortunately have to agree, this would encourage assistants and engineers to always have cuffs on them.. takes away the negative of having to either make them or have a backpack space gone. More of a balance thing.

Making cuffs isn't a negative. 
Its pressing Z then pressing enter. 
Sometimes you can do these inputs faster than the UI loads and it looks like you're seamlessly pulling out cuffs

**Comment by Hopekz** [comment]
> Immersion doesn't matter. This is a game, not a simulation of life.

Lots of things in our game are modeled to behave realistically for immersion. We remove immersion-breaking features when they don't behave the way you would expect them to.
In this case, it is not having a forcefield around your toolbelt that rejects the cable once you fold it.

**Comment by Moja10** [comment]
Imagine arguing like that over a PR like this

**Comment by Hopekz** [comment]
> Imagine arguing like that over a PR like this

 Happens all the time when anything changes that could affect balance no matter how small or seemingly insignificant that balance impact may be

**Comment by Partheo** [comment]
It makes realistic and thematic sense and literally no one is going to think their round was ruined because "damn, if only that engineer wasn't able to put cablecuffs in their belt"

SS13 is unbalanced and chaotic, I think this is fine

**Comment by Jarod1200** [comment]
Most engineers probably wouldn't make them into cuffs until there is a good reason to because 30 cables cuffs is 1 small item . 1 cuff and 15 cables takes up 2 slots and 2 cuffs also takes up 2 slots. You loose utility by committing to the cable cuffs instead of the regular cables so if they end up needing cables for construction they have to go find or make some.

**Comment by alexkar598** [comment]
Encourages validhunting and powergaming, no.

**Pull request closed without merging**
