### PR TITLE
Adds meson sunglasses, makes the CE spawn wearing a pair

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

Adds Meson Sunglasses, and the ability to craft them, and also makes the CE spawn wearing some

Crafting recipe: 5 cables, 1 pair of sunglasses, 1 pair of meson scanners

This is tested

# Wiki Documentation

Probaby something on engi equipment or miner

# Changelog

:cl:  
rscadd: Adds meson sunglasses
rscadd: Adds a crafting recipe for meson sunglasses
imageadd: Added sprites for meson sunglasses
tweak: the CE now spawns with meson sunglasses
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
chrome_d0ODmR7gtf
chrome_4bhAxmbof6

**Comment by Cartlord** [comment]
Consider that QM will also likely end up with these, since Shaft Miners get a lot of Mesons. Is that something we want?

**Comment by N3D6** [comment]
> Consider that QM will also likely end up with these, since Shaft Miners get a lot of Mesons. Is that something we want?

QM gets sunglasses anyway, they could do it with literally ANY other HUD

**Comment by ToasterBiome** [comment]
> Consider that QM will also likely end up with these, since Shaft Miners get a lot of Mesons. Is that something we want?

Seems fine with me, meson sunglasses seem literally the most useless out of the sunglasses + hud combination besides the diagnostic ones. He could right now hassle a miner to buy them the medical hud one and craft that one too.

It's really weird that every head except CE gets sunglasses, and meson sunglasses were the only ones missing.

**Comment by Moggram** [comment]
Why has this not been done before?

**Comment by Bibby0110** [comment]
Powercreep

**Comment by Moggram** [comment]
> 
> 
> Powercreep

What if it was T-ray?

**Comment by LazennG** [comment]
whats wrong with this pr i dont get it

**Comment by JamieD1** [comment]
Why the downvotes. Dont get it.

**Comment by patpol4** [comment]
powercreep

**Comment by Cartlord** [comment]
Also because meson shades are dumb as shit, since mesons - as I understand it - work by picking up MORE light frequencies (as they let you see through walls)

**Comment by ToasterBiome** [comment]
> Also because meson shades are dumb as shit, since mesons - as I understand it - work by picking up MORE light frequencies (as they let you see through walls)

I don’t see why a device capable of detecting more light frequencies wouldn’t also be able to work through sunglasses. IRL only filter out part of the rays anyway. 

Also that’s a terrible explanation as the function was probably made first and then an in universe explanation was thought up

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
