### PR TITLE
Lets preterni recharge off other robotic species

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
They can steal power from mechs, borgs, you name it, what's one more robot

:cl:  
rscadd: Preterni can recharge using other electricity using species
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
can a hungry enough preternis kill an IPC?

**Comment by Moltijoe** [comment]
> can a hungry enough preternis kill an IPC?

nah, just enough to bring the target to starving, it won't bring them down to 0
and since preterni only get /2 the power they drain, they will need two people to fully charge

**Comment by Yarinoi** [comment]
third preternis martial based off this ability where they feed off the charge of literally any living creature when?

**Comment by Moltijoe** [comment]
> third preternis martial based off this ability where they feed off the charge of literally any living creature when?

an ethereal electricity based martial would be more thematic

**Comment by KingSuperBOB** [comment]
Is the drain large enough to be used to suicide rush mechs

**Comment by Moltijoe** [comment]
> Is the drain large enough to be used to suicide rush mechs

If the mech stands still long enough for a preternis to drain, thats a skill issue

**Comment by KingSuperBOB** [comment]
> > Is the drain large enough to be used to suicide rush mechs
> 
> If the mech stands still long enough for a preternis to drain, thats a skill issue

A mech requires to stand still to fix the movement error

**Comment by Moltijoe** [comment]
> A mech requires to stand still to fix the movement error

Theres a mech movement bug?

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
