### PR TITLE
Raises heretic weight

### PR DESCRIPTION
**Pull request by ynot01**
Heresy is too rare

People struggle with even the basics and need to learn this gamemode properly

Needs more balance focus aswell

4 -> 6

### CODE REVIEW

**Comment by Simplehorror** [comment]
heretic is an awful gamemode

**Comment by Maia-J** [comment]
> heretic is an awful gamemode

Yes, because we don't have the option to play it enough to learn it

**Review by MajManatee — APPROVED** [review]
I like being a heretic
except i always get caught within 30 seconds

**Review by Moltijoe — APPROVED** [review]
iirc, was it sacrificing a headless body round removes the target?
that should probably be fixed at some point
either way, heretic is cool

**Comment by The-Sun-In-Splendour** [comment]
> heretic is an awful gamemode

heretic is one of the best gamemodes

**Comment by Bibby0110** [comment]
Me and Jamie are going to look at all the gamemode weights soon
we will keep this in mind and bump up heretic a bit

**Comment by thegoldencat413** [comment]
> 

arent you biased CONSIDERING your username is one of the hours

**Pull request closed without merging**
