### PR TITLE
Nerfs Embryo

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

Here's your fucking nerf.

#### Changelog

:cl:  
tweak:  The Xeno Embryo growth has now been stunted, along with making it more annoying to have while reducing damage that it deals.  

/:cl:

### CODE REVIEW

**Comment by Kmc2000** [comment]
Wow, just WOW this is amazing. I can't actually believe that I am lucky enough to have been born in time to see this fantastic PR, better yet, old enough to understand its far reaching implications.
This idea is truly inspired, nerfing the embryo? It's daring, it's bold, it's true genius. 
Examples like this are what makes me happy that yog desync'd from /tg/ station's stale, stagnating pool. The real talent is right here -- applying nerfs for the people, requested by the people, rather than nerfing popular game mechanics on a whim.

I am truly thankful that you made this, and cannot wait to see it merged.
My rating: 3/5 stars.

**Review by alexkar598 — APPROVED** [review]

**Comment by alexkar598** [comment]
Shitty pointless PR,leave the Xenos alone

**Comment by ghost** [comment]
Blame Cidle for making me do this.

**Comment by HomocidlePancakes** [comment]
>Blame Cidle for making me do this

The sheer amount of ridiculousness coming from this sentence made my morning.

**Comment by ghost** [comment]
> I am still waiting on thouse other changes you mentioned before (implying you even thought up any lol)

You brought this on yourself.

**Pull request closed without merging**
