### PR TITLE
You can now only heal so much per second

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Say goodbye to heal-stacking, now you can't combine meds/nanites/virus/whatever to become an unkillable monster

# Spriting

# Wiki Documentation

You can now only heal so much per second now - add to chemistry page
# Changelog

:cl:  
tweak: You can now only heal so much per second
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Funny

**Comment by Maia-J** [comment]
This just buffs damage mixes whilst nerfing everything else.

**Comment by Simplehorror** [comment]
> This just buffs damage mixes whilst nerfing everything else.

you're not meant to outheal "damage mixes", purge them and heal

**Comment by Bibby0110** [comment]
I’m going to assume this is a meme PR

**Comment by Simplehorror** [comment]
it's not, reopen @TheGamerdk

**Comment by Simplehorror** [comment]
actually i'll just reopen it

**Comment by JamieD1** [comment]
Both of you stop pissing on each other.

**Comment by ynot01** [comment]
soft cap > hard cap, also you need to make sure this doesn't apply to admin tools

**Comment by Marmio64** [comment]
5 is too low

**Comment by Rdrazga** [comment]
Time for cryo to stop working

> 5 is too low

Sir you don't realize, this isn't 5 per tick, this is 5 per SECOND. So yes it is way too low and even if it wasn't too low this is a horrible way to do what this is trying to achieve.

**Comment by Simplehorror** [comment]
> soft cap > hard cap, also you need to make sure this doesn't apply to admin tools

ok i make it so force ignores the cap

**Comment by Simplehorror** [comment]
what i can do is make it so healing rolls over it spreads over time

**Comment by Moltijoe** [comment]
ah, 24 hours have passed now

**Comment by Bibby0110** [comment]
Don’t close this

**Comment by Bibby0110** [comment]
I want to close it

**Comment by JamieD1** [comment]
Fuck sake.

**Pull request closed without merging**
