### PR TITLE
The Syndicate Dreadnought - the Nuclear Operative base is now styled to be like a battlecruiser

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Redesigns the interior of the Syndicate base to feel more like a large mothership which the area name implies - using fake multi-Z effects borrowed from Shiptest's mappers that (probably) won't break.

# Wiki Documentation

Nukie base layout may need changes.

# Changelog

:cl:  
mapping: I fucked around with the nukie base and it looks like a ship now, layout should be the same mostly
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Looks cool, nice to see a change

**Review by Aquizit — CHANGES_REQUESTED** [review]
Bunch of doors missing their proper req_access_txt
Buttons for the fuel door also needs access set.

image
Not sure if this is still supposed to be here if the outpost is to be in space now.

image
Do these doors have an access button?

Also an exit that normal syndies can use to get to the little room near the lower bit of the hanger. As if the ship is docked there's no way to get into the hanger directly. Except for going through the nukie commander's bedroom which I assume is not wanted.

**Comment by Addust** [comment]
nukie commander shutters are WINDOW SHUTTERS

**Comment by Aquizit** [comment]
windows right ok

**Comment by Aquizit** [comment]
image
image
image

All the doors pictured are still missing access.

---

image

These buttons are also missing access but I don't necessarily have a problem with that for that little room in the hanger. Little bonus area I suppose. But you can put it in if you want.

**Comment by Aquizit** [comment]
Stale. Closing tomorrow morning if no comment or commit made.

**Comment by Addust** [comment]
shit lemme do that

**Comment by Aquizit** [comment]
Reopening like I said I would.

**Comment by N3D6** [comment]
What is this “fake multiz” you speak of? Have you actually tested it live to make sure it ISNT broken?

**Comment by Addust** [comment]
> What is this “fake multiz” you speak of? Have you actually tested it live to make sure it ISNT broken?

the lattice thing, its just some special effects bullshit shiptest invented that im stealing, does it identically to how they do it. it will work

**Review by Aquizit — APPROVED** [review]

**Pull request merged**
