### PR TITLE
moves the magic mirror/some wizards a bit, removes some loot from the academy leader or whatever room and gives wizards boss level sentience

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
tweak: Magic mirror is now inside the bathroom instead of the room-that's-supposed-to-spawn-a-ghost-role-but-doesn't
tweak: mirror in the room-that's-supposed-to-spawn-a-ghost-role-but-doesn't is a normal mirror
tweak: moved colburn out of a room that's completely useless and never used to the hallway near the bathrooms
tweak: moves bowl into the bathroom from the room that's completely useless and never used
tweak: removes stupid shit from the room-that's-supposed-to-spawn-a-ghost-role-but-doesn't since it's a fireball staff and antimagic suit which is dumb to get without even fighting a single wizard
tweak: wizards now have boss level sentience and therefore can't be yeeted as easily
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
This doesn’t fix the fact they aint atmosproof

**Comment by Jarod1200** [comment]
Making them atmos proof was a different pr

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Undocumented mapping changes

**Comment by SomeguyManperson** [comment]
Fixed

**Pull request merged**
