### PR TITLE
Blood tomato now has 20% bloody mary production trait

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Blood tomato now has 20% bloody mary production trait

# Why is this good for the game?
Good to have in bloody tomato, can be combined with other plant genes to make a good healing plant for some people.

# Testing
Ran a local test, worked even tho this doesnt have to be tested it but i did anyway

# Wiki Documentation
Update guide to plants document of changes

# Changelog

:cl:  

tweak: Blood tomato now has 20% bloody mary production trait
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
bloody mary can be easily made and distilled so it wont be a problem to have this as a trait

**Comment by SomeguyManperson** [comment]
image
it's already a distill result from the exact plant you are adding it as a reagent to, what's the point

**Comment by ShoziOffical** [comment]
> 

the point is to have it as a trait, you cannot add reagent into plant without trait

**Comment by Moltijoe** [comment]
what's the purpose of it being bloody mary? if you want it to restore blood, then give it iron, making it bloody mary makes it kill podpeople

**Comment by ShoziOffical** [comment]
> what's the purpose of it being bloody mary? if you want it to restore blood, then give it iron, making it bloody mary makes it kill podpeople

bloody mary can restore blood fast, faster than iron for other species, well if you are podpeople the botanist will just seperate a new plant only for them that isnt a bit of a deal

**Comment by ShoziOffical** [comment]
After all this can be easily made already so a small change to this wont impact much into one round

**Comment by MajManatee** [comment]
If this can be made easily already, then why is it needed?

**Comment by ShoziOffical** [comment]
> If this can be made easily already, then why is it needed?

i literally stated above please read my comment, the point is to have it as a trait

**Comment by Moltijoe** [comment]
Balance council:
>it already distills into bloody mary.
It also already contains blood in it

**Comment by ShoziOffical** [comment]
> Balance council:
> 
> > it already distills into bloody mary.
> > It also already contains blood in it

the blood trait is fairly useless since medical can already duplicate blood, distilling is one thing and having it as a trait is another thing

**Pull request closed without merging**
