### PR TITLE
Medical Crafting Update (+New Ointment & Ghetto Sutures)

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Adds a Medical crafting tab
moves the autoinjector recipes to the new tab
Allows you to craft sutures, medicated sutures, regenerative meshes, and advanced meshes, as well as normal gauze, and ointment
adds new Antiseptic Ointment, which is very bad (worse than normal ointment) at healing burns, but, is far better at sterilizing burns to stop infections
adds Makeshift Sutures which are less effective than emergency sutures, but cost torn cloth, a glass shard, and some water
Crafting recipes are as follows
changes the grind results of most medical stack items

Suture
- 1 cloth
- 1 metal
- 4u Sterilizine

Makeshift Suture
- 1 torn cloth
- 1 glass shard
- 4u water

Medicated Suture
- 2 plastic
- 1 metal
- 6u Sterilizine
- 5u Morphine

Regen. Mesh
- 2 improvised gauze
- 1 glass
- 7u Sterilizine
- 3u morphine

Advanced Mesh
- 2 improvised gauze
- 1 glass
- 10u Sterilizine
- 3u morphine
- 10u Silver Sulfadiazine

Ointment
- 1 waterbottle
- 10u ash
- 15u lenturi

Antiseptic Ointment
- 1 waterbottle
- 10u ash
- 15u sterilizine

Gauze
- 4 cloth
- 1 suture

# Spriting

ss (2022-09-16 at 02 02 52)

# Wiki Documentation

cant find any pages that mention ointment directly, even the redirect for the medical page doesn't have it.
also unsure if we even have a crafting page in general?

# Changelog

:cl:  
rscadd: You can now craft sutures/mesh/gauze/ointment
rscadd: added antiseptic ointment, made for quickly tending infections from burns
rscadd: added makeshift sutures, made from torn cloth and glass with some water
tweak: Nanomeds no longer contain Sutures, but do have 4 antiseptic ointment
tweak: Added a new Medical crafting tab and moved the autoinjector recipes there
tweak: some stacked medical items now grind for sterilizine instead of spaceacillin
tweak: burn kits now contain antiseptic ointment
tweak: ointment is now a repeating-use item
imageadd: added green suture sprites, and a yellow ointment bottle
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
this is a very good pr but why remove sutures from nanomed that seems kinda unneeded

**Comment by VaelophisNyx** [comment]
there was only 2, but you can now make them fairly easily so, not much reason to bloat the contents of it much.

**Review by KillerOrcaCora — APPROVED** [review]
meep

**Comment by boodaliboo** [comment]
> there was only 2, but you can now make them fairly easily so, not much reason to bloat the contents of it much.

fair enough

**Pull request merged**
