### PR TITLE
*scream and adds preternis scream

### PR DESCRIPTION
**Pull request by nesisknesis**
Source: https://forums.yogstation.net/index.php?threads/screams.19329/#post-164165

*scream

#### Changelog

:cl:  
tweak: Using the *scream emote will make you audibly scream.  
soundadd: Preternis now have a unique scream. 
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Do plasmamen have their own? I have never really paid attention

**Comment by nesisknesis** [comment]
No, plasmamen, ethereals, and podmen do not have their own screams. If you can suggest any ill see about adding them.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
Could we add a cooldown so you can't spam the sound?

**Comment by HomocidlePancakes** [comment]
Could we not add a couldown so you can spam the sound?

**Comment by nesisknesis** [comment]
after playing a round of goon i regret opening this

**Pull request closed without merging**
