### PR TITLE
Actually Actually Fixed Mecha Wreckage

### LINKED ISSUE #3372: Free miner mech wreck won't contain enough parts to build another mech
I've had multiple complaints about this, probably has something to do with the wreckage still rolling rods/plasteel/metal sheets

### PR DESCRIPTION
**Pull request by ThatLing**
Fixes #3372 
Closes #3395

### CODE REVIEW

**Comment by Cruix** [comment]
Cool. 20 is pretty high, but the engi would have to be pretty stupid to burn all the salvage on that. You should new() the boards so they are actually retrievable.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
what cruix said I guess

**Comment by ThatLing** [comment]
salvage_num is the total amount of times you can salvage the wreck and there's a 70% chance you'll fail to retrieve anything. Boards are already new'd in ``/obj/structure/mecha_wreckage/attackby``.

**Comment by Cruix** [comment]
Crowbar salvage is not new()'ed on tg code, it expects an instantiated object.

**Pull request merged**
