### PR TITLE
Brig cell timers adjustment

### PR DESCRIPTION
**Pull request by Ktlwjec**
This is for a council thing I'm sorry.

:cl:  
tweak: Brig cell default timer lengths are now slightly higher.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Link vote

**Comment by thehighwayman** [comment]
takes forever for those council folk to finish their votes. I say we set this to controversial and listen to further discussion from the coders

**Comment by ThatLing** [comment]
>listen to further discussion from the coders
>PR literally just changes some numbers

**Comment by ShadowDeath6** [comment]
why is a council vote needed if it’s just numbers

**Comment by Ktlwjec** [comment]
It's for a council project and vote was the best tag I could find, so we can have it all ready to merge when/if it's needed

**Pull request merged**
