### PR TITLE
De Ligma

### PR DESCRIPTION
**Pull request by LoliconSlayer**
I dont like references in the game.

# Wiki Documentation

Is this machine even on the wiki?

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
tweak: Removed a ligma joke
/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
sad

**Comment by 00ze-cyclone** [comment]
oh wait nvm it still got a cool acronym

**Comment by MonsWTF** [comment]
Was put in the text in the original LAM PR: https://github.com/yogstation13/Yogstation/pull/9608

As original PR dude, am perfectly fine with this being changed. 

Wish I had time to put more into LAM and other Science/Mining doodads. One day.

**Comment by Tipy1802** [comment]
Pretty lame ngl. Jokes like these are what gives the game it's character 
image

**Comment by Tipy1802** [comment]
Like seriously what even is the issue with it? In game description are usually filled with refrences and jokes. Actually whole items and gamemodes are refrences in ss13. It's charming

**Comment by Marmio64** [comment]
its so sad that loliconslayer died of ligma...

**Comment by ShadowDeath6** [comment]
could have at least made it into an LMAO joke

**Comment by LoliconSlayer** [comment]
> could have at least made it into an LMAO joke

Good idea

**Comment by JamieD1** [comment]
Because apparently PRing shit is funny now. Make up your damn mind.

**Pull request closed without merging**
