### PR TITLE
Toxins/Testing Lab remap (Yogbox!)

### PR DESCRIPTION
**Pull request by Ktlwjec**
#2622 Does the majority of changes in this PR, everything except pipe rearrangements.
In doing so Science had too many freezers and heaters so I just decided to redo the entirety of southern Science. Maint looks cute on the right also.
There are two vents in toxins there because Nich screeched about his pipes going through walls.

image

:cl:  
rscadd: Toxins and testing lab has been changed around.
/:cl:

### CODE REVIEW

**Comment by thehighwayman** [comment]
I love it

**Comment by Ktlwjec** [comment]
im an ok mapper now ive moved up the ranks

**Comment by Nickvr628** [comment]
I dislike the teleporter testing space being gone, it was good for making various projects since it was a lot of open space.

**Comment by Amelia0010** [comment]
it's not gone though?

**Comment by Amelia0010** [comment]
image
🤔 pipe going through girder detected. Pipe-ocracy is non-negotiable

**Comment by Ktlwjec** [comment]
excuse me nich girders are not walls

**Comment by Amelia0010** [comment]
still terrible tho :^)

**Comment by Amelia0010** [comment]
lol merge conflicts

**Comment by thehighwayman** [comment]
merge bad man

**Comment by Ktlwjec** [comment]
omg WHAT IS WRONG WITH IT

**Comment by thehighwayman** [comment]
don't scream it worked

**Pull request merged**
