### PR TITLE
Revert "Removes felinid language"

### PR DESCRIPTION
**Pull request by ReddicusDragon**
Reverts yogstation13/Yogstation#17825

I FINALLY FOUND THE BUTTON

Reason: to bring back a feature players preferred was in the game
# Changelog
:cl:  
rscadd: Felinid language has been forcibly added to every nook and cranny of history, including native speakers' brains where it was previously.
/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]

**Comment by Moltijoe** [comment]
"Xantam once said that donor features should not give a material benefit for donors. Felinids having a meta language seems like a material benefit."

**Comment by ToasterBiome** [comment]
> "Xantam once said that donor features should not give a material benefit for donors. Felinids having a meta language seems like a material benefit."

Cat ears give Felinid language. Multilingual also (used to). There's no material benefit nor is it utilized in the same way as other race languages (like a lizard metagang for example). Xantam has seen Felinid language and approved of it from a donator standpoint.

You are making up reasons because you get your enjoyment through the removal of enjoyment of others.

**Comment by Cartlord** [comment]
You're correct, I get joy from the suffering of furries with money. Why shouldn't I?

**Comment by cuackles** [comment]
Ok I'm really tired of the " material benefit " argument cus it's bullshit, the felinid language it's not a benefit, every fucking race has its own language, every race can communicate with its own poeple, if the issue is poeple forming meta groups and exclusively talking in cat that's a player issue of metafriending and it should be addressed by the admins, and it's not like that it's exclusive to cats as we have had that issue a lot with lizards too, cats are a lot less people so if they bunch up it's a lot more notable due to quantity of them, the cat language can be understood by cats and poeple with cat ears, while the other race language can be only understood by same race or with external stuff like the book of babel or being a librarian, so it is not a benefit, the point that the language they got they got by spending money also doesn't make sense cus if they didn't play cat they would still have other languages for them to talk with the same race,cat language is literally just like any other language, except it's easier to be able to listen to it cus the cat ears head gear.
 the second argument of that it isnt lore friendly cus cat poeple are just humans with implants could be valid if it wasn't for the fact that lore can be changed and has been changed before, and also that there exists a lot of languages that have been made up like Klingon and elvish in the real world that didn't need the span of centurys to develop it also doesn't really matter if matter let's just say that cats are just fucking nerds that made their own language easy.
also for the love of god stop putting fetish content in any PR that has felinids on them, ifs you can only think of them in sexual ways that's ur own issue but like Christ people generally see them in a normal way.
We have donor so poeple can have extra stuff for supporting the server but we refuse to give them stuff that don't give them an advantage but just put them at the same point as the other races ???, Also how the fuck is a language an advantage, it's not like all cat people roll traitor together and they scheme in cat every round, it's just for fucking talking for the love of god.
If the issue is poeple making meta friends groups address that with admins don't take out an entire feature from all players, specially the players that gives us money

**Comment by Bibby0110** [comment]
48 hour rule

**Comment by Lichton** [comment]
every race has its own language... but catpeople aren't supposed to be their own race, just a swap of human. . .

**Comment by ToasterBiome** [comment]
48 hours have passed

**Comment by Bibby0110** [comment]
no they havent

**Comment by ToasterBiome** [comment]
Yes it has. It's been almost 51 hours.

**Comment by ThatLing** [comment]
Missing rationale

**Comment by ToasterBiome** [comment]
Not respecting contributing guidelines

**Comment by ThatLing** [comment]
Inadequate rationale

**Comment by YashinHak** [comment]
"felinids cant have their own language since they are just augmented humans" clearly the ears are magical since they gave people the ability to speak felinid

**Comment by MajManatee** [comment]
remove the ability for felinids to naturally understand the language, and make them spawn with a pair of cat ears in their backpacks, or equipped.

Also, if the players really "Perferred it" then why was the other PR so positively voted for? with literally 0 people opposed to it.

**Comment by ReddicusDragon** [comment]
> remove the ability for felinids to naturally understand the language, and make them spawn with a pair of cat ears in their backpacks, or equipped.

Fuck off

**Comment by Sniblet** [comment]
Someday I'll figure out why people get into such vicious fights every time felinids are brought up on the Github while they're fine everywhere else

**Comment by ToasterBiome** [comment]
> Someday I'll figure out why people get into such vicious fights every time felinids are brought up on the Github while they're fine everywhere else

people cannot live with others having fun

**Comment by JamieD1** [comment]
Firstly, I want to lay out my own personal opinion on this Pull request, I believe that meta cliques are unhealthy for the game and languages like this enable people to get in and isolate them away from others in a way we do not want to see. I believe this language is cringe and shouldnt be in the game, however the issue is, there are loads of other languages which peform the exact same role as this one, lizards have their own, species have their own etc.. Yeah we dont like missing out on whats being said, yes its annoying. I get it.

After thats been said, I do not see a reason to actually remove this from the game, it will not serve the intended purpose as stated by people above and people will just meta clique other ways instead. Also people are going to be cringe someway or another anyway, no point in trying to stop it, its a people problem not a feature problem.

Also to those saying its not lore accurate and they would be unable to speak that language, I agree. They shouldnt, but at the same time we as a human species have several languages just in our own dialect, hell we make some up like Klingon. I definately could see people making up a cringe uwu language and teaching it to others. As much as I think its stupid.

Therefore we will be adding this back into the game and it will be reverted to its previous state, there will be no more discussion about this and no more pull requests to remove this in the future. The only caveat to this would be if we removed all other clique languages, which we will probably never do but I can't predict the future. However is a council vote is pushed and is passed I will have no choice to abide by it. This is a line in the sand and its not fair we remove features for the sake of solving a problem which is unsolvable.

**Pull request merged**
