### PR TITLE
Deletes padded german coat.

### PR DESCRIPTION
**Pull request by nesisknesis**
# Document the changes in your pull request

Exists as a coat for the head of security. Sprite quality is poor but the main infraction is how out of place it is. Disregards the style of security and was pulled straight from Lebensraum (WW2 SS13 server) with little adaptation to the context of our server.

There are many other items that exist that I may PR to remove in future for similar reasons.

image

# Changelog

:cl:  Identification
imagedel: The padded german coat, an item for the head of security, has been removed for being totally out of place.
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
after careful consideration I've decided that the coat looks kind of cool and therefore this change is cringe and you are bad
-2
T:-2

**Review by Partheo — APPROVED** [review]
please remove more

**Review by JamieD1 — CHANGES_REQUESTED** [review]
I’m sorry, but removing one of the most popular coats that is used is really stupid, improve, don’t remove.

**Comment by MusselMain** [comment]
Gotta love removing this, but not spur boots, despite them being literally counterintuitive

**Comment by Partheo** [comment]
> Gotta love removing this, but not spur boots, despite them being literally counterintuitive

Remove them too

**Comment by Partheo** [comment]
> I’m sorry, but removing one of the most popular coats that is used is really stupid, improve, don’t remove.

Popular != Good for the game

**Comment by JamieD1** [comment]
Pending discussion with partheo and ident.

**Comment by Marmio64** [comment]
it fits perfectly with how cruel and evil security can be

**Comment by bruhlookatthisdood** [comment]
n

**Comment by cuackles** [comment]
Yeah we shouldn't have Nazi clothing in the server and stuff

**Comment by Anvilman6** [comment]
It's poorly sprited, it doesn't suit the server or the setting, and the connotations it carries aren't really something we want to preserve. 

Yogstation on the whole suffers A LOT from clothing bloat and outfits that either are exceedingly low quality, or are not suited to the server theme, so this seems like a simple way to cut it down a smidgen.

If the coat can be changed to something better sprited which is more suitable for the server, sure, someone can PR that. Otherwise, I understand Ident's stance, as the art lead, in removing it.

**Comment by JamieD1** [comment]
We can come back to this

**Pull request closed without merging**
