### PR TITLE
Adds "Home" By "Resonance" to lobby music

### PR DESCRIPTION
**Pull request by warface1234455**
# About PR
Adds Home by Resonance to lobby music so everyone can enjoy it
https://www.youtube.com/watch?v=8GW6sLrK40k

# Changelog

:cl:  
soundadd: Added "Home" By "Resonance"
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Why dont you put a link in the pr instead of making people have to go find it.

**Comment by warface1234455** [comment]
> Why dont you put a link in the pr instead of making people have to go find it.

It's in filechange but alright

**Comment by JamieD1** [comment]
> > Why dont you put a link in the pr instead of making people have to go find it.
> 
> It's in filechange but alright

Convenience mate.

**Review by JamieD1 — APPROVED** [review]

**Comment by warface1234455** [comment]
yes yes

**Pull request merged**
