### PR TITLE
Overhauls the space bartender ruin

### PR DESCRIPTION
**Pull request by MrHorizons**
Today on "Horizons overhauls ruins for no real reason", the space bar.

**Old:**
image

**New:**
image

Particular items are interest are:
- The space bartender not only spawning with their shotgun on them (thus allowing for it to be removed from the map itself), but with a double emergency oxygen tank and a breath mask in case it depressurizes. Speaking of...
- More robust anti-depressurization measures: shuttered r-windows and cycling tiny fan-enabled airlocks. In addition, two of these airlocks are public access, so one wouldn't need to break in.
- A jukebox. Enough said.
- A proper kitchen area to make food in, with multiple refrigerators, a deep fryer, and a processor.
- A telecommunication relay, to hear what's going on on-station.

#### Changelog

:cl:  
tweak: Improved the space bar. Now, are you ordering anything or not?
tweak: Centered the Syndicate recruitment poster.
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
Finally the cheese cultures in there will be used

**Comment by Jarod1200** [comment]
Would it be possible to add a food processor

**Review by athena413 — APPROVED** [review]
Looks good but I think this booze dispenser is reachable from the customer side of the counter which makes me :(
image

**Comment by patpol4** [comment]
Can you keep the spacepod dock in? Shouldn't be that hard to expand the entry a bit, also consider using a random plant spawner as a filler for parts that are too empty, such as the room with the cleanbot.

**Comment by Marmio64** [comment]
no more asteroid bar? This makes me sad

**Comment by athena413** [comment]
ty for changine, looks very good now

**Comment by MegaEmpirical** [comment]
Nice.

**Comment by neeshacark** [comment]
Space chef? poor barman need a friend

**Review by patpol4 — COMMENTED** [review]
Fixed some things on my own. 
vivaldi_gz8QRt1ECt
vivaldi_fwRDzWFuzq
vivaldi_CTE2uOqeIF
vivaldi_deOfP7ykEJ
vivaldi_bBu4qhoRVf

**Review by patpol4 — APPROVED** [review]
Map is fine

**Review by patpol4 — CHANGES_REQUESTED** [review]
The headmapper has contacted me and expressed a desire for the asteroid part to be carried over in some shape or form, shouldn't be hard to implement it into this probably.

**Review by JamieD1 — APPROVED** [review]

**Review by patpol4 — APPROVED** [review]
We don't want station areas on a ruin, i just asked for "areas for solars" as in they shouldnt be outside of the station. Other then that i just moved some sand and walls on the outside to make it a bit more organic
chrome_aSdFUly5fr
chrome_1EgMfbC22P

**Review by JamieD1 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
