### PR TITLE
Adds the ability to steal the blackbox from the blackbox recorder (traitor theft objective)

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

original pr: tgstation/tgstation#49298

Adds a new traitor theft objective: steal the blackbox from the blackbox recorder (tcomms).

image

Blackbox recorder, the blackbox item, broken blackbox recorder.

Classes that cannot have this objective:
CE, Station Engineer, Atmos Tech, Signal Tech

Lorewise, the Syndicate wants this for the data it holds. Blackboxes (like in planes IRL) are like a Nokia 3310 and are practically indestructible. This contains a massive amount of data and the Syndicate want to decrypt this and analyze it.

Also good cause it gives the blackbox recorder a use other than being a reference to the code.

note: wiki will have to update this to be included as a high value item as well as a steal objective

#### Changelog

:cl:  
rscadd: Adds a new traitor theft objective, steal the blackbox from the blackbox recorder
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
>spawn as sigtech traitor
>proceed to steal own blackbox

It's the equivalent of a CE traitor stealing his own boots, man.

**Comment by Partheo** [comment]
Why does it float? Also, this shouldn't go in stationobj.dmi. It's for map entities only, not objects.

**Comment by Time-Green** [comment]
Straight port from https://github.com/tgstation/tgstation/pull/49298 by @ArcaneMusic

**Comment by swissloaf** [comment]
> Why does it float? Also, this shouldn't go in stationobj.dmi. It's for map entities only, not objects.

Fixed and fixed. Moved to device.dmi

**Comment by ArcaneMusic** [comment]
> Why does it float? Also, this shouldn't go in stationobj.dmi. It's for map entities only, not objects.

2 Reasons:
It's a hypo-dimensional piece of fractalized gravitic matter capable of recording actions, objects, sounds, light, everything. It's extraplanar geometry can, as a result, absorb the vibations, actions, and causality of everything going on across the station as data, allowing nanotrasen to learn from their mistakes between shifts.
And also,
_**C u b e**_

**Comment by swissloaf** [comment]
> > Why does it float? Also, this shouldn't go in stationobj.dmi. It's for map entities only, not objects.
> 
> 2 Reasons:
> It's a hypo-dimensional piece of fractalized gravitic matter capable of recording actions, objects, sounds, light, everything. It's extraplanar geometry can, as a result, absorb the vibations, actions, and causality of everything going on across the station as data, allowing nanotrasen to learn from their mistakes between shifts.
> And also,
> _**C u b e**_

nah hes right we dont need floating things tho. appreciate the red light

**Review by fluffe9911 — APPROVED** [review]
claimed he tested it should credit his prs better

**Comment by swissloaf** [comment]
> claimed he tested it should credit his prs better

n

**Comment by Marmio64** [comment]
bruh, you didn't even fucking mention you ported it? I honestly thought you might've done this but I guess not, you just didn't credit your port.

**Comment by Partheo** [comment]
Yeah for real why wasn't this credited? @swissloaf

**Pull request merged**
