### PR TITLE
An attempt to port Wiremod from TG

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

An attempt to port Wiremod from TG
https://github.com/tgstation/tgstation/pull/59232

# Wiki Documentation

like a lot. Everything wiremod-related.
Please see the other PR above.

# Changelog

:cl:  
rscadd: Adds Wiremod AKA Integrated Circuits
rscadd: TGUI Updates
wip: This is work in progress. I have no idea what I am doing.
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
due to issues with our version of TGUI, as well as my inability to get a file from the TG git, I am unsure of how this will go.

**Comment by MajManatee** [comment]
https://github.com/tgstation/tgstation/commit/1fb5d68b530b11d55c144733417aca2b27b4c350
This needs to be ported before wire mod will work.

**Comment by maxion12345** [comment]
it's happening ggggggg

**Comment by maxion12345** [comment]
> [tgstation/tgstation@1fb5d68](https://github.com/tgstation/tgstation/commit/1fb5d68b530b11d55c144733417aca2b27b4c350) This needs to be ported before wire mod will work.

I think bee had a wire mod port that has all the requirements

Should be modified to not use the intent changes aswell

**Comment by MajManatee** [comment]
The issue is, our stuff cant handle TSX files right now. Even bee uses them.

**Comment by MajManatee** [comment]
Will re-attempt once jamie is done with all his stuff since a bunch will conflict.

**Pull request closed without merging**
