### PR TITLE
Turf fires

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Revival of #15119, which was a port of shiptest-ss13/Shiptest#872

So basically, turfs can be on fire now. What does this mean for the game? It means fire can exist without instantly turning half the station into an overheated, overpressurized, uninhabitable mess. This allows for cool things like flamethrowers and molotovs setting fire to things without affecting the atmos too severely unless allowed to spread on flammable tiles like wood.

Here's a short video of a molotov setting fire to the library:

https://github.com/yogstation13/Yogstation/assets/93578146/a7bdfa80-10ce-48c3-8fed-1853e0fc6151

Also, the pyroclastic anomaly is back! Instead of just making the room instantly uninhabitable, it instead causes turf fires on nearby turfs, then sets fire to the whole room when it detonates.

Hellfire lasers, flaming arrows, incendiary bullets, and pulse rifles can also start fires, though pulse rifles are much better at doing so and cause blue flames instead of red.

New flamethrower sound effects too!

https://github.com/yogstation13/Yogstation/assets/93578146/6b8153cc-81ab-44f2-a3c6-e6ce5d2ba00f

https://github.com/yogstation13/Yogstation/assets/93578146/b6d5644f-d5e9-4728-a1fe-7eda764e8f61

https://github.com/yogstation13/Yogstation/assets/93578146/280ca79b-02db-413e-9788-39147879a511

https://github.com/yogstation13/Yogstation/assets/93578146/3c536160-d1c1-4275-ba3b-437998a0374d

# Why is this good for the game?

- Makes fires a lot less binary than everything being either perfectly fine or completely fucked
- Gives atmospheric technicians more things they can actually do to help the station than just spacing overheated rooms
- Adds more interesting and fun effects to certain items
- Lets you commit arson in ways that don't render half the station uninhabitable

# Spriting
fire

# Changelog

:cl:  
rscadd: adds turf fires, you can set fire to things now
rscadd: readds and reworks pyroclastic anomalies
tweak: reworked flamethrowers and molotovs to use the new turf fire system
tweak: hellfire lasers, pulse rifles, incendiary rounds, and flaming arrows start fires
tweak: grilles are more resistant to fire
soundadd: adds new flamethrower sounds
imageadd: adds turf fire sprites
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
DO NOT DENY BECAUSE BAD SPRITE!!!
I IMPROVE LATER WITH PARTICLES!!!!

**Comment by Moja10** [comment]
Very cool! Always felt like there could be some in-between, this is definitely a good implementation.

**Comment by Moltijoe** [comment]
i remember seeing the original PR and thinking it was stupid to close it over sprites alone
but i mean, that's par for the course with orca

**Comment by ToasterBiome** [comment]
I like

**Review by cuackles — APPROVED** [review]
sprites do not fully fit but they are still good, and to deny a entire new mechanic just cus its just a bit to round its not something i would consider fair, i do feel like the fire should appear over machinery instead of under it, but apart from that i like it and i do like that there is multiple fire colors including a greyscaled one, also arson good

**Review by ToasterBiome — APPROVED** [review]
shadow fire money gang we love causing fires

**Pull request merged**
