### PR TITLE
Nerfs sec budget

### PR DESCRIPTION
**Pull request by Bibby0110**
subsystem still no worky

sec still have much money (100k+)

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Where is this 100k number coming from? I'm seeing 750 and 250.

**Comment by Bibby0110** [comment]
> Where is this 100k number coming from? I'm seeing 750 and 250.

From observing the round?

**Comment by MegaEmpirical** [comment]
I assumed this was changing the starting budget. What is this changing exactly?

**Comment by Bibby0110** [comment]
Income and starting amount

**Pull request merged**
