### PR TITLE
[admin] Adds a Nerf War adminverb

### PR DESCRIPTION
**Pull request by Altoids1**
# It's Nerf or Nothing!
image

Adds an adminverb that gives every PC, living human on the server some nerf toys and an ammo case of nerf darts.

I was paid to do this by Groudon.

#### Changelog

:cl:  Altoids
rscadd: Admins can now spawn in a Nerf War! It's Nerf or Nothing!
/:cl:

### CODE REVIEW

**Comment by Groudonmaster** [comment]
:+1:

**Comment by boodaliboo** [comment]
its ok

**Comment by Nickvr628** [comment]
when are you nerds gonna port my badass nerf gun sprites?

**Comment by Nickvr628** [comment]
https://images-ext-2.discordapp.net/external/c9kXM3dR1-blLxc5DBJksFFBiYFVRgGgLYtm5uoDDEw/https/cdn.discordapp.com/attachments/230509403101593601/473686356820885513/unknown.png

**Comment by Nickvr628** [comment]
image

**Review by Groudonmaster — APPROVED** [review]
Looks great! Thanks for adding this for me baby.

**Comment by MegaEmpirical** [comment]
This actually seems fun.

**Comment by DLCabbose** [comment]
Every day we stray further from God

**Comment by Groudonmaster** [comment]
It's Nerf or nothing!

**Pull request merged**
