### PR TITLE
ecuttlas does 25 damage now

### PR DESCRIPTION
**Pull request by boodaliboo**
#### Changelog

:cl:  
tweak: tweaked 25 force
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
unnecessary pirate nerf

**Comment by Mesalikepie** [comment]
Uhhh this may be too much 20 seemed nice

**Comment by boodaliboo** [comment]
> Uhhh this may be too much 20 seemed nice

this is for a ecutlass

**Comment by jcatjmeow** [comment]
This means it does 25 damage.

When it's off.

**Comment by UselessTheremin** [comment]
make it only do damage when its off

**Comment by boodaliboo** [comment]
> This means it does 25 damage.
> 
> When it's off.

oh one sec

**Comment by boodaliboo** [comment]
changing reward no longer needed

**Pull request closed without merging**
