### PR TITLE
Allows events to happen during round end

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Allows events to happen during round end

# Why is this good for the game?
It sucks for them not to happen, it's really sad seeing something triggered but the event didnt run

# Testing
image

# Changelog

:cl:  

tweak: Allows events to happen during round end
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
@Runian Confused how

**Comment by Runian** [comment]
> @Runian Confused how

I don't really see a particular need for events to happen during round end. The time has already passed for when events really matter (like being on station).

**Comment by ShoziOffical** [comment]
> > @Runian Confused how
> 
> I don't really see a particular need for events to happen during round end. The time has already passed for when events really matter (like being on station).

But i wanna see admin buses

**Comment by ShoziOffical** [comment]
Like when one time they just spammed meteor event and it didn't happen lol, the announcement by default did

**Comment by JamieD1** [comment]
I dont know if I want lag when admins are dealing with tickets.

**Comment by Moltijoe** [comment]
head dev has spoken

**Pull request closed without merging**
