### PR TITLE
Announcement if AI jumps into a mech and is nuking

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Announcement if AI jumps into a mech and is nuking. People are easily confused when both cores are destroyed and doomsday timer doesn't end, so this makes it obvious the AI is on the lam.
# Changelog
:cl:  
rscadd: Announcement if AI jumps into a mech and is nuking
/:cl:

### CODE REVIEW

**Comment by The-Sun-In-Splendour** [comment]
finally, a good simple horror pr

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Nuke shouldn't tick while inside a mech

**Comment by Simplehorror** [comment]
> Nuke shouldn't tick while inside a mech

it should, it's how it has been since 2015

**Comment by Simplehorror** [comment]
if "nuke shouldn't tick while inside a mech" i'll just scrap mech domination too since that would be noob bait

**Pull request closed without merging**
