### PR TITLE
New sprites for standard security officer and warden gear

### PR DESCRIPTION
**Pull request by nesisknesis**
### Intent of your Pull Request

Resprites the basic gear that the security officer and warden get. Minor edits to some other items.

Security officer: 
image

Warden:
image

Not fully representative of what they look like in-game, missing backpack etc which I did not touch.

honestly not a huge difference, except they look cooler i suppose

The security belt needs to be updated ill get on that later. Berets will also all be updated to the same standard as the one seen on the warden.

There are updated sprites for the HoS trenchcoat that i did not add but that entails a design change and i cant be bothered to argue over that because you guys suck when it comes to that 

Other items i have not updated; bulletproof, riot, ablative, and alt clothing,  because I don't have the energy to continue this PR beyond what i have already covered

### Why is this good for the game?

Explain why each change in your pr is beneficial to the server.

okay guys let me run you through each of my changes in my pr to yogstation 13

- first, the motivation for the helmet was from halo i think halo is a cool game and ykno it looks more interesting so that's beneficial i suppose
- second, the same motivation is HALO for the body armour i love halo its really cool, old armour kinda sucky, it looked like a flat piece of fabric in contrast to my more defined armour.
- third, the beret, i just updated it a bit, yeah
- fourth, the wardens coat, not rally much going on here except i gave it more coat-like features and more definition. yeah the armour might be a bit on the simple side but it works
- fifth, the gloves and boots honestly have not changed a lot, they're practically the same sprite lets move onto the next change
- sixth, de sec glasses, literally added 1 pixel (2 if you you're literal) so you cant complain
- seventh, the hos cap i made more uhhhhhhh lets just say it looks more triangel like those military caps do
- eight, the sec uniforms i touched up to fix my shoddy shading that from my last time i updated sec stuff, it looks better
- 9, alright i forgot to mention this earlier but the obj sprites are a little poor so don't freak out but literally i hate obj sprites and I'm never doing them again so
- 10ten, https://www.youtube.com/watch?v=AiuC_CaObbI

Remember: something that is self evident to you might not be to others. Explain your rationale, even if you feel it goes without saying.

i felt inspired to do sprites for security, I'm pretty sure i had the idea to do this once i had done my three fourths turfs but i guess things don't work out like you expect them to

#### Changelog

:cl:  Identification
imageadd: Security officer and Warden's basic gear have been updated with new sprites.
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
You forgot to remove a palette in `icons/mob/uniform.dmi#rhos`

**Comment by Tipy1802** [comment]
The Warden doesn’t start with his barrete on but with the warden cap. Does this PR make it so he spawns with the resprited barrete instead it keeps him with the warden cap and updates the sprite of the duffel bag barrete?

**Comment by nesisknesis** [comment]
> Does this PR make it so he spawns with the resprited barrete 

no

**Comment by Marmio64** [comment]
don't care for the sec helmet, looks like a weird army helmet meanwhile the old helmet looked dopey in the right way and made them seem like mallcops with armored vests and helmets. Everything else looks pretty neat i guess

**Comment by Tipy1802** [comment]
Love them!

**Comment by BigBigga** [comment]
Fully support this. On another note, lore-wise, I remember reading somewhere that the security roster assigned to NT stations are not supposed to be, in fact, composed solely of retards (in game, of course, is a VASTLY different story on how each player handle themselves) and the Officers/Wardens, and the HOS selected are _supposed_ to be the top of their field and not some run of the mill mallcop, so imo a re-skin is fine tbh, since it makes the vests not look as... lanky...? When compared to the old ones.

**Comment by ghost** [comment]
Not a fan of the security officer helmet. Looks a bit out of place and meh.

Rest of it looks really cool though, nice job.

**Comment by nesisknesis** [comment]
Closed because it would be optimal if all the sec sprites looked to the same standard, obj sprites also don't look that up to spec

going to sit on it until i am able to finish it

**Pull request closed without merging**
