### PR TITLE
Removes Oakboscage from the video game

### LINKED ISSUE #3076: make trash bag break when full
I had a genius idea. When the janitor trash bag is full give it a chance to break, causing the items inside it to fall to the ground.

### PR DESCRIPTION
**Pull request by Altoids1**
Closes #3076. :)

#### Changelog

:cl:  Altoids
rscadd: Trash bags now have a small chance of ripping when filled to very high capacities.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Please do not nerf muhpowergaymer trashbag thnks.

**Comment by MegaEmpirical** [comment]
Glorious.

**Comment by ghost** [comment]
This is going to fuck with people using the trashbag of holding as a belt, as an FYI. Unintended consequence.

**Comment by monster860** [comment]
Adam are you even capable of reading code?

It
doesnt
affect
bluespace
trashbags

**Pull request merged**
