### PR TITLE
Reverts everyone's preferred map to the default (nothing)

### PR DESCRIPTION
**Pull request by Bibby0110**
# Github documenting your Pull Request

Goes with https://github.com/yogstation13/Yogstation/pull/12215
See that for reasoning

# Wiki Documentation

# Changelog

:cl:  
experimental: Preferred maps have been reset to validate which map is most wanted.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Can we make this a popup box that you have to click "ok" to dismiss?

It's really easy to lose that message to loading spam in the chat like that.

**Comment by Bibby0110** [comment]
> Can we make this a popup box that you have to click "ok" to dismiss?
> 
> It's really easy to lose that message to loading spam in the chat like that.

it's the omega big one but sure

**Comment by Hopekz** [comment]
> it's the omega big one but sure

It may just be me, but I ignore all that loading text in the first place. 
There usually isn't anything new in there to read.

**Review by JamieD1 — APPROVED** [review]
Fucking hate preference changes

**Comment by Hopekz** [comment]
-1 gamer point for not mortifying the PR after you implied you would

**Pull request merged**
