### PR TITLE
Resprites all the Canisters and the Portable Siphoner

### PR DESCRIPTION
**Pull request by War-Tex**
Resprites all the Canisters and the Portable Siphoner to have a 3/4 perspective, along with a new but familiar look.

canisters

The first step of the Great (Resprite) Journey.

"There are those who said this day would never come. What are they to say now?" - Prophet of Truth

🆑
tweak: Resprited all the Canisters and Portable Siphoner
/🆑

### CODE REVIEW

**Comment by patpol4** [comment]
Did you change the fastened overlay too? What does it look like now?

**Comment by UselessTheremin** [comment]
man, they need a resprite, and these look great, but i feel they stand out waaaay too different from pipes and other atmos items imo. i feel as if they would be a nice thing to have for the eventual overhaul of how pipes look and stuff.

**Comment by Readystorm546** [comment]
> man, they need a resprite, and these look great, but i feel they stand out waaaay too different from pipes and other atmos items imo. i feel as if they would be a nice thing to have for the eventual overhaul of how pipes look and stuff.

The pipes are in a rework too

**Comment by War-Tex** [comment]
> Did you change the fastened overlay too? What does it look like now?

of course, I'll show ya
canister

**Review by Partheo — APPROVED** [review]
Nice work. The knocked-over canisters are in the wrong perspective though :^)

**Comment by Marmio64** [comment]
i gotta say, i really will miss the old sprites, but this will be a change for the better most likely

**Comment by MegaEmpirical** [comment]
Show us this new portable siphoner thing you animal!

**Comment by MegaEmpirical** [comment]
Did this change air pumps too? They have a new sprite server side.

**Comment by Partheo** [comment]
> Did this change air pumps too? They have a new sprite server side.

It did, Tex wrote portable siphoner in the title but he meant the portable pumps.

**Comment by swissloaf** [comment]
> Show us this new portable siphoner thing you animal!

Silence

**Pull request merged**
