### PR TITLE
adds space suits to space cop

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request

Explain what the purpose of your PR is.
Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool.

Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged. This is much easier for everyone.

whoever made these is stupid
:cl:  
rscadd: Added space suits
bugfix: added a space suit no more suffocation
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
I think it looks a little weird just on a table like that (might look cooler in a suit storage container) but our mapping pope will decide your fate

**Review by Ktlwjec1 — APPROVED** [review]
yeah anywhere you put it it's gonna look cramped, suit storage unit is gonna make that problem worse, not really happy about the placement but I can't really see a better one

**Comment by Marmio64** [comment]
WAIT WHAT THE FUCK THIS GIVES THEM LITERALLY SHIELDED DEATHSQUAD COMMANDO ARMOR

**Comment by patpol4** [comment]
Amazing

**Pull request merged**
