### PR TITLE
Adds a sprite to the RCD drone in the aux base, but it actually works this time

### PR DESCRIPTION
**Pull request by jcatjmeow**
Reverts yogstation13/Yogstation#8713
This was my own pr.

It worked on my local branch. But it flat-out does not work on yogs. I guess nobody noticed? I didn't notice, until recently.

This does work, tho
🆑
rscadd: Adds a sprite to the RCD drone in the aux base
/🆑

### CODE REVIEW

**Comment by Partheo** [comment]
image
is this an error? icondiffbot says the sprite is absent but it does seem present in the file

**Comment by jcatjmeow** [comment]
@Partheo
The sprite is located in 'icons/obj/mining.dmi' with the icon_state  "construction_drone".

The deleted sprite/file was a duplicate from #8713

**Review by Partheo — APPROVED** [review]
This is just a fix and doesn't actually change any sprites themselves

**Review by Partheo — APPROVED** [review]
This is just a fix and doesn't actually change any sprites themselves

**Pull request merged**
