### PR TITLE
Roller beds can now be made using a protolathe.

### PR DESCRIPTION
**Pull request by ghost**
# Github documenting your Pull Request
**This has been tested.**

There are a hilariously small amount of roller beds in the Medbay, it's either using roller beds or spending time picking people up in critical so they don't bleed out all over the Medbay and make reviving them more difficult. Rollerbeds ideally shouldn't be commodities.

# Wiki Documentation
Needs roughly **four sheets of iron** and **one sheet of plastic.** In material costs, **2000 plastic** and **8000 iron.**

# Changelog

:cl:  
rscadd: rollerbeds can now be made at a protolathe, basic biotech node has roller beds
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
autolathes too maybe?

**Comment by ghost** [comment]
> autolathes too maybe?
 
Autolathes can't contain plastic, and letting it contain plastic is far beyond what I have the energy to do at 10:54PM in the night.

**Comment by adamsong** [comment]
Power creep

**Comment by Marmio64** [comment]
cant you just use body bags instead of roller beds

**Comment by Moggram** [comment]
> 
> 
> cant you just use body bags instead of roller beds

yes.

**Comment by adamsong** [comment]
Medical borgs come with a roller bed, just make a bunch of them

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
