### PR TITLE
Remove mineral access from miners

### PR DESCRIPTION
**Pull request by Amelia0010**
see: https://github.com/yogstation13/yogstation/pull/3063/files

### CODE REVIEW

**Comment by GrayRachnid** [comment]
Was there a reason? Out of curiosity.

**Comment by Amelia0010** [comment]
Well, the PR was made shortly after miners doing RnD was declared powergaming officially, so it was mostly just an IC way of preventing that. That, combined with stuff like this https://forums.yogstation.net/index.php?threads/miners-expect-gear-for-doing-their-job.16487/, not to mention the general lack of materials that any non-science department feels :)

**Comment by Jc1469** [comment]
reminder the rule states they can do it if scientists aren't, which this actively impedes.

**Comment by Amelia0010** [comment]
if there aren't any scientists to do it, then it's most likely lowpop enough that they get extended access, in which case they still can.

**Comment by Alexandria404** [comment]
Love it.

**Comment by Oakboscage** [comment]
Great change, council approves.

**Pull request merged**
