### PR TITLE
Charlie Station now has an AGCNR, may God be with you all

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Replaces Charlie Station solars with a mildly damaged nuclear reactor.
image
Moves solars to Beta Station.
image
also removes unused areas i.e hivebot ship, powered tile

# Why is this good for the game?
The AGCNR is an interesting power source, and I want to test player response to a ghostrole nuclear reactor before giving it to a bunch of syndie nerds.

also the station fucking mentions fission as a power source for lower-security research outposts

# Testing

ill do that later

# Wiki Documentation

# Changelog

:cl:  
rscadd: Charlie Station now has a nuclear reactor.
rscadd: please do not spread fallout throughout space, or you will be fined 2 credits for littering
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
I attempted to replace singulo eng with tesla one before and jamie said it was hugbox, the AGCNR is 5x times easier to setup than the tesla

**Comment by ShoziOffical** [comment]
Also did you test the blowout on charlie not spawning ash storm on the station?

**Comment by Addust** [comment]
> I attempted to replace singulo eng with tesla one before and jamie said it was hugbox, the AGCNR is 5x times easier to setup than the tesla

i will probably add damage later

**Comment by Addust** [comment]
> Also did you test the blowout on charlie not spawning ash storm on the station?

testing now

**Comment by ShoziOffical** [comment]
> > Also did you test the blowout on charlie not spawning ash storm on the station?
> 
> testing now

i mean spawning ash storm on the main station where spessmen murderboning

**Comment by Addust** [comment]
> > > Also did you test the blowout on charlie not spawning ash storm on the station?
> > 
> > 
> > testing now
> 
> i mean spawning ash storm on the main station where spessmen murderboning

yea it has indeed done that, drafting until fixed

**Comment by ShoziOffical** [comment]
image

also i think you should put the plasma windows not on the tile where the gas spawns, im pretty sure pressure can break them.. If not then its fine maybe the pressure_resistance var only check for object movements and not damaging it in monstermos code but auxmos could change this soooo yeah

**Comment by Addust** [comment]
> image
> 
> also i think you should put the plasma windows not on the tile where the gas spawns, im pretty sure pressure can break them.. If not then its fine maybe the pressure_resistance var only check for object movements and not damaging it in monstermos code but auxmos could change this soooo yeah

pressure does not fuck gas tanks

**Comment by ShoziOffical** [comment]
> > image
> > also i think you should put the plasma windows not on the tile where the gas spawns, im pretty sure pressure can break them.. If not then its fine maybe the pressure_resistance var only check for object movements and not damaging it in monstermos code but auxmos could change this soooo yeah
> 
> pressure does not fuck gas tanks

yeah figured the pressure_resistance var is a bit misleading

**Comment by Addust** [comment]
heat is what fucks those gas tanks up

**Review by Aquizit — CHANGES_REQUESTED** [review]
Considering this is a mostly ruined station with most of the space debris to the west side, I would say break up some of the space cooling loop. Make 'em fix it. They don't need an RPD as they can use the atmos area to the far west to make what they need. Good way to get that mostly ignored area kinda used again.

**Comment by Addust** [comment]
> Considering this is a mostly ruined station with most of the space debris to the west side, I would say break up some of the space cooling loop. Make 'em fix it. They don't need an RPD as they can use the atmos area to the far west to make what they need. Good way to get that mostly ignored area kinda used again.

got it

**Comment by Aquizit** [comment]
All the stuff you removed is fine but that still needs the /nearstation area so please put that back and should be good to go.

**Comment by Addust** [comment]
> All the stuff you removed is fine but that still needs the /nearstation area so please put that back and should be good to go.

done

**Review by Aquizit — APPROVED** [review]

**Pull request merged**
