### PR TITLE
Ports Cruix The Face of the Revolution!

### PR DESCRIPTION
**Pull request by fluffe9911**
Tested and works just fine had to remove the image tip thing though due to the images for the huds not loading left it in the code though incase someone else can figure it out

See here for what this is https://github.com/yogstation13/yogstation/pull/2216

### CODE REVIEW

**Comment by Bibby0110** [comment]
Wat is this

**Comment by ThatLing** [comment]
What?

**Comment by Groudonmaster** [comment]
What's the original PR?

**Comment by fluffe9911** [comment]
See here for what this is although kinda thought the title would of gave it away lol https://github.com/yogstation13/yogstation/pull/2216

**Comment by Amelia0010** [comment]
the image tip thing?

**Comment by Groudonmaster** [comment]
> 
> 
> See here for what this is although kinda thought the title would of gave it away lol [yogstation13/yogstation#2216](https://github.com/yogstation13/yogstation/pull/2216)

It did. I'm lazy. Provide your references.

**Comment by fluffe9911** [comment]
ok

**Comment by Moja10** [comment]
IIRC, this PR was swimming around old yogs repo for forever, swear at one point it hit the oldest open PR spot. Then eventually, it was finally merged, and in execution it was rather meh. I personally don't see any problem with how revs work and I think it ultimately didn't help either side really. Also dealing with ahelps involving two revs who didn't know they were both revs griefing each other were dumb.

**Comment by fluffe9911** [comment]
`Moja10 commented 7 days ago`
`This is real dumb. Like real dumb dumb, consider merging cruix's faces of the revolution though`

Moja pls

**Pull request merged**
