### PR TITLE
Makes it so every convert isn't instantly made a ridiculously robust species on war clockies

### PR DESCRIPTION
**Pull request by Skrem7**
# Document the changes in your pull request

Not a technical revert PR because the power buff is actually a good thing

# Wiki Documentation

Clockie page should be changed if the war part for convert were ever changed (don't think it was)

# Changelog

:cl:  
tweak: War clockies no longer get to make converts into their ridiculously powerful species type
/:cl:

### CODE REVIEW

**Comment by Skrem7** [comment]
Please attach ided tag

**Comment by 00ze-cyclone** [comment]
Make golems weaker, balance now forever fixed

**Comment by Skrem7** [comment]
> Make golems weaker, balance now forever fixed

Not a bad idea but I don't want to make it

**Comment by TheRyeGuyWhoWillNowDie** [comment]
just remove war cult, this is the only thing that makes it not directly worse than normal clock cult

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
