### PR TITLE
REMOVES THE BURDENING SHACKLES FROM ETHEREAL COLOURS

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
More control to ethereal colours

# Testing
image

:cl:  
tweak: Ethereals can now pick whatever colour they want
/:cl:

### CODE REVIEW

**Comment by Reed0506** [comment]
best pr in history

**Comment by azzzertyy** [comment]
thank you

**Comment by Yarinoi** [comment]
WOOHOOOOOOOO

**Comment by MajManatee** [comment]
should probably not allow things like solid black

**Review by SapphicOverload — APPROVED** [review]
Based

**Comment by iamthesilly** [comment]
> should probably not allow things like solid black

Mutant color selection already prevents this

**Pull request merged**
