### PR TITLE
Disable mulligan on wizard and malf

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

of all gamemodes to have mulligan enabled, why these fuckers? yes, let's roll for traitors after the wizard has summoned ghosts and polymorphed multiple people into syndieborgs or ash drakes or some shit, or given medbay staff of healing.
# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscdel: Disable mulligan on wizard and malf
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
Improve dont remove

**Comment by N3D6** [comment]
@Simplehorror does the round straight up end or just keep going without antags?

**Comment by Bibby0110** [comment]
dumb

**Comment by Simplehorror** [comment]
> @Simplehorror does the round straight up end or just keep going without antags?

ends

**Comment by Simplehorror** [comment]
> dumb

no, but traitors trying to traitor when the shuttle is 5 minutes away is

**Pull request closed without merging**
