### PR TITLE
TRADERS: NPC ships who dock with the station and offer you discounted items/crates and quests

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

Different types of flavorful ships:
NT Loyalists, Secretive """Traders""" (syndicates), Free Miners (not the actual free miner ruin though), Lizard ship, slaver ship (you get to beat these guys up)
Depending on the flavor of ship they'll offer you different crates at discounts, and special items you normally can't get through cargo. TBD

If we do quests they can either be fetch-me-this-item quests or clear-this-part-of-our-ship quests, or maybe they even take you to a mini awaymission, who knows!

Persistent reputation system based on the last 10-20 rounds change which ships attempt to dock.

# Wiki Documentation

# Changelog

:cl:  
rscadd: NPC ships may request docking permissions to the station
rscadd: Aboard NPC ships you'll be able to purchase discounted crates and rare items
rscadd: Some ships may have quests available
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Why do we get to beat the slavers but not the lizards.

**Comment by Bibby0110** [comment]
> Why do we get to beat the slavers but not the lizards.

While the slavers have the goal of being beaten up, it’s fully voluntary if you want to beat up the lizards

**Comment by Tipy1802** [comment]
Can we buy and sell slaves to the slavers instead of beating them up?

**Comment by Marmio64** [comment]
> Can we buy and sell slaves to the slavers instead of beating them up?

antags should be able to sell people to the slavers in exchange for credits, it'd be awesome

**Pull request closed without merging**
