### PR TITLE
Removes Extra gloves from Engineering Store Room

### PR DESCRIPTION
**Pull request by JamieD1**
Fed up of everyone and their mother being able to hack into everywhere.
Still gloves in machine and electrical toolboxes and tech storage

Literally people break in within 30 seconds of a shift to get them...

image

:cl:  
tweak: Nerfs Greytiding
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
Engineers don't start with gloves
source: I forget this a lot then get reminded of it a lot

**Comment by Moja10** [comment]
It's already been moved from the room that you immediately enter if you hack into engineering from maint, is this really necessary? Sometimes its needed to give out additional gloves, and god help you if you are in a perfectly valid situation to take those, like when the malf AI is going complete ape shit and you don't want to die to literally every airlock being shocked. Hasty change. Haven't observed an increase in greytiding for gloves at all.

**Comment by Bibby0110** [comment]
Obvious meme PR is obvious meme PR

**Comment by Moltijoe** [comment]
not 24 hours

**Comment by JamieD1** [comment]
Added gloves to atmos tech, station engineer and CE. Not a meme.

**Comment by Bibby0110** [comment]
> not 24 hours

Me and Jamie have discussed the contents of this PR, and have decided that this PR doesn't align with the direction we wish to take the Yogstation codebase

**Comment by JamieD1** [comment]
> > not 24 hours
> 
> Me and Jamie have discussed the contents of this PR, and have decided that this PR doesn't align with the direction we wish to take the Yogstation codebase

PIss off Bibby.

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Revert the map change

**Comment by BurgerLUA** [comment]
👀

**Comment by JamieD1** [comment]
> Revert the map change

Done

**Review by patpol4 — APPROVED** [review]

**Pull request merged**
