### PR TITLE
Revert "Revert "Adds snails""

### PR DESCRIPTION
**Pull request by fluffe9911**
Nichs like long gone now so lets get snails back

### CODE REVIEW

**Comment by boodaliboo** [comment]
fluffe i already made a revert for this

**Comment by fluffe9911** [comment]
different snail pr silly

**Comment by ThatLing** [comment]
Nich is gone so let's add shit content. This is honestly worse than the dab emote

**Comment by nesisknesis** [comment]
stop trying to push a stale meme

low quality

**Pull request closed without merging**
