### PR TITLE
Removes the felinid restriction from mice cubes.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Potential pay to win is not good, even if the item is shit.

# Changelog
:cl:  
tweak: Removed felinid restriction from mice cubes
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
🥛

**Comment by Moltijoe** [comment]
God bless, i no longer need to play felinid to buy 20 boxes of mice cubes

**Review by Moltijoe — CHANGES_REQUESTED** [review]
if it isn't a race restricted item anymore, please remove it from that tab

**Comment by azzzertyy** [comment]
> if it isn't a race restricted item anymore, please remove it from that tab

done

**Review by Moltijoe — APPROVED** [review]
code approval

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
