### PR TITLE
Adds station map module for borgs

### PR DESCRIPTION
**Pull request by Ktlwjec**
I ask thee to add a cyborg module that's station map
to every modulesI ask thee to add a cyborg module that's station map
to every modulesI ask thee to add a cyborg module that's station map
to every modulesI ask thee to add a cyborg module that's station map
to every modules

:cl:  
rscadd: Borgs have a map module.
/:cl:

### CODE REVIEW

**Review by alexkar598 — CHANGES_REQUESTED** [review]
That's an ugly way to do it, make it a verb at /mob/living/silicon level so that AIs and PAIs can access it too and you dont have to add it to every module

**Comment by Ktlwjec** [comment]
I don't want to add it to AIs or pAIs, so close this if you won't merge it just for borgs.

**Comment by alexkar598** [comment]
Then give it just for borgs, but make it a verb not a module

**Comment by Ktlwjec** [comment]
effort, maybe one day

**Comment by Ratvar** [comment]
And this is how alexkar made game worse

**Pull request closed without merging**
