### PR TITLE
Prevents mechs from shotgun swapping

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

No more ultrakill

# Changelog

:cl:  
tweak: Mecha weapon cooldowns are now shared
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
Replace it with projectile boosting

**Comment by RG4ORDR** [comment]
This is a new one.

**Comment by Moltijoe** [comment]
> No more ultrakill

image

**Comment by Burger1998** [comment]
shouldn't you put this in your other mech pr since that's likely where you encountered the problem and it would be hilarious if that got merged first without this.

**Comment by MajManatee** [comment]
no more bootleg minigun. Sad.

**Comment by ynot01** [comment]
> shouldn't you put this in your other mech pr since that's likely where you encountered the problem and it would be hilarious if that got merged first without this.

this problem exists independent of that pr

**Review by MajManatee — APPROVED** [review]
will merge this before the other one. Just in case.

**Pull request merged**
