### PR TITLE
Revert "probably fixes vote panel"

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#11447

literally no reason to diverge from TG because of this. time to report the original PR

### CODE REVIEW

**Comment by TheLinuxOS** [comment]
The bug was around for a month and you refused to fix it, then theos finally fixed it and you want to revert the fix?

**Comment by ToasterBiome** [comment]
Keep this fix merged until it's fixed on TG's end... no reason to willfully introduce a bug back in just cause you dont agree

**Comment by LazennG** [comment]
bibby bad??????

**Comment by cuackles** [comment]
Bad pr

**Comment by SomeguyManperson** [comment]
waa

**Comment by Bibby0110** [comment]
> waa

waa

**Pull request closed without merging**
