### PR TITLE
Revert "Monstermos - An atmos system that's better"

### PR DESCRIPTION
**Pull request by Bibby0110**
finally

### CODE REVIEW

**Comment by swissloaf** [comment]
bad pr, controversial, council vote needed, DO NOT MERGE

**Comment by Sir-Lagsalot** [comment]
Didn't need a council vote to merge it unfinished in the first place, let's go boys lmaoooo

**Comment by bowlofcereal** [comment]
epic

**Comment by swissloaf** [comment]
all the gay admins upvote this

**Comment by yacabo** [comment]
I don't think removing three lines is how you remove monstermos

**Comment by Bibby0110** [comment]
image

**Comment by yacabo** [comment]
Am I missing something?

**Comment by Sir-Lagsalot** [comment]
Gamer did you fuck up the revert

**Comment by Hopekz** [comment]
This is terrible PR.
Removing 3 check ticks just brings back time dilation and doesn't do anything else.
-1

Read this if you want to know how to revert otherwise close the PR because even if it's merged it won't do what you want it to:
**https://www.bryanlor.com/blog/git-reverts-made-easy**

**Comment by monster860** [comment]
I'm closing this because all this does is make monstermos lag more, not remove it.

**Pull request closed without merging**
