### PR TITLE
Changes Donkpockets to use Vitamins instead of Omnizine. adds fake gondola pockets

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Changes Omnizine in Donkpockets of all types into Vitamins, providing 1.5 brute/burn healing per tick.

Changes the basic donk pocket recipe to mention crewmember instead of traitors
Adds an "original recipe donkpocket" that preserves the omnizine, and puts it in the cargo contraband crate (and thus the smuggler satchels).
Adds a commented-out recipe for Gondola pockets that requires a gondola cutlet
adds Faux-Gondola pockets that contain and cost Pax to craft, and puts them also in the contraband crate/satchels.

This reels in donkpockets as a source of free omni-healing, now only healing brute and burn. The original recipe donkpockets are there for traitors/nukies/infils, and in the smugglers satchels and contraband crates for anyone determined enough to get some.
It makes little sense that a 4" pocket of dough and fillings spontaneously generates a chem only found through: Botany, Syndicate Cigarettes, Borg Lollipop Dispensers

# Wiki Documentation

Guide to food would probably require changes to fit the new donk pockets in, as well as mentioning the vitamins instead of omnizine in almost all of them

# Changelog

:cl:  
rscadd: adds Faux-Gondola pockets that contain and cost Pax to craft
rscadd: adds contraband Original Recipe Donkpockets, that contain omnizine
tweak: Changes Omnizine in Donkpockets of all types into Vitamins
tweak: donkpockets no longer mention traitors in the description
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
First, I want to point out that these changes aren't what we call "atomized" - if this was split into multiple P.R.s (one to add sal-glu, another to make the Gondola changes), it'd have a higher chance of being merged.
Secondly, Gondolapockets aren't available because - in addition to being a grief tool - they let Cargo make horrifying amounts of money by turning monkeypeople into Gondolas, butchering those, selling the hide, and using the meat to make more gondolapockets & continue the loop.

**Comment by VaelophisNyx** [comment]
I wasn't even aware you could make money on gondola hide, lmao
also I'm the one who *ported* the gondola pockets, I just didn't think at the time it was a good idea to make them craftable. It's still stuck behind xenobio RNG as well, so I don't see this happening much.

**Comment by VaelophisNyx** [comment]
to address some complaints on discord:

- Mining has many other healing sources, donkpockets are assuredly not the primary one, or even secondary
- donkpockets healing *everything* but wounds meant they made medbay unneeded if you were wounded. Go to medbay or the bar if you want healing.
- omnizine-donkpockets make sense for syndicate operatives of most types, not really for crewmembers. As is you're getting it for FREE, since none of the recipes require it, because that'd be insane to do as you can't make it without botany. This now means you're getting an otherwise craftable chem for free instead.

**Comment by VaelophisNyx** [comment]
changing gears from sal-glu to Vitamins instead, since those provide much more healing funnily

**Comment by ShadowDeath6** [comment]
Was donk pocket healing really that much of an issue? Miners rarely (if ever) encounter toxin damage, and all the brute/burn damage can easily be repaired with survival pens or the medical kits they can buy. You're not going to heal nearly as much as you would with actual medicine- if you try, you'll just get fat.

**Comment by ToasterBiome** [comment]
This is bad I am sorry

**Comment by VaelophisNyx** [comment]
I'm curious why you think it's bad
talk to me

I was already going to be doubling the vitamin content since the heal it provides lasts less time, to bring it in line with the old omnizine filling.

**Comment by VaelophisNyx** [comment]
> Was donk pocket healing really that much of an issue? Miners rarely (if ever) encounter toxin damage, and all the brute/burn damage can easily be repaired with survival pens or the medical kits they can buy. You're not going to heal nearly as much as you would with actual medicine- if you try, you'll just get fat.

this is partially the point
donkpockets shouldn't be supplanting medication or medical attention in general, even for small wounds or tiny bits of toxin damage. this PR is an attempt to tackle that, in a way that still lets them do some healing since people are attached to that.

**Comment by adamsong** [comment]
Donk pockets are rarely eaten for their healing, omnizine metabolizes very slowly and will fuck your day if you OD.

Additionally, at 1.5 brute/burn per tick you improve the healing properties, as omnizine is only 0.5, and tox damage isn’t treated with it.

All this does is make your imagined problem more likely and remove a source of omnizine that is useful to chemistry

**Comment by VaelophisNyx** [comment]
Omnizine is able to treat toxin damage, though. That's the main issue.
Additionally chemistry should be getting their omnizine from botany, not grinding down a once-rare food item

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
atomize your PR

**Comment by VaelophisNyx** [comment]
Personally I don't think atomizing this one is a great idea, having to add then retroactively nerf new donkpockets, and the syndie donkpockets being a direct result of this nerf, would be horrible.

**Comment by Bibby0110** [comment]
Feel free to reopen a PR where you do the vitamin change and faux-gondola pockets in a separately

**Pull request closed without merging**
