### PR TITLE
Adds moonrats to the game

### PR DESCRIPTION
**Pull request by fluffe9911**
Its the thing that atleast one person was waiting for and wanted and what will save yogstation from its inevitiable demise its moonrats baby woooo!! *warning moonrats are not actual rats*

🆑
rscadd: Moonrats are now in the game
/🆑

Credits:
sam0oneau for the amazing sprite 
fluffe9911 for coding it

### CODE REVIEW

**Comment by Firewolf34** [comment]
What the fuck
moonrat

well I agree this is something we need in the game

**Comment by Firewolf34** [comment]
Is there a moon in the game anywhere? Does lavaland have a moon? Because we should put these on a moon.

**Comment by fluffe9911** [comment]
there is no moons as far as im aware

**Comment by Firewolf34** [comment]
That needs to change, then. Next PR fluffe please add a moon.

**Comment by alexkar598** [comment]
There is a moon

**Comment by alexkar598** [comment]
What happened to the .dmm? why did it fart?

**Comment by fluffe9911** [comment]
no idea

**Review by Amelia0010 — DISMISSED** [review]
remove the yogbox changes

**Comment by fluffe9911** [comment]
But you can check the map bot I just added the moon rat to the garden

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
