### PR TITLE
adds angel to charged black extract possible species

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
adds angel to the possible races you can get when you inject plasma into a charged black extract
#### Changelog

:cl:  
rscadd: Added the ability to roll the angel race to charged black extracts
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
Angel species is already available with a potion from rainbow slimes. Why is duplicate needed? Looking at how you were adding angels to traitor uplinks, you seem to like them.

**Comment by boodaliboo** [comment]
This is rng between around 12 other possible species many which are also obtainable through xenobio

**Comment by Ratvar** [comment]
That's not the answer, tho.

**Comment by boodaliboo** [comment]
Because it’s cool to have multiple ways to reach something

**Comment by Amelia0010** [comment]
Fix your changelog.

**Comment by ShadowDeath6** [comment]
Charged black is a lot easier to get than rainbow, I don’t think this is really needed

**Comment by alexkar598** [comment]
I don't like this. Angel is pointless and adding pointless rewards is equally as pointless

**Pull request closed without merging**
