### PR TITLE
adds engine stuff to the engine room on delta

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Github documenting your Pull Request

apparently TG removed this and didn't replace it with anything so lmao

# Changelog

:cl:  
rscadd: engineering engine stuff on delta now actually exists instead of not doing that
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
best pr

**Review by patpol4 — APPROVED** [review]
There existed some stupid argument against this, something about interdepartamental cooperation, such thing does not and can not exist and this is better for making the other maps likable.
One minor thing might be that there arent any grounding rods and very few tesla coils but I'm sure engineers can manage and it won't cause any serious problems.

**Comment by N3D6** [comment]
Making delta less stinky???

**Comment by SomeguyManperson** [comment]
fixed fixed fuck I hate tg and their stupid no engine for engineering stupid fuck

**Pull request merged**
