### PR TITLE
adds space suits to russian fugitive ship

### PR DESCRIPTION
**Pull request by boodaliboo**
whoever mapped this ship is a fucking idiot
#### Changelog

:cl:  
rscadd: Added space suits
bugfix: russians will no longer die due to a idiot fucking mapper giving them no suits
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
russian powercreep

**Comment by MegaEmpirical** [comment]
This an issue with all of the dudes that spawn to capture fugitives too.

**Comment by boodaliboo** [comment]
> This an issue with all of the dudes that spawn to capture fugitives too.

ill go about doing that then

**Review by Ktlwjec1 — APPROVED** [review]
ye

**Pull request merged**
