### PR TITLE
Add a branch new module of disco ball based on ethereal one that is printable

### PR DESCRIPTION
**Pull request by warface1234455**
#  About PR
add a branch new module of disco ball based on ethereal one that is printable
(also has some light effects from the radiant mk IV)

# Spriting
image

https://user-images.githubusercontent.com/89688125/185617724-bb7ae21f-0736-410b-a6a6-b07f739f9ce6.mp4

# Wiki Documentation
A branch new disco ball based on ethereal one but it's not a head in a box but an actual disco ball 
Can be printed from autolathe

# Changelog

:cl:  
rscadd: added a new disco ball that is printable from autolathe based on ethereal disco ball.
imageadd: Added new sprite for portable disco ball
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
could just have two, the non head one is printable while the head one remains for everywhere else it normally spawns

**Comment by warface1234455** [comment]
> could just have two, the non head one is printable while the head one remains for everywhere else it normally spawns

righto

**Comment by Marmio64** [comment]
you can also avoid needing a new sprite by just making the printable one be called a faux ethereal head disco ball, and write in the desc how it's a fake one

**Comment by warface1234455** [comment]
> you can also avoid needing a new sprite by just making the printable one be called a faux ethereal head disco ball, and write in the desc how it's a fake one

true.... but a sprite would look better

**Comment by JamieD1** [comment]
@adamsong You had issues before with this

**Comment by warface1234455** [comment]
> @adamsong You had issues before with this

I made a new disco ball with no **ethereal** head, this shouldnt affect printing

**Comment by adamsong** [comment]
I'm fine with it if its not the head one and the head one still exists

**Comment by warface1234455** [comment]
> I'm fine with it if its not the head one and the head one still exists

the head one exists but isn't printable

**Comment by ShoziOffical** [comment]
so i just tried to sprite

**Comment by ShoziOffical** [comment]
@JamieD1

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
