### PR TITLE
Hologram control is now a menu

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

You use a radial to change holograms and you get to preview it
image
image
image
image

# Changelog

:cl:  
rscadd: Holopad control now uses a radial menu
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
what is the process for choosing if you want to look like a crewmember?

**Comment by redmoogle** [comment]
> what is the process for choosing if you want to look like a crewmember?

Click on QM symbol click on crewmember

**Comment by redmoogle** [comment]
image

**Comment by JamieD1** [comment]
What have you changed since I last talked about this with you?

**Comment by redmoogle** [comment]
> What have you changed since I last talked about this with you?

made the menu bigger

**Comment by JamieD1** [comment]
Please make this additional not replacing.

**Comment by redmoogle** [comment]
> Please make this additional not replacing.

havent I told you no several times now?

**Comment by JamieD1** [comment]
> > Please make this additional not replacing.
> 
> havent I told you no several times now?

Alright then

**Pull request closed without merging**
