### PR TITLE
I can't spell (Fixes typo for screwdriver syndicate)

### PR DESCRIPTION
**Pull request by Therandomhoboo**
# Document the changes in your pull request

I can't spell, we can't spellcheck either and I know no one cares but me. Fixes typo in screwdriver syndicate thanks to someone reporting it. This is the report  #20435 

# Why is this good for the game?

Because it means I can actually make sure no typos are in the game

# Changelog

:cl:  

spellcheck: Fixed the typo for when you make syndicate screwdriver (flavour text)

/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
meancing

**Comment by Moltijoe** [comment]
ah fuck, misclick

**Review by Moltijoe — APPROVED** [review]

**Comment by MajManatee** [comment]
I mean, you COULD get a spell check plugin for VS code...

**Comment by Therandomhoboo** [comment]
> I mean, you COULD get a spell check plugin for VS code...

what do i look like, good at my job?

**Pull request merged**
