### PR TITLE
Escape Rework

### PR DESCRIPTION
**Pull request by alao3alao3**
## Intent of your Pull Request

Reworks escape by adding chairs, and extends it out a little so that the chairs look better. This minorly extends the Holding Center.
bpng
hell i was fine with the current bland escape nature which is just empty

## Why is this change good for the game?

This is to serve as an alternative to EIB0N's rework which uses the fake multi-z illusion using shadows and stairs. I'm personally still on the fence about it's use in an area as heavily trafficked as escape.

## Wiki Documentation

Wiki image will need to be updated.

# Changelog

:cl:  
tweak: reworks escape, making it and the Holding Center bigger. 
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
no dont make departures be good

noooooooooooooooooooooooooooooooo

**Comment by Tipy1802** [comment]
EIB0N's version is better

**Comment by Marmio64** [comment]
bigger escape helps with highpop and lets you build bigger projects there, which is arguably more important than chairs/decals. Eibon's PR looks very cool but its very restrictive and leans heavily into a easily broken illusion

**Review by patpol4 — CHANGES_REQUESTED** [review]
Fix conflict or just make another pr. 
Going with this one because Eibon's was too cluttered.

**Comment by alao3alao3** [comment]
See #11493

**Pull request closed without merging**
