### PR TITLE
Replaces the diamond pickaxe in necropolis chest with mythrill

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
the diamond pickaxe is completely useless to most if not all lava land inhabitants as they can all find different and better mining tools already scattered around lava land

#### Changelog

:cl:  
tweak: tweaked one of the possible necropolis items
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
fix ur repo ive been emailed twice over a shank and tray

**Comment by boodaliboo** [comment]
> fix ur repo ive been emailed twice over a shank and tray

i dont want to delete the whole weapons dm

**Comment by boodaliboo** [comment]
> > fix ur repo ive been emailed twice over a shank and tray
> 
> i dont want to delete the whole weapons dm

on my next pr also i dont know how to

**Review by ThatLing — CHANGES_REQUESTED** [review]
Icon change

**Pull request merged**
