### PR TITLE
THE HONKMOTHER COMES

### PR DESCRIPTION
**Pull request by ynot01**
## Intent of your Pull Request

# FINISHED, TESTED & FULLY FUNCTIONAL

### Goals

- [x] Set up honk_act for objects to be converted

- [x] Give **Her** appearance

- [x] Remember to give credit to MerchantPixels

- [x] Create **Her**

- [x] Fix /objs not being converted on processing

- [x] Make only 20% of things in range convert per process

- [x] Fix objs already converted being converted again

- [x] Have **Her** spawn on clown ops victory at the location of the detonation

- Make a nice looking effect for converting turfs (optional) (spriter needed)

#### The Honkmother
- Is the one true god
- Kind of smaller than the other gods
- Does not fight the other gods, only ~~sabotages~~ pranks them by turning their shit bananium
- Floats around like a one true god
- Spawns from the bananium fission explosive going off
- Turns all things near into their bananium counterparts
- Can summon clown mobs from ghosts
- Turns guns into Staff of the Honkmother

<details>
 <summary>Sprite courtesy of MerchantPixels</summary>

</details>

<details>
 <summary>Preview images</summary>

</details>

## Changelog

:cl:  ynot01, MerchantPixels
rscadd: Added The Honkmother, who spawns on Clown Ops victory
/:cl:

### CODE REVIEW

**Review by Partheo — APPROVED** [review]

**Comment by Marmio64** [comment]
can you post a image of the sprite
i've gone through all of the commits, and i couldn't find it since im probably just retarded

**Comment by CoreyTori** [comment]
That's a lot of commitments.

**Comment by Georgeur** [comment]
This is A* grade autism and I fucking want it. Especially with how many people are often left alive during a clown ops round. Fucking **outstanding**.

**Review by fluffe9911 — APPROVED** [review]
clown ops in rotation when

**Pull request merged**
