### PR TITLE
New arrival voice

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Reopen of https://github.com/yogstation13/Yogstation/pull/17109

No longer will it says "TG Station" and leave people confused every time you late join.
A 99% chance to play the normal, welcome sound
and a fun, 1% chance to have a... special flair on the end.

https://github.com/yogstation13/Yogstation/assets/42524344/3bfecf48-e952-4931-b148-c513f4dc3b0d

https://github.com/yogstation13/Yogstation/assets/42524344/dff801d2-21aa-4b07-8621-11a16d7b1b37

# Wiki Documentation

# Changelog

🆑 @MajManatee , @cuackles and ssethtzeentach
rscadd: Chance for a alternate arrival sound
soundadd: New arrival sound(s)
sounddel: old sound out the window
/🆑

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
the sound clips, you can hear clicking in it, also who the fuck is this?

**Comment by azzzertyy** [comment]
> the sound clips, you can hear clicking in it, also who the fuck is this?

i hear no clicking, also, no clue, its a reopen, ask manatee
second one is sseth though

**Comment by azzzertyy** [comment]
yes it is actually seth it is not an ai
image

**Comment by athena413** [comment]
worth changing solely because azzzertyy had the balls to ask the man himself

**Comment by cuackles** [comment]
cant aprove cus i helped do the first audio but oh my fucking god its the legend himself

**Comment by Marmio64** [comment]
still dont really like it, though it'd be cool if it was atomized to have the sseth voiceline appear sometimes (or maybe even during the entirety of april fools)

**Comment by MajManatee** [comment]
I have no idea what you mean by clicking, I don't hear nothin,

**Comment by ToasterBiome** [comment]
Don't really think it fits, also I can barely understand it and it has clipping.

**Pull request closed without merging**
