### PR TITLE
Dynamic Threat Level is no longer announced over the station's announcement intercomm.

### PR DESCRIPTION
**Pull request by Xoxeyos**
Dynamic Threat Level is no longer announced over the station's intercomm. Less of "oh shit dynamic", and more !!FUN!!.

:cl:  
tweak: The threat level is no longer announced over the station's announcement comm.
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
I think it's a nice indicator of what is to come.

**Comment by redmoogle** [comment]
Kinda neutral. I feel like it should be removed from low threats(but this makes it meta-able) but kept for high threats because you're basically fucked

**Comment by Xoxeyos** [comment]
> 
> 
> I think it's a nice indicator of what is to come.

The only difference is that the Captain will have to announce it over the station's intercomm. I think it's a nice way to have people less panicky and so on.

**Comment by Hopekz** [comment]
> The only difference is that the Captain will have to announce it over the station's intercom. 

This never happens.
When is the last time the captain announced what to look out for from the round-start report?

**Comment by Xoxeyos** [comment]
I'm for either way, merging it or denying it, I want to see what people want.

**Comment by redmoogle** [comment]
Ok I misunderstood this a bit. Yeah that's pretty good. Only removes the paper title and dynamic mode announcement

**Comment by ghost** [comment]
It should be announced if it's high threat level like 80+, because the crew NEEDS to know they're fucked if they want to survive

**Comment by swissloaf** [comment]
> It should be announced if it's high threat level like 80+, because the crew NEEDS to know they're fucked if they want to survive

I'd say 60-70, those are pretty fucky too

**Comment by Xoxeyos** [comment]
Alright give Adam some upvotes, like around 5, and I'll put it in, or you can write your opinions off.

**Comment by MrHorizons** [comment]
> > The only difference is that the Captain will have to announce it over the station's intercom.
> 
> This never happens.
> When is the last time the captain announced what to look out for from the round-start report?

Personally, I've told security what to look out for based on the roundstart report. In fact, the dynamic announcement is _vaguer_ than the non-dynamic status summary, because it only gives you the flavor text of the threat level rather than actual possibilities.

**Comment by maxion12345** [comment]
idk I kinda like the heads up when admins decide to max out threat and sit back to watch the fires

**Comment by Xoxeyos** [comment]
I'll be adding a way for these announcements to show up sporadically, so don't you worry yet.

**Review by jcatjmeow — APPROVED** [review]
losing is fun!

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
