### PR TITLE
Sterilizes the codebase - Pt.7 Removes Catsip

### PR DESCRIPTION
**Pull request by JamieD1**
Sterilizes the codebase - Pt.7 Removes Catsip

:cl:  
rscdel: Removes Catsip
/:cl:

### CODE REVIEW

**Comment by Smudged** [comment]
Bad change, nerfing felinids ho are already donor only for no reason.

**Comment by VaelophisNyx** [comment]
tbh, catsip is a drink no one makes because its recipe is ass, and its use-case is...felinids. Which rarely come to the bar in the first place.

**Comment by SomeguyManperson** [comment]
Forcing people to nyaa uncontrollably is hilarious especially because its not restricted to cats

**Comment by Hislyna** [comment]
I would suggest making what people say less cringey if that is the main problem, alongside altering the description/flavour text.

**Comment by Marmio64** [comment]
could be a fine drink if it just made felinids trip balls rather than what it has to do right now

**Comment by JamieD1** [comment]
Anyone wanna suggest how to make it less cringe then?

**Comment by Marmio64** [comment]
> Anyone wanna suggest how to make it less cringe then?

yes, i just said how.
Just make it add druggy stacks like space drugs/pan galactic gargle blaster does, but only if they're felinid.

**Comment by VaelophisNyx** [comment]
> yes, i just said how. Just make it add druggy stacks like space drugs/pan galactic gargle blaster does, but only if they're felinid.

This but also, the recipe should be adjusted to use space milk, not soy milk. I don't know a single cat that enjoys soy milk

**Comment by Hislyna** [comment]
/datum/reagent/consumable/ethanol/catsip
    name = "Catsip"
    description = "A felines drink to keep them on their toes on the hunt."
    color ="#ff99ac"
    boozepwr = 50
    quality = DRINK_NICE
    taste_description = "a feline favourite"
    glass_icon_state = "catsip"
    glass_name = "Catsip"
    glass_desc = "Unfortunately has a tendency to induce the peculiar vocal clicks of a hunter."

/datum/reagent/consumable/ethanol/catsip/on_mob_life(mob/living/M)
    if(prob(8))
        M.say(pick("Hiss.", "HISS!", "MIAOW!"), forced = "catsip")
    return ..()

/datum/reagent/consumable/ethanol/catsip/on_mob_add(mob/living/carbon/human/M)
    if(!M.dna.species.is_wagging_tail())
        M.emote("wag")
    return ..()


Would that be less cringe for yall?

**Comment by SomeguyManperson** [comment]
it is FINE just the way it is. it is NOT degenerate to force someone to uncontrollably nya and is ONLY used for COMEDIC EFFECT

**Comment by KillerOrcaCora** [comment]
sowrry if my nya makes you feel funny~

**Pull request merged**
