### PR TITLE
Heretics Among Heretics: Heretics have a higher chance to betray eachother.

### PR DESCRIPTION
**Pull request by BurgerLUA**
Heretics now have a 20% chance to target another Heretic per assassinate objective.

# Changelog

:cl:  
rscadd: Heretics now have a 20% chance to target another Heretic per assassinate objective.
bugfix: Fixes a bug where it was entirely possible to have two of the same assassinate or protect objectives of the same crewmember.
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
i don't think people go for objectives with heretic, they go for ascension. make it so you need to sacrifice another heretic to ascend

**Comment by BurgerLUA** [comment]
> i don't think people go for objectives with heretic, they go for ascension. make it so you need to sacrifice another heretic to ascend

This was the original plan but I'm not really experienced with the code. Heretics have to choose their targets from a pool of 1 to 3 (Chosen randomly) of candidates to sacrifice. I would have to remove that system in order for that to work.

**Comment by Simplehorror** [comment]
> > i don't think people go for objectives with heretic, they go for ascension. make it so you need to sacrifice another heretic to ascend
> 
> This was the original plan but I'm not really experienced with the code. Heretics have to choose their targets from a pool of 1 to 3 (Chosen randomly) of candidates to sacrifice. I would have to remove that system in order for that to work.

i can do it for you

**Comment by UltraBigRat** [comment]
Not a fan of this honestly, heretics are already a pretty darn difficult antag with alot of ways of easily being fucked over. making them kill each other probably isnt a very good idea.

**Comment by Bibby0110** [comment]
Make this compile and reopen, blessed

**Pull request closed without merging**
