### PR TITLE
The supermatter now screams every time it emits rads

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

This way you know if it is emitting rads or not

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: The supermatter now screams every time it emits rads
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
why is my CI not working?

**Comment by Simplehorror** [comment]
there we go

**Comment by Hopekz** [comment]
Would be funny if you made a video of this

**Comment by Moltijoe** [comment]
Too funny for this server

**Pull request closed without merging**
