### PR TITLE
Paramedic space suit

### PR DESCRIPTION
**Pull request by Hopekz**
Revives #8732

Original PR owner didn't feel like fixing his PR and gave up on it so I'm reviving the project.

image

Differences from #8732
-----

- it is now a reskinned EVA spacesuit instead of a hard suit (no thick armor or combat armor values)
- created icons for the items because they were not even there meaning the PR was broken.
- added 1 to each map instead of 2.

#### Changelog

:cl:  Hopek , Partheo , Nickvr628
rscadd: Added the paramedic space suit. Each Paramedic office spawns with 1 space suit for space extractions.
imageadd: Credit to Partheo and Nickvr628 for the Paramedic space suit sprite.
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
will review l8r

**Review by nesisknesis — COMMENTED** [review]
The suit needs some sort of protection. It's also shown to have body armour on the sprite so itd be expected to at least have some defense value as well.

The protection for the EVA suit is `armor = list("melee" = 0, "bullet" = 0, "laser" = 0,"energy" = 0, "bomb" = 0, "bio" = 100, "rad" = 20, "fire" = 50, "acid" = 65)`

The protection for body armor is `armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)`

Perhaps mediate between the two.

Give Nickvr some credit for the concept as well.

**Review by nesisknesis — APPROVED** [review]

**Comment by JamieD1** [comment]
That helmet looks awful :(

**Comment by Hopekz** [comment]
> That helmet looks awful :(

):

**Comment by JamieD1** [comment]
> > That helmet looks awful :(
> 
> ):

Can you add some glass to it?.. make it look less like you cant see out of it?

**Pull request merged**
