### PR TITLE
BoxStation smaller trims [GONE SEXUAL?] [SEC CALLED]

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

smaller trims....

# Changelog

:cl:  
mapping: BoxStation gets new trims
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
what?

**Comment by patpol4** [comment]
> what?

smaller trims

**Comment by Moltijoe** [comment]
> > what?
> 
> smaller trims

ah, thanks, got it 👍

**Review by patpol4 — APPROVED** [review]
impossible to review, we'll fix it in post if something's wrong

**Comment by JamieD1** [comment]
Fuck sake

**Pull request merged**
