### PR TITLE
Adds Lavaland Wallbuilder ruin

### PR DESCRIPTION
**Pull request by Nickvr628**
image

Adds a new ruin to lavaland! The Wallbuilder Base! This is designed to be a "tutorial ruin" of sorts, allowing players to learn aspects of a certain role, like the highly sucessful syndicate base and xeno facility ruins of the past.

This base will teach players the basics of engineering and construction. It has 3 spawners for players, who will start with basic engineering gear and equipment to start building.

Their assigned project is to build a wall. The first segment of it is already built and provides and example of how to construct future segments. The wall would (at least lore wise) protect the miners from xeno life and ashwalkers. 

Their equipment includes raw materials, RCDs, and even a fireproof mech with a mounted RCD to build segments over lava. They also have a locker with a sketchin pistol inside to defend against xenos.

ALSO this nerfs ash walkers so Adam will approve.

:cl:
add: Wallbuilder Base and supporting items
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
Yes this is a great ruin and I think it should be merged.

**Comment by Cruix** [comment]
I 100% garuntee that someone is going to take the mech and pistol and RCD into the mining base, fly to the station, and murder everyone because "lol I am a ghostrole antag I can murderbone"

**Comment by Nickvr628** [comment]
I could make the flavortext more explicitly say they work for NT, more so than it does now.

**Comment by drderp3635** [comment]
"Highly successful syndicate base and xeno facility ruins" my ass. Those ruins are and have always been pieces of garbage. All this will be is a free mechs for miners to steal with no difficulty at all.

**Comment by Keekenox** [comment]
Remove the stetchkin

**Comment by Jc1469** [comment]
balance police say no. too much bullshit for people who AREN'T playing as the role to use.  Like a fully built mech with an RCD. A pistol.  Medical supplies for days. Actual non-mech RCDs. :-1:

**Comment by AdamElTablawy** [comment]
Nope. No more ruin additions please. No more ghost roles or ways for people to enter the round, ESPECIALLY not with a fireproof mech with a mech RCD, which is the best mech tool in the game.

**Comment by Stealthkibbler** [comment]
if someone actually steals a FIREFIGHTER ripley on lavaland then they deserve to be dropkicked.

**Comment by puremanbird** [comment]
stop taking up space on lavaland for stupid shit please. if you really REALLY want to make a ruin like this make it a space ruin.

**Comment by Zostroll** [comment]
Yeah I hate the training ruins as I think most people do please don't add more.

**Comment by Super3222** [comment]
Given the fact that our lavaland budget is being reduced to 60 I feel like we can still keep this in somehow. The amount of lavaland ghost roles will be reduced to 1-2 every round. If not I'll increase some of the weights on ghost roles.

The mech RCD is one of the best tools in the game, Adam's right.
Furthermore, to compensate you can give them an RTD from https://github.com/yogstation13/yogstation/pull/1786.

Also possibly give the mech an ID lock (probably engineer level), and give the builders ID's with the same level. In this case, miners or other random ghost roles can't run in and steal them.

Making them NT governed is good. Probably throw in a book of space law somewhere to constantly remind them of this.

I like the code part of this. Nice work, Nick.

**Comment by Super3222** [comment]
@Nickvr628 Are you still working on this? If not I can just close this, and ask someone to reopen it w/ modifications.

**Comment by Super3222** [comment]
I like the idea, but it's been abandoned.

**Pull request closed without merging**
