### PR TITLE
Ports "Adds beating vending machines for free stuff/getting crushed to death"

### PR DESCRIPTION
**Pull request by Xoxeyos**
# Document the changes in your pull request

This ports over [Ryll-Ryll's](https://github.com/Ryll-Ryll) ["Adds beating vending machines for free stuff/getting crushed to death"](https://github.com/tgstation/tgstation/pull/47799), this has the following effects.

You can attack vending machines with objects to try and knock free things loose! You have a chance of getting a few trinkets for free for each whack! You also have a chance of the vendor falling over on your cheapass head and squish you and anyone else on the tile for 75 brute.

Might be balance implications to this? If there's any machines that really shouldn't be giving stuff away unauthorized I can turn it off for them

Here's your odds:
5% chance to get 3 goodies
10% chance to get 2 goodies
10% chance to get 1 goody
50% chance for nothing
15% chance for tilt
10% chance for tilt with CRIT

There are 5 crit effects:
1- Shattered/pulped legs: Smashes both your legs and removes 150u of blood along with them
2- Pinned: You are stuck under the machine until someone else untilts it and moves it off you
3- Glass candy: You are shredded by glass shards
4- Paralyzed: You have fully severed your control over your legs!
5- Skull squish: Your head explodes! Obviously this is instantly fatal

# Wiki Documentation

If you rattle a vending machine enough, you get free prizes, or you get pulped.

# Changelog

You can now beat on vending machines to try and knock loose free stuff! You can also almost kill yourself doing it, so it's your call if your life is worth ten bucks.

:cl: Ryll/Shaps, MarkSuckerberg, Xoxeyos, arcturus-prime
rscadd: You can now beat on vending machines to try and knock loose free stuff! You can also almost kill yourself doing it, so it's your call if your life is worth ten bucks.
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
image
Meme INC™℠®©℗

**Comment by JayBaez** [comment]
is this a coincidence?

**Comment by Xoxeyos** [comment]
> is this a coincidence?

What'd you mean?

**Comment by JamieD1** [comment]
Dang, I had this idea a couple years ago.

Glad someone went and did it.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
