### PR TITLE
Easel recipe addition

### PR DESCRIPTION
**Pull request by Xoxeyos**
Adds the easel to the crafting menu, using seven wooden planks.

🆑 Xoxeyos
rscadd: The easel can now be made from wood.
/🆑

### CODE REVIEW

**Comment by Takahiru** [comment]
The only way to get them beforehand was cargo crates, I support

**Comment by nesisknesis** [comment]
canvas for easels are qdeleted at roundstart because theyre astronomically broken, this is redundant

**Comment by Takahiru** [comment]
:thonk: i was wondering why i couldnt spawn canvasses

**Comment by Xoxeyos** [comment]
> 
> 
> canvas for easels are qdeleted at roundstart because theyre astronomically broken, this is redundant

TG found a fix, so I'm going to try and port it over at some point.

**Comment by ToGWtF** [comment]
TG's arent like normal. Rather than the world sprite changing, it saves to a IE window. You still have to examine then to see the picture I think

**Comment by Bibby0110** [comment]
> > canvas for easels are qdeleted at roundstart because theyre astronomically broken, this is redundant
> 
> TG found a fix, so I'm going to try and port it over at some point.

I'll probably be doing this at some point, honk

**Comment by Xoxeyos** [comment]
Fixed the merge conflict.

**Pull request merged**
