### PR TITLE
Adds Tatorling Branded Cereal

### PR DESCRIPTION
**Pull request by tattax**
# Document the changes in your pull request

Tired of your not boring darkspawn, gangs and revs rounds making people have fun?

Say no more!

With Tatorling™️ Branded Cereal will make sure you feel the boringness and sleepyness of traitor and ling!
You can now do your job freely for 2 hours!

Comes with two TOYS!
Will you collect them both?

image

86DWt6FhmT

# Wiki Documentation

new food item

:cl:  
rscadd: Tatorling branded cereal coming soon to all vendors in your area! 
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
I just want to point out that the joke of cereal containing vitamin, nutriment, and _salt_ is already in the game - it's in Bran Requests Cereal.

**Comment by tattax** [comment]
> I just want to point out that the joke of cereal containing vitamin, nutriment, and _salt_ is already in the game - it's in Bran Requests Cereal.

does bran requests have TOYS also it was the most neatly written cereal so i took from that and didn't change much

**Comment by ghost** [comment]
Sex

**Review by ghost — APPROVED** [review]

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Comment by ghost** [comment]
Add changeling sting as a reagent for them👍

**Review by ghost — APPROVED** [review]

**Comment by JamieD1** [comment]
@grimm-hollowknight

**Review by nesisknesis — APPROVED** [review]

**Comment by ghost** [comment]
Absorbing AI in traitor maint

**Pull request merged**
