### PR TITLE
Appendicitis is actually annoying in stage 3 now

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Appendicitis in stage 3 will deal toxin damage as well as make you stunned, cough, deal small toxins and have the "sharp pain" flavor text

# Spriting

# Wiki Documentation

# Changelog

:cl:  

tweak: Appendicitis stage 3 isnt bearable anymore

/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
I think its bearable for the worst case scenarios, like when you are HoS in an active combat scenario and can't obviously take a medbay break, so coughing + stunning would mean that in this circumstance the game decided you should die, which obviously isn't ideal

**Comment by Aquizit** [comment]
> I think its bearable for the worst case scenarios, like when you are HoS in an active combat scenario and can't obviously take a medbay break, so coughing + stunning would mean that in this circumstance the game decided you should die, which obviously isn't ideal

Perhaps make Stage 2 give stronger warning signs then? But overall I like this idea.

**Comment by solwashere** [comment]
> I think its bearable for the worst case scenarios, like when you are HoS in an active combat scenario and can't obviously take a medbay break, so coughing + stunning would mean that in this circumstance the game decided you should die, which obviously isn't ideal

it takes a while to stage and I increased the coughing chance early on so that you're more likely to notice it

**Comment by Therandomhoboo** [comment]
Appendicitis basically does nothing anyway unless you're a moron who is anti-medbay. I see no problem fluffing it up so it has some flavour.

**Comment by KingSuperBOB** [comment]
Appendicitis actually impacting the game and not something I ignore the whole game?

**Comment by MajManatee** [comment]
honestly i thought it made you explode when it hit stage 3

**Comment by ynot01** [comment]
appendicitis is one of the most annoying things in the game currently, do peopl=e really just ignore it??

**Comment by solwashere** [comment]
> appendicitis is one of the most annoying things in the game currently, do peopl=e really just ignore it??

Slicer ignored it at stage 3 and all they did was vomit like every 4 minutes
Appendicitis is only annoying at stage 2 as of right now

**Comment by KingSuperBOB** [comment]
> appendicitis is one of the most annoying things in the game currently, do peopl=e really just ignore it??

Ive quite litteraly just sat there with stage 3 appendicitis not dying the only annoying thing is the rare puking

**Comment by KingSuperBOB** [comment]
Appendicitis litteraly only rolls once or twice a round and if you are playing on highpop its a incredibly small chance to get it not to mention the fact that on stage 3 you can ignore the toxin almost completely and medbay knows how to remove appendicitis in seconds with there being no actual threat to having it compared to something like a heart attack you will only have issues with appndicitis if you somehow roll it as a ghost role with no surgery tools nearby

**Comment by solwashere** [comment]
> Appendicitis litteraly only rolls once or twice a round and if you are playing on highpop its a incredibly small chance to get it not to mention the fact that on stage 3 you can ignore the toxin almost completely and medbay knows how to remove appendicitis in seconds with there being no actual threat to having it compared to something like a heart attack you will only have issues with appndicitis if you somehow roll it as a ghost role with no surgery tools nearby

Or if for whatever reason you go 10+ minutes with coughing and the "sharp pain" flavor text and just never get it checked because???

**Comment by SomeguyManperson** [comment]
> honestly i thought it made you explode when it hit stage 3

Idk what it did before organ damage rework (probably toxin damage) but presently it deals damage extremely slowly to the appendix organ, which I don't believe is even blocked from passive healing, and if _that_ fails begins dealing concerning amounts of toxin damage.
This will likely take at least a quarter of an hour of stage 3 appendicitis to start risking organ failure, and that is without accounting for passive organ healing

In 2000000 years of gaming I have only seen this kill one extremely deserving comms agent

**Comment by KingSuperBOB** [comment]
> In 2000000 years of gaming I have only seen this kill one extremely deserving comms agent

He deserved it for not knowing self surgery

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
