### PR TITLE
Piping fixes for box

### PR DESCRIPTION
**Pull request by Readystorm546**
# General Documentation

### Intent of your Pull Request

Changed the hallway below medbay by moving the firelock to have 2 instead of 3. Also moved more pipes and wires around to keep consistancy.

image

image

GOT RID OF THIS MONSTROCITY 

image

### What general grouping does this PR fall under? 

Maping

:cl:  
rscadd: Changed the hallway below medbay by moving the firelock to have 2 instead of 3. also piping fixes/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
>to keep things consistent around the station

I don't get it

Also this makes the maint around that area really straight and uninteresting
The disposals part is fine though

**Comment by UselessTheremin** [comment]
it just looks uglier and more cramped, why??

**Review by patpol4 — CHANGES_REQUESTED** [review]
The bottom part with straightening the pipe can stay but please remove the maint room change, it makes it worse

**Comment by Readystorm546** [comment]
> it just looks uglier and more cramped, why??

THis is for consistency. Before this change this was the only place that had a three-wide mait hallway. Now it has some consistency with the rest of the station

> I don't get it
> Also this makes the maint around that area really straight and uninteresting

Im not sure anyone looks at an oblong hallway and says otherwise. Like I said though it is for consistency. I could make it a little different so its not a 90-degree turn but consistency on things is good

**Review by patpol4 — CHANGES_REQUESTED** [review]
For xenobridge, the disposals is above the pipes, needs to be under,
vivaldi_GubxIN6LLa

Same things for the rest:
by sec:
vivaldi_APJt3FEhTh

below viro:
vivaldi_gyMpzIVtMW

by the 10x10 maint spot:
vivaldi_EzDiUSYSUP

also wrong areas by the monstrosity
vivaldi_MtNDiEYNg7

**Comment by Readystorm546** [comment]
> For xenobridge, the disposals is above the pipes, needs to be under,
> 
> Same things for the rest:
> by sec:
> 
> below viro:
> 
> by the 10x10 maint spot:
> 
> also wrong areas by the monstrosity

I hate dreamaker

**Comment by JamieD1** [comment]
@wejengin2

**Review by patpol4 — APPROVED** [review]
should be fine i think

**Pull request merged**
