### PR TITLE
Security is no longer granted 1000 credits a minute if the self destruct nuke core hasn't been stolen

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

who thought this was a good idea??

# Wiki Documentation

# Changelog

:cl:  
rscdel: Security no longer gets a free 1000 credits a minute
/:cl:

### CODE REVIEW

**Comment by MommaDragon** [comment]
DUDE WHY

**Comment by MommaDragon** [comment]
WHAT RATIONALE IS THERE FOR THIS CHOICE

**Comment by Runian** [comment]
sure why not. theres no physical security budget anyways to get money out of anyways.

**Comment by stwordcitizen** [comment]
> sure why not. theres no physical security budget anyways to get money out of anyways.

the defense budget in armoury is the security budget I think

**Comment by Bibby0110** [comment]
This PR is based on the precedence of https://github.com/yogstation13/Yogstation/pull/11533

**Comment by Loldaddy5676** [comment]
why not make it so it gives 1000 credits every 10 to 15 minutes?

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
