### PR TITLE
Revert "Revert "Cat people have feline screams now and custom emote (#11642)""

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#11736

Outrage, rogue maintainer?
image

### CODE REVIEW

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Please provide information on where you got the sound files from to comply with the license we use for assets

Also please add a cooldown

**Comment by Bibby0110** [comment]
> Please provide information on where you got the sound files from to comply with the license we use for assets
> 
> Also please add a cooldown

Ask jamie

**Comment by alexkar598** [comment]
Get Jamie to make the PR then if you are unwilling to provide information/make changes

**Comment by JamieD1** [comment]
How about you dont speed merge a fucking undo commit without even talking to me.

**Comment by nmajask** [comment]
I have a version of this with new sounds and a cooldown if you want me to PR it

**Pull request closed without merging**
