### PR TITLE
i ded

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request

remove fast speed from simulant from stimpack and whatnot

rationale being stimpacks are less used to shrug off stuns as originally intended and now are used for the free meth speed, letting them run up and kill someone before they can react or just let them dodge bullets since you're literally faster then them now

all at three doses of about five minutes each. I know nukeops already abuse these like mad just due to the removal of damage slowdown and the fact one of the meta strats is to stimpack into the disk holder with the lmg, crit with a burst, and then drag the body out while moving at mach 7

honestly it's a little bit *too* good. This'll keep the damage slowdown remove, healing, and stamina Regen while not giving the user absurdly high movement speed that lets them cheese fights

# Spriting
no
# Wiki Documentation

stimpack no fast
# Changelog

:cl:  
rscdel: stimpack no give free meth speed anymore, use nano stimulant if nookops
/:cl:

### CODE REVIEW

**Comment by Cleverslim** [comment]
literally just a skill issue. #salt pr

**Comment by N3D6** [comment]
pr sucks

**Comment by PibeCantina** [comment]
I mean, if you really dont like it, just make it nukie only, why remove the speed, that's what makes the item

**Comment by iamthesilly** [comment]
Add reasoning for why it's good for the game in the PR description please

**Comment by maxion12345** [comment]
> Add reasoning for why it's good for the game in the PR description please

done

**Comment by Moltijoe** [comment]
Balance council:
>the speed boost is counterable with things like bola and dragnet, and stims are limited unlike other sources of speed

**Pull request closed without merging**
