### PR TITLE
Ports elements system from TG

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Ports [element system](https://github.com/tgstation/tgstation/pull/44817) from TG. Nothing more to explain here, if you want to know what is it just check original PR.

# Wiki Documentation

It is a code change, not required.

# Changelog

:cl:  [ninjanomnom](https://github.com/ninjanomnom), ported to Yogstation by SuperSlayer
tweak: Ports elements from TG
/:cl:

### CODE REVIEW

**Comment by TymurShatillo** [comment]
Okay i will fix this when i will get a normal PC

**Comment by ToasterBiome** [comment]
Thid does not compile. Also can you port more elements so this isn't used for one thing?

Waddling is another easy one

**Comment by ghost** [comment]
> Thid does not compile. Also can you port more elements so this isn't used for one thing?
> 
> 
> 
> Waddling is another easy one

I can port more elements, but the main problem that I don't know how to fix shit that doesn't compile just because. It doesn't show what is the problem, show errors, etc. If i somehow will find the way to fix it i will definitely port more.

**Comment by JamieD1** [comment]
Will merge after https://github.com/yogstation13/Yogstation/pull/14144

**Comment by ghost** [comment]
But i still don't know how to fix compiling errors

**Comment by JamieD1** [comment]
On Hold

**Comment by JamieD1** [comment]
postponing

**Pull request closed without merging**
