### PR TITLE
New turbine sprites

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Ports turbine sprites from BeeStation/BeeStation-Hornet#7634, by PestoVerde322 and PacifistDalek

# Spriting

image

image

# Wiki Documentation

New turbine images for use on the wiki:
Compressor
Turbine

# Changelog

:cl:  PestoVerde322, PacifistDalek, SapphicOverload
imageadd: new turbine sprites
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
Ummm.... shouldn't the wide end be on the other side to seal off the fire? or his it always been like that?

**Comment by iamthesilly** [comment]
> Ummm.... shouldn't the wide end be on the other side to seal off the fire? or his it always been like that?

It's always been like that

**Comment by ShoziOffical** [comment]
Thicc

**Review by cuackles — APPROVED** [review]
damn they gave an extra dimension to the turbine

**Pull request merged**
