### PR TITLE
Adds Shawls

### PR DESCRIPTION
**Pull request by nmajask**
# Github documenting your Pull Request

While looking through the pinned messages in #spriting, I saw the link to the [TG Sprite Dump](https://github.com/tgstation/SS13-sprites) back in 2018 and the shawls sprites within. From what I can tell, they were made by [Kor](https://github.com/imtakingabreakdontatme?tab=overview&from=2016-12-01&to=2016-12-31l), but I could be wrong. People seemed to like the sprites, but I guess no one got around to using them. This PR adds shawls using these sprites as an alternative to the cloaks that heads get. Maybe in the future these can replace the cloaks.

They go into the neck slot like cloaks and are found where the cloaks are found (captain's autodrobe, heads clothing bags, and QM's lockers), but they also have a hood that can be activated by alt clicking on it (I couldn't get the UI button to work). The hood functions similar the goliath cloak hood, taking off the cloak will cause it to be removed. Unlike the head cloaks, the shaws provide a very small amount of armor (5 fire) and are all fire proof (just the CE's cloak is fire proof). There is also a craftable leather shawl that is not fireproof and needs 5 leather. Obviously I've test to make sure the shawls work and spawn correctly

In the sprite sheet in the dump, which sprite is for which head is not well defined and some are just missing, so I had to make ones for the HoP and leather shawls. I originally wanted to add some of the details that the cloaks had, but I ended up just adding a green cross to the CMO's shawl. Here are some pictures of the shawls:

Captain:
cap

Head of Personnel:
hop

Head of Security:
hos

Chief Engineer:
ce

Research Director:
rd

Chief Medical Officer:
cmo

Quarter Master:
qm

Leather Shawl with Directions:
front
back
right
left

Leather Shawl with Hood:
hood

Item Icons (they are just the back of the worn icons, like the cloaks):
capshawl
hosshawl
hopshawl
ceshawl
rdshawl
cmoshawl
qmshawl
leathershawl

# Wiki Documentation

The only things that would need to be changed is the leather recipes and the captains autodrobe options

# Changelog

:cl:  
rscadd: Added shawls using Kor's old sprites with hoods that can be toggled with alt clicking.
/:cl:

### CODE REVIEW

**Review by nesisknesis — CHANGES_REQUESTED** [review]
These can replace cloaks. appreciate that you've done this.

however, if you check the icon diff bot, it seems there is an issue with the cowboy hat which needs to be addressed. your PR overrides a new name it was given in another PR.

**Comment by nmajask** [comment]
> however, if you check the icon diff bot, it seems there is an issue with the cowboy hat which needs to be addressed. your PR overrides a new name it was given in another PR.

Ah, that's probably cause my folder I use to test and make changes is so out of date. The last commit should fix it.

**Review by nesisknesis — COMMENTED** [review]
These should also replace the current cloaks since they're virtually identical but visually improved; effectively a resprite.

**Comment by nmajask** [comment]
> These should also replace the current cloaks since they're virtually identical but visually improved; effectively a resprite.

The last commit should do this. I just stopped the old cloaks from spawning and changed some names. If you want me to fully remove the old cloaks, move the shawls over, or anything else I can do it when I get time. Also, do you want me to keep the hoods or should I remove them, as they have a few issues.

**Review by nesisknesis — COMMENTED** [review]
What issues are there with the hoods?

**Comment by nmajask** [comment]
> What issues are there with the hoods?

Long hair clips through the hoods (goliath cloaks also have this issue), they are toggled by alt clicking as I couldn't get the UI button to work, and they don't look very good in my opinion. Though they are entirely optional to use, so I guess there is no real harm in keeping it in.

**Comment by nesisknesis** [comment]
I would say just remove the hoods then I shawl merge them

**Comment by nmajask** [comment]
> I would say just remove the hoods then I shawl merge them

New commit removes them

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
