### PR TITLE
Adds HUD icon for artist

### PR DESCRIPTION
**Pull request by nesisknesis**
### Intent of your Pull Request

artist now has a hud

image

very small changes to the incarceration icon and sigtech too

Fixes issue #11231 
### Why is this change good for the game?

oooooohhh

thank you for chester for telling me how to fix it

# Changelog

:cl:  Identification
imageadd: Artist has a HUD icon now.
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
idk why but its not working

**Comment by ChesterTheCheesy** [comment]
Try adding artist job to https://github.com/yogstation13/Yogstation/blob/master/code/modules/jobs/access.dm, so it can have a hud assigned based on that.

Oh and yeah, what is the hud supposed to represent? An artist brush? Doesn't speak much of an artist to me.

**Comment by nesisknesis** [comment]
> 
> 
> Try adding artist job to https://github.com/yogstation13/Yogstation/blob/master/code/modules/jobs/access.dm, so it can have a hud assigned based on that.
> 
> Oh and yeah, what is the hud supposed to represent? An artist brush? Doesn't speak much of an artist to me.

i tried a palette but it was really ambiguous on what it was. and of course the aseprite logo is quite meta. if you got a better idea please do tell

**Comment by ChesterTheCheesy** [comment]
obraz

i'd make it look more like a brush on a white canvas

**Comment by nesisknesis** [comment]
> 
> 
> obraz
> 
> i'd make it look more like a brush on a white canvas

this contradicts the two-tone style of job HUDs.

**Review by Partheo — APPROVED** [review]

**Comment by ChesterTheCheesy** [comment]
> this contradicts the two-tone style of job HUDs.

that was kinda the point, artist is a colorful job

**Comment by JamieD1** [comment]
@grimm-hollowknight Looks like a sperm. Add some colour. or change it to a pallette.

**Pull request merged**
