### PR TITLE
Inflation Fetish: Syndicate Hijack Dock Edition

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

title

# Why is this good for the game?
lets us have #22615 - allows for future shuttles to be wider/longer than they would otherwise be - in directions considered previously arcane

# Changelog

:cl: cark
mapping: Increased the size of the syndie shuttle hijack dock
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Why did you have to name it that

**Comment by PibeCantina** [comment]
Now that's a PR name

**Review by AMyriad — APPROVED** [review]
good solution

**Comment by CrazyDrakkon** [comment]
yippee my stupid shuttle fits

**Pull request merged**
