### PR TITLE
Revert "Remove mediborg pinpointer due to having access to the Lifeline modular computer program"

### PR DESCRIPTION
**Pull request by Simplehorror**
Reverts yogstation13/Yogstation#16404
Some people can't use modular computers, and this PR offers no benefit, it just removes options that have a right to exist.

### CODE REVIEW

**Comment by Moltijoe** [comment]
fix the underlying issue

**Comment by Simplehorror** [comment]
> fix the underlying issue

you get IE9 working on wine and we talk

**Comment by Simplehorror** [comment]
@TheGamerdk why was this closed

**Comment by ShoziOffical** [comment]
> Reverts #16404 Some people can't use modular computers, and this PR offers no benefit, it just removes options that have a right to exist.

Borg can download lifeline to track crew

**Comment by ReddicusDragon** [comment]
> > fix the underlying issue
> 
> 
> 
> you get IE9 working on wine and we talk

image

It is not our job to support unsupported configurations. Byond is set up to *run* the games on Windows machines only. Running the games on Linux is unsupported and I believe that any maintainer or coder would agree with me in saying that it not working is entirely your fault for using an unsupported configuration.

**Comment by Bibby0110** [comment]
If you can't use the UI of the game maybe you shouldn't play the game

**Comment by TheGamerdk** [comment]
> @TheGamerdk why was this closed

why was this opened

**Comment by LoliconSlayer** [comment]
Remove the entire game I can't play on OSX

**Comment by Simplehorror** [comment]
> If you can't use the UI of the game maybe you shouldn't play the game

i can use UIs as long as they're not bloated TGUI uis

**Comment by Moltijoe** [comment]
> i can use UIs as long as they're not bloated TGUI uis

Skill issue

**Comment by LoliconSlayer** [comment]
> > If you can't use the UI of the game maybe you shouldn't play the game
> 
> i can use UIs as long as they're not bloated TGUI uis

I hate to inform you, but the "bloated TGUI uis" are part of "the UI of the game"

**Pull request closed without merging**
