### PR TITLE
[MDB IGNORE] [PRE-ALPHA] MiniStation

### LINKED ISSUE #22576: Objects do not fall down stairs when thrown into empty space
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: when you toss an item (on ministation) above a stairwell they don't fall down to the other z-level but stick as if there's a floor
## Supplied Image:

SuppliedImage
 Submitted by: sadthunder07 (263084474672218112)

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Adds a new 30 player multiz map set attached to a small asteroid.

Prebase players might notice that this is nearly a 1:1 direct copy of MiniStation from prebase with an additional z-level, asteroid, and expanded departments.

This is nowhere near finished, and is going up now for some light testing on the server and beginning of feedback.

Chapel Bottom:
image

Xenobio:
image

Armory + Execution Chamber
image

HOP, Captain, and HOS room: 
image

Bar + Kitchen:
image

Virology:
image

closes https://github.com/yogstation13/Yogstation/issues/22576

# Why is this good for the game?
Maps scaled better for lowpop = good when we're in our lowpop era

# Wiki Documentation

Entire new map

# Changelog

:cl:
rscadd: Adds MiniStation, a lowpop station!
/:cl:

### CODE REVIEW

**Review by AMyriad — CHANGES_REQUESTED** [review]
So here's what's missing from what I see

## Missing rooms

Essential:

- [x] Telecomms
- [x] AI sat
- [ ] AI upload

Nonessential:
- [ ] RD office (but needed for RD)
- [x] Bathrooms
- [ ] Pool room
- [ ] Interrogation
- [ ] Psych office (but needed for psychs)
- [ ] Law office
- [ ] Holodeck
- [ ] Experimentor (lol)
- [ ] Art supplies room


## Map errors

- [x] No trimlines around janitor closet
- [x] No access set at teleporter room door
- [x] No access set on armory windoors
- [x] No access set + tile instead of plating at table/windoors between kitchen and botany
- [x] Maintenance /any/ access helper missing from library
- [x] Maintenance door at shipbreaking has wrong access helper
- [x] No hazard trimlines on maint doors at shipbreaking, between shipbreaking and library, and warehouse
- [x] No lightswitch in primary tool storage
- [x] HFR equipment and decals missing in lower atmos
- [x] Missing floor tiles in lower engineering?
- [x] No access set on door control buttons at brig desk
- [x] No access set on disposal vent button at disposals
- [x] No access set on hop privacy shutters button
- [x] No access set at toxin mixing room airlocks
- [x] No access set on toxins mass driver windoor
- [x] No camera covering lower xenobio

**Review by AMyriad — CHANGES_REQUESTED** [review]
### Map errors

- [x] Maint airlock in lower engineering needs maintenance decals, also the helper needs to be `/all/engineering/general` not `/all/engineering`
- [x] No plating underneath north robotics desk
- [x] No access set on door in the middle of AI sat
- [x] Firedoors missing from engie and atmos desks
- [x] Plating under ORM instead of floor tiling
- [x] Firedoors on directional windows in warden's office?
- [x] Hoochmaster 2000 (chem_master/condimaster) ~~and sink~~ missing from bar backroom
- [x] No firedoors on desk between kitchen/botany
- [x] Double lattice at coords 45, 88, 2 and 65, 73, 2
- [x] Double cameras in engineering lathe room, QM office
- [x] Isolation ward windoors in virology missing access
- [x] Missing one paramedic closet in paramedic staging area
- [x] Missing privacy shutters in paramed staging too
- [x] No shutters in SM engine
- [x] Double decal at 108, 128, 2
- [x] "Mech bay door control" that doesn't do anything in robotics

#### Missing requests consoles
- [x] CE office
- [x] RnD
- [x] Telecomms
- [x] Bridge
- [x] Kitchen
- [x] Bar
- [x] Medbay
- [x] Chem lab
- [x] Cargo office
- [x] Chapel
- [x] Janitor closet
- [x] Engineering
- [x] Atmos
- [x] Captain's office
- [x] Warden (idk optional)
- [x] Dorms

#### Missing cameras
- [x] SM engine room
- [x] [Incinerator](https://github.com/user-attachments/assets/2cc5ee6b-d6a0-4a10-9e3e-0860b0e9733b)
- [x] Teleporter
- [x] Equipment area in upper engineering
- [x] Tech storage
- [x] Evac sec checkpoint
- [x] RnD entrance airlocks
- [x] MiniSat monitoring room
- [x] MiniSat maintenance
- [x] [Coverage in atmos could be better](https://github.com/user-attachments/assets/24a03786-8911-483c-aecc-26c18b1c358d)
- [x] [Blindspot also in north atmos](https://github.com/user-attachments/assets/d1ad2de9-1c00-4c59-b116-6a8aa36aed8f)
- [x] [Some blindspots in cargo](https://github.com/user-attachments/assets/608c648a-c02c-4b56-8d65-bf15bcb80462)
- [x] [Blindspot outside cargo](https://github.com/user-attachments/assets/632c0f07-7d50-4afe-ae15-6238554534f3)
- [x] [Blindspot in chapel](https://github.com/user-attachments/assets/0151e9dc-4e8e-4ffe-b60a-6d63db22da72)
- [x] [Blindspot outside EVA](https://github.com/user-attachments/assets/74102454-678b-4bc0-b058-ed1d7785e6ef)
- [x] [Blindspot in bar](https://github.com/user-attachments/assets/aacf1c47-ae20-44d3-aca9-892d21949ef0)
- [x] [Blindspot ](https://github.com/user-attachments/assets/0e7954dd-cadd-4711-9958-15e43c5326fb)
- [x] North end of aux tool storage
- [x] Restroom (idk box does it)

#### Missing lightswitches
- [x] Warden's office
- [x] Upper brig and lower brig
- [x] Armory
- [x] AI sat
- [x] Engineering/atmos could use 1-2 more at the far ends
- [x] Tech storage
- [x] Prison wing
- [x] Gravity generator


### Stylistic notes (optional suggestions)
- [x] ramp_corner/ramp_middle shadows missing from stairs everywhere - putting this as optional cause I wouldn't have a problem doing this myself after it's merged tbh
- [ ] Opportunity for maint ruin in port quarter (SW) maints
- [x] No command trimlines in AI sat
- [x] Could remove glass from garbage disposal airlock to make ambushing more fun
- [x] In the vault, could swap the places of the bank machine and gold crate so the bank machine isn't facing a wall
- [x] Hazard stripe in teleporter room kinda ends abruptly, could be adjusted somehow?
- [ ] Empty room above morgue?
- [ ] No newscasters (lol)
- [x] Chapel mass driver could be less restricted; use `chapel_office` access instead of `crematorium`
- [x] Library could use some paintings :) (would be nice in some places like dorms too)

**Comment by JamieD1** [comment]
Reviewed a shit tone with Biome, much better now

**Review by AMyriad — CHANGES_REQUESTED** [review]
Round 3 of errors/suggestions, probably my last one as I think we're almost ready to go!

- [x] CE desk/racks are lacking fax machine, decryption key, paperwork, etc
- [x] Not sure if 2nd server is reachable with the AI subcontroller in front of it? Could do something like this instead image
- [x] No camera coverage in second AI core
- [x] No mailsorting going to chapel
- [x] No warden jacob :(
- [x] No kitchen animal :(
- [x] No safety possum? :(
- [x] Recommend replacing/removing fire alarm in armory with weapon rechargers, so they aren't behind windoors
- [x] Camera in vault needs to be motion sensitive
- [x] AI chamber needs cameras around its exterior
- [x] Suggest an intercoms pass around the station, almost each department room should have one, and main halls could use a couple more
- [x] Same as above but for fire extinguisher cabinets, notable examples are engineering, atmospherics, cargo for instance

**Review by cuackles — APPROVED** [review]

**Review by AMyriad — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]
She looks good

**Pull request merged**
