### PR TITLE
Deletes virologist (only the job) and gives access to medical doctors (+1)

### PR DESCRIPTION
**Pull request by Moltijoe**
Do note, the skillcape still exists, it simply won't be possible to unlock anymore
The virologist figure and clothes also still exist

I could phrase this as "merges virologist and medical doctor" as that's effectively what it is, but that feels disingenuous

# Why is this good for the game?
Virologist as a job is too narrow in scope, it does it's one thing, finishes it in 10 minutes, and sits around for the entire shift
When a virus comes around, more often than not it's the CMO, chemist, or a doctor that cures it anyways
Giving access to doctors also lets them decide to pop into virology if the round is unusually quiet or boring, giving something to fill the downtime
Gives one additional spawn to doctors so if someone wants to just be virologist they can spawn as doctor and head to virology without "cutting into" the regular doctor spawns

Having less jobs that can do more is better than having more jobs that can do less as it allows people to pick and choose what they want to do as time goes on, rather than be stuck with a single task for an entire round

# Testing
image

:cl:  
rscdel: Deletes the virologist job
tweak: Medical doctors now have virology access
tweak: 1 additional medical doctor can exist at any time
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
unless any of you that have downvoted give any semblance of explanation, i'm gonna assume you haven't actually read the pr and just think this is me deleting viruses

**Comment by Bibby0110** [comment]
GOod PR

**Comment by neeshacark** [comment]
image

**Comment by Moltijoe** [comment]
> image

this isn't even removing viruses as a mechanic, just the job
those bounties are outstanding because we don't have a single coder that cares about virology enough, if you do, feel free to work on the bounties and this pr can be re-evaluated
even then, if virology gets revamped and made actually good, i'm still of the mind that it should be an aspect that doctors access

as i said in discord, we have scientist, not
-xenobiologist
-nanites tech
-toxins specialist

geneticist gets a pass for the time being because not only is genetics a more in-depth mechanic from the start, but they also have more design room for growth and wouldn't need a fundamental rewrite of their whole system
also because chubby would probably kill me (a coder that actually cares about the job)

The only reason to oppose this is for dreams of what virology could be, not what it currently is, which is a less than half baked mechanics focused job
Were it an rp focused job, it'd also get a pass for the reference

**Comment by neeshacark** [comment]
i just fundamentally disagree that genetics is more complex than virology in any way.

**Comment by Moltijoe** [comment]
> i just fundamentally disagree that genetics is more complex than virology in any way.

complex? no
well designed and with room for growth? yes

any time a new virus symptom gets added, virology mains complained about how shit the rng is
any time a new mutation gets added, geneticists rejoice

cowbot also has plans of porting dna infusion from tg, which would be a geneticist thing
virologist has no avenue of sidegrades with it's thematic

**Comment by Scrambledeggs00** [comment]
Might not be a good idea balance wise to give 5+ people easy accessibility to making super AIDS 2.0: my ass is on fire and bleeding profusely edition.

**Comment by Moltijoe** [comment]
> Might not be a good idea balance wise to give 5+ people easy accessibility to making super AIDS 2.0: my ass is on fire and bleeding profusely edition.

if someone's gonna do that, they'd break in using hacking

**Comment by wonderinghost** [comment]
> Might not be a good idea balance wise to give 5+ people easy accessibility to making super AIDS 2.0: my ass is on fire and bleeding profusely edition.

Let me ask you this

Do you think xenobio or toxins should have their own separate jobs from science

**Comment by Cartlord** [comment]
I think the argument being made is that it's easier to shit everything up with viro - tox bombs either require suicide or planting them somewhere they won't be found before detonation (I doubt throwing one sends it far enough away that you're actually safe from the blast), and xenobio takes quite a while to set up and is generally a pain in the ass (though i'm assuming that's also true of viro).

**Comment by Moltijoe** [comment]
> I think the argument being made is that it's easier to shit everything up with viro - tox bombs either require suicide or planting them somewhere they won't be found before detonation (I doubt throwing one sends it far enough away that you're actually safe from the blast), and xenobio takes quite a while to set up and is generally a pain in the ass (though i'm assuming that's also true of viro).

i'm not inclined to believe that
theres only so dangerous a virus can become, and even then it'll eventually get cured because viruses have a limit to how difficult they can be
And even then, there's almost always an ipc or plasmeme that's straight up immune

Toxins is not only known for rendering science uninhabitable via mistakes
but a few well placed maxcaps can crater a department or worse

recovering from a virus is also faster than recovering from bombs
once the virus is cured, most bodies are intact, or husked at worst
and the station is completely unaffected

for bombs, the amount of engineering time to rebuild a department from nothing is longer than most rounds are
and anyone caught in the blast needs to be revive, or possibly even cloned if they were in devastation range
that's not even considering what happens if the department being cratered is medbay

**Comment by wonderinghost** [comment]
Building needs to be faster. Or at least make things quicker to setup for building. 

But that is a different can of worms. 

Reason why I brought up those 2 is that they can become really destructive yet anyone in sci can access. Yet we don't hold that same lense for virology which can also be very destructive

**Review by neeshacark — APPROVED** [review]
maps are fine btw

i still dont like removing viro tho

**Comment by StupidTums** [comment]
Never played the job, but it seems silly to remove the role. It's too unique for it to be accessible to all of medical (even if people don't play the job much). Medbay isn't like science where all the scientists have access to every research area (excluding robo). It's more specialized in that regard, and it helps differentiate it from science. If anything, why does geneticist have science access but viro doesn't? Their jobs are so similar in that regard.

**Comment by wonderinghost** [comment]
Geneticists are a joint job between the departments. Medbay can use the cloner while science can focus on researching mutations
 
But I'm fine with virologist being removed. Possibly make a ruin or bounty reward for their cape. A good chunk of the time when people are sick more often then not people have to break in to get cured. However that's a general problem of how medbay hierarchy is set. 

Medbay has effectively 6 jobs in its department (counting gene but excluding head and external medics). However we mainly focus on the big 3, retrieval, chemical production, and operations (surgery and resurrection). Medbay is the busiest department when there are bodies with a multitude of alements. While yes diseases can be cured in both virology and chemistry the priority for chemists is higher because most viruses are easily curable by ingesting heavy metals. When you can't cure something by chemical production then you have this tedious task of getting into virology or pray that the virologist is listening or there is a CMO/acting cap to deal with it or give someone access to this one office.

Maybe if there was more to virology other than making diseases then this PR wouldn't be on the table. However the scale and focus for virology isn't there ATM

**Comment by StupidTums** [comment]
> While yes diseases can be cured in both virology and chemistry the priority for chemists is higher because most viruses are easily curable by ingesting heavy metals. When you can't cure something by chemical production then you have this tedious task of getting into virology or pray that the virologist is listening or there is a CMO/acting cap to deal with it or give someone access to this one office.
>

Kind of wild that, a majority of the time, diseases can be cured while completely ignoring viro (using it only to mass produce a vaccine). That doesn't seem right and is probably a key factor in its low viability.

**Comment by Necrosium** [comment]
Instead of removing it why don't we rework it into something new? Take Mokestation's example of viro for example, would be a good idea to port it here instead. In Monke a virologist is essential to the curing of a disease; curing it isn't based on a specific chemical to ingest but on an immunity system that you can boost or inhibit as you like. Every disease is weak to 2 antigens, you boost them you cure it, bla bla bla... 

Anyways thing is, how about we use this system instead of removing it all? I think it'd make a better option and more fun.

I'd code it myself but oh god if i can barely code an equippable chair...

**Comment by wonderinghost** [comment]
Virology the code now isn't going just the job position.

**Comment by Moltijoe** [comment]
> Virology the code now isn't going just the job position.

I literally put (only the job) in the title specifically to clarify this, but people still cant read.

**Comment by Tipy1802** [comment]
I would rather MDs focus on healing people than doing virosology. I also just don't see the problem with the job? Sure it doesn't have that much content but that can be said for many jobs. Its like removing chemists and making MDs do it or removing geneticists and having scientist do gene manipulation (also yes mutations fall under science, geneticist is med-sci, with the only medical part being mutations) or combining atmos and engineering, sci and robo and so on...

**Comment by Cartlord** [comment]
I think the difference is that you can feasibly have someone working Chem all round long because of people getting more damaged and needing more meds (or some bitch robbing the smartfridge), you can feasibly do Atmos all round long because of how long it can take to set up pipes & mixes if you're not extraodrinarily well-optimized, Geneticist is a seperate job because it used to be **somewhat** more involved so it could take a lot longer to get every good mutation than it does now, and... I don't have an argument for why Robotics is a dedicated job
as i understand it, viro and genetics are both in a state where the only real way for it to last a whole shift is for you to get phenomenally unlucky in finding whatever random roll you're seeking

**Comment by Moltijoe** [comment]
whatever

**Pull request closed without merging**
