### PR TITLE
Forever erase the makeshit laser rifle so that it never come back

### PR DESCRIPTION
**Pull request by 00ze-cyclone**
# Document the changes in your pull request

It's ugly, it's dumb, it's lame, it is unused. Only chance you might see this shit again is from a gift of Santa or admin. This will make sure it cannot ever appear again in any form.

Yes I hate that thing how did you notice?

# Changelog

:cl:  
rscdel: Utterly and completely erase the makeshift laser rifle, it was already unobtainable normally, now even an admin won't be able to put it back anywhere near the station.
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Someone is mad

**Comment by 00ze-cyclone** [comment]
> Someone is mad

Just a tiiiiiiny bit

**Comment by patpol4** [comment]
Also you might want to fix that changelog

**Comment by Hopekz** [comment]
> It's ugly, it's dumb, it's lame, it is unused.

All the reasons you provided aren't a removal reason but rather a rework reason to reimplement it a different way.

If you yourself don't feel like reworking it just don't touch it 👀

**Comment by cuackles** [comment]
So when i made the gauss rifle i planed to remove the laser rifle as it was meant as a diferent alternative, as for the laser rifle it should need a full rework to actually make it work more than once and make it do more damage than absolutely nothing, Wich honestly no one is gonna do, delete the fucking thing, no one uses it, it's ugly, it has no damage, it like one use and if i remember correctly it was removed from the crafting list by me so it will see no more use cus no one is willing to fix it so now it's just a waste of space

**Review by cuackles — APPROVED** [review]

**Comment by MajManatee** [comment]
I do remember cuack saying it was a replacement.
Too bad the gauss isnt used either...

**Comment by MajManatee** [comment]
@00ze-cyclone idk how but DMI conflicts

**Comment by MajManatee** [comment]
week + of inactivity with unresolved merge confliscts. Reopen when fixed

**Pull request closed without merging**
