### PR TITLE
ADVANCED CRATES

### PR DESCRIPTION
**Pull request by Nickvr628**
**ADVANCED CRATES**

image

image

They are spherical, and thus superior, and also look really cool. They are orderable from cargo as a way for the crew to buy more crates. 

image

#### Changelog

:cl:  
rscadd: Adds new type of crate, the advanced crate. Orderable from cargo under the misc tab.
/:cl:

### CODE REVIEW

**Comment by nichlas0010** [comment]
Ironic that your "better" crates come in a normal crate. Oh and this repo is still frozen, https://www.github.com/yogstation13/tg-rebase

**Comment by Nickvr628** [comment]
They have to come from somewhere nich, and they come in the late crate, not the normal one, so it makes some sense at least.

**Comment by Kmc2000** [comment]
Honestly, that’s not how to shade a circle. The black outlines and details really ruin the sprite as well as the fact that they are lacking in detail.

**Comment by Partheo** [comment]
I made this shit
fuckman

**Comment by Time-Green** [comment]
They should make a rolling motion on move

**Pull request closed without merging**
