### PR TITLE
Replaces the plasmaflood holodeck program with a lava program

### PR DESCRIPTION
**Pull request by Darkstick**
This PR replaces the "atmospheric burn test" holodeck program with the "incinerator" program, which is just a big lake of lava. 

It's a way to get rid of the EZ PLASMAFLOOD (atmospheric burn test) program on the hacked holodeck. The reason is simple: Behind two general access doors, there is a small unguarded console which lets you turn the entire station into a flaming ball of death. You can easily create an extremely powerful plasmaflood that has so much pressure it goes through firelocks before they have time to close, and fills up the station in less than a minute, leaving no room for reaction or even a call out.

:cl:  
rscadd: Added incinerator holodeck program
rscdel: Removed holodeck plasmaflood program
tweak: 
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
why not just add airlocks to it

**Comment by MegaEmpirical** [comment]
Did the burn test nerf not do enough?

**Comment by patpol4** [comment]
Personally im not a fan of the burn test program, it used to be fine but it's just not fine with monstermos. The program needs to be adapted to our atmospheric system. Probably going to merge unless this gets a lot of downvotes or someone higher up objects.

**Comment by ghost** [comment]
Okay but now add the fusion test burn on the holodeck to make up for it /s

**Comment by jcatjmeow** [comment]
Use motherfucking map merger or a program like fastdmm or strongdmm. An 88k long pr for one room is not acceptable jesus fucking christ

**Review by jcatjmeow — CHANGES_REQUESTED** [review]
use a proper mapping tool or map merger dm me if you don't know what im talking about

**Comment by ToGWtF** [comment]
Disagree, but agree that it needs a nerf.

Lava is kinda stronk. Easy peasy item deletion to remove evidence. There's only 2-3 other rooms on the station that can do that

**Pull request closed without merging**
