### PR TITLE
WOW! Moves the AI core to Science and configures Science a bit to cater for this change. 

### PR DESCRIPTION
**Pull request by nesisknesis**
When I mean Moves the AI core, I mean I gave it the big snip. It is now a lot smaller and partly exposed to space, but now has extra security measures to balance the scales.

AI Core:
image

This is where the EXPERIMENTOR used to be, meaning the AI is now apart of Science and at the backdoor of the RD. Lamarr is a shit pet. Now the AI is truly his pet.

But wait, wheres the experimentor?

Here:
image
Cozy.

Back to the AI, this shit is small as fuck, also wasnt there a maint going through here? yes, there was. its now in space.

image

Great. But isnt the AI completely buggered at the backside? Not exactly.

It now has a toggleable core shield, get rekt liberals

image

Also, the RD got some loving to their office, that budget isnt there for show.

image

Their own bed, purple comfy chair, and cyborg statue which picks from random names each round. You'll have to see what names they are in-game or by looking at the code. And that door goes directly to the AI upload access.

image
💦 

How they connect:
image

WAIT. THE ORIGINAL AI CORE?

image

gone mate.

perhaps engineering can do something meaningful with this space or at a later date someone else. cant remember who was doing the gateway but here is plenty space for one.

and finally, the bridge:

image

maybe now the heads of staff can have a nice sit down together without being isolated in a crummy meeting room. also pizza. nanotrasen doesnt leave their senior staff unrewarded

bunker mode:

image

the doors are practically the same.

answers to the questions you may have:

isnt that ai shield op. - no, it can be disabled by killing the APC located in the open area, then it requires a crowbar to pry it open. also they can be sploded by c4.

its fully surrounded by glass you moron, how does it get out. - get some tools.

that space bridge is dangerous someone could get hurt. - ok,

what is that weird ball thing near the bridge. - a radar for fluff

why that poster - rip it down or keep it there

why are you sucking the rd's phallus like this - the rd is suppossed to keep the silicons in check, and with the ai core being right next to their office, now is much easier and they have the incentive to do so since their lazy ass just have to open 2 doors from their spawn

finally final. theres an easter egg

#### Changelog

:cl:  Identification
rscadd: Adds a cyborg statue that picks from random names each round.
rscadd: Adds a purple comfy chair to the RD's office.
rscadd: Adds a radar.
rscadd: Adds a fire extinguisher to the Captain's office.
wip: Original AI core was removed. Empty space is now apparent which can be filled by anyone willing or ingame by opportunists.
tweak: The AI core is now located in Science.
tweak: The checker pattern in Science is now purple.
tweak: The Bridge has a new layout to fit with the recent change.
tweak: The EXPERIMENTOR is now located in the Testing lab, now with a new layout.
tweak: The RD office has had a makeover.
tweak: The section of sci maint to departures is now in space. SPAAAACE.
bugfix: Fixes issues with Perma cameras being named incorrectly and being on different networks.
bugfix: Escape camera taken off the RD cam network.
/:cl:

### CODE REVIEW

**Comment by DiamondSentinel** [comment]
Eww

**Comment by Codeatmos** [comment]
This looks really good for the most part, although how it will affect gameplay and antagonist or antagonistic RD's is uncertain for me. This also means that with only 1 turret a simple locker could protect you from the ai's turrets.

**Comment by nesisknesis** [comment]
Due to the AI being a controversial change, the bug fixes, the Bridge remap, the RD office, and the other small changes will be made into separate PRs if this ultimately fails.

ill also continue work on perspective structures after this which can be found in the #spriter channel

**Comment by Lostlarry** [comment]
well...
A its closer to roboticist if they decide its rouge its not gonna last that long but the turrets might actualy do something
B where does the borg spawn?
C does this mean the bridge was moved down a bit? or is it just bigger?
D dont wanna check that maint when carps arrive
E how do you activate the flasher thats on the ai core?

**Comment by nesisknesis** [comment]
image
 borg spawns there

**Comment by nesisknesis** [comment]
The bridge is just bigger,

Silicons can fire any mounted flash by clicking it.

**Comment by Lostlarry** [comment]
random idea make the inner space bridge glass walls(the ones closer to ai) plasma glass it may or may not help
also for those who think this would make subvert easy, it already easy. 
dont go to the ai upload make your own you, can do it in maint and no one checks GPS to find you
if you wanna breach a high sec area, high sec tech storage is easy as well same as sci.

second to last point What about TTS wont the ai get bombed by the high spec bombs?

the last point werent the two backup coolers there? Did you move them or are they just gone?

**Comment by Alexandria404** [comment]
oh no

**Comment by Amelia0010** [comment]
image

1. You can now breach into the AI core without being shootable by the turrets at all, just by going through space at the back
2. the AI is now vulnerable to bombs, which previously couldn't reach them from outside the bridge
>but now has extra security measures to balance the scales.
3. The AI has 2 fewer turrets as well as all the foam dispensers being gone. What do you mean when you say `extra security measures`
4. There isn't actually any way to access the AI for intellicarding, aside from beating down the window
5. This makes stealing the AI much much easier as well since you can just go through the space bridge, which the AI can't see, and you won't be in the middle of the station so everyone else can't see you either
>This also means that with only 1 turret a simple locker could protect you from the ai's turrets.
6. This is correct, before you couldn't protect yourself with just a locker but now there's only one turret at a time going into the upload which makes it much easier.
7. Speaking of turrets, now the AI can get immediately fucked through lasers if they don't set their turrets to lethal, since the turrets can't shoot through the glass, meaning they're realistically down 3 turrets instead of 2
8. I'm pretty sure you could now EMP the AI without even entering the AI's core, by shooting here with an ion rifle
image

**Comment by Alexandria404** [comment]
what he said ^^

**Comment by MegaEmpirical** [comment]
Nukies can snipe the AI from space with ease using penetrator rounds and no one will notice.

Both the consoles and the boards are easily accessible from breaking down their wall from the outside or from behind the safety of the glass if the AI is asimov. 

The two individual turrets basically can't help eachother so you only have to kill each one, one at a time which I smuhx easier. 

The 4 leading to the AI are really close together so an EMP or grenade could hit two with great ease.

Anyone wanting to disable turrets via the control needs to be standing in front of a kill zone for the first turret just to even try.

**Comment by MegaEmpirical** [comment]
On a different note, I'd recommend putting the SMES in the front room instead of hiding it in the walls.

**Comment by nesisknesis** [comment]
everything is good and green

**Pull request closed without merging**
