### PR TITLE
Ports many improvements to lighting (directional lights)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
# Document the changes in your pull request

Ports https://github.com/tgstation/tgstation/pull/54520
Ports https://github.com/tgstation/tgstation/pull/52881
Ports https://github.com/tgstation/tgstation/pull/60239

Ports https://github.com/tgstation/tgstation/pull/53239
Ports https://github.com/tgstation/tgstation/pull/53816
Ports https://github.com/tgstation/tgstation/pull/52393

This is refactoring many things about the lighting system (and opacity), which I did while trying to fix Ethereal lights (which I failed at doing- for some reason it seems to work until power goes to 2< like it's got some hardcap on and I can't figure out why that is the case). I thought I should throw this stuff up anyways because why not.

It removes an undocumented change in https://github.com/yogstation13/Yogstation/pull/17271 about some lights not contributing to lumcount, idk why that was added but if it's a problem I can re-add. I mostly just tried to get it to be as close to TG's as possible so future work on it wouldn't be as bad.

This also adds directional lights, I'm not sure if it's something that is wanted so for now I only added it to seclites. The support is there, so you can add it to wherever you want after idk I don't want to feature code.

# Why is this good for the game?

Hopefully bringing lighting closer to TG's system will make future portings easier and allow Ethereals to finally work.

# Testing

image

# Spriting

# Wiki Documentation

# Changelog

:cl:  
rscadd: Seclites now have directional lights- point them in the direction you want to see more of.
experimental: Ported over many refactors to lighting and opacity. Please report if you can walk or see through walls unintentionally.
/:cl:

### CODE REVIEW

**Comment by GDRdev** [comment]
pain

**Comment by ThatLing** [comment]
BeeStation tried porting this multiple times and had to revert each time because of various issues, did you look into these?

- https://github.com/BeeStation/BeeStation-Hornet/pull/5086
- https://github.com/BeeStation/BeeStation-Hornet/pull/8070
- https://github.com/BeeStation/BeeStation-Hornet/pull/8093

>It removes an undocumented change in https://github.com/yogstation13/Yogstation/pull/17271 about some lights not contributing to lumcount, idk why that was added but if it's a problem I can re-add

https://github.com/BeeStation/BeeStation-Hornet/pull/6092

**Comment by iloveloopers** [comment]
Preternis buff

**Comment by JohnFulpWillard** [comment]
> > It removes an undocumented change in #17271 about some lights not contributing to lumcount, idk why that was added but if it's a problem I can re-add
> 
> [BeeStation/BeeStation-Hornet#6092](https://github.com/BeeStation/BeeStation-Hornet/pull/6092)

The PR doesn't mention adding this so I think it was completely undocumented, I dont know if it was discussed at all at the time of adding but it seemed like stealth balancing stuff in a refactor pr. The PR linked has 3 TG PRs as "being ported", you're linking Bee.

**Comment by JohnFulpWillard** [comment]
For the issues, I have no way to check if flashlights break late into the round without seeing this as at least a testmerge. For the light in the corner, I remember this being an issue for some time on TG as well, but it's been fixed now.
For the issue on ethereal lights breaking, our ethereal lights are already broken and has a bandaid on top to make them work. This doesn't fix it or break it any further.

**Review by Moltijoe — APPROVED** [review]

**Review by cuackles — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
I gotta figure out why replays won't respect it's alpha

**Pull request merged**
