### PR TITLE
Moves the hoop on Eclipse's bar

### LINKED ISSUE #10603: Cannot leave mime/clown spawn on Eclipse Station Map
## Reproduction:
Try to leave spawn, but basketball net is in the way. And I don't have maint access at round start, so the only way to leave is via disposal.

### PR DESCRIPTION
**Pull request by dragomagol**
### Intent of your Pull Request
Adds accessibility to the stage on ebar_eclipse

### Why is this good for the game?
Fixes #10603 

#### Changelog
:cl:  
bugfix: moved the hoop on the eclipse bar to allow access to the stage
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
I'm assuming making it passable didnt work

**Review by patpol4 — CHANGES_REQUESTED** [review]
Put the hoop back and move the windoor one down instead. The way you did it makes it just stand out in the middle 
vivaldi_Dyu4xL34Ky

**Comment by dragomagol** [comment]
Making the hoop passable made it not work as a hoop, which I assume is functionality we want to keep. I'll change it

**Comment by patpol4** [comment]
Now you removed the pixelshift on the hoop and it still sticks out 😔 , I'll fix that for you

**Comment by dragomagol** [comment]
Thank you!

**Review by patpol4 — APPROVED** [review]
Everything checks out

**Pull request merged**
