### PR TITLE
Changes position of the MIX to Engine pump and pipes on GAXStation so they don't need re-piping shift start

### PR DESCRIPTION
**Pull request by Annoying-plant**
# Document the changes in your pull request

Removes the unnamed gas pump to engine that shared a pipe with the gas to incinerator pump and adds a mix to engine pump on the mix loop instead linked up to the SM so that atmos doesn't need re piping when something needs to be added to the SM (or a Trit mix isn't accidently piped)

this has been added where the old connector was so this has been moved to the opposite side allowing acess from a connector still as well as use of the mix pump to engine

# Changelog

:cl:  
rscadd: added new engine pipe in a position that actually makes sense 
rscadd: added connector to the opposite side 
rscdel: removed old engine pipe removed old connector
rscdel: removed old connector
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
your description is in the wrong place and if there’s no wiki or sprite stuff you can delete all of it

**Comment by ToasterBiome** [comment]
So why is this a good idea? All I see is a pipe accessible from maint.

**Comment by Annoying-plant** [comment]
> 

good point actually okay im going to change its location again but its current location makes it not difficult to use

**Comment by Annoying-plant** [comment]
okay so ive moved the location so its no can no longer be accessed via maints but you can now still pump mix to engine rather than pumping pure to engine down same path as incinerator

**Comment by Annoying-plant** [comment]
the reason i change it is cause on all other maps you pump mix to engine not pure to engine and with it being directly on line with incinerator pump there is always a trit mix going to incinerator making it not really usefull most of the time

**Comment by applepineapplepizza** [comment]
since you removed a connector to place the pipeline from mix to engine, can you add one back somewhere?
can be anywhere, maybe inbetween the freezers.

**Comment by Annoying-plant** [comment]
> 

yeah sure can do will have a look

**Comment by Annoying-plant** [comment]
Okay so ive now added in the connector on the opposite side so the mix pump is at the north side of atmos and the connector is at the south side

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
map diff has a weirdly large area changed, might need to look at if anything is being changed over there

**Comment by Annoying-plant** [comment]
> map diff has a weirdly large area changed, might need to look at if anything is being changed over there

how do I check this I'm quite new to this sorry only my second ever map change?

**Comment by Annoying-plant** [comment]
okay i think i know what ive done im going to close this for now and re open another once ive fixed the issues

**Pull request closed without merging**
