### PR TITLE
Ports Turf Fires from Horizon & Shiptest

### PR DESCRIPTION
**Pull request by VaelophisNyx**
Ports https://github.com/hrzntal/horizon/pull/300 without the flamethrower rework
and ports https://github.com/shiptest-ss13/Shiptest/pull/872 without the flamethrower sprites or rework

# Document the changes in your pull request
maintainers & more experienced people pls help it works but I bet I've done some dumb shit in here

ports Turf Fires that spread from atmos fires. These fires consume oxygen for the duration of time they have fuel, and produce CO2, while increasing the temperature of the air around them. If they are blasted with an extinguisher, or run out of oxygen, they go out. Walking onto a turf fire causes *you* to be ignited.
Turf fires are handled with existing Hotspots code, so anything that creates hotspots, creates turf fires.
turf fires in pressure equal to or less than the needed for a PKA to work, extinguish themselves very quickly.

Adds a lot of side lighting code, moves a bunch of vars up to the atom level, and ported some components that were needed.
had to do a lot of jank custom shit to sidestep https://github.com/yogstation13/Yogstation/pull/14112 never being merged

also pulse rifle projectiles produce blue fire turfs on contact. I...don't know why, other than "it looks cool". this was ported and is VERY easy to kill off.

added some fire armor to grilles since they're literally just metal rods, and die absurdly fast to fires without it

https://youtu.be/77c4E8fspdg - In game & showcases extinguishing them
https://youtu.be/_SE_TUgTvTQ - In game & showcases incendiary shells
https://www.youtube.com/watch?v=iyapNOVI02Y - shows off the pulse carbine's blue fire

# Spriting
ss (2022-08-02 at 04 11 36)
ss (2022-08-02 at 04 13 50)
ss (2022-08-02 at 04 14 01)

Adds Red, White, Blue, Green, and Greyscale (Hex-color) fire sprites

fire

# Why is this good for the game?

Because as of now, the closest thing atmospheric technicians have to do to firefighting is....spacing a room to vent its temp and gas...and either engineering already does that, or the fire was hot enough that it handles it itself by melting through the floor. This gives a new type of fire to worry about for them, and the crew at large, as well as more of a reason to need fire extinguishers, as atmos fires tend to be impossible to put out with them unless you get extremely lucky. These are also very ambient, making it a lot more clear that a room is/was on fire very recently.

This additionally makes CLF3+Phlog mixes in spray bottles a tangible danger to chemists, as they could now be ignited by poorly timed movements

this also a small buff to space dragons, and a buff/nerf to incendiary shells as they now can cause turf fires (since they're just an atmo fire in a shotgun shell), though I will note they do not cause many of them
Genetics firebreath mutation and wizard fireballs similarly would also cause turf fires in this method

# Wiki Documentation

maybe somewhere in the atmos tech guide it should mention that firefighting is important because of turf fires

# Changelog

:cl:  
rscadd: Added Turf Fires
imageadd: adds new sprites for turf fires
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
I thought of doing this a while ago lmao

**Comment by VaelophisNyx** [comment]
wishlist: someone tell me if you can  make these start on random animation frames

**Comment by VaelophisNyx** [comment]
ah shit there was supposed to be a sound for these wasn't there

**Comment by GraveHat** [comment]
Too much fire 7.8/10

**Comment by VaelophisNyx** [comment]
a note on "too much fire"
it literally cannot be helped
plasma floods will cause fucktons of fire turfs; thankfully these are minimally impactful to performance

**Review by KillerOrcaCora — DISMISSED** [review]
I would like to see the fire sprite from CM tested visually instead of the fire from ship test.

**Comment by VaelophisNyx** [comment]
I mean clone the code and test it yourself if you want. It looks trash, that's why I ported the sprites I did.

**Comment by VaelophisNyx** [comment]
like you cannot honestly tell me that this https://media.discordapp.net/attachments/134720091576205312/1003967992243179600/fire.gif
is somehow superior to
https://media.discordapp.net/attachments/440551954788253697/1003861671774789682/fire.gif

**Comment by redmoogle** [comment]
do wood turfs/objectes burn up

**Comment by neeshacark** [comment]
> like you cannot honestly tell me that this https://media.discordapp.net/attachments/134720091576205312/1003967992243179600/fire.gif is somehow superior to https://media.discordapp.net/attachments/440551954788253697/1003861671774789682/fire.gif

i prefer cm's. this one looks way too cartoonish

**Comment by VaelophisNyx** [comment]
> > like you cannot honestly tell me that this https://media.discordapp.net/attachments/134720091576205312/1003967992243179600/fire.gif is somehow superior to https://media.discordapp.net/attachments/440551954788253697/1003861671774789682/fire.gif
> 
> i prefer cm's. this one looks way too cartoonish

CM's looks like ass. it barely animates at all, and is visually a mess

**Comment by JamieD1** [comment]
Am I the only one to think it looks like ass?

**Comment by KillerOrcaCora** [comment]
Ima be honest, this does not look appealing, something is just off about it. At the end of the day, I would also just slot for CMs fire, but even then, this is just jarring to look at. Seeing that cuackles was in no hurry to approve, I'm closing this.

**Comment by cuackles** [comment]
I actually just saw the comment over this one, I'm currently on leave because my PC is mostly broken, so i only go to GitHub in specific cases, do i have to say that when it comes around to big fires it does look jarring, i do like it in it's application to small contained fires but when it comes to Atmos fires it looks a bit odd, if you ever decide to retake this pr in another twist, i might say that making fires not being able to spawn next to each other would probably go a long way, and also trying to make them so they aren't synced up, if one or both of those conditions where met, i would strongly consider merging it, sorry for not paying to much attention to GitHub but seeing sprites in a phone isn't the best way to notice small details

**Pull request closed without merging**
