### PR TITLE
Tweaks inspector booth

### PR DESCRIPTION
**Pull request by wonderinghost**
Makes the inspection booth be completed without the need of stamps. also making it available to all departments
:cl:  

tweak: Inspection booth is now made in all departments and dont need stamps to complete

/:cl:

### CODE REVIEW

**Comment by GDRdev** [comment]
Does it still have the approve and deny stamps built-in?

**Comment by wonderinghost** [comment]
> Does it still have the approve and deny stamps built-in?

no but you can install them after completion. or install a bunch of random stamps

**Comment by JohnFulpWillard** [comment]
This machine needs to stop using copyrighted assets and sounds

**Comment by wonderinghost** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
is it just the stamps?

**Review by wonderinghost — COMMENTED** [review]
accidentally updated my branch

**Pull request closed without merging**
