### PR TITLE
[PORT] Steals reflective surfaces from bee before their PR is even merged

### PR DESCRIPTION
**Pull request by Moltijoe**
https://github.com/BeeStation/BeeStation-Hornet/pull/9898

# Why is this good for the game?
Looks nice, also biome asked me to

it "works" but doesn't look quite right yet
image

also runtimes, i know not what arcane powers with which i dabble
image

also had to port a couple extra filter procs
also didn't port the buffer because i didn't bother to

:cl:  @DrDuckedGoose @Moltijoe 
add: Add reflections to shiny surfaces
add: Add mapping tools to make custom shiny surfaces
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Put photos of what wet surfaces look like cus in the original or it looks great

**Comment by Moltijoe** [comment]
> Put photos of what wet surfaces look like cus in the original or it looks great

image


consider, in motion

https://github.com/yogstation13/Yogstation/assets/108117184/9a6549ed-686a-4cba-8535-35848e1e04bf

**Comment by RG4ORDR** [comment]
Is this a good idea seeing as the lighting system is dookie?

**Comment by neeshacark** [comment]
this is cool but they look exceptionally goofy in motion

**Comment by DrDuckedGoose** [comment]
Doesn't look quite like ours. I wonder if you ported everything properly?
image


> > Put photos of what wet surfaces look like cus in the original or it looks great
> 
> image
> 
> consider, in motion
> 
>  2023-09-26.23-35-35.mp4

**Comment by PowerfulBacon** [comment]
Based on how it works, moving around will give that effect because the reflections are the game plane with a displacement filter. There is just no way to change that

**Comment by azzzertyy** [comment]
raytracing when?

**Comment by MajManatee** [comment]
REALLY cool

**Comment by Moltijoe** [comment]
> Based on how it works, moving around will give that effect because the reflections are the game plane with a displacement filter. There is just no way to change that

Its flipped and displaced
The issue is that when it gets flipped, the movement is also flipped
I just dont know enough about filters to fix that

**Comment by Moltijoe** [comment]
> Doesn't look quite like ours. I wonder if you ported everything properly? image

Pretty sure those differences are because of our tiles having different sprites and differences in our lighting system

**Review by cuackles — APPROVED** [review]

**Comment by Moltijoe** [comment]
@cuackles you really approved this shit? even after watching the video? it definitely needs work before it can be merged

**Comment by cuackles** [comment]
> @cuackles you really approved this shit? even after watching the video? it definitely needs work before it can be merged

It looks good and I have faith that you will fix the weird movement thing before merge

**Comment by Moltijoe** [comment]
> It looks good and I have faith that you will fix the weird movement thing before merge

bruh

**Comment by cuackles** [comment]
> > It looks good and I have faith that you will fix the weird movement thing before merge
> 
> bruh

You better do it

**Comment by DrDuckedGoose** [comment]
The 'weird' movement is pretty much a hard limitation of a performant system, the majority of fixes / improvements will probably tank the performance. I always thought it looked okay-ish enough to suspend my belief.

**Comment by Moltijoe** [comment]
> The 'weird' movement is pretty much a hard limitation of a performant system, the majority of fixes / improvements will probably tank the performance. I always thought it looked okay-ish enough to suspend my belief.

yeah, that's what i was worried about, it would need to dynamically update the offset of the overlay as the thing casting the reflecting moves

**Comment by DrDuckedGoose** [comment]
lmao

**Comment by Moltijoe** [comment]
> lmao

ye, i'm nothing if not lazy

**Pull request closed without merging**
