### PR TITLE
De-Insularisation of Genetics and Xenobiology

### PR DESCRIPTION
**Pull request by Lovebird-Frungy**
# Document the changes in your pull request

Expands the station by adding a new hallway, in order to give genetics and xenobiology some public access, they now have desks to answer requests.
Service hall has also been brought back to the forefront so it isn't that much of a hassle to access it.
Maints were rearranged a bit to fit the new size.
CMO office widened too in order to accommodate, runtime now has some toy and free milk and the cmo has his own private sleeper to treat vip patients.
Botany backroom widened in the same fashion.
Cloning became wide too!!
Blob has a new spawner in the newly widened maints.

Pictures
image
image
image

# Wiki Documentation

Xenobiology and genetics now have desks to interact with crew members.
Service hall is now accessible via main hallways, like old times!
A new area: Aft Starboard Hallway.

# Changelog
:cl: Lovebird
tweak: widened the station, bringing some obscure departments to the forefront.
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
merge conflict moment
good luck

**Comment by ToasterBiome** [comment]
is this taken from somewhere? I can see genetics is different but no picture of it

**Comment by Marmio64** [comment]
too many windows for botany backroom and service hall. Service hall shouldn't have a window at all and botany backroom is way too visible and makes it even harder to try to attack botanists from maint. Also i'm not sure if you fixed after taking the picture or if im looking at it wrong, but disposals may be broken above the botany backroom.

**Comment by maxion12345** [comment]
You'll need to revert the changes and pull from master to resolve conflict, then redo the changes. You can copy pasta from fastdmm though so you don't gotta re-do it again entirely

I think unless someone knows a better way

**Comment by KittyNoodle** [comment]
human interaction, in my xenobio????

**Comment by Lovebird-Frungy** [comment]
Closing this pr and opening a new one on another branch as per me fucking up the code even worse.
I am bad at computers. I have no idea what the commands do.

**Pull request closed without merging**
