### PR TITLE
the ultrakill martial art is now not as hot garbagio

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
currently it's boring and overpowered, you can pull infinite revolvers out of your ass and spam them from range, if you ever get in trouble you can just warp away at light speed, but all the other moves are borderline worthless for actual combat so the only thing you can do is spam infinite 357s.

Changes:
Revolver damage reduced to 30, AP removed.

Spawning a revolver will take 1 dash charge, and cannot spawn if you have no dash charges.

Dash charges no longer recover by themselves, and require combos to recharge.

The shotgun combo will restore 1 dash charge

Blood burst renamed, now requires 4 harm hits again, fully recharges dash and will also shoot the target with a syndicate shotgun shell.

Stun immunity removed

Button to remove stuns and heal 75 stamina damage added, costs 1 dash charge to use

Whiplash added. Can pull you to targets, will immobilize whoever you hit for two seconds, giving you the opportunity to start comboing them. Costs 1 dash charge.

Hard crit immunity removed

# Changelog

:cl:  
tweak: slightly adjusted the ultrakill martial art
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
gotta give props where props are due, you spent more time to rebalance it rather than making another half-ass "i removed it hehe" type PR.
I genuinely think there are good ideas here, but might need some tweaks to avoid losing some amount of identity
I've provided it to balance council and stated my opinions there, and will wait to see what they think
something of note, i think sarah was also working on a rework at the same time, so it depends on what she come out with

**Review by Moltijoe — CHANGES_REQUESTED** [review]
please update the changelog to be more accurate as to what is being changed about the martial art

**Comment by UltraBigRat** [comment]
dislikes ranged playstyle and how all the other moves suck
 removes stun immunity making loud melee combat less viable
 B a l a n c e

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> dislikes ranged playstyle and how all the other moves suck removes stun immunity making loud melee combat less viable B a l a n c e

ikr, wouldn't it have been helpful if some kind of button to remove stun effects at the cost of some kind of resource was added to compensate for the stun immunity removal

**Comment by MajManatee** [comment]
this is a certified gus pr...

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> this is a certified gus pr...

i gussed your dad

**Comment by TheRyeGuyWhoWillNowDie** [comment]
nevermind i got told to suck eggs

**Pull request closed without merging**
