### PR TITLE
Lasers can no longer break or target windows

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

how the hell you supposed to shoot a window with a laser
# Spriting

# Wiki Documentation

n/a
# Changelog

:cl:  
tweak: Lasers can no longer break or target windows
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
At this point just add space thermodynamics.
This isnt there because it makes sense, but for balance reasons.

And as a counterpoint: Only certain frequencies of light emessions pass through glass.

**Comment by Simplehorror** [comment]
> At this point just add space thermodynamics. This isnt there because it makes sense, but for balance reasons.
> 
> And as a counterpoint: Only certain frequencies of light emessions pass through glass.

red light can clearly go through glass and lasers are red

**Comment by Maia-J** [comment]
> > At this point just add space thermodynamics. This isnt there because it makes sense, but for balance reasons.
> > And as a counterpoint: Only certain frequencies of light emessions pass through glass.
> red light can clearly go through glass and lasers are red

Make them invisible and infrared then, improve don't remove.

**Comment by Simplehorror** [comment]
glass is transparent to infrared

**Comment by Maia-J** [comment]
> glass is transparent to infrared

Only to short-wave infrared, which isnt even close to light letalone heat emmisions

**Comment by CMOisLing** [comment]
You guys are discussing this, while light travels as fast as a dude on a skateboard. Can we have another reason other than realism when we are talking about star wars lasers?

**Comment by Hopekz** [comment]
Something that always didn't make sense to me. If lasers pass through glass how could it target and destroy it?

**Comment by Cartlord** [comment]
...I just figured you were shooting the window-frame, especially since the deconstruct messages mention prying it out of said frame.

**Comment by Sniblet** [comment]
You just angle the laser gun so it ricochets off the glass, which damages it

**Comment by Hopekz** [comment]
I guess everyone's trying to use realism arguments so I'm replying with realism as well.

> ...I just figured you were shooting the window-frame, especially since the deconstruct messages mention prying it out of said frame.

That's some expert shooting. How do you even do that at range? If it works like that then you would only be able to do it right next to it to aim at the frame. 

> You just angle the laser gun so it ricochets off the glass, which damages it

That's not what glass in-game currently does. 
When you shoot through the glass at an angle in game it still passes through it. That's also something I would accept since it conforms to reality but that isn't how it is coded in the game at the moment so this PR takes it closer to what you want it to be.

**Comment by ReddicusDragon** [comment]
> # Document the changes in your pull request
> how the hell you supposed to shoot a window with a laser
> 
> # Spriting
> # Wiki Documentation
> n/a
> 
> # Changelog
> 🆑 tweak: Lasers can no longer break or target windows /🆑

I'm redddragon and I find these changes dogshit

**Comment by Hopekz** [comment]
> I'm redddragon and I find these changes dogshit

Can you provide a "why?" Or is your opinion meant to be immediately disregarded

**Comment by Hopekz** [comment]
> > I'm redddragon and I find these changes dogshit
> 
> Can you provide a "why?" Or is your opinion meant to be immediately disregarded

**Comment by ReddicusDragon** [comment]
> > I'm redddragon and I find these changes dogshit
> 
> Can you provide a "why?" Or is your opinion meant to be immediately discarded

everyone is using realism arguments and that's dogshit -- it's a video game not real life. It's supposed to be fun not realistic.

**Comment by Hopekz** [comment]
>  It's supposed to be fun not realistic.

I guess the real question is why is being able to destroy glass with lasers more fun?

If anything not having the ability to hit it would make things more consistent in the game since you can shoot through it.

Games either have "shoot through it" or " can't shoot through it" but not both like we currently have

**Comment by ReddicusDragon** [comment]
> > It's supposed to be fun not realistic.
> 
> I guess the real question is why is being able to destroy glass with lasers more fun?
> 
> If anything not having the ability to hit it would make things more consistent in the game since you can shoot through it.
> 
> Games either have "shoot through it" or " can't shoot through it" but not both like we currently have

The answer is being able to destroy glass with lasers is more fun because funny haha "I'm going to shoot you." If you don't want people to shoot your glass out easily reinforce your windows.

**Comment by MajManatee** [comment]
this is simply a bad change

**Comment by githubuser4141** [comment]
> Something that always didn't make sense to me. If lasers pass through glass how could it target and destroy it?

A window isn't 100% glass, you're probably aiming for the frame/attachment points.

"That's some expert shooting"

Hm, well, yeah. If you're an antag you're a trained shooter. If you're sec same thing. If you're neither you're a validhunter.. /s

Otherwise, no? It's a laser gun, so no recoil. It's also a laser, so it goes where you aim it. Combat in SS13 takes place in literal arms-reach range. So like ~10 meters or less. I think it's believable that someone with good or excellent eyesight could aim at a windowsill  at about ~10 meters with a recoiless, 100% accurate gun - it's also logical that spesspeople (ASTRONAUTS!) would have excellent eyesight and/or eye augmentations.

Here is a window w/frame for example: (from google images) 

image

**Comment by ilikesaying** [comment]
since we're going for more realistic laser weapons let's also make them hitscan

**Comment by ReddicusDragon** [comment]
> since we're going for more realistic laser weapons let's also make them hitscan

There already *is* code for hitscan, it's possible

**Comment by Hopekz** [comment]
> > Something that always didn't make sense to me. If lasers pass through glass how could it target and destroy it?
> 
> A window isn't 100% glass, you're probably aiming for the frame/attachment points.
> 
> "That's some expert shooting"
> 
> Hm, well, yeah. If you're an antag you're a trained shooter. If you're sec same thing. If you're neither you're a validhunter.. /s
> 
> Otherwise, no? It's a laser gun, so no recoil. It's also a laser, so it goes where you aim it. Combat in SS13 takes place in literal arms-reach range. So like ~10 meters or less. I think it's believable that someone with good or excellent eyesight could aim at a windowsill  at about ~10 meters with a recoiless, 100% accurate gun - it's also logical that spesspeople (ASTRONAUTS!) would have excellent eyesight and/or eye augmentations.
> 
> Here is a window w/frame for example: (from google images) 
> 
> image
> 

This just shows me that it can go both ways in the realism department so this choice should be done for gameplay/balance instead.

Not really sure what direction I'd go for that but I like consistency in games so I'd probably personally prefer the "passes through all glass" behavior.

**Comment by chemistrymain2** [comment]
> since we're going for more realistic laser weapons let's also make them hitscan

surprisingly not that unfair on vg, the main issue is that hitscan code here has the projectile just has infinitely fast travel time, so it hits people you're not aiming at and spam works

if you want fair hitscan, you'll have to ensure the projectile stops exactly where you shoot and no farther so that you actually need to click on the target entirely, and not where they will be or half a tile to the side (which is how it works on vg)

which is a giant pain in the ass

anyway this pr sucks lol

**Comment by chemistrymain2** [comment]
> > I'm redddragon and I find these changes dogshit
> 
> Can you provide a "why?" Or is your opinion meant to be immediately disregarded

you should disregard my opinion because i'm gitbanned but it's a balancing issue when you can't shoot down windows or grilles, given (clock cult) the amount (clock cult)of antagonists (clock cult) who rely (clock cult) on obstacles (clock cult)

**Comment by Simplehorror** [comment]
> > since we're going for more realistic laser weapons let's also make them hitscan
> 
> surprisingly not that unfair on vg, the main issue is that hitscan code here has the projectile just has infinitely fast travel time, so it hits people you're not aiming at and spam works
> 
> if you want fair hitscan, you'll have to ensure the projectile stops exactly where you shoot and no farther so that you actually need to click on the target entirely, and not where they will be or half a tile to the side (which is how it works on vg)
> 
> which is a giant pain in the ass
> 
> anyway this pr sucks lol

need lag comp for hitscan

**Review by Moltijoe — APPROVED** [review]

**Comment by ToasterBiome** [comment]
This does not fit in with the current vision of the game.

**Pull request closed without merging**
