### PR TITLE
fixes more things

### LINKED ISSUE #3109: Viro aux atmos manual pump starts on
Should start off and turned on when needed.

image

### LINKED ISSUE #3110: Atmos gas supply consoles do not seem properly set up
None, or nearly none, of the supply consoles for each gas tank seem properly connected to their tanks. Preventing proper control.

### LINKED ISSUE #3111: Distribution and Waste Monitor does nothing
Found in Atmos Monitoring/front office.

To the best of my knowledge this monitor has been defunct for a long time. Should just remove it.

### PR DESCRIPTION
**Pull request by Ktlwjec**
fixes #3111 
fixes #3110 
fixes #3109

### CODE REVIEW

**Comment by thehighwayman** [comment]
just tested it. still brokened.

**Comment by thehighwayman** [comment]
also why no atomizing?

**Comment by Ktlwjec** [comment]
please do not joke on my prs, liam

**Comment by thehighwayman** [comment]
alt text Someone put two atmospheric alert consoles next to each other. why is it a joke when I bring up valid issues?

**Comment by MegaEmpirical** [comment]
And the waste disposal one can just go, it's non-functional.

**Comment by Ktlwjec** [comment]
Yes, the console on the right?
was this /obj/machinery/computer/atmos_control/tank{
	name = "Distribution and Waste Monitor"
now this /obj/machinery/computer/atmos_alert{
	name = "Atmospheric Alert Console"

replaced with a second atmos monitor, one by the desk one there

**Pull request merged**
