### PR TITLE
slipping does not stop tail wagging

### PR DESCRIPTION
**Pull request by Sniblet**
# Document the changes in your pull request

Slipping does not stun you for any appreciable length of time, but it does still stun you
Because of this waggers who slip stop wagging, but can just type *wag again immediately to begin wagging again
So the only thing that really does is annoy them
We don't like annoying people who play our video game do we

do we

That's right we don't. This removes an unnecessary annoyance in slipping

- [x] tested
- [x] works

# Changelog

:cl:  
tweak: waggers are not discouraged by slipping
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Ayeee

**Comment by Smudged** [comment]
Slipping should probably stop tail wagging.

**Comment by KittyNoodle** [comment]
How is this a fix

**Comment by alexkar598** [comment]
Not a fix, PR closed

**Comment by Sniblet** [comment]
> Not a fix, PR closed

Don’t scare me like that, it’s happened enough this past month

**Comment by JamieD1** [comment]
It might be better to make a proc instead of adding the same to all these files

**Comment by Sniblet** [comment]
I haven't forgotten about this I just still haven't thought of a way to do it
For instance I don't know how to make procs

**Comment by Sniblet** [comment]
Putting the ravening hordes of blind unthinking anti-furry protestors well aside this now functions as intended

**Comment by JamieD1** [comment]
Add this check to the handle_slip proc instead in Yogstation\code\game\turfs\open.dm Around line 444

**Comment by Sniblet** [comment]
> Add this check to the handle_slip proc instead in Yogstation\code\game\turfs\open.dm Around line 444

Here?
https://github.com/Sniblet/Yogstation/blob/03b8e3cad65a3cc56f08010c6407ba30e84c4270/code/game/turfs/open.dm#L450
I don't see a stun that I can build it around. I had it at line 477 before and it didn't do anything.

**Comment by JamieD1** [comment]
Remade in #13754

**Comment by Sniblet** [comment]
The remake doesn't do anything, this has been closed without being effectively replaced

**Pull request closed without merging**
