### PR TITLE
Radballs no longer damage machines/structures (QoL change)

### PR DESCRIPTION
**Pull request by warface1234455**
# About pr
QoL change

# Document the changes in your pull request
machines/structures no longer take damage from radball

# Wiki Documentation
machines/structures no longer take damage from radball# Changelog

:cl:  
tweak: machines/structures no longer take damage from radball
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
https://en.wikipedia.org/wiki/Radiation_damage

**Comment by VaelophisNyx** [comment]
AI Buff

**Comment by warface1234455** [comment]
> https://en.wikipedia.org/wiki/Radiation_damage

in ss13 nuclear particles are neutron, and neutron can go through any solid material

**Comment by ShoziOffical** [comment]
> https://en.wikipedia.org/wiki/Radiation_damage

this is ss13 and i think radballs are just neutron and they just go through material right

**Comment by JamieD1** [comment]
What, electronics are always affecting by radiation, never heard of a bitflip?

**Pull request closed without merging**
