### PR TITLE
Traitor Roboticist Item: AI Camera Laser Gun

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
A new role-restricted item for Roboticist and Research Director called that can be installed in an unlocked AI Control Console to grant the AI a new ability. It costs 8 TCs. AIs can be only installed with this item once.

The selected AI gets the ability to shoot a laser (20-damage) every 10 seconds at a selected target from the nearest camera to the target. The selected camera is hit with a heavy emp as a drawback for using it.

Installing one of the few AI upgrades (i.e, surveillance/malf upgrade) no longer runtimes.

# Why is this good for the game?
A new quirky item for traitor roboticists that want to lean into the silicon-aspect of their job (wow, teamwork!) instead of buying an emag, mech piloting book, pilot suit, and then going on a murderous rampage with a gygax. Gives people a real good reason to cut every camera in existence when they meet a silicon-sympathizing traitor.

# Testing
image

Cooldown set to 1 second for testing purposes.
lasergun

# Spriting
Button. Not new sprite:
image

# Wiki Documentation
Add to Syndicate Items. 
- Name: AI Camera Laser Gun Upgrade
- Description: A disk containing experimental and illegal software that allows an AI to temporarily override the safety features on their cameras, enabling them to shoot a laser beam out of them.
- Cost: 8
- Role Restricted: Roboticist & Research Director. 

# Changelog
:cl:  
rscadd: Roboticist role-restricted traitor item that enables AIs to shoot a laser from a non-disabled camera. Costs 8 TCs and requires access to an unlock AI Control Console to install.
rscadd: Only obtainable via a camera laser upgrade disk, AI can get an ability to shoot a 20-damage laser from a nearby camera. 10-second cooldown. Cameras get hit with heavy EMP'd after use.
bugfix: Hitting an AI control console with an upgrade no longer runtimes.
spellcheck: Logging regarding upgrading the AI with disks has better formatting.
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
If this is getting  merged, can you add this for malf AI?

**Comment by Runian** [comment]
> If this is getting merged, can you add this for malf AI?

Sure, but there is no point in doing so unless malf is planned to be enabled soon.

**Comment by iloveloopers** [comment]
8 TC to tickle someone every 10 seconds

**Comment by wonderinghost** [comment]
sec ai buff

**Comment by 00ze-cyclone** [comment]
> 8 TC to tickle someone every 10 seconds

A 20 burn damage (half our species get hurt more by burn) potshot isn’t bad to either finish off someone or kill them through attrition since most normal people don’t carry meds. The ability to shoot someone without them being able to shoot you is valuable, it does however require to get the AI on your side.

**Comment by AMyriad** [comment]
I like this a lot. Very interesting and unique tool to give a subverted AI. But wouldn't the camera shutting off permanently be very awkward for the AI? It would mean dealing 20 damage (if the shot even hits) and then losing the ability to control most of the room/area. Losing vision is a great drawback, and the shot would have to be used rarely because of it.

**Comment by Runian** [comment]
> But wouldn't the camera shutting off permanently be very awkward for the AI?

EMPs only shut off the camera for 90 seconds. Cameras would shut off permanently only if someone decides to cut or break the cameras, but that is expected when people realize that the AI can shoot lasers from any room with a camera.

**Comment by Moja10** [comment]
Worthless at 10 seconds per shot

Make it so it can shoot rapidly, honestly anywhere between .5 to 1 second per shot, for a limited time, say 30 seconds, and then go on cooldown for 1 minute. Change numbers as you see fit, but that creates sudden burst of action and chaos rather than just 1 stinker every 10 seconds

otherwise, awesome idea

**Comment by MajManatee** [comment]
Maybe some sort of heat mechanic so you can in theory fire rapidly but if you fire too many then it overheats and shuts down for a minute.

**Comment by azzzertyy** [comment]
> Worthless at 10 seconds per shot
> 
> Make it so it can shoot rapidly, honestly anywhere between .5 to 1 second per shot, for a limited time, say 30 seconds, and then go on cooldown for 1 minute. Change numbers as you see fit, but that creates sudden burst of action and chaos rather than just 1 stinker every 10 seconds
> 
> otherwise, awesome idea

I strongly disagree.
In its current state this is VERY strong, and, well, probably op?
It doesn't really matter even if it were at 30 seconds per shot, because, well, Youre not escaping it, not easily that is.
Its a gun that can aim at you from anywhere in the station from almost any position that requires planning, time, and investment to remove. It's strong.

**Comment by UltraBigRat** [comment]
> > Worthless at 10 seconds per shot
> > Make it so it can shoot rapidly, honestly anywhere between .5 to 1 second per shot, for a limited time, say 30 seconds, and then go on cooldown for 1 minute. Change numbers as you see fit, but that creates sudden burst of action and chaos rather than just 1 stinker every 10 seconds
> > otherwise, awesome idea
> 
> I strongly disagree. In its current state this is VERY strong, and, well, probably op? It doesn't really matter even if it were at 30 seconds per shot, because, well, Youre not escaping it, not easily that is. Its a gun that can aim at you from anywhere in the station from almost any position that requires planning, time, and investment to remove. It's strong.

The planning time and investment: Screwdriver and wirecutter

**Comment by azzzertyy** [comment]
> > > Worthless at 10 seconds per shot
> > > Make it so it can shoot rapidly, honestly anywhere between .5 to 1 second per shot, for a limited time, say 30 seconds, and then go on cooldown for 1 minute. Change numbers as you see fit, but that creates sudden burst of action and chaos rather than just 1 stinker every 10 seconds
> > > otherwise, awesome idea
> > 
> > 
> > I strongly disagree. In its current state this is VERY strong, and, well, probably op? It doesn't really matter even if it were at 30 seconds per shot, because, well, Youre not escaping it, not easily that is. Its a gun that can aim at you from anywhere in the station from almost any position that requires planning, time, and investment to remove. It's strong.
> 
> The planning time and investment: Screwdriver and wirecutter

ok, youve taken one down, you move 5 steps to the right and, youre in range of another, oh and the time you spent removing the last one is just enough for the cooldown, so youre getting shot again.

**Comment by Moltijoe** [comment]
Balance Council:
>An antag item shouldn't be reliant on subverting the AI, subvert the AI is already very strong, and creating an item who's sole purpose is to empower the subverted AI to essentially shut down any counter attack is not something a regular traitor should be capable of. Were this a traitor AI item or perhaps a malf AI upgrade it would be more reasonable.
It also doesn't much suit the roboticist who's goal is to deal with cyborgs, not AIs which is the netmin's job.
A better suited item for roboticist might be a pda controlled turret that's disguised as a camera or something

**Pull request closed without merging**
