### PR TITLE
[ASTEROID] Redesigns  Perma

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

It was kinda boring so I gave it some TLC

image

# Wiki Documentation

Asteroid Perma looks like this

# Changelog

:cl:  
mapping: Redesigns AsteroidStation Perma
/:cl:

### CODE REVIEW

**Comment by CrazyDrakkon** [comment]
It's illegal to use that kitchen knife illegally.

**Comment by neeshacark** [comment]
i do not like the way you shocked those windows

it is NOT CONSISTENT

AAAAAAAAAAAAAA

**Review by Ethan4303 — APPROVED** [review]
other then the trims cutting off just outside of perma, which might be because your still doing trims, everything else looks good (you wont respond fast enough on discord) >:(((((

**Review by Ethan4303 — APPROVED** [review]
Biome loves me ignore the previous commit message

**Pull request merged**
