### PR TITLE
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

### PR DESCRIPTION
**Pull request by JamieD1**
image

Fixes.

image

:cl:
tweak: Changed the direction of the camera in genetics which was annoying me so much that I had to open fastdmm2 to alter its position from the stupid glass to the more solid wall, now people in genetics will not shat their pants when they look at it and in future will be happy they are being watched by a camera and not bemused by the lack of phyyyyyysics holding up the camera when they break the glass.
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
nah

**Review by ToasterBiome — DISMISSED** [review]
changelog and fill out the template

**Review by ToasterBiome — APPROVED** [review]
looks like shit

**Comment by adamsong** [comment]
Self merge

**Pull request merged**
