### PR TITLE
New Security Tools: Rainbow 6 Edition

### PR DESCRIPTION
**Pull request by Nickvr628**
Ever conduct a security raid but realize the departmental officer didn't attend, and/or the AI is unavailable? Never again be locked out of the science lab preventing you from ~~executing~~ arresting the gang inside, with the new Tactical Breaching Shotgun!

image

This holds a brand new type of shotgun ammo, the Breacher Round, which can break most windows (but not grilles under them) instantly and shoot down airlocks in 3 shots. However, it only deals 10 damage to everything else, so using it on people would be pretty dumb. Consequently, this compact device only holds 3 rounds and only holds the breaching ammo. The ammo, however, can be loaded into any shotgun and can be found in a box in the armory or is producible inside the security protolathe for 4000 metal.

image

More security tools are always good to add as it lets security explore additional options to deal with station challenges. Officers can take one of these to Reebe, for example, to help the crew by breaking down cult doors. They are also great when raiding departments as a group as it can break down welded or bolted doors. Alternatively, it can be used to quickly make window entry points to surprise defenders. 

The main drawback of this device is the low ammo capacity, and the fact that the ammo is expensive to make and only does 10 damage to anything not a door or window. 

This PR also includes RnD support for the included items for balance.

:cl:  
rscadd: The armory now contains breaching shotguns and specialized breaching ammo for them. Use them to quickly break down doors and create entry points, but they are nearly useless against people.
/:cl:

### CODE REVIEW

**Comment by OppressedCactus** [comment]
I like this PR, I much prefer ballistic security weapons to laser ones (they are just cooler) so more options other than the riot shotgun and auto rifle are appreciated. 

And it certainly looks more fun than stealing an RCD to break down doors during sec raids.

**Comment by Nickvr628** [comment]
Also, I forgot to mention, this is a good tool against rogue AIs as it lets you get through bolted shocked doors with minimal risk.

**Comment by alexkar598** [comment]
This severely goes against the energy only weapon style nanotrasen has, fitting more the syndicate projectile based weaponery

**Comment by Nickvr628** [comment]
Well first you don’t get to make the lore argument because:
https://media.discordapp.net/attachments/493951730321457152/658019641670500372/unknown.png

And also security already has shotguns as a main part of their inventory, nothing wrong with new shotgun based tools. Besides, I expect the shells to be used more than the standalone device, ie loading 3 breaching shells into the shotgun and then buckshot after for raids. Security is not going full ballistic anytime soon.

**Comment by LoliconSlayer** [comment]
The fuck? NanoTrasen does use ballistics.
Riot Shotgun - Armory
Compact Combat Shotgun - Warden
Combat Shotgun - Cargo
WT-550 Autorifle - Cargo
.38 Revolver - Detective
Unica 6 - ERT and DeathSquad

Anyway, point is that NT doesn't have this "Energy weapons only" Style you speak of

**Comment by Nickvr628** [comment]
Thanks to alex this pr just got fucked, lets see if I can fix it

**Pull request closed without merging**
