### PR TITLE
Gives jackboots 1 damage

### PR DESCRIPTION
**Pull request by patpol4**
# Document the changes in your pull request

The boots are really solid, it makes sense for them to be able to break things, albeit very slowly.

# Wiki Documentation

no idea if there's a shoe wiki page

# Changelog

:cl:  
tweak: Gives jackboots 1 damage
/:cl:

### CODE REVIEW

**Comment by maxion12345** [comment]
boot powercreep

**Comment by Iplayforss13** [comment]
Reject boots return to feet

**Review by adamsong — APPROVED** [review]
Code does as described

**Comment by Bibby0110** [comment]
good pr

**Pull request merged**
