### PR TITLE
No gravity no longer screws over shadowlings

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request

Shadowling: NOOO YOU CANT COMPLETELY NEGATE MY SPEED AND MOVEMENT CAPABILITYS JUST BY SHUTTING DOWN THE GRAVITY GEN

AI: hehe gravity off button go bonk
:cl:  
tweak: shadowlings should no longer get screwed over by no grav   
/:cl:

Tested!

### CODE REVIEW

**Comment by Takahiru** [comment]
test it

**Comment by fluffe9911** [comment]
I have no way to test this atm

**Comment by Takahiru** [comment]
eventually

**Comment by fluffe9911** [comment]
Xoxeyos tested it for me and it dont work so closing this

**Comment by fluffe9911** [comment]
Nevermind it works honk

**Comment by Xoxeyos** [comment]
It works, I tested it for him

**Comment by Ratvar** [comment]
Well, now shadowlings will always toggle gravity off, is that a good thing

**Comment by JamieD1** [comment]
Lets give it a go, if its too much we can revert.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
