### PR TITLE
Allows lizards to be round start RD and CE

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Allows lizards to be round start CE and RD. I guess late join too. point is they can be the job now when they spawn in.

"But WHY" I hear you asking, allow me to explain.

We have lizards as HoS, so there is already no issue with them working as crucial roles. 
Why wouldn't you want someone who is willing to work just as hard, but for 0.6 the pay?
Someone just as qualified but far more expendable should something go wrong.

And yes I hear you saying "Lizard RD? How will they deal with Asimov ai?"
we call this a "perk of the job"
also, every race (except moths) can be the RD already, so how is this any different?

# Wiki Documentation

I'm sure it needs something but frankly, I don't know

# Changelog

:cl:  
rscadd: Allows lizards to be CE and RD. It's (Current year) guys.
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Bad

**Comment by yacabo** [comment]
Horrible

**Comment by TheRyeGuyWhoWillNowDie** [comment]
fetish content

**Comment by SomeguyManperson** [comment]
-2

**Comment by adamsong** [comment]
Hugbox

**Comment by DeadlyBag** [comment]
Horrible idea

**Comment by 00ze-cyclone** [comment]
Why should lizard able to occupy every command role other than HoP and captain while all other non humans only have 2? They're already the only non humans able to be HoS.

**Comment by Cartlord** [comment]
The clear solution is to remove Lizard Heads of Security.

**Comment by MajManatee** [comment]
I do think that could be an option. HoS could be made human only

**Comment by ToasterBiome** [comment]
> I do think that could be an option. HoS could be made human only

make them all human only

**Comment by MajManatee** [comment]
my next pr will remove all races except lizard. this is just the first step
we will be lizardstation (tm)

**Comment by ghost** [comment]
> The clear solution is to remove Lizard Heads of Security.

To remove lizards from the game

**Comment by Simplehorror** [comment]
power creep

**Comment by Moja10** [comment]
actually no

**Comment by Anvilman6** [comment]
Doesn't keep in line with the original intent of #11505. Lizards are too stupid to do engineering or research.

Sorry, but no

**Pull request closed without merging**
