### PR TITLE
Shadowlings can no longer be cloned

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Somebody broke this, they used to be NODNA so you couldn't clone them like husks.
# Spriting

# Wiki Documentation

# Changelog

:cl:  
bugfix: Shadowlings can no longer be cloned
/:cl:

### CODE REVIEW

**Comment by SapphicOverload** [comment]
Doesn't this also prevent plasmamen from being cloned?

**Comment by Bibby0110** [comment]
funny

**Comment by Simplehorror** [comment]
> funny

this is a bug, this isn't how it used to work, someone broke it AGAIN. it doesnt' even work properly

**Comment by Simplehorror** [comment]
if you think this is how it used to always work, you are a new player

**Comment by Cartlord** [comment]
Why was this closed?

**Comment by VaelophisNyx** [comment]
genuinely tho why was this closed

**Comment by Simplehorror** [comment]
i made it

**Pull request closed without merging**
