### PR TITLE
DAB FOR ME MORTALS!!!

### PR DESCRIPTION
**Pull request by CMOisLing**
im sorry

#### Changelog

:cl:  
rscadd: Voice of god can now make people dab
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Where's the strongly disagree button

**Comment by CMOisLing** [comment]
> Where's the strongly disagree button

It looks like this
image

**Comment by Hopekz** [comment]
> > Where's the strongly disagree button
> 
> It looks like this
> image

Someone press the green strong whatever button

**Comment by gilvian** [comment]
i pressed it and got a virus, why does pope Juan Pablo II started flying on me monitor mr.ling

**Comment by alexkar598** [comment]
Encourages LRP behaviour, dabbing is an expired meme and the ones that still use this meme are expired too. I think we should remove dabbing all together TBH

**Pull request closed without merging**
