### PR TITLE
Revamps the backup shuttle.

### PR DESCRIPTION
**Pull request by MrHorizons**
I've changed the backup shuttle to, well, resemble a shuttle.

**Old:**
image

**New:**
image

#### Changelog

:cl:  
rscadd: Adds a new version of the backup shuttle, so it is no longer a windowless box of chaos.
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
I'd rather not, the point of it is that its so simple nothing could go wrong when trying to load it in in the event of something going wrong

**Comment by Reed0506** [comment]
square is superior

**Comment by MrHorizons** [comment]
> I'd rather not, the point of it is that its so simple nothing could go wrong when trying to load it in in the event of something going wrong

... I guess that makes sense.

**Comment by Marmio64** [comment]
should add the new design in as a new shuttle and call it 'Refurbished Backup Shuttle', desc could be: "A refurbished model of the backup shuttle we have stored in centcom for your station in the event of a emergency. However, it could not pass the model specifications, so we'll pay you 500 credits to take it off our hands."

And yes, please make it give money, because it is so god damn tiny. Could also instead just make it a emag shuttle that traitors can get to make hijack easier for themselves.

**Comment by alao3alao3** [comment]
I just hope it fits in that same spot the old one fit.

**Pull request closed without merging**
