### PR TITLE
Removes holyparasite

### PR DESCRIPTION
**Pull request by ynot01**
[I'm sorry, little one.](https://youtu.be/qOYLNyQtKLA?t=200)

Holyparasite has proven too difficult to balance and at its core, a holoparasite for free/non-antags, has been a massive problem nonstop for many scenarios and gamemodes.

I have not tested these changes on a private server.

# Changelog

:cl:  
rscdel: Removed holyparasite
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
I can at least say that, the one time I was holypara, it was boring as hell - most of the round I was just idly standing by, waiting to be called.

**Comment by N3D6** [comment]
i rarely see this not used for valid hunting, good riddance

**Review by SomeguyManperson — APPROVED** [review]
code should work also maybe people will learn how to properly heal with the bible now

**Comment by maxion12345** [comment]
I don't think it'd be used to validhunt so often if it couldn't smash down literally anything

**Comment by Anvilman6** [comment]
A surprise change, but a welcome one

**Pull request merged**
