### PR TITLE
[IceMeta] Tweaks engine weight

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

Tweaks engine weight ratio, making it 45/30/25 SM, reactor, or TEG.

# Why is this good for the game?
SM is just objectively the best engine, it's a good mix of beginner friendly and gamer friendly being able to make custom setups or just the basic roundstart setup function, and it's also more common on box aswell
Reactor still has the edge over the TEG because the TEG just isn't a very beginner friendly engine at all (still has barely any guide :D)

# Testing

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: tweaks meta engine weights to 45/30/25 sm, reactor, teg
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
whats the problem with the teg guide?

**Comment by N3D6** [comment]
> whats the problem with the teg guide?

the guide is much better than it used to be but it'd be immensely better with labeled pictures, makes it way easier for new players to understand what they're doing and why

**Comment by wonderinghost** [comment]
Right that's what I forgot. Think you can @ mord once I get the pictures together?

**Comment by wonderinghost** [comment]
He has me blocked

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
