### PR TITLE
New sprites for CE tools

### PR DESCRIPTION
**Pull request by Partheo**
Changes the drill, jaws of life, and tricorder sprites. Thanks to Bimmer for giving me a base for the jaws of life sprite.

image

Old sprites:
image 

image

image

No offense to whoever made these but they were really terrible sprites.

#### Changelog

:cl: Partheo
imageadd: New sprites for the chief engineer's drill, jaws of life, and tricorder.
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
why the fuck is this so hard

**Comment by Readystorm546** [comment]
TURDIS MAN MAD

**Comment by Hopekz** [comment]
These are a clear improvement.
I really like the belt overlay icons as well and the animation for the tricoder.
I also really like how you made the cutters and prying heads have different belt overlays because before they were identical.

**Comment by Marmio64** [comment]
i really really really like the hand drill, it looks amazing. Neutral on tricorder, however its a clear improvement over the last one.

However, the jaws of life, I don't really like them to be honest, the spritework itself is great but looks really strange and has no resemblance to real life jaws of life, just looks like a RCD with wirecutters in it.

**Comment by Partheo** [comment]
> 
> 
> i really really really like the hand drill, it looks amazing. Neutral on tricorder, however its a clear improvement over the last one.
> 
> However, the jaws of life, I don't really like them to be honest, the spritework itself is great but looks really strange and has no resemblance to real life jaws of life, just looks like a RCD with wirecutters in it.

I'll admit the jaws aren't my best sprite. It was really hard to figure out a good way to do them. The biggest issue is that jaws of life IRL have a very unappealing silhouette; they only look okay because of the detail that they get by virtue of being a 3D object. Their actual design however doesn't translate well at all to a 2D sprite, especially this small, so it had to be completely redesigned. This was my best attempt; it's not great but I think it's decent enough.

There is, however, also this attempt by Azlan here:

image

Let me know if this jaws design is nicer- if people like it more, I'll take it and adapt it so it fits in with the rest of our tools here.

**Comment by LoliconSlayer** [comment]
I like the 2nd sprite for the Jaws better

**Review by alexkar598 — APPROVED** [review]
merge at your discretion

**Comment by JamieD1** [comment]
I agree with the second jaws sprite

**Comment by Partheo** [comment]
Will merge this for now, and replace the jaws sprite with Azlan's version when I port more of his tools at a later date.

**Pull request merged**
