### PR TITLE
Lavaland Corn Maze Ruin

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

image

Don't want to die to the chasms? Don't walk in.

# Wiki Documentation

New ruin:
Name: Lavaland Corn Maze
Rewards: necropolis chest

# Changelog

:cl:  
mapping: New ruin: Lavaland corn maze
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
where's the fucking corn

**Comment by RG4ORDR** [comment]
**Mandrill maze music**

**Comment by Moltijoe** [comment]
wanna put a fence around it like the minefield has?

also, not a single fuckin thing from a regular necropolis chest is gonna make me want to approach this unless i have flight

**Comment by patpol4** [comment]
What if someone walks into it by accident and dies

**Review by patpol4 — CHANGES_REQUESTED** [review]
Needs a change in /config/lavaruinblacklist.txt

**Comment by MajManatee** [comment]
Evil ohio be like...

**Comment by UltraBigRat** [comment]
needs a fence and more corn, otherwise looks fun.

**Review by MajManatee — APPROVED** [review]
me like corn

**Comment by JamieD1** [comment]
> Needs a change in /config/lavaruinblacklist.txt

Do it then. Config is synced to server.

**Review by patpol4 — APPROVED** [review]

**Comment by patpol4** [comment]
@JamieD1 
obraz
cant dismiss this

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
