### PR TITLE
Makes it more obvious to malf AIs that they can disable downloads

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

Big warning + it's in the malfunction tab now

# Wiki Documentation

# Changelog

:cl:   
tweak: Tweaked visibility of Toggle Download button for malf AIs
/:cl:

### CODE REVIEW

**Review by ToasterBiome — APPROVED** [review]
yes

**Comment by Simplehorror** [comment]
Unrelated question - will toggling download also disable uploads?

**Comment by Bibby0110** [comment]
> Unrelated question - will toggling download also disable uploads?

No

**Comment by Simplehorror** [comment]
> > Unrelated question - will toggling download also disable uploads?
> 
> No

Would it then not be simple to upload an AI and have it turn off the APCs, since you share the same cores?

**Pull request merged**
