### PR TITLE
Removes NTSL

### PR DESCRIPTION
**Pull request by ThatLing**
There is still no NTSL logging. Council wants this removed if no logging is added. PR obviously isn't complete, complain about nobody adding logging for months here.

:cl:  
rscdel: NTSL is gone
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
You monsters.

**Comment by monster860** [comment]
\> almost zero documentation

\> https://wiki.yogstation.net/wiki/NT_Script

**Comment by ThatLing** [comment]
@monster860 claim removed

**Comment by fluffe9911** [comment]
Logging now added nich just accidentally directly added it instead of making a pr for it so delete dis

**Pull request closed without merging**
