### PR TITLE
CMO, RD, and HoS glasses buff

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

CMO, RD, and HoS now get unique glasses

CMO and RD sunglasses can now scan reagents like chemists/sci goggles

HoS sunglasses can now see health HUD

Tested ingame

# Changelog

:cl:  
tweak: CMO & RD sunglasses can now scan reagents
tweak: HoS sunglasses now have a medical HUD
/:cl:

### CODE REVIEW

**Review by ReddicusDragon — APPROVED** [review]

**Comment by Maia-J** [comment]
Me when I craft them

**Comment by ynot01** [comment]
> Me when I craft them

CMO, RD, and HoS glasses only, as per the PR title and description

**Comment by TheRyeGuyWhoWillNowDie** [comment]
RD and CMO glasses sure, but medical work is not part of a HoS's job, and detecting implants in literally 1 click from them should not happen.

**Comment by ynot01** [comment]
> medical work is not part of a HoS's job, and detecting implants in literally 1 click from them should not happen.

Good for combat, Mqiib put it well: "Tells you when someone is in danger, when to press your advantage or back off"

implant detection and other medical examine details are exclusive to medhuds and thus HoS will not get them; even if he did it doesn't detect syndie implants but it doesn't so

**Comment by Hopekz** [comment]
> , but medical work is not part of a HoS's job, 

The PR author isn't pretending this isn't for combat use and you shouldn't either 

In combat having the health bar is pretty powerful. Even lets you know if you'll win a trade at a glance

**Comment by ChuChu42** [comment]
i agree with CMO and RD glasses but its a no from me to HoS sunglasses
this is a heavy buff for HoS and it is not required for them to have a medical HUD, if its nessecary they can implant themselves a medical hud.

**Comment by Burger1998** [comment]
Hos really doesnt need all too big a buff when he can pull a combat shotgun from the armory whenever he wants.

also rip CE forever forgotten. maybe give him diagnostic hud?

**Comment by MajManatee** [comment]
Just get a hud implant. this is unessicary

**Comment by ynot01** [comment]
> its a no from me to HoS sunglasses this is a heavy buff for HoS and it is not required for them to have a medical HUD, if its nessecary they can implant themselves a medical hud.

I see this is a rather inconsequential buff considering HoS is one of many in security, and should be a leg up from the others. The others will still want to seek implants for this, especially once they see the HoS make use of it. It will also serve well to coordinate his team in fights and make callouts.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> I see this is a rather inconsequential buff considering HoS is one of many in security, and should be a leg up from the others. The others will still want to seek implants for this, especially once they see the HoS make use of it. It will also serve well to coordinate his team in fights and make callouts.

the hos already has many many legs up on other members of security, including (but not limited to)
starting with 2 guns
diet AA
armor that covers all of their limbs
teleshield

so tl;dr i dont think they need even more of an advantage, just get an implant if you're desperate to be a gamer who can see health bars constantly

**Comment by RG4ORDR** [comment]
How about the HOS gets a direct security record access or detective scanner with his glasses - ya know two much more department appropriate devices.

**Comment by UltraBigRat** [comment]
Yeeah the rd and cmo glasses buffs are nice but as good  as health scanners are for combat it really isnt something hos needs

**Review by MajManatee — APPROVED** [review]
Frankly, im sure its fine

**Comment by ToasterBiome** [comment]
I dont like this

**Comment by ReddicusDragon** [comment]
> Yeeah the rd and cmo glasses buffs are nice but as good as health scanners are for combat it really isnt something hos needs

HoS should have a health scanner to see if prisoners are dying in their cells

**Comment by Simplehorror** [comment]
powercreep

**Pull request merged**
