### PR TITLE
Makes mining base work with Monstermos

### PR DESCRIPTION
**Pull request by Hopekz**
**Added Air vents so miners stop getting smacked around due to Monstermos.**

image

#### Changelog

:cl:  
bugfix: Made the Mining base work with Monstermos. Miners no longer get smacked around!
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
Just use tiny fan lol

**Comment by MegaEmpirical** [comment]
How does this help?

**Comment by Ktlwjec1** [comment]
Doesn't fix the issue. Will leave this open in case you want to tweak it.

**Comment by Hopekz** [comment]
The best way would be to make cycling airlocks or maybe even tiny fans.
Both solutions require completely different changes than the ones made in this PR so I'm closing this PR.

If I ever decide to pick it up again I'll probably create it under a new branch to start over.

**Pull request closed without merging**
