### PR TITLE
simplifies anti noblium crystal production

### PR DESCRIPTION
**Pull request by iloveloopers**
# Document the changes in your pull request

removes the 100 moles of zauker and nitrium required for the anti noblium crystal recipe in the crystallizer
this is way too damn time consuming and overcomplicated for no reason, like most crystallizer recipes

# Wiki Documentation

wiki doesn't have crystallizer recipes

# Changelog

:cl:  
tweak: anti noblium crystal recipe in the crystallizer now requires BZ and nitrogen instead of nitrium and zauker
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
@milk-is-cool man is jealous!!

**Comment by ShoziOffical** [comment]
the fact that antinob crystal doesnt have any use other than grind it is also fuckup too

**Comment by iamthesilly** [comment]
You could make it antinoblium + BZ + nitrogen

**Comment by iloveloopers** [comment]
Sure

**Review by Moltijoe — APPROVED** [review]

**Comment by iloveloopers** [comment]
Does this really need a review from Monster? Its a 1 line change

**Review by monster860 — APPROVED** [review]
code is fine. I'm not deciding whether this is good for balance though.

**Comment by iloveloopers** [comment]
how come certain PRs get merged 2 days after opening and others take more than a week

**Comment by ShoziOffical** [comment]
> how come certain PRs get merged 2 days after opening and others take more than a week

First time?

**Pull request merged**
