### PR TITLE
Adds beanbag chairs

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Adds craftable beanbag chairs that can be picked up and used as a weapon that does stamina damage for a pillow fight. Thanks to @UselessTheremin for the sprites and @Skrem7 for the description, i just did the code.

# Spriting
image

image

image

# Wiki Documentation
Add them to the cloth crafting recipe list. 

# Changelog

:cl:  UselessTheremin, Nmajask
rscadd: Added beanbag chairs  
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
no inhand sprites?

**Comment by nmajask** [comment]
> no inhand sprites?

Waiting on UselessTheremin to make them real quick

**Comment by LoliconSlayer** [comment]
You ever sit in a beanbag chair? Not a whole lot of room for a tail if you're properly sitting in one, not sure how it'd be notably popular among lizards

**Comment by Marmio64** [comment]
> You ever sit in a beanbag chair? Not a whole lot of room for a tail if you're properly sitting in one, not sure how it'd be notably popular among lizards

likely just a way to shoehorn in a lizard reference

**Comment by nmajask** [comment]
> > You ever sit in a beanbag chair? Not a whole lot of room for a tail if you're properly sitting in one, not sure how it'd be notably popular among lizards
> 
> likely just a way to shoehorn in a lizard reference

Blame skrem, i just pushed ctrl c ctrl v

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
If this can be picked up and used as a melee, it's gonna need in-hand mob sprites done and finished for it. other than that sprites look really nice so far.

**Review by KillerOrcaCora — APPROVED** [review]
Perfect, everything looks good sprite-wise.

**Pull request merged**
