### PR TITLE
Revert "Radio colour change"

### PR DESCRIPTION
**Pull request by ThatLing**
A lot of people seem to hate this. I'll merge this if it gets enough support.

### CODE REVIEW

**Comment by Ktlwjec** [comment]
I like the service color :frowning:

**Comment by thehighwayman** [comment]
easy come easy go. this one was controversial

**Comment by MegaEmpirical** [comment]
You monster, I hate the old colors more.

**Comment by Ratvar** [comment]
I am pro-new radio

**Comment by Logan-H** [comment]
I am cool with the service color, but I really think the command color needs to be changed to something that doesn't blend in with OOC so much.

**Pull request closed without merging**
