### PR TITLE
Adds Sap Blood as the inert mutation for Phytosians

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Same as the others, gives reasons for geneticists to want specific species

it slows bloodloss and slowly clots bleeding wounds

:cl:  
rscadd: Adds Sap Blood as the inert mutation for Phytosians
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
give them this roundstart... make phytos actually yknow a lil more different...

**Comment by Moltijoe** [comment]
> give them this roundstart... make phytos actually yknow a lil more different...

you're kidding, right? innate passive healing is already a lot

**Comment by azzzertyy** [comment]
> > give them this roundstart... make phytos actually yknow a lil more different...
> 
> you're kidding, right? innate passive healing is already a lot

yeah but its boring and lame

**Comment by Moltijoe** [comment]
> yeah but its boring and lame

the whole light vs dark management isn't
or the part where no plant based things will hurt you

**Comment by Marmio64** [comment]
> give them this roundstart... make phytos actually yknow a lil more different...

Only if phytosian players are willing to have a nerf to balance it

**Comment by azzzertyy** [comment]
> > give them this roundstart... make phytos actually yknow a lil more different...
> 
> Only if phytosian players are willing to have a nerf to balance it

Yes

**Review by ToasterBiome — APPROVED** [review]

**Comment by ToasterBiome** [comment]
Cornflakes

**Pull request merged**
