### PR TITLE
[Ezhan] swapped shooting range and brig phys room on YogsDelta

### PR DESCRIPTION
**Pull request by Hopekz**
What it does:
------
image

Reasoning from the author:
------
image

Why I'm PR'ing it:
-------
image
image

Map images
--------

Old:
-------
image

New:
--------
image

Difference:
----------
image

My personal feedback:
-------
Lmao @ how small the new shooting range is

:cl:  Ezhan, Hopek
tweak: swapped shooting range and brig phys room on YogsDelta
/:cl:

### CODE REVIEW

**Comment by Ethan4303** [comment]
My personal reply is that no one ever uses shooting range and brig phys was too far from where officers and prisoners are usually hurt and at so i swapped the rooms, bully me for it.

**Comment by Moggram** [comment]
untitled

Way want to fix this by putting a wall here. From what I know about mapping, this is looked down on.

**Comment by patpol4** [comment]
I like that the shooting range is now 2 meters long

**Comment by Hopekz** [comment]
> Way want to fix this by putting a wall here. From what I know about mapping, this is looked down on.

FYI, made this change

**Review by patpol4 — APPROVED** [review]
Fixed atmos pipes because they weren't connected, fixed whatever this madness is 
vivaldi_cOjwfcC9s3
and a nanomed in a wall.
vivaldi_xmvft4TAC2
straightened a stupid disposals pipe that was driving me nuts,
Added medical decals too

**Pull request merged**
