### PR TITLE
singularity shard

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

singularities, when destroyed, will now drop a singularity shard based on their highest ever achieved stage

higher stage = more cargo value

shards are indestructible and have no other use but are cool looking

tested on local, working

all shards are fully animated

### Why is this change good for the game?

make big singulo and then destroy it for big dosh
more depth to an engine with little depth

# Wiki Documentation

### If there are any numerical values involved in your PR that will be relevant to a player, please note them here. 

stage shard sells for
1 - 500 credits
2 - 3500 credits
3 - 8000 credits
4 - 20000 credits
5 - 40000 credits
6 - 80000 credits

# Changelog

:cl:  
rscadd: Added singularity shards that appear from collapsed singularities
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
make it a food item and instantly dust you if eaten you wont

**Comment by ynot01** [comment]
> make it a food item and instantly dust you if eaten you wont

you're right i wont

**Comment by Jarod1200** [comment]
do you need anything special to handle it or can you just pick it up with your bare hands

**Comment by ynot01** [comment]
> do you need anything special to handle it or can you just pick it up with your bare hands

bare hands

**Comment by ChesterTheCheesy** [comment]
There's potential in the shard

**Comment by alexkar598** [comment]
give it a cool suicide

**Comment by ynot01** [comment]
> give it a cool suicide

give me idea for cool suicide or you dont get a cool suicide

**Comment by Marmio64** [comment]
> > give it a cool suicide
> 
> give me idea for cool suicide or you dont get a cool suicide

have the suicide gib the person and spawn a singularity toy so it looks like a singularity just spawned on them.

Also maybe the shards should get a bit of damage, with more powerful ones dealing more damage, but nothing crazy, maybe 12 or so force for the most powerful one (stage 6)

**Comment by ChesterTheCheesy** [comment]
Btw won't this spawn after Ratvar and Nar'Sie fight?

**Comment by ynot01** [comment]
> Btw won't this spawn after Ratvar and Nar'Sie fight?

i dont know but now it definitely wont

**Review by nesisknesis — APPROVED** [review]

**Comment by JamieD1** [comment]
@ynot01 Fix conflict

**Review by JamieD1 — APPROVED** [review]

**Review by SomeguyManperson — APPROVED** [review]

**Pull request merged**
