### PR TITLE
Readds the Slime Mutation Toxin Recipies!

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑Fluffe9911 for porting Jujumatic for doing the work so I dont have to!
add: Slime Mutation Toxin Recipes have Returned!
/🆑

### CODE REVIEW

**Comment by ghost** [comment]
xenobiology doesn't need another buff

they already have all sorts of nonsense, giving them back the ability to turn into skeletons or runic golems on top of that is just overkill

**Comment by ShadowDeath6** [comment]
I would say to make skeleton mutation toxin sigificantly harder to make, milk is too easy to come by
Also the golem recipe is random so I feel like if they want to roll a bunch of times for a good one then it’s fine

**Comment by ghost** [comment]
@ShadowDeath6 0.01u golem pills are easy as fuck to mass produce

**Comment by ThatLing** [comment]
No thanks

**Comment by ShadowDeath6** [comment]
make the reactions require 5u to do anything then

**Pull request closed without merging**
