### PR TITLE
Gas Station Update

### PR DESCRIPTION
**Pull request by ReddicusDragon**
Old gas station wasn't very cash money for people teleporting in
#### Changelog

:cl:  
tweak: added air-filled area to gas station teleporter
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
could you post a picture of what it does either way i support this

**Comment by ReddicusDragon** [comment]
> could you post a picture of what it does either way i support this

Basically there's a teleporter at the gas station and if someone teleports there without internals they'll die. This pr fixes that.

**Comment by Ktlwjec1** [comment]
image

- Red - Should be /area/lavaland/surface
- Blue - Should be /area/ruin/powered/gasstation
- Purple - Remove the sand decals
- Green - Mystery wall
- Move everything down like the image on the right to prevent lava spawning just outside the airlock

**Comment by ReddicusDragon** [comment]
It is 0104 otherwise I’d do this now bear with me

**Comment by Ktlwjec1** [comment]
Yeah no rush, just do it when you can.

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
I'll just put this here so it's not forgotten, what my previous comment says.

**Comment by Ktlwjec1** [comment]
Going to close this due to no updates in 13 days - reopen it, ask me to reopen it, or remake it if you get time to do the changes.

**Comment by ReddicusDragon** [comment]
hold my beer

**Pull request closed without merging**
