### PR TITLE
Moves AI's data core display to AI upload in all maps except gax.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request

just makes sense innit

image
image
image

:cl:  
mapping: Moved ai core display to upload on all maps except gax
/:cl:

### CODE REVIEW

**Comment by Aquizit** [comment]
My one question is: why move it? Why not just add this one and keep the other one as well?

**Comment by KingSuperBOB** [comment]
Honestly thats a good question why move it instead of making more

**Comment by azzzertyy** [comment]
> My one question is: why move it? Why not just add this one and keep the other one as well?

maybe, ill consider

**Comment by Aquizit** [comment]
Need a commit either adding the Sat ones back or a comment you aren't going to otherwise I don't know when I should be reviewing this.

**Comment by MajManatee** [comment]
Id perfer to see one in both locations

**Review by Aquizit — APPROVED** [review]
Well it's fine. Someone else (I might later) can just add the second one in later.

**Pull request merged**
