### PR TITLE
Adds window shutters spawners

### PR DESCRIPTION
**Pull request by Ktlwjec**
So mappers (me) can see them.

A before and after:
unknown

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
Is there a way that we can get them placed above the grille? They seem difficult to reach as an AI since the grille sprite will cover them if the window is broke but not the grille.

**Comment by Ktlwjec** [comment]
They do appear above the grilles.
image

**Comment by MegaEmpirical** [comment]
That's good, thanks.

Though I believe the ones already live do not.

**Comment by Ktlwjec** [comment]
Ah I see what you mean, should be easy to fix that.

**Pull request merged**
