### PR TITLE
readds pacify to spellbook

### PR DESCRIPTION
**Pull request by tattax**
also improve some files in the yogstation fodler

# Testing
image

:cl:  
bugfix: readds pacify (spell) to the game
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
isn't this just reskinned death touch? can you revert from being a gondola?

**Comment by Moltijoe** [comment]
technically a bugfix, but the spell itself was a point of balance contension, so might as well balance review it

**Comment by RG4ORDR** [comment]
> isn't this just reskinned death touch? can you revert from being a gondola?

No - it's actually way worse because it turns the person into a simple mob if the transformation completes.

However:
Can be cured with pepper spray, frost oil, and getting into something that can do stasis - and getting the peppers is really easy.
At the max its cooldown is 20 seconds. For that it's all your spell points
Single target
Melee ranged


So unless you're REALLY lucky with a bus enabling admin you're left with spell that is really noobbait. Its balance is listed above in that you're waiting an extremely long time for a spell that only works in melee and unless you're specifically geared to do melee as well or lack mobility spells or spells that can save your neck, you're gonna be smeared on the ground.

**Comment by SomeguyManperson** [comment]
its strength is of course that if people don't know exactly what they need to do to cure it, they are on what can be a harsh time limit to find someone who does, then get access to the cure

**Comment by KingSuperBOB** [comment]
> its strength is of course that if people don't know exactly what they need to do to cure it, they are on what can be a harsh time limit to find someone who does, then get access to the cure

Its weakness of course is that its comically expensive to use and if you want to make a strat around it you have to invest everything in mobility and defense spells so you can survive when the spell goes off cooldown or more than 1 person approaches you

**Comment by KingSuperBOB** [comment]
and when a cure is made your magic loses most of its value due to vaccines so now its just a pax/mute toxin injector

**Comment by bawbbawbins** [comment]
> also improve some files in the yogstation fodler
> 
> # Testing
> image
> 
> 🆑 bugfix: readds pacify (spell) to the game /🆑

hi tttie :DDDDD

**Review by bawbbawbins — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
bawbbawbins has been banned for trolling and raiding

**Comment by bawbbawbins** [comment]
> bawbbawbins has been banned for trolling and raiding

slurp on my right nut extremely hard

**Comment by Moltijoe** [comment]
Balance Council:
>Less fun than disintegrate, effectively just used for round removal

**Comment by ToasterBiome** [comment]
Fixing where it was removed, make a revert PR

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
