### PR TITLE
Disposable RPED

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Disposable RPED. Costs 1000 metal. Self-destructs after use. Printable on all protolathes. I see a lot of people who use an RPED for one thing only, and I see a lot of departments who can't build new machines because engineering sucks. (they still don't get fancy stock parts)
# Spriting

# Wiki Documentation

Disposable RPED. Costs 1000 metal. Self-destructs after use. Printable on all protolathes.
# Changelog

:cl:  
rscadd: Disposable RPED. Printable on all protolathes, so you can upgrade machines for a low cost instead of burning a ton of metal to upgrade one machine.
/:cl:

## DONT CLOSE THIS THERE IS NO NEEDED PR IT IS QOL

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
removes any chance for departmental interaction

**Comment by Simplehorror** [comment]
> removes any chance for departmental interaction

removes any chance for departmental interaction by making it so scientists don't waste 10000000 metal just so they can upgrade their freezer?

**Comment by Simplehorror** [comment]
also this is why I only do balance PRs - because they don't get closed instantly because "not needed"

**Comment by ReddicusDragon** [comment]
> > removes any chance for departmental interaction
> 
> 
> 
> removes any chance for departmental interaction by making it so scientists don't waste 10000000 metal just so they can upgrade their freezer?

Science usually is good at upgrading the entire station. This is a bad idea.

**Pull request closed without merging**
