### PR TITLE
Seafood Update: Crab meat and Canned Food shenanigans

### PR DESCRIPTION
**Pull request by AlvCyktor**
# Document the changes in your pull request

Adds canned fish to cargo as well as crab meat

# Why is this good for the game?
Crabs can finally drop the meat they deserve, replacing their placeholder meat. Also allows for chef to have canned fish for greater usage of the seafood section

# Testing

WIP (will add video later)
# Spriting

image
GoldbrandGoldbrand_openedrawcrabRIORIO_openedSalmonSalmon_openedStarkistStarkist_openedcrab

# Wiki Documentation

Add crab meat to food wiki, canned fish to cargo wiki? 

# Changelog

- [x] Canned Fish
- [x] Crab Meat
- [x] Adding it to cargo
- [ ] Crab Recipes

:cl:  
rscadd: Crab meat 
rscadd: Canned Fish & Fish Crate
tweak: Crabs now drop crab meat instead of default meat 
imageadd: Crab and Canned Fish Sprites
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
can we get a can opener and you have to gruelingly open the can which takes like 1 minute straight

**Comment by AlvCyktor** [comment]
> can we get a can opener and you have to gruelingly open the can which takes like 1 minute straight

Pay me 5 robux

**Comment by azzzertyy** [comment]
> > can we get a can opener and you have to gruelingly open the can which takes like 1 minute straight
> 
> Pay me 5 robux

bet

**Comment by boodaliboo** [comment]
> # Document the changes in your pull request
> Adds canned fish to cargo as well as crab meat
> 
> # Why is this good for the game?
> Crabs can finally drop the meat they deserve, replacing their placeholder meat. Also allows for chef to have canned fish for greater usage of the seafood section
> 
> # Testing
> WIP (will add video later)
> 
> # Spriting
> image GoldbrandGoldbrand_openedrawcrabRIORIO_openedSalmonSalmon_openedStarkistStarkist_openedcrab
> 
> # Wiki Documentation
> Add crab meat to food wiki, canned fish to cargo wiki?
> 
> # Changelog
> * [x]  Canned Fish
> * [x]  Crab Meat
> * [x]  Adding it to cargo
> * [ ]  Crab Recipes
> 
> 🆑 rscadd: Crab meat rscadd: Canned Fish & Fish Crate tweak: Crabs now drop crab meat instead of default meat imageadd: Crab and Canned Fish Sprites /:cl:

dude pm me i got so much see sprites

**Comment by ToasterBiome** [comment]
reopen when work commences

**Pull request closed without merging**
