### PR TITLE
Cryoxadone now knocks you over and makes you drops things sometimes while healing

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

No more spacewalk chem you need to put in a little more effort

Also ling buff ig

#

# Changelog

:cl:  
tweak: Cryoxadone now makes you drop items and fall over when healing
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Cryoxadone is now an offensive chemical

**Comment by Burger1998** [comment]
HOLY SHIT NEW COMBAT CHEM DROPPED

**Comment by Burger1998** [comment]
GOD I CAN ABUSE THIS SO MUCH AS A LING

**Comment by Notamaniac** [comment]
Keep in mind it only takes effect when your body temp is below 273K. I mean I guess cryosting followed up by a cryoxadone shot is something you can do, or mixing frost oil with cryoxadone, but I don't know how effective that is over just using cyanide or lexorin instead. Since it's not a paralyse and only a 10% probability per tick, it still lets people be feasibly actionable/scream for help. Hell you might get a more deblitating effect by using a bath salts OD.

**Comment by Firewolf34** [comment]
antag Drake in shambles

**Comment by Burger1998** [comment]
update the changelog

> Keep in mind it only takes effect when your body temp is below 273K. I mean I guess cryosting followed up by a cryoxadone shot is something you can do, or mixing frost oil with cryoxadone, but I don't know how effective that is over just using cyanide or lexorin instead. Since it's not a paralyse and only a 10% probability per tick, it still lets people be feasibly actionable/scream for help. Hell you might get a more deblitating effect by using a bath salts OD.

bath salts is astronomically harder to make and cyanide and lexorin wont make a plucky sec officer from screaming for help and calling out on the other hand a twelve or so second hardstun and blind(sleep) will absolutely make it a free kill.

not all too relevant anymore as ynot changed it but oh well knockdown makes combat easy too so you can armblade him to death and if he pulls a baton or disabler he drops it on the ground as free loot for you.

**Comment by Burger1998** [comment]
> update the changelog
> 
> > Keep in mind it only takes effect when your body temp is below 273K. I mean I guess cryosting followed up by a cryoxadone shot is something you can do, or mixing frost oil with cryoxadone, but I don't know how effective that is over just using cyanide or lexorin instead. Since it's not a paralyse and only a 10% probability per tick, it still lets people be feasibly actionable/scream for help. Hell you might get a more deblitating effect by using a bath salts OD.
> 
> bath salts is astronomically harder to make and cyanide and lexorin wont make a plucky sec officer from screaming for help calling you out on the other hand a twelve or so second hardstun and blind(sleep) will absolutely make it a free kill.
> 
> not all too relevant anymore as ynot changed it but oh well knockdown is the first step to winning combat easy so you can armblade him to death and if he pulls a baton or disabler he drops it on the ground as free loot for you.

**Comment by Burger1998** [comment]
> Keep in mind it only takes effect when your body temp is below 273K. I mean I guess cryosting followed up by a cryoxadone shot is something you can do, or mixing frost oil with cryoxadone, but I don't know how effective that is over just using cyanide or lexorin instead. Since it's not a paralyse and only a 10% probability per tick, it still lets people be feasibly actionable/scream for help. Hell you might get a more deblitating effect by using a bath salts OD.
> 
bath salts is astronomically harder to make and cyanide and lexorin wont make a plucky sec officer from screaming for help and calling out on the other hand a twelve or so second hardstun and blind(sleep) will absolutely make it a free kill.

 not all too relevant anymore as ynot changed it but oh well knockdown makes combat easy too so you can armblade him to death and if he pulls a baton or disabler he drops it on the ground as free loot for you.

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
