### PR TITLE
its over anakin

### PR DESCRIPTION
**Pull request by GuppyLaxx**
i have the highground

:cl: GuppyLaxx
add: Adds the use of high ground
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
10/10  speedmerge right fucking now

**Comment by MacHac** [comment]
Did you ever hear the story of Darth Speedmerge the Wise?  It's not a story the head coders would tell you.

**Comment by Kmc2000** [comment]
Stand on table once
Get friend to hit you

Permanent 99% blockchance

Nice

**Comment by Kmc2000** [comment]
disregard i are have stupid

**Comment by GuppyLaxx** [comment]
you coded star trek 13, of course you are. dummy

**Comment by Kmc2000** [comment]
go back to hippie station

**Pull request merged**
