### PR TITLE
gives pirates a parrot named cracker

### PR DESCRIPTION
**Pull request by boodaliboo**
they had no parrot
:cl:  
rscadd: gives pirates a parrot named cracker

/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
Polly x Cracker?

**Review by swissloaf — CHANGES_REQUESTED** [review]
Can you make it a bone parrot possibly instead

**Comment by patpol4** [comment]
Do we even have bone parrots

**Review by patpol4 — APPROVED** [review]
Meat parrot will have to do

**Pull request merged**
