### PR TITLE
You can no longer play as the enclave.

### PR DESCRIPTION
**Pull request by nesisknesis**
# Github documenting your Pull Request

Deletes the enclave suit from the game.

This game is full of references but at points it gets really dumb. Nice and plainly its named "enclave suit" and available in the autodrobe. There are two problems I can identify; it's too overt, it's quite literally taken from Fallout 3 and stuck into our universe without any adaptation; I could even argue it breaks the OOC rule. And, it is without context or purpose. It's not in some clever location that'd make sense, it's in the autodrobe so you can cosplay as an enclave member.

Also, why would you want to wear the uniform of a racist, fascist paramilitary organization that is objectively evil?

# Wiki Documentation

no

# Changelog

:cl:  Identification
imagedel: The enclave suit is no longer in the game for thematic reasons. 
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
i disagree with the OOC bit but otherwise yea it doesn't belong

**Comment by Marmio64** [comment]
i feel like the suit's sprite might be able to be used for something else in the future, so i always think its nice to leave decent enough sprites in the code even if its slightly more stuff thats unused, but whatever.

**Review by adamsong — APPROVED** [review]
Code changes look functional, but 'because OOC' isn't really a good reason to remove when we have things like ingame antag tokens

**Comment by boodaliboo** [comment]
the reasoning is stupid we have tons of stupid references that are ooc like oranges in maint and shit

**Comment by nesisknesis** [comment]
> 
> 
> the reasoning is stupid we have tons of stupid references that are ooc like oranges in maint and shit

There are references better than others. the orange in a locker next to a cloner is funny because of it's context, it doesn't have to explain that it's Oranges, the headcoder of /tg/ who removed cloning, and if you don't get it, you don't get it. When a reference has to explain itself like "Enclave suit that is from Fallout 3" or "Stormtrooper armour from Star Wars", it isnt a good reference at all and we can do without it.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
