### PR TITLE
Healium tweaks, p2

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Healium now heal organic organs
Cryo tube can now inject healium into dead body
Healium when applied to dead body now heals organic organs (can fix the failure organs aswell), brutes and burns, to a safe level for defibbing.
Healium grenade now injects healium into nearby mobs if they their overall health is below or equal to 20, softcrit, dead, or unconscious

# Why is this good for the game?
Makes sense for healium, it can already interact with organic body to replicate and repair the body, so it should be able to heal the overall of the organic body. Gives atmos tech more interactions with medical to help them during blood hours (medbay is understaffed and filled with dead bodies).

# Testing

https://github.com/yogstation13/Yogstation/assets/89688125/1611b6f0-591d-4632-89a4-34a74416a7a2

# Wiki Documentation
in doc of change

# Changelog

:cl:  

tweak: Healium now heal organic organs
tweak: Cryo tube can now inject healium into dead body
tweak: Healium when applied to dead body now heals organic organs (can fix the failure organs aswell), brutes and burns, to a safe level for defibbing.
tweak: Healium grenade now injects healium into nearby mobs if they their overall health is below or equal to 20, softcrit, dead, or unconscious
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
This is just organ healing with extra steps

**Comment by ShoziOffical** [comment]
> This is just organ healing with extra steps

yes but standard organ healing is slow

**Comment by Moltijoe** [comment]
> yes but standard organ healing is slow

no i mean, why not just make healium directly heal the organs?
as it currently is, this is just a permanent buff to organ passive healing if someone breathes even a bit of healium

**Comment by ShoziOffical** [comment]
> > yes but standard organ healing is slow
> 
> no i mean, why not just make healium directly heal the organs? as it currently is, this is just a permanent buff to organ passive healing if someone breathes even a bit of healium

idk this is a way...

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
