### PR TITLE
You can now emag sec record console to unlock it but be aware it will alert sec

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request

You can now emag sec record console to unlock it but be aware it will alert sec and active silicons

# Wiki Documentation

You can now emag sec record console to unlock it but be aware it will alert sec and active silicons

# Changelog

:cl:  
rscadd: You can now emag sec record console to unlock it but be aware it will alert sec and active silicons
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
why does it need to alert? seems hugbox

**Comment by ShoziOffical** [comment]
> why does it need to alert? seems hugbox

No, sec record is a secured database and shouldnt be emagged so easily

**Comment by ShoziOffical** [comment]
Either that or just smash in spare cabinet and get alerted too

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
shouldn't alert, nothing else does. (other than stuff that is actually important) wait for jamie for final decision

**Comment by 00ze-cyclone** [comment]
I prefer it blaring an alarm instead of being straight up unemaggable like it currently is.

**Comment by ShoziOffical** [comment]
> I prefer it blaring an alarm to it being straight up unemaggable like it currently is.

whats the point of that

**Comment by Sniblet** [comment]
> shouldn't alert, nothing else does. (other than stuff that is actually important)

The entire sec record and crew manifest of the station is pretty important, especially if the AI laws use the term "crew" anywhere

**Comment by Moggram** [comment]
> > shouldn't alert, nothing else does. (other than stuff that is actually important)
> 
> The entire sec record and crew manifest of the station is pretty important, especially if the AI laws use the term "crew" anywhere

What this? Mr. Traitor you seem to be the only crew member. How may I help you today?

**Comment by TheRyeGuyWhoWillNowDie** [comment]
doesnt this let you cheese the objective to erase yourself from the security console pretty effortlessly

**Comment by ShoziOffical** [comment]
> doesnt this let you cheese the objective to erase yourself from the security console pretty effortlessly

No, sec will be on your ass

**Comment by JamieD1** [comment]
The issue comes with people being able to delete all security records, if there was a way for hos to restore round start records I would be more lenient.

**Comment by ShoziOffical** [comment]
> The issue comes with people being able to delete all security records, if there was a way for hos to restore round start records I would be more lenient.

@JamieD1 well i don't think you can restore delete stuffs like on your PC, also tator still can just get AA for this

**Comment by JamieD1** [comment]
> > The issue comes with people being able to delete all security records, if there was a way for hos to restore round start records I would be more lenient.
> 
> @JamieD1 well i don't think you can restore delete stuffs like on your PC, also tator still can just get AA for this

Would be nice if roundstart were stored to blackbox and then HoS can copy from Blackbox with a disk. Hopefully bibby can get to this, or if you can get someone else to do it.

**Comment by ShoziOffical** [comment]
> > > The issue comes with people being able to delete all security records, if there was a way for hos to restore round start records I would be more lenient.
> > 
> > 
> > @JamieD1 well i don't think you can restore delete stuffs like on your PC, also tator still can just get AA for this
> 
> Would be nice if roundstart were stored to blackbox and then HoS can copy from Blackbox with a disk. Hopefully bibby can get to this, or if you can get someone else to do it.

so this is now a different pr???????

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
