### PR TITLE
[REVIVE #15334] Attack anim electric boogalo 2

### PR DESCRIPTION
**Pull request by warface1234455**
Revives #15334 but tweaked a bit

# Document the changes in your pull request
Replaces the old attack anim with a new one, current one is goofy
Old:

https://user-images.githubusercontent.com/89688125/197520243-0dcb886b-574c-4d5a-88e4-99edbd6b0a23.mp4

New:

https://user-images.githubusercontent.com/89688125/197520265-23a9da08-e82c-406e-a459-2e7ac490f48f.mp4

# Wiki Documentation

Replaces attack anim

# Changelog

:cl:  

tweak: Replaces attack anim
/🆑

### CODE REVIEW

**Comment by Mqiib** [comment]
I think the weird tilting makes it look goofier, but maybe that's just me.

**Comment by ShoziOffical** [comment]
> I think the weird tilting makes it look goofier, but maybe that's just me.

on the right side or left side

**Comment by JamieD1** [comment]
Eh, looks weird to lean in to attack like that. Sorry.

**Comment by ShoziOffical** [comment]
well 

> Eh, looks weird to lean in to attack like that. Sorry.

dont you do that irl still @JamieD1

**Pull request closed without merging**
