### PR TITLE
More updates for yogbox

### PR DESCRIPTION
**Pull request by Ktlwjec**
https://github.com/yogstation13/Yogstation-TG/pull/1375
https://github.com/yogstation13/Yogstation-TG/pull/1676
https://github.com/yogstation13/Yogstation-TG/pull/1815
https://github.com/yogstation13/Yogstation-TG/pull/1841

### CODE REVIEW

**Comment by thehighwayman** [comment]
were these really necessary?

**Comment by Ktlwjec** [comment]
i need to prove my updating maps dedication so i can get ling to allow yogsdelta

**Comment by Ktlwjec** [comment]
i broke it then i fixed it i thonk

**Comment by thehighwayman** [comment]
gitub broke it don't blame yourself

**Pull request merged**
