### PR TITLE
Increases xeno event chance

### PR DESCRIPTION
**Pull request by ThatLing**
So we can play this more ((until its getting removed by goof))

### CODE REVIEW

**Comment by Ratvar** [comment]
"can we rise bomb cap before we remove bombs plz it will be fun engaging", I can't understand this PR

**Comment by ThatLing** [comment]
but bombs aren't getting removed?

**Comment by Ratvar** [comment]
So are xenos, thanks Xantam

**Comment by ThatLing** [comment]
but goof said they were

**Comment by Bawhoppen** [comment]
Goof is not in charge

**Comment by ThatLing** [comment]
disney is gonna sue us

**Comment by CMOisLing** [comment]
Disney can just make a PR to remove them

**Pull request closed without merging**
