### PR TITLE
Lizards can hiss at people

### PR DESCRIPTION
**Pull request by yacabo**
image

Here's what it sounds like:
https://cdn.discordapp.com/attachments/205784753352343552/700813621923414046/hiss.mp3

:cl:  
rscadd: Lizards can now hiss
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
that hiss is incredibly aggressive and alien and it cuts off and bad try this
https://cdn.discordapp.com/attachments/205784753352343552/700813424275488878/hiss.mp3

**Comment by overlord12345** [comment]
sounds a bit too deep

**Comment by Featherfield** [comment]
I didnt know scalies were fucking dinosaurs

**Comment by Hopekz** [comment]
I like the idea of you adding a hiss but this one is kind of really "monstrous" if that makes sense.
This really sounds like a Xeno from Aliens type hiss.
It would almost be immersion breaking to have humanoid lizards hiss like an Alien hunter

**Comment by yacabo** [comment]
Anyone have a better hissing sound by chance? Or am I going to need to get my own?

**Comment by overlord12345** [comment]
> Anyone have a better hissing sound by chance? Or am I going to need to get my own?

just find a snake hiss somewhere

**Comment by yacabo** [comment]
Going with ynot's hiss instead, feel free to complain if you don't like that one as well

**Comment by PettyOfficer** [comment]
Haha, lizard go hiss

**Review by Hopekz — APPROVED** [review]
Yeah I like this new sound looks good here

**Comment by Marmio64** [comment]
now it just sounds like a rattlesnake

**Pull request merged**
