### PR TITLE
Syndicate-Nanotrasen hotline

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

cool rp item
can be ignored/deleted by admins if they get annoyed by it

someone that knows how to map can put this where they think is appropriate

#### Changelog

:cl:  
rscadd: Added a hotline to the Syndicate
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
I thought the syndicate was a syndicate and there is no one person or group who represents them all...but traitors can already send messages to ""the syndicate"" via emag so whatever +1 good item

**Comment by ynot01** [comment]
`code/game/objects/items/weaponry.dm:363:error: unexpected character (ascii 194)
code/game/objects/items/weaponry.dm:363:error: unexpected character (ascii 160)`
`code/game/objects/items/weaponry.dm, line 363, column 6:
error: illegal byte 0xc2`

line 363
`	desc = "A bluespace last resort negotiation tool connected directly to the enemy should anything ever go wrong. Misuse will likely lead to the line being cut or anything else they're capable of. All communication monitored by Nanotrasen Officials."`

travis what the FUCK

**Comment by oklews** [comment]
Amazing idea, much love. I feel it should be placed in either that captain’s office or the head of security’s office just as a default thing though

**Comment by Mr-Space** [comment]
inb4 captain booty calls syndicate

**Comment by alexkar598** [comment]
Mind explaining the point of an unobtainable item?

**Comment by ynot01** [comment]
> Mind explaining the point of an unobtainable item?

i dont know how to map and mayhem said he'd map it after it gets merged

**Comment by oklews** [comment]
Would be an interesting idea to let admemes respond to it with a strike team, like how you can smite someone for saying something stupid via CC communication

**Pull request merged**
