### PR TITLE
[SPEEDMERGE] ports Resprites the kitchen knife! 😂😂😂

### PR DESCRIPTION
**Pull request by ktlwjec0**
https://github.com/tgstation/tgstation/pull/57488
changes the kitchen knife sprite

# Why is this good for the game?
it looks cooler

# Testing
no

# Spriting
knifew

:cl:  Krysonism
imageadd: The kitchen knife has a new sprite.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
can't do this due to licensing issues

**Review by MajManatee — APPROVED** [review]
Hey, I have that knife

**Comment by MajManatee** [comment]
Wait ports from where?

**Review by cuackles — APPROVED** [review]
Real knife real knife real knife

**Comment by ktlwjec0** [comment]
> Wait ports from where?

i added it to the pr text sorry

**Comment by MajManatee** [comment]
Looks great

**Pull request merged**
