### PR TITLE
Hulk can no longer be obtained through genetics fuckery (rad stor/wizard only)

### PR DESCRIPTION
**Pull request by Szyszkrzyneczka**
i may make the hulk mut harder
Also hulk makes you bigger :)
#### Changelog

:cl:  
tweak: Cripples powergamers by removing Hulk from recipes and makes hulks bigger
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
This PR needs to be atomized.
Imagine just tagging along "oh by the way Also Telekinesis now requires you to mix two mutations, Mindread and Void mutation"

Shit PR

**Comment by overlord12345** [comment]
Im ok with hulk being removed from genetics but telekinesis should stay

**Comment by Readystorm546** [comment]
Im also okay with hulk going away from gene bois. However keep TK the way it is.

**Comment by yacabo** [comment]
>This PR needs to be atomized.

>Im ok with hulk being removed from genetics but telekinesis should stay

>Im also okay with hulk going away from gene bois. However keep TK the way it is.

**Comment by LoliconSlayer** [comment]
Imagine adding the good first PR label to someone's 10th PR. 

Couldn't care about TK either way, Hulks bad

**Comment by Hopekz** [comment]
> Imagine adding the good first PR label to someone's 10th PR.

Whoops. I guess not being able to properly atomize PR's threw me off
It still looks like a first PR to me.

**Comment by ghost** [comment]
it's not like hulk is anything but a downside given you can't fire guns if you have it. the only real use it has is rushing people because you can't be stunned, but stamina damage is a thing, so it's not like it really matters.

**Comment by LoliconSlayer** [comment]
Last I checked Adam, Hulks don't take stam damage

**Comment by Mr-Space** [comment]
smells like i ded here

**Comment by boodaliboo** [comment]
neutral on this because im agree

**Comment by oklews** [comment]
Hulk bad TK good

**Comment by MegaEmpirical** [comment]
You could also merge our old hulk changes like I suggested. Instead of this.

**Comment by MegaEmpirical** [comment]
Damn you Id

**Pull request closed without merging**
