### PR TITLE
Adds the yarn.lock file to gitignore

### PR DESCRIPTION
**Pull request by Hopekz**
:cl:  Hopek
bugfix: For coders, the yarn.lock file is now being ignored by git since it changes every time you compile.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Someone just needs to update it, nbdl.
No need to git ignore it

**Comment by Hopekz** [comment]
> Someone just needs to update it, nbdl. No need to git ignore it

Whoever updates it can unignore it

**Comment by alexkar598** [comment]
lock files are meant to be committed for reproducible builds. Bad PR

**Comment by alexkar598** [comment]
\+ this impacts security

**Comment by Hopekz** [comment]
I Incorporated both your suggestions in #13619

**Pull request closed without merging**
