### PR TITLE
Adds Reactive Stealth Armor Cooldown

### PR DESCRIPTION
**Pull request by Mqiib**
# Document the changes in your pull request

Gives the reactive stealth armor a cooldown of 8 seconds because apparently it didn't have a cooldown at all and is an exceptionally powerful reactive armor type since it makes you INVISIBLE. This means it has a 50% uptime on the invisibility maximum, which is plenty of invisibility.

# Wiki Documentation

Has 8 second cooldown now.

# Changelog

:cl:  

tweak: Reactive stealth armor no longer has an 8 second cooldown (from 0).

/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
i ded

**Comment by Mqiib** [comment]
> i ded

Wasn't me that died, legally not an ided

**Comment by LoliconSlayer** [comment]
> > i ded
> 
> Wasn't me that died, legally not an ided

I have not played in like  years and I still got an i ded on #13139

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Logical

**Pull request merged**
