### PR TITLE
Save lowpop from appendicitis

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Increase min players for appendicitis event from 5 to 20

# Why is this good for the game?
Appendicitis on lowpop is bad

# Testing
unrequired

# Wiki Documentation
event document change

# Changelog

:cl:  
  
tweak: Save lowpop from appendicitis
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
We should delete antags from the game, I was inconvenienced because of it once

**Comment by ShoziOffical** [comment]
> We should delete antags from the game, I was inconvenienced because of it once

maybe remove assassinate objectives on lowpop

**Comment by solwashere** [comment]
> > We should delete antags from the game, I was inconvenienced because of it once
> 
> maybe remove assassinate objectives on lowpop

Go outside when you die

**Comment by Moltijoe** [comment]
Balance council:
>Just ask one of the 4 people to help you

**Comment by ShoziOffical** [comment]
> Balance council:
> 
> > Just ask one of the 4 people to help you

what the fuck, what if everyone do not know medical and what if they arent there for you to get help

**Comment by KingSuperBOB** [comment]
> > Balance council:
> > > Just ask one of the 4 people to help you
> 
> what the fuck, what if everyone do not know medical and what if they arent there for you to get help

Break the windows into medbay, pick up surgery bag, place on surgery table, follow steps on surgery console

**Pull request closed without merging**
