### PR TITLE
adds a /hat because missa forgot to add it so the helmets till now were identical to to the armor

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request

Explain what the purpose of your PR is.
Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool.

Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged. This is much easier for everyone.

Edit the changelog at the bottom for changes that are noticeable by the players. Remove it if this isn't the case.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.
Include [admin] in the title if it's something admin related.
Include [s] in the title if you don't want it to be announced on discord and the server.

#### Changelog

:cl:  
bugfix: fixed a missing /hat 
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
what does this revert

**Comment by SomeguyManperson** [comment]
Bot works off the changelpg which you should also actually make

**Comment by boodaliboo** [comment]
> Bot works off the changelpg which you should also actually make

fine

**Comment by missatessatessy** [comment]
After looking at this properly (I'm out of commission during weekends) the file is /obj/item/clothing/head/helmet so it doesnt need /hat (like all the other hardsuits in the same file). If there is an issue with the helmets that's something else to look into and this PR probably won't fix anything?

**Comment by missatessatessy** [comment]
I already know what mistake I made, like the big dumb dumb I am

**Pull request closed without merging**
