### PR TITLE
Should remove the intern announcer

### PR DESCRIPTION
**Pull request by Cartlord**
# Document the changes in your pull request

The intern announcer is finally gone.

# Wiki Documentation

I don't think station traits are on the wiki.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:    
rscdel: Removed the CentComm intern announcer
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Me when I see the slightest bit of fun in the games code

**Comment by Spacemanspark** [comment]
Why? This announcer is hilarious.

**Comment by Cartlord** [comment]
I find him very annoying, especially when I hear the line about burgers - or, really, any other line - more than twice in a row, or when the admins decide to spam events in quick succession (which at least one seems to think is the best form of bus, given the frequency with which I see it) and make his lines come out so fast that one starts playing before either of the last two have stopped.

**Comment by Takahiru** [comment]
This announcer makes me think admins are just adminbussing and being annoying, when it is literally just a part of the game. its kinda ass tbh

**Pull request closed without merging**
