### PR TITLE
[admin] Adds in-game python scripting

### PR DESCRIPTION
**Pull request by 1fbff5f83b23d39d38b1dfcb4cac8d9b**
Some potato on goon made a way to script in ss13 with lua:
image
I'm very interested in creating complicated things of questionable usefulness and the guy's project didn't seem to go anywhere, so I recreated it with python.
Admins can use it in cases where SDQL and varedit don't quite cut it, such as putting a gun named "Freedom Station Instrument" in everyone's hand:
image
or making a guy flash colors 10 times quicker than colorful reagent ever could:
image
The possibilities are endless.

There's a couple caveats though: ~~Number A, it's slow as hell. While taking up almost zero CPU usage even when active, it can only execute roughly 20 instructions per second, which in the freedom example translates to equipping about 3 people per second. I'm working on making it faster though.~~ It's lightning fast!
~~The second problem is that it crashes sometimes for no particular reason but I think I removed the most problematic parts. I might need to rewrite the DLL in Rust or some other fearless language.~~ Crashes are gone and it's in Rust now!
The interface is also kinda crappy and it's not very clear whether it's running or if the script server died, but these considerations are secondary.

Hopefully python's syntax is easy enough to pick up quickly and we can get some cool events running with this.

:cl:  McDonald072
rscadd: Added python scripting for admins to create cool effects with.
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Amazing shit!

**Comment by ghost** [comment]
Jesus christ that's fucking awesome

**Comment by simonset55** [comment]
If only a smoothbrain such as I knew anything about thems languages

**Comment by Nirnael** [comment]
Should probably have a specific access level to whitelist just for this. Can't have idiots using it.

**Comment by Amelia0010** [comment]
>Should probably have a specific access level to whitelist just for this. Can't have idiots using it.

[You mean sorta like the +DEBUG flag?](https://github.com/yogstation13/Yogstation-TG/pull/2420/files#diff-1d73825f51b1854a5cc395b7b7c09b1eR4)

**Comment by Nirnael** [comment]
Is it enough? If it is then good.

**Comment by CMOisLing** [comment]
“No one man should have all that power” - Bill Clinton

**Comment by AshCorr** [comment]
I dont care if this is just for admins. I cant begin to tell you how dangerous this is.

You're running totally untrusted Python code on a machine that holds a lot of valuable data.

EDIT: Removed article, not really that good.

**Comment by Kmc2000** [comment]
why is this on yog and not tg.

time to write me a RAT downloading python script for that sweet host access


or maybe a forkbomb, that could be fun
or a dos script i guess? to implicate the host in a DDOS attack?

**Comment by ThatLing** [comment]
@Kmc2000 
Panic remove SDQL access from retmins

**Comment by Ratvar** [comment]
yee

**Comment by ghost** [comment]
Why python over lua? Lua's better

**Comment by ThatLing** [comment]
Closing this because it is stale, feel free to re-open or make a new PR if you are working on this again.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
It's ready

**Pull request closed without merging**
