### PR TITLE
Adds new stealthy traitor item (spy bug)

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Adds the spy bug. The spy bug is an item that latches onto an object and transmits everything it hears to the syndicate channel.
# Spriting

image

# Wiki Documentation

The traitor uplink now contains a box of bugs for 1 TC. Take the description.
# Changelog

:cl:  
rscadd: Adds spy bugs to traitor uplink
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
now this is a pr

**Comment by ShoziOffical** [comment]
so you just stick it to an item, then give that item to another person, it will record every transmits to that person?

**Comment by ShoziOffical** [comment]
Can you throw it onto mob tho, that would be cool

**Comment by Simplehorror** [comment]
> Can you throw it onto mob tho, that would be cool

yea

**Comment by Simplehorror** [comment]
> so you just stick it to an item, then give that item to another person, it will record every transmits to that person?

you could just place it on them but yes

**Comment by Sniblet** [comment]
This dot is small and it is also little
It is a small little dot

**Comment by Simplehorror** [comment]
yep

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
