### PR TITLE
HoP doesn't get a proper gun :/

### PR DESCRIPTION
**Pull request by Amelia0010**
see: https://github.com/yogstation13/yogstation/pull/3048

HoPcurity is bad, for self-defense you don't really need a proper e-gun over this

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
minus one egun from the armory

**Comment by GrayRachnid** [comment]
Is this the miniature pistol?

**Comment by Bawhoppen** [comment]
Yes, it's a mini-egun, rather than a normal egun. Though, do make sure this isn't the version that has a tase functionality.

**Comment by GrayRachnid** [comment]
nice stealth buff

these mini guns get 2 more shots than a normal one, can fit in a pocket, and have a built in flashlight.

**Comment by Amelia0010** [comment]
>these mini guns get 2 more shots than a normal one

w a t

**Comment by Amelia0010** [comment]
https://github.com/yogstation13/tg-rebase/blob/8bfe0df2ddd398ca9a98142c0c30b5aec0ddd50a/code/modules/projectiles/guns/energy/energy_gun.dm#L19

So mini-gun has a maxcharge of 600.

https://github.com/yogstation13/tg-rebase/blob/8bfe0df2ddd398ca9a98142c0c30b5aec0ddd50a/code/modules/projectiles/guns/energy.dm#L8

Proper gun uses these cells, which have a maxcharge of 1000:

https://github.com/yogstation13/tg-rebase/blob/a2669e0b7b582b6838a05072a8b0a1cf01e831ff/code/modules/power/cell.dm#L15

**Comment by Amelia0010** [comment]
>minus one egun from the armory

Good thing the HoP doesn't have armoury access, and just about any warden/HoS will brig them if they start knicking stuff from the armoury. Could also fall under powergaming 😄

**Comment by ShadowDeath6** [comment]
I can guarantee a warden isn't going to complain if the HoP takes an egun from the armory

**Pull request merged**
