### PR TITLE
Experimental: Racial modifier adjustments

### PR DESCRIPTION
**Pull request by Anvilman6**
Changes most all racial damage and environmental modifiers to create more unique experiences for playing each (see PR body for numbers).

# Github documenting your Pull Request

Gives all non-Human races (excepting Polys as they're still quite fresh and don't need an overhaul) a redesigning pass for various species.dm modifiers. I'm also looking at _adding_ some other modifiers, but that will be a separate PR should it happen.

This PR is experimental and open to feedback (I'm requesting feedback from people more knowledgeable than I) as game balance is not something I'm too well versed on. I do understand that some of these changes may end up being too crippling, as nerfs are what I am predisposed to. If anyone has thoughts on how these numbers can be tweaked or adjusted, please let me know here or on the Yog Discord and we can discuss it.

See the next header for documentation of all numerical changes.

TO DO:
- [x] Priority: **Re-evaluate Preternis stats per Moggram and Alexkar input**
- [x] Correct backwards Ethereal modifier
- Adjust Lizard-Fu modifiers to counteract Lizard nerfs in atomized PR? Don't want to unintentionally nerf that
- Compile other (non-modifier based) racial change suggestions for implementation in other PRs
-- Such as Preternis super legs per Moggram suggestion, and Podperson olfaction override on brute damage per Aquizit
- [x] Other things to be added as they come along

# Wiki Documentation

These will need to be documented on each Species' page, perhaps through a new addition to the raceheader template at the top.

### ETHEREAL

- Brute Modifier: 1.25 -> 1.5
- (New) Burn Modifier = 0.8
- (New) Heat Modifier = 0.5
- (New) Cold Modifier = 2.0
- (New) Speed Modifier = 1.1 (-0.1 in code because the modifier is backwards)
- Electricity Modifier [Siemen's Coefficient] = 0.5 (Unchanged)
- (New) Punch maximum damage = 11 (Burning)
- (New) Punch stun range = 11 (Stuns on max hit as usual, ~9% chance)

### LIZARD
	
- Cold Modifier: 1.5 -> 1.75
- Heat Modifier: 0.67 -> 0.75
- (New) Temperature dependent stun modifier: 0.91 at high temperatures, 1.33 at low temperatures
-- Huge thank you to @Mqiib for the code on this.

### MOTH

- (New) Brute Modifier = 0.9
- (New) Burn Modifier = 1.25
- (New) Punch maximum damage = 9
- (New) Punch stun range = 10 (Unable to roll 10 on basic fist attacks, will not stun)

### PLASMAPERSON

- Brute Modifier: 1.5 -> 1.2
- Burn Modifier: 1.5 -> 1.5 (Unchanged)
- Heat Modifier: 1.5 -> 1.5 (Unchanged)
- (New) Electricity Modifier [Siemen's Coefficient] = 1.5
- (New) Punch maximum damage = 7
- (New) Punch stun range = 7 (Stuns on max hit as usual, ~14% chance)

### PODPERSON / PHYTOSIAN

- Burn Modifier: 2.0 -> 2.0 (Unchanged)
- Heat Modifier: 1.5 -> 1.5 (Unchanged)
- Cold Modifier: 1.5 -> 1.5 (Unchanged)
- Acid Modifier: 2.0 -> 2.0 (Unchanged)
- Speed Modifier: 0.33 -> 0.33 (Unchanged)
- (New) Electricity Modifier [Siemen's Coefficient] = 0.75
- (New) Punch maximum damage = 8
- (New) Punch stun range = 9 (Unable to roll 9 on basic fist attacks, will not stun)

### PRETERNIS

- Brute Modifier: 1.25 -> 1.25 (Unchanged)
- Burn Modifier: 1.5 -> 1.5 (Unchanged)
- (New) Heat Modifier = 1.75
- (New) Cold Modifier = 0.8
- (New) Speed Modifier = 0.9 (+0.1 in code because the modifier is backwards)
- (New) Electricity Modifier [Siemen's Coefficient] = 1.75
- (New) Punch stun range = 9 (Double crit range - stuns on roll of 9 or 10, 20% chance)

# Changelog

:cl: @Mqiib  
wip: Changes (most) all non-Human racial modifiers to give them more unique identity and drawbacks
tweak: Too many to list here, please see the PR body text for information
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
image
You changed the wrong podperson species
And I swear to god if you buff podpeople I'm going to throttle your scaley red neck

**Comment by Anvilman6** [comment]
Time to figure out why delinter is angry after work

**Comment by Marmio64** [comment]
i feel like a lot of the changes aren't really necessary and don't make the species different in an interesting way. In fact I feel like all these modifiers are going be confusing to players since it'll be hard to know what damage modifiers each and every species has and what that means for you. Adding more unique species mechanics and interactions would be far more interesting and memorable than just taking 10% less brute and 25% more burn.

**Comment by Anvilman6** [comment]
Like I said in the PR documentation, I will be taking a look at more actually unique changes later on, beyond just reshuffling numbers - it's just that with my current coding capabilities, this was a way to at least gives races some simple identity and uniqueness beyond "reskinned human lol"

**Comment by Chubbygummibear** [comment]
Mmmm delicious snowflake changes

**Comment by TheLinuxOS** [comment]
Id like to point out that the lizards having a larger stun modifier is contradictory to the fact that their martial art DECREASES stun duration on them. Im not 100% certain but by increasing their racial stun modifier it would thus also nerf their martial art

**Comment by Moggram** [comment]
PRETERNIS (forgot to add this)
Brute Modifier: 1.25 -> 0.9
The brute mod being 0.9 feels odd because our arms and lags only have 35 HP. Going to have to drop a big NO to this one.

Heat Modifier = 1.5
I can see why being all metal and along with a 1.5 burn mod.

Cold Modifier = 0.75
The only time this comes up is if I am in a fire suit and in space. coffee and oil will stop alot of the cold damage. A 0.75 mod may stop it all together. testing will need to be done.

Siemen Coefficient = 1.75
I don't get this one. We eat power and have circuits in our arms that deal with power flow. I think there be a grinding wire.

Punch stun range = 9
mah... aim head/groin and get a tool box.

I can't comment on the other races as I do not play and or maybe drunk.

**Comment by ToasterBiome** [comment]
Hidden values are bad bad for players unless they’re obvious and only in certain circumstances, every race having slightly different numbers is questionable

**Comment by Mqiib** [comment]
> Hidden values are bad bad for players unless they’re obvious and only in certain circumstances, every race having slightly different numbers is questionable

That's what the wiki is for, right anvil, maker of this pr and wiki director mans?

**Comment by ToasterBiome** [comment]
> > Hidden values are bad bad for players unless they’re obvious and only in certain circumstances, every race having slightly different numbers is questionable
> 
> That's what the wiki is for, right anvil, maker of this pr and wiki director mans?

The wiki is great and in depth and anvil does an amazing job, i just don’t feel like stuff like “does 1 less damage when punching” and “doesn’t stun on punches” seems like its… needed? I hope to see what other racial benefits there are and how wildly unbalanced they will be

**Comment by Mqiib** [comment]
> > > Hidden values are bad bad for players unless they’re obvious and only in certain circumstances, every race having slightly different numbers is questionable
> > 
> > 
> > That's what the wiki is for, right anvil, maker of this pr and wiki director mans?
> 
> The wiki is great and in depth and anvil does an amazing job, i just don’t feel like stuff like “does 1 less damage when punching” and “doesn’t stun on punches” seems like its… needed? I hope to see what other racial benefits there are and how wildly unbalanced they will be

All it needs is stuff like "More susceptible to burn damage" and "don't punch quite as hard as a human can" and stuff. It doesn't have to be specifics so long as it's documented in the positives/negatives. Also making the races more different is totally worth them maybe being not super homogeneous and "balanced" because that's more fun.

**Comment by Reed0506** [comment]
i feel as though the ethereal speedmod change you are putting in isnt intentional, as you are referencing the speed of light while making them slow. higher speedmod reduces speed more. 1.1 speed mod is slower than alloy golems, gold golems, and pre-buff plasmamen from what i recall. speedmod is not a multiplier, its a flat number added to the number of deciseconds it takes for you to move from tile to tile (or at least that is my vague understanding). you would need a negative speedmod to make them move faster. (-0.1)

i also dont really see the point of putting even more weaknesses on to pods, they are extremely vulnerable to many major damage sources already.

**Comment by Reed0506** [comment]
as far as pods go, i think they are mostly fine as is, they should have their extreme damage vulnerabilities to counteract their weak healing, but if you are genuinely considering a slight buff i would be most happy with changing their speedmod slightly to .25 or .1 or something.

**Comment by alexkar598** [comment]
Not a fan of preternis buff, being able to heal without a medkit is major

**Comment by Anvilman6** [comment]
@Moggram @alexkar598 
Been mulling over some adjustments to Preternis. As you both had input on that species, let me know what you think about these changes.

- Brute Modifier: Revert up to 1.25
- Heat Modifier: Increase to 1.75 (Possibly scale up Burn Mod to keep pace)
- Cold Modifier: Up to .8 from .75, hopefully avoiding any weird circumstances as Moggram pointed out
- Electricity Modifier [Siemen's Coefficient]: Keep at 1.75 as there's an inherent different in a computer or something similar taking in charge through intended routes (eating APCs), and being jolted by an outside source.
- Movespeed -10%

Another change that crossed my mind was to do something with the lungs, such as make them a little more effective at full charge, and give diminishing returns as charge decays (falling to below the current values for STARVING and possibly HUNGRY), but this may be for an atomized PR as it goes beyond the modifier refactoring that this PR is scoped for.

**Comment by Anvilman6** [comment]
Also a thank you to @Reed0506 for continually pointing out my stupidity in here and on the Discord and helping make the PR function as intended

**Comment by alexkar598** [comment]
Speed mod is sad

**Comment by Moggram** [comment]
I have been mulling over the 0.1 speedmod. It be cool to have a [MASC](https://mwo.fandom.com/wiki/Myomer_Accelerator_Signal_Circuitry_(MASC)) system to make up for it.
You could have it damage over time to the legs, eat alot of power or have a big slow down after 5-10 second of use.

**Comment by Anvilman6** [comment]
> I have been mulling over the 0.1 speedmod. It be cool to have a [MASC](https://mwo.fandom.com/wiki/Myomer_Accelerator_Signal_Circuitry_(MASC)) system to make up for it.
> You could have it damage over time to the legs, eat alot of power or have a big slow down after 5-10 second of use.

This is an interesting idea! I'll add power legs to my list of species changes to examine in atomized PRs following this one

**Comment by Mqiib** [comment]
A more interesting change for lizards rather than just making their racial benefits just worse might be to increase their stun mod based on how cold they are (like +0.5 per cold level, up to +1.5) and have a slight reduction in their stun mod if they're warm (-0.1 in temperatures of 40+ degrees C) probably just adjusted on_mob_life or something

**Comment by JamieD1** [comment]
Test Merged

**Review by JamieD1 — APPROVED** [review]
Lets go

**Pull request merged**
