### PR TITLE
Adds Particle Physics

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

This PR adds a new way for science to make more research points: particle physics. Nuclear particles have a chance to collide with each other into stronger particles for 180 research points per collision, or higher if you can get the stronger particles to collide.

Scientists will also be able to use particle emitters for this, which function the same as normal emitters but require you to put a tank full of tritium into them to function, however nuclear particles from any source are able to collide. They can be emagged to fire more powerful particles, but this makes them radioactive when firing.

# Spriting

image

# Wiki Documentation

Add particle emitters to the machines and research items wiki pages, mention they require a tank full of tritium to be inserted into them while the panel is open for them to work. Could also mention particle collision and the emitters on the guide to R&D.

# Changelog

:cl:  
rscadd: adds particle emitters and nuclear particle collision
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Probably going to need a unique sprite

**Comment by MajManatee** [comment]
No activity nearly a month, reopen when work continutes

**Comment by cuackles** [comment]
u killed icon bot 
image

**Review by cuackles — APPROVED** [review]
iconbot is still dead this is so sad, but the sprites where reviewed, nuclear emitter is distinct enough that it should be easily distinguishable

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
