### PR TITLE
Adds side door to medbay [Forum Request]

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request

Adds a side door to medbay.
Moves central primary firelock row up one tile so it doesn't look weird.

# Wiki Documentation
photo update?

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added side medbay door
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Again with this

**Comment by Anvilman6** [comment]
I disagreed with this when I saw it on the forums, and I disagree with it here in execution.

The delivery flaps and door serve the purpose needed - adding an actual accessway is a flimsy addition at best, and actively detrimental at worst (especially if they are public access like the forum post suggested).

**Comment by maxion12345** [comment]
> I disagreed with this when I saw it on the forums, and I disagree with it here in execution.
> 
> The delivery flaps and door serve the purpose needed - adding an actual accessway is a flimsy addition at best, and actively detrimental at worst (especially if they are public access like the forum post suggested).

They are not public access. Carbon copies of the main reception door.

**Comment by JamieD1** [comment]
I get it, I like the idea, however I don't think its necessary in the grand scheme of things, people can shortcut through the paramedic room if they really need to get in that way. It also seems this is an unpopular take, will leave it up for a few days to see if anyone else wants to give input.

**Comment by JamieD1** [comment]
Sorry too much negativity towards this PR, I appreciate your effort on it however.

**Pull request closed without merging**
