### PR TITLE
Buffs my favorite little department (New biogenerator recipes)

### PR DESCRIPTION
**Pull request by Majkl-J**
# Document the changes in your pull request

The people asked, and I deliver.
Adds a good list of new cooking ingredients to the biogen.

image
image

Originally wanted to also make it not require a beaker to function but that idea is scrapped and dead just like my brain on tgui.

# Wiki Documentation
Added rice, meat, and eggs to the food section
Added a new section for chef chems
Added soy milk and soy sauce to said section
Removed all the milk/cream cartons as they are kinda useless

# Changelog
:cl:  
rscadd: Expands the biogenerator recipe list significantly
tweak: Cooks no longer need to play around with the grinder just to make random u rice
/:cl:

### CODE REVIEW

**Comment by Therandomhoboo** [comment]
ew bartender area is better

**Comment by TheBombMakerJL** [comment]
Does synthetic meat contain the same amount of nutrients/vitamins as regular meat because I’m pretty sure cryo synthmeat is dogshit

**Comment by Maia-J** [comment]
> Does synthetic meat contain the same amount of nutrients/vitamins as regular meat because I’m pretty sure cryo synthmeat is dogshit

Yes! It is infact just regular meat

**Comment by burn1cycle** [comment]
Goats are a aggressive mob type and space vines are trivialized by they're use so goat spam would be problematic. Can you remove goats please?

Edit: Maybe goats could be a emagged feature?

**Comment by Maia-J** [comment]
The goats were there before

**Comment by kooarbiter** [comment]
I genuinely love this PR, thank you king/queen/auxiliary monarch


also emagged biogens should make goat cubes which become super evil goats

**Review by ToasterBiome — APPROVED** [review]

**Comment by Cartlord** [comment]
you dick, you didn't document that you gave them free saltpetre

**Comment by Rdrazga** [comment]
It is ME! The unofficial balance council yelling at you for this!

**Pull request merged**
