### PR TITLE
makes synthetic alien plasma vessel researchable without deconstructing alien organs

### PR DESCRIPTION
**Pull request by boodaliboo**
this tech does not give you anything else so doing this wont really do much of anything 
:cl:  
tweak: tweaked synthetic alien plasma vessel tech

/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
originally this was meant to be a little research path that would give access to a couple xeno themed organs but all the ideas I had for organs were stupid
I might throw some stuff in later but this allows for wide access to plasma vessels which give constant access to passive healing which is stronger than any other implant

**Comment by boodaliboo** [comment]
> originally this was meant to be a little research path that would give access to a couple xeno themed organs but all the ideas I had for organs were stupid I might throw some stuff in later but this allows for wide access to plasma vessels which give constant access to passive healing which is stronger than any other implant

how would i nerf the healing specifically for this vessel?

**Comment by nmajask** [comment]
I think the plasma vessel is a nice reward for sci after the station stops an infestation or dealing with meateors. The tech should probably be expanded a bit, with maybe other organs based on those that xenos have (i.e. a resin spinner that can put down atmos resin or a neurotoxin gland that can shoot chems).

**Comment by JamieD1** [comment]
No plasma Vessels.

**Pull request closed without merging**
