### PR TITLE
Revives [#14873] Makes medkits actualy useful for medbay

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

https://github.com/yogstation13/Yogstation/pull/14873 Revives this PR. See it for more details, including photos of medkit contents. No changes made to that PR's code.

one non-coder complaint isn't enough to close a good PR in my eyes.

# Spriting

Sprites had already been approved on that PR

# Wiki Documentation

Need to have the kits updated in the medical supplies page.

# Changelog

:cl:  @nmajask 
tweak: brute/burn kits now have their respective medical sprays in them
tweak: medical sprays now hold half the reagents (this does take into account synthflesh sprays in vendors)
tweak: brute kits now have salicyclic acid pills
tweak: oxygen kits now have two epipens and 4 syrignes of perfluorodecalin
tweak: advanced health kits have been completely reworked and now store the same amount as surgical kits
/:cl:

### CODE REVIEW

**Comment by GraveHat** [comment]
Do keep them in mind though, still, I do want the medkits to be more packed and I really do not think nerfing the sprays would do much in the grand scheme of medbay in the long run now that hypos are introduced. Although still not being able to find a resolution in making the medicinal spray cans actually useful enough to have a reason to be used is still a gripe of mine that I should eventually find a conclusion for. Somewhat unrelated to the topic at hand.

**Comment by Notamaniac** [comment]
This still nerfs medical sprays for a completely unnecessary reason.

**Comment by VaelophisNyx** [comment]
> This still nerfs medical sprays for a completely unnecessary reason.

they're too strong
cope

**Comment by Notamaniac** [comment]
> > This still nerfs medical sprays for a completely unnecessary reason.
> 
> they're too strong cope

Why are they too strong?

**Comment by MegaEmpirical** [comment]
Question, though maybe the original author is better to ask: How does nerfing sprays encourage medical to use them?

**Review by KillerOrcaCora — APPROVED** [review]
Was already approved

**Comment by VaelophisNyx** [comment]
> Question, though maybe the original author is better to ask: How does nerfing sprays encourage medical to use them?

it's not so much that we need encouragement to use them; we already do and probably always will
this just makes them not invalidate hyposprays, and also they were and still are refillable with whatever so...yeah

**Comment by Notamaniac** [comment]
> > Question, though maybe the original author is better to ask: How does nerfing sprays encourage medical to use them?
> 
> it's not so much that we need encouragement to use them; we already do and probably always will this just makes them not invalidate hyposprays, and also they were and still are refillable with whatever so...yeah

So the reason is that you want to force people to use the more expensive hyposprays... even though it's more space efficent to take and use the sutures and meshes from the white kits if you need to treat people in the field. And that people inside medbay should still be using the sleepers and tend wounds surgery.

Then again non coder complaint. The free styptic and sulf sprays might be getting removed in a future PR so who am I to complain. Cope, seethe, blah blah blah.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
