### PR TITLE
Changes cat wagging animation

### PR DESCRIPTION
**Pull request by UselessTheremin**
ports https://github.com/tgstation/tgstation/pull/56750

resprites good I don't want this to turn into a huge stupid "fetish content cat degenerate" thing, rewarding donors with better looking things shouldn't be controversial.

:cl:  EikoBiko
tweak: altered the wagging cat tail sprite
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
fetish content tag when

**Comment by Mqiib** [comment]
cringe cat tail sprite doesn't have the sprites split up properly into front adjacent and back

**Review by nesisknesis — COMMENTED** [review]
credit EikoBiko in da changelog

**Review by nesisknesis — COMMENTED** [review]
actually i can do it nvm

**Review by nesisknesis — COMMENTED** [review]
i did it

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
