### PR TITLE
Changes to Rad Storm

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Add auto maint access to rad storm,

Also makes it so tcomms is down during it

#### Changelog

:cl:  
rscadd: Adds auto access to rad storms and removes comms
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Think it just needs a buff, or keep it as it is.

**Comment by MegaEmpirical** [comment]
Relevant to this discussion: https://forums.yogstation.net/index.php?threads/add-comm-blackout-to-radiation-storm.21217/

Because the maintenance access requires that someone enable it and in the absence of an AI or head, people are fucked and since we're now disabling comms, may as well at least give them a chance.

**Comment by BOBsHERE** [comment]
Removing coms is great but auto access is bad

**Comment by Xoxeyos** [comment]
Add a short delay to the auto access, if you're going to add it.

**Comment by Ktlwjec1** [comment]
you might need to modularise this so be prepared to split this into 2 prs

**Comment by MegaEmpirical** [comment]
If you're going to say something is bad then explain why it is bad. Should for good as well but currently the negative is more useful.

**Comment by BOBsHERE** [comment]
This has been debated before. If you make maint access automatic then rad storms are very pointless as there is no actual threat to anyone who has any ability to walk. Rad storms already do very little damage that cannot be fixed in a mildly upgraded sleeper.

**Comment by MegaEmpirical** [comment]
The access was mostly to compensate for removing comms, and the issue with rad storms is rarely that there isn't access but rather people not hiding in time regardless of access. That said, lets remove the access then,

**Comment by boodaliboo** [comment]
rad storms should be dangerous

**Comment by Hopekz** [comment]
> The access was mostly to compensate for removing comms, and the issue with rad storms is rarely that there isn't access but rather people not hiding in time regardless of access. That said, lets remove the access then,

How is that an "issue"? 
The Harmful event being harmful?

**Comment by boodaliboo** [comment]
i like the idea of comms going off i dont like auto maint make two seperate prs and that would be great

**Review by alexkar598 — APPROVED** [review]

**Comment by alexkar598** [comment]
Closing due to overall negative feedback. If AI or captain doesnt engage maint access, thats on them. Though luck, find an engi to open the door or scream on comms you are about to die.

The comms thing just steals away from the ion anomaly

**Comment by MegaEmpirical** [comment]
The negative feedback was for the auto emergency, why close it instead of requesting a change?

**Comment by JamieD1** [comment]
> Closing due to overall negative feedback. If AI or captain doesnt engage maint access, thats on them. Though luck, find an engi to open the door or scream on comms you are about to die.
> 
> The comms thing just steals away from the ion anomaly

And what if there is no ai or captain big brain.

Also this has a hard limit of once per round, so it doesnt steal from ion.

**Comment by Hopekz** [comment]
> And what if there is no ai or captain big brain.

Your PR doesn't check if there is a captain or AI on station it just does it every time. Confused?

**Pull request closed without merging**
