### PR TITLE
Adds the Song "Carmen Miranda's Ghost".

### PR DESCRIPTION
**Pull request by Xoxeyos**
Here is the link, for your listening pleasure.

https://www.youtube.com/watch?v=D5p8YhhaVlA

🆑
rscadd: Adds the Song "Carmen Miranda's Ghost".
/🆑

### CODE REVIEW

**Comment by Xoxeyos** [comment]
I don't know why github is being retarded and adding all these previous commits, the only one that should matter here is 0a761c2, and only one file should be changed in this PR.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
/datum/controller/subsystem/ticker/proc/choose_lobby_music()
	//Add/remove songs from this list individually, rather than multiple at once. This makes it easier to judge PRs that change the list, since PRs that change it up heavily are less likely to meet broad support
	//Add a comment after the song link in the format [Artist - Name]

**Comment by LoliconSlayer** [comment]
1 song per PR nerd

**Comment by Bibby0110** [comment]
1 song per PR nerd

**Comment by Xoxeyos** [comment]
Fixed.

**Comment by Ktlwjec1** [comment]
Going to do these on downvotes and it's 2v3 so I'll close this one. If you want more opinions on the other prs (I'm assuming you'll make more) I'd suggest a forum post or advertising it in OOC or discord.

**Pull request closed without merging**
