### PR TITLE
[admin]  Adds a quick access clock camera console to CC

### PR DESCRIPTION
**Pull request by Hopekz**
Near the pod bay area separated by space and more walls for when you want to "pod in" to the station by teleporting instead

Triple walled for security

image

#### Changelog

:cl:  
rscadd: CentralCommand clock camera console added for convenience 
/:cl:

### CODE REVIEW

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Im not sure if thats in the shuttle docking zone but regardless, just plant the computer somewhere on cc, no need to have a special isolated room. Thats just wasting space. CC is supposed to be accessible as the shit on it is very much overpowered so "security" on CC is just stupid

**Comment by Hopekz** [comment]
Alright I'll move it here when I get home 

image

**Comment by JamieD1** [comment]
> Alright I'll move it here when I get home
> 
> image

Arena shuttle would break even more if that was there. So yeah moving it out the way would be cool.

**Comment by alexkar598** [comment]
This PR has been closed due to being stale. Contact me or another maintainer on Discord if you wish for this PR to be reopened.

**Pull request closed without merging**
