### PR TITLE
Adds Programming "Socks"

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Adds programming "socks" but they are actually shoes.

Wearable by everyone, but only one pair is available, and it's in the sig techs' vending machine.

normal_left
normal_right
normal_back
normal_front

coderhuman

lizard_front
lizard_left
lizard_right
lizard_back

coder

# Wiki Documentation

Add the socks to the wiki page on clothing, and their respective images

# Changelog

:cl:  
rscadd: Adds the programming "socks"
coder

/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Time to accost the sigtech for their socks

**Review by Altoids1 — APPROVED** [review]
🏳️‍⚧️ 

Since there are already stripey socks as an underwear option in the character creation screen, this shall allow for spessmen to wear two pairs of programmer socks at the same time.

**Review by Bibby0110 — APPROVED** [review]

**Comment by Hopekz** [comment]
This looks like a donator item so I'd add that there personally.
Fits both ways imo

**Comment by MajManatee** [comment]
These socks were almost "lizard only"

**Comment by maxion12345** [comment]
> This looks like a donator item so I'd add that there personally. Fits both ways imo

gotta pay the femboy tax now huh

**Comment by JamieD1** [comment]
Cringe meme. 0/10

**Comment by Hopekz** [comment]
> Cringe meme. 0/10

found the guy that doesn't wear socks

**Comment by Simplehorror** [comment]
> Cringe meme. 0/10

**Comment by nesisknesis** [comment]
We already have programming socks.

**Pull request closed without merging**
