### PR TITLE
adds a ticket machine to boxstation

### PR DESCRIPTION
**Pull request by ReddicusDragon**
see title
:cl:  
rscadd: adds a ticket machine to box  
rscdel: removes a wall by hop office  
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
The way it is now it looks super weird, maybe try rotating it to be facing left and add thin windows?
something like this
vivaldi_WFfsI0luvI

The problem is that the firelocks just cut off, we don't want that

**Comment by ReddicusDragon** [comment]
@wejengin2 basically the ticket machine doesn't have directional sprites also will that suffice in window placement

**Comment by jcatjmeow** [comment]
You can put windows on those places and still click on the machine from the side

It needs to face forward so you can see the numbers

**Comment by jcatjmeow** [comment]
Misclick

**Pull request closed without merging**
