### PR TITLE
Head of Staff minimum for revs to start

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
This change ensures that there has to be a MINIMUM of 3 heads of staff in order for revs to start, otherwise reverting to pregame lobby.

# Changelog

:cl:  
tweak: no more lone head rev rounds
/:cl:

### CODE REVIEW

**Review by Moltijoe — APPROVED** [review]
no clue if LAZYLEN() is preferred over .len
but i see no problem with this

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
This won't work. 
pre_setup runs before jobs are handed out

**Comment by Moja10** [comment]
Two is the better minimum, not three IMO

**Comment by MajManatee** [comment]
FUCK ok, ill have to look into how to do this then. Not at home so I dont have the usual resources.

**Comment by BurgerLUA** [comment]
Another way to fix this is to assign kill objective to those lower on the capitalist pyramid.

https://upload.wikimedia.org/wikipedia/commons/2/26/Anti-capitalism_color%E2%80%94_Restored.png

Heads > Chaplain > Warden > Sec > Cargo.

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
nah that just mean no revs spawn,basically extended
don't think there's a good way to do this tbh (maybe force 3 heads to get picked, but that kinda sucks too)

**Comment by RG4ORDR** [comment]
Thank fuck.
Revs spawning with 1 head(CMO), and 1 security (Detective), was the most annoyingly unfair and unfun gamemode roll. Like who are you rebelling against, the lone CMO coked out on coffee and the drunk detective??

**Comment by MajManatee** [comment]
> nah that just mean no revs spawn,basically extended don't think there's a good way to do this tbh (maybe force 3 heads to get picked, but that kinda sucks too)

Better than the alternative i guess. Ill look at how sec is forced.

**Comment by MajManatee** [comment]
yeah i dont know, not really a great way to do it, and i dont feel motivated enough to make it work. Might change later.

**Pull request closed without merging**
