### PR TITLE
black overlay, unconscious = black screen

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

## BLIND PEOPLE CAN STILL SEE THE SAME AS BEFORE

playing a black screen for the whole round would be shitty and it makes sense to be able to "see" via touching things immediately adjacent, this only targets unconscious people

### Intent of your Pull Request

when you are unconscious, your screen will go completely black
can still see HUD and by extension items, **does not trigger on softcrit**, will trigger on hardcrit, triggers on sleep/unconscious, "barely conscious" is not unconscious

unedited gameplay footage (used teleport and self-rez verbs to speed things up)

### Why is this change good for the game?

greater immersion & uncertainty when sleeping, better potential for kidnap & release gimmicks, no more metaing everything and everyone you saw while sleeping when you aren't supposed to be seeing anything

# Changelog

:cl:  
tweak: You can no longer see the real world when you're sleeping
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Oh boy surgery with anesthetics will be even more fun and engaging.

Whatever, only thing I really dont like about this PR is the fact that black screen usually means theres something wrong with BYOND and that might confuse some people into thinking they're bugged out. Not sure how you'd fix that but likely not a reason to close this PR.

**Comment by boodaliboo** [comment]
yes i love to sit completely still in medbay with no indication of whats going on for 15+ minutes unconcious

**Comment by maxion12345** [comment]
What if it was completely black except for your character? Like current uncon but you can't see anything but you. That way people are atleast a bit aware (is someone stripping me?.)
 Has nobody come near me for awhile so I should ghost? Etc)

**Comment by ynot01** [comment]
> Has nobody come near me for awhile so I should ghost?

if you're asleep for that long you're either asleep by the hand of someone intentionally or you're stuck in cryo
if someone stuck you in cryo and forgot about you, im sorry

**Comment by Yogbot-13** [comment]
#### Test Merge Deployed

##### Server Instance
main

##### Revision
Origin: 39c610f599c05ab55c9551c8328eb9cd5b838117
Pull Request: d5c726533791784cd24fd2247a55eae3800a5aa3
Server: ce13dee3d6e20b89dc7daedfb859ee58550b7dcf

**Review by Partheo — APPROVED** [review]

**Comment by Bibby0110** [comment]
This is fine from a realism/RP standpoint

From a gameplay standpoint this is the most boring change ever. Especially with how long you can be knocked out it's incredibly boring to just be sitting there. Sure either way you can't do anything, but you can at the very least *hope* something can be done the old way.

**Comment by ynot01** [comment]
> This is fine from a realism/RP standpoint
> 
> From a gameplay standpoint this is the most boring change ever. Especially with how long you can be knocked out it's incredibly boring to just be sitting there. Sure either way you can't do anything, but you can at the very least _hope_ something can be done the old way.

disagree; the gameplay element of not knowing is a great one, enables antagonists to create more interesting situations and disorient you by not knowing what's happened or where you are

**Comment by Bibby0110** [comment]
> > This is fine from a realism/RP standpoint
> > From a gameplay standpoint this is the most boring change ever. Especially with how long you can be knocked out it's incredibly boring to just be sitting there. Sure either way you can't do anything, but you can at the very least _hope_ something can be done the old way.
> 
> disagree; the gameplay element of not knowing is a great one, enables antagonists to create more interesting situations and disorient you by not knowing what's happened or where you are

disagree; the gameplay element is fun for nobody but the antag. Disorienting the player is realistic sure, but not fun.

**Comment by JamieD1** [comment]
Eh, this will just piss off the player to be honest, yeah its more realistic, but do you want to be kept unconscious for like 20 minutes if the antag just wishes for it to be and you can do nothing but stare at a black screen? Good for realism sucks for a GAME

**Comment by SomeguyManperson** [comment]
it SHOULD be possible to make people unable to just see or recognize people like drones. It'd be a bit more complex  but possible

**Comment by Bibby0110** [comment]
> it SHOULD be possible to make people unable to just see or recognize people like drones. It'd be a bit more complex but possible

defo possible and arguably a better solution in my opinion.

**Comment by MegaEmpirical** [comment]
Wasn't working for me, I could see as if I was awake.

image



These were bodies spawned by Select Equipment, that's all I got. Tested it twice. Round 34690

**Comment by ynot01** [comment]
> lyis

can only imagine it's due to testmerge fuckery, as nothing in my code has changed and it is tested and working

else might be BYOND version issue or just a random bug that requires a client restart

**Comment by MegaEmpirical** [comment]
Theos says it's not related, disregard

**Comment by Cartlord** [comment]
I don't like the total black-screen when blinded, since it's just... not fun. It's hard to do anything if you can't see anything.

**Comment by MegaEmpirical** [comment]
Hard to do anything if you're unconscious too.

**Comment by Cartlord** [comment]
I said BLIND. A guy stabbed my eyes out and I was basically unable to do anything for the rest of that round - I'm lucky I was on the shuttle already by then.

**Comment by burn1cycle** [comment]
I don't like it. I can't tell if I am screwed for rest of the round and should just ghost or stay-in-body and that's a waste of my time I can go do something else with if I am.

**Comment by MegaEmpirical** [comment]
> I said BLIND. A guy stabbed my eyes out and I was basically unable to do anything for the rest of that round - I'm lucky I was on the shuttle already by then.

This PR isn't supposed to affect the blind. No idea what's going on there.

**Comment by Cartlord** [comment]
> 
> 
> > I said BLIND. A guy stabbed my eyes out and I was basically unable to do anything for the rest of that round - I'm lucky I was on the shuttle already by then.
> 
> This PR isn't supposed to affect the blind. No idea what's going on there.

I mean, I can't think of anything that would force a black overlay there, other than the PR that gives a black overlay under certain conditions.

**Comment by MegaEmpirical** [comment]
Sad, why was it closed?

**Pull request closed without merging**
