### PR TITLE
Changes speed potion logic

### PR DESCRIPTION
**Pull request by ThatLing**
Being able to have a stun-proof, slip-proof vehicle with 0 delay is super overpowered.

### CODE REVIEW

**Review by Amelia0010 — APPROVED** [review]

**Comment by monster860** [comment]
Waaait. This doesnt just affect vehicles it nerfs hardsuits too

**Comment by Reed0506** [comment]
its been over 2 years, but i must mention that this PR made speed potions unusable on all except 2 clothes in the entire game lmao

**Comment by ThatLing** [comment]
good change

**Comment by Amelia0010** [comment]
> its been over 2 years, but i must mention that this PR made speed potions unusable on all except 2 clothes in the entire game lmao

1st of all.
Yes no shit that is the point of the PR

2nd of all.
No you don't have to mention that, you could just leave the PR as is

**Comment by ThatLing** [comment]
hi nichlas how are you

**Pull request merged**
