### PR TITLE
Juggernaut Suit Resprite (EN Edition) 

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
Ah, hello, friend...You seem to want to storm my base... well...Let me first warn you that this is not grandma's hut of warmth and care...no no... it will be a hell beyond your imagination, a hell where the pain will not stop at the burning pain that you will feel when you gather the remaining energy in you to remove your falling skin from the hard ice iron through which you will drag yourself, Where you will kill 50 people, there will be another 500, and then, as soon as you will think that we have run out of ammunition, we will shoot 2 times more ammunition than we have already shot...Now, do you really want to die for a suit?

4c0a2w

# Spriting

Newmaour

# Wiki Documentation
XAXAXAXAXAXA
nEWHELMENT
juggmynauts

# Changelog

:cl:  

imageadd: New sprite changed that your prob not even good enough to even get to see in-game. 

/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
For the cultured folk who use google translate like I -

Ah, hello friend... You seem to want to storm my base... Well... Let me first warn you that this is not grandma's hut warmth and care...no no... it will be hell outside your imagination, a hell where the pain doesn't stop at the burning pain you'll feel when you muster the energy left in you to peel your falling skin off the hard icy iron you'll be dragged through Where you kill 50 people, there will be 500 more, and then just when you think we're out of ammo, we'll shoot twice as much ammo as we've already shot...Now, do you really want to die for the suit?

In fact, the director of knowledge in this institution.

Bottom Part - 

XAXAXAXAXAXA They didn't even add the ones from 3 months ago!

**Comment by KillerOrcaCora** [comment]
Wrong WRONG Wpwegrht
egrqgwb
w
wnr
nt
fsnr
ntrsf SYCKLA BLAYT erhalwr[prwht
tjsnrh

**Comment by KillerOrcaCora** [comment]
image

Cuckles said no flag during the build stage, WE COULD OF HAD SOMETHING GREAT!!!

**Review by cuackles — APPROVED** [review]
good sprite, about the rusian flag, thats a no, ideally no flags denoting nations and specially not nations that have started a war against other nations recently, also if you do a pr again writen in not english and dont put a translation i will find where u live and trow u off a window, apart from that good sprite

**Comment by Sniblet** [comment]
English only server

**Comment by MajManatee** [comment]
sprite looks cool WITH the flag

**Comment by Bibby0110** [comment]
English repository

**Comment by cuackles** [comment]
shit is in english now so now we wait

**Comment by Rdrazga** [comment]
> good sprite, about the rusian flag, thats a no, ideally no flags denoting nations and specially not nations that have started a war against other nations recently, also if you do a pr again writen in not english and dont put a translation i will find where u live and trow u off a window, apart from that good sprite

I do want to put out there that we literally have an entire suit which is just the US flag. and IIRC there is a british flag reference on some items in the game but I may be wrong on this. So the part about not denoting flags of nations is bs. 

Ideally for consistency sake though we have a soviet Russian flag rather then modern Russian since soviet Russia fits the themes of all the Russian stuff in game better, but that can't exactly be sprited on a small thing like this.

**Comment by MajManatee** [comment]
I liked it when it was all in russian

**Pull request merged**
