### PR TITLE
Ultra badass syndicate fedora

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Adds the syndicate fedora. Sharp for the sharp dresser. Has a sharp extended mode that deals some damage.

Located in badass tab of syndicate uplink, costs 3 telecrystals.

image

#### Changelog

:cl:  
rscadd: Adds the syndicate fedora, located in the badass tab of the syndi uplink for 3 tc
imageadd: Adds the syndicate fedora
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
embed is aids please no

but otherwise is good

**Comment by swissloaf** [comment]
> embed is aids please no
> 
> but otherwise is good
> 
> 

cant be a sharp dresser without the sharp

**Comment by ynot01** [comment]
yea thing is embed is useless as a weapon in this game

if you throw an embed at someone they go AAAAAAAA and run away with the weapon that you just threw at them that you spent 3TC on

this is why athiest fedora is useless for everything except opening airlocks

**Comment by swissloaf** [comment]
> yea thing is embed is useless as a weapon in this game
> 
> if you throw an embed at someone they go AAAAAAAA and run away with the weapon that you just threw at them that you spent 3TC on

hmm. I guess we can rmeove it then

**Comment by Marmio64** [comment]
nevermind, i forgot e-dagger exist

**Review by Partheo — CHANGES_REQUESTED** [review]
Pinged you on Discord, sprite needs improvement.

**Review by Partheo — APPROVED** [review]

**Pull request merged**
