### PR TITLE
Revert "Renames Yogstation to YogsBox (#12959)"

### PR DESCRIPTION
**Pull request by KittyNoodle**
This reverts commit 5c91612a238bdc3b2af913935d083311b62763fe.

# Document the changes in your pull request

Fixes issues #13162 and #13200

Renaming a station broke voting so hard and nobody has fixed it despite it being weeks. 
Please Testmerge while we wait for an actual fix.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  

rscdel: Temporarily reverts the yogstation renaming pending an actual fix for the bugs it caused 
bugfix: Voting works again  
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Voting will not work again as it is a problem with the game's interaction with the CDN and not a map name which is not used in local testing

**Comment by maxion12345** [comment]
please merge my pr before you do this I beg

**Comment by alexkar598** [comment]
The CDN works as expected, this is a problem with tgui and/or the asset caching system.

**Comment by ToasterBiome** [comment]
> The CDN works as expected, this is a problem with tgui and/or the asset caching system.

^ Guy is mad

**Comment by alexkar598** [comment]
> > The CDN works as expected, this is a problem with tgui and/or the asset caching system.
> 
> ^ Guy is mad

Don't think I am

**Comment by Bibby0110** [comment]
> > > The CDN works as expected, this is a problem with tgui and/or the asset caching system.
> > 
> > 
> > ^ Guy is mad
> 
> Don't think I am

Proof?

**Comment by adamsong** [comment]
Voting was broken long before the original PR was merged, this doesn't fix either mentioned issue

**Comment by Hopekz** [comment]
> Voting was broken long before the original PR was merged, this doesn't fix either mentioned issue

Well yeah who really knows because we test merged the name change for a while. Felt like it was test merged for like a week or two

**Comment by adamsong** [comment]
Better fix in #13236

**Pull request closed without merging**
