### PR TITLE
Decrease the chance of bubblegum spawning

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

the easiest megafauna in the game with the best loot and he has the highest spawning chances. a miner wrote this code
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Decrease the chance of bubblegum spawning
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Not even a bad idea to slightly reduce the chance, but this changes it from being common to being rare, what gives?

**Comment by MajManatee** [comment]
Name one time you have beaten bubblegum

**Comment by N3D6** [comment]
> the easiest megafauna in the game

you’re trolling at this point

**Comment by Simplehorror** [comment]
> Name one time you have beaten bubblegum

i just no hit him again locally lol

**Comment by N3D6** [comment]
> > Name one time you have beaten bubblegum
> 
> i just no hit him again locally lol

proof? bold claim

**Comment by Simplehorror** [comment]
> > > Name one time you have beaten bubblegum
> > 
> > 
> > i just no hit him again locally lol
> 
> proof? bold claim

not really, it's pretty trivial once you do it enough, tedious mostly

**Comment by ToasterBiome** [comment]
in a perfect world they would all spawn all the time

**Pull request closed without merging**
