### PR TITLE
Updates the moon

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Changes the moon in the background of all the stations

# Why is this good for the game?

there's a weird face on it now, what could it mean?

# Testing

it shows up

# Spriting

image

# Wiki Documentation

# Changelog

:cl:  
rscadd: Adds new moon
rscdel: Removes old moon

/:cl:

### CODE REVIEW

**Comment by Beeper-Skeeper** [comment]
deep lore

**Comment by Chubbygummibear** [comment]
i'm shooting the moon with the bluespace artillery

**Comment by cowbot92** [comment]
gonna make it a station trait

**Comment by ofscarletdreams** [comment]
majoras security gas mask

**Pull request closed without merging**
