### PR TITLE
Space Ninja nerfs

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Ninja sword now has a built-in "honor" clause and is completely non-lethal against anyone who has not directly attacked them 
(Doesn't stop them from picking up a toolbox, but it is 3x worse than the katana)

Kill/debrain objectives are automatically granted lethal status

#

Ninja can no longer upgrade their cell to a higher capacity

Ninja cell upgrades makes power usage absolutely trivial; You may still carry around bluespace cells for the same effect, but you will have to take an active role in recharging

To offset this, draining APCs now grants triple charge from before

# Changelog

:cl:  
tweak: Space ninjas draining APCs now do so 3x better
tweak: Energy katana is now non-lethal until you attack them directly or are an objective
tweak: Space ninjas can no longer upgrade their cell to a higher capacity
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
What's the point of this?
Ninja is one the most glass cannon antags in the game, and even one the most player knowledge dependent midrounds right behind blob. Linear cell upgrades are totally reasonable because it extends the Ninja's utility as an antag by all means make it so they need to upgrade from a full charged T2,T3, and T4 cell to actually do it. But don't remove it it serves no purposes lol.

Smart Ninjas already avoid sapping APCs outside of really specific areas and desperation because power from wires or solars is way better than depowering the room half the time. Buffing their suck speed is literally meaningless 

Ninjas aren't honorable, they're ninjas. They're cutthroats,assassins,mercenaries, they aren't an honorable SAMURAI WARRIOR. 
They already got a slight nerf to not being able to use guns anyway.

**Comment by ynot01** [comment]
> Ninja is one the most glass cannon antags in the game

Having 50/40/30 armor, 50 block chance, and mobility options that rival wizards does not equal glass cannon

> Linear cell upgrades are totally reasonable because it extends the Ninja's utility as an antag by all means make it so they need to upgrade from a full charged T2,T3, and T4 cell to actually do it. But don't remove it it serves no purposes lol.

Teleporting to the science or engineering protolathe and printing a bluespace cell (which is almost always researched by the point a ninja is spawned) takes very little effort and makes power management negligible for the rest of your round.

> Smart Ninjas already avoid sapping APCs outside of really specific areas and desperation because power from wires or solars is way better than depowering the room half the time. Buffing their suck speed is literally meaningless

You misinterpret, the change here will enable ninjas to drain power from an APC at 3x efficiency, providing 7500 (previously 2500) power form a single APC, which is nearly a full ninja suit charge.

> Ninjas aren't honorable, they're ninjas. They're cutthroats,assassins,mercenaries, they aren't an honorable SAMURAI WARRIOR. They already got a slight nerf to not being able to use guns anyway.

The purpose was to enrich gameplay first and foremost, everything else is secondary. The flavor text describes it as "safeties". If you want further or more sensible explanation, contact the lore team.

**Comment by RG4ORDR** [comment]
>Having 50/40/30 armor, 50 block chance, and mobility options that rival wizards does not equal glass cannon
Default armor for most the station is 30/30/30, ninja has slightly better protection to melee and ballistics but retains similar laser protection to standard armor vests on station. Seems pretty balanced give ninjas are usually spawning in at a time where sec can be wearing Mk3 or Mk4 plated armor which on par or superior to Ninja's suit. Likewise security is more than likely going to be operating energy weapons. Temp gun shots can demolish a ninja, dragnet works just as well. I'm not even touching on the fact you need to disable your suit, to even heal yourself and eat. 
Energy swords have 50% block chance yet we witness them getting dunked on pretty consistently.

>*Cells*
I gave you a solution. It isn't the Ninja's fault they are 45-50+ round spawn. Make them have to progressively tier their suits powercell by forcing T2,T3, and T4. Otherwise you need to give the Ninja's suit T3 powercell by default.

>You misinterpret, the change here will enable ninjas to drain power from an APC at 3x efficiency, providing 7500 (previously 2500) power form a single APC, which is nearly a full ninja suit charge.
The ninja doesn't need to be sapping APCs like a starved dog. Their current drain rate isn't even a gameplay issue.

>Lore
True I guess.

But this circle backs to what's the actual point to this when your suggestions for change are extremely tenuous at best.
A decently geared traitor is pretty much on parity with a ninja they just lack stealth and a jaunt ability.

**Comment by ynot01** [comment]
> Ninja armor is not impressive

Ninjas have permanent -1 speed and can teleport 3 walls away at the first sign of danger

> Otherwise you need to give the Ninja's suit T3 powercell by default.

Ninjas can do just fine with a T1 cell

> Their current drain rate isn't even a gameplay issue.

People don't care about it because it's completely negligible. The only person that would care about power management would be the ninja and because the ninja doesn't care about it and no one actually expects the ninja to run out of power and have to retreat, no one cares.

> But this circle backs to what's the actual point to this when your suggestions for change are extremely tenuous at best.

Better gameplay and knocking down one of the strongest antags (which is a midround) down a peg

> A decently geared traitor is pretty much on parity with a ninja they just lack stealth and a jaunt ability.

> **they just lack stealth and a jaunt ability**

The ability to dash is one of the major reasons ninja stands atop all other antagonists on par with a wizard. Being able to sit comfortably at 20 alpha is also very helpful, but not as impactful as jaunting.

**Comment by Marmio64** [comment]
Whenever I've played as ninja without cell upgrades I'd find myself having to recharge so often it becomes straight up unfun to play. After a short while of stealth and a scuffle, boom, go have to charge again. Now, bluespace cell was pretty unbalanced for ninja to have given that it lets you go for too long without charge, but standard cell is the bare minimum for ninjas and is terrible to play with simply on the matter, as if it wasn't bad enough to sit through the suit takeoff sequence to heal and eat (save for a few healing items)

**Comment by RG4ORDR** [comment]
> > Ninja armor is not impressive
> 
> Ninjas have permanent -1 speed and can teleport 3 walls away at the first sign of danger
> 
> > Otherwise you need to give the Ninja's suit T3 powercell by default.
> 
> Ninjas can do just fine with a T1 cell
> 
> > Their current drain rate isn't even a gameplay issue.
> 
> People don't care about it because it's completely negligible. The only person that would care about power management would be the ninja and because the ninja doesn't care about it and no one actually expects the ninja to run out of power and have to retreat, no one cares.
> 
> > But this circle backs to what's the actual point to this when your suggestions for change are extremely tenuous at best.
> 
> Better gameplay and knocking down one of the strongest antags (which is a midround) down a peg
> 
> > A decently geared traitor is pretty much on parity with a ninja they just lack stealth and a jaunt ability.
> 
> > **they just lack stealth and a jaunt ability**
> 
> The ability to dash is one of the major reasons ninja stands atop all other antagonists on par with a wizard. Being able to sit comfortably at 20 alpha is also very helpful, but not as impactful as jaunting.

So all this boils down to, if I honestly check my notes here.
"I think." 
Because anything you have put forward is not conducive enough to give ninjas a nerf.  What is the ninja receiving to compensate for being locked into 100% energy forever. I remember when Ninja was only locked to 100% energy, while ninja is fun having to retreat into maint,solars, or sap and APC every 2 minutes because my energy net kills nearly a quarter of my charge isn't fun. The stamina damage katana on non-targets with a bit of hindsight sounds fine. Honestly could mean security doesn't need to try and instantly kill the ninja anymore.

I'd rather you give ninja 250 or 300% energy reserves so they can be an active threat if they come into existence. This means they aren't gimps because they EMP'd and threw a net because it sounded like a good idea. Give them a martial art too, hell give them sleeping carp. I've had the utter pain of playing ninja when the grav gen literally having been eaten by a Singlo or something. You think you're powerful til the only movement tech you have is jaunting.

**Comment by ynot01** [comment]
> Because anything you have put forward is not conducive enough to give ninjas a nerf.

If you do not think the ninja is overpowered in its current state, then we will simply have to agree to disagree.

> You think you're powerful til the only movement tech you have is jaunting.

"the only" while you describe the most powerful form of movement in SS13 short of a cross-station teleport, not to mention the permanent speed boost

**Comment by Moja10** [comment]
Not to be an ideas guy but if you are determined that they shouldn't be able to upgrade a cell or charge from a cell, they should have an additional backup unrechargable battery that they can drain from in emergency situations, a reserve in case of danger. I would really really not like to see a ninja just eat shit and die from a lack of charge just because a fight or chase lasted longer than 1 minute, and they no longer have any ability to deal with this besides succing APC or SMES. 

I also agree that a ninja doing a couple of ninja actions for 30 seconds before hiding in maint succing an APC for two minutes sounds really boring.

**Comment by ynot01** [comment]
> they should have an additional backup unrechargable battery that they can drain from in emergency situations

You can very easily pick up a power cell, store it in your backpack, and use it for charging when need be

> I also agree that a ninja doing a couple of ninja actions for 30 seconds before hiding in maint succing an APC for two minutes sounds really boring.

Charging from an APC takes seconds, not minutes

**Comment by Moltijoe** [comment]
Ynot can see the balance council thread so this is more so for anyone else curious as to why it was denied
General idea is that it overnerfs ninja in a way that just makes it less interesting of an antag

**Pull request closed without merging**
