### PR TITLE
Oakeditshourrequirementsbecauseapparentlynooneelsediditinalmosttwomonths

### PR DESCRIPTION
**Pull request by Oakboscage**
### Intent of your Pull Request

Updates job hour requirements according to "new" council legislation:
https://forums.yogstation.net/index.php?threads/vote-make-heads-of-staff-require-12-hours-of-department-time.18847/
https://forums.yogstation.net/index.php?threads/vote-raise-minimum-required-playtime-for-security-roles.18893/

#### Changelog

:cl:  
tweak: Hour requirements tweaked 
experimental: As usual I have no clue what I'm doing  
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Wtf is space key?

**Comment by MegaEmpirical** [comment]
Oh god, I didn't realize these never got added. Explains a few things.

**Comment by Bibby0110** [comment]
shitcode

**Review by Altoids1 — CHANGES_REQUESTED** [review]
Immodular. Please change these values via separate files in the /yogstation/ folder.

**Comment by Oakboscage** [comment]
> Immodular. Please change these values via separate files in the /yogstation/ folder.

What's wrong with it being immodular?

**Comment by Altoids1** [comment]
https://github.com/yogstation13/Yogstation-TG/blob/master/yogstation/README.md

**Pull request closed without merging**
