### PR TITLE
Someone took out my motion camera. I blame weje.

### PR DESCRIPTION
**Pull request by JamieD1**
# Github documenting your Pull Request
Motion cam to caps. As it should of been from my original PR.

# Wiki Documentation
n/a

Changelog
🆑
tweak: Added motion cam to captains as it should of been.
/🆑

### CODE REVIEW

**Comment by adamsong** [comment]
Missing some maps

**Comment by patpol4** [comment]
We can bargain and you wont have to change it on omega if you remove it

**Comment by alexkar598** [comment]
You changed the name of the camera

**Comment by patpol4** [comment]
Eclipse

**Comment by JamieD1** [comment]
> Eclipse

C a n t - M a k e - M e

**Review by adamsong — DISMISSED** [review]
Eclipse

**Review by patpol4 — CHANGES_REQUESTED** [review]
Eclipse and template

**Comment by JamieD1** [comment]
Eclipse Does not have the Spare Cabinet on it. So doesnt need motion tracker.

**Review by patpol4 — APPROVED** [review]

**Pull request merged**
