### PR TITLE
More snowflake items - Boxta

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Two new snowflake items for Boxta.

 A Falcon on a Pauldron, neck slot
 And a Gold / Black fedora, hat (duh)
 
 Comes in a box like any other person gets for multiple items

# Spriting

image
image
image
image
image

https://user-images.githubusercontent.com/74586965/216737034-8c3e3f93-a3a7-4617-a092-28a43dc4eab6.mp4

https://user-images.githubusercontent.com/74586965/216737039-7e25c21f-2cff-4779-ac62-e66495d92d48.mp4

https://user-images.githubusercontent.com/74586965/216737041-85503941-df49-4224-8898-9f8b293f6e49.mp4

https://user-images.githubusercontent.com/74586965/216737044-a08c65a5-b159-4fbe-af07-2b18d8a7cdfb.mp4

# Changelog

:cl:  
rscadd: New donor items, falcon and pauldron + black/gold fedora
imageadd: Sprites and stuff for the aforementioned items
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
M'lady

**Comment by Mantlecrawler** [comment]
hmm you should make the fedora have a funny suicide message
"tips their fedora, instantly being smited and turned to dust!"

**Review by cuackles — APPROVED** [review]
Partial review the gold fedora it's ok

**Comment by MajManatee** [comment]
> hmm you should make the fedora have a funny suicide message "tips their fedora, instantly being smited and turned to dust!"

/obj/item/clothing/head/fedora/suicide_act(mob/user)
	if(user.gender == FEMALE)
		return 0
	var/mob/living/carbon/human/H = user
	user.visible_message(span_suicide("[user] is donning [src]! It looks like [user.p_theyre()] trying to be nice to girls."))
	user.say("M'lady.", forced = "fedora suicide")
	sleep(1 SECONDS)
	H.facial_hair_style = "Neckbeard"
	return(BRUTELOSS)

already exists

**Review by ToasterBiome — APPROVED** [review]
sprites look good

**Pull request merged**
