### PR TITLE
Adds reagent canisters that are orderable from cargo

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request
Kinda 50/50 on this PR but this would make it easier to add more chemical effects and push things away from just being a click in sequence game.

Considering making smaller 250-500u variants

Adds 4 2500u reagent canisters (and removes two chems from the chem machine)

The numbers are a little arbitrary but so are half of the games values
- iron: 5000cr
- plasma: 8500cr
- gold: 7500cr
- uranium: 8000cr

Removes iron and gold from the chem dispenser (why was this added?) might make them emag reagents
Removes solidification reactions due to being impossible to reasonably balance. (as in either material exports would need to be nerfed or crates made _way_ more expensive)

Causes a chem splash when broken

# Spriting
image

# Wiki Documentation

Add to cargo crates section

# Changelog

:cl:  
rscadd: Added orderable reagent canisters to cargo
rscdel: Removed iron and gold from chem machine
rscdel: removed gold and plasma soldification
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
I hate that balance of late has shifted to "lets make this one job really hard to play because I dont like it"

**Comment by MegaEmpirical** [comment]
It's an interesting idea, currently chemists are only really gated by time which is mitigated with upgrades. I'm up for trying this. No idea if the numbers are good or not but those are easy to tweak.

**Comment by Cartlord** [comment]
Unatomic & weird. I'm in favor of removing pure iron & gold from dispensers, but I feel like that alone keeps solidification from being overpowered, and removing solidification which also makes certain plants like gold apples worthless.

**Comment by Bibby0110** [comment]
Come back moogle :(

**Pull request closed without merging**
