### PR TITLE
[BOX] The Great Bar/Kitchen Redesign

### PR DESCRIPTION
**Pull request by neeshacark**
# Document the changes in your pull request

Redesigns Bar/Kitchen with the sole goals of A) Making people need to be near the bar to get food, to hopefully get barman some interaction.  B) Giving more room for two chefs to work without stepping on each others toes.

A new minor hall is added between Fitness and Bar.  Bar and Kitchen are both heavily redesigned.

This also nukes all Bar templates (see why this is good for the game for reasoning)
image

# Why is this good for the game?
This will hopefully encourage players to spend some time with the barman by forcing them to be next to him to consume their meal.  It also makes the 2 chefs not hate each other if they don't get along due to them having enough appliances for both of them.

The removal of the templates, this is something that was talked about among the maptainers and biome.  In general, the majority of the bar templates were either outright bad, one off jokes that aren't funny anymore or extremely mild changes.  In order to have kept them, I would have had to do extreme amounts of work for things that really - weren't worth the trouble.

# Changelog

:cl:  cark, azzzertyy
mapping: Redesigns Box's bar/kitchen, nukes all the old templates and moves theatre north to fitness.
/:cl:

### CODE REVIEW

**Review by ToasterBiome — DISMISSED** [review]
image
I dont like these 1 tile walkways by the tables, players will get stuck when more than 1 person is over there.

image

I'm also not a fan of this connection. I'd rather it be put back to maintenance. 

image
There should be more vents in this area.

image
Blinds are not consistent, nor are the airlock types (1x1 and 2x1)

Not seeing any air alarms, or light switches. I think bartender should have a way to get in from the tables still. 

image

Might as well put some chairs here for  "RP".

image

You could walk over the edge of the stairs, the sides need railings at least.

Overall I like the design, just a few issues.

**Comment by ToasterBiome** [comment]
image
This table and chair might be cuter here.

**Comment by neeshacark** [comment]
i should've just left the old template code in jeebus

**Comment by azzzertyy** [comment]
i really like the design, and love the connection between bar and dorms (its a connection that makes logical sense)
id like it fi you kept the code for bar changing in though, although i agree most of them sucked, id like to bring atleast a few of the good ones back.

**Comment by neeshacark** [comment]
> i really like the design, and love the connection between bar and dorms (its a connection that makes logical sense) id like it fi you kept the code for bar changing in though, although i agree most of them sucked, id like to bring atleast a few of the good ones back.

i would not get too attached to the hall, biome and the balance council are going to roast me over a fire over it because it fucks over antags in their opinion

as for the code if I were to do that I'd just remake the PR, it'd probably just be easier to readd it yourself down the line it's only about 20 lines or so that you can just copy and paste back in using this as ref

**Comment by azzzertyy** [comment]
image
add ramp middle all along the elevated section

image
solution to keep artists area and have theatre near the bar like god intended?

**Comment by azzzertyy** [comment]
> > i really like the design, and love the connection between bar and dorms (its a connection that makes logical sense) id like it fi you kept the code for bar changing in though, although i agree most of them sucked, id like to bring atleast a few of the good ones back.
> 
> i would not get too attached to the hall, biome and the balance council are going to roast me over a fire over it because it fucks over antags in their opinion
> 
> as for the code if I were to do that I'd just remake the PR, it'd probably just be easier to readd it yourself down the line it's only about 20 lines or so that you can just copy and paste back in using this as ref

i have no idea how having a hallway there has anything to do with balance in the slightest

**Comment by Moltijoe** [comment]
> i have no idea how having a hallway there has anything to do with balance in the slightest

the idea is that connections between areas can affect antags ability to get around unnoticed

**Comment by azzzertyy** [comment]
image

add railing corners here (i think this is the standard?)

**Comment by ktlwjec0** [comment]
please add disposals to the kitchen

**Comment by neeshacark** [comment]
> please add disposals to the kitchen

oh yeah good point

**Comment by Therandomhoboo** [comment]
I'll be honest, I am not a big fan of this for a couple of reasons

1) I find it rather bland now the templates are gone, the small differences in the layout even though you guys find them shit, I find them fine and a nice breather from just going into the same bar layout constantly and just being a cookiecutter basic part of it all

2) The chef has a very quick access in and out of their area whereas barkeep have to go up into their backroom to get into the bar area and then up and back out via their backroom to get out, its very extra and basically stiffs the barkeep if anything goes down, they will have to risk jumping the table or go around which by then anyone that is fucking with them (or their monkey for instance) and by the time barkeep comes around they can easily just get out and piss off.

3) The bar & kitchen area are quite up into the area itself which yes its nice that the kitchen serving area and the barkeeps part are next to each other so people can give more interactions but where its more up inside, I feel that people will interact less because its just too tucked away.

4) The fact that the bar is nowhere near maints and the aforementioned awkward get out means that any sec suspects the barman or wants to come for them, or antag wants them dead the barman is virtually trapped.

This is more love to the chefs really, I don't see anything at all beneficial or good towards the bartenders. Yeah the interaction will be more but the downsides are too much.

**Comment by ktlwjec0** [comment]
also a meatspike please, they are used often. honestly i'd just make a crate with cooking oil and put a spike there instead

drinks showcase should be public right?

**Comment by neeshacark** [comment]
> I'll be honest, I am not a big fan of this for a couple of reasons

Point by Point:

1. The templates were pretty unanimously agreed during the numerous discussions to not be worth keeping - there were too many and they were a maintenance nightmare.

2. I can see the argument for this and it is possible for me to put in a windoor - this was originally my intent but I found it looked bad and didn't view the benefit of saving 3ish seconds to walk around to outweigh the downside of it looking like ass.  I'll look back into it.

3. I'm not overly sure what the complaint is here, I think I get it but I don't see how this would make people interact less?  Not much I can do about this one.

4. Bar is still right next to maints, it just doesn't have a direct connection like it used to.  This is the case for a lot of roles, and even bartenders on other maps (meta).  I can certainly see the complaint about lack of exits, and am looking to rectify that in my next commit.

As for some of the complaints I've seen from you in the discord - the reason the kitchen got such a big size buff is due to there being 2 chefs.  If they don't get along, it is not fun to be crammed into the 7x7ish space (theres a table in the middle too) with them as they get in your way and steal your ingredients.  

Barman's size to me does not seem to be reduced except in the case of the spacious bar (which I never saw used anyway).  Their space is about the same as before, with extra traffic now due to a hallway through bar and the kitchen right next to it.  The amount of space needed for the creation of drinks by one person is nowhere near the the creation of any food (which uses multiple machines) by two people.

New commits incoming soon.

**Comment by neeshacark** [comment]
> also a meatspike please, they are used often. honestly i'd just make a crate with cooking oil and put a spike there instead
> 
> drinks showcase should be public right?

I left it out because it serves to the best of my knowledge - no purpose other that putting cows and goats on them so they don't move around while you milk them (you make new meatspikes for this anyway)

The cooking oil seems much more valuable to me, given how fast I see people go through the fryer oil on certain rounds.

**Comment by neeshacark** [comment]
Meatspike added, bar has more exits, theatre moved back into bar (I actually did this one last night just didnt image update)

**Comment by Therandomhoboo** [comment]
Well looks like this will be going in anyway which is a bittersweet moment but I will say thank you for giving barkeeps a way to get in and out.

1. I wont lie out of the mappers, maintainers and balance council I don't see anyone that mainly plays in the bar area/kitchen area (Maybe one but I'm not sure) so whilst you guys all agree with that its the barkeep players that have to deal with it. I understand how much anguish it is to maintain it and try to update it but really I enjoyed the different layouts because it made the job not stale despite having no interactions. The different layouts also was good because of the bar sign which you could combine together to give the "right atmosphere" but that is imo. 

2.  Appreciate the windoor addition, I understand the other door being there due to lack of connection to maints (which I will answer in point four) but I'm a bit iffy if this won't cause people to mess with the door prompting barkeeps to open it and letting them into his area. This isn't a major issue though and I think really the only way to find out is in action so its just more of a minor whine from me.

3. So what I was saying about this part of potentially lesser interactions than norm is that the bar area/bar could be seen right from the doors and wasn't that much far into the area meaning people would see the barkeep, the drinks and what not easier. This requires people to actually enter and go up to get a glimpse of the barkeep/chef at all and it feels to me we've been tucked further back from the public eye. However, this is same as point 2, I don't know how exactly it will affect it till it is at least seen and I can be wrong in that.

4. So this is what I'm iffy on. Whilst I appreciate the extra door way. One of them leads into the public eye and the other requires you to go through 3 doors to get to maints if you were lets say confronted at the bar. By the time you would reach the maints, the person would already be in your way, and whilst we have the public central hallway to easily jump out of, its very much out in the open meaning everyone will see you if they know you're bad. I liked the maints being connected to the barkeeps backroom just because the maints are dark and so it's easier to navigate through (even though everyone knows the layout) to dupe sec or whomever. Also if anyone was gunning at you, you had a way to basically hide away by running off into maints.

As one of the main service players, and a barkeep main to me. Whilst I get chefs need mor space feels like I'm more of a side-character to please the kitchen players. Our area feels more bland and the standard cookiecutter as the rest of the others. I would honestly like a few machines in there like arcade and slots ones. Plus now there is no real room for anyone to build rage cages or dance flooring (barkeeps get the equipment to do so such as glass, metal & cables) without it taking up the majority of space.

All in all, I appreciate your efforts really to make it better .

**Comment by neeshacark** [comment]
I will see what I can address of that, I don't see the 'inwardness' being a detriment to people being there.  People need food, and plus the hall running through will also increase foot traffic.

The primary reasoning barman got put where he did was due to spacing issues.  I could in theory fix it, but it'd probably have to be in a later PR because I do imagine that would require me to move a lot of stuff (hydro, library, chapel, evac, maint) which is a pain to manage in this PR.

**Comment by Therandomhoboo** [comment]
> I will see what I can address of that, I don't see the 'inwardness' being a detriment to people being there. People need food, and plus the hall running through will also increase foot traffic.
> 
> The primary reasoning barman got put where he did was due to spacing issues. I could in theory fix it, but it'd probably have to be in a later PR because I do imagine that would require me to move a lot of stuff (hydro, library, chapel, evac, maint) which is a pain to manage in this PR.

All fine, like I said for points 2 & 3 these can't really be confirmed until we see it in game so they're more how I feel it may go than actual points that need addressing. I did think of saying shift everything to the right but that seems like it would be a ton of work which I'm not expecting you to do really but thank you for hearing me out on my opinions on this.

**Comment by Moltijoe** [comment]
If clerk wasnt a template, bar and clerk could get a shared mini maint that would give them a different option to escape

**Comment by azzzertyy** [comment]
> If clerk wasnt a template, bar and clerk could get a shared mini maint that would give them a different option to escape

this wouldnt be hard to do considering that clerk on meta has a maint there that used to be connected, just had to be severed to support both box and meta. you could probably add it back with this though

**Comment by ktlwjec0** [comment]
the left-most curtains should probably be removed. air alarm outside theatre needs moving since the painting will cover it from an AI POV. fire alarm below the bar is upside down. no vents or scrubbers in kitchen. needs corner decal by kitchen maint door. should have a drinks showcase for the department goal of having drinks in it? chefs really need a condimaster for separating stuff, making condiment packets, things like that and i dont see one now (this is very important). I'd move light switches nearer to doors so they're easier to find in the dark instead of in random places. I don't think the bartender needs a door directly into the hallway, they just needed the windoor by the tables which they now have. paper cups aren't needed since the water cooler dispenses them. i'd add something above the kitchen in maint, like a single trash spawner at least, it's really bare which feels out of place considering the entirety of that maint is cluttered. bartender needs a requests console

**Comment by neeshacark** [comment]
> the left-most curtains should probably be removed. air alarm outside theatre needs moving since the painting will cover it from an AI POV. fire alarm below the bar is upside down. no vents or scrubbers in kitchen. needs corner decal by kitchen maint door. should have a drinks showcase for the department goal of having drinks in it? chefs really need a condimaster for separating stuff, making condiment packets, things like that and i dont see one now (this is very important). I'd move light switches nearer to doors so they're easier to find in the dark instead of in random places. I don't think the bartender needs a door directly into the hallway, they just needed the windoor by the tables which they now have. paper cups aren't needed since the water cooler dispenses them. i'd add something above the kitchen in maint, like a single trash spawner at least, it's really bare which feels out of place considering the entirety of that maint is cluttered. bartender needs a requests console

can you use paragraphs in future

**Comment by neeshacark** [comment]
@ktlwjec0 all requests addressed except removing the door to the hall (barman needs escape options because he cant run into maint, requested by multiple people) and the removal of curtains (i dont see why i would)

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
