### PR TITLE
Allows emitters to mine rocks

### PR DESCRIPTION
**Pull request by Altoids1**
image

Right now it has a 50% chance of actually mining the rock per hit. This value can be lowered if this gets powergamey.

#### Changelog

:cl:  
rscadd: Emitters can now mine rocks!
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
More features for aux base. Yey

**Comment by HomocidlePancakes** [comment]
Should have a 100% chance to mine 2 at a time tbh. Manual mining is just so strong that you won’t even consider using emitters unless you use them to idly mine/clear out terrain while you work on some autismo project at aux.

**Comment by oklews** [comment]
Unless you are using like twelve emitters at once, a cutter can overpower it easily, make it more worthwhile like doing two or more tiles at once.

**Comment by Altoids1** [comment]
We'll see how things are once this is actually in the game.

**Pull request merged**
