### PR TITLE
bromine does brain damage now

### PR DESCRIPTION
**Pull request by boodaliboo**
image
bromine causes brain damage irl
tell me if you think it should do less brain damage
#### Changelog

:cl:  
tweak: bromine now does a minor ammount of brain damage
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Not sure if it's a good idea since bromine is a common disease cure (in game)

**Comment by Jarod1200** [comment]
Bromine is easy to get for disease cures and Mannitol is also easy to get so i don't really see an issue with this. Also if they cure one guy with bromine they can make a vaccine if mannitol is that hard to get.

**Comment by Marmio64** [comment]
virus powercreep

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
It works like this IRL is a bad reason to change things

Real life is boring, we are making a game.

**Pull request closed without merging**
