### PR TITLE
Zombies are now stun immune

### PR DESCRIPTION
**Pull request by fluffe9911**
### Intent of your Pull Request
Make zombies stun immune so you cant just spam wack a zombie with a stun baton to murder it

:cl:  
tweak: Zombies are now stun immune
/:cl:
If enough people hate this change im probably just gonna close it

### CODE REVIEW

**Comment by boodaliboo** [comment]
good change

**Comment by maxion12345** [comment]
Aren't they already stun resistant

**Comment by Marmio64** [comment]
> Aren't they already stun resistant

a single stun baton hit is still long enough to cuff them

**Comment by maxion12345** [comment]
I'm mainly afraid that this will turn zombies from "extremely fucking dangerous but containable if you have a surgeon and a way to kill or capture" to "we can't stun them, all we can do it throw floor tiles at them as they walk towards us". 

At most this will be an excuse to authorize lethals whenever the "unknown creature" event triggers. Normal sec gear can't stop em anymore...

**Comment by JamieD1** [comment]
Seriously, zombies are supposed to be slow and bits should be falling off..

https://www.youtube.com/watch?v=uLquz4Iz-30

It should be easy to decap their head with a blunt object..

**Comment by Marmio64** [comment]
> I'm mainly afraid that this will turn zombies from "extremely fucking dangerous but containable if you have a surgeon and a way to kill or capture" to "we can't stun them, all we can do it throw floor tiles at them as they walk towards us".
> 
> At most this will be an excuse to authorize lethals whenever the "unknown creature" event triggers. Normal sec gear can't stop em anymore...

good, throw floor tiles at them to get them,  a stick shouldnt be instantly demolishing a zombie in one hit. Unidentified lifesigns detected can also mean spiders not a zombie and it could just be a false alarm too.

**Review by JamieD1 — APPROVED** [review]

**Comment by Hopekz** [comment]
They already get a 1.6 speed mod.
At least make them slower now that you can't stun them. This is like trying not to get hit by a hulk except when you get hit once you're infected

**Comment by alexkar598** [comment]
They are already snowballing every single round where they exist. They dont need a buff

**Pull request closed without merging**
