### PR TITLE
Changes admin logging due to abuse.

### PR DESCRIPTION
**Pull request by Bibby0110**
[REDACTED]

### CODE REVIEW

**Comment by JamieD1** [comment]
:thonk:

**Comment by Bibby0110** [comment]
> :thonk:

Above your security clearance, sorry pal.

**Comment by alexkar598** [comment]
Since the start of the month of june (2021-06-01), this log has been fired 29 times, out of these 29 times, i could only not find reasoning for 2 of them. The message is way too aggressive and hostile for an event with a high false positive rate

**Comment by Bibby0110** [comment]
> Since the start of the month of june (2021-06-01), this log has been fired 29 times, out of these 29 times, i could only not find reasoning for 2 of them. The message is way too aggressive and hostile for an event with a high false positive rate

:)

**Comment by adamsong** [comment]
Sufficient reasoning for this change has not been provided

**Pull request closed without merging**
