### PR TITLE
Should make Strange Reagent need at least 10u to work

### PR DESCRIPTION
**Pull request by JamieD1**
# Github documenting your Pull Request

Should make Strange Reagent need at least 10u to work

# Wiki Documentation

Strange Reagent need at least 20u to work update chemistry and medicine and shit

# Changelog

:cl:  TheGamerdk, with a tiny amount of help from JamieD1
tweak: Strange Reagent need at least 10u to work
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
sr was already nerfed to do cell damage which requires you to be in cryo for a while, making defib more viable if you can defib, and besides 20u is far too much

**Comment by Anvilman6** [comment]
Maybe try setting it to 10u before the powergamers burn everything down

**Review by Bibby0110 — APPROVED** [review]

**Comment by adamsong** [comment]
SR already does a bunch of clone damage, and a better balance would be to just increase that to guarantee crit

**Comment by adamsong** [comment]
Drop this to 5u and merge #12118

**Comment by JamieD1** [comment]
Will drop to 10u if I get 15 downvotes.

**Pull request merged**
