### PR TITLE
Revert "Adds a totally innocent Giant Medical Dog Donor Skin" on the basis of being fetish content

### PR DESCRIPTION
**Pull request by alexkar598**
Im like, the most degenerate person on earth and even that's too much for me. Can we not port vore borgs....

I heavily recommend reverting this PR because we will look like absolute fools for this shit

### CODE REVIEW

**Comment by JamieD1** [comment]
Its not a fucking Vore Dog you spastic.

**Comment by Mqiib** [comment]
Please do

**Comment by patpol4** [comment]
It's a robot dog

**Comment by Hopekz** [comment]
How is this any different than adding a nyah cat person donor race. 
This won't do anything to make us look like "absolute fools" because we've already crossed that line in other places.

It's a robotic dog.

**Comment by yacabo** [comment]
How in the fuck was that PR not a meme?

**Pull request closed without merging**
