### PR TITLE
Ports techpriest robes to the ChapDrobe

### PR DESCRIPTION
**Pull request by maxion12345**
# Github documenting your Pull Request
le porte: https://github.com/tgstation/tgstation/pull/45365
Adds techpriest robes to the ChapDrobe.
# Wiki Documentation

# Changelog

:cl:  Floyd / Qustinnus, Arathian
rscadd: Added techpriest robes to the ChapDrobe
/:cl:

### CODE REVIEW

**Review by nesisknesis — COMMENTED** [review]
Unfortunately, I don't think these clothes bode well in context. What I mean is, they don't fit within the scope of "Roboticist clothing on a space station". I'm probably known for not liking clothes but this is generally the main reason; out of context and lackluster reference. 

As for the items added to the drobe, I don't think non-clothing items should be added to wardrobes. However, they would be very much viable in a separate PR.

I will leave this PR open for a few days.

**Comment by maxion12345** [comment]
> Unfortunately, I don't think these clothes bode well in context. What I mean is, they don't fit within the scope of "Roboticist clothing on a space station". I'm probably known for not liking clothes but this is generally the main reason; out of context and lackluster reference.
> 
> As for the items added to the drobe, I don't think non-clothing items should be added to wardrobes. However, they would be very much viable in a separate PR.
> 
> I will leave this PR open for a few days.

i'll put it into the chaplain's drobe instead so it fits with the tech sect and whatnot
although I still think that it'll primarily be used by roboticists

**Review by nesisknesis — COMMENTED** [review]
Okay that works, though may you put the item additions to the robodrobe in a separate PR, I still think any non-clothes shouldnt be in the wardrobe vendors so I won't merge it here.

And, if this is a port, please put a link to the original PR in the description and credit the author.

**Comment by Marmio64** [comment]
yeah this is way more fitting for the chaplain to use, it looks too crazy for a relatively 'sane' person like a roboticist to be wearing.

**Comment by JamieD1** [comment]
corn flakes

**Comment by maxion12345** [comment]
I'll fix this later

**Comment by maxion12345** [comment]
@grimm-hollowknight is done

**Review by nesisknesis — CHANGES_REQUESTED** [review]
image


image

**Comment by maxion12345** [comment]
god dammit

**Comment by maxion12345** [comment]
wrong helm dammit

**Comment by maxion12345** [comment]
ever since we updated to that new byond version everything has been 
MERGE CONFLICT
MAP ERROR
HAHA IM GONNA DELETE THESE ICONS FOR NO FUCKING RASIN

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
