### PR TITLE
Replaces plasma windows on the singlo engine with reinforced ones

### PR DESCRIPTION
**Pull request by fluffe9911**
Apparently they were blocking rads or something so this should fix it I think

### CODE REVIEW

**Comment by monster860** [comment]
fluffe

I just looked at the code

normal windows have some rad block
reinforced windows have a shit ton of rad block
plasma windows have...... no rad block.

**Comment by fluffe9911** [comment]
oh

**Comment by fluffe9911** [comment]
Now that the rad collectors are inside we can replace the windows with reinforced so rads stop leaking out everywhere

**Comment by jcatjmeow** [comment]
Outside you mean

**Comment by ByteSizedBee** [comment]
they are now right outside next to the field generators. Changing the glass should hopefully stop engineering being a radiated wasteland

**Comment by monster860** [comment]
Can't you just, like, close the shutters?

Also this PR doesn't work any more, you only modified the plasma windows that don't have shutters.

**Comment by ByteSizedBee** [comment]
The shutters don't have any rad insulation

**Pull request merged**
