### PR TITLE
sends the raven cruiser back to hell

### PR DESCRIPTION
**Pull request by ofscarletdreams**
breaks roundend because ???????? shuttle code

### CODE REVIEW

**Comment by ShoziOffical** [comment]
i brought it back because i thought it broke atmos only

**Comment by ShoziOffical** [comment]
and you sure only raven break the round-end and not other shuttles too?

**Comment by Bibby0110** [comment]
Literally not the reason round-end breaks

**Comment by ofscarletdreams** [comment]
then what IS

**Comment by ShoziOffical** [comment]
> then what IS

something is returning in code could be antags that make round not possible to be ended

**Comment by ShoziOffical** [comment]
i tried to test the raven cruiser on my private server and there was no runtime

**Comment by Bibby0110** [comment]
> then what IS

Something is making SSTicker sleep

**Pull request closed without merging**
