### PR TITLE
Locks sleepers and cryo tubes behind medical machinery access

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Adds a new access, medical machinery, which is granted to medical personnel and allows operation of sleepers and cryo tubes.
Its new access because medical sec officers already get a lot of med access, and I didn't want them to have access to sleepers, and removing their access is out of scope for this PR.

Alternative to #12214

# Wiki Documentation

This needs noted on the sleeper and cryo tube entries

# Changelog

:cl:  
rscadd: Added medical machinery access
tweak: Locked sleepers and cryo tubes behind medical machinery access  
/:cl:

### CODE REVIEW

**Comment by Jarod1200** [comment]
This is better. Is it still possible to open and close them as non medical? If not can you resist out of them as you could before with cryo

**Comment by adamsong** [comment]
> Is it still possible to open and close them as non medical?

Sleeper, yes, cryo pod, no

> If not can you resist out of them as you could before with cryo

Sleepers you can still just move out of, and you can resist out of the pods

**Comment by Moggram** [comment]
ummmm... should cloning pods get this access to?

**Comment by adamsong** [comment]
Possibly, I'm not sure on that one though, it would make more sense for it to be cloning access though

**Comment by azzzertyy** [comment]
cryo should really still be able to be used as its not effective but if someones about to die its the only real way to stop it, with cryo using this as well its too likely to just cause deaths

**Comment by adamsong** [comment]
I don't want to encourage people dragging bodies away from doctors to shove in the tubes

**Comment by Marmio64** [comment]
this wont stop syndis from using their special syndicate sleepers, right?

**Comment by adamsong** [comment]
> this wont stop syndis from using their special syndicate sleepers, right?

Of course

**Comment by overlord12345** [comment]
can they be hacked?

**Comment by adamsong** [comment]
No

**Comment by Hopekz** [comment]
> with cryo using this as well its too likely to just cause deaths

Dying is a part of the game (:

**Comment by Moggram** [comment]
So free miners, the ancient space station crew and I thank free golems all have sleepers. They may need to be changed out for med-kits.

Also just checked, Bluespace Shelter Capsule for miners have them to....

**Comment by Sniblet** [comment]
There are a lot of situations where medical doctors are not physically or mentally present enough to operate a sleeper, such as every single round that doesn't have at least one veteran player in the medbay, or abandoned station and free golems (who both like to make their own sleepers)
When someone is foiled by not being allowed to use the sleeper they're usually not just going to go "well, guess it wasn't meant to be" and give up. They'll tide into chemistry or surgery to get what they need done

**Comment by JamieD1** [comment]
With the sleeper changes this not going to be a thing.

**Pull request closed without merging**
