### PR TITLE
Makes cosmic ashwalker ruin unpickable

### PR DESCRIPTION
**Pull request by AsV9**
:cl:  
rscdel: Made the cosmic ashwalker ruin stop spawning automatically.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
I did it.

**Comment by Altoids1** [comment]
There goes 1 of the like 3 roles that are still fun to play for me anymore

**Comment by SomeguyManperson** [comment]
imagine removing a ruin because miners can't fight a lizard  that can wear shoes B)

**Comment by MegaEmpirical** [comment]
What prompted this?

**Comment by HomocidlePancakes** [comment]
Me

**Comment by MegaEmpirical** [comment]
I'm aware but I've not seen the specifics.

**Pull request merged**
