### PR TITLE
DNA fixing surgery

### PR DESCRIPTION
**Pull request by Darkstick**
### Intent of your Pull Request

This PR adds an advanced surgery that allows to treat crew members that were absorbed by lings using rezadone, allowing you to clone them.

Lings are encouraged to kill random crew members, so I feel like it's unfair for them to have a permanent kill ability ready to be used anywhere they go. I've been told this was so the lings could better impersonate crew they absorb, but I just don't buy it. Lings shouldn't have a 100% foolproof disguise, and the antag itself could be more interesting if impersonation went wrong and suddenly there's two Georges and nobody knows which to shoot. _I found you, faker!_

#### Changelog

:cl:  
rscadd: Adds DNA repair surgery under advanced surgery
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
> and the antag itself could be more interesting if impersonation went wrong and suddenly there's two Georges and nobody knows which to shoot. I found you, faker!

Except this wouldn't happen if one of them literally just got revived back to life using surgery

**Comment by Smudged** [comment]
I like the idea of removing permanent death mechanics from the game so it's certainly a +1 from me.

Some issues i do see are with what ling pointed out, it does make the disguises weaker, I'd almost recommend adding back the transform sting back if this does go through even if that is just also an obnoxious mechanic

**Comment by Darkstick** [comment]
> > and the antag itself could be more interesting if impersonation went wrong and suddenly there's two Georges and nobody knows which to shoot. I found you, faker!
> 
> Except this wouldn't happen if one of them literally just got revived back to life using surgery

Lings getting metaed happens without revival. It's not hard to connect the dots after finding a husked guy in the middle of maint, and often you can recognize who they are via underwear/race.

**Comment by Sir-Lagsalot** [comment]
Once I was killed by a ling but he had the decency to decapitate me before finishing me off, so I ended up getting cloned. Ended up being really fun, actually. See, the thing about the "Oh but it will ruin their disguise!!!" argument is that lings have, shock horror, _multiple disguises_ most of the time, so this guy just kept swapping around to keep people guessing. Perhaps bringing back DNA sting would be interesting, though. Anyway, good PR, congrats on doing one, etc.

**Comment by ghost** [comment]
you can already do brain transplants to revive ling victims

**Pull request merged**
