### PR TITLE
fixes some issues in infiltrator base

### PR DESCRIPTION
**Pull request by patpol4**
# Document the changes in your pull request
???
firefox_FFQO1XuDWY
Also some other issues
# Changelog

:cl:  
mapping: fixes weird turf on cc zlevel
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
actually there are way more fixes to do here

**Comment by MajManatee** [comment]
he doesnt know

**Comment by patpol4** [comment]
No reason not to fix maps that actually load on every round

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
where did griddle go?

**Comment by patpol4** [comment]
the griddle was one of the bugs, its an airlock

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
add griddle somwehere..

**Comment by patpol4** [comment]
They dont have steak???

**Comment by patpol4** [comment]
Griddle added back

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
