### PR TITLE
Reverts a PR that nich deliberately mistitled to make it seem reasonable

### PR DESCRIPTION
**Pull request by ghost**
adrenalin sacs will now provide the adrenalin to changelings again that gives them a minor stun resist per usual for adrenal injections

### CODE REVIEW

**Comment by Amelia0010** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/2341

Please explain how this was mistitled you absolutely insufferable cunt

@ThatLing Love you ❤️ 

@ThatLing still love you ❤️

**Comment by ShadowDeath6** [comment]
it was mistitled because it doesn’t prevent them from being stunned entirely, it’s a minor stun reduction

**Comment by Amelia0010** [comment]
"minor"

It gives you 10 units of lingadrenaline, which removes 2 seconds worth of stun every 2 seconds
So this "minor" reduction, is actually it halfing it completely.

And It lasts between 40 and 62.5 seconds

>Amount removed is metabolization rate(chemical) / metabolization efficiency (owner)
The owner's metabolizationeffieciency changes depending on how well fed they are, ranging from 1.25, to 0.8, with a default of 1
The metabolization rate is 0.4
So the amount removed every 2 seconds is as follows:
Fat/default: 0.4/1 = 0.4
Hungry: 0.4/0.8 = 0.5
Well fed (and with high satiety): 0.4/1.25 = 0.32
So since it ticks every 2 seconds, and we have 10 units to remove this is how long it takes:
Fat/default: (10/0.4) * 2 = 50
Hungry: (10/0.5) * 2 = 40
Well Fed (and with high satiety): (10/0.32) * 2 = 62.5


So if you're well fed and have a high satiety, you get a 50% reduction in all stuns for a full minute. This is not minor. 

And it's a bit far to say that I "deliberately mistitled it to make it seem reasonable". I'll be more than willing to admit that I overexaggerated how powerful it is, [but you have also exaggerated things in PR titles recently,](https://github.com/yogstation13/Yogstation-TG/pull/2074) so using that as your only reason for having this merged is really fucking thonk-worthy

**Comment by ShadowDeath6** [comment]
The difference between his title and yours is that your title is worded in a way that implies you are removing stun immunity while his is dumb meme shit that says nothing without looking at code or the pr body

**Comment by ghost** [comment]
it's tradition

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Even if the title could be misinterpreted, it's still a reasonable nerf.

**Pull request closed without merging**
