### PR TITLE
Ports Removes Hygiene from /tg/

### PR DESCRIPTION
**Pull request by nesisknesis**
/tg/ removed hygiene https://github.com/tgstation/tgstation/pull/44843

Hygiene is flawed and serves only as an annoyance. You don't shower, you get stink. Stink causes disease. The disease is also predominantly annoying due to being under-developed unlike a random event generated one.  

In comparison to a similar concept, food, is associated with a job, the cook, and has more depth to it with nutriment and types of food. However, hygiene lacks anything interesting. 

If you look in the comments of the original PR, you will see a statement from 🍊 s about a possible overhaul for hygiene in the future, and so may be ported if it is successful.

Further reasons to why hygiene is flawed:

- A statement from a local man: 
image

- Sentient disease can be denied victims due to having a disease caused by miasma.

- Green lines.

- Who the fuck likes miasma.

praise Garen7
#### Changelog

:cl:  Identification
del: Removes Hygiene
del: Removes NEET and neat quirks
del: Removes the ability for scangates to scan for hygiene
tweak: Garlic no longer makes you stink
tweak: Replaced the penalty on transcendent olfaction with the inability to use it when in any amount of miasma.
imagedel: Removed Stink Clouds
del: Deodorant is now redundant due to hygiene being removed.
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
epic

**Review by AsV9 — CHANGES_REQUESTED** [review]
Remove the deodorant from the maps

**Comment by Firewolf34** [comment]
I mean, I kind of agree, but at the same time how is the feature supposed to improve if it's not there to improve on?

Like, no one will add any new features to hygiene to make it better now that it is removed.

**Comment by nesisknesis** [comment]
> If you look in the comments of the original PR, you will see a statement from 🍊 s about a possible overhaul for hygiene in the future, and so may be ported if it is successful.

**Review by AsV9 — APPROVED** [review]

**Pull request merged**
