### PR TITLE
Revert "Medical sprays and patches now look for exposed flesh or thin material"

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Reverts yogstation13/Yogstation#8001
Hopek has said he's not planning on making these function properly with pierce immunity gained from things that aren't thick material because "that's intended"

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Speedmerge

**Comment by MegaEmpirical** [comment]
Not a fan.

**Comment by Reed0506** [comment]
this change was bad anyways because it removed the only reason to ever use patches and sprays while simultaneously breaking their functionality in a few specific cases such as the free golems are not able to USE THEIR MEDS.

**Comment by MegaEmpirical** [comment]
Slanderous lies. 

Patches and sprays still have uses: plasmamen. Other situations where removing a helmet/mask would not be favorable. Chems that are toxic or ineffective when ingested. Possibly dead bodies too, not sure if you can feed a dead body.

If no one is going to change golems then just give them pills instead.

**Comment by Hopekz** [comment]
local powergamer wants to revert the change the prevents him from healing in space through his hardsuit while pretending its because of free golems instead of adding a quick exception for his golem problem instead!

More news once it's merged
image

**Comment by JamieD1** [comment]
Fix golems instead. This is not getting reverted. Its overpowered for hard suit wearers.

**Review by JamieD1 — CHANGES_REQUESTED** [review]
See above

**Pull request closed without merging**
