### PR TITLE
Ork accent revamp (Correct edition)

### PR DESCRIPTION
**Pull request by Hopekz**
**EDIT:**
I must have been tired when I created this pull request because I uploaded the wrong version WIP mid-rework.
**I actually created 869 translations, not 395.** 
Changing description and changelog to reflect this.

----------

**Ork accent has been revamped.** 
From 129 translations to 869

I will be releasing these accents as I revamp them but Ork is the first revamp I finished.

Also; reworked the whole file to be organized in a more legible way for easy modification (now alphabetized)

#### Changelog

:cl:  Hopek
rscadd: Ork accent has been revamped. From 129 translations to 869
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
**Edit:** 
I must have been tired yesterday I uploaded the wrong version of the WIP mid-rework.
I actually created 869 translations, not 395.

Updated.

**Comment by Moja10** [comment]
Have of these are just making every word unintelligible and isn't exactly how Orks even speak. Think = fink, yet you have thinking = dinking. The overuse of apostrophes is annoying too because several words are just garbled into nonsense characters spaced by apostrophes. Saying this as an Ork fanatic

**Comment by Hopekz** [comment]
@Moja10 
Updated.
Can you take a second look?

**Comment by Hopekz** [comment]
Closing this PR for now as it has to be re-revamped for #7962 .
I would not be happy merging this PR using the old inefficient system.
Will wait until #7962 is merged before starting to work on this again.

**Pull request closed without merging**
