### PR TITLE
Adds local OOC

### PR DESCRIPTION
**Pull request by ThatLing**
Adds ((local OOC)).
- 7 tile radius
- Can be used by using the LOOC verb in the OOC tab or by using the hotkey (CTRL+L or L by default). 
- OOC bans/mutes also ban from LOOC.
- Can be globally enabled/disabled by admins.
- Can be enabled/disabled per client under ``preferences`` tab.
- Admins can see any LOOC wherever they are and it provides a handy dandy follow link.

Tested locally but needs a testmerge to make sure everything works.
Credits to OracleStation and https://github.com/SunsetStation/SunsetStation/pull/2.

🆑 steamp0rt, originally by FlattestGuitar
add: Adds LOOC!
/🆑

### CODE REVIEW

**Comment by Ratvar** [comment]
it's gonna be ((help me im dying)) and ghosts spamming your chat with "funny remarks" (unless you toggle it off, which prevents you from seeing useful data people send to you with looc) all over again?

I think admin ability to toggle looc off to dead/critted/stunned would be good if it's not in yet, but sounds like clutter.

What was wrong with say, "((so click the vase yeah))"? Say with brackets was looc with inbuilt no metagame already

**Comment by GenericDM** [comment]
all i can say is i hope it works

**Comment by Moja10** [comment]
Wait, can ghosts use LOOC to communicate with people alive and in game?

That would be my only gripe, I welcome this feature, thanks thatLing !!

**Comment by ThatLing** [comment]
@Ratvar 
This adds proper logging so admins can see LOOC logs instead of having to search for ``((...))`` in say logs, saving them a lot of times. Ick ock is not allowed using this and admins will hear any LOOCs. As far as the ghosts spamming memes, I'll disable it for ghosts considering everything they say is already OOC.

@Moja10 
I'll disable this for ghosts considering everything they say is already OOC.

**Comment by GuppyLaxx** [comment]
ew

**Comment by MimicFaux** [comment]
If this came from oracle code I I believe there's already a config for disabling it from dead/ghost/unconscious. Even observers (who are ghosts)

**Comment by ThatLing** [comment]
@MimicFaux 
Yeah, that's what I did

**Pull request merged**
