### PR TITLE
Revert "Reduces Reagent Capacity of Pills to 10u" This removes one of the few late game tasks chemists can do which is making insane one off healing pills

### PR DESCRIPTION
**Pull request by milk-is-cool**
Reverts yogstation13/Yogstation#16013

It takes a lot of time to make all the chems used in 50u mix pills and even more time to determine safe dosage and whatnot. I have never seen anyone take the time to make any exorbitant amount of 50u mix pills nor have I ever in my 1,500 hours of chem made any more than maybe 8 50u mix pills in one round. Even then, the 50u mix pills were used for tooth implants for other people that specifically asked for them.

### CODE REVIEW

**Comment by Marmio64** [comment]
Maybe just make it like 30u so it's not insane but not tiny either

**Comment by TheRyeGuyWhoWillNowDie** [comment]
we should remove pills instead, chemistry players should get fucked

**Comment by Cartlord** [comment]
What if better manipulators increased pill volume?

**Comment by Moltijoe** [comment]
instead of reverting that i'm of the mind that
https://github.com/yogstation13/Yogstation/pull/16024
should be merged and gummy capacity should be upped from 15u

**Comment by VaelophisNyx** [comment]
mind you that 50u mixed pills were never the issue, honestly
it came down more to stuffing thirty-to-fifty units of *one* healing chem into them, then carrying around ~300+ backup HP

**Comment by CMOisLing** [comment]
Dont most medchems have OD thresholds around 30u already? That seems like a much better and already inplemented solution.

**Comment by VaelophisNyx** [comment]
you can safely take that thirty unit pill, though. that's the problem

that and why is ONE pill the VOLUME of a small beaker

**Comment by CMOisLing** [comment]
This game isnt meant to make complete sense so thats not a great argument. But imo this game has so many other ways of healing and such idk why pill size is the big issue. It take more time than its worth to make a couple 50u pills of all healing meds. With all the other ways of having infinite healing such as nanites, viro, xeno, i think mining. I havent noticed and dont believe that pills are really an issue currently.

**Comment by VaelophisNyx** [comment]
> This game isnt meant to make complete sense so thats not a great argument. But imo this game has so many other ways of healing and such idk why pill size is the big issue. It take more time than its worth to make a couple 50u pills of all healing meds. With all the other ways of having infinite healing such as nanites, viro, xeno, i think mining. I havent noticed and dont believe that pills are really an issue currently.

pills are taken instantly, making you capable of downing massive quantities of chems in literally 1-2s

**Comment by CMOisLing** [comment]
The amount of chems you take wont increase your passive healing. You only have so much health. Fighting someone with 5u of salicyclic acid is no different from fighting someone with 30u. Taking 50u of a healing chem on 1 sec isnt going to heal faster than sipping it slowly out of a beaker for 1min. The pill nerf is stupid because it is so much quicker and simpler to just carry a large beaker with a healing mix and take 5u sips. The only time pills are useful is for poisoning and combat stims. Which only need 10u because combat is to short to need anthing over 30seconds.

**Comment by CMOisLing** [comment]
Anyway idk why I care so much it literally changes nothing for me

**Comment by Bibby0110** [comment]
No need

**Pull request closed without merging**
