### PR TITLE
Gang dominator is now not inherently broken also theos is the best coder

### PR DESCRIPTION
**Pull request by SomeguyManperson**
Error: Takeover signal is currently blocked! There are too many walls within 2 standard units of this device."
:cl:  Theos
bugfix: gang dominators can now actually tick down why was this not seen in the testmerge 
/:cl:

### CODE REVIEW

**Comment by Altoids1** [comment]
Yo what the fuck

**Comment by SomeguyManperson** [comment]
unless I'm terribly wrong about something this should work. The dom would NEVER tick down even if the 5x5 area it requires was clear and I think it's because it asks for 30 tiles when it can only get 25

**Comment by Bibby0110** [comment]
If you give it leeway  make it atleast 24

**Comment by SomeguyManperson** [comment]
it has 2 free tiles as of right now

**Comment by SomeguyManperson** [comment]
merge resonator buff

**Comment by Bibby0110** [comment]
make it 24

**Comment by Bibby0110** [comment]
altoids is literally bad

**Comment by SomeguyManperson** [comment]
theos saves entire gamemode (colorized)

**Pull request merged**
