### PR TITLE
Removes the hallucination anomaly because it's either awful or completely harmless and neither is good

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Document the changes in your pull request

image

# Why is this good for the game?
I don't know about you but I like being able to play

# Testing
All references to the anomaly have been obliterated

# Spriting
sprites were removed

# Wiki Documentation

hallucination anomaly is gone

# Changelog

:cl:  
rscdel: hallucination anomaly has been removed since it removes the ability for anyone near it to play
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
Man died to this once probably

**Comment by azzzertyy** [comment]
ided

**Comment by SomeguyManperson** [comment]
> Man died to this once probably

if that was the case I would be removing flux anomalies since they are far more dangerous, the hallucination anomaly is just awful

**Comment by ShoziOffical** [comment]
Use meson to counter it then? Or don't go near it. Anomalies are supposed to be awful, that's why they are called anomalies

**Comment by warface1234455** [comment]
Or don't go near it at all

**Comment by ShoziOffical** [comment]
If you like to play, remove all the anomalies, remove antags, remove sec

**Comment by SomeguyManperson** [comment]
> Use meson to counter it then? Or don't go near it. Anomalies are supposed to be awful, that's why they are called anomalies

It renders your game effectively unplayable just about as long as it's on your screen. Unless, of course, you have equipped a common item, in which case it does literally nothing and can be safely ignored. Other anomalies, for one reason or another, cannot be safely ignored, and have to be approached with some degree of caution regardless of equipment (I'm not counting the radiation anomaly, because it's also awful at being an anomaly, and the "we already have a pile of shit, so adding another log to the pile won't make it stink more" argument is similarly awful)

The one thing the hallucination anomaly does conveniently provide is another equipment gate to stabilizing a delaminating supermatter. Forgot your mesons? that sucks, you can no longer walk.

**Comment by azzzertyy** [comment]
improve dont remove
(esspecially something as harmless as this)

**Comment by ShoziOffical** [comment]
Well if you don't like the other negative effects then just remove it instead of removing entire anomaly

**Comment by SomeguyManperson** [comment]
> improve dont remove (esspecially something as harmless as this)

are anomalies supposed to be harmless

**Comment by ShoziOffical** [comment]
> > improve dont remove (esspecially something as harmless as this)
> 
> are anomalies supposed to be harmless

this one isnt actually harmless, it makes you cant control yourself and could force you walk into SM or something else

**Review by cuackles — APPROVED** [review]

**Comment by Yarinoi** [comment]
> this one isnt actually harmless, it makes you cant control yourself and could force you walk into SM or something else

if you are close enough to the sm to walk into it and you arent wearing mesons then frankly thats a you issue

**Comment by ShoziOffical** [comment]
> > this one isnt actually harmless, it makes you cant control yourself and could force you walk into SM or something else
> 
> if you are close enough to the sm to walk into it and you arent wearing mesons then frankly thats a you issue

Then your opinion about this pr sounds like a you issue, this whole pr is ided

**Comment by ShoziOffical** [comment]
@Moltijoe what did balance council even say? Like for real tho you get the reasons for denied balance council pr but not approved one?

**Comment by Moltijoe** [comment]
> @Moltijoe what did balance council even say? Like for real tho you get the reasons for denied balance council pr but not approved one?

fair, usually it doesn't matter, but it makes sense in this situation

**Comment by Moltijoe** [comment]
Balance council:
>Denied in favour of https://github.com/yogstation13/Yogstation/pull/20842

**Pull request closed without merging**
