### PR TITLE
atomizes wheelchair movement noise

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

It's good code quality, now if someone wants to subtype wheelchair with a different noise, it's possible.

# Changelog

:cl:  
tweak: atomizes wheelchair movement noise
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
>now if someone wants to subtype wheelchair with a different noise, it's possible.

Are you (or anyone else) going to? What's the point of making this PR when nobody has plans to use it?

**Comment by Moltijoe** [comment]
> Are you (or anyone else) going to? What's the point of making this PR when nobody has plans to use it?

or at the very least, what prompted the idea?

**Comment by ToasterBiome** [comment]
> > now if someone wants to subtype wheelchair with a different noise, it's possible.
> 
> Are you (or anyone else) going to? What's the point of making this PR when nobody has plans to use it?

I am going to play a fart sound effect every time Koko moves.

**Comment by Moltijoe** [comment]
> > > now if someone wants to subtype wheelchair with a different noise, it's possible.
> > 
> > 
> > Are you (or anyone else) going to? What's the point of making this PR when nobody has plans to use it?
> 
> I am going to play a fart sound effect every time Koko moves.

ah, varediting?

**Review by ThatLing — APPROVED** [review]
Ok I can't argue with that one

**Pull request merged**
