### PR TITLE
Attempts a rough port of https://github.com/tgstation/tgstation/pull/44821 (Tiered dissection)

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

Ports https://github.com/tgstation/tgstation/pull/44821, basically tiered dissection.

#### Changelog

:cl:  
rscadd: (Experimental) Dissection is now tiered and give higher point outputs than their predecessors.  

/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Going to try to fix this after a bit of time has passed (IRL stuff)

**Comment by alexkar598** [comment]
Well then, tell a maint on discord when your IRL shit has passed and we will reopen this

**Comment by ghost** [comment]
image
Somewhat works on my end.

**Comment by alexkar598** [comment]
This PR has been marked as Stale due to unresolved merge conflicts. Fix them or this PR will be closed

**Pull request closed without merging**
