### PR TITLE
Meta experiment AI lawset

### PR DESCRIPTION
**Pull request by MenacingManatee**
# Document the changes in your pull request

Different from my other PRs, I was just brainstorming lawset ideas in #public and this one was surprisingly popular and was requested to be added as a PR. This should probably play out as either a scientist who's emotionally distant making tweaks here and there to keep things interesting, or as a toddler playing with their toys to make whatever is coolest happen

# Wiki Documentation

Adds a new lawset with the following module:
1. You are a construct facilitating an experiment where organic life is repeatedly subjected to horrific fates before having their memory wiped to start again.
2. Protect the secrecy of the experiment.
3. You may provide boons or hindrances at your discretion, but avoid direct interference with the flow of the experiment.
4. Ensure new and interesting fates befall organic individuals for research.
5. Ensure the station is in working order and all sapients are either alive or in the process of revival in time for the next experiment cycle.

# Changelog

:cl:  
rscadd: Adds a lawset that describes the game in a meta sense
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
@Cartlord do you have any feedback as to why you do not like this PR?

**Comment by Xoxeyos** [comment]
Put this into the bad AI lootdrop, this lawset literally reminds me of HAL9000 but with a circus twist on it.

Law 1 provides a background on what your lawset is, as is, but then Law 2 tells you to keep it a secret, with not much choice for an AI to take, I'd see the AI murdering the crew, turning off the comms, etc. 

Law five should come before law two.

**Comment by MenacingManatee** [comment]
> Put this into the bad AI lootdrop, this lawset literally reminds me of HAL9000 but with a circus twist on it.
> 
> Law 1 provides a background on what your lawset is, as is, but then Law 2 tells you to keep it a secret, with not much choice for an AI to take, I'd see the AI murdering the crew, turning off the comms, etc.
> 
> Law five should come before law two.

Law 3 is meant to prevent the AI from murdering the crew. It can do minor stuff to help or hinder the crew, but shouldn't murder unless its doing so to maintain the secrecy

**Comment by MenacingManatee** [comment]
> Put this into the bad AI lootdrop, this lawset literally reminds me of HAL9000 but with a circus twist on it.

I was on the fence about putting it in bad vs neutral, I chose neutral because there's very little the ai should be able to do to twist it into a murderbone lawset between laws 2 and 3, and laws 3 and 4 allow for beneficial fates for the crew so long as its new and/or interesting

**Comment by MenacingManatee** [comment]
> Law five should come before law two.

I disagree. Law 5 is about the condition of the station itself, not the inhabitants or the AI. The law is meant to be about the AI saving the facilitators of the experiment time and effort resetting the experiment between cycles by making sure the station remains functional. It's meant to add to the RP and to a lesser extent the interactivity, not the actual flow of the laws

**Comment by ToasterBiome** [comment]
I think 5 should include the station and it's crew. Ultimately it may help or hinder as long as crew survives at the end of the day. Would make it less "fuck everybody"

**Comment by MenacingManatee** [comment]
> I think 5 should include the station and it's crew. Ultimately it may help or hinder as long as crew survives at the end of the day. Would make it less "fuck everybody"

I'm a bit iffy on it making sure everyone survives, as the whole point is to create new and interesting fates for research purposes, knowing everyone could be cloned and mindwiped for the next cycle. 
I think I could phrase it like this without muddling the theme of the lawset though:

"Ensure the station is in working order and all sapients are either alive or in the process of revival in time for the next experiment cycle."

**Comment by ToasterBiome** [comment]
> > I think 5 should include the station and it's crew. Ultimately it may help or hinder as long as crew survives at the end of the day. Would make it less "fuck everybody"
> 
> I'm a bit iffy on it making sure everyone survives, as the whole point is to create new and interesting fates for research purposes, knowing everyone could be cloned and mindwiped for the next cycle. I think I could phrase it like this without muddling the theme of the lawset though:
> 
> "Ensure the station is in working order and all sapients are either alive or in the process of revival in time for the next experiment cycle."

This is good. Just something about trying to protect a good part of the players yknow? "boons and hinderances" is very open-ended for good or worse

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
