### PR TITLE
#spriting tricked me into respriting the Contractor baton 

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
image
image

If I catch you doing this I am gonna shove you so far down into #spriting 101 that by the time you come out your gonna be able to take my job away from me. 

# Spriting
batongsss

# Wiki Documentation
Time to feed wiki their rations of acknowledgment. 
batonwikii
batonwiki

# Changelog

:cl:  

imageadd: I only get the contractor baton to kill borgs and that's about it, I hate yall forever and always...dumbass tincans

/:cl:

### CODE REVIEW

**Comment by isotope436** [comment]
make it animated

**Comment by KillerOrcaCora** [comment]
I don't get paid to animate things by request

**Comment by Mantlecrawler** [comment]
This looks much nicer, more befitting of the BATONG

**Comment by Burger1998** [comment]
i like the new orange color but it almost looks too shaded? a lot of shadows when compared to other items that it might be a bit jarring when implemented and the sprites downsized. curved guard looks nice but maybe a bit too curved for my liking i loved the utilitarian style the baton had.
 
but eh what the fuck i suck at pixel art so what do i know. pretty colours though!

**Comment by Burger1998** [comment]
> i like the new orange color but it almost looks too shaded? a lot of shadows when compared to other items that it might be a bit jarring when implemented and the sprites downsized. curved guard looks nice but maybe a bit too curved for my liking i loved the utilitarian style the baton had.
> 
> but eh what the fuck i suck at pixel art so what do i know. pretty colors

**Review by cuackles — APPROVED** [review]

**Comment by isotope436** [comment]
you dont get paid at all though

**Comment by KillerOrcaCora** [comment]
I do get paid, in exposure and filling my portfolio

**Pull request merged**
