### PR TITLE
[PORT] Atmospheric thermals from /tg/

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Ports https://github.com/tgstation/tgstation/pull/68878
Allows atmosians to see the temperature of a turf

https://github.com/yogstation13/Yogstation/assets/42524344/27154b4e-19a6-4e50-9ab0-974ab7761c05

# Spriting
See video

# Wiki Documentation

Add that tray scanners have a thermal mode
Add that the engineering techweb unlocks specialized atmos thermal goggles

# Changelog
:cl:  
rscadd: Added atmosian thermal goggles and mode to t-ray mesons
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by iamthesilly** [comment]
nice

**Comment by cuackles** [comment]
Ok now show it watching a open tile fusion

**Comment by azzzertyy** [comment]
> Ok now show it watching a open tile fusion

see linked port

**Review by cuackles — APPROVED** [review]

**Comment by azzzertyy** [comment]
DNM, needs updating to update_appearance

**Comment by JohnFulpWillard** [comment]
this doesn't touch icons n stuff it should be fine

**Pull request merged**
