### PR TITLE
New Traitor Item: The Gasharpoon

### PR DESCRIPTION
**Pull request by cowbot92**
Special thanks to @LazennG for his work on the buster arm, and to @ident (sorry dont know your github) for the sprites, here's his kofi if you want to support him- https://ko-fi.com/nesisknesis

# Document the changes in your pull request

Adds the Gasharpoon gauntlet, a 10 cost traitor item which acts as a gauntlet that enhances your punches much like the power fist, and grants you access to a ranged harpoon, allowing you to spear your enemies and pull them back.

When you hit a target they will become "harpooned" granting them a 1.3x damage multiplier for a few seconds.

It is a 10 force item, however through the power of math and space magic it does 20 damage on hit with solid wound chance.

# Why is this good for the game?

Bon voyage.

# Testing

https://github.com/yogstation13/Yogstation/assets/75333826/94d35f13-15ca-4fcf-8dd3-0658090c4b26

# Spriting

gasharpoon
gasleft
gasright
gottamakerope
harpoonhead

# Wiki Documentation

Add the 10TC cost item to the Syndicate Items page, along with it's description and photos

# Changelog

:cl:  Cowbot92 & Chubbygummibear

rscadd: Added new traitor item, the gasharpoon

/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Hmm a melee item with a hook to pull things hmm...
If only it had some sort of charged punch and could break walls...

**Comment by ShoziOffical** [comment]
> Hmm a melee item with a hook to pull things hmm... If only it had some sort of charged punch and could break walls...

Mmmmmmmm buster arm go brrr

**Comment by Yarinoi** [comment]
yeah im gonna be real here this sounds  like watered down buster arm

**Comment by LazennG** [comment]
really looking forward to treating people like yo-yos

**Review by Mqiib — APPROVED** [review]
I dunno what the supposed changes are on the tacprod but I don't see any difference so double check that and you're good

**Comment by PibeCantina** [comment]
Idk if it got fixed but the gasharpoon ability tooltip isnt capitalized :nerd:

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
