### PR TITLE
Adds metrocop voicelines to security masks

### PR DESCRIPTION
**Pull request by maxion12345**
# Document the changes in your pull request
we already have the death noises so why not

now you can finally tell those assistants to pick up that can

https://user-images.githubusercontent.com/23666142/136317322-986a4475-3928-4e8f-a405-e12c9cec3ca6.mp4

included voicelines:

Affirmative
Copy
Alright, you can go
Backup
Citizen
Get down
Get out of here
Grenade
Help
Hold it
In position
I said move along
Keep moving
Lookout
Move along
Move back right now
Move it
Now get out of here
Pick up that can
I said pick up the can
suspect prepare to receive civil judgement
Now put it in the trash can
Responding
Roger that
Shit
Take Cover
You knocked it over, pick it up
Searching for suspect
First warning, move away
Sentence delivered
Issuing malcompliant citation
Anticitizen
Apply
Hehe
# Wiki Documentation

n/a
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: you can use metrocop voicelines with a secmask, see PR for full list
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
make it do the CP laugh instead of a normal one when you *laugh

**Comment by maxion12345** [comment]
> make it do the CP laugh instead of a normal one when you *laugh

I'll add it under "hehe" because I don't want to touch emote code after my sheesh pr

**Comment by ynot01** [comment]
question, how will this be made knowledgeable to the average player?

**Comment by maxion12345** [comment]
> question, how will this be made knowledgeable to the average player?

I'm hoping it'll just spread by word of mouth, however, I am considering adding some additional features (toggle button, a button to list the keywords) and so on.

**Comment by maxion12345** [comment]
added them, they are under the right-click menu of the secmask (to avoid cluttering UI with more buttons)

**Comment by adamsong** [comment]
From where did you source these assets?

**Comment by maxion12345** [comment]
> From where did you source these assets?

from a 2009 reddit post containing a .zip of the half-life vo files
yes it violates license, but we've merged license violating things from valve games in the past so dunno where you guys cross the line. half life 2 came out nearly two decades ago so I think we're good on this one folks

**Comment by Hopekz** [comment]
>  yes it violates license, but we've merged license violating things from valve games in the past 

Yikes, knowing something is bad before doing it anyway makes it worse since intent matters if this were to ever go to a courtroom

**Comment by maxion12345** [comment]
> > yes it violates license, but we've merged license violating things from valve games in the past
> 
> Yikes, knowing something is bad before doing it anyway makes it worse since intent matters if this were to ever go to a courtroom

In case of an investigation by any federal entity or similar, I do not have any involvement with this group or with the people in it, I do not know how I am here, probably added by a third party, I do not support any actions by the member of this group.

nah we'll be fine. we're already using assets from valves newest vr game and nobody gives a shit. assets from an 18 year old game are probably the least of our concerns. This is a just a neat PR to make playing security just a little bit more fun for everyone. Also fits with stunbatong :)

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
