### PR TITLE
Adds new Lavaland Biodome Ghost Spawn: The Fisherman, in a Fishing Pier Biodome

### PR DESCRIPTION
**Pull request by VaelophisNyx**
Fish fear him

# Document the changes in your pull request

Adds a new Biodome to lavaland based on fishing, complete with a small bar & kitchen setup for serving miners and the two fishermen that spawn here. Also features a Gift Shop!
PR additionally makes Lavaboats work on water turfs, mostly for RP since water is (currently) safe.
Additionally fixes a missing fishing vendor restock item
adds proper names to lavaland biodome areas, so they're easier to locate in code and in mapping tools.

ss (2022-07-08 at 12 43 39)

# Spriting

new fishing vendor restock
yourspritesire

enlarged
unknown

# Wiki Documentation

Lavaland page will need a mention of Fishermen existing
Ghost page will need the Fisherman Sleeper added to the table of possible ghost spawns
Ruins page will need an entry and screenshot of this ruin
ss (2022-07-09 at 05 03 37)

# Changelog

:cl:  VaelophisNyx, @nmajask, @KillerOrcaCora 
rscadd: Added new Fishing Pier Biodome to Lavaland
rscadd: Added new Fisherman Sleeper ghost spawn role
bugfix: fixed fishing vendor restock item not existing
tweak: lavaboats can now move on water
tweak: lavaland biodome areas now properly named
imageadd: adds a new fishing vendor restock sprite
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
A lot of biodomes feature entrances on at least two sides. Can you split the lake in half and have a small entry area north?

**Comment by VaelophisNyx** [comment]
Yeah I can look into it
it does feel kinda barren up there anyway

**Comment by JamieD1** [comment]
Do we really need all those vending machines?

**Comment by VaelophisNyx** [comment]
I could probably remove some. I'm just unsure what to fill the space with however

**Comment by VaelophisNyx** [comment]
Updated to remove some vendors, and shuffled some stuff around, namely the space cash and arcade machine

**Review by ToasterBiome — APPROVED** [review]

**Review by KillerOrcaCora — APPROVED** [review]
fishy

**Pull request merged**
