### PR TITLE
Aw sheet - Engiborg Gripper Tweak

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
The Engiborg gripper can now hold sheets of stuff so they can build WAY more things, put plasma into generators, make cool new windows, and steal bananium from the clown so it can be properly disposed of (vital)

# Why is this good for the game?
Engiborg can build more better

# Changelog

:cl:  
tweak: Engiborg gripper can hold sheets
/:cl:

### CODE REVIEW

**Comment by Runian** [comment]
Imo should blacklist solid plasma (and maybe plasteel) so only emagged borgs can grab them

**Comment by iamthesilly** [comment]
This lets them build r-walls and make golems, are you sure you want to do that?

**Comment by MajManatee** [comment]
Plasma was the reason I did this because I was trying to set up a generator and couldn't power it since no hand havers were nearby.
As for Rwalls and golems, sure? Laws still prevent borgs from really doing much with these

**Comment by Moltijoe** [comment]
> Plasma was the reason I did this because I was trying to set up a generator and couldn't power it since no hand havers were nearby. 

make it click and drag to put plasma into a generator then

**Comment by Moltijoe** [comment]
Balance Council:
>Borgs aren't supposed to have arms, stop removing THE downside to borgs

**Comment by ju45he** [comment]
Malf engine Borg's R walls when I teleport 3 maxcaps directly into the AI chamber

**Comment by MajManatee** [comment]
fuck "balance council"

**Pull request closed without merging**
