### PR TITLE
ID Consoles read your ID from your body, no need to stick it in

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
Title. Checks the ID you're wearing for access

You need to log out, it retains your access if you just leave, just like the comms console.

### Why is this good for the game?

Convenience. Might be a buff to finding the HoPs ID console unlocked

#### Changelog

:cl:  
rscadd: The Identification Console has been upgraded with SmartScan and can now read your ID directly on your uniform! Don't forget to log out.
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
So this is nifty but I'm on the fence on if it's a good idea.

There are times when I've seen people intentionally jump the HoP when his ID is in so that he can't use the doors and such. It's a smart play and I like to support those. 

Also, I've seen HoPs lock their dumbasses out of their office which has made for interesting situations. 

So these are my thoughts on it.

**Comment by Bibby0110** [comment]
> So this is nifty but I'm on the fence on if it's a good idea.
> 
> There are times when I've seen people intentionally jump the HoP when his ID is in so that he can't use the doors and such. It's a smart play and I like to support those.
> 
> Also, I've seen HoPs lock their dumbasses out of their office which has made for interesting situations.
> 
> So these are my thoughts on it.

Just sounds like a mechanic to punish people for doing their jobs, especially new people. If you're jumping the HoP and you're relying on him to be unable to run open his doors then you're doing it way too slow. By the time he can react you'd be next to him already.

**Comment by Hopekz** [comment]
I always thought that period of vulnerability was a feature.
Not only for the HoP but any machines that require an ID.

**Comment by MegaEmpirical** [comment]
I don't see a punishment.

And opportunities of vulnerability are part of game design.

**Comment by Tipy1802** [comment]
No more making a second ID with Ident console access on it round start while the swarm of angry tiders are blasting your shutters, praise be!
Or accidentaly giving your ID instead of the ID of the person.
No more constant juggling between the two IDs (you need yours to open the windoor)

**Comment by ToGWtF** [comment]
The HoP spawns with a pocket-sized table that has this same capability. He can log in as long as he's got his ID on. If he ever gets his tablet stolen from him, it remains logged in and capable of giving all access.

**Comment by maxion12345** [comment]
Just use your tablet lol

**Comment by Bibby0110** [comment]
> The HoP spawns with a pocket-sized table that has this same capability. He can log in as long as he's got his ID on. If he ever gets his tablet stolen from him, it remains logged in and capable of giving all access.

Yes but this is for the console.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
