### PR TITLE
lets the quartermaster make desk announcements with their console

### PR DESCRIPTION
**Pull request by athena413**
### Intent of your Pull Request

The fucking signal tech gets it, but the QM doesn't.

Okay.

Applies to all maps, including Eclipse, which didn't originally have a quartermaster RC.

#### Changelog

:cl:  
rscadd: announcementConsole = 1 instead of 0 on all the quartermaster request consoles
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
Let the clown make announcements on his desk console

**Comment by Tipy1802** [comment]
Neat, I feel like the warden should get one as well so he can call man hunts, ask for people to turn them self in, announce brig policy, address contraveries around “””shitcurity””” , etc

**Comment by MrHorizons** [comment]
> Neat, I feel like the warden should get one as well so he can call man hunts, ask for people to turn them self in, announce brig policy, address contraveries around “””shitcurity””” , etc

Don't forget that the warden is not only more likely, but is expected, to be in their office.

**Review by JamieD1 — CHANGES_REQUESTED** [review]
On hold till random maint is merged

**Comment by Hopekz** [comment]
If we're letting non-heads do announcements I'd like to see a lower priority announcement system in place so that they don't get the usual announcement notification and sound. Something more gentle and passive to distinguish non-command vs command announcements.

**Review by patpol4 — APPROVED** [review]
Hopek's suggestion is interesting however that requires coders to help out with this, I'll hold on a bit on merging since there is a discussion happening here.

**Comment by Hopekz** [comment]
> Hopek's suggestion is interesting however that requires coders to help out with this, I'll hold on a bit on merging since there is a discussion happening here.

Why merge when it's not exactly what you want?
image
 
**The alternative of changing nothing is appropriate until a more fitting solution comes up.**

"The fucking signal tech gets it, but the QM doesn't." is a very weak argument on why the QM needs this.
Like people have mentioned earlier it leads to a slippery slope of letting everyone make head announcements like the warden etc.

If merged as-is this PR would be leading towards head announcements having less meaning.

**Comment by athena413** [comment]
QM effectively "heads" the cargo department under most circumstances, and they should be able to make proper station announcements. They should be able to make announcements, whether it be "we're an independant state now", "give us your budget card" or even "miners stole all the mats"

**Comment by Hopekz** [comment]
> QM effectively "heads" the cargo department under most circumstances, and they should be able to make proper station announcements. They should be able to make announcements, whether it be "we're an independant state now", "give us your budget card" or even "miners stole all the mats"

I don't like your argument and here is why:

 > QM effectively "heads" the cargo department under most circumstances

**The QM is not a head of staff.** He does not have access to the command channel, he does not get access to the Bridge/Brig. He is a glorified cargo worker.

If we used this logic to determine who can make head announcements we can end up with the following:
**The chef** effectively "heads" the kitchen under most circumstances.
**The warden** effectively "heads" the security department under some circumstances.
**The clown** effectively "heads" the pranking department under most circumstances. Pranks are never approved by the HoP

I think none of the roles that I listed should have official head announcement permissions.

> whether it be "we're an independant state now", "give us your budget card" or even "miners stole all the mats"

This is exactly what I mean. The QM has nothing worthwhile to full-on head announce to the whole crew. All the examples you have provided are spam that would take away from the importance of head announcements.
Even "give me your budget cards" is more of a whiney request because **the QM is not a head of staff.** 
The HoP has access to cargo channels and can serve as the "filter" for announcements since the HoP is a head.

**I would be alright if there was some newer "lesser" announcement that didn't take value away from official head announcements** 
Giving non-heads the ability to do command head announcement is not the way to go in my opinion.

**Comment by patpol4** [comment]
QM is not officially a head of staff but he is technically the head of the cargo department. HoP usually ignores cargo.

**Comment by Hopekz** [comment]
> QM is not officially a head of staff but he is technically the head of the cargo department. HoP usually ignores cargo.

I'd be fine with making QM an official head of staff I just don't like the idea of giving official head announcement powers to a non-head.

**Comment by patpol4** [comment]
Does it say anywhere in the annoucement that it's a 'head' annoucement? IIRC sigtech gets it aswell

**Comment by athena413** [comment]
> The QM is not a head of staff. He does not have access to the command channel, he does not get access to the Bridge/Brig. He is a glorified cargo worker.

The thing is, the QM is also the direct supervisor to their department. Cargo techs and miners generally go to the QM first, and the HoP only in very rare scenarios. What the QM says, almost always, goes. They aren't a head of staff, but they very obviously command the supply department.

> **The chef** effectively "heads" the kitchen under most circumstances.

There is no command structure in the kitchen. The bartender, chef, and botanists are all on the same level as each other, while the Quartermaster is the direct supervisor to Cargo Technicians and Shaft Miners.

> **The warden** effectively "heads" the security department under some circumstances.

This is actually somewhat true, and I wouldn't mind wardens being able to make announcements of their own sometime in the future.

> **The clown** effectively "heads" the pranking department under most circumstances. Pranks are never approved by the HoP

Pranking isn't even a department, or subdepartment.

**Comment by patpol4** [comment]
@JamieD1 please approve and merge since your request is blocking me from merging.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
