### PR TITLE
adds rod of asclepius to legion barracks

### PR DESCRIPTION
**Pull request by boodaliboo**
adds a Greek staff to a ruin based off of Greek army. for anyone who doesn't know this staff when used makes you pacifistic but heal yourself slowly and others around you
#### Changelog

:cl:  
rscadd: Added rod of asclepius
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
i personally really enjoy using the rod of asclepius, one of the few miner items that isnt insane powercreep uber valid loot, would be nice to see it more prevalent and easier to get

**Comment by Marmio64** [comment]
legionnaires are roman not greek, dude, this is a roman ruin

**Comment by boodaliboo** [comment]
> legionnaires are roman not greek, dude, this is a roman ruin

same difference

**Review by Ktlwjec1 — APPROVED** [review]
eh I've got no issue with it

**Comment by deathslayer2481** [comment]
Roman ruin, Italy vs Greece, you are stoopid.

**Pull request merged**
