### PR TITLE
[WIP] Ports mentors

### PR DESCRIPTION
**Pull request by GuppyLaxx**
There, it compiles, haven't tested it for shit because it's 8 in the morning and I was bored
Literally a straight port from hippie with some changed procs and shit

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
@ThatLing so you can complain while im asleep <3

**Comment by ThatLing** [comment]
CONFLICTS

**Comment by GuppyLaxx** [comment]
I SWEAR WHY DID YOU MERGE SHIT WHILE I WAS MAKING THIS

**Comment by ThatLing** [comment]
im on top yo

**Comment by ThatLing** [comment]
Guppy, whats your discord name

**Comment by GuppyLaxx** [comment]
Neon

**Comment by GuppyLaxx** [comment]
You wanna fight buddy?

**Comment by Bawhoppen** [comment]
Just to clarify, are you doing this for the bounty? Cause it's not the full $50 dollars for this.

**Comment by Bawhoppen** [comment]
Or is this just out of the kindness of your heart?

**Comment by Bawhoppen** [comment]
Oh wait, hello Neon.

**Comment by Bawhoppen** [comment]
Still not sure if it's for the bounty though.

**Comment by Carbonhell** [comment]
>stealing my bounty
:gun:

**Comment by Cw3040** [comment]
>stealing my bounty
🔫

stealing MY bounty
🔫

**Comment by Kmc2000** [comment]
I misread this as adds mentos.

Thoroughly disappointed

**Comment by GuppyLaxx** [comment]
tested and just about all of it(???) works, maybe, i've got no fucking idea about SQL and shit so

**Comment by ThatLing** [comment]
This is on hold until staff can figure out the details of mentors.

**Comment by GuppyLaxx** [comment]
reeeee

**Comment by GuppyLaxx** [comment]
zzzz

**Comment by Amelia0010** [comment]
https://github.com/GuppyLaxx/Yogstation-TG/pull/1

**Comment by Amelia0010** [comment]
https://github.com/GuppyLaxx/Yogstation-TG/pull/1

**Comment by Amelia0010** [comment]
https://github.com/GuppyLaxx/Yogstation-TG/pull/1

**Pull request merged**
