### PR TITLE
LITERALLY ADDS BEN SWOLO

### PR DESCRIPTION
**Pull request by nesisknesis**
ADDS BEN SWOLO TO THE GAME. MAY THE FUCKING FOURTH BE WITH YOU, always.

image

image

BEING SWOLE IS GOOD FOR THE SOUL

SPEEDMERGE

#### Changelog

:cl:  
rscadd: ADDS BEN SWOLO
/:cl:

### CODE REVIEW

**Review by fluffe9911 — APPROVED** [review]
Im fluffe9911 and I approve of this meme

**Review by ghost — APPROVED** [review]
Not only it's a Ben Swolo, its a **BEN SWOLO**

**Review by SomeguyManperson — APPROVED** [review]
benis B)

**Comment by Altoids1** [comment]
What the fuck is wrong with you people

**Pull request merged**
