### PR TITLE
Basalt Katana fauna damage buff and new mechanic: A Dodge roll

### PR DESCRIPTION
**Pull request by Chubbygummibear**
# Why is this good for the game
Currently basalt katana does 25 damage to non fauna and 60 to fauna after adding the 35 burn bonus. However vs megafauna this falls to 47.5 due to their burn resist. making the katana a slapping stick only marginally better than a single kpa in exchange for putting yourself in harms way. this makes it more interesting and viable as a fauna fighting weapon and is a fun skill check.

# Document the changes in your pull request

Well it's more of a dodge flip really, but the point is that when you use the katana in hand by clicking it or pressing "z", you do an acrobatic flip that grants you 0.5 seconds of godmode, these are effectively dodge roll i-frames. tech megafauna attacks, a bullet, flip over lava and chasms because i gave it .1 seconds of flying, roll into the sm shard repeatedly, die because you didn't keep track of how much stamina you were using and collapsed. The dodge roll/flip does cost stamina to use, 5 stamina per dodge on lavaland due to less pressure, and 15 on the station. So on lavaland you can dodge roughly 8-9 times in quick succession before the slowdown kicks in, so keep track of your stam meter. On the station it will only take 3 rolls before you hit slowdown.
As an additional skill check, dodge rolling into walls and people will cause you to eat shit and drop the sword, be careful of dodging in close quarters or in diagonals, the game hates trying to resolve those and will probably cause you to clip a wall.

Here's a demonstration of me poorly fighting Hiero, relying on spot dodging, exhausting myself, and finally hitting a wall because i'm bad

https://user-images.githubusercontent.com/46236974/173281438-58c4c63d-9165-499b-a425-35da80389b25.mp4

The damage buff i mentioned was raising the fauna damage bonus to 52, making it 18+52 for 70. this damage type has been changed to brute as not to content with megafauna burn armor

# Sprites
evasion
the icon that pops up to show you that you have the iframes. yes this is the Divinity 2 uncanny evasion skill icon
# Wiki Documentation

Basalt katana's total damage vs fauna on hit up to 70
vs crew it's 18

Basalt Katana now has an in-hand ability that makes you dodge roll forward in the direction you're facing. this flips you over the next two tiles, by flip i mean you get flying while moving, and invincibility frames for .5 seconds. This effect only stops pure damage numbers. Flipping into an explosion will block all the damage but still send you flying, stun you and deafen you. bolas will stick to you and whatever other effects that don't just do numbers on someone.

dodge roll on lavaland costs 5 stamina
dodge roll on station costs 15 stamina 

# Changelog

:cl:  @LazennG, @ToasterBiome, Chubbygummibear
rscadd: Basalt Katana gets an activatable dodge roll mechanic
rscadd: Dodge roll costs 5 stamina on lavaland and 15 on station but gives you .5 seconds of iframes and flying. Dodge rolling into a wall or another person will bonk and stun you, same with stam-critting yourself. i-frames only block straight up damage numbers, explosions still throw and deafen you, cc effects like a bola will still stick
tweak: Basalt katana force down to 18 to avoid miner ninjas tearing up the crew
tweak: Basalt katana damage on lavaland fauna up to 70, including megafauna
soundadd: dodge roll sound effect
imageadd: evasion icon to go with the popup letting you know you're in i-frames
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
badass

**Comment by VaelophisNyx** [comment]
one thing I'd like to know, as primarily a player, is how does time dilation affect the roll & iframe buff

**Comment by Chubbygummibear** [comment]
> one thing I'd like to know, as primarily a player, is how does time dilation affect the roll & iframe buff

I tested this with @LazennG the other day and although his ping was killing him he was still able to iframe juke the ash drake's landing slam. time dilation would be trickier to know the exact effects of since i can't really stress test my server

**Comment by JamieD1** [comment]
@yogstation/Art

**Review by cuackles — COMMENTED** [review]
Gotta learn how this works

**Comment by MajManatee** [comment]
18 damage katana, never gonna use it now smh

**Comment by LazennG** [comment]
> 18 damage katana, never gonna use it now smh

filtered

**Comment by SomeguyManperson** [comment]
document the dodge roll in the wiki bit too pls

**Comment by Chubbygummibear** [comment]
> document the dodge roll in the wiki bit too pls

added

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
