### PR TITLE
shuttles move after the round ends

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Github documenting your Pull Request

this can't POSSIBLY break anything can it
allows shuttles to move and dock after the round ends

# Changelog

:cl:  
tweak: shuttles can now move post-round end
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
ADD EVENTS TOO

**Comment by Bibby0110** [comment]
why?

**Comment by adamsong** [comment]
Catastrophic meteors post round

**Comment by adamsong** [comment]
Does this fix #7439?

**Comment by Hopekz** [comment]
> why?

RP

**Review by JamieD1 — APPROVED** [review]
Can only end badly

**Comment by SomeguyManperson** [comment]
> Does this fix #7439?

won't fix that that's a different problem with the shuttle not automatically having its destination set to cc while in transit

**Pull request merged**
