### PR TITLE
adds tesla supermatter

### PR DESCRIPTION
**Pull request by void5402**
# Document the changes in your pull request
added a new kind of roundstart supermatter engine that does the tesla zaps instead of radiation and a item in ce locker names tsm kit for converting the roundstart sm to one. 
tested in runtime station.
why: to make some weirder setups and give engineers a new toy to play with
 
# Spriting
there are some but github wasn't able to upload them.
https://pasteboard.co/5N10XxiN61bc.png
https://pasteboard.co/6WfBnaQVkc2U.gif
https://pasteboard.co/aZ8jl6gYgHKV.png
https://pasteboard.co/uE93IT6LVo0A.png

# Wiki Documentation
tesla supermatters are now a thing
tsm kit

 
# Changelog

:cl:  
rscadd: added tesla supermatter that do tesla zaps instead of radiation
rscadd: added tsm kit to convert roundstart sm to a zappy one
imageadd: icon for tsm kit
mapping: added tesla supermatter engine template for box and meta
/:cl:

### CODE REVIEW

**Review by MajManatee — DISMISSED** [review]
PR cant be approved if you don't upload the sprites for review. Check the file type and try again I guess?

**Comment by void5402** [comment]
> PR cant be approved if you don't upload the sprites for review. Check the file type and try again I guess?

done.

**Comment by Ethan4303** [comment]
Does this remove the supermatter we all know and love that produces radiation? Or is this a new engine entirely? Because I'll be very sad if your removing the base sm



(I could totally check the code to answer my own question but I'm super lazy, on mobile, and at work B) )

**Comment by MajManatee** [comment]
> Does this remove the supermatter we all know and love that produces radiation? Or is this a new engine entirely? Because I'll be very sad if your removing the base sm
> 
> (I could totally check the code to answer my own question but I'm super lazy, on mobile, and at work B) )

you are just dumb

**Comment by SomeguyManperson** [comment]
why lump  hydrogen in with this when it was already its own pr?

**Comment by void5402** [comment]
> why lump hydrogen in with this when it was already its own pr?

for less pull requests

**Comment by MajManatee** [comment]
We would perfer changes be atomic, thats to say more PRs so that if we wanted to revert a specific thing, we could. Instead of having to revert this whole pr.

**Comment by void5402** [comment]
> We would perfer changes be atomic, thats to say more PRs so that if we wanted to revert a specific thing, we could. Instead of having to revert this whole pr.

so i go remove the hydrogen and inactive state from this pr?

**Comment by cuackles** [comment]
need to know if this pr will be atomized or kept as one for the art review

**Comment by void5402** [comment]
> We would perfer changes be atomic, thats to say more PRs so that if we wanted to revert a specific thing, we could. Instead of having to revert this whole pr.

done.

**Comment by patpol4** [comment]
Looks like bloat, wouldnt it be better to just have the special coils as an option for the normal sm?

**Comment by void5402** [comment]
> Looks like bloat, wouldnt it be better to just have the special coils as an option for the normal sm?

so adding a tesla kit thing to ce locker and some small fixes.
ok

**Comment by void5402** [comment]
done

**Comment by patpol4** [comment]
But you are still adding an entire separate template for this thing which changes only the plasma collectors for a rod

**Comment by void5402** [comment]
i made it so engineers are taking a risk and making sm more lethal by adding it to get more power
not just swaping templates

**Pull request closed without merging**
