### PR TITLE
(hopefully) changes the name of gang tags to be the same as normal graffiti

### PR DESCRIPTION
**Pull request by maxion12345**
tested
# Document the changes in your pull request

Changes the name of gang graffiti from "Graffiti" to "letter" (same as crayon/spraycan) to prevent meta. Is it actually gangs, or clown fucking with a spraycan or crayon???? no more meta :)))
# Wiki Documentation

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl: 
tweak: Gang graffiti sports the same name as normal graffiti, in order to prevent meta. Please go paint fake gang-tags and make security mad.
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
next make blood runes letter for ultra based

**Comment by maxion12345** [comment]
> next make blood runes letter for ultra based

you can just examine the runes
they are made of blood
no real way to disguise that

**Comment by maxion12345** [comment]
why linter angry

**Comment by SomeguyManperson** [comment]
pull from upstream master to fix the linter

**Review by adamsong — APPROVED** [review]
Looks good, pull from upstream to fix linter

**Pull request merged**
