### PR TITLE
donor borg skins

### PR DESCRIPTION
**Pull request by nesisknesis**
adds a new secborg donorskin for me, makes my previous one the paramedic droid skin available for all donors, and adds a new medical borg skin, the stacked medbots (idea by jcat)

image

:cl: Identification
rscadd: 3 new donor borg skins, 1 private, 2 public
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
I might donate just for this

**Comment by nesisknesis** [comment]
the money is always right

**Comment by MegaEmpirical** [comment]
At least show us the private ones. Money shot!

**Comment by nesisknesis** [comment]
here: private
image

public
image

**Comment by conk444** [comment]
sounds good, do I need to donate to the TG server or just to byond? I already donated to byond, hope I've got my money right.

**Comment by MegaEmpirical** [comment]
> sounds good, do I need to donate to the TG server or just to byond? I already donated to byond, hope I've got my money right.

We are not TG so donating to them will do nothing. Also, donating to Byond won't unlock player donator benefits on our server.

To be able to access our player donator benefits you'd need to play on our server and donate to https://yogstation.net/donate

Hopefully that helps.

**Pull request merged**
