### PR TITLE
Fixes shadowlings not being able to veil flashlights

### LINKED ISSUE #17857: Veil doesnt work on protable lights
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: It wouldnt turn off seclights or flashlights that were on the ground nor lights that people had equiped

 Submitted by: Master Drake (598557108551811073)

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Snowflake `on` var necessary for flashlights

# Changelog

:cl:  
bugfix: Fixed shadowlings not being able to disable flashlights
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
LOL I didn't even know this bug existed until I threw 20 flashlights at a sling

**Comment by MajManatee** [comment]
we should just leave slings broken to punish anyone that plays it

**Comment by MajManatee** [comment]
fixes #17857

**Comment by Marmio64** [comment]
please, merge already...

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
