### PR TITLE
poppy the safety possum is resistant to lasers on the SM engine

### PR DESCRIPTION
**Pull request by UselessTheremin**
title, it hurts my soul to see poppy get fuggen blasted every round. i may have done a shitcode moment, just let me know. i wanted to move poppy, but there was no better area so i decided to go this route. plus, its funny to see a possum be completely laser proof.
🆑
tweak: poppy is immune to lasers in sm engine
/🆑

### CODE REVIEW

**Comment by alexkar598** [comment]
inb possum is used in combat to bypass lasers

**Comment by patpol4** [comment]
Poppy the safety possum dying to improper safety procedures is part of the joke. Also I'd rather not have laser resistant mobs running around due to what alexkar said and since it doesn't make much sense for a possum.

**Comment by TheLinuxOS** [comment]
I agree with what wej said, the fact that the possum always died due to being unsafe (Im fairly certain it spawns in front of the emitters) is part of the joke.

**Comment by UselessTheremin** [comment]
Fair enough.

**Pull request closed without merging**
