### PR TITLE
reverts a change to xenobio that makes red slime potions do nothing or gib their user because thatling thought it would be funny to PR that without adding it in the changelog and yog merged it like the useless fucking morons they are. is this another joke? is this one of your fucking jokes like the time you sent me 30mb of nazi MLP futa porn that you had saved to your fucking hard drive nichlas? 

### PR DESCRIPTION
**Pull request by ghost**
Reverts yogstation13/Yogstation-TG#5180

read title, undocumented change, lying changelog, etc

:cl:
bugfix: Red slime potions have been fixed!
/:cl:

### CODE REVIEW

**Comment by Amelia0010** [comment]
>is this one of your fucking jokes like the time you sent me 30mb of nazi MLP futa porn that you had saved to your fucking hard drive nichlas?

1. Yes, it was one of my jokes

2. I didn't have it saved to my hard drive

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
This makes it do literally nothing

**Review by Amelia0010 — APPROVED** [review]
This makes it do literally nothing

**Comment by ThatLing** [comment]
This doesn't revert anything

**Pull request merged**
