### PR TITLE
removes the prisoner skirt

### PR DESCRIPTION
**Pull request by nesisknesis**
This is fetish content lets be frank

no member of security puts this on someone if it isnt with the intention of humiliating them

#### Changelog

:cl:  Identification  
imagedel: The prisoner skirt
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
>no member of security puts this on someone if it isnt with the intention of humiliating them

That is the point of the item existing.
Sec's last "fuck you" before putting the prisoner in perma.

**Comment by boodaliboo** [comment]
i like tih spr

**Comment by ynot01** [comment]
people check the gender before they put the skirt on or not

**Comment by Cinnamon-BonBon** [comment]
Against unban
-1

**Pull request closed without merging**
