### PR TITLE
Buffs Holotool, lets it start surgery, and fit in a toolbelt

### PR DESCRIPTION
**Pull request by Moltijoe**
Holotool is weirdly bad for how it's supposed to be the RD equivalent of the CMO hypospray which is amazing.
I've buffed it's speed by quite a lot and let it actually start surgery.

:cl:  
tweak: Buffs Holotool, lets it start surgery, and fit in a toolbelt
/:cl:

### CODE REVIEW

**Review by MajManatee — APPROVED** [review]
Yeah this looks fine.

Also can you make it fit in a toolbelt? That would be a game changer there.

**Review by ReddicusDragon — COMMENTED** [review]
Tested?

**Comment by Moltijoe** [comment]
> Tested?

curse you, my shitcode nearly got it.
Yeah i tested it, but for some reason despite being able to start surgery, it immediately starts to cancel the surgery rather than do the step

I'll fix it in a bit, just busy for the time being

**Comment by MajManatee** [comment]
maintainter btw

**Pull request merged**
