### PR TITLE
Adds a new toy to find in maint: the hyper-realistic snow globe

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Adds a new toy to random maint tables at the mythic level; the hyper-realistic snow globe

# Why is this good for the game?

I like bold faced references

# Testing

It works like all the other stuff

image

# Spriting

image

image

# Changelog

:cl:  
rscadd: Adds new toy
imageadd: Adds sprites for the new toy

/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
mind telling us what the reference is? without context it just be goofy

**Comment by missatessatessy** [comment]
I think it's supposed to be this
SnowglobeGoodsprings

**Comment by cowbot92** [comment]
> mind telling us what the reference is? without context it just be goofy

https://fallout.fandom.com/wiki/Snow_globe_(Fallout:_New_Vegas)

**Comment by cowbot92** [comment]
> I think it's supposed to be this SnowglobeGoodsprings

yes

**Review by Moltijoe — APPROVED** [review]
I dont understand the reference but okay

**Comment by Beeper-Skeeper** [comment]
> I dont understand the reference but okay

Its a fallout new vegas reference
you can find them around the world and their purpose is that you can give them to Mr. House for 2000 caps each

**Comment by cowbot92** [comment]
I dont have legal permission to use this

**Comment by N3D6** [comment]
> > I dont understand the reference but okay
> 
> Its a fallout new vegas reference you can find them around the world and their purpose is that you can give them to Mr. House for 2000 caps each

So that’s what those are

**Pull request closed without merging**
