### PR TITLE
makes basic sodas in cola vendors 2$ per and adds a new a slogan to reflect it

### PR DESCRIPTION
**Pull request by boodaliboo**
i find it ridiculous that a can of soda costs 10$ thats worst then amuesement park prices. due to finding a new supplier for ingredients nanotrasen has been able to make there sodas cheaper
new slogan "Thats cheap ass soda!"
#### Changelog

:cl:  
rscadd: Added a new slogan
tweak: tweaked prices
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
You know how much money it costs to bring those heavy Soda's all the way to a space station? All basic items on the station are at a premium

**Comment by boodaliboo** [comment]
These sodas are filled in the vendor for cheaper costs dumb Dunn

**Comment by HomocidlePancakes** [comment]
Inflation m8. They actually cost less then two modern dollars.

**Comment by boodaliboo** [comment]
Assistants are payed 10$ at a time

**Comment by ThatLing** [comment]
Just stop playing assistant and get a real job

**Comment by boodaliboo** [comment]
I play clerk mainly and I get vendor stuff for free

**Comment by boodaliboo** [comment]
Actually they get payed 5$ at a time

**Pull request merged**
