### PR TITLE
Jukeboxes will now be synced across all clients

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Instead of being sent the audio every time you get near and restarting the sound from the beginning, everyone is universally sent the audio at the same time and their volume is adjusted to not be muted when they are in range.

Tested locally

Moved megafauna music to CHANNEL_MEGAFAUNA so it no longer clashes

# Changelog

:cl:  
tweak: Jukebox audio is now synced across all clients
tweak: Jukebox volume will now be updated on process instead of having to restart the audio by walking away and re-entering
/:cl:

### CODE REVIEW

**Comment by Notamaniac** [comment]
Don't jukeboxes cause a little bit of lag when they load a song? Or was that fixed?

**Comment by maxion12345** [comment]
> Don't jukeboxes cause a little bit of lag when they load a song? Or was that fixed?

Sometimes I feel like the transition is smooth, and sometimes I get like a second of lag going near the jukebox. Might be a function of server lag or something similar

**Comment by Notamaniac** [comment]
I'll guess we'll see if someone decides to buy five juke boxes and starts playing songs to try and cause lag

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
not a bug fix please adjust changelog

**Comment by ynot01** [comment]
> not a bug fix please adjust changelog

adjusted

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
