### PR TITLE
glowshrooms no longer roundstart

### PR DESCRIPTION
**Pull request by ToGWtF**
### Intent of your Pull Request
being able to shit out 100 max potency glowshrooms within minutes of heaering about "black man in maint" is ass. this at least adds a few extra minutes to how long it takes to get 

reading the code is hard so ill write it here to you mutate them from liberty caps

#### Changelog

:cl:  

tweak: glowshrooms now have to be mutated into from liberty caps
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
> ### Intent of your Pull Request
> being able to shit out 100 max potency glowshrooms within minutes of heaering about "black man in maint" is ass. this at least adds a few extra minutes to how long it takes to get
> 
> #### Changelog
> 🆑
> 
> tweak: glowshrooms now have to be mutated into
> /🆑

and how do you mutate into these?

**Comment by ToGWtF** [comment]
liberty cap mushrooms. they have no other mutate and are the only mushroom that looks somewhat similar

also they are the lsd mushroom so making them mutate to literally glow is kinda in line with them being the "magic" mushroom

**Comment by boodaliboo** [comment]
> liberty cap mushrooms. they have no other mutate and are the only mushroom that looks somewhat similar
> 
> also they are the lsd mushroom so making them mutate to literally glow is kinda in line with them being the "magic" mushroom

put that in the desception

**Review by Hopekz — APPROVED** [review]
I let this marinate for 2 days. Positive reception.
Feel confident in this merge.

**Pull request merged**
