### PR TITLE
Heretic bugfixes/Desc update + IPC/Preternis love (you're welcome you robot bastards)

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Makes it so IPC & Preternis heretics can now heal on rust tiles when they purchase "Leeching Walk"

Adjusts Heretic Codex description to no longer reference depreciated alt+click function, now directs them to use Z

Makes it so heretics can get research point gain w/o having their book on them (like if you lost it)

# Why is this good for the game?

Fair playing ground for all of our races.

# Testing

I was forced to test the healing several times by punching myself in the face. It hurt. It works.

# Changelog

:cl:  

tweak: Adjusts Heretic Book Desc
tweak: Allows IPC & Pretenis (and robotic limbs) to heal on rust tiles
tweak: Allows heretics to gain points w/o needing book in bag
/:cl:

### CODE REVIEW

**Review by Moltijoe — APPROVED** [review]
yeah, that makes sense
honestly thought it was weird you were also touching the rod at the same time

**Comment by cowbot92** [comment]
> yeah, that makes sense honestly thought it was weird you were also touching the rod at the same time

I wanted to be NICE to them

**Comment by Moltijoe** [comment]
> I wanted to be NICE to them

you don't need to, no one else is, they're used to it by now

**Comment by cowbot92** [comment]
> > I wanted to be NICE to them
> 
> you don't need to, no one else is, they're used to it by now

well if anyone wants to add it, the code is the same as what I used for rust heretic's healing :^)

**Pull request merged**
