### PR TITLE
Removes horny photocoping: Trying to photocopy your ass now makes the photocopier say banned before gibing you and disconnecting you

### PR DESCRIPTION
**Pull request by alexkar598**
Removes horny posting

### CODE REVIEW

**Comment by ghost** [comment]
Doesn't even ping all of staff kek

**Comment by JamieD1** [comment]
image
image

**Comment by Hopekz** [comment]
funny "haha gib" PR
Just more things to break immersion.

**Comment by jcatjmeow** [comment]
Meme pr smh

**Comment by alexkar598** [comment]
plz merge

**Comment by patpol4** [comment]
ass.gib()

**Pull request closed without merging**
