### PR TITLE
Adds Mentors to the MOTD startup message

### PR DESCRIPTION
**Pull request by Hopekz**
Finally adds mentors to the MOTD
**Mentors are staff and they are appreciated.**

**OLD:**
----
image

image

**NEW:**
----
image

image

#### Changelog

:cl:  
rscadd: Added mentors to the startup MOTD. No longer just another way to oppress mentors!
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Config change, council input required.

@yogstation13/council

**Comment by Oakboscage** [comment]
Wouldn't exactly call them staff or appreciated but okay

**Comment by ShadowDeath6** [comment]
might want to put mentor application in that section as well

**Comment by HomocidlePancakes** [comment]
Add a separate line for them in MOTD, what they do and how to contact them instead of this “meme”. Also, you are fucking retarded for not figuring that out on your own.

**Comment by alexkar598** [comment]
Gave it long enough, i don't have the power myself to merge it it and it's being passed around from council to headcoder and back.

**Pull request closed without merging**
