### PR TITLE
Makes the CAMERA MEMORY TRACKER show BIGGER text

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

Remove this text and explain what the purpose of your PR is.

# Wiki Documentation

# Changelog

:cl:  
tweak: Camera memory tracker shows bigger text when alerting you now
/:cl:

### CODE REVIEW

**Review by ToasterBiome — DISMISSED** [review]
changelog

**Comment by Bibby0110** [comment]
> changelog

No

**Review by ToasterBiome — DISMISSED** [review]
changelog

**Review by ToasterBiome — DISMISSED** [review]
changelog

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
changelog

**Comment by JamieD1** [comment]
Changelog

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
