### PR TITLE
Changes Power Control Module to APC module for consistency

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

This changes the name of the power control module to APC module. That's it.

# Wiki Documentation

Ideally all instances of power control module would be changed to reflect the new name

# Changelog

:cl:  
spellcheck: Changed power control module to APC module
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
Its not mislabeled, its full name is Area Power Controller. So you can just type in APC to look for one in the protolathe.

**Comment by Altoids1** [comment]
This game relies on its acronyms for anyone with a <200 WPM typing speed to be capable of playing it effectively. Please reconsider.

**Comment by MajManatee** [comment]
The item in-game is called a power control module, hence the change.

**Comment by bruhlookatthisdood** [comment]
> The item in-game is called a power control module, hence the change.

rename the item in-game to a APC Module then ):<

**Comment by JamieD1** [comment]
> > The item in-game is called a power control module, hence the change.
> 
> rename the item in-game to a APC Module then ):<

I agree, do this.

**Comment by MajManatee** [comment]
Hopefully this will please our poor, arthritic players

**Review by adamsong — APPROVED** [review]

**Pull request merged**
