### PR TITLE
I&#39;d like it if our &#39;s didn't get replaced with &amp;#39;s

### PR DESCRIPTION
**Pull request by monster860**
It&amp;#39;s really fucking annoying when there&amp;#39;s the fucking &amp;#39;s get replaced with &amp;amp;#39;s in the #asay channel.

### CODE REVIEW

**Comment by Nickvr628** [comment]
bUt If We dOn&#39;t SaNiTiZe TeXt PeOpLe CoUlD hAcK.

**Comment by Ktlwjec** [comment]
i dont want hackers

**Comment by Time-Green** [comment]
its asay they probably couldnt even hack a tree

**Comment by k-k-karma** [comment]
&#39;

**Pull request merged**
