### PR TITLE
Removes the ability to recall the shuttle from the gang tool

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Security almost always lose on gang rounds, but if they manage to call the shuttle and keep it called despite every head being a gang head they deserve the win.
# Wiki Documentation
Gangs can no longer recall
# Changelog
:cl:  
rscdel: Gangs can't recall anymore
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
whats your ckey / discord? im curious

**Comment by Bibby0110** [comment]
Gang has a 30% winrate.
Don't think this is needed

**Comment by bruhlookatthisdood** [comment]
alternative: make it so you have to plug the tool into the communicatino console, possibly alerting the station and taking some time then it will recall the shuttle and you get the tool back? (if you want more nerf them make it also cost whatever points gangs use idk ive never played gangs)

**Comment by Darkstick** [comment]
the mysterious masked stranger going full vigilante with random rebalances
I may be falling in love

**Comment by stwordcitizen** [comment]
simplehorror try to make a good pr challenge (impossible)
fr though this is a bad idea since sec usually stomps gangs or the other gangs kill eachother so having a way to recall the shuttle is needed imo.

**Comment by Simplehorror** [comment]
> Gang has a 30% winrate. Don't think this is needed
@TheGamerdk 
Is this per gang or is it the gamemode win rate? Individual gangs have a win rate but almost every gang round ends in the destruction of security and one gang winning

**Comment by Moja10** [comment]
You should channel your powerful coding and PR energies into changes that focus more on helping things that need a hand to be better for the game, players, and gameplay as a whole, rather than trying to stamp out any sort of issue that might be perceived as imbalanced negatively. This game can never be really balanced, trying to balance it like its a MOBA is a fool's errand, while yes nerfs can be impactful positively, I am afraid that a change like this can just be a push towards making the gamemode feel neutered, when strong tools are lost and nothing is gained. 

There's a lot existing in the game that can bring a more positive experience, if it only had a helping hand towards such a goal. You have done so for several PRs, but you have also set your mind towards stamping out lots of things you see as a problem, without looking at it from just how it works in the context of the game as a whole. Strong things can exist, they make certain antags real threats, and any antag can be confronted by the crew by working together, and also lethal weapons.

**Comment by N3D6** [comment]
Please remove guns. I died once and I didn’t like it. Please

**Comment by N3D6** [comment]
When are you making blob take 2000 to reach critical mass?

**Comment by Bibby0110** [comment]
> Reference i

This is the % of rounds where any gang wins

**Comment by Simplehorror** [comment]
> When are you making blob take 2000 to reach critical mass?

Blob is underpowered

**Comment by Hopekz** [comment]
> Please remove guns. I died once and I didn’t like it. Please

> When are you making blob take 2000 to reach critical mass?

You're making yog staff look bad

**Comment by SomeguyManperson** [comment]
gangs like all other conversion/round ending antagonists need a way to delay the shuttle since their end goal requires chasing down the nuke disk (and regardless takes a long time of preparing defenses and etc)

**Comment by Simplehorror** [comment]
> gangs like all other conversion/round ending antagonists need a way to delay the shuttle since their end goal requires chasing down the nuke disk (and regardless takes a long time of preparing defenses and etc)

ok, convert a head and have him recall

**Comment by JamieD1** [comment]
Not needed, also Gangs should be removed

**Pull request closed without merging**
