### PR TITLE
singularity sword

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

example of function (old sprite)

new sprite

# Changelog

:cl:  
rscadd: Added the singularity sword
/:cl:

### CODE REVIEW

**Review by patpol4 — APPROVED** [review]
Map cool

**Comment by ynot01** [comment]
undergoing sprite changes

**Comment by LoliconSlayer** [comment]
It should grow progressively longer with each strike

**Comment by ynot01** [comment]
> It should grow progressively longer with each strike

it should switch stages each hit you're a genius

i might be too lazy for that though

and it probably wont look good because later stages are much much larger than 32x32

**Comment by LoliconSlayer** [comment]
If I can't hold a sword that's as long as a dimmadome hat why even use it

**Comment by Reed0506** [comment]
make tesla sword now

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
