### PR TITLE
Adds bar_kitchen, where Bar and Kitchen have swapped positions!

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
This is immensley dumb, and took too many changes for it to have ever been worth it but I have created an awful machination.

Currently, there is one small issue in that I had to move the spawn points for Bartender and Cook, and in this instance when this bar is loaded the bartender will have to minorly walk to his bar, and the cooks to their kitchen, but if any other bar is loaded the cooks will spawn in their kitchen and the bartender just infront of his counter.

From what I believe, there is no real way to fix this because bar choice is completed AFTER bartender spawns in, making it impossible to subvert, so this will have to do.

Another issue is that the left side of the diner is classified as "kitchen" to prevent the bartenders fire-alarm triggering the kitchen area, however this may buff cooks slightly. Good thing cooks cant decide to use this, and the bartender is the one who chooses.

image

# Changelog
:cl:  
mapping: Added bar kitchen to box
/:cl:

### CODE REVIEW

**Comment by Necrosium** [comment]
This looks fantastic, can't wait to try it

**Comment by Aquizit** [comment]
image

This is what is causing your check to fail, aside from the current merge conflict.

**Comment by azzzertyy** [comment]
theres also a door that should be part of the station passthrough that i missed, will have to fix before merging

**Comment by MajManatee** [comment]
Reopen when work continutes

**Comment by azzzertyy** [comment]
> Reopen when work continutes

???? its been a week since any changes were requested? its not stale at all?

**Comment by MajManatee** [comment]
then fix it and make it work
one week with no changes is all thats needed to close a PR.

**Comment by azzzertyy** [comment]
will reopen when im bored enough and redo it

**Pull request closed without merging**
