### PR TITLE
Ports beaker sprites, sounds, and cap code from shiptest

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Ports a few PRs surrounding beakers:

-  ["Resprites and Beaker (and Bottle) Lids" #31](https://github.com/shiptest-ss13/Shiptest/pull/31) by [triplezeta](https://github.com/triplezeta)
-  ["Bay clicking nosies 2: The clickening" #484](https://github.com/shiptest-ss13/Shiptest/pull/484) by [retlaw34](https://github.com/retlaw34) - Beaker handling and transfer sounds
-  ["Moves reagent fill code and adds caps to plastic water bottles" #46878](https://github.com/tgstation/tgstation/pull/46878) by [Urumasi](https://github.com/Urumasi)

Also refactored some vial code to make it better and have more customization options, like being able to add descriptions or bands of any color to them.

# Spriting
New Beaker Sprites:
image
image

Hypospray Kit:
image

Vial Labels:
image

Comically Large Vial:
image

# Wiki Documentation

Images will need to be updated. 

# Changelog

:cl:  triplezeta, Urumasi, RiyaMakary, retlaw34, nmajask
imageadd: New sprites for beaker
rscadd: Beaker Lids
tweak: vials can now use any color for the band, can be given a description, and can have the band/label settings copied over by having the vial with the settings you want in your offhand
soundadd: beakers now have transfer and handling sounds  
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
round 2: let change happen edition

**Comment by KillerOrcaCora** [comment]
Credit the spriters in the changelog!

**Review by KillerOrcaCora — DISMISSED** [review]
>:(

**Comment by nmajask** [comment]
> Credit the spriters in the changelog!

@KillerOrcaCora fixed

**Comment by VaelophisNyx** [comment]
The thing that rocks the most about the new beaker sprites is they don't look fucking weird and 100% sideways on a table; they look so much better, and don't even have clarity issues

**Comment by JamieD1** [comment]
My main issue is that they all look less opaque, beakers are supposed to be clear so you can see whats in them:
image

They look alot shinier and less clear.

**Comment by Ebin-Halcyon** [comment]
> My main issue is that they all look less opaque, beakers are supposed to be clear so you can see whats in them: image
> 
> They look alot shinier and less clear.

Glass in spess is generally blue, as making things a clear white is really hard for recognition in game, along with looking very meh in general. x-large beaker is a white as well, so making them all white would kind of muddy the recognition/tiers of each glass beaker.

Chems are overlayed anyway so there isn't a clarity issue either.

**Comment by JamieD1** [comment]
> > My main issue is that they all look less opaque, beakers are supposed to be clear so you can see whats in them: ![image]
> > They look alot shinier and less clear.
> 
> Glass in spess is generally blue, as making things a clear white is really hard for recognition in game, along with looking very meh in general. x-large beaker is a white as well, so making them all white would kind of muddy the recognition/tiers of each glass beaker.
> 
> Chems are overlayed anyway so there isn't a clarity issue either.

I mean Im not saying they need to be see through, im saying they are MUCH bluer and MUCH shinier.

**Comment by VaelophisNyx** [comment]
I will say they'd be going from bright cyan to a slightly deep blue
not that big a change?
shinier isn't totally bad as well, and as mentioned, there's no clarity issues

maybe they could be made 40% more transparent or something

**Comment by JamieD1** [comment]
@KillerOrcaCora

**Comment by KillerOrcaCora** [comment]
Gonna stick with the simplistic beakers we have now. Highly suggest making a new PR with the unique sprites I mentioned earlier and the excellent sound effects.

**Comment by cuackles** [comment]
Having talked with orca, Ident our previous art director and awaiting a awnser from Partheo, i have decided to re open this PR on the bases that this is an improvement to our current sprites, on a following PR i will dull out a bit of the shine that this sprites have as per request of jamie

**Review by cuackles — APPROVED** [review]
Art aproved 👍

**Comment by ToasterBiome** [comment]
Cornflakes

**Comment by nmajask** [comment]
> Cornflakes

Fixed

**Comment by JamieD1** [comment]
> Having talked with orca, Ident our previous art director and awaiting a awnser from Partheo, i have decided to re open this PR on the bases that this is an improvement to our current sprites, on a following PR i will dull out a bit of the shine that this sprites have as per request of jamie

Can you show me the new sprites

**Comment by cuackles** [comment]
> > Having talked with orca, Ident our previous art director and awaiting a awnser from Partheo, i have decided to re open this PR on the bases that this is an improvement to our current sprites, on a following PR i will dull out a bit of the shine that this sprites have as per request of jamie
> 
> Can you show me the new sprites

They are on the PR, or you mean the ones with dulled out colors? If it's the second thing i will get to it later today now that my PC is working properly

**Comment by JamieD1** [comment]
Unfortunately going to agree with Orca, some of these sprites are obviously better but some just dont cut it im afraid, suggest you atomize it and make a new PR with changes suggested.

**Pull request closed without merging**
