### PR TITLE
[BOX] Revamps the shipbreaking area

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

chrome_jF4uSqzyKF

# Why is this good for the game?

- gives it an actual door instead of tiny fans
- makes it look better

# Changelog

:cl:   
mapping: Revamps the box shipbreaking area
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
with the 1 tile space in the door to space u wont be able to drag the engines in, can we get something like what cargo has for the crates?

**Comment by Mqiib** [comment]
The point of the recycler outside was so that you could recycle the engines. With this setup, doing that is impossible, and it's also a pain in the ass to get all of the random junk broomed into the recycler.

**Review by AMyriad — CHANGES_REQUESTED** [review]
image

I suggest adding these:
- Shadows to those stairs so they look less flat (see other stairs used in the map)
- Adding a third yellow-box decal to the right-most suit storage for consistency
- A security camera or two in the room since it seems to be missing one (the circled empty wall is one example)
- Extending the airlock room to at least 2 tiles long or more like in the example shown. Others have pointed out that it may be an inconvenience when dragging large items back inside to be scrapped.

also nice PR

**Comment by Mqiib** [comment]
> image
> 
> I suggest adding these:
> 
> * Shadows to those stairs so they look less flat (see other stairs used in the map)
> * Adding a third yellow-box decal to the right-most suit storage for consistency
> * A security camera or two in the room since it seems to be missing one (the circled empty wall is one example)
> * Extending the airlock room to at least 2 tiles long or more like in the example shown. Others have pointed out that it may be an inconvenience when dragging large items back inside to be scrapped.
> 
> also nice PR

Extending the airlock isnt enough. I, for one, don't plan on waiting through 20 airlock cycles just to get rid of the engines

**Comment by cowbot92** [comment]
> > image
> > I suggest adding these:
> > 
> > * Shadows to those stairs so they look less flat (see other stairs used in the map)
> > * Adding a third yellow-box decal to the right-most suit storage for consistency
> > * A security camera or two in the room since it seems to be missing one (the circled empty wall is one example)
> > * Extending the airlock room to at least 2 tiles long or more like in the example shown. Others have pointed out that it may be an inconvenience when dragging large items back inside to be scrapped.
> > 
> > also nice PR
> 
> Extending the airlock isnt enough. I, for one, don't plan on waiting through 20 airlock cycles just to get rid of the engines

engine problems will be resolved with https://github.com/yogstation13/Yogstation/pull/22045

**Review by AMyriad — APPROVED** [review]
issues addressed, feel free to improve it from here if you'd like

**Pull request merged**
