### PR TITLE
Updates the base captain uniform sprites.

### PR DESCRIPTION
**Pull request by nesisknesis**
Original: 
image

New:
image

#### Changelog

:cl:  Identification  
imageadd: The captain's base uniform has been visually improved.
/:cl:

### CODE REVIEW

**Comment by Alexandria404** [comment]
very nice

**Comment by Marmio64** [comment]
i like original more and also the new carapace looks like its made out of leather IMO

**Comment by nesisknesis** [comment]
how does it look like leather

**Comment by Marmio64** [comment]
> how does it look like leather

it looks much smoother and more like a jacket than armor, and the little yellow dots that persisted there now kind of look like messed up buttons. Either way, I PERSONALLY do not like it and that is my opinion,.

**Comment by alexkar598** [comment]
How does this compare with the other blue like clothing for capt

**Comment by nesisknesis** [comment]
i'm not gonna compare it with every other captain clothing but the formal jacket looks something like this, just imagine the rest of the uniform is blue

image

**Comment by Partheo** [comment]
I like it overall but I think there could be more definition on the carapace (it does look smooth) and more of a color contrast between the clothing and the carapace- the two look visually similar rather than being distinct.

**Comment by nesisknesis** [comment]
image

**Comment by Bibby0110** [comment]
looks flat

**Comment by Marmio64** [comment]
guess im not wearing the base captain uniform anymore, despite the carapace being my favorite piece.

**Pull request merged**
