### PR TITLE
[YogsMeta] Corrects R&D door access

### PR DESCRIPTION
**Pull request by Aquizit**
# Oh I deleted the wrong line

Changes R&D door from TOX and ROBO_CONTROL to just RESEARCH so the Network Admin can get in there like they're supposed to

# Changelog

:cl:  
tweak: [Meta] Tweaks R&D door access so Network Admin can get in
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
changelog at least

**Comment by Aquizit** [comment]
uhhh -- ok that is very strange considering on discord it's all there but it didn't save -- weird ok lemme retype it up

**Review by patpol4 — CHANGES_REQUESTED** [review]
some box changes made their way in here somehow

**Comment by patpol4** [comment]
I'll fix it in the big one

**Pull request closed without merging**
