### PR TITLE
[URGENT] Fixes data corruption on Boxstation

### PR DESCRIPTION
**Pull request by UselessTheremin**
for the past few rounds the map data has been corrupted on box, and it's been lagging the game to shit. SPEEDMERGE

:cl:  
bugfix: fixes corrupted map data on boxstation
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
before
image
after
image

**Comment by UselessTheremin** [comment]
> before
> image
> after
> image

yeah the mapdiffbot is fucked rn with too much requests, the creator was talking about it on coderbus

**Comment by ChesterTheCheesy** [comment]
Map sure becomes extremely spacious out of the sudden.

**Comment by JamieD1** [comment]
....
image

**Comment by patpol4** [comment]
How did i not notice this before, thanks Theremin

**Comment by alexkar598** [comment]
not funny didnt laugh

**Pull request closed without merging**
