### PR TITLE
Purchasable autosurgeon for 5TC

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

5TC, infinite use autosurgeon

Very obvious sprite and name

# Spriting
Added autoimplanter_red

# Changelog

:cl:  
rscadd: Added the Reusable Autosurgeon to the uplink for 5TC
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
Let it be used for illegal research?

**Comment by ynot01** [comment]
> Let it be used for illegal research?

all autosurgeons can be used for illegal tech

**Comment by cuackles** [comment]
i would like to see it in game cus i have a bit of the impresion that it might be to light but i wanna confirm it before requesting any changes

**Comment by ynot01** [comment]
> i would like to see it in game cus i have a bit of the impresion that it might be to light but i wanna confirm it before requesting any changes

**Review by ReddicusDragon — APPROVED** [review]
**THIS IS A CODE REVIEW THIS IS A CODE REVIEW THIS IS A CODE REVIEW**

literally nothing has changed except art

**Comment by Addust** [comment]
tg has a special syndie autosurgeon sprite, a lot more menacing

**Review by cuackles — APPROVED** [review]

**Pull request merged**
