### PR TITLE
Adds 4 variations to the Arrivals Lounge

### PR DESCRIPTION
**Pull request by Hopekz**
**More Spice continued!**
All feedback is considered (so please speak up if you don't like a variation)
(See Variation 3 modification below as this screenshot is not accurate anymore)
Captureall

Variations:
--------
1:

2:

3: MODIFIED per Monster's suggestion
image
4:

#### Changelog

:cl:  
rscadd: Added 4 variations to the Arrivals Lounge!
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
I, personally, do not like number four and six. But like all others

**Comment by Hopekz** [comment]
> I, personally, do not like number four and six. But like all others

Do you mean don't like it beyond improvement (remove them) or is there something to modify inside them?

**Comment by monster860** [comment]
yes let's just have a random ass bathroom in them iddle of a hallway. I love it.

**Comment by Hopekz** [comment]
> yes let's just have a random ass bathroom in them iddle of a hallway. I love it.

Lol ok I'll remove it

**Comment by yacabo** [comment]
Number 4 doesn't feel right being there. If there should be a ball pit it would be in the holo deck, not the first thing someone should see when walking into the station. Number 6 shouldn't be there since that there's a bathroom there's an actual bathroom a mere thirty meter walk from the lobby. So I'd say remove them.

**Comment by Hopekz** [comment]
Variations 4 and 6 are being removed next commit.

**Comment by Hopekz** [comment]
Modified variation 3 per Monster's feedback:
Added window border
image

**Review by monster860 — CHANGES_REQUESTED** [review]
can you put more descriptive names than just "lounge 1" "lounge 2" etc

**Comment by Ratvar** [comment]
Can you add a version that is just a toilet booth

**Comment by Hopekz** [comment]
> Can you add a version that is just a toilet booth

Funny you should mention that.
A bathroom was a variation I removed from this PR.
If people think this variation would benefit this PR lmk and I'll add it back in.

**Comment by Hopekz** [comment]
Also removed a ball-pit variant just in-case there is an interest in this one as well.

**Comment by fluffe9911** [comment]
The ball pit one would work good as a replacement aut for the boxing ring if you ever plan on adding varations for that

**Comment by Hopekz** [comment]
> The ball pit one would work good as a replacement aut for the boxing ring if you ever plan on adding varations for that

Oh I didn't even think of making variations for that! Sure!

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
Please remove 3 or tweak it I hate it so much, it's the mix of the full airlocks and the thin windows (no windows were also bad so don't think of reverting that). 4, as much as I love the vaporwave style for things like the bar, looks really out of place in my opinion. It's the floor (statue and tables etc are fine).

**Comment by Hopekz** [comment]
Have more time to work on this and will be able to support it if merged so reopening.

**Comment by Hopekz** [comment]
You know this PR is fucked when I have merge conflicts in the shoes and feet files.
Will have to recreate this one as well.

image

**Comment by Ktlwjec1** [comment]
I'll close this since it's being remade.

**Pull request closed without merging**
