### PR TITLE
Adds a basic survival weapon to escape pods

### PR DESCRIPTION
**Pull request by SomeguyManperson**
This addresses one of the two main "my pod landed somewhere stupid and then I died" scenarios people often find themselves in (the other being landing directly in the middle of a lava lake) by adding a couple spearguns to each pod's emergency safe. The "spears" deal lackluster damage to anything that isn't from lavaland but will deal slightly less lackluster damage to lavaland fauna.

:cl:  Theos
rscadd: adds a fancy speargun to escape pods so landing right next to a goliath isn't instant death
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
This pr is quite useless if you ask me
Faunas:
Watchers: good luck getting close to reload your shit
Legion: pickaxe does a better job
Goliath: quite grindy as you need to shoot,bait him away,reload,rince and repeat
Any megafauna: no...just no

**Comment by SomeguyManperson** [comment]
each speargun comes with a spare spear, and they can hold up to 2 spears at once, so each gun can deal 50 damage before you need to retrieve your spears
firing off both spearguns at a watcher and rushing it with a pickaxe results in much less damage than just rushing it with a pickaxe. Fighting a watcher with another person is probably much easier.

firing one speargun at a legion leaves enough health you can kill it with your pickaxe in two hits. When using a damage modded KA, the strategy is just about the same. Two spearguns will kill the legion before it can start spawning heads.

kiting a goliath alone takes some time or is risky but it's better than fighting one with a pickaxe, fighting a goliath with two people is likely much easier.

Taking out a tendril with a speargun is suicidal and it's not meant as a functional weapon against megafauna.

In general, the speargun is easier to use when fighting in pairs. Escape pods have enough supplies for two people, so this isn't much of a problem. It's not meant to be on-par with a KA or crusher, it's meant to be used when you can't get anything better.

**Comment by ghost** [comment]
spearguns already exist in the code

**Review by Amelia0010 — DISMISSED** [review]
You know none of these files are included in the .dme, right?

**Comment by SomeguyManperson** [comment]
The speargun in the code uses thrown items/pneumatic cannon stuff which feels nasty for something that isn't built to be shot at people and results in the projectile needing to be unthrowable to make the gun useful

**Comment by Amelia0010** [comment]
Not like it's any harm

**Pull request merged**
