### PR TITLE
New virology symptom: Superficial healing

### PR DESCRIPTION
**Pull request by Majkl-J**
# Document the changes in your pull request

Partial port of: https://github.com/BeeStation/BeeStation-Hornet/pull/1381

A symptom that heals brute and burn, or toxin (If there is no brute/burn) when you are above 90% health.

Can be improved to make it 70%, however this comes with the disadvantage of stamina damage when healing, slowing you down.

# Why is this good for the game?

An interesting (And fairly weak) alternative to other healing symptoms that comes with a disadvantage when improved. Read the code comments (The stuff after //) for any details about the whys.

# Testing
Seemed to work fine when tested but knowing you people you'll probably manage to break it. Actually I have 24 more hours before this can be merged so I'll test more - Still seems ok

# Wiki Documentation

Virology guide will need a new symptom

# Changelog

:cl:  
rscadd: Virology: New symptom, superficial healing
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
god bless you for this

**Comment by MajManatee** [comment]
yes just what we need, the whole crew regening health at all times

**Comment by 00ze-cyclone** [comment]
we have way too many healing symptoms and RDS already fit the niche of healing not requiring external factors but with a price.

**Comment by Majkl-J** [comment]
> yes just what we need, the whole crew regening health at all times

- all times

Do you actually read the code or pr description? Either make a proper review as to why this is bad, or go cry somewhere else. Maintainer my ass

**Comment by boodaliboo** [comment]
> we have way too many healing symptoms and RDS already fit the niche of healing not requiring external factors but with a price.

rds can kill you what are you talking about unless you meet its thresholds its a easier way to kill someone then heal them

**Comment by Maia-J** [comment]
> yes just what we need, the whole crew regening health at all times

Alright since you CLEARLY didn't like me complaining about your lack of integrity: Read the PR description and provide actual reasoning. For a maintainer this is a terrible response.

**Comment by MajManatee** [comment]
No :)

**Comment by boodaliboo** [comment]
> > yes just what we need, the whole crew regening health at all times
> 
> * all times
> 
> Do you actually read the code or pr description? Either make a proper review as to why this is bad, or go cry somewhere else. Maintainer my ass

based their bitching because its the 4th attempt oh no trying to add something and tweaking it everytime, im sorry your not getting legit criticism their mostly directing that towards rants at me on the discord lol :)

**Comment by Maia-J** [comment]
Made it level 3 as there aren't many symptoms on that level and it is pretty minor

**Comment by boodaliboo** [comment]
> Made it level 3 as there aren't many symptoms on that level and it is pretty minor

awesome thats perfect

**Comment by boodaliboo** [comment]
if you have a issue with this pr leave actual criticism please on what exactly is the issue instead of ranting to me about a pr i didnt make. but as someone who plays viro a ton this virus is not strong it isnt even close to what you can do with other symptoyms and  in a majority of cases 1 hit with most items is going to bring you below 90 health making it not that viable, if anything maybe a cooldown if somebody is constantly taking damage but then heals back up to 90+ so it isnt like constantly something that can bring your health up fast, maybe even have it be something activatable compared to passive, i think it being activatable would also allow you to add a cooldown easier, and most peoples issue with it is that it doesnt have a condition to work. thanks again for reworking this.

**Comment by ehj236** [comment]
If I might add to this as a viro main, Superficial healing in itself is pretty situational, that being said it is the Least situational virus symptom that I can see when compared against every other healing symptom. Regen Coma requires you to be near crit, crit, nearly dead or sleeping. Tumors give you toxin damage and require a start-up time. RPS requires nutriment(and or blood) which can be a issue if there isn't a proper chef. Nocturnal Regeneration requires the station being dark 99% of the time, Starlight Condensation requires you to be near the edge of the station's windows or in space and Tissue hydration needs water. What does this symptom need? "**You can't be damaged too much"** **That is so simple and easily it could be Meta amongst all symptoms and I think even for the healing power, conditions and thresholds you gave it it is Still overpowered in my eyes** even if it doesn't heal all damage at once how often are you really dealing with more than one or 2 damage types and how often is it that you would most likely be dead below 70% rather than around 20-30%(regen coma)? Chances are if you are already near 50% health you have lost the battle and will be executed or captured by who or whatever is already aggroed onto you. This symptom is 99% perfect.

**Comment by Maia-J** [comment]
> If I might add to this as a viro main, Superficial healing in itself is pretty situational, that being said it is the Least situational virus symptom that I can see when compared against every other healing symptom. Regen Coma requires you to be near crit, crit, nearly dead or sleeping. Tumors give you toxin damage and require a start-up time. RPS requires nutriment(and or blood) which can be a issue if there isn't a proper chef. Nocturnal Regeneration requires the station being dark 99% of the time, Starlight Condensation requires you to be near the edge of the station's windows or in space and Tissue hydration needs water. What does this symptom need? "**You can't be damaged too much"** **That is so simple and easily it could be Meta amongst all symptoms and I think even for the healing power, conditions and thresholds you gave it it is Still overpowered in my eyes** even if it doesn't heal all damage at once how often are you really dealing with more than one or 2 damage types and how often is it that you would most likely be dead below 70% rather than around 20-30%(regen coma)? Chances are if you are already near 50% health you have lost the battle and will be executed or captured by who or whatever is already aggroed onto you. This symptom is 99% perfect.

Being at 70-90% with the virus improved will deal enough stamina damage to severely slow you down, making it terribly unviable for combat and only really viable for workplace injury, which basically means you save yourself from the inconvenience of going to medbay at the cost of being slow. Above 90% is basically only useful for minor cosmetic damage from basically anything, and considering any traitor/sec weapon deal damage above this threshold, it is again combat unviable. It won't save you from death like regen coma might. It won't provide constant healing with no downside to you. It only saves you from the minor inconvenience of going to medbay, which you can also just avoid by standing near a starlit window with starlight condensation.

Also the solution to this would be: Testmerge it. See how it goes. If it turns out meh, it can be tweaked, if it turns out somehow OP (Impossible), can always just close this

**Comment by Maia-J** [comment]
And yes, I am balancing this around combat viability, as I believe this place to be equivalent to tg in terms of anything healing related.

**Comment by SomeguyManperson** [comment]
To summarize all the reasons this is bad

> virology healing symptoms require some amount of input to activate, generally being something situational causing an alteration to the user's playstyle. This one doesn't do that.

> healing symptom uptimes are therefore decided by the user i.e. if you have starlight condensation, you can choose to stay near windows to space more often to keep your free healing coming. This one is entirely dependent on incoming damage being within a very small range, to the point it is unlikely to ever actually be helpful, as in any situation it would be active, another healing symptom could do its work faster.

> healing symptoms, being semi-passive, tend to *not negatively impact their user while active.* This is half the reason RPS and metabolic boost aren't used (and over half the reason RPS is awful). If this symptom is for instance statted to be active for more than 30 seconds out of a round, the user is now stuck with constant stamina damage/slowdown if they are so much as sneezed on.

> healing symptoms (and by extension all symptoms) take up a symptom slot in their virus. Each virus can only have 6 symptoms, which will generally be split between positive symptoms and stat boosters to reach thresholds for the positive symptoms. This is not worth one of those slots.

**Comment by Maia-J** [comment]
I am hearing two conflicting sides of this which just makes me wanna ask for a testmerge more. If there's players calling this op and players calling it shit maybe it needs further testing to see how this can be made to work

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
