### PR TITLE
WIP Detective cyborg

### PR DESCRIPTION
**Pull request by Hopekz**
Detective cyborg:
--------

EDIT:
Haven't had much free time for this project lately.

Progress is getting slow so **I'm closing this WIP** and will instead work on it passively over time to reopen near completion much like the Accent project.

If anyone wants to contribute you may reach out to me otherwise I don't have an ETA as to when this will be near completion as it is a big open ended project for me.

--------

I have already gone ahead and created the sprite that I will use for these borgs before reopening this PR the first time.
I tried to go for some kind of cyborg detective dog.

unknown 1

DetectiveBorg 1

**modules (updating this as I go):**
-------
- flash
- ziptie dispenser (**not zipties so unable to cuff.** But emaggable to cuff like regular zipties)
-  **forensic nose**
This is your forensic scanner built into the Cyborg's nose.
It is not ranged unlike a regular scanner but takes advantage of the Cyborg's computer to process results much quicker.

- remote access to forensic/medical database (read-only) (not implemented yet)
- wanted poster
-  compli-o-nator
-  white crayon
- emag item (.38 pistol w/ .38 bullets) (Manually reload from speedloading module)
- emag item (.38 pistol speedloading module) (Reload in recharge station)
-  fedora tipper (not implemented yet)
- body bag fabricator
- Evidence bag (credit to Lyis for idea)
- pinpointer (does this belong here?)
- health analyzer
- **Cyborg police baton module**
Safety precautions prevent the Cyborg from swinging this with full force.
At the moment does half damage and half stun of a normal wooden baton. 
It cannot be used to zip tie or even arrest (as the cooldown to re-apply stun is longer than the stun lasts).

UPGRADES:
-------
(probably won't have time for most of these but I wanna put them down)

- [ ] mood actuator (see Idinuum's comment). Hopefully will be able to finish something like this otherwise future PR
- [ ] smoke kit. Lets the robot smoke whatever cig it chooses. Also gives a zippo lighter
- [ ] Nice upgraded scanner where it'll just tell the borg who prints/blood it is if it is on the manifest (if this exist it can be debated whether or not this is a starting option)

TO DO:
------
- [x] Start coding
- [x] Create a sprite for the Detective Borg
- [ ] Actually implement the sprite I created
- [ ] Make Detective borgs a config option just-in-case they should be disabled.
- [x] Make basic modules
- [ ] Make the ziptie fabricator module
- [x] make the gun work
- [x] rework the gun to be cyborg version. (shoot out casings etc)
- [ ] Make a module to use the forensics console or medical records on the go
- [x] Add more checkboxes because Alex seems to not like it
- [x] ^^^

I want to do but probably won't have time (if you want to contribute to this project) :
-----
- [ ] Paper module. Basically a mix module that lets the borg write something and print it out and organize it in a memory folder (a.k.a normal folder but because borg can't drop it it's memory).  Credit to SaraToubi for the idea
- [x] do better for sprites
-  hopefully, have enough time to make some upgrades from the upgrade list. 
- [ ] Give Detective borg its own icon  (includes removing placeholder sec icons because the detective is not a security officer)
- [ ] Nice upgraded scanner where it'll just tell the borg who prints/blood it is if it is on the manifest
- [ ] get a sprite for the ziptie dispenser module 
- [ ] "Give it a joke verb that lets it "drink" it's own whiskey, and it just spills down their faces and on the floor" - Darkstick

image
image

#### Changelog
No changelog yet will make it as I go
:cl:  Hopek
rscadd: Detective cyborg has been added.
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
Cyborg upgrade called mood actuator or something, makes the current room monotone while causing noir jazz to play. Ends when the borg exits the room and has a cooldown to prevent repetitive use.

I think TG had this effect for the det's office but I can't be sure.

**Comment by Saratoubi** [comment]
You should add either give this borg a whiskey synthesizer or maybe let it be fed whiskey to change it's speech. Great idea tho.

**Comment by Potototatoh** [comment]
add vape functionality

**Comment by MegaEmpirical** [comment]
Ziptie dispenser is actually pretty cool.

**Comment by Saratoubi** [comment]
What about evidence bags? Maybe someone will actually use them for once.

**Comment by yacabo** [comment]
Flashes have a limited use, even for borgs, so if you intend that to be a regular means of offensive capabilities then you might want to adjust that, though I also recognize that it might not also be a regular offensive tool

**Comment by MegaEmpirical** [comment]
I use them you bastard. I write up case notes and organize my evidence in folders. You fucking savage.

If the borg can't print out case notes this is a bust.

**Comment by Hopekz** [comment]
> You should add either give this borg a whiskey synthesizer or maybe let it be fed whiskey to change it's speech. Great idea tho.

> I write up case notes and organize my evidence in folders. 

>What about evidence bags? Maybe someone will actually use them for once.

Added to to-do. 
Hopefully will have time to finish them idk its already starting to look like a big-ish project

**Comment by Readystorm546** [comment]
Like this idea instead of just straight up yeeting sec borgs #7519

**Comment by overlord12345** [comment]
a borg that can smoke and tip its fedora is the best idea

**Comment by Darkstick** [comment]
Give it a joke verb that lets it "drink" it's own whiskey, and it just spills down their faces and on the floor

**Comment by Potototatoh** [comment]
vape

**Comment by Hopekz** [comment]
> vape

code or get a nerd to code the smoke kit module and you can add the vape functionality yourself!

**Comment by maxion12345** [comment]
Maybe have the .38 slowly regenerate ammo over time. The .38 isn't the best gun, and if your emagged and need to do combat against security or whatever, you'll run out of ammo before they drop dead. Also, what about .38 TRAC as a starting pistol? Then emags into an actual .38

**Comment by Hopekz** [comment]
I'm closing this PR per ASV's "executive decision" to keep the secborgs in our codebase.
With secborgs remaining in our codebase this detective borg has no place to exist as I don't want another sub-par borg.
As long as we keep the secborg it will always be the go-to option as it is the superior choice.

**Comment by yacabo** [comment]
Oh come on, lots of people still want it with or without the sec borg, reopen it

**Comment by alexkar598** [comment]
@yacabo you can takeover the code, its licensed under an open source license and you have no obligation to leave this code dead

**Comment by alexkar598** [comment]
img
OP is also chill with people taking his code, so moral reasons can go out of the window

**Comment by MegaEmpirical** [comment]
The vote was for removing sec borgs, not replacing them. I voted no as I'm against removing them since they could still be admin enabled.

The vote should have been to replace them

**Comment by Ktlwjec1** [comment]
if anyone ever revives this, add this for det borg -
monster860 for councilToday at 05:09
make a "toxin injestion tubule" that injests alcoholic beverages so that secborgs can get drunk.

**Comment by Hopekz** [comment]
**Reopening up this PR**
With the recent changes to how secborgs get introduced into the game, I now feel that there is a place for detective borgs.

I have already gone ahead and created the sprite that I will use for these borgs before reopening this PR.

**Comment by yacabo** [comment]
Wew

**Comment by Hopekz** [comment]
Haven't had much free time for this project lately. 
Progress is getting slow so I'm closing this WIP and will instead work on it passively over time to reopen near completion much like the Accent project.

If anyone wants to contribute you may reach out to me otherwise I don't have an ETA as to when this will be near completion as it is a big open ended project for me.

**Comment by deathslayer2481** [comment]
Chonky

**Pull request closed without merging**
