### PR TITLE
New Triage Shuttle

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

A shuttle with expanded medical facilities for an evac with many severe injuries. Comes with a multitude of stasis beds, some sleepers, a cryotube system, and plenty of kits. As well as room for people to move patients around in without interfering much with surgeries or other treatment.

image
(Note: I did use the "loaded" version of the defib mounts, and tested that they're loaded and powered and able to be used in the space above the stasis bed.)
# Wiki Documentation

A new shuttle would need to be added to the list.

# Changelog

:cl:  
rscadd: New Triage Shuttle, for medical heavy evacs. 
mapping: A new map, which just so happens to be the triage shuttle. What a shocker.
/:cl:

### CODE REVIEW

**Comment by Aquizit** [comment]
I do not know why the check failed everything compiles fine on my end.

**Comment by Moltijoe** [comment]
wow, all these stasis beds, sleepers, and even cryo tubes
am i just blind, or do i not even see a single defib though

**Comment by Aquizit** [comment]
Nope revival surgery only! 😡

(My god i can’t believe i missed the defibs of all things, will get it when out of bed.)

**Comment by ToasterBiome** [comment]
This is significantly stupid and very much funny. I cant wait to explode that top little area.

**Review by ToasterBiome — APPROVED** [review]
Map is fine

**Pull request merged**
