### PR TITLE
Adds Transit Shuttle icemoon ruin

### PR DESCRIPTION
**Pull request by alao3alao3**
See #10656 
Apparently you need to commit to master in order to contribute to the icemeta project

##### Changelog

:cl:  
rscadd: Adds icemoon transit shuttle ruin  
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Not going to lie, this looks very blocky(square) and not destroyed at all like a ruin theoretically should be. I'll try making it a bit more ruin-y tomorrowish

**Review by patpol4 — APPROVED** [review]
Actually you know what, this is fine

**Comment by patpol4** [comment]
I might add some tinydans later though

**Comment by patpol4** [comment]
This is ready to merge, i just need the HC to click a button because our settings for config flags are bad. Don't want to bother him but feel free to ping if you really need this merged

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
