### PR TITLE
Lets robotic limbs be self amputated

### PR DESCRIPTION
**Pull request by Moltijoe**
Weird they cant do this, must have been a random mistake someone made in a PR at some point

:cl:  
tweak: robotic limbs can be self amputated now
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
I believe it was Nyx doing that thing they did where no more augmentation for inorganic species because "uhh bypassing racial weaknesses"
Still think that was a completely psychotic take though so this is good

**Comment by LazennG** [comment]
> I believe it was Nyx doing that thing they did where no more augmentation for inorganic species because "uhh bypassing racial weaknesses" Still think that was a completely psychotic take though so this is good

i checked earlier and unless i misread it, nyx didn't touch this surgery at all, just augmentation

**Comment by VaelophisNyx** [comment]
> I believe it was Nyx doing that thing they did where no more augmentation for inorganic species because "uhh bypassing racial weaknesses" Still think that was a completely psychotic take though so this is good

fun how people are blaming random shit on me baselessly long after I leave 👍

anyway yeah no this wasn't my doing at all and has been an issue for a long time

**Comment by Moltijoe** [comment]
> fun how people are blaming random shit on me baselessly long after I leave 👍
> 
> anyway yeah no this wasn't my doing at all and has been an issue for a long time

Yeah, i didn't think it was caused by you, i assumed it was just something that was never noticed until Lazenn's arm got added and IPC or Preterni started wanting to do self surgery to add it.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
