### PR TITLE
Adds new station trait: Moonscorch

### PR DESCRIPTION
**Pull request by cowbot92**
Special thanks to @Chubbygummibear for figuring out how to make it not reset when you exit/enter the z-level

# Document the changes in your pull request

Adds a new station trait with relatively low weight to ensure that it doesn't get too stale too fast.

# Why is this good for the game?

I feel like we haven't done anything much with our backdrop of space. Hopefully this makes it a tiny bit more interesting at times. I also will try to expand on this in other future ways to connect it to other things we already have.

# Testing

Yes it somehow works, I tested it with 1000 weight, then the proper weight to make sure that it wasn't just on all the time

# Spriting

moonupdate2

# Wiki Documentation

yup

# Changelog

:cl: 

rscadd: Adds new station trait: Moonscorch

/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
if you animate it, it would be funnier lol

**Comment by Xoxeyos** [comment]
Fucking awesome. Maybe add a rare variation of the Logic Moon?

**Comment by cowbot92** [comment]
> Fucking awesome. Maybe add a rare variation of the Logic Moon?

Could you send me a picture of what you mean?

**Comment by cowbot92** [comment]
> if you animate it, it would be funnier lol

Animate it in what way?

**Comment by ShoziOffical** [comment]
> > if you animate it, it would be funnier lol
> 
> Animate it in what way?

Make its mouth open up and close showing its core

**Comment by cowbot92** [comment]
> > > if you animate it, it would be funnier lol
> > 
> > 
> > Animate it in what way?
> 
> Make its mouth open up and close showing its core

Unfortunately animating that through the parallax might get a little... fucky, is there an existing animation of it already from the game?

**Review by cuackles — APPROVED** [review]

**Comment by ShoziOffical** [comment]
> > > > if you animate it, it would be funnier lol
> > > 
> > > 
> > > Animate it in what way?
> > 
> > 
> > Make its mouth open up and close showing its core
> 
> Unfortunately animating that through the parallax might get a little... fucky, is there an existing animation of it already from the game?

Not that i know of

**Review by Moltijoe — APPROVED** [review]

**Comment by MajManatee** [comment]
would be cool if it got closer as the shift went by

**Comment by cowbot92** [comment]
> would be cool if it got closer as the shift went by

this might be possible but outside the scope of this PR

**Pull request merged**
