### PR TITLE
Fixes and Buffs Shadowling Glare so it now stuns up to 4 tiles also lasts a bit longer

### PR DESCRIPTION
**Pull request by fluffe9911**
Broken atm and kinda sucks so a small buff wont hurt

### CODE REVIEW

**Comment by Nickvr628** [comment]
Now it stuns EVERYONE in a 4 tile radius? Because that sounds broken as fuck.

**Comment by fluffe9911** [comment]
No it still only stuns one person now it can just stun them from up to 4 tiles lol

**Comment by Nickvr628** [comment]
Ok sounds cool. I think it still might be a bit high but playtesting will determine that.

**Comment by Ludox235** [comment]
Please merge this the sling's glare sucks so hard it feels like even if i'm 1 tile away they wont get stunned

**Comment by Time-Green** [comment]
used to be 7 tile radius so this seems fair enough

**Comment by ghost** [comment]
shadowling is powerful enough as is, it doesn't need any further buffs

**Comment by SomeguyManperson** [comment]
give the stun like 10 or 20 more deciseconds instead of the range buff if you want it to be more useful.

**Pull request merged**
