### PR TITLE
adds lederhosen and german folk hat (wee hoo)

### PR DESCRIPTION
**Pull request by nesisknesis**
aads ledurhoesen und gherhmann volk haat to der otodrobe

vhy shood vis be aaded you maay be aasking?

vell, vis vas shuggested by Cow Maattress in spriter channel, so i aad it vee hoo

picktures:

image
image
image

vee hoo

i caant vhink of a descripshon so suggeshons vould be greatly aappreciated

:cl:
rscadd: adds lederhosen und german folk hat to autodrobe
/:cl:

### CODE REVIEW

**Comment by nesisknesis** [comment]
vhat der fuck

**Comment by fluffe9911** [comment]
oof seems you made it on a outdated version of yogstation

**Comment by fluffe9911** [comment]
dont forget to checkmark the yogstation/code/modules/clothing/head.dm file then recompile so the game actually loads it

**Comment by nesisknesis** [comment]
yeah saw that, autodrobe folkhat was also scuffed which is now fixed

**Comment by nesisknesis** [comment]
ja ja ja vee hoo

**Comment by fluffe9911** [comment]
for the lederhosen you could have the description be the perfect outfit for yodeling on top of a mountain but with more german lol

**Review by monster860 — APPROVED** [review]

**Pull request merged**
