### PR TITLE
Devil affair agents

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## Note

This is also a very barebones version of Devils. I'd like this to be more in-depth in the future, but I quickly burn out on development every time I open this branch, which sucks but what can you do. I hope someone finds this antagonist fun enough to pick up after me.

# Document the changes in your pull request

This adds Devil Affairs Agents into the game. Devil Affairs Agents replace Devils and Internal Affairs Agents entirely, putting the best parts of both antagonists together in a new gamemode meant to work both in a dynamic and standalone environment.

HackMD for the project can be found here: https://hackmd.io/189iSq-4TqysuqT5ICQ6tw -- I did stray from this quite a bit, mostly due to limitations yog code currently has.

Things left to do:

- [x] Flavortext
- [ ] Give IAAs their own TGUI panel telling them who the Devil is
- [x] Icons for Devil abilities
- [x] HUDs so Devils and Agents can see eachother
- [x] Curator interactions & the Codex -- This was changed due to technical limitations of Yogstation.net code
- [ ] ~~Employement filing cabinet (mapping required!!)~~ Not doing this as they were apparently removed for lore stuff. I'm not gonna argue man.
- [x] Testing any of this works
- [x] Pitckfork fixes (ensuring it works with the twohanded component once that is merged)
- [x] Re-add the Devil's souls HUD counter.

#### Agents

The Agents spawn with 10 TC, an uplink, and an objective. They have to kill their objective, another Agent, and turn a piece of paper into a calling card to plant it on their target. Then they can find the Devil, who they innately know, so they can turn in their kill. Each kill, they get a few extra TC deposited directly into their uplink, and they get a new target.

If the Devil is killed, their target will immediately be turned in, but they will get no additional TC.
Once they are the last person standing, they will get the objective to hijack.

#### Devil

The Devil has an ability to make contracts to give people Affairs Agent status, otherwise they are meant to hide in plain site so Agents can turn in kills to them. Each kill they turn in gives them a soul, which powers them up. Once they collect 8 souls, they gain all their special abilities, such as fireball and their pitchfork.

If they die, they will slowly heal unless gibbed.

#### Why is this a Dynamic ruleset

This gamemode was made with intent for it to run properly in Dynamic, with other antags. This is a background thing that snowballs into a roundending one later, but Security's primary focus early in round should be Traitors/Changelings/etc, then turns to the IAAs as they finish up.

#### Why does this replace IAA/Devils

Those two gamemodes were full of shitcode and did not work well. The intent of this PR is to REPLACE those, because the alternative would be to remove them, in the case of Devils they are completely removed from rotation already, and IAA is constantly pinged around because no one can decide how they want to work.
They cannot co-exist with Devil Affairs because it would be beyond too confusing to expect new players (or players in general) to be able to tell which antags do what.

Having all 3 antagonists goes against my goal of this PR to cut down on a ton of bloat code, removing some typically unfun or unbalanced gamemodes, and make these antagonists more approachable to new players.

# Wiki Documentation

IAAs have been removed.
Devils have been removed.
Devil Affairs Agents have been added.

# Changelog

:cl:  
rscadd: Added Devil Affair Agents
rscdel: Removed Devils
rscdel: Removed Internal Affairs Agents
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
i like it but i think it should go alongside IAA now, ynots changes to IAA have made the gamemode Actually Good and Enjoyable and ive had a great time whenever playing it now.

**Comment by JohnFulpWillard** [comment]
I don’t agree for the reasons I explained in the PR body and hackmd

**Comment by azzzertyy** [comment]
> I don’t agree for the reasons I explained in the PR body and hackmd

not at all because your hackmd is out of date,
the first two points in your negatives to IAA are both out of date and dont reflect the gamemode as is

**Comment by JohnFulpWillard** [comment]
>  the first two points in your negatives to IAA are both out of date and dont reflect the gamemode as is

It's still valid arguments, the only difference now is that you are constantly getting more traitors, turning the game into more of a TDM battleroyale, something that the inclusion of Devil is meant to slow down.

**Comment by azzzertyy** [comment]
> > the first two points in your negatives to IAA are both out of date and dont reflect the gamemode as is
> 
> It's still valid arguments, the only difference now is that you are constantly getting more traitors, turning the game into more of a TDM battleroyale, something that the inclusion of Devil is meant to slow down.

id rather have the current IAA in rotation atleast for now, i personally find it really fun and i know others share similar opinions, no reason to delete the gamemode that people are just now enjoying
if opinions change then sure, remove it, but for now i see no reason to.

**Comment by JohnFulpWillard** [comment]
If IAA ends up being preferred over devil affairs then I'll just close this PR. I'm not gonna give up on the entire point of the PR without even seeing it in-game because you don't like change

**Comment by azzzertyy** [comment]
> If IAA ends up being preferred over devil affairs then I'll just close this PR. I'm not gonna give up on the entire point of the PR without even seeing it in-game because you don't like change

where did i say that? i like the change, i like the concept, i just dont think it should replace a gamemode that this can go alongside without harming anything.

**Comment by JohnFulpWillard** [comment]
> where did i say that? i like the change, i like the concept, i just dont think it should replace a gamemode that this can go alongside without harming anything.

and I am saying that these gamemodes are mutually exclusive and cannot coexist together.

**Comment by JohnFulpWillard** [comment]
im done changing this until feedback comes in i think

**Comment by JohnFulpWillard** [comment]
blowing my brains out

**Pull request closed without merging**
