### PR TITLE
Adds a new Lavaland Ruin, The Minefield & Adds New Landmine Spawners

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

pairs best with https://github.com/yogstation13/Yogstation/pull/15449 and https://github.com/yogstation13/Yogstation/pull/15498

Adds a Minefield ruin, blanketed in random landmine spawners
Lots of ruined mechs
and a crate containing:

- Gold Space Pod Armor (Var-Edited to be strong and have a unique description)
- A Kinetic Accelerator Module
- A Plasma Cutter Module
- One of Each storage module so you can choose your pod's purpose
- one Pod Core
- a pod circuit board
- an old toolbox
- a lock & key

ss (2022-08-21 at 10 06 32)

Now adds random landmine spawners

- Random (84% chance for no mine)
- Stun-Only (80% chance for no mine)
- Smart Mine Only (80% chance for no mine)
- Dangerous Only (85% chance for no mine)

# Sprites

spawner sprite, wont be seen in game ever
mine

# Wiki Documentation

Will need to be added to the Ruins page, and need an ingame photo taken properly

# Changelog

:cl:  
rscadd: Adds a new Lavaland Ruin featuring space pod parts
rscadd: adds new randomized landmine spawners for mapping
/:cl:

### CODE REVIEW

**Comment by VaelophisNyx** [comment]
unsure of the best way to get photos of this ruin

**Comment by MenacingManatee** [comment]
Last I checked mines didn't have a sprite, has that been fixed?

**Comment by VaelophisNyx** [comment]
there's an open PR to fix that
#15449

**Comment by JamieD1** [comment]
> there's an open PR to fix that #15449

What would be cool is if you placed the mines with a helper or terrain type and made it a chance to be a landmine instead of people guessing the pattern instantly.

**Comment by VaelophisNyx** [comment]
you know I might do that actually

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
