### PR TITLE
Disables clowns

### PR DESCRIPTION
**Pull request by adamsong**
# Document the changes in your pull request

I hate clowns

# Changelog

:cl:  
rscdel: Removed clowns
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
also bad pr

**Comment by bruhlookatthisdood** [comment]
worst pr

**Comment by cowbot92** [comment]
we do a little honking

**Comment by YashinHak** [comment]
if this is merged then the gift of clownery will be gifted to every other role.

**Comment by LoliconSlayer** [comment]
Holy Fuck

**Comment by JohnFulpWillard** [comment]
It’s over honkbros

**Comment by Hislyna** [comment]
By taking out the clowns, you become a clown yourself. Is it worth taking this path so that the others may live?

**Comment by adamsong** [comment]
> By taking out the clowns, you become a clown yourself. Is it worth taking this path so that the others may live?

Yes

**Comment by MajManatee** [comment]
The clussy will remain

**Pull request closed without merging**
