### PR TITLE
Protolathes and such will attempt to charge newly printed power cells

### PR DESCRIPTION
**Pull request by Absolucy**
This makes anything that can print a power cell attempt to charge it while printing. Mainly, this is a convenience thing. Also, I want science to actually print bluespace power cells for the RPED and upgrade stuff that uses power cells.

:cl: Lucy
add: Protolathes, autolathes, techfabs, and mechfabs, when printing a power cell, will attempt to charge it.
add: APCs will be used to charge the cell if it has enough power *and* is over 20% capacity.
add: Otherwise, it will attempt to draw power from available power on the powernet directly.
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
absurdly large space ninja buff

**Comment by Absolucy** [comment]
@Marmio64 heh, this is more meant as "now science has NO excuse to not upgrade chemistry's power cells" / "now robotics has NO excuse to not upgrade borg's cells"

**Comment by Cartlord** [comment]
What happened?

**Comment by JamieD1** [comment]
So you are charging it whilst its being made? Will it come out charged everytime? Seems a bit op.

**Comment by Absolucy** [comment]
@JamieD1 it charges right after being made. it's not free power though, it will only work if there's enough power in the APC or powernet.

**Comment by Absolucy** [comment]
if you still feel that's a bit OP, here's a few potential compromises

 - quite a bit of extra power is used, which means it's less efficient than a cell charger
 - only like 25% or so of the battery is charged at maximum

**Comment by maxion12345** [comment]
cell charger mains coping and seething
anyways as long as it isn't popping out fully charged 40k cells easily then it shouldn't be too much of an issue

**Comment by Marmio64** [comment]
maybe have it only charge high capacity+ and lower to full(aka 15,000 charge aka 15 KJ)
that way you have to spend some time charging for high tier cells while medium quality ones are instant

**Comment by adamsong** [comment]
Pulling from the power net feels OP, also the all or nothing on the cell feels strange

**Pull request closed without merging**
