### PR TITLE
Adds some netherworld mobs for mapping, bus, etc.

### PR DESCRIPTION
**Pull request by Xoxeyos**
# Document the changes in your pull request

Adds some basic mobs from FAITH: The Unholy Trinity, because I'm tired of uploading them on the fly when I want them. There are two death sounds for pentarox and the wretch. Pentarox and the wretch can be spawned by netherworld portals too.

# Spriting
Adds new sprites for new netherworld creatures.
The ones displayed here are enlarged for your convenience.
Blind One: 
blindone_scaled_10x_minified

Cultist: 
cultist_scaled_10x_pngcrushed

Pentarox:
pentarox_scaled_10x_minified

Wretch: 
wretch_scaled_10x_minified

# Changelog

Adds some basic mobs from FAITH: The Unholy Trinity, as well as sprite assets, and two audio files. Two new things can crawl out of hell.

:cl:  Xoxeyos
rscadd: Adds creepy cult stuff from FAITH.
/:cl:

### CODE REVIEW

**Review by cuackles — CHANGES_REQUESTED** [review]
need you to actually add images of the sprites into the spriting section and question, where the sprites made by yourself or where they taken directly out of faith ?, apart from that the sprites are fine i just need the format to be followed

**Comment by Xoxeyos** [comment]
> need you to actually add images of the sprites into the spriting section and question, where the sprites made by yourself or where they taken directly out of faith ?, apart from that the sprites are fine i just need the format to be followed

The FAITH sprites were taken from the [FAITH wiki's sprite resources](https://airdorf.fandom.com/wiki/Sprite_Resource), and resized to fit within a 32x32 icon.

**Review by cuackles — APPROVED** [review]
Bet, i assume they are ok to use them legally and stuff, they obviously look out of place but it's mainly for busing stuff so i give them the 👍

**Review by ToasterBiome — APPROVED** [review]

**Comment by KingSuperBOB** [comment]
So Im assuming cultists and blind ones are bus only

**Pull request merged**
