### PR TITLE
fixes preference thingy

### PR DESCRIPTION
**Pull request by Bibby0110**
lol

### CODE REVIEW

**Comment by Cartlord** [comment]
you should probably mention that this closes https://github.com/yogstation13/Yogstation/issues/15589

**Review by adamsong — CHANGES_REQUESTED** [review]
Not how prefs work, please do properly

**Review by adamsong — APPROVED** [review]
Looking at outdated code isn't helpful

**Comment by Cartlord** [comment]
why was this closed and re-opened on merge day

**Pull request closed without merging**
