### PR TITLE
Replaces telescopic baton sprites with ones by Identification

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

~Ports ["Telescopic Baton Resprite" #57089](https://github.com/tgstation/tgstation/pull/57089) by [maxymax13/Flareguy](https://github.com/maxymax13) on TG and also changes a few things to make it fit better, though I can revert that if needed. Main differences are adding a tip to the end, moving the collapsed version to line up with the handle of the extended version, fixing an inconsistent pixel on the handle, and coderspriting some icons for the roasting stick. Look to the original for more details.~ Now uses a resprite from Identification, though the roasting stick is still the same as before.

image
image
158418717-369fdeb5-0ae0-44b8-8d1c-921e3d39017d

# Wiki Documentation

Icon will need to be updated for the telebaton and roasting stick if they are on the wiki. 

# Changelog

:cl:  Identification
imageadd: Telescopic batons are now a discernible shape
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
art is nice but idk about the light, it was completely mechanical previously and now it is being introduced with an electrical component; something to think about

**Comment by alexkar598** [comment]
> art is nice but idk about the light, it was completely mechanical previously and now it is being introduced with an electrical component; something to think about

Could be a sticker, similar to how some public toilet doors work

**Comment by alexkar598** [comment]
That being said, not a fan of it myself

**Comment by nmajask** [comment]
image
image
I removed the dot, heres the new sprites in game

image
Also, could try to lighten up the rod to make it stand out more

**Comment by Hopekz** [comment]
> image Also, could try to lighten up the rod to make it stand out more

lightsaber-technique

**Comment by nmajask** [comment]
> image

image

**Comment by Hopekz** [comment]
> image

Perfect

**Comment by nmajask** [comment]
> Perfect

Might still be a bit too dark

**Comment by Hopekz** [comment]
> Might still be a bit too dark

Untitled

image

**Comment by nmajask** [comment]
image

**Comment by Marmio64** [comment]
the baton handle seems too thick, and i liked how the current baton's baton part started large and got smaller then ended with a nice sized tip, rather than this one where its the handle, then the same consistent size until the tip.
edit: what i was trying to say is that the current baton is segmented and i enjoy that.

**Comment by nmajask** [comment]
image
image
Ident did a resprite of it

**Comment by Hopekz** [comment]
> image image Ident did a resprite of it

sweet

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
