### PR TITLE
Makes mop able to be put in your backpack slot

### PR DESCRIPTION
**Pull request by ghost**
Oak asked for it.  I just need a sprite of the mop on the back.

For reference: scythe back dmi, mop dmi, and advanced mop dmi.
[mops.zip](https://github.com/yogstation13/Yogstation-TG/files/2260013/mops.zip)

I need a back sprite for mop and advanced mop.

:cl:  
rscadd: Allows for mops to be slotted in the backpack slot
/:cl:

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
nice job with that spelling error

**Comment by ghost** [comment]
Thank you!

**Comment by Colburn3000** [comment]
Why should the mop fit in the backpack slot, when a feature of the advanced mop is the folding handle? Have you ever tried to put a mop in your backpack?

**Comment by ghost** [comment]
No no, so this doesn't make it fit in the backpack but can be put on your back so you can't also have a backpack.  The folding handle is still a feature.

I honestly never play janitor and Oak asked for it so iunno man.

**Comment by Amelia0010** [comment]
image

**Pull request closed without merging**
