### PR TITLE
TEG Revengence 2

### PR DESCRIPTION
**Pull request by wonderinghost**
Moved to a new repository. due to poor understanding of commits and having them contaminate pr's of different branches.

# Document the changes in your pull request
updates the box and meta layouts of the Thermo-Electric Generator to be easier to setup and have more starting fuel (50 minutes if to empty both tanks).
NOTE: ICE META TEG IS CURRENTLY DISABLED IN CONFIG UNTIL AUXMOS CAN VENT WASTE GASSES BETTER
TEG
image

# Wiki Documentation
Intuit-Ises the TEG setup page to be better to understand.
(Working on that before this is ready to merge)
# Changelog
:cl:  
mapping: Readds and updates TEG layouts for box and meta
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Don’t enable it on icemeta until planetary atmos works better, right now venting it will break everything on icemeta because planetary atmos violently explodes whenever something is on fire

Can do the map template just don’t code it so it spawns on meta for right now

**Comment by wonderinghost** [comment]
need help figuring out what this error is

**Comment by wonderinghost** [comment]
why is map bot weird

**Comment by wonderinghost** [comment]
this isn't going to see light of day as i need to sterilize my repository again

**Pull request closed without merging**
