### PR TITLE
New plasmamen helmets

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
Adds new customization options for plasmamen in the form of more helmet variations, this can be changed in the character customization screen
thanks biome for the code and ident with the help on the handle sprite

# Spriting

image
image
image
image
image
image
itemsfinally

# Wiki Documentation

add the helmets in the plasmamen wiki page and clothing page

# Changelog

:cl:  @ToasterBiome @grimm-hollowknight @cuackles 
rscadd: new customization options for plasmamen
imageadd: add new helmets sprites
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
image

**Comment by knightshade0** [comment]
More customization options yay

**Comment by Simplehorror** [comment]
we do not need cat plasmamen

**Comment by Potototatoh** [comment]
my only schisms are against the wizard hat and cat ear ones

**Comment by Moltijoe** [comment]
> my only schisms are against the wizard hat and cat ear ones

gotta give drake a hat to wear whenever he decides to play plasmaman

**Comment by Simplehorror** [comment]
@cuackles just make it so you can put hats on top of a helmet

**Comment by Marmio64** [comment]
no cat ear plasmamen.
Fourth option looks cool without being over the top/snowflake, best one imo.
Don't really like or explicitly dislike the other options.

**Comment by Cartlord** [comment]
Not a fan of most of these - #1 just looks WEIRD, #2 should not be, #4 having a gas mask is weird since plasmamen still need to wear masks under their helms, and #6 is just silly.

**Comment by 00ze-cyclone** [comment]
Do the mass purrbation button give plasmamen the second helmet?

**Comment by cuackles** [comment]
> we do not need cat plasmamen
> my only schisms are against the wizard hat and cat ear ones
 
 i want to give everyone the posibility of choosing a hat that they would like, if no ones wants to use the cat looking one it will remain unused, but i want the option to still be there , everyone should have the right to make their character look like they want within the rules of the server, i see no issue in giving them those ones, same for the wizard one

**Comment by cuackles** [comment]
> @cuackles just make it so you can put hats on top of a helmet

that could be another option but i did the sprites not the code, and i bealive some of the hats could cause clipping issues , but it does seem like a good idea, but i was requested to make custom helmets so thats what i did

**Comment by cuackles** [comment]
> Not a fan of most of these - #1 just looks WEIRD, #2 should not be, #4 having a gas mask is weird since plasmamen still need to wear masks under their helms, and #6 is just silly.

you are never a fan of anything

**Comment by cuackles** [comment]
> Do the mass purrbation button give plasmamen the second helmet?

image

**Comment by cowbot92** [comment]
you know your PR is good when marmio AND cartlord downvote it

**Comment by KillerOrcaCora** [comment]
Hell I was on the fence about the cat ears and wizard hat but knowing those 2 are against it gives me full reason to green light all of this!

**Comment by Marmio64** [comment]
> you know your PR is good when marmio AND cartlord downvote it

My opinion dies here today as a martyr.

**Review by Ebin-Halcyon — APPROVED** [review]
Don't play enough Yogs to know the design politics, but the quality of the sprites themselves are fine. Up to other maints if they approve or disapprove.

**Comment by Simplehorror** [comment]
> you know your PR is good when marmio AND cartlord downvote it

yeah i get that a lot

**Review by warface1234455 — APPROVED** [review]
very sexy sprites

**Comment by MajManatee** [comment]
Plasma men already lack customization, why not
I do think adding your signature look/hat as an option is a bit cringe though (#6) but at the end of the day i dont really care

**Comment by cuackles** [comment]
> Plasma men already lack customization, why not
> I do think adding your signature look/hat as an option is a bit cringe though (#6) but at the end of the day i dont really care

I understand that it can be seen that way but it's honestly because i do see a lot of people use wiz hats, and wanted to make the option for plasmamen wiz's to be a thing too whitout instantly combusting, i was planing on making all the colors but this already took me like 2 month to finish just because i kept putting it off, will maybe do those someday but basically, 
- Wiz hat is for everyone that likes the hat look and wants to be plasmeme
- Let actual wiz plasman be a thing
- I was gonna make the other ones but I'm a lazy shit

**Comment by 00ze-cyclone** [comment]
> > Plasma men already lack customization, why not
> > I do think adding your signature look/hat as an option is a bit cringe though (#6) but at the end of the day i dont really care
> 
> I understand that it can be seen that way but it's honestly because i do see a lot of people use wiz hats, and wanted to make the option for plasmamen wiz's to be a thing too whitout instantly combusting, i was planing on making all the colors but this already took me like 2 month to finish just because i kept putting it off, will maybe do those someday but basically,
> 
>     * Wiz hat is for everyone that likes the hat look and wants to be plasmeme
> 
>     * Let actual wiz plasman be a thing
> 
>     * I was gonna make the other ones but I'm a lazy shit

Time to make a wizard version of the envirosuit that act like wiz clothes for plasmeme wiz.

**Review by JamieD1 — APPROVED** [review]
WHY CAT EARS YOU MONSTER

**Comment by cuackles** [comment]
> WHY CAT EARS YOU MONSTER

THE DEGENERATES ARE THE ONES WHO GIVES US MONEY JAMIE, THINK IN THE PROFITS, PROFITS!!!!

**Pull request merged**
