### PR TITLE
Gives QM new alt name of "Head of Cargo"

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
# Document the changes in your pull request

Gives the QM alternative name of "Head of Cargo"

# Wiki Documentation

Maybe some? With QM names if that exists i dunno

# Changelog

:cl:  
rscadd: Added new alt name for QM.
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
He is not the Head of Cargo though, the HoP is. Would create confussion

**Comment by Moggram** [comment]
> He is not the Head of Cargo though, the HoP is. Would create confussion

But he is the head of cargo.

**Comment by Hopekz** [comment]
> He is not the Head of Cargo though, the HoP is. Would create confussion

Lmao @ people thinking HoP is head of cargo just because it is written that way

**Comment by Marmio64** [comment]
would create confusion, plus yes, hop is technically already the head of cargo, and QM isnt even a head so why do they need an alt title that declares them as such.

**Comment by LoliconSlayer** [comment]
QM's not a head

**Comment by bruhlookatthisdood** [comment]
Maybe it should be HoP is Head of Service, while QM is Head of Supply.
And anyways, the people have spoken!

**Pull request closed without merging**
