### PR TITLE
Removes box from rotation

### PR DESCRIPTION
**Pull request by LoliconSlayer**
I will not be taking any criticism

Please direct any and all comments to your nearest trash can

Thank you

:cl:  
bugfix: No more Boxstation
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Literally the best PR

**Comment by Spacemanspark** [comment]
This man is about to be shot or something.

Godspeed

**Comment by Firewolf34** [comment]
Can't believe this is finally happening. SPEEDMERGE?

Don't worry bud. We got snipers on the roof across from LoliconSlayer's house, pointed at the snipers attempting to snipe the other snipers attempting to snipe him.

**Comment by maxion12345** [comment]
Time to revive circlestation

**Comment by Chubbygummibear** [comment]
nice change, stranglebot

**Comment by Jarod1200** [comment]
Meme pr from the chairman of "I don't play"

**Comment by Anvilman6** [comment]
Hello based department?

**Comment by LoliconSlayer** [comment]
Dear anyone that wants to whine that I don't play (Looking at you, Jarod),

image

Sincerely, Morder

**Comment by JamieD1** [comment]
Fuck off

**Pull request closed without merging**
