### PR TITLE
Adds Touch of Death (AKA nerfed disintergrate)

### PR DESCRIPTION
**Pull request by Notamaniac**
# Document the changes in your pull request

Adds Touch of death, identical to disintergrate except it just kills instead of gibbing. Antimagic and the bloated human suit still negate it, and it's cooldowns are the same as before.

I don't know if this is a wanted addition, but just keep in mind that the funny hammer can kill more people in a shorter amount of time, and immovable rod has utility on top of being able to do massive damage to multiple people. Since disintergrate had sort of fallen out of the meta before, I don't know if it needs further nerfs on top of this (i.e. it does massive damage over time) but we'll see what the popular opinion is.

# Spriting

Action Icon : touchofdeathicon2
Inhand : touchofdeath
Mobsprite : touchspell_lefthand death

# Wiki Documentation

Something about touch of death added under the offensive category

Cost : 2
Robed : Yes
Cooldown : 60/50/40/30/20 

# Changelog

:cl:  
rscadd: Adds Touch of Death, a wizard spell (AKA disintergrate lite). Still has the same counters as before, but kills instead of gibbing.
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Piss hand piss hand piss hand !!!!!!

**Comment by isotope436** [comment]
PISS HAND!!!

**Comment by Notamaniac** [comment]
correction stinky hand so bad it kills people

**Comment by UltraBigRat** [comment]
could make it 1sp since its nerfed pretty hard, and without the utility of gibbing there is little use getting it compared to other 2 sp options as its just a once in a minute melee instakill when you can get far more powerful options that are spammable

**Comment by Notamaniac** [comment]
> could make it 1sp since its nerfed pretty hard, and without the utility of gibbing there is little use getting it compared to other 2 sp options as its just a once in a minute melee instakill when you can get far more powerful options that are spammable

Yeah I'm gonna have to see what the consensus here is, though it if it gets buffed to 1 sp it might also have to get a cooldown nerf since 1 sp contends wilth the utility spells like knock and charge (which are useful, don't get me wrong but not 'kill a guy instantly' useful).

**Comment by UltraBigRat** [comment]
> > could make it 1sp since its nerfed pretty hard, and without the utility of gibbing there is little use getting it compared to other 2 sp options as its just a once in a minute melee instakill when you can get far more powerful options that are spammable
> 
> Yeah I'm gonna have to see what the consensus here is, though it if it gets buffed to 1 sp it might also have to get a cooldown nerf since 1 sp contends wilth the utility spells like knock and charge (which are useful, don't get me wrong but not 'kill a guy instantly' useful).

I mean yeah,  another option could be keeping its cost and just making the cooldown much lower, so it contends with more spammable spells.

**Comment by Simplehorror** [comment]
> > could make it 1sp since its nerfed pretty hard, and without the utility of gibbing there is little use getting it compared to other 2 sp options as its just a once in a minute melee instakill when you can get far more powerful options that are spammable
> 
> Yeah I'm gonna have to see what the consensus here is, though it if it gets buffed to 1 sp it might also have to get a cooldown nerf since 1 sp contends wilth the utility spells like knock and charge (which are useful, don't get me wrong but not 'kill a guy instantly' useful).

killing 1 guy instantly with a 90 second cooldown is pretty useless as a wizard since you'll almost never be in 1v1s after you're spotted

**Review by cuackles — APPROVED** [review]

**Comment by Notamaniac** [comment]
I'm going to keep this as is for now, unless the ominous balance council says to make changes, then maybe buff it later depending on how easy it is to defib people back to life

**Comment by RG4ORDR** [comment]
Can it be made to shower the area with random gibs then?
I see no issue with it outside of the immense lack of flair, it needs to be so flashy because Ei'nath both has a visual cue it was coming - funny red hand. But you also got to witness a shower of gore.

**Comment by Marmio64** [comment]
It'd be funny if it ripped out their skeleton as flavor (spawn gibs and change their species to skeleton/weak skeleton)

**Review by MajManatee — APPROVED** [review]
i actually really liked the gib spell, and this is a nice replacement.

**Review by Moltijoe — APPROVED** [review]
infinitely better than disintegrate
bit hesitant on a minute cooldown instakill spell though

**Comment by Simplehorror** [comment]
disintegrate left the brain so why are you guys complaining

**Comment by cuackles** [comment]
> It'd be funny if it ripped out their skeleton as flavor (spawn gibs and change their species to skeleton/weak skeleton)

Fuse the Necro stone with this spell for riping skeletons out of people and making them your thralls

**Comment by Moltijoe** [comment]
> It'd be funny if it ripped out their skeleton as flavor (spawn gibs and change their species to skeleton/weak skeleton)

so long as it only does this to races that actually have skeletons (not ipc and preternis)

**Review by ReddicusDragon — APPROVED** [review]
no spelling issues

**Pull request merged**
