### PR TITLE
[WIP] Yogstation cooking expansion DLC $6.99

### PR DESCRIPTION
**Pull request by AlvCyktor**
# Document the changes in your pull request
adding some cultural food and fried chicken (we have the sprites but we never used them)

- [ ] Import all new food sprites
       - [x] Middle Eastern foods
       - [ ] Chicken sprites
- [ ] Reform the chicken code
      - [ ] New chicken food codes
      - [ ]  Make butchering chicken give you a whole chicken
      - [ ] Make able to split the whole chicken into pieces
- [ ] Fryable code
      - [ ] Special fryable objects can now have a special frying result

# Spriting
baklava
falafel
halva
Pita
shawarma
shishtawook

# Wiki Documentation
will have to add the new foods to the food and drinks guide for chef

# Changelog
:cl:  
rscadd: new foods 
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
Mmm fried chicken
Add falafel and make it release a gas within 2 tiles that give you toxin damage

**Comment by Therandomhoboo** [comment]
If it aint bar, I don't want it. 

(This is a good pr)

**Comment by kooarbiter** [comment]
make chicken nuggets actually require chicken meat

also putting a whole chicken on an iron rod should make one rotisserie chicken

**Comment by ToasterBiome** [comment]
Reopen with more work

**Pull request closed without merging**
