### PR TITLE
Donator item for Molti

### PR DESCRIPTION
**Pull request by Moltijoe**
I've donated enough time, now I get an item

@BlueishTsunami made the amazing sprite

reskinned winter coat
the hood part is instead a hat

image
image
image
image

:cl:  @BlueishTsunami @Moltijoe 
rscadd: Donator item for Molti (that's me)
imageadd: Sprites for the donator item
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
Honestly sick as hell

**Comment by adamsong** [comment]
On hold while new procedures for donator items are implemented

**Review by cuackles — APPROVED** [review]

**Comment by tattax** [comment]
🤔

**Comment by MajManatee** [comment]
league of legends content

**Pull request merged**
