### PR TITLE
[Box] Updates Genetics Layout + fixes (Attempt 2)

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Attempt two; moved disposal chute to where the potted plant was. (Photos out of date)

Updates Box's genetics layout, which I felt was lacking; and fixes some things:

- missing air alarm in genetics is missing no more
- adds a wall extinguisher cabinet to genetics so you can leave the one in cloning alone
- fixes a random missing distro pipe in medbay hallway

also shuffled cloning's lockers around some, and gave it a requests console

Before:
ss (2022-08-12 at 04 51 07)

After:
ss (2022-08-12 at 04 51 25)

# Changelog

:cl:  
bugfix: Genetics now features an Air Alarm
bugfix: Air pipes in medbay hallway by the CMO office connect properly now
tweak: Shuffled the layout of Genetics around
tweak: shuffled some stuff in Cloning
tweak: Cloning now has a requests console
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
why remove window between genetics and cloning?

**Comment by VaelophisNyx** [comment]
I felt like it looked funky with the vendor there; I can put it back

**Comment by VaelophisNyx** [comment]
should state the window is back*

**Comment by JamieD1** [comment]
Hi @VaelophisNyx Im sorry but I really dont like the rearrangement you have done in genetics, it just makes it smaller and less great, can you let me know when you are free and I can show you what I think would look better.

**Comment by JamieD1** [comment]
image

**Comment by VaelophisNyx** [comment]
smaller how-
it's literally less wasted space with that gargantuan monkey pen?

**Pull request closed without merging**
