### PR TITLE
Hosea 8:7: "For they have sown the wind, and they shall reap the whirlwind." - Appendicitis Changes

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Appendicitis sucked. Lets be real.
Now it doesn't suck.

Fun fact, in case you didn't know (because why would you?), I have had appendicitis. It fucking sucks. People can, and often DO, die because of it regularly. 

Now you too can enjoy the fun experience of going to an overcrowded ER, waiting while the staff treat John McFartle for his 6,342,303th burn wound from hacking a door until you die in the waiting room after it bursts. Fun!

Honestly I just didn't like how you could realistically just ignore it. it doesn't do enough damage to kill you, and the only reason you have to remove it is because it can stun you or make you vomit. Lame.

**Important Changes**
Appendicitis now:
Has 4 stages.
Stage 1-3 have had minor tweaks to chances of stuff happening. Increases by like 3 to 5%.
Stage 4 now does the following:
40% chance to knock you down, deal 20 damage to your appendix, do 5 brute and 10 toxin damage.
25% to make you vomit
25% to make you cough up blood
10% chance to burst and kill you.

See how much you care now.
Another PR in my list of things I'm making bc I don't like vox

# Why is this good for the game?

Makes a deadly virus actually deadly. Encourage people to not ignore a life-threatening issues. And while the real appendicitis wont gib you, this one is way easier and faster to remove, so it balances out.

# Testing

Ill get to it eventually maybe probably. The nature of the code is that of which it will work and testing isn't _REALLY_ needed though.

# Wiki Documentation
Should mention the above listed rates (if applicable) and definitely mention that its lethal now.

# Changelog

:cl:  
tweak: Appendicitis is lethal now. Just like god intended.
/:cl:

### CODE REVIEW

**Comment by azzzertyy** [comment]
remove the stupid gib

**Comment by MajManatee** [comment]
lol no

**Comment by cowbot92** [comment]
with azzzerty, gib bad

**Comment by iamthesilly** [comment]
Remove the gib

**Comment by Hislyna** [comment]
INCREASE THE GIBBUS CHANCEUS!!

**Comment by Moltijoe** [comment]
Balance council:
>Appendicitis already fucks up lowpop, this makes it a death sentence
This also turns the silly wizard spell into a real threat
also, also, stage 4 might as well just instantly kill the person with 100% chance as it permanently CCs them

**Pull request closed without merging**
