### PR TITLE
Make Drones Craftable

### PR DESCRIPTION
**Pull request by ghost**
This makes drones craftable.

To create them you need a power cell, a flash, cable cuffs, a crowbar, a wrench, a screwdriver, a multitool, a welding tool, wirecutters, and a backpack.

EDIT: Also needs 5 plasteel now.

Let's see where this goes.

#### Changelog

:cl:  
rscadd: Drones are now craftable!
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
:rofl:

**Comment by Nickvr628** [comment]
I like this. Drones were good, just not en masse. Making them craftable for robotisists is a good change.

**Comment by Groudonmaster** [comment]
HAIL MORROW

**Comment by Ratvar** [comment]
Add MMI component, don't let people extract MMI, let people use offline brains. Ta-da, use for morgue's AFK and monkeys + punishment for traitor toes + no crafting respawns (and wasting station plasteel) as drone.

**Comment by Groudonmaster** [comment]
That would require more coding than it's worth to reactivate drones. Also more work than reasonable

**Comment by Ratvar** [comment]
Exactly!

**Pull request merged**
