### PR TITLE
Moves the seclathe into the armory

### PR DESCRIPTION
**Pull request by Partheo**
The seclathe can print guns, guns should be located in the armory, not the security office.

#### Changelog

:cl:  
tweak: The seclathe is now located in the armory
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Please explain anyway, also fix conflict

**Comment by MegaEmpirical** [comment]
Hmm well if you're doing that, then close this:
https://github.com/yogstation13/Yogstation/issues/4788

**Comment by athena413** [comment]
thank you for applying this to all maps

**Comment by ghost** [comment]
as i'm the one who asked parth to do it because I didn't want to use the mapmaker, @wejengin2 

the explanation is such

seclathe prints guns

warden is supposed to distribut eguns

moving it to the armory means that the warden now distributes guns rather than sec officers printing 10 AEGs and lodging them up their assholes

**Comment by Mesalikepie** [comment]
Okay people the seclathe isn't just for guns, but also has ebolas and other equipment that many people use it for. Like seriously maybe just split the sec techfab into two. A weapon printer, and an equipment printer

**Comment by PrinceKirze** [comment]
I agree with the sentiment behind this, but not really the execution. I don't really see a reason why not to split weapons printing and equipment printing into two different machines. A little more work, certainly, but it's the long term solution to this. The lathe also prints ebolas, detective's scanners- tons of things that you don't need to go through the warden to get. On most population levels I think the proposed change would work fine, but during really lowpop and really highpop I see at least a few edge cases where this becomes a hurdle.

**Comment by Tipy1802** [comment]
I would suggest warden office instead, it would still prevent officers from printing guns but it would make it easier for wardens to give non weapons (like body cameras) to sec (less walking)

**Comment by UselessTheremin** [comment]
good change for when there is a good warden, makes the game better. bad change and a hurdle for the whole security team when there is a bad warden. in my experience, 9 times out of 10, there is a bad warden. i dont want to have to hear "go get a stamp of approval from hos and captain" for an ebola or a bodycam.

**Comment by MegaEmpirical** [comment]
I'm generally okay with this but I do think putting it into the Warden office is a much better idea.

It'll be be less walking for the warden who may have to use this often. It'll be a less dangerous area for someone to need to break into or ask the AI for access too.

**Review by patpol4 — CHANGES_REQUESTED** [review]
Let's go for the compromise of putting it in the warden office and fix conflicts

**Comment by Georgeur** [comment]
I'm laughing but sure. Can't wait to see the Warden commit dead after being asked for the 15th time to lathe a new pair of handcuffs, bodycam, ebola, etc. Then sec end up going to cargo to lathe ammo. The real fix here is to remove it's ability to create firing pins, jesus christ.

**Comment by patpol4** [comment]
@Partheo is this going to be worked on?

**Comment by Reed0506** [comment]
oh boy this makes it it suck even more for the det to get ammo on box

**Comment by patpol4** [comment]
Closing due to inactivity, message maintainers on discord to have it reopened

**Pull request closed without merging**
