### PR TITLE
Fixes #8452, adds proper atmos to the server room

### LINKED ISSUE #8452: Science server room lacks vent, scrubber, and air alarm
Madness. Yogstation.

### PR DESCRIPTION
**Pull request by jcatjmeow**
### Intent of your Pull Request
fixes #8452
also adds some stripes. And a new port, so you either re-fill or empty the server room's air without having a headache
also adds a mrp cup
#### Changelog

:cl:  
rscadd: There is now a scrubber and vent in the server room, yogstation. And a cup.
/:cl:

### CODE REVIEW

**Review by patpol4 — CHANGES_REQUESTED** [review]
1. Make your changelog more specific, what server room, what station?
2. There is no need to remove the table, either a. place the scrubber somewhere else, or b. dont remove the table
3. Pipes need to go under the airlock, not wall.
4. This one is just the suggestion but if you're up to it, try fixing the existing pipe to the server room itself so it goes under the airlock, like so : 
chrome_8c57FOHdG0
5. Another suggestion because i love stripes: 
chrome_PNTnZHb1ep

**Comment by jcatjmeow** [comment]
1) see the issue for more info. I linked it
2) the table is gone. I removed it. Bye.
3) pipes can go through the wall it happens
4) those are out of the scope of my pr

**Comment by patpol4** [comment]
Jcat these are not suggestions, either do 1-3 or this won't get merged.

**Comment by jcatjmeow** [comment]
Fiiiine i'll keep your stupid table

**Review by patpol4 — CHANGES_REQUESTED** [review]
Alright thanks for cooperating,
1. You missed a pipe above the room, in the corridor
2. I would prefer if the folder was on the table but I guess it's personal preference, up to ktl and you
3. Edit: I thought there was no atmos alarm but i just found it, ignore this point
4. You removed important variables by rotating the upper vent in the server room
chrome_3ef6y7gfUM
5. This one may be actually useless but I like the idea of a connector near fridges, this one will block off the table if you plug a canister in, how about something like this: 
chrome_SELJxJpq57
6. VERY IMPORTANT THING, REMOVE THE NUDGE VARIABLES ON THE FOLDER AND PAPER BIN, USE PIXEL_X AND PIXEL_Y INSTEAD

**Review by patpol4 — COMMENTED** [review]
Almost there, I have last two things, the folder on the table is actually placed on the console tile and pixelshifted on the table.
And the connnector port is still above the table in a way that would block access to it if a gas canister were to be connected, remove that or move it like i suggested in previous review.

**Comment by jcatjmeow** [comment]
> Almost there, I have last two things, the folder on the table is actually placed on the console tile and pixelshifted on the table.
> And the connnector port is still above the table in a way that would block access to it if a gas canister were to be connected, remove that or move it like i suggested in previous review.

I'll move the folder. As for the port, nobody will use the table and the port at the same time. I don't think it's necessary, and this makes the pipes nice and clean

**Comment by patpol4** [comment]
Everything checks out except the connector port.
Inaccessible spots are bad, I still disagree and cannot approve this. There are just so many ways you can go about this, another suggestion:
chrome_INFXqJlLqp

**Comment by patpol4** [comment]
Kettle will decide your fate

**Review by patpol4 — APPROVED** [review]
Nice cup, final version looks like this for anyone interested:
chrome_PNj4APcV3r

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Table exists

**Review by Ktlwjec1 — APPROVED** [review]

**Comment by jcatjmeow** [comment]
> Table exists

Tried to fix it with #9030 but it was closed by the mean alexkar

**Comment by MegaEmpirical** [comment]
Stop using vents as scrubbers you fucking animals.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
