### PR TITLE
Adds a lost relic: The alien queen maid.

### PR DESCRIPTION
**Pull request by nesisknesis**
image
image
image
image
image

Was deleted by TG in 2017, don't see why it was seems like a cool joke here it is I guess.

In order for this to appear in-game an admin must proc call maidify on the Queen, and can be undone through the proc unmaidify.

Could be made into a donator option to fuel the flames of degeneracy but I dunno how to do that.

#### Changelog

:cl:  Identification
rscadd: The Gods can now call forth the Alien Queen maid through their godly powers. 
imageadd: Lusty, Sexy. 
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
DIe

**Comment by Bibby0110** [comment]
i need this

**Comment by Bibby0110** [comment]
for a...

**Comment by Bibby0110** [comment]
thing

**Pull request merged**
