### PR TITLE
Glamrock peacekeeper for donators skins

### PR DESCRIPTION
**Pull request by cuackles**
adds the fazzkeeper, a skin based of glamrock freddy
image
image
image
image

# Changelog

adds a new borg skin

:cl:  
rscadd: Added new peacekeeper skin
imageadd: added new peacekeeper skin: glamrock Peacekeeper
/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Looks neat!

**Comment by Marmio64** [comment]
terrible job supershit, how'd ya fuck that one up that badly?

**Comment by cuackles** [comment]
> terrible job supershit, how'd ya fuck that one up that badly?

That's not very superstar of your part

**Comment by Marmio64** [comment]
> > terrible job supershit, how'd ya fuck that one up that badly?
> 
> That's not very superstar of your part

wrong line

**Comment by UselessTheremin** [comment]
feddy

**Comment by JamieD1** [comment]
Looks weird

**Review by JamieD1 — APPROVED** [review]

**Comment by bruhlookatthisdood** [comment]
this is the kind of content that makes me want to donate every day just a little bit more.

**Pull request merged**
