### PR TITLE
Replaces Kilo with GaxStation

### PR DESCRIPTION
**Pull request by JamieD1**
Goodnight sweet prince

:cl:  
rscadd: Replaces Kilo with GaxStation
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
approved by the half-insane spessman who only recently started playing yog and hasnt even unlocked any heads yet

**Comment by N3D6** [comment]
Why not keep both? Kilo is a great map

**Comment by stwordcitizen** [comment]
> Why not keep both? Kilo is a great map

Me when I LIE to myself

**Review by ToasterBiome — APPROVED** [review]
nice map

**Comment by SuperTeaLove** [comment]
I don't understand the purpose of replacing a map with a fundamentally different design philosophy with a map that isn't similar to it at all. Why they can't both have a place in rotation is beyond me, and personally I think if we plan to remove Kilo from rotation it should not be combined with a new map PR.

**Comment by ToasterBiome** [comment]
> I don't understand the purpose of replacing a map with a fundamentally different design philosophy with a map that isn't similar to it at all. Why they can't both have a place in rotation is beyond me, and personally I think if we plan to remove Kilo from rotation it should not be combined with a new map PR.

Kilo was added in the removal of another map (Omega) both of which served different purposes. Kilo is a midpop map pretending to be a lowpop one. Gax was created specifically to address the shortcomings of Kilo while keeping lowpop in mind and certain design decisions of Kilo.

**Comment by SuperTeaLove** [comment]
EDIT: It's been explained to me a little more in depth by Baiomu and I imagine my lack of clarity is due to solely me. Seems a lot of love for Kilo went into Gax and it's good to see it's not a case of Kilo going away but it being spiritually upgraded.

I was not aware that this map was designed specifically to address design flaws in Kilo while maintaining certain features. In all discussions of this map with you Baiomu, and others, I never once got the impression that was the idea behind this map's implementation or that Kilo would be removed to make room for this map. I guess I will defer to those with mapping experience and who've taken the time to examine these maps in more depth.

As a general statement I think Kilo had potential of its own just like Omega was not an entirely imperfect map in concept. Perhaps this is simply the age old human stubbornness to accept change at work. Either way I appreciate clarification on this map's design goal and can appreciate the fact Kilo was intended to be removed.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
rip bozo

**Pull request merged**
