### PR TITLE
removes the sleepers and medkits from reebe because new players get confused

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
not actually a clock cult nerf because i also added a paper telling people how to heal each other, because i see way too many new players following the thought process of 'sleepers heal people, so i should dump my dying or dead teammates in there and hope for the best!'

# Changelog

:cl:  
rscadd: added a paper to reebe telling you how to heal and resurrect teammates (spoilers: its not with the super shitty reebe sleepers)
rscdel: the sleepers and medkits are removed from reebe
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
what about toxin

**Comment by TheRyeGuyWhoWillNowDie** [comment]
hello mr mentor, toxin damage is automatically healed by cultists while they stand on brass tiles like the ones found everywhere on reebe

**Comment by Simplehorror** [comment]
thank god

**Comment by ShoziOffical** [comment]
> hello mr mentor, toxin damage is automatically healed by cultists while they stand on brass tiles like the ones found everywhere on reebe

cool

**Comment by Sniblet** [comment]
Non-medical clockcult cyborgs can no longer heal people
Also what makes you think anyone's going to read this, new players are violently allergic to learning anything about clockcult

**Comment by Simplehorror** [comment]
> Non-medical clockcult cyborgs can no longer heal people Also what makes you think anyone's going to read this, new players are violently allergic to learning anything about clockcult

the sleepers dont fucking work they cant heal anyone anyway, also non-medical cyborgs can't heal normal crew without going to medbay either

**Comment by Firewolf34** [comment]
Very desperately needed to explain to players how to heal. 

It's not even about new players, the UI just straight up does not explain how you're supposed to heal&revive, it only mentions a healing scripture (Sentinel's Compromise).

Even older players did not perform it well... And I say this as someone who had to be told what to do because after trying to dig around for information, all I found was the Compromise which still doesn't explain revive process. 

Good PR idea, but maybe you can explain how to use the vitality matrix and compromise instead of just telling them to use it?

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
