### PR TITLE
Removes the majority of the drinks from the perma drink vendor on box

### PR DESCRIPTION
**Pull request by SomeguyManperson**
### Intent of your Pull Request

Removes the majority of the drinks from the perma drink vendor except shamblers and water to make escaping perma slightly harder

### Why is this good for the game?

improves rp

#### Changelog

:cl:  
tweak: the cola vendor in perma has been replaced with an ULTRA SHAMBLERS vendor
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
I thought perma was not supposed to be inescapable

**Review by patpol4 — APPROVED** [review]
No idea how you managed to touch the monkeys and Runtime but maps are fine

**Comment by boodaliboo** [comment]
makes perma significantly harder to escape

**Comment by Smudged** [comment]
> makes perma significantly harder to escape

Good

**Comment by SomeguyManperson** [comment]
no other map has a cola vendor in perma afaik

**Comment by boodaliboo** [comment]
> no other map has a cola vendor in perma afaik

thats why i made a pr to add it to all of them but it was near instantly closed

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
