### PR TITLE
Codergun the slaughter demon that killed my friends

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Slaughter demons (and other bloodcrawlers) now have a 1 second entry time on bloodcrawling, forcing them to commit to crawl exits and not be able to instantly eat or flee from a situation by clicking a blood tile.

To prevent crew-side cheese, the slaughter demon is now un-pullable and un-pushable by crew member hands.

Also, you can no longer speak while jaunted.

# Changelog

:cl:  
tweak: Bloodcrawling now takes 1 second to enter blood
tweak: Slaughter and laughter demons can no longer be pulled with your bare hands or pushed by walking
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
But funny interactions

**Comment by azzzertyy** [comment]
slaughter demons get gamed on enough

**Comment by Maia-J** [comment]
Why cut the speaking too? It changes nothing balance wise and just makes it boring to play

**Comment by Marmio64** [comment]
Demons need some extra health to compensate, just an extra 50 would help them actually be able to survive with this change

**Comment by tattax** [comment]
lol

**Comment by ynot01** [comment]
> Demons need some extra health to compensate, just an extra 50 would help them actually be able to survive with this change

No they don't

**Comment by Maia-J** [comment]
Why don't they need to speak though?

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
remove the nospeak

**Comment by ToasterBiome** [comment]
Reopen with changes

**Review by Moltijoe — CHANGES_REQUESTED** [review]
update the changelog

**Comment by Moltijoe** [comment]
Balance council:
>just seems like a salty ided, this would make demons completely ineffectual for how rare they are

**Pull request closed without merging**
