### PR TITLE
Cheese Staff 2 Electric Booglaloo

### PR DESCRIPTION
**Pull request by missatessatessy**
Based on a few complaints I've revamped the code for the cheese staff to be more... palatable... I would liken this staff to be more like a very specific wabbajack staff

# General Documentation

### Intent of your Pull Request

Essentially what I've done is scrapped the hasty egg suicide code in favour of the wabbajack code. Alongside this creating a new simplemob that looks like cheese that the staff turns you into.
Differences from the old cheese staff are as follows:
- You can't directly pick it up, slice it or eat it like before, but you can pick it up using grab intent to carry it around and use harm intent to take bites out of it.
- Cheese entity can move now, exceedingly slow, but can ventcrawl which makes up for it.
- Added some googly eyes to make it more obvious there's an actual person there
- Some flavourtext added for when you get zapped
- Cheese.

### Why is this change good for the game?

Fixes bugs, and people complain about it sucking a lot. Making the staff more like the wabbajack and less terrible to live with might make it more likely to be added as an ingame item too I hope.

# Wiki Documentation

This is irrelevant as cheese staff is more of a fun feature that hasn't been officially added in game... yet.

# Changelog

:cl:  
bugfix: fixes some bugs with cheese staff
tweak: tweaks how cheese staff works code wise
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
hail cheesus

**Comment by GermanMako** [comment]
Yoggers

**Comment by Marmio64** [comment]
still too OP for it to be an ingame item, even if it would be wizard only tbh
basically just staff of polymorph but it's guaranteed to make the victim defenceless rather than just having a high chance to. Maybe if the staff had a chance to turn people into holy cheese golems it'd make it more fun and add a bit of risk to using it as wizard, since you might end up giving your target antimagic and the power of cheese

**Comment by UselessTheremin** [comment]
> still too OP for it to be an ingame item, even if it would be wizard only tbh
> basically just staff of polymorph but it's guaranteed to make the victim defenceless rather than just having a high chance to. Maybe if the staff had a chance to turn people into holy cheese golems it'd make it more fun and add a bit of risk to using it as wizard, since you might end up giving your target antimagic and the power of cheese

but its funny

**Comment by Marmio64** [comment]
> > still too OP for it to be an ingame item, even if it would be wizard only tbh
> > basically just staff of polymorph but it's guaranteed to make the victim defenceless rather than just having a high chance to. Maybe if the staff had a chance to turn people into holy cheese golems it'd make it more fun and add a bit of risk to using it as wizard, since you might end up giving your target antimagic and the power of cheese
> 
> but its funny

bet you're a average locker staff fan

**Comment by CrazyDrakkon** [comment]
A simple movement animation with alternating sideways sprites would be nice.

**Comment by UselessTheremin** [comment]
> > > still too OP for it to be an ingame item, even if it would be wizard only tbh
> > > basically just staff of polymorph but it's guaranteed to make the victim defenceless rather than just having a high chance to. Maybe if the staff had a chance to turn people into holy cheese golems it'd make it more fun and add a bit of risk to using it as wizard, since you might end up giving your target antimagic and the power of cheese
> > 
> > 
> > but its funny
> 
> bet you're a average locker staff fan

locker staff aint funny

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
