### PR TITLE
Gives the level 7 biohazard some teeth

### PR DESCRIPTION
**Pull request by YouCanBeBetterThanThat**
The level 7 biohazard event kinda sucks. Whenever it happens nobody really notices except for that one guy who got the carrier infection but never gave it to anyone because the stats suck and it's only transmissible by blood. I added some simple diseases that actually have impacts on the round as well as making the random advanced disease more powerful. Simple diseases are more likely to roll as well.

:cl:  
tweak: Buffed the level 7 biohazard
/:cl:

### CODE REVIEW

**Comment by Runian** [comment]
GBS seems too deadly to add.

**Comment by YouCanBeBetterThanThat** [comment]
> GBS seems too deadly to add.

Yeah I was thinking that because it didn't have a lot of tells and the cure is pretty hard to make, but the spreading sucks. I might make a GBS derivative that performs the same just a bit slower and easier to cure.

**Comment by maxion12345** [comment]
> > GBS seems too deadly to add.
> 
> Yeah I was thinking that because it didn't have a lot of tells and the cure is pretty hard to make, but the spreading sucks. I might make a GBS derivative that performs the same just a bit slower and easier to cure.

You under estimate the stupidity of our players. They'll run around and manage to spread even the most solitary of virus

**Comment by Sniblet** [comment]
yeah uh contact spread is apocalyptically powerful for any disease do not leave that in for one that permakills people

**Comment by JamieD1** [comment]
Thats way too strong, way too much teeth.

**Comment by SomeguyManperson** [comment]
the advanced viruses this would add are all cancer and stupid and don't show up in normal gameplay for a reason

**Comment by YouCanBeBetterThanThat** [comment]
> Thats way too strong, way too much teeth.



> the advanced viruses this would add are all cancer and stupid and don't show up in normal gameplay for a reason

Name which ones need removing please.

**Comment by JamieD1** [comment]
You have added deadly viruses to the "non advanced" section, you sure thats what you meant to do.

**Comment by YouCanBeBetterThanThat** [comment]
> You have added deadly viruses to the "non advanced" section, you sure thats what you meant to do.

Yeah, advanced viruses are usually a crapshoot because randomising symptoms tends to give you garbage. I wanted simple viruses to be the actually hard ones

**Comment by JamieD1** [comment]
> > You have added deadly viruses to the "non advanced" section, you sure thats what you meant to do.
> 
> Yeah, advanced viruses are usually a crapshoot because randomising symptoms tends to give you garbage. I wanted simple viruses to be the actually hard ones

I echo what theos said, these are not that prevalent for a reason.. I mean I guess we could try it.

**Comment by JamieD1** [comment]
Going to close this, myself and theos agree its not a good idea to make more round ending viruses more prevelant.

**Pull request closed without merging**
