### PR TITLE
NT IRN app tweaks and bugfixes part 2, cargo packs tweaks

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Heads can now open any private crate
Purchased departmental crates now use different crate sprites instead of the same private crate sprite
Departmenl/Private crates can now be sold back to CC for 500cr(same as other crates), except for small crate type packs will only be sold for 1/5 the value of the crate(100cr)
Fixes NT IRN app turning cargo budget crate into private crate (this bug existed for awhile and I forgor to fix this on my other pr as well)
Adds a new secure radiation crate that prevents radiation from leaking
Fixes fuel rods crate using non rad-proofed crate
Fixes NT IRN packs price not updating station trait modifer cost

# Why is this good for the game?
The ability to distinguish which crate belongs to which department makes sorting easier. 

departmental crates/private crates are not supposed to be excluded from selling, they are just the same ordinary crates with extra locks. The only crates should be excluded are small pack type crates because they use cheap crate types, so i include them in the other categorty

# Testing
Screenshot_21

budget10

# Spriting
image

# Changelog

:cl:  

tweak: Purchased departmental crates now use different crate sprites instead of the same private crate sprite
tweak: Departmenl/Private crates can now be sold back to CC for 500cr(same as other crates), except for small crate type packs will only be sold for 1/5 the value of the crate(100cr)
bugfix: Fixes NT IRN app turning cargo budget crate into private crate (this bug existed for awhile and I forgor to fix this on my other pr as well)
rscadd: Add a new secure radiation crate that prevents radiation from leaking
bugfix: Fixes fuel rods crate using non rad-proofed crate
bugfix: Fixes NT IRN packs price not updating station trait modifer cost
/:cl:

### CODE REVIEW

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
- heads should not be able to open people's private crates
- private crates are unable to be sold because some dickhead can just not unload your stuff that you personally paid for

**Comment by ShoziOffical** [comment]
> * heads should not be able to open people's private crates
> * private crates are unable to be sold because some dickhead can just not unload your stuff that you personally paid for

Above sure, yes.

You didn't understand, private crates can only be sold when it's fully unlocked and the goods inside are removed from the crate

**Comment by warface1234455** [comment]
> > * heads should not be able to open people's private crates
> > * private crates are unable to be sold because some dickhead can just not unload your stuff that you personally paid for
> 
> Above sure, yes.
> 
> You didn't understand, private crates can only be sold when it's fully unlocked and the goods inside are removed from the crate

**Comment by ShoziOffical** [comment]
private crates can already be sent back to cc on this pr https://github.com/yogstation13/Yogstation/pull/20421
but i forgor to remove the restriction to make it sellable

**Comment by ShoziOffical** [comment]
I made the private crates can be opened by head because sometimes assistant with a fuck load of money bought a fucking WT rifle in a private crate, arrested after but the crate cannot be opened because its locked and his ID was fucking fried and eaten by a clown

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
