### PR TITLE
Ports flying bloodsplatters from TG from Hippie for wounds

### PR DESCRIPTION
**Pull request by Moltijoe**
I am the master of copy-paste, watch as i copy paste an entire PR into being functioning code
also adds the pre-requisites of abstract_move and turf/cordon/secret

https://github.com/tgstation/tgstation/pull/63140

### About The Pull Request
image

~~This PR adds a neat feature that I believe originated from Hippiestation, but whose true original PR I am unable to locate due to their rebases. [YoYoBatty claims credit for reintroducing it after the rebase with no mention of who originally made it](https://github.com/HippieStation/HippieStation/pull/10427), so I'll just credit them for the base code~~ [(see the trail of code provenance here, thanks potato)](https://github.com/tgstation/tgstation/pull/63140#issuecomment-981542112). Basically, this PR adds flying bloodsplatters when you get badly hurt, with the additional twist that they're tied to receiving slashing and piercing wounds, as well as dismemberment, with their range scaling to the wound's severity.

[Really the best way to explain it is just to show you.](https://streamable.com/t6qgjb)

Technically it works as is, but I'm waiting on Potato's https://github.com/tgstation/tgstation/pull/62567 to get merged as well so I can get rid of the sleep() in the hitsplatter's GoTo() proc. I also added the ability for the hitsplatters to land on windows, which can be scrubbed out with soap. Pretty neat looking! I may end up toning down some of the other methods of spreading blood like how easy it is to track blood everywhere on your shoes to compensate, so janitors don't just end up with another massive source of messes to clean up, but we'll see

Why It's Good For The Game
Makes the environment feel more dynamic, adds satisfying feedback to landing bleeding wounds on people.

Changelog
:cl: @Moltijoe, Ryll/Shaps, credit to Crystalwarrior of Hippiestation
add: Suffering slashing or piercing wounds, as well as violent dismemberment, can now send bloodsplatters flying from your body that can land on walls/floors/windows/whatever in the environment. Juicy!
/:cl:

### CODE REVIEW

**Comment by TheBombMakerJL** [comment]
Secret det buff downvote downvote

**Comment by cuackles** [comment]
need gif or video of blood flying in action please

**Comment by Moltijoe** [comment]
> need gif or video of blood flying in action please

Look at the middle line

**Comment by Moltijoe** [comment]
while this functions and adds the little blood splatters ontop of the body
and it also makes additional noises when a blood wound is caused
it doesn't seem to make the trailing blood splatters for some reason
i can only guess that it's something different with our wound system that i'm not noticing

**Comment by cuackles** [comment]
> > need gif or video of blood flying in action please
> 
> Look at the middle line

i refuse to read a pr, only pictures

**Review by cuackles — APPROVED** [review]

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
