### PR TITLE
Adds real-time TTS with Piper 2.0

### PR DESCRIPTION
**Pull request by ynot01**
Duplicate of #20977 for technical reasons

# Document the changes in your pull request

At present, there are 12 voices:
- 5 female British
- 1 male British
- 3 female American
- 3 male American

There are several filters that get applied in different ways. Robots and machines will have a silicon filter applied. Lizards, aliens, and ethereals have filters attached to their tongues. Gas masks and sechailers have their own filters as well. Radio will sound more radioy than talking to someone in person.

Once I figure out model training (after this is merged preferably) we can start adding user-provided voices and maybe species-specific voices.

Backend info at https://github.com/yogstation13/yogs-tts

- [x] Do the tgui for the hear-tts pref and voice choice pref
- [x] Move the 750+ binary files to a containerized backend with build process instead of this repo
- [x] Testmerge
- [x] Add pitch preference
- [x] config dpmt wprl
- [x] make TTS into a subsystem
- [x] keep an array of ongoing phrases and deny any incoming requests that are in that
- [x] radio too loud - make a volume pref for both radio and in-person
- [x] slight delay in speech
- [x] gas mask + radio amplifies volume
- [x] kill spam violently
- [x] ai stating laws sounds awful - make it slower
- [x] preview TTS button does not apply filters correctly
- [x] Implement a filter to correct phonetic pronunciations i.e. IPC -> I.P.C.
- [x] ~~Fix ghosts hearing non-radio TTS from other z levels~~ Would break multi-z TTS
- [x] Fix silicons not being able to choose their voice
- [x] Fix AIs hearing themselves twice over radio
- [x] Support all characters via JSON instead of sanitizing them
- [x] fix preview TTS being available before it should be and some potential errors from that
- [x] Figure out and resolve loads of HTTP 500 errors
- [x] Update backend on live to apply the JSON change
- [x] Update chameleon mask with some sick ass TGUI to be able to select your voice
- [ ] Kill tachyon-doppler research array
- [ ] Remove asterisk spam on comms whispering/ionospheric
- [ ] Add filter options to chameleon mask
- [ ] Fix lizards being abnormally quiet
- [ ] API fetch voices (backend)
- [ ] API fetch voices (frontend)

# Why is this good for the game?
Muh immersion

# Testing
https://github.com/yogstation13/Yogstation/assets/28408322/f5f0c309-32b7-4ecc-ae7b-18f7a58b6989

https://github.com/yogstation13/Yogstation/assets/28408322/14dcc4b7-c427-4b02-aeae-ed170ef84b3e

# Changelog

:cl:  
rscadd: Added TTS
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
ok I fucking burst out laughing when I heard Poly, god fucking damnit

**Comment by Addust** [comment]
make voicechanger masks able to change your voice

**Comment by Addust** [comment]
i would highly recommend muting research consoles, vending machines, voice recorders, and machines in general bar the arrivals announcer, for my hubris has caused my death

**Comment by AMyriad** [comment]
small issue: I appear to be able to hear IC radio chatter from the game lobby
audio:
https://github.com/yogstation13/Yogstation/assets/143908044/bcf215c1-c83e-40c5-844b-f99114bd3998

**Comment by bruhlookatthisdood** [comment]
During testmerge, when talking into departmental radio (atleast as AI) you will hear double the TTS

**Comment by ynot01** [comment]
> small issue: I appear to be able to hear IC radio chatter from the game lobby audio

Fixed

**Comment by ynot01** [comment]
> i would highly recommend muting research consoles, vending machines, voice recorders, and machines in general bar the arrivals announcer, for my hubris has caused my death

Research consoles & voice recorders now print to chat instead of speaking aloud.

**Comment by Spacemanspark** [comment]
Voice changers are a bit screwed with this PR, it seems--it fails to take on the voice of the person you're attempting to imitate, doubly so if that person is, say, wearing a security gas mask.

**Comment by DeadlyBag** [comment]
This has been very fun!
Theres one big issue i have though, ASTERISKS ASTERISKS ASTERISKS ASTERISKS ASTERISKS ASTERISKS
If that was fixed the quality would drastically increase imo
There are also some smaller miss pronounciations and stuff but thats just minor stuffs

**Comment by Cartlord** [comment]
I appreciate that there's a pref to turn these off, and I myself will be using it since they sound pretty awkward in-game (especially with multiple speakers). I'm assuming (though it's hard for me to understand the wording of the licensing) that these voices are all used with consent of whoever they belong to, rather than just being made from random people without their knowledge?

**Comment by Absolucy** [comment]
If you get monkied and then unmonkied, it seems that your TTS voice gets randomized/reset?

**Comment by ynot01** [comment]
> I appreciate that there's a pref to turn these off, and I myself will be using it since they sound pretty awkward in-game (especially with multiple speakers). I'm assuming (though it's hard for me to understand the wording of the licensing) that these voices are all used with consent of whoever they belong to, rather than just being made from random people without their knowledge?

All voice licenses can be viewed here https://github.com/yogstation13/yogs-tts/tree/master/piper-voices under MODEL_CARD files

**Comment by Cartlord** [comment]
I've taken a look at the projects cited & their datasets, and I must thank & congratulate you for (seemingly) managing to only use A.I. trained on ethically collected data. The only issues I have are that two (US-amy and US-danny) link to https://github.com/MycroftAI/mimic3-voices without saying exactly which of the entries on the page they are (meaning i can't check how the data was collected), and that one (US-kusal) links to https://github.com/MycroftAI/mimic2 , which is not a voice repository or dataset at all but a model for training A.I.s off them.

**Comment by ynot01** [comment]
> I've taken a look at the projects cited & their datasets, and I must thank & congratulate you for (seemingly) managing to only use A.I. trained on ethically collected data. The only issues I have are that two (US-amy and US-danny) link to https://github.com/MycroftAI/mimic3-voices without saying exactly which of the entries on the page they are (meaning i can't check how the data was collected), and that one (US-kusal) links to https://github.com/MycroftAI/mimic2 , which is not a voice repository or dataset at all but a model for training A.I.s off them.

Voices amy, danny, kusal retrieved from:
https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0/en/en_US

Licensing information was not changed when porting files

All files demand `* License: See URL`, linking to the below two repositories

amy & danny reference [MycroftAI/mimic3-voices](https://github.com/MycroftAI/mimic3-voices), which is licensed under [Creative Commons Attribution Share Alike 4.0 International](https://github.com/MycroftAI/mimic3-voices/blob/master/LICENSE)

kusal references [MycroftAI/mimic2](https://github.com/MycroftAI/mimic2), which is licensed under [Apache License 2.0](https://github.com/MycroftAI/mimic2/blob/master/LICENSE)

It should be noted that [amy](https://github.com/MycroftAI/mimic2/blob/master/datasets/amy.py) and [kusal](https://github.com/MycroftAI/mimic2/blob/master/datasets/kusal.py) are referenced in the [MycroftAI/mimic2](https://github.com/MycroftAI/mimic2) repository, but no differing licenses or datasets are indicated

Because the datasets used to train these voices are not available on the repositories linked, it can only be assumed that the repository LICENSE file must be used because of the instruction `* License: See URL`

CC BY-SA 4.0 DEED is complied with by the links provided on the repository README and supplied unadulterated MODEL_CARD files

**Comment by Cartlord** [comment]
I never meant to imply the license was the problem - that's all clearly above-board. I was only concerned with looking through the datasets to see how the data was collected, and my issue was just that not all of them were wholly transparent with where they got their data - I was trying to make sure it was all either from the public domain or collected from people who volunteered to train A.I..

**Comment by JamieD1** [comment]
I like em

**Review by JamieD1 — APPROVED** [review]

**Comment by ToasterBiome** [comment]
Maybe some other time, nice experiment.

**Pull request closed without merging**
