### PR TITLE
i'm BORED i'm going to REDESIGN SYNDICATE LAVALAND

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

Entirely rebuilds Syndicate Lavaland from the ground up.
Adds the Syndicate Red Phone as an IC way for both Syndicate Lavaland and the Listening Post to contact admins, either to request emergency aid or other shit.

# Why The Fuck Am I Doing This
Syndicate Lavaland is stale, structurally speaking. Its atmospherics systems are outdated and nowhere near complicated enough, and it doesn't really feel very fun. At the same time, the self-destruct being to the right of the base both reduces how potent it is and allows for miners to easily cheese it.
As such, behold, DONUT SYNDICATE LAVALAND.

The Syndicate red phone is added as a way to contact the admins ICly, either to request equipment, give them a basic status report, other RP bullshit, or for emergencies.

Draft in order to get more features in while also garnering opinions.

Also, the prototype cloner is fucking hilarious and creates supply scarcity when you've got like 20 syndies armed with improv shotguns and sheer fucking will or something I dunno

# Wiki Documentation

update the wiki image

# Changelog

:cl:  
rscadd: i was BORED so i REDESIGNED SYNDICATE LAVALAND
rscadd: the bomb's in the middle
rscadd: it's also got a goonstation reference (bar monke name)
rscadd: the Listening Post and Syndicate Lavaland now have a unique 'syndicate red phone' as an IC way to talk to the admins.
/:cl:

### CODE REVIEW

**Comment by Rdrazga** [comment]
I mean step 2 to making this ruin more interesting would be give them actual virus bounties/goals to fill for added gear

**Comment by Addust** [comment]
if i learn to code i could do that, i'd put up a bounty but No

**Comment by Necrosium** [comment]
Looks fun, if only it was more roundy... I also never found a reason to have a cargo spot for the syndicate base, I'd hope for it to be functional someday... (insert evil laughter)

**Comment by N3D6** [comment]
I like it, do you intend to make their cargo functional though?

**Comment by Addust** [comment]
if i learn DM

**Comment by Addust** [comment]
image
FISHING VENDOR ADDED TO CARGO. WE'RE OUTTA DRAFT BOYS

**Comment by Addust** [comment]
i mean i could probably create a subtype of the cargo console and make it use idk some sorta syndi coin and give different supplies but thatd take a century

**Comment by tattax** [comment]
does this fix https://github.com/yogstation13/Yogstation/issues/19057 ? (assuming this is the syndie base mentioned)

**Comment by Addust** [comment]
> does this fix #19057 ? (assuming this is the syndie base mentioned)

no, that applies to the nukie base

**Comment by tattax** [comment]
makes sense

**Comment by Marmio64** [comment]
This has neat additions, but I much prefer the original's overall design, especially the very unique bar lava 'patio'.

**Comment by neeshacark** [comment]
I don't think you hit the mark on this one, I prefer the old one.  This one seems much more boxey and overall shrunken.

**Comment by Addust** [comment]
> This has neat additions, but I much prefer the original's overall design, especially the very unique bar lava 'patio'.
could do something about the bar patio idea using a bit of the space taken up by the cloner crate



> I don't think you hit the mark on this one, I prefer the old one. This one seems much more boxey and overall shrunken.
i can try to round out the structure better, putting back in draft

**Comment by Addust** [comment]
size comparison
image

**Comment by Addust** [comment]
> I don't think you hit the mark on this one, I prefer the old one. This one seems much more boxey and overall shrunken.

added some structural corners, check the diffbot



> This has neat additions, but I much prefer the original's overall design, especially the very unique bar lava 'patio'.


patio designed and added! i also ripped out and redid the entire bar, was a bit hasty may change later
image

**Comment by Addust** [comment]
bar seems better now, undrafting

**Comment by MajManatee** [comment]
I dont really like how easy it would be to get in from the top right. Maybe make that empty pad area a bit smaller, like 3-4 tiles of lava to the base i reckon.

**Comment by MajManatee** [comment]
I dont really like how easy it would be to get in from the top right. Maybe make that empty pad area a bit smaller, like 3-4 tiles of lava to the base i reckon.

**Comment by Addust** [comment]
> I dont really like how easy it would be to get in from the top right. Maybe make that empty pad area a bit smaller, like 3-4 tiles of lava to the base i reckon.

okie dokie

**Comment by neeshacark** [comment]
virology is still a bit too shrunken for my tastes  but the new changes fixed most of my issues

**Comment by Addust** [comment]
if i really had to i could find space to expand it but the base feels finished enough as-is and viro has all the (bare minimum) features of the original

**Comment by SomeguyManperson** [comment]
Does the little rock area with the pickaxe allow the syndicate guys with snipers to leave the syndicate listening outpost they are not supposed to abandon

**Comment by Addust** [comment]
it doesnt, there's still lava around

**Comment by Addust** [comment]
i'm trying to fnagenglegeagn it

**Comment by Addust** [comment]
THIS IS GOING TO BREAK EVERYTHING BUT I'M GOING TO DO IT ANYWAY!!

**Review by cuackles — APPROVED** [review]

**Review by Aquizit — CHANGES_REQUESTED** [review]
image
All of your airlocks to the outside are missing helpers.

image
Missing disposals unit.

image
I think I'd like the poster directly next to the disposals unit, I wasn't sure how I felt about the APC right next to the thing either since it implies you're wiring around a big fuckin' tube that's sticking up through the floor, so trading places of these would work probably.

image
I admit I'm not sure what's going on here, if it's a sprite issue or a fastdmm issue or whatever.

**Comment by Addust** [comment]
> image All of your airlocks to the outside are missing helpers.
> 
> image Missing disposals unit.
> 
> image I think I'd like the poster directly next to the disposals unit, I wasn't sure how I felt about the APC right next to the thing either since it implies you're wiring around a big fuckin' tube that's sticking up through the floor, so trading places of these would work probably.
> 
> image I admit I'm not sure what's going on here, if it's a sprite issue or a fastdmm issue or whatever.

done

**Comment by Aquizit** [comment]
image
Missed this last time you'll *probably* want helpers here to help the comms room keeping cold, but otherwise map's fine now.

**Review by Aquizit — APPROVED** [review]

**Comment by Addust** [comment]
i mean all the airlocks use tiny fans just like the original base

**Comment by Aquizit** [comment]
I saw, just feels weird if both stay open like I know space bar has the fans but also does the helpers for the externals.

**Comment by Addust** [comment]
image

**Review by JohnFulpWillard — APPROVED** [review]

**Comment by Addust** [comment]
AAAAAAAAAAAAA

**Pull request merged**
