### PR TITLE
Reverses colors on med doctor sec hud to make it more different from the CMO

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Reverses the MD's color scheme to help differentiate it from the CMO

image

# Wiki Documentation

Update the sechud image for MD

# Changelog

:cl: 
tweak: tweaked medical doctor sec hud icon
/:cl:

### CODE REVIEW

**Comment by nmajask** [comment]
I think this makes it look too much like the healthy icon from the med hud and breaks the convention of the other sec hud icons, that being the color of the shape on the icon is white, while the background and rim are the department color.

**Review by nesisknesis — COMMENTED** [review]
I agree with nmajask, it's more consistent in its current form, and distinguishes more between a secHUD and medHUD

image
image

will close in a day or so unless given reason not to

**Comment by adamsong** [comment]
It looks too similar to the CMO's though

**Comment by adamsong** [comment]
I have a different idea, might also get shot down, but we will see in the PR

**Pull request closed without merging**
