### PR TITLE
New implants for ERTs and Nuclear Operatives: Biosignallers

### PR DESCRIPTION
**Pull request by AMyriad**
# Document the changes in your pull request
---

So I saw this comment in #20906:
image
And I liked the idea, so I coded it!
Credit for most of the implant code goes to @Runian

---

So what the hell is this?
All Nuclear Operatives and Emergency Response Teams with mindshields now spawn with a Biosignaller implant which broadcasts when and where a team member has died over their respective radio channel (Centcom radio for ERTs, Syndicate radio for nukies).

**Unlike the previous Death Alarm implants, these are not affected by EMPs.**

# Why is this good for the game?
I've seen many situations where both ERTs and nuke ops are left wondering how many people are left in their squad, sometimes because half the team walked off from the group to die in a corner somewhere, or they went in guns blazing and were gunned down instantly. And unlike the crew, ERTs never really keep track of each others' suit sensors, and nuke ops don't have sensors to track, so they both have to play it by ear to keep track of who's dead and who's alive.

I also don't like the idea of teammates being possibly left behind because they took an EMP hit or two, so I removed the implant being affected by that.

### Current version of the implant doesn't suit the game? I can change them in the following ways:
- I can make them be affected by EMPs again, similarly to how Death Alarms were.
- I can make the ERT version delete itself after being used (the nuke ops one does, the ERT one currently doesn't).
- ~~I can make the implant state the user's role (ERT engie, ERT medic, nukie leader) instead of a name.~~ When I figure out how
- I'm also open to any suggestions, including text suggestions!

# Testing
ERT variant:
biosig1

Nuke Ops variant, with bonus encouraging message for any surviving team members:
biosig3
biosig2
biosig4

Everything tested extensively, and _should_ be in working order.

# Wiki Documentation
Probably worth mentioning on the ERT and nuke ops pages that this exists.
Definitely worth mentioning on the implants page that this exists.

# Changelog
:cl:  
rscadd: Added Biosignaller implants to nuke ops and ERTs, which alert their teammates when and where they died
/:cl:

### CODE REVIEW

**Comment by dcxgame** [comment]
How many mojas died to bring us that screenshot?

**Comment by ofscarletdreams** [comment]
are you adding the last member alive warning

**Comment by AMyriad** [comment]
> How many mojas died to bring us that screenshot?

Too many...

**Comment by AMyriad** [comment]
> are you adding the last member alive warning

Probably not here, but sometime in the future, yes

**Comment by MajManatee** [comment]
Now all I need is one of those monitors that has everyone's heartrates like so 
image
So I can sit in my fancy chair at centcom HQ and watch my pawns die.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
