### PR TITLE
[READY]Xeno Rework: Less annoying edition

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Partially uses code from https://github.com/yogstation13/Yogstation/pull/14143

So, what it does now:

Neurotoxin  - now deals 135 stamina damage, meaning that it is still a stun, but can be countered by chems.

Acid - is buffed, now it has x2 effectivity

Xeno quen now has an antag datum!

Hunter's stealth - hunter is less visible now while using this ability.

Aliens now got some movespeed changes, hunters slightly slowed down

Code changes:

Aliens now have movespeed and damage variables, that means that it is more easy to rebalance them... or, for example, to add a new caste, who knows.

# Wiki Documentation

Mention that neurotoxin now works only on guys without hardsuits.

# Changelog

:cl: IndieanaJones, ported with some changes by SuperSlayer
tweak: Neurotoxin now deals 135 stamina damage instead of just stunning
tweak: Slightly changed alien movespeed
rscadd: Xeno queen now has an antag datum
tweak: Acid is buffed
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Still don't like any of these nerfs, especially the neurotoxin one, how the hell are xenos going to deal with the jetpack hardsuit guy sniping them with space? The other misc stuff is nice though.

**Comment by ghost** [comment]
> Still don't like any of these nerfs, especially the neurotoxin one, how the hell are xenos going to deal with the jetpack hardsuit guy sniping them with space? The other misc stuff is nice though.

People need a way to somehow counter neurotoxin. Perhaps, i can try to make it just deal something like 125 stamina damage, that will normally stun, but can be countered by chemicals.

**Comment by Marmio64** [comment]
> > Still don't like any of these nerfs, especially the neurotoxin one, how the hell are xenos going to deal with the jetpack hardsuit guy sniping them with space? The other misc stuff is nice though.
> 
> People need a way to somehow counter neurotoxin. Perhaps, i can try to make it just deal something like 125 stamina damage, that will normally stun, but can be countered by chemicals.

Shields should counter them, you just need to face the enemy. So go in a 1x1 hallway and/or don't turn your back on em. Or get in the almighty Mecha or be hulk.

**Comment by ghost** [comment]
Hulks were removed!

**Comment by JamieD1** [comment]
Think Aliens are fine where they are right now.

**Pull request closed without merging**
