### PR TITLE
Spythief

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

see: https://wiki.ss13.co/Spy_Thief for the general gist of it. 

Still WIP, things that need to be done are:

- [ ] Make the photo bounty actually check whether the right person is in the photo.
- [ ] Make the bounty check check whether the redeemer is in the right area.
- [ ] Add actual objectives
- [ ] Add the list of possible redemption areas for bounties to choose from
- [ ] Add the full list of bounties (this one is easy, but tedious
- [ ] The UI for the telebeacon to show all the bounties.

#### Changelog

:cl:  Nichlas0010, a sprite by KMC
rscadd: New gamemode, called spythief (stolen shamelessly from goon)
rscadd: Syndicate spies are sent to the station, to complete bounties for the syndicate. These bounties can either be a personal item, a station item, a machine, an organ or a photo of someone. 
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
miscreants when also nice

**Comment by Amelia0010** [comment]
meh, noone wants it anyways

**Comment by Nickvr628** [comment]
Nich being a baby by breaking all the new toys when he throws a tantrum and leaves. What's new!

**Comment by fluffe9911** [comment]
Aw

**Comment by nichlas0010** [comment]
What the fuck are you talking about now? I intentionally didn't delete my branch so anyone could take this and work on it further, without having to go through copy+paste hassle, so nothing was fucking broken. 

There was literally no reason whatsoever to keep this PR open when I wasn't gonna work on it anymore. Literally none. Noone else can push to my branch, so this PR would literally just sit here for the next 2 weeks untill either mcdonald or ling close it for being stale. 

@Nickvr628 please explain what the alternative to me closing this is, when I'm not gonna work on it anymore you fucking moronic imbecile.

**Comment by nichlas0010** [comment]
@Nickvr628 I said explain, not downvote. You can't criticize me for doing something if you yourself is too much of an idiot with a lack of brains to actually come up with a superior solution.

**Comment by nichlas0010** [comment]
@Nickvr628

**Comment by nichlas0010** [comment]
@Nickvr628

**Comment by AsV9** [comment]
image

**Comment by nichlas0010** [comment]
@Nickvr628

**Comment by nichlas0010** [comment]
@Nickvr628

**Comment by nichlas0010** [comment]
@Nickvr628

**Comment by nichlas0010** [comment]
@Nickvr628

**Comment by nichlas0010** [comment]
@Nickvr628

**Comment by nichlas0010** [comment]
@Nickvr628 you're a moronic shit-for-brains idiot, who has no actual ability to tell truth apart from lies

**Comment by nichlas0010** [comment]
@Nickvr628 Oh and you are completely unable to accept ever being wrong, and routinely change your story/point so you can keep a scrap of being right, and if that fails you either resort to not responding, or going "no u"

**Comment by nichlas0010** [comment]
@Nickvr628 It's amusing to think that you're the kind of person who complains about leftist snowflake safe spaces, while you yourself cannot comprehend the notion that you might be wrong, and wish you were in a place where everyone agrees with you

**Comment by nichlas0010** [comment]
@Nickvr628 You're the kinda person who does whatever you can to discredit anyone who disagrees with you, whether it's lying, willfully misinterpreting things, misquoting or being incredibly hypocritical.

**Comment by Oakboscage** [comment]
@Nickvr628 fucking retard

**Pull request closed without merging**
