### PR TITLE
Revert "Synergy" PR that changed standart lizard name generation

### PR DESCRIPTION
**Pull request by Ratvar**
Reverts yogstation13/Yogstation#6737
For long, three lizard name types were accepted on yogs: Name-The-Nouns, ashwalker-like Garshinshin-Klrch and human-like Trey Lorenzo. 
Of those three templates, only second one is hard to make: first one is assembled with simple words and has meaning behind the phrase, third one is made by using human name generator. 
I don't think nich's change was good because it ignores how lizard players actually name their characters, which is accepted by other admins, and because it's hard to make Bursh-Cuhk names and easy to make Nouns-the-Verbs names, which means Reeef-Bajr names need randomizator more, hence the revert.
🆑
tweak: Reeef-Bajr's protest gives a rise to classical lizard names across NT
/🆑

### CODE REVIEW

**Comment by ThatGuyPhil** [comment]
as a fellow lizard main i approve of this

**Comment by jcatjmeow** [comment]
Verbs the noun type names are a dumbass elder scrolls reference to argonians, so take that as you will

**Comment by Sir-Lagsalot** [comment]
Speaking as someone with a lizard quite literally named "Verbs-the-Nouns", I think the ashie-style Grzzzztgah-Desdfsdgfe names are a lot better, and the change was one that Nich literally made on a whim because he found a random corporate-buzzword generator and thought it was funny.

**Comment by Amelia0010** [comment]
:)

**Pull request merged**
