### PR TITLE
ports spike baseball bat and metal baseball bat from hippie (port)

### PR DESCRIPTION
**Pull request by boodaliboo**
original pr https://github.com/HippieStation/HippieStation/pull/7547
this brings the spike baseball bat and metal one from hippie
the spike one is only available using the traitor book makeshift weapons
image
image

#### Changelog

:cl:  
rscadd: Adds two new baseball bats metal is currently admin only
imageadd: ported hippie sprites  
/:cl:

### CODE REVIEW

**Comment by overlord12345** [comment]
metal bat alredy exists

**Comment by boodaliboo** [comment]
> metal bat alredy exists

oh lol should i remove it from the pr?

**Review by JamieD1 — APPROVED** [review]

**Comment by Ktlwjec1** [comment]
Yeah remove metal bat, already exists in the same file.

**Comment by boodaliboo** [comment]
> Yeah remove metal bat, already exists in the same file.

done

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Remove the metal sprites or add the code for the metal bat. You choose

**Comment by boodaliboo** [comment]
ugh fine

**Comment by boodaliboo** [comment]
fuck this

**Pull request closed without merging**
