### PR TITLE
Toolbelts can hold construction bags

### PR DESCRIPTION
**Pull request by Hopekz**
It seems like an oversight.
They literally have the place for the belt on the sprite itself

image

#### Changelog

:cl:  Hopek
rscadd: Construction bags can now be put on the toolbelt
/:cl:

### CODE REVIEW

**Comment by Jumps0** [comment]
maybe this could be done with other bags as well :thonk:

**Comment by maxion12345** [comment]
speedmerge

**Comment by JamieD1** [comment]
Pretty sure its for the jumpsuit belt not a belt on a belt

**Comment by Hopekz** [comment]
Its already been more than a full week without other maintainer activity and its a 2 line change so it can't be for code reasons.
Seeing the feedback on this PR I feel confident in merging this.

As far as code quality I am 100% confident in this change being acceptable.

**Pull request merged**
