### PR TITLE
Martial Arts: Corporate Judo

### PR DESCRIPTION
**Pull request by Runian**
# Document the changes in your pull request
Ports [#21229](https://github.com/ParadiseSS13/Paradise/pull/21229) with changes.

Adds a martial arts called "Corporate Judo".
image

Adds a bulky sized belt to the HoS locker that grants Corporate Judo for them to use personally or to hand it to an officer of their choice.

Adds a temporary blindness debuff that #18514 forgot to add.

# Why is this good for the game?
Provides an way for people to learn how martial arts combos work without having to sign up as a cook or rolling antag. A unique, situational, and arguably worse alternative to the stunbaton. Fun.

# Testing
Combos all work. Belt gives the martial arts. It properly spawned in the HoS locker.

# Spriting
In-belt: 
image
Right-hand:
image
Left-hand:
image

# Wiki Documentation
Add it somewhere to https://wiki.yogstation.net/wiki/Security_Items. Include combos mentioned above.

# Changelog
:cl: Runian, Silverplate, AVeryReluctantSpider
rscadd: Corporate Judo. An alternative method to apprehend criminals in a melee instead of with a stun baton.
rscadd: HoS locker now starts with a belt that grants Corporate Judo.
imageadd: Corporate Judo sprites.
/:cl:

### CODE REVIEW

**Comment by PibeCantina** [comment]
I HATE CONFUSION I HATE CONFUSION I HATE CONFUSION I HATE CONFUSION I HATE CONFUSION

I like this

**Comment by iloveloopers** [comment]
this is silly

**Comment by Therandomhoboo** [comment]
Right hate this for the following reasons:
Wardens have Krav, rework that and make it better because it seems shitty to have two high ups have access to CQC

Security already have a mass arsenal to deal with threats, giving them another additional of powergame loot isn't the way

The fact that they can blur your vision for 20 seconds and then blind you for 4 seconds is a right shit because blurry is as good as blind and with the 4 seconds of blind its already game over and with the 20 additional seconds (16 cause they look like they both proc I think) its way overpowered. So if this does **HAVE** to stay then can we get B.C or people to tweak the numbers to reasonable levels?

The fact that HoS gets a gun that has 3 settings, their normal energy gun, free armoury access and a thick clothing trenchcoat already makes HoS formidable so why this?

Martial arts fucking suck and I wish for it to die and break honestly.

**Comment by Runian** [comment]
If you manage to get clicked twice, you already lost to a stunbaton (70x2 stamina damage). If you managed to get clicked twice, you get funny eye poke or the judo kick (which gets you a debuff of some kind and at most 25 stamina damage). I don't see how this makes more "formidable" if stunbaton is just better.

**Comment by Therandomhoboo** [comment]
> If you manage to get clicked twice, you already lost to a stunbaton (70x2 stamina damage). If you managed to get clicked twice, you get funny eye poke or the judo kick (which gets you a debuff of some kind and at most 25 stamina damage). I don't see how this makes more "formidable" if stunbaton is just better.

The difference is that I can shove a officer into a wall, stopping their stunbaton attempt or do more things than get hit by blind, then suffer long as fuck blurry so I can virtually do nothing?

Or the fact that you can eyepoke someone and either judo throw them or take the belt off and finish the job. 

Add a CD to wearing the belt or something to at least force the HoS/Sec to commit to the belt considering by the looks of it they can use it everywhere too.

**Comment by Runian** [comment]
I can agree that it is a buff in a way that an officer can't lose their fighting tools with this. But if you're in a position where you're terribly out geared and woefully under prepared for security, you already lost unless you're fighting a 0-hour security officer who will practically give you their stun baton for free.

If you're actually prepared for security, you would never enter a melee without a upper hand anyways.

**Comment by UltraBigRat** [comment]
Honestly my main question here is, does this take up a weapons slot space law-wise for the hos? cause it probably should, one less gun theyre allowed for funny martial arts.

**Comment by JamieD1** [comment]
I hate martial arts

**Comment by Yarinoi** [comment]
are flashbangs usable with this on

**Comment by Moltijoe** [comment]
Balance Council:
>Since this locks the user out of regular equipment, it's either going to be a strict buff to security, or noob bait
If it didn't lock the user out of regular equipment, it would just be a strict buff to security
It being HoS only means it's not exactly "for people to learn how martial arts work"
This also effectively does what the krav maga gloves were trying to do, probably better to rework those if anything

**Pull request closed without merging**
