### PR TITLE
Welcome To Yogstation 13, Enjoy Your Stay.

### PR DESCRIPTION
**Pull request by UselessTheremin**
# GUYS I FOUND THAT VOICE CLIP OF MOJA AND GAVE IT REVERB AND SHIT CHECK IT
https://cdn.discordapp.com/attachments/731402515970654233/817056736711147560/ApproachingTG.ogg

### Intent of your Pull Request

When arriving the shuttle now says "Welcome to yogstation 13 enjoy your stay" instead of "welcome to tg station"

### Why is this change good for the game?

we aint tg now are we

:cl:  
rscadd: arrivals shuttle now says welcome to yogstation, voice clip by moja
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
While I like the removal of the TG part, it's a bit jarring that it's the only announcement/intercomm voice line that is not voiced by the AI

**Comment by swissloaf** [comment]
Credit to Swiffloaf for retrieving the files from the depths of hell and also cleaning them up

**Comment by UselessTheremin** [comment]
> While I like the removal of the TG part, it's a bit jarring that it's the only announcement/intercomm voice line that is not voiced by the AI

yeah well its the same case with beestation and in the time ive played on there its worked out fine

**Comment by UselessTheremin** [comment]
> Credit to Swiffloaf for retrieving the files from the depths of hell and also cleaning them up

you dont get any brownie points nerd 😠

**Comment by Reed0506** [comment]
its probably fine and stuff, but it just feels wrong to me.

**Comment by redmoogle** [comment]
> 
> 
> its probably fine and stuff, but it just feels wrong to me.

yeah this is like soul vs soulless but it really is soulless

**Comment by PrinceKirze** [comment]
i really like this but it's slightly quiet, maybe bump the gain/volume a bit?

**Comment by Georgeur** [comment]
hey I think it could use some ambience like a smidge of record static, but this is good shit, take my updoot!

**Comment by Marmio64** [comment]
the voiceover sounds like an unpaid intern worker being forced to say the line

**Comment by JamieD1** [comment]
eh

**Comment by JamieD1** [comment]
Will need a general complete announcer overhaul if we are going to do it.

**Pull request closed without merging**
