### PR TITLE
CLOCK AND BLOOD TORTURE (new gamemode)

### PR DESCRIPTION
**Pull request by SomeguyManperson**
based off Citadel-Station-13/Citadel-Station-13#10732

Bloodcult stuff will be integrated soon

Adds a NEW GAMEMODE (oh no not again) with a small team of cultists (scaling 1 per 20 players up to 3) from both clock and bloodcults (to be seen later in a DLC expansion pack) are on the station among normal traitors. These cultists are *unable to convert* and have had some spells removed or nerfed, and have more traitor-like objectives INCLUDING
Implant objective: implant x crew (scaling randomly 1-5 per cultist) with a special implanter that can be created by using a replica fabricator or twisted construction spell(DLC) on any station implanter. This gives the implantee a special objective to not lose the implant and knocks them out for a bit.
Soul extraction: find and steal the soul of a crew member using a special item gained from using a replica fabricator or twisted construction spell(DLC) on an MMI or positronic brain
and the NEW AND IMPROVED TEAM ESCAPE OBJECTIVE
Escape with one survivor: Since cult powers include the use of revival from death, any cultist can die and still count as escaped *as long as they still actually escape.* No more losing because your teammate decided it'd be funny to go get themselves killed then spawn ~~and suicide~~ as a free miner!

#### Changelog

:cl:  Theos for gamemode stuff, kevinz000 for cultless-cult code
rscadd: Adds a new gamemode: traitorcult. Like traitorbros, but with slower scaling and cult powers/themed objectives for the brother teams.
rscadd: cultists can be made without making a cult team for more gimmick stuff
/:cl:

### CODE REVIEW

**Comment by swissloaf** [comment]
aka Hand of God

**Comment by SomeguyManperson** [comment]
no that's later

**Comment by silicons** [comment]
madman

**Comment by alexkar598** [comment]
This PR will be closed in 24 hours due to being in a Work in Progress state for too long (2 weeks+). It will be reopened on request on completion. This is an effort to keep the PR queue clean.

**Pull request closed without merging**
