### PR TITLE
Makes AI data core warnings be sent to AIs deployed in shells too

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

less cringe

# Wiki Documentation

# Changelog

### CODE REVIEW

**Comment by JamieD1** [comment]
Changelog

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
changelog

**Comment by Bibby0110** [comment]
> Changelog



> changelog


No. This doesn't need a changelog, it's fixing an oversight.

**Comment by JamieD1** [comment]
> > Changelog
> 
> > changelog
> 
> No. This doesn't need a changelog, it's fixing an oversight.

Im not merging it until you make your PR body less cringe

**Comment by Bibby0110** [comment]
> > > Changelog
> > 
> > 
> > > changelog
> > 
> > 
> > No. This doesn't need a changelog, it's fixing an oversight.
> 
> Im not merging it until you make your PR body less cringe

done

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
