### PR TITLE
Fixes Gangrel Transform

### PR DESCRIPTION
**Pull request by jachlompsky**
# Document the changes in your pull request

Gangrel clan's Transform ability should now give you armor and increased punch damage like it's supposed to instead of just making you a regular felinid/lizard/gorillaperson

# Changelog

:cl:  
bugfix: gangrel transform now gives the user armor and increased punch damage
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Fix turning from humans to felenids i don't want to turn into an unholy abomination just for some damage and armor 🥺🥺🥺🥺🥺🥺

**Comment by ToasterBiome** [comment]
> Fix turning from humans to felenids i don't want to turn into an unholy abomination just for some damage and armor 🥺🥺🥺🥺🥺🥺

feature not bug

**Comment by SomeguyManperson** [comment]
> > Fix turning from humans to felenids i don't want to turn into an unholy abomination just for some damage and armor 🥺🥺🥺🥺🥺🥺
> 
> feature not bug

arent you one of the poeple who complained about drake blood turning you into a liazrd

**Comment by ghost** [comment]
> > > Fix turning from humans to felenids i don't want to turn into an unholy abomination just for some damage and armor 🥺🥺🥺🥺🥺🥺
> > 
> > 
> > feature not bug
> 
> arent you one of the poeple who complained about drake blood turning you into a liazrd

No.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
