### PR TITLE
fixes hypospray vendor being free because i hate medbay

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
to clarify, it showed as costing money to medical doctors when it wasnt, and to people who werent medical doctors it showed as costing money and didn't charge you when you bought it, which it should.

:cl:  
bugfix: fixed hypospray vendor being free
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
elaborate? and why does everything now have 10x its normal stock? I think you misunderstand vending code greatly

**Comment by MajManatee** [comment]
Fairly certain this was intentional, and not a bug too.

**Comment by azzzertyy** [comment]
> Fairly certain this was intentional, and not a bug too.

it absolutely was not intentional, comment even says so, "all of this shit costs money" and they all had their prices labled in-game but did not charge, it should be free to meddoctors out of the medical budget but not to other crewmembers

> elaborate? and why does everything now have 10x its normal stock? I think you misunderstand vending code greatly

believe youre correct, woops, my bad, but yes. everything previously was free because vending machines NEED non premium stock to work, you cant just set everything they sell to premium because that causes it to not work properly

**Comment by hedgehog1029** [comment]
this was broken by my vending custom compartment PR when I refactored the vending code into multiple procs. i've fixed the underlying issue in #19092, premium-only vending machines work fine again

**Comment by MajManatee** [comment]
no longer relevant

**Pull request closed without merging**
