### PR TITLE
Replaces a Medbay sleeper with a stasis bed

### PR DESCRIPTION
**Pull request by Hopekz**
Perfectly balanced, as all things should be.

People have been talking about this for months but no-one has done this PR for some reason.
Putting this PR out so it can be discussed or finally changed.

image

#### Changelog

:cl:  
tweak: Replaced a Medbay sleeper with a stasis bed. Perfectly balanced, as all things should be.
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Have u considered replacing the operating table with one instead? Surgeries have the same chance of success on a stasis bed, and i think it would be a fitting place for it

**Comment by ynot01** [comment]
contrary to your changelog this is not balanced, this is a clear strict buff

**Comment by Hopekz** [comment]
> Have u considered replacing the operating table with one instead? Surgeries have the same chance of success on a stasis bed, and i think it would be a fitting place for it

I can make this PR in a few if you want. 
I just want all these things to finally get discussed and possibly merged if this is what people want.

To be fair that sounds more in-line with an "upgrade" that should be performed mid-round. I like the surgery table being used but I'm not going to shoot down your idea and would like to give it a chance.

> contrary to your changelog this is not balanced, this is a clear strict buff

Before change: 2 sleepers 0 stasis beds
After change: 1 sleeper and 1 stasis bed
Perfect harmony

**Comment by jcatjmeow** [comment]
Ok but, as it if this pr merges its not a ""midround upgrade"" it's you decon the stasis bed and move it next to the surgery computer roundstart. That can be a roundstart upgrade, so why not just code it in as default and save the other sleeper

**Comment by Hopekz** [comment]
> Ok but, as it if this pr merges its not a ""midround upgrade"" it's you decon the stasis bed and move it next to the surgery computer roundstart. That can be a roundstart upgrade, so why not just code it in as default and save the other sleeper

Here you go I made this PR for you: #7826

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
Can you swap the stasis bed and the sleeper?

I'm thinking it has potential for people to move the stasis bed around, it'll look nicer with a gap on the bottom rather than the top. Also it's easier for people to get to if it's closer to the main doors.

**Comment by Hopekz** [comment]
Won't be around to fix this if something is broken after the merge.
Will reopen when I come back otherwise feel free to reopen if you want to merge.

**Comment by Hopekz** [comment]
I will be able to support it if merged so reopening.

**Comment by Hopekz** [comment]
New placement:
Personally like it less than the previous one but KTL is the mapping pope

image

**Comment by Hopekz** [comment]
I left for a week and this PR got fucked hard almost past recovery.
Recreated this in #7940

**Pull request closed without merging**
