### PR TITLE
Make tables and racks reduce spacewind

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
tweak: Tables reduce spacewind by 5x and racks by 10x
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
If you stand behind them? Next to them?

**Comment by monster860** [comment]
items and shizz on tables and racks have reduced spacewind.

**Comment by maxion12345** [comment]
magnetic. tables.

**Comment by Hopekz** [comment]
> magnetic. tables.

Yes

**Comment by MegaEmpirical** [comment]
Are tables and machines currently preventing rooms from being vacuumed? I had to deconstruct two tables to get the HoS office to vacuum.

**Comment by monster860** [comment]
no that is not the case.

**Pull request merged**
