### PR TITLE
[BOUNTY] Psychotic Brawl granter in uplink

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

As per https://forums.yogstation.net/threads/vote-require-new-features-added-via-bounties-to-have-accompaning-documentation-to-be-paid-out.19311/ I will add this to the wiki if it is merged

As detailed in https://forums.yogstation.net/threads/30-adds-a-granter-for-the-violent-psychosis-martial-art-as-a-chemist-traitor-item-ss13-server.26216/

# Changelog

:cl:  
rscadd: Added Psychotic Brawl Notes to the uplink for 8TC
tweak: Psychotic Brawl is no longer allowed to use stun weapons, including disabling guns
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
this was a BOUNTY??

**Comment by Moltijoe** [comment]
the bounty is still pending approval, $30 is WAY too much

**Comment by ghost** [comment]
12 tc is kinda too much for such random martial art

**Comment by Moggram** [comment]
> the bounty is still pending approval, $30 is WAY too much

He sad he was going to pay it himself on the forum. Don't need to get approval.

>How did you get to that price?
>>I will pay for it because I want it.

**Comment by milk-is-cool** [comment]
how do i uh pay for it

**Comment by ynot01** [comment]
> how do i uh pay for it

DM jamie or moja they'll have your answers

**Comment by Bibby0110** [comment]
> how do i uh pay for it

you paypal ynot

**Comment by milk-is-cool** [comment]
> > how do i uh pay for it
> 
> DM jamie or moja they'll have your answers

dm me your paypal and i can pay you that way if that works

**Comment by Moltijoe** [comment]
Balance council changes requested:
8TC and any weapon being used MUST be harmful

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
