### PR TITLE
Actually adds passive vent to RPD

### PR DESCRIPTION
**Pull request by ThatLing**
# Document the changes in your pull request
The code for passive vents has been in the game for 2 years and nobody bothered to add it to the RPD. Long-term, we should replace all space injectors with these on all maps.

# Changelog

:cl:  
rscadd: Passive vents can now be constructed using the RPD
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
They don't work

**Comment by MajManatee** [comment]
never even heard of a passive vent

**Comment by ThatLing** [comment]
> They don't work

Desc updated

**Comment by bruhlookatthisdood** [comment]
make dual vents creatable by rpd now

**Comment by Cartlord** [comment]
why are you adding them to the r.p.d. if you haven't actually fixed them

**Comment by ThatLing** [comment]
> why are you adding them to the r.p.d. if you haven't actually fixed them

Why not?

**Comment by ReddicusDragon** [comment]
Re-open this once we actually have auxmos so we don't get people complaining that 'muh passive vent doesn't work'

**Comment by ThatLing** [comment]
@ReddicusDragon Passive vents work now

**Review by ReddicusDragon — APPROVED** [review]

**Pull request merged**
