### PR TITLE
Adds new Holodeck Enviorment: Gym

### PR DESCRIPTION
**Pull request by alao3alao3**
Adds a new Gym to the holodeck environment.
apng
I pray to god I did the config right.

##### Why is this good for the game?
While inherently unnecessary, this boxing ring looks cooler and it is the only way certain stations (Yogstation, Yogsmeta, Eclipse, etc) will ever receive weight equipment and punching bags.

##### Changelog

:cl:  
rscadd: New Holodeck Enviorment: Gym
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Did you test it, pretty sure the lockers will be empty when you run the holodeck program

**Comment by UselessTheremin** [comment]
also the holodeck is right next to the gym, seems a bit counterintuitive to me to have a gym in a gym

**Comment by alao3alao3** [comment]
Don't remember weight machines in any gyms besides Delta

**Comment by patpol4** [comment]
Yeah this won't work, the lockers need to have their items put in manually, ill test if it even loads on monday

**Comment by alao3alao3** [comment]
image
fuck is every PR gonna have a merge conflict cause of those pipes

**Comment by patpol4** [comment]
> fuck is every PR gonna have a merge conflict cause of those pipes

sadly yes, copy your changes over onto a fresh cc file and it should work

**Comment by alao3alao3** [comment]
See #10640

**Pull request closed without merging**
