### PR TITLE
Adds Red-Eye & a gateway to traitor chemistry

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
No one thought to make telecrystals grindable apparently, so I made them grindable and this opens the gateway to tons of traitor exclusive stuff like traitor chemistry, traitor bartending and traitor cooking.

As an example of this gateway, I've added Red-Eye as a counterpart to the previous blue-eye pr. (obvious cowboy bebop reference)
Its raw TC cost is 1tc per 40u (willing to adjust, but its fast acting so not sure if its too much of an issue)
Will double action speed and reduce click delay by 20%
Causes minor brain damage.
Will reduce knockdowns by 15, stamina by 4,  unconcious by 5 and paralyzed by 20.
Will spit out narsian text at you randomly.

On overdose, you will randomly telecrystal teleport and drop items while your hands make occult gangsigns (as well as probably dying to toxloss and brain damage)

For future reference, any item made using redspace dust should be considered syndicate contraband just like any uplink item should be.

Another change is that I've changed the sound for telecrystal teleporting to be the same as bluespace crystals but reversed and pitchshifted slightly.

# Spriting
Adds two new sprites for the status effect
aa
redeye

# Wiki Documentation
Needs to have two chems added, redspace dust which can be obtained through grinding telecrystals, as well as red-eye, which is made the same as the previous blue-eye pr with diphenhydramine, iodine, hydrogen and sugar all at one and redspace dust at two.

# Changelog
:cl:  
rscadd: Added Redspace Dust chemistry & Red-Eye
soundadd: New telecrystal crush sound 
imageadd: Status effect images for red-eye
/:cl:

### CODE REVIEW

**Comment by Moja10** [comment]
Very cool idea! if the intent is for it to be obvious that someone smoked illegal syndicate dust, I would add an examine message so that its obvious when someone has big red bulging eyes

**Comment by azzzertyy** [comment]
> Very cool idea! if the intent is for it to be obvious that someone smoked illegal syndicate dust, I would add an examine message so that its obvious when someone has big red bulging eyes

should have it now but because its based on drugginess itl only appear sometimes on examine

**Comment by cuackles** [comment]
same as blue eyes show how it looks ingame pls

**Comment by azzzertyy** [comment]
> same as blue eyes show how it looks ingame pls

https://github.com/yogstation13/Yogstation/assets/42524344/00ddcdf9-e9b2-478e-aa86-96f38c86d4d9

**Review by ToasterBiome — APPROVED** [review]
i like this

**Pull request merged**
