### PR TITLE
removes kill objective from creep

### PR DESCRIPTION
**Pull request by SomeguyManperson**
it's time to force the playerbase to learn how to read

:cl:  
rscdel: creep final objective is only the protect/maroon
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
~~wtf is creep~~

its obsessed

**Comment by SomeguyManperson** [comment]
IT'S BOTH
image

**Comment by Tipy1802** [comment]
Do they still get to kill a co worker of their loved one?

**Comment by SomeguyManperson** [comment]
Yes

**Review by alexkar598 — COMMENTED** [review]
Please clarify if this is intended to leave no final objective to complete(since the maroon/protect is still on a prob 50)

**Comment by SomeguyManperson** [comment]
Protect/maroon was supposed to be 100% yeah

**Comment by alexkar598** [comment]
sure

**Review by alexkar598 — APPROVED** [review]

**Pull request merged**
