### PR TITLE
Replaces Ash Drake Music

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

old (Current) music:

https://user-images.githubusercontent.com/1534478/187696434-ae5a4cfa-21d6-4518-8e48-cace4f2e5184.mp4

New music by @Hey-Holokin

https://user-images.githubusercontent.com/1534478/187688062-62195c65-3b25-4032-bd86-012f220b59d2.mp4

# Changelog

:cl:  @Hey-Holokin
soundadd: Adds new music for Ash Drakes
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Can we get a sample of the current version of the ash drake music for comparation pretty please ?

**Comment by 00ze-cyclone** [comment]
SoulsOULSOULsoulSoUlsOul

**Comment by GraveHat** [comment]
> 

Die.

> SoulsOULSOULsoulSoUlsOul

**Comment by Hey-Holokin** [comment]
hope y'all are enjoying the new music i'm composing for the megafauna!

**Comment by KillerOrcaCora** [comment]
Love it* but the song resembles too closely to the one that will be used in https://github.com/yogstation13/Yogstation/pull/15476 and I don’t really think it grabs the dramtic fire breathing dragon atmosphere as well as the old one does.

**Comment by Hey-Holokin** [comment]
> Love it* but the song resembles too closely to the one that will be used in #15476 and I don’t really think it grabs the dramtic fire breathing dragon atmosphere as well as the old one does.

this is fair enough, I'll try to get started with another approach soon

**Pull request closed without merging**
