### PR TITLE
makes lizards scream when they drink planet cracker

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

makes lizards scream when they drink planet cracker on a 15% chance per mob life

### Why is this change good for the game?

hahaahhahhahhhahahahahahhahahahahhaahhahhahaahhahhahahahaahhahaahha

# Changelog

:cl:  
tweak: Lizards now scream when they drink Planet Cracker
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
i dont get it

**Comment by Marmio64** [comment]
> i dont get it

the drink is a symbol of human supremacy

**Comment by Tipy1802** [comment]
Based. It should probably be all non humans though

**Comment by Jarod1200** [comment]
it is also made with lizard wine to show human supremacy

**Comment by Cartlord** [comment]
Why not cry?

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
