### PR TITLE
adds a trident to the space carp uplink kit

### PR DESCRIPTION
**Pull request by boodaliboo**
the kit right now is god awful and gives you nothing to work with this gives them a decent melee weapon with a unique sprite from Missatessatessy
#### Changelog

:cl:  
rscadd: Added trident to white whale holy grail uplink kit
imageadd: added trident sprite
/:cl:

### CODE REVIEW

**Review by JamieD1 — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]
Well done for fixing it.

**Comment by alexkar598** [comment]
not true, I did my objectives using the kit the other day

**Comment by boodaliboo** [comment]
> not true, I did my objectives using the kit the other day

in comparison to every other kit its god awful

**Comment by ynot01** [comment]
hot

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
