### PR TITLE
Gives Ethereals face shape options and access to hair gradients

### PR DESCRIPTION
**Pull request by Chubbygummibear**
# Document the changes in your pull request
If you've played Starbound you're definitely gonna recognize these, but I think they're really cool and add more flavor option to our resident lightbulbs. In addition, I've enabled hair gradients which were unavailable because I found out you could just select Human as your race, set a gradient, and switch to Ethereal to have a custom gradient, and since I wasn't sure how to cleanse the gradient option on race swap, I'm just enabling it. I hope this will give a bit more flavor and draw to the Ethereals.

image
image
image
image
image
image
image
image
image

One issue that I am aware of is that since they aren't actually eyes, when you wear a mask that can partially reveal the face, nothing except for the Ethereal color is available, and I don't know how to fix that.

Also since the eyes aren't _actually_ eye sprites, they most likely won't glow to indicate cult or thrall, so if that is a big enough issue, I could just remove the eye option or make the default blank faced (but blank is kinda creepy and weird)

# Wiki Documentation

Make sure to note that Ethereals have acquired drip

# Changelog

:cl:  
rscadd: Ethereals can choose face shapes
rscadd: Ethereals can use hair gradients
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
the fucking absolute based pr

**Comment by LazennG** [comment]
YOOOOOO

**Comment by KillerOrcaCora** [comment]
"No. I Think We're Just Getting Started."

**Comment by ToasterBiome** [comment]
Halo N in  shambles

**Review by nesisknesis — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
