### PR TITLE
Adds Yogsdelta

### PR DESCRIPTION
**Pull request by Ktlwjec**
Yogsdelta - Delta piping is now layered. Fixed a few mapping issues with disposals not being connected and medbay having 2 rows of open desks (added a windoor with medical access to one of them) leading to medbay being completely accessible. Added shutters to surgery as the rest of the maps have them now, and also the bomb simulator to toxins. Also added mining medic, their locker and signal tech.

image

### CODE REVIEW

**Comment by thehighwayman** [comment]
after a month it's finally done!

**Comment by monster860** [comment]
after 9 years in development it hopefully will have been worth the weight.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
rebase to master and fix the piping, and various typepaths that've been changed

**Comment by ThatLing** [comment]
@nichlas0010 good to merge?

**Pull request merged**
