### PR TITLE
[ASTEROID] Atmos Approved: Atmospherics Changes + More

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Redoes some pipes in atmos as per an atmosian's input on what works better (IE: not dumping fresh air from a scrubber into the filtering loop half way through)

Also fixes the turbine SMES being inverted (draining power from the station)
Makes the turbine burn chamber 2x2 instead of 1x4
powers all the injectors in space that currently are actually useless
adds more radsuit closets and moves them somewhere better
adds more portable scrubbers (Asteroid is big, y'know?)
color-codes the gas miner output pipes so atmos techs stop getting confused
adds a PILE of Xeno spawners around atmos and one in maint south of viro (Adds some vents there because its too big to ever repressurize without it)
relocates the fire-axe so it is a little harder to reach with greytiding and isn't visible from the hallway
added some vents and scrubbers to the SMES room, engineering secpost, and atmos storage
moved a camera in cargo so the AI can see the ORM
added a third scrubber to the central-central hallway
makes the mining airlock a proper airlock so miners dont space themselves

probably missed some stuff, check mapdiffs as always

# Changelog

:cl:  
mapping: Xeno spawns are a lot more varied
mapping: Viro-maint now has vents so it can repressurize ever
mapping: Atmosian-approved atmos changes & fixes
mapping: other misc. fixes were done to the map
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
There's a pipe going through rock by turbine
The 2-deep walls near turbine probably aren't needed
I'm not seeing where the pipe dispenser and disposals pipe dispenser were moved to after they were replaced with portable scrubbers

**Comment by VaelophisNyx** [comment]
they were deleted
because they're old :P 
RPDs entirely replace their functionality

I figured pipe-through-rock was fine but I can tweak that

double-thicc walls was to prevent it looking weird and off-center

**Comment by VaelophisNyx** [comment]
tweaks made as per above :P

**Comment by VaelophisNyx** [comment]
@ToasterBiome thoughts?

**Comment by ToasterBiome** [comment]
> @ToasterBiome thoughts?

Readd pipe machines

**Comment by VaelophisNyx** [comment]
they suck tho

also they're gone on box

**Comment by ToasterBiome** [comment]
> they suck tho
> 
> also they're gone on box

pretty sure they’re in the front room on box

**Comment by VaelophisNyx** [comment]
> > they suck tho
> > also they're gone on box
> 
> pretty sure they’re in the front room on box

my brother in christ I'm the one who removed them

**Comment by VaelophisNyx** [comment]
ss (2022-10-10 at 02 29 08)
Box reference

**Comment by VaelophisNyx** [comment]
also I put them back

**Comment by ToasterBiome** [comment]
> > > they suck tho
> > > also they're gone on box
> > 
> > 
> > pretty sure they’re in the front room on box
> 
> my brother in christ I'm the one who removed them

readd them to box

**Review by ToasterBiome — APPROVED** [review]

**Comment by MenacingManatee** [comment]
Whats the purpose of the manifold pipes leading from the gas miners?
Why the gray pipe connecting from plasma, n2o, and co2 to the yellow mix pipe?
Why the 2 extra manifolds in the atmos room by the mixing chamber?

Everything else looks good to me though, appreciate ya working on my map! :D

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
manifolds there are "optimal" but we don't start optimal, you can push the pumps back to give someone space to do so (like on box)

**Comment by VaelophisNyx** [comment]
> Whats the purpose of the manifold pipes leading from the gas miners?

done at the request of an atmos-player, to save time. they specifically want them *before* the pump, because you dont want to accidentally send gas down the pipe if you just wanted to fill a canister

>Why the gray pipe connecting from plasma, n2o, and co2 to the yellow mix pipe?

just trying to keep it distinct, since all the rest were color coded; at the time I did that the plasma pipe was still also yellow

>Why the 2 extra manifolds in the atmos room by the mixing chamber?

those push the distro and scrubber pipes back to layer 2, for the hidden pipes that service atmos south of there; there wasn't a need for them to be visible nor on layer 3. Also done at the request of an atmos player, to cut down on visual noise and time-wasting pipe removal to fix it

**Comment by VaelophisNyx** [comment]
> manifolds there are "optimal" but we don't start optimal, you can push the pumps back to give someone space to do so (like on box)

layer manifolds removed (though I dont see the harm in leaving them, it just saves time and stops accidental plasma flooding)

**Comment by MenacingManatee** [comment]
> > Why the gray pipe connecting from plasma, n2o, and co2 to the yellow mix pipe?
> 
> just trying to keep it distinct, since all the rest were color coded; at the time I did that the plasma pipe was still also yellow

image

It just looks weird to me since no other pipe connection uses that gray pipe in atmos except the air mixer

**Comment by VaelophisNyx** [comment]
that's fair, I might look into making it yellow again

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
image

these look fucked up also no vents in maint

**Comment by ToasterBiome** [comment]
and the atmos storage room has an alien spawn but no vents, please add vents in that room (might be covered by stuff)

**Comment by VaelophisNyx** [comment]
these vents are because, if that particular maint area EVER gets vented, it takes a solid SIX cans of air to re-pressurize it, or effectively like 4 IRL hours of opening a door to let air in

also better for that Xeno spawn so it can get outta maint easier

**Comment by VaelophisNyx** [comment]
> and the atmos storage room has an alien spawn but no vents, please add vents in that room (might be covered by stuff)

they are in there, just covered yea

**Comment by ToasterBiome** [comment]
> these vents are because, if that particular maint area EVER gets vented, it takes a solid SIX cans of air to re-pressurize it, or effectively like 4 IRL hours of opening a door to let air in
> 
> also better for that Xeno spawn so it can get outta maint easier

Overdue for more firelocks instead then 👁️

**Comment by VaelophisNyx** [comment]
> > these vents are because, if that particular maint area EVER gets vented, it takes a solid SIX cans of air to re-pressurize it, or effectively like 4 IRL hours of opening a door to let air in
> > also better for that Xeno spawn so it can get outta maint easier
> 
> Overdue for more firelocks instead then 👁️

Are we even allowed to put many firelocks in maint?

**Comment by ToasterBiome** [comment]
> > > these vents are because, if that particular maint area EVER gets vented, it takes a solid SIX cans of air to re-pressurize it, or effectively like 4 IRL hours of opening a door to let air in
> > > also better for that Xeno spawn so it can get outta maint easier
> > 
> > 
> > Overdue for more firelocks instead then 👁️
> 
> Are we even allowed to put many firelocks in maint?

image
image
image
image

**Comment by VaelophisNyx** [comment]
Vents removed, firelocks added

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
