### PR TITLE
Allow moaning in soft crit

### PR DESCRIPTION
**Pull request by monster860**
### Intent of your Pull Request

Explain what the purpose of your PR is.
Mention if you tested your changes. If you changed a map, make sure you used the mapmerge tool.

Mention if your PR is related to an issue.
You can type "Fixes issue #6" and issue 6 will be automatically closed when your pull request is merged. This is much easier for everyone.

Edit the changelog at the bottom for changes that are noticeable by the players. Remove it if this isn't the case.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.
Include [admin] in the title if it's something admin related.
Include [s] in the title if you don't want it to be announced on discord and the server.

#### Changelog

:cl: monster860
tweak: You can now moan in soft crit
/:cl:

### CODE REVIEW

**Comment by Altoids1** [comment]
VERY IMPORTANT VERY VERY IMPORTANT

**Comment by ghost** [comment]
Monster this PR is extremely concerning???

**Comment by monster860** [comment]
It's not i ded because it didn't cause me to die.

**Comment by deathslayer2481** [comment]
I second Adam. Monster I know you’re admin now but what dafuq

**Comment by LoliconSlayer** [comment]
What the hell

**Comment by overlord12345** [comment]
Why

**Comment by Altoids1** [comment]
image
I'm confused

**Comment by Featherfield** [comment]
ok shytter

**Comment by alexkar598** [comment]
cynder has corrupted monster

**Comment by SomeguyManperson** [comment]
no

**Pull request closed without merging**
