### PR TITLE
Adds a rare zombie spawn midround event also tweaks blob zombie infection

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑
rscadd: There is now a rare chance a zombie may spawn during the middle of the round!
tweak: Blob zombies from the wizard event are now regular zombies that may infect you!
/🆑

Also ports: https://github.com/tgstation/tgstation/pull/44999

### CODE REVIEW

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
https://github.com/yogstation13/Yogstation-TG/blob/master/code/modules/events/wizard/blobies.dm 

change this to use zombies instead of blobspores instead.

**Comment by fluffe9911** [comment]
ok

**Comment by Ktlwjec** [comment]
my downvote is for the event not for the other things to clarify

**Comment by HomocidlePancakes** [comment]
I feel like the wiz event will derail the gamemode a tad bit too much. There will be ALOT of corpses during wiz. Also wiz may abuse this to become a z.

**Comment by Amelia0010** [comment]
Oh no, the wizard who can turn into an ED-209, the wizard who can become a lich, the wizard who can literally become an unstoppable rod, the wizard who can change species to shadowling, will become a zombie.

How horrible.

**Comment by HomocidlePancakes** [comment]
@nichlas0010 
There is a reason why zombies are blacklisted from magic mirror
https://github.com/tgstation/tgstation/pull/41505

**Comment by HomocidlePancakes** [comment]
Actually fuck, the hands bug was fixed a long time ago. I sperged out

**Comment by Amelia0010** [comment]
well, remove that part from the sentence, point still stands. Of all the things to worry about from wizards, I don't think that choosing random magical events so you can die to a zombie is amongst the top 100

**Comment by HomocidlePancakes** [comment]
It is pretty high, but you can’t get a holopara after zombification because HANDS, which is something I forgot.

**Comment by Nickvr628** [comment]
nah dont like it

**Comment by fluffe9911** [comment]
you dont play though

**Comment by Nickvr628** [comment]
you dont know that

**Pull request merged**
