### PR TITLE
adds magnifying glass

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Adds the magnifying glass, along with a syndicate and clockwork counterpart

Replaces the roundstart forensic scanner with the magnifying glass

Adds syndicate version to uplink for 2TC

Clockwork version unused

Forensic scanner still researchable and printable and orderable from cargo (and certain maint ruins)

Can examine to see stats

Differences: 

- Magnifying glass takes slightly longer (6 seconds) and displays all results at once.

- Magnifying glass can apply half a fire stack to living mobs on its 6 second cooldown or ignite items such as paper at range if you are 2 tiles or closer to space (and vision is not obstructed)

For comparison, stop-drop-rolling removes 5 fire stacks

## Syndicate Magnifying Glass

Examines things twice as fast (3 seconds) with a halved cooldown on igniting things

Applies 2 fire stacks instead of 0.5

Syndicate Magnifying glass serves as a utility for traitors who want to be extra careful about covering their tracks while also being a situational stealthy weapon. If someone sees you holding it, though, you will get found out.

## Clockwork Magnifying Glass

Applies 5 fire stacks

5 second cooldown

Cannot be used by non-clockies

Cannot be used to ignite other clockies

Unimplemented

# Spriting
By Baiomu

# Wiki Documentation

Ignition is instant

Magnifying Glass:
0.5 fire stacks
6 seconds

Syndicate Magnifying Glass:
2 fire stacks
3 seconds

Clockwork Magnifying Glass:
clock use only
5 fire stacks
5 seconds

# Changelog

:cl:  ynot01, baiomu
rscadd: Added the magnifying glass to the detective's locker and loadout
rscadd: Added the suspicious magnifying glass to the uplink for 2TC
rscdel: Removed the forensic scanner from the detective's locker and loadout
/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
Its a cool item to add, but not round start for a detective. I don't see a range stat anywhere so I can't scan lockers. There is also no way to make printouts so you can't prove anything to the captain/HOS or in court. (I know trials are rare, but its like your job to have all the findings if one goes down.)

The chaplain or curator could get this as RP fluff or add some code to help them hunt down monsters. (Like cultists, vampires and xenos.)

**Comment by ynot01** [comment]
> I don't see a range stat anywhere so I can't scan lockers.

Range is unlimited

**Comment by Moggram** [comment]
> > I don't see a range stat anywhere so I can't scan lockers.
> 
> Range is unlimited

Cool that was a big deal for me. I still don't like not having the printouts, but can live whit it.
Umm... May want to check if you scan stuff when using a secretary camera. (Can't remember if that got fixed or not as I don't play R&D.)

**Comment by ynot01** [comment]
Added range limit of 9 tiles (This already existed on ignition but now exists for both purposes)

**Comment by cuackles** [comment]
are they gonna have an inhand sprite ?

**Comment by ynot01** [comment]
> are they gonna have an inhand sprite ?

No, purposefully, to maintain stealthy

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
It needs a mob sprite for hand holding, this goes for all of them.

**Comment by Bibby0110** [comment]
Stale, apologies. Reopen when spritere'd

**Pull request closed without merging**
