### PR TITLE
Better species environment handlers, and custom race body temperature

### PR DESCRIPTION
**Pull request by Hopekz**
ports tgstation/tgstation#48569

**EDIT: this has been successfully test merged on TG now without any complaints.**

**EDIT 2: It is now merged in TG. wow our maintainers sure are slow see you in another few weeks with an update 3**

**EDIT 3: see comments. Closing this PR**

**PR milestones:**
- [x]  1 week without maintainer activity
- [x]  2 weeks without maintainer activity
- [x]  3 weeks without maintainer activity
- [x] 4 weeks without maintainer activity
- [ ] 5 weeks without maintainer activity

This has been an exciting project so far with lots of twists and turns hopefully we hit our 5-week milestone

**Original PR description:**
"
This now fixes hard suit fire suits and overheating issues.

This refactors the handle_environment for most mobs and species.
Better documentation in the code
Better consistency across mobs.
Basic mobs can now have cold and heat protection from the environmental. (not simple mobs)
Slime's temperature change code has been cleaned up.
Base human default temperature range is a bit more reasonable, (+30, -40 vs +/- 50) you would cook or freeze without taking damage before. (Thoughts)
Split up species handle_environment, it was a single massive proc, now each species has handle_environment, handle_body_temperature, handle_environment_pressure.
Each species can now have their own body temp, and hot/cold damage ranges.
Removed checks that we have an environment in many of the classes, this is handled at the base mob class.

**SPECIES:**
All the species modified will survive the normal range of temperature range on station.

**Ethereals** core body temp is hotter and can stand higher body heat, but they take damage in cold areas faster.
**Lizard people** are cold blooded and do not stabilize body temperature normally, because of they do not take damage as fast as a human. They still stabilize to the room temp.
**Edit:Lizards now self stabalize unless really hot or cold**

**Plasmamen** like it cold and can survive colder temps better, but take damage when it is hot faster and they can stabilize body temp slower at times.
**Zombies** do not stabilize body heat naturally, they are dead. Heat damage is equal to fire spread temp, and cold temp is equal to min temp to move. They still stabilize to the room temp, like lizards
Why It's Good For The Game
Code cleanup
Each race now can be special and handle the environment differently.
Human body temp is not normal for everyone now.
You could find a zombie by scanning its body temp.
"

#### Changelog

:cl:  Hopek
add: Species body temperature handling
balance: Plasmamen, Lizardpeople, Ethereal have custom body temperatures to deal with
fix: natural body temp stabilization now returns proper values
refactor: clean up of the environment handles for mobs and species
/:cl:

### CODE REVIEW

**Comment by Alexandria404** [comment]
very nice

**Comment by SomeguyManperson** [comment]
we should wait for TG to balance this from live testing since there's a few problems with lizards taking way longer to recover from low temperatures making stuff like watcher bolts and cryo almost as damaging as it is to slimepeople

**Comment by Mqiib** [comment]
I feel like plasmamen should really only care when it's really hot, but be entirely immune to any effects of being cold being that they're made of spicy purple gas and not biological stuff. Making them take damage from temperature really kind of fucks over an already pretty vulnerable race by taking away one of their only good qualities.

**Comment by Hopekz** [comment]
Closing PR because of 3 reasons::
**Reason 1:**
a5b6a4c8-ba40-46c9-aae4-e75c551ec3c4

**Reason 2:** 
The milestone can't even go up anymore ever since a maintainer left a comment.
The joke is over.

**Reason 3:**
Unhappy with how me taking the time out of my day to port something for our codebase isn't taken seriously. 
Pretty sure with the amount of testing that I did for this PR with different scenario's (which also ended up me porting #48889 along with it because of my lizard tests) I have about 3 Hours sunk into this.

You can re-open this if you want I'm done caring about it because of this situation so even if an edit gets proposed not sure if I'd be able to find the time to implement it since I started working on other projects such as the Detective borg under #7529

**Comment by alexkar598** [comment]
Yeah well I got bored and lazy

**Pull request closed without merging**
