### PR TITLE
adam makes another one-file change in the web editor: buffing cryogenic blob edition

### PR DESCRIPTION
**Pull request by ghost**
this blob chem is so shit it could double as a yog admin

now the poison it injects isn't the weakest poison this side of weedkiller anymore and it injects more of it, compensating for the fact that it only does ten fucking damage. also it does burn and not brute damage now because brrr cold
#### Changelog

:cl:  
tweak: Cryogenic poison is now less fucking worthless as a blob chem
/:cl:

### CODE REVIEW

**Comment by DiamondSentinel** [comment]
If you're just going to spew insults every time you interact with the server, why do you bother posting things on the git?

Aside from your addiction to pissing people off, change looks good. Cryo needs a bit of a buff, although this might prove a bit much.

**Comment by ghost** [comment]
@DiamondSentinel 
Am I fucking wrong though?

**Comment by DiamondSentinel** [comment]
Regardless of whether or not you think that about the admins, there's no reason to spout it here.

**Comment by boodaliboo** [comment]
> Regardless of whether or not you think that about the admins, there's no reason to spout it here.

does it matter?

**Comment by MonsWTF** [comment]
> > Regardless of whether or not you think that about the admins, there's no reason to spout it here.
> 
> does it matter?

Yes? You support it once, you are leaving a grey area that then encourages people to keep doing it and to keep toeing the line, which will just make it go further and further. You do not have to be negative, or type like an asshat, to make a PR.

**Comment by ghost** [comment]
@MonsWTF

Why do I care?

**Comment by Moja10** [comment]
You should care because you are already on thin ice as it is making PRs despite being permabanned from the server with basically no chance of getting unbanned.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
