### PR TITLE
removes growth serum from eggs.

### PR DESCRIPTION
**Pull request by stwordcitizen**
# Document the changes in your pull request
Removes growth serum from eggs since you guys can't control yourselves and keep rping as children.
# Wiki Documentation
remove growth serum from eggs.
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:   
rscdel: removes growth serum from eggs.  
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
how am i going to make growth serum bees now

**Comment by NCRLouTenant** [comment]
Nanotrasen finally not using biologically engineered chickens.

Now we just have to figure out where they're hiding the chickens at.

**Comment by stwordcitizen** [comment]
> how am i going to make growth serum bees now

fly amantias have growth serum in them

**Comment by ToasterBiome** [comment]
Underlying issue fixed in https://github.com/yogstation13/Yogstation/pull/13929

**Pull request closed without merging**
