### PR TITLE
Removes ERP Ion Law Potential

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

As title says

This is purely a "better safe than sorry" PR

# Changelog

:cl:  
tweak: Scrubs a couple bad AI Ion Law things
/:cl:

### CODE REVIEW

**Comment by Yarinoi** [comment]
i mean, if someone uses the laws to erp, thats on them, not the laws

**Comment by AdamPrime314** [comment]
Those Ion laws provided no RP and in the instances the AI did manage to see and act on them, they always acted creepy. I am guessing because most people who play don't understand the difference between jokingly flirting and sexual harassment.

> i mean, if someone uses the laws to erp, thats on them, not the laws

**WARNING:** This user is biased. They are confirmed to engage in long-term, "cutesy" relationship roleplay with [another player](https://forums.yogstation.net/members/slicerv.6266/) and taking a **SERIOUS BUSINESS** [in-game wedding](https://www.reddit.com/r/SS13/comments/18gisf3/admemes_helped_throw_a_lizardpersons_wedding/). Make sure to avoid their commentary on less-conventional roleplay as they are not afraid to type certain things in the chatbox.

**Comment by Yarinoi** [comment]
> Make sure to avoid their commentary on less-conventional roleplay as they are not afraid to type certain things in the chatbox.

what the fuck
what are you trying to imply here

**Comment by AdamPrime314** [comment]
> > Make sure to avoid their commentary on less-conventional roleplay as they are not afraid to type certain things in the chatbox.
> 
> what the fuck what are you trying to imply here

I worded that wrong. I meant you confidently write content skirting around the line of acceptable roleplay that will create uncomfortable situations for other players, regardless if you try to hide it behind PDA messages (Able to be read by ghosts, AI, comms agent) or specifically changing the language to Draconic (Able to be read by ghosts, other reptile characters, people with a bilingual quirk). While certainly it is allowed within the rules, and [certain instances of **VERY** active skirting](https://www.youtube.com/@Crawlc/videos) [take an oddly long about of time to act on](https://forums.yogstation.net/threads/crawl-report-by-nazitra.27639/), it is too close for comfort for ERP activity. Slippery slope can be argued against this line of logic, but please keep in mind that others who [behaved](https://forums.yogstation.net/members/wolf751.7480/) [the](https://forums.yogstation.net/members/serverroomaccountant.7400/) [same](https://forums.yogstation.net/members/lemon-nades.7122/) now take a rather active part in **Bubberstation**.

**Comment by Yarinoi** [comment]
i would say comparing silly romance rp that someone might see as cringe to the shit rita did in that player complaint is an unfair comparison, but i dont feel like arguing this nor flooding the comments with unnecessary shit so i'm choosing not to discuss this anymore

**Comment by azzzertyy** [comment]
ignore downvotes these laws suck anyway and arent fun

**Comment by azzzertyy** [comment]
> > > Make sure to avoid their commentary on less-conventional roleplay as they are not afraid to type certain things in the chatbox.
> > 
> > 
> > what the fuck what are you trying to imply here
> 
> I worded that wrong. I meant you confidently write content skirting around the line of acceptable roleplay that will create uncomfortable situations for other players, regardless if you try to hide it behind PDA messages (Able to be read by ghosts, AI, comms agent) or specifically changing the language to Draconic (Able to be read by ghosts, other reptile characters, people with a bilingual quirk). While certainly it is allowed within the rules, and [certain instances of **VERY** active skirting](https://www.youtube.com/@Crawlc/videos) [take an oddly long about of time to act on](https://forums.yogstation.net/threads/crawl-report-by-nazitra.27639/), it is too close for comfort for ERP activity. Slippery slope can be argued against this line of logic, but please keep in mind that others who [behaved](https://forums.yogstation.net/members/wolf751.7480/) [the](https://forums.yogstation.net/members/serverroomaccountant.7400/) [same](https://forums.yogstation.net/members/lemon-nades.7122/) now take a rather active part in **Bubberstation**.

Is this a fucking Adam El Tablaway alt? Literal skitzo?

1. Weddings and in-game relationships are perfectly fine and have a clear line. In zero cases was this crossed.
2. Serverroomaccountant was banned for an issue irelated to any form of erp, and has stayed banned mainly for their own mental health.
3. I have zero idea of how lemonades is relevant
4. Crawl is a different person. So are most of the people mentioned here.

**Comment by AdamPrime314** [comment]
> Weddings and in-game relationships are perfectly fine and have a clear line. In zero cases was this crossed.

Difference of perspectives, hard to argue for or against it. My only argument against this sort of behavior is a slippery slope belief that this is shared among people who will later engage in ERP, as it's easier to go from "KISSU KISSU I LOVE YOU" straight to ERP than "how do i get insuls" straight to ERP.

> Serverroomaccountant was banned for an issue irelated to any form of erp 

While they were not banned for any sort of ERP activity on the server, I did state they became active on **Bubberstation**. Their character is a furry fox named **David Frontier** and wears a collar with "puppy" written on it while performing petplay roleplay. Someone else confirmed to have an ["IC relationship"](https://discord.com/channels/134720091576205312/134720091576205312/1141283645991166012) with them on here so it is a good example of the handholding RP to ERP pipeline.

> I have zero idea of how lemonades is relevant

**Nomel Sedan** is the name of their [shark](https://www.furaffinity.net/view/54980207/) [fursona](https://steamcommunity.com/profiles/76561198042102000), which they created a character for on **Bubberstation** who does foot fetish ERP with their partner **Derkala**. 

> Crawl is a different person. So are most of the people mentioned here.

Of course everyone is a different person, but certain behaviors are shared largely enough to raise a few concerns whether or not their opinion isn't biased towards a more open approach to ERP activities. After all, full acceptance is a double-edged sword that the furry and scalie communities know far too well. Gatekeeping certain topics should be done as precaution since the consequences are far too big to ignore.

**Comment by N3D6** [comment]
yeah these laws are wack af anyone downvoting this is an idiot

**Comment by Yarinoi** [comment]
i can see 'seduce' being removed at best, 'flirt' seems pretty innocent

**Comment by Aquizit** [comment]
> i can see 'seduce' being removed at best, 'flirt' seems pretty innocent

Maybe. Like I say in the main post I'm mostly just being as safe as possible using guidelines I've been told as staff. I would be open to leaving that in if a code maint/HD wants.

Seduce should still go though.

**Review by Bibby0110 — DISMISSED** [review]
nvm

**Comment by azzzertyy** [comment]
> > Weddings and in-game relationships are perfectly fine and have a clear line. In zero cases was this crossed.
> 
> Difference of perspectives, hard to argue for or against it. My only argument against this sort of behavior is a slippery slope belief that this is shared among people who will later engage in ERP, as it's easier to go from "KISSU KISSU I LOVE YOU" straight to ERP than "how do i get insuls" straight to ERP. yadayada etc etc

dont you literally play on bubber, adam?

**Comment by AdamPrime314** [comment]
> dont you literally play on bubber, adam?

You are ignoring my examples of players who heavily endorsed this community's acceptance towards IC "relationships" in order to focus on attacking a boogeyman. I understand that you may think whoever Adam El-Tablawy is might try to infiltrate your server with Operation Mockingbird tactics, but you should be sure to provide more arguments or instances of similar speech patterns between me and them before jumping onto that conclusion.

**Comment by Yarinoi** [comment]
im guessing this pr happened because someone used the laws to be weird, judging from an earlier comment?
that kind of proves my point, noone had a problem with the laws until someone used them as an excuse to be weird
seduce should definitely go though
image

**Comment by azzzertyy** [comment]
> im guessing this pr happened because someone used the laws to be weird, judging from an earlier comment? that kind of proves my point, noone had a problem with the laws until someone used them as an excuse to be weird seduce should definitely go though image

sorry but its outright not true, theres been a branch for about 2 years now that removes these two ion laws, it just never had a pr made of it.

**Comment by Yarinoi** [comment]
> but its outright not true, theres been a branch for about 2 years now that removes these two ion laws, it just never had a pr made of it.

huh, the more you know i guess

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
