### PR TITLE
Adds real-time TTS with Piper

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

At present, there are 12 voices:
- 5 female British
- 1 male British
- 3 female American
- 3 male American

There are several filters that get applied in different ways. Robots and machines will have a silicon filter applied. Lizards, aliens, and ethereals have filters attached to their tongues. Gas masks and sechailers have their own filters as well. Radio will sound more radioy than talking to someone in person.

Once I figure out model training (after this is merged preferably) we can start adding user-provided voices and maybe species-specific voices.

Backend info at https://github.com/yogstation13/yogs-tts

- [x] Do the tgui for the hear-tts pref and voice choice pref
- [x] Move the 750+ binary files to a containerized backend with build process instead of this repo
- [x] Testmerge
- [ ] Solve lag if there is any
- [x] Add pitch preference

# Why is this good for the game?
Muh immersion

# Testing
https://github.com/yogstation13/Yogstation/assets/28408322/f5f0c309-32b7-4ecc-ae7b-18f7a58b6989

https://github.com/yogstation13/Yogstation/assets/28408322/14dcc4b7-c427-4b02-aeae-ed170ef84b3e

# Changelog

:cl:  
rscadd: Added TTS
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
Remove british voice

**Comment by Yarinoi** [comment]
please have this be an option you can disable i dont want this

**Comment by azzzertyy** [comment]
> please have this be an option you can disable i dont want this

image

**Comment by Yarinoi** [comment]
> > please have this be an option you can disable i dont want this
> 
> image

thank god

**Comment by Scrambledeggs00** [comment]
Aeiou
John Madden

**Comment by ShoziOffical** [comment]
fucking goated

**Comment by 00ze-cyclone** [comment]
TTS sound flat and emotionless which is bad for immersion.
When you see the text you can imagine the voice in your head and the intonation, with TTS you now have that noise that get linked to what you read that’s completely dissonant.
Also the issue that typos make things sounds weird, with just texts your brain can just correct the typos and you don’t notice it, with sounds even if your brain correct the meaning you still heard something nonsensical and out of place.

**Comment by neeshacark** [comment]
> TTS sound flat and emotionless which is bad for immersion. When you see the text you can imagine the voice in your head and the intonation, with TTS you now have that noise that get linked to what you read that’s completely dissonant. Also the issue that typos make things sounds weird, with just texts your brain can just correct the typos and you don’t notice it, with sounds even if your brain correct the meaning you still heard something nonsensical and out of place.

just turn it off if it bothers y ou

**Comment by azzzertyy** [comment]
> just turn it off if it bothers y ou

sorry yogstation players don't understand stand the concept of "optional"

**Comment by RG4ORDR** [comment]
WHOO TOOK DAE DAM ARDSOOTS

**Comment by 00ze-cyclone** [comment]
> > TTS sound flat and emotionless which is bad for immersion. When you see the text you can imagine the voice in your head and the intonation, with TTS you now have that noise that get linked to what you read that’s completely dissonant. Also the issue that typos make things sounds weird, with just texts your brain can just correct the typos and you don’t notice it, with sounds even if your brain correct the meaning you still heard something nonsensical and out of place.
> 
> just turn it off if it bothers y ou

Just because it’s optional doesn’t mean it’s completely free of criticism, mood is optional and I can still say it fucking suck.

**Comment by MajManatee** [comment]
Too many British. Also yeah, it sounds unnatural. Cant wait to turn it off.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Need a config option and handling to automatically disable it over a certain population. Preferably a min/max like we have the 1.1 tick highpop so if we're sitting at the number it doesn't keep flipping on and off.

**Comment by PibeCantina** [comment]
Add literally best pr tag please

**Pull request closed without merging**
