### PR TITLE
Removes Lavaland prisoners

### PR DESCRIPTION
**Pull request by MrHorizons**
Eight spawners (the absolute most of any ghost spawner), three (loaded!) guns and a box of ammo, murderbone bait, and just being plain outdated.

I tried to improve it, but since apparently they were just "sidegrades", I'm just removing it. I'll probably make something to fill the niche of "group-based, less murdery survival" (an alternative to ashwalkers) later.

#### Changelog

:cl:  
rscdel: Removed the Lavaland prisoner ship.
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
I have seen some great rp with this recently and they are little threat to nonantags generally. So eh

**Comment by Xoxeyos** [comment]
Remove the guns and ammo, and it should be fine.

**Review by patpol4 — CHANGES_REQUESTED** [review]
I agree with this but it's up to headcoders. Also i think you should just blacklist it.

**Comment by Marmio64** [comment]
ashwalkers are just a better version of prisoners.

The niche of non-murder group based survival is already filled up by freegolems, orion med base, and the lavaland veterinarians.

**Comment by neeshacark** [comment]
they literally arent supposed to kill anybody unless they get that murderer background, and even that you aint meant to.

just remove the murderer background if it even exists, ive never seen it

**Comment by boodaliboo** [comment]
remove murderer background and even then blacklist it dont outright remove it its a one line change

**Comment by ghost** [comment]
Totally behind this removal. NTPs are a great example of a ghost role that is not meant for Yog's unique role play environment. There are some pretty glaring issues about them which are only made worse by the lack of an actual objective, leading to murderboning or self antagging that takes away from others' enjoyment.

**Comment by JamieD1** [comment]
@MrHorizons Blacklist it instead.

**Comment by UselessTheremin** [comment]
ah, prisoners... ash walkers but with no interesting tools, only guns, and no incentive to stay on lavaland, and all the incentive to go to the station, and kill or steal everything they can get their grubby paws on. please, prisoners are a plague on this server.

**Pull request closed without merging**
