### PR TITLE
adds atmos to engine pipes to omegastation

### PR DESCRIPTION
**Pull request by athena413**
see title, its messy but better than nothing

#### Changelog

:cl:  
rscadd: Added atmos to engine pipes to omegastation
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
cool changelog btw

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Fix your changelog

**Comment by athena413** [comment]
> Fix your changelog

done

**Review by Ktlwjec1 — APPROVED** [review]
honk she says then notices merge conflicts

**Comment by JamieD1** [comment]
@FLME Conflicts then it will be merged after recheck by KTL

**Comment by athena413** [comment]
i dont know what the problem is aaaaaaaaaaa

**Pull request closed without merging**
