### PR TITLE
Adds new pets to yogstation! Merge Conflict Free Edition!

### PR DESCRIPTION
**Pull request by fluffe9911**
Decided to add some new pets to yogstation to spice up the pet variety! Pets I added were

Anadear a penguin with a sombrero was used in a moral test by the rd before becoming the science departments mascot found next to the E.X.P.E.R.I.M.E.N.T.O.R

Warden Jacob a pug tasked with guarding the armory better then your average warden found in wardens office

Officer Kreb a pet real crab here to lay down the hard claws of the law found in hos office

And Honk Bot clowns "pet" robot found in theater yogstation classic

First time mapping so may of screwed this up may add some pictures later if you guys really want some hope this is good!

### CODE REVIEW

**Comment by Moja10** [comment]
Bit too much IMO, names and reasons for the pets existing don't make much sense...

**Comment by fluffe9911** [comment]
Oh come on its just some flavor text plus some of its funny to me atleast

**Review by ThatLing — CHANGES_REQUESTED** [review]
hello please remove sloth and renault

**Comment by fluffe9911** [comment]
Oh uh alrighty

**Comment by fluffe9911** [comment]
Alright done

**Pull request merged**
