### PR TITLE
Sort gas reactions by priority properly

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

guessing that priority doesn't work since they sort into sublists but they're actually only sorted inside the sublists which doesn't make sense when you start pulling them out of these sublists, you would need to sort them again.

# Spriting

# Wiki Documentation

# Changelog

:cl:  
bugfix: Sort gas reactions by priority properly
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
just checked upstream and found this (which confirms my fix is correct)
https://github.com/tgstation/tgstation/pull/48871
amazing how it takes me 10 seconds to fix this when I'm aware of it, maybe file a bug report next time @SapphicOverload?

**Comment by Rdrazga** [comment]
Test this and make sure hyper noblium doesn't just break the entire gas reaction loop after running 1 time since that is the other possible issue rather then this just being an error with sorting.

**Comment by Simplehorror** [comment]
> Test this and make sure hyper noblium doesn't just break the entire gas reaction loop after running 1 time since that is the other possible issue rather then this just being an error with sorting.

it's not that

**Comment by ShoziOffical** [comment]
I will test this for him

**Comment by ShoziOffical** [comment]
> just checked upstream and found this (which confirms my fix is correct) [tgstation/tgstation#48871](https://github.com/tgstation/tgstation/pull/48871) amazing how it takes me 10 seconds to fix this when I'm aware of it, maybe file a bug report next time @SapphicOverload?

didnt know there was a priority fix on tg damn

**Comment by Rdrazga** [comment]
Also just a code side of things was this not possible using the previous proc instead of creating an entirely new proc?

**Comment by ShoziOffical** [comment]
@Simplehorror [09:17:02] Runtime in reactions.dm,62: Cannot read null.priority

**Comment by warface1234455** [comment]
runtime

**Comment by Rdrazga** [comment]
> @Simplehorror REASON #8: [09:17:02] Runtime in reactions.dm,62: Cannot read null.priority

It ran into an error with his new proc which is why the old proc was coded the way it was.

**Comment by ShoziOffical** [comment]
> > @Simplehorror REASON #8: [09:17:02] Runtime in reactions.dm,62: Cannot read null.priority
> 
> It ran into an error with his new proc which is why the old proc was coded the way it was.

yeah

**Comment by ShoziOffical** [comment]
the tg fix deleted the old proc

**Comment by Rdrazga** [comment]
> yeah

In theory though if that is the ONLY issue causing noblium to not work you can just use the old proc to create the list in the new location, problem is this means you are now running far more procs per gas reaction going on.

**Comment by Simplehorror** [comment]
> > @Simplehorror REASON #8: [09:17:02] Runtime in reactions.dm,62: Cannot read null.priority
> 
> It ran into an error with his new proc which is why the old proc was coded the way it was.

what? these are different procs

**Comment by Simplehorror** [comment]
> @Simplehorror [09:17:02] Runtime in reactions.dm,62: Cannot read null.priority

yeah give me a bit im working on grues right now, my cmp function is being fed nulls

**Comment by ShoziOffical** [comment]
didnt see the s there

**Comment by Simplehorror** [comment]
ok should be fixed, it was trying to sort an associative list and it isn't

**Comment by ShoziOffical** [comment]
> ok should be fixed, it was trying to sort an associative list and it isn't

ok imma gonna run a debug server and test

**Comment by Simplehorror** [comment]
also I appreciate rdrazga shittalking me in the discord for fixing an atmos bug because it didn't work first try

**Comment by ShoziOffical** [comment]
> also I appreciate rdrazga shittalking me in the discord for fixing an atmos bug because it didn't work first try

so you are actually in discord

**Comment by Rdrazga** [comment]
> also I appreciate rdrazga shittalking me in the discord for fixing an atmos bug because it didn't work first try

Mate you are posting OPEN PRs that you are not even taking 2 minutes to bug test of course I am going to point it out.

**Comment by Simplehorror** [comment]
yes because i am working on grues and nobody else was going to do it if i didnt, be happy it happened

**Comment by Simplehorror** [comment]
obviously the code didn't work (first try), but the logic i had in mind was correct

**Comment by Rdrazga** [comment]
Ok fair I won't shittalk you as long as you do atleast spend time to bug and lag test this compared to the old code before getting it merged. If this breaks the server it won't be a good fix, if this lags the server people would much rather deal with not having hyper noblium forming properly rather then just laggy atmos reactions. This was a problem with the original TG fix it looks like so it should be a consideration.

**Comment by Simplehorror** [comment]
it's not going to lag the server, we don't use LINDA + a 5 list sort is nothing, plus I hope being respected isn't being conditional

**Review by warface1234455 — APPROVED** [review]
image
alright seems to work as intended, no lag, gas reactions are pretty smooth

**Comment by ShoziOffical** [comment]
the middle chamber is hypernob production, the right one is fusion chamber which is being stopped by hypernob

**Comment by ShoziOffical** [comment]
this is the first time im asking for a speedmerge of simeplehorror's PR

**Comment by Rdrazga** [comment]
In other news for the sake of my sanity (and far more likely future coders sanity) I am going to figure out how to github and put comments on all this dang code to explain what the hell is actually happening in half of this stuff because Jesus.

**Comment by Rdrazga** [comment]
> this is the first time im asking for a speedmerge of simeplehorror's PR

NGL I don't think hyper noblium forming is that pressing of an issue, also kat is going to yell at us for conflicting auxmos again

**Comment by ShoziOffical** [comment]
> > this is the first time im asking for a speedmerge of simeplehorror's PR
> 
> NGL I don't think hyper noblium forming is that pressing of an issue, also kat is going to yell at us for conflicting auxmos again

he will get it sorted out no worries, im atmos mains so i am on my knees for this

**Comment by Simplehorror** [comment]
> In other news for the sake of my sanity (and far more likely future coders sanity) I am going to figure out how to github and put comments on all this dang code to explain what the hell is actually happening in half of this stuff because Jesus.

i fear that you will leave incorrect comments (which would be worse if I read comments)

**Comment by iamthesilly** [comment]
works fine but hotspots from igniters and such still show up even when there's no reaction happening
image

**Comment by Simplehorror** [comment]
> works fine but hotspots from igniters and such still show up even when there's no reaction happening image

yeah igniters will still generate hotspot, but the hotspot wont react with anything, it's not a bug

**Comment by iamthesilly** [comment]
> yeah igniters will still generate hotspot, but the hotspot wont react with anything, it's not a bug

it can raise the temperature as it if's burning when it's not actually burning so i recommend fixing it

**Comment by Simplehorror** [comment]
that is what an igniter is going to do

**Comment by iamthesilly** [comment]
> that is what an igniter is going to do

it only heats the gas mixture if there's flammable gases in it, because the point of igniters raising temperature is to get the reaction to start, which shouldn't be happening if there's hypernoblium. it's not intended to be a heater.

**Comment by iamthesilly** [comment]
alright i've made my own pr for that (#16893), but i can close it if you want to include the changes in yours

**Review by ReddicusDragon — COMMENTED** [review]
I'm not even going to try reading atmos code it's black magic

**Comment by Simplehorror** [comment]
> I'm not even going to try reading atmos code it's black magic

no it is not

**Review by MajManatee — APPROVED** [review]
test your own god damned code in the future, or im just gonna start closing your PRs

**Comment by Simplehorror** [comment]
i did test this

**Comment by Bibby0110** [comment]
@monster860

**Comment by ShoziOffical** [comment]
> @monster860

github ping is shit

**Comment by Simplehorror** [comment]
remind me to do this properly

**Comment by ShoziOffical** [comment]
> remind me to do this properly

What else

**Pull request closed without merging**
