### PR TITLE
(port) A new pie and four more cakes!

### PR DESCRIPTION
**Pull request by boodaliboo**
original pr https://github.com/tgstation/tgstation/pull/45633
adds 
blackberry and strawberry vanilla cake
blackberry and strawberry chocolate cake
angel food cake
pound cake
hardware cake
baklava
#### Changelog

:cl:  
rscadd: Adds new chef content
/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Baklava is good

**Comment by boodaliboo** [comment]
> Baklava is good

it really is a armenian friend made it for me and my other friends once and it was amazing

**Review by Partheo — CHANGES_REQUESTED** [review]
image
this is so bad... It's not the end of the world since it's just a cake sprite, but I'd appreciate if you could find something a bit better than this...

**Comment by boodaliboo** [comment]
> image
> this is so bad... It's not the end of the world since it's just a cake sprite, but I'd appreciate if you could find something a bit better than this...

ill try to find one

**Review by missatessatessy — CHANGES_REQUESTED** [review]
Never mind xD

**Comment by boodaliboo** [comment]
unable to find better sprites

**Pull request closed without merging**
