### PR TITLE
Forces IAA to get good and removes their access to ez mulligan

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
bugfix: IAA can no longer buy mulligan syringes to become almost entirely untrackable
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
excuse me what the fuck

**Comment by SomeguyManperson** [comment]
What is your gimmick on iaa to just buy a mulligan whenever you have the tc for it

**Comment by Ratvar** [comment]
Bad gimmic then

**Comment by boodaliboo** [comment]
colors made this as he raged

**Comment by E231kei500bandai** [comment]
fun time. now the iaa get to hide in a locker after they kill their target!

**Comment by Takahiru** [comment]
Just fix the tracker that only tracks one target ever

**Comment by E231kei500bandai** [comment]
yeah but now they have to sit in a locker the whole game if tehy dont want people killing them and they arent allowed to kill back

**Comment by SomeguyManperson** [comment]
IAA continue to get targets until all other agents are dead why would yoh be hiding in a locker for the rest of the round

**Pull request merged**
