### PR TITLE
Adds old female pod head bud as a hairstyle for pods

### PR DESCRIPTION
**Pull request by Chubbygummibear**
So I forgor about the default female head style bud when making the pr, so i converted that to a hair and tried to touch it up just a bit to match the palette used by the sprite artist of the rest of the hairs.

Bud:
image

# Bald was too cursed for this world and will no longer be added

~~Bald is horribly cursed but Reed asked for it~~
image
image
~~He later changed his stance to~~
image
~~but it's too late for that now~~

~~BALD:~~
imageimage

:cl:  
rscadd: Adds news Phytosian hairstyles: Bud 
imageadd: Sprites for Bud hairstyles 
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
bald is fucking cursed

**Review by nesisknesis — COMMENTED** [review]
Don't think we should have bald. The hairstyles make them easily identifiable as plants but when they're baldy they're just multicoloured people

**Comment by Chubbygummibear** [comment]
the world isn't ready for bald phytosians, but one day you'll all see

**Comment by ToasterBiome** [comment]
@grimm-hollowknight is flower bud acceptable?

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
