### PR TITLE
Add antinoblium canister sprite

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Give antinoblium canister a sprite
You can now label antinob canister
You can now label danger canister

# Spriting
image

image

# Wiki Documentation
Give antinoblium canister a sprite
You can now label antinob canister

# Changelog

:cl:  
tweak: You can now label antinob canister
tweak: You can now label danger canister

imageadd: Give antinoblium canister a sprite

/:cl:

### CODE REVIEW

**Comment by GDRdev** [comment]
dammit I was planning on doing this... at some point

**Comment by GDRdev** [comment]
AntiNob_canister

**Comment by ShoziOffical** [comment]
a black canister with red/blue/white stripe may suit it better

**Comment by GDRdev** [comment]
also I feel like the fog should be changed honestly but thats a different PR, just dont like them files

**Comment by ShoziOffical** [comment]
> also I feel like the fog should be changed honestly but thats a different PR, just dont like them files

yeah the gas color looks like flies maybe someone should change to like blue gas or something similiar to antinob crystal

**Review by cuackles — APPROVED** [review]

**Pull request merged**
