### PR TITLE
photocopier butt sprite refactor from tg

### PR DESCRIPTION
**Pull request by 13spacemen**
All living mobs support butt sprites
all sprites put into a single .dmi instead of being separate pngs
added sprites for polysmorph, moths, phytosians, abductors, plasmamen, IPCs, slime/jelly people, humans with cat tail [covers humans AND felinids]

# Why is this good for the game?
refactored old code, makes more sense than the old if-else tree

# Spriting
Screenshot 2024-02-26 215406

# Testing
I did test it, forgot to take a screenshot though, works 100%; tested with non-human mobs and different human species

# Changelog

:cl:  
add: Moths, Phytosians, Abductors, Plasmamen, IPCs, Jelly/Slimepeople, Felinids, Polysmorph, all have their own butt sprites
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
fetish content

**Comment by wonderinghost** [comment]
Is IPC butt just a qr link to Rick astley

**Comment by Scrambledeggs00** [comment]
Post pics or it never happened. I must see plasmeme ass.

**Comment by JohnFulpWillard** [comment]
IconDiffBot:

**Review by cuackles — CHANGES_REQUESTED** [review]
its required to add the sprites into the spriting section of the pr, or at least a good portion of them

**Comment by 13spacemen** [comment]
@cuackles 
Screenshot 2024-02-26 215406

**Comment by cuackles** [comment]
> @cuackles Screenshot 2024-02-26 215406

I know perfectly well that they are in icondiff, but it's required to add the sprites into the sprite section of the pr, for people that aren't reviewrs or don't know how to see icondiff to be able to see them and to ease the ease of review, so again, sprites in the spriting section of the pr

**Comment by Hislyna** [comment]
> @cuackles Screenshot 2024-02-26 215406

My god thats some fetish content

**Review by cuackles — APPROVED** [review]

**Pull request merged**
