### PR TITLE
captain loses sec comms since you powergaming fucks keep trying to play him as HoS 2.0: All Access Edition

### PR DESCRIPTION
**Pull request by ghost**
In theory the captain is supposed to be a delegative head in command of all the other heads of staff.

In reality, it's a powergamer's wet dream-unlimited authority and usually serves in first-of-command in security with the HoS being demoted to a grunt with better weapons to do what he wants him to do.

While it doesn't exactly change much, this still forces the Captain to *communicate* with the other heads-or pay attention to common-rather than mindlessly do shit himself. I'm verging on removing the captain's brig access myself but this is a first step. Ideally this reduces Captains who either take over a head's ordering of their department or run security by themselves, and encourages people to play heads of staff if they want to run a department.

And yes I cleared this with the HC. 
:cl:  
tweak: Captain only has access to command channels
/:cl:

### CODE REVIEW

**Comment by Mesalikepie** [comment]
Adam on his alt got robusted by someone playing security captain recently someone go watch all the round logs to figure out who he is.

**Comment by yacabo** [comment]
Well it makes sense they need to have access to all channels, the vast majority of rounds don't have all heads so a lot of times the Captain has to take over command of that department.

**Comment by Mesalikepie** [comment]
Yeah in all seriousness he's the captain. He can kinda do what he wants. Security

**Comment by ghost** [comment]
not on MRP

**Comment by Mesalikepie** [comment]
Captain is an overseer. He needs to be able to pop into departmental comms and help out if there's no head, a heads down, or severe incompetence is going on. Yes sometimes this leads to cap security which sucks, but should be more of an issue to bring up with admins on rule changes then actually just ripping out half his job

**Comment by MegaEmpirical** [comment]
I can get behind this. Never liked how involved the Captain got in Sec all the time.

**Comment by Altoids1** [comment]
> Captain is an overseer. He needs to be able to pop into departmental comms and help out of there's no head, a heads down, or severe incompetence is going on. Yes sometimes this leads to cap security which sucks, but should be more of an issue to bring up with admins on rule changes then actually just ripping out half his job

This is wholly correct. All this does is get rid of the one guy who's sole job is to keep good communication and oversight of the departments.

This game has a **huge** communication problem. Forcing the Captain into only being able to communicate with Command and (probably) Security does not help that problem, nor help to combat captain-as-security. If anything, this just makes him want to explicitly grab a security transceiver and focus on overseeing the Security department.

**Comment by ghost** [comment]
fine i've been cajoled into readding everything _but_ sec comms

**Comment by ghost** [comment]
@Altoids1 Communication problems are the bread, butter, and soul of SS13, where not being able to communicate things is half the reason antagonists can do anything.

More impediments is always a good thing in that regard.

You CANNOT bring it up with admins and rely on admins to do everything. Why? Because admins _**won't do it.**_ Rule changes will do nothing.

Detective has been """"NOT SEC"""" for years, but admins never have and never will do anything to sectectives because they don't give a shit, it's still the det shooting an antag and that's fine by them.

The goal is to impede the captain. Make it a hassle. Because admins won't do it. If that has to stop here, that's fine. If I have to go ahead and remove his brig access too, i'll do that.

If he has to go and grab a sec radio, that's still a wasted inventory slot and an extra hassle trip for him.

CapCurity isn't a 'sometimes.' It is an ALWAYS. ALL captains are CapCurity. All captains communicate on the sec radio and run security and ignore all other departments, even if those other departments are falling apart.

The end, ideal goal is to force the Captain into a purely delegative and communicative position, not a do-everything all-access assistant who runs into science to get all the gamer gear and then goes around hunting down antags while admins shrug their shoulders, just like they do for the detective.

**Comment by Mesalikepie** [comment]
One good idea is removing security comms from being enabled on captains headset at roundstart cause that overtly encourages him to take special care of security. That is not ideal

**Comment by ghost** [comment]
yes which i just did by removing security radio from his radio.

if it keeps being a problem, i take th enuclear option and he loses brig access.

**Comment by TheLinuxOS** [comment]
This is an immensely stupid idea. Sec comms are important for a cap to be sure that the hos isn't authorizing executions without permission, and for him to ensure security isn't being a bunch of shitters. You shouldn't remove their access to an important comms channel just because some dumbasses powergame as captain, you should leave it to the admins to make sure people don't powergame as captain.

**Comment by ghost** [comment]
@TheLinuxOS I hear a lot of crying and not a lot of reasons where the fucking lawyer themselves couldn't do that job.

The HoS doesn't get to authorize executions without the captain's permission. You've got yourself in a bind there.

Either you: Admit admins won't do anything if someone breaks the rules and thus 'relying on admins' to handle the situation is a pointless endeavor because they never will,

OR: Acknowledge that your point about needing to make sure the HoS isn't authorizing executions is false.

As for preventing sec from being a bunch of shitters, they never do that either. This idea is fine. There are no problems with it. Captain doesn't need sec radio access. The HOS can keep them updated, and if there is no HoS, they promote a sec officer to HoS. 

If security is being a bunch of shitters, the HoS informs the Captain. Or the crew informs the Captain, and the Captain informs central command and tries to wrangle the security team with the help of the HoS. The captain doesn't need to _directly_ be there to know that-the lawyer's role is basically to be HR to report sec being shit, and the HoS is there to wrangle sec. 

The idea that the Captain needs to directly hear security radio to handle that situation is nothing more than a transparent excuse to justify powergaming and being CapCurity because all of the above is true and remains true. So the only reason he'd need it is to run security, and the only reason you'd need to run security is because you're a meddling powergamer who insists on playing as exactly the kind of Captain this PR aims to stop-a miniature micromanager/security officer who plays as First-In-Command of the security team while the HoS is shafted into a mindless grunt role who does what the Captain says.

Admins will never do anything about Captain-sec because Captain-sec is fine to them. I present as evidence every single Captain there is-Brenna, Sephka, Zero, Tajanub, Sayk, Pierre (albiet he's usually HoS), Alex, et cetera. All of them run and manage security. Hell, most admins do it too-Alex is a prime example.

So no, this PR is not an immensely stupid idea, and the only people who complain about the Captain losing sec radio are exactly the kind of people this PR is meant to stop-people like you, Linux, going by the dead giveaway you have there.

**Comment by ghost** [comment]
Bad PR. Find a way to kill hopcurity first, then kill capcurity with it.

**Comment by ghost** [comment]
@AutisticFroggy HOPcurity is already killed as well as  it's going to be

**Comment by Hopekz** [comment]
This PR is dumb because how else is the captain supposed to authorize executions if he doesn't have access to the security radio channel?
Through the common channel? Literally makes no sense at all.

**Comment by ghost** [comment]
@Hopekz 

Over

command channel

**Comment by TheLinuxOS** [comment]
I dont think we should waste our time arguing with adam on this one as he has quite literally stated, and I quote, "my argument is not flawed because I am never wrong" as well as "I'm not going to listen to anything you have to say" so ill just wait to see what headcoders decide about this.

**Comment by ghost** [comment]
@TheLinuxOS Jamie wanted the PR, so

**Comment by Hopekz** [comment]
> @Hopekz
> 
> Over
> 
> command channel

What codebase do you play in where warden or other sec officers have command channel?
Here only the HoS has this channel so if there is no HoS or he's unavailable they wouldn't be able to communicate with the captain to ask for an execution.

Your PR doesn't seem to solve a problem but introduces problems like sec not being able to reach out to the captain for execution if the HoS isn't available or present.

**Comment by ghost** [comment]
@Hopekz 

promote

a hos

**Comment by Hopekz** [comment]
> @Hopekz
> 
> promote
> 
> a hos

Alright, now I can't tell if you're serious. Is this a meme PR?

Promoting a HoS requires either the HoP (doesn't follow sec channels) or the captain (wouldn't follow sec channels after this PR). Thus just making more problems and inconveniences while not solving anything. You're just moving everyone to the general channel instead of the sec channel.

Your change would put the captain out of touch with sec so now he's supposed to magically know to promote a HoS when he can't see what's going on?
What does the captain now need to communicate with sec officers via PDA to promote them?

If this isn't a meme PR hopefully people take it seriously if that's what you're going for.

**Comment by ghost** [comment]
It's a serious PR. First step of a few.

1. Lawyers are revamped to IAAs, designed specifically to wrangle security. They can override sentences at any point set by anyone, even the HoS, and have the final say as to space law. While they're explicitly forbidden from ever arresting anyone, or even carrying a weapon, they can message central command as to if space law isn't followed (which can prompt an investigation) or have an officer fired or demoted. 

As compensation, they also can't be antags anymore, since that's a lot of power. No mindshield implant, but they can't be antag'd. 

2. The captain loses security radio. Possibly security access, even, but i'd prefer a rules change on that.

3. The sec protolathe is moved to inside the armory, to prevent officers getting their hands on lethals without the warden's permission.

4. Captain gets a big fat wall of text at roundstart telling him he's not sec, he's supposed to manage the heads of staff, and to NOT run to security for HUDS+RADIO+BATON combo and go hunting antags.

Is my whole gameplan here.

And yes, I mean...the Captain will...know to promote a HoS because he will just see that there's no HoS. And then promote one. It's really not a difficult concept, I mean, communication exists. You just ask 'Is there a HOS" on command comms and then promote one if there's not/you check the crew manifest and see there is no HoS/you ask the AI if there's a HoS.

**Comment by Marmio64** [comment]
if captain is being capcurity, admins should deal with them, and more text should be given in game to clarify that he isn't security. There is no reason to make it so captain can't communicate easily with security if it is needed.

**Comment by Tipy1802** [comment]
Yeah let’s have the role that’s supposed to issue orders and make sure departments are doing their job not be able to issue orders or know what’s going on. Brilliant

**Comment by JamieD1** [comment]
In theory this is good, however we do not have enough sustained population for this to be allowed.

Captain should be literally that, a Captain. He should be in charge of the heads and not get involved. I would be all for this PR except for the instances of low pop where there is noone but a captain and he has to be every Head of Staff. 

So Sorry but no this stays.

**Review by JamieD1 — CHANGES_REQUESTED** [review]
Make it depended on population or numbers of heads of staff and ill consider it.

**Comment by ghost** [comment]
@Marmio64 'admins should deal with them'

they won't.

'more text'

already coming.

**Comment by Tipy1802** [comment]
Tell me how the captain not being able to communicate with the crew (his only job) prevents the captain from arming up and valid hunting. If anything captains now HAVE to do it because they cannot rely on security and have to arrest people in their own, this so stupid and it can be bypassed by just lawfuly taking a sec headset, extracting the encryption key and inserting it in the captain's headset. Just one more example why we shouldn't listen to people that don't play on the server, have absolutely no idea what's going on in the server or the meta yet all they do is make PRs addresing said meta while insulting everyone

**Comment by Tipy1802** [comment]
On top of that the captain needs a way to tell sec who to arrest and also sec needs a way to ask the captain for permission to execute or use lethal force. This PR doesn't solve any issues but only creates more issues.

**Comment by MegaEmpirical** [comment]
Captain can tell the HoS over command, use any of the ways crew normally uses to tell sex to arrest someone, or even use the sec console.

**Comment by Moja10** [comment]
Damn, stuff like lawyer becoming IAA, seclathe to armory, and less Captain playing upgraded HoS sounds really fucking swell, but this change isn't it, chief.

**Comment by faaaay** [comment]
Why in the world would the Captain - _the highest authority on the station_ - be unable to access the Brig?

**Comment by ghost** [comment]
@faaaay

Because they don't _need_ to since they're not sec. Or at least, they'd lose armory access.

They still have an ID console, they could still give themselves that in an emergency, but the issue is that the Captain ends up being a second head of security who relegates the HoS to a grunt role, rather than the delegative role they're supposed to be. Rather than ordering the HoS, who orders security, they instead order security, and that takes away the HoS' main role-which means he has nothing to do but validhunt. 

And all captains validhunt as well.

Forcing the captain to communicate with the HoS to coordinate security removes this problem.

@Tipy1802 I genuinely don't understand how you think like this, tbh.

>If anything captains now HAVE to do it

No more than the HoP being unable to talk on sec comms means he HAS to arm up and go arrest people himself. HoP isn't sec, Cap isn't sec.

**Comment by faaaay** [comment]
> 
> 
> @faaaay
> 
> Because they don't _need_ to since they're not sec. Or at least, they'd lose armory access.
> wordswordswords

@AdamElTablawy 
Should we take away the CMO's Genetics access? After all, they'd be better off healing people, and they can give themselves access if they really need it. Should the HoP have cargo access? They're not cargo.

The answer is, of course, that _it's part of their jurisdiction_ and thus they need to have access so that they can effectively run it.

> And all captains validhunt as well.

Factually false.

**Comment by Tipy1802** [comment]
I don't see how is this a Captain - HoS problem since that's how the captain acts with most heads
You seem to forget that the Captain is not just the head of command but the head of the whole station

**Comment by Oakboscage** [comment]
Probably the dumbest PR of the year.

**Comment by ghost** [comment]
@faaay

Factually true.

And no, the CMO needs genetics access to run genetics. The captain doesn't need sec access because they're not the ones running the department. The HoS is.

@Tipy1802 It is a problem when it comes to all heads, yeah. The thing is the Captain usually ignores all departments BUT sec to exclusively arm and armor up in security.

Roundstart, every captain will immediately get a secHUD, a stunbaton (when they have a perfectly serviceable telebaton) and whatever else they feel like from security and then proceed to run the department in the place of the HoS.

The captain is meant to be a delegative role-order the heads of staff, who order their department. 

It doesn't resolve captains acting as sec by any means, since they can easily bypass it. But it wouldn't make much sense to give them a big fat warning that they're not sec in chat at roundstart, have admins crack down harder on capcurity, but leave them with sec radio, now would it?

Especially since nobody's listed any reason they actually NEED security radio by any means. They don't. They can just talk on command radio to ask the HoS what's going on. 

@Oakboscage Coming from the idiot who threw such a big fit he wasn't allowed to say the n-word that he went and got himself community banned and then tried to start handing out logs of all of council chat to everyone, including me, in the hopes that someone would leak it and start shitstirring, I'm disinclined to take anything you say to heart in regards to what's dumb or not.

**Comment by faaaay** [comment]
> @Faaay

> Factually true.

All clowns are assholes, all QMs buy guns, all assistants will beat you with a toolbox. Sorry bud, that's factually true because I said so.

> And no, the CMO needs genetics access to run genetics. The captain doesn't need sec access because they're not the ones running the department. The HoS is.

The Captain runs the station, and by extension, everything in it. Taking their sec access away is counterproductive to their role not only by undermining their ability to check on and oversee the station, it contradicts the fact that they're the highest authority on the station.
By your logic, should they lose access to all departments as they shouldn't be running them? No, of course not. While most of the time the Captain _should_ delegate to the other heads, it's integral that they _can_ overrule them.

**Comment by Tipy1802** [comment]
You do realise that everything genetics other than cloning is science and under the RD's authority?

**Comment by Tipy1802** [comment]
Also you seem to not know but telebatons got nerfed and are shit now. You need to hit someone three times before cuffing them so that's why captain take stun batons

**Comment by Spl99** [comment]
Why would it make sense for the captain of a space station to not have access to other channels? Regardless of the population on the station, they need to have access to all channels at all time to enable them to make informed decisions in regards to any ongoing situations that may be happening on board their station.
Security can end up being a vital department on the station if a threat is ongoing. Why would you want your commanding officer to be in the dark and relying on the HoS to report to them. What if the HoS is in combat, dead or injured and unable to relay up to date information to the captain.

**Comment by ghost** [comment]
@spl99 

please contact me on discord to discuss that as to avoid this PR getting any more spillover than it currently is.

**Comment by JamieD1** [comment]
I would be happy with Captain only having command and security. Captain does need to be in security as he is the end of the line for executions.

**Pull request closed without merging**
