### PR TITLE
Revert "Beepsky does stamina damage instead of instant stun"

### PR DESCRIPTION
**Pull request by JamieD1**
Reverts yogstation13/Yogstation#18691

He can be one tapped, skill issue

### CODE REVIEW

**Comment by Bibby0110** [comment]
48 hour rule

**Comment by JamieD1** [comment]
> 48 hour rule

????

**Comment by Bibby0110** [comment]
48 hour rule. Read the contributing guidelines before making a PR please.

**Comment by JamieD1** [comment]
"These rules do not apply to corrections made by a HD for a Pull request merged by a maintainer incorrectly or if they disagree it should have been merged in the first place."

Me and Bai believe this should not of been merged in the first place.

**Comment by Bibby0110** [comment]
Inadequate rationale

**Pull request merged**
