### PR TITLE
Sinful demon changes + re-enable

### PR DESCRIPTION
**Pull request by Marmio64**
Attempts to reword objectives and balance out demons more.

1: gluttonous demons hunger 3x as fast as normal people 
2: all demons no longer enter softcrit (still can enter hardcrit), are geneless, dont suffocate in crit, and have stable hearts. (Mainly for flavor and also to make it so they have a higher chance of still being alive after exiting demon form)
3: true demon form deals 20 damage instead of 24 (wrath is 24 instead of 28). Health is lowered to 160 (from 200) and health regen per hit is now 8 instead of 10. To compensate, they are ever so slightly faster, but are still slower than everyone but podpeople. Demons also lose 2 hp every life tick (a life tick is generally 2 seconds, so 2 hp every 2 seconds), so as to try to deter you from staying in demon form the entire round.
4: objectives are made a bit less murderbone-ey.
5: sinful demon spawns slightly less often
6: envy demon no longer has a chance for an extra objective to steal the identity of a specific person

I still want to try to make them more unique and fun to play as and against so please suggest changes, especially if you think any of these current changes will instead make them worse rather than better.

new objectives-
Gluttony: Devour as much food as possible. Do not devour or kill people unless they have gone out of their way to hunt you, or are expressly stopping you

Greed: Acquire as much wealth as possible. Do not kill people for the purpose of acquiring wealth, injury is fine.

Wrath: Inflict as much pain as possible. Do not go on rampages to quickly murder, prolong the suffering of individuals instead."

Envy: Assume the identity of the most powerful person onboard. Deaths of non-targets is to be avoided as best as possible."

Pride: Become as popular, powerful, and influential to as many people possible. Committing crimes is likely to make you less popular with most people."

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Sinful demons in human form get a slight buff. Gluttonous demons hunger faster
tweak: sinful demon objective clarification. Demon form tweaks.
/:cl:

### CODE REVIEW

**Comment by MommaDragon** [comment]
These... look quite good. What's the opinion of the heads, then?

**Comment by ilikesaying** [comment]
Gluttony Demons on their way to eat every 100 potency watermelon

**Comment by VaelophisNyx** [comment]
non-turbo-murderbone wrath demon is good actually

**Comment by JamieD1** [comment]
This is much better.

**Comment by Marmio64** [comment]
i was going to add onto this more and maybe see about adding more abilities to the demons, but i'll likely see if I can do that in another PR, since I don't have time right now. PR in it's current state should be good to go.

**Comment by JamieD1** [comment]
Can you remove the ability to borg demons of sin, I dont want to deal with the situation with laws and shit with this mob. Would be easier just to make it not a thing.

**Comment by Marmio64** [comment]
> Can you remove the ability to borg demons of sin, I dont want to deal with the situation with laws and shit with this mob. Would be easier just to make it not a thing.

not right now, will have to wait a while.

**Comment by JamieD1** [comment]
> > Can you remove the ability to borg demons of sin, I dont want to deal with the situation with laws and shit with this mob. Would be easier just to make it not a thing.
> 
> not right now, will have to wait a while.

For?

**Comment by Marmio64** [comment]
> > > Can you remove the ability to borg demons of sin, I dont want to deal with the situation with laws and shit with this mob. Would be easier just to make it not a thing.
> > 
> > 
> > not right now, will have to wait a while.
> 
> For?

already wrote on discord but ill put it here too

busy with jungleland and this took me longer than expected to try to figure out

**Comment by JamieD1** [comment]
> > > > Can you remove the ability to borg demons of sin, I dont want to deal with the situation with laws and shit with this mob. Would be easier just to make it not a thing.
> > > 
> > > 
> > > not right now, will have to wait a while.
> > 
> > 
> > For?
> 
> already wrote on discord but ill put it here too
> 
> busy with jungleland and this took me longer than expected to try to figure out

DM me when you do this then

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
