### PR TITLE
Adds cyborg damage slowdown

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

at 50 damage it will begin slowdown and will slow more as you are further damaged

#### Changelog

:cl:  alexkar598, ynot01
rscadd: Cyborgs now slowdown when damaged until repaired
/:cl:

### CODE REVIEW

**Comment by Potototatoh** [comment]
yes yes yes ye,s yes, yes, yse yes  , yyes yes yes ,y se yes-yes -y ss yrs yes yse

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Do it sanely like humans(mob/living/carbon/human, not an insult here) do. Calculate the damage(maxHealth - Health), check if its over 40, if so, devide it by 25 and you have your multiplicative slowdown

**Comment by Ratvar** [comment]
One day borgs will stop being so OP you need to give every single antag multiple AOE stuns just for a slim hope of not dying. With this PR, this day is closer.

**Comment by yacabo** [comment]
What's the slow down for when an organic takes damage? This should probably be similar to that.

**Comment by ynot01** [comment]
> What's the slow down for when an organic takes damage?

changes to this are currently being made please hold

**Comment by overlord12345** [comment]
Best PR

**Comment by alexkar598** [comment]
Mayyyybe 100 instead?

**Review by alexkar598 — APPROVED** [review]
Looks good imo but I wrote this code so can someone else review

**Comment by ghost** [comment]
finally

thanks for takin my advice

**Pull request merged**
