### PR TITLE
Temporairly disables mousemove event to see if it helps with lag, will break wizard spellcards and space pods

### PR DESCRIPTION
**Pull request by alexkar598**
Temporairly disables mousemove event to see if it helps with lag, will break wizard spellcards and space pods

test merge

### CODE REVIEW

**Comment by Darkstick** [comment]
mousemove event?

**Comment by Nechronom** [comment]
I think it's a means of aiming something towards the mouse? In the case of space pods it's the direction that the front is facing. I've never gotten to play wizard so I don't know what spell cards they mean

**Comment by DiamondSentinel** [comment]
> 
> 
> I think it's a means of aiming something towards the mouse? In the case of space pods it's the direction that the front is facing. I've never gotten to play wizard so I don't know what spell cards they mean

Spell cards is a spell that casts multiple bursts of damaging cards that follow the mouse cursor over time. Lets you spam it ridiculously, and is quite fun, if not for the fact that it's absolutely awful.

**Comment by jcatjmeow** [comment]
> mousemove event?

it means the game keeps track of when the mouse is moved and where it is.

This, as you might imagine, comes at a cost of performance

**Comment by Amelia0010** [comment]
@alexkar598 what's the status of this?

**Comment by alexkar598** [comment]
It helps with lag, the spell cards can AFAIK work without this but the pod needs something on process() to get the mouse location and use it instead of listening for mouse move

**Comment by JamieD1** [comment]
Can we fix the Pod Issues?

**Pull request merged**
