### PR TITLE
Removes Jive Accent

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

The only people I have ever seen use Jive Accent are "Tyrone Watermelon" characters, it's only used in conjunction with the blackest skin and the biggest afro along with some colorful decisions on translations:

Home: "plantashun" (WHAT)
People: "sucka's"
Metal: "meta-fuckin'l"
Women: "honky chicks"

It's barely even used (if used at all) by players of darker complexion, only shitty trolls who think it's funny to do the same 1 racist character over and over.

# Changelog

:cl:  
rscdel: Removes Jive Accent
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Racist people ruining the game

**Comment by Hopekz** [comment]
No problem in removing this one.
This particular accent was created via https://funtranslations.com/jive and I don't remember me being able to fully check this one.

In https://funtranslations.com/jive when I put in "home" it spits out "plantation" so yeah I'd say that could be considered racist and should be removed.

**Comment by Hopekz** [comment]
> Racist people ruining the game

Who knew there was an alleged racist in an innocent-sounding website called "funtranslations"
The description doesn't even give any clues that it might contain that content

image

**Review by Bibby0110 — APPROVED** [review]

**Comment by Marmio64** [comment]
> > Racist people ruining the game
> 
> Who knew there was an alleged racist in an innocent-sounding website called "funtranslations" The description doesn't even give any clues that it might contain that content
> 
> image

I was more saying people who just make extreme stereotypes are stopping others from using these accents

**Pull request merged**
