### PR TITLE
[PORT] New bluespace harvester sprite from paradise and tweak

### PR DESCRIPTION
**Pull request by warface1234455**
* from https://github.com/ParadiseSS13/Paradise/pull/21232
# Document the changes in your pull request
Resprites the Bluespace Harvester.

Also also slightly changes the nether portals event, so that the portals spawn sequentially over at most 15 seconds.
The BSH will glow red and be inoperable until they all are destroyed.

# Why is this good for the game?
BEtter sprite is cooler

# Testing
(watch to the end to see cool glowy red BSH)
crate

# Spriting
image

# Wiki Documentation
update wiki sprite prob

# Changelog

:cl:  kugamo, warface1234455
imageadd: Resprites the Bluespace Harvester.

tweak: Also also slightly changes the nether portals event, so that the portals spawn sequentially over at most 15 seconds.
The BSH will glow red and be inoperable until they all are destroyed.
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
DAMN that sprite looks out-of-place

**Comment by cowbot92** [comment]
you know its a good pr when cartlord hates it

**Comment by Cartlord** [comment]
I think the mechanic is cool, I just think the sprite's wack

**Comment by MajManatee** [comment]
Damn that's a cool sprite

**Comment by cuackles** [comment]
> DAMN that sprite looks out-of-place

BSA
image
Dna vault 
image
thing that starts the tesla 
image

it a extreamly similar style to all of these idk what u even on about

**Review by cuackles — APPROVED** [review]

**Pull request merged**
