### PR TITLE
uh oh

### PR DESCRIPTION
**Pull request by ynot01**
i forgot to add this file to the dme
turns on https://github.com/yogstation13/Yogstation/pull/17833

### CODE REVIEW

**Comment by YashinHak** [comment]
uh oh

**Comment by Aquizit** [comment]
uh oh

**Review by Moltijoe — APPROVED** [review]
whoops, accidentally removed darkspawn rather than making it midround

**Comment by alexkar598** [comment]
Uh oh

**Comment by cowbot92** [comment]
good thing someone noticed immediately and not 6 months later

**Pull request merged**
