### PR TITLE
Donator axolotl plush for Slicerv

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Add a donator specific plush for slicerv

# Spriting

image

# Changelog

:cl:  
rscadd: Adds an axolotl plush for Slicerv
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
why is tail like that

**Comment by ToasterBiome** [comment]
> why is tail like that

they have weird semi-transparent tails

**Comment by KillerOrcaCora** [comment]
You only need 2 colors on that tail paired with the range tool to represent that, right now it's just banding to hell along with a few jaggies.

**Comment by ToasterBiome** [comment]
> You only need 2 colors on that tail paired with the range tool to represent that, right now it's just banding to hell along with a few jaggies.

image

**Review by KillerOrcaCora — APPROVED** [review]
Approved Tail customs

**Pull request merged**
