### PR TITLE
Fixes agent id's and adds bank accounts to them

### LINKED ISSUE #8405: Agent IDs dont forge a 2nd time after they have a name on them.
Round ID 29256 and another round a few days ago

Basically you buy an agent id and you forge it like your regular id such as "onion oblivious" "chief engineer" and it changes to that. then after if you need to change the id to work with your chameleon mask, the forge button just shows the id in the same way showing the id does. this also happened to me while I was a syndicate comms agent. 

Going to forge the id as a comms agent:
https://i.imgur.com/HhVv5ze.png

what actually happened:
https://i.imgur.com/JjyPWiM.png

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Fixes Agent ID's Forging,

Also adds bank account changing

Fixes #8405

#### Changelog

:cl:  
rscadd: Adds bank accounts to agent ids
bugfix: Fixes Agent ID Forging
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
> ### Intent of your Pull Request
> Fixes Agent ID's Forging,
> 
> Also adds bank account changing
> 
> Fixes #8405
> 
> #### Changelog
> 🆑
> rscadd: Adds bank accounts to agent ids
> bugfix: Fixes Agent ID Forging
> /🆑

how does this adding bank accounts work does it take the buyers bank does it take their set names bank?

**Comment by SomeguyManperson** [comment]
image

**Comment by JamieD1** [comment]
> > ### Intent of your Pull Request
> > Fixes Agent ID's Forging,
> > Also adds bank account changing
> > Fixes #8405
> > #### Changelog
> > 🆑
> > rscadd: Adds bank accounts to agent ids
> > bugfix: Fixes Agent ID Forging
> > /🆑
> 
> how does this adding bank accounts work does it take the buyers bank does it take their set names bank?

It random makes a bank account on spawn and it means you can change it via forging.

**Review by fluffe9911 — APPROVED** [review]
I hate this review system

**Pull request merged**
