### PR TITLE
Helps Doctors Follow SOP (Ported From BeeStation)

### PR DESCRIPTION
**Pull request by ReddicusDragon**
# Document the changes in your pull request
Adds Anesthesia Machines so doctors actually use anesthesia. Before I get bitched at, I am open to changing the timings on any of these actions. Ported from [BeeStation/BeeStation-Hornet#3753](https://github.com/BeeStation/BeeStation-Hornet/pull/3753)

# Spriting
image

# Wiki Documentation
Adds Anesthesia Tank Holders. Can turn a regular IV drip into an Anesthesia Tank Holder by screwdrivering it with a mask in hand. Alt-Click removes the current tank inserted into it. To put a mask from the holder on a person undergoing surgery, drag the Anesthesia Tank Holder onto the patient. To remove the mask after surgery, click the Anesthesia Tank Holder.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:TheReddDragon
rscadd: Added Anesthesia Tank Holder, ported from BeeStation
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
how are users meant to know they can do this

**Comment by ReddicusDragon** [comment]
> how are users meant to know they can do this

The anesthetic tank holders are called anesthetic tank holders so hopefully anyone with a single functional braincell makes the connection that you can put anesthetic tank in an anesthetic tank holder. Additionally, anesthetic tank holders have been added to all medbays on relevant maps and, much to my hatred of mapping, shuttles that have surgical capabilities.

**Comment by Hopekz** [comment]
> > how are users meant to know they can do this
> 
> The anesthetic tank holders are called anesthetic tank holders so hopefully anyone with a single functional braincell makes the connection that you can put anesthetic tank in an anesthetic tank holder. Additionally, anesthetic tank holders have been added to all medbays on relevant maps and, much to my hatred of mapping, shuttles that have surgical capabilities.

I think he means the part where you have to screwdriver it with a mask in your hand because that seems pretty arbitrary

**Comment by Moltijoe** [comment]
> I think he means the part where you have to screwdriver it with a mask in your hand because that seems pretty arbitrary

Some have been added to maps so i assume it'll just be something people will never know about because they'll just use existing ones

**Comment by ReddicusDragon** [comment]
> > > how are users meant to know they can do this
> > 
> > 
> > The anesthetic tank holders are called anesthetic tank holders so hopefully anyone with a single functional braincell makes the connection that you can put anesthetic tank in an anesthetic tank holder. Additionally, anesthetic tank holders have been added to all medbays on relevant maps and, much to my hatred of mapping, shuttles that have surgical capabilities.
> 
> I think he means the part where you have to screwdriver it with a mask in your hand because that seems pretty arbitrary

If someone tells me where to add it to the wiki I will upon this getting merged

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
On behalf of map:

Remove all the ones from the emergency shuttles. If they want to use it then they can bring the multiple from medical.

I don't know how I feel about 2 just sitting there in each map, looks like they were just smacked right on there.

**Comment by ReddicusDragon** [comment]
> On behalf of map:
> 
> Remove all the ones from the emergency shuttles. If they want to use it then they can bring the multiple from medical.
> 
> I don't know how I feel about 2 just sitting there in each map, looks like they were just smacked right on there.

Will remove the emergency shuttle ones, however as for the ones sitting in at roundstart, if you can suggest a better place to plop them I am all ears. I put them in the surgery area because otherwise people won't use them at all.

**Comment by neeshacark** [comment]
What is stopping someone from walking up to you and connecting you to it in main halls to screw you over real quick?  Can you make it so it only applies if the person is laying down?

**Comment by ReddicusDragon** [comment]
> What is stopping someone from walking up to you and connecting you to it in main halls to screw you over real quick?  Can you make it so it only applies if the person is laying down?

Making it lay down only is unnecessary due to the do_after statements to connect it to a person. If memory serves, I think I have the time set to 4 or 5 seconds to slap a mask on someone

**Comment by ReddicusDragon** [comment]
> On behalf of map:
> 
> 
> 
> Remove all the ones from the emergency shuttles. If they want to use it then they can bring the multiple from medical.
> 
> 
> 
> I don't know how I feel about 2 just sitting there in each map, looks like they were just smacked right on there.
> 
> 

@ToasterBiome this is ready for another mapping review

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
this still shows as all the shuttles having (invisible) changes. Adding and then removing something will alter the map file still due to the nature of dmm maps. Ask someone with Git knowledge how to pull these shuttles back from upstream/master.

**Comment by ReddicusDragon** [comment]
> this still shows as all the shuttles having (invisible) changes. Adding and then removing something will alter the map file still due to the nature of dmm maps. Ask someone with Git knowledge how to pull these shuttles back from upstream/master.

Done, thankfully.

**Comment by MajManatee** [comment]
I don't think that this was the reason nobody uses it. 
The cons from not using it are... damage? which 90% of doctors will fix with wound tending instantly after. If you go into crit who cares, You're in medical and they will revive you. 

Most people don't want it anyways because then A.) They get put to sleep, and are vulnerable to all sorts of troublemakers. and B.) Its annoying to not be able to see what's going on around you, nor be able to interact with anyone while on going.

Meanwhile, if you DO use it, you get a negligible success chance boost or something?

its cool sure, but it wont make anyone want to use it more.

**Comment by Hopekz** [comment]
> I don't think that this was the reason nobody uses it. 

Can't hurt to check. Worst case scenario there's another item on the map that maybe gets removed later

**Comment by ReddicusDragon** [comment]
@ToasterBiome I request a final map review, pretty please

**Comment by ReddicusDragon** [comment]
> I don't think that this was the reason nobody uses it. The cons from not using it are... damage? which 90% of doctors will fix with wound tending instantly after. If you go into crit who cares, You're in medical and they will revive you.
> 
> Most people don't want it anyways because then A.) They get put to sleep, and are vulnerable to all sorts of troublemakers. and B.) Its annoying to not be able to see what's going on around you, nor be able to interact with anyone while on going.
> 
> Meanwhile, if you DO use it, you get a negligible success chance boost or something?
> 
> its cool sure, but it wont make anyone want to use it more.

Damage from not using anesthetic is 50% likely to happen. I fully intend on increasing the damage fucking up off anesthetic causes in a later PR.

**Review by ToasterBiome — APPROVED** [review]
maps fine

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
