### PR TITLE
sci rwall rebalance

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

xenobiology reinforced
toxins reinforced
nanites weakened
testing lab weakened
robotics weakened
R&D weakened
sci front door weakened
experimentor weakened
server room weakened
mech bay untouched

visual
image

### Why is this change good for the game?

science is no longer as much of an untouchable fortress
rwalls are now only on things that need them

:cl:  
tweak: Science's r-walls have been moved about
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Wut what's the point of shutters if the area with shutters isn't secure anymore
image

**Comment by ynot01** [comment]
> Wut what's the point of shutters if the area with shutters isn't secure anymore

cant bash open shutters or walls, call it anti-greytide

**Comment by Tipy1802** [comment]
and what’s the reason for the change and why is it good, you don’t really describe that it the template but just restate what the PR does and I really want to know why this is a good decision?

**Comment by ynot01** [comment]
> and what’s the reason for the change and why is it good, you don’t really describe that it the template but just restate what the PR does and I really want to know why this is a good decision?

science is no longer as much of an untouchable fortress
rwalls are now only on things that need them

**Comment by ynot01** [comment]
woops

**Comment by patpol4** [comment]
> science is no longer as much of an untouchable fortress
> rwalls are now only on things that need them

This explains what it does, not why it's good

**Comment by ynot01** [comment]
> This explains what it does, not why it's good

i see these to be good things for the game, such a thing is going to be pretty subjective; maybe I'm missing something here
science is less secure and rwalls are no longer as unnecessarily strewn about the entire place, if you want a rewording of it?

it won't be some powercreep hidey hole (though the powercreep isn't reduced by this change) and it can more easily be broken into, while places that would benefit from it in a workplace-scenario (simplemob outbreak or explosions) are more reinforced

**Comment by Tipy1802** [comment]
Why does greytiders breaking in and powergaming RnD (researching what they need and printing the powerful stuff from the lathe like the portal gun, BoHs and so on) good?
Why does removing social interactions like asking scientists to research something or print you something with you breaking in and doing it yourself better?
Why does making the most easy and boring objective - steal tech nodes, even easier good?
Why is making one of the most powerful techfabs even less secure good? (engineering, security and even medical techfabs are behind rwalls and/or windows)
Same thing with the circuit printer.
And this is just about the RnD room, don't get me started on the other

**Comment by ynot01** [comment]
> Why does greytiders breaking in and powergaming RnD (researching what they need and printing the powerful stuff from the lathe like the portal gun, BoHs and so on) good?

if scientists don't have 99 rwalls to hide behind they will have more incentive to actually work with people instead of afking at their consoles and closing shutters to the outside world

> Why does removing social interactions like asking scientists to research something or print you something with you breaking in and doing it yourself better?

see above, scientists don't interact with people unless they're forced to

> Why does making the most easy and boring objective - steal tech nodes, even easier good?

poorly designed objective, don't blame me for it

> Why is making one of the most powerful techfabs even less secure good? (engineering, security and even medical techfabs are behind rwalls and/or windows)

windows are not "secure"
engineering techfab is not behind rwalls
security techfab is secure for obvious reasons
medical techfab is designed kind of weirdly but is open to several normal walls

> Same thing with the circuit printer.

see above, the science circuit imprinter is just the engineering circuit imprinter but worse

> And this is just about the RnD room, don't get me started on the other

go off

**Comment by Ratvar** [comment]
Does xenobio, sit-afk-in-a-box department, needs wall buff, more so from side observed by researchers? Seems untouchably fortressy

**Comment by alexkar598** [comment]
RnD server should remain reinforced as it has a HUGE impact on the round if an antag can destroy it early on

Toxins and RD wall should remain normal as it helps balance out the fact the rd office is super public by giving it a weakness where people can break in semi sneakly from.

Same thing for xeno and toxins storage but for stealing plasma.


Everything else is good IMO

Altho I'd keep the wall near testing lab reinforced becaus ether fuel tanks there have a tendency to explode(but nanites should be normal walls as to not impact the overall break-in-ability of the place.

**Comment by Tipy1802** [comment]
> if scientists don't have 99 rwalls to hide behind they will have more incentive to actually work with people instead of afking at their consoles and closing shutters to the outside world

what how does making it so greytiders can break in eaiser to powergame shit somehow increase scientist being more social? Literally how. If anything it does the opposite now when I am in RnD I will keep the shutters closed 24/7 so tiders don't break in but before the change I would leave them open and talk with people if they come to the desk and want something.

> see above, scientists don't interact with people unless they're forced to

And how does this PR force them to interact with people? You literally don't encourage ANY interactions and as I said before actually do the opoposite. On top of that this is false, whenever I need science to research or print something PDA messaging a scientist does the trick and actually when I have played scientist I have socialised a lot with my co-workers in the department more than when I have played any other departments actually.

> windows are not "secure"

yes they are more secure than a normal wall

>medical techfab is designed kind of weirdly but is open to several normal walls

The medical techfab is deep within medbay so you need to break multiple walls

> poorly designed objective, don't blame me for it

I can blame you for making it even worse and just because something is bad does not excuse you from making it worse

> security techfab is secure for obvious reasons

So is science techfab, literally almost AA giving portal guns can be printed there

> see above, the science circuit imprinter is just the engineering circuit imprinter but worse

It can print the board for the engineering circurit printer though and on it's own is still valuable

> go off

The server rooms are a restricted area where people have no buisness in, they are indeed supposed to be reinforced.

Nerfing the walls boardering maint is odd and out of standart as most departments have the maint walls reinforced
image
image
image
image
image

As Alexkar stated the weakness in the RD office to the toxins side is strategically placed with that intent

And in general RnD has a good reason for being reinforced (it is not even the most reinforced department, engineering, secuirty and command are more reinforced)

1. It is the department with the most high risk items (reactive vest, holotool, slime extract, plasma and research nodes)
2. It has powerful tools that can be stolen from it  (Toxin bombs, Xenobio cores, Mechs from robotics, Literally everything in the techfab and the nanite cloud)
3. Despite all of these things science is not legally a restricted area so security are not likely to go after you just for breaking and entering and even if they do it's only 3 minutes compared to the 7 minutes for restricted areas

I would like to remind you as the one who is pushing the change the burden of reasoning is on you and so far I am yet to see it.
As I stated before this does not make scientists more social and you have shown no proof of it. All I see coming out of this is shitters breaking in and stealing powergaming tools. Which on top of being bad behaviour and against the rules to an extent is the very opposite of social interactions.

**Comment by maxion12345** [comment]
its a research station

the research area is reinforced

i dont see an issue here. i'll be enjoying the greytiders salty cries from within my secured department.

**Comment by LazennG** [comment]
FUCK science

**Review by patpol4 — CHANGES_REQUESTED** [review]
Tweak this like what alexkar said and it should be mostly ok imo.
Rnd server reinforced (only from maint is ok), RD normal, toxins normal.
Also Im not sure about nanites but I suppose they can stay normal because nobody sabotages nanites.

**Comment by ynot01** [comment]
will tweak soon been busy

**Comment by MegaEmpirical** [comment]
You animal, science NEEDS more rwalls.

**Pull request closed without merging**
