### PR TITLE
Fixes some labcoats being invisible when toggled

### LINKED ISSUE #7468: fancy robotics coat
Issue reported from  Round ID: 27033 (Yogstation 13)

Reporting client version: 512.1488

when you try to close the buttons the texture of the clothing disappears both on the item and the wearer

### PR DESCRIPTION
**Pull request by Ktlwjec**
Fixes #7468 .
robotics steampunk labcoat and robotics fancy labcoat

Swaps the normal labcoats around so they are closed by default.

### CODE REVIEW

**Comment by Potototatoh** [comment]
the labcgoats are inverted also when you toggle them

**Review by alexkar598 — CHANGES_REQUESTED** [review]
aeneasrinil is missing

**Comment by Ktlwjec1** [comment]
> aeneasrinil is missing

It's not, what?

**Comment by alexkar598** [comment]
Nvm im a fart, it didnt show up in icondiffbutt because it wasnt changed

**Pull request merged**
