### PR TITLE
Animated Locker Doors

### PR DESCRIPTION
**Pull request by monster860**
### Intent of your Pull Request

This PR animates locker doors. They still open and close instantly, as in the items are transferred in and out of the locker instantly, but there is an animation that occurs on opening and closing. This affects most kinds of lockers, but not crates.

https://cdn.discordapp.com/attachments/134720091576205312/755151212759875706/2020-09-14_15-39-58.mp4

#### Changelog

:cl: monster860
add: Makes locker doors animated
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Not bad.

**Review by Partheo — CHANGES_REQUESTED** [review]
What's closet.png for?

Also, can you explain what is now necessary when it comes to spriting for lockers?

**Comment by monster860** [comment]
The only additional requirement for spriters is the addition of a sprite for the *back* of the door.

**Comment by Fillywonk** [comment]
It looks a bit too slow. Maybe it's just stubbornness speaking, but I like the snappy open/close states better

**Comment by Hopekz** [comment]
The future is now

**Comment by Darkstick** [comment]
I'd like to see how the locker's animation look with items/people inside before forming an opinion

**Comment by Bibby0110** [comment]
This is so incredibly cursed

**Comment by Partheo** [comment]
Agreed with @Darkstick, I want to see what it looks like with items/bodies inside too.

**Comment by monster860** [comment]
https://cdn.discordapp.com/attachments/134720091576205312/755854707343360050/2020-09-16_14-15-40.mp4

**Review by Partheo — APPROVED** [review]

**Comment by ArcaneMusic** [comment]
This looks very, very clean.

**Review by JamieD1 — APPROVED** [review]
Wish you fixed the medical door bug..

**Comment by Partheo** [comment]
> 
> 
> Wish you fixed the medical door bug..

Yeah @monster860 if you could fix this, it would be appreciated: https://github.com/yogstation13/Yogstation/issues/9168

**Comment by MNarath1** [comment]
@monster860 something i noticed while working on a port for this is that you did not deactivate the animation on secure personal cabinet lockers under code/game/objects/structures/crates_lockers/closets/secure/personal.dm so those are still animated but have 2 doors so it looks weird you deactivated animation for the cabinet locker in bar (that one has the same sprite) so i guess you just overlooked that one

**Pull request merged**
