### PR TITLE
mech pilot suits make you better at piloting

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

cargo ordered pilot suits no longer cosmetic

pilots will now move 20% faster and shoot 20% faster in mechs when wearing mech pilot suits

# Changelog

:cl:  
tweak: cargo-ordered mech pilot suits now make you better at piloting mechs
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Dangerously powerful, I'm excited to see mechs that move faster and dedicated pilots

**Comment by ReddicusDragon** [comment]
THIS IS AN ABSOLUTE W, CRANK IT SHINJI

**Comment by cuackles** [comment]
> THIS IS AN ABSOLUTE W, CRANK IT SHINJI

image

**Review by JamieD1 — APPROVED** [review]
Sounds like fun.

**Pull request merged**
