### PR TITLE
Trash update ( no more invisible squished cans ) and sprite update to 4 drinks (working this time)

### PR DESCRIPTION
**Pull request by cuackles**
# Document the changes in your pull request
Updates coffee cup and tea mug sprites
Adds trash icons to all the cans that had it missing
Redesigns Grey bull to look more like the energy drink its based of, and reduces the sprite size of monkey energy so its the same size as the other energy drink ( sorry to whoever made the original sprite it was really good but i had to downsize the drink so it got a bit butchered )
(but this time without conflicts)
# Spriting
image
(ignore the coffee it was updated again, picture lower down)
image
image

# Wiki Documentation

Update monkey energy, coffee, tea and grey bull icons on corresponding pages
image
image
image
image

# Changelog

:cl:  @ToasterBiome for tea and coffee @cuackles everything else 
imageadd: added missing squashed cans, updates energy drinks and tea and coffe
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
you forgot to credit yourself

**Comment by cuackles** [comment]
> you forgot to credit yourself

no i didnt how dare you assume that i would ever make a mistake

**Review by Ebin-Halcyon — APPROVED** [review]
Definite improvement.

**Comment by MajManatee** [comment]
sweedish redbull?

**Comment by cuackles** [comment]
> sweedish redbull?

Sweedbull??

**Pull request merged**
