### PR TITLE
Ports many mood event related shit from TG

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Amogus

https://github.com/tgstation/tgstation/pull/47254
https://github.com/tgstation/tgstation/pull/46296
https://github.com/tgstation/tgstation/pull/49553
https://github.com/tgstation/tgstation/pull/50192
https://github.com/tgstation/tgstation/pull/49918

# Sprites

image
image

# Changelog

:cl: RaveRadbury, ghost, wesoda25, tralezab, nemvar. Ported to YogStation by SuperSlayer
rscadd: The science department now gets a mood bonus for petting borgs.
rscadd: Mutually exclusive Clown and Mime Fan perks
rscadd: Clown and Mime pins
imageadd: Clown pin and Mime pin
rscadd: Adds a couple new mood events for being held up and put in an electric chair/guillotine.
rscadd: The Psychology Office now has a small positive moodlet, and some ambience
spellcheck: Renamed "My mental status" to "My current sanity" in the mood printout.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Oh fuck

**Comment by KillerOrcaCora** [comment]
Same thing, follow our templates and limit yourself to 1-2 sprites pr port though the pins being exclusive would’ve been alright.

**Review by nesisknesis — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
Fix conflicts then it can be merged

**Comment by ghost** [comment]
Ok

**Pull request closed without merging**
