### PR TITLE
Adds "Transitum" x-ray laser mech weapon

### PR DESCRIPTION
**Pull request by ynot01**
#### Changelog
```
/datum/techweb_node/mech_xray
	id = "mech_xray"
	display_name = "Exosuit Weapon (CH-XC \"Transitum\" X-Ray Laser)"
	description = "An advanced piece of mech weaponry"
	prereq_ids = list("adv_beam_weapons")
	design_ids = list("mech_xray")
	research_costs = list(TECHWEB_POINT_TYPE_GENERIC = 2500)
	export_price = 5000
```
```
/datum/design/mech_xray
	name = "Exosuit Weapon (CH-XC \"Transitum\" X-Ray Laser)"
	desc = "Allows for the construction of the CH-XC X-Ray Laser."
	id = "mech_xray"
	build_type = MECHFAB
	build_path = /obj/item/mecha_parts/mecha_equipment/weapon/energy/laser/xray
	materials = list(MAT_METAL=10000,MAT_GOLD = 6000,MAT_URANIUM = 5000,MAT_TITANIUM = 3000,MAT_BLUESPACE = 3000)
	construction_time = 100
	category = list("Exosuit Equipment")
```
```
/obj/item/mecha_parts/mecha_equipment/weapon/energy/laser/xray
	equip_cooldown = 10
	name = "\improper CH-XC \"Transitum\" x-ray laser"
	desc = "A weapon for combat exosuits. Shoots concentrated X-ray blasts."
	icon_state = "mecha_xray"
	energy_drain = 60
	projectile = /obj/item/projectile/beam/xray
	fire_sound = 'sound/weapons/laser3.ogg'
```
`MAT_METAL=10000,MAT_GOLD = 6000,MAT_URANIUM = 5000,MAT_TITANIUM = 3000,MAT_BLUESPACE = 3000`
`research_costs = list(TECHWEB_POINT_TYPE_GENERIC = 2500)`
`prereq_ids = list("adv_beam_weapons")`

:cl:  
rscadd: Added "Transitum" x-ray laser
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
so long as it has the same cooldown as the basic mech laser gun but more energy drain

**Comment by ynot01** [comment]
> so long as it has the same cooldown as the basic mech laser gun but more energy drain

~~has cooldown of heavy laser~~
now has slightly longer cooldown than laser/disabler, much less cooldown than heavy laser

**Comment by Marmio64** [comment]
> > so long as it has the same cooldown as the basic mech laser gun but more energy drain
> 
> ~has cooldown of heavy laser~
> now has slightly longer cooldown than laser/disabler, much less cooldown than heavy laser

normal laser is 0.8 seconds and cannon is 1.5 seconds IIRC, i think a good inbetween would be 1 second with double the e-ecost of the standard laser.

**Comment by ynot01** [comment]
> > > so long as it has the same cooldown as the basic mech laser gun but more energy drain
> > 
> > 
> > ~has cooldown of heavy laser~
> > now has slightly longer cooldown than laser/disabler, much less cooldown than heavy laser
> 
> normal laser is 0.8 seconds and cannon is 1.5 seconds IIRC, i think a good inbetween would be 1 second with double the e-ecost of the standard laser.

good news because i already made the exact changes you listed

**Review by JamieD1 — APPROVED** [review]

**Comment by alexkar598** [comment]
I am kinda worried about phazon/xray lol spam with this...

**Review by alexkar598 — APPROVED** [review]

**Comment by alexkar598** [comment]
I didnt want to merge this right now but whatever

**Pull request merged**
