### PR TITLE
Removes shadowling and darkspawn

### PR DESCRIPTION
**Pull request by JamieD1**
https://forums.yogstation.net/threads/shadowling-darkspawn-rework-feedback.25356/

Shadowling and Darkspawn are just utter shit game modes, please feedback on mqiibs forum post

Discuss.

:cl:  
rscadd: New Gamemode for Darkspawn & Shadowling  
rscdel: Darkspawn & Shadowling
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Wow jamie thanks for throwing this rework together so quick

**Comment by ynot01** [comment]
Reworking them from existing to not existing

**Comment by JamieD1** [comment]
You fucking blind? Look at the forum post, I want traction on it.

**Comment by Sniblet** [comment]
why does this non-draft pr claim to do something it's not going to do

**Comment by Moltijoe** [comment]
This definitively needs to happen, every darkspawn/shadowling round i've been a part of has been a shit show.
HOWEVER, with both malf ai and these being removed, we are in desperate need of more antag variety.
The replacement should be high priority

> why does this non-draft pr claim to do something it's not going to do

It removes the probability of the modes spawning

**Comment by Marmio64** [comment]
sling vs darkspawn battle royale gameplay. Two groups of 3 walk in, only one gets to transcend. Let the veil vs sling and thrall vs darkspawn commence, get ready to rrrrrrumble!

**Comment by Hopekz** [comment]
> You fucking blind? Look at the forum post, I want traction on it.

You're using the wrong tools for what you're trying to do.
You have stuff life quickfire/server votes or other avenues of feedback.
Even that forum thread that you posted in the description is a place to collect people's opinions.

There is no reason for this PR to exist here on github unless you actually want to remove those modes from the game.
This isn't a youtube thumbnail you aren't supposed to "clickbait" us over to this PR to gain traction/views on that forum thread.

**Comment by Moja10** [comment]
Ided PR, posted after Jamie had a shitshow HoS round where the slings managed to convert the HoS on their side, which by the way, I fine one of the coolest aspects of slings, the ability to convert back implanted people in a way that other gamemodes can't really (because ain't no other antags got time or tools to do that easily and efficiently as slings).  

I think there's a lot about these modes that work and I do agree to encourage discussion about them but if anything it should be around reworks only, not removal, which I agree this PR is a bait and switch to think it's geared around removal, not rework.

**Comment by JamieD1** [comment]
> Ided PR, posted after Jamie had a shitshow HoS round where the slings managed to convert the HoS on their side, which by the way, I fine one of the coolest aspects of slings, the ability to convert back implanted people in a way that other gamemodes can't really (because ain't no other antags got time or tools to do that easily and efficiently as slings).
> 
> I think there's a lot about these modes that work and I do agree to encourage discussion about them but if anything it should be around reworks only, not removal, which I agree this PR is a bait and switch to think it's geared around removal, not rework.

Completely true. They suck. Rework looks cool, people should look at it.

**Comment by Moltijoe** [comment]
> Completely true. They suck. Rework looks cool, people should look at it.

it is cool, not to mention combining them into a single antag is a significant quality of life to those playing as or against them

**Comment by ThatLing** [comment]
I feel like darkspawn and sling would work a lot better in dynamic, where they aren't the only antags and so some attention can be taken off of them. Currently, as soon as a sighting is confirmed, the entire station starts producing lights (e.g. spam printing flashlights, glowing fruit from botany, glowy, etc) and the darkspawn/slings are basically fucked.

Another thing that would help is porting proper ligher eater component, so they can reliably break all lights instead of the stupid code we have now that is duplicated across both antags and that only breaks a few light sources.

**Comment by patpol4** [comment]
Alternative has popped up:
 https://github.com/yogstation13/Yogstation/pull/17782

**Comment by JamieD1** [comment]
> Alternative has popped up: #17782

No this the other is a stopgap. its not an alternative at all, dont be dumb.

**Comment by Cartlord** [comment]
Why did you make a Github pull request that does nothing but redirect to a forum post, and why have you re-opened it multiple times after people rightly close it?

**Comment by MajManatee** [comment]
just close the damn pr jamie its got no reason to be open smh

**Comment by Hopekz** [comment]
> just close the damn pr jamie its got no reason to be open smh

Aren't you a maintainer?
Just close it yourself 🙂

**Comment by Burger1998** [comment]
this is still open?

**Comment by Hopekz** [comment]
> this is still open?

All his maintainers are too scared to close it

**Pull request closed without merging**
