### PR TITLE
Hermes Boots

### PR DESCRIPTION
**Pull request by Moltijoe**
Adds another nullrod option for pacifist chaplains
Shoes that have a -0.3 slowdown and have a fancy trail

image

https://user-images.githubusercontent.com/108117184/226040360-7f5b0469-bbc3-434e-a736-0e8b9574ac03.mp4

also added checks to allow non-shoe items to be put in the shoe slot without causing runtimes

thanks to cuackles for the boot sprites

:cl:  @cuackles @Moltijoe 
rscadd: Chaplain Boot nullrod
/:cl:

### CODE REVIEW

**Comment by solwashere** [comment]
Terraspark boots when

**Comment by Moltijoe** [comment]
> Terraspark boots when

cuackles didn't think either the terraspark or hermes boots looked quite right

**Comment by Maia-J** [comment]
Holyshit now we will have an actual fast support class

**Comment by ChuChu42** [comment]
nice, make it faster

**Comment by stwordcitizen** [comment]
make it make the terraria hermes boots running sound while moving

**Comment by Moltijoe** [comment]
> make it make the terraria hermes boots running sound while moving

give me the sound file and sure

**Comment by Hislyna** [comment]
Very based

**Review by ToasterBiome — APPROVED** [review]
art approval

**Comment by namjay1170** [comment]
could it also have a positive moodlet?

**Comment by Moltijoe** [comment]
> could it also have a positive moodlet?

why?

**Comment by namjay1170** [comment]
> > could it also have a positive moodlet?
> 
> why?

further rewarding not having a sword and cutting peoples heads off

**Pull request merged**
