### PR TITLE
oppressing the poor

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Reasons:

- Money

- Not needed

#### Changelog

:cl:  
rscdel: Removed **old** things  
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
mentors oppressed

**Comment by deathslayer2481** [comment]
U wot

**Comment by Mqiib** [comment]
[
image
](url)

**Comment by Jarod1200** [comment]
CEASE AND D E S I S T

**Comment by SomeguyManperson** [comment]
-4 appeal denied you can try again in a month

**Pull request closed without merging**
