### PR TITLE
Syndicate Softsuit 2: Tex Boogaloo (Design port from Tau Ceti)

### PR DESCRIPTION
**Pull request by War-Tex**
hey hey people, tex here. I hope this works so uh yeah

resprites the syndicate softsuits
syndicategobrrr
e1m1

#### Changelog

:cl:
tweak: resprited all the syndicate eva suits to look fresh
/:cl:

### CODE REVIEW

**Review by nesisknesis — COMMENTED** [review]
clarify that its a port in the title and changelog

add a changelog

**Review by nesisknesis — CHANGES_REQUESTED** [review]
weird fuckity with the dme

**Comment by War-Tex** [comment]
> weird fuckity with the dme

fuckity hopefully fixed, just copied the latest version of it. If this doesn't work I got no clue, it's going through checks now

**Comment by nesisknesis** [comment]
its not fixed

**Comment by War-Tex** [comment]
yeah got no clue then

**Comment by JamieD1** [comment]
If this gets merged it fixes the dme problem

**Review by JamieD1 — APPROVED** [review]

**Comment by War-Tex** [comment]
sweet

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
