### PR TITLE
Fixed a harmless bug where CMO mains would never roll antag

### PR DESCRIPTION
**Pull request by ynot01**

### CODE REVIEW

**Review by ThatLing — APPROVED** [review]

**Comment by Maia-J** [comment]
This should've been silently left there CMO's dont deserve antag anyhow

**Comment by Aquizit** [comment]
This explains a lot, actually.

**Comment by RG4ORDR** [comment]
I thought heads all got excluded from antag.

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
> I thought heads all got excluded from antag.

Read the PR

**Pull request merged**
