### PR TITLE
gunkits 2: return of the gunkits

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
same thing as last time
instead of printing guns for free you now have to sacrifice a gun for the direct upgrade science guns, examining the kit will tell you which, and when you smack the gunkit with the required gun and wait a few seconds you'll get the gun.

image
sprite 4 the kits (except the green)

this is mainly to tone down the immense powercreep security gets throughout the round, becoming very quickly capable of sharting out infinite riot shields and direct upgrade guns (bad) and with the armory slightly less trivial to break into, this is possibly a good idea

# Changelog

:cl:  
rscadd: replaced directly printing guns with printing gunkits
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
same as last time, sounds terrible.

**Comment by KillerOrcaCora** [comment]
This PR makes 0 sense I truly question how this idea came to be

**Comment by Moltijoe** [comment]
I like the idea, but ONLY if we also juice up the armory, so there are more base guns that can be upgraded in there.
It both feels more like gear upgrades rather than replacements, and it makes armory a nicer target to attack.

**Comment by 00ze-cyclone** [comment]
I hate guns being straight upgrades to other and this is just making sure we'll never remove that trend.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> I like the idea, but ONLY if we also juice up the armory, so there are more base guns that can be upgraded in there. It both feels more like gear upgrades rather than replacements, and it makes armory a nicer target to attack.

if you can't make it without the 14 guns in the armory roundstart and cargo i dont know what to tell you

**Comment by Moltijoe** [comment]
> if you can't make it without the 14 guns in the armory roundstart and cargo i dont know what to tell you

If armoury has 14 guns. Why is it always empty during nukie rounds, even if i get there immediately after being the first to get AA?

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> If armoury has 14 guns. Why is it always empty during nukie rounds, even if i get there immediately after being the first to get AA?

main character syndrome causes 1 person to take the whole armory

**Comment by Moltijoe** [comment]
> main character syndrome causes 1 person to take the whole armory

Sounds like an admin issue MR ADMIN.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> Sounds like an admin issue MR ADMIN.

how is it an admin issue

**Review by cuackles — APPROVED** [review]
sprite aproved

**Comment by Yogbot-13** [comment]
#### Test Merge Deployed

##### Server Instance
main

##### Merged By
Alexkar598

##### Revision
Origin: c2e07f090b9608064208668a656da6a54247ae86
Pull Request: 861c9aa58909989c389f8314b029b7a89247afec
Server: e944462d50085599eae1b418e8d9c62b74e26fd1
[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Removed

**Comment by MajManatee** [comment]
Over a month, pretty negatively viewed.

**Comment by isotope436** [comment]
the standing from sec on this is yuck get it out of here and apperently so is a majority of other people so i now ask why has ynot test merged it >:(

**Comment by MajManatee** [comment]
I mean there isn't a single positive vote on this, I don't know why its being considered

**Comment by N3D6** [comment]
> I mean there isn't a single positive vote on this, I don't know why its being considered

cuz devs don't care about the opinions of the playerbase

this sucks lmao

**Comment by RG4ORDR** [comment]
I havent seen any advanced weapons made at all since this.
Not once, people will research it. Print the gun kit, and then just ignore and instead go to cargo to use a laser gun. Sec been mostly using the funny swords recently too.

Only thing I suggested that even improves or makes this viable is let the sec lathe print laser guns and disablers.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> this sucks lmao

Just like your mom. Good and hard. Through my jorts.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> I havent seen any advanced weapons made at all since this. Not once, people will research it. Print the gun kit, and then just ignore and instead go to cargo to use a laser gun. Sec been mostly using the funny swords recently too.

ok, so what you're saying is the direct upgrade guns are rarer now? what's the issue here?

**Comment by 00ze-cyclone** [comment]
> > I havent seen any advanced weapons made at all since this. Not once, people will research it. Print the gun kit, and then just ignore and instead go to cargo to use a laser gun. Sec been mostly using the funny swords recently too.
> 
> ok, so what you're saying is the direct upgrade guns are rarer now? what's the issue here?

Except those guns are no longer direct upgrades:
-xray gun is now doing way less direct damage in exchange for the rads and wall pass
-aegun now get recharged on the field with uranium which irradiate you, making you have to carefully manage it or decide that your life is worth the dead of the guy in front of you
-tesla revolver remain the ultra meme
-ion carbine is now weaker than the ion rifle or the HoS gun, doing only a 1 tile EMP
-the hardlight bow has a fire rate of one bolt per millenia and can’t pass glass in exchange for the unlimited ammo
-decloner remain laser gun that never heal but with less ammo capacity and unable to pass glass
-bouncer egun is a disabler with both less ammo capacity and less damage per shot
-temp gun ate a nerf when we reduced the slowdown of being cold

R&D guns are no longer **direct** upgrades, they are sidegrades which are indeed slightly better overall (except tesla revolver but it’s funny so ultimately it’s the best) but they aren’t laser gun+ that make the laser gun irrelevant anymore. The gun kits are also redundant with the firing pin system now that we can’t print firing pins anymore.

**Comment by burn1cycle** [comment]
I had this idea to limit the amount of guns security can make. There could be this thing that goes inside the gun and without them the guns won't work. It won't be a complete nerf because the Warden's office can have a box of them and also we could possibly order more through cargo, I think it's better than gun kits. I had to smoke a lot of weed to come up with this brilliant idea and that cost some money so I'm wondering if I can get donator for a few months?

**Comment by Hopekz** [comment]
> I had this idea to limit the amount of guns security can make. There could be this thing that goes inside the gun and without them the guns won't work. 

This is already in the game they're called triggers

**Comment by burn1cycle** [comment]
> This is already in the game they're called triggers

NO NO, I thought of it first and I'm calling them "Firing Pins".

**Pull request closed without merging**
