### PR TITLE
Lowers the requirements for the DNA Vault

### PR DESCRIPTION
**Pull request by ghost**
### Intent of your Pull Request

The DNA vault is suppose to be a goal that can be accomplished with proper teamwork, but the requirements to simply use it is insane.

75% to max of the population is required, which is simply too much considering how spread out is everyone. So I lowered it down to 25-50%.

The near 70% of POSSIBLE plants in the game is completely stupid. so I lowed it to 20-30%.

#### Changelog

:cl:  

tweak: Lowered the requirements needed to activate the DNA Vault.  

/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
can yuoremove plant and animal dna requirements

**Comment by ghost** [comment]
No, I'm pushing it already by doing this

**Comment by Hopekz** [comment]
> No, I'm pushing it already by doing this

You know you can commit to your PR and modify it?
Would it make you feel better if we made a "code review" comment instead so it looks like a more official suggestion?

**Comment by ghost** [comment]
I was referring to Oak.

Edit: What I mean is that I don't want council coming down and closing this PR because someone there didn't like what I was doing.

**Pull request merged**
