### PR TITLE
[META] Medbay 3.0

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Redo of medbay again, rolling in standardized decals where applicable, and some changes

- Removes a patient room
- makes the remaining patient room into a proper surgical room with two beds
- converts the dead space from the old patient room into a viewing gallery and side storage area
- restructures treatment so its less cluttered and more central, as a QoL change for doctors
- moves all medbay APCs out of maint where possible
- deletes a rogue APC that caused Med Storage to depower randomly
- fixes a lot of oddly terminated wires to nowhere
- redecorates the CMO office, and changes their screwdriver(???) out for a crew monitor
- removes the awkward windoors and glass from cloning
- total redesign for chemistry, focused on better use of space to prevent it being Huge and Empty at the same time
- adjusts the disposals system for Medbay so that deliveries to it go to Medbay not the Paramedic office
- Genetics Maint door uses the proper access and name now
- changes the break room to be on the storage APC, like Box
- gave runtime her cat toy
- added a crew suit sensors monitor console to the Paramedic office
- removed a second windoor from the plastic flaps to medbay maint's cargo dropoff
- reinforced the CMO office all around, like Box Station
- replaced the virology monkey pen tiles with grass and added foliage. Removed the two roller beds

ss (2022-10-08 at 02 26 45)
ss (2022-10-08 at 02 26 51)

# Changelog

:cl:  
mapping: Meta Medbay overhauled
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
i just want to ask why meta medbay gets its a.p.c.s taken out of maints

**Comment by VaelophisNyx** [comment]
because the plan is for them ALL to be moved out of maint; the rest will just happen later

**Comment by Marmio64** [comment]
> i just want to ask why meta medbay gets its a.p.c.s taken out of maints

because secret plan to nerf darkspawn, nightmares, and shadowlings.

**Comment by VaelophisNyx** [comment]
maint APCs are a relic of ancient times; we've moved past that

**Comment by VaelophisNyx** [comment]
@ToasterBiome review whenever you've got time?

**Review by ToasterBiome — APPROVED** [review]
Looks fine, sleeper/bed is in an odd place, can always be changed if it doesnt work out

**Comment by VaelophisNyx** [comment]
@ToasterBiome cornflakes fixed

**Pull request merged**
