### PR TITLE
NASA Space suit flash protection removal

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request

Removes the flash protection on the old NASA hardsuits, because why the hell can a thin piece of film protect you from flashes?

# Changelog

:cl:  
tweak: Curators no longer get flash protection on their spacesuit
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Can you provide a gameplay reason vs a realism reason?

Instead of "why can a piece of film stop flashes" do "why shouldn't the curator have flash protection from choosing this suit"

Remember this is a game and balance decisions are for gameplay not realism

Also realize that most space suit helmets in the game (if not all)  have flash protection so why should curator's suit specifically not have it?

**Comment by Moltijoe** [comment]
The regular void helmet i could be persuaded for, the _engineering_ helmet though?

**Comment by MajManatee** [comment]
you right, engineering suits make sense

**Comment by Moltijoe** [comment]
> you right, engineering suits make sense

You're going to need to re-add that line and make it
`flash_protect = 2`
Since the engineering helmet is a derivative of the regular one, meaning it would inherit the flash protection loss

**Comment by 00ze-cyclone** [comment]
All space helmets give flash protection, make no sense that one doesn't, just make shit inconsistent for no benefits. You can see from a mile away if the curator got their helmet, it's not like the flash protection was concealed or anything.

**Comment by githubuser4141** [comment]
> Can you provide a gameplay reason vs a realism reason?
> 
> Instead of "why can a piece of film stop flashes" do "why shouldn't the curator have flash protection from choosing this suit"
> 
> Remember this is a game and balance decisions are for gameplay not realism
> 
> Also realize that most space suit helmets in the game (if not all) have flash protection so why should curator's suit specifically not have it?

It's also a 'NASA Centcom' suit, not a '1960s moonsuit' suit, so I dunno how realism comes into play when the suit doesn't even exist IRL. It's just a futuristic space suit that NASA probably ordered in I dunno, the 22nd century? SS13 takes place in 2500, so an ancient suit could still be 100's of years in the future.

**Comment by Hopekz** [comment]
> It's also a 'NASA Centcom' suit, not a '1960s moonsuit' suit, so I dunno how realism comes into play when the suit doesn't even exist IRL. It's just a futuristic space suit that NASA probably ordered in I dunno, the 22nd century? SS13 takes place in 2500, so an ancient suit could still be 100's of years in the future.

It's fine my post was a reworded "this PR is bad and you should feel bad" because I knew he wouldn't be able to answer any of those questions so it was aimed at the person that ultimately decides to close this PR to see.

His argument was literally "why the hell can a thin piece of film protect you from flashes?" When you can't even see how thick the visor/film is in the game 😂

**Comment by KillerOrcaCora** [comment]
On one hand, annoying inconsistency. On the other, Gama clown levels of PR documentation.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
