### PR TITLE
Vaccines require at least 5u to work

### PR DESCRIPTION
**Pull request by Moltijoe**
Spamming 0.1u vaccine pills to counter viruses is too easy for how impactful some viruses should be
i've made it require at least 1u worth of vaccine to take effect
this doesn't make it harder to cure the disease, just harder to vaccinate the entire station

:cl:  
tweak: Vaccines require at least 5u to work
/:cl:

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
nobody will make vaccines now, closing in 24 hours as this is not conducive to how the game should be played

**Comment by solwashere** [comment]
Going to be real virus's are barely impactful enough as it is, all this does is make it more annoying to deal with because virus code is already shit

**Comment by 00ze-cyclone** [comment]
> nobody will make vaccines now, closing in 24 hours as this is not conducive to how the game should be played

are you serious? that still mean you can print batches of 15 instant curing pills, that's far from useless, also stop using that closing in 24h hours tag for PRs you don't like.

**Comment by MajManatee** [comment]
> nobody will make vaccines now, closing in 24 hours as this is not conducive to how the game should be played

are you high?

If anything id like to see it even higher.

**Comment by ynot01** [comment]
Effectively a non-nerf because each bottle prints 15 units so it will be 15 pills (a lot) and bottles can be printed every 20 seconds

Something more impactful would be 5u requirement or perhaps a different, more complex intake method, like syringe injection

Regardless something is better than nothing

**Comment by ReddicusDragon** [comment]
> > nobody will make vaccines now, closing in 24 hours as this is not conducive to how the game should be played
> 
> are you high?
> 
> If anything id like to see it even higher.

thats the trick im always high 😎

**Comment by Moltijoe** [comment]
5u it is

**Comment by solwashere** [comment]
I want you to sit at a virology machine for 10 minutes waiting to make a few vaccine bottles and tell me that this is a "good change"
Medbay already has enough waiting around and doing nothing and you want to make more of it?

**Comment by ynot01** [comment]
> I want you to sit at a virology machine for 10 minutes waiting to make a few vaccine bottles and tell me that this is a "good change" Medbay already has enough waiting around and doing nothing and you want to make more of it?

TBF this is the absolute height of virology gameplay

**Comment by solwashere** [comment]
You know it's telling when most of the people who have thumbsed up it have never played virology for more than 5 hours
Actually horrible change that just makes it so you have to sit around more and do nothing while waiting for a vaccine to cook because it takes an unreasonable amount of time

**Comment by Moja10** [comment]
I'm no expert on virology, if the time to "cook a virus" is too high, then it could be changed as well, but I am in agreement with this PR that .1u or even 1u pills being made in one batch with enough to cure the station, or two batches for higher pops, is a huge component on why viruses are basically a non-threat unless they light you on fire or make you poop out your organs or make you pass out. it's boring to have viruses either be nothing burgers or deadly to kill 9 people in 2 minutes

**Comment by Moltijoe** [comment]
i still would have preferred #18073 but bibby wouldn't take it

**Comment by MajManatee** [comment]
Virologists when they have to do their job for more than the first 0.0000001 seconds of the round

**Comment by MajManatee** [comment]
> i still would have preferred #18073 but bibby wouldn't take it

My brother in christ he merged that one

nvm im retarded

**Comment by Moltijoe** [comment]
> My brother in christ he merged that one

into mAster not master

**Review by MajManatee — APPROVED** [review]
should work yeah

**Comment by TheBombMakerJL** [comment]
this is dumb if you don't also increase the amount of vaccine you get per bottle, it's currently 20u per vaccine bottle so you're decreasing the amount of people you can vaccinate from one bottle from like 200, to 4 which is a 98% reduction

edit : 20 or 15 I forget, if 15 it would be 98.5%

**Comment by TheBombMakerJL** [comment]
> this is dumb if you don't also increase the amount of vaccine you get per bottle, it's currently 20u per vaccine bottle so you're decreasing the amount of people you can vaccinate from one bottle from like 200, to 4 which is a 98% reduction

this also increases the amount of time needed to vaccinate the crew against a virus to an unfathomably degree, esp on high pop to the point where it's probably not even worth going for vaccines when you can just spam the virus cure through chemistry and make like 600u cure in the course of like two minutes

**Comment by Moltijoe** [comment]
> this also increases the amount of time needed to vaccinate the crew against a virus to an unfathomably degree, esp on high pop to the point where it's probably not even worth going for vaccines when you can just spam the virus cure through chemistry and make like 600u cure in the course of like two minutes

i tried a more interesting PR, but bibby wasn't having it

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
