### PR TITLE
Megafauna eat slimes

### PR DESCRIPTION
**Pull request by Amelia0010**
Megafauna eat slimes.

:cl:
tweak: Megafauna eat slimes.
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
It would be better if there neutral

**Comment by Codeatmos** [comment]
Ok fuck no, megafauna would literally follow a trail of slimes to the mining base, or somewhere close, as well as eating all of the fucking slimes, I know xenobio should be stomped into a red mush and washed down a drain but godamn, fighting megafauna so you don't lose your ungi slime?

**Comment by SomeguyManperson** [comment]
This just makes it so megafauna dont die to slimes, they already fight them but hierophant psysically can't harm slimes with its attacks

**Comment by LoliconSlayer** [comment]
Gotta pray that mining gets to those slimes before they die xenobio mains

**Comment by Hopekz** [comment]
To everyone that doesn't support this for some reason its literally a quick bugfix to slimes literally killing megafauna on their own.

If a more elegant solution gets created later on so be it but we need to stop this from happening for now. At least this kind of makes sense-ish

**Comment by Amelia0010** [comment]
`Ok fuck no, megafauna would literally follow a trail of slimes to the mining base, or somewhere close,`

Slimes don't spawn in a trail to the mining base.

**Pull request merged**
