### PR TITLE
Removes Big Tiddy Sec GFs

### PR DESCRIPTION
**Pull request by Mqiib**
Tweaks the sec jumpskirt sprite to be in-line with standard clothing. They stuck out under armor and looked really awful at times. Shame on you, whoever sprited this originally.

Old:
image

New:
image

# Changelog

:cl:  

imagedel: Spess(wo)men wearing the security jumpskirt no longer have artificially-expanded tracts of land.

/:cl:

### CODE REVIEW

**Comment by Tipy1802** [comment]
Who asked for this?

**Comment by Mqiib** [comment]
> Who asked for this?

Literally nobody, but it's a change that should be made anyways because it sticks out over certain sec armors and looks godawful.

**Comment by Tipy1802** [comment]
> > Who asked for this?
> 
> Literally nobody, but it's a change that should be made anyways because it sticks out over certain sec armors and looks godawful.

I have used it multiple times and never noticed it or had an issue of it. You should probably add sec boob armoured vests to make them more in-line

**Review by SomeguyManperson — APPROVED** [review]
Horny removal

**Comment by Moja10** [comment]
Good, big heaving busty boingy bozonkers were really distracting me away from roleplaying. This PR improves RP

**Comment by Georgeur** [comment]
I honestly thought all women sprites are flat chested unless not wearing a uniform, I've never noticed this. But thanks anyway. 
Now I'm going to play citadel and coom to all 3 of those voluptuous pixels as my head is beaten in by a mentally retarded man child duel wielding collapsible chairs and quoting hulk hogan. uwu

**Comment by JamieD1** [comment]
This is stupid, but fine.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
