### PR TITLE
Refactors extended shock touch to actually just be a longer range shock touch

### PR DESCRIPTION
**Pull request by Moltijoe**
# Why is this good for the game?
Code quality

# Testing
image

:cl:  
bugfix: Fixes extended shock touch not having a cooldown or sound effect
/:cl:

### CODE REVIEW

**Review by MajManatee — APPROVED** [review]
Might allow you to remotely defib someone like the normal touch does.

**Comment by Moltijoe** [comment]
> Might allow you to remotely defib someone like the normal touch does.

any ranged shock works that way, that's how extended shock touch works

**Comment by MajManatee** [comment]
well its just kind of how ALL shocks work, but I meant how the normal one had a do after (I think) for it.

**Comment by Moltijoe** [comment]
> well its just kind of how ALL shocks work, but I meant how the normal one had a do after (I think) for it.

no, you're thinking about using the hand for revival surgery, which is far more reliable, the regular one doesn't otherwise have a do_after

**Pull request merged**
