### PR TITLE
Let Snellie play the game again

### LINKED ISSUE #16497: Issues regarding shuttle-movement flinging
### Severity

Round Breaking

### Short Description

Arrivals shuttle clothes causing lag.

### Reproduction

1. Late-join Round 
2. Clothes on Arrivals shuttle fly backwards from shuttle movement
3. Shuttle lands
4. Clothes fly forward
5. Disconnect
6. Shuttle leaves, due to no 'alive' player on.
7. Clothes fly backwards
8. Issue repeats until dragged off of shuttle.

### Round ID

Round #43830

### Test Merges

#16497

### BYOND Username

Snellie

### Additional information

This was only an issue for me currently; but I only make this in a worry that someone else might end up suffering the same issue as I did; as late-joining a round only to be stuck in a disconnecting/reconnecting loop can be annoying.

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Arrivals shuttle now has slower engines so they don't throw everything back and lag connection-challenged people out
Closes https://github.com/yogstation13/Yogstation/issues/16497
# Changelog

:cl:  
tweak: Arrivals shuttle now has slower engines so they don't throw everything back and lag connection-challenged people out
/:cl:

### CODE REVIEW

**Comment by Maia-J** [comment]
Snellie? Is this you?

**Comment by Simplehorror** [comment]
> Snellie? Is this you?

No, this is Patrick

**Comment by Snellie12** [comment]
Already gonna just downvote this.

**Comment by Simplehorror** [comment]
it's a shame because this is really funny

**Review by ReddicusDragon — CHANGES_REQUESTED** [review]
Fixes #16497, please update this to be indicative of this fact.

**Comment by Simplehorror** [comment]
Closes #16497

**Comment by Maia-J** [comment]
> Fixes #16497, please update this to be indicative of this fact.

The first person to actually want this on PRs? Impossible. I thought people who put Issues on their PRs were extinct

**Comment by ReddicusDragon** [comment]
> > Fixes #16497, please update this to be indicative of this fact.
> 
> The first person to actually want this on PRs? Impossible. I thought people who put Issues on their PRs were extinct

i live

**Comment by MajManatee** [comment]
This likely wont matter, given how it looks as if the entire throw force thing is being reverted.

**Comment by Simplehorror** [comment]
> This likely wont matter, given how it looks as if the entire throw force thing is being reverted.

Fun fact: Opening a PR doesn't mean it is getting merged; I am living proof

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
