### PR TITLE
Removes gang from mode rotation. It can still be admin forceed

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

Gangs are a widely hated mode, they're a nightmare to admin on, and they almost always drag out for way too long with no sides doing anything. The mode itself is a mess, it's hard to learn, and it's much too murderboney. People have tried to fix this mode multiple times, but it's awful and that is shown everytime the mode is chosen.
# Spriting

# Wiki Documentation

Add gang to the list of disabled modes
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscdel: removes gangs from rotation
tweak: removes gangs from rotation
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
How will I shoot everyone who looks at me weird with an uzi now?

**Comment by N3D6** [comment]
This isn’t an ided because I’m a logical human being who cryos every time gangs is picked

**Comment by Darkstick** [comment]
just don't go to medbay as civilian, gamemode will improve drastically, trust me

**Comment by Bibby0110** [comment]
I love gangs

**Comment by Bibby0110** [comment]
jk, gangs is bad

**Review by JamieD1 — APPROVED** [review]

**Comment by N3D6** [comment]
HOLY BASED

**Pull request merged**
