### PR TITLE
CentCom Test Chamber v2

### PR DESCRIPTION
**Pull request by Lynameep**
### Intent of your Pull Request

An Alternative to my previous test chamber #5383 pr.

It's not only much bigger but it's completely isolated from the rest of centcom and can easily be disabled by removing the portal from centcom during the game at any point.

Things that were added;
 - Megafauna 
 - Toxins Testing
 - All of the available gasses
 - A lot more explosives
 - A generally more nicer look

#### Changelog

:cl:  
rscadd: Added the Centcom Test Chamber which is accessible by a portal after arriving at centcom.
/:cl:

### CODE REVIEW

**Comment by Ktlwjec** [comment]
changelog different please, but beautiful work from my quick glance 😎

**Comment by boodaliboo** [comment]
you do coding for me for syndicate pod

**Comment by Altoids1** [comment]
The megafauna in the test chamber seem to be tampering with the normal megafauna's ability to spawn, so that has to be fixed.

Also, there's a stray exit portal in the test chamber that needs to be deleted.

**Review by Altoids1 — CHANGES_REQUESTED** [review]
The megafauna in the test chamber seem to be tampering with the normal megafauna's ability to spawn, so that has to be fixed.

Also, there's a stray exit portal in the test chamber that needs to be deleted.

**Pull request merged**
