### PR TITLE
Disables Boxstation

### PR DESCRIPTION
**Pull request by LoliconSlayer**
What do you think this PR does

# Wiki Documentation

Move boxstation to out of rotation on the wiki

# Changelog

:cl:  
mapping: No more box.
/:cl:

### CODE REVIEW

**Comment by iloveloopers** [comment]
ok but how does this improve the game

**Comment by LoliconSlayer** [comment]
> ok but how does this improve the game

By taking box out of rotation

**Comment by Marmio64** [comment]
we should take all maps out of rotation, i just hate people who play them

**Comment by JohnFulpWillard** [comment]
You should give more justification for this if you expect headcoders to weigh their opinion in.

**Review by MajManatee — COMMENTED** [review]
finally a good pr

**Comment by neeshacark** [comment]
unironically i do think this is a good change, box inhibits us.  we lose good mappers because box lovers call their map 'shit' because its not box and they dont know where every epic maint loot is located and cant navigate with their eyes closed.

disabling it for a while would hopefully cause people to get used to other maps so we can finally look into doing cool maps of our own instead of 'its box every round'

**Comment by N3D6** [comment]
We should deadass TM this for a little while

**Comment by solwashere** [comment]
> We should deadass TM this for a little while

on jod

**Review by N3D6 — APPROVED** [review]
The best PR ever made.

**Comment by Hislyna** [comment]
There is a god

**Comment by RG4ORDR** [comment]
Based

**Comment by maxion12345** [comment]
Does this count as an ided

oh man we could totally use that quickfire channel for this

**Comment by Moja10** [comment]
You haven't played in 5 months on Yogs, I don't see why it affects you that box is more heavily played than other maps, other than discord noise. 

If I were to entertain the idea, no, it absolutely should not be removed, doing so is a complete kneejerk reaction to the fact that its played too much. There are many other solutions to alleviate this problem other than outright removal, and those should be preferred to outright removal. For one, the PR that prevents voting on box within certain play thresholds is way better than this.

**Comment by YashinHak** [comment]
It may be wiser to just make a forced map rotation

**Comment by ToasterBiome** [comment]
Not yet

**Pull request closed without merging**
