### PR TITLE
Mob reagent examine with sci goggles

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

Won't tell you exactly what reagents are in the mob, just that there are

# Changelog

:cl:  
rscadd: Added mob reagent examine for science goggles
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
examine drake
93014u of 16 chemicals.

**Comment by Maia-J** [comment]
> examine drake 93014u of 16 chemicals.

Jokes on you bodies have a capacity of 300u

**Comment by Moltijoe** [comment]
> Jokes on you bodies have a capacity of 300u

they most certainly do not, i've seen drake with over 600u of cryoxadone in him prior to the overdose nerf

**Comment by MajManatee** [comment]
ive had 1000u of spider venom in me, and I've seen people with like 5000u of pilk
anyways cool change

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
