### PR TITLE
Disable zombies from dynamic

### PR DESCRIPTION
**Pull request by adamsong**
Disables zombies from dynamic due to them needing reworked

# Changelog

:cl:  
rscdel: Removed zombies from dynamic
/:cl:

### CODE REVIEW

**Review by Xoxeyos — CHANGES_REQUESTED** [review]
Change the cost to 101, and keep the requirements the same, please. Makes it a whole lot easier process once I fix the issue with zombies.

**Comment by adamsong** [comment]
I'd appreciate a review of this

**Review by Xoxeyos — APPROVED** [review]
Thank you! Sorry I didn't get to the review sooner, I've been traveling a bunch.

**Comment by adamsong** [comment]
Can someone review this so it merges? Unfortunately @Xoxeyos your review doesn't count

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
