### PR TITLE
Add AI Upload To Research Access

### PR DESCRIPTION
**Pull request by Hislyna**
### Intent of your Pull Request

Adding AI Upload/Chamber onto the Research Access category, giving the Research Door Remote access to said areas and allowing the RD to give access if needed (such as malf ai or bad law change)

#### Changelog

:cl:  
rscadd: Adds AI Chambers to Research Access  
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
eh

**Comment by Hislyna** [comment]
A quality of life for the RD considering they have the access, wouldn't it make sense that they can also unlock/lock the doors and give out the access in emergencies?

**Review by alexkar598 — DISMISSED** [review]
Upload is fine, leave teleporter alone

**Comment by Hislyna** [comment]
Okay, changed to your request~

**Comment by Hislyna** [comment]
Ill be honest, no clue why it failed this time, its the exact same with one word removed

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
