### PR TITLE
Makes footwraps craftable

### PR DESCRIPTION
**Pull request by nmajask**
# Github documenting your Pull Request

Allows you to craft normal footwraps for two leather, the same amount as leather shoes. I have done very little testing, but it should work.

# Wiki Documentation

You would need to change the construction page to include the recipe. 

# Changelog

:cl:  
tweak: Made footwraps craftable 
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Lizard power creep

**Comment by nmajask** [comment]
> Lizard power creep

Yes

**Comment by nmajask** [comment]
> Lizard power creep

My plan is to make a separate PR to reduce the amount of jobs that give round start footwraps to just engineering and mining.

**Comment by UselessTheremin** [comment]
lizard power crêpe
image

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
