### PR TITLE
Bring back 3D Orange

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
Extradimensional Orange is back
Throwing it will now throw out some normal oranges

also added a new seed sprite for it

# Why is this good for the game?
It was removed for being lame??? it was fine and cool. Also It's funny to make it throw oranges around

# Testing
orange

# Spriting
image

# Wiki Documentation
everything go in guide to plants

# Changelog

:cl:  
rscadd: readded 3D Orange and split it into normal oranges when thrown
imageadd: added new sprite for 3d orange seed

/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Bigger.

**Comment by ToasterBiome** [comment]
Wasn't removed because of the effect it was removed because it was a direct reference to Orange the TG headcoder.

**Comment by ShoziOffical** [comment]
> Wasn't removed because of the effect it was removed because it was a direct reference to Orange the TG headcoder.

ah funny

**Comment by Yarinoi** [comment]
this orange? its ginemenasaurus, or whatever you say
gigantasaurus.
jamenas- uh- bwa- menamoris.
some menaf morphis.
gigandanordisis.

mhm.

jamournus.

**Comment by MajManatee** [comment]
I liked the orange, who cares if its a reference.

**Review by cuackles — APPROVED** [review]

**Comment by ToasterBiome** [comment]
No oranges

**Comment by ShoziOffical** [comment]
> No oranges

this isnt a valid reason!

**Comment by ShoziOffical** [comment]
honestly i dont care about the reference to the tg headcoder, all i care is the orange itself its innocent

**Pull request closed without merging**
