### PR TITLE
Adds Pete's Rollerdome Escape shuttle, eighties retro tiles, and siding decals for spriters who want to make the Station Great Again

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

https://github.com/tgstation/tgstation/pull/54145
https://github.com/tgstation/tgstation/pull/53797
https://github.com/tgstation/tgstation/pull/50057

Adds Pete's Rollerdome Escape shuttle

image

The tiles are those on the shuttle, the funky ones

The siding decals can be seen here:

image
Alternatively you can check sprite diff bot to see the other ones as well

### Why is this good for the game?

It's another escape ship but I like it

#### Changelog

:cl:  
rscadd: Adds Pete's Rollerdome, 90s style rollerdome escape ship
rscadd: Adds siding tiles, hopefully they can be used beyong the rollerdom
rscadd: Adds retro tiles, the carpet you see in the rollerdome
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Add the new sprites for arcades aswell please!

**Comment by Marmio64** [comment]
yes please, i need those tiles

**Comment by patpol4** [comment]
what about rotational arcade sprites :(

**Review by patpol4 — APPROVED** [review]
There are some issues like lack of brig or really tight passage at the bottom but it should be good to go after my technical fixes. I did mostly firelocks and platings

**Comment by alao3alao3** [comment]
what's the updated rollerdome look like

**Pull request merged**
