### PR TITLE
Adds frog hat to donator list and magmu box 2 & adds Novelty Fishing Hat to donator list

### PR DESCRIPTION
**Pull request by VaelophisNyx**
revives https://github.com/yogstation13/Yogstation/pull/15097

# Changelog

:cl:  
rscadd: Added new donor hat to the list, and to the gift vendor
tweak: Donators can now choose a Novelty Fishing Hat as their donator clothing item
imageadd: added new sprite for new donor hat
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
Donor item that gives a real positive bonus is questionable, even if it's just for fishing.

**Comment by VaelophisNyx** [comment]
I agree, but I'd like to hear on that from jamie or biome

**Comment by VaelophisNyx** [comment]
if it does wind up being alright I can toss the fishing hat into the donator list too, though

**Comment by VaelophisNyx** [comment]
orca got the go-ahead from jamie on that; good to know

**Comment by VaelophisNyx** [comment]
ss (2022-08-02 at 08 22 39)

For future reference

**Review by cuackles — APPROVED** [review]
Mmmmm frog 🐸

**Pull request merged**
