### PR TITLE
Fixes a funny potential (by potential I mean literally no one in their right mind would use it) source of DDoSing.

### PR DESCRIPTION
**Pull request by BurgerLUA**
# Document the changes in your pull request

All client topic calls are spam checked to prevent DDoSing or whatever. This one section of code isn't because of an oversight. I don't think a DDoS via this method is feasible unless you get like 20 clients to do it. You'd have to be connected to the server too. 

# Changelog

:cl:  BurgerBB
bugfix: Fixes a funny potential (by potential I mean literally no one in their right mind would use it) DDoS bug.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
You know I completely forgot to test if this breaks anything.

**Comment by Moltijoe** [comment]
just a reminder that you still need to test it and whatnot

**Comment by BurgerLUA** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by BurgerLUA** [comment]
No issues with refreshing tickets.

**Review by ynot01 — APPROVED** [review]

**Pull request merged**
