### PR TITLE
fixes cable coils always having no color

### PR DESCRIPTION
**Pull request by tattax**
also ports : https://github.com/tgstation/tgstation/pull/52614

brown one comes from syncing our cable colors list with tg but it looks cool so why not

RlnmvIdoMg

:cl:  
rscadd: brown cable coil
bugfix: fixes cable cuffs always being white
/:cl:

### CODE REVIEW

**Comment by MajManatee** [comment]
cable coils do have colour

**Comment by tattax** [comment]
cable cuffs is what i meant

**Comment by tattax** [comment]
tVecYJZmOW

this is current

**Comment by cuackles** [comment]
so this adds the colors of the cable used to the cable cuffs correct ?

**Comment by cuackles** [comment]
or well like, it makes it simpler with less sprites needed

**Comment by tattax** [comment]
it makes cable cuffs properly register color because of how color was handled on cable coils (badly)

**Comment by cuackles** [comment]
> it makes cable cuffs properly register color because of how color was handled on cable coils (badly)

Bet

**Review by cuackles — APPROVED** [review]

**Pull request merged**
