### PR TITLE
adds anesthetic to robotics lab: now in MRP-O-VISION!!

### PR DESCRIPTION
**Pull request by UselessTheremin**
### Intent of your Pull Request

adds an anesthetic tank and mask to the robotics lab because its a rule now

### Why is this good for the game?

the new RP rules should be supported in the codebase, so yes, as much as I hate to admit it, this pr helps **INCREASE RP LEVEL 😳**

#### Changelog

:cl:  
rscadd: anesthetic tank and mask to the robotics lab
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
very controversial

**Review by patpol4 — APPROVED** [review]
RP status: increased

**Comment by patpol4** [comment]
also please change title to make sense so this shows up in search results for future generations

**Comment by Hopekz** [comment]
Next step is to make it sub-optimal to perform surgery while conscious so it isn't just a rule but part of the gameplay

**Comment by Nechronom** [comment]
Egad. What self-respecting follower of the great omnissiah would ever allow themselves to be put into a state of unconsciousness during the proceedings of the removing of pathetic flesh? But yes I agree that it should possibly have some effect on surgery chance. Maybe not all damage is restored to a patient after a surgery if they were not unconscious for it? Such as the amount of brute damage that is briefly given to someone when you're giving them xray eyes

**Comment by boodaliboo** [comment]
we could add pain killers

**Comment by Hopekz** [comment]
> we could add pain killers

Painkillers are pointless without pain

**Comment by maxion12345** [comment]
> > we could add pain killers
> 
> Painkillers are pointless without pain

I'm gonna stop you right there.

**Pull request merged**
