### PR TITLE
Adds Syndicate Stamp

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request

Adds two syndicate stamps!
Also makes the chameleon stamp able to stamp a box into a syndie box!

Syndicate Rubber Stamp
large_stamp-syndiround
image
(Can also stamp a box)

Knock-Off Syndicate Rubber Stamp
large_stamp-syndi
image

How they look in game:

image

Where to find them!

SyndiStamp:
-1TC in the uplink
-Spawns at Nukie Base
-Spawns at Caravan Space Ruin
-Spawns at Lavaland Base
-Spawns in the assault pod station ruin

Knock-Off SyndiStamp:
-Spawns in the vacant office

# Wiki Documentation

Added syndi stamp and knock-off syndi stamp

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Added syndicate stamp & offbrand syndicate stamp to a few maps & uplink

/:cl:

### CODE REVIEW

**Comment by Moggram** [comment]
can you also use this from the Chameleon Kit that comes with a stamp?

**Comment by azzzertyy** [comment]
> can you also use this from the Chameleon Kit that comes with a stamp?

as far as im aware yes, ill check again but i think it just looks for all /obj/item/stamp
EDIT:
image
yep

**Review by patpol4 — APPROVED** [review]
More infinity stamps to collect

**Comment by alexkar598** [comment]
isn't poisonous, 0/10

**Comment by Marmio64** [comment]
yes, make stamping someone with the authentic syndi stamp inject them with one unit of cyanide so you can kill someone after stamping them 30 times and waiting 10 minutes and hoping they dont notice their health going down. no seriously, please do it.

**Comment by patpol4** [comment]
no, just make it poison you when eaten, ink is bad for you

**Comment by azzzertyy** [comment]
> no, just make it poison you when eaten, ink is bad for you

how about make it so all stamps can be "licked" which wont dispose of the item but deliver a 1u dose of Bad Food, but the authentic syndie gives 1u of cyanide

**Comment by azzzertyy** [comment]
> > no, just make it poison you when eaten, ink is bad for you
> 
> how about make it so all stamps can be "licked" which wont dispose of the item but deliver a 1u dose of Bad Food, but the authentic syndie gives 1u of cyanide

second thought i cba to figure out how to do that rn maybe another time

**Review by nesisknesis — APPROVED** [review]

**Comment by JamieD1** [comment]
I mean..

Sure..

image

**Review by adamsong — APPROVED** [review]
Code looks fine

**Pull request merged**
