### PR TITLE
Medium scale nullrod quality pass

### PR DESCRIPTION
**Pull request by Moltijoe**
Nullrods are bloated, many of which are just boring reskins (that often times don't even look good)
this seeks to cull some of the worthless nullrods (most antag looking ones get to stay for anti-metagame reasons)

thanks to @cuackles for all the amazing sprites (and putting up with me)

### Tweaks

vibro blade gets a new sprite to tell it apart from the sec one
vibro
force weapon no longer has block chance, but acts like a powerful light source now

corvo blade no longer has block chance
this one was just utterly busted, it can collapse and be stored in the pocket, but it also kept it's block chance while collapsed

1 more reach to whip and can go in the belt slot but has 2 less force
whip always seemed like an underwhelming option when compared to others, people always ask for a ranged chaplain weapon anyways, this brings it closer to that niche, and less it be less clunky by letting them store it (watch the castlevania anime, he wears it on his belt like 90% of the time)

arrhythmic knife properly in weapon tab
that one's just a bug

clown knife has slippery
gives it more power for the honkmother sect

spear has increased throwforce and AP, but reduced force
makes it more like the actual ratvarian spear (just without the stun on throw and bonus burn damage)

### reworks

shield staves
deleted the red one to reduce bloat
moved it into the misc tab
removes block chance, gives it a number-tweaked shielded hardsuit effect (2 shots every 20 seconds instead of 3)
this gives it a defined identity as an "all-round defensive" weapon

40k hammer
this one had literally no identity, but looked cool enough that i know i HAD to give it something
requires two hands to use
pushes back people hit (it looks like a throw, but can't wallsplat people)

possessed sword overhaul
throwing it transforms it into a mob that can fly around (can't hurt anyone)
killing the mob drops the sword back to the ground
the person that woke the sword gets an ability to recall it (not instantly)
this can be used to pull it out of someone else's hands
no longer has any AP

video of the main changes

https://user-images.githubusercontent.com/108117184/227690191-ece8e586-cc23-4184-be63-e2c2d89d2652.mp4

### Deletions

scythe
this doesn't look nearly cool enough to warrant being such a boring weapon,
the vibro blade inherits the main typepath slot that the scythe used to (it's getting a new sprite)

pitchfork
it's kinda stupid looking, also didn't have any interesting effect and couldn't think of one to give it

pride hammer
so this one is a two fold problem, it both looks kinda iffy, and it's effect is ridiculously dangerous, transfering literally all chems from yourself into someone can let an IPC drink 1000u of every super death chem they want, and then bonk someone until it all transfers, rapidly killing them

multiverse blade
stupid effect that wasn't even a fun gimmick, didn't look nearly cool enough to warrant saving

energy cutlass
needless bloat when there's already 2 other energy swords, and doesn't really need the anti-metagame that the other antag weapons prefer

wiki take my energy

:cl:  @cuackles @Moltijoe 
rscdel: removed nullrods: scythe, pitchfork, pride hammer, multiverse blade, energy cutlass
bugfix: arrhythmic knife now shows in the weapon tab  
tweak: nullrod hammer now requires two hands and pushes hit targets away (no wallsplats)
tweak: nullrod staff now functions like the shield from a shielded hardsuit
tweak: possessed blade now has a new mob functionality
tweak: nullrod whip gets 1 more reach and can be put in the belt slot but has 2 less force
tweak: corvo blade nullrod no longer has block chance
tweak: spear nullrod has 2 less force, but 1 more throwforce and 10 more AP
tweak: banana blade nullrod is now slippery
imageadd: added new twohanded hammer sprites
imageadd: added sprites used by new possessed sword (abilities included)
imageadd: added new sprites for vibro blade
imagedel: deleted images used exclusively for removed nullrods
/:cl:

### CODE REVIEW

**Review by ToasterBiome — APPROVED** [review]
art approval

**Comment by Marmio64** [comment]
i used scythe for grim reaper gimmicks along with skeleton on halloween and would use pitchfork for devil cosplays, don't know why they need to be removed.

**Comment by cuackles** [comment]
> i used scythe for grim reaper gimmicks along with skeleton on halloween and would use pitchfork for devil cosplays, don't know why they need to be removed.

The scythe will probably be re integrated with a new sprite on the future, the current one does nothing and its a very shitty resprite of the botany scythe, it also for utility is completely outmatched by anything we currently have, and as more and more nullrods are moving forwards and giving a bit of utility or a gameplay gimmick the ones that are being removed are basically just bloat at this point

**Comment by RG4ORDR** [comment]
Make the whips actually deal bonus damage to vampires and bloodsuckers.

**Comment by Hislyna** [comment]
I prefer the old vibro blades glow, now it won't fit my drip T-T

**Comment by Moltijoe** [comment]
> I prefer the old vibro blades glow, now it won't fit my drip T-T

Get a security one then, im totally sure theyll provide one. (Also cuackles wanted it removed outright initially)

**Comment by Hislyna** [comment]
> > I prefer the old vibro blades glow, now it won't fit my drip T-T
> 
> Get a security one then, im totally sure theyll provide one. (Also cuackles wanted it removed outright initially)

They don't get the glow on it

**Comment by neeshacark** [comment]
MY SCYTHE NOOOOOOO

**Comment by Moltijoe** [comment]
> MY SCYTHE NOOOOOOO

don't worry, it's on the list of rods to re-add but with better quality sprites

**Comment by ChuChu42** [comment]
i like the changes but pride struck.hammer is my favorite nullrod and its only useful against cult as for chaplain usually wont get chems

why dont you make it transfer like 10u instead?

**Pull request merged**
