### PR TITLE
lag compensation

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request
Adds lag compensation to melee attacks, maybe helps feel the game a bit more responsive with high ping
# Changelog
:cl:  
rscadd: Lag compensation for melee attacks
/:cl:
wip

### CODE REVIEW

**Comment by Bibby0110** [comment]
Is this a port of something?

**Comment by Simplehorror** [comment]
> Is this a port of something?

no

**Comment by Maia-J** [comment]
**This man!!!**
**Ided tag him!**

In all honesty, if this is done right, it would increase the enjoyment for quite a lot of people. 
Of course, the Americans with their perfect 5ms will cry about this, but don't listen to them.

**Comment by Simplehorror** [comment]
i live in china so this PR is very important to me

**Comment by Bibby0110** [comment]
> > Is this a port of something?
> 
> no

You’re going to have to explain in technical detail what this does, and how it does it.

**Comment by Simplehorror** [comment]
> > > Is this a port of something?
> > 
> > 
> > no
> 
> You’re going to have to explain in technical detail what this does, and how it does it.

it will save the location history of all mobs in the world for 100 ticks in a rolling queue, when BeginLagCompensation is called it will rewind all mobs temporarily to their previous history and then restore them after EndLagCompensation is called

**Comment by Simplehorror** [comment]
actually not sure if updating it and restoring it in the same proc would cause visual updates but if it does i'll just add a hitbox xyz that's used for distance checking in clicks

**Comment by ToasterBiome** [comment]
> > > > Is this a port of something?
> > > 
> > > 
> > > no
> > 
> > 
> > You’re going to have to explain in technical detail what this does, and how it does it.
> 
> it will save the location history of all mobs in the world for 100 ticks in a rolling queue, when BeginLagCompensation is called it will rewind all mobs temporarily to their previous history and then restore them after EndLagCompensation is called



> > > > Is this a port of something?
> > > 
> > > 
> > > no
> > 
> > 
> > You’re going to have to explain in technical detail what this does, and how it does it.
> 
> it will save the location history of all mobs in the world for 100 ticks in a rolling queue, when BeginLagCompensation is called it will rewind all mobs temporarily to their previous history and then restore them after EndLagCompensation is called

What are the instances where BeginLagCompensation are called and under what conditions, who does it effect, etc.

**Comment by Simplehorror** [comment]
> > > > > Is this a port of something?
> > > > 
> > > > 
> > > > no
> > > 
> > > 
> > > You’re going to have to explain in technical detail what this does, and how it does it.
> > 
> > 
> > it will save the location history of all mobs in the world for 100 ticks in a rolling queue, when BeginLagCompensation is called it will rewind all mobs temporarily to their previous history and then restore them after EndLagCompensation is called
> 
> > > > > Is this a port of something?
> > > > 
> > > > 
> > > > no
> > > 
> > > 
> > > You’re going to have to explain in technical detail what this does, and how it does it.
> > 
> > 
> > it will save the location history of all mobs in the world for 100 ticks in a rolling queue, when BeginLagCompensation is called it will rewind all mobs temporarily to their previous history and then restore them after EndLagCompensation is called
> 
> What are the instances where BeginLagCompensation are called and under what conditions, who does it effect, etc.

it's called in ClickOn if the calling mob has a client, effects every mob on the map

**Comment by ToasterBiome** [comment]
> 

This just sounds like it will wildly lag everyone on the server if someone has a shitty connection

**Comment by Simplehorror** [comment]
no it wouldn't, it's virtual, it should only move them for hitreg detection and no visual updates would be sent

**Comment by ToasterBiome** [comment]
I do not think this will
1) work
2) have the intended effect

I think this will just make hit reg against lagging players advantageous to them.

Most importantly, this is shitcode. No goto, etc. Storing 10 seconds of locs for every mob (even every client) is bad and will cause far more lag at highpop than helping any amount of lagging players.

**Comment by Simplehorror** [comment]
> I do not think this will
> 
>     1. work
> 
>     2. have the intended effect
> 
> 
> I think this will just make hit reg against lagging players advantageous to them.
> 
> Most importantly, this is shitcode. No goto, etc. Storing 10 seconds of locs for every mob (even every client) is bad and will cause far more lag at highpop than helping any amount of lagging players.

please show me a way to do what i did with goto without a massive amount of code duplication and it's not 10 seconds, yogs tickrate is 20. and it wouldn't cause CPU pressure but memory pressure and storing 4 values is not a lot of memory, and you can't say "etc" after stating one example
>I think this will just make hit reg against lagging players advantageous to them.

that's the point? to make it easier for EU players to actually play the game?

**Comment by Bibby0110** [comment]
> no it wouldn't, it's virtual, it should only move them for hitreg detection and no visual updates would be sent

That’s not how that works. You’re doing a massive amount of processing and moving every time someone clicks anything, in addition to doing costly loops 10 times per second.
I don’t see how this wouldn’t have a massive performance impact.
In addition you’re opening yourself up to numerous issues by having a list stored like this. You’re hindering garbage collection of every single mob for approx 10 seconds, potentially causing a flurry of hard deletions and a list sprinkled with random and corrupted data. The same goes for the turfs (and objects) you’re storing.

While yes this is approximately how lag compensation is done in a simple FPS shooter those games have the advantage of being able to tailor their networking code to support all of this, while we’re stuck with BYOND and no way to do the same.

For some of the reasons above, the fact that you’re a new coder around here, and the fact that this would probably have been attempted sometime during the last decade and a half of SS13 development, I remain highly skeptical that this is even possible.

Feel free to correct me if I’ve misunderstood something, but I ask that you do this in a new PR that includes a thorough technical write up and heavily commented code.

**Comment by Simplehorror** [comment]
there's not a massive amount of processing, the move proc is NOT called when i set their xyz so there's almost 0 CPU time used. 
the GC issue is trivial to solve since we can just use the ID of the mob instead of a reference to it. you're acting like this is something impossible when it's been trivially done in every game since the 90s and even is in other BYOND games

**Comment by Simplehorror** [comment]
in fact BYOND gives you all the information you need to do lag compensation in the Click function but nobody uses it @TheGamerdk

**Comment by Bibby0110** [comment]
Provide detailed technical rundown and actual tangible data showing performance improvement and I’ll believe you.

You are absolutely spending a lot of CPU time on all these loops.

**Comment by Bibby0110** [comment]
> in fact BYOND gives you all the information you need to do lag compensation in the Click function but nobody uses it @TheGamerdk

Provide some examples of other BYOND implementations then

**Comment by Simplehorror** [comment]
all other BYOND games are closed source

**Comment by Simplehorror** [comment]
don't forget that this is a background subsystem

**Comment by CMOisLing** [comment]
See if someone who lives in another continent can host so you can preform a test to prove this works and doesnt cause to much extra processing time with a lot of mobs

**Pull request closed without merging**
