### PR TITLE
Multilingual Quirk

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Adds a new quirk: Multilingual. It grants the ability to understand a random language you're capable of learning, and speak it if your tongue is capable of it. This will NOT give you the ability to speak languages like codespeak or any other antagonist-related language.

There are also versions of the quirk for specific languages like etherean and mothian, similar to how the prosthetic limbs quirk has versions for specific limbs.

Ports and reworks BeeStation/BeeStation-Hornet#2228.

# Wiki Documentation

Probably mention this here:
https://wiki.yogstation.net/wiki/Quirks

# Changelog

:cl: SapphicOverload, DatBoiTim
rscadd: adds multilingual quirk
/:cl:

### CODE REVIEW

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
missing a good portion of race languages

**Comment by ToasterBiome** [comment]
thinking about it further, i don’t think we should offer any specific one besides english.

**Comment by 00ze-cyclone** [comment]
> missing a good portion of race languages

Lore reasons
*make the smugest face that ever smuged in history while writing this

**Comment by ToasterBiome** [comment]
hmm i think lore reasons would justify these other languages, nice work not clogging up the quirk menu.

**Comment by iamthesilly** [comment]
> missing a good portion of race languages

i just didn't want to fill up the entire quirks menu with just languages

**Review by ToasterBiome — APPROVED** [review]
looks not shitty

**Comment by ThatLing** [comment]
This will need some minor changes (mainly icon) when preferences gets merged

**Comment by iamthesilly** [comment]
> This will need some minor changes (mainly icon) when preferences gets merged

Noted

**Comment by GraveHat** [comment]
This sounds fun to use

**Comment by Marmio64** [comment]
could instead have it give you a pod caller thing like the musician trait or something of the sort, which would let you choose any roundstart species language (English, Draconic, etc) without cluttering the quirk menu.

**Review by ThatLing — CHANGES_REQUESTED** [review]
This will need changes to work with the preferences. Message me on discord if you need help

**Comment by iamthesilly** [comment]
done

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
