### PR TITLE
Adds Gift Shop to Omegastation

### PR DESCRIPTION
**Pull request by alao3alao3**
Intent of your Pull Request
Adds a much needed gift shop to Omegastation.
aa_MaDDepot

Minor hallway alcove is created. General storage room created, items oriented for the gift shop. Coin mint moved over several tiles.
Annotation 2020-07-13 231803

Displaced items reloacted to expanded Technology Storage (i.e Anti-breach shield projector)
apng

### CODE REVIEW

**Review by Ktlwjec1 — CHANGES_REQUESTED** [review]
Haven't looked at the map yet, but you'll need to go to "/code/modules/jobs/job_types/clerk.dm" and remove "/datum/job/clerk/proc/OmegaStationChanges()
	return TRUE"
and edit changed_maps to remove Omega. Also make sure the original clerk spawner is removed from this map if you haven't done that already, it's currently between medbay and research.

**Review by patpol4 — CHANGES_REQUESTED** [review]
1. remove the key, its stupid and useless,
2. wardrobe vendor needs to be set to req_access=0, check boxstation for reference,
3. patch up the girder hole leading to board storage
4. the hallway alcove needs a light
5. Smooth these areas out
chrome_7RLp1B5AFH
6. Multiple lattices under walls in this part, 
chrome_EQJatTtbvU
7. Paystands can be rotated
8. Please name the maint door to the gift shop

**Comment by alao3alao3** [comment]
I've tried to rectify the noted issues by making a new PR request. Github is a pain in the ass to use.

**Comment by patpol4** [comment]
https://github.com/yogstation13/Yogstation/pull/9262

**Pull request closed without merging**
