### PR TITLE
Windoors open faster and can be interacted with quicker

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Semi-port of https://github.com/BeeStation/BeeStation-Hornet/pull/8620/files using open_speed instead

https://github.com/yogstation13/Yogstation/assets/42524344/59132417-eda7-4c62-aeb2-62d10881eb44

# Why is this good for the game?
Allows you to annoy hop a little more, more consistent with firelocks which are the same size, less annoying to use.

# Testing
See video.

# Changelog
:cl:  
tweak: Windoors open faster
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
Man hacking them is going to be even more annoying

**Comment by azzzertyy** [comment]
> Man hacking them is going to be even more annoying

they stay open for the same amount of time

**Comment by wonderinghost** [comment]
Until someone shuts it. Windoors don't got wires. So you end up ripping the airlock board out of it and altering that

**Review by cuackles — APPROVED** [review]

**Review by Moltijoe — CHANGES_REQUESTED** [review]
what's the deal with the sound deletion?
also, why have open_speed = 0.25 if you're gonna add 0.1 to it?

**Comment by ShoziOffical** [comment]
> what's the deal with the sound deletion? also, why have open_speed = 0.25 if you're gonna add 0.1 to it?

coders are weird

**Comment by Moltijoe** [comment]
reopen this when you continue work

**Pull request closed without merging**
