### PR TITLE
Cargo budget now gets 50% payment from energy harvester

### PR DESCRIPTION
**Pull request by warface1234455**
# Document of changes 
Cargo budget now gets 50% payment from energy harvester
# Wiki Document 
Cargo budget now gets 50% payment from energy harvester

# Changelog

:cl:  
  
tweak: Cargo budget now gets 50% payment from energy harvester
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
Me when Editting on phone, imma go fix it when i get home

**Comment by Sniblet** [comment]
you mean it didn't all go to cargo? none of it went to cargo?
the engineering budget doesn't even exist, why does it go there

**Comment by ShoziOffical** [comment]
> you mean it didn't all go to cargo? none of it went to cargo? the engineering budget doesn't even exist, why does it go there

- there was one time that engineering budget was lacking credit and didnt payout to engi staffs, so energy harvester points got sent to engi #15415

```diff
- var/datum/bank_account/D = get_dep_account(ACCOUNT_CAR)
+ var/datum/bank_account/D = get_dep_account(ACCOUNT_ENG)
```
- now, engineers get paid again not needing energy harvester

**Comment by MajManatee** [comment]
so with this now... 70% of the money goes to engineering... which doesn't have a budget card anymore so it might as well be getting deleted?

I guess its better than nothing but still.
You should just re-add budget cards. :) Every department still has a budget, they just have no way to access it. Heads can order stuff for their departments using this money if they order from their PDAs.

**Comment by ShoziOffical** [comment]
> so with this now... 70% of the money goes to engineering... which doesn't have a budget card anymore so it might as well be getting deleted?

No it doesn't get deleted and instead stored in engi cloud budget, which NIRN program can access it to order stuffs.

> I guess its better than nothing but still. You should just re-add budget cards. :) Every department still has a budget, they just have no way to access it. Heads can order stuff for their departments using this money if they order from their PDAs.

Many prs attempted it and got denied

**Comment by MajManatee** [comment]
why not go up to 50%? That way more of the money will actually be used because, lets be honest, have you ever seen a head order anything, besides the hop or captain.

**Comment by ShoziOffical** [comment]
> why not go up to 50%? That way more of the money will actually be used because, lets be honest, have you ever seen a head order anything, besides the hop or captain.

well beside sm crate, ur right

**Comment by ReddicusDragon** [comment]
hmm we should readd budget cards

**Comment by ShoziOffical** [comment]
> hmm we should readd budget cards

Maybe

**Comment by JamieD1** [comment]
Have horrible balance concerns, will look into after merge

**Review by JamieD1 — APPROVED** [review]

**Comment by ShoziOffical** [comment]
> Have horrible balance concerns, will look into after merge

Wha

**Pull request merged**
