### PR TITLE
Adds new pathfinder lavaland gear, armor with ashproofing.

### PR DESCRIPTION
**Pull request by SomeguyManperson**
recipes:
Kasa: 12 bone, 12 sinew, 12 chitin
Cloak: 1 goliath cloak, 4 goliath plates, and 6 sinew
treads: 12 sinew and 16 chitin

Kasa and cloak have armor values of:
"melee" = 35, "bullet" = 20, "laser" = 20, "energy" = 10, "bomb" = 50, "bio" = 5, "rad" = 10, "fire" = 50, "acid" = 50
goliath plates can be added to increase armor by 10 melee, 5 ullet, 5 laser, 5 energy up to 3 times for 65 melee, 35 bullet, 35 laser, and 25 energy

equipping these will render you immune to ash storms and resistant to high temperatures

:cl:  
rscadd: new lavaland gear made from large amounts of butcher results from lavaland mobs!
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
that is a lot of melee resistance though tbh, only 5 less than ashdrake armor.

**Comment by Ratvar** [comment]
Number of mobs that are needed to assemble this seems a bit tooooo high.
Why not make it much cheaper, but slap a minor slowdown on it? Would make it specifically into anti-ash gear instead of gear upgrade you always wear, slow making it worse for combat and general use. Will let more people use it, which is nice.
Also no cool anti-sand glasses, sad.

**Comment by UselessTheremin** [comment]
i disagree with ratvar, i think that it is fine as is. in my experience as miner, even a tiny bit of slowdown is essentially death and in my opinion will make the armor near worthless

**Comment by Moggram** [comment]
my god, that is alot of killing for the mats.

**Comment by SomeguyManperson** [comment]
I wanted the crafting costs to be high and the armor to be slightly higher than an explorer suit to function as a sort of endgame gear that isnt megafauna or tendril loot so there's a reason to take parts from dead stuff past the first like 3 and a way to get ashproofing without tendril loot or megafauna fighting, although you would still probably need to farm s tendril yo get the required parts.

**Comment by JamieD1** [comment]
@Partheo

**Review by Partheo — APPROVED** [review]

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
@SomeguyManperson Cornflakes

**Pull request merged**
