### PR TITLE
Removes Scrying Orb

### PR DESCRIPTION
**Pull request by JamieD1**
Piece of crap item from 9 years ago and there have been more then 4 admin issues with this orb lately and players have been complaining too, fed up of this piece of crap.

:cl:  
rscdel: Scrying orb
/:cl:

### CODE REVIEW

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Please give a more detailed reasoning

**Comment by JamieD1** [comment]
> Please give a more detailed reasoning

No.

**Comment by maxion12345** [comment]
What kinda issues? And are they so bad they can't be fixed by a simple patch and require us to remove the entire item?

**Comment by JamieD1** [comment]
> What kinda issues? And are they so bad they can't be fixed by a simple patch and require us to remove the entire item?

The whole idea behind the item is a bad idea. Literally giving people aghost in the middle of a around.

**Comment by ToasterBiome** [comment]
Seems a bit of an admin issue innit?

**Comment by VaelophisNyx** [comment]
here's a suggestion from a friend that I think would be good

"I feel like in return they should get a psychic ouija board or something that lets them ask ghosts questions, with the ghosts having no compulsion to tell the truth"

Also good reason for this removal: Wizcurity forcing a greenshift by just outing every antag because free ghosting. Admins almost never do anything about it, it seems.

**Comment by ChesterTheCheesy** [comment]
> Literally giving people aghost in the middle of a around.

literally blood cult

**Comment by Marmio64** [comment]
Make the orb unusable by non wizards, sec should kill the friendly wizcurities.

**Comment by Bibby0110** [comment]
> Make the orb unusable by non wizards, sec should kill the friendly wizcurities.

Do this if it’s such a big problem

also this has 10 downvotes lol, state of Yogs

**Pull request merged**
