### PR TITLE
Replaces lavaland cycling airlock with tiny fans

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

QoL
replaces with 2 tiny fans

#### Changelog

:cl:  
tweak: Replaced lavaland cycling airlock with tiny fans
/:cl:

### CODE REVIEW

**Comment by LazennG** [comment]
uh based?

**Comment by MegaEmpirical** [comment]
SHAME.

Airlock everyday all day.

**Comment by patpol4** [comment]
At this point after numerous fixes that were supposedly going to make the airlock work, I believe this is warranted. @JamieD1 what do you think?

**Comment by SomeguyManperson** [comment]
I mean the lavaland airlock works fine currently the main issue is with airlocks adjacent to shuttle docking areas

**Comment by JamieD1** [comment]
Airlocks work fine, unless you can give me a viable reason apart from I don't want to wait 2 seconds this will not be reopened.

**Pull request closed without merging**
