### PR TITLE
Events prerun text is now much bigger and red and also increase cancel time to 20 seconds

### PR DESCRIPTION
**Pull request by redmoogle**
# General Documentation

### Intent of your Pull Request

image
image

Stops missing events

Lyis Approved:tm:

### Why is this change good for the game?

Makes it easier for admins to realize is something bad is about to gamer you

# Changelog

:cl:  
tweak: Event cancel time is 20 seconds
tweak: Event cancel text is scary red
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
that big of text is gonna get annoying quick

**Comment by alexkar598** [comment]
What the uppercase Y said.

**Comment by redmoogle** [comment]
> 
> 
> What the uppercase Y said.



> 
> 
> that big of text is gonna get annoying quick

Lyis Approved:tm:

**Comment by Mesalikepie** [comment]
I like this because it gives us slightly more time, events aren't too common, and we can now actually notice them.

**Comment by MegaEmpirical** [comment]
Thank you for this.

**Comment by JamieD1** [comment]
Its not often enough to get annoying alexkar.

**Pull request merged**
