### PR TITLE
makes flamethrower not destroy atmos

### PR DESCRIPTION
**Pull request by ynot01**
# General Documentation

### Intent of your Pull Request

Makes flamethrower not destroy the atmos of the room it's used in
Takes on old version where it just ignites things in its path

ISSUES FIXED

- [ ] works when out of atmos
- [ ] works on any gas not just flammable gasse

### Why is this change good for the game?

No more atmos floods with a flamethrower

# Changelog

:cl:    
tweak: Flamethrower no longer spreads atmos, only ignites
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
Yes

**Comment by TheLinuxOS** [comment]
Finally now it will be a weapon that can be used without killing an entire department due to superheating

**Comment by Marmio64** [comment]
you'll still be able to do fun stuff, like putting a tank of water vapor in it and using it to quickly clean floors, yeah?

**Comment by Cartlord** [comment]
Doesn't fire need an Atmosphere to... burn, though?

**Comment by ynot01** [comment]
i fucking hate atmos code

**Comment by N3D6** [comment]
:(

**Pull request closed without merging**
