### PR TITLE
Adds Cluwnes Fixes Dolphins and ... Floor Cluwnes Ported from Hippie

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 fluffe9911 for porting banthebqntz for cluwnes and steamp0rt for floor cluwnes
add: Cluwnes Cluwne Curse Spell and ... Something Else
fix: dolphins now actually spawn (dangit altoids)
/🆑
It was inevitable and please ignore any sounds you may hear in the maintenance or under the floors thank you.

### CODE REVIEW

**Comment by ThatLing** [comment]
Please change your PR title to something less vague

**Comment by fluffe9911** [comment]
Ughhh fine party pooper

**Comment by ghost** [comment]
if you're fixing things can you please fix my life?

please help, i'm very lonely

**Comment by fluffe9911** [comment]
Be nice to people and think about how what you say may effect other people? *shrug*
Socializing also helps

Edit oh and self reflection is important think about why you act or are acting a certain way in situations

**Pull request merged**
