### PR TITLE
Ports and fixes Singularity Hammer in hand sprites + new Mjolnir sprites from TG

### PR DESCRIPTION
**Pull request by tattax**
Original prs: https://github.com/tgstation/tgstation/pull/59889 , https://github.com/tgstation/tgstation/pull/51109
(tested)

# Document the changes in your pull request

hammer now drippy af 

# Wiki Documentation

glow up

image

image

:cl:   
imageadd: hammer now looks epic
imagedel: blue hamoroo is gone  
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
@Chubbygummibear

**Comment by Chubbygummibear** [comment]
pain, agony even

**Comment by tattax** [comment]
the second one should fix the tiny weeny white pixel

**Comment by bruhlookatthisdood** [comment]
thor is that you?

**Review by nesisknesis — APPROVED** [review]

**Pull request merged**
