### PR TITLE
Makes Nightmare a little less shitty on low pop

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

Lets give the crew a chance nightmare.

#### Changelog

:cl:  
tweak: Made nightmare have a wait time.
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
wait time for what, and you can already go up to a nightmare and stunbaton joust it with a light on

**Comment by Hopekz** [comment]
> wait time for what, and you can already go up to a nightmare and stunbaton joust it with a light on

Maybe he needs 45 minutes to mentally prepare himself

**Comment by JamieD1** [comment]
> wait time for what, and you can already go up to a nightmare and stunbaton joust it with a light on

On low pop with no security nighmares steamroll and kill basically everyone. This doesnt nerf them in anyway

**Comment by JamieD1** [comment]
> wait time for what, and you can already go up to a nightmare and stunbaton joust it with a light on

How about if I removed the wait and kept the min players then.

**Pull request merged**
