### PR TITLE
gus is sus as shit: mimes can now get the mech that was designed for them

### PR DESCRIPTION
**Pull request by Moltijoe**
Bruh, why'd they close it

Pretty cool item for a role that unfortunately has next to no exclusive items, which is pretty sad. The things the mech comes equipped with aren't terribly overpowered, so this is probably balanced for 20tc. 

WHY IS MECH MELEE CODED THIS WAY, MECHS DON'T PUNCH THINGS, OBJECTS INSTEAD GET PUNCHED BY MECHS IT'S THE FUCKING OPPOSITE OF WHAT IT SHOULD BE OH DEAR GOD WHY.

:cl:  @TheRyeGuyWhoWillNowDie @Moltijoe 
rscadd: traitor mimes can buy the mime mech for 20tc
tweak: reticence and it's equipment is now completely silent
/:cl:

### CODE REVIEW

**Comment by namjay1170** [comment]
it is painfully easy to see the mech with basic mesons on or even in decent lighting, perhaps it could go fully invisible under some condition? darkness/not moving perhaps.

**Comment by Moltijoe** [comment]
> it is painfully easy to see the mech with basic mesons on or even in decent lighting, perhaps it could go fully invisible under some condition? darkness/not moving perhaps.

it's completely silent, making it at least somewhat visible is probably for the best balance wise

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Mid

**Comment by Therandomhoboo** [comment]
I wanna say not every role needs a mech...

**Comment by Burger1998** [comment]
> I wanna say not every role needs a mech...

i mean roles that have a mech literally designed for them should probably get it in some form

**Comment by ynot01** [comment]
> i mean roles that have a mech literally designed for them should probably get it in some form

dumb logic

the mime mech is cool as shit though

**Review by MajManatee — APPROVED** [review]
i think you addressed all my concerns from the previous PR

**Review by ReddicusDragon — APPROVED** [review]

**Pull request merged**
