### PR TITLE
Removes the Supermatter alert sound in exchange for a better one

### PR DESCRIPTION
**Pull request by swissloaf**
### Intent of your Pull Request

Exchanges the terminal alert for a better supermatter alert

[Supermatter Alert](https://cdn.discordapp.com/attachments/293085045743157248/713481381853790238/supermatter_alert.ogg)

#### Changelog

:cl:  
soundadd: Adds new supermatter alert sound
tweak: Changes supermatter alert from terminal to new one
/:cl:

### CODE REVIEW

**Comment by athena413** [comment]
i hate it

**Comment by swissloaf** [comment]
> i hate it

suks

**Comment by Marmio64** [comment]
sounds like a kitchen fire alarm

**Comment by swissloaf** [comment]
> sounds like a kitchen fire alarm

no its a lab alarm, this is the lowest alert sound. engine_alert1 and 2 get stronger and deeper

**Comment by patpol4** [comment]
The last one was great, this one is awful, please no

**Comment by swissloaf** [comment]
bruh

**Pull request closed without merging**
