### PR TITLE
Revert "Revert "Makes SM the only roundstart engine, no generator for you edition""

### PR DESCRIPTION
**Pull request by Bibby0110**
Reverts yogstation13/Yogstation#18550

Contributor guidelines state that reverts must not be made before 48 hours has passed from the original PR being merged

### CODE REVIEW

**Comment by ToasterBiome** [comment]
unneeded

**Comment by Bibby0110** [comment]
24 hour rule

**Comment by ErolThurn** [comment]
Based PR war,on the other note please stop making tg level no sense PR's

**Comment by ToasterBiome** [comment]
HDs aren’t beholden to the contributing guidelines (for some reason)

**Comment by Bibby0110** [comment]
It doesn't state anywhere in the contributor guidelines that I can't reopen this PR

**Comment by ToasterBiome** [comment]
Your mommy my hugs

**Comment by DylonBR** [comment]
PR wars!!!!!

**Comment by Bibby0110** [comment]
A compromise has been reached

**Pull request closed without merging**
