### PR TITLE
[PORT] New Jraphics

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

Ports https://github.com/BeeStation/BeeStation-Hornet/pull/2144
Steals from https://github.com/BeeStation/BeeStation-Hornet/pull/6464

New floors, area lighting, new overlays (no longer emissive, sorry)

Will get more screenshots

dreamseeker_dhuGblHki4

# Why is this good for the game?
We look a bit dated (espessially compare to something in the same tier of servers as us, like fulp or bee), and this is a multiple year effort for me to get new and different floors in.

# Testing

# Spriting
Will get shortly

# Wiki Documentation

# Changelog

:cl:  PowerfulBacon, Sinestia, ToasterBiome
rscadd: Each area can now have their own tube and bulb color
rscdel: Some old floors that should have been decals were deleted
tweak: Light overlays are brighter and no longer emissive (so you can see them in light)
tweak: Floors have been redesigned
/:cl:

### CODE REVIEW

**Comment by Necrosium** [comment]
They look good, I like the maint ones they have a more industrial appearance, and the wooden ones are just epic (jesus christ)

I especially love the reinforced flooring, looks more realistic and smooth

**Review by cuackles — APPROVED** [review]

**Comment by RG4ORDR** [comment]
Nope. No. Nuh-uh.

I legitimately do not like these - and it's not because of a "SOUL" reason. I legitimately do not think the default floor tiles need to be changed. There's nothing wrong with them, and any new item, machine, furniture, or so forth has no issues going onto of them.
They also have that weird grey dot optical illusion going on. They look raised and beveled for some reason, and look IMO fuzzier than the default.

Seriously do not replace them - make it a station trait for "PREMIUM FLOOR TILES" otherwise there is honest to god no function reason to consider doing this.

**Comment by Moltijoe** [comment]
> I legitimately do not like these - and it's because a "SOUL" reason. I legitimately do not think the default floor tiles need to be changed. There's nothing wrong with them.

my dude, the current tiles are crusty as fuck, i genuinely wanted to jump ship for bee when i briefly booted a test server of their codebase simply because of how much less shitty everything looks

**Comment by cuackles** [comment]
soul is not even considered an argument, is just that people don't like change, and wont be taken as a real argument

**Comment by RG4ORDR** [comment]
> > I legitimately do not like these - and it's because a "SOUL" reason. I legitimately do not think the default floor tiles need to be changed. There's nothing wrong with them.
> 
> my dude, the current tiles are crusty as fuck, i genuinely wanted to jump ship for bee when i briefly booted a test server of their codebase simply because of how much less shitty everything looks

Yeah I made a typo there - it's not because of SOUL.
Like I simply do not like them, they easier on the eyes, they really aren't  over-designed and that are unobtrusive. 
Hell I made my case my for some of the clothing respites because I hate the colors on them and how they simply do not as good as what was being used previously. There are aspects of the game's look that I enjoy - having the HD Texture Pack 1 of 20 is not one of them. I don't even like Bee Station's tools. The sprites aren't bad but half of them simply belong somewhere else and borderline reminds me of stuff from Starbound or other side-scrolling games.

**Comment by JohnFulpWillard** [comment]
it's graphics not graphics

**Review by Aquizit — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]
fairly shrimple code

**Review by cuackles — APPROVED** [review]

**Pull request merged**
