### PR TITLE
Removes the wizard academy entirely

### PR DESCRIPTION
**Pull request by LoliconSlayer**
Just deleting it altogether because people wanted it gone. I could not care less.
Merge conflict with #9547 #9546 #8796 

:cl:  
rscdel: Our NanoTrasen strike teams have found the Wizard Academy and destroyed it.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Based

**Comment by ghost** [comment]
Also need to remove the code bits out or it'll spawn errors on map load

**Review by Hopekz — CHANGES_REQUESTED** [review]
This PR won't work and will cause errors.
You just removed the map file but now you have references pointing to that map file.

**Comment by PettyOfficer** [comment]
No, u.

**Review by patpol4 — CHANGES_REQUESTED** [review]
This is not how removing works, you would have to edit configs and other references in the files aswell.

**Comment by LoliconSlayer** [comment]
Right I forgot about the spawning, hold on

**Comment by LoliconSlayer** [comment]
Well Turdis is happy so I'm sure it's good enough

**Comment by LoliconSlayer** [comment]
Discord_GayWw0FJAL

**Pull request closed without merging**
