### PR TITLE
New virology symptom: symbiotic regeneration

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Adds a new virology symptom: symbiotic regeneration.

This new symptom heals you slowly while standing still for longer than 3 seconds. Heal rate is 0.5 brute/burn/toxin every 2 seconds.

# Why is this good for the game?

Adds more variety to the types of beneficial viruses that can be made, so it's less of the exact same thing every round.

# Testing

Made a virus with this symptom, gave it to myself, the symptom healed when standing still for long enough and stopped when moving.

# Wiki Documentation

Add this to the list of symptoms on the guide to infections

# Changelog

:cl:  
rscadd: new virology symptom: symbiotic regeneration
/:cl:

### CODE REVIEW

**Comment by boodaliboo** [comment]
i think both should be in the game not as a replacer but as a addition but its kinda obvious i would have that decision

**Comment by iamthesilly** [comment]
> i think both should be in the game not as a replacer but as a addition but its kinda obvious i would have that decision

Superficial healing doesn't do anything useful or interesting, why keep it in the game?

**Comment by solwashere** [comment]
Bungus

**Comment by boodaliboo** [comment]
then changed the fucking stamina damage the resistance tier does
slightly change the stealth
from -2
to -1
make its stealth requiremet 3
stage speed sorry
or more like 3-5 range
but jesus slicer when i cnat get a actual word in of course your not going to understand why i think it should stay
i think it should heal to base 15 but at a slower rate
i think having it add scarring which i believe we have now correct me if im wrong
not making you unknown
but like using the injury system

these are just starts on how to rework superficial healing

**Comment by iamthesilly** [comment]
> then changed the fucking stamina damage the resistance tier does slightly change the stealth from -2 to -1 make its stealth requiremet 3 stage speed sorry or more like 3-5 range but jesus slicer when i cnat get a actual word in of course your not going to understand why i think it should stay i think it should heal to base 15 but at a slower rate i think having it add scarring which i believe we have now correct me if im wrong not making you unknown but like using the injury system
> 
> these are just starts on how to rework superficial healing

The core idea of only healing when you're close to full health is just fundamentally bad.

**Comment by boodaliboo** [comment]
> > then changed the fucking stamina damage the resistance tier does slightly change the stealth from -2 to -1 make its stealth requiremet 3 stage speed sorry or more like 3-5 range but jesus slicer when i cnat get a actual word in of course your not going to understand why i think it should stay i think it should heal to base 15 but at a slower rate i think having it add scarring which i believe we have now correct me if im wrong not making you unknown but like using the injury system
> > these are just starts on how to rework superficial healing
> 
> The core idea of only healing when you're close to full health is just fundamentally bad.

why is it bad, i think personally having a symtopym require radiation to heal is bad just because it incentivizes people getting irridiated and then the rads will spread to others. atleast give me a why its bad and not just its bad

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
