### PR TITLE
Makes it so that heads of staff cannot be traitors anymore.

### PR DESCRIPTION
**Pull request by ghost**
Because you're all shit.

### CODE REVIEW

**Review by JamieD1 — APPROVED** [review]

**Comment by boodaliboo** [comment]
i was under the impression they already couldnt be traitors but could be blood bros

**Comment by ghost** [comment]
you're an idiot as usual, then

**Comment by boodaliboo** [comment]
> you're an idiot as usual, then

lol

**Comment by MegaEmpirical** [comment]
I've mentioned either making them less likely to be an antag and/or put a floating cap on how many can be an antag in a round. But I can get behind just making them not antags at all honesty. I always thought it felt a little weird, especially when nearly every fucking head is an antag

**Comment by Mesalikepie** [comment]
Fucking it doesn't make sense lore wise really why they're traitors, it's unbalanced as hell generally, and it's been abused already

**Comment by ynot01** [comment]
ill stand behind this

**Pull request merged**
