### PR TITLE
Adds a preference to disable alternative stations announcers (like the intern and medbot)

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

see title

# Wiki Documentation

# Changelog

:cl:  
rscadd: There is now a game preference to disable wacky announcers like the intern and medbot.
/:cl:

### CODE REVIEW

**Comment by CrazyDrakkon** [comment]
All must suffer.

**Comment by Takahiru** [comment]
Better alternative to #14983 pog

**Comment by ShadowDeath6** [comment]
I haven't ever actually heard alternate announcement voices. Are they just extremely rare?

**Comment by Bibby0110** [comment]
> I haven't ever actually heard alternate announcement voices. Are they just extremely rare?

they're extremely common

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
