### PR TITLE
BibbyBank | Persistent Savings Account and Medical Insurance

### PR DESCRIPTION
**Pull request by Bibby0110**
# Document the changes in your pull request

Depending on your job you get a paycheck after every shift you survive (On the escape shuttle or not)
This gets added to a persistent account. You can subscribe to different plans for *health insurance!*
Medbay can create bills for you (They don't have to) and you can pay them! 

Apart from that you can use your persistent account for showing how cool at playing the game you are! (Leaderboard basically)

Other things maybe too idk.

See what everyone is saying:

> I don't think this is a good idea
> -the discord

> this isn't a good idea
> -me

> can i get funny powergame loot???
> -the donators

# Wiki Documentation

# Changelog

:cl:  
rscadd: Every player is granted a persistent savings account, every shift you survive gets you a paycheck that gets put into this
rscadd: Adds medical insurance. Spend your persistent savings on differing tiers of medical insurance! WHOO!!!
rscadd: Invest your savings in either the NanoTrasen or Syndicate retirement funds! Investing in the Syndicate may potentially help fund their operations..
rscadd: Medical gets a new machine to print out bills! Bills are paid in-shift using actual normal money. 
rscadd: Gift other people medical insurance! WOW!
rscadd: Donators get free shifts of medical insurance????? WHAt???
experimental: This is experimental, like... all of it
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
donator shit is p2w

**Comment by MajManatee** [comment]
sounds cool

**Comment by Bibby0110** [comment]
> donator shit is p2w

yes

**Comment by Mqiib** [comment]
easy solution to pay 2 win: medical insurance never actually covers your bills and is just a perpetual joke

**Comment by Bibby0110** [comment]
> easy solution to pay 2 win: medical insurance never actually covers your bills and is just a perpetual joke

Technically it already does that. You don't really have to pay, I doubt medbay is going to stop you, and I doubt security is going to do anything unless its a slow shift

**Comment by MusselMain** [comment]
Eyo, quit trying to make this an average American simulator, can't wait to grow meds in public botany because I can't pay for the cost of insurance

**Comment by MusselMain** [comment]
Also this means certain roles are more likely to have bigger debts due to the danger involved in being said roles

**Comment by ilikesaying** [comment]
i swear if nanite healing programs are locked behind subscriptions

**Comment by maxion12345** [comment]
this is funny as fuck and shouldn't be added

thumbs up

**Pull request closed without merging**
