### PR TITLE
Adds a system message topic for better integration with tooling

### PR DESCRIPTION
**Pull request by alexkar598**
### Intent of your Pull Request

Adds a world topic for authorized external tools to send messages to the users on the server. ATM not going to be used by anything but eventually I'll need this for smooth TGS updates

:cl:  
rscadd: Adds the ability for external tooling to send server messages
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
DNM while I fix the line endings

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Line endings

**Review by adamsong — APPROVED** [review]
Don’t see anything wrong with the code

**Review by Bibby0110 — APPROVED** [review]

**Comment by Bibby0110** [comment]
Merge in 22 hours

**Pull request merged**
