### PR TITLE
Ports some rev shit from TG

### PR DESCRIPTION
**Pull request by ghost**
# Document the changes in your pull request

Ports some rev related PR's from TG.

https://github.com/tgstation/tgstation/pull/55956
https://github.com/tgstation/tgstation/pull/58160
https://github.com/tgstation/tgstation/pull/58165

And also ports a burectatic error event related PR, because it is required for #55956

https://github.com/tgstation/tgstation/pull/47873

# Changelog

:cl: Mothblocks, tralezab, Skoglol, ported by SuperSlayer
rscadd: A victory for revolutionaries will no longer end the round on dynamic, instead no new security and command will be allowed to join.
rscadd: Headrevs become enemies of the state when the revolution is over!
rscadd: One headrev is tasked with renaming the station when revolutions are successful
tweak: Bureaucratic error event has new effects!
/:cl:

### CODE REVIEW

**Comment by kooarbiter** [comment]
leave the riot suppression to cold, emotionless borgs, it shouldn't be their job to fuck up nukies and wizards and eldritch abominations anyways

**Comment by KillerOrcaCora** [comment]
Please show your sprites in-game using the spriting template.

**Comment by JamieD1** [comment]
Why you removing "check_finished"

**Comment by ghost** [comment]
> Why you removing "check_finished"

It was in the original PR

**Comment by JamieD1** [comment]
> > Why you removing "check_finished"
> 
> It was in the original PR

No, we added this to our PR, you have removed it. Reopen it when you are working on it.

**Comment by ghost** [comment]
I can't reopen this by myself since I am not a maintainer

**Pull request closed without merging**
