### PR TITLE
Smooth Doors

### PR DESCRIPTION
**Pull request by monster860**
Originally, doors have animated icon_states which are often at ~10 fps. This PR replaces this model with a model of having a left side and right side, or in more complicated cases (such as the abductor door with 7 parts!) more, and animating them to move, allowing the thing to be silky-smooth

Gif of all the doors:
[gif](https://cdn.discordapp.com/attachments/134720091576205312/721696461494157342/doooooors.gif)

Gif of hatch:

gif

:cl: monster860
tweak: Doors are now smoother
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Can we see what regular airlocks look like too

**Comment by Partheo** [comment]
@monster860

Show us what the other airlock types look like too, especially regular airlocks as they are the most common and will end up being like 90% of what this PR is changing

**Comment by Partheo** [comment]
I actually like the regular door movements, in the new gif you posted. I wasn't sure about it at first but it looks quite good. 

Strongly dislike the animated hatch though. Rotating pixels is an artistic warcrime.

**Review by Partheo — CHANGES_REQUESTED** [review]
No rotating sections, translations only.

**Review by JamieD1 — APPROVED** [review]

**Comment by Tipy1802** [comment]
Damn that took a while :P

**Pull request merged**
