### PR TITLE
Lets preterni eat ores

### PR DESCRIPTION
**Pull request by Moltijoe**
More flavour for the species, they're growing metal plates as skin, how are they getting the metal?
Can't eat sheet metal (to hard for their teef) (also, haven't made the metal cocktail drink yet, that can come later)

currently just iron (heals 2 brute)
and plasma (heals 2 burn)

can be expanded to include other ores with funny effects in the future

:cl:  
rscadd: Preterni get a special stomach
rscadd: Preternis stomach lets people eat iron and plasma ore to heal for very small amounts
/:cl:

### CODE REVIEW

**Comment by iamthesilly** [comment]
mmm tasty ore

**Comment by wonderinghost** [comment]
New wave of preternis miners and a lack of iron sheets cause they are eating it

**Comment by Marmio64** [comment]
Did you make this instant? If so, it shouldn't be. A small timer of 2 seconds would be pretty appropriate.

**Comment by wonderinghost** [comment]
New traitor weapon for preternis. A big form designed to eat and digest parts of the station. Makes the frame black and purple with yellow accents (Insecticons)

Allows them to eat sheets and it does a whole 4 healing when eating metal and plasma sheets

**Comment by wonderinghost** [comment]
Jk

**Comment by Moltijoe** [comment]
> Did you make this instant? If so, it shouldn't be. A small timer of 2 seconds would be pretty appropriate.

no need, food is already instant to eat elsewhere
they also have healing with timers from cables and welding tools

this is significantly weaker of an effect, so they get to do it instantly just like eating

this isn't even a heal over time like reagents are, so they'll need to be actively eating in order to get any healing

**Comment by Marmio64** [comment]
> > Did you make this instant? If so, it shouldn't be. A small timer of 2 seconds would be pretty appropriate.
> 
> no need, food is already instant to eat elsewhere they also have healing with timers from cables and welding tools
> 
> this is significantly weaker of an effect, so they get to do it instantly just like eating
> 
> this isn't even a heal over time like reagents are, so they'll need to be actively eating in order to get any healing

Except eating actually makes you full and still has a delay between bites, so it can't be spammed. It'd be a bit silly for them to just vacuum entire ore piles for quick healing.

**Comment by Moltijoe** [comment]
> Except eating actually makes you full and still has a delay between bites, so it can't be spammed. It'd be a bit silly for them to just vacuum entire ore piles for quick healing.

i can just always add the delay that food does

edit: so turns out, they already had that delay, BUT, this reminded me to add the speed boost for having voracious

**Comment by MajManatee** [comment]
mmm im so full of (mounds of rock, iron, and plasma), yum!!

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
