### PR TITLE
Adds a trait that makes you more likely to get shitty items in the mail

### PR DESCRIPTION
**Pull request by Moltijoe**
Receiving mail is always a good thing, some don't want or care
This lets them sacrifice mail quality for 1 quirk point (probably voracious or efficient metabolism)
They probably weren't going to open it anyways

:cl:  
rscadd: Adds a trait that makes you more likely to get shitty items in the mail
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
> Also, lets people be very suspicious of cargo techs when they receive mail despite having this quirk (it's a bomb)

Sounds like something easily metable

Also I don't see a need for this, Cargo techs don't have to deliver mail and you dont have to open it. If anything make it so that you get reduced loot because nobody wants to send you stuff.

**Comment by Moltijoe** [comment]
> Also I don't see a need for this, Cargo techs don't have to deliver mail and you dont have to open it. If anything make it so that you get reduced loot because nobody wants to send you stuff.

i don't see how i could give reduced loot, something like subtracting 10 from all weights in the list and then deleting anything in the list with a weight below 1?

**Comment by ToasterBiome** [comment]
> 

Figure it out :^)

**Comment by Moltijoe** [comment]
> > 
> 
> Figure it out :^)

thanks! i will   
:   ^     |

**Review by ToasterBiome — APPROVED** [review]
Much nicer, just need the trait name and define changed along with the desc

**Review by ToasterBiome — APPROVED** [review]
love it

**Comment by Hislyna** [comment]
I'd love to see the opposite where you get better or the chance of double the amount of mail/items for the cost of quirk points

**Review by ReddicusDragon — APPROVED** [review]

**Pull request merged**
