### PR TITLE
Autolathe 2.1 - Fucking Performance Edition

### LINKED ISSUE #8410: Autolathes still build while their panel is open
Round ID: 26721

Reproduction: Queue items up, unscrew the autolathe. The autolathe will continue down the queue, buttons can't be clicked but it will continue.

Additionally, cutting the production wire still lets it build mid-construction (haven't tested cutting the wire and THEN starting production)
Thanks #8142

### PR DESCRIPTION
**Pull request by JamieD1**
### Intent of your Pull Request

- Fixes #8410 
- Search now uses advanced regex and is not simple shit
- Much better performance
      - Moved selected category to client side
      - Force refreshed the queue to make it a little faster (That's all shes got captain)

Will be merged in with TGUI Change #8291 

#### Changelog

:cl:  
bugfix: Fixed being able to autolathe with panel open
tweak: Improved autolathe performance
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Could have just reversed it

**Comment by JamieD1** [comment]
> Could have just reversed it

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Bibby0110** [comment]
now you just need ui_static_data for MAXIMUM power

**Comment by JamieD1** [comment]
> now you just need ui_static_data for MAXIMUM power

Too hard, I tried.

**Review by alexkar598 — CHANGES_REQUESTED** [review]
Remove the regex, its a barely noticable feature but it can get a bit expensive to run without mentionning the fact that you cant write all characters( like ( needs to be escaped )

**Comment by JamieD1** [comment]
> Remove the regex, its a barely noticable feature but it can get a bit expensive to run without mentionning the fact that you cant write all characters( like ( needs to be escaped )

It was one of the most requested features with the new ui :(

**Comment by JamieD1** [comment]
Included in tgui 3.0

**Pull request closed without merging**
