### PR TITLE
Adds a sick jacket

### PR DESCRIPTION
**Pull request by BlueishTsunami**
Adds a sweet jacket
- battlejacket sprites
- battlejacket code

# Spriting
item

clothesdrobe

image

:cl:  
rscadd: Added punk/metal style battle jacket to the hacked clothesdrobe
imageadd: Added sprites for battle jacket
/:cl:

### CODE REVIEW

**Comment by BlueishTsunami** [comment]
quick update to move the jacket under the hacked inventory list

**Comment by solwashere** [comment]
The jacket is indeed sick

**Review by cuackles — CHANGES_REQUESTED** [review]
the outline cuts off at the shoulders pls fix that bit and the outline is also pure black pls make it closer to the colors of the jacket so the jump aint so strong between body and outline

**Review by Moltijoe — APPROVED** [review]
code good

**Review by cuackles — APPROVED** [review]

**Pull request merged**
