### PR TITLE
makes it tell people what the lobby music is

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

people constantly ask, so heyho

#### Changelog

:cl:  
tweak: you'll now be told which lobby-song is playing.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
Breaks war ops

**Comment by Amelia0010** [comment]
what

**Comment by Bibby0110** [comment]
image

**Comment by fluffe9911** [comment]
@nichlas0010 this broke travis lol

**Pull request merged**
