### PR TITLE
makes goliath ranged cooldown longer

### PR DESCRIPTION
**Pull request by boodaliboo**
image

### Intent of your Pull Request
i dunno i guess im doing lavaland changes right now
#### Changelog

:cl:  
tweak: tweaked goliath cooldown
/:cl:

### CODE REVIEW

**Review by jcatjmeow — CHANGES_REQUESTED** [review]
This changes the delay between tentacle attacks.
If your intention is to change the movement you need to change move_to_delay
If you want to make the chomps happen less you gotta change the value rapid_melee although you should arguably just reduce the damage at that point

**Comment by Moggram** [comment]
I feel like this will make the fight longer, as you can get in two hits in when it is doing the ranged attack. But it will be easier for the unrobust who can't time it right and have to wait to dodge the tentacle.

**Comment by boodaliboo** [comment]
> This changes the delay between tentacle attacks.
> If your intention is to change the movement you need to change move_to_delay
> If you want to make the chomps happen less you gotta change the value rapid_melee although you should arguably just reduce the damage at that point

my intention was to change the tentacle attacks

**Comment by Mesalikepie** [comment]
But why though

**Comment by Hopekz** [comment]
Why are you quoting me on your PR when you didn't even do the thing in the quote 

image

**Comment by boodaliboo** [comment]
> Why are you quoting me on your PR when you didn't even do the thing in the quote
> 
> image
> 
> 

i misunderstood what you said but i still wanted this change

**Comment by SomeguyManperson** [comment]
don't see any reason to do this

**Pull request closed without merging**
