### PR TITLE
Cycling Airlocks

### PR DESCRIPTION
**Pull request by monster860**
I wrote my own cycling airlocks with blackjack and hookers! Now, I know there's already two other varieties of cycling airlock in the game, but this one is better because you can map them in without having to change 50 vars, and they can be built in game. It also supports the ability to cycle between two rooms of different atmospheres and has controls for how much you want to allow the two rooms' air to mix.

image

:cl: monster860
add: Cycling airlock controllers! Build them using metal and the appropriate electronics.
tweak: All external airlocks on boxstation are now the cycling kind. In addition, the firelocks under these airlocks have been removed.
/:cl:

### CODE REVIEW

**Comment by yacabo** [comment]
There should be an emergency override option

**Comment by alexkar598** [comment]
Make it locked on engi access to modify shit so that bummer mc tide cant walk up to the airlock and make it pump plasma into the station

**Comment by monster860** [comment]
its locked so only atmos techs can modify the settings

**Comment by alexkar598** [comment]
But does it show visually

**Pull request merged**
