### PR TITLE
Makes wasps have 50 health not 200

### PR DESCRIPTION
**Pull request by UselessTheremin**
200 is immensely steep especially with it being included in the infection gamemode and it being so fast, begone
:cl:  
tweak: wasps now have 50 health instead of 200
/:cl:

### CODE REVIEW

**Comment by ChesterTheCheesy** [comment]
Bro hands off, it's a jungleland mob, if problem is with infection then make infection wasps have less hp.

**Comment by UselessTheremin** [comment]
> Bro hands off, it's a jungleland mob, if problem is with infection then make infection wasps have less hp.

i can change that when jungleland comes into the equation if need be. its also a xenobio mob tbh

**Comment by ChesterTheCheesy** [comment]
Yes, it's meant to be on-par with watchers, thus matches their HP.

**Comment by SomeguyManperson** [comment]
handling this internally for infection

**Pull request closed without merging**
