### PR TITLE
Removes Moja from code entirely.

### PR DESCRIPTION
**Pull request by azzzertyy**
# Document the changes in your pull request
Reverts [#11949]

# Why is this good for the game?
As described by Alex on the original pr, "Going to get real boring real fast"
And guess what? It really did. Its boring. Its very very very boring.
Not only that, it also breaks some non-offical rules of the github that are stated ad nauseum "No in-game player references" This is one of them. This shouldn't be in the game.
It's an excuse to have a boring ass bus with low effort.
It shouldn't have been added to begin with, and its just annoying. I'm sick of seeing mojas, they take me straight out of the game because haha funny naked man haha!!

Before anyone says, "theyre easy to test with" You can just type "dummy" and it works just the same.

# Testing
None.

# Changelog
Nothing player-facing.

### CODE REVIEW

**Comment by Addust** [comment]
OUR MOJA

**Comment by ThatGuyPhil** [comment]
Well I thought it was funny. Oh well. Gonna miss pushing him into glass tables.

**Comment by ynot01** [comment]
Dummies are invulnerable and other things that make them distinct from humans

**Comment by azzzertyy** [comment]
> Dummies are invulnerable and other things that make them distinct from humans

i can add a test human just named "john" if needed

**Comment by MajManatee** [comment]
Arguably the worst PR ive ever seen

**Comment by dcxgame** [comment]
Improve don't remove, I want a cooler moja with eye lasers

**Comment by Maia-J** [comment]
> Dummies are invulnerable and other things that make them distinct from humans

/mob/living/carbon/human/consistent

**Comment by MajManatee** [comment]
biome said to

**Comment by neeshacark** [comment]
cringe pr

**Comment by Therandomhoboo** [comment]
Good, no player references are allowed. Says so in the guidelines and our staff are against it. 

Seems odd we have this one exception.

**Comment by thegoldencat413** [comment]
A curse upon your crop and your children

**Comment by ynot01** [comment]
Not a player reference, Moja does not play, he administrates

**Comment by MajManatee** [comment]
moja isnt a player, hes a deity
24 hrs

**Comment by Addust** [comment]
a victory has been won for moja

**Pull request closed without merging**
