### PR TITLE
fixes gas mixer for air on asteroid and yogs

### PR DESCRIPTION
**Pull request by Ethan4303**
# Document the changes in your pull request

fixes the gas mix ration on the yogstation and asteroid station airmixers

# Spriting

# Wiki Documentation

# Changelog

:cl:  
bugfix: fixes ratio of air mix
mapping: fixes ratio of air mix mixers mixing air for the mix
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
PR freeze

**Comment by ThatLing** [comment]
Did you test this?

**Comment by JamieD1** [comment]
Waiting on Trimlines

**Review by ToasterBiome — APPROVED** [review]
this shouldn't comically break everything

**Pull request merged**
