### PR TITLE
Security added to round end report

### PR DESCRIPTION
**Pull request by MenacingManatee**
### Intent of your Pull Request
All members of security are added to end round report under traitors, with IC name, byond name, and whether they survived or died
Tested with the warden, HoS, detective, and security officer, both alive and dead. 

TLDR: Just adds a small cool thing to encourage/reward playing security
#### Changelog

:cl:  
rscadd: Security added to round end report 
/:cl:

### CODE REVIEW

**Comment by MenacingManatee** [comment]
Some screenshots:
<details>
<summary>Images</summary>

Living warden
Warden_live

Dead detective, with a traitor
det_dead_plus_tator

Lawyer (aka no security)
no_sec
</details>

**Comment by ThatLing** [comment]
Regarding the last image you posted, it should only be displayed if there are security officers

Also, what's with the stupid border?

**Comment by MenacingManatee** [comment]
I made it match the border everything else had.
Good point on the only display if there's sec, I'll fix that

**Comment by MenacingManatee** [comment]
Fixed

**Comment by MegaEmpirical** [comment]
I like it. Does it emphasize commendations given to them as well might encourage heads to use them.

Also, does it state their department?

**Comment by MenacingManatee** [comment]
> I like it. Does it emphasize commendations given to them as well might encourage heads to use them.
> 
> Also, does it state their department?

Commendations are stated separately and were in the end round report before this PR. I'm not sure how to get their department, but I'll play around with it a bit. If I figure it out I'll add it

**Comment by Xantam-13** [comment]
I like this

**Comment by JamieD1** [comment]
Can we make it match the formatting of traitors ie the spacing is wack,

Or make traitors match this one.

               Just want it lined up.

**Comment by MegaEmpirical** [comment]
Sounds good.

I know commendations are already in, I just thought this would be a cool place to emphasize them.

**Comment by MenacingManatee** [comment]
> Can we make it match the formatting of traitors ie the spacing is wack,
> 
> Or make traitors match this one.
> 
> ```
>            Just want it lined up.
> ```
Fixed
<details>
<summary>Image</summary>
Fixed alignment
fixed_alignment


</details>

**Pull request merged**
