### PR TITLE
Makes the Brig Phys locker display its Switzerland pride

### PR DESCRIPTION
**Pull request by nesisknesis**
# Github documenting your Pull Request

image

# Changelog

:cl:  Identification 
imageadd: The Brig Phys locker now looks more akin to security lockers but with a legal medical twist.   
/:cl:

### CODE REVIEW

**Comment by JamieD1** [comment]
Cross looks a bit chunk?

**Comment by JamieD1** [comment]
Is that red the current red? looks a bit light.

**Comment by nesisknesis** [comment]
> 
> 
> Cross looks a bit chunk?

no

> 
> 
> Is that red the current red? looks a bit light.

yes

**Comment by RetroJunki3** [comment]
you cannot break the Geneva convention
you cannot break the Geneva convention
you cannot break the Geneva convention

literally 1984

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
