### PR TITLE
improves syndicate jungleland

### PR DESCRIPTION
**Pull request by Addust**
# Document the changes in your pull request

- adds an ore refinery (as syndicate lavaland also had one)
- adds a syndicate intercom and gives it fluff text, to be added to the other ones later
- adds gulag quarry stones and drills so they can get materials and shit
- also removes a single, weird tiny fan from the mining base

# Why is this good for the game?
gives them more supplies to do funny shit and keep them from getting bored enough to go to station and get immediately banned

# Testing
i did test it but it was recorded in mkv because obs and i cant be bothered to change it 

# Spriting

# Wiki Documentation

change the picture

# Changelog

:cl:  
rscadd: The Syndicate Jungle Base has been given slight upgrades to improve its capability, including being built atop large underground mineral reserves, having a refinery, actually getting a comms agent intercom, and more!
rscadd: Admins can now also dock shuttles to the base's cargo dock as they can with all the others (no this doesnt mean im making the cargo consoles work)
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
I have personal gripes with this further reducing rough symmetry I tried to maintain, and giving them extra stuff which both manages to be unnecessary and kind of useless (since they don't have an protolathe to really make use of the quarry, nor do they really need it just because the other planetary stations have it).

**Comment by Addust** [comment]
> I have personal gripes with this further reducing rough symmetry I tried to maintain, and giving them extra stuff which both manages to be unnecessary and kind of useless (since they don't have an autolathe to really make use of the quarry, nor do they really need it just because the other planetary stations have it).

the other planetary stations have somewhere you can get minerals (lavaland having the rnd test area, icemoon having the area-where-the-reactor-goes) and they do have an autolathe

will find a fix for the symmetry thing tomorrow tho

**Comment by Marmio64** [comment]
> > I have personal gripes with this further reducing rough symmetry I tried to maintain, and giving them extra stuff which both manages to be unnecessary and kind of useless (since they don't have an autolathe to really make use of the quarry, nor do they really need it just because the other planetary stations have it).
> 
> the other planetary stations have somewhere you can get minerals (lavaland having the rnd test area, icemoon having the area-where-the-reactor-goes) and they do have an autolathe
> 
> will find a fix for the symmetry thing tomorrow tho

yes, i meant protolathe, changed that too late for you to see. But the second point just proves you're only adding the mining site because you added one to the other planetary stations, not because it actually needs it.

**Comment by Addust** [comment]
> Contributor
> ###



> > > I have personal gripes with this further reducing rough symmetry I tried to maintain, and giving them extra stuff which both manages to be unnecessary and kind of useless (since they don't have an autolathe to really make use of the quarry, nor do they really need it just because the other planetary stations have it).
> > 
> > 
> > the other planetary stations have somewhere you can get minerals (lavaland having the rnd test area, icemoon having the area-where-the-reactor-goes) and they do have an autolathe
> > will find a fix for the symmetry thing tomorrow tho
> 
> yes, i meant protolathe, changed that too late for you to see. But the second point just proves you're only adding the mining site because you added one to the other planetary stations, not because it actually needs it

fair point but it does allow them to make more things than their initial supply allows and build a bit more if their materials run out, i'll add a symmetry fix to the PR shortly

**Comment by Addust** [comment]
done
image

**Review by neeshacark — CHANGES_REQUESTED** [review]
image
these two trees look bad when placed adjacent to the acid/lava/whatever due to the roots on one partially going onto the acid and the shadow on both looks unnatural

remove/move them somewhere where they dont overhang weirdly on the acid

**Comment by Addust** [comment]
> image these two trees look bad when placed adjacent to the acid/lava/whatever due to the roots on one partially going onto the acid and the shadow on both looks unnatural
> 
> remove/move them somewhere where they dont overhang weirdly on the acid

done

**Review by neeshacark — APPROVED** [review]

**Pull request merged**
