### PR TITLE
Makes the hos trenchcoat not look weird on lizards

### PR DESCRIPTION
**Pull request by Mqiib**
Hos trenchcoat covers legs but not feet so the jumpsuits turn into digitigrade jumpsuits sometimes and it looks bad becuase the legs get squished. This should fix the fashion.

# Spriting

Technically it's the same sprite with a tweaked name

# Changelog

:cl:  

bugfix: Hos trenchcoat should look better with funny legs

/:cl:

### CODE REVIEW

**Comment by DeadlyBag** [comment]
Another sec powercreep stealth buff

**Comment by Mqiib** [comment]
> Another sec powercreep stealth buff

It's actually a lizard buff, you are now obligated to downvote this pr

**Comment by Skrem7** [comment]
Did this mf'er just observe me playing HoS then immediately left to go fix the super scary coat sprites

**Comment by Mqiib** [comment]
> Did this mf'er just observe me playing HoS then immediately left to go fix the super scary coat sprites

yes

**Review by KillerOrcaCora — APPROVED** [review]
dfnhrrwhsrswh

**Pull request merged**
