### PR TITLE
Disarming someone who's holding an active stun-baton now stuns you

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Disarms shouldn't be a viable strategy for fighting security (or anyone with actual weapons really)

#### Changelog

:cl:  
tweak: disarming someone who's holding an active stun-baton now stuns you
/:cl:

### CODE REVIEW

**Comment by Readystorm546** [comment]
I like this nich but i think it should be a chance and not a guaranteed stun..

**Comment by Amelia0010** [comment]
why?

**Comment by boodaliboo** [comment]
Because when disarming someone you are not realistcly touching the stun part every time so I think it should have like a 40% chance to sub on disarm otherwise most antags won’t have a choice but to go lethal st the sight of sec seeing there evil axts

**Comment by Readystorm546** [comment]
> Because when disarming someone you are not realistcly touching the stun part every time so I think it should have like a 40% chance to sub on disarm otherwise most antags won’t have a choice but to go lethal st the sight of sec seeing there evil axts

Thats pretty much what i was gonna say

**Review by ynot01 — CHANGES_REQUESTED** [review]
should be random imo, don't invalidate disarms altogether, just make them worse

**Comment by CMOisLing** [comment]
Stun batons should stun you if you put them away without turning them off. So you can’t whip them out so fast if you start getting disarmed.

**Comment by Ratvar** [comment]
There's no message to show people why they're being stunned, so they'll think enemy hit them first?
Every assistant crafts stunprod to become OP beast?
Makes people with **actual weapons** like eswords, spears, armblades and etc even more useless because their enemy kills them in 1 hit and because they can make a stunprod?
This doesn't fix any issues, just makes stunprod even more of a king. Everyone can make one. Powergamers will.

**Comment by ThatLing** [comment]
this isn't the solution

**Comment by boodaliboo** [comment]
thisbad

**Comment by Moja10** [comment]
Instead of things like this, consider /tg/'s disarm rework instead.

**Pull request closed without merging**
