### PR TITLE
Megafauna rebalance

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

I believe that all mining rewards from megafauna should be primarily used on Lavaland and used to help mining and kill more megafauna, or instead provide a fun and unique experience such as the anomalous crystal. Being able to turn into an ash drake or blood crawl but with vomit are none of these.
I've turned the vomit crawl into a 1% chance and removed the ash drake transformation.

# Wiki Documentation
No more ash drake transformation.
Vomit crawl is only a 1% chance.

# Changelog
:cl:  
tweak: Vomit crawl drop from bubblegum is now only a 1% chance
rscdel: No more ash drake transformation
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
Waiting for the comments from miner mains who have megafauna killing down to a formula so it is a walk through the park to get their gamer loot for validhunting.

**Comment by Darkstick** [comment]
Don't remove fun things please

**Comment by Simplehorror** [comment]
> Don't remove fun things please

THESE REWARDS ARE ONLY FUN FOR YOU. Not for the person you're validhunting, not for security and not certainly for anyone else involved in the round. The anomalous crystal is fun and even brings ghosts back into the round.

**Comment by Bibby0110** [comment]
> > Don't remove fun things please
> 
> THESE REWARDS ARE ONLY FUN FOR YOU. Not for the person you're validhunting, not for security and not certainly for anyone else involved in the round. The anomalous crystal is fun and even brings ghosts back into the round.

Sounds like you’re having a rules issue.
Make a player complaint

**Comment by Spacemanspark** [comment]
I think you're overwhelming the playerbase by pushing a bunch of major balance changes all at once. Regardless of what I or you may think about said changes, it would be much better to handle it slower so people can digest these and form proper thoughts on them, rather than eliciting a knee-jerk reaction from the majority of users looking on as this happens. 

It'll also allow you to handle feedback and opinions in a far less stressful manner, as you won't be dogpiled all at once with several PRs worth of comment critisicm and anger.

**Comment by tattax** [comment]
bro really let the flashbang nerf affect him hardcore

**Comment by Simplehorror** [comment]
> bro really let the flashbang nerf affect him hardcore

im adding a button that lets security call erts

**Comment by Simplehorror** [comment]
> I think you're overwhelming the playerbase by pushing a bunch of major balance changes all at once. Regardless of what I or you may think about said changes, it would be much better to handle it slower so people can digest these and form proper thoughts on them, rather than eliciting a knee-jerk reaction from the majority of users looking on as this happens.
> 
> It'll also allow you to handle feedback and opinions in a far less stressful manner, as you won't be dogpiled all at once with several PRs worth of comment critisicm and anger.

I don't have a lot of time left

**Comment by Spacemanspark** [comment]
Can you elaborate on what that means?  Don't have a lot of time left to play on the server? Don't have a lot of time left today before heading off to sleep? Don't have a lot of time before the man holding you at gunpoint to make these PRs performs an instant brain splattering surgery on you?

**Comment by Simplehorror** [comment]
> Can you elaborate on what that means? Don't have a lot of time left to play on the server? Don't have a lot of time left today before heading off to sleep? Don't have a lot of time before the man holding you at gunpoint to make these PRs performs an instant brain splattering surgery on you?

D. All of the above

**Comment by Spacemanspark** [comment]
Well... dunno what your end goal here is, but good luck. I don't think this is a wise way of handling any of this, but to each their own.

**Comment by bruhlookatthisdood** [comment]
instead of removing dragon transformation maybe balance the dragon you transform into?

**Comment by LazennG** [comment]
fun is subjective but how are drake transformation and vomitcrawling not unique to you

**Comment by tattax** [comment]
> > Don't remove fun things please
> 
> THESE REWARDS ARE ONLY FUN FOR YOU. Not for the person you're validhunting, not for security and not certainly for anyone else involved in the round. The anomalous crystal is fun and even brings ghosts back into the round.

how is  vomit crawl more validhunting than the kill list

**Comment by Simplehorror** [comment]
> fun is subjective but how are drake transformation and vomitcrawling not unique to you

what fun do they provide other players

**Comment by LazennG** [comment]
> > fun is subjective but how are drake transformation and vomitcrawling not unique to you
> 
> what fun do they provide other players

the fun of a much weaker megafauna to fight if one happens. i can't talk about the stomach in terms of involvement for other players besides it being funny when you clean up a vomit puddle and a miner is stunned on that same spot, but the drake form helps when crossing lava and breaking into ruins while the vomitcrawl cuts down on the time it takes to get back to mining base as well as being a decent escape tool if a pool is pre emptively made before aggroing a megafauna

**Comment by Simplehorror** [comment]
> > > fun is subjective but how are drake transformation and vomitcrawling not unique to you
> > 
> > 
> > what fun do they provide other players
> 
> the fun of a much weaker megafauna to fight if one happens. i can't talk about the stomach in terms of involvement for other players besides it being funny when you clean up a vomit puddle and a miner is stunned on that same spot, but the drake form helps when crossing lava and breaking into ruins while the vomitcrawl cuts down on the time it takes to get back to mining base as well as being a decent escape tool if a pool is pre emptively made before aggroing a megafauna

Ok so the fun in being a megafauna for other players is that they get to fight another fucking megafauna on station and also it's intelligent, fucking brilliant logic

**Comment by LazennG** [comment]
> 
my genius is overwhelming, i know.
i could say this is the same logic you're applying by keeping things like the blood contract and mayhem bottle in since i'm assuming you're thinking the 'fun for other players' applies in making players fight each other too

**Comment by Simplehorror** [comment]
> > 
> 
> my genius is overwhelming, i know. i could say this is the same logic you're applying by keeping things like the blood contract and mayhem bottle in since i'm assuming you're thinking the 'fun for other players' applies in making players fight each other too

Be careful!

**Comment by JamieD1** [comment]
@SomeguyManperson

**Comment by Simplehorror** [comment]
Can I get a reason

**Comment by N3D6** [comment]
Because this change is bad

**Pull request closed without merging**
