### PR TITLE
Rework of Omegastation

### PR DESCRIPTION
**Pull request by redmoogle**
### MAP
**NEW**
after

**OLD**
before

**DIFF**
diff

I intend to modernize the map. I added a couple of things
A maint storage above science that has: 2 air cans, 2 scrubbers, 1 water tank, and 1 welding tank
image

moved engineering hardsuits and gloves
image

Added HOS & CE Offices
image
image

Added deathsposals
image

Changed up the layout of engineering
image

Medbay Storage is slightly bigger
image

Added A small resting room in maint
image

Bar/Kitchen/Atrium Rework
image

I feel confident enough to fully open this. Still accepting ideas

#### Changelog

:cl:  
tweak: NT has sent their finest engineers to fix omegastation
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
Idk how i feel about this, most of the changes you made are not because the map is "old". It's because the map is different, no disposals, no head offices, all intended for a bit of a different map, a unique map. 
Correct me if I'm wrong here but i just don't want omega to become "box but small".
The piping changes and storages are nice though.

**Comment by redmoogle** [comment]
> 
> 
> Idk how i feel about this, most of the changes you made are not because the map is "old". It's because the map is different, no disposals, no head offices, all intended for a bit of a different map, a unique map.
> Correct me if I'm wrong here but i just don't want omega to become "box but small".
> The piping changes and storages are nice though.

there are still some old relics, like sulfuric acid in sci lab

I only added 2 more headslots that are semi-important and I dont plan to add more because 1 space, also they arent really important ~~so it ce but shh~~

I mean having no disposals is a fair point but people got pissy over it

part of my goal is to just make it more bearable as a map but people are probably going to vote for YogStation/box anyways /shrug

**Comment by Hopekz** [comment]
> Idk how i feel about this

It's ok we don't play Omega anyway so I'm pretty sure no-one would even notice if you just made a giant hole in the middle of omega until months later when someone map-dives for the next Omega edit.

**Comment by maxion12345** [comment]
I liked omega because it had a nice vibe and the small area was just perfect for those 30 pop rounds. I'd love to see it modernized with all roles implemented

**Comment by redmoogle** [comment]
@wejengin2 @Hopekz @maxion12345 Rereview as I've worked on it quite alot

**Comment by redmoogle** [comment]
I'll try to de-emptyfie the atrium but wanna see if the shape/setup is good

**Comment by patpol4** [comment]
Eeh, not a fan of the new hallway in the bar, the swap is weird too, bartender is now shoved to the side with not a lot space that accessible to customers. Since the focus seems to be on the long table in the north. Here's an idea.
Move the table horizontally between chef and bartender, put some sort of recreation area in the long vertical space. Boxing ring, theater seats, gambling machines, card table, these sorts of things.

Just dont follow this advice word to word, just fill it with something haha

**Comment by redmoogle** [comment]
> 
> 
> Eeh, not a fan of the new hallway in the bar, the swap is weird too, bartender is now shoved to the side with not a lot space that accessible to customers. Since the focus seems to be on the long table in the north. Here's an idea.
> Move the table horizontally between chef and bartender, put some sort of recreation area in the long vertical space. Boxing ring, theater seats, gambling machines, card table, these sorts of things.
> 
> Just dont follow this advice word to word, just fill it with something haha

Working on that part, I'm probably gonna move theater to face up, and remove the lower doors, and add doors to the left

**Comment by patpol4** [comment]
Just remember the lower entry is great because it's a straight line from arrivals, very central spot

**Comment by redmoogle** [comment]
image

@wejengin2

**Comment by redmoogle** [comment]
oh whoops I accidentatly left that other booze storage in

**Comment by patpol4** [comment]
Looks way better, i think you should expand the vertical chef table so its not just 2 tiles

**Review by patpol4 — CHANGES_REQUESTED** [review]
Alright let's do this,
1. Really not a fan of adding disposals, is it tested? Does mailing packages work, did you set the id's for the junctions? 
2. Is that the captains antique gun in his locker? He has a display case already, why have two?
3. I couldn't find the button for bridge shutters, i might be blind
4. Add some thin windows and windoors around here so its separated, looks better that way.
chrome_oMUEa25wtr
5.Either add some more sleep themed items or maint loot spawners or just some trash, too empty in here. Like the idea though.
chrome_4qrnnY2yGM
6.Fire alarm in a window
chrome_JF9anTmK7s
7.This part is nice but a bit barebones, try adding decals so it fits the omega style, also, firelocks
chrome_cSAwBmnC5d
chrome_CANNwbxdha
8. HoS shouldnt have windows here for balance reasons, make it walls. That cave is there so people can sneak into sec from the outside somehow, having windows defeats the purpose, same goes for the cave, please keep it closed.
chrome_7vTvMVNYUL.
Will review the bar area in a bit, super tired right now but i wanted to at least start this

**Comment by redmoogle** [comment]
Only thing I have to say back is that this is designed with no mailing system, it just goes directly to the recycler

**Review by patpol4 — CHANGES_REQUESTED** [review]
Part 2 of review:
Did you check for map errors and load up the map? You go into admin panel>current logs>map errors, download that and check if your pipes are correct, just ignore the apc errors.
1. Firelocks here, i know it looks ugly but its technically a different room: 
JnDi3na87e
2. I don't know if blocking off the top with access is a good idea, lowers bar traffic and closes it off, techfab is not that big of a deal really. I would open it back up again with public glass airlocks.
chrome_Ht8L1hn2Vy
3. This should be a plating under the airlock, also firelocks: 
chrome_5ks1p2SYKX
4. Hydroponics needs a windoor over the table to close it off

I probably missed some problems since this is a big one but it will probably come out when we merge it. Great work man.

**Comment by redmoogle** [comment]
That should address most of that, I cant find the mapping error logs, maint doors dont have firelocks but I placed them where some should have been. Put atrium doors by the tech fab, and hydro has its doors now

**Comment by patpol4** [comment]
Alright all that is left right now is the pipenet mapping errors, pinged you on discord about it

**Comment by redmoogle** [comment]
> 
> 
> Alright all that is left right now is the pipenet mapping errors, pinged you on discord about it

Should be all fixed now

**Review by patpol4 — APPROVED** [review]
Map part of this is fine, now it just needs a coder to look at the two tiny code changes and nod their head

**Review by JamieD1 — APPROVED** [review]
Weje Says yes. *nod head*

**Pull request merged**
