### PR TITLE
Add at least a hundred carps to the white whale holy grail syndikit

### PR DESCRIPTION
**Pull request by 00ze-cyclone**
# Dancingcarp Document the changes in your pull request Dancingcarp

Right now the white whale holy grail kit is full of neat unique items but it's both rather weak for 20 TC and only has 5 space carps despite having the gimmick of a suit that making you friend with space carps.
The solution of course was adding more carps.

Added one space carp clusterbuster grenade for a tide of carps in one click as a panic button and 3 additional regular carp grenades so you can have more friends.
The kit now has a 3 uses carp signal to trigger a space carp migration so you can take advantage of the fact you have a spacesuit that protect you from carps by calling them to he surrounding of the station to retreat there.
Also add one dehydrated carp plush because sometimes you need a true friend in the uncaring void of space.

Because all of those carps will need a backpack to store them, the magspear quiver now goes in a pocket like jobs satchels and the trident fit on the belt, you fit your speargun on the exosuit slot like before.

Since it now has a decent amount of carps the weight got reducedd to 1.
# Dancingcarpfast Wiki Documentation Dancingcarpfast

White Whale Holy Grail kit now has a weight of 1 and contain:
-Kinetic Speargun
-Magspear Quiver
-Carp Space Suit
-Carp Mask
-Trident
-Invasion of the Space Carps Clusterbuster Grenade
-4 Carp Delivery Grenades
-Carp Signal
-Dehydrated Space Carp

# Youcantescape Changelog Youcantescape

Yourdecisionsareultimatelyunimportant

:cl:  Carp'sie
rscadd: Added a carp signal to the white whale syndikit and at least 100 space carps
bugfix: fixed lack of space carps in the white whale syndikit
tweak: White grail syndikit weight reduced to 1 from 2, trident canfit on belt and magspear quiver fit on pocket slots
/:cl:

### CODE REVIEW

**Comment by UltraBigRat** [comment]
ludicrously based pr, now just bee needs to be fixed.

**Comment by Marmio64** [comment]
cluster buster carp with 30 carp sounds overkill, but otherwise its cool

**Comment by ChuChu42** [comment]
last time i had this i was fucked because of the low amount of carps it had, and being unable to wear a backpack to carry stuff
thank you god for fixing this

**Review by ToasterBiome — APPROVED** [review]
map ok

**Comment by JamieD1** [comment]
Thats alot of carp

**Pull request merged**
