### PR TITLE
neurotoxin and beepsky smash no longer stun

### PR DESCRIPTION
**Pull request by ghost**
no
#### Changelog

:cl:  
tweak: Beepsky smash and neurotoxin do not work as stunning chemicals, anymore.
/:cl:

### CODE REVIEW

**Comment by Ratvar** [comment]
Yey, good change.
Now make water+potassium not stun on ingest

**Comment by ShattForte** [comment]
I'm 100% for this PR. If you want instant stun chem memes, you should need an emag.

**Review by ThatLing — APPROVED** [review]

**Comment by ghost** [comment]
if you get hit with a cryostabilized syringe gun shot then it's enough energy investment to make it acceptable as a stun considering bluespace syringes come first and are even deadlier, kojuh

**Comment by jcatjmeow** [comment]
Why did the title change as i was reading it
...
Oh its so that the maintainers merge it without looking at it
Carry on

**Comment by ghost** [comment]
i figured out how to make it stun on ingest but i didn't want to bother anyway so

**Comment by B1gb3ast** [comment]
>           I'm 100% for this PR. If you want instant stun chem memes, you should need an emag.

Then actually give us an instant stun chem for emagging the fucking dispenser because it doesn't.

**Comment by ghost** [comment]
@b1gb3ast

Zombie powder is made from carpotoxin, morphine and copper, and all of those are available in an emagged dispenser

**Comment by ThatLing** [comment]
stop changing the title or i will just close it

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
