### PR TITLE
Remove bias from gamemode antagonist picking

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

BYOND's pick has a bias due to the method it uses, so I reimplemented it in DM without the bias.

# Changelog

:cl:  
bugfix: Remove some bias from gamemode antagonist picking
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
can you elaborate on this "bias" with sources? this is not descriptive

**Comment by Simplehorror** [comment]
> can you elaborate on this "bias" with sources? this is not descriptive

image

**Comment by ynot01** [comment]
> image

Wow this is totally descriptive and not just a screenshot of assembly ripped from binary

Can you tell me, in words, why Mersenne Twister (which I assume is the focus) is bad enough that it warrants a new 'unbiased' function to be used specifically with picking antag candidates

I could not find any references through brief research why MT is bad for this besides being "not cryptographically secure" which is not a concern

**Comment by Simplehorror** [comment]
> > image
> 
> Wow this is totally descriptive and not just a screenshot of assembly ripped from binary
> 
> Can you tell me, in words, why Mersenne Twister (which I assume is the focus) is bad enough that it warrants a new 'unbiased' function to be used specifically with picking antag candidates
> 
> I could not find any references through brief research why MT is bad for this besides being "not cryptographically secure" which is not a concern

Mersenne twister isn't the issue here, read the code. If you don't understand it, wait until someone who knows how to program can review instead.

**Comment by CMOisLing** [comment]
> Mersenne twister isn't the issue here, read the code. If you don't understand it, wait until someone who knows how to program can review instead.

Just show us a comparison. Do 10000 generated values for each and compare the standard distribution of them.

**Comment by Bibby0110** [comment]
Don’t be rude to the other contributors, absolutely nobody here is expected to understand decompiled BYOND code

**Comment by Simplehorror** [comment]
> Don’t be rude to the other contributors, absolutely nobody here is expected to understand decompiled BYOND code

it's not being rude, I just don't like it when people talk about something they know nothing about

**Pull request closed without merging**
