### PR TITLE
Adds The Roost from Animal Crossing (New Horizons ver.) to jukebox

### PR DESCRIPTION
**Pull request by Aquizit**
# Document the changes in your pull request

What the title says. This was originally included in my First Class Shuttle map design but it can be it's own thing as I see if I want to revisit that.

https://youtu.be/ZD1HxnXU-bk

# Changelog

:cl:  
soundadd: Adds The Roost (New Horizons ver.) to Jukebox
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
your link wasn't working, so i fixed it

new horizons and new leaf versions are nicer if you ask me, smash version has too much energy

**Comment by Aquizit** [comment]
New horizons is really really quiet from my experience. I’d be willing to see which people prefer between smash and new leaf though. And thanks for the link fix.

**Comment by Aquizit** [comment]
I'll come back to this (probably).

**Comment by Aquizit** [comment]
Alright changed to New Horizons.

**Review by MajManatee — APPROVED** [review]
musik

**Review by JamieD1 — APPROVED** [review]

**Comment by JamieD1** [comment]
WOAH WOAH WOAH WOAH WOAH

**Pull request merged**
