### PR TITLE
Revert "Fixed and Tweaked Some Stuff With the Crew Console Interface"

### PR DESCRIPTION
**Pull request by JamieD1**
Reverts yogstation13/Yogstation#11570

### CODE REVIEW

**Comment by JamieD1** [comment]
Test merge only

**Comment by Tipy1802** [comment]
Why?

**Comment by nmajask** [comment]
So the problem seams to be that while I was trying to stop the console from getting the map assets, I accidentally stopped it from sending ANY data to tgui. I should have a PR with the fix soon.

**Comment by nmajask** [comment]
I made a fix for it #11615

**Pull request closed without merging**
