### PR TITLE
Fixes Quiet Mode

### LINKED ISSUE #2966: quiet mode doessnt work
[Round ID]: # (19040)
[Reproduction]: # I have quiet mode on but multiple times I end up either antag or an antag's target)

### PR DESCRIPTION
**Pull request by Altoids1**
Fixes #2966

#### Changelog

:cl:  Altoids
bugfix: Quiet Mode has been fixed!
/:cl:

### CODE REVIEW

**Review by Amelia0010 — DISMISSED** [review]
Could you remove the yogs code in code/game/gamodes/game_mode.dm? 

https://github.com/yogstation13/Yogstation-TG/blob/107e79952138c849f42ebedc55b51168ed894fc5/code/game/gamemodes/game_mode.dm#L364

**Comment by GenericDM** [comment]
thank you for doing what i could not

**Comment by ThatLing** [comment]
> 
> 
> thank you for doing what i could not

thank you for doing what i, ling and nich could not
FTFY

**Comment by Altoids1** [comment]
> Could you remove the yogs code in code/game/gamodes/game_mode.dm?

Yeah I did this commit and only *then* noticed all the Yogcode sitting around below my patchwork. Will work on it.

**Comment by Altoids1** [comment]
Managed to distribute antags properly without exploding or runtiming. Good enough for a merge.

**Pull request merged**
