### PR TITLE
doubles the effective healing speed of cryoxadone

### PR DESCRIPTION
**Pull request by SomeguyManperson**
# Github documenting your Pull Request

nobody uses cryo anyways lmao

# Wiki Documentation

cryox healing effective maximum 3 -> 6

# Changelog

:cl:  
tweak: cryoxadone healing increased from a maximum of 3 to a maximum of 6
/:cl:

### CODE REVIEW

**Comment by TheMommaDragon** [comment]
Pyroxadone should also get a boost if we're doing that.

**Comment by SomeguyManperson** [comment]
pyroxadone already heals nasty fast getting up to a base of 10 points at the highest temperature + on fire, cryox is fairly slow for something you'll generally only use when in a cryotube which prevents you from doing anything while it's actively healing

**Comment by maxion12345** [comment]
wheres that chemist guy that makes the super cyro mix when you need him

**Comment by Reed0506** [comment]
image

**Review by adamsong — APPROVED** [review]

**Comment by Firewolf34** [comment]
Will cryo actually be used again?? find out more on the next episode of Yogstation PR push

**Pull request merged**
