### PR TITLE
changes the description of one of toxolyisis threshholds to be more apparent what it does

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
current the descritption makes it seem like it heals you not feed you
#### Changelog

:cl:  
tweak: tweaked a symptoms decsription
🆑

### CODE REVIEW

**Comment by Mqiib** [comment]
should be "feed" not "feeds"

**Comment by DerelictDrone** [comment]
"Nourish" works perfectly fine in this context, I don't see how you got the implication that "nourish" means "heal"
image

**Comment by boodaliboo** [comment]
when i think of nourish i think of it in the context of healing someone from a flu for example not eating

**Comment by ghost** [comment]
since fucking when have you ever nourished someone to cure their flu

**Comment by boodaliboo** [comment]
> since fucking when have you ever nourished someone to cure their flu

i have heard mothers for example nourishing there child back to health in books before

**Pull request merged**
