### PR TITLE
Resprites the power fist because nothing is better then losing your weapon to the grey floors down below

### PR DESCRIPTION
**Pull request by KillerOrcaCora**
how was I supposed to ever know the reference it could have literally been anything. Resprites the powerfist to actually look like its reference. 

# Spriting
image

Capture
***Flash***
image
***Flash*
*Flash*
*Flash***

but we already have a powerfist! the powerfist at home - 
image

# Wiki Documentation
are they still alive? let's give them this just incase. 
thepowerfist

# Changelog

:cl:  

imageadd: Resprites that one traitor item you never use because it phases into the traitor panel color like a Vietnam solider.  

/:cl:

### CODE REVIEW

**Review by Moltijoe — APPROVED** [review]
Very nice, i'm not an art, but it makes my eyes give my brain happy

**Comment by Simplehorror** [comment]
i thought you died

**Comment by Simplehorror** [comment]
also i like the old powerfist sprite

**Comment by MajManatee** [comment]
a morbillion times better

**Comment by Simplehorror** [comment]
none of you even used this item but me so why are we shitting on a sprite you never see

**Comment by cowbot92** [comment]
Looks like a powerful fist, good job orca.

**Comment by Hopekz** [comment]
Tbh they both look like guns to me but the old one wasn't any better

**Comment by LazennG** [comment]
as someone who uses power fist this new sprite is much cooler

**Comment by RG4ORDR** [comment]
Oh yeah time for powerfist variations

**Review by cuackles — APPROVED** [review]
very good, let the fisting comence

**Comment by KillerOrcaCora** [comment]
I’m dead Lmao

**Pull request merged**
