### PR TITLE
Thrumboat (Thrumbo goat)

### PR DESCRIPTION
**Pull request by Chubbygummibear**
# Document the changes in your pull request

@cuackles made a sprite for a Thrumbo so I made the code. It's another goat skin that deals a bit more damage (10-15 damage per swing instead of 1-2 :^) ). The odds of seeing this around are low but never 0. This won't spawn in the kitchen because it would MOST LIKELY murder the chef on first encounter

image
image
(I fixed the lowercase "a", eat my ass Chester)
image

Maybe in the future we'll flesh it out to have thrumbo wool or the horn on its head to be a carvable weapon or something.

# Wiki Documentation

I don't think there's an extensive list of goat reskins that i'm aware of

# Changelog

:cl:  
rscadd: Thrumbo goat  
imageadd: Thrumbo goat
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Now admins can bus being a storyteller

**Comment by Chubbygummibear** [comment]
> Now admins can bus being a storyteller

Cencom Announcment:
Thrumbo migration

**Comment by cuackles** [comment]
Updated look

**Review by nesisknesis — APPROVED** [review]

**Comment by JamieD1** [comment]
@grimm-hollowknight Maintainer check for code was not given.

**Pull request merged**
