### PR TITLE
Adds new alt-titles for roboticists: Ripperdoc & Chrome Shaman

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

image

# Why is this good for the game?

Chop 'em up.

# Testing

yes

# Changelog

:cl:  
rscadd: Adds new alt-job titles to roboticists

/:cl:

### CODE REVIEW

**Comment by 00ze-cyclone** [comment]
I feel like 2 jobs having the same title would cause a lot of confusion on who is what.

**Comment by cowbot92** [comment]
> I feel like 2 jobs having the same title would cause a lot of confusion on who is what.

yeah I just made it for robos

**Comment by Moggram** [comment]
I love this and i think you for it.

also the "Why is this good for the game?" part, should be "Start rip'n Doc."

**Comment by ofscarletdreams** [comment]
behold the google chrome shaman

**Comment by MajManatee** [comment]
I think chrome shaman sounds dumb as hell but ripperdoc is dope.

**Comment by Moggram** [comment]
> I think chrome shaman sounds dumb as hell but ripperdoc is dope.

its a Voodoo Boys thing. It could also be used for the chap in insted.

**Review by Moltijoe — APPROVED** [review]

**Comment by azzzertyy** [comment]
:nerd_face: uhm the roboticist is called the "Ripper" robotics is called "Ripperdoc"

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
