### PR TITLE
pirate selling parrots and hostages are worth more

### PR DESCRIPTION
**Pull request by boodaliboo**
### Intent of your Pull Request
changed price of parrots to 5000
and hostages to 8000
#### Changelog

:cl:  
tweak: tweaked prices
/:cl:

### CODE REVIEW

**Comment by Xoxeyos** [comment]
Could you add it so cuffed prisoners don't get blasted as soon as their near the pirate's ship?

**Comment by boodaliboo** [comment]
> Could you add it so cuffed prisoners don't get blasted as soon as their near the pirate's ship?

i have no clue how to go about doing that i apologize

**Review by SomeguyManperson — CHANGES_REQUESTED** [review]
hostages have price changes in their find_price or whatever proc, you'll want to change those to reflect this or it won't do anything

**Comment by boodaliboo** [comment]
> hostages have price changes in their find_price or whatever proc, you'll want to change those to reflect this or it won't do anything

will do

**Review by SomeguyManperson — APPROVED** [review]

**Comment by Hopekz** [comment]
I let this marinate. Feedback for it seems good

**Pull request merged**
