### PR TITLE
Gives Signal Techs access to Server Room's APC & Air Alarm

### LINKED ISSUE #4605: Signal Tech - No Server Room APC and Air Alarm Access
Issue reported from  Round ID: 21599 (Yogstation 13)

Reporting client version: 512

Signal Tech's do not have access to the server room APC or Air Alarm. I am under the understanding that they are supposed to.

### PR DESCRIPTION
**Pull request by Altoids1**
The main thing is that this allows the Signal Tech to disable the immense spesswind that can sometimes occur in the server room, which can lethally blow around people that lack magboots (such as the Signal Tech).

Fixes #4605.

#### Changelog
:cl:  Altoids
tweak: Signal Technicians now have access to the APC and Air-alarm in the server room!
/:cl:

### CODE REVIEW

**Comment by Jc1469** [comment]
getting around the server room is 10% of the fun of signal tech 
that and giving them atmos alarm access is kinda pointless because if there's a major atmos issue there's either fucked pipes or a gaping hole in a wall, two things signal tech can't easily fix without a space suit, at which point you may aswell get an engineer tbh

**Comment by Altoids1** [comment]
> getting around the server room is 10% of the fun of signal tech
> that and giving them atmos alarm access is kinda pointless because if there's a major atmos issue there's either fucked pipes or a gaping hole in a wall, two things signal tech can't easily fix without a space suit, at which point you may aswell get an engineer tbh

I like how the second part of your argument is an argument against the first part. #JcatCriticizesJcat

**Comment by Jc1469** [comment]
As far as I can tell both are simply against your reason for giving them atmos alarm access. 
No point, and being blown all over the place is the fun part of going into the server room.
And again, even if they have access to that alarm, if there's ever a major reason for it to be required they can't do shit even with access to the alarm.  Might aswell just give signal tech all access and make it a job that does nothing but recover bodies with a blue beret.

**Comment by ThatLing** [comment]
>and being blown all over the place is the fun part of going into the server room.  

Just don't disable it then? lmao what is your argument here

**Comment by Jc1469** [comment]
they didnt have access to the air alarm and they shouldn't because there's no point.
how is it hard to grasp?

**Review by monster860 — APPROVED** [review]

**Pull request merged**
