### PR TITLE
Give heretics a free blade to start with

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Heretics having to get very niche and obscure items to begin playing the game is a pain point for even veteran players so I made it that heretics get their specific blade to begin with.
# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: Give heretics a free blade to start with
/:cl:

### CODE REVIEW

**Comment by KillerOrcaCora** [comment]
Just so you know I am not mocking you this is actually something I wanted god bless your soul heretic is so shit

**Comment by forhiti** [comment]
Good shit

**Review by ReddicusDragon — APPROVED** [review]
holy shit a good change from Simplehorror? I give you a lot of shit but I genuinely have seen some pretty good ideas come from you. Code looks good, idea is sound, makes the game more fun too.

**Comment by KillerOrcaCora** [comment]
It was my idea…;-;

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
