### PR TITLE
makes honk staff bullets ricochet

### PR DESCRIPTION
**Pull request by Amelia0010**
### Intent of your Pull Request

Makes the honkstaff ricochet instead of going through walls. It loses 5 range every time it ricochets and has a range of 200, so assuming that it doesn't travel on any tiles but just ricochets, it can ricochet a maximum of 40 times.

#### Changelog

:cl:  
tweak: honk staff now ricochets around.  
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
>:(

**Comment by Kmc2000** [comment]
very cool

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Make it do an annoying sound on every bounce

**Comment by Amelia0010** [comment]
it already makes the airhorn sound every time it hits anything, including walls & objects

**Review by Altoids1 — APPROVED** [review]

**Pull request merged**
