### PR TITLE
Add a new hack wire for advanced airlock controller that can toggle cycle by pulsing

### PR DESCRIPTION
**Pull request by warface1234455**
## Why you may ask?
This is just for remotely control from distance that's it. 
# Document the changes in your pull request
Add a new hack wire for advanced airlock controller that can toggle cycle by pulsing
Reduced dumb wire to 1

# Wiki Documentation
Add a new hack wire for advanced airlock controller that can toggle cycle by pulsing
Reduced dumb wire to 1
# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscadd: Add a new hack wire for advanced airlock controller that can toggle cycle by pulsing
tweak: Reduced dumb wire to 1
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
wrong button

**Comment by ReddicusDragon** [comment]
is this literally just a wire to make airlocks able to deny everyone entry? What does this PR do, define what you mean by cycling

**Comment by ShoziOffical** [comment]
> is this literally just a wire to make airlocks able to deny everyone entry? What does this PR do, define what you mean by cycling

No, this pr basically just adds a new wire that toggle cycle between exterior and interior

**Comment by ReddicusDragon** [comment]
have you tested this pr

**Comment by ShoziOffical** [comment]
> have you tested this pr

Of course

**Review by ReddicusDragon — APPROVED** [review]
if this breaks the game gitban he for saying he tested it, other than that I see no issues

**Comment by ShoziOffical** [comment]
> if this breaks the game gitban he for saying he tested it, other than that I see no issues

hahahahahah no

**Comment by ReddicusDragon** [comment]
> > if this breaks the game gitban he for saying he tested it, other than that I see no issues
> 
> hahahahahah no

it's a joke lmao, I can say with 80% certainty that this won't break it. I don't have the time to really test it on my own atm

**Comment by ShoziOffical** [comment]
> > > if this breaks the game gitban he for saying he tested it, other than that I see no issues
> > 
> > 
> > hahahahahah no
> 
> it's a joke lmao, I can say with 80% certainty that this won't break it. I don't have the time to really test it on my own atm

yeah i know its a job that is why i laughed

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
