### PR TITLE
makes the holodeck 10x10 so that i can play ACTUAL CHESS

### PR DESCRIPTION
**Pull request by athena413**
### Intent of your Pull Request

every room in the holodeck is 10x10 and the entire holodeck is 10x10 now so i can play space chess

not done yet i need to make the holodecks themselves be bigger now

images uhhhhh:
image
image
image
image
image
image
image
image
image
(burntest)
image
image
image
image
image
image
image
image
image
image
image
image

#### Changelog

:cl: 
tweak: holodeck big now
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
I do love this. But (and maybe this is out of the scope of the pr) I'd like proper chess pieces too. The spacechess ones look really ugly imo.

I also like the spare queens you have.

**Comment by Readystorm546** [comment]
> I do love this. But (and maybe this is out of the scope of the pr) I'd like proper chess pieces too. The spacechess ones look really ugly imo.
> 
> I also like the spare queens you have.

Honestly exactly what I was thinking too

**Comment by UselessTheremin** [comment]
this is nice, but I really want you to actually expand on all the areas. IMO just having chairs outside the medieval area really kills the vibe. also holy shit that atmos burn test is reeeallly gonna hurt, malf ai's dream and im all for it ;)

**Comment by patpol4** [comment]
Expand the snow place a bit, its really weird now, also ping me when this is finished

**Comment by Marmio64** [comment]
yes, proper pieces like jcat said, i have no idea which piece is what and having to examine each time sucks.

**Comment by jcatjmeow** [comment]
At the very least:
King should wear a crown
Bishops should be chaps in robes
Rooks should be...something else

In fact I might want to pr this

**Comment by athena413** [comment]
got a better thing to work on now that i can actually use private servers now

**Pull request closed without merging**
