### PR TITLE
decolonizes all of yogstation

### PR DESCRIPTION
**Pull request by maxion12345**
# If this is your first PR, or not, take the time to read our CONTRIBUTING.md file! You can see it here: https://github.com/yogstation13/Yogstation/blob/master/.github/CONTRIBUTING.md

# Document the changes in your pull request

takes every instance of armour and replaces with armor like god intended      
# Wiki Documentation

Remove this text and write all information regarding your changes that should be known and documented through the Yogstation Wiki. 
Important documentation information includes, but is not limited to: any numerical values that have been changed, any images that have to be updated, names of specific pages that will be impacted by your changes. 

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
bugfix: removed the british
/:cl:

### CODE REVIEW

**Comment by Mqiib** [comment]
based and americapilled

**Comment by Hopekz** [comment]
I had no idea we had this many instances of it. 
I ran it into it once in a while didn't know there was close to 300

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Leaving this for HD, see following from our GitHub guidelines:

image

**Comment by ynot01** [comment]
turdis waking up one day and deciding to fail forno reason

**Comment by maxion12345** [comment]
there isn't even an armor type called that

**Comment by SomeguyManperson** [comment]
Don't forget analyse and defence/offence

**Pull request closed without merging**
