### PR TITLE
gutting flashes so that they're actually personal defense weapons and not the best stun in the game attempt 2

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
# Hello jamied12! I'd like to ask you to read this section before closing this PR. This change is for handheld flashes, the melee weapon. This does NOT touch flashbangs, the ranged stun grenades. They will work how they currently do.

This affects NONE of the following:
Mounted flashes
Portable flashes

All this does is make it so handheld flashes disarm instead of hardstunning for 12 seconds. This is still good as flashes ignore shields, but it's no longer win in 1 click territory, and 'have the counter or you lose invariably' combat is not fun and being removed.
Makes the blinding stronger so that the box they come in that says they can cause blindness isn't false advertisement, also makes it possible to actually blind your attackers to get away. Being temporarily nearsighted or permanently blinded is bad but it's not instant lose scenario like being locked into a chainstun like how current flashes work. I have witnessed many many people get clicked on by this little green tumor for free instant wins and it makes me very sad.
# Changelog

:cl:  
tweak: flashes are now just a disarm, the stun is GONE
tweak: flash blindness has been doubled and confusion has been tripled to keep it competitive
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
Honestly, I don't think flashes even need to be "competitive", since they're so damn easy to get - and making the blind last so long can still fuck people up really badly, since then you can wail on them without fear of them attacking back. I think the confusion is good, though, since that makes chasing harder but doesn't severely hinder your ability to fight.

**Comment by Burger1998** [comment]
where does this leave borgs in combat know with no way to fight off someone trying to hack them?

**Comment by ynot01** [comment]
flashing someone without eye protection will stop them from hacking you easily, they will be blinded, disoriented, and drop their emag, leaving plenty room to flee

**Comment by forhiti** [comment]
I don't play sec normally but wouldnt this affect brig procedures? Or do they just need to use the stunbaton now?

**Comment by reddsnotdead** [comment]
this is bad, this also makes it way harder for borgs to actually be useful during malf or during a subversion. I'll say it's a good idea if it didn't touch borg flashes.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> this is bad, this also makes it way harder for borgs to actually be useful during malf or during a subversion. I'll say it's a good idea if it didn't touch borg flashes.

we hate cyborgs on this codebase so not an issue, also you have hacked modules on malf and a subverted AI has no shot to do anything useful anyways so not a big deal

**Comment by ReddicusDragon** [comment]
Nobody hates cyborgs???

**Comment by iamthesilly** [comment]
> I don't play sec normally but wouldnt this affect brig procedures? Or do they just need to use the stunbaton now?

it doesn't affect mounted or portable flashes

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> > I don't play sec normally but wouldnt this affect brig procedures? Or do they just need to use the stunbaton now?
> 
> it doesn't affect mounted or portable flashes

they meant removing handcuffs after brigging someone, yes you would do it with a stun baton and it's such a nothing concern that i dont know why they brought it up

**Comment by Simplehorror** [comment]
> > > I don't play sec normally but wouldnt this affect brig procedures? Or do they just need to use the stunbaton now?
> > 
> > 
> > it doesn't affect mounted or portable flashes
> 
> they meant removing handcuffs after brigging someone, yes you would do it with a stun baton and it's such a nothing concern that i dont know why they brought it up

moronic, everyone uses flashes for brig procedures because it doesnt need to recharge or 2 hits to stun. flashes are good against non-antags and suck against antags because they rush sechuds or dont need sechuds - also please don't act like anyone is going to use flashes ever again after this

**Comment by kooarbiter** [comment]
>permanent blindness is not an auto win

okay

**Comment by ReddicusDragon** [comment]
> > > > I don't play sec normally but wouldnt this affect brig procedures? Or do they just need to use the stunbaton now?
> 
> > > 
> 
> > > 
> 
> > > it doesn't affect mounted or portable flashes
> 
> > 
> 
> > they meant removing handcuffs after brigging someone, yes you would do it with a stun baton and it's such a nothing concern that i dont know why they brought it up
> 
> 
> 
> moronic, everyone uses flashes for brig procedures because it doesnt need to recharge or 2 hits to stun. flashes are good against non-antags and suck against antags because they rush sechuds or dont need sechuds - also please don't act like anyone is going to use flashes ever again after this

This is one of the rare times I agree with Simplehorror

**Comment by JamieD1** [comment]
You have to be within 1 tile to actually use this, it is hardly ever used against people who security are pursuing. They will always use taser/stun baton. All you are doing with this is nerfing qol and making it so flashes are never used again.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> You have to be within 1 tile to actually use this, it is hardly ever used against people who security are pursuing. They will always use taser/stun baton. All you are doing with this is nerfing qol and making it so flashes are never used again.

don't know what you're talking about, i see security rush people who are fleeing with flashes inhand all the time, knowing that if they get that one lucky click the person is instantly dumpstered and might as well have been dusted instantly. why did we bother nerfing stun batons if we left these the way they are? not literally everyone has flash protection, sunglasses especially are super rare

**Comment by JamieD1** [comment]
> > You have to be within 1 tile to actually use this, it is hardly ever used against people who security are pursuing. They will always use taser/stun baton. All you are doing with this is nerfing qol and making it so flashes are never used again.
> 
> don't know what you're talking about, i see security rush people who are fleeing with flashes inhand all the time, knowing that if they get that one lucky click the person is instantly dumpstered and might as well have been dusted instantly. why did we bother nerfing stun batons if we left these the way they are? not literally everyone has flash protection, sunglasses especially are super rare

Because a flash is not always guaranteed to work, a stun baton is always a guaranteed hit, thats the risk you take.

**Pull request closed without merging**
