### PR TITLE
--------ALL PRS ABOVE MUST BE DOCUMENTED--------

### PR DESCRIPTION
**Pull request by alexkar598**
Hello all, starting from now, ***all new*** PRs must follow the autodoc requirements found in https://github.com/yogstation13/Yogstation/blob/master/.github/AUTODOC_GUIDE.md in order for your PR to be accepted. PRs that lack autodoc comments will be closed. We are doing this for two reasons:

1) To have a place where we can put documentations and see it online.
2) (Its more this than the first one) So you actually start writing documentation for your horrible broken code.
3) So your PRs are easier to understand and by extension quicker to review.

The generated documentation files can be found at https://codedocs.yogstation.net Please note that due to caching systems which are there for the entire domain, changes in the documentation may take up to 3 hours to update. 

Existing PRs are encouraged to follow the standard but have no requirement to do so.

### CODE REVIEW

**Comment by Hopekz** [comment]
haha so funny wow omg I can't believe you did the thing XDDD

**Comment by alexkar598** [comment]
yes this is all a ploy to get back at hopek because he doesnt like autodoc comments

**Comment by alexkar598** [comment]
also i edited the PR to have a useful description

**Comment by patpol4** [comment]
What about pure map or sprite pull requests

**Comment by alexkar598** [comment]
What do you think?

Cant really put documentation in icon states or map files can you?

**Comment by patpol4** [comment]
Just making sure

**Comment by Alexandria404** [comment]
So if this documentation stuff is beyond me, I cant contribute.

**Comment by Partheo** [comment]
> 
> 
> So if this documentation stuff is beyond me, I cant contribute.

If you're literally unable to comment your own code, then yeah, you can't do shit can you?

**Comment by jcatjmeow** [comment]
If any of you need help documenting your code, let me know. I have a lot of experience documenting other people's java code and I am both willing and able to help you. 

Once you get in the rhythm of it, documenting your code is almost automatic. You wont even have to think about it anymore

**Review by swissloaf — CHANGES_REQUESTED** [review]
please tell them to message george kaka too

**Pull request closed without merging**
