### PR TITLE
Ports "Very minor medkit resprite, resprites medal boxes and makes the beer crate that appears on some sand ruins 3/4"

### PR DESCRIPTION
**Pull request by nmajask**
# Document the changes in your pull request

Ports ["Very minor medkit resprite, resprites medal boxes and makes the beer crate that appears on some sand ruins 3/4" #449](https://github.com/shiptest-ss13/Shiptest/pull/449) by [retlaw34](https://github.com/retlaw34) minus the bear bottle holder. 

# Spriting
image

# Wiki Documentation

Images. 

# Changelog

:cl:  retlaw34
imageadd: medkit sprites have been resprited
imageadd: medal boxes no longer soulful 
/:cl:

### CODE REVIEW

**Comment by tattax** [comment]
imo i prefer if it was a cube and not a rectangular prism

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
Everything is alright but I do think the medkits should be left out in this PR.

**Comment by nmajask** [comment]
> Everything is alright but I do think the medkits should be left out in this PR. 

Ah yes, everything is good with this medkit respite apart from the medkit sprites

**Comment by KillerOrcaCora** [comment]
Well, it also says it resprites medal boxes and some beer crates.

**Comment by nmajask** [comment]
> Well, it also says it resprites medal boxes and some beer crates. 

No, it only ports the medkit sprites and medal boxes

**Pull request closed without merging**
