### PR TITLE
Reverts the shitty paramedic grass jacket

### PR DESCRIPTION
**Pull request by Nickvr628**
Reverts #8146

I don't know about you, but when I google "paramedic jacket" I see this:  
image

So why did we replace the good yellow and green jacket with the shitty virologist-colored jacket? Who knows. 

:cl:  
rscdel: Undoes the yellow paramedic jacket removal that not a single paramedic player supported.
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
I like the new sprites personally.
If the paramedics get a vendor maybe add both otherwise neutral as I like both old and new.

Also; ss13 is not a reality simulator so how they appear in the real world shouldn't be too much of a factor.

**Comment by ynot01** [comment]
shut up boomrer you've angered the paramedic mains

**Comment by deathslayer2481** [comment]
Just allow both lmao more outfits is always good

**Comment by JamieD1** [comment]
I would probably just add both.

**Comment by MegaEmpirical** [comment]
Lies, I hated the old one. It was shitty and I was the one that request it be changed.

**Comment by Hopekz** [comment]
> shut up boomrer you've angered the paramedic mains

The 3-4 louder minority != what all "paramedic mains" think.
You can try to make an unbiased poll if you are curious otherwise it's as baseless as me saying "all paramedic mains prefer the new one"

**Comment by Idinuum** [comment]
closed for downgrading the quality of a sprite

**Pull request closed without merging**
