### PR TITLE
Genetics Nerf

### PR DESCRIPTION
**Pull request by Bibby0110**
### Intent of your Pull Request
Instability changes
Hulk: 40 -> 80
Dwarf: 5 -> 10
Chameleon: 25 -> 30
Radioactive: 5 -> 10
Thermal Sight: 25 -> 60
Space Adaptation: 30 -> 60
TK: 30 -> 65
Shock Touch: 20 -> 30

#### Changelog

:cl:  
tweak: tweaks genetic instability
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
no.

that is all.

**Comment by Mesalikepie** [comment]
Genetics needs more gameplay to do as well. Imo but good pr

**Comment by cuackles** [comment]
i like it but could the chance to get the chromosome wich reduces inestability also be uped sligthly ?or it will be be bad for the nerf ?

**Comment by ynot01** [comment]
this is a stupid and shit fix, higher prices doesn't excuse poor balance, make the shit weaker and lower the instability to encourage diverse and fun play instead of doing the opposite

**Comment by Bibby0110** [comment]
> this is a stupid and shit fix, higher prices doesn't excuse poor balance, make the shit weaker and lower the instability to encourage diverse and fun play instead of doing the opposite

No the problem is compounding powers on top of each other

**Comment by PrinceKirze** [comment]
I agree with the premise here but these numbers are a bit much (except for Hulk, fuck Hulk/Space Adapt combo).

**Comment by boodaliboo** [comment]
shock touch cant be used at ranged anymore and it is shitty anyways and also these numbers are excessive

**Comment by Bibby0110** [comment]
> shock touch cant be used at ranged anymore and it is shitty anyways and also these numbers are excessive

no

**Comment by TheLinuxOS** [comment]
I think it is excessive to increase the instability for almost all positive mutations to double what they are at now, I could support increasing them to 1.5 times their current instability but double is too much in my opinion.

**Comment by boodaliboo** [comment]
nerfing them is good but the increase is to high

**Comment by JackKindred** [comment]
I support this PR. Don't get me wrong, I'm no 550 IQ NASA Scientist holder of half a dozen nobel prizes, but I'm pretty sure something that revamps your DNA to such an extent it turns you into a watered down hulk, has to be PRETTY unstable. +1

**Comment by PrinceKirze** [comment]
> I support this PR. Don't get me wrong, I'm no 550 IQ NASA Scientist holder of half a dozen nobel prizes, but I'm pretty sure something that revamps your DNA to such an extent it turns you into a watered down hulk, has to be PRETTY unstable. +1

Again, this thought process is fine but the issue remains that these are gigantic changes. A 1.5x change would make Hulk and Space Adapt at the same time impossible, which is kind of geneticist's main issue (I cannot tell you how many Malf AIs I've seen get killed because two geneticists with Hulk and SA just punched into the core). Pretty much the only other BIG mutations that are viable alongside hulk then would be Chameleon and Shock Touch, which don't synergize as well as Hulk and SA. If you wanna buff chameleon to 40 or 45 to make it, specifically, not possible alongside Hulk, I wouldn't even see an issue with that.

**Comment by ghost** [comment]
lazy bandaid fix 

no idea why you're nerfing shock touch since it's worthless

no idea why you aren't just removing thermals

**Review by Amelia0010 — APPROVED** [review]

**Comment by Moja10** [comment]
Seems like a bit overkill, but i'm no genetics expert.

**Comment by jcatjmeow** [comment]
### Intent of your Pull Request
Explain what the purpose of your PR is. Mention if you tested your changes...

### Why is this good for the game?
Explain why each change in your pr is beneficial to the server. This is less necessary for bugfixes and such, but is always welcome. Remember: something that is self evident to you might not be to others. Explain your rationale even if you feel it goes without saying.

**Comment by Bibby0110** [comment]
> ### Intent of your Pull Request
> Explain what the purpose of your PR is. Mention if you tested your changes...
> 
> ### Why is this good for the game?
> Explain why each change in your pr is beneficial to the server. This is less necessary for bugfixes and such, but is always welcome. Remember: something that is self evident to you might not be to others. Explain your rationale even if you feel it goes without saying.

first one is in the PR you numbnut 

Second one is obvious, you’re literally mental if you think you should have thermals, space adaption and hulk at the same time
Same goes for the rest except shock touch which I’ll probably leave unchanged with the rest of the non-stupid ones

**Comment by JamieD1** [comment]
I agree it needs a nerf but this might be a tad far.

**Comment by MegaEmpirical** [comment]
Big softie.

**Pull request closed without merging**
