### PR TITLE
Add fluff and objective failure for if Narsie dies

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

Narsie's death was rather unspectacular with 0 flair to it, and didn't even fail the objective

# Spriting

# Wiki Documentation

Don't let Nar'Sie die, cultists
# Changelog

:cl:  
tweak: Add fluff and objective failure for if Narsie dies
/:cl:

### CODE REVIEW

**Comment by Sniblet** [comment]
But the round ends as soon as Nar'sie rises? Under what circumstance would this happen

**Comment by Simplehorror** [comment]
> But the round ends as soon as Nar'sie rises? Under what circumstance would this happen

last time i checked the round ends when the nuke goes off (or doesnt if you harvested enough)

**Comment by ReddicusDragon** [comment]
nar'sie vs ratvar

**Comment by Simplehorror** [comment]
singularity or BSA will kill narsie

**Review by ReddicusDragon — APPROVED** [review]

**Comment by JamieD1** [comment]
Please use the same definitions as other cutscenes ie SECONDS

**Comment by Simplehorror** [comment]
done @JamieD1

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
