### PR TITLE
Adds Gamer Girl Pee

### PR DESCRIPTION
**Pull request by GuppyLaxx**
Title. Find out how to get it in game, or be lame
:cl: GuppyLaxx
add: Added Gamer Girl Pee
/:cl:

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
heh

**Comment by GuppyLaxx** [comment]
this is cyber bullying

**Comment by Bibby0110** [comment]
Id like to know why this PR was closed. The pure benefit it could bring to the Yogstation community as a whole, is just too much to deny. The pure improvement of the game that would result from this PR is immense. I have done an indepth analysis of the pros and cons of this PR. 
Pros:
Immense realism
Superior roleplay
Cons:
Nothing

To back up my claims I have construct a graph showing the game quality with and without this PR.
image

Therefor, I strongly recommend that you merge this PR, for the Yogstation community as a whole.

**Comment by mrhugo13** [comment]
Re-open this if this makes the player gib themselves 5 seconds after.

**Comment by Nickvr628** [comment]
I may be a catgirl degenerate but this is too far even for me.

**Comment by CMOisLing** [comment]
Speedmerge

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I will literally unretire and ban you

**Comment by Bibby0110** [comment]
My previous point still stands

**Comment by Moja10** [comment]
I'm not seeing reasons for why this would be closed. Opening up for further discussion amongst the community.

**Pull request closed without merging**
