### PR TITLE
Makes the turbine less weird and bad

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Updates the turbine code to be less weird and fixes some stuff, also makes the turbine require a difference in pressure for gas to flow through it instead of violating conservation of energy.

# Why is this good for the game?

You should respect conservation of energy... NOW!!!

Also more useful stuff in the interface and better code is cool too.

# Testing
image

# Changelog

:cl:  
tweak: the turbine now generates power from a difference in pressure instead of just moving the gas anyway and making power for free (respect conservation of energy!!!)
tweak: turbine computer tgui shows the turbine's internal pressure
bugfix: fixed the turbine making free energy from nowhere at low RPM
bugfix: fixed the turbine forcing air into the outlet turf when it's blocked
bugfix: fixed inlet and outlet turfs not updating air properly
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
Would this force turbines on syndi bases to leak plasma into the outside environment?

**Comment by iamthesilly** [comment]
> Would this force turbines on syndi bases to leak plasma into the outside environment?

They already do

**Comment by Marmio64** [comment]
> > Would this force turbines on syndi bases to leak plasma into the outside environment?
> 
> They already do

they don't unless you open the turbine doors. I am asking if this would force them to open the doors due to having to maintain a pressure difference now.

**Comment by iamthesilly** [comment]
> they don't unless you open the turbine doors. I am asking if this would force them to open the doors due to having to maintain a pressure difference now.

It would, yes

**Comment by KingSuperBOB** [comment]
> It would, yes

Correct me if Im wrong but dont plasma leaks in the syndibase fuck lavaland atmos comically and stone the lava moat

**Comment by iamthesilly** [comment]
> Correct me if Im wrong but dont plasma leaks in the syndibase fuck lavaland atmos comically and stone the lava moat

Yeah that's why having a turbine on the syndicate base is a bad idea

**Comment by MajManatee** [comment]
"wont this thing cause issues?"
"just don't do that thing"
beautiful

**Review by ToasterBiome — APPROVED** [review]

**Comment by ShoziOffical** [comment]
holy shit 24mpa just for 64.5kw this is bad do i have to put an active fusion in there to get the required RPM??

**Pull request merged**
