### PR TITLE
When the AI got moved it got nerfed hard in Defences, This ups it a bit

### PR DESCRIPTION
**Pull request by JamieD1**
Buffs AI Defences.

Old design was able to be breached in less then a minute.

image

:cl:  
tweak: Buffs AI Defences.
/:cl:

### CODE REVIEW

**Comment by Bibby0110** [comment]
this likely won't play well with atmos on high time dilation but ohwell

**Comment by Hopekz** [comment]
Can we just make a new reinforced wall color with double the stats of a regular reinforced wall?
Seems like double walls are being proposed more often now.
Just because double walls look terrible

**Comment by ynot01** [comment]
bring back center AI

**Comment by Hopekz** [comment]
> bring back center AI

actual good take

**Comment by JamieD1** [comment]
> this likely won't play well with atmos on high time dilation but ohwell

Can adjust if it does, we can see

**Comment by Bibby0110** [comment]
> bring back center AI

no

**Review by ynot01 — DISMISSED** [review]
Conflicts

**Comment by Hopekz** [comment]
> > bring back center AI
> 
> no

Awful take

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
make sure the catwalks go all the way around. Also this is very ugly

**Comment by JamieD1** [comment]
> make sure the catwalks go all the way around. Also this is very ugly

Fixed

**Review by ToasterBiome — APPROVED** [review]
fine

**Pull request merged**
