### PR TITLE
Powercreeps the powercrepe

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

ports https://github.com/tgstation/tgstation/pull/49379
> ## About The Pull Request
> Buffs the powercrepe
> Honestly, Never seen anyone make or use this ever, it's finally time to powercreep the powercrepe again.
> 
> ## Why It's Good For The Game
> More incentive to encourage traitors/captains/HoS to make this thing because having people beat/kill other people with a jelly filled pancake tortilla thing is hilarious

#### Changelog

:cl:  NikNak
tweak: The powercrepe has been buffed
/:cl:

### CODE REVIEW

**Comment by deathslayer2481** [comment]
Can it be sharpened with a grindstone tho

**Comment by Hopekz** [comment]
> Can it be sharpened with a grindstone tho

No. Nothing inherited by the parents (/obj/item/reagent_containers/food/snacks/) allow it to be sharpened.

**Comment by Mr-Space** [comment]
dump it

**Comment by AsV9** [comment]
absolute bruh moment

**Comment by Niknakflak** [comment]
Yog hates fun

**Pull request closed without merging**
