### PR TITLE
Revert "Removes the donk-soft vendor from roundstart asteroid"

### PR DESCRIPTION
**Pull request by MajManatee**
Reverts yogstation13/Yogstation#21325

A better title would be "Re-adds fun"
why doesn't this auto-populate with the template?

Removed because "Admin issue" which is dumb.  you don't have to remove the enjoyment for everyone just because some people abuse stuff.

### CODE REVIEW

**Comment by cowbot92** [comment]
why dont you make a hugbox version with guns that cant hold riot darts then

**Comment by MajManatee** [comment]
why didn't you?

**Comment by cowbot92** [comment]
> why didn't you?

mature answer

**Comment by MajManatee** [comment]
thanks

**Pull request closed without merging**
