### PR TITLE
Radio colour change

### PR DESCRIPTION
**Pull request by thehighwayman**
### Intent of your Pull Request

Changes the service channel from light brown to dark green and the command channel from gold to darkish blue

Fixes issue #2362 

#### Changelog

:cl:  
tweak: Changes colours of two radio channels
/:cl:

### CODE REVIEW

**Comment by MegaEmpirical** [comment]
<3

**Comment by MegaEmpirical** [comment]
<3

**Comment by Amelia0010** [comment]
💭 💭 💭 
      💭 💩 💭 
      💭 💭 💭 
     🤔

**Comment by ThatLing** [comment]
Not modular, see here for instructions.

**Review by ThatLing — APPROVED** [review]

**Pull request merged**
