### PR TITLE
Adds a "testing" section to the pull request template

### PR DESCRIPTION
**Pull request by solwashere**
# Document the changes in your pull request

Adds a "testing" section to the Yogstation Github PR template. 

# Why is this good for the game?
This will hopefully encourage individuals to test their PRs to ensure that it is at least partially bug free, which will allow for less bugs that could have been otherwise avoided on the master branch and an increase in code quality. Could also be used as a reference for future bug fixers to help locate the root of certain issues without code diving.

# Changelog

:cl:  
rscadd: Adds "testing" to the GitHub PR template.

/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
is this because of me

**Comment by solwashere** [comment]
> is this because of me

Trying to blame you for something of this nature would be like trying to blame only Brutus for the murder of Caesar

**Comment by neeshacark** [comment]
testing:

untested

**Comment by solwashere** [comment]
> testing:
> 
> untested

This is why it would be cool if the maints and HDs held people accountable

**Comment by neeshacark** [comment]
> > testing:
> > untested
> 
> This is why it would be cool if the maints and HDs held people accountable

i mean i dont think we require prs to be tested, so im not sure really what we'd hold people accountable for.  it's literally my job to make sure your PR works

**Comment by solwashere** [comment]
> > > testing:
> > > untested
> > 
> > This is why it would be cool if the maints and HDs held people accountable
> 
> i mean i dont think we require prs to be tested, so im not sure really what we'd hold people accountable for.  it's literally my job to make sure your PR works

If maints did a good job making sure that a PR works or is functional then we wouldn't have half the bugs or just mechanics that straight up don't work that we have had spring up over the past few months.

**Comment by ToasterBiome** [comment]
> > > testing:
> 
> > > untested
> 
> > 
> 
> > This is why it would be cool if the maints and HDs held people accountable
> 
> 
> 
> i mean i dont think we require prs to be tested, so im not sure really what we'd hold people accountable for.  it's literally my job to make sure your PR works

Players should submit code that functions correctly and maintainers should check if they did so. in a perfect world, maintainers would always check stuff to work and it would work. Your job and I is shuffling through all this stuff, the least that can be done is they submit code that actually functions.

**Comment by azzzertyy** [comment]
i think this is a bad idea
because people can just lie and say "i tested it"
and this encourages maintainers to trust that they tested it and not do the work in themselves to make sure it works.
if maintainers actually test which they should be doing then this is completely unnecessary and wastes time, this solves zero problems.

**Comment by ToasterBiome** [comment]
> i think this is a bad idea
> 
> because people can just lie and say "i tested it"
> 
> and this encourages maintainers to trust that they tested it and not do the work in themselves to make sure it works.
> 
> if maintainers actually test which they should be doing then this is completely unnecessary and wastes time, this solves zero problems.

Testing should preferably fall to both parties. The entire argument against it is ridiculous. In the worst case, a bug gets in the game, WHICH IS WHAT HAPPENS NOW. In the best case the player actually tests it, realizes something doesn't work, and then fixes it before going through the song and dance to have a maintainer request changes. We already require this by needing to show sprites, and showing maps. ("look at map diff bot" is cringe). Yes maintainers should test things but players should also be responsible in the fact that they should be submitting non broken things. Repeatedly lying about testing is also self evident if YOUR STUFF DOESN'T WORK and maintainers will know 100% not to trust your code at all. It's a team effort and actively resisting the submitter have any responsibility is stupid. A person builds a house halfway off a cliff and when the inspector comes around you say "the inspector really should have caught them building on the cliff, the builder  surely isn't responsible for this in any way" because they can write "nope not on a cliff" down on their own report. DONT BUILT IT ON THE CLIFF IN THE FIRST PLACE.

**Comment by solwashere** [comment]
> i think this is a bad idea
> because people can just lie and say "i tested it"
> and this encourages maintainers to trust that they tested it and not do the work in themselves to make sure it works.
> if maintainers actually test which they should be doing then this is completely unnecessary and wastes time, this solves zero problems.

If someone blatantly lies just gitban them lol
Coding is a privilege not a right

**Comment by azzzertyy** [comment]
> > i think this is a bad idea
> > because people can just lie and say "i tested it"
> > and this encourages maintainers to trust that they tested it and not do the work in themselves to make sure it works.
> > if maintainers actually test which they should be doing then this is completely unnecessary and wastes time, this solves zero problems.
> 
> Testing should preferably fall to both parties. The entire argument against it is ridiculous. In the worst case, a bug gets inyadayadayadaydayadayadayadayadaydaayaaydayadyadayda

I guess i see no harm in atleast trying this, i just fear it will backfire and result in maintainers trusting it too much instead of testing the code themselves

**Comment by solwashere** [comment]
> > > i think this is a bad idea
> > > because people can just lie and say "i tested it"
> > > and this encourages maintainers to trust that they tested it and not do the work in themselves to make sure it works.
> > > if maintainers actually test which they should be doing then this is completely unnecessary and wastes time, this solves zero problems.
> > 
> > Testing should preferably fall to both parties. The entire argument against it is ridiculous. In the worst case, a bug gets inyadayadayadaydayadayadayadayadaydaayaaydayadyadayda
> 
> I guess i see no harm in atleast trying this, i just fear it will backfire and result in maintainers trusting it too much instead of testing the code themselves

Only like two maints check the code lol

**Review by ToasterBiome — APPROVED** [review]
Test yo shit

**Pull request merged**
