### PR TITLE
Makes it so non-heretics cannot wear heretic armor items

### PR DESCRIPTION
**Pull request by cowbot92**
# Document the changes in your pull request

Adjusts it so that non-heretics & non-heretic monsters (summons) cannot wear heretic equipment (can still pick up the blade, just can't use it)

# Why is this good for the game?

People wearing the 50 armor heretic armor & other stuff is kinda stinky, am going to work on an alternative to the 50 armor next (maybe make it upgradeable and start at lower values)

# Testing

Tested everything. It hurt. A lot.

# Changelog

:cl:  

tweak: non-heretics can no longer wear heretic stuff

/:cl:

### CODE REVIEW

**Review by Moltijoe — CHANGES_REQUESTED** [review]
please use time defines
also, ty for making it only on equip rather than pickup

**Comment by iloveloopers** [comment]
pretty sure the amulet doesn't give thermal vision to non-heretics already

**Comment by cowbot92** [comment]
> pretty sure the amulet doesn't give thermal vision to non-heretics already

It's mostly for flavor.

**Comment by cowbot92** [comment]
> please use time defines also, ty for making it only on equip rather than pickup

ok I made it have time defines

**Review by cowbot92 — COMMENTED** [review]
Files have been changed

**Comment by MajManatee** [comment]
i thought it already worked this way

**Comment by cowbot92** [comment]
> i thought it already worked this way



> i thought it already worked this way

It did not, only the blade did

**Review by MajManatee — APPROVED** [review]
Looks like it works

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
