### PR TITLE
adds a Servoskull to the chaplain weapons

### PR DESCRIPTION
**Pull request by cuackles**
adds a servo skull,  as for now it just floats next to you and its worn on  the neck stot, i  plan to make it give a hud of some kind and maybe mesons once i figure out how to

# Wiki Documentation

add the skull to the holy weapons list
# Changelog

:cl:  
rscadd: new holy weapon  
imageadd: added skull sprites  
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
you ruined the sci skillcapes

**Comment by cuackles** [comment]
> you ruined the sci skillcapes

I swear i didn't do nothing please don't take me to spriter jail

**Comment by maxion12345** [comment]
feels kinda empty. It'll need abilities for sure, especially attacking. Wonder if a short ranged laser would be possible, or something of the sort.

**Comment by cuackles** [comment]
> feels kinda empty. It'll need abilities for sure, especially attacking. Wonder if a short ranged laser would be possible, or something of the sort.

I want it to be a purely defensive and utility focused item, no damaging potential, i do agree that as how it is now it's kinda empty, i want to give it some sight related abilities but with my limited coding knowledge it's kinda a hard process to get done, but eventually it will have more stuff it can do, i considered make it give thermals but i don't know how strong that would be

**Comment by ChesterTheCheesy** [comment]
It should be a fast bot controlled by middle click that you can switch view with. Ripping swarmer code and staying true to servo-skull functionality.

**Comment by cuackles** [comment]
> It should be a fast bot controlled by middle click that you can switch view with. Ripping swarmer code and staying true to servo-skull functionality.

I like that idea, show me where the code be at and i will see if I can do it

**Review by nesisknesis — CHANGES_REQUESTED** [review]
Your PR replaces the Sci skillcapes with an older version, you need to update them.

**Comment by cuackles** [comment]
> Your PR replaces the Sci skillcapes with an older version, you need to update them.

fixed

**Comment by cuackles** [comment]
wrong button

**Review by nesisknesis — APPROVED** [review]

**Comment by Marmio64** [comment]
maybe have it attack anyone who melee attacks the user. a nullrod with no damaging potential is not very good because its kind of needed so that theres a counter to cult constructs and such.

**Comment by cuackles** [comment]
> maybe have it attack anyone who melee attacks the user. a nullrod with no damaging potential is not very good because its kind of needed so that theres a counter to cult constructs and such.

again,this is suposed to be utility not damaging, and against constructs it will still deal 45 brute if the construct get extra damage from nullrods hasnt been removed

**Comment by cuackles** [comment]
now it gives med and diagnostic hud, and keep antimagic shielding from nullro
2021-12-06 19_42_50-Space station 13_ Festive Construct 9
2021-12-06 19_43_32-Space station 13_ Festive Construct 9
2021-12-06 19_42_27-Space station 13_ Festive Construct 9
2021-12-06 19_42_41-Space station 13_ Festive Construct 9
ds

**Comment by maxion12345** [comment]
> > feels kinda empty. It'll need abilities for sure, especially attacking. Wonder if a short ranged laser would be possible, or something of the sort.
> 
> I want it to be a purely defensive and utility focused item, no damaging potential, i do agree that as how it is now it's kinda empty, i want to give it some sight related abilities but with my limited coding knowledge it's kinda a hard process to get done, but eventually it will have more stuff it can do, i considered make it give thermals but i don't know how strong that would be

If it's a null-rod variant it'll need some combat potential due to it being used to combat cultists and the sort.  Maybe bundle it with one of those techpriest axe-spears as well? Or make it a trophy beacon kit (you can select the axe-spear thing as a null rod variation and get the servo and some "head tech priest" robes from the beacon?"

**Comment by UselessTheremin** [comment]
it doesnt need combat potential tbh what about the shield staffs? also its more interesting than just a weapon the chaplain kinda has a lot of those already and adding a generic spear seems boring to me

**Comment by cuackles** [comment]
Also the damage potential is that you get both hands free while keeping the antimagic shielding, so you can dual wield shotguns or a firexe and don't need to worry about about a magic stun or a direct fireball

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
