### PR TITLE
Adds movie-like rolling credits to the end of the round

### PR DESCRIPTION
**Pull request by swissloaf**
Credit:
BeeStation/BeeStation-Hornet#318
BeeStation/BeeStation-Hornet#320
BeeStation/BeeStation-Hornet#327
BeeStation/BeeStation-Hornet#407

[A Video of such](https://streamable.com/wbpn4)

#### Changelog

:cl:  
rscadd: Adds movie-like rolling credits to the end of the round
experimental: This is experimental  
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
cute

**Comment by Partheo** [comment]
Kind of neutral. I like the idea but I think they could look better, and possibly be on the side rather than in the middle.

Also, can this be disabled? This should absolutely be a preference. I know many will ignore them after a while, and a significant population will want to have them turned off.

**Comment by swissloaf** [comment]
> Kind of neutral. I like the idea but I think they could look better, and possibly be on the side rather than in the middle.
> 
> Also, can this be disabled? This should absolutely be a preference. I know many will ignore them after a while, and a significant population will want to have them turned off.

It has a preference option. If you have widescreen which most do they appear on the side.

**Review by Partheo — APPROVED** [review]

**Comment by maxion12345** [comment]
Does this remove the standard EORG sign that currently appears?

**Comment by boodaliboo** [comment]
eh i truthfully didnt like the look of this when i played bee

**Comment by swissloaf** [comment]
It does not remove the current one

**Pull request merged**
