### PR TITLE
Juggernaut gene

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

New genetics power that lets you smash through structures and become stun immune for 1 second. Better for balance than hulk because you're not 24/7 stun immune and smashing through walls but it's on a 2 minute cooldown, so you have to save it for a purpose. Plus, it is instability 80, which is the highesti n the game.
# Spriting

image

# Wiki Documentation

add the gene to genetics wiki
# Changelog

:cl:  
rscadd: New genetics power, "juggernaut"
/:cl:

### CODE REVIEW

**Review by KillerOrcaCora — CHANGES_REQUESTED** [review]
Fill in the spriting template correctly you should know this by now

**Comment by Simplehorror** [comment]
> Fill in the spriting template correctly you should know this by now

what spriting template

**Comment by KillerOrcaCora** [comment]
image

**Comment by Sniblet** [comment]
`This is completely worthless and will never be used for any purpose`

This is ok and may be used by validhunters pretty often

**Comment by Simplehorror** [comment]
image

**Comment by Simplehorror** [comment]
> This is completely worthless and will never be used for any purpose

why's that

**Comment by KillerOrcaCora** [comment]
> image

Put an image of whatever your sprite is in the spriting template and how it will show in a live server, This is nothing new and if your just gonna keep trying to meme around it I will close this PR until you do it correctly

**Comment by Sniblet** [comment]
> why's that

There is no stun a person can prepare for that 1.5 seconds of immunity will protect them from
Breaking 1 wall every 2 minutes is powerful but a welder can do it twice as well for no instability cost and a combat mech does it for free

**Comment by Simplehorror** [comment]
oh you could break like 5 walls in 1.5 seconds, you break them by walking into them

**Comment by Sniblet** [comment]
> oh you could break like 5 walls in 1.5 seconds, you break them by walking into them

Is this different from every other wall smashing system in the game which makes you wait a second after each one

**Comment by Simplehorror** [comment]
yes, it's instant flattening

**Comment by Simplehorror** [comment]
> > image
> 
> Put an image of whatever your sprite is in the spriting template and how it will show in a live server, This is nothing new and if your just gonna keep trying to meme around it I will close this PR until you do it correctly

ok give me a second

**Comment by Aquizit** [comment]
> oh you could break like 5 walls in 1.5 seconds, you break them by walking into them

Then it’s just a rod, and wizards can already do that. Not sure how I’d feel about a wizard spell turning into a gene, despite how nerfed it may or may not be.

**Comment by LazennG** [comment]
this is good for the game how

**Comment by MajManatee** [comment]
its just hulk, which we removed

**Comment by Simplehorror** [comment]
> this is good for the game how

you play shaft miner & rush bubblegum you have no room to talk lol

**Comment by Simplehorror** [comment]
> its just hulk, which we removed

because it was unbalanced. THIS is juggernaut. Juggernaut is balanced because he can actually be arrested

**Comment by KillerOrcaCora** [comment]
This serves no purpose other then being a mass provided greytider tool, the hulk nerf was modeled the same way just as this is and it became nothing more then a pocket powergame tool that everyone carried in their hot bar. 

We aren’t giving crew damn near wizard ability tier hand me outs. Closing per balance council comments.

**Comment by Simplehorror** [comment]
how is this in any way "wizard tier"

**Comment by KillerOrcaCora** [comment]
Sir what you have described is quit literally the wizard rod ability…

**Comment by Simplehorror** [comment]
> Sir what you have described is quit literally the wizard rod ability…

how

**Pull request closed without merging**
