### PR TITLE
Ballistics shield for nukies

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

30 TC shield that blocks all incoming ballistic projectiles, but not energy. This is so they don't just spec into autorifles roundstart and make energy combat shields completely worthless.
# Spriting

# Wiki Documentation

30 tc ballistic shield, check files changed for desc
# Changelog

:cl:  
rscadd: Ballistics shield for nukies
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
@Skrem7 do you have an issue with me?

**Comment by Mantlecrawler** [comment]
What's to stop a nukie from getting a extra arm, a energy shield, a ballistics shield, and becoming immune to all but melee, where nukies vastly have the upper hand?

**Comment by Simplehorror** [comment]
> What's to stop a nukie from getting a extra arm, a energy shield, a ballistics shield, and becoming immune to all but melee, where nukies vastly have the upper hand?

probably the fact that you can't get extra arms

**Comment by Mantlecrawler** [comment]
Im preety sure nukies can get extra arms

**Comment by Simplehorror** [comment]
they cannot, you should play more

**Comment by Bibby0110** [comment]
There’s no need to be rude

**Comment by Simplehorror** [comment]
ok

**Pull request closed without merging**
