### PR TITLE
Ghost Moff

### PR DESCRIPTION
**Pull request by BlueishTsunami**
Opened this PR to help out a friend add their moth ghost sprite into the game, ckey: "\_hot dyke\_"

- Adds moff into list of ghosts in ghost.dm 
- Updates mob.dmi to include the sprite

moff1
moff2
moff3

:cl:  
rscadd: Added "Moff" to the available list of ghosts in preferences. 
imageadd: Added sprite for Moth Ghost
/:cl:

### CODE REVIEW

**Comment by cowbot92** [comment]
this is cute

**Comment by Mqiib** [comment]
Ah yes an even bigger ghost to click on instead of the thing I want to click on.
Also good sprite

**Review by cuackles — APPROVED** [review]
looks very good, i will ask tho that you @ tag the spriter github acount if they have one

**Review by Moltijoe — APPROVED** [review]
shrimple code

**Pull request merged**
