### PR TITLE
More decals for decal painter

### PR DESCRIPTION
**Pull request by warface1234455**
# About PR
Tired of seeing default floor ugly gray floor? NOW you can decorate any floor you like with the new epic decals

# Changelog

:cl:  
rscadd: More decals
tweak: Buffed large toner from 50 to 75 
/:cl:

### CODE REVIEW

**Comment by warface1234455** [comment]
ah shit conflicts

**Comment by warface1234455** [comment]
WDYM CONFLICTS ITS tHE SAME

**Comment by warface1234455** [comment]
i hate github

**Review by KillerOrcaCora — APPROVED** [review]
Create!

**Pull request merged**
