### PR TITLE
Radiation Anomaly

### PR DESCRIPTION
**Pull request by warface1234455**
# About Pr
- ports https://github.com/Lumos-SS13/Lumos/pull/87

# Document the changes in your pull request

Adds radiation anomaly 
This one will spread radiation and shoot radballs everywhere
SM now also spawn raditation anomaly

# Wiki Documentation
Radiation anomaly 
This one will spread radiation and shoot radballs everywhere
SM now also spawn radiation anomaly

# Spriting 

https://user-images.githubusercontent.com/89688125/191244685-d99ee65e-79a9-463d-8114-c0ad5800d4e9.mp4

image

# Changelog

:cl:  jjpark-kb(Lumos station), warface1234455
rscadd: Radiation Anomaly
tweak: SM now also spawn radiation anomaly
/:cl:

### CODE REVIEW

**Comment by cuackles** [comment]
Like the idea, don't like the sprite it has tho  might it be possible that you get something different for it ?

**Comment by ShoziOffical** [comment]
> Like the idea, don't like the sprite it has tho might it be possible that you get something different for it ?

@cuackles imma try

**Comment by ShoziOffical** [comment]
@cuackles how's this sprite

**Comment by ShoziOffical** [comment]
hmm icondiffbot moment

**Comment by ShoziOffical** [comment]
request testmerge

**Comment by JamieD1** [comment]
Icon kinda meh

**Comment by cuackles** [comment]
Hhhhhhhhmmmmm yeah the icon still lacks something, if you want I can give it a try to make something more fitting later today

**Comment by ShoziOffical** [comment]
> Hhhhhhhhmmmmm yeah the icon still lacks something, if you want I can give it a try to make something more fitting later today

Sure

**Review by cuackles — APPROVED** [review]

**Comment by cuackles** [comment]
Good sprite

**Review by Bibby0110 — APPROVED** [review]

**Pull request merged**
