### PR TITLE
"Mime jaunted!!!1!" - New mime spell

### PR DESCRIPTION
**Pull request by MajManatee**
# Document the changes in your pull request
Sorta kinda ports https://github.com/yogstation13/yogstation-2017-/pull/1373 from old yogs.
Idk dahlia said "please add this 🥺 " and I said yeah sure.

# Why is this good for the game?

More spell diversity. Less use of "wall" hopefully.

# Testing

TBD

# Spriting

TBD

# Wiki Documentation
TBD

# Changelog

:cl:  
rscadd: New mime spell "Invisible Touch"
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
make uses recharge over like 5 minutes or so

**Comment by MajManatee** [comment]
no, then it will literally be never used.

**Comment by LaOubliette** [comment]
Good for the game (i am not biased at all)

**Comment by MajManatee** [comment]
Balance clowncil said "Remove the invisibility part please"

**Comment by Moltijoe** [comment]
> Balance clowncil said "Remove the invisibility part please"

lol, lmao, dude literally reads one comment and closes the request because of it

**Comment by iloveloopers** [comment]
> Balance clowncil said "Remove the invisibility part please"

what do you mean? is that not the whole ability? surely they mean something else?

**Pull request closed without merging**
