### PR TITLE
actually fixes replying to resolved tickets

### PR DESCRIPTION
**Pull request by Amelia0010**

### CODE REVIEW

**Comment by ThatLing** [comment]
are you sure?

**Comment by Amelia0010** [comment]
like 99%

**Comment by ThatLing** [comment]
This just makes a new ticket when they try to respond?

**Comment by Amelia0010** [comment]
[23:05] Nichlas0010 🤕🔫: I figured out that they're not actually responding to the ticket itself, since the response doesn't show up in the ticket log
[23:05] Nichlas0010 🤕🔫: since their current_ticket was already removed
[23:05] Nichlas0010 🤕🔫: we can see here, that this is what they respond to
[23:05] Nichlas0010 🤕🔫: https://github.com/yogstation13/Yogstation-TG/blob/697255884719ad12c85f16abe7a1e5e2da13798a/code/modules/admin/verbs/adminpm.dm#L182(edited)
[23:06] Nichlas0010 🤕🔫: since the href uses key_admin, we go find that proc
[23:07] Nichlas0010 🤕🔫: https://github.com/yogstation13/Yogstation-TG/blob/85214f3b082647a46cdf94c640f0b78dcaf64794/code/__HELPERS/unsorted.dm#L373
[23:07] Nichlas0010 🤕🔫: it's set to use include link, which is this href
[23:07] Nichlas0010 🤕🔫: https://github.com/yogstation13/Yogstation-TG/blob/85214f3b082647a46cdf94c640f0b78dcaf64794/code/__HELPERS/unsorted.dm#L412
[23:08] Nichlas0010 🤕🔫: we can then find out where the priv_msg is used
[23:08] Nichlas0010 🤕🔫: https://github.com/yogstation13/Yogstation-TG/blob/697255884719ad12c85f16abe7a1e5e2da13798a/code/modules/client/client_procs.dm#L87
[23:08] Nichlas0010 🤕🔫: which uses cmd_admin_pm
[23:08] Nichlas0010 🤕🔫: which we see here, their response to the admin as a non-admin
[23:08] Nichlas0010 🤕🔫: https://github.com/yogstation13/Yogstation-TG/blob/697255884719ad12c85f16abe7a1e5e2da13798a/code/modules/admin/verbs/adminpm.dm#L167
[23:09] Nichlas0010 🤕🔫: it's set to log it to the ticket, but there's no ticket to log it too
[23:09] Nichlas0010 🤕🔫: and it never actually checks whether a ticket exists
[23:10] Nichlas0010 🤕🔫: which is why inserting a check that makes a new ticket if none exists will stop the responding to resolved tickets.

**Comment by Amelia0010** [comment]
ignore the compile error, it's fixed on master

**Comment by ThatLing** [comment]
how do you always manage to break travis

**Comment by Amelia0010** [comment]
well, on this occasion I missed a camera on yogstation, which I fixed in another mirror

**Pull request merged**
