### PR TITLE
job gpses start with name instead of GPS0

### PR DESCRIPTION
**Pull request by Simplehorror**
# Document the changes in your pull request

qol noob bait removal
# Spriting

# Wiki Documentation

n/a
# Changelog

:cl:  
tweak: job gpses start with name instead of GPS0
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
mining medic also gets a gps

**Comment by missatessatessy** [comment]
Good pr if it works and is applied to mining medic too

**Comment by MajManatee** [comment]
does this apply to the dead miner bodies on lava land?

**Comment by Simplehorror** [comment]
no

**Review by ReddicusDragon — APPROVED** [review]
code looks fine

**Review by JamieD1 — APPROVED** [review]

**Comment by Moltijoe** [comment]
> Good pr if it works and is applied to mining medic too

i come from the future to tell you, it doesn't work

**Comment by Hopekz** [comment]
> code looks fine

Code wasn't fine at all ):<

**Comment by Simplehorror** [comment]
i was assuming that the original shaft miner GPS code worked when actually it never did

**Comment by Moltijoe** [comment]
> i was assuming that the original shaft miner GPS code worked when actually it never did

Yeah, i assumed so

**Pull request merged**
