### PR TITLE
Streamlines the Tricorder's code

### PR DESCRIPTION
**Pull request by yacabo**
Improves the Tricorder's code so that it is not 70% copy paste. Functionally the only difference is that the medical side of it has a different UI seen here:

image

The code however has been modified so that the gas analyzer now has a part of its code turned into a proc that can be used elsewhere, and as you can imagine, is now used in the tricorder code.

Also it can no longer tell how long someone has been dead.

:cl:  
tweak: Tricorder code has been redone, functionally it only gives it a unique medical scanner UI
tweak: Part of the gas analyzer can be now used as a proc.
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Make it blue instead of neon green please

**Comment by yacabo** [comment]
It's blue now but scanners.dm seems to of broken down 
so uh
standby

**Comment by yacabo** [comment]
GitHub broke this PR, I'm going to need to make a new one, standby

**Comment by yacabo** [comment]
New one here:
https://github.com/yogstation13/Yogstation-TG/pull/6564

**Pull request closed without merging**
