### PR TITLE
Various traitor Dark HONK fixes

### PR DESCRIPTION
**Pull request by ynot01**
# Document the changes in your pull request

This gets ahelped a lot

# Changelog

:cl:  
bugfix: Fixed Dark H.O.N.K. wreckage not reconstructing into a Dark H.O.N.K.
bugfix: Fixed traitor Dark H.O.N.K. requiring nukie access
/:cl:

### CODE REVIEW

**Comment by ShoziOffical** [comment]
i think clarke wrekcage cant be reconstructed aswell

**Comment by ynot01** [comment]
> i think clarke wrekcage cant be reconstructed aswell



Looks fine to me

**Comment by ShoziOffical** [comment]
> > i think clarke wrekcage cant be reconstructed aswell
> 
> 
> 
> Looks fine to me

Oh wait, i mean it cannot be salvaged, i used to be a free miner on the free miner ship but couldnt salvaged it then someone removed the wreckage from the free miner ship on this pr #16724 because so 
image

**Comment by ynot01** [comment]
> well i don't know why but i used to be a free miner on the free miner ship but couldnt salvaged it then someone removed the wreckage from the free miner ship on this pr #16724 because so image

this is because it wasn't set to have a capacitor, the ripley wreckage on the miner ship was specifically set to have a capacitor so it could be repaired, whoever replaced it with a clarke must've forgotten to

**Comment by ChuChu42** [comment]
thanks 
this morning i bought a dark honk as a traitor, wasting 16tc and was unable to ride it and was tagged as traitor because someone found it

note: dark honk in round report shows 20tc despite being 16.

**Review by Moltijoe — APPROVED** [review]
looks good

**Pull request merged**
