### PR TITLE
Removes more AI ion law possibilities

### PR DESCRIPTION
**Pull request by Cartlord**
**Untested, webedited.**
Removed "GAS THE LIZARDS" from the list of ionmust possibilities, after I asked in #staff-help and was told that it'd likely be crossing the line of IC bigotry.
Removed "HAVING GENITALS" from the ionthings list - we don't ever need penis inspection.
Removed "COPULATING WITH" and "POOPING ON" from the ionverb list because those seem like things people shouldn't be RPing.

# Wiki Documentation

Just gotta take those out of their lists of ion laws, if they even keep a list of those.

# Changelog

Edit the changelog below to reflect the changes made by this PR, even if the changes are minor - required for every PR.
If you add a name after the ':cl', that name will be used in the changelog. Leave it empty to use your GitHub name.

:cl:  
rscdel: Removed "GAS THE LIZARDS" from AI ionmust laws
rscdel: Ion'd AIs can no longer call to check if a person possesses genitals
rscdel: Ion storms can no longer give a law that involves people poopng or copulating
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
Put pooping on BACK RIGHT NOW!

**Comment by Cartlord** [comment]
do you really want shitrp

**Comment by Marmio64** [comment]
No please... Must gas the lizards...

**Comment by patpol4** [comment]
"we don't ever need penis inspection"
Bold statement, can you back it up

**Comment by Cartlord** [comment]
erp rules

**Review by adamsong — APPROVED** [review]
Does does as advertised

**Pull request merged**
