### PR TITLE
Shitcurity uniform now has fucking armor

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
No one wears these because giving up your armor is cringe

# Why is this good for game????????????????
More style for security is uncringe and based

# Changelog
🆑
tweak: Shitcurity uniform now has fucking armor
/:cl:

### CODE REVIEW

**Comment by Therandomhoboo** [comment]
It isn't shitcurity if it has armour smh

**Comment by MajManatee** [comment]
i thought nobody wore them because they looked bad

**Comment by PibeCantina** [comment]
The ones that dont wear these because they lose armor are fucking NERDS.

Drip>Armor

**Comment by ShoziOffical** [comment]
> It isn't shitcurity if it has armour smh

you will need protection and drip to be shitsec duh

**Comment by Therandomhoboo** [comment]
> > It isn't shitcurity if it has armour smh
> 
> you will need protection and drip to be shitsec duh

no you just. lethal them first. duhdoi

**Comment by neeshacark** [comment]
i tried to do this a long time ago and they told me to modularize and i never tried again after i closed it, it is finally time for my drip to be a good choice

**Review by Moltijoe — APPROVED** [review]

**Comment by Mqiib** [comment]
Survey says you didnt test this

**Comment by ShoziOffical** [comment]
> Survey says you didnt test this

I forgor

**Pull request merged**
