### PR TITLE
Surrounds Tech Storage with Reinforced Walls

### PR DESCRIPTION
**Pull request by alao3alao3**
### Intent:
Tech storage is no surrounded by reinforced walls.

# Why is this good for the game?
You'd think there'd be more than a standard wall between Joe Antag and the R&D Server, Chem Dispenser, Camera Console, Smoke Machine, Cloning Boards, Microwave, etc.

############ Changelog

:cl:  
rscadd: [box] Adds reinforced walls around tech storage  
/:cl:

### CODE REVIEW

**Comment by patpol4** [comment]
boxstation

**Comment by Mqiib** [comment]
I am formally requesting this pr be put on hold until further notice for reasons to be left undisclosed.

**Comment by alao3alao3** [comment]
I must've violated a UN Peace Treaty

**Review by patpol4 — APPROVED** [review]
Technically this is fine, Jamie will decide your fate.

**Comment by Moja10** [comment]
Oh no not the fuckin microwave!!! I don't like this, there are certain things I don't mind being accessed by the single tear of a wall or airlock, autolathe and microwaves and shit are fine. If there's a particularly problematic board, it should just be moved to the secure storage that exists in tech storage rather than the entire thing being secure. Not to mention that this means that getting into the secure section would require either breaking two R-walls, or two airlocks one of which is reinforced, which is literally harder than the armory to get into.

**Comment by Mqiib** [comment]
if you reinforce the walls you might as well do the door too, otherwise it's mostly pointless as any monkey with a multitool and a crowbar can open an unreinforced door within seconds.

**Comment by JamieD1** [comment]
Might be a good idea to expand secure board storage instead and maybe put those boards in there instead, or just add the cams and server and protolathe board to secure storage.

**Comment by alao3alao3** [comment]
It IS a good idea, someone is going to have to PR it first or settle with this. Someone is also going to have to define what a problematic board is so we don't play the guessing game on what is or isn't.

**Comment by JamieD1** [comment]
> It IS a good idea, someone is going to have to PR it first or settle with this. Someone is also going to have to define what a problematic board is so we don't play the guessing game on what is or isn't.

This wont be merged, im asking you to change your idea to what im suggesting instead,

Excuse my crude drawing: 
image


Problematic boards:
Sec Boards
Teleporter
Medical Records
Intellicard
Reset AI

**Comment by Jarod1200** [comment]
this is gonna severely nerf any antag that doesnt get to go through walls for free. with the exception of the cameras board (which is usually used by sig techs or validhunt hops to spy on people). most tiders just break into engineering or science to print these boards anyway.

**Comment by Georgeur** [comment]
The only 'problematic' boards in there is the RnD console/circuit imprinter, and the chem dispenser board.
I find this unnecessary, the intellicard is fine in there, and so is the reset AI module, both are mostly useless. 
This is a pain in the arse to deal with as an antag, and it's also a pain in the arse to deal with as an atmos tech, who don't have access to technical storage.

**Comment by patpol4** [comment]
Alternative to https://github.com/yogstation13/Yogstation/pull/10446

**Comment by alexkar598** [comment]
Thing in tech storage that powergamy assistants love stealing:
Sec cam(kinda rare)
Chem Dispenser
Insulated Gloves
Multitool(altho they tend to have a multitool before breaking in)
Flash
Intellicard
RND consoles

Teleporter board is not a dangerous board as you need stockparts/bluespace crystals and if you are near a techlathe that prints the parts, you prob have the ability to directly print the board anyways
Medical records have not been used by anyone in eons and IIRC they require medbay access to operate anyways so its not restricted
Reset AI is useless without the upload board and doesnt clear all the laws anyways so a purge and set is always better than a reset

IMO id like to remove the insuls and flash instead as they rarely see any use outside of assistant breaking in and going hurr hurr

**Comment by Jarod1200** [comment]
Removing the flash is bad because this is one of your only sources of those if you get promoted to revhead during the round but after your first revhead already tried flashing the hop and got promptly yeeted.

**Comment by patpol4** [comment]
This problem doesn't exist.

**Comment by alao3alao3** [comment]
so how should we design/reinforce tech storage, based off of gameplay (locking chem dispenser in secure storage since its stolen often) or ick reasons (locking medical records in secure storage) or what

**Comment by alexkar598** [comment]
> 
> 
> This problem doesn't exist.

Which problem?

**Comment by patpol4** [comment]
> Which problem?

the problem of "problematic boards"

**Comment by Georgeur** [comment]
@alexkar598 you have no fucking clue what youre on about and I'll say that as someone who adores you
remove insuls, remove flash, no, fucking no.

**Comment by Georgeur** [comment]
@wejengin2 name me your version of problematic boards and tell me if it doesnt fit mine
you use the term but you have no conscience of its meaning

**Comment by patpol4** [comment]
> @wejengin2 name me your version of problematic boards and tell me if it doesnt fit mine
> you use the term but you have no conscience of its meaning 


All the problematic boards are already in secure storage, the rest are not a problem.
You shouldnt lock boards that someone might use for light antag activity behind more bars, this just reduces the amount of options the antag has, making them even more limited. This will just result in nobody using them ever.

**Pull request closed without merging**
