### PR TITLE
X-ray bolts and lasers can now pass through doors, lockers, and machines

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

If x-ray bolts and lasers can go through reinforced walls they should probably be able to get through a locker or computer

# Changelog

:cl:  
tweak: x-ray bolts and lasers can pass through doors, lockers and machines
bugfix: a door not having glass no longer prevents things from passing through if they're supposed to be able to pass through doors
/:cl:

### CODE REVIEW

**Comment by ReddicusDragon** [comment]
Does this touch weaponry at all?

**Comment by iamthesilly** [comment]
> Does this touch weaponry at all?

It changes two projectiles and fixes the passflags for doors

**Comment by MajManatee** [comment]
you know you can look at the code right red?

**Comment by ReddicusDragon** [comment]
> you know you can look at the code right red?

Projectile code hurts my head. I was verifying that my understanding was correct.

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
