### PR TITLE
Disarm pushes now knockdown instead of paralyze

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

malevolent

#### Changelog

:cl:  
tweak: Disarm pushes now knockdown instead of paralyze
/:cl:

### CODE REVIEW

**Comment by LoliconSlayer** [comment]
Speedmerge RIGHT FUCKING NOW

**Comment by overlord12345** [comment]
uh oh

**Comment by Readystorm546** [comment]
Needs and ided tag

**Comment by maxion12345** [comment]
Not sure how I feel about this
On one hand: ss13 combat is stunbased
On other hand: no more getting beaten half to crit with no ability to defend yourself because of rng

**Comment by Ratvar** [comment]
On one hand: ss13 combat should not be based on stuns
On other hand: first hand

**Comment by Hopekz** [comment]
Nerfing push this much without changing how stuns work is just a lazy ided.
The reason push has been this powerful for so long is because literally everything else in the game 1shot stuns you. We have stun to death combat in this game.
Without pushes you now give the individual with a stun an even more massive advantage plus not everyone is robust enough to act within the window of a knockdown vs a stun.

**Comment by ynot01** [comment]
> The reason push has been this powerful for so long is because literally everything else in the game 1shot stuns you. We have stun to death combat in this game.

you can chain push stuns if you're lucky enough (why reward that?)
you can cuff someone in the time of a single push stun
you can almost reach 3rd level grab in the time of a single push stun (and you will because getting out of grabs is RNG)

**Comment by Hopekz** [comment]
> > The reason push has been this powerful for so long is because literally everything else in the game 1shot stuns you. We have stun to death combat in this game.
> 
> you can chain push stuns if you're lucky enough (why reward that?)
> you can cuff someone in the time of a single push stun
> you can almost reach 3rd level grab in the time of a single push stun (and you will because getting out of grabs is RNG)

Sounds like you're trying to reduce the delay of the stun in your argument so that you can't cuff or full grab..
Unfortunately your proposed changes are changing it from a stun to a knockdown.

**Comment by ynot01** [comment]
> Unfortunately your proposed changes are changing it from a stun to a slip.

those are my proposed changes and i believe it fixes disarm as a whole, disarm rushing will now no longer be a thing, disarms will be used to DISARM someone; you drop their weapon to the ground and then its a race to grab it, potentially turning the tide of battle because of the weapon you had DISARMED them of, not because you stunned them on the ground for 4 seconds and toolboxed them

**Comment by boodaliboo** [comment]
You can rest and it means that you can’t be disarmed

**Comment by ynot01** [comment]
you can still be disarmed when resting i dont understand the issue you're presenting

if you're handicapping your movement then they cant handicap it further?

**Comment by Hopekz** [comment]
> if you're handicapping your movement then they cant handicap it further?

I think the main issue is that a knockdown cannot stop a stun attacker from stunning you similar to how a resting person on the ground can still perform this function.

Yes; I get that you will need to pick up your stun item first but the stunning individual gets a easier time with this as well because their pick-up click is the exact center of their screen every time (where their character is) while the person that stunned them has potentially 9 different squares to effect their accuracy and response time.

I'd honestly be for a much shorter duration of a paralyze rather than a knockdown. 
**I'll let other people put in their opinion because I don't think we can reach a middle ground.**

**Comment by yacabo** [comment]
Does this prevent the victim from moving?

**Comment by Hopekz** [comment]
> Does this prevent the victim from moving?

At this time the proposed changes are a knockdown.
Meaning that if they're standing they will be put into "resting".
No stun.

**Comment by ynot01** [comment]
> I think the main issue is that a knockdown cannot stop a stun attacker from stunning you similar to how a resting person on the ground can still perform this function.

just run away?

**Comment by yacabo** [comment]
>Meaning that if they're standing they will be put into "resting".

Would this mean that they would have to manually press the rest button to stand up again?

**Comment by Hopekz** [comment]
> Would this mean that they would have to manually press the rest button to stand up again?

No.
After the duration of the knockdown (4 seconds at this time) the knocked down individual stands up automatically.

**Comment by Hopekz** [comment]
To anyone confused this is the same effect as slipping for example on water.

**Comment by oklews** [comment]
If we’re changing the system because I ded, we shouldn’t half ass it, stamina based stun batons, just steal it all from TG

**Comment by ynot01** [comment]
> If we’re changing the system because I ded, we shouldn’t half ass it, stamina based stun batons, just steal it all from TG

this is separate from other stun-based combat, this isnt a rework of the system, this just nerfs disarming

**Comment by boodaliboo** [comment]
hard no for me

**Comment by oklews** [comment]
“this is separate from other stun-based combat, this isnt a rework of the system, this just nerfs disarming”

But like, disarms are the most basic form of combat. This one action changes the entirety of combat.

**Comment by AsV9** [comment]
Stuns are bad ok

**Pull request merged**
