### PR TITLE
nerfs chainsword

### PR DESCRIPTION
**Pull request by Amelia0010**
nerfs chainsword from 30 to 20

#### Changelog

:cl:  
tweak: chainsword has been nerfed from 30 force to 20.
/:cl:

### CODE REVIEW

**Comment by ThatLing** [comment]
Reason for nerf?

**Comment by Amelia0010** [comment]
it's 30 damage, which means it's only 4 hits to crit if they have no armour, and as much as an Energy sword, except it's free, and possibly has a ghost inside of it which can also act as life insurance, so they can yell if you get fucked :)

**Comment by Smudged** [comment]
We could make it 16 damage, 1 more than the null-rod because even at 20 it feels like it's still gonna be a first pick for valid hunting chaplains

**Comment by Ratvar** [comment]
@Smudged , nullrods have 18 damage. And there's no reason to make it 20 because it's scythe resprite that talks - it's already better, sneaky Nich. And it's also used by paranormal ERT. And there's also a new PR on TG to nerf it right now, so there's no need in this one at all.

**Comment by ThatLing** [comment]
#1497

**Pull request closed without merging**
