### PR TITLE
[MDB IGNORE] IceMeta

### PR DESCRIPTION
**Pull request by N3D6**
# Document the changes in your pull request

Adds IceMeta, MetaStation but on an ice planet instead.

The goal of this is to add even more uniqueness and map variety, and have this eventually replace the normal Metastation.

Also tweaks Icemoon quite a bit to make mining on IceMeta work.

Map has been tested lots on private servers, no performance issues seem to stick out.

Oh yeah, this also tweaks some maint ruins to prevent them from spawning space instead of ice. A different turf was used to make them spawn space on box/other spacemaps and ice on icemeta

Also makes meta prettier in the form of overhauling the trims from ugly tile decals to modern trimlines.

# Screenshots of stuff

**Podbay**
image

**Updated icemoon mining base**
image

# Spriting

# Wiki Documentation

**Icemoon Basics**

-There are 3 levels, the top level, which is bright and sunny, which houses the station, the middle layer (surface until i change itwhenever i do that), which houses the mining station. This level can spawn ruins, hostile mobs, but isn't super dangerous. The third level is the underground level, which is a little sparse (until I make some more ruins, but I will do it very soon after this is merged I swear), but it also spawns ruins and more hostile mobs. There's some ruins that can only spawn on this level that are considered more "dangerous"

Sentient Beings: Currently the only ghost role on the map is the Innkeeper. You are tasked with running your own inn, and keeping those who require shelter cozy.
There's currently another ghost role being worked on in #19473 which will (i think) be syndicate lavaland repackaged onto icemoon

# Changelog

:cl:  
rscadd: new map, icemeta
rscadd: json and dm files for icemeta
tweak: meta sm and teg templates have been tweaked to suit icemeta
tweak: disables meta in config
tweak: tweaks some maint ruins to make them not break when the map loads
rscdel: spacemeta is DEAD
tweak: some maint ruins with space have been tweaked to suit icemeta
rscdel: kills icemoon maps, they are apart of the main station z-level now
bugfix: Fixes like way too many bugs with planetary maps in general to list
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Your mom. My jorts.

**Comment by N3D6** [comment]
> Your mom. My jorts.

hey you can't say that it's mine

**Comment by ynot01** [comment]
i hope you enjoy map conflicts

**Comment by Moltijoe** [comment]
if this gets in, time to remove regular meta

**Comment by patpol4** [comment]
My baby
https://github.com/yogstation13/Yogstation/pull/10535

**Review by patpol4 — DISMISSED** [review]
The maint ruin spawner is not necessary, as you can just replace space turfs in the ruins with the template turf and it will get filled with the baseturf.

Also im pretty sure this will lag the server to hell but its worth a testmerge

**Comment by N3D6** [comment]
> The maint ruin spawner is not necessary, as you can just replace space turfs in the ruins with the template turf and it will get filled with the baseturf.
> 
> Also im pretty sure this will lag the server to hell but its worth a testmerge

I’ll try and test later but if I remember correctly I had to change the engine templates because the template turf was loading in as space, even though the base turf was snow

**Comment by N3D6** [comment]
@wejengin2 Fixed. Replaced the space on those maps with a different turf that doesn't spawn space and instead spawns the baseturf

**Comment by Yogbot-13** [comment]
#### Test Merge Deployed

##### Server Instance
main

##### Merged By
baiomu

##### Revision
Origin: bee403589de51a2035f0b8a9cd4c28a5d3357ef7
Pull Request: bbdbb6ef94c06708c9fc08cdfb415bf65734bbc2
Server: acf0516109ce5157a863e105203c52eb2760ae96

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Removed

**Comment by Moja10** [comment]
very cool PR, I am almost considering playing roblox with you because this is such a good change

**Comment by Yogbot-13** [comment]
#### Test Merge Deployed

##### Server Instance
main

##### Merged By
baiomu

##### Revision
Origin: 950154b6c666d27343b9fc9e00d5be75b6eca16b
Pull Request: 74f0a50e797889bb8a80549621efba42b6a24df7
Server: 4579eae886f849344562650e4905115f0ac7c9ed

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Updated

##### Server Instance
main

##### Merged By
baiomu

##### Revision
Origin: 8099eac2e52331348d5183acdfe9c29aadbd1923
Pull Request: 74f0a50e797889bb8a80549621efba42b6a24df7
Server: 2fbf5c384a78bff27ea9c9fba280a2ef8b429a14

##### Comment

[GitHub Deployments](https://github.com/yogstation13/yogstation/deployments/activity_log?environment=TGS%3A%20main)

**Comment by Yogbot-13** [comment]
#### Test Merge Removed

**Review by patpol4 — COMMENTED** [review]
I was gone for some time, what's the status on this?

**Comment by N3D6** [comment]
> if this gets in, time to remove regular meta

regular meta is kill

**Comment by N3D6** [comment]
oopsies~!

**Review by cuackles — APPROVED** [review]
art review is required for some reason but i dont see any sprite here so free aprove i guess ????

**Comment by N3D6** [comment]
> 

I accidentally did something  silly and it requested a review from literally everyone

**Comment by AshCorr** [comment]
So it seems like Singularity can infinitely eat the ground on IceMeta which lead to a surprise in this round when the Singularity instantly escaped containment.

https://replays.yogstation.net/?roundid=48696#12336;178.92;160.57;2;null;0.0

I guess this is the reason why this map only spawns with Tesla hah

**Comment by N3D6** [comment]
> So it seems like Singularity can infinitely eat the ground on IceMeta which lead to a surprise in this round when the Singularity instantly escaped containment.
> 
> https://replays.yogstation.net/?roundid=48696#12336;178.92;160.57;2;null;0.0
> 
> I guess this is the reason why this map only spawns with Tesla hah

Yes this is a wontfix, it would simply be too hard / out of scope for me to do and it makes no sense for a black hole to not eat the ground and destroy a planet from the inside out, but I will look into making the singularity generator unobtainable up here

I lied wontfix has been fixed

**Comment by MajManatee** [comment]
singulo eating the planet is scientifically accurate though

**Comment by N3D6** [comment]
> singulo eating the planet is scientifically accurate though
this is ss13 less than half of the shit in this game scientifically accurate

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
