### PR TITLE
You can now go through atmos resin with slowdown

### PR DESCRIPTION
**Pull request by warface1234455**
# Document the changes in your pull request
You can now go through atmos resin with slowdown

# Why is this good for the game?
Screenshot_3

# Testing
i fucking tested this like 20 times, walked in and out...

# Wiki Documentation
You can now go through atmos resin with slowdown
# Changelog

:cl:  

tweak: You can now go through atmos resin with slowdown.
tweak: Changed resin description
/:cl:

### CODE REVIEW

**Comment by Moltijoe** [comment]
i don't know why balance council wanted to weigh in on this one, but alright i guess

**Review by MajManatee — CHANGES_REQUESTED** [review]
image

**Comment by ShoziOffical** [comment]
> image

fuck literally 1984

**Comment by MajManatee** [comment]
image
ill check when im out of prison

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
