### PR TITLE
Miners get research access on skeleton shifts now

### PR DESCRIPTION
**Pull request by N3D6**
# MINER BUFF???? WTF NED!!!!!!!!

 # Document the changes in your pull request

Who else loves playing your favorite job on lowpop and not getting any equipment because there are no scientists?

Me!!!! I do!!!!!

Miners get skeleton crew access now

# Spriting

# Wiki Documentation

# Changelog

:cl:  
tweak: miners get science access on skeleton shifts now
/:cl:

### CODE REVIEW

**Comment by Marmio64** [comment]
what equipment are they really missing out on? They can already get pka upgrades from their vendor and order advanced plasma cutters after doing the mining bounties.

**Comment by N3D6** [comment]
> what equipment are they really missing out on? They can already get pka upgrades from their vendor and order advanced plasma cutters after doing the mining bounties.

not reading allat

**Comment by UltraBigRat** [comment]
> what equipment are they really missing out on? They can already get pka upgrades from their vendor and order advanced plasma cutters after doing the mining bounties.

Pka mods are SEVERELY overpriced for their value in the vendor making them unviable the vast majority of the time, plasma cutters are a fair point though and a skill issue of  miners not wanting to do any cargo

**Comment by Marmio64** [comment]
> > what equipment are they really missing out on? They can already get pka upgrades from their vendor and order advanced plasma cutters after doing the mining bounties.
> 
> Pka mods are SEVERELY overpriced for their value in the vendor making them unviable the vast majority of the time, plasma cutters are a fair point though and a skill issue of miners not wanting to do any cargo

you can also buy pka mods from cargo, its only 350 credits for 3 range mods or 3 damage mods if you would rather spend money than mining points.

**Comment by UltraBigRat** [comment]
> > > what equipment are they really missing out on? They can already get pka upgrades from their vendor and order advanced plasma cutters after doing the mining bounties.
> > 
> > 
> > Pka mods are SEVERELY overpriced for their value in the vendor making them unviable the vast majority of the time, plasma cutters are a fair point though and a skill issue of miners not wanting to do any cargo
> 
> you can also buy pka mods from cargo, its only 350 credits for 3 range mods or 3 damage mods if you would rather spend money than mining points.

this i didnt know, does it also allow cooldown mods to be bought?

**Comment by Marmio64** [comment]
> > > > what equipment are they really missing out on? They can already get pka upgrades from their vendor and order advanced plasma cutters after doing the mining bounties.
> > > 
> > > 
> > > Pka mods are SEVERELY overpriced for their value in the vendor making them unviable the vast majority of the time, plasma cutters are a fair point though and a skill issue of miners not wanting to do any cargo
> > 
> > 
> > you can also buy pka mods from cargo, its only 350 credits for 3 range mods or 3 damage mods if you would rather spend money than mining points.
> 
> this i didnt know, does it also allow cooldown mods to be bought?

yes. Damage, range, cooldown, and even special things like mob AoE, repeater, and resonator blast mods can be bought.

**Comment by SomeguyManperson** [comment]
Give it to engineers

**Review by Moltijoe — APPROVED** [review]

**Comment by iamthesilly** [comment]
wait this got merged???

**Pull request merged**
