### PR TITLE
Pirate flavor text updated

### PR DESCRIPTION
**Pull request by ynot01**
### Intent of your Pull Request

oiGciXW
^ outdated

common issue

#### Changelog

:cl:  
tweak: Pirates are now informed they cannot murderbone
/:cl:

### CODE REVIEW

**Comment by oklews** [comment]
I ded, passionately for this PR regardless

**Comment by Bibby0110** [comment]
It's already in the rules, murderbone bad

**Comment by ynot01** [comment]
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
fuck you travis

**Comment by MegaEmpirical** [comment]
It is in the rules but I'm okay with making clarifying it in game.

**Comment by boodaliboo** [comment]
wait pirates cant murderbone? is it like lings where you need to actually kill them and absorb them but take there stuff and sell them

**Comment by MegaEmpirical** [comment]
They cannot. They need a reason to kill in accordance with their objectives, like most antagonists. So they can kill freely to defend theirself or to take things but they can't go fucking attack evac for no reason and shit.

**Comment by ynot01** [comment]
pirates can sell living beings
emphasis on living
there is no reason to kill anyone that isnt a threat to you as a pirate

**Comment by Hopekz** [comment]
Pirates do not have a murderbone rule at the moment as pirates have been a grey area up to admin discretion.
This needs a council vote as it is something actually new.

**Comment by Alexandria404** [comment]
very nice

**Comment by Hopekz** [comment]
Nevermind I found a very indirect reference to pirates just being under the usual murderboning rules.
Who knew.
https://forums.yogstation.net/index.php?threads/vote-pirate-rules.17191/
Good PR because even I didn't know that with the documentation provided without having to look up a fucking vote

**Comment by MegaEmpirical** [comment]
Doesn't say anywhere in the rules that they can murderbone, murderbone rule applies.

**Pull request merged**
