### PR TITLE
Cargo transit pod now also takes items, crate can be built

### PR DESCRIPTION
**Pull request by warface1234455**
# About PR
I just feel like they could do that too

https://user-images.githubusercontent.com/89688125/183960814-0f9c567d-12aa-4743-8e09-395bfa4ed792.mp4

https://user-images.githubusercontent.com/89688125/183961087-81c9a829-8a05-4eb0-8a4b-843339fee327.mp4

# Document the changes in your pull request
Cargo pod will input items in front of it and output ontop when arrive at destination
Crate will close when being put in cargo pod 
You can now make crate with 2 metal sheets
You can no longer order crate from cargo
Crate export price is reduced to 10cr

# Wiki Documentation
Cargo transit pod will input items in front of it and output ontop when arrive at different location.
Cargo transit pod now close any open crate when inputting
You can now make crate with 2 metal sheets
You can no longer order crate from cargo
Crate export price is reduced to 10cr

# Changelog

:cl:  
tweak: Cargo transit pod now take items with it and output them ontop when arrive at destination
tweak: Cargo transit pod now close any open crate when inputting
tweak: You can now make crate with 2 metal sheets
tweak: You can no longer order crate from cargo
tweak: Crate export price is reduced to 10cr
/:cl:

### CODE REVIEW

**Comment by warface1234455** [comment]
Might have both

**Comment by JamieD1** [comment]
Why would you use this over disposals mailing?

**Comment by warface1234455** [comment]
> Why would you use this over disposals mailing?

first, you cant place another disposal ontop another 
second, doesnt need package wrap
third, for simple and more convenient transportation. For example:**You want to have food tranported from xenobio to kitchen contiously or you wanna transport material to construction zone somewhere inspace** 
~~fourth, for gimmick(You know what i mean)~~

**Comment by JamieD1** [comment]
> > Why would you use this over disposals mailing?
> 
> first, you cant place another disposal ontop another second, doesnt need package wrap third, for simple and more convenient transportation. For example:**You want to have food tranported from xenobio to kitchen contiously or you wanna transport material to construction zone somewhere inspace** ~fourth, for gimmick(You know what i mean)~

My main issue is this is going to promote shitty tubes in the hallways, which annoy everyone else not using them.

**Comment by ShoziOffical** [comment]
> My main issue is this is going to promote shitty tubes in the hallways, which annoy everyone else not using them.

I don't know how this would annoy everyone because i have seen people placing tubes around central hall and there is no sign of anyone complaining from pass rounds i have been on.

**Comment by JamieD1** [comment]
> > My main issue is this is going to promote shitty tubes in the hallways, which annoy everyone else not using them.
> 
> I don't know how this would annoy everyone because i have seen people placing tubes around central hall and there is no sign of anyone complaining from pass rounds i have been on.

I really do not want to encourage people playing unpassable pieces of pipe in the main hallway and cluttering it up even more. Especially when rounds go to shit, I really dont want this making them worse.

**Comment by ShoziOffical** [comment]
> > > My main issue is this is going to promote shitty tubes in the hallways, which annoy everyone else not using them.
> > 
> > 
> > I don't know how this would annoy everyone because i have seen people placing tubes around central hall and there is no sign of anyone complaining from pass rounds i have been on.
> 
> I really do not want to encourage people playing unpassable pieces of pipe in the main hallway and cluttering it up even more. Especially when rounds go to shit, I really dont want this making them worse.

Not unpassable, theres a setting for walkthrough pipe and people rarely use this, i only make this a little bit more connvenient not a big change so its just the same as before

**Comment by ShoziOffical** [comment]
But if people placing unpassable pipe around the station then thats basically just admin issues

**Comment by ShoziOffical** [comment]
okay i think urging here won't get a result, i say testmerge for 3-5 days? so we could see a result

**Comment by JamieD1** [comment]
What about the worry about making mulebots and the delivery system obsolete.

**Comment by ShoziOffical** [comment]
> What about the worry about making mulebots and the delivery system obsolete.

Only cargo can access that

**Comment by Bibby0110** [comment]
Crate nerf for cargo is dumb, agreed with Jamie on the clutter. Use mulebots or disposals. Sorry, neat idea in theory though

**Pull request closed without merging**
