### PR TITLE
Adds king of goats

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860, sabiran
add: Adds king of goats
/:cl:

this thing is fucking overpowered as shit.

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
What the fug is dis refrencing? Ples explain

**Comment by fluffe9911** [comment]
@HomocidlePancakes https://github.com/Baystation12/Baystation12/pull/19052

**Comment by HomocidlePancakes** [comment]
Are goats on bay the same thing as snails on yog? I don't get it

**Comment by fluffe9911** [comment]
I have no idea I just want to use it for the great goat expansion pack I plan on doing

**Comment by Altoids1** [comment]
I don't understand *why* we would need this, but that definitely isn't going to stop me from merging it.

**Comment by monster860** [comment]
Merged into #4673

**Pull request closed without merging**
