### PR TITLE
changes the yellow paramedic jacket to a green paramedic jacket and adds a green emt cap

### PR DESCRIPTION
**Pull request by nesisknesis**
changes it from eyesore green to friendly green

image
image

demodularises it too

#### Changelog

:cl:  Identification
imageadd: yellow paramedic jacket is now green
/:cl:

### CODE REVIEW

**Comment by Nickvr628** [comment]
Not a huge fan of this one, it is too close to the virologist color and I liked the yellow/lime safety jacket from before.

**Comment by athena413** [comment]
ok

**Comment by nesisknesis** [comment]
tried messing about with high saturated green and didnt look great, and the white strips are supposed to be reflective so i guess it works.

also, virologist clothing is white with green highlights, while this is green with white highlights so really were fine.

**Comment by EIB0N** [comment]
Looks solid

**Pull request merged**
