### PR TITLE
Reflector vest buffed, covers arms and groin

### PR DESCRIPTION
**Pull request by ynot01**
ports https://github.com/tgstation/tgstation/pull/47086

## About The Pull Request

Revives [#44267](https://github.com/tgstation/tgstation/pull/44267).
Title, reflect chance going from 40 to 50.
## Why It's Good For The Game

Reflective armor is vastly underused, owing to the fact that if you need it, you're either facing threats that don't fire energy weaponry (security against nukies, cult, traitors, etcetera), or are an antagonist that is most threatened by non-energy weaponry (any antag against shotguns). On the offchance that you DO need it, the random limb hitting chance makes the armor still an awkward choice, with half the shots not hitting the armor at all. This PR slightly helps with that

#### Changelog

:cl: Nemvar, Carlarc, and Bobbahbrown
tweak: reflector vest covers arms, reflect chance from 40 to 50
imageadd: reflector vest has ARM BANDS
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
It's a V E S T change it to a jacket if you want to cover arms actual spoons you is

**Comment by ynot01** [comment]
0BU8Rcu

**Comment by Hopekz** [comment]
If this feature is needed, can spriters work on making the reflective vest look like it covers those areas? In-game the sprite looks like it should only cover the areas it is currently covering.

**Comment by ynot01** [comment]
> If this feature is needed, can spriters work on making the reflective vest look like it covers those areas? In-game the sprite looks like it should only cover the areas it is currently covering.

there was a sprite change

**Comment by Hopekz** [comment]
> > If this feature is needed, can spriters work on making the reflective vest look like it covers those areas? In-game the sprite looks like it should only cover the areas it is currently covering.
> 
> there was a sprite change

Ah. Please disregard my opinion for the time being. I am going to see this sprite when I get back home in a few hours.

**Review by Amelia0010 — CHANGES_REQUESTED** [review]
Rename it to reflective jacket, or reflective armour.

**Review by Amelia0010 — APPROVED** [review]

**Pull request merged**
