### PR TITLE
Improves map rotation by allowing maps to run for at most 3 rounds in a row

### PR DESCRIPTION
**Pull request by redmoogle**
# General Documentation

### Intent of your Pull Request

Ports: https://github.com/tgstation/tgstation/pull/48602

### Why is this change good for the game?

Hopefully this will make people play something else than boxstation

# Changelog

:cl:  
rscdel: Maps will only be allowed to run at most 3 rounds in a row
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Leave the map one alone. People have a right to set a default map so they dont have to vote all the time.

**Comment by redmoogle** [comment]
> 
> 
> Leave the map one alone. People have a right to set a default map so they dont have to vote all the time.

except for the part where it's never changed

**Comment by UselessTheremin** [comment]
> Leave the map one alone. People have a right to set a default map so they dont have to vote all the time.

90% of people never touch it and just have it set to box smh

**Comment by boodaliboo** [comment]
finally

**Comment by swissloaf** [comment]
other maps suck tho

**Comment by redmoogle** [comment]
> 
> 
> other maps suck tho

if they get played they get maintained, otherwise it's not worth the attention

addendum: they can still play box if they want to 4head

**Comment by Marmio64** [comment]
allow people to still mark a map for them to autovote for, but change the default to be no map at all, that way if you dont set a preference and dont vote you wont be counted, but if you do set a preference and forget to vote, you still vote for your favorite map.  Don't know if that is possible even but it'd be better than this.

**Review by SomeguyManperson — APPROVED** [review]
execute order 66

**Comment by athena413** [comment]
> allow people to still mark a map for them to autovote for, but change the default to be no map at all, that way if you dont set a preference and dont vote you wont be counted, but if you do set a preference and forget to vote, you still vote for your favorite map. Don't know if that is possible even but it'd be better than this.

no, it wouldnt be better cause then people would set their preference to box and literally nothing would change

**Comment by alexkar598** [comment]
The default preference is default  and theres no default map. So the default preference is to not vote for any map at all. Those people who just leave it on box did so intentionally, not because they didnt know. The only way this can affect vote results is because people might not notice the vote and have it go through. There is literally 0 reason for this PR.

**Comment by redmoogle** [comment]
> 
> 
> The default preference is default and theres no default map. So the default preference is to not vote for any map at all. Those people who just leave it on box did so intentionally, not because they didnt know. The only way this can affect vote results is because people might not notice the vote and have it go through. There is literally 0 reason for this PR.

Except for that part where were still stuck on box and theres no point in anyone bother to fix map because we apparently have to play box 24/7 because it's the only good map wait sorry, the only map players know exist

**Comment by patpol4** [comment]
I'm ok with this

**Comment by swissloaf** [comment]
By the will of the people, sire!

**Comment by ToasterBiome** [comment]
Yuck. Make people want to play the maps instead of forcing people to play the maps.

**Comment by redmoogle** [comment]
> Yuck. Make people want to play the maps instead of forcing people to play the maps.

This doesnt work and this isnt constructive

People arent going to not play box until they have to accept change something most yog13 players refuse to accept

**Comment by ToasterBiome** [comment]
Nothing wrong with playing box. Again forcing people to play a map is bad and it's there's gonna be a weird drop in population every 3 rounds when we have to play a different map. I think this is worse than just removing the default votes

**Comment by redmoogle** [comment]
> Nothing wrong with playing box. Again forcing people to play a map is bad and it's there's gonna be a weird drop in population every 3 rounds when we have to play a different map. I think this is worse than just removing the default votes

1. Ok
2. Ok? Needs to happen
Also thats pretty false

To sum up dont care eat shit

**Pull request closed without merging**
