### PR TITLE
Dead Simple Mobs now dont slow you down

### LINKED ISSUE #9825: slowdown on dragging dead simplemobs
Wej said to make bug report so: simplemobs cannot be fireman carried and some can't even be aggressively grabbed so unless you have a wheelchair or something on you then the slowdown is unavoidable. remove dragging slowdown for dead simplemobs?

### PR DESCRIPTION
**Pull request by redmoogle**
### Intent of your Pull Request

Fixes: #9825 

#### Changelog

:cl:  
tweak: Dead simple mobs now dont slow down
/:cl:

### CODE REVIEW

**Comment by UselessTheremin** [comment]
finally it isnt tedious to laz injector a lavaland mob

**Comment by JamieD1** [comment]
But they are supposed to be heavy

**Comment by redmoogle** [comment]
Meh, nothing much changes if you can drag a dead simplemob slightly faster

**Review by Amelia0010 — APPROVED** [review]

**Comment by Amelia0010** [comment]
If they're gonna slow you down there should be some way to at least mitigate it, if not completely remove it.

**Pull request merged**
