### PR TITLE
[Meta] Large Station Fixes & Changes

### PR DESCRIPTION
**Pull request by VaelophisNyx**
# Document the changes in your pull request

Almost all of this is done as part of a checklist of actual issues players mentioned

1. Makes the AI sat cameras outside the AI core (all the center hallway cameras and the exterior hallway cameras) all on the ss13 network
2. makes the vault and AI upload cameras on the SS13 network
3. changes the Service Hall to include an autolathe, and doors to the kitchen and botany back rooms (Access matching*), and places a camera in it
4. deletes the seed and nutrivendors outside botany, as well as the table of produce
5. replaced Hydroponics' front windows with Reinforced, matching parity with Box station
6. overhauled hydroponics back room, and shuffled the position of the DNA manipulator and disk drive.
7. Expands the janitor closet by 1x3 tiles to fill the blank space left behind by 4. Also adds a second mop and cart
8. massively expands maint in most of the station
9. FORMER XENOBIO CHANGE ON HOLD TO GET THIS MERGED
10. deletes the Toxins Test Range area and replaces it with a proper Secondary AI Core room
11. shrinks the R&D server room as it no longer must accommodate an AI core
12. expands the whiteship docking hallway so the white ship does not crush the new maints over there
13. expands disposals to include some trash carts and so it can eject past the new maints up there
14. had to move some solar arrays around a little to get new maints to fit comfortably
15. replaced the toxins bomb range with the Box bomb range spawner, for a little variety
16. fixes pixel shifting of some airlock controllers at EVAC
17. removes firelocks from the inner doors of the Toxins mix chamber, and SM engine chamber at request of players
18. removed firelocks from the rad-collector area of the SM engine, matching parity with Box station's SM engine
19. fixes an instance of an unused 1x1 area with a single APC in science maint?? (I checked it was actually just 100% unneeded-)
20. replaced the spawner in the Club that sometimes spawns syndicate throwing cards, with a static russian revolver. We do not hand out free antag gear, last I was told, so...
21. adds spiffles to the clerk's room
22. replaced Pete with a random kitchen animal spawner
23. kills a notice board in Hydro which was always visibly overlapped with a fire extinguisher on the other side of the wall
24. fixes the tcomms agent being unable to reach their donkpockets and microwave
25. removed 2 turrets from AI Upload, bringing it closer to being in line with Box Station's AI Upload chamber

there's probably some stuff I am forgetting, if you see it, call it out and I'll document it here

# Wiki Documentation

Will require extensive updates to YogsMeta screenshots on relevant map pages for Xenobiology, Hydroponics, Janitorial Closet, and anywhere the secondary AI core is mentioned

# Changelog

:cl:  
bugfix: META erased a rogue APC in the AI sat causing it to depower and stay depowered
tweak: META Makes the AI sat cameras outside the AI core all on the ss13 network
tweak: META makes the vault and AI upload cameras on the SS13 network
tweak: META changes the Service Hall to include an autolathe, and doors to the kitchen and botany back rooms, and places a camera in it
tweak: META deletes the seed and nutrivendors outside botany, as well as the table of produce
tweak: META replaced Hydroponics' front windows with Reinforced
tweak: META overhauled hydroponics back room, and shuffled the position of the DNA manipulator and disk drive.
tweak: META Expands the janitor closet by 1x3 tiles & adds a second mop and cart
tweak: META massively expanded maint in most of the station
tweak: META deletes the Toxins Test Range area and replaces it with a proper Secondary AI Core room
tweak: META shrinks the R&D server room as it no longer must accommodate an AI core
tweak: META expands the whiteship docking hallway
tweak: META expands disposals to include some trash carts
tweak: META moved some solar arrays around a little
tweak: META replaced the toxins bomb range with the Box bomb range spawner
tweak: META fixes pixel shifting of some airlock controllers at EVAC
tweak: META removes firelocks from the inner doors of the Toxins mix chamber, and SM engine chamber
tweak: META removed firelocks from the rad-collector area of the SM engine
tweak: META fixes an instance of an unused 1x1 area with a single APC in science maint
tweak: META replaced the spawner in the Club that sometimes spawns syndicate throwing cards, with a static russian revolver.
tweak: META adds spiffles to the clerk's room
tweak: META replaced Pete with a random kitchen animal spawner
tweak: META deleted a notice board in Hydro which was always visibly overlapped with a fire extinguisher on the other side of the wall
tweak: META fixes the tcomms agent being unable to reach their donkpockets and microwave
tweak: META removed 2 turrets from AI Upload
/:cl:

### CODE REVIEW

**Comment by forhiti** [comment]
Not sure if this has been fixed but there's an inaccessible microwave in the tcomm office 
Screenshot_2022-09-02_004710

**Comment by VaelophisNyx** [comment]
thank you for the reminder, will do

**Comment by RG4ORDR** [comment]
6.
I have an issue with this solely because the DNA machine and DISK machine being in the work area is so much of a QOL. Please keep it in the normal spot.

**Review by ToasterBiome — CHANGES_REQUESTED** [review]
Only part I really like is the backroom area for hydro

maints is fine but it don't like the addition above arrivals
too many windows pointing out from maint, the 10x10 have entire sides just windows

Dunno bout the xenobio swap would like @JamieD1 opinion

**Comment by VaelophisNyx** [comment]
Xenobio as a note was done entirely because I had been informed that some shuttles crush it when docking; this layout solves that as jank as it is. Alternate ideas very welcome

**Review by ToasterBiome — APPROVED** [review]
Looks sufficiently good to me, will want Jamie to look at this since it's so thicc

**Comment by VaelophisNyx** [comment]
note: changelog compressed to current size to prevent this one PR from being a wall of changes

**Comment by ToasterBiome** [comment]
I slipped and fell and merged it

**Pull request merged**
