### PR TITLE
[PORT] Welding effects

### PR DESCRIPTION
**Pull request by warface1234455**
# About PR
Welding effect would be nice
Original PR: [Pariah-Station](https://github.com/pariahstation/Pariah-Station/pull/665)  [TauCetiStation](https://github.com/TauCetiStation/TauCetiClassic/pull/6540)

<details><summary>gif</summary>

Recording 2022-07-10 at 23 07 59
</details>

# Wiki Documentation

Welding effects

# Changelog

:cl:  Warface1234455, KillerOrcaCora, axietheaxolotl, redmoogle
rscadd: Welding effects
/:cl:

### CODE REVIEW

**Comment by warface1234455** [comment]
whoopsie typo

**Comment by KillerOrcaCora** [comment]
suggest changing the actual animation color-wise to better fit how our sparks and fires look like.

**Comment by warface1234455** [comment]
> suggest changing the actual animation color-wise to better fit how our sparks and fires look like.

idk how to do that

**Comment by KillerOrcaCora** [comment]
> > suggest changing the actual animation color-wise to better fit how our sparks and fires look like.
> 
> idk how to do that

Alright I’ll just edit it later today for you

**Comment by VaelophisNyx** [comment]
it'd be interesting to see this effect applied to thermite, since its very visually similar to how thermite works IRL

**Comment by warface1234455** [comment]
> > > suggest changing the actual animation color-wise to better fit how our sparks and fires look like.
> > 
> > 
> > idk how to do that
> 
> Alright I’ll just edit it later today for you

are you gonna send

**Review by KillerOrcaCora — APPROVED** [review]

**Pull request merged**
