### PR TITLE
adds pirate space suit to lavaland pirate ruin

### PR DESCRIPTION
**Pull request by boodaliboo**
adam convinced me this is better then a ecutlass 
#### Changelog

:cl:  
rscadd: Added pirate suit and hat that are both spaceproof to lavaland pirate ruin
/:cl:

### CODE REVIEW

**Comment by jcatjmeow** [comment]
Bad changelog

**Comment by boodaliboo** [comment]
> Bad changelog

one sec

**Comment by MegaEmpirical** [comment]
Share the argument as to why one is better than the other.

**Comment by UselessTheremin** [comment]
i am all for as pirate hat is my favorite hat in the game.

**Comment by boodaliboo** [comment]
> Share the argument as to why one is better than the other.

i closed the other

**Comment by MegaEmpirical** [comment]
Not sure how closing something convinces someone to do something.

**Comment by boodaliboo** [comment]
> Not sure how closing something convinces someone to do something.

currently the ruin has jackshit for a reward you have to fight a mob with a rapidly shooting infinite use energy gun in a pressurized space so your pka is ineffective ontop of two melee mobs rushing you

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
