### PR TITLE
flashes knock down instead of stunning

### PR DESCRIPTION
**Pull request by TheRyeGuyWhoWillNowDie**
# flashes knock down instead of stunning

# Wiki Documentation

## flashes knock down instead of stunning

# Changelog

:cl:  
tweak: flashes knock down instead of stunning
/:cl:

### CODE REVIEW

**Comment by neeshacark** [comment]
the hero we need

**Comment by Simplehorror** [comment]
this nerfs a lot of antags in a very significant way

**Comment by Simplehorror** [comment]
also what did flashes do to you? they're incredibly counterable, just get a welding shield or something

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> this nerfs a lot of antags in a very significant way

ok

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> also what did flashes do to you? they're incredibly counterable, just get a welding shield or something

if they're so easy to counter then why do you care if they're nerfed or not

**Comment by Simplehorror** [comment]
because most people won't counter them unless there's revs or something

**Comment by UltraBigRat** [comment]
based pr, while flash protection is easy to get, not having the counter shouldnt immediatly mean hardstun.

**Comment by ynot01** [comment]
flashes will remain useful post merge, disarms are powerful and blinding someone means that A. they can't pick up the weapons they dropped and B. they can't fight back; it will just no longer be a one click win and officers will have to use their batons to arrest

**Comment by Simplehorror** [comment]
aka officers will never use a flash again when they have a baton, you may as well remove it from sec

**Review by MajManatee — APPROVED** [review]
cant wait to flash a heretic and they can still use their hand to knock me 12km away

**Pull request closed without merging**
