### PR TITLE
Infection Event

### PR DESCRIPTION
**Pull request by Bibby0110**
This is the PR for the test merge of the Infection event.

### CODE REVIEW

**Comment by boodaliboo** [comment]
WHEN IS THIS EVENT

**Comment by Bibby0110** [comment]
when Nich wakes up

**Comment by ynot01** [comment]
remove

**Comment by Bibby0110** [comment]
Preparing for Test 2 electric boogaloo next weekend

Den man. 21. okt. 2019 kl. 03.28 skrev ynot01 <notifications@github.com>:

**Comment by alexkar598** [comment]
Isn't this over now

**Comment by alexkar598** [comment]
Apparently not

**Comment by ghost** [comment]
Can we get a date for next event?

**Comment by Bibby0110** [comment]
Satuday at TBA time

**Comment by ghost** [comment]
https://github.com/tgstation/tgstation/pull/45485

**Comment by Bibby0110** [comment]
This has literally nothing to do with that, apart from sharing a name

**Comment by ghost** [comment]
i know

**Comment by Bibby0110** [comment]
Then why did you link it

**Comment by alexkar598** [comment]
ask me to reopen this when its going to be test merged,actually i dont even think you need it to be open for a test merge but w/e

**Pull request closed without merging**
