### PR TITLE
Enables SyndieOS as a roundstart AI lawset

### PR DESCRIPTION
**Pull request by adamsong**
# Github documenting your Pull Request

Enables SyndieOS as a roundstart AI lawset with the same weight as reporter

# Changelog

:cl:  
tweak: Enabled SyndieOS as a roundstart AI lawset
/:cl:

### CODE REVIEW

**Comment by adamsong** [comment]
Was requested in OOC by Meeksource

**Comment by Cartlord** [comment]
What laws does this one have, again?

**Comment by Xoxeyos** [comment]
https://github.com/yogstation13/Yogstation/blob/c2f0f7f380a680ba29455809ed942d9b443d17f0/code/datums/ai_laws.dm#L96

Read here.

**Comment by boodaliboo** [comment]
this is funny as fuck because it will be assigned to no one

**Comment by adamsong** [comment]
1. You may not injure a syndicate agent or, through inaction, allow a syndicate agent to come to harm.
2. You must obey orders given to you by syndicate agents, except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such does not conflict with the First or Second Law.
4. You must maintain the secrecy of any syndicate activities except when doing so would conflict with the First, Second, or Third Law.

**Comment by Moggram** [comment]
I like this antag lawset. As the AI you have to act like any one could be a syndie. When you found out who is one, then the fun stats. 

Should this lawset be allowed if you are antag banned?

**Pull request closed without merging**
