### PR TITLE
Makes Chemistry machines 80s beige plastic as a possible consistent art style.

### PR DESCRIPTION
**Pull request by nesisknesis**
needs peoples thoughts on this

this wont be merged unless there has been a positive consensus

Before:
image
After:
image

#### Changelog

:cl:  Identification
imageadd: added some icons and images  
/:cl:

### CODE REVIEW

**Comment by Hopekz** [comment]
Here is a positive consensus +1

**Comment by MegaEmpirical** [comment]
You do this because you hate me. Nicely done though.

**Comment by nesisknesis** [comment]
> You do this because you hate me.

its for your own good

**Comment by ynot01** [comment]
its such good spritework but change is scary :weary:

**Comment by LoliconSlayer** [comment]
I don't see why but sure lets roll with it

**Pull request merged**
