### PR TITLE
removes the automatic blue alert, and the notification about antags

### PR DESCRIPTION
**Pull request by Amelia0010**
https://github.com/yogstation13/Yogstation/pull/5087 but modern and de-segregated

:cl:
tweak: The station's alert level will no longer automatically escalate to blue
/:cl:

Doesn't touch dynamic.

### CODE REVIEW

**Comment by ynot01** [comment]
bloody brilliant

**Review by jcatjmeow — APPROVED** [review]

**Comment by MegaEmpirical** [comment]
Didn't the council already vote no on this?

**Comment by Amelia0010** [comment]
Oh they did
https://forums.yogstation.net/index.php?threads/vote-remove-auto-blue-alert-and-the-roundstart-report.18754/

I didn't link it on the other PR, so I didn't realize.

**Comment by MegaEmpirical** [comment]
Round two then?

**Comment by alexkar598** [comment]
Its a config flag, get the council to disable it. Theres no need to remove the functionality

**Comment by Tipy1802** [comment]
I like the round start report, gives a nice touch of flavour and roleplay.

I can’t see any reasoning why is this a good thing in the pr description 

There are a few problems that this pr causes that I can think of on top of my head:
1) Blue alert won’t ever be used, the situations where there are signs of a threat but there isn’t one are very few and far between. Traitor, despite being supposed to play out like a murder mystery it very rarely does, either security knows all of the information or non of the information. To use examples, a traitor either successfully killed his victim without anyone even noticing that their colleague went missing or the traitor’s victim successfully yelled out the traitor’s name and location, without leaving room for investigation. Or as it relates to security levels, leaving no room for blue alert just green and red.
2) The knowledge about the existence of certain antags to Command is based on the round start report. I remember admins stating that only Command and security know about changelings and the full extent of their abilities. The roundstart report is what informs Command that changelings may have infiltrated the crew and to NOT inform the wider crew about their existence. Removing this could mean that either command itself doesn’t know about changelings or that the whole crew knows about changelings (having in game reminders of such information is more productive then having people learn about it once they get bwoinked). On top of that vampires are first introduced in the round start report as a new creation of the Wizard Federation meaning there was no prior knowledge of their existence (I haven’t seen any admin ruling on that but vampires are a folk creature so crew knowing what a vampire is makes sense)
3) The roundstart report is a great explanation of all the antagonists, their origins, how they may have found their way on the station. It’s great to have all the antags listed with a briefing on them in game so newer command players have a better idea of the possible threats they may face. On top of that the report is just great worldbuilding, a fine read and great for roleplay and to get yourself immersed 

Now that I have listed why I think the central command report is good for the game it’s time to address why the author of this pr thinks it should be removed but sadly the author doesn’t seem to have answered or even asked the question of why is this pr good for the game in the pr description so I am left with my own guesses. I assume it’s so security can’t random search the whole crew or carry the whole armoury on them. If my guess is correct then I must say that removing the report because of that makes no sense considering such actions are already against server rules and such not a problem.

I apologise if my guess was incorrect but that’s all that I could come up with based on discord conversations and once again the pr description doesn’t say why removing the round start report is good for the game. On top of that I am unsure if this PR removed the report or only the mentions of possible treaths, I think it only removes the mention of possible treaths but if it does remove the whole report then there is the question of how will the crew get informed about station objectives

**Comment by Tipy1802** [comment]
And it got closed while I was typing my wall of text, now I look like a fool

**Pull request closed without merging**
