### PR TITLE
Adds yogsmeta

### PR DESCRIPTION
**Pull request by Ktlwjec**
Found Gray's map changes so I've used them to replace the gateway with the clerk office and add paramed + psych. Redone piping to be layered and go through airlocks. Yogs version of meta - should have done everything correctly but we'll see, it works fine on my testing. Ling said I can as long as I promise to maintain it.

image

### CODE REVIEW

**Comment by Ktlwjec** [comment]
I missed a disposals I'll do that in the morning  and add intercoms (done)

**Comment by MegaEmpirical** [comment]
I see someone did the pipes too.

**Comment by Amelia0010** [comment]
image
image
image

**Comment by MegaEmpirical** [comment]
And I apparently missed that line.

**Comment by thehighwayman** [comment]
nich I swear to god if I had the power I would drop a drone on you

**Comment by thehighwayman** [comment]
also, do intercoms you told me to remind you

**Comment by Ktlwjec** [comment]
i did but thank you

**Comment by Amelia0010** [comment]
@Ktlwjec remember mining medic's stuff. And the sig-tech's stuff plus a spawn for that in case it's ever brought back 🗡

**Comment by MegaEmpirical** [comment]
Oh sweet beloved signal tech. One day.

I like the clerk layout, well done.

**Comment by ThatLing** [comment]
ok now this is epic

**Review by Amelia0010 — APPROVED** [review]

**Comment by ShadowDeath6** [comment]
meta is bad so I’m gonna say this pr is bad

**Comment by Amelia0010** [comment]
we already have meta though, this is just a yogs-specific meta

**Comment by Amelia0010** [comment]
@ThatLing how about this?

**Pull request merged**
