### PR TITLE
BattleRoyale tweaks

### PR DESCRIPTION
**Pull request by Moltijoe**
admeme mode

:cl:  
tweak: tweaked some battle royale loot drop weight
tweak: loot drop crates delete themselves after a delay
/:cl:

### CODE REVIEW

**Comment by Hislyna** [comment]
Can you remove neural overclocker too pls, too op

**Comment by Moltijoe** [comment]
> Can you remove neural overclocker too pls, too op

they're shifted to -5 which is where the too op stuff is, i can move it even past -5 if it's still just that strong

**Comment by Hislyna** [comment]
Cheers boss

**Review by ToasterBiome — APPROVED** [review]

**Comment by ToasterBiome** [comment]
WHY IS THIS TWO PRs

**Comment by Moltijoe** [comment]
> WHY IS THIS TWO PRs

because atomization

**Pull request merged**
