### PR TITLE
Moves a gas meter in brig maint

### PR DESCRIPTION
**Pull request by Ktlwjec**
Moves meter from scrubber pipe to air pipe.
Fixes issue #2713 
image

### CODE REVIEW

**Comment by ThatLing** [comment]
I don't see the issue

**Comment by Ktlwjec** [comment]
frick sake ling they were both attached to the red pipe so i moved one to the left by one tile so one was on the red pipe and one was on the blue pipe

**Comment by thehighwayman** [comment]
it's issue 2713

**Comment by MegaEmpirical** [comment]
This is glorious. You are my hero.

**Comment by ThatLing** [comment]
Sorry, I am colourblind. Could you explain the concept of moving red tiles to me?

**Comment by Ktlwjec** [comment]
I didn't move any red tiles :rofl: :rofl: :rofl: :rofl: :rofl:

**Comment by thehighwayman** [comment]
I am also colourblind. how do we know you moved it to the right coloured pipe?

**Pull request merged**
