### PR TITLE
Replaces slime processor with a surgical set for core removal

### PR DESCRIPTION
**Pull request by SomeguyManperson**
:cl:  
rscdel: Xenobio now has to manually extract slime cores from slimes
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Bad change, just delays and makes it not fun. Doesn't really fix any problem with xeno.

**Comment by Ratvar** [comment]
Real fix would be to remove golden mobs, golems, timestop, methspeed, armors and xenoling, which would be disliked even less because that's all xenobio does: powergames and spawns validhunters/antags/griefers

**Comment by SomeguyManperson** [comment]
The problem with xenobio is how fast they can get to their endgame and deal with multiple different endgame goals at once. When this includes a bunch of speed increasing stuff and the timestop spell but with no antimagic counter it's really easy for xenobio to to end up powerful fast. By restricting the base speed xenobio can get to their endgame state (reproductive extracts still exist) the department is made less powerful without making their rewards less good

**Comment by MonsWTF** [comment]
> The problem with xenobio is how fast they can get to their endgame and deal with multiple different endgame goals at once. When this includes a bunch of speed increasing stuff and the timestop spell but with no antimagic counter it's really easy for xenobio to to end up powerful fast. By restricting the base speed xenobio can get to their endgame state (reproductive extracts still exist) the department is made less powerful without making their rewards less good

10/10 flawed logic. 

Rather than balance the aspects of Xenobio that are considered game-breaking/too powerful, the PR is instead focusing on how to encumber Xenobio with changes that impact every part of the job, rather than tackling the specific parts of the job that are considered overpowered. 

_"They get X content way too fast. Should we adjust the end-game rewards to bring them more in-line? Should we reduce the Mutation % so that acquiring the slime colors they're after takes longer? Of course not, let's make them do even more labor-intensive work!"_ 

Which, in turn, by leaving the 'overpowered' content exactly the way it is, justifies future nerf-related PR's to continue to diminish the job until the point that it is justified to be removed entirely. This PR is building on a harmful precedent and should be seriously reconsidered in regards to how to approach balancing Xenobio.

**Comment by ynot01** [comment]
good change because i hate xenobiologist powergamers lol

**Comment by Ratvar** [comment]
"aspects of Xenobio that are considered game-breaking/too powerful"
those are literally all aspects xenobio players are interested in getting, all of them: fixing them would remove the job (which is a much worse deal overall) because they're not interested in anything that's not broken but sometimes bluespace floors
Reducing mutation chance won't work for as long as red slimes exist, which xenobio mains rush anyway for xenoling... and which would do the same shit this PR does: make xenobio take longer overall

**Comment by MonsWTF** [comment]
> "aspects of Xenobio that are considered game-breaking/too powerful"
> those are literally all aspects xenobio players are interested in getting, all of them: fixing them would remove the job because they're not interested in anything that's not broken but sometimes bluespace floors


This is the flawed logic again, and I don't know why you are supporting it. You are first going to extremes by labeling anyone that plays Xenobio as a 'Powergamer', by defining them as the only group that does the job. You are then refusing to consider removing the game-breaking content by looping back to the extreme _"Since every Xenobio is a powergamer, everyone who plays Xenobio will stop because they can't powergame, dead content."_

And then you digress on your own point by admitting that they get content that isn't powergame related? That's my entire argument that if you get rid of or balance the content that isn't balanced, there is no more room for the powergaming to occur, thus Xenobiology will still get changed, but for the better.

If you don't address the content that's powergaming, you're not actually fixing the problem, just pretending to.

> Reducing mutation chance won't work for as long as red slimes exist, which xenobio mains rush anyway for xenoling

That argument doesn't work when you don't start with Red slimes. Once you have them, yes, you have the mutation potions for enhancing whatever slimes you're boosting to Rainbow for Mind transference,..But what's wrong with that? It satisfies your criteria that you are increasing the time investment required in order to get Rainbow slimes, is it not? It is making it harder to expand to the various colors, which means it will also tackle the "speed" issue you have with Xenobiologists acquiring all the "good" crossbreeds and extracts.

**Comment by Ratvar** [comment]
No, bluespace floors are powergame related because they speed xenobiologists. That they sometimes help others is just an unintended side effect. 

Saying that xenobiologists don't just powergame because there's a *solo* feature that's not aspowergaming they *very rarely do* is funny. It's like saying genetics isn't powergaming based job because they theoretically can share genes/theoretically **must** clone people, or that miners aren't powergaming based job because they also mine.

You can see xenobio players whining in adam's PR that removes methspeed passive, proving this point further
And no, your red slime idea doesn't make it harder to expand xenobio as **whole**, only harder to expand until red slimes. Otherwise you wouldn't suggest it, duh

I myself dislike old surgery method. Why not just remove ability to update slime extractor? This'll remove tediousness while still slowing powercreep down

Entire system of "It takes time, so it must be OP to be worth that time I am afk in a reinforced box" is flawed because it justifies adding OP stuff. And crossbreeding shit was added only because it had so much other shit nobody saw the OP shit, so it was cool as whole. Then nobody 99% of crossbreeding content because it helped other people and not xenobio powergamer.

**Comment by Oakboscage** [comment]
Mane this is just fucking stupid

**Comment by MonsWTF** [comment]
> You can see xenobio players whining in adam's PR that removes methspeed passive, prooving point further

...What? There's no whining there. It's an actually good PR.

> No, bluespace floors are powergame related because they speed xenobiologists. That they sometimes help others is unrelated. Saying that xenobiologists don't just powergame because there's a _solo_ feature that's not powergaming they _very rarely do_ is funny.
> Just like calling everything you disagree with "flawed logic"

It is funny, because these PR's are more focused at nerfing the Job as opposed to nerfing the powergaming itself. I could go down a list of the various things that Xenobio can/could/should make that can benefit people besides themselves, but that's a cultural issue and a balancing issue, as opposed to a job issue, and I'm not going to break down every single item that would have a better purpose if balanced in a PR about the Processor. 

Meanwhile, the PR you mention is specifically targeting the powergaming, like it should be. Flawed logic is logic that is flawed; your defense of this PR doesn't make sense, because you are approaching the issue (Specific Xenobio lategame powers are OP) with the wrong framework (nerf Xenobio **the Job**, rather than nerf Xenobio specific OP results).


> And no, it doesn't make it harder to expand xenobio as **whole**, only harder to expand until red slimes

Reducing Mutation % very much does make it harder to expand the slime mutations as a whole. 
It's still hard to expand unless they spend time upgrading every single slime with a Mutation potion. By the time you reach your first Red slime, you then have to spend at least 2 generations breeding it to have a decent supply of Red extracts, and after that you then would have to collect a good 15+ potions to shove into each slime one at a time to increase their mutation chances for whatever slimes you're missing at T3/T4 (unless you only are mutating a single one to increase those odds), and 

> I myself dislike old surgery method. Why not just remove ability to update slime extractor? This'll remove tediousness while still slowing powercreep down

Getting a single extract per slime is incredibly tedious. It's a pain to try and farm slimes in current meta without getting the Processor upgraded, and I can't imagine that being a 'fun' change compared to other options.

**Comment by Ratvar** [comment]
Nickvr, saratoubi the xenobio mains complain last PR
of course you would mutate 1 slime at a time, why do 4 at once?
Yes, this PR is a bandaid that doesn't fix powergaming, but significantly delays it without disabling entire job until said issues are fixed. And look, even a threat of this PR being merged caused people who don't even play anymore to start merging fixes! Magic

**Comment by drderp3635** [comment]
bad pr, horrible fix, doesn't address any real problems

**Comment by Nickvr628** [comment]
I like this. Merge when

**Comment by Xoxeyos** [comment]
This isn't a good fix.

**Comment by MonsWTF** [comment]
After discussions on both Discord and here, I still fail to see how this PR is actually good for the game, or operates at all in good intentions of balancing Xenobio. As admitted above, this PR is essentially to hold the job itself hostage, and to get other people to code the fixes for them.

**Comment by Alexandria404** [comment]
Forced more routes and forces to make other slimes.
Slows down it all.
Very nice.

**Comment by alexkar598** [comment]
Doesn't fix any issues with xenobio like the super powerful loot at end game and just tries to bandaid the problem in a horrible way

**Pull request closed without merging**
