### PR TITLE
Major wizard academy changes

### PR DESCRIPTION
**Pull request by Marmio64**
This PR changes a shit ton of things, here is the most important first.
1. All player references are completely gone. Trey the lizard was is also unfortunately gone, but he is still in the code.
2. All wizards no longer use spells that can practically kill/completely disable you in one hit. Which means, they don't use magic missile or fireball, they use arcane barrage.
3. There are a special few wizards who carry enchanted rifles. These bullets pierce anti-magic and these 'soldiers' are slightly tougher than other wizards, and they are much more dangerous due to the stamina damage of their rounds. If you kill them though you get to take their gun and shoot it's singular bullet.
4. There is extra loot since the ruin is overall harder especially if you're used to using anti-magic and making the ruin a cake walk. New loot includes: 3 use healing wand in where the tarot cards used to be, rod of Asclepius and safety teleporting wand in the safe in the headmaster's office, and night vision goggles in the cellar. I've also reduced the charges on the fireball wand in the academy by a bit.

This PR is to make it not be impossible to beat the ruin without anti-magic, and make it harder if you do use anti-magic. However, anti-magic still does protect you from the majority of wizards so it is recommended to bring it if you want an easier time. It is also to remove the player references since I don't care for them, even if they do give the ruin some more character.

This is good for the game since it makes the ruin not be so bad and sided towards you REQUIRING anti-magic.

#### Changelog

:cl:  
tweak: Lots of wizard academy changes, including but not limited to the removing of player references.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
unbiased opinion 100% player references were cool

**Comment by jcatjmeow** [comment]
Don't like loot, in general. The loot you did pick is on the tamer side, tho, so idk.

**Comment by Mesalikepie** [comment]
The loot they added is good only on defense/healing. I approve. Good shit

**Comment by alao3alao3** [comment]
we need someone generically robust to trial this and gauge difficulty

**Comment by Hopekz** [comment]
Neat player references suck and start arguments every few months.

**Comment by Moja10** [comment]
I like the gameplay changes but I never really cared about player references.

**Comment by boodaliboo** [comment]
why the rod of snake or however wouldnt that be god awful on this ruin and also doesnt make sense as wizards are hugely not pacifists

**Comment by jcatjmeow** [comment]
> why the rod of snake or however wouldnt that be god awful on this ruin and also doesnt make sense as wizards are hugely not pacifists

they do like to hoard powerful artifacts tho

**Comment by patpol4** [comment]
Bit sad to see the player references go but it's for the better

**Review by patpol4 — APPROVED** [review]
Map seems ok, up to HC if they want the player references removed, I'm fine with it.

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
