### PR TITLE
Mecha QoL changes

### PR DESCRIPTION
**Pull request by warface1234455**
When mecha has armour and you examine it it'll give you a hyperlink to a list of armour and an estimate of its strength. This is to see how strong a mech is compare to others
# Document the changes in your pull request
Mech will now get environment air data, this is for when you want to see what is the current environment air status when having internal tank on
image

Examinating mecha now pop up armor tag list (Requires you to be inside the mech to see the armor tag)
Screenshot_319

# Wiki Documentation
Mech will now get environment air data, this is for when you want to see what is the current environment air status when having internal tank on

Examinating mecha now pop up armor tag list (Requires you to be inside the mech to see the armor tag)

# Changelog

:cl:  
rscadd: Examinating mecha now pop up armor tag list (Requires you to be inside the mech to see the armor tag)
rscadd: Mech will now get environment air data, this is for when you want to see what is the current environment air status when having internal tank on
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
qol changes == powercreep!!!

**Comment by ShoziOffical** [comment]
> qol changes == powercreep!!!

define powercreep here

**Comment by Simplehorror** [comment]
it creeps up on you

**Comment by ShoziOffical** [comment]
> it creeps up on you

cool

**Comment by Simplehorror** [comment]
give me a year and i can give security pulse rifles with powercreep

**Comment by ShoziOffical** [comment]
> give me a year and i can give security pulse rifles with powercreep

go ahead

**Review by JamieD1 — APPROVED** [review]

**Pull request merged**
