### PR TITLE
fake bloodsucker lair 3x3 random maint

### PR DESCRIPTION
**Pull request by Marmio64**
A fake bloodsucker lair. Has a coffin, some of the building materials for a persuasion rack, and a bloodbag. Both terrifies maint goers and gives bloodsuckers some useful stuff if they explore maint and find it.
lair

# Changelog

:cl:  
rscadd: Adds bloodsucker lair random maint 3x3 template
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
needs variations or else people will recognize this instantly, see if you can lower the weight so you can put a bunch without making it the only ruin

**Comment by Marmio64** [comment]
> needs variations or else people will recognize this instantly, see if you can lower the weight so you can put a bunch without making it the only ruin

only idea i'd have for making it weighted would be to assign every other 3x3 template a higher weight, unless you can assign smaller than 1 weight values?
im not exactly sure on how no weight listed chances go, but i'd assume each one would have a 1 weight chance to get chosen? Or if it automatically calculates the percent chance each one has of getting picked and assigns that weight to them.

**Comment by ynot01** [comment]
> only idea i'd have for making it weighted would be to assign every other 3x3 template a higher weight, unless you can assign smaller than 1 weight values?

stationroom templates uses pickweight() which supports non-integer weights

list items without values default to 1 so you can just add `= 0.1` to your variations for example

**Comment by Marmio64** [comment]
lair2
lair3
lair4

including the first, there are now 4 lair variations. Each one has a 0.25 weight so the chance of getting a lair ruin is the same, but each variation has a 25% chance of being chosen pretty much.

**Comment by ynot01** [comment]
Are the coffins anchored?

**Comment by Marmio64** [comment]
> Are the coffins anchored?

no, i can do that too

**Comment by tattax** [comment]
good pr

**Review by ToasterBiome — APPROVED** [review]
lol, lmao even.

**Review by ynot01 — APPROVED** [review]

**Pull request merged**
