### PR TITLE
Hardlight Shotgun Shells

### PR DESCRIPTION
**Pull request by SapphicOverload**
# Document the changes in your pull request

Adds hardlight shotgun shells, a new type of shotgun ammo that does only stamina damage and can be printed at the security or armory lathes.

Does 10 stamina damage per pellet, fires 6 pellets, resolves against energy armor and has negative 40 AP.

Light EMPs triple the spread and heavy EMPs reduce the pellets fired by half.

# Spriting
image
hshell

# Wiki Documentation

Add this to the list of shotgun shells in the guide to combat

# Changelog

:cl:  
rscadd: adds hardlight shotgun shells
imageadd: adds sprites for hardlight shotshells
/:cl:

### CODE REVIEW

**Comment by TheRyeGuyWhoWillNowDie** [comment]
boring and overpowered direct upgrade to rubbershot

**Comment by iamthesilly** [comment]
> boring and overpowered direct upgrade to rubbershot

I don't see how this is overpowered or an upgrade, it does less damage even accounting for the fact energy armor is lower on most things (very high negative AP). The only thing this really has over rubbershot is the ability to not make silicons mad at you for using it.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
> bla bla bla

the only source of energy armor in this game for crew is the reflector vest (which only covers chest and arms) and because this just uses lazily-reskinned bullets this doesn't even work with the reflector vest's special interaction of reflecting energy projectiles

**Comment by iamthesilly** [comment]
> > bla bla bla
> 
> the only source of energy armor in this game for crew is the reflector vest (which only covers chest and arms) and because this just uses lazily-reskinned bullets this doesn't even work with the reflector vest's special interaction of reflecting energy projectiles

NT-USP bullets don't either (which is what this was based on) and most armor has some energy armor, just less of it than bullet armor. Which is why I gave it double the negative AP of normal shotgun pellets.

**Review by cuackles — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
