### PR TITLE
using jaws of life on an airlock shocks you

### PR DESCRIPTION
**Pull request by ToasterBiome**
# Document the changes in your pull request

STOP GREYTIDING

# Changelog

:cl:  
tweak: using jaws of life on an airlock shocks you
/:cl:

### CODE REVIEW

**Comment by wonderinghost** [comment]
no

**Comment by Therandomhoboo** [comment]
Make it instacrit

**Comment by TheRyeGuyWhoWillNowDie** [comment]
BALANCE COUNCIL FLAY THE FLESH FROM HIS BONES

**Comment by ToasterBiome** [comment]
gonna make it do damage instead

**Pull request closed without merging**
