### PR TITLE
Rebalances zombie infections (See: Nerf)

### PR DESCRIPTION
**Pull request by BurgerLUA**
Draft because none of this is tested and needs feedback.

# Document the changes in your pull request

Zombie infection chance is 100%.
Zombies can only infect if the target is horizontal, dead, or grabbed.
Zombies can only infect mobs with valid clients (has a client, not a suicide, not hellbound).
Zombies can eat the brains of mobs that don't have valid clients to heal.

## Justification

Prevents zombies from being unusually smart and mass infecting everyone by hitting them once then leaving to find another target. It's a hilarious tactic but I don't think it's what the founding fathers intended.

# Wiki Documentation

https://wiki.yogstation.net/wiki/Guide_to_races#Zombies

# Changelog

:cl:  BurgerBB
tweak: Zombie infection chance is 100%.
tweak: Zombies can only infect if their target is horizontal or dead or grabbed by them, and they have a valid client. Invalid clients have their brains eaten out for health. 
/:cl:

### CODE REVIEW

**Comment by RG4ORDR** [comment]
Most players already just kill someone they're trying to make into a zombie.
This also makes it way way way way way way easier to prevent zombie infections when their attacks aren't dangerous, so you can just bull rush zombies now and not have to worry about infections unless they actually down or kill you.

Ided PR is Ided

**Comment by TheBombMakerJL** [comment]
>Prevents zombies from being unusually smart and mass infecting everyone by hitting them once then leaving to find another target. It's a hilarious tactic but I don't think it's what the founding fathers intended.

it absolutely is what the founding fathers intended and is a staple in nearly (if not all) every zombie movie

**Comment by Marmio64** [comment]
i mean, hitting them once and then leaving them alone is 90% of the time not going to actually zombify them since they'll just keep downing anti-toxin stuff, you need to actually kill them. Also this is like the one deterrent there is for just kiting zombies with a melee weapon

**Comment by RG4ORDR** [comment]
But by all means make certain armors and clothing ACTUALLY prevent infection - Riot suits, hard suits, bomb suits, bio-suits,durathread.

**Comment by BurgerLUA** [comment]
Zombies can now infect if they've grabbed their target.

**Comment by Hopekz** [comment]
> Zombies can now infect if they've grabbed their target.

You've done nothing to communicate this to the zombie players.
How are they going to know that they need to do specific things to infect?

**Comment by BurgerLUA** [comment]
> > Zombies can now infect if they've grabbed their target.
> 
> You've done nothing to communicate this to the zombie players. How are they going to know that they need to do specific things to infect?

This is what the Wiki is for.

**Comment by Hopekz** [comment]
> This is what the Wiki is for.

People won't read the wiki before they start trying to infect people they will just assume it works how they'd expect to work (a.k.a just attack them).

Zombie isn't an opt-in antag.

**Comment by BurgerLUA** [comment]
> > This is what the Wiki is for.
> 
> People won't read the wiki before they start trying to infect people they will just assume it works how they'd expect to work (a.k.a just attack them).
> 
> Zombie isn't an opt-in antag.

I mean cult, clockwork cult, revs, honestly any conversion antags suffer from this problem so it's not unique.

I can add text explaining how to infect if you want.

**Comment by Hopekz** [comment]
> I can add text explaining how to infect if you want.

It isn't a "if I want"; that is my feedback on this change.
Whether you do something with it or not is up to you but as the PR stands at the moment, in my opinion I do not think it is conveyed well enough to merge vs what we have now.

**Comment by Sniblet** [comment]
I don't think zombies can grab. They don't have free hands.

**Comment by Burger1998** [comment]
this is just leading to the first zombie getting mobbed then the whole midround is over because nobody got infected

**Comment by MajManatee** [comment]
completley unrelated to the current scope i know,

But id REALLY like if zombies couldnt pull things anymore. No more dragging water tanks around to slip people because thats retarded.

**Comment by BurgerLUA** [comment]
> completley unrelated to the current scope i know,
> 
> But id REALLY like if zombies couldnt pull things anymore. No more dragging water tanks around to slip people because thats retarded.

I'll see what I can do.

**Comment by Moja10** [comment]
Zombies should be able to drag things, their balance does not need to be adjusted this drastically in a negative direction.

**Comment by BurgerLUA** [comment]
> Zombies should be able to drag things, their balance does not need to be adjusted this drastically in a negative direction.

I fixed the issue of zombies hitting water tanks in another PR. They can still drag things.

**Comment by Therandomhoboo** [comment]
This just gives noob bait for when zombies happen, not everyone is going to know you have to "grab" to do infection or they have to be dead/laying down. Basically means that people will just rush them with no need to be scared of being hit infected.

This also makes the zombie have to choose between grabbing and hitting so its just pointless.

**Comment by githubuser4141** [comment]
why not add a flavour text that pops up when you bite someone or a timer bar "you must still stand while you infect [person]....", or make it an ability like xenos have that you switch between 'maul' or 'infect'?

**Comment by neeshacark** [comment]
zombies already suck and rarely do anything, why nerf them even more?

**Comment by MajManatee** [comment]
Im suprised to learn the infection chance isnt already 100%.

**Comment by BurgerLUA** [comment]
> Im suprised to learn the infection chance isnt already 100%.

I looked into it and it's 100% for event zombies, for some reason. Gamemode zombies have a different infection chance.

**Comment by BurgerLUA** [comment]
> This just gives noob bait for when zombies happen, not everyone is going to know you have to "grab" to do infection or they have to be dead/laying down. Basically means that people will just rush them with no need to be scared of being hit infected.
> 
> This also makes the zombie have to choose between grabbing and hitting so its just pointless.

There is new text explaining the mechanics.

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Infection chance should just be modified by armor.

Also whats with the dme change?

**Comment by BurgerLUA** [comment]
> Infection chance should just be modified by armor.
> 
> Also whats with the dme change?

It did that automatically.

Also honestly infection chance shouldn't be a chance at all.

**Review by Bibby0110 — CHANGES_REQUESTED** [review]
Unmodularise the items.dm file

**Comment by BurgerLUA** [comment]
> Unmodularise the items.dm file

Will do.

**Comment by Bibby0110** [comment]
Unliked change that just heavily nerf zombies, balance council doesn’t like it either.

**Comment by Moltijoe** [comment]
> Infection chance should just be modified by armor.

it already is

**Pull request closed without merging**
