### PR TITLE
Adds a new ore to Icemoon, Plasma Glacite 

### PR DESCRIPTION
**Pull request by N3D6**
Thanks to @ToasterBiome for the glacite ore and moon anvil sprites 
# Document the changes in your pull request
### **Terrain Changes**
Mineral walls no longer use a different sprite than normal snow walls, so you can't detect ores without a scanner for free anymore. 

**Hardened Ice** (darkness turned off)
Screenshot 2024-09-29 233624
Hardened Ice spawns in groups and is a bit tougher than normal snow to break. Has a higher chance of dropping better minerals.

### **Plasma Glacite**

https://github.com/user-attachments/assets/c54062f9-7109-457f-957f-244c8c1bcd50

Plasma Glacite is the Icemoon equivalent of plasma magmite. You find it inside of hardened ice, and can only harvest it by explosion. Mining it otherwise will not work.

### **Moon Anvil**

Screenshot 2024-09-29 234037

A new subtype of the world anvil that appears on the lowest level of Icemoon. Used to turn glacite ore into glacite upgrade parts. Gives off a Tempered Signal.

### **Glacite Crusher**
A version of the mega kinetic crusher made with plasma glacite.
glacitecrusher

# Why is this good for the game?
Making Icemoon not boring as hell to mine on is always a plus.

# Testing
Has been tested locally, everything works.

# Spriting
**for some reason could not get these screenshots in a great quality, probably looks better on icon bot**
Glacite in a rock

https://github.com/user-attachments/assets/6a130d20-e400-4828-94ee-7edbb0f3ba15

Glacite Sprite (not sure why the quality is so horrible sorry)

https://github.com/user-attachments/assets/1a9be21b-ae67-44ff-9db4-e91ee3d5952f

Moon anvil sprite
anvil2
anvil1

Glacite upgrade parts
gp1 (Active)
gp2 (Inert)

Glacite Crusher showcase

https://github.com/user-attachments/assets/c93b698e-f9ec-4113-8c83-e6783cce7df6

Recharging crusher

https://github.com/user-attachments/assets/d830bdee-850c-41c2-8aae-13f62f6dc8f4

# Wiki Documentation

Yeah this needs to be added to wiki aswell as like everything else icemoon related

# Changelog

:cl: N3D6, Baiomu made the glacite ore sprite
rscadd: code for hardened ice generation
rscadd: Plasma glacite, the icemoon equivalent of plasma magmite
rscadd: The moon anvil, a new subtype of the world anvil that appears on the underground level of icemoon
rscadd: Glacite mega crusher
tweak: makes icemoon mineral walls use the normal snow sprite instead of a special one
mapping: moon anvil ruin
imageadd: sprites for glacite
imageadd: glacite crusher sprites
/:cl:

### CODE REVIEW

**Comment by N3D6** [comment]
We major

**Comment by Mqiib** [comment]
I kinda wish the hardened ice blocks looked a *little* bit different from the snow, like smoother with some cracks in the middle or something

**Review by AMyriad — CHANGES_REQUESTED** [review]
Map needs to be covered in `/area/icemoon/underground/explored` instead of `/area/icemoon/underground` otherwise looks good

Side note though, would love it if you could put some more liquid plasma to make it a tad more interesting, akin to the original world anvil map

**Review by AMyriad — APPROVED** [review]
nice

**Review by cuackles — APPROVED** [review]

**Review by Moltijoe — APPROVED** [review]

**Pull request merged**
