### PR TITLE
Disables the ability to state hacked or ion laws

### PR DESCRIPTION
**Pull request by redmoogle**
# Document the changes in your pull request

Kinda boring when a ion storm happens and its just AI LAWS NOWWWW!!!!! or some AI tries to gamer the system. Just ends up not creating good dynamics. 

So this simply disables the ability to state them unless forced.

## Additionally 
Removes the random ion announcement

# Wiki Documentation

State laws doesnt allow for stating of ion and hacked laws

# Changelog

:cl:  
experimental: Remove the AIs ability to state ion and hacked laws
experimental: Remove random ion announcement
/:cl:

### CODE REVIEW

**Comment by ynot01** [comment]
Make all ion laws silent (no CC announcement) or else this will lead to instant AI lynching

**Comment by Xoxeyos** [comment]
Could you make it so you can default to stating a specific lawset, such as asimov, if you're hacked?

**Comment by JamieD1** [comment]
> Could you make it so you can default to stating a specific lawset, such as asimov, if you're hacked?

^^

**Comment by redmoogle** [comment]
> > Could you make it so you can default to stating a specific lawset, such as asimov, if you're hacked?
> 
> ^^

only problem I see in that is that the captain/rd/whoever could have changed the AI laws and might get sussed out when suddenly its asimov

**Comment by ToasterBiome** [comment]
creating the interesting dynamic of command resetting the AI/killing the ai/carding the ai no matter what now since they'll just lie

**Comment by Bibby0110** [comment]
We feel this promotes weird paranoid behavior towards the AI, with a very real risk of making AI subversions harder, and lynchings more frequent. (At least initially)

**Pull request closed without merging**
