### PR TITLE
Reverts Baton Upgrades - Now back to 2 hit. - Please no more.

### PR DESCRIPTION
**Pull request by JamieD1**
Reverts Baton Upgrades - Now back to 2 hit. - Please no more.

:cl:  
rscdel: Reverts Baton Upgrades - Now back to 2 hit. - Please no more.
/:cl:

### CODE REVIEW

**Comment by ToasterBiome** [comment]
😍

**Comment by Marmio64** [comment]
i liked the idea of upgrades in general though, especially the mindshield pin (to stop people from just killing a seccie loot pinata and no longer requiring antag gear), why axe all of it?

**Comment by JamieD1** [comment]
> i liked the idea of upgrades in general though, especially the mindshield pin (to stop people from just killing a seccie loot pinata and no longer requiring antag gear), why axe all of it?

I do as im told.

**Comment by JamieD1** [comment]
> i liked the idea of upgrades in general though, especially the mindshield pin (to stop people from just killing a seccie loot pinata and no longer requiring antag gear), why axe all of it?

I might ask council about it, but im seriously fed up of all my work being thrown away.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
non-standard firing pins is a solid idea and sad to see it go, 1 hit stun is awful though and deserves to rot

**Comment by maxion12345** [comment]
in conclusion:

baton upgrades? fucking based

one hit batons? cringe

...i might be working on a baton spear. Y'know, for all your caveman spear-chucking security officers. Apes together strong.

**Comment by Smudged** [comment]
> I might ask council about it, but im seriously fed up of all my work being thrown away.

The PR was controversial in the first place with plenty of negative feedback by plenty of folks, 
Sorry that you feel like your work is being thrown away, but it was an expected outcome with the amount of people that didn't like the change.

**Comment by Georgeur** [comment]
Just needs to be reverted for now. At the least so idiots stop arguing about it in public. 
Future pr's about baton upgrades, even a baton upgrade that'd increase its damage, would far better if it was allowed to happen organically. I am genuinely thankful for the groundwork you've set. Like imagine a baton upgrade that'd exchange stam damage with highish burn damage, making it into a lethal melee weapon that sec currently doesnt have one of. It's all not been for naught trust me.

**Review by ToasterBiome — APPROVED** [review]

**Pull request merged**
